### ISSUE TITLE
add ability to specify headerComponent per screen

### ISSUE THREAD

**Issue by ivpusic** [react-community/react-navigation#100]
currently we can do this for navigator, but very useful would be if we can do this for specific screens.

example:
```js
StackNavigator({
  profile: { screen: MyScreen, headerComponent: MyCustomHeader },
})
```

**Comment by ericvicenti** [comment]
This would make sense for `header.mode: 'screen'`, but it would not make sense for a floating header because the flash would look bad.

If we added this feature, the configuration might look like this, so it would be available with `router.getScreenConfig(`

```js
StackNavigator({
  profile: {
    screen: MyScreen,
    navigationOptions: {
      header: (navigation) => ({
        bar: <MyCustomHeader navigation={navigation} />
      }),
    },
  },
})
```

cc @satya164

**Comment by ivpusic** [comment]
makes sense to me. This was removed here https://github.com/react-community/react-navigation/commit/23ca61679dbb50f397ac7a47c553072f551ccbc2. 

Currently I am using ex-navigation and I am rendering custom header component for many scenes. Being able to customize headerComponent only on navigator level won't be enough in many cases. Or let's say it is only possible to do it there, but then custom `headerComponent` should receive `navigationOptions` from scene, so that we can read custom `header` configuration, and render custom header based on it.

**Comment by EmielM** [comment]
The same would apply for `mode`: I have some screens that I would like to use with a `mode: "modal"`. Would that work?

The current alternative seems only to make a complex mess of nested navigators.

**Comment by grabbou** [comment]
I am going to give it a shot today and see if we can get it implemented easy.

**Comment by kennydee** [comment]
any news on that @grabbou ? Thanks

**Comment by grabbou** [comment]
Thanks for a reminder. I was stuck in Header works, but I'll submit my take this weekend.
