### ISSUE TITLE
Enable animation in DrawerNavigator

### ISSUE THREAD

**Issue by prontiol** [react-community/react-navigation#1000]
How can I enable transition animation in a DrawerNavigator?
Instant navigation is nice when performed via drawer sidebar, but sometimes I need to perform navigation via js code in my scene and want it to have transition, just like all other scenes in my StackNavigator.

**Comment by ericvicenti** [comment]
If you like the stack transitions, free to put a `StackNavigator` inside a `DrawerNavigator`.

**Comment by prontiol** [comment]
I already have StackNavigators inside my DrawerNavigator, like this:
```
DrawerNavigator
    --> StackNavigator1
    --> StackNavigator2
```
There is a stack transition when user moves from one scene to another in `StackNavigator1`, but when I navigate to `StackNavigator2` there is not!
Of course I can put everything in one StackNavigator, but how do I make a drawer menu then? It will be pretty useless with a single menu item.

**Comment by douglasjunior** [comment]
@prontiol any solution?

**Comment by prontiol** [comment]
@douglasjunior I solved this by passing around the top navigator reference via `screenProps` and navigating through it, but I believe this was fixed somewhere between beta 7 and 9. Wasn't it?

**Comment by douglasjunior** [comment]
I think I got it wrong. You problem was with Drawer animation. But I want the screen to have animation, just like in the Stack.

**Comment by prontiol** [comment]
@douglasjunior Haha, sorry, it was my fault. I had two similar issues and mistakenly thought I was answering about another one. Please, disregard my previous comment.
Talking about this one: nope, I didn't manage to fix it.

**Comment by douglasjunior** [comment]
@ericvicenti Would you have any suggestions for this case?

**Comment by vandaics** [comment]
Hi, Below is my solution:

My application need to router:
`Splash` » `Login` » `MainScreen ` (has drawer)
 ------------------------├ `Drawer`  » `Screen B`   » `....`
 ------------------------├ `Menu`
  ----------------------------├ `Screen A` » `Screen B`  » `...`
  ----------------------------├ ......
  ----------------------------├`Screen Z`

My Router:

```
const Router = StackNavigator({
    Menu: {
        screen: MainScreen,
        navigationOptions: {
            header: null
        },
    },
    ScreenA: {
        screen: ScreenA
    },
    ScreenB: {
        screen: ScreenB
    },
    ScreenZ: {
        screen: ScreenZ
    }
})

const SlideMenu = DrawerNavigator({
    Home: {
        screen: Router
    }
},{
    drawerWidth: 250,
    drawerPosition: 'right',
    contentComponent: props => <Drawer {...props} />
})

export const AppNavigator = StackNavigator({
    Splash: {
        screen: SplashScreen
    },
    Login: {
        screen: LoginScreen
    },
    Main: {
        screen: SlideMenu
    }
})
```

**Comment by walkerXiong** [comment]
@vandai92 noop, i think what we want is that we can transition in Drawer menu items with animation, just like  all other scenes transition in StackNavigator.

**Comment by evanjmg** [comment]
Any update on this? Animations should work for all navigators

**Comment by allicanseenow** [comment]
Waiting for an answer if animation should be enabled for Drawer Navigator. Putting screens in another nested stackNavigator is pretty awful for the code structure in many scenarios.

**Comment by brentvatne** [comment]
please open a rfc if you are interested in having animations to navigate between different routes in a drawer navigator
