### ISSUE TITLE
navigation.addListener() does not trigger on  closing drawer navigation in class components

### ISSUE THREAD

**Issue by coolusaHD** [react-community/react-navigation#10034]
First of all I'd like to say that the documention on the web is very good and provides all information I need but there are not much of class components examples, which I really can need.

### Current behavior

After closing the drawer nothing happend

### Expected behavior

after closing the console should log a message caused by the  callback function of the listener

### Reproduction

https://gist.github.com/coolusaHD/edf79c5dc97879f6fa6df014f1eaee2e

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.0.4
| @react-navigation/bottom-tabs          | 6.0.7
| @react-navigation/drawer               | 6.1.6
| @react-navigation/material-bottom-tabs | 6.0.7
| @react-navigation/native-stack         | 6.2.2
| react-native-safe-area-context         | 3.3.2
| react-native-screens                   | 3.8.0
| react-native-gesture-handler           | 1.10.3
| react-native-reanimated                | 2.3.0-beta.2
| react-native                           | 0.66.0
| node                                   | v14.16.1
| npm or yarn                            | npm 7.24.0

**Comment by KrifaYounes** [comment]
Hi

Do you have issues with drawer ? 
Sometimes when I close the drawer, I can reopen the drawer outside of the swipeEdgeWidth. (I have a material top bar)
Maybe it's because the drawer not clothing correctly and the listener not called.

**Comment by coolusaHD** [comment]
No the drawer works fine.
it opens on the hamburger menu icon and close after clicking outside of it.
But the trigger dont do anything
