### ISSUE TITLE
TabNavigator onScroll event

### ISSUE THREAD

**Issue by baspellis** [react-community/react-navigation#1003]
I would like to have a transition in the tabbar when the user scrolls from one tab to another. For that I need to track the scroll position? Is there a way to catch the onScroll event of the TabView or something similar?

**Comment by ericvicenti** [comment]
This currently isn't supported, but in theory it would be nice to provide a custom tabBar, which would have access to the `position` Animated.Value, which changes as the user swipes left and right.

In the meantime, this is not on our roadmap, so I'm closing this out.

**Comment by tututututututu** [comment]
need too

**Comment by brentvatne** [comment]
i'd head over to https://github.com/react-navigation/react-navigation-tabs and discuss it there, perhaps open a pr if you are so inclined!
