### ISSUE TITLE
TabBar on top, but below StackNavigator header

### ISSUE THREAD

**Issue by andreialecu** [react-community/react-navigation#1004]
Would it be possible to display the tab bar right below the header bar rendered by the stack navigator?

Similar, more or less to how the Facebook app looks on Android:

![image](https://cloud.githubusercontent.com/assets/697707/24953228/32b848fa-1f83-11e7-8524-6a625c7ff676.png)

Currently, if I create a TabNavigator and put a StackNavigator underneath, the tab bar will be at the top of the screen and the navigation bar will be below it.

**Comment by matthamil** [comment]
Have you tried putting the tabnavigator inside the stacknavigator?

**Comment by ericvicenti** [comment]
Yep, @matthamil's suggestion should work for this

**Comment by andreialecu** [comment]
@matthamil that hides the tabnavigator when navigating to a page using the stacknavigator. I would like to keep the tab bar visible. It's a common pattern on iOS and I would like to bring it to Android, but with a top tabbar rather than a bottom one.

**Comment by bramvbilsen** [comment]
@andreialecu The suggested answer is correct. You can simply insert the stacknavigator into your tabnavigator and hide it from the tabs.

**Comment by JulianKingman** [comment]
This confuses me, shouldn't the header always be at the top? This is how it is in iOS anyway.

**Comment by matthamil** [comment]
We strongly encourage users to write an RFC or open a PR implementing changes that seem beneficial @JulianKingman
