### ISSUE TITLE
`index` option in navigation.reset does nothing

### ISSUE THREAD

**Issue by Maker-Mark** [react-community/react-navigation#10056]
### Current behavior

Calling `navigation.reset` with index 0 or 1 results in the same behavior. The stack always just focuses on the "top" screen, the one at the last index, here index 1 (when zero indexing for this array). I cant find any documentation on what the index actually does, except for in CommonActions (https://reactnavigation.org/docs/navigation-actions/#reset) where the index sets the focusing screen in the stack, but that's not what I'm seeing here. 
```javascript
  navigation.reset({
            index: 0,
            routes: [
               {
                name: 'Profile',
              },
              {
                name: 'Settings',
              }, 
            ],
          })
```

### Expected behavior

The index param set's what screen is focused. Ie index: 1 would 

### Reproduction

https://snack.expo.dev/@markclair/navigation-reset-does-not-effect-focused-screen

### Platform

- [X] Android
- [X] iOS
- [X] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [X] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.0.6
| @react-navigation/stack                | 6.0.11
| @react-navigation/native-stack         | 6.0.0
| @react-navigation/bottom-tabs | NA
| @react-navigation/drawer | NA
| @react-navigation/material-bottom-tabs | NA
| @react-navigation/material-top-tabs | NA
| npm or yarn                            | yarn

**Comment by satya164** [comment]
`index: 0` with 2 routes isn't a valid state object in stack navigator since index is always the last route in a stack. react navigation corrects invalid state and in this case it ignores index.

**Comment by Maker-Mark** [comment]
@satya164 Hmm, so what would be a valid index? I'm having trouble connecting the stack order and index.

Thanks for the quick response! I saw your previous comment on another issue about the index, but it didn't clear this up.

**Comment by satya164** [comment]
> Okay, so I'm confused when it would be necessary to pass an index

If you have a tab or drawer navigator. If you are passing a full state and not partial state (https://reactnavigation.org/docs/navigation-state/) like here.
