### ISSUE TITLE
Nested StackNavigator breaks when navigation is passed as a prop

### ISSUE THREAD

**Issue by pxue** [react-community/react-navigation#1005]
Here's the breaking example:

```jsx
const SecondStack = StackNavigator({
  Index: { screen: Index },
})

const RootStack = StackNavigator({
  Second: { screen: SecondStack },
});

class App extends React.Component {
  constructor(props, context) {
    super(props, context)
    this.customNavStore = new CustomMobxNavStore()
  }

  render() {
    return (
      <RootStack navigation={addNavigationHelpers({
        dispatch: this.customNavStore.dispatch,
        state: this.customNavStore.navigationState,
      })}/>
    )
  }
};
```

It seems like the `RootStack` will treat the `SecondStack` as a screen, and passes only the key and route name to the second stack navigator, ie `{"state":{"key":"Index","routeName":"Index"}}`
This throws an error in `createConfigGetter.js` [here](https://github.com/react-community/react-navigation/blob/master/src/routers/createConfigGetter.js#L42).

**Work-around**:

Currently I'm working around it with a "Splash/place-holder" screen and on will mount, redirects the app to the second stack. 

```jsx
class Splash extends React.Component {
  componentWillMount() {
    resetTo("Second") // navigation action reset
  }
  render() { return null }
}

const RootStack = StackNavigator({
  Spash: { screen: Splash },
  Second: { screen: SecondStack },
});
```
This seem to work as the full state with routes and index are passed to the second navigator. 
```json
{"state":{"type":"Navigation/NAVIGATE","routeName":"Second","index":0,"routes":[{"routeName":"Second","key":"Init"}],"key":"Init0"}}
```

**Comment by pxue** [comment]
Figured out the proper fix, the initial state needs to account for the nested stack routes, ie:

```json
{"index":0,"routes":[{"routeName":"Index","key":"Init"}],"routeName":"Index","key":"Init"}
```

Marking as closed.

**Comment by hjh5696** [comment]
@pxue Can I see how your navReducer looks like? I have exact same situation as yours, but your solution does not seem to work..

**Comment by hjh5696** [comment]
In my case (with your variable names),  the error message "There is no route defined for key Index. Must be one of: 'Second' " appears.

**Comment by pxue** [comment]
I'm using MobX, which let's you override the dispatch behaviour like:

```jsx
  @action dispatch = (action, stackNavState = true) => {
    const previousNavState = stackNavState ? this.navigationState : null;
    return this.navigationState = RootNavigator
        .router
        .getStateForAction(action, previousNavState);
  }
```
so it utilizes the default `getStateForAction` behaviour.
