### ISSUE TITLE
A bit of stack behavior in TabNavigator

### ISSUE THREAD

**Issue by amorokh** [react-community/react-navigation#1006]
Not sure if this is a bug or not but it feels a bit weird to me.

When in a TabNavigator nested in a StackNavigator (like in NavigationPlayground for example), selecting another tab than the initial tab and then executing `goBack()`, the TabNavigator goes back to the initial tab, I expected that `goBack()` would trigger the outer StackNavigator instead. If executing `goBack()` on the initial tab the outer StackNavigator is triggered, regardless if any other tab has been visited before the initial tab.

The DrawerNavigator has the same behavior.

**Comment by ericvicenti** [comment]
This is meant to match the behavior that most Android apps have, but you can disable it with `backBehavior: 'none'`, as [described in this doc](https://reactnavigation.org/docs/navigators/tab#TabNavigatorConfig).

**Comment by amorokh** [comment]
Ok, so it wasn't a bug then, must read the docs better.. I am a iOS user myself with very little Android experience so that's why I don't recognize the behavior. Thanks!
