### ISSUE TITLE
Drawer - progress missing and useDrawerProgress returning undefined

### ISSUE THREAD

**Issue by pocorschi** [react-community/react-navigation#10073]
### Current behavior

Implementing drawer navigator i noticed that the progress is not passed do drawerContent render props. Looking at the actual type shows that it doesn't have any progress property. So the actual documentation cannot be implemented.

![Screenshot 2021-10-23 at 17 51 11](https://user-images.githubusercontent.com/233198/138561275-7f4a719b-f94f-4849-b583-66ea3519027b.png)

Second issue would be using useDrawerProgress() hook, the progress is reported as undefined so no animations are possible.

### Expected behavior

- for progress to be present in DrawerContentComponentProps type
- for useDrawerProgress() to actually return a shared value that can be used for animations.

### Reproduction

installation per getting started guide

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.0.6
| @react-navigation/drawer               | 6.1.8
| @react-navigation/native-stack         | 6.2.5
| react-native-safe-area-context         |
| react-native-screens                   |
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           | 0.66.1
| expo                                   |
| node                                   |
| npm or yarn                            |
| react-native-reanimated | 2.2.3

**Comment by obouchari** [comment]
Having the same issue here! Any updates?

**Comment by bfricka** [comment]
As far as passing the `progress` param, the implementation simply doesn't do it. That's a complete miss:

```tsx
// DrawerView.tsx:189
  const renderDrawerContent = () => {
    return (
      <DrawerPositionContext.Provider value={drawerPosition}>
        {drawerContent({
          state: state,
          navigation: navigation,
          descriptors: descriptors,
        })}
      </DrawerPositionContext.Provider>
    );
  };
```

As far as why the context isn't passed, my presumption is that it's because the ultimate call to `drawerContent()` is a function call rather than rendering a React component. However, I tried wrapping my custom drawer content, so that the function call would return a JSX FC, and it didn't seem to help.

E.g.
```tsx
const DrawerContentWrapped = (p: DrawerContentComponentProps) => {
  const progress = useDrawerProgress()
  //...
}
export const DrawerContent = (p: DrawerContentComponentProps) => <DrawerContentWrapped {...p} />
```
I thought this might work b/c a regular function call, as many things are in this library, is not the same as an actual JSX invocation.

**Comment by satya164** [comment]
The `progress` prop is dropped in favor of the `useDrawerProgress` hook, however the documentation wasn't uptodate. I have updated the documentation and added this to the migration guide: https://reactnavigation.org/docs/upgrading-from-5.x/#the-drawercontent-prop-no-longer-receives-progress-in-its-argument

If `useDrawerProgress` isn't working for you, then please open a new issue with a repro (as far as I see, the repro provided is about `progress` prop, not the hook).

**Comment by am2222** [comment]
@bfricka Can you please share an example how you managed to make it work? I cannot figure out a solution for this. Thanks!

**Comment by renaldodev** [comment]
Is there a solution to this issue? I'd experienced the same issue.
