### ISSUE TITLE
DrawerNavigator Header problem

### ISSUE THREAD

**Issue by snksergio** [react-community/react-navigation#1008]
I'm having difficulty manipulating the Content component header, in which when Drawer appears completely the header is rendered, I would like to remove this header or at least be able to manipulate ... does anyone have a solution?

```
class MainScreenNavigator extends React.Component {
    static navigationOptions = {
        title: "Comanda",
        drawer: () => ({
            label: "Home",
        }),
        header: ({ navigate }) => ({
            right: <Icon name="md-restaurant" />,
        }),
    };

    render() {
        return (
            <View >
               etc..
            </View>
        );
    }
}


const CustomDrawerContentComponent = (props) => (
    <View>
        etc...
    </View>
);


const DrawerMenu = DrawerNavigator ({
    Home: { screen: MainScreenNavigator },
}, {
    contentComponent: CustomDrawerContentComponent,
});


// const
const SimpleApp = StackNavigator({
    Home: { screen: DrawerMenu },
})
```

At run time it looks exactly like this:

![](https://cloud.githubusercontent.com/assets/346214/22697194/abb61362-ed48-11e6-9dac-e0fad266cdc0.gif)

Any suggestions on how to lay the invisible Header or the Drawer on top?

**Comment by ericvicenti** [comment]
It looks like you could fix this by providing `{headerMode: 'none'}` as the config (second argument) of the SimpleApp `StackNavigator`.

Also, the "MainScreenNavigator" name in your code is confusing because it is not a navigator

**Comment by snksergio** [comment]
@ericvicenti thanks for suggestions, I already tried to add {headerMode: 'none'} to MainScreenNavigator, CustomDrawerContentComponent, DrawerMenu and SimpleApp .. but when I add I lose the screen and drawer header, I would not be able to stay with the header on the screen without needing to To make a separate new component to build another header?

**Comment by cernik** [comment]
You should wrap MainScreenNavigator into another StackNavigator

**Comment by nico1510** [comment]
Likes this https://github.com/react-community/react-navigation/issues/469#issuecomment-290640137

**Comment by spencercarli** [comment]
Hi! Since this issue has been quiet for a while I'm going to go ahead and close it. If the issue persists in the latest version of React Navigation please re-open!
