### ISSUE TITLE
How to put TextInput element in the stack navigator header?

### ISSUE THREAD

**Issue by paradigmist** [react-community/react-navigation#1011]
```
static navigationOptions = {
  header: {
      headerTitle: <TextInput
        placeholder="this is placeholder"
        placeholder="search"
        placeholderTextColor= 'gray'
        style={{
          height: 30,
          borderColor: 'white',
        }} />,
  }
}
```

The code above doesn't seem to work.

**Comment by ericvicenti** [comment]
instead of `navigationOptions.header.headerTitle`, you should use `navigationOptions.headerTitle`.

Also you may need to set the width of the TextInput in order for it to appear.

**Comment by paradigmist** [comment]
@ericvicenti It's still not revealing after changing according to your suggestion.static 

```
navigationOptions = {
  headerTitle: <TextInput
        placeholder="this is placeholder"
        placeholder="search"
        placeholderTextColor= 'gray'
        style={{
          height: 30,
          width: 150,
          borderColor: 'white',
        }} />,
}
```

**Comment by mschaeffner** [comment]
Try _title_ instead of _headerTitle_

**Comment by leleofg** [comment]
static navigationOptions = ({ navigation }) => ({
	headerTitle: <TextInput
		textContentType='name'
		placeholder='Search'
		placeholderTextColor='white'
		placeholderStyle={{ marginLeft: 50 }} />
});

this works for me

**Comment by GenoGenoGeno** [comment]
headerTitle: () => {<TextInput style={{ width: '100%', height: 50, fontSize: 20 }} value={'Placeholder'} />}

Use arrow notation.

https://reactnavigation.org/docs/headers/

**Comment by hkn-tr** [comment]
Try:
headerTitle: ()=>{return <TextInput style={{  }} placeholder={'Placeholder'} />}
or 
headerTitle: ()=><TextInput style={{  }} placeholder={'Placeholder'} />
----------------
Usage:

navigation.setOptions({
	//headerShown: false,	
	headerTitle: ()=>{return <TextInput style={{  }} placeholder={'Placeholder'} />}
})
