### ISSUE TITLE
"StackNavigator" documentation for "RouteConfigs" seems to be out of sync

### ISSUE THREAD

**Issue by atshakil** [react-community/react-navigation#1012]
I was working on `StackNavigator`'s `RouteConfig`, and attempted to hide header for a specific screen. According to the documentation, the following code should handle it.

```
StackNavigator(
  {
    S1: {
      screen: S1,
      navigationOptions: {
        headerVisible: false
      }
    },
    S2: {screen: S2},
    ...
  },
  {
    headerMode: "screen"
  }
)
```

But, it didn't work. I found another solution [here](http://stackoverflow.com/questions/42397807/react-navigation-cannot-hide-header-with-nested-navigators),

```
StackNavigator(
  {
    S1: {
      screen: S1,
      navigationOptions: {
        header: {visible: false}
      }
    },
    S2: {screen: S2},
    ...
  },
  {
    headerMode: "screen"
  }
)
```

which is working as expected. (but not mentioned in the documentation)

Is the documentation out of sync?

Note: I'm using master branch.

**Comment by pvinis** [comment]
yea they added that stuff in the documentation like 8 hours ago, and the latest release is still without that. the old way is `header: { visible: false } }` and the new (probably in the next release) is `headerVisible: false`

**Comment by spencercarli** [comment]
This has been updated 😄
