### ISSUE TITLE
TabNavigator: Jank when tabbing between header and header-less tabs

### ISSUE THREAD

**Issue by joncursi** [react-community/react-navigation#1013]
There is a pretty severe jank when navigating between tabs that have different header visibility properties. Consider the following example:

```jsx
const Tabs = TabNavigator({
  HasHeader: { screen: HasHeaderScreen },
  NoHeader: { screen: NoHeaderScreen },
});

// HasHeaderScreen
...
  static navigationOptions = {
    header: {
      visible: true, // headerMode is 'screen'
    },
    tabBar: { ... },
  };
...

// NoHeaderScreen
...
  static navigationOptions = {
    header: {
      visible: false, // headerMode is 'screen'
    },
    tabBar: { ... },
  };
...
```

Navigating between like tabs is fine (no header -> no header, or has header -> has header), but when the tabs have different header visibility characteristics, you can see jank while the layout figures out where the content should be rendered and moves it there.

**Comment by joncursi** [comment]
![out](https://cloud.githubusercontent.com/assets/4974609/24994496/127f2baa-1ff9-11e7-998f-2318415eba3f.gif)

**Comment by ericvicenti** [comment]
Looks like this was also reported here: https://github.com/react-community/react-navigation/issues/1031

**Comment by ericvicenti** [comment]
Ok, this is 3 reports of the same issue within one day! Is this a new bug?

**Comment by joncursi** [comment]
I'm new to react navigation (1 week) so I can't comment on the history of this bug. My gut feel is that this has probably lingered in the codebase since inception and now that the library is getting popular, nitpickers like me are finally coming to log the small details :)

**Comment by Kabangi** [comment]
I have a similar issue. Noticed since the day I started on my project like 2 months ago.

**Comment by lettleprince** [comment]
Same problem +1. I think it can be solved by setting the header visible: true, and setting the header's background the same with the background. But I do not know how to hide the header's bottom line.

**Comment by pfulop** [comment]
@lettleprince    Try setting headerStyle: { elevation: 0 }

**Comment by undershot** [comment]
Anyone have solutions?

**Comment by grabbou** [comment]
CC: @satya164 is this something that could be fixed by your update?

**Comment by satya164** [comment]
I think this is because the transition happens before the header is actually updated.

@grabbou probably

**Comment by joncursi** [comment]
This appears to be fixed on my end in `v1.0.0-beta.9`. Before closing, can we get a dual confirmation from someone else?

**Comment by pfulop** [comment]
@joncursi seconded

**Comment by cherishloveyou** [comment]
v1.0.0-beta.9. not fixed
