### ISSUE TITLE
Stack Navigation: How to Navigate to another Screen from inside a child component

### ISSUE THREAD

**Issue by aswinmohanme** [react-community/react-navigation#1014]
I have a Screen called HomeScreen, which has another component called LoginForm which contains a button. 

What I want is that when the user presses the Button, I want to navigate to another Screen called ImageDownload Screen. 

I am using Stack Navigation.

**Comment by Techdojo** [comment]
I think you need to pass the this.props.navigation object through to your child component as a prop.
