### ISSUE TITLE
Flow types not correctly stripped from release package

### ISSUE THREAD

**Issue by wwwdata** [react-community/react-navigation#1020]
I noticed that the flow types are not correctly stripped out of the javascript files in the release npm package. For example in the `src/NavigationActions` file there is code like this:

```js
const createAction = (type: string) => (payload: object = {}) => ({
  type,
  ...payload,
});
```

this will break any non flow setup. So when I run my react native packager, it works because I guess that also transforms javascript inside the `node_moduels` folder even if the `@flow` annotation at the top is missing? 

But when I run jest tests that import the `NavigationActions` it breaks for me

**Comment by ericvicenti** [comment]
How do you suggest we strip out the flow types? Ideally we would make sure that flow types are exported such that apps which use flow can verify that they use the react-nav API correctly

cc @skevy

**Comment by wwwdata** [comment]
There should be js only files in the repo without any flow types. There also is this ongoing discussion https://github.com/facebook/flow/issues/1996

In there is one easy and good suggestion. Just put transpiled files into a `dist` folder and create a `index.js.flow` file along the normal `index.js` file that points to the files in the `src` folder which are flow annotated and will be preferred by flow over the standard index.js

**Comment by ms88privat** [comment]
@ericvicenti I just installed the latest version from master (because of 0.43.3 issue) and now I believe I'm running into this flow type error:
![image](https://cloud.githubusercontent.com/assets/6705521/25038607/f379d414-20ff-11e7-8799-2b85965b68ef.png)

I have to install 
```
"flow-react-proptypes",
"transform-flow-strip-types"
```
to make it work right now, or ?

**Comment by wwwdata** [comment]
What I also don't understand. This transpiling into `js.flow` files already happens and the files are transpiled into a `lib` and `lib-rn` folder. But inside the `package.json` the `main` entry points to the `src` folder. This is the problem. If this is changed to `lib` everything will work with flow and native js. Should we just change that for the package builds?

**Comment by wwwdata** [comment]
And also, it seems to work for react-native packager because of the `sources` object in the package json?

```json
  "sources": {
    "react-native-v1": "lib-rn/react-navigation.js",
    "web": "lib/react-navigation.web.js"
  },
```

where is this documented? How does this sources work and which package(s) introduced that feature to the package.json just for me to understand this.

**Comment by leethree** [comment]
@wwwdata i'm having the same questions. the flow type in the exported package doesn't really work. flow simply wouldn't check the types because `react-navigation.js` is marked with `@noflow`.
