### ISSUE TITLE
Can't change card background anymore

### ISSUE THREAD

**Issue by navid94** [react-community/react-navigation#1026]
I think that cardStyle prop for StackNavigator has some problems, since before recent update this code worked:

```
var AppNavigator = StackNavigator({
    ...
}, {
    headerMode: 'screen',
    cardStyle: {
        backgroundColor: 'white'
    }
});
```
and now I don't know how to change the background of all screens to white.
I see that at line 169 of [https://github.com/react-community/react-navigation/blob/master/src/views/CardStackTransitioner.js](url) cardStyle prop isn't passed to CardStack component.

**Comment by grabbou** [comment]
Yeah, that is a regression from our recent big update. Thanks for catching it. PR is already waiting.

**Comment by gsaandy** [comment]
+1

**Comment by navid94** [comment]
@gsaandy fix is in master now, i tried and it works.

**Comment by gsaandy** [comment]
tried and working fine with master 👍
