### ISSUE TITLE
gesture regression

### ISSUE THREAD

**Issue by nihgwu** [react-community/react-navigation#1028]
That's a long story, https://github.com/react-community/react-navigation/commit/6aff0ac36617219d1c9cbd06710fe1e7aa6011d6 introduced an issue #527, then was fixed by https://github.com/react-community/react-navigation/commit/11cab8eab62b6ca1c2a0445f30a9d0dc75458e2e, but those two commits introduced more issues when I'm trying to make the PR #828, 

**a**. https://github.com/react-community/react-navigation/blob/master/src/views/TransitionConfigs.js#L32 duration is an invalid props for `Animated.spring`, and the change from `Animated.timing` to `Animated.spring` raised a shadow issue

**b**. https://github.com/react-community/react-navigation/blob/master/src/views/CardStack.js#L220-L221 `velocity` and `bounciness` are invalid props for `Animated.timing`, so `velocity` and `GESTURE_ANIMATED_VELOCITY_RATIO` have no effect at all

**c**. The two changes in **a** and **b** above combined to introduce a issue which leads to a workaround here https://github.com/react-community/react-navigation/blob/master/src/views/CardStackStyleInterpolator.js#L65-L67

**d**. **gesture** support for **modal** is removed https://github.com/react-community/react-navigation/blob/master/src/views/CardStack.js#L261 

actually the workaround in **c** is not needed if we do the following works:
1. revert **a**, `Animated.spring -> Animated.timing`
2. remove redundant animations in `_goBack` https://github.com/react-community/react-navigation/blob/master/src/views/CardStack.js#L208-L232 which mentioned in #828

the workaround introduces a really annoying issue, when we swipe back, we need to wait for the `Animated.spring` animation before the app response to the coming interaction, although is hard to notice after this workaround, but it only hides the shadow, we still need to wait until finish, because this animation is started after the `Animated.timing` in `_goBack`, you can remove the **30px offset** workaround, change the `Animated.spring` to `Animated.timing` in https://github.com/react-community/react-navigation/blob/master/src/views/TransitionConfigs.js#L33 and enlarge the **duration**, then the **none response** will be much obvious

the purpose mentioned in https://github.com/react-community/react-navigation/blob/master/src/views/CardStack.js#L112-L118 doesn't be done in the right way, if we want a smooth swipe back animation, the animation duration should be calculated according to the release position but not a invalid **velocity**

@grabbou @ericvicenti

**Comment by nihgwu** [comment]
I'd like to know your thoughts on this before I make a new PR corresponding #828

**Comment by ericvicenti** [comment]
Thanks for the bug report, it looks like we may have a real issue with the timing as you described in (a) and (b), and also the issue with delayed touch response seems very problematic!

However, I'd like to explain the logic behind the [30px offset that you refer to](https://github.com/react-community/react-navigation/blob/master/src/views/CardStackStyleInterpolator.js#L65-L67). This has nothing to do with timing, actually. The problem is that the view will move fully offscreen but the shadow is still visible. This creates a jarring effect, even when the timing is perfect, because the shadow quickly flashes away as the screen is unmounted.

Also, I think the animation inside of `CardStack._goBack` is not redundant. What happens if you remove it and try swiping back?

If you have ideas on how to fix this without making huge changes, please send a pull request and we will start discussing it. Thanks for your help on this, @nihgwu!

**Comment by nihgwu** [comment]
The animation in `CardStack._goBack` is redundant if we don't need the smooth animation approach I mentioned in the last section, but it was done in a wrong way so I will remove it in the coming PR, the back animation will be done by `CardStackStyleInterpolator` via `navigation.dispatch(NavigationActions.back({ key: backFromScene.route.key }))`

The **30px offset workaround** is unnecessary if you try my steps described above, the PR is on the way

**Comment by nihgwu** [comment]
@skevy Why do you make the change `Animated.spring => Animated.timing`? and when to bring back the gesture support for modal?

**Comment by mcampsall** [comment]
A bit off-topic...

> However, I'd like to explain the logic behind the 30px offset that you refer to. This has nothing to do with timing, actually. The problem is that the view will move fully offscreen but the shadow is still visible. This creates a jarring effect, even when the timing is perfect, because the shadow quickly flashes away as the screen is unmounted.

I was wondering if it would be possible to 'fade' the shadow (reduce alpha to 0) for the last part (maybe the last 30 px) of the transition animation so then the offset would not be required. Might that work?

**Comment by nihgwu** [comment]
@mcampsall see my comments here https://github.com/react-community/react-navigation/pull/1036#issuecomment-294547308
