### ISSUE TITLE
Header rendering delay after changing tab on TabNavigator

### ISSUE THREAD

**Issue by undershot** [react-community/react-navigation#1030]
Maybe I have the same problem with header janking of #1013. 

When I select any tabs on TabNavigator, top header renders with delay. I think, that problem in redux action `Navigation/NAVIGATE`, which dispatches after screen changing and then changes header.

See below:
 
![ice_video_20170413-183904](https://cloud.githubusercontent.com/assets/432682/25008028/ddc31ed4-207b-11e7-983a-5015f59b534e.gif)

How to solve it? Who knows?

```js
// TabNavigator config
{
	animationEnabled: false,
	swipeEnabled: false,
	// lazyLoad: true,
	tabBarPosition: "bottom",
	tabBarComponent: TabView.TabBarBottom,
	initialRouteName: "Search"
}
```

RN@0.43
react-navigation@1.0.0-beta.7
Android API 23

**Comment by ericvicenti** [comment]
Yeah, this looks like the same problem as #1013
