### ISSUE TITLE
[Feature Request] Allow to override HeaderBackButton onPress prop from configuration

### ISSUE THREAD

**Issue by JCMais** [react-community/react-navigation#1032]
I would like to ask for the possibility of adding a new setting to set the ``onPress`` callback of the ``HeaderBackButton``, currently it's hardcoded (see https://github.com/react-community/react-navigation/blob/master/src/views/Header.js#L145) to a function that calls ``goBack`` on the navigation.

**Comment by grabbou** [comment]
At that point you probably want to pass a custom `headerLeft` component. 

`BackButton` is a default implementation of it and we don't intend on allowing its further customisation. At that point,Y you probably want to take [`HeaderBackButton`](https://github.com/react-community/react-navigation/blob/master/src/views/HeaderBackButton.js) and render it yourself.

**Comment by JCMais** [comment]
> you probably want to take HeaderBackButton and render it yourself.

@grabbou Yep, that is exactly what I'm doing. Just wanted to know the possibility of having that added;

All good. :smile:
