### ISSUE TITLE
How to hide parent header?

### ISSUE THREAD

**Issue by timurridjanovic** [react-community/react-navigation#1037]
This is my navigation architecture

StackNavigator -> Splash, Login, Signup, Home
Home -> TabNavigator -> PageOne, PageTwo, PageThree, PageFour
PageOne -> StackNavigator -> PageOneLevelOne, PageOneLevelTwo, PageOneLevelThree

My issue is that when I'm on PageOneLevelOne I see 2 headers. I can hide the child header if I put { header: { visible: false } } in the screen's navigationOptions, but then if I navigate to PageOneLevelTwo, I won't see the back arrow because the back arrow is in the header that I just hid (the child header). I really want to hide the parent header at this point, but I can only turn it off for all screens with headerMode: 'none'.. I don't really want to do that either because I need the headers for the Login and Signup screens.

Not sure what the optimal solution for this is.. Is there a way I can hide the parent header on individual screens?

**Comment by grabbou** [comment]
See #88.

**Comment by kaiyuanneo** [comment]
I have the exact same issue. My understanding as per https://github.com/react-community/react-navigation/issues/88 is that it's still not possible to hide the parent header on individual screens?

**Comment by thisisjaiswal** [comment]
Create a header component suppose <ParentHeader /> 
make it's visibility driven from redux, then this can be controlled from any component.

**Comment by brentvatne** [comment]
https://reactnavigation.org/docs/en/navigation-options-resolution.html
