### ISSUE TITLE
propTypes for navigation prop

### ISSUE THREAD

**Issue by thurt** [react-community/react-navigation#104]
https://reactnavigation.org/docs/navigators/navigation-prop

I like to have propTypes declared in a central location and reused between components for props which are passed around a lot, like the navigation prop.

i'm new to react-navigation, so i'm looking for guidance on what the propTypes for navigation prop might be?

something like?:
```javascript
const navigationType = PropTypes.shape({
  navigate: PropTypes.func.isRequired,
  state: PropTypes.shape({
    routeName: PropTypes.string.isRequired,
    key: PropTypes.string.isRequired,
    params: PropTypes.object.isRequired
  }).isRequired,
  setParams: PropTypes.func.isRequired,
  goBack: PropTypes.func.isRequired,
  dispatch: PropTypes.func.isRequired
}).isRequired;
```

**Comment by grabbou** [comment]
See this file: https://github.com/react-community/react-navigation/blob/master/src/PropTypes.js

**Comment by koenpunt** [comment]
I don't believe the PropTypes in that file are exhaustive. For example, `navigationState` is missing a `params` prop. Or am I missing something?

**Comment by satya164** [comment]
yeah, I think they are out of date. You might wanna look at the flow types instead to get an idea.

**Comment by thurt** [comment]
thanks guys! @satya164 @koenpunt @grabbou 

the flow types [here ](https://github.com/react-community/react-navigation/blob/master/src/TypeDefinition.js) will be very helpful going forward if i run into more issues.

i have refined my definition a little more and i am able to run basic tab and stack navigators without propType warnings so far:
```javascript
const navigationType = PropTypes.shape({
  dispatch: PropTypes.func.isRequired,
  goBack: PropTypes.func.isRequired,
  navigate: PropTypes.func.isRequired,
  setParams: PropTypes.func.isRequired,
  state: PropTypes.shape({
    key: PropTypes.string.isRequired,
    routeName: PropTypes.string.isRequired,
    path: PropTypes.string,
    params: PropTypes.object
  }).isRequired
}).isRequired;
```
