### ISSUE TITLE
How to prevent the android back button from executing action

### ISSUE THREAD

**Issue by valinaga** [react-community/react-navigation#1043]
[Edit]: I found the topic deep in the archive of issues. Look like it's an old issue. So never mind this post. Thanks!

I have a simple case: a stack navigator with home and login.
In home the isLoggedIn si checked and execute `navigate({ routeName: 'login' })`.
I want to prevent users pressing the android back button to go back to home.
How can this be achieved ?
Obviously, only for that case. The android back button must trigger back actions for other cases.
Thanks for help.

**Comment by grabbou** [comment]
See #1081

Also, I believe instead of `disabling` back button, you could change `getStateForAction` of your router to *not* pop scene from stack when certain conditions are met.

**Comment by mayurkothule** [comment]
In my case once user logged in should not route to login page on back action of android button and below logic work for me.(Assuming we are in Login page )

import { NavigationActions } from 'react-navigation';

const resetAction = NavigationActions.reset({
        index: 0,
        actions: [
          NavigationActions.navigate({ routeName: 'Home' }),
        ]
 });
 this.props.navigation.dispatch(resetAction);

and if want to pass params then add 'params' key as below

const resetAction = NavigationActions.reset({
        index: 0,
        actions: [
          NavigationActions.navigate({ routeName: 'Post' }),
        ],
        params:{'id':1,'postId':'1234'}
 });
   
 this.props.navigation.dispatch(resetAction);

**Comment by manojbhardwaj** [comment]
params are undefined  when i try to send params:{'id':1,'postId':'1234'}

**Comment by brentvatne** [comment]
hi there! if this is still a bug can you create a new issue that reproduces the bug on https://snack.expo.io? thanks!
