### ISSUE TITLE
TabNavigator first tab with FlexBox bug on iOS!

### ISSUE THREAD

**Issue by afinal** [react-community/react-navigation#1044]
# when i use TabNavigator,the first tab flex box will have bug,this is my code.
![dfd2cdce-a64e-4ecc-8dce-51ae439d6f13](https://cloud.githubusercontent.com/assets/9390854/25039747/e585d01e-2137-11e7-8e3f-959810ae5ac6.png)
![6548f558-d327-4ec4-bae3-a7e5387167ac](https://cloud.githubusercontent.com/assets/9390854/25039768/0ed1bc94-2138-11e7-9791-b5a3523354be.png)
![599470c6-0924-4844-9308-86b59840bd46](https://cloud.githubusercontent.com/assets/9390854/25039774/1a2674d6-2138-11e7-91ee-854eb2deb062.png)
# the same code will show different result in different tab,this is example
<img width="311" alt="87131a97-c3e9-4bfd-8ff1-b33e06c8fee1" src="https://cloud.githubusercontent.com/assets/9390854/25039830/632fe3ba-2138-11e7-8117-44ff2cc5c58a.png">
<img width="311" alt="420024aa-3056-4379-883f-48c0d301e6dc" src="https://cloud.githubusercontent.com/assets/9390854/25039836/6aadd78c-2138-11e7-874d-b75c17f64da8.png">

# as you know , flex: 1 should seprate the view parent, but the first tab does not show normal,how can i solve this bug

**Comment by grabbou** [comment]
I believe this is a bug with `tab-view` or in `Yoga` (react-native) that should be reported there, @satya164 ?

**Comment by satya164** [comment]
It's likely a bug with ScrollView/Yoga. Can you try to reproduce this in a normal ScrollView?

**Comment by afinal** [comment]
I have solved this bug.please look at this [https://github.com/react-community/react-navigation/issues/1071](url)
