### ISSUE TITLE
Nested Navigations populating the root navigator

### ISSUE THREAD

**Issue by dready** [react-community/react-navigation#1046]
I have a strange Problem which could  be Duplicate by other issues. Since my setup is very complex (although i just thing it's a normal setup if you have a bigger application) i create a new issue.

I was able to solve my problem, but i think it's possible a side effect that it works and maybe some changes in the future might break it. Therefore i present the problem i want to solve and hopefully there will be a possible solution for it or at least the workaround will not be broken in the future.

We have a react native application with deeply nested Navigations. (Stack-Tab-Stack-Tab-Stack... You get the picture). 

I need a Main Header over everthing (because that's the world works), a Main Bottom Tab Navigation and within those Tabs is again a StackNavigation for multiple Screens within this Tab.
In one case i also have another TabNavigation.

Now each of this deepest TabNavigation Screen needs to update the Header with it's title and headerRight Buttons.

The setup that i ended up was that each Screen within that TabNavigation needed to have another StackNavigator. Then i needed a Root StackNavigator which hold the main BottomNavigation TabNavigation. I add a quick example, ignore the Syntax, it's just to get a better picture:

```
root = stackNavigation({
  mainTabs = TabNavigation{
    mainTabA = stackNavigation{ ..},
    mainTabB = stackNavigation{
        ...
        pageFour = TabNavigation({
            pageTabA = stacknavigation{
                Foo: {
                   screen: Foo,
                   navigationoptions: () => {
                      headerRight: (< MyIcon />)
                   }
                }
            },
       },
    }
}, { headerMode: 'none' })
```

Strangely if you add a root Header and hide it and don't setup any StackNavigatorConfig the configuration of the deepest StackNavigation Screen is handover to the top. As soon as any general configuration is done within any of the StackNavigation it's lost.

I ended up setting all style Options and everything for each screen of my application. It works, but is far from a good solution. And it's volatile since i have no idea why it works and it looks like it's a side effect which can be broken at any time.

I really would like to end up with less stacknavigators which i have for the Header Configuration. I would need to be able to configure the main Header within each screen, no matter if it's a tab or a stack.

Maybe a rootNavigationOptions configuration? Just a thought.

If you read to this line, thank you. I really appreciate it.

**Comment by spencercarli** [comment]
Hi! In an effort to reduce the number of open issues I'm closing issues that haven't had any activity in a while.

If you think this should be re-opened please let me know or, if you can, re-open it.

If this is a question please consider asking it on StackOverflow ([react-navigation](https://stackoverflow.com/questions/tagged/react-navigation))

Thanks!

**Comment by manubamba** [comment]
Still an issue
