### ISSUE TITLE
 From tab to another tab When using tabNavigator

### ISSUE THREAD

**Issue by robinstore** [react-community/react-navigation#1049]
from tab to another tab When using tabNavigator，How to get the current tab's screen object，call current tab's screen object's function

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
