### ISSUE TITLE
function for navigationOptions not working

### ISSUE THREAD

**Issue by bhoop** [react-community/react-navigation#1052]
Following the "Hello Mobile Navigation" example here: https://reactnavigation.org/docs/intro/, I reached the last part that uses a function for `navigationOptions` rather than a static object.

When I use this code, my title bar is blank:

    static navigationOptions = ({ navigation }) => ({ title: 'Chat With Someone' });

When I use this code, my title bar has the expected text in it:

    static navigationOptions = { title: 'Chat With Someone' };

My `package.json`, in case it's useful:

	"dependencies": {
		"react": "16.0.0-alpha.6",
		"react-native": "0.43.3",
		"react-navigation": "git+https://github.com/react-community/react-navigation.git#7edd9a7"
	},

**Comment by iEricKoh** [comment]
I have same problem.

**Comment by sibelius** [comment]
@bhoop I've tested against master do you still have the issue?

**Comment by bhoop** [comment]
@sibelius When I change my `packages.json` dependency to:

    "react-navigation": "git+https://github.com/react-community/react-navigation.git"

    I get an error message `Unknown plugin "flow-react-proptypes"...`, which I assumed is related to #923 (the original reason I'm using the specific-commit dependency rather than the npm module). Should I file a separate issue for that?

**Comment by sibelius** [comment]
@bhoop this is fixed on master

**Comment by sibelius** [comment]
try with this commit: https://github.com/react-community/react-navigation/commit/4c55887990e1de2b92d400dafae19fb76c68da6a

**Comment by bhoop** [comment]
@sibelius using that commit does indeed fix the issue, thanks.

**Comment by HugoMatilla** [comment]
I had not the same error, but I wasn't able to show `headerRight` and other screen navigation options using the static object.

```js
static navigationOptions = {
    title: 'Home',
    headerRight: <Text>Info</Text>
  }
```

 As @sibelius points out and  @bhoop confirms, the commit `4c55887` fixes it.

**Comment by seanmadi** [comment]
It looks like for some reason the function has changed from being a function that returns an object, to an object of functions. So this worked for me:
```
static navigationOptions = {
  title: ({ state }) => state.params.name,
};
```

**Comment by jeronnex2** [comment]
I am having the same problem can you tell me how to use the commit in order to fix this?
