### ISSUE TITLE
Header.js Module does not exist 

### ISSUE THREAD

**Issue by lzctbyong** [react-community/react-navigation#1054]
Platform: Android
React-Native Version : 0.43. 3
React Version:  16.0.0-alpha.6 
React-navigation Version : 1.0.0-beta.7

bundling: UnableToResolveError: Unable to resolve module `react/lib/ReactComponentWithPureRenderMixin` from `D:\CodeRoom\ReactNative\Temple\node_modules\react-navigation\src\views\Header.js`: Module does not e
xist in the module map or in these directories:
  D:\CodeRoom\ReactNative\Temple\node_modules\react-navigation\node_modules\react\lib
,   D:\CodeRoom\ReactNative\Temple\node_modules\react\lib

**Comment by nihgwu** [comment]
This has been resolved in master, you can just remove the relative lines

**Comment by lzctbyong** [comment]
OK，thanks
