### ISSUE TITLE
Two tab container nesting will cause the inside of the view can not be displayed properly

### ISSUE THREAD

**Issue by fangkyi02** [react-community/react-navigation#1058]
![qq20170416-010119](https://cloud.githubusercontent.com/assets/3389652/25065358/268fb94e-2241-11e7-80a0-7c59c0b60b70.png)
![qq20170416-010309](https://cloud.githubusercontent.com/assets/3389652/25065359/2693e1a4-2241-11e7-9a63-f67750df846f.png)

Are implemented using your controls and do not use other tab third party components

I tried to add the following attributes in tabitem all of which still can not be displayed

Flex:1,
Position:'absolute',
Left:0,
Top:0,
Right:0,
Bottom:0,

---Baidu translate---

**Comment by Crazy-Ivan** [comment]
I guess I have the same issue. I have TabNavigator inside TabNavigator. 

```js

const SearchNavigator = TabNavigator({
    Search: {
        screen: Search
    },
    Config: {
        screen: Config
    }
}, {
    tabBarComponent: TabView.TabBarTop,
    tabBarPosition: 'top'
});

export const TabBarNavigator = TabNavigator({
    Home : {
        screen: Home,
        navigationOptions: {
            tabBar: {
                icon: Tab(HOME_ICON)
            }
        }
    },
    Search: {
        screen: SearchNavigator,
        navigationOptions: {
            tabBar: {
                icon: Tab(SEARCH_ICON),
            }
        }
    }   
}, {
    tabBarComponent: TabView.TabBarBottom,
    tabBarPosition: 'bottom'
});
```

On IOS works ok, but for Android not so much. Android version doesn't render initial view unless I click on a tab. It looks like a bug :(

**Comment by esseak** [comment]
+1

**Comment by esseak** [comment]
Hi @fangkyi02 , Check out these two issues: #823 and #662 .

**Comment by grabbou** [comment]
Fixed in #1234

**Comment by fangkyi02** [comment]
![image](https://cloud.githubusercontent.com/assets/3389652/25433972/0e71e7fe-2abd-11e7-9acf-7fc353e79e90.png)

RN version 0.43.3
react navigation GitHub version of the latest version of the synchronization

I am now set up after this can really show up
But you can't slide as long as you switch to the tab page
If I open the slide, I can't show the contents

**Comment by xiaozhouwu** [comment]
@fangkyi02 Thanks, it solves my problem. As matter of fact, "swipeEnabled: false; animationEnaabled: false" is enough.

**Comment by morksinaanab** [comment]
Just as extra info. I have the same problem in Android. However when i rotated the device it does become visible. Apparently that does force some sort of redraw.
