### ISSUE TITLE
TabNavigator: Customize onPress functionality for custom tabs?

### ISSUE THREAD

**Issue by joncursi** [react-community/react-navigation#1059]
Right now the TabNavigator has full control of the `onPress` functionality of what happens when you tap on a tab. All you can really do is specify a screen, and the TabNavigator takes care of the rest.

```jsx
const Tabs = TabNavigator({
  ...
  SomeScreen: { screen: SomeScreen },
  ...
});
```

What if I want to render a tab, but with custom `onPress` functionality rather than pushing or jumping to a new screen? Consider yelp's "Add" tab:

![img_3575](https://cloud.githubusercontent.com/assets/4974609/25065787/a0ef58ec-21e3-11e7-8bc8-4a4003f47612.PNG)

Tapping the "+" doesn't push a new screen or jump to a new tab. It simply renders an overlay over the existing screen.

![img_3574](https://cloud.githubusercontent.com/assets/4974609/25065837/78f43e56-21e4-11e7-975c-bb0f665e9c64.PNG)

Is it possible to reacreate the Yelp example with the existing TabNavigator API? I've been scratching my head over this. Thanks!

**Comment by joncursi** [comment]
Reddit is another example:

![img_3576](https://cloud.githubusercontent.com/assets/4974609/25066195/bbfb8e44-21ed-11e7-871f-2b22b13ae9c8.PNG)

**Comment by guoliang1206** [comment]
hi man, did you find some way to handle the custom events of tabs on TabNavigator?

**Comment by joncursi** [comment]
Not yet, I'm also waiting to hear from the authors on possible ways we can achieve this

**Comment by mehtamanan** [comment]
Me too!

**Comment by augustoabreu** [comment]
I'm trying to a similar behaviour #1227

**Comment by ofairfoul** [comment]
@joncursi you can create your own tab bar component quite easily. start by copying the source from [TabBarBottom.js](https://github.com/react-community/react-navigation/blob/31ee86ad5c826c0240d50ae2098ddd5ab6a46ea9/src/views/TabView/TabBarBottom.js) 
Here is a super-stripped down version I created for my project, doesn't support animation, swipe or tab labels.
You can insert your own custom center button into the view hierarchy here.
```js
import React from 'react';
import { View, StyleSheet, TouchableWithoutFeedback } from 'react-native';

const styles = StyleSheet.create({
  tabbar: {
    height: 49,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopColor: colors.border,
    backgroundColor: colors.bgLightGrey
  },
  tab: {
    alignSelf: 'stretch',
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center'
  }
});

const TabBar = React.createClass({
  render() {

    const {
      navigation,
      renderIcon,
      activeTintColor,
      inactiveTintColor,
      jumpToIndex
    } = this.props;

    const {
      routes
    } = navigation.state;

    return (
      <View style={styles.tabbar}>

        {routes && routes.map((route, index) => {
          const focused = index === navigation.state.index;
          const tintColor = focused ? activeTintColor : inactiveTintColor;
          return (
            <TouchableWithoutFeedback
              key={route.key}
              style={styles.tab}
              onPress={() => jumpToIndex(index)}
            >
              <View style={styles.tab}>
                {renderIcon({
                  route,
                  index,
                  focused,
                  tintColor
                })}
              </View>
            </TouchableWithoutFeedback>
          );
        })}

      </View>
    );
  }
});

export default TabBar;
```

and in your tabs navigator definition

```js
const TabsNavigator = TabNavigator(
  {
      ...routeConfig
  },
  {
    tabBarComponent: TabBar,
    tabBarPosition: 'bottom'
  }
);
```

**Comment by valeriaabo** [comment]
So what @ofairfoul posted should work? Im looking exactly for this 😮

**Comment by valeriaabo** [comment]
@joncursi Did you get to recreate the yelp Example? Please IM Stucked!

I used @ofairfoul code but my middle button that opens more options is not overlaying.

**Comment by joncursi** [comment]
No, I haven't gotten it yet either :/

**Comment by ericlewis** [comment]
have you checked where that overlay is in your view hierarchy? if its anything like other overlays, you need to actually do this elsewhere than the tab bar itself or utilize zIndex.

**Comment by javidjamae** [comment]
+1 (so I can search for this later)...

**Comment by spencercarli** [comment]
This use case should be solved by #1335 (will be merging soon)

**Comment by fqueiruga** [comment]
+1

**Comment by kelset** [comment]
Pinging OP @joncursi since this issue is quite old and related to an old version of the lib (we merged #1335 so `beta.13` has this feature). If no answer I'll close in 7 days.

**Comment by kelset** [comment]
Hi there @joncursi ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue (especially if it's a bug report) please open a new issue that uses the new Issue Template to provide some more details to help us solve it.

**Comment by anuragfexle** [comment]
> No, I haven't gotten it yet either :/

Hey @joncursi did you get the solution for this? Please help if you resolve the issue I am tucked here. I want to show exactly the same UI on middle button click.
