### ISSUE TITLE
Official documentation does not apply to version fetched from NPM

### ISSUE THREAD

**Issue by przemkow** [react-community/react-navigation#1060]
could you update package version on NPM? 
in official docs you can find code like this with already implemented flat options: 
```
class ProfileScreen extends React.Component {
  static navigationOptions = ({ navigation, screenProps }) => ({
    title: navigation.state.params.name + "'s Profile!",
    headerRight: <Button color={screenProps.tintColor} {...} />,
  });
```
while in your app you still need to write code like bellow because version fetched from NPM does not include flat options feature.
```
class ProfileScreen extends React.Component {
  static navigationOptions = {
    title: navigation.state.params.name + "'s Profile!",
    header: (navigation) => ({
      left: <Button color={screenProps.tintColor} {...} />,
    })
  };
```

**Comment by henjing** [comment]
Indeed it is

**Comment by DiogoAbu** [comment]
With [this commit](https://github.com/react-community/react-navigation/commit/93976d358e27580e568ef016f820dc0253423aa7) they changed the docs.
You can change your package json to fetch directly from git (7165efc is the latest commit):
`"react-navigation": "git+https://github.com/react-community/react-navigation.git#7165efc",`

**Comment by przemkow** [comment]
@DiogoAbu that's exactly what i did, i even left the comment under this commit. 
The problem was that it took me some time to get why official dosc isn't working with my app so it might discourage new users from using the lib :)

**Comment by grabbou** [comment]
We should probably version the website. Not sure if it's possible now, but since we are using similar engine to `react-native`, it should be fairly doable.

Going to put it on a `todo` list.

Alternatively, we should consider deploying website on release rather than on master commit.

**Comment by akrigline** [comment]
Chiming in here, this really threw me off. Documentation being wrong is a big hurdle for people trying this lib out to jump. That commit changelog was super helpful @DiogoAbu.

So is the website's docs more Up to date than the stuff that's in NPM?

**Comment by grabbou** [comment]
Yes, currently website follows master API, which we are likely to change as
it's confusing.

**Comment by do-n-khanh** [comment]
as a new react-native user, this problem almost discourages me to continue to learn react. Luckily, someone on StackOverFlow sent me the link to this page. Please update package version on npm

**Comment by grabbou** [comment]
Apologies for the inconvenience. This release is special in a sense that we
have shipped few breaking changes hence painful website differences.

I'll try to solve this problem as soon as possible.

**Comment by paradigmist** [comment]
Any updates?

**Comment by DiogoAbu** [comment]
@paradigmist [this seems to work](https://github.com/react-community/react-navigation/issues/1085#issuecomment-296195090)

**Comment by spencercarli** [comment]
Hi! Since this issue has been quiet for a while I'm going to go ahead and close it. If the issue persists in the latest version of React Navigation please re-open!
