### ISSUE TITLE
Disable swipe back action in stack navigation (react-navigation). 

### ISSUE THREAD

**Issue by tungbt-2-3-1994** [react-community/react-navigation#1063]
I have 2 screens A and B in stack navigator. When i click button on screen A, it will navigate to screen B. On screen B, I want to disable the swipe back action. I just want that when i press left button in navigation, i will navigate back to screen A.
Thanks in advance!

**Comment by narendrashetty** [comment]
@tungbt-2-3-1994 Did you find the solution for it?

**Comment by tungbt-2-3-1994** [comment]
@narendrashetty 
In navigationOptions, you add 
/*
cardStack: {
                gesturesEnabled: false,
            },
*/
It helps for me.

**Comment by anton6** [comment]
Example of route definition with gesturesEnabled: false

```
Example: {
    name: 'Example Screen',
    screen: ExampleView
    navigationOptions: {
        gesturesEnabled: false,
    },
},
```

**Comment by bobzhen** [comment]
@anton6 this is brilliant

**Comment by agersoncgps** [comment]
Any way to set this globally for all routes?

**Comment by jlc467** [comment]
@agersoncgps [StackNavigator takes navigationOptions](https://reactnavigation.org/docs/navigators/stack#StackNavigatorConfig) representing the "Default navigation options to use for screens"

Example:
```
const RootStackNavigator = StackNavigator(
  {
    Login: {
      screen: LoginScreen
    },
    Main: {
      screen: MainDrawerNavigator
    }
  },
  {
    index: 0,
    initialRouteName: 'Login',
    headerMode: 'none',
    navigationOptions: {
      gesturesEnabled: false
    }
  }
);
```

**Comment by rodrix** [comment]
Someone can tell me whether {gesturesEnabled: false} works for DrawerMenu? I've tried, but without success. Thanks.

**Comment by hedza06** [comment]
@anton6 thanks man! You made my day!!! <3

**Comment by eflatz** [comment]
gesturesEnabled didn't work for ("react-navigation": "^2.3.1") but swipe enable did.
Source: [(https://stackoverflow.com/questions/48114810/react-native-disable-swiping-stacknavigator-in-tabnavigator?rq=1)]

```
YourStack.navigationOptions = ({navigation}) => {
  return {
    swipeEnabled: false
  }
}
```

**Comment by gbalduzzi** [comment]
If anyone is having the same problem in the newer versions, you can set the default navigation options for all the screens in a stack with `defaultNavigationOptions`:
```
const MainStack = createStackNavigator({
  Dashboard: DashboardScreen,
},
{
  initialRouteName: "Dashboard",
  defaultNavigationOptions: {
    gesturesEnabled: false
  }
})
```

**Comment by vmcruz** [comment]
The `gesturesEnabled: false` is not working for me on Android Emulator. This worked instead:

```javascript
const AppStack = createStackNavigator({
  Welcome: {
    screen: Welcome,
    navigationOptions: () => ({
      gestureResponseDistance: {
        horizontal: -1,
        vertical: -1,
      },
    }),
  },
});
```
It is still a hack, but at least I was able to disable this behavior. This issue was causing me troubles while performing E2E testing with `Detox` on the `.swipe` action.

**Comment by OshaFoster** [comment]
I would like to show a toast when the user swipes to navigate back, to let them know there changes will be lost. Any suggestions on how I could do that?

**Comment by Beats0** [comment]
not work for IphoneX ?

**Comment by AnilkumarDO** [comment]
Not working in iOS and Android  gesturesEnabled: false

**Comment by sangampandey** [comment]
> If anyone is having the same problem in the newer versions, you can set the default navigation options for all the screens in a stack with `defaultNavigationOptions`:
> 
> ```
> const MainStack = createStackNavigator({
>   Dashboard: DashboardScreen,
> },
> {
>   initialRouteName: "Dashboard",
>   defaultNavigationOptions: {
>     gesturesEnabled: false
>   }
> })
> ```

This solution works for me on "react-navigation": "^3.3.2"

**Comment by Neha0595** [comment]
It works for me if i didn't wrap "gestureEnabled: false" in card stack

**Comment by nikola-kolosek** [comment]
What if I wanted do disable and enable it dynamically?
For example, I have a component that is a route inside a stack. I want the user to be able to go back if they want to, but not if the component is fetching some information from the server. When the component finishes fetching, enable going back once again.

**Comment by lucaspelloni2** [comment]
```
    [__SCREENS.AUTHENTICATION]: {
      screen: ({navigation}: NavigationProps) => (
        <AuthMask screen={AuthScreenType.SOCIAL} navigation={navigation} />
      ),
      path: __SCREENS.AUTHENTICATION,
      navigationOptions: ({navigation}: NavigationProps) => ({
        headerLeft: <MyView />,
        headerTitle: <StepTracker stepArray={firstStep} />,
        headerRight: <HeaderRightSide navigation={navigation} />,
        gesturesEnabled: false,
      }),
    },
```
Worked for me as well !

**Comment by jinxac** [comment]
in react navigation 4, `navigationOptions` has been changed to `defaultNavigationOptions`

**Comment by ssathishppm** [comment]
in ios when using below code, it's loading a white background. I want to disable the swipe option

const MainStack = createStackNavigator({
  Dashboard: DashboardScreen,
},
{
  initialRouteName: "Dashboard",
  defaultNavigationOptions: {
    gesturesEnabled: false
  }
})

**Comment by ssathishppm** [comment]
Anyone know how to fix above ?

**Comment by Hemantkml** [comment]
import React, {Component} from 'react';
import {createAppContainer} from 'react-navigation';

import {createStackNavigator} from 'react-navigation-stack';
import LoginScene from '../src/LoginScene';
import SignUpScene from '../src/SignUpScene';
import TabBar from '../src/TabBar';
import Header from '../src/Common/Header';
import WelcomeScene from './scene/WelcomeScene';
import TutorialScene from '../TutorialScene';
class AppNavigation extends Component {
  constructor(props) {
    super(props);
    this.state = {};
  }

  render() {
    return <AppNavigator />;
  }
}
const MainNavigator = createStackNavigator(
  {
    TutorialScene: {screen: TutorialScene},
    WelcomeScene: {screen: WelcomeScene},
    SignUpScene: {screen: SignUpScene},
    LoginScene: {screen: LoginScene},
    TabBar: {screen: TabBar},
    Header: {screen: Header},
  },
  {
    defaultNavigationOptions: {
      gesturesEnabled: false,
    },
    headerMode: 'none',
  },
);

const AppNavigator = createAppContainer(MainNavigator);
export default AppNavigation;

**Comment by kopax** [comment]
I see a lot of `gesturesEnabled` (plural) here, what worked for me is `gestureEnabled={false}` (singular) on my Stack.Navigator with react-navigation 5.

**Comment by CyxouD** [comment]
@nikola-kolosek control it with `static navigationOptions` by passing navigation params

**Comment by zhuobinggang** [comment]
What the hell, why there have no this : 
```js
<Stack.Navigator screenOptions={{gestureEnabled: false}}>
  <Stack.Screen name="Login" component={Login} />
  //...
<Stack.Navigator>
````

**Comment by kadiryaka** [comment]
disable swipe back action and disable back icon and title  for react-navigation v5

`<TakeSendStack.Navigator initialRouteName={"TakeSend"}>
        //...
        <TakeSendStack.Screen name="TakeSendAddPhoto" options={{ title: "Take", headerLeft: null, gestureEnabled: false }} component={TakeSendAddPhoto} />
      </TakeSendStack.Navigator>`

**Comment by kadiryaka** [comment]
disable swipe back action and disable back icon and title for react-navigation v5
```
<TakeSendStack.Navigator initialRouteName={"TakeSend"}>
     //...
     <TakeSendStack.Screen name="TakeSendAddPhoto" options={{ title: "Take", headerLeft: null, gestureEnabled: false }} component={TakeSendAddPhoto} />
</TakeSendStack.Navigator>
```

**Comment by santanuyogi** [comment]
> I see a lot of `gesturesEnabled` (plural) here, what worked for me is `gestureEnabled={false}` (singular) on my Stack.Navigator with react-navigation 5.

Ahh... thank you so much. That worked for me when other solutions hadn't.

**Comment by NilPuig** [comment]
'gesturesEnabled' will be removed in a future version. Use 'gestureEnabled' instead

**Comment by khaledBou** [comment]
`function MyStack() {
  return (
    <Stack.Navigator
      initialRouteName="Home"
      headerMode="screen"
      screenOptions={{
        headerTintColor: 'white',
        headerStyle: {backgroundColor: 'tomato'},
      }}
      options={{
        gestureEnabled: false,      // add this 
      }}>
      <Stack.Screen name="Home" component={Home} />
      <Stack.Screen name="HomeDetails" component={HomeDetails} />
    </Stack.Navigator>
  );
}`

**Comment by khaledBou** [comment]
```
function MyStack() {
  return (
    <Stack.Navigator
      initialRouteName="Home"
      headerMode="screen"
      screenOptions={{
        headerTintColor: 'white',
        headerStyle: {backgroundColor: 'tomato'},
      }}
      options={{
        gestureEnabled: false,   // <------------------- ADD THIS
      }}>
      <Stack.Screen name="Home" component={Home} />
      <Stack.Screen name="HomeDetails" component={HomeDetails} />
    </Stack.Navigator>
  );
}
```

**Comment by Youn-ha** [comment]
Hello, nothing mentioned in this thread worked for me.
So I checked out official docs of React Navigation, and found this out.

https://reactnavigation.org/docs/stack-navigator/#example

```jsx
/* -------------- example1 -------------- */

    <Stack.Navigator initialRouteName="Home">
      <Stack.Screen
        name="Home"
        component={Home}
        options={{
          gestureEnabled: false,
        }}
      />
      <Stack.Screen
        name="Profile"
        component={Profile}
        options={{
          gestureEnabled: false,
        }}
      />
      <Stack.Screen
        name="Settings"
        component={Settings}
        options={{
          gestureEnabled: false,
        }}
      />
    </Stack.Navigator>
```

I gave `gestureEnabled: false` option to ***every*** Stack in navigator that I want to disable swipe gesture.
Also `RootStack.Screen` the navigator is involved too! Like the example under.

```jsx
/* -------------- example2 -------------- */

    <NavigationContainer>
      <RootStack.Navigator headerMode="none" initialRouteName="TabNavigator">
        <RootStack.Screen
          name="SignUpNavigator"
          component={SignUpNavigator}
        />
        <RootStack.Screen
          name="LoginNavigator"
          component={LoginNavigator}
        />
        <RootStack.Screen
          name="TabNavigator"
          component={TabNavigator}
        />
        <RootStack.Screen
          name="SettingsNavigator"
          component={SettingsNavigator}
          // Given that 'SettingsNavigator' is the one involving screens above (screens in example1 !!)
          options={{ gestureEnabled: false }}
        />
      </RootStack.Navigator>
    </NavigationContainer>
```

Hope this can be nice help to somebody.

**Comment by harveyappleton** [comment]
Following up from @Youn-ha comment - you **can** disable it across the whole stack navigator by doing the following.

`<Stack.Navigator
        screenOptions={{
          headerShown: false,
          gestureEnabled: false,
        }}>
        {/* screens here */}
      </Stack.Navigator>`

**Comment by SnowLew** [comment]
> Example of route definition with gesturesEnabled: false
> 
> ```
> Example: {
>     name: 'Example Screen',
>     screen: ExampleView
>     navigationOptions: {
>         gesturesEnabled: false,
>     },
> },
> ```
> 
> For me, for some reason it does not work if I wrap **gesturesEnabled: false** with **cardStack**.

This work perfectly, TY!

**Comment by AlekseyPimenov** [comment]
iOS 14, all ways above not working for me =( 
RN: 0.63.1
React-navigation:  ~5.7.1

**Comment by andikare** [comment]
me to not work 
RN: 0.63.1

  return (
    <Stack.Navigator initialRouteName="Login" screenOptions={{
      headerShown: false,
      gestureEnabled: false
    }}>
      <Stack.Screen options={{
        headerStyle: {
          backgroundColor: colorbirugelap,
        },
        headerTintColor: '#fff',
        headerTitleStyle: {
          fontWeight: 'bold',
        },

      }} name="Login" component={Login} />
      {/* <Stack.Screen name="Login" component={Login} /> */}
      <Stack.Screen name="Dasboard" component={Dasboard} />
      <Stack.Screen name="data2" component={data2} />
      <Stack.Screen name="data3" component={data3} />

    </Stack.Navigator>

**Comment by andikare** [comment]
me to not work 
RN: 0.63.1
`  return (
    <Stack.Navigator initialRouteName="Login" screenOptions={{
      headerShown: false,
      gestureEnabled: false
    }}>
      <Stack.Screen options={{
        headerStyle: {
          backgroundColor: colorbirugelap,
        },
        headerTintColor: '#fff',
        headerTitleStyle: {
          fontWeight: 'bold',
        },

      }} name="Login" component={Login} />
      {/* <Stack.Screen name="Login" component={Login} /> */}
      <Stack.Screen name="Dasboard" component={Dasboard} />
      <Stack.Screen name="data2" component={data2} />
      <Stack.Screen name="data3" component={data3} />

    </Stack.Navigator>`

**Comment by antonioreyna** [comment]
not working for ios14

**Comment by rawatnaresh** [comment]
is there any way to override this swipe behaviour for android and ios? I would like to navigate them to a particular screen on swipe back.

**Comment by gaurav-psych** [comment]
Not working for ios14 .

**Comment by jwhitty1** [comment]
> > Example of route definition with gesturesEnabled: false
> > ```
> > Example: {
> >     name: 'Example Screen',
> >     screen: ExampleView
> >     navigationOptions: {
> >         gesturesEnabled: false,
> >     },
> > },
> > ```
> > 
> > 
> > For me, for some reason it does not work if I wrap **gesturesEnabled: false** with **cardStack**.
> 
> This worked perfectly, TY!

This example is NOT useful at all... This is an object, its not even a Stack.Navigator!!

**Comment by jwhitty1** [comment]
> Following up from @Youn-ha comment - you **can** disable it across the whole stack navigator by doing the following.
> 
> ```js-jsx
> <Stack.Navigator
>   screenOptions={{
>   headerShown: false,
>  gestureEnabled: false,
>  }}>
> {/* screens here */}
> </Stack.Navigator>
> ```
> 
> Hope this helps someone out there 😁

ANYONE LOOKING FOR AN ANSWER THAT WORKS TRY THIS!!

**Comment by MannySAD** [comment]
Not working for iOS 14 - 14.2

**Comment by Kernael** [comment]
Be careful it's `gestureEnabled`, not `gesturesEnabled`

**Comment by jbromberg** [comment]
Nothing here seems to be working on iOS 14.3. Setting the `gestureEnabled` option on a screen to `false` still allows the user to swipe back.

**Comment by linoleum00** [comment]
hi!, any update on this issue?

It shouldn't be closed, because on 14.3 the `gestureEnabled` flag doesn't work, as @jbromberg posted. BTW I'm using react-navigation v4.4.4

**Comment by Charpell** [comment]
If anyone is still having this issue, it could mean you are having a deep nested navigation ion your code.
So you'd have to repeat the `gestureEnabled: false` for both parent and children

**Comment by greengeeko32** [comment]
> If anyone is still having this issue, it could mean you are having a deep nested navigation ion your code.
> So you'd have to repeat the `gestureEnabled: false` for both parent and children

This works to me, thanks.

**Comment by kzar1102** [comment]
I solved this problem with navigation "beforeRemove" event handler.
navigation.addListener('beforeRemove', (e) => {
      e.preventDefault();
}

**Comment by thanhluantl2304** [comment]
I found the problem. I faced this problem when I try to set this with the PUSH stack, not the NAVIGATE stack

**Comment by fedeerbes** [comment]
for those who are looking for a way to dynamically disable the `gestureEnabled` prop.

this worked for me
```js
<Stack.Navigator
      screenOptions={{
        headerShown: false,
        ...TransitionPresets.SlideFromRightIOS,
        gestureEnabled: true,
      }}>
      <Stack.Screen name="SwapScreen" component={SwapScreen} />
      <Stack.Screen
        name="ConfirmationSwap"
        component={ConfirmationSwapScreen}
      />
    </Stack.Navigator>
```

for example inside of `SwapScreen` or a component inside of the screen you can do the following
```js
useEffect(
    () => navigation.getParent()?.setOptions({ gestureEnabled: CONDITION }),
    [navigation, CONDITION],
  );
```

**Comment by svmszcck** [comment]
THe solution is to set gestureEnabled to false in the parent Stack Navigator(not current Stack Navigator) and setting gestureEnabled to true for the screens which need the gesture in the child stack.

**Comment by pruthvirajkarurcodewave** [comment]
> 

Nothnig worked for me. but disabling it dynamically worked.

**Comment by UrosTheDev** [comment]
> The solution is to set gestureEnabled to false in the parent Stack Navigator(not current Stack Navigator) screen and setting gestureEnabled to true for the screens which need the gesture in the current stack or directly in the current stack navigator. Worked for me with React Navigation 5.
> 
> This is a little bit hacky but working for me:
> 
> Parent Stack => Current Stack => Screen 1, Screen 2, Screen 3...
> 
> Here set gestureEnabled to false in Parent Stack Navigator's screen(which is Current Stack), set gestureEnabled to true in Current Stack Navigator options and then set gestureEnabled to false in the specific screens(for ex. Screen 2 only).


This worked for me. React Navigation 5.

So, the main/root stack navigator has a nested navigator KYCNavigation. There you put this code:

<Stack.Screen
       name="kyc-nav"
       component={KYCNavigation}
       options={{ gestureEnabled: false }}
/>

Then in the KYCNavigation stack you place this code:

`<Stack.Navigator headerMode="none" screenOptions={{ gestureEnabled: true }}>`

After that for every screen you can specify behavior like this:

  <Stack.Screen
        name="passport-verification-info"
        component={withLocalization(PassportVerificationInfoScreen)}
        options={{
          gestureEnabled: true // if true will allow swipe back, if false will not allow swipe back
        }}
      />
```
