### ISSUE TITLE
How to show Icons with TabBar Labels?

### ISSUE THREAD

**Issue by kamalk333** [react-community/react-navigation#1065]

**Comment by przemkow** [comment]
check this tutorial https://www.youtube.com/watch?v=C96piR3FRww
basicly you need to do:
```
    navigationOptions: {
      tabBar: {
        label: 'Calendar',
        icon: ({ tintColor }) => (<Icon name='calendar' size={25} color={tintColor} />)
      }
    }
```

**Comment by scottyantipa** [comment]
As of `1.0.0-beta.8` this should be:
```
navigationOptions: {
  tabBarIcon: ...
  tabBarLabel: ...
}
```

**Comment by yukkeechang** [comment]
Instead of tint color, how can I change the onPress color? I tried putting the hex number in quotes in place of tintColor but that doesn't work
