### ISSUE TITLE
CardStackTransitioner dropping screenProps

### ISSUE THREAD

**Issue by coodoo** [react-community/react-navigation#1066]
After switching to the latest master (`7165efc` at the time of writing), `StackNavigator` is not passing down `screenProps` to child screens and breaking a lot of existing code.

Root cause is `screenProps` not being passed down in `CardStackTransitioner`, see [this line](https://github.com/react-community/react-navigation/blob/master/src/views/CardStackTransitioner.js#L117), it should have been `{...this.props}` instead of `{...props}`.

Or, at least pass `screenProps` as below:

```javascript
return (
  <CardStack
	headerComponent={headerComponent}
	headerMode={headerMode}
	mode={mode}
	router={router}
	cardStyle={cardStyle}
	style={style}
	screenProps={this.props.screenProps}
        {...props}
  />
);
```

**Comment by coodoo** [comment]
Just created PR #1067 to fix this.

**Comment by grabbou** [comment]
PR has been merged.
