### ISSUE TITLE
headerVisible property doesn't match documentation

### ISSUE THREAD

**Issue by willlma** [react-community/react-navigation#1070]
The [docs](https://reactnavigation.org/docs/navigators/stack#headerVisible) suggest using a `headerVisible` property in a component's `navigationOptions`, but the below doesn't work.
```
Component.navigationOptions = {
  title: 'Title',
  headerVisible: false
};
```
When looking through #293, I realized that I had to use 
```
Component.navigationOptions = {
  title: 'Title',
  header: {
    visible: false
  }
};
```
I'm using version 1.0.0-beta.7. Should the library be updated to match the docs or vice versa?

**Comment by johnnylc** [comment]
+1 waiting for the next version.

**Comment by grabbou** [comment]
See #1074 comment. Docs are following `master` branch.

CC: @ericvicenti we should probably version docs just like React Native to avoid confusion or just deploy on release.

**Comment by jeremyong** [comment]
Wow this library is hard to use. The docs on master are wrong too so I don't see how even publishing new docs would help. You're better off just telling people what source to read. No docs is better than docs that lie.

**Comment by grabbou** [comment]
@jeremyong Happy to accept any PRs that will contribute to overall improved documentation. Source code might change, pointing to documentation is more future-proof. 

The confusion here is that `v8` has `flatOptions` (`headerTitle`, not `header.title`). We are working on adding a versioned documentation.
