### ISSUE TITLE
cannot pass params between DrawerNavigator's children

### ISSUE THREAD

**Issue by jszcl** [react-community/react-navigation#1072]
```
const handleFixNavigator = DrawerNavigator({
    Fix :{screen:FixScreen},
    Handle: {screen: HandleScreen}

});
```
` this.props.navigation.navigate('Handle', {name:'a'})`

It navigate to Handle but params.name is undefined ,but if i use StackNavigator instead of DrawerNavigator ,it works ,what happened?

**Comment by haroldjones** [comment]
I am experiencing the same issue. Any thoughts?

**Comment by toanz** [comment]
Yes , i have the same issue , I think we must fix it by ourself :(

**Comment by farrukhbashir** [comment]
@jszcl i am using the simple stack navigator it is not working which stack navigator you use i use this [Link](https://reactnavigation.org/docs/navigators/stack)

**Comment by farrukhbashir** [comment]
@toanz @haroldjones

**Comment by Louis345** [comment]
Having the same issue.  Any updates?

**Comment by toanz** [comment]
Hi , I fix it at pull request : https://github.com/react-community/react-navigation/pull/1133

**Comment by Louis345** [comment]
@toanz, question in order to get the fix do I have to reinstall react-navigation?

**Comment by spencercarli** [comment]
Hi! Since this issue has been quiet for a while I'm going to go ahead and close it. If the issue persists in the latest version of React Navigation please re-open!
