### ISSUE TITLE
Not clear if you need to use tabBarIcon

### ISSUE THREAD

**Issue by Gregoirevda** [react-community/react-navigation#1074]
using `tabBarIcon : <Icon name="rocket"/>` did not worked for me.
I saw a thread using `tabBar : { icon : <Icon name="rocket"/> }` and that worked for me.
But the second option is not in the current documentation online.
Which one is the new way of doing it? Should the docs be updated?

**Comment by jszcl** [comment]
I want to ask the same question,   the docs is awful to me .

**Comment by przemkow** [comment]
https://github.com/react-community/react-navigation/issues/1060 check this issue guys

**Comment by grabbou** [comment]
We are in the process of changing the API. NPM version uses `tabBar: { icon }` whereas master uses `tabBarIcon`. Latter is going to be the ultimate approach and blog post is coming that explains the differences.
