### ISSUE TITLE
Setting labelStyle on tabBarOptions

### ISSUE THREAD

**Issue by tomasfrancisco** [react-community/react-navigation#1077]
I'm getting a strange behavior when trying to customize the labelStyle on a TabNavigator.

This is the default style:
<img width="385" alt="screen shot 2017-04-17 at 12 45 42" src="https://cloud.githubusercontent.com/assets/4301103/25088201/6f42de6a-236c-11e7-8068-f38281531444.png">

This is the custom style:
```
labelStyle: {
    color: Colors.color
}
```
<img width="383" alt="screen shot 2017-04-17 at 12 46 09" src="https://cloud.githubusercontent.com/assets/4301103/25088210/864f192a-236c-11e7-949a-908d218ee26e.png">

What styles should I pass into to just change the color?

**Comment by nonameolsson** [comment]
Is it the label color you want to change? If that's the case then this should work:

[iOS](https://reactnavigation.org/docs/navigators/tab#tabBarOptions-for-TabBarBottom-default-tab-bar-on-iOS)
[Android](https://reactnavigation.org/docs/navigators/tab#tabBarOptions-for-TabBarBottom-default-tab-bar-on-iOS)

```
activeTintColor - label and icon color of the active tab
inactiveTintColor - label and icon color of the inactive tab
```

**Comment by tomasfrancisco** [comment]
@nonameolsson Yes, this solved my case.
But if I want to change something related to labelStyle, shouldn't be possible to do it without messing up with default styles?

**Comment by grabbou** [comment]
> But if I want to change something related to labelStyle, shouldn't be possible to do it without messing up with default styles?

As the name suggests, default styles are used as long as you don't pass a custom style object. In that case, you can copy the default styles to your code and simply extend them.

**Comment by Domthegrom** [comment]
@tomasfrancisco Hey how did you accomplish this tab bar style?

**Comment by tomasfrancisco** [comment]
@Domthegrom can you be more specific?
The style is pretty much the basic style that comes with the `TabNavigator` and only the changes that were referenced here.
Let me know what you are looking for.
