### ISSUE TITLE
How can i reload the scene?

### ISSUE THREAD

**Issue by kishanj918** [react-community/react-navigation#1079]
I am handling internet connection error in my app. I want to implement try again feature in which i want to reload the current scene.

**Comment by gsaandy** [comment]
is this something related to reactnavigation?

**Comment by kishanj918** [comment]
like in RNRF , we can refresh the scene. is it possible in react navigation?

**Comment by grabbou** [comment]
This problem is not specific to `react-navigation`. I am going to close it as there are no constraints imposed by this library that would make implementing that harder.
