### ISSUE TITLE
Header fontFamily not respected on Android

### ISSUE THREAD

**Issue by adiki** [react-community/react-navigation#1080]
```
    static navigationOptions = () => ({
        title: 'Rymozwanie',
        headerStyle: { backgroundColor: '#fff' },
        headerTintColor: colors.orange,
        headerTitleStyle: {
            fontSize: 23,
            fontFamily: fonts.junegullRegular
        }
    });
```

This code renders correctly on iOS but not on Android. Font is installed correctly I confirmed that using `<Text>`
![simulator screen shot 17 apr 2017 18 07 01](https://cloud.githubusercontent.com/assets/2124589/25094850/3ebc3a84-2399-11e7-9158-e8f17201c3c8.png)
![screenshot_1492445352](https://cloud.githubusercontent.com/assets/2124589/25094863/499b98fa-2399-11e7-961e-6342041aca9f.png)

**Comment by naren8642** [comment]
In my case none of the settings seem to be taking effect. 

For example: 
```
  static navigationOptions = {
    title: 'My Smart Apartment',
    headerStyle: { backgroundColor: '#55f' },
    headerTitleStyle: {
        fontSize: 23,
    }
  };
```

![screen shot 2017-04-20 at 2 18 52 pm](https://cloud.githubusercontent.com/assets/355768/25248640/976982b2-25d4-11e7-93d4-7aceeea0e7f4.png)

**Comment by mavenave** [comment]
Hi, I faced this issue too. It turns out that it was the font's issue not react-navigation. Refer here:https://github.com/react-community/react-navigation/issues/542#issuecomment-283663786 for details.

Set `fontFamily: '200'`.

**Comment by aroth** [comment]
@adiki any solution on your end for this?

**Comment by adiki** [comment]
Set `fontFamily: '200'`.

**Comment by xDAnkiT** [comment]
Try this

fontFamily: 'YOUR_FONT',
fontWeight:'200',

it works for me.

**Comment by ro1414** [comment]
Thanks @xDAnkiT. Setting `headerTitleStyle: {fontWeight: '200'}` worked for me as well.
Seems like `fontWeight: '500'` is being added by createAnimatedComponent.js which doesn't line up with the default weight for the font.

**Comment by courptwayne** [comment]
how to change header left arrow color ?

**Comment by ankitsevakhr** [comment]
static navigationOptions = ({ navigation, screenProps }) => ({
    title: 'title',
    headerLeft: <TouchableOpacity style={{height: 40,width: 50,justifyContent:'center'}} activeOpacity={1} onPress={() => navigation.navigate('HomeScreen')}><Image source={require('../../assets/BackIcon/left-arrow.png')} style={{marginLeft:10, height: 20, width: 20}} /></TouchableOpacity>,
  });

**Comment by fernandofranca** [comment]
Using `null` works for both Android and iOS

```
headerTitleStyle: {
  fontWeight: null,
}```
