### ISSUE TITLE
HeaderBackButton onPress override provision.

### ISSUE THREAD

**Issue by gsaandy** [react-community/react-navigation#1081]
It would be nice to have an option to override(or pre and post processing callbacks) for header back button, so that we would be able to change state for certain use cases.

**Comment by grabbou** [comment]
I believe a better solution rather than adding `onBackButtonPress`, `onTitlePress` and more is to leverage existing API, that is - provide a custom `left` component. You can import default `HeaderBackButton` that we use and there, you have an ability to customise the way it handles press.
