### ISSUE TITLE
disable the drawerNavigator from swiping open on nested stackNavigators.

### ISSUE THREAD

**Issue by jeffreymendez1993** [react-community/react-navigation#1082]
Currently when I am in a nested StackNavigator inside my DrawerNavigator on every scene I can open the drawer no matter the index. How Can I have control whether the drawer opens or not.

**Comment by jeffreymendez1993** [comment]
@grabbou any progress on this? I think this is a critical issue that should be looked at.

**Comment by dennishansen** [comment]
This is a serious flaw and needs to be dealt with promptly.

**Comment by TsuryKnox** [comment]
Yeah this is a deal breaking issue for me...

**Comment by wkmike** [comment]
PR #793  has resolved this issues
you can disable the drawer on any screen just have to add:
```
navigationOptions: {
  drawerLockMode: 'locked-closed'
}

```

**Comment by visylvius** [comment]
```
navigationOptions: {
  drawerLockMode: 'locked-closed'
}
```
does not lock the drawer. 
Is there any other way to stop the drawer from being opened on nested routes?

**Comment by huynguyencong** [comment]
Still haven't had a property to disable feature slide to open drawer :(

**Comment by Elijen** [comment]
Was this resolved or is there any other workaround? Currently I have to use 3 nested navigators (which is causing other issues) to properly control where the drawer is available.

**Comment by KakarN** [comment]
It seems it's still not resolved. #https://github.com/react-community/react-navigation/pull/793

**Comment by nazywamsiepawel** [comment]
+1

**Comment by CandyOgre** [comment]
+1

**Comment by CandyOgre** [comment]
@jeffreymendez1993 have you resolved the issue somehow?

**Comment by Sonukr** [comment]
+1

**Comment by NirBenya** [comment]
+1

**Comment by Sonukr** [comment]
Install this PR from here
`npm i -S https://github.com/martnu/react-navigation#pass-down-drawer-lock-mode`

and then, you can do something like this : 
`SomeScreen: {
    screen: SomeScreen,
    navigationOptions: ({navigation}) => ({
      drawerLockMode: 'locked-closed'
    })
  }`
or 
`SomeScreen: {
    screen: SomeScreen,
    navigationOptions: () => ({
      drawerLockMode: 'locked-closed'
    })
  }`

**Comment by jsbranco** [comment]
+1

**Comment by kelset** [comment]
In `beta.13` this feature has been merged (PR #1377) so I'm closing this issue

**Comment by rborn** [comment]
@kelset not working, tested with `1.0.0-beta.19` on an iPhone 7. 
sometimes the back gesture - going back to the previous screen -  it's executed, sometimes it opens the drawer.

The code it's just a Drawer with one screen that it's a StackNavigator with 2 screens so I can go back and forth. The second screen has the  `drawerLockMode: 'locked-closed'`

Any idea? Thank you.

**Comment by kelset** [comment]
@rborn can you open a new issue for that?

**Comment by rborn** [comment]
@kelset done - https://github.com/react-community/react-navigation/issues/2939  Thank you!

**Comment by ravirupareliya** [comment]
navigationOptions: {
      drawerLockMode: 'locked-closed'
    }

It's perfectly working with android but somehow not working with iOS, still i can open drawer by swipping and not only drawer but but swipping i can even move to previous screen. How to disable it?

**Comment by apurvaaggarwal** [comment]
ScreenName.navigationOptions = {
  drawerLockMode: 'locked-closed'
};

**Comment by sujitpk-perennial** [comment]
@ravirupareliya  have you find any solution to lock the drawer for iOS? As per doc drawerLockMode supports only Android.

**Comment by Ronnyrr** [comment]
s this functionality available in v2? In the docs I can only find the DrawerLayoutAndroid spec: https://facebook.github.io/react-native/docs/drawerlayoutandroid.html#drawerlockmode and #390 doens't seem to work.

  ReservationDetail: {
    screen: ReservationDetail,
    navigationOptions: () => ({
      title: 'Reservering',
      ...defaultHeaderStyle,
      drawerLockMode: 'locked-open',
    }),
  },

**Comment by LordParsley** [comment]
Setting `drawerLockMode` per screen for me on `v2.0.2` appears to have no effect:

```
  static navigationOptions = {
    headerTitle: 'Select Option',
    drawerLockMode: 'locked-closed'
  }
```

**Comment by sujitpk-perennial** [comment]
@balapkm  I wrote the following code and I am able to lock the drawer both in iOS and Android 

`<DrawerNavigation screenProps={{ drawerLockMode: this.state.drawerLockMode }}}}/> 
`
 Here drawerLockMode state will be 'locked-closed' or 'unlocked' and DrawerNavigation is  

```
const DrawerNavigation = DrawerNavigator (
    {
        Drawer: {
            screen: Drawer,
            navigationOptions: {
                gesturesEnabled: false,
            }
        },
        StackNavigation: {
            screen: StackNavigation
        }
    },
    {
        initialRouteName: 'StackNavigation',
        drawerBackgroundColor: 'transparent',
        contentComponent: ({ navigation, ...props }) =>
            <Drawer style={{flex: 1}}/>
    }
)
```

**Comment by balapkm** [comment]
Finally i wrote this code in DrawerView.js (/node_modules/react-navigation/src/views/Drawer/DrawerView.js)
```
const { drawerLockMode } = descriptor.options;
    let DrawerLockArray      = ['OtherScreen'];
    let drawerLockModeOwn    = 'unlocked';
    let index                = this.props.navigation.state.routes[0].index;
    let stateName            = this.props.navigation.state.routes[0].routes[index].routeName;
    if(DrawerLockArray.includes(stateName))
		{
      drawerLockModeOwn  = 'locked-closed';
    }
    return (
      <DrawerLayout
        ref={c => {
          this._drawer = c;
        }}
        drawerLockMode={drawerLockModeOwn}
        drawerBackgroundColor={
          this.props.navigationConfig.drawerBackgroundColor
        }
        drawerWidth={this.state.drawerWidth}
        onDrawerOpen={this._handleDrawerOpen}
        onDrawerClose={this._handleDrawerClose}
        useNativeAnimations={this.props.navigationConfig.useNativeAnimations}
        renderNavigationView={this._renderNavigationView}
        drawerPosition={
          this.props.navigationConfig.drawerPosition === 'right'
            ? DrawerLayout.positions.Right
            : DrawerLayout.positions.Left
        }
      >
        <DrawerScreen
          screenProps={this.props.screenProps}
          navigation={descriptor.navigation}
        />
      </DrawerLayout>
    );
```

**Comment by zxiest** [comment]
In `react-navigation` `v2`, what fixed it for me is to have the `drawerLockMode: 'locked-closed'` on the `createDrawerNavigator` level

**Comment by shakedOno** [comment]
The documentation is not updated. 
As @zxiest said, it should go in the createDrawerNaigator level.

**Comment by Dror-Bar** [comment]
@zxiest
Saved me! Thanks. Here is a code example:

Does NOT work anymore:
```
const Drawer = createDrawerNavigator({
    Drawer: SomeScreen,
},
    {
        navigationOptions: { drawerLockMode: 'locked-closed' }
    }
);
```

This works:
```
const Drawer = createDrawerNavigator({
    Drawer: SomeScreen,
},
    {
        drawerLockMode: 'locked-closed'
    }
);
```

**Comment by brayanL** [comment]
https://reactnavigation.org/docs/en/navigation-options-resolution.html#a-drawer-has-a-stack-inside-of-it-and-you-want-to-lock-the-drawer-on-certain-screens

**Comment by a-haseeb-shaikh** [comment]
> ```
> navigationOptions: {
>   drawerLockMode: 'locked-closed'
> }
> ```
> It's perfectly working with android but somehow not working with iOS, still i can open drawer by swipping and not only drawer but but swipping i can even move to previous screen. How to disable it?

Hi Dear,
In react-navigation v2 does not support drawerLockMode any more in child. It now work in parent level i-e createDrawerNavigator level

**Comment by naomipol** [comment]
@a-haseeb-shaikh I'm currently using react-navigation v2 and need to lock drawer from child stack navigator. (in order to disable drawer opening in certain screens)
Is there any workaround?
Thanks

**Comment by jeronnex2** [comment]
@zxiest  what you provided isn't working. The drawer is still opening ..

**Comment by alemkhodadadi** [comment]
> Install this PR from here
> `npm i -S https://github.com/martnu/react-navigation#pass-down-drawer-lock-mode`
> 
> and then, you can do something like this :
> 
> ```
> SomeScreen: {
>     screen: SomeScreen,
>     navigationOptions: ({navigation}) => ({
>       drawerLockMode: 'locked-closed'
>     })
>   }
> ```
> 
> or
> 
> ```
> SomeScreen: {
>     screen: SomeScreen,
>     navigationOptions: () => ({
>       drawerLockMode: 'locked-closed'
>     })
>   }
> ```

that worked for me. thanks man :)

**Comment by nageshjawanjal** [comment]
> PR #793 has resolved this issues
> you can disable the drawer on any screen just have to add:
> 
> ```
> navigationOptions: {
>   drawerLockMode: 'locked-closed'
> }
> ```

where to use it?

**Comment by Eldavid** [comment]
I am using `3.11.0` version of `react-navigation` and drawerLockMode seems not to working.

**Comment by saadheikh** [comment]
i am using this version of react-navigation-drawer@2.1.1
still not resolved
 static navigationOptions ={
        header: null ,
        gesturesEnabled: false   , 
        drawerLockMode: 'locked-closed'
        
    };
doesnot worked for me

**Comment by rmsparajuli** [comment]
I am using react-navigation v3 and 
drawerLockMode:'locked-closed'  only works on main createDrawerNavigator but doesn't works inside of drawerNavigator screen where there are also stackNavigator,  but doesn't work inside in it on navigationOptions.


example:
// works on 

 createAppContainer(createDrawerNavigator(
  {
    Home: HomeApp,
  },
  {
    drawerLockMode: 'locked-closed',
  }
))


//but not works on HomeApp

const HomeApp = createAppContainer(createStackNavigator(
{
home:Home
},{
navigationOptions: ({ navigation }) => {
        return {
            header: null,
            drawerLockMode: "locked-closed"
        }
    }
}))

**Comment by saadheikh** [comment]
Thanku I will try this out tomorrw and will let you know about this many
thanks

**Comment by karthick-t2s** [comment]
> https://reactnavigation.org/docs/en/navigation-options-resolution.html#a-drawer-has-a-stack-inside-of-it-and-you-want-to-lock-the-drawer-on-certain-screens

Link broken

**Comment by selrond** [comment]
@karthick-t2s https://web.archive.org/web/20200106061600/https://reactnavigation.org/docs/en/navigation-options-resolution.html

**Comment by maltoze** [comment]
https://reactnavigation.org/docs/screen-options-resolution/#setting-parent-screen-options-based-on-child-navigators-state

> 3. Lock drawer on certain screens: a drawer has a stack inside of it and you want to lock the drawer on certain screens

```tsx

const getGestureEnabled = (route: Route<any>) => {
  const routeName = getFocusedRouteNameFromRoute(route) ?? 'Home';
  switch (routeName) {
    case 'Home':
      return true;
    default:
      return false;
  }
};

...
      <Drawer.Navigator>
        <Drawer.Screen
          name={homeRouteName}
          component={RootNavigator}
          options={({ route }) => {
            return {
              gestureEnabled: getGestureEnabled(route),
            };
          }}
        />
      </Drawer.Navigator>
...
```

**Comment by sahil84538453** [comment]
<Drawer.Navigator
   .....
   screenOptions={{swipeEnabled: false}}
>
      <Drawer.Screen ...>
       .....
</Drawer.Navigator>

**Comment by rochijacob** [comment]
Hi! 

I managed to solve this by doing the following. I have a drawer navigator with a Stack navigator inside. When I navigate the stack I don't want to swipe open the drawer (only in the first screen I want this)

Inside the drawer screen that holds my tab navigation my settings are:

```
        options={({ route }) => {
          const routeName = getFocusedRouteNameFromRoute(route) ?? 'Home';
          let options = {
            title: route.name,
            drawerItemStyle: { display: 'none' },
            headerShown: false,
            unmountOnBlur: true,
          }
          if (routeName !== '<first screen name>') {
            options = { ...options, swipeEnabled: false }
          }
          return options
        }}
```

**Comment by alexanderdavide** [comment]
> Hi!
> 
> I managed to solve this by doing the following. I have a drawer navigator with a Stack navigator inside. When I navigate the stack I don't want to swipe open the drawer (only in the first screen I want this)
> 
> Inside the drawer screen that holds my tab navigation my settings are:
> 
> ```
>         options={({ route }) => {
>           const routeName = getFocusedRouteNameFromRoute(route) ?? 'Home';
>           let options = {
>             title: route.name,
>             drawerItemStyle: { display: 'none' },
>             headerShown: false,
>             unmountOnBlur: true,
>           }
>           if (routeName !== '<first screen name>') {
>             options = { ...options, swipeEnabled: false }
>           }
>           return options
>         }}
> ```

This is working for me, thanks!

Do you use TypeScript? I'm wondering if it's possible to get correct types for `getFocusedRouteNameFromRoute`?
