### ISSUE TITLE
headerRight can not display correctly

### ISSUE THREAD

**Issue by guoliang1206** [react-community/react-navigation#1085]
According to the guide course， the headerRight of header can't display.

This is my environment
```
 "dependencies": {
    "react": "16.0.0-alpha.6",
    "react-native": "0.43.3",
    "react-native-maps": "^0.13.1",
    "react-navigation": "^1.0.0-beta.7"
  },
  "devDependencies": {
    "babel-jest": "19.0.0",
    "babel-preset-react-native": "1.9.1",
    "jest": "19.0.2",
    "react-test-renderer": "16.0.0-alpha.6"
  },
```
this is the navigationOptions in my code.

```
 static navigationOptions = {


        title:'Track trace',
        tabBar:{
            label:'Maps',
        },
        headerRight:<Button title="Info"/>
}
```

this is the screenshots
![simulator screen shot 2017 4 18 9 41 38](https://cloud.githubusercontent.com/assets/12846676/25111156/dadce85a-241b-11e7-8639-5571bb142124.png)

**Comment by guoliang1206** [comment]
```
const MyApp = StackNavigator({

   Maps:{
       screen:MainScreen,
       navigationOptions:{
           title:'Go Track',
           headerRight:<Button title="Info"/>
       }
   }

});
```

this is still with the problem

**Comment by DiogoAbu** [comment]
Official docs are ahead of the master/npm version. You can fetch it directly by adding this to package.json
`"react-navigation": "git+https://github.com/react-community/react-navigation.git#commit",`
Last commit is:
`"react-navigation": "git+https://github.com/react-community/react-navigation.git#77313a2",`
This commit may have changes that will break your code

**Comment by guoliang1206** [comment]
@DiogoAbu  ok, thank you.

**Comment by luangch** [comment]
I update to `1.0.0-beta.7` and it works
