### ISSUE TITLE
show popup-dialog when click item on drawer-menu in react-navigation

### ISSUE THREAD

**Issue by tungbt-2-3-1994** [react-community/react-navigation#1086]
I have a logout button on drawer-menu. I want to when i click on this, my app will appear a popup-dialog view (react-native-popup-dialog). How can i do that?
Thanks in advance!

**Comment by spencercarli** [comment]
Hi! In an effort to reduce the number of open issues I'm closing issues that haven't had any activity in a while.

If you think this should be re-opened please let me know or, if you can, re-open it.

If this is a question please consider asking it on StackOverflow ([react-navigation](https://stackoverflow.com/questions/tagged/react-navigation))

Thanks!

**Comment by law-P** [comment]
@spencercarli please reopen this issue
