### ISSUE TITLE
Change Navigation options according to redux store?

### ISSUE THREAD

**Issue by henrikra** [react-community/react-navigation#1090]
According to docs you can dynamically change navigation options which is good https://reactnavigation.org/docs/navigators/navigation-options But how it is possible to change navigations options according to redux store for example I would like change navigation color when my user goes online :)

**Comment by santiagopoli** [comment]
Related to https://github.com/react-community/react-navigation/issues/1126 and https://github.com/react-community/react-navigation/issues/1160

**Comment by cooperka** [comment]
@henrikra there are some answers here that might help: https://github.com/react-community/react-navigation/issues/717.

**Comment by spencercarli** [comment]
Hi! Since this issue has been quiet for a while I'm going to go ahead and close it. If the issue persists in the latest version of React Navigation please re-open!
