### ISSUE TITLE
Native elements

### ISSUE THREAD

**Issue by RWOverdijk** [react-community/react-navigation#1099]
Awesome library

Quick question... I'm using this in react native, and want to implement chromecast. It offers native ui elements, but I worry I can't show the icon in the bar as it's not native. Any suggestions? Besides using a different lib?

**Update:** I realize that the View itself is native. So perhaps I just don't grasp this concept yet. Anyway, specifically I'm talking about this part: https://developers.google.com/cast/docs/android_sender_integrate#add_a_cast_button

**Comment by grabbou** [comment]
As long as you have a `React` component to render with React Native, it will work as an icon. If it's `native`, you need to wrap it so that React Native can use it. You can find detailed instructions here -> http://facebook.github.io/react-native/docs/native-components-ios.html
