### ISSUE TITLE
Problems trying to run react-navigation in existing project

### ISSUE THREAD

**Issue by andrelimawork** [react-community/react-navigation#110]
Everytime i try to include the library in my projects i get the error:

Syntax Error in TransitionConfigs.js Unexpected token(26:52)

Can somebody help m. I'm stuck here.

Thanks

**Comment by Ehesp** [comment]
Wipe node_modules and try again?

**Comment by satya164** [comment]
Can you give some sample code? What's in your `.babelrc`?

**Comment by andrelimawork** [comment]
Hey Satya, rm node_modules, upgrade an linking resolved my issue.
Thanks for the help.
