### ISSUE TITLE
TabBarIcon not appearing on iOS

### ISSUE THREAD

**Issue by fxfactorial** [react-community/react-navigation#1101]
Greetings, 

Following the docs and I checked with the source code, 

the following should work for a component intended as a TabNavigator component and while it does come up, the Image itself does not render. 

```
  static navigationOptions = {
    tabBarLabel: 'client manager',
    tabBarIcon: (
      <Image style={{height:26, width:26}}
             source={require('./assets/gear.png')}
             />
    )
  }
```
I checked with the source code, `src/views/TabView/TabView.js` and things seem correct on my end, also tried as a function to no avail. 

```
if (options.tabBarIcon) {
    121       return typeof options.tabBarIcon === 'function'
    122         ? options.tabBarIcon({ tintColor, focused })
    123         : options.tabBarIcon;
    124     }
```

On OS X: 
```
$ react-native --version
react-native-cli: 2.0.1
react-native: 0.42.0
```

and this is for: 

```
$ react-native run-ios --simulator 'iPad Air 2'
```

Furthermore, the tabBar's name is using the TabBar's key name for `TabNavigator({` rather than things like `    tabBarLabel: 'Admin'`.

**Comment by norberdo** [comment]
I faced the same problem and it looks like you should have something like this. Works for me.

```
static navigationOptions = {
tabBar: {
    label: 'client manager',
    icon: (
      <Image style={{height:26, width:26}}
             source={require('./assets/gear.png')}
             />
    )
  }
}

**Comment by fxfactorial** [comment]
@norberdo yep, that's what it was. Seems like it similar to the API churn I saw in https://github.com/react-community/react-navigation/issues/1088

Thank you!

**Comment by Malouda** [comment]
Hello, i still have a problem changed the navigationOptions to 
`static navigationOptions = {
        tabBar:{
            label:'Image',
            icon:(
                <Image
                    source={require('../images/gopro.png')}
                    style={{height:26, width:26}}
                />
            ),
        }

    };`
am using  react-navigation": "^1.0.0-beta.11",


![](mtp://[usb:001,007]/Phone/DCIM/Screenshots/Screenshot_2017-05-29-19-19-14.png)

**Comment by nxmohamad** [comment]
@norberdo thank you! is this a bug or should they be updating their docs?

**Comment by ahmadalfy** [comment]
@Malouda I had to add a return

```jsx

  static navigationOptions = {
    tabBarLabel: 'More',
    tabBarIcon: ({ tintColor }) => {
      return (
        <Image
          source={require('../../assets/generic/icons/tabs/account.png')}
          style={[genericStyles.tabIcon, { tintColor }]}
        />
      );
    },
  }
```
