### ISSUE TITLE
TabNavigator::tabBarComponent how to get active state? 

### ISSUE THREAD

**Issue by ChristianTucker** [react-community/react-navigation#1103]
We're moving our application over to react-navigation and we're a little confused as to how to use the `TabNavigator` as the documentation only shows that you can use `tabBarComponent` to return a custom TabBar, but it doesn't seem to pass any props through this function for setting active/deactivate states. 

We want to use different icons based on if the tab is active or not and have the tab bar follow our previous design. Perhaps I'm just missing something here, but the documentation seems fairly lacking. 

Also, when nesting a TabNavigator, like so:

```
Stacknavigator({
    home: { screen: ... },
    tabs: { screen: TabNavigator({...}) }
})
```

How do you navigate from home to tabs and select which screen in tabs you want to view? For example what If I wanted to `navigate('tabs/messages')`

**Comment by konrad-marzec** [comment]
I suggest you to look at react-navigator examples (https://github.com/react-community/react-navigation/blob/master/examples/NavigationPlayground/js/SimpleTabs.js)

In navigation

```javascript
navigationOptions = {
  tabBarLabel: ({ routes, index, focuses }) => <CustomComponent />,
  tabBarIcon: ({ tintColor, focused }) => (
    <Ionicons
      name={focused ? 'ios-chatboxes' : 'ios-chatboxes-outline'}
      size={26}
      style={{ color: tintColor }}
    />
  ),
};
```
![image](https://cloud.githubusercontent.com/assets/26223461/25277604/b0bbe0cc-269f-11e7-9162-0ed000ec1928.png)

![image](https://cloud.githubusercontent.com/assets/26223461/25277647/d8b89732-269f-11e7-8260-7004e9c2833b.png)

**Comment by jpca999** [comment]
@konrad-marzec   where is the   <CustomComponent />,    coming from ?

**Comment by toni-decode** [comment]
looks like currently you can't pass active tab info to your custom tabBar
  tabBarComponent: **CustomTabBar**

**Comment by ptaking** [comment]
any update on this?

**Comment by argentum47** [comment]
Yes, try navigation.state.index where navigation is passed as props

**Comment by dytra** [comment]
> Yes, try navigation.state.index where navigation is passed as props

why i always get empty object when accessing `navigation.state.index` ?
