### ISSUE TITLE
How to configure the color of the back arrow?

### ISSUE THREAD

**Issue by jszcl** [react-community/react-navigation#1104]
```
header:{
            style:{backgroundColor:'#3b5998'},
            titleStyle:{color:'white'},
            left:


    }
```
I can't find anything about how to configure left style  in the docs, such as color, text,..

**Comment by wangzhe890703** [comment]
I think you can build a customized component.

For example:
header:{
            style:{backgroundColor:'#3b5998'},
            titleStyle:{color:'white'},
            left: (<Text style={{color: "#3b5998"}}> BackBtn </Text>),


    }

**Comment by jszcl** [comment]
```header:{
style:{backgroundColor:'#3b5998'},
titleStyle:{color:'white'},
left: (<Text style={{color: "#3b5998"}} onPress={()=>this.props.navigation.goback()}> BackBtn ),

}` 
but onPress={()=>this.props.navigation.goback()} dosen't work

**Comment by wangzhe890703** [comment]
In Foo.navigationOptions, you are not able to get access to `this` and it is `static` actually. And `this.prop` is undefined, so that is why `onPress` doesnot work.

Try:
`header: navigation => ({
            style:{backgroundColor:'#3b5998'},
            titleStyle:{color:'white'},
            left: (<Text style={{color: "#3b5998"}} onPress={()=>navigation.goback()}> BackBtn ),
    })`

**Comment by jszcl** [comment]
It still doesn't work

**Comment by grabbou** [comment]
Use https://reactnavigation.org/docs/navigators/stack#headerTintColor to manipulate color of a default back button. For more advanced use cases, pass `headerLeft` component.

**Comment by neo125874** [comment]
@grabbou may i ask why i set the headerTintColor, and still not working, miss anything?
`static navigationOptions = {
    title: 'LoginPage',
    //put here
  };`

**Comment by grabbou** [comment]
You would need to upgrade to `lastest` version of react-navigation (`v8` or `master`), but we are working on next version.

If `headerTintColor` doesn't work, try `header: { tintColor: '' }}` but keep in mind that this is going to change in next version to `headerTintColor`.

**Comment by neo125874** [comment]
@grabbou ok, thanks, got it works :)

**Comment by seanmadi** [comment]
@wangzhe890703 You mentioned that you cannot access `this` within navigationOptions. I'm having an issue trying to call a class method from my component which changes the state with the onPress prop in a button I have in the `headerRight`. Is there a work around for my to be able to call a method from my component using onPress within navigationOptions?

**Comment by keithics** [comment]
@seanmadi I am having the same question.

**Comment by Tiendq** [comment]
@grabbou I'm using 1.0.0-beta.9, `headerTintColor` changes color of title but not back button.

**Comment by peterchibunna** [comment]
@Tiendq I'm using `1.0.0-beta.11`. It changes the color of both title and back button.

**Comment by Noitidart** [comment]
I am also not able to change the color of the back arrow button. I am on Android. I want to make the arrow white in some cases, and black in other cases depending on applied theme.

I tried the following:

```
    static navigationOptions = {
        title: 'Rawr',
        headerStyle: { backgroundColor: '#1DB0E1' },
        headerTintColor: { color:'#FFFFFF' },
        headerBackTitleStyle: { color:'#FFFFFF' },
        headerTitleStyle: { color:'#FFFFFF' }
```

I haven't got the white yet, so I haven't thought yet how I am going to access the `this.state` or `this.context` to figure out the theme.

**Comment by Noitidart** [comment]
I need my `headerTintColor` to respond to `this.state` or `this.props.navigation.params` as I have a theme. Is this possible? @grabbou - thanks very much for your work and help here.

**Comment by sarahmarciano** [comment]
@peterchibunna I'm also using `1.0.0-beta.11` but the `headerTintColor` property is not changing the back button color

**Comment by dehamzah** [comment]
@sarahmarciano you can try upgrade to latest version (currently `1.0.0-beta.13`).
it works for me. for example:
```
headerTintColor: 'red'
```

**Comment by Barylskyigb** [comment]
@peterchibunna To change color of the arrow but not the title, you can use smth like below:

```
  static navigationOptions = {
    title: 'Home screen',
    headerTintColor: 'red',
    headerTitleStyle: { colors: 'black' }
  };
```

**Comment by illepic** [comment]
This may help some folks: If you've been settings `headerTitleStyle` and `headerBackTitleStyle` using styleSheet syntax, you may be accidentally setting `headerTintColor` with styleSheet syntax.

In other words, you may be accidentally doing the following:

```js
  static navigationOptions = {
    title: 'Home screen',
    headerTintColor: {
      color: 'red', // This is wrong and will not work!!!! 
    },
    headerTitleStyle: { color: 'black' }
  };
```

when you should actually be doing the following:

```js
  static navigationOptions = {
    title: 'Home screen',
    headerTintColor: color: 'red', // YAY! Proper format!
    headerTitleStyle: { color: 'black' }
  };
```

**Comment by mgscreativa** [comment]
Hi! I finally figured it out! In my case, I needed to have the left component text and arrow the same color, and that color should be based in a style sheet color for easily changing it later in case of template needs.

I solved it by using EStyleSheet npm module which stores all precomputed style sheet objects with underscored names for later use, more info here https://github.com/vitalets/react-native-extended-stylesheet#underscored-styles

So for my solution, I have defined the back title style like this:
```
import EStyleSheet from 'react-native-extended-stylesheet';

export default EStyleSheet.create({
...
...
  headerTitleStyle: {
    color: '$primaryColor',
  },
  headerBackTitleStyle: {
    color: '$primaryColor',
  },
...
...
```

Then applied it in my StackNavigator definition
```
import { StackNavigator } from 'react-navigation';
...
...
import styles from './styles';
...
...
const HomeStack = StackNavigator(
  {
    Home: {
      screen: Home,
      navigationOptions: ({ navigation, screenProps }) => ({
        headerTitle: 'Header Title',
        headerBackTitle: 'Back',
        headerStyle: styles.headerStyle,
        headerTitleStyle: styles.headerTitleStyle,
        headerBackTitleStyle: styles.headerBackTitleStyle,
        headerTintColor: styles._headerBackTitleStyle.color, // <-- Here you inject the color definition!
      }),
    },
...
...
```

**Comment by laine-g** [comment]
@jszcl 
@grabbou 
@mgscreativa 
@illepic 
Finally I fond a complete solution. You need to do next manually:
```
import {HeaderBackButton} from "react-navigation"; // Import default react navigate button
// navigationOptions
// tintColor does the work!
			headerLeft: (
		      <HeaderBackButton
		        tintColor='#C80046' onPress={() => navigation.dispatch({ type: 'Navigation/BACK' }) }
		      />
		    ),
```
This working with nested Stacks in Drawers,etc...
Tested on: 
**react-native**: **~0.55.2**,
**react-navigation**: **^2.0.1**

**Comment by courptwayne** [comment]
How to change  header Left arrow color?

**Comment by kyleclegg** [comment]
An example on v2 would be helpful here.

**Comment by Alishgiri** [comment]
User this:
        options: {
          topBar: {
            **backButton**: {
              color: WHITE_COLOR
            },

**Comment by rosnk** [comment]
**react navigation 6:** 

const screenOptions = {
    headerTitleAlign: "center",      // this centers the title
    headerTintColor: "green",      // this makes all the header element color green including - back button
    headerTitleStyle: {
      color: "black",    // this resets color back to "black" from "green" .... from above tint statement
    },
  };

  return (
    <Stack.Navigator screenOptions={screenOptions}>

    </Stack.Navigator>
  );
  
  Note: you can add to individual  <Stack.Screen..... as a option to control how it looks on individual screen 
  OR 
  add to <Stack.Navigator as a screenOptions to control all the screen stack defined.
