### ISSUE TITLE
can get navigation anywhere and push or present anywhere?

### ISSUE THREAD

**Issue by abellee** [react-community/react-navigation#1107]
just like the ios,
example:
a TabNavigator in a StackNavigator, and every screen in TabNavigator is a StackNavigator,
there is a uniform router, and I can choose to push a screen to the inside StackNavigator or outside StackNavigator, or make a present, so how can I do this?

**Comment by vincent1988** [comment]
same isues

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
