### ISSUE TITLE
 Unable to resolve module `react-addons-pure-render-mixin`

### ISSUE THREAD

**Issue by LeesinYasuo** [react-community/react-navigation#1108]
I follow the #923,but the error is changed to addons-pure-render-mixin
 "dependencies": {
    "react": "16.0.0-alpha.6",
    "react-native": "0.43.3",
    "react-navigation": "git+https://github.com/react-community/react-navigation.git#7edd9a7"
  }

**Comment by nihgwu** [comment]
please search the Issues before create a new one, there are already a bunch of issues over this
use the master branch or following this https://github.com/react-community/react-navigation/pull/809

**Comment by LeesinYasuo** [comment]
sorry,but i did search,there was no the same issue like 'react-addons-pure-render-mixin', and #923 is not work.

**Comment by grabbou** [comment]
We don't depend on `addons-pure-render-mixin` anymore, so the error is likely from another library. Please check running master to see if it's still an issue.
