### ISSUE TITLE
navigationOptions does not work when it is a function

### ISSUE THREAD

**Issue by thekelvinliu** [react-community/react-navigation#1113]
just discovered this package, and i'm trying to follow the [getting started](https://reactnavigation.org/docs/intro/) tutorial on the docs. whenever i make `navigationOptions` a function that returns an object instead of a plain object, the header doesn't show anything but a button to go to the previous screen on the stack. also, adding a button to the header with `headerRight` doesn't work either. here's my code:

```jsx
// App.js

import React, { Component } from 'react';
import {
  Button,
  Text,
  View
} from 'react-native';
import { StackNavigator } from 'react-navigation';

class HomeScreen extends Component {
  static navigationOptions = {
    title: 'welcome'
  };
  render() {
    return (
      <View>
        <Text>hello, navigation</Text>
        <Button
          onPress={() => this.props.navigation.navigate('chat')}
          title='chat with alice'
        />
      </View>
    );
  }
}

class ChatScreen extends Component {
  // this works
  static navigationOptions = {
    title: 'chat with alice'
  };

  // // this works, but the button does not show
  // static navigationOptions = {
  //   title: 'chat with alice',
  //   headerRight: <Button title='info'/>
  // };

  // // this does not work at all
  // static navigationOptions = ({ navigation }) => ({
  //   title: `chat with ${navigation.state.params.user}`
  // });

  render() {
    return (
      <View>
        <Text>chat with alice</Text>
      </View>
    );
  }
}

const App = StackNavigator({
  home: { screen: HomeScreen },
  chat: { screen: ChatScreen }
});

export default App;
```

running into this issue on both iOS and Android. am i missing something obvious? i used [crna](https://github.com/react-community/create-react-native-app) setup the project if that makes a difference. here are my installed dependencies, and let me know if there's any other extra info i should share.

```json
{
  "devDependencies": {
    "jest-expo": "^0.3.0",
    "react-native-scripts": "0.0.27",
    "react-test-renderer": "~15.4.1"
  },
  "dependencies": {
    "expo": "^15.1.0",
    "react": "~15.4.0",
    "react-native": "0.42.3",
    "react-navigation": "^1.0.0-beta.7"
  }
}
```

**Comment by Rewieer** [comment]
Same here, just spotted it is not called

**Comment by reinisriekstins** [comment]
Not working on Android Emulator when placed inside the StackNavigator config (instead of being a static property) object as well.

**Comment by ms88privat** [comment]
The new version isn't released yet. Try get this library from master and it should work

**Comment by thekelvinliu** [comment]
i can confirm that this works; did a `yarn add https://github.com/react-community/react-navigation` and everything's looking good. thanks @ms88privat!

**Comment by CvBlixen** [comment]
Now that [1.0.0-beta.9](https://github.com/react-community/react-navigation/releases/tag/v1.0.0-beta.9) is released, `npm update` fixed the problem for me.
