### ISSUE TITLE
Stack navigator not work 

### ISSUE THREAD

**Issue by farrukhbashir** [react-community/react-navigation#1117]
![screenshot_2017-04-12-11-20-18](https://cloud.githubusercontent.com/assets/22269001/25177015/22cd5d54-24b5-11e7-8537-f9288c844cff.png)
Stack navigator not work it give the error i create a simple program but not work i take this code from this [`link`](https://reactnavigation.org/docs/navigators/stack)
I use this code

class MyHomeScreen extends React.Component {
  static navigationOptions = {
    title: 'Home',
  }

  render() {
    return (
      <Button
        onPress={() => this.props.navigation.navigate('Profile', {name: 'Lucy'})}
        title="Go to Lucy's profile"
      />
    );
  }
}

const ModalStack = StackNavigator({
  Home: {
    screen: MyHomeScreen,
  },
  Profile: {
    path: 'people/:name',
    screen: MyProfileScreen,
  },
});
but i get the error
![screenshot_2017-04-19-11-44-46 1](https://cloud.githubusercontent.com/assets/22269001/25176382/cf599c70-24b2-11e7-92b1-22dcd292ba3d.png)

**Comment by AlanFoster** [comment]
@farrukhbashir From the stack trace:

```
Unable to resolve module `./chats-icon.png`
```

I think you're following the example from [TabNavigator](https://reactnavigation.org/docs/navigators/tab) right? If so, this is being you haven't included a `chats-icon.png` image.

**Comment by farrukhbashir** [comment]
@AlanFoster  yes sir i use this one but i include the image also but not working...I use the simple stack navigator it is not working i think in stack navigator there no need of image still not working

**Comment by farrukhbashir** [comment]
Sir below image is the error of tab navigator which is remove when img add after this the image which show first line this error come in tab navigator and stack navigator still same error

**Comment by DavoCg** [comment]
You can try ```"react-navigation": "git+https://github.com/react-community/react-navigation.git",``` in your package.json and run ``` npm install``` It's a problem with react-native 0.43+

**Comment by grabbou** [comment]
Please see https://github.com/react-community/react-navigation/issues/923 for the first error. As far as the second, you might be missing an asset.
