### ISSUE TITLE
Drawer with tabs

### ISSUE THREAD

**Issue by RUIFERNANDE5** [react-community/react-navigation#1119]
I've been trying to resolve a couple of errors in the past 8 hours with no success, already tried suggestions from your docs / issues and did not reach any conclusion.

**Error 1**: Drawer has `headerMode: 'none'` but still has children (Tabs) header;

![2](https://cloud.githubusercontent.com/assets/7592536/25191887/00690c1c-2529-11e7-9956-34e5f39ef8c5.png)

**Question**: How can I navigate from Login Screen (or any other Login screen siblings) to parent's sibling "Dashboard" with reset property? I can only achieve this with navigate. (Already tried what you suggested 

![1](https://cloud.githubusercontent.com/assets/7592536/25191890/03e3a74e-2529-11e7-97d4-c416f2c33787.png)

**Error 2**:` tabBarPosition: 'bottom'` on . android gets behind software buttons;

Does anyone have a working example of a structure like the following?
- Main router with Auth (Login, Register - no header)  and a sibling Scene with drawer and tabs

**Router code:**
```
export const Auth = StackNavigator({
    Login: {
        screen: Login,
    },
}, {
    headerMode: 'screen',
    navigationOptions: {
        header: { visible: false }
    }
});


export const Tabs = TabNavigator({
    Favorites: {
        screen: Favorites,
        navigationOptions: {
            title: 'Favorites',
            tabBar: {
                icon: ({focused}) => <TabIcon image="star" label="Favorites" selected={focused}/>
            },
        },
    },
    Calls: {
        screen: Calls,
        navigationOptions: {
            title: 'Calls',
            tabBar: {
                icon: ({focused}) => <TabIcon image="phone" label="Calls" selected={focused}/>
            },
        },
    }
}, {
    initialRouteName: 'Calls',
    headerMode: 'screen',
    tabBarPosition: 'bottom'
});

const Drawer = DrawerNavigator({
    Tabs: {
        screen: Tabs,
    },
}, {
    headerMode: 'none',
    contentComponent: props => <ControlPanel {...props}/>,
    navigationOptions: {
        header: (props) => ({
            left: <Burguer {...props} />
        }),
    },
});

export const Router = StackNavigator({
    Auth: {
        screen: Auth,
    },
    Dashboard : {
        screen: Drawer,
    },
}, {
    headerMode: 'screen',
});
```

P.s: I want login to have no header.

Any help would be really appreciated. Thanks in advance

**Comment by konrad-marzec** [comment]
Try use this fragment of code to fix Error 1
```javascript
const Drawer = DrawerNavigator({
  Tab1: { screen: Tab1 },
  .
  .
  TabN: { screen: TabN },
});

export const Auth = StackNavigator({
    Drawer: { screen: Drawer },
    Login: { screen: Login },
    /* more routes without header */
}, {
    headerMode: 'screen',
    navigationOptions: {
        headerVisible: false,
    }
});
```
