### ISSUE TITLE
Open Drawer from Header Button

### ISSUE THREAD

**Issue by X-Tender** [react-community/react-navigation#1122]
I would like to have a Menu Button in the Header which open the Drawer.
I've found many solutions here but not for the latest version.

I found this snippets in the doc but how can I add it to the Button in the Header? When I just put it there in the `onPress` function it won't work.

```javascript
this.props.navigation.navigate('DrawerOpen'); // open drawer
this.props.navigation.navigate('DrawerClose'); // close drawer
```

Here's the main part of my code:
```javascript
// [..] Imports and other unimportant Stuff [..]

const MyApp = new DrawerNavigator({
	RecentVideos: {
		screen: RecentVideos,
		navigationOptions: {
	    	drawerLabel: 'Videos',
		},
	},
});

const MenuButton = (
	<View>
		<TouchableOpacity onPress={() => { /* AND NOW?! */} }>
			<Icon name="bars" style={{color: 'white', padding: 10, marginLeft:10, fontSize: 20}}/>
		</TouchableOpacity>
	</View>
);

const AppNavigator = new StackNavigator({
	Main: {
		screen: MyApp,
	},
	VideoDetails: {
		screen: VideoDetails,
		navigationOptions: {
			headerVisible: false,
		},
	},
	VideoPlayer: {
		screen: VideoPlayer,
		navigationOptions: {
			headerVisible: false,
		},
	},
},{
	navigationOptions: {
		title: 'App',
		headerTintColor : style._tint.color,
		headerStyle : style.header,
		headerLeft : MenuButton,
	},
});

export default AppNavigator;
```

**Comment by Andreyco** [comment]
- Import `NavigationActions`
- `navigationOptions` can be specified as getter function, which receives props, `navigation` is one of them. Adjust it accordingly
```
navigationOptions: ({ navigation }) => ({
  headerLeft : <MenuButton navigate={navigation.navigate} />,
}),
```
- finally, call `this.props.navigate('DrawerOpen') from `MenuButton` when needed

**Comment by X-Tender** [comment]
Works like a charm. Thanks a lot! 👍

**Comment by Andreyco** [comment]
No prob. It's documented thou, but yeah, easy to miss ;)

**Comment by AlmogRnD** [comment]
I'm getting undefined is not an object evaluating this props.navigation 

Here is my code 

// Main drawer icon
```
const DrawerIcon = () => {
    return(
    <View>
        <TouchableOpacity onPress={() => {this.props.navigation.navigate('DrawerOpen'); } }>
            <Icon name="bars" style={{padding: 10, marginLeft:10}} size={20} color="black" type={"font-awesome"}/>
        </TouchableOpacity>
    </View>
    );
};
```

```
// Native tab navigation
export const TabsNavigation = TabNavigator({
    Home: {
        screen: Home,
        navigationOptions: ({ props }) => ({
            tabBarLabel: 'Home',
            headerLeft : <DrawerIcon {...props} />,
            tabBarIcon: ({ tintColor }) => <Icon name="home" size={28} color={tintColor} type={"font-awesome"} />
        }),
    },
    Photos: {
        screen: Photos,
        navigationOptions: {
            tabBarLabel: 'Photos',
            tabBarIcon: ({ tintColor }) => <Icon name="camera" size={28} color={tintColor} type={"font-awesome"} />
        },
    },
    SiteDiary: {
        screen: SiteDiary,
        navigationOptions: {
            tabBarLabel: 'Site Diary',
            tabBarIcon: ({ tintColor }) => <Icon name="cog" size={28} color={tintColor} type={"font-awesome"} />
        },
    },
});
```

Any ideas what I'm missing or doing wrong?

**Comment by JeffreyHyer** [comment]
@AlmogRnD You're using a TabNavigator, the `navigate('DrawerOpen')` methods only applies to the DrawerNavigator.

**Comment by Dygerati** [comment]
Alright, so the solution from Andreyco  definitely works, but could someone explain why exactly it works? 

I had assumed that the instance of StackNavigator would provide the navigator only for the Stack, which wouldn't include the 'DrawerOpen' route. I seem to be missing something...

**Comment by hectorsabina** [comment]
@Dygerati, it should be because the 'MyApp' DrawerNavigator is embedded in the root StackNavigator as a screen. Check [these docs](https://reactnavigation.org/docs/intro/nesting#Nesting-a-Navigator-in-a-screen) for more info.

**Comment by AnthonyLamot** [comment]
I have missed something, because I am not getting @Andreyco 's solution to work. Instead, I get the error: "Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object."

My code:

```
const DrawerButton = (
  <View>
    <Icon
      name="menu"
      size={30}
      color="black"
      onPress={() => this.props.navigate('DrawerOpen')}
    />
  </View>
);

const DashboardStack = StackNavigator({
  Dashboard: {
    screen: Dashboard,
    navigationOptions: ({ navigation }) => ({
      headerLeft: <DrawerButton navigate={navigation.navigate} />,
    }),
  },
});

const Drawer = DrawerNavigator(
  {
    Dashboard: {
      screen: DashboardStack,
    },
    Journal: {
      screen: DreamTabs,
    },
    Profile: {
      screen: Profile,
    },
  },
  {
    drawerWidth: SCREEN_WIDTH * 0.8,
  },
);
```

Another note: I also imported `NavigationActions`, though I don't see this actually being used anywhere?

**Comment by sachinwak** [comment]
I guess `NavigationActions` no need to import .  need to get navigation object from  navigationOptions and then use in functional component as props. Below code works for me.
```
const DrawerButton = (props) => {
	return (
    <View>
      <TouchableOpacity onPress={() => {props.navigation.navigate('DrawerOpen')}}>
        <Image
          source={require('../img/iconImage.png')}
          style={styles.icon}
        />
      </TouchableOpacity>
    </View>
  );
};

const main_stack_nav = StackNavigator({
  CategoryList: {
    screen: RecipesCategoryList,
    navigationOptions: ({navigation}) => ({
      title: "Category List",
      headerLeft: <DrawerButton navigation={navigation}  />
    }),
  }
});

```

**Comment by AnthonyLamot** [comment]
Darn poorly defined `DrawerButton`! Thanks for pointing that out, @sachinwak !

**Comment by carboni-rob** [comment]
@sachinwak I tried your solution, but the headerLeft component navigates to the first item in the DrawerNavigator, instead of opening it. Any idea? Here's the code:
`const DrawerButton = (props) => {
    return (
      <View>
          <TouchableOpacity onPress={() => { props.navigation.navigate('DrawerOpen')}}>
              <MaterialCommunityIcons name="menu" size={32} color="#fff" style={{paddingLeft: 10}}/>
          </TouchableOpacity>
      </View>
    );
};

const drawerNavigator = new DrawerNavigator({
  AboutUs: { screen: aboutUsScreen },
  GetInvolved: { screen: getInvolvedScreen }
});

export default App = StackNavigator({
  Home: { screen: HomeScreen },
  Menu: { screen: MainMenu },
  Drawer: {screen: drawerNavigator},   
  Cases: {
    screen: caseStudiesScreen,
    navigationOptions: ({ navigation }) => ({
      headerLeft: <DrawerButton navigation={navigation} />,
    }),
  }, 
});`

**Comment by keshk26** [comment]
You need to check the index of navigation.state, Open and close the drawer based on the index(0 or 1). Something like this:
`const MenuButton = (props) => {
  const { navigate } = props.navigation
  const routeIndex = props.navigation.state.index
  return (
    <View>
      <TouchableOpacity onPress={() => { routeIndex === 0 ? navigate('DrawerOpen') : navigate('DrawerClose') }}>
        <Image source={require('png')} />
      </TouchableOpacity>
    </View>
  )
}`

**Comment by Patrick-Bayer** [comment]
Hey guys, i am trying to nest a DrawerNavigator inside of a StackNavigator. The Drawer Menu should open when pressing the MenuButton. Unfortunately i keep getting the error: Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in.

Any help is appreciated. Here is my code

`const MenuButton = () => {
  return( 
  <View>
    <TouchableOpacity onPress={() => {this.props.navigation.navigate('DrawerOpen')} }>
      <Icon name="bars" style={{color: 'white', padding: 10, marginLeft:10, fontSize: 20}}/>
    </TouchableOpacity>
  </View>
  );
};

const Main = DrawerNavigator({

  Home: { screen: Home },
  Profile: { screen: Profile },
  },
  {
    navigationOptions: ({ navigation }) => ({
      headerLeft : <MenuButton navigate={navigation.navigate} />,
    }),
});

const Application = StackNavigator({
  
  //Screens of the app that you can navigate to
  Login: { screen : Login },
  Main: { screen: Main },
  },
  {
    navigationOptions: {
      
      headerStyle: {
        marginTop: Expo.Constants.statusBarHeight
      }
    }
});

export default class App extends Component {

  render() {
    return <Application/>;
  }
}`

**Comment by peni4142** [comment]
I need help, too.
@X-Tender 
Can you please show the working code?

**Comment by cesarbuenrostro-tiempodev** [comment]
Solution here !!! https://reactnavigation.org/blog/#drawer-routes-have-been-replaced-with-actions

**Comment by vinayclecotech** [comment]
import React,{Component} from 'react'
import {Text,Button,ScrollView,View,StyleSheet,Image,MenuButton} from 'react-native'
import {createDrawerNavigator,NavigationActions,createBottomTabNavigator} from 'react-navigation'
import PropTypes from 'prop-types';

class MyHomeScreen extends React.Component {
  static navigationOptions = {
    drawerLabel: 'Home',
    drawerIcon: ({ tintColor }) => (
      <Text>1</Text>
    ),
  };

  render() {
    return (
      <Button
        onPress={() => this.props.navigation.navigate('Notifications')}
        title="Go to notifications"
        
      />
    );
  }
}

class MyNotificationsScreen extends React.Component {
  static navigationOptions = {
    drawerLabel: 'Notifications',
    drawerIcon: ({ tintColor }) => (
      <Text>2</Text>
   ),
  };

  render() {
    return (
      <Button
        onPress={() => this.props.navigation.goBack()}
        title="Go back home"
      />
    );
  }
}

const styles = StyleSheet.create({
  icon: {
    width: 24,
    height: 24,
  },
});

 const MyApp = new createDrawerNavigator({
  Home: {
    screen: MyHomeScreen,
    home:HomeScreen,
    Settings: SettingsScreen,
  
  },
  Notifications: {
    screen: MyNotificationsScreen,
  },
});


class HomeScreen extends React.Component {

  static navigationOptions = {
    drawerLabel: 'Home',
    drawerIcon: ({ tintColor }) => (
      <Text>NEW</Text>
    ),
  };

  render() {
    return (
      <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
        <Text>home</Text>
        <Image
        source="https://unsplash.com/photos/ZYLmudR28SA"
        
      />
        
      </View>
    );
  }
}

class SettingsScreen extends React.Component {
  render() {
    return (
      <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
        <Text>Settings!</Text>
      </View>
    );
  }
}

  const myapp=new createBottomTabNavigator({
    
       
    screen:MyApp,
  Home: HomeScreen,
  Settings: SettingsScreen,
  
}); 
export default myapp;



i want to add both tab navigation as well as drawer navigation but some error is occur. can anybody check it

**Comment by linux08** [comment]
Hi guys, I have this
` <TouchableOpacity
      onPress={() => {
        if (!navigation.state.isDrawerOpen) {
          navigation.dispatch(DrawerActions.openDrawer());
        } else {
          navigation.dispatch(DrawerActions.closeDrawer());
        }
      }}
    >
      <Ionicons name={leftIcon} color="white" size={35} />
    </TouchableOpacity>`
If i double click the hamburger button app crashes

**Comment by iuliuvisovan** [comment]
Try like this: `navigation.openDrawer();` works for me

**Comment by NickyMwangi** [comment]
This one worked for me..
`HomeScreen.navigationOptions = ({navigation}) => ({
header : (
<Button OnPress = {() => navigation.openDrawer()}
)
});`

**Comment by damianlattenero** [comment]
This one worked for me:

`static navigationOptions = ({navigation}) => ({
        title: "MyTiTle",
        headerRight: <TouchableOpacity
            onPress={() => navigation.toggleDrawer()}
        >
            <Image
                source={require('/assets/drawerMenu/icon-menu.png')}
                style={{width: 26, height: 26, resizeMode: 'contain', align: 'right', marginTop: 8}}
            />
        </TouchableOpacity>,
       moreProps: 
...
...
...
`

**Comment by JOnathanST29** [comment]
OLD :> **_navigation.navigate(‘DrawerOpen’)_** 
NEW :> **navigation.openDrawer()**

> New API for creating navigators
> It is now easier to create and maintain custom navigators. The new createNavigator API fully decouples the navigation view from the router. Information about each screen is available on a single "descriptor", including the pre-computed child navigation prop, allowing you to focus on custom navigation views.
> 
> Custom navigators can now provide actions helpers for their screens. For example, the new drawer navigator now allows props.navigation.openDrawer() within its screen components.
> 
> This does not impact most users - you won't need to make any changes for this unless you use custom navigators in your app. Read more about the changes in RFC 2. Also read the custom navigators documentation. You can also watch the "Creating a navigator" section in this talk to learn more.
> 
> Trivial breaking changes
> The following changes are considered “trivial” because you will only need make straightforward and mechanical changes to update your app for them.
> 
> Drawer routes have been replaced with actions
> Rather than opening a drawer with navigation.navigate(‘DrawerOpen’), you can now call navigation.openDrawer(). Other methods are closeDrawer() and toggleDrawer().

**Comment by NotTooReact89** [comment]
The new method does not work for me. the drawer opens and closes by itself instead of just opening when clicked on headerLeft menu icon.

**Comment by 123dma** [comment]
static navigationOptions = ({ navigation }) => {
        return {
        title: 'Home',
        headerLeft: (
          < Icon name="menu" size={30} style={{marginStart:10}} backgroundColor="#000000" onPress={() => navigation.openDrawer()} > < /Icon>
        ),
      };
    };

**Comment by kumien** [comment]
Hi.
I uses NavigationDrawer in my code written in Typescript and I have a problem with type. What kind of type is param **navigation** in **_navigationOptions_**? DrawerNavigation isn't exported but it looks like this is correct one.

**Comment by sebitoelcheater** [comment]
```
import { DrawerActions } from '@react-navigation/native';
...
<Stack.Navigator
      initialRouteName="LoadingScreen"
      screenOptions={({navigation}) => ({
        headerLeft: () => (
          <Appbar.Action icon="menu" onPress={() => navigation.dispatch(DrawerActions.toggleDrawer())}/>),
      })}
    >
...
</Stack.Navigator>
```
worked for me

**Comment by guymross** [comment]
That the most common use case requires such ugly workarounds is baffling.
