### ISSUE TITLE
[Docs] Inaccurate docs for `navigationOptions`

### ISSUE THREAD

**Issue by Andreyco** [react-community/react-navigation#1124]
Docs for `navigationOptions` say

```
**headerRight** 
String or React Element to display on the right side of the header

**headerLeft** 
String or React Element to display on the left side of the header
```

Apparently this is not true - it fails on strings.

react-native: 0.43.3
react-navigation: https://github.com/react-community/react-navigation.git#4c55887

**Comment by AlanFoster** [comment]
@Andreyco The docs are for the unreleased `1.0.0-beta.8`, whilst npm only has `1.0.0-beta.7` available

**Comment by Andreyco** [comment]
@AlanFoster I understand that. Check commit logs for changes after #4c55887, but no change is related `headerLeft` or `headerRight` prop. Given this, docs will be invalid for `1.0.0-beta.8` as well.

**Comment by grabbou** [comment]
The docs were corrupted. PR pending.
