### ISSUE TITLE
TabNavigator being wrongly re-rendered

### ISSUE THREAD

**Issue by santiagopoli** [react-community/react-navigation#1126]
Hi,

I have a view which renders a "TabBar" (which is a TabNavigator that receives the screens for each tabs as props). For example (i'll skip some implementation details because they are not important):

```javascript
const getTabFor = (listItems) => () => <View><FlatList items={listItems} .../>...</View>

const FavoritesView = ({ movies, tvShows }) =>
  <View style={{ flex:1 }}>
       <FavoritesTabBar moviesTab={getTabFor(movies)} tvShowsTab={getTabFor(tvShows)} />
  </View>
```
FavoritesView is then connected to redux and provided with both the lists of movies and tv shows from the store.

The code in FavoritesTabBar is:

```javascript
const tab = (tabContent, iconName) => ({
    screen: tabContent,
    navigationOptions: {
        tabBarIcon: ({ tintColor }) => <Icon name={iconName} size={24} color={tintColor} />
    }
});

const tabs = (moviesTab, tvShowsTab) => ({
    Movies: { ...tab(moviesTab, MOVIES_ICON) },
    Shows: { ...tab(tvShowsTab, TVSHOWS_ICON) }
})

const tabProperties = {
    animationEnabled: true,
    tabBarOptions: {
        activeTintColor:  platformSpecific({ ios: '#0d9958', android: 'white' }),
        labelStyle: { fontWeight: platformSpecific({ ios: '400', android: 'bold' }) },
        style: { backgroundColor: platformSpecific({ ios: '#ecf0f1', android: '#0dbb58' }) },
        indicatorStyle: { backgroundColor: '#0d9958', height: 3.5 }
    }
}

export default ({ moviesTab, tvShowsTab }) => {
    let Component = TabNavigator(tabs(moviesTab, tvShowsTab), tabProperties);
    return <Component/>
}
```

The problem is that if the user is navigating on the "TV Shows" tab (the second tab) and the store changes to add movies or tvShows, the TabBar re-renders and the navigation changes back to the Movies tab (the first tab). In short, any change on movies or tvShows takes the TabBar to the first tab. The problem becomes more apparent when you do a "Pull-To-Refresh" in the tvShows list and it goes back to movies.

I know this happens because FavoritesTabBar depends on the props provided by FavoritesView, and because movies and tvShows are props of that view, changes are propagated to it. The part I don't understand is why the TabBar STATE changes when there are changes in props. If I'm navigating on the second tab and the props changes, React knows which parts of the views needs to be updated, so I don't know why this is happening.

I solved this problem by letting FavoritesView to be dumb and actually connecting each tab screen to the part of the store it needs (and putting them directly on the TabBar instead of passing them as a prop). But from a cohesive point of view, I want FavoritesView to be the one which is provided with the movies and tvShows props. The TabBar is only an implementation detail and I may change it to another component.

So my question really is: What i'm doing wrong? Why a little change on the props triggers re-rendering of all the TabNavigator?

Thanks in advance!

**Comment by santiagopoli** [comment]
The code in FavoritesTabBar is:

```
const tab = (tabContent, iconName) => ({
    screen: tabContent,
    navigationOptions: {
        tabBarIcon: ({ tintColor }) => <Icon name={iconName} size={24} color={tintColor} />
    }
});

const tabs = (moviesTab, tvShowsTab) => ({
    Movies: { ...tab(releasesTab, MOVIES_ICON) },
    Shows: { ...tab(snapshotsTab, TVSHOWS_ICON) }
})

const tabProperties = {
    animationEnabled: true,
    tabBarOptions: {
        activeTintColor:  platformSpecific({ ios: '#0d9958', android: 'white' }),
        labelStyle: { fontWeight: platformSpecific({ ios: '400', android: 'bold' }) },
        style: { backgroundColor: platformSpecific({ ios: '#ecf0f1', android: '#0dbb58' }) },
        indicatorStyle: { backgroundColor: '#0d9958', height: 3.5 }
    }
}

export default ({ moviesTab, tvShowsTab }) => {
    let Component = TabNavigator(tabs(moviesTab, tvShowsTab), tabProperties);
    return <Component/>
}
```

**Comment by santiagopoli** [comment]
A demonstration of the problem:

![bug](https://cloud.githubusercontent.com/assets/759695/25210249/7db8a52a-2555-11e7-9438-22ff9f750892.gif)
![bugandroid](https://cloud.githubusercontent.com/assets/759695/25210250/7dd29f98-2555-11e7-8acd-421f49a9b379.gif)

**Comment by srounce** [comment]
I'm having this same issue with just a TabRouter. It's children are unmounted/destroyed then constructed/mounted when a navigation prop change happens.

**Comment by santiagopoli** [comment]
That's probably the case... Inner views are always recreated. I don't think that's the expected behavior.

**Comment by santiagopoli** [comment]
The problem in my case is because I'm creating a new navigator on every render (as shown in the following snippet). But i don't know how to fix that... The underlying implementation of TabView seems very difficult to understand

```
export default ({ moviesTab, tvShowsTab }) => {
    let Component = TabNavigator(tabs(moviesTab, tvShowsTab), tabProperties);
    return <Component/>
}
```

**Comment by JakeGinnivan** [comment]
You need to memoize the creation.

```
import memoize from 'lodash.memoize'

const createTabNav = memoize((moviesTab, tvShowsTab, tabProperties) => (
    TabNavigator(tabs(moviesTab, tvShowsTab), tabProperties)
))
```

Memoize remembers the last returned result based on the props passed.

**Comment by santiagopoli** [comment]
Sadly, memoizing doesn't work because the imputs of the function are actually changing.

**Comment by santiagopoli** [comment]
Related to https://github.com/react-community/react-navigation/issues/1160

**Comment by spencercarli** [comment]
Hi! Since this issue has been quiet for a while I'm going to go ahead and close it. If the issue persists in the latest version of React Navigation please re-open!

**Comment by TheRusskiy** [comment]
@spencercarli sadly it's still happening

**Comment by TheRusskiy** [comment]
I figured that this can be solved by connecting nested router to the main one like described here:
https://reactnavigation.org/docs/intro/nesting#Nesting-a-Navigator-in-a-Component
