### ISSUE TITLE
Break with the new Expo version 16

### ISSUE THREAD

**Issue by EQuimper** [react-community/react-navigation#1129]
The new Expo make use of Reactv16 and I think this is what cause this break.

<img width="487" alt="screen shot 2017-04-19 at 11 28 41 pm" src="https://cloud.githubusercontent.com/assets/15819498/25212379/f4544f0c-2557-11e7-9f11-93e775f7dab0.png">

**Comment by EQuimper** [comment]
Resolve with the new update react-navigation@1.0.0-beta.8

**Comment by ChenLi0830** [comment]
Helo @EQuimper, unfortunately updating to 1.0.0-beta.8 doesn't work for me

**Comment by mdeprezzo** [comment]
beta.8 still have some bugs unfortunately, guys. Some options still not working.

**Comment by Vishwas1** [comment]
Has anyone got its solution??
