### ISSUE TITLE
Redux integration with containerOptions

### ISSUE THREAD

**Issue by Ehesp** [react-community/react-navigation#113]
I've got my app working with Redux following [the redux guide](https://reactnavigation.org/docs/guides/redux). I'd also like to integrate Deep Linking, which requires `createNavigationContainer` to be passed. through. 

I'm struggling to understand from the docs:

1) What component am I supposed to pass into `createNavigationContainer`?
2) Where/how do I then handle incoming deep links and other things?

Sorry if this is the wrong place, I'll update the docs if needed as it's not too clear to me!

Cheers

**Comment by meno1** [comment]
I'm lost as well.

**Comment by vascogaspar** [comment]
+1

**Comment by satya164** [comment]
Where does it say that you have to use `createNavigationContainer`? I cannot find any mention of it in the redux guide or deeplink guide.

**Comment by vascogaspar** [comment]
I'm trying to implement deep linking with a top level TabNavigator with nested StackNavigators for each tab but without success. I'm using [this project as reference](https://github.com/parkerdan/SampleNavigation) and I would like to navigate to the second view on first Tab navigator using a deep link like `myapp://second`. @satya164 do you have any ideas on this? Thanks in advance

**Comment by grabbou** [comment]
We should probably send a PR that described `how` to handle deep linking when using Redux. Anyone in this issue, feel free to send it over.

Here's what you need to do, having the following `App` component: 
```
class App extends React.Component {
  render() {
    // dispatch and nav are from Redux,
    // see https://reactnavigation.org/docs/guides/redux#Redux-Integration
    return (
      <AppNavigator navigation={addNavigationHelpers({
        dispatch: this.props.dispatch,
        state: this.props.nav,
      })} />
    );
  }
}
```
change it to:
```
class App extends React.Component {
  componentDidMount() {
      Linking.addEventListener('url', ({ url }: { url: string }) => {
        this._handleOpenURL(url);
      });

      Linking.getInitialURL().then(
        (url: string) => url && this._handleOpenURL(url),
      );
    }

   componentWillUnmount() {
      Linking.removeEventListener('url', this._handleOpenURL);
   }
  
  _urlToPathAndParams(url: string) {
      const params = {};
      const delimiter = '://';
      let path = url.split(delimiter)[1];
      if (!path) {
        path = url;
      }
      return {
        path,
        params,
      };
    }

  _handleOpenURL = (url: string) => {
      const parsedUrl = this._urlToPathAndParams(url);
      if (parsedUrl) {
        const { path, params } = parsedUrl;
        const action = AppNavigator.router.getActionForPathAndParams(path, params);
        if (action) {
          this.props.dispatch(action);
        }
      }
    };

  render() {
    return (
      <AppNavigator navigation={addNavigationHelpers({
        dispatch: this.props.dispatch,
        state: this.props.nav,
      })} />
    );
  }
}
```

**Comment by grabbou** [comment]
> Where/how do I then handle incoming deep links and other things?

See my comment https://github.com/react-community/react-navigation/issues/1189#issuecomment-296628829 and specifically, those lines https://github.com/react-community/react-navigation/blob/master/src/createNavigationContainer.js#L164

**Comment by joncursi** [comment]
Sorry, but I'm still confused on this. I read through the issues and inspected the source, but I'm not having any luck. Could anyone drop in a sample of how they got deep linking to work with redux? Maybe this is a good one to cover in the playground demo app.

**Comment by clycheng2015** [comment]
@grabbou Sorry,but I'm still confused on this. , the codes  createNavigationContainer.js#L164 in my node-module is save to what you said above , and I do as react-community#1189 (comment) ,but still do not work,it so terrible!I have no ideas! my package.json
 react": "^16.0.0-alpha.12",
 "react-native": "^0.48.1",
"react-navigation": "^1.0.0-beta.23",
