### ISSUE TITLE
Lot instances of screen 

### ISSUE THREAD

**Issue by vomchik** [react-community/react-navigation#1132]
I use default StackNavigator, after navigation in my application i got a lot  instances of screen 
It's normal? 
See attached for details.

![react native debugger - debugger session 1028272 active 2017-04-20 09-34-08](https://cloud.githubusercontent.com/assets/732085/25216728/a317c358-25ac-11e7-8043-a3c03cdacca1.png)

**Comment by Andreyco** [comment]
My first guess is redux interferes in some weird way. `react-navigation` on it's own should be no root of problem here.

**Comment by vomchik** [comment]
For redux connecting, i use this documentation  https://reactnavigation.org/docs/guides/redux.
Also, without redux, i have the same problem.

**Comment by vomchik** [comment]
My test case

1. Home screen, go to Setting screen
2. Setting screen 
 2.1 If i use **goBack** i got one instance of Home Screen 
 2.2 If i use **navigate**('Home screen') i got new instance of Home Screen

**Comment by vomchik** [comment]
Maybe this part of code must check existing instance of  screen?
https://github.com/react-community/react-navigation/blob/master/src/routers/StackRouter.js#L151

**Comment by wjwzwy** [comment]
I ran into the same issue. It seems that we need to use goBack or reset, but reset may cause other issues when you have multiple nested StackNavigator.

**Comment by grabbou** [comment]
Closing in favour of #706
