### ISSUE TITLE
Prevent opening multiple views on double click

### ISSUE THREAD

**Issue by yqbk** [react-community/react-navigation#1135]
Occasionally when I double click on a button that is navigating me to a new screen, I get 2 screens open instead of one.

![Double click issue](https://cloud.githubusercontent.com/assets/6362599/25222145/e58a1da2-25b7-11e7-8278-63f835245686.gif)

How can I prevent such a behaviours?

**Comment by MDDemirci** [comment]
Prevent navigating twice when clicking a button quickly #271

**Comment by akhtarvahid** [comment]
I am also facing the same problem as @yqbk mentioned above...please anybody suggest or help.
Thanks

**Comment by ue** [comment]
This issue fixed with latest version, I guess after v2.0 or try upper 👍 @akhtarvahid

**Comment by vinceprofeta** [comment]
@ue it does not appear to be fixed

**Comment by dauane** [comment]
Best solution I found so far:
https://snack.expo.io/@patwoz/withpreventdoubleclick

It worked perfectly for me. Try it out!

**Comment by brentvatne** [comment]
https://reactnavigation.org/blog/2018/05/07/react-navigation-2.0.html#navigateroutename-in-stacknavigator-is-less-pushy
