### ISSUE TITLE
Infinite loop on Navigation Option title

### ISSUE THREAD

**Issue by lorenzsell** [react-community/react-navigation#1139]
I'm having a really strange issue that I can't wrap my head around involving trying to set the title dynamically.  When I make a call to state.params.mainTitle, the app goes into an infinite loop and I can't figure out why.

```
class MainScreen extends Component {
  static navigationOptions = {
      title: ({ state }) => { return state.params.mainTitle; }
  };

  componentWillMount() {
    this.props.navigation.setParams({ mainTitle: this.props.space.spaceName });
  }
```

If I just set the title function to return 'Home' it works fine:

```
  static navigationOptions = {
      title: ({ state }) => { return 'Home'; }
  };
```

Am I doing something wrong here?

**Comment by aalices** [comment]
I think I've got a similar problem. I am calling `setParams` in `componentWillReceiveProps` and also check if the parameters are set. First, the check always leads to false (`navigation.state.params` is `undefined`). Because of that `setParams` is called and there comes the loop and app hangs.

**Comment by AhsanAk** [comment]
I'm having the same issue.

Any solution?

**Comment by pongponglau** [comment]
I have the same problem. May i ask if there is any solution?

Thanks a lot

**Comment by donnes** [comment]
Same problem here

**Comment by rxb** [comment]
Updating props in a function that is called every time props are updated gives you an infinite loop.

Not sure of how to update the title otherwise.

**Comment by kelset** [comment]
Pinging OP @lorenzsell since this issue is quite old and related to an old version of the lib. If no answer I'll close in 7 days.

Btw I think @rxb solution is the way to go.

**Comment by kelset** [comment]
Hi there @lorenzsell, 

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue (especially if it's a bug report) please open a new issue that uses the new Issue Template to provide some more details to help us solve it.
