### ISSUE TITLE
withNavigation in react-navigation@1.0.0-beta.8

### ISSUE THREAD

**Issue by jurajkrivda** [react-community/react-navigation#1140]
Failed context type: The context `navigation` is marked as required in `withNavigation(branch(NavigationContainer))`, but its value is `undefined`.
    in withNavigation(branch(NavigationContainer)) (created by _class)

**Comment by skevy** [comment]
Thanks for the report. I'd continue using 1.0.0-beta.7 (which is now re-published under the `latest` npm tag) until we get a chance to iron out some of the bugs in 1.0.0-beta.8. We'll publish beta 9 with fixes.

**Comment by grabbou** [comment]
Can you post a full example of how you are using `withNavigation`?

**Comment by jurajkrivda** [comment]
```
import { branch, compose, renderComponent } from 'recompose';
import { withNavigation } from 'react-navigation';


export default compose(
  withNavigation,
  maybeUser,
)(Component);



```

**Comment by nihgwu** [comment]
```
export default compose(
  maybeUser,
  withNavigation,
)(Component);
```

**Comment by jurajkrivda** [comment]
@nihgwu Order doesn't matter

**Comment by spencercarli** [comment]
Is this still an issue in the latest version of react-navigation?

**Comment by kelset** [comment]
Closing since OP never replied in months.
