### ISSUE TITLE
Is react-navigation used in production?

### ISSUE THREAD

**Issue by wjwzwy** [react-community/react-navigation#1142]
Does anyone use react-navigation in production? It seems like there are some blocking issues.

**Comment by srounce** [comment]
Like what?

**Comment by DaleJefferson** [comment]
Animated replace is the big one for us. https://github.com/react-community/react-navigation/issues/351

**Comment by grabbou** [comment]
We are likely to roll it out soon with one of our apps. It's still beta and we are working towards decreasing the amount of issues.

Keep in mind some of them are questions.

Here's detailed discussion on road to stable: #723

**Comment by MarkEstefanos** [comment]
I'm trying to, but it's too slow and buggy. I'm going to have to migrate because my client deadline is sooner than this lib will be stable. 😭
