### ISSUE TITLE
Override navigation by addNavigationHelpers

### ISSUE THREAD

**Issue by vomchik** [react-community/react-navigation#1143]
Why we need this part of the code? https://github.com/react-community/react-navigation/blob/master/src/views/CardStack.js#L133? 

This code will override existing navigation which was created early, for example, when we making integration with redux https://reactnavigation.org/docs/guides/redux

**Comment by grabbou** [comment]
It will not. As you can see, it extends `navigation` from props. The only thing it does is that it changes the `state` to point to the screen that is being rendered.

**Comment by vomchik** [comment]
But, if i create own functions, like: navigate, setParams, go Back those will be overridden. l am right?

**Comment by grabbou** [comment]
Yes, they are helpers. You shouldn't need to provide any extra functions nor override those I believe - better to change routers.

Let me know what's your use-case and I'll try to provide some hints on how to achieve them :)
