### ISSUE TITLE
borderColor does not overwrite borderTopColor

### ISSUE THREAD

**Issue by thurt** [react-community/react-navigation#1145]
Hi,

I'm using TabBar.TabBarBottom as the component for my Tab navigator. I have also supplied a tabBarOptions style where I specify a custom borderColor for the TabBarBottom. The problem is my rule `borderColor` does not overwrite the default `borderTopColor` value specified in TabBarBottom https://github.com/react-community/react-navigation/blob/93976d358e27580e568ef016f820dc0253423aa7/src/views/TabView/TabBarBottom.js#L170

I assumed since `borderColor` is more generic than `borderTopColor` that it would overwrite the value with my value. you can also see in the source that my defined style would be applied after the default style https://github.com/react-community/react-navigation/blob/93976d358e27580e568ef016f820dc0253423aa7/src/views/TabView/TabBarBottom.js#L139 . However, i cannot get the TabBarBottom to display my color unless I make my rule use the same key `borderTopColor`. 

I suspect this is not really issue with `react-navigation` but one of the lower abstractions. Does anyone have insight on this? is this the intended behavior for react-native/yoga? I was under the impression that web CSS behavior is different from this, that `borderColor` would overwrite `borderTopColor`
https://jsbin.com/vimilarufi/edit?html,css,output

**Comment by grabbou** [comment]
This is an issue with the way `react-native` handles styling. It's not CSS spec compliant and differs in some places, like in this case. 

I am happy with the way it works since it aligns with how I think about defining styles, but you are good to open an issue at the `react-native` repo.

**Comment by thurt** [comment]
Thanks for the info !
