### ISSUE TITLE
Duplicate headers being rendered

### ISSUE THREAD

**Issue by Techdojo** [react-community/react-navigation#1146]
I have a StackNavigator that contains several screens - one of which is a either a Tab (iOS) or Drawer (Android) Navigator.   What I want to do is hide the header bar on a couple of the screens (ie the initial splash screen and the login screen) - the only option I can find is in the `navigationOptions: {}` entry for each screen is `visible: false`.  This hides the header text but the bar is still visible and on the screens in the Tab / Drawer section the header is rendered again so I have two instances visible.

Can anyone provide any help or assistance in sorting this out?
Thanks
8-)

**Comment by Techdojo** [comment]
Ok - so apparently (for anyone else looking for a similar resolution)
You just need to add '{ headerMode: 'none' }' as the second parameter to the call that creates the StackNavigator.

eg.

```
const platformSpecificNavigation = (Platform.OS === 'ios') ? MainStack : MainDrawer;

export const AppStack = StackNavigator({
  Splash: { screen: SplashPage, navigationOptions: { visible: false } },
  Login: { screen: LoginPage, navigationOptions: { title: 'Login' } },
  Main: { screen: platformSpecificNavigation },
},
{ headerMode: 'none' }
);
```

**Comment by enderandpeter** [comment]
In my experience, this was happening because I had accidentally assigned StackNavigators to my TabNavigator screens instead of just regular components.
