### ISSUE TITLE
Pushing one stack onto another does not render back button

### ISSUE THREAD

**Issue by davideweaver** [react-community/react-navigation#115]
I have the following navigation layout...

```
const DiscoverFilter = StackNavigator({
  FirstFilter: { screen: EmptyView },
  SecondFilter: { screen: EmptyView }
}, {
    headerMode: "float",
});

const DiscoverTab = StackNavigator({
  Discover: { screen: DiscoverView },
  DiscoverFilter: { screen: DiscoverFilter },
}, {
    headerMode: "none",
});
```

I start on screen **Discover** and use the following to push **DiscoverFilter**...

```
navigate("DiscoverFilter");
```

I know this is probably a very rare edge case, but I would like to have a back button appear at the top of the **FirstFilter** screen. It currently does not because **props.scene.index** is 0.

 If not automatically, then I would like to be able to manually add a back button. I don't see a way to manually add a back button. If I use **navigationOptions** to add a left button, how do I get access to **navigation** to call **goBack()**?

```
static navigationOptions = {
    title: "First Filter",
    header: ({ state, setParams }) => ({
      left: (
          <Button
            title="Back"
            onPress={ () => navigation.goBack() }  // how do I make this work?
          />
        )
    })
  }
```

**Comment by UladzimirKuzmin** [comment]
I have the same problem. It would be nice to get any advice how to fix it.

**Comment by davideweaver** [comment]
@UladzimirKuzmin Thanks for the help with the back button. That is a reasonable workaround for now. Also, I needed to add a null argument for my goBack call to work, goBack(null).

**Comment by satya164** [comment]
Added this issue to https://github.com/react-community/react-navigation/issues/88
