### ISSUE TITLE
Screen tracking and analytics for the first page

### ISSUE THREAD

**Issue by ericapply** [react-community/react-navigation#1150]
I need to track every screen view.
I already checked out https://reactnavigation.org/docs/guides/screen-tracking which works fine except for the very first screen.
The reason is because there is no action being fired when loading the first screen.
I can't be the first person who has this problem right?
I want to know how people get around solving this, hopefully without having to hard code within first screen component.
Thank you.

**Comment by grabbou** [comment]
You can use `componentDidMount` of a container, that renders e.g. your stack navigator. Since you know what will the `initialRoute` be, it's easy.

**Comment by debugpai** [comment]
This still doesn't work well with apps that persist user state when the user returns. Then the `initialRoute` can be different.
