### ISSUE TITLE
How can I find the document for older version of react navigation?

### ISSUE THREAD

**Issue by ttdung11t2** [react-community/react-navigation#1152]
I'm using react-navigation beta7 version and now it's upgraded to beta 8 and I got many errors on navigation headers. I come back with beta7 version but when I when I read document, I see a lots of change and it's not compatible with my version. How can I find the old documents?

**Comment by navid94** [comment]
Try here [https://github.com/react-community/react-navigation/tree/ecef7771e65450b3a493e47085e7c887c60d1000/docs](url)

**Comment by cooperka** [comment]
@ttdung11t2 here's a working link: https://github.com/react-community/react-navigation/tree/v1.0.0-beta.7/docs/guides. Just change "v1.0.0-beta.7" to whatever version you'd like to see.

**Comment by grabbou** [comment]
BTW, we are working on implementing website versioning.

**Comment by ttdung11t2** [comment]
Ok cool :)
