### ISSUE TITLE
The nested TabNavigator with  Redux.

### ISSUE THREAD

**Issue by guoliang1206** [react-community/react-navigation#1153]
My app has a login screen, and when I m login system, It show the Main screen, and user can switch the tabs to change the screen. but now, if i tap the 'History', it will back to the Login Screen, how to handle this? 

![simulator screen shot 2017 4 21 11 11 00](https://cloud.githubusercontent.com/assets/12846676/25261395/30ac55c6-2684-11e7-98ff-10f2599f0e88.png)
![simulator screen shot 2017 4 21 11 11 48](https://cloud.githubusercontent.com/assets/12846676/25261398/326ced80-2684-11e7-88d6-0299e09d633d.png)

This is my router config 
```

const MainScreen = TabNavigator({
    Map:{ screen: Map},
    History:{ screen:History},
});

export const AppNavigator = StackNavigator(
    {
        Main: { screen: MainScreen },
        Login: { screen: LoginScreen },
    },
    {
        headerMode:'screen',
    }
);


const AppWithNavigationState = ({dispatch, nav}) => {

    console.log('AppNavigator =================== ',AppNavigator);
    return (
        <AppNavigator navigation={addNavigationHelpers({ dispatch, state: nav })} />
    );


};


AppWithNavigationState.propTypes = {
    dispatch: PropTypes.func.isRequired,
    nav: PropTypes.object.isRequired,
};

const mapStateToProps = state => ({
    nav: state.nav,
});



export default connect(mapStateToProps)(AppWithNavigationState);

```

**Comment by guoliang1206** [comment]
```

function nav(state = initialNavState, action) {

    switch (action.type) {

        case LOGIN:{
            console.log('excute login operator ......',);
            return  AppNavigator.router.getStateForAction(NavigationActions.reset({
                index: 0,
                actions: [
                    NavigationActions.navigate({ routeName: 'Main'})
                ]
            }), state);
        }
        case LOGOUT:
            console.log('excute logout operator ......');
            return initialNavState;
        default:
            return initialNavState;
    }
}
```
I find the problem. if I click login  and go to the Tab screen, the reducer will trigger twice，one is LOGIN and one is default. I think the default is the tab action. So how to deal the tab action in the nested TabNavigator ?

**Comment by guoliang1206** [comment]
Because I can't catch the events of tab switch action, my reducer can't recognize the action, and return the initialNavState.

**Comment by guoliang1206** [comment]
#1059

**Comment by guoliang1206** [comment]
I found an information   I log the action in my reducer 

```
{
     type: 'Navigation/NAVIGATE',
     routeName: 'History',
     params: undefined,
     action: undefined
 }
```
I think this is the tab switch action, if we return the right state in this case, I guess the problem solved.

**Comment by guoliang1206** [comment]
It is really effective,
for the tab switch Action


in my Actions.js file,
```
const NAVIGATE = 'Navigation/NAVIGATE';
```
in my Reducer.js file,
```
case NAVIGATE:
            console.log('excute tab navigator ......',action.routeName);
            return AppNavigator.router.getStateForAction(NavigationActions.navigate({ routeName: action.routeName }), state);
```

now I got a nested navigator (StackNavigator and TabNavigator) with Redux.

**Comment by TuangWang** [comment]
it's not working
