### ISSUE TITLE
Do not define components during render

### ISSUE THREAD

**Issue by jbrodriguez** [react-community/react-navigation#11536]
### Current behavior

the app works, but we get an eslint warning 

```
Do not define components during render. React will see a new component type on every render and destroy the entire subtree’s DOM nodes and state (https://reactjs.org/docs/reconciliation.html#elements-of-different-types). Instead, move this component definition out of the parent component “Tabs” and pass data as props. If you want to allow component creation in props, set allowAsProps option to true
```

this is the code

```
<Tab.Navigator
  screenOptions={({ route }) => ({
    tabBarIcon: (props) => <TabItem name={route.name} {...props} />,
    headerShown: false,
  })}
>
  <Tab.Screen name="One" component={One} />
  <Tab.Screen name="Two" component={Two} />
</Tab.Navigator>
```

i need to pass the route.name in order to set the icon and need `props` due to the focused property

any thoughts ?

### Expected behavior

we shouldn't receive an eslint warning

### Reproduction

https://github.com/react-navigation/react-navigation

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.1.7
| @react-navigation/bottom-tabs          | 6.5.8
| @react-navigation/drawer               | 6.6.3
| @react-navigation/native-stack         | 6.9.13
| react-native-safe-area-context         | 4.7.1
| react-native-screens                   | 3.24.0
| react-native-gesture-handler           | 2.9.0
| react-native-reanimated                | 3.4.2
| react-native-tab-view                  | 3.1.1
| react-native-pager-view                | 6.2.0
| react-native                           | 0.71.12
| node                                   | 18.16.0
| npm or yarn                            | 1.22.19

**Comment by jbrodriguez** [comment]
thank you, the react-native-tab-view component is not active in relation to the issue presented

**Comment by satya164** [comment]
> > You're getting warning from the ESLint rules you're using, it's not a bug in React Navigation. The options like `tabBarIcon` are functions that return a React element, while they look similar to components, they aren't used as components so the warning is a false positive.
> 
> 
> 
> Hello, the same happens when you use `navigation.setOptions` to update a button (in this use case https://reactnavigation.org/docs/header-buttons/#header-interaction-with-its-screen-component). Can we ignore the warning?

Yes

**Comment by VariabileAleatoria** [comment]
> while they look similar to components, they aren't used as components so the warning is a false positive.

Care to elaborate why?

**Comment by VariabileAleatoria** [comment]
> @VariabileAleatoria
> 
> > Care to elaborate why?
> 
> Components are used like `<ComponentName />`. React Navigation doesn't use `tabBarIcon` like that, it's called as a function (`tabBarIcon()`).

Being React Components functions that takes props and returns JSX I don't understand what the difference is and above all why the warning should be a false positive.

**Comment by satya164** [comment]
@VariabileAleatoria returning JSX doesn't make something a component. whether something is a component or not doesn't depend how the definition looks, but how it is used - if it's not used like `<ComponentName />`/with `React.createElement` then it's not a component.

**Comment by mateoLorenzo** [comment]
I fixed this warning passing a function to tabBarIcon instead of a component:

```js
const renderTabIcon = (name: string, color: string) => {
  return <Icon name={name} size={25} color={color} />;
};

<Tab.Screen
   options={{
      title: 'Home',
      tabBarIcon: ({color}) => renderTabIcon('home-outline', color),
   }}
   name="HomeScreen"
   component={HomeScreen}
/>
```

**Comment by kirkalvar** [comment]
Here’s how I resolved the warning by following the instructions in this document https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/no-unstable-nested-components.md

You have to declare the component outside of the parent "BottomTabBar" to prevent React from discarding the state of the nested components every time the parent component re-renders

```js
const TabIcon = ({props}) => (
  <TabItem name={route.name} {...props} />
);

const BottomTabBar = () => {
  <Tab.Navigator
  screenOptions={({ route }) => ({
    tabBarIcon: TabIcon,
  })}
>
  <Tab.Screen name="One" component={One} />
</Tab.Navigator>
}
```

**Comment by shaquibimdad** [comment]
> Here’s how I resolved the warning by following the instructions in this document https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/no-unstable-nested-components.md
> 
> You have to declare the component outside of the parent "BottomTabBar" to prevent React from discarding the state of the nested components every time the parent component re-renders
> 
> ```js
> const TabIcon = ({props}) => (
>   <TabItem name={route.name} {...props} />
> );
> 
> const BottomTabBar = () => {
>   <Tab.Navigator
>   screenOptions={({ route }) => ({
>     tabBarIcon: TabIcon,
>   })}
> >
>   <Tab.Screen name="One" component={One} />
> </Tab.Navigator>
> }
> ```

how you getting route.name? outside screenOptions?  by default tabBarIcon props are passed to TabIcon function

**Comment by shaquibimdad** [comment]
![image](https://github.com/user-attachments/assets/a49e5910-67d9-4d40-b2af-ede590e01c90)
