### ISSUE TITLE
How to Overflow Tab Bar Icon for Android

### ISSUE THREAD

**Issue by rad182** [react-community/react-navigation#1154]
Hi, I'm trying to replicate the Facebook Messenger tabs where the Camera button overflows the tab bar. Currently testing this with the sample code NativePlayground.

Under SimpleTabs.js i also added showIcon for tabBarOptions and tabBarPosition to be "bottom".
I modified this code and added margin bottom.
```js
MyChatScreen.navigationOptions = {
  tabBar: {
    label: 'Chat',
    icon: ({ tintColor, focused }) => (
      <Ionicons
        name={focused ? 'ios-chatboxes' : 'ios-chatboxes-outline'}
        size={26}
        style={{ color: tintColor, marginBottom: 20 }}
      />
    ),
  },
};
```
Results
iOS
<img width="375" alt="screen shot 2017-04-21 at 12 25 53 pm" src="https://cloud.githubusercontent.com/assets/71201/25262890/fea4142e-268d-11e7-88bc-90ac5b763f96.png">

Android
<img width="511" alt="screen shot 2017-04-21 at 12 26 02 pm" src="https://cloud.githubusercontent.com/assets/71201/25262893/048690e2-268e-11e7-8354-efc8746f9d57.png">

Seems to be fine on iOS but for android there's a top view blocking the icon. 
Is there any way to achieve this? TIA

**Comment by konrad-marzec** [comment]
http://stackoverflow.com/questions/41912313/element-overflow-hidden-in-react-native-android
React Navigator uses `react-native-tab-view` you should open issue on react-native-tab-view github.

**Comment by rad182** [comment]
thanks @konrad-marzec but still no luck. here's my code
```js
MyChatScreen.navigationOptions = {
  tabBar: {
    label: 'Chat',
    icon: ({ tintColor, focused }) => (
      <View
        style={{ backgroundColor: 'transparent' }}
        pointerEvents={'box-none'}
      >
        <Ionicons
          name={focused ? 'ios-chatboxes' : 'ios-chatboxes-outline'}
          size={26}
          style={{
            marginBottom: 20,
          }}
        />
      </View>
    ),
  },
};
```

**Comment by grabbou** [comment]
As suggested, please raise this issue in tab-view repository.

**Comment by pongponglau** [comment]
I have the same overflow issue in Android. I have an overflow menu as header above the tab bar. May i ask if there is any solution?

Thanks

**Comment by guoliang1206** [comment]
@ all , does there has a clearly way to solve this issue? I have search and search much websites and issues, I can't find the effective method

**Comment by damathryx** [comment]
anyone solved this?

**Comment by AmirHosseinSalari** [comment]
Did you find the answer?

**Comment by xclidongbo** [comment]
@abuinitski  I implemented this style, but under Android, the top half of the raised picture doesn't respond to an event.
![image](https://user-images.githubusercontent.com/10287985/62922650-7a138600-bdde-11e9-81b7-f1533560bd89.png)

**Comment by Ahmad-Saleem** [comment]
did you solve this issue?

**Comment by Ahmad-Saleem** [comment]
![image](https://user-images.githubusercontent.com/6362562/63649089-35b6ad00-c731-11e9-9289-6a3d05e9c2e6.png)
i have the same issue here

**Comment by muzammil-triffort** [comment]
Any solution for this?

**Comment by brendan1809** [comment]
try using "zIndex"

**Comment by seunghyun-woo** [comment]
In my case, using bottomTabNavigator instead materialBottonTabNavigator helped.

**Comment by RomuloACP** [comment]
> ![image](https://user-images.githubusercontent.com/6362562/63649089-35b6ad00-c731-11e9-9289-6a3d05e9c2e6.png)
> i have the same issue here

Did you fix this issue?

**Comment by jcarlostoledos** [comment]
> @abuinitski I implemented this style, but under Android, the top half of the raised picture doesn't respond to an event.
> ![image](https://user-images.githubusercontent.com/10287985/62922650-7a138600-bdde-11e9-81b7-f1533560bd89.png)

Did you ever fix this? I have the exact same problem.

**Comment by brendan1809** [comment]
> > @abuinitski I implemented this style, but under Android, the top half of the raised picture doesn't respond to an event.
> > ![image](https://user-images.githubusercontent.com/10287985/62922650-7a138600-bdde-11e9-81b7-f1533560bd89.png)
> 
> Did you ever fix this? I have the exact same problem.

try using hitslop

**Comment by Bojan996** [comment]
Guys, any solutions for the overlay part that doesn't respond to an event?

**Comment by sallar** [comment]
I solved it by wrapping my center button in `View`. Previously the topmost component was `TouchableOpacity` and was getting cut in Android. As soon as I replaced the component wrapper with a `View` and made the actual circle `TouchableOpacity` the problem went away!

![image](https://user-images.githubusercontent.com/768052/103903664-db8b7180-5104-11eb-8b14-d777565ce3b2.png)

**Comment by inimist** [comment]
I am having this issue and it is unresolved. @sallar I did not get you. I have my icon wrapped in View already. Here is the code:

`return <View style={styles.view__icon_add}><Ionicons style={{}} name={iconName} size={size} color={color} /></View>`

**Comment by inimist** [comment]
@sallar I do not use TouchableOpacity because tabs switch automatically. I am using "`@react-navigation/bottom-tabs`" I even tried placing <TouchableOpacity> tags around the icon but it did not help.

**Comment by psudocode** [comment]
> @jcarlostoledos, @Bojan996 or anyone else who ends up here, I ran into the same issue but resolved it by importing `TouchableOpacity` from `react-native-gesture-handler` instead of `react-native`.

Thanks, this is work, and I will be using it for now.
But it raises another problem; it will fire the button underneath.

**Comment by hotaryuzaki** [comment]
> 

is it top part of your touchable can be click?

**Comment by hotaryuzaki** [comment]
> I solved it by wrapping my center button in `View`. Previously the topmost component was `TouchableOpacity` and was getting cut in Android. As soon as I replaced the component wrapper with a `View` and made the actual circle `TouchableOpacity` the problem went away!
> 
> ![image](https://user-images.githubusercontent.com/768052/103903664-db8b7180-5104-11eb-8b14-d777565ce3b2.png)

is it top part of your touchable can be click?

**Comment by hotaryuzaki** [comment]
> > @jcarlostoledos, @Bojan996 or anyone else who ends up here, I ran into the same issue but resolved it by importing `TouchableOpacity` from `react-native-gesture-handler` instead of `react-native`.
> 
> Thanks, this is work, and I will be using it for now. But it raises another problem; it will fire the button underneath.

yes its true.
it works but it will fire the button underneath.

@psudocode lu nemuin solusi gak bro?

**Comment by chennakt9** [comment]
> @jcarlostoledos, @Bojan996 or anyone else who ends up here, I ran into the same issue but resolved it by importing `TouchableOpacity` from `react-native-gesture-handler` instead of `react-native`.
yes it is working, but

is it possible to restrict the firing of the button underneath ?

**Comment by hjt-ghasemi** [comment]
> I solved it by wrapping my center button in `View`. Previously the topmost component was `TouchableOpacity` and was getting cut in Android. As soon as I replaced the component wrapper with a `View` and made the actual circle `TouchableOpacity` the problem went away!
> 
> ![image](https://user-images.githubusercontent.com/768052/103903664-db8b7180-5104-11eb-8b14-d777565ce3b2.png)

it works for me too. thank you
