### ISSUE TITLE
How to prevent push more than once when tapping button too fast

### ISSUE THREAD

**Issue by MingLoan** [react-community/react-navigation#1158]
I have a button in my app to navigate screen, if I tapping the button too fast. Screen will bee pushed more than once. 

Anyone can help to explain it and guide me how to do.

**Comment by navid94** [comment]
Already answered here #271
I created the navigateWithDebounce action like explained by dzuncoi comment, then set the timeout according to your needs.

**Comment by jaygarcia** [comment]
I was going to solve this on my end by listening to transition start and end, but your solution is way better, @navid94

**Comment by grabbou** [comment]
Duplicate of https://github.com/react-community/react-navigation/issues/135
