### ISSUE TITLE
Replace tab bar component dynamically ?

### ISSUE THREAD

**Issue by chetankotkar** [react-community/react-navigation#1160]
export const Tabs = TabNavigator({
 tab1: {
   screen: screen1,
   },
 tab2: {
   screen: screen2,
 },
 tab3: {
   screen: screen3,
 },
}

suppose I am on tab2 which containing screen2 now I want to replace the screen2 with screen4 on tab2 on button press. how do we do it. please guide.

**Comment by santiagopoli** [comment]
This is somewhat related to https://github.com/react-community/react-navigation/issues/1126

**Comment by cooperka** [comment]
@chetankotkar there are some answers here that might help: https://github.com/react-community/react-navigation/issues/717.

**Comment by spencercarli** [comment]
Hi! Since this issue has been quiet for a while I'm going to go ahead and close it. If the issue persists in the latest version of React Navigation please re-open!

**Comment by havinhthai** [comment]
@chetankotkar Could you do it?
