### ISSUE TITLE
How to hide the indicator of TabNavigator

### ISSUE THREAD

**Issue by xwpongithub** [react-community/react-navigation#1161]
I am trying to hide the indicator of TabNavigator,but I couldn't find any option to do that

**Comment by grabbou** [comment]
What do you mean by `indicator`?

**Comment by MyGuySi** [comment]
I suspect @xwpongithub means the colored indicator on the Android tab bar. You could try using (I hadn't tested it):

```
tabBarOptions: {
  indicatorStyle: {
    opacity: 0
  }
}
```

**Comment by xwpongithub** [comment]
As you said to do so I can achieve the desired effect, thank you, MyGuySi !

**Comment by mgtitimoli** [comment]
I know this is already closed, but I just wanted to leave a better way to do this for anyone who could land here in the future...

Instead of passing an indicatorStyle with opacity 0, it would be better to not render the indicator at all :wink:, and to do that it's just a matter of passing the following option:

```javascript
renderIndicator: () => null
```

Cheers.

**Comment by wfly-git** [comment]
@mgtitimoli Im trying to customize the Indicator,but it does not work.It is displayed above.Any suggustion?

**Comment by mgtitimoli** [comment]
@wfly-git I've just seen your message, are you using renderIndicator fn to do that or some other way?

**Comment by wfly-git** [comment]
@mgtitimoli Yes,like this
`renderIndicator: () => <Image ...>`

**Comment by deejain** [comment]
@wfly-git: I was able to get this working by putting the renderIndictor property in the tabBarOptions section.  Here's a sample.

`
export const AppNavigator = TabNavigator(
  {
    screenA:  screen1
  },
  { 
     screenB: screen2
  },
  {
     tabBarOptions: {
        renderIndicator: () => null
     }
  }
`
I hope that helps.

**Comment by aman-technyx** [comment]
REF IMAGE -> https://ibb.co/ncj7Cbs

are you guying talking about this ? how can i hide this in landscape mode ?
