### ISSUE TITLE
Statusbar tapping issue when there is scrollview things inside screen

### ISSUE THREAD

**Issue by mnkang89** [react-community/react-navigation#1165]
Expected Behavior:
when scrollview's(I'm using flatlist) option scrollsToTop is set to true
screen will scroll up to top if i tapped statusbar.

Actual Behavior:
It works when there is only one tab mounted in my tabnavigator, but when i pressed more tabs i cannot scrolls up by tapping statusbar. I think there is some overlapping issues between tabs in tabnavigator.

version:
"react-native": 0.42.0,
"react-navigation": "1.0.0-beta.8"

**Comment by spencercarli** [comment]
Can you create an example of this issue on [Snack](https://snack.expo.io)?

**Comment by kelset** [comment]
Closing since OP never replied in months. (and related to old version of lib - if still the case, open a new issue that follows the Issue Template)
