### ISSUE TITLE
Navigation Card Stack like animation in android?

### ISSUE THREAD

**Issue by XeniousSoftware** [react-community/react-navigation#1169]
can we have animation like the following video on Android by using StackNavigator?

https://www.youtube.com/watch?v=0e8Irs4gi3M

**Comment by Pacn91** [comment]
I'm struggling with this too... I want my transitions to be like iOS but I have no idea how to do it... i'm really noob at react-native, if someone could post some example/guide I would be thankful!

P.S: Sorry about my terrible english xD

**Comment by grabbou** [comment]
You can set custom `transitionConfig` to provide a custom animation https://reactnavigation.org/docs/navigators/stack#StackNavigatorConfig. For a more advanced, on per screen animations, see #175
