### ISSUE TITLE
Android back button stops working with redux integration

### ISSUE THREAD

**Issue by eranbes** [react-community/react-navigation#117]
When one passes `addNavigationHelpers({dispatch, state})` as `navigation` prop by hand, the android back button leaves the app instead of firing the back action.

Root cause seems to be that `BackAndroid` handler is only installed when `this._isStateful()` in `createNavigationContainer.js`.

**Comment by RyanMitchellWilson** [comment]
I'm getting this problem as well.

**Comment by CoteViande** [comment]
It's mentioned at the end of the doc on integrating redux that it is something that you need to implement. You should look at the BackAndroid in react native.

**Comment by mikeaxle** [comment]
@CoteViande Hey, does this code have to be on every screen that needs to be able to go back?

**Comment by CoteViande** [comment]
Only in your root Component, called `App.js` in most architectures. You want to define this listener on app start, if you want to disable it on certain screens, you should do so in the `shouldCloseApp` function.

**Comment by vladbars** [comment]
I fixed it in AppWithNavigationState :

```javascript
@connect(state => ({
  nav: state.nav,
  }))
export class AppWithNavigationState extends Component {
    shouldCloseApp(nav) {
      return nav.index == 0;
    }
    componentDidMount() {
      BackAndroid.addEventListener('backPress', () => {
        const {dispatch, nav} = this.props
        if (this.shouldCloseApp(nav)) return false
        dispatch({
          type: 'Navigation/BACK'
        })
        return true
      })
    }

    componentWillUnmount() {
      BackAndroid.removeEventListener('backPress')
    }
    render() {
      return (
        <AppNavigator navigation={addNavigationHelpers({
          dispatch: this.props.dispatch,
          state: this.props.nav
        })} />
        );
    }
  }
```

**Comment by fbarrailla** [comment]
To avoid deprecation warning on `react-native@0.44`, you should use `BackHandler` instead of `BackAndroid`

```javascript
class AppWithNavigationState extends Component {
  componentDidMount() {
    BackHandler.addEventListener('hardwareBackPress', this.onBackPress);
  }
  componentWillUnmount() {
    BackHandler.removeEventListener('hardwareBackPress', this.onBackPress);
  }
  onBackPress = () => {
    const { dispatch, nav } = this.props;
    if (nav.index === 0) {
      return false;
    }
    dispatch(NavigationActions.back());
    return true;
  };
  render() {
    const { dispatch, nav } = this.props;
    return (
      <AppNavigator
        navigation={addNavigationHelpers({ dispatch, state: nav })}
      />
    );
  }
}
```

**Comment by l3lackcurtains** [comment]
@fbarrailla I'm getting this error by using your solution, 
`Cannot read property 'addEventListener' of undefined`
 Instead I used the deprecated solution but, I want to solve the problem with **BackHandler**.

**Comment by fbarrailla** [comment]
@l3lackcurtains , are you using `react-native 0.44` ?

**Comment by andrepcg** [comment]
@l3lackcurtains I was having the same issue because I was importing BackHandler from react instead of react-native

**Comment by l3lackcurtains** [comment]
I solved the problem by using 
> react-native 0.44
@fbarrailla  thanks..

**Comment by lxcid** [comment]
Many of the solution here didn't help me. I was digging the codebase and figured out that when you provides your own `navigation` to the Navigator, [the Navigator will no longer subscribe to back button because it is no longer stateful](https://github.com/react-community/react-navigation/blob/99cd4604b402852765592aa52b00e4d4933518e0/src/createNavigationContainer.js#L150-L152).

My solution is to extends the DrawerNavigator and subscribe it manually, then dispatch the action through redux.

```js
class RootNavigator extends DrawerNavigator(
  {
    AppScreen: { screen: AppNavigator },
  },
  {
    contentComponent: DrawerContent,
  },
) {
  static propTypes = {
    navigation: PropTypes.shape({
      dispatch: PropTypes.func.isRequired,
    }).isRequired,
  };

  componentDidMount() {
    super.componentDidMount();

    this.subs = BackHandler.addEventListener('hardwareBackPress', () =>
      this.props.navigation.dispatch(NavigationActions.back()),
    );
  }
}
```

Hopefully this will help you solve your issue.

**Comment by Morriz** [comment]
I see everybody using the same check:
```
shouldCloseApp(nav) {
      return nav.index == 0;
}
```
But nav.index is always 0 when you use one root navigator, so it always leaves the app...drama!

**Comment by jankalfus** [comment]
Here's how to handle properly back button press on Android when using a DrawerNavigator:
https://gist.github.com/jankalfus/ccb0d0b4023cb6ab3b4aee4e49f4590b

**Comment by cvrajeesh** [comment]
as @Morriz mentioned, checking for `nav.index == 0` inside `shouldCloseApp` won't work well in nested navigator scenarios.

This check works for me

```
shouldCloseApp = nav => {
    if (nav.index > 0) return false;

    if (nav.routes) {
      return nav.routes.every(this.shouldCloseApp);
    }

    return true;
  }
```

**Comment by iesteban** [comment]
It worked for me mixing the solutions of @jankalfus and @cvrajeesh. 

Check it here:
https://gist.github.com/iesteban/724227c2dc1364066473dee5bbfc304d

Also being used here: https://github.com/Semillas/SemillasReactNative/blob/upgrade-react-native/App/Navigation/ReduxNavigation.js

**Comment by simonarcher** [comment]
is there a way to manage this with Stack Navigation?

I have a tabbed navigation. on my index.0 tab, the user can click on an item which takes them into the detail page of that item.
With the current implementation above, when the user clicks back the 'nav.index' is still on 0, so it closes. I can't find a way to determine if the user is currently in a stack and to rather go back up the stack till the root page, and only then close the app.

Am i complicating things for myself?

**Comment by edolix** [comment]
Any updates to have working `hardwareBackPress` event with `StackNavigator` ?

**Comment by animaonline** [comment]
This one works on a StackNavigator

    const { dispatch, state } = navigatorRef;
    if (state.nav.routes[state.nav.index].index === 0) { return false }

**Comment by mstadius** [comment]
I am using React Native 0.55.2 and React Navigation 2.5.1. I have Android back button support set up with stack navigators inside tab navigators by keeping track of current and previous visible screen in the navigation reducer and checking on back button press if the screen changed. If it did not change the stack navigators default screen is visible and the app should be closed. This also works for modal stack navigators.

Here is my reducer
```js
import Navigator from '@src/navigation/navigators'
import { createNavigationReducer } from 'react-navigation-redux-helpers'

// Source: https://reactnavigation.org/docs/en/screen-tracking.html
function getActiveRouteName(navigationState) {
  if (!navigationState) {
    return null;
  }
  const route = navigationState.routes[navigationState.index];
  // dive into nested navigators
  if (route.routes) {
    return getActiveRouteName(route);
  }
  return route.routeName;
}

var navReducer = createNavigationReducer(Navigator);

export default (state, action) => {
  var new_state = navReducer(state, action);

  // update only when a navigation action is fired
  if(action.type.substr(0,11) === 'Navigation/'){

    // keeps name of current and previous screen
    new_state._previousRouteName = getActiveRouteName(state);
    new_state._activeRouteName = getActiveRouteName(new_state);
  }

  return new_state;
}

```

And the navigator

```js

/**
 * Custom navigator with android back button support
 * BaseNavigator is the root navigator
 */
export default class Navigator extends Component {

  static router = BaseNavigator.router;

  componentDidMount() {
    BackHandler.addEventListener('hardwareBackPress', this.onBackPress);
  }
  componentWillUnmount() {
    BackHandler.removeEventListener('hardwareBackPress', this.onBackPress);
  }
  onBackPress = () => {
    this.props.navigation.pop();

    // check if screen has changed after popping state. If screen did not change
    // current screen is a tab home screen
    const screenChanged = (this.props.navigation.state._activeRouteName !== this.props.navigation.state._previousRouteName);

    // if false is returned app is closed
    return screenChanged;
  };

  render() {
    return <BaseNavigator {...this.props} />;
  }
}
```

**Comment by fbarrailla** [comment]
@NooruddinLakhani ,

These examples referred to a documentation about Redux integration:
https://reactnavigation.org/docs/en/redux-integration.html
