### ISSUE TITLE
Cannot pass params between DrawerNavigator's children

### ISSUE THREAD

**Issue by isazon4ik** [react-community/react-navigation#1170]
I am using react-native and using the Drawer Navigator and I am unable to pass props to other screens. I followed the example from the docs, but still unable to resolve the issue.

My code:
>const handleFixNavigator = DrawerNavigator({
>    Fix: {screen:FixScreen},
>    Handle: {screen: HandleScreen}
>});
>
>this.props.navigation.navigate('Handle', {name:'a'})

It navigate to Handle but params.name is undefined, but if i use StackNavigator instead of DrawerNavigator, it works, what happened?

**Comment by jeffreymendez1993** [comment]
^ They both should work the same but do not. I do not understand either.

**Comment by Louis345** [comment]
There is an on going issue 
https://github.com/react-community/react-navigation/issues/1072

A fix has been put in place, but waiting for it to be approved.
