### ISSUE TITLE
Is there a way to force TabNavigator to re-render itself?

### ISSUE THREAD

**Issue by geemaple** [react-community/react-navigation#1171]
As far as I know, a component will be triggered to render itself when its state is changed or forceUpdate function is called explicitly. How to accomplish this with navigators?

**Comment by jszcl** [comment]
I have the same problem.

**Comment by zakster12** [comment]
+1 I am also looking for the same...

**Comment by grabbou** [comment]
Can you explain what you mean? The title is not clear.

**Comment by suano** [comment]
I have the same problem.we just need re-render itself when navigation to same screen but different params

**Comment by AhsanAk** [comment]
I have got the same problem when I pass the screenProps through TabNavigator it doesn't update itself when my screenProps change.

**Comment by MarkRich** [comment]
same

**Comment by dgurns** [comment]
+1

**Comment by 3DEsprit** [comment]
I believe this could be considered the same as #577 , with the tab-navigator not rendering when changing state or props.

**Comment by DaveCole** [comment]
+1

**Comment by joelandplus** [comment]
This problem still exists in react-navigation (beta11).

**Comment by ajostergaard** [comment]
I have a similar issue on beta11, DrawerNavigator not re-rendering when screenProps passed to navigationOptions change.

**Comment by JasonHenson** [comment]
I can't get tabBarLabel to update until I change tabs. l  have tried screenProps={{ ...this.props }} to see if copying props would force the component to update, but nothing works.

**Comment by hectorhottomali** [comment]
So I was having the same issue, I have 2 tabs, 1 is the complete contact list, and the second is the favorites tab.

The solution was quite easy (after 4 hours), the idea is to redo the whole label, so when it is clicked "onPress" it will use navigation.navigate and update a parameter each time, in this case I am sending a date parameter with "new Date()" each time

```
const ContactTabs = TabNavigator(
    {
        ContactList: {
            screen: ContactList,
            navigationOptions: ({navigation}) => ({
                tabBarLabel: ({ tintColor }) => <TouchableOpacity onPress={()=>navigation.navigate('ContactList', {date: new Date()})} style={{flex: 1, alignItems:'center', justifyContent: 'center'}}><Text>All</Text></TouchableOpacity>,
            }),
        },
        Favorites: {
            screen: Favorites,
            navigationOptions: ({navigation}) => ({
                tabBarLabel: ({ tintColor }) => <TouchableOpacity onPress={()=>navigation.navigate('Favorites', {date: new Date()})} style={{flex: 1, alignItems:'center', justifyContent: 'center'}}><Text>Favorites</Text></TouchableOpacity>,
            }),
        },
    })
```



After this in my Favorites component screen you can just call componentWillReceiveProps() so you can update your states or data.

```
export default class Favorites extends Component {
    ...

    componentWillReceiveProps() {
        console.log('rerender here')
        //this.yourFunction()
        //this.setState({})
    }

```

Hope this helps you.

**Comment by kelset** [comment]
Pinging OP @geemaple since this issue is quite old and related to an old version of the lib. If no answer I'll close in 7 days.

Moreover, @hectorhottomali solution seems viable.

**Comment by ajostergaard** [comment]
@kelset really? That solution seems quite a hack to me and not very React at all. Having said that, I am no longer sure there is a problem when wired properly. Will have to check tomorrow.

**Comment by kelset** [comment]
Well, the usage of date it's not a really good idea, yes, but the overall concept (in a situation where you are not using redux) to have some sort of "trigger" that forces an update is not bad.

And, again, this is referred to an old issue (22 Apr) which last comment was posted on Aug 15 - so tbh I don't know if it is still required, a lot happened since then.

**Comment by kelset** [comment]
Hi there @geemaple , 

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue (especially if it's a bug report) please open a new issue that uses the new Issue Template to provide some more details to help us solve it. (so @ajostergaard since you haven't reported back still I invite you to open a new issue if that's the case)

**Comment by TylerPin** [comment]
My problem:
There's 3 tabs, A,B,C and each has their own unread count when push notification is received. 

While in screen A I need to be able to update screen C's unread count, without navigating to screen C.

I tried to reference the count to screenProps. Similar to @AhsanAk 's and facing the same problem.

My solution:
I ended up hiding the tab bar, and implement my own tab bar view in render(). Same design as the tab bar, but now I have reference to it and can update the UI easily.
`static navigationOptions = ({ navigation }) => ({
      tabBarLabel: 'Media',
      header: null,
      tabBarVisible: false,
   });`

 and I'm still using Tab Navigator to utilise each Tab maintain their own Stack Navigator behaviour.

only caveat is Tab Navigator's swiping behaviour will see 2 sets of tab icons between the screens.

**Comment by nickjuntilla** [comment]
What version of which software fixes this problem? I am using  react-navigation ^2.13.0 and still don't get any re-renders when props change.

**Comment by isaaclem** [comment]
I've found a more "elegant" way of achieving re-rendering
```
// HomeScreen.js
...
import { NavigationEvents } from "react-navigation";
class HomeScreen extends React.Component {
  render() {
    return (
      <View>
        <NavigationEvents
          onWillFocus={() => {
            //Call whatever logic or dispatch redux actions and update the screen!
          }}
        />
        <Text>Home</Text>
      </View>
    );
  }
}
```

credits to [https://itnext.io/handle-tab-changes-in-react-navigation-v2-faeadc2f2ffe](url)

**Comment by sherifelkelesh** [comment]
Write this in the screen you want to rerender

componentDidMount() {
        this._navListener = this.props.navigation.addListener('didFocus', () => {
            // get your new data here and then set state it will rerender
          });
    }
and if you don't have access to the navigation prop use withNavigation from react navigation
Hope this helps you.

**Comment by cso01** [comment]
I wanna thank the @sherifelkelesh for the suggest, this function worked very well on my project.

Thank you man, you saved my life ;)

**Comment by setanallas** [comment]
im using bottomTabNavigator and still cant re-render my view

i try to use <Code>navigationEvent</Code> but its never fired, 
<Code> 
class HistoryScreen extends Component {
  render() {
    return (
      <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
      <NavigationEvents
        onWillFocus={payload => console.log('will focus',payload)}
        onDidFocus={payload => console.log('did focus',payload)}
        onWillBlur={payload => console.log('will blur',payload)}
        onDidBlur={payload => console.log('did blur',payload)}
      />
        <Text style={{color: 'red'}}>HistoryScreen!</Text>
      </View>
    );
  }
}

export default HistoryScreen;
</Code>

neither when im using <Code>addlister in componenDidMount()</Code> its not fired too
<Code>
class HistoryScreen extends Component {
  componentDidMount() {
    this._navListener = this.props.navigation.addListener('didFocus', () => {
      // get your new data here and then set state it will rerender
      console.log("did focus history");
    });
  }

  componentWillUnmount() {
    this._navListener.remove();
  }
  render() {
    return (
      <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
        <Text style={{color: 'red'}}>HistoryScreen!</Text>
      </View>
    );
  }
}

export default HistoryScreen;
</Code>

can someone tell where my code is wrong? and how to fix it.

**Comment by Johncy1997** [comment]
```
const MainTab = createMaterialTopTabNavigator({
    [RouteNames.MainTab.Tab1]:{
        screen: HomeStack
    },
    [RouteNames.MainTab.Tab2]:{
        screen: SecondStack
    },
    [RouteNames.MainTab.Tab3]:{
        screen: ThirdStack
    },
    [RouteNames.MainTab.Tab4]:{
        screen: FourthStack
    },
    [RouteNames.MainTab.Tab5]:{
        screen: FifthStack
    },
    [RouteNames.MainTab.Tab6]:{
        screen: SixthStack
    }
},{
    initialRouteName: RouteNames.MainTab.Tab1,
    tabBarComponent: props => {

        return(<CustomTab {...props} hideBack={props.navigation.state.routes[props.navigation.state.index].index === 0?true:false}/>)}
});
```

when hideBack changes, the tabBarComponent never changed. I tried by changing state, navigation params, normal component props. Nothing works! Anyone please explain how to fix it?

**Comment by mtt786** [comment]
After searching too much i only found by changing initialroutename in component to reload tab content using state.  createMaterialBottomTabNavigator not updating component content if i using same component with different props.

`import React, {Component} from 'react';
import * as Config from 'app/config';
import {createAppContainer} from 'react-navigation';
import {createStackNavigator} from 'react-navigation-stack';
import {createMaterialBottomTabNavigator} from 'react-navigation-material-bottom-tabs';
import {TouchableOpacity, View} from 'react-native';
import Icon from 'app/components/icon';
import Orders from './Orders';

class Home extends Component {
    static navigationOptions = ({navigation}) => {
        return {
            title: navigation.getParam('oTitle', 'MY ORDERS (Ready)'),
            headerLeft: (
                <TouchableOpacity
                    style={{marginLeft: 20}}
                    onPress={() => navigation.toggleDrawer()}>
                    <Icon
                        family="FontAwesome5"
                        name="hamburger"
                        size={25}
                        color="#fff"
                    />
                </TouchableOpacity>
            ),
        };
    };

    constructor(props) {
        super(props);
        this.state = {
            initialRouteName: 'Ready',
        };
    }

    render() {
        const {initialRouteName} = this.state

        let BottomTabs = createAppContainer(
            createMaterialBottomTabNavigator(
                {
                    Ready: {
                        screen: props => (
                            <Orders status={'Ready'} {...props} />
                        ),
                        navigationOptions: {
                            // tabBarLabel:'Home',
                            tabBarIcon: ({tintColor}) => (
                                <View>
                                    <Icon
                                        family={'MaterialCommunityIcons'}
                                        color={tintColor}
                                        size={20}
                                        name={'developer-board'}
                                    />
                                </View>
                            ),
                            tabBarOnPress: ({navigation, defaultHandler}) => {
                                this.setState({initialRouteName: 'Ready'});
                            },
                        },
                    },
                    Picked: {
                        screen: props => (
                            <Orders status={'Picked'} {...props} />
                        ),
                        navigationOptions: {
                            // tabBarLabel:'Home',
                            tabBarIcon: ({tintColor}) => (
                                <View>
                                    <Icon
                                        family={'MaterialCommunityIcons'}
                                        color={tintColor}
                                        size={20}
                                        name={'bike'}
                                    />
                                </View>
                            ),
                            tabBarOnPress: ({navigation, defaultHandler}) => {
                                this.setState({initialRouteName: 'Picked'});
                            },
                        },
                    },
                    Delivered: {
                        screen: props => (
                            <Orders status={'Delivered'} {...props} />
                        ),
                        navigationOptions: {
                            // tabBarLabel:'Home',
                            tabBarIcon: ({tintColor}) => (
                                <View>
                                    <Icon
                                        family={'MaterialCommunityIcons'}
                                        color={tintColor}
                                        size={20}
                                        name={'home-circle'}
                                    />
                                </View>
                            ),
                            tabBarOnPress: ({navigation, defaultHandler}) => {
                                this.setState({initialRouteName: 'Delivered'});
                            },
                        },
                    },
                },
                {
                    initialRouteName,
                    activeColor: '#f0edf6',
                    inactiveColor: '#3e2465',
                    backBehavior: 'history',
                    barStyle: {backgroundColor: Config.COLOR_PRIMARY},
                    lazy: false,
                },
            ),
        );

        return <BottomTabs />;
    }
}

export default createStackNavigator(
    {
        Home: {
            screen: Home,
        },
    },
    {
        initialRouteName: 'Home',
        defaultNavigationOptions: {
            headerStyle: {
                backgroundColor: Config.COLOR_PRIMARY,
                elevation: 0, // remove shadow on Android
                shadowOpacity: 0, // remove shadow on iOS
            },

            headerTintColor: '#fff',
            headerTitleStyle: {
                fontWeight: 'normal',
            },
        },
    },
);
`

**Comment by ax-vasquez** [comment]
> For anyone looking for the solution, see https://github.com/react-navigation/react-navigation/issues/1171#issuecomment-461839823 above

@sherifelkelesh thank you so much for this solution! I got this in place and it works like a charm. 

I'm still relatively new to react native, so just to make sure I understand why this works - it seems as though this solution _relies_ on the fact that `react-navigation-tabs` doesn't unmount the component when the user navigates to a different tab, which is how that `_navListener` variable stays defined (even if the user goes to a different tab) - is this correct?

**Comment by nickjuntilla** [comment]
You have to use a plugin that gives you the onFocus event.

**Comment by ax-vasquez** [comment]
@nickjuntilla I didn't need to add anything.

The solution provided by @sherifelkelesh worked for me out-of-the-box without the need for additional plugins since this solution just makes a local reference to an `onFocus` handler. Until his solution, nothing else I found would allow me to re-render the component. Since I am using redux, I just re-fetch the relevant props in the `onFocus` listener that @sherifelkelesh showed how to make by calling the relevant action creator(s).

I was more interested in just learning more about how @sherifelkelesh 's solution worked, which I already have implemented and working. Thanks for the suggestion, though!

**Comment by nickjuntilla** [comment]
@ax-vasquez You are correct react-navigation-tabs does not unmount the component so you have to manually trigger onFocus or componentDidUpdate if your props have changed.

**Comment by ax-vasquez** [comment]
@nickjuntilla Awesome, thanks for the info!

**Comment by obo20** [comment]
For me the listener event was slightly different: 

```
        const {navigation} = this.props;
        navigation.addListener('focus', () => {
             //do your thing here
        });
```

**Comment by GuilhermeTrivilin** [comment]
If you are using React Navigation 5.X, just do the following:

```
import { useIsFocused } from '@react-navigation/native'

export default function App(){

const isFocused = useIsFocused()

    useEffect(() => {
        //Update the state you want to be updated
    } , [isFocused])
}
```

**Comment by francismaria** [comment]
I was having the same issue but @obo20 solution worked for me. Thanks!

**Comment by raarts** [comment]
@GuilhermeTrivilin for me this resulted in:

```
Error: Couldn't find a navigation object. Is your component inside a screen in a navigator?

This error is located at:
    in App (at withExpoRoot.js:21)
    in RootErrorBoundary (at withExpoRoot.js:20)
    in ExpoRoot (at renderApplication.js:40)
    in RCTView (at AppContainer.js:101)
    in DevAppContainer (at AppContainer.js:115)
    in RCTView (at AppContainer.js:119)
    in AppContainer (at renderApplication.js:39)

useNavigation
    useNavigation.tsx:16:6
useIsFocused
    useIsFocused.tsx:10:48
App
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:123620:46
```

**Comment by akzone** [comment]
> If you are using React Navigation 5.X, just do the following:
> 
> ```
> import { useIsFocused } from '@react-navigation/native'
> 
> export default function App(){
> 
> const isFocused = useIsFocused()
> 
>     useEffect(() => {
>         //Update the state you want to be updated
>     } , [isFocused])
> }
> ```

This works. Thank you.

**Comment by akzone** [comment]
@GuilhermeTrivilin

This works. Thank you.

**Comment by rikinshah23** [comment]
@GuilhermeTrivilin 

I am using React Navigation 5.X. I tried your solution. 
My initialRouteName is 'Home' but want to go to 'Notifications' tab when certain condition is met.

I have tried below code but it does not seem to update the state and change the tab. 

@akzone - Could you also look into this? Thanks 
```
    useEffect(() => {
    //Update the state you want to be updated
    console.log('Update the state you want to be updated')
    setInitialScreen('Notifications')
  }, [isFocused])

    <Tab.Navigator
      style={{ backgroundColor: theme.colors.header }}
      initialRouteName={initialScreen}
      sceneAnimationEnabled={false}>
```

**Comment by deggertsen** [comment]
Same result as @raarts when using the solution proposed by @GuilhermeTrivilin with React Navigation 5.5

**Comment by mrgeek1995** [comment]
I answered it here:
https://stackoverflow.com/questions/62725949/react-native-flatlist-not-updating-after-context-changed/62726510?noredirect=1#comment110928561_62726510

**Comment by ubaidmoin** [comment]
You can unmount screens which will help it re-render screen each time by adding option in navigation screenOptions:

`unmountOnBlur: true`

You can do it in Tab & Drawer Navigations but not in Stack Navigation.
And you can also add unmount individual screen by adding same option in Tab or Drawer Screen option.

**Comment by ronherrema** [comment]
@ubaidmoin when I use your method I get a white flash each time I change tabs (in a bottom tab navigator). Is there a way to force the remounting of currently blurred screens?

**Comment by ubaidmoin** [comment]
> @ubaidmoin when I use your method I get a white flash each time I change tabs (in a bottom tab navigator). Is there a way to force the remounting of currently blurred screens?

yes you can remove the white flash by adding this prop in your NavigationContainer but it is a hack:
`<NavigationContainer theme={{ colors: { background: '#000' } }}>
{...}
</NavigationContainer>`
Please try to give background of your app instead of '#000', I used it because my app background was black.

**Comment by marcpope** [comment]
This is the best answer for v5. Works perfectly. 

> If you are using React Navigation 5.X, just do the following:
> 
> ```
> import { useIsFocused } from '@react-navigation/native'
> 
> export default function App(){
> 
> const isFocused = useIsFocused()
> 
>     useEffect(() => {
>         //Update the state you want to be updated
>     } , [isFocused])
> }
> ```

**Comment by marcpope** [comment]
**useIsFocused works perfect!**

`import {useIsFocused} from '@react-navigation/native';`

then useEffect in function:
```
const ShowsFavoriteList = () => {
  const isFocused = useIsFocused();
  const [isLoading, setLoading] = useState(true);
  const [data, setData] = useState([]);
  const url = 'https://myapi.com/getdata';

  useEffect(() => {
    fetch(url)
      .then((response) => response.json())
      .then((json) => setData(json))
      .catch((error) => console.error(error))
      .finally(() => setLoading(false));
  }, [isFocused]);

if (isLoading) {
    return (
      <View style={{flex: 1, paddingTop: 75, paddingBottom: 75}}>
        <ActivityIndicator />
      </View>
    );
  }

return (
    <View style={styles.container}>
      <FlatList
        data={data}
        renderItem={({item}) => <ShowBadge show={item} />}
        keyExtractor={(item) => item.showid}
      />
    </View>
  );
};

```

**Comment by ronherrema** [comment]
@ubaidmoin the problem with your suggestion is that it is precisely the background colour that I am changing (across all screens). Also, I haven't actually been able to get your suggested theme code to work in my NavitationContainer.

**Comment by ubaidmoin** [comment]
@ronherrema please try to use @marcpope suggestion then my suggestion is a hack that i used when i got stuck in this white flickering as i set background color to black as default.

**Comment by ronherrema** [comment]
useIsFocused works better than unMountOnBlur, but there is still a flash the first time I navigate to the other tabs.

**Comment by devanada** [comment]
> You can unmount screens which will help it re-render screen each time by adding option in navigation screenOptions:
> 
> `unmountOnBlur: true`
> 
> You can do it in Tab & Drawer Navigations but not in Stack Navigation.
> And you can also add unmount individual screen by adding same option in Tab or Drawer Screen option.

simplest method and worked

**Comment by ronherrema** [comment]
For me, unmountOnBlur causes a flash every time I switch tabs, whereas useIsFocused() at least causes a flash only the first time I go to that tab. It seems to me the problem lies with the inability to access in a granular way the native lifecycle. If I was working in iOS, for example, I would put these kinds of changes in viewWillAppear().

**Comment by mahiraltinkaya** [comment]
> Write this in the screen you want to rerender
> 
> componentDidMount() {
> this._navListener = this.props.navigation.addListener('didFocus', () => {
> // get your new data here and then set state it will rerender
> });
> }
> and if you don't have access to the navigation prop use withNavigation from react navigation
> Hope this helps you.

Hey bro;
How can I do this with useEffect?
