### ISSUE TITLE
createNativeStackNavigator + transparentModal cross-platform issues

### ISSUE THREAD

**Issue by z1haze** [react-community/react-navigation#11728]
### Current behavior

When using createNativeStackNavigator, and applying `presentation: 'transparentModal'` screenOptions, on iOS the modal correctly sits on top of the entire application, including tabs, despite the screen navigator being nested within a tabs navigator. this behavior is what I would expect for a transparentModal via the native stack navigator

### Expected behavior

On android, the modal appears as a child of the tabs, which is not ideal. These behavior should be consistent across platforms. I created a snack, but there has an error for `view config getter callback for component RNSScreen must be a function (received undefined). I tested this with a basic snack from your documentation and gave the same error. this is not my issue. Attacking a screenshot to show the issue as well.

<img width="1234" alt="image" src="https://github.com/react-navigation/react-navigation/assets/6024725/d03443bb-40f2-40ef-b287-965a843b67ae">

### Reproduction

https://snack.expo.dev/@z1haze/tab-navigation-%7C-react-navigation?platform=web

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |6.1.7
| @react-navigation/bottom-tabs          |6.5.8
| @react-navigation/stack                |6.3.17
| @react-navigation/native-stack         |6.9.17
| react-native-safe-area-context         |4.6.3
| react-native-screens                   |3.22.0
| react-native-gesture-handler           |2.12.0
| react-native-reanimated                |3.3.0
| react-native                           |0.72.6
| expo                                   |49.0.21
| node                                   |18.17.1
| npm                            |9.6.7

**Comment by satya164** [comment]
Native stack navigator exposes the native platform primitives for navigation - so they can have different behavior depending on the platform.

For modals, we recommend specifying them in the root stack instead of nesting inside tab navigators to avoid such issues.
