### ISSUE TITLE
Adding an optional callback function for each button in the TabBar

### ISSUE THREAD

**Issue by mehtamanan** [react-community/react-navigation#1176]
I want some additional flexibility with the Bottom TabBar so that I can execute a function every time a user selects a certain tab before navigating to the selected tab. 

For example: If a user is already on the home tab and he selects the home tab again, I want to fetch new data and show it to the user just like instagram does.

**Comment by jszcl** [comment]
I also need this feature very much

**Comment by skyworld** [comment]
I also need this feature very much

**Comment by grabbou** [comment]
Closing in favour of #314
