### ISSUE TITLE
Navigation Back

### ISSUE THREAD

**Issue by MingLoan** [react-community/react-navigation#1177]
why navigate.goBack({ numberOfPages: 2 }) does not work to pop more than 1 screen.

**Comment by grabbou** [comment]
There's no such option as `numberOfPages`. `goBack` pops a single scene.

**Comment by MingLoan** [comment]
@grabbou so I cannot pop more than one page or pop to root?

**Comment by grabbou** [comment]
No, in this case, you can dispatch a custom action and provide a custom `getStateForAction` that will modify the state.

See: https://reactnavigation.org/docs/routers/api#getStateForAction-action-state

and a bit old, but relevant example: https://github.com/react-community/react-navigation/issues/295#issuecomment-282561646
