### ISSUE TITLE
back button arrow will disappear after some operation

### ISSUE THREAD

**Issue by skyworld** [react-community/react-navigation#1178]
normal 
![image](https://cloud.githubusercontent.com/assets/4318550/25311971/e9eca0ec-283f-11e7-991f-6bc240aabfb4.png)

after some operation
![image](https://cloud.githubusercontent.com/assets/4318550/25311984/158105cc-2840-11e7-8469-87ca8fad7b55.png)

**Comment by AlanFoster** [comment]
@skyworld Is there more context to this issue? Do you have a minimal reproducible code sample?

**Comment by spencercarli** [comment]
Without a reproduction we can't help. Going to close this issue.

**Comment by samuela** [comment]
I'm also experiencing this. AFAICT, it occurs at random. Very concerning. It makes me think that there's no way I can deploy my app with react-navigation if the back button arrows will suddenly disappear for users.

**Comment by AlanFoster** [comment]
@samuela If you're able to provide a reproducible project for this bug, it will be possible to resolve this issue

**Comment by samuela** [comment]
@AlanFoster Understood. If I end up finding a repro I'll certainly provide an update. In any case, I can confirm that this is a real issue.

**Comment by MartinMasek** [comment]
The repro for me is stopping the Expo dev server

**Comment by brentvatne** [comment]
@MartinMasek - that makes sense and it should happen because the image is no longer available if the server is closed
