### ISSUE TITLE
Pushing to TabNavigator re-mounts all existing scenes

### ISSUE THREAD

**Issue by JesperLekland** [react-community/react-navigation#1185]
Expected: Pushing a scene to a TabNavigator mounts said scene and nothing else.
Actual: When pushing a scene to a TabNavigator all existing scenes gets re-mounted (with the addition of the pushed scene). 

EDIT: This seems to be true only for Android, i.e works as intended on iOS

**Comment by duongtranpyco** [comment]
Let's say we have a definition of TabRouter/TabNavigator below:
Tab:
---Screen 1
---Screen 2
---Screen 3
---Screen 4

If navigate to Screen 4, Screen 1 Screen 2 and Screen 3 will be mounted.

**Comment by phanthehien** [comment]
Same issue with you guys. Seem it will load the pre-ordered screens when using with TabRouter. Any solution?

**Comment by grabbou** [comment]
@duongtranpyco  Tabs are pre-loaded. TabNavigator has a `lazy` option to prevent that behaviour https://reactnavigation.org/docs/navigators/tab#TabNavigatorConfig

**Comment by JesperLekland** [comment]
This should be re-opened. The issue is not that tabs are pre-loaded, the issue is that when I add a new tab to the existins stack i.e tab1, tab2, tab3 -> tab1, tab2, tab3, tab4, the tabs 1-3 are re-mounted. This should not at all be necessary, the only tab that needs to be mounted is tab4

**Comment by grabbou** [comment]
I believe that this issue should be opened in `react-native` repository. `react-native-tab-view` (a library that provides us components under the hood), uses `ViewPagerAndroid` for tabs on Android (https://github.com/react-native-community/react-native-tab-view/blob/master/src/TabViewPagerAndroid.js#L142) whereas on iOS - a `ScrollView`. That explains differences in behaviour.

CC: @satya164

**Comment by phanthehien** [comment]
yes @grabbou, I agreed with you. it is because of the react-native-tab-view. As in Android it will use ViewPagerAndroid to render specific tab (also its sibling). Are there anyway to prevent that by replacing ViewPagerAndroid by another component?

**Comment by grabbou** [comment]
There's currently no such way. I believe we should work on fixing the issue rather than allowing changing that behaviour.

**Comment by phanthehien** [comment]
do you have any idea to fix that issue? @grabbou. It is great that you can share some ideas so we can start from?

**Comment by grabbou** [comment]
I'd start in `react-native` repository since that component is built-in to the core.

**Comment by ikshitapuri** [comment]
> This should be re-opened. The issue is not that tabs are pre-loaded, the issue is that when I add a new tab to the existing stack i.e tab1, tab2, tab3 (all have been mounted and rendered as expexted) -> tab1, tab2, tab3, tab4, then tabs 1-3 are re-mounted (componentDidMount is called). This should not at all be necessary, the only tab that needs to be mounted is tab4
> 
> As stated in the original issue it works as intended on iOS but not on Android @grabbou

Did you find a solution or workaround?
