### ISSUE TITLE
getStateForAction ignores initialRouteName

### ISSUE THREAD

**Issue by BarakChamo** [react-community/react-navigation#1186]
I'm using mobx to manage navigation state and noticed inconsistencies in initial routing between managed navigation and internal navigation state.

It seems that the `getStateForAction` helper chooses the routes that point to sub navigators as it goes down the tree. This is my code:

### Component:
```javascript
const SearchTabsNavigator = TabNavigator({
  [SOURCES.YOUTUBE]: { screen: containers.Search },
  [SOURCES.GIPHY]: { screen: containers.Search },
}, {
  tabBarPosition: 'top',
  tabBarOptions: {
    style: { backgroundColor: '#ffffff' },
    labelStyle: { color: '#e91e63' },
    indicatorStyle: { backgroundColor: '#e91e63' },
  },
  lazyLoad: true,
})

const SearchNavigator = StackNavigator({
  [ROUTES.FEATURED]: { screen: containers.Featured },
  [ROUTES.RESULTS]: { screen: SearchTabsNavigator },
}, { headerMode: 'none' })

const MainNavigator = TabNavigator({
  [ROUTES.CONTACTS]: {
    screen: containers.Contacts,
    navigationOptions: containers.Contacts.navigationOptions,
  },
  [ROUTES.HISTORY]: {
    screen: containers.History,
    navigationOptions: containers.History.navigationOptions,
  },
  [ROUTES.SEARCH]: {
    screen: SearchNavigator,
    navigationOptions: containers.Search.navigationOptions,
  },
}, {
  initialRoute: ROUTES.CONTACTS,
  tabBarPosition: 'bottom',
  tabBarOptions: {
    style: { backgroundColor: '#e91e63' },
    indicatorStyle: { backgroundColor: 'white' },
  },
  lazyLoad: true,
})

const ContentNavigator = StackNavigator({
  [ROUTES.MAIN]: { screen: MainNavigator },
  [ROUTES.PLAYER]: { screen: containers.Player },
}, {
  initialRouteName: ROUTES.MAIN,
})

const AppNavigator = DrawerNavigator({
  [ROUTES.APP]: { screen: ContentNavigator },
}, {
  initialRouteName: ROUTES.APP,
})


/*
* Define a top-level connected navigation container
*/

let Navigation = ({ router }) => (
  <AppNavigator
    navigation={addNavigationHelpers({
      dispatch: router.dispatch,
      state: router.navigationState,
    })}
  />
)
```

### Store:
```javascript
import { action, observable } from 'mobx'

import { ROUTES } from '../constants'

export default class NavigationStore {
  // Observable navigation state
  @observable.ref navigationState = null

  constructor(navigator) {
    // Keep reference to top-level navigator
    this.navigator = navigator

    // Set initial navigation state
    this.navigationState = navigator.router.getStateForAction(
      navigator.router.getActionForPathAndParams(ROUTES.MAIN),
    )
  }

  @action.bound dispatch = (navAction, stackNavState = false) => {
    const previousNavState = stackNavState ? this.navigationState : null
    this.navigationState = this.navigator
      .router
      .getStateForAction(navAction, previousNavState)

    return this.navigationState
  }
}
```

When initialized, the app ends up on the `ROUTES.SEARCH` view, which points to the sub navigator `SearchNavigator`, instead of `ROUTES.CONTACTS` which is set is `initialRouteName`. When `  [ROUTES.SEARCH]:...` is commented out, the navigator respects the initial route again, this is consistent across the tree for both `StackNavigator` and `TabNavigator`.

This is not an issue when disabling the navigation store and using the internal navigation state, it points correctly to the initial route even with the sub navigators included.

Again, the issue seems to lie in `navigator.router.getStateForAction` which when inspected, points to the wrong index.

**Comment by ericvicenti** [comment]
I'm not sure if this is the issue, but I see your `MainNavigator` sets the `initialRoute` and not the `initialRouteName`. Other than that, your code looks good!

If you're still having the issue, can you try writing a unit test for TabNavigator or TabRouter that demonstrates the bug? That will make it very clear what the problem is. The contributors guide has more details on running the tests. If you can help narrow down the bug with this test, please file this as a new issue!
