### ISSUE TITLE
Redux can not be used with deep linking

### ISSUE THREAD

**Issue by at-shakil** [react-community/react-navigation#1189]
Redux integration requires `navigation` prop to be passed to the top level navigator [[1]](https://reactnavigation.org/docs/guides/redux#Redux-Integration). Deep linking also requires `uriPrefix` prop to be passed to the top level navigator [[2]](https://reactnavigation.org/docs/guides/linking#URI-Prefix). But, a single navigator can't be passed `uriPrefix` and `navigation` prop both, at a time. This raises an error,

> This navigator has both navigation and container props, so it is unclear if it should own its own state.

Is there any way deep linking can be used with Redux? Or, maybe some workaround?

Note: Related issue #1106

**Comment by grabbou** [comment]
When passing `navigation` prop, you tell navigator that its navigation is coming from either Redux or parent navigator. That means it's not acting as a top-level navigator. `uriPrefix` is only respected if navigator is top-level.

In order to use Redux with deep linking, you should do something along these lines on your own: https://github.com/react-community/react-navigation/blob/master/src/createNavigationContainer.js#L159-L163

**Comment by at-shakil** [comment]
@grabbou Thank you so much for the solution. I followed your instruction and was able to integrate both Redux and deep linking successfully, except, the customized stack navigator and it's descendants in my implementation aren't receiving any header. (I understand, it has something to do with `CardStack`. But, couldn't get a clear idea from the doc. to resolve my issue)

What I am trying to achieve is just to update `uriPrefix`, but to retain all the other properties of `StackNavigator` as it is.

How should I modify the following code to generate a custom navigator that behaves exactly like a built-in `StackNavigator`?

or,

Am I utilizing the `uriPrefix` in a wrong way?

```
import React, { Component } from 'react';
import { createStore, combineReducers } from 'redux';
import { Text, View, Platform, Linking } from 'react-native';
import {
  StackNavigator, StackRouter, addNavigationHelpers, CardStack, createNavigator
  } from 'react-navigation';
import { Provider, connect } from 'react-redux';

const S1 = () => <View><Text>S1 text</Text></View>;
const S2 = () => <View><Text>S2 text</Text></View>;
const S3 = () => <View><Text>S3 text</Text></View>;

const S4 = () => <View><Text>S4 text</Text></View>;
const S5 = () => <View><Text>S5 text</Text></View>;
const S4n = StackNavigator({
  S4: {screen: S4, path: 's4'},
  S5: {screen: S5, path: 's5'}
});

class AppNav extends Component {
  constructor(props, context) {
    super(props, context);
    this.handleUrl = this.handleUrl.bind(this);
  }

  static router = StackRouter(
    {
      S1: {screen: S1, path: 's1'},
      S2: {screen: S2, path: 's2'},
      S3: {screen: S3, path: 's3'},
      S4n: {screen: S4n, path: 's4n'}
    }
  );

  handleUrl(url) {
    const
      { navigation } = this.props,
      { dispatch } = navigation,
      uriPrefix = Platform.OS == 'android' ? 'http://localhost/' : 'http://',
      params = {};
    let
      path = url.split(uriPrefix)[1];
    if(!path) {
      path = url;
    }

    const action = AppNav.router.getActionForPathAndParams(path, params);

    if(action) {
      dispatch(action);
    }
  }

  componentDidMount() {
    Linking.addEventListener('url', ({ url }: {url: string}) => {
      this.handleUrl(url);
    });

    Linking.getInitialURL().then(
      (url: string) => url && this.handleUrl(url)
    );
  }

  render() {
    const
      { navigation } = this.props,
      { state, dispatch } = navigation,
      { routes, index } = state,
      Component = AppNav.router.getComponentForState(state);
    let
      childNavigation = { dispatch, state: routes[index] };
    childNavigation = addNavigationHelpers(childNavigation);

    return (
      <Component navigation={childNavigation} />
    );
  }
}

@connect(state => ({nav: state.nav}))
class App extends Component {
  render() {
    const
      { dispatch, nav } = this.props;

    return (
      <AppNav
        navigation={addNavigationHelpers({dispatch: this.props.dispatch, state: this.props.nav})}
      />
    );
  }
}

const navReducer = (state, action) => (AppNav.router.getStateForAction(action, state) || state);
const rootReducer = combineReducers({nav: navReducer});

const RootApp = props =>
  <Provider store={createStore(rootReducer)}>
    <App />
  </Provider>;

export default RootApp;
```

**Comment by geeknam** [comment]
@atshakil I'm having the same issue of missing the header after implementing the top-level navigator. Have you found a solution for it?

**Comment by kristfal** [comment]
Just a FYI, getting deep linking to work with redux is pretty straightforward. When you've set up the initial deep linking support for iOS and Android, do the following:

In your root component that includes your store provider, subscribe to deep link URL events and grab the initial URL if your app is booting from a deep link:

```js
import React, {Component} from 'react';
import {Provider} from 'react-redux';
import {Linking} from 'react-native';

import store from '../../reducers';
import RootNavigation from '../../containers/nav/RootNavigation';
import LinkRoutes from '../../configs/LinkRoutes';

export default class App extends Component<{}> {
  componentDidMount() {
    Linking.addEventListener('url', event => this.handleOpenURL(event.url));
    Linking.getInitialURL().then(url => url && this.handleOpenURL(url));
  }

  componentWillUnmount() {
    Linking.removeEventListener('url', this.handleOpenURL);
  }

  handleOpenURL(url) {
    const path = url.split(':/')[1];
    LinkRoutes(path);
  }

  render() {
    return (
      <Provider store={store}>
        <RootNavigation />
      </Provider>
    );
  }
}

```

`LinkRoutes` is a simple function that uses `path-parser` to extract params and routes to build a navigateAction that can be dispatched like regular actions to your redux store.

```js
import Path from 'path-parser';
import {NavigationActions} from 'react-navigation';
import store from '../reducers';

const paths = [
  {
    routeName: 'YourScreenRoute',
    path: new Path('/base/path/:paramA/:paramB'),
  },
];

const findPath = url => paths.find(path => path.path.test(url));

export default url => {
  const pathObject = findPath(url);
  
  if (!pathObject) return;

  const navigateAction = NavigationActions.navigate({
    routeName: pathObject.routeName,
    params: pathObject.path.test(url),
  });

  store.dispatch(navigateAction);
};
```

This approach lets you nest navigators as you'd like, and handle deep linking completely separate from `react-navigation`.

**Comment by zibs** [comment]
@kristfal Thanks a ton - this worked perfectly out of the box for us.

**Comment by emaLorenzo** [comment]
@kristfal how did you get that store?
`import store from '../reducers';`

i cant dispatch the navigateAction :/

**Comment by henebb** [comment]
`Linking.getInitialURL()` always returns null as url. What could be wrong?

**Comment by alexmngn** [comment]
handleOpenURL could be even more simplified:

```
  handleOpenURL(url) {
    const path = url.split('://')[1];
    const action = RootNavigation.router.getActionForPathAndParams(path);
    this.props.dispatch(action);
  }
```

**Comment by mpyw** [comment]
@alexmngn This does not work for me. `routeName` gets undefined.

**Comment by brentvatne** [comment]
this should be resolved. if it is not working as expected still on the latest version, please create a new issue with a runnable example on https://snack.expo.io -- thanks!
