### ISSUE TITLE
Incorrect documentation for 'initialTab' / 'initialRouteName' property

### ISSUE THREAD

**Issue by nico1510** [react-community/react-navigation#119]
I just came across a problem with the `initialTab` property of the `TabNavigator`. The [documentation](https://github.com/react-community/react-navigation/blob/master/docs/api/navigators/TabNavigator.md#tab-navigator-options) says that the property `initialTab` should be used for displaying an initial route. 
However this did not have any effect, so I looked at the source and found that the property in the `TabRouter` component is called [initalRouteName](https://github.com/react-community/react-navigation/blob/0c9903556242f7d9b59df88180d395774b707701/src/routers/TabRouter.js#L36). Using this property name works fine for me.
So either the documentation or the `TabRouter` implementation should be corrected.

**Comment by satya164** [comment]
`initialRouteName` is the correct prop. Can you send a PR to fix the docs?

**Comment by nico1510** [comment]
sure https://github.com/react-community/react-navigation/pull/121
