### ISSUE TITLE
Please, can you add android transitioner like ios?

### ISSUE THREAD

**Issue by Lockie-cn** [react-community/react-navigation#1191]
I read the source code and found that ios can use two transition animations by set mode to 'card' or 'modal',but android can't.
```
if (Platform.OS === 'android') {
    // Use the default Android animation no matter if the screen is a modal.
    // Android doesn't have full-screen modals like iOS does, it has dialogs.
    if (prevTransitionProps && (transitionProps.index < prevTransitionProps.index)) {
      // Navigating back to the previous screen
      return FadeOutToBottomAndroid;
    }
    return FadeInFromBottomAndroid;
  } else {
    // iOS and other platforms
    if (isModal) {
      return ModalSlideFromBottomIOS;
    } else {
      return SlideFromRightIOS;
    }
  }
```
So, can you add android transition animations like ios by set mode to 'card' or 'modal',please?

**Comment by grabbou** [comment]
Default implementation is targeted at maximum platform user experience. This PR will make it possible to configure it: https://github.com/react-community/react-navigation/pull/1187
