### ISSUE TITLE
iOS: Modal stack -> Headerless stack -> Float stack

### ISSUE THREAD

**Issue by lprhodes** [react-community/react-navigation#1192]
Using modals and header-less views in iOS is pretty common so it seems crazy to have three nested navigation layers to accomodate them. Is there any work being done on this or any advisory on the direction you're looking to take it before I start work myself?

**Comment by grabbou** [comment]
There's some work in #53, would be great if you could look into that :)

**Comment by lprhodes** [comment]
@grabbou Can I suggest that you not ask people to work on something you're already working on...wasted a fair bit of time yesterday.

**Comment by grabbou** [comment]
@lprhodes sorry about that! I wasn't actually working on anything specific to #53, but the PR that I filled in made it possible to hide header in `headerMode: float`. Your comment suggests that you are working on something bigger (any kind of combination of modes) and fixes to animations? If yes, I'd suggest we open a new issue (or find an existing one) and keep working. My changes are just a first step :)

**Comment by nicoara** [comment]
complete solution:
app.js:
```
auth: {
  screen: StackNavigator({
    auth: { screen: AuthScreen },
    login: { screen: LoginScreen }
  })
},
```

auth: (shows no header)
```
class AuthScreen extends Component {
	static navigationOptions = {
		header: null
	}
```

login: (shows header)
class Login extends Component {...
