### ISSUE TITLE
(in)activeTintColor are ignored for TabNavigator

### ISSUE THREAD

**Issue by matthieucan** [react-community/react-navigation#1194]
This issue has been reported in #792, but the issue was not solved for me (neither was it for the original reporter according to their message).

At least on Android, `activeTintColor` and `inactiveTintColor` seem to be ignored in a `TabNavigator`. `style: {background-color: foo}` works well, however.

I'm using the master branch (c8062d014ce5002e9067a7764e99b483be6d1571).

**Comment by grabbou** [comment]
Can you post a code to reproduce the issue?

**Comment by matthieucan** [comment]
I narrowed it down to the type of label that is passed. A string is rendered correctly, while a component using the parameter tintColor will fail.
I also noticed it happens with 1.0.0-beta.8, but it wasn't the case in 1.0.0-beta.7.
Using a function and setting the color of the Text with tintColor doesn't have any effect.

```javascript
'use strict';
import React from 'react';
import {
  AppRegistry,
  View,
  Text,
} from 'react-native';
import { StackNavigator, TabNavigator } from 'react-navigation';

class Foo extends React.Component {
  static navigationOptions = ({ navigation }) => ({
    // works only in beta.7, not in beta.8
    tabBarLabel: (<Text>Foo</Text>),
  });

  render() {
    return (
        <View>
          <Text>lalala</Text>
        </View>
    );
  }
}

class Bar extends React.Component {
  static navigationOptions = ({ navigation }) => ({
    // works all the time
    tabBarLabel: 'Bar',
  });

  render() {
    return (
        <View>
          <Text>lololo</Text>
        </View>
    );
  }
}

const FooBar = TabNavigator({
  Foo: { screen: Foo },
  Bar: { screen: Bar },
}, {
  tabBarOptions: {
    activeTintColor: 'green',
    inactiveTintColor: 'yellow',
    style: {
      backgroundColor: 'lightgrey',
    },
  },
}
);

AppRegistry.registerComponent('reactnativefoo', () => FooBar);
```
1.0.0-beta.7
![screen-1 0 0-beta 7](https://cloud.githubusercontent.com/assets/2828729/25360463/7f27364a-2949-11e7-88bd-d2ca8a41a185.png)

1.0.0-beta.8
![screen-1 0 0-beta 8](https://cloud.githubusercontent.com/assets/2828729/25360482/96f34854-2949-11e7-965e-b196b3686b1b.png)

**Comment by satya164** [comment]
It is working as intended. When you specify a component, you take the full control over it, including styling. So it's upto you to specify the color. When you define `tabBarLabel`  as a function, you receive the `tintColor` as an argument, `tabBarLabel: ({ tintColor }) => ...`.

Not sure how it was working in previous release, but it was a bug.

**Comment by matthieucan** [comment]
I understand that with a component I'm responsible for styling it. But the tintColor parameter seems to always be empty. As I said in my previous message, this doesn't work either:
```javascript
tabBarLabel: ({ tintColor }) => (<Text style={{color: tintColor}}>Foo</Text>)
```
Am I missing something?

**Comment by matthieucan** [comment]
For those who are wondering, it seems to have been fixed, the same tabBarLabel as in my previous comment works fine with react-navigation@1.0.0-beta.9
