### ISSUE TITLE
Can not use Vectors font icon

### ISSUE THREAD

**Issue by nguyenminh797** [react-community/react-navigation#1196]
I can  not use this code to show Tab Bar Icon
react-native-vector-icons
```
tabBarIcon: () => (
      <Icon name='ios-home-outline' ios="ios-home-outline" android="md-home"/>
    )
```

**Comment by grabbou** [comment]
Can you please elaborate? What is the error you are getting?

**Comment by nguyenminh797** [comment]
@grabbou It do not show Icon in tab bar. (blank icon) I showing in React component normal.

**Comment by grabbou** [comment]
Please take a look here: https://github.com/react-community/react-navigation/blob/93976d358e27580e568ef016f820dc0253423aa7/examples/NavigationPlayground/js/SimpleTabs.js#L46-L49 at the included `demo` example. 

Try putting `size` and `style` to see if it helps.

**Comment by nolan-m** [comment]
That example does not work when I put it into my project with 1.0.0-beta.7.

**Comment by nolan-m** [comment]
@nguyenminh797   Are you on beta 7?  The website docs have been updated with new syntax, but there is not a released version using those docs.

I see you are using `tabBarIcon` which is for beta 8.

Try this way.
```
    navigationOptions: {
      tabBar: {
        label: 'TEST',
        icon: ({ tintColor }) => (
          <Icon
            name='home'
            fontSize='27'
          />
        )
      }
    }
```


See the old docs here.

https://github.com/react-community/react-navigation/commit/93976d358e27580e568ef016f820dc0253423aa7

**Comment by nguyenminh797** [comment]
Thank you guys.

I working in Beta 8.

**Comment by askarhu** [comment]
It's July 2017, and make sure to use "tabBarLabel" and "tabBarIcons" instead.
