### ISSUE TITLE
Cannot find module 'react-native/packager/blacklist' when running example

### ISSUE THREAD

**Issue by laoqiren** [react-community/react-navigation#1200]
I try to run the Redux example, I have run yarn install but the error: 'Cannot find module 'react-native/packager/blacklist'' comes out, I can find the file in node_modules, so what's the matter?

OS: Linux Ubuntu 16.04
RN version: 0.43.3

**Comment by radosch** [comment]
I have the same issue

**Comment by zoom2manoj** [comment]
I also have same issue.

**Comment by zoom2manoj** [comment]
There is a blacklist.js in react-native/packager.
Make a rn-cli.config.js in your project root and do something like this:
```

var blacklist = require('react-native/packager/blacklist');

var config = {
  getBlacklistRE(platform) {
    return blacklist(platform, [
      /node_modules\/my-package\/excluded-directory\/.*/
    ]);
  }
};

module.exports = config;
```

**Comment by grabbou** [comment]
The `rn-cli.config.js` is loaded from the root folder. Make sure to run `yarn` also in root folder, then `yarn` in `examples/NavigationPlayground`.

I cannot reproduce this issue on master (actively running playground)

**Comment by callagga** [comment]
I get the same issue (I downloaded the ZIP version, cd to the redux example, npm install, then react-native run-ios.  

Based on the above I've run: "npm install yarn" on "Downloads/react-navigation-master/examples/ReduxExample" and "Downloads/react-navigation-master", but this doesn't seem to help?? 

FYI: greg_work$ npm outdated
Package                  Current          Wanted  Latest  Location
react             16.0.0-alpha.6  16.0.0-alpha.6  15.5.4  ReduxExample
react-native              0.43.3          0.43.3  0.43.4  ReduxExample
react-navigation    1.0.0-beta.8             git     git  ReduxExample
Greg-Work-MBP:ReduxExample greg_work$

**Comment by callagga** [comment]
PS.  I did trying copying out the Redux example to another area and running however I hit a different issue - I raised it here http://stackoverflow.com/questions/43624452/cannot-find-entry-file-in-any-of-the-roots-issue-in-react-navigation-redux-exa   (not sure if it's a react-native newbie issue or nto)

**Comment by laoqiren** [comment]
just init a new project  by yourself and copy the code to the project and change the name of index.js to index.android.js, this could work @callagga

**Comment by scotbond** [comment]
How is this issue closed? examples should really work out of the box. no tweaking. no magic. this is bad experience for first time testers of this library. makes them run away.

> "Make sure to run yarn also in root folder"

Almost fixed it. but I'm still getting _"Unexpected token import"_ on packager.

**Comment by grabbou** [comment]
@scotbond try running npm start manually from root folder. I am not sure why the default packager that opens might be getting that error, but in my case it's how I fixed it.

**Comment by grabbou** [comment]
(if it's easily reproducible, it most likely deserves a new issue)

**Comment by scotbond** [comment]
Yes, that did the trick.

**Comment by akjesto** [comment]
How to solve this issue?Please mentioned step by steps

**Comment by fgaleano** [comment]
For anyone struggling to figure out the puzzle that is thread, here's what worked for me after cloning the repo:

`react-navigation/examples/ReduxExample$ npm install yarn`
`react-navigation/examples/ReduxExample$ node ./node_modules/yarn/bin/yarn.js`
`react-navigation$ npm install yarn`
`react-navigation$ node ./node_modules/yarn/bin/yarn.js`
`react-navigation$ npm start`
`react-navigation/examples/ReduxExample$ react-native run-ios`

(After running `yarn` on the root of the project, mine get's stuck 'waiting...' after 'fsevents'. I'm behind a proxy so it could be related to that. Regardless, I `Ctrl + C` out of that crap and moved on as if nothing happened.)

The iOS build will actually FAIL complaining the packager is already running. Ignore that and manually open the app on the Simulator. That app should work just fine.

A head scratcher, this one, but I'm moving one 'cos I have too much shit going no to try to figure this out. Hope it helps.

**Comment by akjesto** [comment]
@fgaleano its working fine.Thank you.

**Comment by ryancoughlin** [comment]
Running `yarn` in the project root fixed this for me.

**Comment by rcorrie** [comment]
I am getting this error when upgrading to rn `0.46.x` from `0.44.x`.

It seems that the `packager` directory was completely removed from the repo in the latest releases.

**Comment by nickcharles** [comment]
Also seeing this issue when upgrading from 0.45.x to 0.46.x, probably looking for the same solution as @rcorrie.

**Comment by scttmthsn** [comment]
Found a (temporary) fix, to wit

`const blacklist = require('metro-bundler/build/blacklist');

module.exports = {
	getBlacklistRE: function() {
		return blacklist([/scripts\/.*/]);
	},
};
`

**Comment by rcorrie** [comment]
@scttmthsn thanks for sharing, I was about to post that as well. Seems like they moved without letting us know ;)

**Comment by nickcharles** [comment]
@scttmthsn So far so good with that fix, thanks!

**Comment by mahesh2009** [comment]
worked for me too,thanks

**Comment by scttmthsn** [comment]
@rcorrie, @nickcharles & @mahesh2009 The file has moved post 0.47.0 to 

> metro-bundler/src

```javascript
const blacklist = require('metro-bundler/src/blacklist');

module.exports = {
  getBlacklistRE: function() {
    return blacklist([/scripts\/.*/]); // or what have you 
  },
};
```

**Comment by trietlam** [comment]
For RN 0.54.0 `const blacklist = require('metro/src/blacklist');`

**Comment by wayferer** [comment]
For RN 0.57.1 `const blacklist = require('metro-config/src/defaults/blacklist');`
