### ISSUE TITLE
Update TabNavigator documentation to replace tabBarLabel and tabBarTitle with tabBar object

### ISSUE THREAD

**Issue by svicalifornia** [react-community/react-navigation#1201]
The API has changed from what is currently described in the official docs. See #1101.

Code examples and options list should use the new `tabBar` object in `navigationOptions`.

**Comment by grabbou** [comment]
Actually the docs show the `new` version. The new API is currently in beta phase and can be installed by upgrading to `v8` version. We are working on versioning documentation, so that it's no longer confusing.
