### ISSUE TITLE
custom Navigation Actions

### ISSUE THREAD

**Issue by felixus95** [react-community/react-navigation#1202]
How do I declare and call custom Navigation Actions? The documentation isn't a big help, especially since dispatch was removed from the documentation as an action. 

I am using nested Navigators and I want to give my routes keys, so that the Screens are not rendered on top of each other. 

Custom Actions seem to be the only way to achieve this, but if I'm wrong I would happily accept a different solution 😃

**Comment by grabbou** [comment]
See https://reactnavigation.org/docs/routers/#Custom-Navigation-Actions

**Comment by felixus95** [comment]
As I said... the documentation is not much of a help. If I use the code as is in my project it will result in a exceeded call stack. The navigation action is not performed once. 

Maybe you can help me how to call the action properly, since the doc only says how to define it, if I understand it right.

@grabbou

**Comment by StefanWegener** [comment]
same issue here

**Comment by grabbou** [comment]
Oh, really! Sorry for the confusion and pre-mature close! We had an error in docs, here's a fix https://github.com/react-community/react-navigation/pull/1207

**Comment by felixus95** [comment]
Is working for me. Thanks!
