### ISSUE TITLE
headerBackTitle not working

### ISSUE THREAD

**Issue by svenadlung** [react-community/react-navigation#1204]
For me the screen navigation options `headerBackTitle` and `headerTruncatedBackTitle` are not working with  RN 0.43.1.

The related code: 

```
export default StackNavigator({
	Example: {
		screen: ExampleScreen,
		navigationOptions: ({navigation}) => ({
			headerBackTitle: 'Back',
			headerTruncatedBackTitle: 'Back',
```

Any ideas?

**Comment by grabbou** [comment]
`headerBackTitle` and `headerTruncatedBackTitle` are used to describe `back button` that points to this scene.

That means, you will see your changes taking place when you push something on top of `Example`. Back button will then display `Back`.

**Comment by svenadlung** [comment]
@grabbou of course it does. Sorry, my fault :/

**Comment by grabbou** [comment]
Do you think there's anything we could improve in docs to make it clearer?

**Comment by svenadlung** [comment]
Actually it should be clear but I was confused since all the other options are related to that particular scene.

**Comment by JulianKingman** [comment]
Like @grabbou I expected this to relate to the current scene.  I think the docs should at least say something about it applying to headers navigated to _from_ the current scene, not the scene itself.

**Comment by svenadlung** [comment]
I am with you, that would have saved me some time as well ;)
