### ISSUE TITLE
documentation for routing dynamic paths

### ISSUE THREAD

**Issue by dannycochran** [react-community/react-navigation#1210]
First off, thank you for taking on this effort to provide a reliable navigation system for RN that also plays well with Redux. This is probably not super appropriate as a Github issue but I think some documentation around this problem would be helpful.

I've been migrating to this lib coming from RN Experimental, and I'm having some trouble routing to dynamic paths within a nested navigator. Here is my setup:

- StackNavigatorApp
  - Screen1
  - Screen2
  - Screen3
     - StackNavigatorForScreen3

The StackNavigatorForScreen3 is where I'm having trouble. It seems like with the StackNavigator, each screen needs to be defined in the setup, e.g:

```javascript
const StackNavigatorForScreen3 = StackNavigator({
  someSceneName0: { screen: SomeReactComponent }
});
```

However, within that stack, I only ever want to render "SomeReactComponent", but the data for that component changes (there is a static set of data, such that there could be ~70 screens). Given that the data is static, I could do something like:

```javascript
const allScenes = {
  someSceneName0: { screen: SomeReactComponent },
  someSceneName1: { screen: SomeReactComponent },
  someSceneName2: { screen: SomeReactComponent },
  someSceneName3: { screen: SomeReactComponent },
  ... etc
};
const StackNavigatorForScreen3 = StackNavigator(allScenes);
```

This seems like it would have performance implications though. What is the correct way to create a StackNavigator that creates a route history but only ever updates the data for the same component (in this case, SomeReactComponent)?  I know that "setParams" is an option, but it seems like that will only ever update the same route, which would prevent me from going back / forth and having a proper route history.

I was previously able to do this with RN Experimental because it allowed for arbitrary keys / components to be passed in as a route.

**Comment by grabbou** [comment]
Wouldn't `this.props.navigation.navigate('someScene', { data: {} })` be enough? You would essentially keep pushing generic `someScene` screen that receives "data" that can be anything out of those ~70 you mentioned?

E.g.:
```js
const data = [...];

// once
this.props.navigation.navigate('someScene', { data: data[0] });

// then later
this.props.navigation.navigate('someScene', { data: data[71] });
```

**Comment by dannycochran** [comment]
Ah, okay, that definitely works, thank you. I think with RNExperimental that didn't work and I assumed the behavior would be the same.

**Comment by johngoren** [comment]
I do agree with dannycochran that this use case -- dynamically choosing the next destination -- should be documented...I searched for an answer for a long, long time and I think the documentation could use a "recipe book" of a few cases like this. Thanks for the helpful answer though.

**Comment by thewolff** [comment]
@johngoren did you end up going with the solution above?

**Comment by johngoren** [comment]
@thewolff I did. It worked well once I gave up on having it go to a dynamically-chosen card. It would be nice to be able to do it the other way though.

**Comment by derakhshanfar** [comment]
@grabbou thanks for response but why i can't Create 2 separate navigators like this? because handle it with params is hard.. 
i think if i can define something like this. it will be great!
```
const ADMIN_ROUTES = {
  home: { screen: HomeNavigator },
  listings: { screen: ListingsNavigator }, // admin only screen/tab
  account: { screen: AccountNavigator }
};

const REGULAR_ROUTES = {
  home: { screen: HomeNavigator },
  buildingList: { screen: buildingListNavigator }
};
```
this is my route component:
```
class RouteCompoenent extends Component {
    render() {
        if (this.props.isManager) {
            return <ManagerRoutes/>;
        }         
        return <ResidentRoutes/>;
    }
}
const mapStateToProps = (state) => {
    return {
        isManager: state
            .get('appState')
            .get('isManager')
    };
};

export default connect(mapStateToProps)(RouteCompoenent);
```
does above example has problem?

**Comment by AnthonyLamot** [comment]
I cam here looking for a slightly different use case to which I have not found a good answer yet. 

I also want "dynamic paths", but I also want them to show in my drawer. 

So yeah, doing something like @dannycochran said:

```
const allScenes = {
  someSceneName0: { screen: SomeReactComponent },
  someSceneName1: { screen: SomeReactComponent },
  someSceneName2: { screen: SomeReactComponent },
  someSceneName3: { screen: SomeReactComponent },
  ... etc
};
const StackNavigatorForScreen3 = StackNavigator(allScenes);
```

But then for a `DrawerNavigator`. 

The things I am trying to figure out is basically how can I pass data from my Redux store to the drawernavigator (because that is where my data is and where it is also getting updated)?

**Comment by anil1712** [comment]
@AnthonyLamot Did you get any solution for the same?

**Comment by AnthonyLamot** [comment]
@anil1712 no but you can upvote it here!: https://react-navigation.canny.io/feature-requests/p/dynamic-routes-for-navigators

I stopped working on a custom solution since I found it hard to evaluate if it was worth the effort given the rest of our roadmap, and instead hope it will become available in the future.
