### ISSUE TITLE
Getting "Failed to parse the href to a navigation state." error when options?.config is truthy, but options?.getStateFromPath is falsey

### ISSUE THREAD

**Issue by puja73** [react-community/react-navigation#12114]
### Current behavior

In our app, we have defined these following properties for `linking` where `config` is never `undefined` and `getStateFromPath` can be undefined.

```
    prefixes: ...
    config: DEEP_LINK_CONFIG, // explictly-defined-config
    getStateFromPath: customFuncToReturnStateFromPath(...), // a custom function that runs different validation and returns state or undefined based on validation. 
    subscribe(listener: CallableFunction) {
      ...
    },
```

My understanding was `getStateFromPath` will always override `config` if `getStateFromPath` is truthy. But if it is falsey, then `config` should be used instead.

As you can see [here](https://github.com/react-navigation/react-navigation/blob/main/packages/native/src/useLinkBuilder.tsx#L92-L94), the `else expression` likely will never be executed, if the `linking` has `getStateFromPath` property defined regardless of the value of `getStateFromPath()`.
```
 const state = options?.getStateFromPath
        ? options.getStateFromPath(href, options.config)
        : getStateFromPath(href, options?.config);
```

### Expected behavior

If `options.getStateFromPath` is defined and `options.getStateFromPath()` is falsey, then `options.config` should be used.

### Reproduction

https://snack.expo.dev/@psahahh/github.com-react-navigation-deep-linking-example

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.1.18|
| @react-navigation/bottom-tabs          | 6.6.1|
| @react-navigation/stack                | 6.4.1|
| node                                   | 20.9.0 |

**Comment by satya164** [comment]
If you override `getStateFromPath` then, you have full control over what it does, we can't assume what you mean when you return `undefined` - taking away that control. If you want to use the default behaviour then use the exported `getStateFromPath` instead of returning `undefined`.

**Comment by satya164** [comment]
> But if validation check fails then I'm returning undefined. Are you suggesting instead of returning undefined

So then what's the issue? If it's not a valid state you get an error appropriately. If you want to use default config instead of the error then yes, you should use `getStateFromPath`.
