### ISSUE TITLE
NavigationActions.navigate() returns null

### ISSUE THREAD

**Issue by laoqiren** [react-community/react-navigation#1222]
Yesterday I report this issue but the author closed it soon, the author just gave me a link to another issue but that didn't work. Could you please spend a little more time on my issue? thanks.

I edit the reducer example to change the StackNavigator to TabNavigator, the same error comes out, I think this may be a bug of TabNavigator using  with Redux.
my reducer:
```
import * as types from '../constants/actionTypes';
import {NavigationActions} from 'react-navigation';
import {AppNavigator} from '../containers/App';

const initialNavState = {
    index: 1,
    routes: [
        {key: 'InitB',routeName: 'Completed'},
        {key: 'InitA',routeName: 'Home'}
    ]
}

export default function(state=initialNavState,action){
    
    switch(action.type) {
        case 'Login':
            return AppNavigator.router.getStateForAction(NavigationActions.back(),state);
        case 'Logout':
            return AppNavigator.router.getStateForAction(NavigationActions.navigate({routeName: 'Completed'}),state)
        default:
            return AppNavigator.router.getStateForAction(action,state);
    }
}
```

my AppNavigation:
```
import CompletedView from './CompletedView';
import HomeView from './HomeView';
import EditView from './EditView';

const AppRouteConfigs = {
    Home: {
        screen: HomeView
    },
    Completed: {
        screen: CompletedView
    }
}
export const AppNavigator = TabNavigator(AppRouteConfigs,{
    tabBarPosition: 'bottom',
    tabBarOptions: {
        showIcon: true
    }
});

@connect(state=>({
    nav: state.nav
}))
class App extends Component {
    componentDidMount(){
        SplashScreen.hide();
    }
    render(){
        return (
            <AppNavigator navigation={addNavigationHelpers({
                dispatch: this.props.dispatch,
                state: this.props.nav
            })}/>
        )
    }
}
export default App; 
```
In HomeView I want to navigate to Completed View by dispathing an action:
```
handleClick = ()=>{
        //alert('hei')
        this.props.navigation.dispatch(NavigationActions.navigate({routeName:'Completed'}))
    }
    render(){
        return (
            <View>
                <Text>Hey,I'm home pageaaa</Text>
                <Button onPress={this.handleClick} title="go to completed"/>
                <Icon name="rocket" size={30} color="#900" />
            </View>
        )
    }
```

but the error comes:
`null is not an object (evaluating 'navigation.state.routes')`
I found the `NavigationActions.navigate({routeName:'Completed'})` returns null.

I wish you can see my issue for detail. Thanks.

**Comment by grabbou** [comment]
> Yesterday I report this issue but the author closed it soon, the author just gave me a link to another issue but that didn't work.

Hey, it didn't work because the original issue is open. We are working on a fix, but having multiple issues (duplicates) over the repository doesn't really help.

**Comment by grabbou** [comment]
Also, please see this issue: https://github.com/react-community/react-navigation/issues/485#issuecomment-297012003 and the comment I've linked. 

Redux setup is not easy and often, not even needed. You should consider not using it if the only use-case is that you already have Redux set up.
