### ISSUE TITLE
Pass screen reference to another screen (question)

### ISSUE THREAD

**Issue by DanDance** [react-community/react-navigation#1223]
Let's say we have Stack Navigator
```
const routesStack = {
  Screen1: {
    screen: Screen1
  },
  Screen2: {
    screen: Screen2
  }
};

const navigatorConfig = {
  ...
};

export default StackNavigator(routesStack, navigatorConfig);
```
and we have state like this
```
{
  index: 1,
  routes: [{...screen1}, {...screen2}]
} 
```
So if we have Screen2 we can guarantee that we have Screen1 is already rendered.
Im going to use Screen1 method in Screen2 via reference. How can I do this? Could it be implemented with custom navigator?
Thanks.

**Comment by grabbou** [comment]
There's no way to cross-reference scenes. If you need to re-use a method, I believe it's better to place:
1) Put a method on the outer most component that renders your navigator
2) Pass that method via `screenProps` -> https://reactnavigation.org/docs/navigators/stack#Navigator-Props

**Comment by DanDance** [comment]
Thank you for response. The problem is that I can not put this method out. It passes data to Screen1's WebView via `postMessage`. So consider to user EventEmitter to pass data between two screens.

Anyway, thanks.
