### ISSUE TITLE
Hide TabBar from within StackNavigator

### ISSUE THREAD

**Issue by starchand** [react-community/react-navigation#1224]
I have a project using navigation based on the following example: https://github.com/parkerdan/SampleNavigation

I am struggling to hide the tab bar from within a pushed view on a StackNavigator.
I've tried variations of the below but is unsuccessful. 

```
static navigationOptions = 
    ({ navigation, acc }) => ({
      tabBarKey: navigation.state,
      tabBarLabel: 'Dashboard',
      tabBarIcon: ({ tintColor, focused }) => (
         <Image
          source={require('../../tabBar/images/Pagoda.png')}
          style={[styles.icon, {tintColor: tintColor}]} />
      ),
      tabBarVisible: (acc && acc.visible !== 'undefined') ? acc.visible : true,
   });
```

Any ideas would be appreciated?

**Comment by grabbou** [comment]
What is `acc` btw?

Anyways, please report a full component (follow issue template). Thank you.

**Comment by starchand** [comment]
Acc has just come from: https://github.com/react-community/react-navigation/issues/464

My full component doesn't have any visibility logic: 

```
class LeaderboardNavigation extends React.Component {
  static navigationOptions = 
    ({ navigation }) => ({
      tabBarKey: navigation.state,
      tabBarLabel: 'Leaderboard',
      tabBarIcon: ({ tintColor, focused }) => (
        <Image
          source={require('../../tabBar/images/Leaderboard.png')}
          style={[styles.icon, {tintColor: tintColor}]} />
      ),
    });
  

render(){
    const { dispatch, navigationState} = this.props
    return (
          <NavigatorLeaderboard
            navigation={
              addNavigationHelpers({
                dispatch: dispatch,
                state: navigationState
              })
            }
          />
        )
      }
  }

```

**Comment by grabbou** [comment]
Oh, yeah. It was the old API (`v7`). The new one doesn't have it (and looks like you are using it), so there's no `acc` property.

I would still need a full code including `Tab` navigator to see where's the issue coming from.

**Comment by starchand** [comment]
I'm basically using an identical structure to: https://github.com/parkerdan/SampleNavigation

Tab bar navigator: https://github.com/parkerdan/SampleNavigation/blob/master/app/tabBar/views/TabBarNavigation.js

This repo is a couple months old, is it no longer best practice?

**Comment by grabbou** [comment]
I would suggest you to try `NavigationPlayground`. The author of the repo didn't update it for 3 months and pointed it to `master`. That means the code that used to work 3 months ago no longer works (pointing to master instead of npm version).

In order to fix that, I'd have to see a full code (not `almost like`). Can you publish it to Github or send over a `zip`?

I would generally close that issue, but don't want to discourage you.

**Comment by randytorres** [comment]
Hey I think i'm having the same issue. Here is my code https://gist.github.com/randytorres/56df0b7367cb1b08272a83b1894debd2

**Comment by starchand** [comment]
@grabbou Will send you email with link to zip to your GitHub profile address - as just spent another hour trying to fix this with no success :(

**Comment by randytorres** [comment]
I fixed my issue by upgrading react-navigation.

**Comment by grabbou** [comment]
Closing this issue as I've answered @starchand via email.

**Comment by ugiacoman** [comment]
@randytorres Would you mind sharing how you managed this, maybe in a gist please?

**Comment by Ronnyrr** [comment]
Why wouldn't you share this? Really looking for a solution, but all I can find doesn't work.

**Comment by brentvatne** [comment]
https://reactnavigation.org/docs/en/navigation-options-resolution.html#a-tab-navigator-contains-a-stack-and-you-want-to-hide-the-tab-bar-on-specific-screens
