### ISSUE TITLE
React Navigation is not working on TouchableOpacity

### ISSUE THREAD

**Issue by ajaysaini-sgvu** [react-community/react-navigation#1225]
I tried react navigation on `Button` which is working fine. I want to customize `Button` so this made me to go for `TouchableOpacity`. I am trying to setup react native navigation like below which is not working now with `TouchableOpacity`.

	/**
	 * https://github.com/facebook/react-native
	 * @flow
	 */

	import React, { Component } from "react";
	import {
	  AppRegistry,
	  Image,
	  View,
	  Text,
	  Button,
	  StyleSheet,
	  TouchableOpacity
	} from "react-native";
	import { StackNavigator } from "react-navigation";
	import EnableNotificationScreen from "./EnableNotificationScreen";
	import styles from "./Styles";
	import * as strings from "./Strings";

	class SplashScreen extends Component {
	  render() {
		console.disableYellowBox = true;
		const { navigate } = this.props.navigation;
		return (
		  <View style={styles.container}>
			<Image source={require("./img/talk_people.png")} />
			<Text style={styles.textStyle}> {strings.talk_people} </Text>

			<TouchableOpacity>
			  <View
				style={{
				  backgroundColor: "#FE434C",
				  alignItems: "center",
				  justifyContent: "center",
				  borderRadius: 10,
				  width: 240,
				  marginTop: 30,
				  height: 40
				}}
				onPress={() => {
				  navigate("EnableNotifcation");
				}}
			  >
				<Text style={{ color: "white" }}>CONTINUE</Text>
			  </View>
			</TouchableOpacity>
		  </View>
		);
	  }
	}

	const ScheduledApp = StackNavigator(
	  {
		Splash: {
		  screen: SplashScreen,
		  navigationOptions: {
			header: {
			  visible: false
			}
		  }
		},
		EnableNotification: {
		  screen: EnableNotificationScreen,
		  navigationOptions: {
			header: {
			  visible: false
			}
		  }
		}
	  },
	  {
		initialRouteName: "Splash"
	  }
	);

	AppRegistry.registerComponent("Scheduled", () => ScheduledApp);

**Comment by grabbou** [comment]
`onPress` should be set on `TouchableOpacity`, not `View`.

**Comment by ajaysaini-sgvu** [comment]
I have tried however it is still not working. 

	<TouchableOpacity onPress={() => {
	  navigate("EnableNotifcation");
	}}>
	  <View
		style={{
		  backgroundColor: "#FE434C",
		  alignItems: "center",
		  justifyContent: "center",
		  borderRadius: 10,
		  width: 240,
		  marginTop: 30,
		  height: 40
		}}
	  >
		<Text style={{ color: "white" }}>CONTINUE</Text>
	  </View>
	</TouchableOpacity>

**Comment by grabbou** [comment]
I didn't can you verify that `onPress` is called at all (put console.log) and that the route exists?

**Comment by ajaysaini-sgvu** [comment]
Trust me, Simply change it to `Button` and it is working fine. This seems bug in this library

**Comment by jesshunter** [comment]
Try taking out the extra set of {} in onPress. It should look like: onPress= { () => navigate("EnableNotification")} You don't need the extra set of {} around the navigate fcn

**Comment by ajaysaini-sgvu** [comment]
I tried that also, too much attempts on same problem. It is not working :(

**Comment by jesshunter** [comment]
What is your debugger saying? Is 'navigate' being logged in the console when you press the 'continue' text?

**Comment by ajaysaini-sgvu** [comment]
Have a look this https://www.dropbox.com/s/5msljl727wa7241/db.png?dl=0

**Comment by bulby97** [comment]
@ajaysaini-sgvu Same thing here 👍 

```
import React, { Component, PropTypes } from 'react'
import {
  TouchableOpacity,
} from 'react-native'
import { withNavigation } from 'react-navigation'

class Link extends Component {
  static propTypes = {
    navigation: PropTypes.object.isRequired,
    params: PropTypes.object,
    route: PropTypes.string.isRequired,
  }

  constructor(props) {
    super(props)

    this.handlePress = ::this.handlePress
  }

  handlePress() {
    const { navigation, route, params } = this.props
    console.log(route, params)
    navigation.navigate(route, params)
  }

  render() {
    return (
      <TouchableOpacity {...this.props} onPress={this.handlePress} />
    )
  }
}

export default withNavigation(Link)
```


Doesn't work. Console.log is ok, but the navigation action doesn't trigger.

**Comment by koenpunt** [comment]
You have a typo in your call to `navigate`;
```
navigate("EnableNotifcation");
```

should be 
```
navigate("EnableNotification");
```

**Comment by ajaysaini-sgvu** [comment]
@koenpunt Ahh Seriously it worked! Thanks. This typo wasted my a lot of time..

**Comment by satya164** [comment]
We should throw error for invalid types. cc @grabbou

**Comment by grabbou** [comment]
Yeah, someone wants to send a PR?

**Comment by ajaysaini-sgvu** [comment]
@grabbou What do you mean by PR ?

**Comment by whimsicaldreamer** [comment]
@ajaysaini-sgvu PR means Pull Request.

**Comment by maitrungduc1410** [comment]
For those who's having this issue. It seems like on Android the TouchableOpacity doesn't have a "real" `height` (I mean it actual height is 0, even when we can see it) so when we click, nothing happens. So we need to make a `height` property. For example:
```
    headerRight: (
        <TouchableOpacity onPress = {() => alert('This is a button!')}>
            <View style={{ alignItems: "center", justifyContent: "center", height: 40 }}>
              <Icon
                name="ios-search"
                color="white"
                size={28}
              />
            </View>
        </TouchableOpacity>
      )
```

It works like a charm for me.

**Comment by shyamalVixplor** [comment]
> For those who's having this issue. It seems like on Android the TouchableOpacity doesn't have a "real" `height` (I mean it actual height is 0, even when we can see it) so when we click, nothing happens. So we need to make a `height` property. For example:
> 
> ```
>     headerRight: (
>         <TouchableOpacity onPress = {() => alert('This is a button!')}>
>             <View style={{ alignItems: "center", justifyContent: "center", height: 40 }}>
>               <Icon
>                 name="ios-search"
>                 color="white"
>                 size={28}
>               />
>             </View>
>         </TouchableOpacity>
>       )
> ```
> 
> It works like a charm for me.

Works for me..thank u

**Comment by pankajgulabsharma** [comment]
> For those who's having this issue. It seems like on Android the TouchableOpacity doesn't have a "real" `height` (I mean it actual height is 0, even when we can see it) so when we click, nothing happens. So we need to make a `height` property. For example:
> 
> ```
>     headerRight: (
>         <TouchableOpacity onPress = {() => alert('This is a button!')}>
>             <View style={{ alignItems: "center", justifyContent: "center", height: 40 }}>
>               <Icon
>                 name="ios-search"
>                 color="white"
>                 size={28}
>               />
>             </View>
>         </TouchableOpacity>
>       )
> ```
> 
> It works like a charm for me.


not working for me
