### ISSUE TITLE
How to add a default layout to the app. For example, common StatusBar and bg color?

### ISSUE THREAD

**Issue by THPubs** [react-community/react-navigation#1226]
I want to add a common layout for all my screens. For example, the same StatusBar style and the same bg color. Since I can't put the `StackNavigator` inside a view, we need to find a different way to do it. Any help?

**Comment by grabbou** [comment]
See https://reactnavigation.org/docs/navigators/navigation-options#Default-Navigation-Options, you can do:
```
const MyTabNavigator = StackNavigator({
  ...
}, {
  navigationOptions: {
      // default opts here
  },
});
```

**Comment by THPubs** [comment]
@grabbou But it can only change some navigation options, right? Can't give a layout and change status bar I think.

**Comment by grabbou** [comment]
Yes, layout and statusBar are not controlled by navigation yet and have to be styled on your own (see #11)

**Comment by THPubs** [comment]
Yes but in the current setup, we have to do it for all screens one by one. Can't add a common layout.

**Comment by filiphosko** [comment]
@THPubs To have one common config for StatusBar for the whole app without needing to declare it on every page, you can put it in a top level (container) component next to your nav stack. For example like this:

```jsx
<View style={{ flex: 1 }}>
  <StatusBar barStyle="light-content" />
  <StackNavigator />
</View>
```

**Comment by THPubs** [comment]
@filiphosko The issue is, the navigator won't work if placed inside a `View` 😢

**Comment by filiphosko** [comment]
@THPubs I tested it myself with nested navigators (Stack in a Drawer) and it works, I actually use it in an app. Do you have style={{ flex: 1 }} on the containing View?

**Comment by astriskit** [comment]
It turns out that StackNavigator works inside View, if the flex is defined in that View. as @THPubs indicated. Thumbs up for that!
