### ISSUE TITLE
Open Drawer from Tab bar

### ISSUE THREAD

**Issue by augustoabreu** [react-community/react-navigation#1227]
### Expected Behavior
Hi. I'm developing a app with a bottom tab bar like this:

![artboard](https://cloud.githubusercontent.com/assets/3988554/25397625/3d20eba8-29bf-11e7-8f6e-99a755388627.png)

The first 4 buttons are static views and the last one has a different behaviour: when users taps the last button i need to open a drawer. Is this possible with react-navigation?

**Comment by grabbou** [comment]
Closing in favour of #954

**Comment by subhendukundu** [comment]
Same issue, any solution?

**Comment by subhendukundu** [comment]
Ahh, fixed it.
Incase someone looking for an example,
You need to add the createDrawerNavigator inside the createBottomTabNavigator. I was doing it the otherway.
For example,
```
    const ProfileNavigator = createDrawerNavigator({
      Drawer: DashboardTabNav
    }, {
      initialRouteName: 'Drawer',
      contentComponent: ExampleScreen,
      drawerWidth: 300
    
    });
    
    // Manifest of possible screens
    const PrimaryNav = createStackNavigator({
      DashboardScreen: { screen: ProfileNavigator },
      LoginScreen: { screen: LoginScreen },
      LaunchScreen: { screen: LaunchScreen },
      UpdateUserScreen: { screen: UpdateUserScreen }
    }, {
      // Default config for all screens
      headerMode: 'none',
      initialRouteName: 'LoginScreen',
      navigationOptions: {
        headerStyle: styles.header
      }
    });
    export default createAppContainer(PrimaryNav);
```

**Comment by rjsajnani** [comment]
I know my reply is tooo late sorry for that i was also experimenting with the same UI as mentioned by  
@augustoabreu 
I have created a small expo with the help of issue #5422 
https://github.com/react-navigation/react-navigation/issues/5422#issuecomment-450253726
just gave some customization and done hope this helps anyone who will need it later 

https://snack.expo.io/@rjsajnani/b3Blbi

**Comment by Manil-SoftNEP** [comment]
This [answer](https://stackoverflow.com/a/64866152/19476877) helped me.
Just use the `listeners` prop to `preventDefault` behaviour and then open the drawer.
```
<Tabs.Screen 
  name={"More"} 
  listeners={({ navigation }) => ({
    tabPress: e => {
      e.preventDefault();
      navigation.openDrawer();
    }
  })}
  component={Home} 
/>
```
