### ISSUE TITLE
Error on combining redux with DrawerNavigator

### ISSUE THREAD

**Issue by RWOverdijk** [react-community/react-navigation#1228]
Following the docs, I've set up a very simple, two page StackNavigator with redux. Once that worked, I changed StackNavigator() to DrawerNavigator and I get:

 ![screenshot 2017-04-25 20 01 57](https://cloud.githubusercontent.com/assets/781745/25400199/1c77f292-29f2-11e7-8a1d-dc55ec82b4f6.png)

This occurs in src/withCachedChildNavigation.js

**Comment by grabbou** [comment]
See #857

**Comment by RWOverdijk** [comment]
@grabbou that wasn't the issue for me. My props get passed on properly.

**Comment by guoliang1206** [comment]
@grabbou  
undefined is not an object (evaluating '_AppNavigator2.default.router.getStateForAction')
detail in #857

**Comment by RWOverdijk** [comment]
The issue for me was the documentation. I defined my own state, but should've been using:

```js
const initialState = AppNavigator.router.getStateForAction(AppNavigator.router.getActionForPathAndParams('Login'));
```

from https://reactnavigation.org/docs/guides/redux

**Comment by swellingt0n** [comment]
@RWOverdijk @grabbou I am using that same approach but I still get the original error. `nextState` has routes defined, but `navigation` in withCachedChildNavigation.js has `state` undefined.

reducer:
```
const { getActionForPathAndParams, getStateForAction } = BaseNavigation.router;

{ ... }

nextState = getStateForAction(getActionForPathAndParams('HomeScreen'))
```

StackNavigator
```
const BaseNavigation = StackNavigator({
  Login: { screen: Login },
  HomeScreen: { screen: HomeNavigator }
},{ ... }
```

HomeNavigator
```
const DrawerScreen = DrawerNavigator({
  Home: {
    screen: HomeView
  }
})

{...}

function mapStateToProps(state, ownprops) {
  return {
    nav: state.navigationState
  };
}

{...}

class HomeNavigator extends React.Component {
  render() {
    return (<DrawerScreen navigation={addNavigationHelpers({
        dispatch: this.props.dispatch,
        state: this.props.nav,
      })} />
    )
  }
}
export default connect(mapStateToProps)(HomeNavigator);
```

**Comment by jfklg** [comment]
I have the same issue,how to solve it ? THANKS

**Comment by jfklg** [comment]
@RWOverdijk  do you have solve this problem?
