### ISSUE TITLE
React navigation 7 -> chain navigation - the first nav is ignored

### ISSUE THREAD

**Issue by GaelCO** [react-community/react-navigation#12296]
### Current behavior

In react navigation navigation 7, if 2 navigations was chained, the first one is ignored.
For example : I navigate to goBack (or closeDrawer) -  to close the current screen and navigate to a new screen.
The initial screen was not closed.It's work in react navigation 6.

To workaround this, I wrap the second navigation in a setTimeout. It's not ideal, because it's not elegant and we see a graphic glitch.
There may be an elegant way to do what I want in react-navigation 7, but I don't know it

 
In the repro example : (Web, because I don't pass time to manage correctly the SafeArea
-> start in screen A
-> tap button "Open B" => navigate to B screen
-> tap button  "Open C" => this button chain goBack and navigate to C screen
-> tap button "return -> normally return to A" => this button goBack.
I expect to return to A screen, but I gio back on B screen.

### Expected behavior

When I chain navigations, all navigations are executed

### Reproduction

https://snack.expo.dev/@gco/testdoublenav

### Platform

- [x] Android
- [x] iOS
- [x] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [x] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [x] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 7.0.4
| @react-navigation/stack                | 7.0.7
| react-native-safe-area-context         | 4.14.0
| react-native-screens                   | 4.3.0
| react-native-gesture-handler           | 2.21.2
| react-native                           | 0.76.3
| expo                                   | 52.0.11
| node                                   | 22.11.0
| yarn                            | 4.5.2

**Comment by satya164** [comment]
@GaelCO the bot asks for drawer version since you selected it in the issue.

anyway, please try with the latest version of `@react-navigation/native` (`7.0.6`). it should be fixed.

**Comment by GaelCO** [comment]
I confirm. I update all my navigation dependencies and this issue is fixed.
