### ISSUE TITLE
How to use screenProps on a nested navigator?

### ISSUE THREAD

**Issue by joncursi** [react-community/react-navigation#1232]
The implementation of `screenProps` [as described in the documentation](https://reactnavigation.org/docs/navigators/tab#Navigator-Props) makes sense when you have a single navigator, or if you want to apply `screenProps` to the root navigator. But what if you want to apply `screenProps` on a nested navigator? Consider the following setup:

```jsx
const MainNavigator = StackNavigator({
  ...
  Tabs: { screen: Tabs },
  ...
});

const Tabs = TabNavigator({ // want to apply special screenProps on these nested tabs
  ...
  SomeScreen: { screen: SomeScreen },
  ...
});
```

Only `MainNavigator` gets exposed in JSX as a ReactComponent since it's the main entry point:

```jsx
const App = ({ dispatch, navigationState }) => (
    <MainNavigator
      navigation={addNavigationHelpers({
        dispatch: props.dispatch,
        state: props.navigationState,
      })}
      screenProps={/* root screenProps would go here */}
    />
);
```

`Tabs` never gets exposed as a ReactComponent in JSX since it's essentially handled by `MainNavigator`. So... how do you assign `screenProps` to it?

**Comment by grabbou** [comment]
> But what if you want to apply screenProps on a nested navigator?

Root `screenProps` will get propagated to all the components within that nested navigator. You will have access to main `screenProps` inside each of the component (just tested).

> Tabs never gets exposed as a ReactComponent in JSX since it's essentially handled by MainNavigator

Yes, but you can always define a custom React component (screen) that renders that `TabNavigator` and issue would be gone.

Tip: You can just pass `this.props.navigation` instead of `addNavigationState({...})`

**Comment by cgadea** [comment]
@grabbou I had a similar issue and did what you suggested at the end there.
> you can always define a custom React component (screen) that renders that TabNavigator
I can use this structure to pass screenProps but it brakes deep linking to anything nested under that custom component.

```
const MyTabNavigator = TabNavigator({
  ...
  Profile: {
    screen: ProfileContainer,
    path: 'profile',
  },
});
...

ProfileNavigator = StackNavigator({
  ...
  Foo: {
    screen: Bar,
    path: 'foo',
  },
});

class ProfileContainer extends Component {
  render() {
    return <ProfileNavigator />;
  }
}
```

`myapp://profile` takes me to the Profile screen, but `myapp://profile/foo` does not take me to the Foo screen, just stops at the Profile screen. Any suggestions on an alternative approach to passing screenProps or how to restore deep linking functionality?

**Comment by mattfysh** [comment]
Any update to this issue? I have a nested navigator I want to reuse with a true flag on one, and a false flag on the other.

**Comment by GollyJer** [comment]
@mattfysh I pass screenProps into my root navigator and am able to access them via the `screenProps.` prop from all of my nested navigators.  This is with `v1.0.0-beta.13`.

**Comment by gregblass** [comment]
@GollyJer This worked for me as well!
