### ISSUE TITLE
this.props.navigation.state.params is undefined

### ISSUE THREAD

**Issue by jasan-s** [react-community/react-navigation#1237]
The state object on navigation does not contain any params key, just `{key: 'ddd', routeName: 'ddd'`.

I'm calling navigate like so: 
`onPress={ () => this.props.navigation.navigate('ddd', {hello: 'jasan'}) }`

**Comment by grabbou** [comment]
The `params` object is null when there are no params. Depending on your configuration, you might be running into one of these #143 #80 ?

**Comment by lucfranken** [comment]
@grabbou is that by design or just as is? Reason why asking:

It makes it harder to detect whether a param is set. 

Instead of a simple if statement something like this is needed:

```js
  _getId() {
    let id = false;
    if(this.props.navigation.state.params) {
      id = this.props.navigation.state.params.id;
    }
    return id;
  }
```

**Comment by grabbou** [comment]
It is by design, but I think there was an issue that proposed making it always defined.

**Comment by mativs** [comment]
@lucfranken I have this method in all my components 

```
  getNavigationParams() {
    return this.props.navigation.state.params || {}
  }

**Comment by flyher** [comment]
@grabbou 
The https://github.com/react-community/react-navigation/issues/143 helped me, thank you!

**Comment by ToJen** [comment]
@flyher what did you have in the end?

**Comment by aniketnear** [comment]
Refer this: [react-navigation](https://reactnavigation.org/docs/params.html#docsNav)

**Comment by flyher** [comment]
@ToJen 
I have forget this issue, maybe the flowing links  can help you:

[143#issuecomment-276819944](https://github.com/react-navigation/react-navigation/issues/143#issuecomment-276819944)

[143#issuecomment-277696375](https://github.com/react-navigation/react-navigation/issues/143#issuecomment-277696375)

**Comment by edem** [comment]
It seems impassible to transfer parameters between StackNavigators, the state.params is always 'undefined', even use NavigationActions.

**Comment by lfkwtz** [comment]
`this.props.navigation.getParam()` now exists as a helper method

https://reactnavigation.org/docs/en/navigation-prop.html#getparam-get-a-specific-param-value-with-a-fallback

**Comment by phattruong-agilityio** [comment]
You can try this
```
const { navigation } = this.props;
const id = navigation.getParam('id') || '';
```

**Comment by sciphergfx** [comment]
const { navigation } = this.props;
const id = navigation.getParam('id', '')

Instantiates with an empty value

**Comment by SirPhemmiey** [comment]
@sciphergfx, Yeah. But I think it's better with `const id = navigation.getParam('id', '')`

**Comment by ldslvbrn** [comment]
I might be comming late to the party but props have to be passed as a parameter to the construtor or the navigation will be null. Example below:

constructor(props) {
        super(props);
        const { navigation}  = this.props;
        const userMap = navigation.getParam('userData', null);
        this.state = {
            // . . .
        }
    }

**Comment by GIRIRAJNAGAR768** [comment]
use 
const any = this.props.route.params.param_key_name

**Comment by Mehebbet13** [comment]
sometimes it is because U use separate stack for each screen, so beetween them params cant pass in that way, try just one main stack for all screens

**Comment by GIRIRAJNAGAR768** [comment]
see this....
https://reactnavigation.org/docs/nesting-navigators

this.props.navigation.navigate("**stack_Name**", {
 screen:"home_screen_name_of_stack",
 params:{
 user:"anything_string_or_object"
}
})

**Comment by ronikstha** [comment]
I am having the save problem. Trying pass data between two screens in a same Drawer navigation. 
But, i am getting the same error. 
onPress={() => this.props.navigation.navigate('Detail', { image: item.image,
            price: item.price,
            name: item.name})}

<Image 
              source={this.props.navigation.state.params.image} 
              style={styles.image}
 />

**Comment by AkshayMhatre** [comment]
what a pain this react-navigation is

**Comment by raajnadar** [comment]
@AkshayMhatre you don't read docs and then you say it is pain! WOW
