### ISSUE TITLE
ListView only shows content after scroll

### ISSUE THREAD

**Issue by jasan-s** [react-community/react-navigation#1238]
I have nested routes: 
```
StackNavigator
   TabNavigator
        tabA
           StackNavigator
               View1
               View2
        tabB
          View3
```

However, when I navigate to View2(ListView) from View1. I have to scroll up or down to have the component render to the screen, or else its completely blank.  I'm fairly new to react native, but is this a LIstView issue or related to this lib?

**Comment by jasan-s** [comment]
not sure if its a good solution but solved it using:

`removeClippedSubviews={false}` in Listview Component

**Comment by jakallergis** [comment]
Had the same issue - worked like a charm

**Comment by cooperka** [comment]
Sounds like this is a known React Native bug, dupe of https://github.com/react-community/react-navigation/issues/368. Thanks for posting the workaround!
