### ISSUE TITLE
How to find screen user is currently on

### ISSUE THREAD

**Issue by abhitheawesomecoder** [react-community/react-navigation#1239]
How to find screen user is currently on

**Comment by TheTekton** [comment]
Try getCurrentRouteName(): https://github.com/react-community/react-navigation/issues/949#issuecomment-292812298 / https://reactnavigation.org/docs/guides/screen-tracking

**Comment by abhitheawesomecoder** [comment]
this code only logs current screen when app loads but not when there is screen transition

`/ gets the current screen from navigation state
function getCurrentRouteName(navigationState) {
  if (!navigationState) {
    return null;
  }
  const route = navigationState.routes[navigationState.index];
  // dive into nested navigators
  if (route.routes) {
    return getCurrentRouteName(route);
  }
  return route.routeName;
}

const RouteConfigs = {
    Login: {screen:Login},
    Home: {screen:Home},
    Chat: {screen:Chat},
}

const StackNavigatorConfig = {
    headerMode: 'none',
}

const AppNavigator = StackNavigator(RouteConfigs, StackNavigatorConfig)


export default () => (
  <AppNavigator
    onNavigationStateChange={(prevState, currentState) => {
      console.log("Change");
      const currentScreen = getCurrentRouteName(currentState);
      const prevScreen = getCurrentRouteName(prevState);

      if (prevScreen !== currentScreen) {
        // to track screen change
        console.log(currentScreen);
      }
    }}
  />
);
`
