### ISSUE TITLE
How to retain the state of screen1 while using stack Navigator

### ISSUE THREAD

**Issue by ashrithks** [react-community/react-navigation#1240]
How to retain the state of screen1 , when user navigates to screen2.i.e.,,
Example: in Screen1 some states are maintained (Like text input field ,where user has entered some text)
when user navigates to screen2 and press back button, I should retain the state in Screen1(Text input with user entered text),Please help!!!!!
@grabbou 

| react-navigation |  ^1.0.0-beta.6
| react-native     |  0.42.0

**Comment by grabbou** [comment]
That shouldn't happen, can you please post a full code of your app?

**Comment by ashrithks** [comment]
@grabbou  ,, That is not happening,
But i need in that way, how to acheive.??????

**Comment by grabbou** [comment]
We need a way to reproduce it. The template issue asks explicitly for a code example to reproduce.

**Comment by ashrithks** [comment]
@grabbou  ,i found a way to go back,,
goBack - Close the active screen and move back in docs
but How pass params when using goBack() function

**Comment by ashrithks** [comment]
Got the solutions ,Thanks @grabbou
