### ISSUE TITLE
How to add screen from a different file?

### ISSUE THREAD

**Issue by kelvinblade** [react-community/react-navigation#1241]
In the example the two pages are in the same file.

```
class HomeScreen extends React.Component {
  static navigationOptions = {
    title: 'Welcome',
  };
  render() {
    return <Text>Hello, Navigation!</Text>;
  }
}

class ChatScreen extends React.Component {
  static navigationOptions = {
    title: 'Chat with Lucy',
  };
  render() {
    return (
      <View>
        <Text>Chat with Lucy</Text>
      </View>
    );
  }
}

const SimpleApp = StackNavigator({
  Home: { screen: HomeScreen },
  Chat: { screen: ChatScreen },
});
```

I want to move ChatScreen to a different file.

```
import ChatScreen from './ChatScreen'

const SimpleApp = StackNavigator({
  Home: { screen: HomeScreen },
  Chat: { screen: <ChatScreen /> },
});
```

This doesn't work, how do I set that as the screen?

**Comment by ashrithks** [comment]
You should export it,
I mean:-
export default class ChatScreen extends React.Component {
  static navigationOptions = {
    title: 'Chat with Lucy',
  };
  render() {
    return (
      <View>
        <Text>Chat with Lucy</Text>
      </View>
    );
  }
}

**Comment by grabbou** [comment]
@ashrithks is right, you put `class XXX` in a different file and prepend `export default` before class.

So that the end file is:
```js
export default class ...
```

Then, you just `import Screen from './file'` and reference it normally. See `examples/NavigationPlayground/js/App.js` for further hints. It's an official example that does exactly what you are asking.

**Comment by IpyCreator** [comment]
@grabbou you are right.
