### ISSUE TITLE
examples/ReduxExample not working 

### ISSUE THREAD

**Issue by somsin** [react-community/react-navigation#1242]
cannot find entry file "examples/ReduxExample/index.js" in any of the root.  
same error in NavigationPlayground.

what i used to run example .
Downloaded the ZIP for the github project
Extracted the Redux Example folder and copied it across to another area
run "npm install"
added rn-cli.config.js on root lable .
react-native run-ios

**Comment by grabbou** [comment]
Duplicate of #1244
