### ISSUE TITLE
cannot find entry file "examples/ReduxExample/index.js

### ISSUE THREAD

**Issue by somsin** [react-community/react-navigation#1244]
cannot find entry file "examples/ReduxExample/index.js" in any of the root.  
same error in NavigationPlayground.

what i used to run example .
Downloaded the ZIP for the github project
Extracted the Redux Example folder and copied it across to another area
run "npm install"
added rn-cli.config.js on root lable .
react-native run-ios

**Comment by grabbou** [comment]
Please follow official guide on how to run example project rather than doing steps like copying files outside of the project.

https://github.com/react-community/react-navigation/blob/master/docs/guides/Contributors.md#run-the-example-app

**Comment by sergioutama** [comment]
@grabbou i face similar issue
Already following the guide however the issue persist.

Any other alternative?

**Comment by deathemperor** [comment]
I have the same issue running the example, despite following exactly what the guide says. In that guide, it's also unclear how to start ReduxExample like the NavigationPlayground.

This part:
```
cd examples/NavigationPlayground
npm install
cd ../..
npm start

# In a seperate terminal tab:
npm run run-playground-android
# OR:
npm run run-playground-ios
```

**Comment by naji247** [comment]
+1

**Comment by huzhennan** [comment]
in /examples/ReduxExample/android/app/src/main/java/com/reduxexample/MainApplication.java
remove 
`  
   @Override
   public String getJSMainModuleName() {
      return "examples/ReduxExample/index";
    }
`

it work for me

**Comment by robtaireeo** [comment]
and for iOS: 

`jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];`
