### ISSUE TITLE
current screen not getting logged 

### ISSUE THREAD

**Issue by abhitheawesomecoder** [react-community/react-navigation#1245]
this code only logs current screen when app loads but not when there is screen transition

function getCurrentRouteName(navigationState) {
if (!navigationState) {
return null;
}
const route = navigationState.routes[navigationState.index];
// dive into nested navigators
if (route.routes) {
return getCurrentRouteName(route);
}
return route.routeName;
}

const RouteConfigs = {
Login: {screen:Login},
Home: {screen:Home},
Chat: {screen:Chat},
}

const StackNavigatorConfig = {
headerMode: 'none',
}

const AppNavigator = StackNavigator(RouteConfigs, StackNavigatorConfig)

export default () => (
<AppNavigator
onNavigationStateChange={(prevState, currentState) => {
console.log("Change");
const currentScreen = getCurrentRouteName(currentState);
const prevScreen = getCurrentRouteName(prevState);

  if (prevScreen !== currentScreen) {
    // to track screen change
    console.log(currentScreen);
  }
}}

/>
);

**Comment by grabbou** [comment]
Can you please format your code and follow Github issue template? That makes it easier for us to read your issues and provide support.

As far as your question goes, `onNavigationStateChange` is meant to be called `on state update`, which doesn't happen during transition.

Transition is a result of state update.

**Comment by abhitheawesomecoder** [comment]
so how can i attach a listener for screen transition which also logs the current screen user is viewing

**Comment by grabbou** [comment]
`const currentScreen = getCurrentRouteName(currentState);` this is showing you the "currentScreen".

**Comment by abhitheawesomecoder** [comment]
and how can i listen to the screen transition?
