### ISSUE TITLE
Redux props into navigator's contentComponent

### ISSUE THREAD

**Issue by aalices** [react-community/react-navigation#1246]
I am trying to render a header (not being a nav header, just a label above drawer items) for DrawerNavigator that has a greeting with currently logged in user. I am also using the `contentComponent` property to use a custom View for the drawer. Username comes from Redux but the `props` that are passed to `contentComponent` do not contain the redux ones. Am I missing something?

```
const NavigationDrawer = DrawerNavigator(routes, {
  initialRouteName: 'Dashboard',
  contentOptions: { ... }
  },
  contentComponent: props => (
    <View style={styles.drawer}>
      <NavigationDrawerHeader username={props.username} />
      <DrawerView.Items {...props} />
    </View>
  )
});

const mapStateToProps = (state) => {
  return {
    username: getUsername(state),
  };
};

export default connect(
  mapStateToProps,
)(NavigationDrawer);
```

**Comment by grabbou** [comment]
The `props` that `contentComponent` receive are props used for rendering that component, not the ones you have passed from Redux store to your screen (or even NavigationDrawer). 

If you need to read from `Redux`, you should connect your `contentComponent` with `connect()` instead.

Happy to provide further assistance.
