### ISSUE TITLE
CardStackTransitioner fails to pass router down

### ISSUE THREAD

**Issue by blackxored** [react-community/react-navigation#1247]
I just upgraded my fork to beta 8, after getting weird "Cannot read property key of undefined" errors, I figured it's because `CardStackTransitioner` is failing to pass `router` back to `CardStack` which needs it in `_getScreenDetails`.

**Comment by grabbou** [comment]
Can you try running `master`? This is such a fundamental bug that we would've noted it earlier.

**Comment by blackxored** [comment]
Yeah I can look from the source it's fixed on master, thanks.

**Comment by AnatoliyGatt** [comment]
@blackxored Is it working for you right now? I think I got similar issue to this described in #1874.
