### ISSUE TITLE
Child scenes cause parent to lose state

### ISSUE THREAD

**Issue by Ehesp** [react-community/react-navigation#125]
Hello,

On a previous navigation lib I was using, navigating to a child scene and back again kept the initial scene/route in memory, and navigating back again kept the view in the same state.

For example, using StackNavigator my initial route is a ViewPager, each with a ScrollView. If I go to a ViewPager page which isn't the initial, and scroll down, navigating to a child route and back again (using `goBack()`) causes the ViewPager to reset and also the scroll position to be lost.

I get this is possible to fix with Redux and it also lowers memory consumption, but is there anything internally which would allow this to be possible?

**Comment by satya164** [comment]
AFAIK cardstack keeps scenes mounted, at least the immediate previous screen, so this shouldn't happen.

cc @ericvicenti any idea why this could happen?

**Comment by Ehesp** [comment]
Cheers.

My stack path is as follows... Matches is the ViewPager, Match is the child - assuming this is still correct?

```
 Matches: {
    screen: Matches,
  },
  Match: {
    screen: Match,
    path: 'match/:id',
  },
```

**Comment by satya164** [comment]
Looks correct to me.

BTW you can use the `TabNavigator` instead of a viewpager. The state is stored in navigation state and you also get automatic back button handling (optional). Though this doesn't solve the original issue.

**Comment by Ehesp** [comment]
@satya164 Ideally yes we would use that... however we can have lots of tabs which will span more than the full width of the screen. Therefore when the user swipes along to a view off screen the tab bar would need to move with it and re-align itself... https://github.com/react-community/react-navigation/issues/86 shows an example :)

**Comment by Ehesp** [comment]
I am using Redux, if that is causing the issue.

**Comment by grabbou** [comment]
Have you managed to solve it by any chance?

**Comment by skevy** [comment]
Pinging OP on this issue. cc @Ehesp

**Comment by kelset** [comment]
Since @skevy pinged the OP in May and we haven't heard back, I'm closing this issue.
