### ISSUE TITLE
how can i listen to the screen transition?

### ISSUE THREAD

**Issue by abhitheawesomecoder** [react-community/react-navigation#1250]
how can i listen to the screen transition?

**Comment by satya164** [comment]
there's no API to do that

**Comment by cooperka** [comment]
@abhitheawesomecoder if you just want to know when the navigation state changes (from one screen to another) this might actually be what you're looking for -- https://reactnavigation.org/docs/guides/screen-tracking

**Comment by grabbou** [comment]
We have already discussed that in these issues: https://github.com/react-community/react-navigation/issues?q=is%3Aissue+author%3Aabhitheawesomecoder+is%3Aclosed where I provided you a comprehensive answer on `why` there's no way to listen to `transition` and how the state is set.

If you believe we are wrong it makes sense to continue discussion in that issue to have better context.
