### ISSUE TITLE
Params not passing between tabs

### ISSUE THREAD

**Issue by FacuAcosta** [react-community/react-navigation#1251]
The documentation says the you can pass params using the navigate function, so I'm doing this:
 
`this.props.navigation.navigate('available', { incidentId: incident._id });`

The goal is to pass this "incident._id" to another tab called 'available', the main tab and the next tab are in the same TabNavigator. The problem comes here: in the Navigation Dispatch console log, it seems that the param is correctly passed:

<img width="934" alt="screen shot 2017-04-26 at 14 56 12" src="https://cloud.githubusercontent.com/assets/19332669/25438193/919a60de-2a90-11e7-94a6-997d8803749b.png">

But when I `console.log(this.props.navigation);` the params seems to disappear, am I doing something wrong?

<img width="919" alt="screen shot 2017-04-26 at 14 58 14" src="https://cloud.githubusercontent.com/assets/19332669/25438265/cbb0ec20-2a90-11e7-8fc1-ba16bf59967e.png">

I'm using "react-navigation": "^1.0.0-beta.7" and react-native 15.0.0 so I don't know if its an issue with the dependencies.

**Comment by grabbou** [comment]
I believe this got fixed in https://github.com/react-community/react-navigation/commit/511cd3e1bee99352665d4c454c19398578845fea. That is part of `v8` and latest master. 

Also, I believe this is similiar to #80 or #134 ?

**Comment by jsina** [comment]
@grabbou I have the same problem. here is my code but as you can see in the picture there is no param after navigating.

```
 this.props.navigation.navigate(routeNameConstant.RESERVED, { forceUpdate: true });
```
<img width="284" alt="screen shot 1397-02-30 at 18 12 35" src="https://user-images.githubusercontent.com/2977960/40281425-a88522de-5c76-11e8-9c1f-c01001c6ccf5.png">
