### ISSUE TITLE
No way to search documentation

### ISSUE THREAD

**Issue by cooperka** [react-community/react-navigation#1252]
There's no clear way to search the [docs site](https://reactnavigation.org/docs/intro/) for keywords. A simple first step might be to just add a link to the table of contents that says **Search** and have it link to [GitHub advanced search](https://github.com/search?q=test+repo%3Areact-community%2Freact-navigation+path%3A%2Fdocs%2Fguides&type=Code&ref=advsearch) with prepopulated values.

Thoughts?

**Comment by ericvicenti** [comment]
This would be super handy. Maybe we could tie it in with Algolia search like we do on the RN website

**Comment by grabbou** [comment]
@ericvicenti I am thinking why we don't create a reusable library for those docs? Looks like we are basically re-doing what RN team is doing.

Anyways, there's also WIP for adding version switch, so we might want to make sure work is synced.

**Comment by matthamil** [comment]
For the time being, you can use GitHub to search for keywords and look through the documentation `.md` files to find what you're looking for. It's an inconvenient approach, but it's a workaround until search is added.

**Comment by cooperka** [comment]
@matthamil that's my original suggestion :) I like Algolia better though, it seems super simple: https://github.com/facebook/react-native/search?utf8=%E2%9C%93&q=algolia

**Comment by matthamil** [comment]
@cooperka I should have read more than the title :)

**Comment by matthamil** [comment]
Resolved in https://github.com/react-community/react-navigation/pull/2606
