### ISSUE TITLE
Screen navigation without transition

### ISSUE THREAD

**Issue by X-Tender** [react-community/react-navigation#1254]
How can I disable any animation between screen Change?
Just want an instant Screen change.

**Comment by grabbou** [comment]
This is not yet supported, but this issue tracks progress: #175

**Comment by nihgwu** [comment]
you can use `transitionConfig` to achieve this, define a `CustomNavigator`

**Comment by X-Tender** [comment]
I achieved it now this way:
```javascript
transitionConfig : () => ({
	transitionSpec: {
		duration: 0,
		timing: Animated.timing,
		easing: Easing.step0,
	},
}),
```

**Comment by kelset** [comment]
Thanks @X-Tender for the snippet, did the trick for me too 👏 - probably best workaround until #175 is completed.

**Comment by bernatfortet** [comment]
@X-Tender or @kelset could you provide more context on how you achieved this? It would be great because I also want an instant transition to another page, but I don't know where to begin with.

Thanks!

**Comment by kelset** [comment]
Not yet. Keep an eye on #175 for that

**Comment by Tom29** [comment]
@bernatfortet hey, can i use it for particular `navigate` action?
i want to disable transition at the beginning, then enable it again.

**Comment by bernatfortet** [comment]
@Tom29, Not that I known about.
@kelset pointed out to a thread that talks about that.

**Comment by limichange** [comment]
```js
import CardStackStyleInterpolator from 'react-navigation/src/views/CardStackStyleInterpolator';
import panels from './panels'

const AppNavigator = StackNavigator(
    loadingPanel: {
      name: 'loadingPanel',
      screen: panels.loadingPanel,
    }
  },
  {
    initialRouteName: 'loadingPanel',
    headerMode: 'none',
    transitionConfig: () => {
      return { 
        screenInterpolator: CardStackStyleInterpolator.forInitial 
      }
    }
  }
);
```

**Comment by Rested** [comment]
Here's a hack that might be useful for some people.
`transitionSpec: {
      duration: 800,
      timing: Animated.timing,
      easing: Easing.out(Easing.poly(4)),
    },
    screenInterpolator: sceneProps => {
       const { layout, position, scene } = sceneProps;
       const { index } = scene;

       const width = layout.initWidth;
       const translateX = position.interpolate({
         inputRange: [index - 1, index, index + 1],
         outputRange: [width, 0, 0],
       });


       if (index <= 1){
           return {};
       }

       return {transform: [{ translateX }] };
     }`

This allows instant transition from first to second screen (but new component can't receive input until the duration has elapsed). You could also use scene.route.routeName and scene.isActive to do this for specific transitions.

**Comment by nihp** [comment]
How to config transition in react-native apps using react-navigation.

**Comment by shahabrauf18** [comment]
Transition config for a specific route

```
const StoryNav = createStackNavigator({
    Home: Home,
    Detail: Detail,
    Search: Search,
}, {
    initialRouteName: 'Home',
    transitionConfig: ({ navigation }) => ({
        transitionSpec: {
            duration: getTransitionDuration(navigation),
            easing: Easing.step0
        }
    })

});
```
```
function getTransitionDuration(navigation) {
    let duration;
    if (navigation.state.routes.length > 1) {
        navigation.state.routes.map(route => {
            if (route.routeName === "Search") {   // Disable transition for Search route
                duration = 0;
            } else {
                duration = 300;
            }
        });
    }
    return duration
}
```
