### ISSUE TITLE
Screen config getting overwritten by navigator's default

### ISSUE THREAD

**Issue by blackxored** [react-community/react-navigation#1255]
Bare with me since I'm kind of new to flat options (which is quite recent, obviously). If you set default navigator options on the navigators the screen config would get overwritten.

I've a navigator with `navigationOptions: () => ({ headerStyle: { backgroundColor: '#fff' })` and a component/screen like:

```javascript
static navigationOptions = ({ navigation }) => ({
  headerStyle: {
    shadowOpacity: 0,
  }
 // ...
})
```
In case you're curious that's to override the header's border for a screen. 

This configuration doesn't only not get merged (which I thought it was the point of flat options and not having to manually merge them), but instead of replacing the navigator's config with the screen's (which would bring another issue on how to access the default like we used to have a parameter in the past), the navigator config is the one getting persisted, so I end up with `headerStyle: { backgroundColor: '#fff' }`, and no trace of the screen config's header style, neither merged or replaced.

EDIT: I'm using nested navigators Stack to Tab, the view whose configuration gets overriten it's a tab item.

EDIT 2: It doesn't seem to be that much of an issue with the new implementation of `getScreenConfig` but more of that `CardStack` is calling the top-level router which doesn't have a notion of any child routers, so either of those needs to be aware that a route can have child routes and get the screen config from there. The tests for this seems to have been removed.

**Comment by jeanregisser** [comment]
Hit a somewhat similar issue.
Note that you can still access the default options and merge styles manually:

Before (beta7):
```javascript
static navigationOptions = {
  header: (_, defaultHeader) => ({
    ...defaultHeader,
    style: [defaultHeader.style, styles.screenCustomStyle],
  }),
};
```

Now (beta9):
```javascript
static navigationOptions = ({ navigation, navigationOptions }) => ({
  headerStyle: [navigationOptions.headerStyle, styles.screenCustomStyle],
});
```

**Comment by prontiol** [comment]
I have exactly the same issue.
I have default config defined in my navigator and in one screen I need to update header, but my `static navigationOptions` just does not change anything at all.
@blackxored Did you manage to solve your issue?

**Comment by blackxored** [comment]
@prontiol Yes, but unfortunately not without manual merging, in my top navigator:

```javascript
{
    navigationOptions: ({ navigationOptions }) => {
      // console.log('APP NAVIGATOR', args);
      return {
        headerBackTitle: 'Back',
        headerTintColor: theme.colors.black,
        headerStyle: {
          backgroundColor: theme.colors.white,
          ...navigationOptions.headerStyle,
        },
      // ...
      };
    },
  },
)
```

Hope that helps.

**Comment by beausmith** [comment]
@prontiol - I'm having the issue you describe in beta.11. 

Have you had any luck with a solution?

Specifically [Default Navigation Options](https://reactnavigation.org/docs/navigators/navigation-options#Default-Navigation-Options) doesn't work as it states:

> The navigationOptions from the screen will be merged key-by-key with the default options coming from the navigator. Whenever both the navigator and screen define the same option (e.g. headerTintColor), the screen wins. 

I did discover that you can get to the `navigationOptions` defined in the screen by defining `navigationOptions` as a function in the router with `navigationOptions` as a parameter. For example if a title is defined in the screen like this…

    static navigationOptions = {
      title: 'screen title'
    }

…then used this in the router to get to the title param specified in the screen:

    navigationOptions: ({ navigationOptions }) => ({
      title: navigationOptions.title || 'default title'      
    })

**Comment by kelset** [comment]
Pinging OP @blackxored since this issue is quite old and related to an old version of the lib. If no answer I'll close in 7 days.

**Comment by blackxored** [comment]
Feel free to close if nobody else is having this. Unfortunately I’m locked
into a fork for the time being.

-- 
Best Regards,

Adrian Perez
https://adrianperez.codes
