### ISSUE TITLE
v2 Roadmap

### ISSUE THREAD

**Issue by grabbou** [react-community/react-navigation#1263]
Note: We are currently working on v1 - you can track progress in #723. Once completed, we will start implementing issues below.

For the second release, lets focus on new ways of customising transitions, and overriding navigation components.

- [ ] Support custom transitions per screen #175 

We look forward to your feedback. Feel free to suggest important features you'd like to see in next release.

**Comment by wilomgfx** [comment]
I think releases and goals like this be inside a project. It would make it easier to follow and find.

**Comment by necolas** [comment]
I'd like to make a suggestion: to get react-navigation working with react-native-web. RNW implements much of the RN API and we should be able to support the full feature set of react-navigation on web for people using RNW.

**Comment by nico1510** [comment]
Not really a feature but the issue with the StackNavigator [rendering too many screens](https://github.com/react-community/react-navigation/issues/706) is a blocking issue for anyone who wants to bring an android app into production.

**Comment by vomchik** [comment]
@nico1510  it's really blocker for more developers(

**Comment by matthamil** [comment]
@wilomgfx see https://github.com/react-community/react-navigation/issues/561. For the remainder of v1, it looks like they are going to rely on issues. See https://github.com/react-community/react-navigation/issues/723 for the v1 roadmap.

**Comment by rafayepes** [comment]
I'd like to define StackNavigator mode at route, instead of Navigator level. Somehow, related to #175

**Comment by MovingGifts** [comment]
1. Use `replace` functionality when navigating to `replace` the current scene.
2. Prevent push more than once when tapping navigation button too fast.

**Comment by MovingGifts** [comment]
3. By default, add a null `params` key to navigation state, instead of only having the `params` key exist only if there is a passed param.

**Comment by annelorraineuy** [comment]
When the app is RTL (Farsi/Hebrew, etc), the issue where the drawer nav is open and on screen on hide is important to address as well. This limits apps using drawers to be fully localization-ready for production. #270

**Comment by shirbr510** [comment]
any news about #706 ?
might count as stable if it will be pushed to V1

**Comment by efkan** [comment]
Caching screens according to their `NavigationOptions` would be great. 
Especially when working on screens that have a lot of control or have a map component.
Currently the components re-render when the stack is changed. This causes to lost the entered values or position of the map.

**Comment by matthamil** [comment]
Closing in favor of https://github.com/react-community/react-navigation/issues/2585
