### ISSUE TITLE
StackNavigator routes within a DrawerNavigator shouldn't appear in the drawer

### ISSUE THREAD

**Issue by sonaye** [react-community/react-navigation#1266]
![kapture 2017-04-27 at 3 18 56](https://cloud.githubusercontent.com/assets/23000873/25462550/58f9e87c-2af8-11e7-924d-cdf06666e8f1.gif)

```javascript
<Drawer>
  <Stack shouldAppearInDrawer={true}>
    <Card shouldAppearInDrawer={false}>
    <Card shouldAppearInDrawer={false}>
    <Card shouldAppearInDrawer={false}>
  </Stack>
</Drawer>
```

To address this issue, either these nested routes (cards) should ~~always~~ be hidden by default in the drawer, or a new prop -analogues to `header: null`- can be passed in the navigation options to disable the drawer for that item completely, meaning that we can still navigate to it within the drawer navigator but it's not listed in its items.

It's better to offer more control than to force a default behavior in this case i would think, that's why I crossed "always" above, with the option introduced we can do something like this now:

```javascript
<Drawer>
  <Stack shouldAppearInDrawer={true}>
    <Card shouldAppearInDrawer={false}>
    <Card shouldAppearInDrawer={false}>
    <Card shouldAppearInDrawer={false}>
  </Stack>
  <Secret shouldAppearInDrawer={false} />
</Drawer>
```

I would also suggest adding an option to allow opening the drawer via code only, in some nested screens it's common enough and very reasonable to not allow sliding from the edge to reveal the drawer.

**Proposed API**
```javascript
// do not list route in the drawer
navigationOptions: {
  drawer: null
}

// do not allow opening the drawer via gestures
navigationOptions: {
  drawer: false
}
```

**Comment by sonaye** [comment]
Here is a good question, why did I nest StackNavigator under DrawerNavigator in the first place? because I needed the header, even if it's just a single screen. Perhaps there could be a way to enable the header component for other navigators, drawer and tab.

**Comment by sonaye** [comment]
A quick workaround would be to set the `drawerLabel` and `drawerIcon` props for of the cards to match with the parent stack props for the drawer.

```javascript
<Drawer>
  <Stack  shouldAppearInDrawer={true}  drawerLabel="Same" drawerIcon={() => <Same />}>
    <Card shouldAppearInDrawer={false} drawerLabel="Same" drawerIcon={() => <Same />}>
    <Card shouldAppearInDrawer={false} drawerLabel="Same" drawerIcon={() => <Same />}>
    <Card shouldAppearInDrawer={false} drawerLabel="Same" drawerIcon={() => <Same />}>
  </Stack>
  <Secret shouldAppearInDrawer={false} />
</Drawer>
```

but then we run into another issue, clicking an item in the drawer always pushes a new card (also present when navigators are not nested, so this should be addressed regardless of this use case i think), even if it was already opened/the current. The current screen selected should have a disabled touchable component to prevent this glitch.

![kapture 2017-04-27 at 10 10 18](https://cloud.githubusercontent.com/assets/23000873/25473171/140c1d7c-2b37-11e7-8a62-5183b6cb84e8.gif)

**Comment by sonaye** [comment]
cc: @grabbou @satya164

**Comment by ippa** [comment]
I've been having the exact same issues. I ended up nesting the DrawerNavigator Inside StackNavigator. The problem then is that the drawer is boxed inside a page, not covering the screen from top to bottom. I've yet to find

While experimenting I also ran into the "drawer pushes pages onto the stack" problem, but I Think that can be workaround with https://github.com/react-community/react-navigation/issues/135 and doing manual code for each drawer-click.

All in all, I feel a drawer together with stacknavigator is a supercommon usecase for mobile navigation and there should be a straightforward way to do it.

Regarding issue #135  linked above it's on the roadmap ( https://github.com/react-community/react-navigation/issues/723 ) for mid april, so I'm hopeful :)

**Comment by sonaye** [comment]
> but then we run into another issue, clicking an item in the drawer always pushes a new card (also present when navigators are not nested, so this should be addressed regardless of this use case i think), even if it was already opened/the current. The current screen selected should have a disabled touchable component to prevent this glitch.

This should be fixed now with this https://github.com/react-community/react-navigation/commit/608217abbc0a44976b64b77950760e1c4106288f.

**Comment by sonaye** [comment]
This is my workaround, since the fix hasn't been not released yet.

```javascript
import { EventEmitter } from 'fbemitter';

const NavigationEvents = new EventEmitter();

// ..
componentWillMount() {
  this.navigationEvents = NavigationEvents.addListener('change', navigation =>
    const route = navigation.currentState.routes[0].index; // your current route index
    // ..
  );
}

componentWillUnmount() {
  this.navigationEvents.remove();
}

// ..
<Root // your root navigation component
  onNavigationStateChange={(prevState, currentState) => {
    NavigationEvents.emit('change', { prevState, currentState });
  }}
/>
```

Now that you know your current route index, you can write your own custom <DrawerItems /> that only allows pressing labels when they are not focused.

**Comment by sonaye** [comment]
https://github.com/react-community/react-navigation/issues/1914 should fix the other issue, workaround is as described in https://github.com/react-community/react-navigation/issues/1266#issuecomment-297638990.
>A quick workaround would be to set the drawerLabel and drawerIcon props for of the cards to match with the parent stack props for the drawer.

**Comment by Rebaiahmed** [comment]
@sonaye  can you share your code for you SideBar Menu with nested navigation ?
