### ISSUE TITLE
Dynamic StackNavigator size

### ISSUE THREAD

**Issue by mehtamanan** [react-community/react-navigation#1268]
Hey,

I am working on a project that has persistent bottom tabs (think instagram style navigation). For example, the layout may look like this:

```
TabNavigator: Login Scren
              TabNavigator:
                                       - HomeFeed
                                       - SearchScreen
                                       - AddPost
                                       - Notifications
                                       - Profile
```

A) I want to make the newsfeed like any other; on the newfeed, you can tap on a person's name (say Manan) and it takes you Manan's profile (still being on home tab). Now, you're on Manan's profile and say you click on a person appearing in Manan's posts. You go to that person's profile etc (yet being on the home tab). It's a dynamic stack where you keep pushing screens. In the end, pressing back will take me back to my newfeed following the same route back...

How do I go about implementing? Is there support for this kind of navigation?

B) Can I add a button on the tab that just shows a modal instead of navigating to the screen?

**Comment by spencercarli** [comment]
A) Yep! Just create a StackNavigator for your HomeFeed tab with the newsfeed and profile tabs. See [nesting navigators](https://reactnavigation.org/docs/intro/nesting)

B) You'll have to setup your [own tabbBarComponent](https://reactnavigation.org/docs/navigators/tab#TabNavigatorConfig)
