### ISSUE TITLE
Custom icon style in tabs using top tab bar

### ISSUE THREAD

**Issue by michaelduminy** [react-community/react-navigation#127]
I'd like to display icons that are bigger than the 24x24 size constraint dictated here: 

```javascript
_renderIcon() {
  ...
  return (
    <TabBarIcon
      ...
      style={styles.icon}
    />
  );
}
...
const styles = StyleSheet.create({
  icon: {
    height: 24,
    width: 24,
  },
```
https://github.com/react-community/react-navigation/blob/master/src/views/TabView/TabBarTop.js#L126-L128

My suggestion is to allow custom icon styles to be passed in to override the defaults.

**Comment by lslima91** [comment]
@michaelduminy are you able to render any icon on android?

**Comment by michaelduminy** [comment]
@lslima91 yup, however I want the icons to be bigger. Our design has almost full tab-sized icons in a 4-tab setup.

**Comment by KakarN** [comment]
Yes, same problem.

**Comment by grabbou** [comment]
You can set custom `tabBarComponent` and implement whatever interactions you want. To start with, you can copy the built-in one and tweak whatever you feel is needed.

https://github.com/react-community/react-navigation/blob/master/src/views/TabView/TabView.js#L126

**Comment by michaelduminy** [comment]
Thanks @grabbou 
We ended up redesigning the icons for now and it actually looks better 👍 

It is weird that the top tab bar defines limits to icon sizes while the bottom one doesn't.

**Comment by Donhv** [comment]
I don't know fix issue. pls help me?
