### ISSUE TITLE
Change Tab bar background color when switching between tabs

### ISSUE THREAD

**Issue by zakster12** [react-community/react-navigation#1270]
I need to change the background color of the Tab bar when switching between tabs. To illustrate that here is an example with images:

![screen shot 2017-04-26 at 5 47 28 pm](https://cloud.githubusercontent.com/assets/25477229/25470190/bac58c60-2b29-11e7-81e2-a94035a26d66.png)
![screen shot 2017-04-26 at 5 48 21 pm](https://cloud.githubusercontent.com/assets/25477229/25470191/bac5e746-2b29-11e7-9589-8a4eb943ea2f.png)

The idea is if I press first or third tab the Tab bar background color to be orange but if I press second tab  the Tab bar background color to be green. But I am not sure is it possible to control the tabBarOptions dynamically?

Here is my Tab bar configuration:

```import { TabNavigator } from 'react-navigation';

// Tab-Navigators
import TabOneNavigation from './../tabOne/views/TabOneNavigation';
import TabTwoNavigation from './../tabTwo/views/TabTwoNavigation';
import TabThreeNavigation from '../tabThree/views/TabThreeNavigation';

import Colors from './../../Constants/Colors';
import Fonts from './../../Constants/Fonts';

const routeConfiguration = {
	TabOneNavigation: { screen: TabOneNavigation },
	TabTwoNavigation: { screen: TabTwoNavigation },
	TabThreeNavigation: { screen: TabThreeNavigation },
};

const tabBarConfiguration = {
	tabBarOptions: {
		activeTintColor: 'white',
		inactiveTintColor: 'lightgray',
		labelStyle: {
			fontSize: 10,
			fontFamily: Fonts.book
		},
		style: {
			backgroundColor: 'orange',
			borderTopWidth: 1,
			borderTopColor: 'white'
		},
	}
};

export const TabBar = TabNavigator(routeConfiguration, tabBarConfiguration);

export const tabBarReducer = (state, action) => {
	if (action.type === 'JUMP_TO_TAB') {
		return { ...state, index: 0 };
	}

	return TabBar.router.getStateForAction(action, state);
};```

**Comment by satya164** [comment]
Here is a demo - https://snack.expo.io/rkEaFYNk-

**Comment by zakster12** [comment]
@satya164 I didn't see that you answered my question. That's exactly what I am trying to do. Thank you so much!!!

**Comment by zakster12** [comment]
@satya164 I am sorry for this but why when I change TabBar to TabView.TabBarBottom it stops working. Demo - https://snack.expo.io/rJ8jkDwJW

![screen shot 2017-04-27 at 4 31 30 pm](https://cloud.githubusercontent.com/assets/25477229/25663563/b4703756-3020-11e7-88cd-2c2211e6e7cb.png)

**Comment by satya164** [comment]
It's because `TabBarBottom` doesn't use `Animated.View`. If you send a PR changing https://github.com/react-community/react-navigation/blob/master/src/views/TabView/TabBarBottom.js#L138 to `Animated.View`, I'll merge it.

**Comment by zakster12** [comment]
@satya164 Thank you for your fast response. Here is the pull request: 
https://github.com/react-community/react-navigation/pull/1360

**Comment by AshokICreate** [comment]
Thanks to @satya164  and @zakster12 

And here is the example for `TabBarBottom`.

**Comment by llitfkitfk** [comment]
for android 

indicatorStyle: {
            height: null,
            top: 0,
            backgroundColor: 'red',
},

**Comment by tonysouzza25** [comment]
Thank you! It was what I needed =)

**Comment by AarshApple** [comment]
> for android
> 
> indicatorStyle: {
> height: null,
> top: 0,
> backgroundColor: 'red',
> },

 @llitfkitfk  what about iOS does this work ?

**Comment by vikrantnegi** [comment]
I'm getting error:
`TypeError: Cannot read property 'interpolate' of undefined`.

I'm using this:

"react-navigation": "^3.3.2",
"react": "^16.6.3",
 "react-native": "^0.58.4",

**Comment by jugal-newvision** [comment]
How to use a border on active footer tab-bar in react native?

**Comment by Sumishu** [comment]
> for android
> 
> indicatorStyle: {
> height: null,
> top: 0,
> backgroundColor: 'red',
> },

Worked for iOS too!

**Comment by NasreenUstad** [comment]
> for android
> 
> indicatorStyle: {
> height: null,
> top: 0,
> backgroundColor: 'red',
> },

I really appreciate your solution

**Comment by KennedyKeinstein** [comment]
> for android
> 
> indicatorStyle: {
> height: null,
> top: 0,
> backgroundColor: 'red',
> },

Work perfectly Thanks!

**Comment by frankboris** [comment]
`tabBarColor` do the trick.

```
<Tab.Screen
    name="route_name"
    component={Component}
    options={{
        tabBarLabel: 'Label',
        tabBarColor: '#e74c3c',
    }}
/>
```

**Comment by 1stmuse** [comment]
> 

this doesnt work
