### ISSUE TITLE
headerVisible:flase doesn't work in 1.0.0-beta.9

### ISSUE THREAD

**Issue by bestv2** [react-community/react-navigation#1272]
### Current Behavior
headerVisible:flase doesn't work in 1.0.0-beta.9.
I've set  headerMode: 'screen',
```
const AppNavigator = StackNavigator(RouterConfig, {
    headerMode: 'screen',

    navigationOptions: {
        headerTintColor: '#ffffff',
        headerBackTitle: null,
        headerTitleStyle: {
            width: 300,
        },
        headerStyle: {
            backgroundColor: Colors.header_bg,
        },
        headerMode: "screen"
    },
    headerComponent: NavigationHeader
});
```
```
static navigationOptions = {
        title: 'Index',
        headerVisible: false,
    }
```
this doesn't work for me 
neither
```
static navigationOptions = {
        title: 'Index',
        header: {
            visible: false
        }
    }
```
header: {
visible: false
}
will throw an expcetion 
ExceptionsManager.js:63 Objects are not valid as a React child (found: object with keys {visible}). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons.
### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0.beta.9
| react-native     |  0.43.3
| node             | 6.5.0
| npm or yarn      | 3.10.9

**Comment by nihgwu** [comment]
please check the release note first
`header: null`

**Comment by mdeprezzo** [comment]
To hide the tab bar, set tabBarVisible to false inside navigationOptions. Now in beta 9 works fine.

**Comment by bestv2** [comment]
@nihgwu thanks
