### ISSUE TITLE
How to dynamically change the initialNavState ?

### ISSUE THREAD

**Issue by guoliang1206** [react-community/react-navigation#1273]
I am imitate the ReduxExample to design a login progress ,the initialNavState when first run should be 
```
const initialNavState = {
    index:0,
    routes: [
        { key: 'InitA', routeName: 'Login' },
        { key: 'InitB', routeName: 'Main' },     
};
```

then , when I am logeedin ,if I restart my app,  the  initinalNavState should be  
```
 initialNavState = {
    index:1,
    routes: [
        { key: 'InitA', routeName: 'Login' },
        { key: 'InitB', routeName: 'Main' },
      
};
```
but the problem is ,  I used redux-persist to save my data, if I restart the app, store created by reducer, and reducer accept the initialNavState like unlogin status, then they do `{ type: 'persist/REHYDRATE'` to recover my store.

so Login scene always display befrore Main screen.

How to handle this?

  "react-navigation": "git+https://github.com/react-community/react-navigation.git#77313a2",
    "react-redux": "^5.0.4",
    "redux": "^3.6.0",
    "redux-persist": "^4.6.0",
```

**Comment by guoliang1206** [comment]
https://github.com/rt2zz/redux-persist/issues/338  this is the detail.  I am try to use the AsyncStorage, but it is asyn, it can't give me data when I used.

**Comment by cooperka** [comment]
One option: You could add a splash screen that's always the default route, and once the redux store has been rehydrated you could navigate to the real first route.

**Comment by guoliang1206** [comment]
@cooperka  but i found another question, my Main Screen is a tabNavigator, 
```
Main:{
index0:'page1',
index1:'page2',
index2:'page3',
}
```
 if  I selected index 1 or index 2, when I restart app, it will flash to show the index 0 and   then show the index 1 or index 2,   
because the redux-persist will save  the state of Store, should I don't use the redux-persist?

**Comment by cooperka** [comment]
Redux persist is great, you can keep using it! My suggestion is to add a splash screen component and render that until you've rehydrated your store. THEN you can show your navigator, e.g.:

```jsx
render() {
  if (isLoading) {
    return <SplashScreen />;
  } else {
    return <AppNavigator />;
  }
}
```

With this method, you'll already know which route to show before your navigator is rendered. No more flashing of content.

**Comment by guoliang1206** [comment]
@cooperka  when in the func isLoading(), how to ensure the store has been rehydrated?  I see it will do a action  {type: 'persist/REHYDRATE',...}. can you guide me what is the judge conditions of store rehydrated?

**Comment by guoliang1206** [comment]
@cooperka  thanks man, I have solve this.  used connect(mapStateToProps)(App)

**Comment by wvteijlingen** [comment]
@guoliang1206: I have the same problem as you. How did you end up implementing the `isLoading` variable? How do you figure out when the store is rehydrated?

**Comment by guoliang1206** [comment]
when the store has been rehydrated, it will dispatch an action like this:
```
{ type: 'persist/REHYDRATE',
  payload: 
   { nav: 
      { index: 0,
        routes: 
         [ { type: 'Navigation/NAVIGATE',
             routeName: 'Main',
             routes: 
              [ { key: 'TaskList', routeName: 'TaskList' },
                { key: 'History', routeName: 'History' },
                { key: 'Setting', routeName: 'Setting' } ],
             index: 0,
             key: 'Init0' } ] },
     auth: { isLoggedIn: true },
     app: { isFinishLoading: true } },

```
note its type, and you can connect your component like this:
```
const mapStateToProps = state => {
   return ({
    isFinishLoading:state.app.isFinishLoading,
    })
};

export default connect(mapStateToProps)(App);
```

now ,in the render method of App 
```
render (){

        const { isFinishLoading } = this.props;  //this prop come from store

        if (!isFinishLoading){
            return <SplashScreen/>
        }else {
            return <AppWithNavigationState/>
        }

    }

```

**Comment by diego3g** [comment]
Hi, i tried doing what you mentioned. I have an reducer watching 'persist/REHYDRATE' that set up `isFinishedLoading` to true. But i want to change the initialRoute from my navigation or redirect the user to another page when i have an user at my store. So i tried this:

```
class Router extends Component {
  componentWillReceiveProps(props) {
    if (props.isFinishedLoading && props.signUser && Object.keys(props.signUser) > 0) {
      const actionToDispatch = NavigationActions.reset({
        index: 0,
        actions: [NavigationActions.navigate({ routeName: 'Calendar' })],
      })

      this.props.dispatch(actionToDispatch)
    }
  }

  render() {
    const { isFinishedLoading } = this.props;

    if (!isFinishedLoading) {
      return <Splash />
    } else {
      return (
        <Routes
          screenProps = {{
            ...bindActionCreators(ActionCreators, this.props.dispatch)
          }}
          navigation={
            addNavigationHelpers({
              state: this.props.nav,
              dispatch: this.props.dispatch
            })
          }
        />
      )
    }
  }
}
```

But it keeps looping through action 'navigate' from react-navigation and doesn't redirect user. What am i doing wrong?

**Comment by diego3g** [comment]
The only way i managed to change the initialRouteName based on my store was creating two Navigators with different routes for who is signed in or for the authentication pages like this:

```
export const AuthRoutes = StackNavigator({
  SignUp: { screen: SignUp },
  SignIn: { screen: SignIn }
}, {
  initialRouteName: 'SignPhone'
});

export const Routes = StackNavigator({
  Calendar: { screen: Calendar }
}, {
  initialRouteName: 'Calendar',
})
```

And then at my Router component, i wait for the application to load using the `isFinishedLoading` reducer that you mentioned and then use the Routes component based on the store. I also need to create two nav reducers, one for the authentication routes and another for the rest of the application, like this:

```
const authNavReducer = (state, action) => {
  const newState = AuthRoutes.router.getStateForAction(action, state)

  return newState || state
}

const navReducer = (state, action) => {
  const newState = Routes.router.getStateForAction(action, state)

  return newState || state
}

export default combineReducers(Object.assign(
  { authNav: authNavReducer },
  { nav: navReducer }
))
```

And now, at my Router component i check for the existence of the signUser and then call my routes component:

```
class Router extends Component {
  render() {
    const { isFinishedLoading } = this.props

    if (!isFinishedLoading) {
      return <Splash />
    } else {

      var RouterComponent = AuthRoutes;
      var navReducer = this.props.authNav;

      if (this.props.signUser) {
        RouterComponent = Routes;
        navReducer = this.props.nav;
      }

      return (
        <RouterComponent
          screenProps = {{
            ...bindActionCreators(ActionCreators, this.props.dispatch)
          }}
          navigation={
            addNavigationHelpers({
              state: navReducer,
              dispatch: this.props.dispatch
            })
          }
        />
      )
    }
  }
}
```

I don't know if it's the best way of doing it but it's the only way i managed to change the inital route based on my redux store. If you guys have anything to comment about my code, i would appreciate.

**Comment by hugows** [comment]
Diego, did you ever find another way to do this?

**Comment by diego3g** [comment]
Hello Hugo, yes. Currently, i'm doing this way:

At my main index file, i call the createRootNavigator function with a param that indicates whether i'm logged in or not, and then it returns a navigator based on this param. I have a navigator for logged in routes and logged out routes.

Please tell me if you understood my logic, otherwise i can send you an example project.

```js
// src/routes.js

import { StackNavigator } from 'react-navigation';

import Login from './pages/login';
import Logged from './pages/logged';

export const SignedOutRoutes = StackNavigator({
  Login: {
    screen: Login,
    navigationOptions: {
      title: "Entrar"
    }
  },
});

export const SignedInRoutes = StackNavigator({
  Logged: {
    screen: Logged,
    navigationOptions: {
      title: "Meu perfil"
    }
  },
});

export const createRootNavigator = (signedIn = false) => {
  return StackNavigator({
    SignedIn: { screen: SignedInRoutes },
    SignedOut: { screen: SignedOutRoutes }
  },
  {
    headerMode: "none",
    mode: "modal",
    initialRouteName: signedIn ? "SignedIn" : "SignedOut",
    navigationOptions: {
      gesturesEnabled: false
    }
  });
};
```

```js
// src/index.js

import React from 'react';
import { View } from 'react-native';

import { isSignedIn } from "./services/auth";

import { createRootNavigator, SignedOutRoutes, SignedInRoutes } from './routes';

export default class App extends React.Component {
  state = {
    signed: false,
    signLoaded: false,
  };

  componentWillMount() {
    isSignedIn()
      .then(res => this.setState({ signed: res, signLoaded: true }))
      .catch(err => alert("Erro"));
  }

  render() {
    const { signLoaded, signed } = this.state;

    if (!signLoaded) {
      return null;
    }

    const Layout = createRootNavigator(signed);
    return <Layout />;
  }
}
```

**Comment by eballeste** [comment]
@diego3g what does the reducer look like now that you're using a function to create the `RootNavigator`

**Comment by diego3g** [comment]
@eballeste the reducer is the same from docs:

```
//navigation/reducer.js

import { NavigationActions } from 'react-navigation';
import Routes from './routes';

const initialState = Routes.router.getStateForAction(NavigationActions.init());

const navReducer = (state = initialState, action) => {
  const nextState = Routes.router.getStateForAction(action, state);
  return nextState || state;
};

export default navReducer;
```

And in my `createStore` file:

```
import { createStore, combineReducers } from 'redux';
import navReducer from 'navigation/reducer';

const rootReducer = combineReducers({
  nav: navReducer,
});

return createStore(rootReducer);
```

Let me know if you got it working, otherwise i can create a repo to show what i'm doing.

**Comment by eballeste** [comment]
@diego3g thanks! What is `Routes` in the reducer? Is it a StackNavigator or a StackRouter object? This is where I am confused because in the examples you have to create a StackNavigator Component in the reducer and by default this will be set to `signedIn` false.

**Comment by derakhshanfar** [comment]
@cooperka thanks for response but imagine we have list view and when user tap on one item we want to show separate navigators with different route configs. what can we do for this senario?

**Comment by vjfuenzalida** [comment]
@diego3g when you use the method `isSignedIn()` from your services, do you get the user credentials/token from a persisted store (redux-persist or something)?
I just added redux-persist to my project, but I'm not sure when I'm able to access to persisted store (after rehydration of course). For the moment the only thing I need is to store a user's token with redux-persist so when the user close-open the app, he will still be logged in (by choosing the right navigator).
