### ISSUE TITLE
How to hide  navigation bar

### ISSUE THREAD

**Issue by DamonZPF** [react-community/react-navigation#1275]
### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  
| react-native     |  
| node             | 
| npm or yarn      |

**Comment by bakkan** [comment]
你是想隐藏 header 吧？下面这样就能隐藏了.

```js
class MyScreen extends React.Component {
  static navigationOptions = {
    header: {
       visible: false,
    }
  }
}

const appStack = StackNavigator({
  MyScreen: {
    screen: MyScreen,
  }
}, {
  headerMode: 'screen' // 这里必须设置成 screen
});
```

**Comment by mdeprezzo** [comment]
Which version of react navigation are you using ?

**Comment by bakkan** [comment]
1.0.0-beta.9

@mdeprezzo 
Could you please tell me how to implements this.
 Issue: https://github.com/react-community/react-navigation/issues/1276

**Comment by grabbou** [comment]
Check release notes, it's `header: null`, not `header: { visible: false }`. It was a breaking change.

**Comment by npomfret** [comment]
Isn't it `headerMode="none"`? https://reactnavigation.org/docs/navigators/stack#StackNavigatorConfig

**Comment by bvaibhav95** [comment]
`  static navigationOptions = {
    header: null
  }`

> just use this and Header will be hidden

**Comment by theOnkar** [comment]
How can I pass the params null or screen from a function in the component? I want the header to be visible/hidden on press of a button

**Comment by bvaibhav95** [comment]
I am not able to get you...on press on which button...button on header itself or any other button?....can you put picture or something?

**Comment by vishalgadhiya91** [comment]
navigationOptions = { header: null }

https://reactnavigation.org/docs/navigators/stack#header

**Comment by ganeshr-iprogrammer** [comment]
LoginScreen.navigationOptions = {  
   header : null
};

-try with particular screen name

**Comment by SnehalAgrawal** [comment]
Hello,
Here are the 3 Options to Hide Navigation Bar:

1. For the single screen, you can set header null in navigationOptions

static navigationOptions = {
    //To hide the ActionBar/NavigationBar
    header: null,
};
2. For the single screen, you can set header null in createStackNavigator like this

const App = createStackNavigator({
  First: {
    screen: HomeActivity,
    navigationOptions: {
      header: null,
    },
  },
});
3. Hide the header from all the screens in once using defaultNavigationOptions

const App = createStackNavigator(
  {
    First: {
      screen: HomeActivity,
    },
  },{
    defaultNavigationOptions: {
      header: null
    },
  }
);
![hidden_naavigation_bar_example1-166x300](https://user-images.githubusercontent.com/29939757/52870245-66f46600-316d-11e9-96ee-771bc9a29e3e.png)

Here is a tutorial which will show you the [3 Ways to Hide Navigation Bar in React Native Application](https://aboutreact.com/react-native-hide-navigation-bar-and-make-screen-full-screen/).
