### ISSUE TITLE
How to set different screen mode In A StackNavigator?

### ISSUE THREAD

**Issue by bakkan** [react-community/react-navigation#1276]
How to set different screen mode In A StackNavigator, like Twitter app header right button.
```js
const appStack = StackNavigator({
  Home: {
    screen: HomeScreen
  },
  tweetDetail: {
    screen: TweetDetailScreen
  },
  tweetEditor: {
     screen: tweetEditorScreen
  },
}, {
  mode: 'card'
});
```
StackNavigator screen mode was default to 'card', but tweetEditor screen is a modal mode.
Thank you.

**Comment by mdeprezzo** [comment]
Follow this dicussion [#175](url=https://github.com/react-community/react-navigation/issues/175)

**Comment by bakkan** [comment]
Thank you.

**Comment by nihgwu** [comment]
two `StackNavigator` with different mode nested in to a root `StackNavigator`

**Comment by bakkan** [comment]
@nihgwu It will render two headers and navigation.goBack() doesn't work as sometime. I don't know why.

**Comment by nihgwu** [comment]
nest a `card StackNavigator` to a `modal StackNavigator`, then the `card StackNavigator` is a screen for `modal StackNavigator`, you can hide the header of this screen(`card StackNavigator`)

**Comment by nihgwu** [comment]
https://github.com/nihgwu/react-native-dva-starter see my demo, but in this demo a hide the modal‘s header too

**Comment by bakkan** [comment]
Thanks.

**Comment by bakkan** [comment]
https://github.com/react-community/react-navigation/issues/232

**Comment by a289459798** [comment]
@nihgwu  I can't hide the modal‘s header，How to do?

**Comment by nihgwu** [comment]
@a289459798 `headMode: 'none'`

**Comment by a289459798** [comment]
@nihgwu  headMode: 'none'，the header hides

**Comment by a289459798** [comment]
@nihgwu headMode: 'none'，the modal StackNavigator header hides，if don't，the other card StackNavigator have two Navigator，but i need modal StackNavigator header don't hide

**Comment by just4fun** [comment]
@a289459798 - Did you resolve this issue?
