### ISSUE TITLE
Dynamically render screen

### ISSUE THREAD

**Issue by vinhtq** [react-community/react-navigation#1277]
I have stacknavigator as folow:

```
StackNavigator
---SignIn Screen
---Dashboard Screen
---Settings Screen
```
I want to check if user is logged in then I can dynamically render SignIn or Dashboard screen

Currently, I am checking the condition in SignIn Screen then navigate to Dashboard Screen. But if I do this, I will see transition from SignIn to Dashboard.

**Comment by kelset** [comment]
> Currently, I am checking the condition in SignIn Screen then navigate to Dashboard Screen. But if I do this, I will see the transition from SignIn to Dashboard.

Where do you do this check? In `ComponentDidMount`? May I suggest you try moving that behaviour in `ComponentWillMount`?

**Comment by matthamil** [comment]
Alternatively, you could create a splash screen component that displays until you check that the user is logged in. If they are logged in, navigate to the dashboard, otherwise navigate to the sign in screen.

**Comment by cooperka** [comment]
Dupe: https://github.com/react-community/react-navigation/issues/1273

Possibly even easier would be to show a non-Navigator splash screen component while loading from AsyncStorage, then show the Navigator when it's done loading and you have your data. Then there's no need to re-route anywhere during startup, it's just plain React logic.

**Comment by vinhtq** [comment]
I tried to intercept the route before it come like this guide:
https://reactnavigation.org/docs/routers/#Blocking-Navigation-Actions

But seem no hope.

I also know about the splashscreen. But the problem is my app is more complicated than that.

The screen I want to intercept is in a StackNavigator nested in a TabNavigator.

And it stays in fourth position in the TabNavigator.

**Comment by cooperka** [comment]
@vinhtq do you want to do this on startup, as soon as your app is opened? If so, I posted code in #1273 that should work for you too.

**Comment by spencercarli** [comment]
Hi! Since this issue has been quiet for a while I'm going to go ahead and close it. If the issue persists in the latest version of React Navigation please re-open!
