### ISSUE TITLE
Tab nesting could not be displayed

### ISSUE THREAD

**Issue by fangkyi02** [react-community/react-navigation#1278]
![image](https://cloud.githubusercontent.com/assets/3389652/25482176/10ac8242-2b83-11e7-993c-cdf250110c4e.png)

I set up the content of the tab, although it can be displayed in the normal but I can not slide but also if I open the sliding tab content will become unable to display

My RN version 0.43.3
React navigation version is just sync GitHub version

---Baidu translate---

**Comment by grabbou** [comment]
See https://github.com/react-community/react-navigation/pull/1234 for explanation on why that's happening
