### ISSUE TITLE
Dynamic tab item while app is running.

### ISSUE THREAD

**Issue by owl17** [react-community/react-navigation#1281]
My navigator:
- login scene
- tabbar:
        tab 1
        tab 2
        tab 3
        ...

Here is my situation, there are two type of users in my app: registered user and guest.
Literally, registered user can login into app and they can see 4 tabs in the tabbar. 

On the other hand, guest user can only see 3 tabs. Is it possible to do that ?

**Comment by cooperka** [comment]
@owl17 please see https://github.com/react-community/react-navigation/issues/717
