### ISSUE TITLE
Cannot find StackNavigator on web

### ISSUE THREAD

**Issue by ramancodians** [react-community/react-navigation#1285]
Hey Community,

I want to use `react-navigation` on the web. When I import the StackNavigator like this,
`import {StackNavigator} from 'react-navigation';` and log it, it says `undefined`.

I also tried `import RN from 'react-navigation';` but stack  navigation is **not present**. here's the log,

![image](https://cloud.githubusercontent.com/assets/2060784/25491457/a8bc27b8-2b8d-11e7-9931-92683e4cb4af.png)

I'm using same code on react native and it's working great. Please help!

**Comment by satya164** [comment]
There is no stack navigator on web. Use stack router with a custom navigator.

**Comment by nazrdogan** [comment]
Can you provide simple example @satya164  ? I really dont understand how to use it.
