### ISSUE TITLE
TabBarBottom option not displaying TabBar

### ISSUE THREAD

**Issue by jarredszabadi** [react-community/react-navigation#1287]
Setting `tabBarComponent: TabView.TabBarBottom` or `tabBarComponent: TabView.TabBarTop`now hides the tab bar on Android and iOS. This was working previously on beta.7.

```
const MainScreenNavigator = TabNavigator({

  Equipment: { screen: EquipmentScene },
  Settings: { screen: SettingsScene },

},{
  tabBarComponent: TabView.TabBarBottom,
  tabBarPosition: 'bottom',
  lazy: true,
});
```

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.9
| react-native     |  0.43.4
| node             | v7.8.0
| npm or yarn      | npm 4.5.0

**Comment by HilSny** [comment]
TabView.TabBarBottom is no longer supported (see here: https://github.com/react-community/react-navigation/releases under "static components are gone". 

You should import TabBarBottom directly from 'react-navigation' rather than getting it as a property of TabView.

**Comment by jarredszabadi** [comment]
Thank you! Didn't read the release notes thoroughly.

**Comment by HilSny** [comment]
No worries. I missed it too at first and then wondered why the TabBar wasn't showing up.
