### ISSUE TITLE
Regression: Bleeding shadow when using tabs in stacknavigator

### ISSUE THREAD

**Issue by koenpunt** [react-community/react-navigation#1288]
### Current Behavior

<img src="https://cloud.githubusercontent.com/assets/351038/25505245/400faf32-2ba1-11e7-9885-d77957d3e988.jpg" width="200" />

### Expected Behavior

<img src="https://cloud.githubusercontent.com/assets/351038/25505331/9447ec7c-2ba1-11e7-8ef2-b150f7eae542.png" width="200" />

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  beta 9
| react-native     |  0.43
| node             | 6.9.2
| npm or yarn      | yarn 0.23.2

**Comment by satya164** [comment]
Should be fixed by https://github.com/react-community/react-navigation/pull/1271

Can you check?

**Comment by satya164** [comment]
Though this makes me wonder, why doesn't stack navigator hide it's overflow.

**Comment by koenpunt** [comment]
Ah, missed that, couldn't find an issue relating the issue.
