### ISSUE TITLE
How to add a screen in StackNavigation?

### ISSUE THREAD

**Issue by firetheworld** [react-community/react-navigation#1289]
### Current Behavior
I have read doc but I can not find how to add a screen.
As I know you can use 
`
this.props.navigation.navigate('XXX');//XXX is some screen register when create stackNavigation
const ModalStack = StackNavigator({
    Home: {
        screen: SearchContent,
    },
`

### Expected Behavior
But I want to know how to  add screen,there seems no addScreen method?

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  
| react-native     |  
| node             | 
| npm or yarn      |

**Comment by koenpunt** [comment]
You should define all your screens on initialisation;

So 

```js
 const ModalStack = StackNavigator({
  Home: { screen: SearchContent, },
  XXX: { screen: XXXContent, },
});
```

But this is all explained in the docs: https://reactnavigation.org/docs/intro/#Adding-a-New-Screen

**Comment by Tom29** [comment]
@koenpunt So, if i want to have optional screens? Like multiple level category? If viewing at the first level, only one screen, but on the secondary level, it needs to have two screens. Fixed screens on initialization can't help.

**Comment by koenpunt** [comment]
Since you can navigate to the same screen multiple times, you could pass some params on navigating to differentiate between them.

```js
navigate('Generic', { component: MyCustomComponent })

// ...

const GenericScreen = ({ navigation }) => {
  const Component = navigation.state.params.component;
  return <Component navigation={navigation} />
}
```

**Comment by Tom29** [comment]
I've tried your way but `navigation.state.params.component` or `navigation.state.params` doesn't return anything

**Comment by Tom29** [comment]
@koenpunt I've tried your way but `navigation.state.params.component` or `navigation.state.params` doesn't return anything

**Comment by koenpunt** [comment]
@Tom29 I guess you missed something then. Have a look at this example: https://snack.expo.io/H13DWuSWb

**Comment by Tom29** [comment]
@koenpunt Actually this is not what i wanted.

If i don't use `navigate` , anyway to pass param to component?

On the parent file, i use `<Stack closeModal={() => this.refs.pickCategory.close()} />`

So on the Stack file, how do i get `closeModal` props?

**Comment by koenpunt** [comment]
@Tom29 I don't think your question is really related to react-navigation, but more of a general react-native question. 

If you explain your case in more detail in a question on [StackOverflow](https://stackoverflow.com/questions/ask) I'll have a look.

**Comment by Tom29** [comment]
@koenpunt https://stackoverflow.com/questions/44249833/react-native-how-do-i-pass-parameters-to-stacknavigator-component/44250444Here.
