### ISSUE TITLE
Linking addEventListener&removeEventListener has different callback function

### ISSUE THREAD

**Issue by jefferscn** [react-community/react-navigation#1292]
In [createNavigationContainer.js](https://github.com/react-community/react-navigation/blob/a14ac29c303094eddedc809a351ea421fdde993e/src/createNavigationContainer.js),
there are some codes related with [PlatformHelper](https://github.com/react-community/react-navigation/blob/a14ac29c303094eddedc809a351ea421fdde993e/src/PlatformHelpers.js)

```javascript
componentWillUnmount() {
      Linking.removeEventListener('url', this._handleOpenURL);
      this.subs && this.subs.remove();
    }
```
```javascript
componentDidMount() {
     ...
      Linking.addEventListener('url', ({ url }: { url: string }) => {
        this._handleOpenURL(url);
      });
     ...
    }
```

My problem is that,why addEventListener and removeEventListener have a different callback function;

In my project,I recode the implement of Linking to control the navigator route from external code;
Everything works fine. But removeEventListener pass a different callback function with addEventListener,
I cannot find the eventlistener callback function addEventListener passed in depend on the removeEventListener's.

**Comment by spencercarli** [comment]
@grabbou @skevy looks like you guys were the last to touch those pieces of code - any input on why it is like that?

**Comment by vonovak** [comment]
Closing, as this was fixed by PR https://github.com/react-community/react-navigation/pull/2235
