### ISSUE TITLE
How to make navbar background blur for iOS?

### ISSUE THREAD

**Issue by dfischer** [react-community/react-navigation#1294]
### Current Behavior

Solid background color

### Expected Behavior

Background iOS 9+ background blur like this -> 
![screen shot 2017-04-28 at 3 02 29 am](https://cloud.githubusercontent.com/assets/2424/25524369/221ca336-2bbf-11e7-911c-bc265463773d.png)

### Questions

Any tips on how, or if it's even possible to get that native blur affect?

**Comment by koenpunt** [comment]
Who's Jennifer? 

Just kidding, for this to work the header should be position _over_ the view, instead of above, and the child views should get passed a contentInset, preferably using `automaticallyAdjustContentInsets`. 

The next step would be introducing a library like [react-native-community/react-native-blur](https://github.com/react-native-community/react-native-blur) to actually display blurred content.

**Comment by dfischer** [comment]
Hi, thanks @koenpunt!

Sorry new to react-native. How do you position something over? Would it be `zIndex`?

**Comment by koenpunt** [comment]
I'd not recommend zindex. If you position the views absolute, they will layer in order.

So the following will make the header end on top of the content:

```js
<Content/>
<Header/>
```

This is already how it's done currently, as can be seen here: https://github.com/react-community/react-navigation/blob/master/src/views/CardStack.js#L361

Difference is that there it uses relative positioning.

**Comment by wellyshen** [comment]
Will this feature be included in this library?

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!

**Comment by VictorHCord** [comment]
any solution to this problem?
