### ISSUE TITLE
Animation when navigating between header and no-header cards (iOS)

### ISSUE THREAD

**Issue by lprhodes** [react-community/react-navigation#1295]
I'm creating this issue so that there can be a discussion about how best to make native feeling animations when navigating between different views/cards in the stack when one view has a header and the other does not.

Android is simple as it works well with the existing `headerMode: 'screen'`

iOS requires more finesse:

**no-header to no-header & header to no-header (push, swipe back and pop)**
These are simple as you can just use `headerMode: 'screen'` for the transition.

**no-header to header (push)**
The header should transition inside the card (screen) and then move outside the card (float) once the transition has completed so that it's ready to perform float animations.

**no-header to header (pop)**
The swipe gesture will need to swap the header from being outside (float) to inside (screen) the card immediately.

**no-header to header (swipe back)**
The same as pop (though this should happen when the user starts the pan gesture). It must revert if the action is cancelled.

So essentially we need to be able to position the header inside or outside the card depending on the previous (not parent) card.

In order to achieve this without a major restructure of code, the CardStack must be aware of what the previous (and next when an animation is starting) cards are in the stack.

It must also know when the animation is starting or ending.

It'd be great to get your thoughts on this before I work any further on it.

Thanks!

**Comment by ms88privat** [comment]
I like that. I could archive the same with react-native-router-flux some time ago. I believe I can also do it with react-navigation if we use two StackNavigators, right?

I didn't understand the discussion about animating in/out. For me there is no "animation" involved here. The header will just move with the card movement, like you described.

**Comment by lprhodes** [comment]
@ms88privat In android you expect a card movement but in iOS you can need both card movement (when moving from no-header to no-header or no-header to header) as well as animations in the header (when moving from header to header)

I'm almost finished with this:
![galp7nou2eda8](https://cloud.githubusercontent.com/assets/162989/25556730/400036c4-2d45-11e7-9ac7-c678ec653888.gif)

**Comment by ms88privat** [comment]
@lprhodes of course, I only talked about the navigation between no-header / header screens

**Comment by FullstackJack** [comment]
Yes, this is a necessary fix to avoid header jitter. Let's fix the conflicts in the PR and merge.

**Comment by lprhodes** [comment]
I've been using this without issues.

I plan on adding the ability to slide over tab bars rather than having them just disappear instantly when you push a view without the tab bar.

That should then complete the animation amends.

**Comment by ixje** [comment]
@lprhodes have you made any progress on the 'slide over tabs'? It sounds exactly like what I was about to file an issue for, so I'm very curious to see if you made any progress.

I don't know how the transitions work, but would that also fix the following?
When using gestures to go back from a screen with no header/custom header to a screen with a default header  you can see the content animating in with a fade, but only on the last frame (it seems) the header becomes visible. 
![transition](https://fat.gfycat.com/EnlightenedOffensiveBinturong.gif)

This doesn't happen when you swipe back from a screen with the default header to a screen that also has the default header.

**Comment by lprhodes** [comment]
No I spent a fair bit of time working trying to get it working but react-navigator really isn't implemented in a way to make it achievable without significant changes.

My plan is to do something with fake tab bar images so that when it disappears the fake one appears in its place.

**Comment by ixje** [comment]
That's unfortunate, but thanks for the effort! Let's hope the issue gets some tractions over time when more people start using custom headers and don't accept the jitter/flickering much longer :)

**Comment by kelset** [comment]
Pinging OP @lprhodes since this issue is quite old and related to an old version of the lib. If no answer I'll close in 7 days.

**Comment by kelset** [comment]
Hi there @lprhodes,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue (especially if it's a bug report) please open a new issue that uses the new Issue Template to provide some more details to help us solve it. (that said, I think there's already a newer report of this at #2732)

**Comment by nicoara** [comment]
I moved to react-native-navigation due to the lack of solution for this.

**Comment by brentvatne** [comment]
this is fixed in 2.0
