### ISSUE TITLE
StackNavigator navigationOptions header error. Objects are not valid as a React child...

### ISSUE THREAD

**Issue by FreddieOD** [react-community/react-navigation#1296]
Hi,

Perhaps someone can help me here. I have the following StackNavigator:

```
export default AppNavigator = StackNavigator({
  LoginScreen: {
    screen: LoginScreen,
    navigationOptions:{
      header: ({navigation}) => ({
          left: (<Image source={require('../resources/independent-logo.png')} style={styles.logo}/>),
          style: {backgroundColor: colours.iolRed, elevation: null},
          title:null
      }),
    }
  }
});
```
### Current Behavior
After updating my react native node modules (see versions below) I receive this error. Worked perfectly fine before reinstalling my npm packages which leads me to:

![screenshot_20170428-135553](https://cloud.githubusercontent.com/assets/10277983/25528664/317e57ec-2c1f-11e7-9aba-6fda1d4a4942.png)

### Expected Behavior
As per the examples [here](https://github.com/react-community/react-navigation/blob/master/examples/NavigationPlayground/js/StacksOverTabs.js) line 119 my syntax seems to be correct.

### My Environment

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta7
| react-native     |  0.42.0
| node             | v6.0.0
| npm      | 3.8.6

**Comment by nimishrocks** [comment]
Having the same problem, any fixes?

**Comment by FreddieOD** [comment]
As a further diagnostic clue I have come to realise that the problem lies in 

```
navigationOptions:{
    header: {
       <key>: <value>,
    },
  },
```

This throws the same error. I hope this is not a red herring but removing header as an object seems remove the error. I am going to be trying a few things. Will post updates.

**Comment by nimishrocks** [comment]
use createFragmenet from react-addons-create-fragment package (https://www.npmjs.com/package/react-addons-create-fragment) to enclose the header options
Check this (https://facebook.github.io/react/docs/create-fragment.html)

**Comment by FreddieOD** [comment]
Yes this worked for me. However, adding a style to this seems to be a problem. Anything that is a child object to that returns the same error. for example:
```
export default AppNavigator = StackNavigator({
  LoginScreen: {screen: LoginScreen},
  FrontPageNavigator: {screen: FrontPageNavigator},
},{
    navigationOptions:{
      header: (navigation) => createFragment({
          left: (<Image source={require('../resources/independent-logo.png')} style={styles.logo}/>),
          style: {backgroundColor: colours.iolRed, elevation: null},
          title: null
      }),
    },

  }
);

```

returns the same error. Removing the style it works just fine but obviously it is unstyled. The other issue is that it seems that the header is entirely custom whereas before it was easier to simply style the header as is.

**Comment by nimishrocks** [comment]
use createFragment at every place where there is a key value mapping , until the bug is resolved, 
i.e
use createFragment in style also, it will help you to customize the header

**Comment by koenpunt** [comment]
The navigation options have been refactored quite a bit.

The `header` property is now available to specify a custom header component:

E.g.

```js
export default AppNavigator = StackNavigator({
  LoginScreen: {screen: LoginScreen},
  FrontPageNavigator: {screen: FrontPageNavigator},
} , {
  navigationOptions: {
    header: props => <CustomHeader {...props} />,
  },
});
```

The customisation you want can be accomplished using the new options:

```js
export default AppNavigator = StackNavigator({
  LoginScreen: {screen: LoginScreen},
  FrontPageNavigator: {screen: FrontPageNavigator},
} , {
  navigationOptions: {
    title: null
    headerLeft: (<Image source={require('../resources/independent-logo.png')} style={styles.logo}/>),
    headerStyle: {backgroundColor: colours.iolRed, elevation: null},
  },
});
```

All the changes are documented here: https://github.com/react-community/react-navigation/releases/tag/v1.0.0-beta.9

**Comment by FreddieOD** [comment]
Thank you

**Comment by FreddieOD** [comment]
Interestingly, though, this is still a problem on beta.7?

**Comment by koenpunt** [comment]
> Interestingly, though, this is still a problem on beta.7?

Are you sure you were still on beta.7?

**Comment by FreddieOD** [comment]
I suppose I am not sure now. Thanks for your help. That link of yours helped me a lot. A nice go-to for the future.

**Comment by FreddieOD** [comment]
ok so I dont know how to make 100% I am in beta.7 other than looking in my node_modules/react-navigation package.json which is:

```
{
  "_args": [
    [
      "react-navigation@1.0.0-beta.7",
      "/home/freddie/git/react/adchecker"
    ]
  ],
  "_from": "react-navigation@1.0.0-beta.7",
  "_id": "react-navigation@1.0.0-beta.7",
  "_inCache": true,
  "_installable": true,
  "_location": "/react-navigation",
  "_nodeVersion": "7.7.1",
  "_npmOperationalInternal": {
    "host": "packages-18-east.internal.npmjs.com",
    "tmp": "tmp/react-navigation-1.0.0-beta.7.tgz_1489217328973_0.492629730142653"
  },
  "_npmUser": {
    "email": "satyajit.happy@gmail.com",
    "name": "satya164"
  },
  "_npmVersion": "4.1.2",
  "_phantomChildren": {},
  "_requested": {
    "name": "react-navigation",
    "raw": "react-navigation@1.0.0-beta.7",
    "rawSpec": "1.0.0-beta.7",
    "scope": null,
    "spec": "1.0.0-beta.7",
    "type": "version"
  },
```

This looks an awful lot like a beta.7 navigation.

**Comment by koenpunt** [comment]
Strange, because if you look at the source of the Header component in that version, the header is nowhere used as a component:

**Comment by FreddieOD** [comment]
Hi. Thanks for your time. So the problem I had was that when I looked in my node modules I got beta.7. Excerpt from node_modules/react-navigation package.json: 

```{
  "_args": [
    [
      "react-navigation@1.0.0-beta.7",
      "/home/freddie/git/react/adchecker"
    ]
  ],
  "_from": "react-navigation@1.0.0-beta.7",
  "_id": "react-navigation@1.0.0-beta.7",
  "_inCache": true,
  "_installable": true,
  "_location": "/react-navigation",
  "_nodeVersion": "7.7.1",
  "_npmOperationalInternal": {
    "host": "packages-18-east.internal.npmjs.com",
    "tmp": "tmp/react-navigation-1.0.0-beta.7.tgz_1489217328973_0.492629730142653"
  },
  "_npmUser": {
    "email": "satyajit.happy@gmail.com",
    "name": "satya164"
  },
  "_npmVersion": "4.1.2",
  "_phantomChildren": {},
  "_requested": {
    "name": "react-navigation",
    "raw": "react-navigation@1.0.0-beta.7",
    "rawSpec": "1.0.0-beta.7",
    "scope": null,
    "spec": "1.0.0-beta.7",
    "type": "version"
  },```

Restarting node modules didn't work. Then I read about the the npm server caching the dependencies and rm -rf $TMPDIR/react-* with an npm server restart sorted it out. It seems version 9 must have still been looming around. Very sorry and I hope this helps someone in the future.

Thanks again for your time and patience. And thanks for that changes log! I looked everywhere for that!

**Comment by koenpunt** [comment]
Ah well yeah, happens to me sometimes as well. But once your swapping versions more, it becomes common practice to more often start the packager with the `--reset-cache` flag;

```
yarn start -- --reset-cache
```

Glad to be of help!

**Comment by zainulabidin302** [comment]
from https://github.com/react-navigation/react-navigation/releases/tag/v1.0.0-beta.9 

`header.visible` is now `header: null`
