### ISSUE TITLE
After upgrading to 1.0.0-beta9, I get a screen shadow on the right side of screen after switching tabs.

### ISSUE THREAD

**Issue by joonhocho** [react-community/react-navigation#1299]
### Current Behavior
After upgrading to 1.0.0-beta.9, I get a screen shadow on the right side of screen after switching tabs.
I am using tab navigator -> nested stack navigators.

![simulator screen shot apr 28 2017 10 48 08 am](https://cloud.githubusercontent.com/assets/930795/25540616/96fecba2-2c00-11e7-8a52-57d5d82bb30a.png)

### Expected Behavior
There should be no shadow visible after switching tabs.

### Your Environment
MacOS
iOS simulator
react-native 0.43.0
react-navigation 1.0.0-beta.9

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.9
| react-native     |  0.43.0
| node             | 7.7.4
| npm or yarn      | 4.1.2

**Comment by joonhocho** [comment]
![simulator screen shot apr 28 2017 10 48 08 am](https://cloud.githubusercontent.com/assets/930795/25540604/88bad770-2c00-11e7-9fa3-8792f7cf9607.png)

**Comment by manuelprojects** [comment]
Same here ...

**Comment by vjeranc** [comment]
#1288

**Comment by eflath** [comment]
definitely not fixed by those commits
