### ISSUE TITLE
Support React Elements as header title

### ISSUE THREAD

**Issue by satya164** [react-community/react-navigation#13]
People will want to use images, custom fonts etc for the title. So we should allow react elements too

```js
static navigationOptions = {
  header: {
    title: React.Element<*>
  }
}
```

**Comment by grabbou** [comment]
We support both as far as I am not wrong. 

https://github.com/react-community/react-navigation/blob/master/src/TypeDefinition.js#L103

**Comment by satya164** [comment]
Oh, didn't realize that.

**Comment by kennydee** [comment]
@grabbou oh so there is a small mistakes in the doc : 
`All navigationOptions for the StackNavigator:
title - a title (string) displayed in the header`
:)

Thanks :)

**Comment by kennydee** [comment]
@grabbou @satya164 i think this is not the case, see the issue i just create #272 :)
