### ISSUE TITLE
Header title as image centered

### ISSUE THREAD

**Issue by augustoabreu** [react-community/react-navigation#1302]
### Expected Behavior
Hi, i'm trying to change header title to image and let it centered. I've seen a lot of ways to center the title and to made it a image, but always in separated implementations. None has helped me to acomplish my result, can anyone help me?

I've tried to use navigationOptions with headerTitle, headerTitleStyle, style.header.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  git
| react-native     |  0.43.3
| node             | 6.10.1
| npm or yarn      | 3.10

**Comment by koenpunt** [comment]
The title component will be centered automatically, so no matter what you put in there it should always become centered.

Something like this should work:

```js
navigationOptions: {
    headerTitle: (
      <Image source={require('./some/image.png')}/>
    ),
}
```

**Comment by augustoabreu** [comment]
@koenpunt this code will change my heade title to an image, but on Android title are left aligned. what can i do?

**Comment by koenpunt** [comment]
If you add `alignSelf: 'center'` to the styles it should work.

**Comment by laclance** [comment]
`alignSelf: 'center'` only works if there is just a title. For example, if there is a back button then title gets shifted to the right.

**Comment by tavriaforever** [comment]
I want to add that style must be apply to Image component not by headerTitleStyle

```
navigationOptions: {
  headerTitle: (
      <Image style={{ width: 90, height: 39 }} source={require('./some/image.png')}/>
  ),
headerTitleStyle: ...this styles won`t apply to image in header title, maybe it`s bug, but this is real
```

**Comment by tstrohmeier** [comment]
@tavriaforever It seems that the styles are not passed to the Image component. I just simple created a styled HeaderImage component. 

```javascript
navigationOptions: {
  headerTitle: (
      <HeaderImage/>
  ),
```

**Comment by oscarjg** [comment]
@tavriaforever Can you write some snippet with your code? I can't find any solution for this in my code

**Comment by tavriaforever** [comment]
this works in my project 

![atlantm 2018-01-11 18-11-13](https://user-images.githubusercontent.com/975906/34832480-287914fa-f6fb-11e7-8f63-d9337bad99d6.png)

result

![iphone 6 - ios 8 1 2018-01-11 18-14-07](https://user-images.githubusercontent.com/975906/34832502-3d8bf902-f6fb-11e7-9266-d9f66ea150b2.png)

**Comment by oscarjg** [comment]
@tavriaforever Thanks! With ios works fine the problem is with Android. If any left or right element like back button is displaying the header title block is moved to the right or left. I think I have to create a whole custom header or play with the side elements on every screen. What do you think?

**Comment by caltv** [comment]
@oscarjg  Im seeing something similar, images on the right of left of the title cannot be "moved in", once they do they disappear behind the header background, has anyone found a way around this?

`headerLeft: (
      <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center', }}>
        <Image
          style={styles.imageForHomeHeader}
          source={require('../img/home.png')}
        />
      </View>
    ),`

**Comment by gregblass** [comment]
@oscarjg I'm experiencing the same issue. Did you ever find a working solution?

**Comment by viktorbk** [comment]
This works to center text:
            headerTitle: (
                <View style={{
                    flex: 1,
                    flexDirection: 'row'
                }}>
                    <Text style={{
                        flex:1,
                        fontSize: 18, 
                        fontWeight: '700', 
                        color: '#53799d', 
                        textAlign:'center'
                        }}>
                             YourTitle
                    </Text>
                </View>
            ),

**Comment by oscarjg** [comment]
@gregblass The only solution is implementing your custom header managing everything by yourself. That's the only way that I found so far.

**Comment by yoavapi** [comment]
Same issue in Android 👎

**Comment by Danishkhan007** [comment]
@oscarjg ... I was facing the same issue... Finally I got the solution: just replace <Title> with <View> inside the body:
Here is my code I am using NativeBase header component.

   // -------------- setting the header----------------//
        <Header
            androidStatusBarColor={PRIMARY_DARK_COLOR}
            iosBarStyle={Platform.OS === "ios" ? "dark-content" : "light-content"}
            style={headerStyle}
        >
            {/*-------------Left icon -------------------*/}
            <Left style={{flex: 1}}>
                <Button transparent onPress={() => navigation.navigate("DrawerOpen")}>
                    <Icon name={leftIcon} style={iconStyle} />
                </Button>
            </Left>
            <Body style={{flex: 1}} >
                {/*-------------Center title image-------------------*/}
                <View style={{alignSelf: 'center', flex: 1}}>
                    <Image
                         resizeMode="cover"
                         style={{
                            width: 120,
                            height: 50,
                            resizeMode:'contain',
                        }}
                        source={centerImage}
                    />
                </View>
            </Body>
            {/*-------------Right icon -------------------*/}
            <Right style={{flex: 1}}>
                <LangContextMenu/>
                {/* <Button transparent onPress={contextMenu}>
                    <Text style={textStyle}> English </Text>
                    <Image source={rightIcon} style={{ height: 20, width: 10 }} />
                </Button> */}
            </Right>
    </Header>

Please find the shared screen below:
![screen shot 2018-05-14 at 1 41 27 pm](
https://user-images.githubusercontent.com/20835099/39985549-9525c904-577c-11e8-9461-bbcdf24f5999.png)

**Comment by leo7r** [comment]
I manage to solve this issue with the following:

```
headerTitle: (
    <View style={{flex:1, flexDirection:'row', justifyContent:'center'}}>
        <Image
            source={image}
            style={{width:110, height:18}}
        />
    </View>
),
```
And it works with or without left & right icons :)

**Comment by ThisaraGitHub** [comment]
this is how i solve the issue 
import platform from react native and inside your headerTitleStyle try something like this 
marginLeft: Platform.OS === "android" ? "50%" : "0%"

**Comment by servatti** [comment]
I had the back button on the left and an image as title so to get the image centered I just added an empty view to the right:
```
{
  headerTitle: <Image ... />,
  headerRight: <View></View>,
}
```

**Comment by brentvatne** [comment]
`headerLayoutPreset: 'center'`

https://reactnavigation.org/docs/en/stack-navigator.html#stacknavigatorconfig

**Comment by lukewlms** [comment]
FYI all, the new property for this in version 5.0 is `headerTitleAlign`:

https://reactnavigation.org/docs/stack-navigator/#headertitlealign

**Comment by joaomuribeca** [comment]
> FYI all, the new property for this in version 5.0 is `headerTitleAlign`:
> 
> https://reactnavigation.org/docs/stack-navigator/#headertitlealign

Omg thank you man

**Comment by Govindraj93** [comment]
how to add the stack navigation with option at a time title and image in header how it possible in header
