### ISSUE TITLE
Get initial route from nested navigators for custom navigation store

### ISSUE THREAD

**Issue by svicalifornia** [react-community/react-navigation#1304]
### Current Behavior

I have a deeply nested navigator structure:

    (Modal) Stack Navigator
      Drawer Navigator (which React Navigation has implemented as two nested Tab Navigators)
        Stack Navigator
          Screen A
          …
        Stack Navigator
          Screen B
          …
      Modal X

I'm supplying my own navigation to the root navigator, with a pruned initial state that doesn't include any routes for the inactive "tabs" of the DrawerNavigator:

      // Root navigator is a ModalNavigator
      {
        index: 0,
        routes: [
          { key: 'DrawerNavigator', routeName: 'DrawerNavigator', index: 0, routes: [
            { key: 'DrawerClose', routeName: 'DrawerClose', index: 0, routes: [
              { key: 'StackNavigator', routeName: 'StackNavigator', index: 0, routes: [
                { key: 'Splash', routeName: 'Splash' },
              ]},
            ]},
          ]},
        ],
      };

When I try to navigate from `Welcome` to a modal screen (in the root), `getStateForAction` first looks in the children of `Welcome` (there aren't any), then the other tabs of the `StackNavigator` (finding nothing there either), and then moves up to the TabNavigator created for the drawer. If tries to go to the second tab, and that tab is not in my state routes, so the lookup fails.

I realize that I'm not supplying a full initial state, but Navigation has handled my simpler pruned version until now. Even hard-coding this much state is prone to breakage as the navigators will likely be restructured over time, and hard-coding a full and complete state for every single node in the navigator tree seems ridiculously redundant.

### Expected Behavior

1. Would be great if Navigation would check whether the tab route exists in the current state, and if not, creates a default route for that tab based on `initialRouteName`, before attempting to traverse down that tab.

2. I would also love to have a function that I call on my RootNavigator (or pass a navigator to) and get back a deeply nested state object representing the initial state based on `initialRouteName`s throughout the nested navigator config. Then I could use that instead of hard-coding the initial state, have even less duplicated code, easily adapt to changes in the navigator configs, and totally avoid the issue described here resulting from an incomplete hard-coded initial state.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta9
| react-native     |  0.43.4
| node             | v7.9.0
| npm or yarn      |  4.2.0

**Comment by svicalifornia** [comment]
The docs for [Redux Integration](https://reactnavigation.org/docs/guides/redux) propose this:

    const initialState = AppNavigator.router.getStateForAction(AppNavigator.router.getActionForPathAndParams('Login'));

Adapting this to my nested navigators, I have:

    const splashState = RootNavigator.router.getStateForAction(RootNavigator.router.getActionForPathAndParams('Main/DrawerClose/WelcomeNavigator/Splash'));

That returns the following nested action object:

    {
      "index": 0,
      "routes": [{
        "routeName": "Main",
        "action": {
          "type": "Navigation/NAVIGATE",
          "routeName": "DrawerClose",
          "action": {
            "type": "Navigation/NAVIGATE",
            "routeName": "WelcomeNavigator",
            "action": {
              "type": "Navigation/NAVIGATE",
              "routeName": "Splash"
            }
          }
        },
        "key": "Init"
      }]
    }

However, when I use that as my initial state, I get the following error:

> Expect nav state to have routes and index, undefined> 
>
> Object.getScreenOptions
>     createConfigGetter.js:68:8
> CardStack._this._getScreenDetails
>     CardStack.js:157:24
> CardStack._renderHeader
>     CardStack.js:168:28
> CardStack.proxiedMethod
>     createPrototypeProxy.js:44:29
> CardStack.render
>     CardStack.js:241:28
> CardStack.proxiedMethod
>     createPrototypeProxy.js:44:29
> <unknown>
>     ReactCompositeComponent.js:1207:19
> measureLifeCyclePerf
>     ReactCompositeComponent.js:64:11
> ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext
>     ReactCompositeComponent.js:1206:24

**Comment by svicalifornia** [comment]
Solved: Instead of setting the state directly on your Redux/MobX navigation store object, leave its state undefined (or null), and then do this from your root component:

    const navigation = addNavigationHelpers({
      dispatch: this.navigationStore.dispatch,
      state: this.navigationStore.state,
    });
    navigation.dispatch(NavigationActions.init());

The `init` action will create a state that is set to all of the `initialRouteName`s in your nested navigator hierarchy.

The Redux docs page should be updated to promote this technique rather than setting state explicitly from getStateForAction/getActionForPathAndParams (which doesn't return valid initial state for nested navigators).

**Comment by cooperka** [comment]
@svicalifornia I think this may be a dupe, solved in this comment: https://github.com/react-community/react-navigation/issues/937#issuecomment-297166585

I simply used `NavigationActions.navigate({ routeName: 'Main' });` to generate my initial state instead of changing where the initial state generation happened. Hopefully that works for you too. We should still update the redux docs to demonstrate this.

**Comment by cityvoice** [comment]
If you use nested navigators integerated with redux, try change the code 

`const initialState = AppNavigator.router.getStateForAction(AppNavigator.router.getActionForPathAndParams('Main'));`

to 

```
import MainScreenNavigator from './MainTab';
import ArticleDetailScreen from '../containers/ArticleDetailScreen';
const initialNavState=AppNavigator.router.getStateForAction(NavigationActions.reset({
	index: 0,
	actions: [
	  NavigationActions.navigate({
		routeName: 'Main',
	  }),
	],
}))
```

It works for me, but I don't know why, below is my nested navigators
**AppNavigation.js**
```
export const AppNavigator = StackNavigator({
  Main: { screen: MainScreenNavigator},
  ArticleDetail: 
	{
		screen: ArticleDetailScreen,
		navigationOptions: ({navigation}) => ({
			title: `${navigation.state.params.title} detail`,
		})
	},
},{initialRouteName:'Main'});
```
**MainTab.js**
```
const MainTab = TabNavigator({
  Home: {
    screen: MainScreen,
  },
  Discovery: {
    screen: DiscoveryScreen,
  },
  ...
}, 	  
  {
	tabBarPosition :'bottom',
	initialRouteName:'Home',
       ...
  })
```
hope to help you!

**Comment by seantempesta** [comment]
Thanks @cityvoice!  Your solution worked for me!

**Comment by kelset** [comment]
Pinging OP @svicalifornia since this issue is quite old and related to an old version of the lib. If no answer I'll close in 7 days.

Moreover, solution proposed by @cityvoice seems to work.

**Comment by svicalifornia** [comment]
Hey everyone, I'm here. Please give me a day or two to update my libs and test it again. I'll report back by Sunday night.

**Comment by svicalifornia** [comment]
The main issue I see with the comments above from @cooperka and @cityvoice is that they do not make use of the `initialRouteName` properties of the navigator tree.

Sure, there are ways to force navigation to some state with `navigate`. But we shouldn't have to do that, since `initialRouteName` is supposed to do that for us. That is precisely its purpose, to set the default route for each navigator.

So I think my recommendation above is still the best way to make use of the `initialRouteName` settings:

    const navigation = addNavigationHelpers({
      dispatch: this.navigationStore.dispatch,
      state: this.navigationStore.state,
    });
    navigation.dispatch(NavigationActions.init());

**Comment by haseebnaseem** [comment]
I have not been able to generate the state correctly using either from @dchersey's method or from the the one mentioned in the docs. 
This is how my navigators are defined:
```
const HomeNav = TabNavigator({
    feed:{screen:Feed},
    restaurantScreen:{screen:Restaurant},
},{
    tabBarComponent:NavigationComponent,
    tabBarPosition:'bottom',
    tabBarOptions:{
        bottomNavigationOptions:{
            labelColor:'white',
            rippleColor:'white',
            tabs:{
                feed:{
                    barBackgroundColor:'#37474F',
                },
                restaurantScreen:{
                    barBackgroundColor:'#00796B',
                }
            }
        }
    }
});
export const Navigator=StackNavigator(
    {
        HomeScreen:{screen:Home},
        VerifyScreen:{screen:Verify},
        newUserScreen1:{screen:newUser1},
        newUserScreen2:{screen:newUser2},
        loginScreen:{screen:login},
        feedScreen:{screen:HomeNav},
    },
    {
        headerMode:'none',
    },
);
```
and this is how I am trying to set the initial state and navigate:
```
const initialState=Navigator.router.getStateForAction(
    NavigationActions.init()
);

function navigate(screenName,state){
    return Navigator.router.getStateForAction(NavigationActions.navigate({routeName:screenName},state));
}
```
The following error comes up when navigating from Home screen to the feed Navigator:
```
Expect nav state to have routes and index, {"routeName":"feedScreen","key":"Init-id-1510393473667-1"}
```

**Comment by kelset** [comment]
Ok, then I'm gonna close this. Thanks for the feedback @svicalifornia.

**Comment by rivkabar** [comment]
hi

**Comment by rivkabar** [comment]
Hi, 
i new in react-native. i tried to adding stackNavigator nested in  TabNavigator..
but i got  TypeError: Cannot read property 'screen' of undefined.
a copy several files.  please assist.

AppContainer
import React ,{Component} from 'react';
import { AppRegistry,StyleSheet,Text,View} from 'react-native';
import { Nav, Tab } from 'react-native-simple-tab';
import { TabkNavigator } from 'react-navigation';
import PushPayload from './PushPayload';
import Feed from './Feed';
import TabNavigator from './TabNavigator'

export default class AppContainer extends Component {
    constructor(props) {
      debugger;
      super(props);
      this.state = {
        page: 0,
      };
   
      this._onTabChange = this._onTabChange.bind(this);
    }
   
    _onTabChange(tabIndex) {
      this.setState({ page: tabIndex });
    }

    render() {
      debugger;
      return (       
        <View style={styles.container}>
          <View style={{ flex: 1 }}>
            <TabNavigator navigation={this.props.navigation}/>
          </View>
        </View>
      );
    }
  }
TanNavigator
import React from 'react';
import { TabNavigator } from 'react-navigation';
import { Icon } from 'react-native-elements';
import FeedNavigatior from './FeedNavigator';
import SearchNavigator from './SearchNavigator';
debugger;
 const Tabs = TabNavigator({
  Feed: {
    screen: FeedNavigatior,
    navigationOptions: {
      tabBarLabel: 'Feed',
      tabBarIcon: ({ tintColor }) => <Icon name="list" size={35} color={tintColor} />,
     
    },
  },
  Search: {
    screen: SearchNavigator,
    navigationOptions: {
      tabBarLabel: 'Search',
      tabBarIcon: ({ tintColor }) => <Icon name="search" size={35} color={tintColor} />
    },
  }
},{
  initialRoutName:'Feed'
}

);
export default TabNavigator;

SearchNavigator
import React from 'react';
import { View, Text } from 'react-native';
import { StackNavigator } from 'react-navigation';
import SearchResults from './SearchResults';
import Search from './Search';
const SearchNavigator = StackNavigator({
    Home: {
      screen: Search,
      initialRoutName:{screen: Search},
    },
    Details: {    
      screen: SearchResults,
    },   
  });
  
  export default SearchNavigator;

FeedNavigator

import React from 'react';
import { View, Text } from 'react-native';
import { StackNavigator } from 'react-navigation';
import Feed from './Feed';
import PushPayload from './PushPayload'
const FeedNavigator = StackNavigator({
    Home: {
      screen: Feed,
      initialRoutName:{screen: Feed},
    },
    Details: {
      
      screen: PushPayload,
    },
    
  });
  
  export default FeedNavigator;

Feed
'use strict';
import React ,{Component} from 'react';
import { AppRegistry,StyleSheet,Text,View,ListView,ActivityIndicator,Image,TouchableHighlight} from 'react-native';
import PushPayload from './PushPayload';
var moment = require('moment');

export default class Feed extends Component {
    constructor(props){
        super(props);
        this.props.navigation.state.params={};
        var ds = new ListView.DataSource({
            rowHasChanged: (r1, r2) => r1 != r2
        });

        this.state = {
            dataSource: ds,
            showProgress: true
        };
        
    }

    componentDidMount(){
        this.fetchFeed();
    }

    fetchFeed(){
        require('./AuthService').getAuthInfo((err, authInfo)=> {
            var errorCtrl = <View />;
            if(err)
            {
                console.log('err fetchFeed: '+err)
                if(!this.state.success && this.state.badCredentials){

                    errorCtrl = <Text style={styles.error}>
                        {err}
                    </Text>;
                    return errorCtrl;
                }
                
            }
            var url = 'https://api.github.com/users/'
                + authInfo.user.login
                +'/events';
                // + '/received_events';
            console.log('url: '+url);
            debugger;
            fetch(url, {
                headers: authInfo.header
            })
            .then((response)=> response.json(),(reson)=>console.log('fetch reson: '+reson))
            .then((responseData)=> {
                if(responseData.length==0)
                {
                    console.log('function fetch responseData ia null!');
                }
                var feedItems =
                    responseData.filter((ev)=>
                        ev.type == 'PushEvent');
                this.setState({
                    dataSource: this.state.dataSource
                        .cloneWithRows(feedItems),
                    showProgress: false
                });
            })
        });
    }

    renderRow(rowData){
        debugger;
        const { navigate } = this.props.navigation;  
        return (
            <TouchableHighlight
                onPress= {() => 
                {navigate('Details',{
                    type:"Navigate",
                    routName:"Details",
                    params:{pushEvent:rowData}
                });
                }}
                underlayColor='#ddd'
            >
                <View style={{
                    flex: 1,
                    flexDirection: 'row',
                    padding: 20,
                    alignItems: 'center',
                    borderColor: '#D7D7D7',
                    borderBottomWidth: 1,
                    backgroundColor: '#fff'
                }}>
                    <Image
                        source={{uri: rowData.actor.avatar_url}}
                        style={{
                            height: 36,
                            width: 36,
                            borderRadius: 18
                        }}
                    />

                    <View style={{
                        paddingLeft: 20
                    }}>
                        <Text>
                            {moment(rowData.created_at).fromNow()}
                        </Text>
                        <Text>
                            <Text style={{
                                fontWeight: '600'
                            }}>{rowData.actor.login}</Text> pushed to
                        </Text>
                        <Text>
                            {rowData.payload.ref.replace('refs/heads/', '')}
                        </Text>
                        <Text>
                            at <Text style={{
                                fontWeight: '600'
                            }}>{rowData.repo.name}</Text>
                        </Text>
                    </View>
                </View>
            </TouchableHighlight>
        );
    }
    render(){
       
      if(this.state.showProgress){
        return (
            <View style={{
                flex: 1,
                justifyContent: 'center'
            }}>
                <ActivityIndicator
                    size="large"
                    animating={true} />
            </View>
        );
      }

      return (
        <View style={{
            flex: 1,
            justifyContent: 'flex-start'
        }}>
            <ListView
            
                dataSource={this.state.dataSource}
                renderRow={this.renderRow.bind(this)} enableEmptySections = {true} />
        </View>
      );
    }
}
AppRegistry.registerComponent('Feed', () => Feed);

PushPayload 
import { AppRegistry,StyleSheet,Text,View,ListView,Image,} from 'react-native';
import React ,{Component} from 'react';
'use strict';
var moment = require('moment');
export default class PushPayload extends Component {
    constructor(props){
        debugger;
        super(props);

        var ds = new ListView.DataSource({
            rowHasChanged: (r1, r2) => r1 != r2
        });
        const { navigate } = this.props.navigation;
        const {params} = this.props.navigation.state;
        console.log('params : '+params);
        this.state = {          
            dataSource: ds.cloneWithRows(params.params.pushEvent.payload.commits),
            pushEvent: params.params.pushEvent
        };
    }
    
    renderRow(rowData){
        debugger;
        console.log('this.state.pushEvent.sha : '+rowData.sha)
        var text= rowData.sha.substring(0, 6);
        
        return(

            <View style={{
                flex: 1,
                justifyContent: 'center',
                borderColor: '#D7D7D7',
                borderBottomWidth: 1,
                paddingTop: 20,
                paddingBottom: 20,
                padding: 10
            }}>           
                <Text><Text style={styles.bold}>{text}</Text> - {rowData.message}</Text>
            </View>
        );
    }

    render(){
        debugger;
        
        return (
            <View style={{
                flex: 1,
                paddingTop: 80,
                justifyContent: 'flex-start',
                alignItems: 'center'
            }}>
                <Image
                    source={{uri: this.state.pushEvent.actor.avatar_url}}
                    style={{
                        height: 120,
                        width: 120,
                        borderRadius: 60
                    }}
                />

                <Text style={{
                    paddingTop: 20,
                    paddingBottom: 20,
                    fontSize: 20
                }}>
                    {moment(this.state.pushEvent.created_at).fromNow()}
                </Text>

                <Text><Text style={styles.bold}>{this.state.pushEvent.actor.login}</Text> pushed to</Text>
                <Text><Text style={styles.bold}>{this.state.pushEvent.payload.ref.replace('refs/heads/', '')}</Text></Text>
                <Text>at <Text style={styles.bold}>{this.state.pushEvent.repo.name}</Text></Text>

                <Text style={{
                    paddingTop: 40,
                    fontSize: 20
                }}>
                    {this.state.pushEvent.payload.commits.length} Commits
                </Text>

                <ListView
                    contentInset={{
                        top: -50
                    }}
                    dataSource={this.state.dataSource}
                    renderRow={this.renderRow.bind(this)} />
            </View>
        );
    }
}

var styles = StyleSheet.create({
    bold: {
        fontWeight: '800',
        fontSize: 16
    }
});
AppRegistry.registerComponent('PushPayload', () => PushPayload);


Search
'use strict';

import {
    Text,
    View,
    TextInput,
    TouchableHighlight,
    AppRegistry,
    StyleSheet
} 
from 'react-native';
import React ,{Component} from 'react';
import SearchResults from './SearchResults';

export default class Search extends Component {
    constructor(props){
        super(props);
        this.props.navigation.state.params={};
        this.state = {
        }
    }

    render(){

        return (
            <View style={styles.container}>
                <TextInput
                    onChangeText={(text)=> this.setState({
                        searchQuery: text
                    })}
                    style={styles.input}
                    placeholder="Search Query"></TextInput>
                <TouchableHighlight
                    onPress={this.onSearchPressed.bind(this)}
                    style={styles.button}>
                    <Text style={styles.buttonText}>Search</Text>
                </TouchableHighlight>

            </View>


        );
    }
    onSearchPressed(){
        debugger;
        const { navigate } = this.props.navigation;  
        navigate('Details',{
            type:"Navigate",
            routName:"Details",
            params:{Query:this.searchQuery}
        });
    }
}
'use strict';
import {Text,
    View,
    ListView,
    ActivityIndicatorIOS,
    Image,
    TouchableHighlight,
    StyleSheet,
    AppRegistry} from 'react-native';
    import React ,{Component} from 'react';

SearchResults 
export default class  SearchResults extends Component {
    constructor(props){
        super(props);
        debugger;
        var ds = new ListView.DataSource({
            rowHasChanged: (r1, r2) => r1 != r2
        });
        const { navigate } = this.props.navigation;
        const {params} = this.props.navigation.state;
        this.state = {
            dataSource: ds,
            showProgress: true,
            searchQuery: params.Query
        };
    }

    componentDidMount(){
        this.doSearch();
    }

    doSearch(){
        var url = 'https://api.github.com/search/repositories?q=' +
            encodeURIComponent(this.state.searchQuery);

        fetch(url)
            .then((response)=> response.json())
            .then((responseData)=> {
                this.setState({
                    repositories: responseData.repositories,
                    dataSource: this.state.dataSource
                        .cloneWithRows(responseData.items)
                });
            })
            .finally(()=> {
                this.setState({
                    showProgress: false
                });
            });
    }

    renderRow(rowData){
        return (
            <View style={{
                padding: 20,
                borderColor: '#D7D7D7',
                borderBottomWidth: 1,
                backgroundColor: '#fff'
            }}>
                <Text style={{
                    fontSize: 20,
                    fontWeight: '600'
                }}>
                    {rowData.full_name}
                </Text>

                <View style={{
                    flex: 1,
                    flexDirection: 'row',
                    justifyContent: 'space-between',
                    marginTop: 20,
                    marginBottom: 20
                }}>

                    <View style={styles.repoCell}>
                        <Image source={require('./images/Imagesxcassets/star.imageset/star.png')}
                            style={styles.repoCellIcon}
                        ></Image>
                        <Text style={styles.repoCellLabel}>
                            {rowData.stargazers_count}
                        </Text>
                    </View>
                    <View style={styles.repoCell}>
                        <Image source={require('./images/Imagesxcassets/star.imageset/star.png')}
                            style={styles.repoCellIcon}
                        ></Image>
                        <Text style={styles.repoCellLabel}>
                            {rowData.forks}
                        </Text>
                    </View>
                    <View style={styles.repoCell}>
                        <Image source={require('./images/Imagesxcassets/issues2.imageset/issues2.png')}
                            style={styles.repoCellIcon}
                        ></Image>
                        <Text style={styles.repoCellLabel}>
                            {rowData.open_issues}
                        </Text>
                    </View>

                </View>
            </View>
        );
    }

    render(){
      if(this.state.showProgress){
        return (
            <View style={{
                flex: 1,
                justifyContent: 'center'
            }}>
                <ActivityIndicatorIOS
                    size="large"
                    animating={true} />
            </View>
        );
      }

      return (
        <View style={{
            flex: 1,
            justifyContent: 'flex-start'
        }}>
            <ListView
                dataSource={this.state.dataSource}
                renderRow={this.renderRow.bind(this)} />
        </View>
      );
    }
}
json 
dependencies": {
    "buffer": "^5.0.8",
    "lodash": "^4.17.4",
    "moment": "^2.19.4",
    "object-array-converter": "^1.0.1",
    "prop-types": "^15.6.0",
    "react": "16.0.0",
    "react-native": "0.51.0",
    "react-native-cli": "^2.0.1",
    "react-native-elements": "^0.18.5",
    "react-native-navigation": "^1.1.315",
    "react-native-navigator": "^0.4.2",
    "react-native-simple-tab": "^1.0.8",
    "react-native-vector-icons": "^4.4.2",
    "react-navigation": "^1.0.0-beta.22"
