### ISSUE TITLE
React Native (RN) modal getting closed with left to right swipe gesture in IOS

### ISSUE THREAD

**Issue by ravirajn22** [react-community/react-navigation#1307]
### Current Behavior

I am using lot of React native Modal component in my app to show various pickers. Each modal has 
its own 'close' button to close the Modal. But in IOS with screen swipe gesture enabled , after opening any modal if i try to swipe from left to right with the modal still open, the parent screen of the modal automatically gets closed.

### Expected Behavior

I think swipe gesture should not do anything when a RN modal is open

### Your Environment

IOS

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.7

| react-native     |  0.43.0-rc.4
| node             | 
| npm or yarn      |

**Comment by VictorYuan666** [comment]
I have also encountered this problem！

**Comment by GollyJer** [comment]
Have you tried adding this the stack holding the modals?

```
navigationOptions: {
      gesturesEnabled: false,
}
```

**Comment by re7eal** [comment]
I have the same issue on react-native 0.44.0 with react-navigation 1.0.0-beta.9.

**Comment by ravirajn22** [comment]
@re7eal good method to handle the case, but i feel this functionality should be build into react-navigation and not handled every time by us, since it is the official navigation for react-native.

**Comment by spencercarli** [comment]
I don't think this is an issue in the latest release of react-navigation
