### ISSUE TITLE
DrawerNavigator with StackNavigator

### ISSUE THREAD

**Issue by zakster12** [react-community/react-navigation#131]
I would like to have a  stack navigator on my home screen with a left button which should open the drawer. But from the documentation I can't figure it out how to do it. Something like that:

![22f27b933a93b800fa76f16362dfc125](https://cloud.githubusercontent.com/assets/25477229/22504568/af7e18d2-e87f-11e6-875f-f9fa15e98f72.jpeg)

This is my App.js file:

```
const App = StackNavigator({
  Home: { screen: HomeFeed },
  Notifications: { screen: Notifications },
});
```

Feed.js
```
class Feed extends React.Component {
    static navigationOptions = {
        drawer: () => ({
            label: 'Home Feed',
        }),
    }
}
```

Notifications.js
```
class Notifications extends React.Component {
    static navigationOptions = {
        drawer: () => ({
            label: 'Notifications',
        })
    }
}
```

**Comment by pronevich** [comment]
You can use [DrawerNavigator](https://reactnavigation.org/docs/navigators/drawer) instead StackNavigator and then:
```javascript
static navigationOptions = {
        drawer: () => ({
            label: 'Home Feed',
        }),
    }
```
will be applied

**Comment by dodgecm** [comment]
I'm also having the same issue.  I don't seem to be able to render a left button in the StackNavigator nav bar while the DrawerNavigator is nested in it as the root view.

**Comment by sntran** [comment]
I have a similar issue with @dodgecm with a `DrawerNavigator` nested inside `StackNavigator`. 

When having these options in a 

```
static navigationOptions = {
    title: 'Dashboard',
    header: ({ state, setParams, navigate }) => ({
      left: <Button
          title={'Menu'}
          onPress={() => navigate('DrawerOpen')}
        />
    }),
    drawer: () => ({
      label: 'Home'
    }),
  };
```

The left menu does not appear. And also the drawer appears below the header

<img width="320" alt="screen shot 2017-02-01 at 8 08 35 pm" src="https://cloud.githubusercontent.com/assets/973206/22534518/4650f97a-e8ba-11e6-95c4-3d0fe0bfc7ce.png">

**Comment by nomoreboredom** [comment]
According to https://reactnavigation.org/docs/intro/nesting you have to put one navigator into a screen of root navigator; I use the following way to achieve that:

    const InnerNavigator = DrawerNavigator ({
        InnerHome: {
          screen: InnerHomeScreen,
        }, 
    });

    const SimpleApp = StackNavigator({  
       Landing: { screen: Landing},
       Dashboard: {screen: InnerNavigator}
    });

**Comment by zakster12** [comment]
I updated my code, now I am in the situation of @sntran 

```
const AppDrawer = DrawerNavigator({
	Home: { screen: HomeFeed },
	Notifications: { screen: Notifications }
});

const App = StackNavigator({
	Home: { screen: AppDrawer }
});

AppDrawer.navigationOptions = {
	title: 'Home Feed',
	
	header: () => ({
		// Render a button on the right side of the header
		// When pressed switches the screen to edit mode.
		left: (
			<Button
				title={'Drawer'}
			/>
		),
		tintColor: 'rgba(51, 51, 51, 1)'
	}),
};
```

![screen shot 2017-02-02 at 10 47 45 am](https://cloud.githubusercontent.com/assets/25477229/22542563/14ee46a0-e935-11e6-9cab-b5a04ddb4dac.png)

Also the left button is not visible and the tint color doesn't take any effect.

**Comment by BerndWessels** [comment]
Shouldn't the `Drawer` be the main/root navigation between the major sections of the app?

That would mean that the `Stack` or `Tab` would be nested within the drawer - because there is only one `Drawer` for the app anyways.

I tried that - but this seems to be buggy, because the `Stack` does not show a `header` anymore :(

**Comment by zakster12** [comment]
I think we really need an example in the documentation [https://reactnavigation.org/docs/intro/nesting](url) like there is one for the tab bar.

**Comment by BerndWessels** [comment]
@zakster12 Hi

So the following works for me (only tested on Android yet).

- The drawer draws out covering the full height of the screen - as I am used to on Android.
- The Notifications screen is a Stack with its own header visible on top.

To achieve this I had to render the `NotificationsNavigator` from a `NotificationsContainer` component rather than having it right away within the `DrawerNavigator`.

This has a site effect which I am unsure about whether this is intended, good or bad: The `DrawerNavigator` and the `NotificationsNavigator` now have separate redux reducers.

I actually like this but I can't tell if this is how it should be.

`react-navigator` really really really really needs better documentation of all these common nesting scenarios in combination with `redux`. Otherwise people will get frustrated and go back to `react-native-router-flux`.

So here is my solution for now:

`root app component`:

```js
/**
 * Import external dependencies.
 */
import React, {Component} from 'react';
import {BackAndroid, View} from 'react-native';
import {DrawerNavigator, addNavigationHelpers} from 'react-navigation';
import {connect} from 'react-redux';

/**
 * Import local dependencies.
 */
import Drawer from '../../drawer/component';
import Home from '../../home/component';
import Login from '../../login/component';
import Notifications from '../../notifications/component';

/**
 * The root navigator.
 * If your app should have a drawer, this is the place for it.
 * If not, just place any other navigator here.
 */
const RootNavigator = DrawerNavigator({
    Home: {
        screen: Home
    },
    Notifications: {
        screen: Notifications
    },
}, {
    //initialRouteName: 'Notifications',
    // Uncomment this if you want to use your own custom drawer component.
    // contentComponent: Drawer
});

/**
 * Export the reducer for the root navigator.
 */
export const rootNavigationReducer = (state, action) => (
    RootNavigator.router.getStateForAction(action, state)
);

/**
 * The applications root component.
 */
class AppRoot extends React.Component {
    // Invoked immediately after a component is mounted. Initialization that requires DOM nodes should go here.
    // If you need to load data from a remote endpoint, this is a good place to instantiate the network request.
    // Setting state in this method will trigger a re-rendering.
    componentDidMount() {
        // Subscribe to the hardware back button press event on TODO Android.
        BackAndroid.addEventListener('hardwareBackPress', () => {
            let {dispatch, rootNavigation} = this.props;
            // Close the drawer if necessary.
            if (rootNavigation.routes[rootNavigation.index].key === 'DrawerOpen') {
                dispatch({type: 'Navigate', routeName: 'DrawerClose'});
                return true;
            }
            return false;
        });
    }

    // The render function should be pure, meaning that it does not modify component state,
    // it returns the same result each time it's invoked, and it does not directly interact with the browser.
    // If you need to interact with the browser, perform your work in componentDidMount()
    // or the other lifecycle methods instead. Keeping render() pure makes components easier to think about.
    // You can also return null or false to indicate that you don't want anything rendered.
    // When returning null or false, ReactDOM.findDOMNode(this) will return null.
    render() {
        const {rootNavigation, dispatch} = this.props;
        // Are we authenticated?
        if (true) {
            // Render the root navigator.
            return (
                <RootNavigator navigation={addNavigationHelpers({
                dispatch: dispatch,
                state: rootNavigation
                })}/>
            );
        } else {
            // Render the login screen.
            return (
                <Login/>
            );
        }
    }
}

/**
 * Provide store properties to the component.
 */
const mapStateToProps = (state) => {
    return {
        rootNavigation: state.rootNavigation
    };
};

/**
 * Provide store actions to the component.
 */
const mapDispatchToProps = (dispatch) => ({
    dispatch: dispatch
});

/**
 * Connect the component to the store and export it.
 */
export default connect(mapStateToProps, mapDispatchToProps)(AppRoot);
```

`home screen`:

```js
/**
 * Import external dependencies.
 */
import React, {Component} from 'react';
import {Button, View, Text} from 'react-native';
import {connect} from 'react-redux';

/**
 * Import local dependencies.
 */
import {pingCreators, isPinging} from '../../redux/reducers/ping';

/**
 * Import styles.
 */
import styles from './styles';

/**
 * The component.
 */
class HomeContainer extends Component {
    render() {
        const {isPinging, ping} = this.props;
        return (
            <View style={styles.container}>
                <Text>Welcome Home</Text>
                <Text>{JSON.stringify(isPinging)}</Text>
                <Button onPress={()=>{ping();}} title="ping"/>
            </View>
        )
    }
}

/**
 * Provide store properties to the component.
 */
const mapStateToProps = (state) => {
    return {
        isPinging: isPinging(state.ping)
    }
};

/**
 * Provide store actions to the component.
 */
const mapDispatchToProps = (dispatch) => ({
    ping: () => dispatch(pingCreators.ping())
});

/**
 * Connect the component to the store and export it.
 */
export default connect(mapStateToProps, mapDispatchToProps)(HomeContainer)
```

`notification screen`:

```js
/**
 * Bernd Wessels (https://github.com/BerndWessels/)
 *
 * Copyright © 2016 Bernd Wessels. All rights reserved.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE.txt file in the root directory of this source tree.
 *
 * @flow
 */

'use strict';

/**
 * Import external dependencies.
 */
import React, {Component} from 'react';
import {Button, View, Text} from 'react-native';
import {StackNavigator} from 'react-navigation';
import {connect} from 'react-redux';

/**
 * Import local dependencies.
 */
import NotificationDetails from '../notificationDetails/component';
import NotificationList from '../notificationList/component';

/**
 * Import styles.
 */
//import styles from './styles';

const NotificationsNavigator = StackNavigator({
    NotificationList: {
        screen: NotificationList
    },
    NotificationDetails: {
        screen: NotificationDetails
    }
}, {
    headerMode: 'screen',
    navigationOptions: {
        title: 'my notifications'
    }
});

/**
 * The component.       //// TODO TODO TODO !!!!!!!!!!!!!! This might need its own reducer !!!???!!!??? !!!!!!!!!!!!!!!!!!!!!!!!!!
 */
class NotificationsContainer extends Component {
    // static navigationOptions = {
    //     // Title may be a simple string:
    //     title: 'notification',
    //     header: {
    //         right: <Button title="Info" onPress={()=>console.log('press')} />,
    //     },
    // };
    render() {
        return (
            <NotificationsNavigator/>
        )
    }
}

/**
 * Provide store properties to the component.
 */
const mapStateToProps = (state) => {
    return {
    }
};

/**
 * Provide store actions to the component.
 */
const mapDispatchToProps = (dispatch) => ({
});

/**
 * Connect the component to the store and export it.
 */
export default connect(mapStateToProps, mapDispatchToProps)(NotificationsContainer)
```

**Comment by GollyJer** [comment]
@BerndWessels , do you have a working example somewhere?  I'm trying struggling to get a version if this structure up and running.
If now, no biggy.
Thanks!

**Comment by zoontek** [comment]
@BerndWessels But if you do that, the Login component can't be a StackNavigator (for example)
The cleanest way to do that could be by disabled drawer (completely) and hide drawer element via navigationOptions.

**Comment by nikhildaga** [comment]
Any updates?  I think this is a very common requirement.

**Comment by coreyphillips** [comment]
The following structure helped resolve this issue on my end:

```
const Stack = {
	FirstView: {
		screen: FirstView
	},
	SecondView: {
		screen: SecondView
	},
	ThirdView: {
		screen: ThirdView
	}
};

const DrawerRoutes = {
	FirstViewStack: {
		name: 'FirstViewStack',
		screen: StackNavigator(Stack, { initialRouteName: 'FirstView' })
	},
	SecondViewStack: {
		name: 'SecondViewStack',
		screen: StackNavigator(Stack, { initialRouteName: 'SecondView' })
	},
	ThirdViewStack: {
		name: 'ThirdViewStack',
		screen: StackNavigator(Stack, { initialRouteName: 'ThirdView' })
	},
};

const RootNavigator =
	StackNavigator({
		Drawer: {
			name: 'Drawer',
			screen: DrawerNavigator(
				DrawerRoutes,
			),
		},
		...Stack
	},
		{
			headerMode: 'none'
		}
	);
```

**Comment by grabbou** [comment]
I am going to close this issue as looks like we got quite a few techniques already on how to approach this problem. 

In the meantime, we will try to fix other issues, like the ones about missing header with DrawerNavigator.

If you are still in doubt and don't know how to use a Drawer and Stacks, see `Drawer` example in NavigationPlayground, say what it's missing and we will make it a bit more comprehensive.

**Comment by manjeets12** [comment]
@BerndWessels, I implemented your code but now I am unable to get header over my screens

**Comment by manjeets12** [comment]
@BerndWessels  thanks your solution almost solved my problem, just wrapped my 1st screen within stackNavigator

**Comment by mattijauhiainen** [comment]
The solution by @coreyphillips sort of works, but on IOS if I navigate to 'SecondView' in the stack and then swipe from left to right, it will either navigate back to previous view on the stack (like it should), or open the drawer (undesirable). Is there some hack to prevent this? Or disable the swipe-from-left navigation?

**Comment by kenshinman** [comment]
@matthamil Have you tried setting `gesturesEnabled={false}` to false. It's always true on `iOS` and false on `android`

**Comment by cwagner22** [comment]
@mattijauhiainen Have you found a solution to prevent the drawer from opening with swipe on ios for the second views? I can't set `gesturesEnabled={false})` because I still want the user to be able to go back when swiping.

**Comment by kyaroru** [comment]
I'm able to solve it without using @coreyphillips solution :p

For the issue that @zakster12 facing, I was able to solve that by passing in the navigationOptions for Drawer so that the headerLeft and tintColor take effect.

App.js
```javascript
import { StackNavigator } from 'react-navigation';
import Drawer from './components/drawer';

const App = StackNavigator({
  Drawer: { screen: Drawer },
});

export default App;
```

Drawer.js
```javascript
import { DrawerNavigator } from 'react-navigation';
import Icon from 'react-native-vector-icons/FontAwesome';
import React from 'react';
import { getNavigationOptionsWithAction, getDrawerNavigationOptions, getDrawerConfig } from '../../utils/navigation';
import NavBarItem from '../common/NavBarItem';
import HomeScreen from '../home/HomeScreen';
import UserScreen from '../user/UserScreen';
import CustomerServiceScreen from '../customer-service/CustomerServiceScreen';
import * as Colors from '../../themes/colors';

const getDrawerItem = navigation => (
  <NavBarItem
    iconName="bars"
    onPress={() => {
      if (navigation.state.index === 0) {
        // check if drawer is not open, then only open it
        navigation.navigate('DrawerOpen');
      } else {
        // else close the drawer
        navigation.navigate('DrawerClose');
      }
    }}
  />
);

const getDrawerIcon = (iconName, tintColor) => <Icon name={iconName} size={20} color={tintColor} />;

const homeDrawerIcon = ({ tintColor }) => getDrawerIcon('home', tintColor);
const userDrawerIcon = ({ tintColor }) => getDrawerIcon('user', tintColor);
const csDrawerIcon = ({ tintColor }) => getDrawerIcon('user-md', tintColor);

const homeNavOptions = getDrawerNavigationOptions('Home', Colors.primary, 'white', homeDrawerIcon);
const userNavOptions = getDrawerNavigationOptions('Users', Colors.primary, 'white', userDrawerIcon);
const csNavOptions = getDrawerNavigationOptions('Customer Service', Colors.primary, 'white', csDrawerIcon);

const Drawer = DrawerNavigator({
  HomeScreen: { screen: HomeScreen, navigationOptions: homeNavOptions },
  UserScreen: { screen: UserScreen, navigationOptions: userNavOptions },
  CustomerServiceScreen: { screen: CustomerServiceScreen, navigationOptions: csNavOptions },
}, getDrawerConfig(300, 'left'));

Drawer.navigationOptions = ({ navigation }) => getNavigationOptionsWithAction('RNChat', Colors.primary, 'white', getDrawerItem(navigation));

export default Drawer;

```

Navigation.js
```javascript
export const getNavigationOptions = (title, backgroundColor, color) => ({
  title,
  headerStyle: {
    backgroundColor,
  },
  headerTitleStyle: {
    color,
  },
  headerTintColor: color,
});

export const getNavigationOptionsWithAction = (title, backgroundColor, color, headerLeft) => ({
  title,
  headerStyle: {
    backgroundColor,
  },
  headerTitleStyle: {
    color,
  },
  headerTintColor: color,
  headerLeft,
});

export const getDrawerNavigationOptions = (title, backgroundColor, titleColor, drawerIcon) => ({
  title,
  headerStyle: {
    backgroundColor,
  },
  headerTitleStyle: {
    color: titleColor,
  },
  headerTintColor: titleColor,
  drawerLabel: title,
  drawerIcon,
});

export const getDrawerConfig = (drawerWidth, drawerPosition) => ({
  drawerWidth,
  drawerPosition,
});

```

And the output will be like this
<img width="423" alt="screen shot 2017-06-18 at 03 33 47" src="https://user-images.githubusercontent.com/1030024/27255744-6787dab8-53d7-11e7-8ab1-c3c5c7e47569.png">

> The getDrawerItem() inside Drawer.navigationOptions is the key to make the headerLeft item displayed when drawer is open, but it will apply to all the child screen inside drawer too. (So we no need to pass in headerLeft for every screen)

**Comment by Shrek53** [comment]
@kyaroru  I am interested to your 

import { getNavigationOptionsWithAction, getDrawerNavigationOptions, getDrawerConfig } from '../../utils/navigation';
import NavBarItem from '../common/NavBarItem';

I am new to react-navigation and can not find a way to open the drawer from the header menu button.
It seems that navigation.navigate('DrawerOpen')  does not work inside navigationOption.

Can you help me by pointing to the right direction to open the drawer by clicking the header menu button. 
Thanks in advance.

**Comment by kyaroru** [comment]
Hi Apon,

It works if you retrieve the navigation object and use it. Because navigationOptions can be static or dynamic depending on your usage.
For more info can refer to: https://github.com/react-community/react-navigation/blob/master/docs/guides/Screen-Nav-Options.md

Here’s a simple example that I modify from my code.

NavBarItem.js
```javascript
import React, { Component, PropTypes } from 'react';
import { TouchableOpacity } from 'react-native';
import Icon from 'react-native-vector-icons/FontAwesome';

class NavBarItem extends Component {
  render() {
    const { iconName, onPress } = this.props;
    return (
      <TouchableOpacity
        style={{ paddingHorizontal: 20 }}
        onPress={() => onPress()}
      >
        <Icon name={iconName} size={20} color="#fff" />
      </TouchableOpacity>

    );
  }
}

NavBarItem.propTypes = {
  iconName: PropTypes.string.isRequired,
  onPress: PropTypes.func.isRequired,
};

export default NavBarItem;

```

Drawer.js
```javascript
// this is a method to retrieve icon element to show beside your title in the drawer
const homeDrawerIcon = ({ tintColor }) => <Icon name=“home" size={20} color={tintColor} />;

// this is a method to retrieve nav header of your home screen
const homeNavOptions = () => ({
  title: ‘Home',
  headerStyle: {
    backgroundColor: ‘blue',
  },
  headerTitleStyle: {
    color: ‘white',
  },
  headerTintColor: ‘white',
  drawerLabel: ‘Home',
  drawerIcon: homeDrawerIcon,
});

// this is the Drawer including HomeScreen
const Drawer = DrawerNavigator({
  HomeScreen: { screen: HomeScreen, navigationOptions: homeNavOptions }, // so the homeNavOptions will be used here
}, getDrawerConfig(300, 'left'));

// this is a method to retrieve the menu bar item for the drawer
const getDrawerItem = (navigation) => (
  <NavBarItem
    iconName="bars"
    onPress={() => {
      if (navigation.state.index === 0) {
        // check if drawer is not open, then only open it
        navigation.navigate('DrawerOpen');
      } else {
        // else close the drawer
        navigation.navigate('DrawerClose');
      }
    }}
  />
);

// here’s the key point, you have to retrieve navigation object because navigationOptions can be a dynamic method or static object
Drawer.navigationOptions = ({ navigation }) => ({
  title: ‘AppName',
  headerStyle: {
    backgroundColor: ‘blue',
  },
  headerTitleStyle: {
    color: ‘white',
  },
  headerTintColor: ‘white',
  headerLeft: getDrawerItem(navigation),
});

// after assign navigationOptions only export it
export default Drawer;
```




On 19 Jun 2017, at 1:49 PM, Apon Shahriar <notifications@github.com<mailto:notifications@github.com>> wrote:


@kyaroru<https://github.com/kyaroru> I am interested to your

import { getNavigationOptionsWithAction, getDrawerNavigationOptions, getDrawerConfig } from '../../utils/navigation';
import NavBarItem from '../common/NavBarItem';

I am new to react-navigation and can not find a way to open the drawer from the header menu button.
It seems that navigation.navigate('DrawerOpen') does not work inside navigationOption.

Can you help me by pointing to the right direction to open the drawer by clicking the header menu button.
Thanks in advance.

**Comment by Shrek53** [comment]
@kyaroru  Thanks man for your quick response . 
I was doing the navigation.navigate() wrong.
But after looking at some example code I figured it out some moments ago . 
Now I can open drawer by pressing button. 

Thanks again. :) :)

**Comment by kyaroru** [comment]
@Shrek53 icic, nowonder your reply is gone when I came in haha. It's great that you found out the solution :p

**Comment by sseyha** [comment]
@kyaroru 
Could you share your sample project?
I'm a starter of React-Native... It will help me a lot about this dude.

**Comment by kyaroru** [comment]
@sseyha a moment please :p will create a sample project out of my own

**Comment by kyaroru** [comment]
Hi @sseyha , here you go: https://github.com/kyaroru/ReactNavDrawer

**Comment by sseyha** [comment]
@kyaroru 
Million Thanks, You save my time

**Comment by sseyha** [comment]
@kyaroru 
Do you the way how to add button or toggle to Drawer Slide Menu?

**Comment by hungdev** [comment]
@kyaroru thank for example. but how to hide navbar when drawer appear?
like this
![sb090](https://user-images.githubusercontent.com/12009276/27507122-017399b2-58f3-11e7-8e03-84017cdbcbbc.png)

**Comment by kyaroru** [comment]
@hungdev can refer to my example code here : https://github.com/kyaroru/ReactNavDrawer

**Comment by godfredcs** [comment]
@kyaroru thank you very much. Your efforts are really appreciated.

**Comment by Solban** [comment]
@kyaroru the posted example produces where the appbar or toolbar is over drawer(picture below). Would it be possible to have drawer over the appbar, like on the picture posted by @hungdev ?
![image](https://user-images.githubusercontent.com/2881062/27925366-266c4248-628d-11e7-9979-38087be734ad.png)

**Comment by kyaroru** [comment]
Hi @Solban, to do it that way, i think you have to use @coreyphillips's method :p

**Comment by Pianist038801** [comment]
Hi, @kyaroru!
I have drawernavigator with stacknavigator in it.
and it works fine as expected on iOS,
But on Android, only the first drawerItem is shown and the rest items are invisible.
How can I solve this?

**Comment by mayankbaiswar-CSE** [comment]
How can I remove the gray tint on the left right side? Any suggestions?

**Comment by theOnkar** [comment]
@kyaroru . How can I use Tab Drawer and Stack together?

**Comment by samakkaking** [comment]
@Solban  did you find the answer

**Comment by hoscarcito** [comment]
Hey @BerndWessels  could you tell me if BackAndroid (now BackHandler) is working for you? wherever I am it close the app. The only thing I can do is close the drawer if its open.
Thanks in advance

**Comment by benevbright** [comment]
Those answer is so complicated. I think It's because that it was the only way at that time. 
Now, it's so simple. Please see my code.
```

const Nav = StackNavigator({
    mainnav_list:{
        screen: (props) => <TodoList {...props} dbCollectionName={props.screenProps.dbCollectionName}/>,
        navigationOptions:(props) => ({
            headerLeft:(
                <TouchableOpacity onPress={() => {props.screenProps.drawerNavigation.navigate('DrawerOpen');}}>
                    <Text style={{color:'white', marginLeft:15, fontWeight:'bold'}}>Menu</Text>
                </TouchableOpacity>
            )
        })
    },
    mainnav_detail:{screen: TodoDetail}
}
,
{
    navigationOptions:(props) => ({
        title:props.screenProps.dbCollectionName,
        headerBackTitle:null,
        headerStyle:{backgroundColor:'#000'},
        headerTitleStyle:{color:'#fff'},
        headerTintColor:'#fff',
    })
})

const AppDrawer = DrawerNavigator(
{
    drawer1:{screen:({navigation}) => <Nav screenProps={{dbCollectionName:'todos', drawerNavigation:navigation}}/> },
    drawer2:{screen:({navigation}) => <Nav screenProps={{dbCollectionName:'todos2', drawerNavigation:navigation}}/> }
})

AppRegistry.registerComponent('TodosFS', () => AppDrawer);
```

**Comment by benevbright** [comment]
![untitled-1](https://user-images.githubusercontent.com/916690/33943192-bb7642ac-e05b-11e7-802f-3ad1eb47a3c6.jpg)

**Comment by kyaroru** [comment]
@theOnkar u can refer to my example here: https://github.com/kyaroru/ReactNavTab
it is integrated with redux

**Comment by kyaroru** [comment]
@benevbright this is only when your DrawerNavigator is the main navigator. It will not work if you want to have a Login Page before showing the Drawer 😛

**Comment by Pianist038801** [comment]
Agree with @kyaroru . 
Redux is the best choice at this point.

**Comment by benevbright** [comment]
@kyaroru If you have a Login Page, create one more stackNavigator and put ‘login page’and ‘drawer’ that is created in my code. Then navigate each other as motal screen. It’s common aprouch.

**Comment by Pianist038801** [comment]
If any of you have basic understanding about redux but feels difficulty in implementing redux with navigation when it comes to combination of stacknavigator , drawernavigator and etc, you can follow this simple step.

-Stack Navigator
  --Login Page
  --Drawer Navigator
      ---SubScreen1
      ---SubScreen2 

In componentDidMount() of Login Page, you can get access to StackNavigator's navigation by {this.props.navigation}.
You store that variable to the redux store.
And if you wanna go back to login screen or to access to stack navigator navigation, you can do it easily from any of the screen in the same way you access to redux store.

**Comment by benevbright** [comment]
I have no problem using redux but you don’t even need it. 
Please see my code. @Pianist038801 
It’s better to know once it’s easy too without redux and then you choose redux.

**Comment by ibrahim1990** [comment]
i have a same issue before , but you can solve this problem like this 

first : import { DrawerNavigator , StackNavigator } from 'react-navigation';
second: import all component you want to add to Drawer navigation 
third: 

const Drawer = DrawerNavigator({
  Home: {
    screen: HomeScreen
  },
  Dealers: {
    screen: FindDealers
  },
  WinWithToyota: {
    screen: WinWithToyota
  },
  About: {
    screen: AboutScreen
  },
  Settings: {
    screen: Settings
  }

},
{
  drawerWidth: 300,
  drawerPosition: 'left',
  contentComponent: Sidebar,
  contentOptions: {
    activeTintColor: '#fff',
    activeBackgroundColor: '#eb0a1e'
  },
  drawerOpenRoute: 'DrawerOpen',
  drawerCloseRoute: 'DrawerClose',
  drawerToggleRoute: 'DrawerToggle'
})
=====================================

forth: 

export default App = StackNavigator({
  Main: { 
    screen: Drawer,
    navigationOptions: {
      header: null
    }
  },
  SingleInfo: { screen: SingleScreen }
}, {
    initialRouteName: 'Main',
})
============================

thanks,

**Comment by moddatherrashed** [comment]
Hey people ! 

i did struggle so much with that thing, so i tried many thing but that was the best way !! 

**first of all :**  
in the App file we define easily the DrawerNavigator like : 

```
const App = DrawerNavigator({
  FirstStackScreen: { screen: FirstStackScreen},
  SecondScreen: { screen: SecondScreen},
  ThirdScreen: { screen: ThirdScreen},
})
```

that will initialize the DrawerNavigator routes in general then for example we have a StackNavigator in let us say the FirstScreen, so we define a StackNavigator insdie the FirstScreen Component like : 

```
 const StackNavigation = StackNavigator({
    FirstStackScreen: { screen: FirstStackScreen},
    SecondStackScreen: { screen: SecondStackScreen},
    ThirdStackScreen: { screen: ThirdStackScreen},
})
```

that makes for us : 

1. the landing screen will be FrirstStackScreen.
2. if you swipe for the left to right you will have the drawer with three screens ( FirstStackScreen, SecondScreen, ThirdScreen
3. and you can navigate to SecondStackScreen and ThirdStackScreen with navigate function as normal.

# Happy Coding 👍

**Comment by trinadhkoya** [comment]
Did any body Handled Nested Menu Items for The Drawer.Like Expanded Items.

**Comment by brentvatne** [comment]
hi folks. this is a pretty big issue with lots of random discussions not all related to the OP. I'm going to lock discussion here, but please create a new issue if you have encountered a bug
