### ISSUE TITLE
IOS environment tab content does not show

### ISSUE THREAD

**Issue by fangkyi02** [react-community/react-navigation#1314]
![image](https://cloud.githubusercontent.com/assets/3389652/25565395/8c33d6aa-2df8-11e7-90c7-f9aaa9cd189a.png)

![image](https://cloud.githubusercontent.com/assets/3389652/25565405/a745658a-2df8-11e7-86a9-8bb0567d065a.png)

![image](https://cloud.githubusercontent.com/assets/3389652/25565408/b2356c42-2df8-11e7-8efd-bbc444f9382d.png)

When the lazy is opened, the initialRouteName page does not appear, but other pages can be displayed
If you do not open the lazy as long as it is the use of flatlist pages can not be displayed properly

Android all normal without any problems click into the future can be displayed by default
This problem is only on the IOS side

I tried to delay the update and other ways can not make the home page flatlist display

**Comment by DomiR** [comment]
See here https://github.com/react-community/react-navigation/issues/1279

Gist: add `removeClippedSubviews={false}` to FlatList

**Comment by spencercarli** [comment]
Closing in favor of #1279
