### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by jeffreymendez1993** [react-community/react-navigation#1316]
Not really a issue but when is the next release going to happen? What issues will be targeted on that release since there are a couple workarounds that have been done in my app that I am hoping can be done with the library instead of hacky solutions.

**Comment by matthamil** [comment]
@jeffreymendez1993 https://github.com/react-community/react-navigation/releases v1.0.0-beta.9 was just released 5 days ago. The maintainers encourage PRs to help out the library :)

**Comment by jeffreymendez1993** [comment]
Yeah made a pr to help out with the pace @matthamil. The main issues that I am having I feel like are big issues that are stopping this library from being #1.

**Comment by rumax** [comment]
@jeffreymendez1993 Any plan for stable release, not a `beta`?

**Comment by TiraO** [comment]
@skevy Time for a new release? I'm really looking forward to the Drawer/Stack combo fix that got pulled in this week.

**Comment by sanjayholla94** [comment]
@spencercarli This can be closed
