### ISSUE TITLE
Can't navigate from header

### ISSUE THREAD

**Issue by IgorVanian** [react-community/react-navigation#1318]
1.0.0-beta.9
No error messages, no warnings...
Clicking the button fires goToNewEvent but doesn't navigate to the route.

```
...
events: {
	screen: StackNavigator({
		events: { screen: HomeScreen },
		newEvent: { screen: NewEventScreen }
	})
}
...
```
```
class NewIcon extends Component {
	goToNewEvent = () => {
       		this.props.navigation.navigate({
        		routeName: 'newEvent'
    		});
    	};
  	render() {
	    return (
	      	<TouchableOpacity onPress={() => this.goToNewEvent()}>
			<Icon name='new-message' color='black' size={25} />
		</TouchableOpacity>
	    );
  	}
}

class HomeScreen extends Component {
	static navigationOptions = ({navigation}) => ({
		tabBarIcon: ({focused}) => (focused ? HomeIcon : HomeIconWhite),
		headerRight: <NewIcon navigation={navigation} />,
		title: <Text style={{color: 'black'}}>Events</Text>,
		headerStyle: {
			backgroundColor: 'white'
		}
	})

	constructor(props) {
	    super(props);
	}

	render() {
		return (
			<View style={{flex: 1}}>
			</View>
		);
	}
}
```

**Comment by koenpunt** [comment]
You should call `navigate('newEvent')` instead. The format with `{ routeName: 'newEvent' }` is used for the `NavigationActions.navigate` method.

**Comment by IgorVanian** [comment]
Generates this error when I try to navigate: 

"Invalid data message - all must be length: 36"

![image](https://cloud.githubusercontent.com/assets/16898357/25578397/94917552-2e6e-11e7-9322-93058063b399.png)

```
import React, { Component } from 'react';
import { 
	View, 
	Text 
} from 'react-native';

class NewEventScreen extends Component {


	constructor(props) {
	    super(props);
	}

	render() {
		return (
			<View style={{flex: 1}}>
			</View>
		);
	}
}

export default NewEventScreen;
```

**Comment by IgorVanian** [comment]
Also, this error logs with the previous one:

`Converting circular structure to JSON`

**Comment by despreston** [comment]
getting the same message

**Comment by despreston** [comment]
Ok I found the issue. Changing the `title` in my navigationOptions to a generic string instead of a `<Text>` component resolves the error. Seems like either this is no longer accepting anything but generic strings, or this is a bug. Im uncertain since its hard to tell where in the react-native code this error is being thrown.

**Comment by koenpunt** [comment]
To use a custom component for the title in the header, you have to use the `headerTitle` option.

```js
static navigationOptions = ({navigation}) => ({
  // ...
  headerTitle: <Text style={{color: 'black'}}>Events</Text>,
  headerStyle: {
    backgroundColor: 'white'
  }
})
```

`headerTitle` will also have precedence over `title`

**Comment by koenpunt** [comment]
But if the only customisation you want to do is concerning style, then you can simply set the `headerTitleStyle` option.

**Comment by despreston** [comment]
Right but ideally some where this should be caught and a warning or error should be thrown with a message. Right now its failing and its hard to tell exactly what is going on.

**Comment by IgorVanian** [comment]
Everything is good now I guess.
