### ISSUE TITLE
DrawerNavigator + contentComponent + screenProps

### ISSUE THREAD

**Issue by Andreyco** [react-community/react-navigation#1319]
### Current Behavior
- Having created DrawerNavigator with custom `contentComponent`
- Passing `screenProps` to `DrawerNavigator`
```
<MyDrawerNavigator screenProps={{...}} />
```

Screen component DO receive those screen props, but custom drawer DOES NOT receive them.

### Improved Behavior
It would be convenient if customer drawer component specified as `contentComponent` do receive those `screenProps` - eg, for rendering user info in drawer.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  beta-9
| react-native     |  0.43.4
| node             | 7.9.0
| npm or yarn      | yarn 0.23.3

**Comment by amirrezamahyari** [comment]
same issue

**Comment by Andreyco** [comment]
If you guys are open to this, I am willing to create PR for this improvement.

**Comment by Andreyco** [comment]
This is now implemented, thanks!
https://github.com/react-community/react-navigation/pull/1039/files#diff-1ef5b8f9d10c4acbaf92697f3abd0041R95
