### ISSUE TITLE
Navigator is deprecated in RN 0.44.0  and not working 

### ISSUE THREAD

**Issue by amirrezamahyari** [react-community/react-navigation#1328]
after upgrade react native to 0.44.0 i get this error : 

i use react-navigation  1.0.0-beta.9 package and i got BackAndroid deprecated too .

**Navigator is deprecated and has been removed from this package. It can now be installed and imported from `react-native-deprecated-custom-components` instead of `react-native`. Learn about alternative navigation solutions at http://facebook.github.io/react-native/docs/navigation.html**

how can i fix this ?

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.9
| react-native     |  0.44.0
| node             | 7.9.0
| npm or yarn      | 4.2.0

**Comment by grabbou** [comment]
As error message indicates, you should install react-native-deprecated-custom-components and import NavigationExperimental from there.

**Comment by amirrezamahyari** [comment]
@grabbou but i think you closed immediatly without any define a correct solution .
as i see in the relative module codes  there is a dependency in react-navigation for Navigate component yet  .
so i  think this issue must be reopened till solve this problem .

**Comment by grabbou** [comment]
There's no issue to be solved. Navigation experimental has been removed from React Native and moved to a separate package that I've listed above. You should slowly upgrade your code to use a new navigation library, like this one. Before that happens, you can keep on using Navigation Experimental from the above package.

**Comment by muxiaodeng** [comment]
hi，grabbou，i read your tips and installed react-native-deprecated-custom-components，and import Navigator from 'react-native-deprecated-custom-components' ，but an error occured，it said that  Element type is invild：excepted a string or a class/function but got: object; 
and i just has an Navigator in there ,so can you help me with that? Thanks!

**Comment by ashish-algorythma** [comment]
@muxiaodeng I think you should import NavigationExperimental and not Navigator:
import {NavigationExperimental} from 'react-native-deprecated-custom-components';

**Comment by muxiaodeng** [comment]
@ashish-algorythma thanks,but it didn't work,still say Element type is invalid;

**Comment by Juxtlie** [comment]
I have the same problem

**Comment by Juxtlie** [comment]
@amirrezamahyari  Do you have resolve?

**Comment by davidck** [comment]
Fixed with:
import NavigationExperimental from 'react-native-deprecated-custom-components';

Use with:
<NavigationExperimental.Navigator

**Comment by nvs2394** [comment]
I fixed it with code
`import React, { Component } from 'react';
import {
} from 'react-native';
import Movies from './Movies';

import NavigationExperimental from 'react-native-deprecated-custom-components';

const RouteMapper = (route, navigator) => {
  if (route.name === 'movies') {
    return <Movies navigator={navigator} />;
  }
};

export default class App extends Component {
  render() {
    return (
      <NavigationExperimental.Navigator
        // Default to movies route
        initialRoute={{ name: 'movies' }}
        // Use FloatFromBottom transition between screens
        configureScene={(route, routeStack) => NavigationExperimental.Navigator.SceneConfigs.FloatFromBottom}
        // Pass a route mapper functions
        renderScene={RouteMapper}
      />
    );
  }
}`

**Comment by rexjrs** [comment]
Why was React Navigator deprecated?

**Comment by nvs2394** [comment]
@rexjrs Because in last version it don't use Navigator in react-native . It switch to use react-native-deprecated-custom-components. You can see notied when running app.

**Comment by rexjrs** [comment]
No. My question is, what was the reason behind deprecating the Navigator component? Was it bad, were there much better alternatives? etc.

**Comment by peterheard01** [comment]
Hey Chaps I am using ```import { StackNavigator } from 'react-navigation';``` and I am getting the same error. The solution on here will not work since it is the newest version of ```react-navigation``` which needs to be fixed in order for ```react-native``` to work. When will ```react-navigation``` be fixed? Need any help?

**Comment by amirrezamahyari** [comment]
@saeedtabrizi see this issue

**Comment by saeedtabrizi** [comment]
@amirrezamahyari HAZA MEN FAZLE RABBI, thanks a lot .

**Comment by rexjrs** [comment]
@saeedtabrizi can you clearly explain what you mean by comment in react native folder in node modules? How can I do this.

**Comment by amirrezamahyari** [comment]
@saeedtabrizi thanks MOHANDES
 @rexjrs 
ok , i comment this lines and its already ok:
node_modules/react-native/Libraries/react-native/react-native-implementation.js
line 129
<img width="878" alt="screen shot 2017-05-09 at 9 25 16 am" src="https://cloud.githubusercontent.com/assets/20089037/25836107/8a313a76-3499-11e7-9e09-45f3cd89b0fe.png">

**Comment by rexjrs** [comment]
Thank you very much!

**Comment by prateekvarma** [comment]
@davidck  Did you need to pull in something from NPM too? I get a 500 error when i use your way.
Thanks.

**Comment by davidck** [comment]
@prateekvarma 
npm install react-native-deprecated-custom-components --save

**Comment by Juxtlie** [comment]
@amirrezamahyari Your comment helped me. Thank you very much.

**Comment by minkesh** [comment]
@nvs2394  I also tried doing the same but I am getting an error `Cannot read property 'SceneConfigs' of undefined for _reactNative.Navigator.SceneConfigs` did you face any such issue and how did you solve it ?

**Comment by flyandi** [comment]
so what was the reason to kick it out?  just because react-navigation is more powerful?

**Comment by nontachaiwebdev** [comment]
I have a problem when i use NavigationBar. Who you know way to solve this problem with react-native-deprecated-custom-components ?

Thank you

**Comment by nhoxbypass** [comment]
So what is the officially replacement for Navigator. (i'm using NavigationExperimental.Navigator instead, for it much likely Navigator)

**Comment by dcu-sharepoint** [comment]
I don't have a problem when software is updated or DEPRECATED, but I do have a HUGE problem when software is REMOVED at the whim of some arrogant individual and as some of the answers in this issue can attest, the answer as to **why was the Navigator removed** from react-native does not help and the answer: **deal with it** is not an answer either.
In my case, I'm taking a video course in react-native and the use of the **Navigator** is **totally** different from say **StackNavigator** or any of the navigators in the wild. my only solution is to go back to the version the course uses and then see if I can migrate to a new navigator once I understand the concept of **Navigating**.
Not fun or funny!

**Comment by khalDrogo13** [comment]
@nvs2394 Thanks man...your code helped me. btw does anyone know the difference between StackNavigator and NavigationExperimental.Navigator ?

**Comment by zos** [comment]
I also would like to know what's the best replacement for Navigator?
Now, even when I use import {NavigationExperimental} from 'react-native-deprecated-custom-components' and NavigationExperimental.Navigator I have an error : undefined is not an object (evaluating '_reactNativeDeprecatedCustomComponents.NavigationExperimental.Navigator'). What should I do?

**Comment by zos** [comment]
I also would like to know what's the best replacement for Navigator?

**Comment by mobdevchan** [comment]
I don't use Navigator in my codes. But I am getting this error.

<img width="369" alt="screen shot 2017-06-20 at 3 42 39 am" src="https://user-images.githubusercontent.com/29212850/27298045-885e037c-556a-11e7-8d76-90250412c5bb.png">

<img width="423" alt="screen shot 2017-06-20 at 3 43 14 am" src="https://user-images.githubusercontent.com/29212850/27298067-a01db08e-556a-11e7-829f-96d198e87c96.png">

Anybody can help me?

**Comment by nontachaiwebdev** [comment]
In RN0.44 Not support old Navigator.

You should installed and imported from react-native-deprecated-custom-components instead of react-native

**Comment by hiteshsahu** [comment]
What to use instead of Navigator? using deprecated components in my project make me feel uncomfortable.

**Comment by rexjrs** [comment]
Use react-navigation. It is the most used one and very powerful.

**Comment by thangpq** [comment]
@davidck 👍  Many thanks for all your helps. Its really better anything

**Comment by vivekkumarmaru** [comment]
I think A possible plan is to move Navigator out into a separate repo and publish it to npm.

**Comment by wanhaojun118** [comment]
@muxiaodeng I guess you are importing like this : 
import Navigator from 'react-native-deprecated-custom-components';

Try change it to:
import {Navigator} from 'react-native-deprecated-custom-components';

**Comment by roysG** [comment]
I get error, someone know why?
![screen shot 2017-10-19 at 10 22 03](https://user-images.githubusercontent.com/7311802/31758763-6e3372d2-b4b7-11e7-88d4-03ea7ba33ca6.png)

Thanks.

**Comment by worldlee78** [comment]
The react-native-deprecated-custom-components is using deprecated methods that are no longer available in React 16.0. Until someone updates the component, it is broken.

**Comment by roysG** [comment]
Yee.. tell me about that, after i struggle for 1 hour without success, i move to the new navigator.
Thanks anyway :)

**Comment by kayson** [comment]
Use GitHub version instead of NPM:

`npm install https://github.com/facebookarchive/react-native-custom-components.git --save`

**Comment by saeedtabrizi** [comment]
Hi @roysG 
After the installing `react-native-deprecated-custom-components ` You must clean the cache and build your package again .  
reset the cache with the following line script : 
` rm -rf node_modules/ && npm cache clean && npm install && npm start -- --reset-cache`
I hope this script resolve your problem .

**Comment by roysG** [comment]
Hi guys,
Thanks for your responses, but now i am getting another error when i run the command to clean the cache

Error:

npm ERR! As of npm@5, the npm cache self-heals from corruption issues and data extracted from the cache is guaranteed to be valid. If you want to make sure everything is consistent, use 'npm cache verify' instead.
npm ERR!
npm ERR! If you're sure you want to delete the entire cache, rerun this command with --force.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/rsabah/.npm/_logs/2017-10-26T14_02_28_966Z-debug.log

**Comment by roysG** [comment]
Do i need to install also the: 
"prop-types": "^15.6.0" ? (with npm)

**Comment by saeedtabrizi** [comment]
@roysG it's good news from you , but i guess you must review your navigation configuration again .

**Comment by anniewey** [comment]
@roysG use PropTypes.func instead of React.PropTypes.func if you haven't implement the changes

**Comment by astw** [comment]
There are a lot breaking changes!

**Comment by sven0726** [comment]
i have the same error

**Comment by rh389** [comment]
I had the error even though I wasn't trying to use `Navigator`. It turns out the error was thrown because I accidentally had this line (my IDE had auto-inserted it):

`import * as Platform from 'react-native'`

Changing that to 

`import { Platform } from 'react-native'`

Fixed the issue. It turns out if you do `import * as Foo from 'react-native'` it triggers RN's warnings about deprecated/removed exports, which completely threw me off. HTH

**Comment by macelii** [comment]
They are often too many breaking changes. Update the codebase of your existing project is a nightmare.

**Comment by adrianolsk** [comment]
@rh389 Thank you, you saved my life, was getting this error even not using the Navigator.
I trusted the IDE to do an import and it imported like this: `import * as Messages from "react-native";`
That was causing the problem.

**Comment by VarunDcoder** [comment]
Hi @roysG did you solved that error?

**Comment by VarunDcoder** [comment]
@saeedtabrizi Hi, Ihave commented the code(Navigator) in the node_modules but it's throwing new error 
![newerror](https://user-images.githubusercontent.com/26574718/34763727-22f001c2-f612-11e7-8605-bb02ed1640dc.JPG)

**Comment by slealAndreia** [comment]
@VarunDcoder I'm going through the same situation. Did you solve the problem?

**Comment by VarunDcoder** [comment]
Hi @andreia-sl After resetting the cache with the following line script :
`rm -rf node_modules/ && npm cache clean && npm install && npm start -- --reset-cache`
and commenting the lines in node_modules/react-native/Libraries/react-native/react-native-implementation.js as said by @amirrezamahyari. My code is working fine now but got some warnings.

**Comment by andreia-sl** [comment]
I gave up using the Navigator and am using RouterFlux. But thx @VarunDcoder

**Comment by JAYANTdEV** [comment]
if depresiate and pakage is remove ---error
naivigatorExperimental import and < NaivigatorExperimental.Navigator /> used this two statement perfect run your programme

**Comment by ilpanda** [comment]
you show  use  this  now : 
import {Navigator} from 'react-native-deprecated-custom-components'

**Comment by ue** [comment]
if you already upgrade `react-navigation` and you still see this error probably its not about the `react-navigation`. So you should upgrade which is using `BackAndroid` packages. I found a way;

Just search `BackAndroid` in your `node_modules` So thats for the understand which is using deprecated thing.

Then just upgrade them to latest version or fixed version for `BackAndroid`.
