### ISSUE TITLE
Swipe animation is buggy in TabNavigator (Android)

### ISSUE THREAD

**Issue by VERSAYANA** [react-community/react-navigation#133]
Sometimes when I swipe between screens indicator can't follow screen properly
As you can see sometimes screen changes completely then indicator start moving
![ezgif com-87e42e7045](https://cloud.githubusercontent.com/assets/20874813/22505257/bcd4f716-e88f-11e6-9696-277d2527b66c.gif)

**Comment by VERSAYANA** [comment]
Also why label isn't center when you set tabBarComponent to TabView.TabBarBottom?

**Comment by ericvicenti** [comment]
cc @satya164

**Comment by satya164** [comment]
I'm afraid we can't really do much here right now. The swipe occurs in native side and the indicator animation occurs in JS side, so the JS thread can sometimes fall behind and lag.

The only way to fix this will be to use native animation events, which I'm working on. I need some changes in RN to be able to use native animations fully, so it'll take another month or so.

Another change needed is that `ViewPagerAndroid` doesn't support native animation events yet. So we need to add support for that too. Help is welcome.

Maybe @janicduplesis can help with the `ViewPagerAndroid` part?

**Comment by ericls** [comment]
`InteractionManager` might be helpful,

It allows javascript to focus on animation before any other tasks.

**Comment by satya164** [comment]
I'm closing this issue because this is not actionable. I'm constantly improving tab view as React Native changes, so we will have fully native driven animations someday.

**Comment by wkgalla** [comment]
Thanks for your great work.
But when I am running react native tab view example on exponent, animation is very smooth.
Is react navigation is causing this or what?

**Comment by satya164** [comment]
@wkgalla as strange at it may sound, I think the exponent demo has an older version with JS based pager. generally I have found js based pager feel much smoother than native pagers when js is not blocked, because there's no lag between two different threads.

cc @mkonicek :)

**Comment by wkgalla** [comment]
I will be waiting for it to improve as I am working on a project that requires this feature in later versions.

**Comment by KakarN** [comment]
Me too!

**Comment by satya164** [comment]
This delay is barely noticeable in production. It's more prominent in development mode. The improvements will take time, because the `ViewPagerAndroid` in React Native doesn't support native animation event.
