### ISSUE TITLE
BackAndroid is deprecated [react-native 0.44.0]

### ISSUE THREAD

**Issue by stephanedemotte** [react-community/react-navigation#1330]
In react native 0.44.0, BackAndroid is deprecated. Got a warn :/

Thanks !

**Comment by jimmytb** [comment]
You can use the BackHandler see: http://facebook.github.io/react-native/releases/0.44/docs/backhandler.html

**Comment by stephanedemotte** [comment]
I don't use it, but react-natigation does :)

**Comment by zackify** [comment]
If someone can point me to the write place I'll make a PR, I'll look around the source for now 👍

**Comment by zackify** [comment]
@stephanedemotte https://github.com/react-community/react-navigation/pull/1333

**Comment by m191007** [comment]
I have the same warning when I use StackNavigation, How can I fix it

**Comment by mortezaalizadeh** [comment]
+1

**Comment by Charles-LMQ** [comment]
+1 too, looks like the react-navigation did not upgrade as well

**Comment by c-bata** [comment]
+1

**Comment by crscaballero** [comment]
+1

**Comment by skevy** [comment]
This will land in #1520, and be out in beta.10 -- which will be released tomorrow.

**Comment by ajostergaard** [comment]
All the people commenting "+1" make Baby Jesus cry.

**Comment by mimiyan056** [comment]
"Warning: BackAndroid is deprecated.  Please use BackHandler instead."
I also use the StackNavigation, +1

**Comment by SNNikitin** [comment]
@skevy "tomorrow" was yesterday :)
Is here some news about beta10?

**Comment by Komeyl94** [comment]
@SNNikitin the pre-release is here 🙌

**Comment by helloconch** [comment]
I hava the same problem. 
import{
  StackNavigator,
  TabNavigator
}from 'react-navigation';

**Comment by helloconch** [comment]
I have the same problem.
import{
StackNavigator,
TabNavigator
}from 'react-navigation';

**Comment by SNNikitin** [comment]
@skevy Good news! Thank you!
And what about npm package for this beta? I can't install it via npm/yarn - there still only beta9 is available...

**Comment by skevy** [comment]
It's there -- `npm install react-navigation@1.0.0-beta.10`.

We just haven't set it to the `latest` dist-tag yet because we haven't had time to write release notes.

**Comment by SNNikitin** [comment]
@skevy Yeah!!!! Thank you - you are really right, my confuse
All works now, thanks again :)

**Comment by xilonxiao** [comment]
I'm still getting this warning even with the react-navigation@1.0.0-beta.10 version. I'm on RN 0.44.2.  The update to 1.0.0-beta.10 removed the warning on ios simulator, but not on android device.

**Comment by webraptor** [comment]
And it is still present on beta.11 with RN .45

**Comment by ajostergaard** [comment]
Works for me with:
```
    "react-native": "^0.44.0",
    "react-navigation": "git+https://github.com/react-community/react-navigation.git",
```

**Comment by logileifs** [comment]
I've tried beta 10, beta 11 and install from git like @ajostergaard suggested but I always get the warning on Android. Was the solution really to just remove the warning from iOS ?

**Comment by areeb111** [comment]
Fixed here: https://github.com/aksonov/react-native-router-flux/issues/1842#issuecomment-313804400

**Comment by ue** [comment]
Just take a look this comment [fixed here](https://github.com/react-navigation/react-navigation/issues/1328#issuecomment-459094444)
