### ISSUE TITLE
Can we set mode inside route configs. 

### ISSUE THREAD

**Issue by jeffreymendez1993** [react-community/react-navigation#1331]
It would be awesome if we can do something like this.

const sharedStackConfigs = {
  // ...other configs
  navigationOptions: {
    header:null,
  },
  headerMode: 'screen'
};

const myStack = {
  Landing: {screen: LandingView},
  StackScene1: {screen: SomeOtherView, **mode:'modal'**},
};

const SomeStack = StackNavigator(myStack, sharedStackConfigs);

**Comment by maksimdegtyarev** [comment]
+1

**Comment by jeffreymendez1993** [comment]
@grabbou what's the progress on this? This needs to be added I can try to implement this and make a pr if needed.

**Comment by q273255702** [comment]
+1

**Comment by koenpunt** [comment]
Mode is navigator-wide on purpose I believe. If you want to display a modal screen from within a stacknavigator, wrap that navigator with an additional stacknavigator with `mode` set to `modal`

**Comment by dioxide** [comment]
+1

**Comment by chrissm79** [comment]
@koenpunt I tried that same thing but it did not work (the `Modal` navigator still used the default `card` transitions)

```js
const ModalStack = StackNavigator({
  // when navigating here it still uses the default transition instead 
  // of sliding in from the bottom
  Screen3: { screen: Screen3 },
}, {
  mode: 'modal',
})

const AppStack = StackNavigator({
  Login: {
    screen: Screens.Login,
    navigationOptions: () => ({
      header: null,
    }),
  },
  Modal: { screen: ModalStack },
  Screen1: { screen: Screen1 },
  Screen2: { screen: Screen2 },
});
```

**Comment by kelset** [comment]
Pinging OP @jeffreymendez1993 since this issue is quite old and related to an old version of the lib. If no answer I'll close in 7 days.

**Comment by kelset** [comment]
Hi there @jeffreymendez1993,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue (especially if it's a bug report) please open a new issue that uses the new Issue Template to provide some more details to help us solve it.
