### ISSUE TITLE
Drawer nested in tabs shows on adjacent tab

### ISSUE THREAD

**Issue by scf4** [react-community/react-navigation#1332]
The first tab in my tab nav is a screen with a drawer on the right.

When I go to tab 2 (to the right of tab 1) I see the drawer from tab 1.

Is there a simple fix for this, or should drawers not be children of tabs?

**Comment by spencercarli** [comment]
Hi! In an effort to reduce the number of open issues I'm closing issues that haven't had any activity in a while.

If you think this should be re-opened please let me know or, if you can, re-open it.

If this is a question please consider asking it on StackOverflow ([react-navigation](https://stackoverflow.com/questions/tagged/react-navigation))

Thanks!
