### ISSUE TITLE
Style for active tab

### ISSUE THREAD

**Issue by jonasostrom** [react-community/react-navigation#1334]
Is there a way to set custom style for the active tab?
Like borderBottom and borderWidth for the active tab when using the swipe-function etc.

**Comment by gabrielbull** [comment]
Follow up on this as it is related to #1472 and #1667. Is this something that interests you @skevy? I could add it as a PR as well like I did for #1667. It could use the following parameter in the `tabBarOptions`:

```jsx
tabBarOptions: {
  activeTintColor: '#e91e63',
  labelStyle: {
    fontSize: 12,
  },
  tabStyle: {
    width: 100,
  },
  activeTabStyle: {
    backgroundColor: 'red',
  },
  style: {
    backgroundColor: 'blue',
  },
}
```

**Comment by kelset** [comment]
I could use having an `activeTabStyle` option too :)

**Comment by dmr07** [comment]
+1

**Comment by dmkboo** [comment]
+1

**Comment by kelset** [comment]
that I know of no open PRs tackle this FR, feel free to open a new one and I'll do my best to review it asap.

@gabrielbull would you be interested into doing it?

**Comment by YasirPanjsheri** [comment]
Any news regarding this! I am trying to set fontWeight for the tab label when it's active, can we do that?

**Comment by kelset** [comment]
@YasirPanjsheri here you can find two ways to implement this: https://github.com/react-community/react-navigation/issues/2818

**Comment by kelset** [comment]
To reduce redundancy, I'll close this in favor of #1472

**Comment by nikhil-tayal** [comment]
> Any news regarding this! I am trying to set fontWeight for the tab label when it's active, can we do that?

Not able to find the direct solution but what you can do is:
`<Tab.Screen
        name="Promotion"
        options={{
          tabBarLabel: ({ tintColor, focused }) => (
            <Text style={focused ? { fontWeight: "bold" } : null}>Promotion</Text>
          ),
          tabBarIcon: () => <MaterialCommunityIcons name="bell" size={26} />,
        }}
        component={Promotion}
      />`
