### ISSUE TITLE
Drawer getting stuck on swipe

### ISSUE THREAD

**Issue by Adamnator92** [react-community/react-navigation#1336]
The Drawer get stuck sometimes with no reason, it often happen on view that have gestures features like drag, scrolling or swipe

### My Environment
| software         | version
| ---------------- | -------
| react-navigation |  "^1.0.0-beta.8"
| react-native     |  "0.42.2"
| node             | v6.9.2
| npm or yarn      | 3.10.9

![screenshot_20170502-121159](https://cloud.githubusercontent.com/assets/22557298/25604112/94ad7c8c-2f33-11e7-896e-1fdb1cfbeabc.png)

**Comment by Andreyco** [comment]
Experience same behaviour when in debug mode - not sure about release, haven't run that. How is your experience in release run?

**Comment by jeffreymendez1993** [comment]
Happens to me as well.

**Comment by Adamnator92** [comment]
@Andreyco i tried few times with android release version, it still happen

**Comment by DevYears** [comment]
Same problem on debug and release versions.

**Comment by Mrachko** [comment]
Same problem on Android, could you please investigate it? It makes user's experience much worse.

**Comment by Andreyco** [comment]
This should be resolved in recent `react-navigation` release.

**Comment by Adamnator92** [comment]
@Andreyco thank! it's worked great, didn't face this issues after i update to latest version
