### ISSUE TITLE
Is it possible to support navigation back hook and prevent navigation transition when triggered by gesture.

### ISSUE THREAD

**Issue by 13860120868** [react-community/react-navigation#1337]
### Current Behavior

I want to block the navigation and prompt a confirmation popup for end user to decide whether to leave if current screen is editing, I custom "getStateForAction" and exam the "action.type", in android it works very well, how ever this approach doesn't work for IOS when the screen transition is triggered by gesture, the transition has been done after the animation, please check the following code in react navigation "CardStack.js", cannot do anything to block the "_goBack"

`

         

         
         position.stopAnimation((value: number) => { 
         // If the speed of the gesture release is significant, use that as the indication
          // of intent
          if (velocity < -0.5) {
            this._reset(immediateIndex, velocity);
            return;
          }
          if (velocity > 0.5) {
            this._goBack(immediateIndex, velocity);
            return;
          } 
         // Then filter based on the distance the screen was moved. Over a third of the way swiped,
          // and the back will happen.
          if (value <= index - POSITION_THRESHOLD) {
            this._goBack(immediateIndex, velocity);
          } else {
            this._reset(immediateIndex, velocity);
          }
`

### Expected Behavior

Provide an globe hook on navigation to so we have a chance to block the transition, e.g.

navigation.onBeforeBack and stop when it return "false" for example.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  
| react-native     |  
| node             | 
| npm or yarn      |

**Comment by spencercarli** [comment]
[gesturesEnabled](https://reactnavigation.org/docs/navigators/stack#gesturesEnabled) should do the trick!
