### ISSUE TITLE
Updated to 1.0.0-beta.9 ,ListView not render the row until drag the page.

### ISSUE THREAD

**Issue by guoliang1206** [react-community/react-navigation#1338]
Two screen in the TabNavigator
screen 1: listView 
screen 2: listView 

if  I start the app, ListView on screen 1 render correctly, when I tab screen2, it is show nothing only a background , until I little drag the page, all item will be render.

```
 "react": "16.0.0-alpha.6",
    "react-native": "0.43.3",
    "react-native-maps": "^0.13.1",
    "react-navigation": "1.0.0-beta.9",
    "react-redux": "^5.0.4",
    "redux": "^3.6.0",
    "redux-persist": "^4.6.0",
    "redux-storage": "^4.1.2"
```

**Comment by skyworld** [comment]
I also have this problem

**Comment by skyworld** [comment]
I have this problem , too!

**Comment by guoliang1206** [comment]
and is it correctly when tap tabs?
```
 case NAVIGATION_NAVIGATE:{
            console.log('excute navigate operator ......');
            return AppNavigator.router.getStateForAction(NavigationActions.navigate({routeName:action.routeName}), state);
        }
```

**Comment by guoliang1206** [comment]
another question, how to find the new API guide? Does the website update it ?

**Comment by fangkyi02** [comment]
Similar to my question
I used flatlist in multiple tab
I set lazy:true
Other pages can be displayed after the normal flatlist but the initialization page still can not be displayed
If you do not add this set of all use the flatlist page can not be displayed properly
I mentioned this question a few days ago, but no one has ever looked at it

**Comment by fangkyi02** [comment]
I found all the tab related problems I have encountered
Occurs on a page that is nested with tab
List the problems I encountered

1.tab nested page can not be displayed properly

2.tab nested flatlist or listview can not be displayed but other components can be displayed

3.tab nesting causes this.props.navigation.navigate to execute the command as a result of the false but it can be used outside the call

4.tab nested on the above problem that can not be displayed by disabling the slide although it shows that in addition to the contents of the page, but it can not slide

**Comment by MovingGifts** [comment]
@guoliang1206 @fangkyi02 To your `ListView/ScrollView/FlatList` that do not show up, add this property: `removeClippedSubviews={false}`

That's how I was able to get mine to show up.

**Comment by cooperka** [comment]
Dupe: https://github.com/react-community/react-navigation/issues/368.

**Comment by dayudodo** [comment]
it's ListView bug: (https://github.com/facebook/react-native/issues/1831)
quick solution, add removeClippedSubviews property
```
 render() {
    return (
      <View style={{ flex: 1, justifyContent:'center'}}>
        <ListView
          dataSource={this.state.dataSource}
          renderRow={this._renderRow.bind(this)}
          removeClippedSubviews={false}
        />
      </View>
    );
  }
```

**Comment by guoliang1206** [comment]
thanks everyone .

**Comment by skyworld** [comment]
你可以在relase里面找到最新版本的API的变动

**Comment by jasan-s** [comment]
IS anyone else having performance issue with large lists with images after setting `removeClippedSubViews={false}`.

**Comment by razor1895** [comment]
@jasan-s you could try [VirtualizedList](https://facebook.github.io/react-native/docs/virtualizedlist.html)

> removeClippedSubviews might not be necessary and may cause bugs. If you see issues with content not rendering, try disabling it, and we may change the default there.

**Comment by petersuwara** [comment]
@razor1895, still happens with VirtualizedList, FlatList and SectionList.
