### ISSUE TITLE
TabNavigator, when keyboard open, does not navigate on first swipe or on first tabbar tap.

### ISSUE THREAD

**Issue by FreddieOD** [react-community/react-navigation#1339]
Hi

I'm sure someone must have found this issue before but I can't find it amongst the issues.

### Current Behavior
I have a TabNavigator inside a StackNavigator inside a DrawerNavigator:

Drawer:{
---Stack:{
------TabNavigator:{
---------screen1:{//config},
---------screen2:{//config}
------}
---}
}

When I swipe from screen1 to screen2 while the keyboard is showing the screen jumps back to screen1 and hides the keyboard. On second swipe, when keyboard is no longer showing, the swipe works as expected and I transition to screen2 smoothly. If I click on the actual tab in the tabbar, the only behaviour is that the keyboard hides. On second tap, when keyboard is hidden, the navigator take me to screen2 as expected.

### Expected Behavior
My suggestion is that on swipe the keyboard either stays put when transitioning to screen2, or it disappears without switching back to screen1 and removing keyboard.

Currently I am creating my own custom tabbar so that tapping a tab does navigate while removing keyboard. However the issue persists with swiping. On swipe, when keyboard is open, it jumps back to screen1.

Have I explained this correctly? I hope it's clear.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.7
| react-native     |  0.42.0
| node             |  v6.0.0
| npm or yarn      | 3.8.6

**Comment by rkostrab** [comment]
**Here's simple code to replicate issue. (1.0.0-beta.11)**

```
import React from 'react';
import { TabNavigator } from 'react-navigation';
import { AppRegistry, Text, View, TextInput } from 'react-native';

var Foo = React.createClass({

  render: function() {
    return (
      <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center'}}>
        <Text>Foo</Text>
        <View style={{ flexDirection: 'row'}}>
          <TextInput style={{flex: 1}} placeholder="Tap here to show keyboard then swipe to bar tab"/>
        </View>
      </View>
    );
  },

});

var Bar = React.createClass({

  render: function() {
    return (
      <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center'}}>
        <Text>Bar</Text>
      </View>
    );
  },

});

const App = TabNavigator({
  Foo: {
    screen: Foo,
  },
  Bar: {
    screen: Bar,
  },
});

var TestProject = React.createClass({
  render: function() {
    return (
      <App />
    );
  }
});

AppRegistry.registerComponent('TestProject', () => TestProject);
```

**Comment by kelset** [comment]
Pinging OP @FreddieOD since this issue is quite old and related to an old version of the lib. If no answer I'll close in 7 days.

**Comment by kelset** [comment]
Hi there @FreddieOD,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue (especially if it's a bug report) please open a new issue that uses the new Issue Template to provide some more details to help us solve it.

**Comment by FreddieOD** [comment]
Hi @kelset 

Very sorry for my silence!

I will check out the latest versions and do as you suggest if needed. Thank you.

**Comment by kelset** [comment]
Hey no problems. I suggest you test against master, we recently merged a PR related to how the keyboard interact with tabs (https://github.com/react-community/react-navigation/pull/1764)

**Comment by FreddieOD** [comment]
Ok thanks for the good work!
