### ISSUE TITLE
Set headerBackTitleStyle for StackNavigator

### ISSUE THREAD

**Issue by ludovic-coder** [react-community/react-navigation#1340]
### Current Behavior
Using a StackNavigator embed in a TabNavigator, defining the props 'headerBackTitleStyle' doesn't have any effect on back title. The color still the iOS default one.

<img width="374" alt="capture d ecran 2017-05-02 a 14 24 17" src="https://cloud.githubusercontent.com/assets/1408955/25617603/66962e9c-2f43-11e7-88ec-3445d8526cad.png">

#### Style

    let styles = StyleSheet.create({
        back: {
            backgroundColor: Colors.default.darkGray,
            color: Colors.default.white,
            fontFamily: "Lato-Regular",
        }

    });

#### StackNavigator

    export const HomeNav = StackNavigator({
        Home: {
            screen: Home,
            navigationOptions: {
                headerStyle: styles.header,
                headerBackTitleStyle: styles.back,
                title: "Home",
            },
         Detail: {
            screen: Detail,
            navigationOptions: {
                headerStyle: styles.header,
                headerBackTitleStyle: styles.back,
                title: "Detail",
            },
        },
    });

#### TabNavigator

    export const Tabs = TabNavigator({
        Home: {
            screen: HomeNav,
            navigationOptions: {
                tabBarLabel: 'Home',
                tabBarIcon: ({ tintColor }) =>
                    <Image
                        source={require('../assets/images/home/home.png')}
                        style={[styles.icon, {tintColor: tintColor}]}
                    />
            },
        },
        Stats: {
            screen: Stats,
            navigationOptions: {
                tabBarLabel: 'Mes finances',
                tabBarIcon: ({ tintColor }) =>
                    <Image
                        source={require('../assets/images/stats/stats.png')}
                        style={[styles.icon, {tintColor: tintColor}]}
                    />
            },
        },
    }, {
        tabBarOptions: {
            style: styles.tab,
            activeTintColor: Colors.default.white,
            inactiveTintColor :Colors.default.mediumGray
        },
    });

### Expected Behavior
The defining style should change the back buttons style

### Your Environment
Using iOS 10.3, same thing on simulator or devices.

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0 beta9
| react-native     |  0.44
| node             | 7.7.1
| npm      | 4.1.2

**Comment by koenpunt** [comment]
This has not been released yet, so currently only available on `master`

**Comment by keplersj** [comment]
I'm sure this is redundant, but the same happens on Android. The back button stays Black.

**Comment by njt1982** [comment]
This was asked a while ago in #429 I think, too...

**Comment by njt1982** [comment]
@koenpunt Will this be in beta10?

**Comment by sphism** [comment]
@ludovic-coder headerTintColor appears to change the back button icon and text to whatever color you set it to.

**Comment by Tiendq** [comment]
@koenpunt I got same issue too, did you mean that `headerBackTitleStyle` in `master` works as documented?

**Comment by fabriziomoscon** [comment]
This is working for me:
`"react-navigation": "^1.0.0-beta.11"`

```
navigationOptions: {
        headerStyle: {
            backgroundColor: 'black',
        },
        headerTitleStyle: {
            color: 'white',
        },
        headerBackTitleStyle: {
            color: 'white',
        },
        headerTintColor: 'white',
}

**Comment by keplersj** [comment]
@fabriziomoscon Fixes my issue! Thanks!

**Comment by lokesh755** [comment]
headerBackTitleStyle is working only for backTitle but not the back arrow. I'm not sure whether it's issue or it's working as per design.

**Comment by James-Byrne** [comment]
@lokesh755 setting the `headerTintColor` changes the back button for me although you pass it a string rather than an object as shown in @fabriziomoscon comment just above.

**Comment by ArtixZ** [comment]
Just wondering where can I find docs for **navigationOptions**.

**Comment by abeddow91** [comment]
@ArtixZ , you can find them here: https://reactnavigation.org/docs/navigators/stack#Screen-Navigation-Options

**Comment by jkuczek15** [comment]
Has anyone figured out a way to style the back button? I'd like to change the margin instead of the color.

**Comment by mgscreativa** [comment]
Hi, please take a look at this post https://github.com/react-navigation/react-navigation/issues/1104#issuecomment-362396677

**Comment by ArtemKha** [comment]
RN doesn't support [namedColors] like 'white'

navigationOptions: {
        headerStyle: {
            backgroundColor: '#000',
        },
        headerTitleStyle: {
            color: '#fff',
        },
        headerBackTitleStyle: {
            color: '#fff',
        },
        headerTintColor: '#fff',
}

**Comment by koenpunt** [comment]
> RN doesn't support [namedColors] like 'white'

It actually does: https://facebook.github.io/react-native/docs/colors.html#named-colors

**Comment by lylest** [comment]
> This is working for me:
> `"react-navigation": "^1.0.0-beta.11"`
> 
> ```
> navigationOptions: {
>         headerStyle: {
>             backgroundColor: 'black',
>         },
>         headerTitleStyle: {
>             color: 'white',
>         },
>         headerBackTitleStyle: {
>             color: 'white',
>         },
>         headerTintColor: 'white',
> }
> ```

THIS HAS WORKED FOR ME 100%

**Comment by DkReactNative** [comment]
Try this it will solve your issue
headerStyle: {
        borderBottomWidth: 0
      },
