### ISSUE TITLE
custom header

### ISSUE THREAD

**Issue by 77ukhtar** [react-community/react-navigation#1347]
so I have nested TabNavigator inside StackNavigator and I want to add custom elements on the header or to hide the header and use my own header and make **my own header to be on top of TabNavigator.**

so is there an option for reordering the positions or to put custom components inside the header?
![header](https://cloud.githubusercontent.com/assets/15893922/25645674/12853b2e-2fb9-11e7-8aae-31fae941479a.png)

**Comment by 77ukhtar** [comment]
I couldn't find a way to modify the header the way I want so what I did is I exported the TabNavigator  and I used it in new component file just like any component  and I have put my header on top of it and then I used this new component on the StackNavigator and I made the header null .

so problem solved 
**if you want to customize the position of the TabNavigator just export it and position it manually in your component.**
I can't believe it took me so long to figure this out XD

**Comment by chrisbastian** [comment]
hey, how yo can do this?, please.

**Comment by 77ukhtar** [comment]
@chrisbastian  what you need exactly? what stopped you
