### ISSUE TITLE
Animate effect not  good when switch navigating between header and no-header

### ISSUE THREAD

**Issue by roselind** [react-community/react-navigation#1351]
The original animate have  a little ‘ obtuse ’  when switch navigating between header and no-header
What can I do to improve it ?

![navigation](https://cloud.githubusercontent.com/assets/9067932/25655132/65535652-3026-11e7-9b92-364ead97a32d.gif)

**Comment by spencercarli** [comment]
Try the different headerModes available - I've found that to help for me
