### ISSUE TITLE
View.propTypes has been deprecated

### ISSUE THREAD

**Issue by sargunv** [react-community/react-navigation#1352]
I'm using React Native 0.44 with React Navigation 1.0.0-beta.9 and I'm getting the warning "View.propTypes has been deprecated and will be removed in a future version of ReactNative. Use ViewPropTypes instead." when using a TabNavigator.

Relevant commit (I think): https://github.com/facebook/react-native/commit/53905a537a58d028fc5eb1c4e9a8ec967d8cd396

**Comment by hdsenevi** [comment]
Yep, seeing the same thing. I'm using 
- react-native : "0.44.0",
- react-navigation : "^1.0.0-beta.9",

**Comment by JeremyZheng** [comment]
very annoying...

**Comment by chetankotkar** [comment]
+1

**Comment by tulin745** [comment]
me too

**Comment by rodriguesbreno** [comment]
I see this warning everywhere, many components that I use in react native throw it, and most of then don't even use View.propTypes at all (or even use a component that use it),
Any ideas how this warning can be fixed? I'll be happy to explore the ideas and submit a PR here too.

**Comment by zhaiyjgithub** [comment]
me too.

**Comment by ztplz** [comment]
same problem

**Comment by tslearn** [comment]
me too.

**Comment by cielu** [comment]
强迫症的原因，有个警告很不舒服，所以找到了该文件，把他改掉就行。
目录：node_modules/react-native-tab-view/src/TabViewAnimated.js 第78行，的View.propTypes 改成 ViewPropTypes ，并且在第5行的导入中，增加ViewPropTypes的导入

replace View.propTypes to ViewPropTypes in file node_modules/react-native-tab-view/src/TabViewAnimated.js at line 78 , and import ViewPropTypes at line 5

**Comment by keeleycarrigan** [comment]
Getting really angry with React Navigation. NavigationExperimental has officially been removed in RN 0.44 and I can't even get an example project running properly by just running `yarn add react-navigation`. I have to specifically point it at that project's master. I guess my app is stuck at RN 0.43 because everything isn't ready to port. This is terrible.

**Comment by mhmdfy** [comment]
I have the same problem, and I would rather not have to modify files in node_module folder as it is usually not tracked.

**Comment by hdsenevi** [comment]
I know this is not a fix, but I didn't want to dismiss this warning all the time when I was testing so I ended up doing the following. Hope it helps someone.

> console.ignoredYellowBox = ['Warning: View.propTypes'];

**Comment by slonak79** [comment]
We're also seeing this warning.

```  console.error node_modules/react-native/Libraries/Core/ExceptionsManager.js:71
    Warning: View.propTypes has been deprecated and will be removed in a future version of ReactNative. Use ViewPropTypes instead.
```

`react-native@0.44.0`
`react-navigation@1.0.0-beta.7 `

**Comment by xavieracostapolo** [comment]
esta solución me funciono  @cielu "replace View.propTypes to ViewPropTypes in file node_modules/react-native-tab-view/src/TabViewAnimated.js at line 78 , and import ViewPropTypes at line 5". tambien remplace en todos los archivos lo mismo, me guiaba con el stacktrace del warning. eso me indicaba donde remplazar. saludos

**Comment by razki** [comment]
Update this please

**Comment by Lexiwu** [comment]
Replace View.propTypes  to ViewPropTypes in all plugins you used.
That's how I fixed!

**Comment by valleywood** [comment]
Same problem for me

**Comment by samstr** [comment]
+1

**Comment by keeleycarrigan** [comment]
I think this is something in `react-native-tab-view`. When I made my own tab view based off what is going on in that this warning went away. Not sure, but just noticed that.

**Comment by larryranches** [comment]
+1

**Comment by skevy** [comment]
Should be released in 1.0.0-beta.10, as we've upgrade react-native-tab-view.

**Comment by chenyi5266** [comment]
in   node_modules/react-native-tab-view/src        and        node_modules/react-native-tab-navigator

all  JS files   which  have  "View.propTypes"   ,   should       import { ViewPropTypes } from 'react-native'      and           replace View.propTypes to ViewPropTypes

**Comment by Abdul-majid-ashrafi** [comment]
Some problem

**Comment by matt-oakes** [comment]
This still seems to be present in 1.0.0-beta.11.

**Comment by Abdul-majid-ashrafi** [comment]
Please solve this issue.
Thanks

**Comment by litrosas7** [comment]
I had ViewPropTypes warning because of react navigation. Using npm install --save react-navigation@1.0.0-beta.10 solve my problem ;)

**Comment by Irosshipaz** [comment]
Any solution for this?

**Comment by jhalborg** [comment]
Still seeing this warning with a tab navigator on 1.0.0-beta.11

**Comment by iyotee** [comment]
npm uninstall native-base

and then reinstall the new version 

npm install native-base --save

You all welcome :)

**Comment by axten** [comment]
me to

**Comment by BenBenz** [comment]
Have you a concrete example ?

**Comment by kelset** [comment]
Can it be that it is caused by `babel-plugin-flow-react-proptypes` plugin - that can be found in `package.json`?

According to the [original repo](https://github.com/brigand/babel-plugin-flow-react-proptypes/releases/tag/v3.4.1), its latest version is 3.4.1 while the one in the package.json of this lib is 2.2.2.

**Comment by matt-oakes** [comment]
The cause is listed above by @cielu: The `react-native-tab-view/src/TabViewAnimated.js` `react-native-swiper/src/index.js` files are using a deprecated property and hense is generating a warning. 

To fix this issue:
- [ ] Those libraries need to be updated to use the new `ViewPropTypes`.
- [ ] This library needs to be updated to use the newly updated dependencies.

**Comment by warka0** [comment]
I hope it will be fixed quickly because it's really annoying! :)

**Comment by kelset** [comment]
I think `react-native-tab-view` v0.0.67 fixes its portion of the issue (released yesterday-ish); @matt-oakes I can't find the dependency on `react-native-swiper` in this lib :/

**Comment by ItsMeVlad** [comment]
Has there been any progress with this? Updating to ```1.0.0-beta.11``` does not fix the warning.
Like @kelset, I too cannot find a dependency to ```react-native-swiper```

This has been open for a while and also marked as a bug, it would be great if we could get a fix out for this!

**Comment by junajan** [comment]
+1

**Comment by nhducit** [comment]
there are code mod to do it automatically
https://github.com/reactjs/react-codemod#reactnative-view-proptypes

**Comment by matt-oakes** [comment]
I actually think that all the dependencies on this library have not been fixed and this issue doesn't come up anymore.

In my case, I was still seeing the warning, but it was actually due to another library which is not brought in by React Navigation. In my case it was `react-native-google-signin`.

To see where it's coming from, take a look at the stack trace of the warning:

<img width="1462" alt="screenshot 2017-08-09 22 29 49" src="https://user-images.githubusercontent.com/97068/29144864-83ecedca-7d52-11e7-9761-c31cf3b9d7d6.png">

As far as I can tell, this issue has been fixed for this library and should be closed. Someone, please correct me if I'm wrong, however!

**Comment by AlanFoster** [comment]
I can confirm that the latest version of react-navigation has fixed this issue :+1:

---

If you're wanting to know what libraries you depend on that need upgraded:

I was getting this warning within my jest tests, and I was able to work out which modules were failing via editing `node_modules/react-native/Libraries/Core/ExceptionsManager.js` to have:

```diff
   function reactConsoleErrorHandler() {
+   console.log(new Error().stack);
    console._errorOriginal.apply(console, arguments);
    if (!console.reportErrorsAsExceptions) {
      return;
    }

    if (arguments[0] && arguments[0].stack) {
      reportException(arguments[0], /* isFatal */ false);
    } else {
    ...
```

That way my tests output the stack containing the libraries that needed to be updated:

```shell
console.log node_modules/react-native/Libraries/Core/ExceptionsManager.js:71
  Error
      at BufferedConsole.reactConsoleErrorHandler [as error] (/app/node_modules/react-native/Libraries/Core/ExceptionsManager.js:71:13)
      at printWarning (/app/node_modules/fbjs/lib/warning.js:36:17)
      at warning (/app/node_modules/fbjs/lib/warning.js:60:22)
      at Function.get [as propTypes] (/app/node_modules/react-native/Libraries/Components/View/View.js:184:1)

      at Object.<anonymous> (/app/node_modules/react-native-modal-datetime-picker/src/CustomDatePickerIOS/index.js:98:341)
                   ^^^ This is the component that needs upgraded

      at Runtime._execModule (/app/node_modules/jest-runtime/build/index.js:447:13)
      at Runtime.requireModule (/app/node_modules/jest-runtime/build/index.js:295:14)
      at Runtime.requireModuleOrMock (/app/node_modules/jest-runtime/build/index.js:365:19)
      at Object.<anonymous> (/app/node_modules/react-native-modal-datetime-picker/src/index.js:3:26)
      at Runtime._execModule (/app/node_modules/jest-runtime/build/index.js:447:13)
console.error node_modules/react-native/Libraries/Core/ExceptionsManager.js:72
  Warning: View.propTypes has been deprecated and will be removed in a future version of ReactNative. Use ViewPropTypes instead.
```

In this case I had to upgrade `react-native-modal-datetime-picker` and all warnings were gone

**Comment by matt-oakes** [comment]
Great! I think this issue should be closed in that case. For anyone still seeing the warning, use the method above from @AlanFoster to check where it's coming from.

**Comment by sargunv** [comment]
Excellent, thanks!

**Comment by jeremyfrancis** [comment]
ViewStylePropTypes must be used now. I changed them all manually and got it working but it gives me a lot of warnings.

**Comment by ymz2012** [comment]
ViewPropTypes is not defined

**Comment by cmedinasoriano** [comment]
@ymz2012 you should change 
```
import React, { PropTypes } from 'react'
```
to
```
import React from 'react'
import { ViewPropTypes } from 'react-native'
```

**Comment by arunjkumarp** [comment]
How you remove View.propTypes.style. / how find which lib have the issue ?


My project is working in simulator but not in real device.

How i find which library have issue.

"version": "0.0.1",
"private": true,
"scripts": {
"start": "node node_modules/react-native/local-cli/cli.js start",
"test": "jest"
},
"dependencies": {
"axios": "^0.17.1",
"react": "16.0.0-beta.5",
"react-native": "0.49.3",
"react-native-collapsible": "^0.9.0",
"react-native-country-picker-modal": "^0.5.1",
"react-native-dash": "0.0.7",
"react-native-datepicker": "^1.6.0",
"react-native-elements": "^0.17.0",
"react-native-form-validator": "^0.2.0",
"react-native-modal-dropdown": "^0.5.0",
"react-native-router-flux": "^4.0.0-beta.28",
"react-native-vector-icons": "^4.4.2",
"react-navigation": "^1.0.0-beta.13",
"react-redux": "^5.0.6",
"redux": "^3.7.2",
"redux-logger": "^3.0.6",
"redux-persist": "^5.5.0",
"redux-thunk": "^2.2.0",
"rm": "^0.1.8",
"validate.js": "^0.12.0"
},
"devDependencies": {
"babel-jest": "21.2.0",
"babel-preset-react-native": "4.0.0",
"jest": "21.2.1",
"react-test-renderer": "16.0.0-beta.5"
},

**Comment by brentvatne** [comment]
@arunjkumarp - search in node_modules for it and remove. update libraries to latest
