### ISSUE TITLE
How to get navigation params in custom StackNavigator Header

### ISSUE THREAD

**Issue by ariona** [react-community/react-navigation#1353]
How do i get the passed params from custom StackNavigator Header. I've tried this but it return `undefined`

```js
static navigationOptions = {
    header: (props) => {

        const { params } = props.navigation.state
        console.log('Param value: ',params) // <== this return undefined

        return <NavigationHeader {...props} />
    }
}
```

Using Beta 9

**Comment by chrisharrison** [comment]
Header properties are now 'flat' in Beta 9:
https://github.com/react-community/react-navigation/releases/tag/v1.0.0-beta.9

**Comment by spencercarli** [comment]
Hi! In an effort to reduce the number of open issues I'm closing question-type issues that would be a better for the [react-navigation tag on StackOverflow](https://stackoverflow.com/questions/tagged/react-navigation). This is nothing personal, merely trying to get the # of issues to a more manageable level. If you think this issue should be re-opened please let me know. Thanks!
