### ISSUE TITLE
Rerender tab on click

### ISSUE THREAD

**Issue by itswaze** [react-community/react-navigation#1354]
Is it possible to re-render the tab when I click that tab the second time?
For example, I have a tab called "Stock" with a ListView, I scrolled all the way down, but I want to go back up, If I click Stock tab again it will re-render the tab to the top (like instagram works or facebook works). Or If I select an item and I go to its Details Page, clicking again on the tab, will re-render back do parent screen.

Is it possible??

**Comment by ugiacoman** [comment]
Not with the current implementation, I don't think it's on the `v1` roadmap, but people have requested it.

**Comment by xiemeilong** [comment]
+1

**Comment by mazing** [comment]
+1
