### ISSUE TITLE
how to implement 'replace' function?

### ISSUE THREAD

**Issue by npomfret** [react-community/react-navigation#1356]
I'm in the process of swapping out the deprecated react navigation stuff with react-navigation.  

The old api had a `replace` function that allowed me to swap out one route in the stack.  How would I achieve the same thing here?

**Comment by koenpunt** [comment]
Duplicate of:
https://github.com/react-community/react-navigation/issues/774
https://github.com/react-community/react-navigation/issues/295

**Comment by bashirpour** [comment]
import {StackActions} from 'react-navigation';
	import {NavigationActions} from 'react-navigation';

	const resetAction = StackActions.reset({
	    index: 1,
	    actions: [
	    	// add other screen if you want
	        NavigationActions.navigate({routeName: 'screen2'}),
	        NavigationActions.navigate({routeName: 'newScreen'}),
	    ],
	});
