### ISSUE TITLE
headerBackTitle props not working

### ISSUE THREAD

**Issue by saxenanickk** [react-community/react-navigation#1358]
`headerBackTitle` props not working in react-navigation^1.0.0-beta.9 for ios,

```
  static navigationOptions=({navigation})=>({
  title:navigation.state.params.category,
  headerBackTitle:'Back',
  headerRight:(<View style={styles.shareView} >
               <TouchableHighlight style={styles.shareTo} underlayColor='transparent' onPress={() =>navigation.state.params.handleShare() }>
               <Image style={styles.shareIcon} resizeMode='contain' source={{ uri: 'share' }}/>
               </TouchableHighlight>
               </View>)

   })
  
```

**Comment by koenpunt** [comment]
`headerBackTitle` is not taken from the current screen, but from the last screen before it.

**Comment by ms88privat** [comment]
I would like to set it globally on the navigationOptions of the StackNavigator, but it isn't working.

**Comment by saxenanickk** [comment]
@koenpunt Thanks for the above information.

**Comment by Tiendq** [comment]
@koenpunt where does it say we can only set `headerBackTitle` from last screen? [This page](https://reactnavigation.org/docs/navigators/stack#headerBackTitle) says I can set it or leave it `null`.

It doesn't work if I set a value for it, whatever value set to `headerBackTitle`, it becomes Back instead of previous screen's title.

```
static navigationOptions = ({ navigation }) => {
    return {
      title: navigation.state.params.name,
      headerBackTitle: 'Home' // Always Back, not Home
    };
  }
```

**Comment by koenpunt** [comment]
You have to add `headerBackTitle` to the navigation options of the `Home` screen.

```js
const nav = StackNavigator({
  Home: {
    screen: HomeScreen,
    navigationOptions: {
      headerBackTitle: 'Home',
    },
  },
  Details: {
    screen: DetailScreen,
  },
}, {
  // ...
});

**Comment by Tiendq** [comment]
@koenpunt It works, I actually tried and found it out too. But I think it still needs to be clear on the docs that _it's for previous screen, not on current screen_.

Thanks,

**Comment by Liqiankun** [comment]
Set this on  previous screen it will show on current screen! If you wanna no title. Code like this`headerBackTitle: ' '`

**Comment by xaphod** [comment]
That sounds totally broken to me: what if the current screen can navigate to 3 screens depending on what the user chooses, and each of these screens need to have different back button titles? How can I set `headerBackTitle` differently for each?

**Comment by luco** [comment]
+1 on this. Only got it with @Tiendq  explanation. I think it should be clear that you **must** set `headerBackTitle` on the previous Screen to affect the current one.

**Comment by remeryAGS** [comment]
I have the same problem as @xaphod. Multiple routes to other screens and I want the headerBackTitle to be different for each one.

**Comment by myJarvis** [comment]
@remeryAGS  you can set  headerBackTitle for a screen in previous screen , 

eg.)   ScreenA -> Screen B -> Screen C

const screensNavigator = StackNavigator({
  ScreenA: {
    screen: Screen A,
    navigationOptions: {
      headerBackTitle: 'Give Here some title it will be shown in Screen B with back button',
    },
  }, 
  ScreenB: {
    screen: Screen B,
    navigationOptions: {
      headerBackTitle: 'Give Here some title it will be shown in Screen C with back button',
    },
  },
});

**Comment by SamiChab** [comment]
As @xaphod said, it would be nice to allow setting a `headerBackTitle` from each of the screens we navigate to...

**Comment by brentvatne** [comment]
hi there! if this is still a bug can you create a new issue that reproduces the bug on https://snack.expo.io? thanks!
