### ISSUE TITLE
navigationOptions with parametter in beta9 version?

### ISSUE THREAD

**Issue by ramsestom** [react-community/react-navigation#1361]
With react-navigation before beta9 I defined one of my navigationOptions this way:

```
static navigationOptions = {
    title: 'Sign In',
    header: ({goBack}) => {
      return {
        left: NavIcons.closeButton(goBack)
      };
    }
  };
```

Now this is not working anymore and it crash with the message:
`Objects are not valid as a React child (found: object with keys {left}). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of `View`.`

How am I supposed to transform this navigationOptions object with the beta9 version?

**Comment by ne8il** [comment]
I think this should work:

```javascript
static navigationOptions: ({ navigation}) => ({
  headerTitle: 'Sign In',
  headerLeft: NavIcons.closeButton(navigation.goBack)
})
```
based on the "Breaking Changes" section here: https://github.com/react-community/react-navigation/releases/tag/v1.0.0-beta.9

**Comment by ramsestom** [comment]
Wow. That was a really quick answer. That works. Thanks!
