### ISSUE TITLE
Back button behaviour of custom TabRouter inside StackNavigator

### ISSUE THREAD

**Issue by augustoabreu** [react-community/react-navigation#1362]
Hi guys, i'm developing a app with some behaviours that i think i can't achieve with built-in navigators. This is what i'm trying to implement:

1. My app has mainly 2 sections: login and a tab navigation.
2. The tab bar has 5 components and the last one is used to open a Drawer.

So, i organized something like this:

```
const RootNavigator = StackNavigator({
  SplashScreen: {
    screen: SplashScreen
   },
  IntroScreen: {
    screen: IntroScreen
  },
  LoginScreen: {
    screen: LoginNavigator
  },
  MainScreen: {
    screen: MainNavigationContainer
  }
}, {
  initialRouteName: 'SplashScreen',
  headerMode: 'screen'
});

const MainScreenRouter = TabRouter({
  HomeScreen: {
    screen: HomeNavigator,
    path: 'home'
  },
  ScheduleScreen: {
    screen: ScheduleNavigator,
    path: 'schedule'
  },
  NetworkScreen: {
    screen: NetworkNavigator,
    path: 'network'
  },
  InterestsScreen: {
    screen: InterestsNavigator,
    path: 'interests'
  },
  Drawer: {
    screen: HiddenNavigator,
    path: 'drawer'
  }
}, {
  initialRouteName: 'HomeScreen'
});

const MainNavigationContainer = createNavigationContainer(createNavigator(MainScreenRouter)(TabView));
```

The problem i'm facing is that back button do not appears inside MainNavigationContainer but if navigate from SplashScreen to IntroScreen it appears (the default behaviour is a reset from Splash to Intro/MainScreen).

**Comment by selfeky** [comment]
@augustoabreu 
I'm having the same issue. Did you manage to fix it?

**Comment by augustoabreu** [comment]
@selfeky i have changed my app architecture, so i am no longer using a custom tab bar.
