### ISSUE TITLE
Passing objects between list view screen

### ISSUE THREAD

**Issue by saeropark** [react-community/react-navigation#1364]
Hi 

My current implementation is using React's Navigator and I want to change to this library. 

I am currently pulling JSON object from a URL and I have been passing between navigator
`<FileName navigator={nav} item={route.data} />`

Right now I want to use the '`this.props.navigation.navigate('FileA', {data: item} )`'
but i don't know how. Can someone explain or provide a sample code to aid my understanding?

the flow is:

Tab View
     - TABA
     - TAB B
     - TAB C

Each tab renders a list view and when i click on a list view item, i want to pass object over so that it can be open up to another page. 

Help.

**Comment by FacuAcosta** [comment]
You should be able to see the "data" param on the screen that receives It by using 
`this.props.state.params.data`

**Comment by saeropark** [comment]
@FacuAcosta 

my item is a JSON object. i can just pass it in ? If i understand correctly, they key is a string?

> key - string - required - Route key that should get the new params

**Comment by FacuAcosta** [comment]
@saeropark 
Oh, I thought you were trying to pass a string contained inside the JSON file. I think that you can't pass an object like so, just strings. Maybe using AsyncStorage to save It and the load It  in the next screen?

**Comment by gregblass** [comment]
I'm also trying to figure out the best practice here. I am trying to have my navigations be smooth, so I'd imaging that I would want to load my data when the app first loads, and then either pass it or store it globally? Or is it considered a best practice to import data in each scene?

**Comment by saeropark** [comment]
Hi So now i decided to change it such that I am passing only an id over via navigate('routename', {data: 'jo'})

However, i am facing a problem where it keeps saying 

> undefined is not an object, error at this.props.navigation.navigate

Below are my codes. Basically
When I touch on a listview item, i will pass from eventlist to eventdetail. but i keep getting error. can anyone help?

`
import { StackNavigator, navigate } from 'react-navigation';
import { TabNavigator } from "react-navigation";

//========= MAIN TABS: UPCOMING | PAST =============
class UpcomingTab extends React.Component {
    static navigationOptions = {
        tabBarLabel: 'Upcoming'
    }
  render() {
    return <EventList/>
  }
}

class PastTab extends React.Component {
    static navigationOptions = {
        tabBarLabel: 'Past'
    }
  render() {
    return <Text>List of Past Events</Text>
  }
}

//======= UNDER UPCOMING TABS ==============
class EventList extends React.Component {

  ..
    render() {
      //const { navigate } = this.props.navigation;
        return (
            <ListView
                dataSource = {this.state.dataSource}
                renderRow = {this.renderEvent.bind(this)}
                style = {styles.listView}
            />
        );
    }
    renderEvent(event) {
        return (
           <TouchableHighlight 
                onPress={() => this.props.navigation.navigate('EventTab',  {}, {
                        type: "Navigate", 
                        routeName: "EventList",
                        action: {
                            type: "Navigate", 
                            routeName: "EventDetail", 
                            params: {data: "Jo"}
                        }
                })}  underlayColor='#dddddd'>
                <View>
                    <View style = {styles.container}>
                            <View style = {styles.rightContainer}>
                            <Text style = {styles.title}> {event.title}</Text>
                            <Text style = {styles.detail}>{event.description}</Text>
                        </View>
                    </View>
                    <View style = {styles.separator}/>
                </View>
            </TouchableHighlight>
        );
    }
} 


class EventDetail extends React.Component {
    static navigationOptions = ({ navigation }) => ({
    title: `Title: ${navigation.state.params.data}`,
    });
    
     render() {
        const {params} = this.props.navigation.state;
        return (
            <View style={styles.container}>
                <ScrollView>
                <View style={styles.contentContainer}>
                        <Text> Title?: {params.data}</Text>
                    </View>
                </ScrollView>
        </View>
        );
       
    }
}
    

const EventTab = TabNavigator({
    Upcoming: { screen: UpcomingTab },
    Past: { screen: PastTab },
    // List: {screen: EventList},
    // Info: {screen: EventDetail},
},
    { mode: 'modal' } // this is needed to make sure header is hidden on ios
);

const EventStack = StackNavigator({
    Home: {screen: EventTab},
    List: {screen: EventList},
    Info: {screen: EventDetail},
})

EventTab.navigationOptions = {
  header: null,

};
`

**Comment by saeropark** [comment]
Hi i have finally solved this issue of passing objects using the state props. Another issue in this community actually helped me saw my problem. 

My newly updated code and it works:


```
import { StackNavigator, navigate } from 'react-navigation';
import { TabNavigator } from "react-navigation";

//========= MAIN TABS: UPCOMING | PAST =============
class UpcomingTab extends React.Component {
    static navigationOptions = {
        tabBarLabel: 'Upcoming'
    }
  render() {
    return <EventList/>
  }
}

class PastTab extends React.Component {
    static navigationOptions = {
        tabBarLabel: 'Past'
    }
  render() {
    return <Text>List of Past Events</Text>
  }
}

//======= UNDER UPCOMING TABS ==============
class EventList extends React.Component {

  ..
    render() {
        return (
            <ListView
                dataSource = {this.state.dataSource}
                renderRow = {this.renderEvent.bind(this)}
                style = {styles.listView}
            />
        );
    }
   
    renderEvent(event) {
        return (
           <TouchableHighlight 
                onPress={() => this.testOnPress(event)}>
                <View>
                    <View style = {styles.container}>
                        <View style = {styles.rightContainer}>
                            <Text style = {styles.title}> {event.title}</Text>
                            <Text style = {styles.detail}>{event.description}</Text>
                        </View>
                    </View>
                    <View style = {styles.separator}/>
                </View>
            </TouchableHighlight>
        );
    }

    testOnPress(event) {
        console.log("TestonPress");
        this.props.navigation.navigate('Info', {event});
    }

} 


class EventDetail extends React.Component {
     render() {
        const {params} = this.props.navigation.state;
        return (
            <View style={styles.container}>
                <ScrollView>
                <View style={styles.contentContainer}>
                        <Text> Title?: {params.event.title}</Text>
                    </View>
                </ScrollView>
        </View>
        );
       
    }
}
    

const AnnStack = StackNavigator({
    List: {screen: EventList},
    Info: {screen: EventDetail},
    
},
 { mode: 'modal' } // this is needed to make sure header is hidden on ios
 );
 AnnStack.navigationOptions = {
  header: null,

};


const EventTab = TabNavigator({
    Upcoming: { screen: AnnStack },
    Past: { screen: PastTab },
},
    { mode: 'modal' } // this is needed to make sure header is hidden on ios
);

const EventStack = StackNavigator({
    Home: {screen: EventTab},
    // List: {screen: EventList},
    // Info: {screen: EventDetail},
},

export default EventStack;

```
