### ISSUE TITLE
Application <appname> has not been registered

### ISSUE THREAD

**Issue by Jahans3** [react-community/react-navigation#1366]
### Current Behavior
When I run the app it says "Application <my app> has not been registered" and I am unable to continue.

I am following the initial instructions at https://reactnavigation.org/docs/intro/, my code is slightly different, however even when copying the exact code from the tutorial or putting everything inside index.ios.js everything stil fails.

index.ios.js:

`import './src'`

src/index.js:

```
import React, { Component } from 'react'
import { AppRegistry } from 'react-native'
import { Text, View } from 'native-base'
import { StackNavigator } from 'react-navigation'

class TestScreen extends Component {
  static navigationOptions = {
    title: 'Test Title'
  }

  render () {
    return (
      <View style={{ flex: 1 }}>
        <Text>Hello, Navigation!</Text>
      </View>
    )
  }
}

const TestApp = StackNavigator({
  Home: { screen: TestScreen }
})

AppRegistry.registerComponent('TestApp', TestApp)

```

### Expected Behavior
The application should start

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.9
| react-native     |  0.44.0
| node             | 7.7.2
| npm or yarn      | yarn, 0.20.3

**Comment by saeropark** [comment]
`AppRegistry.registerComponent('PROJECTNAME', () => TestApp)`

**Comment by samthui** [comment]
Thanks @saeropark , Restarting command prompts did the trick, becoz I've ran another RN app previously.

**Comment by leaphawk** [comment]
This may happen when you rename a package. Make sure that the `getMainComponentNam()` returns your react native app name. i.e. name in` app.json`
