### ISSUE TITLE
screenProps won't pass ref

### ISSUE THREAD

**Issue by sean-macfarlane** [react-community/react-navigation#1367]
I'm trying to pass a ref of a Component to screenProps but it just resolves this.props.screenProps to an empty object
`
          <LoginModal ref={(modal) => { this.modal = modal; }} />`
          `<NavTabBar screenProps={{login: this.modal}} />`

**Comment by spencercarli** [comment]
Hi! In an effort to reduce the number of open issues I'm closing issues that haven't had any activity in a while.

If you think this should be re-opened please let me know or, if you can, re-open it.

If this is a question please consider asking it on StackOverflow ([react-navigation](https://stackoverflow.com/questions/tagged/react-navigation))

Thanks!
