### ISSUE TITLE
Adding A Badge on DrawerView

### ISSUE THREAD

**Issue by riftshock** [react-community/react-navigation#1368]
I was hoping to have a **add a Badge** feature for the **drawer view** like how you add **drawer icon** to **drawer view.** Ex:

  navigationOptions: () => ({
          title: 'Dashboard',
          drawerIcon:    IconComponent,
          drawerBadge:  BadgeComponent,
      }),

But if anyone has **bettter work around** for now. It would really be nice of you if you could **share** it to us. **Thank You** ;)

**Comment by Rawphs** [comment]
I've achieved this  by creating a custom component (following the props list in the [docs](https://reactnavigation.org/docs/navigators/drawer#Providing-a-custom-contentComponent)), but replacing the `<DrawerItems />` as a whole instead of wrapping a component around it.

I hope this helps, although I think you might have found a solution by now.

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!

**Comment by scue** [comment]
As you see in https://reactnavigation.org/docs/navigators/drawer, you can custom the `drawerLabel`, like below: 
```
static navigationOptions = {
    drawerLabel: <View style={{flex:1, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between'}}>
        <Text h5 style={{margin: 16, fontWeight: 'bold'}}>
            Home
        </Text>
        <Badge containerStyle={{ backgroundColor: 'violet'}}>
            <Text>3</Text>
        </Badge>
    </View>,
};
```
![qq20171022-020255](https://user-images.githubusercontent.com/2650439/31854531-83f4910a-b660-11e7-90f4-dea9af6139f9.png)
