### ISSUE TITLE
StackNavigator inside TabNavigator

### ISSUE THREAD

**Issue by shahankit** [react-community/react-navigation#1369]
Thank you for creating this library. Really nice navigation library with awesome documentation. I followed the Nesting Navigators doc which shows how to nest TabNavigators in StackNavigator. I tried similar approach for having a StackNavigator inside TabNavigator but it doesn't work. I searched for issues but couldn't find anything related to this. I have the following screen setup. 

```
StackNavigatorMain
  - Login
  - SignUp
  - TabNavigator
    - StackNavigatorNested
      - FirstTabFirstScreen
      - FirstTabSecondScreen
    - SecondTabScreen
    - ThirdTabScreen
  - Settings
```

After implementing this first I saw two navigation bars on FirstTabFirstScreen so I removed the header from StackNavigatorNested:

```js
StackNavigatorNested.navigationOptions = {
  header: null
};
```

Everything looks fine on first screen but when I switch to second tab somehow the app enters into infinite loop and keeps rendering FirstTabFirstScreen and SecondTabScreen. I couldn't figure what I'm missing for implementing this simple behavior. Can someone link me to any existing issue or comment incase I missed something.

| software         | version
| ---------------- | -------
| react-navigation |  ^1.0.0-beta.9
| react-native     |  0.43.4
| node             | 7.9.0
| yarn      | 0.23.2

**Comment by saeropark** [comment]
Hi, I did this last night. Not quite sure what you are asking but this is what i have:
`
const FoodTab = TabNavigator({
  Venue: { screen: VenueTab },
  Directory: { screen: DirectoryTab },
},
    { mode: 'modal' } // this is needed to make sure header is hidden on ios

);

const FoodStack = StackNavigator({
    Home: {screen: FoodTab}
})

FoodTab.navigationOptions = ({navigation})=> ({
  header: null,
  style: {
    backgroundColor: '#b510d3',
  }, 
});

export default FoodStack;`

**Comment by shahankit** [comment]
@saeropark my issue is that if the `Venue: { screen: VenueTab }` is replaced with `Venue: { screen: StackNavigator({ VenueMainScreen: { screen: VenueTab } })}`, then it goes into an infinite loop when I navigate between VenuTab and DirectoryTab.

**Comment by zakster12** [comment]
@shahankit You can see my approach here  https://github.com/react-community/react-navigation/issues/325  which is similar to yours.

**Comment by shahankit** [comment]
@zakster12 My issue is not regarding resetting the navigator. Suppose in your example if replace `TabOneNavigation` with a `StackNavigator({ MainScreenTabOne: { screen: TabOneNavigation } })` then navigating between tabs enters infinite loop.

**Comment by zakster12** [comment]
@shahankit I know that this is not your issue. I just pointing you so you can see my structure. This is how TabOneNavigation is looking like:

```
const routeConfiguration = {
	SubTab1: { screen: GetTicket },
	SubTab2: { screen: SubTab2 },
};

const stackNavigatorConfiguration = {
	headerMode: 'screen',
	initialRoute: 'GetTicket'
};

export const NavigatorTabOne = StackNavigator(routeConfiguration, stackNavigatorConfiguration);
```

**Comment by shahankit** [comment]
okay @zakster12 I'll try this and let you know if this configuration solves the issue. Thanks for help.

**Comment by mehtamanan** [comment]
I have the exact same structure and things are working fine for me except the default back button! It just doesn't go back a screen but if I do navigation.goBack(), it works fine

Anyone else facing this issue?

**Comment by debrice** [comment]
@shahankit you've closed this ticket, what was the solution to your problem ?

**Comment by shahankit** [comment]
I actually didn't solve the problem. I made my navigation stack flat instead of nested. Just try zakster12's solution. It might help.

**Comment by sujitpk-perennial** [comment]
I am able to work on same functionality using 
https://reactnavigation.org/docs/intro/nesting
