### ISSUE TITLE
onNavigationStateChange at v1.0.0-beta9

### ISSUE THREAD

**Issue by dzuncoi** [react-community/react-navigation#1370]
As release docs said:

> It is no longer possible to subscribe to state changes for navigators that receive their navigation prop from outside, e.g. from Redux or a parent navigator.

So we no longer can detect `prevState`,  `newState`?
Are there any reasons for this removal? And how can we detect when new state (tab/stack...) is coming, in this version?

**Comment by TyrealGray** [comment]
I use **componentWillReceiveProps(nextProps)** to compare tab index(I am using redux also).

```
class Navigation extends React.Component {

	shouldComponentUpdate(nextProps, nextState) {
		return nextProps.navigationState.index !== this.props.navigationState.index;
	}

	componentWillReceiveProps(nextProps) {
		const nextTabIndex = nextProps.navigationState.index;

		if (nextTabIndex !== this.props.navigationState.index && nextTabIndex === TAB_INVITATION_INDEX) {
			this.refresh();
		}
	}

	refresh(){
	    //TODO
	}

	render() {
		const {dispatch, navigationState} = this.props;
		return (
			<Navigator
				navigation={
					addNavigationHelpers({
						dispatch: dispatch,
						state: navigationState
					})
				}
			/>
		)
	}
}

export default connect(state => ({
		navigationState: state.Nav,
	}), (dispatch) => ({
		dispatch: dispatch,
		setInvitation: (data) => dispatch(Actions.function(data))
	})
)(Navigation)
```

**Comment by spencercarli** [comment]
Hi! Since this issue has been quiet for a while I'm going to go ahead and close it. If the issue persists in the latest version of React Navigation please re-open!
