### ISSUE TITLE
Android Phone back key issue on router.getStateForAction()

### ISSUE THREAD

**Issue by darin-lao** [react-community/react-navigation#1372]
### Current Behavior

screen Flow1->Flow2 ,Flow2 back on Header back button is success to block black action,But back on Phone Back Key will exit App 
```
const AppStack = StackNavigator(
    {
        Flow1: {
            screen: Flow1,
        },
        Flow2: {
            screen: Flow2,
        },
        Flow3: {
            screen: Flow3,
        },

    },{
        initialRouteName:"Flow1"
    }
);
AppStack.router.getStateForAction = (action, state) => {
    Log('getStateForAction', action, state);
    if (
        state &&
        action.type === NavigationActions.BACK &&
        state.routes[state.index].routeName=='Flow2'
    ){
        // alert('block back alert');
        return null;
    }
    return defaultGetStateForAction(action,state);
};
```
### Expected Behavior

block Android back key event on this issues
### Your Environment

Android OS
| software         | version
| ---------------- | -------
| react-navigation |  1.0.0@beta.9
| react-native     |  0.44.0
| node             | 
| npm or yarn      |

**Comment by darin-lao** [comment]
Is anyone have handle this issues?

**Comment by vjeranc** [comment]
returning `null` means you want to exit the app. if you don't want back action to change your state then return the same state.

**Comment by darin-lao** [comment]
@vjeranc  how to set the action if return the same state and block back key action

**Comment by vjeranc** [comment]
```
if (
    state &&
    action.type === NavigationActions.BACK &&
    state.routes[state.index].routeName=='Flow2'
){
    // alert('block back alert');
    return state;
}
```

This should work.

**Comment by vjeranc** [comment]
Putting snippet below in your MainActivity will prevent back button from killing the activity. I'm not sure when you click the back button, on which screen. The snippet above prevents back button from executing the change or exiting the app if AppStack is the top router.

```java
@Override
public void invokeDefaultOnBackPressed() {
    moveTaskToBack(true);
}
```

**Comment by darin-lao** [comment]
@vjeranc exit app mean finsih MainActivity and AppStack does not  top router status .

```
const TabStack = TabNavigator(
    {
        TabA: {screen: TabA},
        TabB: {screen: TabB},
     }
);

const AppStack = StackNavigator(
    {
        Tab: {
            screen: TabStack ,
        },
        PageA: {
            screen: PageA,
        },
        PageB: {
            screen: PageB,
        },

    },{
        initialRouteName:"Tab"
    }
);
AppStack.router.getStateForAction = (action, state) => {
    Log('getStateForAction', action, state);
    if (
        state &&
        action.type === NavigationActions.BACK &&
        state.routes[state.index].routeName=='PageA'
    ){
        // alert('block back alert');
        return null;
    }
    return defaultGetStateForAction(action,state);
};


```
MainActivity.java 
I have implement double press Android  back key to exit app 

```
@Override
    public void invokeDefaultOnBackPressed() {
        if(System.currentTimeMillis()-mLastDoublePressBackTime<2000){
            super.onBackPressed();
        }else{
            Toast.makeText(this,"click back again to exit app",Toast.LENGTH_LONG).show();
            mLastDoublePressBackTime=System.currentTimeMillis();
        }

    }
```

this init Router Tab and navigate to PageA ,if PageA goBack with Header back button is success to block back Action , but if you click Physical  back key will trigger App exit.

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!

**Comment by manas-gond** [comment]
Sorry but what is "LOG" in above code?
