### ISSUE TITLE
Hiding parent's header

### ISSUE THREAD

**Issue by aalices** [react-community/react-navigation#1373]
I have a `DrawerNavigator` inside `StackNavigator` - they make double header so I had the solution that `StackNavigator` had `header.visible` set to `null`. Now, as the `visible` property has been removed I can't set the header to be visible on some children screens of the `Stack`. What should I do to achieve this?

**Comment by saeropark** [comment]
`const FoodTab = TabNavigator({
Venue: { screen: VenueTab },
Directory: { screen: DirectoryTab },
},
{ mode: 'modal' } // this is needed to make sure header is hidden on ios

);

const FoodStack = StackNavigator({
Home: {screen: FoodTab}
})

FoodTab.navigationOptions = ({navigation})=> ({
header: null,
style: {
backgroundColor: '#b510d3',
},
});`

**Comment by aalices** [comment]
@saeropark everything is okay until I open the drawer. The app moves down and there appear a blank header. That's because I need the header in DrawerNavigator. Moreover, I do not want the modal transitions.

**Comment by aalices** [comment]
Ok, setting the Drawer's `navigationOptions` header to `null` and the parent's `headerMode` to `screen`, solved the problem anyway. Don't know why it didn't work before. Thanks!

**Comment by sospedra** [comment]
@aalices you saved our product! <3

**Comment by alextorn** [comment]
Looks like i have the same issue, but can't solve this with your solution. Here is a live example - [snack](https://snack.expo.io/HJC7YHDWf)
