### ISSUE TITLE
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.

### ISSUE THREAD

**Issue by zakster12** [react-community/react-navigation#1374]
After updating to  v1.0.0-beta.9 I have the following error:

![screen shot 2017-05-04 at 3 12 20 pm](https://cloud.githubusercontent.com/assets/25477229/25703013/777b5508-30dc-11e7-80cb-5d78eb36c88b.png)

I read the https://github.com/react-community/react-navigation/releases but can't see to which one is this error related. Can someone pointed me out?

**EDIT:** It happens only in this snippet:

```
const Tabs = TabNavigator(
	{
		TabOneNavigation: { screen: TabOneNavigation },
		TabTwoNavigation: { screen: TabTwoNavigation },
		TabThreeNavigation: { screen: TabThreeNavigation },
	},
	{
		tabBarComponent: props => {
			const backgroundColor = props.position.interpolate({
				inputRange: [0, 1, 2],
				outputRange: ['white', Colors.greenLightGradient, 'white'],
			});

			return (
				<TabView.TabBarTop
					{...props}
					style={{ backgroundColor }}
				/>
			);
		},
	}
);

export default Tabs;
```
More of the error says:

> Check the render method of `tabBarComponent`.

Thank you in advanced!

| software         | version
| ---------------- | -------
| react-navigation |  v1.0.0-beta.9
| react-native     |  0.43

**Comment by aalices** [comment]
Try `import { TabBarTop } from 'react-native'` and use `<TabBarTop ...` instead of `<TabView.TabBarTop...`

**Comment by zakster12** [comment]
@aalices It works perfectly! Thank you so much!!!

**Comment by shrimaliakash** [comment]
I have used following code

**Comment by youbihi** [comment]
Have the same problem here 
<img width="299" alt="capture d ecran 2017-12-16 a 18 18 03" src="https://user-images.githubusercontent.com/5676321/34072766-9150af7e-e28d-11e7-8b6a-3a583832018d.png">



Here is my code:

import React, { Component } from "react";

import { StyleSheet, Text, View, TextInput, Image, BackgroundImage } from "react-native";

import Forecast from "./Forecast";
import OpenWeatherMap from "./open_weather_map";

class WeatherProject extends Component {
  constructor(props) {
    super(props);
    this.state = { zip: "", forecast: null };
  }

  _handleTextChange = event => {
    let zip = event.nativeEvent.text;
    OpenWeatherMap.fetchForecast(zip).then(forecast => {
      this.setState({ forecast: forecast });
    });
  };

  render() {
    let content = null;
    if (this.state.forecast !== null) {
      content = (
        <Forecast
          main={this.state.forecast.main}
          description={this.state.forecast.description}
          temp={this.state.forecast.temp}
        />
      );
    }
    return (
      <View style={styles.container}>
        <BackgroundImage
          source={require("./flowers.png")}
          resizeMode="cover"
          style={styles.backdrop}
        >
          <View style={styles.overlay}>
            <View style={styles.row}>
              <Text style={styles.mainText}>
                Current weather for
              </Text>
              <View style={styles.zipContainer}>
                <TextInput
                  style={[styles.zipCode, styles.mainText]}
                  onSubmitEditing={this._handleTextChange}
                  underlineColorAndroid="transparent"
                />
              </View>
            </View>
            {content}
          </View>
        </BackgroundImage>
      </View>
    );
  }
}

const baseFontSize = 16;

const styles = StyleSheet.create({
  container: { flex: 1, alignItems: "center", paddingTop: 30 },
  backdrop: { flex: 1, flexDirection: "column" },
  overlay: {
    paddingTop: 5,
    backgroundColor: "#000000",
    opacity: 0.5,
    flexDirection: "column",
    alignItems: "center"
  },
  row: {
    flexDirection: "row",
    flexWrap: "nowrap",
    alignItems: "flex-start",
    padding: 30
  },
  zipContainer: {
    height: baseFontSize + 10,
    borderBottomColor: "#DDDDDD",
    borderBottomWidth: 1,
    marginLeft: 5,
    marginTop: 3
  },
  zipCode: { flex: 1, flexBasis: 1, width: 50, height: baseFontSize },
  mainText: { fontSize: baseFontSize, color: "#FFFFFF" }
});

export default WeatherProject;

**Comment by BSThisarasinghe** [comment]
Hi, I got the same error. But I could solve it. I changed only 

import CardSection from './common';

to

import { CardSection } from './common';

Here common is a folder. I import all the files using only index.js file. So, if you have done the same thing , try editing the code like mine.

**Comment by phoenixxd** [comment]
some kind of whitespace that was not the standard white space was left by code I copied from the internet. I removed everything between component tags and it started working

**Comment by dinglihuaalice** [comment]
![image](https://user-images.githubusercontent.com/29767173/55896989-391e2180-5bf2-11e9-9638-c2b0267cc68c.png)
import React from 'react';
import { Card } from 'antd';
import { Router, Route, Link } from 'react-router';
import styles from "../components/Content.css";


export default class Content extends React.Component {
  constructor() {
    super();
    this.state = {
      news: ''
    };
  }

  componentWillMount() {
    var myFetchOptions = {
      method: 'GET'
    };

    fetch("http://localhost:8080/products", myFetchOptions)
      .then(response => response.json())
      .then(json => this.setState({news: json}));
  }


  render() {
    const { news } = this.state;

    const newsList = news.length
      ?
      news.map((newsItem, index) =>
        <li key={index}>
          <Link target="_blank">
            {newsItem.name+ newsItem.id}
          </Link>
        </li>
      )
      :
      '没有加载到任何新闻';

    return (
      <div className={styles.box1}>
        <Card
          title="焦点新闻" headStyle={{ color: "#1D4C90" }}
          extra={<a href="#" style={{ color: "#1D4C90" }}>More</a>}
          style={{ width: 300 }}
        >
          <ul>
            {newsList}
          </ul>
        </Card>
      </div>
    );
  }
}

**Comment by TCCLUCASS** [comment]
import * as React from 'react';
import { Provider } from 'react-redux';
import { createStore, applyMiddleware} from 'redux';
import ReduxThunk from 'redux-thunk';
import { Router, Scene } from 'react-native-router-flux';

import reducers from './app/reducers';

import Autenticacao from './app/views/Autenticacao';

export default class App extends React.Component {

  render() {
    return (
      <Provider store={createStore(reducers, {}, applyMiddleware(ReduxThunk))}>
        <Router hideNavBar="true">
          <Scene key="root">
            <Scene 
                key="autenticacao" 
                component={Autenticacao}
                title="Login"
                initial={true} />
          </Scene>
        </Router>
      </Provider>
    );
  }
}

This error is returning me


*Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
Invariant Violation: Minified React error #130; visit [snack internals]
    at [snack internals]
    at a ([snack internals]
    at Vr ([snack internals]
    at d ([snack internals]
    at f ([snack internals]
    at [snack internals]
    at Ei ([snack internals]
    at Qi ([snack internals]
    at za ([snack internals]
    at Ja (https://s3.us-west-1.amazonaws.com/snack-web-player-staging/34/static/js/2.904b0b11.chunk.js:1:1055682)

https://snack.expo.io/H1WB03fuS
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: rgs[{=undefined.rgs[)=

This error only contains when I run on snack.expo
Someone same tell me what's going on
