### ISSUE TITLE
Drawer items based on redux props

### ISSUE THREAD

**Issue by aalices** [react-community/react-navigation#1375]
I am struggling with creating a Drawer that has some items based on props gathered by redux. I tried to follow #717 and make the exported element a React Component thats returns a Navigator in `render` : 
```
render() {
    const Drawer = DrawerNavigator(routes, {
      initialRouteName: '...',
      contentComponent: props => ...
    });

    return (<Drawer />);
  }
}
```

but there occurs an infinite loop. It does not loop when I remove  redux `connect()` but then of course there are no props. I would appreciate any help.

EDIT: I decided to have completely custom `contentComponent` - without using DrawerItems and want to `routes.map(...)` but it also hangs here.

**Comment by annelorraineuy** [comment]
I had a similar design case and used `contentComponent` for this with no problem. Didn't need <DrawerItems/> either, but just rendered each items on a loop. When clicked, uses `navigate()` to the specific screen with params from redux.

If you'd like help I think you should put more snippets of your code and what the issue really is (what do you mean by hang?). Is it the kind of hang when a component constantly re-renders because of a state change?

**Comment by SamMatthewsIsACommonName** [comment]
I return my routes in a selector, seems to work ok. Not sure if that's any help?

**Comment by aalices** [comment]
Here is what I'm trying to do:
Some list is fetched and kept in props, I want to render items of this list as Drawer items - every item navigates to the same screen but with different param (let's say ID).

Now I added the common screen to Navigator routes but I'm not rendering it - just using when `navigate` on item press. But I cannot test it properly because there is an issue with DrawerNavigator params... The problematic case I can think of is setting 'active' style for these items.

The hanging I was talking about was probably constantly calling `setParams` for some reason. I think some people complained about something similar.

**Comment by badams** [comment]
@SamMatthewsIsACommonName could you provide a basic example of this? I'm not sure how to get the Navigator to update its routes when the selector changes

**Comment by SamMatthewsIsACommonName** [comment]
@badams that really needs to be handled on a case by case basis. If you plan to change the selector value Ideally you want a sub component that is only interested in that one property, and then you can create the drawer navigator in the render method like 
`this.UserDrawerNavigation = DrawerNavigator(this.props.routes, drawerOptions);`
In my case for the component with the drawer is always either an admin or not admin at the time of logging in and mounting the component so those properties never change dynamically and I'm able to put that same code in componentWillMount. 

This issue has some good starting point though https://github.com/react-community/react-navigation/issues/717

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
