### ISSUE TITLE
How to open specific routes as modals.

### ISSUE THREAD

**Issue by jeffreymendez1993** [react-community/react-navigation#1376]
Is there a way to open a specific route within a nested stack with the mode of modal.

**Comment by jeffreymendez1993** [comment]
Made a pr with my workaround fix https://github.com/react-community/react-navigation/pull/1378

**Comment by dackom** [comment]
How do I use this? :)

Where do I need to put mode:'modal' to have it open for specific view and not whole stacknavigator?

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
