### ISSUE TITLE
Support for left & right Elements in TabNavigator

### ISSUE THREAD

**Issue by nico1510** [react-community/react-navigation#138]
The `StackNavigator`'s `navigationOptions` property comes with the nice properties `left` and `right` in order to display custom elements on the side.
Will there also be something similar for the TabNavigator in the future ? I was able to achieve this with some sort of a hack by reducing the width of the tab bar (I set the width with help of the `style` prop inside the `tabBarOptions` prop). This however leads to an issue with the indicator being a bit off. 
See here: 
![bildschirmfoto vom 2017-02-01 19 32 15](https://cloud.githubusercontent.com/assets/5033050/22520852/350e3aa0-e8b6-11e6-8c77-389f42a08041.png)

![bildschirmfoto vom 2017-02-01 19 31 46](https://cloud.githubusercontent.com/assets/5033050/22520836/2915b214-e8b6-11e6-8a43-193d456edb06.png)

The indicator issue rather belongs to the [react-native-tab-view](https://github.com/react-native-community/react-native-tab-view) repository. However I just wanted to open this here because I think a clean solution for this use case would be to implement support for the `left` and `right` properties of `StackNavigator`.

**Comment by satya164** [comment]
if you override the `tabBarComponent` to provide your own component, you'll receive `layout` as a prop. Just subtract the width of your button from `layout.width` before passing to the wrapped tab bar.

**Comment by satya164** [comment]
Your component can be like this,

```js
tabBarComponent: (props) => {
  const nextProps = {
    ...props,
    layout: {
      ...props.layout,
      width: props.layout.width ? props.layout.width - buttonWidth : 0,
    },
  };
  return (
    <View style={{ flexDirection: 'row' }}>
      <MyButtonComponent />
      <TabView.TabBarTop {...nextProps} />
    </View>
  )
}
``

**Comment by nico1510** [comment]
Yes this works perfectly thanks a lot ;) Support for `left` and `right` properties would still be nice because you wouldn't be forced to override the tab bar shadow/elevation like I did in the screenshot above but this fits my needs well enough. Thanks again!

**Comment by GaoStudio** [comment]
@nico1510 Hello ,How to navigate other screen by MyButtonComponent

**Comment by nico1510** [comment]
Basically like this: 
```javascript
export default class TabsComponent extends Component {

    MenuButton = () => (
           <TouchableNativeFeedback onPress={this.props.navigation.navigate(....)} />
    )

    TabBar = (props) => (
        <View style={styles.myTabBarStyle}>
            <this.MenuButton />
            <TabBarTop .... />
        </View>
    )

    render() {
        const Tabs = TabNavigator({...}, {
                tabBarComponent: this.TabBar
            });

        return <Tabs  />
    }
}
```
Of course you also have to pass the navigation prop down to `TabsComponent` from the screen where you have it available.

**Comment by GaoStudio** [comment]
Thanks very much，It works for me
