### ISSUE TITLE
this.props.navigation.navigate in componentDidMount and componentWillMount throws setState errors?

### ISSUE THREAD

**Issue by acomito** [react-community/react-navigation#1383]
### Current Behavior
I have a login screen. Prior to the LoginScreen mounting, I'm checking if the user is logged in (user is passed via props) and then I'm checking local storage to see if user has already done onboarding, and then I'm navigating to the appropriate screen (or staying on the login screen if they is no logged in user).

This setup is causing "can not set state in mounting/unmounted component" errors. If I remove the `this.props.navigation.navigate` call the errors go away... so it must have something to do with navigation. I feel like this setup worked in an earlier version of react-navigation but now I'm on beta9

Has anyone else seen this? Is there a better way to re-route people programmatically before the hit a given screen (in my case, the login screen)?

```
class LoginScreen extends React.Component {

	state = { stillLoading: true }

	 async componentDidMount(){
		if (this.props.screenProps.data && this.props.screenProps.data.user) {
			let onboardingComplete = await AsyncStorage.getItem('onboardingComplete');
			if (onboardingComplete === 'true') {
				this.setState({ stillLoading: false  });
				return this.props.navigation.navigate('main');
			} else {
				this.setState({ stillLoading: false  });
				return this.props.navigation.navigate('welcome')
			}
		}

		this.setState({ stillLoading: false  });
	}
	render(){
		if (this.state.stillLoading) {
			return <LoadingScreen loadingMessage={''} />;
		}
		return (
			<View style={{flex: 1, justifyContent: 'center', alignItems: 'center'}}>
				<LoginForm {...this.props} />
			</View>
		);
	}
}

```
### Your Environment

```
{
  "private": true,
  "main": "main.js",
  "dependencies": {
    "antd-mobile": "^1.1.1",
    "apollo-client": "^1.1.1",
    "expo": "16.0.0",
    "graphql-tag": "^2.0.0",
    "lodash": "^4.17.4",
    "meteor-apollo-accounts": "^2.0.1",
    "react": "16.0.0-alpha.6",
    "react-apollo": "^1.1.2",
    "react-native": "https://github.com/expo/react-native/archive/sdk-16.0.0.tar.gz",
    "react-native-elements": "^0.11.2",
    "react-navigation": "git+https://github.com/react-community/react-navigation.git",
    "react-redux": "^5.0.4",
    "redux": "^3.6.0",
    "redux-devtools-extension": "^2.13.0",
    "redux-form": "^6.6.3",
    "redux-persist": "^4.6.0",
    "redux-thunk": "^2.2.0"
  },
  "devDependencies": {
    "babel-plugin-import": "^1.1.1"
  }
}

```

**Comment by jeffreymendez1993** [comment]
setState has not completed and you have the navigate action completed . Try adding a setTimeout(() => this.props.navigation.naviate) without any duration. This will cause it to be invoked at the end of the que/.

**Comment by acomito** [comment]
Great trick thanks @jeffreymendez1993

**Comment by bristoljon** [comment]
Alternatively `setState()` accepts an optional callback that is triggered after `setState` has been invoked..

`this.setState({ stillLoading: false  }, () => this.props.navigation.navigate('main') );`

[Source](https://facebook.github.io/react/docs/react-component.html#setstate)
