### ISSUE TITLE
How to Set the title for the Drawer when its open?

### ISSUE THREAD

**Issue by msdark** [react-community/react-navigation#1385]
### Current Behavior
<img width="374" alt="captura de pantalla 2017-05-05 a la s 01 00 43" src="https://cloud.githubusercontent.com/assets/282006/25733326/4ebdf25e-312e-11e7-9d4f-682ec62a1d28.png">

The title there says "Loading". but I didn't set that title so not sure where it comes?

### Expected Behavior
Should be able to set the title for the opened drawer
### Your Environment
My Navigators Config

```javascript 
import { StackNavigator } from "react-navigation";

import SigninScreen from "../screens/Signin";
import DrawerNavigator from "./DrawerNavigator";
import LoadingScreen from "../screens/Loading";
import IndicadoresScreen from "../screens/Indicadores";

const AppNavigator = StackNavigator({
  Home: { screen: SigninScreen },
  Tabs: { screen: DrawerNavigator },
  Loading: { screen: LoadingScreen },
  Indicadores: { screen: IndicadoresScreen }
});

export default AppNavigator;

````

```javascript
import { DrawerNavigator } from 'react-navigation';

import SaldosScreen from '../screens/Saldos';
import RetencionesScreen from '../screens/Retenciones';
import OperacionesNavigator from './OperacionesNavigator';
import EjecutivoScreen from '../screens/Ejecutivo';

const TabScreen = DrawerNavigator(
  {
    Saldos: { screen: SaldosScreen },
    Operaciones: { screen: OperacionesNavigator }, //this is a Tab navigator
    Retenciones: { screen: RetencionesScreen },
    Ejecutivo: { screen: EjecutivoScreen }
  },
  {
    initialRouteName: 'Saldos',
    contentOptions: {
      activeTintColor: '#000'
    }
  }
);

export default TabScreen;

```

The string "Cargando" only appears in the `LoadingScreen` 
```javascript
import React from "react";

import navOptions from "./navOptions";
import LoadingView from "../views/Loading";

const LoadingScreen = () => <LoadingView />;

LoadingScreen.navigationOptions = navOptions({ title: "Cargando" });

export default LoadingScreen;

```
```javascript 
import React from "react";
import { Text, View, StyleSheet } from "react-native";
import { Spinner } from "native-base";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center"
  }
});

export const Loader = () => (
  <View style={styles.container}>
    <Spinner color="blue" />
    <Text>Cargando...</Text>
  </View>
);

const LoadingView = () => <Loader />;

export default LoadingView;
```

| software         | version
| ---------------- | -------
| react-navigation |   git+https://github.com/react-community/react-navigation.git
| react-native     |  https://github.com/exponent/react-native/archive/sdk-16.0.0.tar.gz
| node             | v7.7.2
| npm or yarn      | yarn 0.21.3

Where or How Can i set the title for the opened Drawer?

**Comment by ajostergaard** [comment]
How are you switching from LoadingView to 'loaded' view - looks like you are navigating it in some way... Instead, try something like this at the very top of your app:
```
      this.props.loaded
        ? <Navigator />
        : < AppNavigator />
```

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
