### ISSUE TITLE
Wrap CardStack view with a custom component

### ISSUE THREAD

**Issue by ferdicus** [react-community/react-navigation#1386]
Hey there, new to using react-navigation,
sorry if this is super obvious, but I couldn't find a solution to this - or maybe my approach is wrong to begin with.

I'm basically looking to have the [CardStack](https://github.com/react-community/react-navigation/blob/master/src/views/CardStack.js) view wrapped within a container component that is not supposed to change during transition. 
Basically a shell around the router / navigator behavior.

How would I manage something like this?

Thanks in advance, and again sorry if there is an obvious answer to this question, I would be more than grateful if someone can point me to it.

**Comment by spencercarli** [comment]
Hi! In an effort to reduce the number of open issues I'm closing question-type issues that would be a better for for the [react-navigation tag on StackOverflow](https://stackoverflow.com/questions/tagged/react-navigation). This is nothing personal, merely trying to get the # of issues to a more manageable level. If you think this issue should be re-opened please let me know. Thanks!
