### ISSUE TITLE
Possible to 'redraw' the header again ? Change navigationOptions dynamically ?

### ISSUE THREAD

**Issue by Gys** [react-community/react-navigation#1389]
For some page I want to hide the header temporarily. So the user cannot go back plus I have more screen space. 
I found setting the headerStyle to zero works really well.

export default class myPage extends Component {
    static navigationOptions = {
        headerStyle: { height: 0 }
}

But then at some point I want to show the header again, in this case by changing headerStyle { height: 50 }. Is there a way to access / change the navigationOptions ?

Or any other way of changing the appearance of the header ? An alternative would be to disable and later enable the headerLeft button.

Maybe there is a way to force a scene redraw ?

**Comment by 13860120868** [comment]
Hide the header cannot prevent user to go back in IOS since they can use gesture to swipe back.

**Comment by Gys** [comment]
Good to know, but in my case not really a problem.

**Comment by penumbram** [comment]
@Gys I'm having the same problem, is there a solution to this?

**Comment by Gys** [comment]
@penumbram I hope there is ;-) but unfortunately I do not know it.

**Comment by koenpunt** [comment]
If you look at the examples in the project; there's an example that does just this.

**Comment by koenpunt** [comment]
This one to be precise; https://github.com/react-community/react-navigation/blob/master/examples/NavigationPlayground/js/ModalStack.js

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
