### ISSUE TITLE
Trowing Error on Android "Element type is invalid:" but Okay on iOS

### ISSUE THREAD

**Issue by mgorabbani** [react-community/react-navigation#139]
`Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.`
![image](https://cloud.githubusercontent.com/assets/12911638/22521633/d8b35466-e8e2-11e6-9603-6b2dc96865f7.png)

**Comment by satya164** [comment]
Can you post the code please?

**Comment by mgorabbani** [comment]
Sorry all the problem was on Android file. not here!
