### ISSUE TITLE
Get navigation is undefined in tabBarComponent

### ISSUE THREAD

**Issue by GaoStudio** [react-community/react-navigation#1391]
### Current Behavior
I want get a TabNavigator like #138 ，but I need navigate to other screen by left button，but  I get navigation is undefined in tabBarComponent，What should I do， 

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  beta.7
| react-native     |  0.43

**Comment by matthamil** [comment]
Can you post your code?

**Comment by GaoStudio** [comment]
I got a reply from #138,It works for me
