### ISSUE TITLE
should I get TabNavigator life cycle function?

### ISSUE THREAD

**Issue by milawoai** [react-community/react-navigation#1393]
Our App has a TabView as Home Page. Recently ,we ask remote data  and enable message listener in componentDidMount . But now there are only init function like this:

`export const MainTabbar = TabNavigator({ });`

Should I get TabNavigator life cycle function?

**Comment by spencercarli** [comment]
Hi! In an effort to reduce the number of open issues I'm closing question-type issues that would be a better for for the [react-navigation tag on StackOverflow](https://stackoverflow.com/questions/tagged/react-navigation). This is nothing personal, merely trying to get the # of issues to a more manageable level. If you think this issue should be re-opened please let me know. Thanks!
