### ISSUE TITLE
Direction

### ISSUE THREAD

**Issue by gHashTag** [react-community/react-navigation#1399]
Is it possible to make such navigation using this component?
If it is possible, how?
![ggg mov](https://cloud.githubusercontent.com/assets/6774813/25757325/aa5bac92-31d2-11e7-9148-616b59dfa5b6.gif)

**Comment by matthamil** [comment]
I'm not sure I fully understand your question. How are you wanting to use it?

**Comment by jeffreymendez1993** [comment]
use setState and just render out that new component in render no need for navigation.

**Comment by gHashTag** [comment]
Each polygon is a button to turn on an audio file, and the X Y Z is a three samplepack.

**Comment by matthamil** [comment]
What have you tried? I'm not sure that this is a navigation-related problem.

**Comment by gHashTag** [comment]
@matthamil thanks
