### ISSUE TITLE
Navigation within private method

### ISSUE THREAD

**Issue by evancloutier** [react-community/react-navigation#140]
I'm trying to navigate to a new screen when I click on an item rendered by my screen, but I can't seem to figure out how to properly instantiate the `navigate` method to perform the navigation.

Here is the _renderItem method I'm using to display an Image within a TouchableOpacity:

```javascript
_renderItem(item, itemSize) {
    return (
      <TouchableOpacity
        key = { item.id }
        style = {{ width: itemSize, height: itemSize }}
        onPress={(event) => navigate('Image', { photo: item.src })}
      >
        <Image
          resizeMode = "cover"
          style = {{ flex: 1 }}
          source = {{ uri: item.src }}
        />
      </TouchableOpacity>
    )
  }
```

At the moment the navigate method isn't being recognized, but I'm not quite sure how to get around this.

**Comment by jcarbo** [comment]
"Screen" components will receive a prop called `navigation` which contains all the react-navigation props (read more here https://reactnavigation.org/docs/navigators/navigation-prop).

Assuming this snippet is within a screen, you'll want to use:
```
this.props.navigation.navigate('Image', { photo: item.src })`.
```

**Comment by evancloutier** [comment]
@jcarbo I should have provided more detail about how `_renderItem` was being called, but I am calling it via a custom component called `PhotoGrid`. I figured I could just pass the navigate props into the custom component when I render it, which ended up working.

Here is what I did:

```javascript
render() {
    const navigate = this.props.navigation

    return (
      <PhotoGrid
        data = { this.state.items }
        itemsPerRow = { 3 }
        itemMargin = { 1 }
        renderHeader = { this._renderHeader }
        renderItem = { this._renderItem }
        navigation = { navigate }
      />
    )
  }

  _renderItem(item, itemSize) {
    console.log(this)

    return (
      <TouchableOpacity
        key = { item.id }
        style = {{ width: itemSize, height: itemSize }}
        onPress={(event) => this.navigation.navigate('Image', { photo: item.src })}
      >
        <Image
          resizeMode = "cover"
          style = {{ flex: 1 }}
          source = {{ uri: item.src }}
        />
      </TouchableOpacity>
    )
  }

```
