### ISSUE TITLE
how to perform a navigation action from outside of a component?

### ISSUE THREAD

**Issue by vonovak** [react-community/react-navigation#1401]
ex-navigation allows to perform navigation from outside of a component as described [here](https://github.com/expo/ex-navigation#perform-navigation-actions-from-outside-of-a-component). How to do this in `react-navigation`? More importantly, how to dispatch this action to **an arbitrary navigator**? Is there a concept of `id`s for navigators, just like in ex-navigation?

**Comment by miguerp** [comment]
Hi, I was trying to do the same, finally I made it:

I'm using ReduxThunk, so I have access to the _dispatch_ method.
First, you must import:
```javascript
import { NavigationActions } from 'react-navigation';
```

Then:

```javascript
const nav = NavigationActions.navigate({
  routeName: 'MyRoute',
 // My route params
  params: {...}
  // in case you want to navigate into specific sub route
  action: NavigationActions.navigate({ routeName: 'MySubRoute' })
});
dispatch(nav);
```

If you  are not using ReduxThunk, in your _CustomAction.js_ just do:
```javascript
import { NavigationActions } from 'react-navigation';

export const myAction = () => {
  const nav = NavigationActions.navigate({
    ...
  });
  return nav;
};

```

**Comment by vonovak** [comment]
@miguerp thanks! But how do I specify which Navigator should perform the action? (if I have a top level one and a bunch of other nested ones)

**Comment by AlanFoster** [comment]
@vonovak The parent should handle it correctly with nested children/screens

**Comment by miguerp** [comment]
Hi @vonovak, as @AlanFoster says parent should handle it, but keep in mind the following:
Consider this navigation setup for a CRUD app with previous login screen. The goal is to restrict the CRUD operations to logged in users:

```javascript
const MainNavigator = DrawerNavigator({
  BookCreate: { screen: BookCreate },
  BookList: { screen: BookList },
  BookEdit: { screen: BookEdit }
});

const AppNavigator = StackNavigator({
  Login: { screen: Login },
  Main: { screen: MainNavigator }
});
```
Here we have a DrawerNavigator (_MainNavigator_) nested inside a StackNavigator (_AppNavigator_).
You can only navigate directly between routes inside a common Navigator, for example, I can directly go from _BookList_ to _BookEdit_ or from _Login_ to _Main_.

But what if I want to navigate from _Login_ inside _AppNavigator_ to _BookList_ inside _DrawerNavigator_?
You can do so, navigating first to _Main_ inside _AppNavigator_ and then navigating to _BookList_:

```javascript
import { NavigationActions } from 'react-navigation';

export const myAction = () => {
  const nav = NavigationActions.navigate({
    //Let's navigate to Main first
    routeName: 'Main',
    // and then go to BookList
    action: NavigationActions.navigate({ routeName: 'BookList' })
  });
  return nav;
};

```
If you try to navigate just to _BookList_ being _Login_ the active Route, you'll get an error:

```
Error: There is no route defined for key BookList.
Must be one of: 'Login','Main'
```

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!

**Comment by jpca999** [comment]
@miguerp  I tired your redux-thunk method but It didnt work, 
It throws me the error: NavigationActions.navigate is not a function. 


Im using redux thunk, how can i fix it ?


import { NavigationActions } from 'react-navigation'

```
export const Create = ({address, cell, phone, comments, shift, _id  }) => {

    return async ( dispatch, NavigationActions ) => {
      console.log(' 44-  NavigationActions = ', NavigationActions);
      console.log(' 45-  NavigationActions.getState = ', NavigationActions.getState);
        try {
            const token = await AsyncStorage.getItem('token');
            if (token !== null) {
                axios.defaults.headers.common['authorization'] = token;
                axios.post(ROOT_URL, {
                        address: address,
                        cell: cell,
                        phone: phone,
                        comments: comments,
                        // shift : shift
                    })
                    .then(response => {
                        console.log('43 -  response of FRUIT create   response.data = ', response.data);
                        dispatch({
                            type: FRUIT_CREATE,
                            payload: response.data
                        });

                })
                .then(response => {
                    dispatch(NavigationActions.navigate({ routeName: 'allFruits' }));                    
            });
            }
        } catch (error) {
            console.log(error);
        }
    }; // end return (dispatch)
};
```

**Comment by i6mi6** [comment]
Using react-navigation@1.0.0-beta.11


import { addNavigationHelpers } from 'react-navigation';

class Root extends Component {
  render() {
    const nav = addNavigationHelpers({
      dispatch: this.props.dispatch,
      state: this.props.nav,
    })
    return (
      <StackNavigation navigation={nav}/>
    )
  }
}

const mapStateToProps = state => {
  return { nav: state.nav }
};

export default connect(mapStateToProps)(Root);
then call it in Sagas
yield put(NavigationActions.navigate(...))
or Thunk
dispatch(NavigationActions.navigate(...))

**Comment by oluomoniyi** [comment]
Took an easy way out, using redux thunks.

I passed this.props.navigation.navigate to the action, and within my action I just referenced the navigate method.

e.g
in the component 
`this.props.signUp(authData, this.props.navigation.navigate);`

the action
```
export const signUp = (authData, navigateTo) => dispatch => {
dispatch({type: "SIGNUP_SUCCESS", payload: authData}, navigateTo("StartScreen"));
}

```
I am using redux thunks as well

**Comment by brentvatne** [comment]
i wouldn't recommend using redux. you can do this instead https://reactnavigation.org/docs/en/connecting-navigation-prop.html
