### ISSUE TITLE
What function can be called when close drawer

### ISSUE THREAD

**Issue by SleetShang** [react-community/react-navigation#1402]
I need to dispatch a action when close drawer. but i don't know how to write it

**Comment by AlexDufresne** [comment]
I really need somes help THX

**Comment by spencercarli** [comment]
There's no way (that I know of) to do this when a gesture closes it but if you're calling `this.props.navigation.navigate('DrawerClose');` just make whatever call you need to make is done at the same time you're closing the drawer.
