### ISSUE TITLE
Be very explicit about react-navigation's `dispatch` vs. redux `dispatch`

### ISSUE THREAD

**Issue by xml** [react-community/react-navigation#1405]
It's eminently sensible that React-Navigation uses as key abstractions its actions and its dispatcher. They're well-known, understood patterns and provide decoupled interfaces. Stuff like that is why I like this library! Thanks for writing and maintaining it, guys. 

But, the terminology can be pretty confusing in a community where Redux is a first-class citizen, and requires some pains to be clear about the distinction between one dispatcher and another. At the moment, it's often very difficult to tell which one you're looking at, even here on this project. 

For instance, on the very doc dedicated to explaining [Redux Integration](https://reactnavigation.org/docs/guides/redux), we have quotes like:

>  Your navigation prop must provide the current state, as well as access to a **dispatcher** to handle navigation options.

Which one? Redux's? React-Navigation's? _<shrug>_

Then, we've got this example soon after that:
```js
class App extends React.Component {
  render() {
    return (
      <AppNavigator navigation={addNavigationHelpers({
        dispatch: this.props.dispatch,
        state: this.props.nav,
      })} />
    );
  }
}
```
Again, which `dispatch` is this one? Like all code, I can eventually track it down if I look hard enough and have enough experience. Because we seem to be using `connect`, Redux's `dispatch` must be the prop here, and I don't see any destructuring from `navigation`. But... if I _wasn't_ experienced, how would I know that? (Hell, even if I _am_ experienced, and I'm digging around in the guts of an application, in nested components where props have been passed down a couple levels already... there's simply no way that I'm going to be able to tell which `dispatch` I'm looking at, unless someone has remembered to mention it. That's something consumers can reasonably take pains to avoid, but we should probably make sure they're not confused at least here on the project site...)

So, at a bare minimum, we simply would want to be very, very explicit whenever we're explaining about it in the docs. If we consistently refer to it in docs as "React-Navigation's `dispatch`", or (maybe better) as `navigation.dispatch`, then it should be clear enough. 

But there will probably always be at least some confusion in environments that mix with Redux. It would be great if we could recommend patterns for maximizing clarity between the two, such as always passing `navigation` instead of a bare `dispatch`.

**Comment by koenpunt** [comment]
When react-navigation is used without redux, `dispatch` calls on the "internal" navigation dispatcher, which is default usage, so I think it's totally fine to just refer to `dispatch`.

When using it with redux, `dispatch` still works the same throughout your application, e.g. the action format (`{ type: '..', payload: '..' }`) is still the same, except for the fact that it's no longer handled by react-navigation.

And for the example you give, the `addNavigationHelpers` simply defines what the `dispatch` method should be instead of the default, and where the state of the navigation is stored.

> if I wasn't experienced, how would I know that?

I think the integration with redux is advanced usage, because in most cases the default implementation will suffice. So I think one should be somewhat experienced to use it with redux.

**Comment by LAITONEN** [comment]
I actually thought that the dispatch in addNavigationHelpers is React-Navigation's dispatch up until now. 4 months using this library.

**Comment by kelset** [comment]
A PR to the docs with a clearer explanation would be surely appreciated! ;)

**Comment by slava-lu** [comment]
Hi guys, I am struggling to find the answer to the question of using redux with screens defined as functions. Just thought you might give some ideas if it is at all possible.
The question is below. I am sorry to be asking here but I tried all the the proper ways which did not work.

https://stackoverflow.com/questions/47158992/integration-with-redux-does-not-work-when-screens-and-navigators-are-defined-as

**Comment by kelset** [comment]
Closing this issue since @shubhnik submitted a PR to clarify the docs.
