### ISSUE TITLE
headerVisible ignored in 1.0.0-beta.9 

### ISSUE THREAD

**Issue by datermine** [react-community/react-navigation#1409]
I just npm installed and thus upgraded to 1.0.0-beta.9 from 1.0.0-beta.7 and now it seems that navigationOptions are not being respected.

```
  'Splash': {
      screen: SplashScreen,
      path: 'splash/',
      navigationOptions: {
        headerVisible: false,
      },
    }
```
This used to result in the header being hidden for my splash screen, but now it's being shown.

**Comment by datermine** [comment]
Probably a dupe of: https://github.com/react-community/react-navigation/pull/1286

**Comment by FLGMwt** [comment]
Just posting since this wasn't immediately obvious to me. I thought the ability to configure header visibility per screen was straight up removed.

The above can be accomplished with:

```
'Splash': {
  screen: SplashScreen,
  path: 'splash/',
  navigationOptions: {
    header: null,
  },
}
````

Cheers!
