### ISSUE TITLE
Duplicate header for nested navigator

### ISSUE THREAD

**Issue by jcarbo** [react-community/react-navigation#141]
Possibly related to #88 

### Setup

- `RootNavigator` (StackNavigator)
  - `AuthScreen` (handles authentication, once authenticated redirects to AppNavigator)
  - `AppNavigator` (TabNavigator)
    - `RecentNavigator` (StackNavigator)
    - `ContactsNavigator` (StackNavigator)
    - `SettingsNavigator` (StackNavigator)

### Problem

There are two headers, one above the tab bar and one below it:
<img width="617" alt="screen shot 2017-02-01 at 1 59 20 pm" src="https://cloud.githubusercontent.com/assets/847027/22522074/3cc080b0-e888-11e6-9bf4-f87cd35cec27.png">

I'm assuming
- the top one is associated with the "RootNavigator"
- the bottom one is associated with the currently active StackNavigator within the TabNavigator ("RecentNavigator") in this example.

Trying to hide the header (`header: { visible: false }`) within the screens of the "RecentNavigator" hides both of the headers. Updating the "title" of the header sets the header for both of the titles.

Also, FWIW, the top-most title has a bit of a lag when changing tabs. It seems like the title only gets updated at the end of the tab-change animation. I kinda think it should change at the start.

### Questions

- Is there anything obvious that I'm doing wrong? It seems like a fairly sane setup: Auth/App are at the same level, each tab within "App" has its own stack.
- Is there any valid use-case for having a "nested" header like this? I'm not an Android user so I'm not sure if it's a pattern seen in the wild. Assuming it's not, it seems like the easiest thing to do would be to have the "header" settings of a screen always apply to the top-most/site-wide header.

**Comment by UladzimirKuzmin** [comment]
@jcarbo you can hide nested header pass `{ headerMode: 'none' }` as a second argument in your nested StackNavigator. 
Like that:
```
const RecentNavigator({
   RecentScreen: { screen: RecentScreen }
}, {
   headerMode: 'none'
});
```

**Comment by jcarbo** [comment]
@UladzimirKuzmin - ah, that's did it 👍  Don't know how I missed that.

**Comment by jcarbo** [comment]
I'm reopening because I ran into another issue when pushing screens onto a given tab's stack.

<img width="408" alt="screen shot 2017-02-02 at 12 17 27 am" src="https://cloud.githubusercontent.com/assets/847027/22538333/992d43ae-e8df-11e6-8acc-3a26b18f26c1.png">
<img width="375" alt="screen shot 2017-02-02 at 12 16 46 am" src="https://cloud.githubusercontent.com/assets/847027/22538335/9ce2b90c-e8df-11e6-9ab7-1e470a8ba88b.png">

My set up is:
- `RootNavigator` (StackNavigator)
  - `AuthScreen` (handles authentication, once authenticated redirects to AppNavigator)
  - `AppNavigator` (TabNavigator)
    - `BucketNavigator` (StackNavigator)
      - `BucketListScreen`
      - `BucketItemScreen`

The screenshot above is when you're on the `BucketItemScreen`. The back button is showing up in the second header. It wasn't show up at all initially since I set `headerMode: 'None'`.

What'd I'd really like is one global header above everything at the top of the app. Whenever I'm on a given screen, the title/header navigation options for that screen update the global header. Is something like this possible?

**Comment by jcarbo** [comment]
@satya164 - I recall on a different issue (https://github.com/react-community/react-navigation/pull/105#issuecomment-276311605) you said there was some refactor happening to headers. Do you know if my use-case is possible now and/or it would be possible post-refactor?

**Comment by jsbranco** [comment]
Also having the same use case as @jcarbo . In my case:

- Tabs:
     Home
     Settings - Stack Navigator
                  Profile <- if headerMode set to none = no back arrow
                  About <- if headerMode set to none = no back arrow

**Comment by jsbranco** [comment]
@jcarbo  not sure if you found a solution for your case. I just managed to find a solution for mine:

- In my nested StackNavigator I set the headerMode as none:
 Then in each of my stack screen (Profile / About) I defined the navigationProps as follows:

```
static navigationOptions = {
        title: "Profile",
        header: ({state, setParams, goBack}, defaultHeader) => ({
            ...defaultHeader,
            left: <Button transparent onPress={e=>{
            e.preventDefault();
            console.log("clicked")
            goBack();
            }}><Icon name="arrow-back" style ={{color:"#fff", marginLeft:5}} /></Button>
......
```

**Comment by rafaelcorreiapoli** [comment]
I'm having problems settings headerMode: none
It hides the navbar correctly but then I lose navigation capabilities on each StackNavigator (for each tab) since the navbar that is showing on the screen is the one for the RootNavigator...

**Comment by YutamaKotaro** [comment]
I’m having same issue, and would like to know that situation of this issue. 
I wanna know solution.

**Comment by grabbou** [comment]
I am going to close it in favour of #88 where we will be tracking these issues.

**Comment by Tom29** [comment]
@UladzimirKuzmin how's about hiding header for TabNavigator? I need StackNavigator header working.

**Comment by kelvinlawson** [comment]
I worked around this by specifying the upper header's title within the TabNavigator descriptor:
`
export default TabNavigator(
  {
    Menu: {
      screen: SettingsStackNavigator,
      // Work around the fact that titles in nested stacks are duplicated in main header
      navigationOptions: ({ navigation }) => ({
        title: "Menu"
      })
    }
}
`

Now the screens in the nested stack navigator can still set their own title without affecting the upper / top-level header 'Menu'.

**Comment by johot** [comment]
Why was this closed? This is still a problem in the beta27. When having stack navigators inside the tabs of a tab navigator no back button will be rendered for these stack navigators.

**Comment by ropaillet** [comment]
Same issue here, I can hide the inner stack navigator but the 'go back' arrow won't show up after that.

Any ideas if this should be handled through redux and that is why no one bothers in providing a solution ?

Thx !

**Comment by johot** [comment]
I think this needs to be fixed in the codebase. The way I finally "fixed it" was to create my own back button using the `<BackButton/>` component.

**Comment by brentvatne** [comment]
please open a rfc with a suggestion on how to improve this if this is important to you! thanks
