### ISSUE TITLE
TabNavigator scrollEnabled: false does NOT work

### ISSUE THREAD

**Issue by FrancisShi** [react-community/react-navigation#1410]
What  I want is to disable scroll in my three screens:

const

 cashier = TabNavigator(
  {
    Cash: { screen: CashScreen },
    Order: { screen: OrderScreen },
    Mine: { screen: MineScreen },
  },
  {
    tabBarPosition: 'bottom',
    tabBarOptions: {
      scrollEnabled: false,
      indicatorStyle: {
        opacity: 0
      },
      showIcon: true,
      labelStyle: {
        fontSize: 12,
      },
      style: {
        backgroundColor: 'white',
      },
    },
  }
);

But I can still scroll which I don't want.
**scrollEnabled** only works in **Top** ??

**Comment by AnotherJack** [comment]
You should use swipeEnabled in TabNavigatorConfig [here](https://reactnavigation.org/docs/navigators/tab#TabNavigatorConfig)
