### ISSUE TITLE
Navigate away without unmounting

### ISSUE THREAD

**Issue by anhreg** [react-community/react-navigation#1411]
This is a question, not an issue. I use DrawerNavigator in my project. 

When I navigate from A -> B then from B, I call this.props.navigation.navigate() to go back to A again the screen A, the componentDidMount event is triggered.

If from B, I call this.props.navigation.goBack() the componentDidMount event is NOT triggered.

So I logically I think the this.props.navigation.navigate() method unmounts then mounts the screen as if it's never been loaded. Is there anyway to go from a screen to any screen without unmounting it if it has  already been loaded? I implement the data fetching in componentDidMount event, so I don't want it to fetch data again, because my data is not updated frequently.

Thanks in advanced

**Comment by baldurpan** [comment]
+1

**Comment by sercanov** [comment]
Having the same issue with custom tab bar, when navigating the other tab, previous tab is unmounting. When returned back to first tab, component re-mounting again. Loading the same data etc. It's not the default tab bar behavior.

**Comment by paulief** [comment]
@sercanov were you able to find a solution to that? I can't seem to figure out how to prevent un-mounting in a custom tab bar, which means a user loses their scroll position between when moving between tabs.

**Comment by sercanov** [comment]
@paulief it's solved when I upgraded to beta-9

**Comment by paulief** [comment]
@sercanov hmm, I'm still having the issue with that version. Even when just running their `CustomTabs` example from here https://github.com/react-community/react-navigation/blob/master/examples/NavigationPlayground/js/CustomTabs.js

Is there anything in your setup that you had to change to get this working? Or are you implementing the `react-native-tab-view` that the standard `TabNavigator` uses under the hood?

**Comment by sercanov** [comment]
@paulief I've used custom tab component with TabNavigator yes, here is the snippet works without hassle ; 
```javascript
const RootNavigator = TabNavigator(
  {
    HomeTab: {
      screen: DashboardNavigator
    },
    OrdersTab: {
      screen: OrdersNavigator
    },
    CartTab: {
      screen: CartNavigator
    },
    NotificationsTab: {
      screen: NotificationsNavigator
    },
    ProfileTab: {
      screen: ProfileNavigator
    }
  },
  {
    tabBarComponent: props => <TabBar {...props} />,
    initialRouteName: 'HomeTab',
    lazy: true
  }
)

const ProfileNavigator = StackNavigator(
  {
    ProfileScreen: {
      screen: ProfileScreen,
      navigationOptions: {
        title: I18n.t('Profile')
      }
    }
  },
  {
    initialRouteName: 'ProfileScreen',
    navigationOptions,
    cardStyle
  }
)

```

**Comment by kelset** [comment]
Pinging OP @anhreg since this issue is quite old and related to an old version of the lib. If no answer I'll close in 7 days.

**Comment by kelset** [comment]
Hi there @anhreg,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue (especially if it's a bug report) please open a new issue that uses the new Issue Template to provide some more details to help us solve it.

**Comment by lalestan** [comment]
May I please reopen this issue ? Tab navigation works perfectly fine however facing this issue on StackNavigator and DrawerNavigator .. any suggestions ?

**Comment by amiralimatin** [comment]
May I please re-open this issue as I am facing the re-mounting problem in Drawer and stack navigators? It works perfectly fine on Tab navigator..  Thanks

**Comment by amirmatin** [comment]
May I please re-open this issue as I am facing the re-mounting problem in Drawer and stack navigators? It works perfectly fine on Tab navigator.. Thanks

**Comment by kelset** [comment]
> If you are still having the issue (especially if it's a bug report) please open a new issue that uses the new Issue Template to provide some more details to help us solve it.

@amirmatin

**Comment by amirmatin** [comment]
@kelset  ok thanks, will do...
