### ISSUE TITLE
Reason bindings

### ISSUE THREAD

**Issue by wokalski** [react-community/react-navigation#1412]
@saschatimme and I are working on Reason bindings for react native. We haven't added any navigation lib bindings yet and react-navigation looks like a perfect fit because it's de facto officially recommended. 
We'd like to add bindings to it and ideally upstream them. Bindings *do not* impact any existing code, we don't need to make any changes to existing code to make them work. They live in separate files.

**Comment by saschatimme** [comment]
Here are the current React Native bindings: https://github.com/BuckleTypes/bs-react-native

**Comment by grabbou** [comment]
Just linking this issue in case someone stumbles upon this thread: https://github.com/callstack/reroute/issues/9
