### ISSUE TITLE
Send data back from child screen?

### ISSUE THREAD

**Issue by itswaze** [react-community/react-navigation#1416]
Hi!
Is it possilbe to send data back from child screen without using Redux or any state management library?
I have a Stock screen, when the user clicks a dropdown it open a new screen with all the available brands, after selecting one brand, I need to pass a Name and an ID back to parent screen.

**Comment by DiogoAbu** [comment]
Create a function inside Stock screen and pass it to the child screen using `screenProps`. Call the function from the child screen passing the data

**Comment by itswaze** [comment]
@DiogoAbu isn't possible to send with goBack function? it would be alot easier.

**Comment by DiogoAbu** [comment]
@itswaze i don't believe goBack can send params, gotta check the docs

**Comment by itswaze** [comment]
@DiogoAbu yea it doesn't... but it would be alot easier. Still stuck on this, gotta figure it out.

**Comment by zubricky** [comment]
@itswaze, You can do something along these lines to pass back from the child screen.

Create a function in your parent component like this:
```
returnData(id, name) {
  this.setState({id: id, name: name});
}
```

Then when you navigate to your child component, pass the function:
```
this.props.navigation.navigate('ChildComponent', {returnData: this.returnData.bind(this)});
```

Then in your child component when you go back, you can do something like this:
```
  this.props.navigation.state.params.returnData('123', 'Name of item');
  this.props.navigation.goBack();
```
Or you could call the function anytime, it doesn't have to be when you go back.

It's not great when you have to send props back 2 or 3 screens deep since you have to keep passing the props down in each component, but if you get into a situation like that, you should probably just use Redux or another state management.

**Comment by itswaze** [comment]
@zubricky I was doing that just know and it is working, Im just testing with a name: 'test' on my state and It did change the text on my first screen. Now I have one doubt...

```
        <ScrollView style={styles.container}>
          {list.map((item, index) => {
            return(
              <TouchableHighlight underlayColor='#f48529' onPress={() => this.backStock()} key={index}>
                <View style={styles.marcaContainer}>
                  <Icon name="cv" color="#D0D3D4"/>
                  <Text style={styles.text}>{item.Name}</Text>
                </View>
              </TouchableHighlight>
            );
          })}
        </ScrollView>
```
Now I want to be able to take that item.Name and set the result on this.state or something, so when I click the Item I want it passes the correct name to the previous screen. 

this.backStock() calls this function:

```
  backStock(){
    this.props.navigation.state.params.callback(this.state.nome)
    this.props.navigation.goBack()
  }
```

I think I didn't explained very well :P 
But thank you so much for your help!

**Comment by skizzo** [comment]
@zubricky's approach works fine as long as there is no such thing as `redux-persist` involved to restore the navigation state. Would be really handy to actually be able to hand over navigation params to the `back` function!

**Comment by mkayswork** [comment]
In case you face the behavior that the passed function is undefined but you used the code above from @zubricky , uninstall and install the app again. Thus, make sure that your start screen is the parent's screen

**Comment by Edison4mobile** [comment]
@zubricky  perfect thanks

**Comment by shreepadavasanth** [comment]
@zubricky  thanks mate

**Comment by shivam-mnnit** [comment]
@zubricky  and @mkayswork you guys saved my day...was stuck on this thing from 2 hours.
Thanx a lot

**Comment by Umar461386** [comment]
Thnx a lot you save my day thanks again

**Comment by bboure** [comment]
Passing callback works, however it gives me the following warning in the latest version of react-navigation (5.0.6)

> We found non-serializable values in the navigation state, which can break usage such as persisting and restoring state. This might happen if you passed non-serializable values such as function, class instances etc. in params. If you need to use components with callbacks in your options, you can use 'navigation.setOptions' instead. See https://reactnavigation.org/docs/en/troubleshooting.html#i-get-the-warning-we-found-non-serializable-values-in-the-navigation-state for more details.

The solution offered in the link does not really help since it assumes that the callback is always the same.
I am trying to implement a "place picker".
Use cases can be:
- User clicks a button which opens the place picker. When user selects a place, a **new screen** opens, and the place id is passed as parameter.
- In a form, user clicks a field, which opens the place picker. When user select a place, he should be **redirected back** to the form, and the field should be populated with the selected item
Notes: There can be more than one "place" field in the same form and there can be several forms in different Screens.

All this is easily achieved with the callback solution, and it works. It just tells the "finder" screen what to do when the user picks a place.
I am just a bit worried about the warning and that it might break in some cases (Probably if the state has to be restored).

What would be the recommended way to do this?

Thank you

**Comment by GuleriaAshish** [comment]
> @itswaze, You can do something along these lines to pass back from the child screen.
> 
> Create a function in your parent component like this:
> 
> ```
> returnData(id, name) {
>   this.setState({id: id, name: name});
> }
> ```
> 
> Then when you navigate to your child component, pass the function:
> 
> ```
> this.props.navigation.navigate('ChildComponent', {returnData: this.returnData.bind(this)});
> ```
> 
> Then in your child component when you go back, you can do something like this:
> 
> ```
>   this.props.navigation.state.params.returnData('123', 'Name of item');
>   this.props.navigation.goBack();
> ```
> 
> Or you could call the function anytime, it doesn't have to be when you go back.
> 
> It's not great when you have to send props back 2 or 3 screens deep since you have to keep passing the props down in each component, but if you get into a situation like that, you should probably just use Redux or another state management.

How can we achieve this thing in react navigation v5 ?

**Comment by hoseineghbal** [comment]
what we must do in v5 ???

**Comment by ppoletti** [comment]
How do you do this in v5?

**Comment by marcoskubis** [comment]
> > @itswaze, You can do something along these lines to pass back from the child screen.
> > Create a function in your parent component like this:
> > ```
> > returnData(id, name) {
> >   this.setState({id: id, name: name});
> > }
> > ```
> > 
> > 
> > Then when you navigate to your child component, pass the function:
> > ```
> > this.props.navigation.navigate('ChildComponent', {returnData: this.returnData.bind(this)});
> > ```
> > 
> > 
> > Then in your child component when you go back, you can do something like this:
> > ```
> >   this.props.navigation.state.params.returnData('123', 'Name of item');
> >   this.props.navigation.goBack();
> > ```
> > 
> > 
> > Or you could call the function anytime, it doesn't have to be when you go back.
> > It's not great when you have to send props back 2 or 3 screens deep since you have to keep passing the props down in each component, but if you get into a situation like that, you should probably just use Redux or another state management.
> 
> How can we achieve this thing in react navigation v5 ?

You can achieve by accessing the route property: `props.route.params.callbackFn`

**Comment by prashantopenxcell** [comment]
@zubricky Thank you so much

**Comment by prashantopenxcell** [comment]
in reactnavigation v5
`const navigation=useNavigation() `
For passing function to other screen
`naviation.navigate('screen_name', { fucntion_name : () => {
console.log('callback_received');
}})`

Now on second screen to get the function
`const { function_name } = route.params`
for calling function
`function_name();`

Hope that will work for all in reactnavigation v5

**Comment by losh11** [comment]
> in reactnavigation v5
> `const navigation=useNavigation() `
> For passing function to other screen
> `naviation.navigate('screen_name', { fucntion_name : () => { console.log('callback_received'); }})`
> 
> Now on second screen to get the function
> `const { function_name } = route.params`
> for calling function
> `function_name();`
> 
> Hope that will work for all in reactnavigation v5

This doesn't work for me. It results in `undefined is not an object (evaluating 'route.params.onGoBack')`. Exactly the same as your example, except I'm not using the useNavigation() hook.

**Comment by okihouse** [comment]
> in reactnavigation v5
> `const navigation=useNavigation() `
> For passing function to other screen
> `naviation.navigate('screen_name', { fucntion_name : () => { console.log('callback_received'); }})`
> 
> Now on second screen to get the function
> `const { function_name } = route.params`
> for calling function
> `function_name();`
> 
> Hope that will work for all in reactnavigation v5

It works fine.
But I get a warning like below: 
`[WARN]  Non-serializable values were found in the navigation state.`

**Comment by zholmes1** [comment]
This is a feature that is extremely useful in native Android development and is totally unsupported in react-navigation. Sometimes you need a screen whose only purpose is to allow the user to send some kind of data back to the previous screen. Examples are a place picker, month picker, credit card form, etc.

I think the ideal solution would be to be able to pass anything in `navigation.goBack({ result: 'someUserInput' })` in the child screen, and be able to receive that data in the parent screen with something like this:

```
const route = useRoute()

useEffect(() => {
  route.onResult(result => {
    // do something with the result from the child screen
  })
}, [])

**Comment by raajnadar** [comment]
You have two ways to do it,

First use the global state management like context api, to send and receive data to any parent-child screen.

Second pass the params to `navigation.navigate` and get back from the route props.

Example Child -
```navigation.navigate('SomeScreen', { foo: 'bar' })```

Example Parent -
In the render `props.route.foo` or ` this.props.route.foo`

**Comment by zholmes1** [comment]
Yeah I get that there are ways to accomplish this, but they are roundabout solutions. I feel this is core enough that it should be built directly into `react-navigation` as a first-class feature.

My preferred workaround is actually `DeviceEventEmitter`

```
DeviceEventEmitter.emit('onPlacePicked', placeId)
```

```
useEffect(() => {
  DeviceEventEmitter.addListener('onPlacePicked', placeId => {
    // do something with result
  }) // remove listener
}, [])
```

It's mostly equivalent to a hypothetical "result" feature in react-navigation, you just have to be careful with the event ID.

**Comment by zholmes1** [comment]
> Example Child - `navigation.navigate('SomeScreen', { foo: 'bar' })`
> 
> Example Parent - In the render `props.route.foo` or ` this.props.route.foo`

This solution messes with the param types of the parent screen, and also the child screen has to know which screen to navigate back to. If the child screen can be used by different parents (e.g. multiple places in your app where you can pick a place) then it falls apart.

> First use the global state management like context api, to send and receive data to any parent-child screen.

Passing data between screens is just about the number 1 core feature of `react-navigation`. If you need to bring in another dependency to accomplish that task... well then maybe `react-navigation` should just implement it itself.

**Comment by satya164** [comment]
@zholmes1 the recommended approach is typesafe. what you wrote cannot be type-checked. it still works with multiple screens as long as you pass the screen name as a param.

if you can come up with a simpler API that's also type-safe, please open a RFC here: https://github.com/react-navigation/react-navigation/discussions/categories/ideas

**Comment by sebastienlabine** [comment]
@zholmes1  @satya164 I feel like this is a big feature missing from react navigation. The best solution I came up with is passing to the modal / child screen a unique field id and emitting an event with for that custom ID. I feel like it's a hotfix and that we should have an API allowing us to at least pass a react context to the screen.
