### ISSUE TITLE
Dynamically render headerLeft based on headerProps

### ISSUE THREAD

**Issue by alenia** [react-community/react-navigation#1417]
Currently, you can pass in a function to header in navigationOptions, but headerLeft only allows you to pass in a component.

The [renderLeftComponent method](https://github.com/react-community/react-navigation/blob/master/src/views/Header.js#L115-L143) has a lot of logic about whether or not to show the back button. I'd love to be able to use some of your logic while customizing my header.

I feel like either you should be able to call
```
navigationOptions: {
  headerLeft: (headerProps) => <MyLeftComponent/>
} 
```

or specify component based on headerProps like so:

```
navigationOptions: {
  header: (headerProps) => <Header {...headerProps} leftComponent={MyLeftComponent}/>
}
```

My end goal is to show a hamburger if there isn't a back button and also to be able to customize the back button icon.

**Comment by alenia** [comment]
I'm planning on putting together a PR for this later just figured I'd ask in case someone's already working on it or in case I'm misunderstanding anything.

**Comment by KamWis** [comment]
👍 `headerLeft: (headerProps) => <MyLeftComponent/>` seems also like a solution to me :)

**Comment by Un3qual** [comment]
@KamWis Doesn't work for me. 
```es6
headerLeft: (props) => {
    console.log("HPP", props)
    return <MyLeftComponent />
  },
```
doesn't log anything

**Comment by lucianomlima** [comment]
@Un3qual It's a proposal, it's not implemented yet.

**Comment by Jacse** [comment]
This is possible now that `navigationOptions` can be a function. Issue should be closed (cc @kelset )

**Comment by kelset** [comment]
Thanks @Jacse for ping.
