### ISSUE TITLE
Navigating parent navigators from children

### ISSUE THREAD

**Issue by bendyorke** [react-community/react-navigation#142]
I have a set-up that looks like:

```
const Tab = StackNavigator({
  Profile: { screen: ProfileScreen },
})

const Tabs = TabNavigator({
  One: Tab,
})
 
const Modal = StackNavigator({
  Home: {screen: Tabs},
  Login: {screen: LoginScreen},
}, {mode: 'modal'})
```

Is it possible to navigate between `Modal` screens/routes from `ProfileScreen`?  I'm aware I could do something like: 

```
navigator.dispatch({
  type: 'Reset',
  index: 0,
  action: {
    type: 'Navigate',
    routeName: 'Login',
  },
})
```

However, I don't want to "Reset" the state in all the children navigators.  Ideally I'd like to be able to navigate to `Login` from `ProfileScreen`, then navigate to `Home` from `LoginScreen` and be at the same tab/card that I started at.

Is this currently possible?  If not, is this functionality something that you would consider adding to react-navigation?  I don't mind putting in the work to get it working :)

**Comment by ElliottJRo** [comment]
I think you will have to use a custom `TabNavigator` that doesn't tear down the props when navigating away so 'currentTab' state doesn't change

**Comment by skevy** [comment]
I think generally this is affected by better modal support, such as discussed in #67. This is something we'll work on for 1.0

**Comment by Selman555** [comment]
I'm not sure, but could you try this:

navigator.dispatch({
  type: 'Reset',
  index: 0,
  key: null,
  action: {
    type: 'Navigate',
    routeName: 'Login',
  },
})

It works for me

**Comment by kelset** [comment]
Pinging OP @bendyorke since this issue is quite old and apparently no need to keep open. If no answer I'll close in 7 days.

**Comment by kelset** [comment]
Hi there @bendyorke ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue (especially if it's a bug report) please open a new issue that uses the new Issue Template to provide some more details to help us solve it.
