### ISSUE TITLE
I use a stack navigation in drawer navigation and It will add a new router when click drawer item in drawer navigation

### ISSUE THREAD

**Issue by SleetShang** [react-community/react-navigation#1424]
This are top level drawer navigation.  

                import React ,{Component} from 'react'
                import { addNavigationHelpers } from 'react-navigation';
                import {DrawerNavigator} from 'react-navigation'
                import {connect} from 'react-redux'
                import DevicesPage from '../page/DevicesPage'
                import  HomeStackNavigation from './HomeStackNavigation'
                import ServerPage from '../page/ServerPage'
                import DrawerPage from '../page/DrawerPage'
                const {width,height} = Dimensions.get('window');
                const mapStateToProps = (state)=>({
                    drawerNav : state.DrawerNavReducer
                });
                class DrawerNavigation extends Component{
                    render(){
                        return( 
                            <Drawer
                            navigation={addNavigationHelpers({
                                dispatch: this.props.dispatch,
                                state : this.props.drawerNav
                            })}
                            />
                        );
                    }
                }
                export const Drawer = DrawerNavigator({
                    Home:{
                        screen : HomeStackNavigation
                    },
                    Devices:{
                        screen : DevicesPage
                    },
                    Server:{
                        screen : ServerPage
                    }
                },{
                    initialRouteName:'Home',
                    drawerWidth: width - 100,
                    drawerPosition: 'left',
                    contentComponent: props =><DrawerPage {...props}/>
                })
                export default connect(mapStateToProps)(DrawerNavigation);

And this is my stack navigator, it is the first item of drawer navigator.     
                
                import React,{Component} from 'react';
                import {
                    View
                } from 'react-native'
                import {StackNavigator} from 'react-navigation';
                import {addNavigationHelpers } from 'react-navigation';
                import {connect} from 'react-redux';
                import HomePage from '../page/HomePage'
                class HomeStackNavigation extends Component{
                    render(){
                        return(
                            <StackNavigation navigation={
                            addNavigationHelpers({
                                dispatch: this.props.dispatch,
                                state : this.props.nav,
                            })}/>);
                    }
                }
                export const StackNavigation = StackNavigator({
                    Home:{
                        screen:HomePage
                    }
                },{
                    initialRouteName : 'Home',
                    initialRouteParams :  {
                        chartType : 'BarChart'
                    }
                })
                const mapStateToProps = (state)=>{
                    return({
                        nav : state.HomeStackNavReducer,
                    });
                }
                export default connect(mapStateToProps)(test);

when i first enter the test view it is a router that the key is 'init'.and when I open drawer click the first item. It will add a new router. Finally It will appear a red screen. This is because I need some parameters in the initialized router not a new router. so can you help me.

**Comment by AlexDufresne** [comment]
some detials in [question](http://stackoverflow.com/questions/43863473/i-use-a-stack-navigation-in-drawer-navigation-and-it-will-add-a-new-router-when)

**Comment by thomasbaldwin** [comment]
Having the same issue, did you ever figure out a solution @AlexDufresne ?

**Comment by mattfysh** [comment]
@pvsong do you know why this is - does reactnavigation flatten the names of the child routes? Running into a host of bugs right now trying to reuse a stack navigator with two routes in a drawer navigator

**Comment by kelset** [comment]
Pinging OP @SleetShang since this issue is quite old and related to an old version of the lib. If no answer I'll close in 7 days.

**Comment by mattfysh** [comment]
@kelset just a quick question on this behaviour - do you know if the names of the routes are flattened, so we can't have 'Home' as a route name in multiple child/nested routers?

**Comment by kelset** [comment]
@mattfysh take it with a grain of salt, but my 2c are that route names are not "flattened" per se but still, it may cause an inconsistent behaviour to have multiple routes named the same way. As a general rule I always give different names.

**Comment by kelset** [comment]
Hi there @SleetShang,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue (especially if it's a bug report) please open a new issue that uses the new Issue Template to provide some more details to help us solve it.
