### ISSUE TITLE
undefined is not a function evaluating on navigation.navigate('DrawerOpen')

### ISSUE THREAD

**Issue by tsmrafee-bs** [react-community/react-navigation#1428]
Using the solution on [#834](https://github.com/react-community/react-navigation/issues/834), I have wrote the index.js as

    import React from 'react'
    import {ScrollView} from 'react-native'
    import {DrawerItems, DrawerNavigator, StackNavigator} from 'react-navigation'
    import Home from './screens/home'
    import Chat from './screens/chat'
    import DrawerButton from './components/DrawerButton'

    const RouteConfigs = {
    Home: {
      screen: Home,
    },
    Chat: {
      screen: Chat,
    },
    }

    const config = {
    drawerWidth: 300,
    headerMode: 'screen',
    contentComponent: props => <ScrollView><DrawerItems {...props} /></ScrollView>,
    }

    let drawer = StackNavigator(RouteConfigs, 
    {
    navigationOptions: navigation => ({
      headerLeft : <DrawerButton navigation={navigation} />,
    }),
    })

    const App = DrawerNavigator({
    Home: { screen: drawer }
    },
    config);
    export default App

And my DrawerButton.js file is

import React from 'react';
    import { TouchableOpacity } from 'react-native';
    import Icon from 'react-native-vector-icons/MaterialCommunityIcons';

    const DrawerButton = ({ navigation }) => (
      <TouchableOpacity>
        <Icon
          name="menu"
          onPress={() => navigation.navigate('DrawerOpen')}
        />
      </TouchableOpacity>
    );

    DrawerButton.propTypes = {
      navigation: React.PropTypes.object.isRequired,
    };

    export default DrawerButton

But i found the following result when i click on the drawer button
![screenshot_1494328294](https://cloud.githubusercontent.com/assets/27723951/25848094/9d622b96-34da-11e7-9f0b-6eb959e71172.png)
What is wrong with the code?

**Comment by tsmrafee-bs** [comment]
Using the following code on the navigationOptions solved my problem.

    navigationOptions: ({navigation}) => ({
      headerLeft: <DrawerButton navigation={navigation} />,
    }),

**Comment by tsmrafee-bs** [comment]
Using the following code on the navigationOptions solved my problem.

    navigationOptions: ({navigation}) => ({
      headerLeft: <DrawerButton navigation={navigation} />,
    }),

**Comment by jessycormier** [comment]
Thank you so much for this. It's what I've been searching for for a few hours now. Most people were trying to give examples where they pass ({ navigation}) => {} directly to headerLeft, which does not work.

**Comment by NawazKhanMd** [comment]
Where do I add the above code that you mentioned

**Comment by jessycormier** [comment]
In my example here, I setup a static navigationOptions object that I pass to 
`  
export default class SomeComponentScreen extends React.Component {
  static navigationOptions =  ({navigation}) => ({
    title: 'Bundles',
    headerRight: <Text onPress={ () => { navigation.navigate('ToSomeRoute') } }>Click Me</Text>,
  });
  // ...other code...
}
`
This goes directly in my component that is a route. from here I can click that text to go to a new component.
