### ISSUE TITLE
Transition speed for switching tabs

### ISSUE THREAD

**Issue by tanotify** [react-community/react-navigation#1433]
Is there any ability to control speed of tabs switching in TabNavigator? I mean in moment you click on tab not swiping them.

**Comment by koenpunt** [comment]
Looking at the readme of the tabview library I would say you need to use the `configureTransition` prop. Not sure how to set that from within a navigation though..

https://github.com/react-native-community/react-native-tab-view/blob/master/README.md#tabviewpagerpan-

**Comment by koenpunt** [comment]
Something like this in the navigator config might work:

```js
containerOptions: {
  configureTransition: () => ...,
}

**Comment by tanotify** [comment]
Okay, I

**Comment by anton6** [comment]
@tanotify Hi, can you please provide some documentation links for achieving StackNavigator with custom transition? thanks
