### ISSUE TITLE
Unable to navigate away from drawer screens

### ISSUE THREAD

**Issue by Jahans3** [react-community/react-navigation#1434]
### Current Behavior
Drawer item headers seem unconfigurable.

I set the `navigationOptions` on a drawer item like so:

```
  static navigationOptions = ({ navigation }) => ({
    title: 'Terms & Conditions',
    headerLeft: () => navigation.dispatch(NavigationActions.back()),
```

Then when I click on that drawer item, I am unable to navigate away and have to reset the app to get out. No title appears and nothing resembling a header appears.

### Expected Behavior
I click on the drawer item, it opens the screen for that item and the `navigationOptions` work as I would expect on the screen of a `StackNavigator`.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.9
| react-native     |  0.44.0
| node             | 7.10.0
| npm or yarn      | yarn 0.23.4

### Screens

![Drawer open](http://i.imgur.com/l56N3J3.png)
![Drawer item clicked](http://i.imgur.com/Y5AgiNT.png)

As an aside, does anyone have an up-to-date example of a drawer working with Redux? I have got mine working, but I am not sure if it's correct and I'm mostly thinking in terms of React-Native-Router-Flux and trying to make React-Navigation's work in a similar way.

Thanks

**Comment by spencercarli** [comment]
Hi! In an effort to reduce the number of open issues I'm closing issues that haven't had any activity in a while.

If you think this should be re-opened please let me know or, if you can, re-open it.

If this is a question please consider asking it on StackOverflow ([react-navigation](https://stackoverflow.com/questions/tagged/react-navigation))

Thanks!

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
