### ISSUE TITLE
Adding RCTLinkingIOS pod spec to the Podfile fails on iMessage extension

### ISSUE THREAD

**Issue by shrutic** [react-community/react-navigation#1435]
### Current Behavior

1) As per the issue resolution here https://github.com/react-community/react-navigation/issues/460, I added a new entry in my react native Podfile iMessage extension project. 

2) Upon compiling the code, the following code in react-native errors out
![image](https://cloud.githubusercontent.com/assets/4141641/25874261/95cdce94-34c6-11e7-8efb-d490d6567081.png)

with the error 

> /node_modules/react-native/Libraries/LinkingIOS/RCTLinkingManager.m:74:41: 'openURL:' is unavailable: not available on iOS (App Extension)

Could you let me know the following? 

- Is it really necessary to include the RCTLinkingIOS podspec to the project?

- Is there a simple way to resolve this error barring updating react-native code which will take eons to reach the actual release?

### Expected Behavior
The react-native code should compile so that the Root react-navigation navigator can be executed for me to test my changes to move my project from old "Navigator" built into react-native to the new recommended react-navigation

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0.beta9
| react-native     |  0.43.3
| node             | 6.7.0
| npm or yarn      | npm - 4.5.0

**Comment by kelset** [comment]
Pinging OP @shrutic since this issue is quite old and related to an old version of the lib. If no answer I'll close in 7 days.

**Comment by kelset** [comment]
Hi there @shrutic,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue (especially if it's a bug report) please open a new issue that uses the new Issue Template to provide some more details to help us solve it.
