### ISSUE TITLE
why not provide a good readme with sample app?

### ISSUE THREAD

**Issue by aqnaruto** [react-community/react-navigation#1438]
this readme is for react native ,not for react-navigation.

it is hard to use ,hard to understand .

if i do'nt not need staticnavigator or drawavigator how should i do to jump to another page.

when i write this like '  const { navigate } = this.props.navigation;'  
it is cannt work and prompt no such props.

**Comment by koenpunt** [comment]
The source of the website is in the repo, which obviously is not react native. Maybe that will get you going?

**Comment by aqnaruto** [comment]
i am very grateful  to recieve your reply, i will try the samlpe again .
