### ISSUE TITLE
How to back some data

### ISSUE THREAD

**Issue by lucasleelz** [react-community/react-navigation#1440]
### Current Behavior
I do not know how to pass data from the current screen to the previous screen

### Expected Behavior
It is very easy to pass from the current screen to the next screen. 
but, `goBack()`  Can not pass parameters 。
Can tell me how to pass parameters to the previous screen?

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.9
| react-native     |  0.44.0
| node             | 7.5.0
| npm       | 4.1.2

**Comment by rmevans9** [comment]
Are you using some sort of app wide state library like Redux or MobX?

**Comment by lucasleelz** [comment]
@rmevans9  Not used, I think `redux` has some complicated.

**Comment by rmevans9** [comment]
Without having some app wide state library I am not sure that you can do what you are trying to do currently. I would need someone more familiar with the inner workings of React-Navigation to confirm that though.

**Comment by lucasleelz** [comment]
@rmevans9 Hi
I am now the app can not need `redux`. And used the `react-navigation`, it can also work. 
We are now meeting this problem.

**Comment by itswaze** [comment]
I had the same problem, see #1416. Hope it helps!

**Comment by lucasleelz** [comment]
@itswaze Thank you, this way I know, in fact, is a callback.

**Comment by itswaze** [comment]
@lucasleelz isn't that what you want? :p

**Comment by lucasleelz** [comment]
@itswaze 
Hi, I think this might be better.
### Go back to the previous screen
```
navigation.pop({user: 'itswaze'});
or
navigation.goBack({user: 'itswaze'});
```
### Go back to the specified screen
```
navigation.pop('MainScreen', {user: 'itswaze'}); 
or
navigation.goBack('MainScreen', {user: 'itswaze'}); 
```
```
class MainScreen extends Component { // react life cycle
    componentWillReceiveProps(nextProps) {
         // nextProps.user === 'itswaze' 
   }    
}
```

**Comment by itswaze** [comment]
@lucasleelz but goBack doesn't accept parameteres...

**Comment by lucasleelz** [comment]
@itswaze Yes, That's just what I thought about it

**Comment by JulioOrellana** [comment]
what was the answer to this? why it is closed?

**Comment by devotebest** [comment]
what is correct answer?

**Comment by devotebest** [comment]
I'd like to pass some data with navigation.pop() function.

**Comment by JulioOrellana** [comment]
> I'd like to pass some data with navigation.pop() function.

the correct way is to declare callback on navigationParams

```a
getBackData = (data) => console.log(data)

changeScreen = () => this.props.navigation.navigate('Other', { goBackData: this.getBackData }

----

// On Other Screen

this.props.navigation.params.state.goBackData({ 
//your data json or whatever
})
this.props.navigation.pop()
```

**Comment by devotebest** [comment]
it doesn't work
cannnot read property 'state' of undefined.

**Comment by JulioOrellana** [comment]
> it doesn't work
> cannot read property 'state' of undefined.

sorry, it's `state.params`, not `params.state`

**Comment by devotebest** [comment]
:( it says this.props.navigation.state.params.goBackData is not function now.

**Comment by JulioOrellana** [comment]
paste code

**Comment by devotebest** [comment]
this.props.navigation.state.params.goBackData({ 
            name: 'Lucy'
        })
        this.props.navigation.pop();

**Comment by JulioOrellana** [comment]
where you navigate

**Comment by devotebest** [comment]
want to go to previous screen.

**Comment by JulioOrellana** [comment]
Read declaration carefully 

https://github.com/react-navigation/react-navigation/issues/1440#issuecomment-477303163

**Comment by devotebest** [comment]
okay. thanks

**Comment by devotebest** [comment]
It works fine. thanks

**Comment by devotebest** [comment]
@JulioOrellana 
I just faced other problem. I got data successfully, but this.state is undefined. any helpful tip for this? Thank you
getBackData (data) {
        console.log(data);
        console.log(this.state);
}
