### ISSUE TITLE
StatusBar color

### ISSUE THREAD

**Issue by DylanFayant** [react-community/react-navigation#1441]
Hello !

I've an answer about the react-native status bar. Normally, with the old react-native navigator system, we used to put the <StatusBar component (to change the status bar color) with the navigator. But now with the react-navigation idk how to change the status bar color in every page of my App... 
I've tried to put the StatusBar component in every page but 1. it's borring and 2. the content of my page goes behind the status bar... 

Have a nice day ;)

Thank you for your help !

**Comment by JPStrydom** [comment]
+1

**Comment by thomasbaldwin** [comment]
@DylanFayant did you ever figure this one out?

**Comment by ezzak** [comment]
Have you tried doing this?

```javascript
const AppContent = StackNavigator({
  Home: { screen: HomeScreen },
  Secondary: { screen: SecondaryScreen },
});

const App = () =>
  <View style={{flex: 1}}>
    <StatusBar />
   <AppContent />
 </View>;
```

**Comment by kormang** [comment]
Will this help you: [react-navigation-helpers](https://github.com/kormang/react-navigation-helpers) ?

**Comment by IslamTareq0012** [comment]
@ezzak 
could you provide the complete code please

**Comment by gezichenshan** [comment]
@ezzak But if I want 2 styles , for example ,
```
Home-screen:
        <StatusBar barStyle="light-content"/>

Profile-screen:
        <StatusBar barStyle="dark-content"/>
```
How to do it?

**Comment by dancomanlive** [comment]
In the main app component 

```
<StatusBar
          barStyle={this.getBarStyle()}
        />
```

than 

```
getBarStyle = () => {
    const route = this.props.nav.routes[this.props.nav.index].routeName;
    if (['screenNameHere', 'andHere'].indexOf(route) >= 0) {
      return 'dark-content';
    }
    return 'light-content';
  }
```

**Comment by rahulbrilliant2004** [comment]
Sorry to bother but I tried many things with StackNavigatior but didn't found any way to achieve something like http://nimb.ws/w57XQO
My main concern is StatusBar background and shadow with https://reactnavigation.org/docs/navigators/stack

**Comment by rahulbrilliant2004** [comment]
Sorry to bother but I tried many things with StackNavigatior but didn't found any way to achieve something like http://nimb.ws/w57XQO
My main concern is StatusBar background and shadow with https://reactnavigation.org/docs/navigators/stack

**Comment by kelset** [comment]
Pinging OP @DylanFayant since this issue is quite old and related to an old version of the lib. If no answer I'll close in 7 days.

Moreover, solutions provided by @ezzak & @dancomanlive are good approaches.

**Comment by pvinis** [comment]
currently i do `headerStyle: { paddingTop: 20, marginTop: -20 }` to also color the statusbar, and make the height +20. its a hack, but we should add a `statusBarBackgroundColor` or something.

**Comment by aforty** [comment]
@pvinis God this is messy, but it works! 👍🏼

**Comment by kelset** [comment]
Yeah it's kinda messy atm - the thing it's that this concern with StatusBar has been discussed quite heavily since the very beginning ( #11 #12 ) but we haven't yet a definitive decision about it.

**Comment by kelset** [comment]
Hi there @DylanFayant,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it. Moreover, as I already said, there are other issues open related to this problem - and I still believe that the solution proposed in the comments are viable.

**Comment by mgscreativa** [comment]
Hi! with react-navigation connected to redux, this worked for me https://github.com/react-community/react-navigation/issues/51#issuecomment-345035601

**Comment by FrenchMajesty** [comment]
Unfortunately the solution proposed by @ezzak does not function the way I would hope it would. I need to have a white status bar color on a couple of screens and keep it black on the rest of the app.
Does anyone have an idea on how to achieve this?

**Comment by brentvatne** [comment]
https://reactnavigation.org/docs/en/status-bar.html

if anyone has suggestions for how to improve it, please post an issue or send a PR over to the website. https://github.com/react-navigation/react-navigation.github.io
