### ISSUE TITLE
How to handle headerLeft navigation option on Android?

### ISSUE THREAD

**Issue by joncursi** [react-community/react-navigation#1443]
`headerLeft` renders nicely on iOS since the title text is centered. There is room for it to render. However, on android, the title renders more on the left side to begin with, so sticking a custom element on `headerLeft` will cause conflicts. Consider the following example:

<img width="671" alt="screen shot 2017-05-10 at 8 50 59 am" src="https://cloud.githubusercontent.com/assets/4974609/25899515/2b1823fe-355e-11e7-898c-58b0ba2774da.png">

Thoughts on a clean way to handle this?

**Comment by AlanFoster** [comment]
@joncursi You can confirm this within the source code, but i believe the default back button may have paddingRight added to it to solve this issue

**Comment by alenia** [comment]
Maybe try to modify headerTitleStyle?

**Comment by RogerParis** [comment]
`static navigationOptions = {
    header: (navigation) => ({
      title: <Text style={{ color: 'rgba(0, 0, 0, .9)', fontWeight: Platform.OS === 'ios' ? '600' : '500',  fontSize: Platform.OS === 'ios' ? 17 : 18, alignSelf: 'center' }}>Filters</Text>,
      right: <SearchButton />,
      left: <CancelButton />,
    })
  };`

This looks good in my case. I hope it helps.
