### ISSUE TITLE
How to conditionally return default header with new header api?

### ISSUE THREAD

**Issue by acomito** [react-community/react-navigation#1444]
This will hide the header on android:

`header: Platform.OS === 'android' && null,`

But what if I want to hide the header on android, and show the default header on iOS? Is there a default header component somewhere? This is how I'd set it up but I dont want to build the default header from scratch myself:

`header: Platform.OS === 'android' ? null : <Text>My header</Text>,`

I had used headerVisible in the past which was good for this use case, now I don't know what to do....

**Comment by acomito** [comment]
I'm guessing it is something like this maybe:

```
import { Header } from 'react-navigation';

header: Platform.OS === 'android' ? null : <Header {...screenProps} {...navigation} />,
```
but the above gets an `undefined is not an object` for `evaluating this.props.scene.index`

**Comment by alenia** [comment]
You can call `header: (headerOptions) => Platform.OS === 'android' ? null : <Header {...headerProps />`

**Comment by acomito** [comment]
Thank you!!!!!

**Comment by Monte9** [comment]
this worked for me. Thanks @alenia! 👍 

`header: headerOptions => (isShittyIPhone() ? null : <Header {...headerOptions} />),`

**Comment by gabrieljoelc** [comment]
what's the `import` for doing this with RN Navigation v5 and v6?
