### ISSUE TITLE
Header undefined?

### ISSUE THREAD

**Issue by JulianKingman** [react-community/react-navigation#1445]
### Current Behavior
I'm trying to upgrade the `@shoutem/ui` package to use the navigation from this library, since NavigationExperimental was recently deprecated. I'm trying to use the propTypes from the header and am getting the following error: `undefined is not an object (evaluating _reactNavigation.Header.propTypes`
![screen shot 2017-05-10 at 10 11 06 am](https://cloud.githubusercontent.com/assets/1566400/25903016/3b70f1a8-3569-11e7-9d03-9accd3ec5485.png)

### Expected Behavior
Why is Header undefined? I import it like this:
`import  {Header as NavigationHeader} from 'react-navigation';`
then I use `NavigationHeader.propTypes` in the propTypes of a header component that's effectively extending this one.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.7
| react-native     |  0.42.0
| node             | 
| npm or yarn      |

**Comment by spencercarli** [comment]
Hey @JulianKingman did you ever figure out a solution for this? I'm not familiar with how flow works but the Header component doesn't have propTypes, but it doesn't really explain the error you received.

I'm going to close this (cleaning up issues) but if it's still an issues please re-open.

**Comment by JulianKingman** [comment]
This issue is moot.
