### ISSUE TITLE
Hide Tabbar in runtime

### ISSUE THREAD

**Issue by DharaSingh** [react-community/react-navigation#1447]
I'm trying to hide the tabBar in run-time based on keyboard events. In iOS this snippet is working as per expectation 
**this.props.navigation.setParams({tabBar:{visible:false}})**
but in android this method is not working as expected like iOS. 

Any reason. I'm using 1.0.0-beta7 version

**Comment by DharaSingh** [comment]
code snippet - 

componentWillMount() {
this.keyboardDidShowListener = Keyboard.addListener('keyboardDidShow', this._keyboardDidShow.bind(this));
this.keyboardDidHideListener = Keyboard.addListener('keyboardDidHide', this._keyboardDidHide.bind(this));
}

componentWillUnmount() {
this.keyboardDidShowListener.remove();
this.keyboardDidHideListener.remove();
}

_keyboardDidShow() {
this.props.navigation.setParams({tabBar:{visible:false}})
}

_keyboardDidHide() {
debugger;
this.props.navigation.setParams({tabBar:{visible:true}})
}

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!

**Comment by nishiltamboli** [comment]
@DharaSingh Did you get this resolved mate? I am unable to do it.
