### ISSUE TITLE
navigate 2 screen back on single press 

### ISSUE THREAD

**Issue by abhitheawesomecoder** [react-community/react-navigation#1448]
<Button
          onPress={() => goBack()}
          title="Go back from this HomeScreen"
        />
with this i am going one screen back. how can i go 2 screen back on single press

**Comment by TyrealGray** [comment]
https://reactnavigation.org/docs/navigators/navigation-prop#goBack-Close-the-active-screen-and-move-back
```
<Button onPress={() => goBack('screen-123')}
               title="Go back from screen-123"
/>
```

**Comment by abhitheawesomecoder** [comment]
using the code below i am going one screen back

<Button
          onPress={() => goBack()}
          title="Go back from this HomeScreen"
        />

how can i go 2 screen back on single press action


	

using the code below i am going one screen back

<Button
          onPress={() => goBack()}
          title="Go back from this HomeScreen"
        />

how can i go 2 screen back on single press action

I am using this code to initialize the navigator

const RouteConfigs = {
    Login: {screen:Login},
    Home: {screen:Home},
    Chat: {screen:Chat},
    Facebook: {screen:Facebook},
    Facebookgallery: {screen:Facebookgallery}    
}

const StackNavigatorConfig = {
    headerMode: 'none',
}

export default StackNavigator(RouteConfigs, StackNavigatorConfig)


what is 'screen-123' here ?

**Comment by MovingGifts** [comment]
You can do it with `settimeout` for your second navigate, so one to goBack, and a setTimeout with another one to go back in it, they need to execute at a different time. [This should help guide you.](https://github.com/react-community/react-navigation/issues/978)

**Comment by abhitheawesomecoder** [comment]
I tried something like this but only one goBack works ie it goes one screen back and not two screen back

_goback(){
    const {goBack} = this.props.navigation
    setTimeout(function(){ goBack() }, 500)
    goBack()
  }

onPress={ () => this._goback() }

**Comment by MovingGifts** [comment]
This would be my best guess. 
```js
_goback(){
  const {goBack} = this.props.navigation;
  goBack();
  setTimeout(function(){ goBack() }, 500);
}

onPress={ () => this._goback() }
```
If it doesn't work, maybe someone else can jump in.

**Comment by abhitheawesomecoder** [comment]
nopes its working same as my code. no difference. only one goBack() get called

**Comment by TyrealGray** [comment]
If goBack() does not work, try dispatch instead.

**Comment by abhitheawesomecoder** [comment]
already tried but there isn't much difference

**Comment by ptmt** [comment]
If you see the source code
```
const backRoute = state.routes.find(
            /* $FlowFixMe */
            (route: *) => route.key === action.key
          );
```
So it's not `routeName`that you should passing. You need to find the route `key` (something like `"id-1494508623037-2"` in my case).

**Comment by abhitheawesomecoder** [comment]
yes i just figured it out and i am able to move from a specific screen back but 

how can i pass a param when i go back?

**Comment by julesmoretti** [comment]
@ptmt - How did you look up the ID? I tried so view the states with no luck:

const { navigate, goBack, state } = this.props.navigation;
<Text>{state.routes}</Text>

I also tried `goBack="Init"` and that does not work also...

**Comment by ptmt** [comment]
@abhitheawesomecoder 
> how can i pass a param when i go back?

Did you solve this? I suggest using Redux integration for that purpose.

@julesmoretti In my case, I was able to solve this by passing it via param, and yes, it should be contained in routes state, what's the output for `console.log(state)`?

**Comment by pvinis** [comment]
this is my *temporary* solution:
```

export function navGoBack(navigation, routeName) {
  const { goBack } = navigation
  const { routes } = navigation.reduxState.nav

  let nToGoBack = routes.length+1
  let routeKeyToGoBackFrom = null
  for (let i = routes.length - 2; i >= 0; i--) {
    if (routes[i].routeName === routeName) {
      nToGoBack = routes.length-1 -i
      routeKeyToGoBackFrom = routes[i+1].key
     break
    }
  }
// choose one
// version 1
  for (let i = 0; i < 2; i++) {
    goBack(null)
  }

// version 2
  if (routeKeyToGoBackFrom !== null) {
    goBack(routeKeyToGoBackFrom)
  }
}
```
both versions work, but both versions animate both `back` actions, so instead of going "directly" 2 screens back, it shows it like you are "scrolling" back the screens one by one.

**Comment by boliveira** [comment]
Hi,

I was having the same problem and the path I ultimately took was to send a special action to redux and generating a new state with the screen that I wanted to go back selected. 
Very cumbersome, but if you do that, you avoid the animations of both back actions and works like a charm.

**Comment by antoinegrelard** [comment]
@boliveira do you have an example of the code you wrote that is working?

**Comment by boliveira** [comment]
@antoinegrelard , sorry for the late response, I was in vacation.

Certainly, so I did something like this (I am omitting the parts that are not relevant):

//navigationReducer

```
export default function navigationReducer(state = initialState, action) {
...

//Handle special back case
if (
    action.type === "Navigation/BACK" &&
    action.key === "BACK_MARKETDATA_FROM_ADD_SECURITIES"
  ) {
newNavigationState = getMarketDataState(state.nav);
} else {
newNavigationState = AppNavigator.router.getStateForAction(
      action,
      state.nav
    );
}

...
}

function getMarketDataState(state) {
  const newState = { ...state };

  const drawerCloseRoute = newState.routes[0];

  const streamerRoute = { ...drawerCloseRoute.routes[0] };

  streamerRoute.index = 0;
  streamerRoute.routes.splice(1, 1);

  const newDrawerCloseRoute = { ...drawerCloseRoute };

  newDrawerCloseRoute.routes[0] = streamerRoute;

  newState.routes[0] = newDrawerCloseRoute;

  return newState;
}
```

Then in container component I just do:

this.props.navigation.goBack("BACK_MARKETDATA_FROM_ADD_SECURITIES");

If you have any questions about the code, please, be confortable to ask :)

**Comment by vishaljadav24** [comment]
I tried this and it's worked.
```js
const goDoubleBack = () => {
    setTimeout(() => {
            this.props.navigation.goBack(null);
            this.props.navigation.goBack(null);
    }, 50);
};
```

**Comment by steinarsa** [comment]
This worked for me (the code is in the navigation reducer).
`
...
const tempState = AppNavigator.router.getStateForAction(
    NavigationActions.back(),
        state,
    );
nextState = AppNavigator.router.getStateForAction(
    NavigationActions.back(),
    tempState,
);
...
return nextState || state;
`

**Comment by victorbadila** [comment]
Any idea why the previous answer by @vishaljadav24 was down voted that much? I tried it and it worked well for me, is there something else to it that makes it not desirable?

**Comment by brentvatne** [comment]
another alternative, if you are want to go back twice in a stack: `this.props.navigation.pop(2)`

**Comment by ivan-ha** [comment]
Here's my 2 cents.

I have this: `HomeScreen` -> `QrCodeScanner` -> `PaymentScreen`
And target is go back to `HomeScreen`after some event in `PaymentScreen`.

My original attempt is `this.props.navigation.goBack('screen-key-of-QrCodeScanner')`, [as proposed here](https://github.com/react-navigation/react-navigation/issues/1213#issuecomment-309643674). 

It works, however there will be 2 navigate back animation (QrCodeScanner will flash on screen for < 1s). Which I guess probably will happen for similar solution like invoking `.goBack(null)` twice or `.pop(2)`.

Then my 2nd attempt is [resetting the navigation state](https://reactnavigation.org/docs/navigation-actions.html#reset) as if just `HomeScreen` exist.
```js
const actions = [ NavigationActions.navigate({ routeName: 'HomeScreen' }) ]

const resetAction = NavigationActions.reset({
  index: actions.length - 1
  actions
})

this.props.navigation.dispatch(resetAction)
```
This work perfectly for me, without weird navigation animation. However, need to note that after `reset`, the `HomeScreen` will be brand new, e.g. you'll lost the scroll position. And it gonna mount again, e.g. APIs call in `componentDidMount` will fire again.

**Comment by brentvatne** [comment]
@ivan-ha - thanks for describing this, can you create a new issue that provides an example of both of these situations? we can then discuss further there. certainly sounds like something we should fix though, so i hope you get around to creating an issue for it!

**Comment by benoptimus** [comment]
i got the same problem and this is how i fix it:
`const prevGetStateForActionAppNavigator = AppNavigator.router.getStateForAction;
AppNavigator.router = {
    ...AppNavigator.router,
    getStateForAction(action, state) {
      if(state && state.routes && state.routes.length > 2
        && action.type === 'back_2_screen') {
        let routes = state.routes.slice();
        routes.pop();
        routes.pop();
        return {
            index: routes.length - 1,
            routes: routes
        };
     }
      return prevGetStateForActionAppNavigator(action, state);
    },
}`

and then  `props.navigation.dispatch({type: 'back_2_screen'})` to go back twice.

**Comment by jamessawyer** [comment]
how can I go back the first screen from the third screen without second screen show up? eg:stack: **`A -> B -> C`**, now I want go back like **`C -> A`**

**Comment by Kida007** [comment]
@jamessawyer 
try @brentvatne 's solution.
```
this.props.navigation.pop(2)
```

**Comment by Donhv** [comment]
this.props.navigation.navigate("A").

**Comment by IgorMing** [comment]
Just a point. (for version ˆ3.x)
If you guys are using `.reset` to do it, remeber that function is not part of `NavigationActions` anymore. Use `StackActions.reset` instead.

**Comment by netpoe** [comment]
In my case, I needed to go back from a child screen to the parent screen. 

Adding `resetOnBlur: true` to `createBottomTabNavigator` options did the work for me. 

https://reactnavigation.org/docs/en/bottom-tab-navigator.html#bottomtabnavigatorconfig

**Comment by bobowork** [comment]
I ended up using this.props.navigation.navigate({
      routeName: 'route-name',
      key: 'route-key'
    })

Per the documentation, https://reactnavigation.org/docs/en/navigation-actions.html
key - String - Optional - The identifier for the route to navigate to. Navigate back to this route if it already exists

**Comment by chengsam** [comment]
How about navigate 2 screen back when swipe on iOS? Can I override the swipe behavior?

**Comment by lincolnbf** [comment]
> How about navigate 2 screen back when swipe on iOS? Can I override the swipe behavior?

Hmmm, interesting. **Maybe** you can pass a param when swiping, and on the screen if that param exists, you go back another time.

**Comment by victorwvieira** [comment]
> another alternative, if you want to go back twice in a stack: `this.props.navigation.pop(2)`

This solution worked for me. Tks!
