### ISSUE TITLE
Weird behavior when navigating  back in a nested stack inside drawer

### ISSUE THREAD

**Issue by TsuryKnox** [react-community/react-navigation#1449]
I have these navigators:

```
const AppNavigator = StackNavigator({
  List: {
    screen: ListContainer
  },
  Login: {
    screen: LoginContainer
  }
});

export const MyDrawerNavigator = DrawerNavigator({
  Main: {
    screen: AppNavigator
  },
  Settings: {
    screen: SettingsContainer
  }
});

```

The stack is nested inside of the drawer.
I start from the List screen, then open the drawer and go to Settings screen. From there I go to the Login screen. Once I finish there I navigate back. I expect to find myself in the Settings screen but for some reason I find myself in the List screen.

Maybe I am missing something here? Should I do something other than sending a 'back' action when I finish with the Login screen?

**Comment by nithin-c** [comment]
Me too having the same problem.Going back leads me to inital route given in the DrawerNavigator.

**Comment by Kishanjvaghela** [comment]
Any solution?

**Comment by neegool** [comment]
I'm having a similar problem with my project. I'm still trying to figure out a solution, but I suspect that the problem occurs because the back event is still being handled by the `AppNavigator` component even if a nested navigator is on top of the stack.

I'm working on handling the back event myself using RN's [BackHandler](https://facebook.github.io/react-native/releases/next/docs/backhandler.html) class, and I'm also going to keep track to a reference of the active navigator on screen.

**Comment by TsuryKnox** [comment]
I now have an even more complex hierarchy and the back button does not function as expected at all. Can someone please shed some light over this?

If I navigate in the following way: List -> SettingsMain -> Users -> Login and then press back, I am returned to LIst, since List comes before Users in the main StackNavigator. Why isn't the control transferred to the previous Navigator?

```
export const AppNavigator = StackNavigator({
  List: {
    screen: ListContainer
  },
  Login: {
    screen: LoginContainer
  }
});

export const SettingsNavigator = StackNavigator({
  SettingsMain: {
    screen: SettingsContainer
  },
  Users: {
    screen: UsersContainer
  }
});

export const DrawerWrapperNavigator = DrawerNavigator({
  AppMain: {
    screen: AppNavigator
  },
  Settings: {
    screen: SettingsNavigator
  }
});

class AppWithNavigationState extends Component {
  render() {
    const { dispatch, nav } = this.props;
    return <DrawerWrapperNavigator ref={(nav => { this.navigator = nav; }} navigation={addNavigationHelpers({ dispatch, state: nav })} />;
  }
}
```

**Comment by baldurpan** [comment]
+1

**Comment by Athosone** [comment]
I have the same issue in a Tabbarnavigator.
I managed to fixed it (I dont know at all if its clean..) by ignoring 'Navigate/Back' in my main navigator


`var tabBarPreviousState = {}

const tabBarReducer = (state, action) => {
   if (action.type == 'Navigation/BACK') {
    return tabBarPreviousState
  }
  tabBarPreviousState = state
  return TabBar.router.getStateForAction(action, state)
}
const tabOneReducer = (state, action) => {
  return NavigatorTabOne.router.getStateForAction(action, state)
}
const tabTwoReducer = (state, action) => {
  return NavigatorTabTwo.router.getStateForAction(action, state)
}`

**Comment by kcfgl** [comment]
I'm having a similar issue and posted a question on SO: https://stackoverflow.com/q/45480755/1276359

I'm just looking to go back to the screen that called .navigate.  Even though we changed Stacks. 

Anyone come up with a solution thats clean?

**Comment by kelset** [comment]
Pinging OP @TsuryKnox since this issue is quite old and related to an old version of the lib. If no answer I'll close in 7 days.

**Comment by kelset** [comment]
Hi there @TsuryKnox ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue (especially if it's a bug report) please open a new issue that uses the new Issue Template to provide some more details to help us solve it.

**Comment by sfm2222** [comment]
I still have the same issue can anyone provide a clean solution to resolve this =( I want to show back button on top on iOS and on android navigate to last screen using hardware back button. 

**Drawer Navigator**

/* @flow */

import React from "react";
import { DrawerNavigator } from "react-navigation";

import Home from "./components/home/";
import SplashPage from "./components/splashscreen/";
import SideBar from "./components/sidebar";
import Contact from "./components/Contact/";



const Drawer = DrawerNavigator(
  {
   Home: { screen: Home },
    Contact: { screen: Contact},
  },
  {
    navigationOptions: {
      gesturesEnabled: false
    },
  initialRouteName: "Home",
    contentOptions: {
      activeTintColor: "#e91e63"
    },
    drawerPosition: 'right',
    contentComponent: props => <SideBar {...props} />
  }
);



export default Drawer;

**Stack Navigator**

/* @flow */

import React from "react";

import { Platform } from "react-native";
import { Root } from "native-base";
import { StackNavigator} from "react-navigation";
import Drawer from "./Drawer";
import Contact from "./components/Contact"
import Register from "./components/Register"
import Home from "./components/home/";

const AppNavigator = StackNavigator(
    {
        Drawer: {screen: Drawer},
       Home: { screen: Home },
        Register: {screen: Register},
    },
    {
        initialRouteName: "Home",
           headerMode: Platform.OS == "android" ? "none" : "float",
        header: (navigation) => ({
            left: (
                <Button
                  title="Back"
                  onPress={ () => navigation.goBack() }  
                />
              )
          })
    }
);

export default () =>
    <Root>
        <AppNavigator />
    </Root>;

**Comment by zarincheg** [comment]
Here is the fix: https://github.com/react-navigation/react-navigation/pull/3362

**Comment by LukeSmetham** [comment]
Im having the same problem and the above fix from @zarincheg doesn't seem to work either... 

Heres my navigators:

```
// Root Navigator

const RootNavigator = DrawerNavigator({
  Charities: {
    screen: CharitiesNavigator
  },
  Events: {
    screen: EventsNavigator
  },
  // MapView: {
  //   screen: MapView
  // }
}, {
  drawerOpenRoute: 'DrawerOpen',
  drawerCloseRoute: 'DrawerClose',
  drawerToggleRoute: 'DrawerToggle',
  backBehaviour: 'none',
  contentComponent: ({navigation})=> <Drawer navigation={navigation} />
})

// Charities

const CharitiesNavigator = StackNavigator({
  ChairtiesHome: {
    screen: Charities
  },
  CharityDetail: {
    screen: CharityDetail
  }
}, {
  headerMode: 'screen',
  backBehaviour: 'none',
  cardStyle: {
    backgroundColor: '#F7F9FA'
  }
})

// Events

const EventsNavigator = StackNavigator({
  EventsHome: {
    screen: Events
  },
  EventDetail: {
    screen: EventDetail
  }
}, {
  headerMode: 'screen',
  backBehaviour: 'none',
  cardStyle: {
    backgroundColor: '#F7F9FA'
  }
})
```

The user can tap a link in the EventDetail screen that will link them to the CharitiesDetail screen for a given charity.

However, when navigating back (both hardware and with goBack) from CharitiesDetail I takes me to the CharitiesHome screen, rather than back to EventDetail...

Any help would be greatly appreciated!

**Comment by KalaiselvanMahendran** [comment]
@TsuryKnox Did you fixed this ? am also facing the same issue.
