### ISSUE TITLE
Deep Linking not working on StackNavigator inside a DrawerNavigator

### ISSUE THREAD

**Issue by maggialejandro** [react-community/react-navigation#1450]
I need to open a StackNavigator route that is inside a DrawerNavigator by doing the following:
```{r, engine='bash', count_lines}
adb shell am start -W -a android.intent.action.VIEW -d "deeplinking://deeplinking/page" com.deeplinking
```
Here is a [repo](https://github.com/maggialejandro/deep) with the code

### Current Behavior
The app opens to the initial route. 

### Expected Behavior
The app should open PageScreen

### Your Environment
I'm running the app on Android 6.0.1 on a real device.

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.6
| react-native     |  0.42.0
| node             | v7.5.0
| npm or yarn      | 4.1.2

**Comment by diegorodriguesvieira** [comment]
+1

**Comment by diegorodriguesvieira** [comment]
@maggialejandro Can you post your code to tell us how you are doing?

**Comment by maggialejandro** [comment]
@diegorodriguesvieira Here is the [code](https://github.com/maggialejandro/deep) Diego

**Comment by diegorodriguesvieira** [comment]
Thanks a lot @maggialejandro, I will try...

**Comment by maggialejandro** [comment]
Updating the dependencies fixes the issue
```
"react": "16.0.0-alpha.12",
"react-native": "0.45.1",
"react-navigation": "1.0.0-beta.11"
```
