### ISSUE TITLE
How to stack screen from TabNavigation screen?

### ISSUE THREAD

**Issue by juliensanmartin** [react-community/react-navigation#1451]
It's more a question than an issue.

First here is my navigation structure:
TabNavigation:
  |---- Home Screen 
  |---- Settings Screen

I would like the Settings screen to stack over the Home screen when I click on the Tab 'Settings' in a way that the settings screen takes half of the screen space and we can still see the HomeScreen.
The same behavior we could have with StackNavigator like so:
StackNavigation:
  |---- Home Screen 
  |---- Settings Screen

But then I don't have the TabNavigation displayed, and I have to manually create button that navigate from one screen to another.

It's kind of having both StackNavigation and TabNavigation at the same time.

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
