### ISSUE TITLE
Drawer Content Component

### ISSUE THREAD

**Issue by mynameisbams** [react-community/react-navigation#1458]
Is anyone using drawer content component? how to use it?

**Comment by rmevans9** [comment]
You simply set the property to the component you want to use similar to how they do it in this example from the docs: https://reactnavigation.org/docs/navigators/drawer#Example:

You can use a imported component as well if needed.

**Comment by encorex** [comment]
Here you go:

import { Dimensions } from 'react-native'

import DrawerContent from '../app/components/DrawerContent'

const deviceWidth = Dimensions.get('window').width

const drawerConfiguration = {
  initialRouteName: 'MainStackNavigatior',
  headerMode: 'screen',
  drawerWidth: deviceWidth / 1.38,
  contentComponent: DrawerContent,
  drawerLockMode: 'locked-closed'
}

export default drawerConfiguration


and my DrawerContent is a standard react view with list elements

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
