### ISSUE TITLE
does it need to declared many StackNavigator for jump to different style screen?

### ISSUE THREAD

**Issue by aqnaruto** [react-community/react-navigation#1459]
i mean in some page such as  login ,first page i need to set  `headerMode:none`  ,but in other page ,such as various subpage i need the  `headerMode:screen` .

if i user old navigator ,i just need to declare one navigator , and customizing the header in page,  but how should i do with this?

**Comment by aqnaruto** [comment]
sorry i found it

**Comment by xuanheScript** [comment]
I am sorry, I have encountered this problem, how do you solve it?
