### ISSUE TITLE
Disable Bottom View In/Out Animation

### ISSUE THREAD

**Issue by dkpalmer** [react-community/react-navigation#146]
We just started trying out RN. It seems in every nav library (mostly based on Navigation/NavigationExperimental) pushing a second view (V2) on the stack results in the first view (V1) slightly sliding behind while V2 takes over the screen. Likewise, popping V2 results in V1 sliding back. Can this animation be disabled (where V1 stays static while V2 slides in/out on top)?

**Comment by ericvicenti** [comment]
Have you tried `StackNavigator` `mode: 'modal'`? The new screen comes from the bottom, and the old screen fades out, but it doesn't move.

Regardless, maybe we should add the ability to override the generic style interpolator of the `Card`?

**Comment by dkpalmer** [comment]
The modal behavior is definitely closer to what I'm looking for (except wanting to slide from left/right instead of from bottom, and with a fixed header). Even being able to disable the fade would be awesome.

**Comment by grabbou** [comment]
Closing in favour of #175

**Comment by spencercarli** [comment]
Whoops! Looks like this was never closed - doing some clean up 😄
