### ISSUE TITLE
Have any way to let the drawer navigator Item not be show

### ISSUE THREAD

**Issue by SleetShang** [react-community/react-navigation#1461]
I don't want to let all routers show the itemView. It is because that there are some routers I need custom the item in other position.Thanks your help.

**Comment by GregoryPotdevin** [comment]
When using the DrawNavigator, you can specify a component to render the content of the drawer : `contentComponent`
```jsx
{
  drawerWidth: 200,
  drawerPosition: 'right',
  contentComponent: props => <ScrollView><DrawerItems {...props} /></ScrollView>
}
```

`DrawerItems` takes the list of routes directly from the router, so you can't really filter that. But you could probably just clone DrawerItems and implement your own version : https://github.com/react-community/react-navigation/blob/master/src/views/Drawer/DrawerNavigatorItems.js

**Comment by fozzarelo** [comment]
Yea, I would like a solution for this too..

**Comment by DominicTobias** [comment]
```js
const hiddenDrawerItems = [
  'Login',
];

const Navigator = DrawerNavigator({
  Login: { screen: Login },
  Play: { screen: Play },
}, {
  initialRouteName: 'Play',
  contentComponent: (props) => {
    const clonedProps = {
      ...props,
      items: props.items.filter(item => !hiddenDrawerItems.includes(item.key)),
    };
    return <DrawerItems {...clonedProps} />;
  },
});
```

**Comment by devvtms** [comment]
Hy, i improved this with lodash. you pass keys, what you need show
```js
const filterItems = (props, keys) => ({
  ...props,
  items: _(props.items).keyBy('key').at(keys).value(),
});
//...
<DrawerItems {...filterItems(props, ['sceneKey', 'sceneKeyTwo'])} />
```

**Comment by kelset** [comment]
Pinging OP @SleetShang since this issue is quite old and related to an old version of the lib. If no answer I'll close in 7 days.

Moreover, solutions provided by @DominicTobias & @devvtms are good imho.

**Comment by kelset** [comment]
Hi there @SleetShang ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.

**Comment by Leleking** [comment]
@dbvt10 just what i needed. Thanks
