### ISSUE TITLE
Question - Different headers

### ISSUE THREAD

**Issue by leesolway** [react-community/react-navigation#1462]
Apologies if this is not the best place to ask.
Using react-native.

My App needs a variation on headers... 
- Most screens needs a logo and title
- A few screens need a title and a back button
- A few screens require the header to be hidden, with a custom back button implemented

I can't see how you would go about having various header styles. 

Thanks,
Lee

**Comment by GregoryPotdevin** [comment]
Each screen can define it's own header : 
```jsx 
class ProfileScreen extends React.Component {
  static navigationOptions = ({ navigation, screenProps }) => ({
    title: navigation.state.params.name + "'s Profile!",
    headerRight: <Button color={screenProps.tintColor} {...} />,
  });
```

One of the options is "header", which hides the header if it is set to `null`

**Comment by leesolway** [comment]
Thanks for the response.. 

I didn't explain my question as well as i should have. 
The header will have two different designs:

Style 1:-
Top Bar (Logo left, Button Right)
Second Bar (Title Middle)

Style 2:-
Top Bar  (Button Left, Title Middle)

Using  a pre-done header component or setting the header into a mode, to render either variation would be the ideal way.
