### ISSUE TITLE
How to reset TabNavigator to StackNavigator or reset StackNavigator to TabNavigator

### ISSUE THREAD

**Issue by lucasleelz** [react-community/react-navigation#1463]
### Expected Behavior
I hope `TabNavigator` can be reset to `StackNavigator` and vice versa. That is,`TabNavigator`,`StackNavigator` can switch freely. And can not return to the previous Navigator.

#### Navigation structure
```
const MainTab = StackNavigator({
    Main: {
        screen: MainScreen,
    }
});

const SettingsTab = StackNavigator({
    Settings: {
        screen: SettingsScreen,
    }
});

const MainNavigator = TabNavigator({
    MainTab: {
        screen: MainTab,
    },
    SettingsTab: {
        screen: SettingsTab,
    },
});

const LoginNavigator = StackNavigator({
    Login: {
        screen: LoginScreen,
    }
});
```

If you no login, go to the login screen. 
If you log in, go to the main screen.
If you log out, go to the login screen. Can not return to the main screen.

### Your Environment
| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.9
| react-native     |  0.44.0
| node             | 7.5.0
| npm       | 4.1.2

**Comment by supportclik** [comment]
+1
how to transit between XXXNavigator cleaning the previous one.
i am on StackNavigator in login, if login successes , go to StackNavigator Main and cannot back to login anymore.

**Comment by qianlanse** [comment]
Same question, how do you deal with it at last?

**Comment by lucasleelz** [comment]
@qianlanse 
https://github.com/react-community/react-navigation/pull/1384
I use above way, 
because there is no merger for a long time, 
I had to maintain a version of their own, And posted at `private npm`(`Verdaccio`) .

**Comment by devanshsadhotra** [comment]
@supportclik  i have answer to your question 
``` const { dispatch } = this.props.navigation;
                    dispatch({type:'Navigation/RESET', actions: [{ type: 'Navigate', routeName: 'TabsScreen'}], index: 0 }
                )```

**Comment by devanshsadhotra** [comment]
and i am facing @lucasleelz exactly as you stated , my logout is in tab navigator and after logging out , i should move to login screen again (which on stack navigator)

**Comment by devanshsadhotra** [comment]
@spencercarli  u closed the issue , but there hasn't been any solution!!! please let me know , if anyone has the solution
