### ISSUE TITLE
Keyboard move tabbar up.

### ISSUE THREAD

**Issue by LeDigital** [react-community/react-navigation#1464]
So steps:

Tap on input field and keyboard appears so it pushes tabbar up.

Is it possible to hide tabbar when keyboard appears?

**Comment by computerjazz** [comment]
https://github.com/react-community/react-navigation/issues/618

**Comment by chandrabudiman** [comment]
this work fine for me : 
at AndroidManifest.xml file :
.
I changed this : android:windowSoftInputMode="adjustResize"> to this : 
`android:windowSoftInputMode="stateAlwaysHidden"`
