### ISSUE TITLE
i feel desperate with this navigation

### ISSUE THREAD

**Issue by aqnaruto** [react-community/react-navigation#1467]
old navigator is much better .

this navigation's android transaction-animation is different from ios's。
 i need the same goback-gesture and goback-transaction-animation in android and ios。

this navigation is bugly and make no enhancement than old navigator. it did not fixed the android goback-animation not enough fluetly 's problem

**Comment by aqnaruto** [comment]
![image](https://cloud.githubusercontent.com/assets/9067159/25983656/b5d1b774-3718-11e7-8b40-9586ea5e3f81.png)
in  document the default transition is card ,but still is modal in android

**Comment by koenpunt** [comment]
You don't have to use it. This library is provided free of charge, and is open source, so if you don't like something a about it you can propose a fix. Just complaining about how bad you think something isn't going to help anyone.

**Comment by dioxide** [comment]
agree, headerMode no effect!

**Comment by aqnaruto** [comment]
thank your reply ,but official reactnative in 0.44 is delete navigator ,  we are  forced to use this react-navigation.
on ios, duaring transaction-animation ,the text will be blured  ,it is fell bad.
and on android,  the mode:'card'   make no effect,  and  it is do not have the same  goback-gesture  with ios.   it is just use modal to avoid android goto-goback-Fluently's problem instead of fix this problem.
@koenpunt

**Comment by ippa** [comment]
@aqnaruto
in terminal in your projectfolder: 
`yarn add react-native-deprecated-custom-components`
...and then in your code:
`import {Navigator} from "react-native-deprecated-custom-components";`

**Comment by koenpunt** [comment]
> we are forced to use this react-navigation.

You are not forced, but recommended. 

> by the way, i am really admire opensouce-spirit.

If so, try to change your tone of voice, that will probably yield a more positive and usable response.

**Comment by aqnaruto** [comment]
thank you @koenpunt @ippa

**Comment by koenpunt** [comment]
`mode: 'card'` uses a different transition config on android. To have it behave on Android the same as on iOS you can use something like the following:

```js

import CardStackStyleInterpolator from 'react-navigation/src/views/CardStackStyleInterpolator';

export default StackNavigator({
  Home: {
    screen: HomeScreen,
  },
}, {
  transitionConfig: () => ({
    screenInterpolator: CardStackStyleInterpolator.forHorizontal,
  }),
});

**Comment by aqnaruto** [comment]
@koenpunt great, thank you, i recomment to add this into https://reactnavigation.org/docs/navigators/stack

**Comment by dioxide** [comment]
@koenpunt, i have a question: how to make a same UI for headerBack, headerTitle component between iOS and android?

**Comment by aqnaruto** [comment]
@dioxide  write style by youself ,   do you figure out the android go-back-gesture problem ,and blur in ios 's problem

**Comment by igroz777** [comment]
Just want to say that the above does not work for me.
