### ISSUE TITLE
InitialRouteName with back behaviour

### ISSUE THREAD

**Issue by RUIFERNANDE5** [react-community/react-navigation#1469]
I believe there's a bug on TabNavigator when InitialRouteName is set and it is not on first position.
For the given structure:

```
RootStack

    DrawerNavigator

       TabNavigator

       OtherStacks`
```

If TabNavigator is:

```
TabsStack = TabNavigator({
    Favorites: {
        screen: FavoritesStack,
        navigationOptions: {
            tabBarIcon: ({ focused }) => <TabIcon image="star" label="Favorites" selected={focused}/>
        },
    },
    Calls: {
        screen: CallsStack,
        navigationOptions: {
            tabBarIcon: ({focused}) => <TabIcon image="phone" label="Calls" selected={focused}/>
        },
    },
    Contacts: {
        screen: ContactsStack,
        navigationOptions: {
            tabBarIcon: ({focused}) => <TabIcon image="contacts" label="Contacts" selected={focused}/>
        },
    }
{
    initialRouteName: 'Calls',
    lazyLoad: true
    ....
}});
```

If I dispatch `NavigationActions.back(null) ` inside `OtherStacks` there is no animation while navigating to the previous scene. 
Also, sometimes on emulator if I have `lazyLoad` set to false the first Tab Item shows for a second before it loads the defined initialRoute Scene.

Is anyone experiencing this ? Didn't find anything related on Issues (Could've missed it tho)

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.8
| react-native     |  ~15.4.1
| node             |  7.7.2
| npm       | 4.1.2

**Comment by RUIFERNANDE5** [comment]
any1?

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
