### ISSUE TITLE
How to access this.props from `static navigationOptions=`

### ISSUE THREAD

**Issue by ericls** [react-community/react-navigation#147]
Hello everyone,

My i10n related information are stored in the props of components, however, static properties cannot access `this.props`, which makes i10n for headers and labels difficult.

Is there any work arounds?

Thank you very much, community!

**Comment by rafaelcorreiapoli** [comment]
On your componentDidMount, you can use 
```js
this.navigation.setParams({
 myTitle: this.props.myTitle
})
```

Then, pass a function to your header on static props. This function has access to the params you set before

```js
static navigationProps = {
 header: ({ state }) => {
 return {
  title: state.params.myTitle
 }
}
}
```

You can use the setParams function on componentWIllReceiveProps, but don't forget to compare this.props with nextProps to see if there was a change to myTitle before calling setParams, or you will enter a infinity loop

**Comment by ericvicenti** [comment]
Yep, and you can also put that info in the route params, if you prefer.

**Comment by srameshr** [comment]
@rafaelcorreiapoli 
```
static navigationProps = {
 header: ({ state }) => {
 return {
  title: state.params.myTitle
 }
}
}
``` 
has now been refactored into 
```
static navigationProps = {
  headerLeft: <Ele></Ele>
}
```

How do I access ```navigate``` in onPress of Ele?

**Comment by rafaelcorreiapoli** [comment]
Since it is a react component, it call be a connected component which has access to whatever you want :P

**Comment by RobertSheaO** [comment]
@srameshr you can access navigation this way...

```
navigationOptions: ({navigation}) => ({
  title: `${navigation.state.params.name}'s Profile'`,
}),
```

**Comment by ceefour** [comment]
@rafaelcorreiapoli thanks but how do I access callback methods, e.g.

    <Button onPress={this._createAlbum.bind(this)}>

If there is no this ?

**Comment by sachinwak** [comment]
In 0.47    
@rafaelcorreiapoli    unfortunately above solution not work for me. it give me error as this.navigation is not defined.

```
this.navigation.setParams({
 myTitle: this.props.myTitle
})
```


Below is my workaround. It perfectly get params from props

```
componentWillMount(){
        const {setParams} = this.props.navigation;
        setParams({websiteURL: this.props.websiteURL});
}

static navigationOptions = ({ navigation  }) => {

        const {state} = navigation;

        if(state.params != undefined){
            return { 
                headerRight: <ShareAppButton shareConfig={{
                    url: state.params.websiteURL,
                    subject: "All Recipes Made Easy Android App"
                }}/>
            }
        }
        
    };
```

**Comment by danstepanov** [comment]
Hey all, I have `this.props.imageUrl` defined and I'd like to do 

static navigationOptions = ({navigation}) => ({
    title: 'Newsfeed',
    headerLeft: (
      <TouchableWithoutFeedback onPress={() => navigation.navigate('DrawerOpen')} style={styles.userImageContainer}>
        <View style={styles.userImageBackground}>
          <Image style={styles.userImage} source={{ imageUrl }} resizeMode="cover" />
        </View>
      </TouchableWithoutFeedback>
    )
})
```

I can't seem to do so via @sachiwak's approach or @rafaelcorreiapoli's. Any help would be greatly appreciated :)

**Comment by sachinwak** [comment]
@danstepanov  I think this will not be good solution but, It will work.   define a variable outside class as `var imageURL = "";`   inside class 

```componentWillMount(){
       imageURL= this.props.imageUrl ;
}```

After this it will be easy to use in 

```
static navigationOptions = ({navigation}) => ({
    title: 'Newsfeed',
    headerLeft: (
      <TouchableWithoutFeedback onPress={() => navigation.navigate('DrawerOpen')} style={styles.userImageContainer}>
        <View style={styles.userImageBackground}>
          <Image style={styles.userImage} source={{ imageURL  }} resizeMode="cover" />
        </View>
      </TouchableWithoutFeedback>
    )
})
```

**Comment by danstepanov** [comment]
@sachinwak I was actually just able to do it! I'm using GraphQL and React-Apollo to get this particular prop so I needed to make sure it was there first ;) Probably not the most elegant solution but it works!

```
componentWillReceiveProps() {
    if (this.props.viewer && !this.props.navigation.state.params) {
      this.props.navigation.setParams({imageUrl: this.props.viewer.imageUrl});
    }
  }
```

```
static navigationOptions = ({navigation}) => ({
    title: 'Newsfeed',
    headerLeft: (
      <TouchableWithoutFeedback onPress={() => navigation.navigate('DrawerOpen')} style={styles.userImageContainer}>
        <View style={styles.userImageBackground}>
          {navigation.state.params ? <Image style={styles.userImage} source={{ uri: navigation.state.params.imageUrl }} resizeMode="cover" /> : <Image style={styles.userImage} source={{ uri:'https://pbs.twimg.com/profile_images/861972324328890373/89CXofdV_400x400.jpg' }} resizeMode="cover" />}
        </View>
      </TouchableWithoutFeedback>
    )
})
```

**Comment by hundsim** [comment]
This is how I solved it (react-navigation 3.0):

```
static navigationOptions = ({ navigation }) => ({
  title: navigation.state.params.title
});
```

**Comment by faxioman** [comment]
All these hacks are no working anymore with newer react/react navigations versions.
Why having something like "navigation.getParent().props" is so complex?

**Comment by ishake** [comment]
This works for me:

`
  componentDidMount() {
    mapPropsToNavigationRouteParams(this.props, null, props => ({
      myComponentProp: props.myComponentProp,
    }));
  }

  componentDidUpdate(prevProps) {
    mapPropsToNavigationRouteParams(this.props, prevProps, props => ({
      myComponentProp: props.myComponentProp,
    }));
  }

  static navigationOptions = ({navigation}) => {
    const {params} = navigation.state;
    const myComponentProp = params ? params.myComponentProp : null;
    
  }
`

`
export function mapPropsToNavigationRouteParams(
  props,
  prevProps,
  getPropsToMap,
) {
  if (!props) return;
  const propsToMap = getPropsToMap(props);

  if (
    !prevProps ||
    JSON.stringify(getPropsToMap(prevProps)) !== JSON.stringify(propsToMap)
  ) {
    props.navigation.setParams(getPropsToMap(props));
  }
}

`

**Comment by faxioman** [comment]
I solved using the new React Context API... even if you are required to replace the header with your custom header.

**Comment by ishake** [comment]
> I solved using the new React Context API... even if you are required to replace the header with your custom header component.

Would you be willing to share your solution?

**Comment by faxioman** [comment]
Of course

```
static navigationOptions = function(props) {
    return {
      headerTitle: () => <StoreContext.Consumer>{ store => (<Observer>{() => (<HeaderTitle title={store.uiStore.selectedGallery.title} />)}</Observer>)}</StoreContext.Consumer>
    }
}
```

Note that I’m using mobx... but I think the solution is almost the same for many other app state managers.

**Comment by bohehe** [comment]
> if(state.params != undefined){
>             return { 
>                 headerRight: <ShareAppButton shareConfig={{
>                     url: state.params.websiteURL,
>                     subject: "All Recipes Made Easy Android App"
>                 }}/>
>             }
>         }

great, man! this works for me

**Comment by Zakyyy** [comment]
I always get undefined, I want to update the badge Counter based on a prop value
here is what I am doing
componentDidMount(){
    this.props.navigation.setParams({
      x: this.props.numberOfUnreadNotifications
     })
  }
  static navigationOptions = ({navigation}) => ({
    tabBarIcon: ({ tintColor }) => {
      return (
        
        <IconWithBadge name='bell' type='font-awesome' color={tintColor} badgeCount={navigation.state.params.x} size={24} />
      )
    }
  })
