### ISSUE TITLE
StackRouter getActionForPathAndParams doesn't accept params

### ISSUE THREAD

**Issue by alenia** [react-community/react-navigation#1470]
The TabRouter getActionForPathAndParams accepts params, however the StackRouter version of the method doesn't. These APIs should be more consistent.

**Comment by sergiodxa** [comment]
Yeah this is defined here https://github.com/react-community/react-navigation/blob/master/src/routers/StackRouter.js#L320 without receiving params, but documentation said it's going to receive it :(

**Comment by faceyspacey** [comment]
Here's a PR for it: 

https://github.com/react-community/react-navigation/pull/1623

**Comment by Guacaswole** [comment]
The docs indicate that it does though right? 

https://reactnavigation.org/docs/routers/api

If so, why is it not implemented?

**Comment by vonovak** [comment]
#1623 was merged, this should be fixed in master
