### ISSUE TITLE
Accessing navigationOptions from within redux?

### ISSUE THREAD

**Issue by alenia** [react-community/react-navigation#1474]
In our previous routing, we were sending a custom tracking key string through our navigator to determine what to post to our server for event tracking. I feel like this should now live on navigationOptions (given that it depends on the passed in screen) but it's not clear how to then access the navigationOptions object for the current route from within redux. It looks like I can call `MyNavigator.router.screenOptions(someArgs)` but I'm not clear what those args should be. Also should there be a clearer api for accessing these options or is there another suggested way of having custom per-screen configuration?

**Comment by alenia** [comment]
I figured out how to do this but the issue is now that you can't actually add custom keys onto NavigationOptions and then be able to access them

If you get the current route you can call:
`MyNavigator.router.getScreenOptions(currentRoute, screenProps)` and then view the resultant route object

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
