### ISSUE TITLE
Improvement on docs

### ISSUE THREAD

**Issue by prateekvarma** [react-community/react-navigation#1476]
Hello,
First time user here. I am going through the first "Hello World" example.. and i can't figure out what to do after deleting the content of "index.android.js" , and replacing with "import './App';"

As you see in the screenshot below (URL - https://reactnavigation.org/docs/intro/) - Where is the code to be placed? In the index.android.js or in the ./App.js or HomeScreen (as the classname says) .. or in some other file?

![stacknavigator](https://cloud.githubusercontent.com/assets/9058135/25971057/f54b5000-3668-11e7-8f51-0e2c310bb77b.png)

I know this is a basic question, but i really think it's a good idea to make it clear in the docs, as this is confusing for a beginner. If you could just write some basic things, it can save us probably hours of time. (example, in the above example, write which file does the code belong to)
Many thanks.

**Comment by supportclik** [comment]
+1 
Docs is quite confusing for me as well.

**Comment by DiogoAbu** [comment]
Both `index.ios.js` and `index.android.js` will have it's content replaced by just this line `import './App';`
Then a new file is created `App.js`, with the content being the code example.
The HomeScreen will be the first screen in the navigator.

The main point is sharing the code both IOS and Android will load the same file.
