### ISSUE TITLE
Android header is overlapped

### ISSUE THREAD

**Issue by magician11** [react-community/react-navigation#1478]
On iOS I see this

![screen shot 2017-05-11 at 9 26 24 pm](https://cloud.githubusercontent.com/assets/3735849/25981177/d7ea4818-3690-11e7-9c2a-06a295fa9901.png)

On Android I see this..

![screen shot 2017-05-11 at 9 22 33 pm](https://cloud.githubusercontent.com/assets/3735849/25981178/d7ebb9c8-3690-11e7-9c13-742eb028237d.png)

The code uses defaults

```
const AppRoot = StackNavigator({
  Home: {
    screen: HomeScreen,
    navigationOptions: ({ navigation }) => ({
      title: 'Deep Thought'
    })
  },
  GameScreen: { screen: GameScreen },
  AboutScreen: {
    screen: AboutScreen,
    navigationOptions: ({ navigation }) => ({
      title: 'About Deep Thought'
    })
  }
});
```

I'm using   
- "react-navigation": "^1.0.0-beta.9"
- "react-native": "https://github.com/expo/react-native/archive/sdk-16.0.0.tar.gz",

How do I get the Android header to sit underneath and not be overlapped?

Thanks.

**Comment by dioxide** [comment]
+1, How to make a same UI between iOS and Android?

**Comment by rockingskier** [comment]
I wonder if this is an issue with Expo more than it is with react-navigation.  I have the same problem using [create-react-native-app](https://github.com/react-community/create-react-native-app) where the basic "hello world' app sits behind the status bar.  Ejecting the app "fixes" this and pushes the application below the status bar so it seems to me like the Expo app has a problem.

**Comment by magician11** [comment]
Yes @rockingskier , I had a chat with the Expo guys. Looks like we need to explicitly add padding for Android.

```
import { Platform, StatusBar } from 'react-native';
import { StackNavigator } from 'react-navigation';
import HomeScreen from './home';
import GameScreen from './game-screen';
import FAQScreen from './faq';
import ExternalContent from './external-content';

const AppRoot = StackNavigator(
  {
    Home: {
      screen: HomeScreen,
      navigationOptions: ({ navigation }) => ({
        title: 'Deep Thought'
      })
    },
    GameScreen: { screen: GameScreen },
    FAQScreen: {
      screen: FAQScreen,
      navigationOptions: ({ navigation }) => ({
        title: 'FAQs'
      })
    },
    WWW: { screen: ExternalContent }
  },
  {
    cardStyle: {
      paddingTop: Platform.OS === 'ios' ? 0 : StatusBar.currentHeight
    }
  }
);

export default AppRoot;
```

So this works great. I still see a slight shadow that probably needs to be removed in cardStyle too.

In Expo, we could do this too... (code from @brentvatne)

```
<View style={{paddingTop: Platform.OS === ‘ios’ ? 0 : Expo.Constants.statusBarHeight}}>
  <-- your react navigation stack or whatever goes here -->
</View>
```

**Comment by skevy** [comment]
Also related, #12

**Comment by danaszova** [comment]
Thanks for the post. It works like a charm.

**Comment by dodgertodd** [comment]
This is great. Much better than anything I'm seeing in #12

**Comment by Sir-hennihau** [comment]
Error occurred with create-react-native-app for me, too. After using npm run eject the header was fine.

**Comment by philipjmurphy** [comment]
Thanks for the fix - note: IOS needs to be capitalised.

`paddingTop: (Platform.OS === 'IOS' ? 0 : Expo.Constants.statusBarHeight)`

**Comment by brentvatne** [comment]
@philipjmurphy - it's lowercase: https://github.com/facebook/react-native/blob/master/Libraries/Utilities/Platform.ios.js#L16

**Comment by philipjmurphy** [comment]
Deleted that comment - yes, it is lowercase ios - actually, just `paddingTop: Expo.Constants.statusBarHeight` is working for me (Android (real device) and iPhone (simulator))

**Comment by bebe84** [comment]
Why it is still not fixed in Expo to this day? It seems easy.

**Comment by brentvatne** [comment]
@bebe84 - it is. use the latest version of react-navigation

**Comment by atulmy** [comment]
@bebe84 you can try one of these:
```
{
  "expo": {
    "sdkVersion": "25.0.0",
    "androidStatusBar": {
      "backgroundColor": "#000000"
    }
  }
}
```

Or use padding:
`import Expo from 'expo'`
`paddingTop: Expo.Constants.statusBarHeight`

**Comment by r3wt** [comment]
@atulmy i like your solution. here's my version in `native-base`, also note, it may not be necessary to `import Expo from 'expo' at all. In my case it wasn't. for anyone who arrives here from google not necessarily for react-navigation, but rather for this problem in general, just use this on components as you see fit:
```
style={{paddingTop: Expo.Constants.statusBarHeight}}
```
in my case i used it on a `Container`

**Comment by SKempin** [comment]
@magician11 Does this solution still work? I can't get it to function on the latest version of 1.5.8? Thanks

**Comment by itsnuwan** [comment]
Following works in `"react-navigation": "^2.2.3"`
```
import { Platform, StatusBar } from 'react-native';
```


```const RootStack = createMaterialTopTabNavigator(
  {
    Home: HomeScreen,
    Details: DetailsScreen
  },
  {
    initialRouteName: 'Home',
    navigationOptions: ({ navigation }) => ({
      tabBarIcon: ({ focused, tintColor }) => {
        const { routeName } = navigation.state;
        let iconName;
        if (routeName === 'Home') {
          iconName = `ios-home${focused ? '' : '-outline'}`;
        } else if (routeName === 'Details') {
          iconName = `ios-options${focused ? '' : '-outline'}`;
        }

        return <Ionicons name={iconName} size={25} color={tintColor} />;
      },
    }),
    tabBarOptions: {
      activeTintColor: '#fff',
      inactiveTintColor: '#fff',
      showIcon: true,
      showLabel: false,
    },
    style: {
      paddingTop: Platform.OS === 'ios' ? 0 : StatusBar.currentHeight
    }
  }
);``

**Comment by bexuma** [comment]
Place this in render of App.js:
```jsx
import { SafeAreaView } from "react-navigation";

if (Platform.OS === "android") {
  // removes extra space at top of header on android
  SafeAreaView.setStatusBarHeight(0);
}
```

Source: https://stackoverflow.com/a/50093234/6030239

**Comment by WouterFlorijn** [comment]
@brentvatne I was on Expo 31 and upgraded to 34 (bare). Before, padding would automatically be added to avoid overlap with the status bar, but now everything overlaps.

Do you have any idea what changed?

**Comment by Hirbod** [comment]
@itsnuwan I can't thank you enough. After googling 3 hours finally i fixed the overlapping issue that was related to the tabBar

**Comment by bitttttten** [comment]
I hate to necro this thread, but the react navigation API has moved on a lot since then. Is there an up to date solution for this?

I could render a spacer above the whole stack, like this:

```js
import { createNativeStackNavigator } from "@react-navigation/native-stack"

const Stack = createNativeStackNavigator()

return (
  <>
    <View style={{ height: Constants.statusBarHeight, }} />
    <Stack.Navigator initialRouteName="a">
      <Stack.Screen name="a" options={{ headerShow: false }} />
      <Stack.Screen name="b" />
      <Stack.Screen name="c" />
    </Stack.Navigator>
  </>
)
```

This setup allows a fullscreen image on "screen a", but now it means on Android on "screen b" and "screen c" the header goes into the status bar. Ideally, it would be nice to say on these 2 screens add some padding.

Here is what will happen to "screen b" with the above configuration:

![WhatsApp Image 2020-04-10 at 19 16 27](https://user-images.githubusercontent.com/19930241/79009509-e908d080-7b5f-11ea-8050-2286f81a70fd.jpeg)

And this is "screen a" with a really nice fullscreen background image:

![WhatsApp Image 2020-04-10 at 19 18 12](https://user-images.githubusercontent.com/19930241/79009579-13f32480-7b60-11ea-809b-673f5ed56b94.jpeg)
