### ISSUE TITLE
StackNavigator navigation options not working on some page

### ISSUE THREAD

**Issue by stefensuhat** [react-community/react-navigation#1479]
```
StackNavigator(
auth: {
                screen: StackNavigator({
                    index: {screen: AuthScreen},
                    main: {
                        screen: StackNavigator({
                            login: {screen: LoginScreen},
                            register: {screen: NameScreen},
                            forgotPassword: {screen: ForgotPasswordScreen},
                        },
                        )
                    }
                }, {
                    headerMode: 'none'
                })
            }
);
```

LoginScreen.js

```
class LoginScreen extends Component {
    static navigationOptions = ({ navigation, screenProps }) => ({
        title: "Login Page",
        headerRight: <Button color={screenProps.tintColor}><Text>asd</Text></Button>,
    });

   render() {
        return (
             <View />
       )
   }

}
```

On LoginScreen doesnt show any thing at header
![screenshot_1494565681](https://cloud.githubusercontent.com/assets/10653041/25983029/d70319cc-370b-11e7-92d5-43ef35a12966.png)

But if I move my navigation options directly to screen like below it working properly. 

```
screen: StackNavigator({
    login: {screen: LoginScreen,
        navigationOptions:{
            title: "Login Page",
            headerRight: <Button color={screenProps.tintColor}><Text>asd</Text></Button>,
        }
    },

},
```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  "^1.0.0-beta.9
| react-native     |  ^0.44
|  yarn      | 24.2

**Comment by raarts** [comment]
I have a similar problem. navigationOptions are not considered even on the simple documentation example. My problem is described here: https://stackoverflow.com/questions/44219316/stacknavigator-title-not-showing-in-simplest-example

**Comment by lykfe** [comment]
BUMP

**Comment by BarthesSimpson** [comment]
+1

**Comment by kelset** [comment]
Pinging OP @stefensuhat since this issue is quite old and related to an old version of the lib. If no answer I'll close in 7 days.

**Comment by stefensuhat** [comment]
Right now i'm not build any react native app so i won't use this for a moment. you can close it if you want

**Comment by Taakn** [comment]
@kelset still not working with 1.0.0-beta.15

**Comment by kelset** [comment]
@Taakn can you please open a new issue that follows the template?

**Comment by AliYar-Khan** [comment]
> 
> 
> ```
> StackNavigator(
> auth: {
>                 screen: StackNavigator({
>                     index: {screen: AuthScreen},
>                     main: {
>                         screen: StackNavigator({
>                             login: {screen: LoginScreen},
>                             register: {screen: NameScreen},
>                             forgotPassword: {screen: ForgotPasswordScreen},
>                         },
>                         )
>                     }
>                 }, {
>                     headerMode: 'none'
>                 })
>             }
> );
> ```
> 
> LoginScreen.js
> 
> ```
> class LoginScreen extends Component {
>     static navigationOptions = ({ navigation, screenProps }) => ({
>         title: "Login Page",
>         headerRight: <Button color={screenProps.tintColor}><Text>asd</Text></Button>,
>     });
> 
>    render() {
>         return (
>              <View />
>        )
>    }
> 
> }
> ```
> 
> On LoginScreen doesnt show any thing at header
> ![screenshot_1494565681](https://cloud.githubusercontent.com/assets/10653041/25983029/d70319cc-370b-11e7-92d5-43ef35a12966.png)
> 
> But if I move my navigation options directly to screen like below it working properly.
> 
> ```
> screen: StackNavigator({
>     login: {screen: LoginScreen,
>         navigationOptions:{
>             title: "Login Page",
>             headerRight: <Button color={screenProps.tintColor}><Text>asd</Text></Button>,
>         }
>     },
> 
> },
> ```
> 
> ### Your Environment
> software 	version
> react-navigation 	"^1.0.0-beta.9
> react-native 	^0.44
> yarn 	24.2

how you can add OnPress on this ? i am trying to pass the navigation but it is not picking it as follows 
```

navigationOptions: ({navigation}) ({
    title: "Welcome",
    headerRight : ( <TouchableOpacity
           style={{ backgroundColor: '#29434e' , padding: 10}}
           onPress={() => navigation.params.onlogout()}
         >
           <Text style={{ marginVertical:5, color: 'rgba(255,255,255,0.7)', fontSize: 20,}}> Logout </Text>
         </TouchableOpacity>
    ),  
  })
```

**Comment by jandog8990** [comment]
Hello did you ever figure out how to set navigationOptions in Copmonents rather than the screen?

**Comment by bokhary3** [comment]
@jandog8990 You can achieve that by declare `navigationOptions` as static in your component and call it in options parameter in screen like that:

```
class HomeScreen extends React.Component {
  static navigationOptions = {
    // ...
  };
}

// ...

<Stack.Screen
  name="Home"
  component={HomeScreen}
  options={HomeScreen.navigationOptions}
/>;
```

You can learn more about `navigationOptions` status from here https://reactnavigation.org/docs/upgrading-from-4.x/#specifying-navigationoptions-for-a-screen
