### ISSUE TITLE
If screen is hidden on TabNavigation, styles are not applied to header

### ISSUE THREAD

**Issue by rafaelcorreiapoli** [react-community/react-navigation#148]
My use case:
I need to update my header color according to my redux store

1. This is my TabNavigator
```js
export default TabNavigator({
  Feed: {
    screen: FeedStack,
    navigationOptions: {
      tabBar: {
        label: 'Feed',
      },
    }
  },
  Activities: {
    screen: ActivitiesStack,
    navigationOptions: {
      tabBar: {
        label: 'Atividades',
      },
    }
  },
```

2. This is my FeedStack
```js
const FeedStack = StackNavigator({
  Feed: {
    screen: FeedScreen,
    path: '/',
    navigationOptions: {
      title: 'Feed',
      header: ({ state }) => {
        const primaryColor = state.params && state.params.primaryColor
        const navbarFontColor = state.params && state.params.navbarFontColor

        return {
          tintColor: navbarFontColor,
          style: {
            backgroundColor: primaryColor || '#FFF',
          }
        }
      }
    }
  }
})
```
**My ActivitiesStack is exactly the same**

3. On my FeedScreen, I listen for changes on the store and use setParams
```js
@connect(state => ({
    primaryColor: state.colors.get('primaryColor'),
    navbarFontColor: state.colors.get('navbarFontColor')
  }))
class FeedScreen extends Component {
  constructor(props) {
    super(props)
    this.state = {}
  }

componentWillReceiveProps(nextProps) {
      const primaryColor = nextProps.primaryColor
      const navbarFontColor = nextProps.navbarFontColor

      const oldPrimaryColor = this.props.navigation.state && this.props.navigation.state.params && this.props.navigation.state.params.primaryColor
      const oldNavbarFontColor = this.props.navigation.state && this.props.navigation.state.params && this.props.navigation.state.params.navbarFontColor

      const newParams = {}
      if (primaryColor && oldPrimaryColor !== primaryColor) {
        newParams.primaryColor = primaryColor
      }

      if (navbarFontColor && navbarFontColor !== oldNavbarFontColor) {
        newParams.navbarFontColor = navbarFontColor
      }

      if (Object.keys(newParams).length > 0) {
        console.log('dispatching', newParams)
        this.props.navigation.setParams(newParams)
      }
    }

  render() {
    return (
      <ScreenContainer>
        <Feed />
      </ScreenContainer>
    )
  }
}
```
**My ActivitiesScreen is exactly the same**

Everything works fine for the FeedScreen (which is the first tab) but it does not work on the other screen (which is initially hidden because it is the second tab)

The state.params is never set on the function passed to *header* on my second screen (Activities)

*This is obviously a naive implementation, I'd use HOCs to achieve the same functionally, but I simplified this just for debugging purposes*

**Comment by jankcat** [comment]
I am seeing this same behavior on beta 6, navigating to a tab that is not the initial tab. 

Here are some behaviours I am seeing:
- With lazyLoad set to false, the non-initial tabs fire the SET_PARAMS on app launch, but those params are not maintained when switching to the non-initial tabs.
- With lazyLoad set to true, the non-initial tabs fire the SET_PARAMS when their respective tab is tapped/navigated to. However, it seems there may be a race condition as sometimes the NAVIGATE happens first and the SET_PARAMS second and things work fine, but sometimes the SET_PARAMS happens first and the NAVIGATE second, and the params are not maintained.

<img width="1439" alt="screen shot 2017-03-09 at 4 25 18 pm" src="https://cloud.githubusercontent.com/assets/7744158/23775263/0a17557a-04e5-11e7-949f-b0de46b425fd.png">

**Comment by kelset** [comment]
Pinging OP @rafaelcorreiapoli since this issue is quite old. If no answer I'll close in 7 days.

**Comment by kelset** [comment]
Hi there @rafaelcorreiapoli,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue (especially if it's a bug report) please open a new issue that uses the new Issue Template to provide some more details to help us solve it.
