### ISSUE TITLE
How to verify the type of parameter passed

### ISSUE THREAD

**Issue by lucasleelz** [react-community/react-navigation#1480]
### Current Behavior
```
 this.props.navigation.navigate('About', {user: 'lucas'});
```
How to verify this parameter in `About` is a string type

### Expected Behavior

```
class AboutScreen extends Component {
    static propTypes = {
        user: PropTypes.string.isRequired,
   }
}
```
I would like to be able to verify the parameters as above. 
what should I do?

### Your Environment
| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.9
| react-native     |  0.44.0
| node             | 7.5.0
| npm       | 4.1.2

**Comment by dioxide** [comment]
same promblem ! the Props is so deep

**Comment by Andreyco** [comment]
Won't this help?

```js
class AboutScreen extends Component {
    static propTypes = {
        navigation: PropTypes.shape({
            state: PropTypes.shape({
                params: PropTypes.shape({
                    user: PropTypes.string.isRequired,
                })
            })
        })
   }
}
```

Also, you can create custom prop validation function, which will save you from deeply defining navigation prop.

```js
customProp: function(props, propName, componentName) {
    // do validation here
},
```

Another alternative is to use Flow
```js
import type { NavigationScreenProp } from 'react-navigation/lib/TypeDefinition'

type NavState = {
    params: {
        user: string,
    }
}

type Props = NavigationScreenProp<NavState, *>

export default class AboutScreen extends Component<*, Props, *> {
    render() {
        // ...
    }
}
```

**Comment by lucasleelz** [comment]
@Andreyco Thank you!
But, I still feel that the previous way is very good, do not like this.The level is too deep is very bad
```
class AboutScreen extends Component {
    static propTypes = {
        user: PropTypes.string.isRequired,
   }
}
```
