### ISSUE TITLE
goBack({key:key}) not working

### ISSUE THREAD

**Issue by DevilMayCry4** [react-community/react-navigation#1481]
### Current Behavior
I have a page with key 'Init' in stack and I want pop to this page with goBack({key:'Init'}),
But nothing happen.
I check code in src/routers/StackRouter.js,
 `if (action.type === NavigationActions.BACK) {
        let backRouteIndex = null;
        if (action.key) {
          const backRoute = state.routes.find(
            /* $FlowFixMe */
            (route: *) => route.key === action.key,
          );
          /* $FlowFixMe */
          backRouteIndex = state.routes.indexOf(backRoute);
        }`
The first route's key should equal to action'key. but return false.

<img width="236" alt="2017-05-12 3 31 15" src="https://cloud.githubusercontent.com/assets/2283757/25988182/a18c2400-3729-11e7-837a-6a02c26eb6ba.png">

<img width="321" alt="2017-05-12 3 32 01" src="https://cloud.githubusercontent.com/assets/2283757/25988181/a18b61be-3729-11e7-8ba3-2593ef35dcc1.png">

<img width="826" alt="2017-05-12 3 32 52" src="https://cloud.githubusercontent.com/assets/2283757/25988180/a18ab7b4-3729-11e7-8437-4c9542469f43.png">

 

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.9
| react-native     |  0.44.0
| node             | v6.9.1
| npm       |3.10.8

**Comment by baldurpan** [comment]
Having this issue myself. Did you resolve it?

**Comment by dongodngtang** [comment]
Having this issue myself. Did you resolve it?

**Comment by npomfret** [comment]
The goBack docs are meaningless.  What does this mean??

> key - string or null - optional - If set, navigation will go back from the given key. If null, navigation will go back anywhere.

**Comment by baldurpan** [comment]
Hmm.. I didn't notice that is says "will go back FROM the given key".
I was under the impression that it would go back TO the given key.

**Comment by ryancoughlin** [comment]
I have noticed this as well. Tried passing, some other key to a screen, null and nothing. Can't seem to get a screen to dismiss programatically.

**Comment by DevilMayCry4** [comment]
If A,B,C in stack,and you want goback to A,you should pass the key of B screen.Like goBack('keyofB'). It seem very strange to me,but it works.

**Comment by Obooman** [comment]
#905 This pr is related to the strange usage,maybe the library need some extra info to make the animation so they need the page route name which you `back from`.

**Comment by dann1609** [comment]
None work for me!!

**Comment by lsorin81** [comment]
@dann1609 you're probably providing the wrong key.. in a stack with multiple screens, the key of the screen is different from the routeName... just log the entire this.props.nav object.. you might find the key looks something like:

key:id-1510829501204-2
routeName:Splash

- if you provide that key, the goBack will work!

**Comment by dann1609** [comment]
thanks @lsorin81  I found this solutions weeks ago but I do not post here. Thanks for post!

**Comment by facuescobar** [comment]
@lsorin81  thanks for that! Right before reading this issue, I was thinking if I needed to use `key` instead of the actual `routeName` I use to navigate to new screens.

Is there any reason why react-navigation generates a random keys for some routes? 
The way is done, we have to pass the route key thru navigation params
