### ISSUE TITLE
Not able to navigate from within redux action creators.

### ISSUE THREAD

**Issue by Moebats** [react-community/react-navigation#1482]
Hello, I am one of those people who has just switched from using react-router-flux.  We use redux for our app. Everything seems to be going smoothly with the react-navigation implementation except I am not able to use navigation outside the screens.

The home screen includes a sign up button which when pressed loads a redux action creator which dispatches an action.  In our actions file I have imported `import { NavigationActions } from 'react-navigation';` at the top and then tried to navigate the user to the sign up screen with an action dispatch: 

      export const signupClicked = () => {
       return (dispatch) => {
        dispatch({ type: SIGNUP_CLICKED });
        dispatch(NavigationActions.navigate({ routeName: 'SignupForm' }));
      };
    };

This does not seem to be working.  While using react-router-flux instead of `    dispatch(NavigationActions.navigate({ routeName: 'SignupForm' }));` I would have had something like `Actions.Signup();` and that would navigate to the sign up page.  Any help would be appreciated.

Thanks

**Comment by yiluzhang** [comment]
StackNavigator props navigation={addNavigationHelpers({redux.dispatch, redux.state})}

**Comment by Moebats** [comment]
Thanks for the reply, I am really new to react-native, so can you tell me where I would put the code you provided above?  How should I utilize it exactly?

**Comment by jasan-s** [comment]
@yiluzhang  can you elaborate on your answer.

**Comment by roderickfung** [comment]
@yiluzhang can you please elaborate?

**Comment by yiluzhang** [comment]
[https://reactnavigation.org/docs/guides/redux](url)

Using Redux to manage `navigation`.
Your `AppNavigator` needs `navigation` props.
`AppNavigator` props is created by the `addNavigationHelpers` method.
In Redux, routing is changed through the `AppNavigator` method of `router.getStateForAction`.
```javascript
if (action.type === 'Navigation/NAVIGATE') {
    switch (action.routeName) {
        case 'TAB_NAVIGATOR_MYSELF':
        case 'STACK_NAVIGATOR_USER_XXX':
        case 'STACK_NAVIGATOR_USER_XXXX':
            if (state.notlogin) { action.routeName = 'STACK_NAVIGATOR_LOGIN'; }
            break;
      }
}
nav = AppNavigator.router.getStateForAction(action, state.nav);
```

```javascript
<AppNavigator navigation={addNavigationHelpers({redux.dispatch, redux.state})}/>
```
Can I help you with my answer? @jasan-s @roderickfung

**Comment by kidequinox** [comment]
@yiluzhang Do you have to use Redux to manage navigation, in order for components/screens to use redux ?

**Comment by kelset** [comment]
Pinging OP @Moebats since this issue is quite old and related to an old version of the lib. If no answer I'll close in 7 days.

**Comment by kelset** [comment]
Hi there @Moebats ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.
