### ISSUE TITLE
Common Component for the whole DrawerNavigator

### ISSUE THREAD

**Issue by Fonze** [react-community/react-navigation#1487]
I'm rather new to React Native and I bumped into a rather big of a problem right away. I have a DrawerNavigator nested into a StackNavigator and I'd like to all the screens in DrawerNavigator to have a common header (which is the easy part, just give the DrawerNavigator default navigationOptions where you have the header options you want) AND I'd like to have a little icon on the right side of the header which's color you can change on one of the DrawerNavigator's screens and the color will stay the same on all the screens until you navigate back to one screen where you can control the state of the icon again and change it.

So my logic would say that I should have the icon's state stored to the DrawerNavigator itself and it should also have the functions to control the state and change the color according to the state and pass the control function to the screen which should control the icon's state, but Navigators don't seem to be able to have this kind of state and include such functions that would set the state of the icon re-render the component accordingly.

So am I fortunately wrong and there is a way to make my logic work or do I just have to give each screen same looking header in navigationOptions and just pass the state of the icon around?

**Comment by smitthakkar1** [comment]
Facing the same issue

**Comment by spencercarli** [comment]
I'm not fully understanding what you're trying to do but check out [this article](https://shift.infinite.red/react-navigation-drawer-tutorial-a802fc3ee6dc) for some possible guidance.

For future reference - usage questions are best suited for StackOverflow. Thanks!
