### ISSUE TITLE
Provide an example of using a custon transitionConfig in StackNavigator

### ISSUE THREAD

**Issue by mannol** [react-community/react-navigation#1490]
Currently, docs say the following:
    `transitionConfig` - Function to return an object that overrides default screen transitions

However, no example is provided what that function should look like.

**Comment by HoangTrung** [comment]
Yes, that is what I'm looking for too. Please give us and example. Thanks.

**Comment by koenpunt** [comment]
There's this comment from the author of `transitionConfig`: https://github.com/react-community/react-navigation/pull/1187#issuecomment-300112470

But that probably should documented somewhere.

**Comment by aqnaruto** [comment]
could i add gesture on this ?

**Comment by nihgwu** [comment]
@aqnaruto Stop ruining the `Issues` you idiot, read the damn docs and source code https://reactnavigation.org/docs/navigators/stack#gesturesEnabled

**Comment by aqnaruto** [comment]
thank you ,but it do not work,have you test it on android?@nighwu

**Comment by nihgwu** [comment]
@aqnaruto Seems I have to take a screenshot before I reply you comments, ridiculous! Shame on you again 
https://github.com/nihgwu/react-native-dva-starter/blob/master/app/router.js#L49-L51

**Comment by aqnaruto** [comment]
yes it is written in document and written in source code, but it do not work , you should test it on you android simulator @nihgwu

**Comment by aqnaruto** [comment]
@nihgwu 哥，你安卓跑出来个给我看看，talking is cheap，我给你两个小时，你跑出来了我删除所有评论并道歉。

**Comment by nihgwu** [comment]
![image](https://cloud.githubusercontent.com/assets/2595058/26033860/03757726-38e6-11e7-8141-940417563ee8.png)
for backup 😄

**Comment by aqnaruto** [comment]
ok，你备份，对得起你的签名，talking is cheap ，你跑出来啊。@nighwu

**Comment by koenpunt** [comment]
No need for shaming eachother. @aqnaruto  `gesturesEnabled` works just fine. You can easily test that with the example app in the repo

**Comment by aqnaruto** [comment]
thank you, you are so generous, but i set this 
![image](https://cloud.githubusercontent.com/assets/9067159/26033921/19398f38-38e7-11e7-9aae-f6ed6326090d.png)
still not work

**Comment by koenpunt** [comment]
`gesturesEnabled` should be in the `navigationOptions` object. 

```
navigationOptions: { gesturesEnabled: true }
```

**Comment by koenpunt** [comment]
But this is getting off-topic

**Comment by nihgwu** [comment]
@aqnaruto 
https://github.com/nihgwu/react-native-dva-starter/blob/master/app/router.js#L49-L51
```
    navigationOptions: {
      gesturesEnabled: false,
    },
```
I pasted three lines incase you missed that, you idiot

**Comment by nihgwu** [comment]
![image](https://cloud.githubusercontent.com/assets/2595058/26033957/810ec790-38e7-11e7-8b1e-9db24fbd9091.png)
backup 😄

**Comment by nihgwu** [comment]
@koenpunt I'll send a PR to address this issue, I didn't do it before because I thought it's an advance use case, if you want to master it, the best way is to read the source code, I used 4 different transition animations in my app

**Comment by aqnaruto** [comment]
ok, it is really work, thank you  @nihgwu @koenpunt

**Comment by mannol** [comment]
I reported an issue and received gratis LOL's. I love open source!

**Comment by nihgwu** [comment]
Sorry for the arguing thread, this is not the first time I saw this guy abuse the others, this time he asked in many irrelevant issues for the same question in the same time

**Comment by nihgwu** [comment]
@aqnaruto I'm still waiting for you apologies

**Comment by aqnaruto** [comment]
thank you @nihgwu @koenpunt, and i apologise for my beheavior ,i should read the document carefully and i waste you and other's energy and time . thank you all figure my problem out .  i will delete my question about this .

**Comment by nihgwu** [comment]
@aqnaruto You should also apologize for abusing the others and promise you won't do this again

**Comment by aqnaruto** [comment]
i did not  abused any one

**Comment by nihgwu** [comment]
So you want me to show you the proof? Can you tell me what kind of question is noob? And yours? Have you forget that this is not the first time I backup the screenshots of you comments? 
Well, it's unworthy to play game with you, and I won't take you apologies, that's all

**Comment by aqnaruto** [comment]
noob questions waste peple 's energy and time , i apologize fot this , i will be more carefully before i ask some one noob question,  i do'nt care what your take or not take, i do it because i think i should do it

**Comment by lprhodes** [comment]
Treat people with respect guys...this is the worst issue I've seen in a long time.

**Comment by timrc** [comment]
There were a couple of question regarding this so I decided to write a little step-by-step how to on custom transitions.

### Create a Scene or Two to navigate

    class SceneOne extends Component {
        render() {
            return (
                <View>
                    <Text>{'Scene One'}</Text>
                </View>
            )
        }
    }
    class SceneTwo extends Component {
        render() {
            return (
                <View>
                    <Text>{'Scene Two'}</Text>
                </View>
            )
        }
    }

### Declare your app scenes

    let AppScenes = {
        SceneOne: {
            screen: SceneOne
        },
        SceneTwo: {
            screen: SceneTwo
        },
    }

### Declare custom transition

    let MyTransition = (index, position) => {
        const inputRange = [index - 1, index, index + 1];
        const opacity = position.interpolate({
            inputRange,
            outputRange: [.8, 1, 1],
        });

        const scaleY = position.interpolate({
            inputRange,
            outputRange: ([0.8, 1, 1]),
        });

        return {
            opacity,
            transform: [
                {scaleY}
            ]
        };
    };

### Declare custom transitions configurator

    let TransitionConfiguration = () => {
        return {
            // Define scene interpolation, eq. custom transition
            screenInterpolator: (sceneProps) => {

                const {position, scene} = sceneProps;
                const {index} = scene;

                return MyTransition(index, position);
            }
        }
    };

### Create app navigator using Stack Navigator

    const AppNavigator = StackNavigator(AppScenes, {
        transitionConfig: TransitionConfiguration
    });

### Use App Navigator in your project

    class App extends Component {
        return (
            <View>
                <AppNavigator />
            </View>
        )
    }

### Register your app in eq. `index.ios.js`

    import { AppRegistry } from 'react-native';
    AppRegistry.registerComponent('MyApp', () => App);


# Example 1

### As for the question on how to set transition per scene, this is how I'm doing it.

When you navigate using `NavigationActions` from `react-navigation`, you can pass through some props. In my case it looks like this

    this.props.navigate({
        routeName: 'SceneTwo',
        params: {
            transition: 'myCustomTransition'
        }
    })

and then inside the Configurator you can switch between these transition like this


    let TransitionConfiguration = () => {
        return {
            // Define scene interpolation, eq. custom transition
            screenInterpolator: (sceneProps) => {

                const {position, scene} = sceneProps;
                const {index, route} = scene
                const params = route.params || {}; // <- That's new
                const transition = params.transition || 'default'; // <- That's new

                return {
                    myCustomTransition: MyCustomTransition(index, position),
                    default: MyTransition(index, position),
                }[transition];
            }
        }
    };


I hope this will help some of you guys get your head around it.

**Comment by lprhodes** [comment]
Thanks @timrc that'll be really helpful. Before I get started I just want to make sure; there's no existing drop-in fade transition at the moment, right?

**Comment by mannol** [comment]
Thanks @timrc. Much appreciated!

**Comment by shrutic123** [comment]
@timrc Thanks for sharing this. Do you have an example where I can use these custom transitions inside a Custom navigator created using the createNavigationContainer(
    createNavigator(AppStackRouter)(StackView)
);

This is based off of CustomTabs example in react-navigation examples. Here I am confused as to how do I pass my transitionConfig inside createNavigator

**Comment by lprhodes** [comment]
Thanks again @timrc 

The following is the config I'm using for switching between cross-fades and modals on iOS:

```
import { Animated, Easing, Platform } from 'react-native'
import CardStackStyleInterpolator from 'react-navigation/src/views/CardStackStyleInterpolator'

let CrossFadeTransition = (index, position) => {
    const inputRange = [index - 1, index, index + 1]
    const opacity = position.interpolate({
      inputRange,
      outputRange: [0, 1, 1],
    })

    return {
      opacity
    }
};

const IOSTransitionSpec = ({
  duration: 500,
  easing: Easing.bezier(0.2833, 0.99, 0.31833, 0.99),
  timing: Animated.timing,
}: NavigationTransitionSpec);

export default TransitionConfiguration = () => {
  return {
    transitionSpec: IOSTransitionSpec,
    screenInterpolator: (sceneProps) => {

      const { position, scene } = sceneProps;
      const { index, route } = scene
      const params = route.params || {}
      const transition = params.transition || 'default'

      const final = {
        crossFade: CrossFadeTransition(index, position),
        default: CardStackStyleInterpolator.forVertical(screenProps),
      }[transition]

      return final
    }
  }
}
```

**Comment by customht** [comment]
@timrc Have you any idea how to change this from a cross fade to a fade in?

**Comment by skevy** [comment]
I just came across this thread, and I'm going to lock it given the craziness that happened earlier in the thread. We don't need that type of behavior on this project.

Please, please, please -- let's keep the issues sane in this repo. There doesn't need to be insults or other rude behavior; it's simply not productive.

I'm going to try to put a code of conduct in this repo ASAP, and I will lock threads/block individuals when I see bad behavior.

For those of you on this thread who wanted information about a custom transition, @timrc gave a very good explanation of how this is currently done, and we'll hopefully make it easier in the future.
