### ISSUE TITLE
disable drawer gesture

### ISSUE THREAD

**Issue by mynameisbams** [react-community/react-navigation#1495]
how to disable open drawer gesture? is anyone can help me?

**Comment by aqnaruto** [comment]
i do'nt know ,but do you know how to enable staticnavigation gesture?

**Comment by dabit1** [comment]
I also need it and I can't find it

**Comment by wrightmk** [comment]
has anyone solved this issue?

**Comment by rochapablo** [comment]
+1

**Comment by iRoachie** [comment]
Right now conflicting with slide to go back on iOS

**Comment by zarcode** [comment]
+1

**Comment by beeant** [comment]
+1

**Comment by huanganqi** [comment]
how to disable open drawer gesture? is anyone can help me?

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
