### ISSUE TITLE
How to block app exit when i press android hardware back button on top level of navigation

### ISSUE THREAD

**Issue by zhenliliu** [react-community/react-navigation#1497]
TabNavigationIndex.router.getStateForAction = (action, state) => {

    if(state && state.index == 0 && action.type == 'Navigation/BACK'){
       
    }
    return defaultGetStateForAction(action, state);
};

in this function how to  block app exit

**Comment by Moumene** [comment]
Generally returning `true` while prevent the app exit.

**Comment by zhenliliu** [comment]
but when i return true it remind me such as this 'Cannot read property 'forEach' of undefine'

**Comment by nihgwu** [comment]
`return state;`

**Comment by zhenliliu** [comment]
yes i have solved this problem by  '
return {
        ...state,
        index: state.routes.length - 1,
   };'
