### ISSUE TITLE
Question - How to render default header if it is disabled in root navigatior?

### ISSUE THREAD

**Issue by maxkomarychev** [react-community/react-navigation#1499]
I want to have the default header to be rendered on particular screens while be disable for most of the other screens in the app. Previously it was achieved with `header.visibe: true | false` which is not possible now. It is now offering me to provide a function to render header. How do I override global setting and render default header in particular screen?

I have a root navigator config that looks like this (passed as argument to `StackNavigator`):

```js
{
    navigationOptions: {
        header: null,
        gesturesEnabled: false,
    },
}
```

How do I enable default header back in particular screen?

Thank you.

**Comment by maxkomarychev** [comment]
okay I figured it out (feels weird though) - you should pass `header: undefined` in `navigationOptions` of the particular screen.

**Comment by duhseekoh** [comment]
This did not work for me.
