### ISSUE TITLE
it seems that your official website forgets to remove the logger

### ISSUE THREAD

**Issue by lxfriday** [react-community/react-navigation#1501]
main.3e985a8f.js:6 Navigation Dispatch: 
main.3e985a8f.js:6 Dispatched action did not change state:  Object
main.3e985a8f.js:6 Navigation Dispatch: 
main.3e985a8f.js:6 Action:  Object
main.3e985a8f.js:6 New State:  Object
main.3e985a8f.js:6 Last State:  Object

[https://reactnavigation.org/docs/navigators/navigation-options](https://reactnavigation.org/docs/navigators/navigation-options)

**Comment by nihgwu** [comment]
Have you read the release note of beta.9?

**Comment by lxfriday** [comment]
Ok I get it.Thanks for the great work.I like the navigation transition very much!
