### ISSUE TITLE
Overlapping titles in Header

### ISSUE THREAD

**Issue by edo1493** [react-community/react-navigation#1503]
Hello, 

so I have a main view A and a sub-view B. I am passing the title of B from A through: 

`this.props.navigation.navigate('Expenses', {title:data});
`
data varies according to what title I need when I am pushing from A. 

If I push B from A with a title X, then go back and push again B from A with title Y, I see title Y on top of title X for a few seconds, then X disappears and Y stays where it is supposed to be. 

I don't think this is an expected behaviour and I am not even sure where or how X can stay still there. I have tried to reset navigation.state.params.title to an empty string when I unmount B, but I still get the same effect. 

I am on: 
"react-navigation": "^1.0.0-beta.9",
"react-native": "^0.42.0",

**Comment by aroth** [comment]
Duplicate of https://github.com/react-community/react-navigation/issues/836

**Comment by edo1493** [comment]
I am closing then.
