### ISSUE TITLE
Nesting tab does not work, especially on Android

### ISSUE THREAD

**Issue by imWildCat** [react-community/react-navigation#1506]
### Current Behavior
```javascript
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 * @flow
 */

import {
    AppRegistry,
    Button,
    Image,
    StyleSheet,
    Text,
    View,
} from 'react-native';
import React, { Component } from 'react';
import {
    StackNavigator,
    TabNavigator,
} from 'react-navigation';

// Children
class ChildFooScreen extends Component {
    static navigationOptions = {
        tabBarLabel: 'Foo',
    };
    render() {
        return <View style={{ backgroundColor: 'red', marginTop: 200 }}><Text>Foo</Text></View>;
    }
}

class ChildBarScreen extends Component {
    static navigationOptions = {
        tabBarLabel: 'Bar',
    };
    render() {
        return <View><Text>Bar</Text></View>
    }
}

const ChildTabNav = TabNavigator({
    Foo: {
        screen: ChildFooScreen
    },
    Bar: {
        screen: ChildBarScreen
    }
});


class RecentChatsScreen extends React.Component {
  render() {
    return <View>
        <Text>List of recent chats</Text>
        <ChildTabNav />
    </View>
  }
}

class AllContactsScreen extends React.Component {
  render() {
    return <Text>List of all1 contacts</Text>
  }
}

const MainScreenNavigator = TabNavigator({
  Recent: { screen:  ChildTabNav}, // if it is RecentChatsScreen, it does not work
  All: { screen: AllContactsScreen },
});


export default class AwesomeProject extends Component {
    render() {
        return (

            <MainScreenNavigator />

        );
    }
}


AppRegistry.registerComponent('AwesomeProject', () => AwesomeProject);

```

### Expected Behavior

I'd like to display my 'child tab' in `RecentChatsScreen`, instead of `ChildTabNav` directly. How could I implement it

| software         | version
| ---------------- | -------
| react-navigation |   ^1.0.0-beta.9
| react-native     |   0.44.0
| node             | v7.9.0
| npm or yarn      | 0.23.2 (yarn)

**Comment by andfs** [comment]
I think you can't call <ChildTabNav /> inside a component like you did in RecentChatsScreen, but only in a navigation function like in MainScreenNavigator.

**Comment by 393197906** [comment]
I encountered the same problem, the tab nesting does not work properly

**Comment by yernandus** [comment]
having same issue

**Comment by jsappme** [comment]
same issue here

**Comment by kelset** [comment]
I don't understand why `RecentChatsScreen ` shouldn't work, not what you mean with "RecentChatsScreen doesn't work".

Please @imWildCat  provide the error log for it because I can't think of a reason of it not working. If no answer I'll close this in 7 days since it's really old.

**Comment by kelset** [comment]
Hi there @imWildCat ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.
