### ISSUE TITLE
enforce ios or android tab navigator style regardless of platform

### ISSUE THREAD

**Issue by garan82** [react-community/react-navigation#1507]
I want to have ios tab navigator as the root navigator. In each ios tab, I would have android tab navigator. However it seems that the platform will dictate how tab navigator looks like. Can I enforce a tab navigator to be ios or android style?

**Comment by rmevans9** [comment]
You can use the Tab Bar options to enforce specific setups for tabs. https://reactnavigation.org/docs/navigators/tab#TabNavigatorConfig

You would need to set at minimum the following settings (I believe):

1. `tabBarComponent`
2. `tabBarPosition`
3. `showLabel` (on `tabBarOptions`)
4. `showIcon` (on `tabBarOptions`)

**Comment by windhost** [comment]
Use TabNavigatorConfig someHow like this `   {
        //tabBarComponent: 'TabBarBottom',
        tabBarPosition: 'bottom',
        animationEnabled: false,
        swipeEnabled: false,

        tabBarOptions: {
            // showLabel:true,
            showIcon: true,
            activeTintColor: 'blue',
            inactiveTintColor:'#999999',
            style: {
                backgroundColor: '#ffffff',
            },
            indicatorStyle: {
                backgroundColor: 'white'
            }
        }
    }`

**Comment by Selman555** [comment]
I do the following:

```
const tabs = TabNavigator({
    // Defining tabs as usual
}, {
    ...TabNavigator.Presets.AndroidTopTabs, // or iOSBottomTabs
    tabBarPosition: "bottom",
    // Defining options as usual
});
```

I specify all properties from the default presets, this overrides the platform specific tabbar behavior on all platforms. Perhaps this is an easy way to get what you need?
