### ISSUE TITLE
landscape navbar height is not correct

### ISSUE THREAD

**Issue by pvinis** [react-community/react-navigation#1519]
### Current Behavior
when the phone is landscape, the header height is the full height.
on ios, during landscape, the header height is smaller. (32 pixels)

### Expected Behavior
to be 32 pixels.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0 beta 9
| react-native     |  0.44.0

**Comment by vincejah** [comment]
@pvinis is there any update on this issue? I am surprised to see that this ticket did not get more activity.

Have you find ways to set height correctly?

**Comment by SteffeyDev** [comment]
Just noticed this and seems like a huge oversight, I would really appreciate if someone could pick this up

**Comment by pvinis** [comment]
the change needs to happen here https://github.com/react-community/react-navigation/blob/f84fe152721f0f6f80f799dbcd9bcbf5f42d61d0/src/views/Header/Header.js#L37-L39

i dont want to contribute to this repo, as i see its partly inactive, partly terribly managed, so my PR will just get forgotten into oblivion.

currently i just did the change myself, i have a fork, and i also changed things in the `headerTitleStyle` in the `StackNavigator` initialization on my app.

**Comment by kelset** [comment]
> i dont want to contribute to this repo, as i see its partly inactive, partly terribly managed, so my PR will just get forgotten into oblivion.

First off, I really have no idea of why you are so toxic. We are actively working to make this lib better and comments like yours are simply not helpful. **At all**.

Moreover there are PRs in the pipeline to be merged ( like #2814, #2833 etc ) related to this issue. 

So, please, take that shitty attitude somewhere else. You are not a welcome member of the open source community.

**Comment by vonovak** [comment]
closing since we're handling this in https://github.com/react-community/react-navigation/issues/2795 and in related PRs

**Comment by vonovak** [comment]
@pvinis I understand that you're unhappy about the pace of development, but things are getting better, which can also be seen by the number of PRs we have been merging recently. Personally I'll spend some time reviewing some older PRs this week. My goal is for the community to see that things are moving in the repo and that shipping a PR to the repo is not a waste of time.

**Comment by pvinis** [comment]
i would be very happy to see that. thanks. i already tried to send a couple of pr and fixes, in hopes that they will be picked up.

**Comment by aaronleo28** [comment]
@kelset hey mate was wondering if there are any updates on this issue? Seems to still be present in v1.5.11
