### ISSUE TITLE
goBack() doesn't work

### ISSUE THREAD

**Issue by maxdobler** [react-community/react-navigation#1522]
Hi, 

I use React Navigation with Redux in React Native.
Navigation is working fine, but on one screen the goBack() function doesn't work. Can you tell we why?

This is the header config:

```
static navigationOptions = {
        header: ({ state, goBack }) => {
            return {
                title: state.params.name,
                right: (<Button
                    title={'Done'}
                    onPress={() => goBack()}
                />)

            }
        }
    }
```

This is the dispatched event:

‹Start group›:  action Navigation/BACK @ 16:16:49.078 (in 0.00 ms)

nav:Object {index: 2, routes: Array[3]}

action    
Object {type: "Navigation/BACK", key: Proxy}
key:Proxy {dispatchConfig: null, _targetInst: null, isDefaultPrevented: null, …}
type:"Navigation/BACK"
__proto__:Object {}

next state
nav:Object {index: 2, routes: Array[3]}

No Screen is poped off. The Screen on the device stays the same.

### Your Environment
Windows, Android

| software         | version
| ---------------- | -------
| react-navigation |  git+https://github.com/react-community/react-navigation.git#7edd9a7
| react-native     |  0.43.3
| node             | 4
| npm or yarn      |

**Comment by ryancoughlin** [comment]
Funny timing, I noticed the same thing this past weekend. Same versions, but running on iOS and on Mac.

**Comment by maxdobler** [comment]
I tried the most recent version, but the same issue ...

**Comment by AZZB** [comment]
The same

**Comment by diego3g** [comment]
same here

**Comment by dsibiski** [comment]
As a temporary fix, you can do something like this (v1.0.0 beta 11):

```javascript
navigationOptions: ({ navigation }) => ({
    headerLeft: (
        <Button title='Done' onPress={() => setTimeout(navigation.goBack, 0)} />
    ),
});
```

Something must be happening in the JS stack that needs to be cleared out before `goBack` works normally...

**Comment by vitalyrotari** [comment]
@dsibiski Not for me :/ any status?

**Comment by wootwoot1234** [comment]
Same here.

**Comment by jolocity** [comment]
+1

**Comment by spencercarli** [comment]
Could someone put together a demo of this on [Snack](https://snack.expo.io)? Would help debug this.

I _think_ I've seen something similar when trying to pop from a nested navigator to a parent navigator. In which case calling `goBack(null)` worked for me. Could you give that a shot and see if it works for you?

**Comment by rayronvictor** [comment]
`goBack(null)` works for me with nested navigator, but `goBack()` only work for root navigator direct children (switch between them).

**Comment by kelset** [comment]
Pinging OP @maxdobler since this issue is quite old and related to an old version of the lib. If no answer I'll close in 7 days.

**Comment by kelset** [comment]
Hi there @maxdobler ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.

**Comment by ethanyuwang** [comment]
Having the same issue on the latest version ("react-navigation": "^1.0.2"), calling `goBack(null)` worked for me

**Comment by peteroid** [comment]
Just experienced this issue when I have the setup like below.
```
React Native Navigation
|--screen A
|     |-- React Navigation: StackNavigator
|
|--screen B
|     |-- React Navigation: StackNavigator
```

The workaround mentioned in https://github.com/react-navigation/react-navigation/issues/1522#issuecomment-325965213 worked.

**Comment by yohanes-ai** [comment]
I have 2 screen here. First LoginScreen and LoginFormScreen. LoginScreen have two button, LoginButton : Navigate to LoginFormScreen. So here my AppNavigator.js

```
import LoginScreen from '../screens/LoginScreen';
import LoginFormScreen from '../screens/LoginFormScreen'

export default createAppContainer(createSwitchNavigator({ 
    Login: {screen : LoginScreen},
    LoginForm: {screen: LoginFormScreen},
}, {
  initialRouteName: 'Login',
}));
```
On my LoginScreen button, here action that handled **onPress**

```
<Button
               title="Log In"
               titleStyle={{ fontWeight: 'bold', fontSize: 18 }}
               onPress={() => this.props.navigation.navigate('LoginForm')}
```

And on my LoginFormScreen, I want to once user click back physical button then return to previous screen (LoginScreen). Here are my code
```

constructor(props) {
    super(props); 
    this.handleBackButtonClick = this.handleBackButtonClick.bind(this);
  }

  componentWillMount() {
      BackHandler.addEventListener('hardwareBackPress', this.handleBackButtonClick);
  }

  componentWillUnmount() {
      BackHandler.removeEventListener('hardwareBackPress', this.handleBackButtonClick);
  }

  handleBackButtonClick() {
    this.props.navigation.dispatch(NavigationActions.back());
    this.props.navigation.goBack("Login")
    this.props.navigation.goBack(null)
    this.props.navigation.goBack()
    return true;
  }
```

Have tried all those code above and nothing works with me. Please someone help me out from this problem.

**Comment by kkusanagi** [comment]
using react-navigation: 3.3.2
Same issue when using JS Debugging mode.

**Comment by andrew-koster-** [comment]
This StackActions API is just bad. Half the time when you try to go back to the previous screen, nothing happens. The other half of the time, you get a nonsense error message. Use only NavigationActions instead of StackActions, and things at least work.

**Comment by Sunzkszk** [comment]
> I have 2 screen here. First LoginScreen and LoginFormScreen. LoginScreen have two button, LoginButton : Navigate to LoginFormScreen. So here my AppNavigator.js
> 
> ```
> import LoginScreen from '../screens/LoginScreen';
> import LoginFormScreen from '../screens/LoginFormScreen'
> 
> export default createAppContainer(createSwitchNavigator({ 
>     Login: {screen : LoginScreen},
>     LoginForm: {screen: LoginFormScreen},
> }, {
>   initialRouteName: 'Login',
> }));
> ```
> 
> On my LoginScreen button, here action that handled **onPress**
> 
> ```
> <Button
>    title="Log In"
>    titleStyle={{ fontWeight: 'bold', fontSize: 18 }}
>    onPress={() => this.props.navigation.navigate('LoginForm')}
> ```
> 
> And on my LoginFormScreen, I want to once user click back physical button then return to previous screen (LoginScreen). Here are my code
> 
> ```
> 
> constructor(props) {
>     super(props); 
>     this.handleBackButtonClick = this.handleBackButtonClick.bind(this);
>   }
> 
>   componentWillMount() {
>       BackHandler.addEventListener('hardwareBackPress', this.handleBackButtonClick);
>   }
> 
>   componentWillUnmount() {
>       BackHandler.removeEventListener('hardwareBackPress', this.handleBackButtonClick);
>   }
> 
>   handleBackButtonClick() {
>     this.props.navigation.dispatch(NavigationActions.back());
>     this.props.navigation.goBack("Login")
>     this.props.navigation.goBack(null)
>     this.props.navigation.goBack()
>     return true;
>   }
> ```
> 
> Have tried all those code above and nothing works with me. Please someone help me out from this problem.

i have the same issue as u.Have u figured it out?

**Comment by kkusanagi** [comment]
is it necessary to call BackHandler? By default pressing Android Back, will trigger goBack(). It is not necessary to add any listener to that. Unless, you want to make sure pressing Android Back, will NOT trigger goBack().

Code below should be enough.

```
handleBackButtonClick() {
   if (condition){
    return false;
}else{
    return true;
}
  }
```

**Comment by MCVNick** [comment]
Was playing around with it and this is my code that worked for me.
```
import React from "react";
import { Text, TouchableOpacity } from "react-native";

import styles from "./Profile.style";

const ProfileNavigationOptions = {
  title: "Profile",
  headerLeft: props => (
    <TouchableOpacity onPress={props.onPress} style={styles.exitTouchable}>
      <Text style={styles.xText}>X</Text>
    </TouchableOpacity>
  )
};

export default ProfileNavigationOptions;

```

**Comment by ArsalanAhmed102** [comment]
Its working for me.
 <Drawer.Screen
                name="User Profile"
                component={Profile}
                options={({ navigation }) => ({
                    headerShown: true,
                    unmountOnBlur: true,
                    headerStyle: { backgroundColor: '#8cc543' },
                    headerTitleStyle: { color: '#FFFF' },
                    headerLeft: () => (
                        <TouchableOpacity onPress={() => navigation.goBack()}>
                            <Icon name="arrow-back-circle-sharp" size={24} color="#FFFFFF" />
                        </TouchableOpacity>
                    ),
                })}
            />
