### ISSUE TITLE
tab bar should return to initial route

### ISSUE THREAD

**Issue by despreston** [react-community/react-navigation#1524]
Im not sure if this is the default behavior for a tab bar in native iOS, buts its certainly a popular design pattern.

If I have have a tab bar with stack navigators for each tab, I expect that tapping the icon of the tab that I am currently viewing will return me to the initial route of that tab.

Are there any plans to include this?

**Comment by ericvicenti** [comment]
This has been requested before and I think it would be good to add. I'd be happy to provide guidance on how to implement this, if anybody wants to take the lead

**Comment by despreston** [comment]
somewhat related: https://github.com/react-community/react-navigation/pull/1335

**Comment by sanjayholla94** [comment]
@kelset Since #1335 has been merged, I think this can be closed (?). Pinging OP @despreston

**Comment by kelset** [comment]
yeah thanks for letting me know @sanjayholla94
