### ISSUE TITLE
Programmatically Change Tabs on Nested TabNavigator

### ISSUE THREAD

**Issue by joncursi** [react-community/react-navigation#1526]
Consider the case of a TabNavigator nested inside of a Stack Navigator:

```js
const NavigationStack = StackNavigator({
  ...
  STACK_KEY_TABS: { screen: TabsStack },
  ...
});

const TabsStack = TabNavigator({
  SCREEN_KEY_A: { screen: ScreenA },
  SCREEN_KEY_B: { screen: ScreenB },
});
```

If I am on TabsStack > `ScreenA`, how do I create an onPress event on some element inside `ScreenA` that will change the active tab to TabsStack > `ScreenB`?

I have tried:

```js
        const action = NavigationActions.reset({
          actions: [
            NavigationActions.navigate({
              action() {
                navigation.navigate(SCREEN_KEY_B);
              },
              routeName: STACK_KEY_TABS,
            }),
          ],
          index: 0,
        });

        navigation.dispatch(action);
```

But nothing happens. I put a `console.log` statement inside of `action()` and it never fires. So I then tried:

```js
        const action = NavigationActions.reset({
          actions: [
            NavigationActions.navigate({
              routeName: SCREEN_KEY_B,
            }),
          ],
          index: 0,
        });

        navigation.dispatch(action);
```

But I get a redbox error saying that `SCREEN_KEY_B` is an invalid route name, I'm guessing since SCREEN_KEY_B is unknown to the root `NavigationStack`, since it's defined within the `TabsStack`.

**Comment by monteithpj** [comment]
Have you just tried navigation.navigate(SCREEN_KEY_B) - I don't see why you need a reset at all

**Comment by joncursi** [comment]
Wow! Thanks @monteithpj - I was overengineering the problem when the solution was simple!

**Comment by liu-yuhuan** [comment]
@joncursi i have same problem in my App.js
i got error when i use navigation.navigate 
can you help me to figure this out?


```
export default class App extends Component<{}> {
    
   someFun() {
       .... 
      navigation.navigate('SCREEN_KEY_B')
   }
    
    render() {
        return <NavigationStack somefunc={this.someFun}/>
    }
}

```





```

const NavigationStack = StackNavigator({
 ...
STACK_KEY_TABS: { screen: TabsStack },
 ...
});
 
```

```
const TabsStack = TabNavigator({
  SCREEN_KEY_A: { screen: ScreenA },
  SCREEN_KEY_B: { screen: ScreenB },
});

```

**Comment by brentvatne** [comment]
https://reactnavigation.org/help
