### ISSUE TITLE
How to make deep linking for nested navigators?

### ISSUE THREAD

**Issue by diegorodriguesvieira** [react-community/react-navigation#1527]
I have this code below, I am trying to do deep linking with nested navigators, but it is not working...

I'm using the URL: test://test/main/mainscreentwo

I'm trying to reproduce this example
https://github.com/react-community/react-navigation/issues/687

```
import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View,
  Platform,
} from 'react-native';

import { StackNavigator, TabNavigator } from 'react-navigation';

class MainScreenOne extends Component {
  render() {
    return (
      <View>
        <Text>
          MainScreenOne
        </Text>
      </View>
    );
  }
}

class MainScreenTwo extends Component {
  render() {
    return (
      <View>
        <Text>
          MainScreenTwo
        </Text>
      </View>
    );
  }
}

class MainScreenThree extends Component {
  render() {
    return (
      <View>
        <Text>
          MainScreenThree
        </Text>
      </View>
    );
  }
}

class SecondScreen extends Component {
  render() {
    return (
      <View>
        <Text>
          SecondScreen
        </Text>
      </View>
    );
  }
}

const App = StackNavigator({
  Main: {
    screen: TabNavigator({
      MainScreenOne: {
        screen: MainScreenOne,
        path: 'mainscreenone',
      },
      MainScreenTwo: {
        screen: MainScreenTwo,
        path: 'mainscreentwo',
      },
      MainScreenThree: {
        screen: MainScreenThree,
        path: 'mainscreenthree',
      },
    }),
    path: 'main',
  },
  Second: {
    screen: SecondScreen,
    path: 'second',
  },
})

const prefix = Platform.OS == 'android' ? 'test://test/' : 'test://';
const MainApp = () => <App uriPrefix={prefix} />;
AppRegistry.registerComponent('AppMuffato', () => MainApp);
```

**Comment by filippofilip95** [comment]
I have the same question :)

**Comment by rickardinho** [comment]
Me too

**Comment by aaronbuchanan** [comment]
@diegorodriguesvieira @filippofilip95 @rickardinho any of you make progress on this in the last 27 days :)?

**Comment by aroth** [comment]
Anything?

**Comment by filippofilip95** [comment]
Unfortunately no :(

**Comment by twairball** [comment]
This works if you pass `prefix` to the child navigator. 

````
# Root.js
const prefix = Platform.OS == 'android' ? 'test://test/' : 'test://';
const Root = StackNavigator({
    Main: { screen: Main, path: 'main'}, ...
})

render() {
    <Root urlPrefix={prefix} />
}

# Main.js
const prefix = Platform.OS == 'android' ? 'test://test/main/' : 'test://main/';
const Tabs = TabNavigator({
    Home: { screen: Home, path: 'home' },
    Messages: { screen: Messages, path: 'messages'}, 
})

render() {
    return <Tabs urlPrefix={prefix}> 
}
````

`test://main/home` and `test://main/messages` will switch tabs.

**Comment by alxvallejo** [comment]
@twairball you're suggesting we have to define the route for each nested navigation, and then a path for each screen within that navigation that we want to route to? What year is it?!

**Comment by twairball** [comment]
I'm a rails guy, some none of this router stuff makes sense to me. Please feel free to teach me a more elegant method.

**Comment by pietro909** [comment]
Any progress on this? I've tried everything here and apparently nothing works -_-

**Comment by magicismight** [comment]
This would work for nested navigators.

```
import React, { Component } from 'react';
import { Linking } from 'react-native';

export default function createLinkingAwareContainer(Comp) {
  const router = Comp.router;
  return class extends Component {
    static router = router;

    constructor(props) {
      super(props);
      this.state = {
        nav: props.navigation.state
      };
    }

    _urlToPathAndParams(url: string) {
      const params = {};
      const delimiter = this.props.uriPrefix || '://';
      let path = url.split(delimiter)[1];
      if (!path) {
        path = url;
      }
      return {
        path,
        params
      };
    }

    _handleOpenURL = (url) => {
      const parsedUrl = this._urlToPathAndParams(url);
      if (parsedUrl) {
        const { path, params } = parsedUrl;
        const action = router.getActionForPathAndParams(path, params);
        if (action) {
          this.props.navigation.dispatch(action);
        }
      }
    };

    componentDidMount() {
      Linking.addEventListener('url', ({ url }: { url: string }) => {
        this._handleOpenURL(url);
      });

      Linking.getInitialURL().then(
        (url: string) => url && this._handleOpenURL(url)
      );
    }

    componentWillUnmount() {
      Linking.removeEventListener('url', this._handleOpenURL);
    }

    render() {
      return <Comp {...this.props} />;
    }
  };
}
```


```
createLinkingAwareContainer(ChildNavigator)
```

**Comment by ivanzotov** [comment]
A small article how to set up deep linking with nested navigators – https://medium.com/@ivanzotov/react-native-deep-linking-with-authorization-screen-drawer-and-nested-navigators-in-react-4f702b1520a0, hope it helps

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!

**Comment by yuoppp** [comment]
@twairball not working for me. 
`test://main/smthother/ works`
but
`test://main/home` doesn't

**Comment by hegelstad** [comment]
@twairball
@brentvatne 
Seems like the issues comes from `pathUtils.js:94`: `pathMatch = re.exec(pathToResolve);`

The regexes wont accept paths starting with `/` i.e. `'/messages'`, thats why it works when you add a prefix to the nested navigator, because it gets rid of the initial `/`.

**Comment by hegelstad** [comment]
However it seems the router won't go deeper in a stack if i supply another path when I am already on the same path.

My setup is:

```
- StackNavigator            prefix: marketplace://marketplace/
    - TabNavigator:            path: tabs
         - StackNavigator:   path: messages
             - Screen:             path: :id
```

If i do: `marketplace://marketplace/tabs/messages/123abc` I am navigated to the correct screen.
If i do: `marketplace://marketplace/tabs/messages/` I am navigated to the `messages` StackNavigator but if I follow with: `marketplace://marketplace/tabs/messages/123abc` I am not being navigated to the correct screen. Nothing happens during the last invocation.

**Comment by hegelstad** [comment]
@magicismight edit your example please, your snippet will work for nested variable paths as well with this change :) 

```javascript
_handleOpenURL = (url) => {
      const parsedUrl = this._urlToPathAndParams(url);
      if (parsedUrl) {
        const { path, params } = parsedUrl;
        const action = router.getActionForPathAndParams(path, params);
        if (action) {
          if (action.action) {
            if (action.action.action) {
              this.props.navigation.dispatch(action.action.action);
            } else {
              this.props.navigation.dispatch(action.action);
            }
          } else {
            this.props.navigation.dispatch(action);
          }
        }
      }
    };
```

**Comment by Taylor123** [comment]
@hegelstad i'm seeing the same thing currently, where I cannot link deeper within a tab I'm already on. Were you able to get something working for this?

**Comment by hegelstad** [comment]
Did you follow @magicismight’s example with my changes to handleUrl?

It should work.

> On 20 Aug 2018, at 21:28, Taylor Johnson <notifications@github.com> wrote:
> 
> @hegelstad i'm seeing the same thing currently, where I cannot link deeper within a tab I'm already on. Were you able to get something working for this?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.

-- 


REALIZE YOUR DIGITAL ROADMAP

Enterprise Intelligence Graph for 
Compliance, Governance, and Transformation

ardoq.com 
<https://ardoq.com/?utm_source=email_sig&utm_medium=email>

 
<https://content.ardoq.com/ardoq_mornings_copenhagen-11th-of-september-2018>

**Comment by KevinDoom** [comment]
If you to get to screens in nested navigators without having to define a path for each navigator and thereby creating huge paths, try setting `path: ''` for each parent.

So if my nav structure is something like:

- SwitchNavigator
  - Auth
  - Main (StackNavigator, path: '')
    - Tabs (TabNavigator, path: '')
      - Camera (Component, path: 'camera')

The url `test://camera' will open the Camera component instead of having to define a path like 'test://main/tabs/camera'

**Comment by DISKONEKTeD** [comment]
@KevinDoom 

can't believe it was actually just that easy. all the other solutions are pointlessly complex. thank you.

**Comment by DISKONEKTeD** [comment]
@KevinDoom does this work in iOS? Seems to be working fine on android, but I can't seem to get it to work on iOS. Is it just me? Maybe I have something setup wrong.

**Comment by KevinDoom** [comment]
@DISKONEKTeD yep, I have it working on both. The only thing I can think to suggest is double checking your uriPrefix for iOS and make sure you're testing the correct uri.

**Comment by DISKONEKTeD** [comment]
@KevinDoom you were correct, my prefix was off. thanks :)

**Comment by sheminusminus** [comment]
@KevinDoom thank you, thank you, thank you for that tip! would +10000 on that if i could

**Comment by Farhadkm** [comment]
As mentioned, issue is going deeper on screens that are already chosen. After trying a lot of things I finally ended up doing this (for ios):
on a screen that you are sure you can reach (usually top level screens) use Linking.addEventListener('url', this._handleOpenURL);
and then parse the url and based on the info navigate from there

**Comment by nicholasrq** [comment]
ok, well i've done some research on this and came up with some tips that might help you with deep linking

tl;rd: use unique names for every screen. also take a look at fifth item of the list above

1. All your navigators **MUST** have unique names for every screen. This is essential for current deep linking implementation to work. Basically, if you have somewhere two different screens with the same name – nothing will work as you expect.

2. If you have tab in your app and your structure is something similar to this:

- Tabs (TabNavigator):
  - Feed (StackNavigator)
  - Photos (StackNavigator)
  - Profile (StackNavigator):
    - Profile (Component) – Initial screen of a stack
    - Settings (Component)

and you will try to navigate to `myapp://tabs/profile/settings` it won't work because `react-navigation` will try to lookup `settings` inside of the (Component) part of Profile stack, not inside the stack itself, so navigation will look like this:

- **Tabs (TabNavigator):**
  - Feed (StackNavigator)
  - Photos (StackNavigator)
  - **Profile (StackNavigator):**
    - **Profile (Component)** <-- you'll be navigated here
    - Settings (Component)

Because Settings is a component, it can't contain nested screens/routes and deep linking to Settings screen won't work. This is also true for any other nesting type (stacks, switch navigators, etc.).

3. As @KevinDoom mentioned above, user empty path (`path: ''`) to omit part of the path.

4. Keep in mind that `path` parameter is used to only lookup navigators, `react-navigation` won't use it for actual `.dispatch()` method. That's why you can't have, for example, `Main` StackNavigator inside of TabNavigator.

5. You can always check your screens structure by accessing `router` property of any navigator or your root app container:

```javascript
const tabs = createBottomTabsNavigator(...);
console.log(tabs.router.childRouters)
```

or

```javascript
const appContainer = createAppContainer(...);
console.log(appContainer.router.childRouters)
```

I also suggest `react-navigation` maintainers to update their docs on deep linking because all that's been said is really awkward and not intuitive at all. I spent few hours figuring out how it works.

**Comment by ryansanders67** [comment]
@nicholasrq thank you for the post! Going through each of your steps helped me to figure out the my own problem with deep linking. I ended up having a duplicate key in two of my navigators (each with different screens though) which caused the problem. But after renaming the key names for each screen, that solved the problem. Thanks for the detailed write up!

**Comment by maitrungduc1410** [comment]
@nicholasrq thanks, in my case, I have 2 screens with same name, your answer saves me

**Comment by wallacerodrigon** [comment]
This works fine. 

https://medium.com/@ivanzotov/react-native-deep-linking-with-authorization-screen-drawer-and-nested-navigators-in-react-4f702b1520a0

**Comment by pperron** [comment]
@nicholasrq answer help me a lot too, just remaining a problem on my side... 

If I open a deep link in my nested navigator the first time with a specific path, it works OK (for example: CO/:itemid). If I use another deep link to that same page but with a different "itemid", the page remain on the first deep link.

My `componentDidMount()` has a `this._FocusListener = this.props.navigation.addListener('focus', async () => {...})` but it not getting triggered when accessing the same page...

Any seen the same problem and found a solution ?

**Comment by faerylay** [comment]
const linking = {

  prefixes: [['yoururl://'],](url)

  config: {
    initialRouteName: 'home',
    screens: {
      home: {
        path: 'home',
        screens: {
          path: 'homeDetail',
        },
      },
      event: {
        path: 'event',
        screens: {
          event: 'eventDetail',
        },
      },
      timeline: {
        path: 'timeline',
        screens: {
          friendProfileScreen: {
            path: 'friendProfileScreen/:id',
          },
        },
      },
      chat: {
        path: 'chat',
        screens: {
          chat: 'chatroom',
        },
      },
      profile: {
        path: 'profile',
        screens: {
          path: 'profiledetail',
        },
      },
    },
  },
};

**Comment by faerylay** [comment]
```
const linking = {
  prefixes: ['yoururl://'],
  config: {
    initialRouteName: 'home',
    screens: {
      home: {
        path: 'home',
        screens: {
          screenName: {
            path: 'screenName',
          },
        },
      },
      event: {
        path: 'event',
        screens: {
          screenName: {
            path: 'screenName',
          },
        },
      },
      timeline: {
        path: 'timeline',
        screens: {
          friendProfileScreen: {
            path: 'friendProfileScreen/:id',
          },
        },
      },
      chat: {
        path: 'chat',
        screens: {
          Room: {
            path: 'Room',
          },
        },
      },
      profile: {
        path: 'profile',
        screens: {
          screenName: {
            path: 'screenName',
          },
        },
      },
    },
  },
};

> 
```
