### ISSUE TITLE
Transparent modal background

### ISSUE THREAD

**Issue by yanush** [react-community/react-navigation#1528]
I'm using two nested StackNavigators to show screens and modals.
Is it possible to have a transparent background for modals?
Currently I get a white background and I wish it to be transparent so I can see the card below on the stack.

**Comment by alexwasner** [comment]
I was about to open an issue for the same thing.

**Comment by vendramini** [comment]
+1

**Comment by felipap** [comment]
It's no that the modal's background can't be transparent, but that the screen on the back is fading away. :/

**Comment by felipap** [comment]
Got rid of the effect by commenting out inside `CardStackStyleInterpolator.js` the line that returns the opacity value for the effect that I am using.

Do:
```js
  return {
    // opacity: opacity,
    transform: [{ translateX }, { translateY }],
  };
```

**Comment by pxue** [comment]
Just incase anyone's wondering the proper way without modifying the package source:

```jsx

// create custom transitioner without the opacity animation, ie. for iOS
function forVertical(props) {
  const { layout, position, scene } = props;

  const index = scene.index;
  const height = layout.initHeight;

  const translateX = 0;
  const translateY = position.interpolate({
    inputRange: ([index - 1, index, index + 1]: Array<number>),
    outputRange: ([height, 0, 0]: Array<number>)
  });

  return {
    transform: [{ translateX }, { translateY }]
  };
}

// set it as the transitionConfig param on your stack navigator
const App = StackNavigator(
  {
    Modal: { screen: Modal }
  },
  {
    mode: "modal",
    headerMode: "none",
    transitionConfig: () => ({ screenInterpolator: forVertical })
  }
);
```

If you want to overwrite all the default transitioners, then you should implement all the different animations as specified in the default `CardStackStyleInterpolator.js`

**Comment by ahanriat** [comment]
@pxue thank you

**Comment by kumarpatel** [comment]
https://github.com/react-community/react-navigation/issues/619#issuecomment-315080300
Add this to your StackNavigator
```
cardStyle: {
        backgroundColor: 'rgba(0,0,0,0.5)',
      }
```

**Comment by kelset** [comment]
Pinging OP @yanush since this issue is quite old and related to an old version of the lib. If no answer I'll close in 7 days.

Moreover as pointed out by @kumarpatel there are ways to style the cards.

**Comment by kelset** [comment]
Hi there @yanush,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.

**Comment by theworldslicense** [comment]
in response to @kumarpatel 
#000000 will add a black background, but the easiest way is to add:
```
cardStyle: {
        backgroundColor: 'transparent',
      }
```
to all modal stacks

**Comment by fadookie** [comment]
You may also need to add something like this:
```
transitionConfig : () => ({
  containerStyle: {
    backgroundColor: 'transparent',
  }
}),
```

I put together a simple project where I was messing around with this, showing [a nested, non-animated modal with a transparent background](https://github.com/fadookie/react-navigation-nested-modal-example/tree/dab71301e16443417bf41ee50dc08157b4bd388d).

**Comment by Ashoat** [comment]
https://github.com/react-navigation/react-navigation-stack/commit/a380437f354ab05be0932c826e9c0e8a6bd59147 introduces support for this!

**Comment by fawaz-ahmed** [comment]
You need to have these 2 options in parent StackNavigatorConfig :
  `cardStyle: { opacity: 1 }, transparentCard: true`

and then in the child stack having modal or any transparent screen, you need to have this StackNavigatorConfig :
`transparentCard: true`

**Comment by phuochau** [comment]
@fawaz-ahmed do we have a working sample? Because I have configured as your guidance but seem it's not working at all

**Comment by jbowa** [comment]
Try the following:

```
  {
    Main: MainStack,
    DeleteModal: DeleteModal
  },
  {
    mode: 'modal',
    headerMode: 'none',
    cardStyle: {
      backgroundColor: 'rgba(0, 0, 0, 0)',
      opacity: 1
    },
    transitionConfig: () => ({
      containerStyle: {
        backgroundColor: 'rgba(0, 0, 0, 0)'
      }
    })
  }
```

**Comment by MaxInMoon** [comment]
_Just a note regarding my own router architecture_:

`cardStyle: { opacity: 1 }` is required only on Android and breaks the fading animations of the other modals located at the same level, leading to an ugly result.

**Comment by CyxouD** [comment]
@fawaz-ahmed this solution didn't help me. I was migrating react-navigation from 1.5.11 to 3.0.9. 
Previously I had only
```
    cardStyle: {
      backgroundColor: "transparent",
      opacity: 1
    },
```
However, after update it stopped working. I've fixed it adding **transparentCard: true**, so that my config looks like this
```
  {
      ......
  },
  {
    initialRouteName: "....",
    mode: "modal",
    transparentCard: true,
    cardStyle: {
      backgroundColor: "transparent",
      opacity: 1
    },
    defaultNavigationOptions: {
      headerStyle: {
        backgroundColor: Colors.WHITE,
        borderBottomWidth: 0,
        elevation: 0
      },
      headerTransparent: true
    }
  }
```
Thank you for this **transparentCard: true** prop :)

**Comment by Momazo7u7** [comment]
This is awesome... 

Been wondering if i should implement a popover menu component in my app, but a quick solution would be using this trick and navigating to a screen with the menu in one of the corners.

So far this library is ultra customizable 7u7 thanks developers

**Comment by mernxl** [comment]
> @fawaz-ahmed this solution didn't help me. I was migrating react-navigation from 1.5.11 to 3.0.9.
> Previously I had only
> 
> ```
>     cardStyle: {
>       backgroundColor: "transparent",
>       opacity: 1
>     },
> ```
> 
> However, after update it stopped working. I've fixed it by adding **transparentCard: true**, so that my config looks like this
> 
> ```
>   {
>       ......
>   },
>   {
>     initialRouteName: "....",
>     mode: "modal",
>     transparentCard: true,
>     cardStyle: {
>       backgroundColor: "transparent",
>       opacity: 1
>     },
>     defaultNavigationOptions: {
>       headerStyle: {
>         backgroundColor: Colors.WHITE,
>         borderBottomWidth: 0,
>         elevation: 0
>       },
>       headerTransparent: true
>     }
>   }
> ```
> 
> Thank you for this **transparentCard: true** prop :)

This makes my modal transparent, but the buttons on the modal stop working after adding the transparent property.

using 
* react-navigation: 3.11.1
* react-native-screens: 1.0.0-alpha.23

**Comment by smuxx** [comment]
i have the same problem as @mernxl... interactions with the screen stopped working after setting transparentCard: true

**Comment by yanush** [comment]
@fawaz-ahmed and @smuxx , what if your remove the useScreens() call? does it fix your issues?

**Comment by smuxx** [comment]
yes I found that removing useScreens() fixes my issues

**Comment by high-performance-hery** [comment]
Is removing `useScreens()` altogether an acceptable solution? Doesn't that disable native navigation containers entirely on Android?

**Comment by danyalasif** [comment]
> i have the same problem as @mernxl... interactions with the screen stopped working after setting transparentCard: true

Having this same issue right now, removing useScreens() does fix it, but it may not be the desired way to do this.

**Comment by PabloTeari** [comment]
Same problem :(. I can use reanimated-bottom-sheet, but one more lib =/

**Comment by lifenautjoe** [comment]
Im having this problem on `react-navigation-stack@2.8.2` and no proposed solutions work.

Is this only supported for react-navigation 5.0?

**Comment by d4ins** [comment]
@lifenautjoe It's works with 4.x.x

Here's a code sample:
```
createStackNavigator({
    ...
  }, {
    mode: 'modal',
    headerMode: 'none',
    transparentCard: true,
});
```

**Comment by mernxl** [comment]
Hello, just to add. I am currently using the Modal component from react-native to for my modals. I use it to display all modals around application, so far i haven't really notice any performance issues. Used it with ReactNavigation 3.x, 4.x and now still using with 5.x.

I mean rather than removing `useScreens` you could opt into this approach. Thanks :)

This component handles setting the Status bar to give seamless look for the Modal (if you have to use my approach you will need to change coloring to support the theme of your app)

Here's a snippet

```typescript
// ModalScreen Component
import color from 'color';
import { Icon } from 'native-base';
import React from 'react';
import {
  InteractionManager,
  KeyboardAvoidingView,
  Modal,
  StatusBar,
  StatusBarProps,
  StyleSheet,
  TouchableWithoutFeedback,
  View,
} from 'react-native';

import { themeVars } from '../../theme';

interface ModalScreenState {
  isVisible: boolean;
}

/**
 * ModalScreen Component
 *
 * Used to display a dark transparent modal(by default) over any content
 * @property showClose whether to show close icon for closing
 *
 * The close and the backButton events are listened by the onRequestClose prop
 */
class ModalScreen extends React.Component<ModalScreenProps, ModalScreenState> {
  alive = true;
  statusBar?: StatusBarProps;

  constructor(props: ModalScreenProps) {
    super(props);
    this.state = {
      isVisible: props.visible,
    };

    if (this.state.isVisible) {
      InteractionManager.runAfterInteractions(() => this.setUpStatusBar(true));
    }
  }

  toggleModal = () => {
    this.setUpStatusBar(!this.state.isVisible);

    InteractionManager.runAfterInteractions(
      () =>
        this.alive &&
        this.setState({
          isVisible: !this.state.isVisible,
        })
    );
  };

  setUpStatusBar = (asModalBecomesVisible: boolean) => {
    if (asModalBecomesVisible) {
      if (!this.statusBar) {
        this.statusBar = StatusBar.pushStackEntry({
          hidden: false,
          animated: true,
          barStyle: 'light-content',
          backgroundColor: color(themeVars.brandPrimary).darken(0.5).hex(),
        });
      }
    } else {
      if (this.statusBar) {
        StatusBar.popStackEntry(this.statusBar!);
        this.statusBar = undefined;
      }
    }
  };

  componentDidUpdate(prevProps: Readonly<ModalScreenProps>): void {
    if (prevProps.visible !== this.props.visible) {
      this.toggleModal();
    }
  }

  componentWillUnmount(): void {
    this.alive = false;
    this.setUpStatusBar(false);
  }

  render() {
    return (
      <KeyboardAvoidingView behavior="height">
        <Modal
          onShow={this.props.onShow}
          visible={this.state.isVisible}
          animationType={this.props.type}
          transparent={this.props.transparent}
          onRequestClose={this.props.onRequestClose}>
          <View style={styles.mainContainer}>
            {this.props.showClose && (
              <TouchableWithoutFeedback onPress={this.props.onRequestClose}>
                <View style={styles.modalHeader}>
                  <View style={styles.closeButton}>
                    <Icon
                      name={'close'}
                      color={themeVars.brandLight}
                      onPress={this.props.onRequestClose}
                    />
                  </View>
                </View>
              </TouchableWithoutFeedback>
            )}
            {!this.props.noBackDropClose ? (
              <TouchableWithoutFeedback onPress={this.props.onRequestClose}>
                <View style={styles.childrenContainer}>{this.props.children}</View>
              </TouchableWithoutFeedback>
            ) : (
              <View style={styles.childrenContainer}>{this.props.children}</View>
            )}
          </View>
        </Modal>
      </KeyboardAvoidingView>
    );
  }
}

export const styles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: '#00000080',
  },
  childrenContainer: {
    flex: 1,
  },
  modalHeader: {
    width: '100%',
  },
  closeButton: {
    height: themeVars.toolbarHeight,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  iconStyle: {
    fontSize: 30,
    color: themeVars.brandLight,
  },
});

interface ModalScreenProps {
  visible: boolean;
  transparent?: boolean;
  onShow?: () => any;
  showClose?: boolean;
  noBackDropClose?: boolean;
  type?: 'none' | 'fade' | 'slide';
  onRequestClose: () => void;
}

(ModalScreen as any).defaultProps = {
  type: 'slide',
  visible: false,
  showCross: false,
  transparent: true,
  noBackDropClose: false,
};

export { ModalScreen };
```

**Comment by ObidosDev** [comment]
`react-navigation-stack@2.10.2` can't get transparent modal on android.
`transparentCard` - removed
`transitionConfig` - removed

**Comment by nikhilborana** [comment]
try this, this will do the work you are looking for.


<Stack.Navigator
  screenOptions={{
    headerShown: false,
    cardStyle: { backgroundColor: 'transparent' },
    cardOverlayEnabled: true,
    cardStyleInterpolator: ({ current: { progress } }) => ({
      cardStyle: {
        opacity: progress.interpolate({
          inputRange: [0, 0.5, 0.9, 1],
          outputRange: [0, 0.25, 0.7, 1],
        }),
      },
      overlayStyle: {
        opacity: progress.interpolate({
          inputRange: [0, 1],
          outputRange: [0, 0.5],
          extrapolate: 'clamp',
        }),
      },
    }),
  }}
  mode="modal"
>
  <Stack.Screen name="Home" component={HomeStack} />
  <Stack.Screen name="Modal" component={ModalScreen} />
</Stack.Navigator>

**Comment by ObidosDev** [comment]
@nikhilborana we are talking about `4.+` version, not `5.+`

**Comment by ObidosDev** [comment]
@lifenautjoe I think, I have found the solution. 
This is `stackConfig` for `createStackNavigator`

```
{
    headerMode: 'screen',
    mode: 'modal',
    defaultNavigationOptions: {
      ...getCustomNavigationOptions(),
      cardStyleInterpolator: ({ current }) => ({
        cardStyle: {
          opacity: current.progress,
        },
      }),
    },
    navigationOptions: {
      cardStyle: {
        backgroundColor: 'transparent',
      },
    },
  }
```

**Comment by akshayguptaquovantis** [comment]
For those who are still facing this issue
you have to call in app.js first.

import { enableScreens } from 'react-native-screens';
enableScreens(false);

then add detachPreviousScreen: false in screenOptions. and it will work
