### ISSUE TITLE
What can I do to capture events in the toggle tab bar?

### ISSUE THREAD

**Issue by roselind** [react-community/react-navigation#1530]
What can I do to capture events when switch  the toggle tab bar?

initialRouteName  It not work ！

my Code：

`

const mainTabScreens ={
  Home:{
    screen:Home,
  },
  JobListPage: {
    screen: JobListPage,
  },
  MessageOverView: {
    screen: MessageOverView,
  },
}

const mainScreenNavigator = TabNavigator (
  mainTabScreens,{
  initialRouteName:'JobListPage',
  headerMode: 'screen',
  tabBarPosition:'bottom',
  swipeEnabled: false,
  animationEnabled: false,
  scrollEnabled:false,
  tabBarOptions : tabBarStyles
});

`

**Comment by spencercarli** [comment]
You'll need to create a custom tab bar. Here's [an example](https://snack.expo.io/HkzW4clOZ)
