### ISSUE TITLE
Quick click, jump many times。。。

### ISSUE THREAD

**Issue by Hmily-68** [react-community/react-navigation#1532]
### Current Behavior

 <Button
          onPress={() => navigate('Chat', { user: 'Lucy' })}
          title="Chat with Lucy"
        />

If you click this button quickly, you will jump over the interface many times.
### Expected Behavior

Click on many times, only jump once, follow-up click No effect.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  
| react-native     |  
| node             | 
| npm or yarn      |

**Comment by matthamil** [comment]
This is a repeat of https://github.com/react-community/react-navigation/issues/135. Currently, navigation actions are not idempotent unless they are from a TabNavigator.

**Comment by johnnylc** [comment]
I use debounce from lodash as a workaround.

**Comment by CocoaZX** [comment]
@johnnylc How do you fix this? I can't find where to write the code
