### ISSUE TITLE
several issues with DrawerNavigator & nested navigators [1.0.0-beta.9]

### ISSUE THREAD

**Issue by perscrew** [react-community/react-navigation#1533]
Hi everybody, I faced many problems with the DrawerNavigator and his nested routes (StackNavigator).

Here you will find my react-navigation configuration : 

```
const MainDrawerNavigator = DrawerNavigator(
  {
    HomeDrawer: {
      screen: StackNavigator(
        {
          Home: { screen: HomeScreen },
          Detail: { screen: DetailScreen },
          Photo: { screen: PhotoScreen },
          Scan: { screen: ScanScreen }
        },
        {
          initialRouteName: "Home",
          headerMode: "screen"
        }
      )
    },
    AddDrawer: {
      screen: StackNavigator(
        {
          Add: { screen: AddDrawerScreen },
          AddInfo: { screen: AddInfoScreen },
          Photo: { screen: PhotoScreen },
          Detail: { screen: DetailScreen },
          Home: { screen: HomeScreen }
        },
        {
          initialRouteName: "Add",
          headerMode: "screen"
        }
      )
    },
    ScanDrawer: {
      screen: ScanDrawerScreen
    },
    PrivacyDrawer: {
      screen: StackNavigator(
        { Privacy: { screen: PrivacyScreen } },
        { headerMode: "screen" }
      )
    }
  },
  {
    initialRouteName: "HomeDrawer",
    headerMode: "screen"
  }
);

const AppStackNavigator = StackNavigator(
  {
    MainDrawerNavigator: { screen: MainDrawerNavigator },
    Add: { screen: AddDrawerScreen },
    AddInfo: { screen: AddInfoScreen },
    Photo: { screen: PhotoScreen },
    Detail: { screen: DetailScreen }
  },
  {
    headerMode: "screen",
    navigationOptions: { header: null } // ADDED THIS
  }
);
```

1°) When I dispatch a navigate action from a nested route contained in the DrawerNavigator, the current Drawer label is updated with the current sub route component. Example with my HomeDrawer route. I dispatched a navigate("Detail") and the drawer displayed "HomeDrawer" in the menu. However I indicated the initialRouteName: "Home".

Code used to navigate on the OnPress event: 
```
  goToDetail(medicine) {
    this.props.navigation.navigate("Detail", { medicine });
  }
```
See screenshot here : http://prntscr.com/f8e0vf

2°) When I reset the route state in the Drawer nested route, my screen is displayed twice. Note that I used the sub actions of MainDrawerNavigator. It works without the sub actions but I lost the app Header.

So in this example the "Detail" screen is displayed twice. I push the back button and I come back in another "Detail" screen. The next back button bring me back to the Home screen.

```
this.props.navigation.dispatch(
                      NavigationActions.reset({
                        index: 0,
                        key: null, // I tried to remove this but this is similar
                        actions: [
                          NavigationActions.navigate({
                            routeName: "MainDrawerNavigator",
                            action: NavigationActions.navigate({
                              routeName: "Detail",
                              params: { medicine: medicineUpd }
                            })
                          })
                        ]
                      })
                    );
```
My app is finished but I cannot published it with these issues. 

Could you please bring me some help ? 

Best Regs.

**Comment by saeropark** [comment]
Are you trying to pass an object called medicine? From what i know you can only pass a string.

**Comment by perscrew** [comment]
The medicine objects is working because the Detail screen displayed information correctly.

**Comment by saeropark** [comment]
Oh have you tried to use initialRoute?

**Comment by saeropark** [comment]
@perscrew sorry this is out of topic to your question, but i have a question left unanswered #1364 regarding passing objects like your goToDetail() are you able to share with me? i am so sorry to disturb your thread though but it will be great if you could help me

**Comment by perscrew** [comment]
Hi everybody, any comment regarding my problem will be fine ! :'(

**Comment by vendramini** [comment]
@perscrew did u solve that?

thanks.

**Comment by spencercarli** [comment]
Is this still an issue in the latest release? If so please re-open (or comment and I can do so). Thanks!

**Comment by arled** [comment]
Who uses double quotes?
