### ISSUE TITLE
How to Hide header

### ISSUE THREAD

**Issue by saeropark** [react-community/react-navigation#1534]
![photo_2017-05-16_17-07-23](https://cloud.githubusercontent.com/assets/25519466/26099204/9fdb5e24-3a5c-11e7-9b19-ecaaffb58db8.jpg)

Hi as you can see I have 3 very ugly headers. 

How it works is the main header "EVENTS & ANNOUNCEMENTS" is under a drawer navigator from `sidebar.js ` 

by clicking on each item drawer, it will open up a screen, and in this case a view with 2 tabs (the blue tabs) `eventTabs.js`

SO WHEN i click on each listitem, it will open up another screen with the header. currently. I have hidden the TITLE: PULSE EVENT header., but i was wondering is there a way to set "EVENTS & ANNOUNCEMENTS to the listitem title?

or 

to hide sidebar.js header and enforce a the current screen's EventStack navigator header?

Inside ``eventTabs.js`:

```
const AnnStack = StackNavigator({
    List: {screen: EventList},
    Info: {screen: EventDetail},
    
} );

const EventTab = TabNavigator({
    Upcoming: { screen: AnnStack },
    Past: { screen: PastTab },
},
    { mode: 'modal' } // this is needed to make sure header is hidden on ios
);

const EventStack = StackNavigator({
    Home: {screen: EventTab},
});
```

**Comment by saeropark** [comment]
Is my issue similar to #88  and #141 ?

**Comment by bktoky** [comment]
static navigationOptions = {
    header: null,
  };

**Comment by saeropark** [comment]
@bktoky i have done that to hide the TITLE: XXX header. however, i wish to either 
- replace it with EVENTS & ANNOUNCEMENTS header
- hide EVENTS & ANNOUNCEMENTS header when i navigate into eventTabs.js

**Comment by xipgroc** [comment]
have you tried headerMode: 'none' as option of StackNavigator?

**Comment by JanPeter** [comment]
headerMode: 'none' does not work for me. At least if I configure it like the following:

```
export default class Onboarding extends Component {

  static navigationOptions = {
    headerMode: 'none'
  }

  ...
}
```

`header: null` works for me.

**Comment by jaycee425** [comment]
is there a way to do it programmatically? 
header: navigation.state.params.thanks === 'thanks' ? null : [what-to-put],
I want it to have just the normal component not a personalized one,, thank you :D

**Comment by JanPeter** [comment]
@jaycee425 You can do it programmatically with the following code:

```
static navigationOptions = ({ navigation }) => ({
  header: (navigation.state.params.thanks) => <HeaderView content={navigation.state.params.thanks} /> : null,
})
```

And then you can set the state params with this:

```
componentWillMount() {
  this.props.navigation.setParams({ thanks: "Something" });
}
```

Although I haven't tried the code myself and I'm not sure if something like the HeaderView is accessible for the public api in react-navigation and if there is a content property on that. But I think in an abstract way, this is how you set it programmatically.

**Comment by puelocesar** [comment]
I want to hide the navigation bar when showing my searchBar, so I do the following:

    if (navigation.state.params && navigation.state.params.showSearch) {
        return {
            header: null,
        }
    }

This works fine on iOS, but on Android, I get a blank header above my UI. Any ideas?

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!

**Comment by thebylito** [comment]
static navigationOptions = { header: null };

this works for me, "react-navigation": "^2.0.4"

**Comment by brentvatne** [comment]
https://reactnavigation.org/docs/en/navigation-options-resolution.html for more info
