### ISSUE TITLE
needs and consistent api

### ISSUE THREAD

**Issue by pvinis** [react-community/react-navigation#1535]
i dont want to write to many things for an intro here, but in general, this library is inconsistent, but i care enough to actually try to improve it. and hopefully we can use this issue to plan this, and mold this library to a much much better one.

in #905 i wrote about some problems and inconsistencies that this library has, so i would propose to start making a collection of things that this library can do (public api), what in needs in order to do them (internal structure), and then see whats here, whats missing, what can be done and how, what cant be done and why.

# public api (things that a user of this library should be able to do)
- [ ] define all screens that we can navigate to, by mapping a name to a component
- [ ] push a new screen by name, (`navigate('Bla')` or `navigate.bla()` takes you to `Bla` screen) 
- [ ] pop to any screen in the stack by name, (`goBack()` goes one back, `goBack('Bla')` takes you back to `Bla` screen).
- [ ] way to see the whole stack of screens (at least their name and index), and the current name and index (could be included in the list of the whole stack)

# internal structure
- [ ] we need an index and a name for each screen.

if people here are agreeing, we can gather some more stuff, i can add many more in the list, stuff that are happening now and not, and everyone else can comment and we discuss, so after a while, we can have a nice complete list of things. i can also go through many issues and see what other things we could add here and see if we can combine things, or accept or reject. better than just ignoring them. and after we have a nice list, we can start refactoring etc.

shall we?

**Comment by yinghuaheal** [comment]
I want a clear route map. 
... I think the maintainers want to build a powerful library then they neglect the basic needs. I don't know if I am the only one who feels like that...

**Comment by pvinis** [comment]
that's exactly why I made this but I didn't see any people joining.. like I said it's the best worst navigation lib, and I wish it becomes the best.

**Comment by yinghuaheal** [comment]
Looks like a beautiful one but the worst to use ever

**Comment by sospedra** [comment]
@spencercarli can we close this one in favour of #2585 ?

**Comment by kelset** [comment]
@sospedra yeah, doing it now.
