### ISSUE TITLE
On tab change, refresh current view

### ISSUE THREAD

**Issue by bardic** [react-community/react-navigation#1536]
Hey all,
Without using redux how I can refresh the current view on tab change?  Is there a way for me to call a function on the current view?

**Comment by xavier-villelegier** [comment]
Hey

Are you using the `TabNavigator` ? I have the same issue, the tab doesn't refresh itself until I touch it.
As a quick fix you can specify the props `animationEnabled: true` for the `TabNavigator`, it worked for me. Does anyone have a "real" solution ?

**Comment by neilhamilton** [comment]
There are a few solutions in this thread. I believe the future idea is to implement event listeners for tab changes (blur, focus etc.): https://github.com/react-community/react-navigation/issues/51

**Comment by bardic** [comment]
Thanks @neilhamilton for the heads up. Now it's a waiting game.

**Comment by chenvd** [comment]
@xavier-villelegier  I have the same issue

**Comment by xavier-villelegier** [comment]
@chenvd If your view contains a list, try to set `removeClippedSubviews: false` in your `SectionList` or `FlatList`, it worked for me (but i couldn't explain why, the `removeClippedSubviews` props is not very documented).
