### ISSUE TITLE
[Docs]: Redux Integration on Web

### ISSUE THREAD

**Issue by joncursi** [react-community/react-navigation#1537]
I can't find any documentation on how to use Redux to hold navigation state for a web app using `react-navigation`. Can someone help me figure out how to integrate Redux into [`BrowserAppContainer`](https://github.com/react-community/react-navigation/blob/master/website/src/BrowserAppContainer.js)?

**Comment by srounce** [comment]
Pass redux store's `dispatch`, and the navigation state from your store to the navigator.

**Comment by joncursi** [comment]
@srounce thanks for your reply. Could you provide a little bit more detail on which lines ought to change within [`BrowserAppContainer`](https://github.com/react-community/react-navigation/blob/master/website/src/BrowserAppContainer.js)? Is there any additional configuration that needs to be done outside of this file as well?

**Comment by srounce** [comment]
```
const navState = store.getState().navigation
addNavigationHelpers({
    state: navState.routes[navState.index],
    dispatch: store.dispatch
})
```

**Comment by kelset** [comment]
Closing this in favor of #782
