### ISSUE TITLE
Open DrawerNavigator content with "hamburger" icon

### ISSUE THREAD

**Issue by davidrojo** [react-community/react-navigation#1539]
Hi, I've been a while trying to success with this but I can't find the solution. What I want is basically to show the "hamburger" icon at the top of the header to open the DrawerNavigator menu.

I have a DrawerNavigator which contains 2 options, each of them is loading a StackNavigator component.

I've managed to show the icon and get the onPress event fired, but I don't know how to fire from the onPress event the function to open the navigator (`navigation.navigate('DrawerOpen')`)

```
const SchedulesStack = StackNavigator({
  Schedules: {
    screen: SchedulesScreen,
    navigationOptions: {
      title: 'Schedules`,  // Title to appear in status bar
      headerLeft: <Icon name="menu" size={35} onPress={ () => /** Here should be the magic **/ } />
    }
  }
});

const Homestack = StackNavigator({
  Home: {
    Screen: Home
    navigationOptions: {
      title: 'Home',  // Title to appear in status bar
      headerLeft: <Icon name="menu" size={35} onPress={ () => /** Here should be the magic **/ } />
    }
  }
});

const Root = DrawerNavigator({
  Home: {
    screen: HomeStack,
    navigationOptions: {
      title: 'Home' // Text shown in left menu
    }
  },
  Schedules: {
    screen: SchedulesStack,
    navigationOptions: {
      title: 'Schedules',  // Text shown in left menu
    }
  }
  }
})
```

| software         | version
| ---------------- | -------
| react-navigation |  ^1.0.0-beta.9
| react-native     |  0.44.0
| node             | 6.10.1
| npm or yarn      | 6.10.1 / 0.23.4

Thank you

**Comment by davidrojo** [comment]
Ok, I've found the solution and I respond to myself, what I had to do is to convert the whole navigationOptions key into a function with the navigation as an argument, then I was able to access the naigation property to open the drawer.

```
const SchedulesStack = StackNavigator({
  Schedules: {
    screen: SchedulesScreen,
    navigationOptions: ({ navigation }) => ({
      title: 'Schedules',  // Title to appear in status bar
      headerLeft: <Icon name="menu" size={35} onPress={ () => navigation.navigate('DrawerOpen') } />
    })
  }
});

const Homestack = StackNavigator({
  Home: {
    Screen: Home
    navigationOptions: ({ navigation }) => ({
      title: 'Home',  // Title to appear in status bar
      headerLeft: <Icon name="menu" size={35} onPress={ () => navigation.navigate('DrawerOpen') } />
    })
  }
});

const Root = DrawerNavigator({
  Home: {
    screen: HomeStack,
    navigationOptions: {
      title: 'Home' // Text shown in left menu
    }
  },
  Schedules: {
    screen: SchedulesStack,
    navigationOptions: {
      title: 'Schedules',  // Text shown in left menu
    }
  }
  }
})
```

**Comment by slorber** [comment]
thanks @davidrojo your example was helpful

**Comment by prateekpandey246** [comment]
Guys, there is a typo in the above code. I used it and spent an hour to just debug the issue and finally found a typo. I don't want someone else to waste their time. So, the correct code is:
`const SchedulesStack = StackNavigator({
  Schedules: {
    screen: SchedulesScreen,
    navigationOptions: ({ navigation }) => ({
      title: 'Schedules',  // Title to appear in status bar
      headerLeft: <Icon name="menu" size={35} onPress={ () => navigation.navigate('DrawerOpen') } />
    })
  }
});

const Homestack = StackNavigator({
  Home: {
    screen: Home
    navigationOptions: ({ navigation }) => ({
      title: 'Home',  // Title to appear in status bar
      headerLeft: <Icon name="menu" size={35} onPress={ () => navigation.navigate('DrawerOpen') } />
    })
  }
});

const Root = DrawerNavigator({
  Home: {
    screen: HomeStack,
    navigationOptions: {
      title: 'Home' // Text shown in left menu
    }
  },
  Schedules: {
    screen: SchedulesStack,
    navigationOptions: {
      title: 'Schedules',  // Text shown in left menu
    }
  }
  }
})`

**Comment by RohanGada** [comment]
This is no longer working, can someone please help?
I have tried defining navigationOptions like a function like mentioned above.

my package.json carries the following versions of libraries :
    "react": "16.0.0",
    "react-native": "0.51.0",
    "react-navigation": "^1.0.0-beta.22"

**Comment by jiggylepcha** [comment]
What if someone has to navigate to another screen from the stack navigator, how should I do that?

**Comment by brentvatne** [comment]
@jiggylepcha - you might have better luck asking the question on one of the suggested places here https://reactnavigation.org/en/help.html

**Comment by kirillplatonov** [comment]
Updated code which works with new version of react-navigation:
```
const SchedulesStack = StackNavigator({
  Schedules: {
    screen: SchedulesScreen,
    navigationOptions: ({ navigation }) => ({
      title: 'Schedules',  // Title to appear in status bar
      headerLeft: <Icon name="menu" size={35} onPress={ () => navigation.toggleDrawer() } />
    })
  }
});

const Homestack = StackNavigator({
  Home: {
    screen: Home
    navigationOptions: ({ navigation }) => ({
      title: 'Home',  // Title to appear in status bar
      headerLeft: <Icon name="menu" size={35} onPress={ () => navigation.toggleDrawer() } />
    })
  }
});

const Root = DrawerNavigator({
  Home: {
    screen: HomeStack,
    navigationOptions: {
      title: 'Home' // Text shown in left menu
    }
  },
  Schedules: {
    screen: SchedulesStack,
    navigationOptions: {
      title: 'Schedules',  // Text shown in left menu
    }
  }
  }
})
```
