### ISSUE TITLE
Call class method in header button

### ISSUE THREAD

**Issue by neuberoliveira** [react-community/react-navigation#154]
I have this class with a right button in the header

```
export default class NewSpotScreen extends Component {
	static navigationOptions = {
		header: (navigation, defaultHeader) => ({
			...defaultHeader,
			right: <Button title="OK" onPress={()=>{
				
			}} />,
		}),
	}
        .
        .
        .
```

something im confusing is if theres a way to call a method from my class `NewSpotScreen`. Basically the method i want to call will do the following things:

1. validation in a form
2. submit the data to the server
3. reset the form data
4. change to a success screen

I already have all of this working, but dont know how to call this method in `right` button click, because the `navigationOptions` is `static` `this` dont work, so is possible to do that?

thanks.

**Comment by noung1234** [comment]
Component {
	static navigationOptions = {
		header: (navigation, defaultHeader) => ({
			...defaultHeader,
			right: <Button title="OK" onPress={()=>{
				
			}} />,
		}),

**Comment by neuberoliveira** [comment]
@noung1234 sorry, but what exactly you change? or something goes wrong when formating/paste?

**Comment by despreston** [comment]
Related #145

**Comment by grabbou** [comment]
Closing as it's a duplicate. In fact, I think it's not a duplicate but we have another issue (newer) regarding the same fact that got more comments.

#210
