### ISSUE TITLE
Clicking TabBarTop entry while the text input trey is open closes the trey but does not navigate

### ISSUE THREAD

**Issue by thebigredgeek** [react-community/react-navigation#1543]
### Current Behavior
If I am in the process of entering text on iOS, and I click a different tab with `TabBarTop`, it does not navigate to the new tab and instead simply closes the text trey (the text area that slides up from the bottom on iOS with a keyboard etc).

### Expected Behavior
When I am entering text on iOS, and I click a different tab with `TabBarTop`, it should close the text entry trey / ios keyboard AND navigate to the new tab.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.9
| expo     |  16.0.0
| node             | 6.9.5
| npm or yarn      | yarn (0.16.1)

**Comment by thebigredgeek** [comment]
Might be related to https://github.com/react-community/react-navigation/issues/1339

**Comment by koenpunt** [comment]
This should probably be configurable, maybe just like a scrollview?

https://facebook.github.io/react-native/docs/scrollview.html#keyboardshouldpersisttaps

**Comment by Kerumen** [comment]
Related issue in the appropriate repo: https://github.com/react-native-community/react-native-tab-view/issues/339

**Comment by kelset** [comment]
Good news, this should be fixed in ` v0.0.70` of `react-native-tab-view` (thanks @Kerumen for the link) so it will be most likely be fixed for `beta.16`

**Comment by kelset** [comment]
@thebigredgeek we released new versions which use the aforementioned version of `react-native-tab-view`; can you try upgrading and closing this issue if it got fixed?

(if no answer I'll close in 7 days)

**Comment by kelset** [comment]
Hi there @thebigredgeek ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.
