### ISSUE TITLE
Drawer item icon style vs Guidelines

### ISSUE THREAD

**Issue by Andreyco** [react-community/react-navigation#1544]
Default appearance (provided by this lib) for drawer item icon includes icon opacity.

According to guidelines, there is no opacity specified.
https://material.io/guidelines/patterns/navigation-drawer.html#

Icon can have tint color for active state, but should not have opacity set for inactive/default state. Currently, this behaviour disallows us to fine tune icon appearance.

Despite creating very own `DrawerItems` (with styles under control) solves this problem, I don't consider it the best solution here.

**Improvements requested**  
- Remove opacity from style
- additionally accept `iconStyle` for wrapping `View` component

If you are open to PR, I will gladly provide one.

| software         | version
| ---------------- | -------
| react-navigation |  beta 9

**Comment by sonaye** [comment]
+1, why not submit a pr? I think this would get merged easily, it's a very minor detail.

**Comment by basudz365** [comment]
@Andreyco 
Any movement on this?  I'm also in need of either styling the icon or having the opacity removed.  

I'm not quite sure why there are underlying styles that aren't customizable through props without having to create a custom DrawerItem component.

**Comment by sonaye** [comment]
The quixkest workaround would be to implenet a custome drawer label

```javascript
const DrawerLabel = ({ label, icon }) => (
  <View style={{
    alignItems: 'center',
    flexDirection: 'row',
    height: 40,
    paddingLeft: 10,
    width: '100%'
  }}>
    <View style={{ alignItems: 'center', marginRight: 20, width: 40 }}>
      <Image resizeMode="contain" source={icon} style={{ height: 40, width: 40 }} />
    </View>
    <View style={{ flex: 1 }}>
      <Text>{label}</Text>
    </View>
  </View>
);

// ..

navigationOptions: {
  drawerLabel: (
    <DrawerLabel
      label="Label"
      icon={require('./icon.png')}
    />
  )
}
```

**Comment by kelset** [comment]
Good news for y'all, a lot of customization for the Drawer components will be present in `beta.16`; you can already test some by pointing at master.

**Comment by kelset** [comment]
Ping @Andreyco, we released the new versions which enable a lot of drawer customization, please check the docs & release notes.
And if now what you needed is available please close this issue.

**Comment by kelset** [comment]
Since no answer, I'll close because, again, we have added those features.
