### ISSUE TITLE
NavigationOptions how to monitor the state of redux and update it in real time

### ISSUE THREAD

**Issue by LCJ-MinYa** [react-community/react-navigation#1546]
![qq 20170517104650](https://cloud.githubusercontent.com/assets/19972696/26136922/72498fa4-3af1-11e7-88ad-53f7187c803d.png)

When set the navigationOptions, the component doesn't have the componentDidMount to get this

| software         | version
| ---------------- | -------
| react-navigation |  0.9
| react-native     |  0.44
| node             | 6.10.0
| npm or yarn      |3.10.10

**Comment by koenpunt** [comment]
`navigationOptions` is static and `componentDidMount` is an instance method, so `_this` in the `tabBarIcon` will always be undefined.

But to get the cart prop to the tabbar you can use the `setParams` method.

Something like this;
```js
componenDidMount() {
  this.props.navigation.setParams({ cart: this.props.cart });
}
// ...
static navigationOptions = ({ navigation }) => ({
  tabBarIcon: () => <Text>{navigation.state.params.cart</Text>
});
```

NB. Next time please put the actual code (with correct formatting) in the issue instead of a screenshot.

**Comment by LCJ-MinYa** [comment]
Thank you for your answer.
It works on the current page, But I have one other question. If I want to click on the ProductTab page, And then change the state of the carttab on the tabbar, What should I do?
like this
tabbat => 1.ProductTab 2.CartTab(cart state) 3.orderTab 4.MineTab

**Comment by ztplz** [comment]
You can use screenProps and screenProps base on redux.

**Comment by diegorodriguesvieira** [comment]
@LCJ-MinYa any solution for this?

**Comment by dturton** [comment]
what was the final solution here?

**Comment by aliustaoglu** [comment]
navigation.setParams in componentDidMount is good to begin with, but is not enough. You'll only get update once. Therefore add `componentDidUpdate` to update it:

```javascript
componenDidMount() {
  this.props.navigation.setParams({ cart: this.props.cart });
}
componentDidUpdate(prevProps) {
  if (prevProps.cart != this.props.cart) {
    this.props.navigation.setParams({ cart: this.props.cart });
  }
}
```
