### ISSUE TITLE
Passing props from parent DrawerNavigator to child StackNavigator

### ISSUE THREAD

**Issue by eshwartm** [react-community/react-navigation#1550]
Similar issues (I think)
https://github.com/react-community/react-navigation/issues/80
https://github.com/react-community/react-navigation/issues/1237
https://github.com/react-community/react-navigation/issues/169
https://github.com/react-community/react-navigation/issues/42

### Current Behavior

So my setup is like this 
`StackNavigator -> DrawerNavigator -> StackNavigator`

I am passing props from (parent) `DrawerNavigator` to its (child) `StackNavigator`
`navigation.navigate('DrawerClose', { name: 'Lucy' })`

### Expected Behavior

Not sure if I am doing this right. 

I want DrawerNavigator to close when I tap something on it and load the change in the StackNavigator with the new `headerTitle` accessing `navigation.state.params.name`. 

Instead, `navigation.state.params` is null/undefined in the child StackNavigator.

Also I have listed what I think are related issues on top.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^1.0.0-beta.9
| react-native     |  0.44.0
| node             | v7.2.0
| npm or yarn | 3.10.9

**Comment by dabit1** [comment]
Setting `initialRouteParams` fix the issue

**Comment by efkan** [comment]
I guess this issue also similar with yours - https://github.com/react-community/react-navigation/issues/1706

**Comment by Bundas** [comment]
@dabit1 Doesn't work for me...

Drawer -> Stack

**Comment by kelset** [comment]
Closing this in favor of #1706 to reduce redundancy.

**Comment by 337240552** [comment]
wrap stacknavigator as a component, then use 'screenProps' to pass args`const GuildStack = StackNavigator({
    Guild: {
        screen: CreateGuildScence
    }
});
//这么封装一层是为了传参，DrawerNavigator传参到StackNavigator 无法完成，必须通过screenProps 完成
export default class CreateGuildStack extends Component{

    render(){
        let {params} = this.props.navigation.state
        console.log("CreateGuildStack param:" + JSON.stringify(params))
        return <GuildStack screenProps={{params}} />
    }
}`
