### ISSUE TITLE
I'm passing state from 1st to 2nd page using navigate(2nd, {...}).  I've updated the state on 1st page. Problem: it didn't show correctly on 2nd page.

### ISSUE THREAD

**Issue by philipyoungg** [react-community/react-navigation#1552]
### Current Behavior
```javascript
const routes = {
  Book: {
    screen: BookScreen
  },
  Payment: {
    screen: PaymentScreen
  }
};

const config = {
  navigationOptions: {
    headerStyle: {
      backgroundColor: global.color.primary
    },
    headerTintColor: "white",
    headerBackTitle: null,
    headerTitleStyle: {
      fontSize: 12
    }
  }
};

export default StackNavigator(routes, config);
```

passing state from Book Screen to Payment Screen is not stateful.

For example: on Book screen—I have: 
- `this.state.price = 1`
- `this.setPrice = x => this.setState({price: x})`

I passed the props to 
```javascript
navigate('Payment', {
  price: this.state.price,
  setPrice: this.setPrice
})
```

On payment page, I have
- `Button` that binds to `this.props.navigation.state.params.setPrice` on payment page, and also 
- `Text` that shows the `this.props.navigation.state.params.price`

I've clicked to button and it successfully updated the Book page `price state`. The problem is, the `price` number on Payment page did not updated accordingly. It's like `navigate params` copy the object instead of giving reference.

My question: 
1. Why it's not stateful?
2. How could I solve this issue without Redux? (Cannot use it on current project)

Currently I hacked it with `setParams({ price: value })`, but didn't like this.

### Expected Behavior
`Text` on Payment page automatically updated from `price` changes.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.9
| react-native     |  0.43.4
| node             | 6.9.1
| npm or yarn      | 0.21.3

**Comment by saeropark** [comment]
Hi similar to my issue but I think i know what you are referring to #1364 

I am assuming book screen has a button to press to pass it to payment screen?

if so,

i suggest u place price and set price in an object, and pass over as an object
`
navigate('payment', {priceobject})`

and on payment, you read it as 

`const {params} = this.props.navigation.state;`
....
`{params.priceobject.price} `to display price
`{params.priceobject.setprice}` your new price

not sure if this is what you want

**Comment by philipyoungg** [comment]
@saeropark thank you for helping me with the issue, but that's not what I meant. I have price as Book screen state, and also setPrice (setState({price}) to update the price in Book screen. 

I've successfully shows the price with this.props.navigation.state.params. 

The setPrice button is also working, I can change the price from Payment page. 

The problem is, changing the price didn't trigger re-render price on Payment page. 

If I go back to Book page, and went back to Payment page, then it'll updated accordingly.

**Comment by philipyoungg** [comment]
Solved here: https://github.com/react-community/react-navigation/issues/1585. Closing

**Comment by Ashutosh21Nigam** [comment]
Madarchod kaisi language banayi hai.
