### ISSUE TITLE
goBack Design is very stupid！！！！！

### ISSUE THREAD

**Issue by dongodngtang** [react-community/react-navigation#1556]
goBack({key:key}) not working ====https://github.com/react-community/react-navigation/issues/1481 

_goback(){
const {goBack} = this.props.navigation
setTimeout(function(){ goBack() }, 500)
goBack()
}

onPress={ () => this._goback() }

**Comment by pietrasiak** [comment]
I've heard that adding more `!  !  !` in issue topic might possibly make it work again ;)
