### ISSUE TITLE
Reset stack on tab press

### ISSUE THREAD

**Issue by itswaze** [react-community/react-navigation#1557]
I know there are some workarounds here but I can't get them to work.
So, when I navigate on the Stock stack I want to be able to press the tab bar to get to the initial Stock screen. This is my code:

```
export const StockStack = StackNavigator({
  Stock: {
    screen: Stock,
  },
  Resultados: {
    screen: Resultados,
  },
  Ficha: {
    screen: Ficha,
  },
  Marcas: {
    screen: Marcas,
  },
  Galeria: {
    screen: Galeria,
  }
});

export const VerMaisStack = StackNavigator({
  VerMais: {
    screen: VerMais,
  },
  Financiamento: {
    screen: Financiamento,
  }
});

export const Tabs = TabNavigator({
  Empresa: {
    screen: Empresa,
  },
  Stock: {
    screen: StockStack,
  },
  Contactos: {
    screen: Contactos,
  },
  VerMais: {
    screen: VerMaisStack,
  }
}, {
  initialRouteName: 'Stock',
  tabBarComponent: TabBarBottom,
  tabBarPosition: 'bottom',
  tabBarOptions: {
    inactiveTintColor: '#474747',
    activeTintColor: 'white',
    style: {
      backgroundColor: '#1f1f1f',
    },
  },
});
```

**Comment by diegorodriguesvieira** [comment]
@itswaze try use this code
https://github.com/react-community/react-navigation/issues/314#issuecomment-289103332

**Comment by itswaze** [comment]
@diegorodriguesvieira hmm I tried that before and it didn't work, now I got it working, thanks! Do you know how to disable the animation? I see you opened an issue with that question, but hopefully you found a solution!

**Comment by diegorodriguesvieira** [comment]
I have not found any workaround yet, but this is a problem in the core of the framework, maybe in the future we will have this problem solved.
My solution for now was instead of resetting I simply navigate to the page I want without header...

**Comment by itswaze** [comment]
isn't that bad for performance or something? Since somehow you are increasing stack instead of resetting it?

**Comment by diegorodriguesvieira** [comment]
I believe that yes, but I am not saving the navigation stack and my app is super small...

**Comment by smitthakkar1** [comment]
@diegorodriguesvieira I am facing the same problem and tried the solution you suggested but getting an error " Element type is invalid: expected a string or class/function but got: undefiened" and it says "check the render method of tabBarComponent. 

did you guys face this issue before ?

**Comment by kelset** [comment]
Hi all - reset is currently a method that has some issues, we are looking to better control the behaviour of it in future releases.

In the meantime, I'll close this in favor of #1127. It has a long discussion and code snippets related to reset (in particular from [this comment](https://github.com/react-community/react-navigation/issues/1127#issuecomment-319727619) on) which should help to better understand how it works / how you may have to fix your method call.

**Comment by hodgef** [comment]
In all honesty, `reset()` is a pain, even on version 3x.
Here's how I finally managed to get tab reset working:

```
createBottomTabNavigator({
  HomeTab: {
    screen: HomeStack,
    navigationOptions: {
      title: "Home",
      tabBarOnPress: this.handleTabPress
    }
  },
  MessagingTab: {
    screen: MessagingStack,
    navigationOptions: {
      title: "Messaging",
      tabBarOnPress: this.handleTabPress
    }
  }
});

handleTabPress = ({ navigation }) => {
  navigation.popToTop();
  global.navigate(navigation, navigation.state.routeName);
}
```

**Comment by netbull** [comment]
I guess it's the same as

```js
handleTabPress = ({ navigation, defaultHandler }) => {
  navigation.popToTop();
  defaultHandler();
};
```

**Comment by neiker** [comment]
If there's two levels of navigation, `popToTop` only resets one. My hack to that:

```js
tabBarOnPress: ({ navigation, defaultHandler }) => {
      const firstLevelState = navigation.state;

      if (firstLevelState.index !== 0) {
        navigation.popToTop({ immediate: true });

        const secondLevelState = firstLevelState.routes[firstLevelState.index];
        if (secondLevelState.index !== 0) {
          navigation.popToTop({ immediate: true });
        }
      }


      defaultHandler();
    },
```

**Comment by Beissner** [comment]
@hodgef Thank you for your solution! Do you know if there's any way to remove the animation of `popToTop`?

**Comment by hodgef** [comment]
@Beissner, no I haven't yet. If you do come across a fix for that do let me know!

**Comment by abhinav-official** [comment]
resetOnBlur - Reset the state of any nested navigators when switching away from a screen. Defaults to false.

EG:

`import {
  createAppContainer,
 } from "react-navigation";
import React from "react";
import { createMaterialBottomTabNavigator } from "react-navigation-material-bottom-tabs";
import { createStackNavigator } from "react-navigation-stack";


export default createAppContainer(
  createMaterialBottomTabNavigator(
    {
      Home: createStackNavigator(
        {
          Home: { screen: home },
          SearchScreen: { screen: searchScreen }
        },
      ),
      Nearby: createStackNavigator(
        {
          Nearby: { screen: nearbyRestorants },
          Details: { screen: restaurantDetails }
        },
      ),
      Profile: createStackNavigator(
        {
          Profile: { screen: profle },
          Orders: { screen: orders },
        },
    {
      initialRouteName: "Home",
      barStyle: { backgroundColor: "#fff" },
      resetOnBlur: true
    }
  )
);
`

thank me later

**Comment by augsteyer** [comment]
I've seen some glitchy behaviors when unmounting on blur and with using reset. Pop to top is also kinda not working depending on how the stack is created.

I am writing this because there are some solutions to use "listeners" on Screens, but they are not fired if a customized Tab solution is used. So for anyone using a customized TabBar solution like me, e.g. ```<Navigator tabBar={props => <BottomTabBar {...props} />}>```

```JavaScript
export const BottomTabBar = ({ navigation, state })> {
    return <BottomNavigation
        selectedIndex={state.index}
        onSelect={
            index => navigation.dispatch((state) => {
                const routeStack = state.routes?.[index].state?.routes
                // select the first screen in the history stack if it exists
                const screen = routeStack && routeStack.length > 1
                    ? routeStack[0].name
                    : state.routeNames[index]
                return CommonActions.navigate(state.routeNames[index], { screen })
            })
        }
     <BottomNavigationTab icon={() => <GenericIcon name='home' size={20} />} />
      ....
```
You will not need this complicated logic if the names of your Tabs are the same as the first screen inside them, e.g. 
```JavaScript
<Tab.Screen name="Home">
    <Stack.Navigator>
       <Stack.Screen name="Home">
```
The logic you will need will just be `navigation.navigate('Home', {screen: 'Home'})` or for the case above `navigation.navigate(state.routeNames[index], { screen: state.routeNames[index] })`.

If you are not using a customized solution I mentioned above. This will also work while using a listener directly on a screen components:
```JavaScript
<Tab.Screen name="Home" component={Home}
          listeners={({ navigation }) => ({
            tabPress: (e) => {
              e.preventDefault();
              navigation.navigate("Home", { screen: "Home" };
            }
          })}
        />
```
The "screen" param is the important part here. It bypasses the history. This is mentioned many times in the docs for regular navigation, I just did not think that it could also work on Tab navigation.

**Comment by satya164** [comment]
> but they are not fired if a customized Tab solution is used.

You need to emit those events in your tab bar as shown in this example: https://reactnavigation.org/docs/bottom-tab-navigator#tabbar

**Comment by dominictobias** [comment]
Reset worked fine for me tbh

```ts
listeners={() => ({
  tabPress: (e) => {
    e.preventDefault()
    navigation.reset({
      index: 0,
      routes: [{ name: 'MainScreens', params: { screen: 'News' } }],
    })
  },
})}
```
