### ISSUE TITLE
Undefined is not an object(evaluation ''_AppNavigator/.AppNavigator.router")

### ISSUE THREAD

**Issue by anuj-dhanju** [react-community/react-navigation#1558]
I am following the redux-example. 
https://github.com/react-community/react-navigation/tree/master/examples/ReduxExample

Full detail and code is here:- http://stackoverflow.com/questions/44023043/undefined-is-not-an-objectevaluation-appnavigator-appnavigator-router

**Comment by anuj-dhanju** [comment]
I got the issue, Issue was related to something redux store recreation.
Thank you :)

**Comment by challme28** [comment]
what was the issue? I'm having the exact problem

**Comment by neildevas** [comment]
@anuj-dhanju what was the issue? Im having this same problem
