### ISSUE TITLE
[Docs]: Screen Tracking Integration on Web

### ISSUE THREAD

**Issue by joncursi** [react-community/react-navigation#1559]
Similar to https://github.com/react-community/react-navigation/issues/1537 - I'm struggling to find documentation / guides / help on how to integrate GA screen tracking on a web app that uses `react-navigation`.

**Comment by matthamil** [comment]
The web integration guides are very lacking right now: https://reactnavigation.org/docs/guides/web. If you have a specific question, you are welcome to ask specifics about issues you are having in the issue itself.

**Comment by kelset** [comment]
Closing this in favor of #782
