### ISSUE TITLE
Nested drawer overlaps inside TabNavigator

### ISSUE THREAD

**Issue by xght** [react-community/react-navigation#1561]
Hi,

### Current Behavior
With the minimal code:
```
const Left = () => <View></View>;

// I agree that it seems strange to nest a DrawerNavigator inside a TabNavigaor
const Right = DrawerNavigator({
    home: {
        screen: () => <View></View>,
    }
})

const App = TabNavigator({
    left: {
        screen: Left,
    },
    right: {
        screen: Right,
    }
});
```
I get this when the drawer from the right tab is closed:
![screen shot 2017-05-17 at 17 19 51](https://cloud.githubusercontent.com/assets/16802551/26161995/c98b3c3e-3b25-11e7-9e39-a8d6a862fc6e.png)

Is this the expected behavior ?

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  ^1.0.0-beta.9
| react-native     |  0.44.0

**Comment by zackify** [comment]
This same thing happens to me. It's not weird. I actually have a tab navigator with four screens. Each one is a StackNavigator. Inside one of the stack navs, is a drawer nav. When I load up the app, the screen to the left of the drawer nav is shown on the page.

**Comment by zackify** [comment]
Seems that using it on the right side works correctly. But I would love to have it on the left :/

**Comment by xght** [comment]
To me it's clearly a bug (maybe not the most urgent). 
Do you know how to label it since the issues are a bit out of control ?

**Comment by kelset** [comment]
Pinging OP @xght since this issue is quite old and related to an old version of the lib. If no answer I'll close in 7 days.

(that said, it may be related to #1305... is it?)

**Comment by xght** [comment]
@kelset 
It is fixed, awesome ! 
(I tested 1.0.0-beta.15)
