### ISSUE TITLE
"#" on hover at blog example: On-the-path-to-v1

### ISSUE THREAD

**Issue by talkingtab** [react-community/react-navigation#1562]
In the webpage at https://reactnavigation.org/blog/2017/4/On-the-path-to-v1, if you hover over the title: "On the path ..." a "#" appears at the end so it shows

On the path to React Navigation v1 #

I'm looking at whether I can use react-navigator in a web app instead of react-router

**Comment by matthamil** [comment]
I don't think this is a bug. This is to show you that you can get the link for that specific section of a blog post.

To answer your other question, you can integrate React Navigation with a web app, but the documentation is not quite there yet: https://reactnavigation.org/docs/guides/web.
