### ISSUE TITLE
how can invoke preScreen callback function when app go back preScreen？

### ISSUE THREAD

**Issue by theMonkeyMan** [react-community/react-navigation#1563]
# code:
import { StackNavigator } from 'react-navigation';

import * as containers from '../containers';

const SimpleApp = StackNavigator({
    Home: { screen: containers.AppManagerContainer },
    Second:{screen:containers.SecondContainer}
});

export default SimpleApp;

question:
    when i use StackNavigator.i throught of a question,when i invoke navigate() transition to Second Screen,and then click back go to PreScreen(Home).at now,i found PreScreen Component can't invoke lifecycle hooks.i know it is because this component stay in the route stack.
    but if i want to change the app theme for every Screen,and i change it in the Second Screen,if can't invoke(trigger) lifecycle hooks or other listener,the PreScreen(Home) can't update to new theme,when the app go back to PreScreen(Home).
    official doc provide router listener 'onNavigationStateChange',but it just provide 'preState' and 'currentState',still can't solve this problem.
   i suggest provide some hooks,just like react lifecycle hooks,it's can be invoke when the router change to route stack Screen.

**Comment by spencercarli** [comment]
I'm going to close this since it's been quiet for a while and I think it would be a better fit on StackOverflow with the react-navigation tag.
