### ISSUE TITLE
[Redux] Change header background/title color based on the store

### ISSUE THREAD

**Issue by jbrodriguez** [react-community/react-navigation#1565]
### Current Behavior
Currently, the static navigatorOptions' headerRight prop allows you to pass a React.Component that you can wrap with connect, so you get access to the redux store.

But headerStyle/headerTitleStyle can't be modified dynamically, since in navigatorOptions you don't have access to the redux store nor you can reference the underlying (Header/HeaderTitle) component to wrap it around connect (nor you would want to access it this way I guess).

### Expected Behavior
I'm looking for a way to style the header (background color, title color) dynamically based on redux store state.

- Use case:
A theme based app where the user chooses a dark/light, so the header needs to change dynamically.

Any suggestions on how to do this ?

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.9
| react-native     |  0.44.0
| node             | 6.9.1
| npm or yarn      | 0.24.5

**Comment by matthamil** [comment]
Wrap the component that is setting the navigationOptions with `connect`, then set your navigationOptions to be a function that returns the nav options like so:

```js

class MyComponent extends React.Component {
  static navigationOptions = ({ navigation, screenProps }) => ({
    title: 'My screen',
    headerTintColor: screenProps.storeKey.value,
  });

  render() {
    return <View><Text>Hello world</Text></View>
  }
}

export default connect(mapStateToProps, mapDispatchToProps)(MyComponent);
```

**Comment by jbrodriguez** [comment]
Thanks for the reply @matthamil !

So you mean that 

```javascript
const mapStateToProps = state => ({
  screenProps: state,
})
```
would work ?

**Comment by matthamil** [comment]
The `screenProps` param in `navigationOptions` is a reference to the props of the component itself.

If your `mapStateToProps` looked like this:

`const mapStateToProps = state => ({ title: state.title });`

your navigationOptions would look like this:

```js
static navigationOptions = ({ screenProps }) => ({
  title: screenProps.title
});
```

**Comment by AlanFoster** [comment]
As an alternative; I've been using the following pattern of letting redux manage all state.

For instance, to configure the HeaderBackButton:

```
import { connect } from 'react-redux';
import { HeaderBackButton } from 'react-navigation';

const mapStateToProps = function (state) {
  return {
    // Props you care about
  };
};

export default connect(mapStateToProps, mapDispatchToProps)(HeaderBackButton);
```

And passing your new redux-aware component via:

```
import NewBackButton from '...';

const NavigationStack = StackNavigator({
  Foo: {
    screen: FooScreen,
    navigationOptions: {
      title: 'Example',
      headerLeft: <NewBackButton />,
    }
  },
```

**Comment by jbrodriguez** [comment]
> The screenProps param in navigationOptions is a reference to the props of the component itself (like you are accessing this.props).
> 
> If your mapStateToProps looked like this:
> 
> const mapStateToProps = state => ({ title: state.title });
> 
> your navigationOptions would look like this:
> 
> static navigationOptions = ({ screenProps }) => ({
>   title: screenProps.title
> });

I double checked this, but couldn't get it to work.

Do you have a working example ?

**Comment by matthamil** [comment]
@jbrodriguez can you post your full code?

**Comment by jbrodriguez** [comment]
> As an alternative; I've been using the following pattern of letting redux manage all state.

Yes, that works. But it doesn't if you want to use store state to style header components that can't be wrapped by connect.

**Comment by jbrodriguez** [comment]
> @jbrodriguez can you post your full code?

Sure, I'll clean up and post it

**Comment by jbrodriguez** [comment]
Here it goes

https://github.com/jbrodriguez/NavTest

The issue is that the console.logs come up empty

```
screenProps-{}
screenProps.theme-undefined
```

**Comment by dabit1** [comment]
Hi @matthamil I think you are wrong. `screenProps` is not a reference to props like `this.props`. It is a reference to screenProps defined in `StackNavigator`. I have the same problem like @jbrodriguez, I need to set the title from redux and I don't know how. Any body know how can I access to screen props??

**Comment by koenpunt** [comment]
The pattern without redux would be something like this:

```js
const MyNav = StackNavigator({
  // ...
}, {
  navigationOptions: ({ screenProps }) => ({
    headerStyle: screenProps.headerStyle,
  }),
});

<MyNav screenProps={{ headerStyle: { backgroundColor: '#f00' }}} />
```

So to use it with redux you wrap `MyNav` with `connect` and map your state to a `screenProps` property.

Other solution would be wrapping the `Header` component itself with connect:

```js
import { Header } from 'react-navigation';

const ConnectedHeader = connect(mapStateToProps)(Header);

const MyNav = StackNavigator({
  // ...
}, {
  navigationOptions: ({ screenProps }) => ({
    header: ConnectedHeader,
  }),
});

**Comment by matthamil** [comment]
Apologies for that. Should have tested locally before answering ;)

**Comment by ttdat89** [comment]
Or you can implement like this https://github.com/react-community/react-navigation/issues/1575#issuecomment-302755881

**Comment by dabit1** [comment]
I think the solutions you mentioned with redux rerender all screens unnecessarily, I'm right?

**Comment by ttdat89** [comment]
@dabit1 That what i did to implement theming feature and multi language. Could you tell me another way?

**Comment by jbrodriguez** [comment]
> Or you can implement like this #1575 (comment)

Thank you @ttdat89 ! That worked 👍

**Comment by jbrodriguez** [comment]
@koenpunt I also tried your solution and it almost worked with beta10, which now accepts a style prop (https://github.com/react-community/react-navigation/commit/ff99d6ec0a2d7a62adfd8d1e6a3c906fcedf294a), but I still can't set other header properties (headerTintColor for example).

The benefit of this solution is that it allows a common Header across screens, yet some elements can be overridden at screen level (headerRight, headerLeft, etc).

I tried the following, but screenProps isn't seen by the wrapped Header component.

```
import React from 'react'
import PropTypes from 'prop-types'

import { connect } from 'react-redux'
import { Header } from 'react-navigation'

const NavBar = props => {
	console.log(`props.theme-(${props.theme})`)
        // props.theme is correctly populated so i can set backgroundColor based on theme
        // yellow is just a test
        // headerTintColor though is not accessible within Header
	return <Header {...props} style={{ backgroundColor: 'yellow' }} screenProps={{ headerTintColor: 'red' }} />
}
NavBar.propTypes = {
	theme: PropTypes.string.isRequired,
}

const mapStateToProps = state => ({
	theme: state.settings.theme,
})

export default connect(mapStateToProps)(NavBar)
```

Maybe make ```<Header />``` accept a navOptions prop (same structure as navigationOptions), that can be merged with navigationOptions ?

```diff
  _renderTitleComponent = (props: SceneProps) => {
-    const details = this.props.getScreenDetails(props.scene);
+   const details = Object.assign({}, this.props.navOptions, this.props.getScreenDetails(props.scene).options);

    const headerTitle = details.options.headerTitle;
...
```

Any suggestions ?

**Comment by koenpunt** [comment]
You can just intercept the `getScreenDetails` in your own header component:

```js
import { Header } from 'react-navigation';

const mapStateToProps = (state, ownProps) => ({
  getScreenDetails: (scene) => {
    const details = ownProps.getScreenDetails(scene);
    return {
      ...details,
      options: {
        headerTitleStyle: { color: '#f00' },
        ...details.options,
      }
  },  
});

const ConnectedHeader = connect(mapStateToProps)(Header);

const MyNav = StackNavigator({
  // ...
}, {
  navigationOptions: ({ screenProps }) => ({
    header: (props) => <ConnectedHeader {...props} />,
  }),
});
```

**Comment by jbrodriguez** [comment]
Thanks @koenpunt, this works beautifully !

This helps simplify the custom header so that it doesn't need the style prop passed in.

```
import React from 'react'

import { connect } from 'react-redux'
import { Header } from 'react-navigation'

const NavBar = props => <Header {...props} />

const mapStateToProps = (state, ownProps) => ({
  getScreenDetails: (scene) => {
    const details = ownProps.getScreenDetails(scene);
    return {
      ...details,
      options: {
        headerStyle: { backgroundColor: 'yellow' },
        headerTitleStyle: { color: '#f00' },
        ...details.options,
      }
  },  
});

export default connect(mapStateToProps)(NavBar)
```

**Comment by tnanhpt** [comment]
Im try solution but it not working in version 3.11.1 :(
