### ISSUE TITLE
addComponentAsRefTo(...): Only a ReactOwner can have refs.

### ISSUE THREAD

**Issue by Amurmurmur** [react-community/react-navigation#1568]
### Current Behavior

When using with react-native-code-push for some weird reasons this gets thrown:
```
addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).

Object.addComponentAsRefTo
    ReactOwner.js:84:6
attachRef
    ReactRef.js:71:15
Object.ReactRef.attachRefs
    ReactRef.js:93:4
ReactCompositeComponentWrapper.attachRefs
    ReactReconciler.js:24:11
CallbackQueue.notifyAll
    CallbackQueue.js:75:21
ReactNativeReconcileTransaction.close
    ReactNativeReconcileTransaction.js:36:25
ReactNativeReconcileTransaction.closeAll
    Transaction.js:221:24
ReactNativeReconcileTransaction.perform
    Transaction.js:163:15
batchedMountComponentIntoNode
    ReactNativeMount.js:72:14

```
Here is my app.js
```
import { Tabs } from '@lib/router.js'

import {
  Provider,
  connect
} from 'react-redux';
import configureStore from '@lib/configureStore'

import codePush from "react-native-code-push";
import React, { Component } from 'react';

class app extends Component {
  
  componentDidMount() {
    if (!__DEV__)
      codePush.sync({
        updateDialog: true,
        installMode: codePush.InstallMode.ON_NEXT_RESUME
      });
  }

  render() {
    const store = configureStore(getInitialState());
    store.dispatch(setStore(store))

    return (
      <Provider store={store}>
        <Tabs />
      </Provider>
    );
  }
}
  app = codePush({ checkFrequency: codePush.CheckFrequency.MANUAL })(app);

  export default app;
```
Here is a screenshot:
![simulator screen shot 17 may 2017 23 57 55](https://cloud.githubusercontent.com/assets/8608333/26175843/b9335fb0-3b5c-11e7-85de-2634099c9d8a.png)

However if I comment out this line in my app.js before `export default app;`
```
app = codePush({ checkFrequency: codePush.CheckFrequency.MANUAL })(app);

```
It loads just fine.
The exact same code used to work fine with `react-native-router-flux`

### Expected Behavior

It should just sync with code-push and promt if any update is found on `componentDidMount`:
```
componentDidMount() {
    if (!__DEV__)
      codePush.sync({
        updateDialog: true,
        installMode: codePush.InstallMode.ON_NEXT_RESUME
      });
  }
```
### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.9
| react-native     |  v0.44.0
| node             | v7.10.0
| npm or yarn      | yarn 0.24.5

**Comment by koenpunt** [comment]
Haven't used code push, so can't help you with that. But, I'm really curious why you dispatch `setStore(store)` on the store itself, because that seems like a code smell to me

**Comment by Amurmurmur** [comment]
@koenpunt Thank you very much for your suggestion!
Alright figured it out, the problem was with react-native-router-flux package, just uninstalled it completely, everything is fine now.
Thank you everyone for your attention! 👍
