### ISSUE TITLE
Custom Header Left Navigation

### ISSUE THREAD

**Issue by andkhong** [react-community/react-navigation#1570]
I want to customize the left navigation to go to a specific component (ie Home Component). How might I do that? Below is what I currently have.

    headerLeft: (<Button title="Left" onPress={() => navigate("Home")} />)

**Comment by TBouder** [comment]
`
YourScreen:
	{
		screen: YourScreen,
		navigationOptions: ({navigation}) => ({
			title: 'Blablabla',
			params: navigation.state.params,
			headerLeft: (
				<TouchableHighlight
					onPress={() =>
					{
						navigation.navigate('NewScreen', {params})
					}}
					underlayColor={'#444444'}
					style={style.yourStyle}}>
					<Image source={yourImageForExample} />
				</TouchableHighlight>
			)
		})
	}`

Hope it's helping :)
