### ISSUE TITLE
Opacity reveals components with negative zIndex on back-swipe

### ISSUE THREAD

**Issue by andrewnaeve** [react-community/react-navigation#1571]
when navigating backwards by swiping a screen from left to right on iOS, the screen that is being navigated back to is opaque, which is usually a neat effect. However, I have a Loading component that is not in the StackNavigator that is positioned behind it with a negative zIndex. As a result, the StackNavigator going Opaque reveals the Loading component underneath as well. 

I can probably just create another intermediate solid component, but just wanted to point out this use case.

**Comment by spencercarli** [comment]
Going to close this since there hasn't been any discussion and it seems that it's a relatively isolated case.
