### ISSUE TITLE
the TabNavigator maybe has some problem with  react-native-swiper

### ISSUE THREAD

**Issue by StarOfLife** [react-community/react-navigation#1572]
Hi,I think maybe  it is a bug about TabNavigator and react-native-swiper.
next is the picture
![Uploading Screenshot00.png…]()
![Uploading Screenshot01.png…]()
this is the page code 
```js
import React,{ Component} from 'react';
import {View,Image,StyleSheet,ScrollView,Dimensions} from 'react-native';
import Swiper from 'react-native-swiper';
const screen={
    width: Dimensions.get('window').width,
    height: Dimensions.get('window').height
}
export default class IndexView extends Component{
    render(){
        return (
            <View style={styles.container}>
                <ScrollView style={styles.scrollwrap}>
                    <Swiper style={styles.wrapper} autoplay={true} autoplayTimeout={4} height={screen.width/2} paginationStyle={{bottom:5}} dotColor={'rgba(255,255,255,0.8)'} activeDotColor={'rgba(234,56,62,0.8)'}>
                         <Image source={require('../imgs/banner/banner01.jpg')} style={styles.slider} />
                         <Image source={require('../imgs/banner/banner01.jpg')} style={styles.slider} />
                    </Swiper>
                </ScrollView>
            </View>
        )
    }
}

const styles=StyleSheet.create({
    container:{
        flex:1,
    },
    scrollwrap:{
        backgroundColor:'#f3f3f3',
    },
    wrapper:{
    },
    slider:{
        backgroundColor:'#97cae5',
        width:screen.width,
        height:screen.width/2,
    },
}) 
```
### Current Behavior
when I use the TabNavigator ,in the first screen,the swiper has someting wrong,the images did not show,but in the second screen, it is right.
### Expected Behavior
the swiper's Image should be displayed correctly.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.9
| react-native     |  0.44
| node             | v7.60
| npm or yarn      |

**Comment by StarOfLife** [comment]
![screenshot00](https://cloud.githubusercontent.com/assets/10042282/26191301/eed526e8-3bdf-11e7-8411-dbfce4a25e96.png)
![screenshot01](https://cloud.githubusercontent.com/assets/10042282/26191306/f4dd487c-3bdf-11e7-9a1b-d565a63e8589.png)

**Comment by ZhouYongfan** [comment]
yep, I met the same problem, the view with swiper just like your first picture

**Comment by brenoxp** [comment]
This worked for me:

```javascript
constructor(props) {
   super(props);
   this.state = {
      visibleSwiper: false
   };
}

componentDidMount() {
   setTimeout(() => {
      this.setState({
        visibleSwiper: true
      });
   }, 100);
}

render() {
   let swiper = null;
   if (this.state.visibleSwiper) {
      swiper = <Swiper dotColor={'white'} 
         activeDotColor={'#FF0A0A'} 
         height={250} horizontal={true} 
         loop={false} bounces={true} 
         removeClippedSubviews={false}
      >
         <View style={styles.slide1}>
            <Image resizeMode='cover' style={styles.image} source={require('../img/1.jpg')} />
         </View>
         <View style={styles.slide1}>
            <Image resizeMode='cover' style={styles.image} source={require('../img/2.jpg')} />
         </View>
      </Swiper>;
   } else {
      swiper = <View></View>;
   }

   return (
      ...
      {swiper}
      ...
   );
}
```

Don't forget to set all parent components of, 
```javascript 
<Swiper>
``` 
with 
```javascript
removeClippedSubviews={false}
```
I don't know exactly which one needs this config but for securance I've set all of them, hope it helps.

**Comment by StarOfLife** [comment]
@brenoxp thank you,setTimeout is useful

**Comment by gusgard** [comment]
What works for me was to set the `height` and wrap the `Swiper` in a `View` with `position absolute`, and also add `removeClippedSubviews={false}`

```
import { Dimensions } from 'react-native';
const { height } = Dimensions.get('window');


<View style={{ position: 'absolute' }}>
        <Swiper
          height={height}
          removeClippedSubviews={false}
        >
        ...
...
```

Hope it helps.

**Comment by StarOfLife** [comment]
@gusgard ,thank you,but it in TabNavigator is not show

**Comment by gusgard** [comment]
@StarOfLife Are you using the last version beta.11? Becuase it works for me with TabNavigator.

**Comment by StarOfLife** [comment]
@gusgard yes，I update to the latest version beta.11,but it still can't work

**Comment by woshicezai** [comment]
@brenoxp thankyou man！this is work for me.

**Comment by fddi** [comment]
@brenoxp thanks! this is useful to me

**Comment by gracepham** [comment]
@brenoxp Thanks! I passed this problem.

**Comment by qwlong** [comment]
@StarOfLife did you solve it ? i try setTimeout and it no use for me

**Comment by StarOfLife** [comment]
@qwlong setTimeout有用的

**Comment by sunkibaek** [comment]
You can try to render `Swiper` after the enclosing `View` is rendered if you do not like to use `setTimeout`. For example,

```
      <Container
        onLayout={this.renderSwiper}
        style={{ height: swiperSize, width: swiperSize }}
      >
        {this.state.isSwiperVisible ? (
          <Swiper height={swiperSize} width={swiperSize}>
            {this.renderImages(images)}
          </Swiper>
        ) : (
          <ActivityIndicator />
        )}
        ...
```
and `renderSwiper` simply turns `isSwiperVisible` true.
