### ISSUE TITLE
IOS: Jump over a screen

### ISSUE THREAD

**Issue by TBouder** [react-community/react-navigation#1573]
Hi everyone !
I currently have a bug with my React-Navigation.
Here is the concerned code:

## The stack Navigator
```javascript
const	Flow = StackNavigator(
{
	Mapping:
	{
		screen: Mapping,
		navigationOptions: ({navigation}) => ({title: navigation.state.params.title})
	},
	ActivityList:
	{
		screen: ActivityList,
		navigationOptions: ({navigation}) => ({title: navigation.state.params.title})
	},
	ActivityPrelude:
	{
		screen: ActivityPrelude,
		navigationOptions: ({navigation}) => ({
			title: 'Préparation de l\'activité',
			params: navigation.state.params,
			headerLeft: (
				<TouchableHighlight
					onPress={() =>
					{
						navigation.dispatch(
							NavigationActions.reset({
								index: 0,
								actions: [NavigationActions.navigate({routeName: 'Mapping', params: 'Science'})]
							})
						);
					}}
					underlayColor={getMainColor().Secondary}>
					<Image source={myImage} style={{height: 34, width: 34}} />
				</TouchableHighlight>
			)
		})
	},
}
```

The Mapping Screen is a selector. We select a category and we navigate to ActivityList, where we can find X activities related to this category. The title params is used for the title of the navbar, but also to get the data from the local DB
```javacript
navigate = (category) =>
{
	setCategory(category);
	this.props.navigation.navigate('ActivityList', {title: category});
}
```

In this screen, we can select on activity -> We will reach ActivityPrelude which gives us some details about it. Before that, we set Category (a general Const) to the current category, and Activity to the current Category. 

```javascript
onPress={() =>
{
	setActivity(data.name)
	this.props.navigation.navigate('ActivityPrelude', {title: data});
}}
```

Then, we reach the ActiviyPrelude screen with this as componentWillMount.
```javascript
componentWillMount = () =>
{
	let		data = null;

	data = getActivities(getCategory())[getActivity()];
	data.Name = getCategory();
	this.setState({data});
}
```

Here,
getActivities(getCategory()) -> returns an array with all the Activities of a specific Category
getActivity() -> returns the name of the current Activity
so, getActivities(getCategory())[getActivity()] -> returns the details of the current Activity.

At the beginning, theses data were sent through the navigation params, but because of the bug I'm going to present you, I moved to this solution.

### Current Behavior

https://i.giphy.com/3oKIPcOTxhZbD6CGUU.gif

Here is the flow that leads to a crash (not every time):

> mapping -> CategoryX -> ActivityX -> goBack() -> CategoryY -> ActivityY -> goBack() -> CategoryZ

And the error is on the category screen (ActivityList) but the debugger tell me this:

> Cannot set property 'Name' of undefined
> Prelude._this.componentWillMount
> Prelude.js:72:2

And the line 72:2 matches with `data.Name = getCategory();`, because here, data is null.
But that's 'normal' because the navigator jumps from Mapping to Activity, without passing by `ActivityList (with setActivity(data.name))`.   
setCategory is called when moving from the Mapping screen to the ActivityList screen, so when we press a category, setCategory is set to the new one. But the navigator jump over the ActivityList Screen to directly reach ActivityPrelude. Because of that, setActivity still have the old value, that is not in the new category, leading the application to crash.

### Expected Behavior
The screen should not be skipped.
The bug can occurs on the first 'try' or at the tenth. For now, I have not experienced it on android

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.9
| react-native     |  0.44.0
| node             | v7.4.0
| npm or yarn      | npm 4.6.1

Thank you !

**Comment by kelset** [comment]
Pinging OP @TBouder since this issue is quite old and related to an old version of the lib. If no answer I'll close in 7 days.

**Comment by kelset** [comment]
Hi there @TBouder ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.
