### ISSUE TITLE
HOW TO: setParam to update tabBar label

### ISSUE THREAD

**Issue by MacKentoch** [react-community/react-navigation#1575]
# Objective: update tabBar Labels dynamically

I use `this.props.navigation.setParams` but I find no clear example on how it will update the tabBar labels (*I found examples but from 1 to another I feel even more lost on how to succeed...*).

## my environment:
| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.9
| react-native     |  0.43.3
| node             | v6.9.1
| yarn      | 0.22.0

**Comment by ztplz** [comment]
I used to use setParams to update my app header,  but it doesn't wok .  So I find anthor way to solve this problem.    Here is my solution.

Class ThemeChange extends Component {
  static navigationOptions = ({ navigation, screenProps }) => ({
        ....
       style: {
          backgroundColor:  screenProps.themeColor
      }
       .....
  })
}

in StackNavigator 
    const mapStateToProps = state => {
      return {
         screenProps:  state.GlobalState.screenProps 
      }
}

export default connect(mapStateToDispatch, mapDispatchToProps)(StackNavigator name)


action => redux => screenProps =>  update my app header

it is work for me.

**Comment by ttdat89** [comment]
@ztplz I think you should connect screenProps like this instead connect whole Navigator to redux
In component that contains your Navigator

<AppNavigator
      screenProps={this.props.settings}
      navigation={addNavigationHelpers({
      dispatch: this.props.dispatch,
      state: this.props.navigationState
    })}/>

and 

export default connect(state => ({
  navigationState: state.navigationState,
  settings: state.settings,
}), dispatch => ({
  dispatch: dispatch
}))(YourComponent)

**Comment by MacKentoch** [comment]
Thank you @ztplz and @ttdat89 

I did not plan to connect to redux anything from navigator.

But right now you clearly emphasis there no other working way: so be it.

**Comment by augustoabreu** [comment]
Have you tried something like this?

```
static navigationOptions: ({ navigation }) => {
      tabBarLabel: navigation.state.params.tabLabel,
})
```

**Comment by MacKentoch** [comment]
__I succeeded 👍  in using `setParams` for a `tabNavigator` and without connecting to redux store.
*But there are constraints (in my use case).*__

*In my case I want to update tabBarLabels depending language.*

>Constraints in my use-case: setParams will apply to all tabs only if `lazy: false`.


### TabBarNavigator
```javascript
export const TabBarNavigator = TabNavigator(
  // routeConfig:
  {
    mandatory: {
      screen: MandatoryForm
    },
    optional: {
      screen: OptionalForm
    }
  },
  // tabNavigatorConfig
  {
    lazy: false // IMPORTANT: if lazy: true -> setParam will only appply to selected tab (since only this one is rendered)
```

### MandatoryForm tab (*same as OptionalForm tab*)
```javascript
class MandatoryForm extends PureComponent {
  static navigationOptions = ({ navigation }) => {
    // test params since will be undefined until componentDidMount:
    const tabBarLabel = navigation.state.params && navigation.state.params.tabBarLabel
      ? navigation.state.params.tabBarLabel
      : '';

    return {
      tabBarLabel
    };
  };

  componentDidMount() {
    this.translateTabBarLabels();
  }

  /**
   * update tabBar labels translation
   *
   */
  translateTabBarLabels = () => {
    const {
      language,
      navigation: { setParams }
    } = this.props;

    // update dynamically tabBarLabel dynamically
    setParams({
      tabBarLabel: translate('MANDATORY_FIELDS', language)
    });
  }

```

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!

**Comment by est7** [comment]
@MacKentoch  if i want to set 'lazy ：false',can i  use CustomTabBar to achieve it?
