### ISSUE TITLE
DrawerLockMode not working

### ISSUE THREAD

**Issue by mikhi** [react-community/react-navigation#1578]
Hi,
Great package so far.

I'm using DrawerNavigator nested with TabNavigator. What i'm trying to achieve, is to hide the drawer view on swipe.
I have searched and i found that i can use drawerLockMode, but this option is not working.

drawerLockMode is merged on the master branch?

in "src/Navigators/DrawerNavigator.js" and "src/Views/Drawer/DrawerView.js" there is no reference about this feature.

| software         | version
| ---------------- | -------
| react-navigation |  ^1.0.0-beta.9
| react-native     |  0.43

Best regards,
Mihai

**Comment by spencercarli** [comment]
Could you please provide a small sample app (preferably via [Snack](https://snack.expo.io)) that shows what you're trying to do? I'm going to close this for now but we can re-open if a sample is provided. Thanks!
