### ISSUE TITLE
Option to specify a screen to open as a modal within a stack navigator?

### ISSUE THREAD

**Issue by gregblass** [react-community/react-navigation#1579]
I've got a standard stack navigator and I wanted to be able to have certain screens open up as a modal (slide up from the bottom of the screen). I'm using iOS for now. As far as I know, this isn't possible yet, correct?

For instance, on the first screen of my app, I have an about button on the top left of the header, which would open up a screen with copyright info, the company logo, etc. Stuff about the app. That design pattern would make more sense as a modal...not sliding from the right like the rest of the stack. I can get around this case by using a separate stacknavigator for the first screen and setting that to modal, then using another stacknavigator for the rest of the normal left-right navigation.

Where I'm stuck is when the user navigates once or twice into a stack navigator - you may want to have a filter screen that slides up as a modal (see the attached image). You'd only want that particular screen to be a modal...everything else would be a normal slide left/right.

![modal-stack](https://cloud.githubusercontent.com/assets/279927/26204918/472066f0-3bae-11e7-81cb-db155ed20957.png)

It looks like there is some discussion around this and even a PR from someone, but I wanted to check and see if anyone is prioritizing this or if it might be coming soon in future releases? Hate to be that guy to cry "This is a common use case!", but...yeah.

Or, can anyone offer any insight on a workaround on how I could implement a modal screen from within a stacknavigator? Much thanks in advance.

**Comment by gregblass** [comment]
Looks like you guys are all aware of this. Thanks for all your hard work! https://github.com/react-community/react-navigation/issues/723#issuecomment-293753699

**Comment by gregblass** [comment]
The suggested workaround doesn't seem to work - it just navigates to the home screen and ignores all navigation options.

**Comment by gregblass** [comment]
This works perfectly:
https://github.com/react-community/react-navigation/issues/707#issuecomment-299859578 

If anyone is looking for a solution to this, use that pattern - just start with a modal stack navigator and nest your card stack within it.

**Comment by jorgegorka** [comment]
I'm using another approach to solve this problem. Sending a param inside the navigator like this:

`navigation.navigate("MyModalScreen", { modalVisible: true })`

then in the modal screen I just need to check if the param is present:

```
constructor(props) {
    super();
    let modalVisible = false;
    if (props.navigation && props.navigation.state && props.navigation.state.params ) {
      modalVisible = props.navigation.state.params.modalVisible;
    }

    this.state = {
      modalVisible: modalVisible,
    };
  }
```

**Comment by otaviogaiao** [comment]
@jorgegorka seems interesting. Any comment on performance? Or have you found another way?

**Comment by jorgegorka** [comment]
@otaviogaiao I'm using that approach so far.  I don't see why there should be any performance issues.

**Comment by Bobozee** [comment]
Nesting a FlatList inside a Modal does not work properly. The FlatList does not scroll at all.

**Comment by YousefAlsbaihi** [comment]
this might be late answer but for future reference you can do the following 

```
import { StackNavigator } from 'react-navigation';

    import { MainScreen, ModalScreen } from '../screens/';

    export default Root = StackNavigator({
      Main: { screen: MainScreen },
      Modal: { screen: ModalScreen }
    })
```

and navigate with same way using 

```
buttonPressed() {
      this.props.navigation.navigate("Modal")
    }
  
```
