### ISSUE TITLE
Passing param while the Header Back Button is pressed

### ISSUE THREAD

**Issue by mthuret** [react-community/react-navigation#1580]
### Current Behavior
Hello, 

We are using the `StackNavigator` in an application that basically needs to forward to each screen a `state`. It's working fine when navigating from A to B or from B to A if using: 

```
navigate('Filters', {
                  state: ...,
                })}
```

However, if the back button is used (the one that is put automatically inside the header), then there's no way to specify this `state`. 

We try using the `setParams` function first like:

```
this.props.navigation.setParams({ state })
```

But then when the back button is used, the param `state` is not set. 

What is the best way to handle this use case? 

Thanks in advance!

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.9
| react-native     |  0.42

**Comment by gregblass** [comment]
Wondering this myself. Looks like you're trying to open a filter screen? And pass params back and go back down the stack to close it?

This would definitely be a dealbreaker if so.

I'm trying to figure out if I should use a separate <Modal> component within one screen if this is the case.

**Comment by mthuret** [comment]
@gregblass => yes, this is our use case. Right now we switched to `react-native-router-flux` as we didn't have that much time to investigate what we were doing wrong if so.

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
