### ISSUE TITLE
mode: modal throws off centering of screen for react-native-maps

### ISSUE THREAD

**Issue by acomito** [react-community/react-navigation#1581]
### Current Behavior
I'm not sure if this is a react-native-maps issue, or an expo issue, or a react-navigation issue. When navigating to a MapView (from expo, based on react-native-maps), I expect the map to be centered, but the centering is thrown off somehow by mode: modal. It works as expected when the mode is a default transition.
![img_0031](https://cloud.githubusercontent.com/assets/12701635/26206407/be3a797a-3bb2-11e7-8624-6aca6a0d2826.PNG)

### Expected Behavior
I expect a MapScreen to pop up like a modal. The array of markers should be centered in the screen. I suspect I can hack an offset fix or sorts via react-native-maps but wanted to mention it here, and see if anyone had a better solution for the time being.

![img_0030](https://cloud.githubusercontent.com/assets/12701635/26206419/c5ee94d0-3bb2-11e7-90f3-287de6ebe240.PNG)

| software         | version
| ---------------- | -------
| react-navigation |  "react-navigation": "git+https://github.com/react-community/react-navigation.git",
| react-native     |  "react-native": "https://github.com/expo/react-native/archive/sdk-16.0.0.tar.gz",
| node             | 
| npm or yarn      |

**Comment by skevy** [comment]
Hi there!

Any chance you can provide a repo with a repro case?

**Comment by acomito** [comment]
This is an example using expo:

[https://github.com/acomito/navigation-maps-example](https://github.com/acomito/navigation-maps-example)

It seems like it has something to do with `header: null` while also in `mode: modal`. If I leave the header it works or if I am not using modal it works-- but it wont work with header null and modal mode.

**Comment by acomito** [comment]
It seems like even if you keep the header, but were to make it transparent using the styles from the below issue, you will still seed the centering issue pop up:

`
headerStyle:{ 
position: 'absolute', 
backgroundColor: 'transparent', 
zIndex: 100, top: 0, left: 0, right: 0
 }`

https://github.com/react-community/react-navigation/issues/855

**Comment by kelset** [comment]
Pinging OP @acomito since this issue is quite old and related to an old version of the lib. If no answer I'll close in 7 days.

**Comment by kelset** [comment]
Hi there @acomito ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.
