### ISSUE TITLE
Tab icon animation on press

### ISSUE THREAD

**Issue by itswaze** [react-community/react-navigation#1583]
Is it possible to make an animation when clicking an icon on the tab bar?
Like Spotify has:

![Alt Text](https://thumbs.gfycat.com/SlightPaltryDutchsmoushond-size_restricted.gif)

**Comment by matthamil** [comment]
You can supply your own component to the tab bar to achieve this.

**Comment by itswaze** [comment]
@matthamil any example?

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
