### ISSUE TITLE
Specify stacknavigator headerMode per screen?

### ISSUE THREAD

**Issue by gregblass** [react-community/react-navigation#1587]
Is it possible to override the headerMode per screen? For instance, have the stack headerMode be 'float', but override that for only the first screen to use 'screen'?

**Comment by gregblass** [comment]
This should help explain it. The first animation is wonky as 'float' because the headers are different and the title is an image. Everything else in the stack is good using float. But the first screen should really be 'screen'.

![headermode](https://cloud.githubusercontent.com/assets/279927/26224613/1bec1bc6-3bf1-11e7-8c86-e1f60df65a44.gif)

**Comment by gregblass** [comment]
Its really just the image in the header. Maybe I could hook some callbacks to fade the image in and out?

**Comment by gregblass** [comment]
https://github.com/react-community/react-navigation/issues/335#issuecomment-282300545 - This solved my issue. I tried nesting navigators to get different headerModes, but was unable to figure out how to go back between one to the other. 

`navigation.navigate('TopicAreaFilter')`

This above code works great though!

I will say that now I'm using 3 different navigators so that I can use mode: 'modal' and headerMode: 'screen'. It'd be nice to be able to set both of those per screen one day!

**Comment by Elijen** [comment]
I feel like using another nested StackNavigator is an overkill. I am already using nested TabNavigator, DrawerNavigator and StackNavigator as a workaround for other missing functionality (e.g. disabling Drawer for a screen).
