### ISSUE TITLE
Adding navigationOptions throws "Cannot update during existing state transition"

### ISSUE THREAD

**Issue by shrutic** [react-community/react-navigation#1589]
### Current Behavior

    I added public static navigationOptions to React.Component as below
```
export class ItemPickerView
    extends React.Component<IItemPickerViewProps, IItemPickerViewState> {

    public static navigationOptions = ({ navigation }) => {
        return {
            header: (
                <View style={{height: 44}}/>
            ),
            headerLeft: (
               <Button title='test' onPress={navigation.navigate('ConfirmationView')}/>
            ),
            headerRight: (
                <Button title='testRight' onPress={navigation.navigate('ConfirmationView')}/>
            ),
            title: 'ItemPicker',
        };
    };
```

   Upon navigating from previous component to this component, I get the warning thrown on the screen "Cannot update during existing state transitions ( such as within render or other component constructor)...". 

The Xcode log 

> 
> Objects are not valid as a React child (found: object with keys {visible}). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons.
> 
> Check the render method of `View`.
> 2017-05-18 15:52:47.035 [fatal][tid:com.facebook.react.ExceptionsManagerQueue] Unhandled JS Exception: Objects are not valid as a React child (found: object with keys {visible}). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons.

My Navigator is a StackNavigator

```
export const RouteAwareNavigator = StackNavigator({
    TestView: {
        navigationOptions: {
            header: null,
        },
        screen: TestView,
    },
    ItemPickerView: {
        screen: ItemPickerView,
    },
});
```
I am using typescript and 0.43.3 react-native and  1.0.0.beta9 version of react-navigation

### Expected Behavior

I would expect the navigation options to be correct read in without throwing warnings when rendering the ItemPickerView when navigating from TestView -> ItemPickerView

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0.beta9
| react-native     |  0.43.3
| node             | 
| npm or yarn      |

**Comment by shrutic** [comment]
I am facing exact same issue with react-navigation version 1.0.0.beta11 and 0.43.3 react-native

**Comment by shrutic** [comment]
I still get the same error with 1.0.0.beta11

**Comment by shrutic** [comment]
![image](https://user-images.githubusercontent.com/4141641/27562424-556b1218-5a81-11e7-838a-255b521235f2.png)
Stack trace of the warning fired

**Comment by vishim** [comment]
+1 
Here is my stack trace
```
2017-06-28 23:12:20.716 [error][tid:com.facebook.React.JavaScript] Objects are not valid as a React child (found: object with keys {visible}). If you meant to render a collection of children, use an array instead.
    in View (created by CardStack)
    in RCTView (created by View)
    in View (created by AnimatedComponent)
    in AnimatedComponent (created by Card)
    in Card (created by Container)
    in Container (created by CardStack)
    in RCTView (created by View)
    in View (created by CardStack)
    in RCTView (created by View)
    in View (created by CardStack)
    in CardStack (created by Transitioner)
    in RCTView (created by View)
    in View (created by Transitioner)
    in Transitioner (created by CardStackTransitioner)
    in CardStackTransitioner (created by Unknown)
    in Unknown (created by Navigator)
    in Navigator (created by NavigationContainer)
    in NavigationContainer (created by Stack)
    in Stack (created by App)
    in StyleProvider (created by App)
    in Provider (created by App)
    in App
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
2017-06-28 23:12:20.727 [fatal][tid:com.facebook.react.ExceptionsManagerQueue] Unhandled JS Exception: Objects are not valid as a React child (found: object with keys {visible}). If you meant to render a collection of children, use an array instead.
    in View (created by CardStack)
    in RCTView (created by View)
    in View (created by AnimatedComponent)
    in AnimatedComponent (created by Card)
    in Card (created by Container)
    in Container (created by CardStack)
    in RCTView (created by View)
    in View (created by CardStack)
    in RCTView (created by View)
    in View (created by CardStack)
    in CardStack (created by Transitioner)
    in RCTView (created by View)
    in View (created by Transitioner)
    in Transitioner (created by CardStackTransitioner)
    in CardStackTransitioner (created by Unknown)
    in Unknown (created by Navigator)
    in Navigator (created by NavigationContainer)
    in NavigationContainer (created by Stack)
    in Stack (created by App)
    in StyleProvider (created by App)
    in Provider (created by App)
    in App
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
```

**Comment by shrutic** [comment]
Hey @vishim , I was able to resolve this by fixing the call inside onPress. Instead of specifying a lambda ( ie onPress = {() => {navigation.navigate('ConfirmationView')}} , I used onPress={navigation.navigate('ConfirmationView')} which was causing the navigation to the "ConfirmationView" to happen as soon as the header component was rendering. 

Hopefully this is the same issue that you are facing

**Comment by kelset** [comment]
Closing since OP @shrutic fixed her code 👌

**Comment by luthink** [comment]
@shrutic right
