### ISSUE TITLE
TabNavigator re-renders all tabs on switch

### ISSUE THREAD

**Issue by microwavesafe** [react-community/react-navigation#159]
Currently all of my tabs are re-rendered every time you switch a tab, one of the tabs will be displaying a graph so I don't want to re-render the graph every time you switch between two other tabs.

Can we implement a function in the library that prevents rendering the tab if it is not being viewed? Or would this be better as a condition passed to the screen through this.props.params?

**Comment by ericvicenti** [comment]
The internal `SceneView` is a pure component, which is meant to block extra rendering, but it sounds like it is not working

**Comment by microwavesafe** [comment]
It's good to know this isn't intended behaviour. Let me know if I can help you diagnose the problem.

**Comment by ericvicenti** [comment]
Please do! It is always good to have a few more eyes on the code

**Comment by nico1510** [comment]
Yes I noticed the same issue. The `SceneView` component [receives the navigation property as context](https://github.com/react-community/react-navigation/blob/aead8ff9fbd2aceb2d06c8049c8ad0d55d77b5ab/src/views/SceneView.js#L26) and this prop changes on every navigation action and causes all the tabs to re-render.

**Comment by EmielM** [comment]
Same issue here.

I think https://github.com/react-community/react-navigation/blob/9983ced4eea3c93fa3b26c8d9d71952fb4f5da7e/src/withCachedChildNavigation.js#L45 is the culprit, `_childNavigationProps` is cleared before it is checked if it should be re-used as cache.

Proposed fixes:
1) Change the line into `if (!this._childNavigationProps) this._childNavigationProps = {};`
2) Add some logic that clears out `routes` that aren't set anymore on the new `navigation`. Is that even a possible case?
