### ISSUE TITLE
Nesting StackNavigator and TabNavigator

### ISSUE THREAD

**Issue by prateekvarma** [react-community/react-navigation#1591]
Hello,
I trying to render StackNavigator inside TabNavigator. The Tabs are working fine, but i cannot link the button :(

In simple words, there's a button inside the "Feed" section of the TabNavigator "Tabs" . When clicked on the button, it should go to "UserDetails.js" via StackNavigator.
Please help!

Here is my index.android.js - 

```
export default class HackernoonNavigation extends Component {
  render() {
    return (  
      <Tabs />
    );
  }
}

export const Tabs = TabNavigator({
  Feed: {
    screen: Feed,
  },
  Me: {
    screen: Me,
  },
});
```

And here is the file "Feed.js" , inside which there is a button that leads to "UserDetail.js" -

```
export default class Feed extends Component {
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>
          Welcome to Feed!
        </Text>
         <Button
          onPress={() => this.props.navigation.navigate('Details')}
          title="User Details"
        />
      </View>
    );
  } 
}

export const FeedStack = StackNavigator({
  Details: { screen: UserDetail },
});
```

**Comment by mqstack** [comment]
Got the same problem.
Can't navigate to other screen from the screen in TabNavigator.
Is there any solution?

**Comment by prateekvarma** [comment]
@mqstack I haven't figured it out yet :( , there doesn't seem to be many tutorials on React Navigation, and the docs don't cover this particular case in nesting.

**Comment by eflath** [comment]
I only have experience hooking this stuff up through redux, but maybe try nested actions, as shown [here](https://reactnavigation.org/docs/navigators/navigation-actions#Navigate). so in your case the action you want to dispatch would be something like:
```
const navigateAction = NavigationActions.navigate({
  routeName: 'Feed',
  params: {},
  action: NavigationActions.navigate({ routeName: 'Details'})
});
```

**Comment by jtewright** [comment]
I think the solution is to have your tabs be StackNavigators:
```
const FeedStack = StackNavigator({
  Feed: {
    screen: Feed,
  },
  Details: {
    screen: UserDetail ,
  },

});
const Tabs = TabNavigator({
  Feed: {
    screen: FeedStack,
  },
  Me: {
    screen: MeStack, <not shown
  },
});

**Comment by dustturtle** [comment]
how to hide the tab in details screen though? that is a common case. Any help? @jtewright

**Comment by jtewright** [comment]
@dustturtle to do that you nest the TabNavigator within a StackNavigator as its root/base view. Then the detail page will go on top of the tab view.

**Comment by dekm** [comment]
I tried adding a StackNavigator to my TabNavigator and there is always the error that this must be a screen. Is there no way to nest stacks inside TabNavigator?

**Comment by dustturtle** [comment]
@dekm  There IS a way to do this.

**Comment by jtewright** [comment]
@dekm sounds like your StackNav isn't returning a screen? It should work as a StackNav on its own; that way the TabNav, which needs to be rendering a screen, renders the StackNav it actually just renders the screen the StackNav supplies.

**Comment by dekm** [comment]
@jtewright I ended up wrapping the TabNavigator inside a StackNavigator like below. Some of those screens will need stacks so I might have to find another solution as TabNavigator doesn't appear to accept Stacks for me.

`// HOME SCREEN STACK
const HomeStack = StackNavigator({
    Home: { screen: TabNavigator({
    ScreenOne: { screen: Home },
    ScreenTwo: { screen: Meds },
    ScreenThree: { screen: Health },
    ScreenFour: { screen: Reports },
    ScreenFour: { screen: Inbox }
    })
  },
});
`

**Comment by dustturtle** [comment]
@dekm You can nest stacks in a tab.

**Comment by jtewright** [comment]
@dekm looks correct to me, at least for the composition of the Stack with nested Tab; should work exactly the same for nesting Stack in a Tab nav. What's your error? And what are you returning from render()?

**Comment by kelset** [comment]
Pinging OP @prateekvarma since this issue is quite old and related to an old version of the lib. If no answer I'll close in 7 days.

Moreover, if you are looking for complex examples, we added a dedicated section to the README.

**Comment by prateekvarma** [comment]
Sorry for the late response, i decided to use something else.
Thanks all!

**Comment by sugia** [comment]
Guys, one solution is to build a RootNavigator on top of StackNavigator and TabNavigator. In this way pages in StackNavigator and TabNavigator can go to each other without a problem.

Reference: https://github.com/spencercarli/react-navigation-auth-flow/blob/finished-code/app/router.js

**Comment by dmitryt** [comment]
Hi, there. 
Guys, is it possible to remove `headerBackTitle` from all screens?
I tried to put it into `defaultNavigationOptions` of the RootScreen ,but looks like it works only, when you set it directly to parent Screen.
