### ISSUE TITLE
Defining tabBarComponent as TabView.TabBarBottom doesn't show tabs

### ISSUE THREAD

**Issue by eduplus** [react-community/react-navigation#1596]
### Current Behavior

tabBarComponent: TabView.TabBarBottom

in the TabNavigator config object doesn't show tabs at all. Without it they show fine on iOS as bottom, but Android has default as TabBarTop. This worked on beta-7 on another project.

### Expected Behavior

Seeing TabBarBottom tabs normally.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  beta9
| react-native     |  0.41.2

**Comment by koenpunt** [comment]
This was changed, since beta9 you can import TabBarBottom directly from react-navigation:

```js
Import { TabBarBottom } from 'react-navigation';

**Comment by eduplus** [comment]
Ok, it works with that, thanks. Then documentation is still outdated on this, which makes it hard to know how to use it.

**Comment by koenpunt** [comment]
I don't see `TabView.TabBarBottom` mentioned anywhere anymore? Or at least not on this page: https://reactnavigation.org/docs/navigators/tab#TabNavigatorConfig

**Comment by koenpunt** [comment]
For reference, this changed in beta.9, also pointed out in the release notes here: https://github.com/react-community/react-navigation/releases/tag/v1.0.0-beta.9

**Comment by eduplus** [comment]
Thanks, that explains it pretty well. We can close this.

**Comment by maotora** [comment]
I was looking for the same behaviour.

This solves it, Thanks!

**Comment by waltermvp** [comment]
So we would be using `TabviewTabBarBottom` instead of `TabView.TabBarBottom`? I keep getting invalid prop type
