### ISSUE TITLE
Warning: BackAndroid is deprecated.  Please use BackHandler instead.

### ISSUE THREAD

**Issue by Lizhooh** [react-community/react-navigation#1597]
Warning: BackAndroid is deprecated.  Please use BackHandler instead.

| software         | version
| ---------------- | -------
| react-navigation  |  1.00--beta.9
| react-native   |   0.44 
| node             |  7.10
| npm or yarn      | 4.12

**Comment by kelset** [comment]
This is not strictly an error related to the react-navigation, you just need to change the physical android handler to:

```
import { BackHandler } from 'react-native';

  // code

  componentDidMount() {
    BackHandler.addEventListener('backPress');
  }

  // some more code

  componentWillUnmount() {
    BackHandler.removeEventListener('backPress');
  }

```

**Comment by acomito** [comment]
@kelset would you put this in your top-level component? I'm not using BackHandler myself so it must be used somewhere in react-navigation? I just upgraded to 44 and see this now.

**Comment by chrischen-melb** [comment]
same here, after I started using StackNavigator...
also not sure where shall I apply @kelset 's solution, tried put it in navigation related component, warning stays

**Comment by kelset** [comment]
@acomito yes I've added those lines to the top-level component.

I am running the same React Native version (0.44) but I'm pointing react-navigation to `master`, maybe it's a fix not yet in a release?

**Comment by acomito** [comment]
@kelset I'm also using 44 (but via expo 17) and I believe I'm pointing to master. But I am still seeing the error.

I feel like this has to do something with react-navigation and maybe `navigation.goBack()` or BackAndroid being used somewhere in the library?


```
{
  "dependencies": {
    "antd-mobile": "^1.1.3",
    "apollo-client": "^1.1.1",
    "expo": "^17.0.0",
    "graphql-tag": "^2.0.0",
    "lodash": "^4.17.4",
    "meteor-apollo-accounts": "^2.0.1",
    "moment": "^2.18.1",
    "react": "16.0.0-alpha.6",
    "react-apollo": "^1.2.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-17.0.0.tar.gz",
    "react-native-aws3": "0.0.8",
    "react-native-elements": "^0.11.2",
    "react-navigation": "git+https://github.com/react-community/react-navigation.git",
    "react-redux": "^5.0.4",
    "redux": "^3.6.0",
    "redux-devtools-extension": "^2.13.0",
    "redux-form": "^6.6.3",
    "redux-persist": "^4.6.0",
    "redux-thunk": "^2.2.0",
    "sentry-expo": "^1.0.0",
    "uuid": "^3.0.1"
  },
}
```


```
// TOP LEVEL IMPORTS
import Expo from 'expo';
import React from 'react';
import AppRoutes from './routes';
import { BackHandler } from 'react-native';
// APOLLO
import { ApolloProvider } from 'react-apollo';
import client from './ApolloClient';
// REDUX
import { store } from './store'
// ANTD
import enUS from 'antd-mobile/lib/locale-provider/en_US';
import { LocaleProvider } from 'antd-mobile';
// OTHER
import Sentry from 'sentry-expo';
import { SENTRY_DSN } from './modules/config'



// INITIALIZE SENTRY ERROR LOGGING: https://sentry.io/
// ===================================================
Sentry.config(SENTRY_DSN).install();



  // code

  
// ROOT COMPONENT TO ENTIRE RN APP
// ===================================================
class App extends React.Component {
	componentDidMount() {
	    BackHandler.addEventListener('backPress');
	  }

	  // some more code

	  componentWillUnmount() {
	    BackHandler.removeEventListener('backPress');
  	}
	render() {
		return (
			<ApolloProvider store={store} client={client}>
				<LocaleProvider locale={enUS}>
					<AppRoutes />
				</LocaleProvider>
			</ApolloProvider>
		);
	}
}


// REGISTER ROOT COMPONENT WITH EXPO HELPER
// ===================================================
Expo.registerRootComponent(App);
```

**Comment by kelset** [comment]
Ok, apparently it will be fixed soon, they merged a fix: https://github.com/react-community/react-navigation/pull/1520

**Comment by zaro** [comment]
1.0.0-beta.10 fixes it for me.

**Comment by Lizhooh** [comment]
ok, good

**Comment by skevy** [comment]
Fixed in https://github.com/react-community/react-navigation/commit/9027e1a88f98810ade4a27839dc6f8b036aad4dd

**Comment by macs03** [comment]
I could fix it with this https://github.com/aksonov/react-native-router-flux/issues/1842#issuecomment-313804400

**Comment by ospfranco** [comment]
I'm now getting this issue after updating to react-native 0.58.3
