### ISSUE TITLE
How can I update second screen when user switch tab?

### ISSUE THREAD

**Issue by moschan** [react-community/react-navigation#1598]
I'm setting up TabNavigator and I put 2 screens.
In my situation, in the first screen, user save some data on local storage. The second screen shows the list of these data. In this case, where should I put `this.load()` function to load every time when user switch tab to second? I put some my example code.

```
class First extends Component {
  this.save() {
    // save some data to local storage
  }
  render () {
    return (
      <View><Button onPress={() => { this.save() }}>Save</Button></View>
    )
  }
}

class Second extends Component {
  this.load() {
    // load data from local storage and set these data to this.state
    // where should I run this to load data every time when user come to this tab?
  }
  render () {
    return (
      <View><Listview /></View>
    )
  }
}


export default TabNavigator({
  First: {
    screen: FirstScreen,
  },
  Second: {
    screen: SecondScreen,
  },
})

```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.9
| react-native     |  0.44.0
| node             | v5.2.0
| yarn      | 0.15.1

**Comment by acomito** [comment]
if not redux, than componentWIllMount/ComponentDidMount and/or componentWillUpdate

**Comment by moschan** [comment]
@acomito Thank you for your replying.
Actually, I tried using those function to get callback of switching tabs, but those function did not respond when I change tab. These worked when I open first tab page only.

So, is the redux system the only way to achieve this?

**Comment by jcaspian** [comment]
I am using redux to store the navigation state, and hook it up to the screen components with react-redux's connect & mapStateToProps. So whenever the navigation state changes, my screen components will be updated with the current navigation state, and do the appropriate comparison & reloading if necessary. 
More info here: https://reactnavigation.org/docs/guides/redux

As for another method, you can set onNavigationStateChange prop for the Navigator.
More info here: https://reactnavigation.org/docs/guides/screen-tracking

**Comment by moschan** [comment]
Thanks, @jcaspian 
Finally, I create my app with redux. Then, whenever I tap the each tab, every time `componentWillReceiveProps` is triggered.
So I can run reload function at that time.

Thank you so much for your support.

Let me close this issue.

thanks.

**Comment by pencilcheck** [comment]
I'm on "1.0.0-beta.9" but it doesn't call any callbacks when switching tabs for the active tab.

**Comment by fondoger** [comment]
You can do this without redux, using `navigation.addListener()`.

```
  componentDidMount() {
    this.props.navigation.addListener('willFocus', (playload)=>{
      console.log(playload);
    });
  }
```

[addlistener-subscribe-to-updates-to-navigation-lifecycle](https://reactnavigation.org/docs/navigation-prop.html#addlistener-subscribe-to-updates-to-navigation-lifecycle)
