### ISSUE TITLE
React caught an error thrown by NavigationContainer under jest test: Cannot read property 'then' of undefined

### ISSUE THREAD

**Issue by liushigit** [react-community/react-navigation#1599]
### Current Behavior
When performing a jest test (`npm test`) in a project using `TabNavigator`, an error was thrown.
[Sample Project](https://github.com/liushigit/ReactNavTestIssueDemo)

> ● Console
> 
>     console.error node_modules/react-native/Libraries/Core/ExceptionsManager.js:
> 71
>       Warning: View.propTypes has been deprecated and will be removed in a futur
> e version of ReactNative. Use ViewPropTypes instead.
>     console.error node_modules/react-native/Libraries/Core/ExceptionsManager.js:
> 71
>       Warning: BackAndroid is deprecated.  Please use BackHandler instead.
>     console.error node_modules/react-native/Libraries/Core/ExceptionsManager.js:
> 71
>       React caught an error thrown by NavigationContainer. You should fix this e
> rror in your code. Consider adding an error boundary to your tree to customize e
> rror handling behavior.
> 
>       TypeError: Cannot read property 'then' of undefined
> 
>       The error is located at:
>           in NavigationContainer (created by AwesomeProject)
>           in AwesomeProject
> 
>       The error was thrown at:
>           at NavigationContainer.componentDidMount (/Users/u/code/AwesomeProje
> ct/node_modules/react-navigation/src/createNavigationContainer.js:189:2171),
>           at commitLifeCycles (/Users/u/code/AwesomeProject/node_modules/react
> -test-renderer/lib/ReactFiberCommitWork.js:421:24),
>           at commitAllLifeCycles (/Users/u/code/AwesomeProject/node_modules/re
> act-test-renderer/lib/ReactFiberScheduler.js:349:9),
>           at invokeGuardedCallback (/Users/u/code/AwesomeProject/node_modules/
> react-test-renderer/lib/ReactErrorUtils.js:21:10),
>           at invokeGuardedCallback (/Users/u/code/AwesomeProject/node_modules/
> react-test-renderer/lib/ReactErrorUtils.js:91:34),
>           at commitAllWork (/Users/u/code/AwesomeProject/node_modules/react-te
> st-renderer/lib/ReactFiberScheduler.js:468:19),
>           at completeUnitOfWork (/Users/u/code/AwesomeProject/node_modules/rea
> ct-test-renderer/lib/ReactFiberScheduler.js:614:11),
>           at performUnitOfWork (/Users/u/code/AwesomeProject/node_modules/reac
> t-test-renderer/lib/ReactFiberScheduler.js:641:14),
>           at workLoop (/Users/u/code/AwesomeProject/node_modules/react-test-re
> nderer/lib/ReactFiberScheduler.js:763:26),
>           at invokeGuardedCallback (/Users/u/code/AwesomeProject/node_modules/
> react-test-renderer/lib/ReactErrorUtils.js:21:10)

### Expected Behavior
There should be no error.

###  Environment
I've uploaded a demo of this problem [here](https://github.com/liushigit/ReactNavTestIssueDemo). `npm test` will reproduce the problem.

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-alpha.9
| react-native     |  0.44.0
| node             | v7.10.0
| npm       |  4.2.0

**Comment by Sundin** [comment]
Same issue for me

**Comment by ZhangRGK** [comment]
Same for me.

- react-navigation: 1.0.0-beta.11
- react-native: 0.45.1
- jest: 20.0.4
- react-test-renderer: 16.0.0-alpha.12

**Comment by mengxi-liao** [comment]
I ran into the problem. But I was able to fix it by looking into the source code and found it's calling
```
Linking.addEventListener('url', ({ url }: { url: string }) => {
  this._handleOpenURL(url);
});
```
So it can be fixed by
```
jest.mock('Linking', () => {

  // we need to mock both Linking.getInitialURL() 
  // and Linking.getInitialURL().then()
  const getInitialURL = jest.fn()
  getInitialURL.mockReturnValueOnce({then: jest.fn()})

  return {
    addEventListener: jest.fn(),
    removeEventListener: jest.fn(),
    openURL: jest.fn(),
    canOpenURL: jest.fn(),
    getInitialURL: getInitialURL
  }
})
```

**Comment by vhmh2005** [comment]
same issue

**Comment by kelset** [comment]
Pinging OP @liushigit since this issue is quite old and related to an old version of the lib. If no answer I'll close in 7 days.

**Comment by kelset** [comment]
Hi there @liushigit ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.
