### ISSUE TITLE
StackNavigator: setParams in 2nd screen reroutes the app back to the 1st screen

### ISSUE THREAD

**Issue by despreston** [react-community/react-navigation#160]
For some reason the code below inside my 2nd screen causes the app to briefly show the 2nd screen then immediately transition back to the 1st. I'm not sure if this is a bug..

```
componentDidMount () {
    this.props.navigation.setParams({
      onBack: 'whatever'
    });
  }
```

**Comment by mmazzarolo** [comment]
Yup, having the same issue. 
Even something like this: 
```javascript
  componentDidMount () {
    this.props.navigation.setParams({})
  }
```
does something... weird? It redirects back to the previous screen.

**Comment by dmhood** [comment]
This is a problem for me as well, except it seems to get my app into a weird state where it "routes back" but everything is unresponsive.  FWIW having:

componentDidMount () {
    this.props.navigation.setParams({})
  }

On the top-level component works fine (in my case, a set of tabbed-views), it's just any screens added over the tabbed views that cause this strange behavior.

**Comment by despreston** [comment]
Yes @dmhood , everything is also unresponsive for me as well.

**Comment by Schniz** [comment]
ugly solution in the meantime:

```js
componentDidMount() {
  const name = this.props.dataL.fold(() => 'Untitled', data => data.song.title);
  setTimeout(() => this.props.navigation.setParams({ name }), 500);
}
```

delaying it for 100ms cause it to pause on the animation for some reason

**Comment by timothylui** [comment]
I get this too but it gets stuck in the middle of the animation.

**Comment by dmhood** [comment]
Example with reproducible error (navigate to "Stack with Dynamic Header": https://github.com/react-community/react-navigation/compare/master...sportsaction:setParamsError

**Comment by frankrowe** [comment]
a slightly better solution to this in the meantime is to use `InteractionManager`

```
  componentDidMount() {
    InteractionManager.runAfterInteractions(() => {
      const name = the.props.name;
      this.props.navigation.setParams({ name });
    });
  }
```

**Comment by grabbou** [comment]
Pull request fixing that was merged recently but Github failed to link these two issues. Closing. Here's the PR for reference: #191
