### ISSUE TITLE
Pass params down to children of StackNavigator

### ISSUE THREAD

**Issue by WillyRamirez** [react-community/react-navigation#1600]
Imagine the following setup below.
My problem is, when I click on the Profile tab in my tabbar, it navigates to ProfileTab. I pass some params along. 
However, in the background, since ProfileTab is a stackNavigator, it redirects me to its first child which is the Profile scene... but it does not pass along the params.

How can I get the params that are being sent to ProfileTab in Profile? 

Ps im using Redux 

```
export const AppNavigator = DrawerNavigator({
  Splash: {screen: SplashScreen},
  Main: {screen: TabNavigator({
    NewsFeedTab: NewsFeedStack,    
    NotificationsTab: NotificationsStack,
    ProfileTab: ProfileStack,    
  })},
}
);


const ProfileStack = { screen: StackNavigator({
  Profile : {screen: ProfileScene}
})
};
```  

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.9
| react-native     |  0.42.3

**Comment by augustoabreu** [comment]
Have you tried to navigate to `Profile` ?

**Comment by WillyRamirez** [comment]
Hi @augustoabreu thanks for your response. Yes I have tried that. I get a `did not get valid calls back from JS: [[]` error, and in the console I get an error `Converting circular structure to JSON`. I figured it was because it would be impossible to navigate directly to a nested route from a different Navigator... (just like in React-native-router-flux)

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
