### ISSUE TITLE
How can i change header title dynamically，the header title is a custom view

### ISSUE THREAD

**Issue by wangxuxiang** [react-community/react-navigation#1602]
static navigationOptions = ({ navigation }) => ({
        headerTitle: <SwitchNavTitle ref = {'switchNavTitle'} titles={['111', '2222']}
            navButtonClickCallBack={(buttonName) => {
                _this.navButtonClickCallBack(buttonName);
            }} />,
        headerTitleStyle: styles.headerTitleStyle,
    })

how to change SwitchNavTitle backgroundcolor,titles dynamically

**Comment by augustoabreu** [comment]
You can use `navigation.state.params` object. To set a new property use:

`navigation.setParams({ param: value })`

**Comment by nataroo** [comment]
I am trying to change the headerStyle dynamically.  The following code does not work.  What am I missing here?

```
this.props.navigation.setParams({
     headerStyle: style,
});
```

**Comment by THPubs** [comment]
Still, can't set the title in that method.

**Comment by qqqlllyyyy** [comment]
I have the same question. "this.props.navigation.setParams()" works for some properties like 'headerRight', but not for 'headerTitle'

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
