### ISSUE TITLE
How can I update TabBar backgroundcolor dynamically ? 

### ISSUE THREAD

**Issue by ztplz** [react-community/react-navigation#1604]
Hi, guys:
 Thanks  for the great project.

 There are two modes in my app to show its color.  One is the normal mode,  the other is the night 
 mode. When I click the night mode button,  I want to change the background color of TabBar.  I  don't know how to change the background color of TabBar dynamically.  What should I do?

Thanks in advance !

**Comment by fbarrailla** [comment]
Actually I think you can't change the background color of a TabNavigator properly because the option `tabBarOptions.style` cannot be setted dynamicaly... 

You can change the options with a top level component as bellow, but your navigator will be re-rendered entirely (you will lost the selected tab).

```javascript
class App extends React.Component {
  
  state = { bgColor: 'blue' };
  
  componentDidMount() {
    setTimeout(() => {
      this.setState({ bgColor: 'green' });
    }, 2000);
  }
  
  render() {
    const Navigator = TabNavigator(
      {
        Home: { screen: HomeScreen },
        OtherScreen: { screen: OtherScreen },
      },
      {
        tabBarOptions: {
          style: {
            backgroundColor: this.state.bgColor,
          },
        },
      },
    );
    return <Navigator />;
  }
}
```

**Comment by ztplz** [comment]
@fbarrailla  Thanks for your answer.  But I find another way to got it. 
I use custom TabBar instead of  TabBar.  Here is my solution.

import { TabBarBottom } from 'react-navigation';

Class CustomTabBar extends Component {
  render(){
      return (
          <TabBarBottom 
              {...this.props}
               style={{
                  backgroundColor:  this.props.screenProps.isNIghtMode? '#ffffff' : '#000000'
               }}
         />
    )
   }
}

screenProps is from my app redux

in TabNavigator a:
  const AppTabNavigator  = TabNavigator({
     .......
},{
    tabBarComponent:  CustomTabBar 
})

It is work fine for me.

**Comment by progamr** [comment]
this is exactly my case thanks mate @ztplz

**Comment by harshalkd** [comment]
@ztplz how can i call CustomTabBar in my child js for change tabbar background color?
