### ISSUE TITLE
Create TabBar based on remote json feed

### ISSUE THREAD

**Issue by edward-of-clt** [react-community/react-navigation#1606]
Is it possible to utilize a remote JSON feed to assemble the tabs and point to the appropriate pages?

Essentially, the whole app is dynamically produced from a script on a PHP/MySQL server. I have a content.js file that calls a library I created to format the content provided in the JSON content.

My problem is I need the tabs to be dynamically created using that same idea.... If I delete the page from the pages table, the tab should not be there, if I add one, it should add it on the next app load, etc.

Any ideas?

**Comment by koenpunt** [comment]
StackOverflow should probably be the place to ask such questions. That being said, shouldn't be too hard. 

Something like this should work:

```js
class App extends Component {
  constructor() {
    super();
    this.state = {};
  }

  componentDidMount() {
    fetch('/pages').then(res => res.json()).then(res => {
      const screens = {};
      this.state.pages.forEach(page => {
        screens[page.screenName] = { component: `${page.componentName}Screen` };
      });
      this.setState({ screens: screens });
    });
  }

  render() {
    if (this.state.screens)
      return TabNavigator(this.state.screens);
    }
    return null;
  }
}

**Comment by AbeHerbert** [comment]
Thanks for the help; my experience with SO hasn't been super productive, I find that the GitHub community is typically a better tool — even though I'm technically using it out of scope of what it was designed for.

Thanks again!

**Comment by AbeHerbert** [comment]
Okay, so after trying this out.... I'm finding that I keep getting this error message.

All the dynamic pages point to a DBContent component which renders the data retrieved from the database....


![image](https://cloud.githubusercontent.com/assets/10331721/26327272/b6009868-3f0c-11e7-9b27-198d3cb01135.png)

**Comment by AbeHerbert** [comment]
![image](https://cloud.githubusercontent.com/assets/10331721/26327312/e95bf31a-3f0c-11e7-8a0a-1a6f94c47546.png)

**Comment by koenpunt** [comment]
Ah, now that I need dynamic tabs myself I see I made a mistake in my example.. The result of `TabNavigator(..)` should be rendered _as a component_:

```js
class App extends Component {
  constructor() {
    super();
    this.state = {};
  }

  componentDidMount() {
    fetch('/pages').then(res => res.json()).then(res => {
      const screens = {};
      res.pages.forEach(page => {
        screens[page.screenName] = { component: `${page.componentName}Screen` };
      });
      const tabs = TabNavigator(screens)
      this.setState({ tabs: tabs });
    });
  }

  render() {
    if (this.state.tabs)
      return <this.state.tabs />;
    }
    return null;
  }
}
```

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
