### ISSUE TITLE
Overlaying StackNavigator header.

### ISSUE THREAD

**Issue by nazywamsiepawel** [react-community/react-navigation#1608]
Dear all,

I'm currently working on an application using StackNavigator. As user is navigation deeper into the stack, one of the screens that added has to, at a certain moment, be overlayed with a full-screen view.

Q : Is it possible to overlay the header of StackNavigator from within one of the pushed components? 

My current approach (described below) fails miserably. The blue view should be overlaying the entire screen. 

```
overlayView: {
    height: Dimensions.get('window').height,
    width: Dimensions.get('window').width,
    position: 'absolute',
    backgroundColor:'blue',
    zIndex:1000,
 },
```

<img width="388" alt="screen shot 2017-05-19 at 17 33 44" src="https://cloud.githubusercontent.com/assets/334875/26257838/0d0ec27e-3cba-11e7-9f3f-2fb6045dbe2d.png">

**Comment by augustoabreu** [comment]
You can set `header: null` on navigationOptions, then the header will be hidden.

**Comment by MarkMurphy** [comment]
I have the same problem and hiding the header isn't going to work for me because Im trying to display a full screen semi-transparent loading overlay and having the header disappear all of a sudden wouldn't be cool.

**Comment by jaredramirez** [comment]
I was able to solve this issue by doing:
```
static navigationOptions = ({navigation}) => ({
  headerStyle: {
    position: 'absolute',
    top: 0,
    left: 0,
  },
  ...
});
```

**Comment by JKonTiki** [comment]
i've found react-native `Modal` components to be a good solution for me (in my experience they overlay on top of anything). try just changing your View to Modal with animations and other modal-y things turned off

**Comment by kelset** [comment]
Pinging OP @nazywamsiepawel since this issue is quite old and related to an old version of the lib. If no answer I'll close in 7 days.

Moreover @jaredramirez solution is a good approach.

**Comment by kelset** [comment]
Hi there @nazywamsiepawel ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.

**Comment by rajeshpanwar007** [comment]
Hi @kelset 

I am facing same issue. How can I fix it ?

**Comment by Liqiankun** [comment]
@jaredramirez Not work for me

**Comment by brentvatne** [comment]
hi! if you care about this please create a new issue and fill out the issue template and i'll be happy to look into it!
