### ISSUE TITLE
NavigationPlayground is no longer working

### ISSUE THREAD

**Issue by agrcrobles** [react-community/react-navigation#1609]
I was following instructions:
https://reactnavigation.org/docs/guides/contributors
Getting: `react-native-scripts: not found` when doing `npm start`

**Comment by skevy** [comment]
I'm aware of this issue.

Trying to get this resolved ASAP.

**Comment by ajostergaard** [comment]
Try this: https://github.com/react-community/react-navigation/issues/1325

Note use of **react-native start**.

**Comment by spencercarli** [comment]
Consolidating NavigationPlayground related issues to #2170.
