### ISSUE TITLE
Documentation Overhaul

### ISSUE THREAD

**Issue by ElliottJRo** [react-community/react-navigation#161]
Hey all, is anyone else having issues finding the right API doc while developing? Would people find it useful if we separate the API docs into its own section (kinda like [redux docs](http://redux.js.org/docs/api/#api-reference-1))

How I imagine this restructuring may look like is:
* Intro
  * Motivation
  * Basic Concepts -> Router, View, Navigator, Transitioner
  * Examples
* Basics
* Advanced
* API Reference
  * Top Level (Things you can import from `react-navigation`)
  * navigation (`props.navigation`)
...

related: #118

Thoughts?

**Comment by agrcrobles** [comment]
I agree that are missing pieces but I think documentation is good enough for now and we all understand it has been released just a week ago, I don't find it as an issue and my thought is that  #161 should be closed.

**Comment by benvium** [comment]
I've been evaluating this library today and have found the documentation very good. I'd like to see some more docs on custom styled navigation elements, but that's should be a separate ticket :-)

**Comment by ElliottJRo** [comment]
Hmm Okay, with not enough feedback on this issue, I guess now is not the time for this. Thanks all!
