### ISSUE TITLE
can not switch tab when the tabbar is invisible in android

### ISSUE THREAD

**Issue by cncowboy** [react-community/react-navigation#1614]
### Current Behavior

I set the tabbar visible=false, then switch the tab using NavigationActions.navigate,nothing happened in android, but the behavior is ok in ios

code:

TabNavigator--
-|---Page1
-|---Page2(StackNavigator)
-----|---SubPage1                                                                          
-----|---SubPage2
                                                              
dispatch(NavigationActions.navigate('Page2'));

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  beta 10
| react-native     |  0.44
| node             | 
| npm or yarn      |

**Comment by cncowboy** [comment]
React-navigation : last
React-native: 0.44.0

**Comment by spencercarli** [comment]
Please provide a demo of this issue. I'm going to close this for now but will happily re-open if a demo (using the latest version of react-navigation is provided). Thanks!
