### ISSUE TITLE
In new release (beta.10) shadow under TabNavigator is gone

### ISSUE THREAD

**Issue by jaredgei** [react-community/react-navigation#1615]
There used to be a shadow by default under the TabNavigator on android, which could be turned off/on using the 'elevation' style. Now the shadow is missing, and "elevation" cannot bring it back.

**Comment by allpwrfulroot** [comment]
Same with iOS, zIndex or other mechanisms don't work. Shadow does not show unless the screen view is set to background: 'transparent'

**Comment by tugorez** [comment]
Hey man, dont know if this is still relevant but they've fixed this problem in the master branch.

**Comment by waquidvp** [comment]
I still seem to have this problem, it there any solutions? There is no elevation being rendered even with the elevation specified:
```
tabBarOptions: {
            indicatorStyle: {
                backgroundColor: theme.tabIndicator,
                height: 2
            },
            labelStyle: {
                fontSize: 14,
                fontFamily: 'Roboto-Medium'
            },
            style: {
                backgroundColor: theme.primary,
            },
            tabStyle: {
                height: 48,
                elevation: 4
            }
        }
```

**Comment by waquidvp** [comment]
There is a similar issue with react-native-material-bottom-navigation where the elevation is not showing on versions after 1.0.0-beta.9 . The elevation works perfectly on version 1.0.0-beta.9 . 

The react-native-material-bottom-navigation issue:
https://github.com/timomeh/react-native-material-bottom-navigation/issues/8

**Comment by waquidvp** [comment]
@tugorez Just tried the latest branch. It seems to solve the elevation problem. It fixed it for react-native-material-bottom-navigation too.

**Comment by sanjayholla94** [comment]
@spencercarli This issue can be closed. I'll tag you in a few other issues which I believe can be closed
