### ISSUE TITLE
Force re render on Back action

### ISSUE THREAD

**Issue by BharathKumarBachina** [react-community/react-navigation#1617]
Using stack navigator when I go from the screen(A) -> screen(B)  and click Back on Screen(B), I see Screen(A) with previous state and data as expected.

But now I want to do a force re-render based on some condition. Is there any way to this?

Here is the use case:-

For example, I have a List and details screen. 

When the user clicks on listItem L, then it will go details. let's say If the user set that particular Item favourite in details and come back to the list, then that item should update with that favourite tag

**Comment by koenpunt** [comment]
Could probably be part of #1363

**Comment by Jacse** [comment]
To do this i currently pass a function like `updateFavorites` to screen(B) via `params`. Before navigating back i call the function which updates the state, such as:
````
this.props.navigation.state.params.updateFavorites(23)
this.props.navigation.goBack();
````

**Comment by DavideValdo** [comment]
Banal bookmark scenario: https://vid.me/SYMi
#1810 

@Jacse, Is this really the only way? 
Console-logging the hard way in my Gallery component actually tells that upon BOOKMARK_ADDED or BOOKMARK_REMOVED actions triggered by the FullGallery component, the render() method gets triggered in Gallery, but I can't see the changes unless I switch the js-based segment tab.

**Comment by Jacse** [comment]
@DavideValdo It's not an ideal solution, but a working workaround. By passing the functions that way only my "Gallery" is Redux-aware, while the other screen is a simple component.

To wrap up from #1810: What you have discovered is that render() is actually called in "Gallery" when you change the redux-state, but the rendering is not shown when you navigate back.

**Comment by DavideValdo** [comment]
And what do you do in your updateFavorites()? You pass the children's updated favorites to the parent? Can you show code?

**Comment by DavideValdo** [comment]
I'm experiencing the same problem across tabs from a TabNavigator, so it is not only the back action that behaves like this.

render() is called with correct new props but initially is not shown
https://vid.me/HSgJ

Console output when clicking bookmark in the vid:
gallery.js:196 Rerendering from vendor m_160dfjsofjsok
gallery.js:179 Bookmark found-KmHiFRPIcV8AfLtAJa5
gallery.js:196 Rerendering from category knitwear
gallery.js:179 Bookmark found-KmHiFRPIcV8AfLtAJa5

**Comment by efkan** [comment]
+1 

I'm also in trouble with a similar issue https://github.com/react-community/react-navigation/issues/1825#issuecomment-309053549

I guess the problem `react-navigation` is not refreshed by `Redux` changes. Just a guess.

**Comment by alfie-ab** [comment]
@DavideValdo Having the same issue, any luck?

**Comment by TiraO** [comment]
@BharathKumarBachina 
> But now I want to do a force re-render based on some condition. 

It seems like re-render should just always be triggered on a back action.

**Comment by TiraO** [comment]
The DrawerNavigator does a re-render when switching between pages, but the StackNavigator does not.

There is some additional discussion on these duplicate issues: https://github.com/react-community/react-navigation/issues/1857 https://github.com/react-community/react-navigation/issues/922

**Comment by kazim1** [comment]
Screen A. Pass current scene instance to next scene as state parameter.

`
this.props.navigation.navigate('ScreenB', {ScreenA: this});
`

Screen B. You can now update any thing of your previous scene. Let's say `showCategory` is a state variable of Screen A.

`
this.props.navigation.state.params.ScreenA.setState({'showCategory': true});
`
`
this.props.navigation.goBack(null);
`

**Comment by freynolds** [comment]
Hey guys, just arrived to the same case, this is pretty annoying, and in my case is more than one screen down where redux is triggered.
Having some type of lifecycle, like componentWillApear or something like that would let me at least make a force reload in that case.
But my parent screen, has no clue about what happens in it's children (and that is a good thing!)

**Comment by freynolds** [comment]
Ok, update on my specific problem.
My redux reducer was not cloning the object entirely, and therefore it didn't triger reload.
Check if what you are changing is at the top level of the state if not you will need to use object assign or [...] or {...} until you reach the property

**Comment by DavideValdo** [comment]
@alfie-ab 
I solved this by binding the leaves of the Component tree to the Redux state.

I had code like this in the first screen, to render the products:

```
toRender = new Array()
const { STORE } = this.props;
for (id in STORE.products)
    toRender.push(<PictureThumb product={STORE.products[id]}>
return toRender
```
Now `PictureThumb `and `PictureDetail ` are both HOCs, works like a charm

Is this bad practice somehow?

**Comment by kelset** [comment]
Pinging OP @BharathKumarBachina since this issue is quite old and related to an old version of the lib. If no answer I'll close in 7 days.

That said, I think that to "force" a re-render in a redux scenario you simply need to connect the "target" component with the part of the store where you have the navigation.

**Comment by kelset** [comment]
Hi there @BharathKumarBachina ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.

**Comment by VKGraphics** [comment]
give me solution ?

**Comment by mauriciopazpp** [comment]
```
this.props.navigation.addListener(
    'willFocus',
    () => {
        this.props.yourFunction()
    }
)  
```
You can have control of willFocus putting in a variable if you want
```
this.willFocus = this.props.navigation.addListener(
    'willFocus',
    () => {
        this.props.yourFunction()
    }
) 
```

and you can remove the action if you want too
```
componentWillUnmount() {
   this.willFocusSubscription.remove()
}
```

**Comment by runandrew** [comment]
@mauriciopazpp This works for me, thanks!

**Comment by nickjuntilla** [comment]
I found the answer is navigations events: https://itnext.io/handle-tab-changes-in-react-navigation-v2-faeadc2f2ffe

**Comment by lnx1337** [comment]
@nickjuntilla ;) 

``` 
import { NavigationEvents } from "react-navigation";
class HomeScreen extends React.Component {
  render() {
    return (
      <View>
        <NavigationEvents
          onWillFocus={payload => {
            console.log("will focus", payload);
          }}
        />
        <Text>Home</Text>
      </View>
    );
  }
}

```

**Comment by GuilhermeTrivilin** [comment]
If you are using React Navigation 5.X, just do the following:

```
import { useIsFocused } from '@react-navigation/native'

export default function App(){

const isFocused = useIsFocused()

    useEffect(() => {
        //Update the state you want to be updated
    } , [isFocused])
}
```

**Comment by namchuai** [comment]
`But now I want to do a force re-render based on some condition. Is there any way to this?`
@GuilhermeTrivilin this will rerender the screen even the `condition` does not met.

**Comment by raajnadar** [comment]
@namchuai you can do like this, you can have as many useEffects you want, unlike componentDidMount or any class-based lifecycle hooks.

```
import { useIsFocused } from '@react-navigation/native'

export default function App(){

const isFocused = useIsFocused()

    useEffect(() => {
        if (myCond) {
              //Update the state you want to be updated
        }
    } , [isFocused])
}
```

**Comment by namchuai** [comment]
@raajnadar Thank you! I ended up using React native `useContext` with `useIsFocused()` to solve the problem.

**Comment by ReactNativ** [comment]
```javascript

  React.useEffect(() => {
    const unsubscribe = navigation.addListener('focus', () => {
      // The screen is focused
      // Call any action
    });

    // Return the function to unsubscribe from the event so it gets removed on unmount
    return unsubscribe;
  }, [navigation]);

```
