### ISSUE TITLE
StackNavigator screen header repetition

### ISSUE THREAD

**Issue by powerformer** [react-community/react-navigation#1621]
![image](https://cloud.githubusercontent.com/assets/26423749/26282049/49692426-3e3b-11e7-94ff-843a79e83b9e.png)

**Comment by powerformer** [comment]
change title

**Comment by matthamil** [comment]
Can you include a code snippet so that we may be able to answer your question?

**Comment by bakufusyougunn** [comment]
@powerformer Maybe you make title for both the StackNavigator and each screen within the navigator.
