### ISSUE TITLE
setParam in componentDidMount beta.10. (auto select tab)

### ISSUE THREAD

**Issue by panhna** [react-community/react-navigation#1622]
Hi

i use setParam in componentDidMount i got a problem that it auto select tab.
i create 5 tab. first tab is initialRoute.
but if i try to call setParam in componentDidMount of tab 4th it will open first tab & after that it auto select tab 4th.

something like it will auto select tab on the last tab that has setParam is called.

Thx. sorry for english.

**Comment by spencercarli** [comment]
Without any code it's hard to figure out example what the issue you're having is. If you think it's a bug with React Navigation please provide a demo to work from, otherwise StackOverflow may be a better place to ask. Thank you!
