### ISSUE TITLE
Update react-native-drawer-layout-polyfill to 1.3.1

### ISSUE THREAD

**Issue by Jacse** [react-community/react-navigation#1626]
`react-native-drawer-layout-polyfill@1.3.1` fixes a bug which failed to clear interactions meaning that functions invoked through `InteractionManager.runAfterInteractions` were never called.

For this reason it is currently not possible to do the "render inexpensive component until navigation is done"-trick in a `DrawerNavigator`.

See [react-native-drawer-layout#16](https://github.com/react-native-community/react-native-drawer-layout/issues/16)

**Comment by Jacse** [comment]
Cc @skeva @satya164

**Comment by satya164** [comment]
Can you send a PR for that?

**Comment by Jacse** [comment]
Moved to #1716
