### ISSUE TITLE
Imported screens are not recognised when not explicitly imported

### ISSUE THREAD

**Issue by designorant** [react-community/react-navigation#163]
This is either a borderline bug or my lack of understanding when it comes to modules so apologies if it's the latter.

I've got the following config (simplified):
```js
import { LoginContainer } from '~/containers' // note the containers are not explicitly imported but 'proxied' via ~/containers/index.js file

const AppContainer = StackNavigator({
  Login: { screen: LoginContainer }
})
```

The 'proxy' file (`~/containers/index.js`) lists all containers, i.e.:
```js
export LoginContainer from './Login/LoginContainer'
```

The container itself looks like that:
```js
export default class LoginContainer extends Component {
  ...
}
```

With such config I get the following error:
```
Route 'Login' should declare a screen. For example:

import MyScreen from './MyScreen';
...
Login: {
  screen: MyScreen,
}
```

However, everything is fine when I import the container explicitly:
```js
import LoginContainer from '~/containers/Login/LoginContainer'
```

Furthermore, when I get rid of the `default` export, i.e.:
 ```js
export class LoginContainer extends Component {
  ...
}
```
then I can use named import just fine, i.e.:
```js
import { LoginContainer } from '~/containers/Login/LoginContainer'
```
even via the 'proxy' file (tweaked accordingly):
```js
export { LoginContainer } from './Login/LoginContainer'
```
and then imported to navigator (as per first example).

I've picked up this 'proxy' pattern a while ago and never had any issues but since explicit imports work just fine (whether named or not) I'm a bit puzzled what's going on here.

**Comment by satya164** [comment]
The syntax seems fine, but react navigation cannot affect/doesn't care how modules are imported/exported. I'd suggest to log them and seem what's wrong with the setup.

**Comment by ms88privat** [comment]
@satya164 To me happened something similar. Last month I was in the transition from router-flux to ex-navigation. Because of this, my `screens` where imported in two different locations / files, but only used in the newer one where my ex-navigation config was.

Right now I wanted to upgrade to react-navigation and I basically only changed `createRouter` to `StackNavigator` and moved to the new syntax with screen property. But then I received the error message. 

And I couldn't believed it, my component was really undefined!! It did work before. Then I logged my second Screen and it was defined, only my first input was not.

After I removed the import in the other file, it did work again, but now the second screen was undefined - same reason. After deleting all duplicated imports, it is working...

**Comment by vexsnare** [comment]
Facing similar type of issue. Mind blowing

**Comment by leesolway** [comment]
Exactly the same issue...

When i load from another module, it works fine
**Example:** import {Loading} from '../windows'

When i load from a current module, i get the problem reported above:
Example: import {Login} from './'

**Comment by designorant** [comment]
For those stumbling upon this issue, it appears there might have been a change in one of the recent versions of Node.js that might be causing this behaviour. I haven't looked into it in detail but it looks we might need to be a bit more specific with our imports now:

```js
import { foo } from './bar' // doesn't work
import { foo } from './bar/index' // does work
```

**Comment by jasan-s** [comment]
@designorant how did you solve the issue ? are you just using 
`import LoginContainer from '~/containers/Login/LoginContainer'`
for all containers individually?

**Comment by ms88privat** [comment]
@ericvicenti Just tagged you here. I think this issue has to be reopen or clarified whats going on. Never encountered this before, so I believe it is related to this library. Thank you

**Comment by designorant** [comment]
@jasan-s The project I've been working on has been refactored since and doesn't use that pattern anymore for navigation. There were some other factors that affected the behaviour I've described though.

@ms88privat Try what satya164 said above. Log your modules and see how are they coming through. You'll quickly realise this has nothing to do with this library.

**Comment by ms88privat** [comment]
@designorant ? What do you mean exactly? Did you read my [post here](https://github.com/react-community/react-navigation/issues/163#issuecomment-279242084)?

Why do I can not import the file of the screen in another file? This did never happened before. I will try to reproduce with example and newest version when I'm back home.

**Comment by designorant** [comment]
@ms88privat Sorry, I misread your original post and thought you still have a problem. Nevertheless it looks like you've answered yourself already: your specific issue was with duplicated imports causing some of your modules to come out as undefined. I think it's a good thing that react-navigation picks up such nuances.

**Comment by Mayzie** [comment]
I am running into the exact same issue.

**index.android.js:**
```
import React, { Component } from 'react';
import {
	AppRegistry,
} from 'react-native';

import {
	StackNavigator,
} from 'react-navigation';

import {
	LoginScreen
} from './screens/login';

const App = StackNavigator({
	Login: { screen: LoginScreen },
});

AppRegistry.registerComponent('App', () => App);
```

**./screens/login.js:**
i```
import React, { Component } from 'react';

import {
	View,
	Text,
} from 'react-navigation';

export default class LoginScreen extends Component {
	static navigationOptions = {
		title: 'Login',
	};

	render() {
		return <Text>Login!</Text>;
	}
}

module.exports = LoginScreen;
```

However, it works perfectly fine when I copy and paste the class from `./screens/login.js` into `./index.android.js`and remove the import. What am I doing wrong?

**Comment by satya164** [comment]
@Mayzie you have both `export default` and `module.exports`, remove one. you are also importing as `{ LoginScreen }` even if it's a default export. Basically remove `module.exports = LoginScreen;` and import as `import LoginScreen from '..'`

**Comment by ms88privat** [comment]
Just found something interesting, could this be related to react-native packager? This looks liek my specific problem I mentioned above.

https://github.com/webpack/webpack/issues/4160#issuecomment-285439379

**Comment by mdanics** [comment]
having this same issue too

**Comment by mdanics** [comment]
I just had this problem, and to fix it i had to remove the curly brackets around my import.  

e.g.

I was getting the error by importing like:
`import { Login } from './Login'`
and I fixed it by doing:

`import Login from './Login'`

**Comment by franz-see** [comment]
What @mdanics said worked for me.

Alternatively, you export it this way -`export { Login }`.
