### ISSUE TITLE
Screen headers do not appear when using DrawerNavigator

### ISSUE THREAD

**Issue by ramsestom** [react-community/react-navigation#1632]
### Current Behavior
Screens that are handeled by a DrawerNavigator do not show their header

### Expected Behavior
Screens without header:null in navigationOptions should show a header

### Your Environment
android
react-native  0.42.3
react-navigation  1.0.0-beta.10

For example I have defined this drawer navigator:

```
const MainNavigator = DrawerNavigator({
  Notifications: {screen: Notifications},
  Friends: {screen: Friends},
  Profile: {screen: Profile},
  Settings: {screen: Settings},
});
```

And in my Notifications component class I have:

```
 static navigationOptions = ({ navigation}) => ({
    title: 'Notifications',
    headerTitle: 'Notifications',
  });
```

The title 'Notifications' appear correctly in the drawer but in the Notifications screen itself, there is no header with the title 'Notifications'....

**Comment by basudz365** [comment]
I was able to make this work by setting each screen in the drawer to it's own stack navigator.  Setting the navigation options inside each screen for the stack navigator then did the trick to display the title correctly.

**Comment by samridhgupta** [comment]
@basudz365 Sorry I couldn't interpret your solution. Can you provide some code to assist me. thanks!

**Comment by basudz365** [comment]
```javascript
import MainScreen from '../components/MainScreen';
import SecondScreen from '../components/SecondScreen';

const mainScreenStack = StackNavigator(
  {
    MainScreen: {
      screen: MainScreen,
    }
  },
  {
    navigationOptions: ({ navigation }) => ({
      initialRouteName: 'MainScreen',
      headerMode: 'screen',
      headerTitle: 'Main Screen Header',
      drawerLabel: 'Main Screen',
    }),
  }
);

const secondScreenStack = StackNavigator(
  {
    SecondScreen: {
      screen: SecondScreen,
    }
  },
  {
    navigationOptions: ({ navigation }) => ({
      initialRouteName: 'SecondScreen',
      headerMode: 'screen',
      headerTitle: 'Second Screen Header',
      drawerLabel: 'Second Screen',
    }),
  }
);

const AppNavigator = DrawerNavigator(
  MainScreen: {
    name: 'MainScreenStack',
    screen: mainScreenStack,
  },
  SecondScreen: {
    name: 'SecondScreenStack',
    screen: secondScreenStack,
  },
);
```

@samridhgupta 
You can create single page StackNavigators and set the header title in the navigationOptions[headerTitle] property, and then you set each StackNavigator as your screen in your DrawerNavigator.

Also, you can add more screens to the StackNavigators that would NOT show in the drawer menu, but will allow you to navigate laterally.  You are able to set the headerTitle for each screen in the StackNavigators by setting the navigationsOptions[headerTitle] in that screen component.

I apologize if this example doesn't work, I'm doing this from memory right now but this is the concept that worked for me to set the headerTitle for each screen in my DrawerNavigator.

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!

**Comment by priyankinfinnov** [comment]
Hey @basudz365, i tried your approach, the header is now visible. 

But when i navigate with props like below.
this.props.navigation.navigate( 'Chat', {convoid: '23452'} );
The Chat screen does not receive the params (convoid).

Can you help ?

**Comment by serranoarevalo** [comment]
Isn't any other solution less verbose than making a stack navigator available?

**Comment by uqmessias** [comment]
Thank you @basudz365.
I had to make some adjustments, but the main idea was preserved:

```javascript
// @flow

import React, { type Node } from 'react';
import { Image } from 'react-native';
import { StackNavigator, DrawerNavigator } from 'react-navigation';


import routeNames from 'routes/routes';
import EmailLogin from 'routes/EmailLogin';
import Filter from 'routes/Filter';
import Login from 'routes/Login';
import Welcome from 'routes/Welcome';

...

const doNotAppearOnDrawer = {
  navigationOptions: {
    drawerLabel: (): any => null,
    drawerIcon: (): any => null,
    drawerLockMode: 'locked-closed',
  },
};

const StackWrapper = (screen: Function, routeName: string): StackNavigator =>
  StackNavigator(
    { [routeName]: { screen } },
    {
      headerMode: 'screen',
      navigationOptions: {
        gesturesEnabled: false,
        header: null,
        headerStyle: Layouts.headerContainer,
        headerTitleStyle: Layouts.headerTitle,
      },
    },
  );

const routes = {
  [routeNames.Welcome]: {
    screen: Welcome,
    ...doNotAppearOnDrawer,
  },
  [routeNames.Login]: {
    screen: Login,
    ...doNotAppearOnDrawer,
  },
  [routeNames.EmailLogin]: {
    screen: EmailLogin,
    ...doNotAppearOnDrawer,
  },
  [routeNames.Filter]: {
    screen: StackWrapper(Filter, routeNames.Filter),
    ...doNotAppearOnDrawer,
  },
};


const MenuNavigator = DrawerNavigator(routes, {
  initialRouteName: routeNames.Welcome,
  navigationOptions: {
    drawerIcon: (): any => <Image source={assets.icons.home.search} />,
  },
});
```

**Comment by nsbruce** [comment]
@serranoarevalo did you have any luck finding a less verbose option?

**Comment by nsbruce** [comment]
Hi @spencercarli is it possible to reopen this issue? It seems the bug tag would be more appropriate than the question tag.

**Comment by serranoarevalo** [comment]
@nsbruce No mate. I ended up doing a forEach.

https://github.com/serranoarevalo/cm-nomad-guide/blob/master/Navigation/navigation.js#L59

**Comment by lvalladares** [comment]
This issue should be reopened, is not a question is a bug you have to do all of that only to make a header appear, a very common thing for mobile apps.

**Comment by arapocket** [comment]
Please reopen this. The current solution is overkill for such a simple essential feature.

**Comment by benjefferies** [comment]
Came up against this issue today. Either the [documentation](https://reactnavigation.org/docs/en/drawer-based-navigation.html) should be updated or it should be fixed?

**Comment by chesstrian** [comment]
@benjefferies I have it working, can you please show me an example of your code?, feel free to contact me directly at chesstrian@gmail.com for help.

**Comment by MustaphaGhlissi** [comment]
In this case , 

According to the [official docs](https://reactnavigation.org/docs/en/drawer-navigator.html) you have to create a stack navigator for each drawer item then you'll be able to set the header for every drawer Item.

Here is my code example: 

1- Global app routes: RouteConfigs.js
```
import SignUpScreen from '../screens/SignUp';
import HomeScreen from '../screens/Home';
import DetailsScreen from '../screens/AdDetails';
import ProfileScreen from '../screens/Advertiser/Profile';
import SettingsScreen from '../screens/Settings';
import AdsScreen from '../screens/Advertiser/Ad/Index';
import NewAdScreen from '../screens/Advertiser/Ad/New';
import ShowAdScreen from '../screens/Advertiser/Ad/Show';
import EditAdScreen from '../screens/Advertiser/Ad/Edit';

export const AuthRouteConfigs = { 
  SignUp: SignUpScreen
};

export const HomeRouteConfigs = {
  Home: HomeScreen,
  AdDetails: DetailsScreen,
  NewAd: NewAdScreen,
};

export const AdsRouteConfigs = {
  Ads: AdsScreen,
  NewAd: NewAdScreen,
  EditAd: EditAdScreen,
  ShowAd: ShowAdScreen,
};

export const ProfileRouteConfigs = {
  Profile: ProfileScreen,
};

export const SettingsRouteConfigs = {
  Settings: SettingsScreen
}
```
2- Stack navigator (config included) for each drawer item route config: 

```
import { createStackNavigator } from "react-navigation";
import { 
    HomeRouteConfigs, AdsRouteConfigs, ProfileRouteConfigs, SettingsRouteConfigs
} from "./RouteConfigs";

import {StackNavigatorConfig} from './StackNavigatorConfig';

const StackNavigatorConfig = {
  mode: 'modal',
  headerMode: 'float',
  headerTransitionPreset: 'face-in-place',
  defaultNavigationOptions: {
    header: props => <AppBar {...props} searchable />,
    headerStyle: {
      backgroundColor: "transparent"
    },
    gesturesEnabled: false
  },
}


export const HomeStackNavigator = createStackNavigator(HomeRouteConfigs, StackNavigatorConfig);
export const AdsStackNavigator = createStackNavigator(AdsRouteConfigs, StackNavigatorConfig);
export const ProfileStackNavigator = createStackNavigator(ProfileRouteConfigs, StackNavigatorConfig);
export const SettingsStackNavigator = createStackNavigator(SettingsRouteConfigs, StackNavigatorConfig);


```
3- Drawer navigator (Config included) 
```
import { createDrawerNavigator, createAppContainer } from "react-navigation";
import {
    HomeStackNavigator, AdsStackNavigator, ProfileStackNavigator, SettingsStackNavigator
} from './AppStackNavigator';
import {DrawerNavigatorConfig} from './DrawerNavigatorConfig';

const DrawerRouteConfigs = {
    Home: HomeStackNavigator,
    Ads: AdsStackNavigator,
    Profile: ProfileStackNavigator,
    Settings: SettingsStackNavigator
}

const DrawerNavigatorConfig = {
    contentComponent: (props) => <AppDrawer {...props} />,
    drawerType: 'slide',
    initialRouteName: "Home",
    mode: 'modal'
} 

 const AppDrawer = createDrawerNavigator(DrawerRouteConfigs, DrawerNavigatorConfig);

export const AppContainer = createAppContainer(AppDrawer);
```


I hope this can be beneficial for every one in need ! 

Regards
Mustapha GHLISSI.

**Comment by mharrisweb** [comment]
@uqmessias I've got a very similar solution to yours but its not working, any ideas?


```
const withHeader = (
	screen: Function,
	routeName: string,
	header
): StackNavigator =>
	createStackNavigator(
		{ [routeName]: { screen } },
		{
			headerMode: "screen",
			navigationOptions: ({ navigation }) => ({
				header: props => <Header {...props} />
			})
		}
	);


const routes = {
	Home: {
		screen: withHeader(HomeScreen, "Home", BasicHeader)
	},
	Links: {
		screen: withHeader(LinksScreen, "Home", DrawerHeader)
	},
	Settings: {
		screen: withHeader(SettingsScreen, "Settings", DrawerHeader)
	},
	VideoEpisodes: {
		screen: withHeader(VideoEpisodesScreen, "Video Episodes", DrawerHeader)
	},
	TestYourself: {
		screen: withHeader(TestYourselfScreen, "Test Yourself", DrawerHeader)
	},
	MyResults: {
		screen: withHeader(MyResultsScreen, "My Results", DrawerHeader)
	},
	BookmarkedVideos: {
		screen: withHeader(
			BookmarkedVideosScreen,
			"Bookmarked Videos",
			DrawerHeader
		)
	},
	Search: {
		screen: withHeader(SearchScreen, "Search", DrawerHeader)
	},
	About: {
		screen: withHeader(AboutScreen, "About", DrawerHeader)
	}
};

const AppNavigator = createDrawerNavigator(routes);


export default createAppContainer(AppNavigator);

```

**Comment by galbenyosef** [comment]
> @uqmessias I've got a very similar solution to yours but its not working, no errors but headers are blank, any ideas?
> 
> ```
> const withHeader = (
> 	screen: Function,
> 	routeName: string,
> 	header
> ): StackNavigator =>
> 	createStackNavigator(
> 		{ [routeName]: { screen } },
> 		{
> 			headerMode: "screen",
> 			navigationOptions: ({ navigation }) => ({
> 				header: props => <Header {...props} />
> 			})
> 		}
> 	);
> 
> 
> const routes = {
> 	Home: {
> 		screen: withHeader(HomeScreen, "Home", BasicHeader)
> 	},
> 	Links: {
> 		screen: withHeader(LinksScreen, "Home", DrawerHeader)
> 	},
> 	Settings: {
> 		screen: withHeader(SettingsScreen, "Settings", DrawerHeader)
> 	},
> 	VideoEpisodes: {
> 		screen: withHeader(VideoEpisodesScreen, "Video Episodes", DrawerHeader)
> 	},
> 	TestYourself: {
> 		screen: withHeader(TestYourselfScreen, "Test Yourself", DrawerHeader)
> 	},
> 	MyResults: {
> 		screen: withHeader(MyResultsScreen, "My Results", DrawerHeader)
> 	},
> 	BookmarkedVideos: {
> 		screen: withHeader(
> 			BookmarkedVideosScreen,
> 			"Bookmarked Videos",
> 			DrawerHeader
> 		)
> 	},
> 	Search: {
> 		screen: withHeader(SearchScreen, "Search", DrawerHeader)
> 	},
> 	About: {
> 		screen: withHeader(AboutScreen, "About", DrawerHeader)
> 	}
> };
> 
> const AppNavigator = createDrawerNavigator(routes);
> 
> 
> export default createAppContainer(AppNavigator);
> ```

try replacing 'navigationOptions' with 'defaultNavigationOptions',

**Comment by mharrisweb** [comment]
Does anyone know how to get 'ImageBackground' working with this? How do you make the cards transparent?

**Comment by mharrisweb** [comment]
@galbenyosef How would I pass params from each Stack to Drawer?

Using  `this.props.navigation.navigate("VideoPlayer", { video: video });`

When I try to get params in my component, I get undefined:

```
  this.state = {
      video: this.props.navigation.state.params.video
  ;
```

**Comment by galbenyosef** [comment]
> @galbenyosef How would I pass params from each Stack to Drawer?
> 
> Using `this.props.navigation.navigate("VideoPlayer", { video: video });`
> 
> When I try to get params in my component, I get undefined:
> 
> ```
>   this.state = {
>       video: this.props.navigation.state.params.video
>   ;
> ```

I usually don't use props for navigation but 'NavigationService', take a look at:
https://reactnavigation.org/docs/en/navigating-without-navigation-prop.html

Initial your desired stacks with reference into NavigationService, then you can select exactly which navigation should make an action,

**Comment by mharrisweb** [comment]
@galbenyosef thanks for the reply. I can navigate using the service, but I still can't pass params, they appear undefined. Are my stacks the problem?

**Comment by galbenyosef** [comment]
> @galbenyosef thanks for the reply. I can navigate using the service, but I still can't pass params, they appear undefined. Are my stacks the problem?

Inside your NavigationService, you can create getNavigation function which returns navigator.navigation,
you should then try getNavigation().getParam(paramName, defaultValue),
or as you supposed getNavigation().state.params

**Comment by mharrisweb** [comment]
> > @galbenyosef thanks for the reply. I can navigate using the service, but I still can't pass params, they appear undefined. Are my stacks the problem?
> 
> Inside your NavigationService, you can create getNavigation function which returns navigator.navigation,
> you should then try getNavigation().getParam(paramName, defaultValue),
> or as you supposed getNavigation().state.params

Great thanks, I rolled my own it might not be perfect but it works:

```
function getParams() {
	const {
		nav: { index, routes }
	} = _navigator.state;

	const params = routes[index].params;
	return params;
}
```

**Comment by YOEL311** [comment]
> In this case ,
> 
> According to the [official docs](https://reactnavigation.org/docs/en/drawer-navigator.html) you have to create a stack navigator for each drawer item then you'll be able to set the header for every drawer Item.
> 
> Here is my code example:
> 
> 1- Global app routes: RouteConfigs.js
> 
> 
> const DrawerNavigatorConfig = {
>     contentComponent: (props) => <AppDrawer {...props} />,
>     drawerType: 'slide',
>     initialRouteName: "Home",
>     mode: 'modal'
> } 
> 

> 
> Regards
> Mustapha GHLISSI.

Goodbye My friend
A nice solution but when I put this line the program gets stuck with all kinds of errors


const DrawerNavigatorConfig2 = {
  contentComponent: (props) => <AppDrawer {...props} />,/this line create error
  mode: 'modal',
  intialRouteName: 'DetailsScreen',
  drawerType: 'slide',
}


![image](https://user-images.githubusercontent.com/39925212/72929658-f5e90580-3d62-11ea-8ee6-49fba5943287.png)
![image](https://user-images.githubusercontent.com/39925212/72929686-01d4c780-3d63-11ea-907f-5b2c199fffe1.png)
![image](https://user-images.githubusercontent.com/39925212/72929720-0f8a4d00-3d63-11ea-9d6e-6d59103c79ed.png)
![image](https://user-images.githubusercontent.com/39925212/72929752-1b760f00-3d63-11ea-8477-1022a8405e01.png)
![image](https://user-images.githubusercontent.com/39925212/72929770-2466e080-3d63-11ea-990d-c8ffaf98f0f6.png)
![image](https://user-images.githubusercontent.com/39925212/72929788-2d57b200-3d63-11ea-8e24-4ff9ee6af363.png)

**Comment by inspire22** [comment]
This is still an issue and confusing new users like me.  If drawer-navigator only works as a nested navigator the docs should say so.

**Comment by embray** [comment]
I do find it a bit strange that drawernavigator screens can's also just have headers.

**Comment by rvirani1** [comment]
Yeah, I took like half a day to figure out this super common thing. The example should essentially only show a drawer navigator rendering stack navigator.

**Comment by MatthieuCoder** [comment]
Just for the record, you can do this now since dbe961ba5bb243e8da4d889c3c7dd6ed1de287c4 with the headerShown option

**Comment by intergalacticspacehighway** [comment]
@embray In the latest version of Drawer Navigator ^5.11.4, I am able to do it by passing screenOptions={{ headerShown: true }} in the navigator.
