### ISSUE TITLE
Nested StackNavigator inside DrawerComponent behavior changed bewteen beta.9 and beta.10

### ISSUE THREAD

**Issue by clint42** [react-community/react-navigation#1637]
I have 3 screens in the DrawerNavigator, 2 of them are actually the same StackNavigator containing a WebWrapperScreen.
With beta.9, when switching from the drawer menu between the 2 WebView items, the screen was not reloaded.
With beta.10, every time we switch between WebScreen1 and WebScreen2, the screen is reloaded.

I am not sure which behavior you are trying to achieve (beta.9 or beta.10).
If beta.10 behavior is correct, is there any workaround to achieve my goal (having multiple items in a drawer menu relying on the same StackNavigator and not reloading every time we switch between each other ?

Here is the relevant part of my code:
```const StackNavigatorDrawerItemFactory = (screen, screenName, title) => {
  return StackNavigator({
    [screenName]: {
      screen: screen,
      navigationOptions: {
        title: title,
      }
    }
  }, {
    navigationOptions: ({ navigation }) => ({
      headerLeft: (
        <TouchableOpacity style={{marginLeft: 10}} onPress={() => {
          navigation.navigate('DrawerOpen');
        }}>
          <Icon name="home" size={40} />
        </TouchableOpacity>
      ),
    })
  });
};

const WebViewStackNavigator = StackNavigatorDrawerItemFactory(WebWrapperScreen, 'WebWrapperScreen', 'WebView');
const HomeStackNavigator = StackNavigatorDrawerItemFactory(HomeScreen, 'HomeNavigator', 'HomeScreen');

const LoggedInNavigator = DrawerNavigator({
  HomeScreen: {
    screen: HomeStackNavigator,
  },
  WebScreen1: {
    screen: WebViewStackNavigator,
    navigationOptions: {
      title: 'WebView 1',
    },
  },
  WebScreen2: {
    screen: WebViewStackNavigator,
    navigationOptions: {
      title: 'WebView 2',
    },
  },
});```

**Comment by faceyspacey** [comment]
Personally I find the DrawerNavigator the least important and least polished aspect of this very import library. I would simply use the `contentComponent` option to create your own menu, and then trigger redux actions which trigger state changes which a standard screen can respond to. I.e. just have one screen for your DrawerNavigator, such as a TabNavigator. And then on the first tab of that TabNavigator, put a basic screen that perhaps has a nested (but disconnected) StackNavigator that responds to the actions you dispatch. Boom. done.

I've found that trying to force perfect nesting of all these navigators to be problematic. However, if you learn to use the navigators individually (aka "disconnected"), you have a lot more control and can idiomatically pull off what you need. Of course, if the nested navigator family thing they are going for worked for every use case, that would be the most idiomatic. But I'm finding too many holes in it.

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
