### ISSUE TITLE
How can I enable gestures on the entire screen

### ISSUE THREAD

**Issue by mazing** [react-community/react-navigation#1638]
I have found `gesturesEnabled`, but I can only swipe in the left-most part of the screen to activate `goBack()`.

How can I enable this gesture on the entire screen?

**Comment by computist** [comment]
+1
Trying to make swipe-back work when swiping in the middle of the screen in a decent way. Any suggestions?

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
