### ISSUE TITLE
expose component props to navigationOptions callback

### ISSUE THREAD

**Issue by thebigredgeek** [react-community/react-navigation#1639]
It seems bizarre to me that a component's props aren't accessible per-instance by a `navigationOptions` static function.  If I want to dispatch an action via `@connect`, make a query via `@graphql`, etc... I can't.  This makes the nav bar incredibly limiting IMO.  Is there a plan to add support for this?

**Comment by pfeiffer** [comment]
You can set the options of the navigation bar from your component (eg. `componentDidMount` or other lifecycle methods). See https://reactnavigation.org/docs/navigators/navigation-prop#setParams-Make-changes-to-route-params

Eg.

```js
componentDidMount() {
   this.props.navigation.setParams({ dispatch: this.props.dispatch, .. });
}

**Comment by pfeiffer** [comment]
Also be sure to check out this add-on: https://github.com/satya164/react-navigation-addons#navigationsetoptions

**Comment by thebigredgeek** [comment]
Perhaps I am misunderstanding, but I don't see how `setParams` helps me.  I don't need to set route params.  I need the `headerRight` button to call a method that is passed as `props` to my component.

**Comment by thebigredgeek** [comment]
Are you suggesting that I manually pass the method via params, and then have the button reference said method?  Is that safe?  I'd worry about memory leaks etc.

**Comment by thebigredgeek** [comment]
Also, `setParams` doesn't seem to re-run the `navigationOptions` callback :(

**Comment by vonovak** [comment]
@thebigredgeek the linked addon should work. otherwise you can use `static navigationOptions = ({ navigation, screenProps }) => ({ })` and get the params you need via `navigation.state.params.paramKey`

**Comment by thebigredgeek** [comment]
linked addon?

**Comment by vonovak** [comment]
@thebigredgeek the one from pfeiffer's comment, but probably better is the link from my comment

**Comment by matt-oakes** [comment]
I solved this by using a component in the header which is connected to redux and can get the properties itself. I would rather by able to access the props of the screen component though, but I understand this is less efficient as it will need to recalculate each time the props of the screen changes.

**Comment by migueloller** [comment]
The `setParams` hack doesn't work. Right now you have to do something like:
```js
static navigationOptions = ({ navigation: { state: { params } } }) => ({
  title: params ? params.title : '`params` is undefined on first render',
})

componentDidMount() {
  const { navigation: { setParams }, title } = this.props
  setParams({ title })
}

componentWillReceiveProps(nextProps) {
  const { navigation: { setParams }, title } = nextProps
  setParams({ title })
}
```
`params` is undefined in that first render, and on top of that, there will be an infinite loop as every time the component receives the new props `componentWillReceiveProps` will run again, and again, and again. Given this, this can't be used to modify `navigationOptions` based on the props.

It would be optimal to be able to do something like:
```js
static navigationOptions = ({ ownProps: { title } }) => ({ title })
```
This seems like it would be a very common use case that should be supported.

Currently, it seems that the only option is to pass the required props through `screenProps` but then every single screen in the router will see these props. It would also break the separation of props per component if say, you're passing the title through Redux. Instead of connecting each screen and passing `title`, you would have to pass `screenProp` with a `connect` at the router level with something like `{ screenProps: { screen1Title: 'foo', screen2Title: 'bar' } }`.

**Comment by thebigredgeek** [comment]
^ Yup, you have to do a null pointer check :(

**Comment by fabriziomoscon** [comment]
I am not 100% sure I am referring to the same issue, but I was able to connect my redux store to the `static navigationOptions` using `screenProps` as explained here: https://reactnavigation.org/docs/navigators/stack#Navigator-Props
I am using `"react-navigation": "^1.0.0-beta.11"`

```
<AppNavigator
                ref={nav => { this.navigator = nav; }}
                navigation={addNavigationHelpers({
                    dispatch: this.props.dispatch,
                    state:    this.props.navigator,
                })}
                screenProps={{
                    contactSearchText:    this.props.contactSearchText,
                    contactSearchVisible: this.props.contactSearchVisible,
                    resetSearchText:      this.props.resetSearchText,
                    toggleContactSearch:  this.props.toggleContactSearch,
                    contactSearch:        this.props.contactSearch,
                }}
            />
```

```
static navigationOptions = ({navigation, screenProps}) => {
        return {
            title: 'Contacts',
            headerTitle: (
                <ContactSearch
                    onSearchUpdated={screenProps.contactSearch}
                    contactSearchVisible={screenProps.contactSearchVisible}
                    searchText={screenProps.contactSearchText}
                    resetSearchText={screenProps.resetSearchText}
                />
            ),
            headerRight: (
                <TouchableOpacity
                    style={styles.searchContainer}
                    onPress={() => {
                        screenProps.toggleContactSearch(screenProps.contactSearchVisible)
                    }}
                >
                    <MaterialIcon style={[baseStyle.navigationSearch, {color: colors.white}]} name="search" />
                </TouchableOpacity>
            ),
        }
    }
```

**Comment by matt-oakes** [comment]
@fabriziomoscon That solution will work, but you'll pass those screenProps to every screen in the app, which isn't ideal in some cases.

**Comment by kelset** [comment]
Pinging OP @thebigredgeek since this issue is quite old and related to an old version of the lib. If no answer I'll close in 7 days.

Moreover, the proposed solutions seem viable to me.

**Comment by kelset** [comment]
Hi there @thebigredgeek ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.

**Comment by iwarshak** [comment]
@migueloller I got the same infinite loop that you mentioned in your comment. What I can't figure out is *why* calling `setParams` from `componentWillReceiveProps` will cause `componentWillReceiveProps` to be called again. Any clue?

**Comment by migueloller** [comment]
@iwarshak, it's because `setParams` causes a new set of props to be passed. It's like calling `setState` on render without any conditionals, you'll get an infinite loop on render.
