### ISSUE TITLE
How does this compare/differ from react-native-navigation 

### ISSUE THREAD

**Issue by indivisable** [react-community/react-navigation#164]
Hey @react-community great release, look forward to trying it out. Could anyone help explain how this differs from https://github.com/wix/react-native-navigation? I have come to enjoy using this library and the performance is great. 

Is this new react-navigation using JS or Native navigation implementations?

Thanks!

**Comment by sibelius** [comment]
u can check Hybrid example, it allows u to have some views written in native code and some views written in react native

**Comment by grabbou** [comment]
I remember there was a good explanation in the past on why to favour javascript over native implementations. Anyways, I think the biggest difference is that `wix` is native, whereas this solution is JS only. 

Maybe someone could send a PR to the docs adding the rationale `why not native`?

@ericvicenti

**Comment by sibelius** [comment]
@grabbou this post https://blog.getexponent.com/good-practices-why-you-should-use-javascript-whenever-possible-with-react-native-26478ec22334#.ri5kr0por by @brentvatne could help
