### ISSUE TITLE
Suggestion: Flow type NavigationParams change.

### ISSUE THREAD

**Issue by Palisand** [react-community/react-navigation#1640]
### Current Behavior
Flow will report an error when passing a non-string value for params.

Since there doesn't seem to be a way to directly pass params when using `navigation.goBack`, I have resorted to passing a function on `navigate` to invoke a state change on the previous route:

``` javascript
import type {NavigationScreenProp} from "react-navigation/src/TypeDefinition";

class CompForScreen1 extends Component {

  props: {
    navigation: NavigationScreenProp<*, *>
  }

  onSomeAction = (someValue) => {
    this.setState({ stateValue: someValue })
  };

  navigateToScreen2 = () => {
    this.props.navigation.navigate("Screen2", {onSomeAction: this.onSomeAction})
    //                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    // Flow: arrow function. This type is incompatible with the expected param type of string
  };

  ...
}

class CompForScreen2 extends Component {

  onSomeAction = (someValue) => {
    this.props.navigation.state.params.onSomeAction(someValue);
    this.props.navigation.goBack();
  };

  ...
}
```

The type definition of `NavigationScreenProp` says that the second parameter of [`navigate`](https://github.com/react-community/react-navigation/blob/master/src/TypeDefinition.js#L334-L338) (the `params`) must be of type `NavigationParams`, which is [defined as](https://github.com/react-community/react-navigation/blob/master/src/TypeDefinition.js#L171-L173) `[key: string]: string`.

### Expected Behavior
NavigationParams values should not be limited to strings.

### Environment
| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.9
| react-native     |  0.43.2

**Comment by mikelambert** [comment]
This should now be fixed by the change that was merged above, if you @Palisand (or @skevy) would like to close this issue.

**Comment by Palisand** [comment]
Yay
