### ISSUE TITLE
Drawer width not updated when device orientation locked

### ISSUE THREAD

**Issue by droms** [react-community/react-navigation#1641]
### Current Behavior
Drawer width set based on initial orientation. Locking orientation from landscape to portrait or portrait to landscape doesn't force the drawer width to be updated. 

App started in landscape then forced into portrait. Drawer width remains as if still in landscape

![image](https://cloud.githubusercontent.com/assets/23471971/26334298/a865e1f6-3f96-11e7-9bde-93d3116cebaa.png)

Should look like this

![image](https://cloud.githubusercontent.com/assets/23471971/26334302/b09df1b0-3f96-11e7-8df1-df1f59649965.png)

### Expected Behavior
Drawer width should be recalculated on orientation change.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  from repo
| react-native     |  0.44.0
| react-native-orientation | from repo

**Comment by andreiciceu** [comment]
I confirm this issue. Have you found any way to fix it?

**Comment by dann1609** [comment]
I have the same Issue. I fix it using `import { StyleShee } from 'react-native'; <NavigationView style={StyleSheet.absoluteFill}/>`

**Comment by davepack** [comment]
This is fixed in #2773 :-)
