### ISSUE TITLE
When I click on tabbar, Can I reload each time？

### ISSUE THREAD

**Issue by LCJ-MinYa** [react-community/react-navigation#1643]
I have TabNavigator,But when I click tabs, Only the first can get componentDidMount，If I want to get it every time, What should I do ?
Or when I click tab, Can I trigger the current method of this page?

**Comment by andyhuai** [comment]
I've the same question!

**Comment by MSchmidt** [comment]
Track https://github.com/react-community/react-navigation/issues/51 for this.

**Comment by spencercarli** [comment]
Closing in favor of #51
