### ISSUE TITLE
react navigation navigate to other screen

### ISSUE THREAD

**Issue by mynameisbams** [react-community/react-navigation#1644]
i try make login, when isLoggedIn = true ten navigate to 'Profile', but alaways give me error "undefined is not an object (evaluating '_this.props.navigation')". whats wrong with mycode? can someone help me?

    import React from 'react'
    import {
        Image,
        StyleSheet,
        Text,
        TextInput,
        TouchableOpacity,
        View
    } from 'react-native'
    //const styles_listContent = StyleSheet.flatten(styles.listContent);
    import { Field, reduxForm } from 'redux-form'
    import { Container, Content, InputGroup, Button , Input, Icon, Item } from 'native-base';
    import { login } from '../Action/Action';
    import {NavigationActions} from "react-navigation";
    import styles from './Style';
    //import { login } from './action'

    import { connect,  } from 'react-redux'

    // const submit = values => {
    //     //login: ()=> login(values.email)
    //     this.onLogin(values);
    //     console.log('submitting form', values)
    // }
    function submit(values) {
        console.log(values);

    }
    const renderInput = ({ input: { onChange, ...restInput }}) => {
        return <Input onChangeText={onChange} {...restInput} />
    }
    // _navigateTo = (routeName: string) => {
    //     const resetAction = NavigationActions.reset({
    //         index: 0,
    //         actions: [NavigationActions.navigate({routeName})]
    //     })
    //     this.props.navigation.dispatch(resetAction)
    // }
    const Form = props => {
        //const {navigate} = this.props.navigation;
        //let _navigateTo;
        if (props.appUser.isLoggedIn) {
            console.log("haloooo");
            const navigateAction = NavigationActions.navigate({
                routeName: 'Profile',
                params: {},
                action: NavigationActions.navigate({ routeName: 'SubProfileRoute'})
            })

            this.props.navigation.dispatch(navigateAction)
        }
        const { handleSubmit } = props
        //console.log(props.appUser);
        return (
            <Container >
                <Content>
                    <Content>
                        <View style={styles.container}>
                            <Image source={require('../Assets/Octocat.png')} style={{width: 128, height: 128}} />

                        </View>
                    </Content>
                    <Content style={{paddingLeft:10,paddingRight:10,paddingBottom:5, paddingTop:30}}>
                        <Item rounded>
                            <Field name="username" component={renderInput} />
                        </Item>
                    </Content>
                    <Content style={{paddingLeft:10,paddingRight:10}}>
                        <Item rounded>
                            <Field name="password" component={renderInput} />
                        </Item>
                    </Content>
                    <Content style={{padding:10}}>
                        <Button  onPress={handleSubmit(props.onLogin)} block info>
                            <Text>Login</Text>
                        </Button>
                    </Content>
                </Content>

            </Container>

        )
    }
    const myReduxForm = reduxForm({
        form: 'MyReduxForm', // required by reduxForm()
    //warn: (values, pFormrops) => { ... }, // optional
        //error: (values, props) => { ... } // optional
    })(Form)
    function mapStateToProps(state) {
        return {
            appUser: state.appUser,
            //email: state.email
        }
    }

    function mapDispatchToProps(dispatch) {
        return {
            onLogin: (data) => { dispatch(login(data)); },
            //login:()=>dispatch(login())
        }
    }
    export default connect(
        mapStateToProps,
        mapDispatchToProps
    )(myReduxForm)
    // export default reduxForm({
    //     form: 'test'
    // })(Form)
    // export default reduxForm({
    //     form: 'test'
    // })(Form)

**Comment by hellowin** [comment]
It's better to ask questions in Stackoverflow instead of GitHub issues.

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
