### ISSUE TITLE
Initial route params not passed to tab navigator

### ISSUE THREAD

**Issue by zash80** [react-community/react-navigation#1647]
Having a StackNavigator with 'initialRouteName' and 'initalRouteParams' where the initial route routes to a TabNavigator with tabs relying on the initial route parameter, this initial route parameter is not passed down to the tabs.

If the StackNavigator is re-configured to pass parameter via navigate action to the screen containing the TabNavigator all is working fine, means parameter is passed down to the tabs.

### Current Behavior
The parameters defined in StackNavigator 'initalRouteParams' are not passed down to a nested TabNavigator.

### Expected Behavior
The parameters defined in StackNavigator 'initalRouteParams' should be passed down to a nested TabNavigator.

### Code

```javascript
const SampleStack = StackNavigator({
  Screen1: {
    screen: SimpleScreen
  },
  Screen2: {
    screen: TabScreen
  }
}, {
  initialRouteName: 'Screen2',
  initialRouteParams: { name: 'value' }
});
```
```javascript
const TabScreen = TabNavigator({
  Tab1: {
    screen: SimpleTab
  },
  Tab2: {
    screen: TabRelyingOnParameters
  }
}, {
  tabBarPosition: 'bottom',
  tabBarComponent: MyTabBar
});
```
```javascript
TabRelyingOnParameters.navigationOptions =
  ({ navigation, navigation: { state: { params: { name } } } }) => ({
    header: (
      <Header>
        <Left>
          <Button onPress={() => navigation.goBack(null)} transparent>
            <Icon name='arrow-back' />
          </Button>
        </Left>
        <Body>
          <Title>{name}</Title>
        </Body>
        <Right />
      </Header>
    )
  }
);
```
### Environment

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.10
| react-native     |  0.44.0

**Comment by MrHubble** [comment]
What about adding the `initialRouteParams` as a config option to the TabRouter as per the StackRouter?

StackRouter:
![screen shot 2017-06-13 at 2 13 26 pm](https://user-images.githubusercontent.com/2251631/27065760-9db56e68-5042-11e7-82da-2435e53a48b9.png)

TabRouter:
![screen shot 2017-06-13 at 2 14 36 pm](https://user-images.githubusercontent.com/2251631/27065777-add19c36-5042-11e7-97f9-a27417218f80.png)

and then we could have `initialRouteParams` specific to TabNavigator:
````
const MyApp = TabNavigator({
  Home: {
    screen: MyHomeScreen,
  },
  Notifications: {
    screen: MyNotificationsScreen,
  },
}, {
  initialRouteParams: { foo: 'bar' }
});
````

**Comment by skevy** [comment]
@zash80 I think @MrHubble has a good point. Any reason you didn't go with that approach?

**Comment by RSSfeed** [comment]
Faced the same issue, this is what worked for me (sample code from my project, not matching your variable names and stuff - just to show its logic):

```
const Routes = {/*...*/};
const stackNavigatorDefaultNavigationOptions = {/*...*/};

export default class AuthNavigator extends React.Component
{
    static propTypes = {
        initialRouteName: PropTypes.string
    };

    static defaultProps = {
        initialRouteName: "Login"
    };

    componentWillMount()
    {
        this.Navigator = StackNavigator({
            Login: {
                screen: Routes.Login.screen
            },
            Register: {
                screen: Routes.Register.screen
            }
        }, {
            ...stackNavigatorDefaultNavigationOptions,
            initialRouteName: this.props.initialRouteName
        });
    }

    render()
    {
        const Navigator = this.Navigator;
        return <Navigator />
    }
}
```

So you can use this navigator like this:
```
<AuthNavigator initialRouteName="Register" />
```

**Comment by kelset** [comment]
Pinging OP @zash80 since this issue is quite old and related to an old version of the lib. If no answer I'll close in 7 days.

**Comment by kelset** [comment]
Hi there @zash80 ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.
