### ISSUE TITLE
gesturesEnabled not working well in 1.0.0-beta.10

### ISSUE THREAD

**Issue by cbjs** [react-community/react-navigation#1651]
set gestureEnabled to false, not working in 1.0.0-beta.10

**Comment by nihgwu** [comment]
please provide more information, I'm sure it works pretty well

**Comment by AdriaRios** [comment]
I don't know if it is the same problem, but I have problems too. In my case the gesture in modal mode does not works if the size of the Navigator is small (less than a half of the screen aprox):
```sh
<View style={{flex:1, backgroundColor: 'blue'}}>
          <View style={{flex:1, backgroundColor: 'red'}}>
          </View>
          <View style={{flex:1, backgroundColor: 'red'}}>
            <MyNavigator />
          </View>
        </View>
```

```sh
class HomeScreen extends Component {
  static navigationOptions = {
    title: 'Welcome',
    gesturesEnabled: true
  };
  render() {
    const { navigate } = this.props.navigation;
    return (
      <View>
        <Text>Hello, Chat App!</Text>
        <Button
          onPress={() => navigate('Chat')}
          title="Chat with Lucy"
        />
      </View>
    );
  }
}

class ChatScreen extends React.Component {
  static navigationOptions = {
    title: 'Chat with Lucy',
    gesturesEnabled: true
  };
  render() {
    return (
      <View>
        <Text>Chat with Lucy</Text>
      </View>
    );
  }
}

export default  MatchesNavigation = StackNavigator({
  Home: { screen: HomeScreen },
  Chat: { screen: ChatScreen }
},{
    mode: 'modal',
    headerMode: 'none'
  });
```

**Comment by nihgwu** [comment]
@AdriaRios in modal mode, gesture only works when starting move less then 135 in vertical https://github.com/react-community/react-navigation/blob/master/src/views/CardStack.js#L93

**Comment by TimbreApp** [comment]
@nihgwu 
Do you have any idea how to change that? I've been trying to change the gesture respond distance on both card stacks, and modal stack to no avail. How would one simply go about that?

Thanks

**Comment by AdriaRios** [comment]
@nihgwu Can I ask why?

In my honest opinion I think that this behaviour should work always, without consider the size. Can be a normal thing to get a navigator inside another navigator with diferent sizes

**Comment by nihgwu** [comment]
@TimbreApp I'm planning to send a PR to make gesture responder configurable

**Comment by TimbreApp** [comment]
@nihgwu If you do so the world will be a better place. I feel like this is an issue a lot of people are facing along with gesturesEnabled and the whole modal direction thing.

**Comment by nihgwu** [comment]
@AdriaRios I think you'd better you create your own Transitioner

**Comment by AdriaRios** [comment]
@nihgwu 
In my opinion, this is a bug. There aren't a strong reason to restrict the gesture area, at least it should be configurable.

**Comment by nihgwu** [comment]
@AdriaRios You can take it as a bug, but IMO it's a feature that could be implemented and I'm planning to do that

**Comment by AdriaRios** [comment]
Ok @nihgwu I'll take a look to the transitioners.

Thanks

**Comment by kelset** [comment]
Pinging OP @cbjs since this issue is quite old and related to an old version of the lib. If no answer I'll close in 7 days.

**Comment by kelset** [comment]
Hi there @cbjs ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.
