### ISSUE TITLE
React Navigation modal 'direction' not working. Instead is just defaulting to bottomToTop(default).

### ISSUE THREAD

**Issue by TimbreApp** [react-community/react-navigation#1652]
Hey I was testing out the direction prop for modal navigators and it doesn't seem to be working as intended. Even though I specified a direction prop, it still defaults to the modal default. 

'use strict'

import { StackNavigator } from 'react-navigation'

// Screens
import LibraryTabScreenOne from './views/LibraryTabScreenOne'
import LibraryTabScreenTwo from './views/LibraryTabScreenTwo'
import LibraryTabScreenThree from './views/LibraryTabScreenThree'

const routeConfiguration = {
  LibraryTabScreenTwo: { screen: LibraryTabScreenTwo },
  LibraryTabScreenOne: { screen: LibraryTabScreenOne },
  LibraryTabScreenThree: { screen: LibraryTabScreenThree },
  
}

const stackNavigatorConfiguration = {
  mode: 'modal',
  direction: 'topTopBottom',
  //headerMode: 'none',
  initialRouteName: 'LibraryTabScreenOne'
}

export const NavigatorLibraryTab = StackNavigator(routeConfiguration,stackNavigatorConfiguration)

**Comment by spencercarli** [comment]
`direction` isn't a supported config option currently

**Comment by anonrig** [comment]
So, what's the correct way of changing the direction of the modal @spencercarli ?
