### ISSUE TITLE
Pass props with reset navigation action

### ISSUE THREAD

**Issue by nazywamsiepawel** [react-community/react-navigation#1653]
Dear All,

I am currently working with a StackNavigator, let it be of structure A->B->C.

The last screen in the stack is navigating back to the initial screen, A, after a certain action has been completed. I would like to pass props back to screen A.

For now I use the following code to reset and get back to the initial screen of the stack :

```
  const resetAction = NavigationActions.reset({
      index: 0,
      actions: [
        NavigationActions.navigate('ScreenA'),
      ],
    });
    
    this.props.navigation.dispatch(resetAction);
```

I would like to extend it to pass custom props to initial screen A or find a better way method of doing it. How should I approach that?

**Comment by faceyspacey** [comment]
If the action in the array has a `params` key, they will be passed to `ScreenA`. `NavigationActions.navigate` has built in support for this feature:

https://reactnavigation.org/docs/navigators/navigation-actions#Navigate

Here's how it's done in your case:

```js
const resetAction = NavigationActions.reset({
      index: 0,
      actions: [
        NavigationActions.navigate({ routeName: 'ScreenA', params: { foo: 'bar' } }),  
      ],
    });
```

If for some reason that doesn't work for you, use Redux state and anything stored there is available to connected components you use anywhere.

**Comment by nazywamsiepawel** [comment]
Thanks @faceyspacey!

**Comment by Tom29** [comment]
@faceyspacey I've tried it but didn't work.

`NavigationActions.navigate({ routeName: 'Parent', params: {catId: 12} })`

then inside `componentWillMount`
`console.log(this.props.navigation.state.params)` , it's undefined

**Comment by sawwy** [comment]
Hi,

I am using the above method to reset my navigation stack but I have a case where I need to define 5 levels of navigation with index: 4 -> the render looks very messy as it scrolls through 5 screens. Is there a better way to come back, let's say, from index 7 to index 4? The main problem of getting the back button working correctly to navigate the Screen hierarchy rather than screen history is tackled with above but I just don't like the unprofessional look of it. Am I possibly using the reset action wrong?

**Comment by kelset** [comment]
Closing since solution proposed by @faceyspacey solved it for OP.

**Comment by RoyalDeveloper2015** [comment]
how can I access the redux params on Navigation options ?

**Comment by manojbhardwaj** [comment]
@faceyspacey how can i get the paramsvalue on ScreenA

**Comment by hlbp** [comment]
im having the same problem but with the navigate property. the second screen is not taking any props from the first one. @nazywamsiepawel  how did you fix it?

**Comment by pacozaa** [comment]
Can't get props with reset as well

**Comment by dramalcolm** [comment]
This works for me

this.props.navigation.setParams({foo:null});
