### ISSUE TITLE
How to change GESTURE_RESPONSE_DISTANCE_HORIZONTAL / The gesture respond distance?

### ISSUE THREAD

**Issue by TimbreApp** [react-community/react-navigation#1655]
Anyone know a simple way to change the gesture response distance? I'm pretty sure this information would help EVERYONE using react-navigation as the default response distance for card stacks is extremely small.

I'm looking at the docs here:
https://github.com/react-community/react-navigation/blob/master/src/views/CardStack.js

And I've tried editing using:

CardStyle : { GESTURE_RESPONSE_DISTANCE_HORIZONTAL: 50 }

AND

Navigation Options: {
    CardStack: {
       GESTURE_RESPONSE_DISTANCE_HORIZONTAL: 50,
       RESPOND_THRESHOLD: 30,
    }
}

**Comment by jmparsons** [comment]
I'm looking for this as well. The `gestureResponseDistance` is just hardcoded right now. Really would like full screen or the option to increase the gesture distance for both modal and card stacks.

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
