### ISSUE TITLE
Is it possible to put two tabs (linking to different screens) in an iOS stacknavigator header for the title?

### ISSUE THREAD

**Issue by gregblass** [react-community/react-navigation#1656]
I'm trying to add tabs to the header of an iOS stack navigator (instead of the title/where the title is), each linking to different screens.

![tabs-example1](https://cloud.githubusercontent.com/assets/279927/26362296/7ff60b6e-3fab-11e7-9e65-4a2ea4c3e317.jpg)

![tabs-example2](https://cloud.githubusercontent.com/assets/279927/26362297/80061e78-3fab-11e7-81d5-2c7dc4f4c978.jpg)

I'd like to have two tabs (in the style of the first example) right where my title is circled in the 2nd example.

Is this possible out of the box using react navigation? I don't see anything in the docs. Or, has anyone successfully implemented this on their own?

**Comment by gregblass** [comment]
So far I’m thinking the way to go would be to a implement a custom tab component and pass that in as the header for that screen https://github.com/react-community/react-navigation/blob/master/examples/NavigationPlayground/js/CustomTabs.js

**Comment by faceyspacey** [comment]
it says the `headerTitle` option here: https://reactnavigation.org/docs/navigators/stack can take a react component. So perhaps you can replace the title without having to replace the whole `header`. But if worse comes to worse, it seems you have to replace the entire `header`, which would mean losing individual animations of the elements of the header (but that's likely fine).

**Comment by gregblass** [comment]
Here's the solution I came up with incase anyone finds this in the future:

https://gist.github.com/gregblass/e0190e99bddefd3dd41b14a6f53c2ccf
