### ISSUE TITLE
StackNavigator cannot be delcared as a screen of a TabRouter

### ISSUE THREAD

**Issue by tiaaaa123** [react-community/react-navigation#1661]
Hi! Having difficulties using `react-navigation` and understanding the difference between Navigators and Router...

My objective is to make a custom TabBar which each of the tab is a Stack Navigation.
From what I read, you have to use a TabRouter to make a custom TabBar (because TabNavigator doesn't have the props for it). 

The problem it says is that I can't put a StackNavigator as a screen of the TabRouter :
`Route 'Dashboard' should declare a screen, For example:...`

```
const Main = StackNavigator({
  Dashboard: Dashboard,
}, { initialRouteName: 'Dashboard' });


const Tabs = TabRouter(
  {
    Main: {
      screen: Main,
    },
  },
  {
    initialRouteName: 'Main',
    tabBarComponent: TabView.TabBarBottom,
    swipeEnabled: false,
    animationEnabled: false,
    backBehavior: 'none',
  },
);
```

Is it possible to have a StackNavigator as a screen of a TabRouter?
Because it is possible to pub a tabRouter in a DrawerNavigator...
What am I doing wrong?

**Comment by EslamNasser** [comment]
Try this:
`
const Main = StackNavigator({
  Dashboard: Dashboard,
}, { initialRouteName: 'Dashboard' });


const Tabs = TabRouter(
  {
    Main: {
      screen: (navigator) => < Main/>,
    },
  },
  {
    initialRouteName: 'Main',
    tabBarComponent: TabView.TabBarBottom,
    swipeEnabled: false,
    animationEnabled: false,
    backBehavior: 'none',
  },
);
`
I've the same setup in an application and using it that way works fine. One thing to consider tho is to put the other navigator in a separate component to make it easy for you to send props and use them (i.e the main navigator's props).

**Comment by tiaaaa123** [comment]
It works! However, my screen (Main) which is a StackNavigator does not show any navBar.
Do I need, in the code below, to manually add a navBar for my stack navigation (because I manually create a navigator with the tabRouter)?

```
const Tabs = TabRouter(
  {
    Main: {
      screen: StackNavigator({
        Dashboard: { screen: Dashboard, title: 'Dashboard' },
        Wallet: { screen: Wallet },
        Deck: { screen: Deck },
        EnterpriseProfile: { screen: EnterpriseProfile },
      }, {
        initialRouteName: 'Dashboard',
      }),
    },
  },
  {
    initialRouteName: 'Main',
    swipeEnabled: false,
    animationEnabled: false,
    backBehavior: 'none',
  },
);

const CustomTabView = ({ router, navigation }) => {
  const { routes, index } = navigation.state;
  const ActiveScreen = router.getComponentForState(navigation.state);

  return (
    <View style={{ flex: 1, marginTop: Platform.OS === 'ios' ? 20 : 0 }}>
      <ActiveScreen
        navigation={addNavigationHelpers({
          ...navigation,
          state: routes[index],
        })}
      />
      <View style={styles.tabContainer}>
        {routes.map(route => (
          <TouchableOpacity
            key={route.routeName}
            onPress={() => navigation.dispatch({ type: 'Navigation/BACK' })}
          >
            <TabItem
              count={2}
              countBackgroundColor={Colors.accent}
              isSelected
              title="dashboard"
            />

          </TouchableOpacity>
        ))}
      </View>
    </View>
  );
};

const TabBar = createNavigationContainer(createNavigator(Tabs)(CustomTabView));

export default TabBar;
```

From what I understood from `react-navigation`, the `TabNavigator` is a pre-made tabBar different for Android and iOS. If you want to make a custom TabBar (for example, with `linear gradient` background and notification on items), you need to create your own navigator with a `TabRouter` and you add the TabBar the way you like it. Do we also need to add the custom navBar?

**Comment by skizzo** [comment]
@tiaaaa123 Did you ever manage to solve this? Running into the same problem.. Switched my `TabNavigator` with a `TabRouter` any now the navigation bars of my screens are gone.

**Comment by tiaaaa123** [comment]
@skizzo  I dropped `react-navigation` back to `ex-navigation`. It's too early to use `react-navigation` if you want something a little bit customize. Right now, it's just for plain traditional app.
Probably not the answer you wanted to hear, but it's an honest one. Sorry :/

**Comment by kelset** [comment]
Closing since it was a question, basically, and OP moved away from the lib (there are examples in the README about how to achieve nested/complex solutions).
