### ISSUE TITLE
True native navigation

### ISSUE THREAD

**Issue by braco** [react-community/react-navigation#1664]
Is there any plan to support true native navigation a la (or via) airbnb/native-navigation? Trying to make some decisions and the navigation field seems pretty scattered still.

@ericvicenti, I read [your piece](https://medium.com/@ericvicenti/playing-with-react-navigation-and-airbnbs-native-navigation-4e49fc765489) – do you have any insight?

**Comment by mruba** [comment]
we are facing the same decisions btw react navigation and react native navigation seems to be stable https://github.com/wix/react-native-navigation

**Comment by braco** [comment]
wix/navigation isn't stable, all of the development has been poured into a dev 2.0 branch. There are huge feature gaps and bugs in the 1.0 branch, and [some deeper issues](https://github.com/airbnb/native-navigation/issues/114#issuecomment-303508544)

**Comment by vonovak** [comment]
@ericvicenti imo, the community and react native folks should now focus to get react-navigation working well even though it has the drawback of having some imperfections. So far we have seen development jump from Navigator to NavigationExperimental, ex-navigation, and other 3rd party navigators without bringing one to stability (ex-navigation got farthest).

Now, looking at the medium post, I see you're unhappy about the fact that react-navigation is completely in JS? It was clear from the beginning that it will only approximate the native animations, and that is ok! **The community now needs a navigator that works and is stable, not more demos of how great things may become in future.**

**Comment by matt-oakes** [comment]
[This post](https://medium.com/@ericvicenti/playing-with-react-navigation-and-airbnbs-native-navigation-4e49fc765489) by @ericvicenti might be interesting. It shows how `react-native-navigation` can be used as the navigation implementation with `react-navigation` as the interface for it. Only a demo for now, but promising and provides a nice migration path for the future.

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
