### ISSUE TITLE
question: why is there a `paths` options to the StackNavigator?

### ISSUE THREAD

**Issue by faceyspacey** [react-community/react-navigation#1665]
You already can set all the paths when you define the screens, so it's not like you're re-using imported `routeConfigs` whose paths you may want to change. 

What am I missing for the reason that there is 2 ways to set the paths?

**Comment by spencercarli** [comment]
I really don't think there's much of a reason to it other than, technically, objects don't have an order whereas arrays do?

Though a good question I'm going to close this to try to clean up issues. Thanks!

**Comment by ckeeney** [comment]
At the very least, it lets you have multiple paths mapping to the same screen.  This is useful, for example, if maybe you have a blog or news site and you may have `/` and `/category/:catName` both render a list of posts and reuse the same screen.
