### ISSUE TITLE
Header title image not working on android

### ISSUE THREAD

**Issue by vinhtq** [react-community/react-navigation#1666]
When i set image for header on android seems it does not working.

```
Home: {
    screen: Home,
    navigationOptions: ({ navigation }) => ({
      title: <Image source={{ uri: 'http://unsplash.it/100x20' }} style={{width: 200, height: 20}} resizeMode="cover" />
      })
}
```

On iOS, everything is fine but on android the image is just 10 pixel width.

**Comment by CandyOgre** [comment]
@vinhtq I stuck with the same issue

**Comment by CandyOgre** [comment]
@vinhtq  use headerTitle instead of title. It works for me

**Comment by vinhtq** [comment]
@CandyOgre Thank you!

**Comment by CandyOgre** [comment]
@vinhtq You`re welcome!

**Comment by CandyOgre** [comment]
@vinhtq close issue maybe)

**Comment by ericlewis** [comment]
how do you do this per screen?

**Comment by valetarton** [comment]
@ericlewis 
use the "navigationOptions" per screen definition statically
OR
you can use dynamic configuration
https://reactnavigation.org/docs/navigators/navigation-options
on your component defined in your initial screen definition.

You can use both, however dynamic will overwrite your static configuration

**Comment by vonovak** [comment]
closing, as the original question was answered in the 3rd post.

**Comment by Gentlee** [comment]
It is a hack, because on ios setting title works, on andorid doesn't.

**Comment by zackify** [comment]
This is still a problem, can this be reopened? How can it be expected that you can do 

```
const OffersStack = createStackNavigator(
    {
      Offers,
    },
    {
      defaultNavigationOptions: {
       headerBackImage: BackIcon,
      },
    },
  );```

And it works on iOS but on Android it renders and tapping doesnt do anything?
