### ISSUE TITLE
How to custom key for route

### ISSUE THREAD

**Issue by nimengbo** [react-community/react-navigation#1669]
![image](https://cloud.githubusercontent.com/assets/6950107/26390859/eb6bc4a0-4092-11e7-9827-f8e827e9e18d.png)
I want to use `back` by key, And the key is random. 
what can i do ?

**Comment by dioxide** [comment]
i have a same problem

**Comment by nimengbo** [comment]
@skevy

**Comment by faisalil** [comment]
did you guys figure this out?

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!

**Comment by Laurensdc** [comment]
Still don't know how to set a key

**Comment by brentvatne** [comment]
cc @ericvicenti - we need some better docs around keys ;)

**Comment by mojtaba-hajishah** [comment]
any progress here? still don't know how to specify key.
I need to know the key to access a shared view across app and avoid multiple instances of that shared view.

**Comment by smitthakkar1** [comment]
any update on this ?

**Comment by brentvatne** [comment]
please create a new issue and provide info about what exactly you're trying to accomplish @smitthakkar1 :)
