### ISSUE TITLE
flow status returns error: Unused suppression

### ISSUE THREAD

**Issue by JuhQ** [react-community/react-navigation#1671]
### Current Behavior
When running `flow status`, react-navigation is giving this error:
```
node_modules/react-navigation/src/routers/__tests__/StackRouter-test.js:755
755:       /* $FlowFixMe */
           ^^^^^^^^^^^^^^^^ Error suppressing comment. Unused suppression

node_modules/react-navigation/src/routers/__tests__/StackRouter-test.js:822
822:       // $FlowFixMe
           ^^^^^^^^^^^^^ Error suppressing comment. Unused suppression
```

### Expected Behavior
Should not give an error.
I manually removed these comments and `flow status` passed without errors.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.9
| react-native     |  0.44.0
| node             | v7.3.0
| npm or yarn      | yarn version v0.23.4
| flow-bin      | 0.46.0

**Comment by JuhQ** [comment]
Same error given with version 1.0.0-beta.11

**Comment by pavloko** [comment]
I got the same error and removing the lines fixes it as well.

**Comment by matt-oakes** [comment]
I've just opened a PR with the fix and added a workaround into the PR description.

**Comment by matt-oakes** [comment]
The PR has been closed as the fix was not as simple as the one I made. There is a suggestion for a solution, but it doesn't sound like it will be implemented in the short term. For now, the workaround is to add this to your `.flowconfig` to suppress the errors:

```
[ignore]
; Ignore issues with react-navigation
.*/node_modules/react-navigation/src/routers/__tests__/StackRouter-test.js
```

**Comment by vonovak** [comment]
Given how old this issue is, I believe it was fixed by https://github.com/react-community/react-navigation/commit/d1c434b54c73b6ed17b1642acd6646fbca92c92e or even earlier. Feel free to reopen if that is not the case.
