### ISSUE TITLE
Reset action: two to one screens causes a back transition

### ISSUE THREAD

**Issue by nicgutierrez** [react-community/react-navigation#1672]
I'm resetting the stack navigation but I can't figure out how to disable the back transition. Here's the code I'm using:

````
const resetAction = NavigationActions.reset({
  index: 0,
  actions: [
    NavigationActions.navigate({ routeName: 'Profile'})
  ]
})

this.props.navigation.dispatch(resetAction)
````

There are two screens in the stack before resetting. There is only one screen in the new stack.
The fact that  the stack is at index 1 before resetting and then it goes to index 0 I think is causing a "back transition".

Am I doing this wrong? Or maybe there's a different way to do this? What i'm trying to achieve is to replace the stack, from two screens to only one without any kind of transition.

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.9
| react-native     |  0.44.0
| node             | 6.6.0
| npm or yarn      | 3.10.7

**Comment by faceyspacey** [comment]
Here's a concise proposal that will fix this in many other issues:

https://github.com/react-community/react-navigation/issues/1663

**Comment by spencercarli** [comment]
Look to #1663 for future discussion
