### ISSUE TITLE
Tabbar in another tabbar does not work in RNv0.43.3, "react-navigation": "1.0.0-beta.11"

### ISSUE THREAD

**Issue by LEEY19** [react-community/react-navigation#1674]
This issue happened when I upgraded to RN v0.43.3. I was using v0.40.0, with "react-navigation": "1.0.0-beta.7". Tabbar in another tabbar was working fine. However, problem arises when I upgraded to 0.43.3. I know that with this new RN, I had to upgrade react-navigation version as well. Hence I removed node_module files, re-ran npm install to get 1.0.0-beta.11 (latest). However, tabbar in a tabbar failed to work. None of the codes in the screens in the sub-tabbar are shown. I have validated that, when I reverted both the RN and react-navigation versions back to what they were, tabbar in a tabbar works again.

Do look into this issue, thanks!

**Comment by kelset** [comment]
Can you provide the code? There have been some breaking changes.

**Comment by rafaelmotta** [comment]
same problem here

**Comment by Mercury-Dai** [comment]
me too, I update react-navigation's version to 1.0.0-beta.11,my RN version is 0.42.0,then tabbar can't display

**Comment by keeleycarrigan** [comment]
Yea the code below works in 1.0.0-beta.9 but not in anything above.

```javascript
import React, { Component } from 'react';
import {
  Button,
  Platform,
  ScrollView,
  StatusBar
} from 'react-native';
import {
  StackNavigator,
  TabNavigator,
} from 'react-navigation';
import { NavigationComponent } from 'react-native-material-bottom-navigation';
import { DetectNavbar } from 'react-native-detect-navbar-android';

import Ionicons from 'react-native-vector-icons/Ionicons';
import SampleText from './sample-txt';

const MyNavScreen = ({ navigation, banner }) => (
  <ScrollView>
    <SampleText>{banner}</SampleText>
    <Button
      onPress={() => navigation.navigate('Profile', { name: 'Jordan' })}
      title="Go to a profile screen"
    />
    <Button
      onPress={() => navigation.navigate('NotifSettings')}
      title="Go to notification settings"
    />
    <Button
      onPress={() => navigation.navigate('SettingsTab')}
      title="Go to settings"
    />
    <Button
      onPress={() => navigation.navigate('Home')}
      title="Go to Home"
    />
    <Button
      onPress={() => navigation.goBack(null)}
      title="Go back"
    />
  </ScrollView>
);

const MyHomeScreen = ({ navigation }) => (
  <MyNavScreen
    banner="Home Screen"
    navigation={navigation}
  />
);

const MyHomeScreen2 = ({ navigation }) => (
  <MyNavScreen
    banner="Home Screen"
    navigation={navigation}
  />
);

const MyProfileScreen = ({ navigation }) => (
  <MyNavScreen
    banner={`${navigation.state.params.name}s Profile`}
    navigation={navigation}
  />
);
MyProfileScreen.navigationOptions = ({ navigation }) => ({
  title: `${navigation.state.params.name}'s Profile!`,
});

const MyNotificationsSettingsScreen = ({ navigation }) => (
  <MyNavScreen
    banner="Notification Settings"
    navigation={navigation}
  />
);

const MySettingsScreen = ({ navigation }) => (
  <MyNavScreen
    banner="Settings"
    navigation={navigation}
  />
);

const stackConfig = {};

if (Platform.OS === 'android') {
    stackConfig = {
        navigationOptions: {
            headerStyle: {
              paddingTop: StatusBar.currentHeight,
              height: 56 + StatusBar.currentHeight,
              elevation: 0
            }
        }
    };
}

const HomeTabs = {
    HomeTabOne: {
        screen: MyHomeScreen,
    },
    HomeTabTwo: {
        screen: MyHomeScreen2,
    }
};

const mainTabConfig = {
    ...TabNavigator.Presets.AndroidTopTabs,
    animationEnabled: true,
    swipeEnabled: true,
}

const MainTab = StackNavigator({
  Home: {
    screen: TabNavigator(HomeTabs, mainTabConfig),
    path: '/',
    navigationOptions: {
      title: 'Welcome',
    //   headerMode: 'none'
    },
  },
  Profile: {
    screen: MyProfileScreen,
    path: '/people/:name',
    navigationOptions: ({ navigation }) => ({
      title: `${navigation.state.params.name}'s Profile!`,
    }),
  },
}, stackConfig);

const SettingsTab = StackNavigator({
  Settings: {
    screen: MySettingsScreen,
    path: '/',
    navigationOptions: () => ({
      title: 'Settings',
    }),
  },
  NotifSettings: {
    screen: MyNotificationsSettingsScreen,
    navigationOptions: {
      title: 'Notification Settings',
    },
  },
}, stackConfig);


class StacksInTabs extends Component {
    constructor (props) {
        super(props);
        
        this.state = { softKeys: false }
    }
    
    componentDidMount () {
        if (Platform.OS === 'android') {
            DetectNavbar.hasSoftKeys().then((softKeys) => {
              this.setState({ softKeys });
            });
        }
    }
    
    render () {
        let tabBarConfig = {
          tabBarPosition: 'bottom',
          animationEnabled: false,
          swipeEnabled: false
      };
      
      if (Platform.OS === 'android') {
          tabBarConfig.tabBarComponent = NavigationComponent;
          tabBarConfig.tabBarOptions = {
              bottomNavigationOptions: {
                  style: {
                      height: this.state.softKeys ? 104 : 56
                  },
                  innerStyle: {
                      paddingBottom: this.state.softKeys ? 48 : 0
                  },
                  
              }
          }
      }
        const Tabs = TabNavigator({
          MainTab: {
            screen: MainTab,
            path: '/',
            navigationOptions: {
              tabBarLabel: 'Home',
              tabBarIcon: ({ tintColor, focused }) => (
                <Ionicons
                  name={focused ? 'ios-home' : 'ios-home-outline'}
                  size={26}
                  style={{ color: tintColor }}
                />
              ),
            },
          },
          SettingsTab: {
            screen: SettingsTab,
            path: '/settings',
            navigationOptions: {
              tabBarLabel: 'Settings',
              tabBarIcon: ({ tintColor, focused }) => (
                <Ionicons
                  name={focused ? 'ios-settings' : 'ios-settings-outline'}
                  size={26}
                  style={{ color: tintColor }}
                />
              ),
            },
          },
      }, tabBarConfig);

        return <Tabs />;
    }
}

export default StackNavigator({ Root: { screen: StacksInTabs } }, { headerMode: 'none' });
```

**Comment by LEEY19** [comment]
For my case, I first have a class called Facility that contains a tabnavigator called FacilityBooking:
`class Facility extends Component {
  static navigationOptions = {
    tabBar: {
      label: 'Facility Booking',
      icon: ({ tintColor }) => (
        <Image
          source={require('./../img/facility.png')}
          style={[styles.icon, {tintColor: tintColor}]}
        />
      ),
    },
  }

  render() {
    return <FacilityBooking screenProps={this.props.screenProps} />
  }
}`

FacilityBooking consists of two tabs:
`const FacilityBooking = TabNavigator({
  Facilities: {
    screen: Facilities,
  },
  "My Bookings": {
    screen: MyBookings,
  },
}, {
  tabBarPosition: 'top',
  tabBarOptions: {
    scrollEnabled: false,
    activeTintColor: '#d3004c',
    inactiveTintColor: '#708090',
    labelStyle: {
      fontSize: 13,
    },
    style: {
      backgroundColor: 'white',
    },
    indicatorStyle: {
      backgroundColor: '#d3004c'
    }
  },
});`

Then, Facility is contained within a bigger tabnavigator called App_navigator:
`const App_navigator = TabNavigator({
  Notice_Board: {
    screen: Forum1,
  },
  Notifications: {
    screen: Notif,
  },
  Facility_Booking: {
    screen: Facility,
  },
  Settings: {
    screen: Setting,
  },
}, {
  initialRouteName: "Notice_Board",
  tabBarPosition: 'bottom',
  swipeEnabled: false,
  tabBarOptions: {
    scrollEnabled: false,
    showIcon: true,
    activeTintColor: '#d3004c',
    inactiveTintColor: '#4682b4',
    showLabel: false,
    style: {
      backgroundColor: 'white',
    },
    indicatorStyle: {
      backgroundColor: '#d3004c'
    }
  },
});`

The FacililtyBooking tabnavigator failed to function.

**Comment by mathemagics** [comment]
Same issue here. Any progress?

**Comment by WaDoFa** [comment]
It  also  occurred to me

**Comment by veedeo** [comment]
Same here.
It works if main TabBar swipeEnabled: true and nested swipeEnabled: false,

**Comment by kelset** [comment]
In another issue @satya164 explained that you can't have 2 nested tabbar with `swipeEnabled:true` - and it make sense, 'cause it would be really hard to tell if the swipe is to change the outer tab or the inner.

That said, I think the way you could "try to work around that" is to use a [`react-native-tab-view`](https://github.com/react-native-community/react-native-tab-view); it's the same component used in navigation, from my understanding, but this way it wouldn't be attached to the navigation logic. It's a rough workaround but you may want/need to consider it.

**Comment by veedeo** [comment]
I upgraded react-native to latest ver "0.46.2" and it works as expected

**Comment by kelset** [comment]
Closing this because of my previous comment + newer version of lib & tab-view are out.

If you are still having the issue (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.
