### ISSUE TITLE
headerBackTitleStyle does not work

### ISSUE THREAD

**Issue by Tiendq** [react-community/react-navigation#1681]
### Current Behavior
`headerBackTitleStyle` does not change style of the back button e.g. color (`headerTintColor` only changes color of the title, not back button's title).

```
static navigationOptions = {
  headerTintColor: '#f00', // Change title color to red
  headerBackTitleStyle: styles.backTitle // Do nothing, it's still default blue color
}

const styles = StyleSheet.create({
  backTitle: {
    color: '#0f0'
  }
});
```

### Expected Behavior
`headerBackTitleStyle` changes style of the back button.

### Your Environment

RN 0.44.0
react-navigation 1.0.0-beta.9
iOS 10.x

**Comment by xght** [comment]
#1340
