### ISSUE TITLE
Header Title not getting updated 

### ISSUE THREAD

**Issue by anup1245** [react-community/react-navigation#1682]
### Current Behavior
The header does not update after calling this.props.navigation.setParams({title: 'Hello'})
How to update headerTitle, headerRight  dynamically.
this.props.navigation.setParams is not working

code:

class PostQuestionView extends Component<void, *, void> {
  constructor(props) {
    super(props)
    this.state = {
      title: '',
      message: '',
    }
  }

  static navigationOptions = () => {
    return {
      headerTitle: _t('Compose Post'),
    }
  }

  postThread = () => {
    this.props.navigation.setParams({headerTitle: 'Hello'})
  }

  render() {
    return (
        <Button
          title={'Post'}
          color="#007AFF"
          onPress={this.postThread}
        />
      </View>
    )
  }
}

export default compose(
  graphql(gql`
    //query
  `)
)(PostQuestionView)

### Expected Behavior
The title should update

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.9
| react-native     |  0.42.0

**Comment by JuhQ** [comment]
Why is this issue closed? I have similar problem with updating `title` with `setParams` function and this issue was the first result from google. Please reopen or give information how you fixed your issue.

**Comment by donnes** [comment]
@anup1245 Can you tell us how fixed the issue?
I'm having the same problem.

Thank you!

**Comment by jinghun1999** [comment]
What?? I have the same problem too. `static navigationOptions = ({navigation})=>({` I set title in the function doesn't work. the page is the TabNavigator page
