### ISSUE TITLE
navigator doesn't dispatch if setParams

### ISSUE THREAD

**Issue by cityvoice** [react-community/react-navigation#1683]
I want to pass params to component  when route page,but it doesn't work!
```
  toProfile(){
       const setParamsAction = NavigationActions.setParams({
		  params: { name: 'Hello' },
		  key: 'Profile',
        })
	this.props.navigation.dispatch(setParamsAction);//doesn't work
         this.props.navigation.dispatch({ type: 'Profile' };//works well
  }
```

reducers:
```
export default function nav(state = initialNavState, action) {
  let nextState;
  switch (action.type) {
  ...
    case 'Profile':
      nextState = AppNavigator.router.getStateForAction(
        NavigationActions.navigate({ routeName: 'Profile'}),
        state
      );
      break;
}
```
if i change the code to:
```
export default function nav(state = initialNavState, action) {
  let nextState;
  switch (action.type) {
      ...
      case 'Navigation/SET_PARAMS':
         nextState = AppNavigator.router.getStateForAction(
             NavigationActions.navigate({ routeName: action.key, params:action.params}),
            state
          );
	break;
}
```

it works ,but it's too ugly, do I miss something?Any suggestions will be appreciated!

**Comment by faceyspacey** [comment]
You did miss a few things. The `key` isn't always `Profile`. The `key` changes when you're using StackNavigator, as you can have the same route used multiple times with different parameters. Imagine a profile for Michael Jackson and another for Mark Zuckerberg. The keys will actually be something like `id-1495735912887-0` and `id-1495735912887-1`. Only for TabRouter--I think--does the key stay the same.

...So, if you are using a StackNavigator and if you are using `dispatch(NavigationActions.setParams(..))`, then you will need to look into the state for the navigator/router and find what the key is, perhaps via a thunk:

```js
dispatch((dispatch, getState) => {
   const { routerState } = getState()
   const activeRoute = routerState.routes[routeState.index]

   const action = NavigationActions.setParams({
        params: { name: 'Hello' },
	key: activeRoute.key,
    })

    dispatch(action)
})
```

...however, it's easier if you are calling this within the screen whose params you want to set. `addNavigationHelpers` automatically sets the key for `setParams`:

```js
const Profile = props => 
   <View>
      <TouchableOpacity onPress={() => props.navigation.setParams({ name: 'Hello' })} />
   </View>

const MyStack = StackNavigator({
    Profile: { screen: Profile }
}, options)
```

**Comment by cityvoice** [comment]
thanks for your answer, yes i use a StackNavigator, but still be confused, the relevant code in react-navigations/libs/NavigationActions.js:
```
var SET_PARAMS = 'Navigation/SET_PARAMS';
var createAction = function createAction(type) {
  return function () {
    var payload = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : {};
    return _extends({
      type: type
    }, payload);
  };
};
var setParams = createAction(SET_PARAMS);
```
It means if i call  **setParams** method , **type** should always be **Navigation/SET_PARAMS**, so i must realize **Navigation/SET_PARAMS** condition in reducers, just like i do in my code, do i understand correctly?

and if found below code in addNavigationHelpers.js:
```
   ...
    setParams: (params: NavigationParams): boolean =>
      navigation.dispatch(
        NavigationActions.setParams({
          params,
          key: navigation.state.key,
        })
      ),
   ...
```

so if i call props.navigation.setParams it should dispatch automactically, isn't it?but it still doesn't.

**Comment by faceyspacey** [comment]
you need to simply pass the action and previous state to `MyStack.router.getStateForAction(action, prevState)`. 

You don't need to do `switch`. ...and if you do need `switch` for other actions, simply make the default `getStateForAction`. 

Look into `src/routers/StackRouter.js`. It's the most important file in the entire library, especially when you're first getting started with React Navigation. You will see it is a big file and very advanced. Almost the entire file is the `getStateForAction` method, and it is very large. It handles all the actions supported by React Navigation, and if your router has children routers/navigators, it will automatically see if the child router for the current index can handle the action. 

Research that file and you will have all your answers.

**Comment by faceyspacey** [comment]
basically your reducer can often just be:

const stackReducer = (state, action) =>
   MyNavigator.router.getStateForAction(action, state) || state

...only if your reducer does custom things for regular actions (e.g. `action.type === 'Profile'`) do you need to make a busier reducer. In those cases, you make the regular action.type checks (such as in a switch statement) and then use `getStateForAction` as needed, perhaps simply as the default as I said above. But you can get fancier than that. Basically u can get the next state from `getStateForAction` and then if you want you can modify it, such as change the array of routes or the index.

**Comment by cityvoice** [comment]
is my mistake ,just do:

`this.props.navigation.navigate('Profile', {name: 'Hello'})`
