### ISSUE TITLE
Go back And the callback function

### ISSUE THREAD

**Issue by Adar-Li** [react-community/react-navigation#1692]
hello, I want to ask. 
I have three view.
a->b->c then c goBack('a')  
and want to callback a's function 
here my c code:
const backAction = NavigationActions.back({
              key: 'a',
              // params: { callback(this.accesstoken) },
            });
but is false ;

here my a code:
navigate('b', {callback: (accesstoken) => {
               this.freshData(accesstoken);
           }};

Can you understand what I mean？
thanks

**Comment by liyajie920112** [comment]
I understand, because I have the same problem, but I've solved it by passing a callback function in the parameter

**Comment by naivehhr** [comment]
@Adar-Li goBack('a') 's not work for me..., 
```
const app = StackNavigator({
  a: { screen: home },
})
Is this a?
```

**Comment by Adar-Li** [comment]
@liyajie920112 thanks

**Comment by Adar-Li** [comment]
@naivehhr yes! But goBack('a') need modify the source code. If you need help, please add me QQ: 784556739.

**Comment by kelset** [comment]
Pinging OP @Adar-Li since this issue is quite old and related to an old version of the lib. If no answer I'll close in 7 days.

**Comment by jalil-ranger** [comment]
> hello, I want to ask.
> I have three view.
> a->b->c then c goBack('a')
> and want to callback a's function
> here my c code:
> const backAction = NavigationActions.back({
> key: 'a',
> // params: { callback(this.accesstoken) },
> });
> but is false ;
> 
> here my a code:
> navigate('b', {callback: (accesstoken) => {
> this.freshData(accesstoken);
> }};
> 
> Can you understand what I mean？
> thanks

Got any solution 
I am in same issue but RN 0.63 and ReactNavigation 4.x
