### ISSUE TITLE
webview does not work under TabNavigator

### ISSUE THREAD

**Issue by deity46** [react-community/react-navigation#1693]
Webview does not work under TabNavigator. 

SyntaxError: Unexpected end of JSON input
    at parse (native)
    at process._tickCallback (internal/process/next_tick.js:103:7)
{ Error: write EPIPE
    at exports._errnoException (util.js:1022:11)
    at Socket._writeGeneric (net.js:712:26)
    at Socket._write (net.js:731:8)
    at doWrite (_stream_writable.js:334:12)
    at writeOrBuffer (_stream_writable.js:320:5)
    at Socket.Writable.write (_stream_writable.js:247:11)
    at Socket.write (net.js:658:40)
    at Socket.Writable.end (_stream_writable.js:480:10)
    at Socket.end (net.js:428:31)
    at Promise.resolve.then.then.then.catch.then.message (C:\react\test\node_modules\react-native\packager\src\Server\symbolicate\worker.js:35:33) code: 'EPIPE', errno: 'EPIPE', syscall: 'write' }

Source files:
++++++++++++++++++++++++++
index.android.js
+++++++++++++++++++++++++++
import React, { Component } from 'react';
import {StackNavigator, TabNavigator} from 'react-navigation';
import {Container, Button, Text} from 'native-base';
import web1 from './web1';

export default class HomeScreen extends Component {
    render() {
	return (
<Container>
<Button  onPress={() => this.props.navigation.navigate('Web1')}>
</Container>
); }}

const test = StackNavigator({
  Home: {screen: HomeScreen },
  Web1: {screen: web1},
});

AppRegistry.registerComponent('test', () => test);

++++++++++++++++++++++++++
web1.js
+++++++++++++++++++++++++++
import React, { Component } from 'react';
import {Webview } from 'react-native';
import {StackNavigator, TabNavigator} from 'react-navigation';
import {Container, Text} from 'native-base';
const HTML = `
<html>
  <body>
    <h1>Hello  World</h1>
  </body>
</html>
`;

class Tab1 extends Component {
  static navigationOptions = {
title:'Tab1'   
  };
  
  render() {
    return (
        <View>
        <WebView
        source={{html: HTML}}
                
        />
        </View>
    );
  }
}

class Tab2 extends Component {
  static navigationOptions = {
title:'Tab2'   
  };

  render() {
    return (
      <Text> Hello World </Text>
    );
  }
}

export default (web1 = TabNavigator({
  Home: {
    screen: Tab1,
  },
  Tab2: {
    screen: Tab2,
  }, 
}));

**Comment by deity46** [comment]
const HTML is some basic html codes, replaced the tag with dash:

const HTML = `
-html-
  -body-
    -h1-Hello World-/h1-
  -/body-
-/html-
`;

**Comment by spencercarli** [comment]
Is this still an issue? I'm going to close this since it's been a few months since any updates here.

**Comment by vonovak** [comment]
closing, since it's long dead here. Also, I don't think this is a react-navigation issue.
