### ISSUE TITLE
goBack to previous screen instead of Stack

### ISSUE THREAD

**Issue by itswaze** [react-community/react-navigation#1695]
Hi, I have the following screens and Stacks:

Tab Home:
    -> screenA
    -> screenB
Tab Stock:
    -> screen1
    -> screen2

And I am navigating from screen2 to screenB, and when I press goBack() on screen B it goes to A, when it should be going to screen2. Does anyone know how to implement this?

**Comment by dmr07** [comment]
+1

**Comment by yuguangmao** [comment]
+1

**Comment by p0d3r** [comment]
+1

**Comment by kcfgl** [comment]
Did anyone find a solution to this yet?

**Comment by kelset** [comment]
Closing this in favor of #2549
