### ISSUE TITLE
Calling setParams after reset action make jump action

### ISSUE THREAD

**Issue by mnkang89** [react-community/react-navigation#1697]
### Current Behavior Video
** Video: you can see the current behavior which calls setparams in componentdidmount and jump to next tab after RESET stack action
[youtube link](https://www.youtube.com/watch?v=YTCj5SFteks&feature=youtu.be)

**code:
<img width="568" alt="2017-05-27 09 31 54" src="https://cloud.githubusercontent.com/assets/12220785/26516324/73fcef8c-42bf-11e7-8942-61b22bd184af.png">
<img width="989" alt="2017-05-27 09 32 24" src="https://cloud.githubusercontent.com/assets/12220785/26516325/73ffcbee-42bf-11e7-9280-0144271469b1.png">

### Current Behavior
Like above video when i reset stack with tab press, it resets router stack as it is expected to..
but when it gets back to initial screen `componentDidMount` calls `setParams` and weirdly it goes
to second tab which is not intended to behave.

 Now I'm using setParams to give scrollsToTop method(component method) to `static navigationOptions` in initial screen. because there is no way to get component method in navigationOption now without `setParams`.

I want my app to have scrollsToTop functionality when tab pressed. so I need to make it clear how to hand over component method to navigationOptions. or if there is other ways to make it(scrollsToTop) please let me know how to make it work!

### Expected Behavior
Calling setParams in componentDidMount and remain initial tab after reset action.

### Your Environment
| software         | version
| ---------------- | -------
| react-navigation |  1.0.9-beta (which is latest in npm)
| react-native     |   0.43
| node             | 7.6.0
| npm or yarn      | 4.1.2

**Comment by ghuh** [comment]
This may be related to https://github.com/react-community/react-navigation/issues/1711

**Comment by vonovak** [comment]
#2674 was merged so this should no longer be an issue
