### ISSUE TITLE
goBack doesn't work with following steps from office doc

### ISSUE THREAD

**Issue by WeIio** [react-community/react-navigation#1699]
Yep, I had searched a lots of issues listed on github,but none of them seems been resolved .
I want to goback from a subtab of tabnavigation, but unfortunately,whatever  pass key or  empty, it always doesn't work.
additionally, pass null to goBack works, but it's not a good choice.

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.11
| react-native     |  0.44.0
| node             |  7.10.0
| npm or yarn      | 4.6.1

**Comment by spencercarli** [comment]
Why do you feel passing `null` is a bad choice?

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
