### ISSUE TITLE
Header props in defualt StackNavigatorConfig navigationOptions does not have any effect

### ISSUE THREAD

**Issue by davidskaarup** [react-community/react-navigation#170]
I'm trying to set some default props for my StackNavigator header, but it doesn't seem to work. Only setting the header in navigationOptions on the individual screen seems to have any effect. Am I doing something wrong?

    export default HomeStack = StackNavigator({
      Home: {
        screen: HomeScreen,
      },
      Profile: {
        path: 'people/:name',
        screen: ProfileScreen,
      }
    }, {
      navigationOptions: {
        title: 'Test', // this works
        header: { //any prop in the header is ignored
          tintColor: 'white',
          style: {
            backgroundColor: 'skyblue'
          }
        }
      }
    });

**Comment by davidskaarup** [comment]
I have investigated a bit further, and it seem that the default navigationOptions header works if I don't have any header specified in the screen's navigationOptions. If I have a header on the screen navigationOptions it overrides all my default header settings, even though i'm not specifying any props.

    class HomeScreen extends React.Component {
      static navigationOptions = {
        header: {
          // this empty header will override all default header settings
        }
      }
    }

Is this expected behaviour? If so how do I set some default header props (like background color) while still being able to have individual props on each screen (like title)?

**Comment by satya164** [comment]
@davidskaarup yeah, this is the expected behaviour. You can do this,

```js
header: (navigation, header) => ({
  ...header, // merge the parent header config,
  tintColor: 'orange' // add any overrides
})
```

**Comment by davidskaarup** [comment]
That's just what I needed, thanks a lot 👍

**Comment by Paul-Todd** [comment]
I agree with @davidskaarup here and I hit the same problem too - I think by default the props should merge down from the leaf to the root so settings can be overridden by the child.

I have been working with a very common scenario here:
stacknav -> login screen -> tabs nav -> tabs view -> update object screen

Here we want to set the tabbar visible property to false in the update object screen to hide the tabs. How to do this is currently not obvious. 

Thanks @satya164 for the great tip here!

**Comment by samcorcos** [comment]
That solved it for me. You can find it in the docs here:

https://reactnavigation.org/docs/navigators/navigation-options#Default-Navigation-Options

**Comment by leesolway** [comment]
```
const Router = StackNavigator({
  Splash: { screen: Splash },
  About: { screen: About },
  Quote: { screen: Quote },
}, {
  headerMode: 'screen',
  navigationOptions: {
    header: (navigation, header) => ({
      ...header, // merge the parent header config,
      tintColor: 'orange', // add any overrides
      color: '#ff0000'
    })
  }
})
```
Does not effect the header style at all for me.. ?
