### ISSUE TITLE
how to get all routes?

### ISSUE THREAD

**Issue by kbkyan** [react-community/react-navigation#1700]

**Comment by kbkyan** [comment]
Last state

**Comment by kbkyan** [comment]
![Uploading 23BE43A1-7C8D-4B2E-86CE-934798976423.png…]()

**Comment by ryam4u** [comment]
+1 How can I get all the routes from a normal screen?
To use with NavigationActions.reset

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
