### ISSUE TITLE
Back button is always "Back" if screen title is long enough

### ISSUE THREAD

**Issue by Tiendq** [react-community/react-navigation#1702]
### Current Behavior
1. First screen's title: `First`
2. Second screen's title: `Long Enough Title`
- Second screen's back button is `Back` on iPhone 5 (320px width)
- Second screen's back button is `First` (correct) on iPhone 6 (375px width)

### Expected Behavior
Second screen's back button is always`First` on all devices.

### Your Environment
| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.9 
| react-native     |  0.44

**Comment by vonovak** [comment]
this is not a bug but a feature

**Comment by Tiendq** [comment]
Inconsistent feature?

**Comment by vonovak** [comment]
I am going to close this, because like I said, I believe this is a feature - if there is enough space, the previous' screen title is rendered. If not, 'back' is rendered. Also, there is a config option for this https://reactnavigation.org/docs/navigators/stack#Screen-Navigation-Options

**Comment by SamiChab** [comment]
Works with the `headerBackTitle` option (if not too long as well)
