### ISSUE TITLE
how to pass action type if login succes with redux

### ISSUE THREAD

**Issue by mynameisbams** [react-community/react-navigation#1703]
i try make login, when i login and the loginis success then passing type: 'Login'... but not worked... anyonehave solution for me?

action.js
    import { Login } from '../constant/Constant'

    import { NavigationActions } from "react-navigation";
    import dispatch from "redux/es/createStore";

    export function login(data) {
        if (data.email === 'me') {
            //NavigationActions.navigate({ routeName: 'Route' });
            console.log("login success");
            //dispatch({type: 'Login'});
            return (dispatch) => {
                dispatch({type: 'Login'});
            };
        }else{
            console.log("login error");
        }
    }

reducers

    import { combineReducers } from 'redux';
    import { NavigationActions } from 'react-navigation';
    import { AppNavigator } from '../navigators/AppNavigator';
    import { reducer as formReducer } from 'redux-form'

    const firstAction       = AppNavigator.router.getActionForPathAndParams('Main');
    const tempNavState      = AppNavigator.router.getStateForAction(firstAction);
    const secondAction      = AppNavigator.router.getActionForPathAndParams('Login');
    const initialNavState   = AppNavigator.router.getStateForAction(
        secondAction,
        tempNavState
    )

    function nav(state = initialNavState, action) {
        let nextState;
        switch (action.type){
            case 'Login':
                nextState = AppNavigator.router.getStateForAction(
                    NavigationActions.back(),
                    state
                );
                break;
            case 'Logout':
                nextState = AppNavigator.router.getStateForAction(
                    NavigationActions.navigate({routeName: 'Login'}),
                    state
                );
                break;
            default:
                nextState = AppNavigator.router.getStateForAction(action, state);
                break;

        }

        return nextState || state;
    }

    const initialAuthState  = { isLoggedIn: false };

    function auth(state = initialAuthState, action) {
        switch (action.type){
            case 'Login':
                console.log(action.type);
                return { ...state, isLoggedIn:true };
            case 'Logout':
                return { ...state, isLoggedIn:false};
            default:
                return state;
        }
    }

    const AppReducer = combineReducers({
        nav,
        auth,
        form: formReducer
    })

    export default AppReducer;

**Comment by pyros2097** [comment]
I Think I know what you are trying to do,
This is how I do it
```
const navReducer = (state, action) => {
  switch (action.type) {
    case 'USER_LOGIN_SUCCESS':
      return Router.router.getStateForAction(NavigationActions.reset({
        index: 0,
        actions: [
          NavigationActions.navigate({ routeName: 'Main' }),
        ],
      }), state)
    case 'USER_UPDATE_SUCCESS':
      return Router.router.getStateForAction(NavigationActions.back(), state)
    case 'PUSH_STATE':
      return Router.router.getStateForAction(NavigationActions.navigate({
        routeName: action.payload.route
      }), state)
  }
  return Router.router.getStateForAction(action, state)
}
``

**Comment by mynameisbams** [comment]
@pyros2097 it try it but, the type:'login' not show up when i print in the reducer... can  show me ur action code?

**Comment by pyros2097** [comment]
I don't have the code now but basically I do this in the component,
`this.props.dispatch({ type: 'USER_LOGIN_SUCCESS', payload: { name: 'hello' }})`
And btw it would be easier if you also use redux-logger that would log all actions that are happening irrespective of the reducer since its a middleware.

**Comment by mynameisbams** [comment]
still not work :(

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
