### ISSUE TITLE
frustration level 50,000 foot high; where the hell can I get a SIMPLEAPP example that works.....

### ISSUE THREAD

**Issue by dcu-sharepoint** [react-community/react-navigation#1704]
once the navigator was BROKEN, it's very difficult to follow any example on react courses, articles, blogs and anything else react-native....

why the hell couldn't they keep the old so as to be compatible and be able to learn the fucken shit.
it's so difficult trying to follow this crap without throwing a fucken monkey wrench into the fucken pot.

**Comment by brentvatne** [comment]
hello @dcu-sharepoint - I'm sorry that you're frustrated, that is never pleasant. we don't tolerate aggression towards contributors here. if you would like to re-create the issue and explain it clearly without the aggression then the contributors to this repository would be happy to consider your concerns.

**Comment by dcu-sharepoint** [comment]
@brentvatne; the problems is I don't understand the code as presented in different places for navigation processes. I'm current viewing a video from pactpub where the navigation is being presented in one way and when I write the code, the build process comes up with a long message telling me the Navigator is now deprecated and to use something else. when I use the something else, the configuration is 100% different so that the lessons are now completely useless and when I try to contact the video creator, he does not bother to acknowledge the information request. so my statement still remains, why remove something that is working without any migration information to help out people who are just starting to get into this. these technologies are not for the faint of heart and some of us do have to work for a living and we don't have a lot of time to spend learning and re-learning and re-learning simply because someone decided to change an entire library component on a whim. I went thru that with angular from 1 to 2 where 2 is not compatible with 1, so no more angular, now react is doing the same thing....

I'm sure the contributors spend a lot of time coming with great things, but they should keep in mind what is going on in the real world.

I still didn't get the answer to the question I asked:
**where the hell can I get a complete SIMPLEAPP navigation example that works**

**Comment by gregblass** [comment]
Welcome to the world of bleeding edge technology. Things get depreciated fast. Its part of the process of using awesome new technologies like React Native.

Man up and refactor. Cursing on github isn't going to get you anywhere. You're lucky Brent is such a nice guy.

**Comment by gregblass** [comment]
Have you checked out this example? https://github.com/react-community/react-navigation/tree/master/examples/NavigationPlayground
