### ISSUE TITLE
Unable to pass params from a StackNavigator to/through a DrawerNavigator

### ISSUE THREAD

**Issue by mediashane** [react-community/react-navigation#1706]
After reviewing many similar issues I unable to find a proper working solution for passing params between Navigators.

Use case: DrawerNavigator acts as a side-menu to navigate user through StackNavigator screens. In order for current user data to be 'carried' through navigation chain it would need to pass from StackNavigator screen 1 to DrawerNavigator (menu) and back into StackNavigator screen 2 after navigation is complete.

Is there a best-practice method for solving this use case? Thanks!

### Current Behavior
Attempting to pass and use params between navigators results in error "Can't find variable params":

`onPress={() => navigate('DrawerOpen', { user: navigation.state.params.user })}` 
(Note: replacing 'DrawerOpen' with screen or route names results in same error)

![image](https://cloud.githubusercontent.com/assets/14046192/26526544/9fc32512-43b1-11e7-96f1-494acc1c6b32.png)

### Expected Behavior

That params can be passed between navigators in the same manner as passing between screens within the same navigator:  

`onPress={() => navigate('AddItemScreen', { user: navigation.state.params.user })}`

![image](https://cloud.githubusercontent.com/assets/14046192/26526554/12d6318e-43b2-11e7-9f30-e3059128e3e8.png)

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.11
| react-native     |  0.44
| node             |  6.9.4
| npm or yarn      | 4.6.1

**Comment by efkan** [comment]
It's the same here.

State prop has `params` when using `StackNavigator`. But when using `DrawerNavigator` state has only `{ key: 'Chat', routeName: 'Chat' }`.

If there is no an exeption when using `StackNavigator` and `DrawerNavigator` together there should be a `params` prop. It seems so [over here](https://reactnavigation.org/docs/navigators/navigation-prop#state-The-screen's-current-stateroute).

**Comment by nikolal** [comment]
I have similar issue. I can't pass the params: Drawer -> Tabs

**Comment by Bundas** [comment]
Me too. This kind of issue is known since January. Why it isn't resolved already?

**Comment by nikolal** [comment]
@Bundas 

I solved it using this workaround:

```
  goToTabs = x =>
    NavigationActions.navigate({
      routeName: 'Tabs',
      params: { sport: x },
      action: NavigationActions.navigate({
        routeName: 'AllGames',
        params: { sport: x }
      })
    });
```
In example above I am passing param sport from Drawer to Tabs, and then to AllGames tab.

Hope it helps you.

**Comment by Bundas** [comment]
@nikolal 

Thank you very much, this maybe works, but my case is **Drawer -> Stack**. Any idea how to resolve this? I believe it's similar but I have no idea.

**Comment by nikolal** [comment]
@Bundas 

In my example above "Tabs" represents tabNavigator.

```
const Tabs = TabNavigator(routeConfig, navigationConfig);

export default Tabs;
```

So instead of Tabs you can try using your StackNavigator component.
Something like this:
```
  goToSomeScreen = x =>
    NavigationActions.navigate({
      routeName: 'YourStackNavigatorComponent',
      params: { sport: x },
      action: NavigationActions.navigate({
        routeName: 'SomeScreen',
        params: { sport: x }
      })
    });
```

**Comment by Bundas** [comment]
@nikolal 

Doesn't work :( the params property is still undefined. I do exactly the same you posted.

But i dont understand why it doesnt work. It set params inside child router, so the params should be set...

**Comment by kelset** [comment]
Pinging OP @mediashane since this issue is quite old and related to an old version of the lib. If no answer I'll close in 7 days.

Moreover, solution proposed by @nikolal seems good to me and we also added in the README some articles & tutorials about how to handle complex Drawer examples.

**Comment by kelset** [comment]
Hi there @mediashane ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.

**Comment by huuquan95** [comment]
This is the simple way to solve this problem. See it here https://codeburst.io/react-native-navigation-stack-navigator-inside-tab-navigator-inside-drawer-navigator-b2f21836708d

**Comment by sethnkruse** [comment]
was this ever resolved from going form a Drawer Navigation to a child Stack Navigation and passing param?

**Comment by edem** [comment]
even this issue has been resolved. It's too trouble. awfully design.
I will give it up and rework with react-native-navigator.

**Comment by yowrosales** [comment]
I got this working by doing:

`onPress={() => this.props.navigation.dispatch(NavigationActions.navigate({
            routeName: 'SomeScreen',
            params: { sport: 'x' },
          }))}`

**Comment by danielkolesnik** [comment]
WTF, still don't work?!?!?!

**Comment by danielkolesnik** [comment]
WTF, still don't work?!?!?!
