### ISSUE TITLE
Press drawerItem or Android Back button will not close drawer by itself

### ISSUE THREAD

**Issue by Youngdi** [react-community/react-navigation#1707]
### Current Behavior
On ios device: no problem.
On Android device: I used drawer navigator but it will not close drawer when I press any the draweItems. And I also test to use a button to trigger dispatch('DrawerOpen') and dispatch('DrawerClose'), it doesn't work either. However, I did check is that really trigger action or not. The answer is yes, it did a 'Navigation/NAVIGATE', which routeName is DrawerOpen or DrawerClose. So I don't what wrong in my code, cause it works pretty well on ios. 

ps: I followed [Redux Integration example](https://reactnavigation.org/docs/guides/redux) to build my app. But My Android back button can't trigger drawerClose either. It will just exitApp(), although I follow [issue](https://github.com/react-community/react-navigation/issues/117) to create an AndroidBack handler. it will implement navigation.back then close my app. What the hell is that!
### my case
![case](https://cloud.githubusercontent.com/assets/8704781/26527510/f481106c-43c7-11e7-853e-9049881bea9e.gif)

### my router structure
```sh
TabNavigator
   Tab Screen One -> DrawerNavigator 
                        Drawer Screen One -> StackNavigator
                        Drawer Screen Two -> StackNavigator
                        Drawer Screen Three -> StackNavigator
                        Drawer Screen Four -> StackNavigator
   Tab Screen Two -> StackNavigator
   Tab Screen Three -> StackNavigator
   Tab Screen Four -> StackNavigator
```
the entire code are at [my github](https://github.com/Youngdi/TakeItOver_20170525):
### app/tabOne/navigationConfiguration.js
```sh
'use strict'

import React from 'react';
import { View, Text, Image, StyleSheet, Platform } from 'react-native';
import { StackNavigator, DrawerNavigator, DrawerItems } from 'react-navigation';
// Screens
import TabOneScreenOne from './views/TabOneScreenOne';
import TabOneScreenTwo from './views/TabOneScreenTwo';
import TabOneScreenThree from './views/TabOneScreenThree';
import TabOneScreenFour from './views/TabOneScreenFour';
//import BackgroundImage from '../components/BackgroundImage';

const SideDrawer = (props) => {
  return (
    <View style={styles.DrawerContainer}>
      <View style={styles.drawerIconContainer}>
        <Image  
          source={require('../images/galaxy.png')}
          style={styles.drawerIcon}
        />
      </View>
      <View style={{height:1, width:'100%', backgroundColor:'black'}}></View>
      <DrawerItems {...props} />
    </View>
  )
};


const styles = StyleSheet.create({
    DrawerContainer: {
      flex:1,
      marginTop: Platform == "ios" ? 25 : 0,
      backgroundColor: 'gray'
    },
    drawerHeader: {
      flex:1
    },
    drawerIconContainer:{
      height: 200,
      width: '100%',
      resizeMode: 'cover',
      alignItems:'center',
      justifyContent:'center',
    },
    drawerIcon: {
        width: 100,
        height: '50%',
        borderRadius:10,
    },
});
const stackNavigatorConfiguration = {
  headerMode: 'none',
}
const tabOneDrawerOne = StackNavigator({
  TabOneScreenOne: { screen: TabOneScreenOne },
  },
  stackNavigatorConfiguration
);

const tabOneDrawerTwo = StackNavigator({
  TabOneScreenTwo: { screen: TabOneScreenTwo },
  },
  stackNavigatorConfiguration
);

const tabOneDrawerThree = StackNavigator({
  TabOneScreenThree: { screen: TabOneScreenThree },
  },
  stackNavigatorConfiguration
);

const tabOneDrawerFour = StackNavigator({
  TabOneScreenFour: { screen: TabOneScreenFour },
  },
  stackNavigatorConfiguration
);

const routeConfiguration = {
  TabOneDrawerOne: { screen: tabOneDrawerOne },
  TabOneDrawerTwo: { screen: tabOneDrawerTwo },
  TabOneDrawerThree: { screen: tabOneDrawerThree },
  TabOneDrawerFour: { screen: tabOneDrawerFour },
}
// going to disable the header for now
const DrawerNavigatorConfiguration = {
  initialRouteName: 'TabOneDrawerOne',
  contentComponent: SideDrawer,
}
export const NavigatorTabOne = DrawerNavigator(routeConfiguration, DrawerNavigatorConfiguration);
```
### Expected Behavior
When press DrawerItems should be close by itself and Android back button should be work as well.
### Your Environment
| software         | version
| ---------------- | -------
| react-navigation | 6.2.3  
| react-native     |  0.44.0
| node             | 7.4.0
| npm or yarn      | 4.0.5

**Comment by hansfpc** [comment]
I'll be trying the same

**Comment by spencercarli** [comment]
Can you put together a running example of the issue you (snack is a great place to do that). Also, the version of react-navigation you have listed isn't a valid version - could you double check that?

**Comment by kelset** [comment]
Pinging OP @Youngdi since this issue is quite old and related to an old version of the lib. If no answer I'll close in 7 days.

**Comment by kelset** [comment]
Hi there @Youngdi ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.
