### ISSUE TITLE
Unable to run playground example

### ISSUE THREAD

**Issue by RohanVB** [react-community/react-navigation#1708]
log:
```
$ npm run run-playground-ios

> react-navigation@1.0.0-beta.11 run-playground-ios /Users/Projects/react-navigation
> cd examples/NavigationPlayground && npm run ios


> NavigationPlayground@0.1.0 ios /Users/Projects/react-navigation/examples/NavigationPlayground
> react-native-scripts ios

sh: react-native-scripts: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! NavigationPlayground@0.1.0 ios: `react-native-scripts ios`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the NavigationPlayground@0.1.0 ios script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/***/debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-navigation@1.0.0-beta.11 run-playground-ios: `cd examples/NavigationPlayground && npm run ios`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-navigation@1.0.0-beta.11 run-playground-ios script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

Similar error when I do `npm start`

| software         | version
| ---------------- | -------
| react-navigation |  "^1.0.0-beta.11"
| react-native     |  "0.44.2",
| node             | v7.7.2
| npm or yarn      |4.6.1 ,0.24.5 (npm was used for the purpose of `npm install` here)

**Comment by matthamil** [comment]
Did you run `npm install` in the root project directory?

**Comment by RohanVB** [comment]
Yes I followed the exact steps as given [here](https://github.com/react-community/react-navigation/blob/master/docs/guides/Contributors.md#development)

**Comment by vexsnare** [comment]
+1

**Comment by sebbarg** [comment]
I had the same problem. My work around was to do "react-native init" to a new app and then copy the relevant parts from the example directory.

**Comment by ixje** [comment]
Same here; also running "react-native run-ios" directly from the example app (as suggested by [the contributors docs](https://github.com/react-community/react-navigation/blob/master/docs/guides/Contributors.md#run-the-example-app)) does not work but gives another error

**In console it says**
> Looking for JS files in
   /Users/erik/Documents/code/react-navigation/examples/ReduxExample

> 
> React packager ready.
> 
> Loading dependency graph, done.
> error: bundling: Error
>     at DependencyGraph._getAbsolutePath (/Users/erik/Documents/code/react-navigation/examples/ReduxExample/node_modules/react-native/packager/src/node-haste/index.js:272:11)
>     at DependencyGraph.getDependencies (/Users/erik/Documents/code/react-navigation/examples/ReduxExample/node_modules/react-native/packager/src/node-haste/index.js:216:26)
>     at Resolver.getDependencies (/Users/erik/Documents/code/react-navigation/examples/ReduxExample/node_modules/react-native/packager/src/Resolver/index.js:106:27)
>     at _resolverPromise.then.resolver (/Users/erik/Documents/code/react-navigation/examples/ReduxExample/node_modules/react-native/packager/src/Bundler/index.js:561:62)
>     at process._tickCallback (internal/process/next_tick.js:109:7)
> Bundling `examples/ReduxExample/index.js`  0.0% (0/1), failed.

While the simulator simultaneously says : 
![screen shot 2017-05-31 at 22 26 11](https://cloud.githubusercontent.com/assets/6625537/26652506/687e79c0-4650-11e7-9fdc-6bc12e22b788.png)

It doesn't seem to realise it's already in the ReduxExample folder and tries to use: react-navigation/examples/ReduxExample/examples/ReduxExample/index.js

**Comment by ajostergaard** [comment]
Try this: https://github.com/react-community/react-navigation/issues/1325

Note use of **react-native start**.

**Comment by spencercarli** [comment]
Consolidating NavigationPlayground related issues to #2170.

**Comment by grgrssll** [comment]
This is still happening. Just now on fresh download
