### ISSUE TITLE
how i can init multi page in  the same time ?

### ISSUE THREAD

**Issue by ilovedesert001** [react-community/react-navigation#1709]
### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  
| react-native     |  
| node             | 
| npm or yarn      |

**Comment by matthamil** [comment]
Can you provide an explanation of what you're trying to achieve and what you have tried?

**Comment by ilovedesert001** [comment]
i am trying to initialize a webview page( Activity ) in background.
open app
init page1( loading)
init page2(webview)

i wanna show the loading page and wait until page2(webview) is initialized ok. then go forword to page2.  
NOT: open page2,the webview start loading res.   i need webview shown first , then i can switch to webview page....

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
