### ISSUE TITLE
Disable a tab option

### ISSUE THREAD

**Issue by arthur31416** [react-community/react-navigation#171]
Hello, first a huge thanks for the great work. The lib is very easy to implement and integrate with redux.

I was wondering how to disable a tab option, the `Support` one in my screenshot. The idea is, instead of navigating to this tab, to trigger an external event (in my case show an Intercom list).

Right now I render an empty component and manage by myself an immediate redirection to the previous route.

Obviously, it would be cleaner not to have any navigation at all but I can't find a way to intercept the navigation action.

Any clues how to do so?

Thanks again

<img width="370" alt="tabs" src="https://cloud.githubusercontent.com/assets/12168491/22593560/6e6d5370-ea1f-11e6-9080-fb678d127916.png">

**Comment by ericvicenti** [comment]
You're said you're using redux, so maybe you could change your reducer so that it doesn't even use the `router.getStateForAction` when handling a navigate action with that route name, and does something else instead.

Closing for now but let me know if this doesn't work!

**Comment by arthur31416** [comment]
You're right, thanks for the answer.

When I return the unchanged state, there is very often (~80%) a blink, like an empty component being mounted. I tested this in a production environment. I'll try to figure out what can cause that.
