### ISSUE TITLE
How can I change Tab order programmatically

### ISSUE THREAD

**Issue by iswanj** [react-community/react-navigation#1714]
I know we can change tab order initially. But in some case, we need to change tab order programmatically. Is there a way to do that in the current version?

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.9

**Comment by Andreyco** [comment]
As long as I know, it's not possible. It would be useful to filter tabs as well - e.g. remove them `order` props at all.

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
