### ISSUE TITLE
NavigationActions not found

### ISSUE THREAD

**Issue by wilomgfx** [react-community/react-navigation#172]
I was checking out your redux example and i tried to load it on a simulator to see how it works and it cant find this module : NavigatorActions.

When i press the login button i'm getting "Cannot read property 'navigate' of undefined.

It might not be exported ?

**Comment by ElliottJRo** [comment]
Hey @wilomgfx `NavigatorActions` is a feature added in the master branch recently, what you want to do is:

1. Remove your current version of react-navigation: `npm uninstall react-navigation`
2. Add the master branch one: `npm install --save https://github.com/react-community/react-navigation.git`
3. Restart the packager `npm run start -- --reset-cache`
4. Fire up your emulator

**Comment by wilomgfx** [comment]
Great thats what i though. Thanks a lot :)
