### ISSUE TITLE
Tab Navigator icons not showing

### ISSUE THREAD

**Issue by mocanSergiu666** [react-community/react-navigation#1720]
I try to set icons to tabs but these aren't shown. There are only green squares. I have no idea what to do.
It's my first time I try to set icons to tabs.
:   (

```
import { StyleSheet, View, Text } from "react-native";
import { TabNavigator } from "react-navigation";
import FontAwesome, { Icons } from "react-native-fontawesome";
import Colors from "../miscellaneous/colors";

const styles = StyleSheet.create({
	tab: {
		padding: 5
	},
	indicator: {
		width: 0,
		height: 0
	},
	label: {
		fontSize: 10
	},
	icon: {
		width: 20,
		height: 20,
		backgroundColor: "green"
	},
	tabBar: {
		backgroundColor: Colors.darkBlue,
	}
});

export const MainNavigator = TabNavigator(
	{
		Videos: {
			screen: VideosScreen,
			navigationOptions: ({ navigation }) => ({
				title: "Videos",
			})
		},
		ScoresAndOdds: {
			screen: ScoresAndOddsNavigator,
			navigationOptions: ({ navigation }) => ({
				title: "Scores & Odds",
				icon: ({ tintColor }) => <FontAwesome>{Icons.times}</FontAwesome>
			})
		},
		Picks: {
			screen: PicksScreen,
			navigationOptions: ({ navigation }) => ({
				title: "Picks",
			})
		},
		MyScores: {
			screen: MyScoresScreen,
			navigationOptions: ({ navigation }) => ({
				title: "My Scores",
			})
		}
	},
	{
		initialRouteName: "ScoresAndOdds",
		tabBarPosition: "top",
		swipeEnabled: true,
		animationEnabled: true,
		lazy: true,
		order: ["Videos", "ScoresAndOdds", "Picks", "MyScores"],
		backBehavior: "initialRoute",
		tabBarOptions: {
			activeTintColor: Colors.white,
			inactiveTintColor: Colors.transparentWhite,
			showLabel: true,
			showIcon: true,
			upperCaseLabel: false,
			pressColor: Colors.transparentWhite,
			scrollEnabled: false,
			tabStyle: styles.tab,
			indicatorStyle: styles.indicator,
			labelStyle: styles.label,
			iconStyle: styles.icon,
			style: styles.tabBar
		}
	}
);
```
React Native 0.44

**Comment by tiaaaa123** [comment]
It's triple ` to put code into a block.
One ` is only for a line

**Comment by mocanSergiu666** [comment]
@tiaaaa123 , thanx for help, but could you help me with my real problem? :   )

**Comment by tiaaaa123** [comment]
Possible cause: indicatorStyle of width: 0, height: 0. I would recommend use `backgroundColor: 'transparent'`. It all depends of how the bottom line is implemented. But at the same time, it's only for Android... I haven't used much of react-navigation (and I tried using tabRouter).. So I can't help you much... sorry

**Comment by xsgkaka** [comment]
@mocanSergiu666  
I have the same problem.

**Comment by mocanSergiu666** [comment]
The problem was that I used "icon" instead of "tabBarIcon".
Correct example:
tabBarIcon: ({ tintColor }) => <FontAwesome style={{ color: tintColor }}>{Icons.videoCamera}</FontAwesome>
The issue will be closed by me.

**Comment by huyb1991** [comment]
I got the same issue event using `tabBarIcon`.
My code:
```
static navigationOptions = {
    tabBarIcon: () => (
      <Image
        source={require('@assets/icons/home.png')}
        style={CommonStyles.tabBarIcon}
      />
    )
  }
```

**Comment by maudnals** [comment]
Hi @huyb1991 , I had the same issue and changed the syntax to fix it.  
Have you tried removing the wrapping parentheses so that you return directly the `<Image>` component? 

Like so:    

`tabBarIcon: () =>
      <Image
        source={require('@assets/icons/home.png')}
        style={CommonStyles.tabBarIcon}
      />`

**Comment by 1c7** [comment]
it show on iOS but not Android 
![image](https://user-images.githubusercontent.com/1804755/33939375-e69f1780-e045-11e7-9ab3-971a96877446.png)

full code:

```
import React from 'react';
import { View, Text, StyleSheet, Button, Image } from 'react-native';
import { StackNavigator, TabNavigator } from 'react-navigation';



class MyHomeScreen extends React.Component {
  static navigationOptions = {
    tabBarLabel: '开始放大',
    // Note: By default the icon is only shown on iOS. Search the showIcon option below.
    tabBarIcon: ({ tintColor }) => (
      <Image
        source={require('./assets/add.png')}
        style={[styles.icon, { tintColor: tintColor }]}
      />
    ),
  };

  render() {
    return (
      <Button
        onPress={() => this.props.navigation.navigate('Notifications')}
        title="Go to notifications"
      />
    );
  }
}

class MyNotificationsScreen extends React.Component {
  static navigationOptions = {
    tabBarLabel: '放大记录',
    tabBarIcon: ({ tintColor }) => (
      <Image
        source={require('./assets/history2.png')}
        style={[styles.icon, { tintColor: tintColor }]}
      />
    ),
  };

  render() {
    return (
      <Button
        onPress={() => this.props.navigation.goBack()}
        title="Go back home"
      />
    );
  }
}

class ProfileScreen extends React.Component {
  static navigationOptions = {
    tabBarLabel: '账号设置',
    tabBarIcon: ({ tintColor }) => (
      <Image
        source={require('./001-settings.png')}
        style={[styles.icon, { tintColor: tintColor }]}
      />
    ),
  };

  render() {
    return (
      <Button
        onPress={() => this.props.navigation.goBack()}
        title="Go back home"
      />
    );
  }
}

const styles = StyleSheet.create({
  icon: {
    width: 26,
    height: 26,
  },
});

const MyApp = TabNavigator({
  Home: {
    screen: MyHomeScreen,
  },
  Notifications: {
    screen: MyNotificationsScreen,
  },
  Profile: {
    screen: ProfileScreen,
  },
}, {
    tabBarPosition: 'bottom',
    animationEnabled: true,
    // tabBarOptions: {
    //   activeTintColor: '#e91e63',
    // },
  });

export default MyApp;
```

**Comment by northern** [comment]
@1c7

For Android you should set `showIcon` in `tabBarOptions` to `true` (it's `false` by default):

https://reactnavigation.org/docs/navigators/tab#tabBarOptions-for-TabBarTop-default-tab-bar-on-Android

It might be beneficial to create separate `tabBarOptions` for the different platforms. I.e. you might want to do something like this:

```
import { Platform } from 'react-native'

const tabBarOptions = Platform.OS === 'ios' ? 
  {
    // iOS tabBarOptions
    showLabel: true
  } : {
    // Android tabBarOptions
    showIcon: true,
    showLabel: true
  }
```

**Comment by 1c7** [comment]
@northern Thank you!

**Comment by 1c7** [comment]
@northern it work!
![image](https://user-images.githubusercontent.com/1804755/34026391-b2c14612-e190-11e7-9c22-09b870767e19.png)

**Comment by CodingJbz** [comment]
thanks for @northern and @1c7 . I got same issue .

**Comment by Unlighten** [comment]
My Icons are cutting off only on android and I cannot figure out why...

Here is the code for tabNavigation.js:

`const HomeTabNavigation = TabNavigator(
  
  {
    Profile: { screen: Profile },
    PhotoCard: { screen: PhotoCard },
    Chat: { screen: Chat }
  },
  {
    tabBarPosition: "bottom",
    tabBarComponent: TabBarBottom,
    initialRouteName: "PhotoCard",
    swipeEnabled: false,
    lazy: true,
    tabBarOptions: {
      showIcon: true,
      showLabel: false,
      style: {
        backgroundColor: 'white',
        borderTopColor: 'white',
        borderTopWidth: 1,
        height: metrics.DEVICE_HEIGHT * 0.08
      },
      tabStyle: {
        width: metrics.DEVICE_WIDTH * 0.33333333333333333333333333333333333333333,
        height: metrics.DEVICE_HEIGHT * 0.08,
      },
      indicatorStyle: {
        backgroundColor: 'white',
        width: 0,
        height: 0,
        padding: 0,
        margin: 0
      },
    },
  }
);



export default (HomeTabNavigation);`


Here is the code for index.Js in PhotoCard: 

`static navigationOptions = {
    tabBarIcon: ({ focused }) => (
      focused 
      ? <Text style={styles.activeText}>Let'sWait</Text>
      : <Text style={styles.inActiveText}>Let'sWait</Text>
    )
  }`

**Comment by Unlighten** [comment]
Didn't know that. Thanks man!

**Comment by armanbabai** [comment]
import { TabNavigator,TabBarBottom , StackNavigator } from 'react-navigation';
import {Icon} from 'native-base';
.
.
.

export const Tabs = TabNavigator({
  Feed: {
    screen: tab1,
    navigationOptions: {
      tabBarLabel: 'label',
     tabBarIcon: ({ tintColor }) => <Icon name="list" size={35} color='red' />,
    },
  },
  Me: {
    screen: tab2,
    navigationOptions: {
      tabBarLabel: 'Me',
    },
  },
  
},
  {
    tabBarOptions: {
        activeTintColor: 'red',
        inactiveTintColor: 'gray',
      style: {
        backgroundColor: '#EEEEEE',
      },
    showIcon: true,
    showLabel: true
  },
    tabBarComponent: TabBarBottom,
    tabBarPosition: 'bottom',
    animationEnabled: true,
    swipeEnabled: true,
  });

**Comment by markmiller21** [comment]
@Unlighten did you figure this out?  If so, what is your solution? I am still experiencing wonky behavior where my icon is getting cutoff

**Comment by guiherzog** [comment]
Having this problem too! Icons cutting off.

**Comment by nwaughachukwuma** [comment]
Look up this medium article here: https://medium.com/@c.nwaugha/how-to-show-an-icon-with-react-navigation-tab-navigator-ea9b653241e1

**Comment by Humbl-e** [comment]
Adding width to icon style fixes the icon from getting cut off.
I.e. <Icon style={{width:26-32}} size... color..  />
