### ISSUE TITLE
HTTP request blocks back button on TabNavigator

### ISSUE THREAD

**Issue by M-Nasab** [react-community/react-navigation#1723]
Hi,
I have a TabNavigator with two tabs. when the second tab mounts it will make an HTTP request to fetch some data from a remote address (e.g. using an axios.get). But when this process starts, until the promise resolves, the back button is blocked and i can't go back to previous tab.
after the promise is resolved and the data is fetched, the app responds to the back button.
I expect the App to respond immediately when i press the back button.
Here is my code:
```
import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View,
  Button,
  ActivityIndicator,
  ScrollView
} from 'react-native';
import { TabNavigator } from 'react-navigation';
import axios from 'axios';

class Home extends Component {
	static navigationOptions = {
		tabBarLabel: 'Home'
	};

	render(){
		return (
			<View style={styles.container}>
			  <Text>Home</Text>
			</View>
		);
	}
}

class Profile extends Component {
	static navigationOptions = {
		tabBarLabel: 'Profile'
	};

	constructor(props){
		super(props);
		this.state = { ON: true, Message: '' };
	}

	componentDidMount(){
		console.log('Component Did Mount');
		axios.get(dataURL)
		.then((response) => {
			this.setState({ ON: !this.state.ON, Message: JSON.stringify(response.data) });
		});
	}

	componentWillUnmount(){
		console.log('Component Will Unmount');
	}

	render(){
		if(this.state.ON){
			return (
				<View style={styles.container}>
				  <Text>Profile</Text>
				  <ActivityIndicator size='large' />
				</View>
			);
		}
		else{
			return (
				<ScrollView style={{flex: 1}}>
				<View style={styles.container}>
				  <Text>Profile</Text>
				  <Text>{this.state.Message}</Text>
				</View>
				</ScrollView>
			);
		}
	}
}

const MyApp = TabNavigator({
	Home: {
		screen: Home
	},
	Profile: {
		screen: Profile
	}
},
{
	tabBarOptions: {
		activeTintColor: '#e91e63',
	},
	lazy: true,
});

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});

AppRegistry.registerComponent('backbtntest2', () => MyApp);
```

### Environment

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.11
| react-native     |  0.44.2
| node             | 7.10.0
| npm      | 4.2.0
| platform         | Android

**Comment by kelset** [comment]
Pinging OP @M-Nasab since this issue is quite old and related to an old version of the lib. If no answer I'll close in 7 days.

**Comment by kelset** [comment]
Hi there @M-Nasab ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.
