### ISSUE TITLE
Delay switch between tabs - Android

### ISSUE THREAD

**Issue by claudioviola** [react-community/react-navigation#1725]
I've a terrible delay when switch beetwen tabs on android 
This is the result: http://imgur.com/PpinR9j
![ezgif com-optimize](https://cloud.githubusercontent.com/assets/6689594/26579849/f1ad70dc-4535-11e7-8ce3-cc660fbb01b0.gif)

It's a know issue?

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.11
| react-native     |  0.44.2
| node             | 7.8.0
| npm or yarn      | 4.2.0

**Comment by Andreyco** [comment]
Are you debugging remotely?

**Comment by MSchmidt** [comment]
I'm experiencing some delay as well but not as bad as you. I think it only occurs when having a TabNavigator inside a StackNavigator. But nor sure yet.

**Comment by claudioviola** [comment]
@Andreyco yes I tried in debug mode remotly enabled. After I tried to build apk and I didn't see any delay.
Why in this case the debug mode is affected a delay in tab navigator?

@MSchmidt thanks for suggestion

**Comment by Andreyco** [comment]
In debug mode, there are multiple checks performed and they do decrease performance. Also, if you debug remotely (in browser) and debug tab is not in foreground it's priority is decreased and performance suffers greatly.

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
