### ISSUE TITLE
Tabs - Dynamic style and action

### ISSUE THREAD

**Issue by leesolway** [react-community/react-navigation#1727]
Hi, i am attempting to replicate the following style, using the TabNavigator. 

![screen shot 2017-05-30 at 16 45 26](https://cloud.githubusercontent.com/assets/2929803/26592044/79f3d58c-4557-11e7-9ebf-5cde26667a94.png)

**Issue 1.**
The middle tab needs to be styled independently, to the other four.
Is this currently supported? I can't seem to find a way to do this.

**Issue 2.**
The title, position and callback of the middle button needs to be set dynamically by the screen currently loaded. 

Any advice on how to achieve the above screenshot.

Thanks in advance,

**Comment by zachgibson** [comment]
1.  You can make your own tab bar, see [tabBarComponent](https://reactnavigation.org/docs/navigators/tab#TabNavigatorConfig). I’d check out [TabBarBottom.js](https://github.com/react-community/react-navigation/blob/30ca3c1f80617abc28fdd71f0b37d4f62b3e388a/src/views/TabView/TabBarBottom.js) for reference on writing your own tab bar.

2. Use [navigation props](https://reactnavigation.org/docs/navigators/navigation-prop) to dynamically do want you want in your custom tab bar.

**Comment by leesolway** [comment]
Thanks for the points @zachgibson 

I am struggling to get custom navigation props into the TabBarComponent. 
Do you have any examples, or pointers on how i can pass a callback and title into the custom TabBar  component?

**Comment by zachgibson** [comment]
@leesolway are you trying to change the middle button based on what tab you press?

**Comment by leesolway** [comment]
Exactly @zachgibson 
The tab screen pressed needs to set a callback and title

**Comment by leesolway** [comment]
@zachgibson Did you have any other thoughts on this? 
It would be really helpful to change the middle button.

**Comment by zachgibson** [comment]
@leesolway you have a repo I can pull down?

**Comment by leesolway** [comment]
https://github.com/leesolway/react-navigation-tabs

Thanks @zachgibson, here is the example. Within the TabBarBottom component, i want to be able to change the title, and attach a callback to the button with the text "Custom Text here".

**Comment by kelset** [comment]
Pinging OP @leesolway since this issue is quite old and related to an old version of the lib. If no answer I'll close in 7 days.

Moreover, if you are looking for ways to dynamically changing the tabs you can can this issue https://github.com/react-community/react-navigation/issues/2818

**Comment by kelset** [comment]
Hi there @leesolway ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.
