### ISSUE TITLE
Instagram-like third tab bar button

### ISSUE THREAD

**Issue by MingLoan** [react-community/react-navigation#1729]
Does anyone know how to make tab bar like Instagram? 
The third tab is an action button to present a screen.

**Comment by zachgibson** [comment]
You can create your own Tab Bar using [tabBarComponent](https://reactnavigation.org/docs/navigators/tab#TabNavigatorConfig) and do whatever you’d like. I’d look at TabBarBottom.js to get an idea of how to roll your own.

**Comment by MingLoan** [comment]
Finally I intercept the tab press by using tabBarComponent and dispatch my custom NavigationAction to solve this. Work perfectly.

**Comment by uzikone** [comment]
@MingLoan could you share an example how you did it, please? I have the same issue and can't figure it out.

**Comment by spencercarli** [comment]
Here's a quick example of this type of interaction running - https://snack.expo.io/HkzW4clOZ

Should be even easier in an upcoming version of the library.

**Comment by theOnkar** [comment]
@spencercarli How can I add icons above the label? I tried: 

```const Tabs = TabNavigator({
  Feed: {
    screen: (props) => <Screen title="Feed" {...props} />,
    navigationOptions:{
      tabBarIcon: ({ tintColor, focused }) => (
                    <Ionicons
                      name={focused ? 'ios-home' : 'ios-home-outline'}
                      size={26}
                      style={{ color: tintColor, padding:0 }}
                    />
                ),
    } 
  },
  Search: { ... }
  ...
}, {
  // Instagram has the tabbar on the bottom on iOS and Android
  tabBarPosition: 'bottom',
  tabBarOptions:{
    showIcon :true,
  },
  // Specify our custom navbar
  tabBarComponent: TabBar,
});


Thanks

**Comment by mafiusu** [comment]
@spencercarli @theOnkar Anything new on 'How to add icons for spencercarlis TabBar Navigation example?' Still it is a Instagram like example I would like to have icons. I have to look more into this.

**Comment by pablo-albaladejo** [comment]
@mafiusu  Use icons instead of Text component:

https://snack.expo.io/@pablo-albaladejo/instagram-tab-nav-with-react-navigation

**Comment by hagar0459** [comment]
i have when i run the sample in react native as Component for route Capture must be React Component?
