### ISSUE TITLE
StackNavigator - custom GoBack route

### ISSUE THREAD

**Issue by fredjens** [react-community/react-navigation#1731]
I am using the **StackNavigator**, but sometimes i do not want the "Back" button to go back in the routing history, i want it to go back in the hierarchy of my app. In other words; I want to specify which Screen the Back button should go to, just like `Navigate` works. Is this possible without replacing `headerLeft` with my own component? (Seems a bit overkill, when i only want to change the path).

I have read the docs carefully and searched the issues, but couldn't find anything on this..

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.11
| react-native     |  0.42.0

**Comment by nolan-m** [comment]
I'm pretty sure you have to create a custom Back button with headerLeft.  I just made mine a component and then I could reuse it everywhere I needed the functionality.

**Comment by yasserzubair** [comment]
@nolan-m can you explain? because I've been trying to achieve this but the new component fails to recieve navigation in the props so I cannot navigate.

**Comment by nolan-m** [comment]
You need to set the custom back function in the navigation params so you can access it in the header.  This is usually done in the componentWillMount.  Search the Github issues for a more examples.  

```
  static navigationOptions = {
      header: ({ state, setParams }) => ({
        left: (
          <HeaderBackArrow
            onPress={() => {
              if (state.params && state.params.onBackPress) {
                state.params.onBackPress();
              }
            }}
            title={'Back'}
          />
        )
      }),
    }
```


```
  componentWillMount() {
    this.props.navigation.setParams({
      onBackPress: this._handleBackPress
    });
  }

  _handleBackPress = () => {
    // do something
  }
```

**Comment by nolan-m** [comment]
See example here if you just want to navigate and not use a custom function.

https://github.com/react-community/react-navigation/issues/299

**Comment by fredjens** [comment]
According to [the docs](https://reactnavigation.org/docs/navigators/stack), the config is **headerRight**. So it should be like this?

```
 static navigationOptions = ({ navigation }) => ({
   headerRight: ({ state, setParams }) => (
      <HeaderBackButton
        onPress={() => {}}
      />
    ),
});

**Comment by nolan-m** [comment]
Yes, I am still using an old version.

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!

**Comment by DamienVauchel** [comment]
I know this issue is closed for a long time but for all people who are searching for now and reading this thread, the code must be more like

```js
const navigationOptions = ({ navigation }) => ({
   headerLeft:  () => <HeaderBackButton
      onPress={() => {}}
    />
});
```

You need to pass a function to headerLeft which returns a ReactNode.
