### ISSUE TITLE
title cannot be defined as a function in navigation options

### ISSUE THREAD

**Issue by circuit-monkey** [react-community/react-navigation#1733]
I've recently updated react-navigation, and I can no longer use a function to define a title like so:

 static navigationOptions = {
  title: ({ state }) => `to ${state.params.mainVerbInfinitive}`,
  fontSize: 18,
  backgroundColor: '#ccc',
 };

It results in the following error:

        title cannot be defined as a function in navigation options for ${route.routeName} screen.
        Try replacing the following:
        {,
         title: ({ state }) => state...
        },    
        with:
        ({ navigation }) => ({
         title: navigation.state...
        })

Could someone please give me a clear explanation as to how this can be fixed?

Thank you very much.

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.5
| react-native     | 0.44.2
| node             | 7.4.0
| npm or yarn      | 4.2.0

**Comment by circuit-monkey** [comment]
static navigationOptions = ({ navigation }) => ({
  title: `to ${navigation.state.params.mainVerbInfinitive}`,
  fontSize: 18,
  backgroundColor: '#ccc',
 })

**Comment by Nuptial** [comment]
Circuit-monkey your solution cannot help me. Do you know another solution for this problem?

Thank you...
