### ISSUE TITLE
props.navigation.navigate in not defined from screen that not registered in StackNavigator route

### ISSUE THREAD

**Issue by fasalir** [react-community/react-navigation#1735]
Hello i am new to ReactNative, and i want to implements a navigation between pages, but there is a menu bar below. my menu bar consist of Home, Product, and Account.

### Current Behavior
I have a screen called menubar.js that create a blank view above, and a menu bar below (this is just a template).
In my route.js that that define all my screen for StackNavigator i dont call that menubar.js

this is what my route.js looks like 
```
export var StackHome = StackNavigator({
	Home: {
		screen: Home,
		navigationOptions: {
			header: null
		}
	},
	Users: {
		screen: Users,
		navigationOptions : {
			title: 'User Information,
			headerRight: <RightButton/>
		}
	}
})
```

```
export var StackProduct = StackNavigator({
	Products: {
		screen: Products,
		navigationOptions: {
			header: null
		}
	},
        ProductDetail: {
		screen: ProductDetail,
		navigationOptions: {
			header: null
		}
	}
})

export var StackAccount = StackNavigator({
	Account: {
		screen: Account,
		navigationOptions: {
			header: null
		}
	},
	AccountSetting: {
		screen: AccountSetting,
		navigationOptions: {
			header: null
		}
	}
})

export var Root = StackNavigator({
	Home: {
		screen: StackHome,
		navigationOptions: {
			header: null
		}
	},
	Product: {
		screen: StackProduct,
		navigationOptions: {
			header: null
		}
	},
	Account: {
		screen: StackAccount,
		navigationOptions: {
			header: null
		}
	}
}, {
	headerMode: 'screen'
})
```
in menubar.js i have this code

```
<Button 
	label = 'Product' 
	pressed = {true}
	press = {()=> this.props.navigation.navigate('Product')}
/>
```
but it said undefined is not object (this.props.navigation.navigate)

### Expected Behavior
I want if the button "Account" inside menubar.js pressed, then Accoun screen is viewed. but maybe since my menubar.js never called in route.js so it doesn't have props.navigation.navigate() property. so how to make my button inside menubar.js view Account screen?

### Your Environment
iam using windows 8

| software         | version
| ---------------- | -------
| react-navigation |  ^1.0.0-beta.11
| react-native     |  0.44.2
| node             | v7.1.0
| npm or yarn      | 3.10.9

**Comment by HelloEdit** [comment]
Same problem

**Comment by Talor-A** [comment]
try this: 
```
import { withNavigation } from 'react-navigation'
class MenuBar extends Component { 
...
}
export default withNavigation(MenuBar)

**Comment by MehdiAlouafi** [comment]
Thanks a lot @Talor-A, i didn't see it in the docs my bad, but I have a question though : 

Why even though I'm currently using only one StackNavigator nested in a component every screens has the navigation props except for the last one (which is why I was here haha)

**Comment by leesolway** [comment]
I have this exact issue, very random

**Comment by kelset** [comment]
It's expected that a Button not connected to the navigator doesn't have access to those props.

To achieve what you want you need to use [Navigation Actions](https://reactnavigation.org/docs/navigators/navigation-actions).
