### ISSUE TITLE
route x should declare a screen

### ISSUE THREAD

**Issue by visylvius** [react-community/react-navigation#1736]
Hey Guys! Hope this finds you all well. I've recently switched from Ex-navigation to React-navigation. 

I've been running into problem with nesting navigators tho. 
*index.js* 

    const Drawer = DrawerNavigator({
      UserSettings: {
        screen: Containers.UserSettings,
      },
    })

    const root = StackNavigator({
      ConfigureBrand: { screen: Containers.ConfigureBrand },
      DeviceStateEditor: { screen: Containers.DeviceStateEditor },
      Device: { screen: Containers.Device },
      DebugSettings: { screen: Containers.DebugSettings },
      EmailSignup: { screen: Containers.EmailSignup },
      Explore: { screen: Containers.Explore },
      ForgottenDevices: { screen: Containers.ForgottenDevices },
      History: { screen: Containers.History },
      Home: { screen: Containers.Home },
      Init: { screen: Containers.Init },
      Login: { screen: Containers.Login },
      NameSignup: { screen: Containers.NameSignup },
      Onboarding: { screen: Containers.Onboarding },
      OnBoardingDevices: { screen: Containers.OnboardingDevices },
      PasswordRecovery: { screen: Containers.PasswordRecovery },
      PasswordSignup: { screen: Containers.PasswordSignup },
      Routine: { screen: Containers.Routine },
      Tutorial: { screen: Containers.Tutorial },
      YeelightTutorial: { screen: Containers.YeelightTutorial },
      UserSettings: { screen: Drawer },
      WebView: { screen: Containers.WebView },
    })

    export const AppNavigator = StackNavigator(root, {
      initialRouteName: 'Init',
      headerMode: 'screen',
      navigationOptions: {
        gesturesEnabled: false,
        headerStyle: {
          backgroundColor: 'white',
          elevation: 1,
        },
        headerTitleStyle: {
          alignSelf: 'center',
        },
        headerBackTitle: null,
      },
      cardStyle: {
        backgroundColor: 'white',
      },
    })

Is it because i'm trying to nest a drawer navigation within a StackNavigation? Any help would be appreciated.

**Comment by visylvius** [comment]
So I was able to get this working by putting the root navigation routes into the AppNavigator directly. 
```
export const AppNavigator = StackNavigator({
  CharmsList: { screen: Containers.CharmsList },
  ConfigureBrand: { screen: Containers.ConfigureBrand },
  DebugSettings: { screen: Containers.DebugSettings },
  Device: { screen: Containers.Device },
  DeviceInput: { screen: Containers.DeviceInput},
  DeviceStateEditor: { screen: Containers.DeviceStateEditor },
  DevicesList: { screen: Containers.DevicesList },
  EmailSignup: { screen: Containers.EmailSignup },
  Explore: { screen: Containers.Explore },
  ForgottenDevices: { screen: Containers.ForgottenDevices },
  Header: { screen: Containers.Header },
  History: { screen: Containers.History },
  Home: { screen: Containers.Home },
  Init: { screen: Containers.Init },
  LifxLogin: { screen: Containers.LifxLogin },
  Login: { screen: Containers.Login },
  NameSignup: { screen: Containers.NameSignup },
  Onboarding: { screen: Containers.Onboarding },
  OnboardingDevices: { screen: Containers.OnboardingDevices },
  Page: { screen: Containers.Page },
  PasswordRecovery: { screen: Containers.PasswordRecovery },
  PasswordSignup: { screen: Containers.PasswordSignup },
  Routine: { screen: Containers.Routine },
  RoutinesList: { screen: Containers.RoutinesList },
  Tutorial: { screen: Containers.Tutorial },
  UserSettings: { screen: Drawer },
  YeelightTutorial: { screen: Containers.YeelightTutorial },
  WebView: { screen: Containers.WebView },
},
  {
    initialRouteName: 'Init',
    headerMode: 'screen',
    navigationOptions: {
      gesturesEnabled: false,
      headerStyle: {
        backgroundColor: 'white',
        elevation: 1,
      },
      headerTitleStyle: {
        alignSelf: 'center',
      },
      headerBackTitle: null,
    },
    cardStyle: {
      backgroundColor: 'white',
    },
  })
```

This is quite ugly tho. Shouldn't passing root into AppNavigator work?

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
