### ISSUE TITLE
Dynamically add or delete RouteConfigs.

### ISSUE THREAD

**Issue by dbarros** [react-community/react-navigation#1737]
If I have the following StackNavigator, is it possible to add new screens (to accompany Home and Notes) to the RouteConfigs, sometime after its creation?

```
export default App = StackNavigator({
    Home: { screen: HomeScreen }
    Notes: { screen: NotesScreen }
});
```

I'm using react-navigation 1.0.0-beta.11.

**Comment by franj0** [comment]
I also need this possibillity, ty

**Comment by gunn** [comment]
See also #2362

**Comment by kelset** [comment]
At the moment there is no explicit way to do this - please read here #717; that said, you can also check another way to approach this in the articles in the README.

**Comment by oximer** [comment]
@kelset Any news about this feature?
