### ISSUE TITLE
[Expo] labelStyle with Font Async not working on Android

### ISSUE THREAD

**Issue by bondanherumurti** [react-community/react-navigation#1738]
react-navigation drawerItems contentComponent labelStyle, with expo Font Async, it doesn't work, and only on android, on ios working just fine... here are some code snippet

here is my drawer contentComponent

```
  async componentDidMount() {
    // console.log('HEIGHT', height);
    await Font.loadAsync({
      'dosis-bold': require('../../assets/fonts/dosis/Dosis-Bold.ttf'),
      'dosis-light': require('../../assets/fonts/dosis/Dosis-Light.ttf'),
      'dosis-regular': require('../../assets/fonts/dosis/Dosis-Regular.ttf'),
      'Arial': require('../../assets/fonts/arial/arial.ttf'),
    });
    this.setState({fontLoaded: true});
  }

  render () {
    return(
      <View>
        {
          this.state.fontLoaded ?
          <View>
            <Image source={require('../../assets/images/bg-loading-page.png')} style={{position: 'absolute', top: 0, left: 0, width: 73*vw, height: 100*vh, }}/>
            <DrawerItems {...this.props} labelStyle={{fontFamily: 'dosis-regular', fontSize: 20}} />
            <Text style={{fontFamily: 'dosis-light'}}>Test</Text>
          </View> : <Expo.AppLoading />
        }
      </View>
    );
  }
```

here is problem

<img width="435" alt="screen shot 2017-05-31 at 2 22 15 pm" src="https://cloud.githubusercontent.com/assets/1384256/26620329/986681c6-460c-11e7-92fc-2420ab599a02.png">

the home was drawerItems labelStyle, while the test is just a plain text... the drawerItems doesnt work

on iOS, it works just fine

version
Expo 2.18.0
RN https://github.com/expo/react-native/archive/sdk-16.0.0.tar.gz
react-navigation ^1.0.0-beta.9

**Comment by danikane** [comment]
I am having the same issue.
Other components work well with async loaded custom font and set with **fontFamily**, but DrawerItems **labelStyle** doesn't.

```
    "@expo/samples": "~1.0.4",
    "expo": "^18.0.4",
    "react": "16.0.0-alpha.12",
    "react-native": "https://github.com/expo/react-native/archive/sdk-18.0.1.tar.gz",
    "react-navigation": "^1.0.0-beta.11"
```

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
