### ISSUE TITLE
Drawer navigator does not display menu on web environment

### ISSUE THREAD

**Issue by agrcrobles** [react-community/react-navigation#174]
When using [Drawer Navigator](https://reactnavigation.org/docs/navigators/drawer) on react-native menu is displaying since it is implemented by [react-native-drawer-layout](https://github.com/react-native-community/react-native-drawer-layout).

It should be nice to have the same behavior on web.

**Comment by satya164** [comment]
How are you using drawer navigator on web?

**Comment by agrcrobles** [comment]
good question! Created a [repo](https://github.com/agrcrobles/react-navigation-web) to do some experiments in web.

Basically I implemented a custom navigator view and implemented the drawer by [react-sidebar](https://github.com/balloob/react-sidebar) on it.

So when creating the navigator just import the drawer navigation view and that is all!

```
import DrawerNavigationView from 'DrawerNavigationView';

const routes = {
  Home: {
    screen: Home,
    path: 'home'
  },
  Page: {
    screen: Page,
    path: 'page'
  }
};
const Router = StackRouter(routes);

export const Navigator = createNavigator(Router)(DrawerNavigationView);
```

I still have a ton of questions but it is a good step!

![drawer](https://cloud.githubusercontent.com/assets/5727373/22620019/bede4e66-eb02-11e6-8088-fa17dfd05400.gif)

**Comment by agrcrobles** [comment]
Hey, so I found documentation for the web environment is pretty short and a walk through is still pending so I will try move so pieces forward on that.

**Comment by kopax** [comment]
Hi @agrcrobles and thanks for sharing your example. I am currently looking to implement a drawer for the web with expo sdk 36. I saw your polyfill and it's now deprecated, do you know if I can still use it or should I implement my own ? Do you still use react-sidebar? Thanks!
