### ISSUE TITLE
It´s possible to manually add a back button in the headerLeft?

### ISSUE THREAD

**Issue by agarciaguillo** [react-community/react-navigation#1743]
I need the profile screen to have a button to go back. I don´t know if it can be done manually or I would have to change the code.

### Source code

```javascript
const ProfileStack = StackNavigator({
	Profile: {
		screen: Profile,
		navigationOptions: {
			title: 'Profile',
			headerStyle: { backgroundColor: '#2196f3' },
			headerTintColor: '#fff'
		}
	},
	Settings: {
		screen: Settings,
		navigationOptions: {
			title: 'Settings',
			headerStyle: { backgroundColor: '#2196f3' },
			headerTintColor: '#fff'
		}
	}
});

const OneStack = StackNavigator({
	OneList: {
		screen: One, 
		navigationOptions: ({ navigation }) => ({
			tabBarLabel: 'One',
			tabBarIcon: ({ tintColor }) => <Icon name="list" size={30} color={tintColor} />,
			title: 'Page One',
			headerStyle: { backgroundColor: '#2196f3' },
			headerTintColor: '#fff',
			headerRight: <IconProfile navigation={navigation} />
		})
	},
	OneDetails: {
		screen: OneDetails, 
		navigationOptions: {
			tabBarVisible: false,
			title: 'OneDetails',
			headerStyle: { backgroundColor: '#2196f3' },
			headerTintColor: '#fff'
		}
	}
});

const TwoStack = StackNavigator({
	TwoList: {
		screen: Two,
		navigationOptions: ({ navigation }) => ({
			tabBarLabel: 'Two',
			tabBarIcon: ({ tintColor }) => <Icon name="thumbs-up-down" size={30} color={tintColor} />,
			title: 'Page Two',
			headerStyle: { backgroundColor: '#2196f3' },
			headerTintColor: '#fff',
			headerRight: <IconProfile navigation={navigation} />
		})
	},
	TwoDetails: {
		screen: TwoDetails, 
		navigationOptions: {
			tabBarVisible: false,
			title: 'TwoDetails',
			headerStyle: { backgroundColor: '#2196f3' },
			headerTintColor: '#fff'
		}
	}
});

const ThreeStack = StackNavigator({
	ThreeList: {
		screen: Three,
		navigationOptions: ({ navigation }) => ({
			tabBarLabel: 'Three',
			tabBarIcon: ({ tintColor }) => <Icon name="favorite-border" size={30} color={tintColor} />,
			title: 'Page Three',
			headerStyle: { backgroundColor: '#2196f3' },
			headerTintColor: '#fff',
			headerRight: <IconProfile navigation={navigation} />
		})
	},
	ThreeDetails: {
		screen: ThreeDetails, 
		navigationOptions: {
			tabBarVisible: false,
			title: 'ThreeDetails',
			headerStyle: { backgroundColor: '#2196f3' },
			headerTintColor: '#fff'
		}
	}
});

const FourStack = StackNavigator({
	FourList: {
		screen: Four,
		navigationOptions: ({ navigation }) => ({
			tabBarLabel: 'Four',
			tabBarIcon: ({ tintColor }) => <Icon name="chat" size={30} color={tintColor} />,
			title: 'Page Four',
			headerStyle: { backgroundColor: '#2196f3' },
			headerTintColor: '#fff',
			headerRight: <IconProfile navigation={navigation} />
		})
	},
	FourDetails: {
		screen: FourDetails, 
		navigationOptions: {
			tabBarVisible: false,
			title: 'FourDetails',
			headerStyle: { backgroundColor: '#2196f3' },
			headerTintColor: '#fff'
		}
	}
});

const Tabs = TabNavigator({
	One: { screen: OneStack },
	Two: { screen: TwoStack },
	Three: { screen: ThreeStack },
	Four: { screen: FourStack }
},{
	...TabNavigator.Presets.iOSBottomTabs
});

const RouterComponent = StackNavigator({
	Tabs: {
		screen: Tabs
	},
	Profile: {
		screen: ProfileStack
	}
},{
	mode: 'modal',
	headerMode: 'none',
});

export default RouterComponent;
```

### This is how it works

![vid](https://cloud.githubusercontent.com/assets/16135348/26644853/6e75500c-4636-11e7-84a9-f3e777770ade.gif)

Is there any solution?

**Comment by nico1510** [comment]
You could try 2 things:
a) use `headerMode: 'none'` in your sub-`StackRouters` and do **instead** of  your root router (named RouterComponent). Ideally you shouldn't have to do anything more then and the headers of the sub-`StackRouters` would be displayed in your root router's header. I think I remember something similarly worked a while back for me, but I haven't tested it in a while now and I think it's unlikely that it will still work like this but you can test nevertheless.

b) and this is what I'm currently using in a different situation. To manually include the back button:

```javascript
const navigationOptions = ({ navigation }) => ({
    headerLeft: <HeaderBackButton onPress={() => navigation.goBack(null)} />,
})

const RouterComponent = StackNavigator({
	Tabs: {
		screen: Tabs
	},
	Profile: {
		screen: ProfileStack,
		navigationOptions
	}
},{
	mode: 'modal',
	headerMode: 'none',
});
```

**Comment by hegelstad** [comment]
@agarciaguillo Please reopen this.

@nico1510 manually including the back button as shown in nico1510's example doesn't work with the current version of React-Navigation.

No button is rendered, and I suspect that is because headerMode is set to none (i.e. hidden), and the header shown is the stacks header?

**Comment by RealDyllon** [comment]
FYI: In React Navigation 5, the import has changed:

`import { HeaderBackButton } from "@react-navigation/stack";
`

**Comment by MaykonMorais** [comment]
@RealDyllon, this work just when headerMode is float ou screen

**Comment by Maxim312** [comment]
> @RealDyllon, this work just when headerMode is float ou screen

can you tell me a solution? I've been struggling with this error for several days now.

**Comment by dytra** [comment]
> FYI: In React Navigation 5, things are slightly different:
> 
> `import { HeaderBackButton } from "@react-navigation/stack"; `
> 
> and
> 
> ```
>   <Stack.Screen
>     name="Profile"
>     component={ProfileScreen}
>     options={{
>       headerLeft: ({ navigation }) => (
>         <HeaderBackButton onPress={() => navigation.goBack()} />
>       ),
>     }}
>   />
> ```

this is works and i like this aproach, but how do i modify the icon ?
i used `headerLeft` before, but the touchable area is too small

**Comment by GabrielDierks** [comment]
In React Navigation 6:

`import { HeaderBackButton } from "@react-navigation/elements";`

**Comment by Johan-dutoit** [comment]
> In React Navigation 6:
> 
> `import { HeaderBackButton } from "@react-navigation/elements";`

Not compatible with `native-stack`, only `stack`.  By not compatible, I mean the positioning is off.
