### ISSUE TITLE
Cannot read property 'index' of undefined (Transitioner.js)

### ISSUE THREAD

**Issue by braco** [react-community/react-navigation#1744]
### Current Behavior

Fatal error [here](https://github.com/react-community/react-navigation/blob/30ca3c1f80617abc28fdd71f0b37d4f62b3e388a/src/views/Transitioner.js#L77) when setting up for first use.

Mostly copy and pasted from here: https://github.com/react-community/react-navigation/tree/master/examples/ReduxExample

Trying to track down now, but I didn't see any issues with this title.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  ^1.0.0-beta.11
| react-native     |  0.44

**Comment by braco** [comment]
Seems like this issue is caused by improper integration with Redux store. Should probably have a sanity check for this.

**Comment by dbarros** [comment]
@braco is there any solution at the moment to get the ReduxExample to work?

**Comment by waqqas** [comment]
I am having the same problem.  My guess is that store is not initialized at the time when the app is trying to get the state

**Comment by vitorebatista** [comment]
Same problem here...

**Comment by joshuajtaylor** [comment]
I had the same problem. For me, I forgot to add the nav reducer to my combineReducers. Fixed that and the error went away.

**Comment by kotazi** [comment]
Same here

**Comment by jacks205** [comment]
I had my state wrapped in [Immutable.js](https://facebook.github.io/immutable-js/) and changing the `mapStateToProps` function fixed it for me.

```js
const mapStateToProps = (state) => ({
  nav: state.get('nav')
})
```

**Comment by dannyshisler** [comment]
I've got the same problem.

@braco what did you do to fix your Redux store integration?

**Comment by Clowning** [comment]
Same problem... It's very complicated to add Redux with React-Navigation ! :(

**Comment by DeFenceD** [comment]
Same problem.

**Comment by arjunpa** [comment]
Any update on this? Getting the same error here.

**Comment by bboy79** [comment]
I fixed it by adding my navigation reducer to the outermost combineReducers function (I have two combineReducers calls, and use the result of the first one in the second one. Navigation was in the first one).

**Comment by JoeyCurry** [comment]
@jacks205 I use `Immutable.js` with redux too,but your way can't fix mine.can you help me?

**Comment by ujludwig** [comment]
In my case I the error went away when I renamed my reducer back to 'nav' from 'navr'.

**Comment by diego3g** [comment]
I made it work by changing the name of my reducer to nav, i was using navReducer. 

So i changed:
```
const rootReducer = combineReducers({
  navReducer,
});
```

To:
```
const rootReducer = combineReducers({
  nav: navReducer,
});
```

**Comment by RoarRain** [comment]
you are very good!

**Comment by trinketmage** [comment]
https://github.com/GantMan/drawer-example/tree/step1
I learned redux and react-navigation with this good example.
I'd like to point out the fact that the implementation in the example and real application implementation are a bit different cause you split files.
This error is due to the fact that AppNavigator don't receive this.props.nav so you should check nav reducer related file to see where the definition is wrong or the export is missing.
