### ISSUE TITLE
Nested NavigationActions not working

### ISSUE THREAD

**Issue by jominjohn55** [react-community/react-navigation#1747]
`I` was previously working with react-navigation v1.0.0-beta.8, but after upgrading it to v1.0.0-beta.11, the nested NavigationActions is not working. On v1.0.0-beta.8 this was working well, also i was getting the params for the child navigator

`const searchNav = NavigationActions.reset({
                      index: 0,
                      actions: [
                          NavigationActions.navigate({
                              routeName: 'DrawerNavigate',   //its a DrawerNavigator
                              action: NavigationActions.navigate({
                                  routeName: 'SearchScreen',
                                  params: params
                              })
                          })
                      ]
                  })
 this.props.navigation.dispatch(searchNav);`

Please let me know if I am doing anything wrong. But I it was working fine with the v1.0.0-beta.8
Thanks in advance :) @gabriel

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
