### ISSUE TITLE
How do I remove the animation  when  the navigation push  the next screen，as action reset

### ISSUE THREAD

**Issue by roselind** [react-community/react-navigation#1749]
How do I can remove the animation  when  the navigation push  the next screen，
like the effect of  NavigationActions.reset

**Comment by jcsmesquita** [comment]
Hi @roselind, this is a known issue at the moment and there is a proposal #1663 to fix it.

**Comment by roselind** [comment]
I want to remove animation when the navigation push the next screen

**Comment by jcsmesquita** [comment]
Set the transitionConfig property in the navigator to:
```
() => ({
  transitionSpec: {
    duration: 0,
    timing: Animated.timing,
    easing: Easing.step0
  }
})
```

**Comment by roselind** [comment]
I want to remove an animation from just one page ， 
How do I write the code? Where do I write it?

**Comment by gitlovenotwar** [comment]
@roselind are you able to solve to stop animation on one page only?

**Comment by 0x6e6562** [comment]
@roselind @gitlovenotwar I believe configuring transitions on a per-screen basis is part of the scope of #175.

**Comment by roselind** [comment]
I didn't solve this problem. I was using another way, using   react native  navigate to jump directly to the next page, without animation.

I  look   [#175](https://github.com/react-community/react-navigation/issues/175)  ，
I still have no idea

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!

**Comment by hoanganhbk94** [comment]
@roselind Do you have the idea to solve that problem. I am facing same issue and i don't have solution.
@spencercarli Why did you close this issue? Do you give same issue which have solution?
