### ISSUE TITLE
Custom navigationOptions

### ISSUE THREAD

**Issue by leesolway** [react-community/react-navigation#1750]
How can a screen define custom navigationOptions that can be passed into and used by a component such as a custom TabBarComponent? 

Using the TabBarComponent I am attempting to have a dynamic button within the tab container. The text, icon and onPress functionality will differ with every screen context. 

Use cases include :- Firing redux actions such as quit, join, navigate etc. I can not see a clear path of getting the options from the Screen to the TabBarComponent. 

Thanks,

**Comment by BrutHellman** [comment]
I also want to such

**Comment by leesolway** [comment]
Any updates or thoughts on this?

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
