### ISSUE TITLE
Android hardware back button with BackHandler

### ISSUE THREAD

**Issue by sduqlsc** [react-community/react-navigation#1751]
Integrating with redux and react navigation following [#117](https://github.com/react-community/react-navigation/issues/117).

### Current Behavior

Main Screen (4 tabs) and click 3rd tab in which there's an item with click event binding to jump to next screen->List screen->Detail Screen.

After pressing back hardware button on android device, both detail and list screen finished, aka jumps back to the main screen with 1st tab selected.

### Expected Behavior

Just finishes the detail screen and back to  the list screen.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  ^1.0.0-beta.11
| react-native     |  0.44.2
| node             | 4.6.0
| npm or yarn      | 4.3.0

**Comment by yaraht17** [comment]
i have same problem, too. Are you fixed it?

**Comment by spencercarli** [comment]
Could you put together a demo of this issue? Thanks!

**Comment by kelset** [comment]
Closing since no followup from last comment.
