### ISSUE TITLE
ios folder gone from latest NavigationPlayground

### ISSUE THREAD

**Issue by ajostergaard** [react-community/react-navigation#1754]
ios folder is missing from beta-10 and beta-11, was present in beta-9.

### Current Behavior
```
NavigationPlayground aj$ react-native run-ios

ENOENT: no such file or directory, uv_chdir
```

### Expected Behavior
Should start NavigationPlayground in iOS simulator

**Comment by ajostergaard** [comment]
@skevy is it possible this was a result of your recent cleanups?

**Comment by spencercarli** [comment]
Going to close this since NavigationPlayground now uses Create React Native App

**Comment by spencercarli** [comment]
#2168 is tracking solution
