### ISSUE TITLE
Route to new StackNavigator inside TabNavigator and reset stack

### ISSUE THREAD

**Issue by amhinson** [react-community/react-navigation#1755]
I'm trying to route from one StackNavigator to another, both of which are inside a TabNavigator. I'm currently able to get there by simply doing:
`this.props.navigation.navigate('Screen3')`
But I also want to reset that tab when I go to it. Here is how my app navigators are generally set up:
```
- Main (StackNavigator)
  - LoginScreen
  - MainTabs (TabNavigator)
    - Tab1 (StackNavigator)
      - Screen1
      - Screen2
    - Tab2 (StackNavigator)
      - Screen3
      - Screen4
```
How could I navigate to `Screen4` from `Screen1` but also reset the StackNavigator `Tab2`?

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.11
| react-native     |  0.44.2
| node             | 7.7.2
| npm or yarn      | npm 4.1.2

**Comment by williamwlchan** [comment]
I would like to know as well

**Comment by AlexeySmolyakov** [comment]
Good question. Any thoughts?

**Comment by smitthakkar1** [comment]
Facing the same problem. Any solution ?

**Comment by DracoBlue** [comment]
Same here!

**Comment by phoenixzsun** [comment]
Me too! Any solutions?

**Comment by phoenixzsun** [comment]
@spencercarli Can you give us some solutions?

**Comment by spencercarli** [comment]
I'm not sure I understand this 

> but also reset the StackNavigator Tab2

would you want screen4 to be the only screen in your stack then?

**Comment by xyx2011** [comment]
same here, want to know this answer!

**Comment by wmendes** [comment]
Same here

**Comment by ybentlili** [comment]
any solution guys !!

**Comment by tseck** [comment]
same here!

**Comment by kelset** [comment]
Closing in favor of #2670
