### ISSUE TITLE
How to add SlideInFromRightIOS animation to a Custom StackNavigator 

### ISSUE THREAD

**Issue by shrutic123** [react-community/react-navigation#1758]
I have a Custom StackNavigator as I want the header to render at the bottom of screen with custom buttons. I have followed the https://github.com/react-community/react-navigation/blob/master/examples/NavigationPlayground/js/CustomTabs.js example and created CustomStackNavigator. The navigation between screens is abrupt and not the slide in animation like in default StackNavigator. I see that the TRansitionConfig.js has SlideFromRightIOS. Is there a way I can use this TransitionConfig with my Custom Stack Navigator?

I see that the [createNavigator](https://github.com/react-community/react-navigation/blob/30ca3c1f80617abc28fdd71f0b37d4f62b3e388a/src/navigators/createNavigator.js#L17) takes 4 parameters. So I tried updating my createNavigator call from 
```
createNavigationContainer(
    createNavigator(AppStackRouter)(StackView)
);
```

to

```
createNavigationContainer(
    createNavigator(AppStackRouter, {}, { transitionConfig: defaultTransitionConfig} , {})(StackView)
);
```

where [defaultTransitionConfig](https://github.com/react-community/react-navigation/blob/296becd5d1491f2c00bae0657a6bfaa199ed2f8f/src/views/TransitionConfigs.js#L60) defines the default animations that are used by the built-in StackNavigator. 

But it did not work and there are still no slide-in animations between screens

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0.beta-11
| react-native     |  0.43.3
| node             | 
| npm or yarn      | 5.0.1

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!

**Comment by pvinis** [comment]
this is still a problem. `defaultTransitionConfig` and the transitionConfigs are not exported, but they should.

**Comment by pvinis** [comment]
lets reopen this.
