### ISSUE TITLE
How to change trasition screen right to left instead bottom to top?

### ISSUE THREAD

**Issue by xuho** [react-community/react-navigation#1759]
Hi, I'm using RN 0.44.2 and react-navigation 1.0.0-beta.11. And I'm using StackNavigator to change screens, when I change new screen, trasition is bottom to top by defualt. Can I change to right to left?
Thank.

**Comment by NightFarmer** [comment]
+1

**Comment by xuho** [comment]
@NightFarmer Can you help me fix it?

**Comment by DevilMayCry4** [comment]
transitionConfig: ()=> {
                return {screenInterpolator: CardStackStyleInterpolator.forHorizontal}
            }

**Comment by shrutic123** [comment]
I get Unhandled JS Exception: undefined is not an object (evaluating 'react_navigation_1.CardStackStyleInterpolator.forHorizontal') when I try to import { CardStackStyleInterpolator } from 'react-navigation' . I am on version 1.0.0.beta-11

**Comment by xuho** [comment]
@shrutic123: same problem with you. @DevilMayCry4: how to import CardStackStyleInterpolator? Thank.

**Comment by DevilMayCry4** [comment]
@xuho 
import CardStackStyleInterpolator from 'react-navigation/src/views/CardStackStyleInterpolator';

**Comment by xuho** [comment]
@DevilMayCry4, oh, It's working!!! Thank you so much :+1:

**Comment by manuTro** [comment]
by adding the default property 
transitionConfig: ()=> {
return {screenInterpolator: CardStackStyleInterpolator.default.forHorizontal}
}
worked to me

**Comment by kumarpatel** [comment]
```import CardStackStyleInterpolator from 'react-navigation/src/views/CardStackStyleInterpolator';```

^ This import doesn't work on non-debug builds

**Comment by liuzy0404** [comment]
@kumarpatel CardStackStyleInterpolator directory has changed?
import CardStackStyleInterpolator from 'react-navigation/src/views/CardStack/CardStackStyleInterpolator';

**Comment by philipjc-apacio** [comment]
I have searched so many places for what I'm about to ask, so thought I'd ask here.
I'd like my screen to (enter / slide in) from the left and slide back out to the left, is this possible, please???

**Comment by kumarpatel** [comment]
@philipjc-apacio 
Boilerplate from [CardStackStyleInterpolator.js](https://github.com/react-community/react-navigation/blob/master/src/views/CardStack/CardStackStyleInterpolator.js#L48)

```
import { I18nManager } from 'react-native';
import type {
  NavigationSceneRendererProps,
  AnimatedViewStyleProp,
} from 'react-navigation/src/TypeDefinition';

/**
 * Render the initial style when the initial layout isn't measured yet.
 */
function forInitial(
  props: NavigationSceneRendererProps
): AnimatedViewStyleProp {
  const { navigation, scene } = props;

  const focused = navigation.state.index === scene.index;
  const opacity = focused ? 1 : 0;
  // If not focused, move the scene far away.
  const translate = focused ? 0 : 1000000;
  return {
    opacity,
    transform: [{ translateX: translate }, { translateY: translate }],
  };
}

function forHorizontalSlideInFromLeft(
  props: NavigationSceneRendererProps
): AnimatedViewStyleProp {
  const { layout, position, scene } = props;

  if (!layout.isMeasured) {
    return forInitial(props);
  }

  const index = scene.index;
  const inputRange = [index - 1, index, index + 1];

  const width = layout.initWidth;
  const outputRange = I18nManager.isRTL
    ? ([width * 0.3, 0, -width]: Array<number>)
    : ([width * -0.3, 0, width]: Array<number>);

  // Add [index - 1, index - 0.99] to the interpolated opacity for screen transition.
  // This makes the screen's shadow to disappear smoothly.
  const opacity = position.interpolate({
    inputRange: ([
      index - 1,
      index - 0.99,
      index,
      index + 0.99,
      index + 1,
    ]: Array<number>),
    outputRange: ([0, 1, 1, 0.85, 0]: Array<number>),
  });

  const translateY = 0;
  const translateX = position.interpolate({
    inputRange,
    outputRange,
  });

  return {
    opacity,
    transform: [{ translateX }, { translateY }],
  };
}

const HORIZONTAL_SLIDE_TRANSITION_OVERRIDE = () => ({
  transitionSpec: {
    duration: 250,                                     // These are optional, so feel free to modify them as you see fit.
    easing: Easing.inOut(Easing.ease),
    timing: Animated.timing
  },
  screenInterpolator: forHorizontalSlideInFromLeft
});
```

Usage: Add **HORIZONTAL_SLIDE_TRANSITION_OVERRIDE** to any StackNavigator for this transition

Example:
```
StackNavigator(
  {
    screen1: { screen: screen1Component },
    screen2: { screen: screen2Component },
    screen3: { screen: screen3Component },
  },
  {
    transitionConfig: HORIZONTAL_SLIDE_TRANSITION_OVERRIDE
  }
);
```

**Comment by assafb81** [comment]
@kumarpatel 
thanks, your code really help.

how can I use the native transition of iOS and not the custom one? 

I tried this but with no luck:
```
const HORIZONTAL_SLIDE_TRANSITION_OVERRIDE = () => ({
  transitionSpec: {
    duration: 250,                                     // These are optional, so feel free to modify them as you see fit.
    easing: Easing.inOut(Easing.ease),
    timing: Animated.timing
  },
  screenInterpolator: (Platform.OS === 'android')
      ? forHorizontalSlideInFromLeft
      : NavigationSceneRendererProps.defaultTransitionConfig,
});
```
I am getting can't find variable: NavigationSceneRendererProps

**Comment by kumarpatel** [comment]
@assafb81 Sorry for the late reply. Did you get it working?

I think `defaultTransitionConfig` is located in TransitionConfigs.js
so import it from there.
```
import { defaultTransitionConfig } from "react-navigation/src/views/CardStack/TransitionConfigs";
```

and then use it like this...
```
 screenInterpolator: (Platform.OS === 'android')
      ? forHorizontalSlideInFromLeft
      : defaultTransitionConfig,
```

**Comment by assafb81** [comment]
@kumarpatel Thanks

I thought the default transition in iOS is sliding from left to right (or opposite) , but when I added your code the transition is from up/down

Another issue, I change my locale to hebrew and hope to see that the transition will be from left to right, but it remain right to left.

**Comment by kumarpatel** [comment]
@assafb81 

> I thought the default transition in iOS is sliding from left to right (or opposite) , but when I added your code the transition is from up/down

Looking at [defaultTransitionConfig](https://github.com/react-navigation/react-navigation/blob/master/src/views/CardStack/TransitionConfigs.js#L63) logic *ModalSlideFromBottomIOS* transition is used for Modals. This is most likely what's happening in your case.

If you're just looking for a simple slide-in from Right to Left transition (and slide-out from Left to Right) then I would use [forHorizontal config](https://github.com/react-navigation/react-navigation/blob/master/src/views/CardStack/CardStackStyleInterpolator.js#L38)

```  
import CardStackStyleInterpolator from "react-navigation/src/views/CardStack/CardStackStyleInterpolator";

screenInterpolator: CardStackStyleInterpolator.forHorizontal
```

> Another issue, I change my locale to hebrew and hope to see that the transition will be from left to right, but it remain right to left.

From what I can tell, [CardStackStyleInterpolator.forHorizontal](https://github.com/react-navigation/react-navigation/blob/master/src/views/CardStack/CardStackStyleInterpolator.js#L58) also supports RTL and should work for Hebrew.

Hopefully this helps.

**Comment by assafb81** [comment]
thanks for your help @kumarpatel,
It did the job

**Comment by kumarpatel** [comment]
https://medium.com/async-la/custom-transitions-in-react-navigation-2f759408a053
^ An awesome article that talks about custom transitions using this lib.

**Comment by maulikdhameliya** [comment]
If you want to achieve this with react-native-router-flux then check this out
https://medium.com/@maulikdhameliya/how-to-get-ios-like-screen-transition-in-android-using-react-native-53c9246dfcd2

**Comment by krmao** [comment]
```
const RootStack = createStackNavigator(
    {
        home: {screen: HomeScreen, navigationOptions: (navigation) => global.defaultNavigationOptions(navigation)},
        bridge: {screen: BridgeScreen, navigationOptions: (navigation) => global.defaultNavigationOptions(navigation)},
        order_commit: {screen: OrderCommitScreen, navigationOptions: (navigation) => global.defaultNavigationOptions(navigation)}
    },
    {
        initialRouteName: "home",

        navigationOptions: {
            gesturesEnabled: true,
        },
        mode: "card",
        headerMode: "screen",
        headerTransitionPreset: "uikit",
        transitionConfig: () => ({
            transitionSpec: {
                duration: 300,
                easing: Easing.out(Easing.poly(4)),
                timing: Animated.timing,
            },
            screenInterpolator: sceneProps => {
                const {layout, position, scene} = sceneProps;
                const {index} = scene;

                const width = layout.initWidth;
                const translateX = position.interpolate({
                    inputRange: [index - 1, index, index + 1],
                    outputRange: [width, 0, 0],
                });

                /*
                 const height = layout.initHeight;
                 const translateY = position.interpolate({
                 inputRange: [index - 1, index, index + 1],
                 outputRange: [height, 0, 0],
                 });
                 */

                const opacity = position.interpolate({
                    inputRange: [index - 1, index - 0.99, index],
                    outputRange: [0, 1, 1],
                });

                return {opacity, transform: [{translateX: translateX}]};
            },
        }),
    }
);
```

the important is 
```
screenInterpolator: sceneProps => {
                const {layout, position, scene} = sceneProps;
                const {index} = scene;

                const width = layout.initWidth;
                const translateX = position.interpolate({
                    inputRange: [index - 1, index, index + 1],
                    outputRange: [width, 0, 0],
                });

                /*
                 const height = layout.initHeight;
                 const translateY = position.interpolate({
                 inputRange: [index - 1, index, index + 1],
                 outputRange: [height, 0, 0],
                 });
                 */

                const opacity = position.interpolate({
                    inputRange: [index - 1, index - 0.99, index],
                    outputRange: [0, 1, 1],
                });

                return {opacity, transform: [{translateX: translateX}]};
            },
```

**Comment by Thyix** [comment]
Thanks to everyone in the thread, it worked for me. 

I have many scenes managed by only one **StackNavigator** and I wanted to make a different animation for some of them. 

First of all, I made myself a constant in my router which included *every scenes* I wanted to display with horizontal transition : 
```
const modalScenes = [
  AddContact,
];
```

After that, I designed my app router with StackNavigator : 
```
const App = StackNavigator({
  AddContact: {
    screen: AddContact,
  },
  EditContact: {
    screen: EditContact,
  },
});
```

I used **CardStackStyleInterpolator** to modify the transitions between scenes. I can be imported like this : `import CardStackStyleInterpolator from 'react-navigation/src/views/CardStack/CardStackStyleInterpolator';`

We can now add **transitionConfig** params to our *StackNavigator* to display a different animation depending on our scenes : 
```
const App = StackNavigator({
  AddContact: {
    screen: AddContact,
  },
  EditContact: {
    screen: EditContact,
  },
}, {
 transitionConfig: (currentState:any) => {
    if (currentState.scenes[currentState.scenes.length - 1].route.routeName.includes(modals)) {
      return {
        screenInterpolator: CardStackStyleInterpolator.forHorizontal,
      };
    }
    return {
      screenInterpolator: CardStackStyleInterpolator.forVertical,
    };
  },
});
```
With that *StackNavigator* implementation, you will be able to display different kind of animations for the scenes you want. 

Have a good day 🎉

**Comment by RenalPraba** [comment]
For future reader import this

import CardStackStyleInterpolator from 'react-navigation/src/views/StackView/StackViewStyleInterpolator';

and apply it to your transition config like this

transitionConfig: () => ({
        screenInterpolator: CardStackStyleInterpolator.forHorizontal,
    }),

**Comment by MuhammadHanzala** [comment]
@RenalPraba CardStackStyleInterpolator directory has changed?
`import CardStackStyleInterpolator from 'react-navigation/src/views/StackView/StackViewStyleInterpolator';`

`"react-navigation": "^2.12.1"`

**Comment by atulmy** [comment]
With `"react-navigation": "2.17.0",` following works:

`import StackViewStyleInterpolator from 'react-navigation-stack/dist/views/StackView/StackViewStyleInterpolator'`

And in your `createStackNavigator`:
```
transitionConfig: () => ({
	screenInterpolator: sceneProps => {
		return StackViewStyleInterpolator.forHorizontal(sceneProps);
	}
})
```

**Is there any better way to do this?**

**Comment by renalpraba** [comment]
> @renalpraba CardStackStyleInterpolator directory has changed?
> `import CardStackStyleInterpolator from 'react-navigation/src/views/StackView/StackViewStyleInterpolator';`
> 
> `"react-navigation": "^2.12.1"`

I didn't know it was changed, I updated to 2.18.0 and the the import path doesn't exist and give me error now :(

**Comment by ogbrandon** [comment]
How about:

`transitionConfig: () => StackViewTransitionConfigs.SlideFromRightIOS,`

**Comment by haripermadi** [comment]
> How about:
> 
> `transitionConfig: () => StackViewTransitionConfigs.SlideFromRightIOS,`

Hai, how to add duration to slow transition? I use StackViewTransitionConfigs.FadeOutToBottomAndroid but it's to fast and looks like a blink.

**Comment by Statsministeriet** [comment]
It's possible to give the CardStyleInterpolators.forHorizontalIOS arguments if you give the cardStyleInterpolator a function. One of the arguments are the inverted (-1 | 0) which enables left to right transition. 

See my example here:

`
const Root = createStackNavigator<ExploreStackParams>()
const ExploreOptions: React.FC = () => (
    <Root.Navigator screenOptions={{ 
        cardStyleInterpolator: (props) => CardStyleInterpolators.forHorizontalIOS({...props, inverted: -1})
        }}>
        <Root.Screen name="ExploreIndex" component={ExploreIndex}/>
    </Root.Navigator>
`

**Comment by annaostapenko22** [comment]
@Statsministeriet your solution works the best for me! Thanks! Maybe you have also faced with this ts error
<img width="363" alt="Screenshot 2021-04-22 at 14 23 29" src="https://user-images.githubusercontent.com/46502551/115713605-7fc4bb80-a376-11eb-824d-2f8e01c1cb66.png">

**Comment by satya164** [comment]
Card style interpolators accept animated values, not numbers. 

Anyway, instead of doing that, you can specify gesture direction instead.

```js
screenOptions={{ 
  cardStyleInterpolator: CardStyleInterpolators.forHorizontalIOS,
  gestureDirection: 'horizontal-inverted'
}}
```

**Comment by annaostapenko22** [comment]
> Card style interpolators accept animated values, not numbers.
> 
> Anyway, instead of doing that, you can specify gesture direction instead.
> 
> ```js
> screenOptions={{ 
>   cardStyleInterpolator: CardStyleInterpolators.forHorizontalIOS,
>   gestureDirection: 'horizontal-inverted'
> }}
> ```

Thank you very much!
