### ISSUE TITLE
Disable / Enable swipe depending on screen

### ISSUE THREAD

**Issue by arnaubennassar** [react-community/react-navigation#1760]
I have a nested StackNavigator inside a TabNavigator:
Tab1
---MainScreen
---DetailScreen
Tab2

The problem is that I want to have swipe between tabs (Android) enabled in Tab1 and Tab2, but not when the Tab1 have DetailScreen on top (StackNavigator).

The overall result should behive like whatsapp: you have multiple tabs and one of them have stackNavigator, in this case the 'CHATS' tab, when you are in the tab view you can swipe to change tabs, but when you go to a specific chat, the tab header disapear (already achieved) and you are not longer able to swipe between tabs (NO IDEA ON HOW TO DO THAT).

Any idea on how to that??

**Comment by HoangTrung** [comment]
Try this.
```
static navigationOptions = {
        gesturesEnabled: false
}
```
Put it into the screen you wanna disable swiping

**Comment by arnaubennassar** [comment]
@HoangTrung  not working :(

**Comment by arnaubennassar** [comment]
I make it work by editing TabView.js:

in the render method:
...
const props = {
    lazy,
    animationEnabled,
    **swipeEnabled: !this.props.navigation.state.params.hideTabBar,//   (something meaningful of your redux implementation)**
    renderPager,
    renderHeader,
    ....
};
...
I won't close the issue because this is a hack, not a solution.

**Comment by kitolog** [comment]
@HoangTrung works for stack navigator, tnx

**Comment by git-hubber** [comment]
@arnaubennassar - can you give more explanation on your hack, and where you put it?  Iam having the same issue.  Thanks

**Comment by arnaubennassar** [comment]
@git-hubber Right now I'm on holidays and I don't have my laptop with me, so it's a bit hard to answer accurately, but I'll do my best.
The hack basically consist on hardcoding the value of the swipeEnabled, instead to pass it when creating the navigator, put a boolean of your navigation state, that will change according to the rest of your code. I dont remember how it was change the navigation state, but it was something like navigation.setParams(...). Im sure you will find hot to do this searching a bit on this repo.
The file I've edited is part of the library. You can find it under node_modules/react-navigation/(dont remember the rest of the path)/TabView.js

**Comment by JKonTiki** [comment]
thanks @arnaubennassar for the temp solution -- would love to hear if this does get API'd someday!

**Comment by alexwasner** [comment]
When I attempt to swipe back after disabling this prop, it doesnt animate, but it still pops into the previous view

**Comment by jhalborg** [comment]
+1 - would be great if it can be put into the API, preferably into static options so it works as @HoangTrung  suggested (which it doesn't)

**Comment by AndreiCalazans** [comment]
whats the state of this ?

**Comment by DarkSector** [comment]
Would love to see this is as an option. Any updates on this?

**Comment by kelset** [comment]
I don't know of any PR implementing this so feel free to open one ;)

**Comment by wlindner** [comment]
I have an app made up of a Tab Navigator with a couple tabs. One tab is a Stack Navigator. I want the ability to swipe left and right to switch between tabs, but then disable that swiping once I've navigated into the Stack Navigator within the tab.

Right now, when I navigate into the Stack Navigator I can still swipe to get to the other tab even though I'm hiding the tab bar. If I disable gestures using `gesturesEnabled: false` then the gesture to swipe back in the Stack Navigator also gets disabled, which is not what I want.

So, how can I only disable the tab swiping when I'm in the Stack Navigator, but not lose the swipe back gesture?

**Comment by carlos-proogresa** [comment]
I have same as @wlindner.  Any solution?

**Comment by JKonTiki** [comment]
i had the exact same situation, i.e. wanting to disable tab swiping when deeper into my nested stackNavigators. Here's an example of me implementing the suggested hack by @arnaubennassar, this is my `node_modules/react-navigation/src/views/TabView/TabView.js`

All I've done is hooked the component up to redux and passed it my navigation state object (nav), which is then parsed by a shuoldSwipeDisable function I wrote. It isn't ideal to hack it this way of course, but it definitely does the job. Just be careful of course w/ potentially wiping the code when you `npm install`

and as suggested above, instead of passing the nav state you can really just import one redux boolean that you somehow update in your app

```
/* @flow */

import React, { PureComponent } from 'react';
import { View, StyleSheet } from 'react-native';
import { TabViewAnimated, TabViewPagerPan } from 'react-native-tab-view';
import SceneView from '../SceneView';
import withCachedChildNavigation from '../../withCachedChildNavigation';
import { connect } from 'react-redux';
**import shouldSwipeDisable from'lib/helpers/shouldSwipeDisable';**

import type {
  NavigationScreenProp,
  NavigationRoute,
  NavigationAction,
  NavigationState,
  NavigationRouter,
  NavigationTabScreenOptions,
} from '../../TypeDefinition';

export type TabViewConfig = {
  tabBarComponent?: ReactClass<*>,
  tabBarPosition?: 'top' | 'bottom',
  tabBarOptions?: {},
  swipeEnabled?: boolean,
  animationEnabled?: boolean,
  lazy?: boolean,
};

export type TabScene = {
  route: NavigationRoute,
  focused: boolean,
  index: number,
  tintColor?: ?string,
};

type Props = {
  tabBarComponent?: ReactClass<*>,
  tabBarPosition?: 'top' | 'bottom',
  tabBarOptions?: {},
  swipeEnabled?: boolean,
  animationEnabled?: boolean,
  lazy?: boolean,

  screenProps?: {},
  navigation: NavigationScreenProp<NavigationState, NavigationAction>,
  router: NavigationRouter<
    NavigationState,
    NavigationAction,
    NavigationTabScreenOptions
  >,
  childNavigationProps: {
    [key: string]: NavigationScreenProp<NavigationRoute, NavigationAction>,
  },
};

class TabView extends PureComponent<void, Props, void> {
  props: Props;

  _handlePageChanged = (index: number) => {
    const { navigation } = this.props;
    navigation.navigate(navigation.state.routes[index].routeName);
  };

  _renderScene = ({ route }: any) => {
    const { screenProps } = this.props;
    const childNavigation = this.props.childNavigationProps[route.key];
    const TabComponent = this.props.router.getComponentForRouteName(
      route.routeName
    );
    return (
      <View style={styles.page}>
        <SceneView
          screenProps={screenProps}
          component={TabComponent}
          navigation={childNavigation}
        />
      </View>
    );
  };

  _getLabel = ({ route, tintColor, focused }: TabScene) => {
    const options = this.props.router.getScreenOptions(
      this.props.childNavigationProps[route.key],
      this.props.screenProps || {}
    );

    if (options.tabBarLabel) {
      return typeof options.tabBarLabel === 'function'
        ? options.tabBarLabel({ tintColor, focused })
        : options.tabBarLabel;
    }

    if (typeof options.title === 'string') {
      return options.title;
    }

    return route.routeName;
  };

  _renderIcon = ({ focused, route, tintColor }: TabScene) => {
    const options = this.props.router.getScreenOptions(
      this.props.childNavigationProps[route.key],
      this.props.screenProps || {}
    );
    if (options.tabBarIcon) {
      return typeof options.tabBarIcon === 'function'
        ? options.tabBarIcon({ tintColor, focused })
        : options.tabBarIcon;
    }
    return null;
  };

  _renderTabBar = (props: *) => {
    const {
      tabBarOptions,
      tabBarComponent: TabBarComponent,
      animationEnabled,
    } = this.props;
    if (typeof TabBarComponent === 'undefined') {
      return null;
    }
    return (
      <TabBarComponent
        {...props}
        {...tabBarOptions}
        navigation={this.props.navigation}
        getLabel={this._getLabel}
        renderIcon={this._renderIcon}
        animationEnabled={animationEnabled}
      />
    );
  };

  _renderPager = (props: *) => <TabViewPagerPan {...props} />;

  render() {
    const {
      router,
      tabBarComponent,
      tabBarPosition,
      animationEnabled,
      lazy,
      screenProps,
    } = this.props;

    **let { swipeEnabled } = this.props;
    if (shouldSwipeDisable(this.props.nav)) {
      swipeEnabled = false;
    }**

    let renderHeader;
    let renderFooter;
    let renderPager;

    const { state } = this.props.navigation;
    const options = router.getScreenOptions(
      this.props.childNavigationProps[state.routes[state.index].key],
      screenProps || {}
    );

    const tabBarVisible = options.tabBarVisible == null
      ? true
      : options.tabBarVisible;

    if (tabBarComponent !== undefined && tabBarVisible) {
      if (tabBarPosition === 'bottom') {
        renderFooter = this._renderTabBar;
      } else {
        renderHeader = this._renderTabBar;
      }
    }

    if (animationEnabled === false && swipeEnabled === false) {
      renderPager = this._renderPager;
    }

    const props = {
      lazy,
      animationEnabled,
      swipeEnabled,
      renderPager,
      renderHeader,
      renderFooter,
      renderScene: this._renderScene,
      onRequestChangeTab: this._handlePageChanged,
      navigationState: this.props.navigation.state,
      screenProps: this.props.screenProps,
      style: styles.container,
    };

    return <TabViewAnimated {...props} />;
  }
}

**function mapStateToProps(state) {
  return {
    nav: state.nav,
  };
}

function mapDispatchToProps(dispatch) {
  return {};
}


export default connect(mapStateToProps, mapDispatchToProps)(withCachedChildNavigation(TabView));**

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },

  page: {
    flex: 1,
    overflow: 'hidden',
  },
});

```

**Comment by cmpayc** [comment]
Edit ```node_modules/react-navigation/src/views/TabView/TabView.js``` and change render() func.
Delete ```swipeEnabled``` from start const
```javascript
const {
...
} = this.props;
```
After add new const:
```javascript
const swipeEnabled =
      options.swipeEnabled == null ? this.props.swipeEnabled : options.swipeEnabled; 
```
Now in your screen ```navigationOptions``` use: ```swipeEnabled: false```

**Comment by kelset** [comment]
Hey @cmpayc that looks like a viable solution, would you mind doing a PR with that modification?

**Comment by HighSoftWare96** [comment]
To dinamically change the navigationOptions (gesturesEnabled in this case) please see also this workaround:
[https://github.com/react-navigation/react-navigation/issues/1274#issuecomment-299170607](https://github.com/react-navigation/react-navigation/issues/1274#issuecomment-299170607)
