### ISSUE TITLE
TabNavigator Error: Cannot call a class as a function

### ISSUE THREAD

**Issue by potofpie** [react-community/react-navigation#1761]
I have a stack navigator up and running. This will then lead to a screen with 3 Tabs. I have followed the tutorial successfully but I cannot seem to get it to work on my project. Adisioally I am getting the **Error: Cannot call a Class as a function**.  I found 4 or 5 cases were this happened to others and followed there instructions but it does not seem to be working for my project. 
```
import React, { Component } from 'react';
import {
    AppRegistry,
    StyleSheet,
    Text,
    Image,
    TouchableHighlight,
    View
} from 'react-native';
import {
  StackNavigator,
} from 'react-navigation';

export default class Test1 extends React.Component {
static navigationOptions = {
  tabBarLabel: 'Home',
  tabBarIcon: ({ tintColor }) => (
    <Image
      source={require('./settings.png')}
      style={[styles.icon, {tintColor: tintColor}]}
    />
  ),
};
    render(){
        return (
            <View>
            <Text style={{margin: 10}} >Random Text</Text>
            </View>
        )
    }
}
class MyNotificationsScreen extends React.Component {
  static navigationOptions = {
    tabBarLabel: 'Notifications',
    tabBarIcon: ({ tintColor }) => (
      <Image
        source={require('./settings.png')}
        style={[styles.icon, {tintColor: tintColor}]}
      />
    ),
  };

  render() {
    return (
        <View>
        <Text style={{margin: 10}} >Random Text</Text>
        </View>
    );
  }
}
const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    backgroundColor: '#ecf0f1'
},
icon: {
  width: 26,
  height: 26,
},
});

const MyApp = Test1({
  Home: {
    screen: Test1,
  },
  Notifications: {
    screen: MyNotificationsScreen,
  },
}, {
  tabBarOptions: {
    activeTintColor: '#e91e63',
  },
});
```
Error:
![screen shot 2017-06-02 at 2 10 19 pm](https://cloud.githubusercontent.com/assets/15187309/26744954/3c39d9e2-479d-11e7-8b28-c8dedd297e78.png)

**Comment by potofpie** [comment]
Okay update. I change the line ```const MyApp = Test1({``` to ```const MyApp = new Test1({``` and there was no more error but there is no TabNav bar on the bottom.

**Comment by ajostergaard** [comment]
Perhaps I've misunderstood but I think you need to import `TabNavigator` and use `const MyApp = TabNavigator({`.

**Comment by potofpie** [comment]
Your right.... I can't believe I missed that.

**Comment by ajostergaard** [comment]
No worries - good luck! Don't forget to close the case if that issue is sorted now... :)
