### ISSUE TITLE
How to add icons in drawer menu?

### ISSUE THREAD

**Issue by valinsky** [react-community/react-navigation#1763]
Hello,

I just can't figure out how to add an icon in front of the menu items in the drawer menu
I've tried two different options without any luck; it's like the drawerIcon is ignored
I also tried to include the drawerIcon inside the Settings View but no luck still

```
const SettingsScreen = ({ navigation }) => (
  <Settings navigation={navigation} />
);
SettingsScreen.navigationOptions = {
  drawerIcon: ({ tintColor }) => (<HomeIcon name="home" size={24} style={{ color: tintColor }} />),
};

const WthrMap = DrawerNavigator({
  Home: { screen: MainStack,
    navigationOptions: {
      drawerIcon: ({ tintColor }) => (<HomeIcon name="home" size={24} style={{ color: tintColor }} />),
    }
   },
  Settings: { screen: SettingsScreen },
  About: { screen: About },
},{
  contentOptions: {
    activeTintColor: '#e91e63',
  },
  contentComponent: (props) =>
    <ScrollView>
      <TopDrawer />
      <DrawerView.Items {...props} />
    </ScrollView>
});
```

I want an icon in front of Home, Settings and About, but as shown in the screenshot no icon shows up, even though drawerIcon is defined for both Home and Settings.

![screenshot_20170603-012039](https://cloud.githubusercontent.com/assets/1455496/26750909/207b584e-47fb-11e7-962f-577a5ee33b81.png)

Thanks guys!

**Comment by ajostergaard** [comment]
Have you tried without `contentComponent`? Can't help wondering if `DrawerView.Items` is conflicting in some way.

**Comment by valinsky** [comment]
I found the issue finally. 
I haven't updated the local module in a while and i was using old code which didn't support this functionality.
After an upgrade and a quick refactor it works as intended.

**Comment by AbhishekDS-Userfacet** [comment]
Can I know how you were able to add icons for each tab @valinsky

**Comment by brentvatne** [comment]
hi there! this is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.
