### ISSUE TITLE
TabNavigation: Only the last tab seems to load/use components properly...?

### ISSUE THREAD

**Issue by mcampsall** [react-community/react-navigation#1765]
I have a very simple two tab app:

```
    import React, { Component } from 'react';
    import { AppRegistry } from 'react-native';
    import { TabNavigator } from 'react-navigation';
    
    import {
      Sports,
      News,
    } from 'externalComponents';
    
    const MyApp = TabNavigator({
      Sports: { screen: Sports },
      News: { screen: News },
    });
    
    AppRegistry.registerComponent('MyApp', () => MyApp);
```

The Sports and News components are provided by another company, and I cannot edit that code. If I load this into a `TabBarIOS` component, everything works fine and all tabs work as intended. 

However, with `react-navigation`, only the last tab loaded works properly.

Both the `News` and `Sports` components load a `JSONDownloadService` component like this:

`    downloadService = new JSONDownloadService(this);
`
And then it calls this:

`    downloadService.getJSON(this.state.url, type)
`
Now in `JSONDownloadService` because it has been passed the `NEWS` or `SPORTS` component in its constructor, it gets passed `updateComponent` (the part that is not getting called correctly). The `getJSON()` looks something like this:

```
    getJSON(url, type) {
      //set up vars...
        fetch(request, init)
            .then(function (response) {
              // ...some code
            })
            .then(function (response) {
                if (response) {
                    try {
                     // supposed to call `updateComponent` in News & Sports:
                        callback.updateComponent(response, type);
                    }
                    catch (err) {
                        console.log(err);
                    }
                }
            })
            .catch(function (error) {
                console.error(error);
            });
    }
```

The trouble is, `updateComponent()` is only ever called by the last component loaded in the tabBar. If I switch their positions, only the last one ever works. Except, if I comment out the code relating to `JSONDownloadService` in the last tab, THEN the first one works fine. It seems that whichever component last uses `JSONDownloadService` prevents the other tabs from being able to call `updateComponent`. How can I make this work using `react-navigation`?

**Comment by mcampsall** [comment]
There was a race condition going on in the other party's code, and when all the tabs try to load at once the `JSONDownloadService` couldn't handle it.

I tried `lazyLoad`, but it did not work. Then, 8 hours of tearing my hair out later, I saw that `lazyLoad` was changed to `lazy` and it worked!

**Comment by Adamnator92** [comment]
@mcampsall thank mate, it worked for me
