### ISSUE TITLE
[Question] Why use this instead of aksonov/react-native-router-flux?

### ISSUE THREAD

**Issue by jameskhamil** [react-community/react-navigation#1766]
I am curious why people are using this package instead of https://github.com/aksonov/react-native-router-flux?

There are many problems with this package like sane modal management. Is there some advantage I don't see?

**Comment by 0x6e6562** [comment]
@jameskhamil I find myself asking the same question - I have very quickly run into the short comings of react-navigation and am wondering whether there are some missing concepts in react-navigation or if it is just the case that this package is quite new and hence you shouldn't expect smooth sailing just yet.

**Comment by 0x6e6562** [comment]
To try to be more helpful to people trying to solve concrete issues and not spread FUD, whilst porting an existing ExNavigation app to this package the issues I ran into are:

* Not having an intuitive way to reset a `StackNavigator` that contained parallel child `StackNavigator` and `TabNavigator` instances - #1384 addresses this issue, but you would need to apply this patch manually.

* Not having access to the component state from the static navigation header context - I ended up implementing a custom header component that I could include in all of my screens. This requires plumbing the relevant navigators through to the header component and also rendering the header appropriately (i.e. with the correct flex styling). #1363 is a suggestion to take on board the ExNavigation solution for the static header context, so maybe that approach might gain traction or the project develops another solution for this problem.

At this point in time I couldn't comment whether RNRF addresses these problems in a more elegant way.

**Comment by JCMais** [comment]
@0x6e6562 have you tried RNRF?

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!

**Comment by 0x6e6562** [comment]
@JCMais Sorry for the radio silence, but no, I haven't used RNRF in anger yet. At the time when I posted this, I found myself having to rollback a port from ExNavigation to react-navigation. I still haven't revisited this area yet, but I know that ExNavigation is EOL'ed, so I will have to move away from it sooner or later.
