### ISSUE TITLE
How to make custom drawerItem

### ISSUE THREAD

**Issue by dominicsavb** [react-community/react-navigation#1767]
I want to make DrawerNavigator with Header Menu. 

for example:
Menu
-Home
-About
Product
-Wood
-Metal
-Gold
Info
-News

How to make like that?

Thank you

**Comment by undershot** [comment]
Maybe you should create your own class by extending original:
https://github.com/react-community/react-navigation/blob/master/src/views/Drawer/DrawerNavigatorItems.js

**Comment by dominicsavb** [comment]
@undershot Thank you for your respons

Can you show me the example? I really confuse...

**Comment by undershot** [comment]
For example:

Just copy code from https://github.com/react-community/react-navigation/blob/master/src/views/Drawer/DrawerNavigatorItems.js and change what you want. There is not class-based component, that you can't extends it like class extending. There is a simple function that render simple View.

**Comment by mstmustisnt** [comment]
This is simple. 
Render your headers as simple Views with your styles, render submenus as DrawerNavigationItems. and provide your compnent as contentComponent in options while creating DrawerNavigator instance.

**Comment by gamingumar** [comment]
You can create [custom drawer component](https://reactnavigation.org/docs/navigators/drawer#Providing-a-custom-contentComponent)
and use it in your navigator using contentComponent option.

**Comment by jainniket** [comment]
```
export const MenuNavigator = DrawerNavigator({
  DrawerMenu: {
    screen: StackNavigator({
      Screen1: {
        screen: Screen1,
        },
      },
      Screen2: {
        screen: Screen2,
      },
    }),
  },
}, {
  contentComponent: ({ navigation }) => (
    <Drawer navigation={navigation} />
  ),
});
```
Drawer is the custom component. you can make this component stateful vs stateless and render this in the drawer menu.

**Comment by mateofd** [comment]
This helped me to create a Custom Drawer Item. The key was in extending the getLabel function.
```javascript
contentComponent: (props) => (
            <View style={styles.sidebar}>
              <ScrollView>
                <DrawerItems
                  {...props}
                  getLabel = {(scene) => (
                    <View style={styles.button}>
                      <Text style={styles.buttonText}>{props.getLabel(scene)}</Text>
                    </View>
                  )}
                />
                </ScrollView>
              </View>
            )
```
Hope it helps.

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!

**Comment by kakulgupta** [comment]
You can find an explanation and  sample on https://medium.com/@kakul.gupta009/custom-drawer-using-react-navigation-80abbab489f7. Hoping it helps!

**Comment by kidequinox** [comment]
How to tell which item is active ?

**Comment by SatoshiInoue** [comment]
Thanks, @mateofd! I think the source code would help to customize further and at the same time keep at using DrawerItems tag: https://github.com/react-community/react-navigation/blob/master/src/views/Drawer/DrawerNavigatorItems.js

**Comment by AbhishekDS-Userfacet** [comment]
How to add icons to each category?

**Comment by brentvatne** [comment]
hi there! this is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.
