### ISSUE TITLE
How to set tabBarIcon from the state in navigationOptions (react-navigation)

### ISSUE THREAD

**Issue by ghost** [react-community/react-navigation#1769]
I want to do something just like this. i have image in my state but its showing me undefined error.I am using tabNavigator from react-navigation.

static navigationOptions = {

       tabBarIcon:  <Image source={{uri: this.state.userImage}} style={{width:30, height: 30}}/>

}

**Comment by dioxide** [comment]
+1 same problem

**Comment by andyhuai** [comment]
+1 same problem

**Comment by WildSpy** [comment]
+1

**Comment by nihgwu** [comment]
You can print `this` to see that it's not pointed to you component, so you can't access `this.state`, you can set the icon via `setParams`

**Comment by HanAsteroid** [comment]
<pre>
    static navigationOptions = {
    tabBarLabel: 'Notifications',
    tabBarIcon: ({ focused,tintColor }) => (
      focused ? &lt;Image
          source={require('./img/icon-account-selected.png')}
          style={[styles.icon, {tintColor: tintColor}]}
        /&gt;;
        :
        &lt;Image
          source={require('./img/icon-account.png')}
          style={[styles.icon, {tintColor: tintColor}]}
        /&gt;
    ),
  };
</pre>

**Comment by madeindjs** [comment]
+1 same problem

**Comment by elizamaria** [comment]
you will not do setState, you will do setParams
```
    this.props.navigation.setParams({inRide: true});
```
and in navigations options

```
 static navigationOptions = ({ navigation }) => {

    const { params } = navigation.state;
    return {
      header: null,
      tabBarIcon: ({focused}) => {
        if (params && params.inRide) {
          return (
            <Image
              source={Images.IN_RIDE}
            />
          );
        } 
        return (
          <Image
            source={Images.START_TRIP_ACTIVE}
          />
        )
```

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
