### ISSUE TITLE
How to load tab from server add to tab navigation 

### ISSUE THREAD

**Issue by yaraht17** [react-community/react-navigation#1770]
I have some catalog for product. In my app will call api get list catalog, a catalog corresponding
 a tab in tabbar(the amount of catalogs is dynamic)  catalog  I try like https://github.com/react-community/react-navigation/issues/1606, but not working. Please help, have sample is bestter
Thanks

**Comment by koenpunt** [comment]
@yaraht17 check my latest comment on #1606: https://github.com/react-community/react-navigation/issues/1606#issuecomment-307623883

**Comment by yaraht17** [comment]
@koenpunt  Thank for help! 👍  I think it working with me

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
