### ISSUE TITLE
How to know status drawer?

### ISSUE THREAD

**Issue by dominicsavb** [react-community/react-navigation#1771]
How to know status drawer is Open or is Close?? 

Thank you

**Comment by vigyanhoon** [comment]
+1

**Comment by callmetwan** [comment]
+1

**Comment by jainniket** [comment]
if you have connected this drawer component to redux, it is very easy to read the state.

Else when drawer opens or closes, action is dispatched.

```type(pin): "Navigation/NAVIGATE"
routeName(pin): "DrawerOpen"```

**Comment by skoob13** [comment]
Without Redux integration can be used **onNavigationStateChange** on router component. Just intercept drawer actions: **DrawerOpen** and **DrawerClose**.

Example:
```
  handleNavigationState = (previous, next, action) => {
    const route = get(next, 'routes[0]');
    if (route.routeName === 'tabs' && this.props.tab !== route.index) {
      this.props.setTab(route.index);
    }

    if (action.routeName === 'DrawerOpen') {
      this.props.setDrawerState(true);
    } else if (action.routeName === 'DrawerClose') {
      this.props.setDrawerState(false);
    }
  }

  render() {
    return (
      <Router onNavigationStateChange={this.handleNavigationState} />
    );
  }
```

**Comment by callmetwan** [comment]
@skoob13 Thanks so much for this! I personally decided to go ahead and get Redux hooked up (that was the plan all along, the project just wasn't at a place that it needed a state manager).

[I also asked this on SO](https://stackoverflow.com/questions/44574976/status-of-react-navigation-drawer-open-or-closed). If you'd like to post your answer there, I'd be happy to accept it as the answered question (figured it'd be helpful to disseminate this to as many places as possible. I'm clearly not the only one with this issues). Get those sweet, sweet internet points.

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!

**Comment by hodgef** [comment]
After some digging, this is what worked for me: `this.props.navigation.state.isDrawerOpen`.

**Comment by giantss** [comment]
+1，I found that when the user slid open the sidebar, I can't know that he has already opened it. My requirement is to reload the data each time I open the sidebar.

**Comment by farzer** [comment]
better if i am listen the drawer status only use react-navigation

**Comment by hodgef** [comment]
@RuthenicEye In my case, I wanted to call a function each time the drawer was opened. So on my [custom drawers' `contentComponent`](https://codeburst.io/custom-drawer-using-react-navigation-80abbab489f7) I set:

e.g:
```
class DrawerContentComponent extends Component {
 [...]
  componentWillReceiveProps = (nextProps) => {
    if(nextProps.navigation.state.isDrawerOpen){
      // Example
      this.myMethod();
    }
  }
[...]
```

This works since the `componentWillReceiveProps` method will be fired every time the props passed change (such as `isDrawerOpen`).

Hope that helps!

**Comment by RuthenicEye** [comment]
I tried the above method it works. Thank you @hodgef for sharing with us. here's the screen shot 
![screenshot_1540896074](https://user-images.githubusercontent.com/43641800/47712730-4f46af80-dc5a-11e8-9ec0-bd80ecdcbd16.png)

**Comment by sajera** [comment]
Actually you have "toggleDrawer" it means you have this data (drawer state open/close) inside the library. May be may sens to provide functionality to read it outside ?

**Comment by mehmetnyarar** [comment]
> Without Redux integration can be used **onNavigationStateChange** on router component. Just intercept drawer actions: **DrawerOpen** and **DrawerClose**.
> 
> Example:
> 
> ```
>   handleNavigationState = (previous, next, action) => {
>     const route = get(next, 'routes[0]');
>     if (route.routeName === 'tabs' && this.props.tab !== route.index) {
>       this.props.setTab(route.index);
>     }
> 
>     if (action.routeName === 'DrawerOpen') {
>       this.props.setDrawerState(true);
>     } else if (action.routeName === 'DrawerClose') {
>       this.props.setDrawerState(false);
>     }
>   }
> 
>   render() {
>     return (
>       <Router onNavigationStateChange={this.handleNavigationState} />
>     );
>   }
> ```

As of version `4.0.10`

```ts
interface HandleNavigationStateChange {
  (
    prev: NavigationState,
    next: NavigationState,
    action: NavigationAction
  ): void
}

export const handleNavigationStateChange: HandleNavigationStateChange = (_, __, action) => {
  if (action.type === 'Navigation/TOGGLE_DRAWER') {
    _drawerOpen = true
  } else if (action.type === 'Navigation/CLOSE_DRAWER') {
    _drawerOpen = false
  }
}
```
