### ISSUE TITLE
headerRight of navigationOptions not able to access "this.refs"

### ISSUE THREAD

**Issue by cfs5403** [react-community/react-navigation#1772]
### Current Behavior
the headerRight of navigationOptions not able to access to this.refs. I get this error "undefined is not an object (evaluating 'this.refs[WEBVIEW_REF]')". The alert method under refreshHandler() able to work but the "this.refs[WEBVIEW_REF].reload()" not work.

below is my code
```

import { WebView } from 'react-native'
import React, { PropTypes, Component } from 'react';
import { Modal, ActivityIndicator, View, Text, Button } from 'react-native';

var WEBVIEW_REF = 'webview';

class WebViewComponent extends Component {
    constructor(props) {
        super(props);
    }

    static navigationOptions = ({navigation}) => {
        const {params = {}} = navigation.state;
        return {
            title: navigation.state.params.title,
            headerRight: <Button
                             title="Refresh"
                             onPress={ () => params.handleRefresh() } />

        };
    };

    componentDidMount() {
        this.props.navigation.setParams({
            handleRefresh: this.refreshHandler
        });
    }

    refreshHandler() {
        alert('hello')
        this.refs[WEBVIEW_REF].reload()
    }

    render() {
        const {state} = this.props.navigation;
        const {url} = state.params;

        return (
            <WebView
                ref={ WEBVIEW_REF }
                style={ { flex: 1 } }
                source={ { uri: url } }
                scalesPageToFit={ true }
                startInLoadingState={ true }
                renderError={ () => this.loadError() } />
            );
    }


    loadError() {
        return (
            <View style={ { flex: 1, alignItems: 'center', justifyContent: 'center', margin: 20 } }>
                <Text style={ { fontSize: 18, fontWeight: 'normal', textAlign: 'center' } }>
                    Not able to load content. Please check your internet connection and try again.
                </Text>
            </View>
        )
    }

}

module.exports = WebViewComponent;

```
### Expected Behavior
Should able to call this.refs on headerRight.

### Your Environment
| software         | version
| ---------------- | -------
| react-navigation |  16.0.0-alpha.6
| react-native     |  0.44.2
| node             | 7.0.0
| npm or yarn      |3.10.8

**Comment by Exilz** [comment]
It's `static` so it's not supposed to work, you can't reach the reference to your class in there.

**Comment by cfs5403** [comment]
@Exilz so there is no way I can access this.refs? Because I need to the right button to refresh my webview. Thanks.

**Comment by cfs5403** [comment]
Okay I finally solve it, I will answer my own question
**Solution**
Declare a 'self' variable outside class, then assign it to 'this' inside class constructor. Then self.refs[WEBVIEW_REF].reload()

```
import { WebView } from 'react-native'
import React, { PropTypes, Component } from 'react';
import { Modal, ActivityIndicator, View, Text, Button } from 'react-native';

var WEBVIEW_REF = 'webview';
var self
class WebViewComponent extends Component {
    constructor(props) {
        super(props);
        self = this
    }

    static navigationOptions = ({navigation}) => {
        const {params = {}} = navigation.state;
        return {
            title: navigation.state.params.title,
            headerRight: <Button
                             title="Refresh"
                             onPress={ () => params.handleRefresh() } />

        };
    };

    componentDidMount() {
        this.props.navigation.setParams({
            handleRefresh: this.refreshHandler
        });
    }

    refreshHandler() {
        alert('hello')
        self.refs[WEBVIEW_REF].reload()
    }

    render() {
        const {state} = this.props.navigation;
        const {url} = state.params;

        return (
            <WebView
                ref={ WEBVIEW_REF }
                style={ { flex: 1 } }
                source={ { uri: url } }
                scalesPageToFit={ true }
                startInLoadingState={ true }
                renderError={ () => this.loadError() } />
            );
    }


    loadError() {
        return (
            <View style={ { flex: 1, alignItems: 'center', justifyContent: 'center', margin: 20 } }>
                <Text style={ { fontSize: 18, fontWeight: 'normal', textAlign: 'center' } }>
                    Not able to load content. Please check your internet connection and try again.
                </Text>
            </View>
        )
    }

}

module.exports = WebViewComponent;
```

**Comment by gregblass** [comment]
This is so hackish...

**Comment by agersoncgps** [comment]
Is there a better way..?

**Comment by Exilz** [comment]
@agersoncgps I usually dispatch redux actions for that. It's quite cumbersome to write, but it does the job pretty well.

**Comment by saeropark** [comment]
HI, just wanna say thank you. your hack helps me so much!

**Comment by Nickersoft** [comment]
Hi guys, I know this thread is closed but I'm also facing this same issue and am wondering if there's a better way. @Exilz, would you care to elaborate on how redux dispatching comes into play? The dispatch function would still be in the component's props, right? Wouldn't you still need access to `this` to call that function? Forgive me, I'm new to Redux. I noticed a [similar question](https://github.com/react-community/react-navigation/issues/1989) was asked a bit more recently, and it doesn't have a solid answer either. Is this hack really the only way to go?

**Comment by Exilz** [comment]
Here's how I do it

I set up my button as a custom component in my routes files, something like this

`routes.js`
```javascript
    map: {
        screen: views.Map,
        navigationOptions: ({ navigation }) => ({
            ...defaultHeaderOptions(navigation), // ignore this
            headerRight: <ListButton />
        })
    }
```

In my `ListButton`, I now need to dispatch an action that will toggle the list mode, so I can switch between my map and my list of POIs.

To do so, I can either import my redux store and do `store.dispatch(toggleListMode())` or connect the whole component with `react-redux`. I'll use the second method.

`ListButton.js`
```javascript
import { actions } from 'app/src/redux/modules/userInterface';
import { connect } from 'react-redux';
...

const mapStateToProps = (state) => ({
    listMode: state.userInterface.listMode
});

class ListButton extends Component {
    static propTypes = {
        toggleListMode: PropTypes.func.isRequired,
        listMode: PropTypes.bool.isRequired
    }

    render () {
        return (
            <TouchableComponent
              onPress={toggleListMode}
            >
...
            </TouchableComponent>
        );
    }
}

export default connect(mapStateToProps, actions)(ListButton);
```

Now, all I have to do is subscribe to my `listMode` boolean from my `userInterface` store to switch between the map and the list.

`Map.js`
```javascript
const mapStateToProps = (state, props) => {
    return { displayList: state.userInterface.listMode };
};
...
```

![](https://media.giphy.com/media/l4FsDpq1a8GN5Q7wk/giphy.gif)

**Comment by jjdp** [comment]
It really depends on how you want to control it whether redux or some other state management lib. Declaring `self` is ok.

**Comment by askielboe** [comment]
I ran into a similar problem. None of the methods to access `this` or `navigation.params` in `static navigationOptions` worked for me, and in any case seemed overly hacky.

I ended up creating a custom React component like @Exilz that takes `navigation` as a prop and dispatches an action to hide the current stack navigator.

Here is the `HideButton`component I put on the header to hide a `StackNavigator` (don't mind the boilerplate):

```typescript
import React, { Component } from 'react'
import { connect } from 'react-redux'
import { Dispatch, bindActionCreators } from 'redux'

import { Button } from 'react-native'

interface Action<T> {
    type: string
    payload?: T
    error?: boolean
    meta?: any
}

export const HIDE_STACK_NAVIGATOR = 'HIDE_STACK_NAVIGATOR'
export type HIDE_STACK_NAVIGATOR = { }

function hideStackNavigatorAction(navigation): Action<HIDE_STACK_NAVIGATOR> {
    return {
        type: HIDE_STACK_NAVIGATOR,
        payload: navigation
    }
}

interface Props {
    navigation: any,
    hideStackNavigator(navigation: any): Function
}

function mapDispatchToProps(dispatch) {
    return {
        hideStackNavigator: (navigation) => dispatch(hideStackNavigatorAction(navigation))
    }
}

class HideButton extends React.Component<Props, undefined> {
    render() {
        return (
            <Button
                title='Hide'
                onPress={() => this.props.hideStackNavigator(this.props.navigation)}
            />
        )
    }
}

export default connect(
    undefined,
    mapDispatchToProps)
(HideButton)
```

**Comment by jjdp** [comment]
you can also trigger some action like pressing a button on your header then call `navigation.setParams` and do whatever you want in `componentWillReceiveProps`

**Comment by mahesh963** [comment]
Hi, guys i want to navigate my screen to another screen when clicking on the right header button.
Can any one please suggest me how to do this.
`  static navigationOptions = {
      title:'Map',
      headerTintColor: 'white',
      headerStyle: { backgroundColor: '#f55e69', borderWidth: 1, borderColor: '#f55e66' },
      headerTitleStyle: { color: 'white' },
      headerRight: <Button title="Details" onPress={() => alert('clicked')}/>
}`
In that onPress function i want to navigate from current screen(file) to another screen(file)

**Comment by callagga** [comment]
what's the background on this by the way?  Is there a reason reactnavigation requires the config to be set in a "static" variable?  then from the fact it is static it thens implies the hoops required one has to jump through as noted here and https://reactnavigation.org/docs/intro/headers#Header-interaction-with-screen-component?
(bit of a newbie to react-native here)
