### ISSUE TITLE
Drawer on RTL is not converting properly

### ISSUE THREAD

**Issue by adlahd3** [react-community/react-navigation#1773]
### Current Behavior
I am Developing a multi-language app, a drawer is used for navigation.
In the English Version, it seems OK.
in the Arabic Version ( RTL ) It looks weird:
1- It Shows Part of drawer. 
![1](https://cloud.githubusercontent.com/assets/8708387/26784069/3d24e9a0-4a04-11e7-83fd-8e679562401a.png)

2- When Drag to full extent it goes all the way to the other side of screen. 
![2](https://cloud.githubusercontent.com/assets/8708387/26784077/518acf86-4a04-11e7-9487-70d94791640b.png)

### Expected Behavior
1- Completely Hidden. 
2- Only Scrolls to the right side of screen.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.9
| react-native     |  0.44.0
| node             | 7.8.0
| npm or yarn      | 0.22.0

**Comment by spencercarli** [comment]
A small demo of this would be helpful to aid in debugging!

**Comment by coreform** [comment]
It seems like the Drawer is hinging on (or mirroring on) the left edge of the HeaderLeft (which is typically a hamburger icon), where it should hinge off the end of the header (left edge for LTR and right edge for RTL).

**Comment by kelset** [comment]
Closing in favor of #270
