### ISSUE TITLE
Invalid prop 'children' when core-js is imported

### ISSUE THREAD

**Issue by adam-denny** [react-community/react-navigation#1775]
Importing 'core-js' anywhere in my project causes react-navigation to throw a warning: 
`
Warning: Failed prop type: Invalid prop 'children' supplied to 'TabViewPagerAndroid', expected a ReactNode.`

This doesn't seem to be affecting functionality in any way, just the warning popping up each time I reload is annoying.

**Comment by spencercarli** [comment]
Please provide a demo of this issue. Until then I'm going to close this issue. Thanks!

**Comment by scottmas** [comment]
Can confirm this is still happening. No time right now to create a Snack repro, but maybe will get to it.

**Comment by brentvatne** [comment]
seems like a corejs bug?
