### ISSUE TITLE
Implement my side menu as  a DrawerNavigator

### ISSUE THREAD

**Issue by HoangTrung** [react-community/react-navigation#1776]
I did make a side menu effect like this https://www.youtube.com/watch?v=kiuhNbbL8hM.
Is it possible for me to implement it as a DrawerNavigator? or is there a way to custom the DrawerNavigator to be like this?

**Comment by spencercarli** [comment]
I think StackOverflow would be a better place for this question. Good luck! Would be a cool effect!

**Comment by ioanaverebi** [comment]
Hi @HoangTrung 
Did you manage to implement this using the DrawerNavigator?
