### ISSUE TITLE
react-navigation fails to install

### ISSUE THREAD

**Issue by sclanc** [react-community/react-navigation#1782]
After trying all suggested solutions in issue #923 I am still experiencing the same problem. interestingly, React-Navigation worked fine on my windows computer. I don't have access to what version of RN it was running.

current behavior:  react-navigation will not install because of peer dependencies 
expected: react-navigation installs successfully

OS: Ubuntu 16.04.2 LTS

package.json: 

      "name": "RallyMobile",
      "version": "0.0.1",
      "private": true,
      "scripts": {
        "start": "node node_modules/react-native/local-cli/cli.js start",
        "test": "jest"
      },
      "dependencies": {
        "react": "16.0.0-alpha.6",
        "react-native": "0.43.3",
        "react-native-drawer": "^2.3.0",
        "react-navigation": "git+https://github.com/react-community/react-navigation.git"
      },
      "devDependencies": {
        "babel-jest": "20.0.3",
        "babel-preset-react-native": "1.9.2",
        "jest": "20.0.3",
        "react-test-renderer": "16.0.0-alpha.6"
      },
      "jest": {
        "preset": "react-native"
      }
    }

npm-debug: 

 verbose validateInstall loading /home/sean/dev/Work/package.json for validation
 verbose stack Error: The package react@16.0.0-alpha.6 does not satisfy its siblings' peerDependencies requirements!
verbose stack     at /usr/lib/node_modules/npm/lib/install.js:125:32
verbose stack     at /usr/lib/node_modules/npm/lib/install.js:268:7
verbose stack     at /usr/lib/node_modules/npm/node_modules/read-installed/read-installed.js:142:5
verbose stack     at /usr/lib/node_modules/npm/node_modules/read-installed/read-installed.js:263:14
verbose stack     at cb (/usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
verbose stack     at /usr/lib/node_modules/npm/node_modules/read-installed/read-installed.js:263:14
verbose stack     at cb (/usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
verbose stack     at /usr/lib/node_modules/npm/node_modules/read-installed/read-installed.js:263:14
verbose stack     at cb (/usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
verbose stack     at /usr/lib/node_modules/npm/node_modules/read-installed/read-installed.js:263:14
verbose cwd /home/sean/dev/Work
error Linux 4.4.0-78-generic
error argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
error node v4.4.3
error npm  v2.15.1
error code EPEERINVALID
error peerinvalid The package react@16.0.0-alpha.6 does not satisfy its siblings' peerDependencies requirements!
error peerinvalid Peer react-native@0.43.3 wants react@16.0.0-alpha.6
error peerinvalid Peer react-navigation@1.0.0-beta.11 wants react@*
error peerinvalid Peer react-test-renderer@16.0.0-alpha.6 wants react@^16.0.0-alpha.6
verbose exit [ 1, true ]

**Comment by spencercarli** [comment]
Using the master branch is always iffy as it's hard/impossible to reproduce. Please try this with an release and if the issue persists we can dive deeper
