### ISSUE TITLE
_this3... is not a function

### ISSUE THREAD

**Issue by DanielDziubecki** [react-community/react-navigation#1784]
Hello, Im trying to develop searchBar in react navigation header but I've get this error 
> _this3.handleResult is not a function

How to fix this?
 **Secondly I wanted to access component state in this static navigationOptions but it seems impossible.**

```
    static navigationOptions = {
        headerRight: <SearchBar
                containerStyle={Styles.searchBarContainer}
                inputStyle={Styles.searchBarInput}
                placeholderTextColor={"#16c5cc"}
                textInputRef={(input) => { this.searchingText = input; }}
                onChangeText={(searchingText) => this.handleResults(searchingText)}
                placeholder='Search..'/>
    }
```

**Comment by yasserzubair** [comment]
You cannot access your component's functions inside a static varaible, that is the basic concept of static variables.

**Comment by DanielDziubecki** [comment]
There is any workaround?

**Comment by theohdv** [comment]
Maybe you can create your own component for the headerRight. Then inside this component you'll be able to manage state of this one.

**Comment by samridhgupta** [comment]
https://github.com/react-community/react-navigation/issues/145

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
