### ISSUE TITLE
Keep default Icons in StackNavigator headerLeft but change function

### ISSUE THREAD

**Issue by nprz** [react-community/react-navigation#1788]
I would like to change the function passed to the headerLeft icon on the StackNavigator without changing the icons. Currently the back buttons do not do anything. I believe this is because I am using redux and when I press the back button it does not update the state held in the store. So what needs to happen is the back button needs to fire the actionCreator which will update the store with the correct state. I want to keep the icons as they are so I don't need to write the extra code to target iOS and android to conditionally show the correct icons. Here is a gif which visually illustrates my conundrum. 
![back](https://user-images.githubusercontent.com/17592222/26858871-f3695450-4b01-11e7-9e97-041b81ed32f6.gif)

**Comment by nprz** [comment]
Is there anyway to pass the icon a function without changing the icon?

**Comment by CarlosJJR** [comment]
@nprz pease refer to #2372. I think it is exactly what you need.

**Comment by kelset** [comment]
Hey @nprz can you check if PR #2712 is suitable for what you want to achieve?

**Comment by vonovak** [comment]
A PR which allows to customize the back button behaviour was recently merged: #2712

Since the mentioned PR covers the ability to customize the function called with pressing the button, I'll close this as it is resolved in master.
