### ISSUE TITLE
Cannot access state variables inside navigationOptions

### ISSUE THREAD

**Issue by yasserzubair** [react-community/react-navigation#1789]
### Current Behavior
I need to acces state variable inside the static navigation options. I have a button on the headerRight and I want to change state when that button is pressed. Turns out, state cannot be accessed inside the static navigationOptions. Please provide a solution or workaround.
### Expected Behavior
State variables should be accesible inside navigationOptions

**Comment by cfs5403** [comment]
```
    static navigationOptions = ({navigation}) => {
        const {params = {}} = navigation.state;
        return {
            headerRight: <Button
                             title="Refresh"
                             onPress={ () => params.handleThis() } />

        };
    };

    componentDidMount() {
        this.props.navigation.setParams({
            handleThis: this.changeButtonColorHandler
        });
    }

    refreshHandler() {
        this.setState({
            stateA: state
        })
    }
```

**Comment by yasserzubair** [comment]
you mean to say 

`    static navigationOptions = ({navigation}) => {
        const {params = {}} = navigation.state;
        return {
            headerRight: <Button
                             title="Refresh"
                             onPress={ () => params.handleThis() } />

        };
    };

    componentDidMount() {
        this.props.navigation.setParams({
            handleThis: this.refreshHandler
        });
    }

    refreshHandler() {
        this.setState({
            stateA: state
        })
    }`

this.refreshHandler instead of this.changeButtonColorHandler or vice versa ?

**Comment by cfs5403** [comment]
@yasserzubair typo just now, edited

**Comment by spencercarli** [comment]
Sending data via setParams is the only way to do so

**Comment by SamiChab** [comment]
using setParams is also very slow in my case...

**Comment by alvelig** [comment]
Connect the component to the store... Seems like there's no other nice option.

**Comment by Johncy1997** [comment]
`this.state={
labelname:null
}   
this.props.data.offerstitle.map((item)=>{
       this.state.labelname=item.ColumnOne;
              } )
static navigationOptions={
        tabBarLabel: this.state.labelname
                                     }
`
please someone tell me how to access the labelname for setting the tabBarLabel.

**Comment by marceloHashzen** [comment]
Is it possible to receive some parameters from inside the header component?

this is my code:

```
export default class Search extends Component {
  static navigationOptions = ({ navigation }) => {
    const { params = {} } = navigation.state;

    return {
      headerLeft: (
        <SearchHeader
          navigation={navigation}
          onTextChange={() => params.handleTextChange()}
        />
      ),
    };
  };

  componentDidMount() {
    this.props.navigation.setParams({
      handleTextChange: this.checkTextChange,
    });
  }

  checkTextChange = (text) => {
    console.tron.log(text);
  }

  render() {
    return (
      <View style={styles.container}>
        <Text>Search screen</Text>
      </View>
    );
  }
}
```

```
export default class SearchHeader extends React.Component {
  state = {
    search: '',
  }

  handleCancelSearch = () => {
    this.props.navigation.goBack(null);
  }

  handleTextChange = (text) => {
    this.setState({ search: text });
    this.props.onTextChange(text);
  }

  render() {
    return (
      <View style={styles.navbar}>
        <View style={styles.search}>
          <Icon name="search" style={styles.navbarIcon} />
          <TextInput
            autoFocus
            autoCorrect={false}
            placeholder="Digite o que você procura"
            placeholderTextColor={colors.fadedWhite}
            style={styles.searchInput}
            underlineColorAndroid={colors.transparent}
            onChangeText={search => this.handleTextChange(search)}
            value={this.state.search}
          />
        </View>
        <Icon name="x" style={styles.navbarIcon} onPress={() => this.handleCancelSearch()} />
      </View>
    );
  }
}
```

The checkTextChange() function is called, but the text parameter is allways undefined.
I nedd to get this value to trigger a request inside the Search.js component.

**Comment by brentvatne** [comment]
@marceloHashzen - check out the params section in lecture 6 at https://cs50.github.io/mobile/lectures

**Comment by brentvatne** [comment]
if you're interested in discussing improving the solution for this (something better than `setParams`) then check out this thread: https://github.com/react-navigation/rfcs/issues/24
