### ISSUE TITLE
Request: Example showing complex integration of DrawerNavigator, TabNavigator, StackNavigator

### ISSUE THREAD

**Issue by arashz** [react-community/react-navigation#179]
It would be greatly helpful to see a full example showing DrawerNavigator, TabNavigator and Stack Navigator used together. 

I propose a structure like the following : 
![screen shot 2017-02-04 at 2 14 40 pm](https://cloud.githubusercontent.com/assets/782945/22621946/5b5493aa-eae4-11e6-8b10-1183035294c3.png)

**Comment by si-harps** [comment]
Agreed, this would be helpful. I'm working on a similar structure that would allow tabs to be visible for the majority of the UX by nesting stackNavigators inside tabNavigator Screens. The root of the app is a stackNavigator component with its initial screen set to the afore mentioned tabNavigator. The root stackNavigator contains cards such as login and a couple of other full screen modals. Will post code so far if it will help

**Comment by grabbou** [comment]
If there's no-one working on that, I'll try to submit a PR with an implemented basics in a second.

**Comment by grabbou** [comment]
@si-harps would you be open to contributing back your work? Would be great if you could send over anything you got as an example to demonstrate more advanced use-cases.

If you need any help on how to get moving, let me know!

**Comment by si-harps** [comment]
@grabbou, i'd be happy to contribute. I'll tidy the codebase up a little, with a view to get something over to you at the weekend.

Please let me know how to proceed.

**Comment by grabbou** [comment]
Sure! Ping me here when you are done. Basically what you can do is you can create a `Complex` example and add it to the playground. This PR adds a standalone example for other feature, so you might want to base your work on it: https://github.com/react-community/react-navigation/pull/137/files#diff-8dc8447e85c7816cfb55d178e20eb2c7R67

**Comment by si-harps** [comment]
HI @grabbou, please take a look here https://github.com/si-harps/RNExperimental. Its not based on the example you provided but see what you think.

**Comment by rafaelmmathias** [comment]
@si-harps, thank you! Look the gif below, the drawer is showing above the header bar and tabbar too.
I'll commit the code in https://github.com/rafaelmmathias/RNExperimental.

![screeniphone](https://cloud.githubusercontent.com/assets/21037492/22863974/046f1d2e-f130-11e6-92e5-30f7fa3646c7.gif)

**Comment by si-harps** [comment]
@rafaelmmathias, thanks for this. @grabbou, we've got a half decent example of a more complex structure now, are you keen to use this in the project?

**Comment by grabbou** [comment]
@si-harps thanks! that's an awesome piece of work! Do you feel like integrating that into react-navigation examples and opening a pull request? that would make it easier for a lot of people to try out!

**Comment by si-harps** [comment]
Hi @grabbou, apologies for silence! Just created pull request https://github.com/react-community/react-navigation/pull/428

**Comment by ali-hellani** [comment]
where i can find this working example?

**Comment by AlmogRnD** [comment]
+1

**Comment by rafael-trevisan** [comment]
+1

**Comment by kelset** [comment]
Small update: we are currently working on some more complex examples; in the meantime, we added in the README some links to full prod level solutions.
