### ISSUE TITLE
Error when using jest as an unit test

### ISSUE THREAD

**Issue by marianaMarshaL** [react-community/react-navigation#1792]
Hi,

When i try to run unit test using jest. I got this error:

.../node_modules/react-navigation/src/navigators/StackNavigator.js:3
    import React from 'react';
    ^^^^^^
    SyntaxError: Unexpected token import
      
      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/ScriptTransformer.js:289:17)
      at Object.get StackNavigator [as StackNavigator] (node_modules/react-navigation/src/react-navigation.js:16:33)
      at Object.<anonymous> (app/container/tab/tabHome/navigationConfiguration.js:17:89)

Here my package.json:
"dependencies": {
    "react": "16.0.0-alpha.6",
    "react-native": "0.44.0",
    "react-native-calendar": "^0.11.0",
	  "react-redux": "^3.1.0",
    "redux": "^3.0.4",
    "react-native-svg": "4.5.0",
    "victory-native": "~0.4.0",
    "react-native-swiper": "1.5.4",
    "react-navigation": "^1.0.0-beta.9",
    "redux-logger": "^2.8.1"
  },
  "devDependencies": {
    "babel-jest": "20.0.1",
    "babel-preset-react-native": "1.9.2",
    "jest": "20.0.1",
    "react-test-renderer": "16.0.0-alpha.6"
  },
  "jest": {
    "preset": "react-native"
  },
  "module": {
    "loaders": [
      {
        "": ""
      }
    ]
  },
  "rnpm": {
    "assets": [
        "src/main/resources/photon/fonts"
    ]
  }

**Comment by TyrealGray** [comment]
This is what I wrote in my package.json:
```
"jest": {
    "preset": "react-native",
    "collectCoverage": true,
    "coverageDirectory": "__coverage__",
    "testRegex": "./__tests__/[^setup].*.js$",
    "transformIgnorePatterns": ["node_modules/(?!react-native|native-base|react-navigation|react-native-fabric)"],
    "setupFiles": [
      "./__tests__/setup.js"
    ]
  }
```
I have a folder names "__test__" and under it is a setup.js file to control all the component I mocked:

```
//setup.js
jest.mock('Linking', () => {
    return {
        addEventListener: jest.fn(),
        removeEventListener: jest.fn(),
        openURL: jest.fn(),
        canOpenURL: jest.fn(),
        getInitialURL: jest.fn(),
    }
})

jest.mock('react-native-fabric', () => {
    return {
        Crashlytics: {
            crash: () => {},
        },
        Answers: {
            logCustom: () => {},
            logContentView: () => {},
        },
    }
})

jest.mock('WebView', () => 'WebView');

jest.mock('DatePickerIOS', () => 'DatePickerIOS');
```

**Comment by marianaMarshaL** [comment]
Thanks it's working now

**Comment by marianaMarshaL** [comment]
Hi

i got another issue:
 FAIL  __tests__/container/TestRootContainer.js
  ● Console
    console.error node_modules/react-native/Libraries/Core/ExceptionsManager.js:71
      React caught an error thrown by TabView. You should fix this error in your code. Consider adding an error boundary to your tree to customize error handling behavior.

      TypeError: deprecatedKeys.includes is not a function   

      The error is located at: 
          in TabView (created by withCachedChildNavigation(TabView))
          in withCachedChildNavigation(TabView)
          in Unknown (created by Navigator)
          in Navigator (created by NavigationContainer)
          in NavigationContainer (created by MenuBarContainer)
          in MenuBarContainer (created by Connect(MenuBarContainer))
          in Connect(MenuBarContainer) (created by RootContainer)
          in Provider (created by RootContainer)
          in RootContainer

      The error was thrown at: 
          at /Users/c07nw8xpg1hw/phtn-digital-onboarding/digital_onboarding/node_modules/react-navigation/src/routers/validateScreenOptions.js:15:65,
          at Array.find (native),
          at exports.default (/Users/c07nw8xpg1hw/phtn-digital-onboarding/digital_onboarding/node_modules/react-navigation/src/routers/validateScreenOptions.js:15:24),
          at Object.getScreenOptions (/Users/c07nw8xpg1hw/phtn-digital-onboarding/digital_onboarding/node_modules/react-navigation/src/routers/createConfigGetter.js:100:36),
          at TabView.render (/Users/c07nw8xpg1hw/phtn-digital-onboarding/digital_onboarding/node_modules/react-navigation/src/views/TabView/TabView.js:150:20),
          at finishClassComponent (/Users/c07nw8xpg1hw/phtn-digital-onboarding/digital_onboarding/node_modules/react-test-renderer/lib/ReactFiberBeginWork.js:248:31),
          at updateClassComponent (/Users/c07nw8xpg1hw/phtn-digital-onboarding/digital_onboarding/node_modules/react-test-renderer/lib/ReactFiberBeginWork.js:230:12),
          at beginWork (/Users/c07nw8xpg1hw/phtn-digital-onboarding/digital_onboarding/node_modules/react-test-renderer/lib/ReactFiberBeginWork.js:643:16),
          at performUnitOfWork (/Users/c07nw8xpg1hw/phtn-digital-onboarding/digital_onboarding/node_modules/react-test-renderer/lib/ReactFiberScheduler.js:634:16),
          at workLoop (/Users/c07nw8xpg1hw/phtn-digital-onboarding/digital_onboarding/node_modules/react-test-renderer/lib/ReactFiberScheduler.js:763:26)
  ● renders correctly

    TypeError: deprecatedKeys.includes is not a function

      at node_modules/react-navigation/src/routers/validateScreenOptions.js:15:65
      at Array.find (native)
      at exports.default (node_modules/react-navigation/src/routers/validateScreenOptions.js:15:24)
      at Object.getScreenOptions (node_modules/react-navigation/src/routers/createConfigGetter.js:100:36)
      at TabView.render (node_modules/react-navigation/src/views/TabView/TabView.js:150:20)
      at finishClassComponent (node_modules/react-test-renderer/lib/ReactFiberBeginWork.js:248:31)
      at updateClassComponent (node_modules/react-test-renderer/lib/ReactFiberBeginWork.js:230:12)
      at beginWork (node_modules/react-test-renderer/lib/ReactFiberBeginWork.js:643:16)
      at performUnitOfWork (node_modules/react-test-renderer/lib/ReactFiberScheduler.js:634:16)
      at workLoop (node_modules/react-test-renderer/lib/ReactFiberScheduler.js:763:26)



Here my package.json:
{
  "name": "DigitalOnboarding",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "build:ios": "node node_modules/react-native/local-cli/cli.js bundle --entry-file='./src/app/index/DigitalOnboardingIndex.js' --bundle-output='./ios/DigitalOnboarding/main.jsbundle' --dev=false --platform='ios' --assets-dest='./ios'",
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.0.0-alpha.6",
    "react-native": "0.44.0",
    "react-native-calendar": "^0.11.0",
    "react-native-svg": "4.5.0",
    "react-native-swiper": "1.5.4",
    "react-navigation": "^1.0.0-beta.11",
    "react-redux": "^3.1.0",
    "redux": "^3.0.4",
    "redux-logger": "^2.8.1",
    "victory-native": "~0.4.0"
  },
  "devDependencies": {
    "babel-jest": "20.0.1",
    "babel-preset-react-native": "1.9.2",
    "jest": "20.0.1",
    "react-test-renderer": "16.0.0-alpha.6"
  },
  "jest": {
    "preset": "react-native",
    "collectCoverage": true,
    "moduleNameMapper": {
      "^React$": "<rootDir>/node_modules/react"
    },
    "transformIgnorePatterns": [
      "node_modules/(?!react-native|native-base|react-navigation|react-native-fabric)"
    ],
    "testRegex": "./__tests__/[^setup].*.js$",
    "setupFiles": [
      "./__tests__/setup.js"
    ]
  },
  "module": {
    "loaders": [
      {
        "": ""
      }
    ]
  },
  "rnpm": {
    "assets": [
      "app/fonts"
    ]
  }
}

**Comment by mateen-hussain** [comment]
@marianaMarshaL What was the solution to fix

**Comment by thejettdurham** [comment]
@mateen-hussain I ran into the same problem, and applying the extra jest config outlined in the docs [here](https://github.com/react-community/react-navigation/blob/master/docs/guides/Redux-Integration.md#mocking-tests) solved the issue.

```json
"jest": {
    "preset": "react-native",
    "transformIgnorePatterns": [
      "node_modules/(?!(jest-)?react-native|react-navigation)"
    ]
  }
```

**Comment by spencercarli** [comment]
@thejettdurham has the correct solution for this issue.

**Comment by SerhiiBilyk** [comment]
I have similar issue, but I don't work with React-Native, anybody knows how to fix it?
import React from 'react';
my package.json:
{
  "name": "skew",
  "version": "1.0.0",
  "description": "just simple RWD page",
  "main": "./src/index.js",
  "scripts": {
    "test": " jest",
    "build": "webpack --env production",
    "start": "nodemon --watch webpack.config.js --exec \"webpack-dev-server --content-base dist/ --env development\"  "
  },
  "jest": {
    "transform": {
      "\\.js$": "babel-jest"
    },
    "collectCoverageFrom": [
      "./src/components/**/test/*.jsx",
      "./src/components/*.test.jsx",
      "!./src/components/**/*.scss",
      "!./src/components/**/*.png",
      "!./src/components/**/*.jpg"
    ],
    "testPathIgnorePatterns": [
      "/node_modules/"
    ],
    "transformIgnorePatterns": [
      "!node_modules/react-runtime"
    ]
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/SerhiiBilyk/skew.git"
  },
  "author": "SerhiiBilyk",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/SerhiiBilyk/skew/issues"
  },
  "homepage": "https://github.com/SerhiiBilyk/skew#readme",
  "devDependencies": {
    "babel-core": "^6.26.0",
    "babel-jest": "^21.2.0",
    "babel-loader": "^7.1.2",
    "babel-plugin-styled-components": "^1.2.0",
    "babel-plugin-transform-export-extensions": "^6.22.0",
    "babel-preset-env": "^1.6.0",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-jest": "^21.2.0",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-2": "^6.24.1",
    "babel-register": "^6.26.0",
    "css-loader": "^0.28.7",
    "enzyme": "^3.1.0",
    "enzyme-adapter-react-16": "^1.0.1",
    "extract-text-webpack-plugin": "^3.0.0",
    "file-loader": "^1.1.4",
    "html-loader": "^0.5.1",
    "html-webpack-plugin": "^2.30.1",
    "jest": "^21.2.1",
    "node-sass": "^4.5.3",
    "nodemon": "^1.12.1",
    "postcss-load-config": "^1.2.0",
    "postcss-loader": "^2.0.6",
    "postcss-plugin": "^1.0.0",
    "react-test-renderer": "^16.0.0",
    "sass-loader": "^6.0.6",
    "sass-resources-loader": "^1.3.1",
    "style-loader": "^0.18.2",
    "styled-components": "^2.2.0",
    "url-loader": "^0.5.9",
    "webpack": "^3.6.0",
    "webpack-dev-server": "^2.9.1",
    "webpack-hot-middleware": "^2.19.1"
  }
}

**Comment by assafb81** [comment]
@thejettdurham && @spencercarli 
I am still encountering the same problem:
```
 FAIL  __tests__\index.ios.js
  ? Test suite failed to run

    ***\node_modules\react-navigation\src\NavigationActions.js:5
    import type { NavigationAction } from './TypeDefinition';
    ^^^^^^
    SyntaxError: Unexpected token import

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/ScriptTransformer.js:289:17)
      at Object.get NavigationActions [as NavigationActions] (node_modules/react-navigation/src/react-navigation.js:19:12)
      at Object.<anonymous> (src/containers/resetAppContainer.js:19:33)
```

I've added the Jest config as it is written in the documentation:
```
"jest": {
   "preset": "react-native",
   "testResultsProcessor": "jest-teamcity-reporter",
   "collectCoverageFrom": [
      "src/**/*.js"
   ],
   "coverageReporters": [
      "html",
      "text"
   ],
   "transformIgnorePatterns": [
     "node_modules/(?!(jest-)?react-native|react-navigation)"
   ],
   "setupFiles": [
      "<rootDir>/test/globalFetch.js",
      "<rootDir>/__mock__/react-native-i18n.js"
   ]
}
```

I am using:
```
"react": "16.0.0-alpha.12",
"react-native": "0.45.1",
"react-navigation": "^1.0.0-beta.11",
"jest": "20.0.4",
```

**Comment by ColCh** [comment]
@thejettdurham Thank you! Lifesaver

**Comment by Albert-Gao** [comment]
```json
"transformIgnorePatterns": [
     "node_modules/(?!(jest-)?react-native|react-navigation)"
   ],
```

We need to add this to doc. Otherwise very time wasting.

**Comment by rahamin1** [comment]
I have a similar problem, building a react-native application on iOS, and all the above suggestions didn't work for me.

Here is my package.json. Any idea what is wrong?

```
{
  "name": "newapp",
  "version": "0.0.2",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest --verbose --coverage",
    "test:update": "jest --verbose --coverage --updateSnapshot",
    "test:watch": "jest --verbose --watch",
    "coverage": "jest --verbose --coverage && xdg-open ./coverage/lcov-report/index.html",
    "lint": "npx eslint --fix ./src/*"
  },
  "dependencies": {
    "adm-zip": "^0.4.13",
    "apollo-boost": "0.1.17",
    "axios": "^0.18.0",
    "babel": "^6.23.0",
    "buffer": "5.1.0",
    "cross-fetch": "^3.0.0",
    "enzyme": "^3.3.0",
    "fastfall": "^1.5.1",
    "got": "^9.5.1",
    "graphql": "0.13.2",
    "graphql-tag": "2.10.0",
    "jasmine-react-helpers": "^0.2.2",
    "link": "^0.1.5",
    "lodash": "4.17.5",
    "moment": "2.21.0",
    "plist": "^3.0.1",
    "query-string": "^6.1.0",
    "react": "16.4.0",
    "react-addons-test-utils": "^15.6.2",
    "react-apollo": "2.2.4",
    "react-dom": "^16.7.0",
    "react-native": "^0.57.0",
    "react-native-elements": "0.19.0",
    "react-native-fabric": "^0.5.2",
    "react-native-fbsdk": "^0.6.3",
    "react-native-htmlview": "^0.12.1",
    "react-native-link-preview": "^1.3.5",
    "react-native-login": "^0.0.1-alpha.2",
    "react-native-login-keycloak": "^1.0.2",
    "react-native-onesignal": "3.2.6",
    "react-native-push-notification": "https://github.com/Dhanraj-bidchat/react-native-push-notification.git",
    "react-native-sleek-loading-indicator": "^0.1.3",
    "react-native-spinkit": "^1.1.1",
    "react-native-svg": "6.2.2",
    "react-native-swipe-cards": "^0.1.1",
    "react-native-swiper": "1.5.13",
    "react-native-vector-icons": "4.5.0",
    "react-navigation": "1.5.6",
    "react-redux": "5.0.7",
    "redux": "^3.7.2",
    "redux-logger": "^3.0.6",
    "redux-persist": "5.9.1",
    "redux-thunk": "^2.2.0",
    "victory-native": "^30.0.0",
    "whatwg-fetch": "2.0.4",
    "xcode": "^1.1.0"
  },
  "devDependencies": {
    "@babel/plugin-proposal-optional-chaining": "^7.2.0",
    "babel-eslint": "^8.2.3",
    "babel-jest": "^22.4.4",
    "babel-plugin-dynamic-import-node": "^1.2.0",
    "babel-plugin-syntax-dynamic-import": "^6.18.0",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-plugin-transform-es2015-modules-commonjs": "^6.26.2",
    "babel-preset-react-native": "5.0.2",
    "babel-preset-env": "^1.7.0",
    "enzyme-adapter-react-16": "^1.1.1",
    "enzyme-to-json": "^3.3.4",
    "eslint": "^4.19.1",
    "eslint-config-standard": "^11.0.0",
    "eslint-plugin-import": "^2.12.0",
    "eslint-plugin-jest": "^21.17.0",
    "eslint-plugin-node": "^6.0.1",
    "eslint-plugin-only-warn": "^1.0.1",
    "eslint-plugin-promise": "^3.8.0",
    "eslint-plugin-react": "^7.9.1",
    "eslint-plugin-standard": "^3.1.0",
    "jest": "^23.5.0",
    "jest-resolve": "^23.0.0",
    "jest-serializer-enzyme": "^1.0.0",
    "react-native-mock-render": "^0.0.26",
    "react-test-renderer": "^16.3.2",
    "redux-mock-store": "^1.5.1",
    "sinon": "^5.0.10"
  },
  "jest": {
    "preset": "react-native",
    "setupFiles": [
      "./jest-setup.js"
    ],
    "snapshotSerializers": [
      "enzyme-to-json/serializer"
    ],
    "modulePaths": [
      "<rootDir>/src",
      "<rootDir>/node_modules"
    ],
    "transform": {
      "^.+\\.js$": "<rootDir>/node_modules/react-native/jest/preprocessor.js",
      "^.+\\.jsx?$": "babel-jest"
    },
    "transformIgnorePatterns": [
      "node_modules/(?!(react-native-safe-area-view|react-navigation|react-native-htmlview|react-native-fabric|react-native-login|react-native-elements|react-native-vector-icons|react-native-spinkit|victory-*|react-native-svg|react-native|redux-persist|react-native-swipe-cards|react-native-swiper)/)"
    ],
    "moduleNameMapper": {
      "\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$": "<rootDir>/assetsTransformer.js",
      "\\.(css|less)$": "<rootDir>/assetsTransformer.js"
    }
  }
}

```
