### ISSUE TITLE
Help building this navigation structure.

### ISSUE THREAD

**Issue by lucadegasperi** [react-community/react-navigation#1794]
Hello Everyone, I've just started using react-navigation to build an app. The navigation structure I have in mind is as follows:

```
+ Main -> this page has a drawer
|	+ Resource 1 List
|	|	+ Resource 1 Detail -> show this on the stack
|	|	+ New Resource 1 Form -> show this in a modal
|	|
|	+ Resource 2 List
|		+ Resource 2 Detail -> show this on the stack
|		+ New Resource 2 Form -> show this in a modal
|		
+ Authentication -> show this in a modal
|	+ Login Form -> this is a tab
|	+ Register Form -> this is a tab
```

How would you guys build this? How would the nested navigations look like?

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
