### ISSUE TITLE
Configuring a modal

### ISSUE THREAD

**Issue by tarang9211** [react-community/react-navigation#1795]
I'm not quite sure I understand how to configure a modal. In my current app, I have it working but not sure how I managed to do that.

These are my routes:
```javascript
const routes = {

  Login: {
    screen: Login,
    navigationOptions: {
      header: null
    }
  },

  Main: {
    screen: Blurts,
    navigationOptions: {
      header: null,
      headerLeft: null,
      gesturesEnabled: false,
    }
  },
}

export default routes
```

In another file, I imported the `routes` object (see above) and passed it as the first argument in the `StackNavigator`

```javascript
const CameraStack = StackNavigator({
  Camera: {
    screen: CameraView
  }
})

const Navigator = StackNavigator(routes)

const Root = StackNavigator({
  Navigator: {
    screen: Navigator
  },
  Camera: {
    screen: CameraStack
  }
}, {
  mode: 'modal',
  headerMode: 'none'
})
```

This somehow works. Does this mean a `Modal` configuration object should be the last object in the `StackNavigator`? Any help would be appreciated.

Could I somehow embed the Camera route in the `routes` object and get this to work?

**Comment by tarang9211** [comment]
Guys, is this repo still actively solving issues?

**Comment by spencercarli** [comment]
I will typically have a stack navigator set up as a modal as my root navigator, like you have here. That allows me to open a modal over all other screens. 

You wouldn't be able to put the Camera route inside of `routes` because it would just be treated as a normal screen (like Login or Main). Hope that helps clarify things a bit

**Comment by imod** [comment]
having a modal navigator at root will cause exactly the issue as described here: https://medium.com/4thought-studios/better-modals-in-react-navigation-56c649e0249 is there any way around this?
