### ISSUE TITLE
[Android only] Cannot use with react-native-community/react-native-tab-view

### ISSUE THREAD

**Issue by lsps9150414** [react-community/react-navigation#1796]
Not sure if this is `react-navigation`'s problem or [`react-native-community/react-native-tab-view`](https://github.com/react-native-community/react-native-tab-view)'s problem.

### Steps to reproduce
The problem only exist on Android.
Copy and paste the [example code](https://github.com/react-native-community/react-native-tab-view#example) of `react-native-community/react-native-tab-view` and using it inside a scene of `react-navigation`'s `TabNavigator`.

### Expected Behavior
Only using `react-native-community/react-native-tab-view` on **Android**:
![screenshot_20170607-225933](https://user-images.githubusercontent.com/5022617/26886105-26201976-4bd7-11e7-836d-e2ac696c8401.png)

Using `react-native-community/react-native-tab-view` with `react-navigation` on **iOS**:
![ios](https://user-images.githubusercontent.com/5022617/26886114-2c5c1fd8-4bd7-11e7-8336-f603894c49e6.PNG)

### Current Behavior
Using `react-native-community/react-native-tab-view` with `react-navigation` on **Android**.

Bugs:
1. The scene body of `react-native-community/react-native-tab-view` is not visible.
2. Scene does not "snap" when swiped, instead it's stuck at where it is swiped.

![screenshot_20170607-230006](https://user-images.githubusercontent.com/5022617/26886130-334ab624-4bd7-11e7-95de-4b3712b9f884.png)

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  react-navigation@1.0.0-beta.11
| react-native-tab-view |  react-native-tab-view@0.0.66
| react-native     |  react-native@0.44.0 (using CRNA, expo v = 17.0.0)
| node             | v6.2.1
| npm or yarn      | 3.10.9

**Comment by lsps9150414** [comment]
https://github.com/react-native-community/react-native-tab-view/issues/278

**Comment by mathemagics** [comment]
Happens with nested tab navigators as well

**Comment by ethan605** [comment]
I got this problem too, but only for these conditions:

* Android
* TabNavigator is nested in a StackNavigator
* `react-navigation@1.0.0-beta.10` (with `react-native-tab-view@0.0.65`)

When I use `react-navigation@1.0.0-beta.9` (with `react-native-tab-view@0.0.61`) the problem doesn't happen.

**Comment by walterjar** [comment]
When I use react-navigation nested tab navigators with "animationEnabled: true" in both outer and inner TabNavigator , the inner TabNavigator can not been shown.

**Comment by vonovak** [comment]
This issue is pretty old, and the linked issue in react-native-tab-view#278 offers a solution, so I'm closing this.
