### ISSUE TITLE
Testing with AVA

### ISSUE THREAD

**Issue by JPeer264** [react-community/react-navigation#1798]
### Current Behavior
Fails on triggering tests with [ava](https://github.com/avajs/ava)

```js
/project/path/node_modules/react-navigation/src/navigators/StackNavigator.js:3
import React from 'react';
^^^^^^
SyntaxError: Unexpected token import
```

### Expected Behavior

Run tests as usual. In Jest it is suggested to add `transformIgnorePatterns` which is not an given option in `ava`.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  v1.0.0-beta.11
| react-native     |  v0.43.3
| node             | v6.10.3
| npm or yarn      | yarn

**Comment by JPeer264** [comment]
Solved with:

```js
require('babel-register')({
  ignore: /node_modules\/(?!react|react-navigation)/,
});
```

**Comment by PaijoRX** [comment]
Hi @JPeer264 Where is the location to add your code? Thanks

**Comment by JPeer264** [comment]
I put the above solution in an own file and required it in the AVA config. In my case the config was the following:

```json
{
"ava": {
    "require": [
      "./__tests__/setup/babel-register.js"
    ],
    "babel": "inherit"
  },
}
