### ISSUE TITLE
How to change stack navigator title when a nested drawer navigator item is selected?

### ISSUE THREAD

**Issue by connercms** [react-community/react-navigation#1799]
### Current Behavior
Unable to change stack navigator title when selecting an item from a nested drawer navigator. navigation.state.routeName always points to the stack navigator item and adding title to navigationOptions of screen in drawerNavigator does nothing. Setting title of navigationOptions inside component also had no effect. 

Navigator file
```
const DrawerNavigation = DrawerNavigator({
  Home: {
    screen: Home,
    navigationOptions: {
      title: 'Home Page',  <= Does nothing
      drawerLabel: 'Home',
      drawerIcon: () => (
        <MaterialCommunityIcons name={'home'} size={25} />
        )
    },
  },
  Customers: {
    screen: Customers,
    navigationOptions: {
      title: 'Customers', <= Does nothing
      drawerLabel: 'Customers',
      drawerIcon: () => (
        <MaterialCommunityIcons name={'account-switch'} size={25} />
        )
    },
  },
}, {
  drawerPosition: 'right',
})

const Navigation = StackNavigator({
  Home: {
    screen : DrawerNavigation,
    navigationOptions: ({ navigation }) => ({
      title: navigation.state.routeName, <= Always 'Home'
    }),
  },
})
```

Component file
```
class Home extends Component {
...
static navigationOptions = {
   title: 'Home'
}
}

class Customers extends Component {
...
static navigationOptions = {
    title: 'Customers',
}
}
```

**Comment by valehelle** [comment]
Can you try just removing the title at Home Stack navigator?

**Comment by connercms** [comment]
Yes.. that worked. Thanks a lot, I don't know why I hadn't tried this.

**Comment by daniele-zurico** [comment]
Hi @connercms and @valehelle I'm sorry but I got stack on the same thing and it doesn't work in my case...
```
const InnerNavigator = createDrawerNavigator(
  {
    Home: {
      screen: Home,
      navigationOptions: {
        title: 'Home Page',
        drawerLabel: 'Home',
        drawerIcon: ({ tintColor }) => (
          <Icon name="home" size={24} style={{ color: 'black' }} />
        ),
      },
    },
    Categories: {
      screen: Categories,
      navigationOptions: {
        title: 'Customers',
        drawerLabel: 'Customers',
        drawerIcon: ({ tintColor }) => (
          <Icon name="home" size={24} style={{ color: 'black' }} />
        ),
      },
    },
  },
  {
    contentOptions: {
      activeTintColor: themeStyle.SECONDARY_COLOR,
    },
  }
);

export const RootNavigator = createStackNavigator(
  {
    Landing: {
      screen: InnerNavigator,
    },
  },
  {
    navigationOptions: ({ navigation }) => ({
      headerLeft: <MenuButton navigation={navigation} />,
      headerStyle: {
        backgroundColor: Theme.PRIMARY_COLOR,
      },
      headerTitleStyle: {
        color: '#fff',
      },
      headerTintColor: {},
    }),
  }
);
```
I'm doing something wrong?

thanks

**Comment by wzup** [comment]
Absolutely same issue here.

`DrawerNavigator` is unpredictable. Doesn't follow rules of StackNavigators.

And has no proper documentation and examples.

**Comment by wzup** [comment]
@valehelle 

> _Can you try just removing the title at Home Stack navigator?_

No! This is not an option!
When drawer is opened it must have THE SAME header as current screen. But drawer's header disappears.

The issue is that drawer's header overrides screens' headers. This is wrong behavior.

**Comment by brentvatne** [comment]
https://reactnavigation.org/docs/en/navigation-options-resolution.html

**Comment by shamilovtim** [comment]
Still same issue here. Navigation options resolution isn't predictable either. I set the title on the stack itself and it did not bubble up to the parent even though according to the docs link above it was supposed to.

**Comment by harshmewada** [comment]
I had Same Issue. My headerTitle was not changing at all after many tries. So i tried this approach to change title and surprisingly it worked. i just used string as a screen name.
    
    const MyDrawerNavigator = createDrawerNavigator(
  {
    Home: {
      screen: TabScreen,
      navigationOptions: {
        drawerIcon: ({tintColor}) => (
          <Icon name="home" color={tintColor} size={20} />
        ),
      },
    },
    'Rate This App': {
      screen: MyNotificationsScreen,
      navigationOptions: {
        drawerIcon: ({tintColor}) => (
          <Icon name="star" color={tintColor} size={20} />
        ),
      },
    },
  },

**Comment by harshmewada** [comment]
I had Same Issue. My headerTitle was not changing at all after many tries. So i tried this approach to change title and surprisingly it worked. i just used string as a screen name.

```
const MyDrawerNavigator = createDrawerNavigator(
  {
    Home: {
      screen: TabScreen,
      navigationOptions: {
        drawerIcon: ({tintColor}) => (
          <Icon name="home" color={tintColor} size={20} />
        ),
      },
    },
    'Rate This App': {
      screen: MyNotificationsScreen,
      navigationOptions: {
        drawerIcon: ({tintColor}) => (
          <Icon name="star" color={tintColor} size={20} />
        ),
      },
    },
  },
```
