### ISSUE TITLE
Can't hide header on iOS

### ISSUE THREAD

**Issue by th0th** [react-community/react-navigation#180]
I have screen called `Home` that I want to hide header on. I tried the following, it works on android but doesn't on iOS. Am I doing something wrong or is this a bug?

```js
import React from 'react';
import { View } from 'react-native';
// some other imports go here

class Home extends React.Component {
  static navigationOptions = {
    header: {
      visible: false,
    },
  };

  render() {
    return (
      <View>...</View>
    );
  }
}
```

**Comment by starchand** [comment]
Working for me - the NavigationOptions headerMode needs to be set to 'screen'.

**Comment by heron2014** [comment]
@th0th Try as @starchand mentioned, set the headerMode to ```screen``` on your StackNavigator and also set your navigationOptions as following: 

```js
class Home extends React.Component {
  static navigationOptions = {
    header: () => ({
      visible: false
    })
  }

  render() {
    return (
      <View>...</View>
    );
  }
}

```

Hope that helps.

**Comment by th0th** [comment]
Thanks, setting `headerMode` as `'screen'` did the trick.
