### ISSUE TITLE
You may need an appropriate loader error from TouchableItem.js

### ISSUE THREAD

**Issue by annelorraineuy** [react-community/react-navigation#1800]
I am trying to use `create-react-app` and `react-native-web` with `react-navigation` but I can't get past this compile-time error from this package:

```
./~/react-navigation/src/views/TouchableItem.js
Module parse failed: /projects/rooplay-web/node_modules/react-navigation/src/views/TouchableItem.js Unexpected token (19:12)
You may need an appropriate loader to handle this file type.
|   View,
| } from 'react-native';
| import type { Style } from '../TypeDefinition';
| 
| const ANDROID_VERSION_LOLLIPOP = 21;
```

Anyone have any idea on how to resolve this? Perhaps a webpack config or loader I am missing?

### Your Environment
| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.11
| react-native     |  0.43.2
| node             | 6.6.0
| npm or yarn      | 0.22.0

**Comment by agrcrobles** [comment]
If you want to use built in native navigators on your web app you should configure webpack to transpile `react-navigation` and `react-native-tab-view` and add the following alias: `'react-navigation': 'react-navigation/lib/react-navigation.js'`.
But I am not sure if you can do it with `create-react-app` without ejecting.

**Comment by annelorraineuy** [comment]
I tried that and still encountered errors. : ( I'm going to close this issue coz I decided to use [`react-router` ](https://github.com/ReactTraining/react-router) which has better web support anyway.
