### ISSUE TITLE
How do it  I can change the icon of  backbutton   on android?

### ISSUE THREAD

**Issue by roselind** [react-community/react-navigation#1801]
![d63b0a11-ff55-4c61-910a-97150f4c08ed](https://user-images.githubusercontent.com/9067932/26918851-3e817cfa-4c66-11e7-9501-a5e12f4ba1e2.png)

**Comment by EclipticWld** [comment]
@roselind probably this question should be placed on https://stackoverflow.com/

Anyway, here is an example:

```js
class ProfileScreen extends React.Component {
  static navigationOptions = ({ navigation }) => ({
    headerLeft: (
      <Touchable onPress={() => navigation.goBack()} style={styles.leftIcon}>
        <NavigateBackIcon />
      </Touchable>
    )
  });
  ...
```

**Comment by roselind** [comment]
I want to configure the arrow of all the return buttons to change to another picture

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
