### ISSUE TITLE
Disable the internal logger in production

### ISSUE THREAD

**Issue by codeheroics** [react-community/react-navigation#1804]
The current implementation of react-navigation requires, to disable the internal logger, to create a navigator and pass it a custom `onNavigationStateChange` props, like this :
```
const AppNavigator = StackNavigator({ ... })
export default () => <AppNavigator onNavigationStateChange={null} />`
```
This is problematic because : 
* The ability to disable the logger (and in fact, the logger's existence) is buried in the API documentation about [`onNavigationStateChange`](https://reactnavigation.org/docs/navigators/#onNavigationStateChange-prevState-newState-action)
* The logger can cause significant performance drops if there is a lot of data in the navigation props (my screen transition were about 3 seconds long with it, instantaneous without) because [it is a succession of `console.log`s](https://github.com/react-community/react-navigation/blob/master/src/createNavigationContainer.js#L124)
* The custom code required to disable the logger without needing to create a custom `onNavigationStateChange` function isn't easy to understand when reading code (because of the weird `null` explicitly passed as a prop)  and I was in fact only able to find it thanks to the [PR](https://github.com/react-community/react-navigation/pull/1115) which added the ability to disable it in the first place.

Would it be possible to disable the logger in production? I'm guessing this would give a boost to every app using react-navigation without this particular optimization.

(I actually wanted to send a PR with a check on the presence or absence or the `__DEV__` variable, but I have no idea how to do this check for a project that supports both React and React-Native)

**Comment by crazyx13th** [comment]
Would be cool to disable the logger in production AND if I want it :-)
At the moment don't need it and it's hard to see my own logs because of too many informations
thx!

**Comment by alexkuc** [comment]
Current version from the repo (cannot comment on npm) has the following:
https://github.com/react-community/react-navigation/blob/024297b0141ce63626846fac888d15811d4e5ed7/src/createNavigationContainer.js#L117-L121

In other words, logging is disabled now by default. To enable it, use the following code:
```javascript
process.env.REACT_NAV_LOGGING = true
```

**Comment by spencercarli** [comment]
Should be disabled in production no!
