### ISSUE TITLE
How to hide menu on drawer navigation?

### ISSUE THREAD

**Issue by dominicsavb** [react-community/react-navigation#1806]
How to hide menu on drawer navigation?

I have 2 menu: Login and Logout. If not login yet, then Login show, and Logout hide. If already login, Login hide, Logout will show up?

Thank you

**Comment by jainniket** [comment]
- if you are using redux
read the state, if user is loggedIn vs non-loggedIn and use that to show the particular menu in Drawer.

it is a simple function of your loggedIn status. 

https://reactnavigation.org/docs/navigators/drawer#Providing-a-custom-contentComponent

Use this custom component to handle this.
