### ISSUE TITLE
1 Pixle color difference between header and body view

### ISSUE THREAD

**Issue by agersoncgps** [react-community/react-navigation#1807]
I have a header with backgroundColor: "#00227b"

```
  static navigationOptions = ({ navigation }) => ({
    headerStyle: {
      backgroundColor: "#00227b"
    }
  });
```

and then in the render I have a view with   backgroundColor: "#00227b"

```
render() {
    return (
      <View
        style={{
          backgroundColor: "#00227b",
        }}
      >
        <Text>Loading...</Text>
      </View>
    );
  }
```

### Current Behavior
There is a 1 pixle slightly darker blue color in between them.

### Expected Behavior
I would like a seamless single color from header to body.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  "react-navigation": "^1.0.0-beta.10",
| react-native     |  44

![screenshot 2017-06-08 22 33 47](https://user-images.githubusercontent.com/336441/26958784-8cde6b22-4c9a-11e7-851c-c4ff688484a1.png)

![screenshot 2017-06-08 22 34 13](https://user-images.githubusercontent.com/336441/26958796-9b9a8cc2-4c9a-11e7-85cc-3081cb9b1676.png)

**Comment by zachgibson** [comment]
This is a hairline border which mimics the native iOS Navigation Bar—this uses a shadow not border. To get rid of it you can set shadowOpacity to 0 in your headerStyle.

**Comment by dmr07** [comment]
@zachgibson Getting the same issue here and setting shadowOpacity to 0 doesn't seem to have any effect. Any help would be appreciated. 

```
// Wrapper for Tab Above to Show Header
const ScreenExplore = StackNavigator({
  sometab : {
    screen: TabExplore,
    navigationOptions: {
      headerStyle: {
        shadowOpacity: 0,
        borderBottomWidth: 0,
      },
      headerTitle: (
        <View
          style={{ flex: 1, height: 100, flexDirection:'row',
          borderBottomWidth: 0,
          shadowOpacity: 0,
        }}>
          <Image
            source={require('./../../media/icons/png/something.png')}
            style={{width:180, height:38, tintColor: '#fff', resizeMode: 'contain'}}
          />
        </View>
      ),
    }
  }
})
```

**Comment by agersoncgps** [comment]
Actually, while this did fix it for me in the past. I have noticed it has returned, perhaps with an update to react navigation or RN? Is shadowOpacity still the right parameter?

**Comment by zachgibson** [comment]
@dmr07 @agersoncgps [Here’s the doc](http://facebook.github.io/react-native/releases/0.48/docs/shadow-props.html#shadow-props) for shadowProps. Shadow opacity still works for me with react-native@0.48.1 and react-navigation@^1.0.0-beta.11, but try this to be sure:

```js
shadowOffset: {
  width: 0,
  height: 0
}
```

**Comment by agersoncgps** [comment]
Strangely, adding the width: 0, height: 0 on the header fixes the 1 pixel issue, but turns the statusbar black...

![screenshot 2017-09-08 20 16 03](https://user-images.githubusercontent.com/336441/30235110-93deaa9c-94d2-11e7-97d6-a7da6ded4113.png)

**Comment by lorenzsell** [comment]
I am also having this problem again with the upgrade to react-native@0.48.1.  Anyone figured out how to fix this issue?

**Comment by tapz** [comment]
shadowOpacity and elevation do nothing in 1.0.0-beta.15 and RN 0.49.3.

**Comment by zachgibson** [comment]
This project no longer uses shadow for the hairline, it uses border.

This works for me using `react-navigation@^1.0.0-beta.15`:
```js
headerStyle: {
  borderBottomWidth: 0
}
```

**Comment by tapz** [comment]
If only borderBottomWidth:0 is spesified there is a huge shadow rectangle. Has to add the elevation: 0 and shadow things too.

**Comment by zachgibson** [comment]
@tapz iOS is fine with only this style, didn’t check Android—what I presume you’re testing on.

**Comment by tapz** [comment]
@zachgibson Yes, I tested on Android.
