### ISSUE TITLE
react-navigation is not working in android.

### ISSUE THREAD

**Issue by Ashi90** [react-community/react-navigation#1808]
I'm using react-navigation  and it is working fine for ios, but in android got a issue(please find screenshot).
Issue: undefined is not an object(evaluating this.props.navigation.navigate) 
![screen shot 2017-06-09 at 2 36 31 pm](https://user-images.githubusercontent.com/13783733/26968826-11cc9792-4d21-11e7-93e7-df4e59abdc30.png)
My code:

`rowPressed(listerURL) {
    var property = listerURL;
    const { navigate } = this.props.navigation;
    navigate('TempleDetail', { name: property})
    }`

**Comment by minylund** [comment]
You are not taking out the navigation object correctly out of props.

See this:
`render() {
    const { navigation } = this.props;
    return (
        <View>
          <Button onPress={() => navigation.navigate('MainScene')} title="Login" />
          <Button onPress={() => navigation.navigate('Register')} title="Register" />
        </View>

    )
  }`

**Comment by nithin-c** [comment]
For mee too.
"react": "16.0.0-alpha.12",
 "react-native": "0.45.1",
"react-navigation": "^1.0.0-beta.11"

**Comment by matthamil** [comment]
Can you provide more code? When you have this error, you are most likely not passing `navigation` as a prop to this component. Also, what versions of Android and react-navigation are you using?

**Comment by Ashi90** [comment]
resolved, thanks.
