### ISSUE TITLE
Reset stack on deep link

### ISSUE THREAD

**Issue by parronator** [react-community/react-navigation#1812]
### Current Behavior
In a chat app, if you are currently in a conversation scenario (route index 1, path "group/id1") and you open a deep link to "group/id2" the app navigates to index 2.
Going back navigates to index 1.

### Expected Behavior
Go back to initial route.

### Suggestion
Optional path parameter for navigator that resets scenario stack on open deep link

**Comment by kelset** [comment]
Closing in favor of #2913 to reduce redundancy
