### ISSUE TITLE
onItemPress(route) is not working

### ISSUE THREAD

**Issue by Vetalyo** [react-community/react-navigation#1813]
### Current Behavior

Trying to call "onItemPress(route)" for any menu item but nothing happens.
All other options works well except this one.
### Expected Behavior

Waiting for alert when 'Home' menu item is pressed.

My code:
`{
  initialRouteName: 'Home',
  contentOptions: {
	items:['Home'], 
	activeTintColor: 'red',
	activeBackgroundColor: 'black',
	inactiveTintColor: 'blue',
	inactiveBackgroundColor: '#999',
	onItemPress: (route) => {
		alert('clicked');
		console.log(route);
	},
	style: {
		marginTop: 40,
	},
	labelStyle: {
		fontSize: 18
	},
  } 
 }
);`

| software         | version
| ---------------- | -------
| react-navigation |  ^1.0.0-beta.11
| react-native     |  0.44.2
| node             | 6.9.4
| npm    | 3.10.10

**Comment by Agontuk** [comment]
`items`, `onItemPress` can't be configured from `contentOptions`. They are useful when defining a custom contentComponent. I made a pull request #1694 to remove these options from the docs, so the user won't get confused.

**Comment by marxus85** [comment]
your can use contentComponent and override the onItemPress like this
`
contentComponent: (props) => <DrawerItems {...props, onItemPress: someFunc(route)}/>
`

**Comment by kelset** [comment]
Pinging OP @Vetalyo since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open, because if I get no answer in the next 7 days I will close it.

**Comment by kelset** [comment]
Hi there @Vetalyo ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.

**Comment by AnthonyLamot** [comment]
As an addon to @marxus85 helpful suggestion: In case you want to preserve the original functionality that `onItemPress()` offers, but just want to do _extra_ things, then you can simply wrap `onItemPress()` in another function as you pass it down a custom drawer:

```
  contentComponent: props => (
    <CustomDrawer
      {...props} // make sure all the regular stuff gets passed down a self-defined 
      onItemPress={({ route, focused }) => { // here we overwrite the function with a console.log + the original function
        console.log('test');
        props.onItemPress({ route, focused });
      }}
    />
  ),
```

Some examples on how to make a `<CustomerDrawer />` can be found here: https://github.com/react-navigation/react-navigation/issues/1767

**Comment by brentvatne** [comment]
clear answer from @AnthonyLamot, so I'll lock this thread so it's easy to find!
