### ISSUE TITLE
Provide more redux examples

### ISSUE THREAD

**Issue by jqn** [react-community/react-navigation#1814]
### Current Behavior

React Navigation is awesome but it would be great to have more redux examples.
A great example would be StacksInTabs with redux. 

### Expected Behavior

I expected to be able to reconfigure StacksOverTabs to StacksInTabs with redux in a straight forward way but I keep running into errors, for `instance Expect nav state to have routes and index, {"routeName":"Main","key":"Init"}` By providing more examples we can ensure there is a stronger community backing to this project and has more users.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  "^1.0.0-beta.9"
| react-native     |   "^0.44.2"
| node             |  "v6.3.1"
| npm or yarn      | "npm 5.0.1"

**Comment by kelset** [comment]
Closing this since we added a section in the README with multiple articles, tutorials & examples in order to provide sources. Later on we'll migrate that into the docs. (PRs for that surely welcome!)
