### ISSUE TITLE
Reorder stackNavigator indices and navigationActions  

### ISSUE THREAD

**Issue by sclanc** [react-community/react-navigation#1816]
What I believe is the default behavior of the Stack Navigator is creating a UX issue for my app. Here's the use case:

current behavior:
 A user navigates from  screen1 to  screen2 and then to screen1 again. This creates two separate instances of the components that comprise screen1.

A user navigates from screen1 to screen2 and then presses the Android back button. This does not create two instances of screen 1, but rather, re-renders the original instance.    

Problem: 

screen1 makes an api call when the component mounts and I noticed that when a user navigates to screen1 the content of the call is rendered after the 1-2 seconds it takes to get a promise, convert it to json, and set the state of the component, as one would expect. Then if a user navigates to screen2, and then to screen1, there is another 1-2 second delay, indicating that a new component is being added to the stack, and that component is going through the componentDidMount() process. However, if a user were to use the back button instead, there is no delay, indicating that the navigation component is storing that old component and that it's stateful data remains intact even if the user navigates away from it. This unnecessarily slows down the user experience, and could generate dozens of unnecessary instances of commonly used screens.

Solution:

I would like the set up my app so that no more than one instance of a screen exists. if a user navigates from screen1 to screen2 and then to screen1, I simply want to reorder those instances on the stack, instead of creating a new instance of screen1. I'm not sure how I can do that. 

I can achieve a similar effect by keeping track of stateful data in redux (which will require a refactor) and also keeping track of the of the Navigation states in redux. Then when a user wants to go from screen1 to screen2 and then back to screen1, I can use NavigationActions.reset() to simply rearrange the screens instead of adding a new one, but is there another way to do this?

**Comment by spencercarli** [comment]
I think this is a relatively unusual case. If someone is going from screen 1 to screen 2 and then to screen 1, why not just have them go back to screen 1?
