### ISSUE TITLE
Emit action on drawer item press

### ISSUE THREAD

**Issue by dominicsavb** [react-community/react-navigation#1818]
is screen just for Component? 

is it able, when drawer menu is clicked, then just do an action? maybe open external compose email or logout?

Thank you

**Comment by TheTekton** [comment]
If you're trying to use the drawer navigator to display a custom component, use the `contentComponent` property of the DrawerNavigatorConfig object passed to `DrawerNavigator()`. The drawer navigator's `RouteConfigs` object must have at least one screen or nested navigator; such as the app's stack/tab navigator. If you're using redux or need route information, use the contentComponent's props parameter to access the navigator or other params.

Based on https://reactnavigation.org/docs/navigators/drawer#Example: you would setup navigation similar to the following:

```
import { DrawerNavigator } from 'react-navigation';

function getCurrentRouteParams(navigationState) {
  if (!navigationState) {
    return null;
  }
  const route = navigationState.routes[navigationState.index];
  // dive into nested navigators
  if (route.routes) {
    return getCurrentRouteParams(route);
  }
  if (route.params) {
    return route.params;
  } else {
    return null;
  }
}

const CustomDrawerContentComponent = (props) => (
  const nav = props.nav;
  params = getCurrentRouteParams(nav); // Route's navigator params...
  const doSomething = () => {
    console.log("doSomething pressed");
  };
  <View style={style.container}>
    <Button title="Do Something" onPress={doSomething}
  </View>
);

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
});

const navigatorConfig = {
  drawerWidth: 300
  contentComponent: CustomDrawerContentComponent
};

class MyHomeScreenOrNavigator extends React.Component {
  static navigationOptions = {
    drawerLabel: 'Home',
    drawerIcon: ({ tintColor }) => (
      <Image
        source={require('./chats-icon.png')}
        style={[styles.icon, {tintColor: tintColor}]}
      />
    ),
  };

  render() {
    return (
      <View><Text>MyHomeScreen content</Text></View>
    );
  }
}

const styles = StyleSheet.create({
  icon: {
    width: 24,
    height: 24,
  },
});

const MyApp = DrawerNavigator({
  Home: {
    screen: MyHomeScreenOrNavigator,
  },
}, navigatorConfig);
```

**Comment by nbluis** [comment]
👍

**Comment by luisfuertes** [comment]
Any update about this?

**Comment by kelset** [comment]
Pinging OP @dominicsavb since this issue has not been active for a while, and it's related to an old version of the lib (and in the meantime a lot has been added to the Drawer).

Please let me know if you want this to remain open, because if I get no answer in the next 7 days I will close it.

**Comment by kelset** [comment]
Hi there @dominicsavb ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.

**Comment by wfettich** [comment]
I did it by basically tapping into onItemPress of DrawerItems. No need to redesign the whole view. 

```
const CustomDrawerContentComponent = (props) => {
  const nav = props.nav;
    
  return (<View>
    <ScrollView>
      <DrawerItems
        {...props}
        onItemPress = {
          ({ route, focused }) =>       
          {    
            props.onItemPress({ route, focused })
            console.log("item pressed");
          }
          }
      />
      </ScrollView>
    </View>)
};
```

and in your DrawerNavigator add
`contentComponent: CustomDrawerContentComponent,`

as drawer option

**Comment by montao** [comment]
What if I already have a contentComponent and want to add a logout option in my drawer?

**Comment by normdoow** [comment]
@montao You should be able to add the logout button to whatever component is in your contentComponent. So in @TheTekton's example above you would add the login button to the "CustomDrawerContentComponent" Component that he has created.

**Comment by AlphaMikeFoxtrot** [comment]
> I did it by basically tapping into onItemPress of DrawerItems. No need to redesign the whole view.
> 
> ```
> const CustomDrawerContentComponent = (props) => {
>   const nav = props.nav;
>     
>   return (<View>
>     <ScrollView>
>       <DrawerItems
>         {...props}
>         onItemPress = {
>           ( route, focused ) =>       
>           {    
>             props.onItemPress({ route, focused })
>             console.log("item pressed");
>           }
>           }
>       />
>       </ScrollView>
>     </View>)
> };
> ```
> and in your DrawerNavigator add
> `contentComponent: CustomDrawerContentComponent,`
> 
> as drawer option

Can I use `this.props.navigation.navigate(route)` inside Drawer Navigator?

**Comment by vetri-iteron** [comment]
Hi there,

I expecting solution like this, 

**Select 'Logout' in the drawer menu -> automatically trigger a function (Show warning alert "Are you sure to logout" ? "ok" or "cancel" ) -> If user selected "ok" then navigate to the 'Login' page.**

I expecting this kind of solution. Someone please help me.

**Comment by lukemueller** [comment]
@vetri-iteron I solved the same problem by having some conditional logic in the onItemPress function, if the route matches the registered Logout route I trigger the alert, otherwise just call the default onItemPress function:

```javascript
<DrawerItems
  {...props}
  onItemPress={(route) => {
    if (route.route.routeName !== routes.Logout) {
      props.onItemPress(route);
      return;
    }

  Alert.alert(...)
}}/>
```

And then you can effectively register an empty/dummy component with `react-navigation` by providing a string:

```javascript
createDrawerNavigator({
  [ routes.Home ]: HomeScreen,
  [ routes.Company ]: CompanyScreen,
  [ routes.Logout ]: 'LogoutScreen'
}, { ...}
);
```

Hope this helps, happy coding!

**Comment by leandrosouzaa** [comment]
> > I did it by basically tapping into onItemPress of DrawerItems. No need to redesign the whole view.
> > ```
> > const CustomDrawerContentComponent = (props) => {
> >   const nav = props.nav;
> >     
> >   return (<View>
> >     <ScrollView>
> >       <DrawerItems
> >         {...props}
> >         onItemPress = {
> >           ( route, focused ) =>       
> >           {    
> >             props.onItemPress({ route, focused })
> >             console.log("item pressed");
> >           }
> >           }
> >       />
> >       </ScrollView>
> >     </View>)
> > };
> > ```
> > 
> > 
> > and in your DrawerNavigator add
> > `contentComponent: CustomDrawerContentComponent,`
> > as drawer option
> 
> Can I use `this.props.navigation.navigate(route)` inside Drawer Navigator?
> 
> 'cause, I tried using it inside the `createDrawerNavigator()` method. It gave me `this.props.navigation.navigate()... is not defined` error.

Hello @AlphaMikeFoxtrot , 
Did you manage to resolve this error?

**Comment by devsphinx214** [comment]
> > > I did it by basically tapping into onItemPress of DrawerItems. No need to redesign the whole view.
> > > ```
> > > const CustomDrawerContentComponent = (props) => {
> > >   const nav = props.nav;
> > >     
> > >   return (<View>
> > >     <ScrollView>
> > >       <DrawerItems
> > >         {...props}
> > >         onItemPress = {
> > >           ( route, focused ) =>       
> > >           {    
> > >             props.onItemPress({ route, focused })
> > >             console.log("item pressed");
> > >           }
> > >           }
> > >       />
> > >       </ScrollView>
> > >     </View>)
> > > };
> > > ```
> > > 
> > > 
> > > and in your DrawerNavigator add
> > > `contentComponent: CustomDrawerContentComponent,`
> > > as drawer option
> > 
> > 
> > Can I use `this.props.navigation.navigate(route)` inside Drawer Navigator?
> > 'cause, I tried using it inside the `createDrawerNavigator()` method. It gave me `this.props.navigation.navigate()... is not defined` error.
> 
> Hello @AlphaMikeFoxtrot ,
> Did you manage to resolve this error?

just put do this on your argument ({route, focused})

**Comment by coayscue** [comment]
Here's the solution: a combination of this event and screenListeners 
https://reactnavigation.org/docs/drawer-navigator/#events
+
https://reactnavigation.org/docs/navigation-events/#screenlisteners-prop-on-the-navigator
=
```
<DrawerNavigator.Navigator
          screenListeners={{
            drawerItemPress: (e) => {
              console.log(e.target);
              if (e.target?.includes(Screens.AuthStack)) {
              }
            },
          }}
>
```
