### ISSUE TITLE
Expand Redux tutorial

### ISSUE THREAD

**Issue by starchand** [react-community/react-navigation#182]
I've got standard Nested navigator working with tabs and stack navigators. I'm struggling to get my head around the Redux tutorial (albeit, I'm relatively new to Redux). I have redux working following https://github.com/jlebensold/peckish and trying to intergrate the 2. 

The react-navigation redux tutorial has no information about 
 - mapStateToProps
- actions
- tabs

**Comment by starchand** [comment]
Warning: Failed prop type: The prop `navigation.state` is marked as required in `CardStack`, but its value is `undefined`.

Can anyone help one this?

**Comment by parkerdan** [comment]
I wrote a detailed example of taking complete control...

https://medium.com/@parkerdan/react-navigation-with-complete-redux-state-management-tab-bar-and-multiple-navigators-ed30a69d9a4d#.fl0959br8

**Comment by wilomgfx** [comment]
@parkerdan you da man!

**Comment by ericvicenti** [comment]
@parkerdan, You can certainly do things that way, but it is usually easier to delegate the navigation reducer logic to `MyNavigator.router.getStateForAction`. This reducer handles all the standard navigation actions, and of course you can add additional logic that is specific to your application.

**Comment by wilomgfx** [comment]
@ericvicenti thats what i though. Kinda makes it complicated the way @parkerdan  did it. Certainly works, but it seemed like a lot of work for this library already does.

**Comment by parkerdan** [comment]
@ericvicenti...thanks.  `getStateForAction ` sure does make it super easy to `navigate` and `goBack()`.  Still need some logic in place for `Android Back Button` things, correct?

**Comment by ericvicenti** [comment]
The back button behavior is just a back action, but you do need to fire the action on the [native back button event](http://facebook.github.io/react-native/docs/backandroid.html). If your top-level navigator doesn't have a navigation prop, this will happen automatically, but when your navigation is integrated with redux, you need to listen to the back event manually.

**Comment by hwaterke** [comment]
I wrote an minimalistic example of using Redux together with nested navigators.

You can open it in Exponent:
https://getexponent.com/@nauktis/nested-navigation-redux
(every component shows you the complete Redux state, so you can figure out what happens)

The source can be found there:
https://github.com/hwaterke/react-navigation-nested-redux/blob/master/main.js

**Comment by MyTotoro** [comment]
Can anyone help me with my code? I've read @parkerdan tutorial but I can't get it working with Redux

My RootContainer of the app:
`
...
<PrimaryNavigation />
...

export default connect(null, mapDispatchToProps)(RootContainer)
`

PrimaryNavigation:
`
const mapStateToProps = (state) => {
 return {
  navigationState: state.primaryNav
  }
}

class PrimaryNavigation extends React.Component {
  render() {
    return (
      <PrimaryNav
        navigation={
          addNavigationHelpers({
            dispatch: this.props.dispatch,
            state: this.props.navigationState
          })
        }
      />
    )
  }
}

export default connect(mapStateToProps)(PrimaryNavigation)
`

PrimaryNav:
`

const routeConfiguration = {
  LaunchScreen: {
    screen: LaunchScreen
  },
  LoginScreen: {
    screen: LoginScreen
  },
  MainContainer: {
    screen: MainContainer
  }
}

// Manifest of possible screens
const PrimaryNav = StackNavigator(
  routeConfiguration,
  {
    // Default config for all screens
    headerMode: 'none'
  })

export default PrimaryNav

export const reducer = (state, action) => {
  const newState = PrimaryNav.router.getStateForAction(action,state)
  return newState || state;
}
`

My create store:
`
  const rootReducer = combineReducers({
    ...
    primaryNav: require('../Navigation/AppNavigation').reducer
  })

  return configureStore(rootReducer, rootSaga)
`

When I start the app - I get an error of `Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. Check the render method of 'PrimaryNavigation'`

**Comment by RubenSandwich** [comment]
@parkerdan

Thank you for your excellent example. However, I would prefer all data to live in my reducers and for the reducer data to be the source of truth. To achieve this I store React Navigation routers state in my Reducers and pass that routers state to the Navigators. This allows me to keep the reducer as the source of truth in my app.

Navigation Reducer:
https://github.com/CMP-Studio/BeaconDeploymentTool/blob/master/src/reducers/navigation.js

Initing a Navigator:
https://github.com/CMP-Studio/BeaconDeploymentTool/blob/master/src/components/rootScreen.js

If this is helpful to anyone else. I suggest upping this issue I created to allow navigators routers to be passed in which would allow my solution to feel less 'hacky':
#797
