### ISSUE TITLE
Modal swipe back goes to previous stack navigator. Unexpected behaviour

### ISSUE THREAD

**Issue by tarang9211** [react-community/react-navigation#1820]
Hi Guys. I am currently using react-navigation in a project and running into a view issues. 
I have two main screens, `Login` and `Main`.  After logging in a user is taken to the `Main` screen. The main screen has a camera button which opens a Camera component in a `modal` view.

**Issue**
Swiping from left to right on the camera modal goes back to the `Login` screen. I need it to go back to the `Main` screen.

Here's how I have it setup:
```javascript
export const LoginStack = StackNavigator({
  Login: {
    screen: Login,
    navigationOptions: {
      header: null
    }
  }
})

export const MainStack = StackNavigator({
  Main: {
    screen: Blurts,
    navigationOptions: {
      header: null,
      headerLeft: null,
      gesturesEnabled: false,
    }
  },

  Camera: {
    screen: CameraView,
    navigationOptions: {
      header: null,
      headerLeft: null,
    }
  }
}, {
  mode: 'modal',
  headerMode: 'none'
})
```

```javascript
const Root = StackNavigator({
  Login: {
    screen: LoginStack
  },
  Main: {
    screen: MainStack
  }
})


export default Root
```

Is this a bug in the module? If my configuration is wrong, could you help fix it?

**Update** 
See GIF
![nav-issue](https://user-images.githubusercontent.com/5876249/27001924-a32ca5a2-4df2-11e7-8de2-007db8dbcdac.gif)

**Comment by tarang9211** [comment]
Guys, is this repo still actively solving issues?

**Comment by matthamil** [comment]
Have you tried enabling `gesturesEnabled: false` for your `Root`navigator?
