### ISSUE TITLE
Redux state change won't sync across different screens in a TabNavigator

### ISSUE THREAD

**Issue by DavideValdo** [react-community/react-navigation#1825]
Reopening #1810 because the problem is deeper...

I have a TabNavigator like this:
```
TabNavigator({
        Products: {
          screen: StackNavigator({
              Categories: {
                screen: CategoriesShowcase
              },
              CategoryDetail: {
                screen: Gallery
              }
            })
        },
        Vendors: {
          screen: StackNavigator({
              VendorsList: {
                screen: VendorsList
              },
              VendorDetail: {
                screen: VendorDetail
              },
              VendorGallery: {
                screen: Gallery
              },
              VendorFullGallery: {
                screen: FullScreenGallery,
              }
            })
        })
```
**This is wrapped inside redux's Provider in a parent component, which is the app's entry point**

I can't sync state.Bookmarks across two tabs in a TabNavigator.
render() is called with new props upon actions but changes are not shown 

Gallery's render() console output when clicking bookmark in the vid:
gallery.js:196 Rerendering from vendor m_160dfjsofjsok
gallery.js:179 Bookmark found-KmHiFRPIcV8AfLtAJa5
gallery.js:196 Rerendering from category knitwear
gallery.js:179 Bookmark found-KmHiFRPIcV8AfLtAJa5

Same things happens going from VendorFullGallery back to VendorGallery

@Jacse suggested to pass a refresh callback from VendorGallery to VendorFullGallery to address this, this is clearly not possible in my case as I would need every Gallery component to have a list of every other Gallery instance and trigger each refresh callback upon every possible NavigationAction from one to another. Also I don't see how this callback would work, since render() is actually triggered.

As I understand, in order to cache tab state (scrolling and so on) React Navigation will create HOCs on top of my Redux components, but I was expecting Redux-related props not to be cached.

Am I structuring this the wrong way?

**Comment by efkan** [comment]
+1 

I use DrawerNavigator and I emit `redux` store like the code below. `<Button>` is my custom component. And the button cannot be rendered on screens _except initial screen_. But when I gesturing the DrawerMenu the router configuration refreshes and button becomes appear.
(Actually I've been migrating from React-Native-Router-Flux and when using RNRF I never encounter this issue)

```
return {
	initialRouteName: 'screen2',
	headerMode: 'screen',
	headerStyle: { backgroundColor: 'blue' },
	headerTintColor: 'yellow',
	headerLeft: (
		<Button
			style={{flex: 1}}
			color={'yellow'}
			icon={<MaterialIcons name="menu" size={24} />}
			onPress={() => navigation.navigate('DrawerOpen')}
		/>
	),
	headerTitle: 'screen2',
}
```

**Comment by DavideValdo** [comment]
@efkan, I don't know if this can help you, but I solved my issue binding my PictureThumb directly to Redux.

Before I was doing something like this in my **gallery** component

```
foreach product
     gallery.push(<PictureThumb bookmarkID={this.checkBookmark()} />)
```

Now I'm checking the bookmark existence directly inside PictureThumb, which is bound to state.Bookmarks

```
  hasBookmark () {
      for (id in this.props.allBookmarks)
          if (this.props.allBookmarks[id].res_id == this.props.product.id)
            return id;
        
      return null;
  }
```
This way I get the correct expected behaviour.

**Comment by efkan** [comment]
@DavideValdo, thank you very much for your share.

It is very good that you had overcome the issue.

I guess this solution cannot be applied to my code. My issue about the all components(button, checkbox etc) in my screens and headers. Until `redux` store is changed.

Thanks anyway...

**Comment by kelset** [comment]
Pinging OP @DavideValdo  since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open, because if I get no answer in the next 7 days I will close it.

**Comment by kelset** [comment]
Hi there @DavideValdo ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.
