### ISSUE TITLE
How can i remove the backlistener?

### ISSUE THREAD

**Issue by lazzy930529** [react-community/react-navigation#1828]
I used StackNavigation and compenentWillUnmount().
But when i navigated to an other screen,the function compenentWillUnmount() did not excute.
So how can i remove the backListener?

**Comment by spencercarli** [comment]
You'll need to handle state management yourself. It's not difficult and you don't need to be using Redux in any other part of your app. Here are [the instructions](https://reactnavigation.org/docs/guides/redux)
