### ISSUE TITLE
OMG!, Please Help Me, My iPhone Simulator Display "Route 'Home' should declare a screen. For example: 

### ISSUE THREAD

**Issue by YinHanMsn** [react-community/react-navigation#1830]
My English is no good.

OMG!  Please Help Me. Thank 
I use react-navigation alter.
my iPhone Simulator Screen Display 

Route 'Home' should declare a screen.
For Example:

import MyScreen from './MyScreen';
...
Home:{
    screen:MyScreen,
}

<unknown>
validateRouteConfigMap.js:22:6
....

--------------

my React-native code

App.js

import React,{Component} from 'react';
import {View, StyleSheet, Text} from 'react-native';
import {HomeScreen, ProfileScreen} from './HomeScreen';
import { StackNavigator } from 'react-navigation';

const App = StackNavigator({
    Home: { screen: HomeScreen },
    Profile: { screen: ProfileScreen },
});

MainScreen.js

import React,{Component} from 'react';
import {View, StyleSheet, Text} from 'react-native';
import { StackNavigator } from 'react-navigation';

class MainScreen extends React.Component {
    static navigationOptions = {
        title: 'Welcome',
  };
  render() {
      const { navigate } = this.props.navigation;
      return (
          <Button
              title="Go to Jane's profile"
              onPress={() =>
               navigate('Profile', { name: 'Jane' })
          }
        />
    );
  }
}

class ProfileScreen extends React.Component {
    static navigationOptions = ({navigation}) => ({
        title: navigation.state.params.name,
  });
  render() {
       const { goBack } = this.props.navigation;
       return (
          <Button
             title="Go back"
             onPress={() => goBack()}
          />
      );
  }
}

let styles = StyleSheet.create({
	container: {
		flex: 1
	},
	navigator: {
		flex: 1
	}
});

Thank, Good luck to you

**Comment by matthamil** [comment]
Is this the entire code sample? I don't see a `MyScreen` component being exported anywhere.

**Comment by YinHanMsn** [comment]
Hi big boy, I fix this question. 
----------
app.js


class ChatScreen extends React.Component {
  static navigationOptions = {
    title: 'Chat with Lucy',
  };
  render() {
    return (
      <View>
        <Text>Chat with Lucy</Text>
      </View>
    );
  }
}


class HomeScreen extends React.Component {
  static navigationOptions = {
    title: 'Welcome',
  };
  render() {
    const { navigate } = this.props.navigation;
    return (
      <View>
        <Text>Hello, Chat App!</Text>
        <Button
          onPress={() => navigate('Chat')}
          title="Chat with Lucy"
        />
      </View>
    );
  }
}


const MyHomeScreen = ({ navigation }) => (
  <ChatScreen  navigation={navigation} />
);





const MainScreen = ({ navigation }) => (
  <HomeScreen navigation={navigation}/>
);

MainScreen.navigationOptions = {
  title: 'Welcome',
};

const App = StackNavigator(
  {
    Index: {screen: MainScreen},
    Chat: {screen: MyHomeScreen},

  },{initialRouteName: 'Index',});

export default () => <App />;

-------------
good, Display Navigation
