### ISSUE TITLE
Sending props from navigator route makes the navigator.navigate disappear . Can not jump from one screen to another.

### ISSUE THREAD

**Issue by Shrek53** [react-community/react-navigation#1832]
// my router

`
export const NewsFetch = StackNavigator({
          Brief              :     { screen   : props => `<NewsColumnFixed` head="bangladesh"/> },
          Detail             :     { screen   : props => <NewsDetails head="bangladesh" /> },          
});
`
// Inside NewsColumnFixed

` 
   <Button 
                              onPress={ () => this.props.navigation.navigate('Detail')}  //works no more
                               title="Go to Details page"
    />
`
// when I changed my router as below 

`
export const NewsFetch = StackNavigator({
          Brief              :     { screen   : NewsColumnFixed  }, //It works
          Detail             :     { screen   : props => <NewsDetails head="bangladesh" /> },          
});
`

//Now I can not send props to  NewsColumnFixed

**Comment by spencercarli** [comment]
You need to pass on props when using the function. A working version of your first code would be:

```javascript
export const NewsFetch = StackNavigator({ 
  Brief : { screen : props =><NewsColumnFixedhead="bangladesh" {...props} /> }, 
  Detail : { screen : props => <NewsDetails head="bangladesh" {...props} /> }, 
});
```

**Comment by Shrek53** [comment]
Passing the props is not a problem here.
I can pass props and receive on the the other end.
But when I pass props the screen loses the default props from the parent navigator and so it can not navigate from one screen to another screen . That is the main point of this issue.

Though I worked the problem around and screenprops served my need well but the question remains "Why sending props like above overrides the default props sent by the parent navigator".

**Comment by spencercarli** [comment]
Right, that's where the `{...props}` comes in. When we simply pass the component the stack navigator will go ahead and render the component and pass it the default props but since you're rendering the component you need to pass the default props, which is what `{...props` does.

screenProps is certainly an option but you've then got to access navigation at `this.props.screenProps.navigation` rather than `this.props.navigation`. With the method I suggest you can access it normally.

Here's a [working demo](https://snack.expo.io/HkzW4clOZ)

**Comment by Shrek53** [comment]
Now I get it.
Thanks man for explaining it to me.

**Comment by Quadriphobs1** [comment]
I implemented it the way you did @spencercarli 
```
  Settings: {
      screen: ({
        props,
        navigation,
      }: {
        props: NavigationScreenProp<{}>,
        navigation: NavigationScreenProp<{}>,
      }) => (
        <Example
          screenProps={{ rootNavigation: navigation }}
          {...props}
        />
      ),
    },
```
```
this.props.navigation.dispatch(NavigationActions.navigate({
                  routeName: BASE_ROUTE,
                  action: NavigationActions.navigate({
                    routeName: SUB_ROUTE,
                  }),
                }))
```

It only navigate to the base route and not the subroute
