### ISSUE TITLE
DrawerNavigator. Ability to set styles for TouchableItem View

### ISSUE THREAD

**Issue by mstmustisnt** [react-community/react-navigation#1833]
### Current Behavior
Only backgroundColor can be set

### Expected Behavior
any style property can be set

[Code](https://github.com/react-community/react-navigation/blob/master/src/views/Drawer/DrawerNavigatorItems.js#L67)

Please provide an ability to pass drawer item style in props. Thank you!

**Comment by kelset** [comment]
Closing since this has been now added - check [here](https://reactnavigation.org/docs/navigators/drawer) for details
