### ISSUE TITLE
Issue: header not hidden when calling navigation.goBack() 

### ISSUE THREAD

**Issue by joesonw** [react-community/react-navigation#1834]
### Current Behavior
So I have set route's `navigationOptions.header = () => null`, it displays correctly. However, when I call `this.props.navigation.goBack()`, the header shows for like `0.3s`, then it's gone.

### Expected Behavior
It should be consistent, it should not reappear during animations.

### Your Environment
`OS: macOS Sierra`
`iOS simulator version: 10.3`

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.9
| react-native     |  0.42.3
| node             |  6.9.2
| npm or yarn      | npm

**Comment by spencercarli** [comment]
A reproduction of this issue would be very helpful. Thanks!

**Comment by kelset** [comment]
Closing this in favor of #2941
