### ISSUE TITLE
Add iOS 11 Style Large Navigation Bars

### ISSUE THREAD

**Issue by bhagyas** [react-community/react-navigation#1835]
### Current Behavior
Does not provide large navigation bars as presented with ios11.

### Expected Behavior
ios11 style large navigation bars (including search) bars should be available.

**Comment by phuongwd** [comment]
it very cool https://www.youtube.com/watch?v=oW7N6-_92Lg 

@React Navigation, did you have plan to add iOS 11 style large and animation navigation header text?

**Comment by gurmukhp** [comment]
This would be awesome to do! Can we tap into the native iOS headers instead of recreating them?

**Comment by nickyhajal** [comment]
Just wanted to throw in some support for this!

**Comment by keithyeohh** [comment]
looking forward!

**Comment by kinergy** [comment]
is this being considered? +1

**Comment by kelset** [comment]
I think so, @spencercarli was on iOS11 implementation.

**Comment by spencercarli** [comment]
Though this issue was created earlier, I already posted a reply in #2749 and would like to point you there (thus closing this issue).
