### ISSUE TITLE
Installation Error !

### ISSUE THREAD

**Issue by wisnuprayoga** [react-community/react-navigation#1836]
I am just followed this installation step 
- react-native init SimpleApp
- cd SimpleApp
- npm install --save react-navigation

and when execute **react-native run-android** its said "_Command `run-android` unrecognized. Make sure that you have run `npm install` and that you are inside a react-native project._"

i did npm install and nothing changes, please help thankyou

**Comment by zphhhhh** [comment]
Are you using the latest npm ? 
So if your npm's version >= 5, you must touch firstly:
```
npm cache clean --force
```
and before your installation, you must touch :
```
npm i
```
btw npm5 doesn't need `--save` at all, it is default.
then you can:
```
npm i react-navigation
```
It maybe help you.

**Comment by zphhhhh** [comment]
If it work, you may close the issue.  : )
