### ISSUE TITLE
Drawer doesn't open when screen as a function

### ISSUE THREAD

**Issue by Levi-ackerman** [react-community/react-navigation#1837]
### Current Behavior

Currently, I have a screen with a Drawer. This my config : 

`const drawerNavigationOptions = ({screenProps, navigation }) => ({
  headerStyle: {
    backgroundColor: AppColors.colorPrimary,
    shadowColor: AppColors.colorPrimary,
  },
  headerTitleStyle: {
    color: 'white',
  },
  headerLeft: (<DrawerButton navigation={navigation} />)
});`

`const DiscoverNav = StackNavigator({
  DiscoverNav: {
    screen: DiscoverScreen,
    navigationOptions: {
      title: 'Discover',
    }
  },
}, {
  navigationOptions: drawerNavigationOptions
});`

`const MoviesNav = StackNavigator({
  MovieNav: {
    screen: MoviesScreen,
    navigationOptions: {
      title: 'Movies',
    }
  },
}, {
  navigationOptions: drawerNavigationOptions
});`

`const MainScreenNavigator = 
DrawerNavigator({
  Discover: {
    screen: DiscoverNav,
  },
  Movies: {
    screen: MoviesNav,
  }
});`

--> Everything work ok. When I press DrawerButton, drawer screen will show.
Now I want to add some props to screenProps, so I modify my MainScreenNavigator to : 

`const MainScreenNavigator = DrawerNavigator({
  Discover: {
    screen: () => <DiscoverNav screenProps={{x : true}} />,
  },
  Movies: {
    screen: MoviesNav,
  }
});`

Now, the Drawer Button not working anymore. I click to it and nothing happen. No log error.

Could someone help me please ??!!!!

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  ^1.0.0-beta.11
| react-native     |  0.44.2
| node             | v7.6.0
| npm or yarn      | v0.21.3

**Comment by spencercarli** [comment]
You need to pass props on to DiscoverNav

```javascript
const MainScreenNavigator = DrawerNavigator({ 
  Discover: { screen: (props) => <DiscoverNav {...props} screenProps={{x : true}} />, }, 
  Movies: { screen: MoviesNav, } 
});
```
