### ISSUE TITLE
Access to navigation state on back

### ISSUE THREAD

**Issue by mic7010** [react-community/react-navigation#1838]
I have set up a handler to listen for back press on Android. I am not using redux. I want to make a decision where to navigate next based on the navigation state. How to I access the current navigation index and route name?

**Comment by matthamil** [comment]
You could override the navigator's `onNavigationStateChange` method: https://github.com/react-community/react-navigation/blob/77b04f342d4791ec6470685905133f440e3968c1/src/createNavigationContainer.js#L115-L144

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
