### ISSUE TITLE
[FEATURE REQUEST] Navigate without animation

### ISSUE THREAD

**Issue by mrgoonie** [react-community/react-navigation#1839]
It would be great if it's possible to ignore the transition as below:

`this.props.navigation.navigate('SomeScreen', {animation: false});`

or 

`this.props.navigation.navigate('SomeScreen', {animation: null});`

..and use some custom animations by doing this:

```
...
this.props.navigation.navigate('SomeScreen', {animation: 'ModalSlideFromBottom'});
this.props.navigation.navigate('SomeScreen', {animation: 'SlideFromRight', easing: 'easeOutElastic'});
this.props.navigation.navigate('SomeScreen', {animation: 'SlideFromLeft', animationDuration: 500 });
...
```

Right?

**Comment by matthamil** [comment]
This is on the roadmap for V2: https://github.com/react-community/react-navigation/issues/1263

**Comment by kelset** [comment]
Closing in favor of https://github.com/react-community/react-navigation/issues/175

**Comment by ChandniSharma** [comment]
Did any one get any proper solution for it?
