### ISSUE TITLE
Any Ideas how does it work with Relay?

### ISSUE THREAD

**Issue by lookeme** [react-community/react-navigation#184]
Would be grateful if somebody will share some experience with Relay GraphQl integration.
Thanks in advance.

**Comment by Steviey** [comment]
+1
Excellent Suggestion!
![Image of Yaktocat](https://octodex.github.com/images/goretocat.png)

**Comment by sibelius** [comment]
U can take a look on this issue https://github.com/exponent/ex-navigation/issues/175 from ex-nav

and my example with ex-nav-relay

I'll try to make an example for react-navigation and relay

**Comment by sibelius** [comment]
check this out: https://github.com/sibelius/ReactNavigationRelay

**Comment by ericvicenti** [comment]
Thanks for writing up that example, @sibelius. It looks great!

**Comment by lukecwilliams** [comment]
FYI, it's trivial to implement without adding extra libraries - it's only necessary for the `screen: ` parameter to be set to a component that renders `Relay.RootContainer`.  Example here:

https://github.com/react-community/react-navigation/issues/588#issuecomment-287480454

**Comment by tslater** [comment]
@sibelius Do you know of any examples of how to use react-navigation with the newer `usePreloadedQuery`?
