### ISSUE TITLE
Tabbar IndicatorStyle not working

### ISSUE THREAD

**Issue by sawwy** [react-community/react-navigation#1840]
I am reading through the Tabbar documentation and I can modify IndicatorStyle for bottom (the bottom line in tabbar). However, when I try to set that line on top of the tabbar, it does not work. Any ideas where to start looking for the remedy? Here is my code:

tabBarOptions: {
      indicatorStyle: {
        borderTopColor: '#000000',
        borderTopWidth: 4
      }
}

**Comment by fabriziomoscon** [comment]
https://github.com/react-community/react-navigation/issues/504#issuecomment-282931627

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
