### ISSUE TITLE
Access Navigation Dispatch

### ISSUE THREAD

**Issue by Asleepace** [react-community/react-navigation#1843]
Hello, I was wondering how can I access the Navigation Dispatch object that gets printed to the console.log every time I navigate to a new screen?

<img width="723" alt="screen shot 2017-06-12 at 2 07 51 pm" src="https://user-images.githubusercontent.com/10716803/27055281-bba6a7e0-4f78-11e7-896c-96d8dac11158.png">

Mainly I would like to access the newState property so I can find the key to my home route and use that to navigate back to the home view. The problem is the navigation prop on my current screen only displays its own route and nothing else...

**Comment by matthamil** [comment]
You can access it by overriding your Navigator's `onNavigationStateChange`. See https://github.com/react-community/react-navigation/blob/77b04f342d4791ec6470685905133f440e3968c1/src/createNavigationContainer.js#L115-L144

**Comment by matthamil** [comment]
Closing this issue. If the above solution did not solve your problem, please open a new issue. 😄
