### ISSUE TITLE
Clicking on tab bar icon does not link me to tab page

### ISSUE THREAD

**Issue by delgiudices** [react-community/react-navigation#1845]
### Current Behavior
Clicking on tab bar icon does not redirect me to the tab. Label does.
### Expected Behavior
Clicking on tab bar icon should redirect to the tab i'm clicking.
### Your Environment
iPhone 6 ios 10.3 emulator on mac os 10.12.3. Tested on iphone 7 plus device and does not work either

| software         | version
| ---------------- | -------
| react-navigation |  ^1.1.86
| react-native     |  0.44.2
| node             |  4.4.3
| npm or yarn      | npm 3.8.6

**Comment by spencercarli** [comment]
Without any code we can't help debug this.
