### ISSUE TITLE
Error after install react-navigation package with npm

### ISSUE THREAD

**Issue by cronos88** [react-community/react-navigation#1846]
### Current Behavior
I created a new project in create-react-native-app. Next, I was install react-navigation: npm install --save react-navigation.

When I run: yarn start in the terminal, appear this error:

yarn start v0.24.5
$ react-native-scripts start 
sh: 1: react-native-scripts: not found
error Command failed with exit code 127.

I created again another app and next I was install react-navigation with yarn and next yarn start and the error not appear. I believe error appear when react-navigation is installed with npm.

### Your Environment

| software               | version
| ----------------------- | -------
| react-navigation   | 1.0.0-beta.11  
| react-native          |  0.44.0
| node                     | 7.10.0
| npm or yarn         | npm 5.0.3 - yarn 0.24.5
| linux                     | Linux Mint 18.1 64bits

**Comment by vingel** [comment]
run 'npm install -g react-native-sripts'  and then try again.

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!

**Comment by JahanzaibHussain** [comment]
am also stuck at this point, some one help me out!

**Comment by Fazalcs13** [comment]
Is there anyone who solved the issue???
