### ISSUE TITLE
Can't remove header shadow on ios when backgroundColor is transparent

### ISSUE THREAD

**Issue by m860** [react-community/react-navigation#1847]
```javascript
headerStyle:{
    backgroundColor:"transparent",
    shadowOpacity:0,
    shadowOffset:{height:0},
    shadowRadius:0
}
```
header shadow can't be removed on ios

**Comment by carsonwah** [comment]
I faced the same problem after upgrading from 1.0.0-beta.11 to 1.0.0-beta.12.

I couldn't find any related style when I inspect it. But after digging out the 
react native ViewStylePropTypes docs, I found some fix to it.
Before:
```
elevation: 0,
borderBottomWidth: 0,
shadowColor: 'transparent',
shadowRadius: 0,
shadowOffset: {
    height: 0,
},
```
And now I fixed it by adding one more style:
```
borderBottomWidth: 0
```
Hope this helps.

**Comment by jasonkuhrt** [comment]
All I had to do was:

```
shadowColor: "transparent",
```

**Comment by spencercarli** [comment]
Seems this is a styling issue unrelated to this library

**Comment by kamal** [comment]
It looks like the shadow for iOS is no longer coming from `shadow*` styles, but rather `borderBottomWidth` and `borderBottomColor`. So to remove the "shadow" from iOS header, you would set

```
headerStyle: {
  borderBottomColor: 'transparent',
  borderBottomWidth: 0
}
```

This change was introduced in https://github.com/react-community/react-navigation/commit/2da42c0cc09cd64d5991cb15125a50fff9cbf58c
