### ISSUE TITLE
How to place back button icon?

### ISSUE THREAD

**Issue by m860** [react-community/react-navigation#1850]
I want to use my back button icon , how to do it?

**Comment by QQizi** [comment]
You can use a custom Button and use this on onPress : 

`const backAction = NavigationActions.back();
this.props.navigation.dispatch(backAction);`

**Comment by matthamil** [comment]
You can provide your own custom [headerLeft](https://reactnavigation.org/docs/navigators/stack#headerLeft) component.

```js
static navigationOptions = ({ navigation }) => ({
  headerLeft: 
    <YourTouchableComponent onPress={() => navigation.goBack()}>
      <Image source={require('path/to/image')>
    </YourTouchableComponent>
});
