### ISSUE TITLE
TabNavigator inside TabNavigator throws exception "the specified child already has a parent"

### ISSUE THREAD

**Issue by veedeo** [react-community/react-navigation#1853]
TabNavigator inside TabNavigator will throw exception "the specified child already has a parent" if parent tabbar swipeEnabled: false and child tabbar swipeEnabled: true.

If parent tabbar swipeEnabled: true and child tabbar swipeEnabled: false it renders but child tabbar is broken

any ideas what I miss here?

**Comment by spencercarli** [comment]
If each tabnavigator has the same routes it could potentially cause an issue.

But without any code samples it's hard to help. Please provide them and I can help further
