### ISSUE TITLE
Is there any advantage of using Redux on React-Navigation

### ISSUE THREAD

**Issue by efkan** [react-community/react-navigation#1854]
As far as I know from [official simple examples](https://reactnavigation.org/docs/intro/), React-Navigation can be used without `Redux`.

I wonder that is there any advantage of Redux usage on React-Native?

**Comment by ericvicenti** [comment]
Sometimes your navigation logic/behavior will depend on other data in your app. In those cases it may be desirable to use redux and customize the navigation logic alongside the rest of your state management
