### ISSUE TITLE
goBack transition for a custom HeaderLeft Button(question)

### ISSUE THREAD

**Issue by jasan-s** [react-community/react-navigation#1860]
I'm using a custom headerback Button like so: 
```
Auth: {
    screen: AuthContainer,
    navigationOptions: (props) => {
      const { navigation } = props
      return {
        headerLeft: CustomNavButton(navigation),
      }
    },
  }

export const CustomNavButton = (navigation) => {
  const { containerStyle } = styles
  return (
    <View style={containerStyle}>
      <TouchableOpacity onPress={() => navigation.navigate('Home')}>
        <Icon name='ios-arrow-back-outline' size={35} color={colors.buttonBackground} />
      </TouchableOpacity>
    </View>
  )
}
```

However the transition when using navigation.navigate() is "right to left" but I want the transition "left to right". 

| software         | version
| ---------------- | -------
| react-navigation:  |  1.0.0-beta.11
| react-native: |  0.45.1

**Comment by octopitus** [comment]
It should be `navigation.goBack()` instead of `navigation.navigate('Home')`. `navigate` means push a new route to the stack.

**Comment by jasan-s** [comment]
But home in this case is not the previous navigator, it is a navigator
before the previous navigator.

**Comment by octopitus** [comment]
[Here](https://github.com/react-community/react-navigation/pull/1187#issuecomment-300112470) and [here](https://github.com/react-community/react-navigation/issues/1490#issuecomment-304801223) is some examples to custom transition. But if I am a user, I would expect that new screen comes from right to left.

**Comment by jasan-s** [comment]
Found out I can pass in a screen name to the `navigation.goBack('Home')`.
