### ISSUE TITLE
withNavigation does not work on web

### ISSUE THREAD

**Issue by joncursi** [react-community/react-navigation#1862]
I have implemented a web integration according to the docs and pretty much everything is working for me except for a Redux integration (no docs on this) and `withNavigation`. When I try to enhance my components with a `navigation` prop as per usual via `withNavigation`, it comes into the component as `undefined` with the following error:

```
Warning: Failed context type: The context `navigation` is marked as required in `withNavigation(Connect(InjectIntl(HOC)))`, but its value is `undefined`.
    in withNavigation(Connect(InjectIntl(HOC))) (created by HOC)
```

**Comment by agrcrobles** [comment]
Hey,
`withNavigation` works only for built in native navigators, if you integrated the web, you might have implemented your own `BrowserAppContainer` view and therefore you won't have the navigation in the context.

**Comment by joncursi** [comment]
Yeah, I implemented a `BrowserAppContainer`, similar to what the docs pointed to in GitHub. Have little idea what this component does though, TBH, because it's fairly complex and there were no inline comments for me to learn from. I'm REALLY looking forward to more docs / examples / explanations on the Web integration side of things, and hoping it arrives before I decide to ditch this approach for a better-documented solution like React Router.

**Comment by joncursi** [comment]
Is the only solution on Web to manually pass navigators down your component tree? This is making my code extremely messy and brittle.

**Comment by kelset** [comment]
Closing this in favor of #782

**Comment by jmatsushita** [comment]
Hi there,

I'm also looking at how to replace withNavigation until more detailed docs are written. 

@agrcrobles I'm thinking it would help me understand how to deal with `withNavigation` if I understood your comment. Could you explain if it would be possible to have "the navigation in the context" despite using `BrowserAppContainer`? 

Would there be a problem putting `navigation` in context (like with [`SceneView`](https://github.com/react-navigation/react-navigation/blob/master/src/views/SceneView.js#L25)) like this (replacing [these lines](https://github.com/react-navigation/react-navigation/blob/master/website/src/BrowserAppContainer.js#L126-L137):
```js
    static childContextTypes = {
      getActionForPathAndParams: PropTypes.func.isRequired,
      getURIForAction: PropTypes.func.isRequired,
      dispatch: PropTypes.func.isRequired,
      navigation: PropTypes.object.isRequired
    };
    getChildContext() {
      return {
        getActionForPathAndParams: this.getActionForPathAndParams,
        getURIForAction: this.getURIForAction,
        dispatch: this.dispatch,
        navigation: addNavigationHelpers({
          state: this.state,
          dispatch: this.dispatch
        })
      };
    }
```
