### ISSUE TITLE
Tab Navigator nested in Drawer Navigator - Transition to tab navigation flow chunks

### ISSUE THREAD

**Issue by cohendl** [react-community/react-navigation#1864]
When I go from Map or Shuttle screens to the Main in my Tab Navigator the Drawer chunks as it is animating away.

Any potential causes of this behavior?

Thanks!

Dan

Code below: 

`const tabScene = TabNavigator({
  Main: {
    screen: StackNavigator({
      home: { screen: HomePage },
      party: { screen: PartyPage }
    })
  },
  Bands: { screen: BandPage },
  Events: { screen: EventsPage },
  CheckInPage: { screen: CheckIn },
},
{
  initialRouteName: 'Main',
  tabBarOptions: {
    labelStyle: { fontSize: 12 }
  },
  navigationOptions: {
    tabBarVisible: true
  },
  lazyLoad: false,
});

const MyApp = DrawerNavigator({
  Wrapper: { screen: tabScene },
  Map: { screen: MapPage },
  Shuttle: { screen: ShuttleMap },
},
{
  contentComponent: SideMenu,
});`

**Comment by jainniket** [comment]
can you check in debugger how may actions are being triggered at that time?
you may use `React-Native-Debugger` for the same.

**Comment by spencercarli** [comment]
Going to close this since it's been stale for a few months now.
