### ISSUE TITLE
Reseting the navigation state without animation

### ISSUE THREAD

**Issue by kevin-wolf** [react-community/react-navigation#1865]
Let's suppose I have a basic application with three different screens:

```
- Login
- SignUp
- Profile
```

When I am on the `Login` view, I can reset my navigation state successfully because I am currently on the index `0`.

But, when I am on the `SignUp` view, when I try to replace the navigation state, since I am currently on the index `1`, it does a back animation and then replaces the view.

So, how to reset the navigation stack without the back transition, if I am on an index grater than the one that I one to reset?

**Comment by adrianlemess** [comment]
me too!

**Comment by oxape** [comment]
me too!

**Comment by migueloller** [comment]
Here is the way I get around it. This is a bit hacky since React Navigation doesn't export the style interpolators but it gets the job done.

```js
import { StackNavigator } from 'react-navigation'
import CardStackStyleInterpolator from 'react-navigation/src/views/CardStackStyleInterpolator'

import Home from './scenes/Home'
import Page from './scenes/Page'

const Navigator = StackNavigator({
  Home: { screen: Home },
  Page: { screen: Page },
}, {
  transitionConfig: () => ({
    screenInterpolator: (sceneProps) => {
      // Disable the transition animation when resetting to the home screen.
      if (
        sceneProps.index === 0 &&
        sceneProps.scene.route.routeName !== 'Home' &&
        sceneProps.scenes.length > 2
      ) return null

      // Otherwise, use the usual horizontal animation.
      return CardStackStyleInterpolator.forHorizontal(sceneProps)
    },
  }),
})
```

**Comment by migueloller** [comment]
If all you want is to disable all animations then just use this:

```js
const Navigator = StackNavigator({
  Home: { screen: Home },
}, {
  transitionConfig: () => ({ screenInterpolator: () => null }),
})
```

**Comment by oxape** [comment]
Thank you. I find that implement this feature will be the next version on the roadmap for V2: [#1263 ](https://github.com/react-community/react-navigation/issues/1263).[issue1893](https://github.com/react-community/react-navigation/issues/1839). Now I mix react-router and react-navigation to solve my problem in my react native project. But can‘t deal with all the cases. Your solution is perfect for me.

**Comment by cccRaim** [comment]
@migueloller but the Header still has the animation, how to disable them?

**Comment by RomanVanso** [comment]
yes, how should we disable the header animation?

**Comment by Tom29** [comment]
@migueloller can we access to `navigation.state.params` inside `screenInterpolator`?
I need to detect when to disable transition by a parameter or at beginning #2086

**Comment by Tom29** [comment]
Found the way here #1490 
Use: `sceneProps. route.params`

**Comment by connorvincent** [comment]
```
const navigate = StackNavigator({
    Home: { screen: Home },
    Other: { screen: OtherScreen},
    }, {
        transitionConfig: () => ({
            transitionSpec: {
                duration: 0,
            },
        }),
});
```
Credit to X-Tender,
https://github.com/react-community/react-navigation/issues/1254
https://github.com/X-Tender

**Comment by EduardJS** [comment]
Just putting it out, it's actually found in another path now, than the one mentioned by **migueloller**

```import CardStackStyleInterpolator from 'react-navigation/src/views/CardStack/CardStackStyleInterpolator'```

**Comment by kelset** [comment]
Closing this in favor of #1493 since it's the one with the most comments and proposed solution (just trying to reduce redundancy)

**Comment by brooth** [comment]
Based on the answers above:
```
  transitionConfig: (sceneProps) => ({
      transitionSpec: {
        duration: sceneProps.scene.route.routeName === 'Home' ? 0 : 260,
      },
    }),
```

or you can create an alias for `Home`, smth like `Home_noTransition`:

```
const Navigator = StackNavigator({
  Home: { screen: Home },
  Home_noTransition: { screen: Home },
  Page: { screen: Page },
}, {
 transitionConfig: (sceneProps) => ({
      transitionSpec: {
        duration: sceneProps.scene.route.routeName === 'Home_noTransition' ? 0 : 260,
      },
    }),
}
```

**Comment by lvst09** [comment]
newState.routes = routes;
          newState.index = 0;
          newState.isTransitioning = false;

it works in Reducer.js

**Comment by shahabrauf18** [comment]
Interpolator route has been changed to

`import StackViewStyleInterpolator from 'react-navigation-stack/src/views/StackView/StackViewStyleInterpolator'`

**Comment by Yooooomi** [comment]
Hello! Any ways to achieve this after v4? It seems like we can only tell if a screen has animations or not and not fine control it
