### ISSUE TITLE
How to send props from navigator to it's screen without disrupting the navigator.navigation in that particular screen

### ISSUE THREAD

**Issue by Shrek53** [react-community/react-navigation#1867]
When I do something in my stack navigator 
`export const NewsFetch = StackNavigator({
Brief     :  { screen :  props=> <NewsColumnFixed head='bangladesh' /> },
Detail   :  { screen : NewsDetails },               
});`

the default navigator props is not passing down or somehow my props named head overwriting the default props and so I can not navigate from one screen to another using navigator.navigate()

Thanks in advance.

**Comment by Shrek53** [comment]
Find the solution after a long hustle I found this on a Cooment of @joshuapainter
in this issue https://github.com/react-community/react-navigation/issues/876
 
His Code

import React from 'react';

import {
  AppRegistry,
  Text,
} from 'react-native';

import { StackNavigator } from 'react-navigation';

class MyApp extends React.Component {
  render() {
    console.log('this.props in MyApp', this.props); // This will list the initialProps.

    // StackNavigator **only** accepts a screenProps prop so we're passing
    // initialProps through that.
    return <Navigator screenProps={this.props} />; 
  }
}

class HomeScreen extends React.Component {
  render() {
    console.log('this.props in HomeScreen', this.props);
    // This will output something like this: 
    // { screenProps: { ...your initialProps }, navigation: { ...StackNavigator stuff... } }

    return <Text>My initialProps are {JSON.stringify(this.props.screenProps)}.</Text>;
  }
}

const Navigator = StackNavigator({
  Home: { screen: HomeScreen },
});

AppRegistry.registerComponent('MyApp', () => MyApp);

**Comment by silhouette5366** [comment]
can you guys please give a solution which works for react-navigation-3 in which you must set up your app container directly.
