### ISSUE TITLE
remove shadow under the header

### ISSUE THREAD

**Issue by tsmrafee-bs** [react-community/react-navigation#1868]
![screenshot_1497418725](https://user-images.githubusercontent.com/27723951/27117045-79b118fa-50f6-11e7-92ce-2bc595ec67b5.png)
I use same background color in the header and the next component. but there is a line between them. 
I need to remove the line. It should look like one component. Is it possible?

**Comment by tsmrafee-bs** [comment]
shadowOpacity: 0,
shadowOpacity: 0,
shadowOffset: {
   height: 0,
},
elevation: 0,

**Comment by night-king** [comment]
Thank you very much, fixed my issue.
