### ISSUE TITLE
pass in InitialRouteName as a prop OR use a ScreenProp as InitialRouteName 

### ISSUE THREAD

**Issue by jasan-s** [react-community/react-navigation#1869]
There is not a InitialRouteName prop yet on StackNavigator at render (when called from another Component), where I can just pass in the screen name I want to render initially.  However is it possible to use ScreenProps passed to the Stack Navigator to condinally set the IntialRouteName in the StackRouter config? 

My Current solution is a Duuplication of the StackNavigator with the only change being intialRouteName

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.11
| react-native     |  0.45.1

**Comment by spencercarli** [comment]
There's no great way to do this given the static nature of route definitions. I've used this pattern before

```javascript
const MyStack = (initialRoute) => {
  return StackNavigator({
    ...
  }, {
    initialRouteName, // pass the initial route & any other settings
  });
};
```

And then use this as `<MyStack />`.

Hope that helps! Since this was opened a while ago I'm going to close it to reduce the # of open issues. Happy to continue discussion
