### ISSUE TITLE
set initial route based on redux props

### ISSUE THREAD

**Issue by ezha86** [react-community/react-navigation#1870]
hi community.
 i set up navigation with redux and now trying to do navigate between scenes depends on my
 props. my tab navigator and stacknavigators are connected to redux.
with one single stackNavigator for 1 tab it works fine and i can see index changing while navigate through stack.
but in my case i need behavior like this:
 - for example  if i have  'parrots' in my props and its count is 0 i want to have navigate to scene 1 but if count more than 1 i want to navigate to scene 2 within 1 tab. (dynamically change initialRouteName within StackNavigator that seems not possible))
 i have created 2 stacknavigators and component where i do  check if props.parrots.length more than 1 or not and return stack1 with scene1 or stack2 with scene2. it works

class InitNavigation extends Component {
  render(){
    if(this.props.parrot.length === 0){
      return <NavigationStack1/>
    }
      return <NavigationStack2/>
    }
}
but how to handle redux state for this ?
how do you guys solve this ?
can provide code samples if my explanations are not clear

thanks in advance.

**Comment by spencercarli** [comment]
There's no great way to do this given the static nature of route definitions. I've used this pattern before

const MyStack = (initialRoute) => {
  return StackNavigator({
    ...
  }, {
    initialRouteName, // pass the initial route & any other settings
  });
};
And then use this as <MyStack />.

Hope that helps! Since this was opened a while ago I'm going to close it to reduce the # of open issues. Happy to continue discussion

**Comment by jasan-s** [comment]
@spencercarli  I followed the pattern above however if I do and dispatch Redux action from `onNavigationStateChange` the Navigation breaks. See [Example](https://snack.expo.io/@jasan/react-navigation-w-redux). 

Notice if you click on `open screen 2`  the redux action fires but the screen never changes. If Line 170 (`this.props.update();`) is commented the navigation works.   Any Suggestions.
