### ISSUE TITLE
headerBackTitle doesn't show  at all in android

### ISSUE THREAD

**Issue by cityvoice** [react-community/react-navigation#1871]
I route the page from `List` to `Detail`,  `headerBackTitle` doesn't show in  `Detail` whether I set it  in `List` or `Detail`.In fact, it doesn't show at all.

```
	List: { 
		screen : ListComponent,
		navigationOptions: ({navigation}) => ({
			headerBackTitle:'Home',//headerBackTitle doesn't show in Detail
		})
	},
```
```
	Detail: { 
		screen : DetailComponent,
		navigationOptions: ({navigation}) => ({
                        headerTitle:'Back', //it works
			headerBackTitle:'Back',//doesn't work 
		})
	}, 
```
```
	Detail :{ 
		screen : DetailComponent,
		navigationOptions: ({navigation}) => ({
                        //do nothing, headerBackTitle doesn't show
		})
	}, 
```
It doesn't show whatever I do anything!It only renders an arrow icon without title.

**Comment by cityvoice** [comment]
sorry, I have checked the docs, and `headerBackTitle` is suported only in IOS

**Comment by Amurmurmur** [comment]
You might want to close the issue, if everything is solved for you successfully 👍 
No offence just too many issues that are open, and do make it harder to actually track real issues :/

**Comment by golestanirad** [comment]
so what should we do to have headerBackTitle? on Android

**Comment by matthamil** [comment]
@golestanirad Please open a new issue if you are experiencing issues with react-navigation.
