### ISSUE TITLE
Using with redux got error "Cannot read property 'createElement' of undefined"

### ISSUE THREAD

**Issue by jaggerwang** [react-community/react-navigation#1873]
### Current Behavior
![image](https://user-images.githubusercontent.com/1255011/27132144-4426609c-5140-11e7-905c-de67c54bb393.png)

I'm using react with redux, so need to pass react-redux Provider to react components. But it always complain the error above. Here is the source code.

index.ios.js
```javascript
/**
 * 在球场
 * zaiqiuchang.com
 */

import './src/setup';
```

setup.js
```javascript
/**
 * 在球场
 * zaiqiuchang.com
 */

import {AppRegistry} from 'react-native';
import App from './App';

AppRegistry.registerComponent('gtgj', () => App);
```

App.js
```javascript
/**
 * 在球场
 * zaiqiuchang.com
 */

import {React, Component} from 'react';
import {Provider} from 'react-redux';

import store from './store';
import {AppNavigator} from './navigation';

export default class App extends Component {
  render() {
    return (
      <Provider store={store}>
        <AppNavigator />
      </Provider>
    );
  }
}
```

navigation.js
```javascript
/**
 * 在球场
 * zaiqiuchang.com
 */
import {StackNavigator} from 'react-navigation';

import * as components from './components';

export const AppNavigator = StackNavigator({
  Bootstrap: {screen: components.Bootstrap},
});
```
### Expected Behavior
Navigate to Bootstrap screen.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.11
| react-native     |  0.44.3
| node             | v6.11.0
| npm or yarn      | npm 3.10.10

**Comment by jaggerwang** [comment]
There is no need to manage navigation state in redux store.

**Comment by matthamil** [comment]
Are you sure this issue is caused by redux? `createElement` is a React method. If `React` is undefined or improperly imported in a file, you will get this error when your app tries to run the compiled JSX since `<View>` is syntactic sugar for `React.createElement`. Try changing your import from `import { React, Component } from 'react';` to `import React, { Component } from 'react';`

**Comment by jaggerwang** [comment]
My fault, Thanks a lot!
