### ISSUE TITLE
setParams not being updated after resetting the navigation stack

### ISSUE THREAD

**Issue by samridhgupta** [react-community/react-navigation#1875]
### Current Behavior
After setting params with `setParams` in `componentDidMount` the params should get updated, but the params are getting reset due to an earlier resetting of navigation stack.

### Expected Behavior
After setting params with `setParams` in `componentDidMount` the params should get updated.

### Your Environment
MacOS `10.12.5`

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.7 - commit hash `d211492a4c0d66b9a6c8b3e027e220079851362d`
| react-native     |  `0.43`
| node             | `6.11`
| npm or yarn      | yarn `0.24.x`

Navigation Log output - 
```
Jun 14 23:14:18 Admins-MacBook-Pro-2 DemoApp[46110]: 'Navigation Dispatch: ', { action: 
	   { type: 'Navigation/RESET',
	     index: 0,
	     actions: [ { type: 'Navigation/NAVIGATE', routeName: 'Dashboard' } ] },
	  newState: 
	   { index: 0,
	     routes: [ { routeName: 'Dashboard', key: 'Init0' } ] },
	  lastState: { index: 0, routes: [ { routeName: 'Home', key: 'Init' } ] } }
Jun 14 23:14:18 Admins-MacBook-Pro-2 DemoApp[46110]: 'Navigation Dispatch: ', { action: 
	   { type: 'Navigation/SET_PARAMS',
	     params: { handleLogout: [Function: bound onLogoutPressed] },
	     key: 'Init0' },
	  newState: 
	   { index: 0,
	     routes: 
	      [ { routeName: 'Dashboard',
	          key: 'Init0',
	          params: { handleLogout: [Function: bound onLogoutPressed] } } ] },
	  lastState: 
	   { index: 0,
	     routes: [ { routeName: 'Dashboard', key: 'Init0' } ] } }
Jun 14 23:14:18 Admins-MacBook-Pro-2 DemoApp[46110]: 'Navigation Dispatch: ', { action: 
	   { type: 'Navigation/RESET',
	     index: 0,
	     actions: [ { type: 'Navigation/NAVIGATE', routeName: 'Dashboard' } ] },
	  newState: 
	   { index: 0,
	     routes: [ { routeName: 'Dashboard', key: 'Init0' } ] },
	  lastState: 
	   { index: 0,
	     routes: 
	      [ { routeName: 'Dashboard',
	          key: 'Init0',
	          params: { handleLogout: [Function: bound onLogoutPressed] } } ] } }
```

**Comment by spencercarli** [comment]
Hi! Can you check if this is still an issue with the most recent release?

**Comment by Pollizzio** [comment]
I'm getting the same issue scenario on beta 15

**Comment by kelset** [comment]
Pinging OP @samridhgupta  since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open, because if I get no answer in the next 7 days I will close it.

**Comment by kelset** [comment]
(actually, closing in favor of https://github.com/react-community/react-navigation/issues/1912 )

**Comment by kelset** [comment]
(actually, closing in favor of https://github.com/react-community/react-navigation/issues/1912 )
