### ISSUE TITLE
DrawerNavigator: "undefined is not an object" when close it.

### ISSUE THREAD

**Issue by vendramini** [react-community/react-navigation#1876]
I've a DrawerNavigator as main navigator. It opens with the command: `this.props.navigation.navigate('DrawerOpen');`

But when it closes an error appear:

![drawer-erro1](https://user-images.githubusercontent.com/510878/27149685-c544b3f2-511a-11e7-949e-4862380777b6.png)

My navigator config:
```javascript
export const AppNavigator = StackNavigator(
    {
        //a lot of screens
    },
    {
        headerMode: 'none',
        initialRouteName: 'Menu'
    }
);

export const RootNavigator = DrawerNavigator(
    {
        App: { screen: AppNavigator },
    },
    {
        initialRouteName: 'App',
        drawerPosition: 'right',
    }
);

class AppWithNavigationState extends React.Component {
    render() {
        return (
            <RootNavigator navigation={addNavigationHelpers({
                dispatch: this.props.dispatch,
                state: this.props.nav,
            })} />
        );
    }
}

const mapStateToProps = state => ({
    nav: state.nav,
});

export default connect(mapStateToProps)(AppWithNavigationState);
```

And my reducer (small for simplicity):
```javascript
import { NavigationActions } from 'react-navigation';
import { RootNavigator } from '../navigators/config';

export default function nav(state, action) {
    let nextState;

    switch(action.type) {
        default:
            nextState = RootNavigator.router.getStateForAction(action, state);
            nextState = {...nextState, ...defaultState}
    }

    return nextState || state;
}
```
I don't have an "initial state" for the navigator. To be honest, I didn't understand why. But all works when my root navigator was an `StackNavigator`, but now I should implement it as a `DrawerNavigator` and this happens.

It's my first experience with react-native.

I appreciate any help.

| software         | version
| ---------------- | -------
| react-navigation |  ^1.0.0-beta.9
| react-native     |  ^0.45.0
| node             |  7.10.0
| npm      | 5.0.3

**Comment by vendramini** [comment]
**UPDATE**

I've updated the react-navigation version to 1.0.0-beta.11 and it stopped to crush when closes it. But show me the same error when I press some item on menu.

Still trying and investigating the problem.

**Comment by vendramini** [comment]
Everything is working now, I misunderstood some concepts and re-coded all structure. Closing this issue.

**Comment by RobbyWH** [comment]
Hello @vendramini, 

I found the same problem, can you tell your solution?

**Comment by vendramini** [comment]
@RobbyWH sorry the delay, dude.

I just re-coded all my structure on a better way. I really don't know what exactly I did =(
Did u updated your react-navigation? What version are you using? Could you show me your nav config?

As i said, I just did a great refactoring, using the right concepts like creating a StackNavigator for screens with childs, etc.
