### ISSUE TITLE
titleTemplate navigation option

### ISSUE THREAD

**Issue by joncursi** [react-community/react-navigation#1877]
It would be great if `navigationOptions` supported a `titleTemplate` key so that you can specify a pattern to use to format all titles. This would be defined at the stack level as a default, and then individual titles are defined at the screen-level to pass strings into the template.

I got this idea from React Helmet, which does this on the web via:

```jsx
// app.js
<Helmet
  titleTemplate="MyApp - %s"
>
  {...}
</Helmet>
```

Where `%s` is the string defined at the screen-level:

```jsx
// screen.js
<Helmet
  title="Screen Title"
>
  {...}
</Helmet>
```

Resulting title: `MyApp - Screen Title`.

This is an important feature to consider when it comes to the Web Integration of react-navigation. I'm tempted to use React Helmet for titles because of this, but that defeats the point of sticking with `react-navigation` for cross-platform code. So I'm at a fork in the road trying to decide which tradeoff to make.

**Comment by matthamil** [comment]
You can already do this with `react-navigation`. If you set a [screenProp](https://reactnavigation.org/docs/navigators/navigation-options) you could pass down a function to generate the title, i.e.:

```js
const Navigator = StackNavigator(/*routes, config*/);

export default class WrappedNavigator extends React.Component {
  getTitle = (name) => {
    return 'MyApp - ' + name;
  }
  render (
    <MyNavigator screenProps={{getTitle: this.getTitle}}/>
  );
}
```

Inside one of the `screen`s rendered by `Navigator`:

```js
export default class Profile extends React.Component {
  static navigationOptions = ({ screenProps }) => ({
    title: screenProps.getTitle('Screen Title')
  });

  render() {
    // ...
  }
}

**Comment by matthamil** [comment]
Closing this issue. If you are still having problems, please comment or open a new issue 😄
