### ISSUE TITLE
How to check screen position ?

### ISSUE THREAD

**Issue by sihitejulio** [react-community/react-navigation#1879]
> Sample  routesConfig

`const routesConfig = {`
  `Splash:{screen:SplashScreen},`
  `Home: { screen: homeStack },`
 ` Scan: {screen:scanStack},`
  `Login:{screen:loginStack},`
`};`
how to check current screen position or `Home` ?

**Comment by matthamil** [comment]
Thanks for the issue! I'm not sure I understand your question. Can you provide a more in-depth code snippet and the current behavior/expected behavior of what you are wanting?
