### ISSUE TITLE
Doesn't work with webpack 2

### ISSUE THREAD

**Issue by steida** [react-community/react-navigation#188]
```
in ./~/react-navigation/src/createNavigationContainer.js
Module parse failed: /Users/danielsteigerwald/dev/este/node_modules/react-navigation/src/createNavigationContainer.js Unexpected token (11:12)
You may need an appropriate loader to handle this file type.
| import addNavigationHelpers from './addNavigationHelpers';
| 
| import type {
|   NavigationAction,
|   NavigationContainerOptions,
 @ ./~/react-navigation/src/react-navigation.js 8:43-81
 @ ./src/browser/app/router.js
 @ ./src/browser/app/Root.js
 @ ./src/browser/main.js
 @ ./src/browser/index.js
 @ multi webpack-hot-middleware/client?path=http://10.0.1.3:8080/__webpack_hmr ./src/browser/index.js
```

Webpack 2 takes files from /src, then fail because it does not recognize `import type`.

**Comment by ericvicenti** [comment]
The codebase is type-annotated with flow. It sounds like we should probably strip the flow types from the built library.

In the mean time, you could configure webpack to strip the flow types.

**Comment by steida** [comment]
I tried, no success. I tried babel plugin for that, no success again. I tried cmd tool, it removed types with some code as well. 6 hours spent on that, fok that :(

**Comment by steida** [comment]
NPM library design with ES6 and flow is a shitty mess. No clear guidelines, no best practices, only darkness and coldness. Not your fault. Thank you anyway.

**Comment by satya164** [comment]
It's our fault. Libraries shouldn't be shipped without transpiling. I'll update the build scripts tonight if possible.

Meanwhile you can use https://www.npmjs.com/package/babel-plugin-transform-flow-strip-types

Remember to allow transpiling react-navigation, since by default it doesn't transpiles modules under node_modules

**Comment by steida** [comment]
Don't hurry, take your time. I am going to try https://github.com/4Catalyzer/found which seems to be the only sane and working routing solution for React web. I believe react-navigation for web needs time to consolidate and then, it should probably look (and therefore be replaceable) like found.

**Comment by ericvicenti** [comment]
>  only darkness and coldness

LOL, I totally agree and feel the same pain!

But I agree with @satya164. We can do better here.

@skevy is good at this stuff. Maybe we can find a best practice for compiled libraries going forward, and make it easier for people next time.

**Comment by agrcrobles** [comment]
yeah, I think it should be build in UMD in a similar way it is built [react-native-web](https://github.com/necolas/react-native-web/blob/master/webpack.config.js) but happy to see how create the bundle by webpack@2

**Comment by thurt** [comment]
guys, I also ran into this issue from a different angle when trying to do simple Jest snapshot test. I have it working now with the solution described here: https://github.com/GeekyAnts/NativeBase/issues/396#issuecomment-270116326 and of course make sure jest is using react-native preset

**Comment by grabbou** [comment]
@satya164 I remember you were working on "Fix webpack build", was that related to that by any chance?

**Comment by respectTheCode** [comment]
We ran into this same problem working on a cross platform (iOS, Android, Desktop Web) app. Publishing it as a UMD build would work but then we would need to add a library definition to flow-typed and maintain that as well.

ES6 + flow + NPM really is a mess right now. Seem like there is no simple answer.

**Comment by satya164** [comment]
I had fixed webpack build in the previous release, so I'm going to close this. Please comment if latest version has problems with webpack 2.
