### ISSUE TITLE
Keyboard congestion in oppo mobile phones!!

### ISSUE THREAD

**Issue by ZHT131** [react-community/react-navigation#1882]
### Keyboard congestion in oppo mobile phones!
For example, there are two pages of A and B, write a TextInput component respectively in the two page, when in the A page, click on the pop-up keyboard TextInput, and then close the keyboard, and then open the new page B, click on the pop-up TextInput keyboard, the keyboard is closed again, and then return to the A page, click TextInput cannot eject keyboard. The keyboard had blocked, when you press the standby button again and open the pop-up keyboard, ask the people encountered this problem? Hope to answer it.

![gif5](https://user-images.githubusercontent.com/22323594/27162677-2784c328-51b5-11e7-9612-5aeac77c9d23.gif)

react-navigation :1.0.0-beta.11

**Comment by matthamil** [comment]
Is this an issue with React Navigation or React Native with these phones?

**Comment by spencercarli** [comment]
Closing for lack of followup by OP

**Comment by DemaHamson** [comment]
i have the same problem in oppo phone too after using react-navigation. hope to solve

**Comment by NoPPT** [comment]
@ZHT131 Have you solved the problem? I have also encountered this problem.
