### ISSUE TITLE
Feature: Pass down props in goBack method

### ISSUE THREAD

**Issue by jamesone** [react-community/react-navigation#1885]
### Current Behavior
I don't believe the current behaviour allows for passing custom props down via the goBack method

### Expected Behavior
It would be super handy to pass down props in the goBack method! This would be helpful to determine what component you just came from OR allow you to pass down data that has just been created in another component.

E.g `goBack(key, { from: 'name_of_route', ...otherCustomProps }`

**Comment by kelset** [comment]
Duplicate https://github.com/react-community/react-navigation/issues/938
