### ISSUE TITLE
How to get title in Custom Header ? 

### ISSUE THREAD

**Issue by nilaybrahmbhatt** [react-community/react-navigation#1886]
I create custom header in navigationOptions
like .
```
navigationOptions: ({ navigation }) => ({
    header:Header,    
  })
```
but in header.js I can't get the title in navigation passed from this navigationOptions function.
please help me.

**Comment by matthamil** [comment]
Which title are you referring to? You can do something like:

```jsx
static navigationOptions = ({ navigation }) => ({
  header: <MyHeaderComponent title="My Title"/>
});
```

and access the prop `title` in `MyHeaderComponent` like any other prop.

**Comment by nilaybrahmbhatt** [comment]
@matthamil  i added custom header at time of stackNavigator initialization   

```
StackNavigator(Routes,{
  navigationOptions: ({ navigation }) => ({
    header:<headercomponent />,
   })
```

**Comment by Clowning** [comment]
@matthamil  Thanks :) ! Do you have any idea to put "<headercomponent />" in a function in the component ? 

Because with the static method i can't reach 'this' obviously!

**Comment by bristoljon** [comment]
I have the same problem, most of my screens use the same custom header component so I have defined it in `StackNavigator` initialisation like this..

```
export const Navigator = StackNavigator(routes, {
  headerMode: 'screen',
  navigationOptions: ({ navigation }) => ({
    header: props => <Header {...props} />,
  }),
})
```

I did find a work around but it seems pretty verbose for what seems to be a common use case..

```
// Header.js
...
render() {
  const { getScreenDetails, scene } = this.props
  const details = getScreenDetails(scene)
  return (
    <View>
      <Text>{details.options.title}</Text>
    <View>
  )
```

Why isn't the `title` available in the `Header` props automatically?

**Comment by RWOverdijk** [comment]
Is there a solution for this in place now? I still can't get the screen title in my header.

**Comment by VivekNayyar** [comment]
May be this article can help anyone who is struggling with custom header and bottom tabs in react navigation.
https://medium.com/@VivekNayyar/how-to-use-a-custom-header-and-custom-bottom-tab-bar-for-react-native-with-react-navigation-969a5d3cabb1

**Comment by intoxicated** [comment]
Can someone confirm this? I can't find getScreenDetails in v2.8.0. @VivekNayyar your article was helpful but still did not mention how to get options properly.

**Comment by intoxicated** [comment]
For those who have similar problem, I solved like below

1. Pass all props to your custom header.
```
navigationOptions: {
  header: props => <Header { ...props } />
  ...
}
```
in Header class use `scene.descriptor.options` for screen options 
```
  render() {
    let options = this.props.scene.descriptor.options

    return (
      <View style={styles.container}>
        <Text style={styles.title}>{options.headerTitle}</Text>
      </View>
    );
  }
```

**Comment by hamzawaleed0102** [comment]
For those looking for a solution in react-navigation 3.x, our **navigationOptions** looks like this.

`navigationOptions: ({ navigation }) => {
				return headerWithTitle(navigation)
}`

**headerWithTitle** is a simple function returning custom header component.

`const headerWithTitle = (navigation, title = null) => {

	return {
		header: props => <GradientHeader headerProps={props} navigation={navigation} />,
		headerStyle: { backgroundColor: ' transparent' },
		headerTintColor: '#fff',
		headerTitle: navigation.getParam("main") ? navigation.getParam("main").headerTitle : title,
	};
}`
