### ISSUE TITLE
Correct way to create a root Modal?

### ISSUE THREAD

**Issue by sean-macfarlane** [react-community/react-navigation#1887]
Hi, I feel as though I've searched through most of the issues/docs and I cannot find the exact correct way to create a Modal screen. 

### Current Behavior
Right now all I can find in the docs is to set `mode: 'modal'` but it says this does not work on Android? 
So I've tried using the React-Native Component with it as well which works, except I'm having trouble with `goBack()`. The only way I was able get it to work is with ` this.props.navigation.goBack(null);` but I find the closing animation is slow and delayed by like 2 seconds.

The basis of my navigator structure is such: 
```
const AuthStackNavigator = StackNavigator({
    Login: { screen: LoginModal }
}, {
        headerMode: 'none',
        mode: 'modal'
    });

const RootStackNavigator = StackNavigator({
    MainTabNavigator: { screen: NavTabBar },
    LoginModalNavigator: { screen: AuthStackNavigator }
}, {
        headerMode: 'none',
        mode: 'modal'
    });


export default class LoginModal extends Component {
 render() {
        return (
            <Modal
                style={styles.modal}
                animationType={"slide"}
                transparent={false}
                onPress={Keyboard.dismiss}
            >
                ....
            </Modal>
     )};
}
```

### Expected Behavior
What I'm trying to do is from my "MainTabNavigator" be able to open the "LoginModalNavigator" and any point, and then go back to the previous state in "MainTabNavigator". 
HomeTab -> Open Login Modal -> Close Login Modal -> HomeTab

So what is exactly the correct way of creating a Modal screen in React-Navigation? For iOS and Android.
Thank You.

### Your Environment
| software         | version
| ---------------- | -------
| react-navigation |  "^1.0.0-beta.9"
| react-native     |  "^0.43.4"
| node             | v7.9.0
| npm or yarn      | 4.20

**Comment by nonameolsson** [comment]
Yesterday I was googling for the same thing! Thanks for creating this issue.

**Comment by rad182** [comment]
+1

**Comment by dmr07** [comment]
According to the contributors, it's not recommended to use RN's Modal component with this project. From what I can see, I'd recommend trying `<View>` or `<ScrollView>` components instead.

**Comment by koenpunt** [comment]
It should work without using the react native `Modal`.

```js
const AuthStackNavigator = StackNavigator({
  Login: LoginScreen,
});

const RootStackNavigator = StackNavigator({
  MainTabNavigator: { screen: NavTabBar },
  LoginModalNavigator: { screen: AuthStackNavigator },
}, {
  headerMode: 'none',
  mode: 'modal',
});
```

With such a setup you can call `navigation.navigate('LoginModalNavigator')`, and then the `AuthStackNavigator` will be presented on top of everything.

Example snack: https://snack.expo.io/rkWC409QZ

**Comment by a83988029** [comment]
@koenpunt 
In your example, how to dissmiss `AuthStackNavigator` in `RegScreen`
```
const LoginScreen = ({ navigation }) => (
  <View style={styles.container}>
    <Button onPress={() => navigation.goBack(null)} title="Back" />
    <Button onPress={()=>navigation.navigate('Reg')} title='reg'/>
  </View>
);
const RegScreen = ({ navigation }) => (
  <View style={styles.container}>
    <Button onPress={() => navigation.goBack(null)} title="dismiss" />
  </View>
);
const AuthStackNavigator = StackNavigator({
  Login: {screen: LoginScreen},
  Reg:{screen: RegScreen}
});
```

**Comment by koenpunt** [comment]
@a83988029 haven't found a out of the box method for it, but it can be implemented using a custom action, for which you return a custom state.

You can have for example a `Navigation/POP` action;

```js
navigation.dispatch({ type: 'Navigation/POP' });
```

Which can be handled in the routers `getStateForAction` method:

```js
if (action.type === 'Navigation/POP') {
  return {
    ...state,
    routes: state.routes.slice(0, state.routes.length - 1),
    index: state.index - 1,
  };
}
```

Updated snack: https://snack.expo.io/rJRXDBhXZ

**Comment by sheprdinc** [comment]
@koenpunt your example is not totally a modal, at least not in the most common of ways known/accepted to most devs... i mean, technically it's a modal, but visually it's not... here's what typical modal's look like:
https://github.com/react-native-community/react-native-modal
https://raw.githubusercontent.com/mmazzarolo/react-native-animated-modal/master/extras/example-modal.gif
https://raw.githubusercontent.com/mmazzarolo/react-native-tips/master/imgs/modal.gif

I was not able to apply enough styling to your "modal" example to make it look/behave like a real modal would, so unfortunately I'm resigned to just calling your "modal" an overlay... i mean, visually speaking how is your 'modal' any different than just pushing a new screen onto the stack with a scene transition that flies in from the bottom? It's a bit misleading to refer to full screen overlays as modals.

Is there a way I can take your example and get it to look more like an actual modal?

**Comment by koenpunt** [comment]
It's a modal in the context of React Navigation, hence `mode: 'modal'` on the StackNavigator. But I see what you mean.

**Comment by koenpunt** [comment]
You can make the background of the card transparent, and have a child component displaying as a modal.

Something like this: https://snack.expo.io/H131gcsEZ

**Comment by nonameolsson** [comment]
@koenpunt Thanks for you example, I've been looking for something like that. Even though I have to agree with @sheprdinc that it doesn't feel like a "real" modal :)

**Comment by kelset** [comment]
Pinging OP @sean-macfarlane since this issue has not been active for a while, and it's related to an old version of the lib. Moreover in the README there are articles, tutorials & example to provide more ways to approach something like this.

Please let me know if you want this to remain open, because if I get no answer in the next 7 days I will close it.

**Comment by geminiyellow** [comment]
@sheprdinc  yes, but you know, when somebody use `react-native-web`, https://github.com/react-native-community/react-native-modal is not a solution.
