### ISSUE TITLE
Path starting with / leads to unexpected errors

### ISSUE THREAD

**Issue by slorber** [react-community/react-navigation#1889]
### Current Behavior

If you have a router with a path starting with "/",  it will lead to hard to debug errors, particularly inside `getActionForPathAndParams` 

The problem is that we use `const parts = path.split('/');` so if the path starts with a "/", then parts[0] will always be `""`.

For the record, current implementation is:

```
 getActionForPathAndParams(path: string, params: ?NavigationParams) {
      return (
        order
          .map((tabId: string) => {
            const parts = path.split('/');
            const pathToTest = paths[tabId];
            if (parts[0] === pathToTest) {
              const tabRouter = tabRouters[tabId];
              const action: NavigationNavigateAction = NavigationActions.navigate(
                {
                  routeName: tabId,
                }
              );
              if (tabRouter && tabRouter.getActionForPathAndParams) {
                action.action = tabRouter.getActionForPathAndParams(
                  parts.slice(1).join('/'),
                  params
                );
              } else if (params) {
                action.params = params;
              }
              return action;
            }
            return null;
          })
          .find((action: *) => !!action) ||
        order
          .map((tabId: string) => {
            const tabRouter = tabRouters[tabId];
            return (
              tabRouter && tabRouter.getActionForPathAndParams(path, params)
            );
          })
          .find((action: *) => !!action) ||
        null
      );
    },
```

### Expected Behavior

1) throw error on routers declared with path starting with a `/` for better DX

OR

2) accept paths starting with "/" and make `getActionForPathAndParams`work by removing leading "/" to get first path part.

**Comment by kelset** [comment]
Pinging OP @slorber since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open, because if I get no answer in the next 7 days I will close it.

**Comment by kelset** [comment]
Hi there @slorber ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.
