### ISSUE TITLE
header style is applied to 'left' and 'right' components

### ISSUE THREAD

**Issue by slicejunk** [react-community/react-navigation#189]
for instance with:
```
header: {
     style: {
          backgroundColor: 'transparent',
          borderWidth: 1,
          borderColor: 'red',
    }
}
```
![header](https://cloud.githubusercontent.com/assets/5887100/22630084/277b7e62-ebf3-11e6-8682-410917a24f2d.png)
 creates a border around the header container but also around the left and right

**Comment by satya164** [comment]
cc @grabbou

**Comment by grabbou** [comment]
Yeah, looks like a bug. Will send a PR in a second.
