### ISSUE TITLE
How to refresh Screen after goback ()

### ISSUE THREAD

**Issue by boyinfotronics** [react-community/react-navigation#1891]
How to refresh Screen after navigate goback () 
anyone have example ? thank you.
![goback](https://user-images.githubusercontent.com/25657869/27192003-d1eb5426-5223-11e7-9b57-2178c25f78d4.png)

**Comment by jasan-s** [comment]
If the data which is passed as state or prop to screen 1 component, React inherently would update the View, unless you you specify not to, in a lifecycle method.

**Comment by shangxinbo** [comment]
But navigation goback() doesn't pass any state or prop to screen 1 component.Don't it?

**Comment by jasan-s** [comment]
goback() is just an Action. your right it doesn't pass any state or props to screen 1.  However as shown in the picture the datasource for the ListView is being stored as either state or coming down as Prop from redux or another component. Thus if that Data changes the data Source will inherently change will then change the List View.

**Comment by shangxinbo** [comment]
@jasan-s you mean that you should change the data in screen1 or redux store before goBack()?

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!

**Comment by brentvatne** [comment]
hi @khushboogupta1! you can use `withNavigationFocus` https://reactnavigation.org/docs/en/with-navigation-focus.html and do some action in componentDidUpdate, or use `navigation.addListener` and do something when `didFocus` fires https://reactnavigation.org/docs/en/navigation-prop.html#addlistener-subscribe-to-updates-to-navigation-lifecycle

**Comment by brentvatne** [comment]
can continue discussion in https://github.com/react-navigation/react-navigation.github.io/issues/191
