### ISSUE TITLE
how to help bring react-navigation to 1.0

### ISSUE THREAD

**Issue by vonovak** [react-community/react-navigation#1892]
Hi! I was really excited about react-navigation when it came out. Now couple of months down the road I feel like the development speed is not where it could and should be (not very frequent commits, lots of open PRs), so I want to ask the authors ( @skevy @grabbou @satya164 and others) - are there some specific things the community can now do that will help move forward faster?

Are there some high priority issues that nobody's working on?
Do you need somebody to manage the issues where really most of them are questions (I'd volunteer)?
...

Thanks!

**Comment by MovingGifts** [comment]
I totally agree & feel the same way! Navigation is _critical_ to any app. React Native is awesome, but it feels like react-navigation is sometimes ignored compared to React Native. Why can't it be awesome too with the same level of activity and progress?

Just like FB has core team members continuously progressing React Native (along with the community), why can't they do the same with react-navigation?

**Comment by nonameolsson** [comment]
Good question! But there is already an issue with the roadmap for 1.0. I don't have the knowledge how to close those issues. [https://github.com/react-community/react-navigation/issues/723](https://github.com/react-community/react-navigation/issues/723)
But I would assume that the priority should be those mentioned in that isssue. What do you say @skevy @grabbou @satya164 ?

**Comment by matthamil** [comment]
There are plenty of ways you can help out :) You can answer questions in the Issues (currently 617 open issues) or start a conversation on the open PRs. Even if you are not a maintainer of the project, asking about decisions made in PRs helps the maintainers get a sense of what the PR is meant to do, and whether or not it should be accepted. The documentation could always be better too. Thank you for wanting to make this project better!
