### ISSUE TITLE
error:  Unhandled JS Exception: ReferneceError:   can't find variable : React

### ISSUE THREAD

**Issue by jpca999** [react-community/react-navigation#1893]
![image](https://user-images.githubusercontent.com/1026325/27205736-8e65a346-5200-11e7-958b-c38f9a9536f7.png)

Heres my whole code. 

class MyHomeScreen extends React.Component {
  static navigationOptions = {
    drawerLabel: 'Home',
    drawerIcon: ({ tintColor }) => (
      <Image
        source={require('./chat.png')}
        style={[styles.icon, {tintColor: tintColor}]}
      />
    ),
  };

  render() {
    return (
      <Button
        onPress={() => this.props.navigation.navigate('Notifications')}
        title="Go to notifications"
      />
    );
  }
}

class MyNotificationsScreen extends React.Component {
  static navigationOptions = {
    drawerLabel: 'Notifications',
    drawerIcon: ({ tintColor }) => (
      <Image
        source={require('./notify.png')}
        style={[styles.icon, {tintColor: tintColor}]}
      />
    ),
  };

  render() {
    return (
      <Button
        onPress={() => this.props.navigation.goBack()}
        title="Go back home"
      />
    );
  }
}

const styles = StyleSheet.create({
  icon: {
    width: 24,
    height: 24,
  },
});

const drawerNav = DrawerNavigator({
  Home: {
    screen: MyHomeScreen,
  },
  Notifications: {
    screen: MyNotificationsScreen,
  },
});

AppRegistry.registerComponent('drawerNav', () => drawerNav);

Package.json 

{
	"name": "drawerNav",
	"version": "0.0.1",
	"private": true,
	"scripts": {
		"start": "node node_modules/react-native/local-cli/cli.js start",
		"test": "jest"
	},
	"dependencies": {
		"react": "16.0.0-alpha.12",
		"react-native": "0.45.1",
		"react-navigation": "^1.0.0-beta.11"
	},
	"devDependencies": {
		"babel-jest": "20.0.3",
		"babel-preset-react-native": "2.0.0",
		"jest": "20.0.4",
		"react-test-renderer": "16.0.0-alpha.12"
	},
	"jest": {
		"preset": "react-native"
	}
}

environment: 
Mac latest:

**Comment by matthamil** [comment]
You are missing a line in one of your files that is referencing `React`:

```js
import React from 'react'; // should be at the top of the file using React or JSX
```

**Comment by matthamil** [comment]
Closing this issue. Please open a new issue if the above solution does not resolve your problem :)
