### ISSUE TITLE
Enabling scroll on the tab navigation with TabNavigator.

### ISSUE THREAD

**Issue by siddhism** [react-community/react-navigation#1897]
### Current Behavior
providing scrollEnabled : true in TabNavigator doesn't make the tab bar scrollable.

```
export const Tabs = TabNavigator({
    all: {
      screen: TopicsFlatList,
      navigationOptions: {
        tabBarLabel: 'Feed',
        tabBarIcon: ({ tintColor }) => <Icon name="list" size={35} color={tintColor} />,
      },
    },
    world: {
      screen: TopicsFlatList,
      navigationOptions: {
        tabBarLabel: 'world',
        tabBarIcon: ({ tintColor }) => <Icon name="account-circle" size={35} color={tintColor} />
      },
    },
    // .... more categories here
},{
  'lazy': true,
  'scrollEnabled': true,
  'tabStyle': {
      width: 60
    },
  },
);

```

### Expected Behavior
Tab bar should be scrollable.

related discussions : 
https://github.com/react-community/react-navigation/issues/86
https://github.com/react-community/react-navigation/issues/133#issuecomment-276706941

Here is how it looks 

![image](https://user-images.githubusercontent.com/6917183/27212860-ace0a188-5280-11e7-98ee-c645e37d8136.png)

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  ^1.0.0-beta.11
| react-native    | ^0.44.0 
| node             | v6.10.0
| npm or yarn      | 4.1.2

**Comment by siddhism** [comment]
needed to be passed in tabBarOptions


export const Tabs = TabNavigator({
    all: {
      screen: TopicsFlatList,
      navigationOptions: {
        tabBarLabel: 'Feed',
        tabBarIcon: ({ tintColor }) => <Icon name="list" size={35} color={tintColor} />,
      },
    },
    world: {
      screen: TopicsFlatList,
      navigationOptions: {
        tabBarLabel: 'world',
        tabBarIcon: ({ tintColor }) => <Icon name="account-circle" size={35} color={tintColor} />
      },
    },
    // ... more here

},{
  'lazy': true,
  tabBarOptions: {
    scrollEnabled: true,
    activeTintColor: '#e91e63',
  },
  // 'tabBarComponent': TabView.TabBarTop,
},
);
works now.

**Comment by xiaozhouwu** [comment]
good

**Comment by peni4142** [comment]
This does just work for me on Android. I have trouble on iOS. No scrolling tabbar.

```
export const Tabs = TabNavigator({
    Page1: {
        screen: Page1,
    },
    Page2:{
        screen: Page2,
    },
    Page3:{
        screen: Page3,
    },
    Page4:{
        screen: Page4,
    },
    Page5:{
        screen: Page5,
    },
},
    {
        swipeEnabled:false,
        animationEnabled: true,
        tabBarOptions: {
          scrollEnabled:true,
        },
})
```

**Comment by jack2684** [comment]
Same issue as @peni4142

**Comment by peni4142** [comment]
Hi this issue is closed. I recognized it late, too. But I don't know if that is realy a bug, so I didn't open an other one.

**Comment by satya164** [comment]
It's not a bug. you need to use the `TabBarTop` component on iOS if you want the scroll behavior.

**Comment by peni4142** [comment]
I edited it now, but doesn't work:

```
{
        swipeEnabled:false,
        animationEnabled: true,
        tabBarPosition: 'top',
        tabBarOptions: {
          scrollEnabled:true,
          tabStyle:{
              width: 200,
          }
        },
```

but no scrollable Tabbar on iOS

**Comment by satya164** [comment]
> **you need to use the TabBarTop component**

**Comment by anilgurindapalli** [comment]
any example on how to use TabBarTop in the code..

**Comment by peni4142** [comment]
```
 

{
        swipeEnabled:false,
        animationEnabled: true,
        tabBarPosition: 'top',
        tabBarComponent: TabBarTop,
        tabBarOptions: {
          scrollEnabled:true,
        },

```

if I run the App on Android, I get an error by clicking on a tab....


Unsupported top level event type "topScroll" dispatched
extractEvents
    C:\Users\user\App\App\node_modules\react-native\Libraries\Renderer\ReactNativeFiber-dev.js:3519:22
extractEvents
    C:\Users\user\App\App\node_modules\react-native\Libraries\Renderer\ReactNativeFiber-dev.js:3298:71
handleTopLevel
    C:\Users\user\App\App\node_modules\react-native\Libraries\Renderer\ReactNativeFiber-dev.js:3539:64
<unknown>
    C:\Users\user\App\App\node_modules\react-native\Libraries\Renderer\ReactNativeFiber-dev.js:3560:55
batchedUpdates
    C:\Users\user\App\App\node_modules\react-native\Libraries\Renderer\ReactNativeFiber-dev.js:2754:26
batchedUpdates
    C:\Users\user\App\App\node_modules\react-native\Libraries\Renderer\ReactNativeFiber-dev.js:202:35
batchedUpdatesWithControlledComponents
    C:\Users\user\App\App\node_modules\react-native\Libraries\Renderer\ReactNativeFiber-dev.js:209:34
_receiveRootNodeIDEvent
    C:\Users\user\App\App\node_modules\react-native\Libraries\Renderer\ReactNativeFiber-dev.js:3559:50
receiveEvent
    C:\Users\user\App\App\node_modules\react-native\Libraries\Renderer\ReactNativeFiber-dev.js:3564:60
__callFunction
    C:\Users\user\App\App\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:302:47
<unknown>
    C:\Users\user\App\App\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:116:26
__guard
    C:\Users\user\App\App\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:265:6
callFunctionReturnFlushedQueue
    C:\Users\user\App\App\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:115:17

**Comment by HerlanAssis** [comment]
{
        swipeEnabled:false,
        animationEnabled: true,
        tabBarPosition: 'top',
        tabBarTopComponent: props => {
        },

**Comment by mrafei** [comment]
@satya164
I want to reset the tabbar to active tab when user is scrolling in the current screen. This will help for a better user experience. Is it possible to manually scroll to a tab in tabbar? 
Thanks.

**Comment by AbdelhalimAhmed** [comment]
i publish a new article of my solution on Medium , you can see what am doning.
[https://medium.com/@abdelhalim.ahmed95/how-to-create-scrollable-and-dynamic-top-tabsbar-using-react-navigation-17ca52acbc51?fbclid=IwAR3B03f2uyvSPLDUmmMSbYdMelEZkujUJNr_yg9xpMpxtvaghg7wo9u24hc](url)
