### ISSUE TITLE
How to properly wrap a child TabNavigator in a View?

### ISSUE THREAD

**Issue by zubko** [react-community/react-navigation#1900]
### Current Behavior

https://snack.expo.io/By3fcM-7W

I have a `Drawer` as a root and one of the screens has a `TabNavigator` with 2 tabs and a common View shared for both tabs.

I can't add a common view to each tab, because it is supposed to be Android style TabNav with swipes, so it will be visible.

As you can see from the Snack the TabNav navigation is disconnected from the root navigation (I can't open drawer from it and I can't switch to a certain tab from another screen.

I wanted to link tab navigator manually with  `<TabNav navigation={navigation}/>` but when I do so I get a crash:

<img width="253" alt="screen shot 2017-06-16 at 11 42 40 am" src="https://user-images.githubusercontent.com/16039/27219379-301b9cfc-528a-11e7-8582-723cc9ece840.png">

### Expected Behavior

All links between screens work when I add `TabNavigator` directly to `Drawer`
https://snack.expo.io/BkMR8fbQb

### Your Environment
Expo SDK v16.0

**Comment by zubko** [comment]
Yay! 🎉
I was able to link the wrapper to the root navigation, by making its router to be a `TabNavigation` router. 
Like:
```
HomeWrapper.router = TabNav.router;
```
And adding `TabNav` to `HomeWrapper` with navigation now doesn't crash:
```
<TabNav navigation={this.props.navigation}/>
```
The result is here, drawer can be opened from within a tab and it's possible to link to a certain tab from a different screen:
https://snack.expo.io/SJWYZL-Qb

Now the question is:
Is this the right way of achieving that effect?

**Comment by matthamil** [comment]
This is an interesting use case of the TabNavigator's router. It appears to resolve your issue though. If you experience any issues with this approach, please open another issue. Thank you for commenting your solution to your problem :). Closing this issue.

**Comment by jordanmkoncz** [comment]
Thanks for posting your solution @zubko, I've implemented the same thing in my app so that I can conditionally show a completely different navigator than my normal TabNavigator based on the value of a property from my Redux store. It seems to be working well!
