### ISSUE TITLE
Can't show screen title in a tabNavigator app

### ISSUE THREAD

**Issue by folivi** [react-community/react-navigation#1903]
### Current Behavior
Hi all,
I started a tabbar navigation app like this:

```
const PrimaryNav = TabNavigator({
  HomeScreen: { 
    screen: HomeScreen,
    navigationOptions: { title: 'Home' }
  },
  EventsScreen: { 
    screen: EventsScreen,
    navigationOptions: { title: 'Events' }
  },
  CommunityScreen: { 
    screen: CommunityScreen,
    navigationOptions: { title: 'Community' } 
  },
  ProfileScreen: { 
    screen: ProfileScreen,
    navigationOptions: { title: 'Profile' }
  }
}, {
  
  initialRouteName: 'HomeScreen',
  swipeEnabled: false,
  animationEnabled: false,
  tabBarOptions: {
     
    activeTintColor: '#e91e63',
    labelStyle: {
      fontSize: 12,
    },
  }
})
```
In one of the screens I put this:
```

static navigationOptions = {
    title: 'Title',
  };


```
But the navigationBar doesn't show so the title neither.

### Expected Behavior
Show 'Title' in the screen current screen navigation bar
### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.7
| react-native     |  0.42.3
| node             | 7.10
| npm or yarn      | 3

**Comment by rankun203** [comment]
For those navigated to here, this is possibly a duplicate of #741
