### ISSUE TITLE
[Question] Block closing app on Android with Back Button

### ISSUE THREAD

**Issue by bennygenel** [react-community/react-navigation#1904]
### Current Behavior
App closes down if no more routes to back down.

### Expected Behavior
I'm having some problem on Android with the navigation. I explained it [here](https://github.com/react-community/react-navigation/issues/1805).
So as a temporary solution I want to block closing app with the hardware back button.

I tried to use `getStateForAction` to block router going back but it doesn't work.

```
const defaultGetStateForAction = InitialNavigation.router.getStateForAction;
const defaultGetComponentForState = InitialNavigation.router.getComponentForState;

InitialNavigation.router.getStateForAction = (action, state) => {
  if(state != null){
    let prevComponent = defaultGetComponentForState(state);
    console.log(prevComponent.name);
    if(action.type === NavigationActions.BACK && prevComponent.name === 'InitialScreen'){
      console.log('Block app closing!');
      return null;
    }
  }
  return defaultGetStateForAction(action, state);
};

```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  "^1.0.0-beta.11"
| react-native     |  "0.44.0"
| Android     | 7.1.1 & 6.0.1

**Comment by matthamil** [comment]
You will need to change the `if(action.type === NavigationActions.BACK` line to:

```js
  // Do not allow to go back from InitialScreen
  if (action.type === 'Navigation/BACK' && state && state.routes[state.index].routeName === 'InitialScreen') {
    return null;
  }
```

This is what I use in my app to resolve this issue:

```js
const prevGetStateForAction = RootNavigator.router.getStateForAction;

RootNavigator.router.getStateForAction = (action, state) => {
  // Do not allow to go back from Home
  // Prevent the user from going back to the login screen after logging in
  if (action.type === 'Navigation/BACK' && state && state.routes[state.index].routeName === 'HomeStack') {
    return null;
  }

  // Do not allow to go back from Login
  if (action.type === 'Navigation/BACK' && state && state.routes[state.index].routeName === 'LogIn') {
    return null;
  }

  // Do not allow to go back to Login
  // Unless the user is on the Register screen
  if (action.type === 'Navigation/BACK' && state && state.routes[state.index].routeName !== 'Register') {
    const newRoutes = state.routes.filter(r => r.routeName !== 'LogIn');
    const newIndex = newRoutes.length - 1;
    return prevGetStateForAction(action, { index: newIndex, routes: newRoutes });
  }
  return prevGetStateForAction(action, state);
};
```

**Comment by bennygenel** [comment]
Hi @matthamil 
Thanks for your help but it didn't work either. 

`state.routes[state.index].routeName` and `prevComponent.name` gives different results in my code. I guess its because of my navigation stack.

The problem is that with my code I can see that the console logs the line I inserted so I guess `return null` is not doing anything.

In [here](https://github.com/react-community/react-navigation/issues/1805#issuecomment-308965346) you can see why I'm trying to do this and basic stack of my navigation.

I would really appreciate if you help me about this situation.

Thanks again.

**Comment by thiagonsilva** [comment]
Oi @bennygenel 

When returning null you keep the state equal to the previous one and if this state to equal the app closes, to avoid this behavior use "return Object.assign ({}, state);", then it will return a same state with however in a new Object, this prevents the screen from returning and the app closes.
