### ISSUE TITLE
Open Stack over Tabs on tab click

### ISSUE THREAD

**Issue by AlexeySmolyakov** [react-community/react-navigation#1906]
### The goal
According to this sample code [StacksOverTabs.js](https://github.com/react-community/react-navigation/blob/master/examples/NavigationPlayground/js/StacksOverTabs.js) react-navigation can open StackNavigator over TabNavigator hiding tabs. And this is preferred behavior. But you have to click a button inside tab screen in order to open stack screen using `navigation.navigate('NotifSettings')`.

The main goal is to open screen as stack on tab click.

### The goal behavior
Tabs:
| **Home** | **Companies** | **Camera** | **Achievements** | **Profile** |

Click on **Camera** tab will open new stack screen (with camera) over tabs.

### Issues
#586 Open screens from a single StackNavigator over current tab
This issue uses the same mechanism as [StacksOverTabs.js](https://github.com/react-community/react-navigation/blob/master/examples/NavigationPlayground/js/StacksOverTabs.js).

TIA, Alex!

### Your Environment
| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.11
| react-native     |  0.45
| node             | 8.0.0
| yarn      | 0.24.6

**Comment by matthamil** [comment]
Are you wanting to hide the tab bar on a specific tab screen? 

For the Camera screen component:

```js
static navigationOptions = () => ({
  tabBarVisible: false
});
```

This will hide the tab bar.

**Comment by AlexeySmolyakov** [comment]
Yes, sure it can hide tabs, but the reason, I want to open Camera in stack, is that it won`t be active when I leave this tab.

**Comment by pj0579** [comment]
@AlexeySmolyakov  have you  resolve it

**Comment by AlexeySmolyakov** [comment]
@pj0579 I used [react-native-scrollable-tab-view](https://github.com/skv-headless/react-native-scrollable-tab-view) with react-navigation.

```
StackNavigator
-|-
ScrollableTabView | Level2Screen1 | Level2Screen2 ...
```

From screens in tabs in ScrollableTabView you can navigate to Level2Screen1, Level2Screen2 ..., overlaying tabs.
And you can detect when user navigate to certain tab in react-native-scrollable-tab-view.

**Comment by pj0579** [comment]
@AlexeySmolyakov   thx
