### ISSUE TITLE
Most stable version of react-navigation for react-native 0.39

### ISSUE THREAD

**Issue by PrimeLens** [react-community/react-navigation#1907]
I've inherited a legacy 0.39 app. 
What is the highest react-navigation version that I can use?
Where would the list of npm releases for react-navigation be?
Thanks!

**Comment by prontiol** [comment]
I believe legacy react-navigation releases are too unstable to use them in production.

**Comment by PrimeLens** [comment]
At what release was this considered stable? @prontiol 
Also is there a list of the releases? Thank you

**Comment by prontiol** [comment]
[List of releases](https://github.com/react-community/react-navigation/releases)
I don't think any of the released versions can be considered production ready yet.

**Comment by PrimeLens** [comment]
Thanks
