### ISSUE TITLE
Consecutive setParams on different views causes unexpected results

### ISSUE THREAD

**Issue by fernandofranca** [react-community/react-navigation#1912]
| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.11
| react-native     |  0.44.2
| node             | v7.8.0
| npm or yarn      | 0.17.9

### Current Behavior
I have two views, each one is a TabNavigator tab.
Each view calls `this.props.navigation.setParams` on componentWillMount.
Only the second view navigation have `navigation.state.params` set. The first will not be defined.
If I delay the second `setParams` using a `setTimeout`, both navigators will have distinct and correct `navigation.state.params`

### Expected Behavior
Both view navigators should have parameters set on `navigation.state.params`.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  
| react-native     |  
| node             | 
| npm or yarn      |

### Example

```
class TabA extends React.Component {
  static navigationOptions = ({ navigation }) => {
    return {
      headerRight: (
        <View style={{flexDirection: 'row'}}>
          <Button 
            onPress={()=>{
              console.log(navigation.state.params, "A <<<")
            }} />
        </View>
      ),
    }
  };

  constructor(props) {
    super(props);
  }

  componentWillMount() {
    this.props.navigation.setParams({foo: 'bar'});
  }
}


class TabB extends React.Component {
  static navigationOptions = ({ navigation }) => {
    return {
      headerRight: (
        <View style={{flexDirection: 'row'}}>
          <Button 
            onPress={()=>{
              console.log(navigation.state.params, "B <<<")
            }} />
        </View>
      ),
    }
  };

  constructor(props) {
    super(props);
  }

  componentWillMount() {
    setTimeout(() => {
      this.props.navigation.setParams({foo: 'bar'});
    }, 1000)
  }
}
```

**Comment by elizamaria** [comment]
+ 1

**Comment by tedpark** [comment]
+1 same issue.
  some trick "setTimeout" set 0 second.
================================================================
 componentDidMount() {
    setTimeout(this.setParam, 0);
  }

  setParam = () => {
    this.props.navigation.setParams({
      setModalVisible: this.setModalVisible,
      modalViewVisible: !this.state.modalViewVisible
    });

    console.log(this.props.navigation);
  };

**Comment by Pollizzio** [comment]
beta 15 same issue

**Comment by kelset** [comment]
Closing in favor of https://github.com/react-community/react-navigation/issues/2931
