### ISSUE TITLE
help with using iOS tab bar in Android

### ISSUE THREAD

**Issue by garan82** [react-community/react-navigation#1916]
I'm trying to use iOS tab bar in the main screen regardless of mobile OS, here is the complete code as in create-react-native app https://pastebin.com/8CGTX40G

I did set tabBarComponent, tabBarPosition, animationEnabled, swipeEnabled and use sample tabBarOptions for TabBarBottom from https://github.com/react-community/react-navigation/blob/master/docs/api/navigators/TabNavigator.md

The app comes up as blank white when loaded in expo app in Android, I dont have iOS to test but I assume it would be the same result. Can you find what's wrong with my implementation? Thanks.

**Comment by Babazon** [comment]
same problem, using redux nav reducer for RN: blank screens on android and clicking tab bar icons/labels do nothing (redux actions are still dispatched)

**Comment by garan82** [comment]
I do have both swipeEnabled & animationEnabled set to false :(

**Comment by bennygenel** [comment]
Hi;
 Did you try returning just the Navigation itself not in a view?

```
export default class App extends React.Component {
  render() {
    return (
        <MainScreenNavigator />
    );
  }
}
```

**Comment by garan82** [comment]
That works, thank you so much. Now I need to fix the style.

**Comment by matthamil** [comment]
Closing this issue as it appears your problem was resolved by bennygenel. 👍
