### ISSUE TITLE
ScrollView and nested tabs swiping don't work properly in TabNavigator

### ISSUE THREAD

**Issue by 2rajpx** [react-community/react-navigation#1917]
### Current Behavior
This is the structure of my application:
- Drawer: `DrawerNavigator`
  - Wrapper: `StackNavigator`
    - Main: `TabNavigator` (initialRouteName in Wrapper)
      - Home: Screen (First tab and initialRouteName in Main)
      - Redeem: `TabNavigator` (Second tab)
        - Store: Screen (First nested tab)
        - Transactions: Screen (Second nested tab)
      - Invite: Screen (Last tab)
    - Profile: Screen (Accessible from drawer)
    - Contact: Screen (Accessible from drawer)

I'm using a `ScrollView` in `Home` screen. But this happens:
![rnnazarbazar-home](https://user-images.githubusercontent.com/19687157/27253921-fec5718c-5392-11e7-9abd-7070db039654.gif)
##### Content of `Home` screen doesn't hide on other tabs.
And when I change `initialRouteName` to `Redeem` this happens:
![rnnazarbazar-redeem](https://user-images.githubusercontent.com/19687157/27254013-a600e674-5394-11e7-8b7b-91728634844d.gif)
##### Previous problem is fixed but it makes another problem in nested tabs swiping
And finally when I change `initialRouteName` to `Invite` everything are fixed:
![rnnazarbazar-invite](https://user-images.githubusercontent.com/19687157/27254299-f01eac04-539a-11e7-8c13-c8c9b16987f2.gif)

### Expected Behavior
- When initial route has `ScrollView`, the contents of `ScrollView` shouldn't be remain on other tabs
- Nested tabs swiping should work properly, when their parent tab is initial route

### Your Environment
| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.11
| react-native     | 0.44.0
| node             | v7.8.0
| npm or yarn      | yarn v0.24.5

**Comment by 2rajpx** [comment]
After 4 days finally I fixed this bug in my application. I changed TabNavigator route config to:
```
{
  ...
  initialRouteName: 'Home',
  order: ['Invite', 'Redeem', 'Home'],
}
```
instead of
```
{
  ...
  initialRouteName: 'Home',
  order: ['Home', 'Redeem', 'Invite'],
}
```

**Comment by ganisback** [comment]
+1

**Comment by kelset** [comment]
Closing since OP @2rajpx fixed it himself.
