### ISSUE TITLE
How can i jump to diffent Tab from diffrent  Stack with no headerBack

### ISSUE THREAD

**Issue by ray0324** [react-community/react-navigation#1918]
In the case 'Stacks Over Tabs', 
I'm now in 'Root' stack, 'MainTab' , I press the 'Open profile screen' button, jump into 'Profile' Stack,
then I want going to 'SettingsTab' in 'Root' stack ,How can i navigate to the 'SettingsTab'  with no history?(with no headerBack )
and then i press the 'MainTab' button,  how can i go to homepage of main tab with no headerBack button?

**Comment by jcaspian** [comment]
If you're trying to `go back` using a custom button, you can try calling `this.props.navigation.goBack()` in your Screen component.

**Comment by ray0324** [comment]
@jcaspian  yes, but i still don't konw how to use reset action
