### ISSUE TITLE
Does the navigation animation get inherited?

### ISSUE THREAD

**Issue by l3wi** [react-community/react-navigation#192]
I've nested the Stack Navigator inside of a Drawer navigator. While navigating the stack I've found the transitions 'non-existent'. Even with StackNavigatorConfig mode set to card. 

However, I assume the animation is that of the drawer navigator, as it just replaces the screen and animates the drawer. So when navigating screens without the drawer, it looks like no animation is occuring.

See this gif:
![Gif explaining showing the issue](http://i.giphy.com/d3mlBmbH7Di5kqkg.gif)

1. Can some one confirm this for me?
2. Is it possible to force the StackNavigator animations to occur?

**Comment by satya164** [comment]
Can you try the master branch and lemme know if it's still an issue?

**Comment by l3wi** [comment]
Just pulled from the repo and issue still persisting. 

Here is my code setting up the Navigators:
``` javascript 
const ChatsNavigator = StackNavigator({
  Chats: {
    path: '/chats',
    screen: Chats,
  },
  Chat: {
    path: 'chat/:chatId',
    screen: Chat,
  },
}, {
  initialRouteName: 'Chats',
  headerMode: 'none',
  mode: 'card',
});

// Impliment Navigation
const Application = DrawerNavigator({
  ChatsNav: {
    screen: ChatsNavigator,
  },
  Settings: {
    path: '/settings',
    screen: Settings,
  },
}, {
  initialRouteName: 'ChatsNav',
  navigationOptions: {
     header: {
       visible: false,
     },
   },
}); 
```

**Comment by l3wi** [comment]
Solved the problem. 

I was running RN 0.40.0, when I updated to 0.41.0 as a fix to another issue I was debugging. This solved the animations issues now it's working as described.

Here is the current view:
![Updated view](http://i.giphy.com/26xBSNCDt1BX1R8pa.gif)
