### ISSUE TITLE
Keyboard hidden TextInput when changing `android/app/src/main/res/values/styles.xml`

### ISSUE THREAD

**Issue by zphhhhh** [react-community/react-navigation#1921]
### Current Behavior
To let the statusBar be transparent in Android, I add the code to `/android/app/src/main/res/values/styles.xml` that is :
```
<resources>
    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <!-- Customize your theme here. -->
        <item name="android:windowTranslucentStatus">true</item>
        <item name="android:windowTranslucentNavigation">true</item>
    </style>
</resources>
```
But then in React Native , Keyboard hidden the `TextInput` when focus.
Before adding that `transparent` codes, the `TextInput` is normal.

### Expected Behavior
Even adding that `transparent` codes, the `TextInput` should be normal anytime.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.11
| react-native     |  0.45.1
| node             | 7.10.0
| npm      |  4.2.0

**Comment by matthamil** [comment]
I'm not sure if this is an issue related to React Navigation. Is this an issue with React Native or this library? If this is an issue with React Native, you can [open an issue](https://github.com/facebook/react-native/issues) on the React Native repo.

**Comment by matthamil** [comment]
Closing this issue. If you believe that this is an issue with [React Navigation](https://reactnavigation.org/) and not React Native, please reopen another issue with more details about the problem you are experiencing.
