### ISSUE TITLE
Parent state changing but not updating child state via screenprops

### ISSUE THREAD

**Issue by VietDucPhan** [react-community/react-navigation#1923]
I am having problem to passing the state in the parent to child using screenprops. All is ok until i want to change the state in the parent and it does not update in the child. My code is like this:
```javascript
import { StackNavigator, TabNavigator } from 'react-navigation';

const Tabs  = TabNavigator({
    profile : { screen: profile }
});

export default class App extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            user:null
        };
    }
    _signIn(){
        this.setState({user:true})
    }

    render(){
       var self = this;
        return(
        <Tabs screenProps={{
             user:this.state.user,
            signIn:self._signIn.bind(this)
          }} />
       );
        
    }
}

class profile extends Component {
  constructor(props){
    super(props);
    var self = this;
    this.state = {
      user:this.props.screenProps.user,
      
    };
  }
  render(){
     return(
       <button onPress={()=>self.props.screenProps.signIn()} />
     );
  }
}
```
I have check the state in the parent it does change but somehow it is not reflected to the child.

Anyone have any idea how to fix this problem? or passing props to child that updated along with parent state?

**Comment by jcaspian** [comment]
You are setting the `user` state in the constructor, which will only be called once during mounting.
Unless you are re-mounting it, it will not update the `state`.

The child should also not receive the `user` from the parent as a `state` of its own.

> State is reserved only for interactivity, that is, data that changes over time.

> Neither parent nor child components can know if a certain component is stateful or stateless, and they shouldn't care whether it is defined as a function or a class.

> This is why state is often called local or encapsulated. It is not accessible to any component other than the one that owns and sets it.

-quoted from react docs

Do go through the sections here to better understand when to use state & props:
https://facebook.github.io/react/docs/thinking-in-react.html#a-brief-interlude-props-vs-state
https://facebook.github.io/react/docs/state-and-lifecycle.html#the-data-flows-down

Your code can be something like this:

```jsx
class Profile extends Component {
  render() {
    const { screenProps } = this.props
    
    if (screenProps.user) {
      return (
        <div>Welcome!</div>
      )
    }
    
    return (
      <button onPress={() => screenProps.signIn()}>
        Sign In
      </button>
    )
  }
}
```

If `Profile` is a stateless component, we can even write a shorter one:

```jsx
const Profile = ({ screenProps }) => {
  if (screenProps.user) {
    return <div>Welcome!</div>
  }
  return <button onPress={() => screenProps.signIn()}>Sign In</button>
}
```

**Comment by VietDucPhan** [comment]
@jcaspian Thanks for the tips. However, My problem is that the screenProps.user will not updating the state.user from the parent. I have used your method before it not working.

**Comment by jcaspian** [comment]
Just as the first sentence of my previous reply, you are setting the `state` in the child's constructor.
You **should not** do that, as parent should only set the `props` of it's children.

Constructor is called during the **initialization and construction**.
Parent updating the child's state or props, **doesn't re-initialize nor re-construct** the child.

Data going down the tree: use `props`;
Data going up the tree: use `state`, parent's setState.

**Comment by VietDucPhan** [comment]
@jcaspian Noted, Much appriciation.

**Comment by bologer** [comment]
@jcaspian is is possible to make this: 

```js
const Profile = ({ screenProps }) => {
  if (screenProps.user) {
    return <div>Welcome!</div>
  }
  return <button onPress={() => screenProps.signIn()}>Sign In</button>
}
```

as a `class` instead of `cosnt`? 

For example if I would like to extend another class for the component.

**Comment by jcaspian** [comment]
@bologer Yes of course. Check out the first code snippet in https://github.com/react-navigation/react-navigation/issues/1923#issuecomment-309276907 where I was using class for the Profile screen/component.
