### ISSUE TITLE
How to refresh current screen when onPress

### ISSUE THREAD

**Issue by boyinfotronics** [react-community/react-navigation#1924]
How to refresh current screen when onPress anyone have example ? thank you

**Comment by jcaspian** [comment]
What do you mean by refreshing current screen?
Re-rendering it or fetching new data and then re-render it?

You could simply set a different state to re-render the screen.

```jsx
class MyScreen extends Component {
  constructor(props) {
    super(props)
    
    this.state = {
      lastRefresh: Date(Date.now()).toString(),
    }
    
    this.refreshScreen = this.refreshScreen.bind(this)
  }
  
  refreshScreen() {
    this.setState({ lastRefresh: Date(Date.now()).toString() })
  }
  
  render() {
    return (
      <View>
        <Text>My Screen</Text>
        <Text>Last Refresh: {this.state.lastRefresh}</Text>
        <Button onPress={this.refreshScreen} title="Refresh Screen" />
      </View>
    )
  }
}
```

**Comment by sirilicious** [comment]
@jcaspian your example is helpful, but i want to accomplish a refresh when "reselecting" an already selected tab.

**Comment by tnguyenblurb** [comment]
@sirilicious you need to understand more how a component re-rendering, just update the state, any components related to that state will be refresh/re-rendering.

**Comment by JooseNavarro** [comment]
Perfect friend!!!

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!

**Comment by BinMansoor11** [comment]
> What do you mean by refreshing current screen?
> Re-rendering it or fetching new data and then re-render it?
> 
> You could simply set a different state to re-render the screen.
> 
> ```js-jsx
> class MyScreen extends Component {
>   constructor(props) {
>     super(props)
>     
>     this.state = {
>       lastRefresh: Date(Date.now()).toString(),
>     }
>     
>     this.refreshScreen = this.refreshScreen.bind(this)
>   }
>   
>   refreshScreen() {
>     this.setState({ lastRefresh: Date(Date.now()).toString() })
>   }
>   
>   render() {
>     return (
>       <View>
>         <Text>My Screen</Text>
>         <Text>Last Refresh: {this.state.lastRefresh}</Text>
>         <Button onPress={this.refreshScreen} title="Refresh Screen" />
>       </View>
>     )
>   }
> }
> 
that was really helpful. my problem is solved after hours of brainstorming.
