### ISSUE TITLE
Cannot swipe in TabNavigator on iOS

### ISSUE THREAD

**Issue by Cretezy** [react-community/react-navigation#1926]
### Current Behavior
I cannot swipe left/right on the TabNavigator on iOS. It does work on Android.

### Expected Behavior
I expect it to swipe between tabs. I must use the tab bar now.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.11
| react-native     |  0.45.1

**Comment by matthamil** [comment]
Can you post the code showing your navigation structure and your [tabNavigatorConfig](https://reactnavigation.org/docs/navigators/tab#TabNavigatorConfig)?

**Comment by Cretezy** [comment]
Sorry, I figured it out.

The `swipeEnabled` is false on iOS by default. Had to force it to true.
