### ISSUE TITLE
Question. Is it possible to change the drawer background color?

### ISSUE THREAD

**Issue by diz00** [react-community/react-navigation#1927]
I know we can customize the styles of contents, but can we actually change the bg color of the container?

**Comment by matthamil** [comment]
You should be able to wrap the `DrawerItems` component from React Navigation with a `View` that is styled however you want. See the example [here](https://reactnavigation.org/docs/navigators/drawer#Providing-a-custom-contentComponent).

**Comment by Shhzdmrz** [comment]
I am new to react native and react navigation but what I found is just pass background color to the component of the react navigation. e.g.
`const MainNavigator = DrawerNavigator({
                           ... 
});

render(){
     return(
        <MainNavigator style={{backgroundColor: '#437F82'}} />
    );
}`

PS: Its working on my side.

**Comment by tuananh11594** [comment]
drawerOpenRoute: "DrawerOpen",
    drawerCloseRoute: "DrawerClose",
    drawerToggleRoute: "DrawerToggle",
    drawerBackgroundColor: "black",
makes it work.
