### ISSUE TITLE
LayoutAnimation on TabNavigator has some problems when its props 'lazy' is true

### ISSUE THREAD

**Issue by XboxYan** [react-community/react-navigation#1930]
### Current Behavior

In TabNavigator when set its props 'lazy=true', LayoutAnimation in  sceneview has some problems,it look like animation run a half

### Only in initialRoute

it's in a TabNavigator
```
const Root = TabNavigator({
    Home: { screen: Home },
    Movie: { screen: Movie },
    Live: { screen: Live },
    Me: { screen: Me },
},TabNavigatorConfig);

```
some codes in Home
```javascript

componentDidMount() {
        fetchData('index',{},
            (data)=>{
                this.data = data.body;
                this.isRender = true;
                LayoutAnimation.easeInEaseOut();
            }
        )
    }

```
#### result
![image](https://user-images.githubusercontent.com/19424274/27268131-24e1014e-54e0-11e7-8801-e194bfe13806.png)

### Expected Behavior

when I delete the layoutAnimation or set lazy to false,it is normal
![image](https://user-images.githubusercontent.com/19424274/27268071-affd1c82-54df-11e7-8cb6-72640333bf84.png)

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.11
| react-native     |  0.44.3
| node             | 
| npm or yarn      |

**Comment by matthamil** [comment]
Can you record a video showing the problem? Can you also provide more of the code that you think is causing this issue?

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
