### ISSUE TITLE
Cannot read property 'screenProps' of undefined

### ISSUE THREAD

**Issue by marcelocbf** [react-community/react-navigation#1931]
Hi,

I'm trying to use React Navigation on a React Native app, without success. I have no clue why I'm getting this error. Trying to debug I brought the app to its minimum but it still gives me the error. It looks like is a problem with my setup as I follow tutorial, docs and read the code multiple times and still can't figure out why. Maybe someone can give me an idea of how to debug it.

Here is the complete code
```
class Start extends React.Component {

  render() {
    return(
      <View><Text>Debug</Text></View>
    )
  }

}

const MyApp = StackNavigator(
  {
    Home: {
      screen: Start
    }
  }
)

export default MyApp;

```
Here is my package.json

```
{
  "name": "MyApp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "babel-node ./server.js",
    "update-schema": "babel-node ./scripts/updateSchema.js"
  },
  "dependencies": {
    "aws-sdk": "2.72.0",
    "babel-preset-react-native": "1.9.0",
    "babel-relay-plugin": "0.10.0",
    "graphql": "0.7.2",
    "graphql-relay": "0.4.4",
    "native-base": "2.1.0",
    "react": "15.4.2",
    "react-native": "0.40.0",
    "react-native-aws-cognito-js": "0.0.5",
    "react-native-aws-signature": "0.0.9",
    "react-native-easy-grid": "^0.1.13",
    "react-native-localization": "0.1.30",
    "react-navigation": "1.0.0-beta.11",
    "react-relay": "0.10.0"
  },
  "devDependencies": {
    "babel-cli": "6.9.0",
    "babel-core": "6.9.1"
  },
  "engines": {
    "npm": ">=3"
  }
}

```
Node v6.9.2
NPM 4.0.3

The code is actually a lot bigger and I tried to use all different ways to return the component, adding screenProps to the Navigator, navigationOptions, etc. but even with the simplest case, it does not work. I've already deleted my whole node_modules folder and re-installed 3 times but no luck

Here is the error
![screen shot 2017-06-18 at 10 09 20 pm](https://user-images.githubusercontent.com/2860079/27269194-c104d75c-5482-11e7-97cf-fa1f4a53ab68.png)

I appreciate any help to find out what is going on...

**Comment by jcaspian** [comment]
I don't know how are you passing the `screenProps` from your code but the minimal setup should be something like this:

```jsx
import React, { Component } from 'react'
import { AppRegistry, Button, Text, View } from 'react-native'
import { StackNavigator } from 'react-navigation'

class HomeScreen extends Component {
  render() {
    const { navigation, screenProps } = this.props
    
    return (
      <View>
        <Text>Welcome, {screenProps.user.name}!</Text>
        <Button onPress={() => navigation.navigate('Profile')} title="Go to Profile" />
      </View>
    )
  }
}

class ProfileScreen extends Component {
  render() {
    const { navigation, screenProps } = this.props
    
    return (
      <View>
        <Text>My Profile</Text>
        <Text>Name: {screenProps.user.name}</Text>
        <Text>Username: {screenProps.user.username}</Text>
        <Text>Email: {screenProps.user.email}</Text>
        <Button onPress={() => navigation.goBack()} title="Back to Home" />
      </View>
    )
  }
}

const AppNavigator = StackNavigator({
  Home: { screen: HomeScreen },
  Profile: { screen: ProfileScreen },
})

class MyApp extends Component {
  render() {
    const screenProps = {
      user: {
        name: 'John Doe',
        username: 'johndoe123',
        email: 'john@doe.com',
      },
    }
    
    return (
      <AppNavigator screenProps={screenProps} />
    )
  }
}

export default MyApp

AppRegistry.registerComponent('MyApp', () => MyApp);
```

`HomeScreen` and `ProfileScreen` are components defined as screens for `AppNavigator`. 
In the example above, I am passing the `user` data from the top-level, root component `MyApp` to both `HomeScreen` and `ProfileScreen`.

Since there is a `AppNavigator` between `MyApp` and the screen components, we will need to pass the `user` to `screenProps` prop of `AppNavigator`, so that the `AppNavigator` will pass it down to the screens. Any other prop except `screenProps` will not be passed down.

```
MyApp <-- user data here
- AppNavigator <-- the StackNavigator, the middle man. must use screenProps to pass user data down
  + HomeScreen <-- will receive user data from this.props.screenProps.user instead of this.props.user
  + ProfileScreen <-- same as HomeScreen
```

**Comment by marcelocbf** [comment]
Hey @jcaspian Thanks for taking the time and for the nice formatted answer.

I copied your example but still getting the same error. That's the reason I think it might be something with this installation or some kind of incompatibility with another library I have in my package.json? Maybe?

The code I posted before was the complete code I was using to debug (besides the .registerComponent that is by itself in another file) I'm not using screenProps at all. I did try to use it once while debugging thinking that it might help the Options Object not to be undefined, but no help, so I reverted back. Very Strange.

I don't know what else to do as I have already deleted node_modules more than once and rebooted the machine many times...

Thanks anyway,

**Comment by marcelocbf** [comment]
Hi again, trying to debug on a physical device and not attached to the Chrome Remote Debugger, I receive a slightly different message, that it looks like it is coming from CardStackTransitioner.js from the lib folder not lib-rn folder (Hint: _this$props). Now I'm wondering how the library makes this selection of the platform, maybe my installation has something that is causing this mess and it can help me debug ...

![screenshot_20170619-232932](https://user-images.githubusercontent.com/2860079/27315510-f7b1bffc-5547-11e7-9e21-37c5e4db1ae8.png)

**Comment by matthamil** [comment]
@marcelocbf Are you locked into React Native version `0.40.0`? Can you reproduce this on v0.41 or greater?

**Comment by marcelocbf** [comment]
Hey @matthamil I didn't want to upgrade because I do have a lot of packages using React 15ish and RN 0.44 is using 16 Alpha, I removed some during the debug process. I did upgrade and it worked ... Strange! But I'm happy it's finally working! Now I'll see what I can do to upgrade the other packages.

Thanks for pitching in!

**Comment by quocthinh26091998** [comment]
Hello @marcelocbf. how did you stop the undefined is not object error. I'm currently using React-Native "0.61.5" but I still stumble that annoying error. Could you pls tell me more of the things u did to solve it.
Thank you so much.
