### ISSUE TITLE
Passing props to nested components

### ISSUE THREAD

**Issue by cipriancaba** [react-community/react-navigation#1932]
### Current Behavior
I am trying to pass some props to the nested `WelcomeScreen` and `AddProjectScreen`. The only solution I found until now was to pass along the custom `screenProps`. However, this imposes a dependency on the nested components (`Welcome`, `AddProject`) on the `screenProps` property
 
```
const RootNavigator = StackNavigator({
  Welcome: { screen: WelcomeScreen },
  AddProject: { screen: AddProjectScreen }
})

class ConnectedRootNavigator extends Component {
  render() {
    return <RootNavigator screenProps={this.props} />
  }
}

export default connect(mapStateToProps, mapDispatchToProps)(
  ConnectedRootNavigator
)
```

### Expected Behavior
Right now, the props are being passed to the `ConnectedRootNavigator`, but are not passed to the nested components
I would like to be able to pass props without the use of screenProps so I can normally access them in my nested components via `this.props`. Is this achievable?

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.11
| react-native     |  0.44.3
| node             | v8.0.0
| npm or yarn      | yarn

**Comment by matthamil** [comment]
Is there any reason why you don't want to connect a different component with redux?

**Comment by cipriancaba** [comment]
Initially, I connected the `StackNavigator`, but the props were available inside the `StackNavigator` component, but not passed to the `WelcomeScreen` and `AddProjectScreen`

**Comment by matthamil** [comment]
Correct, StackNavigators do not pass down props to their screen components. You will have to either use `screenProps` like you first thought, or what I recommend, connecting the `screen` components instead of connecting the StackNavigator itself unless you absolutely _need_ to connect the navigator.

**Comment by cipriancaba** [comment]
That's very useful, thank you very much.. Don't know why I haven't considered the option to connect all the screens in the first place

**Comment by imyoka** [comment]
@cipriancaba  what if you considered the option to connect all the screens in the first place? Is there any gist to show.I'm learning to pass props to nested components with the same confusion. Thank you~

**Comment by imyoka** [comment]
@matthamil how to achieve connecting the screen components instead of connecting the StackNavigator itself unless you absolutely need to connect the navigator. Is it like below inside WelcomeScreen?
``` javascript
@connect(
  state => ({
    // counter: state.counter
  }),
  dispatch => bindActionCreators(WelcomeActions, dispatch)
)
```
Or the other gists?

**Comment by matthamil** [comment]
@imyoka Can you open a new issue detailing the problem you are describing?

**Comment by barakoles** [comment]
I'm facing the same problem fml
