### ISSUE TITLE
How to setState befor render view?

### ISSUE THREAD

**Issue by sihitejulio** [react-community/react-navigation#1935]
I can setState in `componentDidMount` or `componentWillMount `from `asycnStorage`, how to initial before render?

**Comment by jcaspian** [comment]
Please give us a sample mock up code to better understand what you're trying to achieve.
This doesn't seemed like a react-navigation related issue though.

**Comment by matthamil** [comment]
As jcaspian said, I don't believe this is a react navigation issue. Please refer to [StackOverflow](https://stackoverflow.com/) or join the [Reactiflux](https://www.reactiflux.com/) community on Discord.

Here is my attempt to understand your question:

```js
class MyComponent extends React.Component {
  constructor(props) {
    this.state = { loaded: false };
  }
  componentDidMount() {
    AsyncStorage.getItem('myKey', (result) => this.setState({ loaded: true }));
  }

  render() {
    return this.state.loaded ? <WhatINormallyRender> : <LoadingScreen>;
  }
}
```

**Comment by matthamil** [comment]
I'm going to close this issue since I do not believe this is related to React Navigation. Feel free to check out the resources I mentioned in my comment above. If you are continuing to experience an issue related to React Navigation, please open another issue :)
