### ISSUE TITLE
Resetting stack shows an older page in stack for a split second.

### ISSUE THREAD

**Issue by Raktima** [react-community/react-navigation#1938]
I have the following stack navigation set up:

`const Routes = StackNavigator({
  	Login: { screen: Login },
	Main:{screen:Main}
},
{
	headerMode:'none'
})`

`const Main=StackNavigator({
PhoneInputPage: { screen: PhoneInputPage },
OTP:{screen:OTP}
})`

when I am in my Routes stack and I reset my stack to point to the Main stack I see the Login screen briefly in Android.  It doesn't look appealing at all. How do I solve this?

**Comment by tmaly1980** [comment]
Do you have some example code of resetting your stack?

**Comment by Raktima** [comment]
` const resetAction = NavigationActions.reset({
      index: 0,
      actions: [NavigationActions.navigate({ routeName: 'Main' })]});`


` this.props.navigation.dispatch(resetAction);   `

**Comment by matwii** [comment]
I have the exact same problem and need help aswell.

**Comment by JulianKingman** [comment]
Related: https://github.com/react-community/react-navigation/issues/2084

**Comment by nickpleis** [comment]
I have this same problem. I'm attempting to reset from a nested navigator. It briefly shows the bottom screen before properly navigating to the dispatch target.

**Comment by javidjamae** [comment]
Similar issue here.. I have a Stacks over Tabs setup. 

```
const MainTabNavigator = TabNavigator( {
  connectionList: { screen: ConnectionListNavigator },
  addConnectionMain: {  screen: AddConnectionNavigator    },
  drafts: { screen: DraftsNavigator },
  settings: { screen: SettingsNavigator },
} )

const MainNavigator = StackNavigator( {
  root: { screen: MainTabNavigator },
  addConnectionViaSms: { screen: AddConnectionViaSmsScreen },
  addConnectionViaEmail: { screen: AddConnectionViaEmailScreen },
  addConnectionDetails: { screen: AddConnectionDetailsScreen }
}, {
  mode: 'modal'
} )
```

I navigate from addConnectionMain -> addConnectionViaSms -> addConnectionDetails then after a form is submitted on that page, I do a reset back to connectionList. 

```
      const resetAction = NavigationActions.reset( {
        index: 0,
        actions: [
          NavigationActions.navigate( { routeName: 'root' } )
        ]
      } )
      await navigation.dispatch( resetAction )
```

When I do the reset, it distinctly  navigates be back through each route: addConnectionViaSms -> addConnectionMain -> connectionList. 

Sometimes it's fairly slow (especially on the iOS simulator) and actually hangs on one or two of the screens for a few seconds.

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
