### ISSUE TITLE
Deep Linking test call shows Warning 

### ISSUE THREAD

**Issue by jasan-s** [react-community/react-navigation#1940]
I added deep linking to my app as docs stated: 
Its functional now, but I'm getting the following warning when testing the URI call in the simulator:

> Warning: Can only update a mounted or mounting component. This usually means you called setState, replaceState, or forceUpdate on an unmounted component. This is a no-op.
> 
> Please check the code for the NavigationContainer component.

When navigating normally within the app this warning does not come up. 

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.11
| react-native     |  0.45.1

**Comment by ados1991** [comment]
same issue too

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
