### ISSUE TITLE
Can't use 'npm run ios' to run SimpleApp

### ISSUE THREAD

**Issue by amuseamuse** [react-community/react-navigation#1945]
Before adding react-navigation in my project, when I follow the get started instructions of react-native project, I can use 'npm run ios' to test my app via Exop on iPhone simulator, and when I edit App.js (eg:change text), the preview will update automatically. 

But after following instructions of https://reactnavigation.org/docs/intro, when I try 'npm run ios' in SimpleApp, it cannot run the project, instead I need to run 'react-native run-ios' to rebuild each time when I change my code. Does react-navigation support live reload? if not, do I need to run 'react-native run-ios' to refresh my app once I start using react-navigation?

**Comment by matthamil** [comment]
Do you have live reloading enabled in your emulator? You can activate the React Native development settings on the emulator by pressing CMD + M on your keyboard while the iOS emulator is open. Let me know if this issue persists while live reloading is enabled.

**Comment by andkhong** [comment]
did you yarn add the dependencies? you're less likely to run into issues if you yarn add install npm install

**Comment by amuseamuse** [comment]
my step to reproduce it:

1. I followed the instruction of creating a new react-native project:

npm install -g create-react-native-app
create-react-native-app AwesomeProject
cd AwesomeProject

2. add react-navigation into my project:

npm install --save react-navigation

3. replace the App.js with the following (react-navigation HelloWorld):

import React from 'react';
import {
AppRegistry,
Text,
} from 'react-native';
import { StackNavigator } from 'react-navigation';

class HomeScreen extends React.Component {
  static navigationOptions = {
    title: 'Welcome',
  };
  render() {
    return <Text>Hello, Navigation!</Text>;
  }
}

const SimpleApp = StackNavigator({
  Home: { screen: HomeScreen },
});

AppRegistry.registerComponent('SimpleApp', () => SimpleApp);

After replacing App.js, it is failed to run the app using 'npm run ios':

Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object. You likely forgot to export your component from the file it's defined in.

Check the render method of `AwakeInDevApp`.
in AwakeInDevApp (at registerRootComponent.js:21)
in ExponentRootComponent (at renderApplication.js:35)
in RCTView (at View.js:127)
in View (at AppContainer.js:93)
in RCTView (at View.js:127)
in View (at AppContainer.js:92)
in AppContainer (at renderApplication.js:34)

Note 1: I can run the app if I follow Hello Mobile Navigation in https://reactnavigation.org which uses 'react-native run-ios' instead of creating project from react-native tutorial (https://facebook.github.io/react-native/docs/getting-started.html)

Note 2: seems I started knowing what is happening, I'm using react-native, and should I use react-native-nagivation instead of react-nagivation?

**Comment by matthamil** [comment]
@amuseamuse This is an issue with unclear documentation, and thank you for reporting this issue. When you use `create-react-native-app`, you do not need to use `AppRegistry` in your root component. This is handled for you. Your root component is exported, which means that some other file will be using `AppRegistry`. If you use the `react-native` CLI to generate a new project (i.e. `react-native init HelloWorld`), you _will_ have to use `AppRegistry` to render your root component (similar to ReactDOM.render in React). 

If you are using `create-react-native-app`, your root component would look like this, given your example:

```js
import React from 'react';
import {
  Text,
  View
} from 'react-native';
import { StackNavigator } from 'react-navigation';

// Creating a simple Hello World home screen
class HomeScreen extends React.Component {
  static navigationOptions = {
    title: 'Welcome'
  };

  render() {
    return (
      <View>
        <Text>Hello, Navigation!</Text>
      </View>
    ); 
  }
}

const SimpleApp = StackNavigator({
  Home: { screen: HomeScreen }
});

export default SimpleApp; // Export your root navigator as the root component
```

I hope this resolves your issue and makes sense. The React Native documentation is pushing for new React Native users to get up and running with `create-react-native-app`, which is great. However, the original Hello World example for React Navigation was created _before_ CRNA was released. 

React Navigation is a library that aims to manage the issue of _navigation_ for you in your app. [React Native Navigation](https://github.com/wix/react-native-navigation) is another option, like you mentioned. I suggest that you look into both libraries and see which works best for your use case. React Navigation is still not yet at v1.0, although there is a [roadmap](https://github.com/react-community/react-navigation/issues/723).

**Comment by jamesg1** [comment]
Thanks @matthamil for that clarification.

**Comment by nomikeeper** [comment]
How about when you use react-native init to create a project? I still can't register to AppRegistery.
Here is my route settings.

```
import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View
} from 'react-native';
import {StackNavigator} from "react-navigation"
import mainScreen from "./views/login/_mainScreen"

class MainScreen extends Component{
  render(){
    return(
      <mainScreen />
    );
  }
}
const ProjectApp = StackNavigator({
  Login_MS:{screen: MainScreen},
},
{
  initialRouteName:"Login_MS"
});

AppRegistry.registerComponent(  'LessonTimeApp', () => ProjectApp,);
```
It's saying expected a component class, got [object Object] when I try to run the app.
I've been using react-navigation on react-native version: 0.44 and It was working fine in my previous project. Now I'm using react-native 0.47.1 and I'm failing on react-navigation integration.

P.S: I checked react-navigation docs and there was no change.

**Comment by spencercarli** [comment]
Instructions will be clarified when #2491 is merged

**Comment by vonovak** [comment]
Closing since #2491 was merged and the docs should be good now.
