### ISSUE TITLE
Can I change sub-routes with main-routes in run-time

### ISSUE THREAD

**Issue by efkan** [react-community/react-navigation#1948]
I use a `DrawerNavigator` which consists of **only one** `StackNavigator`. 
Because of components (screens) re-rendering when the current stack is changed I use only one `StackNavigator`.

My setup like the below:

```
AppNavigator (StackNavigator)

    ->    mainDrawer (DrawerNavigator)

          ->  mainStack (StackNavigator)

              -> Home (Screen component)
              -> Profile (Screen component)
              -> Contact (Screen component)

```

I wonder that can I change sub-routes (`Home`, `Profile` and `Contact`) with main-routes (in this case there is only one route, `mainStack`)? 

### Details

With this setup, the app opens Home screen first. The components on the screen can be changed according to `Redux` state. Users can navigate the other screens by using drawer menu (DrawerNavigator). Also users can return to `Home` screen by pressing `HeaderLeft` back button.
And also users can back to Home screen directly by using drawer menu. I use the code below to perform this case:

```
_backToHome = () => {

	const navigateAction = NavigationActions.navigate({
		routeName: 'mainStack',
		action: NavigationActions.back()
	})

	let routes = this.props.navigation.state.routes[0].routes
	routes.forEach((currentValue, index, array) => {
		if (index < routes.length - 1) { // don't dispatch for the initial route
			this.props.navigation.dispatch(navigateAction)
		}
	})

}
```
(_`action` option in `navigate` works like a charm!_)

It works. 

However, if I can set `Home`, `Profile` and `Contact` sub-routes as main-routes so instead of `mainStack` everything would be more easy.

For instance, `this.props.navigation.state.routes[0].index` gives the current route index. But I can find the current route index at ` this.props.navigation.state.routes[0].routes[0].index` with the code above.

Also I cannot use `this.props.navigation.goBack()` helper and cannot dispatch `NavigationActions.back` on `DrawerNavigator` because of the same reason.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  ^1.0.0-beta.11
| react-native     |  0.44.2
| node             | v7.10.0
| npm or yarn      |4.2.0

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
