### ISSUE TITLE
Dynamically configure initialRoute

### ISSUE THREAD

**Issue by tonyxiao** [react-community/react-navigation#195]
Is it possible to dynamically configure the initialRoute used in Stack Navigator and the like? Sometimes the initial route depends on user's login state. Right now there does not seem to be an easy way to take that into account.

**Comment by ericvicenti** [comment]
You have at least two options:

1. Create a new navigator with the correct initial route, once you know what it is
2. Control the navigator by providing the `navigation` prop, and making sure to render it with the correct initial `navigation.state`.

**Comment by ericvicenti** [comment]
I'm closing this out for now. If you have troubles with either option, please post a detailed issue with the example code, explaining the unexpected behavior.

**Comment by RobertSheaO** [comment]
@ericvicenti Can you provide an example of option number 2? I'm using redux, so I  already supply the `navigation` prop. Would I supply the correct initial state inside the `addNavigationHelpers` function?

**Comment by MrHubble** [comment]
@tonyxiao or @RobertSheaO are you able to share some code of how you solved the problem? Thanks.

**Comment by jasan-s** [comment]
@tonyxiao RobertSheaO  did you guys ever implment a solution

**Comment by adamterlson** [comment]
I just completed an implementation which will select the default route based on the shape of the redux store and the given params of the given route.  In my scenario, it's switching the default tab based on the current user's membership.

```javascript
import { TabNavigator } from 'react-navigation'
import { connect } from 'react-redux'

const TabNavigation = TabNavigator(
    {
        NonMemberTab: {
            screen: NonMemberScreen,
        },
        MemberTab: {
            screen: MemberScreen,
        },
    },
    {
        initialRouteName: 'NonMemberTab',
    },
)

const MyTabNav = (props) => {
    let navigation = props.navigation
    if (props.isMember) {
        navigation = {
            ...props.navigation,
            state: {
                ...props.navigation.state,
                index: navigation.state.routes.findIndex(r => r.routeName === 'MemberTab'),
            },
        }
    }
    return <TabNavigation navigation={navigation} />
}

const ConnectedMyTabNav = connect((state) => ({ isMember: state.isMember }))(MyTabNav)

```

**Comment by tmaly1980** [comment]
Maybe instead of handling this in the routing, use a shared (higher order) component that renders a different depending on the user's state?

**Comment by ababba15** [comment]
@tmaly1980 Seems like we want to let navigator handle that, including transitions and all other navigator's stuff..

**Comment by derakhshanfar** [comment]
@ericvicenti thanks for response but how can we Create a new navigator with the correct initial route after state changed?

**Comment by itskevinsam** [comment]
were someone able to implement any of the methods proposed by ericvicenti  ever ??
