### ISSUE TITLE
Sub routing and params do not work in reset!

### ISSUE THREAD

**Issue by ZHT131** [react-community/react-navigation#1951]
``
const resetAction = NavigationActions.reset({
          index: 0,
          actions: [
            NavigationActions.navigate({ routeName: 'TabNav',params:{},action: NavigationActions.navigate({ routeName: 'PersonalSet'})})
          ]
        })
        this.props.navigation.dispatch(resetAction);
``

# Action doesn't work, and params can't carry data to the next page in NavigationActions.navigate
#1620

**Comment by matthamil** [comment]
Closing in favor of #1620.
