### ISSUE TITLE
TabIcon failed to respond to use click in nested navigator

### ISSUE THREAD

**Issue by danqing-jin** [react-community/react-navigation#1952]
### Current Behavior

In my app, I have a login screen and a screen with tabbars at the bottom of the screen. I used stacknavigator to handle login screen and the screen with tabbars. If the use logged in successfully, I switched to tabnavigator. I used redux in my app. When I clicked the icon on the tab bar, I can see the state of my app changed. But the state of the icon does not change. Only the initial icon is active no matter which icon on the tab bar I clicked.
### Expected Behavior

If a tabnavigator is nested in a stacknavigator, I should be able to choose different tabs.
### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.11
| react-native     |  0.44.0
| node             | v8.1.0
| npm or yarn      | 5.0.3

**Comment by danqing-jin** [comment]
I just noticed that the app worked as expected if I enabled swipe. Maybe there's some sort of problem in my code?

**Comment by matthamil** [comment]
Thanks for the issue. Can you provide more information about your navigation stack and/or code snippets that you believe are causing the issue?

**Comment by danqing-jin** [comment]
Thanks for your attention. I added 'use strict'; to the top of my code and the app is working as expected now.
