### ISSUE TITLE
Got stackNavigator config cardStyle:transparent failed in some android devices.

### ISSUE THREAD

**Issue by Obooman** [react-community/react-navigation#1954]
### Current Behavior

```js
export default StackNavigator(decoratedRoutes,{
  headerMode: "none",
  transitionConfig: () => NavigationTransitionConfig,
  cardStyle:{
    backgroundColor:"transparent"
  }
})
```

The style config works well at some of our android devices,the scene appear from bottom with transparent background.In [redMi 4X](http://www.ebay.com/itm/Xiaomi-Redmi-4X-16GB-Black-Unlocked-Smartphone-/142405418370?hash=item2128063d82:g:-aAAAOSwAPVZNTwS) the device duration the animation it's transparent,upon finishing the animation the background turns to be grey(or some grey-like color,seem to be the default opaque background color).It behaves different among devices.

And I have tried `rgba(0,0,0,0)` color expression ,fails too.

### Expected Behavior
It should keep transparent all the time.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.11
| react-native     |  0.45.1
| node             | 8.0.1
| npm or yarn      | yarn 0.15.1

**Comment by Obooman** [comment]
#864 releated,I have tried make opacity 0.99
```js
export default StackNavigator(decoratedRoutes,{
  headerMode: "none",
  transitionConfig: () => NavigationTransitionConfig,
  cardStyle:{
    backgroundColor:"transparent",
    opacity:0.99
  }
})
```
and it works,however I lost the opacity transition.Another way I have changed the customized transitionConfig opacity relationship to 

```js

  var opacity = position.interpolate({
    // have not modified inputRange(the 0.99),see 
    // https://github.com/react-community/react-navigation/blob/master/src/views/CardStackStyleInterpolator.js#L128
    inputRange:[index - 1, index, index + 0.99, index + 1], 
    outputRange: [0, 0.99,0.99, 0]
  });
```
and it doesn't work.Any solution or better hack methods?

**Comment by matthamil** [comment]
What version of Android are you running on the devices that are encountering issues?

**Comment by Obooman** [comment]
It's  `Android 6.0.1 MMB29M`

**Comment by kelset** [comment]
Pinging OP @Obooman  since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open; if I get no answer in the next 7 days I will close it.

**Comment by kelset** [comment]
Hi there @Obooman ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.
