### ISSUE TITLE
can it run on react-native-web?

### ISSUE THREAD

**Issue by damiaozi** [react-community/react-navigation#1955]
The react native React-Navigation library is approaching maturity, and I'd like to add it into RN-web. I'm working on allowing routing and navigation code to be shared between web and RN.

Would this be accepted?

**Comment by kelset** [comment]
Closing in favor of https://github.com/react-community/react-navigation/issues/782#issuecomment-336658574

**Comment by jasonleonhard** [comment]
inconclusive.
