### ISSUE TITLE
HeaderBackTitle is Not Being Hidden When Setting It to null

### ISSUE THREAD

**Issue by junctioniv** [react-community/react-navigation#1956]
### Current Behavior
I am trying to hide the `headerBackTitle` for every screen in a `StackNavigator` which is nested in a `TabNavigator`. I have set each screen's `headerBackTitle: null` in the `navigationOptions` for each screen to hide it, but the `headerBackTitle` is still pulling the title of the previous page.

My screen Layout structure is:
```
TabNavigator
     - Home
          -> StackNavigator
               --> Screen1
               --> Screen2
               --> ...
     - Settings
```

The `navigationOptions` for each screen in the `StackNavigator` is as follows:

```
navigationOptions {
    title: 'Screen1',
    tabBarVisible: false,
    headerBackTitle: null,
  },
```
The `navigationOptions` for each screen in the `TabNavigator` is as follows:
```
navigationOptions: {
        title: "Home",
        headerBackTitle: null,
        tabBarLabel: "Home",
},
```

### Expected Behavior
According to the docs setting `headerBackTitle: null` should hide the `headerBackTitle` from the NavBar. I would think that if I have set all of these to null I should not be seeing the `headerBackTitle` still pulling though.

### Your Environment
I am testing this using Expo on ios.

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.11
| react-native     |  0.44.0

**Comment by junctioniv** [comment]
This randomly started working. Something must have been cached with expo.

**Comment by rajat1saxena** [comment]
It is not hiding the text on the back button for me. I don't know why.

**Comment by jemmyphan** [comment]
@rajat1saxena have u tried to set the headerBackTitle on the previous screen? not the current screen.

**Comment by euroclydon37** [comment]
@jemmyphan's suggestion works, but that's inconsistent with all of the other header options. And It's much more straight forward for the removal of the back title to take place on the active Screen, since your reason for removing it most likely relates to what's currently showing, not what was showing before. Just my opinion.

**Comment by jerrytohvan** [comment]
<img width="281" alt="Screen Shot 2020-03-26 at 10 16 35 PM" src="https://user-images.githubusercontent.com/12148853/77656877-76b8bd80-6faf-11ea-9258-5f9790a712ae.png">
<img width="420" alt="Screen Shot 2020-03-26 at 10 16 53 PM" src="https://user-images.githubusercontent.com/12148853/77656898-80422580-6faf-11ea-8f6d-ba348e46cd27.png">

Hi there, 
Same issue here. Its running fine on my android platform. However, i cant seem to hide the default iOS headerBackTitle.

**Comment by oehc123** [comment]
I am having the same issue as  @jerrytohvan , i was able to work arround by setting it to an string qwith a space =S

Not a good solutions though

**Comment by jerrytohvan** [comment]
@oehc123 strangely the string space on the `headerBackTitle` didnt work on my side either

**Comment by uusa35** [comment]
headerBackTitle: () => null,
worked for me

**Comment by uniqueomokenny** [comment]
I solved it by add 
`defaultNavigationOptions: {

	title: null,

},`

**Comment by rasck** [comment]
After upgrading react-navigation-stack from 1.X to 2.X i had to replace 
`headerBackTitle: null` with `headerBackTitleVisible: false`

I am using:
Expo: 36.0.0
React Navigation: v.4.X
react-navigation-stack: v.2.X

**Comment by daminduLiyanage** [comment]
> headerBackTitle: () => null,
> worked for me

Thank you. It works now.

**Comment by alan-usst** [comment]
![image](https://user-images.githubusercontent.com/49443628/119680501-d2146300-be73-11eb-99f1-b0a003070adf.png)
set headerMode = null in Navigator. It worked for me.

**Comment by akinncar** [comment]
"Title string used by the back button on iOS. Defaults to the previous screen's title, or "Back" if there's not enough space. Use headerBackTitleVisible: false to hide it."

So this will unshow the title correctly:
```js
headerBackTitleVisible: false
```

**Comment by savayer** [comment]
`headerBackTitleVisible: false` is not working

**Comment by esraaMaged** [comment]
both `headerBackTitleVisible: false` and `headerBackTitle: "some text"` aren't working :( Help?

**Comment by ValerioLV** [comment]
I brute forced it by replacing entirely the left section of the header and made my own "go back" arrow. Something like this 
`headerLeft: () => (
				<View className="flex-row items-center">
					<Entypo
						name="chevron-left"
						size={24}
						color="black"
						onPress={() => navigation.goBack()}
					/>`

**Comment by burakkbilginn** [comment]
The problem is still valid. Neither of the solutions mentined doesn't work. Not any library update for this issue?

**Comment by Seras3** [comment]
For iOS use:   

`
headerBackButtonDisplayMode: 'minimal'
`
