### ISSUE TITLE
Coupling animations to TabNavigator's sliding animation

### ISSUE THREAD

**Issue by asterikx** [react-community/react-navigation#1957]
I'm basically trying to achieve is Snapchat's camera capture button behaviour.

So I have the following requirements considering my `CameraButton` component:

- should be visible on most screens (quick-access to the camera screen), but not all. For example it should _not_ be visible in the Settings-`StackNavigator` nested inside top-level `TabNavigator`
- must trigger different actions depending on the currently active screen - taking a photo in the camera screen vs. navigating to the camera screen if another screen is currently active.
- should change its appearance while navigating. It's supposed to be smaller when the camera screen is not active (just like in Snapchat). For this I would like to apply an animation that is in sync with the sliding mechanism of the `TabNavigator`. So the animation's speed should match that of the sliding tab, i.e. even "pause" when the user slides the tab only halfway in (again, just like in Snapchat).

I'm not quite sure how to achieve such a behaviour bets with `react-navigation` (neither any other navigation library).

My first attempt was basically
```
<View>
  <AppNavigator {ref => this.nav = ref.navigation} />  // <-- top-level TabNavigator plus several nested Navigators 
  <CameraControl navigation={this.nav} />
</View>
``` 
So this way my `CameraControl` has access to the current active route and can thus decide when it should be visible and what action to trigger if gets pressed.

However I have no idea on how to implement the animation 😕 

Thanks for any suggestions! :slightly_smiling_face:

EDIT: I'm wondering if there's a cleaner solution. Deriving the active (nested) route from the bare version of the `navigation` prop doesn't feel like it was designed to do so (as the nesting depth varies from route to route). Also there is no rerendering happening to my `CameraControl` when the active route changes as the `navigation` prop doesn't change. I feel like I'm barking up the wrong tree...

**Comment by Minishlink** [comment]
For something similar, I'm currently using the `position` prop inside the TabNavigation's Header component. It's an `AnimatedValue`, meaning that you can do things like `this.prop.position.interpolate(...)`.
It's not ideal though, for two reasons:

1. Sometimes, the other tabs are not initialized until you swipe to their tab (even when lazy loading is disabled), and it makes the animation "jumping" from one position to the other
2. You have to put your animated component in the header

I'd love to hear about another way that may be better! :)

**Comment by kelset** [comment]
Pinging OP @asterikx since this issue has not been active for a while, and it's related to an old version of the lib. (moreover it's not really nor an issue nor a feature request)

Please let me know if you want this to remain open; if I get no answer in the next 7 days I will close it.

**Comment by asterikx** [comment]
Can be closed.
