### ISSUE TITLE
Background screen disappears after transition

### ISSUE THREAD

**Issue by dmr07** [react-community/react-navigation#1958]
I'm trying transition to modal stack while the current screen remains in the background. When the transition occurs, the background is at first present, but as the fade completes, it disappears into the background color of the modal. 

My fadeIn code is follows: 
```
function fadeIn(props) {
  const { layout, position, scene } = props;

  const index = scene.index;
  const height = layout.initHeight;

  const translateX = 0;
  const translateY = 0;

  const opacity = position.interpolate({
    inputRange: [index-1, index, index+1],
    outputRange: [0, 1, 0],
  });

  return {
    opacity,
    transform: [{ translateX }, { translateY }]
  };
}

export const RootNavigator = StackNavigator(
  {
    tabs : {
      screen: SomeNavigator
    },
    modals   : {
      screen: ModalNavigator
    },
  },
  {
    cardStyle: {
      shadowOpacity: 0,
      backgroundColor: 'transparent',
    },
    headerMode: 'none',
    transitionConfig: () => ({ screenInterpolator: fadeIn }),
    animationEnabled: false,
  },
);
```

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.11
| react-native     |  0.45.0
| node             | 7.4.0
| npm      | 5.0.3

**Comment by JulioC** [comment]
Maybe it's related to this? https://github.com/react-community/react-navigation/issues/864

In my case, the workaround  was to set `opacity: 1` on `cardStyle`

**Comment by dmr07** [comment]
@JulioC You're a life saver!
