### ISSUE TITLE
[iOS] Swipe back gesture has low width which makes it sometimes difficult to navigate back

### ISSUE THREAD

**Issue by cihancil** [react-community/react-navigation#196]
Swiping back is harder than native.
I believe if we can increase the width that swiping back gesture starts, it would be easier. 

Is it possible to make gesture width changeable
changeable?

**Comment by ericvicenti** [comment]
I agree, this should be improved! 

The logic is implemented here:

https://github.com/react-community/react-navigation/blob/master/src/views/CardStackPanResponder.js#L130-L134

Can you experiment with the values and let us know what feels better? PR would be appreciated!

**Comment by zzq889** [comment]
I set to 50 and it looks good for me.

**Comment by ericvicenti** [comment]
You set the `RESPOND_THRESHOLD` to 50? That doesn't seem right, I would expect a lower value than the current `15` to help this issue

**Comment by zzq889** [comment]
No I mean `gestureResponseDistance`. I didn't modify the source code.
```
const SettingsTab = StackNavigator({...});
SettingsTab.defaultProps = {
  gestureResponseDistance: 50,
};
```

But the velocity after pan release is weird. I have some idea to optimize the animation curve. The transition speed should be the same as pan release at the moment, and decrease the velocity by time. I'll try it and send PR when available.

**Comment by ericvicenti** [comment]
Awesome, thanks for taking a look! The performance is very delicate at the moment of release, and I think there is some room for improvement.

**Comment by ericvicenti** [comment]
Hmm, my understanding of the original issue is that sometimes the gesture doesn't start, even when touching from the right distance from the edge.

**Comment by cihancil** [comment]
@zzq889 
Thank you. Increasing gestureResponseDistance did it. Now it feels better.

@ericvicenti 
My issue was about manually setting gesture distance and it worked as @zzq889 implemented. I don't have any issue now about gesture being not started.

Thank you both I am closing the issue
