### ISSUE TITLE
Drawer doesn't open after fast double click. Primarily because the drawer and its state are out of sync

### ISSUE THREAD

**Issue by jainniket** [react-community/react-navigation#1960]
###Project
https://github.com/jainniket/drawer-issue

![afof7b](https://user-images.githubusercontent.com/10733088/27467163-998f9c88-57fd-11e7-819f-edb47a453911.gif)

### Current Behavior
There is a Hamburger Menu on whose click `DrawerOpen` action is triggered. 
But when, that menu is tapped twice very fast, the drawer opens and closes back, but the state is still set as Open.

So the error is, once the menu is clicked, it opens the drawer, but in the transition phase, when the drawer is opening, another tap happens which eventually happens to be on the View being presented by Drawer. This tap forces the menu to close back but the action `DrawerClose` doesn't get registered.

Whereas the redux state says the current route as `DrawerOpen` even though the drawer is clossed. So any further taps on the menu icon becomes un-responsive. 

Reason - The drawer presented and drawer state are out of sync.

### Expected Behavior
The double tap should be disabled.
The presenting view of drawer shouldn't take any touch event.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  ^1.0.0-beta.11
| react-native     |  0.45.1
| node             | v7.6.0
| npm or yarn      | v4.1.2

**Comment by d3fkon** [comment]
Agreed!
The button becomes unresponsive upon double tapping and won't work till the drawer is pulled from the edge of the screen. This makes up to a very bad user experience!

**Comment by jainniket** [comment]
@d3fkon exactly.. and this is specifically there on Android. unable to think of any hack to resolve this temporarily.

**Comment by d3fkon** [comment]
I think that if we handle the double tap with what's in here,
https://gist.github.com/mrzmyr/9ac94ca4622c1602a2a3 we can work it out

**Comment by jainniket** [comment]
@d3fkon so this was my first step towards fixing this issue. 
unfortunately, the double tap action isn't captured by the button but rather the presenting view of the drawer on which i have no control!!

**Comment by d3fkon** [comment]
I'll check it out and report back what happens

**Comment by d3fkon** [comment]
Okay. I  think I found a solution. Borrowing the idea from this, I could write my Navbar to handle double taps for drawer events.

```state = {
        lastLeftPress: 0,
    };

    DOUBLE_TAP_DURATION = 500;

    _handleLeftClick = (action, resetAction) => {
        const currentTime = parseInt(new Date().getTime());
        let duration = currentTime - parseInt(this.state.lastLeftPress);
        console.log(duration);
        this.setState({lastLeftPress: currentTime});
        if (parseInt(duration) <= this.DOUBLE_TAP_DURATION) {
            //Handle Double Tap
            console.log("Double");
            return resetAction? resetAction(): false;
        } else {
            //Handle Single Tap
            console.log("Single");
            return action();
        }
    };
```

As my NavBar is a separate component, I'm passing

1. `navigation.navigate('DrawerOpen')` as the `action' param
2. `navigation.navigate('DrawerClose')` as the `resetAction` param
to the event handling function.
According to the very simple logic here, If the user double taps,
The drawer will open as a result of the first tap. 
And if a double tap is recognized, the drawer will close, thus syncing the state of navigation.

I feel like 500 ms is quite good with the limited testing I could do. Feel free to report back lesser values which seem to work more effectively too. 
I'm not sure how reliable this solution is, but it sure as hell is better than not having a solution

**Comment by jainniket** [comment]
@d3fkon thank you for the help.
unfortunately that doesn't work. It is because the double tap action isn't captured by the button but the presenting view of the drawer by DrawerNavigation.

I've updated the sample project for this issue with the above mentioned suggestion.

https://github.com/jainniket/drawer-issue

**Comment by d3fkon** [comment]
I'm not quite sure about what you implemented there. I did not see my solution in your code,
However, I have made a pull request to your repo with the fix. Do check it out.

I strongly suggest you close the issue and also rename it to something more concise so that people who actually face this issue can come across with the solution more easily.

**Comment by jainniket** [comment]
@d3fkon My bad.. My code didn't get pushed..

Here's a PR 
https://github.com/jainniket/drawer-issue/pull/2

Moreover i just checked your PR. The issue isn't resolved in that.
When you double tap on the button very fast as shown in the gif, the drawer doesn't open after that.

**Comment by jainniket** [comment]
This fast-click is a separate issue. But this one which i've reported is definitely a different one.
This has something to do with the presented view of drawer and not the button being clicked.

**Comment by spencercarli** [comment]
We just [merged a PR](https://github.com/react-community/react-navigation/commit/8fdfc6d7a6e7695d5440b615d75696257005ef69) that adds a `DrawerToggle` option so you don't have to track the state of the drawer yourself. Will that fix this issue?

**Comment by kelset** [comment]
Pinging OP @jainniket since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open; if I get no answer in the next 7 days I will close it.

**Comment by axsann** [comment]
I have same issue..

**Comment by kelset** [comment]
Hi there @jainniket,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

@axsann if you are still having the issue with the latest version please open a new one that uses the new Issue Template to provide some more details to help us solve it.

**Comment by evanjmg** [comment]
This is still an issue, I've upgraded to the latest. Using key flag fixes it, but it breaks if you do it really fast :(

**Comment by LeoLopesRey** [comment]
I was able to fix it with:
``
props.navigation.navigate('DrawerClose'); setTimeout(() => props.navigation.navigate('DrawerOpen') ), 0}
``
when calling onPress to open the menu

**Comment by brentvatne** [comment]
should be resolved on master
