### ISSUE TITLE
Header defining working the wrong way

### ISSUE THREAD

**Issue by Fonze** [react-community/react-navigation#1961]
I have been making pretty complex navigation logics in my RN-apps and everytime I'm met the same annoying feature of react-navigation: parent navigators deciding what children's headers look like.

For example in Java when you extend other class you can redefine every rule a parent class has defined and the child always has the last word in it's functions and this pretty much goes for all different situation in different coding languages and libraries.

But in react-navigation let's say I have this kind of hierarchy:

```
StackNavgiator1
  screen1
  DrawerNavigator
    screen2
    StackNavigator2
      screen3
      screen4
```

I'd like to define in DrawerNavigator's NavigationOptions that I have a default header with a button for DrawerOpen-action on the left. Then in the StackNavigator2 I have screen3 which leads to screen4 and I could navigate back with a back button overriding the DrawerOpen-button, but in the end I'll end up seeing the header defined in DrawerNavigator.

Is there anyway to patch this so that the children have the power to define their NavigationOptions? Right now the only way about this is define header at every screen which ends up showing on the screen.

**Comment by spencercarli** [comment]
Could you provide a small running example of this issue? [Snack](https://snack.expo.io) is a great tool for that

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
