### ISSUE TITLE
Question: Multiple TavNavigators update changes across them all

### ISSUE THREAD

**Issue by florinpop17** [react-community/react-navigation#1962]
### Details
I have an app where I have multiple TabNavigators. 
Each TabNavigator contains a list of items but in different ways for different tabs like: liked items list, viewed items list, not viewed items list, etc...

### Question
Which is the best way to update an item which will update across multiple TabNavigations when the user for example, likes it? The issue I have now is that when I update an item from a list, it doesn't reflect that change in another list right away. I have to refresh the app as the changes are saved in the database but the state of the list is somehow "internal" to the corresponding tab.

Any suggestions?

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.11
| react-native     |  0.45.1
| node             | 8.0.0
| yarn      | 0.24.5

**Comment by cityvoice** [comment]
My suggestion is to  use redux to hold all states in this context.

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
