### ISSUE TITLE
Disable Drawer Navigation on some pages

### ISSUE THREAD

**Issue by Vetalyo** [react-community/react-navigation#1970]
### Current Behavior
I have some pages in my app. For example I have Login page which redirecting user to the Main app page using StackNavigator.

Redirecting to main page:
`this.props.navigation.navigate('MainNavigation');`

File with StackNavigator for redirecting:

```
const StartNavigation = StackNavigator(
  {
		// Send location page
    MainNavigation: {
			screen: MainNavigation
		},

		// Login page
    LoginPage: {
      screen: LoginPage
    },

		// Splash Screen
    Index: {
      screen: SplashScreen
    }
  },
  {
    initialRouteName: 'Index',
    headerMode: 'none',
    navigationOptions : ( { navigation } ) => ( {
      gesturesEnabled: false
    }),
    transitionConfig : () => ( {
      transitionSpec: {
        duration: 0
      }
    })
  }
);
```

On that Main Page I have Drawer Navigator with menu point's  which redirecting to own page and I also have 'Log out' point which redirecting to the Login page( First page of my app).
And all is working good except Drawer Navigator which is available on Login Page now.
Anyway to disable Drawer when redirecting to Login Page?

StackNavigator for redirecting to Login Page:
```
const loginPageStack = StackNavigator(
  {
    StartNavigation: {
      screen: LoginPage,
    },
  },
  {
    initialRouteName: 'StartNavigation',
    headerMode: 'none',
    navigationOptions : ( { navigation } ) => ( {
      gesturesEnabled: false
    }),
    transitionConfig : () => ( {
      transitionSpec: {
        duration: 0
      }
    })
  }
);
```

...

DrawerNavigator for redirecting to other pages and Login Page also:
```
const MainNavigation = DrawerNavigator(
{
  MainNavigation: { screen: locationPageStack },
  Test: { screen: testPageStack },
  StartNavigation: { screen: loginPageStack }
},
{
  initialRouteName: 'MainNavigation',
  drawerPosition: 'left',
  headerMode: 'none',
  contentComponent: CustomSidebarMenu
 }
);
```

On Log out menu point click:

`this.props.navigation.navigate('StartNavigation');`

| software         | version
| ---------------- | -------
| react-navigation |  ^1.0.0-beta.11
| react-native     |  0.44.2
| node             | 6.9.4
| npm | 3.10.10

**Comment by Vetalyo** [comment]
Can anyone help me?

**Comment by kholiavko-roman** [comment]
I have exactly the same problem. Does anybody found the solution ?

**Comment by dx51job** [comment]
Same problem. Looking for the solution.....

**Comment by rochapablo** [comment]
+1

**Comment by fgrs** [comment]
+1

**Comment by fgrs** [comment]
would love to know how to enable/disable DrawerNavigator for specific pages

**Comment by SimerdeepSinghPopli** [comment]
I have exactly the same problem. Does anybody found the solution ?

**Comment by jm90m** [comment]
No solution yet, but there's an open PR: https://github.com/react-community/react-navigation/pull/793

**Comment by vonovak** [comment]
you need to call a reset, not `navigate`, otherwise the screens will remain in you stack, and tapping the android back button would take user back to the screens before logging out.

**Comment by vonovak** [comment]
Closing, since this was solved with https://github.com/react-community/react-navigation/pull/1377
