### ISSUE TITLE
TabView: have way of knowing which tab is focused

### ISSUE THREAD

**Issue by EmielM** [react-community/react-navigation#198]
To "mark messages as read" I need to know if my tab view is currently being focused.

It looks like `react-native-tab-view` actually passes a `focused` prop to `props.renderScene({focused})`, but `react-navigation` does not pass this to the scene (neither in `TabView._renderScene` nor `SceneView.render`), presumably because it's not part of the generic scene API.

What would the approach for `TabNavigator` route components be to know if they are currently focused? Is there an alternative approach, perhaps subscribe directly to some events on the `navigation` prop and determine the current navigation state?

**Comment by EmielM** [comment]
I would suggest a `visible` prop could fit the generic API, because the same would apply for `StackNavigator` scenes that are in the history and currently not visible.

Adding such a property would break caching pure scenes, as they will have to be re-rendered when they become invisible. Quite stupid.

Any ideas, @satya164 ?

**Comment by satya164** [comment]
@EmielM We can add lifecycle hooks to the screens, and provide a HOC to pass the `focused` prop to the underlying component. Check https://github.com/react-community/react-navigation/issues/51#issuecomment-275866099

PR welcome if you want to implement it. Let's continue the discussion in the other issue.
