### ISSUE TITLE
incorporate with immutable.js without excess use of toJS()

### ISSUE THREAD

**Issue by RyanWan** [react-community/react-navigation#1980]
I am incorporating immutable.js into my RN app. I basically followed this link [https://medium.com/the-react-native-log/react-navigation-with-redux-and-immutable-js-1385c0457cb8](url). This method works for my app with the code below.

`  switch (action.type) {
    case LOGIN_SUCCESS:
      return state.merge(AppNavigator.router.getStateForAction(
        NavigationActions.navigate({ routeName: 'Main' }),state.toJS()));`
`const mapStateToProps = state => ({
  nav: state.get('nav').toJS(),
});`

However, in the documentation of redux, it says we should avoid the use of toJS() because they are expensive. 
I am wondering if there is a way to incorporate immutable.js without excess use of toJS().

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!

**Comment by taranda** [comment]
@RyanWan: Have you found a satisfactory answer?  I was thinking the same thing.  Unfortunately, I think it may take rewriting the middleware in react-navigation-redux-helpers to use Immutable  JS.

That seems like a beneficial project, but there may be easier work arounds.  I am open to suggestions.
