### ISSUE TITLE
Override value of GESTURE_RESPONSE_DISTANCE_HORIZONTAL

### ISSUE THREAD

**Issue by mazing** [react-community/react-navigation#1981]
How can I override the value of GESTURE_RESPONSE_DISTANCE_HORIZONTAL?

I would like to enable swiping the entire screen instead of only little of the left part of the screen. It doesn't seem such option is available although famous apps like Instagram, Facebook, etc. have this function enabled. Would it make sense to allow this?

**Comment by vonovak** [comment]
this was fixed by the linked pr
