### ISSUE TITLE
Is headerComponent prop still supported?

### ISSUE THREAD

**Issue by fdnhkj** [react-community/react-navigation#1982]
### Current Behavior
In master, `headerComponent` is listed as a prop of [`CardStack`component](https://github.com/react-community/react-navigation/blob/master/src/views/CardStack.js).
However, I don't see any place in the code where that prop is used.

Thus, I am wondering if this property is still supported or if it is legacy code.

![capture d ecran 2017-06-25 a 11 39 06](https://user-images.githubusercontent.com/5569608/27515065-5d837846-599b-11e7-8d41-0c664fdee179.png)

### Expected Behavior
If it is not supported, I think it would be nice to have a way to configure a custom header component at navigator level (just as it is possible at screen level via screen config).

**Comment by spencercarli** [comment]
I think that's just legacy. You can configure a custom nav header component via [`header`](https://reactnavigation.org/docs/navigators/stack#header)
