### ISSUE TITLE
How to refer to screens defined in StackNavigator from other file

### ISSUE THREAD

**Issue by Swaypreet** [react-community/react-navigation#1983]
I am facing issue while navigating from splashscreen to login/home screen
I have defined a stacknavigator as below:

AppNavigator.js

const AppNavigator = StackNavigator( 
{
  Splash: {screen: SplashScreen},
   Login: {screen: Login},
    Main: { screen: Main },
   Signup: {screen: SignUp},
   },
  {
 initialRouteName: 'Splash',
 });
export default AppNavigator 

index.android.js

export default class MY_APP extends Component {
  render() {
    return (
       <View>
       <AppNavigator />
      </View>
    );
  }
}
AppRegistry.registerComponent('MY_APP', () => MY_APP);

In my splashscreen.js i have written a logic where it checks if user is already logged in then go main page else go to login page.
using below code snippet.

_gotToHomePage=()=>{
       this.props.navigation.navigate('Main')
  }

but the screen is not navigating, i am not getting any error also.
Could you please help.

| software         | version
| ---------------- | -------
| react-navigation |  git+https://github.com/react-community/react-navigation.git
| react-native     |  0.43.3

**Comment by jurajkrivda** [comment]
```
const createRootNavigator = ({ userId = null }) => {
	return StackNavigator(
		{
			Splash: {
				screen: Splash,
			},
			Main: {
				screen: Main,
			}
		},
		{
			headerMode: "none",
			mode: "modal",
			initialRouteName: userId ? "Main" : "Splash"
		}
	);
};
```

**Comment by Swaypreet** [comment]
Thank you. I will try and update.

**Comment by cityvoice** [comment]
In your index.android.js:

```
import AppNavigator  from 'AppNavigator.js';
import { addNavigationHelpers} from 'react-navigation';
...
render() {
return(<AppNavigator screenProps={this.props} navigation={addNavigationHelpers({ dispatch:this.props.dispatch, state: this.props.nav })} />)
}
```
it should work.

**Comment by Swaypreet** [comment]
when i am trying with below version 

react-navigation	git+https://github.com/react-community/react-navigation.git
react-native	0.43.3

this.props.navigation.navigate('Main') --- this line of code is not working, page doesn't navigate at all,

but if i revert back to previous version 

{
    "react": "15.6.1",
    "react-native": "0.42.3",
   "react-native-maps": "0.15.2",
    "react-navigation": "git+https://github.com/react-community/react-navigation.git",
}
this.props.navigation.navigate('Main') -- this line is working and pages are able to navigate. I am not able to understand why it is happening like that, do i need to add any extra like of code ?

@cityvoice - Thank you, I have tried the solution you have shared, it is working. 

Regards,
Swaypreet

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
