### ISSUE TITLE
StackNavigator doesn't handle component transparent color

### ISSUE THREAD

**Issue by manuTro** [react-community/react-navigation#1984]
Hi, I'm using the Stacknavigator to render a component with a transparent background, but instead to have the tranparent color, the component has a light-grey background color ( is this maybe the stacknavigator default backgraund color? )

Is there a way to adjust it?
I tried by adding to the component style options `:background "transparent"` but this is not working.

Thanks

**Comment by igroz777** [comment]
in your StackNavigator you can provide the color like so:

const Stack = StackNavigator(
  {
    Screen1: {
      screen: Apple,
    },
    Screen2: {
      screen: Soft
    }
  },
  {
    cardStyle: {
      backgroundColor: "transperent"
    }
  });

**Comment by manuTro** [comment]
Thanks! now it's working :D

**Comment by fattahmuhyiddeen** [comment]
> transperent

seriously the spelling is "transperent" ? instead of "transparent". only wrong spelling works

**Comment by brentvatne** [comment]
no. this maybe does something that the OP interpreted as working but it is certainly not the correct way to do this
