### ISSUE TITLE
Header strange behavior

### ISSUE THREAD

**Issue by alexanderniebuhr** [react-community/react-navigation#1985]
Hello together,

currently I am working on a new project in RN and tried React Navigation.

Everything worked fine until I saw this

![good_1](https://user-images.githubusercontent.com/15894713/27538272-728966f6-5a77-11e7-8b30-b16d1e84846d.png)
![bad_2](https://user-images.githubusercontent.com/15894713/27538273-743f4362-5a77-11e7-9041-028ea589b582.png)

So on my main screen the top bar looks great, then I use a button to go to the next screen, but then the screen name appears under the clock of iOS.
```
const SimpleApp = StackNavigator({
  Home: { screen: CodeSharing },
  Submit: { screen: Submit },
},
  {
    navigationOptions: {
      header: null,
    },
    headerMode: 'none'
  }
);
```
Any Ideas or suggestion how to fix this?

Cheers
Alex

**Comment by lhang** [comment]
I have the same issue too
My back button and title is not in the right position

**Comment by smitch88** [comment]
You guys probably want to offset the "status bar" height which can be found in `Expo.Constants.statusBarHeight`

**Comment by alexanderniebuhr** [comment]
I would like to delete the screen name completly. How could I do this


Am 29.06.2017 um 15:48 schrieb Scott Mitchell:

**Comment by smitch88** [comment]
@alexanderniebuhr Make sure your navigationOptions title is empty or undefined perhaps? I think adding headerMode: 'none' would also do the trick already. I'm doing the exact same thing.

**Comment by smitch88** [comment]
I created a simple wrapping component `Screen` to handle this consistently across my screens.

```
import React from 'react';
import { StyleSheet, View } from 'react-native';
import { Constants } from 'expo';
import theme from '../theme';

/*
* Screen Component
*
* Simple top-level layout component that provides a full height / width / columnized
* `View` w/ an offset for the top status bar
*/

const styles = StyleSheet.create({
  container: {
    ...theme.layout.container,
    alignItems: 'center',
    justifyContent: 'space-around'
  },
  statusBar__offset: {
    paddingTop: Constants.statusBarHeight
  }
});

const Screen = ({ style = {}, children }) => (
  <View style={ StyleSheet.flatten([styles.container, style]) }>
    { /* Add top padding to offset status bar */ }
    <View style={ styles.statusBar__offset }></View>
    { children }
  </View>
);

export default Screen;
```

Used like...

```
<Screen><Text>Put stuff in here</Text></Screen>
```

**Comment by alexanderniebuhr** [comment]
@smitch88 as u see in my first post, i did add `headerMode: 'none'` didnt I?

**Comment by smitch88** [comment]
I see. I also use this and also avoid setting the title in my screens...

```
// https://reactnavigation.org/docs/navigators/stack#StackNavigatorConfig
const stackConfigurationOptions = {
  // Headers on screens will be created manually
  headerMode: 'none'
};

export default StackNavigator(routingConfiguration, stackConfigurationOptions);
```

Seems to work perfectly fine? Not sure...maybe you are adding it in the component side as a static prop?

**Comment by alexanderniebuhr** [comment]
So u add the headerMode prop to every single screen js file?

**Comment by smitch88** [comment]
no its just on the single StackNavigator instance just like you have...I dont see titles.

**Comment by alexanderniebuhr** [comment]
well that is the point, i dont want title. I want the navigation in the background of my application ... the user should not see any title bar or information except the ones i add later on the view

**Comment by smitch88** [comment]
Right and I don't see any title bar or anything by setting headerMode: 'none'. Not sure what your own app issue is.

**Comment by alexanderniebuhr** [comment]
The only prop my app is the little bug seen on the screenshot in the first post

**Comment by smitch88** [comment]
Right so you need to add the paddingTop for the statusBar and you will be fine. Good luck have some work to do now 👍

**Comment by alexanderniebuhr** [comment]
thx ... dont thing padding is the best way to solve. but a beginning

**Comment by smitch88** [comment]
Well its the recommended way of solving from Expo themselves. It's in the docs. But yeah it would be nice if by default expo exposed a layout component that just applied it.

**Comment by spencercarli** [comment]
[Not able to reproduce](https://snack.expo.io/r15B7x8t-) on the beta.11 using given code

**Comment by ozdemirozge** [comment]
{
      GirisEk: { screen: Giris },
      AnaRouterEk: { 
          screen: AnaRoutergit},
   },
    {
      navigationOptions: {
        header: null,
      },
      headerMode: 'none'
    }

**Comment by rosnaib11** [comment]
I got same issue. The navigation of my app overwrites to navigation of my phone. I was added `headerMode: "none"`

![image](https://user-images.githubusercontent.com/26837762/72696504-62071600-3b77-11ea-8ad7-a48410d5355a.png)
