### ISSUE TITLE
Android Back Button is not handled properly?

### ISSUE THREAD

**Issue by sankalpsingha** [react-community/react-navigation#1987]
### Current Behavior
I am developing a trivia game, I have 3 components, (newGame, Questions, Results ) I don't want the user to go back to the questions from the results page if the no. of questions has been exhausted, however, pressing the back button ( Android Hardware ) is taking him back to the questions. I then tried to handle the hardware back button like so: 
```
componentWillMount() {
      this.props.gameState(true);
      BackHandler.addEventListener('hardwareBackPress', () => {
        if (this.props.gamePlaying) { // Currently set to true. I will set it to false again on NewGame Page.
          this.props.navigation.navigate('NewGame');
        }
      });
    }
```
However, this is taking the user to the NewGame screen but immediately, it is bouncing back to the results page as it is firing the NAVIGATION/BACK as well immediately in the NewGame page. Which is again taking it back to the results page. 

### Possible fix?
I want to stop the the back button to fire after I have landed in the NewGame component page. Is there a way to do it?

### My Environment

| software         | version
| ---------------- | -------
| react-navigation |  ^1.0.0-beta.11
| react-native     |  0.44.0
| node             | 
| npm or yarn      | yarn

**Comment by dave-irvine** [comment]
`return true;` at the end of the handler to prevent the default.

**Comment by spencercarli** [comment]
Going to assume the comment left fixed the issue since there wasn't a followup - thanks @dave-irvine!
