### ISSUE TITLE
Display fixed routes in Drawer

### ISSUE THREAD

**Issue by clementino36** [react-community/react-navigation#1988]
### Current Behavior
The current route's name is automatically displayed in the drawer.

![screenshot_20170626-161302](https://user-images.githubusercontent.com/6041593/27543555-ca187e94-5a8a-11e7-9d96-f2dfb3dced57.png)

### Expected Behavior
The drawer's menu should always display the same route names through the entire app. Some other routes are available but the only entry points are the fixed names in the drawer.

![screenshot_20170626-161357](https://user-images.githubusercontent.com/6041593/27543606-f0c511f6-5a8a-11e7-8bc5-0a06097f704d.png)

Here's the relevant code:

```
const Stack = {
    Login: { screen: Login },
    Overview: { screen: Overview },
    Settings: { screen: Settings },
    Logout: { screen: Logout },
    JobDescription: { screen: JobDescription },
    TaskList: { screen: TaskList },
};

const DrawerRoutes = {
    SettingsStack: {
        name: 'SettingsStack',
        screen: StackNavigator(Stack, { initialRouteName: 'Settings' }),
    },
    OverviewStack: {
        name: 'OverviewStack',
        screen: StackNavigator(Stack, { initialRouteName: 'Overview' }),
    },
    LogoutStack: {
        name: 'LogoutStack',
        screen: StackNavigator(Stack, { initialRouteName: 'Logout' }),
    },
};

export const DrawerNavigation = StackNavigator({
    Drawer: {
        name: 'Drawer',
        screen: DrawerNavigator(DrawerRoutes),
    },
    ...Stack,
}, { headerMode: 'none' });
```

Hope it's clear enough! Thanks

**Comment by MrHubble** [comment]
@clementino36 I'm not sure I completely follow, but would using `navigationOptions` work/help:

````
const DrawerRoutes = {
    SettingsStack: {
        name: 'SettingsStack',
        screen: StackNavigator(Stack, { initialRouteName: 'Settings' }),
        navigationOptions: {
           drawerLabel: 'Settings',
        },  
    },
````

**Comment by clementino36** [comment]
I'll explain a bit more. 
A button in the `Settings` screen navigates to the `JobDescription` screen. As soon as I'm on the `JobDescription` screen, the first drawer label changes to the `JobDescription`'s navigationOptions title. Then if I navigate to the next page, the label changes to this page's title, etc.. So the drawer's first item is always the current screen. But what I want is that wherever you are in the app, the items in the drawer should always remain the same, so the first one should always be "Settings" and not the current screen.
So in this case, setting the `drawerLabel` in `DrawerRoutes` doesn't change anything.
I hope it makes sense, i'm having a hard time trying to give a clear explanation.

**Comment by clementino36** [comment]
Using the `contentComponent` prop of DrawerNavigator solved the issue.
It's as simple as that:
```
Drawer: {
        name: 'Drawer',
        screen: DrawerNavigator(DrawerRoutes, {
            contentComponent: DrawerView,
        }),
    },
```

Where `DrawerView` is just a custom component with a FlatList.

**Comment by MrHubble** [comment]
Thanks for taking the time to share your solution. I'm glad you were able to get it working.

Thanks also for your initial example code, it helped me understand how to use DrawerNavigator with StackNavigator.

I guess this issue can be closed now?
