### ISSUE TITLE
Reset always handled by child router

### ISSUE THREAD

**Issue by monteithpj** [react-community/react-navigation#199]
I have a setup with nested StackNavigators

```
const MyNavigator = StackNavigator({
    notSignedIn: {screen: StackNavigator(someRoutes)},
    signedIn: {screen: StackNavigator(someOtherRoutes)},
})
```
 When I have a state like:

```
{index: 0, 
 routes: [
     {index: 0,
      key: 'Init0',
      routeName: 'notSignedIn',
      routes: [... valid routes from someRoutes]
 }]}
```

and now I want to reset (so that the root route is signedIn) I can do 
```
NavigationActions.reset({index: 0, actions: [NavigationActions.navigate({routeName: 'signedIn'})]})
```

However, reset seems to always be handled by the child navigator, so it's giving me a state like:

```
{index: 0, 
 routes: [
     {index: 0,
      key: 'Init0',
      routeName: 'notSignedIn',
      routes: [{index: 0,
                key: 'Init0',
                routeName: 'signedIn'
                routes: [...initial route of signedIn]}]
 }]}
```

It then fails, because signedIn is not a valid child route of notSignedIn

Is this behaviour intended? How can I make the parent navigator (MyNavigator) handle the reset action?

I think the problem is that reset (as it contains multiple actions) should be handled before attempting to delegate to the child routers (as this will be attempted on a per-action basis while mapping over the sub-actions on the reset). A simple test of just copy-pasting the reset handling to before checking if the child should handle the action seems to fix my issue - but I've not thought this through thoroughly yet.

**Comment by ericvicenti** [comment]
Yes, the assumption is that the action will go to the deepest active router. However, we could implement a new feature for the Reset action, where they key can be specified. If the key is specified, the reset action would only reset for the router with the matching key in the state.

**Comment by Colmea** [comment]
I guess it's what causing my issue when trying to reset from a nested navigation to a parent navigation: "There is no route defined for key %key%" ?

Is there a simple workaround to avoid this issue ? 
Actually, I have a listener for auth. Each time auth change (connected/disconnected), I try to reset my navigation to LoginScreen or AppScreen. 
But this can occurs while in a nested navigation (and that's where this issue appears)

**Comment by pkl** [comment]
I'm having the exact same problem, @Colmea did you manage to find a workaround for this?

**Comment by monteithpj** [comment]
@Colmea I'm currently playing around with an alternative whereby the base navigator isn't a StackNavigator at all (assuming you're only ever going to want 1 element in it). I've hacked together a simple "SwapNavigator" that just replaces when its children get navigated to. This way you don't need to use reset.

It occurs to me, this is similar to just using a TabNavigator that is controlled programmatically...

**Comment by ElliottJRo** [comment]
Hey all,

I was having this issue as well. As Eric mentioned, the reset action is handled by the deepest active router. My workaround is to dispatch a `Navigate` action first and then nest a `Reset` action.

*Given a navigation like so:*
```js
const NestedStackView = StackNavigator({
  Home: {screen: genericView},
  Login: {screen: genericView}
})

const DeepNestedStackView = StackNavigator({
  Chat: {screen: genericView},
  Profile: {screen: genericView}
})

const NestedTabView = TabNavigator({
  Messages: {screen: DeepNestedStackView},
  Settings: {screen: viewWithResetAction}
})

const MasterNavigator = StackNavigator({
  UnAuth: {NestedStackView},
  Auth: {NestedTabView}
});
```

To reset navigation from `Settings` to `Home` (eg: user clicks logout) we would dispatch the following from the button `onPress`
```js
this.props.navigation.dispatch({
  type: NavigationActions.NAVIGATE,
  routeName: 'UnAuth',
  action: {
    type: NavigationActions.NAVIGATE,
    routeName: 'Home',
    action: {
      type: NavigationActions.RESET,
      index: 0,
      routeName: 'Home'
    }
  }
})
```

**Comment by grabbou** [comment]
To add what I mentioned in #389 

==

@ericvicenti do you think we should implement handling of `RESET` in TabRouter itself? Ie. if active tab doesn't handle it, then apply it on tabs.

Then:
```js
NavigationActions.reset({
   index: 0 ,
   routeName : "HomeDrawer",
   actions: [NavigationActions.navigate({routeName: "HomeScreen"}),
})
```
would mean to apply actions on a tab with name `routeName`. If there's no `ChildRouter` for a given tab, just do nothing (or warn).

Sounds like that's what all the people are trying to do.

**Comment by Kerumen** [comment]
I definitely need this too.

**Comment by Kerumen** [comment]
@grabbou @ericvicenti Do you think that this is something we can hope soon?

I think to not be able to reset the stack from a child router is not viable for a decent app nowaday. Every app with a Login / Signup process will need this. As it's the case for mine and I'm stuck now.

**Comment by devdlx** [comment]
Check this out. band-aid fix.
[gist](https://gist.github.com/devdlx/039cf28a7ea49c4b691f69a6ab380997)

**Comment by Landon696** [comment]
Any docs on the fix?

**Comment by michalmmm** [comment]
Any updates? Or is there a new workaround?

**Comment by flaviohenriquecbc** [comment]
+1

**Comment by quadsurf** [comment]
@ericvicenti 

> Yes, the assumption is that the action will go to the deepest active router. However, we could implement a new feature for the Reset action, where they key can be specified. If the key is specified, the reset action would only reset for the router with the matching key in the state.

Has this been implemented yet? Can you please provide an example of how to syntax this?

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
