### ISSUE TITLE
unmounting / remounting in StackNavigator

### ISSUE THREAD

**Issue by jslz** [react-community/react-navigation#1990]
hi I asked on discord but no real luck there.

react-navigation question/ignorance/confusion: it seems the StackNavigator keeps components around even as they get buried on the stack. They don't seem to be unmounted for example. This means when things pop off and the app is returning to an 'old' page, it has 'old' state afaict like if a textinput had gained focus, when we return it will still have focus - whereas it was defined to start off unfocused. iiuc this is a problem i have in my use case. does react-navigation give me something, sort of like "viewWillReappar" where i could know that a given component/page is live again because it was returned to / popped to?

* "react-navigation": "^1.0.0-beta.9",
* "react-native": "0.44.0",
* "react-redux": "^5.0.5",
* "redux": "^3.6.0",
* "redux-logger": "^3.0.6",
* "redux-thunk": "^2.2.0",

**Comment by buncismamen** [comment]
yeah I need this, so my code in componentDidMount(); is working

**Comment by jslz** [comment]
@buncismamen et. al. I do not think that #51 is what I want, personally. What I think I want is a navigator that remembers the stack but

1. does not pre-create any components.
1. only creates the component when they are being navigated to, either going to them or returning to them from the stack.
1. releases/frees/destroys the component when navigating away from it. (in the case of navigating to the same screen then i am going to hazard to guess it is better to not release it, as the exception that proves the rule.)
1. thus calls the full RN component lifecycle appropriately when going to or leaving a component.

What I want is basically a "StacklessNavigator" that keeps the history so that back navigation works right automatically, however, does not cache any components at all. (Somebody should think of a better name, of course, like "NonCachingStackNavigator" or something.)

**Comment by leejms** [comment]
Hi Guys!  I'm new here and have been asked to help out with this.  Based on the last post by @jslz it seems this would be a custom router where every route acted like a `reset()` but the route history is stored in an array somewhere, so when you go "back" it will create a new nav to the previous route via the array.

Are you sure you want to destroy and create the view each time?  this can cause render delays especially if data is involved.

**Comment by jslz** [comment]
@leejms having the option to experiment with cached vs. non-cached would be great. While caching might make things faster, it has various effects that don't fit our use case so well.

**Comment by leejms** [comment]
cool!  i'm getting the code now and will look into it.
can you give me a newbie version of the unwanted effect and how to create it?
(**very** noob! :) )
@jslz & @buncismamen

**Comment by yash2code** [comment]
same issue

**Comment by Noitidart** [comment]
@leejms, @yash2code  wouldn't this `replace` here - https://github.com/react-community/react-navigation/issues/2122 - solve this issue?

**Comment by ishita-kothari** [comment]
I have following dependencies:
"react-navigation": "^1.0.0-beta.11",
"react": "16.0.0-alpha.12",
 "react-native": "0.45.1"

How can I use navigator.pop() function? I need to unmount older screen and navigate to new screen.

**Comment by ArvoGuo** [comment]
`NavigationActions.reset` saved me.

I spent time to re-understand `NavigationActions.reset`'s usage.

the correct usage is that you should reset all navigation state stack.

it means we should give a basic stack navigation list to actions , and point out your current index.

```js

   const resetAction = NavigationActions.reset({
        index: 2,         // it means current state is C, and can goBack to A
        actions: [
          NavigationActions.navigate({ routeName: 'A'}),
          NavigationActions.navigate({ routeName: 'B', params: {id: "***"}}),
          NavigationActions.navigate({ routeName: 'C', params: {id: "***"}}),
          NavigationActions.navigate({ routeName: 'D', params: {id: "***"}})
        ]
   })
   this.props.navigation.dispatch(resetAction);

```

**Comment by Noitidart** [comment]
Oh wow thanks for sharing that @ArvoGuo - your example really helps to makes sense of it!

**Comment by kelset** [comment]
Pinging OP @jslz since this issue has not been active for a while, and it's related to an old version of the lib. Moreover, the snippet @ArvoGuo seems to help out in clarifying the question and the actual FR is on #51.

Please let me know if you want this to remain open; if I get no answer in the next 7 days I will close it.

**Comment by kelset** [comment]
Hi there @jslz ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.

**Comment by jaspermendiola** [comment]
Navigations.reset is now replaced with StackActions.reset
