### ISSUE TITLE
Route `router` should declare a screen Error!

### ISSUE THREAD

**Issue by Domthegrom** [react-community/react-navigation#1991]
Trying to get my react-navigation Routes to work and I can not for the life of me get past this error! Any guidance would be much appreciated! Error and code snippet below.
![simulator screen shot jun 26 2017 12 58 56 pm](https://user-images.githubusercontent.com/23178405/27559510-d1ab0902-5a8e-11e7-8914-9db40a3de066.png)
```import React from "react";
import { TabNavigator, StackNavigator } from "react-navigation";
import { View } from "react-native";
import Login from "../app/screens/login";
import Profile from "../app/screens/profile";
import Icon from "react-native-vector-icons/FontAwesome";
import Home from "../app/screens/home";
import SignUp from "../app/screens/signup";
import LoginForm from "../app/screens/loginform";
import Discussion from "../app/screens/discussion";

const myNavOptions = {
  headerStyle: {
    backgroundColor: "#FFFFFF"
  },
  headerRight: (
    <Icon
      onPress={() => navigation.navigate("Profile")}
      name="user-circle"
      size={22}
      color="#b6b6b6"
      style={{ marginRight: 8 }}
    />
  ),
  headerLeft: (
    <Icon
      onPress={() => navigation.navigate("Profile")}
      name="comments-o"
      size={22}
      color="#b6b6b6"
      style={{ marginLeft: 8 }}
    />
  ),
  title: "Coin Deck"
};

const Routes = StackNavigator({
  Login: {
    screen: Login,
    navigationOptions: {
      header: null
    }
  },
  Home: {
    screen: Home,
    navigationOptions: myNavOptions
  },
  Profile: {
    screen: Profile,
    navigationOptions: {
      headerStyle: {
        backgroundColor: "#FFFFFF"
      },
      title: "Domthegrom"
    }
  },
  SignUp: {
    screen: SignUp,
    navigationOptions: {
      header: null
    }
  },
  LoginForm: {
    screen: LoginForm,
    navigationOptions: {
      header: null
    }
  },
  Discussion: {
    screen: Discussion,
    navigationOptions: {
      title: "Coin Name"
    }
  }
});

export default StackNavigator(Routes);```

**Comment by bhoop** [comment]
You are calling `StackNavigator()` twice:
1. `const Routes = StackNavigator({`
1. `export default StackNavigator(Routes);`

Removing one of those calls should fix your issue (i.e. change the export to `export default Routes;`).

**Comment by kristofferkarlsson93** [comment]
Hi! 
I have a problem similar to this. Can anyone help? 
I have created a router
`import React from 'react'
import { NavigationComponent } from 'react-native-material-bottom-navigation'
import { TabNavigator } from 'react-navigation'
import Settings from './screens/Settings.js';
import MainScreen from './screens/MainScreen.js';

export const Tabs = TabNavigator({
	Settings: {
		screen: Settings,
	},
	MainScreen: {
		Screen: MainScreen,
	},
},
{
	tabBarPosition: 'bottom',
	swipeEnabled: true,
});`

and two screens, wich both look like this.

`mport React from 'react';
import TextView from 'react-native';
import Icon from 'react-native-vector-icons/MaterialIcons'


export default class MainScreen extends React.Component {
	static navigationOptions = {
		tabBarLabel: 'MainScreen',
		tabBarIcon: () => (<Icon size={24} color="white" name="tv" />)
	}

	render() {
		return (
			<View><Text>Main</Text></View>
		)
	}
}`

I get the Error: 'MainScreen should be decleared a screen. 
What might be teh problem? 
Full project here: 
https://github.com/kristofferkarlsson93/solidar-spar/tree/master/Solidar

**Comment by sujitpk-perennial** [comment]
I got this issue for following
`import { RootScreen } in '../../Tabs/RootScreen' `
I changed this to 
`import RootScreen in '../../Tabs/RootScreen' `
