### ISSUE TITLE
is there a way to lazyload screen component?

### ISSUE THREAD

**Issue by cityvoice** [react-community/react-navigation#1995]
I have many screen components defined in AppNavigator. below is code:
```
import MainScreenNavigator from './MainTab';
import ArticleDetailScreen from '../containers/ArticleDetailScreen';
import ArticleListScreen from '../containers/ArticleListScreen';
import SignInScreen from '../containers/SignInScreen';
...
export const AppNavigator = StackNavigator({
MainTab: { screen: MainScreenNavigator },
ArticleList:{screen: ArticleListScreen , ...
ArticleDetail:{screen: ArticleDetailScreen , ...
SignIn:..
SignOut:...
...
})
```

it seems the app loaded all screen components  before loads AppNavigator, so the screen is frozen before all components loaded successfully, it's a bad experience to client.how to resolve this problem?

**Comment by Clowning** [comment]
You can put this option 'lazy' in 'TabNavigatorConfig' :)

**Comment by cityvoice** [comment]
Thanks, but my screen components is defined in StackNavigator, such as ArticleListScreen, ArticleDetailScreen and so on , it seems that StackNavigatorConfig doesn't have this option.

**Comment by spencercarli** [comment]
All screens in the stacknavigator won't be loaded until they're active or in the stack. If that's the case please supply a demo of the issue. Thanks!

**Comment by arkhwise** [comment]
@cityvoice you can use `getScreen` property but there is one limitation

> Note: Child navigators cannot be configured using getScreen because the router will not be accessible. Navigators must be configured using `screen: MyNavigator`

 https://reactnavigation.org/docs/routers/stack#RouteConfig

**Comment by Udbhav12** [comment]
@arkhwise - Can you please share an updated link or some documentation regarding `getScreen` property ? The link shared above is not working
