### ISSUE TITLE
How do I get " >" rather than back button in stack navigation

### ISSUE THREAD

**Issue by jpca999** [react-community/react-navigation#1997]
like in the image below 

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  
| react-native     |  
| node             | 
| npm or yarn      |

**Comment by matthamil** [comment]
Can you provide more details behind your question?

**Comment by jpca999** [comment]
Sure, below is the pic of my project. 

it has 4 tabs,  heres the code below what i want is, when i go to followup tab, it should give me drawer option.. , 

import { TabNavigator, StackNavigator, DrawerNavigator } from 'react-navigation';
import { Provider } from 'react-redux';

import store from './store';

import AuthScreen from './screens/AuthScreen';
import WelcomeScreen from './screens/WelcomeScreen';
import MapScreen from './screens/MapScreen';
import DeckScreen from './screens/DeckScreen';
import SettingsScreen from './screens/SettingsScreen';
import ReviewScreen from './screens/ReviewScreen';
import UserProfileScreen from './screens/UserProfileScreen';
import SubscriptionScreen from './screens/SubscriptionScreen';

import ContractSettingsScreen from './screens/ContractSettingsScreen';
import HelpSupportScreen from './screens/HelpSupportScreen';

import FollowupScreen from './screens/FollowupScreen';

import NotificationsScreen from './screens/NotificationsScreen';
import FeedbackScreen from './screens/FeedbackScreen';


class App extends React.Component {
  render() {
    const MainNavigator = TabNavigator({
          review: { screen: ReviewScreen },  // Jay remove it from here
          welcome: { screen : WelcomeScreen },
          auth: { screen : AuthScreen },
          main: {
            screen: TabNavigator ({
              followup: { screen: FollowupScreen },
              map: { screen: MapScreen },
              deck: { screen: DeckScreen },
              review : {
                screen: StackNavigator ({
                  review: { screen: ReviewScreen },
                  settings: { screen: SettingsScreen },
                  UserProfile: { screen: UserProfileScreen },
                  Contract: { screen: ContractSettingsScreen },
                  Subscription: { screen: SubscriptionScreen },
                  HelpSupport: { screen: HelpSupportScreen },
                  Notifications: { screen: NotificationsScreen },
                  Feedback: { screen: FeedbackScreen },

                })
              }
            })
          }
    }, {
      navigationOptions: {
          tabBarVisible: false
      },
      lazy: true
});




![image](https://user-images.githubusercontent.com/1026325/27613893-2f91148e-5b6c-11e7-805a-d775648d808a.png)

**Comment by jpca999** [comment]
so now ive adaded another screen called draw , but how do i add drawer inside it ?

class App extends React.Component {
  render() {
    const MainNavigator = TabNavigator({
          review: { screen: ReviewScreen },  // Jay remove it from here
          welcome: { screen : WelcomeScreen },
          auth: { screen : AuthScreen },
          main: {
            screen: TabNavigator ({
              // followup: { screen: FollowupScreen },
              map: { screen: MapScreen },
              deck: { screen: DeckScreen },
              review : {
                screen: StackNavigator ({
                  review: { screen: ReviewScreen },
                  settings: { screen: SettingsScreen },
                  UserProfile: { screen: UserProfileScreen },
                  Contract: { screen: ContractSettingsScreen },
                  Subscription: { screen: SubscriptionScreen },
                  HelpSupport: { screen: HelpSupportScreen },
                  Notifications: { screen: NotificationsScreen },
                  Feedback: { screen: FeedbackScreen },
                })  //screen: StackNavigator ({
              },
              draw: {
                screen: DrawerNavigator ({
                  drawin: { screen: DrawScreen },
                })  //screen: StackNavigator ({
              }
            }) //screen: TabNavigator
          }
    }, {
      navigationOptions: {
          tabBarVisible: false
      },
      lazy: true
});

**Comment by jpca999** [comment]
Awesome I got it working Thanks, :_)

**Comment by jpca999** [comment]
Lol sorry I mixed up the issues...

**Comment by jpca999** [comment]
Drunk programming
