### ISSUE TITLE
transitionConfig not working no matter what

### ISSUE THREAD

**Issue by igroz777** [react-community/react-navigation#1998]
### Current Behavior
passing transitionConfig does absolutely nothing. If i modify the default interpolator used for android in TransitionConfig.js I can see changes.

### Expected Behavior
transition config should be able to affect the transition of screens

### Your Environment
Windows 10, Android virtual device(emulator)

| software         | version
| ---------------- | -------
| react-navigation |  react-navigation.git#7edd9a7
| react-native     |  0.45.1
| node             | 6.9

**Comment by igroz777** [comment]
So i tracked down the issue to StackNavigator.js. transitionConfig was not being passed as a prop to CardStack component. I added it manually.

I checked the current master branch and transitionConfig is there. Apperently the issue is me using this in my package.json file:

 "react-navigation": "https://github.com/react-community/react-navigation.git#7edd9a7",

I had issues with the alpha build and saw using this version as a solution. 

Hope someine can address this?

**Comment by spencercarli** [comment]
If this was on master then it should be in the latest release. Let me know if not

**Comment by NickOpen** [comment]
Hi, I occur this issue on react-navigation V2.18.2,  transitionConfig is not working no matter what change the transitionConfig function when i used the "react-navigation-transitions" npm package (https://www.npmjs.com/package/react-navigation-transitions);

My Environment:
![image](https://user-images.githubusercontent.com/3014954/48463511-3839bd00-e817-11e8-89b9-c8c45441deaf.png)

Device: Android V7.1.1  & iOS (simulator iPhone 8)
