### ISSUE TITLE
Is it possible to make navigation bar translucent (iOS)?

### ISSUE THREAD

**Issue by GaborWnuk** [react-community/react-navigation#200]
Hi,

i'm trying to achieve translucent navigation bar on iOS, however currently i have no luck with available attributes.

Currently i'm configuring my StackNavigator like this:

```javascript
const ExploreNavigator = StackNavigator({
  Home: {
    screen: ExploreScene,
    navigationOptions: {
      header: ({ state, setParams }) => ({
          style: {
            translucent: true
          }
        }),
      },
  }
})
```

However, navigation bar is still just gray and nontransparent.

**Comment by veenanjoshi** [comment]
Hi,

I am also looking for the solution to modify navigation bar color for Android.

my code : 

`
static navigationOptions = {
    title: 'Home',
    header: {
      style: {
        backgroundColor : '#454545'
      }
    }
  }
`

Is there any way to modify navigation bar background color ?

**Comment by si-harps** [comment]
Also experiencing header styling issues. i cant seem to find a way to style a header component from within navigationOptions. 

```
static navigationOptions = {
        title: 'Home',
        header: ({ state, setParams }, defaultHeader) => ({
            ...defaultHeader,
            style: HeaderStyle,
            right: (<Icon
                name="menu"
                style={{ fontSize: 20, right: 15 }}
            />)
        })
    };
```

...where HeaderStyle is...

```
{
    backgroundColor: 'red'
}
```

**Comment by yapjinkun** [comment]
Having header styling issue as well. "visible" option is not working for IOS, but it's working for Android.

`class HomeScreen extends React.Component {
  static navigationOptions = {
    title: 'Welcome',
    header: ({ state, setParams }) => ({
      visible: false
    })

  };
  render() {
    return <View style={{backgroundColor:'#ff5976', flex: 1}}>
        <Text>Hello, Chat App!</Text>
        <Button
          onPress={() => this.props.navigation.navigate('Chat', { user: 'Lucy' })}
          title="Chat with Lucy"
        />
      </View>;
  }
}`

**Comment by si-harps** [comment]
@yapjinkun i had a similar issue, try changing the headerMode to 'screen' in the navigator. Unfortunately, this will not work with headerMode as 'float' (IOS default)

**Comment by yapjinkun** [comment]
@si-harps much thanks, it's works now to hide the header bar. This will be workaround for me to insert custom header if react-navigation header styling is not working :(

**Comment by plraphael** [comment]
Guys, I manage to style the nav bar using react-navigation that is on master right now. Installed with this command:

npm install --save https://github.com/react-community/react-navigation.git

**Comment by jinxac** [comment]
@plraphael  not working for me :( . Are you sure this issue is fixed?

**Comment by si-harps** [comment]
Thanks @jinxac , that worked for me :)

**Comment by si-harps** [comment]
It looks as though style is applied to all header elements. For example, i have set a border which is being applied to the container as well as each of the buttons. ie. left and right

**Comment by designorant** [comment]
@si-harps That's a known bug: #189.

**Comment by grabbou** [comment]
Closing in favour of #11

**Comment by hnryjms** [comment]
I'm not really sure that #11 is the same ticket. On native iOS, the entire `44px` navigation bar is not a solid color, and instead is a mostly-tinted white that blurs the content that is below it. This is completely separate from the Android-only `StatusBar.setTranslucent()` and `light-content` styles on the StatusBar component built-in to ReactNative. I think the original poster of this ticket is referring to getting support for the translucent functionality of the navigation bar similar to native iOS, rather than the status bar (an Android only thing).

**Comment by cseelus** [comment]
@grabbou Yes, this has nothing to do with #11. This issue here regards options to get the DrawerNavigator to look like with native iOS apps, see here (1 = translucent, 2 = solid):

![ZQzd3](https://user-images.githubusercontent.com/3188392/54853304-c525e300-4cef-11e9-8193-4fcca173ca81.png)

**Comment by brentvatne** [comment]
https://github.com/react-navigation/react-navigation/blob/master/examples/NavigationPlayground/app/StackWithTranslucentHeader.tsx

**Comment by cseelus** [comment]
Thanks @brentvatne, you got to be the most helpful guy on Github ;-)

I already saw [the old example](https://github.com/react-navigation/react-navigation/blob/828e7f2d437cab81e9a33584a3d548203169f4de/examples/NavigationPlayground/js/StackWithTranslucentHeader.js) and was wondering if the inset has to be added to every screen manually.

Btw when trying to run the [new react-navigation examples](https://github.com/react-navigation/react-navigation/tree/master/examples/NavigationPlayground) via sending a link to my iPhone, i get the following error:

![IMG_0102](https://user-images.githubusercontent.com/3188392/54865934-e88f7300-4d6d-11e9-9cb3-8e806268b4a0.png)
