### ISSUE TITLE
Question : Why to integrate 'redux' to this library?

### ISSUE THREAD

**Issue by furkanedu** [react-community/react-navigation#2003]
Why would someone want to integrate 'redux' to this library ? 

Although I will use redux in my project, I can not think of any reasons to integrate it to this library. 

Any reason I can not think of ? 

I have integrated react-router to redux in a previous project, but again, there was no gain to doing this. So before integrating for react-native, I am not sure why to do this. 

If there is a simple reason like being unable to change routes without redux or sth, I would like to know. 

Otherwise I do not want to spend time on how to integrate. Thanks for your time to read and answer.

**Comment by uxman-sherwani** [comment]
You can do every possible navigation without integrating redux. 

The only benefit of integrating it with redux would be to navigate from anywhere in the code by dispatching actions. Without redux, only screen components have navigation props needed for navigation. You have to pass this prop to nested child components, if they want to change routes. But this comes with a price,  you are now responsible for persisting navigation state, handling any deep linking, integrating the back button, etc. Also, the added complexity of handling nested navigators.

**Comment by furkanedu** [comment]
Thanks for the clear answer. 

I thought so. This only benefit already requires me to pass dispatch or actions to the components so I do not think passing the given props to the child components are different. 

I will not integrate the library to redux. At least until I see it is required. 

It would be great to point out 'why to integrate' to the docs so that nobody feels like they have to integrate. 

Anyway, thank you.
