### ISSUE TITLE
Jest Tests failing after upgrading to react-native 0.45.1

### ISSUE THREAD

**Issue by uxman-sherwani** [react-community/react-navigation#2004]
### Current Behavior
After upgrading to react-native 0.45.1 and react 16.0.0-alpha-12 jest tests starts to fail

![screen shot 2017-06-27 at 16 02 18](https://user-images.githubusercontent.com/3153380/27591603-730e4a52-5b52-11e7-977b-0c1496a509e7.png)

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.11
| react-native     |  0.45.1
| node             | 8.0.0
| yarn      | 0.24.5

**Comment by jainniket** [comment]
Can you post the failing test case and code snippet being tested?

**Comment by uxman-sherwani** [comment]
Its the default test which comes with react-native init. It works fine with react-native 0.44.3.

**Comment by kelset** [comment]
Pinging OP @uxman-sherwani since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open; if I get no answer in the next 7 days I will close it.
