### ISSUE TITLE
TabBar right border

### ISSUE THREAD

**Issue by florinpop17** [react-community/react-navigation#2005]
Is there a way I could set a right border for all but last of the tab bars?
I tried adding some styling to the `tabStyle` but it's not working...
```
"react": "16.0.0-alpha.12",
"react-native": "0.45.1",
"react-navigation": "^1.0.0-beta.11",
```

**Comment by spencercarli** [comment]
Here are the different style options for tabs. Give another one a shot

- `style` - style object for the tab bar
- `labelStyle` - style object for the tab label
- `tabStyle` - style object for the tab

An example of what you want to accomplish/tried to accomplish would be helpful here, we can discuss further then
