### ISSUE TITLE
I can't find the a way to pull the drawer in your example  of Drawer + tabs Example. 

### ISSUE THREAD

**Issue by jpca999** [react-community/react-navigation#2008]
![img_0066](https://user-images.githubusercontent.com/1026325/27606563-d1bd5524-5b4e-11e7-95d7-1fbc5634a9d5.PNG)

I took the example from here :    https://expo.io/@react-navigation/NavigationPlayground

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  
| react-native     |  
| node             | 
| npm or yarn      |

**Comment by jainniket** [comment]
I think left swipe will open the drawer.
Ideally there should be a button too!! You can add it and trigger action 'DrawerOpen' on press of that button

**Comment by jpca999** [comment]
you’re right 



thank you,
Jay
