### ISSUE TITLE
params undefined on ios but on android ok

### ISSUE THREAD

**Issue by shuffgy** [react-community/react-navigation#2009]
### Current Behavior
`this.props.navigation.state.params` is `undefined` on **ios**, but on **android** i'm getting the correct values.

From a TabNavigator-Screen i'm navigating via button to another StackNavigator-Screen via 
` 
_goToComments(){
this.props.navigation.navigate('Comment', {datum: this.state.antwort.datumraw, wahl: this.state.antwort.echo});
}`

On the "Comment"-Screen i'm checking everything in the cunstructor

`    constructor(props) {
      super(props);
      this.state = {
                      [....some states.....]
                  }
    console.log(this.props.navigation.state.params); // Here i'm checking the parameter from navigate
    }`

### Your Environment
Testing Apps via Expo.io-Client on an Android Nexus 6P and iPhone 6S+ with react-navigation 1.0.0-beta.11

Am I just missing something?

**Comment by nickmccally** [comment]
@shuffgy did you ever find a solution? I'm experiencing the same thing.
