### ISSUE TITLE
why don t you provide working image on this location ?   https://reactnavigation.org/docs/navigators/drawer

### ISSUE THREAD

**Issue by jpca999** [react-community/react-navigation#2010]

**Comment by matthamil** [comment]
I'm not sure I understand your question. Can you go into more detail?

**Comment by jpca999** [comment]
I appreciate your reply. Like in other pages you have the images at the bottom.  like below image. 

Also 



![image](https://user-images.githubusercontent.com/1026325/27613516-f589b91e-5b69-11e7-825f-57bec1787a42.png)

Also in this example  the drawer doesnt work / at least i couldnt figure how to open drawer inside the tab/s. 

![image](https://user-images.githubusercontent.com/1026325/27613560-3a2749ce-5b6a-11e7-99e7-386b96940f17.png)

**Comment by matthamil** [comment]
If you are referring to the tabs, a drawer does not require a tab navigator. This is why none appear.

**Comment by jpca999** [comment]
@matthamil   i agree but   if i have 4 tabs, how do i fit in Drawer inside one of the tabs ?

**Comment by matthamil** [comment]
You can render a TabNavigator inside a DrawerNavigator. This will overlay the ability to swipe-to-reveal the drawer over your tabs. Or you can use `navigation.navigate('DrawerOpen')` and `navigation.navigate('DrawerClose')` to close it.

**Comment by jpca999** [comment]
@matthamil  lol -  im not too familiar with navigation thing,, could you point to some example where i can see tabs + drawer working together ?

**Comment by matthamil** [comment]
You can open the drawer in the Drawer + Tabs example by swiping from the left side of the screen to the right to reveal it.

**Comment by jpca999** [comment]
resolved thanks 


thank you,
Jay
