### ISSUE TITLE
react-native-scrollable-tab-view transit slow in  android at react-navigation beta-0.11

### ISSUE THREAD

**Issue by cielu** [react-community/react-navigation#2011]
before  I upgrade react-navigation from beta-0.9 to react-navigation beta-0.11 , react-native-scrollable-tab-view do well at android when I use tabNavigator  .

use tabNavigator ;

Do well version : 

react-navigation@beta-0.9
react-native-scrollable-tab-view@0.6.7

wrong version : 
react-navigation@beta-0.11
react-native-scrollable-tab-view@0.6.7

**Comment by spencercarli** [comment]
`react-native-scrollable-tab-view` isn't used in this project. Check other updates you made to your project as I don't think your issue is related to this project
