### ISSUE TITLE
Custom background colour for a tab

### ISSUE THREAD

**Issue by elizamaria** [react-community/react-navigation#2015]
Hy, I would like to know how I could add a custom background colour for a specific tab, using TabNavigator as I've seen that from Screen Navigation Options I can't access any option regarding the tab styling, only icon/label. Is there any way? 

![screen shot 2017-06-27 at 17 24 34](https://user-images.githubusercontent.com/15130574/27592617-95af271a-5b5d-11e7-9811-9eb587833c97.png)

Expected behaviour: 
```
export default class AddScreen extends Component {
static navigationOptions = ({ navigation, screenProps }) => ({
    tabBarIcon: ({ focused }) => (
      <Image
        source={Images.ADD}
      />
    ),
    style: {
     backgroundColor: 'blue',
    },
  });
}
```

**Comment by Mimble-Wimble** [comment]
You will want to wrap `style` in `tabBarOptions` like so:

```
tabBarOptions: {
  style: {
     backgroundColor: 'blue',
  }
}
```

You have additional options to play around with the tabs behavior as well such as activeTintColor, inactiveTintColor, etc. Those options can be seen here (https://reactnavigation.org/docs/navigators/tab).

**Comment by elizamaria** [comment]
I use tabBarOptions in the TabNavigator constructor for the white background and it will apply the color to all the tabs. But i don't think that i can access tabBarOptions from a screen. On the page it says that the only available Screen Navigation Options are title, tabBarVisible, tabBarIcon, tabBarLabel.

**Comment by matthamil** [comment]
It looks like this is currently not supported in react navigation without creating your own custom [tabBarComponent](https://reactnavigation.org/docs/navigators/tab). The default `TabBarBottom`: https://github.com/react-community/react-navigation/blob/89db9ea2046fde59fd01b463364398addab36c31/src/views/TabView/TabBarBottom.js#L123-L173 although you could create a similar custom tab bar component with the added functionality you are looking for.

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
