### ISSUE TITLE
params.navigation.state.routeName gives all available route Names with Meteor

### ISSUE THREAD

**Issue by LukasNavickas** [react-community/react-navigation#2017]
My Stack and Tab Navigators

```
export const FeedStack = StackNavigator({
  Jobs: {
    screen: EmployeeList,
    navigationOptions: {
      header: {
        visible: false,
      },
    },
  },
  Studies: {
    screen: EmployeeList,
    navigationOptions: {
      header: {
        visible: false,
      },
    },
  },
  ProjectDetail: {
    screen: ProjectDetail,
    navigationOptions: {
      title: ({ state }) => state.params.title,
    },
  },
});


export const Tabs = TabNavigator({
  Jobs: {
    screen: FeedStack,
    navigationOptions: {
      title: 'Jobs',
    },
  },
  Studies: {
    screen: FeedStack,
    navigationOptions: {
      title: 'Studies',
    },
  }, 
  tabBarOptions: {
    labelStyle: {
        fontSize: 12,
    },
    tabStyle: {
        width: 90,    
    },
  },
});
```

### Current Behavior
I have createContainer (from Meteor) in the component EmployeeList. I would like to get the routeName (tab I'm currently in), so I could subscribe to the right Meteor collection. However, whenever I change a tab, params.navigation.state.routeName returns 'Jobs' 'Studies' 'Jobs' 'Studies' (both twice) and my Meteor app subscribes to both collections. 

### Expected Behavior
params.navigation.state.routeName gives only the current route (tab) and my Meteor app can easily subscribe only to that collection.

"react": "15.4.2",
"react-native": "0.42.3",
"react-navigation": "^1.0.0-beta.7"
| npm|

**Comment by matthamil** [comment]
I believe this is due to the fact that you are rendering the same `FeedStack` twice in your `TabNavigator`. This will mount the stack and it's components twice, which explains the duplicate 'Jobs', 'Studies', 'Jobs', 'Studies'.

**Comment by LukasNavickas** [comment]
I did create a new StackNavigator for Studies, but I get a very similar result.

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
