### ISSUE TITLE
Login Screen user can slide back to it 

### ISSUE THREAD

**Issue by AlmogRnD** [react-community/react-navigation#2022]
I have my navigation setup using React Navigation, which works fine, however, I have a login screen/view once user logins they can slide back to that screen is there a way to disable that or am I doing it wrong. 

My router 

```
// Native tab navigation
export const TabsNavigation = TabNavigator({
    Home: {
        screen: Home,
        navigationOptions: {
            tabBarLabel: 'Home',
            tabBarIcon: ({ tintColor }) => <Icon name="home" size={28} color={tintColor} type={"font-awesome"} />
        },
    },
    Photos: {
        screen: Photos,
        navigationOptions: {
            tabBarLabel: 'Photos',
            tabBarIcon: ({ tintColor }) => <Icon name="camera" size={28} color={tintColor} type={"font-awesome"} />
        },
    },
    SiteDiary: {
        screen: SiteDiary,
        navigationOptions: {
            tabBarLabel: 'Site Diary',
            tabBarIcon: ({ tintColor }) => <Icon name="cog" size={28} color={tintColor} type={"font-awesome"} />
        },
    },
});

// Main navigation StackNavigator
export const MainScreenNavigator = StackNavigator({
    Login: {
        screen: Login,
        navigationOptions: {
            title: "Login",
            headerLeft: null
        },
    },
    ResetPassword: {
        screen: ResetPassword,
        navigationOptions: {
            title: "Reset Password",
            headerLeft: null
        },
    },
    Drawer: { 
        screen: MainDrawerNavigator
    },
    Home: {
        screen: TabsNavigation,
        navigationOptions: {
            title: "Home",
            headerLeft: null,
        }
    }
});
```

My index file 
```
class App extends Component {
    render() {
        return <MainScreenNavigator />
    }
}

export default App;
```

Here is the issue 
![login-screen-issue](https://user-images.githubusercontent.com/169507/27672569-ad322506-5c50-11e7-9d00-66f5a2655aa9.gif)

**Comment by jurajkrivda** [comment]
I could recommend you to split your router into two parts. SignedIn (StackNavigator with Tabs) part and SignedOut part (Login, SignUp etc.)

**Comment by AlmogRnD** [comment]
For the SignedOut part (Login, SignUp etc.) just use StackNavigator and how would you load between the different parts?

**Comment by jurajkrivda** [comment]
Look at my solution

```
class Layout extends Component {
	render() {
		const { userId } = this.props;

		return <View style={{ flex: 1 }}>
			<StatusBar
				backgroundColor={ AppColors.brand.primary }
				barStyle="light-content"
			/>
			{ userId ? <SignedIn /> : <SignedOut /> }
		</View>
	}
}
```

**Comment by AlmogRnD** [comment]
Sorry, this is not clear, a bit incomplete can you send the router?

**Comment by jurajkrivda** [comment]
Here you are:

SignedOut.js

```
export default StackNavigator({
	Login: {
		screen: Login,
		navigationOptions: {
			title: "Sign In"
		}
	},
	...
});
```

SignedIn.js

```
export default StackNavigator({
	Tabs: {
		screen: Tabs,
	},
	}, {
		initialRouteName: 'Tabs',
	}
);
```

**Comment by helloyou2012** [comment]
```
const AppNavigator = ({ auth }) => {
  if (auth.isLogin) {
    return <MainNavigator />;
  }
  return <LoginNavigator />;
};
```

**Comment by jinziyi** [comment]
Here is my solution.
`export const App = props => <View style={{flex: 1}}>{props.isLogin ? <Main/> : <Login/>}</View>;`

**Comment by jurajkrivda** [comment]
@helloyou2012 and @jinziyi your example is the same as mine.

**Comment by helloyou2012** [comment]
@jurajkrivda yes, I just make it clear 🙂

**Comment by AlmogRnD** [comment]
@jurajkrivda thanks, this is really great appreciate the help, once a user logins how do you navigate to the correct view I had the following  

 `this.props.navigation.dispatch(navigateActionHome)`

```
// Navigation
const navigateActionHome = NavigationActions.navigate({
    routeName: 'Home',
    params: {},
    action: NavigationActions.navigate({ routeName: 'Home'})
})
```

But it's not working with the changes

**Comment by jurajkrivda** [comment]
```
props.navigation.navigate('Home');
```

**Comment by AlmogRnD** [comment]
@jurajkrivda that doesn't do anything here is my updated code 

Router.js
```
// Drawer Navigation
export const MainDrawerNavigator = DrawerNavigator({
    Home: {
        screen: Home,
        navigationOptions: {
            drawer:{
                label: "Home",
            }
        },
    },
    Logout: {
        screen: Logout,
        navigationOptions: {
            drawer:{
                label: "Logout",
            }
        },
    }
});


// Native tab navigation
export const TabsNavigation = TabNavigator({
    Home: {
        screen: Home,
        navigationOptions: ({ navigation }) => ({
            tabBarLabel: 'Home',
            headerLeft : <DrawerIcon navigation={navigation} />,
            tabBarIcon: ({ tintColor }) => <Icon name="home" size={28} color={tintColor} type={"font-awesome"} />
        }),
    },
    Photos: {
        screen: Photos,
        navigationOptions: {
            tabBarLabel: 'Photos',
            tabBarIcon: ({ tintColor }) => <Icon name="camera" size={28} color={tintColor} type={"font-awesome"} />
        },
    },
    SiteDiary: {
        screen: SiteDiary,
        navigationOptions: {
            tabBarLabel: 'Site Diary',
            tabBarIcon: ({ tintColor }) => <Icon name="cog" size={28} color={tintColor} type={"font-awesome"} />
        },
    },
});


// Main navigation StackNavigator
export const MainScreenNavigator = StackNavigator({
    Home: {
        screen: TabsNavigation,
        navigationOptions: {
            title: "Home",
            //headerLeft: null,
        },
    }
});

// Public navigation StackNavigator
export const PublicScreenNavigator = StackNavigator({
    Login: {
        screen: Login,
        navigationOptions: {
            title: "Login",
            headerLeft: null
        },
    },
    ResetPassword: {
        screen: ResetPassword,
        navigationOptions: {
            title: "Reset Password",
            headerLeft: null
        },
    }
});
```

index.js
```
class App extends Component {
    render() {
        const { userId } = this.props;
        return <View style={{ flex: 1 }}>
            <StatusBar
                barStyle="light-content"
            />
            { userId ? <MainScreenNavigator /> : <PublicScreenNavigator /> }
        </View>
    }
}

export default App;
```

Login, paricle 
```
 // Use Api Utils to handle fetch status check, known issue with fetch api
                .then(ApiUtils.checkStatus)
                .then(response => response.json())
                .then((res) => {
                    alert(`Success!`)
                    AsyncStorage.setItem('jwt', res.token)

                    // Redirect to home screen
                    //this.props.navigation.dispatch(navigateActionHome)
                    this.props.navigation.navigate('Home');
                })
                .catch(() => {
                    alert('There was an error logging in.');
                })
                .done()
        } else {
            // Form validation error
            alert('Please fix the errors listed and try again.')
        }
```

**Comment by jurajkrivda** [comment]
If anyone uses Recompose 

```
import { compose, branch } from 'recompose';


const withUser = connect(state => ({ userId: state.user.id }));


const displaySignedIn = branch(
  (props) => props.userId,
  renderComponent(SignedIn),
);

export default compose(
	withUser,
	displaySignedIn
)(SignedOut)
```

**Comment by AlmogRnD** [comment]
@jurajkrivda thanks very much I got it working

**Comment by AlmogRnD** [comment]
Never mind I was unable to get it to work, I'm not sure your example is correct. Once I login I can't get it to navigate to the correct view.

**Comment by AlmogRnD** [comment]
The issue is with the following code 

{ userId ? <SignedIn /> : <SignedOut /> } 

Once the app is loaded it only loads one of the navigation <SignedIn /> or <SignedOut /> if so it never loads the other nav and you can't navigate to it 

I'm not sure how you it working on your app

**Comment by jurajkrivda** [comment]
I recommend you use Redux for holding the user state and then you can easily do switch between layouts. You don't need navigate to the Home page after `AsyncStorage.setItem('jwt', res.token)`

**Comment by jurajkrivda** [comment]
Btw this is more sexy:

```
try {
	const status = await ApiUtils.checkStatus;
	await AsyncStorage.setItem('jwt', status.token);
	...
} catch (e) {
	console.log
}
```

**Comment by migueloller** [comment]
I'm not sure why there are such complicated suggestions in this thread but the API allows for this with the [`gesturesEnabled`](https://reactnavigation.org/docs/navigators/stack#gesturesEnabled) navigation option.

```js
static navigationOptions = {
  gesturesEnabled: false,
}
```

**Comment by AlmogRnD** [comment]
Wanted to send out a quick update, I appreciate everyone's help and thanks. I would say that react navigation is a nightmare very disappointing. I did add redux and had the same issue as I did without it, the only to really fix it is using gesturesEnabled: false @migueloller thanks. I'm not sure this is really good more of a workaround and you lose some of the native functionality. 

Also really no good examples showing complex navigation. And I would redux add more issues. 

At this stage, there is no way to really have sepicatrion between different navs.

**Comment by MrHubble** [comment]
@migueloller I wasn't aware of `gesturesEnabled` so thanks for that. However, this interferes with the Drawer navigation. The reason I'm trying to stop the back swipe is because in the iOS Simulator I try to swipe open the drawer but it often invokes the back action instead which makes debugging difficult. I think if I could simply disable the back action for that one screen that would suffice. I don't think that option is currently available.

**Comment by migueloller** [comment]
@MrHubble,

Yeah, you can control `gesturesEnabled` per screen but I haven't looked at its interaction with the drawer navigation.

@AlmogRnD,

I do agree that there is a lack of resources available online to build complex navigation systems with React Navigation. Hopefully with time the documentation will get better and there will be some more resources out there on how to achieve complex navigation use cases.

For now, keeping in mind that the library isn't feature complete and looking at the source when attempting to build for complex use cases looks like the way to go. This unfortunately isn't the most desirable way but there are people working hard on this so we just have to be patient and grateful of their work.

**Comment by ratelgogo** [comment]
@jurajkrivda any suggestion if without redux?

**Comment by JeremyZheng** [comment]
@jurajkrivda  ， How do you handle this scenario:
Index scene do not need to login, but when I navigate to a tab or another scene, login scene should show out and after login then go to the tab or scene (not navigate to home).

Need your suggestions, thanks!

**Comment by Jerameel** [comment]
For people having a hard time implementing the login. Here is a template,
https://github.com/Jerameel/ReactNativeLogin

**Comment by sarykemmoun** [comment]
@migueloller A big thanks!
I've almost tried the complex suggestions when suddenly I've seen your useful answer.
