### ISSUE TITLE
routes array in navigationOptions of StackNavigator

### ISSUE THREAD

**Issue by pgengoux** [react-community/react-navigation#2023]
Hi,

I want to get the routes state array in the StackNavigator's global navigationOptions function in order to render a custom LeftButton hamburger menu when routes.count > 1

The current output of 
```
var AppNavigator = StackNavigator( 
{
  {
    WelcomeView: {screen: WelcomeView},
    SecondView: {screen: SecondView}
  },
  {
    cardStyle: {
      backgroundColor: 'white',
  },
  navigationOptions: ({navigation}) => { 
    console.log(navigation.state);
    return {...}
  }
});
```

=>

```
{ 
  key: 'id-123456',
  params: undefined,
  routeName: 'WelcomeView'
}
```

Is there a way to access the route state array to determine the current navigation level within the navigationOptions function of the stack navigator?

I am using redux, I have the route array state in my store, but I cannot access it in the definition of the StackNavigator constructor function.

**Comment by mantas-janulionis** [comment]
Have you tried adding it to screenProps?
```
<YourNavigator screenProps={nav:this.props.nav} />

...
const mapStateToProps = (state) => ({
  nav: state.nav // your navigation reducer
...
})
```

You should be able to pass a complete navigation state. Then you can access it like
```
  navigationOptions: ({navigation, screenProps}) => { 
    console.log(screenProps.nav)
    return {...}
  }
```

You can read more about screenProps [in the docs](https://reactnavigation.org/docs/navigators/stack)

**Comment by pgengoux** [comment]
You are a life saver! 
It worked using screenProps in the render method of the component rendering the StackNavigator!  :)
