### ISSUE TITLE
Transition background color

### ISSUE THREAD

**Issue by bernatbombi** [react-community/react-navigation#2026]
When transitioning from one Screen to another (either using card or modal mode), there's a white background that transitions its alpha from 0 o 1, during the screen to screen animation.

I'd like to know how to change the color, if possible.

![Screenshot](https://preview.ibb.co/eZURTQ/telegram_cloud_file_4_431807530_164558_7308204946965615270.jpg)
---
### Environment
* React Native Navigation version: 1.0.0-beta.11
* React Native version: 0.45.1
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iOS 10.3, iPhone 6

**Comment by kantharia** [comment]
I am having a similar issue. I am using `StackNavigator` while transitioning from one screen to another screen flickers with white background 
![screenflicker](https://user-images.githubusercontent.com/8065874/27816578-05db5508-60aa-11e7-910c-6bdec254c02c.gif)

**Comment by kumarpatel** [comment]
+1 on this. How do we override this?

**Comment by skizzo** [comment]
Hi,
I've tried about anything with this cardStyle property (including the suggested solution by @kumarpatel) but my screens still have the same flicker as mentioned by @kantharia. In other words: **I can't find any working way of changing the "overlay behaviour" during transitions of my screens**. Using  v1.0.0-beta.11:

![screen-shot-2017-08-27-at-11 51 02- 2](https://user-images.githubusercontent.com/2892572/29748832-5c559634-8b1e-11e7-9b5b-2a8f8ed8662c.jpg)



Any ideas why this might not work?

**Comment by Jobeso** [comment]
It seems like react navigation is using the root view background color. You can change it like this: [https://moduscreate.com/changing-the-react-native-rootview-background-color-ios-and-android/](url)
This also includes your starting screen color when transitioning from the launch screen to your first react-native screen.
But this is not an option for me because I want different colours for the navigation animation.

**Comment by sawwy** [comment]
That article is from Dec 2015 and at least in my android source, the MainActivity.java does not have the mReactRootView method when I search. Using the latest React Navigation. Is my file

**Comment by danieldelouya** [comment]
Having same issue. White flashes when pushing to new screen. Tried setting cardStyle bg

**Comment by danieldelouya** [comment]
This has been open since June. Seriously no fix yet?

**Comment by sawwy** [comment]
Hi,

You can set the cardStyle opacity to 1 which removes the white ("opacity: 0") flickering. 
https://github.com/react-community/react-navigation/issues/619#issuecomment-285137424

const AppNav = StackNavigator(
  {
    startupTasks: { screen: StartUpTasks },
    auth: { screen: Login },
    main: { screen: DrawerNav },
  },
  {
    cardStyle: {
      opacity: 1,
    }
  }
);

Works for me on Android (virtual and physical):
react-navigation@1.0.0-beta.12
react-native@0.48.2
react@16.0.0-alpha.12

**Comment by kelset** [comment]
Pinging OP @bernatbombi since this issue has not been active for a while, and it's related to an old version of the lib. Moreover solution proposed by @sawwy seems valid.

Please let me know if you want this to remain open; if I get no answer in the next 7 days I will close it.

**Comment by kelset** [comment]
Hi there @bernatbombi,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.

**Comment by flyskywhy** [comment]
When use DrawerNavigator and StackNavigator, need:

    cardStyle: {
        backgroundColor: 'transparent',
    },

and need:

use [react-native-root-view-background](https://github.com/johniak/react-native-root-view-background) to setRootViewBackgroundColor('black')

**Comment by jordangrant** [comment]
https://medium.com/@Krizzu/how-to-change-background-color-of-rootview-in-react-native-3279417c34bb

**Comment by kkx64** [comment]
Solved by adding

```
<View style={{ 
    position: 'absolute',
    height: '100%', 
    width: '100%', 
    backgroundColor: <whatever-color-you-want> 
 }}/>
```

above <Stack.Navigator>

**Comment by MahamidRawi** [comment]
@flyskywhy  Where Do I add the card style property exactly ?

**Comment by flyskywhy** [comment]
> @flyskywhy Where Do I add the card style property exactly ?

https://reactnavigation.org/docs/4.x/stack-navigator/#cardstyle

**Comment by webersilv4** [comment]
**define property animation with none**
<Navigator
                initialRouteName='Home' 
                screenOptions={{ 
                    headerShown: false,
                    statusBarColor: '#FFF',
                    animation: 'none'
                }}>
