### ISSUE TITLE
Listview not shown until scroll when added into Tab - IOS only

### ISSUE THREAD

**Issue by ydydxhg** [react-community/react-navigation#2027]
HI All,

I am experiencing an issue where the listview content is not shown until scrolled, when I put the listview into a StackNavigation which sits in a TabNavigation. this is only happening in IOS, android is fine. I am wondering if any one has such problem?

so basically i have: 
```

export const ArtworkStack = StackNavigator({
    List:{
        screen: ArtworkList,
        navigationOptions: {
            title: SystemStrings.Artworks
        }
    },
    Detail: {
        screen: ArtworkDetail,
        navigationOptions: ({navigation}) => ({
            title: navigation.state.params.name.toUpperCase(),
            id:  navigation.state.params.id,
            description:  navigation.state.params.description
        })
    }
});

export const MainScreenNavigator = TabNavigator({
  Home: { 
        screen: Home,
        navigationOptions: {
        tabBarLabel: SystemStrings.Home,
        tabBarIcon: ({ tintColor }) => <Icon name="home" size={30} color={tintColor} />,
        },
    },
  Artworks: { 
        screen: ArtworkStack, 
        navigationOptions: {
            tabBarLabel: SystemStrings.Artworks,
            tabBarIcon: ({ tintColor }) => <Icon name="list" size={30} color={tintColor} />,
        },
    },
  Map: { 
        screen: Map , 
        navigationOptions: {
            tabBarLabel: SystemStrings.Map,
            tabBarIcon: ({ tintColor }) => <Icon name="map" size={30} color={tintColor} />,
        },
    }
});
```

and in the ArtworkList page, my render method looks like:

    render() {
        return (
        <View  style={styles.view}>
            <ListView ref="listView"
                dataSource={this.state.dataSource}
                renderRow={(rowData) => 
                    <TouchableHighlight onPress={() => this.onClickDetail(rowData)} >
                        <View  style={localStyles.list} >
                            <View  style={localStyles.row}>
                                <Image source={ rowData.url } style={localStyles.image}/>
                            </View>
                            <View  style={localStyles.row}>
                                <Text style={localStyles.rowTitle}>
                                    {rowData.name}
                                </Text>
                                <Text>
                                    {rowData.description}
                                </Text>
                                
                                <Text>
                                    {rowData.distanceText}
                                </Text>
                            </View>
                        </View>
                    </TouchableHighlight>
                }>

            </ListView>
        </View>
        );
    }

if I show the listview page on its own, i.e. not putting it into tab nav or stack nav, it shows just fine. So i guess there is something going on when i put it into the nested structure.

| software         | version
| ---------------- | -------
| react-navigation |  v1.0.0-beta.l1
| react-native     |  0.44
| node             | 7.4.0
| npm or yarn      | 5.0.4

Could someone point me to the right direction please? 
Many thanks

Paul

**Comment by WFNeIn** [comment]
I met same issue,too.How to solve it.

**Comment by jurajkrivda** [comment]
You can try put `flex:1` into styles.view

**Comment by ydydxhg** [comment]
Hi @jurajkrivda, thanks so much for your reply, unfortunately, adding flex:1 didnt help. Let me post the whole styling here:
'
export default StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
  view:{
    paddingTop: 40,
    flex:1
  }
})

const localStyles = StyleSheet.create({
  list: {
    flex: 1,
    flexDirection: 'row'
  },
  row: {
    flex: 1,
    flexDirection: 'column',
    height: 170,
    marginLeft: 10,
    marginRight: 10
  },
  image: {
      width: 150,
      height: 150
  },
  rowTitle: {
      fontSize: 18,
      fontWeight: 'bold'
  }
});
'

**Comment by ydydxhg** [comment]
I have a gut feeling that this might be a bug in the control when you nest stack Nav inside a Tab Nav, rather than a styling issue. coz if I show the artworkList page as my home page,i.e. not inside the tabNavigator or stack Nav, it shows ok, If i show the ArtworkList page inside a stackNavigator but not in a Tab, it shows ok.

**Comment by DCKT** [comment]
Hi, I get same behavior, `flex: 1`still doesn't work. Someone has an idea about this ?

**Comment by ydydxhg** [comment]
@DCKT how was your code placed? i.e. any nested navs or a simple view in a stack or tab?

**Comment by DCKT** [comment]
@ydydxhg Yes I have a `ListView` in a `TabNavigator` screen which is in `StackNavigator`

**Comment by ydydxhg** [comment]
looks like as soon as you nest 2 Navs it will cause issue with list view or scroll view. I tried with scroll view as well, same problem

**Comment by ydydxhg** [comment]
Any one know how to simulate a scroll action? just as a workaround until the bug is fixed, :P

**Comment by augustoabreu** [comment]
Use `removeClippedSubviews={false}` param of `ListView`

**Comment by ydydxhg** [comment]
Thanks @augustoabreu, I tried that, didn't help

**Comment by jurajkrivda** [comment]
@ydydxhg try to delete TouchableHighlight from your row.

**Comment by ydydxhg** [comment]
@jurajkrivda, i did change it to a view just to see, didnt fix it

**Comment by DCKT** [comment]
Hey @augustoabreu it works for me, thanks !

**Comment by ydydxhg** [comment]
HI @augustoabreu, I tried your code again, and it turns out I lied, lol. removeClippedSubviews={false} does fix the issue. I wonder what did i do wrong the first time.

Thanks so much!!!

**Comment by augustoabreu** [comment]
@DCKT @ydydxhg You're welcome! Don't forget to close the issue ;)

**Comment by arunprasathsivasamy** [comment]
Hey @augustoabreu it works for me, thanks !
