### ISSUE TITLE
When Custom a TabBar, switch TabBar will rerender other screen

### ISSUE THREAD

**Issue by lxooxl** [react-community/react-navigation#2030]
### Current Behavior

```
const CustomTabRouter = TabRouter({
    Deliver: { screen: Deliver },
    Pick: { screen: Pick },
    Store: { screen: Store },
    Profile: { screen: Profile },

}, { 
    initialRouteName:'Deliver',
    tabBarOptions: {
        tabBarPosition: 'bottom',
        lazy: true,
    }
});
```

tabBarOptions lazy not effect ;

but if I don't use CustomTab
```
const TabBarNav = TabNavigator({
    Deliver: { screen: Deliver },
    Pick: { screen: Pick },
    Store: { screen: Store },
    Profile: { screen: Profile },
},{
    tabBarOptions: {
        tabBarPosition: 'bottom',
        lazy: true,
    }
})
```

the screen don't reRender,
how to let custom tabBarOptions lazy have effect

###  Environment
Environment iOS

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.11
| react-native     |  0.44.3
| node             |  7.9.0
| npm      | 4.2.0

**Comment by matthamil** [comment]
For TabRouter to have a lazy-loading effect, you need to specify [getScreen](https://reactnavigation.org/docs/routers/tab). Lazy-loading is configured by setting `lazy` to `true` for TabNavigators.
