### ISSUE TITLE
navigate to parent navigator screen from drawer

### ISSUE THREAD

**Issue by tsmrafee-bs** [react-community/react-navigation#2034]
I have a drawer navigator inside a stack navigator.

the stack navigator has a screen named "profile".

I need to add a button in the drawer that will navigate to the "profile" screen.

How can i do this?

**Comment by spencercarli** [comment]
You can use the [`onPress`](https://reactnavigation.org/docs/navigators/drawer#contentOptions-for-DrawerItems) function to handle this. Check if the route is correct and if so take the appropriate action.
