### ISSUE TITLE
navigationOptions function is not called by setParams

### ISSUE THREAD

**Issue by musicode** [react-community/react-navigation#2038]
I have a Tab navigator. 

when i call setParams, the tab label is not update.

createNavigationContainer  179l

```js
const nav = Component.router.getStateForAction(action, state.nav);
```

StackRouter 248l

```js
const childRouter = childRouters[childRoute.routeName];
// childRouter is null
```

how to update tab bar?

**Comment by musicode** [comment]
anyone can help me?

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
