### ISSUE TITLE
Nested navigators in redux with components in between

### ISSUE THREAD

**Issue by jjant** [react-community/react-navigation#2041]
Hi, I'm trying to set up my navigators which look like this:

```jsx
const AppNavigator = TabNavigator({
  User: { screen: UserScreen },
});

const AppWithNavigationState = ({ dispatch, navigation }) => (
  <AppNavigator
    navigation={addNavigationHelpers({ dispatch, state: navigation })}
  />
);

const mapStateToProps = state => ({
  navigation: state.navigation,
});

export default connect(mapStateToProps)(AppWithNavigationState);

// reducer

const initialNavState = AppNavigator.router.getStateForAction('Channel');

class NavigationReducer {
  static reduce(state = initialNavState, action) {
    const nextState = AppNavigator.router.getStateForAction(action, state);
    return nextState || state;
  }
}

export default NavigationReducer.reduce;

```

```jsx
const UserScreen = ({ dispatch }) => (
  <View>
    <Text>User screen</Text>
    <GroupNavigator />
  </View>
);

export default connect()(UserScreen);
```

```jsx
const GroupNavigator = StackNavigator({
  GroupList: { screen: GroupList },
  GroupDetail: { screen: GroupDetail },
}, {
  headerMode: 'none',
  initialRouteName: 'GroupList',
});

export default GroupNavigator;
```

Now, I understand that if I nest navigators directly as screens of other navigators, this works automatically, and the state is correctly stored under a single key in my store, but when there are components in between, like `UserScreen` here, I don't understand how to set this up. Should I create a whole new reducer for this?

Perhaps the docs could be improved to show what to do in this case.

**Comment by bristoljon** [comment]
Same problem here. The initial state is not populated with nested routes in these cases.

I tried passing all received props down to the nested navigator e.g. `<GroupNavigator {...this.props} />` but  errored with:

`Invariant Violation: This navigator has both navigation and container props, so it is unclear if it should own its own state. Remove props: "getInitialDevicesData, cancelDataSync, startDataSync" if the navigator should get its state from the navigation prop. If the navigator should maintain its own state, do not pass a navigation prop.`

The props mentioned are the actions creators I need the screen to call on mount and unmount. If I avoid passing them down to the navigator I get:

`Cannot read property 'find' of undefined at DrawerView._this._updateScreenNavigation`

If I nest the navigator directly, the nav state tree populates correctly but I'm unable to call the actions I need to when the screen mounts and unmounts.

Sorry to bump thread, not looking for specific answers to my case. Just what the right approach is for nested navigators or, more specifically, non-directly nested navigators..

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!

**Comment by Luomusha** [comment]
docs writes nothing about this.
I have same problem.

**Comment by alexeymolchan** [comment]
same problem here

**Comment by sven0726** [comment]
same problem here

**Comment by kelset** [comment]
@sven0726 @alexeymolchan @Luomusha check this section of the [README](https://github.com/react-community/react-navigation#community-contributions), in particular, [this article](React-Navigation, complete Redux state management, tab-bar, and multiple navigators).

**Comment by alex-gunning** [comment]
Same problem here. I've been trying to solve this with Higher-order components. I'll report back if I have any luck. This is a pretty common use-case I imagine.

**Comment by brentvatne** [comment]
@alex-gunning - can you create a new issue that reproduces this problem with a minimal, runnable project on snack or github? thanks!
