### ISSUE TITLE
NavigationActions navigates incorrectly when TabNavigator is nested in DrawerNavigator

### ISSUE THREAD

**Issue by baldurpan** [react-community/react-navigation#2043]
I believe I have found a bug when nesting TabNavigator in DrawerNavigator when using the same screen in multiple tabs.
In this example I'm using the screen "ProfileScreen" in both Tab1 and Tab2 and in Tab3 I have a button that should navigate to Tab2 -> ProfileScreen. This works perfectly if I only use TabNavigator but when It's nested in a DrawerNavigator, the navigator sends me to Tab1 -> ProfileScreen.

Here's my example App.js
```
import React from 'react';
import { StyleSheet, Text, View, Button } from 'react-native';
import { DrawerNavigator, TabNavigator, StackNavigator, NavigationActions } from 'react-navigation';

const ProfileScreen = () => {
  return (
    <View>
      <Text>This is profile</Text>
    </View>
  )
}

const Tab1Navigator = StackNavigator({
  Main: {
    screen: () => {
      return (
        <View>
          <Text>Main screen in tab 1</Text>
        </View>
      )
    },
  },
  Profile: {
    screen: ProfileScreen,
  },
});

const Tab2Navigator = StackNavigator({
  Main: {
    screen: () => {
      return (
        <View>
          <Text>Main screen in tab 2</Text>
        </View>
      )
    },
  },
  Profile: {
    screen: ProfileScreen,
  },
});

const Tab3Navigator = StackNavigator({
  Main: {
    screen: (props) => {
      return (
        <View>
          <Text>Main screen in tab 3</Text>

          <Button title="Take me to profle in tab2" onPress={() => {
            props.navigation.dispatch(NavigationActions.navigate({
              routeName: 'Tab2',
              params: {},
              action: NavigationActions.navigate({
                routeName: 'Profile',
              }),
            }));
          }}/>
        </View>
      )
    },
  },
});

const Tabs = TabNavigator({
  Tab1: {
    screen: Tab1Navigator,
  },
  Tab2: {
    screen: Tab2Navigator,
  },
  Tab3: {
    screen: Tab3Navigator,
  },
}, {
  lazy: true,
  tabBarPosition: 'bottom',
  tabBarOptions: {
    showIcon: false,
    activeTintColor: '#e91e63',
  },
});

const Drawer = DrawerNavigator({
  Tabs: {
    screen: Tabs,
  },
}, {
  contentComponent: () => <View />
});

export default class App extends React.Component {
  render() {
    return <Drawer />
  }
}
```

### Current Behavior
Button in Tab3 using NavigationActions sends me to Tab1 -> ProfileScreen

### Expected Behavior
Button in Tab3 using NavigationActions should be sending me to Tab2 -> ProfileScreen

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.11
| react-native     |  0.45.1
| node             | 8.1.2
| npm or yarn      | yarn 0.24.6

**Comment by kelset** [comment]
Pinging OP @baldurpan since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open; if I get no answer in the next 7 days I will close it.

**Comment by kelset** [comment]
Hi there @baldurpan ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.
