### ISSUE TITLE
createConfigGetter tries to stringify route causes 'Converting circular structure to JSON'

### ISSUE THREAD

**Issue by ppong** [react-community/react-navigation#2044]
This line in createConfigGetter https://github.com/react-community/react-navigation/blob/master/src/routers/createConfigGetter.js#L68 tries to call JSON.stringify on the route is problematic. It prevents users from passing javascript object params. This sometimes results in the error: Converting circular structure to JSON

**Comment by mikemurray** [comment]
Having this same issue as well. For now to resolve the issue I have to flatten my params object.

**this:**
```
{
  param1: "value 1",
  param2: {
    param2_1: value 2
  }
}
```

**become this:**
```
{
  param1: "value 1",
  param2_1: value 2
}
```

The problem doesn't happen for me on the initial route pushed, but the next route.

**Comment by m-vdb** [comment]
this issue has been blocking me for the past week. I thought I did something wrong and re-installed different versions of my dependencies, but I am now convinced that this code is bugged. `createConfigGetter` shouldn't call `JSON.stringify` on an object as complex as a `route` and it is sad that the code is evaluated every time even if the `invariant()` call is ok.  I've had to modify the source code of the module to bypass that.

Note: I'm using `react-native-router-flux`, so maybe it's not 100% the fault of `react-navigation` but I think this comment is still relevent 😄

**Comment by farhanmannan** [comment]
I'm getting this issue using pure `react-navigation` (not using `react-native-router-flux` like @m-vdb). 

@mikemurray did you flatten the params object programmatically?

**Comment by wschurman** [comment]
One workaround is to override `toJSON` in the object that is being passed as a navigate param.

**Comment by mikemurray** [comment]
@farhanmannan Sorry for just seeing this. No, I flattened them manually if the problem occurs. Most of my data is in redux, so I can get away with less complex structures in navigation.

**Comment by m-vdb** [comment]
I don't control exactly "what is passed as a navigation parameter" because i use a library on top of this one. But I truly believe that debug code shouldn't try to convert objects to JSON. That's just bad practice and decreases performances

**Comment by selsamman** [comment]
I was having this problem because I store my component in SetParams.  This allows me to access component state, props and methods from within my header which is really convenient but I worry about passing in complex objects.  For now using the toJSON method of dealing with this specific issue.  Most of my data is also in Redux.

**Comment by ppong** [comment]
What's currently on master is no longer an issue for me now. https://github.com/react-community/react-navigation/blob/1b761cf9d1a82a62255976080c81612e25bc896f/src/routers/createConfigGetter.js#L68 `JSON.stringify` is no longer called on the route unless `!route || !routes || index == null`.

**Comment by m-vdb** [comment]
AMAZING!

**Comment by vonovak** [comment]
you don't need to use master, just the latest release. this was fixed in https://github.com/react-community/react-navigation/pull/2693
