### ISSUE TITLE
Custom tabBar connect to my redux store is not visible

### ISSUE THREAD

**Issue by claudioviola** [react-community/react-navigation#2045]
### Current Behavior
When I connect my custom tabBar to my redux store with 
`export default connect(mapStateToProps, null)(TabBar);` my tab bar is not visible.
I need it to get some data about user to pass params in some screens.

### Expected Behavior
I would to show tab bar with connect to my store. I don't have the navigation state connect to my redux store. I don't think that is necessary for me.

| software         | version
| ---------------- | -------
| react-navigation |  react-navigation@1.0.0-beta.11
| react-native     |  0.45.0
| node             |  4.2.0
| npm or yarn      | 0.21.3

This is my routing configuration
`

export const Router = TabNavigator({
    root: { screen: RootScreen },
    welcome: { screen: WelcomeScreen },
    auth: { screen: AuthScreen },
    main: {
        screen: TabNavigator({
            home: {
                screen: HomeScreen,
            },
            chapterEditorScreen: {
                screen: ChapterEditorScreen
            },
            userProfile: {
                screen: StackNavigator({
                    userProfileScreen: { screen: UserProfileScreen },
                    settings: { screen: SettingsScreen }
                })
            },
        }, {
            tabBarComponent: TabBar,
            initialRouteName:'home',
            lazy: false,
            tabBarPosition: 'bottom',
            tabBarOptions: {
                /*showIcon: true,
                showLabel: false*/
            }
        })
    },
}, {
    initialRouteName: 'root',
    navigationOptions: () => { return { tabBarVisible: false } },
    //lazyLoad: true,
    swipeEnabled: false,
    animationEnabled: false,
});

`

This is my custom tab bar:

`
// create a component
class TabBar extends Component {

    constructor(props){
        super(props);
        this.state = {
            userFullName: '',
            userImageProfile: ''
        }
    }

    //componentWillReceiveProps({ user_profile }){
    componentWillReceiveProps(nextProps){
        console.log(nextProps);
    }

    onPress(routeName, params){
        console.log(store.user_profile);
        const navigateAction = NavigationActions.navigate({
            routeName,
            params
        })
        this.props.navigation.dispatch(navigateAction)
    }

	render() {

        const { container, innerContainer, containerIconStyle, iconStyle } = styles;
        const { userFullName, userImageProfile } = this.state;

        console.log('userFullName=',userFullName);

		return (
			<View style={container}>
                <View style={innerContainer}>
                    <Icon
                        name='home'
                        containerStyle={containerIconStyle}
                        iconStyle={iconStyle}
                        onPress={this.onPress.bind(this, 'home', {})}
                    />
                    <Icon
                        name='search'
                        containerStyle={containerIconStyle}
                        iconStyle={iconStyle}
                        onPress={this.onPress.bind(this, 'search', {})}
                    />
                    <Icon
                        reverse
                        name='explore'
                        containerStyle={containerIconStyle}
                        iconStyle={iconStyle}
                        onPress={this.onPress.bind(this, 'chapterEditorScreen', {})}
                    />
                    <Icon
                        name='view-list'
                        containerStyle={containerIconStyle}
                        iconStyle={iconStyle}
                        onPress={this.onPress.bind(this, 'chapterList' , {})}
                    />
                    <Icon
                        type='font-awesome'
                        name='user'
                        containerStyle={containerIconStyle}
                        iconStyle={iconStyle}
                        onPress={ this.onPress.bind(this, 'userProfileScreen', {userFullName, userImageProfile}) }
                    />
                </View>
			</View>
		);
	}
}

const styles = StyleSheet.create({
	container: {
		height: 60
	},
    innerContainer: {
        flex: 1,
        flexDirection: 'row',
        justifyContent: 'space-around',
        alignItems: 'center',
        backgroundColor: '#2c3e50',
    },
    containerIconStyle: {
	    height: 60
    },
    iconStyle: {
        fontSize: 20,
        color: '#FFF'
    },
});

const mapStateToProps = ({ user_profile }) => {
    return { user_profile };
};

export default connect({}, null)(TabBar);
`

**Comment by DavidSongzw** [comment]
I have same problem

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!

**Comment by eng-osman** [comment]
i have some problem in 2020
