### ISSUE TITLE
HOW TO:  Hide header by event emitted from a component

### ISSUE THREAD

**Issue by dmr07** [react-community/react-navigation#2048]
I'm trying to hide the header on scroll down event, and show it on scroll up. In the component, I managed determine the scroll direction, and now I need to get it to my header some how. 

Function to update headers look something like this. 
```javascript
updateHeader(cmd) {
  if (cmd == 'show') {
    // do something to show header
  } else {
    // do something to hide header
  }
}
```

I've tried connecting the StackNavigator to Redux, but it gave me this error: 
```
This navigator has both navigation and container props, so it is unclear if it should own its own state. 
```

I also tried passing it through using setParams, but the StackNavigator doesn't have the params prop:
```javascript

// scroll event comes from a component in screenA
const Child = TabNavigator({
  screenA: {
    screen: A,
  },
  screenB: {
    screen: B,
  }
},{
  tabBarPosition: 'top',
});

// Need to hide header here
const Parent = StackNavigator({
  parent: {
    screen: ChildTab,
    path: '/parent/:show',
    initialRouteName: {
      show: true,
    },
    navigationOptions: {
      header: ({ navigation }) => { // <--- here specifically
        const { state, screenProps } = navigation;
        console.log(navigation.params); // undefined
        return (
          <View style={[styles.header]}> ... </View>
        )
      }
    }
  }
})
```

**Comment by dmr07** [comment]
I ended up making the view redux-aware by wrapping it in a custom component.

**Comment by LAITONEN** [comment]
Could you, please, give more details on how did you cope with this problem? I also want to show / hide the header, but in my case, it should be shown in componentDidMount()?

**Comment by dmr07** [comment]
@LAITONEN I actually never got around to solving the problem, but in theory it should be fairly simple:

1. In navigationOptions, make your header a component and connect it to redux. 
2. Detect scroll up / scroll down in your component and dispatch the change to your redux store.
3. Write code in the header component that animates the change based on redux scroll variable. 

Others have mentioned passing the data upwards via navigation params, but the param obj was empty for me. 

Regarding showing on componentDidMount, just set the appropriate initial state of the header component so it is initially rendered, and hidden on scroll down.
