### ISSUE TITLE
Nested navigations render screen twice. What to do?

### ISSUE THREAD

**Issue by natashache** [react-community/react-navigation#205]
Hi,
I just found this great module and I'm really liking it. But when I try to nest a stack navigator inside of a tab navigator, it causes the screen that is part of both navigators to be rendered repeatedly when I click on it. 

Specifically, I have the following tab navigation set up:
```
export const MainNavigator = TabNavigator({
  Explore: { screen: Explore },
  CourseNavigator: { screen: CourseNavigator },
  MyProfile: { screen: MyProfile }
}, {
  initialRouteName: 'CourseNavigator',
  navigationOptions: {
    tabBar: {
      visible: false
    }
  },
  headerMode: 'screen'
})
```
As you can see, one of the screens, `CourseNavigator`, is a navigator itself, which is defined as:
```
export const CourseNavigator = StackNavigator({
    MyCourses: { screen: MyCourses },
    CoursePage: { screen: CoursePage }
  }, {
  headerMode: 'screen'
})
```
Upon entering the app, the screen shown is the `MyCourses` screen. Because it is the first screen in `CourseNavigator`, and `CourseNavigator` is the initial screen for the `MainNavigator`. That part renders fine. But if I navigate to any other tabs in the `MainNavigator`, and then click a button to go back to `CourseNavigator`, it will render the `MyCourses` twice consecutively-- once static, once with left-swiping animation, which I guess is from the StackNavigator setting. 

My question is: how do I stop the repeated rendering? I only want the `MyCourses` screen to be rendered once (ideally without the animation) when I go back to the `CourseNavigator` tab.

Thanks for any tips!

**Comment by ElliottJRo** [comment]
Hey @natashache I just tried this and it might be an issue that was resolved few commits back on the master branch. I suggest deleting the `react-navigation` node module and downloading directly from github

**Comment by natashache** [comment]
@ElliottJRo Thanks for the tip! I'll try that!
