### ISSUE TITLE
How to get the parameters on the URL?

### ISSUE THREAD

**Issue by damiaozi** [react-community/react-navigation#2050]
I use react-navigation Do interface jump.
but,now，I want to get the parameters on the URL。
How to get the parameters on the URL?

**Comment by jurajkrivda** [comment]
You can get it from `props.navigation.state.params`

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
