### ISSUE TITLE
How to navigate out of components?

### ISSUE THREAD

**Issue by anhuiliujun** [react-community/react-navigation#2051]
### Expected Behavior
I just want to find a way to navigate out of components. Not just in redux. I want navigate in any js file. But i just cannot find a way.

**Comment by gitfdy** [comment]
goback('key')

**Comment by anhuiliujun** [comment]
I want to do navigation in utils, not in components. So i do not have the props.

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
