### ISSUE TITLE
Animation not working on Android with nested TabNavigators

### ISSUE THREAD

**Issue by matwii** [react-community/react-navigation#2052]
I have a TabNavigator, StackNavigator, TabNavigator, nested in eachother in this order. For some reason the animations are not working on Android, but works perfectly on iOs, to make it work on Android I have to set animationEnabled: false. I have tried to set both TabNavigators to lazy: true, but it's not working. Anyone know how to make this work on Android?

**Comment by ganisback** [comment]
nested TabNavigator is also not working for me, it only does not work in first tab,
I have expected the solution for several weeks, I don't think react navigation is a mature component.

**Comment by mathemagics** [comment]
Yep, I had the same issue a few weeks ago. It looks like its from a change to react-native itself, in particular its use of ViewPagerAndroid.

**Comment by LeonWang2006** [comment]
me too

**Comment by xyxabcdiy** [comment]
My first tab works fine, but the second not work

**Comment by Ben56** [comment]
me too

**Comment by minocoko** [comment]
set tabNavigatorConfig.lazy to true, it seems works

**Comment by shenst1** [comment]
I experienced the same issue with a TabNavigator nested inside a StackNavigator. The only solution that worked for me was to set `animationEnabled` and `swipeEnabled` to false in my tested Tab. Also, it does work on ios though, so i added `Platform.OS === 'ios' ? true : false`

**Comment by kelset** [comment]
Pinging OP @matwii since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open; if I get no answer in the next 7 days I will close it.

**Comment by kelset** [comment]
Hi there @matwii,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.

**Comment by pilot4u** [comment]
Hi @kelset , we experiencing the same issue of transition animations are not executing
I tried upgrading to 1.0.0-beta.23 but the issues still remains.
could you please reopen this issue?
here is the relevant code sample:
`const slidingTransition = (index, position, pageY) => {
  const inputRange = [index - 1, index, index + 1];
  const opacity = position.interpolate({
    inputRange,
    outputRange: [0, 1, 0],
  });

  const translateY = position.interpolate({
    inputRange,
    outputRange: [pageY, 0, 0],
  });

  return {
    opacity,
    transform: [{ translateY }],
  };
};

const transitionSpec = {
  duration: 1000,
};

export const transitionConfiguration = () => {
  return {
    transitionSpec: transitionSpec,
    screenInterpolator: sceneProps => {
      const { position, scene } = sceneProps;
      const { index } = scene;
      const { params } = sceneProps.scene.route;
      const pageY = params ? params.pageY : 0;
      return slidingTransition(index, position, pageY);
    },
  };
};

BottomTabNavigator = TabNavigator(
  {
    Main: { screen: TabMain, path: 'Main' },
    Feed: { screen: TabOptions, path: 'Feed' },
    Social: { screen: TabSocial, path: 'Social' },
  },
  {
    tabBarOptions: {
      showIcon: true,
      showLabel: true,
      upperCaseLabel: false,
      labelStyle: AppStyles.bottomTabLabel,
      pressOpacity: 0.1,
      indicatorStyle: AppStyles.bottomBarIndicator,
      activeTintColor: lightTheme.tabActiveIconTint,
      inactiveTintColor: lightTheme.tabInactiveIconTint,
      activeBackgroundColor: lightTheme.tabActiveBackground,
      inactiveBackgroundColor: lightTheme.tabInactiveBackground,
      style: AppStyles.bottomBarStyle,
      tabStyle: AppStyles.bottomTabStyle,
      navigationOptions: {
        headerBackTitle: null,
        header: null,
      },
    },
    lazy: true,
    tabBarPosition: 'bottom',
    tabBarComponent: TabBarTop,
    swipeEnabled: true,
    animationEnabled: true,
    initialRouteName: INITIAL_ROUTE_NAME,
    backBehavior: 'initialRoute',
  }
)

AppNavigator = StackNavigator(
  {
    SplashScreen: { screen: SplashScreen },
    Entry: { screen: EntryContainer },
    Tabs: { screen: TabBarNavigation },
    Options: { screen: OptionsContainer },
    People: { screen: PeopleContainer },
  },
  {
    initialRouteName: 'SplashScreen',
    key: 'SplashScreen',
    mode: 'modal',
    gesturesEnabled: true,
    transitionConfig: transitionConfiguration,
    cardStyle: {
      backgroundColor: lightTheme.headerBackground,
    },
  }
)`
