### ISSUE TITLE
Passing props from parent component to custom navigator

### ISSUE THREAD

**Issue by leanminmachine** [react-community/react-navigation#2053]
### Current Behavior
Referring to the custom tabs example on the docs, I had passed params through the navigate function to a screen. eg. 

`onPress = {() => navigate('ListingDetails', {listingAttributes: listing})`

this works as expected and when I go to the ListingDetails screen, console logging this.props.navigation.state.params returns me the listingAttributes. 

### Expected Behavior
Now my problem is I have a CustomTabs component in ListingDetails. Would it be possible to pass this.props.navigation.state.params into the CustomTabs and render the data from each CustomTabView, and how to do so?

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  "react-navigation": "1.0.0-beta.7",
| react-native     |  "react-native": "https://github.com/exponent/react-native/archive/sdk-15.0.0.tar.gz",
| node             | v7.2.1
| npm or yarn      | 4.6.1

**Comment by matthamil** [comment]
I'm not sure I follow your question. Can you post a relevant code snippet?

**Comment by leanminmachine** [comment]
Hey @matthamil thanks for taking a look at my thread!

Here is a snippet:

```
class ListingDetailsScreen extends Component {

  componentDidMount() {
    console.log("state", this.props.navigation.state.params);
  }

    static navigationOptions = {
    header: { style:{ position: 'absolute', backgroundColor: 'transparent', zIndex: 100, top: 0, left: 0, right: 0 } }
    }

    render() {

      const {navigate} = this.props.navigation;
      this.props.userFetch();

        return (
            <View style = {{backgroundColor: 'white', height: 650}}>

            <ListingHeader
            name = {this.props.name}
            bio =  {this.props.bio}/>

                <CustomTabs />
            </View>
        );
    }
}
```

CustomTabs refers to [CustomTabs.js](https://github.com/react-community/react-navigation/blob/30ca3c1f80617abc28fdd71f0b37d4f62b3e388a/examples/NavigationPlayground/js/CustomTabs.js) 

I would like some way to pass this.props.navigation.state.params into CustomTabs through something like screenProps but unsure if it is possible.

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
