### ISSUE TITLE
Create TabBar Navigation in Drawer Navigation 

### ISSUE THREAD

**Issue by MSSPL-PiyaleeMaiti** [react-community/react-navigation#2054]
I want to show two tab bar in Drawer. When I open the drawer I want to show two tab in drawer.
I set tabNavigation in Drawer contentComponent, so that I can't get that StackNavigator route which declared before Drawer. My drawer code is below : 

```
const AppNavigate = StackNavigator({
		Home: { screen: Home },
		Notification: { screen: Notification },
		Profile: { screen: Profile },
		Chat: { screen: Chat },
	});
```

```
const Home = DrawerNavigator({
	  HomeList: { screen: HomeList },
	},
	{
		contentComponent: props => <LeftDrawer  {...props} />
	}
);
```

```
const LeftDrawerItems = TabNavigator({
  PlatformList: { screen: PlatformList },
  MenuList: { screen: MenuList },
},{
	tabBarPosition: "bottom",
	tabBarOptions: {
		// showLabel: false,
	}
});
```

Now the problem is how can I pass the previous navigation to Drawer componet TabNavigation route.
I want to navigate from PlatformList component to Profile, but I couldn't, can anyone suggest any solution.

Screen-shoot is below:
![screenshot_1499152102](https://user-images.githubusercontent.com/20696057/27819236-e8171612-60b6-11e7-8e43-06bdb9e61b96.png)

| software         | version
|  android and iOS | 
| react-navigation |  ^1.0.0-beta.11
| react-native     |  0.45.1 & 0.44.0
| react             | 16.0.0-alpha.12

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
