### ISSUE TITLE
DrawerNavigator, drawerWidth needs to recalculate when screen orientation changes. 

### ISSUE THREAD

**Issue by bijubijoy** [react-community/react-navigation#2055]
i set drawer menu content by **contentComponent** and gave **drawerWidth** respective to device width, now if i change orientation of screen it will not recalculate the drawerWidth .

**Comment by Porshe** [comment]
+1

**Comment by markentingh** [comment]
This is a serious issue. When loading the app in landscape orientation, the menu is large, and stays large after switching to portrait orientation. When loading the app in portrait orientation, the menu is small, and stays small after switching to landscape orientation while the app is still running.

**Comment by douglasjunior** [comment]
No need to calculate if you set a good fixed width. 

Try:

```js
import { Dimensions } from 'react-native'
const { width, height } = Dimensions.get('window');

...

const DrawerRoutes = DrawerNavigator(
    {
        ...
    },
    {
        ...
        drawerWidth: Math.min(height, width) * 0.8, // calculates 80% of the smaller side of the screen.
    }
);

**Comment by doublex** [comment]
+1

**Comment by davepack** [comment]
We went with a fixed width based on the suggestion by @douglasjunior. Fixed in #2773 :-)

**Comment by Donhv** [comment]
How to fix it? I don't see any change?

**Comment by douglasjunior** [comment]
Fixed in https://github.com/react-navigation/react-navigation/releases/tag/v1.0.0-beta.20
