### ISSUE TITLE
Modal navigation stack - Invalid data message

### ISSUE THREAD

**Issue by pulkitsharma99** [react-community/react-navigation#2057]
Hi,

Currently I want a scenario where I have a screen which presents a modal. Now I want this modal to be the base screen on which other transitions(right to left) will happen? Can anyone guide me how to accomplish this ? Here's my code: 

```
const AccountsStack = StackNavigator({
  Account:{
    screen: AccountsPage,
    navigationOptions:{
      title: 'MY Page'
    }
  },
  Country: {
    screen: CountryView,
    navigationOptions:{
      title: 'COUNTRY'
    }
  },
});
const LoginStack = StackNavigator({
  Login: {
    screen: LoginPage,
  },
  EmailLogin: {
    screen: EmailLogin,
    
  }
})
const AccountsStackModal = StackNavigator({
  AccountsStack: {
    screen: AccountsStack,
    navigationOptions:{
      header: null
    }
  },
  LoginStack: {
    screen: LoginStack,
    navigationOptions: {
      header: null,
      tabBarVisible: false
    }
  }
},
{
  mode: 'modal',
})
```

Now when EmailLogin is pushed on the modal, i get the following error, moreover I am not sure if this approach will achieve the desired outcome.
![simulator screen shot 04-jul-2017 4 24 33 pm](https://user-images.githubusercontent.com/29450892/27827526-4f1b1d90-60d5-11e7-99fb-4f05debe0a0d.png)
 P.S. [https://github.com/react-community/react-navigation/issues/1318](url) didn't help

**Comment by matthamil** [comment]
Can you provide details about your current enviroment (e.g. RN version, React Navigation version, etc).

**Comment by pulkitsharma99** [comment]
@matthamil sure.
react-navigation - ^1.0.0-beta.11"
react-native - 0.44.0
react - 16.0.0-alpha.6

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
