### ISSUE TITLE
Subtitle with DrawerNavigator ?

### ISSUE THREAD

**Issue by Sh1n1x** [react-community/react-navigation#2059]
Hi !
I would like customize the Drawer with icon, title and subtitle, it's possible ?

Like that: [http://www.datingbusters.com/wp-content/uploads/2015/01/Tinder-settings.gif](http://www.datingbusters.com/wp-content/uploads/2015/01/Tinder-settings.gif)

**Comment by Andreyco** [comment]
You are free to provide your very own implementation of drawer.

```js
{
  contentComponent: props => <ScrollView><DrawerItems {...props} /></ScrollView>
}

**Comment by Solban** [comment]
@Andreyco When placing `<DrawerItems {...props} />` somewhere in the contentComponent, it shows the basic list item(icon on the left, text on the right). Would it be possible to customize the item, so lets say we have an item in the drawer navigation with a structure: (icon)(title)(subtitle)?

**Comment by Andreyco** [comment]
@Solban sure, it's possible. You must create your own implementation of `DrawerItems` component. You can do anything there.

**Comment by Solban** [comment]
Thanks @Andreyco !
Being new to React and JS in general, I currently got it working like this:
`contentComponent: props =>
      <ScrollView style={styles.drawerStyle}>
        <DrawerItems {...props} getLabel={(scene) => (
          props.getLabel(scene) === 'test' ?
            <ItemOne title={props.getLabel(scene)}/>
            :
            <ItemTwo title={props.getLabel(scene)}/>
        )}
        />
      </ScrollView>`

Why prefer creating my own DrawerItems component to this solution?

**Comment by Andreyco** [comment]
Welcome to React and RN then! I am glad you found your solution. Custom `DrawerItems` offers more control. As you see, there is no "right" way. Pick solution that works for you and requires least effort, especially while you learning. Happy coding :)
