### ISSUE TITLE
Unable to style header component

### ISSUE THREAD

**Issue by si-harps** [react-community/react-navigation#206]
Possibly a noob question but i cant seem to find a way to style a header component from within navigationOptions. 

```
static navigationOptions = {
        title: 'Home',
        header: ({ state, setParams }, defaultHeader) => ({
            ...defaultHeader,
            style: HeaderStyle,
            right: (<Icon
                name="menu"
                style={{ fontSize: 20, right: 15 }}
            />)
        })
    };
```

...where HeaderStyle is...

```
{
    backgroundColor: 'red'
}
```

**Comment by chandu0101** [comment]
@si-harps  how did you fixed this ? i am also facing similar issue ..

**Comment by si-harps** [comment]
@chandu0101 sorry, i closed and moved to https://github.com/react-community/react-navigation/issues/200

Still facing the same issues :(

**Comment by chandu0101** [comment]
@si-harps  oh ok thanks for info :)

**Comment by Fenwil** [comment]
Is there a way to style the header on Android ? Thanks in advance.
