### ISSUE TITLE
UWP/Windows - Long title is showing after first transition

### ISSUE THREAD

**Issue by Noitidart** [react-community/react-navigation#2061]
### Current Behavior

I created a StackNavigation on Windows/UWP (react-native windows). On the main page, when there is a long title. On first navigation, it will show the long title underneath. On consequent navigations it is not shown. Here is a youtube screencast - https://youtu.be/55gANaPtsMo

### Expected Behavior

The title should not show after page transitions away.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  ^1.0.0-beta.11
| react-native     |  0.45.1
| node             |  7.5.0
| npm      | 5.0.4

Version of react-native-windows is ^0.45.0-rc.1 - https://github.com/Microsoft/react-native-windows

Here is my code, it is simple, based on the getting started with stack navigator code:

```
import React from 'react'
import {  AppRegistry, Text } from 'react-native'
import { StackNavigator } from 'react-navigation'

class HomeScreen extends React.Component {
  static navigationOptions = {
    title: 'Welcome hi there ya aya sdfe lsdf iewek soaoa'
  }
  render() {
    const {navigation:{ navigate }} = this.props;
    return <Text onPress={navigate.bind(null, 'B')}>Hello, Navigation!</Text>;
  }
}
class BScreen extends React.Component {
  static navigationOptions = {
    title: 'B'
  }
  render() {
    return <Text>B</Text>;
  }
}

const SimpleApp = StackNavigator({
  Home: { screen: HomeScreen },
  B: { screen: BScreen },
});

AppRegistry.registerComponent('qaida_board', () => SimpleApp);

````

**Comment by kelset** [comment]
Pinging OP @Noitidart since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open; if I get no answer in the next 7 days I will close it.

**Comment by Noitidart** [comment]
Thank you @kelset! I will try it in a new verison and let you know. :)

**Comment by kelset** [comment]
@Noitidart any news?

**Comment by Noitidart** [comment]
Oops, trying now, thanks for the remidner!

**Comment by Noitidart** [comment]
@kelset Im not able to get the windows build stuff working right now. Thanks so much for waiting for me. I'll close this out and update when I get a chance to test.
