### ISSUE TITLE
how to reset a back button?

### ISSUE THREAD

**Issue by saeropark** [react-community/react-navigation#2063]
Hi.. 

My flow:
Home > Promotion List  (click on an item) > Promotion Details. 

Main screen: navigates inside a stacknavigator.

**Main.js**
```
`class ToPromotion extends React.Component {
    static navigationOptions = ({navigation}) => ({
        header: null,
    });
    render() {
        const { params } = this.props.navigation.state;
        return <Promo />
    }
}`
```
This is inside a stacknavigator. 

now inside 
**Promo.js**
```class PromoList extends React.Component {
static navigationOptions = ({ navigation }) => {
const {goBack} = this.navigation;
  
  return {
    title: ' Promotion',
        headerLeft: (
          <Icon
            size={30}
            name='keyboard-arrow-left'
            //type='ionicon'
            color= 'black'//color='#517fa4'
            onPress={() => goBack()}
            />
    ),
  };
};```

my goback button is not doing anything. can anyone help?

**Comment by jainniket** [comment]
how are you using the goBack action?

Ideally 
`this.props.navigation.goBack()`
https://reactnavigation.org/docs/navigators/navigation-prop
or 
`NavigationActions.back({key: })`
https://reactnavigation.org/docs/navigators/navigation-actions#Back

should work in this case.

**Comment by saeropark** [comment]
For the above, i realize why goBack() couldnt work. this is because the current stack is at its own. Later i found out that the goBack() could only work within the same stack. 

i later found out the trick which works PERFECTLY without adding any complex logic. 

General idea of my app: 

Using a nested analogy:

HomeStack : {
      Tab: {
            PromoStack: {
                  -listpage
                  -detailpage
          }
    }
}

i have problems going back from pages inside promostack to tab and back to home page. 

then i found out, for this 'back' to happen (home <-- tab <---- content <---- detail)

we need to set header visibility to true and then not generate promostack header.

this is by setting
promostack.navigationoptions.. 
headerMode: 'none'.

this can be found in the files https://reactnavigation.org/docs/navigators/stack
