### ISSUE TITLE
How to pass redux state to initialRouteParams?

### ISSUE THREAD

**Issue by vzhen** [react-community/react-navigation#2064]
How can i connect to react redux and pass state to initialRouteParams ?
```
const stackNavigatorConfiguration = {
  initialRouteName: 'PostList'
  initialRouteParams: { // I want to get state from redux and pass it to here. }
}
export const TabPostNavigator = StackNavigator(routeConfiguration,stackNavigatorConfiguration)
```

**Comment by tyleralves** [comment]
I'm trying to do the same thing. Specifically dispatching a redux action from `onTransitionEnd`. 

From the docs, it looks like you might need to create a custom navigator, but I really hope I'm wrong about that!

**Comment by tugorez** [comment]
@vzhen @tyleralves just a question. Why do you want to do that?

**Comment by vzhen** [comment]
@tugorez I have a component to display user's post list. This component read params which `user id` and get user's post list and I want it to first initial load logged in user's post list.

**Comment by lucianomlima** [comment]
@vzhen How did you handle it?

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
