### ISSUE TITLE
Tab bar overlay

### ISSUE THREAD

**Issue by moonjava2005** [react-community/react-navigation#2065]
Dear all,
I want to make the Top Tab bar overlay on other tabs in order to make the take bar auto hide when scrolling
Currently, the Top Tab bar is relative. It means the content view will begin from the bottom of Tab bar
There's any solution?

**Comment by spencercarli** [comment]
You'll want to create a custom tab bar.

Since this pertains to your specific app/use-case it's probably a better fit for StackOverflow (with the react-navigation tag)
