### ISSUE TITLE
How i can redirect from function login or register as we use previously "this.props.navigator.push".

### ISSUE THREAD

**Issue by aurehmanghani** [react-community/react-navigation#2066]
### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.11
| react-native     |  0.45.1
| node             | 
| npm or yarn      |

**Comment by jainniket** [comment]
Can you give some more detailed context on it?

Would be great if you can put some code snippet!!

**Comment by aurehmanghani** [comment]
Its Done:
 const { navigate } = this.props.navigation;
navigate('DashBoard', { Access_Token: accessToken });
