### ISSUE TITLE
possible to forceUpdate DrawerNavigator?

### ISSUE THREAD

**Issue by Adamnator92** [react-community/react-navigation#2067]
my Drawer Content:

```
- User name
- User profile_picture
- <DrawerItems />
```

i will allow user to update their info, but after user updated their info, the` user name` and `profile_picture` in the drawer is still the previous user data. any way i can do to `forceUpdate `the user data?

**Comment by jainniket** [comment]
if this is connected to redux and you are reading it as props, it should re-render automatically.

if not this, then how are you implementing it?

**Comment by matthamil** [comment]
@Adamnator92 Can you post a snippet showing the relevant code?

**Comment by Adamnator92** [comment]
@jainniket i didnt using redux for my current project, and i dont think the drawer navigator will re-render itself as i use the drawer navigator as root level

**Comment by Adamnator92** [comment]
@matthamil i treat my DrawerNavigator as root level, i will retrieve user data during `componentDidMount()`  and display the user name at drawer. 

```
classs DrawerContent extends Component {
     componentDidMount(){
           //async function
     }
     
     render(){
         return(
         <Scrollview>
                  ///user name 
          	<DrawerItems {...this.props} />
         </Scrollview>
         )
     }
}

const Navigation = DrawerNavigator(
	{
		Profile: screen: Profile,
	},
	{
		contentComponent: DrawerContent,
	}
);
```

**Comment by tienvd1994** [comment]
I have same problem. Plz help me.

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!

**Comment by geekyayush** [comment]
Umm..... I'm also looking for a solution without using Switch Navigator.

**Comment by fahadhaq** [comment]
@geekyayush  not sure if you found a solutions but the following is working for me when I need to refresh a page from the drawer navigator.

you can do that by following,

In navigation add a parameter (isFromHome),

```
const navigateAction = NavigationActions.navigate({
      routeName: routeName,
      params: { isFromHome: true}
    });
    this.props.navigation.dispatch(navigateAction);
```

Then add code in componentWillReceiveProps() of your class

eg:

```
componentWillReceiveProps(newProps) {
    console.log("#######", newProps.navigation.state.params.isFromHome);
    // Here you will get the parameter every time. By checking the parameter you can achieve your need.
  }
```

Hope this helps.

**Comment by adamnator92** [comment]
use redux for handle the state in drawer would solve the issue

**Comment by ksetrin** [comment]
@adamnator92 

I had DrawerContent connected to redux but components inside didn't updated themselves

The problem was with TouchableOpacity component, because my styles was binded to it.
I solved the problem by decompose my component and moved styles to View behind TouchableOpacity like this

```
return (
    <View style={props.disabled ? styles.itemDisabledContainer : styles.itemContainer}>
      <TouchableOpacity onPress={props.onPress} style={styles.itemWrapper}>
      ...
      </TouchableOpacity>
    </View>
```

**Comment by jaycee126** [comment]
Hi there, i had the same issue, Solved it by checking if drawer was open from the react-navigation hook useIsDrawerOpen, then in my useeffect like this 
```
const drawerOpen = useIsDrawerOpen()
useEffect(() => {
if(!drawerOpen){
   // Add code here to load data
}
}, [drawerOpen])
```
