### ISSUE TITLE
How to reset stacknavigator  stack? 

### ISSUE THREAD

**Issue by One28Piece** [react-community/react-navigation#2068]
How to reset stacknavigator  stack?

**Comment by jainniket** [comment]
https://reactnavigation.org/docs/navigators/navigation-actions

use the navigation actions `Reset`

**Comment by RWOverdijk** [comment]
That link is broken. For future googlers: https://reactnavigation.org/docs/navigation-actions.html#Reset

**Comment by RyPope** [comment]
And the new link... https://reactnavigation.org/docs/en/stack-actions.html#reset

**Comment by akhileshUvionicstech** [comment]
when use replace/reset losses 'transitionConfig()'  animations.

**Comment by mubashirrahman** [comment]
const prevGetStateForActionHomeStack = HomeStack.router.getStateForAction;
HomeStack.router.getStateForAction = (action, state) => {
    if (state && action.type === 'ReplaceCurrentScreen') {
      const routes = state.routes.slice(0, state.routes.length - 1);
      routes.push(action);
      return {
        ...state,
        routes,
        index: routes.length - 1,
      };
    }
    return prevGetStateForActionHomeStack(action, state);
  },
};



.....................................................................................................................................................................
replaceScreen = () => {
  const { locations, position } = this.props.navigation.state.params;
  this.props.navigation.dispatch({
    key: 'NearMeMap',
    type: 'ReplaceCurrentScreen',
    routeName: 'NearMeMap',
    params: { locations, position },
  });
};

...................................................................................................................................................................
replaceScreen = () => {
  const { locations, position } = this.props.navigation.state.params;
  this.props.navigation.dispatch({
    key: 'NearMe',
    type: 'ReplaceCurrentScreen',
    routeName: 'NearMe',
    params: { locations, position },
  });
};

**Comment by viniciusemferreira** [comment]
And the new link... Again... https://reactnavigation.org/docs/navigation-actions/#reset
