### ISSUE TITLE
Access to component in onNavigationStateChange

### ISSUE THREAD

**Issue by shahankit** [react-community/react-navigation#2069]
Currently `onNavigationStateChange` provides prevState, currentState and action. The state only contains routeName, key and params. Is there a way to access the component or it's static methods/properties like navigationOptions. I found the key parameter, is there any internal method to get component from key.

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.11
| react-native     |  0.44.0

**Comment by jainniket** [comment]
`
// gets the current screen from navigation state
export function getCurrentRouteName(navigationState) {
  if (!navigationState) {
    return null;
  }
  const route = navigationState.routes[navigationState.index];
  // dive into nested navigators
  if (route.routes) {
    return getCurrentRouteName(route);
  }
  return route.routeName;
}
`

You can use this method to know the current route name for your prevState and currentState.

**Comment by shahankit** [comment]
@jainniket I already know that code from documentation. I actually need access to the class and not just the routeName.

**Comment by matthamil** [comment]
What is your use case for needing to access the component or static methods? You could try to pass a ref as one of the params.

**Comment by shahankit** [comment]
My primary objective was setting the status bar color. I checked the thread for focus events(#51) and setting status bar(#11). I think it would be great if we could get reference to component in onNavigationStateChange. That way the subscription for events could be  built by the developer rather than implementing in react-navigation core.

**Comment by shahankit** [comment]
@matthamil How do I pass ref as param? I have following navigation stack:
```
const TabNavigator = TabNavigator({
  Home: { screen: HomeScreen },
  Discover: { screen: DiscoverScreen },
  Channels: { screen: ChannelsScreen },
  Settings: { screen: SettingsScreen }
});

const routeConfig = {
  Login: { screen: LoginScreen },
  TabWrapper: { screen: TabNavigator },
  PrivacyPolicy: { screen: PrivacyPolicyScreen },
  ForgotPassword: { screen: ForgotPasswordScreen },
  Profile: { screen: ProfileScreen },
};

const navigatorConfig = {
  initialRouteName: isLoggedIn ? 'TabWrapper' : 'Login',
  navigationOptions: {
    headerTitleStyle: styles.headerTitleStyle,
    headerStyle: styles.headerStyle,
    headerTintColor: colors.kNavBarTitleFontColor
  }
};
const RootNavigator = StackNavigator(routeConfig, navigatorConfig);

return (
  <RootNavigator
    onNavigationStateChange={onNavigationStateChange}
  />
);
```

**Comment by shahankit** [comment]
@matthamil @satya164 Is there any way that I can access the component in onNavigationStateChange?

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!

**Comment by npinochet** [comment]
Did someone found a solution?
