### ISSUE TITLE
Export HeaderBackButton from this module

### ISSUE THREAD

**Issue by davideweaver** [react-community/react-navigation#207]
Is there any reason HeaderBackButton is not exported from this module? Because of [issue #115](https://github.com/react-community/react-navigation/issues/115) I need to manually place a back button in some of my views. If HeaderBackButton was exported I'd be able to reuse that code. I'd be happy to do a PR with the change if there's not a problem in doing so.

**Comment by lnikkila** [comment]
It’s available through properties: [`StackNavigator.Header.BackButton`][0].

You can use a destructuring assignment after importing StackNavigator to assign it to some easy to use variable like `BackButton`.

[0]: https://github.com/react-community/react-navigation/blob/c35a706/src/views/Header.js#L60

**Comment by davideweaver** [comment]
@lnikkila That worked. I just used `const BackButton = CardStack.Header.BackButton`. How would you use destructuring to simplify that? Thanks

**Comment by lnikkila** [comment]
Great!

It’s not that much simpler, you could even argue destructuring is more complex to reason about than regular property access:

```js
const {Header: {BackButton}} = CardStack;
```

**Comment by satya164** [comment]
This is a saner use of destructuring

```js
const { BackButton } = CardStack.Header
```

**Comment by tirrorex** [comment]
For anyone bumping into this you can now directly import the button : 
import {HeaderBackButton} from "react-navigation";

**Comment by cglacet** [comment]
Any idea where is this button now? (on version `6.x.y`)

**Comment by cglacet** [comment]
Ah, found it, its in another package:

```tsx
import {HeaderBackButton} from '@react-navigation/elements';
```
