### ISSUE TITLE
use function on Screen#1 after .dispatch(backAction) from Screen#2

### ISSUE THREAD

**Issue by shuffgy** [react-community/react-navigation#2072]
I'm sorry, it could be a duplicate of #1617 but i dont use redux and "just" want to use a function again, after going back via [NavigationActions.back()](https://reactnavigation.org/docs/navigators/navigation-actions#Back) and 
`this.props.navigation.dispatch(backAction)`

Works like a charm!

So i have a screen that renders some stuff like comments. Then there is a button to go to another screen and after submitting something i'm using the back-action to close that screen.
So now Screen Nr.1 should now re-render or just use a function again (like getcomments() ).

How can i archive that? I'm using react-navigation 1.0.0-beta.11

I hope you can help me.

**Comment by xsgkaka** [comment]
i got the same problem

**Comment by Andreyco** [comment]
Since you are not using Redux, or any external state management lib, callbacks are your possible solution.

```
// When pushing screen
navigation.navigate('SomeScreen', {
    onSuccess: () => getcomments(),
})

// then on SomeScreen
onSubmit() {
    try {
        await submit(...);
        navigation.state.params.onSuccess();
        navigation.goBack();
    } catch () {
        //
    }
}
```

**Comment by shuffgy** [comment]
Sorry for my late response, but i tried it now and yes - it is working! Thank you very much @Andreyco !
And i hope you got it also working @xsgkaka :)
