### ISSUE TITLE
react-navigation lost the backbutton image when hot updated

### ISSUE THREAD

**Issue by cityvoice** [react-community/react-navigation#2075]
I use react-navigation in my react-native app, It works well, but when i hot updated, all back-icon.png disappeared.I have copied all images to assets folder, it still doesn't work.

```
-app/src/main/assets
    -fonts
    -back-icon@1.5x.android.png
    -back-icon@1x.android.png
    -back-icon@2x.android.png
    -back-icon@3x.android.png
```

I have checked the index.android.bundle, and there are some code as below:

`registerAsset({__packager_asset:!0,httpServerLocation:"/assets/node_modules/react-navigation/src/views/assets",width:24,height:24,scales:[1,1.5,2,3,4],hash:"a364dc7a784101f7c8f6791c7b4514ce",name:"back-icon",type:"png"})`

platform is android, so how to resolve this problem?

**Comment by matthamil** [comment]
Can you provide info on your dev environment? E.g.:

| software         | version
| ---------------- | -------
| react-navigation |  
| react-native     |  
| node             | 
| npm or yarn      |

**Comment by jesseXu** [comment]
Had same issue these days, but its more like React Native issue. The javascript shipped with app uses '{ uri: 'xxx_xxx_backicon.png' }' to find the image. However, if the javascript is loaded from out side apk file, its using '{ uri: RELATIVE_TO_JAVASCRIPT_PATH/backicon.png }' which is not the original place. It seems we have to manually put the images there. Not sure how CodePush solved it.

**Comment by spencercarli** [comment]
Closing for lack of followup from OP.
