### ISSUE TITLE
is there "tabBarSelectedItemStyle"?

### ISSUE THREAD

**Issue by Poordeveloper** [react-community/react-navigation#2078]
so that we can set border color for active tab.

**Comment by spencercarli** [comment]
Currently limited to the tint color and background color (https://reactnavigation.org/docs/navigators/tab#tabBarOptions-for-TabBarBottom-default-tab-bar-on-iOS) which helps the tabbar conform to ios/android style guides

**Comment by ahmadalfy** [comment]
Hello,

Is there a way to achieve this effect? (border to the active tab?)

![image](https://user-images.githubusercontent.com/87611/30867618-313e0876-a2e5-11e7-9666-c15f137deac4.png)

**Comment by anceque** [comment]
@spencercarli Hi, will there be support for styling active label? I need to use a bold font for an active tab label but the rest of the labels should use a regular font weight. Is this anyhow possible?

**Comment by spencercarli** [comment]
You should be able ot use lableStyle https://reactnavigation.org/docs/navigators/tab#tabBarOptions-for-TabBarBottom-default-tab-bar-on-iOS

**Comment by anceque** [comment]
@spencercarli i know about it. But the styling options for *active* labels are limited. That's why i'm asking if there are any other options [e.g. font width] supported in the future :)

**Comment by cesarmal** [comment]
One possible solution is:
```
const TabBarIcon = ({ tintColor, focused, iconName }) => (
  <Icon
    name={iconName}
    size={iconSize}
    style={iconStyle}
    color={(focused) ? Colors.otherColor : 'lightgray'}
  />
);

const TabBarLabel = ({ tintColor, focused, label }) => (
  <Text
    style={{
      color: (focused) ? Colors.someColor : 'gray',
      fontSize: 11,
      paddingTop: 2,
      textAlign: 'center',
    }}
  >
    {label}
  </Text>
);

... (then on TabNavigator declaration)

someTabName: {
    screen: ScreenName,
    navigationOptions: {
      tabBarLabel: (props) => <TabBarLabel label="Custom Label" {...props} />,
      tabBarIcon: (props) => <TabBarIcon iconName="home" {...props} />,
    },
  },
```

**Comment by Joyor** [comment]
@ahmadalfy 

`  tabBarOptions: {
    indicatorStyle:{
      top:0,
    }},`

indicatorStyle - Style object for the tab indicator (line at the bottom of the tab).
https://reactnavigation.org/docs/navigators/tab#tabBarOptions-for-TabBarTop-default-tab-bar-on-Android

**Comment by sankar9659** [comment]
> Hello,
> 
> Is there a way to achieve this effect? (border to the active tab?)
> 
> ![image](https://user-images.githubusercontent.com/87611/30867618-313e0876-a2e5-11e7-9666-c15f137deac4.png)

@ahmadalfy ahmadalfy Have you found the solution?

**Comment by ahmadalfy** [comment]
@sankar9659 I didn't do it. Ended up ignoring the line on top

**Comment by sankar9659** [comment]
> @sankar9659 I didn't do it. Ended up ignoring the line on top

I have achieved by the custom tab bar design
