### ISSUE TITLE
Tabnavigator in Stacknavigator with a flatlist of articles

### ISSUE THREAD

**Issue by DevSzurmanski** [react-community/react-navigation#2080]
Hello :D. 
I have a pretty big problem. I have a stacknavigator with a flatlist with articles(just headers and photos). When I press a cell I am redirected to an article. I'd like to put a tabnavigator in there so I could swipe between articles when I'm on a single article. Something like in the video. I don't know how to implement it with react-navigation :( any ideas?

![pudlgif](https://user-images.githubusercontent.com/26198907/27913470-84d15a8a-6260-11e7-9de5-b6cf032acf60.gif)

**Comment by adrienthiery** [comment]
Hi @DevSzurmanski ,

This is not really a bug. 
Would you mind asking that on Stackoverflow or on [reactiflux](https://www.reactiflux.com/), as recommended in the [Readme](https://github.com/react-community/react-navigation#community), close that issue and we'll help you there ?

Thanks a lot!

**Comment by windhost** [comment]
@DevSzurmanski see this https://reactnavigation.org/docs/intro/nesting

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
