### ISSUE TITLE
How to change active tab style in TabNavigator? 

### ISSUE THREAD

**Issue by bhargavjoshi** [react-community/react-navigation#2082]
Right now the library provides way to provide labelStyle
 
```
labelStyle: {
    fontWeight: "bold"
}
```

is there any way it supports activeTab styling?

**Comment by ixje** [comment]
The TabNavigatorConfig supports [tabBarOptions](https://reactnavigation.org/docs/navigators/tab#tabBarOptions-for-TabBarBottom-default-tab-bar-on-iOS) like `activeTintColor` and `activeBackgroundColor`

Another way is via e.g. `tabBarIcon` of `navigationOptions` like so: 
```
		navigationOptions: {
			tabBarLabel: 'Give Feedback',
			tabBarIcon: ({ tintColor, focused }) => (
				<FAIcons
					name={focused ? 'comment' : 'comment-o'}
					size={24}
					style={{ color: tintColor }}
				/>
			),
		},
```
you can use the `focused` for conditional styles as well

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!

**Comment by hellenzhou** [comment]
_getTopBar = () => {
        let tops = {};
        this.topParams.map((item, index) => {
            tops[`tab${index}`] = {
                screen: props => <TaskContent labelItem={item} {...props} />,
                navigationOptions: {

                    tabBarLabel: ({ tintColor, focused }) =>
                        focused ? (<Text style={{ fontWeight: 'bold' }} >{item}</Text>) :
                            (<Text style={{ fontWeight: 'normal' }} >{item}</Text>),
                }
            }
        })
        return tops;
    }

    render() {
        const TabNavigator = createAppContainer(createMaterialTopTabNavigator(this._getTopBar(),
            {
                'lazy': false,

                initialLayout: {
                    height: 0,
                    width: Dimensions.get('window').width,
                },

                tabBarOptions: {
                    pressOpacity: 0,
                    tabStyle: { ...styles.tabStyle },
                    activeTintColor: "red",

                    labelStyle: { ...styles.labelStyle },
                    // showIcon: true,  
                    // activeTabStyle: {
                    //     fontWeight: 'bold',
                    //     backgroundColor: 'red',
                    // },

                    scrollEnabled: true, //是否支持选项卡滚动
                    indicatorStyle: styles.indicatorStyle,
                    style: {
                        backgroundColor: "#fff",

                    }
                },
                tabBarPosition: 'top',


            }
        ))

**Comment by hellenzhou** [comment]
Atthis-----> navigationOptions: {
                tabBarLabel: ({ tintColor, focused }) =>
                    focused ? (<Text style={{ fontWeight: 'bold' }} >{item}</Text>) :
                        (<Text style={{ fontWeight: 'normal' }} >{item}</Text>),
            }
        }
    })
    return tops;

**Comment by ravieze** [comment]
below code worked for me

```

 <NavigationContainer >

	<Tab.Navigator
		lazy={true}
		screenOptions={({ route }) => ({
			tabBarLabel: ({ tintColor, focused, item }) => {
				return focused
					? (<Text style={{ fontWeight: 'bold', letterSpacing: 0.3, marginBottom: 20, fontSize: 15, paddingLeft: 0, paddingRight: 0, width: 100 }} >{route.name}</Text>)
					: (<Text style={{ fontWeight: 'normal', letterSpacing: 0.3, marginBottom: 20, fontSize: 15 }} >{route.name}</Text>)
			},
			tabBarIcon: ({ focused, color, size }) => {
				// You can return any component that you like here!
				if (focused)
					return <Text style={{ fontWeight: 'bold', fontSize: 40 }} >{route.name}</Text>
				return <Text>{route.name}</Text>
			},
		})}
```

**Comment by simonho1025** [comment]
> below code worked for me
> 
> ```
> 
>  <NavigationContainer >
> 
> 	<Tab.Navigator
> 		lazy={true}
> 		screenOptions={({ route }) => ({
> 			tabBarLabel: ({ tintColor, focused, item }) => {
> 				return focused
> 					? (<Text style={{ fontWeight: 'bold',}} >{route.name}</Text>)
> 					: (<Text style={{ fontWeight: 'normal', fontSize: 15 }} >{route.name}</Text>)
> 			},
> 			
> 		})}
> ```

The label would get cut-off when changed to bold, like this
#8390
