### ISSUE TITLE
Same screen being added to stack upon dispatching a Redux action

### ISSUE THREAD

**Issue by jeanverster** [react-community/react-navigation#2083]
Hi guys,

So I've encountered a weird issue wherein I have a RefreshControl in a ScrollView, which triggers this onRefresh function: 

`_onRefresh () {
    this.setState({
      refreshing: true
    })
    this.props.walletRequest(this.props.user.token)
  }`

Then as indicated above, the walletRequest function dispatches a Redux action: 

`const mapDispatchToProps = (dispatch) => {
  return {
    walletRequest: (token) => dispatch(WalletActions.walletRequest(token))
  }
}`

This action has no navigation actions in it, but for some reason each time it fires - between request and success - react-navigation "navigates" to the same screen that I'm on and adds it to the stack. 

![image](https://user-images.githubusercontent.com/17738943/27929633-f86a48d4-6293-11e7-8e76-8d4aafbefffc.png)

Would a re-render of the component cause this behaviour? I'm pretty confused.. Any help would be appreciated!

React Native 0.45.1
React 16.0.0-alpha.12

**Comment by nico1510** [comment]
I don't think this is related to this library. I assume that somewhere in your saga you `put` a `NavigationAction` ? Maybe you can share this part of the code as that would be more helpful.

**Comment by jeanverster** [comment]
@nico1510 here is the code from the Saga:

`import { call, put } from 'redux-saga/effects'
import WalletActions from '../Redux/WalletRedux'

export function * wallet (api, action) {
  // make the call to the api
  const response = yield call(api.wallet)
  // success?
  if (response.ok) {
    // You might need to change the response here - do this with a 'transform',
    // located in ../Transforms/. Otherwise, just pass the data back from the api.
    yield put(WalletActions.walletSuccess(response.data))
  } else {
    yield put(WalletActions.walletFailure())
  }
}`

Then walletRequest and walletSuccess from the redux:

`export const walletRequest = (state, { token }) =>
  state.merge({ fetching: true, token })

// successful api lookup
export const walletSuccess = (state, {wallet}) => {
  return state.merge({ fetching: false, error: null, wallet })
}`

**Comment by nico1510** [comment]
So nowhere in your code you dispatch a `NavigationAction` ? Do you navigate from your component then ? The code where navigation happens is the interesting one.

**Comment by jeanverster** [comment]
So I managed to figure it out, it had to do with the fact that the previous screen (Login) was still mounted after navigating away from it - and in that component there was a navigation action being fired based on newProps that it receives. So the fact that it was still mounted meant it kept receiving those props and would fire the navigation action.. But all sorted now, thanks :)
