### ISSUE TITLE
NavigationActions.reset the issue of flashing screen

### ISSUE THREAD

**Issue by 94cstyles** [react-community/react-navigation#2084]
I have the screen like this:
- Splash -> `this.props.navigation.navigate('Login')`
- Login -> `this.props.navigation.navigate('Main')`
- Main -> `this.props.navigation.navigate('User')`
- User -> `this.props.navigation.navigate('Setting')`
- Setting -> reset to Main

```javascript
navigation.dispatch(
  NavigationActions.reset({
    index: 0,
    actions: [NavigationActions.navigate({routeName: 'Main'})]
  })
)
```
![gif](http://7xv74p.com1.z0.glb.clouddn.com/ezgif.com-resize.gif)

 **animation seems a little bit not normal**

react: 16.0.0-alpha.12
react-native: 0.46.0
react-navigation: 1.0.0-beta.11
react-redux: 5.0.5
redux: 3.7.1
node: 8.1.2
npm: 5.1.0

**Comment by LCJ-MinYa** [comment]
你试试欢迎页的时候就重置一下，不要让欢迎页存在导航记录里面。

**Comment by 94cstyles** [comment]
@LCJ-MinYa 这样做可以，只要让Main在堆栈第一位就好
但是你看注意到 还有个问题
Main -> User ->  Setting -> Rest('Main')
动画效果是 Setting -> User -> Main 
理想效果就是 Setting -> Main 
不展示user离开的动画 不知道你能明白我的意思么

**Comment by LCJ-MinYa** [comment]
我是用的tab，没有出现你的这种问题，所以无法判断问题出现在什么地方。

**Comment by NSshentu** [comment]
我也出现中间页面闪现的情况，在goBack(key)和reset两种方式都存在中间页面闪现的情况。

**Comment by 94cstyles** [comment]
@NSshentu so 你的解决方案？ 
我现在目前为了避免这个问题 多重back 就直接使用`navigate(...)`跳转
但是这样会让路由堆栈给涨下去

**Comment by NSshentu** [comment]
I also meet the same problem, and i try to use goBack(key) and NavigationActions.reset() . But when animating we can also see the screen flash

**Comment by DCKT** [comment]
Hello,

I've the same issue, is there a way to navigate to screen and then reset the navigation ?

**Comment by 94cstyles** [comment]
@brentvatne @dikaiosune @ide @skevy 
We need your help...

**Comment by jeremaihloo** [comment]
#1865 
#1839 
#1263 
#1493 

these issues may be helpful.

**Comment by walkerXiong** [comment]
@94cstyles 想问下，splash部分的动画是怎么做的？感谢。

**Comment by limichange** [comment]
@walkerXiong Look at `react-native-splash-screen`

**Comment by kelset** [comment]
Closing this in favor of #1493 since it's the one with the most comments and proposed solution (just trying to reduce redundancy)

**Comment by 94cstyles** [comment]
I have submitted a PR [https://github.com/react-community/react-navigation/pull/2520] to solve this problem. Why has not passed and merged? @kelset

**Comment by kelset** [comment]
1) branch is outdated
2) there are still some changes to be done (read vonovak feedback)
