### ISSUE TITLE
How to begin StackNavigator on certain level?

### ISSUE THREAD

**Issue by Tom29** [react-community/react-navigation#2086]
I have only one screen and calls itself.

```
    module.exports = StackNavigator({
    	Parent: { screen: PickCategory },
    })

```
Currently, i navigate to screen level i wanted on `componentWillMount`.
But i can see the transition, it's ugly and annoying.

I wanna load StackNavigator with specified level without animation.
Is it posible?

**Comment by KylePalko** [comment]
```
this.props.navigation.dispatch(
    NavigationActions.reset({
        index: 0,
        actions: [
            NavigationActions.navigate({ routeName: 'route-name' })
        ]
    })
)
```

Using a `reset` should navigate without animation. You will lose your navigation "history" (stack) in doing this, so you'll need to recreate that if that is a problem.

**Comment by Tom29** [comment]
@KylePalko And how do i pass parameter on it like:
`this.props.navigation.navigate("Parent", {catId: 12})`
I need parameter to recognize this is the child category screen, not parent.

I've tried on `componentDidMount` and it keep reseting forever.
How do i know when to stop the reseting action?

**Comment by Tom29** [comment]
@KylePalko I've tried this way, but still see the transition.

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
