### ISSUE TITLE
TabNavigator conflict gesture !

### ISSUE THREAD

**Issue by wuyunqiang** [react-community/react-navigation#2088]
### Current Behavior
![cur](https://user-images.githubusercontent.com/13480948/27945980-1d5f2298-6322-11e7-9fb5-6e4dc3ec1bb5.gif)

### Expected Behavior
![exp](https://user-images.githubusercontent.com/13480948/27945622-64d7a1b0-6320-11e7-8e8a-63ceadda7fee.gif)

### Your Environment
 "react": "16.0.0-alpha.6",
 "react-native": "0.44.3",
 "react-navigation": "^1.0.0-beta.11",
  node: v8.0.0
  npm: 5.0.1

code:
  constructor(props) {
    super(props);
    this.state = { trans: new Animated.ValueXY({ x: 0, y: 0 }), };
    this._panResponder = PanResponder.create({
      onStartShouldSetPanResponder: () => true, // 响应手势
      onStartShouldSetResponderCapture: () => true,
      onMoveShouldSetPanResponder: () => true,
      onMoveShouldSetPanResponderCapture: () => true,
      onPanResponderMove: Animated.event(
              [null, { dx: this.state.trans.x, dy: this.state.trans.y }] // 绑定动画值
          ),
      onPanResponderRelease: () => { // 手松开，回到原始位置
        Animated.spring(this.state.trans, { toValue: { x: 0, y: 0 } }
              ).start();
      },
      onPanResponderTerminate: () => { // 手势中断，回到原始位置
        Animated.spring(this.state.trans, { toValue: { x: 0, y: 0 } }
              ).start();
      },
      onResponderTerminationRequest: () => false
    });
    this.state.trans.addListener(this.animateListener);
  }

 render() {
    return (
      <View style={[styles.container, { backgroundColor: 'blue' }]}>
        <Animated.View
          style={{ width: 100,
            height: 100,
            backgroundColor: 'red',
            transform: [
                      { translateY: this.state.trans.y },
                      { translateX: this.state.trans.x },
            ],
          }}
          {...this._panResponder.panHandlers}
        />
      </View>
    );
  }

tab:
const TabContainer = TabNavigator(
  {
   ...ROUTER
  },
  {
    lazy: true,
      **swipeEnabled: true,**
    tabBarPosition: 'bottom',
    animationEnabled: true,
    tabBarOptions: {
      activeTintColor: '#3e9ce9',
      inactiveTintColor: '#999999',
      showIcon: true,
      style: {
        backgroundColor: '#fff'
      },
      indicatorStyle: {
        opacity: 0
      },
      tabStyle: {
        padding: 0
      }
    }
  }
);

I need help!!!

**Comment by KylePalko** [comment]
His code again, for readability:

```
constructor(props) {
    super(props);
    this.state = { trans: new Animated.ValueXY({ x: 0, y: 0 }), };
    this._panResponder = PanResponder.create({
        onStartShouldSetPanResponder: () => true, // 响应手势
        onStartShouldSetResponderCapture: () => true,
        onMoveShouldSetPanResponder: () => true,
        onMoveShouldSetPanResponderCapture: () => true,
        onPanResponderMove: Animated.event(
            [null, { dx: this.state.trans.x, dy: this.state.trans.y }] // 绑定动画值
        ),
        onPanResponderRelease: () => { // 手松开，回到原始位置
            Animated.spring(this.state.trans, { toValue: { x: 0, y: 0 } }
            ).start();
        },
        onPanResponderTerminate: () => { // 手势中断，回到原始位置
            Animated.spring(this.state.trans, { toValue: { x: 0, y: 0 } }
            ).start();
        },
        onResponderTerminationRequest: () => false
    });
    this.state.trans.addListener(this.animateListener);
}

render() {
    return (
        <View style={[styles.container, { backgroundColor: 'blue' }]}>
<Animated.View
    style={{ width: 100,
        height: 100,
        backgroundColor: 'red',
        transform: [
        { translateY: this.state.trans.y },
        { translateX: this.state.trans.x },
    ],
    }}
    {...this._panResponder.panHandlers}
/>

);
}

tab:
    const TabContainer = TabNavigator(
        {
            ...ROUTER
        },
        {
            lazy: true,
            swipeEnabled: true,
            tabBarPosition: 'bottom',
            animationEnabled: true,
            tabBarOptions: {
                activeTintColor: '#3e9ce9',
                inactiveTintColor: '#999999',
                showIcon: true,
                style: {
                    backgroundColor: '#fff'
                },
                indicatorStyle: {
                    opacity: 0
                },
                tabStyle: {
                    padding: 0
                }
            }
        }
    );

```

**Comment by JKonTiki** [comment]
+ 1

**Comment by wuyunqiang** [comment]
I need help !!!
how I can do ?

**Comment by wuyunqiang** [comment]
@brentvatne

**Comment by lionel95200x** [comment]
I have same problem, do you have any solutions ?

**Comment by wuyunqiang** [comment]
@lionel95200x  sorry no.

**Comment by JKonTiki** [comment]
I ended up, at different times, using three different semi-solutions.


1) Move the panResponder outside of your navigator. This probably wouldnt make sense for most things that have to fit into another screen, but if your view is position: 'absolute' then consider it as at least a temp fix. This one actually made sense for me as my view filled the whole screen.

2) Make your View into a [Modal](https://facebook.github.io/react-native/docs/modal.html). Modals automatically assert themselves on top of everything else (or at least over your navigator), so dragging them around might cut off the gesture from going to the panResponder. If you your Modal's set `animation={'none}` `transparent={true}` and `visible={true}` then it will behave much the same as other Views (i have however noticed an issue where my modal would flash very quickly at the beginning and end of rendering -- not sure if that's universal but if anyone else has an insight on it please let me know!

3) [This hack](https://github.com/react-community/react-navigation/issues/1760) by @arnaubennassar actually worked for me (needed for a different objective actually). Although it's never satisfying to step in and play w/ your node modules, I was totally able to connect my `node_modules/react-navigation/src/views/TabView/TabView.js` to redux and have it decide to enableSwipe based on my state.

**Comment by JKonTiki** [comment]
^^for solution #3 here is the render method of my TabView.js file.*

_If you're not using Redux then I'm not sure how applicable this is._

```render() {
    const {
      router,
      tabBarComponent,
      tabBarPosition,
      animationEnabled,
      lazy,
      screenProps,
    } = this.props;

    let { swipeEnabled } = this.props;
    if (this.props.blockNavSwipe) {
      swipeEnabled = false;
    }

    let renderHeader;
    let renderFooter;
    let renderPager;

    const { state } = this.props.navigation;
    const options = router.getScreenOptions(
      this.props.childNavigationProps[state.routes[state.index].key],
      screenProps || {}
    );

    const tabBarVisible = options.tabBarVisible == null
      ? true
      : options.tabBarVisible;

    if (tabBarComponent !== undefined && tabBarVisible) {
      if (tabBarPosition === 'bottom') {
        renderFooter = this._renderTabBar;
      } else {
        renderHeader = this._renderTabBar;
      }
    }

    if (animationEnabled === false && swipeEnabled === false) {
      renderPager = this._renderPager;
    }

    const props = {
      lazy,
      animationEnabled,
      swipeEnabled,
      renderPager,
      renderHeader,
      renderFooter,
      renderScene: this._renderScene,
      onRequestChangeTab: this._handlePageChanged,
      navigationState: this.props.navigation.state,
      screenProps: this.props.screenProps,
      style: styles.container,
    };

    return <TabViewAnimated {...props} />;
  }
}

function mapStateToProps(state) {
  return {
    blockNavSwipe: state.blockNavSwipe,
  };
}

function mapDispatchToProps(dispatch) {
  return {};
}


export default connect(mapStateToProps, mapDispatchToProps)(withCachedChildNavigation(TabView));

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },

  page: {
    flex: 1,
    overflow: 'hidden',
  },
});
```


*Just a reminder that editing anything in your node_modules folder is dangerous as that is vendor code wiped when you update libraries or run `npm install`. I'd copy and paste the file somewhere not ignored by your .gitignore file so you dont lose your code. you'll just have to use it to update the file in your node_modules everytime it gets wiped.

**Comment by wuyunqiang** [comment]
@JKonTiki  
I not using Redux.
I try to solution 2,yes , dragging them around might cut off the gesture from going to the panResponder.but this like {swipeEnabled: false}.not my Expected Behavior.
About solution 1. how to do Move the panResponder outside of your navigator ?

**Comment by JKonTiki** [comment]
@wuyunqiang I was thinking just by rendering it as a sibling to your navigator, probably at the very root of your app. 

e.g. : 

```
<App>
     <TabNavigator />
     <CustomPanResponderComponent />
</App>

```

this should work but might not be ideal for your data flow, as I imagine you may want to pass some state down to your customComponent, at the very least when it should render. I guess this is more practically a redux solution as well, but perhaps you could flow any props up through the TabNavigator to your App component and then down into your customPanResponderComponent. I can understand though that that wouldnt sound very fun for many apps :/

**Comment by wuyunqiang** [comment]
sorry I don't know what to do. 
Can you show me you code.
if you use redux. is ok. I changed to redux. 
how to combin action/reducer.

**Comment by wuyunqiang** [comment]
@JKonTiki

**Comment by lionel95200x** [comment]
@wuyunqiang Have you found any solution with redux ?

**Comment by brentvatne** [comment]
this is a problem with how react-native handles gestures, so this is more of an upstream react-native issue. an alternative is in progress: https://github.com/kmagiera/react-native-gesture-handler

**Comment by wuyunqiang** [comment]
@brentvatne 
I used react-native-gesture-handler.it not ok.
I setting react-navigation { gesturesEnabled: true,} and not available;
Scrollview to scroll is bad effect.
if I delete code of android Mainactivity, I can swipe. react-navigation  and Scrollview is ok.
but the quesstion still here.

**Comment by brentvatne** [comment]
it is a work in progress as i mentioned.

**Comment by wuyunqiang** [comment]
yarn add react-native-gesture-handler
react-native link react-native-gesture-handler
run ios bug：
![gesture](https://user-images.githubusercontent.com/13480948/28557790-0b1909b4-7141-11e7-98a7-886f1676e0a4.png)

run android like I said.

**Comment by brentvatne** [comment]
you might have to wait a week or so until a first version is released

**Comment by wuyunqiang** [comment]
you mean 0.46->1.0 right?
ok I hope , I can know if this fixed.

**Comment by lifh1234** [comment]
@wuyunqiang Have you found any solution ?

**Comment by telmen** [comment]
Anything on this?

**Comment by dray356** [comment]
Any elegant solutions for this so far?

**Comment by woshihuxingtan** [comment]
Any elegant solutions so far for iOS? Android side don't have this issue...

**Comment by ninechung** [comment]
gesturesEnabled: false,

**Comment by lalitkhedkar** [comment]
I am facing the same issue.. any update on this? already tried swipeEnabled and gesturesEnabled but not working..

**Comment by jeffreybrowning** [comment]
@brentvatne can we get an update?
