### ISSUE TITLE
TabView - iOS bottom tabs can get pushed off screen

### ISSUE THREAD

**Issue by sagivo** [react-community/react-navigation#209]
simple text view in a page. you can see that the tab navigation disappears right after loading:
![giphy](https://cloud.githubusercontent.com/assets/1484886/22673224/a057dce2-ece1-11e6-8668-83415e3f04b5.gif)

when changing to `tabBarPosition: 'top'` it renders correctly
<img width="280" alt="screen shot 2017-02-07 at 2 56 26 am" src="https://cloud.githubusercontent.com/assets/1484886/22673185/4e81f27c-ece1-11e6-8655-a096604e648b.png">

**Comment by ericvicenti** [comment]
Yikes. Is this issue on the beta.1, or on master? (You may want to try the latest)

Could you also paste the simplest code that will show us how to replicate the issue?

**Comment by sagivo** [comment]
@ericvicenti i'm on latest master. will isolate a code sample soon

**Comment by sagivo** [comment]
here is the sample source code:
```js
import React, {Component} from 'react';
import { TabNavigator } from 'react-navigation';
import { Provider } from 'react-redux';
import store from './../models/store'

import ComposeContainer from './ComposeContainer';
import FeedContainer from './FeedContainer';

const Tab = TabNavigator(
{
  Compose: {
    screen: ComposeContainer,
  },
  Feed: {
    screen: FeedContainer,
  },
}, {
  // tabBarPosition: 'top',
});


export default class App extends Component {
  render() {
    return (
      <Provider store={store}>
        <Tab />
      </Provider>
    );
  }
}
```
the screen have simple <text> inside them and nothing more

**Comment by sagivo** [comment]
EDIT - the tutorial sample **is** working. investigating now what is the difference in my case.

**Comment by satya164** [comment]
That's so weird. I can't think of a reason it will happen, except if the height of the container changes. Have you got a repro yet?

**Comment by sagivo** [comment]
the more i dig into this bug the more i think it has nothing to do with this lib and looks like an issue we have in our internal listview. closing for now.

**Comment by sagivo** [comment]
finally narrowed the issue - i don't know if it's by design (and in that case feel free to close the issue) but - 
if you have a view that is vertically bigger than the screen size, and no scrollview is in place, the tabs will never show.
for example, tale the tutorial sample (the one i posted above) and change one of the screen to have something like: 
```js
render() {
    return (
      <View style={{paddingVertical: 1500}}>  // <----- add this
        <Button
          onPress={() => this.props.navigation.navigate('Notifications')}
          title="Go to notifications"
        />
      </View>
    );
  }
```
this will cause the view to overflow and the tabs to never be presented.

**Comment by satya164** [comment]
> if you have a view that is vertically bigger than the screen size

Yeah, so basically what I said above. Not sure what's the alternative except hardcoding the tabbar height.

> will probably happen if you use tab view with a list-view that has more data than can be shown on the screen.

Why would it happen for ListView? ListViews have scroll enabled in them.

**Comment by sagivo** [comment]
@satya164 well from some reason looks like it doesn't work for a listview. try this sample:

```js
import React, { Component } from 'react';
import { TabNavigator } from 'react-navigation';
import { AppRegistry, Text, Button, ListView, View, StyleSheet } from 'react-native';

const paddingVertical = 30; //change to bigger value like 300 and the tabs will not show

const rows = [
  {id: 0, text: 'aaa'},
  {id: 1, text: 'bbb'},
]

export default class App extends Component {
  render() {
    return (
      <MyApp/>
    );
  }
}

class MyHomeScreen extends React.Component {
  static navigationOptions = {
    tabBar: {
      label: 'Home',
    },
  }

  constructor(props) {
    super(props);

    const rowHasChanged = (r1, r2) => r1.id !== r2.id
    const ds = new ListView.DataSource({rowHasChanged})
    this.state = { dataSource: ds.cloneWithRows(rows) };
  }

  render() {
    return (
       <ListView
        dataSource={this.state.dataSource}
        renderRow={(data) => <Text style={{paddingVertical}}>{data.text}</Text>}
      />
    )
  }
}

class MyNotificationsScreen extends React.Component {
  static navigationOptions = {
    tabBar: {
      label: 'Notifications',
    },
  }

  render() {
    return (
      <Text>hi</Text>
    );
  }
}

const MyApp = TabNavigator({
  Home: {
    screen: MyHomeScreen,
  },
  Notifications: {
    screen: MyHomeScreen,
  },
}, {
  tabBarOptions: {
    activeTintColor: '#e91e63',
  },
});
```

**Comment by dpyeates** [comment]
I've been pulling my hair out with the same problem - I ripped my app apart trying to figure out the problem so I'm glad its not my app and others are seeing the same issue. I just wish I checked here earlier! In my case I'm using a ScrollView and when the content of the scrollview gets bigger than the height of the screen, the tabs disappear.

**Comment by satya164** [comment]
Hey guys, sorry for the trouble. I just pushed a fix https://github.com/react-native-community/react-native-tab-view

It would be great if you could help me test it out before I update the version in this repo.

**Comment by dpyeates** [comment]
@satya164 worked for me! Thank you for such a quick response.

**Comment by sagivo** [comment]
@satya164 not sure i have a way to test it as i rely on `TabNavigator` under `react-navigation`, can you push it to a branch here?

**Comment by satya164** [comment]
@sagivo you can replace `react-native-tab-view` inside your `node_modules` folder with the one I linked to

**Comment by ng-hai** [comment]
I have the same issue.

**Comment by satya164** [comment]
@ng-hai did you try https://github.com/react-community/react-navigation/issues/209#issuecomment-278820032 ?

**Comment by ng-hai** [comment]
I've just temporary fixed by using `ScrollView` with `height: Dimension.get('window').height`. I don't have enough time to try; my deadline is coming, will try later. Thanks !

**Comment by sagivo** [comment]
@satya164 the update looks good, it's an important update!

:shipit:

**Comment by ng-hai** [comment]
I have fixed by wrapping out Navigator with a `View` parent that has `flex: 1` so I can use normal `View` inside TabNavigator.

// My Nested Navigation
![image](https://cloud.githubusercontent.com/assets/19520278/22900264/51a62f34-f260-11e6-8cae-ed851ac2ad24.png)

// main.js
![image](https://cloud.githubusercontent.com/assets/19520278/22900163/f5fd7f2a-f25f-11e6-8e66-dec49f35466e.png)

// TabView
![image](https://cloud.githubusercontent.com/assets/19520278/22900222/1d629582-f260-11e6-87d4-2762154266d0.png)

**Comment by sckoh** [comment]
I have the same problem after I update my react-navigation to 1.0.0-beta.9

**Comment by dpyeates** [comment]
I also have just upgraded to 1.0.0-beta.9 and this problem has re-appeared. I'm losing by tab bars after initial render when the scrollview is bigger than the window.
