### ISSUE TITLE
StackNavigator load between different StackNavigator

### ISSUE THREAD

**Issue by AlmogRnD** [react-community/react-navigation#2090]
I have the following StackNavigator

```
export const OauthNavigator = StackNavigator({
    Login: {
        screen: Login,
        navigationOptions: {
            title: "Login",
            headerLeft: null,
        },
    },
    ResetPassword: {
        screen: ResetPassword,
        navigationOptions: {
            title: "Reset Password",
            headerLeft: null
        },
    }
}); 
```

And then I have my main navigation 

```
// Main navigation StackNavigator
export const MainScreenNavigator = StackNavigator({
    Home: {
        screen: TabsNavigation,
    },
    Drawer: {
        screen: MainDrawerNavigator
    }
});
```

I'm using redux how would I load the different ones

Here is my reducer 
```
const AppReducer = combineReducers({
    nav: (state = initialNavState, action) => {
        switch(action.type) {
            case 'LOGIN':
                return AppNavigator.router.getStateForAction(NavigationActions.navigate({ routeName: 'Login' }), state);
            case 'LOGOUT':
                return AppNavigator.router.getStateForAction(NavigationActions.navigate({ routeName: 'Login' }), state);
            case 'RESET_PASSWORD':
                return AppNavigator.router.getStateForAction(NavigationActions.navigate({ routeName: 'ResetPassword' }), state);
            case 'MAIN':
                return AppNavigator.router.getStateForAction(NavigationActions.navigate({ routeName: 'Main' }), state);
            case 'TEAM':
                return AppNavigator.router.getStateForAction(NavigationActions.navigate({ routeName: 'Teams' }), state);
            default:
              return AppNavigator.router.getStateForAction(action, state);
        }
    },
```

**Comment by AlmogRnD** [comment]
I'm closing this, I'm moving onto react-native-router-flux it's much better and uses the react navigation API 

- Based on latest React Navigation API
- Separate navigation logic from presentation. You may change now navigation state directly from your business logic code - stores/reducers/etc. navigationStore
- Built-in state machine (former Switch replacement) - each ‘scene’ could have onEnter/onExit handlers. onEnter handler could be async. For successful termination of onEnter, success handler (if defined) will be executed (if success is string then router will navigation to that Scene), in case of handler's failure failure (if defined) will be run. It will allow to build authentication, data validation and conditional transitions in very easy way.
- MobX-powered, all used scenes are wrapped as 'observer' automatically. You may subscribe to navigationStore (former Actions), observe current navigation state, etc. If you are using Redux, skip this.
- Flexible nav bar customization, that is not allowed by react navigation right now: https://github.com/react-community/react-navigation/issues/779
- Drawer support (provided by reactnavigation)
- 'Lightbox' support (used by popups like Error alert within Example project)

**Comment by tywoodpav** [comment]
imo `react-navigation` api is more elegant and enforces better patterns than `react-native-router-flux` (especially with redux). If they're build on the same thing, why not use the original? 

I used rnrf for months before switching to react-navigation. Pavel is great and super helpful, but react-navigation is just better. Sucks that theres so many open issues though, but rnrf has more by default.

Theres things I miss like `Actions.currentScene` and `onEnter/onExit`, but those are worth the easier customization imo.
