### ISSUE TITLE
How to pass back function reference into custom header?

### ISSUE THREAD

**Issue by xahon** [react-community/react-navigation#2095]
How can i pass function that pops current route into my own header?

When i define navigator `this` context doesn't have props key
```
StackNavigator({
   Scene: {
      screen: MyComponent,
      navigationOptions: {
            header: <MyCustomHeader onBack={ dont_know_what_can_i_pass_here? } />
      }
   }
})
```

And `MyCustomHeader` doesn't have `navigation` property

I suppose this plugin should have static navigator instance to provide functionality to go to route without special component instance

Don't understand what to do

**Comment by matthamil** [comment]
See https://github.com/react-community/react-navigation/issues/145#issuecomment-281418095 for details on passing a function into a header element.

**Comment by xahon** [comment]
This cannot be implemented in my situation. Passing props working only for native component `Header`, so i can't get parent context in it at all

**Comment by xahon** [comment]
In addition later i will need to pass extra props to get complex header with not only title and back button, but another data
