### ISSUE TITLE
TabNavigator header

### ISSUE THREAD

**Issue by xahon** [react-community/react-navigation#2096]
How can i create something like this

```
Main: {
  screen: TabNavigator({
    Contacts: {
      screen: ContactsView
    },
    Projects: {
      screen: ProjectsView
    }
  }),
  navigatorOptions: {
    header: <Text>HEADER</Text>
  }
}
```

`navigatorOptions` here is not working

**Comment by matthamil** [comment]
Your screen will need to be a StackNavigator to have a header. TabNavigators by default do not have a header component. StackNavigators, however, do.

**Comment by xahon** [comment]
![screenshot from 2017-07-08 16-52-23](https://user-images.githubusercontent.com/18731681/27983390-37994f3a-63fe-11e7-831b-0b16d960f5ff.png)
I need to create something like this. Including custom header and custom tab switchers

**Comment by xahon** [comment]
So i need TabNavigator

**Comment by xahon** [comment]
I solved this problem. Just include header in each TabNavigator child. Don't know is this right?

**Comment by jsbranco** [comment]
@xahon do you mean you added into each screen a header component?

**Comment by xahon** [comment]
@jsbranco yes

**Comment by jsbranco** [comment]
@xahon  right, I also did the same approach for one of my projects.  The current project I am working on I did used TabNavigator as base, and each screen in the TabNavigator is a StackNavigator.

My use case for this current projects requires each screen to have its own stack so it fits nicely.

**Comment by xahon** [comment]
@jsbranco Didn't you think to do navigator as singleton for easier navigation?

**Comment by xahon** [comment]
@jsbranco I had remake my project from react-native-router-flux to your plugin ans stucked into #2095 problem. Another navigator plugins have single navigator instance and was more comfortable, but their unintuitive behavior make me search antoher plugin like this. I cannot find gold mean in this dozens of plugins

**Comment by jsbranco** [comment]
@xahon I know, is like almost every day there is a new library to handle the same problem.

I reckon in certain cases it feels more natural to nest navigators, the level of complexity added doesn't seem to be too much to put me off. 

Then again, some projects you really don't need nesting if you are for example having an app which only has Tabs and then from the tabs you popup a modal then it works pretty well. 

To me nesting navigators doesn't seem to still keep navigation relatively easy to navigate and develop.

Although this project is still evolving but currently I am sticking with this one because so far I have not encountered any big obstacles while working with it.

**Comment by kaueDM** [comment]
@xahon can you show an example? I'm stucked in the same problem

**Comment by xahon** [comment]
@kaueDM I just use RNRF with custom header component that has `touchable`. I've created layouts and wrap into them all of my screens. Each layout has this custom header and back button (touchable)

**Comment by mahmutduva** [comment]
You can use StackNavigator and TabNavigotor together. 

Main
`const Main = StackNavigator({
  Main: {
    screen: Tabs
  }
})`

Tabs
`export const Tabs = TabNavigator({
  X: {
    screen: XScreen,
    navigationOptions: {
      tabBarLabel: 'X',
      title: 'X Title' 
    }
  },
  Y: {
    screen: YScreen,
    navigationOptions: {
      tabBarLabel: 'Y',
      title: 'Y Title' 
    }
  },
  Z: {
    screen: ZScreen,
    navigationOptions: {
      tabBarLabel: 'Z',
      title: 'Z Title' 
    }
  }
})`

**Comment by zaguini** [comment]
You can set the `tabBarComponent`, in the second argument of the `TabNavigator` function to a wrapped view containing the actual tab bar. Look:

```js
TabNavigator(tabs, {
  tabBarComponent: (props, state) => (
    <View>
      {/* your code here */}
      <TabBarBottom {...props} {...state} />
    </View>
  ),
})
```

Don't forget to include the `TabBarBottom` component from the `react-navigation` package!

**Comment by i2chris** [comment]
If i make each screen within a TabNavigator a Stack then I can no-longer pass params to this stack and all the other tabs.
