### ISSUE TITLE
How to slide the tab bar down and offscreen?

### ISSUE THREAD

**Issue by EdmundMai** [react-community/react-navigation#2097]
I would like to animate and hide the tab bar off the screen. Is there an option to do this? I've tried this: https://stackoverflow.com/questions/44982203/react-navigation-how-to-animate-the-tab-bar-so-that-it-slides-off-screen

but it doesn't work well. It flashes quite often

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
