### ISSUE TITLE
Android back button behavior

### ISSUE THREAD

**Issue by vonovak** [react-community/react-navigation#21]
Is there a plan to introduce the same component that is in ex-navigation for this purpose?  Thanks a lot for this lib! 

What I have in mind is that the android back button "just works" while it can be overridden like [this](https://github.com/exponent/ex-navigation#android-back-button-handling) i.e. not worrying about it but having the ability to control what happens when the back button on android is pressed, if needed.

use case: I need to select some items from a list, and on android, the back button takes me out of the "selection mode", similar to selecting mail in gmail app.
![1](https://cloud.githubusercontent.com/assets/1566403/22371145/a7abd600-e495-11e6-84e7-558475fce533.png)

**Comment by satya164** [comment]
Can you explain a bit more what you mean? Which component? What's the use case?

**Comment by tlvenn** [comment]
If I had to guess, I think the OP meant:
> Android back button handling (it just works, no need to do anything)

**Comment by vonovak** [comment]
Sorry for not giving more details @satya164 . I have updated the desciption.

**Comment by satya164** [comment]
@vonovak I think what you're asking could be done easily with [BackAndroid](https://facebook.github.io/react-native/docs/backandroid.html) directly

```js
componentDidMount() {
  this._listener = BackAndroid.addListener('hardwareBackPress', () => {
    if (shouldDoSomething) {
      doSomething();
      return true;
    }
  });
}

componentWillUnmount() {
  this._listener.remove();
}
```

**Comment by vonovak** [comment]
@satya164 I was assumming that the android back button "just works" out of the box - i.e. it does a `pop()` unless I specify otherwise. That is not the case, it seems?

**Comment by satya164** [comment]
@vonovak yes, it works out of the box, and you can override it by attaching a listener in your component and returning `true` from the listener.

**Comment by vonovak** [comment]
ok, great! let me know where I should land a PR documenting this if you're interested.

**Comment by satya164** [comment]
@vonovak I'm not really sure. since the behaviour comes from`BackAndroid`. We're not doing anything special to allow you to override it.

**Comment by vonovak** [comment]
@satya164 I see, no need for special docs, then.

**Comment by Ehesp** [comment]
@satya164 Just came across this. Using StackNavigator, when traversing down the stack (child pages), BackAndroid closes the app rather than navigating back up the stack until it hits the Init route, which would then close the app. 

If this is intended, like you say it's easily handled - just I read this thread thinking the default behaviour would be like what I just described. Cheers

**Comment by satya164** [comment]
@Ehesp sorry I didn't get what you mean. doesn't back button behave the same as `navigation.goBack`?  can open an issue with a sample if it doesn't?

**Comment by Ehesp** [comment]
Not here, however I'm integrating it with Redux so that might be the issue. Will investigate more and see if I can replicate without Redux.

**Comment by Fenwil** [comment]
@Ehesp Did you still have the same problem ? I have exactly the same issue but I fix it with what @satya164 said about `BackAndroid`

```javascript
BackAndroid.addEventListener('hardwareBackPress', () => true);
````

I don't know if this is the correct solution but this doesn't closes my App and also allows me to navigate back keeping the navigators history.

**Comment by lu79931748** [comment]
@lndgalante you solve this problem already ?
`componentWillMount(){
    BackHandler.addEventListener('hardwareBackPress', this._onBackAndroid)
}

_onBackAndroid = () => {
    console.log(this.props.navigation.state.routeName)
    if (this.lastBackPressed && this.lastBackPressed + 2000 >= Date.now()) {
        return false;
    }
    this.lastBackPressed = Date.now();
    toastShort('Press Again Exit App');
    return true;
};

componentWillUnmount(){
    BackHandler.removeEventListener('hardwareBackPress', this._onBackAndroid)
}`
`_onBackAndroid`does not work until back root route

**Comment by lu79931748** [comment]
@lndgalante you solve this problem already?
### componentWillMount(){
    BackHandler.addEventListener('hardwareBackPress', this._onBackAndroid)
}

_onBackAndroid = () => {
    console.log(this.props.navigation.state.routeName)
    if (this.lastBackPressed && this.lastBackPressed + 2000 >= Date.now()) {
        return false;
    }
    this.lastBackPressed = Date.now();
    toastShort('Press Again Exit App');
    return true;
};

componentWillUnmount(){
    BackHandler.removeEventListener('hardwareBackPress', this._onBackAndroid)
}

the method of _onBackAndroid does not work until back root route
