### ISSUE TITLE
Ability to configure navigationOptions based on *this* (context or other props)

### ISSUE THREAD

**Issue by joncursi** [react-community/react-navigation#210]
It's great that there is a dynamic option for specifying `navigationOptions` that are based on data. However, does it *have to be* `static`?

`navigationOptions` would be extremely powerful if it could be generated based on other entities, such as context or other props (fun stuff that requires access to `this`). As an example, I use [react-intl](https://github.com/yahoo/react-intl) to translate all of my copy into the appropriate language via context - including navigation headers, and left and right text. Unfortunately this setup is not currently supported in `react-navigation` because `navigationOptions` does not support context, because it lacks access to `this`:

```jsx
import { intlShape } from 'react-intl';
import React, { Component } from 'react';

class MyComponent extends Component {
  static contextTypes = {
    intl: intlShape.isRequired,
  };

  static navigationOptions = {
    title() {
      return this.context.intl.formatMessage({ // this doesn't work , pun intended :(
        id: 'general.profile',
      });
    },
  };

  render() {
    <Something />
  }
}
```

Another example would be updating / re-rendering the header when when the data used to generate the initial rendering of `navigationOptions` has been invalidated with new data. I.e. determining a value based on one or more changing conditions, and monitoring for changes to those conditions:

```jsx
import React, { Component } from 'react';

class MyComponent extends Component {
  static navigationOptions = {
    header: {
       visible: this.something.someCondition, // nope :/
     },
  };

  _handleUpdateSomeCondition() {
    updateSomeCondition(somethingNew);
  }

  render() {
    ...
  }
}
```

Another example would be forms. Think of a form with 5 fields, and you want to disable or enable the left or right action based on what the user has or hasn't yet filled out.

**Comment by Paul-Todd** [comment]
#145 hs some good ideas around this but it is currently blocked with another bug.

**Comment by satya164** [comment]
Relevant https://github.com/react-community/react-navigation/issues/296#issuecomment-279586617

**Comment by ericvicenti** [comment]
One of the reasons why props and context is not supported is because these are the sorts of things that will break if your navigator is implemented a different way.

Little secret: StackNavigator is designed in such a way that it can eventually be swapped out with a native hybrid implementation. In that case, the right button and screen components are both top-level react components, and no context can be shared between them. Params may be very simple, but they can easily come from native native code 😄

**Comment by satya164** [comment]
> Params may be very simple, but they can easily come from native code

Native code could send complex data structures like booleans, numbers, nested objects, arrays etc. along with strings too. Only when you decode URLs, you will get only strings. Though this could probably be addressed by a custom `getPathAndParamsForURL` or something.

Maybe I don't have the full picture, but placing such restriction on all apps only because of we cannot automatically decode URLs properly makes it pretty limiting.

**Comment by ericvicenti** [comment]
In my mind, the main reason for keeping params flat is because the flow types get very very confusing if they are flexible. I'm closing this out for now, but we are working towards an API where navigation options are defined as a function of navigationScreenProps

**Comment by timscott** [comment]
Correct me if I am wrong, but without this ability it will not be possible to render tab icons with  badges?

Unfortunately, that's a deal breaker for me. My tabs have badges showing item counts and status indicators based on props. I'm currently using ```react-native-tab-navigator```, which supports this, but has other shortcomings.

**Comment by joncursi** [comment]
@timscott I am using a bad workaround for this right now, but it works. In `componentWillMount` or `componentDidMount`, I am making a call to `setParams` to load prop data into react-navigation as params. This will cause the header to re-render with the desired appearance. Example:

```jsx
  static navigationOptions = ({ navigation }): => ({
    headerTitle: navigation.state.params.headerTitle || `Badge Count: Loading...`,
  });

  componentWillMount() {
    navigation.setParams({
      headerTitle: `Badge Count: ${this.props.badgeCount}`,
    });
  }
```

Initial load shows "Badge Count: Loading..." while the screen transitions, and once the component finished mounting, it updates to "Badge Count: <Number>".

It feels like double the work, but it's functional. Hoping to find a better solution to this soon...

**Comment by timscott** [comment]
Thanks @joncursi. I tried that technique, which I saw in a comment in another issue, and it works. However, I found another way that might be better for me. Using ```redux```:

```javascript
TabIcon = connect(mapStateToProps)(TabIcon);
```

```javascript
static navigationOptions = {
  tabBarIcon: () => <TabIcon />
};
```

From the redux store, I can get what I need to render my tab icon with a dynamic badge. It only works for components, not other kinds of settings, so I may end up using both techniques. Thanks again!

**Comment by xaphod** [comment]
@joncursi I'm not able to get your method to work. I tried sticking the same thing (navigation.setParams -> a button) in componentWillMount(), nothing happens. This method still working for you in today's react-native?

**Comment by noumantahir** [comment]
I need to interact with screen component using the headerRight of navigation bar...is there any workaround for this...?

**Comment by tbarmann** [comment]
@joncursi I'm also not able to get your method to work. `navigate` is not in scope in `ComponentWillMount`. Am I missing something?

**Comment by philwilks** [comment]
@timscott This has just blown my mind and completely changed my understanding of Redux. 

You can just **connect a component**!!!!!!

**Comment by hodgef** [comment]
Thanks! Just for the record though, I ended up creating my own Header component. It saved me a lot of headaches down the road.
