### ISSUE TITLE
How to customize tabs and allow to pass data in them?

### ISSUE THREAD

**Issue by xahon** [react-community/react-navigation#2103]
I need to place number of unread messages into tab buttons. I already have tab button component with styles and function that receives props. How can i replace default tab button with my own components?

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
