### ISSUE TITLE
how to send navigations params to mapStateToProps to react-redux connect?

### ISSUE THREAD

**Issue by buncismamen** [react-community/react-navigation#2104]
I'm trying not to use redux, for my react-navigation to keep it simple, but if that is the only way I will use it.

here is mycode 
```
import React from 'react';
import {
  Button,
  View,
  Text,
} from 'react-native';
import { StackNavigator } from 'react-navigation';
import { connect } from 'react-redux'

class GameScreen extends React.Component {
  static navigationOptions = ({navigation}) => ({
    headerTintColor: 'white',
    headerStyle: {
         backgroundColor:"midnightblue"
       },
    title: navigation.state.params.id,
  });

  render() {
    return (
      <View style={{flex:1, backgroundColor: '#005662'}}>
        <Text>ID</Text>
        <Text>{this.props.game.id}</Text>
        <Text>TITLE</Text>
        <Text>{this.props.game.title}</Text>
        <Text>ICON</Text>
        <Text>{this.props.game.icon}</Text>
        <Text>NAME</Text>
        <Text>{this.props.game.name}</Text>
        <Text>SUBTITLE</Text>
        <Text>{this.props.game.subtitle}</Text>
        <Text>AVATAR_URL</Text>
        <Text>{this.props.game.avatar_url}</Text>
        </View>
    );
  }
}

function mapStateToProps(state, props) {
  return {
    game: state.games.find(item => item.id === /* how to put value from navigation.state.params.id to here */)
  }
}

export default connect(mapStateToProps)(GameScreen);
```

**Comment by kidequinox** [comment]
I'm dealing with same concern. I want to use redux in my app, but not sure if I have to fully integrate it with React-navigation.

Can we do this:
```
componentDidMount() {
   const { params } = this.props.navigation.state;
   this.props.setGameID(params.id).then( () => {
      this.setState({ loaded: true });
   });
}
```
where setGameID is connected with `mapDispatchToProps` and is an async action creator

?

**Comment by nico1510** [comment]
Is `navigation` not available in the `props` parameter in your `mapStateToProps` function ? Like this:
```javascript
function mapStateToProps(state, props) {
  return {
    game: state.games.find(item => item.id === props.navigation.state.params.id)
  }
}

```

**Comment by buncismamen** [comment]
damn you are correct, I have thought about ownProps, but doesn't know how to use it
just realize the parameter that sended by navigationActions is also props.

**Comment by nico1510** [comment]
The structure of navigation.state depends on which type of Navigator you use. You can view the internal state and analyze it in debug mode but I don't think there's documentation on it because it's a internal API which could potentially change in every release. Therefore I wouldn't recommend relying on anything that's in there.

**Comment by stereodenis** [comment]
but how to dynamic change title? (In my case I want to localize title on country change)

**Comment by nico1510** [comment]
like this 
```javascript
class ChatScreen extends React.Component {
  static navigationOptions = (props) => ({
    title: ... // use your props.locale here
  });
  ...
}
```

**Comment by nico1510** [comment]
@buncismamen please consider to close this issue if it was resolved since there are many open issues currently

**Comment by buncismamen** [comment]
@nico1510  oh!, sorry about that I thought contributors/you will close it. OK

**Comment by dustinyoste** [comment]
for any future viewers, this can be done cleanly with the spread operator
```js
const mapStateToProps = (state, props) => ({
  ...props.navigation.state.params,
})

const { prop1, prop2 } = this.props;
```
