### ISSUE TITLE
How can I remove the gesture on navigationbar when I modal a view?

### ISSUE THREAD

**Issue by woodwoodchow** [react-community/react-navigation#2105]
When I modal a view, there will be add a gesture (for dismiss) to the navigationbar automatically。How can I disable the gesture?

**Comment by nolan-m** [comment]
https://reactnavigation.org/docs/navigators/stack

`gesturesEnabled` is a property in `navigationOptions`

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
