### ISSUE TITLE
Styling nested navigators on Android

### ISSUE THREAD

**Issue by FredyC** [react-community/react-navigation#2106]
### Current Behavior
I've prepared this small demo: https://snack.expo.io/B1kOKaJSZ

If you turn on Preview down there, use Android, and then navigate to Scene 3. Result is white screen without text aligned as you can see on Scene 1/2

![Alt text](https://monosnap.com/file/xdUkqOdOD0cmShAs2QfUaKOaN5FEyW.png)

### Expected Behavior
Running the demo on iOS works as expected. Nested scenes are styled correctly.

![Alt text](https://monosnap.com/file/u7CeNCAfOu0J9UJpp1NOlhdciFFtnQ.png)

### Your Environment
Frankly, I am not sure versions included in Snack, cannot seem to find it anywhere.  I've tried running the same thing locally against real device and behavior is the same with these versions of modules.

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.11
| react-native     |  0.45
| node             |  6.10.1
| yarn      | 0.24.6

**Comment by FredyC** [comment]
I've experimented a bit more and it seems that problem is not really about styling. Apparently trying to navigate to a nested screen just displays a blank screen on Android (works perfectly on iOS though). Also when I actually "click" on tab of nested TabNavigator, suddenly it displays correct screen, but using `navigate()` or swiping around just doesn't seem to be working,

https://snack.expo.io/SJE4iferZ

**Comment by sun2rise** [comment]
any news on this?

**Comment by kelset** [comment]
Closing in favor of #1805
