### ISSUE TITLE
how to get params outside react component?

### ISSUE THREAD

**Issue by buncismamen** [react-community/react-navigation#2107]
I know I can do things like this inside react component

```
class ProfileScreen extends React.Component {
static navigationOptions = ({ navigation }) => ({
    title: `Chat with ${navigation.state.params.user}`,
  });
  render() {
    const {state} = this.props.navigation;
    // state.routeName === 'Profile'
    return (
      <Text>Name: {state.params.name}</Text>
    );
  }
}

```

, but how about outside the react component?
because I want to use the params in my `mapStateToProps` function

FYI : I'm using react-navigation with redux integration if that helps

**Comment by nolan-m** [comment]
```
const mapStateToProps = (state, props) => {
  const name = props.navigation.state.params.name;

  return {
    name
  };
}
```

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
