### ISSUE TITLE
navigation params cleared  after dispatch Navigation/BACK 

### ISSUE THREAD

**Issue by ezha86** [react-community/react-navigation#2109]
my navStack contains 2 screens (1 and 2)
i set params for head button like this:  this.props.navigation.setParams(
        {
          onPress1:() => this.onPress1()
        });

i navigate from 1 to 2 via setParam for headerButton like:
onPress1 = () =>{
  this.props.navigation.navigate('2',
     {param: param}); };
}

if i press back button from screen 2:  navigation.dispatch({ type: 'Navigation/BACK' }) 
all works fine and onPress1  is defined at screen 1

but if i do redirect from screen 1 to screen 2 from componentDidMount with condition like this:
componentDidMount(){
    if(condition === true){
      this.props.navigation.setParams(
        {
          onPress1:() => this.onPress1()
        });
      this.props.navigation.navigate('2',
       {param: param})
    }
  } 
and then press back button - onPress1 is undefined at 1 screen

any idea how handle this ?
thanks in advance.

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
