### ISSUE TITLE
[iOS] transition speed is not continuous after pan gesture released

### ISSUE THREAD

**Issue by zzq889** [react-community/react-navigation#211]
As I described in #196 

The transition initial speed should be the same as pan gesture released at the moment, and decrease the velocity by time.

The current animation looks stop at the moment when you swipe fast. I'll send an experimental PR for this later.

**Comment by mkonicek** [comment]
Can you share a video so others can see the bug?

**Comment by zzq889** [comment]
<img width="801" alt="screen shot 2017-02-07 at 11 31 11 pm" src="https://cloud.githubusercontent.com/assets/685488/22697793/89be69cc-ed8d-11e6-8d43-b05bd502e987.png">

**Comment by zzq889** [comment]
Compare:
- [React Navigation Demo Video](https://youtu.be/BSIhrsXdtGM)
- [iOS Native Navigation Demo Video](https://youtu.be/KkCVBVDAeBE)

**Comment by grabbou** [comment]
@zzq889 would you also be interested in working on animations for the header? I got few todos there.

**Comment by zzq889** [comment]
Yes of course. Where can I see the todos?

**Comment by grabbou** [comment]
Nowhere yet, but basically the `todo` I had in mind was to implement a proper animation for back button label on iOS. I'll attach you to my PR to highlight what has to be done :)

**Comment by zzq889** [comment]
Let me guess. Do you want to slide the back title to center than just fade
it?
Mike Grabowski <notifications@github.com>于2017年2月9日 周四下午7:03写道：

**Comment by grabbou** [comment]
Yeah, I think so. Currently it has I guess just the opacity animation. As far as I know, on iOS it moves slightly to the right before animating out. So that would be the first todo. Another one is replacing `Too l...title` label with `Back`, just like iOS does natively.

**Comment by zzq889** [comment]
Yeah, just as I thought. Let me know when you PR.
Mike Grabowski <notifications@github.com>于2017年2月9日 周四下午7:54写道：

**Comment by cihancil** [comment]
@grabbou is it possible if you make bak label optional? It might  be another property of header in navigationOptions.

**Comment by grabbou** [comment]
We will factor that in to the open PR. Thanks for your question.

**Comment by ericvicenti** [comment]
This should be resolved
