### ISSUE TITLE
How does a app use StackNavigator and TabNavigator at the same time?

### ISSUE THREAD

**Issue by zznan0o0** [react-community/react-navigation#2111]
How does a app use StackNavigator and TabNavigator at the same time?
In this "Hello Mobile Navigation", StackNavigator must use AppRegistry, What about TabNavigator?

AppRegistry.registerComponent('SimpleApp', () => SimpleApp);

**Comment by poptocrack** [comment]
Please check the documentation: [Nested tabs](https://reactnavigation.org/docs/intro/nesting)

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
