### ISSUE TITLE
Bottom TabBar Styling Help

### ISSUE THREAD

**Issue by kelvinblade** [react-community/react-navigation#2118]
This is on Android.

1. I am trying to add some spacing between the icon and the top of the tab bar and reduce the spacing between icon and the label.
2. I am trying to change the bottom border color ie Yellow line.
3. I am trying to reduce the spacing, padding left and right inside each cell.

Any idea how I can achieve this? Thanks!

![screenshot_2017-07-10-17-59-20-708_host exp exponent](https://user-images.githubusercontent.com/6658015/28052056-10f871fa-663b-11e7-913c-1f42cfbfed6e.png)

`{

    tabBarPosition: 'bottom',
    animationEnabled: true,
    swipeEnabled: true,
    tabBarOptions: {
      showIcon: true,
      labelStyle: {
        fontSize: 8
      },
      style: {
        backgroundColor: 'grey',
      },
      tabStyle: {
        height: 49
      },
      iconStyle: {
        flexGrow: 0,
        marginTop: 1.5
      }
    }
  }`

**Comment by rulgf** [comment]
For the yellow line use indicatorStyle
`
tabBarOptions: {
indicatorStyle: {
                            backgroundColor: 'transparent',
                    }
            }
`

**Comment by kelvinblade** [comment]
@rulgf thanks for the help. 

Any idea how I can do 1. and 2. ? Still stuck on that

**Comment by rulgf** [comment]
Mmmmm i'm not sure but you could try something like this:  
```
tabStyle: {
      padding: 20
 },
labelStyle:{
       marginTop: -2
}
```
Hope it helps

**Comment by stefli** [comment]
Try this:
`tabStyle: { marginTop: 10 },
labelStyle: { marginTop: 2 }`

**Comment by spencercarli** [comment]
Gonna close this since it's been quiet for a while (trying to clean up issues 😄)

**Comment by RyanWan** [comment]
I did something like this and it worked.
`labelStyle: {
       marginTop:-5,
       marginBottom: 5
     }`

**Comment by rishabhbhatia** [comment]
If you still want the solution, adding `style: { padding: 5 }` inside tabBarOptions works fine for me.

**Comment by captain-xu** [comment]
try this: 
`tabBarOptions: {
            style: {
                marginBottom: -2, //hide border in android
            }
        }`

**Comment by celwell** [comment]
If any Google-searchers are looking to get rid of the top border (like me), check this out:
```javascript
    tabBarOptions: {
      style: {
        borderTopColor: 'transparent',
      },
      // other stuff unrelated:
      labelStyle: {
        marginTop: -7,
      },
      activeTintColor: colors.orange,
      inactiveTintColor: 'gray',
    },
```

**Comment by mr-tost** [comment]
> If any Google-searchers are looking to get rid of the top border (like me), check this out:
> 
> ```js
>     tabBarOptions: {
>       style: {
>         borderTopColor: 'transparent',
>       },
>       // other stuff unrelated:
>       labelStyle: {
>         marginTop: -7,
>       },
>       activeTintColor: colors.orange,
>       inactiveTintColor: 'gray',
>     },
> ```

this king of responses make my days, unfortunately, documentation sometimes skips little details like this

**Comment by jjg77** [comment]
@celwell doesn't seem to work on anroid.  I can't hide the top border.

**Comment by zinaida2mc** [comment]
try:
```
tabBarOptions: {
      style: {
        borderTopWidth: 0,
      },
}
```

**Comment by MatiSera** [comment]
Hi! I'm trying to add that yellow line below the icon. Does anyone know how to add it?
