### ISSUE TITLE
Android StackNavigator headerRight still shows component from previous screen

### ISSUE THREAD

**Issue by twairball** [react-community/react-navigation#2124]
### Current Behavior
When pushing a new screen on `StackNavigator`, `headerRight` navigator bar button from previous screen is still visible on Android. 

![android_right_bar_button_bug](https://user-images.githubusercontent.com/1191601/28105550-78d3a86c-6712-11e7-91cb-824de4874e20.png)

````
/**
 * Right bar button on navigation bar
 */
const RightBarButton = (title, onPress) => {
  return (
    <Button
        title={title}
        color={Colors.purple}
        backgroundColor='white'
        borderRadius={12}
        fontSize={11}
        buttonStyle={{paddingTop: 5, paddingBottom: 5, paddingLeft: 8, paddingRight: 8}}
        onPress={onPress} />
  )
}

const ShopButton = (navigation) => {
  const { navigate } = navigation;
  const onPress = () => {navigate('Shop')}
  return RightBarButton(strings.shop, onPress)
}

const Screens = {

  Invite: {
    screen: Invite,
    path: 'invite', 
    navigationOptions: ({ navigation }) => (
      Object.assign(DefaultHeader, {
        title: strings.invite,
        headerRight: ShopButton(navigation),
      })    
    ),

  Shop: {
    screen: Shop,
    navigationOptions: ({ navigation }) => (
      Object.assign(DefaultHeader, {
        title: strings.shop,
        headerRight: null, // This works fine in iOS, headerRight is blank.
      })
    ),     
  }, 
}

const Config = {
  headerMode: 'float',
  headerTintColor: 'white',
}

const DefaultHeader = {
  headerStyle: {
    backgroundColor: Colors.purple,
  },
  headerTintColor: 'white',
}

export const BasicStack = StackNavigator(Screens, Config)


````

### Expected Behavior
On iOS this works correctly by setting `headerRight: null` in screen options. 

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta1.1
| react-native     |  0.44
| node             | 
| npm or yarn      |

**Comment by twairball** [comment]
FYI Emulator was API 26, Android 8.0

Current workaround is to do `headerRight: <View style={{ backgroundColor: PURPLE, width: 80, height: 40}} />` but clearly far from ideal.

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!

**Comment by Paul-Bird** [comment]
This is still an issue,  headerRight: null  removes the element in iOS but does not in Android.  I don't understand how this is a question.
