### ISSUE TITLE
Documentation wrong param

### ISSUE THREAD

**Issue by dioxmio** [react-community/react-navigation#2126]
### Current Behavior
At the moment the documentation says that to use lazy load on TabNavigator the param should be named: `lazy`
### Expected Behavior
I was seeing no effect when the flag was either on/off. The right param name is `lazyLoad`

I have created https://github.com/react-community/react-navigation/pull/2125 for that matter. Would be awesome if somebody could merge it and save the trouble of having to dive into the code :)

**Comment by matthamil** [comment]
Which version of react-navigation are you using? The prop should be `lazy` as seen [here](https://github.com/react-community/react-navigation/blob/master/src/navigators/TabNavigator.js#L58).

**Comment by dioxmio** [comment]
oh good then it was fixed recently... I am version `1.0.0-beta.8` and the current is `1.0.0-beta.11`. Thanks will be closing the PR then :D
