### ISSUE TITLE
How to goBack with some params?

### ISSUE THREAD

**Issue by Kaelzzs** [react-community/react-navigation#2127]
### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  
| react-native     |  
| node             | 
| npm or yarn      |

**Comment by Manweill** [comment]
i need too

**Comment by ccoeder** [comment]
same here.

**Comment by shangxinbo** [comment]
same here. maybe I prefer to trigger a event in back screen while goBack()

**Comment by Kaelzzs** [comment]
`Maybe` dispatch an action to changed params?

**Comment by Manweill** [comment]
i set mobx store to changed params

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
