### ISSUE TITLE
Click the notification bar to jump

### ISSUE THREAD

**Issue by jiedonglia** [react-community/react-navigation#2129]
### Current Behavior
Use jpush, receive notifications, click the notification bar to jump to the front page now
const ZxptNavigator = TabNavigator({
  rdzx: { screen: RdzxMain },
  qyzx: { screen: QyzxMain },
  lxr: { screen: LxrMain },
  wode: { screen: WodeMain },
})

const MyNavigator = StackNavigator({
  Main: { screen: ZxptNavigator,path:'main' },
  pjyw: { screen: PjywView ,path:'pjyw'},
  pjywmx: { screen: PjywmxView,path:'pjyw/pjywmx' },
})
Click on event：
  JPushModule.addReceiveOpenNotificationListener((map) => {
    console.log("message:" + map.extras);
    MyNavigator
  })

### Expected Behavior
I want to jump to the corresponding business details page
### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  git+https://github.com/react-community/react-navigation.git
| react-native     |  0.44.0
| node             | 
| npm or yarn      |
|jpush-react-native|^1.6.6

**Comment by adrienthiery** [comment]
Did you check out https://reactnavigation.org/docs/guides/linking ?

**Comment by jiedonglia** [comment]
I think my problem is solved by router, but I won't use it

**Comment by jiedonglia** [comment]
The jpush event listening code is written here：

class MyApp extends Component {

  componentDidMount() {
         JPushModule.addReceiveOpenNotificationListener((map) => {
        console.log("点击了消息" + map.extras);
        this.props.navigation.navigate('pjyw')//error!!!!
      })
}
  render() {
    return (
      <MyNavigator ref={nav => { this.navigator = nav; }} />
    )
  }

**Comment by adrienthiery** [comment]
@jiedonglia What is your error when you do `this.props.navigation.navigate('pjyw')` ?

**Comment by jiedonglia** [comment]
because MyApp is not in MyNavigator ,so this.props.navigation is null

**Comment by adrienthiery** [comment]
Would you be able to move your `componentDidMount` function inside your initial component of the Navigator? 

Otherwise, do you use Redux ?

**Comment by jiedonglia** [comment]
I'm not using redux, I'm using the react - navigation if I write it in the Navigator, what pages are I going to write? Or where?

**Comment by adrienthiery** [comment]
You could set your `componentDidMount` function in your `RdzxMain` component, for example.

**Comment by jiedonglia** [comment]
I tried once, I write listening in RdzxMain, appeared the following conditions, if the app is open, jump to the specified page first, and then will be open the app back to the home page, if the app is in the background, will only open the app to the home page, don't jump to any page. It seems to have something to do with push plug-in jpush

**Comment by adrienthiery** [comment]
I think you might have to implement deep linking as show in the docs instead of using jpush then... Sorry 😅

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!

**Comment by hnliyuan** [comment]
How can I get current screen when notification. have any functions?
