### ISSUE TITLE
DrawerNavigator mount screen again when select current screen again

### ISSUE THREAD

**Issue by tamdesktop** [react-community/react-navigation#2130]
I'm using DrawerNavigator to make side menu in my app.
For example, menu have 2 items: home and profile.
If main screen is home screen, open side menu and select home again. DrawerNavigator will mount home screen again and reload all my data. 
My expectation is just close side menu if user select current screen on side menu.

Anyone can help?
Thanks

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
