### ISSUE TITLE
Undefined is not an object(evaluation this.props.navigation.navigate).

### ISSUE THREAD

**Issue by vivekebics** [react-community/react-navigation#2131]
### Current Behavior
I have followed the exact steps given blow. I have the following error (**Undefined is not an object(evaluation this.props.navigation.navigate)).** If am wrong please correct. Please let me know any other steps i need to follow . 

### Expected Behavior
i would like to navigate from one page to another page. 

### Your Environment
Android
![screenshot_1499951977](https://user-images.githubusercontent.com/29792642/28168375-906ea554-67fc-11e7-8104-a5a84e2f2852.png)

react-native-cli: 2.0.1
react-native: 0.46.2

**Comment by abi** [comment]
Can you create a Gist of the file where you are calling this code?

**Comment by abi** [comment]
Please ask questions like this on https://www.reactiflux.com/ You'll get more immediate answers there!

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
