### ISSUE TITLE
react-navigation cannot be used with react-native

### ISSUE THREAD

**Issue by jslvtr** [react-community/react-navigation#2133]
### Current Behavior
The current `react` peerDependency of `react-navigation` is incompatible with the `react` peerDependency of `react-native`.

`react-native`: `react@16.0.0-alpha.12`
`react-navigation`: `react@*`

As per https://github.com/npm/node-semver#prerelease-tags, the `*` does not include prerelease tags, thus:

```
> semver.satisfies('16.0.0-alpha.12', '*')
false
> semver.satisfies('16.0.0-alpha.12', '^16.0.0-0')
true
```

### Expected Behavior
I would expect them to be compatible.

A way to achieve this might be by adding the following peerDependency in `react-navigation`:

```
react@* || react@^16.0.0-0
```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  `1.0.0-beta.11`
| react-native     |  `0.44.0`
| node             |  `4.0.0`
| npm      | `2.14.2`

It may only be an issue in old versions of node or npm; I realise we're outdated here. Nevertheless other frameworks have more flexible peerDependencies:

```
react-redux@5.0.5 wants react@^0.14.0 || ^15.0.0-0 || ^16.0.0-0
```

**Comment by alextreppass** [comment]
👍

**Comment by spencercarli** [comment]
This should all be taken care of now 😄
