### ISSUE TITLE
found: object with keys {backTitle}

### ISSUE THREAD

**Issue by genmmao** [react-community/react-navigation#2134]
I run

react-nativ run-ios

tips

![image](https://user-images.githubusercontent.com/2843284/28177146-7ef6c2e0-682c-11e7-89f7-4348ec5c769d.png)

ExceptionsManager.js:71 Unhandled JS Exception: Objects are not valid as a React child (found: object with keys {backTitle}). If you meant to render a collection of children, use an array instead.
    in View (at CardStack.js:363)
    in CardStack (at CardStackTransitioner.js:110)
    in RCTView (at View.js:132)
    in View (at Transitioner.js:187)
    in Transitioner (at CardStackTransitioner.js:60)
    in CardStackTransitioner (at StackNavigator.js:52)
    in Unknown (at createNavigator.js:33)
    in Navigator (at createNavigationContainer.js:202)
    in NavigationContainer (at renderApplication.js:35)
    in RCTView (at View.js:132)
    in View (at AppContainer.js:98)
    in RCTView (at View.js:132)
    in View (at AppContainer.js:97)
    in AppContainer (at renderApplication.js:34)

This is my code:
import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View
} from 'react-native';

import {
    StackNavigator,
    TabNavigator
} from 'react-navigation';

import List from './creation/index'
import Detail from './creation/detail'
import Edit from './edit/index'
import Account from './account/index'

const MainScreenNavigator = TabNavigator({
    Home: {
        screen: List,
        navigationOptions: {
          tabBarLabel: '首页'
        }
    },
    Edit: {
        screen: Edit,
        navigationOptions: {
          tabBarLabel: '编辑'
        }
    },
    Account: {
        screen: Account,
        navigationOptions: {
          tabBarLabel: '我的'
        }
    },
}, {
    animationEnabled: false, 
    tabBarPosition: 'bottom', 
    swipeEnabled: false, 
    backBehavior: 'none', 
    tabBarOptions: {
        activeTintColor: '#008AC9', 
        inactiveTintColor: '#999', 
        showIcon: true, 
        indicatorStyle: {height: 0}, 
        style: {
            backgroundColor: '#fff', 
        },
        labelStyle: {
            fontSize: 12, 
        },
    },
});

const imoocApp = StackNavigator({
  Home: { screen: MainScreenNavigator },
  Detail: { screen: Detail },
  Edit: { screen: Edit },
  Account: { screen: Account }
}, {
  initialRouteName: 'Home',
  navigationOptions: {
    headerTintColor: '#51c4fe',
    headerStyle: {backgroundColor: "white"},
    headerTitleStyle: {alignSelf: 'center'},
    backTitle: []
},

});

AppRegistry.registerComponent('imoocApp', () => imoocApp);

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.11
| react-native     |  0.46.1
| node             | 8.1.3
| npm or yarn      | 5.2.0

**Comment by rmemoria** [comment]
+1

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
