### ISSUE TITLE
Change goBack transition

### ISSUE THREAD

**Issue by skoob13** [react-community/react-navigation#2136]
Is it possible to change goBack transition to something like navigate animation?

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
