### ISSUE TITLE
Navigation is not visible

### ISSUE THREAD

**Issue by Hayko1994** [react-community/react-navigation#2137]
I've integrated my MainNavigator  with all screens imported while when I ma running it on my ios simulator it shows just white screen and nothing else. It means there is not any error with running an app. I don't know why navigation is not visible.
Here is the code. 
import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { TabNavigator, DrawerNavigator, StackNavigator } from 'react-navigation';

import WelcomeScreen from './screens/WelcomeScreen';
import SigninScreen from './screens/SigninScreen';
import SignupScreen from './screens/SignupScreen';
import HomeScreen from './screens/HomeScreen';
import BusinessScreen from './screens/BusinessScreen';
import TechScreen from './screens/TechScreen';
import EducationScreen from './screens/EducationScreen';
import LifestyleScreen from './screens/LifestyleScreen';
import ProfileScreen from './screens/ProfileScreen';
import FavoritesScreen from './screens/FavoritesScreen';
import SettingsScreen from './screens/SettingsScreen';

export default class App extends React.Component {
  render() {
    const MainNavigator = TabNavigator({
      welcome: { screen: WelcomeScreen },
      signin: { screen: SigninScreen },
      signup: { screen: SignupScreen },
      main: {
        screen: DrawerNavigator({
          home: { screen: HomeScreen },
          business: { screen: BusinessScreen },
          tech: { screen: TechScreen },
          education: { screen: EducationScreen},
          lifestyle: { screen: LifestyleScreen },

          profile: {
            screen: StackNavigator({
              profile: { screen: ProfileScreen },
              settings: { screen: SettingsScreen }
            })
          }
        }, )
      }
    },)
    return (
      <View style={styles.container}>
        <MainNavigator />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});

Here are the versions that I am using in my app:
expo 18.0.4
react 16.0.0-alpha.12
react-native  seems the latest version at the moment. In package.json shows this ling gnerated by expo  https://github.com/expo/react-native/archive/sdk-18.0.1.tar.gz"
react-navigation 1.0.0-beta.11

**Comment by dave-irvine** [comment]
I think this is related to what I just opened https://github.com/react-community/react-navigation/issues/2145

You can't wrap the `<MainNavigator>` in the `<View>`.

Try

   return (<MainNavigator />);

**Comment by Hayko1994** [comment]
I watched tutorial where it was used older versions of react-navigation and it worked inside <view>. after moving it out from view it says some syntax error about closing tags so I remove all scripts of view with its container styles.  Thanks a lot for solution. Hope removing view part will not cause lots of troubles in the feature.

**Comment by Hayko1994** [comment]
Is it possible to add specific styles for the latest 2 links of the drawer-navigation. Like drop them in the bottom with top margin, also add icons on the left side?

**Comment by spencercarli** [comment]
Going to close this since a solution was presented. @Hayko1994 you second question would best be asked on on StackOverflow. Thanks!
