### ISSUE TITLE
lazyLoad bug with TabNavigator on Android

### ISSUE THREAD

**Issue by mkonicek** [react-community/react-navigation#214]
(Using react-navigation 1.0.0-beta.1)

From my Chat example app:

```
const HomeScreenTabNavigator = TabNavigator({
  Welcome: {
    screen: WelcomeScreen,
  },
  Chats: {
    screen: ChatListScreen,
  },
}, {
  lazyLoad: true,
});
```

Here's what it looks like. Notice the broken (late) animation:

![ezgif com-1477d358f9](https://cloud.githubusercontent.com/assets/346214/22693888/03e80772-ed3d-11e6-956d-05bac2e2638d.gif)

**Comment by mkonicek** [comment]
cc @ericvicenti @grabbou

**Comment by mkonicek** [comment]
cc @ericvicenti @grabbou @satya164

**Comment by michaelduminy** [comment]
I have what might be a related issue. When I switch tabs the animation is fine but the header title is only updated 0.5-2s after the transition has been completed.

**Comment by michaelduminy** [comment]
Update:

The TabNavigator is nested in a StackNavigator (for header) which is nested in a DrawerNavigator:
`drawer > stack > tab`

When selecting a different tab the header only changes after the tab change animation has completed plus some slight delay. However, when navigating to a different tab from the drawer's custom content component (which just calls `navigation.navigate('Tab2')`) the header changes immediately, likely before the tab animation begins.

This might be explained by the nesting. My guess is that the internal `navigate` is called from the deeply nested tab navigator, which propagates up to the containing stack navigator when complete, therefore only updating the title in the header when the child navigator state has actually changed. Maybe navigating from the drawer applies the navigation change from the top, down, therefore changing the title in the header before sending the navigate to the child tab navigator.

**Comment by jpgarcia** [comment]
any update on this?

**Comment by satya164** [comment]
No, if this issue is important to you consider sending a PR to help us fix it.

**Comment by claudioviola** [comment]
Guys in docs the feature is "lazy" and not "lazyLoad"
Could I open a PR or this message is enought?

**Comment by michaelduminy** [comment]
@claudioviola the property used to be called `lazyLoad` and is now just `lazy`. No need to open a PR.

**Comment by kelset** [comment]
Pinging OP @mkonicek since this issue is quite old and related to an old version of the lib. If no answer I'll close in 7 days.

**Comment by kelset** [comment]
Hi there @mkonicek ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue (especially if it's a bug report) please open a new issue that uses the new Issue Template to provide some more details to help us solve it.
