### ISSUE TITLE
How to add icon in each tab in  customTab example ?

### ISSUE THREAD

**Issue by yash2code** [react-community/react-navigation#2142]
[CustomTabs.js](https://github.com/react-community/react-navigation/blob/master/examples/NavigationPlayground/js/CustomTabs.js)

**Comment by Amurmurmur** [comment]
@yash2code 
Im pretty sure you can to do it right here [CustomTabs.js#51](https://github.com/react-community/react-navigation/blob/master/examples/NavigationPlayground/js/CustomTabs.js#L51)

Right when it maps the routes, use <Icon /> component along with the <Text> (which is a tab label) inside the map statement.

Hope this helps 👍

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
