### ISSUE TITLE
Deep linking in Android

### ISSUE THREAD

**Issue by jlopez90** [react-community/react-navigation#2144]
Followed deep linking guide but can't open android app from URI

### Current Behavior
The app opens URI ok in iOS but nothing happens in Android devices. I can open the app and navigate ok from the shell using a command like (modified my androidmanifest ok): 

`adb shell am start -W -a android.intent.action.VIEW -d "mychat://mychat/chat/Taylor" com.simpleapp`

but when I click a button with this URI or typing in browser the app doesn't open.

### Expected Behavior
Open my android app from URI by clicking a button 

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.11
| react-native     |  0.44.0

**Comment by Amurmurmur** [comment]
Make sure you set the Intent filter right in your AndroidManifest.xml
For example you can have something like this:
```
            <intent-filter>
                <data android:scheme="mychat" android:host="mychat" />
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
            </intent-filter>
```
Put it inside your `<activity  android:name=".MainActivity" ...>` tag

**Comment by jlopez90** [comment]
Yes, it is set and inside the main activity. Thanks @Amurmurmur

**Comment by Amurmurmur** [comment]
@jlopez90 Didnt help to resolve your issue?

**Comment by jlopez90** [comment]
@Amurmurmur Nope, it doesn't work. Note that adb shell ... works

**Comment by kelset** [comment]
Hi @jlopez90 is this bug still present in newer versions of the lib (`beta.15`)?

**Comment by kelset** [comment]
Hi there @jlopez90 ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.
