### ISSUE TITLE
Wrap Navigator in View?

### ISSUE THREAD

**Issue by dave-irvine** [react-community/react-navigation#2145]
So my use case here is that I'd like to open the device's camera when the app opens, and keep it open when navigating through the app. However the problem is that the camera preview needs to be rendered at all times otherwise it looses access to the camera and I have to reinitialise on each navigation which on Android is very slow (1000ms+).

Ideally I'd like to wrap the Navigator in a View so that the camera preview can be a sibling to the Navigator, but as soon as I do the wrap the Navigator stops rendering.

Is there a workaround I could use here?

**Comment by ntkzwane** [comment]
#1659

**Comment by ntkzwane** [comment]
@dave-irvine take a look at #1659

**Comment by phumaster** [comment]
Hi @dave-irvine and every one!

I think this problem has been around for a long time. I tried a few and succeeded. But really do not understand how it can run xD.

The first, I **wrap TabNavigator in StackNavigator** -> this is solve?????

**App.js**

```
import React from 'react';
import Main from './src/Main';

import { StackNavigator } from 'react-navigation';

const StackNav = StackNavigator({
  Main: {
    screen: Main
  }
});

export default class App extends React.Component {
  render() {
    return (
      <StackNav />
    );
  }
}
```

I create `TabNavigator` in a file `TabMain.js`

**TabMain.js**

```
import React from 'react';
import { TabNavigator } from 'react-navigation';

import Home from './Home';
import AboutMe from './AboutMe';

const TabMain = TabNavigator({
    Home: {
        screen: Home
    },
    AboutMe: {
        screen: AboutMe
    }
});

export default TabMain;
```

Then in **Main.js**, I create view with `flex: 1`
**Main.js**

```
import React, { Component } from 'react';
import { View, Text } from 'react-native';
import TabMain from './TabMain';

class Main extends Component {

    static navigationOptions = {
        header: null
    };

    render() {
        return (
            <View style={{ flex: 1 }}>

                <View style={{
                    flex: 1,
                    backgroundColor: 'lightblue',
                    justifyContent: 'center',
                    alignItems: 'center'
                }}>
                    <Text>I am in Main.js</Text>
                </View>

                <View style={{ flex: 1, backgroundColor: 'lightgreen' }}>
                    <TabMain />
                </View>

            </View>
        )
    }
}

export default Main;
```

This is my gist: https://gist.github.com/phumaster/6144cf3c57e29d42631fba45fe05cb97

It worked for me! Thank for reading.

<img src="http://i.imgur.com/qFJgEOb.png"/>

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!

**Comment by Sleepful** [comment]
in v3, you need to pass the navigation props down, `<TabMain navigation={ props.navigation} />`
and you also need to declare the router, either with `static router = TabMain.router;` if you are using class components or like this for functional react components:

```
const reactComponent = (props) => { 
    /* your component logic and render here */
}
reactComponent.router = TabMain.router; //equivalent to static variable inside a class
export default reactComponent
```
