### ISSUE TITLE
Impossible to achieve the Hello Mobile Navigation tutorial

### ISSUE THREAD

**Issue by will83** [react-community/react-navigation#2146]
I don't know why, but I cant see the Stack Navigator in my iOs simulator, just by copy/paste all the code in the Get Started tutorial on this page [https://reactnavigation.org/docs/intro/](https://reactnavigation.org/docs/intro/)

I'm using Expo if it can help

**Comment by spencercarli** [comment]
Hey @will83, I think this issue likely comes down to `AppRegistry.registerComponent('SimpleApp', () => SimpleApp);` being shown in the documentation but since you're using Expo it would be `Expo.registerRootComponent(App);`

Hope that helps out!
