### ISSUE TITLE
Can't find variable: it

### ISSUE THREAD

**Issue by saeedhei** [react-community/react-navigation#2148]
**I Got This red Screen Error: `Can't find variable: it`**
First I Created New React Native Project 
after That I used Example of Your navigation codes.
I pasted `App.test.js` to my `index.android.js`
How Can I fix This red Error?

```
import React from 'react';
import 'react-native';
import renderer from 'react-test-renderer';

import App from './App';

it('renders without crashing', () => {
  const rendered = renderer.create(<App />).toJSON();
  expect(rendered).toBeTruthy();
});

AppRegistry.registerComponent('Navigation', () => Navigation);
```

**Comment by przemkow** [comment]
@saeedhei 
`App.test.js` is a file with unit tests, not with react-native app. Google something about unit testing so everything will be clear :) 

Check official documentation https://reactnavigation.org at first, there is a lot of code examples which might help you.

**Comment by saeedhei** [comment]
Thank you @przemkow.
I'm new in react native, I've already seen examples, just do not know what strategy Should I do for index.android and my router page, what is the professional way to make index.android and my router (app.js) page for Navigation with react navigation.

**Comment by vonovak** [comment]
@saeedhei `import 'react-native';` doesn't look right

**Comment by saeedhei** [comment]
@vonovak I copied from (https://github.com/react-community/react-navigation/blob/master/examples/NavigationPlayground/App.test.js)
But @przemkow Said This a unit test and I don't need to use That in my Project,

**Comment by vonovak** [comment]
hmm, interesting, I always saw it in the form of `import something from 'somewhere'`

but yeah, that is a unit test, as can be seen from the file extension. I suppose there is also a `App.js` file. If you have questions on unit tests (or tests in general) I suggest you close this issue and find some tutorials that will help you understand it.

**Comment by saeedhei** [comment]
Yeah Thank you.
