### ISSUE TITLE
Tab Navigator - Invalid Key 'tabBar' defined in navigation options...

### ISSUE THREAD

**Issue by vinefreeman** [react-community/react-navigation#2149]
I'm trying to get a tab menu to appear using react-navigation (TabNavigator) but I either get the below red screen error or If I change the name of the keys I get a blank screen

react-navigation 1.0.0-beta.11
react native 0.45.1
npm 3.10.10

Apologies if this is obvious I'm fairly new to react-native but have been trying to resolve for about 2 days...  thanks in advance for anyone's time.

Files below:
App.js
Navigation.js
PeopleList.js

Error image below references this file: PeopleList.js

```

import React, { Component } from 'react';
import { Text, View, StyleSheet, ListView } from 'react-native';
import { connect } from 'react-redux';
import PeopleItem from './PeopleItem';
import Icon from 'react-native-vector-icons/EvilIcons';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    width: 353,
    flexWrap: 'wrap',
    paddingTop: 20,
    paddingLeft: 20,
  },
});

class PeopleList extends Component {
    static navigationOptions = {
        tabBar: {
            label: 'People',
            icon: ({ tintColor }) => (
                <Icon
                    name={'user'}
                    size={50} 
                    style={{ color: tintColor }}
                />
            )
        }
    }
  componentWillMount() {
    const ds = new ListView.DataSource({
      rowHasChanged: (r1, r2) => r1 !== r2,
    });
    this.dataSource = ds.cloneWithRows(this.props.people);
  }
  render() {
    return (
      <View style={styles.container}>
        <ListView 
          enableEmptySections={true}
          dataSource={this.dataSource}
          renderRow={(rowData) => 
            <PeopleItem people={rowData} />
          }
        />
      </View>
    );
  }
}

const mapStateToProps = state => {
  return { people: state.people };
};

export default connect(mapStateToProps)(PeopleList);
```
App.js

```
import React, { Component } from 'react';
import {
  StyleSheet,
  Text,
  View
} from 'react-native';
import firebase from 'firebase';
import { Provider } from 'react-redux';
import { createStore } from 'redux';
import Login from './Login';
import Loader from './Loader';
import Navigation from './Navigation';
import reducers from '../reducers/PeopleReducer';

const store = createStore(reducers, window.__REDUX_DEVTOOLS_EXTENSION__ && window.__REDUX_DEVTOOLS_EXTENSION__());

export default class App extends Component {
  state = { loggedIn: null};

  componentWillMount(){
    firebase.initializeApp({
      ...
    });

    firebase.auth().onAuthStateChanged((user) => {
      if (user) {
        this.setState({ loggedIn: true });
      } else {
        this.setState({ loggedIn: false});
      };
    })
  }
  renderInitialView() {
    switch (this.state.loggedIn) {
      case true:
        return <Navigation />;
      case false: 
        return <Login />;
      default:
        return <Loader size="large" />;
    }
  }
  render() {
    return (
      <Provider store={store}>
        <View style={styles.container}>
         {this.renderInitialView()}
        </View>
      </Provider>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
    paddingTop: 50
  }
});
```
Navigation.js
```
import { StackNavigator, TabNavigator } from 'react-navigation';
import PeopleList from './PeopleList';
import CompanyList from './CompanyList';
import AddPerson from './AddPerson';

const Navigation = TabNavigator({
    PeopleList: { screen: PeopleList },
    AddPerson: { screen: AddPerson },
    CompanyList: { screen: CompanyList },
}, {
    tabBarOptions: {
        activeTintColor: 'white',
        inactiveTintColor: '#80cbc4',
        swipeEnabled: true,
        showLabel: false,
        style: {
            backgroundColor: '#26a69a',
        },
    },
});

export default Navigation;
```

![screen shot 2017-07-15 at 07 19 30](https://user-images.githubusercontent.com/4687836/28237034-fa5fd23a-692d-11e7-965e-53e234674496.png)

**Comment by vinefreeman** [comment]
I also get a blank screen if I change tabBar to tabBarOptions

**Comment by RoderickJDunn** [comment]
It looks like the structure of the navigation options have changed recently(ish). In you PeopleList class, try this instead:

`static navigationOptions = {
            tabBarLabel: 'People',
            tabBarIcon: ({ tintColor }) => (
                <Icon
                    name={'user'}
                    size={50} 
                    style={{ color: tintColor }}
                />
            )
}`

There is no longer a 'tabBar' object. Each tabBar option is now one level up in the data structure. 
[https://reactnavigation.org/docs/navigators/tab](url)

**Comment by mayanksahai** [comment]
Are you sure this works ?. is something wrong with my implementation.

export const Tabs= TabNavigator({
  MyOrders: {
      screen: ClientOrdersList,
      navigationOptions: {
        tabBarLabel: 'MyOrders',
        tabBarIcon: ({tintColor}) => (
            <Icon
                name={'user'}
                size={50}
                style={{color: tintColor}}
            />
        ),
      },
  },
  UpdateOrder: {
    screen: ModifyClientOrder,
    navigationOptions: {
        tabBarLabel: 'UpdateOrder',
        tabBarIcon: ({tintColor}) => (
            <Icon
                name={'list'}
                size={50}
                style={{color: tintColor}}
            />
        ),
      },
  },
}
);

<img width="366" alt="screen shot 2017-08-06 at 2 16 09 am" src="https://user-images.githubusercontent.com/558742/28997692-59a51aea-7a4d-11e7-9f32-e8de6354046f.png">


Dependencies are: 
		"react": "16.0.0-alpha.12",
		"react-native": "0.46.4",
		"react-native-elements": "^0.15.0",
		"react-native-vector-icons": "^4.3.0",
		"react-navigation": "^1.0.0-beta.11"

**Comment by david-valentin** [comment]
Hey, @vinefreeman! It looks like your issue is in your App.js render call - the view container that you have wrapped around your renderInitialView() method is what is displaying, which is why you have the 'blank screen' once the loader is done checking if you're logged in.

Try changing the stylesheet for that view to black and see what happens! That "blank screen" will be black after the loader finishes:
```
const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'black',
    paddingTop: 50
  }
});
```

A quick fix is just to remove the View container wrapper that you have around this.renderInitialView(), but you should try messing around with the react-native-debugger and put a couple of breakpoints in your renderInitialView() to get a better understanding of how these components are getting called.

Hope that helps!

**Comment by vinefreeman** [comment]
@david-valentin I'll give it a go, thanks for commenting.

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!

**Comment by fadkabli** [comment]
Hi, I am stuck with same issue,(blank screen), Does any one find some valid solution.

**Comment by rat-moonshine** [comment]
I'm having the same problem and without any possible fix so far (considering my level of expertise :P ). I tried to put the `navigationOptions` part of the `TabNavigator` declaration, but again only a blank screen after loading icon disappears:

example:
```
export const Tabs = TabNavigator({
    BooksList: {
        screen: BooksList,
        navigationOptions: {
            tabBarLabel: "Books",
            tabBarIcon: ({ tintColor }) =>
                <Icon name="list" size={35} color={tintColor} />
            }
        }
});
```

My app is broken at this point.

**Comment by rat-moonshine** [comment]
After banging head to several discussion, I've found that if I wrap the `TabNavigator` component inside a `View` - it'll break - show nothing but blank screen :/

Previously:
```
render() {
	return (
		<View><TabNavigationComponent /></View>
	);
}
```

Fixed version:
```
render() {
	return (
		<TabNavigationComponent />
	);
}
```
