### ISSUE TITLE
An extra white space header on the top when working with redux

### ISSUE THREAD

**Issue by scurlyhair** [react-community/react-navigation#2150]
I use react-navigation with redux following this article: 
[https://reactnavigation.org/docs/guides/redux](https://reactnavigation.org/docs/guides/redux)

Finally got an unexpected white space header on the top:

![image](https://user-images.githubusercontent.com/19921003/28238228-afdf79d2-6981-11e7-87c9-96d493c5490f.png)

This might be the reason of something wrong with parent navigator,  it takes a long time but really can't find out it. Is there anyone has the same issue?

Environment

| software         | version
| ---------------- | -------
| react-navigation | ^1.0.0-beta.11 
| react-native     |  ^0.45.1
| node             | v6.10.2
| npm or yarn      | 4.6.1

Blow is the sample code:

```javascript
// index.js
import React from 'react';
import thunk from 'redux-thunk';
import { createStore, applyMiddleware } from 'redux';
import { Provider } from 'react-redux';
import Root from './navigatorContainer';
import reducers from './reducers';

const store = createStore(reducers, applyMiddleware(thunk));

export default () => (
  <Provider store={store}>
    <Root />
  </Provider>
);
```

```javascript
// navigatorContainer.js
import React from 'react';
import PropTypes from 'prop-types';
import { connect } from 'react-redux';
import { addNavigationHelpers } from 'react-navigation';


export const AppNavigator = StackNavigator({
  Home: { screen: Home },
});

const AppWithNavigationState = ({ dispatch, nav }) => (
  <AppNavigator navigation={addNavigationHelpers({ dispatch, state: nav })} />
);

AppWithNavigationState.propTypes = {
  dispatch: PropTypes.func.isRequired,
  nav: PropTypes.object.isRequired,
};

const mapStateToProps = state => ({
  nav: state.nav,
});

export default connect(mapStateToProps)(AppWithNavigationState);
```

```javascript
// reducers.js
import { NavigationActions } from 'react-navigation';
import { AppNavigator } from './navigatorContainer';
import { homeReducer } from './Home';

const defaultAction = AppNavigator.router.getActionForPathAndParams('Home');
const initialNavState = AppNavigator.router.getStateForAction(defaultAction);

function nav(state = initialNavState, action) {
  let nextState;
  switch (action.type) {
    case 'HOME':
      nextState = AppNavigator.router.getStateForAction(
        NavigationActions.back(),
        state,
      );
      break;
    default:
      nextState = AppNavigator.router.getStateForAction(action, state);
      break;
  }
  return nextState || state;
}

export default combineReducers({
  nav,
  home: homeReducer,
});
```

**Comment by scurlyhair** [comment]
It's so shameful to say that it happen to be my mistake. 
Because of adding another StackNavigation in App.js.
So I'm going to close this issue.

**Comment by muntaserq** [comment]
Thank you @scurlyhair for posting this question. Ran into the same issue and was able to get some ideas on why it was happening with my app.

**Comment by aircatcher** [comment]
I am now only having one StackNavigator on my app and it still renders the same white space like yours

**Comment by tavantzo** [comment]
@aircatcher That white-space actually is the default header. Use the `headerMode: none` configuration param to disappear it.
```
export default StackNavigator({
    LoginScreen: { screen: Login.component }
}, {
    initialRouteName: 'LoginScreen',
    headerMode: 'none' <------------- This
})
````

**Comment by nolife08021** [comment]
> @aircatcher That white-space actually is the default header. Use the `headerMode: none` configuration param to disappear it.
> 
> ```
> export default StackNavigator({
>     LoginScreen: { screen: Login.component }
> }, {
>     initialRouteName: 'LoginScreen',
>     headerMode: 'none' <------------- This
> })
> ```

I used headerMode : none, the white-space header gone. But my other Screen header gone also.

**Comment by nolife08021** [comment]
headerMode: 'screen' <<<<<< solved my issues

**Comment by falk-stefan** [comment]
How to do this with v6 ?
