### ISSUE TITLE
Changing navigationOptions of screen in componentWillReceiveProps

### ISSUE THREAD

**Issue by LAITONEN** [react-community/react-navigation#2152]
Hello!

I am trying to force the header of the route in StackNavigator to become visible / show up / render only when the component (assigned as a screen to this route) has received props in componentWillReceiveProps (because at that moment the ListView, that the screen is solely comprised of, appears). How could I do that?

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
