### ISSUE TITLE
Calling a function in one of the components in the route.

### ISSUE THREAD

**Issue by KinanKazmi** [react-community/react-navigation#2153]
Suppose i have this.
```
const navtest = StackNavigator({
	Home: {screen: HomeScreen},
	Stuff: {screen: Screen2},
	Stuff2: {screen: Screen3},
});
```
And im currently viewing Stuff2/Screen3. And i have some function in my HomeScreen component, say XYZ( ). On the basis of any certain action on my current route ( Screen3 ), How do i call that function XYZ( )  in HomeScreen ?

**Comment by KinanKazmi** [comment]
I used to do something like this with the previous react-native Navigator, by putting the function as a navigator prop. `<Navigator mainFunction = {this.someFunction} ... >` and then to call it, `this.props.navigator.props.mainFunction()`.

I was thinking that maybe the `dispatch()` function can do something like this?

**Comment by LAITONEN** [comment]
Just a broad general suggestions:
- try to use mapDispatchToProps parameter of React-Redux's connect helper
- check setParams NavigationActions (https://reactnavigation.org/docs/navigators/navigation-actions)

**Comment by KinanKazmi** [comment]
@LAITONEN I want to do this without using Redux. And no, the docs didn't help.

**Comment by vonovak** [comment]
@KinanKazmi calling a function of a component from another component sounds like an antipattern. You probably wanna extract the function somewhere else.

**Comment by KinanKazmi** [comment]
This component already does this like a global state change, without Redux or something, but only for dispatching header changes. E.g. screen 1's header says "hi max" in blue color. You goto screen 3 and dispatch the change in screen 1 to say "hi mark" with red. And go back to screen 1 it would be saying "hi mark" in red. I'm just asking to call another function in that screen 1.

**Comment by vonovak** [comment]
> I'm just asking to call another function in that screen 1.

which likely is something you don't wanna do in the first place. But if you have a function and want to pass it as a prop, you can pass in in the `screenProps`: https://reactnavigation.org/docs/navigators/stack#Navigator-Props

**Comment by KinanKazmi** [comment]
Can you please write a small example? It's not clear in the docs how to
pass it. Since it shows a function on top and component with tags on bottom.

**Comment by vonovak** [comment]
it's all written there:

```
<SomeStack
  screenProps={/* this prop will get passed to the screen components as this.props.screenProps */}
/>
```

**Comment by KinanKazmi** [comment]
... thats not the thing. Have a look at my code please.
```
import {AppRegistry} from 'react-native';
import React, { Component } from 'react';
import {StackNavigator} from 'react-navigation';
import Screen2 from './Screen2';
import Screen3 from './Screen3';
import HomeScreen from './HomeScreen';

const navtest= StackNavigator({
	Home: {screen: HomeScreen},
	Stuff: {screen: Screen2},
	Stuff2: {screen: Screen3},
});
AppRegistry.registerComponent('navtest', () => navtest);
```

and in my HomeScreen file
```
export default class HomeScreen extends Component {
	constructor(props){
		super(props);
		this.state = {one: '0'};
	}

	static navigationOptions = {
		header: null,
	};

	functionToPass() {
		console.log('Function accessed');
		me.setState({one: 'X'});
	}

	render() {
		const {navigate} = this.props.navigation;
		return (
			<View>
				<TouchableOpacity onPress = {() => navigate('Stuff', {ABC: 'abc'})}>
					<Text>
						{this.state.one}
					</Text>
				</TouchableOpacity>
			</View>
		);
	}
}
```

**Comment by vonovak** [comment]
you can pass the function in the props:

```
render() {
		const {navigate} = this.props.navigation;
		return (
			<View>
				<TouchableOpacity onPress = {() => navigate('Stuff', {ABC: 'abc', functionToPass: this.functionToPass})}>
					<Text>
						{this.state.one}
					</Text>
				</TouchableOpacity>
			</View>
	
```

and change `functionToPass` to an arrow function. Even better, start using a state management library.

**Comment by KinanKazmi** [comment]
But passing like this would only make it accessable in the next screen. Not
any other. Unless i pass it through every single screen. Which would make
it ugly.

**Comment by vonovak** [comment]
I'm afraid there's no better way unless you use some state management lib.

**Comment by KinanKazmi** [comment]
How about a global object and naming it "State".

On Jul 16, 2017 5:15 PM, "Vojtech Novak" <notifications@github.com> wrote:

I'm afraid there's no better way unless you use some state management lib.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/react-community/react-navigation/issues/2153#issuecomment-315605532>,
or mute the thread

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!

**Comment by olivemz** [comment]
have exact same issue here, but I guess redux would be the easiest way to resolve this issue. redux is like a missed piece of puzzle that dedicate to solve this kind of issue.

**Comment by radoncreep** [comment]
> 
> 
> > I'm just asking to call another function in that screen 1.
> 
> which likely is something you don't wanna do in the first place. But if you have a function and want to pass it as a prop, you can pass in in the `screenProps`: https://reactnavigation.org/docs/navigators/stack#Navigator-Props

page not found, following the link you posted

**Comment by rodolforamos** [comment]
> > > I'm just asking to call another function in that screen 1.
> > 
> > 
> > which likely is something you don't wanna do in the first place. But if you have a function and want to pass it as a prop, you can pass in in the `screenProps`: https://reactnavigation.org/docs/navigators/stack#Navigator-Props
> 
> page not found, following the link you posted

https://reactnavigation.org/docs/stack-actions/
