### ISSUE TITLE
[Question] Customize / pass custom props to StackNavigatorConfig

### ISSUE THREAD

**Issue by msadura** [react-community/react-navigation#2154]
My use case: app is integrated with native iOs app. I want to have ability to open RN app with chosen screen as initial screen so my root component receives prop `initialRoute` which holds proper state. I can pass it down or save to redux store but I do not find a way to use it while initialising StackNavigator.

Root component index.js (receives `initialRoute` prop):
```
<Provider store={store}>
        <AppNavigatorContainer />
</Provider>
```

AppNavigatorContainer component (@connect'ed):
```
<AppNavigator
          navigation={addNavigationHelpers({
            dispatch: dispatch,
            state: appNavigator,
          })}
/>
```

AppNavigator:
```
const defaultConfig = {
  initialRouteName:  // ***I would like to use my initialRoute param here or pass it somehow to StackNavigator***
};

const AppNavigator = StackNavigator(routes, defaultConfig);
```

I have no idea how pass my InitialRoute prop down and use it to configure StackNavigator. They are in different files and scopes. My only idea is to export it from `index.js`, import and use in `defaultConfig` object but it seems so nasty that I don't event want to try.
Is it possible? Am I missing something?

**Comment by LAITONEN** [comment]
- Props from the top-level Navigator could be passed with this.props.screenProps.
- If you want to open the particular page, I guess you could have a look at the third line of the first block of code inside this link: https://reactnavigation.org/docs/guides/redux

Also, do you mean that you want to open the RN app from the Native app?

**Comment by DoubleAngle** [comment]
I have same question, I want to open the React Native Page from the native pages.Please kindly tell me what to do ? @LAITONEN

**Comment by msadura** [comment]
@LAITONEN thank you for showing me the way! I didn't notice that part with redux integration.
btw. as for your questions:
1) Yup my RN app is integrated with iOs native app, so native might want to open different RN  app with different views as starting point in RN.
2) Sorry I wasn't clear - by different scopes I mean js scopes - they are located in different modules so basically I cannot access root  component variables in stack navigator component directly (as I mentioned I can export them but that seems really wrong).

Your solution was good the only thing was that my "default state" was not static as in example so I created additional action and updated my navigation reducer like below. BTW. @DoubleAngle maybe this can help you:

updated navigation reducer:
```
import AppNavigator from './AppNavigator';
import type { Action } from '../common/types/Action';
import actions from '../common/actions';

const { SET_INITIAL_ROUTE } = actions;

export default function nav(state, action: Action) {
  if (action.type === SET_INITIAL_ROUTE) {
    const initialPathAndParams = AppNavigator.router.getActionForPathAndParams(action.payload.initialRoute);
    return AppNavigator.router.getStateForAction(initialPathAndParams) || state;
  }
  return AppNavigator.router.getStateForAction(action, state)|| state;
}
```

and in my root component which receives props from native app:
```
export default class App extends Component {
  componentDidMount() {
    const bound = bindActionCreators({ setInitialRoute }, store.dispatch);
    bound.setInitialRoute(this.props.initialRoute || '')
  }

  props: Props;

  render() {
    return (
      <Provider store={store}>
        <AppNavigatorContainer />
      </Provider>
    );
  }
}
```

and if you need here is action object:
```
export default function setInitialRoute(initialRoute: string): SetInitialRouteAction {
  return {
    type: SET_INITIAL_ROUTE,
    payload: {
      initialRoute
    }
  };
}
```

Once again, thank you for help @LAITONEN !
