### ISSUE TITLE
How To add `Header Photo`  to Nav Bar?

### ISSUE THREAD

**Issue by saeedhei** [react-community/react-navigation#2155]
I Designed my Stack and Drawer Nav Bar But I Don't Know, How Should I add a `Header background` and a `Header Logo` on it ?

**Comment by RobIsHere** [comment]
In my app I added a custom component for the drawer content
https://reactnavigation.org/docs/navigators/drawer#Providing-a-custom-contentComponent
Then you can recreate your very own design, add headers, lines and footers where you like. That worked pretty well for me.

**Comment by saeedhei** [comment]
@RobIsHere RobIsHere I imported `import { DrawerNavigator, DrawerItems } from 'react-navigation';` to my `MainScreen`
**My Header:**
```
const ImageHeader = props => (
    <View style={{ backgroundColor: '#fff' }}>
        <Image
            style={StyleSheet.absoluteFill}
            source={{ uri: 'https://upload.wikimedia.org/wikipedia/commons/3/36/Hopetoun_falls.jpg' }}
        />
        <Header {...props} style={{ backgroundColor: 'transparent' }} />
    </View>
);
```
**and this is my navigation option:**
```
    static navigationOptions = {
        drawerLabel: 'Welcome to Book',      //ok
        drawerIcon: ({ tintColor }) => (         //ok
            <Image
                source={require('../assets/icons/react-navigation.png')}
                style={[styles.icon]}
            />
        ),
        headerTitleStyle: { color: '#fff' },                                 //not ok
        header: (props) => <ImageHeader {...props} />,      //not ok
    };
```
But header background not work, `drawerLabel` and `drawerIcon` for main Screen is ok but `headerTitleStyle` and `header` not ok, What  I did wrong?

**Comment by RobIsHere** [comment]
There is a file https://github.com/react-community/react-navigation/blob/master/src/views/Drawer/DrawerNavigatorItems.js

Maybe you can reuse it or at least copy the rendering? Don't know if this works better than creating your own line items.

**Comment by saeedhei** [comment]
Hmm, I'm Sorry, I Don't understand very well, I mean:

- For Header: I Can put my Own Header and Styles Before `DrawerItems`: `<Text>Header Area</Text><DrawerItems {...props} />`

- For Footer: I Can put my Own Footer and Styles After `DrawerItems`: `<DrawerItems {...props} /><Text>Footer Area</Text>`

But How Can Access to DrawerItems Styles or add lines under Each DrawerItem.
Do you Have any Simple Example Please?
