### ISSUE TITLE
What is differences between `ReduxExample` and `NavigationPlayground`?

### ISSUE THREAD

**Issue by saeedhei** [react-community/react-navigation#2159]
What is differences between `ReduxExample` and `NavigationPlayground`?

- When Should I use `ReduxExample`?
- When Should I use `NavigationPlayground`?

**Comment by cooperka** [comment]
@saeedhei they are both just example apps for you to play around with the code. You can use whichever one you want, but `NavigationPlayground` demonstrates a lot of different features and `ReduxExample` only demonstrates one feature, namely a `redux` integration.

**Comment by saeedhei** [comment]
Thank you @cooperka
