### ISSUE TITLE
Android TabNavigator inside TabNavigator 

### ISSUE THREAD

**Issue by andreyslyusar** [react-community/react-navigation#2160]
### Current Behavior
Android TabBar inside another TabBar does not response to click events or swipe events. 

Click events actions are handled inside Redux, but nothing changed on UI. Swipe work "like" horizontal scroll.

The same setup works perfectly ok on iOS device. 

Parents TabNavigator
```
const navigatorConfig = {
	...TabNavigator.Presets.iOSBottomTabs,
	tabBarOptions: {
		activeTintColor: colors.fortnoxGreen,
		inactiveTintColor: colors.fn.grey,
		activeBackgroundColor: 'white',
		inactiveBackgroundColor: 'white',
	},
};
```

Child TabNavigator
```
const navigatorConfig = {
	...TabNavigator.Presets.AndroidTopTabs,
	tabBarOptions: {
		upperCaseLabel: false,
		labelStyle: {
			color: 'white',
		},
		tabStyle: {
			elevation: 4
		},
		indicatorStyle: {
			backgroundColor: 'white',
			height: 3
		},
		style: {
			backgroundColor: colors.fortnoxGreen,
		},
		activeTintColor: colors.fortnoxGreen,
		inactiveTintColor: colors.fn.grey,
		activeBackgroundColor: 'white',
		inactiveBackgroundColor: 'white',
	},
};
```
![device-2017-07-17-143609](
<img src="https://user-images.githubusercontent.com/1401690/28268135-5b8f3a2a-6afd-11e7-8508-80d6bf09486d.png" height="512">)

### Expected Behavior
Allow using tab bar inside another tab bar, as latest material design allow usage of bottom tab bar (https://material.io/guidelines/components/bottom-navigation.html#bottom-navigation-specs).

### Your Environment
| software         | version
| ---------------- | -------
| react-navigation |  master(cc22138b1927a006b6e2a29c2b3dd38da736a164)
| react-native     |  0.42.3
| node             | 7.10.0
| npm or yarn      | yarn 0.27.5

**Comment by andreyslyusar** [comment]
@satya164 You made a pull request to fix this problem, am I missing some configuration ? Thanks in advance.

**Comment by spencercarli** [comment]
I believe you have to disable swipe on one of the tabnavigators

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!

**Comment by andreyslyusar** [comment]
@spencercarli As described in 'Current Behaviour' section I am disabling swipe and animation for 1 of tab navigators. Please re-open issue, as this is not a Question.

**Comment by MehdiAlouafi** [comment]
Hi @andreyslyusar ! spencercarli is totally right ! I just had this exact same problems with nested TabNavigators and by setting the tabBarOptions.swipeEnabled: false everything worked again

**Comment by smithaitufe** [comment]
@andreyslyusar @spencercarli @MehdiAlouafi @gabriel @satya164 
I have same issue here. In my case, the outer tab navigator, I have set `swipeEnabled: false` , `animationEnabled: false` and `lazy: false`

In the first instance, the first tab contains a nested stack navigator (to get header) and the stack navigator contains tab navigator with two tabs.

The second tab contains a nested stack navigator (to get header) and the stack navigator contains tab navigator with two tabs.

here is my current code
```
const LandingScreen = ({ navigation, text }) => <ScreenGenerator text="lainding Screen" navigation={navigation} />
LandingScreen.navigationOptions = {
    tabBarLabel: 'Welcome'
}
const RoyaltyScreen = ({ navigation, text }) => <ScreenGenerator text="Royalty Screen" navigation={navigation} />
RoyaltyScreen.navigationOptions = {
    tabBarLabel: 'Royalty'
}

const AboutScreen = ({navigation, text}) => <ScreenGenerator text="About Screen" navigation={navigation} />
AboutScreen.navigationOptions = {
    tabBarLabel: 'About'
}
const AnnouncementScreen = ({ navigation, text }) => <ScreenGenerator text="Announcement Screen" navigation={navigation} />
AnnouncementScreen.navigationOptions = {
    tabBarLabel: 'Announcement'
}


const HomeTabTest = TabNavigator({
    Landing: {
        screen: LandingScreen
    },
    Royalty: {
        screen: RoyaltyScreen
    },
},
{
    tabBarOptions: {
        upperCaseLabel: false
    },
    lazy: false,
    swipeEnabled: true,
    animationEnabled: true,
    initialRouteName: 'Landing',
    // order: ['Landing', 'Royalty']
},
)

const InformationTabTest = TabNavigator({
        About: {
            screen: AboutScreen
        },
        Announcement: {
            screen: AnnouncementScreen
        }
    },{
        tabBarOptions: {
            upperCaseLabel: false
        },
        lazy: false,
        swipeEnabled: true,
        animationEnabled: true,
        initialRouteName: 'About',
        // order: ['About', 'Announcement']
    })

export const MainTab = TabNavigator({
    Home: {
        screen: StackNavigator({
            HomeStack: {
                screen: HomeTabTest
            }
        }),
        navigationOptions: {
            tabBarLabel: 'Home'
        }
    },
    Information: {
        screen: StackNavigator({
            InformationStack: {
                screen: InformationTabTest
            }
        }),
        navigationOptions: {
            tabBarLabel: 'Information'
        }
    }
},
{
    tabBarPosition: 'bottom',
    tabBarOptions: {
        labelStyle: {
            color: '#333333'
        },
        tabStyle: {
            backgroundColor: '#f5f5f5'
        }
    },
    animationEnabled: false,
    swipeEnabled: false,
    lazy: false,
})
```

The first tab with the label `Home` contains two tabs positioned at the top `Welcome` and `Royalty`.
The top tabs do not respond to press/tap neither does the swipe works.

The second tab that contains `About` and `Announcement` tabs is fine. When I swipe, it does not lag and when I tap the tabs, they work fine.

What should be done to correct this please?

**Comment by dktan** [comment]
@smithaitufe I have exactly the same setup, works fine in ios, not in android.

**Comment by sharathkoppolu** [comment]
const AppNavigation = StackNavigator({
    TabTop: {
        screen: TabNavigator({
            TabBtm: {
                screen: TabNavigator({
                    TabT1: { screen: TabT1 },
                    TabT2: { screen: TabT2 },
                    TabT3: { screen: TabT3 }
                }, {
                    tabBarPosition: 'top',
                    swipeEnabled: true,
                    tabBarOptions: {
                      activeTintColor: '#e91e63',
                    },
                  })
            },
            Tab1: { screen: Tab1 },
            Tab2: { screen: Tab2 },
            Tab3: { screen: Tab3 },

            
        }, {
            tabBarPosition: 'bottom',
            swipeEnabled: false,
            tabBarOptions: {
              activeTintColor: '#e91e63',
            },
          })
    }
})

Swipe and tab click is working fine on ios but not working properly on Android. I think this is similar to what the discussion is about. can someone let me know where am I going wrong? did it work for anyone on android?

**Comment by Manzn** [comment]
I had the same issue, but got it to work with the suggestions above.
So here is how my Tabnavigators look like (It´s basically designed like the reddit app):

This is the "outer" one, or the main Navigator if you will. It should not be able to swipe, just to click on the items, displayed at the bottom:

```
   tabBarPosition: 'bottom',
   swipeEnabled: false,
   animationEnabled: false,
   tabBarOptions:
   {
     showIcon: true,
     showLabel: false,
   }
```

And here the inner one:

```
  swipeEnabled: true,
  tabBarOptions:
  {
    scrollEnabled: true,
    showIcon: false,
    showLabel: true,
  }
```
I didn´t added design stuff...

So basically now it works like the reddit app. At the bottom only changing tabs by clicking and the tab navigator within works with clicking and swiping!
