### ISSUE TITLE
DrawerNav - StackNav nesting 

### ISSUE THREAD

**Issue by devvtms** [react-community/react-navigation#2161]
Hy, i try archive for client simple master-detail layout with nested stacknav inside drawer, so:

drawerItems:

- master // list of items, only here need drawerNav
- settingsScreen // opened with stacknav, no need drawerMenu, back support

so, i need open these screen with stackNav:

- detail // single item, with back support
- settings // with back support

i try this way:
```js
// drawerNav
const drawerNav = DrawerNavigator({
master: {
    screen: () => (
    	<StackNav
			// some screenProps for masterScreen
      		screenProps={}
      	/>),
	},
	// how i can navigate to settingsScene with screenProps/stacknav??
settings: {
	screen: () => (
    	<StackNav
			// some screenProps for masterScreen
      		screenProps={}
      	/>),
}
  
```

```js
// stackNav
// my routes

const stackNav = StackNavigator({
  master: { screen: MasterScene },
  detail: { screen: DetailScene },
  settings: { screen: SettingsScreen },
});
```
soo, how i can archive this? thank you for tips... :)

**Comment by chiformihai** [comment]
@devvtms did you find any solution?
