### ISSUE TITLE
Nesting Drawer- and Tabsnavigator and Tabs should be visible on all Scenes

### ISSUE THREAD

**Issue by markusguenther** [react-community/react-navigation#2162]
Hi, I use react-navigation and first want to thank all the contributors for the work they have done. 
I have a question but am not able to label it as a question.

I want to use the TabNavigator and the DrawerNavigator together. I know that you can nest the navigators, but then just one link of the Drawer has my Tabs for instance.

I would like to have the tab navigation always visible and the drawer should be available.

[Drawer slides over tabs](https://i.stack.imgur.com/pRUEm.png)

So the three tabs at the top should be always visible. And the drawer can slide out to link different scenes.

Actually i nest the Navigators like that.

```
const CustomTabRouter = TabRouter({
  Tab1: {
    screen: Tab1,
    path: '1',
  },
  Tab2: {
    screen: Tab2,
    path: '2',
  },
  Tab3: {
    screen: Tab3,
    path: '3',
  },
}, {
  initialRouteName: 'Tab2',
})

const TabNavigation = createNavigationContainer(
  createNavigator(CustomTabRouter)(CustomTabView)
)

const AppNavigation = DrawerNavigator({
  Home: {
    screen: TabNavigation
  },
  ScreenOne: {
    screen: ScreenOne
  },
  ScreenTwo: {
    screen: ScreenTwo
  },
}, {
  headerMode: 'none',
  initialRouteName: 'Home',
  drawerPosition: 'right',
  contentComponent: props => Slider(props),
  contentOptions: {
    inactiveTintColor: Colors.primary,
    activeTintColor: Colors.orange,
    activeBackgroundColor: Colors.white
  },
})
```

But then I obviously have the tabs only on the home then.
I also tried to nest the drawer inside the tabs, but then the drawer did not slide out.

So there is maybe a way to use both together. I just need the 3 Tabs and a button that toggles a drawer.

Would be awesome if someone has a hint for me.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.11
| react-native     |  0.46.1
| npm or yarn      | yarn

**Comment by jainniket** [comment]
the above code snippet will make the tabs always there on top and have drawer open method available on all the screens.
what is the issue you are facing?

**Comment by markusguenther** [comment]
@jainniket Yeah right... my plan is to have the Tabs on all Scenes. But don`t know how to tackle this.

My next plan would be to nest the drawer in a StackNavigator. Add the three Scenes of the tabs to the StackNavigator and then try to change the view of the StackNavigators Header to have these three buttons. But I would prefer the current solution because I am not sure if you can customise the header in this way.

**Comment by markusguenther** [comment]
Since May it is possible to add a complete custom header. So I will try to solve my issue with a custom header and a drawer.

Will keep you up2date.

```
export const MainNavigator = StackNavigator({
  Index: { 
    screen: Landing,
    navigationOptions: {
      header: props => <LandingHeader {...props} />
    } 
  }
})
```

But this looks promising 👍

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!

**Comment by illepic** [comment]
@markusguenther, checking in on what your solution to "universal tabs" was. I, too, need a set of tabs that are visible on all screens. 

I would normally just make this a little component that would exist at the bottom of a common wrapping component, but I need the tabs to **not** animate on stack navigation change. Basically, I need that rock steady `TabNavigator` behavior (does not animate on navigation change) on all screens.

**Comment by markusguenther** [comment]
If you need the tabs at the bottom it is maybe better to use the react native navigation from wix. Then you can build that an have a better performance.

I could not use the library because the customer wanted the tabs on the top. And don’t want to pay the development to make the wix approach work on top.

So I choose react navigation and ended up in building a custom navigation that I put into the header so that I have the tabs always on.

It is a bit hacks but worked for my use case.
