### ISSUE TITLE
Example for getCurrentRouteName in Docs has a bug when used with Drawer

### ISSUE THREAD

**Issue by RobIsHere** [react-community/react-navigation#2163]
### Current Behavior
If you ask for the getCurrentRouteName to highlight active menu items inside of the drawer custom component - and use the example from docs (https://reactnavigation.org/docs/guides/screen-tracking#Screen-tracking) you get back "DrawerOpen" as current route. Which make no sense at all!

### Expected Behavior
Fix the example to return correct open route shown in main screen of drawer.

```
const getCurrentRouteName = function(navigationState) {
    if (!navigationState) return null;

    const route = navigationState.routes[navigationState.index];
    if (route.routes) {

        let goDeepTo = route;
        for (let i = 0; (i < route.routes.length); i++){        
            if (route.routes[i].routeName === "DrawerClose" && route.routes[i].routes){
                goDeepTo = route.routes[i];
                break;
            }
        }

        // dive into nested navigator (it's a navigator if routes property is present)
        return getCurrentRouteName(goDeepTo);
    }
    return route.routeName;
}

```

**Comment by jainniket** [comment]
Drawer Open state as the current route is only shown when you open the drawer.
and ideally that should be the implementation.

Are you expecting the screen in the background (the previous state) to be the response of that method?

Solution:
`onNavigationStateChange={(prevState, currentState) => {}`
you can use this method in AppNavigator as a prop to get your previous state and pass the previous route as a prop.

**Comment by RobIsHere** [comment]
I considered remembering the previous state, but dropped this solution because it's an ugly design pattern going against the reason for using redux at all.

In abstract terms, I need some implementation of
(reduxNavigationState, routeNameToCheck) => isActiveRoute:bool

That implementation must work while the drawer is open, so I can highlight the active navigation item if isActiveRoute is true. Inside of my custom, redux-connected sidebar component.

But because the active route is always equal to "DrawerOpen", no matter what is shown in the main tab behind the drawer, that doesn't work. So I shared the workaround above, maybe that helps other people.

**Comment by kelset** [comment]
Pinging OP @RobIsHere since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open; if I get no answer in the next 7 days I will close it.

Moreover it looks to me like it's a duplicate of https://github.com/react-community/react-navigation/issues/51

**Comment by RobIsHere** [comment]
Closing this in favor of the broader discussion linked above.
