### ISSUE TITLE
Drawer Navigator : Remove background opacity

### ISSUE THREAD

**Issue by gourav-singhal** [react-community/react-navigation#2167]
How to remove the opacity as highlighted below ?

![1-feooxrdb-wbnwzuz6cpkeg](https://user-images.githubusercontent.com/22169281/28281816-f2dc2364-6b45-11e7-880e-7206a8f4f3a6.png)

Please help how this can be done. I am using Drawer Navigator with a contentComponent.

**Comment by gourav-singhal** [comment]
Any update for this?

**Comment by llaine** [comment]
+1

**Comment by gourav-singhal** [comment]
Thanks @spencercarli  for replying will try something else then. Will be helpful if library provides a way to change the Drawer to custom component like : 
[](https://github.com/root-two/react-native-drawer)

**Comment by kelset** [comment]
Pinging OP @gourav-singhal  since this issue has not been active for a while, and it's related to an old version of the lib (and we added a lot of Drawer customization).

Please let me know if you want this to remain open; if I get no answer in the next 7 days I will close it.

**Comment by kelset** [comment]
Hi there @gourav-singhal ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.

**Comment by Donhv** [comment]
@kelset how can I remove background opacity without different lib?

**Comment by brentvatne** [comment]
moved this to a feature request: https://react-navigation.canny.io/feature-requests/p/customize-overlay-opacity-for-drawer

**Comment by Angelk90** [comment]
@gourav-singhal :  Hi, you could post an example of code in the side menu that you see in the image with the ability to have multiple accounts graphically.

**Comment by jordanpicaso** [comment]
First, make sure you have React Navigation 3.x installed on your project and then add `overlayColor: '00FFFFF'` to your code as [DrawerNavigatorConfig](https://reactnavigation.org/docs/en/drawer-navigator.html#drawernavigatorconfig)

**Comment by huynv1509** [comment]
I add: overlayColor: "transparent" and then it work well.
https://reactnavigation.org/docs/en/drawer-navigator.html

const Navigator = createDrawerNavigator(
  {
    Main: { screen: MainScreen},
    Profile: { screen: MyProfileScreen },
  },
  {
    contentComponent: SideMenu,
    overlayColor: "transparent"
  }
);

**Comment by jbnunn** [comment]
In 2024 I'm able to accomplish it like this:

`<Drawer.Navigator
    initialRouteName="BottomTabs",
    overlayColor: 'transparent,
    screenOptions={{
        ...
    }}
>
`
