### ISSUE TITLE
Example app can't run in Expo

### ISSUE THREAD

**Issue by cooperka** [react-community/react-navigation#2168]
### Current Behavior

Setup:

1. `npm install`
2. `cd examples/NavigationPlayground/`
3. `npm install`
4. `exp start`
5. Open the provided URL in the Expo app
    - e.g. `exp://tg-zxx.cooperka.navigationplayground.exp.direct:80`

After the above steps, I see a raw HTML error in Expo (**see a [plaintext version here](https://gist.github.com/cooperka/5840a46b9dd2e34c81da0c213d84cd7a)**, or click to enlarge):

<div>
<img src="https://user-images.githubusercontent.com/2047062/28285152-78f878f2-6ae8-11e7-9472-61ce83fb73b1.png" width=200 />
</div>

Most notably:
- `Failed to complete tunnel connection`
- `successfully tunneled to your ngrok client, but the client failed to establish a connection to localhost:19001`
- `The error encountered was: dial tcp [::1]:19001: getsockopt: connection refused`
- `Warning: Not using the Expo fork of react-native` when running `exp start`, though this is common and not necessarily a problem
- Lots of `@providesModule naming collision` when running the app, though this is common and not necessarily a problem

### Expected Behavior

The example app should work.

Note that the [Contributors Guide](https://github.com/react-community/react-navigation/blob/master/docs/guides/Contributors.md#development) is severely out of date, and there are numerous other open issues related to getting the example app running (most of them outdated now after the [recent upgrade to CRNA](https://github.com/react-community/react-navigation/compare/b19beda%5E...fff7ef4)):

- https://github.com/react-community/react-navigation/issues/1754
- https://github.com/react-community/react-navigation/issues/1708
- https://github.com/react-community/react-navigation/issues/1629
- https://github.com/react-community/react-navigation/issues/1609
- https://github.com/react-community/react-navigation/issues/1457
- https://github.com/react-community/react-navigation/issues/1325

I'll happily submit a PR to clean this all up, if only I can get it working 😉

### Environment

| software         | version
| ---------------- | -------
| react-navigation |  Latest master cc22138b1927a006b6e2a29c2b3dd38da736a164
| react-native     |  v0.43.4
| node             | v6.11.1 (Boron LTS)
| npm      | v3.10.10 (Boron LTS)
| device | iOS simulator

It's even worse if I upgrade to node v8 and npm v5, so I'm sticking with LTS for now.

### Notes

I tried creating a new app using `create-react-native-app` and `exp start`, and that all works perfectly fine. It's just `NavigationPlayground` that's broken.

The [official NavigationPlayground Expo demo](https://expo.io/@react-navigation/NavigationPlayground) also still works; I just can't build it locally.

Despite these issues, all Jest tests pass successfully on both the main library and the example app.

### Proposed fix

I have a WIP branch here where I'm trying to fix it: https://github.com/cribspot/react-navigation/commits/fix-example

**Comment by cooperka** [comment]
Solved in #2170 😄

**Comment by cooperka** [comment]
Hi @spencercarli, could you please let me know why this was closed? The PR is still unmerged.

**Comment by spencercarli** [comment]
@cooperka sorry about that - had a script that was closing issues with "solved" in the last comment. I'll reopen until we get this merged 😄

**Comment by cooperka** [comment]
Cheers, thank you @spencercarli!

**Comment by spencercarli** [comment]
Resolved via #2170!

**Comment by pinchez254** [comment]
Try this  on your terminal :$~ echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
then :$~ npm i or yarn install  if you are using yarn
