### ISSUE TITLE
initialRouteParams not being passed to initial scene for StackNavigator

### ISSUE THREAD

**Issue by mauritsd** [react-community/react-navigation#217]
I'm having an issue where `this.props.navigation.state.params` remains undefined for the initial scene in a StackNavigator, even though I'm passing initial params through `initialRouteParams`. I've managed to work around the problem, but unless I've made a very stupid typo somewhere, this seems to be a bug?

Minimal example to reproduce included:
```
import React from 'react';
import {
  AppRegistry,
  Text,
} from 'react-native';
import { StackNavigator } from 'react-navigation';

class HomeScreen extends React.Component {
  static navigationOptions = {
    title: 'Welcome',
  };

  render() {
    const { state } = this.props.navigation
    return <Text>{state.params.someParam}, Navigation!</Text>;
  }
}

const ReactNavigationTestCase = StackNavigator({
  Home: { screen: HomeScreen },
}, {
  initialRouteName: 'Home',
  initialRouteParams: { someParam: 'Bonjour' }
});

AppRegistry.registerComponent('ReactNavigationTestCase', () => ReactNavigationTestCase);
```

**Comment by mauritsd** [comment]
Sorry, I missed the pull request fixing this exact issue (#150) . Closing now!

**Comment by joshuapinter** [comment]
Hey @mauritsd, I wasn't able to get this to work, even when pulling from you master branch of the library.

What I'm trying to do is pull in a prop set in `launchOptions` when the app starts and then have that accessible in my initial scene. 

I created an issue to tackle this directly as well at #634.

Any help would be really great. 

Thanks!

Josh

**Comment by silhouette5366** [comment]
can you guys please give a solution which works for react-navigation-3 in which you must set up your app container directly.
