### ISSUE TITLE
Pass navigate to my tab navigator

### ISSUE THREAD

**Issue by lionel95200x** [react-community/react-navigation#2173]
Hello everyone

### Current Behavior

I have an app built like this

StackNavigator
- Login
- Home (TabNavigator)
      - Chat
      - Profile  -> Want to go to Settings page

My Stack Navigator 👍 

const RouteCongifs = {
  Login: {
    screen: Login
  },
  Home: {
    screen: Home
  },
  Settings: {
    screen: Settings
  }
};

My TabNavigator 👍 
const Home = TabNavigator({
  Profile: {
    screen: props => <Profile/>,
  },
  Chat: {
    screen: props => <Chat />,
    }
  })

I have a button on my Profile page 👍 
<Button onPress={ () => this.props.navigation.navigate('Settings')} />

### Expected Behavior

From my Profile screen i want to go on my Settings screen

But when i clicked on button i got and error :
undefined is not an object (this.props.navigation.navigate)

Do you know how to pass the navigation function to my tabNavigator and how tu use it in render methods of my components

Thanks for your help

### My Environment

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.11
| react-native     |  ^0.44.0

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!

**Comment by preyesm** [comment]
@lionel95200x there are two things you need to check:

As far as i understand your flow is something like,
-MainStack
      -Screen A
      -Tab A
           -TabScreen A / StackNavigator
           -TabScreen B / StackNavigator
      -Screen B

If you need to move from profile to settings which is part of the MainStack navigator you need to pass the navigation props of MainStack  to the profile screen, in that case it will go to the settings page.

But i you have stack navigator loaded on one of the tab then you need to pass navigationOptions of the specific tab to the screen, only then the tab will remain else you will get full screen structure.
