### ISSUE TITLE
Check the render method of `Drawer Sidebar`

### ISSUE THREAD

**Issue by saeedhei** [react-community/react-navigation#2175]
I'm using React-navigation module, and I Created `DrawerContent` and I Got this Error:  
```Check the render method of "Drawer Sidebar"```  
How Can I Fix this Error?
![photo_ - - _ - -](https://user-images.githubusercontent.com/25050762/28318718-025c296a-6be1-11e7-9dd3-b18089c502d3.jpg)

**Default Code is ok:**  
`contentComponent: props => <ScrollView><DrawerItems {...props} /></ScrollView>`   

**My new Code is Not ok:**  
`contentComponent: DrawerContent`  
and  
`const DrawerContent = (props) => (<ScrollView><DrawerItems {...props} /></ScrollView>)`

**My Router Page Code:**
```
import React from 'react';
import {
    AppRegistry, ScrollView, Text
} from 'react-native';
import { DrawerNavigator, DrawerItems } from 'react-navigation';
import MainScreen from './MainScreen';
import News from './News';
import Photos from './Photos';
import Musics from './Musics';
import Videos from './Videos';
import Projects from './Projects';
import Biography from './Biography';

const Router = DrawerNavigator(
    {   //Navigator
        Home: { screen: MainScreen },
        New: { screen: News },
        Photo: { screen: Photos },
        Music: { screen: Musics },
        Video: { screen: Videos },
        Project: { screen: Projects },
        Biography: { screen: Biography },
    },
    {   //DrawerNavigatorConfig
        initialRouteName: 'Home',
        contentOptions: {
        },
        drawerWidth: 280,
        drawerPosition: 'left',
        contentComponent: DrawerContent
    }
);

const DrawerContent = (props) => (<ScrollView><DrawerItems {...props} /></ScrollView>)


AppRegistry.registerComponent('Router', () => Router);
export default Router;
```

**Comment by matthamil** [comment]
Change `contentComponent: DrawerContent` to `contentComponent: (<DrawerContent/>)`

**Comment by saeedhei** [comment]
@matthamil  , Still I have that error,
`but got: undefined` Changed to `but got: object`

**Comment by townmulti** [comment]
Try contentComponent: props => <DrawerContent {...props} />

**Comment by saeedhei** [comment]
@townmulti Solved ✔️
You Are Awsome, Thank you

**Comment by cyb3rsalih** [comment]
@townmulti  getting same error, Check the render method of 'CustomDrawerComponent'

**Comment by iamharky** [comment]
@cyb3rsalih import **DrawerItems** as **DrawerNavigatorItems** from **react-navigation-drawer** and change DrawerItems component in **CustomDrawerComponent** as well.
