### ISSUE TITLE
sources for assign MUST be an object - NavigationActions.navigate(..) 

### ISSUE THREAD

**Issue by tmwhdgsn** [react-community/react-navigation#2178]
I have this component below but  on pressing the button I receive this performance error. Is there a way to fix this or suppress it?

> In this environment the sources for assign MUST be an object.This error is a performance optimization and not spec compliant.

``` javascript
import React from 'react'
import {NavigationActions} from 'react-navigation'
import {View, Button} from 'react-native'
import {
  TRAINER_REG,
  STANDARD_REG
} from '../../../lib/constants'

export default class Selection extends React.Component {
  constructor (props) {
    super(props)
    this.navigateStandardReg = this.navigateStandardReg.bind(this)
    this.navigateTrainerReg = this.navigateTrainerReg.bind(this)
  }

  navigateStandardReg () {
    NavigationActions.navigate(STANDARD_REG)
  }

  navigateTrainerReg () {
    NavigationActions.navigate(TRAINER_REG)
  }

  render () {
    return (
      <View>
        <Button
          onPress={this.navigateStandardReg}
          raised
          title='STANDARD'
        />
        <Button
          onPress={this.navigateTrainerReg}
          raised
          title='TRAINER'
        />
      </View>
    )
  }
}
```
### Stack Trace
![image](https://user-images.githubusercontent.com/25855718/28325265-40e9d4e0-6bd5-11e7-8009-b7776c9ba215.png)

| software         | version
| ---------------- | -------
| react-navigation | ^1.0.0-beta.9 
| react-native     |  ^0.42.0
| node             | 6.11.0
| npm or yarn      | yarn 0.27.5

**Comment by kuldeeprawat** [comment]
+1

**Comment by muneebkhan7737** [comment]
what would  be the routeName?
can you please  give  example...

**Comment by kaueDM** [comment]
@muneebkhan7737 the property `routeName` is somewhere you wanna go, previously defined in your navigator (Stack or Tabs)

**Comment by lucasleelz** [comment]
+1
