### ISSUE TITLE
How to run on web?

### ISSUE THREAD

**Issue by MovingGifts** [react-community/react-navigation#2179]
There are so many people having issues getting it to work on web, and there is no solid walkthrough to help them (like there is for the react native part).

Many threads regarding web integration are open, some ignored, others not outlining the steps to get everything to run on web smoothly. Most point to the `BrowserAppContainer` for reference but a very simple walkthrough of proper integration is really needed.

Can someone give a simple step by step how to get react navigation to run on web?

**Comment by HelloEdit** [comment]
+1

**Comment by HelloEdit** [comment]
I think it's time for someone to write the expected walkthrough in the documentation,
Please, it would be really good and so much better than react-router 💩

**Comment by damiaozi** [comment]
I've used it，but Encounter problems。[I've used it](https://github.com/react-community/react-navigation/issues/2247)

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
