### ISSUE TITLE
How to style each `DrawerItem` in DrawerNavigator individual?

### ISSUE THREAD

**Issue by saeedhei** [react-community/react-navigation#2181]
How to add  style each `DrawerItem` in DrawerNavigator individual?
For example `border` and `background` Color to Each Drawer Item.

`contentComponent: props => <ScrollView><DrawerItems {...props} /></ScrollView>`

**Comment by Andreyco** [comment]
Implement your very own `DrawerItems` component. Reference to [original implementation here](https://github.com/react-community/react-navigation/blob/master/src/views/Drawer/DrawerNavigatorItems.js)

**Comment by saeedhei** [comment]
@adreyco You mean I should edit orginal module ?, or I should add something to my project?

**Comment by Andreyco** [comment]
Hello there.

You don't need to edit any on components provided by `react-navigation`.

The easiest way is to create custom component, let's say `CustomDrawerItems`. You can use original implementation (see link above) as reference (copy-paste-edit), or implement it however you want.

```js
function CustomDrawerItems(props) {
    return (
        <ScrollView>
            // your implementation details here
        </ScrollView>
    )
}
```

Having such component, pass it as `contentComponent` when creating drawer navigator.
```js
export default DrawerNavigator({
    // route config,
 }, {
     contentComponent: props => <CustomDrawerItems {...props} />
 })
```

**Comment by saeedhei** [comment]
I got it. Thank you @andreyco

**Comment by EmirGluhbegovic** [comment]
@Andreyco  I tried doing what you said but keep getting an error whenever I add the second parameter for DrawerNavigator: undefined is not an object ( evaluating 'route.routeName') Has something changes in recent versions?

**Comment by GuiCavi** [comment]
@EmirGluhbegovic Try this

```js
const DrawerNavigatorConfig = {
    drawerOpenRoute: 'DrawerOpen',
    drawerCloseRoute: 'DrawerClose',
    drawerToggleRoute: 'DrawerToggle',
    ...OtherOptions      
}
```
It's related to #1803.

**Comment by ankitdesai** [comment]
For those looking: original implementation of `DrawerItems` [now lives here](https://github.com/react-navigation/react-navigation-drawer/blob/master/src/views/DrawerNavigatorItems.js) (original link above no longer active)

**Comment by Unicity-Pimentel** [comment]
@kitdesai the link is also not active

**Comment by kitdesai** [comment]
@Unicity-Pimentel updated the link. they've moved to typescript and updated the file

**Comment by The-White-Fang** [comment]
If someone is looking for just small changes to the style like fontFamilly of label or something similar, you can use `screenOptions`. `drawerLabelStyle` is the property you would want to change. Not very intuitive, I wasted an hour to do it. Or maybe I am just dumb.

**Comment by charlestbell** [comment]
Could we make this less-cursed please? That would be awesome.

**Comment by murraygunn** [comment]
'drawerLabelStyle` doesn't work for DrawerItem. You need to use `labelStyle` in every DrawerItem.
