### ISSUE TITLE
How to intercept user to login and go to the scene what he want  after login succeed

### ISSUE THREAD

**Issue by JeremyZheng** [react-community/react-navigation#2182]
### Current Behavior
When app navigate to some scene, we need user to login first. So show up the login view, and after login navigate to index or home scene that we configured in the login view scene.

### Expected Behavior
We expect this: if user click A or B or C screen, go to login scene first. After login succeed then go to A or B or C scene.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.9
| react-native     |  0.44.0

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
