### ISSUE TITLE
I need to disable gestures about swipe to change screen

### ISSUE THREAD

**Issue by boyinfotronics** [react-community/react-navigation#2184]
I need to disable gestures about swipe to change screen
but i choose false for gesturesEnabled it's not working

https://gist.github.com/boyinfotronics/b48a6cd4726fc66fbc5fa37f9ce4846b

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
