### ISSUE TITLE
Missing tabbar shadow on Android

### ISSUE THREAD

**Issue by jwhscholten** [react-community/react-navigation#2186]
### Current Behavior

I'm not seeing an elevation shadow under my tabbar on Android. I've tried using elevation as style property.

```
        tabBarOptions: {
            activeTintColor: AppStyles.color.secondary,
            inactiveTintColor: Platform.OS === 'ios' ? '#BBBBBB' : '#000000',
            upperCaseLabel: false,
            showIcon: true,
            indicatorStyle: { opacity: 0 },
            labelStyle: {
                fontFamily: AppStyles.fontFamily.medium,
                fontSize: AppStyles.fontSize.small,
                marginBottom: 8
            },
            style: {
                paddingTop: 4,
                backgroundColor: '#fff',
                height: 57,

                ...Platform.select({
                    android: {
                     elevation: 3
                    }
                })
            }
        }, 
```

### Expected Behavior

I'd expect to see a drop shadow behind my tabbar based on elevation value.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.11 
| react-native     |  0.43.2
| node             | 
| npm or yarn      |

**Comment by Clowning** [comment]
Can you sent us a screenshot? 

Do you use a StackNavigator into a TabNavigator ?

**Comment by jwhscholten** [comment]
![tabbar](https://user-images.githubusercontent.com/10798293/28367842-a70b1cf8-6c92-11e7-88d9-fd652f839cba.png)

The TabNavigator is inside a StackNavigator.

**Comment by programmende** [comment]
Hi,
i have the same issue. Any ideas to fix this?
My TabNavigator is the Root navigator.

**Comment by AdrianZghibarta** [comment]
I have another problem, on iOS I am trying to remove this top shadow and I cannot do that, anyone managed to do this ?

**Comment by PhillipWinder** [comment]
+1 having the same issue

**Comment by devfausto** [comment]
Vou ficar esperando uma resposta também, no meu caso o TabBar é Top (padrão android), mas isso é o de menos.

**Comment by ryam4u** [comment]
try:
```
tabBarOptions: {
	style: {				
		elevation: 4,
		marginBottom: 5
	}
}
```

**Comment by Megamind2301** [comment]
None is working for me. I tried elevation in both style and tabStyle. None was helpful.

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!

**Comment by c316** [comment]
This is what worked for me.

```
tabBarOptions: {
    style: {				
        elevation: 3,
        paddingBottom: 2,
    }
}
```

**Comment by YasirPanjsheri** [comment]
Any update regarding this, I am using 0.48 and elevation is not working?

**Comment by vbhv19** [comment]
Elevation is mostly a bottom-shadow. Try this
    tabBarOptions: {
        style: {				
            borderTopWidth: 0,
            elevation: 8
        }
    }

**Comment by zygama** [comment]
Hi, nothing here worked for me so I created a component to simulated a shadow with react-native-linear-gradient and I putted it in top of the tabBar component (I created a custom tab bar)

Here is the code for the shadow component, it's pretty easy:
`import React from 'react';
import { StyleSheet } from 'react-native';
import LinearGradient from 'react-native-linear-gradient';

import { colors } from '../../config/colors';


const ShadowTabBar = () => (
  <LinearGradient
    start={{ x: 1, y: 0 }} // for a vertical gradient
    end={{ x: 1, y: 1 }} // for a vertical gradient
    locations={[0, 0.3, 1]} // 3 "steps" of color
    colors={['#ededed', '#e2e2e2', '#c6c6c6']} // top color, middle color, bottom color
    // colors={[colors.mainBarsColor, colors.mainNightClubsColor]}
    style={styles.gradient}
  />
);

const styles = StyleSheet.create({
  gradient: {
    height: 3
  }
});

export default ShadowTabBar;`

And here is the code for the custom tab bar:
`import React, { Component } from 'react';
import { View, StyleSheet, TouchableWithoutFeedback } from 'react-native';

import PartyNowGradient from '../components/common/PartyNowGradient';
import ShadowTabBar from '../components/tab_bar/ShadowTabBar';
import { colors } from '../config/colors';


class CustomTabBar extends Component {

  render() {

    const {
      navigation,
      renderIcon,
      activeTintColor,
      inactiveTintColor,
      jumpToIndex
    } = this.props;

    const {
      routes
    } = navigation.state;

    return (
      <View>
        <ShadowTabBar />
        <View style={styles.tabBar}>
          {routes && routes.map((route, index) => {
            const focused = index === navigation.state.index;
            const tintColor = focused ? activeTintColor : inactiveTintColor;
            return (
              <TouchableWithoutFeedback
                key={route.key}
                style={styles.tab}
                onPress={() => jumpToIndex(index)}
              >
                <View style={styles.tab}>
                  {renderIcon({
                    route,
                    index,
                    focused,
                    tintColor
                  })}
                </View>
              </TouchableWithoutFeedback>
            );
          })}
        </View>
      </View>
    );
  }

}

const styles = StyleSheet.create({
  tabBar: {
    height: 45,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: "white",
    borderRadius: 3
  },
  tab: {
    alignSelf: 'stretch',
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  }
});

export default CustomTabBar;`

**Comment by sooxiaotong** [comment]
@zygama Can i see the preview of that code?

**Comment by Zvukamar** [comment]
tabBarOptions: {
	style: {				
		elevation: 0
	}
}
worked for me

**Comment by omerman** [comment]
If it is still relevant for you:

```
    tabBarOptions: {
      showLabel: false,
      style: {
        backgroundColor: colors.light[3],
        elevation: 5,
        borderTopWidth: 2,
        top: 1, // This is the important part.. without it there will be no shadow effect on the top edge of the tab bar.
      },
    },
```

**Comment by Diyorbek** [comment]
I had the same issue and turns out that it is because of `style` prop of screens of tabs. I had used `flex: 1` in my components, so they covered the shadow of the tab bar. I removed `flex: 1` and shadow appeared.

**Comment by kesha-antonov** [comment]
Is it possible to add offset for shadow on android?

**Comment by leahaense** [comment]
@omerman do you have a working example? `top: 1` does not have any effect for me, I just get a shadow at the bottom of the tabbar, which is obviously not visible for a bottom tab bar

**Comment by ChiragMDave** [comment]
top: 10 will move your tab buttons down and you will see the shadow over some other ui component beneath which actually hides it when top is 0.

**Comment by mbernardes19** [comment]
Not working on `react-navigation@4.3.9` `react-navigation-tabs@1.2.0`

**Comment by redvelvet-fan** [comment]
tabBarOptions={{
                style: {
                    borderTopColor: "#DCDCDC", borderTopWidth: 3,
                    shadowColor: '#DCDCDC',
                    shadowOffset: { width: 0, height: -1 },
                    shadowOpacity: 0.8,
                    shadowRadius: 1,
                }
            }}

my work

**Comment by rayjackson13** [comment]
Still not resolved to this day: `@react-navigation/native: ^6.0.2` `@react-navigation/bottom-tabs: ^6.0.5`

This is an example of my code:
```
const BottomTab = createBottomTabNavigator<RootTabParamList>();

function BottomTabNavigator() {
  const { colors } = useTheme();
  return (
    <BottomTab.Navigator
      initialRouteName=...
      screenOptions={{
        header: (props: BottomTabHeaderProps) => <Header {...props} />,
        tabBarStyle: {
          backgroundColor: '#f6f6f6',
          elevation: 9,
          borderTopWidth: 0,
        },
      }}
    >
      ...
    </BottomTab.Navigator>
  );
}
```

The shadow (elevation) simply doesn't appear on android. I tried different solutions from this thread, and also tried doing a custom TabBar component with its own shadow properties - still no luck.
This is an issue that has been open 4 years ago and still no resolution, unfortunately.

**Comment by praveens96** [comment]
`tabBarStyle: { shadowColor: '#000', shadowOffset: { width: 0, height: 0.4 }, shadowOpacity: 0.5 }`
this is working for me in v6

**Comment by saperlipopette45** [comment]
> 

This is still not working for me in Android...

**Comment by saperlipopette45** [comment]
> `tabBarStyle: { shadowColor: '#000', shadowOffset: { width: 0, height: 0.4 }, shadowOpacity: 0.5 }` this is working for me in v6

This one is not working for me on RN 0.69.4 + react navigation 6+

**Comment by JessyAngel07** [comment]
> tabBarOptions: {
>     style: {				
>         paddingBottom: 2,
>     }
> }

there is no option like this

**Comment by git-user-1337** [comment]
In case this might help someone here: 
I found a simple solution for a consistent tabbar shadow on Android & iOS. I am using the [react-native-fast-shadow](https://github.com/alan-eu/react-native-fast-shadow) package in combination with the [tabbarbackground](https://reactnavigation.org/docs/bottom-tab-navigator#tabbarbackground) property:
```
    <Tab.Navigator
      screenOptions={{
        tabBarStyle: {
          borderTopWidth: 0,
          elevation: 0,
          borderTopColor: 'white'
        },
        tabBarBackground: () => (
          <ShadowedView
            style={{
              backgroundColor: '#ffffff',
              height: '100%',
              ...shadowStyle({
                opacity: 0.065,
                radius: 6,
                offset: [0, 0]
              })
            }}
          />
        )
      }}
    >
...
```

Result:
![screenshot](https://github.com/react-navigation/react-navigation/assets/86466408/be5337e7-536a-4266-b87f-9a87efaa4839)
