### ISSUE TITLE
getStateForAction

### ISSUE THREAD

**Issue by JasonLeeSen** [react-community/react-navigation#2187]
![b575fcc4-b9dc-4e15-b60c-b47f71cc1be1](https://user-images.githubusercontent.com/15101532/28371864-b0cea992-6cd0-11e7-915e-d594255851d4.png)
As the picture shows, could you explain why the getStateForAction return like this when in this situation

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  
| react-native     |  
| node             | 
| npm or yarn      |

**Comment by matthamil** [comment]
It looks like you're referencing the compiled & published version of react-navigation. Do you have a question about the original source?

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
