### ISSUE TITLE
Reducing the spacing between the tabBarIcon and tabBarLabel?

### ISSUE THREAD

**Issue by trippyhat** [react-community/react-navigation#2189]
I am working through the tutorial in the docs for TabNavigation, and I want to change the amount of spacing between the icon and the label:

```
class MyHomeScreen extends React.Component {
  static navigationOptions = {
    tabBarLabel: 'Home',
    // Note: By default the icon is only shown on iOS. Search the showIcon option below.
    tabBarIcon: ({ tintColor }) => (
      <Image
        source={require('./home.png')}
        style={[styles.icon]}
      />
    ),
  };

const TutorialProject = TabNavigator({
  Home: {
    screen: MyHomeScreen,
  },
  Notifications: {
    screen: MyNotificationsScreen,
  },
}, {
  tabBarOptions: {
    activeTintColor: '#e91e63',
    showIcon: true,
    iconStyle: { width: 30, height: 30, margin: 0, padding: 0},
    tabStyle: { height: 55 }
  },
});
```

I have set the `iconStyle` to be `margin: 0, padding: 0`, but this did not affect the spacing between the two elements.

<img width="122" alt="screen shot 2017-07-19 at 11 51 08 am" src="https://user-images.githubusercontent.com/19194431/28376742-e737e73a-6c78-11e7-98b2-d8d805a18bde.png">

In that image, the icon is cut off, so I'm trying to shift it down a bit by reducing the spacing in between the label and icon. I like the tab height at 55, which is why I'm not increasing it.

**Comment by RyanWan** [comment]
+1

**Comment by spencercarli** [comment]
The goal of this library is to provide tabbars and navigators that closely mimic the default ones. If you want to customize them you'll probably want to create your own (which is very simple via the tabBarComponent option, check docs for more info).

**Comment by rishabhbhatia** [comment]
@trippyhat @RyanWan if you still want the solution, adding `style: {
      padding: 5
    },` inside tabBarOptions works fine for me.

**Comment by zaghadon** [comment]
What I did was apply a paddingHorizontal style to the tab bar screen options.

``` js
        <Tab.Navigator
            initialRouteName='Home'
            screenOptions={() => ({
                tabBarShowLabel: false,
                headerShown: false,
                tabBarHideOnKeyboard: true,
                tabBarStyle: [
                    {
                        height: 70,
                        paddingBottom: 10,
                        paddingHorizontal: 60, //this brings them further together and produces the desired prensentation.
                        alignContent: 'center',
                        alignItems: 'center',
                        backgroundColor: '#F9F9F9',
                    }
                ]
            })}> 
```

**Comment by lclarkg18** [comment]
> What I did was apply a paddingHorizontal style to the tab bar screen options.


This approach is not great because it will change depending on the device's width. For some reason, padding/margin is not working for me on a custom tabBarLabel but I was able to achieve the same but hardcoding the width in the tabBarItemStyles:
```
          tabBarItemStyle: {
            width: 104,
          },
```

**Comment by Gowtham8940** [comment]
thank you which is work's for me
