### ISSUE TITLE
How to handle iterative/different screenProps

### ISSUE THREAD

**Issue by JulianKingman** [react-community/react-navigation#219]
I'm wondering if I'm missing something, it seems like I should be possible to pass different props to the children of a navigator, but screenProps makes that rather confusing... For instance, if I want to have a dynamic set of tabs, with dynamic content that's passed through props, I currently have no idea how I'd do that. Is there a reason this would be bad, or is this already possible?

**Comment by satya164** [comment]
You shouldn't do that. It makes it impossible to optimize anything. Connect your individual screens instead of the root screen. If you really want to pass different props, just pass all of them in the object. All screens receive all props and they can choose what to use.
