### ISSUE TITLE
Using react-navigation without react-native

### ISSUE THREAD

**Issue by all2187** [react-community/react-navigation#2191]
The documentation for this package states that "React Navigation can also be used across React and React Native projects allowing for a higher degree of shared code", implying that we can use it in react-only projects (without react native). However when trying to install it, it asks for react-native, and throughout the discussions in the different issues it seems that it is expected to rely on react-native.

I was just wondering if there is actually a way to use this package in react but without react-native, or if the documentation is simply slightly misleading. I have a Meteor project in which we use cordova for mobile (rather than react-native) but react for most of the UI. I would have loved to use this package with the rest of our react (in a way similar to how I can use https://github.com/aputinski/react-navigation-controller).

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
