### ISSUE TITLE
Drawer Duplicating Views

### ISSUE THREAD

**Issue by LukBowen** [react-community/react-navigation#2194]
### Current Behavior
If you open the Drawer and click on the correct navigation item it puts a duplicate view on the screen. On Android you can use the back button to pop them off. On iOS you can see the views being placed on top of the already created one.

### Expected Behavior
I would expect that if the current view is the selected view that it would either just dismiss or be unclickable. 

### Your Environment
<Drawer>
   <Stack>
   <Stack>
   <Stack>
<Drawer>

| software         | version
"react": "16.0.0-alpha.12",
"react-native": "0.46.2",
"react-native-elements": "^0.14.0",
"react-native-flurry-analytics": "^2.1.0",
"react-native-localization": "^0.1.31",
"react-native-mapbox-gl": "^5.1.0",
"react-native-vector-icons": "^4.2.0",
"react-navigation": "^1.0.0-beta.11",

**Comment by nico1510** [comment]
This was fixed in https://github.com/react-community/react-navigation/commit/608217abbc0a44976b64b77950760e1c4106288f#diff-1ef5b8f9d10c4acbaf92697f3abd0041 and will land in the beta.12 release. Please consider to close this issue if it was resolved by this answer.

**Comment by tomdye** [comment]
When is `beta12` going to be release?
