### ISSUE TITLE
Nested Navigators - Blank Screen while using Stack Navigator

### ISSUE THREAD

**Issue by leanminmachine** [react-community/react-navigation#2195]
This is my current navigator hierarchy now, which works as intended. 

- TabNavigator: 
Welcome: WelcomeScreen
Auth: StackNavigator
Main: TabNavigator
-- StackNavigators within each tab

I would like to modify it to StackNavigator as the first / primary navigator so that I am able to reset the navigation all the way to the welcome screen if a user signs out. I can't do that using TabNavigator as the first navigator (if anyone knows how, please let me know!) 

However my problem is that when I edit TabNavigator (the first navigator) into a StackNavigator, I get an empty white screen. I tried creating a 'wrapper' navigator called Root and using that as a StackNavigator, placing the first TabNavigator inside but I still get an empty white screen. 

```
export const FirstNavigator = StackNavigator({
      Welcome: {screen: WelcomeScreen},
      Auth: {screen: LoginFlow},
      Main: {screen: MainTabs}
    }
  );



export const Root = StackNavigator({
  FirstNavigator: {screen: FirstNavigator}
});

```

![simulator screen shot 20 jul 2017 10 13 25 am](https://user-images.githubusercontent.com/16240321/28397477-6775b9d4-6d34-11e7-9ce8-0056fc05f22f.png)

If I remove Welcome screen from the Stack Navigator, I get a glitched view of the Auth / loginflow

![simulator screen shot 20 jul 2017 10 16 49 am](https://user-images.githubusercontent.com/16240321/28397525-b841d190-6d34-11e7-891c-5137995100a0.png)

Seems like the styled view on my main.js is showing the white background colour. When i swapped the colour to black, the screen loads up as black.

```
  render() {
   if (this.props.loggedIn) {

    return (
      <Provider store = {store}>
      <View style={styles.container}>
        <Root /> //suppose to load navigator when logged in but i'll edit it when this manages to work?
      </View>
      </Provider>
    );

  } else {
    return (
      <Provider store = {store}>
      <View style={styles.container}>
        <Root /> //load up the welcome screen 
      </View>
      </Provider>
    );
  }
}

}


const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});

const mapStateToProps = state => {
    return {
      loggedIn: state.auth.loggedIn
      };
};

export default connect (mapStateToProps, {
  loginUser
})(App);

Expo.registerRootComponent(App);
```

| software         | version
| ---------------- | -------
| react-navigation |  "1.0.0-beta.7"
| react-native     |  "https://github.com/expo/react-native/archive/sdk-18.0.1.tar.gz"
| node             |  v7.2.1
| npm or yarn      | 4.6.1

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
