### ISSUE TITLE
REACT-NAVIGATION doesn't delete old component and creates new!? Duplicate component creation

### ISSUE THREAD

**Issue by listatt** [react-community/react-navigation#2196]
"react-native": "0.44.0",
"react-navigation": "^1.0.0-beta.11",
"react-redux": "^5.0.3".

I have a screen "A", which has a body component "A.1" with touchableopacity component.

Component "A.1" connected to redux store and gets mapstatetoprops.
Touchable component in "A.1" has onPress listener, which dispatch some action.

I use StackNavigator and when I navigate to screen "A" it looks like **each time** when I navigate to this screen react-navigation doesn't delete old component(s) but creates new. Cause all components (old and new) responding on each action. When I reset stack on navigate it works fine

I've created some identifier to touchable component and on each navigate to component "A" in shouldComponenteCreate of component "A.1" it duplicates logs.

Also on navigate to screen component "A" it renders it on each time.

P.S. Is it bug or I've mistaken?

```
class NearestDay extends Component {
  shouldComponentUpdate(nextProps, nextState) {
     console.log('11'); **// ON EACH NAVIGATE IT DUPLICATED MORE AND MORE**
     console.log(this._item.idEnt) // EACH TIME ON ACTION IT LOGS OLD AND NEW IDENTIFIERERS

    if (this.props !== nextProps) {
      return true;
    }

    return false;
  }

  render() {
    const { dispatch, dayOfWeek, numberOfDay, date, active } = this.props;
    
    return (
      <TouchableOpacity
        onPress={() => {
          dispatch(selectedDate(date));
        }}
        ref={(item) => {
          this._item = item;

          if (this._item === null) {
            return false;
          }

          if (this._item.idEnt === undefined || this._item.idEnt === null) {
            this._item.idEnt = Math.floor(Math.random() * (100000 - 1)) + 1;
          }
        }}
        style={{backgroundColor: 'transparent'}}
        >
        <View style={!active ? styles.nearestDay: styles.nearestDayActive}>
        </View>
      </TouchableOpacity>
    )
  }
}

export default connect (
  (state, ownProps) => ({
    active: ownProps.date.isSame(state.selectedDate)
  })
)(NearestDay);
```

**Comment by nico1510** [comment]
related to https://github.com/react-community/react-navigation/issues/706

**Comment by spencercarli** [comment]
Let's keep this all focused on #706. Thanks for finding that @nico1510
