### ISSUE TITLE
StackNavigator: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.

### ISSUE THREAD

**Issue by wuyunqiang** [react-community/react-navigation#2197]
### Current Behavior
android && ios wrong
![typeinvalid](https://user-images.githubusercontent.com/13480948/28412313-626e166a-6d76-11e7-8689-c45af251e25b.png)

### Expected Behavior
can work.

### Your Environment
"react": "16.0.0-alpha.12",
"react-native": "0.46.4",
"react-navigation": "^1.0.0-beta.11"
 node:8.0.0
 npm:5.0.1

code:
const AppNavigator = StackNavigator(
    {
        home: {screen: myHome,},
        project: {screen: myProject,},
        credit: {screen: myCredit,},
        profile: {screen: myProfile,},
    },
    {
        headerMode: 'screen',
        navigationOptions: {
            headerStyle: {
                backgroundColor: 'red'
            },
            headerTitleStyle: {
                color: '#fff',
                fontSize: 20,
                alignSelf: 'center'
            },
            headerTintColor: '#fff',
            gesturesEnabled: true,
        }
    }
);
export default AppNavigator;

myhome/myProject/myCredit/myProfile  code:

`export default class Home extends Component {

    render(){
        return (<View>
           <Text>hahhahah</Text>
        </View>)
    }
}`

**Comment by wuyunqiang** [comment]
I though.it a quesstion of 0.46.4.
when I install 0.44.0 and yarn install (not npm install)
and is ok.

**Comment by spencercarli** [comment]
One of your screens likely isn't imported/exported correctly. Make sure you can render each screen independently of the navigator.
