### ISSUE TITLE
How to update navigationOptions with values from mapStateToProps

### ISSUE THREAD

**Issue by veedeo** [react-community/react-navigation#2203]
My `mapStateToProps` looks like this, note that Im using `Redux` state here to get the object
```
const mapStateToProps = (state, {id, navigation}) => {
  id = id || navigation.state.params.id;
  const activity = state.userActivities[id] || state.nearbyActivities[id];
  
  return {
    id,
    activity
}}
```
Now I want to draw an Image on the header with parameter from activity object.  How would I do this? Since `navigationOptions` is static, the only way I can think of is to access global state, but it looks ugly.

**Comment by veedeo** [comment]
Similar issue if I have a Submit button in the header and I want this button to dispatch a callback of Component?
Is there any API to control the header within Component and not defining it statically?

**Comment by jasonnathan** [comment]
I used a custom `connect()`ed `<Header />` component.

**Comment by acomito** [comment]
what is the reason for not having props in navigationOptions? Because it may render before the props are ready/available/change? It would be nice to be able to get at Apollo or Redux (or any HOC) without having to have the data on the previous screen (where you can pass it in as a param).

**Comment by veedeo** [comment]
I found a workaround for this
```
static navigationOptions = ({ navigation }) => {
  return navigation.state.params.headerConfig;
};
```
and then in `componentWillMount`
```
componentWillMount()
{
  const headerConfig = this._renderHeader(this.props);
  this.props.navigation.setParams({headerConfig});
}
```
The only problem is that header update is not immediate and takes few moments, after the whole screen was rendered

**Comment by anderson9149** [comment]
I have the same issue.  I'm able to update the navigation options by setting params in componentWillMount().  However, they don't take effect right away.  It renders the wrong thing for about half a second.  This is odd, because I am using the same method for a tabs nav, inside a drawer and it works fine.  But, when I nest a stack inside that tab I get this issue on that Stack Navigator.  Any one figure this out?

**Comment by Johncy1997** [comment]
hi @veedeo I have a problem in acessing the props into tabBarLabel.
This is my component:
*****************************************************
class ColumnOne extends Component{
 constructor(props){
      console.log("started 1st tab"+props);
        super(props);
         this.state={
            diwali:[],
       }}
 componentWillMount(){
//this.props.data.offerstitle=[{ColumnOne:'Diwali',...}]
      this.props.data.offerstitle.map((item)=>{
        const tabLabel=item.ColumnOne;
       this.props.navigation.setParams({tabLabel});
        debugger
       })
    }
      static navigationOptions=({navigation})=>{
       tabBarLabel= navigation.state.params.tabLabel;//Here i want to assign the value from this.props.data.offerstitle[0].ColumnOne
      drawerIcon=({tintColor }) => (
        <Image
        source = {require('../assets/contactusicon.png')}
        style={{height:50,width:'100%',resizeMode:'contain'} }/> 
      )
    } 
   render(){
      ............
       }
}
const mapStateToProps = (state) =>{
  return{
      data : state.trending,
      
  }
}
export default connect(mapStateToProps)(ColumnOne);
