### ISSUE TITLE
Wrong version reported on Yarn Upgrade 1.0.0-beta.11.

### ISSUE THREAD

**Issue by jasonnathan** [react-community/react-navigation#2204]
Yarn reports wrong version when running `yarn upgrade-interactive`

### Current Behavior
N.A

### Expected Behavior
Github shows package version `1.0.0-beta.12` but yarn reporting incorrect version
on upgrade .  

````
1.0.0-beta.11. //note the trailing dot
````

Possible bug in published NPM version.

### Your Environment
<img width="842" alt="screen shot 2017-07-21 at 8 35 11 pm" src="https://user-images.githubusercontent.com/780157/28463689-4e4391cc-6e54-11e7-97a8-e90a011f930d.png">

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.11
| react-native     |  0.46.4
| node             |  v7.10.0
| npm or yarn      | yarn 0.27.5

**Comment by alphasp** [comment]
@skevy 1.0.0-beta.12 is not yet published on npm

**Comment by spencercarli** [comment]
Is this still an issue? When I run `yarn info "react-navigation"` I'm seeing

- latest: '1.0.0-beta.11'
- next: '1.0.0-beta.12'

I'm not sure if this is intentional or not.

**Comment by skevy** [comment]
I honestly just didn't put it as `latest` because I didn't yet have a chance to do release notes.

@spencercarli or @matthamil or @davepack is that something you guys could help with?

**Comment by vonovak** [comment]
closing since the issue concerns an old version of the package
