### ISSUE TITLE
Provide Getting Started for create-react-native-app

### ISSUE THREAD

**Issue by probeadd** [react-community/react-navigation#2205]
### Current Behavior

React navigation has a nice docs. The docs are clear enough, but I have a problem when I follow the documentation (from intro) because react native recommend us to create an initial project with create-react-native-app. There are some different starter of using create-react-native-app and react-native init.

### Expected Behavior

I hope the documentation would be great if it follows what react native documentation do. It make people more easy to start working on it.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  ^1.0.0-beta.11
| react-native     |  ^0.45.1
| node             |  v7.10.1
| npm or yarn      | npm 4.2.0

**Comment by spencercarli** [comment]
Though not a guide, if you're wanting to use the [official intro](https://reactnavigation.org/docs/intro/) with CRNA all you'll need to do is swap out `react-native init SimpleApp` with `create-react-native-app SimpleApp` and you should be on your way! All the following instructions will  work the same 😄

**Comment by probeadd** [comment]
Yes, @spencercarli. But I've found some question that refering to this problem. I am sorry, but it will be great if we can provide for newbie like me! :smile:

**Comment by kelset** [comment]
Closing since now the docs have the [CRNA approach too](https://reactnavigation.org/docs/intro/basic-app).
