### ISSUE TITLE
Simple ScrollView like Page Transition animation?

### ISSUE THREAD

**Issue by Jonovono** [react-community/react-navigation#2209]
I want to do something like:

![Transition](https://cdn-images-1.medium.com/max/800/1*EXjEiLO6SGc8TH-d05yAhg.gif)

Is this possible? The defalut seems to add like a page overlay?

Thanks.

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
