### ISSUE TITLE
StackNavigator push transition pausing 80% through & then finishing

### ISSUE THREAD

**Issue by thomasbaldwin** [react-community/react-navigation#2210]
### Current Behavior
I'm doing a redux call in my `componentDidMount` method for one of my components that is being pushed onto the screen via the `StackNavigator`. The transition stops about 80% through and then finishes. However, when I remove the redux call from the `componentDidMount` method, the transition is completely smooth.

Here is some sample code:

    function mapStateToProps(state) {
      return {
        currentPosition: state.fetchedUserLocation,
        locationData: state.fetchedLocation,
      }
    };

    function mapDispatchToProps(dispatch) {
      return bindActionCreators(ActionCreators, dispatch);
    };

    class Place extends Component {
      constructor(props) {
        super(props);

        const commentActionDetails = {
          options: ['Cancel'],
          cancelIndex: CANCEL_COMMENT_INDEX,
        }
        
        this.state = {
          commentActionDetails,
          currentPosition: props.navigation.state.currentPosition,
          locationData: props.locationData,
        };    
      }
      
      componentDidMount() {
        const { locationId } = this.props.navigation.state.params;
        this.props.fetchLocation(locationId);
      }

Is there somewhere else I should be placing my redux calls than in the componentDidMount? Or am I doing my redux operation wrong? I thought they should be asynchronous.

Thanks for the help!

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.11
| react-native     |  0.44.0
| node             | 8.1.2
| npm or yarn      | 5.2.0

**Comment by thomasbaldwin** [comment]
If I modify the `componentDidMount` function to look like this, I have smooth transitions too:

    componentDidMount() {
      const { locationId } = this.props.navigation.state.params;
      
      setTimeout(() => {
        this.props.fetchLocation(locationId);
      }, 1000);
    }

**Comment by thomasbaldwin** [comment]
So this issue is actually with a component i'm rendering which is a MapView from `react-native-maps`. Is there anyway to tell when the push transition for the `StackNavigator` is completed so I know when to start rendering & loading the map?

**Comment by spencercarli** [comment]
Hey @thomasbaldwin! [InteractionManager](https://facebook.github.io/react-native/docs/interactionmanager.html) might be what you're after here. Basically replace the `setTimeout` with 

```javascript
componentDidMount() {
  InteractionManager.runAfterInteractions(() => {
   const { locationId } = this.props.navigation.state.params;
   this.props.fetchLocation(locationId);
});
}
```

**Comment by spencercarli** [comment]
Closing for lack of followup.
