### ISSUE TITLE
How do i setParams to 2 tabs at once?

### ISSUE THREAD

**Issue by Tom29** [react-community/react-navigation#2211]
### Current Behavior
It can dispatch `setParams` action for one tab only

### Expected Behavior
I want to dispatch / `setParams` to all tabs

```
const setParamsAction1 = NavigationActions.setParams({ params: { foo: 'bar' } }, key: 'a' });
const setParamsAction2 = NavigationActions.setParams({ params: { foo: 'bar' } }, key: 'b' });
this.props.navigation.dispatch(setParamsAction1);
this.props.navigation.dispatch(setParamsAction2);
```

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
