### ISSUE TITLE
Space between Navigation Bar and FlatList

### ISSUE THREAD

**Issue by rheasrivats** [react-community/react-navigation#2212]
### Current Behavior

I am implementing a FlatList with StackNavigator, and I am getting a space between the Navigation Bar and the View.
![image](https://user-images.githubusercontent.com/23413969/28476925-bf9cbe00-6e06-11e7-9053-0d635175ff7b.png)
![image](https://user-images.githubusercontent.com/23413969/28476936-cf9d5422-6e06-11e7-83da-0ea27286a5b8.png)
![image](https://user-images.githubusercontent.com/23413969/28476954-e196d3ce-6e06-11e7-955b-da91464f1673.png)

### Expected Behavior

I can't seem to get rid of the space, and when I did it with ListView previously it worked correctly.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  
| react-native     |  
| node             | 
| npm or yarn      |

**Comment by Andreyco** [comment]
Blind shot...
Speaking look is as expected with `ListView`, I would blame `FlatList` instead of `react-navigation`. Have you tried `<FlatList style={{ margin: 0 }} />?

**Comment by rheasrivats** [comment]
@Andreyco yeah I tried that :/

**Comment by apkoponen** [comment]
Removing the `<List>` -component surrounding the FlatList fixed this issue for me.

**Comment by spencercarli** [comment]
Yeah if using the `<List />` from react-native-elements will cause this. Closing as that should be a solution.

**Comment by avanzarit-in** [comment]
You could also set containerStyle={{ marginTop:0 }} on the List component. By default the marginTop is set to 20
