### ISSUE TITLE
StackNavigator bug: doesn't draw top page/card.

### ISSUE THREAD

**Issue by jslz** [react-community/react-navigation#2213]
Thanks for the cool library.

This issue here might be related to the history of all the stuff around transparency bugs e.g. https://github.com/react-community/react-navigation/issues/1645

### Current Behavior
1. This happens somewhat non-deterministically so it is hard to come up with a minimally reproducing example.
1. Sometimes when going to a new route, the new route has the render() method called however it doesn't appear visibly to the human user.
1. Note: The route is on the stack (visible in the debugger or console.logging the stack), and the component has been rendered()'d. So there's not an obvious failure to update the stack.
1. If the stack is only 1 item due to using reset(), sometimes then we get an utterly blank result because there is nothing "underneath" on the stack to show through.
1. We've seen it on both Android and iOS.

### Expected Behavior
1. Always correctly visibly render/show/see the top card/page on the stack. :-)

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.11
| react-native     |  0.45.1
| react-native-cli     |  2.0.1
| node             | 6.11.1
| npm      | 3.10.10
| yarn      | 0.27.5

**Comment by spencercarli** [comment]
Can you provide a demo application for this issue?

**Comment by jslz** [comment]
Thanks for your attention. I do not have a minimal example. :-( It has been spurious and hard to repro. I don't expect anybody to have a solution out of the blue :-) and it might be due to different components causing the issue, of course. Mostly wanted to report what I've seen on the off chance anybody else is like, "yeah me too".
