### ISSUE TITLE
`navigate()` fails silently when Scene name does not exist.

### ISSUE THREAD

**Issue by joshuapinter** [react-community/react-navigation#2217]
### Current Behavior
If you try to navigate to a scene that doesn't exist, it fails silently. e.g. `this.props.navigation.navigate("DoesNotExist");`

### Expected Behavior
An error would indicate that "DoesNotExist" scene does not exist.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.11
| react-native     |  0.46.4
| node             | 6.9.1
| npm or yarn      | 4.2.0

**Comment by Andreyco** [comment]
Related to #1053. Also, there is PR #2140 pending

**Comment by spencercarli** [comment]
Closing in favor of of #1053.
