### ISSUE TITLE
Header : Flickering back button

### ISSUE THREAD

**Issue by si-harps** [react-community/react-navigation#222]
I have an app using the following structure...

```
+-- Stacknavigator             [ headerMode: 'screen' ]
|   +-- Screen                 [ navigationOptions: header: visible: false ]
|   +-- TabNavigator           [ navigationOptions: header: visible: false ]
|       +-- StackNavigator     [ headerMode: 'float' ]
|           +-- Screen
|           +-- Screen
|       +-- StackNavigator     [ headerMode: 'float' ]
|           +-- Screen
|           +-- Screen
|   +-- Screen
```
...which seems to allow me to have a top level set of components with no / custom headers and the main tabbed navigation for the app using react-navigation headers as standard.

The issue i am seeing is that when i press the header back button on any of the screen components nested under the TabNavigator -> Stacknavigators, there seems to be a flicker as the transition happens. Maybe once or twice the first time, then increased the more times i try to action. Not sure what to do...maybe my structure is just plain crazy?

I've also noticed that the first time i navigate to a screen in the TabNavigator -> Stacknavigators set, the right button of the first header seems to sit on top, overlapping the right button of the next header but maybe this is related?

**Comment by satya164** [comment]
Can you record a video of what you mean?

**Comment by si-harps** [comment]
![react-navigation 1](https://cloud.githubusercontent.com/assets/2602859/22713548/d828bb24-ed80-11e6-97a1-5a347da6ee04.gif)

**Comment by si-harps** [comment]
sorry, the gif quality is shite

**Comment by satya164** [comment]
I think I have seen this exact flickering elsewhere. Might be a bug in `TouchableOpacity`, perhaps when used with native animations.

If you have some time, can you comment out this line https://github.com/facebook/react-native/blob/master/Libraries/Components/Touchable/TouchableOpacity.js#L101 under your `node_modules/react-native` and  check so we can know if it's related to native animations, or something else.

Also try returning `false` from here if the previous doesn't work out https://github.com/react-community/react-navigation/blob/ddb2107acdd844eac7eac6b3a1895238784e7e00/src/views/CardStackStyleInterpolator.js#L170

**Comment by grabbou** [comment]
@satya164 what are the actions we can take in order to fix it? Shall we wait for confirmations on what's solving the problem?

@si-harps let us know which of these did work for you. Coming up with as native-like look&feel as possible on iOS is a crucial thing. I am working on that in the meantime, any help would be appreciated.

**Comment by satya164** [comment]
> @satya164 what are the actions we can take in order to fix it

It's likely bug in the touchable component. I don't think we can take any actions to fix it in React Navigation.

**Comment by grabbou** [comment]
Cool, added `wontfix` label for now.

**Comment by si-harps** [comment]
@satya164 the first option (comment out this line https://github.com/facebook/react-native/blob/master/Libraries/Components/Touchable/TouchableOpacity.js#L101) certainly made the transition much smoother. The second option had no effect as far as i could tell. Thanks for the response. I guess this is a bug in react-native itself

**Comment by grabbou** [comment]
@si-harps I can confirm that I seen the same issues with other animations in the library, like flickering headers etc. It only happens once, at the first time animation triggers.

**Comment by kelset** [comment]
Pinging OP @si-harps since this issue is quite old and related to an old version of the lib. If no answer I'll close in 7 days.

**Comment by kelset** [comment]
Hi there @si-harps ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue (especially if it's a bug report) please open a new issue that uses the new Issue Template to provide some more details to help us solve it.

**Comment by nateblog** [comment]
I have the same issue, then tapping the back button, my custom header took a second before it changes. I don't think it is an issue in TouchableOpacity because the header itself is so delayed.

**Comment by Gregoirevda** [comment]
Getting the same error with a default `headerLeft` config used as custom back button.
The blink happens when you swipe back on iOS.

```jsx
 <Stack.Navigator
      screenOptions={({ navigation, route }) => ({
        headerBackVisible: false,
        headerLeft: () => <BackButton navigation={navigation} />
      })}>
      <Stack.Screen
        name="View1"
        component={View1}
      />
</Stack.Navigator>
```

This solves it

```jsx
 <Stack.Navigator
      screenOptions={({ navigation, route }) => ({
        headerBackVisible: false,
      })}>
      <Stack.Screen
        name="View1"
        component={View1}
        options={{headerLeft: () => <BackButton navigation={navigation} />}}
      />
</Stack.Navigator>
```

But this solves it too
```jsx
 <Stack.Navigator
      screenOptions={({ navigation, route }) => ({
         headerBackVisible: false,
        headerLeft: () => {
          return route.name === 'View1' ? null : <BackButton navigation={navigation} />;
        },
      })}>
      <Stack.Screen
        name="View1"
        component={View1}
      />
</Stack.Navigator>
```

This can probably be solved in the library instead.
Linked to [PR 1](https://github.com/react-navigation/react-navigation/pull/1)  @grabbou does it rely on `canGoBack()` which is slower?
