### ISSUE TITLE
Adding screens to DrawerNavigator

### ISSUE THREAD

**Issue by Solban** [react-community/react-navigation#2221]
What I am trying to do?
I have a DrawerNavigator and I would like to add items dynamically after the app has started.
For example, think of the Slack app. They have a navigationdrawer, where you can add Channels to. Then navigate to the added items on the navigationdrawer.

I have found no documentation or issues about how to achieve that.

**Comment by saeedhei** [comment]
You can use this:(https://reactnavigation.org/docs/navigators/drawer)

**Comment by Solban** [comment]
@saeedhei Thanks, adding a drawer is straightforward and understandable with the help of examples and docs. 

What I am having trouble with, is adding items to the drawer once it has been initialized and the app is running.

**Comment by chidionuekwusi** [comment]
+1

**Comment by gunn** [comment]
See also #2362

**Comment by spencercarli** [comment]
Closing for #2362
