### ISSUE TITLE
Tabs with other navigation system. Tabs and router?

### ISSUE THREAD

**Issue by yolosaucisson** [react-community/react-navigation#223]
Hi,

In my app (Android), I implemented some tabs (TabNavigator) in the top. But when I click on something on the first tab for example. I would like to open a new "scene" or screen about this one to have its datas.
How can I do this with react-navigation?

Sincerely,

**Comment by grabbou** [comment]
Hey, your question is very generic and so, it's hard to suggest any actionable tips. Please check `StacksInTabs` example, that shows how to push a stack with routes to any tab.

Let me know if that worked for you.
