### ISSUE TITLE
How to change background color of drawer

### ISSUE THREAD

**Issue by sa63** [react-community/react-navigation#2236]
How can I change Background Color of the drawer? I don't need to change drawer items need to change the background color of the drawer fully. By default, it's white while I need to make it Green. Is there any demo example?

**Comment by saeedhei** [comment]
Use this link (https://github.com/react-community/react-navigation/issues/2181#issuecomment-316232456)

**Comment by sa63** [comment]
Thanks for replying. In this link all about drawer items not about changing full drawer background :(

**Comment by valetarton** [comment]
@sa63 
He is referring to using a custom drawer component, when you do that you can manipulate all the properties of the drawer.
you can even use the built DrawerItems imported from react-navigation WITH your custom drawer component

**Comment by matthamil** [comment]
Closing this issue as the above answer should resolve this.

**Comment by Stophface** [comment]
@matthamil please re-open. I dont see from the given example where you can change the backgroundcolor of the whole `drawer`.

**Comment by tuananh11594** [comment]
drawerOpenRoute: "DrawerOpen",
drawerCloseRoute: "DrawerClose",
drawerToggleRoute: "DrawerToggle",
drawerBackgroundColor: "black",
insert it in DrawerNavigator
