### ISSUE TITLE
How to actually use redux connected components as Screens?

### ISSUE THREAD

**Issue by wachunei** [react-community/react-navigation#2237]
# The set up
I have set up a project with `redux` and `react-navigation`. Screens are `connect`ed stateless components, the state is being mapped from navigation state. Here is a simplified code example:
* Communes objects are stored at `state.communes`
* Navigation state is at `state.navigation`
* Connected component is being mapped its state through navigation state params
* `id` parameter inside `navigation.state.params` is set using `navigate(·, ·)`

This is a component, pretend it renders a `commune` object and its data.

```jsx
// Commune.js
const Commune = ({commune}) => <View><CommuneView commune={commune}/></View>;
export default Commune;
```

This will be the connected component, which will be used as a navigator screen.
```jsx
// CommuneContainer.js
// this is set as screen in StackNavigator
import get from 'lodash/get';
import Commune from './Commune';

const mapStateToProps = ({navigation, communes}) => ({
  commune: communes[get(navigation, ['routes', navigation.index, 'params', 'id'])],
  // previous line is mapping commune[id] to state, getting it from params of the
  // top of the stack 
});
const mapDispatchToProps = dispatch => ({ /* action creators are binded here */});

export default connect(mapStateToProps, mapDispatchToProps)(Commune)
```
# The problem
The problem shows up when navigating through these screens, since these are connected, they re-render on every state.['navigation' || 'communes'] change, so, when stacked, they are always showing the top `communes[id]`, and now that I write this, it may even don't exist if I combine another screens (let's say a `navigate(·, params)` without `id` inside of `params`).

Check the video to understand the problem, look how as transition happens, the data is showing the same info and then being re-rendered (since `navigation.index` is always the stack length): https://youtu.be/b3ZzUf9wd3o

# The cause
Well, of course this is supposed to happen, because of the way I'm mapping state.

# The question
So after all this it comes the question: Am I doing this right? Is this the approach I'm supposed to take on doing this? How am I supposed to do this correctly?
<hr />
PS:
<small><ul><li> Sorry for beaking the issue format</li><li>Adding the object (commune in this case) to the component state (making it stateful) is not a solution</li><ul></small>

**Comment by wachunei** [comment]
## A solution
After sleeping I've come up with a solution: instead of getting `params.id` from the `route` at top of the `state.navigation.routes` stack, I remembered `mapStateToProps` takes a second argument (`ownProps`) with the props passed to the connected component, which does not change when `state.navigation` changes. 

Updated code:

```jsx
// CommuneContainer.js
// this is set as screen in StackNavigator
import get from 'lodash/get';
import Commune from './Commune';

const mapStateToProps = ({communes}, {navigation}) => ({
  commune: communes[get(navigation,[ 'state', 'params', 'id'])],
  // previous line is mapping commune[id] to state, getting id from ownProps
});
const mapDispatchToProps = dispatch => ({ /* action creators are binded here */});

export default connect(mapStateToProps, mapDispatchToProps)(Commune)
```

(This solution also solves the problem of mixing different components on the stack)

## The Question
I'm glad I found a solution, but the question still stands, Is this a hack or the way it is supposed to be?

**Comment by matthamil** [comment]
Your solution looks good. I've used the second param of `mapStateToProps` to write selectors that use a navigation param as well.
