### ISSUE TITLE
how can hidde headertab

### ISSUE THREAD

**Issue by IZHQT** [react-community/react-navigation#2238]
occasionally， I need to hide the headertab of navigation，how can I do? I don't see in the document     .
![image](https://user-images.githubusercontent.com/6813909/28602831-e2c0e632-71f2-11e7-92ce-11458af47206.png)

**Comment by valetarton** [comment]
@IZHQT 
https://reactnavigation.org/docs/navigators/tab#tabBarVisible

**Comment by matthamil** [comment]
Closing this issue as the above solution should resolve it.
