### ISSUE TITLE
tabBarOnPress inside static 'navigationOptions' not working.

### ISSUE THREAD

**Issue by rimzici** [react-community/react-navigation#2239]
Thank you very much for the module.
Please Correct me If I am doing it in the wrong way.
I am trying to do some action while pressing the tab (NavigationStatechange does not meet the requirement).
### Current Behavior

'tabBarOnPress' function never getting called.

### Expected Behavior

ON pressing the tab, the current/active tab, expecting the 'tabBarOnPress' function to get executed. So that I can dispatch an Action from the function.
### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.12
| react-native     |  0.42.3
| node             |  6.3.1
| npm or yarn      | 3.10.3

To explain how I am trying to do:
snippet of my TabNavigator:
`const Tabs = TabNavigator(
	{
		Overview: {
			screen: Overview,
		},
	},
	{
		initialRouteName: 'Overview',
		tabBarOptions: {
			indicatorStyle: {
			},
			labelStyle: {
			},
			style: {
			},
			tabStyle: {
			},
			iconStyle: {
			},
			swipeEnabled: true,
			lazy: true,
			animationEnabled: true,
			upperCaseLabel: false,
			scrollEnabled: true,
			activeTintColor: '#F06F0C',
			inactiveTintColor: '#A59F9A',
			showIcon: true,
		},
	}
);`

and inside the 'OverView' component I am passing the 'navigationOptions' statically as suggested in the Documentation.

here is the snippet:

`static navigationOptions = ({ navigation }) => ({
		tabBarLabel: 'Overview',
		tabBarIcon: ({ tintColor }) => (
			<Icon name="icon_home" size={24} color={tintColor}/>
		),
		tabBarOnPress: (scene, jumpToIndex) => {
			console.log('test tab bar press overview');
		},
	});`

The function is never getting executed for me.

Thanks in Advance.

**Comment by beausmith** [comment]
@rimzici - Are you sure this is a bug? I tried using `tabBarOnPress` inside the static `navigationOptions` in my screen file using code nearly identical to what you are using and the `tabBarOnPress` method is called successfully.

**Comment by LiuTing0403** [comment]
@beausmith Which version did you use? I didn't find any code of `tabBarOnPress` in the latest version.

**Comment by beausmith** [comment]
@LiuTing0403 See steps here: https://github.com/react-community/react-navigation/pull/1335#issuecomment-320123143

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!

**Comment by sunilkumarc** [comment]
Even I'm facing the same problem as @rimzici. I even tried the solution suggested by @beausmith. Not sure if it's a bug or I'm doing something wrong.

**Comment by beausmith** [comment]
@sunilkumarc Post your code? 😉   Unless your code is identical to initial problem of course! Also note the version your are using. 

Note: The master branch of react-navigation (not the release branch) has recently been updated. I updated [my example](https://github.com/react-community/react-navigation/pull/1335#issuecomment-320123143) to reflect this.

**Comment by sunilkumarc** [comment]
I have a Tab navigator like below

```
const MyTabNavigator = TabNavigator({
    Track: {
        screen: MyStackNavigator,
    },
    Details: {
        screen: FundDetailsScreen,
    }
}, {
        tabBarPosition: 'bottom',
        tabBarOptions: {
            upperCaseLabel: false,
            activeTintColor: '#7562DB',
            inactiveTintColor: '#7562DB',
            pressColor: '#7562DB',
            indicatorStyle: { backgroundColor: '#6458A8' },
            style: {
                backgroundColor: '#fff'
            }
        },
        navigationOptions: ({ navigation }) => ({
            tabBarOnPress: (scene, jumpToIndex) => {
                console.log('onPress:', scene.route);
                jumpToIndex(scene.index);
            },
        }),
    });
```
From my screen **Track**, when I swipe left to the **Details** screen or click the **Details** tab, the log is not getting printed. So for some reason, the control is not going inside **tabBarOnPress** method.

My node version - 6.11.2
My npm version - 5.4.2

Any help is appreciated!

**Comment by nielsmadan** [comment]
Seems like tabBarOnPress is not in the current release. Had the same problem, and fixed it by adding the github master branch as a dependency.

package.json:

```
  "dependencies": {
    ...
    "react-navigation": "react-community/react-navigation#master",
    ...
  },
```

**Comment by sunilkumarc** [comment]
Cool. It's working! But it doesn't working on swipe to the next tab. Is there a work around for that too?

**Comment by assafb81** [comment]
@nielsmadan 
was this PR merged into the package?
I am using - `"react-navigation": "^1.0.0-beta.27",`

**Comment by brentvatne** [comment]
yes it was merged

if this is still a bug can you create a new issue that reproduces the bug on https://snack.expo.io? thanks!
