### ISSUE TITLE
StackRouter has error in react-native

### ISSUE THREAD

**Issue by mohsen158** [react-community/react-navigation#2244]
i want to use stack router in react native with react-navigation package 
but when i use it i get this error 
>Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
instantiateReactComponent
    D:\react-native\AwesomeProject\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1984:75
instantiateChild

my code:
        

     import React,{Component} from 'react'
     import  {StyleSheet, Text, View, AppRegistry} from 'react-native'
 
     import{StackRouter} from 'react-navigation'
     export default class Activity extends Component {

    constructor(props) {
        super(props);

    }

    render() {
        return (
            <Text> title:adsfdsf </Text>
        )
    }
    }

    const AwesomeProject = StackRouter({
    Home: {screen: Activity},

     }, {
    initialRouteName: 'Home',
     })
     AppRegistry.registerComponent('AwesomeProject', () => AwesomeProject);

**Comment by eslambasher** [comment]
import{StackRouter} from 'react-navigation' i think its here the problem you forgot the space between import and the components  

import { StackRouter } from 'react-navigation'

**Comment by mohsen158** [comment]
no it doesnt work :(
@eslambasher

**Comment by vonovak** [comment]
maybe you wanted to use `StackNavigator`, not router

**Comment by eslambasher** [comment]
why you want using StackRouter ?

**Comment by mohsen158** [comment]
i just want to test it  and know what is it exactly 
and i want to compare it with  stacknavigator
would you please help me
@eslambasher  @vonovak

**Comment by eslambasher** [comment]
i don't know how it's work , i just used stackNavigator but i  think you must create navigator for dispatch to router page you can looking in this page for example to block navigation there use stackRouter https://reactnavigation.org/docs/routers/#Blocking-Navigation-Actions

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!

**Comment by AyubaMakoa** [comment]
problem still not solved. stack router is different from the navigator. one is for web while one is for native. we want help to solve the problem of the router not the navigator.
