### ISSUE TITLE
dispatch action on tap Drawer or Tabbar item

### ISSUE THREAD

**Issue by EthanChouTW** [react-community/react-navigation#2245]
now I create a DrawerNavigator and one of the items is for logout,
is it possible to dispatch logout action `{ type: 'Logout' }` to reducer when on tap the drawer item
like the code below?

```
export const MainNavigator = DrawerNavigator({
  Home: {
    screen: OrderFulfillmentList
  },
  BranchesList: {
    screen: BranchesListScreen
  },
  Logout: {
    screen: LoginScreen
   /* onTapItem: dispatch(action)  */ //some function like this
  }
});
```

**Comment by kidequinox** [comment]
That would be awesome. I have the drawer as a component and I just manually add the logout item for now. But it would be cool if we could even bypass a screen prop and just dispatch a navigation action or redux.

**Comment by kelset** [comment]
Closing since this is now possible for both [Drawer](https://reactnavigation.org/docs/navigators/drawer#contentOptions-for-DrawerItems) and [TabBar](https://reactnavigation.org/docs/navigators/tab#tabBarOnPress)
