### ISSUE TITLE
Element type is invalid: Expected a string. Check the render method of contentComponent 

### ISSUE THREAD

**Issue by sa63** [react-community/react-navigation#2249]
![20427273_1585308044837547_1165824010_o](https://user-images.githubusercontent.com/30106593/28672808-cfc89a52-72f1-11e7-9474-a0fdb79e02b1.png)

I am trying to customize drawer navigator in my app. I am using react-navigation. When first time I've inserted this code it showed just white screen and even navigation links were disappeared after making few things it showed this error screen.  Here is the code.

**App.js**

```
import React from 'react';

import {StyleSheet, Text, View } from 'react-native';

import WelcomeScreen from './screens/WelcomeScreen';

import SigninScreen from './screens/SigninScreen';

import SignupScreen from './screens/SignupScreen';

import HomeScreen from './screens/HomeScreen';

import FoodScreen from './screens/FoodScreen';

import RestaurantsScreen from './screens/RestaurantsScreen';

import ProfileScreen from './screens/ProfileScreen';

import FavoritesScreen from './screens/FavoritesScreen';

import SettingsScreen from './screens/SettingsScreen';


import { TabNavigator, DrawerNavigator, StackNavigator,contentComponent } from 'react-navigation';

import {DrawerContent} from './components/DrawerContent'






export default class App extends React.Component {

render() {

const MainNavigator = TabNavigator({

  welcome: { screen: WelcomeScreen },

  signin: { screen: SigninScreen },

  signup: { screen: SignupScreen },

  main: {

       screen: DrawerNavigator({

         home: { screen: HomeScreen },

         food: { screen: FoodScreen },

         restaurants: { screen: RestaurantsScreen },

         profile: {

           screen: StackNavigator({

             profilw: { screen: ProfileScreen },

             settings: { screen: SettingsScreen }

           })

         }

       },

       {

  
  contentComponent: props => <DrawerContent {...props} />,
}

        )
     }
   },

   );


return (

  <MainNavigator />



);


}
}

**DrawerContent.js**

```
```
import React, { Component } from "react";

import { View, ScrollView,Button,Text } from "react-native";

class DrawerContent extends Component {
render() {

return (

  <ScrollView style={styles.container}>

    
  </ScrollView>
);

} }

const styles = {

container: {

flex: 1,

padding: 20,

backgroundColor: 'Green',

}, };

export default DrawerContent;
```

```






```

**Comment by TheMisir** [comment]
@sa63  how did you fixed this?

**Comment by ovxrfl0w** [comment]
Well, we will never know. Struggling with the same issue too.

**Comment by TheMisir** [comment]
I fixed my issue. I had made a mistake. I tried to import a component from the wrong package and tried to use it to render `contentComponent`. If anyone faced with the same issue just check your render function twice or more times.

**Comment by Monte9** [comment]
Same issue. I removed `DrawerItems` and it works.

Hmm.. so how do I use `DrawerItems` in the `customComponent` then?

**Comment by Monte9** [comment]
Huh I figured it out. Looks like you should use `DrawerNavigatorItems` instead of `DrawerItems`.

Here's the file for it: https://github.com/react-navigation/drawer/blob/master/src/views/DrawerNavigatorItems.tsx

**Comment by bouchezb** [comment]
> Huh I figured it out. Looks like you should use `DrawerNavigatorItems` instead of `DrawerItems`.
> Here's the file for it: https://github.com/react-navigation/drawer/blob/master/src/views/DrawerNavigatorItems.tsx

This fixed the issue for me. Thanks !
