### ISSUE TITLE
params !== state

### ISSUE THREAD

**Issue by mgtitimoli** [react-community/react-navigation#225]
Hi there!

Before moving forward, I want to thank you for your great work, keep on going!

I was wondering if you have ever thought of separating route state from params, since they are not the same conceptually, as for state, it should only be changed by the scene, while for the params, they should only be provided by the one that is activating the scene.

I'm not saying anything new, this separation is the same React does for props and state, but here `props == params`... 

Right now, I am doing this separation manually using a **Symbol** to get/set my internal params (that IMHO, they should have been called state...)

I would really like to hear your thoughts about this, thanks!

**Comment by ericvicenti** [comment]
I'm not quite sure what the difference is between params and state. Can you provide an example for each, and explain how they are used differently?

Why is it a bad thing for a screen to be able to change its params? Maybe you have a param like `isEditing`. A screen should be able to switch into and out of that state, and people who link to this screen may want to link to the edit mode or the normal mode.

**Comment by mgtitimoli** [comment]
Sure, one example could be the case of a dynamic title that depends on the scene internal state (f.e. `friendName`). Right now, the only way to pass this information is using **params** (by calling `navigation.setParams`), but this also leaves the door open for the one that is navigating to this scene, so it  could potentially set this params with whatever value it wants...

**Comment by satya164** [comment]
Hmm... sounds like React props vs state

**Comment by mgtitimoli** [comment]
Indeed @satya164, that's why I wrote:

> I'm not saying anything new, this separation is the same React does for props and state, but here props == params...

Another example I can bring here is what I'm doing now: a scene with a map that when the user moves it, it needs to display in the title how many items are in the centered location, and again, yep, I can use params, but IMHO this is not a param, but an internal state...

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
