### ISSUE TITLE
Background color covers only a half of the drawer

### ISSUE THREAD

**Issue by Hayko1994** [react-community/react-navigation#2250]
<img width="345" alt="drawer-nav" src="https://user-images.githubusercontent.com/22639899/28684404-4ad2b4d0-7315-11e7-9c67-383770c6a9bf.png">

How to cover with background full drawer? Here is the code of DrawerContent.

**DrawerContent.js**

```
import React, { Component } from "react";

import { View, ScrollView,Button,Text,StyleSheet } from "react-native";

import { DrawerItems } from 'react-navigation';

const  DrawerContent = (props) => (

  <View style={style.container}>

    <DrawerItems {...props} />

  </View>

);

const style = StyleSheet.create({

  container: {

  height: null,

    backgroundColor: '#00FF00',
  },
});

export default DrawerContent;

```

**Comment by valetarton** [comment]
@Hayko1994 
You'll want to take care to make sure you are using `flex: 1` in your DrawerContent View, otherwise since your height is null, the component will only go as far as the children.

**Comment by Hayko1994** [comment]
I've added flex:1 but its not solving my problem :(

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
