### ISSUE TITLE
Querystring params not set with the URI action

### ISSUE THREAD

**Issue by joeybaker** [react-community/react-navigation#2251]
### Current Behavior

When using the `URI` action, querystring params aren't set on the active route.

```js  
    import {NavigationActions, StackNavigator} from 'react-navigation'
    
    // very simple component
    const Foo = () => null
    
    const ChildNavigator = StackNavigator({Food: {path: 'foo', screen: Foo}})
    const ParentNavigator = StackNavigator({Child: {path: 'child', screen: ChildNavigator}})
    
    // ... instantiate ....
    
    const path = 'child/foo?bar=baz'
    const action = NavigationActions.uri({ uri: path })
    const nextState = getStateForAction(action)
    
    /*
    {
	index: 0,
	routes: [
	    {
		routeName: 'Child',
		index: 0,
		routes: [
		    // expected: `params: {bar: 'baz'}` to be included
		    {routeName: 'Foo'}
		]
	    }
	]
    }
    */
```

### Expected Behavior

The query string params should be set on the active route.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.11
| react-native     |  0.46.4
| node             |  7.10.0
| npm or yarn      |  0.27.5

**Comment by PatNeedham** [comment]
@joeybaker @spencercarli I figured it out. [Line 363 of `StackRouter.js`](https://github.com/react-community/react-navigation/blob/master/src/routers/StackRouter.js#L363) is not passing the `queryString` variable on to the next `getActionForPathAndParams` call in order to retrieve the nested action!

Changing that line from

    pathMatch.slice(pathMatchKeys.length).join('/')

to

    pathMatch.slice(pathMatchKeys.length).join('/') + '?' + queryString

did the trick for me.

**Comment by spencercarli** [comment]
Just merged the fix - thanks @PatNeedham! Will be out in the next release (hopefully this week).
