### ISSUE TITLE
handle back button android on drawer

### ISSUE THREAD

**Issue by dominicsavb** [react-community/react-navigation#2254]
How handle this scenario?

when drawer is close, press back button, then drawer will open and app will not exit
when drawer is open, press back button, then app will exit

Thank you

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
