### ISSUE TITLE
DrawerNavigatorItems

### ISSUE THREAD

**Issue by vlade2008** [react-community/react-navigation#2256]
Can u please add new props for the `DrawerNavigatorItems`  that can identify the item not will not display in the `DrawerItems`.. 
example:
![display](https://user-images.githubusercontent.com/13525454/28708427-d246a874-73ae-11e7-903a-24cfe337a522.png)

**Comment by matthamil** [comment]
See https://github.com/react-community/react-navigation/issues/717#issuecomment-289904770
