### ISSUE TITLE
usage of invariant results in unnecessary evaluations

### ISSUE THREAD

**Issue by vonovak** [react-community/react-navigation#2258]
`invariant` is used in places throughout the library, eg.

```
invariant(
      route && routes && index != null,
      `Expect nav state to have routes and index, ${JSON.stringify(route)}`
    );
```

found [here](https://github.com/react-community/react-navigation/blob/5e075e1c31d5e6192f2532a815b1737fa27ed65b/src/routers/createConfigGetter.js#L66)

The problem with this approach is that the second parameter to `invariant` is evaluated even though it may not be needed. In case of short strings that is negligible, but serializing an object to JSON, to me, seems like unnecessary waste. Let me know if a PR for this would be welcome.

**Comment by spencercarli** [comment]
PR would be welcome, but I would hold off a bit. We're trying to get out from under water with all the issues and pull requests so it could be a little while until we get to it and I wouldn't want you to put in the work and just have it sit there.

We're working on it and I or someone else will loop back around to this once we're at a point where we're merging PRs again 😄

**Comment by vojtechnovak** [comment]
Great to see somebody's taking care of the issues, I was under the impression this library is going to die... 
Thanks, will wait with this until somebody pings me.

**Comment by vonovak** [comment]
@spencercarli would a PR be accepted now?

**Comment by kelset** [comment]
I think you can start working on it, it looks it's a good way to reduce a bit the workload to avoid all these JSON.stringify - what are you planning on substituting it with?

**Comment by vonovak** [comment]
@kelset good question. eg:
```
invariant(
      route && routes && index != null,
      `Expect nav state to have routes and index, ${JSON.stringify(route)}`
    );
```

-->
```
if(!(route && routes && index != null)) {
  console.error(`Expect nav state to have routes and index, ${JSON.stringify(route)}`)
}
```
I think the question is:
1 . use console.warn, or console.error? I'd go with error
2 . how to rewrite the conditions: should I take the invariant condition and put a `!` in front of it, or change the conditions? I don't have a strong opinion on this, but using the extra `!` will leave no room for error when rewriting this... `if(!route || !routes || index === null))` is perhaps a little more readable though.. what do you think?

**Comment by kelset** [comment]
1. I think error is best, looks like places where it was used are quite important to not mess

1.  yeah probably `if(!route || !routes || index == null))` is better, meaning to separate at the best of your possibilties each element so that it's easier to re-write.
