### ISSUE TITLE
Request: git tag releases

### ISSUE THREAD

**Issue by thurt** [react-community/react-navigation#226]
it would be nice to have git tags for each release. this will make it easier to find what git commit lines up with what release version.

v1.0.0-beta.1 
8dd951aae727cc33bee5b1b7c1ce1a92f4fe8fee

**Comment by mrpatiwi** [comment]
Any plans for a `v1.0.0-beta.2` soon?

**Comment by grabbou** [comment]
@mrpatiwi we are working on it and it's planned to land today. Just last fixes and refinements and @satya164 will `npm publish` :)
