### ISSUE TITLE
How can I make the custom navigation bar transparent? I have tried all the options in react-native-router-flux like:   navigationBarStyle or navTransparent and also navigationBarStyle={[STYLES.navBar]}all of these are  not working while trying to make the custom navigation bar transparent  Is there any ways to make it transparent using react-navigation and should I change from react-native-router-flux to react-navigation to do this   

### ISSUE THREAD

**Issue by adarshTS** [react-community/react-navigation#2262]
### Current Behavior

this is my Router.js file 
import React from 'react';
import { Scene, Router } from 'react-native-router-flux';
import mainScreen from './components/mainScreen';
import challengeScreen from './components/challengeScreen';
import NavBar from './components/NavBar';

const RouterComponent = () => {
  return (
    <Router>
<Scene key="root">
    <Scene key="homeScreen" component={mainScreen} hideNavBar={1} />
    <Scene
     key="screen2" component={challengeScreen} navTransparent={1}
     navBar={NavBar}
     barStyle='transparent'
       />
</Scene>
    </Router>
  );
};
export default RouterComponent;

and this is my navigationbar js file 

`import {
 View, Image, StatusBar, TouchableWithoutFeedback
} from 'react-native';
import React, { Component } from 'react';
import { Actions, Router, Scene } from 'react-native-router-flux';

class NavBar extends Component {
  render() {
    return (
<View style={styles.backgroundStyle}>
      <StatusBar />
      <View style={{ flexDirection: 'row' }}>
      <TouchableWithoutFeedback onPress={() => Actions.homeScreen()}>
      <Image
    source={require('./Images/back-arrow.png')}
    style={styles.backarrowStyle} />
      </TouchableWithoutFeedback>

      <Image
  source={require('./Images/help.png')}
  style={styles.helpStyle} />

  <Image
source={require('./Images/setting.png')}
style={styles.settingStyle} />
    </View>
</View>
    );
  }

}
const styles = {
  backgroundStyle: {
    backgroundColor: 'transparent'
  },
  backarrowStyle: {
    resizeMode: 'contain',
    flexDirection: 'row',
    width: 55,
    height: 55,
    left: 0,
    justifyContent: 'flex-start'
  },
  helpStyle: {
    resizeMode: 'contain',
      width: 50,
      height: 50,
      left: 210,
      justifyContent: 'flex-end',
      position: 'relative'

  },
  settingStyle: {
    resizeMode: 'contain',
    width: 50,
    height: 50,
    justifyContent: 'flex-end',
  position: 'relative',
  left: 210
  }
};

export default NavBar;
`
### Expected Behavior

need to make the present navigation bar look transparent and the background be visible 

### Your Environment

    "react": "16.0.0-alpha.12",
    "react-native": "0.46.4",
    "react-native-router-flux": "^4.0.0-beta.14",
     "react-native-router-flux-nav-bar": "^1.1.0"

**Comment by PhillipWinder** [comment]
I would recommend switching from react-native-router-flux to react-navigation.

What you are looking for can be done easily with react-navigation by either using a TabNavigator and setting `tabBarVisible: false` or by using a StackNavigator and setting `header: null` depending on which kind of Navigator you need.

See: 
https://reactnavigation.org/docs/navigators/tab#tabBarVisible and https://reactnavigation.org/docs/navigators/stack#header

**Comment by adarshTS** [comment]
thanks @PhillipWinder I will surely try that but is there any way to do this without switching from react-native-router-flux

**Comment by PhillipWinder** [comment]
None that I would know of :)

**Comment by adarshTS** [comment]
I couldn't make the custom navBar transparent I tried all the methods suggested everywhere and i think its an issue with react-navigation and thats why i posted it as an issue it would be better to refer to some solution or giving a solution  rather than posting up views @augustoabreu

**Comment by massimopibiri** [comment]
This issue is not solved. It shouldn't be closed

**Comment by LukeTeng** [comment]
I am facing the same issue now. It is really necessary to provide a way to make the bar transparent.
