### ISSUE TITLE
npm install seems to work, yet empty react-navigation folder in node_modules

### ISSUE THREAD

**Issue by joelwass** [react-community/react-navigation#2265]
Empty folder within node_modules

### Current Behavior
When I run npm install - everything seems to work fine, however if i navigate into `node_modules/react-navigation/` the only file in the folder is package.json

this causes me to get an `Unable to resolve module 'react-navigation' from 'path/to/project/node_modules/'`

<img width="283" alt="screen shot 2017-07-29 at 2 45 42 pm" src="https://user-images.githubusercontent.com/7344422/28747448-a991f5dc-746c-11e7-9dd4-f7c369975e7a.png">

### Expected Behavior
I'm assuming that the react-navigation module can't be found because the folder within the node_modules folder is virtually empty.

### Your Environment
I'm running react native using Expo, version 2.19.2. 

| software         | version
| ---------------- | -------
| react-navigation |  0.0.0 ?
| react-native     |  https://github.com/expo/react-native/archive/sdk-19.0.0.tar.gz
| node             |  v8.2.1
| npm or yarn      |  npm v3.3.6

**Comment by reynaldoDev** [comment]
I join the request, I have the same error

**Comment by reynaldoDev** [comment]
Solucion
remove npm react-navigation

1 : npm install path-to-regexp --save
2: npm install --save react-navigation

**Comment by joelwass** [comment]
Following those steps, what does your node_modules/react-navigation folder contain?

**Comment by ismaildeve** [comment]
@joelwass  thank you so much its work
