### ISSUE TITLE
Cannot Swipe to Next Tab

### ISSUE THREAD

**Issue by quadsurf** [react-community/react-navigation#2266]
Swiping horizontally to advance to the next tab works great when tabs are on the top, but when tabs on are on the bottom, swiping stops working. How can I override this default so that the bottom tabs work like the top tabs, so that I can swipe left and right to switch between tabs.

**Comment by matthamil** [comment]
Can you provide info on your current dev environment, i.e. react-navigation version, RN version, and relevant code samples?

**Comment by quadsurf** [comment]
@matthamil oops, my bad, sorry for not including that initially

Expo 19, RN 47, and react-navigation@^1.0.0-beta.12

please see the expo demo... then tap on the primary "Tabs Example" ... if i swipe left on the screen, it should advance me from the 'Home' tab, to the 'People' tab, but it doesn't, which is okay if that's not the intended default, but i don't see any where in the docs where i can override that default to accommodate a more common usage of tabs, kind of like what the react-native-community built here: 
https://github.com/react-native-community/react-native-tab-view
https://raw.githubusercontent.com/satya164/react-native-tab-view/master/demo/demo.mp4

pls help

**Comment by kelset** [comment]
Pinging OP @quadsurf since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open; if I get no answer in the next 7 days I will close it.

**Comment by kelset** [comment]
Hi there @quadsurf ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.

**Comment by quadsurf** [comment]
@kelset so the issue stems from how Android and iOS differ on what a tab experience should be... for iOS, tab navigation on iOS defaults to tabs at the bottom of screen that are only tappable (not swipe-able), whereas tab navigation on Android defaults to tabs at the top of screen where tabs are BOTH tappable and swipe-able.

I COMPLETELY disagree with these defaults, but if they're going to be there, then the option to override those defaults, should be an option. Why you ask? Because many front-end developers PREFER a consistent UI experience across platforms, REGARDLESS of the disagreement between iOS and Android (in my opinion, Android's default is superior because it lets the user choose between taps or swipes to navigate, so if I want iOS to behave the way Android does, then this library should give me some control in overriding those defaults). Am I wrong for thinking this? Please advise, thanks!
