### ISSUE TITLE
Snapshot testing for stacknavigation components and ignoring certain keys

### ISSUE THREAD

**Issue by mateen-hussain** [react-community/react-navigation#2269]
I'm a newbie to React/Jest/JS and playing with react-navigation and jest. 
In my sample app  I have

       `const MainApp = StackNavigator({
              Home: {
                       screen: mapNavigationStateParamsToProps(SearchScreen)
              },
             SearchResults: {
                       screen: mapNavigationStateParamsToProps(SearchResultsScreen)
              },
         });

         function mapNavigationStateParamsToProps(SomeComponent) {
                return class extends Component {
                       static navigationOptions = SomeComponent.navigationOptions; // better use hoist-non-react-statics
                       render() {
                              const {navigation: {state: {params}}} = this.props
                              return <SomeComponent {...params} {...this.props} />
                       }
                }
          };

         export default class App extends React.Component {
                 render() {
                     return (
                         <View style={{ flex: 1 }}>
                           <StatusBar
                                barStyle="light-content"
                                backgroundColor={'#202930'} />
                           <MainApp />
                        </View>
                 );
          }
       }`

My snapshot test is as simple as 

       `describe('App', ()=> {
             it('renders app', ()=> {
               const tree = renderer.create(<App />).toJSON();
               expect(tree).toMatchSnapshot();
             });
         });`

I have two issues when I run the snapshot test:

**Issue 1) In the snapshot created there is no representation of the "SearchResults" Screen.** 

If I change the title of the component in navigationOptions, the test doesnt fail. However if I change the title of the "Home" screen component in navigationOptions, the test fails. 

So not sure if this is an issue in react-navigation or my test is not right for testing the "title section" of screens other than Home Screen

**Issue 2) The snapshot test for the StackNavigator always generates a random key and the test keeps failing.** 

         `expect(value).toMatchSnapshot()
          Received value does not match stored snapshot 1.
          - Snapshot
         + Received
    
         @@ -219,11 +219,11 @@
                 "setParams": [Function],
                 "state": Object {
                   "index": 0,
                   "routes": Array [
                     Object {
           -                  "key": "Init-id-1501348933188-0",
           +                  "key": "Init-id-1501364629304-0",
                               "routeName": "Home",
                     },
                   ],
                 },
               }
      
          at Object.<anonymous> (__tests__/App.test.js:14:14)`

How is this Key's value  assigned, and how can I mock/ignore for the test to pass consistently.

| software         | version |
| ---------------- | -------|
| react-navigation |  1.0.0-beta.11 |
| react-native     |  0.46.0 |
| node             | 6.11.1 |
| npm       | 3.10.10 |

**Comment by joeybaker** [comment]
The keys aren't really important for your testing purposes. What you really care about is the routes and the index. We just run the state through this function before handing it to the snapshot matching:

```js
// keys are date and order-of-test based, so just removed them
const filterKeys = (state) => {
  if (state.routes) {
    return {
      ...state,
      routes: state.routes.map((route) => {
        const { key, ...others } = route
        return filterKeys(others)
      }),
    }
  }
  return state
}
```

**Comment by mateen-hussain** [comment]
@joeybaker I got around the random key issue my mocking the DateTime function, which seems to be generating that random Key ID. But I still have the first issue i.e unable to test the "title of subsequent components of stack navigation". 

My suspicion is on my lack of understanding of testing of React/Snapshot. 

If you can give me any pointers (links) that would be great. I 'm a total newbie to react/JS

**Comment by joeybaker** [comment]
Is the title you're changing in `MainApp`? If so, the test isn't changing because you're doing a shallow render - only the first level of components are rendered. Take a look at the snapshot file.

**Comment by mateen-hussain** [comment]
No the title is part of navigationOptions property of every screen. When I generate the snapshot for individual screens I dont see the title for the screen in the snapshot. I tried changing the title to make the test fail, but it still passes.

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!

**Comment by dfcontr** [comment]
@joeybaker can you elaborate on the function to get rid of the keys? Where should I put that or how do I make it work? I am having the issue of being unable to test without -u because of the random key.

**Comment by joeybaker** [comment]
@dfcontr here's a sample test:

```js
  it('clears all other routes', () => {
    const inputState = {}
    const action = { type: AUTH_LOGOUT_SUCCESS }
    const state = filterKeys(reducer(inputState, action))
    expect(state.routes).toBe........
  })
```

**Comment by krislm** [comment]
@mateen-hussain I'm experiencing the same issue. How did figure the DateTime function was the culprit? And how did you mock it?

**Comment by mateen-hussain** [comment]
@krislm that key is a randomly generated number who seed value comes from Date.now. So mocking date.now in your jest setup.js should fix the problem.

```
// This is to mock the random Key-ID being generated for StackNavigation
Date.now = jest.fn(() => 148000000);
```

**Comment by joeybaker** [comment]
@mateen-hussain I don't have a repo to share, sorry. I can tell you that, while hacky, this does work for us:

```js
// keys are date and order-of-test based, so just removed them
const filterKeys = (state) => {
  if (state.routes) {
    return {
      ...state,
      routes: state.routes.map((route) => {
        const { key, ...others } = route
        return filterKeys(others)
      }),
    }
  }
  return state
}

it('clears all other routes', () => {
    const inputState = {}
    const action = { type: AUTH_LOGOUT_SUCCESS }
    const state = filterKeys(reducer(inputState, action))
    expect(state.routes).toBe........
})
```

**Comment by dantn93** [comment]
I tried to do something as @mateen-hussain but it's fail. The error is:
Details:

    /Users/macos/Dev/jesttest/node_modules/react-navigation/src/navigators/createContainedStackNavigator.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import createNavigationContainer from '../createNavigationContainer';
                                                                                             ^^^^^^

    SyntaxError: Unexpected token import

       8 | import People from './People'
       9 |
    > 10 | const MainApp = createStackNavigator({
         |                                    ^
      11 |   Home: {
      12 |            screen: mapNavigationStateParamsToProps(Home)
      13 |   },

Please help me!

**Comment by NgoVanTien** [comment]
https://github.com/react-navigation/react-navigation/issues/2269#issuecomment-413080770
PLEASE HELP ME .

**Comment by brentvatne** [comment]
see jest docs for info on how to use it with react-native. the error @dantn93 posted is related to this: https://jestjs.io/docs/en/tutorial-react-native#transformignorepatterns-customization

**Comment by 3rfan** [comment]
My solution to this issue:
```
jest.mock('react-navigation/src/routers/KeyGenerator', () => ({
  generateKey: jest.fn(() => 123)
}));
```

**Comment by gustavobarretto** [comment]
The react-native replace the KeyGenerator at routers to use [nanoid](https://www.npmjs.com/package/nanoid) at BaseRouter.tsx.

To solve this problem I needed to do the same mock as KeyGenerator, but I replaced to:
```javascript
jest.mock('nanoid/non-secure', () => ({
  nanoid: () => 1
}));
```
