### ISSUE TITLE
There is no route defined to key 'x' issue after I used a StackNavigator instead of a plain screen inside a TabNavigator

### ISSUE THREAD

**Issue by eliasturbay** [react-community/react-navigation#2270]
### Current Behavior

I’m working on a React Navigation / Redux integration basically … But I’m facing an app crash issue when I’m trying to nest a StackNavigator (3) inside a TabNavigator (2) (which BTW is also nested in another StackNavigator (1)) 

I’m getting the following error:
`There is no route defined to key Main. Must be one of : 'HomeScreen', 'ProfileScreen'`

so it’s now looking only at the routes of the nested StackNavigator (3) instead of using the routes of the StackNavigator (1) which is the one used for the Main navigation and is the one used in the Reducer

```
// (3)
const HomeStack = StackNavigator({
  HomeScreen: { screen: MainScreen },
  ProfileScreen: { screen: ProfileScreen }
});

// (2)
const MainScreenNavigator = TabNavigator({
  Home: { screen: HomeStack },
  Profile: { screen: ProfileScreen }
});

// (1)
export const AppNavigator = StackNavigator({
  Main: { screen: MainScreenNavigator },
  Login: { screen: LoginScreen }
});

const AppWithNavigationState = ({ dispatch, nav }) => (
  <AppNavigator navigation={addNavigationHelpers({ dispatch, state: nav })} />
);
```

I have a full code sample here (this little change caused the issue):
https://github.com/eliasturbay/reactnavigation-redux/compare/nested-navs-inside-tab-navigator?expand=1

### Expected Behavior

I should be able to use nested navigator without any problems

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  ^1.0.0-beta.11
| react-native     |  0.46
| node             | 8
| npm or yarn      | npm 4.6.1

**Comment by greghaygood** [comment]
I just ran into this as well. Make sure you assign unique keys for your different navs in your reducers. By default, Redux is looking for state.nav, which was overridden and led to this error (for me at least). Once I gave them unique keys, all worked as expected.

**Comment by devanshsadhotra** [comment]
@greghaygood can u paste your snippet here!

**Comment by devanshsadhotra** [comment]
i am experiencing the same things , my logout is on 4th tab and after that i need to go to sign In page, which is the initial screen. but it's not working , it showed me the error as @eliasturbay  got

**Comment by greghaygood** [comment]
Sure. (I'm using this in a RN+IgniteRed app, so your exact syntax might be diff)

```javascript
// reducers/index.js
 const rootReducer = combineReducers({
    appNav: require('./AppNavigationRedux').reducer,
    eventNav: require('./EventSubNavigationRedux').reducer,
})

// AppNavigationRedux.js 
export const reducer = (state, action) => {
  const newState = AppNavigation.router.getStateForAction(action, state)
  return newState || state
}

// EventSubNavigationRedux.js
export const reducer = (state, action) => {
  const newState = EventNavigation.router.getStateForAction(action, state)
  return newState || state
}

// AppNavigation.js 
const mapStateToProps = state => ({ nav: state.appNav })
export default connect(mapStateToProps)(ReduxNavigation)

// EventSubNavigation.js
const mapStateToProps = state => ({ nav: state.eventNav })
export default connect(mapStateToProps)(ReduxNavigation)

```

**Comment by devanshsadhotra** [comment]
@greghaygood  even i am using IGNITE 2.0

**Comment by sospedra** [comment]
We're experiencing the same.
Basically. Actions thar are not `navigate` doesn't know about nested navigators.

**Comment by ahanriat** [comment]
@greghaygood does it mean that you need to have a reducer + container per navigator?
@eliasturbay did you tried the solution of @greghaygood ?

**Comment by greghaygood** [comment]
@ahanriat yeah, as far as i could tell, i needed multiple reducers to support the different navigator types. i ended up switching over to react-native-router-flux, which smoothed out this and some other issues so i could get on with building my app. :)

**Comment by mujavidb** [comment]
I had a similar issue in the past where I had a tab navigator which contained a Stack and a Screen, like in your example. I solved it by **placing the Screen in its own stack**, that way **both Screens passed to the TabNavigator were Stacks**.

**Comment by kelset** [comment]
Pinging OP @eliasturbay since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open; if I get no answer in the next 7 days I will close it.

Moreover https://github.com/react-community/react-navigation/issues/2962 seems to pinpoint this issue better.

**Comment by kelset** [comment]
Hi there @eliasturbay ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.

**Comment by romandubrov** [comment]
I have updated to react-navigation@1.0.0-beta.22 and have same issue

**Comment by mymai91** [comment]
the problem here in StackNavigator they use screenProp. you should use screenprop to move page.

**Comment by brentvatne** [comment]
we don't support redux on this repository. if you have questions related to redux i suggest posting them on https://github.com/react-navigation/react-navigation-redux-helpers
