### ISSUE TITLE
How to connect a StackNavigator/TabNavigator directly to redux?

### ISSUE THREAD

**Issue by joncursi** [react-community/react-navigation#2271]
I am using Redux in my application. I have [followed the instructions](https://reactnavigation.org/docs/guides/redux) to get the Redux integration working with react-navigation.

Is it possible to connect a `TabNavigator` or a `StackNavigator` directly to redux? This is very useful for conditionally navigating to a screen, based on whether or not some condition exists in the Redux store (i.e. if the user is signed in or out).

Example:

```jsx
const Tabs = TabNavigator({
  [SOME_SCREEN_KEY]: {
    screen: userIsSignedInRedux ? SignedInTabNavigator : SignedOutScreen,
  },
});
```

... where `userIsSignedInRedux` is a key within my Redux store.

Notice here that I am trying to choose between rendering a set of tabs for signed in users (a TabNavigator), and rendering a single screen for signed out users (a React component).

If not directly connecting to Redux, is there some other way this effect can be achieved?

**Comment by ixje** [comment]
Have a look at the [Redux example](https://github.com/react-community/react-navigation/tree/master/examples/ReduxExample) that should give you an idea how you could handle it.

**Comment by joncursi** [comment]
The Redux example (https://github.com/react-community/react-navigation/blob/master/examples/ReduxExample/src/navigators/AppNavigator.js#L10) doesn't attempt to do what I'm describing above. There is no existing documentation for what I am asking as far as I can tell.

**Comment by ixje** [comment]
@joncursi the `nav` [func](https://github.com/react-community/react-navigation/blob/ae9fb10e60d2735cd2debaae34483510aa9ab3e9/examples/ReduxExample/src/reducers/index.js#L15) is the reducer of the StackNavigator defined in [AppNavigator.js](https://github.com/react-community/react-navigation/blob/ae9fb10e60d2735cd2debaae34483510aa9ab3e9/examples/ReduxExample/src/navigators/AppNavigator.js) . It's doing exactly what you want, but not at the location in the code you expect.

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
