### ISSUE TITLE
Does drawer navigation use the native thread for opening and closing drawer?

### ISSUE THREAD

**Issue by collinglass** [react-community/react-navigation#2273]
I am currently not using this library. 

I am having usability issues in my app when I have a block on the javascript thread and I'm trying to open and close the drawer. 

I'd like to know if the drawer navigation in this project uses the native thread for opening and closing animation of the drawer?

**Comment by matthamil** [comment]
This is a JavaScript-based solution to navigation. If your drawer is lagging when you open and close it, you might be doing something that locks the thread while the drawer is trying to animate.
