### ISSUE TITLE
Warnings on resizeMode props.style

### ISSUE THREAD

**Issue by alper** [react-community/react-navigation#2275]
| react-navigation |  ^1.0.0-beta.11
| react-native     |  ^0.46.4

Running the basic example throws warnings on the resizeMode prop being passed to View and RCTView.

Also the back button image is not shown.
![iphone 6s - ios 11 0 2017-07-31 16-24-49](https://user-images.githubusercontent.com/72429/28782248-eb3c83e8-760c-11e7-96ac-7941d40df5fe.jpg)

**Comment by spencercarli** [comment]
Is this occurring when running the [NavigationPlayground](https://github.com/react-community/react-navigation/tree/master/examples/NavigationPlayground) example?

**Comment by alper** [comment]
Sorry, I think this was caused by my failure to include the `RCTImage` pod subspec which causes Images to fallback to Views and then these kind of things seem to break.

My bad, but for a lot of the functionality it is not immediately obvious which podspecs you need to include and then if you don't things break in curious ways.
