### ISSUE TITLE
navigator.navigate is handled by parent navigator instead of child navigator after BackHandler.exitApp()

### ISSUE THREAD

**Issue by nicemanis** [react-community/react-navigation#2276]
I have a nested navigator structure:
```
const Tab1Navigator = StackNavigator({
  Tab1: { screen: routes.Tab1 },
  OtherScreen: { screen: routes.OtherScreen }
});

const Tab2Navigator = StackNavigator({
  Tab2: { screen: routes.Tab2 }
});

const AuthenticatedNavigator = TabNavigator({
  Tab1: { screen: Tab1Navigator },
  Tab2: { screen: Tab2Navigator }
});

const UnauthenticatedNavigator = StackNavigator({
  Login: { screen: routes.Login },
  Register: { screen: routes.Register }
});

const AppNavigator = StackNavigator({
  Unauthenticated: { screen: UnauthenticatedNavigator },
  Authenticated: { screen: AuthenticatedNavigator }
});

```

If I call `this.props.navigation.navigate('Tab1')` normally it would dispatch `Navigation/NAVIGATE` action with `routeName: Tab1`, but if I exit the app with `BackHandler.exitApp()`, then when I call `this.props.navigation.navigate('Tab1')` it dispatches `Navigation/NAVIGATE` action with `routeName: Authenticated` instead of the expected `routeName: Tab1` and it results in a duplicated `Authenticated` route in the root stack navigator.

I have tried changing the keys for the tabs, so that they don't match the actual screen keys, but it doesn't solve this issue.

### Environment

| software         | version
| ---------------- | -------
| react-navigation |  ^1.0.0-beta.11
| react-native     |  0.46.4
| node             | v6.5.0
| npm or yarn      | 3.10.7

**Comment by spencercarli** [comment]
A running demo would be very helpful in debugging this issue - thanks!

**Comment by kelset** [comment]
Pinging OP @nicemanis since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open; if I get no answer in the next 7 days I will close it.

**Comment by kelset** [comment]
Hi there @nicemanis ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.
