### ISSUE TITLE
Request: The get started guides seem incomplete to me, could they be expanded?

### ISSUE THREAD

**Issue by whimsybit** [react-community/react-navigation#228]
I tried following the Get Started -> Hello Mobile Navigation guide and I failed on adding the second screen.

I did manage to get the first screen up and running, but, upon trying to add the second screen, the guide is apparently skipping steps and/or wrong.  It looks to me like we're moving a const from the HomeScreen to the ChatScreen, and neither of the example sources include all the imports after the first screen is finished.

It would be helpful to have complete, working versions of the steps in the guide somewhere, like, after following the Hello Mobile Navigation guide, this is what you should end up with.

On a lot of my attempts to fix it myself, I end up with an error saying that it expects a route to define a screen, but, as far as I can tell, I've met the requirements for doing just that.

**Comment by grabbou** [comment]
Thanks for trying out the library and going through the examples! The main problem that I see with them is that they are made by the library authors - as far as we try to be as descriptive as possible, it is possible we skip some things that are not so obvious for newcomers. 

If you could try to fix it by submitting some PRs, that would be great! Please ask any questions - I'll try to help you get moving as quickly as possible.

**Comment by kelset** [comment]
Closing this since it's quite old, and the intro guide has been updated many times.
