### ISSUE TITLE
Nested navigation not being updated, and allows to mount component multiple times

### ISSUE THREAD

**Issue by facuescobar** [react-community/react-navigation#2281]
### Navigation Structure
This is my parent navigator, it is using **mode: 'modal'**, 
main screen is not unmounted when **error** screen is mounted

```javascript
export default StackNavigator(
  {
    main: {
      screen: HomeNavigator,
      path: '/'
    },
    error: {
      screen: Error,
      path: '/error'
    }
  },
  {
    initialRouteName: 'main',
    headerMode: 'none',
    mode: 'modal'
  }
);
```

This is my main screen (HomeNavigator)
```javascript
export default StackNavigator(
  {
    home: {
      screen: Home
    },
    profile: {
      screen: Profile
    },
    photos: {
      screen: Photos
    }
  },
  {
    initialRouteName: 'home',
    headerMode: 'none'
  }
);
```

A few things to know:
- All screens extends from Screen component.
- Screen component is connected to redux, which means, all screens are connected to redux and, in each redux update, each screens checks if necessary information to access to the screen is correct.

And now, based on each update, an screen can **this._navigate** to an specific screen.
```
//If condition checks if navigation state is different to prevent multiple calls over the same component 
_navigate(screen, props){
    const { navigation } = this.props;
    if (navigation.state.routeName !== screen.routeName) {
      navigation.navigate(screen.routeName, screenProps);
    }
}
```

### Current Behavior
- When the app start, loads **Home** screen.
- Home screen dispatch two actions to make two API requests. Let's call them **session**, and **profile**.
- If **session** request is completed, and the request gets an **ERROR**
- **home** screen receives this information and call **this._navigate('error')**
- **this._navigate()** checks that current screen is not **error** screen, so, **Error** screen is mounted.
- So now, **Home** screen and **Error** screen are mounted, and receive redux updates.
- When **profile** request is done:
 - **Error** screen checks this information, and try to **this._navigate('error')**, but it doesn't do anything, because navigation.state.routeName is **error**.
 - **Home** screen checks this information, and try to this._navigate('error'), navigator.state.routeName is 'home' (**not Error**) so, navigation.navigate('error') is executed again, and Error screen is mounted twice.

### Expected Behavior
If a nested navigation can navigate to any parent or child screen, child navigation should get parent navigation updates.

Home screen navigation state is still 'home', but 'home' screen already called navigation to navigate to 'error'. So, home navigation should get this update.

### Your Environment
This is my Expo project package.json:
```json
"expo": "^18.0.9",
"react": "16.0.0-alpha.12",
"react-native": "https://github.com/expo/react-native/archive/sdk-18.0.1.tar.gz",
"react-navigation": "^1.0.0-beta.11",
"react-redux": "^5.0.5",
"redux": "^3.7.1",
"redux-thunk": "^2.2.0"
```

Cheers!

**Comment by Shubham-Sinha** [comment]
Did you find any solution to it. In my case number of times the screen is mounted is equal to the level of nesting.

**Comment by facuescobar** [comment]
Hi @Shubham-Sinha , this is the solution I've found to prevent mounting the same screen multiple times.
I didn't find any solution to create a top level navigator component to control all screens. I think it would be a great way to manage screens, but for some reason, react-navigation wasn't created for that purpose.

Here's the solution I've found:
Route actions can be cancelled overriding getStateForAction function

Here's an example from official docs
```javascript
const MyStackRouter = StackRouter({
  Home: { screen: HomeScreen },
  Profile: { screen: ProfileScreen },
}, {
  initialRouteName: 'Home',
})

const defaultGetStateForAction = MyStackRouter.router.getStateForAction;

MyStackRouter.router.getStateForAction = (action, state) => {
  if (
    state &&
    action.type === NavigationActions.BACK &&
    state.routes[state.index].params.isEditing
  ) {
    // Returning null from getStateForAction means that the action
    // has been handled/blocked, but there is not a new state
    return null;
  }
  
  return defaultGetStateForAction(action, state);
};
```
https://reactnavigation.org/docs/routers/api

Cheers!

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
