### ISSUE TITLE
create-react-native-app and react navigation no responsive design possible

### ISSUE THREAD

**Issue by Stophface** [react-community/react-navigation#2284]
I created a `react native` project with `create react native app`. I implemented the `react navigation` and it works - sort of. 
In order to show the bottom navigation on android, it needs a `width`. I do it this way

`  tabBarOptions: {
    style: {
      width: Dimensions.get('window').width,
    },`

I tried to replace the `width` by using `flex dimension`

`  tabBarOptions: {
    style: {
      flex: 1,
    },`

That caused the bottom navigation not to show at all.  A similar problem with `create-react-native-app` was reported and discussed here: https://github.com/react-community/react-navigation/issues/713

### Current Behavior
Setting the `width` this way (`Dimensions.get`) causes the navigation (on turning the phone horizontally) to stay just as big as it was when the phone was hold vertically. It only takes the initial `width` on startup I suppose.

### Expected Behavior
I want the bottom navigation to stretch out over the whole screen when the phone is turned horizontally.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.11
| react-native     |  0.46.1
| node             | v6.11.1
| npm or yarn      | v0.27.5 (yarn)

**Comment by Stophface** [comment]
is that expected behaviour?

**Comment by spencercarli** [comment]
You should just be able to use the [`tabBarPosition`](https://reactnavigation.org/docs/navigators/tab#TabNavigatorConfig) configuration to set the tab bar to the bottom. Have you tried that (instead of setting width/flex)?

**Comment by Stophface** [comment]
@spencercarli That doesnt work on `Android`. On iOS it does.

**Comment by spencercarli** [comment]
Unable to reproduce with the following code

```javascript
import React from 'react';
import { Text, View, StyleSheet } from 'react-native';
import { Constants } from 'expo';
import { TabNavigator } from 'react-navigation'; // 1.0.0-beta.11

const Screen = ({ title }) => (
  <View style={styles.container}>
    <Text style={styles.paragraph}>
      {title}
    </Text>
  </View>
);

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: Constants.statusBarHeight,
    backgroundColor: '#ecf0f1',
  },
  paragraph: {
    margin: 24,
    fontSize: 18,
    fontWeight: 'bold',
    textAlign: 'center',
    color: '#34495e',
  },
});

export default TabNavigator(
  {
    Home: { screen: () => <Screen title="Home" /> },
    BBQ: { screen: () => <Screen title="BBQ" /> },
    Recipes: { screen: () => <Screen title="Recipes" /> },
  },
  {
    tabBarPosition: 'bottom',
  }
);
```

[Running example](https://snack.expo.io/SJ-kdgUuW)

Please provide a demo of this issue and I can re-open.
