### ISSUE TITLE
Wrong navigation with TabNavigator inside StackNavigator when swiping if one of headers is not set

### ISSUE THREAD

**Issue by konradkierus** [react-community/react-navigation#2286]
### Current Behavior
Click on third tab and start swiping tabs back to the first one. The header title switches as expected but we end up with content of 'Tab2' instead of 'Tab1'. Also, the tab bar shows we are on Tab2 but we can't go to Tab1 as the react-navigation still thinks we are on the Tab1.
This is somehow related with 'header:null' as with header on Tab3 everything works as expected.
Does anyone have a suggestion for a workaround?

Example code to reproduce the issue and GIF presenting the issue below:
[![tab_issue.gif](https://gifyu.com/images/tab_issue.gif)](https://gifyu.com/image/zKBp)
```javascript
import React from 'react';
import { View, Text } from 'react-native';
import { TabNavigator, StackNavigator } from 'react-navigation';

const Tab1 = () => <View><Text>Tab 1</Text></View>;
const Tab2 = () => <View><Text>Tab 2</Text></View>;
const Tab3 = () => <View><Text>Tab 3</Text></View>;

const TabbedNavigator = TabNavigator(
  {
    Tab1: { screen: Tab1, navigationOptions: { title: 'Tab1' } },
    Tab2: { screen: Tab2, navigationOptions: { title: 'Tab2' } },
    Tab3: { screen: Tab3, navigationOptions: { header: null } },
  }, {
    tabBarPosition: 'bottom',
    swipeEnabled: true,
    animationEnabled: true,
  },
);

const AppNavigator = StackNavigator({
  Home: {
    screen: TabbedNavigator,
  },
});

const App = () => (
  <View style={{ flex: 1 }}>
    <AppNavigator />
  </View>
);

export default App;
```

### Expected Behavior
Swiping should work as expected and we should end up on Tab1 with correct title, content and tab bar position.

### Your Environment
The issue exists on both Android and iOS but the example code was tested on Android only.

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.12 but tried with 1.0.0-beta.11 as well
| react-native     |  0.45.1
| node             |  7.8.0
| npm or yarn      |  npm 4.2.0

**Comment by konradkierus** [comment]
I've noticed the issue is caused because of the callback on animation frame in react-native-tab-view dependency project because when header becomes visible/hidden then `this.props.layout.height` changes and `componentWillReceiveProps` is called here: https://github.com/react-native-community/react-native-tab-view/blob/master/src/TabViewPagerAndroid.js#L45
Commenting out this method fixes this issue but I'm not sure what is exact purpose of this method so @satya164 I'm leaving this here to not duplicate the issue on react-native-tab-view project.

**Comment by spencercarli** [comment]
I don't have a solution for you, but I just wanted to thank you for the very descriptive and clear bug report! Hopefully we can sort this out soon.

**Comment by kelset** [comment]
Pinging OP @konradkierus since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open; if I get no answer in the next 7 days I will close it.

**Comment by kelset** [comment]
Hi there @konradkierus ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.
