### ISSUE TITLE
Failed get params on StackNavigator

### ISSUE THREAD

**Issue by creativefull** [react-community/react-navigation#2290]
i read tutorial from https://reactnavigation.org/docs/navigators/navigation-prop . and i try in my code, but params always undefined. my question, how to send param when i click a button and change a screen ?

**Payment.js**
```js
    render() {
        const {navigate} = this.props.navigation
        return (
            <View>
                <Text>Pembayaran</Text>
                <Button
                    onPress={() => navigate('Profile', {balance : 80809})}
                    title="My Balance"/>
            </View>
        )
    }
```
**Profile.js**
```js
    render() {
        const {state} = this.props.navigation
        return (
            <View>
                <Text>Your Balance: {state.params.balance}</Text>
            </View>
        )
    }
```
| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.11
| react-native     |  0.46.4
| node             | v8.1.4
| npm or yarn      | npm 5.0.3

**Comment by matthamil** [comment]
Can you post your navigation setup?

**Comment by creativefull** [comment]
this is

```js
const Drawer = DrawerNavigator({
    Home : {
        screen : Home
    },
    Profile : {
        screen : ProfileScene
    },
    Payment : {
        screen : PaymentScene
    },
})

const App = StackNavigator({
    Drawer : {
        screen : Drawer
    }
}, {
    headerMode: 'none'
})
export default App
```

**Comment by creativefull** [comment]
now i got a params object, but i can't get key params. example

```js
{
balance : 200
}
```
when i try to console.log(params) its work fine, but when i try console.log(params.balance) i got undefined. what should i do ?

**Comment by spencercarli** [comment]
Seems there may be a bug when passing params & using DrawerNavigator

**Comment by jjdp** [comment]
#1072

**Comment by kelset** [comment]
Pinging OP @creativefull since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open; if I get no answer in the next 7 days I will close it.

**Comment by kelset** [comment]
Hi there @creativefull ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.
