### ISSUE TITLE
Failed to get Params on page coming using goBack()

### ISSUE THREAD

**Issue by nilaybrahmbhatt** [react-community/react-navigation#2296]
hey,

I navigate same pages recurringly using different params all time.
I got params and all perfectly when go to the page using navigation.navigate() function but when i come back to page using header back button or goBack() function i didn't get params in componentWillMount nor componentWillReceiveProps.

please tell me how can I get that param?

**Comment by spencercarli** [comment]
When you're navigating to new screens the previous screens are not unmounted. Therefore when you goBack to them they're just becoming visible again, not remounting.

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
