### ISSUE TITLE
Dynamically hiding the Navigation Bar works on iOS, but not on Android

### ISSUE THREAD

**Issue by puelocesar** [react-community/react-navigation#2302]
I have this screen, who belongs to a StackNavigator, and I want to hide the navigation bar when showing the searchBar. I did it with the following code:

    static navigationOptions = ({ navigation }) => {

        if (navigation.state.params && navigation.state.params.showSearch) {
            return { header: null }
        }

        return ({
            title: `Atendimento`,
            headerRight: navigation.state.params ? navigation.state.params.headerRight : null,
        })
    };

This works fine on iOS, but on Android, I get a blank header above my UI. Any ideas?

Example:
![alt text](https://media.giphy.com/media/3o6vY4CPcdD5WaKL6w/giphy.gif "Logo Title Text 1")

Note that after showing the header for the first time, it's background won't go away anymore

**Comment by spencercarli** [comment]
If you could provide a sample project demonstrating this issue I (or someone else) would be able to much more help as we wouldn't need to rebuild components. Thanks 😄
