### ISSUE TITLE
StackNavigator navigation to the same route doesn't work

### ISSUE THREAD

**Issue by DevSzurmanski** [react-community/react-navigation#2304]
### Current Behavior
I have in stack navigator an Article. I'd like to navigate from this Article to another with same route, but other parameters. It logs all of the parameters and they are correct, but it doesn't navigate. When I change route it works.

### Expected Behavior
It should just navigate and back arrow should navigate to the previous Article.

### Your Environment
RN 0.47.1
React-Navigation 1.0.0-beta.11

**Comment by DevSzurmanski** [comment]
False alarm xD. I had anti double click from github issue:
```Javascript
const navigateOnce = getStateForAction => (action, state) => {
  const { type, routeName } = action;
  return state &&
  type === NavigationActions.NAVIGATE &&
  routeName === state.routes[state.routes.length - 1].routeName
    ? null
    : getStateForAction(action, state);
};

Navigation.router.getStateForAction = navigateOnce(Navigation.router.getStateForAction);
```
I totally forgot about it. It did a good job with double click, but it caused this problem.

**Comment by spencercarli** [comment]
Since it seems your issue is fixed I'm going to go ahead and close this. Just as a reminder - when an issue is fixed please close the issue. Thanks!

**Comment by shardick** [comment]
It's a bit late, but come into this issue only now and searching on Google landed here.

I've resolved using a "fake" screen that dispatch the navigation, so the stack is filled with different route key:

```
class NavigationDispachter extends BaseTruckyScreen {
    // eslint-disable-line

    constructor(props)
    {
        super(props);
    }

    componentDidMount()
    {
        this.props.navigation.navigate(this.props.navigation.state.params.to, this.props.navigation.state.params);
    }

    render() {
        return (
            <View />
        );
    }
}

import { globalMapStateToProps } from '../reducers';

export default connect(globalMapStateToProps, null)(NavigationDispachter)
```

Navigate to this route with this:

`
this.props.navigation.navigate('NavigationDispatcher', { to: 'UserProfile', steamID: row.account.steam_id, goBack: 'MyProfile' })
`

hope this helps.
