### ISSUE TITLE
Blurred/transparent header

### ISSUE THREAD

**Issue by mazing** [react-community/react-navigation#2306]
Many apps, including Netflix, Spotify, and Tidal, have a blurred header so you can see the content changing behind it.

How do you accomplish this? I know I can use `react-native-blur` to get the blurred effect, but how do you make the content behind it visible? Do you have to make an absolutely positioned header? If so, how do you make sure the content in the top of each screen is visible? Do you create a top margin on every single screen?

**Comment by spencercarli** [comment]
You could [create your own header](https://reactnavigation.org/docs/navigators/stack#header) component and make that with a blurred background.

**Comment by spencercarli** [comment]
Going to close this issue - this would probably be better for StackOverflow since it's more of a question related to your specific app. Thanks!

**Comment by rogchap** [comment]
```
static navigationOptions = ({ navigation }) => {
    return {
      headerStyle: {
        backgroundColor: 'transparent',
        right: 0,
        left: 0,
        top: 0,
        position: 'absolute',
        borderBottom: '0',
      },
    };
  }
```

**Comment by SKempin** [comment]
@rogchap  I have attempted to replicate this in my code but I can't get it working. I'm using `2.4.1`:

```
export const MainStack = createStackNavigator(
  {
    Home: {
      screen: SearchScreen,
      navigationOptions: {
        title: "Search"
      }
    },
    Details: {
      screen: DetailsScreen,
      navigationOptions: ({ navigation }) => ({
        title: `${navigation.state.params.title}`,
        headerMode: "screen",
        headerStyles: { backgroundColor: "transparent" }
      })
    }
  },

  {
    headerTransitionPreset: "uikit",
    navigationOptions: {
      // headerTransparent: true,
      headerStyles: { backgroundColor: "transparent" },
      headerMode: "screen",
      headerBackground: Platform.select({
        ios: <BlurView style={{ height: 50 }} intensity={98} />,
        android: (
          <View
            style={{
              flex: 1,
              height: 50,
              backgroundColor: "rgba(255,255,255,0.5)"
            }}
          />
        )
      })
    }
  }
);
```
