### ISSUE TITLE
Make TabNavigation visible when using StackNavigation

### ISSUE THREAD

**Issue by yolosaucisson** [react-community/react-navigation#231]
Hi,

It should be great if with react-navigation, tabs are still visible when you have tabs and one button open an stacknavigation.
https://reactnavigation.org/docs/intro/nesting
Because on this example (at the bottom), on stacknavigation, there tabs are no more visibles :(

Sincerely,

**Comment by Freddy03h** [comment]
In the example, TabNavigator is inside StackNavigator.
You want the reverse : StackNavigator inside TabNavigator, and it's already possible.

You'll need a StackNavigator for each Tab.

**Comment by yolosaucisson** [comment]
Thanks for your help
Do you have an exemple to understand a little bit more how to do? :D

**Comment by jcarbo** [comment]
Given these components from the examples:
```jsx
class RecentChatsScreen extends React.Component {
  render() {
    return <Text>List of recent chats</Text>
  }
}

class AllContactsScreen extends React.Component {
  render() {
    return <Text>List of all contacts</Text>
  }
}

class ChatScreen extends React.Component {
  render() {
    return <Text>Individual chat</Text>
  }
}
```

The examples show a TabNavigator within a StackNavigator:
```jsx
const MainScreenNavigator = TabNavigator({
  Recent: { screen: RecentChatsScreen },
  All: { screen: AllContactsScreen },
});

const SimpleApp = StackNavigator({
  Home: { screen: MainScreenNavigator },
  Chat: { screen: ChatScreen },
});
```

You want something like this:
```jsx
const MainScreenNavigator = StackNavigator({
  Recent: { screen: RecentChatsScreen },
  All: { screen: AllContactsScreen },
});

const SimpleApp = TabNavigator({
  Home: { screen: MainScreenNavigator },
  Chat: { screen: ChatScreen },
});
```

Notice the "base" navigator here is the tab navigator. Within the first "tab" you have a stack navigator, so you can navigate b/w those screens.

**Comment by yolosaucisson** [comment]
Thanks you a lot  :)
