### ISSUE TITLE
Bottom tab bar display issue on larger devices

### ISSUE THREAD

**Issue by devericx** [react-community/react-navigation#2313]
I'm trying to display a bottom tab bar for iOS navigation. It looks fine on the default iPhone 6 emulator, but on the iPhone 7 Plus emulator there are these weird grey rectangles on the top and bottom of the tab bar.

<img width="465" alt="screen shot 2017-08-04 at 4 29 48 pm" src="https://user-images.githubusercontent.com/24878221/28985924-d335c6d2-7932-11e7-9f9e-fa181f0b0a33.png">

Any idea why this could be occurring? Here's the style code for the tab bar component.

```
tabBarOptions: {
      showLabel: false,
      activeTintColor: '#000',
      style: {
        paddingTop: height * 0.08,
        paddingBottom: height * 0.08,
        borderTopWidth: 0.5,
        backgroundColor: '#fff',
      },
},
```
Thanks.

**Comment by spencercarli** [comment]
Where is the `height` value coming from? That could be messing things up

**Comment by vonovak** [comment]
Since the issue has been inactive for a long time, I'm closing it. It also seems like a usage question better suited for SO.
