### ISSUE TITLE
Issue to run the example project

### ISSUE THREAD

**Issue by ansonyao** [react-community/react-navigation#2314]
I downloaded the project and go to the Example folder. I run "npm install", it said  Babel command is unknown. So I did "npm install babel-cli -g". Then I try "npm install" again and I get the following results:

ReferenceError: Unknown plugin "transform-flow-strip-types" specified in "/Users/ansonyao/Desktop/react-navigation/.babelrc.env.publish-web" at 0, attempted to resolve relative to "/Users/ansonyao/Desktop/react-navigation"

I am not sure what is this unknown plugin and how to fix this. I am on a Mac computer.

React-Navigation: I am on master branch on Aug 1, 2017. commit b00208b. 
React-native cli: 2.0.1
node 6.11.0
npm 4.6.1

**Comment by alper** [comment]
I did a fresh checkout and ran `yarn install` in that directory without problems.

But then when I try to run the example as described in [contributors](https://reactnavigation.org/docs/guides/contributors), it gives me:

```
yarn run v0.27.5
$ cd examples/NavigationPlayground && npm run ios

> NavigationPlayground@0.1.0 ios /Users/alper/Documents/projects/volders/react-navigation/examples/NavigationPlayground
> react-native-scripts ios

1:25:31 PM: Starting packager...
1:25:50 PM: Starting simulator...
1:25:57 PM: Failed to start simulator:

Error: Process exited with non-zero code: 2

Exiting...
Done in 28.81s.
```

**Comment by spencercarli** [comment]
I'm running into this issue as well. Not sure if it's just documentation issues or if the playground example is broken.

**Comment by spencercarli** [comment]
Tracking example related issues here in #2168
