### ISSUE TITLE
Passing navigation prop down to navigator in contentComponent

### ISSUE THREAD

**Issue by MyTotoro** [react-community/react-navigation#2316]
### Current Behavior
I have a Stack, Drawer, and Stack navigator

````
Stack [
  Screen1
  Screen2
  Drawer
]

Drawer [
  Screen3
  Screen4
  Stack2
]

Stack2 [
  Screen5
  Screen6
]
````
I recently modified the Drawer to have its own contentComponent, and each screen to a wrapper screen so I can add icons and colors

````

SettingsWrapper extends React.Component {
  constructor (props) {
    super(props)
  }

  static navigationOptions = {
    drawerLabel: 'Settings',
    drawerIcon: () => (
      <Icon
      />
    )
  }

  render() {
    const navigation = this.props.navgiation
    return (
      <SettingsNavigationRouter
        navigation={navigation}
      />
    )
  }
}

const CustomDrawerContentComponent = (props) => (
  <ScrollView>
    <DrawerItems {...props} />
  </ScrollView>
)

routes = {
  Settings: {
      screen: SettingsWrapper
    }
}

backBehavior: 'initialRoute',
contentComponent: CustomDrawerContentComponent
````

### Expected Behavior
I expected the navigation to flow down as expected

````
const navigation = this.props.navgiation
   
    return (
      <SettingsNavigationRouter
        navigation={navigation}
      />
    )
````
Does not crash but tapping on a child of SettingsNavigationRouter does not do anything - debuging the state tree, I can see that the routes of SettingsNavigationRouter are not visible (Screen5 and Screen6 is not visible)

````
    return (
      <SettingsNavigationRouter
        navigation={this.props.navigation}
      />
    )
````
and
````
    const { dispatch, state } = this.props.navigation

    return (

      <SettingsNavigationRouter
        navigation={addNavigationHelpers({
          dispatch: dispatch,
          state: state,
        })}
      />
    )
````
Just crashes
`undefined is not an object (evaluating 'nextState.routes.forEach')`

I've integrated this with redux and nested Stack2 inside Drawer previously with no problems - but when I pulled it out and added a layer of indirection for aesthetics, the _navigation_ prop did not seem to pass down correctly

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.12
| react-native     |  0.46.4
| node             | v8.2.1
| npm or yarn      | 5.3.0

**Comment by MyTotoro** [comment]
Solved here:

[https://github.com/ajostergaard/react-navigation/commit/e410a2f1d03329185721569e6509839b5953e9af](docs)

**Comment by lai32290** [comment]
I'm having the same issue
