### ISSUE TITLE
Nested StackNavigator inside DrawerNavigator. Drawer Item navigates to the screen on top of the stack. Please help

### ISSUE THREAD

**Issue by diz00** [react-community/react-navigation#2317]
Basically, I have a DrawerNavigator with different screens, one of them is a StackNavigator with several screens. My problem is that when I navigate from a Drawer menu to this Stack I need to always navigate to the bottom () screen in the stack, currently it navigates to the top screen in the stack.

Please help!

My code is rather simple:

```       
const HistoryNavigator = StackNavigator({
    history: { screen: HistoryScreen },
    edit: { screen: EditScreen }
        }, {
            headerMode: 'none'
     });

const MainNavigator = DrawerNavigator({
   Home: { screen: MainScreen },
   History: { screen: HistoryNavigator }
```

Please help!

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.11

**Comment by shawngustaw** [comment]
Have you tried setting an initial route on `HistoryNavigator` (https://reactnavigation.org/docs/navigators/stack#StackNavigatorConfig)? That will probably do it. What actions are you dispatching to navigate? You could also look into using `reset` to manually set the stack ordering like here: https://reactnavigation.org/docs/navigators/navigation-actions#How-to-use-the-index-parameter

**Comment by diz00** [comment]
Tried setting the initial route - doesn't change a thing. 
I'm not sure where to use ```reset```. My best guess would be to use it in ```onItemPress(route)``` method, but I would need a ```props.navigation``` to dispatch an action.

**Comment by diz00** [comment]
Tried setting an initial route - doesn't change a thing.
I'm not sure where to use ```reset``` to achieve required behavior.

**Comment by diz00** [comment]
#1384 fixed my problem
