### ISSUE TITLE
Header configuration disappears when the drawer opens

### ISSUE THREAD

**Issue by cazetto** [react-community/react-navigation#2318]
Hello, first of all thank's for this excellent lib.

I am having problem with header configuration when drawer is open. The title and logo disappear and the drawer opens under the header.

My code looks like this:

> RootNavigator.js

```
export default RootNavigator = StackNavigator({
  LaunchPage: {
    screen: LaunchPage
  },
  LoginPage: {
    screen: LoginPage
  },
  SignupPage: {
    screen: SignupPage
  },
  ForgotPage: {
    screen: ForgotPage
  },
  AppNavigator: {
    screen: AppNavigator
  }
});
```

> AppNavigator.js

```
export default AppNavigator = DrawerNavigator({
  DashboardPage: {
    screen: DashboardPage
  },
  ProfilePage: {
    screen: ProfilePage
  }
});
``` 

Should I implement this differently?
I have the following need:
I need three screens for authentication and one for startup.
After login, I need to have n screens that I will still define, and have drawer access to go back to login, logout.

Thank you all.

**Comment by cazetto** [comment]
Solution found:

I removed the RootNavigator header by adding headerMode: 'none'.

> RootNavigator.js
```
export default RootNavigator = StackNavigator({
  LaunchPage: {
    screen: LaunchPage
  },
  LoginPage: {
    screen: LoginPage
  },
  SignupPage: {
    screen: SignupPage
  },
  ForgotPage: {
    screen: ForgotPage
  },
  AppNavigator: {
    screen: AppNavigator
  }
}, {
  headerMode: 'none'
});
```

and add a StackNavigator for each screen in AppNavigator.

> AppNavigator.js
```
export default AppNavigator = DrawerNavigator({
  DashboardPage: {
    screen: StackNavigator({
      DashboardPage: {
        screen: DashboardPage
      }
    })
  },
  ProfilePage: {
    screen: StackNavigator({
      ProfilePage: {
        screen: ProfilePage
      }
    })
  }
});
```

If anyone knows any other solution I accept evaluate that.

Thanks!

**Comment by spencercarli** [comment]
Closing since solution was found 😄
