### ISSUE TITLE
how to add custom route data?

### ISSUE THREAD

**Issue by kikoololmdrxdd** [react-community/react-navigation#2320]
### Current Behavior
hello, im currently learning how to use create a custom navigation, in the doc it says we can add some custom route data in the navigation state. i tried putting { test: 'test'} in several places in my Custom navigation, but the logs only show me Index, routeName and key. 
### How can i put "test":"test" in route?

from MyCustomTabs.js 

    const NewsfeedStack = StackNavigator({
      Newsfeed: { screen: Newsfeed, },
      Explore: { screen: Explore, },
      Profile: { screen: Profile, },
      Map: { screen: Map, },
      Restaurant: { screen: Restaurant, },
      Dish: { screen: Dish, },
      Image: { screen: Image, },
    })

    const ExploreStack = StackNavigator({
      Explore: { screen: Explore, },
      Map: { screen: Map, },
      Search: { screen: Search, },
      Restaurant: { screen: Restaurant, },
      Dish: { screen: Dish, },
      Image: { screen: Image, },
      Profile: { screen: Profile, }, 
    },{
      navigationOptions :{
        title :'dododo'
      }
    })

    const BookmarkStack = StackNavigator({
     Bookmark: { screen: Bookmark,},
      Trophy: { screen: Trophy, },
      Restaurant: { screen: Restaurant, },
      Dish: { screen: Dish, },
      Image: { screen: Image, },
      Explore: { screen: Explore, },
      Map: { screen: Map, },
      Profile: { screen: Profile, },
    },{
      navigationOptions :{
        title :'dududu'
      }
    })

    const ProfileStack = StackNavigator({
      Profile: { screen: Profile, },
      Settings: { screen: Settings, },
      Restaurant: { screen: Restaurant, },
      Explore: { screen: Explore, },
      Map: { screen: Map, },
      Dish: { screen: Dish, },
      Image: { screen: Image, },
    },{
      navigationOptions :{
        title :'dadada'
      }
    })

    const CustomTabBar = ({ navigation }) => {
      const { routes } = navigation.state;
      console.log(routes[0].routes);
      return (
        <View style={styles.tabContainer}>
          {routes.map(route => (
            <TouchableOpacity
              onPress={() => navigation.navigate(route.routeName, {data:'test'})}
              style={styles.tab}
              key={route.key}
              test={'test'}
            >
              <Text>{route.routeName}</Text>
            </TouchableOpacity>
          ))}
        </View>
      );
    };

    const CustomTabView = ({ router, navigation }) => {
      const { routes, index } = navigation.state;
      console.log(' custom tab view' + routes);
      const ActiveScreen = router.getComponentForState(navigation.state);
      return (
        <View style={styles.container}>
        <ScrollView>
          <ActiveScreen style={{flex:1}}
            navigation={addNavigationHelpers({
              ...navigation,
              state: routes[index],
            })}
          />
          </ScrollView>
         <CustomTabBar navigation={navigation} />
        </View>
      );
    };

    const CustomTabRouter = TabRouter(
    {
      NewsfeedStack: { screen: NewsfeedStack, },
      ExploreStack: { screen: ExploreStack,  },
      BookmarkStack: { screen: BookmarkStack,  },
      ProfileStack: { screen: ProfileStack,  },
    },{
      initialRouteName: 'NewsfeedStack',
      backBehavior :'initialRoute'
      test:'test'
    })

    const CustomTabs = createNavigationContainer(
      createNavigator(CustomTabRouter)(CustomTabView)
    );
 

console.log(routes) shows me this

    Array [
    Object {
       "index": 0,
      "key": "NewsfeedStack",
    "routeName": "NewsfeedStack",
    "routes": Array [
      Object {
        "key": "Init-id-1501975093315-0",
        "routeName": "Newsfeed",
         },
      ],
    },
       Object {
       "index": 0,
       "key": "ExploreStack",
       "routeName": "ExploreStack",
      "routes": Array [
      Object {
        "key": "Init-id-1501975093315-1",
        "routeName": "Explore",
      },
    ],
      },
       Object {
       "index": 0,
       "key": "BookmarkStack",
       "routeName": "BookmarkStack",
       "routes": Array [
         Object {
          "key": "Init-id-1501975093315-2",
          "routeName": "Bookmark",
        },
      ],
      },
        Object {
       "index": 0,
       "key": "ProfileStack",
       "routeName": "ProfileStack",
       "routes": Array [
         Object {
           "key": "Init-id-1501975093315-3",
          "routeName": "Profile",
        },
      ],
    },
       ]

**Comment by lxcid** [comment]
I'm curious as well…

**Comment by alexkuc** [comment]
You need to use `navigationOptions` in your route config. For example,
```
const NewsfeedStack = StackNavigator({
  Newsfeed: { screen: Newsfeed, },
  navigationOptions: { customData: 'customString', }
})
```
You can then retrieve the value using [getScreenOptions](https://reactnavigation.org/docs/routers/api#getScreenOptions-navigation-screenProps)

**Comment by spencercarli** [comment]
@kikoololmdrxdd @lxcid have either of you tried the potential solution that @alexkuc supplied?

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
