### ISSUE TITLE
Create an external screen to compose item

### ISSUE THREAD

**Issue by swad1992** [react-community/react-navigation#2322]
The best way to explain this problem is image
![illustration](https://user-images.githubusercontent.com/29170415/29007317-9f6ec0fe-7b00-11e7-9d51-77f80740484b.png)

My current code is : 
```
import React from 'react';
import { StackNavigator, TabNavigator } from 'react-navigation';

import Screen1 from './Screen1';
import Screen2 from './Screen2';
import Screen3 from './Screen3';
import Screen4 from './Screen4';
import Screen5 from './Screen5';

const TwoAndFive = StackNavigator({
    Main: {
        screen: Screen2,
    },
    Screen5: {
        screen: Screen5,
    }
});

const Tabs = TabNavigator({
    Main: {
        screen: TwoAndFive,
    },
    Screen3: {
        screen: Screen3,
    },
    Screen4: {
        screen: Screen4,
    }
});

const Navigator = StackNavigator({
    Main: {
        screen: Screen1,
    },
    Screen 2: {
        screen: Screen2,
    }
});
```

(What I mean by external screen is the screen 5)

I have successed **blocking the user to return to screen 5 from the screen 2** using `NavigationActions` and ` this.props.navigation.dispatch()`
But the problem is that the user **can not return to screen 1 from screen 2**...

Thanks for your help

**Comment by spencercarli** [comment]
I'm not entirely following, but do neither `navigation.goBack()` or `navigation.goBack(null)` work?

If not then `Screen1` isn't in the current stack, in which case you'll need to navigate to it `navigation.navigate('Screen1')`

**Comment by swad1992** [comment]
Sorry I have forgot to close the issue, yes, I solved my problem using goBack()

thank you however
