### ISSUE TITLE
In nested navigator, BackHandler closes app instead of popping off the stack.

### ISSUE THREAD

**Issue by samdoj** [react-community/react-navigation#2324]
None of the other solutions related to this issue are working for me.  I wouldn't expect to have to implement hardware back button behaviour as this is a common use case.  I just use BackHandler to use navigation.goBack().  Here's the weird thing.  When I use my software back button as part of my custom header, everything works fine.  I know that my BackHandler event fires where BackButton, my component, lives, and it will perform its action and then immediately close the app from any screen.  I am nesting a StackNavigator in a TabNavigator.  I expect a hardware back press to  respond exactly the same way as my software button, code here: 

  componentDidMount() {
        BackHandler.addEventListener("hardwareBackPress", () => {
            console.log("Backbutton.js")
            this.props.nav.goBack() //My handler() function, which is triggered also calls this.
            return true //From my reading this should cease any other listeners from listening to the 
           event, yet the app closes here.  That's acceptable behaviour on the first screen, but not on any others.
        })
       }
### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.11
| react-native     |  0.44.0
| node             | 7.2.1
| npm or yarn      | 3.10.10

**Comment by michbil** [comment]
You need to check if your navigation on level 0 on each of nested navigators, and then decide either exit the app, or go back.This code works fine for me.
```
class App extends React.Component {
  componentDidMount() {
    BackHandler.addEventListener('hardwareBackPress', this.onBackPress.bind(this));
  }
  componentWillUnmount() {
    BackHandler.removeEventListener('hardwareBackPress', this.onBackPress.bind(this));
  }
  onBackPress () {
      
    const { dispatch, nav } = this.props;
    console.log("Back pressed", nav);
    const activeRoute = nav.routes[nav.index];
    if (activeRoute.index === 0) {
      return false;
    }
    dispatch(NavigationActions.back());
    return true;
  }
    render() {
        return (
            <AppNavigator navigation={addNavigationHelpers({
        dispatch: this.props.dispatch,
        state: this.props.nav,
      })} />
        );
    }
}
```

**Comment by DeFenceD** [comment]
You can see this, it is how to cover the react-navigation default action, prevent the pop by judge the action type('NavigationActions.BACK').
https://reactnavigation.org/docs/routers/#Blocking-Navigation-Actions

**Comment by spencercarli** [comment]
@samdoj do any of the responses here work for you? If so please close the issue. Thanks!

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!

**Comment by samdoj** [comment]
But this is still an issue.  Default behavior should allow nested navigators to correctly use BackHandler by default. If the nested navigator is at index 0 then the root navigator should go back if possible. On Aug 27, 2017 7:21 PM, Spencer Carli <notifications@github.com> wrote:Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!

**Comment by Noitidart** [comment]
Agreed with @samdoj - this is an issue. TabNavigator should automatically tie in with hardware back button on Android.

**Comment by Noitidart** [comment]
@michbil I don't understand the example. May you please show more code. My app is like this, so I don't have access to this.props.dispatch and this.props.nav I don't know where that is coming from please:

```
// @flow

import React, { Component } from 'react'
import { AppRegistry, View } from 'react-native'
import { Provider } from 'react-redux'

import store from './flows'

import MyTabNavigator from './MyTabNavigator'

import styles from './styles'

export default class App extends Component {
    render() {
        return (
            <Provider store={store}>
                    <MyTabNavigator />
            </Provider>
        )
    }
}

AppRegistry.registerComponent('myapp', () => App);
```

**Comment by michbil** [comment]
Code I posted is actually your MyTabNavigator class, (i updated name in the code snippet, so there is no confusion). this.props.nav and this.props.dispatch are provided by redux-connect middleware

**Comment by Noitidart** [comment]
Thanks @michbil very much for that fast reply! Is there a way you know without redux?

**Comment by michbil** [comment]
@Noitidart sorry, i didn't used react-navigation without redux

**Comment by Noitidart** [comment]
Darn. Thanks very much for a super fast reply again.

@spencercarli - May you please re-open as there isn't a solution for all here please?

**Comment by dabaooline** [comment]
@michbil  verygood solution,thank you.
