### ISSUE TITLE
Put a Switch Component in header,and Switch Component doesn't work

### ISSUE THREAD

**Issue by jzz567** [react-community/react-navigation#2325]
react-navigation:1.0.0-beta.11   
react-native:0.47.1 
node:8.1.1
npm:5.3.0

This is my code
```
class HomeScreen extends React.Component {
    static navigationOptions = ({navigation, screenProps}) => {
        const params = navigation.state.params || {title: <Text>none</Text>, headerRight: <Text>none</Text>};
        return {
            title: params.title,
            headerRight: params.headerRight,
        }
    };

    constructor(props) {
        super(props);
        this.state = {
            switch: false
        };
    }

    setNavigationParams() {
        let title = 'Welcome';
        let headerRight =
            <Switch value={this.state.switch} onValueChange={(value) => {
                this.setState({
                    switch: value
                });
            }}/>;

        this.props.navigation.setParams({
            title,
            headerRight,
        });
    }

    componentWillMount() {
        this.setNavigationParams()
    }

    render() {
        return <View>
            <Switch value={this.state.switch} onValueChange={(value) => {
                this.setState({
                    switch: value
                });
            }}/>
        </View>
    }
}
```
But i get this:
<img src="https://51php.org/files/1.gif"/>
Clicking the \<Switch\/> in header makes homepage's state and \<Switch\/> under the header change<br/><br/>
But \<Switch\/> in header will not be changed.
Maybe redux can solve this,but the code is just a simple example.<br/>
In the future, maybe there will be so many HomePages.They should control \<Switch\/>'s state by themself(use local state).<br/><br/>
How can I fix this?

**Comment by lpfunding** [comment]
Was this ever resolved?

**Comment by bijoycse** [comment]
Was this ever solved???

**Comment by whileMeAwakeMeCode** [comment]
I had the same issue and I wanted that Switch on that position. 
The only solution I ended up with sounds more like a dirty hack. No choice except playing with styling making my header background transparent and position absolute my Switch :

`
static navigationOptions = ({ navigation }) => { 
    
        return {
            headerStyle:{
                backgroundColor:'transparent', 
                // rebuild original header divider
                borderBottomWidth: 1, 
                borderBottomColor: 'silver',
                shadowColor: "#000",
                shadowOffset: { width: 0, height: 2 }, 
                shadowOpacity: 0.23, 
                shadowRadius: 2.62,
                elevation: 4,
                marginHorizontal: -4
            },
            headerTitle: 'Database',
            headerLeft: (
                <Icon name="storage" color="black" size={25} />
            ),
        };    
    };
render() {
        const { personalDb } = this.state;

        return(
            <View>
                <View style={{position: 'absolute', top:-40, right:0, zIndex:2}}>
                    <Switch // false by default
                        trackColor={Colors.lightRed}
                        onValueChange={this.toggleDatabase.bind(this)}  
                        value={personalDb}      
                    />
                </View>
                <Text> {personalDb ? 'Private' : 'Public'} Database </Text>

                 {/* ...  */}

            </View>
        )
    }
`
At least it allows use to get what we seek but it would be nice to have a real fix for that issue.

**Comment by bijoycse** [comment]
@whileMeAwakeMeCode 
*yes i can help you*

**Comment by whileMeAwakeMeCode** [comment]
@bijoycse have you found something ? sure share your fix with us

**Comment by bijoycse** [comment]
@whileMeAwakeMeCode  now i am busy hope tomorrow i will
