### ISSUE TITLE
this.props becomes undefined after calling from Navigation header

### ISSUE THREAD

**Issue by kevng9** [react-community/react-navigation#2326]
### Current Behavior
I'm trying to navigate to a different stacknavigator screen using a button in the header. Followed [docs](https://reactnavigation.org/docs/intro/headers) to pass function to header button but getting the following error

> Cannot read property 'navigation' of undefined

My code is as follows.

```
static navigationOptions = ({ navigation }) => {
       const {state, setParams} = navigation;
       return {
           headerRight: <Button onPress={() => state.params.callSettings()} ><Text>Go</Text></Button>
       };
   };

     componentDidMount() {
     //console.dir(this.props);
     this.props.navigation.setParams({ callSettings: this.goToSettings });
    }

    goToSettings(){
      //console.dir(this.props);
      this.props.navigation.navigate('SettingsBody');
    }
```
onPress seems to be calling goToSettings() but when I looked at this.props within the function it is undefined. this.props is set in componentDidMount.

TIA for any assistance

### Expected Behavior
Should navigate to SettingsBody screen

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  ^1.0.0-beta.11
| react-native     |  0.46.4
| node             | v6.10.3
| npm or yarn      | npm 5.0.3

**Comment by wkgalla** [comment]
You should call navigate directly.
`static navigationOptions = ({ navigation }) => {
       const {state, setParams} = navigation;
       return {
           headerRight: <Button onPress={() => navigation.navigate('SettingsBody')} ><Text>Go</Text></Button>
       };
   };`

**Comment by kevng9** [comment]
calling navigation.navigate directly worked. Thanks a lot for your help :)

**Comment by pherm** [comment]
I have some issue. I imported my stacknav (DrawerStack and DrawerNavigation) by appnav.js in one screen (in my case, screen1.js). In screen1.js i code ''const { navigation } = this.props;'' AND NEXT ''onPress={() => navigation.navigate(“Screen2”)}''.

anyway it return **undefined is not an object (evaluating 'navigation.navigate'**). Someone can help me?

HERE my stack (appnav.js):
const DrawerStack = DrawerNavigator(
  {
    screen1: { screen: screen1 },
    screen2: { screen: screen2 },
  },
  {
    // drawerWidth: deviceFull,
    gesturesEnabled: false,
    contentComponent: DrawerContainer
  }
);
const DrawerNavigation = StackNavigator(
  {
    DrawerStack: { screen: DrawerStack }
  },
