### ISSUE TITLE
Customization of DrawerNavigator

### ISSUE THREAD

**Issue by alfie-ab** [react-community/react-navigation#2327]
Hi, I'm sure this is likely a simple fix, it's just taken me way too long and I'm getting more and more frustrated. 

I have a DrawerNavigator nested within my main StackNavigator:

`const MainNavigator = StackNavigator({`

      login: { screen: Auth },
      signup: { screen: SignUp },
      home: { screen: Home },
      history: { screen: History },
      main: {
        screen: DrawerNavigator({
          supplier: { screen: SupplierNavigator },
          messaging: { screen: Messaging },
          profileDev: { screen: ProfileNavigator },
          settingsDev: { screen: SettingsNavigator}
        }, {
          drawerPosition: 'right',
          drawerWidth: 300,
          contentComponent: props => <Drawer {...props}/>,
        })
      },
      basket: { screen: Basket },
      sendOrder: { screen: SendOrder }
`})`

Whenever I click the 'DrawerOpen' button I am presented with this screen:

![screen shot 2017-08-07 at 13 59 01](https://user-images.githubusercontent.com/20194492/29027458-b46a5d4c-7b78-11e7-94fb-06fc9454a4ff.png)

I want to remove the "Order History" back button.

drawerLabel as a prop is not affecting anything, neither is drawerIcon. I've tried to putting them in the navigationOptions prop, in my customComponent component, in the custom header I am using in the DrawerNavigator screens, in the screens themselves in the navigationOptions, I've tried adjusting and manipulating it in contentOptions, plus many more variations that I can't remember right now.

I haven't included these as snippets/screenshots as there would be too many to list. I have a feeling the issue is to do with my nesting of the DrawerNavigator within a StackNavigator, but to be honest, at this point I'm not sure. 

Any help would be much appreciated :)

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
