### ISSUE TITLE
TouchableNativeFeedback ripple effect dosen't work

### ISSUE THREAD

**Issue by dlehdanakf** [react-community/react-navigation#2329]
Hi,
I'm trying to use StackNavigation library on my RN app.
I wrote code like
```
<TouchableNativeFeedback onPress={()=>{
    this.props.navigate('Page2');
}}>
...
</TouchableNativeFeedback>
```

So that, navigate page when user press the button with `<TouchableNativeFeedback />` ripple effect

### Current Behavior
But, unlike my intentions the page changed without any ripple effects.
Is there any way to maintain ripple effect?
Without navigate method, ripple effect works fine.

### Expected Behavior
Play  `<TouchableNativeFeedback />` ripple effect and route `<StackNavigator />`

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.11
| react-native     |  16.0.0-alpha.12
| node             |  8.2.1
| npm or yarn      | 4.6.1

**Comment by spencercarli** [comment]
A few thoughts on this one.

1. Make sure you're setting a view inside with TouchableNativeFeedback
2. Set background on TouchableNativeFeedback
3. It might just be some lag in the emulator you're using. I put together a [snack](https://snack.expo.io/Sykb8qLwb) which shows that the ripple works with navigation BUT there's a delay and the screen changes before the ripple takes effect. If you use the setTimeout line you can see it using ripple.

Hope that helps!

**Comment by dlehdanakf** [comment]
Thanks for reply.
But because of my poor english, I still don't understand very well... ㅠㅠ

Can you give me some sample code?

**Comment by dlehdanakf** [comment]
@spencercarli 
Thanks for your reply!!!
Ripple effect with setTimeout shows exactly what I want!

**Comment by spencercarli** [comment]
Sure thing! Just so you know - I don't think the setTimeout is a good solution, I just wanted to demonstrate that a bug didn't exist in React Navigation and that the page transition was taking place before the ripple was.

If this is sorted out could you close this issue?

**Comment by sospedra** [comment]
We ran into the same issue. Guess that the only solution is to not use ripple effect for those buttons that triggers a navigate action.
