### ISSUE TITLE
Window loading multiple times

### ISSUE THREAD

**Issue by ladislavbili** [react-community/react-navigation#2335]
Simple problem but I cant find solution. Is there a setting for this?

### Current Behavior
When you tap anything that triggers navigation (eg. onPress={() => this.props.navigation.navigate('Edit')}) more then once, the component displays multiple times. 

### Expected Behavior
While navigator is working (after one tap) it does not accept more input. So even if user would ran 10x onPress mentioned above, it would still ran just once.

### Your Environment
Android application ran on phone (Android version 4.4.2)

| software         | version
| ---------------- | -------
| react-navigation |  "^1.0.0-beta.11"
| react-native     |  "^0.46.1"

Thanks for any answers.

**Comment by spencercarli** [comment]
#271 is related to this
