### ISSUE TITLE
Recover from an invalid navigation state? (getScreenForRouteName() – There is no route defined for key XXX)

### ISSUE THREAD

**Issue by aforty** [react-community/react-navigation#2336]
So I have a fairly typical, nested navigation setup using `redux` and `redux-persist`.

During the course of development (and in production as well) it can happen that some nested routes change in which case the persisted navigation state may no longer be valid against the new route configuration. In such cases `getScreenForRouteName` will fail with "There is not route defined for the key XXX. Must be one of: YYY, ZZZ".

My question is how would I deal with this? How can I recover from this error, or how do I check ahead of time that the navigation state is still valid? (after `redux-persist` hydration but before suppling the router with the state)

| software             | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.11
| react-native       |  0.46.1

**Comment by spencercarli** [comment]
Just personal opinion here but it seems that it would be relatively uncommon that you would want to persist the navigation state between sessions, especially nested. Why is it that you want to do so?

Regardless though - a possible solution is, when using `redux-persist`, to [migrate](https://github.com/rt2zz/redux-persist#migrations) route names when they change. Or just avoid changing route names 😄

**Comment by aforty** [comment]
Yeah, maybe that's the right answer: don't persist it. And personal opinions was exactly what I was looking for. Keep 'em coming.

Still, a proper way to "recover" from such an error would be nice.

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
