### ISSUE TITLE
Stack Nav inside Tab nav initially renders with the stack on top already?

### ISSUE THREAD

**Issue by chrisgreg** [react-community/react-navigation#2338]
I've got a Tab Navigator for my main app navigation, I want one tab of my app (lets call it Page A) to let me open a modal tab. I've done it but for some reason whenever my app starts (it starts on that tab intentionally - Page A), I get a render of Page A with a back button in the header to Page A..

So the app starts, I've got Page A open and I have to close it to get back to the same page.

Has this happened before for anyone?

**Comment by spencercarli** [comment]
Can you share some code? Preferably a small example on [Snack](http://snack.expo.io)

**Comment by RocketPuppy** [comment]
I was seeing this as well. It seems to be related to connecting the application to a redux store. https://snack.expo.io/B10b-k5Pb

**Comment by RocketPuppy** [comment]
Playing with the example some more, changing this:
```javascript
// Redux config
const initialState = AppNavigator.router.getStateForAction(
  AppNavigator.router.getActionForPathAndParams('StackOne')
);
```

to this:

```javascript
// Redux config
const initialState = AppNavigator.router.getStateForAction(
  { type: 'VOID' }
);
```

seemed to work, although I'm not 100% sure why. The first method is also the recommended method in the documentation here: https://reactnavigation.org/docs/guides/redux.

**Comment by chrisgreg** [comment]
I'll give it a try and see if it works - thanks!

**Comment by kelset** [comment]
Pinging OP @chrisgreg  since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open; if I get no answer in the next 7 days I will close it.

**Comment by kelset** [comment]
Hi there @chrisgreg ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.
