### ISSUE TITLE
Nested TabNavigator inside StackNavigator with DrawerNavigator

### ISSUE THREAD

**Issue by rafael-trevisan** [react-community/react-navigation#2340]
Hi folks,

I'm trying to achieve a navigation layout but I am not quite sure if my layout/structure is right.

Here is what I **think** I should have:

```
==> RootStackNavigator (headerMode: 'none' and mode: 'modal')
====> LoginStackNavigator (I don't want headers on this stack)
====> Settings / Others modal (I do want header on this stack)
====> MainDrawerNavigator
======> DrawerScreen
======> MainTabNavigator
========> Tab1StackNavigator
==========> ScreenA1
==========> ScreenA2
========> Tab2StackNavigator
==========> ScreenB1
==========> ScreenB2
========> Tab3StackNavigator
==========> ScreenB1
==========> ScreenB2
```

Because RootStackNavigator has `headerMode = none`, I can't have header on Settings and other modals other than Login that I intentionally don't have modal.

If I change RootStackNavigator to `headerMode = screen` then I can easily hide the header on Login, I also have nice header on Setting and other modals BUT I start to have duplicates header for all other StackNavigator.

If I set Tab[1,2,3]StackNavigator to `headerMode = none` then I don't have duplicate headers anymore, I'll have only one header BUT I won't have any buttons (back) anymore.

I don't know how to nest/ident and setup my navigation structure to achieve what I desire.

Does someone have any advise?

Thanks in advance.

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
