### ISSUE TITLE
Header shows on .back() when set to null

### ISSUE THREAD

**Issue by RWOverdijk** [react-community/react-navigation#2345]
### Current Behavior
Tested this on iOS. When navigating back using `this.props.navigation.goBack` the header shows momentarily for the transition animation. I don't have this problem when dragging back. I've set the header to null using:

```js
static navigationOptions = {header: null}
```

### Expected Behavior
No header at all.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.12
| react-native     |  0.47.1
| node             | 7 & 8
| npm or yarn      | yarn

**Comment by spencercarli** [comment]
Could you put together a demo on [Snack](https://snack.expo.io)?

**Comment by AlanFoster** [comment]
@RWOverdijk I'm unable to recreate your issue; An example would be appreciated :)

**Comment by RWOverdijk** [comment]
Alright. I've dropped the headerless approach. If I ever get to it again I'll report back.
