### ISSUE TITLE
React Navigation detect tab bar press and re-rendering screen help

### ISSUE THREAD

**Issue by shlomi84** [react-community/react-navigation#2347]
I am in need of a solution to a problem I am having with react navigation. I will start off by listing what I want to get done and if it is possible with react navigation:

1. currently, I have 2 tabs on my app screen. One tab displays weather information to the user, and the second tab controls what the user wants to see in his/her weather forecast in the first tab. So the second tab is essentially a settings screen while the first screen is where the GUI takes place. Now, In my second tab, once the user changes his/her options, I want to make sure they saved their preferences by clicking a button I have on the screen. Now, here is where my issue with react navigation comes into place, I want the second tab to work in such a way that when the user clicks back on the first tab, an Alert will pop up asking them, "Are you sure you want to leave this page without saving? Yes/no" If they click no, I want them to stay in this tab, if they click yes, I want them to go back to the first tab.

Here is my code:

```
export const Tabs = TabNavigator({
  WeatherDisplay: {
    screen: WeatherDisplay,
    navigationOptions: {
        header: null,
        tabBarLabel: 'Weather',
        tabBarIcon: ({ tintColor }) => <Icon name="weather" size={24} color={tintColor} />
    },
},

  WeatherOptions: {
    screen: WeatherOptions,
    navigationOptions: {
      header: null,
        tabBarLabel: 'Weather Options',
        tabBarIcon: ({ tintColor }) => <Icon2 name="settings" size={23} color={tintColor} />
    },
  },
},
{
  animationEnabled:true,
  swipeEnabled:false,
  gesturesEnabled:false,
  tabBarOptions: {
    inactiveTintColor: 'gray',
    showIcon:true,
    activeTintColor:'#D088EB',
    showLabel: false,
    indicatorStyle: {
      borderBottomColor: '#D088EB',
      borderBottomWidth: 2,
    },
    style: {
    backgroundColor: '#F8F8F8',
  },
  onTabPress: (tab) => {
    if (tab.index == 0) {
	    	Alert.alert("Save","Dont forget to save your weather!");
      }
	    }

},
}
);
```

Thus far, I have done extensive research and reading online and have been banging my head against the react-navigation doc's but I can't seem to find a function related to onTabPress. In my code above, the onTabPress works only and android and not on iOS, meaning the onTabPress() function gets called when a user changes tabs, but this still doesn't address my problem because I only want the tab to change if a user clicks 'yes' when an alert popups. Currently, the code just sends an Alert but still automatically changes the screen, and it only works on android.

I appreciate any help! thank you for reading this!

**Comment by spencercarli** [comment]
There's not currently a way that's built in to do this in React Navigation but, by overriding the tabBarComponent, you can customize it in a variety of ways.

#1335 has an example of how you could do it - I actually implemented something similar on a project this morning! 😄

**Comment by shlomi84** [comment]
Hey @spencercarli, sorry I am new to react native and GitHub and all of these things. In that #1335 link do I just go to the "commits" section and copy the changes he made to specific files then I can have the onTabPress method and then make it so that I can add an alert with option yes/no and if they click yes it will change screens, if they click no then it will stay in the same screen?

**Comment by spencercarli** [comment]
@shlomi84 you can use that [code](https://github.com/cribspot/react-navigation/blob/187913749f61f27e109af841b5558235032652b7/src/views/TabView/TabBarBottom.js#L159) as a reference point for building your own tabbar. Try to understand what the code is doing vs. just copying it.

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
