### ISSUE TITLE
Why is this library the official RN navigation solution?

### ISSUE THREAD

**Issue by raarts** [react-community/react-navigation#2349]
I usually don't rant, but I need to get his off my chest. 
I have been wrestling with this library since I started using it. Problems I encounter: 

- The documentation is leaving a lot to be desired. It fails to explain basic things: the difference between navigators and routers, how to put together various navigators/routers to get the behaviour you want, how to do modals properly. Most importantly, it fails to present a mental model for it all.
- The API is confusing, and inconsistent: some configuration can only be defined statically, entire navigators can be set modal, but not individual screens (isn't that where 'modal' starts?).  
- There are so many open issues for something as simple as a routing solution.

To me it feels like there should be a qualified engineer in the lead with enough time on his/her hands, and there currently isn't any. 

I appreciate open source and being bleeding edge, but why is this the official RN navigation then?
Also, why are there so many routing solutions? It seems like such a small and basic part of the ecosystem.

**Comment by kelset** [comment]
> "It seems like such a small and basic part of the ecosystem."

Navigation is always a **complex** part of an ecosystem; probably you only need to navigate between two tabs, but more complex scenarios require complex solutions.

**Comment by spencercarli** [comment]
> The documentation is leaving a lot to be desired. It fails to explain basic things: the difference between navigators and routers, how to put together various navigators/routers to get the behaviour you want, how to do modals properly. Most importantly, it fails to present a mental model for it all.

Looking to improve it soon! Getting issues under control first 

> There are so many open issues for something as simple as a routing solution.

Working on this now!

> To me it feels like there should be a qualified engineer in the lead with enough time on his/her hands, and there currently isn't any.

The folks who have put tremendous time, effort, and energy into this package are also the ones who lead so much of the React/React Native ecosystem and they've only got so much time. My suggestion would be to help go through issues answer questions, ping me if you think an issue should be closed, and help to bring the repo as a whole to a more manageable state so others aren't intimidated to help out.

_Note: I just joined to help get issues under control so I can't speak for any of the core maintainers but, again, they're folks who have contributed so much and only have so much time on their hands. We can all do a bit to help out._

**Comment by spencercarli** [comment]
I'm going to close this issue (in my effort to clean up excess issues 😉 ) but I encourage people to continue conversing on the subject! 😄

**Comment by raarts** [comment]
Thanks for joining Spencer! I appreciate your work on spreading the word on how to get started with RN, and I really got started, but felt that React Navigation was what was holding me back.

Looking forward to what the future will bring.
