### ISSUE TITLE
set initial/default screen params

### ISSUE THREAD

**Issue by thurt** [react-community/react-navigation#235]
I haven't figured out a way to do this yet.

Example use case: 
```javascript
import { TabNavigator, TabView } from 'react-navigation';
import Ionicons from 'react-native-vector-icons/Ionicons';
import Search from './Search';

const MyTabNavigator = TabNavigator({
  Search: { 
    screen: Search,
    params: {
      iconName: 'ios-search-outline'
    }
}, {
  navigationOptions: {
    tabBar: ({ state }) => ({
      icon: ({ tintColor, focused }) => (<Ionicons name={state.params.iconName} color={tintColor} />)
    })
  },
  tabBarComponent: TabView.TabBarBottom
});
```
Explanation: if I am using default `navigationOptions` (0c99035) to create a generic handler for `tabBar.icon`, I would like to provide some initial/default screen params to the generic handler. in this simple example, i would define `iconName` as an initial screen param so that the `tabBar.icon` handler can get the correct icon to render.

Thoughts? or alternatives?

**Comment by ericvicenti** [comment]
You could do this:

```js
import { TabNavigator, TabView } from 'react-navigation';
import Ionicons from 'react-native-vector-icons/Ionicons';
import Search from './Search';

function routeNameToIcon(routeName) {
  switch (routeName) {
    case 'Search':  return 'ios-search-outline';
    default: return 'default-icon';
  }
}

const MyTabNavigator = TabNavigator({
  Search: { 
    screen: Search,
}, {
  navigationOptions: {
    tabBar: ({ state }) => ({
      icon: ({ tintColor, focused }) => (<Ionicons name={routeNameToIcon(state.routeName)} color={tintColor} />)
    })
  },
  tabBarComponent: TabView.TabBarBottom
});
```

**Comment by ericvicenti** [comment]
Closing for now but feel free to keep discussion going or open more specific issues

**Comment by thurt** [comment]
hi @ericvicenti, thanks for chiming in. yep that is exactly what my current solution is. 

i would be interested in hearing more opinions about whether this is a useful feature to develop.

currently, the only way I am aware of to pass params is via the navigation prop which is injected into components, ie. `this.props.navigation.navigate('ScreenName', { myProp: 'value'});`. this allows `myProp` to be passed from one component to another component.

however, my use case presents a situation where no navigation has taken place; the `tabBar.icon` is utilized immediately on first render. in these cases, it would be nice to be able to define initial screen params.

**Comment by joshuapinter** [comment]
@thurt Did you figure out a way to define the initial/default screen params? I'm trying to pass an initial param from `launchOptions` to the initial scene but I'm not sure how to do that. 

I've created a new issue to address this directly #634 as well.

Thanks!
