### ISSUE TITLE
Add documentation for key parameter of RESET action

### ISSUE THREAD

**Issue by janzal** [react-community/react-navigation#2350]
I found this (reseting to the topmost navigator) and it is really useful sometimes, but I am not sure if I understand it correctly Would it be possible to add some kind of documentation for parameter key of RESET action?

https://github.com/react-community/react-navigation/pull/789

**Comment by kelset** [comment]
I think you are looking for this: https://github.com/react-community/react-navigation/blob/cc22138b1927a006b6e2a29c2b3dd38da736a164/docs/guides/Navigation-Actions.md#reset

**Comment by janzal** [comment]
Thanks, I missed this one. I checked only docs at https://reactnavigation.org/docs/navigators/navigation-actions#Reset
