### ISSUE TITLE
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in 

### ISSUE THREAD

**Issue by MMRATXS** [react-community/react-navigation#2352]
### Current Behavior
I am working with react-navigation and it has been working fine for me before,
but now when I have to include it in an app, it gives me this error,

`Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in `

the project works fine without the navigation feature,

I tried changing this line
`import {StackNavigator} from 'react-navigation';`
to
`import StackNavigator from 'react-navigation';`

![capture](https://user-images.githubusercontent.com/10835492/29178776-ff0a865c-7e0b-11e7-9706-d441d8454ac0.PNG)

but then navigation doesn't work, giving the error

`(0 , _reactNavigation2.default) is not a function`

Any help is highly appreciated

Thanks

| software         | version
|---------------|-------  
| react-navigation |  ^1.0.0-beta.11
| react-native     |  0.46.4
| node             | 8.1.2
| npm or yarn      | npm 5.0.4

**Comment by spencercarli** [comment]
I think the issue you're running into is from index.android.js/index.ios.js. You need to make sure you're using `import { SimpleApp } from 'react-navigation';` and then registering the component.

**Comment by MMRATXS** [comment]
That worked!
Can't believe I spent a whole day.

I just added the curly braces and that helped.
