### ISSUE TITLE
TouchableHighlight as a stack navigator doesn't work and throws this error

### ISSUE THREAD

**Issue by Hayko1994** [react-community/react-navigation#2353]
<img width="346" alt="newerror" src="https://user-images.githubusercontent.com/22639899/29178474-f56331fe-7df1-11e7-8db7-5764afbdd0e8.png">

TouchableHighlight as a stack navigator doesn't work and throws this error. It's needed to navigate another page when user clicks on the CardItem. Here is my code.

**CardItem**

```
<TouchableHighlight onPress={() => this.props.navigation.navigate("Post")}>
 <CardItem>
              <Left>
                <Thumbnail source={{uri: 'Image URL'}} />
                <Body>
                  <Text>NativeBase</Text>
                  <Text note>GeekyAnts</Text>
                </Body>
              </Left>
            </CardItem>
            <CardItem cardBody
            onPress={() => this.props.navigation.navigate('post')}
>
              <Image source={{uri: 'Image URL'}} style={{height: 200, width: null, flex: 1}}/>
            </CardItem>
<TouchableHighlight>
```

**app.js**

   import React from 'react';
    import {StyleSheet, Text, View,ScrollView,Image,Icon } from 'react-native';
    import {
      Asset,
      AppLoading,
    } from 'expo';
    
    
    import WelcomeScreen from './screens/WelcomeScreen';
    import SigninScreen from './screens/SigninScreen';
    import SignupScreen from './screens/SignupScreen';
    import HomeScreen from './screens/HomeScreen';
    import ProfileScreen from './screens/ProfileScreen';
    import SettingsScreen from './screens/SettingsScreen';
    import ContactScreen from './screens/ContactScreen';
    import ForgetpassScreen from './screens/ForgetpassScreen';
    import { TabNavigator, DrawerNavigator, StackNavigator,contentOptions} from 'react-navigation';
    import DrawerContent from './components/DrawerContent'
    
    
    export default class App extends React.Component {
    
    
    
    
    render() {
    
    
    const MainNavigator = TabNavigator({
    
      Welcome: { screen: WelcomeScreen },
    
      Signin: { screen: SigninScreen },
    
      Signup: { screen: SignupScreen },
    
      main: {
           screen: DrawerNavigator({
             Home: { screen: HomeScreen },
    
             Profile : { screen: ProfileScreen },
             Settings : {screen: SettingsScreen},
             Contact: {screen:ContactScreen},
           },
           {
       drawerPosition: 'Left',
    
               contentComponent: props => <ScrollView>< DrawerContent {...props} /></ScrollView>,
               contentOptions: {
            inactiveTintColor: '#1414fc',
            activeBackgroundColor: '#383838',
            activeTintColor: '#1414fc',
    
           }
    
          }
    
        ),
          links : {
                 screen: StackNavigator({
                   Forgetpass:{screen: ForgetpassScreen},
                   Post: { screen: PostScreen },
    
                 },
               )
             }
         }
       },
    
       );
    
    
    return (
      <MainNavigator />
    
    
    
    );
    
    
    }
    }

**Comment by spencercarli** [comment]
The `navigation` prop is only going to be available to components registered with a navigator. If you want to access it via a child component you'll need to either 

1) Pass the `navigation` prop down manually
2) Use [`withNavigation`](https://github.com/react-community/react-navigation/blob/master/docs/api/withNavigation.md) on the child component to grab navigation from context

**Comment by sa63** [comment]
Sorry but I am a bit confused. Documentation is a bit unclear. Will it look like to this?
`TouchableHighlight onPress={() => this.props.withNavigation.navigate("Post")}>`

it shows the same error. As I need to add this code for navigating through card item I don't find how to use it.

**Comment by Hayko1994** [comment]
Sorry but I am a bit confused. Documentation is a bit unclear. Will it look like to this?
TouchableHighlight onPress={() => this.props.withNavigation.navigate("Post")}>

it shows the same error. As I need to add this code for navigating through card item I don't find how to use it.

**Comment by spencercarli** [comment]
No, sorry you would use it like this

```javascript
import { withNavigation } from 'react-navigation';
class CardItem extends React.Component {
  render() { ... }
}

export default withNavigation(cardItem);
```

**Comment by Hayko1994** [comment]
The main problem with this approach is that component is the Posts while inside are 4 cards which include those CardItems so CardItem is not a component that is why it becomes so challenging to use this approach.
