### ISSUE TITLE
re-render screen with onpress state change

### ISSUE THREAD

**Issue by sawwy** [react-community/react-navigation#2356]
### Current Behavior
I am sending a callback from one of my screens to update the root component state which flows to child components and screens via props. onPress event is fired correctly and state is updated in root component with setState but to see the changes, I need navigate back to previous screen and then navigate again to the screen where onPress was fired to see the changes. My root component screen index = 0 and my button screen index = 2 so I navigate through a screen in the middle.

### Expected Behavior
I would like to have my current screen re-render automatically when I update the parent state instead of having to navigate back and forth. As I press the button, I would like to see my UI reflect the change in the parent state immediately without changing screens. 

Currently, I am not using redux/mobx as to my understanding, I should be able to achieve the desired result without them. I am just passing function as a prop to the child elements through which it eventually gets fired from by button screen, the callback chain results in successful state change but the immediate re-render does not fire off from root back to my button screen.

Thanks for your time, all help is really appreciated!

### Your Environment
| software         | version
| ---------------- | -------
| react-navigation | "git+https://github.com/react-community/react-navigation.git"
| react-native     | "^0.46.4
| node             | v6.9.1
| npm or yarn      | npm 3.10.8

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
