### ISSUE TITLE
[React-Native] Why react-nativigation example use Stateless function?

### ISSUE THREAD

**Issue by thoth-nexlesoft** [react-community/react-navigation#2357]
This is not bug !!!

I have a question. Why react-navigation example use Stateless function? 
Because I am coding react-native. I very difficult handle life cycle of component.
I usually use Statefull function when I create a component.

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
