### ISSUE TITLE
Hide tabbar label completely (labelStyle not working?)

### ISSUE THREAD

**Issue by flavordaaave** [react-community/react-navigation#236]
Is there an easy way to just hide the Tabbar Labels completely?
I tried to apply some labelStyle (width height: 0) but labelStyle does not seem to work at all...

```
const Tabs = TabNavigator({
  Home: {
    screen: HomeScreen,
    path: 'home',
    navigationOptions: {
      tabBar: {
        label: 'TEST',
      },
    },
  },
...
}, {
  swipeEnabled: false,
  animationEnabled: true,
  backBehavior: 'none',
  tabBarOptions: {
    labelStyle:{ backgroundColor: 'yellow', color: 'red', fontSize: 30, }
  },
})
```

The labelStyle in the above code does NOT change anything.

**Comment by kylpo** [comment]
https://github.com/react-community/react-navigation/pull/234 might be what you're looking for. Just merged in.

**Comment by manavbhikadiya** [comment]
try this,

tabBarOptions={{
showLabel : false
}}
