### ISSUE TITLE
Adding common element to all screens?

### ISSUE THREAD

**Issue by burakadam** [react-community/react-navigation#2360]
I'm very new to React-Native so I definitely may be missing something. All i want to do is adding common element to all screens. I created "TopBar.js" and add to all screens but navigation button which is in common element does not work.

**index.android.js**

import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View,
  ScrollView,
  Image,
   } from 'react-native';
import Icon from "react-native-vector-icons/MaterialCommunityIcons";
import { DrawerNavigator } from "react-navigation";
import Home from "./views/Home";
import Products from "./views/Products";
import About from "./views/About";
import Choies from "./views/Choies";
import Tuna from "./views/Tuna";

const DrawerNav = DrawerNavigator({
  Home: { screen: Home,},
  Products: { screen: Products,},
  About: { screen: About,},
  Choies:{screen:Choies},
  Tuna:{screen:Tuna}
},
 {
      drawerPosition : "right",
      contentComponent: props => <DrawerContent {...props} />,
  }
  
);

class DrawerContent extends Component {
render() {
return (
  <ScrollView style={styles.container}>
    <View style={{ flex: 1 }}>
     <TouchableOpacity  onPress={() => this.props.navigation.navigate('Products')}>
          <Text style={styles.btnTxt}>Ürünler</Text>
      </TouchableOpacity>
      <View style={styles.seperator}></View>
      <TouchableOpacity onPress={() => this.props.navigation.navigate('Choies')}>
          <Text style={styles.btnTxt}>Tonla Seçenek Var</Text>
      </TouchableOpacity>
      <View style={styles.seperator}></View>
      <TouchableOpacity onPress={() => this.props.navigation.navigate('Tuna')}>
          <Text style={styles.btnTxt}>Balığını Sorgula</Text>
      </TouchableOpacity>
      <View style={styles.seperator}></View>
      <TouchableOpacity onPress={() => this.props.navigation.navigate('Tuna')}>
          <Text style={styles.btnTxt}>Balık & Sağlık</Text>
      </TouchableOpacity>
      <View style={styles.seperator}></View>
      <TouchableOpacity onPress={() => this.props.navigation.navigate('Tuna')}>
          <Text style={styles.btnTxt}>Hakkımızda</Text>
      </TouchableOpacity>
    </View>
  </ScrollView>
);}}

const styles = StyleSheet.create({
 container:{
  backgroundColor:"#060a16",
  padding:10,
 },
 btnTxt:{
    color:"white",
     fontSize: 20,
     padding:15,
 },
 seperator:{
    height:2,
    backgroundColor:"black"
 },
 topBarContainer:{
    height: 55,
    backgroundColor:"#0c142c",
      flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',

  },
  topBarLogo:{
    height:44 ,
    width:140
  }
});

and **TopBar.js**

import React, { Component } from 'react';
import { AppRegistry,StyleSheet, Text ,View,Image,TouchableOpacity} from 'react-native';
import Icon from "react-native-vector-icons/MaterialCommunityIcons";

export default class TopBar extends Component {
        render() {
          return (
            <View style={styles.topBarContainer}>
               <Icon name="circle" size={21} color="#0c142c" style={{ padding: 10 }} />
                <Image source={require('../img/icon.png')} style={styles.topBarLogo}/>
                <TouchableOpacity  onPress={() => this.props.navigation.navigate('Home')}>
                    <Icon name="menu" size={21} color="#d3d3d3" style={{ padding: 10 }} />
                </TouchableOpacity>
             </View>
        );
    }
}

module.extends = TopBar

const styles=StyleSheet.create({

	topBarContainer:{
		height: 55,
		backgroundColor:"#0c142c",
	    flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',

	},
	topBarLogo:{
		height:44 ,
		width:140
	}
})

and **Home.js**

import React, { Component } from 'react';
import { AppRegistry, Text ,View,ScrollView,StyleSheet,Image,TouchableOpacity,Button} from 'react-native';
import TopBar from './TopBar'; 
import Icon from "react-native-vector-icons/MaterialCommunityIcons";

export default class Home extends Component{
    render() {
    return (
      <View>
        <TopBar />
        <Text>HOme</Text>
        </View>
    );
  }
}

const styles = StyleSheet.create({

 
 topBarContainer:{
    height: 55,
    backgroundColor:"#0c142c",
      flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',

  },
  topBarLogo:{
    height:44 ,
    width:140
  }
});

AppRegistry.registerComponent('SampleProject', () => Home);

Can someone help?

**Comment by AlanFoster** [comment]
@burakadam Could you please correctly format your question? :+1:

In particular check out https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
