### ISSUE TITLE
i18n

### ISSUE THREAD

**Issue by baijunjie** [react-community/react-navigation#2361]
How to achieve dynamic language switching?

```js
class ListScreen extends Component {
    static navigationOptions = (props) => {
        return {
            tabBarLabel: () => i18n.t('name'),
            tabBarIcon: function ({tintColor}) {
                return (
                    <Image source={image}
                           style={[styles.icon, { tintColor: tintColor }]}/>
                )
            }
        };
    }
    ...
}

...

TabNavigator({
    List: {
        screen: ListScreen,
    },
    User: {
        screen: UserScreen,
    },
})
```
When I switch the language to refresh component `tabBarLabel`, even if I through event mechanism components perform `this.forceUpdate()`, still can't update. It was not until after I switch navigation `tabBarLabel` will be updated.

Is there any way to without switching navigation update component `tabBarLabel`?

**Comment by soleilgl** [comment]
static navigationOptions = {
    tabBarLabel: I18n.t('name'),
  };
this works for me.

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!

**Comment by s349856186** [comment]
@baijunjie do you solved it?
