### ISSUE TITLE
How to generate tab from API

### ISSUE THREAD

**Issue by trieuvi** [react-community/react-navigation#2362]
### Current Behavior

I'm loading data from API and generate tab like this:

| key         | product types
| ---------------- | -------
| 1 |  shirt
| 2 | shoes 
| 3 | hat 
| ...  | ...

product types are loaded from database, so they are dynamic, i can't use this code:
```
const ShopTab = TabNavigator(
    {
        shirt: { screen: shirtScreen },
        shoes: { screen: shoesScreen },
        hat: { screen: hatScreen },
        ...
    }, 
    {
        tabBarOptions: {...},
        ...
    }, 
);
```

### Expected Behavior

I want to generate dynamic tabs: t-shirt | shoes | hat | ....
Can anyone help? I'm very newbie with react native, so please give me detail example, thanks.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.11
| react-native     |  0.43.4
| node             | v6.9.1
| yarn      | v0.27.5

**Comment by spencercarli** [comment]
You'll want to wrap your navigator in a function, pass the config to that function, and then return & use the navigator. I'm not saying it's a great solution, but it should work. A big issue with this solution is if the navigator is re-rendered it will lose navigation state

```javascript
const createTabNav = (screenConfig) => {
  return TabNavigator(screenConfig, { tabBarOptions: { ... } });
}
```

then to use it you would

```javascript
render() {
  return createTabNav({
    shirts: { screen: shirtScreen },
    ...
  });
}
```

**Comment by AlanFoster** [comment]
@trieuvi You may also want to consider a different UX for your application; Perhaps you really want a FlatList to allow you to scroll through all of your available products from a data base - and then use a stack navigator to help you explore all of the available product types.

This kind of UX is called a master-detail interface

**Comment by gunn** [comment]
@spencercarli I'm attempting this and came up with essentially the approach you suggested. The losing of navigation state kills it though.

Is there a better solution or a good way to fake the effect?

**Comment by trieuvi** [comment]
Thank you @spencercarli, @AlanFoster. My final solution is:
```
const arr = ['shirt', 'shoes', 'hat',...]; 
const tab = [];

for (let i = 0; i < arr.length; i++) {
  tab[arr[i]] = { screen: AppScreen };
}

const App = TabNavigator(
  tab,
  {
    tabBarOptions: { ... }
  }
);
```

**Comment by ociata** [comment]
@spencercarli How it is possible to return TabNavigator/StackNavigator from inside render() function? It always fails with `A valid React element(or null) must be returned`.

**Comment by Chris-Petty** [comment]
@ociata it should be pretty straight forward looking at docs here https://reactnavigation.org/docs/intro/nesting#Nesting-a-Navigator-in-a-Component

**Comment by karsens** [comment]
I tried the above but it didn't work. This is my solution to show/hide tabBar items dynamically.

Import Dimensions and get screen.width, then decide the amount of items in the tabBar:
`import { Dimensions } from "react-native";

var screen = Dimensions.get("window");`

`    navigationOptions: ({ screenProps, navigation }) => ({
        tabBarButtonComponent: ({ children }) => {
        const { me } = screenProps.data;
        const { routeName } = navigation.state;

        const co = me && me.community;
        

        // the vars below are booleans
        const board1Disabled = co && co.board1disabled;
        const board2Disabled = co && co.board2disabled;
        const eventsDisabled = co && co.disableEvents;
        const chatDisabled =
          co &&
          co.channelsOff &&
          !co.whatsappGroup1 &&
          !co.whatsappGroup2 &&
          !co.whatsappGroup3;

         // +{boolean} returns 0 for false and 1 for true
        const tabsAmount =
          6 -
          +board1Disabled -
          +board2Disabled -
          +eventsDisabled -
          +chatDisabled;

        const item = (
          <TouchableWithoutFeedback
            onPress={() => navigation.navigate(routeName)}
          >
            <View
              style={{
                width: screen.width / tabsAmount,
                height: "100%",
                justifyContent: "center",
                alignItems: "center"
              }}
            >
              {children}
            </View>
          </TouchableWithoutFeedback>
        );

        return (routeName === "chatstack" && chatDisabled) ||
          (routeName === "events" && eventsDisabled) ||
          (routeName === "board1" && board1Disabled) ||
          (routeName === "board2" && board2Disabled)
          ? null
          : item;
      },

      tabBarIcon: ({ focused, tintColor }) => {
        const { routeName } = navigation.state;

        let iconName = routeName === "userstack" ? "users" : null;
        iconName = routeName === "chatstack" ? "comments" : iconName;
        iconName = routeName === "board1" ? "book" : iconName;
        iconName = routeName === "board2" ? "book" : iconName;
        iconName = routeName === "events" ? "calendar" : iconName;
        iconName = routeName === "morescreen" ? "bars" : iconName;

        const focusedColor = "maroon";
        return (
          <FontAwesome
            name={iconName}
            size={20}
            style={{ color: focused ? focusedColor : tintColor }}
          />
        );
      }

})`

Enjoy!

**Comment by devpascoe** [comment]
Anyone got this working with React Navigation 3?

**Comment by devpascoe** [comment]
I ended up writing something like this to only load the component once the tab configuration was fetched from an api and saved into a global variable and used state to only show the component once ready.
```
  fetchTabs = async () => {
    const fetchUrl = `urltoapi/menu`
    const response = await fetch(fetchUrl)
    global.tabs = await response.json()
    AppScreen = require('./screens/AppScreen').default
    this.setState({ loadedTabs: true })
  }
```
...and in AppScreen its default returns the createBottomTabNavigator with the tabs object being the result of the following tabs() function
```
const tabs = () => {
  const tabItems = {}
  global.tabs.forEach(tab => {
    if (tab.screen == 'Feed') {
      tabItems['Feed'] = FeedStack
    } else if (tab.screen == 'Chat') {
      tabItems['Chat'] = ChatStack
    } else if (tab.screen == 'Profile') {
      tabItems['Profile'] = MyProfileStack
    } else if (tab.screen == 'Contact') {
      tabItems['Contact'] = ContactScreen
    }
  })
  return tabItems
}
```
So i'm basically doing whatever i can to delay loading and then showing the createBottomTabNavigator until i have prepared the tabs object for it to use since it needs that result returned synchronously.
