### ISSUE TITLE
Using Modal is repeating animation in reverse

### ISSUE THREAD

**Issue by nucleons** [react-community/react-navigation#2363]
Hi

I have integrated the example app in the existing Android app. When ever I navigate to ShowModal screen and come back the animation of slide down again repeats. Any idea what is happening?

But when I run the example app as an standalone app, it's working as expected.

**Comment by spencercarli** [comment]
Could you share some code? A small demo of the issue on [Snack](https://snack.expo.io) would be event better! 😄

**Comment by nucleons** [comment]
@spencercarli Thank you for the reply. The problem was in my project, since I was using "slide_up.xml and slide_down.xml" in my anim folder and this was overriding the "react-native's slide_up.xml and slide_down.xml" files. And this was creating problem. I renamed the files and it worked like a charm.

**Comment by spencercarli** [comment]
Glad it's sorted out!
