### ISSUE TITLE
The next page also has this first page content

### ISSUE THREAD

**Issue by dongchuanlei** [react-community/react-navigation#2364]
this.props.navigation.navigate("SecondView",{title:"第二页"});
From the first page of the map to the next page, the second page still has a map of the first page

![screenshot_2017-08-11-16-25-22-922_com amapdemo](https://user-images.githubusercontent.com/19383409/29209893-73bead18-7ec3-11e7-932b-538ceb3549e3.png)
![screenshot_2017-08-11-16-25-41-333_com amapdemo](https://user-images.githubusercontent.com/19383409/29209894-74a42a82-7ec3-11e7-85eb-c7ac0c1d6fcd.png)

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  
| react-native     |  
| node             | 
| npm or yarn      |

**Comment by dongchuanlei** [comment]
My Environment
"react-navigation": "^1.0.0-beta.11",
"react-native" : "^0.47.1"

**Comment by dongchuanlei** [comment]
sorry

**Comment by dongchuanlei** [comment]
Sorry, My Environment
"react-navigation": "^1.0.0-beta.11",
"react-native" : "^0.47.1"
node : v7.8.0
npm : v4.2.0

**Comment by spencercarli** [comment]
Could you share some of your code? If you can make a small demo of this issue on [Snack](https://snack.expo.io) that would be even better!

**Comment by dongchuanlei** [comment]
If necessary,  I can send the project to you.
Only Android has this problem

[FirstView.js.zip](https://github.com/react-community/react-navigation/files/1219312/FirstView.js.zip)
[SecondView.js.zip](https://github.com/react-community/react-navigation/files/1219313/SecondView.js.zip)

**Comment by spencercarli** [comment]
I wonder if the issues is related to how [react-native-amap3d](https://github.com/qiuxiang/react-native-amap3d) and react-navigation interact with each other.

**Comment by dongchuanlei** [comment]
I've tried
<img width="638" alt="2017-08-15 11 43 44" src="https://user-images.githubusercontent.com/19383409/29301519-5029e5ae-81af-11e7-9c88-0e65f3786d12.png">
The problem is gone.

**Comment by spencercarli** [comment]
Glad you got it working!
