### ISSUE TITLE
how to put more than 2 icons on top of header like screenshot below?

### ISSUE THREAD

**Issue by jpca999** [react-community/react-navigation#2368]
![image](https://user-images.githubusercontent.com/1026325/29231363-ecb65c3e-7eb4-11e7-9649-b19780740753.png)

    static navigationOptions = ({ navigation }) => {
      const {state, setParams} = navigation;
      return {
        title: 'All Data (pull down)',
        headerRight: (
          <Button
            title='Add'
            // onPress={() => setParams({ mode: isInfo ? 'none' : 'info'})}
             onPress={() => navigation.navigate('createData')
             }
          />
        ),
      };
    };

**Comment by AlanFoster** [comment]
@jpca999 I'm not sure I understand the question; Do you want a custom title with two images?

Or do you want a custom image for your headerRight and headerLeft?

**Comment by jpca999** [comment]
@alanfoster yes I want custom images in the title...

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
