### ISSUE TITLE
can i put icon inside the title of the header ?

### ISSUE THREAD

**Issue by jpca999** [react-community/react-navigation#2369]
![image](https://user-images.githubusercontent.com/1026325/29234468-288c59f6-7ec5-11e7-8f8f-913b74268d6a.png)

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  
| react-native     |  
| node             | 
| npm or yarn      |

**Comment by spencercarli** [comment]
You'll need to create your own [header component](https://reactnavigation.org/docs/navigators/stack#header) to do this. You can use the existing [Header](https://github.com/react-community/react-navigation/blob/master/src/views/Header/Header.js) as a starting point.

**Comment by jpca999** [comment]
Lol - is there an easy way ?

**Comment by spencercarli** [comment]
Ah, actually you can put a React component into the [`headerTitle`](https://reactnavigation.org/docs/navigators/stack#headerTitle). That'll probably be easier.
