### ISSUE TITLE
Call function when tab navigator screen is mounted

### ISSUE THREAD

**Issue by swad1992** [react-community/react-navigation#2371]
Hello
How I can call function of A component ? (see commented line)
```
<Navigator
	onNavigationStateChange={(prevState, currentState) => {
  const getCurrentRouteName = (navigationState) => {
    if (!navigationState) return null;
    const route = navigationState.routes[navigationState.index];
    if (route.routes) return getCurrentRouteName(route);
    return route.routeName;
  };
  let currentRoute = getCurrentRouteName(currentState);
  if(currentRoute == "A") {
     // "HERE, HOW I CAN CALL FUNCTION IN THE 'A' COMPONENT") //---> the problem
  }
}}/>;
```
Thank you for any help

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!

**Comment by swad1992** [comment]
Hello,
thank you, I'm waiting answer in this issue (it's exactly the same problem)  : https://github.com/react-community/react-navigation/issues/51

**Comment by ceefour** [comment]
@swad1992 this seems the way : https://github.com/react-community/react-navigation/issues/51#issuecomment-323536642

Indeed it's pretty convoluted at the moment, and I don't think that this is already covered in the docs as @spencercarli suggested, as issue #51 proves this is not straightforward at all (142 comments from 52 participants!).

Just for the sake of comparison, Xamarin.Forms as [OnAppearing](https://developer.xamarin.com/api/member/Xamarin.Forms.Page.OnAppearing/).

**Comment by ceefour** [comment]
@swad1992 This is what I ended up using:

    export default class RootNavigator extends React.Component {
      state = {currentScreen: null}

      _onNavigationStateChange(prevState, newState, action) {
        // const currentScreen = getCurrentRouteName(currentState)
        // const prevScreen = getCurrentRouteName(prevState)
        // console.debug('onNavigationStateChange currentScreen=', currentScreen,
        //   'prevScreen=', prevScreen, 'action.routeName=', action.routeName)
        console.debug('onNavigationStateChange action.routeName=', action.routeName)
        this.setState({currentScreen: action.routeName})
      }

      render() {
        return <RootStackNavigator onNavigationStateChange={this._onNavigationStateChange.bind(this)}
          screenProps={{currentScreen: this.state.currentScreen}}/>;
      }

coupled with `componentDidUpdate()` on the screen (which may or may not perform something depending on the screenProps's `currentScreen`).

**Comment by swad1992** [comment]
@ceefour Perfect, thank you for your answer

**Comment by ceefour** [comment]
@swad1992 I just noticed my method has performance issues ... but it might work for you.

**Comment by swad1992** [comment]
@ceefour ok, I use it waiting for officials methods

**Comment by laurenz-glueck** [comment]
@swad1992 I tried your method and your right - it has significant performance issues... Do you found any alternative way?

**Comment by laurenz-glueck** [comment]
@swad1992 @ceefour - I think I found a better performing solution - if you use `componentWillReceiveProps` instead of `componentDidUpdate` the performance is much better:

```
componentWillReceiveProps(nextProps){
    if(nextProps.screenProps.currentScreen === 'ScreenName') {
        // do what you need
    }
}
```
