### ISSUE TITLE
How to change the tabBar_icon when the index changed.

### ISSUE THREAD

**Issue by Kaelzzs** [react-community/react-navigation#2375]
### Current Behavior

i can't find the way to changed icon image when index changed.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  
| react-native     |  
| node             | 
| npm or yarn      |

**Comment by WeiYuanlin** [comment]
Maybe I can help you!As you set icon,it has callback,Just like this code:       
 tabBarIcon: item => {
            let icon = item.focused ? require('../../../resource/tab_home_sel.png') : require('../../../resource/tab_home.png');
            return (
                <Image
                    source={icon}
                    style={{width:20,height:20}}
                />
            )
        }

**Comment by Kaelzzs** [comment]
@WeiYuanlin  It's helpful!

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
