### ISSUE TITLE
tab label allowfontscaling

### ISSUE THREAD

**Issue by saeropark** [react-community/react-navigation#2377]
Hi, i realize that the tab label scales according to the phone size. I saw that RN < Text> itself has a allowFontScaling={false} method which i can include in a text tag, however, tab label is not directly calling < Text>. any idea how to prevent font scaling? it is affecting my UI really bad.

**Comment by saeropark** [comment]
i manage to go right down to react-navigation src to edit the _renderlabel functionality..

react-navigation > src > views > tabview > tabview.js

under _renderlabel:

if (typeof label === 'string') {
      return (
        <Animated.Text style={[styles.label, { color }, labelStyle]} allowFontScaling={false}>
          {label}
        </Animated.Text>
      );
    }

include allowFontScaling = {false}


is there a way to not allow font scalling without changing the src code? or maybe add this feature?
i have users who set their iphone font text to the largest and the labels of the tab goes out of place.

**Comment by vonovak** [comment]
closing since this option was added in #2721

**Comment by prakashw3expert** [comment]
In react-navigation 2.0.4. it work for me as following 

`tabBarOptions: {
    allowFontScaling: false
  }`

**Comment by kumarutsav111** [comment]
This is how we should use it. 
const TabNavigator = createBottomTabNavigator(
  {
    Appointments: {
      screen: HomePage,
      navigationOptions: {
        tabBarLabel: "Appointments",
        headerLeft: null,
        tabBarIcon: ({ tintColor }) => (
          <Icon name="event" color={tintColor} size={25} />
        )
      }
    }
  },
  {
    tabBarOptions: {
      allowFontScaling: false
    }
  }
);
