### ISSUE TITLE
Don't change Tab label when inside a subroute

### ISSUE THREAD

**Issue by nickrobinson352** [react-community/react-navigation#2378]
I currently have the following nested hierarchy

TabA (title = 'TabA')
    - SubMenu A (title = 'SubmenuA') (default)
    - SubMenu B (title = 'SubmenuB')
TabB (title = 'TabB')
Tab C (title = 'TabC')

SubMenu are StackNavigators nested in TabNavigator which is the root. When I navigate to SubMenu A or SubMenu B, the label of the Tab in the TabNavigator changes to 'SubMenuA'. I would like the header title to show as 'SubmenuA' but the TabNavigator to still remain as 'TabA'

| software         | version
| ---------------- | -------
| react-navigation |  latest
| react-native     |  0.47
| node             | 
| npm or yarn      |

**Comment by spencercarli** [comment]
You should explicitly set the [tabBarLabel](https://reactnavigation.org/docs/navigators/tab#tabBarLabel) for each of your tabs to prevent it from being changed when a child navigator changes.
