### ISSUE TITLE
Dynamic Change Title Content

### ISSUE THREAD

**Issue by xiaosizhao** [react-community/react-navigation#2379]
```

class Web extends PureComponent {


    static navigationOptions = ({ navigation }) => ({

        title: 'find',

        headerStyle: { backgroundColor: color.theme },
    });

   

    render() {
       
        return (
            <View style={styles.container}>
                <Text>Hello React Native</Text>
            </View>
        )
    }

}

const styles = StyleSheet.create({
    container: {
        flex: 1,
    },
    webView: {
        flex: 1,
    }
})

const WebScene = StackNavigator(
    {
        Web: { screen: Web }
    },
    {
        navigationOptions: {
            // headerBackTitle: null,
            headerTintColor: color.white,
            showBack: true

        }
    }
)

export default WebScene;
```
How can I change the title content ? Someone can help me ?

**Comment by xiaosizhao** [comment]
I slove this problem 

`class Web extends PureComponent {


    static navigationOptions = ({ navigation }) => ({

        title: typeof(navigation.state.params)==='undefined' || typeof(navigation.state.params.title) === 'undefined' ? 'find': navigation.state.params.title,

        headerStyle: { backgroundColor: color.theme },
    });

   

    render() {
       
        return (
            <View style={styles.container}>
                <Text>Hello React Native</Text>
            </View>
        )
    }

}

const styles = StyleSheet.create({
    container: {
        flex: 1,
    },
    webView: {
        flex: 1,
    }
})

const WebScene = StackNavigator(
    {
        Web: { screen: Web }
    },
    {
        navigationOptions: {
            // headerBackTitle: null,
            headerTintColor: color.white,
            showBack: true

        }
    }
)

export default WebScene;`

And then you can use  
`this.props.navigation.setParams({ title: 'your content' })`
so you can dynamic change the title content.

**Comment by cactis** [comment]
seems works
`static navigationOptions = ({ navigation }) => ({
  title: navigation.state.params.title || 'default title',
  ...
});`

then 
`this.props.navigation.setParams({ title: 'your content' })
`

**Comment by mopilo** [comment]
I tried the solutions above, buh each time the screen  resets,  i get an error of undefined.  please how can i solve this error been stuck for a while now.

**Comment by anastely** [comment]
Hey, I want to use passed param in the next screen, I'm tried to do that with 
```
static navigationOptions = ({ navigation }) => {
        return {
            title: navigation.getParam('providerName'),
        };
    }
 render() {
        return (
            <View style={styles.container}>
                <Text>Provider Profile</Text>
                {console.log("@name", this.props.navigation.getParam('providerName'))} // i can get the name here
            </View>
        );
    }
```

**Comment by liyamahendra** [comment]
@cactis I have a small variation to your code, which gave `undefined` error when the `state.params` was `undefined`. Below is what I used:

```static navigationOptions = ({navigation}) => ({
    title: navigation.state.params ? navigation.state.params.title : 'Contacts',
  });```

**Comment by liyamahendra** [comment]
@cactis I have a small variation to your code, which gave `undefined` error when the `state.params` was `undefined`. Below is what I used:

```
static navigationOptions = ({navigation}) => ({
    title: navigation.state.params ? navigation.state.params.title : 'Contacts',
  });
```

And works well by allowing to change the title dynamically by calling `this.props.navigation.setParams({title: 'New Title'});`

**Comment by liyamahendra** [comment]
@cactis I have a small variation to your code, which gave `undefined` error when the `state.params` was `undefined`. Below is what I used:

```
static navigationOptions = ({navigation}) => ({
    title: navigation.state.params ? navigation.state.params.title : 'Default Title',
});
```

And works well by allowing to change the title dynamically by calling `this.props.navigation.setParams({title: 'New Title'});`

**Comment by anurbecirovic** [comment]
@liyamahendra  for some reason I can't use this navigationOptions at all, with new React Navigation.  Not sure how they manage when you want to change title dynamically.

**Comment by jgkiano** [comment]
Here's my implementation with the react-navigation > v5
 
```javascript
function MyScreen ({navigation, title = 'My dynamic title'} = {}) {
  navigation.setOptions({ title });
  return <Text>Hello world</Text>;
};
```
