### ISSUE TITLE
Bug: TouchableHighlight on initial screen stays black after going back (using StackNavigator)

### ISSUE THREAD

**Issue by thurt** [react-community/react-navigation#238]
Please see video: http://recordit.co/u84D4jtTj7

Using StackNavigator.
TouchableHighlight should not remain black when going back to the initial screen.

My TouchableHighlight has`onPress={() => this.props.navigation.navigate('SelectPriceRange')}`. no other TouchableHighlight props are defined.

**Comment by satya164** [comment]
cc @janicduplessis

**Comment by thurt** [comment]
i am able to reproduce on NavigationPlayground SimpleStack.js with some slight modification. will post code.

**Comment by thurt** [comment]
https://github.com/thurt/react-navigation/commit/1ffee15524cea889f3bcc33ec3024feda08ad2f0
http://recordit.co/PHkkvJNTIy

**Comment by spencercarli** [comment]
Hi! Could you try this on the most recent version of React Navigation? Since it's been a while since there's been any discussion on this issue I'm going to close it, but we can re-open if the issue still exists. Thanks!
