### ISSUE TITLE
How to used different icon when tabbaricon selected and unselected

### ISSUE THREAD

**Issue by Kaelzzs** [react-community/react-navigation#2381]
How to used different icon when tabbaricon selected and unselected。
which API ？

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  
| react-native     |  
| node             | 
| npm or yarn      |

**Comment by Kaelzzs** [comment]
sorry ,
`tabBarIcon`: ({focused,tintcolor}) => {
return 
}

**Comment by spencercarli** [comment]
Yes - `focused` is what you would want to use here. Here's an [example](https://github.com/react-community/react-navigation/blob/30ca3c1f80617abc28fdd71f0b37d4f62b3e388a/examples/NavigationPlayground/js/SimpleTabs.js#L47).
