### ISSUE TITLE
[question] stack over tabs: screen's header is not set with parameter passed to navigate()

### ISSUE THREAD

**Issue by garan82** [react-community/react-navigation#2386]
I download "react navigation examples" app from Google play store to check out example "stacks over tab" (source https://github.com/react-community/react-navigation/blob/master/examples/NavigationPlayground/js/StacksOverTabs.js ). When navigating to profile screen, the header title is empty but I think it's supposed to be "Jordans Profile". Specifically, line 103 https://github.com/react-community/react-navigation/blob/master/examples/NavigationPlayground/js/StacksOverTabs.js#L103 doesn't seem to set title correctly. I tried similar code on crna and the header is also blank. However, if title is set with literal string, it works just fine. Can someone help me how to set header through parameter passed to navigate().

doesn't set title correctly
`navigationOptions: ({ navigation }) => {
      title: `${navigation.state.params.name}'s Profile!`;
    },`

works fine
`navigationOptions: {
      title:"some title"
    },`

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.11
| react-native     |  0.46
| node             |  v6.11.0
| npm       | 3.10.10

**Comment by garan82** [comment]
Found a bug in example https://github.com/react-community/react-navigation/blob/master/examples/NavigationPlayground/js/StacksOverTabs.js  , I'll send a pull request.

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
