### ISSUE TITLE
TabNavigator vanished with latest git pull vs npm pull

### ISSUE THREAD

**Issue by sigmazen** [react-community/react-navigation#239]
Hi
Awesome library ... very straightforward and logical.  I'm a bit new to all this so apologies if I've made a dumb error.
This is my simple code:

    import React, { Component } from 'react';
    import {  AppRegistry, Text, StyleSheet, View, Button, Icon } from 'react-native';
    import { StackNavigator, TabNavigator } from 'react-navigation';
    
    import ChatScreen from './ChatScreen'
    import RecentChatsScreen from './RecentChatsScreen'
    import AllContactsScreen from './AllContactsScreen'
    
    const TabScreen = (
      TabNavigator({
        'Recent Chat': { screen: RecentChatsScreen },
        'Contacts': { screen: AllContactsScreen },
      })
    )
    
    TabScreen.navigationOptions = {
      title: 'Welcome',
    }
    
    const StackNav = StackNavigator({
      Home: { screen: TabScreen },
      Chat1: { screen: ChatScreen },
      Chat2: { screen: ChatScreen },
    });
    
    AppRegistry.registerComponent('navigationAppProto', () => StackNav);

Using the npm version I get to see the two Tabs at the bottom (top image)
Using the latest github clone version they're not showing (bottom image)

Any ideas?
Thanks in advance

![screen shot 2017-02-08 at 11 11 12 am](https://cloud.githubusercontent.com/assets/7496847/22751114/7ebe85bc-edf0-11e6-8244-0273c445b18f.png)
<img width="318" alt="screen shot 2017-02-08 at 11 13 37 am" src="https://cloud.githubusercontent.com/assets/7496847/22751127/8bc25720-edf0-11e6-8e0d-91049e0a4ceb.png">

**Comment by anpage** [comment]
It looks like this is a result of commit edad95a96da3829a191e46d5d65a43b502d9e936. The `visible` param is not defaulting to true.
