### ISSUE TITLE
Unable to add header image to DrawerNavigator

### ISSUE THREAD

**Issue by connected-space** [react-community/react-navigation#2391]
I've searched and tried myself to implement but unable to add a header image to the drawer (similar to the image below). I don't want to add the profile pic or any touchable functionality to the image, just show a static image.

![cdb7d6dc238d12e749f2d4fbd2d37a02](https://user-images.githubusercontent.com/28143488/29325681-86e6385a-81e0-11e7-900a-81f7483a1e16.jpg)

This is the set up of my DrawerNavigator at the moment which is working well for the rows.
```
const App1 = DrawerNavigator(
  {
    Events: {
      screen: HomeNavigator,
      navigationOptions: {
        drawerLabel: 'Events',
        drawerIcon: <Image source={eventsIcon} size={20} />
      }
    },
    Exhibition: {
      screen: HomeNavigator,
      navigationOptions: {
        drawerLabel: 'Exhibition',
        drawerIcon: <Image source={exhibitionIcon} size={20} />
      }
    },
    Lectures: {
      screen: HomeNavigator,
      navigationOptions: {
        drawerLabel: 'Lectures',
        drawerIcon: <Image source={lecturesIcon} size={20} />
      }
    },
    Screenings: {
      screen: HomeNavigator,
      navigationOptions: {
        drawerLabel: 'Screenings',
        drawerIcon: <Image source={screeningsIcon} size={20} />
      }
    },
    Walks: {
      screen: HomeNavigator,
      navigationOptions: {
        drawerLabel: 'Walks',
        drawerIcon: <Image source={walksIcon} size={20} />
      }
    },
    Tours: {
      screen: HomeNavigator,
      navigationOptions: {
        drawerLabel: 'Tours',
        drawerIcon: <Image source={toursIcon} size={20} />
      }
    }
  },
  {
    drawerWidth: 300,
    contentOptions: {
      activeTintColor: 'white',
      activeBackgroundColor: '#10ACBB',
      inactiveTintColor: 'black',
      labelStyle: 'normal'
    }
  }
)
```

So the question is, how do you add an image to the top of the DrawerNavigator?

**Comment by Shubham-Sinha** [comment]
Use ``contentComponent`` in DrawerNavigator for custom sidebar. [Check this](https://reactnavigation.org/docs/navigators/drawer#DrawerNavigatorConfig)

**Comment by connected-space** [comment]
Thanks for the response @Shubham-Sinha.

Going to have another look at it now and see how I get on.

**Comment by LogicSols** [comment]
from where you are getting these images what is the source of these ??
drawerIcon: <Image source={toursIcon} size={20} !!
kindly
