### ISSUE TITLE
How to pass default params to each routes to use it in their components?

### ISSUE THREAD

**Issue by Benjamin5050** [react-community/react-navigation#2392]
I have this router config:

```
export const Bird = StackNavigator({
    ResidentBirds: {
        screen: BirdList,
        navigationOptions: ({navigation}) => ({
            title: 'Resident Birds',
        })
    },
    MigratoryBirds: {
        screen: BirdList,
        navigationOptions: {
            title: 'Migratory Birds'
        }
    }
});
```

Both the routes have the same screen component (BirdList).

BirdList.js:

```
export default class BirdList extends React.Component {
    state = {
        fetching: false,
        dataSource: []
    };

    componentDidMount() {
        this.getBirds();
    }

    getBirds = () => {
        // const birdType = this.props.navigation.state.params.birdType;
        // const args = this.pros.navigation.state.params.args;

        // fetch list of birds of type birdType
    };

    render() {
        return (
            <View style={{flex: 1, backgroundColor: 'skyblue'}}>
                <Text>Fetching birds: {this.state.fetching.toString()}</Text>
                <FlatList
                    data={this.state.dataSource}
                    ...
                />
            </View>
        )
    }
}
```

My question is how can I pass default params to the Routes (i.e., ResidentBirds and MigratoryBirds) so that I can use that values to fetch appropriate data? Maybe something like this:

```
export const Bird = StackNavigator({
    ResidentBirds: {
        screen: BirdList,
        navigationOptions: ({navigation}) => ({
            title: 'Resident Birds',
        }),
        params: {
            birdType: 'Resident',
            args: {
                'height': 100,
                'region': 'America'
            }
        }
    },
    MigratoryBirds: { 
        ...
    }
});
```

I am using:

- "react": "16.0.0-alpha.12",
- "react-native": "^0.46.1",
- "react-navigation": "^1.0.0-beta.11"

**Comment by spencercarli** [comment]
Here's a way I've done similar things

```javascript
export const Bird = StackNavigator({
    ResidentBirds: {
        screen: (props) => <BirdList {...props} birdType="Resident" args={{ height: 100, region: 'America' }} />,
        navigationOptions: ({navigation}) => ({
            title: 'Resident Birds',
        })
    },
    ...
});
```

Notice that I can pass any custom props to the component but also that I need to copy over all existing props (`{...props}`) so the component still has access to `navigation`.

**Comment by Benjamin5050** [comment]
Yes, that's much better! Thank you Spencer.

**Comment by galhardi** [comment]
@spencercarli, I need change this prop inside my component to update my conditional render. When enter in tab the value is true and after a action I set to false.
When user go to another screem and then come back I need set this default value to true again, but this value never update.
Do you know how I can do this?

**Comment by acomito** [comment]
@spencercarli is there anyway to do something similar but have it show up in the params object? I want to re-use a screen, and I want to do X on the screen when this.props.navigation.state.params.specialThing is true and something else when this.props.navigation.state.params.specialThing  is false. And in one case I can pass in specialThing like a normal param to this.props.navigation.navigate, and the other I'd like to pass in from where I declare my router config (as you do above).

**Comment by brentvatne** [comment]
`this.props.navigation.getParam('name', defaultValueHere)` lets you have default params

grab the default value from the prop if you want

**Comment by SurrealShock** [comment]
I am getting `Unhandled promise rejection: TypeError: undefined is not an object (evaluating 'this.props.navigation.state.params.birdType'` when trying to access the value using Spencer's method.

**Comment by agarwalvasu** [comment]
@Manoj002 
Did you get the answer? I am too stuck on the same problem and I can't find any solution.
