### ISSUE TITLE
Screen mount twice when go back and quickly re navigate to same screen 

### ISSUE THREAD

**Issue by lyingd** [react-community/react-navigation#2396]
I use StackNavigator for my application with two screens.
Page1 can navigate to Page2, and Page2 can go back to Page1.
### Current Behavior

When I am on Page2, go back to Page1 , and quickly re navigate to Page2, the Page2 mount twice,  mount first->remount second->unmount first, 
gif:
![](https://thumbs.gfycat.com/SpanishLargeGourami-size_restricted.gif)
log:
```
1 -> [page 2]constructor
1 -> [page 2]render
1 -> [page 2]componentDidMount
1 -> [page 2]componentWillUnmount
2 -> [page 2]constructor
2 -> [page 2]render
3 -> [page 2]constructor
3 -> [page 2]render
2 -> [page 2]componentDidMount
3 -> [page 2]componentDidMount
2 -> [page 2]componentWillUnmount
3 -> [page 2]componentWillUnmount
```

### Expected Behavior

The Page2 should mount once.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.12
| react-native        | 0.47.1
| react                    | 16.0.0-alpha.12
| node                    | 7.10.0
| yarn                     | 0.21.3
| npm                     | 5.3.0

### Demo
```javascript
//index.ios.js
import React, { Component } from 'react'
import { AppRegistry, } from 'react-native'

import { StackNavigator } from 'react-navigation'
import Page1 from './Page1'
import Page2 from './Page2'
const Scenes = StackNavigator({
  Page1: {
    screen: Page1,
    navigationOptions: {
      title: 'Page1',
    }
  },
  Page2: {
    screen: Page2,
    navigationOptions: {
      title: 'Page2',
    }
  },
})

AppRegistry.registerComponent('demo', () => Scenes)
```
```javascript
//Page1.js
import React, { Component } from 'react'
import {
  Text,
  TouchableOpacity
} from 'react-native'
let i = 0
export default class Page1 extends Component {
  index
  constructor(props) {
    super(props)
    this.index = ++i
    console.log(`${this.index} -> [page 1]constructor`)
  }
  componentDidMount() {
    console.log(`${this.index} -> [page 1]componentDidMount`)
  }
  componentWillReceiveProps(nextProps) {
    console.log(`${this.index} -> [page 1]componentWillReceiveProps`)
  }
  componentWillUnmount() {
    console.log(`${this.index} -> [page 1]componentWillUnmount`)
  }
  render() {
    console.log(`${this.index} -> [page 1]render`)
    const {
			navigation
    } = this.props

    return (
      <TouchableOpacity style={{ flex: 1 }} onPress={() => {
        navigation.navigate('Page2')
      }}>
        <Text>goto page 2</Text>
      </TouchableOpacity>
    )
  }
}
```
```javascript
//Page2.js
import React, { Component } from 'react'
import {
  Text,
} from 'react-native'
let i = 0
export default class Page2 extends Component {
  index
  constructor(props) {
    super(props)
    this.index = ++i
    console.log(`${this.index} -> [page 2]constructor`)
  }
  componentDidMount() {
    console.log(`${this.index} -> [page 2]componentDidMount`)
  }
  componentWillReceiveProps(nextProps) {
    console.log(`${this.index} -> [page 2]componentWillReceiveProps`)
  }
  componentWillUnmount() {
    console.log(`${this.index} -> [page 2]componentWillUnmount`)
  }
  render() {
    console.log(`${this.index} -> [page 2]render`)
    return <Text>page2</Text>
  }
}
```

**Comment by lyingd** [comment]
Any solution yet? I found the issue exists only in iOS.
I fix it like this, but I don't know why the issue exists only in iOS.
```javascript
//CardStack.js
  render(){
    //...other code
    const hasReNavigate = this._hasScenesReNavigate(scenes);
    return (
      <View {...handlers} style={containerStyle}>
        <View style={styles.scenes}>
          {scenes.filter((s: *) => !(s.isStale && hasReNavigate)).map((s: *) => this._renderCard(s))}
        </View>
        {floatingHeader}
      </View>
    );
  }

  _hasScenesReNavigate(scenes: Array<NavigationScene>) :boolean {
    let scenesCount = scenes.length;
    let doubleIndex = scenesCount >= 2 && scenes[scenesCount - 1].index === scenes[scenesCount - 2].index;
    let hasReNavigate = false;
    if(doubleIndex){
      const route = scenes[scenesCount - 1].route;
      const prevRoute = scenes[scenesCount - 2].route;
      hasReNavigate = route.routeName === prevRoute.routeName;
    }
    return hasReNavigate;
  }
```

**Comment by kholiavko-roman** [comment]
Same issue

**Comment by ahmadalfy** [comment]
I have the exact same issue and I thought I was doing something wrong

**Comment by brunocascio** [comment]
+1

**Comment by quangduz** [comment]
Same to me,

When i use react-native-admob to show AdMobInterstitial.

First, screen will change when user press button. At this case, everything ok. Go -> back -> go -> back ...

Then, i use a function (A) to show AdMobInterstitial before screen move (multi functions when button press). I got problem here, Go -> back -> Go (2 times) -> back (2 times) -> Go ( 3 times) ....

So, i think, our problem will be found in (A).

Ok, now, in this func, i used an Event Listener when adClosed. Its mean, screen only move after adClosed. 

```
    AdMobInterstitial.addEventListener('adClosed',
      () => {
        console.log('AdMobInterstitial => adClosed');
        (error) => console.warn(error);
        navi.navigate(...)
      }
    );
```

I move the navigation out of this event.

```
    navi.navigate(....);

    AdMobInterstitial.addEventListener('adClosed',
      () => {
        console.log('AdMobInterstitial => adClosed');
        (error) => console.warn(error);
      }
    );
```
Test again => Problem solved !
But in this case, Ad and Screen will run at same time.

Waiting for professionals found good solutions from my case.

Sorry for my bad english !

**Comment by tangweikun** [comment]
+1

**Comment by Charles-LMQ** [comment]
+1

**Comment by gancan110** [comment]
Same to me

**Comment by kelset** [comment]
Pinging OP @lyingd since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open; if I get no answer in the next 7 days I will close it.

Moreover, if that's the case and the code [fix you posted](https://github.com/react-community/react-navigation/issues/2396#issuecomment-327862954) solves the issue, can you please open a PR with it?

Last thing, @gancan110 @Charles-LMQ @tangweikun @brunocascio @kholiavko-roman commenting with useless "same issue/ +1" only pollutes the issue. Use the reactions 👍 .

**Comment by brunocascio** [comment]
@kelset My apologies.

Since Github does not notify when a reaction has been made, we use "+1/same issue" in order to make a "hey, this issue need attention", but you are right and make sense for me.

Thanks!

**Comment by kelset** [comment]
Hi there @lyingd,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.

**Comment by AdamChrist** [comment]
same issue in `"react-navigation": "1.5.6"`

**Comment by SDrinkwater** [comment]
I have the same issue with 2.0.1.

**Comment by edo1493** [comment]
I have the same issue on 2.6.2.

**Comment by ravirupareliya** [comment]
Same issue with `react-navigation:2.12.1`

I had 3 screens called LoginScreen, HomeScreen and HomeDetailScreen.

Here is the output in each case

Initial load
output : calls constructor of LoginScreen

When i move from Login to Home
output : calls constructor of LoginScren -> calls constructor of HomeScreen.

when i move from Home to HomeDetail
output : calls constructor of LoginScren -> calls constructor of HomeScreen -> calls constructor of HomeDetailScreen.

**Comment by ahartzog** [comment]
I'm also seeing a screen (a StackNavigator inside a TabNavigator) being re-mounted when it's being navigated AWAY from. Super odd, trying to get to the bottom of it.

**Comment by danmdinu** [comment]
same issue on Android "react-navigation": "^3.5.1" 

Why was this issue closed?

**Comment by CodeBlastr** [comment]
Same issue 3.11.1

**Comment by Flouwrian** [comment]
same issue 4.0.10

**Comment by miguelmsoler** [comment]
same issue 3.11.1

**Comment by adamsolomon1986** [comment]
same issue here

**Comment by MAKARD** [comment]
Same issue 5.7.1

**Comment by Das-ist-gutt** [comment]
Same issue on react-navigation: 4.4.3

**Comment by cashcount** [comment]
same

**Comment by lzchengmi** [comment]
still same issue in react-navigation: 2.16.0
