### ISSUE TITLE
ReactNavigation.org is down

### ISSUE THREAD

**Issue by callmetwan** [react-community/react-navigation#2397]
I wasn't sure where to put this, and I'm sure folks that manage the docs are aware, but figured it was worth mentioning.

I was getting a SSL handshake error and now I'm getting a 500 error.

**Comment by spencercarli** [comment]
cc @skevy @matthamil 

I'm having quite a few issues with the site as well. Who manages it?

**Comment by matthamil** [comment]
If you have stumbled across this issue and are needing access to the documentation, please refer to the markdown files in the repo for the time being. They are found [here](https://github.com/react-community/react-navigation/tree/master/docs). Sorry for this :(

CC @grabbou @satya164

**Comment by matthamil** [comment]
Closing as this now seems resolved.

**Comment by skevy** [comment]
We host on now.sh. Zeit had an outage this morning.

**Comment by callmetwan** [comment]
Thanks all!

**Comment by Kreozot** [comment]
Still down. Checked many times in 3 weeks.

**Comment by matthamil** [comment]
Might have been a temporary outage or a problem with Circle CI @Kreozot. The website appears to be up now.

**Comment by danmondy** [comment]
down again? 503
