### ISSUE TITLE
Is there any way to save and restore the navigation history

### ISSUE THREAD

**Issue by anishtr4** [react-community/react-navigation#2401]
I have a StackNavigator(1) with 5 screens. After 3rd screen I am navigating into another StackNavigator(2) screen and after some action on the second StackNavigator(2) screen I need to come back to Stack StackNavigator(1) 4th screen and should be able to go back to history in StackNavigator(1) using navigation.goBack()

I am able to come back to Stack StackNavigator(1) 4th screen but when i use navigation.goBack() it is not going to StackNavigator(1) 3rd screen

I need to save and restore the navigation history in StackNavigator(1).

Please let me know is there any way to achieve this.

![untitled diagram](https://user-images.githubusercontent.com/2930699/29380087-2d3c2ba4-82e2-11e7-9aab-1c27182e6d74.png)

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!

**Comment by sospedra** [comment]
If you have `react-navigation` connected to `redux` you can plugin `redux-persist` which will save/rehydrate the `store`; including the `react-navigation` state. Elsewhere I'm pretty sure you cannot save internal React states.

**Comment by Ahmed1998222** [comment]
Does anyone get an idea else redux-persist?
