### ISSUE TITLE
headerTruncatedBackTitle option doesn`t work

### ISSUE THREAD

**Issue by tavriaforever** [react-community/react-navigation#2402]
### Current Behavior
I found a header options `headerTruncatedBackTitle` https://github.com/react-community/react-navigation/blob/be1da2c4c97a97aefc81c7e7497913e440423bdb/docs/api/navigators/StackNavigator.md#headertruncatedbacktitle

But truncated back title leave `Back`.

![iphone 5s ios 10 3 14e8301 2017-08-16 23-44-43](https://user-images.githubusercontent.com/975906/29384487-eeaa3142-82dc-11e7-826d-e73154ca66c7.png)

My code 
```
class AboutScreen extends Component {
  static navigationOptions = () => ({
    headerTitle: 'About',
    headerStyle: styleHeader.common,
    headerTitleStyle: styleHeader.title,
    headerTruncatedBackTitle: 'Return', // this is not working
  })

  render() {
    return (
      <Container>
        <Content>
          <Text>some text</Text>
        </Content>
      </Container>
    );
  }
}
```

### Expected Behavior
I want change back title to `Return` or disabled title at all, leave only arrow back

### Your Environment
| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.11
| react-native     |  0.47.1
| node             | 6.11.2
| npm or yarn      | 3.10.10

**Comment by spencercarli** [comment]
Can you provide a demo of this issue? Preferably on [Snack](https://snack.expo.io)

**Comment by matthamil** [comment]
The `headerTruncatedBackTitle` is never showing because `headerBackTitle` is not set. `headerTruncatedBackTitle` is a back-up when `headerBackTitle` is too long to render properly.

**Comment by dflourusso** [comment]
@matthamil Thanks, it works for me.

**Comment by kelset** [comment]
Pinging OP @tavriaforever since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open; if I get no answer in the next 7 days I will close it.

**Comment by tavriaforever** [comment]
Let`s close it! Thanks for help!

**Comment by lolobosse** [comment]
Hey, 

I walked into this issue and I think the documentation is not super beginner friendly on that point (I had to look at source code to understand): **This has to be defined in the origin view not in the destination view**

For instance, when you have a transition A to B you should have something like:

```javascript
 StackNavigator({
   A: {
        screen: AScreen,
        navigationOptions: () => ({
            title: `A`,
            headerBackTitle: 'A much too long text for back button from B to A',
            headerTruncatedBackTitle: `to A`
        }),
     },
   B: {
     screen: BScreen,
     navigationOptions: () => ({
            title: `B`,
     }),
    }
})

```

**Comment by brentvatne** [comment]
pr to docs welcome: http://github.com/react-navigation/website

**Comment by brentvatne** [comment]
can continue discussion on the issue linked to above ^
