### ISSUE TITLE
Crash when navigating with image in parent screen header

### ISSUE THREAD

**Issue by genbag** [react-community/react-navigation#2403]
### Current Behavior

When going from a screen with a header like this : 
```
static navigationOptions = {
    title: (
      <Image
        source= require('./assets/logo/c2iStandardFonce.png')
        style={{height: 170, width: 300}}
        resizeMode="contain"
      />
    ),
    headerStyle: { height: 130, backgroundColor: '#424242', borderTopWidth: 27, borderTopColor: 'black' },
    headerTitleStyle: {color: '#ffffff', alignSelf: 'center', marginTop: 30, marginBottom: 30}
  };
```
To another, my expo crashes, i don't know if the problem comes from my code or expo (although i don't see why it would come from expo)
My png is in my source files, and is displayed without problems nor errors.

### Expected Behavior

It shouldn't crash :).

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0 beta 11
| react-native     |  0.45.1
| node             | 6.11.2
| npm or yarn      | 3.10.10

**Comment by genbag** [comment]
i was using title in place of headerTitle, sorry for the useless thread.

**Comment by craig8two** [comment]
This helped me, thank you. I was using "title" instead of "headerTitle". Thank you.
