### ISSUE TITLE
NavigationActions.reset setParams don't work

### ISSUE THREAD

**Issue by nuoxiang** [react-community/react-navigation#2404]
```js
 const resetAction = NavigationActions.reset({
                index: 0,
                actions: [
                    NavigationActions.navigate({
                        routeName: 'Main',
                        params:{login:true}
                    })
                ]
            })
            this.props.navigation.dispatch(resetAction)
```
In MainPage ,I can't get params.What's wrong

**Comment by spencercarli** [comment]
How are you accessing params from the Main component?

**Comment by nuoxiang** [comment]
MainPage is a TabNavigator.
```js
const MainPage = TabNavigator({
    Home: {
        screen: HomePage,
    },
   ...
})
```
In HomePage ,I use `console.log(this.props.navigation.state)` ,can't get params

**Comment by spencercarli** [comment]
Can you put together a running example of this issue? It could be a bug but we need to isolate it from your other code first

**Comment by nuoxiang** [comment]
(https://github.com/nuoxiang/testRN) 
In LoginPage , use `NavigationActions.reset` can't get params ,but use `NavigationActions.navigate` can get

**Comment by vanhoutk** [comment]
I think I have the same issue. My structure is a Stack Navigator, with a Tab Navigator nested inside of it. 

```
const TabNav = TabNavigator({
  TabA: {
    screen: TabA,
  },
  TabB: {
    screen: TabB,
  },
});

const StackNav = StackNavigator({
  ScreenA: { screen: ScreenA },
  ScreenB: { screen: ScreenB },
  Tabs: { screen: TabNav },
});
```

When I navigate from ScreenA to the TabNav, either through directly using `navigate( )` or through using `NavigationActions.navigate( )`, it works perfectly fine, but when I try to reset (as I don't want my users to be able to go back one they're in the TabNav), I can suddenly no longer access props from within my Tabs.

This works:
```
const navigateAction = NavigationActions.navigate({
  routeName: 'Tabs',
  params: {id: id, auth: auth}
});
this.props.navigation.dispatch(navigateAction);*/
```

This doesn't:
```
const resetAction = NavigationActions.reset({
  index: 0,
  actions: [
    NavigationActions.navigate({
      routeName: 'Tabs',
      params: {id: id, auth: auth}
    })
  ]
});
this.props.navigation.dispatch(resetAction);
```

The error the latter throw up is `[TypeError: undefined is not an object (evaluating 'state.params.id')]`

**Comment by nuoxiang** [comment]
@vanhoutk `[TypeError: undefined is not an object (evaluating 'state.params.id')]` because state don't have params , you can use `console.log(this.props.navigation)` see data structure .

**Comment by vanhoutk** [comment]
Sorry I should have specified that in my TabA and TabB I have the following line `const { state } = this.props.navigation;`, thus `state.params` is how I'm attempting to access the params passed through the NavigationAction

**Comment by Denakol** [comment]
I have some issue with same structures. @vanhoutk did you find solution for this?

**Comment by vanhoutk** [comment]
@Denakol Nope I have not. I'm hoping that it gets solved before I need to go to production, but if not I'll probably use asyncstorage as a work around.

**Comment by Denakol** [comment]
@vanhoutk I found solution in https://github.com/react-community/react-navigation/issues/2073. 
I call the init() instead of navigate() and it works now.

**Comment by vanhoutk** [comment]
@Denakol, thanks for that!

**Comment by nuoxiang** [comment]
@Denakol thanks

**Comment by thangkho** [comment]
@vanhoutk  I use `const navigateAction = NavigationActions.navigate({
  routeName: 'Tabs',
  params: {id: id, auth: auth}
});
this.props.navigation.dispatch(navigateAction);*/` but I can't get param in Tabs. How I can get it?
