### ISSUE TITLE
NavigationContainer flowtypes are wrong 

### ISSUE THREAD

**Issue by dantman** [react-community/react-navigation#2406]
The flowtype for the `NavigationContainer` props (what `StackNavigator` and all the other navigators return) marks `navigation` and `navigationOptions` as required props.

This is incorrect since `navigationOptions` is not required and `navigation` is explicitly not required because `NavigationContainer` is responsible for the navigator at the top level.

**Comment by 349989153** [comment]
May I ask how can I access to `NavigationContainer` in a certain screen?

**Comment by dantman** [comment]
@349989153 `NavigationContainer` is defined in [`src/createNavigationContainer.js`](https://github.com/react-community/react-navigation/blob/master/src/createNavigationContainer.js). It's the return value when you call `StackNavigator({...}, {...})`. You don't need to access it from a screen.

**Comment by 349989153** [comment]
@dantman thanks a lot, I start to understand how it works

**Comment by kelset** [comment]
hey @DanielMSchmidt is this still the case with latest version? We refactored a lot of flowtypes while moving to RN 0.49 & flow 0.53

**Comment by DanielMSchmidt** [comment]
I think you mean @dantman

**Comment by kelset** [comment]
(uh yeah sorry, stupid autocomplete ><' )

**Comment by dantman** [comment]
Yup, I don't get the error anymore on the tests in my PR.
