### ISSUE TITLE
How can I force TabNavigator's child to re-render in TabNavigator?

### ISSUE THREAD

**Issue by 2hyjun** [react-community/react-navigation#2407]
## How can I force TabNavigator's child to re-render in TabNavigator?
```javascript
export const MainTab = TabNavigator({
    Timeline: {
        screen: TypeTab,
        navigationOptions: {
            ...
        }
    },
    Post: {
        screen: post,
        navigationOptions : {
            ...
        }
    },
    Chat: {
        screen: ChatStack,
        navigationOptions:{
            ...
        }
    },
    MyPage: {
        screen: MyPageStack,
        navigationOptions: {
            ...
        }
    }
}, {
    tabBarComponent: TabBarBottom,
    tabBarPosition: 'bottom',
    swipeEnabled: false,
    animationEnabled: true,
    lazy: true,
    tabBarOptions: {
        showIcon: true,
        showLabel: false,
    }

});
```

```javascript
export const ChatStack = StackNavigator({
    ChatList: {
        screen: meanless5,
    },
    ChatRoom: {
        screen: chat
    }
});
```

```javascript
class meanless5 extends React.Component {
    constructor(props) {
        super(props);

    }
    componentWillMount() {
        Alert.alert('componentWillMount!');
    }

    componentDidMount() {
        Alert.alert('componentDidMount!');
    }
    render() {

        return (
            <View>
                <Text>
                    {'\n\n\n\n\n\n'}Hi
                </Text>
            </View>
        )

    }
}
```

```javascript
this.props.onNavigate('Chat',
            {
                user_email: global.user_email,
                partner_email: this.props.user_email
            })
```
`this.props.onNavigate` equals to `this.props.navigation.navigate`
this method is called in a screen of `MainTab`(TabNavigator).
### Current Behavior

I want a component to be re-rendered EVERY TIME I navigate to it.
But it was rendered only ONCE when I navigate to it.

### Expected Behavior

Every time I navigate to a screen,  how can I force that screen to be re-rendered?
### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.11
| react-native     |  0.47.1
| node             |  8.2.1
| npm or yarn      | npm 5.3.0

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!

**Comment by nickjuntilla** [comment]
@spencercarli You didn't answer the question at all and then closed the tab. That's poor project management.
