### ISSUE TITLE
A doubly nested DrawerNavigator dispatches actions incorrectly

### ISSUE THREAD

**Issue by Draydrew** [react-community/react-navigation#2408]
I have a basic navigator layout with a StackNavigator on top, containing another StackNavigator that contains a DrawerNavigator. Not using Redux or anything, just the navigator library alone. 

I'm looking to use this sort of structure so I can have a 'main' StackNavigator paired with a 'modal' StackNavigator on the top level, allowing a modal to appear from the bottom of the screen and such.

The code producing this bug looks like this (the screens are just simple Views/Text with a title in the navigationOptions, nothing else):

```
const MainDrawerNavigator = DrawerNavigator({
    screen: {screen: Screen1},
    screen4: {screen: Screen4},
})

const MainStackNavigator = StackNavigator({
    screen: {screen: MainDrawerNavigator},
    screen2: {screen: Screen2},
})

const TopLevelStackNavigator = StackNavigator({
    nestedStackNavigator: {screen: MainStackNavigator},
})

AppRegistry.registerComponent('app', () => TopLevelStackNavigator)
```

### Current Behavior
When opening the DrawerNavigator with a gesture, for some reason it appears to push in another scene. From what I've seen from the console outputs, dragging the DrawerNavigator open fires a navigation action to `DrawerOpen` twice. This is a gif of it:

![drawernavbug2](https://user-images.githubusercontent.com/9513009/29409534-8d9f6db4-8344-11e7-9c0e-ea7d28cf5100.gif)

The `DrawerClose` navigation does not fire so the menu is still open after navigating back too. After closing the menu (firing a navigation action to `DrawerClose`), opening the menu then causes two navigations to `DrawerOpen` again and so on and so forth.

### Expected Behavior
Only one navigation to `DrawerOpen` should be fired when the menu is opened by a gesture. This works normally if it's just a single StackNavigator with a DrawerNavigator inside. The problem only presents itself when extra StackNavigators are added on top.

(Interestingly, it also seems to work fine if the top level navigator is a TabNavigator instead of a StackNavigator.)

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.11
| react-native     |  0.47.1
| node             | 8.2.1
| npm or yarn      | yarn (0.27.5)

Any help would be very appreciated.

**Comment by vonovak** [comment]
I think you may be able shuffle your navigation structure a little and find a different setup that will make it work the way you want. I for example have a stack without header as top level nav, then in it I have some screens and a drawer, which has also stack in it.. not sure this helps but it's just a tip

**Comment by Ajith-Pandian** [comment]
@Draydrew I'm facing exactly the same issue. Did you find any solution or workaround?

**Comment by Draydrew** [comment]
@vonovak Thank you for the suggestion! I'm not sure if there's a way to shuffle the screens around and still get a proper modal transition though.

@Ajith-Pandian Unfortunately no, haven't seen or managed any progress on this issue yet.

**Comment by Ajith-Pandian** [comment]
@Draydrew Thanks. I'll let you know If I find any workaround or fix.

**Comment by Ajith-Pandian** [comment]
@Draydrew I found a workaround for this by the following code,

````
const MainDrawerNavigator = DrawerNavigator({
    screen: {screen: Screen1},
    screen4: {screen: Screen4},
})

const MainStackNavigator = StackNavigator({
    screen: {screen: MainDrawerNavigator},
    screen2: {screen: Screen2},
})

const RescueComponent = () => <MainStackNavigator />;

const TopLevelStackNavigator = StackNavigator({
    nestedStackNavigator: {screen: RescueComponent},
})

AppRegistry.registerComponent('app', () => TopLevelStackNavigator)
````
Try this. I hope it will help you.

**Comment by Draydrew** [comment]
@Ajith-Pandian Thank you very much!

**Comment by kelset** [comment]
Pinging OP @Draydrew since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open; if I get no answer in the next 7 days I will close it.

Moreover, the code snippet provided by @Ajith-Pandian seems to fix your issue.

**Comment by Draydrew** [comment]
@kelset Ah sorry, yep I'm happy with this issue being resolved. I'll go ahead and close it.

**Comment by manojbhardwaj** [comment]
@Ajith-Pandian Thank you very much!
