### ISSUE TITLE
[Question] Avoid status bar overlap on all screens

### ISSUE THREAD

**Issue by James2516** [react-community/react-navigation#2410]
I want all screens on my app to appear below the status bar on both iOS and Android. Currently I have to use `headerStyle: { marginTop: 24 }` on all the stack navigators.

Is there a way to do this globally? Where is the appropriate top level component to add the `StatusBar` in a Redux app? (eg. which part of https://github.com/react-community/react-navigation/tree/master/examples/ReduxExample)?

**Comment by Noitidart** [comment]
I do the same thing. Note that on iOS marginTop should be 20. On Android you should use `StatusBar.currentHeight` instead of hard coding 24 (it usually is 24 though).

**Comment by riwu** [comment]
Where do u wrap your whole app? https://github.com/react-community/react-navigation/tree/master/examples/ReduxExample Wrapping it at `<Provider>` does not work.

**Comment by Noitidart** [comment]
Ok so I lied, I don't really wrap my whole app. Each screen/card has a `<Header>` component. I just gave that `<Header>` a extra padding at the top so it shows nicely behind the status bar.

**Comment by ro-savage** [comment]
Shouldn't this be defaulted into the app? 

That the header always appears below the statusbar (unless specified otherwise).

As @efkan pointed out, updating [line 24](https://github.com/react-community/react-navigation/blob/b310b153fd76edd27ecbf4d6d2d71ead1d33a530/src/views/Header.js#L37) in header.js fixes this.

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
