### ISSUE TITLE
Can I remove tab like this if i use react-navigation

### ISSUE THREAD

**Issue by IZHQT** [react-community/react-navigation#2416]
![image](https://user-images.githubusercontent.com/6813909/29452913-7c88c024-843a-11e7-8479-6d1bd054ae9e.png)
I want to do like this

**Comment by spencercarli** [comment]
If you wish to not show the tabbar you can simply set `tabBarComponent` to `View`, like in this [example](https://snack.expo.io/ByVnC6EOb)
