### ISSUE TITLE
Error: Ripple drawable is not availabile on android API <21 

### ISSUE THREAD

**Issue by FrancescaBarbazeni** [react-community/react-navigation#2417]
During the loading of DrawerNavigator the App crash over this error:

> Error while updating property "nativeBackgroundAndroid" of a view managed by: RTCView
> Ripple drawable is not available on android API <21

| software         | version
| ---------------- | -------
| react-navigation |  ^1.0.0-beta.11
| react-native     |  0.47.1
| node             |  7.6.0
| npm or yarn      | 4.6.1
| android      | 4.4.3

**Comment by fighterzhou** [comment]
发自网易邮箱大师
On 08/18/2017 18:41, FrancescaBarbazeni wrote:

During the loading of DrawerNavigator the App crash over this error:

Error while updating property "nativeBackgroundAndroid" of a view managed by: RTCView
Ripple drawable is not available on android API <21

| software | version |
| react-navigation | ^1.0.0-beta.11 |
| react-native | 0.47.1 |
| node | 7.6.0 |
| npm or yarn | 4.6.1 |
| android | 4.4.3 |

**Comment by spencercarli** [comment]
Could you provide an example that demonstrates this issue?

**Comment by matthamil** [comment]
Android 4.4.3 is [API level 19](https://developer.android.com/about/versions/android-4.4.html). [RippleDrawable](https://developer.android.com/reference/android/graphics/drawable/RippleDrawable.html) was added in API level 21. You will need to provide your own custom [`contentComponent`](https://reactnavigation.org/docs/navigators/drawer#DrawerNavigatorConfig) to avoid using the react-navigation built-in Drawer item components which use the ripple effect.
