### ISSUE TITLE
How to navigate to different screen and get back to the screen from where its navigated when using DrawerNavigator?

### ISSUE THREAD

**Issue by robinlery** [react-community/react-navigation#2418]
I have two components (**List** and **Detail**):

List.js:

```
export default class List extends React.Component {
    render() {
        const {navigate} = this.props.navigation;
        return (
            <View style={styles.container}>
                <Text style={styles.headerText}>List of Contents</Text>
                <Button onPress={()=> navigate('Detail')} title="Go to details"/>
            </View>
        )
    }
}
```

Detail.js:

```
export default class Detail extends React.Component {
    render() {
        return (
            <View>
                <Text style={styles.headerText}>Details of the content</Text>
            </View>
        )
    }
}
```

I would like to have two screens (_NowList_ and _SoonList_) which are basically the same type of list, so I am using the same **List** component for both the screen. And from each of these screens I want to navigate to the _Detail_ screen of the item, also which in this case has the same type of layout so I am using **Detail** component for both the list items.

Finally, when the App starts I want the _NowList_ screen to show. And using the drawer I would like to navigate to _SoonList_ screen.

I am not sure how to configure this route. But, this is how I have configured the routes for now:

```
const NowStack = StackNavigator({
    NowList: {
        screen: List,
        navigationOptions: {
            title: 'Now',
        }
    },
    Detail: {
        screen: Detail,
        navigationOptions: {
            title: 'Detail',
        }
    }
});

const SoonStack = StackNavigator({
    SoonList: {
        screen: List,
        navigationOptions: {
            title: 'Soon',
        }
    }
});

export const Drawer = DrawerNavigator({
    Now: {
        screen: NowStack,
    },
    Soon: {
        screen: SoonStack,
    }
});
```

So when the app starts _NowList_ screen is displayed. I can navigate from _NowList_ route to _Detail_ route. There's a back button in the _Detail_ route which on press navigates back to the _NowList_. Which is how I expect it to be.

However, when I go to _Soon_ route using the DrawerNavigator, and navigate to _Detail_ route, I go to Detail screen. But, when I press the back button on **Detail** navigation header, instead of navigating back to the _SoonList_ screen, I am navigated to the _NowList_ screen.

I think I am missing something here, or my route layout is not how its suppose to be. Could you help me how to configure the routes so that I can use DrawerNavigator to navigate to different screens, and from those screens navigate to another screen and again back to the screen navigated from?

Using:
  
-   "react-native": "^0.46.1",
-   "react-navigation": "^1.0.0-beta.11"

**Comment by rafaelcorreiapoli** [comment]
I'm also facing the same problem in my app :(
Any ideas on how to solve this ?

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!

**Comment by MelodiiLy** [comment]
I have same issue. 'this.props.navigation.goBack()' in one of the StackNavigators doesn't do anything for me.
