### ISSUE TITLE
Navigating back from pre-built nested route

### ISSUE THREAD

**Issue by swellingt0n** [react-community/react-navigation#2419]
### Current Behavior
Navigating BACK via the navigation.goBack() or dispatching a NavigationActions.back() is not working correctly, when called after navigating to a nested route via a Redux reducer.

In my navigation reducer, i navigate the user 2 screens from the very first route.

Initial state:'Login'

Reducer code:
```
var homeAction = NavigationActions.navigate( {
    routeName: 'HomeNav',
    action: NavigationActions.navigate( { routeName: 'Page2' } )
} );
nextState = getStateForAction( homeAction, state);
```
Routers:
```
const Base = StackNavigator({
    'Login': { 
        screen: LoginScreen
    },
    'HomeNav': { 
        screen: Home
    },
    ...
    initialRoute: 'Login'
})
const Home = StackNavigator( {
    'Home': {
        screen: HomeScreen
    },
    'Page2': {
        screen: SecondPage
    },
    ...
    initialRoute: 'Home'
}
```
Navigating back from here happens in two ways*
* navigation.goBack(), navigation.goBack(null) navigation.goBack('Page2') - does nothing
* navigationActions.back(null), navigationActions.back({key: 'Page2'}) - Navigates back to the initial route

### Expected Behavior
* navigation.goBack(), navigation.goBack(null) navigation.goBack('Page2') - SHOULD navigate back to 'Home'
* navigationActions.back(null), navigationActions.back({key: 'Page2'}) - SHOULD navigate back to 'Home'

### Workaround
I have to fire a navigate action rather than back, which works in this circumstance but would not work in any other, as navigating back from the home screen logs the user out, and anywhere else it would absolutely mess up the stack.

### Your Environment
Both android and ios are affected

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.11
| react-native     |   .44

**Comment by spencercarli** [comment]
Could you put together a running example that demonstrates this issue? That way I (or someone else) can have some code to work off of. Thanks!

**Comment by swellingt0n** [comment]
@spencercarli Here is a basic repro: https://snack.expo.io/H1pdf_PuZ

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
