### ISSUE TITLE
C

### ISSUE THREAD

**Issue by carsonwah** [react-community/react-navigation#2422]
### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  
| react-native     |  
| node             | 
| npm or yarn      |

**Comment by matthamil** [comment]
Are you experiencing a bug or problem with React Navigation?

**Comment by carsonwah** [comment]
@matthamil Sorry i have already opened one. This issue should be an accident. You may delete it.

**Comment by matthamil** [comment]
No worries, it happens :)
