### ISSUE TITLE
DropdownAlert does not begin above the header

### ISSUE THREAD

**Issue by testshallpass** [react-community/react-navigation#2423]
- Original issue reported: https://github.com/testshallpass/react-native-dropdownalert/issues/73
- I sense the contents of a screen are rendered in container like:
```
<ReactNavigation> 
  <Header mode={'on'} /> 
  <MyScreen /> 
</ReactNavigation>
```
### Current Behavior
![dropdownalertstacknavigator](https://user-images.githubusercontent.com/7293079/29481615-4cd3edc4-8451-11e7-8b55-1a8e92e32bf7.png)

### Expected Behavior
It should start at the top of the screen and overlap the header. 

| software         | version
| ---------------- | -------
| react-navigation |  
| react-native     |  0.45.1
| node             | 6.9.1
| npm or yarn      | 3.10.10

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
