### ISSUE TITLE
How to remove Title (which appears beneath the icons) from Tab bar

### ISSUE THREAD

**Issue by Kudzai3** [react-community/react-navigation#2424]
static navigationOptions = {
        title: 'Camera',
        activeTintColor: Colors.tabIconSelected,
        inactiveTintColor : Colors.tabIconDefault,
        showLabel: false
  };

### Current Behavior

I tried the default expo client app with navigation and I cannot seem to be able to remove the title which appears underneath the label or even change its color. When I changed the color, only the icon color was changed but the title remains the same. How can I remove the title completely?
### Expected Behavior

I tried showLabel false but its not working, the options mentioned above only change the color of the icon not the title. (I would really love to remove it)

Are label and title the same thing? If not then how would I remove the title.
### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  ^1.0.0-beta.12
| react-native     |  https://github.com/expo/react-native/archive/sdk-19.0.0.tar.gz
| node             | 
| npm or yarn      |

**Comment by limichange** [comment]
try it.
```js
const MainScreenNavigator = TabNavigator([
  { screen: RecentChatsScreen },
  { screen: AllContactsScreen },
], {
  tabBarOptions: {
    showLabel: false
  }
});
```

**Comment by witalobenicio** [comment]
It's possible to remove label only for Android?

**Comment by piedrucci** [comment]
thanks so mucho @limichange

**Comment by Xdabier** [comment]
is it possible to remove the label for one tab only? because the solution mentioned by @limichange removes it for all the tabs.

**Comment by tobiastornros** [comment]
Try tabBarLabel and title in navigationOptions.

**Comment by Xdabier** [comment]
that actually doesn't do what I need, but I solved what I need in [this fork](https://github.com/Xdabier/react-navigation-tabs)

**Comment by Xdabier** [comment]
you can see  it's behavior in this video here
