### ISSUE TITLE
How can I disable Android's native back button under certain screen?

### ISSUE THREAD

**Issue by 2hyjun** [react-community/react-navigation#2425]
### Current Behavior

```javascript
import {
    Loading
} from '../config/router.js';

class App extends React.Component {
    render() {
        return (
            <Loading/>
        );
    }
}
```
**index.js**
```javascript
export const Auth = StackNavigator({
    Login: {
        screen: login
    },
    Main: {
        screen: MainTab,
    },
    Register: {
        screen: register,
    }
}, {
    headerMode: 'none',
    gesturesEnabled: false,
});

export const Loading = StackNavigator({
    Loading: {
        screen: loading,
    },
    AuthStack: {
        screen: Auth,
        navigationOptions: {
            gesturesEnabled: false,
        },
    },
}, {
    headerMode: 'none',
    gesturesEnabled: false,
});
```
**router.js**
When users start my app, Loading screen appears first. 
If user isn't signed, navigate to `Login` screen page.  
And then, all users navigate to `Main` Page.
I set `gesturesEnabled` as false, so on `IOS` users can not go back to previous page.
### Expected Behavior

But what I want is forbidding go back to previous page on `Android` with `hardware back button` not software back button.

How can I implement it?

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.11
| react-native     |  0.47.1
| node             |  8.2.1
| npm or yarn      | npm 5.3.0

**Comment by justinlok** [comment]
You must set backhandler event listener in your main container, usually app.js.
https://facebook.github.io/react-native/docs/backhandler.html

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!

**Comment by SirPhemmiey** [comment]
@2hyjun see __https://github.com/react-navigation/react-navigation/issues/1063#issuecomment-379477007

**Comment by Ritesh3011** [comment]
Login: {
        screen: login,
       header:null
    },
