### ISSUE TITLE
undefiend is not an object (evaluating 'navigation.state' ) 

### ISSUE THREAD

**Issue by TopGuo** [react-community/react-navigation#2426]
I modify the react-navigation of code so i meet the bug. It's undefiend is not an object (evaluating 'navigation.state' ) .
I want to modify the react-navigation of code because i need to listen tabBar, when i click the tabBar on TabNavigator.
Next i will show my code in here.

```js
//---------------------App.js------------------------------//
import React, { Component } from 'react';
import { Text, View, Image,StyleSheet,Platform } from 'react-native';

import {
    StackNavigator,
    TabNavigator
} from 'react-navigation';

import MineView from './controller/MineView';
import TargetView from './controller/TargetView';
import FindView from './controller/FindView';

const TargetIcon = require('./assets/home.png');
const FindIcon = require('./assets/msg.png');
const MyIcon = require('./assets/my.png');

const MyTabNavigator = TabNavigator({
    TargetView: {
        screen: TargetView,
        navigationOptions: () => tabOption('目标', TargetIcon, TargetIcon),
    },
    FindView: {
        screen: FindView,
        navigationOptions: () => tabOption('发现', FindIcon, FindIcon),
    },
    MineView: {
        screen: MineView,
        navigationOptions: () => tabOption('我的', MyIcon, MyIcon),
    },
},
    {
        //----------------------
        tabBarPosition: 'bottom',//显示在底部 android默认显示在顶部
        swipeEnabled: false,//禁止滑动
        animationEnabled: false,//切换页面时不显示动画
        backBehavior: 'none',//按住 back键 是否返回第一个tab
        lazy: true,//延迟加载
        tabBarOptions: {
            labelStyle: {
                margin: 2,
                paddingTop: 5,
                fontSize: 16,//z字体大小
            },
            iconStyle: {
                marginTop:5,
                height: 45,
                width: 35,
            },
            style: {
                height: 69,
                backgroundColor: 'white'//tabbar 背景色
            },
            activeBackgroundColor: 'white',
            activeTintColor: '#FF3344',
            inactiveBackgroundColor: 'white',
            inactiveTintColor: '#aaa',
            showIcon: true,
            showLabel: false,
            pressOpacity: 0.3,//透明度
            indicatorStyle: {
                height: 0,
            }
        },

    }

);

const App = StackNavigator({
    MyTabNavigator: {
        screen: MyTabNavigator
    }

});

const tabOption = (tabBarTitle, normalImage, selectedImage) => {
    const tabBarLabel = tabBarTitle;
    const tabBarIcon = (({ tintColor, focused }) => {
        return (
            <View style={styles.tabImg}>
                <Image
                    source={!focused ? normalImage : selectedImage}
                    style={[styles.icon, { tintColor: tintColor }]}
                />
                <Text style={{ color: focused ? '#FF3344' : '#43484d' }}>{tabBarTitle}</Text>
            </View>
        )
    });
    const headerTitleStyle = { fontSize: (Platform.OS === 'ios') ? 20 : 24, color: 'white', alignSelf: 'center' };
    const tabBarVisible = true;
    return { tabBarLabel, tabBarIcon, headerTitleStyle, tabBarVisible };
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#fff'
    },
    icon: {
        height: 22,
        width: 22,
        resizeMode: 'contain'
    }
});

export default App;

//---------------------FindView .js------------------------------//
//import liraries
import React, { Component } from 'react';
import { View, Text, StyleSheet,TouchableOpacity } from 'react-native';

// create a component
class FindView extends Component {
    render() {
        return (
            <View style={styles.container}>
                <Text>FindView</Text>
            </View>
        );
    }
}

// define your styles
const styles = StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#2c3e50',
    },
});

//make this component available to the app
export default FindView;


//-------------------------------MineView.js------------------//
//import liraries
import React, { Component } from 'react';
import { View, Text, StyleSheet,TouchableOpacity } from 'react-native';

// create a component
class MineView extends Component {
    render() {
        return (
            <View style={styles.container}>
                <Text>MineView</Text>
            </View>
        );
    }
}

// define your styles
const styles = StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#2c3e50',
    },
});

//make this component available to the app
export default MineView;


//---------------------------TargetView.js-------------------//
//import liraries
import React, { Component } from 'react';
import { View, Text, StyleSheet,TouchableOpacity } from 'react-native';

// create a component
class TargetView extends Component {
    render() {
        return (
            <View style={styles.container}>
                <Text>TargetView</Text>
            </View>
        );
    }
}

// define your styles
const styles = StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#2c3e50',
    },
});

//make this component available to the app
export default TargetView;
```

**Comment by maxisawesome** [comment]
I have a similar issue, but I'm importing StackNavigator. I'm using the same code as found in the tutorial here: https://reactnavigation.org/docs/intro/
`import React from 'react';
import {
  AppRegistry,
  Text,
} from 'react-native';
import StackNavigator from 'react-navigation'; //'react-navigation/lib/react-navigation.js';

class HomeScreen extends React.Component {
  static navigationOptions = {
    title: 'Welcome',
  };
  render() {
    return <Text>Hello, Navigation!</Text>;
  }
}

const stackNav = StackNavigator({
  Home: { screen: HomeScreen }
});

`

I'm getting an error code that reads
`
Object is not a function (evaluating '(0, _reactNavigation2.default)({
  Home: { screen: HomeScreen }
})')

` 
Looks like StackNavigation isn't importing right, so the compiler sees StackNavigator as an object and gets confused? I've seen posts saying  change `import StackNavigator from 'react-navigation';` to `import { StackNavigator } from 'react-navigation';`, but I've also seen posts saying to change it from having brackets to not having brackets hahaha. When I add the brackets, the compiler gives me a different error, complaining about how a string should follow import not an object. I'm caught in a catch 22.

**Comment by TopGuo** [comment]
Now,are you OK? We shouldn't think it's the same problem.

**Comment by matthamil** [comment]
@maxisawesome in your code, you are not returning valid JSX. The `render()` method should look something like 

```jsx
return (
  <Text>Hello, Navigation!</Text>
);
```

otherwise your `render`'s `return` value is evaluated and it can't find a component/object/function/anything called `Hello`.

**Comment by matthamil** [comment]
@TopGuo can you provide the full stack trace? I don't see where you are accessing `navigation.state` in your code sample. You mentioned that you modified `react-navigation`-- did you modify the source or modify an existing example?

**Comment by matthamil** [comment]
@maxisawesome Are you using `AppRegistry` in your code, i.e. is your RN app registered? Is this the full code-snippet? The import should be `import { StackNavigator } from 'react-navigation';`

**Comment by TopGuo** [comment]
@matthamil Yes,I had modified the source.

**Comment by matthamil** [comment]
@TopGuo Can you post a link to your forked repo? I think this is a question better suited for [Reactiflux (#react-navigation)](https://discord.gg/reactiflux) since this isn't a question about this repo.

**Comment by TopGuo** [comment]
It's so sorry .I couldn't upload my red box of picture. I refer to this article modified my source code. link: https://github.com/kimdhoe/react-navigation/commit/f120c72af57d1a6b406a32c692deb6d3999d92ef#diff-6f52f52094e1001dd754981e92d9f933

**Comment by TopGuo** [comment]
In fact,I only want to listen the tabbar on tabnavigator when i click some tabbar. but the React navigation's official website didn't provide the way to realize it.

**Comment by TopGuo** [comment]
In fact,I only want to listen the tabbar on tabnavigator when i click some tabbar. but the React navigation's official website didn't provide the way to realize it. @matthamil

**Comment by TopGuo** [comment]
It's so sorry .I couldn't upload my red box of picture. I refer to this article modified my source code. link: kimdhoe/react-navigation@f120c72#diff-6f52f52094e1001dd754981e92d9f933 @matthamil

**Comment by matthamil** [comment]
That PR is from an older version of react-navigation. The `navigationState` prop is no longer supported. It is now `navigation`: https://github.com/react-community/react-navigation/blob/5e075e1c31d5e6192f2532a815b1737fa27ed65b/src/views/TabView/TabBarBottom.js#L32

**Comment by TopGuo** [comment]
OK,Are there any other places that need to  modify? @matthamil        ...I want a solution.

**Comment by matthamil** [comment]
You might need to do a `git diff` between that branch and the current branch to find everything that has changed.

I am closing this issue since it is related to an old PR.

**Comment by TopGuo** [comment]
OK. Thank you very much.

**Comment by maxisawesome** [comment]
@matthamil my bad, formatting is my weak point. 
That is the full code snippet. Using ` import { StackNavigator } from 'react-navigation'; ` gives me "Element type is invalid: expected a string (for built in components) or a class/function (for composite components) but got: object. You likely forgot to export your component from the file it's defined in.

**Comment by matthamil** [comment]
@maxisawesome Are you using CRNA? Try `export default stackNav;` at the bottom. If the issue persists, please open a new issue :)

**Comment by maxisawesome** [comment]
@matthamil that worked!! Thanks. I assume that's "create-react-native-app"? If so yes.
