### ISSUE TITLE
Question: How to navigate nested navigator (wrapped by a component)

### ISSUE THREAD

**Issue by Tom29** [react-community/react-navigation#2427]
I read on the docs about navigating nested screen https://reactnavigation.org/docs/navigators/navigation-actions#SetParams
However, my nested navigator is wrapped by a component

`module.exports = class _ extends React.Component { ... }`

not

`module.exports = StackNavigator({})`

So how do i do it? 
I've tried `componentDidUpdate` to catch `navigate` event from its parent but didn't work.

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!

**Comment by kashishgrover** [comment]
Instead of simply closing the issue, won't it be better to link to an issue you create on these channels? Don't answer them here but at least provide a link so that the user can still track any update. :/
