### ISSUE TITLE
animation item drawer

### ISSUE THREAD

**Issue by mynameisbams** [react-community/react-navigation#2429]
how to remove animation when click item on drawer item?

when i click item on drawer its need 1-2 second to go to other screen... i test in real device. This is very disturbing

**Comment by kholiavko-roman** [comment]
I have the same issue on android. When I tapped on drawer item, it change screen only after delay. On ios I don't saw this problem.

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
