### ISSUE TITLE
Multi Line Header

### ISSUE THREAD

**Issue by rtman** [react-community/react-navigation#2430]
Hi,

I would like to be able to have a multiline header in the following format:

Name //larger font
Company Name //smaller font

I've tried adding a custom header but I can't quite get it working, the documentation isn't very clear on this.

How would one go about having a multi line header, keeping the back button and everything else as is?

Thanks

**Comment by bjrn** [comment]
At this stage, I'd suggest you take a look at the implementation of [Header.js](https://github.com/react-community/react-navigation/blob/master/src/views/Header/Header.js)

It seems (by looking at the [**source code**](https://github.com/react-community/react-navigation/blob/master/src/views/Header/Header.js#L85-L89)) that passing a custom component to the `headerTitle` prop in the scene would allow you to override just the title part of the header component, leaving backButton and rightButtons etc. as-is. 

There seems to be some issues regarding the behaviour and overridability of different props: https://github.com/react-community/react-navigation/issues/2132

I've made a quick expo example for a basic implementation: https://snack.expo.io/Sydk-FD_W
There are some severe styling differences between iOS and Android, but maybe you can use it as a starting point at least

**Comment by spencercarli** [comment]
Hi @rtman this is likely a question better suited for StackOverflow (since it's not a bug/feature request). That being said @bjrn provided a very detailed and valuable response so be sure to check that out (thanks @bjrn)!

**Comment by rtman** [comment]
Hi @bjrn , sorry I got caught up in another thing yesterday.

Thanks for the detailed response!! I will work on implementing this now.

@spencercarli I understand, my issue is that the documentation isn't clear about custom headers which is why I chose to post here. Also I have found a lot of information regarding old versions of react-navigation online that doesn't work anymore due to refactoring.

**Comment by rtman** [comment]
@bjrn This worked great thanks!

For future reference here is what I did (this is after declaring a tab navigator called ChatScreenNavigator):

`const CustomHeader = ({ title, subtitle }) => (
  <View style={styles.headerContainer}>
    <Text style={styles.headerTitle}>{title}</Text>
    <Text style={styles.headerSubtitle}>{subtitle}</Text>
  </View>
);

ChatScreenNavigator.navigationOptions = ({navigation, title, subtitle }) => ({
    headerTitle: <CustomHeader title={navigation.state.params.friend.name} subtitle={navigation.state.params.friend.companyName}/>,
});`

I followed the styles in the header.js file for react-navigation and it looks great.

**Comment by bjrn** [comment]
Good to hear that it worked out - maybe the solution you ended up with could be added to the playground examples? Agree that it can be hard to find solutions that are valid for recent versions of react-navigation, and also due to the fact that solutions often look very different depending on whether the responding person is using the library with Redux or passing down props.navigation...

**Comment by brayanL** [comment]
I am using Native Base Header Component is awesome:  [https://docs.nativebase.io/Components.html#header-title-subtitle-headref](url)

**Comment by buzzb0x** [comment]
Closed since long but it would be much easier if the HeaderTitle component was exported and accessible to use.

**Comment by kumarutsav111** [comment]
i used this for multiple lines healder and it works:
import { createStackNavigator } from "react-navigation-stack";
const CustomHeader = ({ title, subtitle }) => (
  <View style={[ {flexGrow: 1, } ]} >
    <Text allowFontScaling={false}
      style={{ flexGrow: 1, fontSize: title.length >=27 ?15:22, }} >
      {title}  </Text> </View>
);
const AppStack = createStackNavigator({
  tabs: {  screen: TabNavigator,
    tabBarOptions: { allowFontScaling: false },
    navigationOptions: ({ navigation, screenProps }) => ({
      allowFontScaling: false,
      headerTitleAllowFontScaling: false,
      headerTitle: ()=>
        <CustomHeader
          title={navigation.state.params.title}
        />,
      headerStyle: {
        backgroundColor: "#01AEEF",
        elevation: 0,
        shadowOpacity: 0
      },
      headerLeft: ()=> <ActionBarImage />,
      headerTintColor: "#333333",
      headerTitleStyle: {
        width: "75%",
        textAlign: "center",
        alignSelf: "center" } })
  },
  Survey: Survey,
  Consents: Consents,
});
