### ISSUE TITLE
How to disable TabNavigator gestures?

### ISSUE THREAD

**Issue by limichange** [react-community/react-navigation#2431]
How to disable TabNavigator gestures? In the StackNavigator, I can set `gesturesEnabled: false`, but how to do this in the TabNavigator? I just want it can't go back.

```
# now:
Login ---> Index(tab)
Login <--- Index(tab)

# expect:
Login ---> Index(tab)
Login <-x- Index(tab)
```

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
