### ISSUE TITLE
Back button is taking space in header bar

### ISSUE THREAD

**Issue by ajaysaini-sgvu** [react-community/react-navigation#2432]
I am trying to set header title in center and remove back button space. I tried by changing navigationOptions

```
navigationOptions: {
    headerLeft: null,
    headerTitleStyle: { alignSelf: "center" }
} 
```

It set header in center and hide the icon but icon keeps taking space of back button so header title is not 100% centered. Any work around for this issue ?

![screenshot](https://user-images.githubusercontent.com/2501024/29497227-305bc740-8602-11e7-97b6-e4801d899347.png)

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
