### ISSUE TITLE
how to set navigationOptions params by mapStateToProps to react-redux connect?

### ISSUE THREAD

**Issue by yjchen920927** [react-community/react-navigation#2435]
### Current Behavior
for example:
import Icon from 'react-native-vector-icons/Ionicons';
function mapStateToProps(store, props) {
    return {
        mainThemeColor: store.settingState.mainThemeColor,
    }
}
class HomeScreen extends Component {
    static navigationOptions = ({navigation}) => {
        return {
            tabBarVisible: true,
            headerTitle: 'Home',
            tabBarLabel: 'Home',
           headerStyle: {
            backgroundColor: this.props.mainThemeColor
        },
        }

    };
...
}

how to set navigationOptions params  {backgroundColor: this.props.mainThemeColor} by mapStateToProps to react-redux connect value?

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |1.0.0-beta.11
| react-native     |0.46
| node             |7.10.0
| npm or yarn      | 4.2.0

**Comment by mantas-janulionis** [comment]
One of possible ways to achieve that would be using `screenProps` https://reactnavigation.org/docs/navigators/navigation-options .
You have to connect the parent to the redux store and pass whatever you want via this parameter.

```
class MainNavigator = StackNavigator({
   mainScreen: {
    screen: MainScreen
  }
});

//---------------//
class RootComponent extends React.Component {
  render() {
    <MainNavigator screenProps={{myProp: this.props.myProp}} />
  }
}

const mapStateToProps = (state) => ({
  myProp: // map your prop here
});

export default connect(mapStateToProps)(RootComponent);

//---------------//
class MainScreen extends React.Component {
  static navigationOptions = ({screenProps}) => ({
    // access screenProps.myProp here
  })
  render() {
    // ...
  }
}
```

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!

**Comment by bartoszgolebiowski** [comment]
@mantas-janulionis
Your solution works, Thanks! :)
