### ISSUE TITLE
Same Background for 2 Components

### ISSUE THREAD

**Issue by wvicioso** [react-community/react-navigation#2438]
I'm not sure how to implement this with react-navigation.

I want to navigate between 2 components while keeping a background image static. So the content would move over the single background image. How can I do this/is it possible?

Thanks

**Comment by stereodenis** [comment]
@wvicioso you can do it with ScrollView + pagingEnabled

**Comment by wvicioso** [comment]
@stereodenis Thanks. I was trying to avoid doing it this way.

**Comment by spencercarli** [comment]
Hey @wvicioso this question is probably better suited for StackOverflow so I'm going to close this.

For what it's worth I typically do what @stereodenis suggested.
