### ISSUE TITLE
How to listen tabBar when i used tabNavigator

### ISSUE THREAD

**Issue by TopGuo** [react-community/react-navigation#2442]
//----------------------------
How to listen tabBar when i used tabNavigator?
I want to listen the tabBar when i click the tabBar on tabNavigator.

//----------------------------
Pressing a tab bar often requires some kind of side effects other than
navigation to be performed. This PR will allow a screen accept
`onTabPress` callback as an option. It will be invoked exactly once on
every press on the screen's corresponding tab button, receiving a
`TabScene` object as an argument.

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
