### ISSUE TITLE
dynamic navigationOptions not working in TabNavigator

### ISSUE THREAD

**Issue by Pustelto** [react-community/react-navigation#2443]
Hi, I'm using TabNavigator and I have issues with using function as navigationOptions param. I have checked docs, other issues and StackOverflow but with no success. Details below, any help is appreciated.

### Current Behavior
- My components look like this:
```js
const EventNavigator = TabNavigator(
  {
    Event: {
      screen: Home,
    },
    Schedule: {
      screen: ScheduleComponent,
    },
    Notifications: {
      screen: NotificationsPage,
    },
    PromoCodes: {
      screen: PromoCodesPage,
    },
  }
)

// Here I render Tab navigator defined above
class EventPage extends React.PureComponent {
  props: EventPageProps;

  render() {
    const { dropdownOpen, closeDropdown } = this.props

    return (
      <View style={style.col}>
        <EventNavigator
          screenProps={{ rootNavigation: this.props.navigation }}
        />

        <MenuDropdown
          isOpen={dropdownOpen === "APP_MENU"}
          onClose={closeDropdown}
        />

        <FiltersDropdown
          isOpen={dropdownOpen === "FILTERS"}
          onClose={closeDropdown}
        />
      </View>
    )
  }
}
```

And this is Home component:

```js
class EventFrontPage extends React.Component {
  static navigationOptions = ({ navigation, screenProps }) => {
    console.log("NAV OPTIONS PROPS", props)

    return ({
      tabBarLabel: "Home",
      tabBarIcon: (iconprops) => {
        console.log(props);
        return (<GeIcon
          name="home"
          size={20}
          style={{ width: 24, height: 24, color: iconprops.tintColor }}
        />)
      },

    })
  };
  ...
```
__Note__: console logs were here to help me debug the issue, but they are not called as well, as if entire navigationOptions method is not called.

I have double check everything and it looks good, but so far I have no success in making this work.

### Expected Behavior
- navigationOptions method should be run and config should be changed based on returned object.

### Your Environment
- _Include as many relevant details about the environment you experienced the bug in_

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.12
| react-native     | 0.44.2
| node             | 6.7.0
| npm or yarn      | 0.21.3

**Comment by sonbuiGFD** [comment]
I have the same issue as your @Pustelto 
I've tried console log like your demo and got nothing.
I use:  
- react-navigation: 1.0.0-beta.11,
- react-native: 0.47.1

**Comment by kelset** [comment]
Pinging OP @Pustelto since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open; if I get no answer in the next 7 days I will close it.

Moreover I suggest you take a look at this issue for how to implement dynamic options: https://github.com/react-community/react-navigation/issues/2818

**Comment by Pustelto** [comment]
Hi thanks for the info. I'm not sure when I will be able to check this properly. Therefore you can close the issue for now. I will test it later on (and the solution in #2818) and in the worst case re-open the issue again. 

Are you ok with this?

**Comment by kelset** [comment]
Perfect 👌
