### ISSUE TITLE
Overflow menu in the header shown underneath the tab bars  in Android

### ISSUE THREAD

**Issue by pongponglau** [react-community/react-navigation#2444]
I have an overflow menu as header above the tab bar. It is shown beneath the tab bar but not on top of it. May i ask if there is any solution?

Thanks a lot

**Comment by spencercarli** [comment]
Can you provide a demo of this?

**Comment by vonovak** [comment]
Since the issue has been inactive for a long time, I'm closing it. It also seems like a usage question better suited for SO, along with a repro.
