### ISSUE TITLE
Cannot get the scrollEnabled working on UWP

### ISSUE THREAD

**Issue by ballySingh** [react-community/react-navigation#2448]
### Current Behavior
Before I start, I am trying to build an app that works on all platforms, Android, iOS and UWP wish me luck!.

I have added the TabNavigator code in my app and it appears on all devices, Great:

const HomeTabsNav = TabNavigator({
    Location: { screen: GeolocationExample},
    Messages: {screen: MessagesScreen},
    Chat: { screen: ChatScreen},
    Messages1: {screen: MessagesScreen},
},{
    tabBarPosition  : 'top' ,
    tabBarComponent: TabBarTop,
    swipeEnabled: true,
    tabBarOptions: {
        scrollEnabled: true,
    },
});

But I cannot get the scrollEnabled working on UWP, Messages1 cannot be clicked.

![image](https://user-images.githubusercontent.com/30837072/29609823-3bdf1cee-87f0-11e7-8fb9-e3511a3d4e83.png)

### Expected Behavior
What I am expecting is with the scrollEnabled set to true. Then user will be able to scroll the tabs and be able to select 'Messages1' tab.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^1.0.0-beta.11
| react-native     | 0.47.1
| node             | v8.2.1
| npm      | 5.3.0
| react-native-windows | ^0.47.0-rc.5

**Comment by spencercarli** [comment]
Is there a way to run on UWP without having a device? Could you provide a demo of this issue?

**Comment by ballySingh** [comment]
@spencercarli apologies but I've come across another issue which relates to the initial issue, I have no idea why it was working before but I'm seeing this now.

![image](https://user-images.githubusercontent.com/30837072/29655837-3442bb52-88aa-11e7-94e1-fbb50bb26c31.png)

I've solved the issue by adding the width to the styles and the tab, as you can see below.

    tabBarOptions: {
        scrollEnabled: true,
         style: {
            backgroundColor: '#000',
            width: 1000,
            height: 50
        },
          tabStyle: {
            width: 125,
            height: 50
        },
    },

But I still cannot get it to scroll and I have a feeling adding a width will never work with scrolledEnable.

Regarding your question, I believe you're asking me if I have tried this on an emulator or local and the answer is yes.

I placed a demo on my github account:

https://github.com/ballySingh/TabNavUWP.git

**Comment by ballySingh** [comment]
Updated the git repo, please let know if there are any issues

**Comment by Noitidart** [comment]
I think scrolling horizontally in ScrollView's on UWP are a bug on the react-native-windows side - https://github.com/Microsoft/react-native-windows/issues/1072

**Comment by kelset** [comment]
Pinging OP @ballySingh since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open; if I get no answer in the next 7 days I will close it.

Moreover I think @Noitidart is right, but since the issue that he links is still open I am not sure :(

**Comment by ballySingh** [comment]
please feel free to close this issue. thanks
