### ISSUE TITLE
Collapsing header with background image

### ISSUE THREAD

**Issue by StefanWegener** [react-community/react-navigation#245]
Hi,

first of all: great framework. I think this could be the navigation framework for the future of react native.

But I have a question about styling the header:

Is it possible to create a collapsing header with a search bar an maybe a background image, which collapse when we scroll inside of the scene? (like the iOS header of airbnb)

**Comment by grabbou** [comment]
We've been trying to implement such thing recently and had a debate with @satya164 regarding that. I think it's not possible with the standard header, but as soon as you provide your own component - why not? All in all with e.g. `headerMode: screen`, you should be able to add a custom one w/o compromising on animations.

With `headerMode: float`, that may become a bit more complex.

**Comment by spencercarli** [comment]
Hi! I'm going to go ahead and close this since it hasn't been updated in a while. Thanks for understanding!
