### ISSUE TITLE
Do not add duplicate when navigating to current route

### ISSUE THREAD

**Issue by pensierinmusica** [react-community/react-navigation#2450]
Imagine the Stack Navigator is in a route called `Test`.

If I invoke:

```js
navigator.navigate('Test');
```

The navigator will push a new view to the stack, with the same route. This seems like a bug / bad feature to me. Imho since we're already in that route nothing should happen instead.

The same concept probably applies to Tab Navigator.

Thoughts?

**Comment by matthamil** [comment]
Tab Navigator actions are idempotent. If you navigate to the same route with new params, the route is modified in place in the navigation history. If you navigate to the same route within a StackNavigator, you do not have idempotent pushes. Currently, you have to manually manage this.

This is a known issue. https://github.com/react-community/react-navigation/issues/135
