### ISSUE TITLE
TabNavigator `path` redux 

### ISSUE THREAD

**Issue by carloscuesta** [react-community/react-navigation#2452]
### Current Behavior

I'm using a `TabNavigator` as a top level navigator. All the state is managed through Redux.

I've downloaded the [ReduxExample](https://github.com/react-community/react-navigation/tree/master/examples/ReduxExample) and modified it to use a `TabNavigator` adding the `path` as a Route Config in order to be able to use the **deeplink** feature. 

```javascript
export const AppNavigator = TabNavigator({
  Login: { screen: LoginScreen, path: '/login' },
  Main: { screen: MainScreen, path: '/main' },
  Profile: { screen: ProfileScreen, path: '/profile' },
});
```

Then I've updated the reducer to use the provided `path`.

```
const firstAction = AppNavigator.router.getActionForPathAndParams('/main');
const secondAction = AppNavigator.router.getActionForPathAndParams('/login');
```

As you can see the app throws the following error. And I don't know if I'm missing something but if I use this example with a `StackNavigator` instead of `TabNavigator` everything works.

![screen shot 2017-08-23 at 15 09 52](https://user-images.githubusercontent.com/7629661/29617433-254391e8-8815-11e7-938b-50018fb184ca.png)

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.11
| react-native     | 0.44.0 & 0.47
| node             | 6.11.1
| npm       | 3.10.10

**Comment by carloscuesta** [comment]
Looks like the problem is using `/` in paths, then, how it's possible to define a "root" or "/" path?

**Comment by spencercarli** [comment]
Perhaps getting the root path would just be passing an empty string (I'm not familiar with that code so I'm not sure). This could be a possible enhancement (either in code or at least the docs). To make sure we can best do that a running example of this issue would be very useful!

Thanks!

**Comment by carloscuesta** [comment]
@spencercarli 

Thanks for your quick response! Here's the example repo https://github.com/carloscuesta/react-navigation/tree/master/examples/ReduxExample

**Comment by kelset** [comment]
Pinging OP @carloscuesta since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open because it still happens in latest version; if I get no answer in the next 7 days I will close it.
