### ISSUE TITLE
How are we supposed to set this up when we don't use an EXPO project?

### ISSUE THREAD

**Issue by limeytrader007** [react-community/react-navigation#2453]
Your example illustrates the assumption that the user has an App.js file built from
Expo.

How do we use the DrawerNavigator when we have index.ios.js and index.android.js?
All I get is Native module cannot be null.

Thanks

**Comment by matthamil** [comment]
Let those files, `index.ios.js` and `index.android.js` render a component which eventually renders your navigator, or render your navigator directly inside the `render()` method of your root component. Navigators are React components and can be rendered like any other component.
