### ISSUE TITLE
how I can replace screen?

### ISSUE THREAD

**Issue by wuyunqiang** [react-community/react-navigation#2459]
### Current Behavior
I navigate A->B->C 
I want use C replace B how I can do.
I seacrh in stackoverflow and I not found answer.

| software         | version
| ---------------- | -------
| react-navigation | ^1.0.0-beta.11
| react-native     | 0.46.4
| node             |v8.3.0
| npm or yarn      | yarn 0.27.5

**Comment by kokiy** [comment]
i also meet this question

**Comment by justinlok** [comment]
https://medium.com/handlebar-labs/replace-a-screen-using-react-navigation-a503eab207eb
#295

**Comment by nirpeled** [comment]
Check out https://medium.com/handlebar-labs/replace-a-screen-using-react-navigation-a503eab207eb

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
