### ISSUE TITLE
Drawer under Stack Navigator always show header?

### ISSUE THREAD

**Issue by thiennhank9** [react-community/react-navigation#2460]
Hey guys, I don't know how to disable header of drawer navigation when it's under a Stack navigator
My code look like this

```
export const draw = DrawerNavigator(
    {
        Login: { screen: Login },
        ChatView: { screen: ChatView },
        ListViewDone: { screen: ListViewDone },
        Side: { screen: Side }
    },
    {
        headerMode: 'screen',
        drawerPosition: 'right',
        contentComponent: Side
    }
)

}, navigationOptions:{ header: { visible: false } });
export const stack = StackNavigator(
    {
        Login: { screen: Login },
        draw: { screen: draw },
        Side: { screen: Side }
    },
    {
        headerMode: 'screen',
    }
)
```

But whenever open the drawer, it always shows header. Although I set header be null all components like this.

```
static navigationOptions = {
        header: null,
    };

```
Simply, every scenes and components don't have any header on top, I disabled it all.
But only open drawer, it always shows header.

This is how it looks like:
[https://ibb.co/hCwG6k](url)

**Comment by thiennhank9** [comment]
Oh I solved it by my self, it's quite simple!
Just hit following code to set header of draw (Drawer Navigation) be null

```
draw.navigationOptions = {
    header: null
}
```
Hope this is can be useful to someone!

**Comment by xerotolerant** [comment]
Hey, I'm trying to do the reverse of what you are doing. I want the header to show on the child screen but not on the menu itself. Or rather, when the menu is showing the header is showing as blank for some reason.

You solution allows me to hide it in both places but I really want to hide it on the  menu (or rather not show an additional, blank one).

Have you dealt with this use case?

**Comment by yasir-netlinks** [comment]
@thiennhank9  hi there, can you please elaborate what you did ! I trying to have the drawer to be displayed without header / above header. Is it possible that some screens in the `drawer` have headers, so when opening drawer it would be displayed above that header's screen!

**Comment by Dror-Bar** [comment]
> Just After I wrote this I solved it in a sense. I'm displaying the same thing on both the menu navbar and the the child component nav bar. Not perfect but workable.

Not very useful if you have different / dynamic headers in the child components.

**Comment by pinchez254** [comment]
just pass this prop if your working with combined navigations
Drawer: {
      screen: Drawer,
      navigationOptions: {
        header: null,
      },
    },

**Comment by satyadaraviteja** [comment]
> just pass this prop if your working with combined navigations
> Drawer: {
> screen: Drawer,
> navigationOptions: {
> header: null,
> },
> },

nice man...struggled a lot to fix this one...
