### ISSUE TITLE
Refresh/Reset Router

### ISSUE THREAD

**Issue by anishtr4** [react-community/react-navigation#2462]
I have a router/component with following code.
const {
        checkedSignIn,
        isSignedIn,

        redirectTo
    } = this.props.screenProps;

    const navigation = this.props.navigation;

    if (isSignedIn) {
        const obj = Object.assign({}, this.props, this.props.screenProps);
        return (
            <DashboardTabComponent
                 //navigation={navigation}
                //  screenProps={this.props.screenProps}
                screenProps={obj}
            />
        );
    } else {
        return (
            <HomeScreen
                 navigation={navigation}
                 screenProps={this.props.screenProps}
            />
        );
    }

And inside 'DashboardTabComponent' in one of the tab I have sign out button. when I press sign out button it should re-render this component so that it can show Home screen.

**Comment by spencercarli** [comment]
This question would probably be better suited for StackOverflow.
