### ISSUE TITLE
Change cardStyle dynamically

### ISSUE THREAD

**Issue by Noitidart** [react-community/react-navigation#2465]
I have a `<StackNavigator>` that I creaet with `cardStyle` of transparent background. Later, I would like to make this an opaque background. Is this possible? I tried re-mounting the navigator with seperate options for a solid background, but it caused a flicker. Is there anyway to do a `setState` thing here?

The reason why I load transparent navigator is because, I have a native splash screen, which has an image. When my navigator loads I have the same image in the same exact spot. If the background is not transparent there is a flicker as the image is rendered after a second after the opaque background is. I am loading a native image so there is practically 0 load time, but there is still a flicker.

**Comment by spencercarli** [comment]
I think this is more of an issue with how your app is configured. I would suggest checking out react-native-splash-screen to aid in this situation
