### ISSUE TITLE
Screen custom params

### ISSUE THREAD

**Issue by leesolway** [react-community/react-navigation#2466]
How would would you pass a custom param or callbacks from a screen to the tab container? 

Thanks for the help.

**Comment by JulianKingman** [comment]
You mean like `this.props.navigation.navigate('SomeRouteInATabNavigator', {customParam: 'sry, no callbacks'})`? You can also use [screenProps](https://reactnavigation.org/docs/navigators/tab#Navigator-Props)

**Comment by leesolway** [comment]
Not exactly.. 
I want to do it from within a screen.. I would assume somewhere navigationOptions.

**Comment by leesolway** [comment]
@JulianKingman I would like the screen to be able to pass props to the TabBar, in the same way an TabIcon or TabTitle is set. I would like custom params, to be used in a custom TabBar component.

**Comment by JulianKingman** [comment]
See if screenProps will work for you.

Do you have an example of what you're trying to do? It sounds like you're trying to pass data the wrong way, or at least in a way that's not normal/easy.

**Comment by leesolway** [comment]
Yea @JulianKingman  it may be the wrong way, but the TabTitle and TabIcon shows it is an established pattern. 

Basically i want a dynamic button that can fire actions in context of the screen. Not specifically navigation actions, other ones like save, or invite. The actions and title for this new button need to come from the screen they are rendered on.

**Comment by JulianKingman** [comment]
It sounds like something better suited to plain old redux, not something that should be connected directly to the TabNavigator. If you have a real-life example, I can maybe give you an idea on how to approach it.

**Comment by leesolway** [comment]
I was thinking of using Redux, but the "guideline" is to not pass no serialisable data (in my case, a callback) into the store. 

I'll build a stand alone example tomorrow, to demo the problem. I appreciated the help @JulianKingman .

**Comment by leesolway** [comment]
@JulianKingman https://github.com/leesolway/react-navigation-tabs  is the example.

Within the TabBarBottom component, i want to be able to change the title, and attach a callback to the button with the text "Custom Text here"

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!

**Comment by JulianKingman** [comment]
Oh, I think I get what you're saying. You want the tab label to be dynamic, and you want it to perform a custom function. Is that right? For the first part, you can pass a label through ScreenProps, for the second part it's a little tricker, but there is some discussion on it here: https://github.com/react-community/react-navigation/pull/1335
