### ISSUE TITLE
Reset flashes previous screens in StackNavigator

### ISSUE THREAD

**Issue by Cygnus2112** [react-community/react-navigation#2467]
### Current Behavior
When I use NavigationsActions.reset(), the display cycles through all the previous screens before it lands on its intended destination, as if it's pressing the back button in rapid succession.

My code looks like this: 

```
const MyApp = StackNavigator({
 Home: {
    screen: HomeScreen,
  },
  Screen1: {
    screen: Screen1,
  },
  Screen2: {
    screen: Screen2,
  },
  Screen3: {
    screen: Screen3
  },
  Screen4: {
    screen: Screen4,
  }
},
  { headerMode: 'screen' }
);
```

On Screen4, I am calling reset() like this:

```
let resetNav = NavigationActions.reset({
  index: 0,
  actions: [
      NavigationActions.navigate({routeName: 'Home'})
  ]
})

this.props.navigation.dispatch(resetNav);
```

At which point it cycles quickly through Screen3 --> Screen2 --> Screen1 --> Home.

### Expected Behavior

I would like it to simply go from Screen4 to Home, as if I were calling `this.props.navigation.navigate('Home')`.

Is there something I'm missing? Any help would be appreciated. 

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.12
| react-native     |  0.44.2
| node             |  8.2.1
| npm or yarn      | npm 5.3.0

**Comment by JulianKingman** [comment]
This has been posted a few times before. I recommend closing this issue and following the issue here: https://github.com/react-community/react-navigation/issues/2084 and here: https://github.com/react-community/react-navigation/issues/1493

Next time do a quick search before posting ;)

**Comment by Cygnus2112** [comment]
I did ample searches, but neglected to try queries in Mandarin. My bad!

**Comment by JulianKingman** [comment]
Huh. I just searched "reset flash" and they came right up.

**Comment by Cygnus2112** [comment]
> Huh. I just searched "reset flash" and they came right up.

That's great!
