### ISSUE TITLE
Expo seems to block case this.props.naviagtion

### ISSUE THREAD

**Issue by dekm** [react-community/react-navigation#2468]
I'm trying to navigate to a stack screen from within another screen.  Everything appears to be setup correctly.  I've tried two methods to navigate first redux and my Appnavigator doesnt received the state change.  

Next I tried using props.navigation
const {navigate} = this.props.navigation;

then calling my screen
this.navigate('SearchMeds')

Here i get a this.props.navigation is undefined.  I'm pretty sure this is because Expo isnt allowing the props through for some reason as I had the same issue with redux.

Does anyone know a way around this when using expo?

**Comment by spencercarli** [comment]
Please provide a reproduction of this issue and I'll reopen. Thanks!

**Comment by dekm** [comment]
What I'm trying to figure out is how this.props.navigation is passed into the screens.

My stack looks like this
`const HomeStack = StackNavigator({
    Home: { screen: TabNavigator({
    ScreenOne: { screen: Home },
    ScreenTwo: { screen: MedsTab },
    ScreenThree: { screen: Health },
    ScreenFour: { screen: Reports },
    ScreenFour: { screen: Inbox }
    })
  },
});`

Inside of my MedsTab there is a component which I want to gain access to this.props.navigation.  (should i pass a ref to navigation through the component?) Whenever I try and use const {navigate} = this.props.navigation I get the error navigation is undefined and when I log the props I don't see it there.

Thanks

**Comment by dekm** [comment]
Ended up getting this working with redux inside my reducer index.
