### ISSUE TITLE
How can i set the mode on a single screen ?

### ISSUE THREAD

**Issue by cizhaoyang** [react-community/react-navigation#2469]
I set like this :

	static navigationOptions = {
		header: null,
		mode: 'modal'
	};

but it do not work! I want to load a screen from the bottom and then load other screen from the right

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
