### ISSUE TITLE
Typo in contributors guide

### ISSUE THREAD

**Issue by DiscoStarslayer** [react-community/react-navigation#247]
In the contributors guide, there is a sentence that is abruptly cut off. See below (excuse the blame link, but there is no way to reference a individual markdown line as far as I can tell):

https://github.com/react-community/react-navigation/blame/master/docs/guides/Contributors.md#L71

Is there some known text to go here? Or does something need to be written for this?

**Comment by grabbou** [comment]
CC: @ericvicenti the original blame suggests you authored the file, did you mean to explain some additional things after `But it`? :fire:
