### ISSUE TITLE
navigationOptions ,headerBackTitle 

### ISSUE THREAD

**Issue by RayToby** [react-community/react-navigation#2470]
navigationOptions ,headerBackTitle  not work...

**Comment by matthamil** [comment]
Can you refer to the [issue template](https://github.com/react-community/react-navigation/blob/master/.github/ISSUE_TEMPLATE.md) when reporting bugs? It helps us to understand what is happening in your code so we can help you faster :)

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!

**Comment by RayToby** [comment]
@matthamil i set headerBackTitle to null, but it's not be hidden

**Comment by gaodeng** [comment]
same issue here .

**Comment by zgfang1993** [comment]
same issue

**Comment by zgfang1993** [comment]
you can set headerBackTitle on the previous Screen to affect the current one, it works

**Comment by joncursi** [comment]
Same here. I don't think this is a question, looks like a legitimate bug. I tried setting `headerBackTitle` to a string on my screen and it has no effect

**Comment by joncursi** [comment]
Nevermind! It does work, just not as I expected, as per https://github.com/react-community/react-navigation/issues/1358#issuecomment-298918466 - maybe this could be an issue request for more robust documentation around this nav prop (https://reactnavigation.org/docs/navigators/stack#headerBackTitle).

**Comment by RayToby** [comment]
you must set headerBackTitle on the previous Screen to affect the current one...

**Comment by Noitidart** [comment]
Wow thank you @RayToby for explaining that, I had no idea.

And that stinks, because i needed to affect the `backHeaderTitle` from the current screen. >_<

**Comment by hehuangz** [comment]
do not set `backHeaderTitle:null` in the current screen,
 you can set  `backHeaderTitle:null`  on the previous Screen to affect the current one, it works.
