### ISSUE TITLE
StackNavigator triggers transition twice when double tapping fast

### ISSUE THREAD

**Issue by stefanengel** [react-community/react-navigation#2471]
Hi,

if you use a StackNavigator and double tap on an item, the transition is triggered twice. You then have to go back two times as well to get back to the starting point. This behaviour can be observed in the current NavigationPlayground using expo. I was able to reproduce it on iOS (iPhone 6) and on Android (Samsung Galaxy S8).
Reproducing this bug on real devices can require a few attempts, you have to double tap really fast. I was not able to reproduce it on the iOS simulator.

### Current Behavior
- Fast double tap on StackNavigator item triggers transition to next Screen two times, user must go back two times

### Expected Behavior
- When the tap was recognized, another tap should not trigger the transition again

### Environment
- Current NavigationPlayground using Expo
- iPhone 6 on iOS 10.3.2
- Samsung Galaxy S8 on Android 7.0

**Comment by matthamil** [comment]
This is a known issue, see https://github.com/react-community/react-navigation/issues/271. There is discussion in other issues for potential fixes/workarounds. See also https://github.com/react-community/react-navigation/issues/135.

**Comment by murtuzamac** [comment]
Do we have a official fix for this so far?

**Comment by ue** [comment]
This issue fixed with latest version, I guess after v2.0 or try upper 👍 @murtuzamac

**Comment by brentvatne** [comment]
more info about how 2.0 fixed it here: https://reactnavigation.org/blog/#navigateroutename-in-stacknavigator-is-less-pushy
