### ISSUE TITLE
StackNavigator Error: React.createElement: type is invalid — expected a string 

### ISSUE THREAD

**Issue by mirzavu** [react-community/react-navigation#2472]
### Current Behavior

I have tried the basic code for react navigation from the documentation. But shows the below error for me

> Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object. You likely forgot to export your component from the file it's defined in.

### Steps to reproduce

1. Created native project using command create-react-native-app AwesomeProject
2. Installed `npm install --save react-navigation`
3. Pasted the below code to App.js from react navigation documentation
```
import React from 'react';
import {
  AppRegistry,
  Text,
} from 'react-native';
import { StackNavigator } from 'react-navigation';

class HomeScreen extends React.Component {
  static navigationOptions = {
    title: 'Welcome',
  };
  render() {
    return <Text>Hello, Navigation!</Text>;
  }
}

const SimpleApp = StackNavigator({
  Home: { screen: HomeScreen },
});
AppRegistry.registerComponent('SimpleApp', () => SimpleApp);
```
4. Run the app using `npm start` and opened in expo app android
Note: No other files have been edited.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^1.0.0-beta.11
| react-native     | ^0.47.0
| node             | v7.8.0
| npm or yarn      | 4.5.0

**Comment by canavdan** [comment]
Same issue here.

**Comment by mirzavu** [comment]
When using expo app, you need to export the main Component:

`export default SimpleApp;`

in standard React Native project, you use AppRegistry in index.android.js:

`AppRegistry.registerComponent('SimpleApp', () => SimpleApp);`

Problem solved
