### ISSUE TITLE
Half of the screen is black on some Android devices when using React Navigation

### ISSUE THREAD

**Issue by LCanceled** [react-community/react-navigation#2475]
### Current Behavior
After integrating react navigation library into my app that navigates between a pure react native screen and a custom ui component rendered using OpenGL, half of the react native screen turns black when I navigate between these two screens.

Some Android devices that have shown this bug:
魅族 MX5, Android 5.1
Galaxy Tab A 10.1 (gtanotexlwifikx) Android 7.0
One (m7) Android 5.0
Galaxy Note4 (tre3g) Android 5.1
小米Note开发版MIUI 8.7.6.14 Android 6.0.1
URBANO V02 (KYV34) Android 5.1

I made two sample apps to better reproduce this bug.
How to reproduce:
1. Download the code from https://github.com/LCanceled/GLSampleNavigation
2. Run "react-native run-android" on one of the devices listed above, say Galaxy Note 4.
3. Tap on the "Go To GL Screen" button in the middle of the screen (Screenshot A), it should show a red background rendered with OpenGL. (Screenshot B)
ScreenshotA:
![screenshota](https://user-images.githubusercontent.com/1491506/29728677-cb1192a4-898d-11e7-9807-7caddba02f7c.png)
ScreenshotB:
![screenshotb](https://user-images.githubusercontent.com/1491506/29728681-d273db6a-898d-11e7-81e0-b91db1ffd879.png)

4. Tap on the back arrow to go back to the react native screen, more than half of the screen now turns black. (Screenshot C)
ScreenshotC:
![screenshotc](https://user-images.githubusercontent.com/1491506/29728691-da08c390-898d-11e7-9054-5196c87945fd.png)

5. I have made another app that switches between the two screens using setState() instead of react-navigation. You can download it from here: https://github.com/LCanceled/GLSample
You can tap on the "Switch" button on the upper left corner to switch between the two screens. Everything works fine on Galaxy Note 4. It doesn't display the black screen behavior.

### Expected Behavior
Shouldn't show a black screen after navigating back from a custom react native component.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.11
| react-native     |  0.47.2
| node             | v6.11.0
| npm     | 5.2.0
Android devices and OS versions | listed above in "Current Behavior" section.

**Comment by LCanceled** [comment]
@skevy Filed this bug and uploaded code samples. It seems to be a problem in react navigation.

**Comment by nguyenanhthai** [comment]
I have same issue (black apart of screen) when back from a screen has RTCView component that plays webrtc stream.
https://github.com/oney/react-native-webrtc

**Comment by kelset** [comment]
Pinging OP @LCanceled since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open (does it still happen in latest version?); if I get no answer in the next 7 days I will close it.

**Comment by kelset** [comment]
Hi there @LCanceled ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.

**Comment by afshin-hoseini** [comment]
I have the same issue.
"react-navigation": "^1.5.8" 

😞

**Comment by dreadrocksean** [comment]
Same issue here.  rn: 1.5.8

**Comment by zamponotiropita** [comment]
I have the same issue when using a custom view. Please re-open.

**Comment by lzgrzebski** [comment]
same here :<

**Comment by brentvatne** [comment]
please create a new issue with a repro on the latest version of react-navigation
