### ISSUE TITLE
Drawer goBack action always re-render

### ISSUE THREAD

**Issue by luyx2412** [react-community/react-navigation#2477]
When i goBack action from drawer child, Parent screen alway re-render.
Screen A(Parent) --> Screen B(Child) --> goBack() (this is alway re-render Screen A).

I want to disable re-render when back action from Screen B --> Screen A(Parent)

How can solve this problem?
Thanks!

**Comment by spencercarli** [comment]
Hi, please follow the issue template when submitting an issue. It's there to help people help you. Thanks!
