### ISSUE TITLE
initialRouteName is invalid

### ISSUE THREAD

**Issue by pwj1993** [react-community/react-navigation#2479]
const AppNavigator = StackNavigator({
  TabBar: {
    screen: TabBarNavigator
  },
  Home: {
    screen: HomeView
  },
  HomeIndex: {
    screen: HomeTest
  },
  Wallets: {
    screen: Wallets,
    navigationOptions: ({navigation}) => {
      return {title: "我的钱包"};
    }
  },
  WalletsDetails: {
    screen: WalletsDetails
  }
}, {
  initialRouteName: "Wallets",
  mode: "modal"
});

I set the initialRouteName, but it always go to HomeIndex

**Comment by spencercarli** [comment]
Please follow the issue template when submitting an issue. Thanks!
