### ISSUE TITLE
headerStyle backgroundColor is not the same you put on code

### ISSUE THREAD

**Issue by matheusrocha89** [react-community/react-navigation#2480]
I was styling the header bar of StackNavigation and change the background color. But I saw that the color was not exactly the one I chose, it's darker (just tested on iOS Simulator).

The color I chose:
![image](https://user-images.githubusercontent.com/3718366/29741088-4e462b18-8a3c-11e7-8dc3-53f1df1dbe6c.png)

The color on the bar:
![image](https://user-images.githubusercontent.com/3718366/29741092-5a5c4b76-8a3c-11e7-8a12-7be7ef7b88e2.png)

My Code:
![image](https://user-images.githubusercontent.com/3718366/29741098-77bf708a-8a3c-11e7-8d2c-add272a8ad34.png)

The color on simulator is:
`#008527`

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.11
| react-native     | 0.47.1
| node             | 7.5.0
| yarn      | 0.27.5

**Comment by spencercarli** [comment]
The headerStyle is passed on [exactly as it is passed](https://github.com/react-community/react-navigation/blob/5e075e1c31d5e6192f2532a815b1737fa27ed65b/src/views/Header/Header.js#L291) so I don't see how this is. If you can provide a reproduction of this issue we can re-open. Thanks!
