### ISSUE TITLE
tabNavigator doesn't render correctly on android

### ISSUE THREAD

**Issue by abhishek-raj** [react-community/react-navigation#2481]
### Current Behavior
-Android doesn't render correctly if more than 1 tabNavigator is nested. I can't navigate inside the nested tabNavigator.
- My code is:
```
const mainFlow = {
      screen: TabNavigator({
        record: { screen: RecordScreen },
        send: { screen: SendScreen },
        homeFlow: {
          screen: StackNavigator({
            home: { screen: HomeScreen },
            settings: { screen: SettingsScreen }
          })
        }
      }, {
        navigationOptions: {
          tabBarVisible: true
        }
      })
    }

    const MainNavigator = TabNavigator({
      welcome: { screen: WelcomeScreen },
      signin: { screen: SigninScreen },
      signup: { screen: SignupScreen },
      mainFlow: mainFlow
    }, {
      navigationOptions: {
        tabBarVisible: true
      }
    });
```

The screenshot for this:
![image](https://user-images.githubusercontent.com/8985497/29741482-4d806b0e-8a8b-11e7-90b6-1edd458b4906.png)

### Expected Behavior
- It works on my iphone correctly
The screenshots:
![image](https://user-images.githubusercontent.com/8985497/29741487-7910cb60-8a8b-11e7-8979-32106aa1f4dc.png)

- :-
![image](https://user-images.githubusercontent.com/8985497/29741492-89dc9cf8-8a8b-11e7-8aef-19e0b62236b1.png)

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.11
| react-native     | 0.47.1
| node             | v6.11.1
| npm or yarn      | 3.10.10

**Comment by RsanabriaZ** [comment]
Hey look at this answer, I had the same issue and it helped me to fix it.
https://github.com/react-community/react-navigation/issues/662

You only need to add to make it works.
`swipeEnabled: false,
animationEnabled: false,`

**Comment by spencercarli** [comment]
Closing since solution linked to.
