### ISSUE TITLE
Custom background image but keep native back button

### ISSUE THREAD

**Issue by genbag** [react-community/react-navigation#2485]
I want to give my header a custom background image, but every solution makes me use the 'header' option in navigationOptions, wich puts a custom header in place, _above_ the original one.
But i like the default back button. It suits what i want, and i can't seem to be able make a custom one. It's still here, but it's **underneath** my custom header image.
Is there a way to put a background image in my headers, but keep the default components above it ?

**Comment by JulianKingman** [comment]
It might work to put a background on `headerTItle`, like `headerTitle: () => <Image><Text>...</Text></Image>`

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!

**Comment by genbag** [comment]
@spencercarli no problem. I ended up making my own back button, not without problems, but i made it ! ^^.
@JulianKingman Thanks for your answer, it most likely works too ! :)
