### ISSUE TITLE
Why TabNavigator render all sub screens at same time?

### ISSUE THREAD

**Issue by guoliang1206** [react-community/react-navigation#2488]
Four sub screen in the TabNavigator, don't you think it is the extra overhead  about render all of the sub screen at same time?
1. Does there has a way render single sub screen every time.
2.If 1 is not, and each of my sub screens has  a lot of data, how to handle the  hidden danger，e.g. lag, suspend?

![2017-08-29 1 31 22](https://user-images.githubusercontent.com/12846676/29805825-8f942cbc-8cbe-11e7-9ac0-d3080ba52e42.png)

**Comment by buncismamen** [comment]
we got lazy options 
`lazy - whether to lazily render tabs as needed as opposed to rendering them upfront`
https://github.com/react-community/react-navigation/blob/master/docs/api/navigators/TabNavigator.md

**Comment by guoliang1206** [comment]
@buncismamen  how to use Lazy?  what params should inside of lazy? can you provide an example?

**Comment by buncismamen** [comment]
```
const MyApp = TabNavigator({
  Home: {
    screen: MyHomeScreen,
  },
  Notifications: {
    screen: MyNotificationsScreen,
  },
}, {
  lazy: true,
  tabBarPosition: 'top',
  animationEnabled: true,
  tabBarOptions: {
    activeTintColor: '#e91e63',
  },
});
```

**Comment by guoliang1206** [comment]
@buncismamen  thanks , it works , I have wrote it in the wrong place before.

**Comment by Noitidart** [comment]
@buncismamen if they are lazy loaded, do they unload when the tab is changed? It doesnt seem to unload for me.

**Comment by buncismamen** [comment]
@Noitidart I think its not, they are not as smart as flatlist

maybe contributor have better explanation for this one

**Comment by buncismamen** [comment]
@Noitidart idk if this component is as smart as flatlist, but I think its not, maybe contributor have better words and explanation for this, maybe you could create another issue or looking through the code.

**Comment by Noitidart** [comment]
Thanks very much @buncismamen for such a fast reply!! :)

**Comment by thomaskleiven** [comment]
@buncismamen I cannot seem to find the lazy option in the docs. Can I specify this property somewhere else? Thank you.

**Comment by Noitidart** [comment]
@thomaskleiven here is example:

```
const HubNavigator = TabNavigator(
    TABS,
    {
        initialRouteName: INITIAL_ROUTE_NAME,
        backBehavior: 'initialRoute',
        swipeEnabled: false,
        lazy: true,
        tabBarComponent: TabBar,
        tabBarOptions: {
            showIcon: true,
            showLabel: false,
            tabStyle: styles.tab,
            iconStyle: styles.iconSize,
        }
    }
)
```

**Comment by thomaskleiven** [comment]
@buncismamen  allright, thank you!

**Comment by tianweicc** [comment]
@guoliang1206 @buncismamen @Noitidart  lazy 0.52 remove ，Is there any other way？

**Comment by Donhv** [comment]
I want lazy comeback :(.
But now lazy removed. who have solution for this issue?

**Comment by vendicto** [comment]
@tianweicc the same :|

**Comment by fuyue111** [comment]
@Donhv the same :(

**Comment by prodigynelson** [comment]
+1

**Comment by towfiqi** [comment]
+1

**Comment by pilot4u** [comment]
+1

**Comment by muhammedmirza** [comment]
+1

**Comment by cosmosof** [comment]
+1

**Comment by mefjuu** [comment]
+1

**Comment by lfalcao** [comment]
Not the best solution, but solved my issue. Only execute when screen is visible. 

```
componentDidMount () {
    this._sub = this.props.navigation.addListener( 'didFocus', () => (
      ...api requests...
    ))
  }
```

**Comment by brentvatne** [comment]
hi folks! please install react-navigation@1.1.0-rc.0, where `lazy` is now default. I also added other optimizations for better memory usage. let me know if this works well for you. https://github.com/react-navigation/react-navigation/pull/3538
