### ISSUE TITLE
custom animation has problem.

### ISSUE THREAD

**Issue by wuyunqiang** [react-community/react-navigation#2489]
### Current Behavior
A -> B  navigate
I custom a animat for react navigation,like that.
![navigationanimat](https://user-images.githubusercontent.com/13480948/29807323-00e600c8-8cc6-11e7-91ee-304cedd09afb.gif)

```
const forVerticalTop = (sceneProps)=>{
    const { layout, position, scene } = sceneProps;
    const index = scene.index;
    const height = layout.initHeight;
    const width = layout.initWidth;

    console.log('index',index);
    console.log('position',position);
    const opacity = position.interpolate({
        inputRange: ([
            index - 1,
            index - 0.99,
            index,
            index + 0.99,
            index + 1,
        ]: Array<number>),
        outputRange: ([1, 1, 1, 0.85, 0]: Array<number>),
    });

    const translateX = 0;
    // const translateX = position.interpolate({
    //     inputRange: ([index, index+1, index + 1]: Array<number>),
    //     outputRange: ([0,width,0]: Array<number>),
    // });
    const translateY = position.interpolate({
        inputRange: ([index, index+1, index + 1]: Array<number>),
        outputRange: ([0,height,height,]: Array<number>),
    });

    return {
        opacity,
        transform: [{ translateX }, { translateY }],
    };

};
```
### Expected Behavior
I hope no black part show me.
how I can make A don't move. 

### Your Environment
| software         | version
| ---------------- | -------
| react-navigation |  ^1.0.0-beta.11
| react-native     |  0.46.4
| node             |  v8.3.0
| npm or yarn      | 0.27.5

I search from stackoverflow and I have nothing. please help me .

**Comment by 94cstyles** [comment]
```js
StackNavigator(routes, {
  transitionConfig: () => ({
        screenInterpolator: (props) => {
            const {scene, scenes} = props
            if (scene === scenes[scenes.length - 1]) {
                return forVerticalTop()
            } else { 
                // 类似这样的操作 把动画设为null
                return null
            }
        }
    })
})
```

**Comment by wuyunqiang** [comment]
@94cstyles 
我不是想让他没有动画 我是想让黑色的部分消失就是A页面保持不动然后B页面从上面动画进入
按照你的方法尝试后 发现动画消失了

**Comment by 94cstyles** [comment]
1. 黑色部分是react-navigation的背景颜色 #000 ~ 我记得那里可以修改这个背景颜色
2. 把A的动画设为null 就是A页面保持不动 或者你 `return {transform: [{translateX: 0}]}`
3. 如果是A和B的动画都没了 应该是判断写错了~ 你可以根据RouteName进行判断 我这里只是给个思路

**Comment by wuyunqiang** [comment]
@94cstyles 
我从Home跳转到OverTimeApply 通过routeName判断是否有动画
如果等于OverTimeApply 就应用动画 然而还是会有黑色部分。
```
  screenInterpolator: (sceneProps) => {
            const {scene,scenes } = sceneProps;
            const { route,index } = scene;
            const params = route.params || {};
            const transition = params.transition || 'forHorizontal';
            console.log('route',route);
            switch (transition){
                case 'forVerticalTop':
                    if(route.routeName.indexOf('OverTimeApply')>=0){
                        console.log('有动画');
                        return forVerticalTop(sceneProps);
                    }else{
                        console.log('没有动画');
                        return null;
                    }

                case 'forHorizontalLeft':
                    return forHorizontalLeft(sceneProps);
                case 'freeStyle':
                    return freeStyle(sceneProps);
                default:
                    return CardStackStyleInterpolator[transition](sceneProps);
            }
        },
```

**Comment by yiky84119** [comment]
try this way:

screenInterpolator: (sceneProps) => {
        const { scene, scenes, position } = sceneProps;
        let sn = scenes[scenes.length - 1];

        if (scene.route.routeName !== 'Login' && sn.route.routeName === 'Login') {

            return {
                ...CardStackStyleInterpolator.forHorizontal(sceneProps),
                transform: [{ translateX: 0 }, { translateY: 0 }],
            };
        }

        if (scene.route.routeName === 'Login') {
            return pop(sceneProps);
        } else if (scene.route.routeName === 'Search') {
            return fade(sceneProps);
        }
        return CardStackStyleInterpolator.forHorizontal(sceneProps);
    },

**Comment by yiky84119** [comment]
try this way, set translateX to 0
```
const TransitionConfiguration = () => ({
    screenInterpolator: (sceneProps) => {
        const { scene, scenes, position } = sceneProps;
        let sn = scenes[scenes.length - 1];

        if (scene.route.routeName !== 'Login' && sn.route.routeName === 'Login') {

            return {
                ...CardStackStyleInterpolator.forHorizontal(sceneProps),
                transform: [{ translateX: 0 }, { translateY: 0 }],
            };
        }

        if (scene.route.routeName === 'Login') {
            return pop(sceneProps);
        } else if (scene.route.routeName === 'Search') {
            return fade(sceneProps);
        }
        return CardStackStyleInterpolator.forHorizontal(sceneProps);
    },
});
```

**Comment by kelset** [comment]
Pinging OP @wuyunqiang since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open (does it still happen in latest version?); if I get no answer in the next 7 days I will close it.

**Comment by JakeRawr** [comment]
I still run into this problem with v1.0.0

I customized the animation to "pushFromLeft", basically just the reverse of "forHorizontal" function. When push from left, the previous screen still slide to the left leaving empty black view on the right.
