### ISSUE TITLE
Fade in and fade out animation example in StackNavigator

### ISSUE THREAD

**Issue by MelodiiLy** [react-community/react-navigation#2493]
Hello, is anyone can give an example of how to transit views in 'fade in' and 'fade out' animation inside **StackNavigator**? I read the documentation, but unfortunately, it seems like I still can't figure it out. 

I really need some help, thanks for any help!!!

**Comment by 94cstyles** [comment]
```js
const fade = (props) => {
    const {position, scene} = props

    const index = scene.index

    const translateX = 0
    const translateY = 0

    const opacity = position.interpolate({
        inputRange: [index - 0.7, index, index + 0.7],
        outputRange: [0.3, 1, 0.3]
    })

    return {
        opacity,
        transform: [{translateX}, {translateY}]
    }
}

...
StackNavigator(routes, {
    transitionConfig: () => ({
        screenInterpolator: (props) => {
            return fade(props)
        }
    })
})
```

**Comment by MelodiiLy** [comment]
@94cstyles It works. Thank you!

**Comment by MelodiiLy** [comment]
Since the transitionConfig is inside the whole StackNavigator, all the screens inside the StackNavigator will perform the fade animation. But if I only want to perform fade between screen A and screen B, how to do it? One way in my mind is creating another StackNavigator which only includes A and B (with fade animation). Then put this StackNavigator in another 'bigger' StackNavigator.

I'm not sure this is the correct way or not. But personally, I don't like this way. Can anyone give some help? Thank you!

**Comment by 94cstyles** [comment]
```js
StackNavigator（routes，{
     transitionConfig ：（）=>（{
         screenInterpolator ：（props）=> {
             const {scene} = props
             if (scene.route.routeName === 'B') return  fade（props）
             return  outer....
        }
    }）
}）
```

**Comment by MelodiiLy** [comment]
@94cstyles The routeName part works! But I'm not sure the 'outer' part. I checked other issues about the animation but only found 'null'. So is there a snippet that can represent the 'default animation'? Or I have to adjust the inputRange and outputRange to make another 'default transition'? Cloud you please also give an example of the default one? Thanks!

**Comment by MelodiiLy** [comment]
Thanks!
