### ISSUE TITLE
RTL issue with stack navigator back button in Android

### ISSUE THREAD

**Issue by omar84** [react-community/react-navigation#2497]
First, thanks for the great job you've done with this package. really great job.

there seems to be an issue with the navigation arrow in Android when switching between RTL/LTR.
in iOS, when I change the language, the button switches direction, which is great, but in Android, the button never changes direction, until I exit the App, remove it from the Drawer, and then launch it again.

now, if I could set the direction in the headerLeft as an optional param, that would be great. as in:

```
navigationOptions = {
  headerLeft: {
    direction: 'rtl'
  }
}
```

if you have any other suggestion, I'm ready to try it.

Thanks.

**Comment by spencercarli** [comment]
Are you switching LTR -> RTL in app (as in it's not the default)? If so I'm wondering if the way Android caches images is causing an issue.

Would be very helpful if you could put together a small sample of this issue. Thanks!

**Comment by omar84** [comment]
Yes, I'm switching using I18nManager as recommended by react-native like so:

I18nManager.forceRTL(true);

everything is working fine, direction of the header is switched OK, the position of the back button switches from left to right, only the image itself stays the same, I figured it has something to do with image caching, but then I checked the code and it is using transform to flip the image in the style. so I'm not sure what is happening exactly.

**Comment by omar84** [comment]
@spencercarli I've create this App so you can see what I'm talking about for yourself.

https://github.com/omar84/MultiLanguageReactNativeSampleApp

**Comment by omar84** [comment]
@spencercarli any update on this?

**Comment by omar84** [comment]
OK, so I have updated all my packages to the latest versions, and updated my android to oreo, and the problem seems to be fixed, though i am not sure what exactly fixed it :)
