### ISSUE TITLE
Pre header coverd current page header on android device when using StackNavigator

### ISSUE THREAD

**Issue by blackkey520** [react-community/react-navigation#2502]
Hello,there have two page in my project,the first page like this
<img width="412" alt="wx20170831-132812 2x" src="https://user-images.githubusercontent.com/10826048/29907880-afb4a380-8e50-11e7-974e-4ecf6ce21d31.png">

The second pager like this
<img width="409" alt="wx20170831-132848 2x" src="https://user-images.githubusercontent.com/10826048/29907845-7338fab4-8e50-11e7-89c3-8562eed8d0de.png">
They have different navigationOptions,
when I navigate first page to second page I found Pre header coverd current page header,like this
<img width="407" alt="wx20170831-132831 2x" src="https://user-images.githubusercontent.com/10826048/29907881-b794aa28-8e50-11e7-9fba-c19a0f923ceb.png">
This issue happen only when the application is first started,after that,my project working fine.

My Environment
| software         | version
| ---------------- | -------
| react-navigation |1.0.0-beta.12
| react-native     |0.47.2
| node             |8.3.0
| npm or yarn      |5.3.0

**Comment by spencercarli** [comment]
Can you put together a small demo of this issue? Preferably on [Snack](https://snack.expo.io). Thanks!

**Comment by blackkey520** [comment]
close

**Comment by blackkey520** [comment]
close#2502

**Comment by Zhengjian1** [comment]
I use last leval ，have some question
