### ISSUE TITLE
How to navigate to a new screen and close the current screen?

### ISSUE THREAD

**Issue by nguyenhoanglam** [react-community/react-navigation#2504]
I'm new in React Navigation. I've researched many navigators (StackNavigator...) but I did not find an example for my case. For example, I'm in A screen, press a button to navigate to B screen, then close A screen.

Please help me!

**Comment by nico1510** [comment]
duplicate of https://github.com/react-community/react-navigation/issues/295. Please consider to close this issue if the linked issue describes your problem.

**Comment by nguyenhoanglam** [comment]
@nico1510 Thanks!

**Comment by karimkhamwani** [comment]
if you want to do this. reset navigation action

**Comment by A000ANB** [comment]
Use reset action or Use SwitchNavigator
https://reactnavigation.org/docs/en/switch-navigator.html

**Comment by wdayanand** [comment]
use SwitchNavigator 
https://reactnavigation.org/docs/en/switch-navigator.html

Or you can reset navigation action 


 const resetAction = StackActions.reset({
            index: 0,
            actions: [
                NavigationActions.navigate({ routeName: 'ScreenThree' })],
        });
        this.props.navigation.dispatch(resetAction);

**Comment by pradipb255** [comment]
simple method I found for it.
<this.props.navigation.replace('Home')>

**Comment by sirajalam049** [comment]
is there any method for replacing a new screen with last n screens?

or you can say... pop(n).push('NewScreen');

**Comment by mbzuze** [comment]
> is there any method for replacing a new screen with last n screens?
> 
> or you can say... pop(n).push('NewScreen');

this.props.navigation.pop(n);

**Comment by liqiujiong** [comment]
you can try it 
`    navigation.navigate(ROUTES.ChatMain)
    navigation.dispatch(state => {
      // Remove the home route from the stack
      const routes = state.routes.filter(r => r.name !== ROUTES.Login);

      return CommonActions.reset({
        ...state,
        routes,
        index: routes.length - 1,
      });
    });`
[https://reactnavigation.org/docs/navigation-actions/#reset](url)
