### ISSUE TITLE
Is it possible to have a globally-accessed DrawerNavigator

### ISSUE THREAD

**Issue by calvincanas** [react-community/react-navigation#2505]
Hello, like the title I want to know if a drawernavigator can be toggle(open/close) on any screens(component) and have the same drawer items?

**Comment by spencercarli** [comment]
Yes - you can call `this.props.navigation.navigate('DrawerOpen')` on any child screen of a DrawerNavigator.

For future reference usage questions are better asked on StackOverflow and when submitting an issue (feature request/bug) please follow the issue template. Thanks!
