### ISSUE TITLE
Official Solution?

### ISSUE THREAD

**Issue by tompiarulli** [react-community/react-navigation#251]
Based on the React Native [Roadmap](https://github.com/facebook/react-native/wiki/Roadmap) this is going to become the new standard navigation library for React Native correct? Will it remain separated or eventually make it's way into core to replace Navigator/Navigation-Experimental?

We're working on a new React Native project so we're trying to be as forward thinking as we can.

Thanks!

**Comment by grabbou** [comment]
As far as I know it will replace all other Navigators (some of them are going to be deprecated soon). It is a natural progression of ex-navigation and so, it will also become the `v2` for existing users.

As far as merging goes, I am not really sure. I think someone like @ericvicenti or @ide should be able to provide more details here.

**Comment by ide** [comment]
It is the standard navigation library but will remain separate. Core is best suited for truly core pieces, like the React Native bridge and UIManager.

**Comment by tompiarulli** [comment]
Good to know, thanks!
