### ISSUE TITLE
TabNavigator don't work. TabViewAnimated need onIndexChange props

### ISSUE THREAD

**Issue by Sean-Snow** [react-community/react-navigation#2510]
change TabView.js

    onRequestChangeTab: this._handlePageChanged

to 
   
    onIndexChange: this._handlePageChanged,

**Comment by matthamil** [comment]
Hi! Are you reporting a bug? Can you please use the [Issue Template](https://github.com/react-community/react-navigation/blob/master/.github/ISSUE_TEMPLATE.md) when opening issues? It helps us to understand what your issue is about :)

**Comment by Palisand** [comment]
Please see reference.

**Comment by manubamba** [comment]
Submitted a PR for the same.

https://github.com/react-community/react-navigation/pull/2527
