### ISSUE TITLE
How do I call the following method?Method defined within a component？

### ISSUE THREAD

**Issue by xiaoyongchen** [react-community/react-navigation#2511]
## Before You Start...
The issue list is reserved exclusively for bug reports and feature requests. That means we do not accept usage questions.

For usage questions, please use the following resources:

```js
/import liraries
import React, { Component } from 'react';
import { View, Text, StyleSheet,TouchableOpacity,Button ,ScrollView,Image} from 'react-native';
import {NormerBtn,BackBtn,Line,PraiseBtn}from '../../common/index'
import styles from './TopLinesDetailStyle';
import *as variables from '../../styles/variables';

let read_image = require('../../image/topLines/register_icon_eve.png');
let zan_image = require('../../image/topLines/register_icon_good2.png');
// create a component
class TopLinesDetail extends Component {

    static navigationOptions = ({ navigation, screenProps}) => ({
        
        title: '',
        headerLeft: <BackBtn callback={()=>{navigation.goBack()}} />,
        headerRight: <NormerBtn callback={()=>{
            // 请求数据
            this.task();
        }}/>,
        headerStyle: { backgroundColor: '#FFFFFF'},   //去除下面的阴影        
                    
    });
    task() {

    }
    
    render() {
        return (
            <View style={[styles.box,{backgroundColor:'#FFFFFF'}]}>
                <Line/>
                <Detail/>
            </View>
        );
    }
}
```

- [Read the docs](https://reactnavigation.org/)
- [Ask on the Reactiflux (#react-navigation)](https://discord.gg/reactiflux)
- [Look for / ask questions on StackOverflow](https://stackoverflow.com/questions/tagged/react-navigation)
- Also try to search for your issue - it may have already been answered or even fixed in the development branch. However, if you find that an old, closed issue still persists in the latest version, you should open a new issue.

---

### Current Behavior
- _If describing a bug, tell us what happens. Provide a screenshot when possible and full code sample_
- _If suggesting a change/improvement, explain the difference from current behavior_

### Expected Behavior
- _If you're describing a bug, tell us what should happen_
- _If you're suggesting a change/improvement, tell us how it should work_

### Your Environment
- _Include as many relevant details about the environment you experienced the bug in_

| software         | version
| ---------------- | -------
| react-navigation |
| react-native     |
| node             |
| npm or yarn      |

**Comment by xiaoyongchen** [comment]
task()

**Comment by matthamil** [comment]
You should do the following in `componentDidMount()`:

```
componentDidMount() {
  this.props.navigation.setParams({ method: this.method });
}
```

In `headerRight`, you can access it with `navigation.state.method`.

**Comment by arbantas** [comment]
@matthamil I think it should be `navigation.state.params.method`

**Comment by matthamil** [comment]
Thank you for catching that @arbantas , fixed
