### ISSUE TITLE
[v1.0.0-beta.12] Release Notes?

### ISSUE THREAD

**Issue by joncursi** [react-community/react-navigation#2516]
https://github.com/react-community/react-navigation/releases/tag/v1.0.0-beta.12

I've been waiting for these release notes to understand breaking changes before upgrading my project from beta `11` -> `12`, since I have no idea what has changed. The release notes say "coming soon", but it's been a month and a half. Has this been forgotten, or are they coming soon?

Thanks!

**Comment by guilhermepontes** [comment]
You can check the changes here: https://github.com/react-community/react-navigation/compare/v1.0.0-beta.12...master

**Comment by joncursi** [comment]
I tried upgrading from `11` -> `12` blindly a month ago, and my app looked and felt different navigationally. Seems like some properties and functionalities have changed which nullified some of the custom colors and setup I had, but I'm not sure which ones and why, or how to fix them.

**Comment by Kerumen** [comment]
@guilhermepontes You linked changes between `beta.12` and `master`. Here are the correct link for changes `beta.11` and `beta.12`
https://github.com/react-community/react-navigation/compare/v1.0.0-beta.11...v1.0.0-beta.12

**Comment by guilhermepontes** [comment]
true!

**Comment by matthamil** [comment]
This appears resolved https://github.com/react-community/react-navigation/releases
