### ISSUE TITLE
individual tabs should also get 'tabOptions'

### ISSUE THREAD

**Issue by Morriz** [react-community/react-navigation#2517]
same as for `tabBarOptions`, we should get a `tabOptions` prop that we can give to individual tabs:
```
    tabOptions: {
      inactiveTintColor,
      inactiveBackgroundColor,
      activeTintColor,
      activeBackgroundColor,
    },
```
(These tintcolors should then also be passed to the labels and icons when specified as a function.)

At the same time, it would be better to move `tabBarLabel` and `tabBarIcon` under `tabOptions` as `label` and `icon`, as they have nothing to do with navigation. We should also remove the `navigationOptions.title` as `navigationOptions.headerTitle` already exists.

I think I understand the rationale behind the current setup (a programmer's shortcut), but it's unclear and inconsistent.

I know this breaks backwards compatibility, but it's clearly the right way forward imo. Maybe support both for a while? What do you think?

**Comment by kelset** [comment]
Agree, it would be quite useful.
But it was already proposed here #1472 so I'll close this in favor of that issue.

Ofc feel free to submit a PR with the modifications proposed and I'll try to review it asap.
