### ISSUE TITLE
Deep Linking Not working with nested nevigation

### ISSUE THREAD

**Issue by nilaybrahmbhatt** [react-community/react-navigation#2518]
hey guys,

i am using nested navigation in react-navigation like 

```
var DrawerRoutes = StackNavigator(Routes,{
  initialRouteName:'Home',
  headerMode: 'screen',
  transitionConfig:TransitionConfiguration,
  navigationOptions: ({ navigation,transitioning }) => ({
    header: props => <Header {...props}  />
  })
});

export const AppNavigator = DrawerNavigator({
  Home: { screen: DrawerRoutes }
},{
  contentComponent: props => <SideBar {...props} />
})

const AppWithNavigationState = ({ dispatch, nav }) => (
  <AppNavigator navigation={addNavigationHelpers({ dispatch, state: nav })} />
);

```

i want to use deep linking here. i tried to use in 

```
export const AppNavigator = DrawerNavigator({
  Home: {
  screen: () => (<DrawerRoutes uriPrefix={prefix} />)
}
},{
  contentComponent: props => <SideBar {...props} />
})
```
Deep linking works perfectly but 

this.props.navigation.navigate("DrawerOpen") not worked

drag drawer is working but not using click on button.

please suggest me any other way for deep linking or to open drawer

**Comment by PatNeedham** [comment]
@nilaybrahmbhatt where are you defining `DrawerOpen` within one of your navigators? If you're not defining it anywhere, the `navigate` function won't do anything.

**Comment by kelset** [comment]
Pinging OP @nilaybrahmbhatt  since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open (does it still happen in the latest version?); if I get no answer in the next 7 days I will close it.

**Comment by kelset** [comment]
Hi there @nilaybrahmbhatt,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.
