### ISSUE TITLE
request: searchable documentation

### ISSUE THREAD

**Issue by Morriz** [react-community/react-navigation#2519]
Can we have search functionality? Pretty please?

**Comment by guilhermepontes** [comment]
You can use the GitHub's search bar for it. All documentation are available here as `.md` files.

**Comment by spencercarli** [comment]
On my wish list as well! But until then I would suggest using @guilhermepontes suggestion 😄

**Comment by malashkevich** [comment]
Seems like it's related to #1252

**Comment by matthamil** [comment]
Resolved in https://github.com/react-community/react-navigation/pull/2606
