### ISSUE TITLE
Values for NavigationParams are defined as strings (is it on purpose?)

### ISSUE THREAD

**Issue by juhasuni** [react-community/react-navigation#252]
TypeDefinition.js defines `NavigationParams` as a map where each value (parameter) must be a string.

`export type NavigationParams = {
  [key: string]: string,
};`

Yet, in the same file there's a documented example, where the value is an int. 

```
/**
   * Params passed to this route when navigating to it,
   * e.g. `{ car_id: 123 }` in a route that displays a car.
*/
```

To me it looks like NavigationParams type definition is wrong, but I couldn't be sure, since you may have thought about URL routing, where each parameter must be string.

**Comment by grabbou** [comment]
To me, the type could be:
```
export type NavigationParams = {
  [key: string]: mixed,
};
```
Let's send a PR!
