### ISSUE TITLE
the method in BackHandler does not work until back root route

### ISSUE THREAD

**Issue by lu79931748** [react-community/react-navigation#2523]
```js
    componentWillMount(){
        BackHandler.addEventListener('hardwareBackPress', this._onBackAndroid)
    }

    _onBackAndroid = () => {
        console.log(this.props.navigation.state.routeName)
        if (this.lastBackPressed && this.lastBackPressed + 2000 >= Date.now()) {
            return false;
        }
        this.lastBackPressed = Date.now();
        toastShort('Press Again Exit App');
        return true;
    };

    componentWillUnmount(){
        BackHandler.removeEventListener('hardwareBackPress', this._onBackAndroid)
    }
```

| react-navigation | 1.0.0-beta.11
| react-native     |0.44

**Comment by lu79931748** [comment]
when i press hardware back button,  the log have not output until back root route

**Comment by DCKT** [comment]
I've the same behavior

**Comment by HappyerKing** [comment]
this.subs = BackAndroid.addEventListener('hardwareBackPress', () =>{
        this.dispatch(NavigationActions.back())
        return false;
      }

**Comment by lu79931748** [comment]
@DCKT I seem to know what the reason is that the react navigation manage all back listener，so you must invoke `BackAndroid.addEventListener` after the `react navigation` has been created.

**Comment by kelset** [comment]
Pinging OP @lu79931748  since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open (does it still happen in the latest version?); if I get no answer in the next 7 days I will close it.

**Comment by kelset** [comment]
Hi there @lu79931748 ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.
