### ISSUE TITLE
[Android] Deep Linking not working from Browser

### ISSUE THREAD

**Issue by maggialejandro** [react-community/react-navigation#2525]
### Current Behavior
I followed the [Docs](https://reactnavigation.org/docs/guides/linking), also I've read [this](https://developer.android.com/training/app-links/deep-linking.html) but when I open the following URI in Google Chrome, Deep Linking does not work.

> company.app://company.app/main/notifications

This works correctly using the CLI
```bash
adb shell am start -W -a android.intent.action.VIEW -d "company.app://company.app/main/notifications" com.company.app
```

### Your Environment

I tried these combinations of scheme/host but none of them work from Chrome.
```xml
<intent-filter>
    <action android:name="android.intent.action.VIEW" />
    <category android:name="android.intent.category.DEFAULT" />
    <category android:name="android.intent.category.BROWSABLE" />
    <data android:scheme="company.app" android:host="company.app" />
    <data android:scheme="https" android:host="www.company.com" />
    <data android:scheme="company" android:host="mobile" />
    <data android:scheme="companymobile" android:host="company" />
</intent-filter>
```

Also, only this URI works using adb shell: "company.app://company.app/main/notifications"

any ideas?
Thanks in advance!

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.11
| react-native     | 0.45.1
| node             | v8.4.0
| npm or yarn      | 5.3.0

**Comment by maggialejandro** [comment]
[Here](https://github.com/maggialejandro/deep) is a repo with the issue

```bash
adb shell am start -W -a android.intent.action.VIEW -d "deeplinking://deeplinking/page" com.deeplinking
```

**Comment by athmangude** [comment]
I was stuck here too. Ended up moving on with [Linking](https://facebook.github.io/react-native/releases/0.21/docs/linking.html#content)

**Comment by maggialejandro** [comment]
Hi @athmangude , can you share your intent-filter tag?
Are you setting android:launchMode="singleTask" on .MainActivity?

I tried to use Linking without success. 
I need URLs like https://m.domain.com/page to open certain screens on my app.

Thanks

**Comment by kelset** [comment]
Hey @maggialejandro, is the issue still worth keeping open? Have you tried with the latest version (beta.13)?

Trying to answer what you asked @athmangude, in my prod app I'm also using Linking without many issues, I have something like this:


```gradle
      <activity
        android:name=".MainActivity"
        android:launchMode="singleTask"
        android:label="@string/app_name"
        android:theme="@style/SplashTheme"
        android:screenOrientation="portrait"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
            <action android:name="android.intent.action.DOWNLOAD_COMPLETE"/>
        </intent-filter>
        <intent-filter android:label="filter_react_native">
          <action android:name="android.intent.action.VIEW" />
          <category android:name="android.intent.category.DEFAULT" />
          <category android:name="android.intent.category.BROWSABLE" />
          <data android:scheme="[name of my app]" android:host="*" />
        </intent-filter>
      </activity>
```

**Comment by maggialejandro** [comment]
@kelset Hi Lorenzo, sorry for the delay.
I ended up using an intent-filter like this:
```xml
<intent-filter android:label="@string/app_name" android:autoVerify="true">
    <action android:name="android.intent.action.VIEW" />
    <category android:name="android.intent.category.DEFAULT" />
    <category android:name="android.intent.category.BROWSABLE" />
    <data android:scheme="https"
        android:host="*.mywebsite.com.ar"
        android:pathPrefix="/page" />
</intent-filter>
```

Then I handle the url using Linking as @athmangude said.

**Comment by esipavicius** [comment]
@maggialejandro Hi, can you help me with deep link? How can I in Android from browser run something like something://something/aaa/datId ? I using DrawerNavigator->StackNavigator->TabNavigator

**Comment by sadikyalcin** [comment]
Bump... It does work but most browsers will run a search instead of navigating to the links as it does not recognise it as a link... If you try putting `<a href="your-scheme://` on a webpage and tap it, it will open the app I'm sure :)

**Comment by cyanoluck** [comment]
> If you try putting `<a href="your-scheme://` on a webpage and tap it, it will open the app I'm sure :)

thanks my friend. waste so much time to put this fking link into google chrome

**Comment by sharadkatre1995** [comment]
Yes @sadikyalcin It is working with the webpage but can we make it work by sending the same kind link in the email to get redirect to the app.

**Comment by ashutoshgngwr** [comment]
I was finding a solution to a different issue and landed here. This is a common pitfall for Android Intent Filters. From the [official documentation](https://developer.android.com/guide/topics/manifest/data-element):

> All the `<data>` elements contained within the same [`<intent-filter>`](https://developer.android.com/guide/topics/manifest/intent-filter-element) element contribute to the same filter.

**Comment by ShaunKoooo** [comment]
In my case, deep link didn't work when using Chrome, does anyone know why?

**Comment by Siumauricio** [comment]
I spended 3 hours on fixing this until i see https://stackoverflow.com/questions/37069816/deep-linking-not-working-in-chrome,  the only way to work is as [sadikyalcin](https://github.com/sadikyalcin) said, use a anchor tag with href="..///" it will work
