### ISSUE TITLE
when I reset route, all old routes appear my App

### ISSUE THREAD

**Issue by lu79931748** [react-community/react-navigation#2528]
```js
const resetAction = NavigationActions.reset({
    index: 0,
    actions: [
        NavigationActions.navigate({routeName: 'Index'})
    ],
    key:null
});
this.state.navigation.dispatch(resetAction);
```
before I reset, I through some pages, and when I reset toutes, these pages appear in my App until navigate ```Index```
| react-navigation | 1.0.0-beta.11
| react-native     | 0.44

**Comment by lu79931748** [comment]
I see some developer take this problem, but looks like have no effect method to solve it

**Comment by infeng** [comment]
To handle your app's navigation state in redux, you can overwrite reset action.

**Comment by spencercarli** [comment]
Is this a bug report or a question?

**Comment by pierot** [comment]
@spencercarli We are experiencing the same.
We have a flow of multiple screens. On the final screen in the flow we have an action that dispatches a `reset`. The app navigates to the given route but all other screens in that flow appear in the transition:

```
NavigationActions.reset({
  index: 0,
  actions: [NavigationActions.navigate({routeName: 'Home'})],
})
```

**Comment by vonovak** [comment]
closing since I believe this was fixed by https://github.com/react-community/react-navigation/commit/e6505054bd765f0771aec8c328238b0b4d8ddab9, but feel free to reopen if that is not the case.
