### ISSUE TITLE
Center title on Android in a StackNavigator

### ISSUE THREAD

**Issue by yolosaucisson** [react-community/react-navigation#253]
Hi,

I tried to center the title of a StackNavigator in Android but nothing worked.
Someone knows how to do? :(

Sincerely,

**Comment by grabbou** [comment]
Hey,

You can pass custom style for title that centers text just like on iOS:
```js
navigationOptions: {
  header: {
     style: {
        textAlign: 'center',
     },
  },
}
```

**Comment by yolosaucisson** [comment]
It works? It tried and nothing happened
Maybe I did a mistake

**Comment by grabbou** [comment]
Please provide a full snippet showing how you tried setting these values up. As far as the code goes, it should work.

**Comment by michaelduminy** [comment]
There's also the new `titleStyle` prop for headers. Maybe try setting the `textAlign: 'center'` in that?

**Comment by grabbou** [comment]
@michaelduminy yeah, you are right! I meant that prop :)

**Comment by matthamil** [comment]
@grabbou Any suggestions on how to fix this? When I applied `textAlign: 'center'` in my `titleStyle` object, it centers the title, but I want to center the text respective to the entire window, not the size of the text box:

![image](https://cloud.githubusercontent.com/assets/11802078/22950060/f2fc9b0c-f2c9-11e6-83bf-a32370f579a5.png)

Also, is there any way to change the color of the navigation arrow pictured in the top left?

My code:

```js
static navigationOptions = {
    title: applyLetterSpacing('REGISTRATION'),
    header: navigation => ({
      style: {
        backgroundColor: 'rgb(47, 54, 61)',
        shadowOpacity: 0,
      },
      titleStyle: {
        color: '#fff',
        fontFamily: 'MuseoSansRounded-300',
        textAlign: 'center'
      }
    })
  };

```

**Comment by satya164** [comment]
Add `marginRight: 56`

**Comment by mabounassif** [comment]
I don't know why textAlign isn't working with me.
```
const MainScreenNavigator = StackNavigator({
	Home: {
		screen: LoginScreen,
		navigationOptions: {
			header: {
				title: 'TITLE',
				titleStyle: {
					color: 'black',
					align: 'center',
					textAlign:'center',
					fontFamily: 'MuseoSansRounded-300',
					fontWeight: '500'
				}
			}
		}
	}
});
```

**Comment by matthamil** [comment]
alignSelf: center

**Comment by dcp12345678** [comment]
In case anybody struggles with this as I just did, it looks like the latest version uses headerTitleStyle instead of titleStyle.  See docs [here](https://reactnavigation.org/docs/navigators/stack)

**Comment by Lexiwu** [comment]
It doesn't work for me.  Does anyone have a solution?

**Comment by matthamil** [comment]
@Lexiwu what version of React Navigation are you using? The API has changed in the latest release.

**Comment by Lexiwu** [comment]
I updated the latest version from git. 
I check the[ latest release](https://github.com/react-community/react-navigation/releases),
and I use :
 headerStyle :{justifyContent: 'center',borderWidth: 1, borderColor: '#1d2088'},
 headerTitleStyle :{textAlign: 'center', borderWidth: 1, borderColor: '#ff0000'}

Am I using it right?

I am a newer in react-native.

**Comment by matthamil** [comment]
@Lexiwu if you add `alignSelf: 'center'` does your issue get resolved?

**Comment by Lexiwu** [comment]
@matthamil 
It works!!
That's odd. I tried "alignSelf: 'center'" yesterday, and it did not work.
Anyway, thank you a lot!!!

**Comment by lakeoffaith** [comment]
static navigationOptions = {
    title:'登录',
    headerTitleStyle :{textAlign: 'center',alignSelf:'center'},
    headerStyle:{
      backgroundColor:'red',
    }
  };
it work

**Comment by gulshanzealous** [comment]
headerTitleStyle:{
	fontWeight:'500',
	fontSize:24,
	marginTop:5,
	alignSelf:'center'
},

`alignSelf:'center'`

this works for me.

**Comment by Kirill23** [comment]
Just in case if you want to have well centered title make sure both 
headerLeft: (<View></View>), 
headerRight: (<View></View>)

have "View" or other element inside.

together with 
headerTitleStyle :{textAlign: 'center',alignSelf:'center'},

will work like a charm.

**Comment by rjloura** [comment]
This was sufficient for me:
```
  static navigationOptions = {
    title: 'My Title',
    headerTitleStyle: {alignSelf: 'center'},
};
```

**Comment by HHuiHao** [comment]
**1.Modify the method _renderTitle in source code Header.js
Comment on the following code:**
if (Platform.OS === 'android') {
if (!options.hasLeftComponent) {
style.left = 0;
}
if (!options.hasRightComponent) {
style.right = 0;
}
}
**2. set headerTitleStyle in the global situation**
const stackNav = StackNavigator(
{
xxx: {screen: xxx}
},
{
navigationOptions: {
headerTitleStyle: {
marginHorizontal: 0,
alignSelf:'center',
},
},
}
);
```

**Comment by iuraya** [comment]
Hi!

If my navigation bar has left or right elements the title is not well centered:

<img width="390" alt="captura de pantalla 2017-10-06 a las 16 47 20" src="https://user-images.githubusercontent.com/14769734/31283511-2ab008d2-aab6-11e7-8a83-f0917716c682.png">

**Comment by nobuti** [comment]
@iuraya clearing the right view works for me:
```
static navigationOptions = ({ navigation }) => ({
    headerTitle: 'New Card',
    headerTitleStyle: {
      alignSelf: 'center',
      textAlign: 'center'
    },
    headerRight: (<View></View>)
  })
```

**Comment by luisfuertes** [comment]
The same that @iuraya here

**Comment by Garib-ka-code** [comment]
@gulshanzealous Its work for me also...

**Comment by googya** [comment]
@Kirill23 I set left and right in config: 
```javascript
  navigationOptions: ( {navigation}) => {
    const { routeName } = navigation.state;
    return {
      gesturesEnabled: false,
      headerLeft: (<View />),
      headerRight: (<View />),
```

but, when tabNavigator be nested in StackNavigator, the sub screen's header of right does not override the default config of header 

```javascript
  static navigationOptions = ({navigation}) => {
    const params = { headerTitle: (<Title content='mall'/>) };
    params.headerRight = (
      <SearchIcon
        iconStyle={{ marginRight: 10, marginBottom: -5 }}
        iconClick={() => navigation.navigate('Search.index')} />
    );

    return params;
  }
```

do you have any suggestion ?

**Comment by northern** [comment]
As of today, with the latest version of React Native Navigation, this issue still persists. In this thread there a number of "hacks" presented but the real issue is obvious in the library itself.

Just to reiterate the problem; on Android, then title is not centered correctly when a button on the left is shown (like a Back button). Centering the title without any buttons in the header works correctly.

**Comment by golestanirad** [comment]
but why headerStyle: {justifyContent: 'center'} doewn't work ??!!

**Comment by oscarjg** [comment]
Same for me. I try to put an image in the center of my header but is impossible! I can't undertand why this issue is not resolved yet. Anyone knows the real problem behind of this? On IOS works perfectly. I tried all the styles posibilites but any works.

**Comment by Garib-ka-code** [comment]
Register: {
    screen: Register,
    navigationOptions: {
        title: 'Register',
        headerBackTitle: null,
        headerStyle: {
          backgroundColor: '#0D2143',
          position: 'absolute',
          height: 50,
          top: 0,
          left: 0,
          right: 0,
        },
        headerTitleStyle:{
          alignSelf:'center',
          textAlign: 'center',
          width: '100%',
        },
        headerTintColor: '#fff',
      }
  }

Above code is working for me. Please try @oscarjg

**Comment by sporteman** [comment]
@oscarjg 
I use an image as well, to me, the best solution was:

```
screen: ApplicationTabs,
      navigationOptions: ({ navigation }) => ({
        title: <Image source={HEADER_LOGO} />,
        headerTitleStyle: {
          alignSelf: 'center',
          textAlign: 'center',
        },
        headerTintColor: '#FFF',
        headerStyle: {
          backgroundColor: '#E3D200',
          borderBottomColor: 'transparent',
          borderWidth: 0,
          elevation: 0,
          shadowOpacity: 0,
        },
      }),
```

Please try, hope it works to you too! 
ps:
I'm using:
**"react-native": "0.52.0",
 "react-navigation": "^1.0.0-beta.27",**

**Comment by oscarjg** [comment]
Hi @sporteman!

I'm trying your code, but doesn't work for me. Using title instead of headerTitle I get an error on next routing route and on the other hand the image is display a little bit small on Android. Using hederTitle the error disappears but I still have the same issue on android. For me the only way is overriding the header prop with my custom header managing left and right buttons with myself

**This is with headerTitle**
<img width="817" alt="screen shot 2018-01-28 at 20 58 57" src="https://user-images.githubusercontent.com/6267700/35486490-0e00513e-046f-11e8-994c-dcd84d8e756b.png">

**This is with title**
<img width="766" alt="screen shot 2018-01-28 at 21 00 03" src="https://user-images.githubusercontent.com/6267700/35486491-0e1d38a8-046f-11e8-9ad1-b6299c1f05b3.png">

**This is the error on the next route with title**
<img width="815" alt="screen shot 2018-01-28 at 21 00 30" src="https://user-images.githubusercontent.com/6267700/35486492-0e47282a-046f-11e8-82a5-a3ba871837fd.png">

Thanks for your help anyway! I still looking the way, so if you o anybody have good news about this I'll be appreciated

**Comment by golestanirad** [comment]
@oscarjg   get the device width and set the title padding from right to half of it

**Comment by maxhanzo** [comment]
I had the same issue with StackNavigation, reporded by @oscarjg  and @iuraya .

Unfortunately, it seems that the only way to solve this issue is by using  headerTitleStyle: { ...alignSelf: "center"... }  and adjusting the width percentage according to the size of the text (in order to prevent the text to be truncated). And also, this may work well with Android but not with iPhone (check if the percentage work for both OS). 

Something like this:
`
headerTitleStyle: {
          fontFamily: "Montserrat-Regular",
          fontSize: 16,
          fontWeight: "normal",
          justifyContent: "center",
          alignSelf: "center",   
          width: "35%"  //Varies according to the size of the text. 
      }
`

 **For example:"Termos e Condições"**: 

`  
static navigationOptions = {
      title: "Termos e Condições",
      headerStyle: {backgroundColor: color.grapePurple},
      headerTintColor: color.whiteTwo,
      headerTitleStyle: {
          fontFamily: "Montserrat-Regular",
          fontSize: 16,
          fontWeight: "normal",
          justifyContent: "center",
          alignSelf: "center",
          width: "65%"
      }
  };
`
![screenshot_2018-02-20-18-51-27 copy](https://user-images.githubusercontent.com/735552/36452211-5c1d61e4-1672-11e8-95d7-190dfa063240.png)

**Another example: "Sobre":**

`
  static navigationOptions = {
      title: "Sobre",
      headerStyle: {backgroundColor: color.grapePurple},
      headerTintColor: color.whiteTwo,
      headerTitleStyle: {
          fontFamily: "Montserrat-Regular",
          fontSize: 16,
          fontWeight: "normal",
          justifyContent: "center",
          alignSelf: "center",
          width: "35%"
      },
      backTitle: ""
  };
`
![screenshot_2018-02-20-18-51-43](https://user-images.githubusercontent.com/735552/36452333-d2eec2ea-1672-11e8-9f29-0bef43cf4672.png)

**Comment by brentvatne** [comment]
can someone please create a new issue for this and include an example that reproduces it on https://snack.expo.io? thanks

**Comment by pravinraut809** [comment]
static navigationOptions = {
title:'TITLE',
headerTitleStyle :{textAlign: 'center',alignSelf:'center'},
headerStyle:{
backgroundColor:'red',
}
};


check this .,, 100% working

**Comment by oscarjg** [comment]
Hi! @pravinraut809 The problem is with image component as a title not with simple text and on Android platform.

@brentvatne I'm going to try it today or tomorrow

Thanks!

**Comment by SamirMarin** [comment]
Was there a new issue open for this?

**Comment by mohamed-sultan** [comment]
it's a huge pan for me

**Comment by bbeckk** [comment]
static navigationOptions = {
        title: 'Home',
        headerStyle: {
        },
        headerTintColor: '#fff',
        headerTitleStyle: {
            width: '90%',
            textAlign: 'center',
        },
    };

Setting width percent works for me. I've no idea why setting width: 100% makes it in the absolute center

**Comment by adhambadr** [comment]
same problem here some tricks that worked for me perhaps it helps you : 
1. added `flex:1` to HeaderTitleStyle 
2. added flex as well as fixed dimensions for android
`headerLogo:Platform.OS === 'ios'?{
  	width:90,alignSelf:'center',alignItems:'center'
  }:{
  	flex:1,width:180,height:70
  }`
3. used title for Android and headerTitle for ios (dont know why they work better this way): 
```javascript
    title:Platform.OS === 'ios' ?null:logo,
    headerTitle:Platform.OS === 'ios' ? logo : null, 
```

**Comment by sebirdman** [comment]
So far the best solution i've found is to set headerTitleStyle to have 

```
{
    textAlign: "center",
    flex: 1,
}
```

this way you don't have to set a percent, works well with text (not sure what images do)

**Comment by KaraboCoder** [comment]
headerTitleStyle: {textAlign:'center', alignSelf:'center',flex:1}
works for me

**Comment by brentvatne** [comment]
some good answers here so I'll lock this so they're easy to find. if you run into further issues or these solutions do not work for you, please create a new issue. also, if you'd like to add these solutions to the documentation that would be very helpful! github.com/react-navigation/website
