### ISSUE TITLE
NavigateActions.navigate - Same routeName indefinitely

### ISSUE THREAD

**Issue by carloscuesta** [react-community/react-navigation#2533]
### Current Behavior

When using the `navigate` method from `NavigateActions` it is possible to navigate to the same exact `routeName` indefinitely. Creating a history within the same route.

![bug](https://user-images.githubusercontent.com/7629661/30056846-a1e70008-9234-11e7-864f-f3f829e3c90a.gif)

Let's say you have the following Navigator

```es6
const RootNavigator = StackNavigator({
  Home: { screen: Home, path: '/home' },
})
```

Then, your Home component has a button which navigates to the same `routeName`.

```es6
const Home = ({ navigation }) =>  (
    <Button onPress={() => navigation.navigate('Home')} title='Navigate Home' />
)
```

### Expected Behavior

- The Navigator shouldn't navigate to the same route if it's already inside of it.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.11
| react-native     | 0.47.2
| node             | 6.11.1
| npm or yarn      | 0.27.5

**Comment by matthamil** [comment]
Hi Carlos, this behavior is expected due to the fact that you may want to navigate to the same route with different params: `navigation.navigate('Profile', { username: 'Matt' })` and `navigation.navigate('Profile', { username: 'Carlos' })` should both take you to the same route with different data.

There is more discussion in the links in the comments on this PR: https://github.com/react-community/react-navigation/pull/1787

**Comment by sospedra** [comment]
In the web world different params would be different routes. Hence, same `routeName` and params should not navigate anywhere.

**Comment by Gerharddc** [comment]
Has this been "fixed" because I actually need this behavior of being able to navigate to the same screen with different params but can't get it?

**Comment by carloscuesta** [comment]
I think this is the expected behaviour so you'll have to workaround on this feature @Gerharddc

**Comment by Oblongmana** [comment]
Just noting in case this crops up again, that being able to navigate to the same route with different params is very much a desired behaviour for me - I'd expect this to be supported by any navigation library (even if it requires a bit of extra work on my side to configure)

**Comment by carloscuesta** [comment]
Of course @Oblongmana, the thing is that within that particular case the navigation params were the same so makes no sense to navigate IMHO
