### ISSUE TITLE
Tab Navigation setParams freeze screen

### ISSUE THREAD

**Issue by adhicl** [react-community/react-navigation#2534]
Hi, I tried to call setParams from a screen inside a tab navigation and it freeze the screen. Is there no way to setParams when inside a tab? Any other solution if I want to pass this.props to the navigation option then?

This is the code inside my screen:
```
componentDidMount() {
        this.props.navigation.setParams({handleTextSearch: this._onHandleChangeTextSearch.bind(this)});
    }
_onHandleChangeTextSearch(text) {
        this.props.searchTopicList(text);
    }
static navigationOptions = ({navigation}) => {
        console.log(navigation.state.params.handleTextSearch);
}
```
Thanks.

**Comment by spencercarli** [comment]
Can you provide a demo of this issue?

**Comment by adhicl** [comment]
Hi, @spencercarli , I created a new project to reproduce the issue and found out how the issue crops up. 

### Current Behavior
I have a splash screen that will check if my app should show a login screen or enter home screen (tab navigation). The issue crops up whenever my app enter the home screen. The screen freezes up
![screen-freeze](https://user-images.githubusercontent.com/2452628/30150491-d73a2666-93d5-11e7-829f-b58de19e24c6.jpg)

### Expected Behavior
From splash screen, the app should have open the home screen.
![screen-ok](https://user-images.githubusercontent.com/2452628/30150478-c48017ec-93d5-11e7-9ebc-15ba8db74ddc.jpg)

The project to reproduce can be grabbed here:
https://github.com/adhicl/emptyprojectv20
(is this what you mean?)

The problem of the code is in 
Tab1Screen.js
```
componentDidMount() {
        this.props.navigation.setParams({
            handleEnterChild: this._onHandleEnterChild.bind(this)
        });
}
```

### My Environment
(I am using expo)
| expo | ^20.0.0",
| react |16.0.0-alpha.12",    
| react-navigation | ^1.0.0-beta.11
| react-native | https://github.com/expo/react-native/archive/sdk-20.0.0.tar.gz
| react-redux | ^5.0.6
| redux | ^3.7.2
| redux-thunk | ^2.2.0

**Comment by adhicl** [comment]
Hi @spencercarli, is my post before has enough information? Need anything more?

**Comment by tehwayne** [comment]
This may be an infinite loop related to my issue here: #2702

**Comment by spencercarli** [comment]
Hey @adhicl thanks for that repro. Swamped by the number of issues but hopefully, this can get sorted out.

**Comment by kelset** [comment]
@tehwayne yes, it looks to me that it freezes because of the infinite loop. I'll close this in favour of the other one.

**Comment by adhicl** [comment]
okay. I will watch to the other tread then
