### ISSUE TITLE
Undefined is not an Object this.props.navigation.navigate

### ISSUE THREAD

**Issue by joshmello** [react-community/react-navigation#2537]
I have searched all the SO my options are depleted. I had this working yesterday and nothing changed. I deleted node_module reinstalled, cleared cache and watchman still getting this error. Hopefully, someone can help me out if I missed something. IF you need more code let me know but I am calling the login function obviously the user gets authenticated just fine but will not push to 
Splash screen. [Error Screenshot](https://ibb.co/dQoXda)
Login.js
`import React, { Component} from 'react';
import PropTypes from 'prop-types';
import {Text,View, Navigator} from 'react-native';
 login() {
        const { navigate } = this.props.navigation;   
        const self = this;
        Auth
           .userLogin(this.state.email, this.state.password)
           .then(() => {
            navigate('Splash');
           })
          .catch((err) => {
            self.setState({
              error: err,
            });
          });
      };`

Router
`import React from 'react'; 
import {  Navigator} from 'react-native';
import { StackNavigator, NavigationActions } from 'react-navigation';
import Login from '../screens/Login';
export const StackNav = StackNavigator({
Login: { screen: Login},
},
{
  initialRouteName: 'Login',
  headerMode: 'none',
},
);`

**Comment by lerl221295** [comment]
Hi, i was have the same problem and i get succes by that: https://github.com/react-community/react-navigation/issues/2198#issuecomment-316883535

**Comment by joshmello** [comment]
@lerl221295 Thanks go figure that was it.

**Comment by courptwayne** [comment]
const { navigate } = this.props.navigation; is not working !
