### ISSUE TITLE
Unable to navigate to a TabNavigator with reset action

### ISSUE THREAD

**Issue by junshengpierre** [react-community/react-navigation#255]
Hi all,

I have a navigation setup like this:

 * RootNavigator
   * TopLevelScreen
   * TopLevelScreen
   * TabNavigator
     * StackNavigator
       * Screen
       * Screen
     * StackNavigator
       * Screen
       * Screen

I was trying to navigate to the TabNavigator from a TopLevelScreen after resetting the navigation stack, with:

```javascript
import { NavigationActions } from 'react-navigation'

const resetAction = NavigationActions.reset({
  index: 0,
  actions: [
    NavigationActions.navigate({ routeName: 'Tabs' }),
  ]
})
```
 but got the error:
`There is no route defined for key Tabs. Must be one of: 'Tab1Screen1', 'Tab1Screen2'`

Code: 
```javascript
const Tab1Navigator = StackNavigator({
  screen: Tab1Screen1,
  screen: Tab1Screen2
})

const Tab2Navigator = StackNavigator({
  screen: Tab2Screen1,
  screen: Tab2Screen2
})

const Tabs = TabNavigator({
  screen: Tab1Navigator,
  screen: Tab2Navigator
})

const RootNavigator = StackNavigator({
  screen: LoginScreen,
  screen: TestScreen,
  screen: Tabs
})
```

Does anybody know what I might have done wrong? Navigating from a TopLevelScreen like `TestScreen` or `LoginScreen` to another TopLevelScreen after resetting worked fine.

**Comment by junshengpierre** [comment]
This only happens when the RootNavigator is integrated with redux. Otherwise, it works as expected.

**Comment by parkerdan** [comment]
I have the same set up with Login leading to Tabs and had the same issues...

I now navigate with Redux by creating a new action and managing this myself.

```js
      navigation.dispatch({
        type:'DO_THIS_THANG',
        payload: {
          index:0,
          routes:[
            {routeName:'TabbedNavigator', key:'Init'}
          ]
        }
      })

```

and in this set-up...

```js
export const loginNavState = (state,action) => {
  if (action.type === 'DO_THIS_THANG') {
    return { ...state, ...action.payload }
  } else {
    return LoginNav.router.getStateForAction(action,state)
  }
}

```

and store

**Comment by parkerdan** [comment]
Yeah...  I _had_ the same issue.  Same set-up with Stack-Nav Screens and a Tab-Nav in the stack.

Solved it by using Redux and dispatching a custom action:

```js
      navigation.dispatch({
        type:'DO_THIS_THANG',
        payload: {
          index:0,
          routes:[
            {routeName:'TabbedNavigator', key:`Init`}
          ]
        }
      })

```

and in the Redux Store:

```js
  combineReducers({
    whatever:(state,action) => {
      if (action.type === 'DO_THIS_THANG') {
        return { ...state, ...action.payload }
      } else {
        return LoginNav.router.getStateForAction(action,state)
      }
    },
   // ...other things
```

**Comment by junshengpierre** [comment]
I realised I hooked up my navigation with redux wrongly. I both my RootNavigator and TabNavigator integrated with redux. After removing the TabNavigator from redux and only having my top-level navigator - RootNavigator integrated with redux, I was able to navigate into TabNavigator.
