### ISSUE TITLE
navigate() throws exception when title is an <Image>

### ISSUE THREAD

**Issue by lukecwilliams** [react-community/react-navigation#2556]
**Edit:** The below applies when the header title is an <Image> component.

This works fine:

    public static navigationOptions = {
      title: 'foobar', //...

This causes this error:
    public static navigationOptions = {
      title: <Image source={require('../images/header_logo.png')} />, //...

It looks like a react-navigation bug to me.  Thanks for taking a look.

### Current Behavior
Attempting to call this.props.navigation.navigate() results in this error message.  I've tried it with different components.  It seems like some prop name is being passed as an object, not a string.
 
![image](https://user-images.githubusercontent.com/19214773/30178029-9dd2b92e-93d5-11e7-9e22-5cedf5333c98.png)

log-ios gives a bit more detail:

> Sep  7 14:14:56 MacBook-Pro-5 mobile2mr[25676] <Error>: Error setting property 'accessibilityLabel' of RCTView with tag #196: JSON value '{

Here's my StackNavigator setup (within a TabNavigator):

```
const trackingTabWithHeader = { screen: StackNavigator(
  {
    Tracking: { screen: TrackingScreen },
    Workout: { screen: WorkoutGroupScreen },
  },
  {
    ...stackNavigatorConfig,
    initialRouteName: 'Tracking',
  },
)};
```

### Expected Behavior
Should navigate!

### Environment

| software         | version
| ---------------- | -------
| react-navigation | v1.0.0-beta.11
| react-native     | 0.47.1
| node             | 8.0.x
| npm or yarn      | yarn 1.0.1

**Comment by bennygenel** [comment]
I think you should use [headerTitle](https://reactnavigation.org/docs/navigators/stack#headerTitle) not `title`

**Comment by lukecwilliams** [comment]
@bennygenel Yes - thanks.  Thought I saw this example somewhere, that was a costly erroneous type.

Will increase reliance on TS in the future esp since this lib provides good defs.

**Comment by manjeetwadi** [comment]
@bennygenel I am using headerTitle but it still breaking for me, any suggestion

**Comment by bennygenel** [comment]
@manjeetwadi hard to say without any code and more info about how its breaking.

**Comment by manjeetwadi** [comment]
@bennygenel  your solution works

**Comment by StefanWallin** [comment]
THANK YOU! This saved my day! 🚀 🌮
