### ISSUE TITLE
Access screenProps from custom TabBar

### ISSUE THREAD

**Issue by vanhoutk** [react-community/react-navigation#2558]
I'm not sure whether this should be classed as a bug or a feature request.

## Current Behaviour
When using a TabNavigator as a component (i.e. `<TabNav screenProps = {someProps}/>`), screenProps is only available in the screens of the TabNavigator and not from the TabBar.

```
export const TabNav = TabNavigator({
  Tab1: { screen: TabA },
  Tab2: { screen: TabB },
}, {
  tabBarComponent: TabBar,
  tabBarPosition: 'bottom',
});
```

## Expected Behaviour
TabBar should ideally be able to access screenProps too, as using the navigator as a component means that there is no way to access `navigation.state.params` and thus currently no way to pass any parameters to a custom TabBar.

### Environment
"react-native": "0.47.2",
"react-navigation": "^1.0.0-beta.11"

**Comment by linkinmedo** [comment]
can't you access this.props.getScreenDetails(scene)?

**Comment by leesolway** [comment]
In the render method of  TabBar, i did the following :-

`const screenOptions = AppNavigator.router.getScreenOptions(navigation)`

This allowed me to do the following :-

```
        {screenOptions.actionButton && (
          this.renderActionButton(screenOptions.actionButton)
        )}
```
ActionButton is set in the screen :- 

  ```
static navigationOptions = ({ navigation, screenProps }) => ({
    actionButton: {
      title: _('create'),
      icon: 'plus',
      onPress: () => navigation.navigate('EventCreate')
    },
    tabBarLabel: _('calendar'),
    tabBarIcon: ({focused}) => <Icon name="calendar" active={focused} />
  })
```
You can make this dynamic using some of the same patterns used for dynamic titles. 
Hope it helps.

**Comment by kelset** [comment]
Pinging OP @vanhoutk since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open (does it still happen in the latest version?); if I get no answer in the next 7 days I will close it.

Moreover this issue https://github.com/react-community/react-navigation/issues/2818 provides some ways to pass parameters to a custom TabBar

**Comment by vanhoutk** [comment]
@kelset I've changed the structure of my navigators within my app since creating this issue, so have no need for it to stay open myself and I'm unable to quickly test whether it still persists with the latest version.
