### ISSUE TITLE
StackNavigator inside DrawerNavigator, goBack() doesn't work!

### ISSUE THREAD

**Issue by MelodiiLy** [react-community/react-navigation#2559]
```
export const Stack_A = StackNavigator({
  A1: {
    screen: A1
  },
  B1: {
    screen: B1
  }
});

export const Stack_B = StackNavigator({
  A2: {
    screen: A2
  },
  B2: {
    screen: B2
  }
});

export const Drawer_Stack = DrawerNavigator({
  Stack_A: {
    screen: Stack_A
  },
  Stack_B: {
    screen: Stack_B
  }
}
```
I can go to Stack_A or Stack_B through Drawer Navigation. However, I can't goBack() to the main screen by press back button in Stack_A or Stack_B. 

```
<Button
  title='back button'
  onPress={() => this.props.navigation.goBack()}
/>
```
Thanks for any help!

**Comment by spencercarli** [comment]
In this context what is the "main" screen. Though it's not a great solution, does `this.props.navigation.goBack(null)` accomplish what you're looking for?

**Comment by MelodiiLy** [comment]
@spencercarli The main screen is the first screen in DrawerNavigator. It always backs to the first screen from any other screens. Am I right?

this.props.navigation.goBack(null) works! But the animation is like a fade out. Do you know how to set the animation like the normal one(Same as the StackNavigator)?

Also, can you please explain why this.props.navigation.goBack(null) works but this.props.navigation.goBack() not? Thank you!

**Comment by kelset** [comment]
Pinging OP @MelodiiLy since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open (does it still happen in the latest version?); if I get no answer in the next 7 days I will close it.

**Comment by kelset** [comment]
Hi there @MelodiiLy ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.
