### ISSUE TITLE
Method componentWillMount just called first access

### ISSUE THREAD

**Issue by galhardi** [react-community/react-navigation#2564]
I'm trying use TabNavigator and in one tab I put react-native-camera with conditional render.
On componentWillMount I set showCamera flag to true and after camera read's a barcode I set showCamera to false, and when I return to camera page in a second time the constructor method is not trigger.
What event handler tab activate?

| software              | version
| ---------------------- | -------
| react-navigation  | 1.0.0-beta.11
| react-native         | 0.47.0
| react-redux          | 5.0.6
| redux                   | 3.7.2

**Comment by spencercarli** [comment]
As it stands once a tab is mounted it will not be re-mounted in a tab. For now the only real option is to create a custom tab bar that you can add a onTabPress function to, allowing you to detect when the correct tab is pressed.

There is a a [PR](https://github.com/react-community/react-navigation/pull/1335) open addressing this functionality already. We just need to review & merge it.

**Comment by galhardi** [comment]
@spencercarli, thk you!
