### ISSUE TITLE
Nested navigators Stack1->Drawer->Stack2 don't allow go back to Stack1

### ISSUE THREAD

**Issue by Jose-Gallegos** [react-community/react-navigation#2565]
I have a complex navigation structure, where I have a initial StackNavigator for Login screen, after that I have a DrawerNavigator, and then each drawer option is a StackNavigator for showing a header.

```
const SearchAnimalStack = StackNavigator(
  {
    SearchAnimal: {
      screen: SearchAnimalScreen,
      navigationOptions: ({ navigation}) => ({
        headerLeft: <DrawerButton navigation={navigation}  />
      }),
    }
  },
  {
    navigationOptions: ({ navigation}) => ({
      drawerLabel: "Buscar Animal",
      headerTitle: "Buscar Animal",
      headerTintColor: '#407a4f',
      headerStyle: {
            backgroundColor: '#58b076',
      },
    }),
  }
);


const RegisterAnimalStack = StackNavigator(
  {
    RegisterAnimal: {
      screen: RegisterAnimalScreen,
      navigationOptions: ({ navigation}) => ({
        headerLeft: <DrawerButton navigation={navigation}  />
      }),
    }
  },
  {
    navigationOptions: ({ navigation}) => ({
      drawerLabel: "Registrar Animal",
      headerTitle: "Registrar Animal",
      headerTintColor: '#407a4f',
      headerStyle: {
            backgroundColor: '#58b076',
      },
    }),
  }
);

const SignedInDrawer = DrawerNavigator({
    SearchAnimal: { screen: SearchAnimalStack,
      navigationOptions: {
        drawerLabel: "Buscar Animal",
      }
    },
    RegisterAnimal: { screen: RegisterAnimalScreen,
      navigationOptions: {
        drawerLabel: "Registrar Animal",
      }
    },
    Profile: { screen: ProfileScreen,
      navigationOptions: {
        drawerLabel: "Perfil",
      }
    },
  }
);

const BovinoAppStack = StackNavigator({
    Login: { screen: LoginScreen },
    SignedInDrawer: {screen: SignedInDrawer },
  },
  {
    headerMode: "none",
  }
);
```

I'm trying to have a Logout button on ProfileScreen  like this:

```
  logout() {
    const { dispatch } = this.props.navigation;
    dispatch(NavigationActions.reset( { index: 0, actions: [ NavigationActions.navigate({routeName: 'Login', params: { noAutologin: true }})]}));
  }

<TouchableOpacity style={styles.simpleButton} onPress={() => {this.logout()}}>
          <Text style={styles.buttonText}>Cerrar sesión <FontAwesome>{Icons.signOut}</FontAwesome></Text>
</TouchableOpacity>
```

But when I click the button there is an error: "There is no route defined for key Login. Must be one of: 'SearchAnimal'

The expected behavior is to go back to LoginScreen.

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.12
| react-native     | 0.48.2
| node             | v7.7.0
| npm or yarn      | npm 4.1.2

**Comment by kelset** [comment]
Hi - reset is currently a method that has some issues, we are looking to better control the behaviour of it in future releases.

In the meantime, I suggest you take a look at issue #1127 (in particular from [this comment](https://github.com/react-community/react-navigation/issues/1127#issuecomment-319727619) on) to better understand how it works / how you may have to fix your method call.

I'd like to close this issue since it's mostly a duplicate, but I'd prefer to wait to hear back from you before that.

**Comment by Jose-Gallegos** [comment]
It worked setting key:null on this line:

`dispatch(NavigationActions.reset( { index: 0, key: null, actions: [NavigationActions.navigate({routeName: 'Login', params: { noAutologin: true }})]}));
`
Thanks!

**Comment by rochapablo** [comment]
Still the same problem

```
const initialNavState = AppNavigator.router.getStateForAction(NavigationActions.reset({
  index: 0,
  key: null,
  actions: [
    NavigationActions.navigate({
      routeName: 'LoginNav',
      params: { noAutologin: true }
    })
  ]
}))
```

**Comment by dbyilmaz** [comment]
I think it is bug . @rochapablo

**Comment by rochapablo** [comment]
@dbyilmaz, do you know if there's a solution for that?

**Comment by graig12** [comment]
@rochapablo did you ever happen to figure this issue out? i am running into the same issue here 
and i can't seem to figure this one out

**Comment by graig12** [comment]
------AppNavigator.js-----
import React from 'react';

import { StackNavigator, SwitchNavigator, TabNavigator, addNavigationHelpers} from 'react-navigation';

import{createStore,combineReducers,} from 'redux'

import {connect} from 'react-redux'



import Homes from '/Users/IFSTech/Desktop/Consent/app/screens/Home';

import Profile from '/Users/IFSTech/Desktop/Consent/app/screens/profileScreen';

import SignInScreen from '/Users/IFSTech/Desktop/Consent/app/screens/signIn';

import AuthLoadingScreen from '/Users/IFSTech/Desktop/Consent/app/screens/auth';

import Consent from '/Users/IFSTech/Desktop/Consent/app/screens/consent';

import  RegisterScreen from '/Users/IFSTech/Desktop/Consent/app/screens/register'


const AppStack = TabNavigator({ Home: Homes, Profile: Profile,Consents:Consent });
const AuthStack = StackNavigator({ SignIn: SignInScreen, Register: RegisterScreen });

export const Appswitch = StackNavigator(
  {
    AuthLoading: AuthLoadingScreen,
    App: AppStack,
    Auth: AuthStack,
  },
  {
    initialRouteName: 'AuthLoading',
  }
);


const AppWithNavigationState =({ dispatch,nav}) =>(
  <Appswitch

     navigation={addNavigationHelpers({dispatch,state:nav})}

     />

);

const mapStateToProps =state =>({

  nav:state.nav,
})

export default connect(mapStateToProps)(AppWithNavigationState);


---NavReducer----

import { combineReducers } from 'redux';
import { NavigationActions } from 'react-navigation';
import { Appswitch } from '/Users/IFSTech/Desktop/Consent/app/screens/AppNavigator';




const initialNavState=Appswitch.router.getStateForAction(NavigationActions.reset({
	index: 0,
	actions: [
	  NavigationActions.navigate({
		routeName: 'AuthLoading',
		params:{noAutologin:true}
	  }),
	],
}))

const NavReducer = (state = initialNavState, action) => {
  return router.getStateForAction(action, state);
};

export default NavReducer;





Can some one review and assist thanks

**Comment by graig12** [comment]
I also tried adding the key value to null but still the same issue.
import { combineReducers } from 'redux';
import { NavigationActions } from 'react-navigation';
import { Appswitch } from '/Users/IFSTech/Desktop/Consent/app/screens/AppNavigator';




const initialNavState=Appswitch.router.getStateForAction(NavigationActions.reset({
	index: 0,
	key:null,
	actions: [
	  NavigationActions.navigate({
		routeName: 'AuthLoading',
		params:{noAutologin:true}
	  }),
	],
}))

const NavReducer = (state = initialNavState, action) => {
  return router.getStateForAction(action, state);
};

export default NavReducer;

**Comment by rochapablo** [comment]
@graig12, I just add all in one `DrawerNavigator`:

```
export const AppNavigator = DrawerNavigator(
  {
    Login: { screen: Login },
    ...
  },
  {
    ...settings,
    navigationOptions: {
      drawerLockMode: 'locked-closed'
    },
    drawerPosition: ...,
    contentComponent: ...,
    initialRouteName: '...'
  }
)
```

It's not what I wanted, but it's working for now.

**Comment by dbyilmaz** [comment]
@rochapablo  is there any bugs in react navigation new version?

**Comment by rochapablo** [comment]
dbyilmaz, I can't tell; right now I'm working with Angular, but I'll be starting a new RN very soon running the new version, so let's hope not =D

**Comment by dbyilmaz** [comment]
@rochapablo I hope you don't encounter bugs. good luck :)
