### ISSUE TITLE
DrawerNavigator doesn't make use of native animations

### ISSUE THREAD

**Issue by AndrewIngram** [react-community/react-navigation#2572]
There are certain scenarios (eg navigating to a screen with a `SectionList` with a `ListHeaderComponent` prop set) which perform very poorly when using `DrawerNavigator`. I suspect this is because a relatively expensive blocking operation occurs mid-way through the animation (such as calculating layout for list windowing).

We dug into things a bit and discovered that `react-native-drawer-layout` (which `DrawerNavigator` uses under the hood) exposes a `useNativeAnimations` prop, but react-navigation itself doesn't make use of it or expose it further.

We hacked the code a bit to expose the prop and it made quite a significant difference:

Before: https://www.youtube.com/watch?v=O3-YMhocBVw
After: https://www.youtube.com/watch?v=dSpF-WkP1Yc

Are there any reasons why this isn't enabled by default, or otherwise exposed as an option?

Pull Request is here: https://github.com/react-community/react-navigation/pull/2568

**Comment by matthamil** [comment]
Closing since https://github.com/react-community/react-navigation/pull/2568 was merged
