### ISSUE TITLE
Active Tab in TabNavigator tabBarComponent

### ISSUE THREAD

**Issue by mehdizadeh93** [react-community/react-navigation#2574]
How to get active Tab in `tabBarComponent` of `TabNavigator ` ?
i create costume `tabBarComponent`  for `TabNavigator ` and i need the active Tab, How to find out witch tab is active know ?

**Comment by spencercarli** [comment]
This isn't currently supported by the library (and has been asked about before). I'll point you to #51 for workarounds.

**Comment by bakaa99** [comment]
you can get the navigation index from props and then show active image or inactive image based on the condition

this.props.navigationState.index === 3 ? {if_index_condition :else_condition}}

**Comment by jaimebiernaski** [comment]
Try this ;-)

`static navigationOptions = ({ navigation }) => ({
  tabBarOnPress: ({ scene, jumpToIndex }) => {
    navigation.state.params.setCurrentScreen(scene);
    if (!scene.focused) {
      jumpToIndex(scene.index);
    }
  },
});

....

componentDidMount() {
    this.props.navigation.setParams({
      ...this.props.navigation.state.params,
      setCurrentScreen: scene => {
        this._setCurrentScreen(scene);
      }
    });
  }

.... 

render(){...}

_setCurrentScreen = (scene) => {
  console.log('Current Scene:', scene)
}`
