### ISSUE TITLE
StackNavigator - Unknown element inside DOM

### ISSUE THREAD

**Issue by anton6** [react-community/react-navigation#2576]
When I use react-devtools to inspect DOM, I find an `Unknown` element inside the Navigator.
It seems to wrap the transitioner.

<img width="614" alt="screen shot 2017-09-13 at 17 21 20" src="https://user-images.githubusercontent.com/16119505/30388707-61bd87f2-98a8-11e7-85e8-69e91217ad37.png">

I am using StackNavigator

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.11
| react-native     | 0.46.4

Has anyone came across this? Why is it there?
Thanks.

**Comment by matthamil** [comment]
This looks like an issue with react-devtools. This is probably appearing as `Unknown` based on how the `createNavigator` is [exported](https://github.com/react-community/react-navigation/blob/master/src/navigators/createNavigator.js#L26-L38). If you feel like this is an issue with react-navigation, feel free to open a PR. :)
