### ISSUE TITLE
`screenProps` warning can't be hidden

### ISSUE THREAD

**Issue by SpaceK33z** [react-community/react-navigation#258]
Since beta 2, using `screenProps` will result in a warning saying this:

```
Behaviour of screenProps has changed from initial beta [...]. Pass `hideScreenPropsWarning` to hide this warning.
```

But when I try to hide that warning, like this:

```js
import { StackNavigator } from 'react-navigation';

const Navigator = new StackNavigator({
    Home: { screen: HomeScreen },
});

export default () => <Navigator screenProps={{ foo: 'bar' }} hideScreenPropsWarning />;
```

It still shows up. It looks like this is because the `hideScreenPropsWarning`  prop is never passed through to the `SceneView` component (see https://github.com/react-community/react-navigation/commit/b9bc386a4b788412b126637ee3965c5383714c3d).

**Comment by grabbou** [comment]
Looks like a good first task! @SpaceK33z got some time to contribute? :)

**Comment by SpaceK33z** [comment]
Sure, probably later today.
But are we sure `hideScreenPropsWarning` is the best way to do this? For new users to this library this warning is totally irrelevant. For existing users it is kinda nice, but for one time only.

If there was a changelog where this change would be stated, that would be enough.

**Comment by grabbou** [comment]
I think we don't even need that prop as you can turn off (mute) some warnings in React Native (hint: what about non-RN consumers of this library?)

```js
console.ignoredYellowBox = [
   'Behaviour of screenProps has changed',
];
```

**Comment by satya164** [comment]
I just removed the prop and published an update. The warning should be shown only once, so shouldn't be an issue for non-RN users.
