### ISSUE TITLE
TabNavigator in custom tabBarComponent component when user scroll animate header. 

### ISSUE THREAD

**Issue by hari-mohan-choudhary** [react-community/react-navigation#2582]
I am using tabNavigator 
`const ProfileStack = TabNavigator({
    Home: {
      screen: ProfileAccount,
    },
    Account: {
      screen: ProfileBankAccount,
    },
    Wallet: {
      screen: ProfileWalletAccount,
    },
  }, {
    animationEnabled: true,
    tabBarComponent: TabsComponent,
    tabBarPosition: 'top',
    swipeEnabled: true,
    backBehavior: 'none',
    lazy: true,
    tabBarOptions: {
      activeTintColor: '#e91e63',
      //scrollEnabled: true,
    },
    style: {
        backgroundColor: 'blue',
      },

  });
`
when user scroll I want animation on TabsComponent component How possible...?

**Comment by Noitidart** [comment]
Nice question, I am also wondering the same thing.

**Comment by Noitidart** [comment]
The custom component is passed a `position` prop which is an animated value. Example:

```
class TabBarDumb extends PureComponent<void, Props, void> {

    componentDidMount() {
        this.props.position.addListener(e => console.log('pos e:', e));
    }
    render() {
        console.log('tab bar props:', this.props);
        const { color, navigation:{state:{ routes }}, position } = this.props;

        // const routesFiltered = routes.filter(route => !route.key.startsWith('dum'));
        const styleActivePill = {
            backgroundColor: color,
            transform: [{ translateX:position.interpolate({ inputRange:[0, 3], outputRange:[0, Dimensions.get('window').width] }) }]
        }
```

**Comment by hari-mohan-choudhary** [comment]
@Noitidart  Thanks for answer but I am not understand I think You don't understand my question so  I am explain  
<img width="281" alt="screen shot 2017-09-14 at 2 24 37 pm" src="https://user-images.githubusercontent.com/16562224/30469557-6c8cb8f8-9a0e-11e7-8b5f-0a894abbb6a4.png">
this is my profile where I am using tabNavigator. When user scroll vertical then I want add animation on top profile(tabBar margin and opacity ). I have build animation and fire onScroll event. but No way to communicate TabsComponent and Personal Details components. 

I want these type animation and when animation finish tabBar fixed top 
![1-pxoer2z45hyyflzhhqbq8w](https://user-images.githubusercontent.com/16562224/30469669-ff8a1ce0-9a0e-11e7-9745-f5f18afea5b2.gif)

My Custom components
`import React from 'react';
import { View, StyleSheet, Text, TouchableWithoutFeedback, ScrollView, Animated } from 'react-native';
import UserDetailCard from './../Componets/Profile-Components/userDetailCard.components';

class TabsComponent extends React.Component {
    state = {
        AnimateVar: new Animated.Value(0),  // Initial value for opacity: 0
    }
    static navigationOptions = {
        tabBarLabel: 'user',
        // Note: By default the icon is only shown on iOS. Search the showIcon option below.
        tabBarIcon: ({ tintColor }) => (
            <Image
                source={require('./../Assets/Images/profileIcon.png')}
                style={[styles.icon, { tintColor: tintColor }]}
            />
        ),
    };

    componentDidMount() {
        Animated.timing(                  // Animate over time
            this.state.AnimateVar,            // The animated value to drive
            {
                toValue: 1,                   // Animate to opacity: 1 (opaque)
                duration: 1000,              // Make it take a while
            }
        ).start();                        // Starts the animation
    }

    scrollDown(event: Object) {
    }

    render() {
        const {
      navigation,
            renderIcon,
            activeTintColor,
            inactiveTintColor,
            jumpToIndex
    } = this.props;
        console.log(this.props);
        margin = this.state.AnimateVar.interpolate({
            inputRange: [0, 1],
            outputRange: [20, 0],
        });
        height = this.state.AnimateVar.interpolate({
            inputRange: [0, 1],
            outputRange: [200, 25],
        });
        fadeAnOut = this.state.AnimateVar.interpolate({
            inputRange: [0, 1],
            outputRange: [1, 0],
        });
        const {
      routes,

    } = navigation.state;

        return (
            <ScrollView onScroll={this.scrollDown()} style={{ backgroundColor: '#fff' }}>
                <Animated.View style={{ height: height, opacity: fadeAnOut, }} >
                    <UserDetailCard />
                </Animated.View>
                <Animated.View style={[styles.tabbar, { marginRight: margin, marginLeft: margin }]} >

                    {routes && routes.map((route, index) => {
                        const focused = index === navigation.state.index;
                        const tintColor = focused ? activeTintColor : inactiveTintColor;
                        return (
                            <TouchableWithoutFeedback
                                key={route.key}
                                style={styles.tab}
                                onPress={() => jumpToIndex(index)}
                            >
                                <View style={styles.tab}>
                                    {renderIcon({
                                        route,
                                        index,
                                        focused,
                                        tintColor
                                    })}
                                    <Text>a{this.props.scrollvalue}</Text>
                                </View>
                            </TouchableWithoutFeedback>
                        );
                    })}


                </Animated.View>
            </ScrollView>
        );
    }
}

const styles = StyleSheet.create({
    tabbar: {
        height: 50,

        marginTop: -25,
        top: 0,
        marginBottom: 10,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        borderTopWidth: 1,
        borderTopColor: '#fff',
        backgroundColor: '#fff',
        borderWidth: 1,
        zIndex: 111,
        borderRadius: 2,
        borderColor: '#ddd',
        borderBottomWidth: 0,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.8,
        shadowRadius: 2,
        elevation: 1,
    },
    tab: {
        alignSelf: 'stretch',
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center'
    }
});


export default TabsComponent;
`

**Comment by Noitidart** [comment]
For that collapsible effect you would use something like this - https://github.com/wix/react-native-interactable - please do share your solution there, as I ran into some issues when working on it - https://github.com/wix/react-native-interactable/issues/35

**Comment by alexstoyanov** [comment]
@hari-mohan-choudhary did you find a solution. Could you post the solution because I have the same issue.

**Comment by kelset** [comment]
Pinging OP @hari-mohan-choudhary since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open (does it still happen in the latest version?); if I get no answer in the next 7 days I will close it.

**Comment by kelset** [comment]
Hi there @hari-mohan-choudhary ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.
