### ISSUE TITLE
With TabNavigator calling setParams() from inactive tab makes it active

### ISSUE THREAD

**Issue by aforty** [react-community/react-navigation#2583]
I have a `TabNavigator` with 3 tabs, one of the tabs calls `setParams` on `componentWillMount` to set some initial params which are later changed with use. 
I noticed that using `setParams` in a `TabNavigator` tab sets the TabNavigator's state `index` to the tab that called it. So when I have 3 tabs (with `lazy: false`) and one of them calls `setParams` then that tab becomes active and thus focus changes away from the current tab. 

Is this a feature or a bug? And how could I work around it so that the tab does not become active?

**Comment by matthamil** [comment]
I'm curious about your use case with `setParams` without any intention to navigate? Maybe I don't understand your scenario fully. Perhaps an "initialParams" should exist for routes?

**Comment by aforty** [comment]
I have a paging horizontal scrollview on that page and each page sets it's own title. So on initial `componentWillMount()` I set the current page's title (based on user settings, so it's not static) using `setParams()`. I suppose I could get hacky and handle this in my navigation reducer but I'd prefer to keep the logic on that page as that's where it all lives anyway for when the scrollview pages horizontally.

Hope that makes sense.

**Comment by wellyshen** [comment]
Duplicated with #1711

**Comment by kelset** [comment]
Thanks @wellyshen for reporting, closing this one in favor of the other one.
