### ISSUE TITLE
Programatically change TabNavigator background color

### ISSUE THREAD

**Issue by Noitidart** [react-community/react-navigation#2584]
In my app, my users are allowed to change color theme. I want to dynamically change the background color of the tab strip in `<TabNavigator>`, is this possible?

**Comment by matthamil** [comment]
Are you trying to change the color of the tab inside the tab bar or the screen?

**Comment by Noitidart** [comment]
I was trying to modify style backgroundColor. Thanks sir for your reply.

**Comment by kelset** [comment]
Closing in favor of this https://github.com/react-community/react-navigation/issues/2818
