### ISSUE TITLE
onNavigationStateChange does not fire on initial route

### ISSUE THREAD

**Issue by msageryd** [react-community/react-navigation#2588]
I don't know if this is by design or a bug.

I switch the root of my routes depending on login-status. If user is not logged in I render my `<LoginRouter>`, otherwise I render my `<AppRouter>`.

I handle the initial route manually for now, but it would be a better solution if react-navigation fired an onNavigationStateChange on the initial route as well.

**Comment by niocncn** [comment]
same here

**Comment by kelset** [comment]
Closing in favor of https://github.com/react-community/react-navigation/issues/2409
