### ISSUE TITLE
Support iPhone X

### ISSUE THREAD

**Issue by DaleJefferson** [react-community/react-navigation#2589]
What is the plan for supporting the iPhone X?

This is what things looks like currently (Body intentionally removed).

![screen shot 2017-09-14 at 11 49 36](https://user-images.githubusercontent.com/375005/30480358-448faeac-9a11-11e7-97e6-2b0f7bc12674.png)

It should have margins like this.

![pasted image at 2017_09_14 11_54 am](https://user-images.githubusercontent.com/375005/30480273-e8d55fbc-9a10-11e7-8287-b5ba9fb31e84.png)

Is this something React Navigation will handle automatically in a future release?

**Comment by admmasters** [comment]
FWIW - this is not trivial by any means.

**Comment by spencercarli** [comment]
Was just about to make an issue about this! Absolutely something React Navigation will handle 😄

**Comment by spencercarli** [comment]
This could be a good reference - [Building Apps for iPhone X](https://developer.apple.com/videos/play/fall2017/201/)

**Comment by Noitidart** [comment]
I don't know if that "microphone"/"black bar at bottom" will be there. Here is image taken from their iPhone X splash -

![](http://i.imgur.com/Y5974bq.png)

we see there is no mic there.

**Comment by satya164** [comment]
https://blog.prototypr.io/designing-for-the-iphone-x-4239d5ac736c

**Comment by spencercarli** [comment]
![iphonex](https://user-images.githubusercontent.com/1105429/30490627-1f991112-9a00-11e7-924c-9fabc8f20683.gif)

Did a little bit of prototyping this morning (just a _very_ rough pass). I'm not sure how we'll detect that it's an iPhoneX because the result of `Dimensions.get('window')` is the same as a normal 4.7inch iPhone screen. Again, was just a super fast look at it so I might have missed something.

**Comment by satya164** [comment]
Have you taken a look at the `Platform` module? Maybe a constant could be exposed in the module if not exposed already.

**Comment by spencercarli** [comment]
I was mistaken about `Dimensions.get('window')`. Height on iphoneX = 812, iphone 8 = 667.

**Comment by matthamil** [comment]
An exposed constant in `Platform` would be a good solution imo @satya164

**Comment by spencercarli** [comment]
Here's what I [had to do](https://github.com/spencercarli/react-navigation-iphonex-test/commit/a5fc58fcf23eda37daa966f5a763a6f65df0d738) to get it to work. Only tested on portrait

**Comment by brunolemos** [comment]
I just wish it was not a 100% javascript navigation library, so it could have a native side that would do this job automatically instead of having to make all these workarounds on js side :/

**Comment by brentvatne** [comment]
@brunolemos - there are other libraries that do that, you can use one of those! that's not the purpose of this library.

**Comment by brunolemos** [comment]
@brentvatne I meant like 99% javascript, but nevermind, thanks.

**Comment by grabbou** [comment]
I think there's already an external module that provides all device information, including user agent like string.

That would be very useful to incorporate into DeviceInfo module in React Native I guess.

**Comment by brentvatne** [comment]
> @brentvatne I meant like 99% javascript, but nevermind, thanks.

oh ok, that wasn't clear. not sure what you mean by workarounds as the only way to have it just handled out of the box would be to use uikit. if you mean expose some device info that lets you know the device model and safe areas, i agree!

**Comment by ide** [comment]
I suspect the way to go about this is to get the status bar height and/or safe area bounds and insets from the native layer and send it to JS. This lets us avoid code like `if (device is iPhone X) { set header height to 109px }`.

**Comment by spencercarli** [comment]
Put together a potential PR for this (#2617). There are a few other interactions/changes in iOS11 that we might want to handle in a different PR. I'm not sure of all the UI changes in iOS11 (I keep finding new ones like the new landscape tab bar) so if there are tasks missing in that PR let me know.

**Comment by LeoNatan** [comment]
Everyone here putting magic numbers, how about you actually push FB to solve the problem for real? Yoga, the layout library in RN, should take into account safe area and layout margins when doing flex layout. That's the real solution, not these magic numbers and `if(isPhoneX)` nonsense.

**Comment by dantman** [comment]
I agree with @ide, I'll cleanup some of the notes I made when the iPhone X was announced.

* RN's Android only StatusBar.currentHeight should be made to work on all platforms, then we can just use it
* We'll want a *"`NavigationFooter`"* API similar to the StatusBar API. On iOS this will handle iPhone X's home button area and the only useful thing will be `currentHeight`. On Android this will handle the Soft Keys API and let you control the translucency/colors much like the StatusBar API.
* And we'll want an `isTranslucent` API on both to check if they are actually translucent (this'll tell us if the iPhone X's translucent home indicator is present and also fix the react-navigation+Expo+Android issue.

**Comment by dantman** [comment]
Here's work on making it possible to get the status bar's height, without hardcoding hacks:
https://github.com/facebook/react-native/pull/16478

As a bonus I've also handled the landscape status bar.

**Comment by ptelad** [comment]
Check out my lib for helping with the iphoneX:
https://www.npmjs.com/package/react-native-iphone-x-helper

**Comment by birkir** [comment]
Is checking the height of the window really enough to determine that it's an specific device?

I am very afraid of apple adding an option to disable the notch screen area for some or all apps, there must be a better way.

**Comment by spencercarli** [comment]
Initial iPhoneX support is live with v1.0.0-beta.16!

**Comment by yoohan-dex** [comment]
how about the bottom. probably react native team will add that features until the patterns of design released?

**Comment by joncursi** [comment]
As of RN `0.50.0`, iPhone X can now be detected in a more reliable way, at least temporarily, with:

```
DeviceInfo.isIPhoneX_deprecated
```

https://github.com/facebook/react-native/commit/33f4779ed8cbab765e9a3a4f864c23133d3c754e

**Comment by freddiewanah** [comment]
Anyone know how I can publish the app that is full screen in iPhone X? 

It's full screen in Expo however, after publication, it's back to a scaled version.

**Comment by brentvatne** [comment]
@freddiewanah - maybe you built the ipa a long time ago? https://itunes.apple.com/us/app/nodevember/id1316372562?mt=8 was built yesterday with Expo and works as expected in full screen. you will need to have built your ipa since xcode9 was supported on Expo, which I believe was a just about a month ago

**Comment by freddiewanah** [comment]
@brentvatne are there anything need to be specified in app.json? 

I'm building it with expo sdk 23.0.0

**Comment by p-syche** [comment]
I set up kind of "device detection": since we ONLY need to target iPhone X that has a specific height, I wrote the following condition for my Tab Bar styles:

`bottom: ((Platform.OS === 'ios' && height === 812) ? 20 : 0)`

seems to be working correctly :)

**Comment by Jahans3** [comment]
Wrap the screens that are affected by the iPhoneX layout inside a `<SafeAreaView />`, this is a new component added in later RN versions specifically for cases like these

**Comment by Noitidart** [comment]
@Jahans3 may you please link to docs/code for `SafeAreaView`?

**Comment by Jahans3** [comment]
@Noitidart Couldn't find anything in the official docs unfortunately, however I'm using it in production in RN 0.51.

Here's an example from the repo: https://github.com/facebook/react-native/blob/master/RNTester/js/SafeAreaViewExample.js

It basically works by auto-detecting the device and adding padding accordingly, I use it in place of views on each screen that needs the protection and I've barely had to think about iPhoneX compatibility since!

**Comment by Noitidart** [comment]
Thanks @Jahans3!

**Comment by diamanthaxhimusa** [comment]
If you’re not on React Native 0.50+ yet, you can use SafeAreaView from react-navigation.

`import { SafeAreaView } from 'react-navigation';`

**Comment by lukewlms** [comment]
@p-syche Thanks - I was able to tweak your example to properly set `KeyboardAvoidingView` `keyboardVerticalOffset` to compensate for React Navigation Tab Bar offset for iPhone X.

        keyboardVerticalOffset={
          isIOS && Dimensions.get("window").height === 812 ? 85 : 65
        }

**Comment by Nasirilahi** [comment]
@diamanthaxhimusa import { SafeAreaView } from 'react-navigation' is not working for me ?

**Comment by diamanthaxhimusa** [comment]
@Nasirilahi  check your react-navigation version, try to upgrade it to latest version.

**Comment by giantss** [comment]
@diamanthaxhimusa
 import { SafeAreaView } from 'react-navigation'  
How to fit iPhone X? Can you give me an example?🙏

**Comment by diamanthaxhimusa** [comment]
@giantss check this: [https://github.com/react-community/react-native-safe-area-view](https://github.com/react-community/react-native-safe-area-view)
`
<SafeAreaView>
  <View>
    <Text>Look, I'm safe!</Text>
  </View>
</SafeAreaView>
`
