### ISSUE TITLE
react-navigation default screen

### ISSUE THREAD

**Issue by vijay-dadhich09** [react-community/react-navigation#2590]
Hi I want to show 5 tabs (MyPlanner, Seminars and The Market etc) plus default home screen. The very first screen is Home screen and all the tabs will be display on home screen and no tab will be selected. I tried with TabNavigator but there is no provision to add Home as default screen in Tah bNavigator.
Code..

```js
const MainNavigation = StackNavigator({
  _home: {
    screen: Home
  },
  _exhibitorDirectory: { screen: ExhibitorDirectory },
  _myPlannerStack: {
    screen: StackNavigator({
      _myPlanner: { screen: MyPlanner },
      _addCustomItem: { screen: AddCustomItem }
    })
  },
  _seminarsAndEvents: { screen: SeminarsAndEvents },
  _shuttlesAndMaps: { screen: ShuttlesAndMaps },
  _theMarket: { screen: TheMarket }
});

```

**Comment by matthamil** [comment]
You're wanting to display a set of tabs without one selected?

**Comment by vijay-dadhich09** [comment]
Yes,  n that is home page.

**Comment by vonovak** [comment]
@vijay-dadhich09 I'm not sure what exactly you want to achieve, can you update the description?

**Comment by vijay-dadhich09** [comment]
Actually, I don't understand yr request. Can you please explain yr
requirement? I m quite confident for any challenge in terms of react n
react native.

Regards
Vijay D

**Comment by kelset** [comment]
Pinging OP @vijay-dadhich09 since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open (does it still happen in the latest version?); if I get no answer in the next 7 days I will close it.

**Comment by kelset** [comment]
Hi there @vijay-dadhich09,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.
