### ISSUE TITLE
How do I pass arguments to react when I use custom router?

### ISSUE THREAD

**Issue by xiaoyongchen** [react-community/react-navigation#2596]
## Before You Start...
The issue list is reserved exclusively for bug reports and feature requests. That means we do not accept usage questions.

For usage questions, please use the following resources:

- [Read the docs](https://reactnavigation.org/)
- [Ask on the Reactiflux (#react-navigation)](https://discord.gg/reactiflux)
- [Look for / ask questions on StackOverflow](https://stackoverflow.com/questions/tagged/react-navigation)
- Also try to search for your issue - it may have already been answered or even fixed in the development branch. However, if you find that an old, closed issue still persists in the latest version, you should open a new issue.

---

### Current Behavior
- _If describing a bug, tell us what happens. Provide a screenshot when possible and full code sample_
- _If suggesting a change/improvement, explain the difference from current behavior_

### Expected Behavior
1.  
RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:[ReactAppContext sharedContext].sharedBridge moduleName:[self getReactModulesName] initialProperties:@{@"tid":@"17"}];
    rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];
    rootView.frame = self.view.bounds;
    rootView.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight;
    [self.view addSubview:rootView];

2. 

 render() {
        return (
            <Provider store={store}>
                <View style={{flex:1,backgroundColor:'#ffffff'}}>
                    <OnlyRegionRouter {...this.porps}/>
                    <InfoModal/>
                    <LoadingModal/>
                    <ShareModal/>
                </View>
            </Provider>
        );
    }
    
3.
// 配置自定义导航
//import liraries
class InviteFriendNavigationState extends Component {
    static propTypes = {
        dispatch: PropTypes.func.isRequired,
        nav: PropTypes.object.isRequired,
        sid:PropTypes.string.isRequired,
        mobile:PropTypes.string.isRequired,
    }
    render() {
        let {dispatch,nav,sid} = this.props;
        return (
            <AppNavigator navigation={addNavigationHelpers({ dispatch, state: nav })} sid={sid} />
        );
    }
}

export default connect((state) => {
    return {
        nav: state.onlyRegionNav,
    };
}, (dispatch) => {
    return {
        
    };
})(InviteFriendNavigationState);
### Your Environment
- Debug

| software         | version
| ---------------- | -------
| react-navigation |^1.0.0-beta.11",
| react-native     |2.0.1
| node             |v7.9.0
| npm or yarn      |4.2.0

**Comment by kelset** [comment]
Invalid bug
