### ISSUE TITLE
React-native how to navigate to stackNavigator page from outside header component

### ISSUE THREAD

**Issue by vijay-dadhich09** [react-community/react-navigation#2604]
Hi I want to open a stackNavigator page from outside component of header and footer. I have different buttons on the footer and want to open different stackNavigator pages onPress. The this.props.navigation not exist in the custom component then how to access navigator?
Code..
const MainNavigation = StackNavigator({
      _home: {
        screen: Home,
      },
      _myPlannerStack: {
        screen: StackNavigator({
          _myPlanner: { screen: MyPlanner },
          _addCustomItem: { screen: AddCustomItem },
        }),
      },
      _exhibitorDirectory: { screen: ExhibitorDirectory },
      _seminarsAndEvents: { screen: SeminarsAndEvents },
      _shuttlesAndMaps: { screen: ShuttlesAndMaps },
      _theMarket: { screen: TheMarket },
    });

<Container>
        <HeaderContainer />
        <MainNavigation />
        <FooterContainer />
      </Container>

**Comment by vijay-dadhich09** [comment]
this post have same issue which I am facing...
https://stackoverflow.com/questions/45751497/how-to-link-from-outside-into-navigator-for-example-from-a-global-footer/45751950?noredirect=1#comment78480828_45751950

**Comment by vonovak** [comment]
closing since the question was answered on SO
