### ISSUE TITLE
BackHandler don't work with TabNavigator

### ISSUE THREAD

**Issue by Sean-Snow** [react-community/react-navigation#2611]
### Current Behavior
``BackHandler`` in ``TabNavigator`` does't work.

This is my code structure ：
```
StackNavigator
----TabNavigator
--------Home
--------User
----Setting
```
i listene ``backPress`` in root Element. When I go from User to Setting。 the ``backPress `` did not perform

### Your Environment
| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.12
| react-native     | 0.48.3
| node             | v8.4.0
| npm or yarn      | yarn

**Comment by justinlok** [comment]
Do you have backBehaviour configured?
https://reactnavigation.org/docs/navigators/tab

**Comment by Sean-Snow** [comment]
my ``backBehaviour`` is none
```
  tabBarComponent: TabBarBottom,
  tabBarPosition: 'bottom',
  tabBarOptions: {
    style: styles.tabBar,
    activeTintColor: main
  },
  backBehavior: 'none',
  swipeEnabled: false
```

**Comment by MSSPL-PiyaleeMaiti** [comment]
In my App we not set any backBehavior so it's default set to intial route. Now we implement BackHandler, but hardwareBackPress event not effect in tabbarNavigation. Its only happen in tabbar navigaiton but it properly working in stack navigation. Can't find any solution for this. Can anyone help us to resolve the issue.

**Comment by gcmartins93** [comment]
This issue shouldn't be closed, since it's an unexpected behaviour. In order to allow behaviour's customization, customs listeners should've precedence over navigation specific listeners, even in this case where we choose _backBehavior_ to _initialRoute_. What if we want the initialRoute behaviour only if none of our custom listeners return true?
