### ISSUE TITLE
ScrollView / ListView inside modal doesn't work

### ISSUE THREAD

**Issue by ahanriat** [react-community/react-navigation#262]
**Platform**: **iOS**

**Issue**:  ScrollView is buggy with `StackNavigation` and `mode: 'modal'`.

Hi guys!

It's an old issue with the navigationExperimental, if you don't set the `gestureResponseDistance` or disable the `gesturesEnabled`, a *ScrollView* / *ListView* in a modal won't get the touch events for scrolling.

I would love to make a PR to fix this issue, but first I would like you to help me find the best solution:
- Proposition 1: in the [CardStackPanResponder](https://github.com/react-community/react-navigation/blob/master/src/views/CardStackPanResponder.js#L119) Add some default value to `gestureResponseDistance` when the direction is 'vertical'.
- Proposition 2: Add default Props for `gestureResponseDistance` in the [CardStack](https://github.com/react-community/react-navigation/blob/master/src/views/CardStack.js#L150)
- Proposition 3: Maybe it's already possible, but if not, allow to set the `gestureResponseDistance` and `gesturesEnabled` props.

Thanks for your help !

🚀

**Comment by satya164** [comment]
Is this iOS or Android? Because I remember with Navigation Experimental, it used to work correctly on Android.

**Comment by ahanriat** [comment]
@satya164  It is on IOS only (description updated) ;)

**Comment by davideweaver** [comment]
It would be great to be able to disable the gesture on the modal to prevent the screen from being swiped away. This is important when using a modal for a login screen.

**Comment by hilkeheremans** [comment]
See also PR #385

**Comment by smkhalsa** [comment]
Any update on this?

**Comment by RichardLindhout** [comment]
@smkhalsa You can do something like this

`
import {
  StackNavigator as stackNavigator,
  // TabNavigator as tabNavigator,
  // TabView as tabView,

} from 'react-navigation'


import Login from './routes/Login'
import Home from './routes/Home'
// import Account from './routes/Account'
// import Detail from './routes/Detail'
import EditTimer from './routes/EditTimer'

// const HomeNavigator = tabNavigator(
//   {
//     Home: { screen: Home },
//     Account: { screen: Account },
//   },
//   {
//
//     tabBarComponent: tabView.TabBarBottom,
//     tabBarPosition: 'bottom',
//     swipeEnabled: false,
//     animationEnabled: true,
//     lazyLoad: true,
//   }
// )
const MainNavigator = stackNavigator(
  {
    Home: { screen: Home },
    EditTimer: { screen: EditTimer },
  },
  {
    cardStyle: {

      opacity: 1,
    },
    navigationOptions: {


      header: {
        tintColor: 'rgba(255,255,255,0.8)',
        titleStyle: {
          color: 'rgba(255,255,255,0.8)',
          fontWeight: '400',
        },
        style: {
          backgroundColor: 'rgba(69,37,200,0.8)',
          shadowColor: 'rgba(69,37,200,0.8)',
          shadowOpacity: 1,
          shadowRadius: 3,
          shadowOffset: {
            height: 3,
            width: 0,
          },
        },
      },
    },
    headerMode: 'float',
  }
)

const Router = stackNavigator(
  {
    Main: { screen: MainNavigator },
    Login: { screen: Login },
  },
  {
    headerMode: 'none',
    mode: 'modal',
    cardStyle: {
      opacity: 1,
    },
    navigationOptions: {
      cardStack: {
        gesturesEnabled: true,
      },
    },

  }
)


export default Router
`

**Comment by smkhalsa** [comment]
@RichardLindhout Thanks, I ended up just disabling gestures in my screen

**Comment by RichardLindhout** [comment]
@smkhalsa Me too!

**Comment by RichardLindhout** [comment]
A workaround for scrolling + modal gestures could be.
Use the library from @satya164 
https://github.com/satya164/react-navigation-addons

Your Router
```
const MainNavigator = enhance(stackNavigator)(
  {
    Home: { screen: Home },
    EditTimer: { screen: EditTimer },
  },
  {
    navigationOptions: {
      cardStack: {
        gesturesEnabled: true,
      },
    },
    headerMode: 'screen',
    mode: 'modal',

  }
)

```


Your modal screen

```
import React, { Component } from 'react'
import {
  ScrollView,
} from 'react-native'

import binder from '../../logic/shared/helpers/binder'


class EditTimer extends Component {
  constructor(props) {
    super(props)

    binder(this, ['_handleScroll'])
  }
  _handleScroll(event) {
    if (event.nativeEvent.contentOffset.y < 10) {
      if (!this.closeViaGestures) {
        this.closeViaGestures = true
        this.props.navigation.setOptions('cardStack', {
          gesturesEnabled: true,
        })
      }
    } else if (this.closeViaGestures) {
      this.closeViaGestures = false
      this.props.navigation.setOptions('cardStack', {
        gesturesEnabled: false,
      })
    }
  }

  render() {

    return (
        <ScrollView
          onScroll={this._handleScroll}
          scrollEventThrottle={16}
          overScrollMode={'never'}
          bounces={false}
          alwaysBounceVertical={false}
          style={{ flex: 1 }}
        >

          

        </ScrollView>


    )
  }
}


EditTimer.PropTypes = {

}
EditTimer.defaultProps = {

};


EditTimer.navigationOptions = {
  title: ' ',

 
}

export default EditTimer


```

If you want to hide the header, don't do it the default way but on the screen where you want to hide in .navigationOptions {}

```
 header: {
    style: {
      opacity: 0,
      height: 0,
      width: 0,
      overflow: 'hidden',

      backgroundColor: 'transparent',
    },
  },
```

If you hide it another way it'll break the gestures enabled prop somehow xD.

**Comment by spencercarli** [comment]
Gonna close for inactivity (cleaning up issues)
