### ISSUE TITLE
navigationOptions changes do not hot reload

### ISSUE THREAD

**Issue by Jakst** [react-community/react-navigation#2623]
### Current Behavior
When editing for example the headerStyle.backgroundColor of a StackNavigation screen, the change is not reflected in a hot reload. A hot reload is triggered, bu nothing changes. Tested on both iOS and Android.

Rebuilding through XCode or doing `react-native run-android` does trigger the change.

### Expected Behavior
The changed property should be updated on the device by the triggered hot reload

### Your Environment
The project is setup with create-react-native-app and ejected to React Native (removing expo).

Started using react `react-native start` and triggering a build through XCode.

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.11
| react-native     | 0.48.3
| node             | 8.5.0
| yarn              | 1.0.2

Example code:
```js
import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { StackNavigator } from 'react-navigation';

class HomeScreen extends React.Component {
  static navigationOptions = {
    title: 'App title'
  }
  
  render() {
    return (
      <View>
        <Text>Open up App.js to start working on your app!</Text>
        <Text>Changes you make will automatically reload.</Text>
        <Text>Shake your phone to open the developer menu.</Text>
      </View>
    );
  }
}

export default StackNavigator({
	Home: { screen: HomeScreen }
})
```

**Comment by vonovak** [comment]
you do not need to rebuild the project for this - just reload the app (the rage shake gesture of cmd+r on ios emulator, or cmd+m on android emulator, if I'm not mistaken).

**Comment by Jakst** [comment]
No, that does not work either.

**Comment by vonovak** [comment]
@Jakst that means your setups is somehow broken.

**Comment by fpoumian** [comment]
I'm having this exact same issue on Android, react-navigation 1.0.0-beta.19 and react-native 0.49.

I think it might be related to:
https://github.com/facebook/react-native/issues/15363
https://github.com/facebook/react-native/issues/10991

**Comment by kelset** [comment]
Pinging OP @Jakst since this issue has not been active for a while, and it's related to an old version of the lib.

Moreover as pointed out by @fpoumian it looks like it's a RN issue.

Please let me know if you want this to remain open (does it still happen in the latest version?); if I get no answer in the next 7 days I will close it.

**Comment by Jakst** [comment]
I cannot reproduce anymore. Closing.
