### ISSUE TITLE
[Android] TabNavigator incredibly slow when tabs have content (FlatList)

### ISSUE THREAD

**Issue by Maxeh** [react-community/react-navigation#2627]
### Current Behavior
I have a TabNavigator inside of a StackNavigator and the behavior when a tab is pressed is extremly laggy when the tabs include a FlatList (or ListView). When the tabs dont have any content, then there are no lags and everything works like in the Expo example. The array of the FlatList only has 10 entries (rows).

### Environment
Samsung Galaxy S6, Debug mode is turned off (with debug the app is not really usable anymore because of extreme lags).

**react-native**: 0.46
**react-navigation**: newest version from master branch (commit 2b40182cd72861691956f059e56535c1994abd57)

**Comment by matthamil** [comment]
Can you make a repo showing code that reproduces this?

**Comment by Maxeh** [comment]
@matthamil I think I have resolved the issue by changing "Component" to "PureComponent" in my FlatList. Now, the tabs change more smoothly. 

I guess the FlatList was re-rendering all the time when I used "Component" and changed the tabs.

**Comment by matthamil** [comment]
Glad you got it resolved :). Do you think it's resolved enough to close the issue?

**Comment by Maxeh** [comment]
Yes I think that was the reason. However, quite strange that it laged so much when I used "Component", even though the FlatList only had 10 rows.
