### ISSUE TITLE
Drawer showing under header, blank header title

### ISSUE THREAD

**Issue by Noitidart** [react-community/react-navigation#2628]
I accidentally got my drawer to show underneat the header. I don't know how I did this but its awesome I like it.

However when the drawer is open, it blanks out the `headerTitle`. Is it possible to not blank it and make it retain whatever title it is?

Here is screencast - https://gfycat.com/HiddenSoftCatbird

GIF of screencast

![](https://thumbs.gfycat.com/HiddenSoftCatbird-max-14mb.gif)

**Comment by matthamil** [comment]
You're most likely rendering a DrawerNavigator inside a StackNavigator, which is why the drawer appears behind the header bar.

**Comment by Noitidart** [comment]
Thanks @matthamil  - is there anyway to control the label while the menu is open?

**Comment by codesinghanoop** [comment]
is there any solution for it ?

**Comment by kelset** [comment]
Duplicate https://github.com/react-community/react-navigation/issues/374
