### ISSUE TITLE
How to disable navigation drawer swipe gesture in particular screen?

### ISSUE THREAD

**Issue by lohithananda** [react-community/react-navigation#2630]

**Comment by linkinmedo** [comment]
A fix for this has been merged like 4 hours ago in #1377 , you'll just have to wait for the new release to use it.

**Comment by matthamil** [comment]
Closing since this should be resolved with the next release.

**Comment by t407289575** [comment]
when about the next release @matthamil

**Comment by dbyilmaz** [comment]
@t407289575 
is it solve this problem?
They can't hear you :+1:
