### ISSUE TITLE
DrawerNavigator组件的navigation.navigate('DrawerClose')的问题

### ISSUE THREAD

**Issue by qw110946** [react-community/react-navigation#2636]
我的导航路由大概是这样的

      const App = StackNavigator({
        HomeStack: {
          screen: Home,
          // ...
        },
        HistoryStack: {
          // ...
        },
        DownloadStack: {
          // ...
        }
      },{
          // ...
      });

然后Home大概是这样

      const MyApp = DrawerNavigator({
        HomeDrawer: {
          // ...
        },
        BangumiDrawer: {
          // ...
        },
        HistoryDrawer: {
          // ...
        },
        DownloadDrawer: {
          // ...
        },
      },{
        contentComponent: props => (
          <ScrollView>
            <DrawerItems
              {...props}
              onItemPress={
                ({route}) =>  {
                  props.navigation.navigate('DrawerClose');
                  props.navigation.navigate('HistoryStack');
                  /*
                    我这样跳StackNavigator的路由的话
                    props.navigation.navigate('DrawerClose'); 貌似没有执行,总之左侧的滑出没有退回去
                    但如果改成这样是可以退回的
                      setTimeout(() => props.navigation.navigate('HistoryStack'), 0);
                      不知道我写的有问题，还是库有问题
                  */
                }
              }
            />
          </ScrollView>
    
        )
      });
    
      export default MyApp;

环境
    react: 16.0.0-alpha.12
    react-native: 0.48.3
    react-navigation: ^1.0.0-beta.11
表达不太好，求解决

**Comment by vonovak** [comment]
this is being handled in #1313

**Comment by qw110946** [comment]
OK

**Comment by kelset** [comment]
#1313 was merged, closing
