### ISSUE TITLE
Customize navigation header button 

### ISSUE THREAD

**Issue by assafb81** [react-community/react-navigation#2638]
I am using Redux with my react navigation and my screens are written in a routes.js file that looks something like:

Routes.js:
```
import screenA from '../screens/screemA';
import screenB from '../screens/screemB';
import screenC from '../screens/screemC';

const Routes = {
  Main: {
    screen: screenA,
    navigationOptions: {
        title: 'screenA',
    },
  },
  Second: {
    screen: screenB,
    navigationOptions: {
        title: 'screenB',
    },
  },
  Third: {
    screen: screenC,
    navigationOptions: {
        title: 'screenC',
    },
  },
};

export default Routes;
```

export default Routes;
Routes is used in another file and the navigation works fine.
I want to add a header button, I have a component called 'HeaderButton' that I want to add to screenA and screenB.

my versions:
react: 16.0.0-alpha.12
react-native: 0.45.1
react-navigation: 1.0.0-beta.11

how can I do that?
Routes is not a JSX scope, any thoughts so I can't do something like:

Routes.js
```
import HeaderButton from '../components/HeaderButton';
....
Main: {
    screen: screenA,
    navigationOptions: {
        title: 'screenA',
        headerRight: <HeaderButton />,
    },
},
```

routes.js is used in app navigator:

```
import React from 'react';
import PropTypes from 'prop-types';
import { connect } from 'react-redux';
import { addNavigationHelpers, StackNavigator } from 'react-navigation';

import Routes from '../config/routes';

export const AppNavigator = StackNavigator(Routes, {});

const AppWithNavigationState = ({ dispatch, nav }) => (
    <AppNavigator
        navigation={addNavigationHelpers({
            dispatch,
            state: nav,
        })}
    />
);

AppWithNavigationState.propTypes = {
    dispatch: PropTypes.func.isRequired,
    nav: PropTypes.object.isRequired,
};

const mapStateToProps = state => ({
    nav: state.nav,
});

export default connect(mapStateToProps)(AppWithNavigationState);
```

**Comment by assafb81** [comment]
My solution
I moved `navigationOptions` from Routes.js to my container.

static navigationOptions = ({ navigation )} => ({
  title: 'screenC',
  headerRight: <HeaderButton navigation={navigation} />,
}),

**Comment by vonovak** [comment]
this can probably be closed

**Comment by markmiller21** [comment]
@assafb81 I think you meant

`
static navigationOptions = ({ navigation }) => ({
  headerRight: <HeaderButton navigation={navigation} />,
});
`

but other than that, it worked for me as well
