### ISSUE TITLE
`mode` property on sub screen not working

### ISSUE THREAD

**Issue by digital-flowers** [react-community/react-navigation#2645]
following the example of this project "https://github.com/allpwrfulroot/yaba-social", I have created a sub StackNavigator, all properties works fine for the sub navigator but `mode: "modal"` is not working !!!
**Note:** the transition doesn't start from the bottom as described in the documentation, if i change it for the parent StackNavigator all screens acts as a modal

```javascript
import {StackNavigator} from 'react-navigation';
import Home from "./home";
import Login from "./login";
import Signup from "./signup";
import Boot from "./boot";
import AddPostModal from "./add-post-modal";

export default StackNavigator({
  Boot: {
    screen: Boot
  },
  Home: {
    screen: Home
  },
  Login: {
    screen: Login
  },
  Signup: {
    screen: Signup
  },
  AddPostModal: {
    screen: StackNavigator({
      Home: {
        screen: AddPostModal
      }
    }, {
      headerMode: "none",
      mode: "modal"
    })
  }
}, {
  headerMode: "none",
  initialRouteName: 'Boot',
  mode: "card"
});
```

**Comment by spencercarli** [comment]
Currently `mode` isn't a per-screen option.  It's a per navigator option. [Docs](https://reactnavigation.org/docs/navigators/stack#StackNavigatorConfig)

**Comment by digital-flowers** [comment]
But as can you see in my code i have created a separated `StackNavigator` for  the `AddPostModal` screen !

**Comment by digital-flowers** [comment]
And btw: 
1- this is not a question
2- i really hate the idea that you just decided to close the issue, without even waiting for my reply, i guess this is not how an official library should be operated !!!

**Comment by dccarmo** [comment]
@digital-flowers From my understanding setting `modal` on `AddPostModal` only affects transitions on screens registered with this navigator.

**Comment by digital-flowers** [comment]
@dccarmo exactly, `AddPostModal` has it is own StackNavigator but it seems something wrong with the way this module share options between instances

**Comment by golestanirad** [comment]
@spencercarli   AddPostModal has it is own StackNavigator. so what isn't it having its own mode?
