### ISSUE TITLE
Navigate to same screen but go back still display newest content

### ISSUE THREAD

**Issue by longtranista** [react-community/react-navigation#2654]
I have Home screen (H) and Product detail screen (P) in Stack navigation. 
In Product detail screen I have another products (recommendation products) which will navigate to another Product detail screen. 
My problem is when I navigate from Product detail screen to another Product detail screen, then I goBack(), the back Product Detail screen is still display the same (The newest one).

Home -> Product Detail (1) -> Product Detail (2) -> Product Detail (3) 
Then I back: 
Product Detail (3) -> Product Detail (3) -> Product Detail (3) -> Home

It seems like when Product Detail page is added to Stack but the page content is not saved for different products.

My environments:
React-native: 0.42.3
react-navigation: 1.0.0-beta.12

Sorry for my english! 
Hope someone can address my problem!

**Comment by spencercarli** [comment]
We need more info to help. Are you using redux? Can you put together a demo of this issue?

**Comment by longtranista** [comment]
@spencercarli 
I don't use redux. 
Here is my code:
AppNavigation.js
`const Tabs = {
  RankingScreen: { screen: RankingScreen },
  ScanScreen: { screen: BarcodeScreen },
  UserScene: { screen: UserScene }
}

// Manifest of possible screens
const PrimaryNav = StackNavigator({
  Tab: {
    screen: TabNavigator(
      Tabs,
      {
        initialRouteName: 'RankingScreen',
        // lazy: true,
        tabBarPosition: 'bottom',
        tabBarOptions: {
          activeTintColor: Colors.orange,
          labelStyle: {
            fontSize: 11,
          },
          style: {
            backgroundColor: Colors.snow,
            paddingVertical: 2,
            height: 52
          }
        }
      }
    )
  },
  BrandScreen: { screen: BrandScreen },
  Intro: { screen: Intro },
  SearchScene: { screen: SearchScene },
  SearchResult: { screen: SearchResult },
  ProductScreen: { screen: ProductScreen, path: 'product/:code' },
  FavoriteScene: { screen: FavoriteScene },
  HistoryScreen: { screen: HistoryScreen },
  SettingScreen: { screen: SettingScreen },
  SplashScreen: { screen: SplashScreen },
  CategoryScreen: { screen: CategoryScreen },
  About: { screen: About },
}, {
  // Default config for all screens
  headerMode: 'none',
  initialRouteName: 'SplashScreen',
  navigationOptions: {
    headerStyle: styles.header
  }
})

export default PrimaryNav`

In HomeScreen I have a list view like this. 
`renderRow (rowData) {
    const {navigate} = this.props.navigation
    return (
      <TouchableOpacity
        style={styles.row}
        onPress={() => navigate('ProductScreen', {code: rowData.ean})} >
        <Image
          resizeMode={'contain'}
          style={styles.thumbnail}
          source={{uri: rowData.medium_image_url}} />

        <Text
          numberOfLines={2}
          style={styles.name}>{rowData.name.trim()}</Text>

        <Text style={styles.brand}>{rowData.category}</Text>

        <View style={styles.col}>
          <View style={styles.grid}>
            <Text style={styles.price}>{vnPrice}</Text>
            <Text style={styles.currency}> đ</Text>
          </View>
        </View>

        <Text style={styles.tag}>¥{jpPrice}</Text>
      </TouchableOpacity>
    )
  }`

In ProductScreen I have a list view like above. 

So When navigate from Product 1 to Product 2, then Product 3 ... When I click back button (goBack()), the Product screen is alway Product 3. Not From 3 to 2 to 1 then Home. 

I'm not sure if should I use redux instead ?

**Comment by longtranista** [comment]
I found my problem! 
I use same Redux for different instances of a Scene, so when Redux status update, all instances content will update. 

so I will close this issue.
