### ISSUE TITLE
Navigating spesific screen in nested navigators

### ISSUE THREAD

**Issue by emregurler** [react-community/react-navigation#2656]
I didn't find to navigate spesific screen. Here is my case:
I have a TabNavigator with 2 tabs which are Tab1 and Tab2 inside DrawerNavigator. Also, I have a StackNavigator which has 6 different stacks, and one of them is DrawerNavigator. Now I wanna solve this problem: When I am on one of Stacks, I want to navigate Tab1 inside Drawer after clicking a button in the Stack. How can I do that? I found that some issues which are about changing initialRouteName, but I couldn't fit my case. Any idea ?

**Comment by keirk** [comment]
Did you see this: https://reactnavigation.org/docs/navigators/navigation-actions

So it seems you need to use the action param to navigate to a route in the child navigator. Something like this: 

`navigate('Drawer', {}, NavigationsActions.navigate({ routeName: 'Tab1'}))`

**Comment by kelset** [comment]
Closing in favor of #1715
