### ISSUE TITLE
Disable gestures on drawer and onBack

### ISSUE THREAD

**Issue by jjdp** [react-community/react-navigation#2657]
Can you dispatch an action to disable them somehow?

**Comment by vonovak** [comment]
use `drawerLockMode` to disable gestures on drawer

**Comment by rochapablo** [comment]
https://github.com/react-community/react-navigation/issues/2981

**Comment by krewllobster** [comment]
This doesn't seem to work in IOS emulator using a 'contentcomponent' in the DrawerNavigator

**Comment by brentvatne** [comment]
if @vonovak's suggestion doesn't work please create an issue with a reproducible example
