### ISSUE TITLE
1.0.0-beta.13 still has flow errors :(

### ISSUE THREAD

**Issue by joeybaker** [react-community/react-navigation#2658]
### Current Behavior

Thanks to @Ashoat's work, flow support greatly improved in https://github.com/react-community/react-navigation/pull/2619, but it looks like the built version of the package is now throwing new flow errors:

```
node_modules/react-navigation/lib-rn/utils/invariant.js.flow:0
invariant. Duplicate module provider
current provider. See: node_modules/fbjs/lib/invariant.js.flow:0

node_modules/react-navigation/lib-rn/utils/shallowEqual.js.flow:0
shallowEqual. Duplicate module provider
current provider. See: node_modules/fbjs/lib/shallowEqual.js.flow:0

node_modules/react-navigation/lib/utils/invariant.js:0
invariant. Duplicate module provider
current provider. See: node_modules/react-navigation/lib-rn/utils/invariant.js:0

node_modules/react-navigation/lib/utils/invariant.js.flow:0
invariant. Duplicate module provider
current provider. See: node_modules/fbjs/lib/invariant.js.flow:0

node_modules/react-navigation/lib/utils/shallowEqual.js:0
shallowEqual. Duplicate module provider
current provider. See: node_modules/react-navigation/lib-rn/utils/shallowEqual.js:0

node_modules/react-navigation/lib/utils/shallowEqual.js.flow:0
shallowEqual. Duplicate module provider
current provider. See: node_modules/fbjs/lib/shallowEqual.js.flow:0

node_modules/react-navigation/src/utils/invariant.js:0
invariant. Duplicate module provider
current provider. See: node_modules/react-navigation/lib-rn/utils/invariant.js:0

node_modules/react-navigation/src/utils/shallowEqual.js:0
shallowEqual. Duplicate module provider
current provider. See: node_modules/react-navigation/lib-rn/utils/shallowEqual.js:0


Found 8 errors
```

### Expected Behavior
It looks like the root of this problem is to not rely on the `fbjs` package in https://github.com/react-community/react-navigation/pull/1698. I'm pretty unclear why it's desirable to not rely on the package? We could just rely on the package again, that _should_ fix things. 

Another option is to remove `@providesModule` from each of the two files and not export their `.js.flow`files during the build. (This feels less clean to me)

Edit: Yet another option: could we not have `src/utils` not copied into `lib` and `lib-rn`?

### Your Environment
- _Include as many relevant details about the environment you experienced the bug in_

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.13
| react-native     | 0.48.3
| node             | v7.10
| yarn      | 1.0.2
| flow | 0.49.1

**Comment by Ashoat** [comment]
Hmm... for some reason, installing an NPM version of `react-navigation` leads to `src`, `lib-rn`, and `lib` folders all being present, but installing the Github master only leads to `src` being present...

**Comment by joeybaker** [comment]
Yea… it appears there's a postinstall hook that's compiling those folders. The tests don't seem to check those folders :\

**Comment by joeybaker** [comment]
Oh! Good point @Ashoat! Deleting those directories does the trick, maybe there's a way to not copy `src/utils` into the `lib*` directories?

**Comment by spencercarli** [comment]
Thanks for reporting, @joeybaker! I'll try to figure out what's going on with lib/lib-rn vs. src

**Comment by spencercarli** [comment]
The easiest thing to do would probably be removing the [@providesModules](https://github.com/react-community/react-navigation/search?utf8=%E2%9C%93&q=providesModule&type=) instances in the package so they don't conflict with React Native's. Would someone want to open a PR for that?

**Comment by hawkrives** [comment]
@spencercarli I'll try it!

**Comment by Ashoat** [comment]
Yeah, I can do it. Should be easy, since all files importing those two utils do it with the full path, so ostensibly the `@providesModule` declarations can just be removed without consequence...

**Comment by hawkrives** [comment]
@Ashoat You might be better suited than I to fix anything that breaks

**Comment by Ashoat** [comment]
Okay, here it is - #2665

**Comment by dmnd** [comment]
I'm using master but still getting a Flow error even after #2665. Here it is:

```
Error: node_modules/react-navigation/src/createNavigationContainer.js:5
  5: import { BackHandler, Linking } from './PlatformHelpers';
                                          ^^^^^^^^^^^^^^^^^^^ ./PlatformHelpers. Required module not found


Found 1 error
error Command failed with exit code 2.
```

Here's my config:

```
; React navigation tests don't typecheck:
; https://github.com/react-community/react-navigation/issues/912
<PROJECT_ROOT>/node_modules/react-navigation/.*/__tests__/.*
<PROJECT_ROOT>/node_modules/react-navigation/jest-setup.js
```

Do you have some kind of extra config to get around the PlatformHelpers issue? I noticed that the actual files are `PlatformHelpers.native.js` and `PlatformHelpers.web.js`.

**Comment by Ashoat** [comment]
I think the .flowconfig like you want is `module.file_ext=.native.js`. I'm not entirely sure, but I think this line came from the default React Native .flowconfig?

**Comment by Palisand** [comment]
@dmnd Does your project's flow version match [react-navigation's](https://github.com/react-community/react-navigation/blob/master/package.json#L77)?

@Ashoat After updating to flow >= 0.53.0, which includes [major changes to Flow's model for React](https://github.com/facebook/flow/blob/master/Changelog.md#0530), I am getting flow errors pertaining to react-navigation from within my project (and also from _`node_modules/react-navigation`_  obviously, although I'm fine with those errors because I can easily suppress them).

Here's a sample:
```
Error: app/index.js:60
           v-------------
 60:       <RootNavigator
 61:         ref={this.setRef}
 62:         onNavigationStateChange={this.handleNavigationStateChange}
 63:       />
           -^ React element `RootNavigator`
           v-------------
 60:       <RootNavigator
 61:         ref={this.setRef}
 62:         onNavigationStateChange={this.handleNavigationStateChange}
 63:       />
           -^ props of React element `RootNavigator`. This type is incompatible with
 42:   class NavigationContainer extends React.Component<void, Props<O, S>, State> {
                                                         ^^^^ undefined. See: node_modules/react-navigation/src/createNavigationContainer.js:42
```
This particular error owes itself to the fact that typing components post flow 0.53.0 must be done as follows:
``` javascript
class NavigationContainer extends React.Component<Props, State> { ...
                                               // ^^^^^^^^^^^^
```
**Will support for flow versions >= 0.53.0 come any time soon?**

**Comment by dmnd** [comment]
@Palisand I'm on Flow 0.52.0, but react-navigation is 0.51.0. That could be the explanation.

**Comment by Ashoat** [comment]
Latest stable React Native version line is 0.48, which is [still on Flow 0.51.0](https://github.com/facebook/react-native/blob/0.48-stable/.flowconfig#L55). `react-native-git-upgrade` automatically maintains the `[version]` declaration in your `.flowconfig` for you.

I'm excited for those Flow updates! I accidentally came across the [documentation](https://flow.org/en/docs/react/types/) for those the other day, and was confused when they didn't seem to work in my local version, haha.

Seeing as those changes will likely be breaking in both directions, we'll likely need to make a breaking switch over to the new version at some point (unless somebody knows a way to avoid that?). Probably makes sense to at least wait until RN 0.49, which should ostensibly release any day now, and comes with Flow 0.53.0.

**Comment by Palisand** [comment]
@Ashoat Yeah, that makes sense. I've got my fair share of RN flow errors because 0.48.4 user flow 0.49.1. Judging from the the latest RN [release label](https://github.com/facebook/react-native/releases/tag/v0.49.0) "v0.49.0", the next release is coming very soon, as you said.

**Comment by Palisand** [comment]
I don't know if any work has begun on since the 0.49 RN release, but after forking and running `npm flow`, there were no reported errors (as expected), and after upgrading to flow 0.53.0, I am seeing 924 (and 937 for 0.54.0).

**Comment by Palisand** [comment]
I have tried and failed to update react-navigation to support flow 0.53.0. I do not have enough experience with flow to refactor the typing going on in this project. Something that left me stumped was updating `ReactClass`:

```javascript
// src/TypeDefinition.js

export type NavigationScreenComponent<T, Options> = ReactClass<T> & {
  navigationOptions?: NavigationScreenConfig<Options>,
};
```
I erroneously thought substituting in `React.ComponentType<T>` would do the trick.

For the react-native-tab-view dependency, I have made a [PR](https://github.com/react-native-community/react-native-tab-view/pull/361) that eliminates all but 2 errors (arising from react-native 0.49.0).

**Comment by Ashoat** [comment]
One thing that makes it a little annoying to upgrade react-navigation to Flow 0.53 now is that the NavigationPlayground example in the repo is set up using Expo, and Expo versions tend to trail React Native ones by a couple weeks.

**Comment by h-michael** [comment]
I think type def should be hosted by flow-typed, because anyone could use several versions flow.
What do you think about this ?

**Comment by Ashoat** [comment]
@h-michael - that's a good point, since the Flow 0.53 version will be incompatible with earlier versions. However, I'm not familiar with an automatic way to generate library definitions from a package, and I'm not sure how to keep older library versions in sync for newer versions of react-navigation as the underlying source gets updated.

**Comment by h-michael** [comment]
@Ashoat 
> I'm not familiar with an automatic way to generate library definitions from a package,

At first there is such command which is [flow gen-flow-files](https://github.com/facebook/flow/releases/tag/v0.32.0).
But I do not know how reliable it is.

> I'm not sure how to keep older library versions in sync for newer versions of react-navigation as the underlying source gets updated.

Unfortunately there is no good way for now.
This problem is being discussed on this [issue](https://github.com/facebook/flow/issues/4917).

**Comment by Ashoat** [comment]
Unfortunately, looks like `flow gen-flow-files` doesn't seem to work on the package main file:

```js
ashoat@Ashoats-MacBook-Pro [~/Dropbox/src/react-navigation]# flow gen-flow-files src/react-navigation.js
Error: Failure("/Users/ashoat/Dropbox/src/react-navigation/src/react-navigation.js: Failure(\"Internal Error: Unexpected method type: IntersectionT\")")
```

When run on other files, it outputs a result with import statements (generally on TypeDefinition.js), which doesn't match what flow-typed needs. On top of that, flow-typed libdefs need test files as well.

It seems like dealing with flow-typed libraries is a significant bit of work, since they would need to be maintained separately and kept in sync with the react-navigation library. I personally don't have the spare time for it, and I'm content to just sync my react-navigation version to a particular react-native and corresponding flow-bin version. But I'm sure a pull request (to the flow-typed repository, ostensibly?) would be welcome. And I'm betting that as this library stabilizes, it will make more and more sense to do this, as the amount of work to maintain the flow-typed libdefs will decrease.

**Comment by spencercarli** [comment]
Hey all - it seems like there are still going to be issues with this package in regards to flow. I just published v1.0.0-beta.14 which has @Ashoat PR in it (#2665) and I hope it will at least reduce issues!

All of you commenting in this thread certainly seem to have a better grasp on Flow than I do so I certainly want to remind you that PRs are happily accepted! Be it a fix (which doesn't seem straightforward) or documentation additions to make flow usable for other devs would be greatly appreciated! 

Thank you all for your insight in regards to this issue! 😄

**Comment by Ashoat** [comment]
@spencercarli - Wait, what issues? :) `v1.0.0-beta.14` typechecks for me on my project, and master react-navigation typechecks both in the root directory and in the NavigationPlayground example!

We should probably close this issue, as with #2665 in v1.0.0-beta.14 everything works okay. The discussion above regards whether we should upgrade a libdef to flow-typed, and how we'll deal with the react-native@0.49 and flow-bin@0.53 updates, which will together introduce a whole bunch of new errors.

I think we should close this issue and open a new one for react-native@0.49. I did the latter (#2771), but I don't seem to be able to do the former.

**Comment by joeybaker** [comment]
@Ashoat good call. Closing this and we can move discussion to #2771. Thank you!

**Comment by spencercarli** [comment]
Doh! Misunderstood the discussion 😄 

> react-native@0.49 and flow-bin@0.53 updates, which will together introduce a whole bunch of new errors

new errors?! ah man haha
