### ISSUE TITLE
AccessibilityID and testID for NavBarBottom

### ISSUE THREAD

**Issue by joearasin** [react-community/react-navigation#2662]
I am integration-testing my app with Webdriver.io + Appium. When doing so, it is far easier to find components to click on by searching for testID and accessibilityID. The default tab navigator on iOS, TabBarBottom, does not expose these properties, making integration testing extremely difficult.

I am pretty sure that the default android Tab Bar does expose these properties: https://github.com/react-native-community/react-native-tab-view/blob/master/src/TabBar.js#L460

**Comment by spencercarli** [comment]
I think this would be a great addition! Would you be willing to open a PR that adds it? Here's the [TabBarBottom](https://github.com/react-community/react-navigation/blob/master/src/views/TabView/TabBarBottom.js)

**Comment by spencercarli** [comment]
Going to close this because it was added in #2684
