### ISSUE TITLE
Center React elements in header on Android

### ISSUE THREAD

**Issue by DavideValdo** [react-community/react-navigation#2664]
```
static navigationOptions = ({navigation}) => {
        firstIsActive = navigation.state.params ?  navigation.state.params.currentTab == 0 : true;
        secondIsActive = navigation.state.params ?  navigation.state.params.currentTab == 1 : false;

        return {
          tabBarVisible: false,
          headerTitle:
            navigation.state.params.vendorID ?
              <Segment style={{backgroundColor: 'transparent'}}>
                <Button style={{ borderColor: 'white', backgroundColor: firstIsActive ? 'white' : globalStyles.BLUE }} onPress={() => navigation.setParams({ currentTab: 0 })} first active={firstIsActive}>
                  <Text style={{color: firstIsActive ? globalStyles.BLUE : 'white', fontSize: 10, letterSpacing: 1}}>FEATURED</Text>
                </Button>
                <Button style={{ borderColor: 'white', backgroundColor: secondIsActive ? 'white' : globalStyles.BLUE }} onPress={() => navigation.setParams({ currentTab: 1 })} last active={secondIsActive}>
                  <Text style={{color: secondIsActive ? globalStyles.BLUE : 'white',  fontSize: 10, letterSpacing: 1}}>ALL PRODUCTS</Text>
                </Button>
              </Segment>
            :
            <Image style={globalStyles.splashLogo} source={require('../assets/logo-horizontal.png')} />
      }
    }
```
This is the result for the segment:
![screen shot 2017-09-28 at 16 13 23](https://user-images.githubusercontent.com/26572302/30971383-057a63a4-a468-11e7-8b11-df5cd114469b.png)

Logo with back arrow goes slightly on the side:
![screen shot 2017-09-28 at 16 14 08](https://user-images.githubusercontent.com/26572302/30971511-6818a0ca-a468-11e7-9367-bf51475f2eea.png)

On iOS all looks good.
Anyone got a quick fix for this? :(

npm 4.1.2
node 7.7.4
"react-native": "0.45.1",
"react-navigation": "^1.0.0-beta.11"

**Comment by spencercarli** [comment]
React Navigation aims to follow standard patterns per platform.

That being said you should be able to change this by customizing `headerTitleStyle` and setting `alignItems` to 'center'.

**Comment by DavideValdo** [comment]
Thanks. Suggested workaround did not work, which just confirms that the best way is to follow standards and differentiate UI.

**Comment by edisonywh** [comment]
@DavideValdo adding `alignSelf` to headerTitleStyle worked for me, however now I'm having the issues where it doesn't recognise my icon on the left.

**Comment by spencercarli** [comment]
Going to close this since `alignSelf` works.

@edisonywh if you think this is an issue with the library could you open up a new issue?
