### ISSUE TITLE
test coverage issues with navigationOptions.tabBar

### ISSUE THREAD

**Issue by thurt** [react-community/react-navigation#267]
Example code:
```javascript
const AppSections = TabNavigator({
  Search: { screen: Search },
  Favorites: { screen: Favorites }
}, {
  navigationOptions: {
    tabBar
  },
  tabBarComponent: TabView.TabBarBottom,
  tabBarPosition: 'bottom',
  initialRouteName: 'Search',
});
```
If you notice, I am using default `navigationOptions` and I have pulled out `tabBar` into a separately declared function for testing/coverage purposes
```javascript
// used in tabBar
const routeNameToIconName = {
  Search: 'ios-search-outline',
  Favorites: 'ios-heart-outline'
};

export const tabBar = ({ state }) => ({
  icon: ({ tintColor }) => ( // eslint-disable-line react/prop-types
    <Ionicons name={routeNameToIconName[state.routeName]} color={tintColor} size={30} />
  )
});
```
I would like to be able to make tabBar.icon an actual react component, but I can't do this because i need `state`, and `state` is only found within the closure scope. 

It seems like `state` should be passed to tabBar.icon by react-navigator, instead of relying on closure scope

thoughts?

**Comment by satya164** [comment]
Why can't you pass `state` yourself like `<Ionicons state={state} />`?

**Comment by thurt** [comment]
this works! but it means you have to also test the wrapper function (`tabBar.icon`) to get full coverage:
```javascript
export const TabBarIcon = ({ tintColor, state }) => <Ionicons name={routeNameToIconName[state.routeName]} color={tintColor} size={30} />;

TabBarIcon.propTypes = {
  state: navigationStateType.isRequired,
  tintColor: PropTypes.string.isRequired
};

/**
 * provides the base tab bar functionality for the AppSections Navigator
 * @param {navigationStateType} state
 */
const tabBar = ({ state }) => ({
  icon: ({ tintColor }) => <TabBarIcon state={state} tintColor={tintColor} />
});
```

Ideally there would be no closure scope where i'm forced to create a wrapper function that I need to separately test

**Comment by grabbou** [comment]
I am not really sure if this issue is actionable. What you @thurt ended up doing, out of curiosity? That's the way the API is designed.

**Comment by thurt** [comment]
hi @grabbou -- i havent changed anything. tabBar.icon is same as shown in my first post. 

my test looks like:
```javascript
describe('tabBar.icon', () => {
    it('matches snapshot', () => {
      const icon = tabBar({ state: navigationState }).icon({ tintColor: 'black' });
      expect(icon).toMatchSnapshot();
    });
  });
```

unfortunately, i have to use `//eslint-disable-line react/prop-types` currently for `tabBar.icon`. I'm not able to cleanly define the propTypes interface for an `tabBar.icon` component because the navigation state is not being passed.

**Comment by alecpo** [comment]
> hi @grabbou -- i havent changed anything. tabBar.icon is same as shown in my first post.
> 
> my jest test looks like:
> 
> ```js
> describe('tabBar.icon', () => {
>     it('matches snapshot', () => {
>       const icon = tabBar({ state: navigationState }).icon({ tintColor: 'black' });
>       expect(icon).toMatchSnapshot();
>     });
>   });
> ```
> 
> unfortunately, i have to use `// eslint-disable-line react/prop-types` currently for `tabBar.icon`. I'm not able to cleanly define a propTypes interface for an `tabBar.icon` component because the navigation state is not being passed along with the other icon properties (tintColor, focus).

Thanks!
