### ISSUE TITLE
component not re-mounting on navigation

### ISSUE THREAD

**Issue by rickardinho** [react-community/react-navigation#2671]
Hi, 

I have a stack navigator nested within a tab navigator with 3 screens, A and B.

If I navigate from screen A to screen B, screen B's component renders correctly.
If i then goBack to screen A, and then navigate again to screen B, screen B doesn't re-render.

This is a problem because I want my component to take account of state change, i.e. reset screen B's component state to its initial state, but screen B doesn't seem to re-render.  I would have thought that once it was popped, it would then be re-mounted when i navigate to it again?

Is this a bug?
Or have i misunderstood?  
The docs don't seem to explain how component life cycle fits with react navigation.

Is there a workaround to force the screen to re-mount?  Then i could simply reset the state in componentWillMount.

**Comment by spencercarli** [comment]
This is a misunderstanding - granted it's not communicated well.

Once I tab is mounted it's not going to be unmounted until that tab navigator is unmounted.

Check out on [tabBarOnPress](https://reactnavigation.org/docs/navigators/tab#tabBarOnPress) and see if it does what you need.

**Comment by rickardinho** [comment]
Thanks, So how can I force a props/state update of my tabbar components?  I don't see how tabBarOnPress helps.  If I change state on tabbar components A, how can I ensure B updates and rerenders?

**Comment by rickardinho** [comment]
I'm using redux in my app, but haven't hooked navigation up to redux as it looked complicated.

**Comment by spencercarli** [comment]
Redux would probably be easiest or some sort of event dispatch/listener setup where you emit an event on tabBarPress and listen for that event in the components that need to update.

**Comment by johncrisostomo** [comment]
> Once I tab is mounted it's not going to be unmounted until that tab navigator is unmounted.

😱 😱 😱 
This is also causing me some problems. 😭

**Comment by kelset** [comment]
Closing this since it's a question; moreover, in the [README](https://github.com/react-community/react-navigation#community-contributions) you can find some valuable articles that will help you out using redux with react-navigation, like [this one](https://codeburst.io/react-navigation-with-complete-redux-state-management-tab-bar-and-multiple-navigators-ed30a69d9a4d).
