### ISSUE TITLE
Android: Nested animated tab navigator stuck when swiping 

### ISSUE THREAD

**Issue by mantas-janulionis** [react-community/react-navigation#2673]
The bug occurs on android when having two nested tab navigators:
Outer tab navigator with `animationEnabled=false` and `swipeEnabled=false`
Inner tab navigator with `animationEnabled=true` and `swipeEnabled=true`

iOS works correctly

---

### Current Behavior
- Clicking on inner navigator buttons nothing happens.
- Swiping works, but does not snap when touch is released

### Expected Behavior
- Clicking on inner navigator buttons navigates to the other tab.
- Swiping works and snaps to the correct position when touch is released

### Your Environment
Tested on Android emulator, Android 6.0

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.13
| react-native     | 0.48.4
| node             | 8.5.0
| npm or yarn      | 5.3.0

Stripped down code snippet:
```import React, { Component } from 'react';
import {
  AppRegistry,
  View,
} from 'react-native';

import {
  TabNavigator,
} from 'react-navigation';

class ScreenRed extends React.Component {
  render() {
    return (
      <View style={{flex: 1, backgroundColor: 'red'}}/>
    );
  }
};
class ScreenGreen extends React.Component {
  render() {
    return (
      <View style={{flex: 1, backgroundColor: 'green'}}/>
    );
  }
};

class ScreenYellow extends React.Component {
  render() {
    return (
      <View style={{flex: 1, backgroundColor: 'yellow'}}/>
    );
  }
};

const TabTopNavigator = TabNavigator({
  inner_one: {
    screen: ScreenRed
  },
  inner_two: {
    screen: ScreenGreen
  },
}, {
  tabBarPosition: 'top',
})

const TabBottomNavigator = TabNavigator({
  outer_tab1: {
    screen: TabTopNavigator,
  },
  outer_tab2: {
    screen: ScreenYellow,
  },
}, {
  tabBarPosition: 'bottom',
  animationEnabled: false,
  swipeEnabled: false,
});
AppRegistry.registerComponent('TestApp', () => TabBottomNavigator);
```
![sep-29-2017 15-22-44](https://user-images.githubusercontent.com/1628399/31015721-422cde36-a52a-11e7-8edb-d395112576b3.gif)

**Comment by metelski** [comment]
This is the same as #1442

**Comment by spencercarli** [comment]
Closing in favor of #1442
