### ISSUE TITLE
InitialRouteName not working for TabNavigator inside StackNavigator after update to beta.13

### ISSUE THREAD

**Issue by lucianomlima** [react-community/react-navigation#2680]
### Current Behavior
- I set initialRouteName in TabNavigator, but always load in first tab
```
const Tab = TabNavigator(
    {
        homeTab: {
            screen: Home,
            navigationOptions: {
                tabBarIcon: ({ tintColor }) => (
                    <Icon name={'home'} style={{ color: tintColor }} />
                )
            }
        },
        profileTab: {
            screen: Profile,
            navigationOptions: {
                tabBarIcon: ({ tintColor }) => (
                    <Icon name={'user'} style={{ color: tintColor }} />
                )
            }
        }
    }, {
        initialRouteName: 'profileTab',
        tabBarComponent: TabBarBottom,
        tabBarOptions: {
            activeTintColor: '#05b0ba',
            inactiveTintColor: '#a7a9ac',
            activeBackgroundColor: '#fff',
            inactiveBackgroundColor: '#fff',
            showIcon: true,
            showLabel: false,
            tabStyle: {
                ...shadow.tab,
                backgroundColor: '#fff'
            }
        }
    }
);
```
### Expected Behavior
- Render in initialRouteName when is setted.

### Your Environment

| software | version
| --------- | -------
| react-navigation | 1.0.0-beta.13
| react-native | 0.45.1
| node | 8.5.0
| yarn | 1.0.2

**Comment by vexsnare** [comment]
+1

**Comment by spencercarli** [comment]
Can you put together a running demo?

**Comment by dackom** [comment]
I can confirm that something is different with this in beta 13, i switched back to beta 11, and now everything is working as should. But to me, it didn't actually want to load first screen in configuration, with initialRouteName or without...

welcome: { screen: WelcomeScreen },
auth: { screen: AuthScreen },
main: { 
        screen: TabNavigator({
...


In version beta11, it was automatically loading welcome screen, but in version 13 it started initially to go to main screen, even if I explicitly said initialRouteName:"welcome".

**Comment by vexsnare** [comment]
For me It's working even in beta 13. Initially I thought its not but there was a mistake from my side while setting up 'initialRouteName' value.

**Comment by lucianomlima** [comment]
I create a new fresh demo and everything works fine, but above project has Redux and Redux Saga.
I will try to put the Redux configuration to see if it will continue working or not. Then I'll close this issue or I'll put the repo url here.

**Comment by lucianomlima** [comment]
It's totally weird but now it's working and I don't know why. Thank you all.

**Comment by windhost** [comment]
same as beta 21

**Comment by wfsovereign** [comment]
same as beta 27
