### ISSUE TITLE
Unable to setParams

### ISSUE THREAD

**Issue by realtebo** [react-community/react-navigation#2682]
```
 componentWillMount() {
        console.log('1', this.props.navigation.params);
        this.props.navigation.setParams({ realtebo: 2 });
        console.log('2', this.props.navigation.params);
    }
```

Output:
```
1 undefined
2 undefined
```

Why ?!

My environment

    "expo": "^21.0.0",
    "firebase": "^4.4.0",
    "react": "16.0.0-alpha.12",
    "react-native": "^0.48.4",
    "react-navigation": "^1.0.0-beta.13",
    "react-redux": "^5.0.6",
    "redux": "^3.7.2",
    "redux-thunk": "^2.2.0"

Node 8.5
npm 4.61

**Comment by kelset** [comment]
Hi @realtebo - it's really hard to tell why you are getting those undefined without seening the code of the component and navigation.

That said I'm quite confident is not a bug of the library.

**Comment by andrew-wagner89** [comment]
I think it's `this.props.navigation.state.params` not `this.props.navigation.params`
