### ISSUE TITLE
Unexpected token error when I‘m first use React-Native

### ISSUE THREAD

**Issue by derting** [react-community/react-navigation#2685]
Hi,
I got an Unexpected token error when I‘m first use React-Native
error: bundling failed: "SyntaxError ..ProjectName/index.ios.js: Unexpected token (49:15)"
`  49 | export default const SimpleApp = StackNavigator({`
`__ | ________________^`
`  50 |   Home: { screen: HomeScreen },`
`  51 | });`
`  52 | `

It should be like this:
`const SimpleApp = StackNavigator({
  Home: { screen: HomeScreen },
});`

https://stackoverflow.com/questions/46254733/first-to-use-react-native-got-unexpected-token

**Comment by kelset** [comment]
A PR with the fix #2679 is already going to get merged ;)
thanks anyway for reporting
