### ISSUE TITLE
How to center TabNavigator tabs vertically?

### ISSUE THREAD

**Issue by kazzkiq** [react-community/react-navigation#2697]
No matter what I do, my tabs always stay on "top" vertically. How can I put them in the center regardless of their height?

This image explains exactly what I'm trying to achieve:

![123](https://user-images.githubusercontent.com/1953194/31248077-ffb8daa0-a9e8-11e7-8381-8ace282a9004.jpg)

**Comment by sanjayholla94** [comment]
Will need more code to reproduce the issue. I've put together a snack to check this issue. https://snack.expo.io/ryCSYVs2W
By default, the tab title is centered. 
![tab center](https://user-images.githubusercontent.com/30792573/31427163-fc69c432-ae83-11e7-8fa1-e818113399d8.png)

Which version of react navigation are you using?

**Comment by kelset** [comment]
@kazzkiq can you check the code provided by @sanjayholla94? It seems to me that his implementation is correct and it doesn't present your issue
