### ISSUE TITLE
How can I change the title style in navigationOptions? for example font color and size maybe fontFamily?

### ISSUE THREAD

**Issue by ElSadeq** [react-community/react-navigation#2704]
## The issue list is reserved for bugs and feature requests, not for questions.

For usage questions, try to:

- [Read the docs](https://reactnavigation.org/)
- [Ask on the Reactiflux (#react-navigation)](https://discord.gg/reactiflux)
- [Look for / ask questions on StackOverflow](https://stackoverflow.com/questions/tagged/react-navigation)
- Search for your issue - it may have already been answered or even fixed in the development branch. However, if you find that an old, closed issue still persists in the latest version, you should open a new issue.

---

### Current Behavior
- _If describing a bug, tell us what happens. Please provide a repository with code and steps to reproduce the bug. **Not providing code that other people can run makes is significantly harder to fix your bug.** Provide a screenshot when possible_
- _If suggesting a change/improvement, explain the difference from current behavior_

### Expected Behavior
- _If you're describing a bug, tell us what should happen_
- _If you're suggesting a change/improvement, tell us how it should work_

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |
| react-native     |
| node             |
| npm or yarn      |

**Comment by vonovak** [comment]
hi, since this is a question, a better place for it would be stackOverflow. After you create the question there, post the link here and I'll try to answer.

**Comment by ElSadeq** [comment]
thank you vonovak, you are right I should've asked there first.. here's the link to the question I just asked it there: https://stackoverflow.com/questions/46624137/how-can-i-change-the-title-style-in-navigationoptions-of-react-navigation

**Comment by vonovak** [comment]
@ElSadeq I think you can close the issue here, since it is being handled on SO
