### ISSUE TITLE
From left to right animation ?

### ISSUE THREAD

**Issue by kesepara** [react-community/react-navigation#2707]
Hey,

Is there any way to animate window from left to right with navigate() function?

Thanks in advance.

**Comment by vonovak** [comment]
hi, since this is a question, a better place for it would be stackOverflow. After you create the question there, post the link here and I'll try to answer.

**Comment by kesepara** [comment]
here is the link mate @vonovak any help will be appreciated
https://stackoverflow.com/questions/46624633/from-left-to-right-window-animation-with-react-navigation

**Comment by vonovak** [comment]
I think this issue can be closed since it is being handled on SO.

**Comment by vonovak** [comment]
@spencercarli this can be closed
