### ISSUE TITLE
Execute a function when a screen is shown on the phone

### ISSUE THREAD

**Issue by Alexandre59700** [react-community/react-navigation#2710]
Hi everyone ! 

I'm using react-native-navigation for my project but I'm a bit stuck on something, so if maybe someone has the solution, that would be wonderfull :) 

So, I want to execute a function EACH TIME a particular screen is show to the user.  Not only when it is rendering, really each time it is shown to the user.

So if someone have a solution ! That would be great !

**Comment by vonovak** [comment]
try screen tracking https://reactnavigation.org/docs/guides/screen-tracking

**Comment by Alexandre59700** [comment]
Thanks for the link :) I've managed to do make it work !

**Comment by vojtechnovak** [comment]
You're welcome. That means you can close the issue.

**Comment by kelset** [comment]
thanks @vojtechnovak for helping him finding the solution.
