### ISSUE TITLE
[Help] Being able to style the DrawerSidebar?

### ISSUE THREAD

**Issue by kingstenbanh** [react-community/react-navigation#2711]
### Current Behavior
Currently, there is no way to customize the style of the DrawerSidebar. For my app, I would like the drawer view not take up the whole height of the app. I found a work around that the limitation is by 
- creating a customDrawer for `contentComponent`
- A parent wrapper to take up the full height and match the gray color of the background
- The `DrawerNavigationItems` to not take the full height of the app.

However, the transition isn't smooth and you could see the color different when closing the drawer. The desired result is that I could make the background of the `DrawerView` transparent so when transitioning, it doesn't look hacky. Please help!

![screen recording 2017-10-08 at 01 30 am](https://user-images.githubusercontent.com/7540669/31315195-53d793d4-abc8-11e7-8558-f5d20858af25.gif)

### Expected Behavior
Should be able to set the DrawerSidebar color to transparent or reduce its height.

**Comment by padil** [comment]
Hello, this has already been solved with a **pullrequest**, it is already in the documentation, however the version with this feature does not know when it will launch.

Search for `drawerBackgroundColor` in documentation.

 [documentation](https://reactnavigation.org/docs/navigators/drawer)

**Comment by kelset** [comment]
Hi @kingstenbanh and @padil - `beta.15` has been released, and it has the wanted option for the drawer ;)

**Comment by kelset** [comment]
Closing because of no followup to my last comment.
