### ISSUE TITLE
component repeat mount 

### ISSUE THREAD

**Issue by HiLittleCat** [react-community/react-navigation#2719]
loading app
index.js:9 dispatching {type: "persist/REHYDRATE", payload: {…}, error: null}
index.js:11 next state {nav: {…}, userStore: {…}, tag: {…}}
index.js:9 dispatching {type: "persist/REHYDRATE", payload: {…}, error: null}
index.js:11 next state {nav: {…}, userStore: {…}, tag: {…}}
2login.js:27 login componentWillMount
recordList.js:15 recordList componentWillMount
2login.js:27 login componentWillMount
3recordList.js:15 recordList componentWillMount
login.js:27 login componentWillMount
4recordList.js:15 recordList componentWillMount
login.js:27 login componentWillMount
5recordList.js:15 recordList componentWillMount
18login.js:27 login componentWillMount
23recordList.js:15 recordList componentWillMount
42login.js:27 login componentWillMount
66recordList.js:15 recordList componentWillMount
4family.js:18 family componentWillMount
recordList.js:15 recordList componentWillMount
29family.js:18 family componentWillMount
recordList.js:15 recordList componentWillMount
29family.js:18 family componentWillMount
recordList.js:15 recordList componentWillMount
5family.js:18 family componentWillMount
recordList.js:15 recordList componentWillMount
3family.js:18 family componentWillMount
recordList.js:15 recordList componentWillMount
33family.js:18 family componentWillMount
recordList.js:15 recordList componentWillMount
5family.js:18 family componentWillMount

when i refresh my app ,  component repeat mount.

**Comment by vonovak** [comment]
Please include a full reproduction code. Nobody will be able to figure out what's wrong just from this stacktrace.

**Comment by HiLittleCat** [comment]
my navigation tree：

AppNavigator :
export const AppNavigator = StackNavigator({
    MainPage: {
        screen: MainPage,
        navigationOptions: {
            header: nul
        }
    },
    LoginPage: {
        screen: LoginPage,
        navigationOptions: {
            headerTitle: '登录',
            headerBackTitleStyle : { fontSize: 14 }
        }
    },
    RegisterPage: {
        screen: RegisterPage,
        navigationOptions: {
            headerTitle: '注册',
            headerBackTitleStyle : { fontSize: 14 }
        }
    },
});

MainPage:
export default Main = TabNavigator({
    Record: {
        screen: RecordPage,
        navigationOptions: {
            tabBarLabel: '记录',
            tabBarIcon: ({ tintColor }) => (
                <Icon name='list' style={[styles.tabBarIcon, { fontSize: 25, color: tintColor }]} />
            ),
        },
    },
    Remind: {
        screen: RemindPage,
        navigationOptions: {
            tabBarLabel: '提醒',
            tabBarIcon: ({ tintColor }) => (
                <Icon name='bell' style={[styles.tabBarIcon, { fontSize: 25, color: tintColor }]} />
            ),
        },
    },
    Family: {
        screen: FamilyPage,
        navigationOptions: {
            tabBarLabel: '家庭',
            tabBarIcon: ({ tintColor }) => (
                <Icon name='group' style={[styles.tabBarIcon, { fontSize: 25, color: tintColor }]} />
            ),
        },
    },
    Profile: {
        screen: ProfilePage,
        navigationOptions: {
            tabBarLabel: '我',
            tabBarIcon: ({ tintColor }) => (
                <Icon name='user' style={[styles.tabBarIcon, { fontSize: 25, color: tintColor }]} />
            ),
        },
    }
}, {
    initialRouteName: 'Record',
    tabBarPosition: 'bottom',
    swipeEnabled: false,
    animationEnabled: false,
    backBehavior: 'none',
    tabBarOptions: {
        style: { height: 49, backgroundColor: '#EEE' },
        indicatorStyle: { height: 0 }, 
        activeBackgroundColor: '#666',
        activeTintColor: '#FFF',
        inactiveTintColor: '#000',
        inactiveBackgroundColor: '#000',
        inactiveTintColor: '#FFFFFF',
        showLabel: false,
        showIcon: true
    }
});

RecordPage:
export default Record = StackNavigator({
    RecordListPage: {
        screen: RecordListPage,
        navigationOptions: {
            headerTitle: '记录列表',
            headerBackTitleStyle: { fontSize: 14 },
            headerTitleStyle: { color: '#333' }
        }
    },
    RecordDetailPage: {
        screen: RecordDetailPage,
        navigationOptions: {
            headerTitle: '记录明细',
            headerBackTitleStyle: { fontSize: 14 },
            headerTitleStyle: { color: '#333' }
        }
    }
});

**Comment by HiLittleCat** [comment]
**reducer**

const initialState = AppNavigator.router.getStateForAction(AppNavigator.router.getActionForPathAndParams('LoginPage'));

export default navReducer = (state = initialState, action) => {
  const nextState = AppNavigator.router.getStateForAction(action, state);
  return nextState || state;
};

**Comment by vonovak** [comment]
hi, @HiLittleCat I meant a repository which reproduces the bug. Some thing that people can clone and run to see the error.

**Comment by HiLittleCat** [comment]
i remove the reducers of the navigation, then the bug is disappear,  thanks
