### ISSUE TITLE
Use component for title is not possible

### ISSUE THREAD

**Issue by kennydee** [react-community/react-navigation#272]
Hi,

It seems impossible to use a component for the `title` option in a `stackNavigator` for now, even if #13 say the opposite :)

If i want to have a custom title (with an image for exemple) in the header, i have to be able to use a component instead of a string.
So i tried this, but it does nothing, the header stays empty : 

```javascript
const HomeTitle = () => (
  <Image
    source={logoImage}
    style={styles.image}
  />
);

stackNavigatorConfig[SCENE_HOME] = {
  screen: HomeSceneConnector,
  navigationOptions: {
    title: HomeTitle,
  },
};
```

After digging in `react-navigation` source code, i found that the problem is located here : 
https://github.com/react-community/react-navigation/blob/master/src/views/Header.js#L91

```javascript
  _getHeaderTitle(navigation: Navigation): ?string {
    const header = this.props.router.getScreenConfig(navigation, 'header');
    let title;
    if (header && header.title) {
      title = header.title;
    } else {
      title = this.props.router.getScreenConfig(navigation, 'title');
    }
    return typeof title === 'string' ? title : undefined;
  }
```

If i change line 91 (last line of this code) by `return title;` my title now work :)

But i think this condition is here for something ? So, why do you return `undefined` when title is not a string ? 

Tested on the last version `1.0.0-beta.3`

Thanks for your help, and keep up the good work, `react-navigation` is already awesome !

Kenny

**Comment by Freddy03h** [comment]
`title` work with a component, but not the one directly on the option, you have to declare an `header` option before.


```js
  static navigationOptions = {
    header: (navigation) => ({
      title: ( <PlanningTitleSegment navigation={navigation} /> )
    })
  }
```

**Comment by grabbou** [comment]
Yes, the `title` in navigationOptions must be a string. Using `header.title` with a component is fully supported.

**Comment by ethanyanjiali** [comment]
I'm able to use a component in react-navigation 1.0.0-beta.9 as title. However, it must only render a Text component. The problem is, it will later throw a "invalid data message" error in some case (using redux form in my case). It took me two nights to figured out that using headerTitle instead of title can fix the problem. 

@grabbou Is it possible to make `title` to only expect a string, rather than a node? It can help people to find the issue earlier.

**Comment by keeleycarrigan** [comment]
`headerTitle` isn't working for me at all. I've tried to set heights/widths and backgroundColor on the component and it still doesn't show.

**Comment by Faolain** [comment]
@ethanyanjiali headerTitle allowed you to use a component which does not render a Text component?
