### ISSUE TITLE
Execute a function ONLY when a screen is shown to the user

### ISSUE THREAD

**Issue by Alexandre59700** [react-community/react-navigation#2720]
Hi everyone !

I'm using react-native-navigation for my project but I'm a bit stuck on something, so if maybe someone has the solution, that would be wonderfull :)

So, I want to execute a function EACH TIME a particular screen is shown to the user. 

I'm already using "react-navigation-is-focused-hoc", and I have managed to make a function which is execute each time the screens loads and so the screen is only shown when the function is finished. But I want to execute the function ONLY when the screen is shown on the device.

So if someone have a solution ! That would be great !

**Comment by vonovak** [comment]
Please be so kind and ask questions on stackoverflow, instead of opening a duplicate question for the one you asked 2 days ago - #2710 
Thank you.

**Comment by sanjayholla94** [comment]
@kelset This issue can be closed as it's a duplicate

**Comment by kelset** [comment]
Thanks for pointing it out @vonovak & @sanjayholla94, completely missed out this issue.
