### ISSUE TITLE
getScreen function should not block the use of functions

### ISSUE THREAD

**Issue by mschipperheyn** [react-community/react-navigation#2724]
### Current Behavior
if you use the getScreen function and use a wrapping function, an error occurs:
`The getScreen defined for route 'Login didn't return a valid screen or navigator.`

E.g.
```
import SceneWrapper from 'modules/navigation/components/SceneWrapper';
import { DrawerNavigator, StackNavigator } from 'react-navigation';

const applySceneWrapper = scene => <SceneWrapper>{scene}</SceneWrapper>;

const loginRoutez = {
    Login: {
        path: 'login',
        getScreen: () => applySceneWrapper(require('screens/LoginScreen').default),
    },
    [...]
};
```
### Expected Behavior
It should not throw an error. Developers should be able to make their own decisions on how to handle this. In my case, I want the wrapper to contain stuff like connection toasts, etc. There is no obvious way to do this otherwise in DrawerNavigator other than repeating this code across all of your screens, which is not DRY and risks OOPS situations.

### Your Environment
react-navigation 1.0.0-beta.13

**Comment by mschipperheyn** [comment]
I have resolved this in the following way on the screen level (based on React-Router withRouter). I don't think this is the ideal solution, which I think would be as described above at the Router level.

```
import React from 'react';
import PropTypes from 'prop-types';
import hoistStatics from 'hoist-non-react-statics';
import SceneWrapper from './SceneWrapper';

const withSceneWrapper = (Component, options = {}) => {
    const C = props => {
        const { wrappedComponentRef, ...remainingProps } = props;
        return (
            <SceneWrapper>
                <Component {...remainingProps} ref={wrappedComponentRef} />
            </SceneWrapper>
        );
    };

    C.displayName = `withSceneWrapper(${Component.displayName || Component.name})`;
    C.WrappedComponent = Component;
    C.propTypes = {
        wrappedComponentRef: PropTypes.func,
    };

    return hoistStatics(C, Component);
};

export default withSceneWrapper;

```
the Screen itself
```
class MyScreen extends React.Component{
}

export default withSceneWrapper(MyScreen, {
   someOption: 123
});
```

**Comment by kelset** [comment]
I am not sure I've understood the issue.

It seems to me that there are actually two parts:

1. your `applySceneWrapper`not returning an object that `getScreen` likes
1. a feature request to create a sort-of HOC per screen

...right?

**Comment by mschipperheyn** [comment]
Let's close this. I created the HOC as described to work around this limitation and it works fine as it is.

**Comment by kelset** [comment]
@mschipperheyn mind to share it with the community? Someone else may end up facing a similar issue and surely a snippet would help them.
