### ISSUE TITLE
Clicking very fast will call the navigate function multiple times causes multiple "next" screens to stack

### ISSUE THREAD

**Issue by pencilcheck** [react-community/react-navigation#2726]
## The issue list is reserved for bugs and feature requests, not for questions.

For usage questions, try to:

- [Read the docs](https://reactnavigation.org/)
- [Ask on the Reactiflux (#react-navigation)](https://discord.gg/reactiflux)
- [Look for / ask questions on StackOverflow](https://stackoverflow.com/questions/tagged/react-navigation)
- Search for your issue - it may have already been answered or even fixed in the development branch. However, if you find that an old, closed issue still persists in the latest version, you should open a new issue.

---

### Current Behavior
- _If describing a bug, tell us what happens. Please provide a repository with code and steps to reproduce the bug. **Not providing code that other people can run makes is significantly harder to fix your bug.** Provide a screenshot when possible_
- _If suggesting a change/improvement, explain the difference from current behavior_

If you have a callback that calls the navigation props's navigate function to a different screen, and implement as part of the callback of a click event of a button, you can easily click it very fast to trigger multiple calls of that function to cause the same screen to stack multiple times.

And once you are clicking on the back button, you need to click multiple times in order to get back to the "real" previous screen.

### Expected Behavior
- _If you're describing a bug, tell us what should happen_
- _If you're suggesting a change/improvement, tell us how it should work_

Either
1. On transition, it prevents multiple calls to the same view to be transition and stack on top of each other
2. Or a way when clicking on the back button, shouldn't be displaying the same screen.

### Your Environment

| software         | version
| ---------------- | -------|
| react-navigation |  1.0.0-beta.9 |
| react-native     | expo https://github.com/expo/react-native/archive/sdk-21.0.2.tar.gz 0.48.4 | 
| node             |  7.6.0 |
| npm or yarn      | 0.27.5 |

**Comment by sanjayholla94** [comment]
There is already an existing issue for this https://github.com/react-community/react-navigation/issues/135. There are also a few proposed PRs to fix this issue #1313, #2400, #2578. 
Till then, there is a temporary workaround https://github.com/react-community/react-navigation/issues/271#issuecomment-303217976

**Comment by pencilcheck** [comment]
However I tried the workaround, it doesn't work.

**Comment by pencilcheck** [comment]
I made my own workaround, seems to work. Already shared in the same thread as the workaround. Hope that would help everyone.
