### ISSUE TITLE
error with navigation "Cannot read property 'setParams' of undefined"

### ISSUE THREAD

**Issue by pirosoft** [react-community/react-navigation#2729]
Hi, i use redux, thunk, and react-navigation, i have my login screen with:
 ```
static navigationOptions = {
title: 'Login',
headerLeft: null,
headerRight: (
<Button
onPress={() => this.onButtonLogout()}
>
Logout
</Button>
)
};
onButtonLogout() {
console.log('logout button');
//this.props.logoutUser();
}
```

But this give me a error:
_this2.onButtonLogout is not a function

and if i use:
```
componentDidMount() {
this.props.navigation.setParams({
onButtonLogout: this.onButtonLogout.bind(this)
});
}
```
give mi this error:
Cannot read property 'setParams' of undefined

why?

**Comment by kelset** [comment]
These are not bugs in the library, but simply you incorrectly set up your component.

I'm going to close this but if you want to post the whole component and navigation configuration I can try to help you out in finding where the code is wrong.

**Comment by pirosoft** [comment]
https://stackblitz.com/edit/react-dqeeq2
here is the code!
thanks :)

**Comment by kelset** [comment]
Ok I think I found it - basically in your mapStateToProps you "re-define" `navigation` and this override the one you are receiving automatically from the StackNavigator.

Try changing it to something like:
```js
const mapStateToProps = (state) => {    
    const { username, password, error, loading } = state.auth;
    const navigationLocal = state.nav;
    return { username, password, error, loading, navigationLocal };
};
```

And tbh I don't really understand why you need it, maybe I'm overlooking something.

For your "second case" where you write 
```js
componentDidMount() {
     this.props.navigation.setParams({
         onButtonLogout: this.onButtonLogout.bind(this)
     });
}
```

Btw use [Snack Expo](https://snack.expo.io/) next time so we can try around the code ;)
