### ISSUE TITLE
Hide icon for TabBar on ios?

### ISSUE THREAD

**Issue by coodoo** [react-community/react-navigation#273]
Just flipped through the codebase and seemed there's no way to hide icon for `TabBar` on ios, or was I missing something obvious here?

**Comment by coodoo** [comment]
I just sent a [PR](https://github.com/react-community/react-navigation/pull/279) to have this implemented, please have a look.

Code sample:
```javascript
tabBarOptions: {
	activeTintColor: '#9b59b6',
	labelStyle: { fontSize: 16 },
	showIcon: false, // toggle this false to hide icons in tabbar on iOS
},
```

**Comment by grabbou** [comment]
Fixed in the follow-up PR https://github.com/react-community/react-navigation/commit/546fc657d5b6bb4b5f7bec6980986c867aaf5fd2
