### ISSUE TITLE
Cannot cancel back

### ISSUE THREAD

**Issue by Thyiad** [react-community/react-navigation#2735]
There is no way to handle before do back.

In header.js, line 131

 <HeaderBackButton
        onPress={() => {
          this.props.navigation.goBack(null);
        }}

It just goBack.....

**Comment by kelset** [comment]
This is not an issue, if you need to handle the way the back in the header works you can simply override the Header options.

**Comment by zamponotiropita** [comment]
@kelset it would be very useful to be able to configure the behaviour of `goBack`. Making a custom BackButton would be overkill, for example we need the width of the BackButton to fit nicely which is not accessible:
```jsx
const width = this.state.widths[props.scene.key]
      ? (this.props.layout.initWidth - this.state.widths[props.scene.key]) / 2
      : undefined;```
