### ISSUE TITLE
"Lower" card still visible after initial navigation to new card in StackNavigator

### ISSUE THREAD

**Issue by shanecav** [react-community/react-navigation#274]
I'm playing around with transparent header and card backgrounds using `StackNavigator`. I've found that when I first navigate from the initial screen to another screen, the initial screen animates away, but then becomes visible again behind the current screen. However, if I use the back button, and then re-navigate to another screen, the initial screen correctly stays hidden.

Example (based on the chat app example in the docs):
![react-navigation-bug](https://cloud.githubusercontent.com/assets/120918/22821012/7e901cd0-ef36-11e6-9615-febe1eda5a88.gif)

In this example, the `StackNavigator`'s config includes the following options:

```
{
  navigationOptions: {
    header: {
      titleStyle: {
        color: 'white',
      },
      style: {
        backgroundColor: 'rgba(0,0,0,0)',
      },
    }
  },
  cardStyle: {
    backgroundColor: 'rgba(0,0,0,0)',
  },
}
```

Happy to make an example repo if that's helpful, too.

**Comment by pshurygin** [comment]
+1. Any workaround for that issue?

**Comment by spencercarli** [comment]
I think this has been fixed in an a release since the issue was posted. Please re-open if not!

**Comment by gariklolkin** [comment]
Hello guys. It seems I have the same issue.
