### ISSUE TITLE
Low performance with Redux integration

### ISSUE THREAD

**Issue by LAITONEN** [react-community/react-navigation#2742]
My app has redux integrated into React-Navigation based on the information in [React-Navigation docs](https://reactnavigation.org/docs/guides/redux).

### App

```
import AppWithNavigationState from './src/navigators/AppNavigator'; 
export default class App extends React.Component {

 render() {
    return (
      <Provider store={store}>
          <AppWithNavigationState />
      </Provider>
    );
  }
}

```
### AppNavigator

```
 const navigatorConfig = {
				lazy: true,
      			navigationOptions: {
    				tabBarVisible: false } 
				};

export const AppNavigator = TabNavigator({
      auth: { screen: AuthScreen },
      liststab: { screen: ListsTabNavigator }
	}, navigatorConfig);

class AppWithNavigationState extends React.Component { 
	render() {
		const { dispatch, nav } = this.props;
		return (
			<AppNavigator
				navigation={addNavigationHelpers({ dispatch, state: nav })}
			/>
		);
	}
}

AppWithNavigationState.propTypes = { 
	dispatch: PropTypes.func.isRequired,
	nav: PropTypes.object.isRequired 
};

const mapStateToProps = ({ app }) => ({ nav: app });

export default connect(mapStateToProps)(AppWithNavigationState);
```

### NavigatonReducer

```
import { AppNavigator } from '../navigators/AppNavigator';

const initialAppState = AppNavigator.router.getStateForAction(NavigationActions.init());

export default (state = initialAppState, action) => {
  const nextState = AppNavigator.router.getStateForAction(action, state);

  return nextState || state;
};

```
### App hierarchy 
```
TabNavigator({
      auth: { screen: AuthScreen },
      list: { screen: ListsTabNavigator({ 
                  ListOneStack({ 
                          List: { screen: SectionListOne },
                          Details: { screen: ListItemDetails },
                          Add: { screen: AddItem },
                          Edit: { screen: EditItem }, })
                  ListTwoStack({ 
                          List: { screen: SectionListTwo },
                          Details: { screen: ListItemDetails },
                          Add: { screen: AddItem },
                          Edit: { screen: EditItem }, })
        })}
});
```

With this configuration, my app suffers from  lags when:

1. Navigating between screens (2-3 seconds lag).
2. Adding / Editing / Deleting an item (longer lags).

If I change the App.js file to look like this (use AppNavigator without nav state):

```
import { AppNavigator } from './src/navigators/AppNavigator'; 

export default class App extends React.Component {

  render() {
    return (
      <Provider store={store}>
          <AppNavigator />
      </Provider>
    );
  }
}
```

The lags regarding navigation fade away, but the "add/edit/delete" actions still suffer from lags (more than 2-3 secs). 

### FetchFirebaseDatabase Action Creator:

```
export const fetchDatabase = (navigation) => {
        const DATABASE = (location) => firebase.database().ref(location);
	const access = `/users/${firebase.auth().currentUser.uid}/`;
	const type = FETCHED_DATABASE;
	return (dispatch) => {
		DATABASE(access).on('value', snapshot => {
			dispatch({ type, payload: snapshot.val() });
		});
	};
};
```

### Create Item Action Creator (delete and edit implemented in the similar way)

```
export const createItem = (item, navigation) => {

	const { params } = navigation.state;
	const error = () => fieldOne === '' || fieldTwo.length < 2;
	const payload = 'Fill in the first two fields!';
	const type = EMPTY_FIELDS_ERROR;

        const DATABASE = (location) => firebase.database().ref(location);
	const access = `/users/${firebase.auth().currentUser.uid}/`; 

	const actions = [NavigationActions.navigate({ routeName: 'list', params })];
	const resetToList = NavigationActions.reset({ index: 0, actions });

	return (dispatch) => {
		if (error()) dispatch({ type, payload });
		else DATABASE(access).push(item).then(() => navigation.dispatch(resetToList));
	};
};
```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^1.0.0-beta.13
| react-native     | https://github.com/expo/react-native/archive/sdk-21.0.2.tar.gz
| node             | v8.6.0
| npm or yarn      | 4.6.1

**Comment by kelset** [comment]
There is already an open issue that refers to performance issues so I'll close this one.
I highly suggest you read from [this comment on](https://github.com/react-community/react-navigation/issues/608#issuecomment-328635042) to better understand the current situation/what you can do to improve your performances.

**Comment by LAITONEN** [comment]
Hello, @kelset 
It seems that you have not really read what the issue is. Surely, one part of it could probably be solved by implementing what you suggest in the [comment](**https://github.com/react-community/react-navigation/issues/608#issuecomment-328635042**) you linked, but that solution does not seem to have anything to do with the way App.js communicates with AppNavigator in my example, where in the case if I follow the Redux Integration guide and use AppWithNavigationState in App.js, the navigation, even from the first page in the Stack, takes at least 2-3 second to perform. But if I simply import App**Without**NavigationState (which is called "AppNavigator" in my app and which consists of Route and Navigation configs), the lags fade away.

I will look into the solution you proposed, certainly, but **is something wrong with your docs regarding Redux Integration?**

**Comment by kelset** [comment]
> It seems that you have not really read what the issue is

It seems to me that your original issue posting was about how your app was performing "based" on the documentation. So about your app. Not about the docs.

>is something wrong with your docs regarding Redux Integration?

The docs can surely be improved. Feel free to submit a PR with your suggestions on how to make them better. That said, I suggest you read [this comment](https://github.com/react-community/react-navigation/issues/2031#issuecomment-336393229) and/or the SO answer he posted, because it looks to me that it may solve your issue.

**Comment by Mostafasaffari** [comment]
@LAITONEN 
Hi I have same problem. can you solve it? I'm confused.
