### ISSUE TITLE
base12 began to appear borderBottom, but base11 did not appear

### ISSUE THREAD

**Issue by chenyanji** [react-community/react-navigation#2745]
"react-navigation": "^1.0.0-beta.12" ~ "^1.0.0-beta.13"
![image](https://user-images.githubusercontent.com/8857201/31544185-3d8f6b0e-afdf-11e7-9a2a-b9637ccf4736.png)

"react-navigation": "^1.0.0-beta.11"
![image](https://user-images.githubusercontent.com/8857201/31544248-78d84762-afdf-11e7-9247-9fe390610ce2.png)

![image](https://user-images.githubusercontent.com/8857201/31544301-c24c4dee-afdf-11e7-9e36-e551e7756687.png)

**Comment by kelset** [comment]
Hey @chenyanji this is not strictly an issue - anyway if I understand correctly you can "fix" the line you are seeing for the header with:

```js
      headerStyle: {
        backgroundColor: Colors.mainArray[0],
        borderBottomWidth: 0,
        shadowOpacity: 0,
        shadowOffset: {
          height: 0,
        },
        shadowRadius: 0,
        elevation: 0,
      },
```

**Comment by chenyanji** [comment]
thinks,add：borderBottomWidth: 0
