### ISSUE TITLE
Drawer and "orientation change"

### ISSUE THREAD

**Issue by doublex** [react-community/react-navigation#2755]
First bug:
a) Open the app
b) Change orientation of the device
c) Drawer will not adopt to the orientation change

Second bug:
a) Open the drawer
b) Change orientation
c) Drawer will not adopt to the orientation change

**Comment by emregurler** [comment]
Did you use view onlayout prop for catching orientation change? Maybe it needs to be rerendered.

**Comment by spencercarli** [comment]
@doublex this was fixed in #2773 and released in v1.0.0-beta.15 (I just published this a few minutes ago)
