### ISSUE TITLE
A change in state re-render inactive and previous views (Redux implemented)

### ISSUE THREAD

**Issue by dann1609** [react-community/react-navigation#2756]
I implemented react-navigation in redux like docs said. but since it. I found that all my displays re-render each time I send an action to redux.

### Current Behavior
-Right now if I change a state, all views since first display to actual display re-render. no mater if are no actual visible view in my stack navigator. 

### Expected Behavior
- I expect only my actual view in stack navigator render each time I send and action to reducers.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.11
| react-native        |  0.45.1
| node                    | 8.0.0
| npm                     | 5.0.0

**Comment by sevo1** [comment]
It is not redux related, I have recreated this behaviour with state update

**Comment by kelset** [comment]
Yes, it is a known issue. This is a duplicate, in fact.
Please refer to issue#608 from [this comment](https://github.com/react-community/react-navigation/issues/608#issuecomment-328635042) on.
