### ISSUE TITLE
Nested stack navigation with drawer navigation

### ISSUE THREAD

**Issue by whimsicaldreamer** [react-community/react-navigation#2758]
I have seen and read Q&A in many places. I tried them and even posted question on SO and Reactiflux but I am unable to solve the problem. I am basically trying to have a simple navigation but I also want to have a drawer menu on only one single screen. Whatever I tried didnt open up the drawer, instead I got `undefined is not an object`

I am maintaining the routes in single file **RouteConfig.js**

```
import { StackNavigator, DrawerNavigator } from 'react-navigation';
import ConversationListScreen from './ConversationListScreen';
import Drawer from './Drawer';
import ChatScreen from './ChatScreen';

export const SideNav = DrawerNavigator({
    Drawer: { screen: Drawer},
});

export const Hola = StackNavigator({
    ConversationList: { screen: ConversationListScreen },
    Drawer: { screen: SideNav },
    Chat: { screen: ChatScreen },
});
```

and the screen **ConversationListScreen** is where I want to have the drawer menu has this:
```
import React, { Component } from 'react';
import {
    View,
    Text,
    Button,
    TouchableHighlight,
    Alert,
} from 'react-native';
import Icon from 'react-native-vector-icons/MaterialIcons';
import styles from './styles';

export default class ConversationListScreen extends Component
{
    static navigationOptions = {
        title: 'Hola',
        headerLeft: (
            <TouchableHighlight onPress={() => this.props.navigation.navigate('DrawerOpen')}>
                <Icon name="menu" style={ styles.menuIcon }/>
            </TouchableHighlight>
        ),
        headerRight: (
            <TouchableHighlight onPress={() => Alert.alert('Hi!', 'What you want to search?')}>
                <Icon name="search" style={ styles.searchIcon }/>
            </TouchableHighlight>
        )
    };
    render() {
        return (
            <View>
            </View>
        );
    }
}
```

And for the drawer nav I have set up **Drawer.js**

```
import React, { Component } from 'react';
import {
    View,
    Text,
} from 'react-native';

export default class SideNav extends Component
{
    render() {
        return (
            <View>
                <Text>My first Drawer</Text>
            </View>
        );
    }
}
```

I have been trying a lot but with no avail 😞

**Comment by moddatherrashed** [comment]
why that issue has been closed ?????

**Comment by whimsicaldreamer** [comment]
If you are trying to solve what I had been attempting to solve, then try this: https://github.com/kakulgupta/CustomDrawer

**Comment by moddatherrashed** [comment]
Thank you i have already fixed the problem :)

**Comment by whimsicaldreamer** [comment]
Great! :) if your way differed from the way I mentioned, kindly post it here. It might help someone else too.

**Comment by moddatherrashed** [comment]
can you please send me the link of the issue, because i could not find it :)

**Comment by whimsicaldreamer** [comment]
Here is the issue: #2758
You could also click on **View it on github** link on your email footer.

**Comment by moddatherrashed** [comment]
oh yeah i just noticed it is on github XS i look stupid now XD

anyway i did struggle so much with that thing, so i tried many thing but that was the best way !! 

**first of all :**  
in the App file we define easily the DrawerNavigator like : 

```
const App = DrawerNavigator({
  FirstStackScreen: { screen: FirstStackScreen},
  SecondScreen: { screen: SecondScreen},
  ThirdScreen: { screen: ThirdScreen},
})
```

that will initialize the DrawerNavigator routes in general then for example we have a StackNavigator in let us say the FirstScreen, so we define a StackNavigator insdie the FirstScreen Component like : 

```
 const StackNavigation = StackNavigator({
    FirstStackScreen: { screen: FirstStackScreen},
    SecondStackScreen: { screen: SecondStackScreen},
    ThirdStackScreen: { screen: ThirdStackScreen},
})
```

that makes for us : 

1. the landing screen will be FrirstStackScreen.
2. if you swipe for the left to right you will have the drawer with three screens ( FirstStackScreen, SecondScreen, ThirdScreen
3. and you can navigate to SecondStackScreen and ThirdStackScreen with navigate function as normal.

i hope it is clear...
# Happy Coding 👍

**Comment by minuee** [comment]
1213
