### ISSUE TITLE
Backbutton title

### ISSUE THREAD

**Issue by Antonides** [react-community/react-navigation#276]
How can i set the backbutton title? or leave it blank.

**Comment by florentroques** [comment]
This thread comes up first for back button text issue

So here's an update for newcomers, you need to use the navigation option headerBackTitle
https://reactnavigation.org/docs/navigators/stack#headerBackTitle

how to use https://github.com/react-community/react-navigation/issues/1358#issuecomment-300526270

**Comment by fossecode** [comment]
The link in the previous comment is broken, here is the new one:
https://reactnavigation.org/docs/en/stack-navigator.html#headerbacktitle
