### ISSUE TITLE
Is it possible to push down the main container screen?

### ISSUE THREAD

**Issue by dekm** [react-community/react-navigation#2761]
Is it possible to push down the whole navigation screen including the header? I need to push down my screen like the following image. Not sure where to start on accomplishing this. Will I need to nest my whole navigation inside another container?

https://i.imgsafe.org/4a/4a19578d7a.png

**Comment by vonovak** [comment]
hello, please be so kind and use stackoverflow for questions. Can you post a link to SO, and then close the issue? I'll answer there.

**Comment by dekm** [comment]
Ok will do thanks!

**Comment by dekm** [comment]
Here is the SO link thanks again.

https://stackoverflow.com/questions/46770553/how-to-create-a-push-down-of-screens-in-react-navigation
