### ISSUE TITLE
Stop Default Animation when using Custom Tab Bar in Stack Navigator

### ISSUE THREAD

**Issue by deadcoder0904** [react-community/react-navigation#2763]
Note that I've asked on StackOverflow & Reactiflux both & both had different answers where none of them led to solutions (one asked to keep an eye 👁‍🗨  on issue #175 & another said it can be done with #1254) & now I'm confused so asking it on the original repo so that it grabs more eyes 👀 

I've made a custom tab bar in a Component which uses `StackNavigator` like so

```js
export default StackNavigator(
	{
		Login: {
			screen: Login,
		},
		ForgotPassword: {
			screen: ForgotPassword,
		},
		SignUp: {
			screen: SignUp,
		},
		Home: {
			screen: Home,
		},
	},
	{
		headerMode: 'none',
		navigationOptions: {
			headerVisible: false,
		},
		initialRouteName: 'Home',
	},
);
```

Now my `Home` screen has a custom made Tab Bar like so

```js
export default () => (
	<View>
		<Text>HOME</Text>
		<TabBar />
	</View>
);
```

Note - My `Tab bar` component is same as `Instagram's Bottom Tab bar`

I want my `Home` screens Tab bar to have no animations 

Currently it animates (`left to right` for `IOS` & `bottom to up` for `Android`) when one of the Tab link is clicked

I checked docs & found `mode` property but it has only 2 props `card` & `modal` & I want no animations

How to do it ?

**Comment by vonovak** [comment]
you're saying that you have a "custom made tab bar", so how much custom is it, if you're asking in this repo? If it is based on the react-navigation's tab bar, there apparently is a prop for that: https://reactnavigation.org/docs/navigators/tab#TabNavigatorConfig

if that doesn't help, you'll probably have to dig around in the code to figure out where the animation is defined and see how it can be changed...

**Comment by deadcoder0904** [comment]
Custom Tab Bar is as follow

```
const TabItems = [
	{
		title: 'Trending',
	},
	{
		title: 'Settings',
	}
];

<View style={styles.footer}>
	{TabItems.map(({title}, i) => (
		<TouchableOpacity onPress={() => this.props.navigation.navigate(title)} key={i}>
			<Text>{title}</Text>
		</TouchableOpacity>
	))}
</View>
```

**Comment by vonovak** [comment]
@deadcoder0904 I probably misunderstood your question, so you're basically using the tab bar to push screen onto a stack? Can you please include the SO link in the description? Also, note that using `i` (array index) as a `key`may break react's reconciliation. In this particular case it will be fine, but generally, it may lead to errors.

**Comment by deadcoder0904** [comment]
[SO link](https://stackoverflow.com/questions/46755743/how-to-stop-default-transition-when-using-custom-tab-bar-in-react-native-using-r) is no different. I actually copy pasted the whole thing here. & the `key` is not much an issue for me

**Comment by deadcoder0904** [comment]
Also, my only problem was to not use `TabNavigator` was bcz in Android it is on the Top & IOS its in bottom so I only wanted it in the bottom & I didn't knew about `Custom TabNavigatorConfig` with which we can make it in bottom for both OSes.

So if I were to use `TabNavigator` inside of `StackNavigator` then I should make `HomePage` screen (in `StackNavigator` besides `SignUp` & `Login`) which will have all `Tabs` & if I click it won't show any animations now. Is my approach correct ❓

**Comment by deadcoder0904** [comment]
This got answered on [StackOverflow](https://stackoverflow.com/questions/46755743/how-to-stop-default-transition-when-using-custom-tab-bar-in-react-native-using-r)

@vonovak Thank you, but now all my animations are stopped. 

Check SO for more info. Closing this one.
