### ISSUE TITLE
Unable to resolve module `react-navigation`

### ISSUE THREAD

**Issue by caihuajian** [react-community/react-navigation#2765]
I init a new react native project,when i use react-navigation display 'Unable to resolve module `react-navigation`'

**Comment by brentvatne** [comment]
you need to install it with `npm install react-navigation --save` on a new project :)

**Comment by caihuajian** [comment]
Yes ,I did.but display this problem

**Comment by caihuajian** [comment]
@brentvatne

**Comment by irwanayeah** [comment]
when I use script 

> npm install react-navigation --save

folder react-navigation never seen in node_modules, here output 

> npm install react-navigation --save
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
> 
> + react-navigation@1.0.0-beta.27
> added 10 packages in 11.96s

what's wrong?

**Comment by brentvatne** [comment]
try using yarn instead of npm 5. or try `rm -rf node_modules` and `rm package-lock.json` and `npm i`

**Comment by supervu** [comment]
I got the same issue. this is my package
"dependencies": {
    "react": "16.2.0",
    "react-native": "0.53",
    "react-native-restart": "0.0.6",
    "react-navigation": "1.2.1"
  }
Still no luck. Any ideas?

**Comment by vdharankar** [comment]
having similar issue here and its damn frustrating

**Comment by brentvatne** [comment]
if you have this problem please create a new issue and follow the issue template. i don't know how to reproduce this on a working version of npm or yarn (npm5 is broken, do not use it!)
