### ISSUE TITLE
Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. You likely forgot to export your component from the file it's defined in.

### ISSUE THREAD

**Issue by GuyZwer** [react-community/react-navigation#2767]
Hi guys,
I am trying to setup a new react native project and new component but I got the error:

`Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. You likely forgot to export your component from the file it's defined in.`

My app.js in my react native project directory:
```
import { AppRegistry } from 'react-native';
import { App } from './src/app';

AppRegistry.registerComponent('TechStack', () => App);
```

My App.js that  in the './src/app' directory:
```
import React from 'react';
import { View } from 'react-native';
import { Provider } from 'react-redux';
import { createStore } from 'redux';
import { reducers } from './reducers';
import { Header } from './components/common';


const App = () => {
  return (
    <Provider store={createStore(reducers)}>
      <View />
    </Provider>
  );
};

export default App;


```
Any help is highly appreciated

Thanks

**Comment by kelset** [comment]
This is not an issue with this library, so I'll close this issue.

Most likely the reason you are seeing this error is because somewhere you have a Text object.

**Comment by dhilt** [comment]
@Zwerd You need to import the default properly:

```
import App from './src/app';
```

**Comment by ronniecodes** [comment]
For me, I was importing items from the wrong module. For instance, ScrollView doesn't below in the import below. 

import  { ScrollView } from 'react-native-router-flux';

**Comment by syyam** [comment]
I'm having the same error, has anyone got the solution for it?

**Comment by subhamkrishna** [comment]
I'm also having the same error, @syyam  did you get any solution?

**Comment by jsah9105** [comment]
I'm having same error. Even i am not using Text object anywhere. just i am setup initial project?
Has anyone found solution?

**Comment by rajeshde** [comment]
> I'm having same error. Even i am not using Text object anywhere. just i am setup initial project?
> Has anyone found solution?
> Without redux it is working fine but after i am adding <Provider store = { store } > it is giving error
> above error

Same issue here in <Provider store = { store } >
Strangely the same project is working in another machine with same package versions. I just tried to run from another machine and then i got this error

**Comment by EphraimMwanda** [comment]
i am facing the same problem, Just adding <Provider store = { store }> the error pops up.
do you think its a bug in the current version of redux ??
i am clueless as to what might be causing the error.

**Comment by EphraimMwanda** [comment]
ooh my mistake!
i was making the mistake of importing my Provider from 'redux' instead of 'react-redux'
silly mistake.

**Comment by erdemildiz** [comment]
It was fixed 
`/** @format */
import React from 'react'
import {AppRegistry} from 'react-native';
import RootApp from './src';
import {name as appName} from './app.json';

import { Provider } from 'react-redux'
import configStore from './src/configStore'

const store = configStore({});

const App = () => {
    return (
      <Provider store={store}>
        <RootApp />
      </Provider>
    );
  };
  
  export default App;

AppRegistry.registerComponent(appName, () => App);
`

**Comment by AkashGalani** [comment]
In my case (using Webpack) it was the difference between:

import {MyComponent} from '../components/xyz.js';
vs

import MyComponent from '../components/xyz.js';

Full Solution At [Here](https://icetutor.com/question/uncaught-error-invariant-violation-element-type-is-invalid-expected-a-string-for-built-in-components-or-a-class-function-but-got-object/)

**Comment by VypaCodes** [comment]
Had the exact same error... I installed React navigation and all its dependencies.. Installed the bottomtabnavigator.. Used the example given but was given this error. please how do I go about it?. its really bugging me out

**Comment by VypaCodes** [comment]
And by the way, WHY THE FUCK DOES REACT NATIVE HAVE TO BE SUCH A HEADACHE HUH??... I code a beautiful app and it looks good on the emulator. then when I run it in my phone, it looks like shit. Icons look bigger, texts look bigger and bolder, among other things.. I can do with height and with not being adjustable but the others just pisses me the fuck off.. BTW, I dont mean no disrespect

**Comment by JetPlaneJJ** [comment]
@ValentineCodes I am having the same problem

**Comment by brayanL** [comment]
I am having the same problem: Element type is invalid" expect a string .........
