### ISSUE TITLE
Custom transition for stack navigation has stopped working on iPhone X

### ISSUE THREAD

**Issue by rashtay** [react-community/react-navigation#2769]
### Current Behavior
I have applied custom transition using stack navigators transition property. It works well on all other versions of iPhone except iPhone X. Please note that I tested it on the simulator.

### Expected Behavior
Transitions should work seamlessly on iPhone X.

 I am sure support for iPhone X would be in progress and I thought this might help.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.13
| react-native     | 0.47.1
| node             | 8.6.0
| yarn      | 1.1.0

**Comment by spencercarli** [comment]
How can we test this? Please supply a reproduction app or, at the least, steps to reproduce this.

**Comment by rashtay** [comment]
Unfortunately, I can't provide you the app but I'll provide you code snippets and GIF of the problem. I'll do it today.

**Comment by rashtay** [comment]
Hey, it was an iPhone cache issue. The transitions are working fine. Apologies for the inconvenience.
