### ISSUE TITLE
DrawerNavigator

### ISSUE THREAD

**Issue by pcofilada** [react-community/react-navigation#277]
Is it possible to have two DrawerNavigator on the same screen?

**Comment by satya164** [comment]
What do you have in mind?

**Comment by pcofilada** [comment]
I'm thinking of having two drawer (one on the left and one on the right). Is this possible?

**Comment by satya164** [comment]
@pcofilada should be if you nest two drawer navigators. not sure though. have you tried it yet?

**Comment by sigmazen** [comment]
Hi @satya164 
This is ultimately where my original Q was going ( #268 ) once the left-drawer was working.
I'm wanting to trigger the right-drawer off of a tab-button (ie the More icon) as well as the Menu header icon/drawer
So conceptually it would require something like:
  `onPress={() => {DrawerNavLeft.navigate('DrawerOpen')} }`
  `onPress={() => {DrawerNavRight.navigate('DrawerOpen')} }`
We can see the onPress events working in the  `MoreTab.navigationOptions` section via the console but no joy on triggering the DrawerOpen onPress
Cheers

    import React, { Component } from 'react';
    import {  AppRegistry, Text, StyleSheet, View, Button, Icon, ScrollView, } from 'react-native';
    import { StackNavigator, TabNavigator, DrawerNavigator, } from 'react-navigation';
    import Ionicons from 'react-native-vector-icons/Ionicons';
    
    //**** SimpleScreen view
    const SimpleScreen = ({ navigation, banner }) => {
      return (
        <ScrollView style={styles.container}>
          <Text style={styles.welcome}>{banner}</Text>
        </ScrollView>
      )
    };
    //**** Profile view
    const Profile = ({ navigation, banner }) => (
      <SimpleScreen
        navigation={navigation}
        banner="Profile"
      />
    );
    //**** Settings view
    const Settings = ({ navigation, banner }) => (
      <SimpleScreen
        navigation={navigation}
        banner="Settings"
      />
    );
    
    //**** Home Tab
    const HomeTab = ({ navigation }) => (
      <SimpleScreen
        navigation={navigation}
        banner="Home Tab"
      />
    );
    HomeTab.navigationOptions = {
      title: 'Home',
      header: ({ state, setParams, navigate }) => ({
            left: (    
                <Button
                    title={'Menu'}
                    onPress={() => {navigate('DrawerOpen')} }
                />
            ),
      }),
      tabBar: {
        label: 'Home',
        icon: ({ tintColor, focused }) => (
          <Ionicons
            name={focused ? 'ios-home' : 'ios-home-outline'}
            size={26}
            style={{ color: tintColor }}
          />
        ),
      },
    };
    
    //**** Rewards Tab
    const RewardsTab = ({ navigation }) => (
      <SimpleScreen
        navigation={navigation}
        banner="Rewards Tab"
      />
    );    
    RewardsTab.navigationOptions = {
      title: 'Rewards',
      header: ({ state, setParams, navigate }) => ({
            left: (    
                <Button
                    title={'Menu'}
                    onPress={() => {navigate('DrawerOpen')} }
                />
            ),
      }),
      tabBar: {
        label: 'Rewards',
        icon: ({ tintColor, focused }) => (
          <Ionicons
            name={focused ? 'ios-star' : 'ios-star-outline'}
            size={26}
            style={{ color: tintColor }}
          />
        ),
      },
    };
    
    //**** More Tab
    const MoreTab = ({ navigation }) => (
      <SimpleScreen
        navigation={navigation}
        banner="More Tab"
      />
    );
    MoreTab.navigationOptions = {
      title: 'More',
      header: ({ state, setParams, navigate }) => ({
            left: (    
                <Button
                    title={'Menu'}
                    onPress={() => {console.info("Open left drawer")} }
                />
            ),
      }),
      tabBar: {
        label: 'More',
        icon: ({ tintColor, focused }) => (
          <Ionicons
            name={focused ? 'ios-more' : 'ios-more-outline'}
            size={26}
            style={{ color: tintColor }}
            onPress={() => {console.info("Open right drawer")} }
          />
        ),
      },
    };
    
    
    //====================================================
    //            **** Navigation setup ****
    //====================================================
    //********* Drawer setup
    const DrawerNavRight = DrawerNavigator({
        Profile: { screen: Profile },
        Settings: { screen: Settings },
    }, {
        drawerPosition: 'right',
    });
    
    const DrawerNavLeft = DrawerNavigator({
      Profile:  { screen: Profile, },
      Settings: { screen: Settings, },
    });
    
    //DrawerNavLeft is here to show that the Drawer works in isolation 
    //  when `TabBar:    { screen: TabNav },`  within StackNav is commented out
    //DrawerNavRight.navigationOptions = {
    DrawerNavLeft.navigationOptions = {
        title: 'Main Menu',
        header: ({ state, setParams, navigate }) => ({
            left: (    
                <Button
                    title={'Menu'}
                    onPress={() => {navigate('DrawerOpen')} }
                />
            ),
        }),
    };
    
    //********* Tab setup
    const TabNav = TabNavigator({
      Home:      { screen: HomeTab, },
      Rewards:   { screen: RewardsTab, },
      More:      { screen: MoreTab, },
    });
    
    //********* Stack setup
    const StackNav = StackNavigator({
      TabBar:    { screen: TabNav },
      DrawerNav: { screen: DrawerNavRight },
    });
    
    
    //====================================================
    //            **** Styles setup ****
    //====================================================
    //********* Styles
    const styles = StyleSheet.create({
      welcome: {
        fontSize: 12,
        textAlign: 'center',
        margin: 30,
      },
      container: {
        marginTop: 20,
      },
    });
    
    
    //********* AppRegistration
    AppRegistry.registerComponent('navigationAppProto', () => StackNav);

**Comment by sigmazen** [comment]
Hi
I've been playing around with this today ... really impressed with its simplicity, however I'm pretty new to this ( ie ES6 + JSX ) so it's taking rather a long time 😕 
Anyway I've created a mashup with my other question ( #268 ) which I'll add to, but in terms of a chest-of-drawers approach 😜   I got the following working:

    //********* Drawer setup
    const DrawersLeft = DrawerNavigator({
      Inbox:  { screen: InboxScreen,    },
      Drafts: { screen: DraftsScreen,   },
    });
    
    const DrawersRight = DrawerNavigator({
      Profile:  { screen: ProfileScreen,    },
      Settings: { screen: SettingsScreen,   },
    }, {
        drawerPosition: 'right',
    });
    
    
    //********* Tabs setup
    const Tabs = TabNavigator({
      Home:     { screen: HomeScreen,    },
      Email:    { screen: DrawersLeft,   },
      Settings: { screen: DrawersRight,  },
    });
    
    //********* Stack setup
    const Stack = StackNavigator({
      Tabs:   { screen: Tabs         },
    });

and the associated `navigationOptions` to open them is `navigate('DrawerOpen')` 
No doubt I'll break it as I try to add more screens within the Home tab journey, but for now it's working
Cheers

**Comment by pcofilada** [comment]
I think I got the answer I need. Closing this. Thanks @satya164 @sigmazen
