### ISSUE TITLE
Update to react-native@0.49 and flow-bin@0.53

### ISSUE THREAD

**Issue by Ashoat** [react-community/react-navigation#2771]
Flow 0.53 completely revamps the way React components are typed, along with several other major changes to React types. react-native@0.49 uses flow-bin@0.53, so we'll have a whole lot of type errors to correct when we update to react-native@0.49. I'm opening this issue to track my own work in fixing these type errors so we can update to the latest version of React Native. Earlier discussion in #2658.

Right now I'm waiting for Expo SDK 22, since the NavigationPlayground example relies on Expo, and we can't mix react-native versions between the root directory and the NavigationPlayground directory. We won't be able to push a version that passes CI with react-native@0.49 until Expo SDK 22 has been released.

**Comment by Ashoat** [comment]
(I don't seem to be able to assign myself, but if somebody else wants to do that please go ahead!)

**Comment by Ashoat** [comment]
`react-native-git-upgrade` makes some important changes to .flowconfig when upgrading to 0.49: https://gist.github.com/Ashoat/e755141aaf0fc471bb8d782e88498f8a

Package authors (that's us!) will need to manually make these changes when we update.

**Comment by kelset** [comment]
Looks like [Expo 22 is out](https://blog.expo.io/expo-sdk-v22-0-0-is-now-available-7745bfe97fc6).

Moreover, as a reference for this update I've seen [this PR](https://github.com/devtools-html/debugger.html/pull/4433) which may be useful example of how another repo handled it :)

**Comment by Ashoat** [comment]
Awesome! Another blocker is that [this PR](https://github.com/react-native-community/react-native-tab-view/pull/361) on react-native-tab-view needs to be accepted and a new version needs to be released.

**Comment by kelset** [comment]
New version of `react-native-tab-view` is [out](https://github.com/react-native-community/react-native-tab-view/releases/tag/v0.0.70)!
With
a
lot
of
BC

Ok, probably then we need two separate PR I guess.

**Comment by Ashoat** [comment]
Unfortunately I think it'll have to be a single PR, since `react-native-tab-view@0.0.70` is incompatible with RN 0.48 and `react-native-tab-view@0.0.69` is incompatible with RN 0.49. I'll take a look today.

**Comment by satya164** [comment]
It's straightforward to address those breaking changes, it's just renaming 2 methods (react-navigation uses only 1) :p

They were deprecated few versions ago.

**Comment by kelset** [comment]
@satya164 you are right, sorry I didn't want to flame in any way, when I wrote that comment I was basically stunned by the complexity of this overall task @_@ ;)

**Comment by satya164** [comment]
no worries

**Comment by kelset** [comment]
Closed via #2845
