### ISSUE TITLE
[Beta 14] TabNavigator > TabBarBottom > tabBarIcon prop broken on Android

### ISSUE THREAD

**Issue by joncursi** [react-community/react-navigation#2772]
In navigation options, `tabBarIcon` has no effect on android. I am getting empty spaces where tab icons used to be in beta.13.

![0](https://user-images.githubusercontent.com/4974609/31686232-a3326ca0-b353-11e7-80e2-04502d693aaf.png)

iOS is fine.

**Comment by spencercarli** [comment]
That one's my bad. Fixing it now 😄

**Comment by spencercarli** [comment]
v1.0.0-beta.15 was just released with this fix.

**Comment by WillCoco** [comment]
still not work.  v1.0.0-beta.15  rn0.47 android 6.0

**Comment by kelset** [comment]
@WillCoco that's weird, `beta.15` fixed it for me too.

Can you provide a code sample that shows the bug?

**Comment by chhschou** [comment]
Still an issue for me on `beta.21`.
In the react-navigation examples I replaced `import Ionicons from 'react-native-vector-icons/Ionicons';` with `import { Ionicons } from '@expo/vector-icons';` in `SimpleTabs.js` and icon does not show on tabs. If I add a `<Ionicons/>` as part of content then it does show up.
