### ISSUE TITLE
react navigation custom tabBarComponent?

### ISSUE THREAD

**Issue by wuyunqiang** [react-community/react-navigation#2776]
https://stackoverflow.com/questions/46802619/react-navigation-custom-tabbarcomponent
bug like that:
![rendericon](https://user-images.githubusercontent.com/13480948/31702472-db9b1bc6-b409-11e7-869a-e548f4fd9d6f.png)

navigator:
```
const LeaveListIndex = TabNavigator(
    {
        LeaveUnCheckList: { screen: LeaveUnCheckList },
        LeaveFinished:{screen: LeaveFinished}
    },
    {
        lazy: true,
        // swipeEnabled: true,
        tabBarComponent:props => <Tab {...props}/>,
        tabBarPosition: 'bottom',
        animationEnabled: true,
        tabBarOptions: tabbaroption,
        headerLeft:null,
    });
```
page页面
```
static navigationOptions = ({navigation})=>({
        tabBarLabel:'查看',
        headerTitle:navigation.state.params.title,
        tabBarIcon: ({ tintColor,focused }) => (
            <Image style={SKIN.tabImage} source={focused?AppImages.MyPost.lookchoose:AppImages.MyPost.look}/>
        ),
    });
```
custom Tab
```
export default class Tab extends Component {
    renderItem = (route, index) => {
        const {
            navigation,
            jumpToIndex,
        } = this.props;

        const focused = index === navigation.state.index;
        const color = focused ? this.props.activeTintColor : this.props.inactiveTintColor;
        return (
            <TouchableOpacity
                key={index}
                style={styles.tabItem}
                onPress={() => jumpToIndex(index)}
            >
                <View
                    style={styles.tabItem}>
                    {this.props.renderIcon(color,focused)}
                    <Text style={{ color }}>{this.props.getLabel()}</Text>
                </View>
            </TouchableOpacity>
        );
    };

    render(){
        console.log('Tab this.props',this.props);
        const {navigation,} = this.props;

        const {routes,} = navigation.state;
        return (
            <View style={styles.tab}>
                {routes && routes.map(this.renderItem)}
            </View>
        );
    }
}
```
how I can get tabBarLabel and tabBarIcon?

### Your Environment
| software         | version
| ---------------- | -------
| react-navigation  |  ^1.0.0-beta.11
| react-native     | 0.46.4
| node             | 8.3.0
| npm or yarn      | v0.27.5

**Comment by wuyunqiang** [comment]
ok I know.

**Comment by walker-ll** [comment]
same issue here

**Comment by wuyunqiang** [comment]
look that
https://github.com/wuyunqiang/ReactNativeUtil/issues/9
@walker-ll

**Comment by walker-ll** [comment]
@wuyunqiang 解决了，但是遇到一个奇怪的问题，我用了StackNavigator嵌套了StackNavigator，当最外面的StackNavigator在redux的action里去dispatch跳转动作的时候，发现StackNavigator会不停的setState，在对应的reducer里debug发现一直在循环调用type为Navigation/COMPLETE_TRANSITION的action

**Comment by wuyunqiang** [comment]
设置animationEnabled:false

**Comment by walker-ll** [comment]
@wuyunqiang 没有用，我debug看到的是StackNavigator里循环调用onTransitionEnd()方法造成的，可能也有用了immutableJS的原因，但是检查过listener还有navigation.state里都已经转成plain object，debug的时候也没有问题，在React Navigation的issue里查到的目前两种方法：
1、在navigator的reducer里判断新旧state是否相同，相同就直接返回state，不同返回新state
2、不用redux维护navigator的状态，直接用ref引用出来
参照：[https://github.com/react-navigation/react-navigation/issues/1439#issuecomment-303661539](url)
我偏向第二种，心累

**Comment by wuyunqiang** [comment]
我感觉你这个应该是动画原因造成的 以前也遇到过类似的 后来我爸动画禁止了 或者自己实现动画的函数 
不过你解决了就好
