### ISSUE TITLE
About go back too.

### ISSUE THREAD

**Issue by xclidongbo** [react-community/react-navigation#2778]
example:

```

MainTabs: {
    Stack1:{A, B},
    Stack2:{A, B},
    Stack3:{A, B},
    Stack4:{A, B},

}

```
MainTabs: TabNavigator,
StackX: StackNavigator,
A, B : Screen,

StackX => A => B

How can I go back from B to StackX.
StackX is one of { Stack1,Stack2,Stack3,Stack4, }

**Comment by kelset** [comment]
Closing for 3 reasons:
* you literally just opened another issue related to goBack - there'a an edit function on github
* there are tons of issues related to goBack so it's duplicate, next time search for issues before opening a new one
* you haven't respected the issue template
