### ISSUE TITLE
TabBarTop w/ scrollEnabled does not scroll the tab bar correctly when an off-screen tab is focused

### ISSUE THREAD

**Issue by mauritsd** [react-community/react-navigation#278]
If you scroll a TabBarTop (w/ scrollEnabled) and then focus an offscreen tab the focused tab label does not animate to the 'middle' of the tab bar (like the currently focused tab indicator does). I've only tested this so far on iOS so I don't know whether Android is also affected by this issue. Note that the correct tab page is focused, and swiping the content view will fix the positioning of the tab bar labels.

I've attached a screenshot showing the issue. The tab to the left ("OLOGIE" in white text is visible) is currently focused and should appear under the yellow tab focus indicator, but doesn't.

![screen shot 2017-02-10 at 12 17 31](https://cloud.githubusercontent.com/assets/835197/22825165/cfbfa486-ef8b-11e6-8be9-6144bc2d66ec.png)

**Comment by satya164** [comment]
- Do you have an example project?
- Have you set `width` in `tabStyle`?

**Comment by mauritsd** [comment]
Width was not set initially, but setting it does not resolve the issue for me. The following code reproduces the problem for me (on the iOS simulator).

```
import React from 'react';
import {
  AppRegistry,
  Text,
} from 'react-native';
import { TabNavigator, TabView } from 'react-navigation';


function makeTabComponent(i) {
    return class extends React.Component {
      static navigationOptions = {
        title: `Tab #${i}`,
      };

      render() {
        return <Text>This is the {i}'th tab!</Text>;
      }
    }
}

const ReactNavigationTestCase = TabNavigator({
  Tab1: { screen: makeTabComponent(1) },
  Tab2: { screen: makeTabComponent(2) },
  Tab3: { screen: makeTabComponent(3) },
  Tab4: { screen: makeTabComponent(4) },
  Tab5: { screen: makeTabComponent(5) },
  Tab6: { screen: makeTabComponent(6) },
  Tab7: { screen: makeTabComponent(7) },
  Tab8: { screen: makeTabComponent(8) },
  Tab9: { screen: makeTabComponent(9) },
  Tab10: { screen: makeTabComponent(10) }
}, {
  initalRouteName: 'Tab1',
  tabBarComponent: TabView.TabBarTop,
  tabBarPosition: 'top',
  swipeEnabled: true,
  tabBarOptions: {
    scrollEnabled: true,
    tabStyle: { width: 100 }
  }
})

AppRegistry.registerComponent('ReactNavigationTestCase', () => ReactNavigationTestCase);
```

An example project with the code above is available [here](https://github.com/mauritsd/ReactNavigationTabBarScrollingBugRepro/).

**Comment by Fenwil** [comment]
@mauritsd This is the solution that I made and works for me. I hope it helps

```
const routeConfiguration = {
  News: { screen: News },
  Databank: { screen: DataBank },
  Videos: { screen: Videos }
};

const numberOfTabs = Object.keys(routeConfiguration).length;
const tabWidth = width / numberOfTabs;

const tabNavigatorConfig = {
  tabBarOptions: {
    tabStyle: {
      width: tabWidth,
    }
  }
};

const MainTab = TabNavigator(routeConfiguration, tabNavigatorConfig);
```

**Comment by mauritsd** [comment]
Thanks, but I think a bugfix is necessary here. I'll have a look at the iOS code for the tab bar and maybe send a pull request.

**Comment by toninho** [comment]
This is not working for me when swipe the tabs menu and click at some tab as you can see.
![tabbar2](https://cloud.githubusercontent.com/assets/3512/24662800/91a7cbc2-192c-11e7-8d5b-4cc67b40be13.gif)

**Comment by townmulti** [comment]
@Fenwil Where are you getting the `width` from in `const tabWidth = width / numberOfTabs;`?

**Comment by kelset** [comment]
Pinging OP @mauritsd since this issue is quite old and related to an old version of the lib. If no answer I'll close in 7 days.

**Comment by mauritsd** [comment]
This has been fixed in one of react-navigation's dependencies. Sorry; forgot to close it.

**Comment by alpamys-qanybet** [comment]
@mauritsd which dependencies, I am figuring out this issue and cannot handle it.

**Comment by alpamys-qanybet** [comment]
@toninho, can you share your code plz.

**Comment by alpamys-qanybet** [comment]
I was able to make it work by changing the original source code in ```node_modules/react-native-tab-view/src/TabBar.js -> _handleTabPress``` and adding there
```
if (this.props.scrollEnabled) {
      global.requestAnimationFrame(() => {
        this._scrollView.scrollTo({
          x: this.props.navigationState.index * this.props.layout.width,
          animated: false,
        });
      });
 }
```

in my case I set ```tabStyle width``` to ```device width```

**Comment by alpamys-qanybet** [comment]
@toninho, anyway, please share your code. this is my email ```alpamys.qanybet@gmail.com```
