### ISSUE TITLE
this.props.navigation.state doesn't work

### ISSUE THREAD

**Issue by salateeq** [react-community/react-navigation#2782]
hi 
i'm new in react native , i'm trying to navigate from screen 1 to screen 2 with parameter but i'm not get the parameter in the second screen

`import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View,
} from 'react-native';
import Login from './app/component/Login';
import Login1 from './app/component/Login1';
import {
  StackNavigator,
} from 'react-navigation';

class mobiletodos extends Component<{}> {
  static navigationOptions = {
    title: 'Home',
  };
  render() {
      return (
          <View style={{alignItems: 'center', justifyContent: 'center', flex: 1}}>
            <Text onPress={this._handlePress}>Todos Welcome Screen!</Text>
          </View>
        )
    }
    _handlePress = () => {
      this.props.navigation.navigate('Login',{test2:'test1'});

  }

}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
export default StackNavigator({
  mobiletodos: {
    screen: mobiletodos,
  },
  Login1:{
      screen:Login1,
    },
  Login:{
    screen:Login,
  },

});
AppRegistry.registerComponent('reactproject00',()=>mobiletodos)
`

`import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View,
  Navigator,
  Image,
  TextInput,
  TouchableOpacity,
  ListView,
  AsyncStorage
} from 'react-native';
import {
  StackNavigator,
} from 'react-navigation';

export default class Login extends Component<{}> {
  static navigationOptions = {
    title: 'Login',
  };
    constructor(props) {
        super(props);
        this.state  ={
          isLoading:true,
          cloneStudent:[],
          paramss :'',
        }

  }
  componentDidMount(){
    fetch("http://localhost:8888/newApi/index1.php").then((response)=>response.json()).then((responseJson)=>{
      var ds = new ListView.DataSource({rowHasChanged:(r1,r2)=>r1!=r2});

      this.setState({
      isLoading:false,
      cloneStudent:ds.cloneWithRows(responseJson),
      paramss  : this.props.navigation.state
});
   })
  }

  render() {
    if(this.state.isLoading){
      return(
        <View><Text>Wait</Text></View>
      )
    }
    return (
  <View>
  <Text>Login</Text>
  <Text>{this.state.paramss.test2}</Text>
  <Text>{this.props.navigation.state.test2}</Text>

  <ListView
  dataSource={this.state.cloneStudent}
  renderRow={(rowData)=>
    <Text>{rowData.name}</Text>
  }
  />
  </View>

    );
  }

}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
  backgroundImage:{
    flex:1,
    alignSelf:'stretch',
    width:null,
    justifyContent:'center',
  },
  content:{
    alignItems:'center',
  },
  logo:{
    color:'white',
    fontSize:40,
    fontStyle:'italic',
    fontWeight:'bold',
    textShadowColor:'#252525',
    textShadowOffset:{width:2,height:2},
    textShadowRadius:15,
    marginBottom:20
  },
  inputContaner:{
    margin:20,
    marginBottom:5,
    padding:20,
    paddingBottom:10,
    alignSelf:'stretch',
    borderWidth:1,
    borderColor:'#fff',
    backgroundColor:'rgba(255,255,255,0.2)'
  },
  input:{
    fontSize:16,
    height:40,
    padding:10,
    marginBottom:10,
    backgroundColor:'rgba(255,255,255,1)'
  },
  buttonConta:{
    alignSelf:'stretch',
    margin:20,
    padding:20,
    backgroundColor:'blue',
    borderWidth:1,
    borderColor:'#fff',
    backgroundColor:'rgba(255,255,255,0.6)',
    marginBottom:15,
  },
  buttonText:{
    fontSize:16,
    fontWeight:'bold',
    textAlign:'center'
  }
});

AppRegistry.registerComponent('Login',()=>reactproject00)
`

output : 
[ Login 
names from the API without "test2"text

**Comment by caihuajian** [comment]
You must be use this.props.navigation.state.params.test2,try it

**Comment by salateeq** [comment]
still is not shown , i have try with 
  <Text>{this.state.paramss.test2}</Text>
  <Text>{this.props.navigation.state.test2}</Text>
  <Text>{this.props.navigation.state.params.test2}</Text>

still doesn't shown
