### ISSUE TITLE
Icons not showing on TabBar

### ISSUE THREAD

**Issue by jayspirits** [react-community/react-navigation#2783]
### Current Behavior
- Icons not showing. Im using TabBarBottom for my tabBarComponent.

### Expected Behavior
- It supposed to be working. Already have it on production. It happens when I uninstall all my npm packages and reinstalled again.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.11
| react-native     | 0.47.0
| node             | 8.3.0
| npm      | 5.3.0

**Comment by spencercarli** [comment]
Fixed in #2774 and just released 1.0.0-beta.15 with the fix!

**Comment by jayspirits** [comment]
Yes. Icon is back again :)
