### ISSUE TITLE
App is navigating to the initial route twice on load of ejected app

### ISSUE THREAD

**Issue by AhadCove** [react-community/react-navigation#2786]
I'm having an issue for the first time using react-navigation. 
Using a stack navigator I'm getting the initial route being loaded twice. 

This is an expo kit react native ejected app. I tried to make a new app without ejecting it and seen that it was working perfectly fine, but as soon as I ejecting it and loaded it back up, it started doing the same thing as my other ejected app.

What it's doing is mounting the initial component and then navigating to the same initial component immediately. It even will allow me to go back which is the exact same component I was on.

**Comment by AhadCove** [comment]
Yes, this is correct. I tried it with a plain react native app after ejecting and it works as it should be. I guess I should post this issue over in Expo then?

**Comment by murad-aghakishiyev** [comment]
Have the exact same issue with ejected app, it does not happen on android but it happens on ios (simulator)

**Comment by AhadCove** [comment]
Yes, @murad-aghakishiyev there is a workaround. Apparently, it's a known issue.
Kind of Homebrewy, but it works!

[https://github.com/react-community/react-navigation/issues/2599#issuecomment-337845786](react-community/react-navigation#2599 (comment))

**Comment by kelset** [comment]
@AhadCove the link you posted seems to be broken :/ Anyway yeah I think you should close it here and post it on Expo's repo.

**Comment by AhadCove** [comment]
Oh sorry about that, just fixed the link. Okay closing now

**Comment by kelset** [comment]
Thanks for the fix, I still think it's worth creating an issue on Expo's repo to understand why it happens only for apps that get ejected :/

**Comment by AhadCove** [comment]
Yeah, I agree. This is the only response I received when I posted it over there. But, I am interested in wanting to know why. I will ask and see if I get a response
