### ISSUE TITLE
Get the previous scene in the tabBarOnPress callback

### ISSUE THREAD

**Issue by pietro909** [react-community/react-navigation#2787]
### Current Behavior
- The callback `tabBarOnPress` [used here](https://github.com/react-community/react-navigation/blob/master/src/views/TabView/TabView.js#L104) takes as arguments `scene: TabScene, jumpToIndex: (index: number) => void` with `scene` as the destination scene.

### Expected Behavior
- In order to implement a custom behavior, I need to know what is the scene we just left. Can we add `prevScene: TabScene` as the previous scene?
- Alternatively: is there a way to retrieve that information? I already inspected the `navigation` object and doesn't store that information.

Thanks

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | #master
| react-native     | "^0.48.4"
| node             | "6.10.3"
| npm or yarn      | "1.1.0"

**Comment by sanjayholla94** [comment]
There's a **workaround** to get the previous screen inside tabBarOnPress. 

Let's say you have this Tab Navigator:
```js
const TabNav = TabNavigator({
    ExampleScreen: {
        screen: ExampleScreen
    }
});
```
Add the following to the file where you're using the Tab Navigator. This will set previous tab in the screenProps and it can be used in all the screens of the tab navigator. Every time the `navigationState` changes, `previousTabScreen` is updated
```js
class App extends React.Component {
    
    getCurrentRouteName = navigationState => {
        if (!navigationState) {
        return null;
        }
        const route = navigationState.routes[navigationState.index];
        if (route.routes) {
        return this.getCurrentRouteName(route);
        }
        return navigationState.routeName;
    };

    render(){
        return(
            <TabNav
                onNavigationStateChange={(prevState, currentState) => {
                    const currentTabScreen = this.getCurrentRouteName(currentState);
                    const previousTabScreen = this.getCurrentRouteName(prevState);
                    if (currentTabScreen !== previousTabScreen) {
                        this.setState({
                            previousTabScreen: previousTabScreen,
                        });
                    }
                }}
                screenProps={{
                    previousTabScreen: this.state.previousTabScreen,
                }}
            />
        )
    }
}
```
And in the screen where you're using tabBarOnPress: 

```js
class ExampleScreen extends React.Component{
    static navigationOptions = ({screenProps}) =>({
        tabBarOnPress: (scene, jumpToIndex) => {
            // You can use sceneProps.previousScreen here
        }
    });
};
```
It would be good if it is possible to access the previous screen in the tabBarOnPress parameters though.

**Comment by pietro909** [comment]
Thank you, storing that information somewhere else and track it on my own was the first approach.

I just think it that since the Navigator is already doing that I can simply ask it and rely on its logic, and it is the kind of information one expects to be exposed, it's not an internal implementation detail.

**Comment by sanjayholla94** [comment]
In one of my use cases, I needed access to the previous screen and I used the above approach. But I believe that having access to the previous screen in tabBarOnPress will be helpful.

**Comment by carlost** [comment]
@sanjayholla94 ... I had implemented something similar using the react-navigation v1.x StackNavigator.

I just upgraded to v2.2.3 and the scene's `navigationOptions` method is invoked before the `onNavigationStateChange` event handler is invoked. Have you see anything like this?
