### ISSUE TITLE
onPress getting invoked automatically

### ISSUE THREAD

**Issue by jjdp** [react-community/react-navigation#2792]
```
static navigationOptions = ({navigation}) => {
    const params = navigation.state.params;

   let someFunction
   if(params && params.someData)  {
   someFunction = function() {
       console.log('invoked immediately');
   }

    let headerRight = (
        <View style={styles.rightView}>
          <View
            style={styles.rightIconWrapper}>
            <View style={styles.rightHeaderIcon}/>
          </View>
          <TouchableOpacity
            onPress={() => someFunction()}>
          </TouchableOpacity>
        </View>
      );

    return {
      headerRight: headerRight
    };
  }
```

Any idea why my `someFunction()` is invoked immediately as soon as my data is fetched?

I sometimes use setParams when i fetch my data.

**Comment by jose920405** [comment]
hi @jjdp your `onPress` is bad structured is not a `react-navigation` issue.

You should use

`onPress={() => { this.someFunction() }}>`
or
`onPress={() => this.someFunction }>`

**Comment by jjdp** [comment]
it’s not a component function. it’s inside the static navigation action.

**Comment by vojtechnovak** [comment]
@jjdp can you reproduce this in an expo snack? It indeed doesn't seem to be a react navigation issue.

**Comment by kelset** [comment]
This is not a library issue. So I'll close the issue.
But yes, if you can provide a [Snack](https://snack.expo.io/) snippet we'll try to help you out.

I think you simply need to write
```js
   someFunction = () => {
       console.log('invoked immediately');
   }
```
or something :/ again, having real code would be better.
