### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by SkyzohKey** [react-community/react-navigation#2797]
Hey guys, the [website](https://reactnavigation.org) seems to be down for me. Either I get the "500" error page or cloudflare host down page.

Workarround for people needing docs right now: 
1. Check the [`docs/` folder in this repo](https://github.com/react-community/react-navigation/tree/master/docs)
2. Or use this [cached version of October, 8 2017](https://web.archive.org/web/20171008231004/https://reactnavigation.org).

**Comment by kelset** [comment]
hey thanks for reporting, I just changed the title to remove the f word. That said, thanks again, we'll look into it asap

**Comment by SkyzohKey** [comment]
Ǹow it says:
```
503 
The deployment is currently unavailable.
```

**Comment by kelset** [comment]
looks like it's related to Zeit, that we use for deployment. Hopefully will be back on soon

**Comment by matthamil** [comment]
Yep, looks like [others are experiencing issues as well](https://twitter.com/search?f=tweets&vertical=default&q=zeithq&src=typd&lang=en). Worst case scenario, you can search the docs on GitHub or clone the repo and run the website locally.

**Comment by skevy** [comment]
It's back now folks. We moved the website to a paid Heroku account. Hopefully life will be better now.
