### ISSUE TITLE
Documentation: Differences from `NavigationExperimental`

### ISSUE THREAD

**Issue by kkamperschroer** [react-community/react-navigation#28]
First of all, congrats on the release. Everything looks great and is overall well documented.

One thing I think is missing are documented reasons why this would be a better option than using the built-in [`NavigationExperimental`](https://facebook.github.io/react-native/docs/navigation.html#navigationexperimental) library that is actively being developed on the react-native side.

For example, my team is using `NavigationExperiemental` on the react-native side and `react-router` on the web side. Is the primary gain by using this new `react-navigation` library that you can share all navigation logic between both?

I'd be happy to issue a PR documenting this if I just had a better understanding. Thanks for your time.

**Comment by satya164** [comment]
This builds upon the NavigationExperimental library. Most of the components from NavigationExperimental are reused with little changes. NavigationExperimental will be deprecated and React Navigation will replace it.

You can use React Navigation both in the web and react native.

**Comment by kkamperschroer** [comment]
That is excellent. Thank you for the context @satya164. That is the key piece of information that I think is not obvious from reading the docs or the intro.

I think this information could be presented cleanly in a `motivation` section on the README. Knowing that this library is meant to be the replacement for `NavigationExperimental` makes it much more obvious that this is what my team should move to going forward.

**Comment by satya164** [comment]
Feel free to send PRs to improve the docs.

**Comment by kkamperschroer** [comment]
Will do. Thanks again!
