### ISSUE TITLE
One of my label contains too many characters in TabNavigator

### ISSUE THREAD

**Issue by AlfredOdling** [react-community/react-navigation#2800]
I want my TabNavigator to look like this: 
<img width="324" alt="skarmavbild 2017-10-21 kl 22 54 30" src="https://user-images.githubusercontent.com/18306386/31852934-e2fc0158-b645-11e7-8357-c9300fd6bad1.png">

But it looks like this: 
<img width="324" alt="skarmavbild 2017-10-21 kl 22 49 34" src="https://user-images.githubusercontent.com/18306386/31852917-b4ff4a94-b645-11e7-9d4e-0431e6b01857.png">

My code: 
```
const MediaTabNav = TabNavigator({
  Images: {
    screen: ImageTabStack,
  },
  Albums: {
    screen: AlbumTabStack,
  },
  'Shared albums': {
    screen: SharedAlbumTab,
  }
}, 
  {
    tabBarPosition: 'top',
    animationEnabled: true,
    tabBarOptions: {
      style: {
        backgroundColor: 'white',
      },
      activeTintColor: 'black',
      labelStyle: {
        fontSize: 22,
        fontWeight: '100',
      },
    },
  })
```

I've tried messing with the tabStyle and the style in tabBarOptions but with no effect. 

Do any one know what might be wrong? 
Thanks

**Comment by kelset** [comment]
A few questions:
1. which version of the library are you using? 'cause we modified the font in the header to autoscale via this https://github.com/react-community/react-navigation/commit/f84fe152721f0f6f80f799dbcd9bcbf5f42d61d0

2. in the first image the font looks smaller (like a 16 vs a 14/13), or is it just me?

**Comment by AlfredOdling** [comment]
I'm using
`    "react-navigation": "^1.0.0-beta.15"
`

The font size (22) is the same for all labels and the dimensions of the tabs are 125x48.5 and respective text elements are: 
```
(30.0, 21.0) 65.0x 26.5, 
(154.0, 21.0) 67.5x26.5, 
(278.0, -5.5) 69.5x53.0
```

**Comment by spencercarli** [comment]
The reason this is occuring is due to the [`flex:1`](https://github.com/react-community/react-navigation/blob/master/src/views/TabView/TabBarBottom.js#L242) that each tab item has, thus allowing each tab item to take up an equal amount of space (regardless of the contents of that tab item). You'll have to override that, perhaps with a flex: 0?
