### ISSUE TITLE
Back button centered in iOS

### ISSUE THREAD

**Issue by andrewnaeve** [react-community/react-navigation#2801]
navigation back button in centered in iOS, as pictured. Component has bare minimum of styling with flex:1, and nothing more, just to demonstrate. 

"react-navigation": "^1.0.0-beta.15",
"react": "^16.0.0",
"react-native": "^0.49.3",

<img width="438" alt="screen shot 2017-10-21 at 10 35 23 am" src="https://user-images.githubusercontent.com/16847584/31854376-ee09981a-b64c-11e7-8a4b-0f48f9cf75da.png">
<img width="512" alt="screen shot 2017-10-21 at 10 35 38 am" src="https://user-images.githubusercontent.com/16847584/31854377-f20d7e40-b64c-11e7-8c3d-176725ac131c.png">
<img width="535" alt="screen shot 2017-10-21 at 10 35 49 am" src="https://user-images.githubusercontent.com/16847584/31854378-f3d6e914-b64c-11e7-8882-d5c664d3c6a7.png">

**Comment by kelset** [comment]
Are you sure you don't have any other styling in, for example, the Component in which HomeScreen is rendered?

This to me looks like something related to that. Are you following some tutorial? Because [our intro](https://reactnavigation.org/docs/intro/) doesn't have that issue, as far as I can see.

**Comment by andrewnaeve** [comment]
Confirmed user error. Thanks for the quick reply!
