### ISSUE TITLE
Navigation.setParams() overrides tabsNavigation initial route

### ISSUE THREAD

**Issue by zyadsherif** [react-community/react-navigation#2817]
So I've done my fair share of research and am leaning towards thinking this might be a bug. Please don't bash on me if the ticket isn't clear I'll try my absolute best to explain 

---

### Current Behavior
- Currently am trying to add a function to the navigation state that will handle onTabBarPress to hopefully scroll to the top of a scrollview, exactly how the facebook app does it.
- Whenever I define use the setParams function, going into the tabNavigation stack leads to loading the initialRoute for a fraction of a second then switching to the stack that includes the addressed code
- The code is on the componentDidMount of the main screen from a StackNavigator inside of a TabNavigator
- Below is a simplified example

```
// Main entry point stack
export const Root = StackNavigator({
    Tabs: {
        screen: Tabs,
    },
    Login: {
        screen: Login,
    },
}, {
        initialRouteName: 'Login',
        headerMode: 'none'
    });

// Tabs Stack
export const Tabs = TabNavigator({
    HomeStack: {
        screen: HomeStack,
    },
    FeedStack: {
        screen: FeedStack,
    },
    ProfileStack: {
        screen: ProfileStack,
    },
}, {
        initialRouteName: 'HomeStack',
        tabBarComponent: TabBarBottom,
        tabBarPosition: 'bottom',
    });


// Child stack that is not the initialRoute 
export const FeedStack = StackNavigator({
    Feed: {
        screen: Feed,
        navigationOptions: {
            title: 'Feed',
        },
    },
    Details: {
        screen: WodDetail,
        navigationOptions: ({ navigation }) => ({
            title: `${navigation.state.params.wod.title}`,
        }),
    },
}, {
        initialRouteName: 'Feed',
}


// The cause of all problems Feed Screen, initialRoute for non initial Stack
class Feed extends Component {
    static navigationOptions = (props) => {
        tabBarOnPress: (tab, jumpToIndex) => {
            console.log('tabBarOnPress', tab);
            if (!tab.focused) {
                jumpToIndex(tab.index)
            } else {
                // It works here no problem
                props.navigation.state.params.handleTabBarPress(tab)
            }
        }
    }

    handleTabBarPress = (tab) => {
       // Scrolling logic, nothing fancy
    }
    componentDidMount() {
        this.props.navigation.setParams({ handleTabBarPress: ()=>this.handleTabBarPress })
    }

    render(){
       return(FANCY_STUFF)
    }
}

```
- I've also tried with other example string values, I've also removed the `static navigationOptions` completely and it seems like it's not related to this

### Expected Behavior
- I expect that the the navigator wouldn't switch to this route on adding params, am also wondering how is it able to run this when it's on `componentDidMount` and the initialRoute is on another stack

### My Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.15
| react-native     | 0.48.4
| node             | v6.11.4
| npm or yarn      | 3.10.10

![appvideo](https://user-images.githubusercontent.com/1159370/31969361-a0ccfe82-b914-11e7-84c8-ab62c650c404.gif)

**Comment by elwhitman** [comment]
+1 experiencing the same behavior with setParams call on componentDidMount

**Comment by elwhitman** [comment]
@zyadsherif I recently have hacked a solution where I still call setParams but for a parent, nesting stack navigator and the initial tab does not get switched. i then reference those params accordingly by passing my root navigator to the child tab navigator

**Comment by kelset** [comment]
Hi thanks for reporting, I think it's related to this PR: https://github.com/react-community/react-navigation/pull/2674 - can you confirm it? I'm planning on merging it soon.

**Comment by zyadsherif** [comment]
@elwhitman yeah I thought about the same thing but seemed to me like a not really maintainable solution when having to set local functions that handle this specific screen behaviour.

@kelset yup this seems to be the exact problem.

**Comment by kelset** [comment]
@zyadsherif it got merged, we are going to release a new version prob next week. If you want to check if it works for you can point to master (just be careful 'cause there are some Breaking Changes mostly related to Drawer stuff)

**Comment by zyadsherif** [comment]
@kelset I've checked it on master and works fine, although there's another bug that am not sure if it's related to it or not.

The onTabPress even isn't propagated to the child stacks, I'll close this one for now

**Comment by kelset** [comment]
Ok thanks for reporting, it's probably 'cause of a BC related to that. It will be in the release notes.
