### ISSUE TITLE
Dynamic TabBar Tint Color

### ISSUE THREAD

**Issue by Zyphrax** [react-community/react-navigation#2818]
In my app the colors are based on the properties provided by the native app. 

```typescript
const tabBarIcon = (nameInactive, nameActive) => ({ tintColor, focused }) => (
  <Icon name={focused ? nameActive : nameInactive} size={26} color={focused ? tintColor : Colors.tabInactive} />
);

export default TabNavigator(
  {
    Statistics: {
      screen: Statistics,
      navigationOptions: {
        tabBarLabel: "Statistics"
        tabBarIcon: tabBarIcon("ios-stats-outline", "ios-stats")
      }
    },
    Profile: {
      screen: ProfileNavigator,
      navigationOptions: {
        tabBarLabel: "Profile"
        tabBarIcon: tabBarIcon("ios-contact-outline", "ios-contact")
      }
    }
  },
  {
    tabBarOptions: {
      activeTintColor: Colors.tint
    }
  }
)
```

The issue is that the proper tint color is set in the constructor of my main React Component. However `Colors.tint` is already evaluated when the engine is processing my javascript code.

The only thing I could think of is to wrap my navigator in a function (note the `createElement`):

```typescript
export default () => React.createElement(
  TabNavigator(
    {
      Statistics: {
        screen: StatisticsNavigator,
        navigationOptions: {
          tabBarLabel: "Statistics"
          tabBarIcon: tabBarIcon("ios-stats-outline", "ios-stats")
        }
      },
      Profile: {
        screen: ProfileNavigator,
        navigationOptions: {
          tabBarLabel: "Profile"
          tabBarIcon: tabBarIcon("ios-contact-outline", "ios-contact")
        }
      }
    },
    {
      tabBarOptions: {
        activeTintColor: Colors.tint
      }
    }
  )
);
```

Now comes the magic... it seems that I don't have to change the way I use the navigator:
```typescript
return <MainNavigator />;
```

Is this the best way to do this? Or is there an easier way?
I was hoping that I could make the `tintColor` a property and do something like this:

```typescript
return <MainNavigator tintColor={Colors.tint} />;
```

But that is difficult because React-Navigation's `TabNavigator` not actually a component, but a function that creates a component.

Hopefully this will at least help people facing similar issues.

**Comment by kelset** [comment]
Hi @Zyphrax,
thanks for sharing your solution.

I actually have a similar situation in my app but I have gone this way to "hijack" the tintColor:

```js
import { TabNavigator, TabBarBottom, NavigationActions } from 'react-navigation';

const routeConfiguration = {
  screen1: { screen: screen1 },
  screen2: { screen: screen2 },
  screen3: { screen: screen3 },
};

const tabBarComponent = ({ props }) => {
  props.activeTintColor = colorArray[props.navigationState.index];

  return (
    <TabBarBottom
      {...props}
    />
  );
};

const tabBarConfiguration = {
  tabBarComponent,
  tabBarPosition: 'bottom',
};

export const BottomTabBar = TabNavigator(routeConfiguration, tabBarConfiguration);
```

(this is a simplified version of my code ofc but all the pieces are there)

Let me know what you think of this approach, and if you like it :)

(anyway I'll close this issue since it's nor a bug nor a feature request, but I'd love to hear your feedback)

**Comment by Zyphrax** [comment]
@kelset Thank you for the code snippet!
It is great that you can make the tabBarComponent dynamically like that.

**Comment by firofame** [comment]
react navigation 2.0

`import { createBottomTabNavigator, BottomTabBar } from 'react-navigation-tabs'; //With react-navigation@^2.0.0, no installation is required.`

`    tabBarComponent: props => <BottomTabBar {...props} activeTintColor={drugColor} />,
`

**Comment by hernanif1** [comment]
```
class HomeScreen extends React.Component<{}> {
  getRoutes = () => ({
    screen1: {
      screen: Arrivals,
      navigationOptions: {
        // you can set specific color with your redux this.props.name_propertie from redux
        title: 'Arrivalssss',
        // you can set specific color for each tab
        // tabBarOptions: {
        //   style: { backgroundColor: this.props.theme.background.primary },
        // },
      },
    },
    screen2: { screen: InPort },
  });

  getOptions = () => ({
    tabBarOptions: {
      // this is an example with styled component theme
      style: { backgroundColor: this.props.theme.background.primary },
    },
  });

  getTabs = () => {
    const Tabs = createMaterialTopTabNavigator(
      this.getRoutes(),
      this.getOptions()
    );
    return Tabs;
  };

  render() {
    const Tabs = this.getTabs();
    return <Tabs />;
  }
}
export default withTheme(HomeScreen);
```

**Comment by lvlrSajjad** [comment]
> In my app the colors are based on the properties provided by the native app.
> 
> ```ts
> const tabBarIcon = (nameInactive, nameActive) => ({ tintColor, focused }) => (
>   <Icon name={focused ? nameActive : nameInactive} size={26} color={focused ? tintColor : Colors.tabInactive} />
> );
> 
> export default TabNavigator(
>   {
>     Statistics: {
>       screen: Statistics,
>       navigationOptions: {
>         tabBarLabel: "Statistics"
>         tabBarIcon: tabBarIcon("ios-stats-outline", "ios-stats")
>       }
>     },
>     Profile: {
>       screen: ProfileNavigator,
>       navigationOptions: {
>         tabBarLabel: "Profile"
>         tabBarIcon: tabBarIcon("ios-contact-outline", "ios-contact")
>       }
>     }
>   },
>   {
>     tabBarOptions: {
>       activeTintColor: Colors.tint
>     }
>   }
> )
> ```
> 
> The issue is that the proper tint color is set in the constructor of my main React Component. However `Colors.tint` is already evaluated when the engine is processing my javascript code.
> 
> The only thing I could think of is to wrap my navigator in a function (note the `createElement`):
> 
> ```ts
> export default () => React.createElement(
>   TabNavigator(
>     {
>       Statistics: {
>         screen: StatisticsNavigator,
>         navigationOptions: {
>           tabBarLabel: "Statistics"
>           tabBarIcon: tabBarIcon("ios-stats-outline", "ios-stats")
>         }
>       },
>       Profile: {
>         screen: ProfileNavigator,
>         navigationOptions: {
>           tabBarLabel: "Profile"
>           tabBarIcon: tabBarIcon("ios-contact-outline", "ios-contact")
>         }
>       }
>     },
>     {
>       tabBarOptions: {
>         activeTintColor: Colors.tint
>       }
>     }
>   )
> );
> ```
> 
> Now comes the magic... it seems that I don't have to change the way I use the navigator:
> 
> ```ts
> return <MainNavigator />;
> ```
> 
> Is this the best way to do this? Or is there an easier way?
> I was hoping that I could make the `tintColor` a property and do something like this:
> 
> ```ts
> return <MainNavigator tintColor={Colors.tint} />;
> ```
> 
> But that is difficult because React-Navigation's `TabNavigator` not actually a component, but a function that creates a component.
> 
> Hopefully this will at least help people facing similar issues.

you can do this to achive props for react element

`class ChatsTab extends Component {
  render() {
    const ColorScheme = colorScheme(this.props.isDarkMode);

    return (
      <View style={styles.mainContainer}>
        <ChatsTabNavigator colorScheme={ColorScheme}/>
      </View>
    );
  }
}
const mapStateToProps = state => ({
  isDarkMode: state.isDarkMode.isDarkMode
});

const mapDispatchToProps = dispatch => ({});

export default connect(mapStateToProps, mapDispatchToProps)(ChatsTab);
`


`const tavNav = (props) => React.createElement(
  createMaterialTopTabNavigator(
    {
      ['چت ها']: ChatsRouteOptions,
      ['گروه ها']: GroupsRouteOptions,
.
.
.

`

but on state change , navigation will reset and starts on first tab ...

**Comment by Morriz** [comment]
@hernanif1 I get the infamous no routes error when I use that approach:
```
TypeError: No "routes" found in navigation state. Did you try to pass the navigation prop of a React component to a Navigator child? See https://reactnavigation.org/docs/en/custom-navigators.html#navigator-navigation-prop
```

**Comment by hernanif1** [comment]
Sorry for the late reply,
I had this problem but I don't remember how I fixed it, but maybe these files can help you somehow.

I had to change the config of my navigation

Navigation.js
```js
import React from 'react';
import { StatusBar, Image, TouchableOpacity } from 'react-native';
import { StackViewStyleInterpolator } from 'react-navigation-stack';
import {
  createStackNavigator,
  createMaterialTopTabNavigator,
} from 'react-navigation';

// local imports ....

/* Tabs ----------------- */
const tabs = {
  arrivals: 'arrivals',
  inPort: 'inPort',
  departures: 'departures',
};

export const initialTab = tabs.arrivals;

const Tabs = createMaterialTopTabNavigator(
  {
    [tabs.arrivals]: Movements,
    [tabs.inPort]: Movements,
    [tabs.departures]: Movements,
  },
  {
    initialRouteName: initialTab,
  }
);

Tabs.navigationOptions = props => ({
  title: i18n.t('common:app'),
  paddingTop: StatusBar.currentHeight || 20,
  headerTintColor: themeDark.text.primary, // @FIXME: change to dynamic theme
  headerTitleStyle: { color: themeDark.text.primary },
  headerStyle: {
    elevation: 0,
    shadowOpacity: 0,
    backgroundColor: themeDark.background.primary,
    borderBottomColor: themeDark.background.primary,
  },
  headerRight: (
    <TouchableOpacity onPress={() => props.navigation.navigate('Privacy')}>
      <Image source={themeDark.images.privacy} />
    </TouchableOpacity>
  ),
});

/* Main stack ----------------- */
const Navigation = createStackNavigator(
  {
    SplashScreen,
    Tabs,
    Visit,
    Privacy,
  },
  {
    headerMode: 'screen',
    initialRouteName: 'SplashScreen',
    transitionConfig: () => ({
      screenInterpolator: StackViewStyleInterpolator.forHorizontal,
    }),
    navigationOptions: {
      headerBackTitle: null,
    },
  }
);

export type TabType = $Keys<typeof tabs>;
export default Navigation;
```

after this inside my component I could do this:
Component.js
```js
import React from 'react';
import { bindActionCreators as bind, type Dispatch } from 'redux';
import { type NavigationScreenProp } from 'react-navigation';
import { withTheme } from 'styled-components';
import { compose } from 'recompose';
import { connect } from 'react-redux';

// local imports ...

export type VisitType = {
  title: string,
  data: Array<{
    title: string,
    description: string,
  }>,
};

type PropsType = {
  theme: ThemeType,
  title?: string,
  image?: string,
  data?: Array<VisitType>,
  error?: string,
  refreshing?: boolean,
  getData: typeof Actions.getData,
  navigation: NavigationScreenProp<{ params: { visitId: string } }>,
};

class Visit extends React.Component<PropsType> {
  componentDidMount() {
    const { getData, navigation } = this.props;
    const { visitId } = navigation.state.params;
    getData(visitId);
  }

  render() {
    const { data, error, image, theme, getData } = this.props;
    const { visitId } = this.props.navigation.state.params;

    if (error) return <Error retry={() => getData(visitId)} message={error} />;
    if (!data) {
      return (
        <Container>
          <Loader />
        </Container>
      );
    }

    return (
      <ScrollView>
        <Image source={image} sourceOnError={theme.images.vesselNotFound} />
        <SectionList
          sections={data}
          keyExtractor={(item, index) => item.title + index}
          ItemSeparatorComponent={() => <Divider height={1} />}
          renderItem={({ item, index }) => (
            <SectionList.Item key={index} {...item} />
          )}
          renderSectionHeader={({ section, index }) => (
            <SectionList.Header key={index} {...section} />
          )}
        />
      </ScrollView>
    );
  }
}

export default compose(
  withTheme,
  connect(
    state => ({
      title: Service.getTitle(state),
      image: Service.getImage(state),
      data: Service.getData(state),
      error: Service.getError(state),
    }),
    (dispatch: Dispatch<*>) =>
      // $FlowFixMe
      bind({ getData: Actions.getData }, dispatch)
  ),
  // I created this withHeader just to avoid repetition
  withHeader(({ title, theme }: PropsType) => ({
    title,
    headerTintColor: theme.text.primary,
    headerTitleStyle: { color: theme.text.primary },
    headerStyle: {
      backgroundColor: theme.background.primary,
      borderWidth: 1,
      borderBottomColor: theme.background.primary,
    },
  }))
)(Visit);
```

this is the withHeader just in case of doubt:
withHeader.js
```js
import React, { type ComponentType } from 'react';
import type {
  NavigationScreenProp,
  NavigationStackScreenOptions,
} from 'react-navigation';
import { isEqual } from 'lodash';

type PropsType = {
  navigation: NavigationScreenProp<{
    params: { header: NavigationStackScreenOptions },
  }>,
};

type ConfigType = (props: Object) => NavigationStackScreenOptions;

const withHeader = (config: ConfigType) => (
  WrappedComponent: ComponentType<*>
) => {
  class Header extends React.Component<PropsType> {
    static navigationOptions = ({ navigation }: PropsType) =>
      navigation.state.params && { ...navigation.state.params.header };

    componentDidMount() {
      const options = config(this.props);
      this.props.navigation.setParams({ header: options });
    }

    componentDidUpdate() {
      const { params } = this.props.navigation.state;
      if (params && params.header) {
        const options = config(this.props);

        if (!isEqual(options, params.header)) {
          this.props.navigation.setParams({ header: options });
        }
      }
    }

    render() {
      return <WrappedComponent {...this.props} {...this.state} />;
    }
  }
  return Header;
};

export default withHeader;
```

**Comment by Morriz** [comment]
Tnx for the reply. I forgot to mention that I fixed all my issues by overriding the tabbarcomponent, which allows full control over the styling of all of it.

**Comment by Remote478** [comment]
https://hummock-formula.github.io/zr6od-fxAeCOzKMksnbBxKiI86YijITsKfulJi42d_rckd-NYNJaNZF3m7g5Rx7s2MSvPD-fxLNHX2UbD30oGw/
