### ISSUE TITLE
Remove paddingTop from Drawer contentComponent

### ISSUE THREAD

**Issue by raymundtusk7** [react-community/react-navigation#282]
Hi guys,

How do I get rid of the 20pt white strip at the top of the drawer? Is there a way to override the styles? 

![screen shot 2017-02-11 at 12 00 29 am](https://cloud.githubusercontent.com/assets/25691049/22834106/0ad9fe8c-efef-11e6-88b8-f0dc8916d0e5.png)

Thanks!

Ray

**Comment by rafaelmmathias** [comment]
I'm suggesting a fix for this here: #177. (If dont already exists a better solution)

**Comment by raymundtusk7** [comment]
@rafaelmmathias hope it gets merged soon. The paddingTop is annoying.

**Comment by RobertSheaO** [comment]
Will this fix be making it into a release soon?  Or should I fork it and apply the fix myself?

**Comment by TaiPA** [comment]
@raymundtusk7
How did you change the Drawer background color ? (Sorry, i'm a newbie)

**Comment by RobertSheaO** [comment]
For now, you need to fork the repo, apply the change manually, and then reference it from your package.json.

**Comment by satya164** [comment]
Fixed in #642
