### ISSUE TITLE
contentOptions.labelStyle - fontFamily is not applied

### ISSUE THREAD

**Issue by r0st1kuzh** [react-community/react-navigation#2822]
fontFamily property is not applied to the labelStyle.
Meanwhile, color is.

**Comment by kelset** [comment]
1. please follow the issue template when creating an issue (next time I'll close it right away)
1. does it happen for both Android & iOS? chances are that the font has a different family name on the two platforms
1. have you tested the font in other portions of the app? Does it appear there?
1. which version are you using?

**Comment by r0st1kuzh** [comment]
1. Ok, got it. Sorry about that.
2. Android only. If seems like it defaults to Roboto. I am using the same font which I use in the application. It is showing ok in regular components. I was able to override Drawer Item with ```getLabel={(scene) => {``` but it is not the best way I think
3. Yes. All works
4. "^1.0.0-beta.15",

**Comment by r0st1kuzh** [comment]
Also, when I am specifying headerTitleStyle in the  ```navigationOptions: ({ navigation }) => ({```
it also is not applied and defaults to Roboto on Android. On the iOs all works as expected

**Comment by r0st1kuzh** [comment]
Android 6.0.1

**Comment by kelset** [comment]
Ok, if it works in other portions of the app then my guess is that it's related to the weight of the font in the header.

Can you try adding something like: `fontWeight: Device.isIOS ? '600' : 'normal',` to the options you pass to the header?

Again, it's probably related to how Android "digests" the font you provided it with.

**Comment by r0st1kuzh** [comment]
Thank you. The issue is resolved when I specified `fontWeight: 'normal'` for Android. This can be closed.

**Comment by Adamnator92** [comment]
@kelset it worked for me too! thank you.
