### ISSUE TITLE
Error calling RCTDeviceEventEmitter.emit ::

### ISSUE THREAD

**Issue by jayeszee** [react-community/react-navigation#2826]
### Current Behavior
I seem to be getting a bug on iOS where whenever I open up the drawer (either by swiping or pressing the hamburger button) I get a crash. 

This seems to only happen on the new version of expo which is 22 that uses react@16.0.0-beta-5 and react-native@49... Once I downgrade to alpha 12 and react native 48 it seems to work fine... I'm currently on beta 15 of this package.

on simulator: 
![simulator error](https://user-images.githubusercontent.com/9297599/32020414-f3f8c4f4-b984-11e7-96f6-e0ce94513bab.png)

on physical device:
![image](https://user-images.githubusercontent.com/10326244/32023601-9676d456-b98e-11e7-94f6-f86030f1d2fa.png)

- ✅  on beta 11
- ✅  on beta 12
- ❌  on beta 13
- ❌  on beta 14
- ❌  on beta 15

Looks like something that came with the update from beta 12 to beta 13 somehow doesn't play well with the newer version of react and react native. Android works fine, iOS does not.

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.15
| react-native     | 0.49.3
| react |  16.0.0-beta.5
| node             | 8.6
| npm or yarn      | 4.6.1 // 1.01

**Comment by spencercarli** [comment]
Hmm I'm using react-navigation with the latest RN fine. Can you provide a reproduction of this issue?

**Comment by kelset** [comment]
This is mostly a duplicate of #2826 as far as the error is shown in Android. @jayeszee please have a look at my suggestions there to try and figure how a way to fix it for you.

It's actually really hard to figure out this kind of issue without having a test project/repo that reproduces the error.

**Comment by jayeszee** [comment]
For sure, i’ll have a test project up tomorrow.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jayeszee** [comment]
@kelset @spencercarli https://github.com/jayeszee/navigation-demo I made a quick demo with expo very with similar drawer as my app. Opening the draw and releasing at any point will crash it on iOS

**Comment by kelset** [comment]
Hey @jayeszee thanks for providing the repo, we'll take a look at it asap. I'm starting to see a pattern with people having trouble after they update to RN 0.49 (see #2829) and what I can tell you right away is that we are actively working on properly supporting 0.49.

**Comment by jayeszee** [comment]
@kelset no problem! Thanks alot! in the mean time I'm ok with using beta 12

**Comment by kelset** [comment]
Hey @jayeszee , we released beta.17; does your issue still happen in the latest version?

**Comment by jayeszee** [comment]
i have not tried upgrading! I’ll check it out

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by kelset** [comment]
Ok, let me know - if it's fixed can you please close the issue too? 😇

**Comment by jayeszee** [comment]
@kelset Hi, unfortunately, I just tried it on beta-19 (which is latest) and the bug still seems to be there. =/

**Comment by alongubkin** [comment]
I'm now running beta.19 on React Native 0.50.1 and it works great with all 3 drawers. 

In the beginning I had this problem and I thought it was a bug in react-navigation, but later I found out that it was something silly such as putting drawerWidth=0 in DrawerNavigatorConfig.

Same for https://github.com/react-community/react-navigation/issues/2821.

**Comment by kelset** [comment]
@jayeszee can you check if what @alongubkin says is related to your implementation?

**Comment by jayeszee** [comment]
I don’t think that’s the issue but i can take a look at it. It might just be react native 50.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by leeola** [comment]
Fwiw, I was getting this expo 22.0.0 and react native 0.49.0, but upgrading RN to 0.49.5 fixed the issue for me.

**Comment by SamMatthewsIsACommonName** [comment]
For me the issue was also a drawer width of 0. Maybe there is something that divides by drawerWidth creating infinity?

**Comment by kelset** [comment]
It may be, needs to investigate

**Comment by jayeszee** [comment]
It seems like upgrading to 49.5 fixed the issue for me. Not sure what changes in that version actually fixed it though.

**Comment by kelset** [comment]
@jayeszee gotcha. Well then maybe it was some internal call in RN. Should we keep this open?

**Comment by jayeszee** [comment]
lets close it now Thanks guys!

**Comment by waterstar** [comment]
![img_1960](https://user-images.githubusercontent.com/8625997/43055890-b65c4c8a-8e6b-11e8-98cd-0a29b7260767.PNG)
Still seeing this problem with react@16.0.0-alpha.12 and react-native@0.53.3. No sure how to work around this :(

**Comment by woodpav** [comment]
If you are using expo, make sure you are using `expo install react-native`.
