### ISSUE TITLE
tab switch flash

### ISSUE THREAD

**Issue by wuyunqiang** [react-community/react-navigation#2829]
this is bug!!!

### Current Behavior
like that:
![reactnavigationflash](https://user-images.githubusercontent.com/13480948/32043806-59bc7f76-ba6e-11e7-956d-5fb367673e70.gif)

code:
```
import React, {Component} from 'react';
import {
    Platform,
    View,
    I18nManager,
    TouchableOpacity,
    Easing,
    StatusBar,
    Animated,
    DeviceEventEmitter,
    Image
} from 'react-native';
import './utils';
import { StackNavigator,TabNavigator } from 'react-navigation';
const tabbaroption = {
    activeTintColor: 'red',
    inactiveTintColor: '#999999',
    showIcon: false,
    style: {
        justifyContent:'center',
        alignItems:'center',
        backgroundColor:'#fff'
    },
    indicatorStyle: {
        opacity: 0
    },
    iconStyle:{
        paddingBottom:0,
        paddingTop:0,
        padding:0,
        marginTop:0,
        marginBottom:0,
        width:SCALE(40),
        height:SCALE(40),
    },
    labelStyle:{
        paddingTop:0,
        paddingBottom:SCALE(10),
        marginTop:0,
        padding:0,
        fontSize:FONT(10),
        color:Color.C888888
    },
    tabStyle: {
        height:Platform.OS==='ios'?SCALE(98):SCALE(100),
        justifyContent:'center',
        alignItems:'center'
    }
};
//我发起的请假选项
const TabContainer = TabNavigator(
    {
        Home:{screen:Home},
        Project:{screen:Project},
        Profile:{screen:Profile},
    },
    {
        lazy: true,
        swipeEnabled: true,
        tabBarPosition: 'bottom',
        animationEnabled: true,
        backBehavior: 'none', // 按 back 键是否跳转到第一个Tab(首页)， none 为不跳转
        tabBarOptions: tabbaroption});


const Routes = {
    Root:{screen: TabContainer,},

};

const StackOptions = ({navigation}) => {
    const gesturesEnabled = true;
    const headerStyle= {
            height:Platform.OS==='ios'?SCALE(120):SCALE(120)-20,
            backgroundColor: Color.ffffff,
            borderWidth:0,
        borderBottomWidth:0,
    };
    const headerTitleStyle = {
        fontSize: FONT(17),
        color: '#4b4d56',
        alignSelf: 'center'
    };
    const headerTintColor= '#4b4d56';
    const headerLeft = (
        <TouchableOpacity activeOpacity={1} onPress={()=>{navigation.goBack(null)}}>
            <View style={{paddingLeft:SCALE(30),paddingRight:SCALE(40)}}>
                {/*<Image source={AppImages.Home.back}*/}
                       {/*style={{width:SCALE(20),height:SCALE(37)}}/>*/}
            </View>
        </TouchableOpacity>
    );
    const headerRight=(<View style={{paddingRight:SCALE(30)}}>
        {/*<Icon name="md-home" size={25} color={'transparent'}/>*/}
    </View>);
    return {headerLeft,headerRight,headerStyle,gesturesEnabled,headerTitleStyle,headerTintColor,}
};



const AppNavigator = StackNavigator(
    {
        ...Routes,
    },
    {
        headerMode: 'screen',
        navigationOptions: ({navigation}) => StackOptions({navigation}),
    }
);

export default AppNavigator;
```
Home:
```
export default class Home extends React.Component {
    static navigationOptions = {
        tabBarLabel: '首页',
    };

    constructor(props) {
        super(props);
    }

    render() {
        console.log('render home');
        return (<View style={{
            width: WIDTH,
            height:HEIGHT,
            justifyContent: 'center',
            alignItems: 'center',
            backgroundColor: 'blue'
        }}>
        </View>)
    }
}
```
Project:
```
export default class Project extends React.Component {
    static navigationOptions = {
        tabBarLabel: '项目',
         header: null,
    };

    constructor(props){
        super(props);
    }

    render(){
        console.log('render Project');
        return (<View style={{flex:1, backgroundColor:'red'}}/>)
    }
}
```
Profile:
```
export default class Profile extends React.Component {

    constructor(props){
        super(props)
    }

    componentDidMount() {
        console.log('执行了这里');
    }


    render(){
        return (<View style={{width:WIDTH,height:HEIGHT}}>
            <View style={{width:250,height:230,backgroundColor:'green'}}/>
            <View style={{width:50,height:30,backgroundColor:'blue'}}/>
        </View>)
    }
}
```

### Expected Behavior
switch tab right.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | "^1.0.0-beta.13"
| react-native     |"0.49.3",
| node             |v8.3.0
| yarn      | v0.27.5

**Comment by kelset** [comment]
1. you have `lazy:true` which means that when you first open a new tab a "flash" is basically expected; the tab has not being created yet: it will be created on your first press so for a split second the user should see the background "below" the tabnavigator.

2. the reason why it's probably so noticeable is because you have `console.log();` in every render method. Which affects greatly performances.

3. I don't really understand why you would need a StackNavigator with 1 screen which is the tabnavigator. If you remove the stacknavigator completely does it still happen?

**Comment by wuyunqiang** [comment]
because I have console.log()? 
I dont think. I delete console.log,the bug still here. 
I change react native version to 0.48.4 is right.
![tabnavigationrigh](https://user-images.githubusercontent.com/13480948/32044809-2d92f814-ba71-11e7-95b3-093c696c5c7e.gif).

**Comment by wuyunqiang** [comment]
only ios 
android is right.

**Comment by wuyunqiang** [comment]
OK I know.
this bug because of the header.
if I set  header: null  or header:<View .../> every page will be right.
if I set some page header : null and some header:<View .../> will be show the bug.
@kelset  yes is bug

**Comment by kelset** [comment]
Awesome, thanks @wuyunqiang for pinpointing it. So it's probably related to #2732 (and maybe will be fixed soon via #2520.

**Comment by wuyunqiang** [comment]
if fixed let me know please.
@kelset

**Comment by kelset** [comment]
We'll probably do a new release next week, in the meantime technically you could try pointing to master since it's already merged - but be careful 'cause some other commits have breaking changes (but if you are not using drawers you should be fine) ;)

**Comment by fengshanjian** [comment]
@kelset It's  because of the header. Screen with header to screen header(null)
Is any way to set the backgroundColor of header to transparent ,and set the screen margintop:-64

**Comment by li-z** [comment]
if you don't need tab "animationEnabled",you can set it false,you can resolve this issue

**Comment by wuyunqiang** [comment]
@li-z  it's work.

**Comment by kelset** [comment]
@wuyunqiang so it's fixed? Does it still happen? Should this issue be closed?

**Comment by JuanCAlpizar** [comment]
@kelset  nope it's not fixed, what he probably meant is IF you disable animations as @li-z suggested then it works as a workaround because the flicker doesn't appear, but if you enable them, then the issue it's still there. I'm having the exact same issue, but all of the tabs have a header using `1.0.0-beta.21` which as far as I know it's the latest version

**Comment by wuyunqiang** [comment]
@JuanCAlpizar 
animationEnabled: false .
or
animationEnabled: true,
configureTransition:()=>_configureTransition(),
const _configureTransition = () => {
    return {
        duration: 100,
        timing: Animated.spring,

    };
}
look it https://github.com/wuyunqiang/ReactNativeUtil/issues/29

**Comment by hadesownage** [comment]
I have the same problem, why is this closed ?

**Comment by code-matt** [comment]
This happens in debug for sure, not release. Seems like a non issue.

**Comment by raphaelrk** [comment]
@HafizAhmedMoon solution from #1679 fixed it for me (tested on iOS): 

> I was having the same issue and `containerStyle` was set to transparent. Remove `containerStyle` or make `backgroundColor` to black, this make it unnoticeable.
> 
> ```
> transitionConfig: () => ({
>     containerStyle: {
>       backgroundColor: "#000",
>     }
>   })
> ```

**Comment by brentvatne** [comment]
this should be resolved. if it is not working as expected still on the latest version, please create a new issue with a runnable example on https://snack.expo.io -- thanks!
