### ISSUE TITLE
Change the header height

### ISSUE THREAD

**Issue by zoontek** [react-community/react-navigation#283]
Hi,
First thanks you for the good job 😄 

Is there any way to change the header height?
I tried:

```javascript
static navigationOptions = {
    title: 'Welcome',
    header: navigation => ({
      style: {
        height: 80,
        backgroundColor: 'yellow',
        shadowColor: 'black',
        shadowRadius: 5,
        shadowOpacity: 0.1,
        shadowOffset: {
          height: 3,
          width: 0,
        },
      },
      titleStyle: { color: 'red' },
      left: <Text style={{color: 'red'}} onPress={() => navigation.goBack()}>LEFT</Text>,
      right: <Text style={{color: 'red'}} onPress={() => navigation.goBack()}>RIGHT</Text>,
    })
  }
```

And only get this weird result: https://transfer.sh/IbAum/header-height.png
I guess this is the problem: https://github.com/react-community/react-navigation/blob/master/src/views/Header.js#L283

**Comment by zoontek** [comment]
I just see #105. It should do the trick when merged.

**Comment by grabbou** [comment]
This is going to be resolved when #257 is merged. My PR changes the layout of header from being absolutely positioned to using normal flex. That means changes to header should produce no glitches.

**Comment by timomeh** [comment]
Possible in latest release, see #341

**Comment by zoontek** [comment]
@timomeh Yes, but elements are not vertically centered on iOS (because of the status bar). I created another issue : https://github.com/react-community/react-navigation/issues/359

**Comment by paweldziura** [comment]
static navigationOptions = {
```
    ...
    header: ({ state, setParams }) => ({
      style: { height: 40, backgroundColor: '#0099ff', justifyContent: 'center' },
      titleStyle: {  },
      tintColor: '#fff'
    })
  }
```

**Comment by aviggiano** [comment]
I am using a property called `headerStyle`:

```javascript
static navigationOptions = ({navigation}) => ({
    title: 'Title',
    headerStyle: {height: 60}
  })
```

**Comment by dcangulo** [comment]
What is the default height?

**Comment by KBB99** [comment]
The default height is 64

**Comment by Kuoyhout** [comment]
@KBB99 The default height is 64 for both ios and android on every os version and device?

**Comment by kesha-antonov** [comment]
> @KBB99 The default height is 64 for both ios and android on every os version and device?

```
const APPBAR_HEIGHT = Platform.select({
  ios: 44,
  android: 56,
  default: 64,
});
```

**Comment by thaothaopt-hcmute** [comment]
V5:
import {useHeaderHeight} from '@react-navigation/stack';
const HEADER_NAVIGATION = useHeaderHeight();

**Comment by allindeveloper** [comment]
Hi @thaothaopt-hcumte
where do exactly do i apply this code

**Comment by rutvikER1999** [comment]
if you want to remove shadow and border bottom from your header in navigation 6 -  you can set

options:{{  headerShadowVisible:  false }}

i used this::::


<NavigationContainer>
      <Stack.Navigator>
        <Stack.Screen name='Home' component={Home} />
        <Stack.Screen name='ForumListing' component={ForumListing} options={{
          title: 'Forum Listing', headerTintColor: 'white', headerStyle: {
            backgroundColor: '#ff8000',
            borderBottomWidth: 0,
            elevation: 0
          },
          headerShadowVisible: false
        }} />
      </Stack.Navigator>
    </NavigationContainer>
