### ISSUE TITLE
animation nonfluency problem

### ISSUE THREAD

**Issue by Herryjoeson** [react-community/react-navigation#2837]
Hey, I found there was a bit of animation nonfluency when the route was jumping, I was using the latest version and using Qualcomm's 835 CPU phone, was I setting the problem, or was there something that wasn't optimized?Didn't anyone find such a problem, or was it my cell phone problem?

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.15
| react-native     | 0.49.3
| node             | 8.1.2
| npm      |5.0.3

**Comment by vonovak** [comment]
hi @Herryjoeson, unfortunately, your description is not detailed enough for us to see what problem you have. Please feel free to reopen the issue, but make sure add some video or screenshots which clearly show the problem. Thanks.
