### ISSUE TITLE
SyntaxError: 'import' and 'export' may only appear at the top level

### ISSUE THREAD

**Issue by eschablowski** [react-community/react-navigation#2838]
Babel gives me this issue when trying to parse react-navigation/src/createNavigationContainer.js on line 4

### Expected Behavior
No Build Error

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.15
| react-native-web     | 0.1.12
| node             | 8.6.0
| npm    | 5.4.2

Sofware at https://github.com/eschablowski/morscout-client

**Comment by eschablowski** [comment]
Turns Out That this error triggers on the second import statement

**Comment by kelset** [comment]
1. you haven't respected the issue template, next time I'll close your issue right away
1. it's quite useless to write down your "current environment" if you don't specify versions, and you don't write which version of `react-native` and `react-navigation` you are using.
