### ISSUE TITLE
Not sure what .goBack('home') means and how it works

### ISSUE THREAD

**Issue by machadogj** [react-community/react-navigation#285]
I don't fully understand what this section of the documentation means:

```
Optionally provide a key, which specifies the route to go back from. By default, goBack will close the route that it is called from. If the goal is to go back anywhere, without specifying what is getting closed, call .goBack(null);
```

Here's what I am trying to do, I have the stack like this:
- home
- email
- credit-card

Notice that I am using REDUX! From inside the `credit-card` scene I am doing the following hoping it will "pop" both `credit-card` and `email` scenes to finally show the `home` screen:

```
navigation.goBack('home');
```

This is doing nothing, and the stack is not being altered in any way. How can I accomplish this? (I volunteer to enhance the documentation once I figure out how it works).

**Comment by machadogj** [comment]
I found the problem, the stack router is comparing by `key`, when according to the state I have in my app, it should be comparing by `routeName`:

```
      if (action.type === NavigationActions.BACK) {
        let backRouteIndex = null;
        if (action.key) {
          const backRoute = state.routes.find(route => route.key === action.key);
          backRouteIndex = state.routes.indexOf(backRoute);
        }
        if (backRouteIndex == null) {
          return StateUtils.pop(state);
        }
        if (backRouteIndex > 0) {
          return {
            ...state,
            routes: state.routes.slice(0, backRouteIndex),
            index: backRouteIndex - 1,
          };
        }
      }
```

https://github.com/react-community/react-navigation/blob/master/src/routers/StackRouter.js#L207

**Comment by machadogj** [comment]
When I changed the following to compare using `routeName`:

`const backRoute = state.routes.find(route => route.routeName === action.key);`

I can tell now that the functionality is poping all the scenes including the `routeName` one. I believe that we could really use a `goBackTo` that leaves the `routeName` in the stack (`backRouteIndex - 1`).

**Comment by aimak** [comment]
I had the same understanding of what the `goBack('Home')` should have done and I struggle with the same issue. 
However, I don't understand why this issue was closed. Is this fixed ? Is there a PR for this ?

**Comment by edo1493** [comment]
This is not clear to me too. Explicitly, I don't understand how to implement something like popN() or popToTop() from Navigator/NavigatorIOS.

**Comment by aimak** [comment]
What I understood from @machadogj's explanation and after a quick look at the code, the "bug" can easily be fixed : right now `goBack(screenKey)` takes the user to the screen before the screen with 'screenKey' as key. But it would be nice to give the screen name as parameter.

But I'm still not sure if the fix is something wanted by the Contributors or not. I tried to ping @machadogj several times but never succeeded :(

**Comment by edo1493** [comment]
I kinda understand that logic, but I was also wondering how to retrieve the screenkey of the route I want to go back to. I tried to look into the chrome debugger and it seems they are all randomly generated at runtime.

**Comment by edo1493** [comment]
I mean if I can do it by key, no biggie. Do you know how to retrieve the key of each screen/route? @aimak

**Comment by sunnylqm** [comment]
'key -> routeName' seems to be a forgotten change.
ping @skevy @grabbou @satya164 
P.S. This repo moves quite slowly, it's a hurry to make it a replacement for Navigator (and even you guys deprecated Navigator before 0.43 release!)

**Comment by jeffreymendez1993** [comment]
Agreed with the activity on the repo.

**Comment by janiokq** [comment]
I try to modify the code effect is reached But the return of animation Seems a little bit not normal


  if (action.type === NavigationActions.BACK) {
        
        let backRouteIndex = null;
        if (action.key) {
          /* $FlowFixMe */
          const backRoute = state.routes.find((route: *) => route.key === action.key);
          /* $FlowFixMe */
          backRouteIndex = state.routes.indexOf(backRoute);
        }
        if (backRouteIndex == null) {
          return StateUtils.pop(state);
        }

        if (state.routes.length >= 2 && backRouteIndex < state.routes.length ) {
          return {
            ...state,
            routes: state.routes.slice(0, backRouteIndex+1),
            index: backRouteIndex,
          };
        }
      }
      return state;
    },


I call

global.navigatorApp._navigation.goBack(global.navigatorApp.state.nav.routes[1].key);

![94463971-45c2-43c4-9251-f902403b2489](https://cloud.githubusercontent.com/assets/10770735/24392287/c6cefbac-13c5-11e7-8842-2069d96d9911.png)

I have 3 pages   1 2 3      I return from 3 to 1  But he carried out two times return to animation  3 to 2 to 1

**Comment by machadogj** [comment]
According to the roadmap this will not be used in core? [roadmap](https://github.com/facebook/react-native/wiki/Roadmap#core-libraries)

**Comment by alimek** [comment]
it also doesn't work for me when i try go back by Key. Why is this closed?

**Comment by mu1ex** [comment]
This works. But the api is a bit confusing.

Consider the following scenes on stack

A -> B -> C -> D

if you want to go to A from D you should do `navigation.goBack(keyOfB)` in D.
Its sort of confusing and would have been simpler if you could pop to the specified scene id.

**Comment by edo1493** [comment]
@mu1ex how do you retrieve the key of B from D?

**Comment by mu1ex** [comment]
@edo1493 You cant get the key of B from D. You should have retrieved it when you were at B and pass them as props when you're navigating. Or if you use redux save it there. Save `this.props.navigation.state.key` when you enter B and pass it as props to C & D and then use navigation.goBack() at D. Im not sure if this can be done in some other way. Its ugly though this way.

**Comment by maksim-harakhovich-itechart** [comment]
https://github.com/gorokhovich/react-navigation/tree/feature/goback-functionality
in this fork I added two features: goBack N screens and goBack to specific screen in stack.

**Comment by aimak** [comment]
@maksim-harakhovich-itechart can you make it a PR ?

**Comment by maksim-harakhovich-itechart** [comment]
@aimak will do it over weekends, need to take look on tests and docs

**Comment by alimek** [comment]
@maksim-harakhovich-itechart good work :) i am waiting for you fix then, fingers crossed

**Comment by aimak** [comment]
@maksim-harakhovich-itechart do you need any help on this ? :)

**Comment by janiokq** [comment]
Flicker can be solved @maksim-harakhovich-itechart

**Comment by maksim-harakhovich-itechart** [comment]
https://github.com/react-community/react-navigation/pull/905

**Comment by alimek** [comment]
Hmm any solution for flashing screen which @janiokq described when doing `.back({ key: 'A'})` from screen D? 
@maksim-harakhovich-itechart PR is `closed` :(

**Comment by ericvicenti** [comment]
There is a way to hack scenes reducer to avoid the flashing effect: only make the previously active scene as a stale scene, instead of keeping all stale scenes around.

**Comment by maksim-harakhovich-itechart** [comment]
Yes, a hack. I have it in my repo. But it sucks.
I can separate it into other branch and do PR. @ericvicenti @alimek

**Comment by ericvicenti** [comment]
I think it is not a hack if we assume that Transitioner is designed to only display one screen at a time

**Comment by maksim-harakhovich-itechart** [comment]
@ericvicenti alright :) Will do soon

**Comment by brucecodezone** [comment]
@mu1ex it works.
i have three screen A B C.
I get the screen key of A when at B screen.then i pass the screen key of A  to  C screen by params
`navigate('C',{screenKeyOfA:screenKeyOfA})`
finally,i get the screen key of A at C screen.Thank you very much!
sorry, my english is poor :)

**Comment by guoliang1206** [comment]
@alimek  , @janiokq hi guys, did u fixed the issue of flashing screen?

**Comment by peacechen** [comment]
The example in the documentation is at best misleading :
https://reactnavigation.org/docs/navigators/navigation-actions#Back

Instead of having 'Profile' in the example, it should be 'id-xxxxxxxx-#' to make it perfectly clear that it's referring to the [randomly] generated key and not the name of the route, which 'Profile' implies.

Overall this behavior is quite badly architected.  It would be much more convenient to specify the route name to go back from.  My guess is that the authors wanted to be able to handle duplicate routes on the stack such as A -> B -> A -> C.  IMHO that's an anti-pattern in routing and they should leave the handling of that to the few people who want that behavior.

**Comment by guoliang1206** [comment]
@peacechen   hi, if I goback from C to A , how can I avoid that screen B flashing in the middle?

**Comment by ColCh** [comment]
@guoliang1206  what about call `reset` ? https://reactnavigation.org/docs/navigators/navigation-actions#Reset

**Comment by peacechen** [comment]
@guoliang1206   On a stack with A -> B -> C, I don't see B flash when going back from C to A on iOS.  Are you by chance running on Android?

**Comment by guoliang1206** [comment]
@peacechen @ColCh  In fact, my route stack like this 

`Main:TabNavigator `
and route in Main ：
```
TabA  -> ScreenA1 ->ScreenA2
TabB
TabC
```
Now I need back to TabA from ScreenA2, but ScreenA1 will flashing , it is appear at iOS .

And I try like this in ScreenA2:
```
 let navigateAction = NavigationActions.back({
            key:"TabA",    
        });
        this.props.navigation.dispatch(navigateAction);
```
the key of TabA I have saw is "TabA",  and I have also try this 2 : 
```
 this.props.navigation.state.params.key,    key of ScreenA1 passed by  'params.key'
 this.props.navigation.state.key,    key of ScreenA2 
```
Nope.

And I have try like this:
```
let  navigateAction =  NavigationActions.reset({
            index: 0,
            actions: [
                NavigationActions.navigate({ routeName: 'Jobs'})  //or routeName:'Main'
            ]
        });
        this.props.navigation.dispatch(navigateAction);
```
Nope.

So guys, can you show me the simple code ,how to handle this? back to root and no flashing of middle screen.

**Comment by purplepeng** [comment]
@mu1ex Did you have find a better way to get screen key of B when in screen D?

**Comment by ranran2** [comment]
@mu1ex  i met a problem the same with you ,i have a stacks include A,B,C,D;  i navigate from A to D one by one;  if i  want to goBack to A from D, i  need to do `navigation.goBack(keyOfB)`. 
Have you understood why  it  act like this, i annoy with this for  hours. 
Looking forward to your answer.

**Comment by ColCh** [comment]
@guoliang1206 this is somewhat harder

with your snippet

```
// TabA  -> ScreenA1 ->ScreenA2

let navigateAction = NavigationActions.back({
            key:"TabA",    
        });
```

so you want transition from `ScreenA2` to `TabA` 

The key passed to `goBack` should be key of `ScreenA1`

key of "TabA" is not right, because argument for `goBack` is a route key **go back from**, and it can't go back from first route in stack.

I'm using approach with `key of ScreenA1 passed by  'params.key'`. I wonder if there is better solution for this

**Comment by ranran2** [comment]
@ColCh your answer solve my confuse perfectly.thanks

**Comment by guoliang1206** [comment]
@ColCh  it was my mistake , 
```
 const MainScreen = TabNavigator({
    Jobs: {screen: Jobs},
    Message: {screen: MessageList},
    InfoCenter: {screen: InfoScreen},
    Setting: {screen: Setting},
});
```
and  StackNavigator 
```
StackNavigator({

    Login:{ screen:LoginScreen},
    Main: { screen: MainScreen },
    ScreenA:{ screen: ScreenA},
    ScreenB:{ screen:ScreenB},
    ScreenC:{ screen:ScreenC}
})
```
And the stack like this: Jobs ->ScreenA->ScreenB->ScreenC , and I need back to jobs from C

**Comment by ColCh** [comment]
@ranran2 You're welcome. I just not understand why react-native has deprecated `Navigator` component in favor by react-navigation. It has much less features than deprecated component.

@guoliang1206 I have same thing in my app. Finally, I'm passing key of `ScreenA` route through `ScreenB` to `ScreenC` with params. Then, in `ScreenC` call of `navigation.goBack(keyOf_ScreenA)` will go back to `Jobs` screen.

It looks like this:

```
// Jobs
this.props.navigation.navigate('ScreenA');
```

```
// ScreenA
this.props.navigation.navigate('ScreenB', { screenAKey: this.props.navigation.state.key, });
```
```
// ScreenB
this.props.navigation.navigate('ScreenC', { screenAKey: this.props.navigation.state.params.screenAKey, });
```
```
// ScreenC
this.props.navigation.goBack(this.props.navigation.state.params.screenAKey);
```

I really don't know if this is right solution for this, or `reset` action should be used here

**Comment by ColCh** [comment]
Or may be use some function in route params?? 

`Jobs ->ScreenA->ScreenB->ScreenC`

```
// Jobs
this.props.navigation.navigate('ScreenA');
```

```
// ScreenA
const goBackToJobs = () => this.props.navigation.goBack(this.props.navigation.state.key);
this.props.navigation.navigate('ScreenB', { goBackToJobs, });
```
```
// ScreenB
this.props.navigation.navigate('ScreenC', { goBackToJobs: this.props.navigation.state.params.goBackToJobs, });
```
```
// ScreenC
this.props.navigation.state.params.goBackToJobs();
```

At least this looks much more neat :D

**Comment by guoliang1206** [comment]
@ColCh  I could back to Jobs from ScreenC like your ways, but ScreenB will flashing . see at above likes janiokq 's issue.

**Comment by ColCh** [comment]
@guoliang1206 Ah, sorry. Now I understand the issue. Yeah it seems that `reset` action should be used in this case

**Comment by guoliang1206** [comment]
Jobs is the subtab in TabNavigator ,and I go to ScreenC from Jobs, Jobs -> A->B->C ,now I need back to Jobs from C, so if use reset function , is  the destination route should be set "Jobs"?

**Comment by ranran2** [comment]
@ColCh  the Navigator is influent  and doesn't fit between  the two platform. react-navigaton fix this and  is more fluent. it have advantages in the data transfer,tab and so on.it also support redux.  Totally,it's powerful though it need us spare some time to learn it.

**Comment by ranran2** [comment]
@guoliang1206 this is the document ,[https://reactnavigation.org/docs/navigators/navigation-actions#Reset](url)   it have a nice example to reset.

**Comment by alimek** [comment]
@ranran2 @guoliang1206  I couldn't fix this issue too using `reset` action :( so @ranran2 maybe you can share you code to show how you fix this issue using `reset`?

**Comment by ranran2** [comment]
![image](https://user-images.githubusercontent.com/17609120/28456293-711dcc46-6e34-11e7-9d3b-37681e35f07a.png)
in your code ,the routeName should be 'Jobs'

**Comment by guoliang1206** [comment]
@aimak In fact, I have tried use 

Back 
```
 let navigateAction = NavigationActions.back({
             key:"Jobs",
});
  this.props.navigation.dispatch(navigateAction);
```
Reset
```
 let navigateAction = NavigationActions.reset({
      index: 0,
     actions: [
     NavigationActions.navigate({ routeName: 'Main'})]   //and also try routeName: 'Jobs'
});
  this.props.navigation.dispatch(navigateAction);
```
.goBack();
```
this.props.navigation.goBack({key:'Jobs'});  //also tried key:'Main' ,  {numberOfPages:2}
```

All of these ways can not solve my problem.

**Comment by ranran2** [comment]
@guoliang1206 Does   your problem is when your reset, the screen between will flash??   if is, now the only way to solve this is to forbid the animation.

**Comment by ColCh** [comment]
@guoliang1206 can you provide minimal launchable example?  On https://expo.io/ or something

**Comment by guoliang1206** [comment]
![2017-07-21 16_58_39](https://user-images.githubusercontent.com/12846676/28456738-e2eecd7e-6e35-11e7-8b72-1468f32a8729.gif)

**Comment by ranran2** [comment]
@guoliang1206  i met this flash before, and the best way  i  found  is to  forbid the animation  when you reset .

**Comment by peacechen** [comment]
@guoliang1206 
Be sure to use the route's key (e.g. 'id-xxxxxxxx-#') and not its routeName parameter (in your case ScreenA1).  This underscores the need to fix the documentation.

**Comment by guoliang1206** [comment]
@peacechen  The screen in the Tab, key of that is "ScreenName",
![2017-07-24 9 07 11](https://user-images.githubusercontent.com/12846676/28504810-80e99e4e-704f-11e7-933a-bb1accc1d4fc.png)
And then I push subScreens from this screen which in the tab. Now I need back to this tab screen, should I use what key ?

**Comment by yaronlevi** [comment]
Hope the next release will include something like goBack(2) and goBack('routeName')

**Comment by nwkeeley** [comment]
@guoliang1206  did you find a solution? I tried all the items you've tried

**Comment by guoliang1206** [comment]
@nwkeeley no, I didn't find a perfect solution, now I only forbid the animation when it pop to rootView

**Comment by voidstarfire** [comment]
Any solution for this? It's preventing my app from passing quality assurance.

Should be as simple as goBack('nameofscreen') but that produces flashing and doesn't work half of the time.

**Comment by santhosh77h** [comment]
if our scrrens are like A - B - C - D

if we want to go back to A from D we need to store the key of B like this 

`navigator.navigate('Scrren',{screenKey:navigation.state.key})` 

so in all the screen we can access `screenKey` using `navigation.state.params.screenKey`and while we are in the screen D to go back to A 

`navigation.goBack(navigation.state.params.screenKey)`

Now we are in scrrenn A and B - C - D are removed from stack

**Comment by jaywuYJ** [comment]
I tried the solution provided by santhosh77h and it worked, and be aware that we need to pass down the target screen's screenKey as the navigation parameter along the navigation chain so that the last screen in the chain would be able to get the target screen's screenKey.

**Comment by laizhenhai88** [comment]
the goBack api has no problem, think about this situation:
register need 3 steps from Home, so the stack like this:
`Home - p1 - p2 - p3`
when we in p3(sometimes the success page), we need close p3, pop p2,p1 and go back to Home, so call goBack(key of p1) in p3 is ok
but, maybe you like call goBack('Home') in p3
if there is another way to start register, such as pay screen, so the stack maybe like this:
`Home - some product - pay - p1 - p2 - p3`
so, we can't  call goBack('Home') in p3, but call goBack(key of p1) in p3 is still ok !
now, the problem is how to store the key of p1, just write your store code in p1
`navigator.navigate('Scrren',{screenKey:navigation.state.key})`
and call `navigation.goBack(navigation.state.params.screenKey)` in p3
because the store code in p1 means we will start a progress (p1-p2-p3), and the key of p1 is the start point, when you want to finish this progress, call goBack(progress start point)

**Comment by shripada** [comment]
To clarify @santhosh77h  answer,  we need to ensure, we propagate the key of screen 'B' (I am referring to the case @santhosh77h is referring), to screen C, and to Screen D. 

```
//Navigate from B -> C  in B
const key = this.props.navigation.state.key;
this.props.navigation.navigate("C", {screenBKey:key});

//Navigate from C -> D in C  (params now contain a key screenBKey, just pass it down)
this.props.navigation.navigate("D", this.props.navigation.state.params)

//Now to go back from D to B in D.
this.props.navigation.goBack(this.props.navigation.state.params.screenBKey);
```

**Comment by ChauVV** [comment]
A->B->C->D(Cureent)

just   `navigation.navigate('B')`
