### ISSUE TITLE
StatusBar Issues with dispatch(resetAction)

### ISSUE THREAD

**Issue by URvesh109** [react-community/react-navigation#2851]
When ever i dispatch reset action, I get the respective screen. But if i go background from that screen and resume that page. The statusbar component does not work

**Comment by kelset** [comment]
Closing because you haven't followed the issue template.
Without that information is nearly impossible to understand & investigate the issue.

**Comment by est7** [comment]
@URvesh109 i have the same issue ,did you solve it ?

**Comment by URvesh109** [comment]
Use outside of component of main component like

StatusBar.setBackground('your fav color');
StatusBar.setBarStyle('light or dark')
