### ISSUE TITLE
Navigation prop not passed to navigable components.

### ISSUE THREAD

**Issue by rscharfer** [react-community/react-navigation#2852]
### Current Behavior
[Link to respository](https://github.com/rscharfer/mobileflashcards/tree/a01649ed379bf07f22fea923b644930c25dfd8f1) : 

When the Button component is pressed on the first screen (DeckListView), the user should be able to navigate to the NewDeckView, because both views are part of the StackNavigator() call.  Instead the error "undefined is not an object (evaluating '_this3.props.navigation.navigate')" pops up.  Using console.log tests I see the props object passed to the DeckListView component is empty,  So is seems the cause of the error is that the navigation property is not being passed to the component, but why not?

### Expected Behavior
- I expected the components listed as screens in the call to StackNavigator() to receive the navigation prop and I expected to be able to call navigate() on the prop to allow my user to navigate to a new screen.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | v 1.0.0-beta.15
| react-native     | v0.48.4
| node             | v6.11.0
| yarn   |v1.2.1

**Comment by kelset** [comment]
Well from my understanding in your `App.js` you are not rendering the `Stack` but instead `return <DeckListView/>`.
Change that to return the Stack and it will work.

Not an issue caused by the library.

**Comment by rscharfer** [comment]
@kelset Thank you!  Somehow this wasn't clear for me in the documentation.  At least it wasn't clear in Quick Start.

**Comment by kelset** [comment]
I am a bit confused, aren't you following a tutorial? Your repo says "This is the third project of the udacity React Nanodegree.".

That said feel free to submit a PR if you think that the wording in the Quick Start isn't clear enough.
