### ISSUE TITLE
StackNavigator crashing on Android with 1.0.0-beta.16

### ISSUE THREAD

**Issue by richeterre** [react-community/react-navigation#2853]
### Current Behavior
1. Create a blank RN project using `react-native init`
1. Add a dead-simple `StackNavigator`:

```
const DemoNavigator = StackNavigator({
  Blank: { screen: () => <Text>Blank</Text> }
})

export default class App extends Component<{}> {
  render() {
    return (
      <DemoNavigator  />
    );
  }
}
```

1. Run project on **Android** (I'm using an API level 23 emulator)

Result:

![screenshot_1509481707](https://user-images.githubusercontent.com/555663/32247896-28337634-be84-11e7-9f7e-4e1e540f3813.png)

### Expected Behavior

The app should render a `StackNavigator` with a screen containing the text "Blank". On iOS this works as expected.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 0.49.5
| react-native     | 1.0.0-beta.16
| node             | 8.8.1
| npm or yarn      | yarn 1.2.1

**Comment by kelset** [comment]
Thanks for reporting, we'll look into it asap.

**Comment by spencercarli** [comment]
Interesting - can't reproduce on Android https://snack.expo.io/B1pzVPURZ

**Comment by richeterre** [comment]
I'm running it on a Nexus 5X emulator with API level 23. Not super familiar with Expo tbh, but I wonder if the behavior can differ between Expo and `react-native init`?

**Comment by matthamil** [comment]
I can reproduce with `react-native init`

**Comment by spencercarli** [comment]
Yeah must be a discrepancy between expo and react native

**Comment by spencercarli** [comment]
It's due to the JSC version on Android (Expo specifies a higher one, which is why we didn't see that error before). If you turn on remote debugging on Android the app will render.

Still trying to figure out why this occurs and how to fix it.

**Comment by huangbong** [comment]
Getting the exact same error. Nexus 5X real device, API level 25.

```
"react": "^16.0.0-beta.5",
"react-native": "^0.49.5",
```

**Comment by huangbong** [comment]
Did some debugging, realized componentWillMount of one of my components was firing before I wanted it to and I forced a state check now the error is gone.

**Comment by allmaxgit** [comment]
@huangbong 
For fix you can change react-navigation dependency in `package.json`:
```
"react-navigation": "git+https://github.com/react-community/react-navigation.git#ed2fc9a09e2f562ae9d3fc7f5df17c593989db0a",
```
for directly install react-navigation from this repository with commit where it bug fixed and run `yarn`.

**Comment by huangbong** [comment]
@allmaxgit works perfect now. Thanks!

**Comment by h0rac** [comment]
dave solution works with editing src/views/SafeAreaView.js

**Comment by johngoren** [comment]
I don't know if I should open up a separate issue for this, but I found that under beta.16, my stack developed an unsightly white gap over the toolbar that went away when I rolled back to beta.15.

**Comment by clickclickonsal** [comment]
@johngoren I've experienced that issue with beta.15
I'm pointing to the version @allmaxgit pointed out because that fixes the original issue. In using that version, that as well fixes that weird white gap over the toolbar in beta.15.
![image](https://user-images.githubusercontent.com/8260678/32342726-c10f6fc6-bfd7-11e7-93d5-110b9db11dcc.png)

**Comment by kelset** [comment]
@johngoren @clickclickonsal yeah we already fixed the header issue, I suggest you point to master if you have the necessity to be on `beta.16`. But we are going to do a new release soon 💪

**Comment by kelset** [comment]
Quick update: we released ´beta.17´, @richeterre can you please update and close this issue if it's fixed?

**Comment by richeterre** [comment]
It's a fix! Thank you for the quick response, and keep up the good work ❤️
