### ISSUE TITLE
StackNavigator header color not visible beneath status bar in 1.0.0-beta.16

### ISSUE THREAD

**Issue by richeterre** [react-community/react-navigation#2854]
### Current Behavior

On iOS, the header background color of a `StackNavigator` no longer extends underneath the status bar.

Example: https://snack.expo.io/B1fqtvUAZ (the status bar appears in white above the red header)

### Expected Behavior

The header background stretches all the way to the top of the screen as in `1.0.0-beta.15`, underlaying the status bar. Alternatively, if this is the new desired behavior (I guess related to iPhone X somehow?), it should be listed as a breaking change.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.16
| react-native     | 0.49.5
| node             | 8.8.1
| npm or yarn      | yarn 1.2.1

**Comment by spencercarli** [comment]
cc @davepack

**Comment by spencercarli** [comment]
I'm guessing it's the `top: 'always'` [here](https://github.com/react-community/react-navigation/blob/master/src/views/Header/Header.js#L317).

**Comment by davepack** [comment]
It's because headerStyles aren't being applied to the SafeAreaView. BackgroundColor is the only thing that needs to be applied to the SafeAreaView instead of the nested View that all other styles are applied to.

**Comment by davepack** [comment]
I'll figure that out. Thanks.

**Comment by wellyshen** [comment]
I have the same issue +1

**Comment by outaTiME** [comment]
Yup, here visual comparison side by side, by the moment I left de beta15:

![group](https://user-images.githubusercontent.com/140472/32290869-297e0586-bf1a-11e7-8905-74d02e75bb9c.png)

**Comment by allmaxgit** [comment]
It possible to pass image in status bar instead headerBackgroundColor?

**Comment by theohdv** [comment]
@kelset I'm pointing at master but still have this issue (emulator Iphone 6, iOS 11.1). Is there a new property to set or it is a bug ?

**Comment by kelset** [comment]
Uhm weird. Keep an eye on #2875 for updates, we are working on a PR for that that should fix this fully.

**Comment by outaTiME** [comment]
Hi guys, I update to beta.17 header issue solved but still extra padding on DrawerItems component.

In beta.15 doesn't exist, take a look the following image:

![group 2](https://user-images.githubusercontent.com/140472/32360358-cc1e2ad6-c033-11e7-8b6e-ff2ed2283a1b.png)

thanks !!!

**Comment by outaTiME** [comment]
Probably something related with this line:

https://github.com/react-community/react-navigation/blob/master/src/views/SafeAreaView.js#L288

**Comment by davepack** [comment]
Hey @outaTiME, sorry for the confusion there. #2872 added `itemsContainerForceInset` to `contentOptions` (see https://reactnavigation.org/docs/navigators/drawer#contentOptions-for-DrawerItems). In your case you will want to have: 

``` JavaScript
contentOptions: {
  itemsContainerForceInset: { top: 'never', horizontal: 'never' },
}
```

This will override the default `forceInset` on the SafeAreaView that wraps each drawer item. It's not ideal, it's one of the tradeoffs of having a JS only solution and have iPhone X support asap, but it will be resolved soon when this is ported to native.

**Comment by outaTiME** [comment]
Hi @davepack, awesome the `itemsContainerForceInset` works as expected, thanks !!!

**Comment by manjeets12** [comment]
In my case SafeAreaView adding some extra padding at the top of header and bottom of tabs, my react-navigation version is 1.0.0-beta.19 and RN is 0.50.0, any hint to resolve this?
![simulator screen shot - iphone x - 2017-12-14 at 18 47 13](https://user-images.githubusercontent.com/17762875/33994413-6717f854-e100-11e7-9606-46ef305ce8d6.png)
![simulator screen shot - iphone x - 2017-12-14 at 18 46 51](https://user-images.githubusercontent.com/17762875/33994439-79d06292-e100-11e7-9a80-38401e24d9ef.png)

**Comment by AdamDiament** [comment]
> In my case SafeAreaView adding some extra padding at the top of header and bottom of tabs, my react-navigation version is 1.0.0-beta.19 and RN is 0.50.0, any hint to resolve this?
> ![simulator screen shot - iphone x - 2017-12-14 at 18 47 13](https://user-images.githubusercontent.com/17762875/33994413-6717f854-e100-11e7-9606-46ef305ce8d6.png)
> ![simulator screen shot - iphone x - 2017-12-14 at 18 46 51](https://user-images.githubusercontent.com/17762875/33994439-79d06292-e100-11e7-9a80-38401e24d9ef.png)

did you ever get a fix for this?
