### ISSUE TITLE
TabBarBottom/Header internal SafeAreaView padding backgroundColor cannot be changed in 1.0.0-beta.16

### ISSUE THREAD

**Issue by paulpopiel** [react-community/react-navigation#2857]
https://github.com/react-community/react-navigation/blob/473192176238c8dd8bcd2f629f13683f533b8a15/src/views/TabView/TabBarBottom.js#L183

The root SafeAreaView for the TabBarBottom render method has its style hardcoded to an internal style with a default background color. The subsequent padding (in iPhoneX) will therefore always have this default background color (F7F7F7).
This is regardless of any backgroundColor set on the TabBarBottom style prop, or likewise tabBarOptions style set in TabNavigator.

EDIT: 
Same issue in Header.js
https://github.com/react-community/react-navigation/blob/473192176238c8dd8bcd2f629f13683f533b8a15/src/views/Header/Header.js#L316

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.16
| react-native     | 0.49.3
| node             | 8.4.0
| npm or yarn      | 0.27.5

**Comment by gaodeng** [comment]
same issue +1.

**Comment by wellyshen** [comment]
Same issue +1

**Comment by kelset** [comment]
Thanks for reporting guys, we'll look into this ASAP.
