### ISSUE TITLE
headerStyle: {elevation:0} no longer works after updating to beta 16

### ISSUE THREAD

**Issue by jslok** [react-community/react-navigation#2858]
On <= beta 15, I could use elevation:0 in headerStyle for stack navigator to get rid of the shadow below the header. On beta 16, this no longer works.
![screenshot_20171031-221351](https://user-images.githubusercontent.com/22921326/32261157-f1015694-be89-11e7-81c3-a170e35b2eb3.png)
![screenshot_20171031-221046](https://user-images.githubusercontent.com/22921326/32261158-f12d2bb6-be89-11e7-889d-c497bfc939d7.png)

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0 beta 16
| react-native     | 0.49.5

**Comment by paulpopiel** [comment]
+1

**Comment by kelset** [comment]
Duplicate, closing in favor of #2857
