### ISSUE TITLE
Platform.OS throws a TypeError when used with tabBarOptions

### ISSUE THREAD

**Issue by himanshug16** [react-community/react-navigation#2859]
![screenshot_1509517011](https://user-images.githubusercontent.com/32382466/32262394-627fea04-befa-11e7-917b-3c0210f0c293.png)

Getting this TypeError issue as shown above when tried to add Platform.OS in TabBarOptions

Code for the Navigation is as follows: -
         tabBarOptions: {
           inactiveTintColor: 'rgb(148,147,147)',
          activeTintColor: '#e91e63',
         justifyContent: 'center',
        showIcon: true,
        flexDirection: 'row',
        labelStyle: (Platform.OS === 'android') ? { fontSize: 7 } : { fontSize: 10 },
       tabStyle: (Platform.OS === 'android') ? { height: 50 } : { height: 0 },
       style: {
        backgroundColor: 'rgb(247,247,247)',
       },
   },

**Comment by vonovak** [comment]
how do you import `Platform`?

**Comment by himanshug16** [comment]
Used the following import statement:-

        import { Platform } from 'react-native';

**Comment by kelset** [comment]
Please provide the full code for App.js or a repo that reproduces the issue.

**Comment by himanshug16** [comment]
Found the solution,The import statement was not properly collobrated on the navigator page. Thanks hence closing the issue
