### ISSUE TITLE
undefined is not a function (evaluating 'reactAPIs[typeof Symbol ==='function'? Symbol.iterator: '@@iterator']()') react-native

### ISSUE THREAD

**Issue by TheIdhem** [react-community/react-navigation#2862]
undefined is not a function (evaluating 'reactAPIs[typeof Symbol ==='function'? Symbol.iterator: '@@iterator']()') react-native
is there any body know how can i solve this problem?

**Comment by kelset** [comment]
Duplicate #2853. Read the comments there for a workaround until new version is released

**Comment by TheIdhem** [comment]
@kelset 
i tried that solution but it wasn't worked

**Comment by sh-soltanpour** [comment]
I tried using "react-navigation": "1.0.0-beta.15" instead of "react-navigation": "^1.0.0-beta.15" and it worked. Just remove the '^' symbol.

**Comment by TheIdhem** [comment]
@sh-soltanpour 
it worked!!
tnQ so much for your refers!!

**Comment by humlk** [comment]
use react-navigation@1.0.0-beta.15
or 
modify:  node_modules/react-navigation/src/views/SafeAreaView.js [ line 190 ]
old code is :   const [firstLtr] = key;
new code is :  const firstLtr = key;
then run
npm start -- --reset-cache

or
wait the new version.

**Comment by jackqqxu** [comment]
downgrade to react-navigation@1.0.0-beta.15, do not use react-navigation@1.0.0-beta.16
