### ISSUE TITLE
Navigation crashing on Android with 1.0.0-beta.16

### ISSUE THREAD

**Issue by theohdv** [react-community/react-navigation#2863]
### Current Behavior

My navigation structure look like this:

root (stackNavigator):
-> screen 1
-> screen 2
-> screen 3
-> screen 4 (drawerNavigator):
--------->screen 5 (stackNavigator):
-----------------> screen 6
-----------------> screen 7

The bug is when i try to do a reset navigation action from my screen 3 to my screen 4 (**Only on Android**).
This is the code i used to reset:

```javascript
this.setState({ load_modal_open: false }, () => {                                                                                 		
        const resetAction = NavigationActions.reset({
			index: 0,
			actions: [
				NavigationActions.navigate({
						routeName: "screen 4",
				})
			]
	});
	this.props.navigation.dispatch(resetAction);
});
```
I get this error:

![screenshot_1509534439](https://user-images.githubusercontent.com/26060802/32272296-6adfffe0-bef5-11e7-87d0-e62e7be838f6.png)

### Expected Behavior
No error using react-navigation 1.0.0-beta.15.
It  should reset to my screen 4.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.16
| react-native     | 0.48.4
| node             | 8.7.0
| npm or yarn      | 5.5.1

**Comment by kelset** [comment]
Probably related to #2853. Can you trying pointing at master to see if the commit we already pushed fixes your issue?
We'll release a new update soon, hold tight until then.

**Comment by theohdv** [comment]
Yes master fixes it, thanks for your reactivity!
