### ISSUE TITLE
Navigation crashing on iOS & Android with 1.0.0-beta.16

### ISSUE THREAD

**Issue by theohdv** [react-community/react-navigation#2864]
### Current Behavior

Error: **"InputRange must be monotonically increasing 0,1.5,2,1.5,3"**

My navigation structure look like this:

root (stackNavigator):
-> screen 1
-> screen 2
-> screen 3
-> screen 4 (drawerNavigator):
--------->screen 5 (stackNavigator):
-----------------> screen 6
-----------------> screen 7
-----------------> screen 8
-----------------> screen 9

this happens not every time, it happens only when when i follow this navigation:

screen 3 -> reset -> screen 4 ( screen 6 is displaying) --> navigate --> screen 7 --> navigate --> screen 8 --> try to reset to screen 6 --> **ERROR**

But it if do not go directly to screen 8 and I navigate in my app before this error disappear and everything is working fine.

I get this error:
![simulator screen shot - iphone 6 - 2017-11-01 at 10 59 54](https://user-images.githubusercontent.com/26060802/32272806-ada64a26-bef7-11e7-9cb5-99cf852ad37f.png)

### Expected Behavior

Should reset to screen 6.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.16
| react-native     | 0.48.4
| node             | 8.7.0
| npm or yarn      | 5.5.1

**Comment by kelset** [comment]
Same question as the last issue, does it still happen with master?

**Comment by theohdv** [comment]
Yes it still happens, I've tried before submitting the issue this time.

**Comment by kelset** [comment]
Ok perfect, sorry it wasn't clear in the issue. Thanks for letting us know, we'll look into this.

**Comment by theohdv** [comment]
No it was working well on beta.15

**Comment by vonovak** [comment]
@theohdv could you create a minimal reproduction on expo snack?

**Comment by theohdv** [comment]
Here is the link: https://snack.expo.io/Bk8_cUDCb 

Reproduction seems to work on Android & iOS (may you'll need to do it few times).

**Comment by 94cstyles** [comment]
Sorry, I submitted the PR without a rigorous test. 
#2873 The problem has been fixed.

**Comment by kelset** [comment]
@theohdv can you test & confirm that with that PR the issue would be fixed?

**Comment by theohdv** [comment]
Tested and the issue seems to be fixed! thanks for the PR 👍

**Comment by kelset** [comment]
Merged! Now if you point at master it should work 👌
We'll probably do a new release soon :)
