### ISSUE TITLE
Header style is not configurable anymore

### ISSUE THREAD

**Issue by bunea** [react-community/react-navigation#2865]
### Current Behavior
Since #2833 elevation and bottom border styles cannot be changed anymore. The problem is [here](https://github.com/react-community/react-navigation/pull/2833/files#diff-7d1ace708bab0c8203594be64846ebecR316) because the default style and user style aren't merged anymore.

### Expected Behavior
Should be able to customize them.

**Comment by kelset** [comment]
Duplicate #2854
