### ISSUE TITLE
Header color is no longer overridable

### ISSUE THREAD

**Issue by rmevans9** [react-community/react-navigation#2868]
### Current Behavior
If you pass a `headerStyle` in on a `StackNavigator` that contains a `backgroundColor` prop it is no longer taking up the entire `Header`. 

Snack Example: https://snack.expo.io/HJdcOPvCW

### Expected Behavior
The background color provided via the `headerStyle` should be used instead of the default color for the entire `Header`

Possible Solution:
With the new `SafeAreaView` the container structure changed a bit which changed how styles work. As you can see here https://github.com/react-community/react-navigation/blob/master/src/views/Header/Header.js#L307 `headerStyle` is still being put in but that style gets added to the `View` nested in the `SafeAreaView`. The `SafeAreaView` style (which is not configurable at all) contains the background color now. I would recommend either making the `SafeAreaView` style overridable or moving the `headerStyle` to override the `SafeAreaView`s style instead

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.16
| react-native     | 0.48.4
| node             |  4.2.0
| npm or yarn      | yarn

**Comment by kelset** [comment]
Duplicate #2854
