### ISSUE TITLE
Header elevation styling to remove shadow does not work in beta16

### ISSUE THREAD

**Issue by paulpopiel** [react-community/react-navigation#2875]
### Current Behavior
Issue first raised in:
https://github.com/react-community/react-navigation/issues/2858

Subsequently, along with other raised issues, all got logged under:
https://github.com/react-community/react-navigation/issues/2854

Which led to the following PR:
https://github.com/react-community/react-navigation/pull/2871

The PR addressed the background color issues, but not the elevation styling on the header.

### Expected Behavior

Should be able to set elevation in:
- the headerStyle of nevigationOptions
- tabBarOptions.style (for TabNavigators)

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.16
| react-native     | 0.49.3
| node             | 8.4.0
| npm or yarn      | 0.27.5

**Comment by kelset** [comment]
Well, we are doing the best we can to address all these issues as fast as we can. So hold tight, a new release will come out soon.

But ofc, if you can't wait for, a PR will be surely welcome, and we'll review it asap.

**Comment by davepack** [comment]
@paulpopiel can you see if #2889 fixes this?
