### ISSUE TITLE
Not able to push screen from bottom in a nested stack navigator?

### ISSUE THREAD

**Issue by jinxac** [react-community/react-navigation#2881]
### Current Behavior
I have an application in which I have login screen which redirects upon successful sign in redirect to dashboard. On dashboard I have list of cards which upon clicking navigate me to detail screen of the card. I wanted this detail screen to be pushed from bottom but this is not working in case this navigator is nested.

Here is a code for my navigation:-
```

const mapNavigationStateParamsToProps = (SomeComponent) => {
  return class extends React.Component {
    static navigationOptions = SomeComponent.navigationOptions; // better use hoist-non-react-statics
    render () {
      const {navigation: {state: {params}}} = this.props;
      return <SomeComponent {...params} {...this.props} />;
    }
  };
};

const GoalStack = StackNavigator (
  {
    GoalDetail: {
      screen: mapNavigationStateParamsToProps(GoalDetail)
    },
   /** Other Routes*//
  },
  {
    headerMode: "none",
    mode: "modal"
  }
);

const MainNavigation = StackNavigator({
  /** Other Routes**/
  Goal: {
    screen: GoalStack
  },
 /** Other Routes**/
}, {
  headerMode: "none"
});

```
I want `GoalDetail` component to slide up from bottom and not the entire stack. I was using Navigator earlier in my application and it was pretty easy to specify the direction with each route. I am not sure if I am missing something here. 

### Expected Behavior

If I have an application in which I want few screens to navigate horizontally (mode: card) and few screens to navigate vertically(mode: modal) it should be allowed ( Also inside nested stacks)

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^1.0.0-beta.15
| react-native     | 0.47.2
| node             | v8.2.1
| npm or yarn      | 5.3.0

**Comment by kelset** [comment]
Duplicate: #1290 - there's a PR that will provide this feature #2308

**Comment by jinxac** [comment]
Thanks @kelset looking forward to it  👍
