### ISSUE TITLE
20 paddingTop in header

### ISSUE THREAD

**Issue by amestsantim** [react-community/react-navigation#2885]
### Current Behavior
A gap (paddingTop: 20) appears just above the header when using StackNavigator. It appears between the statusbar and the header. The cause is a paddingTop: 20 style applied to SafeAreaView and can be seen in the Inspector of the react native debug tool. It only appears in portrait mode and not in landscape. I was testing on Android 5.1.1 (a nexus 7 tablet)

### Expected Behavior
There should be no paddingTop: 20

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.15
| react-native     | 0.49.5
| node             | 8.6.0
| npm or yarn      | 5.5.1

**Comment by kelset** [comment]
I guess you mean you are using `beta.16` ;)

Anyway this issue is a duplicate of https://github.com/react-community/react-navigation/issues/2854, we have already fixed it on master and we'll release a new version soon. In the meantime, by pointing at master you should not see this issue.

**Comment by amestsantim** [comment]
Ok, thanks!

**Comment by theohdv** [comment]
@kelset I'm pointing at master but still have this issue (emulator Iphone 6, iOS 11.1). Is there a new property to set or it is a bug ?
