### ISSUE TITLE
TabBarBottom changing height during renders on screen mount

### ISSUE THREAD

**Issue by danieljvdm** [react-community/react-navigation#2888]
### Current Behavior
TabBarBottom initially has a larger height than expected, as shown by the first screenshot. After a second it corrects to the second screenshot. Happens on iPhone X as well as other iPhone devices.

![simulator screen shot - iphone x - 2017-11-02 at 14 50 52](https://user-images.githubusercontent.com/3450486/32345303-2a14534e-bfe0-11e7-8b51-a88bab49d1ff.png)
![simulator screen shot - iphone x - 2017-11-02 at 14 50 53](https://user-images.githubusercontent.com/3450486/32345304-2a21af62-bfe0-11e7-9187-1931dbc0556a.png)

### Expected Behavior
Expect no change of height during render

### Your Environment

Tested on both beta 16 and latest master (f899b2eb13a48e7f84250f2e6f59ef2e5a5b9085).
Tested on iPhone X simulator and iPhone 8 simulator
React Native 0.49.3

**Comment by davepack** [comment]
can you link to #2889 and see if this fixes the issue?
