### ISSUE TITLE
Navigators vs Routers

### ISSUE THREAD

**Issue by jpshelley** [react-community/react-navigation#289]
Not so much an issue but a question. I assume navigators and routers are somewhat mutually exclusive. If this is true when would one chose an option over the other?

This might be beneficial to add to the docs and I can submit a PR if a response is given.

Also sorry if this is a better StackOverflow post, but want to update the docs so others know as well.

**Comment by satya164** [comment]
Routers contain the routing logic. Navigators are routers + views.

**Comment by jpshelley** [comment]
So Basically you are always using a Navigator? And Routers are just an object that the Navigators contains to handle the routing logic? If so we can delete this issue.

**Comment by shawngustaw** [comment]
A navigator HAS a router see: https://github.com/react-community/react-navigation/blob/master/src/navigators/createNavigator.js#L19
