### ISSUE TITLE
how can i Create 2 separate navigators with different route configs?

### ISSUE THREAD

**Issue by derakhshanfar** [react-community/react-navigation#2893]
hi guys
 i have two roles in my app:
admin and reqular

```
const ADMIN_ROUTES = {
  home: { screen: HomeNavigator },
  listings: { screen: ListingsNavigator }, // admin only screen/tab
  account: { screen: AccountNavigator }
};

const REGULAR_ROUTES = {
  home: { screen: HomeNavigator },
  buildingList: { screen: buildingListNavigator }
};
 
```

ADMIN_ROUTES  and REGULAR_ROUTES  have some shared route, for example in the home page both of them see list view and when user tap on one item i checked is he manager or regular, and i have to show the target routes like this:

```
class RouteCompoenent extends Component {
    render() {
        if (this.props.isManager) {
            return <ManagerRoutes/>;
        }         
        return <ResidentRoutes/>;
    }
}
const mapStateToProps = (state) => {
    return {
        isManager: state
            .get('appState')
            .get('isManager')
    };
};

export default connect(mapStateToProps)(RouteCompoenent);
```
in my home page (user and admin can see home page) when user tap on one item  and if i understand he is manager, i dispatch the action and navigate to target route, but i see blank page. this is my home page component

```
onBuildingClick = (item) => {
    let newData = {
        name: item.name,
        isManager: item.isManager                
    };


    this.props.changeAppState({
        name: 'selectedBuilding',
        value: Immutable.fromJS(newData)
    });
    if (item.isManager) {
        this.props.navigation.navigate('Listing'); // if i use it with setTimout it will be ok but the back button is 
         not work   
    } else {
        this.props.navigation.navigate('BuildingList');
    }
  
}
```
---

### Current Behavior
when user tap on one item and and i understand he is manager, as you see i show managerRoutes but i see blank page, i mean when i change a route config its not work

### Expected Behavior
i expected to define seprate navigator for manager and regular user and when user tap on one item, i decide which route should i render.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^1.0.0-beta.11
| react-native     | 0.48.3
| node             | 6.11.1
| npm or yarn      | 3.10.10

**Comment by vonovak** [comment]
hi @derakhshanfar, I'm sorry but we use issue tracker for issues only, to make it easier for us to manage them. Since your post is not an issue but a usage question, I'm closing it. I recommend asking your question on stackoverflow.

**Comment by derakhshanfar** [comment]
@vonovak  thanks for response but why do you have question label ? :-)  i can't find any solution on stackoverflow
