### ISSUE TITLE
I can't use NavigationActions.navigate() to trun to other Navigator Screen from another Navigator by redux and react-navigation

### ISSUE THREAD

**Issue by MBWu** [react-community/react-navigation#2902]
## The issue list is reserved for bugs and feature requests, not for questions.

For usage questions, try to:

these are my code :

//navReducer.js

let initialState = TopLevelNavigator.router.getStateForAction(

    TopLevelNavigator.router.getActionForPathAndParams( 'Home' )

);

const navReducer = ( state = initialState, action ) => {

    let nextState;

    switch( action.type ){

        case 'nav_songlist':
            nextState = TopLevelNavigator.router.getStateForAction(
                NavigationActions.navigate( {routeName: 'FoundMusicStack_MVPlayer'} ),
                state
            )

        default:
            nextState = TopLevelNavigator.router.getStateForAction(

                action,
                state

            )
    }

    return nextState || state;
}

these are my top level navigator
// topnavigator.js

export const TopLevelNavigator = StackNavigator( {
    
    Home : {
        screen: HomeScreen
    },
    AduioPlayer : {
        screen: AduioPlayerScreen
    },
    MVPlayer: {
        screen: MVPlayerScreen
    },
    PrivateFM: {
        screen: PrivateFMScreen
    },
    MyMessage: {
        screen: MyMessageScreen
    },
    PrivilegeCenter: {
        screen: PrivateFMScreen
    },
    Store: {
        screen: StoreScreen
    },
    FreeFlow: {
        screen: FreeFlowScreen
    },
    Setting: {
        screen: SettingScreen
    },
    SetTimePause: {
        screen: SetTimePauseScreen
    },
    About: {
        screen: AboutScreen
    },
    Login: {
        screen: LoginScreen
    },
    PlayQuality: {
        screen: PlayQualityScreen
    },
    DownloadQuality: {
        screen: DownloadQualityScreen
    },
    Equalizer: {
        screen: EqualizerScreen
    },
    BluetoothPlayer: {
        screen: BluetoothPlayerScreen
    },
    SongReview: {
        screen: SongReviewScreen
    },
    ExchangeTheme: {
        screen: ExchangeThemeScreen
    }

},{
    cardStyle: {
        paddingTop:0
    },
    
} )

// this is a component in HomeScreen 's child's child's child's component

<Text
                    
                    style = { styles.PersonalRCMScreen_RcmSonglistTitleMore }
                    onPress = { () => {

                        store.dispatch ({
                            type: 'nav_songlist'
                        })  
                        
                    } }
                    >
                        more >
                    </Text>

---

### Current Behavior
 i use redux and react-navigation  , but i can only trun to the top level screen  from other  child 's Navigator screen component . i try to dispatch the action ,but nothing happened. 

i'm sad qwq....

**Comment by jonbcampos** [comment]
+1 watching. I recently updated and am seeing the same results

**Comment by kelset** [comment]
1. you haven't respected the issue template
1. in your code you are trying to use `store.dispatch`, not `NavigationActions.navigate()` as you say in the title

@jonbcampos if you think you are experiencing an actual bug, please open a new issue that **follows** the template, with a snack or a repo that reproduces the issue.
