### ISSUE TITLE
Card is cut off on iPhone X

### ISSUE THREAD

**Issue by danieldelouya** [react-community/react-navigation#2907]
On the iPhone X simulator, the size of the card does not stretch out to the top and bottom. 
Running:
"react": "^16.0.0-beta.5",
"react-navigation": "^1.0.0-beta.15",
"react-native": "^0.49.3",

I've tried with the even newer versions than mentioned above. 

<img width="369" alt="skaermbillede 2017-11-05 kl 13 56 04" src="https://user-images.githubusercontent.com/8565737/32414938-313054ae-c231-11e7-9a15-f821c1184c04.png">

**Comment by danieldelouya** [comment]
Update: It had something to do with another library.

**Comment by fenglu09** [comment]
@danieldelouya   Have the same problem. Did you have solved it ?
