### ISSUE TITLE
Disabling hardware back button without using redux?

### ISSUE THREAD

**Issue by jinxac** [react-community/react-navigation#2911]
In my application I have certain screens where I want to disable native android back button and I am not using redux. 

I know with redux this can be achieved as seen in [https://github.com/react-community/react-navigation/issues/455](https://github.com/react-community/react-navigation/issues/455) but also I have deeplinking associated with few screens so I don't want to handle all those cases on my own but framework do it.

So what is the best way to achieve deeplinking and disabling android back without bringing redux into the picture?

**Comment by vonovak** [comment]
hi! In your screen component, just add 

```js
  componentDidMount() {
    BackHandler.addEventListener('hardwareBackPress', this.onBackButtonPressAndroid);
  }

  componentWillUnmount() {
    BackHandler.removeEventListener('hardwareBackPress', this.onBackButtonPressAndroid);
  }

  onBackButtonPressAndroid = () => {
    if (youWannaHandleThisPress) {
      // do your work
      return true;
    } else {
      return false;
    }
  };
}
```

**Comment by jinxac** [comment]
@vonovak I have few screens where I need to implement custom back functionality. But since it is a stack navigator and I use navigate to go to another component, `componentWillUnmount` is not called for previous component and events in both the components clash and it does not work properly. Its there a good way to handle this?
