### ISSUE TITLE
Reset StackNavigator

### ISSUE THREAD

**Issue by hszeto** [react-community/react-navigation#2912]
let's say I have this setup:

```
const bStack = StackNavigator({
  b1: { screen: B1 },
  b2: { screen: B2 }
});

const AppNavigator = TabNavigator({
  a1: { screen: A1 },
  b:  { screen: bStack }
});
```

Let's say I went to the B2 screen... then tab on A1 screen... then tab on bStack... 

It shows the B2 screen.

How can I reset the bStack to show the B1 screen when user re-visit the bStack tab?

**Comment by kelset** [comment]
Closing this in favor of #2291
