### ISSUE TITLE
tabs renders nothing sometimes

### ISSUE THREAD

**Issue by shi1hh** [react-community/react-navigation#2914]
### Environment
react-native

### Steps to reproduce
code
```

import React, { PureComponent } from 'react';
import {ListView,Text} from 'react-native'
import {Tabs,Button,List} from 'antd-mobile'
import {StackNavigator,TabNavigator} from 'react-navigation'

const ds = new ListView.DataSource({rowHasChanged: (r1, r2) => r1 !== r2});

class Test extends PureComponent {

    constructor(props) {
        super(props);
        this.state={
            tabs:[{title:'一',index:0},{title:'二',index:1},{title:'三',index:2},{title:'四',index:3},{title:'五',index:4}]
        }
    }

    renderContent = (tab, index) => {
        let arr=[];
        for(let i=0;i<100;i  ){
            arr.push(1)
        }
        return <ListView    dataSource={ds.cloneWithRows(arr)}
                            renderRow={(rowData) => <Text>{rowData}</Text>}/>
    };

    render() {
        return (
            <Tabs

                tabs={this.state.tabs}
                initialPage={0}
            >
                {this.renderContent}
            </Tabs>
        )
    }
}


const Tabs2 = TabNavigator({
    Home: {
        screen: Test,
        navigationOptions: {
            tabBarLabel: '1',

        }
    },
    Video:{
        screen:Test,
        navigationOptions:{
            tabBarLabel:"2",

        }
    },
    Mine:{
        screen:Test,
        navigationOptions: {
            tabBarLabel: "3",
        }
    }

}, {
    initialRouteName:"Home",
    tabBarPosition: 'bottom',
});

const AppNavigator = StackNavigator({
    Tabs2: { screen: Tabs2,
    }
},{
    initialRouteName: 'Tabs2'});

export default AppNavigator;

```

![image](http://chuantu.biz/t6/126/1509808612x989668850.gif)

this bug about react-navigation?

[https://github.com/ant-design/ant-design-mobile/issues/2048](https://github.com/ant-design/ant-design-mobile/issues/2048)

### What is expected?
no white screen

### What is actually happening?
white screen

**Comment by apsbtn** [comment]
Change RCTView.m
```ObjectiveC
if (!CGRectContainsRect(testView.bounds, testRect)) {
  clipView = testView;
  clipRect = CGRectIntersection(testView.bounds, testRect);
}
```
To
```ObjectiveC
if (!CGRectContainsRect(testView.bounds, testRect) && !CGRectIsEmpty(CGRectIntersection(testView.bounds, testRect))) {
          clipView = testView;
          clipRect = CGRectIntersection(testView.bounds, testRect);
}
```

**Comment by kelset** [comment]
Without properly following the issue template, it's nearly impossible to understand & investigate the issue. Please answer/explain these questions:

1. have you tried updating to the latest release?
1. does it happen only on Android/iOS?
1. does it happen on both Debug and Release modes?
1. does it happen with Debugger On or Off? Both?
1. Can you provide a repo or a snack to reproduce this issue?

And write down your dependencies.

**Comment by shi1hh** [comment]
@apsbtn works fine,thank you.

@kelset
1.have you tried updating to the latest release?

my navigation version is git+https://github.com/react-community/react-navigation.git#ed2fc9a09e2f562ae9d3fc7f5df17c593989db0a.

2.does it happen only on Android/iOS?

only ios.

3.does it happen on both Debug and Release modes?

may be,i have no try

4.does it happen with Debugger On or Off? Both?

does

5.Can you provide a repo or a snack to reproduce this issue?

sorry,i can't

**Comment by kelset** [comment]
@shi1hh you mean that the suggestion provided by @apsbtn fixed the issue?

Moreover, I'll say it again: without properly following the issue template, it's nearly impossible to understand & investigate the issue. And you not answering my follow up questions leaves the situation unchanged.

**Comment by kelset** [comment]
Closing in favor of https://github.com/react-community/react-navigation/issues/3035
