### ISSUE TITLE
TabBar tabBarIcon overflow position

### ISSUE THREAD

**Issue by albinekb** [react-community/react-navigation#2916]
This is a regression in versions after `beta 13`

### Current Behavior
Using this code:
```js
ItemNavigator.navigationOptions = props => ({
  tabBarLabel: 'items',
  tabBarIcon: ({ tintColor }) => (
    <View>
      <Image
        source={require('../../assets/icons/tabs/maskinparGrey.png')}
        style={[{}, { tintColor: tintColor }]}
      />
      {props.screenProps.itemBadge ? (
        <Badge
          badgeColor={props.screenProps.itemBadge.color}
          count={props.screenProps.itemBadge.count}
          fontSize={12}
          up={-5}
        />
      ) : null}
    </View>
  )
```
On actual device:
![image](https://user-images.githubusercontent.com/5027156/32441740-2930dad0-c2f9-11e7-840c-5c81e687e5f1.png)

In simulator: 
![image](https://user-images.githubusercontent.com/5027156/32441778-4c0b97fc-c2f9-11e7-8f07-8668278f09b9.png)

### Expected Behavior
Should work as it did in beta 13 and earlier:
![image](https://user-images.githubusercontent.com/5027156/32441794-552763b6-c2f9-11e7-9034-7d8aaf9e2b69.png)

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | beta 14 and up (issue still present in beta 19)
| react-native     | `0.49.5`
| node             | `8.x`
| npm or yarn      | `yarn 1.2.1`

**Comment by kelset** [comment]
Duplicate: https://github.com/react-community/react-navigation/issues/2805#issuecomment-341763432

**Comment by albinekb** [comment]
Thanks @kelset 👍
