### ISSUE TITLE
Improvement for unclear error message

### ISSUE THREAD

**Issue by LAITONEN** [react-community/react-navigation#2925]
### Current Behavior
If a user does not provide a **truthy** string for `headerTitle`, leaving it to be equal to **empty string**, then during the **navigation** between screens in the StackNavigator, they will get an unclear error:
`RawText "" must be wrapped in an explicit <Text> component.`
The description of this error does not provide clear enough explanations on where did the problem occur and how to fix it. It took some hours for me to solve it. The error most probably comes from React-Native side.

### Expected Behavior
It would be much better if React-Navigation's error popped-up, explaining that the value of headerTitle should be a truthy string.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^1.0.0-beta.13
| react-native     | https://github.com/expo/react-native/archive/sdk-21.0.2.tar.gz
| node             | v8.6.0
| npm or yarn      | 4.6.1

**Comment by kelset** [comment]
Thanks for reporting, a PR with this small improvement would surely be welcome.

**Comment by vonovak** [comment]
this is fixed in master through https://github.com/react-community/react-navigation/commit/fafe68b8cba06b64e5cd63f48b0490856edd34b7
