### ISSUE TITLE
iOS not showing icon from tabs 

### ISSUE THREAD

**Issue by artsx** [react-community/react-navigation#2927]
Hello,
By updating the package, I no longer see the icons of the tabBar only on iOS =>
<img width="413" alt="screen shot 2017-11-07 at 20 03 54" src="https://user-images.githubusercontent.com/7711803/32512356-0b526e76-c3f7-11e7-9f84-d6b0e40bc060.png">

I've already try to delete all my `node_modules` and `npm install` but it does not matter

To see the icons I need to downgrade the version up to **1.0.0-beta.13**

**Config :**
React-native : **0.44.2**
node : **6.9.1**

my code : 
```
export const Navigator = TabNavigator(tabs, {
    tabBarPosition: 'bottom',
    swipeEnabled: false,
    animationEnabled: true,
    tabBarOptions: {
        indicatorStyle: { backgroundColor: 'transparent' },
        inactiveTintColor: Colors.secondaryColor,
        activeTintColor: Colors.brandColor,
        showIcon: true,
        showLabel: false,
        style: {
            backgroundColor: Colors.light
        }
    }
});
```

And Icon : 
```
static navigationOptions = {
        tabBarIcon: ({focused}) => <TabIcon active={focused} size={26} color={Colors.primaryColor} groupName={'FontAwesome'} name="newspaper-o" />
    };
```
I've already try with simply `<Icon name="lens" ... />` from react-native-vector-icon, same issue

Any idea why ? Thank you for your help !

**Comment by kelset** [comment]
Duplicate: https://github.com/react-community/react-navigation/issues/2805#issuecomment-341763432
