### ISSUE TITLE
Custom tabBarIcon not rendered on iOS

### ISSUE THREAD

**Issue by ptboyer** [react-community/react-navigation#2928]
When upgrading to version `1.0.0-beta.14` or above (for iOS), custom defined `tabBarIcon` in `navigationOptions` for a `TabNavigator`'s child scenes are not rendered at all and leaves the touchable view without any inner content which is supposed to be the icon, but it is still pressable.

Last working on version `1.0.0-beta.13`, regression introduced `1.0.0-beta.14`.

```
MyView: {
  screen: FeedScene,
  path: 'feed',
  navigationOptions: {
    tabBarLabel: 'MyView',
    tabBarIcon: ({ tintColor }) => (
      <Icon name='newspaper-o' size={20} color={tintColor} />
    )
  }
}
```

---

### Current Behavior
- Regression stops custom defined `tabBarIcon`s from rendering in tab buttons.

<img width="351" alt="screen shot 2017-11-08 at 10 52 03" src="https://user-images.githubusercontent.com/8391902/32524611-b848da2a-c474-11e7-9fd3-35e83f9417e9.png">

### Expected Behavior
- The `tabBarIcon` should be rendered.

<img width="351" alt="screen shot 2017-11-08 at 10 48 03" src="https://user-images.githubusercontent.com/8391902/32524607-b44ec498-c474-11e7-861b-2a33e97becdb.png">

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.14
| react-native     | 0.44.3
| node             | 8.7.0
| npm or yarn      | 0.24.6

**Comment by kelset** [comment]
Duplicate: https://github.com/react-community/react-navigation/issues/2805#issuecomment-341763432
