### ISSUE TITLE
Cannot hide header

### ISSUE THREAD

**Issue by bosung90** [react-community/react-navigation#293]
I tried following:

1. 
```
headerMode: 'none'
```

2. 
```
headerMode: 'screen',
navigationOptions: {
  header: {
    visible: false
  }
}
```

neither of them works.

Currently using:
```
  "dependencies": {
    "react": "15.4.2",
    "react-native": "0.41.2",
    "react-navigation": "^1.0.0-beta.3",
    "react-redux": "^5.0.2",
    "redux": "^3.6.0",
    "redux-thunk": "^2.2.0"
  }
```

**Comment by shawngustaw** [comment]
Which navigator are you using?

**Comment by mbrochh** [comment]
For me it looks like this:

```
class AskForFeedbackScreen extends React.Component {
  static navigationOptions = {
    header: {
      visible: false,
    }
  };

  render() {
    return (
      <View>
        <Text>Ask for Feedback</Text>
      </View>
    )
  }
}

const MainScreenNavigator = TabNavigator({
  Feed: { screen: FeedScreen },
  Contacts: { screen: ContactsScreen },
  Alerts: { screen: AlertsScreen },
  Profile: { screen: ProfileScreen },
});

const SimpleApp = StackNavigator({
  Tabs: { screen: MainScreenNavigator },
  ProfileThem: { screen: ProfileThemScreen, user: 'Sally' },
  AskForFeedback: { screen: AskForFeedbackScreen },
});
```

The header for `AskForFeedbackScreen` still shows up.

**Comment by mbrochh** [comment]
@bosung90 this worked for me:

```
class AskForFeedbackScreen extends React.Component {
  static navigationOptions = {
    header: {
      visible: false,
    }
  }
  render() {
    return (
      <View>
        <Text>Ask for Feedback</Text>
      </View>
    )
  }
}

const MainScreenNavigator = TabNavigator({
  Feed: { screen: FeedScreen },
  Contacts: { screen: ContactsScreen },
  Alerts: { screen: AlertsScreen },
  Profile: { screen: ProfileScreen },
});

const SimpleApp = StackNavigator(
  {
    Tabs: { screen: MainScreenNavigator },
    ProfileThem: { screen: ProfileThemScreen, user: 'Sally' },
    AskForFeedback: { screen: AskForFeedbackScreen, headerMode: 'none' },
  },
  { headerMode: 'screen' }
);

AppRegistry.registerComponent('hoorah', () => SimpleApp);
```

I had to specifically set `headerMode: 'screen'` on the navigator options. After I did that, the `header: { visible: false }` on the screen component was being honored.

**Comment by meno1** [comment]
Wow.  Thanks, @mbrochh that was driving me insane.  Why does this fix work?

**Comment by shawngustaw** [comment]
@meno1 from the docs:
```

headerMode - Specifies how the header should be rendered:

    float - Render a single header that stays at the top and animates as screens are changed. This is a common pattern on iOS.
    screen - Each screen has a header attached to it and the header fades in and out together with the screen. This is a common pattern on Android.
```

I assume the default is float, which enforces that the header doesn't hide.

**Comment by grabbou** [comment]
Yeah, there was a discussion whether to allow header visibility changing on per screen basis when mode `float`. Please follow this discussion: #53

**Comment by thurt** [comment]
solution from @mbrochh worked for me. i am using react-navigation 1.0.0-beta.2

one other comment: `visible: false` works without issue on android, even when `headerMode` isn't specified. But on ios, i need to specify `headerMode: screen`, otherwise a header that is `visible: false` will still show a blank header and it will push down all other content.

**Comment by AlanFoster** [comment]
For iOS it seems you will need to specify the `mode` as `modal`. Doing so removes the need to specify `headerMode: 'screen'` based on the current implementation of `_getHeader`:

```
const SimpleApp = StackNavigator(
  {
    Tabs: { screen: MainScreenNavigator },
    ProfileThem: { screen: ProfileThemScreen, user: 'Sally' },
    AskForFeedback: { screen: AskForFeedbackScreen },
  },
  { mode: 'modal' } // Updated
);
```

This will work for both Android and iOS

**Comment by cpenarrieta** [comment]
note this changed starting [beta9](https://github.com/react-community/react-navigation/releases/tag/v1.0.0-beta.9)
Before:
```
{
  header: {
    visible: false,
  },
}
```
Now:
```
{
   header: null,
}
```

**Comment by mehtamanan** [comment]
@cpenarrieta  Thanks a lot, buddy! Exactly what i was finding for!

**Comment by mynameisbams** [comment]
Objects are not valid as a React child (found: object with keys {visible}). If you meant to render a collection of children, use an array instead.

**Comment by AlexandrePalo** [comment]
@mynameisbams remove `static`

**Comment by betocantu93** [comment]
On iOS emulator: header: null, tabBarLabel and tabBarIcon works as expected, but when tested on iPad, the header shows, the tabBarLabel and tabBarIcon don't work at all (shows default screen or navigator name), I don't know how to debug it.

**Comment by foobar8675** [comment]
not sure if this is what people are looking for, but i want to disable headers in my entire app, this is how i'm doing it.
````
export default StackNavigator({
  Home: {
    screen: HomeNav,
  },
  Onboard: {
    screen: OnboardNav,
  },
}, {
    // see next line
    headerMode: 'none',
});
````

**Comment by dan-me** [comment]
@cpenarrieta Thanks a lot, buddy!

**Comment by gotoAndBliss** [comment]
Just a wild guess, but perhaps because i'm using Redux, there is no way to hide the header?

Using (beta9)[https://github.com/react-community/react-navigation/releases/tag/v1.0.0-beta.9]

No options I add augment my header nor remove it :

```
export const Navigation = StackNavigator({
  Home: { 
    screen: Purgatory,
    headerMode: 'none',
    header: null,
    navigationOptions: {
        header: null
    }    
  },
  Start: { 
    screen: GameStart,
    headerMode: 'none',
    header: null,
    headerTintColor: '#000000',
    navigationOptions: {
      header: null
    }    
  }
}, {
  header: null,
  headerMode: 'none',
  navigationOptions: {
    header: null
  }
});

const AppWithNavigationState = ({ dispatch, nav }) => (
  <Navigation navigation={addNavigationHelpers({ dispatch, state: nav })} />
);

AppWithNavigationState.propTypes = {
  dispatch: PropTypes.func.isRequired,
  nav: PropTypes.object.isRequired,
};

const mapStateToProps = state => ({
  nav: state.nav,
});

export default connect(mapStateToProps)(AppWithNavigationState);
```

**Comment by FranzAlvaroMD** [comment]
use the following form: 
-------------------------------------
const IndexApp = StackNavigator(
  {
  App: { screen: App },
  Search: { screen: Search },
},
{  headerMode: 'none' }
);
-------------------------------------
after:
------------------------------------- 
  static navigationOptions = {
    header: {
       visible: false
     }
   }
-------------------------------------

**Comment by ShayanJavadi** [comment]
@foobar8675 saved my life

**Comment by foobar8675** [comment]
@ShayanJavadi :)

**Comment by sachinwak** [comment]
Below code also works for me 
`const login_stack_nav = StackNavigator({
  LoginForm: {
    screen: LoginForm,
    // Optional: Override the `navigationOptions` for the screen
    navigationOptions: ({navigation}) => ({
      header: false
    }),
  }
});`

**Comment by sachinwak** [comment]
Below code also works for me.

`
const login_stack_nav = StackNavigator({
  LoginForm: {
    screen: LoginForm,
    // Optional: Override the `navigationOptions` for the screen
    navigationOptions: ({navigation}) => ({
      header: false
    }),
  }
});
`

**Comment by sachinwak** [comment]
Below code also works for me 
```
const login_stack_nav = StackNavigator({
  LoginForm: {
    screen: LoginForm,
    // Optional: Override the `navigationOptions` for the screen
    navigationOptions: ({navigation}) => ({
      header: false
    }),
  }
});
```

**Comment by TeaNose** [comment]
@sachinwak : thx! your solution worked for me. :)

**Comment by BarthesSimpson** [comment]
@sachinwak 's solution worked for me. {header: null} did not work.

**Comment by raihanrazi** [comment]
this worked for me 

navigationOptions: {
      header: () => null,
    }

**Comment by rakibulalam** [comment]
@raihanrazi Why do you keep extra overhead? ` header:null instead of ()=>null`

**Comment by raihanrazi** [comment]
@rakibulalam I followed this approach due to tabBarLabel requiring `() => null`.

For header just `null` is fine. 

Thanks for pointing it out. Cheers.

**Comment by HuyThong96** [comment]
thanks worked for me !

**Comment by xMaarf** [comment]
@cpenarrieta thanks man! :D

**Comment by murthy474** [comment]
this is use full for you
const Main = StackNavigator({
        tab: {screen:Router,navigationOptions: { header: null}},  });

**Comment by CoericK** [comment]
I was facing the same issue, so in summary set headerMode to 'screen' in the root StackNavigator and hide it when you dont need it, this is the only way?
PS: Talking about react-navigation@1.5.8

**Comment by Jacckashakashkumar** [comment]
thanks cpenarrieta

**Comment by Brlo1992** [comment]
@foobar8675  thanks, this works for me:D!

**Comment by dhavaljardosh** [comment]
<h3>header: null</h3>  

```
static navigationOptions = {
    header: null,
};
```

**Comment by xavierartot** [comment]
this one works, I have Stack in Tabs:
```
const Stacks = createStackNavigator({
  // new routes
  Decks: {
    screen: Tabs,
    navigationOptions: ({ navigation }) => ({
      header: null,
    }),
  },
  DeckList: {
    screen: DeckList,
    navigationOptions: {
      headerTintColor: white,
      headerStyle: {
        backgroundColor: purple,
      },
    },
  },
})
```

**Comment by blurdylan** [comment]
You can hide it with `navigationOptions: () => ({ header: null })`

Full Code:
```javascript
const AppNavigator = createStackNavigator(
  {
    Home: { screen: Home },
    TV: { screen: TV }
  },
  {
    initialRouteName: "Home",
    navigationOptions: () => ({ header: null }) //<= The line you are looking for
  }
);
```

This code helps to hide it on all screens, if you want to hide that on a single screen, just add this line `navigationOptions: () => ({ header: null })` only in the page's object

Docs Reference: https://reactnavigation.org/docs/en/headers.html#sharing-common-navigationoptions-across-screens

**Comment by rimiti** [comment]
This works fine for `react-navigation` 3 :

```
{
  initialRouteName  : 'Screen1',
  headerMode        : 'none',
}
```

**Comment by timurridjanovic** [comment]
How would you show it back again dynamically? 
header: { visible: true }, doesnt work after it was set to null

**Comment by rimiti** [comment]
@timurridjanovic use `headerMode        : 'none',`

**Comment by ananth10** [comment]
Splash: {
            screen: Splash,
            **headerMode: 'none',**
            **header: null,**
            defaultNavigationOptions: {
                statusBarHidden: true,
                **header: null,**
            }
        },


Still is not hide the default header in android. react navigation version is 3.6.0. any help??

**Comment by BharathReddyA** [comment]
I'm still able to see the header, can anyone help me out of this.

class MainScreen extends React.Component {
  static navigationOptions = {
    header: null
  };

  render() {
    return (
      <View style={styles.container}>
        <Button
          style={styles.btn}
          title="Sign in!"
          onPress={() => this.props.navigation.navigate("Login")}
        />
      </View>
    );
  }
}

class OtherScreen extends React.Component {
  static navigationOptions = {
    header: null
  };

  render() {
    return (
      <View style={styles.container}>
        <Button
          style={styles.btn}
          title="Sign in!"
          onPress={() => this.props.navigation.navigate("Login")}
        />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#282828"
  },
  btn: {
    backgroundColor: "#1db954",
    marginVertical: 10
  }
});

const AppStack = createStackNavigator({
  Other: OtherScreen,
  Login: LoginScreen
});

export default createAppContainer(
  createSwitchNavigator(
    {
      Main: MainScreen,
      App: AppStack
    },
    {
      initialRouteName: "Main"
    }
  )
);

**Comment by Aung-Myint-Thein** [comment]
```
const AppStack = createStackNavigator(
  {
    Screen1: Screen1,
    Screen2: Screen2,
    Screen3: Screen3
  },
  {
    headerMode: 'none',
    header: null
  }
);
```

For me, this solved the `header` showing up after updating to React Navigation 4.0.5

**Comment by hugoh59** [comment]
None of these worked for me.

**Comment by tauanbinato** [comment]
Hope this helps.. working here:
`const AppNavigator = createStackNavigator({
  LoginScreen: {
    screen: LoginScreen,
    navigationOptions: ({ navigation }) => ({
      headerShown: false
    }),
  },
  MainScreen: MainScreen
});

export default createAppContainer(AppNavigator);`

**Comment by aravindSiruvuru05** [comment]
` options={{
          headerShown: false
        }}`
