### ISSUE TITLE
Update to react-native@0.50 and flow-bin@0.56

### ISSUE THREAD

**Issue by macrozone** [react-community/react-navigation#2933]
I know a lot of effort went into this, but I still have a lot of flow errors on react-navigation and i have no idea what i should do anymore.

I am using flow version 0.56 with react-native 0.50.x and react-navigation@1.0.0-beta.19 and atom ide-flowtype (latest version)

<img width="954" alt="bildschirmfoto 2017-11-08 um 15 05 55" src="https://user-images.githubusercontent.com/1972353/32553160-592423ca-c496-11e7-9dd4-f89af6807d9c.png">

I also get a lot of errors in test-files where "expect" or "it" is not defined. What's wrong with my configuration?

**Comment by daveysigma** [comment]
same issue. newly create-native-react-app with react-navigation added, follow instructions for setup of flow 0.53.0 (version specified in .flowconfig) 
```
  "dependencies": {
    "expo": "^22.0.2",
    "react": "16.0.0-beta.5",
    "react-native": "^0.49.5",
    "react-navigation": "^1.0.0-beta.19"
  },
  "devDependencies": {
    "flow-bin": "0.53.0",
    "jest-expo": "^22.0.0",
    "react-native-scripts": "1.7.0",
    "react-test-renderer": "16.0.0-beta.5"
  }
```
seeing loads of flow errors mainly, jest related 

`identifier 'it|expect|describe|jest' could not resolve name in node_modules/react-navigation

and

`./PlatformHelpers. Required module not found`


adding
```
; Ignore react-navigation
<PROJECT_ROOT>/node_modules/react-navigation/.*
```

to `.flowconfig` suppresses them.

**Comment by kelset** [comment]
Hi @macrozone, yes, we have been working a lot to reduce the number of Flow errors. The main reason you are seeing them I think it's because you are using version 0.56 with react-native 0.50.x.

We currently support up to rn 0.49 and flow 0.53. Which makes quite weird what @daveysigma says.

Ping @Ashoat which is our resident Flow expert.

**Comment by Ashoat** [comment]
@macrozone: @kelset is 100% right - we haven't upgraded to RN 0.50 yet, so you're going to see Flow errors. I looked at upgrading earlier in the week, but since Expo 23 hasn't been released yet, and since the RN version in root and the RN version in `NavigationPlayground` need to be kept in sync, I figured we couldn't upgrade yet.

@daveysigma: I'm not sure what's going on there, I'll need more details to debug. Have you set up `flow-typed` in your repo and ran `flow-typed install`?

**Comment by daveysigma** [comment]
yeah flowTyped was the key to shutting down the errs. but the libs installed as pretty much `any` types everywhere for expo. are there actual flow types for expo?

**Comment by Ashoat** [comment]
No, there are not. There's an issue somewhere in their repo about it.

**Comment by macrozone** [comment]
@Ashoat thx for clarification. So as you updated the title of this issue to match the underlying problem, i leave it open.

**Comment by jherencia** [comment]
Expo SDK 23 has beed released: https://blog.expo.io/expo-sdk-v23-0-0-is-now-available-be0a8c655414

**Comment by kelset** [comment]
Hi @jherencia thanks for the comment, we (ash & skevy) are already working hard on bumping up the deps. But I don't have an ETA sorry

**Comment by jherencia** [comment]
Sure! I just wanted to let you know.

Thank you!

**Comment by Ashoat** [comment]
We're pretty close, just have 5 Flow errors left in the main directory, and 6 Flow errors in the NavigationPlayground directory.

**Comment by ferrannp** [comment]
I am trying latest version of `react-navigation@1.0.0-beta.21` and I am close to get no errors. Just 5 so far:

```sh
Launching Flow server for /Users/ferrannp/Development/Projects/ReactNative/Showman
Spawned flow server (pid=51553)
Logs will go to /private/tmp/flow/zSUserszSferrannpzSDevelopmentzSProjectszSReactNativezSShowman.log
Error: node_modules/react-navigation/lib-rn/createNavigationContainer.js.flow:4
  4: import { BackHandler, Linking } from './PlatformHelpers';
                                          ^^^^^^^^^^^^^^^^^^^ ./PlatformHelpers. Required module not found

Error: node_modules/react-navigation/lib/createNavigationContainer.js.flow:4
  4: import { BackHandler, Linking } from './PlatformHelpers';
                                          ^^^^^^^^^^^^^^^^^^^ ./PlatformHelpers. Required module not found

Error: node_modules/react-navigation/src/createNavigationContainer.js:4
  4: import { BackHandler, Linking } from './PlatformHelpers';
                                          ^^^^^^^^^^^^^^^^^^^ ./PlatformHelpers. Required module not found

Error: node_modules/react-navigation/src/createNavigationContainer.js:40
 40: export default function createNavigationContainer<S: NavigationState, O: {}>(
                                                          ^^^^^^^^^^^^^^^ object type. This type is incompatible with
                    v-------------------------------------------------------------
 40: export default function createNavigationContainer<S: NavigationState, O: {}>(
 41:   // Let the NavigationNavigator props flowwwww
 42:   Component: NavigationNavigator<S, O, *>
 43: ) {
     ^ some incompatible instantiation of `S`

Error: node_modules/react-navigation/src/createNavigationContainer.js:40
 40: export default function createNavigationContainer<S: NavigationState, O: {}>(
                                                                              ^^ object type. This type is incompatible with
                    v-------------------------------------------------------------
 40: export default function createNavigationContainer<S: NavigationState, O: {}>(
 41:   // Let the NavigationNavigator props flowwwww
 42:   Component: NavigationNavigator<S, O, *>
 43: ) {
     ^ some incompatible instantiation of `O`


Found 5 errors
```

Using `react-native@0.50.3` and `flow-bin@0.56.0`.

**Comment by Ashoat** [comment]
The first three errors can be solved by adding the following lines to the `[options]` section of your .flowconfig:

```
module.file_ext=.js
module.file_ext=.jsx
module.file_ext=.json
module.file_ext=.native.js
```

Regarding that it would also be helpful to ping [this PR](https://github.com/facebook/react-native/pull/16816/files) so that these lines are included in the default .flowconfig used by `react-native init` and presumably `react-native-git-upgrade`.

Regarding the last two errors, I am seeing these in my project as well. Not sure why they aren’t showing up in our NavigationPlayground example. I haven’t yet been able to refactor `createNavigationContainer` in a way that gets rid of those two errors, unfortunately.

**Comment by Ashoat** [comment]
Okay, #3030 should finally get us to 0 errors!

**Comment by jherencia** [comment]
Great news! Thank you!

**Comment by ferrannp** [comment]
@Ashoat thank you !!!

**Comment by alinz** [comment]
@Ashoat the problem still exists.

**Comment by kelset** [comment]
@alinz https://github.com/react-community/react-navigation/pull/3030

**Comment by alinz** [comment]
@kelset Is this already pushed to npm? I have to cherry pick this one? it's not out yet right?

**Comment by kelset** [comment]
You can point to master in your package.json, we haven't done a release with it yet. May be worth doing one soon.

**Comment by alinz** [comment]
Would be a good idea to release the new version as point it to master will not a good idea.

**Comment by punksta** [comment]
```
Error: node_modules/react-navigation/src/createNavigationContainer.js:4
  4: import { BackHandler, Linking } from './PlatformHelpers';
                                          ^^^^^^^^^^^^^^^^^^^ 
 ./PlatformHelpers. Required module not found
```
have this with flow `^0.57.0` and master react-navigation

**Comment by Ashoat** [comment]
https://github.com/facebook/react-native/pull/16816
