### ISSUE TITLE
Error after install react-navigation package with npm

### ISSUE THREAD

**Issue by stevesweetney** [react-community/react-navigation#2935]
Having the same problem as described in issue #1846
I am not sure if I should install react-native-scripts globally because of potential side effects
### Current Behavior
Ran `npm install react-navigation` in a Creact-React-Native-App project. Running `npm start` gives me an error: 

> 'react-native-scripts' is not recognized as an internal or external command,operable program or batch file

If run `npm uninstall react-navigation`, everything works fine.

### Expected Behavior
I should be able to use run `npm start`
### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |1.0.0-beta.19
| react-native     |0.49.5
| node             | 8.8.1
| npm or yarn      |5.5.1

**Comment by kelset** [comment]
I guess this issue is related to how CRNA works; and then the way to solve it is to do what the first reply to that said https://github.com/react-community/react-navigation/issues/1846#issuecomment-307988556

**Comment by manisha-sinha01** [comment]
The issue will get solved if you add the name of the dependency and its verson in the package,json file and then run the command 'npm install'

**Comment by brentvatne** [comment]
npm5 :(

**Comment by vijay0056** [comment]
Run the npm install command you can solve the issue.
