### ISSUE TITLE
src/createNavigationContainer.js: Unexpected token (46:6) ?

### ISSUE THREAD

**Issue by fozzarelo** [react-community/react-navigation#2936]
### Current Behavior

- I am getting an "error: bundling failed: SyntaxError" on a fresh installation using "react-native init":

    /node_modules/react-navigation/src/createNavigationContainer.js: Unexpected token (46:6)

-The error comes as soon as I try to import the lib.
- (46:6) is the "=" in the following segment code:

    export default function createNavigationContainer<A: *, O: *>(
  Component: NavigationNavigator<NavigationState, A | NavigationInitAction, O>
) {
  class NavigationContainer extends React.Component<Props<O>, State> {
    subs: ?{
      remove: () => void,
    } = null;

    static router = Component.router;

    constructor(props: Props<O>) {
      super(props);

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.19
| react-native     | 5.5.1
| node             | v8.8.1
| npm or yarn      | npm

**Comment by kelset** [comment]
Thanks for reporting.
This seems quite weird.

1. what do you mean by "fresh installation"? A `react-native init` command?
1. npm 5 is known for having issues, can you please try with yarn?

**Comment by fozzarelo** [comment]
thanks kelset.
Yea, pretty weird right?
Yup, created using "react-native init". there's no expo in it. 
Im going to try to reinstall with yarn. 
I'll report back.

**Comment by fozzarelo** [comment]
Yea... working good with yarn. 
I had to reinstall react, react-native and react-navigation. 
Not sure what went wrong w/ NPM.
thank you.

**Comment by kelset** [comment]
I'm not sure why, but basically NPM since version 5 is unreliable. :/
