### ISSUE TITLE
Customizing Router examples in docs causes max recursion depth. 

### ISSUE THREAD

**Issue by shawngustaw** [react-community/react-navigation#294]
Not sure if I'm missing something but the docs are defining getStateForAction as:

```
getStateForAction(action, state) {
    ...
    return MyApp.router.getStateForAction(action, state);
  }
```

which leads to that function calling itself over and over again. Am I missing something or is this a typo/mistake?

**Comment by shawngustaw** [comment]
Note that I'm also using redux so this might have something to do with it? Not too sure. 

```
const appReducer = combineReducers({
  nav: (state, action) => (
    AppNavigator.router.getStateForAction(action, state)
  ),
  ...
});
```

**Comment by mikeaxle** [comment]
I think you are missing NavigationActions and navigate. My code for the same is like this and its works fine:

```javascript
return AppNavigator.router.getStateForAction(NavigationActions.navigate({ routeName: 'route_name' }), state);

**Comment by ElliottJRo** [comment]
Hey @shawngustaw I just did this and my simplest solution was to make a copy of the old router before overwriting/extending:

```js
const oldRouter  = MyApp.router;
MyApp.router = {
  ...MyApp.router,
  getStateForAction(action, state) {
    console.log('getStateForAction is extended!');
    return oldRouter.getStateForAction(action, state);
  }
}
```
