### ISSUE TITLE
initialRouteName ignored after passing navigation prop to nested navigator

### ISSUE THREAD

**Issue by goinnovative** [react-community/react-navigation#2947]
In my app I have two navigators. One TabNavigator and a StackNavigator. Both are wrapped by components.

**AppNavigator** (Tabs: DishesScreen, DealsScreen, FavoritesScreen)
All screens are rendering a StackNavigator (consisting of DishList, DishDetails)

Everything works fine until I need to pass the navigation prop from the AppNavigator down to the screens and set the router after each class (like DishesScreen.router = DishesStack.router) to navigate back to the DishList if the user taps to time on the same tab (This works fine).

In my AppNavigator I have this:
```
export default TabNavigator({
  Deals: { screen: DealsScreen },
  Dishes: { screen: DishesScreen },
  Favorites: { screen: FavoritesScreen },
}, {
  initialRouteName: 'Dishes',
....
})
```

But if I start the app the FavoritesScreen is alway appearing...

And: The header of DishesScreen or DealsScreen are not visible randomly..

If I remove the  `navigation={this.props.navigation}` from the DealsScreen, DishesScreen and FavortesScreen everything works fine but navigating back the StackNavigator from the TabNavigator is not working anymore...

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.13
| react-native     | 0.50.1

**Comment by kelset** [comment]
Duplicate https://github.com/react-community/react-navigation/issues/2609
