### ISSUE TITLE
Back Button Minimizing the application

### ISSUE THREAD

**Issue by rochapablo** [react-community/react-navigation#2948]
### Current Behavior
Before start using redux, it was all working but now that I had change all my components to redux according to the example, in any screen that I'm, when I click at the Back Button (Android) from mobile the application minimize itself.

### Expected Behavior
It should go back to the preview screen, not minimize.

```
export default class App extends Component {
  store = store // import
  render() {
    return (
      <Provider store={this.store}>
        <AppWithNavigationState />
      </Provider>
    )
  }
}
```

```
export const AppNavigator = StackNavigator(
  {
    LoginNavigator: { screen: login },
    PrivateNavigator: { screen: drawer }
  },
  {
    ...settings,
    initialRouteName: 'LoginNavigator'
  }
)

class AppWithNavigationState extends Component<Props, {}> {
  render() {
    const { dispatch, nav } = this.props
    return (
      <AppNavigator navigation={addNavigationHelpers({ dispatch, state: nav })} />
    )
  }
}

const mapStateToProps = state => ({
  nav: state.nav
})

export default connect(mapStateToProps)(AppWithNavigationState)
```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.15
| react-native     | 0.49.3
| node             | 8.6.0
| npm      | 5.5.1

**Comment by kelset** [comment]
Uhm, I'm a bit confused. Have you wired the backHandler as said in [this section](https://reactnavigation.org/docs/guides/redux#Handling-the-Hardware-Back-Button-in-Android) of the docs?

**Comment by rochapablo** [comment]
@kelset I surely skipped that part of documentation, my bad.

Thank for your time.
