### ISSUE TITLE
Maximum update depth exceeded

### ISSUE THREAD

**Issue by lucasleelz** [react-community/react-navigation#2951]
### Current Behavior
```
 static navigationOptions = ({ navigation }) => {
    const { params = {} } = navigation.state;
    let headerRight = (
      <Button
        title="Save"
        onPress={params.handleSave ? params.handleSave : () => null}
      />
    );
    return { headerRight };
  };

  _handleSave = () => {
    console.log('click...');
  };

  componentDidMount() {
    this.props.navigation.setParams({ handleSave: this._handleSave });
  }
```
Console output results:
Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.

**The app interface may also be randomly stuck!!!**
**cpu soaring**
![image](https://user-images.githubusercontent.com/4484335/32642414-294bf572-c60f-11e7-9750-0338c99bfde1.png)

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.19
| react-native     | 0.50.2
| node             | v7.5.0
| npm    | 5.5.1

**Comment by kelset** [comment]
Duplicate https://github.com/react-community/react-navigation/issues/2702
