### ISSUE TITLE
Deep Linking with query params does not work anymore

### ISSUE THREAD

**Issue by vincejah** [react-community/react-navigation#2953]
The issue was first introduced with commit 7adad618d1ab0080004df8d6f2f1c1d1125551c7

### Current Behavior
- DeepLinking with uri that contains query params does not work anymore. query params are not passed down the state params.

`inputParams` is by default equal to `{}`, therefore, `queryParams` returns always `{}` even if `queryString` is not empty.

It causes a regression

### Expected Behavior
- query params should be passed to state.params.

### Your Environment

| software         | version
| ---------------- | -------
"react-navigation": "^1.0.0-beta.19",
"react-native": "0.44.3"

**Comment by vonovak** [comment]
@vincejah can you please try this branch and let me know if that fixes your issue? https://github.com/react-community/react-navigation/tree/fix2953

**Comment by vincejah** [comment]
@vonovak it is indeed fixed with your commit. Thanks!

**Comment by vonovak** [comment]
closing, fixed in master
