### ISSUE TITLE
SafeAreaView in DrawerNavigatorItems causes extra spacing between things when DrawerNavigatorItems is not the ONLY thing in the drawer

### ISSUE THREAD

**Issue by dantman** [react-community/react-navigation#2963]
### Current Behavior
#2833 added a `SafeAreaView` to every `DrawerNavigatorItems` instance. Now when you customize the drawer to either add a header or footer to it or to split up the items into multiple sections you get extra padding in between your sets of drawer items and other sets / headers or footers.

<img width="212" alt="screen shot 2017-11-10 at 8 17 41 pm" src="https://user-images.githubusercontent.com/53399/32686150-bdae0468-c654-11e7-9851-b7937667d68d.png">

### Expected Behavior
`SafeAreaView` should only be used once in the drawer content container, not in the `DrawerNavigatorItems` component. And custom implementations should be able to customize it because sometimes the contents aren't supposed to be inset (eg: the status bar should overlap the drawer header).

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.19
| react-native     | 0.50.3
| node             | v8.9
| npm or yarn      | 1.3.2

**Comment by kelset** [comment]
Thanks for reporting, we'll take a look at it asap. I know that @davepack is still working around this iPhone X integration so I've assigned him.

**Comment by davepack** [comment]
Hey @dantman, can you confirm that this fix does not work: https://github.com/react-community/react-navigation/issues/2854#issuecomment-341622757. Sorry we don’t have great documentation yet for this.

If it doesn’t work, can you post code that reproduces the problem? Thanks!

**Comment by dantman** [comment]
@davepack That is going to just make code unnecessarily bigger and messier. SafeAreaView is entirely unnecessary in the `DrawerNavigatorItems` component. It belongs in the (custom) drawer content component.

**Comment by davepack** [comment]
The default drawer needs it to support iPhone X. I agree this is messy and not ideal at all, but it was a trade off to get support for iPhone X out quickly.

We would welcome a PR if a better solution is found. Ideally there will be a better way to support iPhone X safe area insets before React Nav hits 1.0. SafeAreaView is also not the ideal solution, imo.

**Comment by dantman** [comment]
To support the iPhone X in the drawer only contentComponent needs the SafeAreaView. I'll make a PR when I have time.

**Comment by davepack** [comment]
Okay, I see what you mean, you're right. I'll make the change, test, and have a PR ready right away.

**Comment by davepack** [comment]
@dantman PR is up, would appreciate if you could test when you get a chance.
