### ISSUE TITLE
Header not rendering correctly

### ISSUE THREAD

**Issue by haseebnaseem** [react-community/react-navigation#2966]
## The issue list is reserved for bugs and feature requests, not for questions.

For usage questions, try to:

- [Read the docs](https://reactnavigation.org/)
- [Ask on the Reactiflux (#react-navigation)](https://discord.gg/reactiflux)
- [Look for / ask questions on StackOverflow](https://stackoverflow.com/questions/tagged/react-navigation)
- Search for your issue - it may have already been answered or even fixed in the development branch. However, if you find that an old, closed issue still persists in the latest version, you should open a new issue.

---

### Current Behavior
Header renders incorrectly when navigating to a different screen.
This is how the navigators are defined:
```
const FeedNav=TabNavigator({
    general:{screen:Feed},
    nearby:{screen:Nearby},
},{
    tabBarComponent:NavigationComponent,
    tabBarPosition:'top',
    initialRouteName:'general',
    tabBarOptions:{
        topNavigationOptions:{
            labelColor:'white',
            rippleColor:'white',
            tabs:{
                general:{
                    barBackgroundColor:'#37474F',
                },
                nearby:{
                    barBackgroundColor:'#00796B',
                }
            }
        }
    }
});
const HomeNav=StackNavigator({
    home:{screen:FeedNav},
    review:{screen:Review},
},{
    navigationOptions:{
        headerTitle:(<Image source={require('../paitoAssets/images/NewProtoImages/topSmallLogo.png')} style={{width:60,height:60}}  />),
        headerStyle:{
            backgroundColor:'#c21f2b',
        },
        headerTitleStyle:{
            alignSelf:'center',
        },
        headerLeft:null,
    }
})
export const Navigator=StackNavigator(
    {
        feedScreen:{screen:HomeNav},
        HomeScreen:{screen:Home},
        VerifyScreen:{screen:Verify},
        newUserScreen1:{screen:newUser1},
        newUserScreen2:{screen:newUser2},
        loginScreen:{screen:login},
    },
    {
        initialRouteName:'HomeScreen',
        headerMode:'none',
    },
);
```
![screenshot from 2017-11-13 01-32-03](https://user-images.githubusercontent.com/10306624/32703080-95a62b34-c812-11e7-8d02-753aa03654f4.png)
This is a tabNavigator nested inside a stack navigator. Which renders the header correctly. When navigating to a different screen inside the stack navigator, the header does not render the image. 
![image](https://user-images.githubusercontent.com/10306624/32703096-dc11aef4-c812-11e7-92be-b14fc082f65a.png)

- _If suggesting a change/improvement, explain the difference from current behavior_

### Expected Behavior
![image](https://user-images.githubusercontent.com/10306624/32703148-7a9314e6-c813-11e7-8028-fc985694ead7.png)

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.19
| react-native     | 0.48.2
| node             | 7.10.1
| npm or yarn      | npm 4.2.0

**Comment by kelset** [comment]
Duplicate https://github.com/react-community/react-navigation/issues/2918
