### ISSUE TITLE
Navigation is very slow in android

### ISSUE THREAD

**Issue by Sunil-tc** [react-community/react-navigation#2969]
Navigation is very slow in android, both in emulator and in phone. IOS navigation works fine.
All the navigators(TabNavigator, StackNavigator & DrawerNavigator) are slow in android.
What is the solution for this ?

**Comment by kelset** [comment]
Closing because you haven't respected the issue template, nor [read the README](https://github.com/react-community/react-navigation#my-app-is-really-slow).
