### ISSUE TITLE
Header bottom shadow 

### ISSUE THREAD

**Issue by primalyeti** [react-community/react-navigation#297]
I can't seem to get rid of the bottom shadow on the header. Is that not supported yet?

static navigationOptions = {
		title: 'Test',
		header: {
			visible: true,
			style: {
				borderWidth: 0,
				borderBottomColor: Styles.Settings.colors.secondary,
				backgroundColor: Styles.Settings.colors.secondary,
				shadowColor: Styles.Settings.colors.secondary,
				shadowRadius: 0,
				shadowOpacity: 0,
				shadowOffset: {
					height: 0,
					width: 0,
				},
			},
			titleStyle: {
				color: Styles.Settings.colors.white,
			},
			tintColor: Styles.Settings.colors.secondary,
		}
	};

**Comment by cmrichards** [comment]
The shadow is probably implemented using the "elevation" property - which is not a style attribute.  

I'm also interested in changing this value to 0 and can't see a why to do it.  (I want my nav bar to merge seamlessly with my tabs)

**Comment by satya164** [comment]
The shadow is using `elevation` on Android and the `shadowX` properties on iOS, so you would want to pass `elevation: 0` or `shadowOpacity: 0` according to the platform.

**Comment by primalyeti** [comment]
@satya164 I'm testing in xcode, so ios, and even with the shadowOpacity: 0 set in the styles, i'm still seeing that shadow, super annoying!

**Comment by davidskaarup** [comment]
Are you refreshing your app after your header styling changes? In my experience hot reloading does not update the navigation styling.

**Comment by grabbou** [comment]
I have confirmed `shadowOpacity: 0` to work on iOS. Please make sure you are running latest version and that you have refreshed your app properly.

**Comment by lalaj** [comment]
Set  borderBottomWidth: 0
This worked for me.
