### ISSUE TITLE
Transitioning from route with tabbar displayed to the route without it

### ISSUE THREAD

**Issue by yuoppp** [react-community/react-navigation#2974]
### Current Behavior
I have tabnavigator with stacknavigators on it. The scheme looks like this:

Tab1: Stack1,
Tab2: Stack2

I'm hiding the tabnavigator when navigating deeper then level 1. But the transitioning looks bad. 
At first, the navigator disappears, then the content of the page resizes, because after the disappearance of the navigator empty space remained. Then we go to the next page

### Expected Behavior
The tabbar should hide without jumping. A good example is how Instagram does it. 

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.15
| react-native     | 0.45
| node             |  8.2.1
| npm or yarn      | 5.3.0

Both platforms: iOS and Android

**Comment by yuoppp** [comment]
Here is sample code

`/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 * @flow
 */

import React, { Component } from 'react';
import {
  Platform,
  StyleSheet,
  Text,
  View,
  TouchableOpacity
} from 'react-native';


import { StackNavigator, TabNavigator } from 'react-navigation';

class Screen1 extends Component {
	render() {
		return (
		<View style={styles.container}>
			<TouchableOpacity onPress={() => this.props.navigation.navigate('Screen2')}>
				<Text>Nav to screen2</Text>
			</TouchableOpacity>
		</View>)
	}
}
class Screen2 extends Component {
	render() {
		return <View><Text>Screen2</Text></View>
	}
}
class Screen3 extends Component {
	render() {
		return <View><Text>Screen3</Text></View>
	}
}
class Screen4 extends Component {
	render() {
		return <View><Text>Screen4</Text></View>
	}
}


const Stack1 = StackNavigator({
	Screen1: { 
		screen: Screen1,
	},
	Screen2: {
		screen: Screen2,
		navigationOptions: ({navigation}) => ({
			title: 'Screen2',
			tabBarVisible: false,
		})
	}
});

const Stack2 = StackNavigator({
	Screen3: { 
		screen: Screen3,
	},
	Screen4: {
		screen: Screen4,
		navigationOptions: ({navigation}) => ({
			title: 'Screen4',
			tabBarVisible: false,
		})
	}
});

const Tabs = TabNavigator({
	Tab1: {
		screen: Stack1,
		tabBarLabel: 'Tab1'
	},
	Tab2: {
		screen: Stack2,
		tabBarLabel: 'Tab2'
	}
});


const instructions = Platform.select({
  ios: 'Press Cmd+R to reload,\n' +
    'Cmd+D or shake for dev menu',
  android: 'Double tap R on your keyboard to reload,\n' +
    'Shake or press menu button for dev menu',
});

export default class App extends Component<{}> {
  render() {
    return (
      <Tabs/>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'green',
  },
});
`

**Comment by kelset** [comment]
Duplicate https://github.com/react-community/react-navigation/issues/2732
