### ISSUE TITLE
componentWillUnmount never called despite having to switch to another screen?

### ISSUE THREAD

**Issue by trisetianto** [react-community/react-navigation#298]

**Comment by agrcrobles** [comment]
I might be wrong but my understanding is that Components are not unmounting when switching to another screen instead you push screens in a router stack as you are dispatching actions to navigate.

In fact back button pops an element from the stack and that behavior will never be possible if the component has been unmounted.

**Comment by lslima91** [comment]
@trisetianto can you describe what is that you want to do?

**Comment by trisetianto** [comment]
@lslima91 this my explanation

I made a simple quiz game, in the game is given the time to answer all questions and remain time is showed on screen.

To calculate the time I use [react-native-timer](https://github.com/fractaltech/react-native-timer), I register function setInterval for updates remainTime in componentDidMount like this:

`timer.setInterval('timer', () => updateTimeRemain(startTime, 480), 1000)`

Then I clean all interval in componentWillUnmount for stop update state every second.

how do I do this if componentWillUnmount not called when switching to another screen?

thank for all respond

**Comment by lslima91** [comment]
@trisetianto I don't know if it's the best option, but you could use the properties onTransitionStart and onTransitionEnd from StackNavigator, to start and stop the global timer respectively.

**Comment by grabbou** [comment]
The OP is requesting focus/blur events just like in `ex-navigation` to be called on components as we transition. There's already open discussion for doing so in tabs. I'll join these two. #51

**Comment by dann1609** [comment]
I have this problem and it only happen when I'm using react. If I do not use redux. This call work without problem.

this is the way I made navigation reducer

`
export const navReducer = (state = initialState, action) => {
  //console.log('navReducer state: '+JSON.stringify(state));
  //console.log('navReducer action: '+JSON.stringify(action));

  const nextState = AppNavigator.router.getStateForAction(action, state);

  // Simply return the original `state` if `nextState` is null or undefined.
  if(state.routes[state.routes.length-1].routeName!=action.routeName){
    return nextState || state;
  }else{
    return state;
  }
};

`

**Comment by karunkumark** [comment]
componentWillUnmount not called even though navigating to the next screen why?
