### ISSUE TITLE
PropTypes/checkPropTypes has been moved to a separate package

### ISSUE THREAD

**Issue by hushicai** [react-community/react-navigation#2984]
I get some React Warnings when i upgrade react-navigation to 1.0.0-beta.19.
When I reset to 1.0.0-beta.15, everything become ok. Is there something wrong?

react-native: 0.47.2
babel-preset-react-native: 2.1.0
react-navigation: 1.0.0-beta.19

![image](https://user-images.githubusercontent.com/1249423/32872520-c13135f0-ca4c-11e7-9685-292f23b24cbf.png)

**Comment by hushicai** [comment]
I have found some similar issues, but there is not solution.

#2979 #2019

**Comment by kelset** [comment]
Literally just said to you to comment on #2019 to avoid redundancy (in #2979). I am closing this. Moreover you haven't followed the issue template.

**Comment by hushicai** [comment]
@kelset I have searched that indeed. but found nothing. I also wonder that why react warnings show after i upgrade to beta.19. is that happened in  some dependency package?
