### ISSUE TITLE
Feature Request : Ability to customise left and right header buttons

### ISSUE THREAD

**Issue by si-harps** [react-community/react-navigation#299]
It would be useful to be able to further customise the left and right header buttons. 

What do people think of the following suggestions...

Left (Back) header button : The ability to define a custom component (icon) to sit inside the back button whilst keeping the current functionality

Right header button : The ability to use navigation methods inside the navigationOptions static component class property to switch between screens on press (maybe this is already an option?)

**Comment by davidskaarup** [comment]
The last suggestion is already implemented. You can do this:

    static navigationOptions = {
      header: (navigation, header) => ({
        ...header,
        right: (
          <TouchableOpacity onPress={() => navigation.navigate('Settings')}>
            <Text>Settings</Text>
          </TouchableOpacity>
        )
      })
    }

**Comment by si-harps** [comment]
@davidskaarup your a legend, thanks for this!! :)

**Comment by Paul-Todd** [comment]
And if you want to link the button to your component:
``` javascript
    componentDidMount() {
        const params = {
            right: (
                <Button
                    onPress={() => { this.save(); }}
                    title={"Save"}
                />
            ),
        };
        
        this.props.navigation.setParams(params);
    }
```
Then in your navigation properties add:
```
MyScreen.navigationOptions = {
    title: 'Add',
    header: ({ state }) => {

       // we link through state.params.right
        return {
            right: (state.params && state.params.right)
        };
    }
};
```

**Comment by si-harps** [comment]
@Paul-Todd this is very useful. Thanks for posting. I'm starting to wish i could star this project twice :)

**Comment by cmrichards** [comment]
@Paul-Todd  This useful, thanks!, but it seems like a strange solution for something that should be easier to do

**Comment by Paul-Todd** [comment]
The other tip is how to hide tabs - took me a couple of posts here to figure out how to do it. 

We have:
tabnav->stacknav->view->leaf-view. 
HomeScreenNavigator -> DashboardNavigator -> DashboardScreen -> SettingScreen

The leaf-view (SettingsScreen) is the one we want to display full screen so we dont want tabs here.

The most important thing to note below is the props are merged from the settings screen to the tabnav and the tabBarProps parameter in the tabBar callback is spread using ... and then the fields are updated so the tabBar declaration in the settings screen (leaf-view above) is merged with the tabBar settings here and then returned.

TabNavigator
--------------

``` javascript
const HomeScreenNavigator = TabNavigator({
    dashboard: {
        screen: DashboardNavigator,
        navigationOptions: {
            title: "Dashboard",
            
            tabBar: (navigation, tabBarProps) => {
                return {
                    ...tabBarProps,
                    label: 'Dashboard',
                    icon: ({ tintColor, focused }) => {
                        return (
                            <FontAwesome
                                name={'tachometer'}
                                size={26}
                                style={{ color: tintColor }}
                            />);
                    	}
                	};
            	}
        	}
    	}
	});
```

StackNavigator
--------------

This needs a stack navigator with the root view to go into the tab and a settings view that does not want to have tabs visible.

``` javascript
const DashboardNavigator = StackNavigator({
    root: { screen: DashboardScreen },
    settings: { screen: SettingsScreen },
});
```

The view to go into the tab is DashboardScreen - clicking on the settings 
button in the header top right goes to the settings screen.

``` javascript
DashboardScreen.navigationOptions = {
    title: 'Dashboard',
    header: ({ navigate }) => {
        return {
            titleStyle: {
                color: Theme.lightText,
            
            },
            style: {
                backgroundColor: Theme.basis
            },
            right: (
                <Button
                    title={'Settings'}
                    onPress={() => {
                        navigate('settings');
                    }}
                />
            )
        };
    }
};
```

And finally the settings screen. We define here that we want to hide the tabbar.

Note the tabBar property in the navigationOptions below for the settings view but is propagated down to the HomeScreenNavigator

``` javascript
SettingScreen.navigationOptions = {
    title: 'Settings',
    header: {
        titleStyle: {
            color: Theme.lightText
        },
        style: {
            backgroundColor: Theme.basis
        },
    },
    tabBar: {
        visible: false
    }
};
```

**Comment by Kabangi** [comment]
Is it possible to hide the right button. I don't want to have the back button on some screens of my app. How do I implement this?

**Comment by grabbou** [comment]
@Kabangi just do `right: null` instead of `right: ''`.

As per the original request, I feel like defining a custom label is a responsibility for a custom left component one should set on `navigationOptions`. We are working on improving built-in look & feel to make it look as native as possible and so, I believe that `tintColor` is the only reasonable config that should be accepted for a default button.

Feel free to re-open if I misunderstood your original request :)

**Comment by sypl** [comment]
I too would like to only override the onPress behaviour. Having to create an entire react component that looks like that duck but doesn't behave like it seems overkill.

**Comment by brentvatne** [comment]
@mvanroon - that seems somewhat reasonable I think you'd find that isn't sufficient. it'd work for ios if you want to prevent someone from going back in certain circumstances, but then how do you block the hardware back button on android from preventing it?
