### ISSUE TITLE
SafeAreaView and SafeView do not stack correctly

### ISSUE THREAD

**Issue by mmerickel** [react-community/react-navigation#2991]
I wrapped my entire app in react-native 0.50's `SafeAreaView` and this is not playing nicely with the new `SafeView` in react-navigation (using 1.0.0-beta.19 right now). On 1.0.0-beta.15 (before `SafeView`) this was working fine by shifting my entire app including the navigation. Also it appears at native `SafeAreaView` nicely stacks with other `SafeAreaViews` to ensure that they have no effect unless the view actually intersects a safe area. The `SafeView` on the other hand is always applying a shift, causing the UI to be shifted down by 44 pixels leaving a giant gap at the top of the screen. I don't see a way to disable this right now and so I'm forced to stick with 1.0.0-beta.15.

**Comment by kelset** [comment]
Closing because you haven't followed the issue template; please open a new one that follows the template.
Moreover, I don't understand why you would need to have both `SafeAreaView` in place.

**Comment by unboundmusic** [comment]
I'm having this issue as well. @mmerickel did you figure out a solution?
