### ISSUE TITLE
1.0.0-beta.19 results in white screen

### ISSUE THREAD

**Issue by rajat1saxena** [react-community/react-navigation#3002]
## The issue list is reserved for bugs and feature requests, not for questions.

For usage questions, try to:

- [Read the docs](https://reactnavigation.org/)
- [Ask on the Reactiflux (#react-navigation)](https://discord.gg/reactiflux)
- [Look for / ask questions on StackOverflow](https://stackoverflow.com/questions/tagged/react-navigation)
- Search for your issue - it may have already been answered or even fixed in the development branch. However, if you find that an old, closed issue still persists in the latest version, you should open a new issue.

---

### Current Behavior
A blank white screen.
![unnamed](https://user-images.githubusercontent.com/821092/32994347-ec749d14-cd8b-11e7-8dd3-ed478d288426.png)

### Expected Behavior
It should render the StackNavigator.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.19
| react-native     | https://github.com/expo/react-native/archive/sdk-22.0.1.tar.gz
| node             | 8.5
| npm or yarn      | yarn

**Comment by vonovak** [comment]
Sorry, but we're no wizards :) We need a reproduction on Snack to be able to help.

**Comment by rajat1saxena** [comment]
Here is the snack:
https://snack.expo.io/@rajat1saxena/react-navigation-test

Please look into it. Thanks.

**Comment by vonovak** [comment]
this will fix it:

```js
export default class App extends Component {
  render() {
    const Screen = RootRouter();
    return (
       <Screen />
    );
  }
}
```
