### ISSUE TITLE
*1.0.0-beta.19* - React 16 warnings for React.PropTypes, react.createClass

### ISSUE THREAD

**Issue by stephenotalora** [react-community/react-navigation#3005]
### Current Behavior
- Using react navigation `"^1.0.0-beta.15"` installs `"1.0.0-beta.19"` as expected, however Dev tools now complain that `PropTypes` have been moved to `prop-types` and `React.createClass` has been deprecated.
- Is the library `@1.0.0-beta.19` using `React.PropTypes` and `React.createClass` directly? Because it shouldn't in **react.16.x.x**.
- Has this been changed since *1.0.0-beta-15*? I have since locked React Navigation to beta-15.
- Thoughts?

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.19
| react-native     |  "^0.48.4"
| node             | lts (8.8.1)
| npm or yarn      | yarn@1.2.1

**Comment by kelset** [comment]
Duplicate https://github.com/react-community/react-navigation/issues/2019#issuecomment-344848710
