### ISSUE TITLE
Prevent fade transitions

### ISSUE THREAD

**Issue by sun2rise** [react-community/react-navigation#3007]
### Current Behavior
A fade-in transition effect is applied in several parts of the navigator 

### Expected Behavior
I would like to prevent this transition effect and switch screen (or navigator, in the nested navigators case) without effect and in no time

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.19
| react-native     | 0.49.5
| node             | 8.9.1
| yarn      | 1.3.2

**Comment by kelset** [comment]
Duplicate https://github.com/react-community/react-navigation/issues/175

**Comment by sun2rise** [comment]
@kelset I'm sorry but this is not a duplicate: the issue you linked is about transition effects between different pages but what I'm talking about is the ugly fade-in effect you have on the very first screen of the app or every first screen of every stackNaviagtor inside a drawerNavigator
