### ISSUE TITLE
Docs: How to livesync when developing locally?

### ISSUE THREAD

**Issue by pavloko** [react-community/react-navigation#3012]
I was wondering how do main contributors to this library develop locally?

I searched documentation and couldn't find a clear way how to setup a development workflow.

What I'd like to have:
1. I run an example app in examples folder.
2. I make changes to the code in `src`, for example `TabView/TabBarIcon.js`. 
3. I get the changes synced in the emulator.

What I've tried/have in mind:
1. `npm link, npm link react-native-elements` --> doesn't work with React Native.
2. making changes in `example/node_modules`. Not ideal if you're making lots of changes in different files.
3. Another option might be setting up storybook.

I'm not sure how critical this is, but maybe it would be nice to have a few things about it in the CONTRIBUTING.md.

Thanks and I really appreciate your input on this.

**Comment by vonovak** [comment]
I personally have a testing app which is packed using haul, which supports `npm link`, if that answers the question.

**Comment by pavloko** [comment]
Cool idea. Do you think there is a place for a tiny guide in the docs?

**Comment by kelset** [comment]
@pavloko check also this issue: https://github.com/react-community/react-navigation/issues/2879

If you want to submit a PR feel free to do so, we'll try to review it asap.

Going to close this since it's not an issue nor a feature request.
