### ISSUE TITLE
Unsupported top level event type "topScrollBeginDrag" dispatched

### ISSUE THREAD

**Issue by qinfensky** [react-community/react-navigation#3016]
software-version:
"react-native": "0.50.3",
"react-navigation": "^1.0.0-beta.11",
I slip on the tabbar, and there's an error. This is just the case on Android.

![s71121-093153](https://user-images.githubusercontent.com/7803520/33050785-aa51f302-cea1-11e7-893f-a9fe76cfc8e9.jpg)

**Comment by kelset** [comment]
This is a RN issue: https://github.com/facebook/react-native/issues/16522#issuecomment-345901857
