### ISSUE TITLE
how to Reset TabNavigation with initRouterName

### ISSUE THREAD

**Issue by darin-lao** [react-community/react-navigation#3017]
```
const TabStack = TabNavigator(
    {
        TabA: {screen: TabA},
        TabB: {screen: TabB},
     }
);

const AppStack = StackNavigator(
    {
        Tab: {
            screen: TabStack ,
        },
        PageA: {
            screen: PageA,
        },
        PageB: {
            screen: PageB,
        },
        PageC: {
            screen: PageC,
        },


    },{
        initialRouteName:"Tab"
    }
);
```
first time screen init TabA ,user click TabB >> TabB has button click to PageA >>  PageB >>  PageC ,PageC has a button to reset to Tab.

```
let resetAction = NavigationActions.reset({
            index: 0,
            actions: [
                NavigationActions.init({routeName: 'Tab'}),
            ]
        });
this.props.navigation.dispatch(resetAction);
```

how to reset to Tab init with TabB,is anyone due this question?

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.13
| react-native     | 0.44.3
| node             | 
| npm or yarn      |

**Comment by Mullvinn** [comment]
I have the same question.

**Comment by kelset** [comment]
Refer to https://github.com/react-community/react-navigation/issues/1715
