### ISSUE TITLE
[Beta 20]: headerLeft: null no longer works

### ISSUE THREAD

**Issue by joncursi** [react-community/react-navigation#3019]
I have certain screens that I don't want to show a back button on. So I've been using `headerLeft: null` in the navigation options.

This no longer has an effect in Beta 20; the back arrows are still showing on screens that use the above code to turn them off.

**Comment by vonovak** [comment]
@joncursi thanks for reporting, a PR with the fix is available, I expect it to be merged and released soon. In the meantime, you can use the current master.

**Comment by kelset** [comment]
@joncursi can you test @vonovak's PR, if it fixes for you I'll approve and merge asap.

**Comment by spencercarli** [comment]
Fixed and released in beta.21! Thanks for reporting.
