### ISSUE TITLE
Example showcasing a change of scene with a computationally heavy operation

### ISSUE THREAD

**Issue by lslima91** [react-community/react-navigation#302]
Hi,
Simple example showing what happens if you do a heavy operation at the start of a transition, vs waiting for the transition to end, and then do the operation.

https://github.com/lslima91/react-navigation/blob/Deferred-Rendering/examples/NavigationPlayground/js/DeferredRendering.js

Hopefully this is useful for someone.

This was inspired by https://github.com/brentvatne/run-after-interactions-exp/blob/master/main.js

**Comment by grabbou** [comment]
Thanks for doing that! Do you think that it should be a part of documentation? Is it any different from the existing perf documentation in React Native?

**Comment by satya164** [comment]
https://facebook.github.io/react-native/docs/performance.html

**Comment by lslima91** [comment]
I think it's enough to close the issue. The perf docs do a good job of explaining it.
