### ISSUE TITLE
Crash on tab

### ISSUE THREAD

**Issue by adhicl** [react-community/react-navigation#3023]
### Current Behavior
Hi, I have not changed my code for more than a month and all of a sudden this behavior pops up and depressed me. When I click on tab it will immediately give this error:
![bug-react-navigation](https://user-images.githubusercontent.com/2452628/33072711-223fbe70-cef3-11e7-8771-8adb4dbc90ca.png)
The message pops up after I update the expo from 22 to 23 but even after I re-roll back to expo 22 the bugs now keeps on showing up.
I have made a simple code for this:
https://snack.expo.io/r1-tj5ZxG

### Expected Behavior
- bug show up when click on a tab.
- should just change to the tab

### MyEnvironment
"dependencies": {
        "expo": "^23.0.0",
        "react": "16.0.0",
        "react-native": "^0.50.3",
        "react-navigation": "^1.0.0-beta.20",
        "react-redux": "^5.0.6",
        "redux": "^3.7.2",
        "redux-thunk": "^2.2.0"
    }

Thanks for anyone helping

**Comment by valinaga** [comment]
same as #3020

**Comment by kelset** [comment]
Closing in favor of #3020
