### ISSUE TITLE
升级到最新出现问题导航变高

### ISSUE THREAD

**Issue by PeterLocas** [react-community/react-navigation#3028]
升级到最新出现问题导航变高
Tab被挤压

![image](https://user-images.githubusercontent.com/5467858/33124432-95b0cf1c-cf42-11e7-857b-f80a98cf05ac.png)

**Comment by kelset** [comment]
Duplicate https://github.com/react-community/react-navigation/issues/2805
(I guess - can't understand Japanese)

**Comment by guoliang1206** [comment]
@kelset Chinese
