### ISSUE TITLE
Can't run example on Android

### ISSUE THREAD

**Issue by ddeanto** [react-community/react-navigation#304]
I cloned this repo locally, and ran `npm install` in `/react-navigation/examples/HelloHybrid`. Then ran `react-native run-android` while still in `/react-navigation/examples/HelloHybrid` and the following error is displayed on my emulator:

<img width="344" alt="screen shot 2017-02-11 at 3 57 07 pm" src="https://cloud.githubusercontent.com/assets/8404695/22857429/ce912a70-f072-11e6-9509-bc6359875c58.png">

**Comment by lslima91** [comment]
@ddeanto did you run npm install in the root directory "react-navigation"

**Comment by Steviey** [comment]
@ddeanto 
Since the example installs are currently not cross-platform, it is important that you mention the OS you are working on. 
Related: https://github.com/react-community/react-navigation/issues/75

**Comment by agrcrobles** [comment]
So as they said in the [README.md](https://github.com/react-community/react-navigation/tree/master/examples/HelloHybrid)

> iOS only right now. Help needed to support Android!

I have already created #155 to see if could make it work but I deserted.

I did a couple of gist, [HybridNavigationPackager.java](https://gist.github.com/agrcrobles/8906160304d2055bfa09c26079ed5a0c) and [HybridNavigationManager.java](https://gist.github.com/agrcrobles/8906160304d2055bfa09c26079ed5a0c) in case someone is also interested on that as I am!

**Comment by agrcrobles** [comment]
So as they said in the [README.md](https://github.com/react-community/react-navigation/tree/master/examples/HelloHybrid)

> iOS only right now. Help needed to support Android!

I have already created #155 to see if could make it work but I deserted.

I did a couple of gist, [HybridNavigationPackager.java](https://gist.github.com/agrcrobles/f8702b8ea2a10b6fd79bb0a5a967c7d7) and [HybridNavigationManager.java](https://gist.github.com/agrcrobles/8906160304d2055bfa09c26079ed5a0c) in case someone is also interested on that as I am!

**Comment by ddeanto** [comment]
I am closing this because it is already documented that `examples/HelloHybrid` still needs Android support. Also, I re-cloned this repo, and followed the instructions for  different example: `examples/NavigationPlayground` - which is now working for me on Android. Everybody else  please remember to also `npm install` in the root directory to run the examples!
