### ISSUE TITLE
Can't create redux connected component with TabNavigator

### ISSUE THREAD

**Issue by DavideValdo** [react-community/react-navigation#3040]
After login, when `App`'s `render()` returns the TabNavigator, I'm getting a red error.

Thing is, the same exact technique is working in a project with react-native 0.49.3
Maybe I'm missing something? Should I necessarily create navigation reducer?

EntryPoint.js

```
import React from 'react'

import { createStore, applyMiddleware } from 'redux';
import { Provider } from 'react-redux'
import thunk from 'redux-thunk';
import logger from 'redux-logger';

import { registerAuthStateListener } from './actions/auth.js'
import { fetchWishes } from './actions/wishes.js'
import PACKED_REDUCERS from './reducers/Index.js'

import App from './App.js'

store = createStore(PACKED_REDUCERS, applyMiddleware(thunk, logger));
store.dispatch(registerAuthStateListener())
store.dispatch(fetchWishes())

export default class EntryPoint extends React.Component {
    render () {
        return (
            <Provider store={store}>
                <App />
            </Provider>
        )
    }
}
```

App.js

```
import React, { Component } from 'react'
import { 
    TabNavigator,
    StackNavigator
} from 'react-navigation';
import { connect } from 'react-redux'

import Login from './Login.js'
import WishesDashboard from './WishesDashboard.js'
import Home from './Home.js'

const MAIN_TABS_OPTIONS = {
    tabBarPosition: 'bottom',
    swipeEnabled: false,
    animationEnabled: false
}

class App extends Component {
    render () {
        const { AUTH } = this.props

        const MainNavigator = StackNavigator({
            Index: {
                screen: TabNavigator({
                    Home: {
                        screen: Home
                    },
                    Desideri: {
                        screen: WishesDashboard
                    }
                }, MAIN_TABS_OPTIONS)
            }
        }, {
            initialRouteName: 'Index'
        })

        if (AUTH.user)
            return (<MainNavigator />)
        else
            return (<Login />)
    }
}

export default connect(
    (state) => {
        return {
            AUTH: state.auth
        }
    }
)(App)

```
---

### Current Behavior
Getting red error **<<You must pass a component to the function returned by connect. Instead received {"navigation": {"state": {"key": "Desideri", "routeName": "Desideri"}}}>>**

### Expected Behavior
TabNavigator gets rendered

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.14
| react-native     | 0.48.4
| node             | 8.7
| npm or yarn      | yarn 2.1

**Comment by kelset** [comment]
1. have you tried updating to the latest release?
1. does it happen only on Android/iOS?
1. does it happen on both Debug and Release modes?
1. does it happen with Debugger On or Off? Both?
1. Can you provide a GIF or a repo or a snack to reproduce this issue?

I think simply you haven't properly wired redux, please make sure you have it set up properly: [our docs](https://reactnavigation.org/docs/guides/redux), [redux docs](https://redux.js.org/docs/basics/ExampleTodoList.html)

**Comment by DavideValdo** [comment]
Problem was in my **WishesDashboard** component, I wasn't correctly passing the component to it's own connect() call.

Thanks @kelset and sorry about this
