### ISSUE TITLE
Jest: TypeError: Cannot read property 'Constants' of undefined

### ISSUE THREAD

**Issue by mschipperheyn** [react-community/react-navigation#3049]
Getting this vague error running a Jest test (not even including anything react-native)

```
TypeError: Cannot read property 'Constants' of undefined
      
      at Object.<anonymous> (node_modules/react-native/Libraries/Components/DrawerAndroid/DrawerLayoutAndroid.android.js:25:47)
      at Object.get DrawerLayoutAndroid [as DrawerLayoutAndroid] (node_modules/react-native/Libraries/react-native/react-native-implementation.js:25:34)
      at Object.<anonymous> (node_modules/react-native-drawer-layout-polyfill/dist/index.android.js:1:229)
      at Object.<anonymous> (node_modules/react-navigation/src/views/Drawer/DrawerView.js:5:38)

```
### Current Behavior
It generates this error. Not even testing anything specifically react-native or react-navigation.

### Expected Behavior
Not this.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.21
| react-native     | 0.49.5
| node             | 08.5
| npm or yarn      | yarn

**Comment by kelset** [comment]
> Not even testing anything specifically react-native or react-navigation.

So what are you using Jest for? 🤔

Anyway it looks like it's related to [`react-native-drawer-layout-polyfill`](https://github.com/react-native-community/react-native-drawer-layout-polyfill), and that he released a new 2.0.0 version less than 20 days ago.

Maybe updating it will fix it? We'll need to do a PR for that.

**Comment by peterlandry** [comment]
I'm also running into this error, and updating to 2.0.0 for `react-native-drawer-layout-polyfill` doesn't seem to help.

**Comment by peterlandry** [comment]
A clue: this only occurs for me when `jest.haste.defaultPlatform` is set to `android`

**Comment by peterlandry** [comment]
I think this can be closed here. I can reproduce this without `react-navigation` from a cleanly created `react-native` app by setting the `defaultPlatform` to android. I'm going to file a bug report in react-native proper.

cc @kelset

**Comment by kelset** [comment]
Thanks for reporting @peterlandry
