### ISSUE TITLE
Using with SafeAreaView

### ISSUE THREAD

**Issue by ahmetcetin** [react-community/react-navigation#3055]
I'm trying to use react navigation with SafeAreaView to cover iPhoneX layout. Basically, render of my App.js is as follows:

```  
render() {
  <Provider store={store}>
    <PersistGate loading={<Loading />} persistor={persistor}>
      <View
        style={{ backgroundColor: "darkslategrey", height: height || Constants.statusBarHeight }}
      >
        <StatusBar barStyle="light-content" />
      </View>
      <SafeAreaView style={styles.container}>
        <Navigation />
      </SafeAreaView>
    </PersistGate>
   </Provider>
}
```
And the Navigation is as follows:
```
const MainNavigation = StackNavigator({
  Home: {
    screen: Home,
  },
  Area: {
    screen: Area,
  },
  Result: {
    screen: Result,
    navigationOptions: {
      title: 'Result',
    },
  },
});

const TabNavigation = TabNavigator(
  {
    Find: {
      screen: MainNavigation,
      navigationOptions: {
        tabBarLabel: 'Home',
        tabBarIcon: ({ tintColor, focused }) => (
          <Icon name="open-book" size={26} style={{ color: tintColor }} />
        ),
      },
    },
    Stats: {
      screen: ParamsToPropsWrapper(Stats),
      navigationOptions: {
        tabBarLabel: 'Stats',
        tabBarIcon: ({ tintColor, focused }) => (
          <Icon name="area-graph" size={26} style={{ color: tintColor }} />
        ),
      },
    },
  },
  {
    tabBarPosition: 'bottom',
    lazy: true,
    animationEnabled: true,
  }
);

export default TabNavigation;
```
Please pay attention that Navigation component is inside the SafeAreaView, otherwise when you rotate screen right, front camera notch is covering the layout.

### Current Behavior
- Margin between iphonex bottom handle and the tab is quite big
- Icon and the text is not centered vertically, it's on top of tab.

<img width="434" alt="iphone_x_-_ios_11_1_and_new_issue_ _react-community_react-navigation_and_slack_-_wavebreak_media" src="https://user-images.githubusercontent.com/5046786/33335038-2741ec4e-d46c-11e7-909c-b05d78f68992.png">

### Expected Behavior
- To cover the screen fully, or having less margin at the bottom when it's inside SafeAreaView
- Icon and Text is centered vertically

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.19
| react-native     | 0.50.3
| node             | 8.2.1
| yarn      | 1.3.2

**Comment by davepack** [comment]
React Navigation components such as header, tabbar, and drawer already use SafeAreaView, so you don't need to wrap the navigation in a SafeAreaView. You would want to wrap screens inside your navigation with a SafeAreaView instead.

**Comment by ahmetcetin** [comment]
Thx @davepack, indeed when i put only the content in SafeAreaView, it solved the problem of the margin. But still problem of not vertically centered icon & text exists. see the attached screenshot.
<img width="417" alt="iphone_x_-_ios_11_1_and_using_with_safeareaview_ _issue__3055_ _react-community_react-navigation" src="https://user-images.githubusercontent.com/5046786/33370778-d615725e-d4f8-11e7-9091-a69767854ae7.png">

**Comment by kelset** [comment]
@ahmetcetin It seems like this other issue is actually this one https://github.com/react-community/react-navigation/issues/2805

so I suggest you close this issue and report there to keep the conversation all in the same place.

**Comment by jose920405** [comment]
Hi @davepack ,

I am presenting the same problem.

In my case I also have `SafeAreaView` and` TabNavigator`. But if I need to have the `SafeAreaView` because my application has no header and I need my components to respect the top space.

**Comment by davepack** [comment]
Wrap the content of your screen with SafeAreaView, don't wrap the TabNavigator or the entire app with SafeAreaView.

**Comment by nthgol** [comment]
@davepack  this is not a good solution, it will cause jumping on rendering when moving between screens

**Comment by davepack** [comment]
Using forceInset will prevent jumping. Putting SafeAreaView at the root is not a good option in most cases.
