### ISSUE TITLE
HeaderRight button is slow to display with StackNavigator

### ISSUE THREAD

**Issue by jkbreunig** [react-community/react-navigation#3067]
### Current Behavior
HeaderRight button is slow to display with StackNavigator when navigating to a screen. When navigating to a screen, header title, back button and screen content renders immediately but there's a second delay before right button displays.

class StackNavigatorScreen extends Component<any, any> {
    static navigationOptions = ({ navigation, screenProps }) => {
        const { params = {} } = navigation.state
        return {
            headerTitle: 'Title',
            headerRight: <EditButton handlePress={() => params.handleEditButtonPressed()} />
        }
    }

### Expected Behavior
HeaderRight button should display immediately when navigating to a screen.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.21
| react-native     | 0.50.4
| node             | 8.9.1
| npm or yarn      | 5.5.1

**Comment by kelset** [comment]
Read [the documentation](https://reactnavigation.org/docs/intro/headers#Header-interaction-with-screen-component), please. In particular, the `Note` after the code snippet.
