### ISSUE TITLE
Reset/go to to parent router

### ISSUE THREAD

**Issue by primalyeti** [react-community/react-navigation#307]
Right now, if I push into a Navigator, i'm unable to access the parent. Would be sweet if this could be updated.

Ex:

```
const AppNavigator = StackNavigator({......});
const AuthNavigator = StackNavigator({.....});
const RootNavigator = StackNavigator({
	init: {
		screen: RootContainer
	},
	auth: {
		screen: AuthNavigator
	},
	app: {
		screen: AppNavigator
	}
}, {
	initialRouteName: 'init',
	headerMode: 'screen',
});
```

If i push into auth, im stuck in there. Only workaround i've found so far is to put everything on the same "level"

Thanks!

**Comment by lslima91** [comment]
@primalyeti This is already implemented, what happens when you dispatch a back action?

**Comment by ericvicenti** [comment]
What do you mean by "access the parent"? That isn't generally something you can do.

You can dispatch a back action to get out of the deep navigator. If something is wrong with the behavior of the routers/navigators, could you write a test case that demonstrates the problem, and open a new issue? Just follow the contributors guide on the website to run the tests, and it should be pretty easy to copy an existing test and change it to show the problem.

**Comment by dazziola** [comment]
I think I know what @primalyeti was alluding to, as I'm experiencing the same issue here. I'll try to explain it best I can:

    const TutorialNavigator = StackNavigator({
      Tutorial: { screen: TutorialScene }
    },{
      headerMode: "none"
    });
    
    const MainNavigator = StackNavigator({
      Dashboard: { screen: DashboardScene },
      Profile: { screen: ProfileScene }
    });
    
    export const AppNavigator = StackNavigator(
      {
        TutorialScene: { screen: TutorialNavigator },
        MainScene: { screen: MainNavigator }
      },
      {
        headerMode: "none"
      }
    );
    
    class Navigation extends Component {
      render() {
        return(
          <AppNavigator />
        )
      }
    }

Above is my rudimentary Navigator component. The flow starts off as expected, I see my TutorialScene component via my TutorialNavigator stack. All is right with the world.

However, in my TutorialScene component, I navigate to MainScene using:
    this.props.navigation.navigate("MainScene")

This brings me to my MainNavigator stack, and all seems well. But what if I want to revert to my tutorials page from anywhere in the MainScene stack?

I've attempted to set the correct this.props.navigation object in Redux, but even when using that, it treats it as if it were from the navigator of the current stack (which is a sub-stack of MainScene stack, its parent).

It seems as though I can navigate _to_  a different stack, but not _from_ a substack. Any clarity would be great as the docs don't explain it past reseting the current stack navigator.
