### ISSUE TITLE
SafeAreaView missing bottom padding on screens

### ISSUE THREAD

**Issue by jamsesso** [react-community/react-navigation#3072]
### Current Behavior

When I define a simple screen (in this case, `LockScreen`), the `SafeAreaView` (provided by react-navigation) appears to be missing bottom padding. This can be seen by the fact that the button is visually too close to the bottom of the screen.

<img width="545" alt="screen shot 2017-12-03 at 5 54 29 pm" src="https://user-images.githubusercontent.com/107810/33530293-cc320d52-d853-11e7-808c-4b93fa6f2105.png">

```
import React, {Component} from 'react';
import {connect} from 'react-redux';
import {View, Text, StyleSheet} from 'react-native';
import Icon from 'react-native-vector-icons/FontAwesome';

import Button from '../components/Button';
import LoadingMessage from '../components/LoadingMessage';

@connect()
class LockScreen extends Component {
  static navigationOptions = {
    title: 'Locked'
  };

  state = {
    loading: false
  };
  
  /* Event handlers removed for brevity */

  render() {
    if(this.state.loading) {
      return <LoadingMessage message="Trying to login..." />;
    }

    return (
      <View style={styles.container}>
        <View style={styles.messageContainer}>
          <View style={styles.icon}>
            <Icon name="lock" size={60} color="#aaa" />
          </View>
          <View style={styles.message}>
            <Text style={styles.text}>You're logged in to Agyle on another mobile device. Before you can continue, you will need to logout from the other device.</Text>
            <Text style={styles.text}>Can't logout from the other device? Call your Agyle account manager for assistance.</Text>
          </View>
        </View>
        <View style={styles.button}>
          <Button title="OK, I've logged out. Try again" onPress={this.handleTryAgain.bind(this)} />
        </View>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1
  },
  messageContainer: {
    flex: 1,
    flexDirection: 'row',
    padding: 12
  },
  icon: {
    width: 80,
    alignItems: 'center'
  },
  message: {
    flex: 1
  },
  text: {
    fontSize: 16,
    marginBottom: 10
  },
  button: {
    padding: 12,
    borderTopWidth: 1,
    borderTopColor: '#ccc'
  }
})

export default LockScreen;
```

### Expected Behavior

If I use `SafeAreaView` provided by react-navigation outside of a screen, it appears to behave correctly. In the following screenshot, the blue `View` does not reach the bottom of the display. I would expect the button on my screen above to be "pushed up" by this amount of padding as well.

<img width="545" alt="screen shot 2017-12-03 at 5 55 44 pm" src="https://user-images.githubusercontent.com/107810/33530301-fc782172-d853-11e7-96e8-a8a2e963a501.png">

```
import React, {Component} from 'react';
import {View} from 'react-native';
import {Provider} from 'react-redux';
import {SafeAreaView} from 'react-navigation';

import ReduxNavigator from './ReduxNavigator';

class App extends Component {
  render() {
    // Instead of rendering the app inside of a react-navigation screen, just use SafeAreaView directly.
    /*return (
      <Provider store={...}>
        <ReduxNavigator />
      </Provider>
    );*/

    return (
      <SafeAreaView style={{flex: 1}}>
        <View style={{flex: 1, backgroundColor: 'blue'}} />
      </SafeAreaView>
    );
  }
}

export default App;
```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.21
| react-native     | 0.50.3
| node             | 8.1.3
| npm or yarn      | 5.5.1

**Comment by kelset** [comment]
Thanks for reporting, pinging @spencercarli & @davepack which have more exp in SafeArea/Layout in iOS issues.

(maybe related to https://github.com/react-community/react-navigation/issues/2805 ? )

**Comment by davepack** [comment]
The layout measuring that SafeAreaView uses is inaccurate. In general, if you know an edge of the view will touch the edge of the device, add `forceInset={{ [edge]: 'always' }}` e.g. `forceInset={{ top: 'always', horizontal: 'never' }}`. This is documented [here](https://github.com/react-community/react-native-safe-area-view#forceinset), I apologize it is not in the react navigation documentation yet.

**Comment by jamsesso** [comment]
@davepack Thank you. For others: I was able to fix this as simply as wrapping my screen contents in `SafeAreaView`. I had the false impression that react-navigation's `SafeAreaView` would handle it (perhaps they're setting `forceInset={{bottom: 'never'}}` somewhere in the stack navigator?)

I'll leave this open for now as I think it may still be an issue that users have to wrap screens in `SafeAreaView`s themselves. If not, this can be closed.

**Comment by davepack** [comment]
@jamsesso I apologize, I didn’t understand your question at first. The solution you came up with is the correct one. React navigation does not automatically wrap screens with SafeAreaView, developers are required to add it to their screens as needed. In many use cases wrapping the screen in a SafeAreaView is not appropriate, such as for lists and scrollviews. Sorry for the confusion!
