### ISSUE TITLE
Navigation issue with a new navigator inside a navigator

### ISSUE THREAD

**Issue by tomleeshihhung** [react-community/react-navigation#3073]
My navigation structure is like this:

Main TabNavigator
    Home
    User
    Goals

but inside the 'Goals' screen, I have created another <TabNavigator> within it. 
This is because I wish for only the lower portion of Goals screen to navigate, not the entire screen.

Goals TabNavigator
    Nutrition
    Sleep
    Exercise

I wish for a button in Nutrition to navigate the whole screen to User ( in the parent navigator).
How would I go about this?  I assume it involves passing this.props.navigation from the parent navigator down to Goals, but I have no clue how to do it.

I tried to pass a prop like this  `<TabNavigator parent={this.props.navigation} />`
but then I don't know how I can access that parent prop in my Nutrition screen.

I'm fairly new so my terminology may be off here..thanks guys!

**Comment by tomleeshihhung** [comment]
Problem solved.

I passed 'this.props.navigation' through redux and accessed it in Nutrition.

**Comment by amyliu1062** [comment]
i have same problem, if i don`t use redux， how i do?
