### ISSUE TITLE
The link in document 'example' was 404

### ISSUE THREAD

**Issue by zxhycxq** [react-community/react-navigation#3078]
https://github.com/react-community/react-navigation/tree/master/examples/NavigationPlayground

>  see the [Contributors Guide](url) for instructions on running these example apps.

`Contributors Guide` 404

![image](https://user-images.githubusercontent.com/11674203/33586108-9d2ed986-d9a2-11e7-8620-56698ffdfd54.png)

**Comment by kelset** [comment]
Thanks for reporting, here's the doc: https://reactnavigation.org/docs/guides/contributors

**Comment by zxhycxq** [comment]
thanks！
