### ISSUE TITLE
Create Custom Animate between Screens

### ISSUE THREAD

**Issue by Kottidev** [react-community/react-navigation#308]
I need create Custom Animate .

i found this documentation but i think it's wrong 

https://github.com/react-community/react-navigation/blob/aead8ff9fbd2aceb2d06c8049c8ad0d55d77b5ab/docs/api/views/Transitioner.md

Transitioner need props navigation 

    navigation: PropTypes.shape({
      state: NavigationPropTypes.navigationState.isRequired,
    }).isRequired,

Anyone can  help me 
Thanks

**Comment by ericvicenti** [comment]
You're right it looks like the docs are out of date on this. Would you mind submitting a pull request to fix them?

Custom animations are possible now, but we may be able to improve the API. Feel free to open issues if you have suggestions. Right now, you can implement your own card stack, but hopefully we will eventually make it easier to customize the behavior of CardStack

**Comment by Kottidev** [comment]
@ericvicenti 

to create custom animate we need use cardStack ?

`
navigationOptions = {
  cardStack: {
    transition: (previousRoute: Route) => {
      // configure the animation here
    }
  },
}
`

**Comment by grabbou** [comment]
I am closing this in favor of #124
