### ISSUE TITLE
TabNavigator How to Hide certain tabs based on user access

### ISSUE THREAD

**Issue by fahadhaq** [react-community/react-navigation#3082]
I am using TabNavigator to display some tabs in my app but is there a  way I can show/hide some tab option? The reason I ask is that the users  have access to different areas of the app. Some have access to all 5  tabs and some only have access to 3. so if a user with access to 3 tabs  only is there a way to hide the other two?  here is an image of what I am trying to achieve.

User 1 access

![image1](https://user-images.githubusercontent.com/2104888/33645057-bdff6502-daad-11e7-9bcd-979b083cf4b6.png)

user 2 access
![image2](https://user-images.githubusercontent.com/2104888/33645062-c19be316-daad-11e7-830f-f5b514045af1.png)

Is there a way to achive this using tabNavigator. Any help would be greatly appreciated

**Comment by kelset** [comment]
https://github.com/react-community/react-navigation/issues/717
