### ISSUE TITLE
[Android] Fade up transitions between screens not silky smooth

### ISSUE THREAD

**Issue by cmrichards** [react-community/react-navigation#309]
On Android :
When I add a new screen to the stack (Stack navigator), the fade up animation for the new screen doesn't feel 60fps smooth. It's bearable, but you can see a slight jerkyness.  It does the same when using goBack so it's not due to fetching data or other processing I'm doing.

 I'm running a released apk on my Google Pixel XL phone - so no slow coach.

Is this to be expected or is there something in my app that I must be doing wrong?

**Comment by lslima91** [comment]
@cmrichards do you have any console log in your code?

**Comment by cmrichards** [comment]
I might use it in 2 or 3 places, but not extensively

**Comment by lslima91** [comment]
Use the perf monitor to see if your js thread is dropping fps. Logs are most of the time the reason.

**Comment by cmrichards** [comment]
According to the perf monitor on genymotion, 4 frames are dropped when I goBack from one screen to another.  This doesn't seem enough to account for the jerkyness of the screen transition.  On the device you would expect this to improve.

**Comment by lslima91** [comment]
Try the examples in the playground. Do you have some kind of redux logger?

**Comment by JimmyDaddy** [comment]
I got the same problem, and I disabled all loggers

**Comment by Maxim-Chuhno** [comment]
same issue. on IOS all transitions ~60 fps,  but on android ~15-25fps and if connect to chrome debugger it much better 30-40fps... console logs disabled.

**Comment by JimmyDaddy** [comment]
I solve my problem by unbinding the navigation reducer from my HOME page witch contains a large list. The reason of my problem is every time I navigate it will update my HOME page then make the translation between every screens slow.

**Comment by spencercarli** [comment]
If this is still an issue please re-open. Quick suggestion for anyone coming to this - make sure you're not doing any expensive operations in componentWillMount, it can negatively affect perf
