### ISSUE TITLE
Adding new screens to navigation while app is running

### ISSUE THREAD

**Issue by ttraenkler** [react-community/react-navigation#310]
Is it possible to add new screens to e.g. the StackNavigator while the app is running? I would like to  while the app is already running and using the StackNavigator is showing the first screen mount the second screen dynamically - so not all screens have to be known and loaded at the start of the application.

**Comment by satya164** [comment]
> so not all screens have to be known

How do you later load a screen if you don't know what's it gonna be?

> and loaded at the start of the application

All screens aren't rendered at the start of the application

**Comment by ttraenkler** [comment]
> How do you later load a screen if you don't know what's it gonna be?

It could for example be generated from data fetched over the network - e.g. imagine each node of a graph as a screen with routes that allow to navigate to the incoming and outgoing edges.

> All screens aren't rendered at the start of the application

Yes, but the screen routes and content would have to be known at "compile time"?

**Comment by satya164** [comment]
> Yes, but the screen routes and content would have to be known at "compile time"?

Screens have to be known statically. You can load whatever content you want.

> It could for example be generated from data fetched over the network - e.g. imagine each node of a graph as a screen with routes that allow to navigate to the incoming and outgoing edges.

You'll still have a screen coded that would show the data. So you always know about all screens and will be able to specify the screen in advance. Just fetch the data when the user navigates to the screen and pass an id or something in params to tell it how to fetch the data.

**Comment by ttraenkler** [comment]
> Screens have to be known statically. You can load whatever content you want.

Thanks for the clarification. So I cannot add screens to an existing StackNavigator. Am I right to assume I could also not replace the whole StackNavigator object with new routes while the app is not showing one of its routes? If so then I assume the only option left is to add placeholder screens - let's say 100 blank screens and fill in the content dynamically?

**Comment by satya164** [comment]
> Am I right to assume I could also not replace the whole StackNavigator object with new routes

I'm not sure what you mean by replacing stacknavigator with new routes

> If so then I assume the only option left is to add placeholder screens - let's say 100 blank screens 

Hmm... Why would you need 100 blank screens? Each screen represents the kind of data you show, for example I have a `Profile` screen, a `Settings` screen etc. Then that `Profile` screen can be profile screen of `satya164`, or profile of `ttraenkler` etc. which you'll pass via params.

A screen is a like component. You don't have 100s of blank components. You have one component to show some specific data in a specific format and you pass the data as props or fetch the data in `componentDidMount`

**Comment by ttraenkler** [comment]
Indeed it's quite a specific use case, so I will close the issue. Thanks nevertheless for the swift response!

**Comment by hose314** [comment]
@ttraenkler it's not specific actually. I've encountered the same issue. Image that you have two different users and you want to specify different behavior for certain tab and accosted `StackNavigator`.

```js
const main = TabNavigator({
  profile: { screen: isExperimentUser ? StackForExperiment : UsualStack }
})
```
it's will be awesome if we can do something like this (an ad hoc idea):
```js
class SplashScreen extends Component {
  componentWillMount() {
    this.props.navigation.replace('profile', isExperimentUser)
  }
}
```

**Comment by satya164** [comment]
Pass some params and render the correct component according to params.

**Comment by sckoh** [comment]
@satya164 
what if I have 2 TabNavigator

`
const main = StackNavigator({
  profile: { screen: isExperimentUser ? ExperimentTabNavigator : UsualTabNavigator }
})
`

I tried to use some props in a single Screen and return TabNavigator in the Screen render method.
However, it is not working. It is showing error of my Screen is not returning a valid React element.

**Comment by kelset** [comment]
Tbh I'm facing a similar issue: I have a TabNavigator but the number of tabs shown maybe change, based on an array which I parse from a server. So if the array length is 4, I need to show 4 tabs, if long 5 show 5 screens, etc.
Any idea of how handle it?

Does something similar to `NavigatorTab.router.push({newTab: {screen: newTab}})` exists ?

**Comment by lukasbalaz** [comment]
+1

**Comment by pekka** [comment]
I have the same problem. I'm loading a tree structure from a JSON file. Each item in the tree represents a screen. This seems very, very difficult to build without the ability to push new screens to the Navigator during runtime.

**Comment by Selman555** [comment]
Bump... stuck at this as well

```
    const Tabs = TabNavigator({
        Start: {
            screen: UserStackNavigator,
            navigationOptions: {
                tabBarIcon: (<Icon
                    type="font-awesome"
                    name="users"
                    color="#dddddd"
                    size={20}
                />),
            },
        },
        ...Account.User.hasAccess ? {
            RestrictedScreen: {
                screen: RestrictedScreen,
                navigationOptions: {
                    tabBarIcon: (<Icon
                        type="font-awesome"
                        name="recycle"
                        color="#dddddd"
                        size={20}
                    />),
                },
            }} : {},
        Settings: {
            screen: Settings,
            navigationOptions: {
                tabBarIcon: (<Icon
                    type="font-awesome"
                    name="cog"
                    color="#dddddd"
                />),
            }
        }
    });
    export default class DynamicTabBar extends React.Component {
        constructor(props) {
            super(props);
        }
        render() {
            return <Tabs navigation={this.props.navigation} />
        }
    }
    
    DynamicTabBar.router = Tabs.router;
```

Tabs has to be defined outside the wrapper, a static context, because otherwise I can't link the router to my navigation tree `DynamicTabBar.router = Tabs.router`. So the routes have to be known at compile time and cannot be changed at runtime...

**Comment by anson0370** [comment]
This is not a specific case I think. Because react navigation can use in web, I can use dynamic import to import screens and add to router, so webpack can separate js to several chunk files.

**Comment by aaronkchsu** [comment]
Bumping this because I am stuck as well! I am trying to get a dynamic number of tabs from the server which i am able to by building a tabNavigator after fetching, but since that tabNavigator is enclosed in the class I am not able to set the router of that generated tab navigator with the router of the wrapped class that has the static router property. Is there a different way to tackle this problem?

**Comment by Selman555** [comment]
I found a solution this this a while back.
What you should do is create a class for your dynamic tab bar and use it as a Screen for your root navigator:

export default class DynamicTabBar extends React.Component {
    static router = TabRouter({
        StaticTab: { Screen: StaticScreen },
        showTab1 ? {ConditionalTab1: { Screen: ConditionalScreen1 }} : {},
        showTab2 ? {ConditionalTab2: { Screen: ConditionalScreen2 }} : {},
    })
    render() {
        const Tabs = TabNavigator({
            StaticTab: { Screen: StaticScreen },
            showTab1 ? {ConditionalTab1: { Screen: ConditionalScreen1 }} : {},
            showTab2 ? {ConditionalTab2: { Screen: ConditionalScreen2 }} : {},
        });
        return <Tabs
            navigtion={this.props.navigation}
            screenProps={{rootNavigation: this.props.navigation}}
    }
}

There is a slight delay in re-rendering the tabbar, but it does what I want is to, that counts for something :)

**Comment by aaronkchsu** [comment]
@Selman555 Thanks so much!!  Sorry for the late reply, but I am wondering how do you set the showTab1 and showTab2 within the static variable?

**Comment by devpascoe** [comment]
Anyone got this working with React Navigation 3?

**Comment by devpascoe** [comment]
I ended up writing something like this to only load the component once the tab configuration was fetched from an api and saved into a global variable and used state to only show the component once ready.
```
  fetchTabs = async () => {
    const fetchUrl = `urltoapi/menu`
    const response = await fetch(fetchUrl)
    global.tabs = await response.json()
    AppScreen = require('./screens/AppScreen').default
    this.setState({ loadedTabs: true })
  }
```
...and in AppScreen its default returns the createBottomTabNavigator with the tabs object being the result of the following tabs() function
```
const tabs = () => {
  const tabItems = {}
  global.tabs.forEach(tab => {
    if (tab.screen == 'Feed') {
      tabItems['Feed'] = FeedStack
    } else if (tab.screen == 'Chat') {
      tabItems['Chat'] = ChatStack
    } else if (tab.screen == 'Profile') {
      tabItems['Profile'] = MyProfileStack
    } else if (tab.screen == 'Contact') {
      tabItems['Contact'] = ContactScreen
    }
  })
  return tabItems
}
```
So i'm basically doing whatever i can to delay loading and then showing the createBottomTabNavigator until i have prepared the tabs object for it to use since it needs that result returned synchronously.

**Comment by WilliamAnputra** [comment]
For those who needed to add a new tab everytime there is a change from api ( assuming you want to display tab from api response ), this is the code:

`renderSubCategoryTab = () => {
    
    // foodSubCategory contains many items ['seafood','fruit','vegetables']

    const { foodSubCategory } = this.props.navigation.state.params
  
    const dynamicScreenName = {};

    foodSubCategory.forEach(subCategory => {
      dynamicScreenName[`${subCategory.name}`] = {
        screen: () => <TabScreen />
      };
    });
 
    const SubCategoryTabs = createMaterialTopTabNavigator(dynamicScreenName);

    return <SubCategoryTabs />;
    
  }

  render() {
    return this.renderSubCategoryTab();
  }`

**Comment by mbrucher** [comment]
Has anyone managed to do this combined with react-redux?
Basically my screens depend on whether or not my user is signed in, which is indicated by a redux field. But I don't think there is an option to create the mapping based on props like there is for the `navigationOptions`?
