### ISSUE TITLE
Drawer navigation causesre-mounting of components

### ISSUE THREAD

**Issue by amirmatin** [react-community/react-navigation#3115]
### Current Behavior
Having implemented the Drawer navigation nested in Tab navigation, going from page "Home" to "Settings" and navigating back to "Home", it causes the "Home" component to reload. Same behavior when navigating back using the back button of the phone.
This behavior is only on Drawer navigator where Tab navigation works fine..  
Happens on both Android and iOS ...

### Expected Behavior
Navigating back to initial page (which was just open) shouldn't cause the component to reload  

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.15
| react-native     | 0.50.3
| node             |  v6.11.1
| npm or yarn      | 3.10.10

**Comment by kelset** [comment]
duplicate https://github.com/react-community/react-navigation/issues/2277
