### ISSUE TITLE
The color of the StatusBar

### ISSUE THREAD

**Issue by baicuhaha** [react-community/react-navigation#3116]
![2017-12-12 11 16 08](https://user-images.githubusercontent.com/20334376/33865789-454e3766-df2e-11e7-996e-6e9bbed51d7a.png)

![2017-12-12 11 19 29](https://user-images.githubusercontent.com/20334376/33865812-5bb12932-df2e-11e7-85d8-d37d8787ea32.png)

Set the color after The color of the navigationBar and statusBar There are differences
why?

**Comment by kelset** [comment]
Closing because you haven't followed the issue template; please open a new one that follows the template.
Without that, it's nearly impossible to understand & investigate the issue.

That said, the header is not the [status bar](https://facebook.github.io/react-native/docs/statusbar.html).
