### ISSUE TITLE
Transparent NavBar with background image behind the navbar

### ISSUE THREAD

**Issue by phrozenra** [react-community/react-navigation#312]
The idea is to have a full background image, then a transparent navbar on top of it.

You can style navbar and set backgroundColor: 'transparent', but this will just display the default ios navbar with a shadow. Currently the <Image> doesn't go behind the bar.

![screen shot 2017-02-12 at 20 40 26](https://cloud.githubusercontent.com/assets/2829339/22864970/86d0d3d8-f163-11e6-932f-b689ded7975d.png)

Is there any way to achieve this currently?

**Comment by pfulop** [comment]
I had the same problem as you, since my navbar was actually just a title for a screen, I ditched it and made simple view with text in it.

**Comment by phrozenra** [comment]
I managed to sort of get around this, by placing the StackNavigator inside a <Image> component.

`{ cardStyle: { backgroundColor: 'transparent' }, header: { style: { backgroundColor: 'transparent' }, tintColor: 'white' } }`

That allows the content to show up on the background, and sets the tintcolor properly.

This should be in a different ticket, but how do i change the status bar color (or hide it)

**Comment by GU5TAF** [comment]
Just use the `StatusBar` component with the `barStyle` prop to set the colour: https://facebook.github.io/react-native/docs/statusbar.html#barstyle

You can also hide it using the `hidden` prop if you prefer.

**Comment by phrozenra** [comment]
Thanks, that works.

**Comment by jhilden** [comment]
Facing the same issue.

> I managed to sort of get around this, by placing the StackNavigator inside a  component.

@phrozenra could you be so kind to elaborate what exactly you did there and share some code?


I would also be interested in how exactly to integrate the `StatusBar` with `react-navigation` and what the differences are to the other solution above.

**Comment by phrozenra** [comment]
Here's what I ended up with:
[https://gist.github.com/phrozenra/f38df22a04c2b86dcea2b6091e7dc9d2](https://gist.github.com/phrozenra/f38df22a04c2b86dcea2b6091e7dc9d2)

As you can see I created a LoginNavigator component, which is just a navigator to take care of all the login screens (the user doesn't reach any of the inner screens from anywhere else inside the app, also they share the same background).

Also, the nav bar is hidden on the navigator component and shown individually on every screen handled inside that navigator (done to prevent double nav bar).

I'm not sure which "other solutions above" you are referring to. Using StatusBar is straight forward, just check the documentation mentioned above and place the StatusBar component inside your Component

**Comment by jhilden** [comment]
thanks so much @phrozenra, with the help of your code example I was able to figure out the error I made :green_heart: 

It turns out I was doing basically everything the right way, the only problem I had was, that I had somehow copied a wrong `alignItems: 'center'` into `styles.backgroundImage`. now it works.

**Comment by chenyi5266** [comment]
if you don't want to make a image full of screen in ios , you can set StackNavigator config  ,  headerMode: 'none' 
![86a7a6092e48f751d0f5acf4ffb0a199](https://user-images.githubusercontent.com/28749518/27855881-b990e53c-619e-11e7-82ca-7953074d2ca2.png)

**Comment by damathryx** [comment]
I achieved this without removing the navigation bar with this:

```
      headerStyle: {
        backgroundColor: 'transparent',
        position: 'absolute',
        height: 50,
        top: 0,
        left: 0,
        right: 0,
      },
      headerTintColor: '#fff'
```

**Comment by freemanon** [comment]
`height` and `headerTintColor` aren't mandatory.

```js
headerStyle: {
  backgroundColor: 'transparent',
  position: 'absolute',
  top: 0,
  left: 0,
  right: 0,
  borderBottomWidth: 0 // removes the border on the bottom
}
```

**Comment by RyanRong** [comment]
@freemanon nice !!!good job!!!   
`borderBottomWidth: 0 // removes the border on the bottom`

**Comment by ihewro** [comment]
@damathryx  thank you for your answer ,it spend my two hour and make me sad!

**Comment by iamparthaonline** [comment]
for newer version ^3 of react-navigation, use `headerTransparent: true` inside `navigationOptions`

**Comment by riazXrazor** [comment]
@iamparthaonline thanks, that's what I needed !!

**Comment by edgargrs** [comment]
I could not make it work, until I added ` in headerMode: 'float',`  in StackNavigator config. Thanks :+1:

**Comment by fukemy** [comment]
> headerTransparent

i love u so muchhhhhhh <3
