### ISSUE TITLE
How to set header title with value from redux state

### ISSUE THREAD

**Issue by mikeaxle** [react-community/react-navigation#313]
Hi, i connected react-navigation to redux and when I try to add values from redux as part of the header title, I get an error. What is the correct code to accomplish this? 

my code:

```javascript
    //define navigation option - show header
    static navigationOptions = {

        title: `Total: K${this.props.totalCharge}`,
        header: {
            visible: true,
        }
    };
```
the error:
![screenshot_1486948710](https://cloud.githubusercontent.com/assets/15367382/22868152/2d450bda-f19b-11e6-8c2e-ad88f78d4be4.png)

**Comment by rmevans9** [comment]
AFAIK you can't hook directly to a redux store but you could do something like this:

```
class SuperManComponent extends React.Component {
    {...}
    static navigationOptions = {
        title: ({ state }) => `Total K:${state.params && state.params.totalCharge ? state.params.totalCharge : ''}`,
        {...}
    }
    {...}
    componentWillReceiveProps(nextProps) {
        if (nextProps.totalCharge) {
            this.props.navigation.setParams({ totalCharge });
        }
    }
}

const connectedSuperMan = connect(state => ({ totalCharge: state.ReducerYo.totalCharge }))(SumerManComponent);
```

**Comment by ericvicenti** [comment]
@rmevans9 is right, that is one way to do it, the other way is to have a pre-connected title component:

```
const MyTitle = ({ navigation, text }) => <TitleView text={text} navigation={navigation} />;
const MyConnectedTitle = connect(storeState => ({ text: storeState.title }))(MyTitle);

class SuperManComponent extends React.Component {
    {...}
    static navigationOptions = {
        title: (navigation) => <MyConnectedTitle navigation={navigation} />
```

**Comment by mikeaxle** [comment]
@rmevans9 thanks, my problem was solved

**Comment by jordanmkoncz** [comment]
@rmevans9 Your solution worked for me too, cheers!

**Comment by yingdongzhang** [comment]
@rmevans9 

I did the same however componentWillReceiveProps gets called infinitely. Any ideas? Thanks

**Comment by cmendes0101** [comment]
@yingdongzhang 

Check to make sure only when the nextProp is chaging

```
componentWillReceiveProps(nextProps) {
    if (this.totalCharge !== nextProps.totalCharge
        && nextProps.totalCharge) {
        this.props.navigation.setParams({ totalCharge });
    }
}
```

**Comment by yingdongzhang** [comment]
@cmendes0101 

Thank you that makes sense. Cheers

**Comment by chawax** [comment]
The `componentWillReceiveProps` method is deprecated from React 16.3, so this is no more the good place to set the header title. Any idea where we could do that ?

**Comment by soleimanipwy** [comment]
its really simple you can make stateless component and connect it with redux like this : 

const view = ({ state, color }) => {
  <View><Text>{state.something}</Text></View>
}

export default connect(
    (state) => ({
        data: state.data,
    }),
    null
)(view);

and then use it in static options : 

    static navigationOptions = ({ navigation }) => {
        return {
            tabBarIcon: ({ tintColor }) => <view color={tintColor}/>
        }
    };

**Comment by KianooshSoleimani** [comment]
its really simple you can make stateless component and connect it with redux like this : 

const view = ({ state, color }) => {
  <View><Text>{state.something}</Text></View>
}

export default connect(
    (state) => ({
        data: state.data,
    }),
    null
)(view);

and then use it in static options : 

    static navigationOptions = ({ navigation }) => {
        return {
            tabBarIcon: ({ tintColor }) => <view color={tintColor}/>
        }
    };

**Comment by EricWiener** [comment]
Please see this answer for an easier way to do this: https://stackoverflow.com/a/51883306/6942666

**Comment by The1nternet** [comment]
> @rmevans9 is right, that is one way to do it, the other way is to have a pre-connected title component:
> 
> ```
> const MyTitle = ({ navigation, text }) => <TitleView text={text} navigation={navigation} />;
> const MyConnectedTitle = connect(storeState => ({ text: storeState.title }))(MyTitle);
> 
> class SuperManComponent extends React.Component {
>     {...}
>     static navigationOptions = {
>         title: (navigation) => <MyConnectedTitle navigation={navigation} />
> ```

When i try to use a connected component in navigationOptions.header, i get:  TypeError: Object is not a function (near '...renderHeader...') . How can i add a connect() component to navigationOptions.header?
