### ISSUE TITLE
Ability to define a custom `onPress` for a tab

### ISSUE THREAD

**Issue by alphasp** [react-community/react-navigation#314]
=== by @grabbou

This is a catch-all issue for TabBar `onPress`, that is:
- ability to define a custom press handler
- press tab to reset active stack

=== original issue below ===

Given following nested tab setup
```
  MainTab
    --> Home
       --> Profile
          --> Related
  SettingTab
    --> ...
```
How to back/reset to Home screen from Related screen on press MainTab icon in tabs when MainTab is focused?

```
const MainTab = StackNavigator({
  Home: {
    screen: MyHomeScreen,
  },
  Profile: {
    screen: MyProfileScreen,
  },
  Related: {
    screen: MyRelatedScreen,
  }
});

const StacksInTabs = TabNavigator({
  MainTab: {
    screen: MainTab,
  },
  SettingsTab: {
    screen: SettingsTab,
  },
});

```

**Comment by grabbou** [comment]
CC: @satya164

**Comment by satya164** [comment]
Just do `navigation.goBack()` as you would usually do in a stack navigator.

**Comment by satya164** [comment]
Ah I see you mean when pressing tab icon. We should allow adding a listener to tab press so you can perform custom actions. cc @ericvicenti

**Comment by makirby** [comment]
I was also wondering this, is there no way of listening to the actions from the TabNavigator button press without hooking onto the actions they produce?

**Comment by ericvicenti** [comment]
I agree, a tab button handler override sounds like a reasonable thing to add, maybe call it `navigationOptions.tab.pressHandler` or something.

**Comment by satya164** [comment]
@ericvicenti it won't be very useful inside the static `navigationOptions` IMO. You can only dispatch navigation actions there. If you want any change anything else inside the component, it'll be a tedious process of passing it through params.

**Comment by ericvicenti** [comment]
Ok, so you want it to have access to the tab navigator's props? What API would you recommend for this?

Usually I would just fire a different action other than navigate, so I think the dispatch channel would be fine for me, (plus I may want to do side effects).

**Comment by satya164** [comment]
I think @browniefed wanted access to tabview's `onPositionChange` too, which is called every time the animation value is changed. We can't pass props to since it's a parent component, so I guess we need to have a way to attach listeners to the navigator.

> plus I may want to do side effects

yeah, if you are not using redux and say just want to fetch some data, or component state, or say scroll to top, you need to be able to listen to press event from inside the component.

**Comment by ericvicenti** [comment]
FWIW, I think the best practice for `onPositionChange` is not to call a callback tons of times but instead to pass around an animated value that represents the position

**Comment by browniefed** [comment]
I don't disagree but I'd like to potentially do logic to determine if I need to trigger `Animated.setValue`, etc. Hence a callback would be preferred.

**Comment by jankcat** [comment]
I am fairly new to this new (and so far awesome) nav project, but the basic behaviour described by OP is definitely a common behaviour among production apps currently in the market. Facebook, Instagram, Reddit (official app), Twitter, and AirBNB are just a few popular examples of this behaviour.

The common "tap flow" between these apps, when you are currently on the tab you are tapping:
 - Tap 1: Pop to root
 - Tap 2: Scroll to beginning (usually the top) of root, if it is a scrollview.

Just some thoughts to keep in mind when architecting a solution :)

**Comment by ayalpani** [comment]
I need this too! Any ideas for a workaround?

**Comment by ayalpani** [comment]
Dear @satya164 

will this one be approached any time soon? Otherwise I may be forced to build my own TabNavigator. And I'd really prefer not to :) Thanks!

**Comment by LiquidHelium** [comment]
I'm running into this problem now, it would be really helpful if the tabBarComponent took navigator as a prop so I can dispatch actions.

**Comment by satya164** [comment]
> it would be really helpful if the tabBarComponent took navigator as a prop so I can dispatch actions

I'm pretty sure it gets `navigation` as a prop right now

**Comment by LiquidHelium** [comment]
@satya164 

I pretty sure it doesn't unless I am not understanding something. If I print the props my tabBarComponent gets I get: 
```
["layout", "navigationState", "position", "jumpToIndex", "getLastPosition", "subscribe", "getLabelText", "renderIcon", "animationEnabled"]
```
Code I used to get that list: http://pastebin.com/EV9gdjws

**Comment by satya164** [comment]
Don't know what version you're on, but we pass the prop https://github.com/react-community/react-navigation/blob/master/src/views/TabView/TabView.js#L136

So maybe try `master` and see

**Comment by LiquidHelium** [comment]
Ah, you are right, it is passed in on master but not 1.0.0-beta.5. Thanks a lot.

**Comment by arnsa** [comment]
@satya164 when is this going to be implemented?

**Comment by maxmcd** [comment]
This is the workaround I use. Feedback welcome. 

```jsx
const MainTab = StackNavigator({
  Home: {
    screen: MyHomeScreen,
  },
  Profile: {
    screen: MyProfileScreen,
  },
  Related: {
    screen: MyRelatedScreen,
  }
});

let currentIndex;

const StacksInTabs = TabNavigator({
  MainTab: {
    screen: MainTab,
  },
  SettingsTab: {
    screen: SettingsTab,
  },
}, {
  tabBarComponent: ({ jumpToIndex, ...props }) => (
    <TabView.TabBarBottom
      {...props}
      jumpToIndex={index => {
        if (currentIndex === index && index === 0) {
          let resetTabAction = NavigationActions.navigate({
            routeName: "MainTab",
            action: NavigationActions.reset({
              index: 0,
              actions: [
                NavigationActions.navigate({ routeName: "Home" }),
              ],
            }),
          });
          props.navigation.dispatch(resetTabAction);
        } else {
          currentIndex = index
          jumpToIndex(index);
        }
      }}
    />
  ),
});

```

**Comment by jamesisaac** [comment]
@maxmcd Nice workaround, although gets caught out if you use `navigate` actions to change tabs programatically (`currentIndex` won't get updated).  Had to add a function called every time tab is changed programatically to update the index...

Would be great to have real support for this built in, where we can just access a `focused` property directly.

**Comment by grabbou** [comment]
@ericvicenti @satya164 given the traction that issue receives in past few days, I propose we include it in `v1`.

**Comment by augustoabreu** [comment]
I'm with the same problem. Tried many different things, the best result was back to Home only from child screens, but i have a lot of nested screens.

**Comment by jamesisaac** [comment]
@maxmcd I realised that workaround also falls apart when the user uses the Android back button to switch between tabs.  Here's a better workaround that doesn't rely on keeping track of the current index manually.  Replace jumpToIndex with:

``` javascript
jumpToIndex={index => {
  const { dispatch, state } = props.navigation

  if (state.index === index) {
    const stackRouteName = ['Tab1Home', 'Tab2Home', 'Tab3Home'][index]

    dispatch(NavigationActions.reset({
      index: 0,
      actions: [NavigationActions.navigate({ routeName: stackRouteName })],
    }))
  } else {
    jumpToIndex(index)
  }
}}
```

**Comment by cooperka** [comment]
I've opened a PR to support a `tabBarOnPress` prop: https://github.com/react-community/react-navigation/pull/1335. I'd love to hear feedback on whether this solves your use-cases.

**Comment by satya164** [comment]
I created a proposal for an event emitter system (#1363) to address these kinds of use cases. would love your suggestions.

**Comment by sfqpublic** [comment]
I comment this issue because I also wondering this

**Comment by itswaze** [comment]
@maxmcd using this workaround works just fine on iOS but on Android it won't set the TabBar to bottom. How can I fix this?

**Comment by danielreed07** [comment]
Interested in this as well.

**Comment by gugudwt** [comment]
Same problem. I'm using redux, and on every tab in the tabBar, i call the same react Component but passing different properties, and i would like to re-render the tab with the new properties.

`this.TabNavigator = TabNavigator({
            Home: {
                screen: Home,
                navigationOptions: {
                    tabBarLabel: 'Home'
                }
            },
            UltimeNews: {
                screen: props => <UltimeNews navigatorStack={this.props.navigation} categoria={{id:"",name:""}} />,
                navigationOptions: {
                    tabBarLabel: 'Ultime News'
                }
            },
            Ambiente: {
                screen: props => <UltimeNews navigatorStack={this.props.navigation} categoria={{id:"1",name:"Ambiente"}} />,
                navigationOptions: {
                    tabBarLabel: 'Ambiente'
                }
            }
        }, {
            tabBarPosition: 'top',
            swipeEnabled: true,
            animationEnabled: true,
            ...TabNavigator.Presets.AndroidTopTabs,
            tabBarOptions: {
                scrollEnabled: true,
                showIcon: false,
                showLabel: true,
                activeTintColor: Color.WHITE,
                style: {
                    backgroundColor:Color.MAINCOLOR
                },
                indicatorStyle: {
                    backgroundColor: 'white',
                    height: 6,
                    width:60,
                    marginLeft: 30
                },
                tabStyle: {
                    width:120
                },
                labelStyle:{
                    padding:0,
                    margin:5
                }

            },
            lazy:true
        });`

As you can see, tab 'Ambiene' and tab 'Ultime News' call the same component '<UltimeNews>' but with different props (categoria).

**Comment by danstepanov** [comment]
Any update on when this will be available?

**Comment by mleduque** [comment]
Would it be possible to have the current understanding on this problem? I tried to read the comments but it seems to be a succession of false leads (or incomplete...).
I'm actually not interested on the "ability to define a custom onPress for a tab" because I don't use a TabNavigaor but DrawerNavigator (the fact that DrawerNavigator is based on TabNavigator is an implementation detail), and I don't want onPress, I just want to correctly reset StackNavigators nested inside a DrawerNavigator.
So, what's the (current) best way to attain that goal?

**Comment by mleduque** [comment]
No?

**Comment by jitinmaher** [comment]
Is this a right way to capture the on press event. 
```
const TestNavScreen = TabNavigator({
  Test: {
    screen: TestScreen,
    navigationOptions: {
      tabBarIcon: ({ tintColor }) => (
        <TouchableWithoutFeedback onPress={() => { console.log('Got IT!'); }}>
          <Image
            source={require('../../assets/img/test.png')}
            style={[styles.icon, { tintColor }]}
          />
        </TouchableWithoutFeedback>
        ),
    }
  },
  Notifications: {
    screen: NotificationsScreen,
  },
});
```
This worked for me !

**Comment by cooperka** [comment]
@jitinmaher I believe that will only put an `onPress` handler on a very small portion of the tab (just the icon itself), and it will likely also steal the tap event and prevent changing the tab. That doesn't seem like a good solution. You can check out #1335 for a working PR.

**Comment by harbi** [comment]
Any update on this?

**Comment by tobiassernhede** [comment]
I experimented a little with this and came up with this pretty clean solution. The tab bar button will function as the back button when it is the active tab.

It requires that you also imports the following:
`import { TabBarBottom, NavigationActions } from 'react-navigation';`

`const tabBarConfiguration = {
    tabBarComponent: ({ jumpToIndex, ...props }) => (
        <TabBarBottom
            {...props}
            jumpToIndex={(index) => {
                    if(props.navigation.state.index === index) {
                        props.navigation.dispatch(NavigationActions.back());
                    } else {
                        jumpToIndex(index);
                    }
                }
            }
        />
    ),
}`

**Comment by cooperka** [comment]
@tobiassernhede that's a neat trick, but there's already a real working solution: #1335

**Comment by dmr07** [comment]
@cooperka This issue should be closed.

**Comment by cooperka** [comment]
Hi @dmr07, unfortunately I'm not a maintainer so I don't have permission to close this issue.

**Comment by Tom29** [comment]
@maxmcd you saved my life today 👍

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!

**Comment by opera9900** [comment]
```js
TabNavigator({
    ****
}, {
    tabBarComponent: ({jumpToIndex, ...props}) => (
        <TabBarBottom
            {...props}
            getOnPress={() => {
                return (scene) => {
                    const {route, index, focused} = scene;
                    if (index !== 3 /* ~ ~ */) {
                        jumpToIndex(index);
                    } else {
                        // HANDLE IT !!
                    }
                };
            }}
        />
    ),
    tabBarPosition: 'bottom'
})
```

Worked for me!!

**Comment by pensierinmusica** [comment]
@spencercarli can you please tag this issue as `feature-request` and reopen it? Thanks!

**Comment by cooperka** [comment]
Hi @pensierinmusica, this was already solved in https://github.com/react-community/react-navigation/pull/1335. The feature request has been accepted.

**Comment by pensierinmusica** [comment]
@cooperka oops I missed that, thx, awesome then!  :)

**Comment by vlimag** [comment]
All you need to do is set a custom onPress event for the TabBarIcon, as follows:
`
import Icon from 'react-native-vector-icons/FontAwesome';

class YourClass extends Component {

      static navigationOptions = ({ navigation, screenProps }) => ({
    title: YourTitle',
    headerTintColor: '#fff',
    headerStyle: {
       backgroundColor: '#000', 
       height: 70,
       elevation: null
     },
    tabBarIcon: ({ tintColor }) => (
      <Icon name = {"user-o"} color={tintColor} size={20} onPress={()=>navigation.goBack()}/>
      ),
  });
`

Hope it helps!

**Comment by topherCarpediem** [comment]
@cooperka That's really helps. Thanks

**Comment by jaimebiernaski** [comment]
One more solution...

```
static navigationOptions = ({ navigation }) => ({
  tabBarOnPress: ({ scene, jumpToIndex }) => {
    navigation.state.params.setCurrentScreen(scene);
    if (!scene.focused) {
      jumpToIndex(scene.index);
    }
  },
});

....

componentDidMount() {
    this.props.navigation.setParams({
      ...this.props.navigation.state.params,
      setCurrentScreen: scene => {
        this._setCurrentScreen(scene);
      }
    });
  }

.... 

render(){...}

_setCurrentScreen = (scene) => {
  console.log('Current Scene:', scene)
}
```

**Comment by tsalama** [comment]
For anyone looking for an easier solution using React Navigation 6:

```
import { useScrollToTop } from '@react-navigation/native';

export default function Home({ route, navigation }) {

	return (
	);
}

```
