### ISSUE TITLE
Custom header: weird border when using header component

### ISSUE THREAD

**Issue by yooouuri** [react-community/react-navigation#3141]
### Current Behavior
This problem does not exists on iOS!!!

Without the `header` component it is working fine on android.
```
      return (
        <View>
          <StatusBar
            backgroundColor='rgb(240,105,64)'
            barStyle="light-content"
          />
          <ImageBackground source={require('../../images/gradient_orange.png')} style={styles.background}>
            <View style={styles.left}>
              <TouchableOpacity onPress={() => this.onPressSearch()}>
                <Image source={require('../../images/search.png')} style={styles.icon}/>
              </TouchableOpacity>
            </View>
            <Image source={require('../../images/logo.png')} style={styles.logo} resizeMode={'contain'}/>
            <View style={styles.right}>
              <TouchableOpacity onPress={() => this.onPressFilter()}>
                <Image source={require('../../images/filter.png')} style={styles.icon}/>
              </TouchableOpacity>
            </View>
          </ImageBackground>
        </View>
      );
```

<img width="422" alt="imageedit_1_8269460376" src="https://user-images.githubusercontent.com/12934957/34074138-31ab8596-e2a9-11e7-919e-c8e6aa9ec14e.png">

```
return (
        <View>
          <StatusBar
            backgroundColor='rgb(240,105,64)'
            barStyle="light-content"
          />
          <ImageBackground source={require('../../images/gradient_orange.png')} style={styles.background}>
            <Header {...this.props} />
          </ImageBackground>
        </View>
      );
```

<img width="422" alt="screen shot 2017-12-16 at 21 27 02" src="https://user-images.githubusercontent.com/12934957/34074076-ecf9358e-e2a7-11e7-9ee6-501fc8caca99.png">

### Expected Behavior
Like the first screenshot, no weird borders around the header when using `header` component.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.21
| react-native     | 0.51.0
| node             | v8.6.0
| npm or yarn      | 5.6.0, 1.3.2

**Comment by kelset** [comment]
Closing in favour of #3052
