### ISSUE TITLE
TabNavigator + Redux strange behaviour

### ISSUE THREAD

**Issue by monteithpj** [react-community/react-navigation#315]
I've put together a simple example with a TabNavigator, one with and one without Redux.

The one without Redux works as expected, but the one with Redux gives an error when attempting to navigate to the current tab.

Example:

Navigator:
```
const screen = (name, to) => React.createClass({
  render() {
    return (
      <View>
        <Text>{name}</Text>
        <Button title={"TO " + to} onPress={() => this.props.navigation.navigate(to)}/>
      </View>
    )
  }
})

export const WithoutRedux = TabNavigator({
  tabA: {screen: StackNavigator({screen1: {screen: screen("screen1", "screen2")},
                                 screen2: {screen: screen("screen2", "tabA")}})},
  tabB: {screen: StackNavigator({screen3: {screen: screen("screen3", "screen4")},
                                 screen4: {screen: screen("screen4", "tabA")}})}
})

export const WithRedux = connect(({nav}) => ({nav}))
(({nav, dispatch}) => (
  <WithoutRedux navigation={addNavigationHelpers({dispatch, state: nav})}/>
))
```

Reducer:
```
const reducer = (state, action) => {
  return WithoutRedux.router.getStateForAction(action, state)
}
```

The other parts of the integration are identical to the Redux Integration documentation

When pressing the "TO tabA" button on screen2, the WithRedux version throws "Cannot read property routes of null" (as getStateForAction has returned null) but the version WithoutRedux does nothing (as expected)

**Comment by rmevans9** [comment]
Likely related: https://github.com/react-community/react-navigation/issues/246

Try and change your reducer to the way I have it in my comment on that ticket.

**Comment by monteithpj** [comment]
@rmevans9 Yup, looks like the same issue. Thanks
