### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'route.routeName')

### ISSUE THREAD

**Issue by tegarkurniawan** [react-community/react-navigation#3153]
I'm having an error like this, I've added the routename but it's still an error like that

TypeError: undefined is not an object (evaluating 'route.routeName')

This error is located at:
    in DrawerView (at DrawerNavigator.js:127)
    in Unknown (at createNavigator.js:52)
    in Navigator (at createNavigationContainer.js:210)
    in NavigationContainer (at SceneView.js:31)
    in SceneView (at CardStack.js:412)
    in RCTView (at View.js:113)
    in View (at CardStack.js:411)
    in RCTView (at View.js:113)
    in View (at CardStack.js:410)
    in RCTView (at View.js:113)
    in View (at createAnimatedComponent.js:134)
    in AnimatedComponent (at Card.js:26)
    in Card (at PointerEventsContainer.js:55)
    in Container (at CardStack.js:454)
    in RCTView (at View.js:113)
    in View (at CardStack.js:383)
    in RCTView (at View.js:113)
    in View (at CardStack.js:382)
    in CardStack (at CardStackTransitioner.js:97)
    in RCTView (at View.js:113)
    in View (at Transitioner.js:192)
    in Transitioner (at CardStackTransitioner.js:49)
    in CardStackTransitioner (at StackNavigator.js:60)
    in Unknown (at createNavigator.js:52)
    in Navigator (at createNavigationContainer.js:210)
    in NavigationContainer (at registerRootComponent.js:34)
    in RootErrorBoundary (at registerRootComponent.js:33)
    in ExpoRootComponent (at renderApplication.js:35)
    in RCTView (at View.js:113)
    in View (at AppContainer.js:102)
    in RCTView (at View.js:113)
    in View (at AppContainer.js:122)
    in AppContainer (at renderApplication.js:34)

My code
https://pastebin.com/KkqX1MUD
 what is the solution ?

**Comment by ihor** [comment]
I'm having the same issue.

**Comment by kelset** [comment]
Closing in favour of https://github.com/react-community/react-navigation/issues/3148

**Comment by tegarkurniawan** [comment]
I'm using beta 2.1 but it's still an error

**Comment by tegarkurniawan** [comment]
![jawab](https://user-images.githubusercontent.com/8655617/34150954-733231f6-e4dc-11e7-96bd-457feb1b44a2.PNG)

**Comment by HunDunDM** [comment]
@tegarkurniawan try to delete `^` and then `yarn install`

**Comment by walter211** [comment]
I got this error for one week. Any test case run before release?

**Comment by SamiChab** [comment]
@HunDunDM, it didn't worked for me. Any ideas on how to resolve this issue?

**Comment by SamiChab** [comment]
as @sonaye mentioned in issue #3148, adding
```
drawerOpenRoute: 'DrawerOpen',
drawerCloseRoute: 'DrawerClose',
drawerToggleRoute: 'DrawerToggle'
```
makes it work.

**Comment by ducnhat** [comment]
@SamiChab

**Comment by ducnhat** [comment]
@SamiChab thank you! You saved my life.
