### ISSUE TITLE
Undefined is not an object (evaluating route.routeName)

### ISSUE THREAD

**Issue by Rah1x** [react-community/react-navigation#3159]
Yesterday I tried to install `react-native-elements`, after this all hell broke loose. Now I cant reverse to a working app. Ive done all steps:

1. Remove react-native-elements
2. ensure nothing is new in package
3. Remove all node_modules and rebuild them
4. npm cache clear

Nothing works!!
PLZZZ help...

![image](https://user-images.githubusercontent.com/841857/34183431-e35e35b4-e56e-11e7-8a15-fc07722d446e.png)

**Comment by wachunei** [comment]
check this comment https://github.com/react-community/react-navigation/issues/3148#issuecomment-352778884

**Comment by Rah1x** [comment]
@wachunei  you are a legend!! Thanks a million.. finally after like 2 days of looking for this UNDOCUMENTED option!!
