### ISSUE TITLE
Drawer Navigator Breaks If Config Provided (as of 1.0.0-beta.22)

### ISSUE THREAD

**Issue by dancherb** [react-community/react-navigation#3183]
I've recently been struggling with why my navigator, hooked up with redux, wasn't working in an identical new project.

My error (triggered in the navigation reducer) was:
_null is not an object (evaluating 'action.type')
getStateForAction_

I was led to this merge in the most recent update of React Navigation:
https://github.com/react-community/react-navigation/pull/1803

It seems that if we're providing config values for a drawer navigator, we now have to provide some mandatory properties or the app breaks. I feel like this unfairly caused me a lot of problems, so hopefully a fix can be thought and others struggling can find this thread!

**Comment by dancherb** [comment]
Duplicate of https://github.com/react-community/react-navigation/issues/3148, oops.  Maybe someone searching for my specific error will still be pointed in the right direction.

**Comment by acomito** [comment]
@dancherb Thanks!
