### ISSUE TITLE
Android TypeError:undefined is not an object (evaluating 'this._subscribableSubscription.forRach')

### ISSUE THREAD

**Issue by wangbingqiong** [react-community/react-navigation#3187]
For usage questions, try to:
<img width="100" alt="1" src="https://user-images.githubusercontent.com/18202889/34354241-e88c03e2-ea67-11e7-89d2-14b93e7c208c.png">
<img width="100" alt="2" src="https://user-images.githubusercontent.com/18202889/34354257-fb42d164-ea67-11e7-8870-75825d75e99f.png">

                "react": "16.0.0",
		"react-native": "^0.50.3",
		"react-native-code-push": "^5.2.1",
		"react-navigation": "^1.0.0-beta.18"

import codePush from 'react-native-code-push';
export default class Home extends Component {
    componentDidMount() {
        codePush.sync();
    }
}
There is a problem when app reloads the code

**Comment by greenzeal** [comment]
have exactly the same issue!

**Comment by sonaye** [comment]
See https://github.com/facebook/react-native/issues/17348
