### ISSUE TITLE
Docs: Navigation Prop doc should discuss the navigator's navigation prop

### ISSUE THREAD

**Issue by ericvicenti** [react-community/react-navigation#319]
The top of the [Navigation Prop doc](https://reactnavigation.org/docs/navigators/navigation-prop) should be rewritten to explain that the navigation prop is passed to every navigation-aware component, including navigators. The big exception is that a navigator's navigation prop may not have the helper functions on it, it may only have `state` and `dispatch`. 

Also, people don't always hook things up to redux correctly, because they mis-understand the navigator's top-level API, where the navigation prop is optional. The navigator will maintain its own state if it doesn't get a navigation prop, but this is not a feature you generally want to use when hooking your app up with redux. For navigators that are nested inside of your main navigator, you *always* want to pass the screen's navigation prop down. This allows your top-level navigator to communicate and provide state for all the children navigators. Only your top-level router needs to be integrated with redux, because all the other routers are inside it.

Who would like to take on this docs improvement work? I've seen a lot of confusion around these things, so I hope we can make it more clear to the community what the difference is between a navigator's navigation prop in comparison to a navigation screen prop.

**Comment by grabbou** [comment]
Closing as changes were implemented already.
