### ISSUE TITLE
Navigation Actions Doc

### ISSUE THREAD

**Issue by ericvicenti** [react-community/react-navigation#320]
The docs for navigation actions are hard to find. There is currently an incomplete list of actions under the `dispatch` section of [the navigation prop doc](https://reactnavigation.org/docs/navigators/navigation-prop).

We should remove the list from that page and instead link to a new page for the actions, that can provide more thorough documentation for `NavigationActions`. Its not clear exactly where in the sidebar this doc should go, but probably in the Navigators section.

**Comment by ElliottJRo** [comment]
hey @ericvicenti I can do this but one problem I ran into with dispatching actions is the additional `action` param that is the "sub-action to run in the child router". When I add in a `RESET` action as a sub-action (inside a `NAVIGATE`) I expected the `Reset` action to be handled by the new router given by the `NAVIGATE` action by it was handled by the router before transition. Is this expected?

Also I don't see `NavigationActions.URI` handled in `StackRouter` or `TabRouter`.

**Comment by ElliottJRo** [comment]
@ericvicenti  Can be closed now!

**Comment by guigrpa** [comment]
@elliotjro what about your question on the embedded reset subaction being handled by the current router (before the transition) instead of by the future one? Did you figure it out?

**Comment by ElliottJRo** [comment]
@guigrpa no sorry I did not. I ended up writing my own custom actions to deal with that certain scenario.
