### ISSUE TITLE
Dynamic changing routeconfig with DrawerNavigator

### ISSUE THREAD

**Issue by ippa** [react-community/react-navigation#326]
Started playing with react-navigation and the DrawerNavigator. Very easy to create a static sidebar, but how would one go about to get dynamic content into the sidebar? For example in a chat-application I would want to list all channels (which are changing over time) in the sidebar.

This is what I got right now:

```
import React, { Component } from 'react';
import { View, Text} from 'react-native';
import { DrawerNavigator} from 'react-navigation'

class App extends Component {
  render() {
    return(
      <View style={styles.container}>
        <Text>test</Text>
      </View>
    )
  }

export default DrawerNavigator(
{
  channel: {
    screen: App,
    navigationOptions: {
      drawer: () => ({label: '#channel1'})
    }
  },
  channel2: {
    screen: App,
    navigationOptions: {
      drawer: () => ({label: '#channel2'})
    }
  },
},
{})
```

**Comment by satya164** [comment]
Use the `contentComponent` option to provide your own drawer component https://reactnavigation.org/docs/navigators/drawer

**Comment by Noitidart** [comment]
@ippa did you solve this? I would love to see your solution please if possible.

**Comment by cstehreem** [comment]
@ippa I would like to see your solution too if possible. I created a very simple contentComponent but I need to render one item based on existence of a file. And even though the method returns true my drawer item does not render

**Comment by movier** [comment]
@Noitidart @cstehreem Check out [Custom drawer using React Navigation](https://codeburst.io/custom-drawer-using-react-navigation-80abbab489f7). It works for me!

**Comment by Noitidart** [comment]
Thanks very much @movier for notifying me of this I will check it out!
