### ISSUE TITLE
Back button behaviour with redux store integration

### ISSUE THREAD

**Issue by f0rr0** [react-community/react-navigation#327]
This does not seem to be documented. After integrating redux, I was expecting back button to dispatch actions to which I can react in my reducer. But the button does not dispatch any action. Does this mean I will have to override the entire Header component and provide a custom one?

**Comment by f0rr0** [comment]
To be more precise, after integrating Redux, what is the default behaviour of back buttons in headers? Do they dispatch any action by default on press or does that need to be specified?

**Comment by satya164** [comment]
Add your own back button listener and dispatch an action - https://reactnavigation.org/docs/guides/redux

> Keep in mind that when a navigator is given a navigation prop, it relinquishes control of its internal state. That means you are now responsible for persisting its state, handling any deep linking, integrating the back button, etc.

**Comment by mikeaxle** [comment]
@f0rr0 I was battling with this issue too for the past two days, I solved it just now. her is my code:
this is a screen called 'ChargeCard' and these are the navigation options:

```javascript
    static navigationOptions = {
        // Nav options can be defined as a function of the navigation prop:
        title: `Charge K`,  //use redux for charge total
        header: (navigation) => ({
            left: (
                <TouchableOpacity
                    style={{marginLeft: 20}}
                    onPress={() => navigation.dispatch({type: 'back_screen'})}>
                    <Icon name="undo" size={25} color='#95989A'/>
                </TouchableOpacity>
            ),
            tintColor: '#95989A',
            style: {
                backgroundColor: '#EDEDED'
            }
        }),
    };
```
and this is my navigation reducer:

```javascript
import { NAVIGATE, BACK_SCREEN } from '../actions/types'; //import action types
import { AppNavigator } from '../App'; //import stack navigator from App entry point
import { NavigationActions } from 'react-navigation';

//define initial navigation state
const INITIAL_NAV_STATE = {
    index: 0,
    routes: [
       //{ key: 'LoginForm', routeName: 'LoginForm' },
       { key: 'Charge', routeName: 'Charge' },
    ],
};

export default (state = INITIAL_NAV_STATE, action) => {



    switch (action.type){
        case NAVIGATE:
            return AppNavigator.router.getStateForAction(NavigationActions.navigate({ routeName: action.payload }), state);

        case BACK_SCREEN:
            return AppNavigator.router.getStateForAction(NavigationActions.back(), state);

        default:
            return state;

    };

    return state;
};
```
and this is my navigation actions:

```javascript 

import { NAVIGATE, BACK_SCREEN } from './types';

//action to change screens
export const moveToScreen = (screen) => {
    return {
        type: NAVIGATE,
        payload: screen
    };
};


//action to go back a screen
export const backScreen = () => {
    return {
        type: BACK_SCREEN,
       // payload: screen
    };
};

```

what u will want to use is the ```  onPress={() => navigation.dispatch({type: 'back_screen'})}> ``` to dispatch actions from the header and ```return AppNavigator.router.getStateForAction(NavigationActions.back(), state); ``` to handle the navigation from the reducer. I think the docs need some work, nothing really said this explicitly. Good luck.

**Comment by f0rr0** [comment]
@mikeaxle the default back button dispatches `NavigationActions.BACK`.

```js
import Router from 'Router'
import { NavigationActions } from 'react-navigation'
import { handleActions } from 'redux-actions'

const defaultState = {
  index: 0,
  routes: [
    { key: 'xyz-1234', routeName: 'Home' }
  ]
}

const { NAVIGATE, BACK } = NavigationActions

export default handleActions({
  [NAVIGATE]: (prevState, { payload: { routeName } }) =>
  Router.router.getStateForAction(NavigationActions.navigate({ routeName }), prevState),
  [BACK]: prevState => Router.router.getStateForAction(NavigationActions.back(), prevState)
}, defaultState)
```

This should be documented prominently. You don't need a custom back button.

**Comment by AlanFoster** [comment]
For anyone coming to this in the future; There is a redux example available within the repository [here](https://github.com/react-community/react-navigation/tree/af787e56fe05183ae1e1e0c26899b8ae76e318d7/examples/ReduxExample) - note this linked example is for `1.0.0-beta.6`

**Comment by FrederikNygart** [comment]
If you're working with redux you could also use componentWillUnmount() to dispatch actions when going back.

This is not a solution to the problem per se, but it worked in my case.

**Comment by peacechen** [comment]
@f0rr0 
`handleActions` isn't working with react-navigation 1.0.0-beta.13.   Has something changed?

**Comment by dchhetri** [comment]
How do you handle this properly when you have multiple composed navigator. For example If I have a TabBarNavigator which composes of 2 Screen, both of which are StackNavigator. If a Navigation.Back action is emitted, how do you properly handle it in the reducer, since inside the reducer, Navigation.Back action does not specify which Navigator emitted the Back action? I can keep track of the top most navigator, but is there a cleaner way? Best.
