### ISSUE TITLE
withNavigation does not provide valid navigation object

### ISSUE THREAD

**Issue by prontiol** [react-community/react-navigation#329]
I am trying to use `withNavigation` helper to let my custom header components perform navigation.
Code is pretty simple (non-relevant code and imports skipped):
```js
import { withNavigation } from 'react-navigation';

const Home = ({ navigation }) => (
    <TouchableOpacity onPress={() => navigation.navigate('Home')}>
        <Icon name="home"/>
    </TouchableOpacity>
);

export default withNavigation(Home);
```
Unfortunatelly, `navigation` prop is `undefined`.
What am I doing wrong?

**Comment by satya164** [comment]
cc @jakubsta

**Comment by agrcrobles** [comment]
I am getting
```
Uncaught TypeError: (0 , _reactNavigation.withNavigation) is not a function
```
when doing `import { withNavigation } from 'react-navigation';`

In the meantime I am dispatching action `Navigation/NAVIGATE` in my component.

**Comment by satya164** [comment]
Just saw that you mentioned custom `header` components. The `header` option received `navigation` as an argument which you can pass down to the component.

`withNavigation` doesn't work because header is rendered outside the scene, so it doesn't provide the navigation context.

**Comment by joncursi** [comment]
Hmm, I am running into the same issue of an undefined `navigation` object via `withNavigation` for non-scene components. I thought the main goal of `withNavigation` was to provide easy access to the `navigation` object on components **outside** the list of registered scenes, so that you didn't have to pass the `navigation` object around.

**Comment by joncursi** [comment]
It looks like `withNavigation` works for any components used inside the `render` method of a registered screen, regardless of how deep. It's just the header bar that seems to need the `navigation` prop passed in manually from what I can tell, which isn't that bad.

**Comment by telkandrew** [comment]
I'm trying to use withNavigation for a nested component used inside the render and still not able to access the navigation prop throwing the error "Cannot read 'navigation' of undefined". Were you able to use it successfully?
