### ISSUE TITLE
What about this package instead of the Facebook "official" one?

### ISSUE THREAD

**Issue by benjaminb10** [react-community/react-navigation#33]
Hi,

This package seems pretty good. Bravo for the release.

I've seen in the Facebook Roadmap that they will release a new navigation package (here is a screenshot) : 
![screenshot_2017-01-27 15 44 12_nhnycn](https://cloud.githubusercontent.com/assets/2952678/22374726/a9910780-e4a7-11e6-93b9-6ed695c29004.png)
_(source: https://github.com/facebook/react-native/wiki/Roadmap)_

Why should I use this package and not the future Facebook "official" one?

**Comment by knowbody** [comment]
This is that "new standard navigation".

**Comment by benjaminb10** [comment]
Oh! Great. So you guys work at Facebook or are core contributors?

**Comment by knowbody** [comment]
I don't work at Facebook. This project is a collaboration between folks from Exponent, Facebook and react community.

If this answer your question please close the issue.

**Comment by benjaminb10** [comment]
Thanks for the reply.
