### ISSUE TITLE
Tiny back button on real iOS device

### ISSUE THREAD

**Issue by jamsesso** [react-community/react-navigation#333]
Hi,
When running my app on a real device (iPad Mini, iOS 9.3.5) the back button appears very tiny. I am not able to replicate this problem in the simulator, unfortunately.

I am using 1.0.0-beta.3

Is there a temporary workaround for this?

![img_0004](https://cloud.githubusercontent.com/assets/107810/22937976/a6ab1d5a-f2b0-11e6-82e4-0cb7f996bddd.PNG)

**Comment by satya164** [comment]
cc @grabbou

**Comment by grabbou** [comment]
Interesting, maybe no-one ever run it on an iPad. I'll try to debug it today, thanks for reporting.

**Comment by satya164** [comment]
Hmm.. This one looks pretty small and different from other icons https://github.com/react-community/react-navigation/blob/master/src/views/assets/back-icon@1x.ios.png

**Comment by jamsesso** [comment]
@satya164 @grabbou For reference, I see the correct version when I launch the same build in the iPad simulator:

![simulator screen shot feb 15 2017 10 00 12 am](https://cloud.githubusercontent.com/assets/107810/22977671/052c3a3e-f366-11e6-9e2d-fba360951c3c.png)

**Comment by grabbou** [comment]
@satya164 Looks like I added `back-icon.png` instead of just `back-icon@1x.png`. Will update that one either, maybe it fixes the issue.

**Comment by grabbou** [comment]
Will be probably fixed by #344

**Comment by jamsesso** [comment]
@grabbou I'm having troubles installing from this module from the master branch in the usual manor (`npm install github:react-community/react-navigation` followed by an `npm install` in the node_modules directory) so I am not sure how to test that exactly.

**Comment by grabbou** [comment]
You can install beta-5 now, it contains the fix. Rather than that, just `npm install react-community/react-navigation#master` or replace `master` with commit sha.

**Comment by jamsesso** [comment]
Yes, I can confirm this is fixed in `1.0.0-beta.5`
Thanks for publishing that release!
