### ISSUE TITLE
Relay

### ISSUE THREAD

**Issue by Lenin7** [react-community/react-navigation#346]
Would it be possible to implement `react-navigation` with `Relay.createContainer` and `Relay.injectNetworkLayer`  instead of `RelayStore.reset/createRenderer`? [https://github.com/sibelius/ReactNavigationRelay
](url)

Thanks

**Comment by sibelius** [comment]
createRenderer is just a wrapper on top of Relay.Renderer.

U could use Relay.Renderer directly

**Comment by lukecwilliams** [comment]
FYI, example of using react-navigation with Relay.createContainer here:

https://github.com/react-community/react-navigation/issues/588#issuecomment-287480454

@Lenin7
