### ISSUE TITLE
Problem overriding router for built-in navigators

### ISSUE THREAD

**Issue by abergenw** [react-community/react-navigation#348]
Overriding the router for StackNavigator and TabNavigator doesn't seem to work. NavigationContainer exposes router as a static property but this is never used internally, instead Component.router is used. Am I missing something obvious here?

**Comment by ElliottJRo** [comment]
hey @abergenw soo to override routers, you need to do something like this:

```js
const WelcomeNavigator = StackNavigator({
  Main: { screen: MainScreen },
  Login: { screen: LoginScreen },
  Register: { screen: RegisterNavigator }
}, {
  headerMode: 'none'
});

const WelcomeRouter = WelcomeNavigator.router;
WelcomeNavigator.router = {
  ...WelcomeNavigator.router,
  getStateForAction(action, state) {
    // Add in custom action handlers / hooks here ie. logging
    console.log('getStateForAction router', action, state);

    // reuse default router getStateForAction (optional, only needed if want to extend and not replace)
    return WelcomeRouter.getStateForAction(action, state);
  }
}
```

Hope this helps.

**Comment by abergenw** [comment]
According to the documentation this should work but it doesn't. The problem seems to be the fact that NavigationContainer (if stateful) uses the static router set on the wrapped component instead of the static router set on itself. Of course I can manipulate the router instance of NavigationContainer.router but simply setting a new router does not work.

Here's a snippet from createNavigationContainer.js illustrating how router is accessed.

```
class NavigationContainer extends React.Component {
    state: State;
    props: Props;

    subs: ?{
      remove: () => void,
    } = null;

    static router = Component.router;

    _isStateful: () => boolean = () => {
      const hasNavProp = !!this.props.navigation;
      if (hasNavProp) {
        invariant(
          !containerConfig,
          'This navigator has a container config AND a navigation prop, so it is ' +
          'unclear if it should own its own state. Remove the containerConfig ' +
          'if the navigator should get its state from the navigation prop. If the ' +
          'navigator should maintain its own state, do not pass a navigation prop.'
        );
        return false;
      }
      return true;
    }

    constructor(props: Props) {
      super(props);
      this.state = {
        nav: this._isStateful()
          ? Component.router.getStateForAction(NavigationActions.init())
          : null,
      };
    }
```

**Comment by ElliottJRo** [comment]
Are you saying that you want to override the default router so the built in navigators use it on init? Im having trouble understanding whats wrong with modifying the instance only.

**Comment by abergenw** [comment]
Ok now I see what's wrong here. I'm transpiling from Typescript which results in `let a = {...b, c}` being transpiled to `let a = Object.assign({}, b, c)`. This is why the example code didn't work for me and lead me to believe there was a bug. So the idea is to modify the instance, roger that.

Just out of curiosity, is NavigationContainer using Component.router instead of NavigationContainer.router to make sure that the router set on the actual component is being used instead of the one set on NavigationContainer? I guess this is ok but it's sort of misleading that setting the static router property on a navigator doesn't work if it's wrapped with NavigationContainer.

Cheers!

**Comment by satya164** [comment]
> which results in let a = {...b, c} being transpiled to let a = Object.assign({}, b, c).

It's the same in ESNext too. You need to assign the variable yourself.
