### ISSUE TITLE
Support Initial params in TabRouter

### ISSUE THREAD

**Issue by RobertSheaO** [react-community/react-navigation#349]
I'm trying to specify params that I can access inside my custom `contentComponent` But all I get on `this.props.navigation.state.route` is `index`, `key`, routeName` and `routes`. Here's my setup

```JS
// DrawerNavigator
const DrawerWrapper = DrawerNavigator({
  Home: {
    screen: HomeNavigator,
    navigationOptions: { title: 'Home', params: {test: 'this'} },
    params: {hello: 'world'},
  },
}, {
  initialRouteName: 'Home',
  contentComponent: SideDrawer,
});

// SideDrawer
class SideDrawer extends React.Component {
  render() {
    const { navigate, state } = this.props.navigation;
    // Expecting to see either test:this or hello:world
    console.log(state);
   
    return null;
  }
}

// HomeNavigator
const HomeNavigator = StackNavigator({ index: { screen: HomeScreen } }, { initialRouteName: 'index' });

// HomeScreen
class HomeScreen extends React.Component {
  static navigationOptions = {
    title: 'Home'
  };
  render() {
    return (
      <ScrollView>
        <Text>Home</Text>
      </ScrollView>
    );
  }
}
```

**Comment by satya164** [comment]
This should be solved by #306

**Comment by jamesisaac** [comment]
Not sure about that.  #306 is about params attached to the NAVIGATE action, here they're being set on the static config.

**Comment by satya164** [comment]
@jamesisaac isn't that what we talked about here? https://github.com/react-community/react-navigation/pull/306#issuecomment-279476332

**Comment by RobertSheaO** [comment]
That's how to send params when navigating, I'm not navigating, I'm setting up my DrawerNavigator. What I want to do is set a custom param that has the name of the SVG icon I want to use on the route. Since I'm using a custom component, specifying the icon as shown in the documentation doesn't work.

**Comment by jamesisaac** [comment]
@satya164 Similar, but in my case the params are originating from a NAVIGATE action, then passed onto an INIT action.  I don't think there's any code that would take params from the static config and put them into the router when it's initialised that way.

However, I'm not really sure I see the use case for needing to define params at initialisation.  Can't they just be defined or looked up in the component itself?  What do you have access to in a static route config that can't be reached from components?  Even if you want multiple instances of the same component with different params for different navigators, the idiomatic react way would surely be to create a couple of wrapper components that compose the original with extra props passed in.  `SideDrawerHelloWorld` etc.

**Comment by joshuapinter** [comment]
In my case I'm trying to pass a param from the `launchOptions` to the initial StackNavigator. Is that possible? 

I've created an issue over here to address it directly as well #634.

Thanks.

**Comment by MrHubble** [comment]
@RobertSheaO or @jamesisaac did you figure out how to pass params with the static config rather than the `navigate` action?

**Comment by kelset** [comment]
Pinging OP @RobertSheaO since this issue is quite old and related to an old version of the lib (and because the other issue mentioned by @joshuapinter has been closed long ago). 
If no answer I'll close in 7 days.

**Comment by kelset** [comment]
Hi there @RobertSheaO,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue (especially if it's a bug report) please open a new issue that uses the new Issue Template to provide some more details to help us solve it.
