### ISSUE TITLE
`showLabel` not working for `TabBarBottom`

### ISSUE THREAD

**Issue by danstepanov** [react-community/react-navigation#352]
I have a tab bar nested inside of a stack navigator and, within my `tabBarOptions`, I have `showLabel` set to `false`. However, this does not produce the desired effect of hiding the label and only keeping the icon for a given tab. Below is my code and the tab bar that it produces:

```
const TabBar = TabNavigator({
  Companies: { screen: CompanyList },
  Favorites: { screen: FavoritesPage },
  Portfolio: { screen: PortfolioList },
}, {
  tabBarOptions: {
    activeTintColor: '#F57C00',
    showLabel: false,
  },
});
```

<img width="375" alt="screen shot 2017-02-15 at 11 30 00 pm" src="https://cloud.githubusercontent.com/assets/5482800/23007437/b5184b52-f3d6-11e6-87be-14b2db01a00d.png">

Thanks in advance for any input :)

**Comment by sonnylazuardi** [comment]
@danstepanov is it solved?

**Comment by danstepanov** [comment]
@sonnylazuardi it is yes, simply update to the latest beta of the project and you should be all good :)

**Comment by pzehle** [comment]
I'm sorry, I have the latest version and it doesn't work for me. Could you please provide another solution?

**Comment by Alexandra-Assembly** [comment]
Hello, I'm currently using `"react-navigation": "^1.0.0-beta.11"` and the `showLabel: false` does not work as expected. How can I fix this?

<img width="380" alt="2017-07-17_1038" src="https://user-images.githubusercontent.com/23174829/28281509-3584958a-6adc-11e7-81b1-d0ffefbe25a4.png">

**Comment by danstepanov** [comment]
@Alexandra-Assembly `false` should not be a string value, it is of type `boolean`. Changing `showLabel: 'false'` to `showLabel: false` should fix your problem.

**Comment by Alexandra-Assembly** [comment]
Oops! My apologies, you are correct @danstepanov & thank you for the speedy reply.

**Comment by bhavyasruthi** [comment]
I am facing same issue now. I am using  "react-navigation": "^1.0.0-beta.22"
TabNavigator(
                                    {
                                      Camera : {
                                                screen : Camera,
                                                navigationOptions: {
                                                    tabBarOptions:{
                                                        showIcon : true,
                                                        showLabel : false, -->I don't want label in this tab
                                                    },
                                                    tabBarIcon: ({ tintColor }) => <Icon name='account-circle' size={26} style={{ color: tintColor }} />
                                                },
                                                },
                                      Chats : {screen : Chats,
                                                navigationOptions:{
                                                    tabBarOptions:{
                                                        showIcon : false,
                                                    },
                                                },
                                                },
                                      Status : {screen : Status},
                                      Calls : {screen : Calls},
                                    },
}
                                    );

Please help me !!

**Comment by nizar2yas** [comment]
same issue with react-navigation :3.11.0

**Comment by vikramkh** [comment]
same

**Comment by jwjoeywalsh** [comment]
Anyone find a fix? Ive tried using a boolean and a string. Not working

**Comment by headhuntar** [comment]
DOC: https://reactnavigation.org/docs/en/material-bottom-tab-navigator.html

If you are using Material Bottom Tab

use ' labeled: false' property

{
    initialRouteName: 'Home',
    labeled: false
 }
