### ISSUE TITLE
Whitespace in StackNavigator Android Toolbar

### ISSUE THREAD

**Issue by timomeh** [react-community/react-navigation#354]
Since upgrading to the new release 1.0.0-beta.5, I've got some whitespace in the Toolbar on the initial screen of the StackNavigator, where the Back Button would be on other screens. (Android)

Setting `header.left` to undefined or something empty didn't work either.

![feb-16-2017 09-41-14](https://cloud.githubusercontent.com/assets/4227520/23013754/473e9694-f42c-11e6-8e2c-0952e19fd9fe.gif)

**Comment by satya164** [comment]
cc @grabbou

**Comment by satya164** [comment]
The transition seems weird too.

**Comment by timomeh** [comment]
I've experimented a bit and used `headerMode: 'float'`, which is normally a iOS thing. That's why the transition looks a bit unusual.

**Comment by satya164** [comment]
@timomeh even with `float`, the transition should be smooth. this seems abrupt.

**Comment by timomeh** [comment]
@satya164 Well, now that you say it, I noticed it too, it looks abrupt.

Also I noticed that styling the Toolbar/Header works differently for `float` and `screen`. But that seems like a different issue.

**Comment by satya164** [comment]
Thanks for the report. Yeah, they should be same. Will ensure that in next beta.

**Comment by grabbou** [comment]
That was fixed a while ago. The whitespace is no longer there.
