### ISSUE TITLE
Support native-base?

### ISSUE THREAD

**Issue by sankhadeeproy007** [react-community/react-navigation#355]
Hi, is there any way I can use custom NavBars, like the one from native-base for example?

**Comment by satya164** [comment]
Native base needs to provide a nav bar compatible with React Navigation. Please file an issue on Native Base repo.

**Comment by sankhadeeproy007** [comment]
How do I customize the navbar in general? The one that comes inbuilt with react-navigation? If I want to add some additional buttons to it, how do I do it?

**Comment by satya164** [comment]
Please check the docs https://reactnavigation.org/docs/navigators/stack

**Comment by sankhadeeproy007** [comment]
Thank!
