### ISSUE TITLE
Too much space between tab labels with TabNavigator

### ISSUE THREAD

**Issue by markflorisson** [react-community/react-navigation#356]
Tab labels/names take up so much space that I cannot even fit three tab labels on the screen (half the label disappears of the screen for the third one). The labels are pretty short too (3, 4 and 6 characters each).

How can we make tab labels take up less space?

**Comment by markflorisson** [comment]
Ah, I noticed this issue occurs only when scrollEnabled is set to true on android. However, I think labels could still take up less space even with scrolling enabled?

**Comment by satya164** [comment]
You can specify the width you want for the tabs in `tabStyle` - https://reactnavigation.org/docs/navigators/tab
