### ISSUE TITLE
StackNavigation into DrawerNavigation header problem.

### ISSUE THREAD

**Issue by jamesalways** [react-community/react-navigation#357]
Hi! I'm new with React Native and I'm doing tests to learn react-navigation.

I have a DrawerNavigation and when I navigate to Profile StackNavigator appears two headers one for drawer and one for StackNavigator. I want hide drawer navigation header when I am in ProfileStackNavigator.

I have:

const ProfileStack = StackNavigator({
    Profile: { screen: Profile },
    Params: { screen: Params }
});

const Drawer = DrawerNavigator(
    {
        Home: { screen: Home },
        ProfileStack: { screen: ProfileStack },
    },
    {
        initialRouteName: 'Home',
        contentComponent: Menu
    }
);

const Navigator = StackNavigator({
    Login: { screen: Login },
    Drawer: { screen: Drawer },
});

 
![screen shot 2017-02-16 at 10 36 34](https://cloud.githubusercontent.com/assets/3009870/23015730/3736d128-f434-11e6-9001-42fd3f0f25d6.png)

How do i solve it?

Thanks!!

**Comment by maticaputti** [comment]
You can use **headerMode** option within **StackNavigatorConfig** to disable that headers.
Here's an example: https://github.com/react-community/react-navigation/blob/master/examples/NavigationPlayground/js/App.js#L97
Here's the docs: https://reactnavigation.org/docs/navigators/stack#StackNavigatorConfig

**Comment by jamesalways** [comment]
Thanks!!

**Comment by AnkitKumarRathi** [comment]
n,,

**Comment by AnkitKumarRathi** [comment]
above link doesn't working.

**Comment by brentvatne** [comment]
here you go https://reactnavigation.org/docs/stack-navigator.html

**Comment by alizons** [comment]
what if I want to have 1 **drawer** header for drawer navigator and another **stack navigator header** for nested stack navigator routes? If I will hide stack nav header with headerMode - I won't be able to use build in "back" button to navigate back between stacks
