### ISSUE TITLE
Nest TabNavigator within DrawerNavigator

### ISSUE THREAD

**Issue by mgtitimoli** [react-community/react-navigation#358]
Hi there,

I'm trying to nest a **TabNavigator** within a **DrawerNavigator** with no luck, this should work, right?

Thanks

**Comment by goncalomarques** [comment]
Can you provide code examples?

**Comment by mgtitimoli** [comment]
Hi @goncalomarques, sure:

```javascript
import {DrawerNavigator, StackNavigator, TabNavigator} from 'react-navigation';

// scene imports

const HomeScene = TabNavigator({
  discover: {screen: DiscoverScene},
  otherTab: {screen: OtherTabScene}
}, {
  initialRouteName: 'discover',
});

HomeScene.navigationOptions = {
  header: {
    visible: false,
  },
};

const RootScene = DrawerNavigator({
  home: {screen: HomeScene},
  other: {screen: OtherScene},
}, {
  initialRouteName: 'home',
});

export default StackNavigator({
  tour: {screen: TourScene}, // has a skip button that navigates to root
  root: {screen: RootScene},
}, {
  initialRouteName: 'tour',
});
```

The problem I'm having is that **TabBar** is not being renderer...

**Comment by goncalomarques** [comment]
@mgtitimoli 

A created a nested version of `./examples/NavigationPlayground/js/Drawer.js`. You just need to specify a DrawerScreen as the return of your TabsNavigator.

[Here is the code](https://gist.github.com/goncalomarques/6260808a1dd3243cb1a4792c47639ad9)

**Comment by mgtitimoli** [comment]
Thanks @goncalomarques,

Sorry but I'm not getting what you mean by returning the Drawer from the TabsNavigator, and I tried to get the pattern from your gist, but I couldn't find it...

What I don't know is if am I doing something wrong? I mean, right now I have the following:

- **MainNavigator**
  - routes: tour, root (screen: DrawerNavigator)...
  - default: tour
- **DrawerNavigator** (root route)
  - routes: some, home (screen: TabsNavigator)
  - default: home
- **TabsNavigator** (home route)
  - routes: discover, activities, etc
  - default: discover

So, from the docs, and continuing with what we were doing with the prev navigator we were using before integrating with **react-navigation**, we are nesting all the routes under the **Drawer**, so I was expecting it not to block any nested navigator that I could have in any of their child routes, that in fact is what is happening now with the home route that is a **TabsNavigator**.

Maybe I should need to specify some `navigationOptions` in the drawer to tell it that it has to show the tabs, should I?

**Comment by goncalomarques** [comment]
Holy f*... I just realized I copied the wrong file to the gist I provided you with @mgtitimoli

(I edited the content)[https://gist.github.com/goncalomarques/6260808a1dd3243cb1a4792c47639ad9]

What you have to do is create a `TabNavigator` and provide it as a screen to one of your DrawerNavigator. eg: 

``
const TabsScreen = TabNavigator({
  Settings: {
    screen: SettingsScreen
  },
  Profile: {
    screen: ProfileScreen
  }
});




const DrawerExample = DrawerNavigator({
  Inbox: {
    path: '/',
    screen: InboxScreen,
  },
  Drafts: {
    path: '/sent',
    screen: DraftsScreen,
  },
  Stacks: {
    path: '/stacks',
    screen: TabsScreen
  }
}, {
  initialRouteName: 'Drafts',
  contentOptions: {
    activeTintColor: '#e91e63',
  },
});
``

**Comment by satya164** [comment]
So what exactly is not working?

**Comment by mgtitimoli** [comment]
Hi @satya164,

The last code @goncalomarques shared is the same that I have here, and I'm still not able to make it work.

The issue is that no tabs are shown when a **TabsNavigator** has a **DrawerNavigator** as its inmediate ancestor in the routes tree.

**Comment by arnsa** [comment]
Did anyone managed to make it work?

**Comment by mgtitimoli** [comment]
@satya164 I've just created an example that exemplifies this error:

https://sketch.expo.io/Hy0JaOajx

There should be tabs in HomeScene (Scene1, Scene2) and there is none.

Any thoughts?

**Comment by mgtitimoli** [comment]
@satya164 I tested it with **1.0.0-beta.7** and is working fine, you can close this issue, thanks.

**Comment by marianna7731** [comment]
Is it possible to access all tabs from the drawer? I mean in @mgtitimoli  example I would like to be able to tap both scene 1 and scene 2 from the drawer.

**Comment by garcia1994** [comment]
mgtitimoli, podrias pasarme el ejemplo, estoy tratando de hacer el mismo funcionamiento, sin embargo el link ya no funciona.
https://sketch.expo.io/BJb0Au6sg

**Comment by brentvatne** [comment]
@garcia1994 https://snack.expo.io/@notbrent/react-navigation:-nested-navigators-with-tabs
