### ISSUE TITLE
Header elements are not centered

### ISSUE THREAD

**Issue by zoontek** [react-community/react-navigation#359]
Hi,

I've just updated to beta 5 and notice that when you change the header height, the header elements are not vertically aligned (because it ignores the height of the status bar).

![screenshot of the problem](https://cdn.pbrd.co/images/yZKInLs8U.png)

My StyleSheet is basic:

```javascript
const styles = StyleSheet.create({
  background: {
    backgroundColor: colors.primary,
    height: 80,
  },
  title: {
    fontSize: 16,
    fontWeight: '400',
    color: 'white',
    backgroundColor: 'yellow',
  },
  button: {
    backgroundColor: colors.transparent,
    color: 'white',
    fontSize: 16,
    backgroundColor: 'yellow',
  },
})
```

**Comment by grabbou** [comment]
I believe it's a duplicate, anyways, my pending PR changes the way layout is calculated and centered (no absolute positioning) and I believe that should fix the issue.

**Comment by grabbou** [comment]
As I suspected, it's no longer an issue.

**Comment by grabbou** [comment]
![Uploading Screen Shot 2017-02-20 at 13.49.11.png…]()

**Comment by paweldziura** [comment]
```
static navigationOptions = {
    ...
    header: ({ state, setParams }) => ({
      style: { height: 40, backgroundColor: '#0099ff', justifyContent: 'center' },
      titleStyle: {  },
      tintColor: '#fff'
    })
  }
```
