### ISSUE TITLE
Add support for tintColor in header

### ISSUE THREAD

**Issue by knowbody** [react-community/react-navigation#36]
This should style a text and icon colors. See #30 for reference

**Comment by grabbou** [comment]
That sounds to me like a good first task.

**Comment by Ehesp** [comment]
If someone can explain what the best naming convention for styling all of the components would be this should be fairly straightforward. 

1. Title/text colour 
2. Back arrow tint colour 

Anymore? E.g. Would titleStyle and tintColor as 2 individual props on header be ok? 

Cc @satya164

**Comment by satya164** [comment]
We should add a single `tintColor` property which sets color for both title and back button.

**Comment by Ehesp** [comment]
Okay sounds good, will see if I can get this in within the next few hours.

**Comment by grabbou** [comment]
There's already `tintColor` prop on a back button that is applied.

**Comment by Ehesp** [comment]
@grabbou from the looks of it though the Header class only applies the onPress prop. On my phone so could be wrong but will check it out soon.

**Comment by satya164** [comment]
The `BackButton` accepts the prop, but `Header` component doesn't accept such an prop, and the screen navigation options aren't passed either.

**Comment by Ehesp** [comment]
@satya164 @grabbou 

I'm applying `tintColor` to my `navigationOptions.header` like so:

```javascript
header: ({ state }) => {
      return ({
        title: 'Some title',
        tintColor: '#ffffff',
```

However, when logging out `header` & `props` [here](https://github.com/react-community/react-navigation/blob/master/src/views/CardStack.js#L206), it logs twice directly after each other (double re-render or previous scene => new scene??). The first time `header` does not contain my prop, second time it does, but misses the `left` property.

Is this correct? 

```javascript
return renderLeftComponent(props);
```

This passes in props, but does not include the `tintColor` prop - apologies I'm a bit confused as to how to get this from within the `renderLeftComponent`.

**Comment by satya164** [comment]
Your usage looks correct. But hold off a bit since @grabbou is doing some refactors right now.

> it logs twice directly after each other (double re-render or previous scene => new scene??). The first time header does not contain my prop, second time it does, but misses the left property.

I'm not fully sure, but I think it might be related to #48

**Comment by jsdario** [comment]
API seems to have changed in 1.0.0-beta, is there a way to use tintColor from `navigationOptions = ({navigation}`?

**Comment by grabbou** [comment]
Yeah, just return `headerTintColor` and you are done.

**Comment by guigrpa** [comment]
May I ask: why a single color to tint header title *and* back icon/label? In the standard header, the title is black and the back button is blue (on iOS). I'd like to change the back button color, is there some prop to do that?

**Comment by sUdayBhaksar** [comment]
There's already tintColor prop on a back button that is applied.

<div class="highlight highlight-source-js">
<HeaderBackButton tintColor = '#fff' onPress={() => navigation.goBack(null)} />
</div>

**Comment by davidcort** [comment]
> There's already tintColor prop on a back button that is applied.
> 
> <HeaderBackButton tintColor = '#fff' onPress={() => navigation.goBack(null)} />

Thanks, works !!
