### ISSUE TITLE
Disable logging?

### ISSUE THREAD

**Issue by sankhadeeproy007** [react-community/react-navigation#360]
I just followed the example from the docs and noticed some lag when rendering heavy components on Android. On enabling debugger, it was somewhat faster as the Navigation actions were logged on chrome. Question is, how do I disable logging from the router? I could not find anything regarding that in the docs (or maybe I didn't know where to look for it).

**Comment by agrcrobles** [comment]
are you using a redux middleware for logging?

**Comment by ElliottJRo** [comment]
I think @sankhadeeproy007 is talking about the dispatch logging. If thats the case, I don't think there is a way to disable it atm. You can disable it yourself by modifying local version in `/src/createNavigationContainer.js`

**Comment by satya164** [comment]
I think we should use a custom function for logging so we can enable it for development and not for library consumers. PR is welcome.

**Comment by ericvicenti** [comment]
This behavior lives in [`createNavigationContainer`](https://github.com/react-community/react-navigation/blob/a7b124305393a8e392621a32e49fa96a3a14c6c9/src/createNavigationContainer.js). It also logs URI requests

I think we should add something like `onNavStateChange` to `containerOptions`, which is currently documented in the [wrong](https://github.com/react-community/react-navigation/issues/403) [place](https://reactnavigation.org/docs/navigators/custom).

The default behavior of `onNavStateChange` would literally just be the logging function, so if you want to disable logging you could simply override it with an empty function.

**Comment by ARMATAV** [comment]
+1 Please add an option for disabling the logging

**Comment by tomykho** [comment]
+ 1

**Comment by joemckie** [comment]
+1, related to [this issue](https://github.com/evgenyrodionov/redux-logger/issues/32). I notice a definite lag in some screens due to logging.

**Comment by csotiriou** [comment]
+1 for providing a way to disable logging.

React native's log is extremely slow. We are noticing 7 seconds (having debugging disabled!) when we have a screen with 30 items inside, due to the navigator displaying the contents of the state, which has a Realmjs object with 30 items inside it.

**Comment by geekvijay** [comment]
+1 for Disabling Logging. it takes one at least a second to navigate to another screen and resulting in bad UX.

Is anyone figured out any patch for this ?

**Comment by adi69** [comment]
`RCTSetLogThreshold(RCTLogLevelError);` will disable all the logging except in case of Error or Fatal Exception.

**Comment by tomykho** [comment]
+1

**Comment by iboxgithub** [comment]
@ericvicenti  Don't you think the logging should be disabled by default?

**Comment by grabbou** [comment]
It has been fixed. You can now disable logging by setting https://reactnavigation.org/docs/navigators/#onNavigationStateChange-prevState-newState-action to `null` or your own implementation.

**Comment by EyalSi** [comment]
Can you please explain how exactly? where do you set it to null?

**Comment by EyalSi** [comment]
BTW, though react-navigation is still in beta, can the logs be enabled with some flag? instead of defaulting to console? ;)

**Comment by superandrew213** [comment]
@EyalSi use it like this:

```
const AppNavigator = StackNavigator(SomeAppRouteConfigs);

class App extends React.Component {
  render() {
    return (
      <AppNavigator onNavigationStateChange={null} /> // <----- Here
    );
  }
}
```

**Comment by jslz** [comment]
Seeking help on this / asking for more/clearer docs: We originally used
```
<AppNavigator
    navigation={addNavigationHelpers({ dispatch: dispatch, state: navigation })}
  />
```

so I added the line mentioned [above](https://github.com/react-community/react-navigation/issues/360#issuecomment-306981742)

```
<AppNavigator
    onNavigationStateChange={null} // disable logging for performance reasons.
    navigation={addNavigationHelpers({ dispatch: dispatch, state: navigation })}
  />
```

but i get

```
<Error>: *** Terminating app due to uncaught exception 'RCTFatalException: Unhandled JS Exception: This navigator has both navigation and container props, so it is unclear if it should own its own state. Remove props: "onNavigationStateChange" if the navigator should get its state from the navigation prop. If the navigator should maintain its own state, do not pass a navigation prop.', reason: 'Unhandled JS Exception:...
```

I have been reading to try to understand how to get what we want, but I am so far still apparently resolutely clueless about it. Any helpful directions would be appreciated :-)

**Comment by jordanmkoncz** [comment]
@jslz I'm getting the same error as you. It's coming from `NavigationContainer._validateProps` in `react-navigation/src/createNavigationContainer.js`, which is preventing the app from running when you've passed a `navigation` prop to the navigator (meaning the navigator is not "stateful") and then you also try to pass onNavigationStateChange.

@grabbou I think something needs to change here because currently your solution of passing `onNavigationStateChange={null}` to the navigator won't work for anyone using Redux with react-navigation.

**Comment by jordanmkoncz** [comment]
@jslz I've created a separate issue for the problem we're having, see https://github.com/react-community/react-navigation/issues/2074.

**Comment by MrLoh** [comment]
React navigation is great, but this logging is really bad. Basically makes it unusably slow on android. And it's incompatible with redux, why not just disable it by default, like you would expect. I've never used a library that logs something to the console by default other than errors and warnings.

**Comment by p30arena** [comment]
Im not using REDUX but still doesn't work!

`
const UsersRouter = StackNavigator({
	Home: {
		screen: Home
	},
	Business: {
		screen: Business
	},
	ResultsMap: {
		screen: ResultsMap
	}
}, {
	headerMode: 'none'
});

export default UsersRouter;
`

and

`<UsersRouter onNavigationStateChange={null} />`

**Comment by Noitidart** [comment]
@p30arena - setting null as a prop does work for me:

```
// @flow

import React, { Component } from 'react'
import { AppRegistry, View } from 'react-native'
import { Provider } from 'react-redux'

import store from './flows'

import AppNavigator from './AppNavigator'

import styles from './styles'

export default class App extends Component {
    render() {
        return (
            <Provider store={store}>
                <View style={styles.app}>
                     <AppNavigator onNavigationStateChange={null} />
                    <FAB />
                </View>
            </Provider>
        )
    }
}

AppRegistry.registerComponent('trustedfamily', () => App);
```

And AppNavigator is:

```
// @flow

import React, { Component } from 'react'
import { StackNavigator } from 'react-navigation'

import ScreenLanding from './ScreenLanding'
import ScreenContact from './ScreenContact'
import ScreenHelp from './ScreenHelp'
import ScreenHub from './ScreenHub'
import ScreenDemo from './ScreenDemo'
import ScreenTwo from './ScreenTwo'
import ScreenThree from './ScreenThree'

import styles from './styles'

const AppNavigator = StackNavigator(
    {
        demo:    { screen:ScreenDemo },
        two:     { screen:ScreenTwo },
        three:   { screen:ScreenThree }
    },
    {
        initialRouteName: 'demo'
    }
)

export default AppNavigator
```

**Comment by alxvallejo** [comment]
+1

**Comment by tom-p-uk** [comment]
+1

**Comment by gurmukhp** [comment]
How would this work with a tabbed bar approach?

```
const tabs = [{
  label: 'Latest',
  screen: 'Latest',
  title: 'hello'
},{
  label: 'History',
  screen: 'History',
},{
  label: 'Settings',
  screen: 'Settings',
}
];

Navigation.startTabBasedApp({
  tabs,
  tabsStyle: {
  },
  appStyle: {
    navBarHidden: true,
  }
```

**Comment by brentvatne** [comment]
logging has hidden behind an env var flag `REACT_NAV_LOGGING` for some time now, see: https://github.com/react-navigation/react-navigation/blob/ac83cf804c9ece7a92ee78f1d93ed4b5868559c2/src/createNavigationContainer.js#L102-L123

locking this thread
