### ISSUE TITLE
How can I add custom component adjacent to Navigator?

### ISSUE THREAD

**Issue by MintyOwl** [react-community/react-navigation#361]
![tabnavigator](https://cloud.githubusercontent.com/assets/7389244/23030545/16bc76ea-f494-11e6-835d-88286204e95d.png)

In the image above I have a menu button and title (" View all settings ") placed above the TabNavigator. I would like to achieve this effect. How can this be achieved? 

Something like the one below. 

```
const Composite= ( ) => ( 
  <View>
      <MenuComponent />
      <MyTabNavigator />
</View>
 )
```

Or by allowing TabNavigator is render `this.props.children`, like this

```
const Composite= ( ) => (       
      <MyTabNavigator><MenuComponent /></MyTabNavigator>
 )
```

I cannot achieve this effect. Wonder how to do it!

Thanks

**Comment by satya164** [comment]
Check this https://github.com/satya164/PocketGear/blob/master/src/components/PokemonInfo.js

**Comment by MintyOwl** [comment]
Thanks, I will check it out.

**Comment by MintyOwl** [comment]
Ahh I was missing  
```
container: { 
    flex: 1,
  }
```
on the root View element..now its working..
