### ISSUE TITLE
Back button doesn't work while scrolling

### ISSUE THREAD

**Issue by smkhalsa** [react-community/react-navigation#364]
I have a ListView within a StackNavigator. While the ListView is scrolling, touches to the back button don't appear to work.

**Comment by smkhalsa** [comment]
@satya164 any ideas about this?

**Comment by Choujiji** [comment]
I also met this question, my custom button works no more when scrolling...

**Comment by jaygarcia** [comment]
I've had similar issues, except, when using StackNavigator and ListViews, it works fine.
![scroll-works](https://cloud.githubusercontent.com/assets/180031/25297067/9be29e88-26b9-11e7-9f74-f61af3c403b8.gif)

However, if i nest within a TabView, that is TabView has a child of StackNavigator, i run into this. 
![scroll-not-works](https://cloud.githubusercontent.com/assets/180031/25297071/9f05b410-26b9-11e7-87c7-264b1f2971ce.gif)

**Comment by smkhalsa** [comment]
@jaygarcia I also have a nested Stacks in Tabs.

**Comment by spencercarli** [comment]
Hi! Since this issue has been quiet for a while I'm going to go ahead and close it. If the issue persists in the latest version of React Navigation please re-open!
