### ISSUE TITLE
Question: reactnavigation.org down most of the time..

### ISSUE THREAD

**Issue by andrispraulitis** [react-community/react-navigation#365]
Hi,

Anyone else having trouble accessing docs website? For me seems to be either very slow or down most of the time. I'm from UK

**Comment by ElliottJRo** [comment]
Maybe its getting too popular ;) If you just need the docs, might be easier to view through [github](https://github.com/react-community/react-navigation/tree/master/docs/api)

Some of the linking will be off since doc files expect url to be https://reactnavigation.org/docs/

**Comment by grabbou** [comment]
We use [`now`](https://zeit.co/now) to deploy the website, so if there are any downtimes observed, we might want to report them directly. I haven't noticed any downtimes, however browsing docs via Github is also a solution.
