### ISSUE TITLE
Navigating to existing screens without adding to stack

### ISSUE THREAD

**Issue by michaelduminy** [react-community/react-navigation#370]
I'm having trouble understanding if it's possible to have singleton/static versions of screens.

```
StackNavigator
  - LoggedIn
    - DrawerNavigator
      - Main
        - StackNavigator (1)
          - Home
            - TabNavigator
  - Notifications (2)
```

Notes:
(1) - This stack navigator provides my main header which needs the drawer to cover it when open.
(2) - The Notifications screen is outside of the drawer because I don't want the drawer to be available from within it. I can't see a way of disabling the slide in ability per screen.

StackNavigator (1) has a notifications button on it which opens the Notifications (2) screen. When navigating from the Notifications screen to a tab in the TabNavigator there are two issues:
1. I need to first specify the `LoggedIn` route before specifying a tab route.
2. (main issue) When the app navigates to the tab from the Notifications screen it recreates the entire hierachy of views, placing them on top of the stack. I understand why this is but I'd like to be able to have "static" views that do not get created again, because now I am forced to either:
  * deal with an app slowing down as multiple instances of the app live on top of each other **OR** 
  * use the reset action which solves the multiple instance problem but still recreates the views, therefore firing all the `componentDidMount` events and other various startup events.

I'd like to be able to say something like: this screen is static and should only ever exist once.
Now this could be problematic to deal with within the backstack so maybe we could enable you to say something like: close this screen (Notifications in this example) and open this one (everything under LoggedIn) but don't recreate it, just navigate to a part inside of it.

I realise this could be solved by using the back action on the Notifications screen before issuing the `navigate` to tab action. However I'd like my screens to not have to care where they are in the navigation stack, in my mind they should just tell the root navigator where they want to go and not have to implement any specific logic wherein they need to know how the stack is structured.

**Comment by michaelduminy** [comment]
In Android native dev you can set a screen to be `"singleTask"`, this is essentially what I'm trying to do here. 

> The system creates a new task and instantiates the activity at the root of the new task. However, if an instance of the activity already exists in a separate task, the system routes the intent to the existing instance through a call to its onNewIntent() method, rather than creating a new instance. **Only one instance of the activity can exist at a time.** https://developer.android.com/guide/components/activities/tasks-and-back-stack.html#ManagingTasks

I will probably end up extending the Router to deal with this.

**Comment by wilomgfx** [comment]
My issue was closed because it is related to this one. But have we got any advancement/ideas on how to do this ?

**Comment by wilomgfx** [comment]
@michaelduminy i think i made it work but looking deep into the source code to see how routers were working. I'll update when im sure everything is working correctly :)!

**Comment by michaelduminy** [comment]
@wilomgfx yes! Please let me know, even if it doesn't work 100%. It'll still help.

**Comment by wilomgfx** [comment]
Ill write a more detailed example on how it works but essentially i keep the index of the route i want kept open in the stack, and then with a custom redux action i navigate by that index. 

The animations are quite clunky when using the StackRouter, which is understandable because its used to route either one index above or under itself. It also makes it so the ```BACK``` action adds my home screen every time on time.  Which is obviously unnecessary.

Probably will end up needing to create a custom router or something of that sort with the Router API.

**Comment by ericvicenti** [comment]
This would be fixed by adding a key to the navigate action. Tracking that feature in https://github.com/react-community/react-navigation/issues/135

**Comment by wilomgfx** [comment]
@ericvicenti great, indeed that's what i was aiming for.
I will look into #135

**Comment by PerspectivesLab** [comment]
is there any news about this ? i got a stacknavigator, and in one of its screens a webview, each time i call the screen to sho, the webview gets recreated, i would like to reuse the screen instance, is there a way to achieve this ? thx

**Comment by wilomgfx** [comment]
@PerspectivesLab yep it's exactly my use case too.
