### ISSUE TITLE
What are the difference between StackNavigator and StackRouter?

### ISSUE THREAD

**Issue by vzhen** [react-community/react-navigation#376]
When to use?

**Comment by satya164** [comment]
https://reactnavigation.org/docs/routers/

**Comment by johngoren** [comment]
Dudes, let me be real for a second...we need a new navigation library. In every thread on the pros and cons of React Native, nobody ever lists React Navigation as a pro.

The docs are a nightmare. The pleas for help on Github are a desperate forest of thumbs-ups. Common sense questions lead to dismissive requests, e.g. https://github.com/react-community/react-navigation/issues/376.

Who do we talk to at the React Native project about the need for something better?

**Comment by Tav0** [comment]
Totally weird, I also would like to know more about this smh
