### ISSUE TITLE
Please Date Your Blog Posts

### ISSUE THREAD

**Issue by flyingace** [react-community/react-navigation#378]
So far I am loving the documentation and the speed at which you are providing updates and working on this project. But as you add blog posts it would be helpful to have the posts dated so we could see how recent the information provided therein is.

In my general experience, updates are usually made to repositories first and blog posts about those updates tend to lag behind so this may help sort out any confusion.

**Comment by ericvicenti** [comment]
I agree, and this should be pretty easy to fix- would you like to jump in and add it yourself?

Just follow the [website section of the contributors doc](https://reactnavigation.org/docs/guides/contributors), and you should be up and running!

**Comment by flyingace** [comment]
Okay, I'll see if I can't get that taken care of!

**Comment by flyingace** [comment]
@ericvicenti https://github.com/react-community/react-navigation/pull/410

**Comment by skevy** [comment]
Closed in https://github.com/react-community/react-navigation/commit/3a1766cb788a3ba3a5b5c474bae10b88be666a31
