### ISSUE TITLE
custom components in navigation bar title area?

### ISSUE THREAD

**Issue by RoboTeddy** [react-community/react-navigation#379]
Apple's iOS Human Interface Guidelines suggest: 

> Consider putting a segmented control in a navigation bar at the top level of an app. This is especially useful if doing so helps to flatten your information hierarchy, making it easier for people to find what they’re looking for.

(via https://developer.apple.com/ios/human-interface-guidelines/ui-bars/navigation-bars/)

Looks like `title` in `navigationOptions` is just a string -- perhaps we should change to accommodate the above?

**Comment by satya164** [comment]
You can use react elements in `navigationOptions.header`

**Comment by farhanmannan** [comment]
@satya164 is it possible to style the TabTopBar to look like iOS's UISegmentedControl?
