### ISSUE TITLE
Wrong positioning for indicator in TabNavigator

### ISSUE THREAD

**Issue by ahmedlhanafy** [react-community/react-navigation#380]
### I'm having this issue where the indicator doesn't have the correct position in `TabNavigator`
 
![](https://cloud.githubusercontent.com/assets/7052827/23097312/7fe17070-f639-11e6-8ee4-5269aaccb0d3.gif)

**Comment by satya164** [comment]
We don't support  dynamic tab widths yet. Here your `Acount info` label is too big. Adjust the padding with `tabStyle` or set a width.

Right now, the only way we can set width automatically is by waiting for layout to calculate the width, which will cause 1 frame delay in rendering and is probably not the best experience. React Native's latest feature to provide percentage width will help with this, but it's not in stable version yet, and we'll proabably want to wait for few more versions before using it.
