### ISSUE TITLE
Decorators + static navigationOptions

### ISSUE THREAD

**Issue by brunolemos** [react-community/react-navigation#381]
If I use decorators, the navigator does not detect the `static navigationOptions`.
Is there a better way to do it than the way below?

This does not work:
```jsx
@connect(mapStateToProps)
@withTheme
export default class extends React.PureComponent {
  static navigationOptions = {
    tabBar: { label: 'CustomLabel' },
  }
```

This works but it's not cool to have to do it when using class:
```jsx
@connect(mapStateToProps)
@withTheme
class MyClass extends React.PureComponent {
}

MyClass.navigationOptions = {
  tabBar: { label: 'CustomLabel' },
}

export default MyClass;
```

**Comment by jhen0409** [comment]
I guess the `withTheme` haven't do static hoisting, I'm sure `connect` [have](https://github.com/reactjs/react-redux/blob/master/src/components/connectAdvanced.js#L282).

**Comment by brunolemos** [comment]
@jhen0409 interesting , thanks. I'll fix that with a PR.
