### ISSUE TITLE
Change tabBarOptions on runtime

### ISSUE THREAD

**Issue by brunolemos** [react-community/react-navigation#382]
In an app with themes, the user can change it from light to dark, for example.
How to update the tabbar background color without having to re-instantiate the whole TabNavigator?

**Comment by satya164** [comment]
You can wrap tab bar in your custom component and pass props directly instead of using `tabBarOptions`

**Comment by brunolemos** [comment]
@satya164 thanks.

This is my solution, for anyone trying it:

`TabBar.js`
```jsx
import React from 'react';
import { Platform } from 'react-native';
import { TabNavigator } from 'react-navigation';
import { withTheme } from 'styled-components/native';

const DefaultTabBar = TabNavigator.Presets.Default.tabBarComponent;

export default withTheme(({ theme, ...props }) => (
  <DefaultTabBar
    {...props}
    activeTintColor={theme.brand}
    inactiveTintColor={theme.base05}
    indicatorStyle={{
      backgroundColor: theme.brand,
    }}
    scrollEnabled={false}
    showLabel={Platform.OS !== 'android'}
    showIcon
    style={{
      backgroundColor: theme.base00,
      borderTopColor: theme.base02,
    }}
  />
));
```

`AppNavigator.js`
```jsx
// @flow

import { TabNavigator } from 'react-navigation';

import TabBar from './TabBar';

export default TabNavigator(
  {
    // ...
  },
  {
    tabBarComponent: TabBar,
  },
);

```

**Comment by balthazar** [comment]
@harshalkd Use something like redux or a react context, just like Bruno

**Comment by bwillem** [comment]
I need to theme my tab bar, but my tab bar is a nested navigator. I can't use any solution that explicitly renders the navigator: https://reactnavigation.org/docs/en/common-mistakes.html

I can't use screenProps to pass the theme, because there's no way of accessing screenProps in my tabBarOptions

Anyone faced with this?
