### ISSUE TITLE
Specify Back Button iOS Animation Slide Direction

### ISSUE THREAD

**Issue by RobertSheaO** [react-community/react-navigation#384]
The back button animation on iOS slides the previous screen in from the right, rather than the left as expected. Is there a way to change the direction a screen slides in from? Would I need a custom Transitioner for this? I haven't used a Transitioner yet, so not sure wha their scope is.

EDIT: I realized I forgot an important part. I'm using Redux, so I'm dispatching my action as follows:

```JS
dispatch({ type: 'Navigation/NAVIGATE', routeName });
```

I also just discovered the `Navigation/BACK` type; however, that takes me back to the first page of my app, and I want to specify a specific routeName. Any tips?

**Comment by satya164** [comment]
cc @grabbou

**Comment by RobertSheaO** [comment]
Found a way to do it! The initial issue I had was that I had no access to `this.props` inside my `static navigationOptions` where I substitute the left side of the header with my custom component, this I couldn't just simply call "goBack". Turns out, you can access `goBack` and others by specifying `header` as a function, rather than just a plain object.

Documentation is here: https://reactnavigation.org/docs/intro/headers

Code example:
###### notificationsView
```JS
static navigationOptions = {
  header: ({ goBack }) => {
    return {
      left: <BackButton goBack={goBack} />,
    }
  },
};
```

###### BackButton
```JS
<IconToggle name="arrow-back" color={white} onPress={() => this.props.goBack()} />
```

**Comment by philipjc-apacio** [comment]
@RobertSheaO You never actually said how you got the slide direction to change?

**Comment by RobertSheaO** [comment]
The issue I was having was because I was just tossing more and more screens onto my stack, so they’d come in from right. I needed to use the goBack function to remove the current screen from the stack. This causes the expected back transition.

**Comment by philipjc-apacio** [comment]
Thank you, for clarifying.
