### ISSUE TITLE
Reuse react native app code to be in iframe loaded on web and working with react navigation?

### ISSUE THREAD

**Issue by MovingGifts** [react-community/react-navigation#386]
Is there any way we can embed/iframe the react native app into the browser for a web version?

**Comment by satya164** [comment]
Check tools like appetizer. This has nothing to do with React Navigation

**Comment by MovingGifts** [comment]
@satya164 I can't find appetizer, is there a link to it?

The reason I think it has to do with react navigation is because if you navigate via url say `https://` or `http://` in a web browser which has your react native app embedded, `react navigation` would look at the web url and navigate via the nested react native app's react navigation to match the web url scene in the react native app. In other words, `react navigation` would sync between the web url and the nested app url, so they're in sync with which scene to render based on the given web url.

Any idea if this is possible?

**Comment by MovingGifts** [comment]
Okay, got it you meant appetize.io but that's different than what I mean.

So instead of having to create a react website version, what I mean is to write once the react native app, and use that (responsively) as the website too. So when you visit from a web url, using react navigation, it would show it in the app full screen, just like you would a responsive website.

This is a useful idea because of the inconsistencies in components between react native and react, and if we can somehow render the react native app as the responsive website, that would remedy the inconsistencies and having to have a separate react web version. I figured the routing solution would be react navigate since I read it can work for both react and react native.

So essentially some sort of wrapper/container to wrap/contain the react native app and serve it as the website version too, so it's really universal if you know what I mean.

**Comment by satya164** [comment]
You can use something like react-native-for-web or react-primitives, but nothing specific to react navigation. If you look at the routers documentation and website, you can already use it on web.

**Comment by MovingGifts** [comment]
Thank you will look into those :)
