### ISSUE TITLE
How do I go about creating a searchbar at the navbar.

### ISSUE THREAD

**Issue by Kabangi** [react-community/react-navigation#387]
Am looking to achieve the following.

<img width="425" alt="screen shot 2017-02-19 at 8 27 13 am" src="https://cloud.githubusercontent.com/assets/8632600/23099657/40396a88-f67d-11e6-82ed-bf027485a355.png">

**Comment by KakarN** [comment]
Maybe you can place a component to the right header. This component can be a TextInput. And a left component to the left header, which can be a Button for cancel.

**Comment by Kabangi** [comment]
@KakarN Thanks, I have tried that the only problem I have is styling the component. It also feels like a horrible hack doing it this way. I would want the entire searchbar to feel the navbar.
This is what I have. 
` header: (navigation, defaultHeader) => ({
      ...defaultHeader,
      visible: true,
      left:null,
      right:(
        <View style={{flex:1,backgroundColor:'#003552',flexDirection:'row'}}>
          <View style={{position:'absolute',top:-30,backgroundColor:'#fff',flexDirection:'row'}}>
            <SearchBar
              backgroundColor="#003552"
              ref={(ref) => this.searchBar = ref}
              data={this.contacts}
              handleResults={this._handleResults}
              showOnLoad
            />
            <Icon name="search" size={25} color="#fff" style={styles.search} />
          </View>
        </View>
      )
    })`

**Comment by RobertSheaO** [comment]
@Kabangi You can use the `react-native-material-ui` npm, which comes with the component you're looking for out of the box. You'd just include it and set your `headerMode` to none in your `StackNavigatorConfig`.

https://github.com/xotahal/react-native-material-ui/blob/master/docs/Toolbar.md

**Comment by Kabangi** [comment]
I think that approach might save the day. Let me give it a try. Will let you know how it goes. Thanks a lot for this.

**Comment by Kabangi** [comment]
Got it working using your approach. Thanks alot for this.

**Comment by milon87** [comment]
@Kabangi  can you describe more. how you have done that.

**Comment by brentvatne** [comment]
you can copy this example: https://github.com/brentvatne/react-navigation-addon-search-layout

the strategy is basically one of two things -- add a search button to header which when pressed:
1) pushes a new screen without an animation. the new screen has a search bar in the header and is focused. OR
2) set a param when the button is pressed, which then changes the header to render some search component

**Comment by brentvatne** [comment]
you can copy this example: https://github.com/brentvatne/react-navigation-addon-search-layout

the strategy is basically one of two things -- add a search button to header which when pressed:
1) pushes a new screen without an animation. the new screen has a search bar in the header and is focused. OR
2) set a param when the button is pressed, which then changes the header to render some search component

**Comment by hasnaina-entertainer** [comment]
For anyone new here, use 'header' in options and create your own header
