### ISSUE TITLE
DrawerNavigator doesn't content doesn't cover status bar on iOS

### ISSUE THREAD

**Issue by RobertSheaO** [react-community/react-navigation#388]
The drawer on iOS lays over the status bar; however the content inside does not. I've specified a `contentComponent` for my drawer, and set `<StatusBar barStyle="light-content">`. The issue here is that when the drawer opens, the top of the drawer is white, where the status bar is, and the text of the status bar is white due to "light-content" being applied.

![simulator screen shot feb 18 2017 10 28 56 pm](https://cloud.githubusercontent.com/assets/962181/23100006/df395e62-f629-11e6-9e67-56ad65bbe012.png)

**Comment by raymundtusk7** [comment]
Same as #282 and there's a proposed fix in #177.

**Comment by ericvicenti** [comment]
Yeah this does look annoying. I'm closing this out because #282 is already tracking it
