### ISSUE TITLE
how to force Drawer to unmount previous screen

### ISSUE THREAD

**Issue by chandu0101** [react-community/react-navigation#389]
I have a Drawer 
              Home  - Stack Navigator - Home Screen 
                                                           ProfileScreen 
              Settings - Stack Navigator  - Settings Screen 
                                                                Notification Settings Screen

on load HomeScreen rendered and i clicked to `Go To Profile` , and then i opened Drawer clicked on `Settings` -> Settings Screen Rendered and opened Drawer again clicked on `Home` i still see previous Profile Screen , is there any way to force Drawer to unmount previous screen  ?( i don't want them stay in memory when i clicked new Drawer Option)

**Comment by shawngustaw** [comment]
I think what you're looking for is Reset found here: https://reactnavigation.org/docs/navigators/navigation-prop

**Comment by chandu0101** [comment]
@shawngustaw  thanks for reply , here is what i tried 

configured `contentComponent` with my custom component , it has two buttons `Home` and `Settings` 
Home Button - on Press - NavigationActions.reset({ index = 0 , routeName = "HomeDrawer",actions: [NavigationActions.navigate({routeName = "HomeScreen"})

Settings Button - on Press - NavigationActions.reset({ index = 0 , routeName = "SettingsDrawer",actions: [NavigationActions.navigate({routeName = "SettingsScreen"})

***Case 1 :***

after initial load, I clicked on ` Go to Profile`  -> Profile Screen rendered , opened Drawer and Clicked on `Home Button` as expected! Drawer closed and `Home Screen Rendered` but i still see `POP/BACK` animation of Stack Navigation is there any way to avoid it ? 

*** Case 2 **** 

after initial load , i opened Drawer and clicked on `Settings Drawer Button` ,boom red screen on my face :(  , with the following error 

`There is no route defined for key SettingsScreen.
Must be one of: HomeScreen,ProfileScreen`

:s

**Comment by ericvicenti** [comment]
Can you post a minimal code example that demonstrates this issue? Otherwise it is very difficult to see what is broken.

**Comment by chandu0101** [comment]
@ericvicenti  sure , my app code is in scala.js , i'll try to mimic same in js and will post here tomorrow .

**Comment by chandu0101** [comment]
@ericvicenti 
```js

const HomeDrawer = StackNavigator(
  {
    HomeScreen: { screen: HomeScreen },
    ProfileScreen: { screen: ProfileScreen }
  }
);

const SettingsDrawer = StackNavigator(
  {
    SettingsScreen: { screen: SettingsScreen },
    NotificationsScreen: { screen: NotificationsSettingsScreen }
  }
);

const root = DrawerNavigator(
  {
    HomeDrawer: { screen: HomeDrawer },
    SettingsDrawer: { screen: SettingsDrawer }
  },
{
 contentComponent : CustomContent
}
);

//CustomContent
<TouchableOpacity onPress= {() => NavigationActions.reset({ index: 0 , routeName :"HomeDrawer",actions: [NavigationActions.navigate({routeName: "HomeScreen"}) }> 
<Text>Home</Text> 
</TouchableOpacity>
<TouchableOpacity onPress= {() => NavigationActions.reset({ index: 0 , routeName :"SettingsDrawer",actions: [NavigationActions.navigate({routeName: "SettingsScreen"}) }> 
<Text>Settings</Text> 
</TouchableOpacity>

```

Error : `There is no route defined for key SettingsScreen. Must be one of: HomeScreen,ProfileScreen`

**Comment by ericvicenti** [comment]
I don't think you need to use reset actions to do this navigation. You should be able to simply dispatch a `navigate({routeName: 'HomeScreen'})`, instead of the reset action.

**Comment by chandu0101** [comment]
if i understand correctly , let say my `HomeScreen` have 20 list items rendered and i clicked one Item , ProfileScreen Added to stack , and then i opened Drawer i clicked on Settings Buttons now you want me to do `navigate({routeName: 'HomeScreen'}) ; navigate({routeName: 'SettingsDrawer'})` ? if yes isn't HomeScreen  data still in memory ?

**Comment by dggriffin** [comment]
Same problem. @ericvicenti using only navigate is a problem, as it maintains the prexisting stack, and allows the user to use gestures to swipe to the previous screen.

This is especially a problem for initializing user auth -- why would I want a user to be able to go back to a splash screen after pulling their credentials?

**Comment by grabbou** [comment]
> This is especially a problem for initializing user auth -- why would I want a user to be able to go back to a splash screen after pulling their credentials?

Use `reset` then, not `navigate`.

There's currently no way to reset tab router, by that I mean to reset to another tab and change its state. `RESET` is not handled exclusively by TabRouter, it delegates handling to an active tab, and that's why it yields there's no such route.

@ericvicenti do you think we should implement handling of `RESET` in TabRouter itself? Ie. if active tab doesn't handle it, then apply it on tabs.

Then:
```js
NavigationActions.reset({
   index: 0 ,
   routeName : "HomeDrawer",
   actions: [NavigationActions.navigate({routeName: "HomeScreen"}),
})
```
would mean to apply actions on a tab with name `routeName`. 

Sounds like that's what all the people are trying to do.

**Comment by grabbou** [comment]
Closing in favor of #199
