### ISSUE TITLE
Enable/disable drawer gesture for a screen

### ISSUE THREAD

**Issue by justinobney** [react-community/react-navigation#390]
I am trying to figure out how to only enable drawer open gestures on root views of a StackNavigator

**Comment by shawngustaw** [comment]
Off the top of my head I think this could be accomplished by using something like...

```
Stack Navigator -> Drawer -> Root Views
                -> Other Non-Root Views
```

**Comment by ericvicenti** [comment]
@shawngustaw, yep that is the best way to do it for now. Soon we'll have some better example code for this use case

**Comment by justinobney** [comment]
@shawngustaw im not sure I follow...

**Comment by temitope** [comment]
in this same vein is it possible to have the drawer gesture disabled on specific components/pages/views? @shawngustaw @ericvicenti

**Comment by justinobney** [comment]
This is more in line with what I was wondering..

I was thinking of having some state somewhere (redux?) and enable/disable drawer based on that.

ex:

```jsx
<DrawerNavigator disableGuestures={disableGuestures} />
```

**Comment by temitope** [comment]
The gestures seem to eat each other (get in the way) when you have a stack navigator wrapping a drawer navigator. It would be nice to be able to turn both or all of them off.

**Comment by justinobney** [comment]
I have opted to wrap my StackNavigator with react-native-side-menu

**Comment by temitope** [comment]
Thanks for the update. Will look into it if I can't make a good Pr.

**Comment by temitope** [comment]
I think I have identified the two key places for being able to ignoring/disable the gestures, but because it is an imported module it seems we have limited control...it allows one to lock the drawer, so it doesnt open, but what if you just want to disable the gesture but still open the drawer with a button or something? I dont think we have direct access to simply ignore gesture without changing external repo code. Thoughts @ericvicenti @satya164 ?

This is where the drawer layout is created -https://github.com/react-community/react-navigation/blob/master/src/views/Drawer/DrawerView.js#L115

This is where the relevant prop is defined for the module being imported for drawer functionality - https://github.com/react-native-community/react-native-drawer-layout/blob/master/src/DrawerLayout.ios.js#L43

**Comment by satya164** [comment]
The module imitates the API here https://facebook.github.io/react-native/docs/drawerlayoutandroid.html

So I guess we're out of luck if the inbuilt drawer doesn't support it. I guess you can just unlock it just before opening it.

**Comment by temitope** [comment]
@satya164 your expertise in this space is great. i didnt realize it was mimicking that API, if so maybe we are in luck if it is a close imitation as it seems that locking is specifically for gestures according to the documentaiton at the link you showed.

> ...The drawer may still be opened and closed programmatically (openDrawer/closeDrawer).

**Comment by satya164** [comment]
cc @DanielMSchmidt who is working on it

**Comment by temitope** [comment]
cool. I noticed this method that makes me wonder if it actually breaks things. If locking it prevents it from closing? So if it opened programmatically via button press or whatever, will it be stuck out there if we disabled gestures using via `this.props.drawerLockMode === 'locked-closed'` it seems like it :/

@autobind
  _onOverlayClick(e) {
    e.stopPropagation();
    if (!this._isLockedClosed() && !this._isLockedOpen()) {
      this.closeDrawer();
    }
  }

**Comment by satya164** [comment]
I think @DanielMSchmidt can clear it up. I am not very familiar with drawer's codebase.

**Comment by temitope** [comment]
Ok, I will wait to hear back. If it is an issues maybe it can be altered to just check for the `isLockedOpen()` *bool* and not the `isLockedClosed()` , so it can go back to closed by touch (it is partial gesture ignoring i guess)...

**Comment by DanielMSchmidt** [comment]
@temitope @satya164 - sorry for the delay. So to the topic: 

If I understand your question correctly you want to disable the guestures but still be able to open and close it programmatically, am I right? So this should be able with the current implementation when locked. 

To the last comment, I am not entirely sure what the native behavior is. IMHO we could / should build a new library which implements a non-react-native-conform way of a drawer layout (maybe use a configured version in react-native-drawer-layout) to be able to inrtoduce such customizations.

**Comment by temitope** [comment]
@DanielMSchmidt thanks for getting back. 

You are right in a way. We do want to disable only the "slide to open" gesture, but not the "click outside drawer to close" which is arguably a gesture, more of just a click...but yes, to be able to only open it programmatically (e.g. by hamburger menu click) so that on certain pages (like pre-auth login/signup) drawers cannot be accessed perhaps).... that was what the last 2 comments I made were about, looking at the `_onOverlayClick` method that I think allows one to click outside of the drawer to close it.  

hope that clears things up. Whether done in your lib or in a new library build I think it would allow a lot of scenarios to work without too much nested navigation.

**Comment by DanielMSchmidt** [comment]
@temitope Okay I see, so I just tested the `DrawerLayoutAndroid` and it behaves the same as `react-native-drawer-layout`. I also see your problem, so this is my first draft of a solution (would be cool to hear other opinions on this).

I would love to have a `react-native-drawer-layout-polyfill`, which uses the `react-native-drawer-layout` under the hood for ios and windows. This would allow us to enhance `react-native-drawer-layout`  with props like `forceCloseOnClick` or sth. that we could disable in the polyfill version. Does that sound like a cool thing? I would start the development in the next couple days, feel free to do a PR on `react-native-drawer-layout` that suits your needs 👍

**Comment by temitope** [comment]
@DanielMSchmidt im pretty new to the react/react-native space so im not very familiar with the term `polyfill` but will look into it, from your usage of it I assume it is a bridge/lib  between react and the native ios/android languages for a feature... as it stands is there not a unifying piece of code for the ios and android versions of the Drawer Layout (im guessing maybe that si why you mentioned testing `DrawerLayoutAndroid`. 

thoughts @satya164 ?

**Comment by DanielMSchmidt** [comment]
Let me clarify that a bit:

There is a DrawerLayoutAndriod, it is a native Android implementation of this visual pattern. 
The goal with react-native-drawer-layout so far was to implement the exact same behavior as this component to use it cross platform instead of only on Android. This is the current behavior, which I would like to rename to `react-native-drawer-layout-polyfill`. 

This should use a pure js implementation under the hood, which is extendable and called `react-native-drawer-layout` from now on. This allows extending the implementation in a way that is in sync with the react native implementation but also extendable.

**Comment by DanielMSchmidt** [comment]
So I did that now (I had a little time this weekend), [react-native-drawer-layout](https://github.com/react-community/react-native-drawer-layout) would be ready for such a PR now, we can "hide" it behind a feature flag property and should be able to stay compatible with the native implementation.

**Comment by RobertSheaO** [comment]
@DanielMSchmidt, can you elaborate on your solution? Is this to allow disabling gestures, or simply making a polyfill?

**Comment by DanielMSchmidt** [comment]
I split the package to have a polyfill for `DrawerLayoutAndroid` (with `react-native-drawer-layout-polyfill`) and to have a pure JS implementation which we may develop under our own means and enhance with features like adding a property `forceCloseOnOverlayClick` which differs from the "original" behavior

**Comment by annelorraineuy** [comment]
From my understanding, #793 extends `drawerLockMode` just like in DrawerLayoutAndroid, but I want to disable the swipe gesture just for a particular screen within the stack. Is this currently possible in `1.0.0-beta.9`? 

Anyone got a workaround going?

**Comment by mynameisbams** [comment]
Is there a solution to this issue?

**Comment by KingDr** [comment]
In my case, I've disabled all gestures( pan gesture and tap gesture--the shadow layer), only reserved the outer button action for `DrawerOpen` and `DrawerClose`. 

Maybe you'd like to try it out: 
open `YourProjectRootDir/node_modules/react-native-drawer-layout/dist/DrawerLayout.js`,  in function `_isLockedClosed` and `_isLockedOpen`, just `return true`.

**Comment by ryanvanderpol** [comment]
@annelorraineuy did you ever figure out a workaround for disabling the swipe gesture for nested `StackNavigator` screens?

**Comment by annelorraineuy** [comment]
@ryanvanderpol unfortunately not. I switched to [react-native-navigation](https://github.com/wix/react-native-navigation) instead, which gave us better performance for our case. Better modal handling too.

**Comment by cwagner22** [comment]
So we have to switch to react-native-navigation just to be able to disable the drawer for some screens? I just switched from react-native-router-flux  😭

**Comment by annelorraineuy** [comment]
Sorry! Just to be clear: there's **no** way to disable drawer gesture **per screen** yet on react-native-navigation, but there is a way to disable the open drawer gesture itself -- and that's what I compromised on. 

For react-navigation, #793 is still not integrated so i was stuck.

**Comment by ryanvanderpol** [comment]
I ended up taking #793 and merging it into my own fork and installing that via npm and it works for me 👍

**Comment by cwagner22** [comment]
Thank you, it's working!

**Comment by gouravsood** [comment]
@cwagner22 what you did to get it working? I am also trying to disable the gesture only for Drawer?

**Comment by cwagner22** [comment]
@gouravsood Fork #793 and install that version instead.
Or `npm i -S https://github.com/martnu/react-navigation#pass-down-drawer-lock-mode`
Then you can do:
```
  SomeScreen: {
    screen: SomeScreen,
    navigationOptions: ({navigation}) => ({
      drawerLockMode: 'locked-closed'
    })
  }
```

**Comment by gouravsood** [comment]
@cwagner22 Thanks a lot for suggesting this fix. I have tried to follow this fix but not able to get the drawer locked. Still my app is pushing me out after i have logged in, when from home screen swiping left to right to open drawer.

I am using https://github.com/start-react/native-starter-kit as base for my app and tried the same solution on this. To show what I am doing, I have forked the native-starter-kit here: https://github.com/gouravsood/native-starter-kit and checked in the changes you suggested by referencing your version of PR https://github.com/martnu/react-navigation#pass-down-drawer-lock-mode

I have done the changes in as shown here https://github.com/gouravsood/native-starter-kit/commit/855dabe65d8d069931ec7d9c7442c7b57d3fc17b but not able to make it work.

Would really appreciate if you can guide how I can fix it in this version of code I shared.

Thanks,
Gourav.

**Comment by cwagner22** [comment]
@gouravsood `drawerLockMode: 'locked-closed'` is to prevent the drawer from opening up with gestures but this doesn't work with your code for some reason. I couldn't find the exact reason so I'd suggest you to try with the simple react-navigation example first.
If what you want is disable swiping back but keep the drawer openable with swipe then maybe using 
```
this.props.navigation.reset({
    index: 0,
    actions: [
      this.props.navigation.navigate("Home")
    ]
  })
```
instead of
```
this.props.navigation.navigate("Home")
```

would work. (`login/index.js`) I haven't tested though.

**Comment by gouravsood** [comment]
Thanks a lot @cwagner22 for the idea of resetting the navigation. That was the trick and I did it in Navigation Reducer using below code which is now resetting navigation state in the store to home after success login. Now Swipe works and app is going back to login!
      
      const resetAction = NavigationActions.reset({
        index: 0,
        actions: [
          NavigationActions.navigate({ routeName: 'Home'})
        ]
      });

      nextState = AppNavigator.router.getStateForAction(
        NavigationActions.navigate(resetAction),
        state
      );

PS: nextState is returned back to store.

**Comment by kelset** [comment]
A lock functionality has been added in `beta13` via #1377, so this can be closed.

**Comment by prateek3255** [comment]
Try adding these navigation options with screens defined in drawer navigator

```
DrawerNavigator({
   ...
      Login:{screen:Login, 
                 navigationOptions:({navigation})=>({
                        drawerLockMode:"locked-closed"
                })}
    ...
})
```

**Comment by brentvatne** [comment]
more info in https://github.com/react-navigation/react-navigation/issues/4441

**Comment by shreepadavasanth** [comment]
thankyou @chriswt_ it worked awesome
