### ISSUE TITLE
Is it possible to make tabs not fill available width?

### ISSUE THREAD

**Issue by cmrichards** [react-community/react-navigation#391]
Like the Google play movies app, and many others.

**Comment by ericvicenti** [comment]
cc @satya164, this seems like a reasonable request

**Comment by satya164** [comment]
You can use `tabStyle` to set a width for the tabs

**Comment by nonameolsson** [comment]
@cmrichards Did you get this to work? Is it possible to have an adaptive width depending of the length of the text in the tab?

**Comment by cmrichards** [comment]
@nonameolsson  I haven't had a chance to test it yet.  

> Is it possible to have an adaptive width depending of the length of the text in the tab?

This is a good point. If you can't do it, then it won't be that useful

**Comment by arfianadam** [comment]
setting width in `tabStyle` doesn't make it contain the label and making it adaptive in width. any work on this?
