### ISSUE TITLE
Can't set default route to a nested StacksInTab

### ISSUE THREAD

**Issue by meno1** [react-community/react-navigation#392]
I get an error when trying the following:

```
const AppNavigator = StackNavigator(
  {
    Login: { screen: LoginScreen },
    Profile: { screen: ProfileScreen },
    Rest: {
      name: 'Rest',
      description: 'Rest of it',
      screen: StacksInTabs
    }
  }
)

const initialNavState = {
  index: 0,
  routes: [
    { key: 'Rest', routeName: 'Rest' }
  ]
};
```

Upon further inspection, `TabRouter.getStateForAction` requires NavigationState as the second parameter, but `StackRouter` is passing in the `currentRoute`:

```
const route = childRouter.getStateForAction(action, currentRoute);
```

<img width="372" alt="bad" src="https://cloud.githubusercontent.com/assets/18617874/23105682/c95d4c84-f6b0-11e6-81ea-8a40e4a7f57d.png">

**Comment by meno1** [comment]
I tried passing in state instead of currentRoute, but then I get "There is no route defined for key undefined."

**Comment by jlongster** [comment]
I'm hitting this as well. In fact I can't seem to get nested routes working. I have something like this:

```js
// My own custom navigator with a static route:
  static router = StackRouter({
    stackScreens: { screen: StackScreens }
  }, {
    initialRouteName: 'stackScreens'
  });

// And the nested router
const stackNav = StackNavigator(
  {
    screen1: { screen: StackScreen1 },
    screen2: { screen: StackScreen2 },
    screen3: { screen: StackScreen3 }
  },
  {
    initialRouteName: 'screen1'
  }
);
```

I keep getting "There is no route defined for key stackScreens. Must be one of: 'screen1','screen2','screen3'". It's like the route name for the child route is wrong.

**Comment by meno1** [comment]
@jlongster are you still using this?  I'm just curious if you're using anything else instead.

**Comment by spencercarli** [comment]
Hi! Since this issue has been quiet for a while I'm going to go ahead and close it. If the issue persists in the latest version of React Navigation please re-open!
