### ISSUE TITLE
Can't run Redux example on Android

### ISSUE THREAD

**Issue by matthamil** [react-community/react-navigation#393]
## Problem

I can't run the redux example on an Android emulator. I get a bundle error in my emulator after I run `react-native run-android`.

## Expected Behavior

Be able to run the redux example without any problems

## Steps to Reproduce

I did a clean `git clone` of the repo, and ran `yarn` in the root of the react-navigation directory. I navigated to the ReduxExample folder and tried to run `yarn`, and got the following error:

![image](https://cloud.githubusercontent.com/assets/11802078/23106176/1e8818f8-f6af-11e6-87f4-e330e1edc68a.png)

Instead, I did an `npm install` (which oddly enough worked when yarn didn't work).

When I tried to run `react-native run-android` with my Android emulator open, I got the following error in the console:

```
React packager ready.

jest-haste-map: @providesModule naming collision:
  Duplicate module name: react-native-vector-icons
  Paths: /Users/matthamil/workspace/react-navigation/node_modules/react-native/local-cli/core/__fixtures__/files/package.json collides with /Users/matthamil/workspace/react-navigation/examples/ReduxExample/node_modules/react-native/local-cli/core/__fixtures__/files/package.json

This warning is caused by a @providesModule declaration with the same name across two different files.
jest-haste-map: @providesModule naming collision:
  Duplicate module name: core-js
  Paths: /Users/matthamil/workspace/react-navigation/examples/ReduxExample/node_modules/react-native/node_modules/core-js/package.json collides with /Users/matthamil/workspace/react-navigation/node_modules/react-native/node_modules/core-js/package.json

This warning is caused by a @providesModule declaration with the same name across two different files.
jest-haste-map: @providesModule naming collision:
  Duplicate module name: react-native
  Paths: /Users/matthamil/workspace/react-navigation/node_modules/react-native/package.json collides with /Users/matthamil/workspace/react-navigation/examples/ReduxExample/node_modules/react-native/package.json

This warning is caused by a @providesModule declaration with the same name across two different files.
[02/19/2017, 14:08:08] <START> Building Haste Map
Failed to build DependencyGraph: @providesModule naming collision:
  Duplicate module name: react-native-vector-icons
  Paths: /Users/matthamil/workspace/react-navigation/node_modules/react-native/local-cli/core/__fixtures__/files/package.json collides with /Users/matthamil/workspace/react-navigation/examples/ReduxExample/node_modules/react-native/local-cli/core/__fixtures__/files/package.json

This error is caused by a @providesModule declaration with the same name across two different files.
Error: @providesModule naming collision:
  Duplicate module name: react-native-vector-icons
  Paths: /Users/matthamil/workspace/react-navigation/node_modules/react-native/local-cli/core/__fixtures__/files/package.json collides with /Users/matthamil/workspace/react-navigation/examples/ReduxExample/node_modules/react-native/local-cli/core/__fixtures__/files/package.json

This error is caused by a @providesModule declaration with the same name across two different files.
    at HasteMap._updateHasteMap (/Users/matthamil/workspace/react-navigation/examples/ReduxExample/node_modules/react-native/packager/react-packager/src/node-haste/DependencyGraph/HasteMap.js:158:13)
    at p.getName.then.name (/Users/matthamil/workspace/react-navigation/examples/ReduxExample/node_modules/react-native/packager/react-packager/src/node-haste/DependencyGraph/HasteMap.js:133:31)
~
Process terminated. Press <enter> to close the window
```

The error in my Android emulator:

![image](https://cloud.githubusercontent.com/assets/11802078/23106182/6bb7c2cc-f6af-11e6-8a25-5dc5fc63efa0.png)

**Comment by ericvicenti** [comment]
The examples have a sorta strange setup: you need to run the packager from the `react-navigation` root, with `npm run start`. This error you are seeing is what happens if you run the packager from inside the example, which wont work.

[This document](https://reactnavigation.org/docs/guides/contributors) is supposed to explain that, please send in a revision if it seems unclear: Also, maybe there can be a better error or a better way to help people avoid this problem. If you have any ideas, help would be appreciated!

**Comment by oguennec** [comment]
`react-native start` instead of `npm start` might be a workaround for the time being to run the **ReduxExample** for those facing  above issue (jest-haste-map: @providesModule naming collision).

See [issues/1325](https://github.com/react-community/react-navigation/issues/1325) and [create-react-native-app/issues/193](https://github.com/react-community/create-react-native-app/issues/193)
