### ISSUE TITLE
Required to install react-native-vector-icons in 2.0-rc.1

### ISSUE THREAD

**Issue by DimitryDushkin** [react-community/react-navigation#3934]
### Current Behavior
Hey! Thank you for great work!
I'm switching to 2.0 in app using TabNavigator. My app is iOS-only so it's kind of surprise to see **react-native-paper** installed and **react-native-vector-icons** in peer deps.

Code is simply:
```js
import {createBottomTabNavigator} from 'react-navigation';
const Navigator = createBottomTabNavigator({ ... });
export default Navigator;
```

### Expected Behavior
I'm expecting do not have **react-native-paper** and **react-native-vector-icons** in dependencies for ios-only apps.

### How to reproduce

`npm i react-native-navigation@2.0.0-rc.1`
And use `createBottomTabNavigator` somewhere. Compilation fails with:
```
error: bundling failed: Error: Unable to resolve module `react-native-vector-icons/MaterialIcons` from `.../iosapp/node_modules/react-native-paper/src/components/Icon.js`: Module `react-native-vector-icons/MaterialIcons` does not exist in the Haste module map
```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.0.0-rc.1
| react-native     | 0.55.1
| node             | 9.10
| npm or yarn      | 5.6.0

**Comment by dushaobindoudou** [comment]
do not want to depend on react-native-paper ，hope i can install the specified navigation type

**Comment by MrLoh** [comment]
React native paper just fixed this, that should alleviate the problem. But React navigation will probably have to update it's dependency. 
https://github.com/callstack/react-native-paper/issues/303#event-1581034776

**Comment by rhazegh** [comment]
This issue is still present in Release `2.0.0-rc.3`
