### ISSUE TITLE
How to change drawer item's fontFamily and fontSize

### ISSUE THREAD

**Issue by Noor0** [react-community/react-navigation#398]
i think there's currently no way to do that, please consider adding this feature.

**Comment by ericvicenti** [comment]
You can always render you own drawer content.

See `contentComponent` in this doc: https://reactnavigation.org/docs/navigators/drawer

**Comment by carlos-cbqa** [comment]
If there are a doubt with this, @ericvicenti the new url is [https://reactnavigation.org/docs/en/drawer-navigator.html#contentoptions-for-draweritems](https://reactnavigation.org/docs/en/drawer-navigator.html#contentoptions-for-draweritems) and to add it to your project you only need to add the property 

`{
    initialRouteName: 'YourInitialScreen',
    contentComponent: DrawerContentComponent,
    drawerOpentRouter: 'DrawerOpen',
    drawerCloseRoute: 'DrawerClose',
    drawerToggleRoute: 'DrawerToggle',

//this is the property you are looking for
    contentOptions: {
        labelStyle: styles.contentOptions
    },`

**Comment by AwaMelvine** [comment]
@carlos-cbqa I followed the documentation but I was only able to change the font color and size. The fontFamily property doesn't seem to be working.

**Comment by callmeaponte** [comment]
Can we reopen this as a feature request? I understand we can opt to render custom drawer content, but that option is a bit cumbersome if we're simply trying to set a different font family.

**Comment by oscarafuentes** [comment]
@AwaMelvine @callmeaponte Adding `fontWeight` of `normal` seems to fix it. Try adding `fontWeight: 'normal',` to the `labelStyle` and should work. https://stackoverflow.com/questions/48632706/labelstylefontfamilyverdana-does-not-show

**Comment by malmukhtar** [comment]
Hello,

if you are using the DrawerItemList component, it has "labelStyle" property that allows changing the style of the element.

<DrawerItemList {...props}
          labelStyle={{fontFamily: 'Cairo_Regular'}}
        />

**Comment by obayit** [comment]
Use the `drawerLabelStyle` option, [docs](https://reactnavigation.org/docs/drawer-navigator/#drawerlabelstyle).
