### ISSUE TITLE
Push some scenes from current stack?

### ISSUE THREAD

**Issue by aksonov** [react-community/react-navigation#400]
Some app UI screens, like user profile UI could be pushed anywhere in the app, by current navigation controller. How to achieve that with reactnavigation - as I see I should define all hierachy with all screens? Does it mean that I should duplicate definition of that screen and add it to all used stacks?

**Comment by ericvicenti** [comment]
You can always share routeConfigs if you want to. For example:

```js
const genericRouteConfigs = {
  Foo: {screen: Foo},
};

const Bar = StackNavigator({
  ...genericRouteConfigs,
  BarScreen: {screen: BarScreen},
});

const Baz = StackNavigator({
  ...genericRouteConfigs,
  BazScreen: {screen: BazScreen},
});

const App = TabNavigator({
  BarScreen: {screen: Bar},
  BazScreen: {screen: Baz},
});
```

With this approach, you can navigate to Foo within either the Bar or Baz navigators.
