### ISSUE TITLE
CardStack Transitioner problems

### ISSUE THREAD

**Issue by tarikmlaco** [react-community/react-navigation#401]
I have been having problems with CardStack...I just couldn't force it to accept custom transitions...in the end I ended up deeply digging into the react-navigation code and noticed that...
```
  _getTransitionConfig(
    // props for the new screen
    transitionProps: NavigationTransitionProps,
    // props for the old screen
    prevTransitionProps: NavigationTransitionProps
  ): TransitionConfig {
    const defaultConfig = TransitionConfigs.defaultTransitionConfig(
      transitionProps,
      prevTransitionProps,
      this.props.mode === 'modal'
    );
    // LOOK HERE
    if (this.props.transitionConfig) {
      return {
        ...this.props.transitionConfig,
        ...defaultConfig
      };
    }
    return defaultConfig;
  }
```
BUT...`propTypes` expects `this.props.transitionConfig` to be a function. Which makes no sense, as the `_renderScene` method takes this:
 ` const { screenInterpolator } = this._getTransitionConfig();`
Other thing...this way, even when I push it as an object down the props...
the custom `screenInterpolator` gets overridden by the default one, and it always ends up using the default interpolator.
I had to change CardStack in this way:
```
    if (this.props.transitionConfig) {
      return {
        ...defaultConfig,
        ...this.props.transitionConfig
      };
```
...to make it work, and send `transitionConfig` as an object.

Is there a solution that I am missing here, or this should be fixed inside the library?

**Comment by ericvicenti** [comment]
I think we fixed this in https://github.com/react-community/react-navigation/commit/2273ef1c1477fb2930f961683131e30af36a37d4 . It just hasn't been released yet
