### ISSUE TITLE
Screen tracking with TabNavigator?

### ISSUE THREAD

**Issue by markflorisson** [react-community/react-navigation#402]
There is a great example here for how to do screen tracking:

    https://reactnavigation.org/docs/guides/screen-tracking

But this doesn't seem to work with TabNavigator: `null is not an object (evaluating 'this.state.nav')`

**Comment by ericvicenti** [comment]
Its not clear from the information provided what the issues is

Is the problem broken documentation, or is there a bug in the code? What is the expected behavior in comparison to what is happening?

Also, you can check the history of that document, and ping the authors: https://github.com/react-community/react-navigation/commits/master/docs/guides/Screen-Tracking.md

**Comment by grabbou** [comment]
@markflorisson it is because `TabNavigator` doesn't have `nav` in its state. It's simply a different `Navigator`.

You can try that code:
```js
const screenName = (navigation) => {
  return navigation.state.routes[navigation.state.index];
};

SimpleTabs.prototype.componentDidUpdate = function(prevProps, curProps) {
  const currScreen = screenName(this.props.navigation);
  const prevScreen = screenName(prevProps.navigation);
  if (!!currScreen && currScreen != prevScreen) {
    // the line below uses the Google Analytics tracker
    // change the tracker here to use other Mobile analytics SDK.
    console.log('changed', currScreen);
  }
}
```

**Comment by grabbou** [comment]
@satya164 @ericvicenti any ideas why we've decided to use `this.state.nav` instead of `this.props.navigation.state` in the docs? The above seems to work universally for both components https://github.com/react-community/react-navigation/pull/107/files#diff-1a19ce8a5a58e51bde21c6798edcbbd3R18

**Comment by satya164** [comment]
Sent a PR removing this part. Sorry I didn't notice this in the PR, but overriding prototype is a hack we shouldn't document. https://github.com/react-community/react-navigation/pull/449/files

**Comment by satya164** [comment]
I think a the correct way is to have `onNavigationStateChange` prop on the navigator.

**Comment by grabbou** [comment]
@satya164 I think opening a new issue makes sense.
