### ISSUE TITLE
Is there a way to navigate without the navigation prop?

### ISSUE THREAD

**Issue by jeffreymendez1993** [react-community/react-navigation#406]
Currently I using a normal class not attached to a component and need to be able to called the navigation action on that class without using the navigation prop.

Below is an example of the usage I would like.

 NavigationActions.dispatch({type:'NAVIGATE', path: 'http://url/secondPath/:params'});

**Comment by jeffreymendez1993** [comment]
Nvm found out how.

**Comment by jeffreymendez1993** [comment]
Nvm found a way. Called the navigator on the top level component and used a global to now navigate. Might be more efficient to use contextTypes but not sure if it will update properly.

**Comment by uxman-sherwani** [comment]
Can you post the sample code how you achieved this? Thank you :)

**Comment by nkov** [comment]
Now you can use this: https://reactnavigation.org/docs/connecting-navigation-prop.html
