### ISSUE TITLE
Header Styles

### ISSUE THREAD

**Issue by leesolway** [react-community/react-navigation#407]
Using the following code, i have been unable to alter the style of the header bar. 

```
const Router = StackNavigator({
  Splash: { screen: Splash },
  About: { screen: About },
  Quote: { screen: Quote },
}, {
  headerMode: 'screen',
  navigationOptions: {
    header: (navigation, header) => ({
      ...header, // merge the parent header config,
      tintColor: 'orange', // add any overrides
      color: '#ff0000'
    })
  }
})
```

**Comment by satya164** [comment]
You don't merge the header config at root level. Are you merging it at the screen level? What's the options in screen level?

Also there's no `color` prop. There's `titleStyle` and `style`

**Comment by matthamil** [comment]
@leesolway , `navigationOptions` is not available as a property for the second argument to `StackNavigator`. You can `navigationOptions` one of two ways:

1. inside your route configuration (the first argument) like so:

```js
const Router = StackNavigator({
  Splash: { 
    screen: Splash,
    navigationOptions: {
    ...
    }
  },
  About: { screen: About },
  Quote: { screen: Quote },
}, { ... });
```

2. Inside the stateful component set as the `screen` for a route (e.g. `screen: MyComponent`

```js
export default class MyComponent extends React.Component {
  constructor(props) {
    super(props);
  }

  static navigationOptions = {
    header: (navigation) => ({
      tintColor: 'orange',
      style: { /* appropriate styles */ }
    })
  }

  render() {
  ...
  }

}
```

**Comment by ko** [comment]
@satya164 I'm guessing that the use of 'color' is based on [this page](https://reactnavigation.org/docs/navigators/navigation-options) with 

```
color: 'blue',
```

in the "Extending defaults" section. At least, that's why I tried using it... and how I ended up here. 

Would this be a case of the documentation not being up to date, or is there another scenario where using the 'color' prop does work out? Though there's always the possibility that I've just confused myself about this.

**Comment by matthamil** [comment]
@ko Yes, the use of `color` is not supported, and this should be opened as a new issue that the docs are incorrect. I don't know if `color` was supported in the past (still new to this library as well). I couldn't find a commit in the log that specified that `color` was the old method of doing this.

See this part of the source: https://github.com/react-community/react-navigation/blob/79f21277cbec2a684edc6f2073ff36530d093f41/src/views/HeaderTitle.js#L16

The `HeaderTitle` is looking for `tintColor` not `color`.

**Comment by grabbou** [comment]
> @leesolway , navigationOptions is not available as a property for the second argument to StackNavigator. The second argument is the StackNavigatorConfig as seen here.

`StackNavigatorConfig` has a property `navigationOptions`, the OP is right.

> I'm guessing that the use of 'color' is based on this page with

Yup, looks like an unwanted confusion in the docs, submitting PR to fix it. I used it for demo purposes, wasn't mean to be a part of public API.

==

Since the original issue is resolved, I am closing the issue.

**Comment by leesolway** [comment]
Is theres no way to set a global header style?

**Comment by matthamil** [comment]
Ah I missed the part of the docs that explains that StackNavigatorConfig's navigationOptions is for default navigationOptions for the screens. Apologies.

**Comment by grabbou** [comment]
@leesolway your snippet in first post is eight, just remove function and replace it with plain object. Should be:
```
header: {
   tintColor: 'red', 
} 
```

**Comment by eslambasher** [comment]
static navigationOptions = {
    title: 'Example',
    headerRight: <Button title="Info" />,
    headerTintColor: 'lightgrey',
    headerStyle: { backgroundColor: 'deepskyblue', borderWidth: 1, borderBottomColor: 'white' },
  }

**Comment by ThaJay** [comment]
How do we get headerStyle to be evaluated again?
For instance if we want to change theme (headerStyle on all screens)
Right now it looks like we have to implement the header function on each page to respond to this.

**Comment by dougbacelar** [comment]
@ThaJay did you find an answer to your question?

**Comment by dougbacelar** [comment]
@ThaJay https://reactnavigation.org/docs/headers.html#sharing-common-navigationoptions-across-screens
