### ISSUE TITLE
Question about rendering headers and TabNavigation

### ISSUE THREAD

**Issue by mypark** [react-community/react-navigation#408]
This is a question and not a bug - I can't get headers and title to show on a screen if it's in a TabNavigation.  However I can see the title if it's in a StackNavigation.  Is that by design?  

If that's the case, if I want to see headers, should I nest each tab item in a stack navigation, or should I wrap/nest the tab navigation in one big stacknavigation?

**Comment by satya164** [comment]
Can you post the code please?

**Comment by mypark** [comment]
```
// tabs navigation doesn't show a header title in each screen

    const TabsNavigator = TabNavigator({
      Home: {
        screen:HomeScreen,
      },
      Profile: {
        screen: ProfileScreen,
      },
    }, {
      tabBarOptions: {
        activeTintColor: '#e91e63',
      },
      navigationOptions: {
        header: {
          visible: true,
        },
      },
    });

Header shows when I wrap it in a StackNavigator

    default StackNavigator({
      Home: { screen: TabsNavigator },
    });

Or is it better to do it this way

     export TabsNavigator = TabNavigator({
          Home: {
            screen:StackNavigator({
              Home: { screen: TabsNavigator },
            }),
          },
          Profile: {
            screen: ProfileScreen,
          },
        }, {
          tabBarOptions: {
            activeTintColor: '#e91e63',
          },
          navigationOptions: {
            header: {
              visible: true,
            },
          },
        });
```

**Comment by mypark** [comment]
Oh interesting, if I set the navigationOptions when I'm declaring the TabNavigator - it works  .e.g. 
```
TabNavigator({
  Discover: {
    screen: DiscoverScreen,
    navigationOptions: {
      title: () => 'Discover Screen',
    },
  },
```
however setting the static navigationOptions on the component itself doesn't work unless its in a StackNavigator

**Comment by matthamil** [comment]
@mypark You are attempting to configure the `navigationOptions` in the `TabNavigatorConfig` which is not the proper place for `navigationOptions` (details on [TabNavigatorConfig](https://reactnavigation.org/docs/navigators/tab). I answered a similar question [here](https://github.com/react-community/react-navigation/issues/407#issuecomment-281239081). Check the code samples I posted and see if this resolves your issue.

**Comment by mypark** [comment]
@matthamil actually the opposite is true - it works if I configure it at the  TabNavigator.  However if I try to set it with the static property in the screen itself - it does not work with tabs.

**Comment by allpwrfulroot** [comment]
Same issue, would love to have a header that offers a "bring up filters" button when one of my tabs is chosen.

**Comment by mypark** [comment]
Another thing that's a bit confusing is the difference between route name and key and duplicate route names.  It seems like the route name doesn't have to be unique as shown in my example since both the outer tab and the inner stack have the same route name.  When you use the navigate functions - you pass the route name, correct?  If so how does it differentiate between the duplicate route names in nested navigators and when would you use the key instead?

**Comment by grabbou** [comment]
> If that's the case, if I want to see headers, should I nest each tab item in a stack navigation, or should I wrap/nest the tab navigation in one big stacknavigation?

Both work, depends on what you want to achieve. If you have a Facebook-like layout, probably former. If you want to show a tabbed screen, the latter.

See `StacksInTabs` in playground for a potential solution.

**Comment by KabirKang** [comment]
@grabbou so can you put configured headers on each tab of a tab navigator? It's not showing for me.

**Comment by CapitanRedBeard** [comment]
@grabbou 
Yeah there is a lack of clarity about that. But refer to @grabbou 's comment for a solution
