### ISSUE TITLE
Changing title of the navigation bar

### ISSUE THREAD

**Issue by ulhas** [react-community/react-navigation#413]
Hi,

I have been trying to change the title of the navigation bar based on the locality of the user, determined by geocoding the location. How do I update the title once i get the geocoded location?

`onGeocodeLocation = locality => {
console.log(locality);
RestaurantScreen.navigationOptions.title = locality;
}`

This changes the title but only if i move to different screen, does it refresh.

Thanks,
Ulhas

**Comment by grabbou** [comment]
Check `dynamic configuration` section on [this page](https://reactnavigation.org/docs/navigators/navigation-options). Once your `title` depends on a route params, check `setParams` section [here](https://reactnavigation.org/docs/navigators/navigation-prop).

**Comment by ulhas** [comment]
@grabbou Sorry, I saw this a little late. So, I have a geolocation service, which when changed dispatches an action to change the state via redux. Now this happens asynchronously and can take a few seconds. How do i change the title of the navigation bar few seconds after it has loaded?

**Comment by RichardLindhout** [comment]
@ulhas You probably need something like this!
https://github.com/satya164/react-navigation-addons

**Comment by blackxored** [comment]
I've seen this issue popping all over the place, are there any plans on this at all?

**Comment by msert29** [comment]
I know this is a little late but you can pass the initial title as from navigation i.e. `this.props.navigate('Map', {'geolocation: '-000000,-0000000'})` and then within the Map component have your header component like `static navigationOptions = ({navigation}) => ({
      header: <Header pageTitle={navigation.state.params.geolocation}/>
    });` Finally within the same component, if you decode the geolocation, simply callling `this.props.navigation.setParams({geolocation: newLocation})` will update your header.
