### ISSUE TITLE
Absolute 'screen' header is rendered behind the scene (experimentations with transparent header)

### ISSUE THREAD

**Issue by bd-arc** [react-community/react-navigation#414]
Hi,

I've been experimenting with miscellaneous ways to alternate between plain and transparent headers in my React Native app. This is what I've been trying to achieve:

![sweet dream](https://media.giphy.com/media/xTiN0sNopLKCavM9G0/giphy.gif)

My conclusions so far are the following:
- currently, there seems to be no way of doing it while setting `headerMode` to `screen`
- header must be absolutely positioned.

Below are the different configurations I've tried and their respective results.

### Configuration 1 : Floating header

![config 1](https://media.giphy.com/media/l44Qn9C8mAHPdRfhu/giphy.gif)

```
headerMode: 'float',
navigationOptions: {
    header: {
        style: { backgroundColor: 'transparent' }
    }
}
```

This is not working. You can see the background view and there is no difference between plain and transparent headers.

### Configuration 2 : Screen header

![config 2](https://media.giphy.com/media/xTiN0i4lVJbjUhn8u4/giphy.gif)

```
headerMode: 'screen',
navigationOptions: {
    header: {
        style: { backgroundColor: 'transparent' }
    }
}
```

This is not working either. Since the header is not rendered on top of the scene, there is no real header transparency.

### Configuration 3 : Floating header + absolute positioning + spacer

![config 3](https://media.giphy.com/media/l44QfAwCzYpOBPOXS/giphy.gif)

```
headerMode: 'float',
navigationOptions: {
    header: {
        style: {
            backgroundColor: 'transparent',
            position: 'absolute',
            top: 0,
            left: 0,
            right: 0
        }
    }
}
```
**This is the closest to what I've been trying to achieve**. The header is absolutely positioned and the first scene contains a "header spacer" - a simple `View` with a white background and a height equals to header's one. Its purpose is to simulate a plain header whenever needed.

### Configuration 4 : Screen header + absolute positioning + spacer

![config 4](https://media.giphy.com/media/l44Qspz4WBLhp5soU/giphy.gif)

```
headerMode: 'screen',
navigationOptions: {
    header: {
        style: {
            backgroundColor: 'transparent',
            position: 'absolute',
            top: 0,
            left: 0,
            right: 0
        }
    }
}
```

This is the configuration I'd like to use. Unfortunately, it comes with one major issue: **the header is rendered behind the scene**, which makes it invisible and unable to receive click events (I've made the spacer slightly transparent so that you can see the header in the first scene).

By digging in the source code, I've found out that [only the floating header is rendered on top of the scene](https://github.com/react-community/react-navigation/blob/master/src/views/CardStack.js#L233:L248), not the 'screen' one.

Is this by design? Is there any way to make this configuration work?

Thanks for any insight you can provide.

**Comment by satya164** [comment]
> the header is rendered behind the scene

hmm this looks like a bug

cc @grabbou

**Comment by javiercr** [comment]
@bd-arc with your solution #4 I was able to make it work just by adding `zIndex: 2` to the `style` for the header :)

**Comment by grabbou** [comment]
Yeah, I've hit that bug earlier today. Releasing a fix tomorrow morning as it's a blocker for my app. Thanks for posting examples!

**Comment by bd-arc** [comment]
@javiercr Thanks for looking into it :) But I forgot to mention that I had already tried that, and while this hack works on iOS, it unfortunately doesn't on Android.

@grabbou That's good to hear! Looking forward to your fix :)
