### ISSUE TITLE
Unnecessary whitespace added to the left of the screen title

### ISSUE THREAD

**Issue by ayalpani** [react-community/react-navigation#415]
Hi,

for whatever reason, there is always a white space (I painted it yellow to illustrate the problem) left to my screen title:

![whitespace](https://cloud.githubusercontent.com/assets/603179/23165595/405ca07c-f83d-11e6-9964-ff61b142ae22.png)

Obiously it reserves space so a left arrow fits there. But as long as my screen is the first on the stack, how can I make the blank area disappear?

Thanks!

```
export default class NotificationsScreen extends React.Component {
  
  static navigationOptions = {
    title: 'Notifications'
  }

  render() {
    return (
      <View></View>
    );
  }
}

```

**Comment by satya164** [comment]
cc @grabbou

**Comment by grabbou** [comment]
I cannot reproduce that issue. Run latest master, still, as tested:
<img width="468" alt="screen shot 2017-02-21 at 22 57 03" src="https://cloud.githubusercontent.com/assets/2464966/23186912/1a600e3a-f889-11e6-9c22-b73bfb8264ea.png">
<img width="469" alt="screen shot 2017-02-21 at 22 57 00" src="https://cloud.githubusercontent.com/assets/2464966/23186914/1a6d13dc-f889-11e6-9385-d0d58ac1fb8d.png">

What is the exact hierarchy you got? Does arrow appears in other places?

**Comment by ayalpani** [comment]
To make sure nothing interferes, I did this:

1. react-native init test
2. cd test
3. yarn react-navigation
4. vim index.android.js => 

```
import React from 'react';
import {
  AppRegistry,
  Text,
} from 'react-native';
import { StackNavigator } from 'react-navigation';

class HomeScreen extends React.Component {
  static navigationOptions = {
    title: 'Welcome',
  };
  render() {
    return <Text>Hello, Navigation!</Text>;
  }
}

const SimpleApp = StackNavigator({
  Home: { screen: HomeScreen },
});

AppRegistry.registerComponent('rntest', () => SimpleApp);

```

5. react-native run-andoid

And this is the result:

![whitespace2](https://cloud.githubusercontent.com/assets/603179/23202838/3a71cf72-f8e0-11e6-818c-eff4e448d205.png)

I'll try it with another Android and let you know if something differs then.

**Comment by satya164** [comment]
Try running `yarn clean cache` and repeat the process

**Comment by ayalpani** [comment]
Well, I tried using latest master:

`npm install --save git+https://github.com/react-community/react-navigation/`

Et Voilà, it works as expected. Thanks for your support!
