### ISSUE TITLE
Custom Icon for DrawerNavigator

### ISSUE THREAD

**Issue by Fenwil** [react-community/react-navigation#416]
Hi! I'm trying to use a Custom Component (called DrawerIcon) on the icon parameter inside my navigationOptions on each of my Drawer Items and I get this on the first render:

<img width="491" alt="screen shot 2017-02-21 at 10 40 09 am" src="https://cloud.githubusercontent.com/assets/2475912/23167195/2bcceb64-f822-11e6-8eea-2cc02e4c75d4.png">

Then clicking on any of the Items I get:

<img width="490" alt="screen shot 2017-02-21 at 10 40 41 am" src="https://cloud.githubusercontent.com/assets/2475912/23167215/3e5a9c04-f822-11e6-9d3d-038b45df7caf.png">

This is my Home Component:
```javascript
export default class Home extends Component {
  static navigationOptions = {
    drawer: () => ({
      label: 'Home',
      icon: () => <DrawerIcon iconName="md-home" iconSize={25} iconColor="#FFF" />
    })
  };
  render() {
    const { navigate } = this.props.navigation;
    return (
      <View style={styles.container}>
        <MainHeader navigate={navigate} />
        <View style={styles.wrapper}>
          <Image style={styles.backgroundHeader} source={require('../assets/tabBackground.png')} />
          <MainTab />
        </View>
      </View>
    );
  }
}
```

This is my DrawerIcon:
```javascript
import React from 'react';
import { View, StyleSheet, Image } from 'react-native';
import Icon from 'react-native-vector-icons/Ionicons';

const DrawerIcon = ({ iconName, iconSize, iconColor, polygonWidth, polygonHeight }) => (
  <Image source={require('../assets/polygon.png')} style={styles.iconWrapper}>
    <Icon name={iconName} size={iconSize} color={iconColor} style={styles.icon} />
  </Image>
);

const styles = StyleSheet.create({
  iconWrapper: {
    width: 77.4,
    height: 44
  },
  icon: {
    position: 'absolute',
    top: 8,
    left: 28
  }
});

export default DrawerIcon;
```

Seeing the Drawer source code:
[DrawerNavigatorItems.js](https://github.com/react-community/react-navigation/blob/master/src/views/Drawer/DrawerNavigatorItems.js)

It seems that the Icon has this styles:
```javascript
const styles = StyleSheet.create({
  container: {
    marginVertical: 4,
  },
  item: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  icon: {
    marginHorizontal: 16,
    width: 24,
    alignItems: 'center',
  },...
```

Would be great to have a `renderCustomIcon()` or something like it without those constraints.

Thanks!

**Comment by grabbou** [comment]
As already discussed in PR, this is now possible.
