### ISSUE TITLE
DrawerNavigatior's Menu Is Not Showing

### ISSUE THREAD

**Issue by ananth10** [react-community/react-navigation#4170]
I am trying to implement DrawerNavigator in my React Native Application. I have already added some screens in StackNavigator then i have added DrawerNavigator inside StackNavigator. but Navigator menu is not showing. can anyone tell me why its not showing . thanks in advance

This is my repo link **https://github.com/ananth10/DrawerNavigatorSample**. please review my code and let me know where i  have been wrong.

**Comment by brentvatne** [comment]
can you put this example on https://snack.expo.io so it is easier to run, please? also please fill out the entire issue template in the future

**Comment by ananth10** [comment]
@brentvatne I have put all code here **https://snack.expo.io** . please check it and do the needful as soon as possible. Thank you in advance.

**Comment by brentvatne** [comment]
@ananth10 - you need to save it and send me a link to the url on snack that has the code

**Comment by ananth10** [comment]
@brentvatne  i have saved all code in expo. this is the url **https://snack.expo.io/Hk7uQLZCG**  . pleaselet me know you need anything else. Thank you!

**Comment by ananth10** [comment]
@brentvatne . Its working now. this is snack url **https://snack.expo.io/@ananth10/drawernavigator** 
you can see home screen but side menu is not showing. please check it and let me know where I have been wrong. I am just new to React Native. so please .

**Comment by ananth10** [comment]
@brentvatne I have figured it out. Thanks for you support.
