### ISSUE TITLE
Pop nested navigator

### ISSUE THREAD

**Issue by jarandmi** [react-community/react-navigation#419]
I have a nested Navigator that looks like this

```javascript
const MainNavigation = StackNavigator({
  Home: {
    screen: FrontNavigator,
  },
  ObjectNavigation: {
    screen: ObjectNavigation,
  }
}, { headerMode: "none", mode: "modal" });

const ObjectNavigation = TabNavigator({
  Objects: { screen: ObjectList },
  MyReservations: { screen: MyReservations },
  Profile: { screen: Profile }
}
});
```

I want to pop the `ObjectNavigation` from the `MyReservations` path, but i cant figure out how to do it. 

If i try to do `this.props.navigation.dispatch({ type: "Navigation/BACK" })`from the `Objects` path it works like a charm (The `ObjectNavigation` pops, and navigation goes back to `MainNavigation` Home path). 

If i do the same within `MyReservations` it just goes back to the `Objects` path in the TabNavigator.

What am i doing wrong?

**Comment by InteractiveLogic** [comment]
@jarandmi did you find a solution to this problem?

**Comment by InteractiveLogic** [comment]
OK so I basically just needed to pop the TabNavigator off the top of the StackNavigator, and the following worked for me (styles/noise removed):

```
            <TouchableHighlight
              onPress={ () => this.props.navigation.goBack(null) }
            >
              <Text>Back</Text>
            </TouchableHighlight>

```

**Comment by jarandmi** [comment]
Yepp, this work now with the latest version

**Comment by InteractiveLogic** [comment]
Acually I was mistaken... it's not working as I had hoped so I'm still stuck. I found another solution in #335, but the solution mentioned there wipes out the params I pass during the dispatch... I may have to use redux to get around that problem, however, as I'm only passing a small amount of data and it wouldn't be too complex...
