### ISSUE TITLE
state not available

### ISSUE THREAD

**Issue by schneck** [react-community/react-navigation#42]
Hi,

I have an issue trying to open a detail screen.

In my routing config, I have this:

```
const Navigator = DrawerNavigator({
    Details: {
        path: 'details/:pk',
        screen: DetailsContainer
    }
    [...]
});
```

In some Component, I navigate like this:

`navigation.navigate('Details', {pk: 1})`

In the Detail Component, I don't have `navigation.state`:

```
console.log(navigation)
=> {key: "Details", routeName: "Details"}
```
  
Any idea what I'm doing wrong?

**Comment by knowbody** [comment]
@schneck hey, something like this is very hard for us to debug. Could you create a minimal example repo where we could see this happening?

**Comment by ericvicenti** [comment]
You do have `navigation.state`, (that is the thing with `key` and `routeName`), but the params were not passed in properly. This looks like a bug in the way the TabRouters or the way they are set up inside the drawer.

Can you show us the console log output, which shows the actions and state changes? We can use that to write a test case that makes sure params get passed in deeply.

**Comment by schneck** [comment]
Sure, I'm using the following snippet, which I pass the "pk" param:

```
    componentDidMount() {
        console.log("NAV: ", this.props.navigation)
    }
```
Output is this:

<img width="531" alt="screenshot 2017-01-27 20 30 48" src="https://cloud.githubusercontent.com/assets/150785/22384695/ba37cc36-e4cf-11e6-952a-b43bf874152a.png">

Does this help or can I help in another way?

**Comment by grabbou** [comment]
I am going to close it in favor of #80 as they are about the same.
