### ISSUE TITLE
Push stack on another stack

### ISSUE THREAD

**Issue by stief510** [react-community/react-navigation#420]
Is there a way to to push a new stack onto an already existing stack navigator -- meaning have the stack as a view for a route?

I have it set up like this

```
return StackNavigator({
   Home: {screen: HomeView},
   Settings: {screen: SettingsStack}
})
```

where SettingsStack is  

```
return StackNavigator({
   MainSettings: {screen: SettingsView}
})
```

And it is telling me that it is `converting circular structure to JSON`

**Comment by PavSidhu** [comment]
You need to do the following for your settings StackNavigator:

```
const SettingsStack = StackNavigator({
    MainSettings: {screen: SettingsView}
})

export default class Settings extends Component {
  render() {
    return <SettingsStack/>
  }
}

```

and then the parent StackNavigator should be like so:

```
return StackNavigator({
   Home: {screen: HomeView},
   Settings: {screen: Settings}
})
```

**Comment by stief510** [comment]
Cool... thanks. I will give that a shot

**Comment by satya164** [comment]
Yes, you can (and should) do what you wrote above. You don't need to wrap it in a component.

**Comment by stief510** [comment]
@satya164 Without wrapping it, I am getting an error

**Comment by satya164** [comment]
what's the error?

**Comment by stief510** [comment]
As I wrote above, `converting circular structure to JSON`

**Comment by satya164** [comment]
Can you post your code and stacktrace for error? It's not possible to tell why the error is happening without a stacktrace

**Comment by stief510** [comment]
Wrapping it in a component does in fact work. However, it then renders two headers

**Comment by stief510** [comment]
@satya164  
<img width="880" alt="screen shot 2017-02-22 at 5 35 49 pm" src="https://cloud.githubusercontent.com/assets/5383963/23235967/7d9a7d54-f925-11e6-83f7-4737f3b6a75d.png">

![simulator screen shot feb 22 2017 5 35 48 pm](https://cloud.githubusercontent.com/assets/5383963/23236015/a4adc306-f925-11e6-8422-3c1924eda548.png)

**Comment by chourobin** [comment]
This is a little late but @stief510, were you passing params in your `navigate()` action?

This error may be complaining about the type of param you were passing.

**Comment by zvona** [comment]
This is very peculiar. I banged my head on the wall with this for two hours (with beta 11).

Problem seems to be at general `navigationOptions` vs screen specific `navigationOptions`. I had one screen without screen specific options and I got this error. After adding some empty options, things started to work... 😠

**Comment by AndrewIngram** [comment]
I'm seeing the same thing @zvona, going from a screen which defines headerLeft to one which doesn't (for example) is crashing my app.

**Comment by JinHoSo** [comment]
@AndrewIngram +1, 
Have you found a solution for that?

**Comment by abeddow91** [comment]
I'm also having the same issue when going from headerLeft - does anyone have any fixes for this?
