### ISSUE TITLE
Long Transition Delay only in Dev Mode

### ISSUE THREAD

**Issue by bbil** [react-community/react-navigation#4218]
### Current Behavior

- Simple stack navigator with two screens
- Navigating from one to the other can take ~2 seconds to start the animation
    - using the Android back button is instant, no noticeable delay
- Switching JS Dev Mode to off causes transition to have no delay
    - Shake Gesture -> Dev Settings -> change JS Dev Mode -> Reload

### Expected Behavior

- Transition should look and behave similar with dev mode

I have not tested on iOS, only on a real Android device.

**Comment by mydesweb** [comment]
I notice this also on iOS

**Comment by cbjs** [comment]
same

**Comment by brentvatne** [comment]
I don't know how to reproduce this. It works fine for me. Please provide a runnable example project that has this problem. Also provide a video showing what you are experiencing
