### ISSUE TITLE
RN Web - StackNavigator is not a function

### ISSUE THREAD

**Issue by reggi** [react-community/react-navigation#423]
I'm trying to get this running on react native web.

```
Uncaught TypeError: (0 , _reactNavigation.StackNavigator) is not a function
    at Object.defineProperty.value (bundle.js:78675)
    at __webpack_require__ (bundle.js:660)
    at fn (bundle.js:84)
    at Object.defineProperty.value (bundle.js:78642)
    at __webpack_require__ (bundle.js:660)
    at fn (bundle.js:84)
    at Object.defineProperty.value (bundle.js:78489)
    at __webpack_require__ (bundle.js:660)
    at fn (bundle.js:84)
    at Object.defineProperty.value (bundle.js:78556)
    at __webpack_require__ (bundle.js:660)
    at fn (bundle.js:84)
    at Object.<anonymous> (bundle.js:36601)
    at __webpack_require__ (bundle.js:660)
    at fn (bundle.js:84)
    at Object.<anonymous> (bundle.js:79861)
    at __webpack_require__ (bundle.js:660)
    at bundle.js:709
    at bundle.js:712
```

Also what's weird, when I just run the following with `babel-node`

```js
import RN from 'react-navigation'
console.log(RN.StackNavigator)
```

I get this error:

```
/Users/thomasreggi/Desktop/web/ap/node_modules/react-navigation/src/navigators/StackNavigator.js:3
import React from 'react';
^^^^^^
SyntaxError: Unexpected token import
```

When I check package.json `main` it uses the `src` and not the `lib` version, why is this?

https://github.com/react-community/react-navigation/blob/master/package.json#L5

**Comment by reggi** [comment]
Here's a demo repo:

https://github.com/reggi/example-web-react-navigation-issue

![screen shot 2017-02-21 at 2 22 07 pm](https://cloud.githubusercontent.com/assets/296798/23180966/2e0b0158-f841-11e6-9532-159c03254c40.png)

**Comment by temitope** [comment]
The second error may be due to `react-navigation` requiring `React` to be imported first, so the snippet by itself is kissing dependencies.

**Comment by temitope** [comment]
Disregard I see you got an error doing just that.

**Comment by reggi** [comment]
@temitope Any idea what's going on?

**Comment by reggi** [comment]
Seems like the `react-navigation.web.js` file doesn't contain `StackNavigator`.

```js
import RNW from 'react-navigation/lib/react-navigation.web.js';
console.log(RNW)
```

```js
{ createNavigationContainer: [Getter],
  StateUtils: [Getter],
  addNavigationHelpers: [Getter],
  NavigationActions: [Getter],
  createNavigator: [Getter],
  StackRouter: [Getter],
  TabRouter: [Getter],
  withNavigation: [Getter] }
```

**Comment by temitope** [comment]
@reggi Ahh I am just realizing now that it is a totally different core library (in a way)...yeah if anything would be different between native and web I would assume the navigation would be as it is so different in terms of touch/click/back<->forward buttons, but I must say i dont know as I am unfamiliar with the RN4WEB .... seems like is is still in nascent stages and not yet up to support for full react-navigation features (i.e. DrawerNavigator and StackNavigator)....i probably wouldnt mix the two libraries as of yet, but I am relatively new to the React/ReactNative world myself.

**Comment by satya164** [comment]
Just import `'react-navigation/lib/react-navigation.js'` if you're using react native for web. `react-navigation.web.js` is for normal websites which.

**Comment by code-by** [comment]
After updating from 3 to 4, got this error in RN4W

**Comment by geminiyellow** [comment]
yep , i use rnrf 4, and got this error.

**Comment by brentvatne** [comment]
can someone who would like to see this issue resolved please create a new issue with a reproducible example on https://snack.expo.io or in a github repository, with a minimal amount of superfluous code? (please don't post your entire app, just a small one to reproduce the problem). thanks!
