### ISSUE TITLE
Launch a `Modal` scene from a stack of scenes in `Card` mode 

### ISSUE THREAD

**Issue by SandroMachado** [react-community/react-navigation#424]
Is it possible to launch a scene in `Modal` visualisation mode from a stack o scenes in `Card` visualisation mode?

For this example:
``` 
const CardStack = StackNavigator({
  Home: {
    screen: MyHomeScreen,
  },
  Profile: {
    path: 'people/:name',
    screen: MyProfileScreen,
  },
  HeaderTest: {screen: MyHeaderTestScreen},
}, {
  mode: 'card',
});
```

What I am trying to do is the following:

``` 
const ModalStack = StackNavigator({
  Home: {
    screen: MyHomeScreen,
  }, {
  mode: 'modal',
});

const CardStack = StackNavigator({
  Home: {
    screen: ModalStack,
  },
  Profile: {
    path: 'people/:name',
    screen: MyProfileScreen,
  },
  HeaderTest: {screen: MyHeaderTestScreen},
}, {
  mode: 'card',
});
```

But it is not working, the `Home` scene is displayed in `Card` display mode. Any thoughts how to fix this?

The animation desired:
![desired](https://cloud.githubusercontent.com/assets/631739/23178987/4d96e370-f864-11e6-9922-fb08e1d24093.gif)

The animation obtained:
![obtained](https://cloud.githubusercontent.com/assets/631739/23179006/5b3b3e40-f864-11e6-843d-482cbc557f5e.gif)

**Comment by miracle2k** [comment]
The way to achieve this would be to move the ModalStack to the top-level, and make the cardstack the child.

I am struggling with this, because  I am dealing with a handful of cases where I'd like to navigate card-like inside a modal, that is, the first screen opens like a modal, and subsequent screens transition horizontally. Having to create two nested navigators to achieve this is verbose.

I'm finding myself wanting to attach a "mode" setting to an individual screen.

**Comment by SandroMachado** [comment]
As a workaround I am moving all of my modal scenes to inside a `Modal` component from React Native.

**Comment by justinobney** [comment]
@SandroMachado that is precisely what I did. However, I am also using Redux. This is causing an issue because the `back` action is handled by all Navigators. So I grab the dispatch and add a key for the initiating action. Then in the reducer, I decide if I need to handle it or not.

```
<View style={StyleSheet.absoluteFill}>
  <MainStack navigation={addNavigationHelpers({
    dispatch: (action) => {
      action._navigator = 'main';
      return dispatch(action);
    },
    state: mainNav,
  })} />
  <Modal
    animationType={"slide"}
    transparent={false}
    visible={identity.loginScreenVisible}
    onRequestClose={() => this._handleBackButton()}>
   <AuthStack navigation={addNavigationHelpers({
     dispatch: (action) => {
       action._navigator = 'auth';
       return dispatch(action);
     },
     state: authNav,
   })} />
  </Modal>
</View>
```

**Comment by nihgwu** [comment]
I have a workaround for this https://github.com/react-community/react-navigation/issues/232#issuecomment-286973451

**Comment by tdurand** [comment]
I'm struggling with that also, @miracle2k your verbose solution works well if you don't have to do both transition (modal and slide) from the same screen,  I have the following screens

-Home
-List of items
--History 
--Item details 

Transitions wanted:
- Home -> List:  slide
- List of items -> History : modal
- List of items -> Item details : modal

I can't have both transition for the List of Items screen, I want to slide to Item details and to open History as a Modal...

The workaround of wrapping the History view in a React Native Modal works well on iOS, but on Android the transition is super sluggish when opening the Modal, closing it works fine.

Someone found some workaround ?

**Comment by ragnorc** [comment]
#972

**Comment by dazziola** [comment]
I would love to see the option of declaring an override for what type of mode you would want your screen to be in. Seems quite restrictive to not allow this as many apps mix and match between pushing to stack and modal views.

**Comment by evernoteHW** [comment]
@miracle2k Is a best way to solve it

**Comment by lprhodes** [comment]
@miracle2k How do you then reference the parent modal navigation stack?

**Comment by aqnaruto** [comment]
if you use android ,the card is even not work!!

**Comment by theebi** [comment]
Hello,
I have a modal working fine.  I have made the modal window transparent. But I have to reduce the opacity of background screen when modal is presented. Any workaround on this?

**Comment by danstepanov** [comment]
@miracle2k You can use this to navigate "card-style" in a modal:

```
import React, { Component } from 'react';
import { StackNavigator } from 'react-navigation';

export default function DismissableStackNavigator(routes, options) {
  const StackNav = StackNavigator(routes, options);

  return class DismissableStackNav extends Component {
    static router = StackNav.router;

    render() {
      const { state, goBack } = this.props.navigation;
      const nav = {
        ...this.props.navigation,
        dismiss: () => goBack(state.key),
      };
      return (
        <StackNav navigation={nav} />
      );
    }
  };
}
```

Then just do:

```
import { StackNavigator } from 'react-navigation';
import DismissableStackNavigator from '../DismissableStackNavigator';
import HomePage from '../HomePage';
import ScreenOne from '../ScreenOne';
import ScreenTwo from '../ScreenTwo';

const DismissableStack = DismissableStackNavigator({
  FirstScreen: {
    screen: ScreenOne,
    path: '/',
  },
  ScreenTwo: {
    screen: ScreenTwo,
    path: '/screentwo/',
  },
}, {
  headerMode: 'none',
});

export default StackNavigator({
  Home: {
    screen: HomePage,
    path: '/',
  },
  Modal: {
    DismissableStack: DismissableStack,
    path: '/',
  },
});
```

**Comment by pulkitsharma99** [comment]
@miracle2k Can you share with me an example for the approach you mentioned ?

**Comment by kelset** [comment]
Pinging OP @SandroMachado since this issue is quite old and related to an old version of the lib. If no answer I'll close in 7 days.

**Comment by kelset** [comment]
Hi there @SandroMachado ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue (especially if it's a bug report) please open a new issue that uses the new Issue Template to provide some more details to help us solve it.

**Comment by SandroMachado** [comment]
This still happening!

@kelset can you please reopen the issue?

**Comment by brentvatne** [comment]
please create a new issue and post an example on https://snack.expo.io or in a github repo, without any superfluous code :) thanks
