### ISSUE TITLE
NavigationExperimental on React Native Web

### ISSUE THREAD

**Issue by reggi** [react-community/react-navigation#426]
I'm trying to pickup this issue from React Native Web

https://github.com/necolas/react-native-web/issues/135

I have a `react-native` project and I'm trying to get it working with `react-native-web`.

I know very little about the differences here, but can there be a centralized core for navigation between the two?

Does this package provide a shim for NavigationExperimental on web?

**Comment by miracle2k** [comment]
`NavigationExperimental` experimental works with react-native-web. The issues with the png assets not being found you'd have to fix yourself, that seems to be an issue with how that particular package has been created.

This project takes some of the ideas of `NavigationExperimental`, but is a new approach. It is supposed to replace `NavigationExperimental`. I haven't tried it with react-native-web yet.

**Comment by reggi** [comment]
`NavigationExperimental` works with `react-native-web`? Where am I supposed to get that dependency? It's not included with `react-native-web`.

**Comment by miracle2k** [comment]
https://www.npmjs.com/package/react-native-experimental-navigation Judging from your post on react-native-web, you already tried it. It works, with your own adjustments, such as accounting for the missing pngs.

**Comment by satya164** [comment]
This library is `react-navigation`, not `NavigationExperimental`. It builds on `NavigationExperimental`, but it's not the same thing. https://github.com/react-community/react-navigation/issues/423#issuecomment-281851896 on your other issue should be enough to get it working in react native for web.
