### ISSUE TITLE
Current index or previous routes in StackNavigator not available

### ISSUE THREAD

**Issue by stief510** [react-community/react-navigation#427]
The StackNavigator should have access to the previous routes however when I console log out the navigation state there is no array of routes

**Comment by stief510** [comment]
Updated question: Is there a way to access the component's router when within a StackNavigator view?

**Comment by zevmo** [comment]
I am having a similar problem. Any solution?

**Comment by aliyoge** [comment]
I have the same problem.

**Comment by spencercarli** [comment]
Hi! Since this issue has been quiet for a while I'm going to go ahead and close it. If the issue persists in the latest version of React Navigation please re-open!

**Comment by Lilmortal** [comment]
This issue still persist, I will like to know the previous stack so if I know the previous stack is the login page it will display a modal saying do you want to logout.

**Comment by provider-vtnetzwelt** [comment]
I am also getting this issue. I need to know what was my previous route. Any update on it ?

**Comment by duyank** [comment]
+1 same problem

**Comment by ThalesCrisostomo** [comment]
+1 mesmo problema
