### ISSUE TITLE
Question: How do you style the back button?

### ISSUE THREAD

**Issue by leesolway** [react-community/react-navigation#429]
How do you style the back component? I can't find a reference in the docs.

**Comment by grabbou** [comment]
What would you want to style? There's a `tintColor` you can pass to change the color of the icon. The default `backButton` implementation we ship tries to be as native as possible. And so, it's not so configurable. But nothing stops you from using your custom component, by setting `left`.

**Comment by leesolway** [comment]
@grabbou That is the part i have been misunderstand then. tintColor is actually the icon and the style prop is the entire bar. 

Can you set the tintColor and style as a default, instead of redefining for each Screen via NavigationOptions?

**Comment by zachrnolan** [comment]
@leesolway You can set the default for the entire StackNavigator by setting navigationOptions in the StackNavigator config like so:

```
const navigationConfig = {
  initialRouteName: 'Places',
  headerMode: 'float',
  navigationOptions: {
    title: 'App Name',
    header: ({ state, setParams }) => ({
      style: { backgroundColor: 'green' }
    })
  }
}
```

Just pass that config into the StackNavigator:

```
const Navigation = StackNavigator({
  Setup: { screen: SetupViewContainer },
  Places: { screen: PlacesViewContainer },
  PlaceDetail: { screen: PlaceDetailViewContainer }
}, navigationConfig)
```

**Comment by gregblass** [comment]
@grabbou It doesn't look like there are any docs posted about this yet, so I don't understand your response to the question here? (If there are docs, my bad...where are they?)

I did some basic styling to the navigation header (a blue background and white text) - So I'd want the back button arrow and text to be white text as well. Also interested in removing the word 'back'.

Any way to set the arrow color to white and remove the word back from the arrow?

**Comment by tudoanh** [comment]
Can I change Back Button Icon with other icon? I'm using [React Native Vector Icon](https://github.com/oblador/react-native-vector-icons)

**Comment by james2406** [comment]
I used the tintColor, but kept the navigation the default color by doing:
`{ titleStyle: { color: null }, tintColor: colors.primary }`

**Comment by BigPun86** [comment]
just return headerTintColor in navigation options does it for me ;)


    navigationOptions: ({ navigation }) => ({
        title: `${navigation.state.routeName}`,
        headerTintColor: 'white',
        headerStyle: { backgroundColor: 'black', borderWidth: 1, borderBottomColor: 'white' },
        headerTitleStyle: { color: 'white' }
    }),

**Comment by neo125874** [comment]
@BigPun86 excuse me, could i ask about you put the code in the page, and that page get works about the effect?

**Comment by tudoanh** [comment]
Thanks a lot, but I found out that ``header`` take goBack as argument, in the [docs](https://reactnavigation.org/docs/navigators/navigation-prop)

**Comment by BigPun86** [comment]
@neo125874  Sorry my friend but i can not follow your question :) My english ist not the best u know ;)

**Comment by Tiendq** [comment]
Is there a solution to this issue, while I see it's closed!

`headerTintColor` doesn't change color of back button.

`headerBackTitleStyle` doesn't change color of back button too, I tried it on both current and previous screens' `navigationOptions`.

**Comment by nonameolsson** [comment]
Yeah, I'm still looking for an answer for this. As I see it, there is no way to change the color of the back button without rendering a custom component.

This should be implemented, as it's possible to change everything else.

**Comment by jedau** [comment]
@nonameolsson hey, man. I was just trying it out and `headerTintColor` solved it for me. You would need to put the hex color or rgba directly there instead of a style variable or whatever. Though the navigationOption is for per component, I don't know if there's an easier way to set this in the routes.

**Comment by KirillGudkov** [comment]
if You want to change color of back button on the next screen, you have to do something like this:
```
screen1: {
 screen: screen1,
 navigationOptions: {
      headerBackTitle: null, //here I mean that the title will not be shown on the NEXT(!) screen
      title: 'blah blah',
   }
},
screen2: {
 screen: screen2,
 navigationOptions: {
      headerTintColor: 'red', //here I mean that the tintColor will be have that value on the CURRENT(!) screen
      title: 'blah blah'
      }
}
```
it works for me, when I turn from screen1 to screen2, there's no backTitle on screen2 and backButton is red
![2017-11-23 0 20 06](https://user-images.githubusercontent.com/17552441/33150362-254e78a8-cfe4-11e7-90c9-e60d0e6f0f13.png)

**Comment by alexbird** [comment]
These style options don't all seem to do anything, at least on iOS.

What I desire is to keep black title text, and change the colour of the back chevron and back text to match our branding. By default the title is black and the others are blue, so clearly this is possible. 

However, the only options seem to be:
1. change everything to one colour, using `headerTintColor`
2. change the back text, but not the chevron, using `headerBackTitleStyle->color`

Am I missing something?

**Comment by vdanylov** [comment]
@KirillGudkov but how to set margins to leftHeader? Is there any leftHeaderStyle?

**Comment by tafint** [comment]
@KirillGudkov thanks for share

**Comment by UmarAdkham** [comment]
@BigPun86 's way solved my issue.

**Comment by daveteu** [comment]
It should be **pretty obvious**, but I struggled for a while thinking headerTintColor doesn't work. Remember it's an option and not a style.

So you write it as...

`headerTintColor: 'white'`

NOT

```
headerTintColor: {
    color: 'white'
}
```

**Comment by redbar0n** [comment]
Following up on @daveteu's clarification, I'd add that this didn't strike me as obvious, but is actually how it works when using a HeaderBackButton component:

DO:
```
navigationOptions {
  headerLeft: <HeaderBackButton tintColor={'white'} onPress={...} />,
}
```
DON'T:
```
navigationOptions {
  headerLeft: <HeaderBackButton tintColor={{ color: 'white' }} onPress={...} />,
}
```

**Comment by PurnimaNaik** [comment]
How to add space between the left screen boundary and the left header button in Android?? Adding margin left in the headerStyle pushes the content to right but adding padding does nothing. I want padding between the button and screen boundary. 
    
```
headerStyle: {
      marginHorizontal:0,
      borderBottomWidth: 0.2,
      elevation:0,
      marginLeft:20 -->works
      paddingLeft:50 --> does nothing 
}
```

**Comment by liplylie** [comment]
For <HeaderBackButton>, you can look at the source code to see how to override styles and props: https://github.com/react-navigation/react-navigation/blob/master/packages/stack/src/views/Header/HeaderBackButton.tsx

**Comment by ansavchenco** [comment]
My case was similar to this [one](https://github.com/react-navigation/react-navigation/issues/429#issuecomment-349634521). I made it work by using [theme](https://reactnavigation.org/docs/themes/#properties) instead like so:

```typescript
const MyTheme: Theme = {
  ...DefaultTheme,
  colors: {
    ...DefaultTheme.colors,
    primary: SkColor.accent,
  }
}

```
