### ISSUE TITLE
Question: how to control the left button?

### ISSUE THREAD

**Issue by jkomyno** [react-community/react-navigation#430]
[Vaguely related to [429](https://github.com/react-community/react-navigation/issues/429)]. I can't seem to find anything related in the official documentation.

For example, sometimes react-navigation adds a back button on the toolbar. What if I didn't want it to appear? What if I wanted an X (sort of a close icon) to appear instead? Thanks for any tips on this one.

**Comment by grabbou** [comment]
Just define a custom left component in navigation options for a particular route. Default back button on iOS follows native guideline.
