### ISSUE TITLE
Android back button icon not  displayed properly.

### ISSUE THREAD

**Issue by chandu0101** [react-community/react-navigation#432]
I am using `react-nativation` master in my app 
<img width="343" alt="screen shot 2017-02-22 at 4 31 14 am" src="https://cloud.githubusercontent.com/assets/2179670/23189219/f184404c-f8b7-11e6-97a4-151368944333.png">

**Comment by RomualdPercereau** [comment]
I get the same issue.

**Comment by chandu0101** [comment]
@grabbou  it just made things worse :( 

<img width="338" alt="screen shot 2017-02-22 at 8 07 58 pm" src="https://cloud.githubusercontent.com/assets/2179670/23216112/d1b097d8-f93a-11e6-9c86-4803b49c4fc2.png">

**Comment by grabbou** [comment]
Run playground from master and as far as I was able to reproduce your initial issue, I couldn't find the 2nd one.

Can you paste here the code you have?

**Comment by chandu0101** [comment]
nothing changed in my code i just ran `npm update`  and my code is two dumb components (HomeScreen,SecondScreen) registered in a stack navigator.

**Comment by chandu0101** [comment]
ok in my SecondScreen render method i have `<Text>Second Screen </Text>` , i replaced this to `<View style = {{flex= 1}}> <Text>Second Screen</Text> </View> `  now looks ok  :s

**Comment by lukesanantonio** [comment]
I can confirm this issue, and also that wrapping the content in a View with flex: 1 fixes it.
That being said the issue of the header being at the bottom of the screen appears in commit 4d1e531c6b87ddca70792a02b45141dda506f11f for me.

**Comment by satya164** [comment]
@lukesanantonio can you send a PR to fix it?

**Comment by lukesanantonio** [comment]
@satya164 I'm afraid I don't know how to fix this without reverting #436, which looks like it solves another, separate issue.

**Comment by satya164** [comment]
@lukesanantonio you said above that changing flex direction fixes it.

**Comment by lukesanantonio** [comment]
@satya164 I tried adding another View below the View that was modified in the commit I mentioned above. This seems to work so I'm making up the PR now.

**Comment by grabbou** [comment]
Great that my commit revealed this issue. The screen container should take
all the available space and we already wrap scene container with a flex
view for floating header.

Adding a view with flex fixes the issue.

**Comment by chandu0101** [comment]
@grabbou  @lukesanantonio  thanks alot for fixes :)
