### ISSUE TITLE
NavigationPlayground sample project does not allow access to debug menu in iOS

### ISSUE THREAD

**Issue by SandroMachado** [react-community/react-navigation#433]
I am trying to access to the debug menu in iOS (using the shake gesture) for the sample project [NavigationPlayground](https://github.com/react-community/react-navigation/tree/master/examples/NavigationPlayground#navigation-playground-example) to connect the debugger to the browser and I am not able to do it. 
It works as expected in Android. 

Any thoughts how to fix this? I already checked if the app is running in debug mode and tried with other apps and the menu opens.

**Comment by grabbou** [comment]
Fixed
