### ISSUE TITLE
How to dynamically get initialRouteName ?

### ISSUE THREAD

**Issue by MintyOwl** [react-community/react-navigation#435]
```
export default App = DrawerNavigator({
    Home: {
        screen: First
    },
    Second: {
        screen: Second
    }
}, {
    initialRouteName: Route(),
    contentComponent: CustomItem
});
```

`Route()` is a custom function that fetches data from database in async fashion. Since I cannot return value in async, how can i achieve this effect?

**Comment by satya164** [comment]
How can you specify initial route like that if it's async?

**Comment by MintyOwl** [comment]
I cannot, thats why I am stuck. But I want to dynamically set the value of `initialRouteName`. Is there a way to achieve this?

I was thinking to send a callback inside the `rt` function, but react-native has problems with global variables.  Global variable doesnot seem to  work in React properly as seen from this code below.
```
let globalvar = ""

const setglobalvar = (v) => {
     globalvar = v
     console.log(globalvar) // value correctly set here
}

const rt = async (fn) => {
    try {
        const value = await AsyncStorage.getItem('key');
       fn(value)
    } catch (error) {
        ToastAndroid.show('Error fetching from DB', ToastAndroid.SHORT)
    }
}

 const Route = () => {
    rt(setglobalvar)
    console.log(globalvar) // value is NOT set here
    return globalvar
}

class App extends Component {
   ................
   ...........
}

export default App = DrawerNavigator({
    Home: {
        screen: First
    },
    Second: {
        screen: Second
    }
}, {
    initialRouteName: Route(),
    contentComponent: CustomItem
});
```

**Comment by satya164** [comment]
> But I want to dynamically set

Your title says *get*, so I was confused.

So what you can do is render a splash screen route or something till data is fetched, then navigate to the route you want after data is loaded. Dynamically setting it is not possible ATM, but we need to fix that.

**Comment by MintyOwl** [comment]
> render a splash screen route or something till data is fetched, then navigate to the route you want after data is loaded

Not sure what that is. An example would be great, if possible.

Thanks a lot.

**Comment by MintyOwl** [comment]
Oh I see what you are saying. I am closing the issue for now.

**Comment by RazerTang** [comment]
I also want this function,have you fixed?

**Comment by wcandillon** [comment]
I would be also interested to be able to set `initialRouteName` as a prop of the navigator. Same use cases as described above,

**Comment by rohozhnikoff** [comment]
+1

**Comment by szymczakk** [comment]
+1

**Comment by ralcon** [comment]
+1

**Comment by PerspectivesLab** [comment]
+1

**Comment by brentvatne** [comment]
please write a detailed rfc if this is important to you. https://github.com/react-navigation/rfcs
