### ISSUE TITLE
Error: node has not been attached to a view

### ISSUE THREAD

**Issue by rom1k** [react-community/react-navigation#438]
http://i.imgur.com/RwAB3Li.png

I have 4 tabs
I'm getting this error when trying to change the icon on any tab other than the first one.

1. Added this to my first tab, no errors:
```
class FeedScreen extends Component {

  static navigationOptions = {
    tabBar: {
      icon: ({ tintColor }) => (
        <Image
          source={images.icons.home}
          style={theme.tabIconStyle}
        />
      )
    }
  }
```

2. Added this to my second tab (same code), got error "node has not been attached to a view":
```
class MapScreen extends Component {

  static navigationOptions = {
    tabBar: {
      icon: ({ tintColor }) => (
        <Image
          source={images.icons.search}
          style={theme.tabIconStyle}
        />
      )
    }
  }
```

My navigator looks like this:
```
const routeConfig = {
  Feed: { screen: FeedScreen },
  Map: { screen: MapScreen },
  Notifications: { screen: NotificationScreen },
  More: { screen: MoreScreen }
}

const tabNavConfig = {
  initialRouteName: 'Feed',
  navigationOptions: {
    header: {
      visible: false,
    },
  },
  tabBarPosition: 'bottom',
  tabBarOptions: {
    showIcon: true,
    showLabel: false
  }
}

const MainTabNavigator = TabNavigator(
  routeConfig,
  tabNavConfig
)
```

The MainTabNavigator is nested inside a StackNavigator

Any ideas?

**Comment by rom1k** [comment]
Closing this, I was missing an import (Image). Error messages in react native are more confusing than helpful.

**Comment by samcorcos** [comment]
I got the same error when trying to `mapStateToProps` to a key that doesn't exist.

**Comment by jose920405** [comment]
+1.

- I'm using redux.
- React version:

`0.39`

**Comment by aliszafar1** [comment]
+1

**Comment by Amurmurmur** [comment]
For me the problem was that <View> is not supported inside the <Text> tag on Android.

**Comment by jinxac** [comment]
I was facing similar issue when an error was thrown by a function in my common library.

**Comment by ManvendraFlipkart** [comment]
I was facing a similar issue. It turned out that I was using "Text" element and I forgot to import it from "react-native". I was also using js-linter, but still it was not able to point out this error!
The message "Error: node has not been attached to a view" was very confusing, ate a lot of my time!
Hope this helps!

**Comment by ThomasGHenry** [comment]
+1 for barfing on undefined props. Thanks, all!
