### ISSUE TITLE
wrong merge of navigationOptions

### ISSUE THREAD

**Issue by pvinis** [react-community/react-navigation#439]
here is the problem case:

i have
```
const Navigator = StackNavigator({
  Login: { screen: LoginScreen },
}, {
  navigationOptions: {
    header: {
      style: {
        backgroundColor: 'green',
      },
    },
  },
  headerMode: 'screen',
})
```

this gives me a nav header that has a green background. now in the loginscreen i have
```
LoginScreen.navigationOptions = {
  title: 'Log In',
  header: {
    visible: true,
  },
}
```
this should change nothing, except for the title. so in that screen, i should have a green header with the title of Log In. yet, i dont. and thats because the `header` part that has the `style` is replaced by the one that has the `visible`.

i found that the problem is on the bottom of the `createConfigGetter.js` file. in the last 15 lines, its making an array of the `navigationOptions` and running a reduce on them. the problem is that it returns the value of every next option. what should happen there is instead of
```
options[optionName]
```
in all variations should be
```
Object.assign(acc[optionName], options[optionName])
```
or we can use immutablejs and do `mergeDeep`.

@grabbou is there a preference on how we should do that?

**Comment by grabbou** [comment]
Unfortunately it's been already discussed https://github.com/react-community/react-navigation/issues/48 and closed. 

My original PR introducing that feature used to do it, but I removed it as requested.

CC: @ericvicenti 

For now, in order to avoid overriding that config, you have to:
```
navigationOptions: {
   header: (_, defaultHeader) => ({
      ...defaultHeader,
      visible: true,
   }),
}
```

(merge manually)

**Comment by pvinis** [comment]
ok that works. but it seems weird to me. i still think this shouldnt be a manual merge. now its making 2 simple lines of code into 4 slightly more complex lines.

also, we have the "default" options set once, and we have screen-specific changes in all screens. repeating these extra lines and manual merging in every screen file seems unnecessary.

**Comment by grabbou** [comment]
Yeah, I know. Hm, wish I could link to a history of this conversation (forgot). Maybe @satya164 knows where to look. He has been very opinionated here as well as me.

**Comment by pvinis** [comment]
yes i would like to hear his opinion too. mostly because none of the 4 api suggestions on the other issue have deep merging. all use manual merging.
lets wait for a comment from him.

**Comment by grabbou** [comment]
@pvinis the discussion was held before this repo was open sourced and looks like we lost the track of it.
