### ISSUE TITLE
How do I remove shadow effect in screens transitions?

### ISSUE THREAD

**Issue by jamesalways** [react-community/react-navigation#440]
Hello! 

In stack navigator for example, when you go to next screen, this screen has a shadow in the left, how do I remove it?

Thanks!!

**Comment by jamesalways** [comment]
I just see what you can pass cardStyle prop to stack navigation options. Closed!

**Comment by grabbou** [comment]
Mind pasting your solution so others know what to use? :) Sounds like a common question!

**Comment by jamesalways** [comment]
```
import { StackNavigator } from 'react-navigation';
import Login from '../components/auth/login';
import Index from '../components/auth';

const AuthNavigator = StackNavigator({
        AuthIndex: { screen: Index },
        Login: { screen: Login },
    },
    {
        initialRouteName: 'AuthIndex',
        headerMode: 'none',
        cardStyle: {
            shadowOpacity: 0,
        }
    }
);

export default AuthNavigator;

```

**Comment by mfy5013** [comment]
jamesalways' answer did not work for me, using v4
what worked for me was

` {
        `cardOverlayEnabled: false
    }`

insted of

`    {
        cardStyle: {
            shadowOpacity: 0,
        }
    }`
