### ISSUE TITLE
`onTransitionStart` from within the screen component

### ISSUE THREAD

**Issue by f0rr0** [react-community/react-navigation#447]
Can this be moved to screen config from navigator config? I need to dispatch an action `onTransitionStart`, however I don't have `dispatch` when setting up the navigator

**Comment by grabbou** [comment]
If you use `redux`, you can export your store from another file and just access it statically, e.g.:
```js
store.dispatch(action)
```
would that work?

**Comment by f0rr0** [comment]
@grabbou my `createStore` function is async and is called on app start

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!

**Comment by Luckygirlllll** [comment]
What is update regarding this issue? is that possible to get access to  onTransitionStart in the particular screen?
