### ISSUE TITLE
Help: setParams in nested navigators

### ISSUE THREAD

**Issue by artembloom** [react-community/react-navigation#448]
Hey, community!

I want to make this structure:

```
Stack
-- Modal
-- Tabs
     --Tab1(Stack)
         -- Screen1
         -- Screen2
     --Tab2(Stack)
         -- Screen3
         -- Screen4
```

I tried to setParams on Screen3 (componentDidMount). But when I go to Tab2, params on Screen3 disappear (because of action NAVIGATE to Tab2)

How to save params on Screen3 or catch action when user go to Tab2?

Thanks in advance.

**Comment by KabirKang** [comment]
I'm having this issue too with a stacknavigator nested in each tab of a tab navigator. trying to setparams of the tab navigator on some screens so i can hide the tabs sometimes.

**Comment by grabbou** [comment]
Duplicate of #80 and #42
