### ISSUE TITLE
Disable android back button?

### ISSUE THREAD

**Issue by rom1k** [react-community/react-navigation#455]
Is there a simple way to disable the hardware back button in android for specific screens? I couldn't find it in the docs.

**Comment by grabbou** [comment]
Built-in `BackAndroid` handler is registered by the default navigation container [here](https://github.com/react-community/react-navigation/blob/master/src/createNavigationContainer.js#L89) and dispatches `back` action. 

You can use `Redux` for instance (or anything else that has state and dispatch). When you do it, the navigation container [resigns from managing the state](https://github.com/react-community/react-navigation/blob/master/src/createNavigationContainer.js#L88) and so, the `BackAndroid` handling is up to you.

Does that sound like a solution?

**Comment by rom1k** [comment]
Thanks for your reply

A simple navigation option for this would be very useful, for example disableBack: true, which would disable back gesture, back button and hide the back button. I couldn't get react-navigation to work together with redux so I decided to just use the navigation prop.

**Comment by satya164** [comment]
`TabRouter` has a `backBehaviour` config. PR welcome for `StackRouter`

**Comment by grabbou** [comment]
I am going to send over a fix for that tomorrow in the morning.

**Comment by grabbou** [comment]
@satya164 afaik the `backBehaviour` in tab router relates to how `back` button works (whether it resets the tab or you go to previous one).

Here, the OP talks about disabling back button (and ideally) gestures on per route basis. Might be useful for things like custom ads. 

That said, I believe that should go into `navigationOptions` if possible.

**Comment by satya164** [comment]
> afaik the backBehaviour in tab router relates to how back button works (whether it resets the tab or you go to previous one)

Not sure what you mean by resetting tab, but afaik right now only two back behaviours are going to first tab and back action not being handled.

> That said, I believe that should go into navigationOptions if possible.

Agree. Same for tab router too.

**Comment by grabbou** [comment]
> Not sure what you mean by resetting tab

Going to initial tab :)

**Comment by satya164** [comment]
Afaik there is no config to go to previous tab

**Comment by grabbou** [comment]
You are right, my wrong wording 👌

**Comment by jkomyno** [comment]
@grabbou So that's the reason why, if I touch the back button on a screen, instead of going back to the previous one it freezes the app and returns to the smartphone desktop? I'm using Redux (followed your example configuration along to connect the app navigator with the central state) and I haven't configured the BackAndroid.addEventListener stuff.

**Comment by Fenwil** [comment]
@grabbou I did this on my RootContainer and it works but on my main screen I cannot go back and send the app to the background. Is there anyway to say "in this scene/view you shouldn't go back and go to the background" ?

```
import React, { Component, PropTypes } from 'react';
import { connect } from 'react-redux';
import { BackAndroid } from 'react-native';
import { addNavigationHelpers } from 'react-navigation';

import RootNavigator from '@navigators/RootNavigator';

class RootContainer extends Component {
  handleBackPress = () => {
    const { dispatch, nav } = this.props;
    const navigation = addNavigationHelpers({
      dispatch,
      state: nav,
    });
    navigation.goBack();
    return true;
  };
  componentDidMount() {
    BackAndroid.addEventListener('hardwareBackPress', this.handleBackPress);
  }
  componentWillUnmount() {
    BackAndroid.removeEventListener('hardwareBackPress', this.handleBackPress);
  }
  render() {
    const { dispatch, nav } = this.props;
    return (
      <RootNavigator
        navigation={addNavigationHelpers({
          dispatch,
          state: nav,
        })}
      />
    );
  }
}

RootContainer.propTypes = {
  dispatch: PropTypes.func,
  nav: PropTypes.object,
};

function mapStateToProps(state) {
  return {
    nav: state.nav,
  };
}

export default connect(mapStateToProps)(RootContainer);

```

**Comment by caleb-tolu** [comment]
@Fenwil have you been able to resolve the issue ?
I had the same problem but resolved it this way tho it might not be the best solution to it 
`if(navigation.state.routes[0].index === 0) return false;
   navigation.goBack();
            return true;`
before your `navigation.goBack()` try and add the if block if its gonna work for you.

**Comment by Fenwil** [comment]
Yes I try that, you can give the behaviour you want to any particular screen. Thanks @caleb-tolu

**Comment by satya164** [comment]
You can add a handler for back button in `componentDidMount` of the screen in which you want to disable back button, and return `true` from the handler.

**Comment by selimober** [comment]
@Fenwil In my use case, I only want to send the app to background is my initial screen, where the index happens to be 0. So I did this:

```javascrpit
handleBackPress = () => {
  if (this.props.nav.index) {
    this.props.dispatch({type: "Navigation/BACK"})
    return true
  } else {
    return false
  }
}
```

**Comment by jimmytb** [comment]
@selimober thanks, really helped me!

**Comment by Noitidart** [comment]
@grabbou you said: 

> @satya164 afaik the backBehaviour in tab router relates to how back button works (whether it resets the tab or you go to previous one).

I am using TabRouter, I set `backBehavior` to the values of `none` and `initialTab` but both ways it the back is not going to the previous tab. Is there an option to make it go to previous tab? That's what I'm looking for.
