### ISSUE TITLE
How to render global footer?

### ISSUE THREAD

**Issue by lappalj4** [react-community/react-navigation#456]
I would like to have a global navigation footer at the bottom of the screen on all screens. Is there a simple way to do that?

**Comment by grabbou** [comment]
What you mean by `global navigation footer`? How it should behave? It's not clear from your issue what the question really is.

**Comment by lappalj4** [comment]
I think it is rather clear from my question that I want a custom view to be shown ``` at the bottom of the screen on all screens```. To see what I mean, something in the essence of this is what I'm going for: 

`
<Provider store={store}>
    <AppNavigator />
    <MyFooter/>
</Provider>
`

**Comment by satya164** [comment]
So what's wrong with what you're doing right now?

**Comment by grabbou** [comment]
Yeah, was just going to ask. Your snippet looks pretty much like what I would do.

**Comment by lappalj4** [comment]
For starters, Provider only takes one view as a child, so I would have to do something like this: 

```
<Provider store={store}>
    <View>
         <AppNavigator />
         <MyFooter />
     </View>
</Provider>
```

But then I'm unable to get anything to show, and the following error shows up on launch:
```
Possible Unhandled Promise Rejection (id: 0) undefined is not an object (evaluating 'store.dispatch') ... (followed by an unreadable stacktrace)
```

**Comment by satya164** [comment]
> For starters, Provider only takes one view as a child

So just wrap it in a view

> But then I'm unable to get anything to show, and the following error shows up on launch:

your store is `undefined`

**Comment by lappalj4** [comment]
@satya164, to reiterate: 

Works normally:
```
<Provider store={store}>
    <AppNavigator />
</Provider>
```

Does not render anything:
```
<Provider store={store}>
    <View>
        <AppNavigator />
    </View>
</Provider>
```

**Comment by lappalj4** [comment]
My bad, I needed to add flex: 1 to the container view... Sorry for the troubles

**Comment by Irosshipaz** [comment]
What if I want to pass `<AppNavigator />`'s navigator prop to `<MyFooter />` because it will render a 'Next' and 'Back' button?

**Comment by chuntley** [comment]
@Irosshipaz , the only way I was able to access the navigation prop in the global footer was to use the Redux integration: https://github.com/react-community/react-navigation/blob/master/docs/guides/Redux-Integration.md

As long as your components are within the <Provider> tag, you will always be able to access it in the Redux store.

**Comment by lykfe** [comment]
I'm guessing that the answer to this question is no....
it seems that everyone here kind of missed the point of the question.
There's a global navigation header that Navigation can take in as `header` but there isn't one for `footer`.  Would be pretty cool if navigationOptions also has a property as footer

**Comment by cseelus** [comment]
Is there any know way to link from your custom footer to a Screen inside AppNavigator?

``` javascript
<Provider store={store}>
    <View>
         <AppNavigator />
         <MyFooter /> // Link from here to a path/screen inside AppNavigator
     </View>
</Provider>

**Comment by apoorv-1310** [comment]
@cseelus navigator is undefined in app.js

**Comment by artemAp** [comment]
My quick solution for a global footer without using redux. It is shown on one of stack navigation and it is hidden on others.

I use 3 version of navigation, but I think this solution can work with version 2.


**nav.js**
`const navigation = React.createRef()

class AppLayout extends React.Component {
  state = {
    isFooter: false
  }
  handleNavigationChange = (prev, next, action) => {
    // change isFooter state here
  }

  render () {
    const { isFooter } = this.state
    return (
      <View style={{ flex: 1, backgroundColor: '#fff' }}>
        <AppNav
          onNavigationStateChange={this.handleNavigationChange}
          ref={navigation}
        />
        {isFooter && <Footer navigation={navigation.current} />}
      </View>
    )
  }
}

export default AppLayout`

**footer.js**
`const navigateTo = (navigation, screen) => {
  console.log('navigation', navigation)
  navigation.dispatch(
    NavigationActions.navigate({ routeName: screen })
  )
}

const Footer = ({ navigation }) => (
  <SafeAreaView style={styles.footer}>
    <TouchableOpacity style={styles.chatBtn} onPress={() => navigateTo(navigation, 'About')} />
  </SafeAreaView>
)`

**Comment by artemAp** [comment]
My quick solution for a global footer without using redux. It is shown on one of stack navigation and it is hidden on others.

I use 3 version of navigation, but I think this solution can work with version 2.


**nav.js**
```javascript
const navigation = React.createRef()

class AppLayout extends React.Component {
  state = {
    isFooter: false
  }
  handleNavigationChange = (prev, next, action) => {
    // change isFooter state here
  }

  render () {
    const { isFooter } = this.state
    return (
      <View style={{ flex: 1, backgroundColor: '#fff' }}>
        <AppNav
          onNavigationStateChange={this.handleNavigationChange}
          ref={navigation}
        />
        {isFooter && <Footer navigation={navigation.current} />}
      </View>
    )
  }
}
```

**footer.js**
```javascript
const navigateTo = (navigation, screen) => {
  navigation.dispatch(
    NavigationActions.navigate({ routeName: screen })
  )
}

const Footer = ({ navigation }) => (
  <SafeAreaView style={styles.footer}>
    <TouchableOpacity style={styles.chatBtn} onPress={() => navigateTo(navigation, 'About')} />
  </SafeAreaView>
)
```

**Comment by brayanL** [comment]
I am using NavigationService [https://reactnavigation.org/docs/en/navigating-without-navigation-prop.html](url), so I have the navigation from Footer component. Thanks for your example @artemAp
