### ISSUE TITLE
Access children routes from parent StackNavigator

### ISSUE THREAD

**Issue by llaine** [react-community/react-navigation#457]
Hello,
I have the following issue.

My main navigator : 

```js
const defaultNav = StackNavigator({
  defaultParentRoute: {
    screen: DefaultParentComponent,
  },
})
```

And in my component Login 

```js
class DefaultParentComponent extends Component {

  static navigationOptions = {
    header: ({ navigate }: any) => {
      return {
        right: (
          <Button title='next'
                  onPress={() => {
                    navigate('childRouteB');
                  }}/>
        ),
        visible: true,
      };
    },
  };

  render() {
    return (
      <View>
        <ChildrenNavigator />
      </View>
    );
  }

}
```

which render a second navigator (children) called `SignupNavigator`

```js
const ChildrenNavigator = StackNavigator({
  childRouteA: {
    screen: ChildComponentA,
  },
  childRouteB: {
    screen: ChildComponentB,
  },
})
```

My button never manages to go to the children routes `ChildComponentB`, am I missing something or doing something wrong here? 

I tried using `dispatch` and create a full action but nothing works.

**Comment by grabbou** [comment]
What renders for the first time when you open the app? From the snippet, looks like `routeB` with `ComponentB` renders by default.

> My button never manages to go to the children routes routeB

Not sure how it would. Did you mean `routes of routeB`? Is `routeB` another Stack Navigator?

**Comment by llaine** [comment]
I updated my comment.
So basically when I render the app the `defaultNav` navigator renders with the `LoginScreen` as the main route. 
This one render by default the `ChildComponentA`. 

My issue is that I would like to go to the `childRouteB` from the `DefaultParentComponent`

``

**Comment by KyleKhalaf** [comment]
I have the same problem here and now. I want to from a screen in the parent navigator, to access a screen in the child navigator. How can we do that?

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
