### ISSUE TITLE
Set `initialRouteName` and `initialRouteParams` based on props

### ISSUE THREAD

**Issue by dasmikko** [react-community/react-navigation#458]
Hi

Is it possible to have a conditional homescreen?

Like, the app knows from the start that your not logged in, then automatically show the login screen, else show the "real" home.

Hope my question makes sense.

**Comment by grabbou** [comment]
Hey,

Assuming your static knowledge is:
```js
const isLoggedIn = true;
```
you can just use `initialRouteName` property and pass it to StackNavigation to select the route.

**Comment by satya164** [comment]
You can't set `initialRouteName` and `initialRouteParams` based on props right now, but I think we need this.

**Comment by grabbou** [comment]
Yeah, sounds like a valid use case. I'll take a look into that in the morning (I need it anyways for that exact purpose)

**Comment by dasmikko** [comment]
>@grabbou 
> you can just use initialRouteName property and pass it to StackNavigation to select the route.

I'm not sure what you mean by this. I'm pretty new to ReactJS and React Native.

**Comment by grabbou** [comment]
No worries. I just meant that if you now the variable at compile time
(before `render`), at the time when you call `StackNavigator(Routes)`, you
can pass the 2nd argument `{ initialRouteName: isLoggedIn ? 'a' : 'b' }`.

But as Satya said, you are probably talking about deciding inside
`render()`, which we do not support yet. I'll land that tomorrow if
no-one's faster :)

**Comment by dasmikko** [comment]
Now I understand. 

Looking forward for the new feature! :)

**Comment by jeffreymendez1993** [comment]
You could easily do something like this. 
<img width="561" alt="screen shot 2017-02-24 at 9 24 22 am" src="https://cloud.githubusercontent.com/assets/8095978/23306839/3258cda6-fa73-11e6-9f3b-bb3a1f1ae1d1.png">

**Comment by jeffreymendez1993** [comment]
You guys could always do something like this @dasmikko @grabbou 
<img width="834" alt="screen shot 2017-02-24 at 9 30 57 am" src="https://cloud.githubusercontent.com/assets/8095978/23307080/2ab65d56-fa74-11e6-8f92-de72d8dfcd0a.png">

**Comment by BenMcH** [comment]
@jeffreymendez1993 That would add to the stack and cause the back button on android for example to take you to the "InitialScene" view. The gestures are still there.

Using the reset action should be all that is needed. 

https://reactnavigation.org/docs/navigators/navigation-prop

**Comment by dasmikko** [comment]
I'm a little consfused for when I should fire the reset.

Because I have a login screen, but I don't want to user to be able to go back.

**Comment by BenMcH** [comment]
@dasmikko I made a method in my splash screen that takes the name of the route as an argument and I can just call that with the route name. 

I can provide an example in a couple hours when I get home.

**Comment by dasmikko** [comment]
Looking forward to see the example.

**Comment by grabbou** [comment]
Alternatively, you can have two navigators and if statement in render. Both use-cases are valid. I think for time-being this is a satisfactory solution and the issue can be closed.

**Comment by BenMcH** [comment]
@dasmikko I completely forgot last night. 

What I have is something like this in my splash screen class:

```javascript
reset = (route) => {
  let resetAction = NavigationActions.reset({
    index: 0,
    actions: [
      NavigationActions.navigate({ routeName: route})
    ]
  });
  this.props.navigation.dispatch(resetAction);
}
```

**Comment by satya164** [comment]
This is not solved.

**Comment by grabbou** [comment]
I feel it would also solve a couple of other issues we have spotted, esp. with Tab navigator.

**Comment by satya164** [comment]
I think we could deprecate `screenProps` too once we have functionality to pass `initialParams` during render.

**Comment by jeffreymendez1993** [comment]
@BenMcH Yes using reset should do the trick. I need to add this into my application as well good.

**Comment by MrHubble** [comment]
@grabbou 

>Alternatively, you can have two navigators and if statement in render

Are you able to provide sample code on how to do this? I tried following the example given by @jeffreymendez1993  but I get an error as it's my initial screen and there is no value for `const { navigate } = this.props.navigation;`

**Comment by f0rr0** [comment]
Any progress on this?

**Comment by shrutic** [comment]
Is there a fix in works for this long-standing issue? I have scenario where:

- The first screen (initialRouteName) depends on props ( I have taken the route of creating 2 navigators with different initialRoute)

- If one of the 2 navigators is selected, I need to pass a dynamic initialRouteParams, that is residing in the this.props of the component launching the navigator 

Appreciate insight on how to address the second bullet point

**Comment by demonhunterunderdarkness** [comment]
@sata
Pass initalRouteName as a props still not work now,so I have to define two or more StackNavigators as an alternative  solution for conditional choice.
Thanks for your job anyways

**Comment by vitorebatista** [comment]
Any progress on this?

**Comment by jaredmharris** [comment]
Need this!

**Comment by jasan-s** [comment]
I naively thought I could do this :(

`{
  initialRouteName: (props) => {
    return props.screenProps.isAuthed ? 'Home' : 'Auth'
  }
}`

> Get the error , Cannot get config because the routes does not have a routeName

**Comment by dmr07** [comment]
@grabbou Regarding your comment of using if statements in the render function, I must disagree that it is satisfactory. By using conditional rendering, screen transitions are lost, which result in UI ambiguity for the user. I have attempted to wrap the elements in AnimatedAPI, but transitions are very choppy for some reason. 

It seems to me that if StackNavigators are designed to be nested, they ought to have ways to dynamically set the initial route or else it is self-defeating. 

Would love to see this implemented when you guys have a chance.

**Comment by stantoncbradley** [comment]
this works for us:
```
const Navigator = ({ initialRouteName, screenProps }) => {
  const stackNavigatorConfigs = {
    initialRouteName,
    navigationOptions: ({ navigation }) => ({
      headerStyle: styles.headerStyle,
      headerLeft: <Left navigation={navigation} />,
    }),
  };
  const CustomNavigator = StackNavigator(routeConfigs, stackNavigatorConfigs);
  return <CustomNavigator screenProps={screenProps} />;
};

export const NavWrapper = ({ initialRouteName, screenProps }) => (
  <Navigator screenProps={screenProps} initialRouteName={initialRouteName} />
);

```

**Comment by LEEY19** [comment]
@stantoncbradley Buddy, if my stacknav (or in my case, a drawer nav actually) resides within a bigger react native navigator, how do I 'push' into NavWrapper? Previously, if const Navigator = DrawerNavigator(routeConfigs, drawerNavigatorConfigs) ; , we can just export Navigator, and put it under renderScene belonging to root navigator like this:

///
  renderScene(route, navigator) {
    switch (route.index) {
   ....
      case "App_navigator":
        return <App_navigator screenProps={navigator} />;
    .....
    }
  }
///

But for your solution, how do I do that?

**Comment by stantoncbradley** [comment]
@LEEY19 not sure if I understand 100%...  where are you trying to push to the NavWrapper from?  When you replace `<Navigator />` with the exported `<NavWrapper />` it doesn't work?

It might be helpful to use [redux integration](https://reactnavigation.org/docs/guides/redux) to manage your navigation state manually.  then you can use redux dispatch actions to navigate around your drawer navigator

**Comment by stantoncbradley** [comment]
with redux integration:
we set an initial "loading" screen for initial redux state.
when loading resolves, we reset the navigator to the initial screen we want:
```
const AuthNavigator = StackNavigator(routeConfigs, stackNavigatorConfigs);
const initialState = AuthNavigator.router.getStateForAction(
  AuthNavigator.router.getActionForPathAndParams(routeConfigs.LOADING),
);

export const authNavReducer = (state = initialState, action) => {
  if (Object.values(routeNames).includes(action.type)) {
    const navAction = AuthNavigator.router.getActionForPathAndParams(action.type, action.params);
    const nextState = AuthNavigator.router.getStateForAction(navAction, state);
    return nextState;
  }
  const nextState = AuthNavigator.router.getStateForAction(action, state);
  return nextState || state;
};


const AuthNavWrapper = ({ dispatch, nav, screenProps }) => (
  <AuthNavigator
    navigation={addNavigationHelpers({
      dispatch,
      state: nav,
    })}
    screenProps={screenProps}
  />
);

const mapStateToProps = state => ({
  nav: state.authNav,
});

const AuthNavigationWithState = connect(mapStateToProps)(AuthNavWrapper);

export default AuthNavigationWithState;
```

then dispatch reset action:
```
navigateToInitialAuthScreen: (routeName) => {
    const navAction = NavigationActions.reset({
      index: 0,
      actions: [
          { type: 'Navigate', routeName },
      ],
    });
    dispatch(navAction);
  },
```

**Comment by MrLoh** [comment]
If you are using redux anyways, you might consider just implementing the logic for the tab router yourself, since it is quite trivial and to use [react-native-tab-view]( https://github.com/react-native-community/react-native-tab-view) for the animations, which has a proper declarative API. 

While the StackNavigator from react-navigation is really great, theres many better libraries for the other routers, that don't have such an akward imperative API. Especially if you are using Redux, consider just using the StackNavigator.

**Comment by zhangming0305** [comment]
@stantoncbradley works even for tabnavigator

```
import React from 'react';
import { connect } from 'react-redux';
import { TabNavigator } from "react-navigation";
import {
  Button,
  Text,
  Icon,
  Item,
  Footer,
  FooterTab,
  Label
} from "native-base";

import MAIN from './Main';
import Second from './Second';
import Summary from './Summary';
import Settings from '../pages/Settings';

const Tabnavigator = ({ initialRouteName }) => {
  const CustomTabNavigator = TabNavigator({
    Main: {
      screen: MAIN,
    },
    Second: {
      screen: Second,
    },
    Summary: {
      screen: Summary,
    },
    Settings: {
      screen: Settings,
    },
  }, {
    tabBarPosition: "bottom",
    tabBarComponent: props => {
      console.log(props);
      return (
        <Footer>
          <FooterTab>
            <Button
              vertical
              active={props.navigationState.index === 0}
              onPress={() => props.navigation.navigate("Main")}
            >
              <Icon name="home"/>
              <Text>Account</Text>
            </Button>
            <Button
              vertical
              active={props.navigationState.index === 1}
              onPress={() => props.navigation.navigate("Second")}
            >
              <Icon name="briefcase"/>
              <Text>Booking</Text>
            </Button>
            <Button
              vertical
              active={props.navigationState.index === 2}
              onPress={() => props.navigation.navigate("Summary")}
            >
              <Icon name="bowtie"/>
              <Text>Summary</Text>
            </Button>
            <Button
              vertical
              active={props.navigationState.index === 3 }
              onPress={() => props.navigation.navigate("Settings")}
            >
              <Icon name="settings"/>
              <Text>Settings</Text>
            </Button>
          </FooterTab>
        </Footer>
      );
    },
    initialRouteName
  });
  CustomTabNavigator.navigationOptions = {
    header: null
  }
  return <CustomTabNavigator/>
}


const TabbarWithProps = props => (
  <Tabnavigator
    initialRouteName={props.hasAccounts ? 'Main' : 'Settings'}
  />
)


const mapStateToProps = state => ({
  hasAccounts: state.bankAccount.accounts.length !== 0,
});


export default connect(mapStateToProps)(TabbarWithProps);

**Comment by MrLoh** [comment]
Yes you can always just construct the navigator inside a components render method. But it's gonna be very inefficient, constructing a new router on each props change.

**Comment by stantoncbradley** [comment]
additionally, you can create an initial route screen and put your initial route logic there.
```
const initialRoute = () => (
  condition ? <RouteA /> : <RouteB />
)
```

**Comment by JulianKingman** [comment]
I couldn't get any of the above to work in combination with my various custom redux things going on, so I used a special screen that instantly resets the navigator depending on the logged in status. I'd be interested to see a better solution.

**Comment by 471685249** [comment]
this solution can't use getStateForAction @zhangming0305

**Comment by hushicai** [comment]
repost

**Comment by hushicai** [comment]
Now react-navigation can just declare routes tree at the very begin, with initialRouteName...
But I need to use it like Navigator.
```jsx
<Navigator initialRouteName={'main or login'} />
```
Now I use a Splash component to acheive this:
```jsx
class Splash extends Component {
   render() {
       if(this.props.authorized === 1) {reset to main}
       else(this.props.authorized === 2) {reset to login}
       return null;
   }
}
const AppNavigator = StackNavigator({
   splash: {screen: Splash},
   login: {screen: Login},
   main: {screen: Main}
});
// use like this in App.js
// authorized could change to 1 or 2, when verify api is resolved.
<AppNavigator screenProps={{authorized: this.props.authorized}} />
```
I think this is troublesome...
Expect this feature...

**Comment by sbalay** [comment]
A feature that would help me a lot is setting the initialRouteName as a promise, and have another param to indicate the "loading" component that's mounted while the promise is resolved.
During that async action that resolves the promise, we can check in AsyncStorage (for react native) if there is any user session saved and then determine the initial route.
That's just one simple example where this proposed feature would help.
Another use case, similar the previously mentioned, is to retrieve the user session from storage, validate it against an authentication api and then determine the proper initial route.

If this makes sense to you, I'm open to help in the implementation if help is wanted/needed.

**Comment by richardgirges** [comment]
Just sharing my experiences with this issue:

I spent weeks going back and forth thru every approach mentioned here. All of them come with their own flavor of headaches. The worst solution I experienced was using _multiple_ navigators, each with their own statically-defined initial route. My navigators were being unmounted/re-mounted based on prop changes (i.e. when the user logged out and the `session` prop became null); this results in all sorts of "setState on an unmounted component" errors. Not to mention you can't do push notification deep linking to any route that isn't pre-defined with it's _own_ navigator.

Ultimately, the cleanest (aka least buggy) approach for me was to go with the Splash screen that resets to the initial route. Having a component whose only purpose is to execute a side-effect (i.e. navigate somewhere) on componentDidMount is the definition of a React anti-pattern, but meh...

**Comment by JulianKingman** [comment]
I came to the same conclusion as @richardgirges. My implementation ended up using connecting the redux navigation state, and getting the active routeName from there to determine whether to try to navigate. Something like this:
```javascript
const getRouteName = (path) => {
    if (path.routes && path.routes.length) {
      return getRouteName(path.routes[path.index]);
    }
    return path.routeName;
};
// ...
componentWillReceiveProps(nextProps) {
    if (getRouteName(nav) === 'NameOfThisRoute') {
       if (case1) {
         this.props.navigate(...somewhere);
       } else {
         this.props.navigate(...somewhereElse);
       }
    }
  }
```

**Comment by csumrell** [comment]
````
@connect(({ auth: { auth} }) => ({
  auth
}))
export default class HomeScreen extends React.Component {

  componentDidMount() {
    if (this.props.auth) {
      this.props.navigation.navigate("AuthStack");
    } else {
      this.props.navigation.navigate("RegularStack");
    }
  }

  render() {
    return (
      <View style={{ flex: 1 }}>
        <ActivityIndicator size="large" />
      </View>
    );
  }
}
`````

I am doing the "splash screen" routing technique, but this prevents the Backhandler from minimizing the app. When a user presses back, it just takes them to this page and then re-routes them back to either of the routes in the componentDidMount. Does anyone know how to resolve this so the backhandler will correctly minimze the app?

**Comment by JulianKingman** [comment]
You could use navigation.reset instead. It can be a bit confusing to use, but works reasonably well.

My original solution turned out to be too buggy (often wouldn't navigate properly), so I ended up using a cringe-worthy solution: setting a 1ms interval to check if the "splash screen" is the current route, and then routing based on that. I feel dirty. Hopefully we'll get a better solution soon.

```javascript
const getCurrentRouteName = (navigationState) => {
  if (!navigationState) {
    return null;
  }
  const route = navigationState.routes[navigationState.index];
  // dive into nested navigators
  if (route.routes) {
    return getCurrentRouteName(route);
  }
  return route.routeName;
};

//...

componentDidMount() {
    const throttledCheck = _.throttle(() => this.navigate(), 1000, {
      leading: true,
    });
    this.checkLayout = setInterval(() => throttledCheck(), 1);
  }

componentWillUnmount() {
    clearInterval(this.checkLayout);
  }

navigate() {
    if (getCurrentRouteName(this.props.nav) === 'SplashScreen') {
      this.props.navigation.dispatch(
        NavigationActions.reset({
          index: 0,
          actions: [
            NavigationActions.navigate({
              routeName: this.props.someProp ? 'Route1' : 'Route2',
            }),
          ],
        }),
      );
    }
  }
```

**Comment by stantoncbradley** [comment]
I'm surprised people are still having issues with this.  Our solution works well for us.  To reiterate in case it wasn't clear:

we define a specific initial route, which has logic for determining which view to render.  each of these routes is defined in the navigator as well, so you can route to them directly whenever.  it's just our initial screen is a wrapper around them:

```
const InitialRoute = ({ routingCondition }) => (
  routingCondition ? <RouteA /> : <RouteB />
);
```
would love to hear why this doesn't work for you

**Comment by philsam** [comment]
@stantoncbradley Please can you provide a gist of your example containing an index.js and your router.js . It appears the pattern doesn't work when you login and put the app in background mode, and when you reopen it goes back to the login nav state.

**Comment by stantoncbradley** [comment]
@philsam here is the working example
https://github.com/stantoncbradley/InitialRouteExample
let me know if that helps

**Comment by richardgirges** [comment]
@stantoncbradley your solution worked really well but I got stuck once I needed one of the initial routes to be a navigator. I wasn't sure how to get the navigator to stay connected to the root navigator. Any thoughts on this?

**Comment by stantoncbradley** [comment]
@richardgirges are you using redux to manage your nav state?

**Comment by philsam** [comment]
@stantoncbradley - Thank you so much for taking the time to create a working example. I'm digging into your gist. I'll update you on my findings soon.

**Comment by richardgirges** [comment]
@stantoncbradley I haven't integrated redux with react navigation -  but my app is making heavy use of redux anyway so I wouldn't mind doing so if it would help resolve this issue.

**Comment by stantoncbradley** [comment]
we haven't had to nest routers yet, but we've found moving our nav state to redux to be easier to work with since it abstracts the nav state out of the navigator. Redux should be able to persist your the nested nav states regardless what is being rendered

**Comment by philsam** [comment]
@stantoncbradley - i've been busy but i took time to dig into the gist and test it in a real scenario. Your solution actually works pretty well. The only thing i noticed was in InitialRouteExample/Navigation.js
The following are not necessary for it to work in the routeConfigs object.
```
login: { screen: LoginScreen },
main: { screen: MainScreen },
```
Apart from that its a great solution and i highly recommend others to follow the pattern.

**Comment by kelset** [comment]
Pinging OP @dasmikko to know if this issue can be closed, since the solution proposed by @stantoncbradley seems to be working fine for multiple users.

Maybe @stantoncbradley can you do a small PR to add your example or an explanation to the docs? 😇

**Comment by richardgirges** [comment]
@kelset I think that @stantoncbradley's solution is clearly the best approach but I would appreciate this issue staying open until there's a more official solution - one that can work out of the box for both redux and non-redux integrated react-navigation apps. In addition to that, it feels like a lot of overhead that one must take on just to handle dynamic initial routes (including the need to re-define any components that _can_ be initial routes in a second place, after already defining them as routes in your navigators). 

Obviously this can fall in priority now that there's a "good enough" solution - it's definitely good enough for me to keep going. But I fear that closing issues when there are only workarounds in place is what has ultimately depleted the quality of react-navigation. I say that a concerned citizen who has placed his bets on the future of react-navigation, it's not meant to be taken as criticism.

If people disagree, then close away. Perhaps I'm misunderstanding the goal behind react-navigation's issue-triaging strategies.

**Comment by kelset** [comment]
Hey @richardgirges thanks for your reply; I'll keep this issue open, but as you can see in #2585 probably it won't be implemented for v1.0. That said we are always trying to review each and every PR so it's not like if somebody provides a PR with this feature we will not merge it ;)

**Comment by richardgirges** [comment]
Thanks @kelset! I have noticed that the open PRs have been slowly depleting. I may even take a crack at this one myself sometime soon, just started getting familiar with the react navigation codebase :)

**Comment by dasmikko** [comment]
@kelset This can be closed, it works for me too. 👍

**Comment by kelset** [comment]
I appreciate your attitude @richardgirges :) How about starting with a new issue that follows the issue template for the feature request you have been writing about? After that you can open a PR and start working on it :)

Don't worry about "not being too familiar" with the codebase, or even deadlines, it's all about you also learning while trying :)

I'll use myself as an example ;) Look here: https://github.com/react-community/native-directory/pull/50

**Comment by amorenew** [comment]
My Full solution
https://github.com/react-community/react-navigation/issues/2683

**Comment by danna88** [comment]
how to solve this issue without redux？？

**Comment by amorenew** [comment]
@danna88  I don't use redux

**Comment by danna88** [comment]
@amorenew Thank you.  I see you are using the InitialScreen, used to jump to other pages, I want to do the function is automatically Login, can I use Login page as InitialScreen? In addition, I used the react-native-splash-screen, but I encountered a problem: I do autoLogin in componentWillMount, then I closed Splash in componentDidMount, but it always render LoginScreen first，then navigate to other pages。

**Comment by amorenew** [comment]
@danna88 I use splash without a library just with timer,
As you can see in initial screen
```
render() {
        return null;
    }
```
which renders nothing so the required screen only will be visible to the user
in `componentWillMount` 
I use `GeneralPref.getInitialScreen()` which is an` AsyncStorage.getItem('initailscreen')`

**Comment by danna88** [comment]
@amorenew thank you very much!  I 'll try it !

**Comment by jeffreymendez1993** [comment]
I use a splash screen and set the initial stack to render. I set up the configuration of my app during the initial launch and when it is completed the router/Stack is returned.

**Comment by iamrutvik** [comment]
So basically redirecting user to the Home screen in nested navigator scenario, I did this little trick. As react-navigation does not provide a way to set the `initialRouteName`, we dispatch an action to navigate to the drawer stack i.e. Home screen.

Here is our Navigation file with Redux integration, which will show you the nesting of various navigators

```
// drawer stack
const DrawerStack = StackNavigator({
  DashboardScreen: { screen: DashboardScreen, navigationOptions: { title: 'Event', drawerLabel: 'Event' } },
  MyAccountScreen: { screen: MyAccountScreen, navigationOptions: { title: 'My Account', drawerLabel: 'My Account' } },
}, {
    headerMode: 'screen',
    navigationOptions: ({ navigation }) => ({
      headerStyle: {
        backgroundColor: Colors.darkBlue,
        shadowOpacity: 0,
        shadowOffset: { height: 0, },
        elevation: 0,
      },
      headerTitleStyle: {
        color: Colors.snow,
        alignSelf: 'center',
      },
      headerLeft: navigation.state.routeName == 'DashboardScreen' ? <TouchableOpacity activeOpacity={0.2} style={styles.leftIcon} onPress={() => {
        navigation.dispatch(NavigationActions.navigate({ routeName: 'DrawerOpen' }));
      }}><Image large source={Images.Bar} style={styles.bar} /></TouchableOpacity> : <TouchableOpacity activeOpacity={0.2} style={styles.leftIcon}
        onPress={() => {
          if (navigation.state.params && navigation.state.params.onBackPress) {
            navigation.state.params.onBackPress();
          }
          navigation.goBack();
        }}><Icon name="angle-left" size={28} color="snow" /></TouchableOpacity>,
      headerRight: <TouchableOpacity activeOpacity={0.2} style={styles.leftIcon} onPress={() => {
        navigation.dispatch(NavigationActions.navigate({ routeName: 'DrawerOpen' }));
      }}><Icon size={28} color="snow" /></TouchableOpacity>

    })
  })
const DrawerNavigation = DrawerNavigator({
    DrawerStack: { screen: DrawerStack }

}, {
    contentComponent: DrawerComponent,
    drawerWidth: 300,
  })
// login stack
const LoginStack = StackNavigator({
  LoginScreen: { screen: LoginScreen },
  RegisterScreen: { screen: RegisterScreen },
  ForgotPasswordScreen: { screen: ForgotPasswordScreen },
  CountryListScreen: { screen: CountryListScreen },
  VerificationScreen: { screen: VerificationScreen },
}, {
    headerMode: 'none',
  })
// Manifest of possible screens
const PrimaryNav = StackNavigator({
    drawerStack: { screen: DrawerNavigation },
    loginStack: { screen: LoginStack },
  }, {
    // Default config for all screens
    headerMode: 'none',
    initialRouteName:  'loginStack',
    transitionConfig: noTransitionConfig,
})
export default PrimaryNav
```

Now we have done a little bit tweak in the first App.js file which will run just after botting the React native application from index.ios.js/index.android.js/index.js file. We just set a state `loading` to check whether data is loaded from `AsyncStorage` or not. And if the data is loaded, then we will return our Root component else we will return null, which will not show login screen or anything on the UI front.

```
import '../Config'
import DebugConfig from '../Config/DebugConfig'
import React, { Component } from 'react'
import { Provider } from 'react-redux'
import RootContainer from './RootContainer'
import createStore from '../Redux'
import { AsyncStorage, Linking } from 'react-native'
import Constants from '../Components/Constants'
import LinkRoutes from '../Config/LinkRoutes';
import {NavigationActions} from 'react-navigation';

// create our store
const store = createStore()

/**
 * Provides an entry point into our application.  Both index.ios.js and index.android.js
 * call this component first.
 *
 * We create our Redux store here, put it into a provider and then bring in our
 * RootContainer.
 *
 * We separate like this to play nice with React Native's hot reloading.
 */
class App extends Component {

  constructor(props) {
    super(props)
    this.state = {
      loading: false,
    }
  }


  componentWillMount() {
    AsyncStorage.getItem(Constants.KEY_IS_LOGIN, (err, result) => {
      this.setState({ loading: true} , () => {
        if (result === '1') {
          const navigateAction = NavigationActions.navigate({
            routeName: 'drawerStack',
            index: 0,
          });
          store.dispatch(navigateAction);
        }
      })
    });
  }


  render() {
    if(this.state.loading){
      return (
        <Provider store={store}>
          <RootContainer />
        </Provider>
      )
    }else{
      return null
    }
  }
}

// allow reactotron overlay for fast design in dev mode
export default DebugConfig.useReactotron
  ? console.tron.overlay(App)
  : App

``` 

In `componentWillMount` I have just dispatched a `NavigationActions` that will navigate to the Drawer screen/Home screen. Hope this helps.

**Comment by eugenecp** [comment]
easy as pie
-------
var signedIn = false ; // however , whatever
var routes = {
      Categories: { screen: Categories },
      Landing: { screen: Landing }
    }
    
    if (signedIn) { 
      routes = {
        Landing: { screen: Landing },
        Categories: { screen: Categories }
      }
    }

    routes.SignIn = { screen: SignIn }

    var MyApp = StackNavigator(
      routes );

    return <MyApp />;

**Comment by stantoncbradley** [comment]
@eugenecp this will only evaluate 'signedIn' once, right? How does this get updated once the user signs in/out? Wouldn't it have to rebuild the whole stackNavigator?

**Comment by dwivediamit** [comment]
Hi, I am using react-native tab navigator for two tabs, account and profile i want if user is logged in then only it will show the account and profile screen otherwise it will go to login screen.

Here I have given onPress condition but how to check user is logged or not in below code...
onPress={() => {
                if (props.navigationState.index === false) {
                  alert('Hi');
                  props.navigation.navigate("Profile")
                } else {
                  alert('Yes');
                  props.navigation.navigate("Login")
                }
              }}



This is my code index.js 

import React, { Component,AsyncStorage } from "react";
import Home from "./Home.js";
import Schedule from "./Schedule.js";
import Account from "./Account.js";
import Location from "./Location.js";
import Profile from "./Profile.js";
import { TabNavigator } from "react-navigation";
import {
  Button,
  Text,
  Icon,
  Item,
  Footer,
  FooterTab,
  Label
} from "native-base";


import styles from "../../css/style";



export default (MainScreenNavigator = TabNavigator(



  { 
    Home: { screen: Home},
    Schedule: { screen: Schedule },
    Account: { screen: Account },
    Location: { screen: Location },
    Profile: { screen: Profile }
  },
  {
    tabBarPosition: "bottom",
    tabBarComponent: props => {
      return (

        <Footer>
          <FooterTab>
            <Button
              vertical
              active={props.navigationState.index === 1}
              onPress={() => props.navigation.navigate("Schedule")}
            >
              <Icon name="calendar" />
              <Text>Schedule</Text>
            </Button>

           

            <Button
              vertical
              active={props.navigationState.index === 2}
              onPress={() => {
                if (props.navigationState.index === false) {
                  alert('Hi');
                  props.navigation.navigate("Account")
                } else {
                  alert('Yes');
                  props.navigation.navigate("Login")
                }
              }}>
              <Icon name="barcode" />
              <Text>Account</Text>
            </Button>

          
            
            <Button
              vertical
              active={props.navigationState.index === 3}
              onPress={() => props.navigation.navigate("Location")}
            >
              <Icon name="ios-navigate-outline" />
              <Text>Location</Text>
            </Button>


            
            <Button
              vertical
              active={props.navigationState.index === 4}
              onPress={() => {
                if (props.navigationState.index === false) {
                  alert('Hi');
                  props.navigation.navigate("Profile")
                } else {
                  alert('Yes');
                  props.navigation.navigate("Login")
                }
              }}>
              <Icon name="person" />
              <Text>Profile</Text>
            </Button>
       
          
          </FooterTab>
        </Footer>
      );
    }
  }
));

**Comment by slorber** [comment]
An easy workaround for that is to wrap the navigation into a class, get a ref, and dispatch a reset action on mount.


class WrappedNavigation extends Component {

  return <MyNav ref={c => this.myNav = c}/>;
}

**Comment by kkotkkio** [comment]
const RootStackNavigatorWrap = (initialRouteName) => {

  const RootStackNavigator = StackNavigator(
    {
      Main: {
        screen: MainTabNavigator,
      },
      Join: {
        screen: JoinNavigator
      },
    },
    {
      ...initialRouteName,
      navigationOptions: ({ navigation }) => ({
        header: null
      }),
    }
  );
  return <RootStackNavigator/>;
};

export class RootNavigator extends React.Component {
  render() {
    return <RootStackNavigatorWrap initialRouteName={this.props.app.initialRouteName}/>;
  }
}

**Comment by wellyshen** [comment]
If I want to keep the transition of react-navigation with dynamic `initialRouteName ` any suggestion for it?

**Comment by amorenew** [comment]
@wellyshen may help https://github.com/react-navigation/react-navigation/issues/2683

**Comment by wellyshen** [comment]
@amorenew Thank you my solution is not to invoke navigator re-rendered immediately so that the transition of react-navigation won't be cut off. BTW this [post](https://medium.com/the-react-native-log/building-an-authentication-flow-with-react-navigation-fb5de2203b5c) explain the idea of **login** flow of react-navigation. Help it'll help someone else.

**Comment by brentvatne** [comment]
if you need to set the `initialRouteName` as a prop it is because there is some data that you need to fetch asynchronously before you render the app navigation. another way to handle this is to use a switchnavigator and have a screen that you show when you are fetching the async data, then navigate to the appropriate initial route with params when necessary. see https://reactnavigation.org/docs/auth-flow.html for a full example of this.

that said, if you think that it is important to support these options as props then please feel free to thumbs up this rfc issue: https://github.com/react-navigation/rfcs/issues/23. and if you really care about it a lot, please open a proper rfc from the rfc template! thanks!
