### ISSUE TITLE
Native module cannot be null (blast from the past)

### ISSUE THREAD

**Issue by ferologics** [react-community/react-navigation#460]
I wrap already working component in the simplest way

```js
const Demos = StackNavigator({
  Home: { screen: DemoList }
})
```

I `AppRegistry.registerComponent('Demos', () => Demos)`. Voilà:

error - `Native module cannot be null.`

If I `AppRegistry.registerComponent('DemoList', () => DemoList)` everything works like a charm.

It's a hybrid app with Cocoapods / RN / Obj-C. The registered component is being initialized as `RCTRootView` module, later presented as a ViewController in native.

**Comment by ferologics** [comment]
In fact, just mentioning StackNavigator gives me the error, unrelated to component registry. Must be something off with project structure, just can't figure out what it is.

**Comment by ferologics** [comment]
I was missing the `RCTLinkingIOS` pod subspec inside my Podfile. All good here 💯

**Comment by mariobento** [comment]
mehh had to search on the issues to find this ... maybe it is a good ideia do add a "How to integrate with hybrid app" on the docs! 👍

**Comment by ferologics** [comment]
@mariobento In my past week experience the majority of solutions were from, as you say searching on issues, and reading the source. The project is very fresh but slowly getting there.

**Comment by vinayakparmar92** [comment]
Tried adding `RCTLinkingIOS`  to podspec. Still getting the same error. Any solution for this issue?

**Comment by bithavoc** [comment]
@vinayakparmar92 my node.js was too old(4.x), upgraded to 7.x and started working.

**Comment by shrutic** [comment]
Adding RCTLinkingIOS to podspec causes the compilation of React native code to fail as I am using it inside an iMessage extension and using [RCTSharedApplication() openUrl: URL] fails with the error 

"..native/Libraries/LinkingIOS/RCTLinkingManager.m:74:41: 'openURL:' is unavailable: not available on iOS (App Extension)"

Anyone easy way to resolve this barring changing the react native code ?

**Comment by shrutic123** [comment]
https://github.com/facebook/react-native/pull/13881 is a PR that fixes this issue. Adding it here so that hopefully it might get some eyes so that it can be checked in. I have the fix out for over 10 days with signed off CI tests, but no one at react-native is looking into it. :(

**Comment by LouisJS** [comment]
I've tried to add React Navigation to my Hybrid RN/Swift Project.

Using:

    "react": "^15.4.1",
    "react-native": "0.42.x",
    "react-navigation": "^1.0.0-beta.13",
    "react-redux": "^5.0.6",
    "redux": "^3.7.2",
    "redux-form": "^6.8.0"

Thanks @ferologics 💯

**Comment by bill-mark** [comment]
i meet the same issue  when i tye use react-navigation in an existing app,please for help

**Comment by mailworks** [comment]
i meet the same issue too
