### ISSUE TITLE
Change Navigation Options Based on Screen Information

### ISSUE THREAD

**Issue by evancloutier** [react-community/react-navigation#466]
For one of the screens I'm designing, I'm using a [Swiper](https://github.com/leecade/react-native-swiper) component that renders an array of photos when the component mounts, so the user can swipe through the photos as they please. I'd like to display the name of the photo within the header I have, is it possible to dynamically update the `navigationOptions` within the `render()` function?

**Comment by grabbou** [comment]
See #313 and #413 and #145. If they don't have a solution that works for you, please let me know.
