### ISSUE TITLE
Deep linking path search incomplete

### ISSUE THREAD

**Issue by s-nel** [react-community/react-navigation#4682]
### Current Behavior

Currently when deep linking if there is a partial path match with one router, siblings of that router will not be checked (even if the partial match doesn't match fully)

In the following snippet, deep links to route `C` will not work because there is a partial match on `B` (even though `D` doesn't fully match the path) and `react-navigation` will not navigate anywhere.

```
const RootRouter = createSwitchNavigator({
  Index: {
    screen: () => <View><Text>Index</Text><NavigateToCButton title="Navigate to C"/></View>,
  },
  A: {
    screen: createStackNavigator({
      D: {
        screen: () => (<View><Text>Screen D</Text></View>),
        path: 'd',
      }
    }),
    path: null,
  },
  B: {
    screen: createStackNavigator({
      C: {
        screen: () => (<View><Text>Screen C</Text></View>),
        path: 'c'
      }
    }),
    path: null,
  }
})
```

The problematic code is in [pathUtils](https://github.com/react-navigation/react-navigation/blob/master/src/routers/pathUtils.js#L92):

```
for (const [routeName, path] of paths) {
      const { re, keys } = path;
      pathMatch = re.exec(pathToResolve);
      if (pathMatch && pathMatch.length) {
        pathMatchKeys = keys;
        matchedRouteName = routeName;
        break; // here we take the first partial match and we never search any siblings that are after this match. 
        // instead we should recurse into child routers and if null action, continue matching against sibling routes until `paths` is exhausted
      }
    }
```

### Expected Behavior

Deep links should recursively search all routes until a match is found or no match is present.

### How to reproduce

[This repository](https://github.com/s-nel/rn-nav-incomplete-path-search) reproduces the issue on Android

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.6.2
| react-native     | 0.55.4
| node             | 9.11.2
| npm or yarn      | yarn

**Comment by ericvicenti** [comment]
You're right that this behavior is currently buggy.

I have a pull request that basically rewrites the path handling logic, and includes tests similar to your example: https://github.com/react-navigation/react-navigation/pull/4671

Would you do me a favor and test the new code against your use cases? I'd like to make sure it works for you
