### ISSUE TITLE
Question: Problem with StackNavigator

### ISSUE THREAD

**Issue by Blackscr33n** [react-community/react-navigation#472]
Question:

Hello Community!

I hope my question isn't missplaced here!
I am new to RN and I am trying to implement react-navigation StackNavigator
I encountered this error:
![image](https://cloud.githubusercontent.com/assets/6410789/23302872/16f5fdb8-fa91-11e6-81e5-54827baa3059.png)

Maybe someone have a hint what I am doing wrong?
This is the code:

```
import React, { Component } from 'react';
import {
  AppRegistry,
  Text,
  View
} from 'react-native';
import StackNavigator from 'react-navigation';
import { Button } from 'react-native-elements'
import Drawer from 'react-native-drawer'
import Startpage from './src/container/startpage'
import Home from './src/container/home'

const Test = StackNavigator({
  Home: {screen: Home},
  Start: {screen: Startpage},
},{
  initialRouteName: 'Start',
  headerMode: 'none',
});

AppRegistry.registerComponent('Test', () => Test);
```

If you need more code, I can provide you the container Startpage & Home.

**Comment by satya164** [comment]
`import { StackNavigator } from 'react-navigation';`
