### ISSUE TITLE
How can I intercept any call to "navigate"?

### ISSUE THREAD

**Issue by ayalpani** [react-community/react-navigation#473]
Hi!

First of all, thanks for providing us with this great library! I am new to mobile development, just started to use react-native and it's less than a week with react-navigation, so I am quite unexperienced and possibly unable to see the obvious.

This little picture I have drawn to illustrate and discuss my problem:

![img_20170224_131640](https://cloud.githubusercontent.com/assets/603179/23303565/0e495c92-fa95-11e6-8a29-f451a9bf9809.jpg)

**The "Happy Case" is what I want to achieve:**
1. Tapping on a notification leads me to the "Contact Details"
2. Tapping on the back button leads me back to the "Notifications"
3. Tapping on the "Contact List" tab leads me to "Contact List"
4. Tapping on a contact leads me to "Contact Details"
5. Tapping the back button leads me back to the "Contact List"

**The "Sad Case" is what I am experiencing:**
1. Tapping on a notification leads me to the "Contact Details"
2. Tapping on the back button leads me back to the "Notifications"
3. Tapping on the "Contact List" tab leads me to the very same "Contact Details" I had opened before, **instead of the "Contact List"**

So to wrap things up, my App consists of 3 Tabs:

1. Notifications
2. Contact List
3. Settings

```
const MyTabNavigator = TabNavigator({
  Notifications: { screen: NotifcationsScreen, ... },
  Contacts: { screen: ContactsStack, ... },
  Settings: { screen: SettingsScreen, ... },
}, {
  initialRouteName: 'Notifications'
})

```
I have arranged my Contacts with a StackNavigator:

```
const ContacksStack = StackNavigator({
  ContactList: { screen: ContactListScreen, ... },
  ContactDetails: { screen: ContactDetailsScreen, ... },
}, {
  initialRouteName: 'ContactList'
})
```

**My Question is:** how would I achieve my goal to _always_ get back to the initial route of my stacked navigation, whenever I click the "Contact List" tab?

Or, asking more generally: how can I intercept _any_ call to "navigate" _wherever_ it is called, to react upon that? 

It would be great to have an API to handle events:

```
import { addEventListener, removeEventListener } from 'react-navigation'

addEventListener('navigate', (event) => {
  console.warn(event.route) // 'Contacts'
  console.warn(event.source) // 'TabNavigator'
  ...
})
```

Something like this (or better). You get my point?

But even if you are not considering this, what workarounds are possible top solve my problem? 
Thanks!

**Comment by skellock** [comment]
FTFY

![image](https://cloud.githubusercontent.com/assets/68273/23305325/36cc9194-fa6c-11e6-9263-553f0448c146.png)

**Comment by mmalfertheiner** [comment]
Hi, 
I have a similar issue. I have a list of users as my main screen, when I tab on a user, I open the detail screen of the user. If I make changes to the user and than hit the back button, the users list screen should get a notification that it has to update.

Is it possible to listen to the navigation action? 
Or is there another way to force the screen to render?
Thanks

**Comment by seenickcode** [comment]
Hey there @ayalpani , did you get a resolution to this yet?

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
