### ISSUE TITLE
Can you make the back button in the tab navigator go to the last tab?

### ISSUE THREAD

**Issue by KabirKang** [react-community/react-navigation#475]
By default, pressing back in the tab navigator will go to the initial route. How can you make it go to the last selected tab? The last state carries the correct index, but the behavior is wrong.

**Comment by grabbou** [comment]
You can set backBehavior of tab navigator to none. Check documentation for Tab Navigator ☺️

**Comment by KabirKang** [comment]
Hmm I tried that but it just made the app close when back was pressed. Is that intended? I was thinking if theres 3 tabs and you click on tab 1, then tab 2, then tab 3, pressing back should go to Tab 2

**Comment by satya164** [comment]
It's not possible right now. PR welcome.

**Comment by satya164** [comment]
Closing in favor of https://github.com/react-community/react-navigation/issues/678
