### ISSUE TITLE
[Feature] DrawerNavigator provide the whole item render via navigationOption

### ISSUE THREAD

**Issue by ggarek** [react-community/react-navigation#478]
While creating a custom `DrawerNavigatorItems`, i found that in some cases it would be more convenient to provide the whole item renderer through the screen navigation options, then providing icon+label separately. ~Currently~ In the upcoming release it will become possible to provide custom render for `label` property, but it means, that one needs to wrap the content in additional `View` if more than one component is required for the `label`.

Proposal:
- add `navigationOptions.item` renderer as mutual exclusive alternative for `{ icon: ..., label: ...}`

Rationale:
- Sometimes a drawer menu item is easier to treat as a single component, rather than an icon and a label;
- It will decrease the component nesting (no `View`-wrappers for icon and label);

Currently it is very tricky to achieve, because the `contentComponent` has no access to the route navigation config. *(It is hidden in `DrawerSidebar`)*

After issue #80 is fixed one could create custom `DrawerNavigatorItems` and reach the navigation config for the route and implement desired behaviour.

But if there were `item`-renderer alternative for `icon`+`label` in a route config, one would not need to make own `DrawerNavigatorItems`.

----
If you consider this reasonable i am ready to provide a PR. If not, feel free to close/decline the feature request.

Thank you! The project is a lifesaver!

**Comment by satya164** [comment]
Why can't you just omit `icon` and provide the `label` prop with what you want? How does `item` in your case behaves differently than `label` without an `icon`?

> Currently it is very tricky to achieve, because the contentComponent has no access to the route navigation config

I'd accept a PR passing the `router` to content component

**Comment by ggarek** [comment]
That's true. In the upcoming release it will become possible to use a `label` without an `icon` to render the whole item.

----

While submitting PR i first tried to pass the router down to the content component. But what we really want here, is to make the navigation options (aka route config) accessible in the content component. So one could implement own drawer navigation menu with custom options. 
To do it with the bare router one needs the access to `childNavigationProps`. May be the better idea would be to pass down `getScreenConfig` instead? We could even bound second argument to `'drawer'`, since it is the related config section, to make the API even stricter.

What do you think, @satya164? Does it make sense?

**Comment by satya164** [comment]
Commented on your other PR.

**Comment by ggarek** [comment]
The PR is merged. 

- If you need to provide the whole item renderer, just omit the `icon` property and pass the item renderer via `label`.

- If you want to implement custom drawer menu and use own screens configuration, use the `router` property of the content component to reach a screen config. *(To access child navigation props one can use `withCachedChildNavigation`, which probably will be exposed via react-navigator API)*
