### ISSUE TITLE
Right header button not showing up in a screen

### ISSUE THREAD

**Issue by mypark** [react-community/react-navigation#479]
I have an odd bug where the right button shows up on the header on the home screen but doesn't on another screen that I push in.

here's the root navigation

```

const RootTabNavigator = TabNavigator({
  Home: {
    screen: HomeScreen,
  },
  MyProfile: {
    screen: MyProfileScreen,
  },
}, {
  tabBarOptions: {
    activeTintColor: '#e91e63',
    showIcon: true,
  },
});

export default StackNavigator({
  Root: { screen: RootTabNavigator },
  Event: {
    screen: EventDetailScreen,
    navigationOptions: defaultNavigationOptions,
  },
  EditEvent: {
    screen: EditEventScreen,
    navigationOptions: {
      title: 'Host an Event',
      mode: 'modal',
      header: defaultNavigationOptions.header,
    },
  },
});

```

Here's the right button code

```
export default class EventDetailScreen extends Component {
  
  static navigationOptions = {
    title: 'Game Session',
    header: {
      right: <Button title="Info" />,
    },
  };
```

**Comment by KakarN** [comment]
I think you should put a return statement inside the right header.

**Comment by mypark** [comment]
Ok so it looks like my mistake was thinking that the static navigationOptions overrides the navigationOptions set in the navigator - seems it's the other way around.

**Comment by nonameolsson** [comment]
@mypark I just got to the same conclusion. Have you figured out a way to override it from the component?

**Comment by mypark** [comment]
@nonameolsson I couldn't override it - so I removed it from the stacknavigator and set it individually in all my components.

**Comment by AliYar-Khan** [comment]
> 
> 
> @nonameolsson I couldn't override it - so I removed it from the stacknavigator and set it individually in all my components.

If your component is also connected to redux store, then how can you add a button on the header ?
