### ISSUE TITLE
Animating the Header

### ISSUE THREAD

**Issue by ppiechota** [react-community/react-navigation#480]
Could you advise me how to animate the Header? I would like to hide it smoothly on scrolling down the ListView.

I could use style of Header property inside navigationOptions, but to animate a component with Animated it is additionally required to use for example <Animated.View>, so is there any way to use Animated with Header? Custom header returning <Animated.View>? Or is there a better approach?

**Comment by satya164** [comment]
`Header` is already an animated view https://github.com/react-community/react-navigation/blob/master/src/views/Header.js#L302

**Comment by Talor-A** [comment]
can the header's height be animated? I was able to statically set it but the content inside would still be cropped at the header's normal height. I'm looking for something like this: 

![image](https://cloud.githubusercontent.com/assets/11509865/23577360/f4c31f96-0071-11e7-8b36-5f23ea78fd77.png)

found in [this](https://medium.com/appandflow/react-native-scrollview-animated-header-10a18cb9469e#.w0hvyttae) tutorial

**Comment by michaelduminy** [comment]
+1

Still not sure how to do this with nested navigators.

**Comment by ppiechota** [comment]
@Talor-A 

I also checked that tutorial. Finally I  managed to get animated Header with  below approach.

I use this._animatedValue (which here is an object returned by Animated.Value) to set param of navigation screen so that it can be referenced by header function inside navigationOptions. This is done only once inside componentWillMount.

```
export default class Calendar extends Component {

    constructor(props) {
      super(props);
      
      this._animatedValue = new Animated.Value(0);
    }

    componentWillMount() {
      this.props.navigation.setParams({animatedValue: this._animatedValue.interpolate({
        inputRange: [0, 80],
        outputRange: [0, -80],
        extrapolate: 'clamp'
      })
    });
    }
```
Then it is used in header inside navigationOptions like so:
```
static navigationOptions = {
        title: moment().format('dd, Do of MMMM'),
        header: ({state}) => {
          return {
            style: {
              position: 'absolute',
              top: (!state.params ? 0 : state.params.animatedValue),
              left: 0,
              right: 0,
              overflow: 'hidden',
            }
          };
        }
```

So the above happens when Calendar component is mounted, it is done only once. As animatedValue param is an object it references this._animatedValue inside Calendar and any change will be reflected in our param.

Scrolling down will change value of this._animatedValue and consequently animatedValue param.

```
          <ScrollView
            onScroll={ Animated.event([{nativeEvent: {contentOffset: {y: this._animatedValue}}}]) }
            scrollEventThrottle={16}
          >
```

Before this I tried to setParams on every scroll but it was too laggy, so above approach was much better but I don't know if it is 'React' way of doing things, so I'm open for discussion.

**Comment by Talor-A** [comment]
@ppiechota thanks for the help! I adapted your example to make the header expand and collapse rather than show/hide with this code:

```
componentWillMount() {
    const HEADER_MAX_HEIGHT = 200
    const HEADER_MIN_HEIGHT = 60
    const HEADER_SCROLL_DISTANCE = HEADER_MAX_HEIGHT - HEADER_MIN_HEIGHT

    this.props.navigation.setParams({animatedValue: this._animatedValue.interpolate({
      inputRange: [0, HEADER_SCROLL_DISTANCE],
      outputRange: [HEADER_MAX_HEIGHT, HEADER_MIN_HEIGHT],
      extrapolate: 'clamp'
    })
    });
  }
``` 
and then animating `height` rather than `top`. However, I still have the issue that the `Title` Component gets cropped at the normal navbar height, seen here:
![image](https://cloud.githubusercontent.com/assets/11509865/23628980/076a3bc0-026b-11e7-8ca2-f3b34eca1c69.png)

the white area is the header in its expanded state, and the image inside should be square but it is still cropped at the standard title height. is there any way to fix this?

**Comment by michaelduminy** [comment]
New tutorial out, trying to figure out how to adapt it to this library.

https://medium.com/appandflow/react-native-collapsible-navbar-e51a049b560a

**Comment by Talor-A** [comment]
@michaelduminy awesome! any chance we could see the expanding header adapted to this library as well? I can share with you the code I have so far if it helps

**Comment by michaelduminy** [comment]
@Talor-A yeah please share away :)

**Comment by vitorebatista** [comment]
I'd like to know how to animate the header too... 😕

**Comment by Talor-A** [comment]
@michaelduminy this is what I've got. I've only tested on android, but whatever you put as the value for `title: ` is cut off 50px or so from the top of the screen. 

```
...

export default class Home extends Component {
  constructor(props) {
    super(props);

    this._animatedValue = new Animated.Value(0);
  }
  static navigationOptions = {
    header: ({state}) => {
      return {
        title:<HeaderComponent />,
        style: {
          position: 'absolute',
          top: 0,
          left: 0,
          right: 0,
          height:(!state.params ? 0 : state.params.animatedValue),
          overflow: 'hidden',
        },
        titleStyle:{
          flex:1,
          height:(!state.params ? 0 : state.params.animatedValue),
        }
      }
    }
  }

  componentWillMount() {
    const HEADER_MAX_HEIGHT = 200
    const HEADER_MIN_HEIGHT = 60
    const HEADER_SCROLL_DISTANCE = HEADER_MAX_HEIGHT - HEADER_MIN_HEIGHT

    this.props.navigation.setParams({animatedValue: this._animatedValue.interpolate({
      inputRange: [0, HEADER_SCROLL_DISTANCE],
      outputRange: [HEADER_MAX_HEIGHT, HEADER_MIN_HEIGHT],
      extrapolate: 'clamp'
    })
    });
  }
  render() {
    return (
      <ScrollView
        onScroll={ Animated.event([{nativeEvent: {contentOffset: {y: this._animatedValue}}}]) }
        scrollEventThrottle={16}>
        ...
      </ScrollView>
    )
  }
}
```

**Comment by Gvade** [comment]
Thank you guys for the nice solutions. 
In my case the screen, on which I need to animate a header, is a tab, wrapped by StackNavigator.
As you probably know, TabNavigator screens do not have their own headers, instead parent screen header is shown. How can I call setParams of a parent StackNavigator screen inside a Tab? I want to change height of a header, but the tabbar should remain.

`this.props.navigation.setParams` will change the route param of a current Tab, which doesn't have it's own  header

![animated header mockup](https://cloud.githubusercontent.com/assets/23520539/24209019/61958c5a-0f25-11e7-9e91-34808813bc85.jpg)

**Comment by vedatyilmaz** [comment]
@Gvade i'm trying to animate a header like yours. My TabNavigator inside the StackNavigator. Tab bar still remains top of the screen but on IOS there is blank space (20) above it. On android working expected but laggy.

If i change `top: 0` to `marginTop: -20` looks good on IOS. This time i have a problem with Android. :) 

if i solve the lag issue, it's fine for me.

```
export default class MyTabView extends Component {
  constructor(props) {
    super(props);

    this._animatedValue = new Animated.Value(0);
  }
  static navigationOptions = {
    header: ({state}) => {
      return {
        title: 'My Title',
        style: {
          top: 0,
          left: 0,
          right: 0,
          height:(!state.params ? 0 : state.params.animatedValue),
          overflow: 'hidden',
        },
      }
    }
  }
  componentWillMount() {
    const HEADER_MAX_HEIGHT = 60
    const HEADER_MIN_HEIGHT = 0
    const HEADER_SCROLL_DISTANCE = HEADER_MAX_HEIGHT - HEADER_MIN_HEIGHT

    this.props.navigation.setParams({animatedValue: this._animatedValue.interpolate({
      inputRange: [0, HEADER_SCROLL_DISTANCE],
      outputRange: [HEADER_MAX_HEIGHT, HEADER_MIN_HEIGHT],
      extrapolate: 'clamp'
    })
    });
  }
  render() {
    return (
      <ScrollView
        onScroll={ Animated.event([{nativeEvent: {contentOffset: {y: this._animatedValue}}}]) }
        scrollEventThrottle={16}>
        ...
      </ScrollView>
    )
  }
}
```

**Comment by Talor-A** [comment]
@vedatyilmaz try this: `marginTop: Platform.OS === 'ios' ? -20 : 0`. you will also need to import `Platform` from `react-native`.

**Comment by kevinold** [comment]
Thanks for all who left examples here!  I have this working for my header.

I'd also like to do this for Tabs via tabBarOptions?

I've tried this code but no luck.

```
static tabBarOptions = ({ state }) => ({
      style: {
        position: 'absolute',
        top: Platform.OS === 'ios' ? -20 : 0,
        left: 0,
        right: 0,
        height:(!state.params ? 0 : state.params.animatedValue),
        overflow: 'hidden',
        marginTop: Platform.OS === 'ios' ? -20 : 0
      },
      labelStyle: {
        flex:1,
        height:(!state.params ? 0 : state.params.animatedValue),
      }
    });
```

**Comment by roselind** [comment]
https://camo.githubusercontent.com/906acaa2a596e1d92cbea72f109ec45e32a90cdd/68747470733a2f2f63646e2d696d616765732d312e6d656469756d2e636f6d2f6d61782f3830302f312a50786f4572325a3435487979466c5a484871627138772e676966 
 How to achieve this animation effect！

**Comment by jsplaine** [comment]
@ppiechota

re:

```
static navigationOptions = {
        title: moment().format('dd, Do of MMMM'),
        header: ({state}) => {
          return {
            style: {
....
```

navigationOptions' header param needs to be a Component.  Is this still working for you?  What version of react-navigation are you using?

Here's the error when I use the above header value:

> Objects are not valid as a React child (found: object with keys {style}). If you meant to render a collection of children, use an array instead.

**Comment by fabriziogiordano** [comment]
Does someone has an example in expo to solve the Header animation on card scroll?
I tried the suggestions here and I get `params` undefined. 

Thanks

**Comment by kidequinox** [comment]
@kevinold , @fabriziogiordano, they will be undefined at first until you start scrolling and emitting events from `this._animatedValue`. You may need to build the logic to detect params.

In our case, we used a custom header component and declared settings and handled interpolation in the render method of it instead of in the scrollView component. Our header needs to be universally accessible and interactive with components. works great on android, no jitter, and universal. I noticed depending on your method of where you interpolate and how you store it could cause jitter of different magnitudes.


```
// TabBarCustomComponent.js
export class TabBarCustomComponent extends Component {
  render() {
    const {
     navigation: { state }
    } = this.props;

    let theValue = 0;
    let position = {};
    let theParams = this.props.navigation.state.routes[state.index].params || 0;

    if(theParams){
      if(theParams.animatedValue){
        theValue = theParams.animatedValue;
        let positionStyle = Animated.diffClamp(theValue, 0,80).interpolate({
        inputRange: [0, 1],
        outputRange: [0, -1],
        })
        position = {transform: [{translateY: positionStyle}]};
      }
    }
    
    return( <View style={[position, height: 80, etc..]}> content </View> );
  }
};
```
The DiffClamp combined with interpolate, handles resetting the scroll to 0 so when ever you scroll up, the header interpolation is triggered.

```
// ScrollViewComponent.js

export class ScrollViewComponent extends Component{
  constructor(props){
    super(props);
    this.state = {
      _animatedValue: new Animated.Value(0)
    };
  }
  componentWillMount(){
    this.props.navigation.setParams({animatedValue: this.state._animatedValue});
  }
  render(){
    return(
      <ScrollView
        style={styles.container}
        onScroll={ Animated.event(
          [{nativeEvent: {contentOffset: {y: this.state._animatedValue}}}],
          { useNativeDriver: false }
        )}
        scrollEventThrottle={16}
        overScrollMode="never"
        >
        
        ... content
      
      </ScrollView>
    );
  }
};
```

**Comment by JulianKingman** [comment]
@kidequinox how do you handle bounce? For example, if you scroll fast and bounce against the edge, I get weird behaviors.

**Comment by JulianKingman** [comment]
Nevermind, I figured it out. To fix bounciness, add an interpolator to  `_animatedValue` (full post with code here: https://medium.com/appandflow/react-native-collapsible-navbar-e51a049b560a)

**Comment by alpamys-qanybet** [comment]
@vedatyilmaz, can you please share working example, I am new to RN and cannot reproduce.

**Comment by alexstoyanov** [comment]
@JulianKingman Could you please post code how you fix the bounciness?

**Comment by JulianKingman** [comment]
@alexstoyanov read the article I referenced, quote:

> clampedScroll, this is the value used to animate the navbar. We also save it in the state to avoid recreating it on each render. It is created by adding together scrollAnim and offsetAnim and then using Animated.diffClamp. I’ll explain what diffClamp does in details in the next section. **It also does an interpolation on scrollAnim to avoid issues with the bounce effect on iOS**.

**Comment by rishi-hasher** [comment]
@vedatyilmaz were you able to solve the lag issue in android?I have implemented it exactly according to yours last post and is working fine on ios but lags on android.
Do let me know if there is a work around to it.

**Comment by giantss** [comment]
![image](https://user-images.githubusercontent.com/13778798/35373177-5c91fda0-01d8-11e8-82f4-a49580a968da.png)
help me.
@Talor-A @ppiechota

**Comment by giantss** [comment]
![image](https://user-images.githubusercontent.com/13778798/35421116-4c82a622-027c-11e8-9fa7-24513edba8aa.png)
In accordance with the code you are given the wrong report.
@ppiechota

**Comment by raphaelrk** [comment]
Got this working with a map + tabview underneath it with the following code, based on the aforementioned [Medium article](https://medium.com/appandflow/react-native-scrollview-animated-header-10a18cb9469e). Hopefully nothing was lost in translation as I stripped it down.

```jasvascript
class MapScreen extends Component {
  constructor(props) {
    super(props);
    this.state = {
      scrollY: new Animated.Value(0),
    }
  }

  render() {
    const MAP_MAX_HEIGHT = 300;
    const MAP_MIN_HEIGHT = 0;
    const MAP_SCROLL_DISTANCE = MAP_MAX_HEIGHT - MAP_MIN_HEIGHT;

    const mapHeight = this.state.scrollY.interpolate({
      inputRange: [0, MAP_SCROLL_DISTANCE],
      outputRange: [MAP_MAX_HEIGHT, MAP_MIN_HEIGHT],
      extrapolate: 'clamp',
    });

    return (
      <View style={{ flex: 1 }}>
        <Animated.View style={{height: mapHeight}}>
          <MapView> /*...*/ </MapView>
        </Animated.View>
        <View style={{flex: 1}}>
          <MapTabNavigator screenProps={{scrollY:this.state.scrollY}} />
        </View>
      </View>
    );
  }
}
```

```
const MapTabNavigator = TabNavigator({
  TabOne: {
    screen: MapStuffList
  }
}, {
  tabBarComponent: TabBarTop,
  tabBarPosition: 'top',
});
```

```
class MapStuffList extends Component {
  static navigationOptions = {
    title: 'Map Stuff',
  };

  render() {

    // let data = ...

    return (
      <View style={{ flex: 1 }}>
        <FlatList
          data={data}
          keyExtractor={item => item.id}
          scrollEventThrottle={12}
          onScroll={Animated.event(
            [{nativeEvent: {contentOffset: {y: this.props.screenProps.scrollY}}}]
          )}
          renderItem={({ item }) => {
            ...
          }}
        />
      </View>
    );
  }
}
```

**Comment by raphaelrk** [comment]
Update: improved on above by using the nativeDriver

```javascript
const { height } = Dimensions.get('window');

class MapScreen extends Component {
  constructor(props) {
    super(props);
    this.state = {
      scrollY: new Animated.Value(0),
    }
  }

  render() {
    const MAP_MAX_HEIGHT = height*0.6;
    const MAP_MIN_HEIGHT = 0;
    const MAP_SCROLL_DISTANCE = MAP_MAX_HEIGHT - MAP_MIN_HEIGHT;

    const mapY = this.state.scrollY.interpolate({
      inputRange: [0, MAP_SCROLL_DISTANCE],
      outputRange: [-MAP_MIN_HEIGHT, -MAP_MAX_HEIGHT],
      extrapolate: 'clamp',
    });

    return (
      <View style={{ flex: 1 }}>

        <Animated.View style={{
          height: MAP_MAX_HEIGHT,
          transform: [
            {translateY: mapY},
            {perspective: 1000}, // needed for Android
          ],
        }}>
          <MapView> /*...*/ </MapView>
        </Animated.View>
        <Animated.View style={{
          // flex: 1,
          height: height,
          minHeight: height,
          transform: [
            {translateY: mapY},
            {perspective: 1000}, 
          ],
        }}>
          <MapTabNavigator screenProps={{scrollY:this.state.scrollY}} />
        </Animated.View>
      </View>
    );
  }
}
```

```javascript
const MapTabNavigator = TabNavigator({
  TabOne: {
    screen: MapStuffList
  },
  TabTwo: {
    screen: MapStuffList
  }
}, {
  tabBarComponent: TabBarTop,
  tabBarPosition: 'top',
});
```

```javascript
const { height } = Dimensions.get('window');

class MapStuffList extends Component {
  static navigationOptions = {
    title: 'Map Stuff',
  };

  render() {

    // let data = ...

    return (
      <View style={{ flex: 1 }}>
        <FlatList
          data={data}
          keyExtractor={item => item.id}
          scrollEventThrottle={1}
          onScroll={Animated.event(
            [{nativeEvent: {contentOffset: {y: this.props.screenProps.scrollY}}}],
            { useNativeDriver: true }
          )}
          style={{ height: height }}
          renderItem={({ item }) => {
            ...
          }}
        />
      </View>
    );
  }
}
```

Wondering if there's a way I can drag the TabBar header to scroll up and down, not just the FlatList

**Comment by benevbright** [comment]
Hi, everyone. I have a question.
If we achieve this feature and make PR for `react-navigation`, we have to able to get `onScroll` event from user's ScrollView(or FlatList) of his screen.
In the React technology, how can this be possible? I mean, accessing the user's ScrollView. I'm curious.

If it's not possible in React.
Perhaps, is it the only way that we provide the new component overriding ScrollView or FlatList like or HOC method?

**Comment by noambonnie** [comment]
The Header is a two part affair: I have a component called `AnimatedHeader` - it is an animated view. I then use this Animated View to create the actual content of the header.

I don't use headerTransparent: true. Instead I replace the entire header object.

Here's the code for the animated header:
```
import React from 'react';
import {
    Animated,
    Platform,
    View,
    StyleSheet,
} from 'react-native';

import { HEADER_HEIGHT, STATUS_BAR_HEIGHT } from './constants';
import StyleConstants from '../styles/constants';

export const headerAnim = new Animated.Value(0);

let headerVisible = true;

export const setHeaderVisible = (visible) => {
    if (visible === headerVisible)
        return;

    headerVisible = visible;
    Animated.timing(headerAnim).stop();
    Animated.timing(headerAnim, {
        toValue: HEADER_HEIGHT * (visible ? -1 : 1),
        duration: 300,
        useNativeDriver: true,
    }, ).start();
};

export const navbarTranslate = headerAnim.interpolate({
    inputRange: [0, HEADER_HEIGHT],
    outputRange: [0, -HEADER_HEIGHT - Platform.select({ ios: STATUS_BAR_HEIGHT, android: 0 })],
    extrapolate: 'clamp',
});

export class AnimatedHeader extends React.Component {
    constructor(props) {
        super(props);
    }

    render() {
        return (
            <Animated.View style={headerStyleSheet.headerContainer}>
                { Platform.OS === 'ios' && (<View style={headerStyleSheet.statusBarFiller} />) }
                {this.props.children}
            </Animated.View>

        )
    }
}

const headerStyleSheet = StyleSheet.create({
    headerContainer: {
        backgroundColor: StyleConstants.BACKGROUND_COLOR,
        height: HEADER_HEIGHT + (Platform.OS === 'ios' ? STATUS_BAR_HEIGHT : 0),
        flex: 1,
        position: "absolute", left: 0, right: 0, top: 0,
        transform: [{
            translateY: navbarTranslate,
        }],
        borderBottomWidth: Platform.OS === "ios" ? 1 : 0,
        borderBottomColor: "lightgrey",
    },
    statusBarFiller: { 
        width: "100%", 
        minHeight: STATUS_BAR_HEIGHT, 
    }
})
```

Then, to create a header that looks like the default OS header I have this:
```
import React from 'react';
import {
    Platform,
    View,
    Text,
    StyleSheet,
} from 'react-native';
import { AnimatedHeader } from '../common/headerAnimator';
import DrawerButton from './DrawerButton';
import { navigationStylesheet } from '../styles/constants'

export default class AnimatedHeaderDefault extends React.Component {

    constructor(props) {
        super(props);
    }

    render() {
        return (
            <AnimatedHeader>
                {Platform.select(
                    {
                        // On iOS, I want the header centered. Since I use absolute positioning for that, I need
                        // to render the drawer button after the label. There's probably a cleaner way to do it
                        // but sticking with this for now as I'm too tired to figure it out.
                        "ios": (
                            <View style={headerStylesheet.headerContainer}>
                                <DrawerButton />
                                <View style={headerStylesheet.iosLabelContainer}>
                                    <Text style={navigationStylesheet.headerText}>{this.props.label}</Text>
                                </View>
                            </View>
                        ),
                        "android": (
                            <View style={headerStylesheet.headerContainer}>
                                <DrawerButton />
                                <Text style={navigationStylesheet.headerText}>{this.props.label}</Text>
                            </View>
                        )
                    }

                )}
            </AnimatedHeader>
        )
    }
}

const headerStylesheet = StyleSheet.create({
    headerContainer: {
        flex: 1,
        flexDirection: 'row',
        alignItems: "center"
    },
    iosLabelContainer: {
        position: "absolute",
        width: "100%",
        alignItems: "center",
        justifyContent: "center"
    },

})
```

Then I use the header like this:
```
TabNavigator.navigationOptions = ({ navigation }) => {
    const { routeName } = navigation.state.routes[navigation.state.index];
    return {
        header: (<AnimatedHeaderDefault label={Strings.t('notifications.notifcationsScreenHeader')}    />)
    }
}
```

It's not the prettiest code and can probably be improved but this works for me.

**Comment by benevbright** [comment]
Oh, wow good to see your code. Thanks very much. 
I'll share my code when it's done. I'm doing a similar thing but I'm using `react-navigation`'s header.
Thanks again! @noambonnie

**Comment by benevbright** [comment]
![demo](https://user-images.githubusercontent.com/916690/44006562-d9b23174-9e86-11e8-9c02-fa7bceade736.gif)

I just made and published `react-navigation-collapsible` module. It’s HOC component, so you can make your current `react-navigation` collapsible by adding only a few lines. 
https://medium.com/@brightlee/introducing-react-navigation-collapsible-3ff80ac097a

**Comment by Marius2m** [comment]
@benevbright ,
That's really great!
Are we limited to FlatList or can we use SectionList too (and others)?

**Comment by benevbright** [comment]
Thanks! @Marius2m 
You can also use ScrollView and maybe SectionList too. (I will try it).
It's basically same as far as I know.

**Comment by mopilo** [comment]
@benevbright how do i install the module (react-native-collapsible)??

**Comment by zigang93** [comment]
Btw, did anyone try to animate the `headerTransparent` when is set from `true` to `false`?

**Comment by mohsen0311** [comment]
i tried Costume Tabbar option , not the styling it, but when i use state to pass to costume components its undifinded . is anybody know where i should pass my variable to be accessible with my costume component?

**Comment by sorxrob** [comment]
> Btw, did anyone try to animate the `headerTransparent` when is set from `true` to `false`? 

Hi, any update?

**Comment by fukemy** [comment]
I want to animate the navigationbar not animate the fake view as header
