### ISSUE TITLE
How to catch navigating to initial tab action on TabNavigator?

### ISSUE THREAD

**Issue by originerd** [react-community/react-navigation#481]
I'm trying to draw tabs. I want to catch navigating to initial tab action on TabNavigator. navigate function works when I tap tabs except initial tab. Then, how could I know that current tab is initial tab?

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
