### ISSUE TITLE
gesturesEnabled doesn't work for Android 

### ISSUE THREAD

**Issue by joeyzhao0113** [react-community/react-navigation#484]
I use below configuration to enable gestures but it has no effect on Android device.  

> static navigationOptions = {
>     title: 'Notification',
>     cardStack: {
>       gesturesEnabled: true
>     }
>   }

**Comment by rmevans9** [comment]
Are you using the NPM version @joeyzhao0113? If so NPM (as of 2 days ago) didn't have a version with that feature. It looks like a new version is getting released to NPM today which should include this ability.

**Comment by cooltoo** [comment]
Yes I am using NPM and the dependency version on `react-navigation` is as below:

> "react-navigation": "^1.0.0-beta.5"

what is the correct version I should use?

**Comment by joeyzhao0113** [comment]
Yes I am using NPM and the dependency version on `react-navigation` is as below:

> "react-navigation": "^1.0.0-beta.5"

what is the correct version I should use?

**Comment by rmevans9** [comment]
1.0.0-beta.6 should have it when it hits npm (which it might already be there, if not should be soon)
