### ISSUE TITLE
cannot read property routes of undefined - navigation state seems to be getting lost 

### ISSUE THREAD

**Issue by chadi-kazan** [react-community/react-navigation#485]
using drawer navigation with redux integration, the state is for some reason not getting properly passed down to my components - if i properly understand the error. the following is the navigation object i get when _updateNavigationProps is called in withCachedChildNavigation
```javascript
{
    dispatch:(action)
    goBack:goBack(key)
    navigate:navigate( routeName, params, action)
    setParams:setParams(params)
    state:undefined
```

i did my best to follow the ReduxExample app
here are my navigator
```javascript
    const AppNavigator = DrawerNavigator({
        home: {
            screen: Home
        },
        settings: {
            screen: Settings
        },
        login: {
            screen: LoginScreen
        }
    }
```
my navigation reducer

```javascript
const INITIAL_STATE = {
	index: 1,
    routes: [
        { key: 'InitA', routeName: 'home' },
        { key: 'InitB', routeName: 'settings' },
        { key: 'InitC', routeName: 'login' }
    ]
};
export default function navigation(state = INITIAL_STATE, action) {
    switch (action.type) {
            case 'login':
                return AppNavigator.router.getStateForAction(NavigationActions.back(), state);
            case 'home':
            case 'settings':
                return AppNavigator.router.getStateForAction(action, state);
        }
    return state;
}
```

and my app container

```javascript
@connect(state => ({nav: state.navigation, navigation: state.navigation, data: state.data}))
export default class AppContainer extends Component {
	render(): ReactElement {
		const { dispatch, nav } = this.props;
		const navigation = addNavigationHelpers({dispatch, state: nav});
		return <AppNavigator navigation={navigation} />;
	}
}
```

the render function of AppContainer never gets called by the way, the error occurs before.
sorry to post here, but i am unable to find any other forums to get help on this

**Comment by grabbou** [comment]
Please publish entire example. The code looks good at first sight, might be easier to check when we have a runnable code.

If you know `exponent`, try posting it there.

**Comment by chadi-kazan** [comment]
[here](https://github.com/chadi-kazan/bookmarker)'s the github repo for the example

**Comment by stief510** [comment]
I am having a similar problem #427

**Comment by chadi-kazan** [comment]
ok so i replaced DrawerNavigator with TabNavigator, using the exact same routes, reducers and so on, i didn't change anything else in my routing/redux configuration and TanNavigator works!
I updated the example i put on [here](https://github.com/chadi-kazan/bookmarker), if you want to reproduce the bug, simply replace TabNavigator with AppNavigator in src/App.js

```javascript
import { connect } from 'react-redux';
import {AppNavigator, TabNavigator} from '../navigator';
import { addNavigationHelpers } from 'react-navigation';
import React, { Component } from 'react';

@connect(state => ({nav: state.navigation, navigation: state.navigation, data: state.data}))
export default class AppContainer extends Component {
	render(): ReactElement {
		const { dispatch, nav } = this.props;
		const navigation = addNavigationHelpers({dispatch, state: nav});
		// using AppNavigator instead of TabNavigator in the line below will make it pop
		return <AppNavigator navigation={navigation} />;
	}
}
```

**Comment by srounce** [comment]
I had tried similarly to @chadi-kazan, using a reducer that was set up for a StackRouter. I don't think this is a bug, the relationship between the reducer state's index and routes in the various routers is are totally different (albeit with a similar shaped object). From a bit of playing around I've come my current understanding (please correct me if I'm wrong) that the TabRouter's state has all available routes in the routes array using the index to point at the current one, whereas the StackRouter is exactly as it's name describes: a stack, on which routes are pushed onto and can be traversed (forward/backward) by changing the index (as well as pushing/popping).

**Comment by chadi-kazan** [comment]
@srounce I didn't try with StackNavigator. But i guess DrawerNavigator functions more or less the same way TabNavigator does, in that it knows before hand all the possible routes and it can point to the current one with index. I am curious to know how you solved your problem with StackNavigator though, did you set your initial state using something like  
```javascript
router.getStateForAction(router.getActionForPathAndParams(path))
```
Anyway the problem with DrawerNavigator seems different to me

**Comment by srounce** [comment]
@chadi-kazan You got it dude! That's exactly how the store state is initialised. I've found this is pretty safe for initialising the store state for all routers (that I have tried).

**Comment by chadi-kazan** [comment]
ok, i tried setting my initial state to 
```javascript
router.getStateForAction(router.getActionForPathAndParams('home'))
```
but i still got the same error. the initial state you get from this looks like the following
```javascript
{
 index: 0
 routes: [
	  {
	   index: 0
	   key: "DrawerClose"
	   routeName: "DrawerClose"
	   routes: [
	   	    {
	   	     key: "home"
	   	     routeName: "home"
	   	    },
	   	    {
	   	     key: "settings"
	   	     routeName: "settings"
	   	    },
	   	    {
	   	     key: "login"
	   	     routeName: "login"
	   	    }
	   	   ]
	  },
	  {
	   key: "DrawerOpen"
	   routeName: "DrawerOpen"
	  }
	 ]
}
```
and this is what i have declared in my navigator route configuration
```javascript
export const AppNavigator = DrawerNavigator({
  home: {
    screen: Home
  },
  settings: {
    screen: Settings
  },
  login: {
    screen: LoginScreen
  }
}
```
what am i missing?

**Comment by chadi-kazan** [comment]
do i have to declare DrawerOpen and DrawerClose in my navigator's route config?!

**Comment by wangzhe890703** [comment]
a naive question: what is addNavigationHelpers for? I can still integrate navigation state to redux without addNavigationHelpers.

**Comment by grabbou** [comment]
@wangzhe890703 as it name implies, it adds navigation helpers https://github.com/react-community/react-navigation/blob/master/src/addNavigationHelpers.js

**Comment by cooperka** [comment]
It's been quite a while, any updates on this? I can repro the issue using the ReduxExample app on latest master; see the diff here for repro: https://github.com/cribspot/react-navigation/commit/3243501f6b78ea3c49d52e273773911cb93d3469.

**Comment by chadi-kazan** [comment]
I didn't have time to sit down look into it and try and solve it myself yet. it's good you managed to reproduce

**Comment by cooperka** [comment]
@grabbou I added a bit more info to my comment above. It's very simple to repro using the example app. Do you have any insights here?

**Comment by chadi-kazan** [comment]
ok i am not sure i am following here. is there a bug? or is the example's code wrong?

**Comment by cooperka** [comment]
@chadi-kazan it seems to be a bug: `DrawerNavigator` doesn't work at all with redux (i.e. when using the `navigation` prop).

**Comment by hjh5696** [comment]
any idea about this now? I am getting troubled exactly on this.
Using DrawerNavigator as a root navigator while integrating redux makes 'undefined' of undefined error like @cooperka mentioned above

**Comment by cooperka** [comment]
@grabbou or @ericvicenti this seems like a serious bug, can someone please at least comment on whether it's planned to be fixed? We feel ignored 😿. Redux is a very common paradigm and it simply breaks react-navigation when using a DrawerNavigator.

For this reason, I'm stuck using the deprecated ex-navigation until react-navigation works with redux.

I've looked into it and I'd be happy to make a PR, but it doesn't seem very straightforward. All my debug info is [above](https://github.com/react-community/react-navigation/issues/485#issuecomment-291381623). Thanks for any direction you can provide.

**Comment by lorenzsell** [comment]
any updates on this?  I'm having this problem as well and it seems like a major issue.

**Comment by cooperka** [comment]
Update: In my example above, it turns out the initial redux state was invalid. I simply tweaked the StackNav state, but actually, DrawerNav has a very different format (the main routes should be nested under a `DrawerClose` route).

We can generate an initial programmatically like this:

```js
const initialNavState = AppNavigator.router.getStateForAction(AppNavigator.router.getActionForPathAndParams('Login'));
```

Doing so gets us further than before, but now as soon as I open the drawer I get `Cannot read property 'index' of null` in `DrawerView.componentWillReceiveProps`.

Repro diff: https://github.com/cribspot/react-navigation/commit/d63a6d5c21e7a0a0879bf87e4dd32bee220aa763

**Comment by grabbou** [comment]
Can this issue be closed now @cooperka? Have you managed to properly get `Drawer` working?

**Comment by cooperka** [comment]
@chadi-kazan the [redux docs](https://reactnavigation.org/docs/guides/redux) have been updated; please try again with my [solution above](https://github.com/react-community/react-navigation/issues/485#issuecomment-296398323). I've implemented it on a medium-large production app (stack + drawer + tabs + redux) and it seems to be working quite well now.

I think this can be closed -- but feel free to continue discussing here if you still have issues and maybe we can improve the docs even more.

cc @hjh5696, @lorenzsell, @ground5hark, @junshengpierre, @bernatfortet (those who originally +1'd my incorrect comment earlier, there is now a good solution).

**Comment by chadi-kazan** [comment]
thanks @cooperka . is there a full example with drawer navigator and redux we can look at?

**Comment by cooperka** [comment]
@chadi-kazan you can try it on the ReduxExample app: https://github.com/react-community/react-navigation/tree/master/examples/ReduxExample

Simply replace `StackNavigator` with `DrawerNavigator` in [AppNavigator.js](https://github.com/react-community/react-navigation/blob/master/examples/ReduxExample/src/navigators/AppNavigator.js) and it should work.

**Comment by lucalaissue** [comment]
**I have the issue "cannot get property undefined of undefined" on first line ("Main" exist)**

```js
const initialState = AppNavigation.router.getStateForAction(AppNavigation.router.getActionForPathAndParams("Main"));

let store = createStore((state = initialState, action) => {
    let newState = AppNavigation.router.getStateForAction(state, action);

    return newState || state;
});

const AppWithState = connect((state) => ({...state}))(class App extends Component {
    public constructor(props) {
        super(props);
    }

    public render() {
        return (
            <AppNavigation navigation={addNavigationHelpers({
                dispatch: this.props.dispatch,
                state: this.props.nav
            })}/>
        );
    }
});

export default class Root extends Component {
    public constructor(props) {
        super(props);
    }

    public render() {
        return (
            <Provider store={store}>
                <AppWithState/>
            </Provider>
        );
    }
}

```

**Comment by cooperka** [comment]
Hi @lucalaissue, we're currently working on [better documentation](https://github.com/react-community/react-navigation/pull/1311) for this. Can you try using this instead:

```js
cost initialState = AppNavigation.router.getStateForAction(NavigationActions.navigate({ routeName: "Main" }));
```

**Comment by lucalaissue** [comment]
```js
let initialState = AppNavigation.router.getStateForAction(NavigationActions.navigate({routeName: "Main"}));

let store = createStore(combineReducers({nav: (state = initialState, action) => {
    let newState = AppNavigation.router.getStateForAction(action, state);

    return newState || state;
}}));

let AppWithNavigationState = connect((state) => ({nav: state.nav}))(class App extends Component {
    public constructor(props) {
        super(props);
    }

    public render() {
        return (
            <AppNavigation navigation={addNavigationHelpers({
                dispatch: this.props.dispatch,
                nav: this.props.nav
            })}/>
        );
    }
});

export default class Root extends Component {
    public constructor(props) {
        super(props);
    }

    public render() {
        return (
            <Provider store={store}>
                <AppWithNavigationState />
            </Provider>
        );
    }
}

```

Now it's : **"Cannot read property index of undefined"**

**Comment by TsuryKnox** [comment]
I having the same issue when trying to nest a `StackNavigator` inside of a `DrawerNavigator` using Redux.

I have a `StackNavigator` app working great with Redux built according to your examples, but as soon as I add the `DrawerNavigator` I am getting the `cannot read property routes of undefined` error.

Do I need to declare the initial state differently since I am nesting a `StackNavigator` inside of a `DrawerNavigator`?

Here are my drawers and reducer:

```
export const AppNavigator = StackNavigator({
  Users: {
    screen: UsersContainer
  },
  Login: {
    screen: LoginContainer
  }
});

const MyDrawerNavigator = DrawerNavigator({
  Mainscreen: {
    screen: AppNavigator
  }
});

const initialNavState = AppNavigator.router.getStateForAction(NavigationActions.navigate({ routeName: 'Login' }));

function nav(state = initialNavState, action) {
  let nextState = AppNavigator.router.getStateForAction(action, state);

  return nextState || state;
}
```

**Comment by eduardoleal** [comment]
I'm having trouble to connect redux on an app that has nested navigators. 
When I try to add a TabNavigator inside a StackNavigator connected to redux the app crashes and give the following error:

```
undefined is not an object (evaluating 'state.routes[state.index]')
```

RootNavigator.js:
```javascript
import React from 'react';
import PropTypes from 'prop-types';
import { connect } from 'react-redux';
import { addNavigationHelpers, StackNavigator } from 'react-navigation';
import CardStackStyleInterpolator from 'react-navigation/src/views/CardStackStyleInterpolator';
import Splash from '$screens/Splash';
import LoginNavigator from './LoginNavigator';

export const RootNavigator = StackNavigator({
  Login: {
    screen: LoginNavigator,
    path: 'login',
  },
  Splash: {
    screen: Splash,
    path: 'splash',
  },
}, {
  headerMode: 'none',
  navigationOptions: {
    headerVisible: false,
    gesturesEnabled: false,
  },
});

const ConnectedRootNavigator = ({ nav, dispatch }) => (
  <RootNavigator
    navigation={addNavigationHelpers({
      dispatch,
      state: nav,
    })}
  />
);

const mapStateToProps = ({ nav }) => ({ nav });

export default connect(mapStateToProps)(ConnectedRootNavigator);
```

LoginNavigator.js:
```javascript
import { TabNavigator } from 'react-navigation';
import {
  Welcome,
  SignIn,
} from '$screens/Login';

const LoginNavigator = TabNavigator({
  Welcome: {
    screen: Welcome,
    path: 'login/welcome',
  },
  SignIn: {
    screen: SignIn,
    path: 'login/signIn',
  },
}, {
  swipeEnabled: false,
  lazy: true,
  navigationOptions: {
    tabBarVisible: false,
  },
  title: 'Login',
});

export default LoginNavigator;

```

navReducer.js:
```javascript
import { NavigationActions } from 'react-navigation';
import { RootNavigator } from '$navigators/RootNavigator';
import { settings } from '$config';

const initialState = RootNavigator.router.getStateForAction(
  NavigationActions.navigate({ routeName: 'login' }));


const navReducer = (state = initialState, action) => {
  const nextState = RootNavigator.router.getStateForAction(action, state);
  return nextState || state;
};

export default navReducer;
```

When I set my initial state to a route that has normal component works normally:

```javascript
const initialState = RootNavigator.router.getStateForAction(
  NavigationActions.navigate({ routeName: 'splash' }));
```

But when I set my initial state to a nested navigators, the app raises the error:
```javascript
const initialState = RootNavigator.router.getStateForAction(
  NavigationActions.navigate({ routeName: 'login' }));
```

**Comment by matt-oakes** [comment]
It seems like the issue is that nested navigators can't be at the root of the navigation stack. They don't get properly initialized with the `routes` property. If you add in a non-navigator component before it, everything works as expected.

**Comment by matt-oakes** [comment]
Ok. I've found a way to fix this. I have a "modal stack navigator" at the root and want to set it up with a TabNavigator nested at the root of that with a welcome modal on top. To do that, the initial state should be setup like this:

```javascript
const tabsAction = NavigationActions.init()
const tabsState = ModalStackNavigator.router.getStateForAction(tabsAction)
const welcomeAction = NavigationActions.navigate({ routeName: 'welcomeStack' })
export const initialState = ModalStackNavigator.router.getStateForAction(welcomeAction, tabsState)
```

The first two lines will correctly set up the nested tabs navigator with the `routes` property and avoid the error above.

**Comment by freekvdp** [comment]
@matt-oakes I have a StackNavigator implementing 2 other StackNavigators that are both pretty much identical. On one of them I get the error "Cannot read property 'router' of undefined", when I comment out that Navigator suddenly the app works fine. Is your solution applicable in this situation? (I've just started on react and redux, and untill now I have had the most problems with navigation...)

**Comment by eduardoleal** [comment]
@matt-oakes, it worked for me! Thanks!

**Comment by eduardoleal** [comment]
@matt-oakes its working now, but it's causing the app to render twice... 

```(javascript)
const tabsAction = NavigationActions.init()
```

**Comment by swellingt0n** [comment]
@matt-oakes The result is the same for me, with or without using NavigationActions.init(). State comes out of the reducer containing the correct `navigation.state` values, but when it comes time to render the nested DrawerNavigator, `navigation.state` only contains the data of the single route, rather than the routes property.

**Comment by herman-rogers** [comment]
So I have a react native app implemented with Redux and I was running into a similar issue (perhaps not the same problem though). Essentially I have navigation setup to do StackNavigator as the App Route and TabNavigator as a child (nested) route of the Stack Navigator.

I was having issues selecting different tabs with the system throwing an error of 'property undefined' inside the reducer. From what I can tell when attempting to navigate to a tab - say 'Home' - it was looking for any route inside of the Stack Navigator but failed to find 'Home' since home only exists inside of the TabNavigator.

To get around this issue (warning this may just be a hack - I'm not sure) I updated the reducer to navigate to main first, grab the corresponding action for 'Home', and then navigate to home.

The reducer looks like:

```javascript
export default function navigation(state = initialState, action) {
  // currentRoute was returning null through tab navigation
  let currentRoute = AppNavigator.router.getActionForPathAndParams(action.routeName);
  let nextState = state;

  switch (action.routeName) {
    case 'Home':
      // First navigate to Main, the grab the 'Home' action
      currentRoute = AppNavigator.router.getActionForPathAndParams(`Main/${action.routeName}`);
      nextState = AppNavigator.router.getStateForAction(currentRoute.action);
      break;
    default:
      nextState = AppNavigator.router.getStateForAction(currentRoute);
  }
  return nextState;
}
```

Seems to work fine. In addition I was also dispatching navigation actions from my Redux actions by nesting the action (Navigation.action(routeName: 'Main', action: 'Home') but I'm able to just normally dispatch home now without nesting an action.

Hope this helps.

**Comment by tonbh10x** [comment]
![text](https://github.com/react-navigation/react-navigation/assets/126857292/ebcec756-3df5-48a7-9a7b-f218bfe15ca3)
I want to use DrawerItemList but when I use it, I get the above error. I hope everyone can help.

**Comment by MorganTrudeau** [comment]
For me this was happening to me on web only. The fix was to ensure you had linking (for your NavigationContainer) set up for every screen. If you don't have screens mapped to linking names the browser history gets messed up I guess?
