### ISSUE TITLE
Is it possible to catch tab bar press events?

### ISSUE THREAD

**Issue by kimdhoe** [react-community/react-navigation#486]
I'm trying to figure out a way to detect tab press event. What I'd like to achieve is:

1. A user presses the first tab and navigates to _tab-1_ screen.
2. Scrolls down a bit.
3. Presses the first tab again --> __scrolls to top__

I saw passing `onTabPress` callback down to the `<TabBar />` (of _react-native-tab-view_) mentioned at PR #405. I tried something like:

```javascript
TabNavigator(
  { /* ...routes */ },
  { tabBarOptions: { onTabPress: () => { /* ... */ } }
)
```

Unfortunately, nothing happened. It seems like `onTabPress` is not passed down to the `<TabBar />`. 

Feels like I'm missing something very obvious. Any comments would be appreciated!

__My question is__: Is it possible to pass `onTabPress` callback down to the `<TabBar />`? If not, are there any workarounds to achieve my goal to catch tab press events?

**Comment by shawngustaw** [comment]
I think this was just added recently. 

See the section on `onNavigationStateChange(prevState, newState)`

https://reactnavigation.org/docs/navigators/

**Comment by kimdhoe** [comment]
Thanks for the comment, @shawngustaw, but I'm afraid that's not what I'm looking for.

The problem is that what I want to catch is basically a _tab press_ event, not a _navigation state change_. In the situation I described above, pressing a tab does not dispatch an action or trigger a state change at all. I was wondering if a callback can be passed down to the button component in a tab bar so that it can be invoked on `onPress`, since _react-native-tab-view_ is already accepting `onTabPress` callback.

**Comment by arnsa** [comment]
+1, need this also. If I navigate to child route in tabbar and press on tab bar icon, it won't go back to initial route :(

**Comment by samwise00** [comment]
Need this as well

**Comment by nickw** [comment]
This should probably be built-in to TabNavigator somehow. These are pretty standard behaviors a tab should have if you are already viewing that tab and press it again:

1. Takes you back to the first screen in that tab's stack
2. If you are already on the first screen, scrolls you to the top of that screen
3. If you are already on the first screen and scrolled to the top, does nothing

**Comment by idris** [comment]
@nickw agreed #1 would be a nice option to have. The scrolling part could get tricky based on _where_ the scroll view is actually located, so I would still recommend an onTabPress callback for that

**Comment by kennydl** [comment]
+1, I really need this too. I got problems with getting to initial screen when pressing one of the tab buttons.

**Comment by grabbou** [comment]
Closing in favour of #314

**Comment by andersrehn** [comment]
@opera9900 @kimdhoe I did not follow the entire thread to know how the discussion ended up with the condition `if (index !== 3 /* ~ ~ */)` but I found out that in `({jumpToIndex, ...props})` especially the `props`-object where is a `getLastPosition()` function that you can call. Changing `if (index !== 3 /* ~ ~ */)` to `if (index !== getLastPosition())` will make the `else` statement to be triggered when the same tab has been pressed multiple times.

**Comment by mmckinley8** [comment]
I was able to achieve the exact functionality that @nickw outlined with the following code:

In TabNav config: 

```const tabBarOnPress = navigation => config => {
  const {scene, index, jumpToIndex} = config

  if (scene.index === 0 || scene.index === 1) {
    StatusBar.setBarStyle('default')
  }

  if (scene.index === 0 && scene.route.index > 0) {
    StatusBar.setBarStyle('light-content')
  }

  if (!scene.focused) {
    jumpToIndex(scene.index)
  } else {
    if (scene.route.routes.length > 1) {
      for (let i = 0; i < scene.route.routes.length - 1; i += 1) {
        const backAction = NavigationActions.back()

        navigation.dispatch(backAction)
      }
    } else {
      const homeNavigator = scene.route.routes[0]

      if (!!homeNavigator && !!homeNavigator.params && !!homeNavigator.params.scrollToTop) {
        homeNavigator.params.scrollToTop()
      }
    }
  }
}```

**Comment by SamBellerose** [comment]
@mmckinley8 Thanks for this solution! Worked perfectly. I've got one small question though, I'm new to React-Native/Javascript syntax, how could I pass an other variable in the tabBarOnPress function? 

Something like:

```
navigationOptions: ({navigation}) => ({
    tabBarOnPress: tabBarOnPress(navigation, value)
})

//not sure about the syntax here
const tabBarOnPress = (navigation, value) => config => {
    //do something with value
}
```

Thanks a lot in advance for help.

**Comment by amin-mundano** [comment]
If you're using `createBottomTabNavigator`, you can use something like this: 
```
const tabBarOnPress = ({ navigation, defaultHandler }) => {
    const { isFocused, state, goBack } = navigation;
    if (isFocused()) {
        if (state.routes.length > 1) {
            for (let i = 0; i < state.routes.length - 1; i += 1) {
                goBack();
            }
        } else {
            // @TODO SCROLL TO TOP OF EACH TAB IF SCROLLABLE, $CALLBACK().
        }
    } else {
        defaultHandler();
    }
};

    navigationOptions: navigation => ({
        ....
        tabBarOnPress,
        ....
    }),

```

**Comment by ggomaeng** [comment]
@amin-mundano there can be a situation where state.routes can be undefined for other tabs.

```
const tabBarOnPress = ({ navigation, defaultHandler }) => {
    const { isFocused, state, goBack } = navigation;
    if (isFocused()) {
        if ( **state.routes** && state.routes.length > 1) {
            for (let i = 0; i < state.routes.length - 1; i += 1) {
                goBack();
            }
        } else {
            // @TODO SCROLL TO TOP OF EACH TAB IF SCROLLABLE, $CALLBACK().
        }
    } else {
        defaultHandler();
    }
};

    navigationOptions: navigation => ({
        ....
        tabBarOnPress,
        ....
    }),
```

**Comment by Bautista-Baiocchi-lora** [comment]
'state.routes.length' seems to always return 1 even when it is not. Why is that? @ggomaeng @amin-mundano

**Comment by Neha0595** [comment]
navigationOptions: ({ navigation }) => ({
      tabBarOnPress: (scene, jumpToIndex) => {
          console.log('onPress:', scene.route);
          jumpToIndex(scene.index);
      },
    }),

tabBarOnPress function not called

**Comment by iseegr8tfuldeadppl** [comment]
Another method of doing it is to SIMPLY SET THE LISTENER


```
const unsubscribe = navigation.addListener('tabPress', e => {
    // Prevent default action
    e.preventDefault();
    console.log("caught tab press");
});
```

**Comment by ar0692** [comment]
You can use { useScrollToTop } from '@react-navigation/native' hook in react navigation 5
https://reactnavigation.org/docs/use-scroll-to-top/

**Comment by whalemare** [comment]
Link: https://reactnavigation.org/docs/navigation-events/#listeners-prop-on-screen
```
<Tab.Screen
  name="Chat"
  component={Chat}
  listeners={{
    tabPress: e => {
      // Prevent default action
      e.preventDefault();
    },
  }}
/>
```

**Comment by cmcodes-uniworks** [comment]
**THIS WILL WORK!**

https://reactnavigation.org/docs/navigation-events/#navigationaddlistener

**Comment by yulyasystem** [comment]
> Another method of doing it is to SIMPLY SET THE LISTENER
> 
> ```
> const unsubscribe = navigation.addListener('tabPress', e => {
>     // Prevent default action
>     e.preventDefault();
>     console.log("caught tab press");
> });
> ```

How to know which tab is pressed exactly?

**Comment by cglacet** [comment]
I think my issue is related to this, I want to have a specifi screen behavior when the screen is visited from a tab bar press or from a deeplink (in contrast with a back navigation). 

I can handle deeplinks pretty easily as I can pass URL arguments. But I struggle intercepting tab bar events to insert route params for that specific navigation event. 

I found a hack, but its very dirty:

```tsx
<Tab.Screen
    name="Todo"
    component={SomeStack}
    listeners={({ navigation }) => ({
        tabPress: () => {
            navigation.navigate('Todo', {screen: 'Test', params: {new: true}});
        },
    })}
/>
```

The problem here is that this make my navigation dependent on that hidden call to `navigate` even though the navigation **should** be handled like all others: using the inner stack `initialRouteName` and `initialParams`. Using this solution is problematic since any change to these two stack props will have no effect (since the navigation is handled with the hack).

I would be very interested by a solution that makes more sense.

**Comment by saumya66** [comment]
> Link: https://reactnavigation.org/docs/navigation-events/#listeners-prop-on-screen
> 
> ```
> <Tab.Screen
>   name="Chat"
>   component={Chat}
>   listeners={{
>     tabPress: e => {
>       // Prevent default action
>       e.preventDefault();
>     },
>   }}
> />
> ```

works like charm! thanks.

**Comment by Abubakarraza** [comment]
I handle event by adding tabBarButton in screenOptions
add your desire function here or default function
`tabBarButton: (props) => {
                  return (
                    <MTouchable
                      style={props.style}
                      onPress={() => {
                          props.onPress();
                      }}
                    >
                      {props.children}
                    </MTouchable>
                  );
                },`

**Comment by Vimiso** [comment]
Anyone know whether the listener can be configured from within the tab screen so that I can deal with local state.
