### ISSUE TITLE
Ability to configure header from any navigator

### ISSUE THREAD

**Issue by mguida22** [react-community/react-navigation#488]
My understanding is that the Header component is only part of the StackNavigator. It would be extremely helpful be able to have the Header component available when just using a TabNavigator (or any navigator).

I've seen some other talk on [stackoverflow](https://stackoverflow.com/questions/42356771/how-to-display-headers-in-react-navigation-with-tabnavigation) and in https://github.com/react-community/react-navigation/issues/190 about this but thought a new feature request would be best.

My specific use case is for a settings page, using a TabNavigator. I want to be able to set the navigationOptions similar to the following...
```jsx
// within App.js
const App = TabNavigator({
  Home: { screen: Home },
  Settings: { screen: Settings },
}, {
  tabBarOptions: {
    activeTintColor: colors.primary,
  },
})

// within Settings.js
static navigationOptions = {
  title: 'Settings',
  header: {
    right: <Button title="Edit" />,
  },
  tabBar: {
    label: 'Settings',
    icon: () => (
      <Icon color={colors.primary} name='settings' size={26} />
    ),
  },
}
```

I believe I can get the desired effect using a StackNavigator, but it makes sense to me to have the header available on any navigator. Sorry if I am misunderstanding and this is already possible.

**Comment by satya164** [comment]
Just nest it inside a stack navigator with a single screen.

**Comment by AdamChrist** [comment]
+1
