### ISSUE TITLE
[StackNavigator] Header Title Component not align center on iOS.

### ISSUE THREAD

**Issue by ng-hai** [react-community/react-navigation#490]
I can't find a way to center my header Title component, so I go inside `Header.js` and see that there is no style for iOS Platform, only Android.
```

const style = {};

if (Platform.OS === 'android') {
      if (!options.hasLeftComponent) {
        style.left = 0;
      }
      if (!options.hasRightComponent) {
        style.right = 0;
      }
}
```

![simulator screen shot feb 27 2017 10 17 04 am](https://cloud.githubusercontent.com/assets/19520278/23347715/bf499bf4-fcd6-11e6-97ff-478886c584c8.png)

**Comment by RobertSheaO** [comment]
You can pass it in as the `title` prop to the header as either a string, or a react component.

```JS
static navigationOptions = {
  title: 'This can only be a string'
  header: {
   title: 'this defaults to above title, or can be react element'
  },
};
```

https://reactnavigation.org/docs/navigators/stack

**Comment by ng-hai** [comment]
I used `header.title` as a react component just for test. Like this:

```
static navigationOptions = {
        header: {
            title: <Text>Settings</Text>,
            right: <Text>Right</Text>,
            left: <Text>Left</Text>
        }
}
```

**Comment by RobertSheaO** [comment]
@ng-hai You can checkout the default styles applied to the header title here...

https://github.com/react-community/react-navigation/blob/master/src/views/HeaderTitle.js

**Comment by ng-hai** [comment]
Actually, my component could be a <Title /> with different fontFamily or a <DropDownMenu /> of Shoutem UI, that's why I must use component instead of a string.

**Comment by RobertSheaO** [comment]
@ng-hai Then just mimic the styles from `HeaderTitle.js` that you'd like to borrow in your own custom component. If you want to detect between Android/iOS, you can import `Platform` from `react-native`

**Comment by ng-hai** [comment]
I have temporarily fixed by adding `titleStyle` with fontFamily and using a string instead of component. Will try to find some way to handle title component later.

![simulator screen shot feb 27 2017 11 47 23 am](https://cloud.githubusercontent.com/assets/19520278/23349070/83a7dac8-fce2-11e6-86a7-3e09d17353c9.png)

**Comment by zenyr** [comment]
What about `<TextOrView style={{flex:1,textAlignOrAlignItems:'center'}}><YourThing /></TextOrView>`? 😄

**Comment by grabbou** [comment]
Please use master. Beta 5 has a different layout and that's why your custom React component need styling. On master, I believe it should center regardless. 

Closing as OP fixed the issue.

**Comment by syssam** [comment]
You need to add left and right at the same time, it will be fixed.
if you only add left or right, the title will be offset because the right or left component have the width.

```
if (Platform.OS === 'android') {
      if (!options.hasLeftComponent) {
        style.left = 0;
      }
      if (!options.hasRightComponent) {
        style.right = 0;
      }
}

```

<img width="1012" alt="2017-04-23 18 56 16" src="https://cloud.githubusercontent.com/assets/20774834/25312901/e9639df8-2856-11e7-8b39-54278d776e99.png">

you could add <View></View> on the empty left or right, it will fixed it.

**Comment by JirkaNovakProBohate** [comment]
just add `headerLeft: <View></View>`

**Comment by Pouria22** [comment]
you could write something like this:
`headerTitleStyle: {
                        textAlign: 'center',
                        alignSelf: 'center',
                        fontWeight: 'normal',
                        fontSize: 20,
                        color: '#606060'
                    }`

**Comment by a11231g** [comment]
{flex:1, textAlign: 'center'} solved my issue on android ,

**Comment by jimenezjrs** [comment]
> {flex:1, textAlign: 'center'} solved my issue on android ,

Works on iOS also.

**Comment by Almos-Pal** [comment]
In  **_2025_** @react-navigation/native-stack **version 7** you can use:

` headerTitleAlign: "center",`
