### ISSUE TITLE
No documentation for headerMode

### ISSUE THREAD

**Issue by sadika9** [react-community/react-navigation#491]
What is headerMode option do? I could not  find any documentation for it

**Comment by MrHubble** [comment]
@sadika9 I assume you closed this issue because you found the documentation? Could you please paste a link to the documentation?

**Comment by sadika9** [comment]
@MrHubble https://reactnavigation.org/docs/navigators/stack#StackNavigatorConfig

**Comment by MrHubble** [comment]
@sadika9 Thanks for taking the time to respond.

I also found [this example](https://github.com/react-community/react-navigation/issues/293#issuecomment-279146748) helpful.

**Comment by karltaylor** [comment]
@sadika9 that doc 404's FYI

**Comment by brentvatne** [comment]
https://reactnavigation.org/docs/en/stack-navigator.html
