### ISSUE TITLE
Child routes of tabbar

### ISSUE THREAD

**Issue by arnsa** [react-community/react-navigation#492]
Hello,

so I've decided to rewrite my current app using react-navigation and I already have a problem (which, I am sure, is already solved, but I can't seem to find a way how). I have a TabNavigator. Inside index tab, there's a list of messages. If I click on a message, it should open up a new scene with a chat. From what I've seen in the docs, StackNavigator is used for that, but the problem is that when StackNavigator is used, TabBar isn't visible anymore and that's not what I need :(. I need TabBar to still be visible, and when, for example, user clicks on messages tab icon, it should go back to that scene.

**Comment by bsnelder** [comment]
I got this to work by combing the `TabNavigator` with the `StackNavigation`

**TabNavigator**
```
const MyApp = TabNavigator({
    Home: { screen: HomeNavigator },
    Products: { screen: ProductsNavigator },
});

```
**StackNavigator**
```
const HomeNavigator = StackNavigator({
    HomeScreen: { screen: HomeScreen },
    BlankScreen: { screen: BlankScreen }
});

const ProductsNavigator = StackNavigator({
    ProductsScreen: { screen: ProductsScreen },
    ProductDetailScreen: { screen: ProductDetailScreen }
});
```

**Comment by arnsa** [comment]
@bsnelder thank you, I've found a very similar example in their examples folder just a few minutes ago! :D
