### ISSUE TITLE
Change color of tabbar icon

### ISSUE THREAD

**Issue by arnsa** [react-community/react-navigation#493]
Hello,

I have 2 icons: tabbarIcon.png and tabbarIconActive.png, but I can't seem to find a way how to change between these two if tab is active or inactive. All I could find is activeTintColor property, which says that it's changing color of a text in a tabbar and icon's color, but I don't see how can it change a color of a png image.

**Comment by grabbou** [comment]
Hey,

You can do it that way:
```js
icon: ({ focused }) => {
   // based on `focused` boolean, decide what `Image` to return
},
```

icon can also be a function, not only React element, that receives `focused` property. Also check examples in `NavigationPlayground` on how to change it based on active state.
