### ISSUE TITLE
Get previous scene?

### ISSUE THREAD

**Issue by arnsa** [react-community/react-navigation#497]
Hello,

Let's say I am navigating from Schedule to Favorites scene. Then in Favorites scene I hit back button and this function gets called: this.props.navigation.goBack(). What I need now is to know in Schedule scene what was the previous scene (in this case Favorites). I tried doing it like this: this.props.navigation.goBack('Favorites') but then back button stop working :(.

**Comment by stief510** [comment]
You have to provide the key for Favorites, not the route name.

**Comment by arnsa** [comment]
@stief510 I am not sure what you mean. Can you give me an example, please?

**Comment by stief510** [comment]
Every route has an associated key that is assigned to it when pushed onto the stack. You have to search the stack for the key associated with the route that you want and then pass that into the goBack function.

However, you could also try without passing in anything if you just want to pop the current screen and go back to the previous

**Comment by arnsa** [comment]
@stief510 but as I understand I must use redux for this? Because otherwise componentWillReceiveProps never gets called on container component.

**Comment by stief510** [comment]
I don't use redux at all in my project. It should be accessible via the navigation state. However, I am having some issues getting the previous routes at the moment

**Comment by arnsa** [comment]
@stief510 but if you don't use redux, at least for me, container's componentWillReceiveProps lifecycle hooks never gets called, because it doesn't receive any props.

**Comment by stief510** [comment]
But you should be able to receive props in other places, like the constructor as an example

**Comment by arnsa** [comment]
@stief510 yes, but that'll happen only once (when the component mounts). And I won't be able to get previous scene anyways.

**Comment by stief510** [comment]
I opened a PR #500 to hopefully fix that

**Comment by MrHubble** [comment]
So currently there's no way to view the current stack within StackNavigator?

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
