### ISSUE TITLE
"reset" scenes after language change

### ISSUE THREAD

**Issue by arnsa** [react-community/react-navigation#498]
I am using https://github.com/stefalda/ReactNativeLocalization for my app localization. Let's say I've visited scene A that has some text in english: <Text>{I18n.some.text}</Text>. Then if I change the language from english to lithuanian and go back to scene A, the text will still be in english, because the scene was already mounted and didn't "reload" after language change. If I didn't visit scene A and went straight to language change, it would display text in lithuanian, as expected.

Is there any solution for this?

**Comment by Fenwil** [comment]
@arnsa Did you resolve this ? If so how ? Having the same problem but I'm using https://github.com/AlexanderZaytsev/react-native-i18n

**Comment by arnsa** [comment]
@Fenwil yeah, the solution was to integrate redux and to use that router in every container component using redux's connect. That fixed the problem.
