### ISSUE TITLE
StackNavigator Animations on iOS are super laggy 

### ISSUE THREAD

**Issue by jaredly** [react-community/react-navigation#5]
Not sure what's the cause here - is it weird animation curves, or just performance problems?
I do have `libRCTAnimation` linked to the project, fwiw
![laggy](https://cloud.githubusercontent.com/assets/112170/22353727/1db46d88-e3df-11e6-85bb-4eac5f093f9c.gif)

**Comment by knowbody** [comment]
that might be caused by the simulator. I just checked on the actual device and works fine.

@brentvatne just published the examples on Exponent: https://getexponent.com/@community/react-navigation-playground

please let us know if you are still having the issue

**Comment by skevy** [comment]
I haven't seen this particular issue @jaredly. Will try on a real device soon just to be sure. But this issue not withstanding, as I said on Twitter, we do have some work to do still on the animation curves.

**Comment by ericvicenti** [comment]
The gestures are coordinated from JS and may not be perfectly performant. But the animations should be animated using the new API

**Comment by jcarbo** [comment]
Hard to tell exactly how slow the animations are going from the gif, but is it possible you accidentally turned on "slow-motion animations"? http://stackoverflow.com/questions/8624519/simulator-slow-motion-animations-are-now-on/8624549#8624549

**Comment by mkonicek** [comment]
I can't repro this and it looks like other can't repro it either. Let's close for now unless it turns out it's an issue not caused by the simulator.
