### ISSUE TITLE
indicatorStyle not working on IOS

### ISSUE THREAD

**Issue by yapjinkun** [react-community/react-navigation#504]
trying to set underline indicator for active tab, but it's not working on IOS. Android is working fine.

![screenshot 2017-02-28 11 12 44](https://cloud.githubusercontent.com/assets/16733273/23390360/7fdf685e-fda8-11e6-9382-52bcc4d45fd2.png)

![screenshot_20170228-111446](https://cloud.githubusercontent.com/assets/16733273/23390369/8c1eec2a-fda8-11e6-9ed9-924c0a8c54e4.png)

```
const HomeScreen = TabNavigator({
  Home: {
    screen: HomeTabMainScreen,
  },
  Nearby: {
    screen: HomeTabNearbyScreen,
  },
  Upcoming: {
    screen: HomeTabUpcomingScreen,
  },
}, {
  tabBarPosition: 'top',
  swipeEnabled: true,
  tabBarOptions: {
    activeTintColor: '#ffffff',
    inactiveTintColor: '#ffffff',
    inactiveBackgroundColor: '#353539',
    activeBackgroundColor: '#353539',
    showIcon: false,
    indicatorStyle: {
      borderBottomColor: '#ffffff',
      borderBottomWidth: 2,
    },
    labelStyle:{
      fontSize: 12,
      justifyContent: 'center',
      alignItems: 'center',
    },
    style:{
      backgroundColor: '#353539',
    },
    tabStyle: {
      justifyContent: 'center',
      alignItems: 'center',
    }
  },
});
```

**Comment by satya164** [comment]
```js
const HomeScreen = TabNavigator({
  Home: {
    screen: HomeTabMainScreen,
  },
  Nearby: {
    screen: HomeTabNearbyScreen,
  },
  Upcoming: {
    screen: HomeTabUpcomingScreen,
  },
}, {
  ...TabNavigator.Presets.AndroidTopTabs,
  tabBarOptions: {
    // whatever
  },
});

**Comment by camunity** [comment]
I'm trying to set an indicator to show an underline under the bottom tab bar items in iOS is this possible?

**Comment by TheTekton** [comment]
@camunity:

```jsx
var highlightTab = (tabName, focused) => {
  var footerHeight;
  if (focused) {
    footerHeight = 1;
  } else {
    footerHeight = 0;
  }

  var styles = StyleSheet.create({
    tab: {
      flexGrow: 1,
      alignItems: 'stretch',
      justifyContent: 'flex-end'
    },
    labelFooter: {
      height: footerHeight
    }
  });
  
  return (
    <View style={styles.tab}>
      <Text>{tabName}</Text>
      <View style={styles.labelFooter}/>
    </View>
  );
};

var tabRouteConfigs = {
  MyTab: {
    screen: MyTabScreen,
    navigationOptions: {
      tabBar: {
        label: ({ focused }) => {
          highlightTab('MyTab', focused);
        }
      }
    }
  }
};
```

**Comment by davidfloegel** [comment]
has the indicatorStyle prop been removed? Can't find it anywhere in the codebase if I search for it!

**Comment by liuxiaocong** [comment]
any update? i want ios to be same as android

**Comment by agentilela** [comment]
Yeah, it's been removed for some reason, but you can override the TabBarTop props (it is just passing them to [react-native-tab-view](https://github.com/react-native-community/react-native-tab-view) under the hood, so configure those however you'd like)

```
import { TabBarTop, TabNavigator } from "react-navigation";

...

TabNavigatorConfig = {
...
  tabBarComponent: props => (
    <TabBarTop {...props} indicatorStyle={{ backgroundColor: "#333" }} />
  ),
}

export default TabNavigator(RouteConfigs, TabNavigatorConfig)
```

**Comment by willdavidow** [comment]
Ran into this issue today as well and decided to try to get the example that @TheTekton had posted working for my needs...

Essentially the functionality replaces the label with a label + indicator (`showLabel` needs to be enabled in the `TabNavigator` even if you don't want to display a text label). It gets applied to the Component driving the route via its `navigationOptions`

Hopefully this helps someone:

```
import React from 'react';
import {
  StyleSheet,
  Text,
  View,
} from 'react-native';

export default TabBarHighlightLabel = ({
    focused,
    label,
    indicatorHeight,
    activeLabelColor,
    activeIndicatorColor,
    inactiveLabelColor,
    inactiveIndicatorColor
}) => {
  const config = {
    activeIndicatorColor: activeIndicatorColor || '#333333',
    inactiveIndicatorColor: inactiveIndicatorColor || 'transparent',
    activeLabelColor: activeLabelColor || '#333333',
    inactiveLabelColor: inactiveLabelColor || '#CCCCCC',
  };

  const indicatorColor = focused ? config.activeIndicatorColor : config.inactiveIndicatorColor;
  const labelColor = focused ? config.activeLabelColor : config.inActiveLabelColor;

  const styles = StyleSheet.create({
    labelContainer: {
      flex: 0,
      width: '100%',
      alignItems: 'center',
      justifyContent: 'flex-end',
    },
    labelText: {
      flex: 0,
      width: '100%',
      textAlign: 'center',
      justifyContent: 'center',
      fontSize: 12,
      color: labelColor
    },
    labelIndicator: {
      flex: 0,
      width: '100%',
      height: (indicatorHeight ? indicatorHeight : 2),
      justifyContent: 'flex-end',
      backgroundColor: indicatorColor
    },
  });
  const maybeRenderLabel = label && <Text style={styles.labelText}>{label}</Text>; 

  return (
    <View style={styles.labelContainer}>
      {maybeRenderLabel}
      <View style={styles.labelIndicator} />
    </View>
  );
}

```

Example usage in a Component:
```
import React, { Component } from 'react';
import {
  Platform,
  StyleSheet,
  Text,
  ScrollView,
View,
} from 'react-native';

import TabBarHighlightLabel from './TabBarHighlightLabel';

const styles = StyleSheet.create({
  container: {
    marginTop: Platform.OS === 'ios' ? 20 : 0,
  },
});

class Favorites extends Component {
  static navigationOptions = {
    tabBarLabel: ({focused}) =>
      <TabBarHighlightLabel
        focused={focused}
        activeLabelColor="#333333"
        activeIndicatorColor="#333333"
        inactiveLabelColor="#CCCCCC"
        inactiveIndicatorColor="transparent"
        indicatorHeight={2}
      />
  };

  render() {
    return (
      <ScrollView style={styles.container}>
        <Text>Favorites</Text>
      </ScrollView>
    );
  }
}

export default ExampleComponent;
```


![tab-underline](https://user-images.githubusercontent.com/763985/27154994-080814e0-5125-11e7-9937-fc3570704a82.gif)

**Comment by finetimi** [comment]
A simple working solution here.
https://github.com/finetimi/React-Native-Reddit/blob/master/src/containers/index.js#L49
![home](https://user-images.githubusercontent.com/20421030/27773834-b69db63e-5f50-11e7-954c-6a9019cb63be.png)

**Comment by justinlok** [comment]
I had the same issue on iOS but got it working. It seems you must explicitly set the tabBarComponent to TabBarTop on iOS if you want a top tab bar.

`import { StackNavigator, TabNavigator, DrawerNavigator, TabBarTop } from 'react-navigation'`

Then for the TabNavigator, make sure to set:
```
tabBarComponent: TabBarTop,
tabBarPosition: 'top',
```

**Comment by sepion02** [comment]
@jslok can you tell me your versions of read-native and react-navigation ?
Because your solution is not working for me.

**Comment by YasirPanjsheri** [comment]
@sepion02 Hi, have you found a solution? I SOLVED the problem by wrapping all the screens with a container applying in it `paddingTop: 20`.
but once I position the tabs at top, I cannot find a way to add the padding. The container with padding thing does not work in this case.

```
import { TabNavigator, TabBarTop } from 'react-navigation';
import { Platform } from 'react-native';
// other imports


const routeConfiguration = {
    Tab1: { screen: Tab1 },
    Tab2: { screen: Tab2 },
    Tab3: { screen: Tab3 },
    Tab4: { screen: Tab4 },
  }

const tabBarConfiguration = {
    tabBarPosition: 'top',
    tabBarComponent: TabBarTop,    // this so I can get the indicator like in android
    animationEnabled: true,
    swipeEnabled: true,

    tabBarOptions:{
        activeTintColor: 'rgb(52,113,157)',
        inactiveTintColor: 'rgb(146,148,151)',

        showIcon: true,
        style: {
            backgroundColor: 'rgb(255,255,255)',
            borderBottomWidth: 1,                // this because elevation is not working, wish if someone can tell me why or how to fix it
            borderColor: 'rgb(208,210,211)',
            //marginTop: 20                     // this is working when adding margin, but then I don't know how to set the background there (status bar's background)
        },
        indicatorStyle: {
            backgroundColor: 'rgb(67,126,181)',
        },
        iconStyle: {
            width: 28,
            height: 28
        },
        labelStyle: {
            fontSize: 11,
        },

    }
}
export const TabBarUser = TabNavigator(routeConfiguration, tabBarConfiguration)
```

**Comment by namxam** [comment]
@agentilela I am not sure if they have added it again, but setting indicatorStyle works quite well. I think I ran in the same issue and used your solution and it worked. But then I realised, that I have set the backgroundColor of all tabs via `tabStyle`. Instead you should set the TabBar background via `style` property.

**Comment by jasonzhangdong** [comment]
@satya164  very good

**Comment by soundstage** [comment]
`indicatorStyle`'s `backgroundColour` needs to be set within `tabBarOptions` of the `TabNavigator`. `indicatorStyle` will get overridden by the styles under `tabStyle`.

**Comment by dengue8830** [comment]
@sidgwick can you share the complete config json object?

**Comment by shabeer3508** [comment]
> ```js
> const HomeScreen = TabNavigator({
>   Home: {
>     screen: HomeTabMainScreen,
>   },
>   Nearby: {
>     screen: HomeTabNearbyScreen,
>   },
>   Upcoming: {
>     screen: HomeTabUpcomingScreen,
>   },
> }, {
>   ...TabNavigator.Presets.AndroidTopTabs,
>   tabBarOptions: {
>     // whatever
>   },
> });
> ```

...TabNavigator.Presets.AndroidTopTabs, did the trick 👍

**Comment by khaitrann** [comment]
As @soundstage mentioned above, I use this setting and it works fine. Hope this help

tabBarOptions={{
                style: { backgroundColor: 'red' },
                indicatorStyle: {
                    backgroundColor: 'blud'
                }
            }}
