### ISSUE TITLE
How do I use this without ES6?

### ISSUE THREAD

**Issue by seantempesta** [react-community/react-navigation#505]
I'm trying to use this library with ClojureScript, so I need to create components with non-es6 calls.  I know how to create a React class that has a render method, but I have no idea how to do the static variables inside the class:

```js
class MyHomeScreen extends React.Component {
  static navigationOptions = {
    title: 'Home',
  }

  render() {
    return (
      <Button
        onPress={() => this.props.navigation.navigate('Profile', {name: 'Lucy'})}
        title="Go to Lucy's profile"
      />
    );
  }
}
```

Is there another way to configure the `navigationOptions`?  Maybe by passing in props to a normal React Component?

Thanks!

**Comment by browniefed** [comment]
These just get defined as static properties so you can do 
```
MyHomeScreen.navigationOptions = {
  title: "Home"
}
```

**Comment by seantempesta** [comment]
Okay, that took me quite a bit, but I finally figured it out.  Thanks for the tip!  For anyone else who wants to do this in ClojureScript (specifically with Reagent), here's the final code I used:

```clojure
(defonce ReactNative (js/require "react-native"))
(defonce Text (.-Text ReactNative))
(defonce StackNavigator (.-StackNavigator (js/require "react-navigation")))

;; Create the HomeScreen Reagent class
(defn home-screen []
  (fn []
    [:> Text {} "Finally Got It!"]))

;; Convert it into a normal react component
(def HomeScreen (r/reactify-component home-screen))

;; Set the navigationOptions onto the component
(aset HomeScreen "navigationOptions" (clj->js {:title "Welcome"}))

;; Setup the StackNavigator to use it
(defn app-root []
  (fn []
    (.createElement js/React (StackNavigator (clj->js {:Home {:screen HomeScreen}})))))

;; Render it!
(defn init []
  (.registerComponent rn/app-registry "main" (fn [] (r/reactify-component app-root))))
```

**Comment by manuTro** [comment]
@seantempesta How do call the navigate function?

**Comment by manuTro** [comment]
@seantempesta I'm trying to use this library as well.. Do you know how to navigate between nested stacknavigator? Like in this situation
```
                                  Stack-navigator
                            
                                       Main 
                                                 Stack/navigator
                                                       FirstScreen
                                                       SecondScreen
                                       Chat
                                       Prova
```

In this case, do you know how I can navigate from FirstScreen to Chat?

**Comment by theronic** [comment]
@seantempesta, how do you render a dynamic headers by passing `:headerRight` as a functoint hat takes props/screenProps? I am unable to call `(aset "navigationOptions" (fn [props] ...))` without React blowing up.
