### ISSUE TITLE
使用 createMaterialTopTabNavigator 组件后，无法在其子组件内部跳转路由

### ISSUE THREAD

**Issue by ghost** [react-community/react-navigation#5052]
使用了createMaterialTopTabNavigator  组件，在其子组件内部调转到其他页面的路由，发现无法实现跳转，好像只能跳转 tabs 的路由的， 要怎么实现跳转其他路由

I used createMaterialTopTabNavigator as a component, I wanna to navigate another route, but it doesn't work, just can navigate tabs's route. How can i navigate route.

## Code
export const BettingTabs = createMaterialTopTabNavigator(
    {
        '全部': Child ,
        '待开奖': Child 
        '已中奖': Child 
    },
    {
        tabBarOptions: {
            ...options
        }
    }
)

### Then in another RouteComponent

import { BettingTabs } from '../../components/public/Tabs'

render() {
    return (
        <BettingTabs />
    )
}

### Child 
render() {
    return (
        <TouchableOpacity
            onPress={ () => { thi.props.navigation.navigate('Other') } }
           //  can't navigate
        >
        <TouchableOpacity>
    )
}

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^2.17.0
| react-native     | 0.55.4
| node             | 8.11.4
| npm or yarn      | yarn

**Comment by Pecking** [comment]
@13678460136  解决了这个问题吗？

**Comment by 13678460136** [comment]
好像是因为的tabNavigator 已经是在一个 BottomNavigation 的嵌套当中，所以我无法在tabNavigation 跳转 BottomNavigation 的路由，算是跳跃嵌套的路由关系





------------------ 原始邮件 ------------------
发件人: "Pecking"<notifications@github.com>;
发送时间: 2018年10月16日(星期二) 下午3:53
收件人: "react-navigation/react-navigation"<react-navigation@noreply.github.com>;
抄送: "Cyan"<869071331@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [react-navigation/react-navigation] 使用 createMaterialTopTabNavigator 组件后，无法在其子组件内部跳转路由 (#5052)




@13678460136  解决了这个问题吗？

**Comment by Pecking** [comment]
@13678460136 怎么解决了？

**Comment by 13678460136** [comment]
我一开始的做法是 在BottomNavigation 中有个RouterA ，然后RouterA包裹一个 Component 和 TabNavigation  这样就是把TabNavigation 试做一个组件，导致其内部无法获取到BottomNavigation 的路由层面 无法越层跳转，然后 我就把TabNavigation 替换到RouterA的位置，使其直接作为BottomNavigation的子路由，这样就可以获取到路由，实现跳转，但是也同时导致我无法再和其他组件配合使用





------------------ 原始邮件 ------------------
发件人: "Pecking"<notifications@github.com>;
发送时间: 2018年10月16日(星期二) 下午3:57
收件人: "react-navigation/react-navigation"<react-navigation@noreply.github.com>;
抄送: "Cyan"<869071331@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [react-navigation/react-navigation] 使用 createMaterialTopTabNavigator 组件后，无法在其子组件内部跳转路由 (#5052)




@13678460136 怎么解决了？

**Comment by Onekki** [comment]
你可以这样写
TopTabNav.navigationOptions = ({navigation}) => {
 return {
headerRight:<View navigation=navigation/>
}
}

**Comment by jiyouliang** [comment]
这个问题我通过全局路由解决的，可以参考：https://github.com/jiyouliang/NavigationDemo
