### ISSUE TITLE
The initial route in TabNavigator has been constructed twice

### ISSUE THREAD

**Issue by brownshang** [react-community/react-navigation#508]
After updated to 1.0.0-beta.6 from beta.5, I have found that in TabNavigator, the initial route's constructor(props) has been called twice, so as componentDidMount() and render().

I took the minimal TabNavigator sample for test, and got the same result.

Do you meet the same problem?

**Comment by makirby** [comment]
Yes I was having the same problem since beta.5, it's also been noted here #476.

**Comment by brownshang** [comment]
close this issue due to duplication #476
