### ISSUE TITLE
Bottom Navigation using wrong component

### ISSUE THREAD

**Issue by geobarlow** [react-community/react-navigation#509]
Hi, 

The Android version of iOS' Tab Bar is Android "Bottom Navigation" - https://material.io/guidelines/components/bottom-navigation.html

Is it possible to have this as a configurable option please? Just moving tabs to appear at the bottom is not really the same as the UI element behaves differently. 

Thanks

**Comment by alvaromb** [comment]
Hi @geobarlow!

You might wanna check this out https://github.com/timomeh/react-native-material-bottom-navigation#usage-for-react-navigation

**Comment by geobarlow** [comment]
Hi @alvaromb, 

Thanks - that looks great! 

Should this not be included with react-navigation,  like **react-native-tab-view** is?

**Comment by alvaromb** [comment]
I think the authors of `react-navigation` prefer to keep that in a separate module.

**Comment by nonameolsson** [comment]
@alvaromb Yeah, it seems like that.

I think it would be better to have that as a component in `react-navigation`.

**Comment by grabbou** [comment]
That sounds like a valid request. @satya164 since you are tab master, how do you feel about that?

**Comment by eduplus** [comment]
I would also greatly prefer to have it as a component in react-navigation.

**Comment by satya164** [comment]
I don't we can have all types of tab bars in core. Android's bottom navigation design is quite sophisticated because of all the animations it has. So it will have a huge maintenance cost. You can use something like what @timomeh made though.

**Comment by timomeh** [comment]
Although my opinion could sound slightly biased, I want to agree with @satya164. It's very important that react-**navigation** becomes a rock-solid **navigation**-module. Having more and more semigood and semi-bug-free features wouldn't help anyone. There would be more issues and PRs related to completely different things; bugfixes and new features would be shipped much slower.

The [reason why react-native deprecated the included navigator libraries in the first place](https://github.com/facebook/react-native/issues/12103) was _"to increase the focus on core components and direct PRs to the right place"_. I think that's a very important thought.

That being said, it would be great if react-navigation would provide more and better interfaces in the future to plug additional 3rd-party modules into; and to have a good documentation on how to write one. But at the moment you can't expect everything from those guys.

**Comment by alvaromb** [comment]
I'm with @timomeh and @satya164 in this one. It's better to have a clear interface to easily build modules that can work with `react-navigation` than integrating it into the lib.
