### ISSUE TITLE
Header visibility doesn't work on iOS

### ISSUE THREAD

**Issue by fk1blow** [react-community/react-navigation#511]
The header can be hidden by adding:
`tatic navigationOptions = {
    header: {
      visible: false
    }
  };`

While this is clear in the docs, it only works on android. The workaround for this
would be to add a style (`{width: 0, height: 0}`) to the header, causing it
to be hidden on iOS to.

Tested on iOS 10.2 and android 6 simulators.

**Comment by ibmsoft** [comment]
i have the same problem in ios 
version  	 "react-navigation": "^1.0.0-beta.5"

**Comment by fk1blow** [comment]
yeah, sorry for not specifying the version - ^1.0.0-beta.3

**Comment by bjrn** [comment]
if this is within a stackNavigation context, you'll need to add `headerMode: 'screen'` to the navigator options. See #293 for more info.

**Comment by grabbou** [comment]
Yes. @bjrn is right. Open `PR` that changes `headerComponent` to `header.bar` also makes it possible.
