### ISSUE TITLE
Override navigationOptions in StackNavigator screen

### ISSUE THREAD

**Issue by nonameolsson** [react-community/react-navigation#515]
Hi!
I have some problems to override some of the navigationOptions in a separate screen. Here is my code.
`app/navigators/settingsNavigator.js`

```
import React from 'react'
import { Text } from 'react-native'
import { StackNavigator } from 'react-navigation'
import { colors } from '../styles'

// Screens
import SettingsScreen from '../containers/settingsContainer'
import AboutScreen from '../containers/aboutContainer'
import NotificationsScreen from '../containers/notificationsContainer'

// StackNavigator options
const options = {
  header: () => ({
    tintColor: colors.white,
    style: {
      backgroundColor: colors.primaryColor
    }
  })
}

const routeConfigs = ({
  Settings: { 
    screen: SettingsScreen,
    navigationOptions: options
  },
  About: { 
    screen: AboutScreen,
    navigationOptions: options
  },
  Notifications: {
    screen: NotificationsScreen,
    navigationOptions: options
  }
})

const SettingsNavigator = StackNavigator(
  routeConfigs,
  {
    initialRouteName: 'Settings',
  }
)

export default SettingsNavigator
```

`app/containers/settingsContainer.js`
```
...
class SettingsContainer extends Component {
  static navigationOptions = {
    title: 'Inställningar',
    drawer: () => ({
      label: 'Inställningar',
      icon: () => <Icon name='settings' />
    }),
    header: () => ({
      left: <DrawerButton />
    })
  }

  ...

  render() {
    return (
      <View>
        <CustomStatusBar />
        <ListView
          dataSource={this.state.dataSource}
          renderRow={(data) => <ListItem onPress={() => this.onPress(data.screen)} {...data} />}
        /> 
      </View>
    )
  }
}
export default SettingsContainer
```

The `drawer` object in the navigationOptions works for my drawer. But everything I write in the the `header` or `title` in my component is overridden by the configuration in my StackNavigator.  

If I understand it correctly, that is the expected behaviour, [https://reactnavigation.org/docs/navigators/stack#RouteConfigs](https://reactnavigation.org/docs/navigators/stack#RouteConfigs)

How should I do if I want to override some settings on screen-basis?

**Comment by bjrn** [comment]
In order to conditionally show/hide header on individual screens of a stackNavigator, you need to change its `headerMode` to `screen`: 

```
const SettingsNavigator = StackNavigator(
  routeConfigs,
  {
    initialRouteName: 'Settings',
    headerMode: 'screen', // <- needed for being able to toggle header visibility
      navigationOptions: { header: { backTitle: null } },
    }
)
```

**Comment by nonameolsson** [comment]
@bjrn Thanks! But how about just overriding individual settings? Like overriding left icon on different screens?

**Comment by grabbou** [comment]
@nonameolsson in that case, make a function: `navigationOptions: (_, headerConfig) => ({ ...headerConfig, newProperty: false })`. Params are not merged and you have to do it yourself.

**Comment by Kishanjvaghela** [comment]
@grabbou It is not working. Can you please explain in detail how to do this?

**Comment by ayalpani** [comment]
@grabbou @Kishanjvaghela yes, more explanation would be great. Placing the function inside the screen's code does not have any effect.

**Comment by Kishanjvaghela** [comment]
This is work for me
```
UserListScreen.navigationOptions = {
  header: (navigation, defaultHeader) => ({
    ...defaultHeader,
    visible: false,
  }),
};

```
Just make function for header in inner screen that have navigation and defaultHeader parameters and destructor as shown in my code.

**Comment by jonnywyatt** [comment]
@Kishanjvaghela defaultHeader is undefined when I implement your code with 1.0.0-beta.9

**Comment by momirror** [comment]
"react-navigation": "^1.0.0-beta.11".

config global:
MainScreenNavigator.navigationOptions =
    (headerConfig) => ({
        title:'Demo',
        headerLeft:<View style={{backgroundColor:'red',width:10,height:10}}></View>,
        ...headerConfig.navigationOptions
    });

config in a separate page:
static navigationOptions = ({navigation,screenProps}) => ({
        title:'haha',
        headerLeft:<View style={{backgroundColor:'green',width:10,height:10}}></View>,
});

**Comment by TheOverRide** [comment]
@momirror Thanks man, your code got the job done
