### ISSUE TITLE
android the tabbar not show icon

### ISSUE THREAD

**Issue by ibmsoft** [react-community/react-navigation#516]
the tabbar in android not show icon

i follow the example
`cd react-navigation
npm install
cd examples/NavigationPlayground
npm install
cd ../..
react-native start
cd examples/NavigationPlayground
react-native run-ios # ignore packager starting error
react-native run-android # ignore packager starting error`

the ios platform tabbar show the icon but the android not show icon

and 
i follow the doc  on reactnavigation.org
 find  hidden the header when use visible
i use header：{visible：false} no effect on ios

**Comment by grabbou** [comment]
You have to set [`showIcon`](https://reactnavigation.org/docs/navigators/tab#tabBarOptions-for-TabBarTop-default-tab-bar-on-Android) to `true` on Android, as it's false by default.

**Comment by AaronVasquez** [comment]
Does this not work for TabBarBottom on Android?

**Comment by EsdrasEtrenne** [comment]
I am getting the same issue. Doesnt work for TabBarBottom android for me

**Comment by nihp** [comment]
@EsdrasEtrenne  I need to display the footer images on tab navigator. How can I display it? I tried with Image source = {image.png} but it did not help yet.  

Also, I have set showIcon: true, it also not working. Kindly provide your inputs

**Comment by EsdrasEtrenne** [comment]
I think you would need to update the tabBarIcon key in navigationOptions to return an image component with the correct image source. I have it set up to return an icon component above
