### ISSUE TITLE
Pass custom props to stack navigator screen

### ISSUE THREAD

**Issue by jamesone** [react-community/react-navigation#518]
I'm wondering how can do this via the stack navigator - I know there are ways around it, but there are some specific use cases in our app which it'd be handy for.

E.g I'd expect it to work like: 
```js
const ModalStack = StackNavigator({
  ProfileLayout: {
    screen: ProfileLayout,
    options: {
       props: {
         isMyProfile: true,
        ... Custom props specific to the profilelayout route
       }
    }
  },
  OtherProfileLayout: {
    options: {
       props: {
         isMyProfile: false,
        ... Custom props specific to the OtherProfileLayout route
       }
    }
   }
```

Is this possible? Can we make it possible if not?

**Comment by grabbou** [comment]
You can use [`params`](https://reactnavigation.org/docs/intro/headers#Configuring-the-Header) for that to pass screen-specific config. For other things, something like redux's connect should do the trick.
