### ISSUE TITLE
Conditional tabs in TabNavigator

### ISSUE THREAD

**Issue by henry-whil** [react-community/react-navigation#519]
Is it possible to hide a tab conditionally?  I know I can just create a new TabNavigator for each platform but would be nice to have something like the example below.

```
TabNavigator({
  OneScreen: {screen: OneScreen},
  TwoScreen: {screen: TwoScreen, visible: Platform.OS === 'ios' ? true : false},
  ThreeScreen: {screen: ThreeScreen}
})
```

**Comment by grabbou** [comment]
I think you could do this instead:
```js
TabNavigator({
  ...(Platform.OS === 'ios' ? { TwoScreen: { screen: TwoScreen } } : {}),
  OneScreen: {screen: OneScreen},
  ThreeScreen: {screen: ThreeScreen}
})
```

**Comment by amanthegreatone** [comment]
Hi,

I want to know if its possible to do conditional rendering of tabs based on some variable in the app state.

My structure is as follows:
Drawer with 2 items.
navigator.js
```
const DashboardNavigator = StackNavigator({
  Dashboard: {
    screen: DashboardContainer,
    navigationOptions: baseNavigationOptions,
  },
});

const TasksNavigator = StackNavigator({
  TaskList: { screen: TaskListTabNavigator },
  TaskDetails: { screen: TaskDetailsTabNavigator },
});

const drawerStackRoutes = {
  Dashboard: { screen: DashboardNavigator },
  Tasks: { screen: TasksNavigator },
};

export const MyDrawerNavigator = DrawerNavigator(drawerStackRoutes, drawerStackOptions);
```

Tasks is another stack with 2 TabNavigators (TaskList & TaskDetails).

The user will navigate to the TaskDetails from one of the tasks in the TaskList. What I want to implement is that based on the kind of tasks there are in task list, the task details should have different set of tabs. 

Not able to figure out how to make this happen. Any help will be appreciated!

**Comment by amanthegreatone** [comment]
Ok, so what I have done is to define all possible TaskDetails navigators (TaskDetails1, TaskDetails2, TaskDetails3) and then navigate to the appropriate TaskDetails(x) based on the task. Is there any other way than defining multiple navigators?

**Comment by ntkzwane** [comment]
@grabbou this does not work if the tab's visibility is dependent on the navigation state params or initialProps. Is there any intention to add a `visible` property to the navigator's navigation options, as suggested by @henry-whil?

**Comment by alenia** [comment]
I agree with this. it would be especially nice to be able to hide tabs based on redux state (e.g. based on feature flags coming back from the server)

**Comment by ballenwillis** [comment]
Is there a solution to this yet? I'm in the same situation as @amanthegreatone

**Comment by bramski** [comment]
Thanks for this posting, with much googling and poking around I found a solution for this.

If you want to get redux state into the rendered tabs then you need to provide an outer component to the TabNavigator.  The difficulty with this solution though, is that the TabNavigator is re-instantiated if you re-render.  This can cause difficulties down the line.

```
class HomeTabNavigation extends React.Component {
  state = {
    showPrivilegedTab: false,
  };

  componentWillReceiveProps(nextProps) {
    // calculate showPrivilegedTab
    this.setState({ showPrivilegedTab });
  }

 // prevent re-renders by unimportant props
  shouldComponentUpdate(nextProps) {
    // calculate showPrivilegedTab
   return showPrivilegedTab !== this.state.showPrivilegedTab
  }

  render() {
    const configuredTabs = {
      MyTab1: Tab1Config,
      ...(this.state.showPrivilegedTab && { MyPrivilegedTab: PrivilegedTabConfig }),
      MyTab3: Tab3Config
    }

    const TabsComponent = TabNavigator(configuredTabs, tabNavigatorOptions);
   return (<TabsComponent />);
  }

// use mapStateToProps to get your redux variables in the component.
```

This works for react-navigation 1.5.x.
