### ISSUE TITLE
Help: Navigate from nested navigation

### ISSUE THREAD

**Issue by ElliottJRo** [react-community/react-navigation#52]
Hi all, I am trying to setup navigation in my app but having some trouble navigating from nested views. Im pretty sure im doing this wrong since I cant go from a 2nd level view to another 2nd level view in another Navigator. 

Basically I want to go from LoginView to MainView somehow but keeping WelcomeNavigator separate from HomeNavigator (mostly for organization purposes but also to clear the stack when transitioning from !isLoggedIn screen to isLoggedIn screen)

Can someone point me in the right direction? Thanks! 

```
const WelcomeNavigator = StackNavigator({
  Login: { screen: LoginView},
  Register: { screen: RegisterView}
}, {
  headerMode: 'none'
});

const HomeNavigator = TabNavigator({
  Main: {screen: MainView },
  Settings: { screen: SettingsView}
});

const MasterNavigator = StackNavigator({
  Welcome: { screen: WelcomeNavigator },
  Home: { screen: HomeNavigator }
},
{
  headerMode: 'none'
});
```

**Comment by satya164** [comment]
I don't think this will work. What do you expect it to do?

**Comment by satya164** [comment]
> I expect it to go from one nested view to another nested view ideally hahah

What'll animation do you expect?

> Can I use a custom router to go from one path to another using absolute keys instead of having local keys? eg: /welcome/login to /home/main or something

Use `navigation.dispatch` to dispatch a nested 'Reset' action which does 'Navigate' after the reset

**Comment by ericvicenti** [comment]
We have an advanced feature that may help here: you can create a nested navigate action. In your case, it would look like this:

```js
this.props.dispatch({
  type: 'Navigate',
  routeName: 'Home',
  action: {
    type: 'Navigate',
    routeName: 'Main',
  },
});
```

**Comment by ElliottJRo** [comment]
@ericvicenti ahaha it works!! So when I dispatch the navigate action its caught by the parent `Navigator` or does it look first in sibling views and then passes to the parent?

One thing I did notice is: I don't see a second `Navigation Dispatch` in console log, is this expected?

**Comment by ericvicenti** [comment]
It is caught by the parent navigator because the action's routeName matches the route config name for that navigator. It is expected that there is only one action logged, because only one action happens at the top level.

I'm closing this out for now, feel free to file more issues as you come across them. If you have a chance, consider improving the docs to help make this feature more apparent!

**Comment by temitope** [comment]
@ericvicenti that was extremely helpful, but i had to use
`this.props.navigation.dispatch` vs `this.props.dispatch` for any future readers.

**Comment by mateofd** [comment]
Hi Everyone,
@ericvicenti's comment on Jan 28 was crucial for me to make the nested navigation work. 
However, I'm having trouble passing parameters to the target route in the child navigator.
Any ideas?

Thanks!

**Comment by githubmss** [comment]
facing similar issue , so i posted my question here , hope you can help me out in this issue .Please have a look at this link 
https://stackoverflow.com/questions/44801667/navigate-to-root-screen-from-nested-stack-navigator?noredirect=1#comment76584210_44801667

**Comment by dmr07** [comment]
@ericvicenti There is a memory leak with your solution. Under the performance monitor, RAM went up ~40mb every time that command is called.

**Comment by ericvicenti** [comment]
Could you show a full example of the memory leak? Hard to tell exactly what you're doing
