### ISSUE TITLE
Calling setParams in a nested navigator sets the params on the wrong screen

### ISSUE THREAD

**Issue by hasLandon** [react-community/react-navigation#520]
Currently, my setup is that I have a `StackNavigator`, with a `TabNavigator` route, that has nested `StackNavigators` for each of the tabs like so:

* Root (StackNavigator)
  * Home (TabNavigator)
    * Dashboard (StackNavigator)
      * Dashboard (regular view)
    * Feedback (StackNavigator)
      * Feedback (regular view)
    * Settings (StackNavigator)
      * Settings (regular view)
  * Login (regular view)
  * Startup (regular view)

Currently, when I call `this.props.navigation.setParams({ test: 'me' }` in the `Settings` view's `componentWillMount`, I'm finding that that the param is actually getting added to the `Dashboard` view's params instead of the `Settings` view. I think this may have to do with `Dashboard` being the initial route for the `Home` navigator. This is on version `1.0.0-beta.6`.

Here's the resulting state after the setParams call is made:

```
{
   index:1,
   routes:[
      {
         routeName:'Startup',
         key:'Init'
      },
      {
         type:'Navigation/NAVIGATE',
         routeName:'Home',
         params:undefined,
         action:undefined,
         routes:[
            {
               index:0,
               routes:[
                  {
                     routeName:'Dashboard',
                     key:'Init',
                     params:{
                        test:'me'
                     }
                  }
               ],
               key:'Dashboard',
               routeName:'Dashboard'
            },
            {
               index:0,
               routes:[
                  {
                     routeName:'Feedback',
                     key:'Init'
                  }
               ],
               key:'Feedback',
               routeName:'Feedback'
            },
            {
               index:0,
               routes:[
                  {
                     routeName:'SettingsView',
                     key:'Init'
                  }
               ],
               key:'Settings',
               routeName:'Settings'
            }
         ],
         index:0,
         key:'id-1488328251539-0'
      }
   ]
}
``` 

My root navigator is set up like so:

```
import React, { PropTypes } from 'react';
import { connect } from 'react-redux';
import { addNavigationHelpers } from 'react-navigation';

import AppRootNavigator from './appRootNavigator';

const AppWithNavigation = props => (
  <AppRootNavigator
    navigation={addNavigationHelpers({
      dispatch: props.dispatch,
      state: props.navigationState,
    })}
  />
);

AppWithNavigation.propTypes = {
  dispatch: PropTypes.func,
  navigationState: PropTypes.object,
};

const mapStateToProps = state => ({
  navigationState: state.navigation,
});

export default connect(mapStateToProps)(AppWithNavigation);

```

**Comment by jhhayashi** [comment]
Check out #80

**Comment by hasLandon** [comment]
@jhhayashi Good point, they're probably related. Sadly the issue still exists in the new release :(

**Comment by dmhood** [comment]
related to https://github.com/react-community/react-navigation/issues/296 as well

**Comment by Himujjal** [comment]
I think the solution to your problem is [#143 comment 324960178 ](https://github.com/react-community/react-navigation/issues/143#issuecomment-324960178). Check out the problem and the solution which I used using Redux. Although there is no inbuilt solution to this problem. As a workaround Redux will surely help you here. Its a simple solution with a few lines of extra code.
