### ISSUE TITLE
How can I track currentRoute in DrawerNavigator using contentComponent

### ISSUE THREAD

**Issue by RobertSheaO** [react-community/react-navigation#521]
Right now I'm using redux to update the `currentRoute` in my global reducer and then checking it against the route name when I loop through `this.props.navigation.state.routes`. Am I missing an easy way to determine the current route so I can use `activeBackgroundColor`? Also, how can I access activeBackgroundColor when I use `contentComponent`?

**Comment by satya164** [comment]
https://github.com/react-community/react-navigation/blob/master/src/views/Drawer/DrawerNavigatorItems.js
