### ISSUE TITLE
How to get available screen dimensions under TabNavigator screens

### ISSUE THREAD

**Issue by JLLLinn** [react-community/react-navigation#522]
React native provides the dimensions api to get the screen width and height, but the available height with tabs and header is shorter, is there anyway to get the available screen height in this case?

**Comment by arnsa** [comment]
Is the header and tab bar height changing? If not, you could just subtract their height from the total height.

**Comment by JLLLinn** [comment]
Thanks for replying, how would I get the header and tab bar height?

**Comment by arnsa** [comment]
Well, in my case, I've specified the height for both header and tab bar, so I already know what their height is.

Another option is [this.](http://stackoverflow.com/questions/33770901/how-to-get-size-of-a-component-in-react-native)

**Comment by JLLLinn** [comment]
Yes thanks, the link seems to help... it would still be great to have an officially supported API for this.

**Comment by satya164** [comment]
https://facebook.github.io/react-native/docs/view.html#onlayout
https://facebook.github.io/react-native/docs/nativemethodsmixin.html#measure
