### ISSUE TITLE
Code broken on master branch of react-native

### ISSUE THREAD

**Issue by coodoo** [react-community/react-navigation#523]
I was playing with the `SimpleStack.js` example from the playground, it crashed after clicking the button while navigating to next screen, with error message 
```this.updater.enqueueCallback is not a function```.

Detailed trace messages here:

```
ExceptionsManager.js:63
this.updater.enqueueCallback is not a function
handleException @ ExceptionsManager.js:63
handleError @ InitializeCore.js:114
reportFatalError @ error-guard.js:44
guard @ MessageQueue.js:48
callFunctionReturnFlushedQueue @ MessageQueue.js:107
(anonymous) @ debuggerWorker.js:71

ExceptionsManager.js:71
Unhandled JS Exception: this.updater.enqueueCallback is not a function
reactConsoleErrorHandler @ ExceptionsManager.js:71
console.error @ YellowBox.js:62
logIfNoNativeHook @ RCTLog.js:38
__callFunction @ MessageQueue.js:244
(anonymous) @ MessageQueue.js:108
guard @ MessageQueue.js:46
callFunctionReturnFlushedQueue @ MessageQueue.js:107
(anonymous) @ debuggerWorker.js:71
```

I traced back all commits from react-native and found that everything worked great with react-navigation before `Feb. 17`, after that `navigate()` started causing above mentioned issues.

Not sure if this is a regression issue but might worth having a look into for that next release of react-native is just around the corner.

Current has following installed

```
"react": "^15.4.2",
"react-native": "git+https://github.com/facebook/react-native.git#master",
"react-navigation": "~v1.0.0-beta.6",
```

**Comment by coodoo** [comment]
Ended up this might be a false alarm, just tested again with master branch of both `react` and `react-native`, and everything is working great, closing it.

```
"react": "^16.0.0-alpha.3",
"react-native": "git+https://github.com/facebook/react-native.git#master",
```

**Comment by gaving** [comment]
This error is driving me mad, even on the latest stables.

Anyone arriving here have any idea what is up? Trying to link it back to some redux state dispatches but really having no luck nailing it down.
