### ISSUE TITLE
TabNavigator in StackNavigator Back button brings first tab screen

### ISSUE THREAD

**Issue by wkgalla** [react-community/react-navigation#526]
If first tab is NOT focused, pressing back button in navbar or calling goBack() navigates to first tab.

Ideally, it should navigate to previous screen in stack.

**Comment by markusguenther** [comment]
Can confirm that.

**Comment by nico1510** [comment]
This is intended behaviour which can be customized by setting the `backBehaviour` property ([see docs](https://reactnavigation.org/docs/navigators/tab#TabNavigatorConfig)).

**Comment by wkgalla** [comment]
Set `backBehavior: 'none'` in TabNavigatorConfig as suggested by @nico1510 
Thanks Beck!

**Comment by rtrann** [comment]
just to be clear, as it isn't clear in the docs where this code would go. This is how you would do this:
```
const Tabs= TabNavigator({
  Tab1: {screen: Screen1},
  Tab2: {screen: Screen2},
  Tab3: {screen: Screen3}
  }, {
    tabBarOptions: {
  },
  backBehavior: 'none',
});
```
