### ISSUE TITLE
Edge case: is there a better way to render iOS bar as a block?

### ISSUE THREAD

**Issue by thurt** [react-community/react-navigation#528]
I'm using StackNavigator.

when navigationOptions header `visible: false`
![screen shot 2017-03-01 at 8 55 05 am](https://cloud.githubusercontent.com/assets/8955144/23463916/42771e80-fe61-11e6-86cd-6677b84d2668.png)
(iOS status bar is rendered on top of content & w/ transparent bg)

I want iOS status bar to render as block with white bg, but not have any of the other navigation header parts. **Is there a better way than this solution?**:
```javascript
    navigationOptions: {
      header: {
        /*
          (thurt) these styles are to keep the ios status bar rendering as a block w/ white background (per Style Guide)
          this is the only way I have figured out so far. There could be a better way to do this.

           basically it hides all elements which are not the ios status bar.
           I'm not able to use the react-navigation header property `visible: false` here because that makes the
           ios status bar no longer render as block and its background becomes transparent.
        */
        style: { height: 0 },
        titleStyle: { height: 0 }
        /**/
      }
    }
```
result (it does work):
![screen shot 2017-03-01 at 8 50 12 am](https://cloud.githubusercontent.com/assets/8955144/23463926/4a3e2208-fe61-11e6-9f5f-25ec2222d643.png)

**Comment by grabbou** [comment]
I think you can pass [`cardStyle`](https://reactnavigation.org/docs/navigators/stack#StackNavigatorConfig) marginTop for the Navigator that doesn't have header. Otherwise, on-per screen basis `marginTop` should be fine.

I wouldn't follow your solution as its still rendering an invisible header, which is rather bad.
