### ISSUE TITLE
Routing flow with redux

### ISSUE THREAD

**Issue by jkomyno** [react-community/react-navigation#529]
I have read the source code of the [official Redux navigation example](https://github.com/react-community/react-navigation/tree/master/examples/ReduxExample), but I didn't find what I was looking for. Basically what I want to do is navigating to another route when I receive a correct token from a server. The redux stuff is already configured in my app, and I can dispatch actions with no problems at all.

But, I'd like to know what's the best way to handle this problem, using redux and react-navigation. I guess that I have to perform something like 

```javascript
  if (action.type === 'JUMP_TO_TAB') {
    return { ...state, index:0 }
  } else {
    return TabBar.router.getStateForAction(action,state)
  }
```
somewhere, but configured for StackNavigator.

Here's my commented [example gist](https://gist.github.com/jkomyno/ef32cbff4c95b5e2c2fce7b7e4587a9f). I hope this issue can also be useful to many others.

**Comment by RobertSheaO** [comment]
You can use `dispatch({ type: 'Navigation/NAVIGATE', routeName: 'YourRouteName' })`, or simply `this.props.navigation.navigate('routeName')`

Here's a sample from my app.

```JS
class HistoryScreen extends PureComponent {
render() {
    render(
      <HistoryList
        onViewDetails={this.props.onViewDetails}
      />
    );
}

const mapStateToProps = createStructuredSelector({});

function mapDispatchToProps(dispatch) {
  return {
    onViewDetails: (txId) => {
      dispatch({ type: 'Navigation/NAVIGATE', routeName: 'Details', params: { txId } });
    },
    dispatch,
  };
}

export default connect(mapStateToProps, mapDispatchToProps)(HistoryScreen);
```

**Comment by jkomyno** [comment]
Thanks for the answer, but it didn't work for me. Please take a look at the update gist, I've added the actions.js file related to my login reducer. (Watch out for the comment at the end)

https://gist.github.com/jkomyno/ef32cbff4c95b5e2c2fce7b7e4587a9f

**Comment by grabbou** [comment]
Mind also sharing an example of your reducer?

**Comment by RobertSheaO** [comment]
@jkomyno, you should try adding `redux-logger` to see if your actions are getting called.

In the file where you have your `combineReducers` call.

```JS
import logger from 'redux-logger';
...
const store = createStore(
  combineReducers({
    // Your reducers here
  }),
  initialState,
  applyMiddleware([logger])
);
```

**Comment by jkomyno** [comment]
@grabbou Hi Mike, I've updated the gist with the login reducer and the root reducer (where I use combineReducers).

@RobertSheaO Hey Robert, thanks for the tip I can use it to remove some console.log(), but as I have already mentioned I'm sure that the login actions work correctly. However, I could use redux-logger to discover if "Navigation/NAVIGATE" gets called.

**Comment by jkomyno** [comment]
Basically I'm looking for the cleanest and most proper way of having something like:

```javascript

actionTypeHappened('RESPONSE_LOGIN')
  .then((response) => {
    dispatch(
      { type: 'Navigation/NAVIGATE', routeName: 'Details', params: { response}}
    )
  })

```

**Comment by arnsa** [comment]
But isn't NAVIGATE going to push a route onto the stack? While JUMP action does what it says - it jumps without pushing anything to the stack.

**Comment by jkomyno** [comment]
Is there any update on this one guys, please?

**Comment by wilomgfx** [comment]
Pretty much my use case as well. Being able to JUMP to already opened scenes/views without adding to the stack. Exactly like a tab bar that already uses the JUMP action.

**Comment by goblinbr** [comment]
Hi @jkomyno 

Check out my repo:
https://github.com/goblinbr/manager-react-native-app

It's working with react-navigation and redux.

Here are the files that contains the react-navigation stuff:
https://github.com/goblinbr/manager-react-native-app/blob/master/src/AppWithNavigationState.js (used by App.js)
https://github.com/goblinbr/manager-react-native-app/blob/master/src/reducers/AppNavigatorReducer.js
https://github.com/goblinbr/manager-react-native-app/blob/master/src/actions/navigateTo.js (used by AuthActions.js and EmployeeActions.js)

**Comment by chauthai** [comment]
@goblinbr Thanks a lot for pointing to your repo! It really helped me a lot to integration react-navigation into my existing project.
You should submit a pull request to link your repo as an example in the docs.

**Comment by jkomyno** [comment]
Hi @goblinbr, sorry but I didn't notice your answer. Tomorrow I'm going to test your application and possibly embedding the same functionality in my app.

In the mean time, thank you for your response!

**Comment by mattharrison** [comment]
Thanks @goblinr for sharing. I would like to add buttons to the navigation header that call redux dispatch. Do you (or anyone) happen to know how to get access to the props from within `nagivationOptions`?

**Comment by jakallergis** [comment]
Great example @goblinbr !!

**Comment by daose** [comment]
@mattharrison 

You can get it in the route configs:

```javascript
const AppNavigator = StackNavigator({
  Drawer: {
    screen: Drawer,
    navigationOptions: {
      title: 'Parkr'
    }
  },
  Login: {
    screen: Login,
    navigationOptions: {
      title: 'Login'
    }
  }
}, {
  navigationOptions: {
    header: props => ({
      left: <Hamburger {...props} />
    })
  }
});
```

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
