### ISSUE TITLE
drawer label throwing an error

### ISSUE THREAD

**Issue by despreston** [react-community/react-navigation#530]
Ive got a a drawer navigator with a bunch of StackNavigator's as screens. Inside each of those Stacknavigator's I have a navigationOptions object which looks like this:

```
{
  drawer () => ({ label: 'whatever' })
}
```

I have a contentComponent in my DrawerNavigator. Inside the contentComponent I would like to get the label for for the current screen ( getLabel() ). When I do this, it throws an error on line 53 of DrawerSidebar.js: focused is undefined.

My drawer.label is merely a string, there is no function. What is going on? I will keep debugging but this does not seem correct to me.

**Comment by Blackscr33n** [comment]
I think you are missing a `:`
Like
```{
drawer: () => (...)
}```

**Comment by despreston** [comment]
Sorry that was a typo in the issue description. with that fixed its still throwing the error.

**Comment by grabbou** [comment]
getLabel requires an argument of this shape https://github.com/react-community/react-navigation/blob/master/src/views/Drawer/DrawerView.js#L20. The error you are getting says internal implementation was unable to access focused property on an undefined object. See how it's called in default conentComponent.
