### ISSUE TITLE
Error on navigating back using default back button, from child stack/tab navigator

### ISSUE THREAD

**Issue by rimzici** [react-community/react-navigation#5301]
### Current Behavior

Having a `root stack navigator` with screens
1. Stack
2. Tab
3. Normal Component

- Moved from root nav to screen(1 or 2), then trying to return by pressing the default back button on the nav header. It crashes with an error.

**NOTE**
- Happens only, when returning back from a screen that is either stack/tab nav.
- and a setState is done inside the `onNavigationStateChange` method.
- and `screenProps` is passed to the navigator container component.

- No issues on navigating back and forth a normal component screen.

![simulator screen shot - iphone 5s - 2018-11-28 at 21 13 40](https://user-images.githubusercontent.com/16771765/49163507-3f061b00-f353-11e8-91a8-f3412d67b2a3.png)

### Expected Behavior

- Must be able to navigate back and forth, root and child navigators.

### How to reproduce
[Demo](https://github.com/rimzici/RNavigation-v3)

Steps:

- Press `go to stack` and try returning back.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.0.2
| react-native     | 0.57.7
| node             | v10.13.0
| yarn      | 1.7.0

Please correct me if I am doing it the wrong way.
Thanks!

**Comment by abn-volk** [comment]
I've got the same issue. Here's a snack from @rimzici's example: https://snack.expo.io/@jibi/null-navigation-state

**Comment by brettdh** [comment]
@rimzici THANK YOU I'm seeing this too after upgrading to v3 and I was having a nightmare time trying to reproduce it on Snack.

Odd that, in @abn-volk's snack, the error shows up as `e.state` rather than `navigation.state` - but maybe that's just `navigation` being minified to `e` (as opposed to an entirely different variable). Is there a way to disable minification on Snack?

**Comment by brettdh** [comment]
Here's my snack reproducing the same error, about as close to my actual app usage while still being (relatively) minimal: https://snack.expo.io/@brettdh/react-navigation-repro-example-v3

**Comment by nhannah** [comment]
Having the same issue.

**Comment by brentvatne** [comment]
won't have time to look at this for a bit as i'm busy at the moment and this is a fairly niche bug, but thank you @rimzici and @brettdh for providing so much information! if you want to also try to figure out a fix it'd be much appreciated

**Comment by rimzici** [comment]
Hi,
My initial inference: [Referring to my sample]

It is clear that change in `screenProps` allows an additional re-render of the Navigator. allowed in [here](https://github.com/react-navigation/react-navigation-core/blob/master/src/navigators/createNavigator.js#L37)

Following that re-render what I could see happening is, for the child stack navigator[(StackHome)](https://github.com/rimzici/RNavigation-v3/blob/master/App.js#L111) the method [getChildNavigation](https://github.com/react-navigation/react-navigation-core/blob/master/src/getChildNavigation.js#L16) is called. Which I do not see happening if screenProps has not changed(no re-render). And inside this method first [line](https://github.com/react-navigation/react-navigation-core/blob/master/src/getChildNavigation.js#L17) which gets the current children, does [removes](https://github.com/react-navigation/react-navigation-core/blob/master/src/getChildrenNavigationCache.js#L11) the cache key, that is the child stack navigator(StackHome) which is the root cause of the issue, that results `navigation` to go undefined [here](https://github.com/react-navigation/react-navigation-core/blob/master/src/getChildNavigation.js#L83)

Solution:

- If the cache key is not removed I see the current issue disappears but can cause other problems.
so may be some conditional check before removing could help.
- Or not calling the method `getChildNavigation` from a screen that we have moved/navigated back(child stack navigator(StackHome)), can also solve the issue.

**Comment by rimzici** [comment]
@brentvatne Please have a look at the [change](https://github.com/react-navigation/react-navigation-core/pull/25). Hope it does not break anything else.

**Comment by rimzici** [comment]
> Is there a way to disable minification on Snack?

@brettdh : sorry, not sure about that. But in prod. we could use sourcemap to backtrace though :)

**Comment by brentvatne** [comment]
thank you for that @rimzici! I will do a release during the week
