### ISSUE TITLE
DrawerNavigator: unable to scroll through Items

### ISSUE THREAD

**Issue by Blackscr33n** [react-community/react-navigation#531]
Hey!

As mentioned in the title I am unable to scroll through my list of Screens in the DrawerMenu.

Is there a way I can achieve this? 
Couldn't find an option for.

![image](https://cloud.githubusercontent.com/assets/6410789/23474526/53f0a6e2-feb4-11e6-8b40-0ad6f641fe87.png)

**Comment by grabbou** [comment]
Oh, looks like default contentComponent for Drawer doesn't use `ScrollView` which makes it impossible to scroll. 

For now, what you can do is:
1) copy the contents of [the file](https://github.com/react-community/react-navigation/blob/master/src/views/Drawer/DrawerNavigatorItems.js) into your source code
2) replace container `View` with `ScrollView`
3) pass `contentComponent` to `DrawerConfig`

Generally a quick glance at the available solutions to that problem on Android reveals that it's scrollable when content is too big. 

I'd accept a pull request for that. Please test that it has no difference when there are less items on screen.

**Comment by satya164** [comment]
It's already exported, so it's just `contentComponent: props => <ScrollView><DrawerNavigation.Items {...props} /></ScrollView>`

**Comment by Blackscr33n** [comment]
Thanks both for your reply!

I thought it would be something with `contentComponent`
Thanks!

I'll try it.

Greets

**Comment by grabbou** [comment]
@satya164 neat thing!

**Comment by Blackscr33n** [comment]
May not a bad idea to add it to the docs as example?

**Comment by grabbou** [comment]
If you feel like sending PR - go ahead!
