### ISSUE TITLE
Navigate to already opened Routes

### ISSUE THREAD

**Issue by wilomgfx** [react-community/react-navigation#533]
Heres what i mean / use case.

I am using redux and react-navigation. Instead of popping some of the routes, i keep them opened by just navigating to my Home route.

This way i could (currently trying to make it work) navigate back to the Scene/component and keeping its state and the webview active. Kinda like the TabBarNavigator.

Is it possible ? Currently im trying to route by its route index, its animating in but closing immediately.

I simply dispatch a custom action like so

```javascript

//normal switch statement for reducers
switch(type){
 case someActionType:
   return {
        ...state,
        ...action.payload
      }
 default:
      return AppNavigator.router.getStateForAction(action, state)
}
```

**Comment by michaelduminy** [comment]
Related: #370

**Comment by wilomgfx** [comment]
Its related, but we would still love help with #370
