### ISSUE TITLE
disable back history for specific scene

### ISSUE THREAD

**Issue by zwenza** [react-community/react-navigation#534]
hey first of all i want to thank all the contributors for this awesome react-native navigation library. Thanks for your hard work 👍 

i have a question: is there a way to navigate to a scene without saving that i was actually at this scene? 

my specific case is that i have a scene to select articles. if i select a article i come back to the order screen where i see all selected articles. But my problem is is that when i press back in the order screen i will land at the article-scene because this was the scene before this.

i simply want to ignore the opening of the article scene in the navigator. sadly i didn't find any way in the docs yet.
is there any way i can do this?

**Comment by grabbou** [comment]
Hey,

What you can do is you can specify your own `left` component for that particular route and handle `onPress` with `reset` action. 

Let's assume your stack is A, B, C, D. You are on "D" and want to go back to B on back press and skip C. 

Here's another issue you'll find an answer: #538
