### ISSUE TITLE
DrawerNavigator items doesn't show when contentComponent added 

### ISSUE THREAD

**Issue by mgorabbani** [react-community/react-navigation#536]
When i remove `contentComponent:({navigation})=> <DrawerContent navigation={navigation} routes={DrawerRoutes} />`
this code the menu show up. 

My Code
```
const DrawerRoutes = {
  Single: {
    screen: single,
  },
  SecB: {
    screen: secb,
  }
}

const RouteConfigs = {
  contentComponent:({navigation})=> <DrawerContent navigation={navigation} routes={DrawerRoutes} />,
}

const App = DrawerNavigator(DrawerRoutes,RouteConfigs);
```

**Comment by grabbou** [comment]
Mind sharing `DrawerContent` file?

**Comment by RobertSheaO** [comment]
Is this syntax supported? I've seen it around, but when I tried it, it never works.

```JS
contentComponent: ({ navigation }) => <DrawerContent navigation={navigation} routes={DrawerRoutes} />
```

Mine looks like this.

```JS
import DrawerComponent from '../components/DrawerComponent'
...
contentComponent: DrawerComponent
```

Then, inside DrawerComponent

```JS
const { navigate } = this.props.navigation;
const { routes } = this.props.navigation.state;
```

**Comment by grabbou** [comment]
> Is this syntax supported? 

Yeah. JSX tags are desugared to `React.createElement`. The first argument can be a valid React Component which is either a class or a function. In other words, you could also do `({ props }) => <DrawerComponent {...props} />`.

**Comment by RobertSheaO** [comment]
@grabbou, I understand that; however, it doesn't work for me for some reason at that point in the code. Here's a direct snippet of my code.

```JS
import { DrawerNavigator } from 'react-navigation';
import { Dimensions } from 'react-native';
import SideDrawer from '../../components/SideDrawer';
import Home from '../Home/connect';
import Login from '../Login/connect';

const routes = {
  Home: { screen: Home, navigationOptions: { title: 'Home' } },
  Login: { screen: Login, navigationOptions: { title: 'Login' } },
};
const options = {
  initialRouteName: 'Login',
  order: ['Home', 'Login'],
  contentComponent: SideDrawer,
  drawerWidth: Dimensions.get('window').width - 119,
  style: {
    paddingTop: 0,
  },
};

const AppRoutes = DrawerNavigator(routes, options);

export { AppRoutes };
```

And my a boiled down version of my SideDrawer.

```JS
import React, { PureComponent } from 'react';
import { connect } from 'react-redux';
import { createStructuredSelector } from 'reselect';

class SideDrawer extends PureComponent {
  render() {
    ...
    return (
      // JSX code
    )
  }
}

const mapStateToProps = createStructuredSelector({});

function mapDispatchToProps(dispatch) {
    dispatch,
  };
}

export default connect(mapStateToProps, mapDispatchToProps)(SideDrawer);
```

**Comment by mgorabbani** [comment]
@grabbou  here it is
```
import React, {Component} from 'react'
import {View,Text,
  TouchableNativeFeedback,
  TouchableOpacity,
  TouchableHighlight
} from 'react-native'
import Icon from 'react-native-vector-icons/Octicons';
export default class DrawerContent extends Component {
  constructor(props) {
  super(props)
}
  render(){
    return(
      <View style={{elevation: 10}}>
        <View style={{height:200,backgroundColor:'#6ABFA0'}}>
          <View style={{marginTop:50, alignItems:'center'}}>
            <Text style={{fontSize:30,fontFamily:'futurapt-bold',color:'#fff'}}>
              Daily Attendance
            </Text>
            <Text style={{fontSize:50,fontFamily:'futurapt-book',color:'#fff'}}>
              Sections
            </Text>
          </View>
        </View>
          </View>
    )
  }
}
```

**Comment by grabbou** [comment]
I couldn't reproduce it. Putting `DrawerContent` (as provided by you) and setting `contentComponent` makes the following: 
<img width="379" alt="screen shot 2017-03-02 at 10 34 45" src="https://cloud.githubusercontent.com/assets/2464966/23501360/de18a034-ff33-11e6-9581-199521b2efa2.png">
which I assume it's valid. I think you have to dig in deeper. Alternatively, try deleting entire `render()` method and replacing it with a simple `Text` to see if it works at all.

**Comment by mgorabbani** [comment]
this is my github repo [](https://github.com/mgorabbani/attendanceApp)

**Comment by mgorabbani** [comment]
i tried but did not work!

**Comment by satya164** [comment]
Can you please post a screenshot of what you mean by it doesn't work?

**Comment by mgorabbani** [comment]
i should see these menu under the drawer Header.  I only see one of these. not the both. 
![image](https://cloud.githubusercontent.com/assets/12911638/23503605/a12ea5fa-ff66-11e6-9ac1-393136d01d4c.png)
![image](https://cloud.githubusercontent.com/assets/12911638/23503676/de7415da-ff66-11e6-9dbe-84536dc96d04.png)

**Comment by satya164** [comment]
That looks right. `contentComponent` replaces the content of the drawer.

You need to render `<DrawerView.Items {...props} />` if you want the navigation items too.

**Comment by mgorabbani** [comment]
I don't understand how can i implement this! Sorry

**Comment by RobertSheaO** [comment]
@mgorabbani Inside your `DrawerContent` file, you need to import `DrawerView` from `react-navigation` and then pass props to it.

```JS
import React, { PureComponent } from 'react';
import { View } from 'react-native';
import { DrawerView } from 'react-navigation';

export default class DrawerContent extends PureComponent {
  render() {
    return (
      <View>
        <DrawerView.Items {...this.props} />
      </View>
    );
  }
}
```

P.S. Make sure `Items` is capitalized in `DrawerView.Items`

**Comment by mgorabbani** [comment]
Thanks!

**Comment by huiming1313** [comment]
@mgorabbani  
hi, is it possible to update your example app in github?
i'm doing the same things but in <DrawerView.Items {...this.props} /> gives me errors.

error is element type is invalid: expected a string...

**Comment by Makingweb** [comment]
@huiming1313 try this
```javascript
import React, { PureComponent } from 'react';
import { View } from 'react-native';
import { DrawerItems } from 'react-navigation';

class DrawerContent extends PureComponent {

  render() {

    return (
      <View>
        <DrawerItems {...this.props} />
      </View>
    );
  }
}

export default DrawerContent;
```

**Comment by pedrojioc** [comment]
@RobertSheaO I have tried to use DrawerItems, but I have not been able to set which send parameters in the component, right here <DrawerView.Items {... props} />

Thanks

**Comment by AGASampath** [comment]
@mgorabbani  if you can give your code
