### ISSUE TITLE
Right button is not work

### ISSUE THREAD

**Issue by musicode** [react-community/react-navigation#537]
I set router config with navigationOptions:

```js
StackNavigator({
    Home: {
        screen: xx,
        navigationOptions: {
            header: {
                style: {
                    backgroundColor: '#FF0000',
                },
                tintColor: '#FFF'
            }
        }
    }
})
```

then I set `navigationOptions` in Component, the right button is not work:

```js
static navigationOptions = {
    title: 'xxx',
    header: (navigation, defaultHeader) => {
        return {
            right: (
                <Button
                    title="Click to Alert"
                />
            )
        }
    },
}
```

But I want to set the backgroundColor and tintColor for one place, how to resolve it?

**Comment by satya164** [comment]
cc @grabbou 

I think we should make header items functions too ¯\_(ツ)_/¯

**Comment by musicode** [comment]
@satya164 
How to make a theme for all navigation header?

**Comment by RobertSheaO** [comment]
@musicode You don't have an `onPress` attribute on your button

**Comment by musicode** [comment]
@RobertSheaO `onPress` is not the reason

**Comment by spencercarli** [comment]
I believe this issue would have been fixed with the api change (`header: { style: {} }` -> `headerStyle: {}` for example)
