### ISSUE TITLE
Reset to screen in the middle of StackNavigator

### ISSUE THREAD

**Issue by nguyenhd0709** [react-community/react-navigation#538]
Hi, I'm new and I try to use react-navigation in my Android project instead of using default navigator of react-native, and I get the following problem: 

I got screen A is initRoute of stackNavigation, then I navigate to screen B. From screen B, I navigate 2, 3 steps, travel 2, 3 screens then I go to screen C. After that, I have 1 button in screen C which navigate to screen B, and when I press Back button, I want this will go back to screen A, instead of back to screen C at the present, I want new screen B will replace old screen B in route stack and clear all of the entire, is it possible ?.

RouteStack is: 
---- Screen A
------- Screen B
--------- Some screen
------------ Screen C -> press button
--------------- Screen B

What I want is: When press button in screen C, routeStack will have the following route: 
---- Screen A
------- Screen B
So when I press back and screen B this will go back screen A as expected.

As default navigator I use, I can get my goal by using replaceAtIndex().  I get stuck so long and hope someone can give me some solutions to resolve it.  
Thanks.

**Comment by grabbou** [comment]
> After that, I have 1 button in screen C which navigate to screen B

Instead of navigating to screen B (pushing screen B onto stack), you can navigate back to it (you already have it). You can do so by calling `reset` action with an array of routes. That will make your stack to be `[a, b]`.

[Here's](https://reactnavigation.org/docs/navigators/navigation-prop#Reset) docs on how to do it.

**Comment by nguyenhd0709** [comment]
Hello @grabbou, thanks for your response. I got this by using your guide. It's work as I expected.
Sorry but I have another question:
Like the example above: 
From screen C I navigate to D with custom params, in screen D I have one button that replaces screen D by another screen D, with params send from the previous screen D.  This params like data fetch, and this data will render different screen D. So the question is how can I replace new screen D, so when I press back it will back to screen C (not pushing new screen D to stack). I think I can get this by using reset action but I get stuck when getting all routes array with params I already use to navigate, if params not right, it'll getting a bug. Are there any solutions to get all routes array state in child component, or any solutions for my problem?

**Comment by evisong** [comment]
@grabbou excuse me but is the `reset` method still working? I read the doc https://reactnavigation.org/docs/navigators/navigation-prop#Reset but don't find it.

**Comment by douglasjunior** [comment]
`Reset` is a `Action`, see: https://reactnavigation.org/docs/navigators/navigation-actions#Reset

```javascript
import { NavigationActions } from 'react-navigation'

const resetAction = NavigationActions.reset({
  index: 0,
  actions: [
    NavigationActions.navigate({ routeName: 'Profile'})
  ]
})
this.props.navigation.dispatch(resetAction)
```

This code will replate the current state by the `Profile`, but the transition have no animation.

Is it possible to add animation in the Reset?

**Comment by jslz** [comment]
@douglasjunior heh, I seem to have a sort of opposite problem: I use reset OK but visually I see one by one all of the previously navigated to screens being popped off the stack. I don't want to see any of that, I want to just switch to the new place. Have tried various/random things like 'quiet', but no luck yet. :-)

```
navigationAction = NavigationActions.reset({
        index: 0,
        actions: [
          navigationAction = NavigationActions.navigate({
            routeName: action.routeEnum,
            params: Object.assign({
              transition: action.transition || null,
              quiet: true
            }, action.params)
          })
        ]
      });
```

**Comment by berkcoker** [comment]
I have the same issue @jslz

**Comment by xiaochanghai** [comment]
@douglasjunior thank you! I follow your code, it's work.

**Comment by erikvdplas** [comment]
@douglasjunior @jslz Any follow-up on achieving this behavior with just a single transition?

**Comment by igaidai4uk** [comment]
the world was so much better with the old deprecated navigator, so far I don't see any improvement

**Comment by douglasjunior** [comment]
Several fixes and improvements have been made in the latest releases, take a look https://github.com/react-community/react-navigation/releases

**Comment by igaidai4uk** [comment]
Thanks, but ... I can reset only to index: 0, and I see animation issues, which seems to me no one was able to resolve. 
This is so weird it is a default functionality.
