### ISSUE TITLE
Contents of  header has change offset 

### ISSUE THREAD

**Issue by guoliang1206** [react-community/react-navigation#539]
when first loading the app,the title and right button ,display on the left of the header and moved to center of header fastly.Anyone find this question and know how to handle this?

**Comment by satya164** [comment]
cc @grabbou 

could it be something due to the delay in `onLayout`?

**Comment by grabbou** [comment]
Yeah, probably, however I haven't experienced any issues because of that. `onLayout` was the only reasonable solution as far as I experimented with that. 

Mind posting a screen recording or/and steps to reproduce? Should be easily fixable.

**Comment by RobertSheaO** [comment]
I just posted about this same issue. This bug was introduced in beta.6 and I think it has to do with dynamically configuring width and converting the top nav area to using flexbox.

https://github.com/react-community/react-navigation/issues/553

**Comment by thorsonmscott** [comment]
I'm also seeing this issue and can confirm I wasn't seeing it before beta.6.  I'll grab a screen recording and upload tomorrow AM.

**Comment by guoliang1206** [comment]
![header bug](https://cloud.githubusercontent.com/assets/12846676/23538230/ab033496-000c-11e7-8599-731dbe3058c3.gif)

see this GIF
