### ISSUE TITLE
JUMP action?

### ISSUE THREAD

**Issue by arnsa** [react-community/react-navigation#541]
Hello,

I noticed that NavigationActions has no JUMP action, but it's implemented in StateUtils. Why is that so? I need JUMP action, because there seems to be no way to do it right now.

**Comment by grabbou** [comment]
Have you tried calling `reset`? If you have a stack `A, B, C, D` and want jump back from D to B, you can just reset it to `A, B`.

That will however unmount `C and D`.

**Comment by arnsa** [comment]
@grabbou I did try that, but reset actions don't have any animations :(

**Comment by vjeranc** [comment]
You can override `getStateForAction`.

For `action.type === NavigationActions.INIT` you have to put all of the initial routes.
For `action.type === 'YourCustomJump'` you have to change the index.
For `action.type === NavigationActions.BACK` you have to change the index (and not allow the original function to remove the scene from the routes.

Animated transitions seem to work.

**Comment by spencercarli** [comment]
Gonna close for inactivity (cleaning up issues)

**Comment by nisargrthakkar** [comment]
Any Update on this?

How can I use or make JUMP  function?
