### ISSUE TITLE
Is there any way to change header's font ?

### ISSUE THREAD

**Issue by yeknava** [react-community/react-navigation#542]
Is there any way to change header's font ?
i tried this but didn't work.
```
static navigationOptions = {
	    title: 'title',
	    header: {
	    	titleStyle: {
	    		fontFamily: 'test'
	    	}
	    }    
	}
```

**Comment by grabbou** [comment]
That's how it should work. Are you sure you don't override `header` config? Do you specify `navigationOptions` in any other places?

**Comment by yeknava** [comment]
yes. there is not other options that override it. color and other styles, everything works but fontFamily.

**Comment by RobertSheaO** [comment]
Make sure you're using a supported `fontFamily` I just tried one and it works.

Here's a list of supported fonts: https://github.com/dabit3/react-native-fonts

```JS
static navigationOptions = {
  header: ({ navigate }) => {
    return {
      titleStyle: {
        fontFamily: 'American Typewriter'
      },
    };
  },
};
```

**Comment by grabbou** [comment]
Since the title passes and the end component is `<text />`, I don't think it's an issue with React Navigation. Does that font work for other components within your app?

**Comment by thotegowda** [comment]
I have faced this problem too. The main problem seems to be in react-native rather than react-navigation. 

HeaderTitle.js sets fontWeight as fontWeight: Platform.OS === 'ios' ? '600' : '500',

When fontWeight is set to >=500, react-native expects bold variation of custom font (naming convention CustomFont_bold.ttf) to be present. If it fails find bold variation of custom font, it falls back to default font family instead of custom font family with regular font.

In this case, app is setting fontFamily to custom font and HeaderTitle.js is hardcoding fontWeight, so custom font will never reflect. 
**Quick fix would be have fontWeight: "200" in your header.titleStyle of your navigationOptions.** Which is <500 and regular font is picked up. 

I'm planning to raise PR to react-native project to fix it by falling back to regular custom font instead default.  

But if you feel HeaderTitle.js should always read fontWeight from header.titleStyle. Let me know, happy to raise PR.

**Comment by allpwrfulroot** [comment]
Just to note, Exponent does not support fontWeight or fontStyle at the moment, so those of us with custom fonts are SOL at the moment unless we go in and change the src.

**Comment by kamalk333** [comment]
@thotegowda Heyy!!! thanks for that quick fix, that really helped me.

**Comment by airguide** [comment]
`headerTitle: <Text style={ styles.textHeader }>Dashboard</Text>`
Works on android

**Comment by WilliamIPark** [comment]
Just because I landed here through a google search on how to change a headers font in general, and none of the above was working:

Use `headerTitleStyle` in `navigationOptions`.

**Comment by aroth** [comment]
@thotegowda any further information on this? did you have a chance to submit a PR?

**Comment by anceque** [comment]
@aroth Renaming the font to `CustomFont_bold` and using it with `headerTitleStyle` really does the magic. Try it.

**Comment by Charlynux** [comment]
If your fontFamily doesn't on Android for "headerTitleStyle" or "labelStyle", check weights managed by your font.

Just discover after some research that Android use a default font, if requested font doesn't have the requested fontWeight. (iOS seems to ignore fontWeight in this case.)
Both HeaderTitle and DrawerNavigatorItems define fontWeight (respectively 500 and bold).

My workaround is to define a font weight present in my TTF file in "headerTitleStyle" and "labelStyle".
```
labelStyle: {
  fontWeight: "normal",
  fontFamily: "Chalet-NewYorkNineteenSeventy"
}
```

Hope this could help someone.

**Comment by pallavbakshi** [comment]
In Jan 2018, 
`  static navigationOptions = ({ navigation }) => ({
    title: 'Projects',
    headerTitleStyle: {
        fontWeight: '300',
        justifyContent: 'space-between',
        textAlign: 'center',
        alignSelf: 'center',
        color: '#ffffff',
        fontFamily: 'Nunito-Regular',
        fontSize: normalize(16)
      }
})`

**Comment by mastersam92** [comment]
In feb 2018 :)

Not worked for me, but, solved( for me ):

-It is important, that 'fontFamily' contain name of **font file**( w/o extention )

In my case, name of font file: 'EuclidFlex-Regular.otf'
This font applying( android ) only when i set: fontFamily: 'EuclidFlex-Regular'
Whereas iOS works perfectly with real font name( i.e fontFamily: 'Euclid Flex' )

**Comment by Charlynux** [comment]
That's well explained in this article.
https://medium.com/react-native-training/react-native-custom-fonts-ccc9aacf9e5e

**Comment by yasir-netlinks** [comment]
Hi guys, I am looking for a way to make the title text bold when the tab is active! Any ideas, thanx
```
static navigationOptions = {
        title: 'Groups',  // how to set bold when active
        tabBarIcon: ({ focused }) => {
            let imageSource = focused
            ? require('../../../assets/iconGroupsSelected/iconGroupsSelected.png')
            : require('../../../assets/iconGroups/iconGroups.png')
            return <Image
                source={ imageSource }
            />
        },
    }
```

**Comment by mlazari** [comment]
@Charlynux Thank you for the hint. I was wondering why the font is working in other components, but not working in `headerTitleStyle`. I added `fontWeight: undefined` to `headerTitleStyle` and it's working now.

**Comment by ivanfranchi** [comment]
for One Plus 5t I got it working with  
`static navigationOptions = {
    title: 'Title',
    headerTitleStyle: {
      fontFamily: 'Roboto',
    }
  }`  
Default font was truncating no matter the length of the title text

**Comment by pascaloliv** [comment]
⬆️ See above @mlazari answer ⬆️ 

This portion of code wasn't working. ❌ 
```
{
  color: 'white',
  fontFamily: 'Montserrat-Bold',
  fontSize: 16,
}
```
When I added `fontWeight: undefined` , it worked very well. ✅ 
```diff
{
  color: 'white',
  fontFamily: 'Montserrat-Bold',
  fontSize: 16,
+  fontWeight: undefined,
}

**Comment by steniowagner** [comment]
Wow! That so weird...

fontWeight: undefined works like a charm!

Thank you @pascaloliv @Charlynux and @mlazari!

**Comment by Kalpeshsuthar** [comment]
> > @Charlynux Thank you for the hint. I was wondering why the font is working in other components, but not working in `headerTitleStyle`. I added `fontWeight: undefined` to `headerTitleStyle` and it's working now.
> 
> ⬆️ See above @mlazari answer ⬆️
> 
> This portion of code wasn't working. ❌
> 
> ```
> {
>   color: 'white',
>   fontFamily: 'Montserrat-Bold',
>   fontSize: 16,
> }
> ```
> When I added `fontWeight: undefined` , it worked very well. ✅
> 
> ```diff
> {
>   color: 'white',
>   fontFamily: 'Montserrat-Bold',
>   fontSize: 16,
> +  fontWeight: undefined,
> }
> 
> It looks like a bug, or at least a weird font behaviour.
> ```

it's really working but really and surprised also that why font weight is required.

**Comment by mlazari** [comment]
@Kalpeshsuthar I guess it's what @thotegowda said above.

**Comment by kpratik2015** [comment]
> I have also faced this problem. The main problem seems to be in react-native rather than react-navigation.
> 
> HeaderTitle.js sets fontWeight as fontWeight: Platform.OS === 'ios' ? '600' : '500',
> 
> When fontWeight is set to >=500, react-native expects bold variation of custom font (naming convention CustomFont_bold.ttf) to be present. If it fails find bold variation of custom font, it falls back to default font family instead of custom font family with regular font.
> 
> In this case, app is setting fontFamily to custom font and HeaderTitle.js is hardcoding fontWeight to 500, so custom font will never reflect.
> **Quick fix would be have fontWeight: "200" in your header.titleStyle of your navigationOptions. or keep bold variation of your custom font**
> 
> I'm planning to raise PR in react-native project to fix it by falling back to regular variation of custom font instead default family bold font.
> 
> But if you feel, HeaderTitle.js should always read fontWeight from header.titleStyle. Let me know, happy to raise a PR.

Thanks man, you helped me

**Comment by ridmal** [comment]
@thotegowda Thanks , you saved me. :)

**Comment by SaphiraNgocThuy** [comment]
> If your fontFamily doesn't on Android for "headerTitleStyle" or "labelStyle", check weights managed by your font.
> 
> Just discover after some research that Android use a default font, if requested font doesn't have the requested fontWeight. (iOS seems to ignore fontWeight in this case.)
> Both HeaderTitle and DrawerNavigatorItems define fontWeight (respectively 500 and bold).
> 
> My workaround is to define a font weight present in my TTF file in "headerTitleStyle" and "labelStyle".
> 
> ```
> labelStyle: {
>   fontWeight: "normal",
>   fontFamily: "Chalet-NewYorkNineteenSeventy"
> }
> ```
> 
> Hope this could help someone.

Cool!! Big thankssss!!

**Comment by RemyMachado** [comment]
Is there a way to change it for all headers once. Using the theme for instance? The documentation is really poor in this regard.
