### ISSUE TITLE
Bottom Tab Navigation overlaps on new iPad Pro

### ISSUE THREAD

**Issue by cesargdm** [react-community/react-navigation#5450]
### Current Behavior
Bottom Tab Navigation is not using Safe Area View insets in new **iPad Pro**.
![img_0003](https://user-images.githubusercontent.com/10179494/50728263-9d5db080-10ec-11e9-8d35-eb8406866f35.png)

### Expected Behavior
- Use safe area view as in iPhone X, to add padding at the bottom of the nav.

### How to reproduce
- Use bottom tab navigation and the padding is not present, home button overlaps with bottom navigation (used actual device, iPad Pro 12.9 and release build configuration).

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.0.9
| react-native     | 0.57.8
| node             | 10.14.0
| yarn      | 1.7.0

**Comment by brentvatne** [comment]
related: https://github.com/react-native-community/react-native-safe-area-view/issues/54

PR welcoome

**Comment by cesargdm** [comment]
@brentvatne :)
https://github.com/react-native-community/react-native-safe-area-view/pull/55

**Comment by kaloncheung124** [comment]
Does this mean it's been fixed in react navigation? I tried installing the latest build but it wasn't fixed yet.

**Comment by kaloncheung124** [comment]
Nevermind, the latest build is currently 3.0.9, but I was able to install 3.1.0.

`npm install react-navigation@3.1.0` or `npm install react-navigation@next`
