### ISSUE TITLE
TabBar icon function gets called twice

### ISSUE THREAD

**Issue by arnsa** [react-community/react-navigation#546]
```
static navigationOptions = {
    tabBar: ({ dispatch, navigate, state }) => ({
      icon: ({ focused }) => {
        console.log(focused);
        return(...);
      },
    }),
  }
```

Why icon is called twice for EVERY tab bar item? And everytime the first value is true, and second one is false. It doesn't matter if the tab is focused or not, second time focused will always be false.

**Comment by grabbou** [comment]
That's how `TabBar` loads icons for active and in-active state for a tab to display. It does that at once to optimise rendering.

See the implementation here: https://github.com/react-community/react-navigation/blob/master/src/views/TabView/TabBarIcon.js#L59

**Comment by arnsa** [comment]
@grabbou well, it if returns true and then false everytime, how am I supposed to know when the icon is focused and when not?

**Comment by grabbou** [comment]
Not sure I understand, that's what focused boolean is for.

**Comment by arnsa** [comment]
@grabbou well, my case is that since tab bar icons have no onPress listeners, I've implemented my own component for tab bar icon and when it's focused, when user presses it, it does one thing, and when it's not focused, it does another thing. But it always seems to be doing exactly one thing onPress, no matter if it's focused or not.

**Comment by satya164** [comment]
Tab bar icons are not supposed to have `onPress` listeners. The `focused` prop is to get the icon for focused and unfocused tabs. Not for side effects. If you want custom behaviour, you should create a Tab bar component instead.

**Comment by arnsa** [comment]
@satya164 I would disagree with this. Look at the facebook app for example. You're in the news feed, you scroll down a bit, then click notifications icon in the tab bar, then click news feed icon in the tab bar again. On the first press, it goes to news feed scene. However when that scene is loaded and when you press on the news feed tab bar icon again, it scroll to the top. And that's standard behaviour. This is how it works in many applications. Why can't we have onPress for tab bar icons in react-navigation?

**Comment by satya164** [comment]
@arnsa well, what you want is a press handler on the tab, not the icon. adding it on the icon is a hack and it's not supported. The icon doesn't even cover the whole tab. adding a press handler on icon will leave a lot of gap around the icon.

**Comment by arnsa** [comment]
@satya164 well, yes, that's what I meant, sorry if I wasn't clear. Is it possible to add press handler on the tab?

Also, I had to completely turn off labels and create my own tab consisting of icon and a label, because when I would change the language of the app, labels would stay in the old language for some reason, they wouldn't re-render.

**Comment by satya164** [comment]
It's not supported right now. But you can achieve the behaviour with a custom tab bar.

**Comment by arnsa** [comment]
@satya164 okay, I see. And what about the labels? Is this issue going to be fixed in the future?

**Comment by satya164** [comment]
You should re-render your root component by changing it's `key` when language changes to ensure everything gets re-rendered.

**Comment by Nitroman605** [comment]
I am facing similar issue where in the tabBarIcon I am supplying a function and depending on focused the icon will have different style . The function get called twice every time I click on a tab with the first time focused is true and the second time focused is false , does not matter what tab is clicked always twice .

I also have this weird and stupid effect on the first tab label and icon where the opacity increases when its clicked and decrease the farthest away from the tab .

**Comment by alexpopa-work** [comment]
I have the same problem. The focused and tintColor params get changed twice for every render and if you have a custom component to render the icon it doesn't know whether the tab is active or not.
In my case, I have one icon for each state (active / inactive).
My route definition:
```
			screen: SearchStack,
			navigationOptions: {
				title: null,
				tabBarIcon: ({tintColor, focused})=>{
					return <MenuIcon icons={TAB_ICONS.HS} tintColor={tintColor} focused={focused} />
				},
			}
```

TAB_ICONS.HS has the icons:
```
HS: {
        focused: require('../../assets/icons/menu/map-marker-focused.png'),
        normal: require('../../assets/icons/menu/map-marker.png')
    }
```

Inside the MenuIcon component I check the focused prop to know what to render. Something like this:
```
const MenuIcon = ({ icons, focused }) => {
    return (
        <Image resizeMode="contain" style={styles.iconStyle} source={focused ? icons.focused : icons.normal} />
    );
};
```

But the result is always the same (focused) image, because the component gets rendered always in the same order (with focused = false and then true). Same goes for the tint color. At every state change this value gets updated twice, the last one is always the same...

**Comment by robinmitra** [comment]
@alexpopa-work Did you manage to find a solution to this? I have the same issue.

**Comment by alexpopa-work** [comment]
@robinmitra Yes, the logic behind this is rather strange, but it works.
Basically react-native renders BOTH states when you run your app, that's the reason why it is called twice. When you tap the tab, the component does not re-render, it simply takes the already rendered focused state component. I know, is confusing and simple in the same time.

You can use the focused property inside the component and it will work.
Only that when the app runs, the icon component will be rendered twice and held somewhere to be used, and automatically the right one will be chosen when the tab changes state, without re-rendering it.

The syntax in my previous comment is working right, I only had a stupid problem with my image resources (it was basically the same icon, yep, a stupid mistake).
Try it with two different icons for the focused ans unfocused states and you'll see by yourself. 

Bear in mind that at the startup your app has two copies of your component and it knows which one to use. If you don't use the props (focused, tintColor, etc), the app will have two identical copies of the component, thus visually it will be the same. If you use them, one will be rendered with the behavior you chose for focused===false, the other one will be the one rendered with focused===true.

**Comment by bramski** [comment]
Is there any way to prevent the double rendering?  I'm trying to run tests via detox and I can't add a unique identifier in order to activate the tab navigation... why is it being rendered twice? this makes no sense. Two elements shouldn't both be visible at the same time.

**Comment by thomaschriskelly** [comment]
> Is there any way to prevent the double rendering? I'm trying to run tests via detox and I can't add a unique identifier in order to activate the tab navigation... why is it being rendered twice? this makes no sense. Two elements shouldn't both be visible at the same time.

@bramski I had the same issue as you. What I ended up doing is only attaching the testID to one of the two elements:

`tabBarIcon: ({ focused }) => (<View testID={focused ? 'jobs tab' : undefined}>...</View>),`

**Comment by satya164** [comment]
Why are you trying to add a test id to an icon instead of using `tabBarTestID` option? The icon is not a button. Users click the touchable containing the icon and label, not the icon itself.

**Comment by thomaschriskelly** [comment]
> Why are you trying to add a test id to an icon instead of using `tabBarTestID` option? The icon is not a button. Users click the touchable containing the icon and label, not the icon itself.

Oh looks like I somehow didn't notice the `tabBarTestID` prop. I guess I was looking for a prop called `testID` and skimmed past this one. Thanks @satya164 !

**Comment by alzalabany** [comment]
what if i want to run certain animation on icon selected for example? or run any side effect when component is mounted on screen ?

`useEffect(()=>{ ... } , [focused]) will not work`
