### ISSUE TITLE
setParams not working with nested TabNavigator and Redux

### ISSUE THREAD

**Issue by lfabreges** [react-community/react-navigation#548]
My application navigator is configured as follow:
```
StackNavigator
  Login (Component)
  Hub (TabNavigator)
    Home (Component)
    ...
```

The HomeContainer has a componentWillReceiveProps function:
```js
componentWillReceiveProps(nextProps: Props) {
  if (nextProps.user !== this.props.user) {
    this.props.navigation.setParams({ user: nextProps.user });
    this.refresh();
  }
}
```

The following doesn't work:

1. Navigate to LoginContainer from HomeContainer.
2. The user log in and the store user property is updated.
3. HomeContainer has not been unmounted, so componentWillReceiveProps is called.
4. Go back to HomeContainer, setParams has been called but nothing happened.

When setParams is called, it dispatches the SET_PARAMS action and the StackRouter getStateForAction tries to handle it. But it can't delegate it to the TabRouter because the currentRoute is Login, not Hub:
```js
// currentRoute.routeName == "Login"
const childRouter = childRouters[currentRoute.routeName];
```

It can't handle it itself because the route is not found:
```js
// action.key == "Home" and state.routes includes ["Login", "Hub"], not "Home"
const lastRoute = state.routes.find((route: *) => route.key === action.key);
```

Is that a bug or do I need to find a workaround ?

Thank you.

**Comment by dmhood** [comment]
related to https://github.com/react-community/react-navigation/issues/296

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
