### ISSUE TITLE
Help: How to perform navigation in header left or right elements

### ISSUE THREAD

**Issue by nebula-ai** [react-community/react-navigation#55]
Hi,

I'd like to ask for an example of invoking .navigate from with the left or right elements of a header.    Something along the line of

    header: ({ state, setParams }) => {
       // The navigation prop has functions like setParams, goBack, and navigate.
       let right = (
         <Button
           title="Options"
           onPress={() => this.props.navigation.navigate('Options')}
         />
       );
       return { right };
     },

where Options is another screen.  The above doesn't work.  I'm missing how to get hold of the navigation object.

Thanks

**Comment by JakeDluhy** [comment]
The first prop in dynamic configuration is the navigation object. So it would look like
```javascript
header: (navState) => ({
  title: 'Home',
  right: <Button label='About' onPress={() => navState.navigate('About')} />
})
```
Ref: https://reactnavigation.org/docs/navigators/navigation-options

**Comment by nebula-ai** [comment]
Works!    Thanks for the help

**Comment by mesbahsabur** [comment]
Great! thanks @JakeDluhy

**Comment by LordRahl90** [comment]
@JakeDluhy so i tried 
<code>
static navigationOptions=({navigation})=>({
        title:"New Post",
        headerTintColot:'blue',
        header: (navigation) => ({
            title: 'Options',
            right: <Button title='About' onPress={() => navigation.navigate('Options')} />
        })
    });
</code>
and i am getting this error
<code>
Objects are not valid as a React child (found: object with keys {title, right}). If you meant to render a collection of children, use an array instead.

Check the render method of `View`.
</code>
Please what am i doing wrong???

**Comment by LordRahl90** [comment]
@JakeDluhy 
I tried this too
`
static navigationOptions = ({ navigation, screenProps }) => ({
        title: "My Profile!",
        headerRight: <Button title="Menu" onPress={(navigation)=>{
                navigation.navigate('DrawerOpen');
         }} />,
    });
`

but i am getting 
`
Unhandled JS Exception: navigation.navigate is not a function
`

**Comment by JakeDluhy** [comment]
I haven't worked in this library for a while, but it looks like
```javascript
static navigationOptions = ({ navigation, screenProps }) => ({
  title: "My Profile!",
  headerRight: <Button title="Menu" onPress={(navigation)=>{ navigation.navigate('DrawerOpen'); }} />,
});
```
is almost the right way to go about it. You have the `navigation` passed in with object destructuring with the `navigationOptions` (`static navigationOptions = ({ navigation, screenProps })`) which looks right according to the to docs. But you're also doing `onPress={(navigation)=>{ navigation.navigate('DrawerOpen'); }}` and so in the context of `navigation.navigate` you're using the locally scoped `navigation` as opposed to the one from the `navigationOptions`. The one you're using is probably the press event.

Try `onPress={()=>{ navigation.navigate('DrawerOpen'); }}`

**Comment by LordRahl90** [comment]
@JakeDluhy 
Thanks a lot for this insight... that was the perfect way to go.. i was using the locally scoped navigation and it works pretty well now...
i really appreciate.

**Comment by patelkunala** [comment]
@JakeDluhy Your last line in the last comment did the trick! `navigation` from the outermost scope (i.e. 
`static navigationOptions = ({navigation, screenProps})` ought to be used instead of the local one passed from the immediate local one. Thank you!

**Comment by ajaymalviya001** [comment]
static navigationOptions = {
    headerLeft: (<Image source={require('../images/category/menu.png')} style={  {'height':25,  'width':25}}/>),
      title: 'Services',
      headerTintColor: "white",
      headerStyle: {
         backgroundColor: '#e6097a',
       },
    };

Need on press event when press on headerleft button anyone help me

**Comment by superlbr** [comment]
I put 'static navigationOptions' in react.componets for a screen, 
it's no use. 
only I pass navigationOptions in 'StackNavigator({...})' that work, but I cannot put a navigate button this way.

**Comment by LordRahl90** [comment]
@ajaymalviya001 y not overlay a button with that image or make the image itself clickable... but i think its better if you add a button to the headerLeft, then overlay the button with the image...
moreso, why not use vector icons instead of image? well, unless they are localised for the customer.
My Proposed solution will be 
`static navigationOptions = {
headerLeft: (

<Button onPress={(navigation)=>{ navigation.navigate('DrawerOpen')}}>
<Image source={require('../images/category/menu.png')} style={ {'height':25, 'width':25}}/>
</Button>),
title: 'Services',
headerTintColor: "white",
headerStyle: {
backgroundColor: '#e6097a',
},
};`

**Comment by xero88** [comment]
I get 'navigation.navigate is not a function' error

**Comment by ivnxyz** [comment]
@xero88 
Change 
`(navigation) => {navigation.navigate('YourViewNameHere')`
To
`() => {navigation.navigate('YourViewNameHere')`

That should work

**Comment by davidtoomey** [comment]
Adding `static navigationOptions = ({ **navigate,** navigation }) =>` and removing
` headerRight: <Button title="Name" onPress={**()=>**{ navigation.navigate('viewname'); }} />,`
is what fixed it for me

 ```
 static navigationOptions = ({ navigate, navigation }) => ({
    title: "Title",
    headerRight: <Button title="Name" onPress={()=>{ navigation.navigate('viewname'); }} />,
  })
```

**Comment by isaaclem** [comment]
@davidtoomey first argument `navigate` doesn't seems needed to be there

**Comment by dbarabashdev** [comment]
You can try 

```
const stackNavigatorConfig = {
  initialRouteName: 'InititalRoute',
  navigationOptions: ({ navigate, navigation }) => ({
    headerRight: (
      <TouchableOpacity
        onPress={() => navigation.navigate('YourRoute')}
      >
        <Text>Click</Text>
      </TouchableOpacity>
    )
  }),
}
```

**Comment by Lmjcvm** [comment]
@dbarabashdev this works for me.....thank you :3

**Comment by redbar0n** [comment]
@dbarabashdev 

```navigationOptions: ({ navigate, navigation }) => ({```

should be:

```
navigationOptions: (navigation) => ({
  // and, futhermore...
  const navigate = navigation.navigate;
```

since it's the navigation object which the function receives.

**Comment by wrossier** [comment]
Hi, 

It's writing in the doc : https://reactnavigation.org/docs/en/headers.html#using-params-in-the-title
```
class DetailsScreen extends React.Component {
  static navigationOptions = ({ navigation }) => {
    return {
      title: navigation.getParam('otherParam', 'A Nested Details Screen'),
    };
  };

  /* render function, etc */
}
```

**Comment by jussellymoreno1394** [comment]
@JakeDluhy Hey, thanks a lot for help.

**Comment by mrsnow070** [comment]
for functional component
`ScreenName.navigationOptions = ({ navigation }) => {

    return {
        title: 'Title',
        headerRight: <Button title='Settings' onPress={() => navigation.navigate('Settings')} />


    }
}`

**Comment by kumarideepika** [comment]
> Hi,
> 
> I'd like to ask for an example of invoking .navigate from with the left or right elements of a header. Something along the line of
> 
> ```
> header: ({ state, setParams }) => {
>    // The navigation prop has functions like setParams, goBack, and navigate.
>    let right = (
>      <Button
>        title="Options"
>        onPress={() => this.props.navigation.navigate('Options')}
>      />
>    );
>    return { right };
>  },
> ```
> 
> where Options is another screen. The above doesn't work. I'm missing how to get hold of the navigation object.
> 
> Thanks
below line work fine ..............
Instead of declaring const navigation into constructor do this line
 onPress={() => this.props.navigation.push('ProductList')}

Its working fine

**Comment by Anisha961** [comment]
> You can try
> 
> ```
> const stackNavigatorConfig = {
>   initialRouteName: 'InititalRoute',
>   navigationOptions: ({ navigate, navigation }) => ({
>     headerRight: (
>       <TouchableOpacity
>         onPress={() => navigation.navigate('YourRoute')}
>       >
>         <Text>Click</Text>
>       </TouchableOpacity>
>     )
>   }),
> }
> ```

It worked
