### ISSUE TITLE
replace history instead of push

### ISSUE THREAD

**Issue by yeknava** [react-community/react-navigation#551]
Im using redux integration and i had no luck to provide replace navigate. at least with this code:
```
this.props.navigation.navigate(
   NavigationActions.reset({
      index: 0, actions: [NavigationActions.navigate({ routeName: 'Test1'})]
   })
)
```
btw i think RouteConfigs accept a history attr to set it like this:
```
const AppRouteConfigs = {
  Test1: {
  	screen: Test1,
  },
  Test2: {
  	screen: Test2,
  	history: 'replace'
  }
};
```

hope we could have a more readable API for such a great library.

**Comment by RobertSheaO** [comment]
Ya, reset doesn't work at the moment, at least not with redux. There are a lot of open tickets for this. https://github.com/react-community/react-navigation/issues?utf8=%E2%9C%93&q=reset%20redux

**Comment by agrcrobles** [comment]
The following action creator works fine for me.

```
import { NavigationActions } from 'react-navigation';

export const tryReset = (): Thunk => {
	return function (dispatch: Dispatch, getState: GetState) {
		dispatch(NavigationActions.reset({
			index: 0,
			actions: [
				NavigationActions.navigate({
					routeName: "Home"
				})
			]
		}));
	})
}
```

**Comment by prontiol** [comment]
Why there is no shortcut for this behaviour?
Like `navigation.reset('MyProfile')`?
It feels odd to write so much code for such a simple action.
