### ISSUE TITLE
Title jumps from left to center on iOS

### ISSUE THREAD

**Issue by RobertSheaO** [react-community/react-navigation#553]
When a StackNavigator loads, the title first starts out on the left (Android style) and then jumps to the center (iOS style). This is on an iOS device. I'm pretty sure this is related to this commit https://github.com/react-community/react-navigation/commit/79f21277cbec2a684edc6f2073ff36530d093f41#diff-7a1b35ffbe830ce647e620ea2b07b52a

That commit also appears to be causing problems with centering the title on Android.

**Comment by grabbou** [comment]
I close that one as #539 has a better documentation. Working a fix, will roll out in a second!
