### ISSUE TITLE
Question: Reactiflux

### ISSUE THREAD

**Issue by andrispraulitis** [react-community/react-navigation#556]
Do we have a channel there for questions and discussions that should not go here in issues?

**Comment by markusguenther** [comment]
Not yet ...

**Comment by jonrh** [comment]
Found this while searching for some chat channels. As far as I can see it's been requested two times in #new-channel-requests in the reactiflux community at Discord. It's been denied/deferred both times for being too specific to justify a separate channel. #need-help, #react-native, and #exponent were mentioned as possible surrogates.

Personally I'd be more in favour a **react-navigation** channel on [gitter.im](https://gitter.im/).

**Comment by satya164** [comment]
I think it's reasonable to have a cannel for react navigation. cc @ericvicenti

**Comment by satya164** [comment]
Okay, I asked in reactiflux again.

**Comment by satya164** [comment]
Ok, we have #react-navigation in reactiflux now :D

**Comment by rjkmurray** [comment]
Where could a channel be found

**Comment by rjkmurray** [comment]
Where could a channel be found

**Comment by rjkmurray** [comment]
Where could a channel be found

**Comment by satya164** [comment]
https://discordapp.com/channels/102860784329052160/288388742929055765

**Comment by satya164** [comment]
If you don't have an invite, see reactiflux.com

**Comment by jonrh** [comment]
Should we make it visible somewhere (readme, website, etc) that we now have a reactiflux channel going?

**Comment by QuantumInformation** [comment]
@jonrh yeah I would put it in the readme
