### ISSUE TITLE
Unexpected elastic/rubber band effect when using pan handlers

### ISSUE THREAD

**Issue by idris** [react-community/react-navigation#559]
If you swipe a screen away and "slam" it hard, the screen beneath it bounces in an unexpected way.

Instead, these should be treated completely separately.  That is, when you swipe away a card in a forceful manner, the metaphor is that you threw it really far, and it will slide away faster/further.  But it should never effect the screen beneath it.

In case my explanation is unclear, here are videos:
https://dl.dropboxusercontent.com/u/35437/rn-elastic-horiz.mov
https://dl.dropboxusercontent.com/u/35437/rn-elastic-vertical.mov

**Comment by drop-dan** [comment]
It would be great to see this resolved before 1.0.  It seems like the transition on each card needs to have `extrapolate: 'clamp'` applied to its interpolation, but I'm not certain what the PR would look like.

**Comment by spencercarli** [comment]
Hi! In an effort to reduce the number of open issues I'm closing issues that haven't had any activity in a while.

If you think this should be re-opened please let me know or, if you can, re-open it.

If this is a question please consider asking it on StackOverflow ([react-navigation](https://stackoverflow.com/questions/tagged/react-navigation))

Thanks!
