### ISSUE TITLE
GitHub project to track versioning/updates

### ISSUE THREAD

**Issue by matthamil** [react-community/react-navigation#561]
One of the maintainers should start a GitHub project so contributors like myself can keep an eye on what bugs/features are high priority. This would also help other potential contributors to see what needs to get done so they can help out.

**Comment by grabbou** [comment]
It's here https://github.com/react-community/react-navigation/projects/1

I am not sure what's high priority at this point, I am meeting up with @evv next week so we'll discuss that.

**Comment by grabbou** [comment]
My priorities are as follows:
1) Fix all the remaining Header / docs issues
2) Focus on fixing nested Drawer / Tab reducer loosing params etc

**Comment by grabbou** [comment]
That didn't work quite well and so, we resorted to using #723 issue as a placeholder for remaining work.
