### ISSUE TITLE
How to prevent navigation from one screen to itself

### ISSUE THREAD

**Issue by wangzhe890703** [react-community/react-navigation#564]
I am new to react-navigation. 
Is there a way to prevent navigation from one screen to itself? 
For example, I am in a screen which have several links routing to other screen. One of the link routes to the same screen. How can I prevent the navigation?

**Comment by jamesone** [comment]
Wait - So there is a link in (lets call it screen A) screen A which links to screen A? Why would you have this? 

Could you maybe explain it a little better.

**Comment by nihgwu** [comment]
#271 check my workaround, it's easy to customize the navigate behavior

**Comment by wangzhe890703** [comment]
Closed this issue.
Thanks everyone!
