### ISSUE TITLE
[iOS] Long title name is not truncated

### ISSUE THREAD

**Issue by Ehesp** [react-community/react-navigation#566]
When setting a really long title on iOS, the text goes over the top of the back text:

![image](https://cloud.githubusercontent.com/assets/842078/23561744/772954a4-0037-11e7-96e9-4c753ea5c798.png)

Not sure what the expected behaviour is here, but from the screenshot above it doesn't look great.

Cheers

**Comment by satya164** [comment]
Are you on master?

**Comment by grabbou** [comment]
Fixed in master.
