### ISSUE TITLE
createNavigationContainer: Unexpected token (33:46) using exponent

### ISSUE THREAD

**Issue by sigmazen** [react-community/react-navigation#569]
Hi
I've been using reactNavigation in isolation and wanted to start incorporating it with exponent so have the following (amongst others):
    
    import Exponent from 'exponent';
    import { StackNavigator, TabNavigator, TabView, DrawerNavigator } from 'react-navigation';

But when I open in the iOS simulator I get the lovely red screen of death with:
`SyntaxError: ../node_modules/react-navigation/src/createNavigationContainer.js: Unexpected token (33:46)`

Any ideas?
Cheers

**Comment by RobertSheaO** [comment]
Can you post what line 33 looks like in your `node_modules/react-navigation/src/createNavigationContainer.js` file? 33:46 the middle of a variable name, which seems odd to me. Have you modified the react-navigation source code?

**Comment by sigmazen** [comment]
Hi ... that's the strange thing ... I've not modified anything.
The line is the same as github, namely:
    onNavigationStateChange?: (NavigationState, NavigationState) => void,
which as you say is right in the middle of the NavigationState name  :-/
I've actually broken my project at the moment ( haha ) so will rebuild it all from fresh install and update ( or close ) if needed.
Thanks for the quick response.
Cheers

**Comment by sigmazen** [comment]
Rebuilt the App from ground-up ... all working :-) 
Thanks

**Comment by jbail** [comment]
I get this exact error, same exact message and line number. Clean and rebuild didn't work for me. I still get a red screen of death in the iOS simulator

**Comment by maximovicd** [comment]
I get the same problem. I am moving from NavigationExperimental and I'm not using Exponent.

I'm not quite sure that I understood what @sigmazen did. I tried restarting packager and running app again 

Could this have something to do with TS, or there is some kind of RN version requirement?

**Comment by andfs** [comment]
I'm facing the same problem too

**Comment by carllippert** [comment]
I was having the same problem. My Navigator isn't my root component its nested under my Provider for redux

. Since it didn't have appRegistry I needed to add export default (HomeScreen) to the bottom of the example from the intro documentation. This fixed the problem.

**Comment by NeskireDK** [comment]
I too have been stuck on this for the better part of an hour. Seems that maximovicd fixed it by running a newer version of RN (React Native??) however I'm unable to get it working. I'm running with these versions 

		"react": "~15.4.1",
		"react-native": "0.42.3",
		"react-navigation": "^1.0.0-beta.7"
		"babel-jest": "19.0.0",
		"babel-preset-react-native": "1.9.1",
		"jest": "19.0.2",
		"react-test-renderer": "~15.4.1"

**To reproduce:** 

- Create a new React Native App


```
react-native init SimpleApp
cd SimpleApp
```

- Install the latest version of react-navigation from npm


`npm install --save react-navigation
`
- Run the new app


```
react-native run-android # or:
react-native run-ios
```

**Comment by jbail** [comment]
I got React Navigation 1.0.0-beta.7 working by upgrading my React Native app from 0.34 to 0.36. This issue definitely appears to be tied to React Native somehow. If you find yourself in a similar situation, my advice would be to upgrade your React Native one version a time until React Navigation works.
