### ISSUE TITLE
Nesting Navigators tutorial - 'Home' should declare a screen

### ISSUE THREAD

**Issue by DFelten** [react-community/react-navigation#571]
I'm trying to follow the [tutorial for nesting navigators](https://reactnavigation.org/docs/intro/nesting), but there is always an error: 

> Route 'Home' should declare a screen. For example:
> 
> import MyScreen from './MyScreen';
> ...
> Home: {
>     screen: MyScreen,
> }

I'm not sure what I'm doing wrong. When I start the navigators individually, they work. But unfortunately not combined.

This is the App.js, which I have created using the tutorial:
```
import React from 'react';
import {
	AppRegistry,
	Text,
	View,
	Button
} from 'react-native';

import {
	StackNavigator,
	TabNavigator
} from 'react-navigation';

class HomeScreen extends React.Component {
	static navigationOptions = {
		title: 'Welcome',
	};
	render() {
		const { navigate } = this.props.navigation;
		return <View>
			<Text>Hello!</Text>
			<Button
				onPress={() => this.props.navigation.navigate('Chat', { user: 'Daniel' })}
				title="ReactNavigation Test"
			/>
		</View>;
	}
}

class ChatScreen extends React.Component {
	static navigationOptions = {
		title: 'ReactNavigation Test',
	};
	render() {
		const { params } = this.props.navigation.state;
		return (
			<View>
				<Text>Neue Seite für den Navigator. Hallo {params.user}!</Text>
			</View>
		);
	}
}

class RecentChatsScreen extends React.Component {
	render() {
		return <Text>List of recent chats</Text>
	}
}

class AllContactsScreen extends React.Component {
	render() {
		return <Text>List of all contacts</Text>
	}
}

const ReactNativeTest = StackNavigator({
	Home: { screen: MainScreenNavigator },
	Chat: { screen: ChatScreen },
});

const MainScreenNavigator = TabNavigator({
	Recent: { screen: RecentChatsScreen },
	All: { screen: AllContactsScreen },
});

AppRegistry.registerComponent('ReactNativeTest', () => ReactNativeTest);
```

Maybe you can help me there. Thanks in advance!

**Comment by kimdhoe** [comment]
It seems the source code order is the problem. `MainScreenNavigator` is being used before it is defined. Swap the definitions of `ReactNativeTest` and `MainScreenNavigator`.

**Comment by DFelten** [comment]
Of course, how could I overlook this. Many Thanks!

**Comment by SaraChicaD** [comment]
@kimdhoe you are the best!

**Comment by armnotstrong** [comment]
Hey, I just come into this and swiped the declarations of the `ReactNativeTest ` and `MainScreenNavigator ` of the code @DFelten give as @kimdhoe advised, but I meet with following error just with that code:

```
import React from 'react';
import {
  AppRegistry,
  Text,
  View,
  Button
} from 'react-native';

import {
  StackNavigator,
  TabNavigator
} from 'react-navigation';

class HomeScreen extends React.Component {
  static navigationOptions = {
    title: 'Welcome',
  };
  render() {
    const { navigate } = this.props.navigation;
    return <View>
      <Text>Hello!</Text>
      <Button
        onPress={() => this.props.navigation.navigate('Chat', { user: 'Daniel' })}
        title="ReactNavigation Test"
      />
    </View>;
  }
}

class ChatScreen extends React.Component {
  static navigationOptions = {
    title: 'ReactNavigation Test',
  };
  render() {
    const { params } = this.props.navigation.state;
    return (
      <View>
        <Text>Neue Seite für den Navigator. Hallo {params.user}!</Text>
      </View>
    );
  }
}

class RecentChatsScreen extends React.Component {
  render() {
    return <Text>List of recent chats</Text>
  }
}

class AllContactsScreen extends React.Component {
  render() {
    return <Text>List of all contacts</Text>
  }
}



const MainScreenNavigator = TabNavigator({
  Recent: { screen: RecentChatsScreen },
  All: { screen: AllContactsScreen },
});

const ReactNativeTest = StackNavigator({
  Home: { screen: MainScreenNavigator },
  Chat: { screen: ChatScreen },
});

AppRegistry.registerComponent('ReactNativeTest', () => ReactNativeTest);
```

And the error is 

```
23:54:20: Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object. You likely forgot to export your component from the file it's defined in.

Check the render method of `AwakeInDevApp`.
    in AwakeInDevApp (at registerRootComponent.js:21)
    in ExponentRootComponent (at renderApplication.js:35)
    in RCTView (at View.js:128)
    in View (at AppContainer.js:93)
    in RCTView (at View.js:128)
    in View (at AppContainer.js:92)
    in AppContainer (at renderApplication.js:34)

23:57:27: Failed building JavaScript bundle

```

And I am using version `0.45` by the way

Did I miss something?

**Comment by jemmamariex3** [comment]
Same error ^ :/

**Comment by jwoertink** [comment]
I'm getting the same error, and my example isn't even as complicated.

```
// App.js
import React from 'react';
import { StackNavigator } from 'react-navigation';
import { HomeScreen } from './HomeScreen';

const App = StackNavigator({
  Home: { screen: HomeScreen }
});

export default App;
```

```
//HomeScreen.js
import React from 'react';
import { Text } from 'react-native';

export default class HomeScreen extends React.Component {
  render() {
    return (
      <Text>Hello</Text>
    );
  }
}
```

If I literally copy and paste the `HomeScreen.js` code in to the `App.js`, then it works fine. So something with it being a separate file is causing it to throw the "Home should declare a screen" error.

**Comment by kaumil-gh** [comment]
`import React from 'react';
import { Text, View, StyleSheet, Dimensions, Button,
  KeyboardAvoidingView, TextInput, TouchableOpacity, StatusBar,
  Animated, Image } from 'react-native';
import { StackNavigator } from 'react-navigation';
import { Constants } from 'expo';
import HomeScreen from './src/components/homescreen';
import LoginOptions from './src/components/loginoptions';
import StudentLogin from './src/components/studentlogin';
import ForgotPassword from './src/components/forgotpassword';
import StudentNavigation from './src/components/studentnavigation';


export default class App extends React.Component {
  render() {
    return (
      <View style={styles.container}>
        <MainScreenNavigator style={{ width: Dimensions.get('window').width }} />
      </View>
    );
  }
}

const MainScreenNavigator = StackNavigator({
  Home: { screen: HomeScreen },
  LoginOptionsScreen: { screen: LoginOptions },
  StudentLoginScreen: { screen: StudentLogin },
  PasswordPrompt: { screen: ForgotPassword },
  NavigationScreen: { screen: StudentNavigation },
});


const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ecf0f1',
    //paddingTop: Constants.statusBarHeight,
  },
  xContainer: {
        flex: 1,
        backgroundColor: '#2c3e50',
    },
    loginContainer:{
        alignItems: 'center',
        flexGrow: 1,
        justifyContent: 'center'
    },
    logo: {
        position: 'absolute',
        width: 300,
        height: 100
    },
    //title:{
      //  color: "#FFF",
        //marginTop: 120,
        //width: 180,
        //textAlign: 'center',
        //opacity: 0.9
    //},
    yContainer: {
     padding: 20
    },
    input:{
        height: 40,
        backgroundColor: 'rgba(225,225,225,0.2)',
        marginBottom: 10,
        padding: 10,
        color: '#fff'
    },
    buttonContainer:{
        backgroundColor: '#2980b6',
        paddingVertical: 15
    },
    buttonText:{
        color: '#fff',
        textAlign: 'center',
        fontWeight: '700'
    },
    loginButton:{
      backgroundColor:  '#2980b6',
       color: '#fff'
    }
});
`

> I am getting the same error and I am unable to find where I am doing wrong. Please Help

**Comment by kaumil-gh** [comment]
`import React from 'react';
import { Text, View, StyleSheet, Dimensions, Button,
  KeyboardAvoidingView, TextInput, TouchableOpacity, StatusBar,
  Animated, Image } from 'react-native';
import { StackNavigator } from 'react-navigation';
import { Constants } from 'expo';
import HomeScreen from './src/components/homescreen';
import LoginOptions from './src/components/loginoptions';
import StudentLogin from './src/components/studentlogin';
import ForgotPassword from './src/components/forgotpassword';
import StudentNavigation from './src/components/studentnavigation';


export default class App extends React.Component {
  render() {
    return (
      <View style={styles.container}>
        <MainScreenNavigator style={{ width: Dimensions.get('window').width }} />
      </View>
    );
  }
}

const MainScreenNavigator = StackNavigator({
  Home: { screen: HomeScreen },
  LoginOptionsScreen: { screen: LoginOptions },
  StudentLoginScreen: { screen: StudentLogin },
  PasswordPrompt: { screen: ForgotPassword },
  NavigationScreen: { screen: StudentNavigation },
});


const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ecf0f1',
    //paddingTop: Constants.statusBarHeight,
  },
  xContainer: {
        flex: 1,
        backgroundColor: '#2c3e50',
    },
    loginContainer:{
        alignItems: 'center',
        flexGrow: 1,
        justifyContent: 'center'
    },
    logo: {
        position: 'absolute',
        width: 300,
        height: 100
    },
    //title:{
      //  color: "#FFF",
        //marginTop: 120,
        //width: 180,
        //textAlign: 'center',
        //opacity: 0.9
    //},
    yContainer: {
     padding: 20
    },
    input:{
        height: 40,
        backgroundColor: 'rgba(225,225,225,0.2)',
        marginBottom: 10,
        padding: 10,
        color: '#fff'
    },
    buttonContainer:{
        backgroundColor: '#2980b6',
        paddingVertical: 15
    },
    buttonText:{
        color: '#fff',
        textAlign: 'center',
        fontWeight: '700'
    },
    loginButton:{
      backgroundColor:  '#2980b6',
       color: '#fff'
    }
});
`

I am facing the same issue but unable to find problem. Please help.

**Comment by YasirPanjsheri** [comment]
Hi , I am getting error `undefined is not an object (evaluating 'MainScreenNavigator.router')`
```
import React, {Component} from 'react'
import { AppRegistry, View, Text, Button } from 'react-native'
import { TabNavigator, StackNavigator } from "react-navigation";

class ChatScreen extends React.Component {
  // Nav options can be defined as a function of the screen's props:
  static navigationOptions = ({ navigation }) => ({
    title: `Chat with ${navigation.state.params.user}`,
  });
  render() {
    // The screen's current route is passed in to `props.navigation.state`:
    const { params } = this.props.navigation.state;
    return (
      <View>
        <Text>Chat with {params.user}</Text>
      </View>
    );
  }
}

class RecentChatsScreen extends Component {
  render() {
    return (
      <View>
        <Text>List of recent chats</Text>
        <Button
          onPress={() => this.props.navigation.navigate('Chat', { user: 'Lucy' })}
          title="Chat with Lucy"
        />
      </View>
    );
  }
}

class AllContactsScreen extends Component {
  render() {
    return (
      <View>
        <Text>List of all contacts</Text>
          <Button
            onPress={() => this.props.navigation.navigate('Chat', { user: 'Lucy' })}
            title="Chat with Lucy"
          />
      </View>
    );
  }
}

class NavigatorWrappingScreen extends React.Component {
  render() {    
    return (
      <View>
        <SomeComponent/>
        <MainScreenNavigator navigation={this.props.navigation}/>
      </View>
    );
  }  
}
  NavigatorWrappingScreen.router = MainScreenNavigator.router;

class SomeComponent extends Component {
  render() {
    return <Text>SOME COMPONENT</Text>
  }
}

const MainScreenNavigator = TabNavigator({
  Recent: { screen: RecentChatsScreen },
  All: { screen: AllContactsScreen },
});

const SimpleApp = StackNavigator({
  Home: { screen: NavigatorWrappingScreen },
  Chat: { screen: ChatScreen },
})

AppRegistry.registerComponent('myTest', () => SimpleApp);
```

the problem occurred when adding `NavigatorWrappingScreen` What am I doing wrong!

**Comment by suntehnik** [comment]
It literally says: `expected a class but got: object`.

Means you use 
`
const App = StackNavigator ...`
which means you define a const object, but AppRegistry expects a class.

Here is how to fix it:
`
export default class App extends StackNavigator({
                                Main: {screen: MainScreen},
                                Profile: {screen: ProfileScreen}
                                                     }) {
}
`

**Comment by greenroses** [comment]
Should be `import HomeScreen from './HomeScreen';`
instead of `import { HomeScreen } from './HomeScreen';`

**Comment by redochka** [comment]
@greenroses you are right but can you explain the difference between the 2 syntaxes?

**Comment by fullhdpixel** [comment]
I just had to 

> export default navigation

 in my App.js

**Comment by VesperDev** [comment]
App.js

`'use strict';
import React, { Component } from 'react';
import { StyleSheet, View, Text, Button } from 'react-native';
import { StackNavigator } from 'react-navigation';
import  HomeScreen  from './src/screens/HomeScreen';
import  ChatScreen  from './src/screens/ChatScreen';

export const SimpleApp = StackNavigator({
  Home: { screen: HomeScreen },
  Chat: { screen: ChatScreen },
});

export default class App extends React.Component {
  render() {
    return <SimpleApp />
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center'
  }
});`

HomeScreen.js

`'use strict';
import React, { Component } from 'react';
import { StyleSheet, View, Text, Button } from 'react-native';

export default class HomeScreen extends React.Component {

    static navigationOptions = {
      title: 'Bienvenido'
    }
  
    render() {
      const { navigate } = this.props.navigation;
      return (
        <View>
          <Text>Hello, Chat App!</Text>
          <Button
            onPress={() => navigate('Chat', { 'user': 'Edgar Mendoza Ortgon' })}
            title="Chat with Lucy"
          />
        </View>
      );
    }
  
  }`

ChatScreen.js

`'use strict';
import React, { Component } from 'react';
import { StyleSheet, View, Text, Button } from 'react-native';

export default class ChatScreen extends React.Component {

    static navigationOptions = ({ navigation }) => ({
      title: `Habla con ${navigation.state.params.user}`,
    });
  
    render() {
      const { params } = this.props.navigation.state;
      return (
        <View>
          <Text>Chat with {params.user}</Text>
        </View>
      );
    }
  }`

**Comment by VesperDev** [comment]
App.js

`import React, { Component } from 'react';
import { StyleSheet, View, Text, Button } from 'react-native';
import { StackNavigator } from 'react-navigation';
import  HomeScreen  from './src/screens/HomeScreen';
import  ChatScreen  from './src/screens/ChatScreen';

export const SimpleApp = StackNavigator({
  Home: { screen: HomeScreen },
  Chat: { screen: ChatScreen },
});

export default class App extends React.Component {
  render() {
    return <SimpleApp />
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center'
  }
});`

HomeScreen.js

`import React, { Component } from 'react';
import { StyleSheet, View, Text, Button } from 'react-native';

export default class HomeScreen extends React.Component {

    static navigationOptions = {
      title: 'Bienvenido'
    }
  
    render() {
      const { navigate } = this.props.navigation;
      return (
        <View>
          <Text>Hello, Chat App!</Text>
          <Button
            onPress={() => navigate('Chat', { 'user': 'Edgar Mendoza Ortgon' })}
            title="Chat with Lucy"
          />
        </View>
      );
    }
  
  }`

ChatScrenn.js

`import React, { Component } from 'react';
import { StyleSheet, View, Text, Button } from 'react-native';

export default class ChatScreen extends React.Component {

    static navigationOptions = ({ navigation }) => ({
      title: `Habla con ${navigation.state.params.user}`,
    });
  
    render() {
      const { params } = this.props.navigation.state;
      return (
        <View>
          <Text>Chat with {params.user}</Text>
        </View>
      );
    }
  }`

**Comment by mjstelly** [comment]
@VesperDev you posted code but didn't give any context. Did you have a problem? Are you posting to help someone else? Without context, most folks will ignore the post.

**Comment by VesperDev** [comment]
@mjstelly this code worked perfectly for me. Only when I put the code looks bad do not know why: /

**Comment by redbar0n** [comment]
@VesperDev for code spanning multiple lines use ``` on the line above and below the code, instead of wrapping in a single `

**Comment by crzycoder** [comment]
**It navigate all screen on main Screen but when i navigate screen on "HomeScreen" to "VideoScreen" it gave me error "Props.navigation.navigate undefined" Props error how should i slove it ( PlateForm: Android )  **

Navigator Screen (./scr/navigator/navigator)

import React, { Component } from "react";

//import { Text, View, TouchableOpacity } from "react-native";
import { createStackNavigator } from "react-navigation";
import Main from "../Main";
import VideoScreen from "../navigationScreens/VideoScreen";
import ScreenTest from "../ScreenTest";
import HomeScreen from "../HomeScreen";

const AppStacknavigator = createStackNavigator({
  Home: {
    screen: Main,
    navigationOptions: {
      header: null
    }
  },
  HomeScreen: {
    screen: HomeScreen,
    navigationOptions: {
      header: null
    }
  },
  VideoScreen: {
    screen: VideoScreen,
    navigationOptions: {
      header: null
    }
  },
  ScreenTest: {
    screen: ScreenTest,
    navigationOptions: {
      header: null
    }
  }
});

export default class App extends Component {
  render() {
    return <AppStacknavigator />;
  }
}
-------------------------------------------------------------------------------------------------------------------

HomeScreen (./scr/HomeSreen)

import React, { Component } from "react";
import {
  Image,
  StyleSheet,
  Dimensions,
  View,
  Text,
  TouchableOpacity
} from "react-native";
//import VideoScreen from "./VideoContent";
import { Thumbnail } from "native-base";
//import VideoScreen from "./navigationScreens/VideoScreen";
import Icon from "react-native-vector-icons/FontAwesome";

const { imageWidth } = Dimensions.get("window").width;

export default class HomeScreen extends Component {
  render() {
    return (
      <View style={styles.contanier}>
        {this.props.data.map(function(videoData, index) {
          console.log(videoData, "fetch3");
          return (
            <View style={styles.card_contanier} key={index}>
              <TouchableOpacity
                style={{ flex: 1 }}
                // onPress={() => this.props.navigation.navigate("VideoScreen")}
              >
                <View style={{ height: "45%" }}>
                  <Image
                    source={require("../img/special-page-banner.jpg")}
                    style={{
                      flex: 1,
                      width: imageWidth,
                      resizeMode: "stretch"
                    }}
                  />
                </View>
                <View style={styles.title}>
                  <Text
                    style={{ color: "black" }}
                    numberOfLines={2}
                    ellipsizeMode={"tail"}
                  >
                    {videoData.name}
                  </Text>
                </View>
                <View style={{ height: "20%" }}>
                  <View style={styles.buttom_contanier}>
                    <View style={styles.logo}>
                      <Thumbnail
                        source={require("../img/andy-sm.png")}
                        style={{ height: 32, width: 32 }}
                      />
                    </View>
                    <View style={{ flexDirection: "column" }}>
                      <View style={{ flexDirection: "row", left: 5 }}>
                        <Text
                          style={{ color: "black" }}
                          numberOfLines={1}
                          ellipsizeMode={"tail"}
                        >
                          {videoData.created_by_user.name}
                        </Text>
                      </View>
                      <View style={styles.iconic_contanier}>
                        <Icon name="calendar" size={10} style={{ top: 2 }} />
                        <Text style={styles.text}>10 Oct 2018</Text>
                      </View>
                      <View style={styles.iconic_contanier}>
                        <Icon name="eye" size={10} style={{ top: 2 }} />
                        <Text style={styles.text}>11 views</Text>
                      </View>
                    </View>
                  </View>
                </View>
              </TouchableOpacity>
            </View>
          );
        })}
      </View>
    );
  }
}
