### ISSUE TITLE
How to keep left-to-right swipe gesture to previous screen in stack nav but disable top-to-bottom swipe?

### ISSUE THREAD

**Issue by PatNeedham** [react-community/react-navigation#572]
I am trying to build a layout flow so that on the initial home screen there are two buttons, clicking one navigates to a Login screen, and clicking the other navigates to a separate TabNavigator. That TabNavigator has four tabs, each of which is its own StackNavigator in order to mimic the iOS NavigationViewController. I like how the react-navigation StackNavigator has the left-to-right swipe gesture to go to the previous screen in the stack enabled by default. But one negative consequence of including the `{mode: "modal"}` option when creating my root StackNavigator is that regardless of which tab I'm on or how nested I am in that tab's stack, swipe from top to bottom always removes the TabNavigator from the screen and shows the home screen again.

I've tried including cardStack: `{ gesturesEnabled: false }` inside the `navigationOptions` of certain screens but that disables everything when I do want to keep left-to-right swipe to go to previous screen on the current tab.

Right now the two buttons in the `HomeScreen`'s `render()` function look like this:
```
<Button
  onPress={() => navigate('Login')}
  title="Sign In"
/>
<Button
  onPress={() => navigate('CustomerTabBar')}
  title="Find Food"
/>
```

And the `HomeScreen` is used in the root StackNavigator like this:
```
const MyApp = StackNavigator({
  Home: { screen: HomeScreen },
  CustomerTabBar: { screen: CustomerNavigator },
  Login: { screen: LoginScreen},
  Signup: { screen: SignupScreen},
}, {mode: "modal"});

AppRegistry.registerComponent('MyApp', () => MyApp);
```

Is it possible to keep only one type of gesture and not the other? If it's not, how could I exclude `CustomerTabBar` from the StackNavigator` and replace `onPress={() => navigate('CustomerTabBar')}` with something that goes to the tab bar view (keeping the modal animation) while removing `HomeScreen` from the stack so there is nothing before the tab bar to swipe back to?

**Comment by joemckie** [comment]
I have the same problem. I have a settings page that uses a ScrollView in a modal, which gets closed  consistently whenever the user scrolls.

**Comment by joemckie** [comment]
@ericvicenti do you have any idea how to tackle this?

**Comment by kaynewbie** [comment]
I have met the situation the situation(a scroll view nests in a modal screen).It performs not good when swiping down.How to disable the modal screen's gesture?
I'm new for react-native.I need help.

**Comment by kaynewbie** [comment]
#385 It helps.

**Comment by aqnaruto** [comment]
@kaynewbie  do you know  how to make same goback-gesture on android just like ios's ?   mode:'card'

thank you alot

**Comment by kaynewbie** [comment]
I dont know.

**Comment by aqnaruto** [comment]
thank you @kaynewbie

**Comment by PatNeedham** [comment]
Within src/views/CardStack.js there is this line `const GESTURE_RESPONSE_DISTANCE_VERTICAL = 135;`. When I change 135 to a smaller value like 30, I notice it becomes much more difficult to encounter that undesired 'swipe down removes  the tab navigator' experience. And setting it to 0 makes it impossible.

I don't know how effective this solution would be as I'd have to make sure I set it back to 0 after pulling in new updates to this library.

Could there be optional props for the `CardStack` component `disableVerticalScroll` and `disableHorizontalScroll` (default values of `false`) so that after the line `const isVertical = mode === 'modal';` within `onMoveShouldSetPanResponder` method, there can be another check like:

    if ((isVertical && disableVerticalScroll) || (!isVertical && disableHorizontalScroll)) {
        return false;
    }

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!

**Comment by murthy474** [comment]
same problem any one help

**Comment by MacKentoch** [comment]
This is just a beautiful example of why RN is failing
