### ISSUE TITLE
Got there should always be only one scene active error on reset action

### ISSUE THREAD

**Issue by joeyzhao0113** [react-community/react-navigation#574]
I want to find a way to go back three times from current screen. I tried to call `navigation.goBack()` three times but it only go back once. After some searching I found there is a `reset` method which seems to work for my case. Below is what I did.

My current navigation route stack has 7 routes. I want to go back to the 4th route by using below method:

```
let routes = this.props.nav.routes.slice(0, this.props.nav.routes.length - 4);
dispatch(NavigationActions.reset({index: 3, actions: [routes[3]]}));
```

I got the current routes array from redux nav state then call `reset` function to fire a reset action. In the reset method, I choose the 4th route as the value of actions parameter. But I got below error:
```

there should always be only one scene active, not 0.
Invariant Violation: there should always be only one scene active, not 0.
```

**Comment by florentroques** [comment]
Regarding your navigation route stack, we can describe it as follows :
Screen1 > Screen2 > Screen3 > Screen4 > Screen5 > Screen 6 > Screen7

According to the [doc](https://reactnavigation.org/docs/navigators/navigation-actions#Reset):
> The Reset action wipes the whole navigation state and replaces it with the result of several actions.

So you need to rebuild your entire stack navigation state:
```javascript
NavigationActions.reset({
  index: 3,
  actions: [
    NavigationActions.navigate({ routeName: 'Screen1' }),
    NavigationActions.navigate({ routeName: 'Screen2' }),
    NavigationActions.navigate({ routeName: 'Screen3' }),
    NavigationActions.navigate({ routeName: 'Screen4' }),
  ]
})
```

That's how i solved a similar issue, tell me if it works for you.

**Comment by 349989153** [comment]
what does `this.props.nav` stands for?

**Comment by kelset** [comment]
Pinging OP @joeyzhao0113  since this issue is quite old and related to an old version of the lib. If no answer I'll close in 7 days.

**Comment by kelset** [comment]
Hi there @joeyzhao0113 ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue (especially if it's a bug report) please open a new issue that uses the new Issue Template to provide some more details to help us solve it.
