### ISSUE TITLE
Overriding router in StackNavigator

### ISSUE THREAD

**Issue by srounce** [react-community/react-navigation#580]
Is this possible? Or would i have to build a Navigator and pass it to the CardStack in there?

**Comment by grabbou** [comment]
Hey, what is your use case? What are your trying to achieve?

**Comment by srounce** [comment]
I was wondering if there was another way to do [this](https://github.com/srounce/react-navigation/commit/dabacabdb03f28ed367e634196efd0d1b0013c90#diff-109c57d09b031f621d1c4cfcb0d28d9fR42), but it doesn't look like it.

**Comment by spencercarli** [comment]
Hi! Since this issue has been quiet for a while I'm going to go ahead and close it. If the issue persists in the latest version of React Navigation please re-open!
