### ISSUE TITLE
messenger's camera button

### ISSUE THREAD

**Issue by tugorez** [react-community/react-navigation#583]
Hi guys, I'm trying to figure it out how to implement a messenger-like camera button ( **the one present in the middle image**) with the current implementation of **TabNavigator**.

![button](http://cdn.pocket-lint.com/r/s/650x/assets/images/phpqnluun.jpg)

Is this possible? Thank you for your time and for such an awesome library.

**Comment by satya164** [comment]
You can use a custom tabbar for this.

**Comment by tugorez** [comment]
@satya164 thank you.  Is it possible to animate the hidding of the tabBar ?
