### ISSUE TITLE
Replace header title to IMAGE

### ISSUE THREAD

**Issue by JunhyeokHeo** [react-community/react-navigation#584]
static navigationOptions = {
    title: 'Coupon',
    header: {
      titleStyle: {
      },
    },
    tabBar: tabBarSelecter('coupon')
  }

Currently i can put a 'Text' for title. 
how could i put Image thing there?

**Comment by danielbrodin** [comment]
`title` can take a react component, so `title: <Image />` should work

**Comment by JunhyeokHeo** [comment]
title: <Image /> doesn't get error page, but could not see it

**Comment by G2Jose** [comment]
Same problem here. Tried using an image, but does not work.

**Comment by myorukoglu** [comment]
Same here.  No error, just nothing displayed for a title.

**Comment by TomiHiltunen** [comment]
+1

**Comment by markmiller21** [comment]
+1

**Comment by andrioid** [comment]
Try specifying width and height

**Comment by mbrochh** [comment]
I can't see the image as well:

```
static navigationOptions = {
    title: ({ state }) => {
      if (typeof state.params !== 'undefined') return state.params.category.name
      return (
        <Image
          source={logoPng}
          style={{ width: 10, height: 10 }}
          resizeMode="contain"
        />
      )
    },
```

Tried mounting the image in a View like that and can see it, so my import of the image src should be correct.
