### ISSUE TITLE
tabBar visibility toggle from nested screens

### ISSUE THREAD

**Issue by f0rr0** [react-community/react-navigation#587]
Hierarchy: 

TabNavigator -> ScreenNavigator -> Screen

```js
  static navigationOptions = {
    tabBar: {
      visible: false
    }
  }
```

Above does not have any effect. Is this intended?

**Comment by f0rr0** [comment]
Possible duplicate of https://github.com/react-community/react-navigation/issues/581

**Comment by bjrn** [comment]
... and #464. May I suggest you close this ticket, @f0rr0?

**Comment by shixiaoquan** [comment]
solved the problem @f0rr0 @bjrn 
`Device: {
        screen: DevicesList,
        navigationOptions: {
            title: '设备总览',
            gesturesEnabled: false,
            **_## tabBarVisible: false,_**
        }
    },`

**Comment by rabindrachhachan** [comment]
I have navigation hierarchy
TabNavigator{HomeStack,SettingStack} -> StackNavigator {HomeScreen,DetailScreen}.
Suppose here the  StackNavigator refers HomeStack. I want to hide tab bar in DetailScreen. I tried with
detail: {
    screen: DetailScreen,
    navigationOptions: {
        title: '
        tabBarVisible: false,
    }
 }

but it did not work.  Can anyone suggest me the solution? Thanks

**Comment by shekharartemedia** [comment]
did you get any solution? I also facing this issue.

**Comment by shixiaoquan** [comment]
@shekharartemedia

**Comment by shixiaoquan** [comment]
@shekharartemedia  
First of all, I suggest you take a look at this document.   https://reactnavigation.org/docs/en/navigation-options-resolution.html#a-tab-navigator-contains-a-stack-and-you-want-to-hide-the-tab-bar-on-specific-screens。

According to the documentation, we can easily control the tabBarVisible of each page.
If you still don't understand, after reading the documentation. Please contact me again.

**Comment by shekharartemedia** [comment]
@shixiaoquan 
thanks :) , i will let you know.

**Comment by vkiranmaniya** [comment]
> solved the problem @f0rr0 @bjrn
> 
> **tabBarVisible: false**
> 
> ```
> Device: {
>     screen: DevicesList,
>     navigationOptions: {
>         title: '设备总览',
>         gesturesEnabled: false,
>         tabBarVisible: false,
>     }
>  }
> ```

Tried but not working!
