### ISSUE TITLE
How can react-navigation work with react-relay?

### ISSUE THREAD

**Issue by zhangmengying** [react-community/react-navigation#588]

**Comment by grabbou** [comment]
I am not sure what is you question. Have you tried setting it up? Have you encountered some issues?

**Comment by Kottidev** [comment]
Hi @zhangmengying :

check  with this repository 

https://github.com/sibelius/ReactNavigationRelay

**Comment by zhangmengying** [comment]
@grabbou Sorry for the confusion, for example for react-router for the web, there is react-router-relay use for integrate relay with router hierarchies. So I'm thinking is there a similar correspondences for react-navigation?

**Comment by zhangmengying** [comment]
@Kottidev Thank you very much~

**Comment by sibelius** [comment]
@zhangmengying can we close this?

**Comment by lukecwilliams** [comment]
We have this set up very simply, without adding the RelayUtils.js and RelayStore.js files referenced above - we couldn't get those to work after around 90 min of work so can't comment on their usefulness, though thanks for the info @sibelius.

To make Relay work with react-navigation just requires changing a couple lines.  Export a bare bones Component that renders Relay.RootContainer, and use that Component as your screen.

(TypeScript example)

MyComponent.tsx:
`
export default class MyComponent extends Component <any, any> {
  render() { return(
    <Relay.RootContainer
      Component={myRelayContainer}
      route={new MyRoute()}/>
  )}
}

let myRelayContainer = Relay.createContainer() //...
`

TabBar.tsx (using react-navigation library):
`
export default TabNavigator({
  FirstTab: { screen: MyComponent },
});
`

**Comment by sibelius** [comment]
U should use Relay.Renderer instead of Relay.RootContainer

**Comment by Lenin7** [comment]
For the user list to show up in the example [https://github.com/sibelius/ReactNavigationRelay](https://github.com/sibelius/ReactNavigationRelay),
you have to refresh the app after it loaded. Any ideas why doesnt the user list show up automatically after launching the app?

I only tested this on Android

**Comment by zhangmengying** [comment]
@sibelius Closed

**Comment by nikolasburk** [comment]
> U should use Relay.Renderer instead of Relay.RootContainer

@sibelius What's the benefit of using `Renderer` over `RootContainer` in that setup?

**Comment by nikolasburk** [comment]
@lukecwilliams I followed your instructions for my setup but somehow Relay doesn't seem to fetch any data. I posted my issue on SO, any help will be much appreciated 🙏

http://stackoverflow.com/questions/43089129/data-in-relay-not-fetched-when-using-it-with-react-navigation-in-react-native
