### ISSUE TITLE
error on launch

### ISSUE THREAD

**Issue by ajonno** [react-community/react-navigation#589]
i wanted to try out the example and got this when launching from command line :

module.js:471
    throw err;
    ^
Error: Cannot find module 'react-native/packager/blacklist'

**Comment by tigarcia** [comment]
I had some issues with the example too.  Can you put in more details about which example you tried to run and what commands you ran exactly?

**Comment by grabbou** [comment]
Try running via npm run-playground-ios from react-navigation folder. That's how I run examples when iterating on new features.

**Comment by matthamil** [comment]
Be sure to follow all of the steps on the Contributors Guide: https://reactnavigation.org/docs/guides/contributors.

The steps to run the examples are in an odd place imo. Most people who run the examples aren't looking to run them to add contributions; they're wanting to understand how the library works.
