### ISSUE TITLE
How to customize the drawer of the Drawer Navigator?

### ISSUE THREAD

**Issue by wangzhe890703** [react-community/react-navigation#591]
I want to customize the drawer part of the drawer Navigator. For example, I want to define the fontSize, fontFamily, color of the text. Can anyone give me some instruction/example?

Thanks!

**Comment by matthamil** [comment]
Check out `contentOptions` as seen here: https://reactnavigation.org/docs/navigators/drawer.

If you want to further customize the drawer, you should use your own component as the `contentComponent` in the `DrawerNavigationConfig`.

**Comment by futurechallenger** [comment]
The actual address is this: https://reactnavigation.org/docs/navigators/drawer#DrawerNavigatorConfig.
It's `DrawerNavigatorConfig`.

Anyway thanks for the answer!

**Comment by SunTzu92** [comment]
Help me please! I can not get it to work, please customize the drawer!

_**file: customDrawerContentComponent.js**_
`import React, { Component } from 'react';
import { Container, Content, Header, Body, Image } from 'native-base';
import { DrawerItems, SafeAreaView } from 'react-navigation';

class CustomDrawerContentComponent extends Component {
  render () {
    return (
      <Container>
          <SafeAreaView style={{ flex: 1 }} forceInset={{ top: 'always', horizontal: 'never' }}>
            <Header style={{ height: 200 }}>
              <Body>
                <Image
                  style={{ height: 150, width: 150, borderRadius: 75 }}
                  source={ require('../../assets/drawIcon/profile.png') }
                />
              </Body>
            </Header>
  
            <Content>
              <DrawerItems { ...props } />
            </Content>
          </SafeAreaView>
      </Container>
    );
  }
};

export default CustomDrawerContentComponent;`

_**file: route.config**_

`const drawer = () => ({
  Home      : { screen : HomePage },
  Schedule  : { screen : SchedulePage }
});

const drawerConfig = () => ({
  initialRouteName  : 'Home',
  contentComponent  : CustomDrawerContentComponent,
  drawerPosition    : 'Left',
  drawerOpenRoute   : 'DrawerOpen',
  drawerCloseRoute  : 'DrawerClose',
  drawerToggleRoute : 'DrawerToggle'
});

export default {
  drawer,
  drawerConfig,
};`

_**file: index.js**_

`import React, { Component } from 'react';
import { StackNavigator, DrawerNavigator, DrawerNavigatorConfig }   from 'react-navigation';

import routes from './config/routes.config';

const MainStack   = StackNavigator(routes.stack(), routes.stackConfig());
const MainDrawer  = DrawerNavigator(routes.drawer(), routes.drawerConfig());

const RouteConfig = () => ({
  Main    : { screen : MainStack },
  Drawer  : { screen : MainDrawer }
});

const NavigationConfig = () => ({
  mode: 'modal',
  headerMode: 'none',
  initialRouteName: 'Drawer'
});

export default StackNavigator(
  RouteConfig(),
  NavigationConfig()
);`


# **ERROR**

> _Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `CustomDrawerContentComponent`.

This error is located at:
    in RCTView (at View.js:71)
    in View (at Body.js:10)
    in Body (at connectStyle.js:384)
    in Styled(Body) (at customDrawerContentComponent.js:11)
    in RCTView (at View.js:71)
    in View (at Header.js:36)
    in RCTView (at View.js:71)
    in View (at Header.js:21)
    in Header (at connectStyle.js:384)
    in Styled(Header) (at customDrawerContentComponent.js:10)
    in RCTView (at View.js:71)
    in View (at createAnimatedComponent.js:147)
    in AnimatedComponent (at SafeAreaView.js:128)
    in SafeView (at withOrientation.js:30)
    in withOrientation (at customDrawerContentComponent.js:9)
    in RCTView (at View.js:71)
    in View (at Container.js:15)
    in Container (at connectStyle.js:384)
    in Styled(Container) (at customDrawerContentComponent.js:8)
    in CustomDrawerContentComponent (at index.js:11)
    in contentComponent (at DrawerSidebar.js:87)
    in RCTView (at View.js:71)
    in View (at DrawerSidebar.js:86)
    in DrawerSidebar (at withCachedChildNavigation.js:44)
    in withCachedChildNavigation(DrawerSidebar) (at DrawerView.js:112)
    in RCTView (at View.js:71)
    in View (at DrawerLayoutAndroid.android.js:176)
    in AndroidDrawerLayout (at DrawerLayoutAndroid.android.js:200)
    in DrawerLayoutAndroid (at DrawerView.js:134)
    in DrawerView (at DrawerNavigator.js:88)
    in Unknown (at createNavigator.js:13)
    in Navigator (at createNavigationContainer.js:214)
    in NavigationContainer (at SceneView.js:17)
    in SceneView (at CardStack.js:380)
    in RCTView (at View.js:71)
    in View (at createAnimatedComponent.js:147)
    in AnimatedComponent (at Card.js:12)
    in Card (at PointerEventsContainer.js:39)
    in Container (at CardStack.js:409)
    in RCTView (at View.js:71)
    in View (at CardStack.js:343)
    in RCTView (at View.js:71)
    in View (at CardStack.js:342)
    in CardStack (at CardStackTransitioner.js:66)
    in RCTView (at View.js:71)
    in View (at Transitioner.js:142)
    in Transitioner (at CardStackTransitioner.js:19)
    in CardStackTransitioner (at StackNavigator.js:38)
    in Unknown (at createNavigator.js:13)
    in Navigator (at createNavigationContainer.js:214)
    in NavigationContainer (at App.js:11)
    in Provider (at App.js:10)
    in App (at renderApplication.js:35)
    in RCTView (at View.js:71)
    in View (at AppContainer.js:102)
    in RCTView (at View.js:71)
    in View (at AppContainer.js:122)
    in AppContainer (at renderApplication.js:34)_

please help me!

**Comment by darocha** [comment]
Did you figure it out yet? It appears you forgot to import CustomDrawerContentComponent on your  route.config file.

**Comment by Pl4gue** [comment]
I'm getting the same Error. @SunTzu92

**Comment by darocha** [comment]
Hi my friends, 

I was able to replicate this problem on my machine. It appears that there is no Image component on the 'native-base' package.

Try this:

On the file: customDrawerContentComponent.js

1. Don't import the Image component from native-base.
import { Container, Content, Header, Body } from 'native-base';

2. Import the Image component from react-native
import { Image } from 'react-native';

Please take a look at the NativeBase docs. They also import the Image component from 'react-native' package. See it here: https://docs.nativebase.io/Components.html#card-image-headref

I hope it helps.

**Comment by matthamil** [comment]
Hi all, this issue is closed. If you are having further problems with react-navigation, can you open a new issue? This helps others to find your ticket and (hopefully) provide some help!

**Comment by SunTzu92** [comment]
@darocha , thanks man, You're right. Solved my problem. Thanks man.
