### ISSUE TITLE
componentWillMount being called multiple times

### ISSUE THREAD

**Issue by dondragon2** [react-community/react-navigation#592]
I have the following structure.

StackNavigator
  - auth
  - home (TabNavigator)
     - Tab 1 (Tab Navigator)
         - Tab A
         - Tab B
     - Tab 2

All the TabNavigators have `lazyLoad: true` set on them but I notice that the code that I have in my `componentWillMount()` on Tab A is being executed 3 times when the app starts up. Is there something that I need to add for the layLoad to work?

**Comment by grabbou** [comment]
Duplicate od #476

**Comment by dondragon2** [comment]
I added ` initialRouteName: 'Home',` and that did fix the issue.
I am using `"react-navigation": "^1.0.0-beta.6"`
