### ISSUE TITLE
Passing props to child component using Redux 

### ISSUE THREAD

**Issue by gbenga504** [react-community/react-navigation#593]
I am having a very tough time passing props to child component...  The docs said I should be able to access my props using this.props.screenProps... But how do I do this?  I am using redux

**Comment by RobertSheaO** [comment]
If you're using redux, shouldn't you have selectors to retrieve data and actions to store data?

**Comment by grabbou** [comment]
Exactly. Please demonstrate the code and what you are trying to achieve.

**Comment by gbenga504** [comment]
Yap...  Thanks...  I have solved the problem....  I was trying to use a destructive with screenProps i.e <Somestack screenProps={...this. props} />... So I changed it to <Somestack screenProps={this.props} />
