### ISSUE TITLE
Switch tabs, the scene would be reload, is it right?

### ISSUE THREAD

**Issue by guoliang1206** [react-community/react-navigation#595]
Hi everyone, every time when I tap the tab, the corresponding scene would be reload.So it cause little lag , is it need me to do some measures like cache?  Or is the use of I  is  wrong?
my StackNavigator:
```
const rootApp = StackNavigator(
    {
        Main: { screen: CustomTabBar },
        Home_2:{screen:Home_2},
        Contacts_2:{screen:Contacts_2},
        Find_2:{screen:Find_2},
        Me_2:{screen:Me_2}
    },
    {
        headerMode:'float',
    },
);

```
my custom tabBarNavigator:
```
const CustomTabs = createNavigationContainer(createNavigator(CustomTabRouter)(CustomTabView));
```

**Comment by matthamil** [comment]
Hi @guoliang1206 thanks for the question.

I solve this problem with redux in my app. I do an initial load the first time the user navigates to a specific tab, and I save the information in my redux store. Upon each subsequent navigation to that tab, I display the information from the redux store and fire off another `GET` to retrieve the most recent data from my API. You could probably achieve something like this without redux.

**Comment by guoliang1206** [comment]
@matthamil  thanks for your answer, I will research it

**Comment by rishabhbhatia** [comment]
@matthamil Hi Matt, i got stuck with the same problem. Could you elaborate how do you restore previous state from redux store. In my case using Stack Navigator i go from screen A-B-C. Screen B loads a list & now when i press back on C, B shows up empty as the componentDidMount function is not called. How can i restore my components previous state on reload?

**Comment by lhr000lhr** [comment]
@matthamil @guoliang1206 did you solve this problems? can you give me a hint?
