### ISSUE TITLE
header title : replace TEXT to IMAGE

### ISSUE THREAD

**Issue by JunhyeokHeo** [react-community/react-navigation#597]
import React from 'react';

import {
  Platform,
  StyleSheet,
  Text,
} from 'react-native';

import type {
  Style,
} from '../TypeDefinition';

type Props = {
  tintColor?: ?string;
  style?: Style,
};

const HeaderTitle = ({ style, ...rest }: Props) => (
  <Text numberOfLines={1} {...rest} style={[styles.title, style]} />
);

const styles = StyleSheet.create({
  title: {
    flex: 1,
    fontSize: Platform.OS === 'ios' ? 17 : 18,
    fontWeight: Platform.OS === 'ios' ? '600' : '500',
    color: 'rgba(0, 0, 0, .9)',
    textAlign: Platform.OS === 'ios' ? 'center' : 'left',
    marginHorizontal: 16,
  },
});

HeaderTitle.propTypes = {
  style: Text.propTypes.style,
};

export default HeaderTitle;
------------------------------------------------------------------------------------------------------------------

Current HeaderTitle.js in 'react-navigation' . so couldn't i change text to image for title?

**Comment by grabbou** [comment]
`title` can be a React.Element as well, try setting:
```js
static navigationOptions = {
   header: {
      title: <Image />,
   }
}
```
