### ISSUE TITLE
So many errors and warnings on flowtype 0.40.0

### ISSUE THREAD

**Issue by wellyshen** [react-community/react-navigation#598]
There're some many flowtype errors and warnings on the version of flow 0.40.0, does anyone has good solution for it?

**Comment by grabbou** [comment]
It's a different version than what we use -> https://github.com/react-community/react-navigation/blob/master/.flowconfig#L55.

Feel free to send over a PR that bumps it to 0.40 and fixes various issues.

CC: @satya164

**Comment by wellyshen** [comment]
I solved it by :
- add `.*/node_modules/react-navigation/.*` to [ignore] of `.flowconfig`
- add `module.name_mapper='^react-navigation$' -> 'emptyObject'` to [options] of `.flowconfig`

RN 0.43.0 will use flow 0.40.0, I think if the flow version of react-navigation could match with RN's version would be better :)

**Comment by tigarcia** [comment]
I'll try to do this today if @wellyshen isn't working on it. I've been looking for a task to get started with

**Comment by grabbou** [comment]
Sure, please go ahead :)
