### ISSUE TITLE
Navigation Playground on web

### ISSUE THREAD

**Issue by agrcrobles** [react-community/react-navigation#599]
after experimenting for a while there is it! https://react-navigation-playground.herokuapp.com/

it is really suprising most native components are web platform compatible!

will you consider adding navigators to web or would you rather have it in the way it is?

**Comment by ayalpani** [comment]
Hi @agrcrobles 

Would you also share the code, so we can have a look into it?

Thanks!

**Comment by agrcrobles** [comment]
Hi @ayalpani , yes.
Not much to share though, it is just [webpack](https://github.com/agrcrobles/react-navigation-web/blob/master/webpack.config.js) configuration and minor tweaks to make it work.

**Comment by udfalkso** [comment]
I'd love to see the code as well if you don't mind sharing.  

Does this use something like BrowserAppContainer.js as described here https://reactnavigation.org/docs/guides/web ?

**Comment by agrcrobles** [comment]
Sure, you can take a look at the following [repo](https://github.com/agrcrobles/react-native-web-workspace) but routes are not working there only navigations on web.

**Comment by spencercarli** [comment]
Gonna close this to help clean up some issues but thanks for the demo @agrcrobles!

**Comment by agrcrobles** [comment]
that is fine @spencercarli 

Thanks for cleaning this up
