### ISSUE TITLE
Host a demo (perhaps on github pages)?

### ISSUE THREAD

**Issue by appsforartists** [react-community/react-navigation#6]
There should be a hosted demo of https://github.com/react-community/react-navigation/blob/master/website/, linked to both from the docs and the GH repo

**Comment by knowbody** [comment]
One website is enough I think, don't see a point of doing it in two places. Any particular reason for that?

**Comment by appsforartists** [comment]
Sorry, I misunderstood the copy in the docs.  Opened a PR to fix it.
