### ISSUE TITLE
Library and examples probably not ready for use with Windows

### ISSUE THREAD

**Issue by Steviey** [react-community/react-navigation#60]
Got the following output on 

'npm install' within the react-navigation folder...

'rm' is not recognized as an internal or external command. [...]

Win 7
npm v 4.1.2
node v 6.9.4

PS:
Tried to hint this issue with rimraf in package.json, but then the install breaks at
cannot read property split of undefined at compile-docs.js.

I'm wondering seeing so much 'Mac-first approaches' in React land.
Shouldn't traditional MS Windows dev-environments supported from the beginning?

https://gist.github.com/domenic/2790533

**Comment by satya164** [comment]
> I'm wondering seeing so much 'Mac-first approaches' in React land. Shouldn't traditional MS Windows dev-environments supported from the beginning?

We don't use windows and it's extremely difficult for us to verify that everything works fine on windows. It's mac-first, because we use macs to develop it.

Though it would be great I people who actually use windows can send PRs to fix bugs on windows. And probably tests too, to make sure that we don't break windows.

> Shouldn't traditional MS Windows dev-environments supported from the beginning?

It should be, but most of the developers here work on mac, and it's impossible to verify that it'll work on windows. PRs welcome.

> Tried to hint this issue with rimraf in package.json, but then the install breaks at

I personally prefer `del-cli`. If you could figure out why it's not working, it'd be awesome.

**Comment by Steviey** [comment]
I simply did this for function split() in compile-docs.js: "docs\\"
Next error then causes mkdir, which probably can be hinted by https://www.npmjs.com/package/mkdirp on Windows. But then it has to be a js - file. 
All in all it needs a cross-platform install (very common these days). 
Easy for professionals to implement. Not so easy for me :-).

**Comment by Steviey** [comment]
Update:
I also managed to 'node.jsish cross platformarize' this from package.json:
```
"watch-rn": "node scripts/watch-rn",
"watch-web": "node scripts/watch-web",
"build-rn": "node scripts/build-rn",
"build-web": "node scripts/build-web",
```
So who has fun to translate this into node.js (last step)?

 "build-dot-flow": "find ./src -name '*.js' -not -path '*/__tests__*' | while read filepath; do cp $filepath `echo $filepath | sed 's/\\/src\\//\\/lib\\//g'`.flow && cp $filepath `echo $filepath | sed 's/\\/src\\//\\/lib-rn\\//g'`.flow; done",

**Comment by Steviey** [comment]
Update:
For the last part to make cross platform I would suggest this:

http://stackoverflow.com/questions/25460574/find-files-by-extension-html-under-a-folder-in-nodejs

But I have no idea what sed does, and why it is in a pipe.

**Comment by Steviey** [comment]
Now I see. So it could be done by a simple 
str.replace("src", "lib") 
followed by
str.replace("src", "lib-rn") 
in a 'looped file traversal' from the link above.

**Comment by Steviey** [comment]
I'm a little bit confused and need a clarification.  

I don't know how the files should look like after...  

sed 's/\\/src\\//\\/lib\\//g'.flow and 
sed 's/\\/src\\//\\/lib-rn\\//g'.flow

...respective a string replace and a copy.

I need before and after state of example files. 

Currently I can't see any files ending with 'flow'.

**Comment by satya164** [comment]
It needs to copy files from `/src` to `lib/` and `lib-rn/` folder and adds `.flow` extension to them

![image](https://cloud.githubusercontent.com/assets/1174278/22405579/0088bfa0-e66b-11e6-8857-23ca35d65fe1.png)

**Comment by Steviey** [comment]
Thank you, could be done.

**Comment by satya164** [comment]
> Thank you, worked out

Great!

> But currently my complete RN environment is broken...looking forward to fix this.

Ouch. Hope you fix it soon

**Comment by Steviey** [comment]
already fixed.
