### ISSUE TITLE
Screen Flickers when transiting to next route in StackNavigator

### ISSUE THREAD

**Issue by JustinNothling** [react-community/react-navigation#603]
![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/4808358/23668181/fb7ee4b0-0368-11e7-99fd-bba3c010bf59.gif)

I'm using the SimpleStack demo. The first time navigating to profile it works fine, but the next time I navigate then there is a flash in the animation.
Is there something interfering with the Javascript thread? I'm thinking about using the interactionManager somewhere.
Any ideas?

**Comment by benvium** [comment]
We've run into this too. I tried using:

```
const wrappedPress = () => InteractionManager.runAfterInteractions(onPress);
```

for the onPress on the button that triggers the transition but the flicker still happens every 3rd or 4th transition.

**Comment by JustinNothling** [comment]
@benvium thanks for the idea. Too bad that doesn't completely fix it.

**Comment by vikeri** [comment]
Experiencing this as well after upgrading to RN 0.39

**Comment by grabbou** [comment]
This is an issue with native animations in React Native. Should be fixed in latest version. See #222
