### ISSUE TITLE
DrawerNavigator and TabNavigator

### ISSUE THREAD

**Issue by haapio** [react-community/react-navigation#604]
Hi there, is this possible to create with a react-navigation?

I have 4 screens and i would like that all 4 are in DrawerNavigator but only first 3 in TabNavigation. I would also like that it shows that screen 2 is active when you click "screen 2 tab" and then open Drawer.

Here i have 3 different TabNavigators but when i click "screen2 tab" and open Drawer it shows that Screen1 is "active".

Any help how to do this correctly?

Thanks!

```
//  React imports
import React from 'react';
import {
  Text,
} from 'react-native';

// React navigation imports
import {
  TabNavigator,
  DrawerNavigator
} from 'react-navigation';

// Simple screens
const Screen1 = () => (
  <Text>Screen1</Text>
);
const Screen2 = () => (
  <Text>Screen2</Text>
);
const Screen3 = () => (
  <Text>Screen3</Text>
);
const Screen4 = () => (
  <Text>Screen4</Text>
);

// TabNavigators
const Screen1Tabs = TabNavigator({
  Screen1: {
    screen: Screen1,
  },
  Screen2: {
    screen: Screen2,
  },
  Screen3: {
    screen: Screen3,
  }
});

const Screen2Tabs = TabNavigator({
  Screen1: {
    screen: Screen1,
  },
  Screen2: {
    screen: Screen2,
  },
  Screen3: {
    screen: Screen3,
  }
});

const Screen3Tabs = TabNavigator({
  Screen1: {
    screen: Screen1,
  },
  Screen2: {
    screen: Screen2,
  },
  Screen3: {
    screen: Screen3,
  }
});

// DrawerNavigator
const App = DrawerNavigator({
  Screen1: {
    screen: Screen1Tabs,
  },
  Screen2: {
    screen: Screen2Tabs,
  },
  Screen3: {
    screen: Screen3Tabs,
  },
  Screen4: {
    screen: Screen4,
  }
});

export default App;
```

**Comment by RobertSheaO** [comment]
You're believe you're looking for `initialRoute`, which is found in the documentation [here](https://reactnavigation.org/docs/navigators/tab) and/or `initialRouteName` [here](https://reactnavigation.org/docs/navigators/drawer)

**Comment by heikkihautala** [comment]
I have a same kind of navigation solution: Multiple screens in a drawerNavigator, and the first 4 of them are also in a tabNavigator.

My problem is, that when I select any of the first 4 items from the drawer, the correct screen is shown, but the drawer displays the first item highlighted, and the name of the first item changes based on the selected tab in the TabNavigator.

How can I get the correct item to get highlighted and prevent the drawer item name from changing?

**Comment by webenformasyon** [comment]
i have the same problem. I have 3 screens. I want to show them and to navigate inside both drawer and tab. But when i nest drawer inside tab navigator as above tab changes but drawer remains, when i nest tab inside drawer navigator drawer changes but tab remains. I started to think there is no solution for this situation with react navigation alone. In summary i need intersected navigators not nested.

**Comment by samartha-kar23** [comment]
Quoting @heikkihautala 's question again..
My problem is, that when I select any of the first 4 items from the drawer, the correct screen is shown, but the drawer displays the first item highlighted, and the name of the first item changes based on the selected tab in the TabNavigator.

Did anyone find solution for this?

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!

**Comment by dalvira** [comment]
@haapio Did you ever find a solution? I have the exact issue. I want to have more items in my drawer nav than in my tab nav but when I select one of those extra items in my drawer nav I want the entire tab navigation bar to stay on the screen. I also have the issue with the the first drawer nav option remaining highlighted no matter the screen I am on.
