### ISSUE TITLE
After the head button click, the error message appears, the prompt is undefined

### ISSUE THREAD

**Issue by zhaopengme** [react-community/react-navigation#606]
![untitled](https://cloud.githubusercontent.com/assets/1415418/23671608/d62939b6-03a6-11e7-989d-c65cfc9905f0.gif)

I add a button in the head, click on the implementation of the current page method, and #145 mentioned in the same problem.
I have seen the solution given in #145, and the test can be used.
My current page structure is

TabNavigator
     StackNavigator-A
     StackNavigator-B

The StackNavigator-A and the StackNavigator-B code are the same for the TabNavigator that contains two StackNavectors, only StackNavigator-A can be used, and StackNavigator-B can not be used.

Here is the code I use.

[tab.zip](https://github.com/react-community/react-navigation/files/825385/tab.zip)

**Comment by grabbou** [comment]
Can you please reword your issue and update title?

**Comment by zhaopengme** [comment]
@grabbou I rewrited issue.please !

**Comment by zhaopengme** [comment]
https://github.com/satya164/react-navigation-addons  is a good solution.

**Comment by zhaopengme** [comment]
https://github.com/satya164/react-navigation-addons for me .
