### ISSUE TITLE
Q: Add React Elements to the Drawer navigator's sidebar

### ISSUE THREAD

**Issue by PuercoPop** [react-community/react-navigation#607]
AFAIU the sidebar is populated from the [routeConfig](https://reactnavigation.org/docs/routers/tab#RouteConfig) which an object that has key which represent the route name and an object which takes a screen (and some other options).

What I want to do is to add a log-out button, which can be seen as a 'conditional screen transition', is there any way to insert a react element to the side bar menu? (w/o modifying the drawer navigator)

**Comment by PuercoPop** [comment]
I'm guessing the answer involves getComponentRouteName?

**Comment by grabbou** [comment]
Have you tried setting your own [`contentComponent`](https://reactnavigation.org/docs/navigators/drawer#DrawerNavigatorConfig) and below item rendering logic, simply displaying a log out button? That would work I guess.

**Comment by PuercoPop** [comment]
@grabbou Thanks, that is the approach I'm trying right now. Although I would like to fallback to NavigationDrawerItems for the rest of the routes. Would it be unreasonable to ask for react-navigation to export the it?

**Comment by grabbou** [comment]
I think it should be exported if it's not already (we export Header of
CardStack so that could be done the same way). If it's not, feel free to
send a PR as fallback to default render is a reasonable approach.

**Comment by satya164** [comment]
It's already exported.
