### ISSUE TITLE
Can't to remove shadow on the header in Android

### ISSUE THREAD

**Issue by joeyzhao0113** [react-community/react-navigation#609]
In below screenshot, you can see a shadown under the header bar. I have tried to set values on `style` and `titleStyle` on header but failed to remove this shadow. Is there a way to do that? It seems that this only happens on Android device.

![image](https://cloud.githubusercontent.com/assets/23547018/23689446/c36bddac-040e-11e7-973e-7175a3056f8e.png)

**Comment by matthamil** [comment]
I was able to remove the shadow by going to `/src/views/Header.js` and commenting out this line: 

https://github.com/react-community/react-navigation/blob/e650f341e35fbb87f265c354019f5431cf09e2fc/src/views/Header.js#L340

Remove the `elevation` style and rebuild your React Native app and the shadow will be gone.

**Comment by joeyzhao0113** [comment]
Are you saying that I need to change the react-nagivation source code?  It is not good for building it in different machines across our team.

**Comment by matthamil** [comment]
Currently, yes. You can submit a PR if you want to make this property configurable.

**Comment by joeyzhao0113** [comment]
where is your PR link I can use?

**Comment by matthamil** [comment]
You are welcome to fork the repository and submit a pull request with the proper updates as well to the documentation:

https://github.com/react-community/react-navigation/pulls

**Comment by joeyzhao0113** [comment]
Just tried that, I changed this file under `node_modules` directory then run `react-native run-android`. The shallow is still there. Did I miss anything on rebuilding?

**Comment by matthamil** [comment]
What version of RN and React-Navigation are you using? This is the only change I have made in my source files to remove the header shadow on Android.

Be sure to shut down your packager and restart it as well.

**Comment by matthamil** [comment]
From my `src/views/Header.js` file:

```js
const styles = StyleSheet.create({
  container: {
    paddingTop: STATUSBAR_HEIGHT,
    backgroundColor: Platform.OS === 'ios' ? '#EFEFF2' : '#FFF',
    shadowColor: 'black',
    shadowOpacity: 0.1,
    shadowRadius: StyleSheet.hairlineWidth,
    shadowOffset: {
      height: StyleSheet.hairlineWidth,
    },
    // elevation: 4, // remove header shadow
  },
  appBar: {
    height: APPBAR_HEIGHT,
  },
  item: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  title: {
    bottom: 0,
    left: 40,
    position: 'absolute',
    right: 40,
    top: 0,
  },
  left: {
    bottom: 0,
    left: 0,
    position: 'absolute',
    top: 0,
  },
  right: {
    bottom: 0,
    position: 'absolute',
    right: 0,
    top: 0,
  },
});

```

**Comment by joeyzhao0113** [comment]
I did the same change but doesn't work for me.

I am using below version:

```
react-native: 0.39.2
react-navigation: ^1.0.0-beta.6
```

**Comment by matthamil** [comment]
I am using `react-navigation: 1.0.0-beta.3` and `react-native: 0.41.2`. See if you can downgrade your `react-navigation` and get it working.

**Comment by joeyzhao0113** [comment]
I just tried that downgrade to `1.0.0-beta.3` works for me. I wander what the different between `1.0.0-beta.3` and `1.0.0-beta.6` in this case?

**Comment by matthamil** [comment]
This is very odd behavior. There are a few minor differences between 1.0.0-beta.3 and 1.0.0-beta.6 in the `Header.js` file, but the `navigation` property was not touched in the new releases.

**Comment by joeyzhao0113** [comment]
that's strange. Anyway thanks for your help. I am going to use this approach for now.

**Comment by matthamil** [comment]
I'll try to look into this further and see what the issue is. Thank you for reporting this bug!

**Comment by grabbou** [comment]
Have you tried passing `style: { elevation: 0 }` via `navigationOptions.header`?

**Comment by joeyzhao0113** [comment]
`style: { elevation: 0 }` works perfect. It would be better to document it somewhere.
 Thanks.

**Comment by GollyJer** [comment]
`        elevation: 0,       //remove shadow on Android
        shadowOpacity: 0,   //remove shadow on iOS
`

**Comment by Vishal7008** [comment]
#790  SOLVED BY  Barylskyigb
 Properties names have changed, so:

  navigationOptions = {
      headerStyle: {
        elevation: 0,
        shadowOpacity: 0
      }
  }

**Comment by billscheidel** [comment]
I've tried sticking this code everywhere and nothing is working on Beta 24.

````
    [screens.TODO]: {
      screen: ToDoScreen,
      navigationOptions: {
        headerStyle: {
          shadowOpacity: 0,
          elevation: 0,
        },
      },
    },
````

````
class ToDoScreen extends Component {
  static navigationOptions = ({ navigation }) => ({
    title: 'TO DO',
    headerTitle: <HeaderTitle label="todo" />,
    headerRight: <ToDoActions navigation={navigation} />,
    tabBarIcon: ({ focused }) => (
      <TabButton icon="todo" label="todo" focused={focused} />
    ),
    headerStyle: {
      shadowOpacity: 0,
      elevation: 0,
    },
  });
````

Is there a different trick now? Any chance we can just get a 'don't display border' property somewhere? This issue has come up at least 4 times now and seems to be a pretty populate point of confusion.

**Comment by iorena** [comment]
ShadowOpacity and elevation aren't doing anything for me either.

**Comment by paulofdev** [comment]
> Have you tried passing `style: { elevation: 0 }` via `navigationOptions.header`?

THANK YOU DUDE

**Comment by superbrisa** [comment]
_if you are using RouterFlux_ just add this line into Scene @joeyzhao0113 

 `<Scene key="anotacao" navigationBarStyle={{backgroundColor:'white', elevation:2}} title="Anotações" backToInitial component={Anotacao}/>`

**Comment by felipejh** [comment]
`elevation: 0` in Android 10 doesnt work. Others Android version it works.
It is changes to transparent header.

![2020-10-01_10-06](https://user-images.githubusercontent.com/37714181/94812984-d617e000-03cd-11eb-8f80-2a5e8963bbdc.png)
