### ISSUE TITLE
add withNavigation HOC, and export navigation context from SceneView

### ISSUE THREAD

**Issue by markflorisson** [react-community/react-navigation#61]
Can we get access to the global dispatch/nagivate/etc functions, so that we don't have to pass them through our component trees?

**Comment by satya164** [comment]
Probably we could provide an HOC like `ex-navigation` did. @ericvicenti is there a reason we don't do this?

**Comment by ericvicenti** [comment]
No reason, it just hasn't come up yet. All we need to do is modify SceneView to provide the navigation prop via context, then add a simple HOC to pull it out of context.

The hardest part about this is deciding on the name of the HOC, and docs.

**Comment by satya164** [comment]
@ericvicenti ex-navigation use `withNavigation`, so maybe we can steal that name?
