### ISSUE TITLE
Broken iOS chrome debugger

### ISSUE THREAD

**Issue by GertjanReynaert** [react-community/react-navigation#610]
When using a stackNavigator (haven't tried other navigators) I only get a white screen when I start remote debugging. Each of the views separately render nicely in debugger mode when not using the stack navigator, but as soon as I add the navigator back the screen turns white again.

In the chrome console there are no errors, so nothing there that can be helpful for this issue.

I'm using RN 0.42.0, react-navigation 1.0.0-beta6 on mac os

**Comment by GertjanReynaert** [comment]
Update: The issue seems to be related to `screenProps`. When I use the stackNavigator without screenProps the debugger works. When I add the screenProps the remote debugging no longer works and only the white screen shows. I do get a warning in the console
```
Behaviour of screenProps has changed from initial beta. Components will now receive it as `this.props.screenProps` instead.
This warning will be removed in future.
```

But I'm setting the screenProps like this 
```
<StackNavigator screenProps={{ setFlag: (bool) => {this.setState({flag: bool}) }}} />
```
and reading them from `this.props.screenProps.setFlag` in my screen, so this seems ok to me

**Comment by nolan-m** [comment]
Having this problem as well and its definitely related to screenProps.

**Comment by GertjanReynaert** [comment]
Update 2: I only have this issue in the iOS simulator, in the android simulator (genymotion) I'm able to debug

**Comment by GertjanReynaert** [comment]
The issue seems to be resolved in beta7
