### ISSUE TITLE
Tab indicator's view component style.

### ISSUE THREAD

**Issue by kamalk333** [react-community/react-navigation#612]
I want to give styles to my "Tab indicator" such that the indicator slider on the top part of its view (attaching a screenshot of my design).

The view container of this indicator is fixed to the bottom part of the header. I want to take this little bit up in the header bar.

what I feel is, this indicator should be fixed under the label's. 

![issue-indicator](https://cloud.githubusercontent.com/assets/22167533/23703362/8ce36964-0425-11e7-8617-f3842f193855.png)

**Comment by ldipasquale** [comment]
You could try setting a black View as the tab icon for each scene.

Something like this:

```
YourScene.navigationOptions = {
  tabBar: {
    icon: ({ focused }) => (
      focused && (
        <View style={{ backgroundColor: '#000', width: 20, height: 2, alignSelf: 'center' }} />
      );
    ),
  },
};
```

**Comment by spencercarli** [comment]
Hi! In an effort to reduce the number of open issues I'm closing question-type issues that would be a better for for the [react-navigation tag on StackOverflow](https://stackoverflow.com/questions/tagged/react-navigation). This is nothing personal, merely trying to get the # of issues to a more manageable level. If you think this issue should be re-opened please let me know. Thanks!
