### ISSUE TITLE
Access header in nested navigator

### ISSUE THREAD

**Issue by microwavesafe** [react-community/react-navigation#613]
I need to turn the back button (left component) on and off from a nested navigator and I can't see how to do it. My setup is this.

StackNavigator
--Stack 1,
--Stack 2,
--TabNavigator
----Tab 1
----Tab 2
----StackNavigator
------Stack 1 
------Stack 2 <- need to turn on back button (left component) in header here

here are the navigator setups

```
export const NestedStack = StackNavigator({
    NestedStack1: {
        screen: NestedStack1,
        navigationOptions: {
            header: (navigation, defaultHeader) => ({
                ...defaultHeader,
                left: null,
            }),
        },
    },
    NestedStack2: {
        screen: NestedStack2,
    },
});

export const MainTabs = TabNavigator({
    Tab1: {
        screen: Tab1,
        navigationOptions: {
            header: (navigation, defaultHeader) => ({
                ...defaultHeader,
                left: null,
            }),
        },
    },
    Tab2: {
        screen: Tab2,
        navigationOptions: {
            header: (navigation, defaultHeader) => ({
                ...defaultHeader,
                left: null,
            }),
        },
    },
    NestedNavigator2: {
        screen: NestedStack,
    },
},{
  navigationOptions: {
        header: {
            visible: true,
            backTitle: null,
            style: {
                backgroundColor: '#00acec',
            },
            tintColor: '#fff'
        }
    },
});

export const MainStack = StackNavigator({
    MainStack1: {
        screen: MainStack1,
    },
    MainStack2: {
        screen: MainStack2,
    },
    NestNavigator1: {
        screen: MainTabs,
    },
}, {
    headerMode: 'screen',
});
```
I only want the back button to appear on the NestedStack2 page, but if I try to set anything in the header options I get a second header with the new settings. For example the code above will generate two headers on the NestedStack1 page.

So does anyone know how to change the settings of the parent header from a child nested navigator?

**Comment by kamalk333** [comment]
I just did this today.

In the navigationOptions of your 2nd stacknavigator, just put this object

header:{
//your earlier code
   left: true, <- this is what you require.
}

**Comment by microwavesafe** [comment]
@kamalk333 For me if I do that I end up with a second header underneath the first one. The top one is styled as per the TabNavigator and the second one has the back button and is default styled. Do you not get two headers when you try to change the settings on a nested page?

I tried hiding the TabNavigator header and styling the NestedStack header as required, which works, but due to #578 it looks really bad. When you navigate to one of the tabs there is no header, until a second later when the header appears. And when you navigate to one of the NestedStack pages you get two headers until a second later is removes the top one. So I can't really use that.

**Comment by microwavesafe** [comment]
@kamalk333 here is what I tried

```
export const NestedStack = StackNavigator({
    NestedStack1: {
        screen: NestedStack1,
    },
    NestedStack2: {
        screen: NestedStack2,
    },
},{
    navigationOptions: {
        header: {
            left: true, <-- this creates a second header below the first
        },
    }
});

export const MainTabs = TabNavigator({
    Tab1: {
        screen: Tab1,
    },
    Tab2: {
        screen: Tab2,
    },
    NestedNavigator2: {
        screen: NestedStack,
    },
},{
  navigationOptions: {
        header: {
            visible: true,
            left: null,
            backTitle: null,
            style: {
                backgroundColor: '#00acec',
            },
            tintColor: '#fff'
        }
    },
});

export const MainStack = StackNavigator({
    MainStack1: {
        screen: MainStack1,
    },
    MainStack2: {
        screen: MainStack2,
    },
    NestNavigator1: {
        screen: MainTabs,
    },
}, {
    headerMode: 'screen',
});
```

**Comment by kamalk333** [comment]
Try to give navigationOptions to the components file.

export const NestedStack = StackNavigator({
    NestedStack1: {
        screen: NestedStack1,
    },
    NestedStack2: {
        screen: NestedStack2,
    },
}

Now in your NestedStack2 Component,

define navigationOptions before render function like

export default class NestedStack2 extends Component{
    static navigationOptions = {
       header:{
            left: true
       }
   }
     render(){
         .................
}

By this method of putting navigationOptions in their respective component creates their own navigation configuration.
What you have done is you have created a single navigationOptions for both of your components.

**Comment by microwavesafe** [comment]
@kamalk333 I think it's more fundamental than that. If I don't explicitly set header: {visible:false} in the nested StackNavigator I get a second header. For example
```
export const NestedStack = StackNavigator({
    NestedStack1: {
        screen: NestedStack1, <-- these pages have a second header
    },
    NestedStack2: {
        screen: NestedStack2,<-- these pages have a second header
    },
});

export const MainTabs = TabNavigator({
    Tab1: {
        screen: Tab1,
    },
    Tab2: {
        screen: Tab2,
    },
    NestedNavigator2: {
        screen: NestedStack,
    },
},{
  navigationOptions: {
        header: {
            visible: true,
            left: null,
            backTitle: null,
            style: {
                backgroundColor: '#00acec',
            },
            tintColor: '#fff'
        }
    },
});

export const MainStack = StackNavigator({
    MainStack1: {
        screen: MainStack1,
    },
    MainStack2: {
        screen: MainStack2,
    },
    NestNavigator1: {
        screen: MainTabs,
    },
}, {
    headerMode: 'screen',
});
```

**Comment by kamalk333** [comment]
@microwavesafe Is it working there?

**Comment by microwavesafe** [comment]
@kamalk333 no, I always get two headers. I don't think anyone wants two headers, so I might start another issue.

**Comment by hugopretorius72** [comment]
Anyone get a fix for this?
