### ISSUE TITLE
StackNavigator inside StackNavigator produces two headers

### ISSUE THREAD

**Issue by microwavesafe** [react-community/react-navigation#614]
When putting a StackNavigator inside a StackNavigator you get two headers. I don't think this is desirable behaviour in any situation. You can turn off the header in the nested StackNavgiator, but this means you can't change settings in the nested StackNavigator pages. I've created a very simple app to demonstrate the problem.

app.js
```
import React from 'react'
import { AppRegistry } from 'react-native'
import { StackNavigator } from 'react-navigation'

import Stack1 from './Stack1'
import NestedStack1 from './NestedStack1'

const NestedStack = StackNavigator({
    NestedStack1: {
        screen: NestedStack1,
    },
});

const MainStack = StackNavigator({
    Stack1: {
        screen: Stack1,
    },
    NestedNavigator: {
        screen: NestedStack,
    },
}, {
    headerMode: 'screen',
});

AppRegistry.registerComponent('NestedStack', () => MainStack);
```
Stack1.js
```
import React, { Component } from 'react';
import {
    View,
    Button,
    Text,
} from 'react-native';

export default class Stack1 extends Component {

    _goDownALevel = () => {
        console.log(this.props.navigation)
        this.props.navigation.navigate("NestedNavigator");
    };

    render() {
        return (
            <View>
                <Button title='Go to nested stack' onPress={this._goDownALevel} />
                <Text>Stack1</Text>
            </View>
        )
    }
}
```
NestedStack1.js
```
import React, { Component } from 'react';
import {
    Text,
} from 'react-native';

export default class NestedStack1 extends Component {
    render() {
        return (
            <Text>NestedStack1</Text>
        )
    }
}
```
Pushing the button on the first page, sends you to a second page with two headers. I think if a StackNavigator has a parent StackNavigator it's header settings should be merged, not used to create a second header. What do you think?

![screenshot_1488983222](https://cloud.githubusercontent.com/assets/1586235/23707755/6271fa84-040b-11e7-9276-900fc93dd50c.png)

![screenshot_1488983224](https://cloud.githubusercontent.com/assets/1586235/23707751/5caf44a8-040b-11e7-8edf-9b4e03acb9f9.png)

**Comment by microwavesafe** [comment]
So I've completely abused the screenProps system in this commit microwavesafe/react-navigation@e57b61e but can you see what I'm getting at to prevent multiple headers? I ended up using screenProps as it was already passed down.

Is there an easier way to do it?

**Comment by JonasWho** [comment]
+1, I have the exact same issue.

**Comment by HyperSimon** [comment]
+10086

**Comment by grabbou** [comment]
I am closing this issue in favour of #88 where we are tracking better integration of these stack navigators.

**Comment by jeremyong** [comment]
I think the much easier way is to set the navigationOptions property on the nested stack navigator to disable header visibility @microwavesafe @JonasWho

**Comment by mukul-raina** [comment]
@HyperSimon you're a life saver. Thank you!

**Comment by lucas1richard** [comment]
I know this is closed, but I found a workaround: https://gist.github.com/lucas1richard/605af948f77b5599c6c587da272c5cb1

Basically, wrap the sub-navigation in a screen with `header: null` and pass down the navigation object from that screen. It is used in the initial screen of the sub-navigation to get back to the parent navigation.

**Comment by jskidd3** [comment]
@HyperSimon Whilst your solution works it disables header transitions between views in the nested stack. Do you know if there's a way around this?

**Comment by quantumpotato** [comment]
@HyperSimon how do I then customize the header on the B stack?

**Comment by avet-m** [comment]
@quantumpotato did you find any solution for custom header for nested navigator screeens?

**Comment by quantumpotato** [comment]
I just switched to a different stack entirely by putting multiple tabnavigators inside a switch navigator.
So a Switch navigator is the top component.

**Comment by artsnr1** [comment]
@jskidd3 same issue. Did you find a workaround

**Comment by wadeenghoiwa** [comment]
> My project structure is as follows
> -- stacknavigator( We call it A)
> ---- tabnavigator
> ---- stacknavigator( We call it B)
> 
> this is A look like
> 
> ```js
> // your stack navigator
> const App = StackNavigator(
> {...},
>   { headerMode: 'screen' }
> )
> ```
> 
> this is B look like
> 
> ```js
> const CustomerManagerStack = StackNavigator(
>   {... },
>   { headerMode: 'none' }
> )
> ```
> 
> And it work for me.
> 
> ![2017-03-27 6 14 13](https://cloud.githubusercontent.com/assets/9377192/24351686/4a61a332-1319-11e7-8ff4-23324b464c76.png)

Alternative way:
`<Stack.Navigator
      initialRouteName="Create New Sticker"
      headerMode="screen"
    >
      <Stack.Screen name="Create New Sticker" component={Home} />
      <Stack.Screen name="Create New Sticker Stack" component={CreateNewStickerStack} />

    </Stack.Navigator>`

`<Stack.Navigator
      initialRouteName="Create New Sticker"
      headerMode="none" // prevent duplicated header
    >
      <Stack.Screen name="Create New Sticker" component={CreateNewSticker} />
      
    </Stack.Navigator>`

**Comment by wadeenghoiwa** [comment]
> > My project structure is as follows
> > -- stacknavigator( We call it A)
> > ---- tabnavigator
> > ---- stacknavigator( We call it B)
> > this is A look like
> > ```js
> > // your stack navigator
> > const App = StackNavigator(
> > {...},
> >   { headerMode: 'screen' }
> > )
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > this is B look like
> > ```js
> > const CustomerManagerStack = StackNavigator(
> >   {... },
> >   { headerMode: 'none' }
> > )
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And it work for me.
> > ![2017-03-27 6 14 13](https://cloud.githubusercontent.com/assets/9377192/24351686/4a61a332-1319-11e7-8ff4-23324b464c76.png)
> 
> Alternative way:
> `<Stack.Navigator
> initialRouteName="Create New Sticker"
> headerMode="screen"
> >
> <Stack.Screen name="Create New Sticker" component={Home} />
> <Stack.Screen name="Create New Sticker Stack" component={CreateNewStickerStack} />
> 
> ```
> </Stack.Navigator>`
> ```
> 
> `<Stack.Navigator
> initialRouteName="Create New Sticker"
> headerMode="none" // prevent duplicated header
> >
> <Stack.Screen name="Create New Sticker" component={CreateNewSticker} />
> 
> ```
> </Stack.Navigator>`
> ```
