### ISSUE TITLE
White flash in whole screen when back button pressed in StackNavigator

### ISSUE THREAD

**Issue by cosivox** [react-community/react-navigation#619]
There is a white flash when back button in StackNavigator is pressed and going back to previous screen I think it's because of the root.view.background and the transition animation with changing opacity but I notice there's not such effect on native iOS apps. Example:

![simulator screen shot mar 8 2017 11 56 05 am](https://cloud.githubusercontent.com/assets/5602777/23716552/39bd5800-03f6-11e7-9503-8ccc1503eae7.png)

Versus:
![simulator screen shot mar 8 2017 11 49 43 am](https://cloud.githubusercontent.com/assets/5602777/23716454/01755632-03f6-11e7-8a8e-ac400f4c277c.png)

I think the solution would be allow to specify the opacity change in default transition

**Comment by ddeanto** [comment]
Try passing in `CardStyle` to your navigator:

```
const AppNav = StackNavigator(
  {
    startupTasks: { screen: StartUpTasks },
    auth: { screen: Login },
    main: { screen: DrawerNav },
  },
  {
    cardStyle: {
      opacity: 1,
    }
  }
);
```

**Comment by cosivox** [comment]
@ddeanto Not working, seems that it only changes the main view opacity so it becomes hidden/invisible.

The solution that I found for now is to modify the "forHorizontal" transition in the "src/views/CardStackStyleInterpolator.js" and setting the opacity of the transition to 1:

`const opacity = 1;`

**Comment by cosivox** [comment]
@ddeanto It worked! Thank you, where's that in documentation or how did you find it?

**Comment by ddeanto** [comment]
@cosivox I referenced https://github.com/react-community/react-navigation/issues/440 where I saw they set `shadowOpacity` to solve their issue. So, I got lucky and tried `opacity` which was just a lucky guess and it worked - I didn't see it in anywhere in the documentation lol

**Comment by cosivox** [comment]
@ddeanto Haha cool, I guess there's still a lot to do about documentation. Thanks again.

**Comment by joshuajtaylor** [comment]
Thanks, this helped! backgroundColor also works and actually did what I was looking for. That way you can keep the opacity animation.
This worked for me with my darker screens:
```
cardStyle: {
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
```
or
```
cardStyle: {
    backgroundColor: '#000',
  },
```

**Comment by flyskywhy** [comment]
When use DrawerNavigator and StackNavigator, need:

    cardStyle: {
        backgroundColor: 'transparent',
    },

and need:

use [react-native-root-view-background](https://github.com/johniak/react-native-root-view-background) to setRootViewBackgroundColor('black')

**Comment by steniowagner** [comment]
When you're using react-navigation V3, you just need to set the headerMode prop as follow:

```
const RootStack = createStackNavigator(
  {
    'SCREEN': {
      screen: MyScreen,
    },
  },
  {
      headerMode: 'screen',
  },
);
```

**Comment by nihp** [comment]
@steniowagner I am using react-navigation version 3. When I am navigating from the stack navigator to the header right element, UI shows a white spalsh.

How can I resolve this error.

cardStyle not works for me

**Comment by baquy96** [comment]
It works for me.
`cardStyle: {
      opacity: 1,
      shadowOpacity: 1
}`

**Comment by sharadrb** [comment]
Nothing worked for me with React Navigation 4. This is what worked for me to resolve flickering.
animationEnabled: false
