### ISSUE TITLE
Is it possible to push a new view, that has a *different* nav bar height than the parent?

### ISSUE THREAD

**Issue by ajonno** [react-community/react-navigation#623]
This seems simple in concept but seeing some probs. Example is, the root view, has a "nav bar" with a height of 120 pixels (say). User taps a button on this root view, and so we push a new view. This new view, has a "nav bar" with a height of 70 pixels.

That's it. How can we achieve this ?

**Comment by grabbou** [comment]
You can set `navigationOptions.header.style` and set the height to be whatever you want.

**Comment by ajonno** [comment]
wicked thanks Mike! is this same feature available on ex-navigation ? i did a search on the github repo but couldn't find a navigationOptions object ?
