### ISSUE TITLE
Update navbar background color (iOS)?

### ISSUE THREAD

**Issue by IWCollege-AaronBentley** [react-community/react-navigation#626]
Hello,

I have a typical master->detail listView, and each item has it's own brand color (stored as a standard hex code).

When a user taps on a list item, I then navigate to the detail view and I'd like to update the background color of the navbar to the items brand color, but I can't seem to  get it to work 😬

I've tried the following attempts within the detail view navigationOptions (trimmed for brevity): 

```
static navigationOptions = {
        title: ({state}) =>  state.params.data.name,
        header: {
            style: {
                backgroundColor: '#0294cb',  // Works fine with a standard string
                // backgroundColor: ({state}) => state.params.data.accent_color // Errors
                // backgroundColor: ({state}) => { return state.params.data.accent_color } // Errors
            },
            ...
```

When it errors, the message i'm receiving in the debugger is: 

`Warning: Failed prop type: Invalid prop 'backgroundColor' supplied to 'View': function backgroundColor(_ref2) {
                var state = _ref2.state;
                return state.params.data.accent_color;
            }
Valid color formats are
  - '#f0f' (#rgb)
  - '#f0fc' (#rgba)
  - '#ff00ff' (#rrggbb)
  - '#ff00ff00' (#rrggbbaa)
  - 'rgb(255, 255, 255)'
  - 'rgba(255, 255, 255, 1.0)'
  - 'hsl(360, 100%, 100%)'
  - 'hsla(360, 100%, 100%, 1.0)'
  - 'transparent'
  - 'red'
  - 0xff00ff00 (0xrrggbbaa)

Bad object: {
  "paddingTop": 20,
  "height": 64,
  "shadowColor": "black",
  "shadowOpacity": 0.1,
  "shadowRadius": 0.3333333333333333,
  "shadowOffset": {
    "height": 0.3333333333333333
  },
  "elevation": 4
}
    in View (created by AnimatedComponent)
    in AnimatedComponent (created by Header)
    in Header (created by Transitioner)
    in RCTView (created by View)
    in View (created by Transitioner)
    in RCTView (created by View)
    in View (created by Transitioner)
    in Transitioner (created by CardStack)
    in CardStack (created by Unknown)
    in Unknown (created by Navigator)
    in Navigator (created by NavigationContainer)
    in NavigationContainer
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
`

Any help or advice welcomed, thanks in advance,

Aaron Bentley.

![simulator-screen-shot-9-mar-2017 -11 59 14](https://cloud.githubusercontent.com/assets/6940392/23749926/7609a300-04c2-11e7-926b-5a66c860a514.png)

![simulator-screen-shot-9-mar-2017 -12 00 40](https://cloud.githubusercontent.com/assets/6940392/23749932/8052afbe-04c2-11e7-9c9c-c6c00bae9956.png)

**Comment by pvinis** [comment]
would you mind answering too?

**Comment by IWCollege-AaronBentley** [comment]
@pvinis Sure,
In the detail view (as in, after the user taps on a list item), I added the following static navigationOptions...

```
static navigationOptions = {
    header: (navigation, defaultHeader) => ({
        ...defaultHeader,
        style: {
            backgroundColor: navigation.state.params.data.accent_color
        }
    })
}
```

Hope this helps you 😁

**Comment by pvinis** [comment]
ah so it was the `...defaultHeader` missing then? ok, i think i had the same problem. thanks for sharing.

**Comment by IWCollege-AaronBentley** [comment]
You're welcome @pvinis, I needed to set the header prop as a function, that takes the 'navigation' & 'defaultHeader' arguments.

This lets you merge your screen customisations with the default header `...defaultHeader`.
