### ISSUE TITLE
Redux Navigation/NAVIGATE to nested tab inside a stack

### ISSUE THREAD

**Issue by onlydave** [react-community/react-navigation#627]
Layout of the app is as follows

* Drawer
  * Main Stack
    * Home
    * Competition
      * Tab 1
      * Tab 2
      * CompetitionNews
      * Tab 4
      * Tab 5

By adding the drawer to our redux store with `router.getStateForAction` we're able to navigate to any route with dispatch `Navigation/NAVIGATE`. 

My question is what's the intended way to navigate to a tab that's nested in a stack that's not currently open?

Dispatching two navigate actions one after another works:
```
this.props.dispatch({
  type: 'Navigation/NAVIGATE', 
  routeName: 'CompetitionOverview',
});

this.props.dispatch({
  type: 'Navigation/NAVIGATE', 
  routeName: 'CompetitionNews',
});
```

Using the subrouter action seems better but results in **nothing** at all happening
```
this.props.dispatch({
  type: 'Navigation/NAVIGATE', 
  routeName: 'CompetitionOverview',
  action: this.props.dispatch({
    type: 'Navigation/NAVIGATE', 
    routeName: 'CompetitionNews',
  }),
});
```

Am I misunderstanding how nested navigators should work?
Does the the tab navigation need to wait until the stack has opened?

**Comment by chadi-kazan** [comment]
may i ask how you made the drawer navigator work with redux? i struggled with it so i let it go for now waiting for some decent examples to come up but i am interested in the approach you used.
thanks

**Comment by allpwrfulroot** [comment]
I'm seeing a similar issue, even sans redux. When I try to navigate back to a particular tab from the DrawerNavigator, I can only navigate to the tab that was NOT selected previously. 

Drawer:
  * Tab1
  * Tab2
  * ScreenOther
  * Etc

Through the Drawer:
Tab1 -> ScreenOther -> Tab2 works just fine, as does Tab2 -> ScreenOther -> Tab1
Tab1 -> ScreenOther -> Tab1 does NOTHING (no error, even), as does Tab2 -> ScreenOther -> Tab2

**Comment by onlydave** [comment]
@chadi-kazan 

```
import { combineReducers } from 'redux';
import AppDrawerNavigation from 'S_AppDrawerNavigation';

const appReducers = combineReducers ({
  ...,
  AppDrawer: (state,action) => AppDrawerNavigation.router.getStateForAction(action,state),
});
```

AppDrawerNavigation is just a DrawerNavigator that then loads a stack navigator. From there if we want to navigate somewhere we just dispatch types like in my first comment.

Also had to add an event listener for the android hardware back button.
```
import RN, { Platform } from 'react-native';
...
  constoructor (props) {
  ...
    if (Platform.os === 'android') {
      RN.BackAndroid.addEventListener('hardwareBackPress', () => {
        return this.props.dispatch({
          type: 'Navigation/BACK',
        });
      });
    }
  }
```

Haven't found a way around the original problem though

**Comment by spencercarli** [comment]
Hi! Since this issue has been quiet for a while I'm going to go ahead and close it. If the issue persists in the latest version of React Navigation please re-open!
