### ISSUE TITLE
tabBar label dynamic configuration

### ISSUE THREAD

**Issue by vernetztekirche** [react-community/react-navigation#628]
Is there a way to set the label of a Tab dynamically, so that the label is set from the state of the component? I couldn't find any example and all my attempts didn't work.
```
static navigationOptions = {
    tabBar: ({ state }) => ({
      label: 'Tab Label', <---- configure this dynamically ? eg. state.params.label
      ...
    }),
  };
```

**Comment by mfclarke** [comment]
I can't quite figure this out either. I know you probably use `state.params`, but I don't know how to set `state.params` initially. When you're using a `StackNavigator` you can set params when you call `navigate` or use `initialRouteParams`, but `navigate` is never called for `TabsNavigator` and there is no `initialRouteParams`.

**Comment by vernetztekirche** [comment]
I found a solution with a pure function:

```
static navigationOptions = {
    title: 'Karte',
    tabBar: ({ state }) => ({
            label: setTabLabel(state),
            icon: (<Image source={require('./img/map-android.png')} />)
        }),
  };
```

and the function with a Config-Object, which holds different languages for the Label. Now I can change the language of the app and the label changes:

```
function setTabLabel(state){
  if(state.params != undefined){
    return Config[state.params.lang][state.key];
  } else {
    return Config[Config.lang][state.key];
  }
}
```

**Comment by mfclarke** [comment]
@vernetztekirche thanks for the answer. How are you setting the `lang` param initially? My `TabNavigator`'s `state` has no `params`, even after calling `setParams`.

**Comment by vernetztekirche** [comment]
if `state.params` is undefined, I set it from `Config.lang` . The initial lang is taken from:
Android: `var userlang = NativeModules.I18nManager.localeIdentifier;`
iOS: `var userlang = NativeModules.SettingsManager.settings.AppleLocale;`
When the language is changed by a button, I call a method in the Navigator 
```
_changeLangReload(newLang){
    ...
    const setParamsActionKarte = NavigationActions.setParams({
      params: { lang : newLang },
      key: 'titleTab1',
    })
    this.props.navigation.dispatch(setParamsActionKarte);

   ...

}
```

**Comment by mfclarke** [comment]
Ahh, got it. Thanks!
