### ISSUE TITLE
Tab examples are broken: Invalid layout forRCTView...

### ISSUE THREAD

**Issue by sectore** [react-community/react-navigation#63]
Tab examples of [`HelloHybrid`](https://github.com/react-community/react-navigation/tree/master/examples/HelloHybrid) ([SettingsView](https://github.com/react-community/react-navigation/blob/master/examples/HelloHybrid/screens/Settings.js)) and [`NavigationPlayground`](https://github.com/react-community/react-navigation/tree/master/examples/NavigationPlayground)  ([StacksInTabs](https://github.com/react-community/react-navigation/blob/master/examples/NavigationPlayground/js/StacksInTabs.js) / [CustomTabs](https://github.com/react-community/react-navigation/blob/master/examples/NavigationPlayground/js/CustomTabs.js)) are broken with following error:

![error](https://cloud.githubusercontent.com/assets/47693/22398099/a2f97266-e580-11e6-9e7e-969846df59cb.png)

This issues occurs using latest `react-native-tab-view` [ v.0.0.53](https://github.com/react-native-community/react-native-tab-view/releases/tag/v0.0.53). 

Downgrading to `react-native-tab-view` [v.0.0.52](https://github.com/react-native-community/react-native-tab-view/releases/tag/v0.0.52) does fix this issue.

**Comment by satya164** [comment]
Hmm. It worked fine when I tried it last time. But I get the error after reinstall. Will check now.
