### ISSUE TITLE
tabPress or onChangeTab

### ISSUE THREAD

**Issue by quangas** [react-community/react-navigation#630]
Has anyone worked out how to add this event in the tabBar? Or should I use a different tab bar control and somehow make it work with reactnavigation?

**Comment by samwise00** [comment]
Also interested in this.

**Comment by superquest** [comment]
This is being discussed here:
https://github.com/react-community/react-navigation/issues/630

@satya164 I think you can close this

**Comment by spencercarli** [comment]
Hi! Since this issue has been quiet for a while I'm going to go ahead and close it. If the issue persists in the latest version of React Navigation please re-open!
