### ISSUE TITLE
can I use a <View> with child components to render the header ?

### ISSUE THREAD

**Issue by ajonno** [react-community/react-navigation#631]
As per the animated gif here - how can I render a ```<View>``` as the header, so that i can (for example) use a background Image, use color gradient (```<LinearGradient>```) ? Pretty urgent so appreciate quick feedback. Thanks!

![2017-03-08_22-55-26](https://cloud.githubusercontent.com/assets/3005269/23773843/1baa6f6c-0575-11e7-995d-d4c1a53525a8.gif)

**Comment by darleikroth** [comment]
If there is a way, I would like to know too. It is possible to add a custom component below the title?

**Comment by rafaelmotta** [comment]
+1 

![screen shot 2017-03-30 at 8 09 12 pm](https://cloud.githubusercontent.com/assets/446731/24529888/cf684424-1584-11e7-8a34-cfc36f9875a1.png)

Anyone?

**Comment by MatthieuPeyrot** [comment]
+1

**Comment by ajonno** [comment]
does anyone know if this is possible yet ?

**Comment by marlonoso** [comment]
+1 for Gradient

**Comment by DjangoGG** [comment]
+1 for gradient
the react-native-router-flux can easily set a background image in nav bar but still cant fide a workaround here

**Comment by choipd** [comment]
+1 linear gradient

**Comment by cosio55** [comment]
+1

**Comment by alecsutzuu** [comment]
+1

**Comment by spencercarli** [comment]
You can accomplish this by creating your own [header component](https://reactnavigation.org/docs/navigators/stack#header). The [existing header](https://github.com/react-community/react-navigation/blob/master/src/views/Header/Header.js) is a good starting point.
