### ISSUE TITLE
passing down ActionCreator props to child Screens

### ISSUE THREAD

**Issue by rodzzlessa24** [react-community/react-navigation#632]
I'm having an issue with passing down my `ActionCreators` from my Nav component down to its scenes.

I have an `AppContainer` that wraps the entire application.

```javascript
    import React, { Component } from 'react';
    import { DrawerNavigator, addNavigationHelpers } from 'react-navigation';
    import { connect } from 'react-redux';
    import { bindActionCreators } from 'redux';
    
    import { ActionCreators } from '../actions';
    
    import DashboardContainer from './DashboardContainer';
    import CustomersContainer from './CustomersContainer';
    
    
    const ApplicationNavigation = DrawerNavigator({
      Dashboard: { screen: DashboardContainer },
      Customers: { screen: CustomersContainer },
    });
    
    class AppContainer extends Component {
      render() {
        return (
          <ApplicationNavigation />
        );
      }
    }
    
    function mapDispatchToProps(dispatch) {
      return bindActionCreators(ActionCreators, dispatch);
    }
    
    export default connect(() => { return {} }, mapDispatchToProps)(AppContainer);

```

Here is the CustomerContainer:

```javascript
    import React, {Component} from 'react';
    import {View, Text, Button} from 'react-native';
    
    export default class CustomerContainer extends Component {
        btnPressed() {
            this.props.listCustomers()
        }
    
        render () {
            return (
                <View style={{marginTop: 40}}><Text>Customer</Text>
                <Button onPress={() => this.btnPressed()} title="Press Me!" />
                </View>
            );
        }
    }

```
Now I'm trying to call an action within my `CustomerContainer` `this.props.listCustomers()`. The problem is the ActionCreator props aren't being passed down to the screens. I've tried doing adding the `screenProps` prop to the `ApplicationNavigation` component:

```javascript
<ApplicationNavigation screenProps={this.props} />
```

But for some reason when I do this my app doesn't display any screens its just blank with no errors.

**Comment by andfs** [comment]
@rodzzlessa24 can you tell me how did you solve this problem? I'm facing the same issue.

**Comment by rishabhbhatia** [comment]
@rodzzlessa24 @andfs Were you guys able to find a solution

**Comment by rodzzlessa24** [comment]
@andfs @rishabhbhatia So I wasn't able to find a "solution" per say I just went about the problem a bit differently. instead of hooking up the props within the `ApplicationNavigation`  component I did it in the `CustomerComponent`. Whenever one of the child elements from the `CustomerComponent` needs access to action creators I just pass it down as a prop. For example:

``` javascirpt
    import React, {Component} from 'react';
    import {View, Text, Button} from 'react-native';

   import {Foo} from './foo';
    
    export default class CustomerContainer extends Component {
        btnPressed() {
            this.props.listCustomers()
        }
    
        render () {
            return (
                <View style={{marginTop: 40}}><Text>Customer</Text>
                    <Foo {...this.props}></Foo>
                    <Button onPress={() => this.btnPressed()} title="Press Me!" />
                </View>
            );
        }
    }
```

**Comment by wilomgfx** [comment]
If y'all are interested in a way to do from it, i did it like this :

```typescript 

<AppNavigator
        navigation={addNavigationHelpers({
            dispatch: this.props.dispatch,
            state: this.props.nav,
            ...bindActionCreators(actionCreators, this.props.dispatch),
        })}
        screenProps={this.props}
      />

```

This way i can access my action creators as : `this.props.navigation.**myActionCreator()**`

**Comment by kodayashi** [comment]
@wilomgfx - Is that approach still working for you? Are you passing in the `addListener` now per the documentation here: https://github.com/react-navigation/react-navigation/blob/master/examples/ReduxExample/src/navigators/AppNavigator.js ?

I'm trying your approach as I've also bound action creators and avoid explicitly using `dispatch` in my containers. The example app in the repo though uses dispatch off of the navigation prop...

**Comment by wilomgfx** [comment]
@kodayashi still is, i have not updated react-navigation yet, so my approach still works.
