### ISSUE TITLE
How to push a screen from bottom to up?

### ISSUE THREAD

**Issue by musicode** [react-community/react-navigation#633]

**Comment by enbashi** [comment]
`mode: 'modal'` in StackNavigatorConfig

https://reactnavigation.org/docs/navigators/stack

**Comment by zhipenglin** [comment]
can I set the config dynamically，different screen set different value?

**Comment by jeffreymendez1993** [comment]
@zhipenglin  currently you cannot.

**Comment by gregblass** [comment]
Hmm. So I've got a stack navigator. Works great, but on the home screen I'd like an about page that slides up instead of left -> right.

This really isn't possible? What about nesting navigators?

**Comment by spencercarli** [comment]
Hi! Since this issue has been quiet for a while I'm going to go ahead and close it. If the issue persists in the latest version of React Navigation please re-open!

**Comment by Alexorz** [comment]
same question

**Comment by dinhtrumdieu** [comment]
<Stack.Screen
        name=".."
        component={...}
        options={{...TransitionPresets.ModalSlideFromBottomIOS}}
      />

react navigation version 5.0

**Comment by RicardoBrito1938** [comment]
Hello, just to update in case some one comes digging until here, on react navigation 6.0 you can use animation prop to have this effect

 <Navigator
    linking={linking}
    initialRouteName="Settings"
    screenOptions={{
      headerShown: false,
      animation: 'slide_from_bottom',
    }}
  >

or 

 <Navigator
    linking={linking}
    initialRouteName="Settings"
    screenOptions={{
      headerShown: false,
      animation: 'fade_from_bottom',
    }}
  >

**Comment by imoempire** [comment]
Can you slide from the top?
