### ISSUE TITLE
How do I pass initial props (or launchoptions) to first scene?

### ISSUE THREAD

**Issue by joshuapinter** [react-community/react-navigation#634]
I set a simple prop in Android via the `launchoptions`, which is the third param of `startReactApplication`. 

My first scene's constructor props would be something like `{ someProp: 'somePropValue' }` and that was great.

I'm implementing `react-nativation` now and I'm just trying to setup the initial `StackNavigator` like this: 

```js
const HelloWorld = StackNavigator({
  Home: { screen: HomeScreen },
});


AppRegistry.registerComponent('HelloWorld', () => HellowWorld);
```

Now my `someProp` doesn't come up with the HomeScreen's constructor. How do I pass my initial props into the `HomeScreen`?

Many Thanks.

**Comment by grabbou** [comment]
Use `screenProps` as demonstrated on this page https://reactnavigation.org/docs/navigators/navigation-options#Screen-Navigation-Options

**Comment by joshuapinter** [comment]
Thanks for the response but please do not close this Issue without providing a working solution. I tried the `screenProps` methods in a variety of ways initially and could not get a variable to be passed from the `registerComponent` method on launch. 

If you could re-open this until a solution is shown here that works, that would be greatly appreciated. 

Thanks.

**Comment by grabbou** [comment]
Sorry if my comment wasn't helpful - I was referring to that #876, esp. my comment: https://github.com/react-community/react-navigation/issues/876. 

If none of the solutions presented there work for you, please comment there and we will see what we can do to make it working.

**Comment by joshuapinter** [comment]
@grabbou That's much more helpful, thanks. I'll take a look when I have time and see if I can get it working.

**Comment by grabbou** [comment]
Sure, let me know if there's any problem later ;)

**Comment by joshuapinter** [comment]
Can you please re-open this, @grabbou. I looked at the comment you made on the other Issue and still cannot access the `initialProps` from inside the first scene.

Thanks.

**Comment by joshuapinter** [comment]
Okay, finally understood the approach you were taking and managed to get it working. To help others, here is a full solution:

```js
import React from 'react';

import {
  AppRegistry,
  Text,
} from 'react-native';

import { StackNavigator } from 'react-navigation';

class MyApp extends React.Component {
  render() {
    console.log('this.props in MyApp', this.props); // This will list the initialProps.

    // StackNavigator **only** accepts a screenProps prop so we're passing
    // initialProps through that.
    return <Navigator screenProps={this.props} />; 
  }
}

class HomeScreen extends React.Component {
  render() {
    console.log('this.props in HomeScreen', this.props);
    // This will output something like this: 
    // { screenProps: { ...your initialProps }, navigation: { ...StackNavigator stuff... } }

    return <Text>My initialProps are {JSON.stringify(this.props.screenProps)}.</Text>;
  }
}

const Navigator = StackNavigator({
  Home: { screen: HomeScreen },
});

AppRegistry.registerComponent('MyApp', () => MyApp);
```

**Comment by Tom29** [comment]
@joshuapinter @grabbou 
`screenProps` basically isn't particular screen parameter. I was looking forthe answer. `screenProps` is like Navigator's property and all it's screen inherit it, not a particular screen property. 

Any way to do like this:

```
Home: { screen: Home, param: 'a'},
Detail: { screen: Detail, param: 'b'},
```

**Comment by joshuapinter** [comment]
A quick follow-up to my previous comment, for those that are looking to set the initial Route based on the initial props of the app, here is how I accomplished that: 

```js
import React from 'react';

import {
  AppRegistry,
  Text,
} from 'react-native';

import { StackNavigator } from 'react-navigation';

class MuskApp extends React.Component {
  render() {
    const Navigator = StackNavigator(
      {
        SpaceX: { screen: SpaceXScreen },
        Tesla:  { screen: TeslaScreen },
      },
      {
        initialRouteName: this.props.initialRoute, // Assumes you pass in "SpaceX" or "Tesla" as initialRoute with initialProps.
      }
    );

    return <Navigator screenProps={this.props} />; 
  }
}

class SpaceXScreen extends React.Component {
  render() {
    return <Text>SpaceX Baby!</Text>;
  }
}

class TeslaScreen extends React.Component {
  render() {
    return <Text>Tesla Baby!</Text>;
  }
}

AppRegistry.registerComponent('MuskApp', () => MuskApp);
```

Essentially bringing the `StackNavigator` into the `render()` method of the app. If you don't do this it will not update the `initialRoute` properly.

**Comment by dantman** [comment]
@joshuapinter That's going to create a brand new navigator if the root component is ever re-rendered. The Navigator should be created on mount as an instance prop instead.

**Comment by joshuapinter** [comment]
@dantman Yeah, that's true. I didn't think it would be a problem since it shouldn't be re-rendered unless you back out to the root. 

Care to adjust the code to show your method?

**Comment by joshuapinter** [comment]
@dantman I took another look at it to avoid any re-renders and ended up with composing a `MyStackNavigator`. Let me know if you think it can be improved.

```js
import React from 'react';

import {
  AppRegistry,
  Text,
} from 'react-native';

import { StackNavigator } from 'react-navigation';

class MuskApp extends React.Component {
  render() {
    return <MyStackNavigator {...this.props} />; 
  }
}

class MyStackNavigator extends React.Component {
  constructor(props) {
    super(props);

    this._StackNavigator = StackNavigator(
      {
        SpaceX: { screen: SpaceXScreen },
        Tesla:  { screen: TeslaScreen },
      },
      {
        initialRouteName: this.props.initialRoute, // Assumes you pass in "SpaceX" or "Tesla" as initialRoute with initialProps.
      }
    );
  }

  render() {
    let StackNavigator = this._StackNavigator;

    return <StackNavigator screenProps={this.props} />;
  }
}

class SpaceXScreen extends React.Component {
  render() {
    return <Text>SpaceX Baby!</Text>;
  }
}

class TeslaScreen extends React.Component {
  render() {
    return <Text>Tesla Baby!</Text>;
  }
}

AppRegistry.registerComponent('MuskApp', () => MuskApp);
```

**Comment by prabhu73** [comment]
> https://reactnavigation.org/docs/navigators/navigation-options#Screen-Navigation-Options

Link you provided is not working.

**Comment by brentvatne** [comment]
the documentation changed since over 1.5 years ago and that link doesn't work anymore but surely you're capable of searching the docs @prabhu73!

https://reactnavigation.org/docs/en/stack-navigator.html#navigator-props
