### ISSUE TITLE
navigationOptions header function has something wrong

### ISSUE THREAD

**Issue by musicode** [react-community/react-navigation#635]
```js
static navigationOptions = {
    title: 'xx',
    header: ({ state }) => {
        let { handleBackPress } = state.params
        return {
            left: <Button title="Back" onPress={handleBackPress} />
        }
    }
}
```

header function execute many times. if I set a breakpoint in it, it will execute again an again, never stop.

sometimes, I pass a `handleBackPress` by `setParams`，but when i press the button, nothing happened!

who can help me?

**Comment by briancalvium** [comment]
I got it working by making it: 
```
onPress={() => handleBackPress()}
```

Seems like it shouldn't matter

**Comment by crpr** [comment]
This is happening to me too. But it gives me undefined to my function

**Comment by spencercarli** [comment]
Hi! Since this issue has been quiet for a while I'm going to go ahead and close it. If the issue persists in the latest version of React Navigation please re-open!
