### ISSUE TITLE
StackNavigatorConfig.mode. card not work for android

### ISSUE THREAD

**Issue by MarsArbiter** [react-community/react-navigation#636]
the version is 1.0.0-beta.6.
and I work on react-native 0.41.2 and react 15.4.0

**Comment by PizzaLiu** [comment]
@MarsArbiter  it seems that you must set headerMode  to  'float' :  `headerMode: 'float',`

**Comment by spencercarli** [comment]
Hi! In an effort to reduce the number of open issues I'm closing issues that haven't had any activity in a while.

If you think this should be re-opened please let me know or, if you can, re-open it.

If this is a question please consider asking it on StackOverflow ([react-navigation](https://stackoverflow.com/questions/tagged/react-navigation))

Thanks!

**Comment by shopshow** [comment]
same issue here.
version: 1.0.0-beta.27
react-native version: 0.52.1
react version: 16.2.0
