### ISSUE TITLE
Is react-navigation going to become official replacement for React-native navigation? (Question)

### ISSUE THREAD

**Issue by jasan-s** [react-community/react-navigation#637]

**Comment by alvaromb** [comment]
It's not going to replace `NavigatorIOS` or `Navigator`. Only `NavigationExperimental` is going to get marked as deprecated. Anyway, `react-navigation` is now a recommended library in the official docs: http://facebook.github.io/react-native/docs/navigation.html#react-navigation

**Comment by satya164** [comment]
> It's not going to replace NavigatorIOS or Navigator.

For now. Eventually they'll be deprecated.

**Comment by alvaromb** [comment]
Yeah, maybe `NavigatorIOS` will not be deprecated, just move the maintenance to the community.

**Comment by shivanand217** [comment]
> It's not going to replace `NavigatorIOS` or `Navigator`. Only `NavigationExperimental` is going to get marked as deprecated. Anyway, `react-navigation` is now a recommended library in the official docs: http://facebook.github.io/react-native/docs/navigation.html#react-navigation



> It's not going to replace `NavigatorIOS` or `Navigator`. Only `NavigationExperimental` is going to get marked as deprecated. Anyway, `react-navigation` is now a recommended library in the official docs: http://facebook.github.io/react-native/docs/navigation.html#react-navigation

Bro its deprecated now.
