### ISSUE TITLE
Why does StackRouter.getStateForAction returns 1 route in the routes array?

### ISSUE THREAD

**Issue by godlevel** [react-community/react-navigation#638]
I've created a StackRouter: 

```
const ProfileRouter = StackRouter({
  Personal: {
    screen: Personal,
    path: 'personal',
  },
  Golf: {
    screen: Golf,
    path: 'golf',
  },
}, {
  initialRouteName: 'Personal',
});
```

when I call 
`this.props.router.getActionForRouteAndParams('Personal')` 
I get an Action object: 
```
{
    routeName: "Personal",
    type: "Navigation/NAVIGATE"
}
```

When I use that action to get my State using:
`this.props.router.getStateForAction(action)`
it returns an State object:
```
{
    index: 0
    routes: [
        {
            key: "Init"
            routeName:"Personal"
        }
    ]
}
```

While the docs says the State object should include all the routes available (hence the index property?)
https://reactnavigation.org/docs/routers/api (see getStateForAction, which specifically says ...moreRoutes in the State object).

Can anyone clarify this for me?

**Comment by satya164** [comment]
> When I use that action to get my State using: this.props.router.getStateForAction(action) it returns an State object:

You passed an action object to the function, it doesn't know anything about your state, so it cannot return a new state based on your current state. It just returns the initial state with the action.

You need to pass the current state for `getStateForAction(action, state)`

**Comment by godlevel** [comment]
@satya164 and how do I get that initial state? Do I build it myself? That should be weird. I should be able to ask the router for the initial state because I provided my routeConfig + initialRouteName. It should provide me the state, right?

**Comment by satya164** [comment]
You already know the state when you are using Redux.

**Comment by godlevel** [comment]
What If I dont use redux?

**Comment by satya164** [comment]
Why would you use `getStateForAction` then?

**Comment by godlevel** [comment]
To save the state in a (local) parent component. I should save the state somewhere to navigate right?

**Comment by satya164** [comment]
I don't understand what you're trying to do, but if you are saving the state somewhere, you already have the previous state from the previous `getStateForAction` action call. Usually you'd save the state in Redux, but you can use any other library.

**Comment by godlevel** [comment]
What I'm trying to do: 

I have my global navigation using redux. That's working. But I'm trying to create a custom navigator which saves the state in it's parent component. So I want to get the state and pass it through.

**Comment by satya164** [comment]
If you are saving the state in parent component, then you already have the state in the parent component after you call `getStateForAction` the first time to get initial state.

**Comment by godlevel** [comment]
That exactly what I did, but then I'd get the state which I posted in my initial post:
```
{
    index: 0
    routes: [
        {
            key: "Init"
            routeName:"Personal"
        }
    ]
}
```

**Comment by satya164** [comment]
I don't see what's the issue, this is the initial state which you get the first time you call `getStateForAction`. In subsequent dispatch actions you will call `getStateForAction` with the previous state and the action to get a new state.

**Comment by godlevel** [comment]
The issue is: why is there only 1 route provided in that initial state which I get from my router while I defined two routes.

**Comment by satya164** [comment]
Because it's the initial state where there is only first screen visible/present in the stack. When a new screen is pushed, it'll add the new route to the stack.

The `routes` array represents the routes present in the navigation stack, not the `routes` you defined.
