### ISSUE TITLE
Flicker during navigation reset

### ISSUE THREAD

**Issue by ishsingh** [react-community/react-navigation#639]
I have screens on a stack router when I call the reset method. It works as expected and I am able to get to the screen I intended, however all the other screens leaving the stack cause flickering. Is there a way to do smooth ui transition during navigation reset?

**Comment by jcsmesquita** [comment]
I'm seeing this as well. Any solutions proposed?

**Comment by arunshejul** [comment]
I'm facing same issue, Any solution?

**Comment by kelset** [comment]
Maybe related to https://github.com/react-community/react-navigation/pull/2520?

**Comment by vonovak** [comment]
I believe this was fixed by https://github.com/react-community/react-navigation/commit/e6505054bd765f0771aec8c328238b0b4d8ddab9 but feel free to reopen with a repro, in case the issue persists.
