### ISSUE TITLE
How do I add content above a top tab bar?

### ISSUE THREAD

**Issue by thorsonmscott** [react-community/react-navigation#64]
Hey, thanks for the release!  I have a screen in my app that has some content that takes up about a third of the top of the screen, and below that I want to have a nested tab view with the tab bar just below the other content at the top.  With ex-navigation it was simple to render the `<SlidingTabNavigation>` component below the rest of my component contents, but I can't figure it out with this library.  It seems as I define my nested navigators as screens in a parent navigator, I don't know where I would even define that other content?  Do I need to write a custom navigator?

Thanks for the help!

**Comment by satya164** [comment]
Take a look here, where I've done a similar thing - https://github.com/satya164/PocketGear/blob/master/src/components/PokemonInfo.js

PR is welcome to add this too the docs,

**Comment by thorsonmscott** [comment]
Thanks a ton!

**Comment by soroushm** [comment]
> Take a look here, where I've done a similar thing - https://github.com/satya164/PocketGear/blob/master/src/components/PokemonInfo.js
> 
> PR is welcome to add this too the docs,

link not found

**Comment by sniib** [comment]
> > Take a look here, where I've done a similar thing - https://github.com/satya164/PocketGear/blob/master/src/components/PokemonInfo.js
> > PR is welcome to add this too the docs,
> 
> link not found

https://github.com/satya164/PocketGear/blob/master/src/components/PokemonInfo.tsx
