### ISSUE TITLE
Setting styles on DrawerNavigator

### ISSUE THREAD

**Issue by cainaleaouk** [react-community/react-navigation#640]
Hi, really enjoying using the library but running into some issues; I can't seem to set any styling on the `<DrawerView />`, I've tried passing `screenProps` and all sorts. I can't seem to find any documentation or relevant issues, could someone more knowledgeable please advise?

Any help whatsoever would be appreciated 👍

**Comment by jurassix** [comment]
@cainaleaouk one option for you is to just recreate the DrawerNavigator so you have total control.

This is the exact code from [DrawerNavigator.js](https://github.com/react-community/react-navigation/blob/master/src/navigators/DrawerNavigator.js) but updated to be standalone (also removed flow.) Update at will. 

@satya164 @grabbou would need to validate this approach, before you depend on it. But it does represent the build-able nature of _react-navigation_ without relying on any core changes for customization.

```js
import React from 'react';
import {
  Dimensions,
  Platform,
} from 'react-native';

// Modified the imports to rely on public api from react-navigation
import { createNavigationContainer, createNavigator, TabRouter } from 'react-navigation';

// Modified the imports to rely on private api from react-navigation
import DrawerScreen from 'react-navigation/src/views/Drawer/DrawerScreen';
import DrawerView from 'react-navigation/src/views/Drawer/DrawerView';

const DefaultDrawerConfig = {
  /*
   * Default drawer width is screen width - header width
   * https://material.io/guidelines/patterns/navigation-drawer.html
   */
  drawerWidth: Dimensions.get('window').width - (Platform.OS === 'android' ? 56 : 64),
  contentComponent: DrawerView.Items,
  drawerPosition: 'left',
};

const CustomDrawerNavigator = (
  routeConfigs,
  config,
) => {
  const mergedConfig = { ...DefaultDrawerConfig, ...config };
  const {
    containerConfig,
    drawerWidth,
    contentComponent,
    contentOptions,
    drawerPosition,
    ...tabsConfig
  } = mergedConfig;
  const contentRouter = TabRouter(routeConfigs, tabsConfig);
  const drawerRouter = TabRouter({
    DrawerClose: {
      screen: createNavigator(contentRouter)((props) =>
        <DrawerScreen {...props} />
      ),
    },
    DrawerOpen: {
      screen: () => null,
    },
  }, {
    initialRouteName: 'DrawerClose',
  });
  return createNavigationContainer(createNavigator(drawerRouter)((props) =>
    <DrawerView
      {...props}
      style={{
        /* custom styles here */
      }}
      drawerWidth={drawerWidth}
      contentComponent={contentComponent}
      contentOptions={contentOptions}
      drawerPosition={drawerPosition}
    />
  ), containerConfig);
};

export default CustomDrawerNavigator;

```

**Comment by xilonxiao** [comment]
@jurassix Is this a possible way to implement any view i want inside the drawer view? I ve been looking for a drawer solution, but the ones i found didn`t meet my requirements. I ve tried using drawer navigation, but i couldn t figure out a way to implement the custom view i want inside the drawer.

**Comment by jurassix** [comment]
It's pretty straightforward to render any view inside a drawer. 

[From the docs](https://reactnavigation.org/docs/navigators/drawer#Providing-a-custom-contentComponent)

```js
const CustomDrawerContentComponent = (props) => (
  <View style={style.container}>
    <DrawerView.Items {...props} />
  </View>
);

const AppNavigator = DrawerNavigator(appRoutes, {
  initialRouteName: 'Dashboard',
  drawerPosition: 'right',
  contentComponent: CustomDrawerContentComponent,
});
```

In my current project I've take this a step farther and rewrote the `DrawerView.items` class to have full control of the styling. 

Hope this helps.

**Comment by spencercarli** [comment]
Hi! Since this issue has been quiet for a while I'm going to go ahead and close it. If the issue persists in the latest version of React Navigation please re-open!
