### ISSUE TITLE
[Proposal] support for `TabBarIOS`

### ISSUE THREAD

**Issue by alvaromb** [react-community/react-navigation#644]
This was tweeted by @mkonicek a few days ago: https://twitter.com/martinkonicek/status/839136633270206464

Excerpt: 

> Please don't build JS reimplementations of standard platform components like drawer or view pager.

`TabBarBottom` is a JS reimplementation of the iOS `UITabBar`. I think it is really nice, works very well and looks a lot like the native tab bar. However, if future iOS versions decide to change the style or behavior of the `UITabBar`, this JS component will need further work in order to match the native implementation. Maybe the new interaction or behavior will not be easy to reimplement, maybe the result output will not match their native counterpart. Many issues can arise.

My proposal, if the owners of this library agree, is to bring support for the `TabBarIOS` component, which wraps the `UITabBar` implementation. If there is no interest in bringing this to the library, I would like to develop a separate tab bar implementation that works with `react-navigation`. In this case, I think it is interesting to develop or document an interface to easily integrate third-party components like [react-native-material-bottom-navigation](https://github.com/timomeh/react-native-material-bottom-navigation#usage-for-react-navigation) or this proposed `TabBarIOS` component.

In any case, I'm available to help in any of the proposed solutions.

**Comment by satya164** [comment]
We had talked about this earlier and this is why we prefer a JS implementation,

1. It's difficult to customize native components, building a JS implementation allows a higher level of customization
2. The reason @mkonicek dislikes JS reimplementations is because it's extremely difficult to match native animation curves and gestures, it's not an issue for the tab bar
3. In practice, usually when you design the app, you want it to look it like you designed it everywhere, automatically changing the styles to match the new style in the OS can break the app's design

> Maybe the new interaction or behavior will not be easy to reimplement, maybe the result output will not match their native counterpart. Many issues can arise.

We'll see when/if it happens. We shouldn't overthink about it. TabBar is usually pretty simple.

> In this case, I think it is interesting to develop or document an interface

You can log the props passed to a custom `tabBarComponent` and look at the current tab bar implementations to see how they are built.

**Comment by alvaromb** [comment]
Thanks for your reply @satya164!

I agree that the tab bar is quite simple. What we are lacking right now is the gaussian blur applied to the background of the tab bar, which in some of our present and future projects will be required, thus the issue. Also, I agree with you that customising a native iOS `UITabBar` is a bit harder than doing that in the JS counterpart that comes inside this library, so I think that what I'll be doing is to develop a separate tab bar component that uses `TabBarIOS` that can work with `react-navigation`.

Once I have an initial release, I would like to add it to the docs, how do you feel about that?

**Comment by satya164** [comment]
> What we are lacking right now is the gaussian blur applied to the background of the tab bar, which in some of our present and future projects will be required, thus the issue.

You can achieve that right now by using a custom `tabBarComponent` which wraps `TabBarBottom` with `BlurView`. Don't need a native component for that. Eventually we'd like to add `BlurView` to `react-native` core and support it out of the box.

Maybe add docs on how to use the provided tab bar with `BlurView`. `TabBarIOS` doesn't provide any extra value.

**Comment by alvaromb** [comment]
That's interesting @satya164. I think using `react-native-blur ` brings more flexibility than `TabBarIOS` due to the ability to use vibrancy, not only blurring. I'll do some tests and I'll come back with the results later.

Thanks.

**Comment by SvetlinStaev** [comment]
@satya164 I know this has been closed but I am trying to achieve the desired blurred effect on a bottom tab navigator using the technique you proposed with the following code:

```
		tabBarComponent: props => (
			<BlurView tint="light" intensity={50}>
				<TabBarBottom {...props} />
			</BlurView>
		),
```

It does not seem to work. I do not find anything in the docs for that, any idea what might be going wrong here?

**Comment by canon4ever** [comment]
## TabBar.js

```js
import React from 'react';
import {StyleSheet} from 'react-native';
import {BlurView} from 'react-native-blur';
import {BottomTabBar} from 'react-navigation-tabs';

const styles = StyleSheet.create({
    blurView: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
    },
    bottomTabBar: {
        backgroundColor: 'transparent',
    },
});

export default function TabBar(props) {
    return (
        <BlurView blurType="xlight" style={styles.blurView} blurAmount={30}>
            <BottomTabBar {...props} style={styles.bottomTabBar}/>
        </BlurView>
    );
}
```

```js
tabBarComponent: TabBar,
```

It's works good for me.

**Comment by SvetlinStaev** [comment]
Yeah, I posted this on stackoverflow and got that same answer last week. This is the solution to the problem indeed.

**Comment by yangm97** [comment]
What if I want to give up customization for a more native look? Has anyone mapped  `UITabBar` into react-native?
