### ISSUE TITLE
Ability to access all Navigator instances

### ISSUE THREAD

**Issue by juhaelee** [react-community/react-navigation#647]
Is it possible to access every all the instances? I'm trying to open a modal from a StackNavigator that is above my TabNavigator, and I'm currently doing so right now by passing in the StackNavigator's this.props.navigator through the TabNavigator's screenProps prop

ex:
```
// assuming this is in a screen within a StackNavigator
<TabBar screenProps={{
      parentNavigation: this.props.navigation
}} /> 
```

**Comment by satya164** [comment]
See https://github.com/satya164/react-navigation-addons#navigationgetparent

**Comment by juhaelee** [comment]
Sweet. 

Also, in this example: https://reactnavigation.org/docs/intro/nesting
is
```
<Button
  onPress={() => this.props.navigation.navigate('Chat', { user: 'Lucy' })}
  title="Chat with Lucy"
/>
```
inside the `RecentChatsScreen`? Does this.props.navigation have access to navigate to any screens in all of its parents?

**Comment by ericvicenti** [comment]
> Does this.props.navigation have access to navigate to any screens in all of its parents?

Yes, you can `.navigate(` to a route that is defined in any of your navigators. Because of this you shouldn't need to directly access a parent instance
