### ISSUE TITLE
Android Device back button doesn't have consistent behaviour between stack navigator and tab navigator

### ISSUE THREAD

**Issue by zhaoyi0113** [react-community/react-navigation#648]
In tab navigator, when I click back button on android device, the navigator call `goBack` function to go to the previous screen which is good behaviour. But when I am using stack navigator and click device back button, it will exist the application. How can I keep stack navigator to be same as tab navigator?

**Comment by monkeymon** [comment]
I hit this issue too. Will be interested if you have found the solution.

**Comment by rjkmurray** [comment]
My up and down volume buttons are non responsive , could this behavior be related to the same problems you are having with the back button

**Comment by vokhuyet** [comment]
same issue

**Comment by spencercarli** [comment]
Hi! Since this issue has been quiet for a while I'm going to go ahead and close it. If the issue persists in the latest version of React Navigation please re-open!
