### ISSUE TITLE
how the get the current route key

### ISSUE THREAD

**Issue by musicode** [react-community/react-navigation#652]
route key' format is like `id-1489246424348-0`, it is useful with `goBack(key)`

but how can i get the key?

**Comment by junshengpierre** [comment]
You access it with `this.props.navigation.state.key` in your screen component.

**Comment by musicode** [comment]
@junshengpierre `this.props.navigation.state.key` is not the runtime key

**Comment by junshengpierre** [comment]
@musicode Are you sure you are passing the right key? Passing a key into `this.props.navigation.goBack()` brings you back _from_ the route of the key.
`this.props.navigation.goBack(screen1Key)` brings you to screen0
`this.props.navigation.goBack(screen5Key)` brings you to screen4
Could it be that you are passing screen4Key thinking that it will navigate to screen4?

**Comment by ericvicenti** [comment]
@junshengpierre has the right answers here

**Comment by musicode** [comment]
@junshengpierre 

the stack is like  `A -> form screen -> form result screen`, if the current screen is `form result`, when i press back, i want to skip `form screen`, back to the A directly.

how can i do that?

**Comment by oliverbenns** [comment]
Cannot access with `navigation.state.key` (maybe since update). Ended up doing this kinda knarly solution. I needed this to set active state on tab bar:
```
const { state } = navigation;
const currentRouteKey = state.routes[state.index].key;
```

**Comment by voidstarfire** [comment]
navigation.state.routes[state.index].key;

Navigator has no property 'routes'

**Comment by carlos-peru** [comment]
I'm experiencing the same as @voidstarfire. No routes in the navigation state.

**Comment by WhatAKitty** [comment]
+1 no routes in the navigation state, how can I get the routes?
by `onNavigationStateChange`?

**Comment by rashtay** [comment]
The state doesn't have routes or index.

**Comment by hoscarcito** [comment]
+1

**Comment by Versus2017** [comment]
Is there any solutions for this problem ? I think it confuses a lot of people, cause the function of getting current routes or index is important for us.

**Comment by rolldone** [comment]
+1

**Comment by brentvatne** [comment]
can someone who can explain this issue clearly and provide a reproducible example to demonstrate it on https://snack.expo.io or in a github repository, please create a new issue following the template? (please don't post your entire app, just a small one to reproduce the problem). thanks!
