### ISSUE TITLE
how to update header when tab navigator change?

### ISSUE THREAD

**Issue by musicode** [react-community/react-navigation#654]
my home page is based on tab view, every tab has its own component.

if the `lazy` config is `false`, every tab component will mount at the begining, and so that `componentDidMount` will call at the same time.

then tab changed, but how to update component header?

**Comment by musicode** [comment]
anyone can help me?

**Comment by Richard-Cao** [comment]
same problem

**Comment by spencercarli** [comment]
Hi! Since this issue has been quiet for a while I'm going to go ahead and close it. If the issue persists in the latest version of React Navigation please re-open!
