### ISSUE TITLE
Getting Started with React Navigation on a Web Project

### ISSUE THREAD

**Issue by bsbechtel** [react-community/react-navigation#656]
I'm working on a project where I want to implement react navigation on the web to help share code across platforms. I'm trying to read the source code of the docs website to get an understanding of what is necessary to wrap the react navigation router in a browser compatible component. Is this source code what you would want to include in your own project to implement React Navigation on a website? Thanks!

https://github.com/react-community/react-navigation/blob/master/website/src/BrowserAppContainer.js

**Comment by MovingGifts** [comment]
@bsbechtel Hi! did you figure out how to get it to run on web?

**Comment by bsbechtel** [comment]
I wasn't able to. I'm using meteor to deliver my bundle to the client, and something in React Navigation seems to break the bundle when it arrives on the client. I'm not sure if there is a global namespace conflict, or what exactly is going on. I only spent a few hours on it, however, as I was mainly just testing things out.

**Comment by MovingGifts** [comment]
I see no worries then, thanks for getting back 👍

I'll just go with React Router 4 for web, too bad react navigation web docs aren't enough guidance to reuse navigation on web 👎

**Comment by hiddentao** [comment]
I'm going to try using react-navigation for a web project.

**Comment by udfalkso** [comment]
I've gotten this to work.  I basically used this boilerplate as a starting point and got my app up and running with webpack:
https://github.com/ndbroadbent/react-native-web-webpack

Then I used normal redux-based react-nativigation (tab navigator and stack navigator) and everything just worked out of the box.  

Nothing custom, and no BrowserAppContainer.js was needed.  That threw me off for a while, but it isn't required.  I think if you want to to url based routing you might have to start to head in that direction but without that you shouldn't need it.

**Comment by MovingGifts** [comment]
@hiddentao Good luck :)

@udfalkso Thank you for your comment :) Yup, I definitely need url routing to work as well, but since the docs are still very lacking, I started integrating React Router 4 for web. It's a pain to have 2 different routing libraries (one native, one web), but their docs are pretty solid and community very active 👍

**Comment by kelset** [comment]
Pinging OP @bsbechtel  since this issue is quite old and related to an old version of the lib. If no answer I'll close in 7 days.

Moreover, sadly with the new roadmap to v1.0 we are freezing the web support by the library since there is a lot of work that has an higher priority.

**Comment by bsbechtel** [comment]
@kelset No worries. In an ideal world, it would be nice to have support for this, but having a solid RN router is a higher priority. Looking forward to seeing how things pan out and the new v1.0! Good luck!

**Comment by rodrigofeijao** [comment]
As now there's [react-native-web](https://github.com/necolas/react-native-web) and it's getting quite popular, does anyone found a way to make it work on both worlds?

**Comment by JavaJamie** [comment]
Any update on this? I've noticed react-navigation-web but unsure as to its stability.

**Comment by JavaJamie** [comment]
Any update on this? I've veered towards react-native-web (thanks @rodrigobdz) and hopefully it will work. Has anybody tried [https://github.com/react-navigation/react-navigation-web]? I'm unsure as to its stability before taking a leap of faith.

**Comment by JavaJamie** [comment]
Any update on this? I've veered towards react-native-web (thanks @rodrigobdz) and hopefully it will work. Has anybody tried [](https://github.com/react-navigation/react-navigation-web)? I'm unsure as to its stability before taking a leap of faith.

**Comment by hiddentao** [comment]
@rodrigofeijao I have gotten react-navigation working for react-native-web (both web and mobile). See https://github.com/meth/app/tree/dev/src/ui/nav

**Comment by kopax** [comment]
Is this still not solved? I am trying to get hash or browser history, and it seems I still need to use `react-router`. 

I'm thinking of creating an adapter, that is equal to react-navigation for most of userland code, and plug react-router behind, until this get solved within react-navigation. Or maybe one have already done that? 

Thanks and best!

**Comment by avitorio** [comment]
@kopax Any luck here? I'm trying to add the same features to my app...

**Comment by NilsBaumgartner1994** [comment]
> Is this still not solved? I am trying to get hash or browser history, and it seems I still need to use `react-router`.
> 
> I'm thinking of creating an adapter, that is equal to react-navigation for most of userland code, and plug react-router behind, until this get solved within react-navigation. Or maybe one have already done that?
> 
> Thanks and best!

Did it work with a hash router?
