### ISSUE TITLE
Unexpected token import

### ISSUE THREAD

**Issue by GalFriD** [react-community/react-navigation#657]
when trying to make test i getting this error:

![image](https://cloud.githubusercontent.com/assets/20794214/23831474/dcf60698-072a-11e7-9d79-8714b9313b58.png)

it happens only after i use this package.
any ideas? thanks

**Comment by bhaskarmurthy** [comment]
Same here. Happens when running Jest.
Seems Jest should ignore `node_modules` by default, so not sure what's going on here.

**Comment by matthamil** [comment]
This is a repeat of https://github.com/react-community/react-navigation/issues/256
