### ISSUE TITLE
How to prevent triggering navigate multiple times

### ISSUE THREAD

**Issue by zhaoyi0113** [react-community/react-navigation#658]
I am using `react-navigation` to create an Android application. There is a performance issue on navigating stack screen on Android. When user click on  a button, it usually takes one to two seconds to switch the screen. If users click the button multiple times, there will be multiple screens added on the stack. How to prevent users click multiple

**Comment by PavSidhu** [comment]
This has already been answered here #271, I wish that debouncing would be implemented into the library but you have to implement it yourself for now.

**Comment by zhaoyi0113** [comment]
Close it since it is a duplicate issue.
