### ISSUE TITLE
can't set tab bar icon height properly

### ISSUE THREAD

**Issue by zhaoyi0113** [react-community/react-navigation#659]
I am using `react-nativation` on an Android app. Below is my tab navigation configuration:

```
const Tabs = TabNavigator({
  Home: {
    screen: HomeContainer,
  },
  Patient: {
    screen: PatientContainer,
  },
  User: {
    screen: UserContainer,
  }
}, {
  tabBarOptions: {
    showIcon: true,
    style: {backgroundColor: 'lightgray', height: 60, padding:0, margin:0},
    showLabel: false,
    tabStyle: {margin: 0, padding: 0, height: 60},
    indicatorStyle: {backgroundColor: 'lightgray'}
  },
  tabBarPosition: 'bottom',
});
```

I set the height to be `60` on the tab bar options. It works fine. But when I place an image icon on the tab bar. The height of the icon can't be set to 60. Below is navigationOptions set on my component:

```
static navigationOptions = {
    tabBar: {
      label: '',
      // Note: By default the icon is only shown on iOS. Search the showIcon option below.
      icon: (obj) => {
        const image = obj.focused ? require('../../../images/home_pre.png') : require('../../../images/home_nor.png');
        return <Image style={{resizeMode:'contain', height:50, width:40}}
                      source={image}
        />
      },
    },
  }
```

From below screenshot you can see that the icon image is clipped and there are spaces on the top and bottom of the image. How to set the icon image to take full height of the tab bar?

![screen shot 2017-03-12 at 11 55 05 pm](https://cloud.githubusercontent.com/assets/3355579/23831955/6a7affe2-077f-11e7-9fc1-aacc00c793fb.png)

**Comment by ldipasquale** [comment]
The tab icon is wrapped by the [TabBarIcon component](https://github.com/react-community/react-navigation/blob/0c8f9f7424e4af92f7ed9b9e564d930d43157bba/src/views/TabView/TabBarTop.js), whose style has 24x24.

`tabBarOptions` object should have a `iconStyle` extending this properties (width, height, etc)

**Comment by cooltoo** [comment]
Has `iconStyle` been implemented? I didn't find it on the source code

**Comment by ldipasquale** [comment]
No, it hasn't. But the PR should be _easy_.

**Comment by zhaoyi0113** [comment]
I have made the changes and it works fine. Can I get the permission to submit a pull request?

**Comment by rgabs** [comment]
It is implemented now in the latest version of react-navigation

**Comment by kelset** [comment]
Pinging OP @zhaoyi0113 since this issue is quite old and related to an old version of the lib. If no answer I'll close in 7 days.

**Comment by kelset** [comment]
Hi there @zhaoyi0113,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue (especially if it's a bug report) please open a new issue that uses the new Issue Template to provide some more details to help us solve it.

**Comment by theOnkar** [comment]
Can somebody help me with removing the default `padding:8` for `View`?

![image](https://user-images.githubusercontent.com/20907403/31732444-25a2e9fa-b456-11e7-99ed-f6c4b5351034.png)

**Comment by elmawardy** [comment]
@theOnkar  you can also add 

`   	labelStyle:{
   		margin:0,
   		padding:0,
        },`

to change the tabbar's label margin & padding

**Comment by theOnkar** [comment]
@elmawardy .. Worked like a charm. Thanks heaps!!

**Comment by andersondecarvalho** [comment]
tabBarOptions: {
      ...
      iconStyle: { height: 30, width: 30 }, 
}
