### ISSUE TITLE
DrawerNavigator Background Dim

### ISSUE THREAD

**Issue by pex** [react-community/react-navigation#660]
Tested in iOS simulator and on actual iOS device:
After updating to beta7 `DrawerNavigator` does not dim the background no more when opened.
The visible content behind the drawer is not clickable neither (which was closing the drawer in earlier versions).
Is this desired behaviour? If yes: are there options to recover the legacy background-dimming?

**Comment by DanielMSchmidt** [comment]
Hi @pex,

This is a bug in the drawer library we are using, see https://github.com/react-native-community/react-native-drawer-layout/issues/12. I am currently working on this issue, can you expand a bit on how you found it? It is every content of the drawer or only specific ones?

**Comment by DanielMSchmidt** [comment]
I just tested it on the drawer example in this project, but it worked there on the iOS Simulator and on a real android device. It would be so great if you could provide further detail or an example so I can debug this issue a little further. Thank you for your help!

**Comment by pex** [comment]
Hej @DanielMSchmidt thank you for your quick support. I am also following react-native-community/react-native-drawer-layout/issues/12 which sounds like fixing that resolves this issue as well.
I'm curious about your solution. Good luck!

**Comment by spencercarli** [comment]
Seems this was fixed - closing!
