### ISSUE TITLE
backBehavior for TabNavigator

### ISSUE THREAD

**Issue by ddeanto** [react-community/react-navigation#663]
By default, the back button takes you back to the initial tab if you are on the >= 2nd tab. I would like for the back button to pop back out of the TabNavigator completely (just like what happens when pushing back button from the 1st tab) regardless of which tab I am currently on. According to the docs, I need to set `backBehavior` to `none`, but this appears to make no difference in behavior. 

Am I doing this correctly?:

```
const Team = TabNavigator({
  tab_1: {
    screen: StackNavigator({
      teamEvents: { screen: MyTeam }
    })
  },
  tab_2: {
    screen: StackNavigator({
      teamSettings: { screen: TeamSettings }
    })
  } },
  {
    tabBarOptions: {
      activeTintColor: 'yellow',
      showIcon: true,
      showLabel: false,
      style: {
        backgroundColor: 'rgb(40,40,40)'
      }
    },
    tabBarPosition: 'bottom',
    backBehavior: 'none' // IS THIS RIGHT?
  }
);
```

**Comment by XboxYan** [comment]
@ddeanto yes,it is right

**Comment by ddeanto** [comment]
@XboxYan, but if it is right then why isn't the behavior as expected? Thanks again!

**Comment by ddeanto** [comment]
I am using "react-navigation": "^1.0.0-beta.7"

**Comment by ddeanto** [comment]
Nevermind, it is working with "react-navigation": "^1.0.0-beta.7", I must have been using an older version before?
