### ISSUE TITLE
Custom tabBar , lag when I switch scenes.

### ISSUE THREAD

**Issue by guoliang1206** [react-community/react-navigation#664]
question:   
 when I tap the tab and then switch the scene, all components of the destination scene will be render every time,so it's cause little lag . Last week a friendly man told me that he used Redux.But now I haven't use the network data,I don't think that I need Redux to manage my app's state at present.Becasue my app just is a demo, it has no state changed. Just switch the page,and it will render its child components again. Is there should be some cache mesures? 
This is my custom TabBar:

```
//cusotm router
const CustomTabRouter = TabRouter({

        Home:{
            screen:Home,
        },
        Me:{
            screen:Me,
        },
        Contacts:{
            screen:Contacts,
        },
        Find:{
            screen:Find,
        },
    },                   {
        initialRouteName:'Home'
    }
);


//create custom TabBar
const CustomTabs = createNavigationContainer(createNavigator(CustomTabRouter)(CustomTabView));

```

the Home screen just is a swiper view on the header of a LisView,all data of the ListView is local data and fake. every time when I select this screen ,lag about 0.5s will happen.

**Comment by guoliang1206** [comment]
Whether there is such a possibility，some code trigger the function - componentsDidMount()？ It cause the scene re- reload?

**Comment by guoliang1206** [comment]
official TabNavigator is natural, it doesn't re-render the components if there no state change.

**Comment by holyxiaoxin** [comment]
You can try using 'react-native-tab-view', which has caching of views. It's actually the underlying TabView that TabNavigation is implementing. `react-navigation` should only handle routing/navigation, and shouldn't handle view.
