### ISSUE TITLE
Question on Android --- TabNavigator How to get the scrollView? (3rd parts conflict)

### ISSUE THREAD

**Issue by guoliang1206** [react-community/react-navigation#665]
On the android platform,the TabNavigator style is  scrollView . But when I use the 3rd parts Swiper on the header of the ListView , the looper image can not be load correctly,just blank pages. So i need get the scrollView of the TabNavigator ,and set `removeClippedSubviews={false}`.How can I handle this?

**Comment by brenoxp** [comment]
I'm having exactly the same issue here :(

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
