### ISSUE TITLE
(is not a function. (In '(0, _reactNavigation2.default)','(' is an instance of object)

### ISSUE THREAD

**Issue by zakster12** [react-community/react-navigation#666]
I have this error when trying to install react navigation. I tried with:
```
yarn add react-navigation
```
and with

```
npm install --save react-navigation
```

and in both ways I have the above error. 

I am using 
React Native - 0.42.0
macOS Sierra

![screen shot 2017-03-13 at 3 42 58 pm](https://cloud.githubusercontent.com/assets/25477229/23857624/90b7b3da-0806-11e7-938a-b1beb0e14f93.png)

**Comment by zakster12** [comment]
Same as: https://github.com/react-community/react-navigation/issues/550. I am closing this one.

**Comment by codemonkey1337** [comment]
I hade the same issue, nad this solved it:

failes:
import StackNavigator from 'react-navigation';

works:
import { StackNavigator } from 'react-navigation';

**Comment by lucaszanella** [comment]
For me, I had to change from 

`import { StackNavigator } from 'react-navigation';`

to

`import StackNavigator from 'react-navigation';`

**Comment by YouCii** [comment]
666
