### ISSUE TITLE
Tab Bar appears before transition

### ISSUE THREAD

**Issue by MyGuySi** [react-community/react-navigation#668]
When navigating from a screen with `tabBar: { visible: false }` the tab bar appears on the screen before the transition. It would be great if it appeared once the transition has completed if the initial screen has it hidden.

![](https://media.giphy.com/media/yLoUDKFbziLEk/giphy.gif)

I'm using 1.0.0-beta.6

**Comment by kanzitelli** [comment]
@MyGuySi hey, can I please know what the structure of your navigation part is? Because I am trying to get the same result in my app but I can't. Thank you in advance. 
And this behavior may appear because it starts showing tabBar when 'Back' action is caught.

**Comment by Thorbenandresen** [comment]
@MyGuySi did you find a way to solve this? Currently I work around it by rendering my own TabBar on the first screens of the two StackNavigators inside my two tabs.

**Comment by MyGuySi** [comment]
@Thorbenandresen I haven't dedicated any time to trying to solve it to be honest, I changed the UI so the tab bar persists across all screens now

**Comment by kelset** [comment]
Pinging OP @MyGuySi  since this issue is quite old and related to an old version of the lib. If no answer I'll close in 7 days.

**Comment by MyGuySi** [comment]
We switched to react-native-navigation so feel free to close it 👍
