### ISSUE TITLE
Hiding headers when sliding

### ISSUE THREAD

**Issue by cgestes** [react-community/react-navigation#670]
Hi,

thank you for this awesome project.

I am creating this issue to gather informations on hiding the titlebar and/or the tabbar when sliding the current screen.

This idea is to be able to achieve what we can do with a coordinatorlayout on Android.

Picture bellow for an idea of what I mean:
![Image](https://github.com/maolion/mao-rn-android-kit/raw/master/demo.gif)
 
Some react-native projects implementing the coordinatorlayout:
- https://github.com/maolion/mao-rn-android-kit 
- https://github.com/zetavg/react-native-android-design-support

Anyone did it? If not where should I start?

**Comment by satya164** [comment]
Here is a simple example of auto-hiding header https://sketch.expo.io/B1v5RS7ix

To adapt it to React Navigation, you need to set the header styles based on scroll value. You can use this to achieve it https://github.com/satya164/react-navigation-addons

**Comment by fdnhkj** [comment]
Hi @satya164,
I wondering why you are suggesting to use `react-navigation-addons`. Wouldn't passing the info via [navigation.setParams](https://reactnavigation.org/docs/navigators/navigation-prop#setParams-Make-changes-to-route-params) do the job?

**Comment by kelset** [comment]
Pinging OP @cgestes since this issue is quite old and related to an old version of the lib. If no answer I'll close in 7 days.

**Comment by cgestes** [comment]
Didn't try lately. Didn't find a solution either.

But I'am fine closing.

Back then I also didnt understand when react-navigation-addons could help.
