### ISSUE TITLE
Performance issue on StackNavigator

### ISSUE THREAD

**Issue by xilonxiao** [react-community/react-navigation#672]
My current project is structured like this:

A main TabNavigator which holds two tabs, and both are composed by a stack navigator. These stacks can hold two or more screens, something like this:

 - Main (TabNavigator)
    - HomeTab (StackNavigator)
         - Feed level 1
         - PublicationDetails (Some publication) level 2
         - Profile level 3
         - PublicationDetails (Another publication) level 4
     - Exploretab (StackNavigator)
         - Explore level 1
         - PublicationDetails (Some publication) level 2
         - Profile level 3
         - PublicationDetails (Another publication) level 4

My problem is: When a PublicationDetails page is on level 2 of the stack, its scroll performance is a flawless 60 fps. But the same page, on the third level of the stack, suffers some noticeable jerkyness.
I' ve run the systrace.py to chek this issue, and it clarified a little my suspicious: When on level 4 of the stack, the PublicationDetails page suffers from "Scheduling delay" and "Expensive bitmaps uploads", which both take way more than ideal 16ms to process, causing the jerkyness. It happens also with Profile page, considering that both could be on levels, 2, 3 or 4, depending on how we navigate. The point is: When on top of a short stack (level 2), the pages performance are very good, but on a tall stack (level 4) it is very bad. Do you guys have any suggestions/ideas/tips to address this problem?

Thanks

**Comment by nico1510** [comment]
https://github.com/react-community/react-navigation/issues/706 may be related

**Comment by xilonxiao** [comment]
Thanks, I'll check it out.

**Comment by spencercarli** [comment]
Hi! Since this issue has been quiet for a while I'm going to go ahead and close it. If the issue persists in the latest version of React Navigation please re-open!
