### ISSUE TITLE
Scenes push super slow on iOS

### ISSUE THREAD

**Issue by jeffreymendez1993** [react-community/react-navigation#674]
It takes about a minute and a half to push a scene from a listView on iOS 7.

**Comment by brunolemos** [comment]
@jeffreymendez1993 You need to provide more details.

1. Is it on simulator?
2. Is debug mode enabled?
3. Have you tried iOS 8+?
4. Have you tried on a device?
5. Have you tried on the release mode?
6. Which RN version?
7. Which machine configuration? (ram, ...)

**Comment by jeffreymendez1993** [comment]
1. yes
2. yes
3. no
4. no
5 no
6. 0.42.0
7. ram

**Comment by thorsonmscott** [comment]
@jeffreymendez1993 I've been burned by `Slow Animations` setting of the iOS simulator so many times, cmnd+t is only a key away from cmnd+r for reload.  Triple check you haven't accidentally enabled that setting?  From iOS simulator: `Debug` -> `Slow Animations`

**Comment by jeffreymendez1993** [comment]
@thorsonmscott  Thanks that was the problem. Closing the issue now.
