### ISSUE TITLE
Error: Cannot find module 'react-native/packager/blacklist'

### ISSUE THREAD

**Issue by leonardgithub** [react-community/react-navigation#675]
I run the ReduxExample, show the below error:
Error: Cannot find module 'react-native/packager/blacklist'

**Comment by leonardgithub** [comment]
It is OK now, reference: https://reactnavigation.org/docs/guides/contributors

**Comment by rochapablo** [comment]
https://github.com/ds300/react-native-typescript-transformer/issues/20
