### ISSUE TITLE
TabNavigator  set  icon invalid  on android 

### ISSUE THREAD

**Issue by roselind** [react-community/react-navigation#679]
TabNavigator  set  icon invalid  on android 

![008b58d1-9022-4f78-ab86-af56567dd212](https://cloud.githubusercontent.com/assets/9067932/23892222/b2c72324-08d4-11e7-8a3a-e7c78211660b.png)

**Comment by satya164** [comment]
https://reactnavigation.org/docs/navigators/tab#tabBarOptions-for-TabBarTop-default-tab-bar-on-Android

**Comment by roselind** [comment]
tab:

const mainScreenNavigator = TabNavigator ({
  LoginPage: {
    screen: LoginPage,
  },
  PersonPage: {
    screen: PersonPage,
  },
  JobListPage: {
    screen: JobListPage,
  }, 
},{

  tabBarPosition:'bottom',
  swipeEnabled: false,
  animationEnabled: true,
  tabBarOptions : {
    activeTintColor: '#FFFFFF',
    inactiveTintColor: '#70FFFFFF',
    labelStyle: { fontSize: 10 },
    style: {
      backgroundColor: '#008956',
    },

    // for TabBarTop
    upperCaseLabel: true,
    indicatorStyle: {
      backgroundColor: 'blue',
    }
  },
});

mainScreenNavigator.navigationOptions = {
  title: 'My Chats',
  header: {
    tintColor: 'white',
    style: {
      backgroundColor: '#42a5f5',
   }
 },
};

//https://reactnavigation.org/docs/navigators/stack#StackNavigatorConfig
const config = {
  headerMode: 'screen',
  // mode: 'modal'
}
const App = StackNavigator({
  Home: {
    screen: mainScreenNavigator
  },
  // GeneralBoard: {
  //   screen: PersonPage
  // },
  // ImageBoard: {
  //   screen: JobListPage
  // },

}, config);


page:
export default class JobListPage extends Component {
  static navigationOptions = {
    title: 'JobList',
    tabBar:{
      icon: ({ tintColor }) => (
          <Image source={require('../../../img/arrow_right_gray.png')} style={[styles.tabIcon, {tintColor: tintColor}]}/>),

    }
  }
