### ISSUE TITLE
How to fetch new data every time when the tab is switched to active?

### ISSUE THREAD

**Issue by manoharank** [react-community/react-navigation#680]
I fetch data in `componentDidMount` hook of the tab screen. Since the TabNavigator screens are cached, `componentDidMount` hook is triggered only on the first switch, not on the subsequent switch.

**Comment by satya164** [comment]
We need this feature in core, but in the meantime, check https://github.com/satya164/react-navigation-addons

**Comment by manoharank** [comment]
@satya164 Thanks! This add-on solves two problems for me.

1. navigation.addListener: to fetch data every time
2. getParent: to navigate to parent navigator

Expecting to have these in core soon.

**Comment by maxyharr** [comment]
Any update on if there is a core solution to this yet? If there is, I can't seem to find it in documentation, but it's been a while so I thought it was worth asking. react-navigation-addons seems good, but worried about just copy/pasting into project

**Comment by arryanggaputra** [comment]
npm install --save satya164/react-navigation-addons 
this work for me

**Comment by pencilcheck** [comment]
Does this work with apollo? I want the tab to refetch apollo that are wrapped outside of the component every time the tab switches, is that possible?

**Comment by karlingen** [comment]
What about using this?
https://github.com/react-community/react-navigation/pull/1335

**Comment by Donhv** [comment]
how about to use componentwillreceiveprops
