### ISSUE TITLE
Redux store and custom state in screens of a navigator

### ISSUE THREAD

**Issue by csotiriou** [react-community/react-navigation#682]
I am trying to add a Redux store in all screens that are embedded inside a StackNavigator, in order to manage many things other than a navigation state. All screens inside the same navigator will use the same variables, and I want them to respond reactively when the state changes.

While I am able to call a custom dispatch action, I am unable to get the props from my redux store.

Here is a sample:

```
const AddOrderNavigatorPlain = StackNavigator({
  AddOrderCategory: {
    screen : AddOrderCategoryScreen
  },
  AddOrderSubCategory: {
    screen : AddOrderSubCategoryScreen
  },
  AddOrderSubCategoryScreen : {
    screen : AddOrderSubCategoryScreen
  },
  ItemListScreen: {
    screen : ItemListScreen
  },
  ItemModifiers : {
    screen : ItemModifiersScreen
  }
});

const MyStackReducer = (state, action) => {
  if (action.type === 'SAMPLE_ACTION') {
    console.log('SAMPLE_ACTION!!! with state: ', state);
    return {...state, screenProps : {newProp : 'new Prop!!!'}};
  }
  return AddOrderNavigatorPlain.router.getStateForAction(action, state)
};


const mapStateToProps = (state) => {
  let newNavigationState = state;

  if (!state.params) {
    newNavigationState.params = state.screenProps;
  } else {
    if (state.screenProps) {
      newNavigationState.params = {
        ...state.params,
        ...state.screenProps
      }
    }
  }

  return {
    navigationState : newNavigationState,
    screenProps : state.screenProps
  }
};

class AppWithNavigationHelpers extends Component {
  constructor(props){
    super(props);
    console.log('AppWithNavigationHelpers props:', props);
  }

  render() {
    return (
        <AddOrderNavigatorPlain navigation={addNavigationHelpers({
          dispatch : this.props.dispatch,
          state : this.props.navigationState,
          params : {...this.props.screenProps}
        })}
        />
    );
  }
}


const AddOrderNavigatorConnected = connect(mapStateToProps)(AppWithNavigationHelpers);

const store = createStore(MyStackReducer);

export class AddOrderNavigator extends React.Component {
  constructor(props){
    super(props);
    console.log('add order navigator props:', props);
  }
  render() {
    return (
      <Provider store={store}>
        <AddOrderNavigatorConnected {...this.props} />
      </Provider>
    )
  }
}
```

When I enter inside the screen, in `componentDidMount()`, I am calling the action like this:

```
this.props.navigation.dispatch({type : 'SAMPLE_ACTION'})
```

and I am trying to display my new test variable using:

```
<Text>{this.props.navigation.params? this.props.navigation.params.newProp : "!"}</Text>
```

And although it seems to have been called, I am unable to see the new props inside my screen. It's like it's not handled reactively, although the state has been changed.

In general, what is the recommended way of handling a custom redux store with custom properties when using react-navigation's navigators?

I am struggling with this for quite some time now, and I haven't found any good example with this. Maybe I am missing something, but can someone point me in the right direction?

**Comment by csotiriou** [comment]
Update:

I eventually did this:

```
 <AddOrderNavigatorPlain navigation={addNavigationHelpers({
          dispatch : this.props.dispatch,
          state : this.props.navigationState
        })}
        screenProps = {this.props.screenProps}
        />
```

Note the screenProps. They seem to have the effect I need, and I am able to call my custom variables with ```this.props.screenProps.newProp``` and have the expected result.

However, is this correct? Should we use screenProps for these things or is there another more "correct" way of doing it?

**Comment by spencercarli** [comment]
Hi! In an effort to reduce the number of open issues I'm closing question-type issues that would be a better for the [react-navigation tag on StackOverflow](https://stackoverflow.com/questions/tagged/react-navigation). This is nothing personal, merely trying to get the # of issues to a more manageable level. If you think this issue should be re-opened please let me know. Thanks!
