### ISSUE TITLE
goBack detect stackNavigator

### ISSUE THREAD

**Issue by quangas** [react-community/react-navigation#684]
Screen A -> Screen B

On Screen B after I fill in a form, I use goBack() to go back to Screen A. However upon going back to Screen A, I need to refresh its contents. From Screen A, how can I detect a 'goBack()' event?

Is there any other way to solve this? 

From Screen B i could do navigate('ScreenA') but then I have an extra Screen on the stack so it will look like Screen A -> Screen B -> Screen A. Is there maybe a way to pop Screen A when I go to Screen B? If so, how?

**Comment by tirsoh** [comment]
I also have a similar need. I want to be able to have the component re-render upon going back to the previous screen. How can this be accomplished using the StackNavigator?

**Comment by quangas** [comment]
I had to use a Modal in the end as I could still access the parent screen.

Screen A -> Screen B (Modal)

Screen B had a function as a prop so I was able to close the Screen B (Modal) and still have access to Screen A. So something like

```
ScreenA ...

handleScreenBAction(props) {
 dosomething();
 closeScreenB(); 
}
render() {
 return (
  <Modal visible={this.state.modal_visible}>
    <ScreenB onClick={this.handleScreenBAction.bind(this)} />
  </Modal>
 )
}
```

I just used another component called ScreenB but you could write all your field entries or whatever you want to replace ScreenB.

```
ScreenB ....
DoSomething()  {
 this.props.onClick(...); // this should propogate to ScreenA.handleScreenBAction
}
render() {
 <TextInput .... />
 <Button onClick={this.props.DoSomething} />
}

```

**Comment by temitope** [comment]
thanks @quangas for bringing up this issue and profering a solution . i ended up relying on firebase's on event to update ui, but it would be nice if there was a way to trigger some kind of event when back reloads. modal was not an option for me as navigation going on underneath it was not visible.

**Comment by yuana1** [comment]
@quangas   have you tried DeviceEventEmitter? i used it to solve my problem perfectly.
```
//screen A
import {DeviceEventEmitter} from 'react-native'
componentWillMount() {
    DeviceEventEmitter.addListener('your listener', (e)=>{})
}
//may be you need componentShouldUpdate

//screenB
DeviveEventEmitter.emit('your listener',  {})
```

**Comment by quangas** [comment]
@yuana1 thanks! I've never heard of a DeviceEventEmitter for RN and this might work really well. I've been thinking about 'nsnotification'-like or 'delegate'-like things for RN but didn't know where to look.

**Comment by JimmyDaddy** [comment]
@quangas you can pass a refresh function to B, and before close B action you can run the refresh function, then goBack A

```
//ScreenA...
goBAction = () => {
   const {navigation} = this.props;
   navigation.navigate('B', {refresh: refreshFunction});
}
refreshFunction = () => {
   //do refresh
}

//ScreenB...
goBackAAction = () => {
    const {navigation} = this.props;
    const {state} = navigation;
    let refreshFunc = state.refresh;
if(typeof refreshFunc === 'function'){
    refreshFunc();
}
   navigation.goBack();
}

```

**Comment by grabbou** [comment]
Closing in favour of #51

**Comment by ahmadalfy** [comment]
Question, what if that refresh function tries to set the state?

I currently get that error:

```
Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op.
```

How do I wait till the component is mounted then refresh?

**Comment by bhatti-waqas** [comment]
@JimmyDaddy: but refresh function doesn't reload/Update the UI. Throws warning 
"Can only update a mounted or mounting component. This usually means you called setState, replaceState, or forceUpdate on an unmounted component. This is a no-op.
"

**Comment by JimmyDaddy** [comment]
@bhatti-waqas : 
if you push form screen A to screen B, screen A will not be unmounted, so the warning you occurred will not throw. Though I don't know what you have done in your code caused this warning, there is a solution can avoid this problem.
```
import React from 'react'

export default class Component extends React.Component {
  constructor (props) {
    super(props)
    this.__EXIST_FLAG = true
  }

   changeState (...args) {
     if (this.__EXIST_FLAG) {
        this.setState(...args)
     }
   }
   
  componentWillUnmount () {
      this.__EXIST_FLAG = false
  }
}

```

Using the `Component` instead of `React.Component`, can avoid this warning

**Comment by LyhengTep** [comment]
@yuana1 great job thank guy

**Comment by arbabi2010** [comment]
@yuana1 Hi.
Could you show me with a complete example for hardwareBackPress.
i can't use your code correctly

**Comment by BayShubar** [comment]
The best solution was using addListener to navigation
[here](https://reactnavigation.org/docs/en/navigation-prop.html)
`const didBlurSubscription = this.props.navigation.addListener(
  'didBlur',
  payload => {
    console.debug('didBlur', payload);
  }
);

- willBlur - the screen will be unfocused
- willFocus - the screen will focus
- didFocus - the screen focused (if there was a transition, the transition completed)
- didBlur - the screen unfocused (if there was a transition, the transition 

- completed)`

**Comment by toddpi314** [comment]
@BayShubar's solution was pretty solid for our use-cases around this issue. Thanks man.

**Comment by ShrikantRao** [comment]
I think you should not close this. This is a very good use-case where I want 2 different events or 2 different animation to perform on screen focus (on screen-2). First on navigating from screen-1 to screen-2 and second on navigating from screen-3 to screen-2 (goBack). 

In V4 and V5 I don't find any **function** or **hook** which help me identify this (goBack) on screen-2. Please correct me if I'm wrong. 

Instead of just 'focus' can there be 3 version on 'focus'. 
1. focus - standard one
2. focusOnPush or focusForward 
3. focusOnPop or focusBackward

Same for Blur.

**Comment by abbasmoosavi** [comment]
> @quangas have you tried DeviceEventEmitter? i used it to solve my problem perfectly.
> 
> ```
> //screen A
> import {DeviceEventEmitter} from 'react-native'
> componentWillMount() {
>     DeviceEventEmitter.addListener('your listener', (e)=>{})
> }
> //may be you need componentShouldUpdate
> 
> //screenB
> DeviveEventEmitter.emit('your listener',  {})
> ```

Save my day, Thanks!

**Comment by rlecart** [comment]
I had the same issue and this is the best solution i found : the hook [useIsFocused()](https://reactnavigation.org/docs/use-is-focused/) 


```js
import { useIsFocused } from '@react-navigation/native';

const MyComponent = () => {

    useEffect(() => {
        // your refresh logic here
    }, [isFocused]);
    
// [...]
```

**Comment by VariabileAleatoria** [comment]
I think there is still not a real solution to this issue and thus it should not be closed.
All the checks to know if the screen is focused are not valid because they fails at distinguish the reason of the screen being focused.
On screen focus there should be a way to know that the last navigation action was a 'POP' or 'BACK'
