### ISSUE TITLE
Disable swipe from DrawerNavigator

### ISSUE THREAD

**Issue by rldona** [react-community/react-navigation#685]
I want to avoid the effect on the screen Login, Register, etc

Is this possible?

Thanks

**Comment by Andreyco** [comment]
I think you should not render drawer on login at all.

Render Login/Register "sub app" without navigators when needed.
Render main app after user logs in, with navigators in place.

That's it.

**Comment by xilonxiao** [comment]
Regardless if his issue could be solved by just not render the drawer on said screens, I guess being able to enable/disable the swipe a great feature to be implemented.

**Comment by emaLorenzo** [comment]
I did it today, this feature could be implemented using the code from this PR https://github.com/react-community/react-navigation/pull/793

inside the navigationOptions of your screen you just have to add:
lockMode: 'locked-closed'

**Comment by riftshock** [comment]
@emaLorenzo  hey man newbie here, tried it but did not work..was wondering how I got it wrong..so I added it on my static navigationOptions under my Login class component but still swiping drawerNavigator isnt' disabled..would really be glad if you could help me..thank you ;)

**Comment by mynameisbams** [comment]
@emaLorenzo lockMode not work

**Comment by kelset** [comment]
Pinging OP @rldona since this issue is quite old and related to an old version of the lib. If no answer I'll close in 7 days.

(moreover, a PR got merged to provide the requested feature: #1377)

**Comment by kelset** [comment]
Hi there @rldona ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue (especially if it's a bug report) please open a new issue that uses the new Issue Template to provide some more details to help us solve it.

**Comment by Orxan43** [comment]
add to  navigationOptions of your screen : drawerLockMode: 'locked-closed'. It fixed my problem
