### ISSUE TITLE
Deep linking with nested navigators

### ISSUE THREAD

**Issue by robtaireeo** [react-community/react-navigation#687]
Is it possible to use deep linking with nested navigators?

I would have the URIprefix on the parent navigator while having a path on a screen on the inner navigator.

**Comment by joonhocho** [comment]
I am also struggling to figure out how to get this working.
It's very common pattern to have stack navigators inside tab navigator like any iOS apps.
Does anyone have a working example of this?

**Comment by reinisriekstins** [comment]
It's totally possible. Haven't tried with a StackNavigator inside a TabNavigator, however I'm building an app that has it vice versa, as can be seen below:

```
const App = StackNavigator({
  Main: {
    screen: TabNavigator({
      Lockers: {
        screen: LockersScreen,
        path: 'lockers',
        navigationOptions: {
          title: 'Lockers',
        },
      },
      History: {
        screen: HistoryScreen,
        path: 'history',
        navigationOptions: {
          title: 'History',
        },
      },
      Profile: {
        screen: ProfileScreen,
        path: 'profile',
        navigationOptions: {
          title: 'Profile',
        },
      },
    }),
    path: 'main',
  },
  ChangePassword: {
    screen: ChangePasswordScreen,
    path: 'change-password',
    navigationOptions: {
      title: 'Change Password',
    },
  },
})

const prefix = Platform.OS == 'android' ? 'reactnavtest://reactnavtest/' : 'reactnavtest://';

export default (props) => (
  <View>
    <App {...props} uriPrefix={prefix} />
  </View>
);
```

And I can access HistoryScreen on android using `reactnavtest://reactnavtest/main/history` as well as get to the ChangePasswordScreen using `reactnavtest://reactnavtest/change-password`. I've found that the key thing here is that the nested navigator has to have a valid path, so Main has to have `path: 'main'` or something similar, it can't be `path: ''` or `path: '*'`.

**Comment by diegorodriguesvieira** [comment]
Hello @reinisriekstins, I tried to follow your example, but it does not work, can you help me?

```
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 * @flow
 */

import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View,
  Platform,
} from 'react-native';

import { StackNavigator, TabNavigator } from 'react-navigation';

class HomeScreen extends Component {
  render() {
    return (
      <View>
        <Text>
          Home
        </Text>
      </View>
    );
  }
}

class ChatScreen extends Component {
  render() {
    return (
      <View>
        <Text>
          Chat screen
        </Text>
      </View>
    );
  }
}

const App = StackNavigator({
  Main: {
    screen: TabNavigator({
      Lockers: {
        screen: HomeScreen,
        path: 'lockers',
        navigationOptions: {
          title: 'Lockers',
        },
      },
      History: {
        screen: ChatScreen,
        path: 'history',
        navigationOptions: {
          title: 'History',
        },
      },
      Profile: {
        screen: HomeScreen,
        path: 'profile',
        navigationOptions: {
          title: 'Profile',
        },
      },
    }),
    path: 'main',
  },
  ChangePassword: {
    screen: HomeScreen,
    path: 'change-password',
    navigationOptions: {
      title: 'Change Password',
    },
  },
})


const prefix = Platform.OS == 'android' ? 'test://test/' : 'test://';


const MainApp = () => <App uriPrefix={prefix} />;

AppRegistry.registerComponent('AppMuffato', () => MainApp);
```

**Comment by diegorodriguesvieira** [comment]
@robtaireeo do you have any solution?

**Comment by mattfysh** [comment]
This is certainly working, just be sure that everywhere you have a `screen` in your route configs, you also have a non-empty `path`

**Comment by eduardoleal** [comment]
this should work with redux?

**Comment by Andreyco** [comment]
@eduardoleal not sure.

> Keep in mind that when a navigator is given a navigation prop, it relinquishes control of its internal state. That means you are now responsible for persisting its state, handling any deep linking, integrating the back button, etc.

**Comment by Keksike** [comment]
There seems to be some problems with this, e.g. breaking of a nested TabNavigator swipe-gesture animations after navigating to it through a deep link.

**Comment by ivanzotov** [comment]
A small article how to set up deep linking with nested navigators, hope it helps – https://medium.com/@ivanzotov/react-native-deep-linking-with-authorization-screen-drawer-and-nested-navigators-in-react-4f702b1520a0

**Comment by kelset** [comment]
Pinging OP @robtaireeo since this issue is quite old and related to an old version of the lib. If no answer I'll close in 7 days.

(Moreover, I hope the link provided by @ivanzotov is useful)

**Comment by kelset** [comment]
Hi there @robtaireeo ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue (especially if it's a bug report) please open a new issue that uses the new Issue Template to provide some more details to help us solve it.

**Comment by devanshAppiness** [comment]
https://stackoverflow.com/a/56544182/6642869 
 here i have explained the react navigation with nested navigators . i hope it will work
