### ISSUE TITLE
Disabled backButton

### ISSUE THREAD

**Issue by ThomsCass** [react-community/react-navigation#689]
Hi there,

Is there a way to disable the back button completely all I can find is this `backTitle: null`

Thanks

**Comment by joemckie** [comment]
If you don't want anything on the left side at all you could overwrite the `header.left` property to erase it. Or did you want to disable it but keep it visible?

**Comment by ThomsCass** [comment]
Hi, 

Thanks for the answer. Could you show me how you do it please ?

For now I reset the router which is not a good solution ...

```javascript
const resetAction = NavigationActions.reset({
  index: 0,
  actions: [
    NavigationActions.navigate({ routeName: 'Proteges'})
  ]
});
```

**Comment by ericvicenti** [comment]
Yes I agree with @joemckie, the fix here is to override `header.left`

**Comment by joemckie** [comment]
@ThomsCass 

```
new StackNavigator({
   ...
}, {
  navigationOptions: {
    header: {
      left: null
    }
  }
}
```

Off the top of my head but should work

**Comment by ericvicenti** [comment]
StackNavigator is a function, not a class 😄

**Comment by joemckie** [comment]
Oh yeah you're right, I just had to write it like that cause of my eslint

**Comment by MrHubble** [comment]
Thanks @joemckie, `header: { left: null}` worked for me.

**Comment by lucasleelz** [comment]
@MrHubble Click on the `Android` entity keys to return to the above can still return. And can not really be disabled.

**Comment by SoundBlaster** [comment]
Set `headerLeft: null` for `navigationOptions` of your screen to remove left item in navigation bar.

**Comment by SrSandeepKumar** [comment]
Any suggestion for using DrawerNavigator!, as we make  `headerLeft: null`, React Component used in Drawer in headerLeft will be gone.
