### ISSUE TITLE
Access to parameters in component

### ISSUE THREAD

**Issue by jurajkrivda** [react-community/react-navigation#692]
I have this issue with getting parameters in my component.

```
const action = NavigationActions.navigate({
      routeName: 'Order',
      params: { orderId, name }
    });
    navigation.dispatch(action);
```

and then

```
const withData = graphql(SOME_QUERY, {
  options: ({ navigation }) => ({
    variables: { id: navigation.state.params.orderId }
  }),
  ...
});
```

Is this the correct way to get parameters (orderId and name)? It works but I thought that it is sufficient to select parameters like

```
const withData = graphql(SOME_QUERY, {
  options: ({ orderId, name }) => ({
    variables: { id: orderId }
  }),
  ...
});
```

**Comment by ericvicenti** [comment]
Hi, can you reproduce the error without the `graphql` function? It is impossible to see what the bug is, without understanding the behavior of it.

**Comment by smitthakkar1** [comment]
Facing the same problem
