### ISSUE TITLE
TabNavigator loads in on the first tab then switches to initialRouteName

### ISSUE THREAD

**Issue by ARMATAV** [react-community/react-navigation#694]
TabNavigator loads in on the first Screen, and then flashes over to the initialRouteName screen, instead of just loading into the initialRouteName screen.

This is an issue for login routing; since if you only want to display a login modal when the user accesses the left and right tab, and let them freely access the middle tab, it instantly calls the login method upon loading since it lands on the left tab, and then moves over to the middle.

Is there a way to have it actually 'load in' on the middle tab?

**Comment by nicoceledon** [comment]
I have the same problem in iphone 5 - iOS 10.2.1. In android i didn't saw the problem, and I tried the app in android 6.0 (moto g3rd) and android 6.1(samsung S7)

**Comment by ericvicenti** [comment]
Are there any logs that you can post, that will hopefully confirm if the navigation state is correct?

I think this may be an issue with the tab view (instead of the navigator/router), and if you log the navigation state we can confirm that.

**Comment by atlanteh** [comment]
This happens to me too, I have a TabNavigator inside a StackNavigator.
@ericvicenti you are right. The state seems correct.
I noticed that when I set lazyLoad to true, this doesn't happen, so it might be related..

**Comment by ARMATAV** [comment]
These are the only logs that get sent upon navigation to my Tabs.

`2017-03-18 13:44:39.048 [info][tid:com.facebook.react.JavaScript] 'Navigation Dispatch: ', { action: 
   { type: 'Navigation/RESET',
     index: 0,
     actions: [ { type: 'Navigation/NAVIGATE', routeName: 'Tabs' } ] },
  newState: 
   { index: 0,
     routes: 
      [ { type: 'Navigation/NAVIGATE',
          routeName: 'Tabs',
          routes: 
           [ { key: 'Hangouts', routeName: 'Hangouts' },
             { key: 'Create', routeName: 'Create' },
             { key: 'Friends', routeName: 'Friends' } ],
          index: 1,
          key: 'Init0' } ] },
  lastState: 
   { index: 0,
     routes: [ { routeName: 'Verification', key: 'Init0' } ] } }
`

**Comment by nicoceledon** [comment]
In my case, when the application starts, it doesn't seems to generate any log entry. When  I change the tab, then it shows a log that makes sense. You could still could see that weird behavior. 

Other thing that i notices is the icons doesn't seems to make that weird change. It seems to be fine.

**Comment by satya164** [comment]
Can someone try this and see if it fixes their issue?

**Comment by nicoceledon** [comment]
That worked for me. Thanks!

**Comment by sercanov** [comment]
Hey @satya164 
Is that resolved with beta-7 ? I've upgraded but the issue is still there.

**Comment by ARMATAV** [comment]
Yeah - has this gone into the main package yet? Seems pretty important in terms of UX imo.

**Comment by ARMATAV** [comment]
@satya164 Your 0.0.58 commit fixes this issue 100% -- just had to npm shrinkwrap and manually update nested dependancy then npm install for anyone who comes across this.

Thanks!

**Comment by starchand** [comment]
@ARMATAV I ran npm shrinkwrap and can see: 

```
 "react-native-tab-view": {
      "version": "0.0.57",
      "from": "react-native-tab-view@>=0.0.57 <0.0.58",
      "resolved": "https://registry.npmjs.org/react-native-tab-view/-/react-native-tab-view-0.0.57.tgz"
    },
```

What do I need to do now?

**Comment by ARMATAV** [comment]
Change it to

>  "react-native-tab-view": {
      "version": "0.0.58",
      "from": "react-native-tab-view@>=0.0.58",
      "resolved": "https://registry.npmjs.org/react-native-tab-view/-/react-native-tab-view-0.0.58.tgz"
    }

Save it, and then npm install and you should see it update 'react-navigation -> react-native-tab-view@0.0.58' or something similar.

**Comment by ARMATAV** [comment]
Also @satya164 can this get added to react-navigation yet?

**Comment by satya164** [comment]
Feel free to send a PR and mention me there

**Comment by foobar8675** [comment]
I think I'm seeing the same issue, has this been merged?

**Comment by Druux** [comment]
facing the same issue as well

**Comment by Druux** [comment]
@satya164 facing the same issue as well. Is there a fix for this already available? I am on the latest version of react-navigation.
