### ISSUE TITLE
Upgrading to version 1.0.0-beta.7 crashes iOS

### ISSUE THREAD

**Issue by luisfcofv** [react-community/react-navigation#695]
iOS is crashing when upgrading to 1.0.0-beta.7 or 1.0.0-beta.6
My current version is 1.0.0-beta.5

I'm getting the following error: 

`availableWidth is indefinite so widthMeasureMode must be YGMeasureModeUndefined`

```
2017-03-15 11:36:40.228 [info][tid:main][RCTRootView.m:275] Running application app ({
    initialProps =     {
    };
    rootTag = 1;
})
2017-03-15 11:36:40.229 [warn][tid:main][RCTUIManager.m:1650] Calling of `[-RCTUIManager setFrame:forView:]` which is deprecated.
2017-03-15 11:36:40.231 [info][tid:com.facebook.react.JavaScript] Running application "app" with appParams: {"rootTag":1,"initialProps":{}}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
availableWidth is indefinite so widthMeasureMode must be YGMeasureModeUndefined
```

![screen shot 2017-03-15 at 11 40 21](https://cloud.githubusercontent.com/assets/1128284/23946987/96896afa-0974-11e7-99a7-bb84b62b3e3d.png)

Any idea how to fix it?
Thanks in advance.

**Comment by kylerc** [comment]
Getting the same error, doesn't seem to be specific to `beta.6` or `beta.7` for me though.

**Comment by ericvicenti** [comment]
I'm guessing your RN configuration has been borked in some way. You may try removing node_modules and re-installing, or try re-creating your project. You can also remove the ios and android folders and re-create them with `react-native eject` (on new versions of RN).

Lastly, if your app is pure JS, you can create the app without native dependencies with Create-React-Native-App.

Also be sure to check out the troubleshooting page on the RN docs.

Actually lastly, please re-open this if you have a consistent reproduction with react-navigation and a fresh react-native project. Be sure to report the version of RN!

**Comment by weatherfordmat** [comment]
Was there any progress on figuring out the cause? I am having this issue on beta.7. Went back to beta.6. Running RN 0.42.3.

Only fails when I specify a percentage width in a component. Setting an explicit width on a parent doesn't seem to help.

**Comment by jbovenschen** [comment]
This error, is thrown by yoga internals... Also happens on smaller iOS devices.
The exception that is thrown states;
`SIGABRT: availableWidth is indefinite so widthMeasureMode must be YGMeasureModeUndefined`
Currently looking in to finding a way to fix it.
