### ISSUE TITLE
How to goBack from nested StackNavigator?

### ISSUE THREAD

**Issue by Twinski** [react-community/react-navigation#697]
Hey everyone! 😄 
I've been trying a lot of things but nothing worked out so far.. 🤔 

```
const InsuranceAddStackNavigator = StackNavigator({
    Teaser: { screen: TeaserPage },
    Quote: { screen: QuotePage },
    TermsConditions: { screen: TermsConditionsPage },
    Pay: { screen: PayPage },
    Success: { screen: SuccessPage },
}

const RootNavigator = StackNavigator({
    Main: { 
      screen: MainNavigator,
    },
    InsuranceAdd: { 
      screen: InsuranceAddNavigator,
    },
}, {
  headerMode: 'none',
  mode: 'modal'
});

export default RootNavigator;
```

I can navigate to InsuranceAddNavigator without a problem. In InsuranceAddNavigator (which is used to go through 5 steps > Next > Next > Next ...) I'd like to be able to dismiss the whole InsuranceAddNavigator-flow from any screen inside it (eg. Teaser, Quote, Terms, ..). 

I've tried to call this.props.navigation.dispatch({ type:'Navigate/BACK', routeName:null });
Cause my modalNavigator has no routeName, correct? How can I say to my ModalNavigator: quit the InsuranceAdd-flow?

**Comment by wenbinf** [comment]
I had same problem. After doing quite a lot of research, I still couldn't find any clean & elegant solution. So I ended up putting multiple "steps" into one single screen, so goBack() from any step of this single screen would exit the entire flow. The implementation is actually not too bad, as I could 100% understand what's going on there and structure the code in a maintainable way :)

**Comment by ericvicenti** [comment]
The `Navigate/BACK` action can take a `key`, which can specify exactly which screen to go back from. Each screen can see its key by looking at `this.props.navigation.state.key`

**Comment by Twinski** [comment]
@ericvicenti  
Thanks for the suggestion. I'll have a look at it. 

- So even the "root"-stacknavigator has a key and can be controlled from anywhere? :) 
- Can you assign a custom key per StackNavigator / ..?

**Comment by InteractiveLogic** [comment]
@Twinski Were you able to solve this? I have a similar situation -- a tab navigator inside a stack navigator and I need to go back/pop the top-level stack navigator from any of the screens associated with the tabs in the nested tab navigator, and none of the things I've tried have worked... so I'm just wondering how you were able to ultimately solve your problem.

**Comment by Twinski** [comment]
I didn't give a try to be honest. Right now I switched to wix's library for native navigation. Airbnb also released their navigation library. I would try to solve some of your problems in combination with Redux? I wrote my own tab navigator to have a complete custom tabbar (with a big plus button in the middle) & to be able to select a tab from anywhere in the app. (Dispatch action "NAVIGATE_TO_TAB" with { tabbar: "home", tab: "profile" } as payload for example. Hope this gives you some inspiration to tackle your problem ;)

**Comment by xiemeilong** [comment]
I can't goback() even with a key

**Comment by dhruvparmar372** [comment]
I'm facing a similar issue. this is my current setup
```
const AppNavigator = StackNavigator({
  Login: { screen: LoginScreen },
  Splash: { screen: SplashScreen },
  Timeline: { screen: TimelineNavigator },
});

const TimelineNavigator = StackNavigator({
  Timeline: { screen: TimelineScreen },
  Task: { screen: TaskNavigator },
});

const TaskNavigator = StackNavigator({
  Task: { screen: TaskScreen },
});
```

The route flow I have in application
```
Splash -> Reset to Timeline -> Navigate to Task -> Go back to Timeline
```

For the last step, I'm trying `goBack()` & `goBack('Task')` from `TaskScreen` but it does not go back to `TimelineScreen`. Am I missing something here?

**Comment by Germinate** [comment]
@dhruvparmar372  According to the doc,  
> a navigator's navigation prop may not have the helper functions (navigate, goBack, etc); it may only have state and dispatch. 

So, use dispatch instead of goBack when the goBack not working.  Example:
`this.props.navigation.dispatch(NavigationActions.back())`

See the example [here](https://reactnavigation.org/docs/navigators/navigation-actions#Back) to learn more.

**Comment by anishu23** [comment]
@Germinate That did work. But may I ask why goBack() didn't work?

**Comment by sigridbra** [comment]
I'm having trouble with something similar. The set up is a StackNavigator nested within a TabNavigator within a StackNavigator. It workes perfectly except navigating to the outermost stacks initial screen.

 I tried the 
`this.props.navigation.dispatch(NavigationActions.back(<ScreenName>))`
but I get an error like
`In this environment the sources for assign MUST be an object.This error is a performance optimization and not spec compliant.`
What is happening?

**Comment by lorenzsell** [comment]
@Germinate's solution worked for me.

**Comment by gurudev51** [comment]
I have exactly same issue with @Twinski.
Any solutions?

**Comment by jimfilippou** [comment]
```
import { NavigationActions } from 'react-navigation'

const backAction = NavigationActions.back({
  key: null
}) 

this.props.navigation.dispatch(backAction);
```

This should do the trick!

**Comment by NamanAulakh** [comment]
@sigridbra I also faced similar problem.
I solved it as follows:
```
navigation.dispatch(
      NavigationActions.reset({
        index: 1,
        actions: [
          NavigationActions.navigate({ routeName: 'Router' }),
          NavigationActions.navigate({ routeName: 'ProfilePage' }),
        ],
      }),
    )
```

Refer [docs](https://reactnavigation.org/docs/navigators/navigation-actions#Reset)

**Comment by beausmith** [comment]
@Twinski Found this Issue when looking for a solution. @Germinate's [solution](https://github.com/react-community/react-navigation/issues/697#issuecomment-309359044) worked for going back one screen at a time, but I needed to reset back many screens. Ultimately this solution worked for my similar use case: https://github.com/react-community/react-navigation/issues/1127#issuecomment-295841343

**Comment by awinograd** [comment]
I was also a little confused by the API here. It seems like the most common use case of wanting to go back to something other than the immediately previous screen (which you can get with just `NavigationActions.back()` is to go back _to_ a given screen in the navigation state rather than back _from_. Here's some untested, use at your own risk code).

```
function getKeyToGoBackToRouteName(
  state: NavigationState,
  routeName: string
) {
  // reverse the routes so we go back to the most recent route with name=RouteName
  const reversedRoutes = state.routes.slice(0).reverse();

  const index = reversedRoutes.findIndex(r => {
    return (
      // Check if the route is the one we want
      r.routeName === routeName ||
      // Or if this is a nested Navigator route, recursively check to see if
      // it's children match
      !!(r.routes && getKeyToGoBackToRouteName(r, routeName))
    );
  });

  // If we didn't find the route, then return immediately
  if (index === -1) return null;

  // We want the key of the route _after_ routeName so that when we go back from
  // key, we are at routeName
  // Since we have reversed the routes, later routes have smaller indices
  const route = reversedRoutes[index - 1];
  return route ? route.key : null;
}

NavigationActions.back(getKeyToGoBackToRouteName('RouteToBeActiveAfterThisAction'));
```

**Comment by Guihgo** [comment]
I did all that everyone above say to do.
After read [(react navegation code)](https://github.com/react-navigation/react-navigation), i understood and now I can do that !

In my case i have 3 router : A -> B -> C 
and i want go from C to A directly. So i do this:

_on constructor  in **B.js**:_
```
constructor(props) {
    super(props);
    this.props.navigation.state.key = 'BScreen'; //set the name that you want
}
```

_on render in **C.js**:_
`<Button onPress={() => {goBack('BScreen')}}>Go BACK!</Button>`

**Comment by MatheusLima7** [comment]
@Germinate It did not work for me. Always returns to the initial route. I wanted to go back to the previous page.

**Comment by Guihgo** [comment]
@MatheusLima7 see my comment

**Comment by bluesockets** [comment]
@MatheusLima7 Your solution worked for me. In my case I wanted the back gesture to skip over one stack:

`
const RootNavigator = StackNavigator({
    Main: { 
      screen: MainNavigator,
    },
    Something: { 
      screen: SomethingNavigator,
    },
});

const SomethingNavigator = StackNavigator({
    Step1: { screen: Step1 },
    Step2: { screen: Step2 },
    Step3: { screen: Step3 },
}

export default RootNavigator;
`

My code is set up to conditionally go to either Step2 or Step3 from Step1. The behavior I want is for the back gesture to navigate to Step1 from Step3. Step2 already goes back to Step1 because of the stack order. 

By using your suggestion, and setting the navigation state key to Step2 in Step3's constructor, the navigation works for my behavior!!

`
export default class Step3 extends React.Component {
  constructor(props) {
    super(props);
    this.props.navigation.state.key = 'Step2';
  }
...
}

`
Now, swiping back from either Step2 or Step3 it always pops back to Step1.

Thanks!

**Comment by Guihgo** [comment]
@bluesockets what is @MatheusLima7  's solution ?

**Comment by rxh143030** [comment]
@Guihgo Thanks man, your code was an easy fix to my problem! However, i'm just wondering why it works?

**Comment by MatheusLima7** [comment]
@Guihgo I just wanted to return a method to a previous page in a simple way. There are routes with parameters that would cause me many problems. GoBack for me would work as a simple return to the previous page.

**Comment by wachunei** [comment]
Just in case anyone needs a solution, `goBack(null)` did the trick for me.

```js
Screen.navigationOptions = ({ navigation }) => ({
  headerRight: (
    <TouchableOpacity
      onPress={() => navigation.goBack(null)}
    >
      <Text>Back</Text>
    </TouchableOpacity>
  ),
});
```

**Comment by LadyBethJ** [comment]
thanks to the [response](https://github.com/react-navigation/react-navigation/issues/697#issuecomment-357143230) of @Guihgo I've found what I needed to solve the problem: You got the screens A, B, C and D; and you navigate from A->B->C->D. Now you're on D and wants to go back to A.
**reactnavigation's doc** gives you a few ways to do this:

- using the `navigation prop goBack` [link](https://reactnavigation.org/docs/navigators/navigation-prop#goBack-Close-the-active-screen-and-move-back)

```
this.props.navigation.goBack('B')
```

- using the `Back NavigationAction` [link](https://reactnavigation.org/docs/navigators/navigation-actions#Back)

```
this.props.navigation.dispatch(
    NavigationActions.back({key:'B'})
)
```

We're using the key = 'B', because only the screen B can go back to the screen A. But the code above doesn't work, why?
Because the key of the screen B is not 'B'; the key is another alphanumeric string which we don't know. So, to solve this, what we have to do is to set the key = 'B' in the constructor of screen B, as @Guihgo did in his comment:

```
constructor(props) {
    super(props)
    this.props.navigation.state.key = 'B'
}
```

Then, you could navigate to screen A from screen D, or C or any other screen.
This worked for me, and I hope this could help.

**Comment by beausmith** [comment]
Check out this thread for a **DismissableStackNavigator**: [How to dismiss modal containing a StackNavigator](https://github.com/react-navigation/react-navigation/issues/686#issuecomment-292225313)

And a [second comment noting an option to add the `dismiss` method to `screenProps`](https://github.com/react-navigation/react-navigation/issues/686#issuecomment-342766039)

**Comment by MrZhang123** [comment]
@Guihgo I try the code to fix bug ( creating screen B twice) ,  but it's not work , my react-navigation version is v1.5.8, how to fix ? why set key will render twice ?

**Comment by remisaado** [comment]
@LadyBethJ @Guihgo 

I am using:

`this.props.navigation.goBack('B')`

and

`this.props.navigation.state.key = 'B' // Tried in constructor and componentDidMount(), same result`

However, I keep getting this yellow box error:

`Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the B component`

And also it does not run my `componentWillUnmount()` function.

Does anyone know why I am getting this? The goBack navigation works great but why does this happen?

**Comment by martjoao** [comment]
I just spent a whole afternoon with this issue and solved it pretty simply.

My case:
RootNav
     |-----TabNavigator
                   |-----------TabA
                   |-----------TabB
                   |-----------TabC
      |-----StackNavigator
                   |-----------StackA
                   |-----------StackB

From TabC I launched stackNavigator in modal mode. I then navigated from StackA to StackB and wanted to dismiss my modal and get back to TabC.

I ended up accomplishing this with:
`
      this.props.navigation.dispatch(NavigationActions.popToTop());
      this.props.navigation.dispatch(NavigationActions.back());
`

**Comment by kevinscience** [comment]
@wachunei this.props.navigation.goBack(null) will fire constructor and componentDidMount, and fire componentWillUnmount improperly

**Comment by daveteu** [comment]
@kevinscience  can you elaborate? Because so far navigation.goBack(null) seems to be the only solution that shows the intended behavior.

**Comment by deepaksisodiya** [comment]
```
 const currentRoutes = screenProps.rootNavState.routes;
 const currentTrustedContactRoutes = currentRoutes.find(route =>
     route.routeName === 'Navigator',
 );
 const key = currentTrustedContactRoutes.routes.find(route => route.routeName === 'Screen').key;
 navigation.goBack(key); // moved one back from 'Screen'
```

**Comment by ujjwalagrawal17** [comment]
Thanks @Germinate :)

**Comment by osikes** [comment]
goBack(null) is the winner.

**Comment by DevJulianSalas** [comment]
Thanks, @wachunei  :)

**Comment by nikilarigela** [comment]
@ananth10 
``const resetAction = NavigationActions.reset({
      index: 0,
      actions: [
        NavigationActions.navigate({ routeName: 'ScreenA', params: { foo: 'bar' } }),  
      ],
    });
``

**Comment by ananth10** [comment]
@nikilarigela I dont want o reset stack, all i need is go back to Screen A from Screen C. it is working now . i have followed @Guihgo  solution. but i need to pass some params to Screen A. if i reset stack and do navigate Screen A then all data reloading from server. so i dont want to happen this.

**Comment by nikilarigela** [comment]
@ananth10 ok got it. Thanks

**Comment by jdnichollsc** [comment]
`navigation.goBack()` is not working properly as you can see here: https://github.com/proyecto26/react-native-modular
**Steps:**
- Navigate to **Component2**
- Navigate Back // It's redirected to Component1 instead  of HomeComponent

**Comment by pollen-official** [comment]
same issue as @remisaado. Using @Guihgo  's example will result in a new render for each time you switch between screens. For example going 
A->B = B renders once
A - B - A - B  = B rendering twice
A - B - A - B - A - B = B rendering thrice 

and so on. Setting the navigation key therefore is not very effective. Spent the afternoon trying to circumvent the multiple renders and couldnt find anythin

**Comment by mi-mazouz** [comment]
no solutions worked for me... this is very frustrating

**Comment by IbrahimCanKALYA** [comment]
@mi-mazouz did you find any solution for this bug ?

**Comment by mi-mazouz** [comment]
@Twinski I definitely had to put it in another stack or at the top of the main stack

**Comment by xtealer00** [comment]
> I had same problem. After doing quite a lot of research, I still couldn't find any clean & elegant solution that I could deeply understand.
> 
> So I ended up putting multiple "steps" into one single screen, so goBack() from any step of this single screen would exit the entire flow.
> 
> The implementation is actually not too bad, as I could 100% understand what's going on there and structure the code in a maintainable way :)

I'm new to react native but i hope this helps. I have found a way to navigate to a parent container from it's child using navigation.navigate() function. You have to replace `navigation.goBack` property received from parent component with `navigation.goBack = () => navigation.navigate('YourNotNestedRoute');`...

**Comment by LeDanielH** [comment]
Until recently, we had `navigation.goBack(null)`, for navigating out of nested stackNavigator. Because `navigation.goBack()` just showed us blank screen. But we noticed, `isFocused` listener stopped working whenever we called `navigation.goBack(null)`. Actually all listeners stopped working ('willBlur', 'didFocus',....)

So this is what I found out:

- When your StackNavigator is `mode: 'modal',` and you navigate to nested StackNavigator, you need to call `navigation.pop()` when you want to exit the nested StackNavigator.
- When you are within stackNavigator and there is a previous screen to navigate to, you can just call `navigation.goBack()`
- When there is no screen to go back too and your StackNavigator is nested within `mode: modal` StackNavigator, you will see the blank screen.
- When you call `navigation.goBack(null)`, navigation listeners will stop working. 

I hope this helps.

**Comment by haileymag** [comment]
Thank you @LeDanielH , navigation.pop() helped me escape a drawer navigation that would not let me return to the other navigators I had.

**Comment by felire** [comment]
Is it okey if I use a combination of `popToPop` and `goBack` to go back from a deep screen on a nested stack navigator to the original navigator

**Comment by arcsoftanil** [comment]
@Germinate You make my day

**Comment by uladzislau-stuk** [comment]
> Just in case anyone needs a solution, `goBack(null)` did the trick for me.
> 
> ```js
> Screen.navigationOptions = ({ navigation }) => ({
>   headerRight: (
>     <TouchableOpacity
>       onPress={() => navigation.goBack(null)}
>     >
>       <Text>Back</Text>
>     </TouchableOpacity>
>   ),
> });
> ```
Thanks, it works

**Comment by miki995** [comment]
For react native navigation v6 this works for me:

import { CommonActions } from '@react-navigation/native';

navigation.dispatch(CommonActions.goBack());

https://reactnavigation.org/docs/navigation-actions

**Comment by diegorochawebdg** [comment]
In my case I was using createNavigationContainerRef() as a navigation service, so whats worked for me is something like this:
`import { createNavigationContainerRef } from '@react-navigation/native';`
`export const navigationRef = createNavigationContainerRef<any>();`
`...`
`<Button onPress={() => navigationRef.goBack()} />`
