### ISSUE TITLE
Gesture navigation freezes the app on iOS

### ISSUE THREAD

**Issue by Exilz** [react-community/react-navigation#700]
I'm using the latest version of react-navigation and react-native 0.42.0.

Quite often, when I use the gesture navigation on iOS, my app freezes. The weird thing is that it's not properly crashed per se, since I can still see my notifications on screen playing, I can still drag my side-menu and so on...

I cannot navigate anymore, though. I'm struggling debugging this issue since there are no errors whatsoever (nothing in xcode on the native side, nothing in the JS console...).

It happens in both development and production.

I know it's a long shot, but I'm wondering if someone encountered the same issue ?
Gesture navigation is really smooth, it would be sad to disable them completely 😢 

Here's what's happening so you can picture it better, I'm dragging around the article view and when navigating back on the main list you can see it freeze.

![](https://media.giphy.com/media/3o7bu37AO07heunJcY/giphy.gif)

Thanks guys ! 🆘

**Comment by JulianKingman** [comment]
I had something similar, but not directly related to gestures. For me the problem turned out to be that state and props were being changed mid-navigation. So the best place to start is to check all the prop and state changes going on, and then defer them with the interactionmanager or some other means.

**Comment by Exilz** [comment]
@JulianKingman I'll try it out, thanks for the suggestion.

**Comment by GingerBear** [comment]
I have the same issue with the latest react native and react-navigation 
```
    "react-native": "0.42.0",
    "react-navigation": "^1.0.0-beta.7"
```

![mar-15-2017 18-17-11](https://cloud.githubusercontent.com/assets/902357/23973273/c6035b88-09ab-11e7-8d3a-747a778eb61e.gif)


there is the code to reproduce 

```js
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 * @flow
 */

import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View,
  Button
} from 'react-native';


import { StackNavigator, TabNavigator } from 'react-navigation';

class ChatScreen extends React.Component {
  static navigationOptions = {
    title: 'Chat with Lucy',
  };
  render() {
    const { navigate } = this.props.navigation;
    return (
      <View>
        <Text>Chat with Lucy</Text>
        <Button
          onPress={() => navigate('Chat')}
          title="Chat with Lucy"
        />
      </View>
    );
  }
}


class HomeScreen extends React.Component {
  static navigationOptions = {
    title: 'Welcome',
  };
  render() {
    const { navigate } = this.props.navigation;
    return (
      <View>
        <Text>Hello, Chat App!</Text>
        <Button
          onPress={() => navigate('Chat')}
          title="Chat with Lucy"
        />
      </View>
    );
  }
}

const SimpleApp = StackNavigator({
  Home: { screen: HomeScreen },
  Chat: { screen: ChatScreen },
});

AppRegistry.registerComponent('TestReactNavigation', () => SimpleApp);

```

**Comment by skevy** [comment]
Hi @GingerBear thanks for the gif!

Could you give master a try, and see if it fixes your issue?

**Comment by skevy** [comment]
(also thanks @Exilz !)

**Comment by Exilz** [comment]
@skevy thank you for answering so fast. I'll be trying out your changes today. I couldn't get it to freeze for now, but it's quite random so... I'll keep in touch 😄

**Comment by GingerBear** [comment]
@skevy  thanks for the answer!

I just tried master, unfortunately the issue still exist.

**Comment by nihgwu** [comment]
#527

**Comment by nihgwu** [comment]
Two weeks have passed, I don't know what's wrong with the Issues dealing, It's really a severe bug preventing react-navigation for production ready, I know I shouldn't complain about that, it's a library  maintained by the community, I should try to solve it by myself, then I just reverted the specific commit mentioned in that issue. 
But IMO this library is developed to replace the existing `Navigator` and `ExperimentalNavigation` in the official repo, and it's also be recommended too, and the `navigation template` use it, I don't think this issue should be leave abandoned for such a long time.

BTW, I also don't know what's happening with the PR process, there are pending PRs for weeks, without any response or reasons why they are still there.

Sorry for my words, I just want to see `react-navigation` become much more robust and production ready quickly.

**Comment by Exilz** [comment]
@nihgwu I missed #527 before creating this issue. I posted this one yesterday and @skevy tried to push a fix a few hours later.
It *seems* to work for me. Since you are both saying it still freezes for you, I'm wondering if I just got lucky, but it seems highly unlikely.
It might be two different problems, or be related with the state and props changing during navigation as @JulianKingman mentioned earlier.

**Comment by nihgwu** [comment]
@Exilz yes, perhaps they two different problems, 
I remember there is a issue with Native Animated about default value fixed by @janicduplessis
looks like the commit by @skevy shipped that to react-navigation, sorry I can't find the PR now

**Comment by nihgwu** [comment]
I've test the master branch, it works great, thanks @skevy 

I posted the above I just want to know what's react-navigation's attitude to the issues and PRs.

Why severe issues are left abandoned for weeks, should we label it as a **BUG**?

Why it takes so long for a PR to be merged, for example #99 , it's such an obvious bug, and the PR is extreme simple.

**Comment by Exilz** [comment]
@skevy I haven't encountered a single freeze today. I guess I can close this, thanks a ton !

**Comment by VolkRiot** [comment]
I have encountered the same problems using StackNavigator beta 22.

Is it possibly related to a redux integration? Could re-rendering or the passing of props be responsible? 

The other interesting thing I noticed is that when testing on a live device using two fingers allows the swipe to operate as normal. 

Interesting bug, really wish it could be fixed.

**Comment by Wojtechnology** [comment]
Also getting this in beta 29. Seems like a regression from the previous fixes.
