### ISSUE TITLE
How to add general-purpose tab to TabNavigator (i.e. not a screen, for opening Drawer)

### ISSUE THREAD

**Issue by JulianKingman** [react-community/react-navigation#701]
I'm nesting a TabNavigator in a DrawerNavigator, and I'd like to be able to toggle it from the a tab in the TabNavigator. Outside of creating a screen and putting a function into it's `componentWillMount` function (which seems pretty hackish), is there a good way to run a function from a tab, instead of navigate to a component? I think this would also be super useful in other scenarios in this and other navigators ("log out" button, "take picture" button, "share" button, etc...)

**Comment by christianchown** [comment]
I got this working by adapting satya164's idea from here: https://github.com/react-community/react-navigation/issues/717#issuecomment-287392565
```
const routeConfig = {
  tabBarComponent: ({ jumpToIndex, ...props }) => (
    <TabView.TabBarBottom 
      {...props}
      jumpToIndex={(index) => {
        if (index === 4) { // or whatever index your menu button is
          props.navigation.navigate('DrawerOpen')
        } else {
          jumpToIndex(index)
        }
      }}
    />),
    ...
}

const hackedTabs = TabNavigator(routes, routeConfig)
```

**Comment by JulianKingman** [comment]
Awesome, that works well enough for me.
