### ISSUE TITLE
after transition, button press doesn't work until a certain amount of time 

### ISSUE THREAD

**Issue by GingerBear** [react-community/react-navigation#703]
Touch event not always trigger when a screen popped. 

```
    "react-native": "0.42.0",
    "react-navigation": "^1.0.0-beta.7"
```
comparing react-navigation vs NavigatorIOS + NavigationExperimental

### react-navigation ([code](https://gist.github.com/GingerBear/6aedca970faae3d4cbd662e01b982f85)) 
button press doesn't work until a certain amount of time 

![mar-15-2017 18-28-10](https://cloud.githubusercontent.com/assets/902357/23973705/ba8cac1c-09ad-11e7-9228-b8b4f690098b.gif)

### NavigatorIOS ([code](https://gist.github.com/GingerBear/022a09632adc8278e3ab9db7c17a5e17)) + NavigationExperimental ([code](https://github.com/facebook/react-native/tree/0.42-stable/Examples/UIExplorer/js/NavigationExperimental)) 
button press much more responsive 

![mar-15-2017 18-26-42](https://cloud.githubusercontent.com/assets/902357/23973704/ba8c4812-09ad-11e7-9969-7b03e6a8a103.gif) ![mar-15-2017 18-32-01](https://cloud.githubusercontent.com/assets/902357/23973706/ba8cdcaa-09ad-11e7-8467-19721afbe161.gif)

**Comment by OmgDef** [comment]
I have faced the same issue

**Comment by spencercarli** [comment]
Hi! Can you check if this is still an issue in the most recent release of react-navigation? If so please ping me/re-open this issue. Thanks!
