### ISSUE TITLE
Navigating to a nested screen

### ISSUE THREAD

**Issue by davidkpham** [react-community/react-navigation#704]
Supposing I have a StackNavigator nested within another StackNavigator like below, how would I navigate to the NewChatScreen from the root? Doing navigate("NewChat") doesn't seem to work.

```
const ChatNavigator = StackNavigator({
  List: { screen: ListScreen },
  NewChat: { screen: NewChatScreen }
});

const App = StackNavigator({
  Home: { screen: HomeScreen },
  Chat: { screen: ChatNavigator }
});

AppRegistry.registerComponent('App', () => App);
```

**Comment by ldipasquale** [comment]
You have to use the third param (`action`) from `navigate` method.

https://reactnavigation.org/docs/navigators/navigation-prop

**Comment by davidkpham** [comment]
Ah, missed that. Thanks @ldipasquale.

**Comment by ericvicenti** [comment]
Actually, this should work without a nested action! Lets leave this issue open until somebody can do a deeper investigation

**Comment by nihgwu** [comment]
@ericvicenti https://github.com/react-community/react-navigation/issues/232#issuecomment-286973451 here is a very common use case, and https://github.com/nihgwu/react-native-dva-starter#advance explains why I do so

**Comment by ashconnell** [comment]
@ericvicenti it doesn't look like it will work without a nested action, the `getScreenForRouteName.js` file only looks for the route like so:

```
const routeConfig = routeConfigs[routeName];
```

If there is no routeConfig it throws an error

**Comment by grabbou** [comment]
There's now pull request opened that fixes the issue (`navigate("NewChat")` is now supposed to work)

**Comment by Tom29** [comment]
@ldipasquale what if the nested navigation is an wrapper?

`module.exports = class _ extends React.Component { ... }`

not

`module.exports = StackNavigation({})`

i've tested and it didn't navigate to its child screen
