### ISSUE TITLE
DrawerNavigator Position 

### ISSUE THREAD

**Issue by AhsanAk** [react-community/react-navigation#708]
I would like to give the starting position of drawer below the stackNavigator header, but I have no idea how I can achieve this. I've been looking at the documentation from reactnavigation.org, but can't really find any hints.

**Comment by jurassix** [comment]
You can only control the staring position from right or left, to achieve this use the `drawerPosition` option on the DrawerNavigatorConfig.

e.x.

```js
const MyApp = DrawerNavigator({
  Home: {
    screen: MyHomeScreen,
  },
  Notifications: {
    screen: MyNotificationsScreen,
  },
}, {
  drawerPosition: 'right',
});
```

**Comment by spencercarli** [comment]
Hi! In an effort to reduce the number of open issues I'm closing question-type issues that would be a better for the [react-navigation tag on StackOverflow](https://stackoverflow.com/questions/tagged/react-navigation). This is nothing personal, merely trying to get the # of issues to a more manageable level. If you think this issue should be re-opened please let me know. Thanks!
