### ISSUE TITLE
Error: `tintColor` missing from props validation

### ISSUE THREAD

**Issue by petermikitsh** [react-community/react-navigation#710]
I realize this may not be the most appropriate place to ask this question (not a bug or a feature request), but I'm sure others here may have encountered this linter error:

<img width="574" alt="screen shot 2017-03-16 at 8 19 56 am" src="https://cloud.githubusercontent.com/assets/1571918/24004008/5e64eb64-0a22-11e7-9053-18c53c84cc48.png">

Adding `tintColor` to propTypes still doesn't fix the issue:

<img width="612" alt="screen shot 2017-03-16 at 8 28 27 am" src="https://cloud.githubusercontent.com/assets/1571918/24004086/9fc75b5a-0a22-11e7-9a58-c5284f744a75.png">

Is this an issue with the `react/prop-types` rule? (Also, for context, these components are being used in a TabNavigator, but I didn't show that code).

**Comment by petermikitsh** [comment]
The solution was to name the stateless, functional wrapper component and declare propTypes on it, e.g.,

```jsx
function SubmitIcon({tintColor}) {
  return (<Icon name="create" size={30} color={tintColor} />);
}

SubmitIcon.propTypes = {
  tintColor: React.PropTypes.string.isRequired
};

Submit.navigationOptions = {
  tabBar: {
    label: 'Submit',
    icon: SubmitIcon
  }
}
```

**Comment by dmacmillan** [comment]
Is it possible to functionalize the icon name and size as well?

**Comment by justinh00k** [comment]
This doesn't seem ideal.
