### ISSUE TITLE
Using react-intl

### ISSUE THREAD

**Issue by blackxored** [react-community/react-navigation#712]
I did a search and it only came up with #210, this is exactly the problem I'm seeing with this library that I can't use react-intl to set tabbar titles or headers. It was closed a while ago and I'm not entirely sure why. IMHO i18n is a serious issue and I can't see how a navigation library would make it hard to use. Any thoughts?

**Comment by RobertSheaO** [comment]
I use `react-intl`. I accomplish it by using `setParams` from `this.props.navigation` inside `componentWillMount`. You may also want to use the same logic inside `componentWillUpdate` if that fits your needs better.

```JS
import { FormattedMessage } from 'react-intl';

class HomeScreen extends PureComponent {
  static navigationOptions = {
    title: ({ state }) => (state.params ? state.params.title : ''), // state.params is undefined on init
  };

  componentWillMount() {
    const { setParams } = this.props.navigation;

    setParams({
      title: <FormattedMessage {...messages.home} />
    });
  }
}

HomeScreen.contextTypes = {
  intl: PropTypes.object.isRequired,
};
```

**Comment by ericvicenti** [comment]
@RobertSheaO has a reasonable workaround, but there are other techniques you can use work around the lack of shared context. If you wrap your whole app with the context provider, your header component will be able to render the `<FormattedMessage>`

If anybody has suggestions on improving the docs for this sort of situation, it would be greatly appreciated!

**Comment by RobertSheaO** [comment]
BTW, my original implementation looked like this, where I actually access context.

```JS
class HomeScreen extends PureComponent {
  static navigationOptions = {
    title: ({ state }) => (state.params ? state.params.title : ''), // state.params is undefined on init
  };

  componentWillMount() {
    const { setParams } = this.props.navigation;
    const { formatMessage } = this.context.intl;

    setParams({
      title: formatMessage({ ...headerMessages.home })
    });
  }
}

HomeScreen.contextTypes = {
  intl: PropTypes.object.isRequired,
};
```

**Comment by ericvicenti** [comment]
I think it is a hack to set params on `componentWillMount`.

Instead, why not have a title component that uses `<FormattedMessage>` within it, and wrap the whole app/navigator with the IntlProvider ?

**Comment by RobertSheaO** [comment]
@ericvicenti I was only demonstrating how it could be done. My app is wrapped with `<IntlProvider>`

**Comment by ericvicenti** [comment]
Do you need to use `setParams` on `componentWillMount`? Avoid it if you can.

If your whole app is wrapped with the provider, I think this should work:

```
const HomeTitle = () => <FormattedMessage>{headerMessages.home}</FormattedMessage>

class HomeScreen extends PureComponent {
  static navigationOptions = {
    title: ({ state }) => <HomeTitle />
  };
  ...
}
```

**Comment by tukkajukka** [comment]
(Not related to react-intl but continues the same topic)

What about using `navigation.navigate` inside e.g. `navigationOptions.header`?

@RobertSheaO's workaround works perfectly in this case:

```jsx
componentWillMount() {
    const { setParams, navigate } = this.props.navigation;
    setParams({
        navigate
    });
}
```

And after that, it's possible to do e.g.:

```jsx
static navigationOptions = {
    title: 'Home',
    header: (state) => ({
        left: (
          <TouchableHighlight onPress={() => state.navigate('Somewhere')}>
            <Text>Go</Text>
          </TouchableHighlight>
        )
    })
};
```

Otherwise `navigation.navigate` is not accessible inside `navigationOptions`.

**Comment by fson** [comment]
@ericvicenti's example worked for me with a small modification – I had to use the `title` option of the header config (`navigationOptions.title` only accepts a string). This works:
```js
const HomeTitle = () => (
  <FormattedMessage id="headerMessages.home" defaultMessage="Home" />
);

class HomeScreen extends PureComponent {
  static navigationOptions = {
    header: (navigation) => ({
      title: <HomeTitle />
    }),
  };
  ...
}
```

**Comment by fson** [comment]
Maybe the `title` and `backTitle` could be changed to also accept a `ReactElement` (in addition to string) which would be rendered inside the default `Title` and `BackButton` components. I think this would be the preferred way to render localized messages, because it's the same way titles are typically rendered inside components and doesn't require any extra configuration besides the normal context set by `IntlProvider`.

**Comment by jamuhl** [comment]
For others struggling with the i18n support - react-i18next might be a easier solution:

Wrapping the navigator like: https://github.com/i18next/react-i18next/blob/master/example/react-native-expo/App.js#L14 -> so all renders nicely on language change (https://github.com/i18next/react-i18next/blob/master/example/react-native-expo/js/pages/Home.js#L21)

Than just access t and set title on component like: https://github.com/i18next/react-i18next/blob/master/example/react-native-expo/js/pages/Home.js#L10

Prefer ICU format - support is there via https://github.com/i18next/i18next-icu
(there is also an option for polyglot -> i18next-polyglot)

Detect device language:
expo -> https://github.com/i18next/react-i18next/blob/master/example/react-native-expo/js/i18n.js#L7
react-native -> https://github.com/DylanVann/i18next-react-native-language-detector

Hope that helps others struggling with the correct setup for i18n.

**Comment by thcolin** [comment]
Here our solution : 

```js
import React from 'react'
import { injectIntl } from 'react-intl'
import { createSwitchNavigator, createBottomTabNavigator } from 'react-navigation'
import Dashboard from 'pages/Dashboard'
import Loading from 'pages/Loading'

const AppNavigator = createBottomTabNavigator({
  Dashboard: {
    screen: Dashboard,
    navigationOptions: ({ screenProps }) => ({
      title: screenProps.intl.formatMessage({ id: 'page.dashboard.title' }),
    })
  }
})

const RootNavigator = createSwitchNavigator({
  Loading: Loading,
  App: AppNavigator,
}, {
  initialRouteName: 'Loading',
})

const App = injectIntl((props) => <RootNavigator screenProps={props} />)
```
