### ISSUE TITLE
How to hide a specific route from tabbar ?

### ISSUE THREAD

**Issue by MahbbRah** [react-community/react-navigation#719]
I just couldn't find how to hide a specific route from tabar? While I'm creating new routes it automatically got added on tabbar if tabbar is enabled But i want show only specific tabs Please Help

**Comment by ragnorc** [comment]
You have to create both a Stacknavigator and a Tabnavigator. The Tabnavigator should be part of the Stacknavigator. All routes you don't want in your Tabbar should be added to the parent Stacknavigator rather than to the Tabbar.

```
const TabScreenNavigator = TabNavigator({
  
  Tab1: { screen: Tab1 },
  Tab2: { screen: Tab2 },
  
});

const MainScreenNavigator = StackNavigator({
  
  ScreenNotOnTabbar: { screen: ScreenNotOnTabbar },
  Tab: { screen: TabScreenNavigator },
  
});
```

**Comment by MahbbRah** [comment]
Thanks It worked Perfectly.

**Comment by morfsys** [comment]
But this hides the `TabBar` as well. How to keep the TabBar visible?

**Comment by mw-tim** [comment]
@morfsys did you find a solution to this?

**Comment by hielfx** [comment]
You can override the default TabBarComponent setting the property `tabBarComponent` like this:
```
const BotTabHolder = createBottomTabNavigator(
  {
    Tab1: { screen: Tab1 },
    Tab2: {screen: Tab2},
    Tab3: {screen: Tab3},
    HiddenTab: {screen: HiddenTab}
  },
  {
    tabBarComponent: (props) => <CustomTabBar {...props} />
  },
);
```

Inisde CustomTabBar you can do something like this:
```
const CustomTabBarBottom = props => {
  return (
    <View style={flexDirection: "row"}}>
          {
            props.navigationState.routes.map((route) => {
              return route.key==="HiddenTab" ? null : <Button title={route.key} onPress={()=> {props.navigation.navigate(route.key)}}></Button>
            })
          }
        </View>
  );
};
```

This way you can show the routes you want while still working when using the "navigate" function.
The drawback is that you have to fully costomize the style of the TabBar.

If you want to see some example you can edit [this expo sample](https://snack.expo.io/HyVAreX1X) (which is not mine) going to `components/CustomTabBarBottom.js` and replacing the component with this one:
```
import React from "react";
import {
  TabBarBottom
} from "react-navigation";
import { View, Text, Button } from "react-native";
import { LinearGradient } from "expo";
import { Ionicons  } from '@expo/vector-icons';

const CustomTabBarBottom = props => {
  return (

        <View style={{backgroundColor: "#fff", flexDirection: "row"}}>
          {
            props.navigationState.routes.map((route) => {
              return route.key==="Account" ? null : <Button title={route.key} onPress={()=> {props.navigation.navigate(route.key)}}></Button>
            })
          }
        </View>
  );
};

const styles = {
  actionButton: {
    backgroundColor: "#6200EE",
    width: 50,
    height: 50,
    borderRadius: 50/2,
    position: "absolute",
    bottom: 40,
    left: 155,
    zIndex: 999
  },
  buttonIcon: {
    textAlign: "center",
  }
}

export default CustomTabBarBottom;
```

This way you will hide the "Account" TabBar button (and also get a pretty uggly TabBar :P).

Hope it's usefull to you all :)
