### ISSUE TITLE
StackNavigator header is partially covered by notification bar

### ISSUE THREAD

**Issue by erbridge** [react-community/react-navigation#720]
![screenshot_20170317-125336](https://cloud.githubusercontent.com/assets/1027364/24044039/53f5fc50-0b11-11e7-9d77-660a4335251c.png)

**Comment by erbridge** [comment]
This was a configuration issue using Expo.

**Comment by rcpetluru** [comment]
@erbridge Can you elaborate on what the configuration issue was? I'm seeing the same thing and I created an app using Expo.

**Comment by erbridge** [comment]
Expo appears to make the app fill the entire screen, so you need to offset by the status bar height. Just add the following style to your navigator:

```
paddingTop: Expo.Constants.statusBarHeight
```

**Comment by rahulbrilliant2004** [comment]
Sorry to bother but I tried many things with StackNavigatior but didn't found any way to achieve something like http://nimb.ws/w57XQO
My main concern is StatusBar background and shadow with https://reactnavigation.org/docs/navigators/stack

**Comment by nhnam** [comment]
Adding 
`"androidStatusBar": {
      "barStyle":"light-content"
  }`
into expo settings (app.js) should help
