### ISSUE TITLE
RFC: Simplified Navigation Options

### ISSUE THREAD

**Issue by ericvicenti** [react-community/react-navigation#722]
To simplify nav option configuration, what if we always provided it as a function?

The results of several navigationOptions will be merged. Navigator options will be overridden by static screen options, which will be overridden by route config options. Because this merging happens only at one level, we should attempt to flatten the options:

```js
static NavigationOptions = props =>({
  // these components will be rendered with screen nav props
  header: MyHeaderComponent,
  headerRight: MyRightComponent,
  headerTintColor: 'red',
  
  // this can either be a string, element, or component
  title: <TitleText>{props.navigation.state.params.name}</TitleText>,
  tabBarTintColor: 'blue',
});
```

We can add `navigationOptions` into the `screenNavigationProp`, which will allow screens to see its own computed and flattened navigationOptions. Also it will allow us to kill `HeaderProps` entirely.

Hopefully this has enough details to start off discusion. cc @grabbou @satya @skevy

**Comment by satya164** [comment]
Probably it's too much to ask, but could we have `<NavigationOptions />`?

This will solve a lot of issues and confusion people are having right now. `props => options` is a good step towards the direction, but still doesn't solve a lot of issues. Most of the time we need access to props, state and instance methods. It can be worked around, but it's not ideal. Defining the configuration inside render will make it possible to use all of it, and it's intuitive.

**Comment by csummers** [comment]
> Most of the time we need access to props, state and instance methods. It can be worked around, but it's not ideal.

I'd like to see this also.  In the mean time, can anyone speak to how they are working around this limitation currently?

**Comment by satya164** [comment]
@csummers you can try this for now https://github.com/satya164/react-navigation-addons

**Comment by BrennanRoberts** [comment]
Both this and @satya164's proposal address #943.
