### ISSUE TITLE
Pass tintColor to tabBar label

### ISSUE THREAD

**Issue by petermikitsh** [react-community/react-navigation#724]
Currently, tab bar icons receive the `tintColor` prop, but not labels. This is problematic when you use a custom component for the label. Active and non-active labels will be the same color:

e.g.,

```jsx
function Label({name}) {
  return <Text style={{textAlign: 'center', fontSize: 10}}>{name}</Text>;
}

const TabNavigatorImpl = TabNavigator({
  Home: {
    screen: Home,
    navigationOptions: {
      tabBar: {
        label: props => (<Label name='Home' {...props}/>),
        icon: props => (<IconWrapper name='home' {...props} />)
      }
    }
  },
  Submit: {
    screen: Submit,
    navigationOptions: {
      tabBar: {
        label: props => (<Label name='Submit' {...props}/>),
        icon: props => (<IconWrapper name='create' {...props} />)
      }
    }
  },
  ...
});
```

Renders a tab bar that looks like this:

<img width="368" alt="screen shot 2017-03-17 at 10 30 17 am" src="https://cloud.githubusercontent.com/assets/1571918/24055307/c194a96a-0afc-11e7-9c06-487939726d4b.png">

tintColor does seem to be respected, however, when passing in a string as the `label`.

**Comment by satya164** [comment]
Please send a PR fixing the issue.

**Comment by petermikitsh** [comment]
I realized that `active` is getting passed in; that's sufficient for styling.

```jsx
function Label({name, focused}) {
  return <Text style={{textAlign: 'center', fontSize: 10, color: focused ? '#f00' : '#000'}}>{name}</Text>;
}

Label.propTypes = {
  focused: React.PropTypes.bool.isRequired,
  name: React.PropTypes.string.isRequired
};
```

<img width="371" alt="screen shot 2017-03-17 at 10 54 40 am" src="https://cloud.githubusercontent.com/assets/1571918/24056234/26202320-0b00-11e7-9869-fc4bccc6a6a2.png">

**Comment by satya164** [comment]
Active get's passed to `icon` too. `tintColor` should be passed to `label` if you don't want to manually set color again.

**Comment by CapitanRedBeard** [comment]
Good solution Pete, I literally just ran across this problem 👍

**Comment by grabbou** [comment]
This is now supported.
