### ISSUE TITLE
Resetting stack navigation on pressing a DrawerView Item

### ISSUE THREAD

**Issue by samridhgupta** [react-community/react-navigation#725]
Hi,

I'm having difficulties in resetting the stack when I'm navigating to my Home Screen from the Drawer Sidebar. I don't know how to inject code to drawer item's onPress so that I can clear the stack and navigate to the screen. Any help would be appreciated. Thanks.

**Comment by shawngustaw** [comment]
Assuming you have a Drawer with a Stack nested inside of it, something like this should work:

```
const Root = StackNavigator({
  Home: { screen: HomeScreen },
  ...,
  ...,
  ...
});

const drawer = DrawerNavigator(Root, {
  contentComponent: Drawer,  // custom component
});
```

and then in your drawer component something like this:

```
import { NavigationActions } from 'react-navigation';

  handleHomePressed() {
    const resetAction = NavigationActions.reset({
      index: 0,
      actions: [
        NavigationActions.navigate({ routeName: 'Home'})
      ]
    })
    return () => this.props.navigation.dispatch(resetAction)
  }
```

Hopefully that works/helps!

**Comment by DFelten** [comment]
I've got the same problem and your solution isn't working for me.

```
const Stack = StackNavigator({
  Home: {
    screen: Home
  },
  Settings: {
    screen: Settings
  }
})

export const Drawer = DrawerNavigator({
  Home: {
    screen: Stack
  }},
  {
    contentComponent: HamburgerMenu
  }
)
```
And this is the menu
```
export default class HamburgerMenu extends Component {
  _onPressButton () {
    console.log('You tapped the button!')
  }

  render () {
    return <ScrollView>
      <Icon.Button
        name={'home'}
        borderRadius={0}
        size={25}
        onPress={() => { this.handleHomePressed() }}>
        <Text>{I18n.t('home')}</Text>
      </Icon.Button>

      <HamburgerButton
        text={I18n.t('home')}
        icon={'home'}
        navigation={this.props.navigation}
        link={'Home'}
      />
      <HamburgerButton
        text={I18n.t('monthlySettlement')}
        icon={'lock'}
        navigation={this.props.navigation}
        link={null}
      />
    </ScrollView>
  }

  handleHomePressed () {
    console.log('TEST')
    const resetAction = NavigationActions.reset({
      index: 0,
      actions: [
        NavigationActions.navigate({ routeName: 'Home' })
      ]
    })
    return () => this.props.navigation.dispatch(resetAction)
  }
}
```
The console log command is executed, but nothing else happend.

Thanks in advance for the help!

**Comment by shawngustaw** [comment]
Can you try changing 

`onPress={() => { this.handleHomePressed() }}>`

to 

`onPress={() => { this.handleHomePressed().bind(this) }}>`

**Comment by DFelten** [comment]
Thanks, but unfortunately, nothing has changed.

**Comment by DFelten** [comment]
Only as info for those with the same problem: I've now asked a further question on [StackOverflow](http://stackoverflow.com/questions/43090884/resetting-the-navigation-stack-for-the-home-screen-react-navigation-and-react-n).

**Comment by grabbou** [comment]
Closing in favour of #314. Drawer uses Tab behind the scenes.

**Comment by mleduque** [comment]
So what's the recommended way to do this? I skimmed #314 but it seems non-conclusive...

**Comment by joshmello** [comment]
@mleduque So I had a SignOut button on my UserProfile.js which looked like this.

```
logout = () => {
    const actionToDispatch = NavigationActions.reset({
      index: 0,
      key: null,  
      actions: [NavigationActions.navigate({ routeName: 'loginStack' })]
    })
    this.props.navigation.dispatch(actionToDispatch)
  }

```
Then in my router.js I had this.
```
const DrawerStack = DrawerNavigator({
  Profile: {screen: UserProfile},
  // Settings: {screen: UserSettings},

},
const LoginStack = StackNavigator({
  Login: { screen: Login },
  Tutorial: { screen: Tutorial },
  Register: { screen: Register },
  ForgotPass: {screen: ForgotPass},
  UserProfile: {screen: UserProfile}
},{
  headerMode: 'none',
  navigationOptions: ({navigation}) => ({
  gesturesEnabled: false,

  })
})
const PrimaryNav = StackNavigator({
  loginStack: { screen: LoginStack },
  drawerStack: { screen: DrawerNavigation }
},`
```

So really you are routing back to the login but if you are in a DrawNav "SCREEN" you have to reference back if that makes sense. Not sure if you still have the issue but thought I would post it fr other people as well.

**Comment by Cre3z** [comment]
@samridhgupta have you found a solution for this? I am having the same problem...

**Comment by awaismobylogix** [comment]
@Ariel-Rodriguez , This works fine! But animation sucks :smile:
