### ISSUE TITLE
Question: How to change tabBar color based on current tab

### ISSUE THREAD

**Issue by sigmazen** [react-community/react-navigation#727]
Hi
How do I change the tabBar background color when I change tab?
Here is some pseudo-code showing what I'm hoping for:

    _backgroundColor = function() { 
        switch (this.routeName) {
          case 'tabHome':     return { backgroundColor: '#002663' };
          case 'tabRewards':  return { backgroundColor: '#3F9C35' };
          default:            return { backgroundColor: 'white' }           
        }
    }
    
    // Tabs setup
    export const TabStack = TabNavigator({
      tabHome:     { screen: HomeStack,       },
      tabRewards:  { screen: RewardsStack,    },
    }, {
      tabBarOptions: {
        style: _backgroundColor(),
      }
    });

At the minute it's always defaulting to white :-(
Any help would be most appreciated.
Thanks in advance
Cheers

**Comment by grabbou** [comment]
Take a look at https://reactnavigation.org/docs/navigators/tab#tabBarOptions-for-TabBarBottom-default-tab-bar-on-iOS - that should help ;)
