### ISSUE TITLE
How can arbitrary props be passed to screens?

### ISSUE THREAD

**Issue by lukecwilliams** [react-community/react-navigation#728]
I haven't found an example of how to pass properties to screens that are being displayed.

For reference: using NavigatorIOS, arbitrary properties can be passed via `initialRoute.passProps`.

So I'm looking for something like:

```
TabNavigator({
  FirstTab: { screen: MyReactComponent, props: { customProp: 1 } },
});
```

**Comment by taiki-t** [comment]
Have you tried [screenProps](https://github.com/react-community/react-navigation/blob/eb6646f6da7c522083d6ac2e48d9d4aee6a97fe3/docs/api/navigators/TabNavigator.md#navigator-props) option?

**Comment by taiki-t** [comment]
[screenProps](https://github.com/react-community/react-navigation/blob/eb6646f6da7c522083d6ac2e48d9d4aee6a97fe3/docs/api/navigators/TabNavigator.md#navigator-props) option can pass arbitrary props to screens but isn't only limited to "being displayed" screen.

**Comment by arvinsim** [comment]
Still not sure how it helps though

```
export const App = StackNavigator({
  Home: { screen: HomeScreen },
  ...
})

// Should I do this here?
// <TabNav  screenProps={/* this prop will get passed to the screen components as this.props.screenProps */} />

AppRegistry.registerComponent('foobar', () => App)

```

**Comment by jbovenschen** [comment]
Answered this in #740, hope it is a good solution for your case.

**Comment by PragyaTripathi** [comment]
Yes. https://reactnavigation.org/docs/en/navigation-actions.html#setparams 
```
const setParamsActionLeaderboard = NavigationActions.setParams({
					params: { contract: this.props.contract, accountHash: accountHash },
					key: 'Leaderboard',
				});
this.props.navigation.dispatch(setParamsActionLeaderboard);
```
