### ISSUE TITLE
Navigate to URI/Deep Link

### ISSUE THREAD

**Issue by markflorisson** [react-community/react-navigation#73]
Can we manually navigate to a deep link/URI, or should we use `Linking.openURL(...)`?

**Comment by mkonicek** [comment]
What do you mean by manually navigate? Have you checked the linking example here?
https://github.com/react-community/react-navigation/tree/master/examples

**Comment by markflorisson** [comment]
Yes, I mean can we open a deeplink from within the app without having to parse it? I realize this is not a common usecase (we can always represent dynamic links within the app in a more convenient format than a deep link), so we can probably close this.

**Comment by marlonoso** [comment]
I'm wondering how can we open a link from a navigator entry. Like:

```
const Home = DrawerNavigator(
  {
    Account: { screen: Account },
    Availability: { screen: Availability },
    Favorites: { screen: Favorites },
    Website: { screen: Linking.openURL('http://www.example.com') },
  }, 
```

**Comment by ericvicenti** [comment]
@marlonoso, With the current API, you'd be best off by implementing your own drawer content component.

There are a bunch of hacks you could do, like using a dummy component and then overriding the router `getStateForAction` behavior to intercept the navigate request and do something different, but you might run into some issues with that.

But there are certainly a few ways we could improve this. If you'd like to propose a better API, feel free to open up a detailed RFC issue.

**Comment by ericvicenti** [comment]
@markflorisson  For now, you'd be best off using `Linking.openURL` in your app, but I might be in support of a `OpenURI` navigation action, if that is something you'd want to propose and push forward.

**Comment by helixbass** [comment]
@ericvicenti I was attempting to use your suggested solution of using `Linking.openURL()` (use case is navigating to a specific screen when a push notification is opened) but seem to have run into the issue that when using `Linking.openURL()` with a universal link (as opposed to a custom-protocol deeplink URI), iOS doesn't allow the app itself to handle the universal link (so `Linking.openURL()` opens Safari)

So for now am going to just manually recreate the existing `uriPrefix`/`path` navigation logic by parsing the universal link URL, but am curious how hard it'd likely be to add an `OpenURI` action, as it may be worth investing in that option as the number of universal link types on this project grows?

**Comment by netgfx** [comment]
Is there a solution to this then? Can we add a Linking.openURL directly on the drawer `screen` property? Because right now it crashes my App
