### ISSUE TITLE
Is there a way to listen on goBack() in previous component?

### ISSUE THREAD

**Issue by zhaoyi0113** [react-community/react-navigation#733]
In my current screen component, I call `this.props.navigation.navigate('nextComponent')` to navigate to the next component. In the `nextComponent` we call `goBack()` to go to the previous component. Is there a way for the previous component to register a callback function which is called on `goBack`?

**Comment by cychiuae** [comment]
Maybe you can pass a callback as a navigation param when you call `this.props.navigation.navigate('nextComponent')`
like
```js
this.props.navigation.navigate(
  'nextComponent', 
  {
    onGoBack: () => console.log('Will go back from nextComponent'),
  }
);
```

**Comment by zhaoyi0113** [comment]
this one works. but it requires callback function to be passed into other screen manually. Is there a automatical way for doing that? I need to do some render when navigation go back to previous component.

**Comment by edo1493** [comment]
Hi guys, sorry if I step in. I am looking to pop 2 routes, instead of 1. If I pass callback like this, I could call goBack() again, but it sounds really weird. Do you know a solution? 

ps: @zhaoyi0113 I would simply use redux.

**Comment by nolan-m** [comment]
@edo1493 Check out [285](https://github.com/react-community/react-navigation/issues/285).  About halfway down there is an example.   Also see [Navigation Actions Back](https://reactnavigation.org/docs/navigators/navigation-actions#Back).

**Comment by brucecodezone** [comment]
@edo1493 Have you find solution?

**Comment by edo1493** [comment]
@brucecodezone Yes. ;)

**Comment by grabbou** [comment]
For automated way, check #51

**Comment by onlybenyang** [comment]
react-navigation provide addListener function. You can listen to the WillBlur and DidFocus event to know whether it go back

**Comment by danniarreza** [comment]
Could u please tell where to put or how to declare the addListener function properly? I tried to put it on componentDidMount and nothing happens

**Comment by bradlasecke** [comment]
@danniarreza It's been a while since your comment but to follow up, you could do something like this:

`componentDidMount() {
        this.props.navigation.addListener('willBlur', () => console.info("willBlur"});
}`

**Comment by Beamanator** [comment]
FYI, according to [the 5.x docs](https://reactnavigation.org/docs/upgrading-from-4.x/#navigation-events), in react-navigation 5.x `willBlur` is gone, you have to use `blur`

**Comment by parnekov** [comment]
I have used "beforeRemove" and manage the current component/screen before he unmounted.
