### ISSUE TITLE
goBack or dispatch - do the screens actually pop off?

### ISSUE THREAD

**Issue by quangas** [react-community/react-navigation#737]
I have a navigation structure like so:

```
Login
-> MyCourses (StackNavigator)
-> AddCourse
--> Main (TabNavigator)
---> Courses (StackNavigator)
----> ExitCourse
---> Exercises (StackNavigator)
```

```
const MyCoursesNavigator = StackNavigator({
 MyCoursesMain: { screen: MyCourses },
})
```

```
const CourseNavigator = StackNavigator({
 CourseMain: { screen: CourseMain },
 CourseExit: { screen: CourseExit }
})
```

```
const MainNavigator = TabNavigator({
 Main: { screen: Main },
 Courses: { screen: CourseNavigator },
 Exercises: { screen: ExerciseNavigator },
 ... etc
})
```

**This is the primary navigation**

```
const AppNavigator = StackNavigator({
 Login: { screen: Login },
 MyCourses: { screen: MyCoursesNavigator },
 CourseInfo: { screen: MainNavigator }
})

```
I'm trying to goBack to MyCourses from CourseExit.

I tried the following which works:

```
this.props.navigation.dispatch({
      type: 'Navigation/NAVIGATE', 
      routeName: 'MyCourses',
    });
```

Now if I select another course, then exit course again and repeat, I noticed the Routes array keeps increasing in the Navigation, why is this? Does this mean the Screens are still available and are just sitting there eating up memory? Is there some way to goBack to MyCourses from CourseExit and basically remove the CourseNavigator and the MainNavigator screens all from Route stack? Basically its the equivalent of 'popping' 2 screens and landing on the desired screen. The result in the stack would just then be Login > MyCourses (just the remaining 2 routes).

I tried the following reset action hoping it would do what I wanted but actually it doesn't even recognise the 2nd level route (MyCourses), it only recognises CourseMain or CourseExit. As a result it just errors out.

```
const resetAction = NavigationActions.reset({
      index: 0,
      actions: [
        NavigationActions.navigate({ routeName: 'MyCourses' })
      ]
    })

    this.props.navigation.dispatch(resetAction);
```

Is there some other action that can be used?

**Comment by gravitywell-sawdays** [comment]
+1

**Comment by kelset** [comment]
Pinging OP @quangas since this issue is quite old and related to an old version of the lib. If no answer I'll close in 7 days.

Moreover it's referenced in #2454 and quite similar to many other open issues, so it's sort of redundant.

**Comment by kelset** [comment]
Hi there @quangas ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue (especially if it's a bug report) please open a new issue that uses the new Issue Template to provide some more details to help us solve it.
