### ISSUE TITLE
How to change right component or title of header depending on component state or props?

### ISSUE THREAD

**Issue by artembloom** [react-community/react-navigation#74]
First thanks guys for this library!
It's super easy to understand unlike others navigation libraries.
Screen (component) can change its state or props can be changed.
I tried to setParams in componentWillUpdate and other lifecycle methods and then change "right" and "title" in navigationOptions but it invoked only one time.

Sorry if I asked a dumb question.
Thanks in advance.

**Comment by temafedorov** [comment]
+ 1

**Comment by artembloom** [comment]
I found only this solution.
It works for my case, but I'm not sure this is correct for the others

`componentWillUpdate(nextProps) {
  if (this.props !== nextProps) {
    if (nextProps.someConst) {
      const right = (
        <Button
          onPress={() => nextProps.navigation.navigate('SomeScreen')}
          title="SomeScreen"
        />
      )
      nextProps.navigation.setParams({ right })
    }
  }
}

CurrentScreen.navigationOptions = {
  title: 'CurrentScreen',
  header: ({ state }) => {
    if (state.params) {
      return { right: state.params.right }
    }
    return null
  }
}`

**Comment by kennydee** [comment]
:/ is there another solution ? I want to do the same things, to have a button at the right of the Navigation Bar, but i don't found another way to have access to the component props in the `navigationOptions` ?

Maybe there's a way to add component props to navigation params ?

Thanks

**Comment by artembloom** [comment]
Answer [#147](https://github.com/react-community/react-navigation/issues/147)

**Comment by housseindjirdeh** [comment]
@chimon2000 that is correct. You can run the tests using webpagetest.org/easy for both Faster 3G and EM settings with the Lighthouse Audit checked. Once you're test completes, you can click the Lighthouse score to navigate to its associated report with which First Interactive is the time that we use for all of the implementations on the site.

**Comment by assafb81** [comment]
hi @kennydee,
I've open an issue #2638 which later I found out you answered in some degree.
I want to use a react component as a header button.
I have `routes.js` file which is not a react component and when I try to change it to a react component I keep getting errors, hope you will help..

**Comment by moahmed123** [comment]
headerLeft: <Icon name='arrow-left' type='SimpleLineIcons' style={{color: '#16a085', fontSize: 18,paddingLift: 10}}/>
