### ISSUE TITLE
Setting screen specific props / params

### ISSUE THREAD

**Issue by getnashty** [react-community/react-navigation#740]
Is there a way to do this in the StackNavigator that I'm not seeing?

I would like to do something like:

```
const AuthFlows = StackNavigator({
  EnterInvite: {
    screen: EnterInvite,
    props: { ...myProps},
  }
});
```

**Comment by jbovenschen** [comment]
You can work around this with a helper factory function.

```js
function createComponent(instance, props) {
  return () => React.createElement(instance, props);
}

const AuthFlows = StackNavigator({
  EnterInvite: {
    screen: createComponent(EnterInvite, myProps),
  }
});
```

I hope this helps.

**Comment by getnashty** [comment]
Thanks @jbovenschen this seems to partially work - but that component doesn't seem to receive the navigation prop now. Any ideas?

**Comment by jbovenschen** [comment]
```js 
import merge from 'lodash/fp/merge'

function createComponent(instance, ownProps) {
  return (props) => React.createElement(instance, merge([ownProps, props], {});
}
```

This will give you the props derived from the higher order function / higher order component created with the createComponent also it works nearly the same as the createFactory function within react which will be removed in the future (Could not find the source of that...). Hope this helps :)

**Comment by satya164** [comment]
`Home: { screen: props => <Home {...props} {...myProps} /> }`

**Comment by getnashty** [comment]
thanks @jbovenschen & @satya164! - Satya's solution seems a little simpler, and is working for me so far - thanks again!

**Comment by scottbrassfield** [comment]
I was running into this same issue, and the answers above were really helpful!  

Just as an FYI, when I wrapped my screen component in a function, as described above, my navigationOptions within the actual component (e.g., screen title) were not rendering.  I set the navigationOptions within the navigator instead, and that solved the problem for me.

**Comment by JulianKingman** [comment]
Ditto, the static navigationOptions for the component seem to be ignored. @satya164 any idea how to use the component's navigationOptions?

**Comment by JulianKingman** [comment]
Ah, it has to do with hoisting the statics, but if I hoist the statics, (via `hoist-non-react-statics`), then the props are no longer passed. Here's what I have:
````javascript
import hoist from 'hoist-non-react-statics';
const DrawerNavigator = RNDrawerNavigator({
  DisputeForm: {screen: hoist((props) => (<Link {...props} screenProps={{url: 'test.com'}}/>), Link)},
})

**Comment by JulianKingman** [comment]
Inspired by this comment (https://github.com/react-community/react-navigation/issues/235#issuecomment-278386092), I did something like this:
````javascript
const links = {
  ContactForm: {
    url: 'https://www.example.com/contact',
    label: 'Contact Us',
  },
  Blog: {
    url: 'https://blog.example.com',
    label: 'Blog',
  },
}
const DrawerNavigator = RNDrawerNavigator(
  {
    Home: {screen: TabNavigator},
    ContactForm: {screen: DrawerLink},
    Blog: {screen: DrawerLink},
  },
  {
    navigationOptions(props) {
      return {
        ...props.navigationOptions,
        links,
      };
    },
  },
);

// in DrawerLink.js
// CustomDrawerItem just renders a label and runs the onPress function
DrawerLink.navigationOptions = (props) => {
  const {navigation: {state: {routeName}}, navigationOptions, screenProps} = props;
  const {links} = navigationOptions;
  return {
    drawerLabel: ({tintColor, focused}) => {
      return (
        <CustomDrawerItem
          focused={focused}
          tintColor={tintColor}
          onPress={() => {
            WebBrowser.openBrowserAsync(
              links[routeName].url,
            );
          }}
          label={links[routeName].label}
        />
      );
    },
  };
};
````

**Comment by Tom29** [comment]
@satya164 It only works if `Home` is an React component. If `Home` is a StackNavigator, it gets: 
![simulator screen shot aug 13 2017 3 36 25 pm](https://user-images.githubusercontent.com/5781080/29248230-2fc58f3e-803d-11e7-815c-27e1b760c7db.png)

**Comment by evanjmg** [comment]
It should be dynamic and we shouldn't have to create smart components, have to use NavigatorIOS instead

**Comment by lolobosse** [comment]
@JulianKingman I can reproduce the issue (that the navigationOption are being ignored) but I do not understand how you're fixing it (I mean I can see your code but I cannot really get what you're doing).

Can you provide a quick explanation? 🙏 😄

**Comment by JulianKingman** [comment]
AS mentioned above, it has to do with static hoisting. Static properties (duh as navigation options) do not get automatically hoisted. 

Anyway, my solution is using navigationOptions as a function that returns the built in options (props.navigationOptions), along with my additional properties. 

Does that answer your question?

**Comment by builtbyproxy** [comment]
Chances are if you've followed any of the tutorials on the first page of google. youll have a structure like this: 
![image](https://user-images.githubusercontent.com/16897508/42682666-9569251a-86ce-11e8-9f0b-cf3179c199c2.png)

Then you can either parse a `screenProps={}` to the Navigator on line 19, or parse `props => <Profile {...props} style={{ 'gradientColors': ['#f7d1d6', '#FCFAFA'] }}  />` to line 9 instead of just Profile as the value to the screen key. 

Giving you something like this: 
![image](https://user-images.githubusercontent.com/16897508/42682761-cbb854b0-86ce-11e8-8bdb-00e5e9034432.png)

You can do either of these or both and they are received as youd expect with `this.props.style.gradientColors` in the case of line 9.

Sorry to dig up an old issue but this was the one that helped me so ill add this here since it seems the most 'findable' in a google search.

**Comment by TomasGonzalez** [comment]
@JulianKingman 

> Ditto, the static navigationOptions for the component seem to be ignored. @satya164 any idea how to use the component's navigationOptions?

This is what i came up whith.
`class StackNavigator extends Component {
  render () {
      const Stack = createStackNavigator({
        EnterInvite: {
          screen: props => < EnterInvite {...props} {...this.props}/>,
          navigationOptions: EnterInvite.navigationOptions,
        },
      })
    return(<Stack/>)
  }
}`

**Comment by PragyaTripathi** [comment]
ScreenProps are immutable once they are set and sent once, and therefore you cannot filter them out. Perhaps you can dispatch params once you have them available. This worked beautifully for me. Courtesy of perusing the docs: https://reactnavigation.org/docs/en/navigation-actions.html#setparams It even guarantees to change the state.
```
const setParamsActionLeaderboard = NavigationActions.setParams({
					params: { contract: this.props.contract, accountHash: accountHash },
					key: 'Leaderboard',
				});
this.props.navigation.dispatch(setParamsActionLeaderboard);
```

**Comment by joebernard** [comment]
Here is a working example of how to set `navigationOptions` when screens are passed as a function to a `create*StackNavigator`. When screens are passed as a variable it is not required. Not sure if this is a bug or just an artifact of not hoisting.

https://snack.expo.io/@joebernard/c3RhdG

**Comment by vetri-iteron** [comment]
Hi @rahulgi ,

This is actually works for me. I used this method as follows,

`LogOut: {
    navigationOptions: ({navigation}) => {
      if (navigation.getParam("isSignOut") != true) {
        navigation.setParams({ isSignOut: true });
      }
      return ({
      drawerLockMode: 'locked-open',
      drawerLabel: 'Sign out'
    })},
    screen: Login
  }`

Inside the 'createDrawerNavigator'. Most people's solutions is not worked for me, but yours worked for me.

If anyone has any other ideas efficient than this, please suggest me.

Thanks.

**Comment by alangumer** [comment]
For params you can use the property params:
```js
const AuthFlows = StackNavigator({
  EnterInvite: {
    screen: EnterInvite,
    params: {
        param1: value
    },
  }
});
```
