### ISSUE TITLE
how to set header for TabNavigator?

### ISSUE THREAD

**Issue by AdamChrist** [react-community/react-navigation#741]
header props is not work in TabNavigator's navigationOptions.So I have no way to define right for header .
How can each tab have a right button in header ?

**Comment by kamalk333** [comment]
TabNavigator() function provides the ability that you want.
tab navigator function accepts two parameters, routeConfig and tabNavigatorConfig. 
In tabNavigatorConfig, you can play with whatever you need. I'll share a link for you to look at.

https://reactnavigation.org/docs/navigators/tab#TabNavigatorConfig

**Comment by InteractiveLogic** [comment]
Is it my imagination or do we have to embed a StackNavigator to actually generate a header in the first place? I couldn't even get a header to appear without getting a StackNavigator in the mix... it feels like I was doing something incorrectly but if it works, that's good enough for me right now.

However, I'd still like to know if that's the correct way of doing it...

**Comment by Rewieer** [comment]
I guess that according to @kamalk333 you have to provide your own custom tabbar with your header to have it

**Comment by jkbreunig** [comment]
How to set top tabbar beneath header?

**Comment by grabbou** [comment]
The answer is: 
```js
StackNavigator({
   MyTab: {
     screen: TabNavigator({ }),
     navigationOptions: { title: 'Header title' }
  }
})
```
You have to put it inside `Stack` to get a header component.

**Comment by 0x6e6562** [comment]
@grabbou Thanks for the tip about nesting the `TabNavigator` inside the `StackNavigator` to get headers - this is working well for me.

Following on from this, I was wondering what the idiomatic way is to handle a complete navigation reset, since I haven't found a function to reset the router and I've had to use what feels like a bit of a hack.

Given this nested config:

```js
const Routes = {
    First: { screen: FirstScreen },
    Second: { screen: SecondScreen },
    Settings: { screen: SettingsScreen },
};

const TabConfig = {
  stateName: 'MainNavigation',
  tabBarOptions: {
    activeTintColor: '#e91e63',
    labelStyle: {
      fontSize: 12,
    },
  },
};
```

If I dispatch a reset to the to the `TabNavigator` using #1384

```js
const resetMain = NavigationActions.reset({
   index: 0,
   stateName: 'MainNavigation',
   actions: [
     NavigationActions.navigate({ routeName: 'First' })
   ]
});
```

This will not reset the `TabNavigator` to it's initial state. I'm not quite sure whether this is part of the scope of #1384, but more generally what it means to reset a `TabNavigator`.

So to work around this, I've tried to make the parent `StackNavigator` rebuildable:

```js
const buildStack = () => (
  StackNavigator({
    screen: {
      screen: TabNavigator(Routes, TabConfig),
    }
  })
)
```

Using this builder, I can create the initial stack and then I can subscribe to the `Navigation/RESET` action and in this case I re-initialize the stack:

```js
const Stack = buildStack();

export const navigationReducer = (state, action) => {
  if (action.type === 'Navigation/RESET') {
    const resetStack = buildStack();
    return resetStack.router.getStateForAction(action, null);
  }
  return Stack.router.getStateForAction(action,state);
}
```

This feels like I'm missing the point somewhere - is there a more idiomatic way to achieve this?

**Comment by BransonGitomeh** [comment]
I have the tab navigator under inside stack navigator, and i want to have the tab navigator to have the same elevation as the header to have the same look... Any clues? any support for this that's simple?

**Comment by itanhduy** [comment]
Thanks @grabbou,
It worked for me. I'm wondering. How can I change the title for each screen inside TabNavigator?
Many thanks.

**Comment by hezhii** [comment]
@itanhduy Have you solved it?

**Comment by cordosvictor** [comment]
Thanks @grabbou. Wrapping the TabNavigator with a StackNavigator works.
@itanhduy @hezhii If you're still looking for a solution to change the title for each screen..

**Comment by cordosvictor** [comment]
Thanks @grabbou. Wrapping the TabNavigator with a StackNavigator works nicely.
@itanhduy @hezhii Found a way to change the title for each screen (using React Navigation v2 API).

```js
const getCurrentRoute = (navigationState) => {
    if (!navigationState) {
        return null
    } else if (!navigationState.routes) {
        return navigationState
    }

    const route = navigationState.routes[navigationState.index]
    if (route.routes) {
        return getCurrentRoute(route)
    }

    return route
}

const Routes = {
   TabStack: { key: "TabStack" },

   Screen1: { key: "Screen1", title: "Screen 1" }, 
   Screen2: { key: "Screen2", title: "Screen 2" },
   Screen3: { key: "Screen3", title: "Screen 3" },
}

const tabNavigator = createMaterialTopTabNavigator({
      [Routes.Screen1.key]: { screen: FirstScreen },
      [Routes.Screen2.key]: { screen: SecondScreen },
      [Routes.Screen3.key]: { screen: ThirdScreen },
   }, {
      initialRouteName: Routes.Screen1.key,
      ...
      tabBarOptions: { ... }
   }
)

const mainNavigator = createStackNavigator({
      [Routes.TabStack.key]: tabNavigator
   }, {
      initialRouteName: Routes.TabStack.key,
      navigationOptions: ({ navigation }) => {
         // triggered each time you're changing a tab

         const navRoute = getCurrentRoute(navigation.state)
            , route = navRoute && navRoute.routeName && Routes[navRoute.routeName]
            , title = route ? route.title : ""

         return { title }
      }
   })
)

export default mainNavigator
```

And each time you're changing a tab, mainNavigator's navigationOptions will trigger.

**Comment by chj-damon** [comment]
what if It's not just a title, but a custom component???
If I wrap a stack navigator in Tab navigator, I need to hide tabbar if I navigate to some inner screens under the stack. and also, the default navigate.goBack() can not work as expected. Isn't there a better way to solve this?

**Comment by StefanDimov** [comment]
Hey guys,

This is how I solved the problem for my project:

```
const aScreen = () => {
  // Screen Implementation
}

const makeAScreenConfig = navigation => {
  // return navigationOptions to set on TabsNavigator
  return {
    title: 'Habits',
    headerRight: (<MaterialIcons name="add" size={30} />),
  }
}

import { aScreen, makeAScreenConfig } from './aScreen'
import { bScreen, makeBScreenConfig } from './bScreen'
import cScreen from './cScreen'

const Tabs = createBottomTabNavigator(
  { aScreen, bScreen },
  {
    navigationOptions: ({ navigation }) => {
      const { routeName } = navigation.state.routes[navigation.state.index]

      if (routeName === 'aScreen') {
        return makeAScreenConfig(navigation)
      }

      if (routeName === 'bScreen') {
        return makeBScreenConfig(navigation)
      }
    },
  },
)

const MainStack = createStackNavigator({ Tabs, cScreen })
const AppContainer = createAppContainer(MainStack)

```

Basically I pass the Tab Screen configuration to be set on the TabNavigator so it can be read from the StackNavigator on top.

It's a little dirty, but in case of a TabNavigator you won't have that many tabs so it's not that bad of a solution.

**Comment by avitorio** [comment]
@chj-damon I have used @grabbou's answer and worked it out like this:
`
            navigationOptions: navigation => ({
              header: <Header {...navigation} />,
            }),
            cardStyle: {
              backgroundColor: 'black',
            },`

**Comment by Stringsaeed** [comment]
the best way to control every screen it would be like this:
```
- tabs
    - screenKey:
        - stack
            - screen1
            - navigation options
                - header
    - screenKey:
        - stack
            - screen2
            - navigation options
                - header 
```
```js
// example.js
const tabs = createBottomTabNavigator({
	screen1: createStackNavigator({
		stackedScreen: Screen1,
	}, {
		defaultNavigationOptions: {
			header: // your header
		}
	}),
	screen2: createStackNavigator({
		stackedScreen: Screen2,
	}, {
		defaultNavigationOptions: {
			header: // your header
		}
	}),
});
```

**Comment by luckytuvshee** [comment]
For newer (> 5) version, it helped me,

**Comment by luckytuvshee** [comment]
For newer (>= 5) versions, it helped me, (link)[https://reactnavigation.org/docs/nesting-navigators/]

```
function Home() {
  return (
    <Tab.Navigator>
      <Tab.Screen name="Feed" component={Feed} />
      <Tab.Screen name="Messages" component={Messages} />
    </Tab.Navigator>
  );
}

function App() {
  return (
    <NavigationContainer>
      <Stack.Navigator>
        <Stack.Screen name="Home" component={Home} />
        <Stack.Screen name="Profile" component={Profile} />
        <Stack.Screen name="Settings" component={Settings} />
      </Stack.Navigator>
    </NavigationContainer>
  );
}
```

**Comment by micheilsgrey** [comment]
> For newer (>= 5) versions, [this documentation](https://reactnavigation.org/docs/nesting-navigators) helped me.
> 
> ```
> function Home() {
>   return (
>     <Tab.Navigator>
>       <Tab.Screen name="Feed" component={Feed} />
>       <Tab.Screen name="Messages" component={Messages} />
>     </Tab.Navigator>
>   );
> }
> 
> function App() {
>   return (
>     <NavigationContainer>
>       <Stack.Navigator>
>         <Stack.Screen name="Home" component={Home} />
>         <Stack.Screen name="Profile" component={Profile} />
>         <Stack.Screen name="Settings" component={Settings} />
>       </Stack.Navigator>
>     </NavigationContainer>
>   );
> }
> ```

And how ecactly it helped? I need to set header title for each tab in nested Tab navigator and if i understand right it will show header 'Home' no matter what tab you klick.

**Comment by chj-damon** [comment]
```js
function getTabHeaderTitle(route: RouteProp<RootParamList, 'BottomTabs'> & { state?: State }) {
  const routeName = route.state ? route.state.routeNames[route.state.index] : route.params?.screen || 'Feed';
  return routeName;
}
```
this can render different title based on different tab

**Comment by nbcnc** [comment]
I had a similar problem with Tab Navigator.  I wanted the header buttons to change depending on which tab I'm currently on.  Here's my solution:

1.  In each of my Tab screens, I add a 'focus' event listener to the navigation prop passed to each screen:

```
function componentDidMount() {
    this.props.navigation.addListener('focus', this.setHeaderOptions);
}
```

2.  setHeaderOptions is a function that uses dangerouslyGetParent to make changes to the **parent screen** which actually controls the header for both tabs:

```
setHeaderOptions=()=> {
    this.props.navigation.dangerouslyGetParent().setOptions({headerRight: () => <AnythingYouWant/>});
};
```

This feels like a hack but I consider it a huge flaw in React Navigation v5 that you can't update the header (or use setOptions) from within a Tab Screen.  In my case, the Tab Screen is the child of a StackNavigator.  If there is a better way to do it, it's not documented very clearly.

**Comment by micheilsgrey** [comment]
All i did is put my 3 main screens in 3 `StackNavigator`'s and the put 3 stacks in `BottomTabNavigator` and then put bottom Tab inside StackNavigator so i could show some screens  modal.

```Javascript
const TabHomeStack = () => {
  return (
    <HomeStack.Navigator>
      <HomeStack.Screen
        name='Home'
        component={HomeScreen}
        options={screenOptions}
      />
    </HomeStack.Navigator>
  );
};

const TabDiscoverStack = () => {
  return (
    <DiscoverStack.Navigator>
      <DiscoverStack.Screen
        name='Discover'
        component={DiscoverScreen}
        options={screenOptions}
      />
    </DiscoverStack.Navigator>
  );
}

const TabProfileStack = () => {
  return (
    <ProfileStack.Navigator>
      <ProfileStack.Screen
        name='Profile'
        component={ProfileScreen}
        options={screenOptions}
      />
    </ProfileStack.Navigator>
  )
}

const TabNavigator = () => {
  return (
    <Tab.Navigator
      tabBarOptions={{
        activeTintColor: '#2F80ED',
        inactiveTintColor: '#999999',
        style: {
          backgroundColor: '#133740',
          height: Platform.OS === 'ios' ? 94 : 60,
          borderTopWidth: 0
        },
        labelStyle: {
          //color: '#3D908E',
          fontFamily: 'Beaufort',
          fontSize: 12,
          lineHeight: 13,
          textAlign: 'center'
        }
      }}>
      <Tab.Screen
        name='Home'
        component={TabHomeStack}
        // options={{ tabBarLabel: ({ color, focused }) => (
        //   <Text style={{ color: color }}>Home</Text>
        // )}}
        options={{ tabBarIcon: ({color, focused, size}) => (
          <Image
          source={images.tabBarIcon} 
          style={{ tintColor: color }}
          />
        )}}
      />
      <Tab.Screen
        name='Discover'
        component={TabDiscoverStack}
        options={{ tabBarIcon: ({color, focused, size}) => (
          <Image
          source={images.tabBarIcon} 
          style={{ tintColor: color }}
          />
        )}}
      />
      <Tab.Screen
        name='Profile'
        component={TabProfileStack}
        options={{ tabBarIcon: ({color, focused, size}) => (
          <Image
          source={images.tabBarIcon} 
          style={{ tintColor: color }}
          />
        )}}
      />
    </Tab.Navigator>
  );
};

const RootStackNavigator = () => {
  return (
    <RootStack.Navigator mode='modal'>
      <RootStack.Screen
        name='TabNavigator'
        component={TabNavigator}
        options={{ headerShown: false }}
      />
      <RootStack.Screen
        name='ModalPlayer'
        component={StreamsPlayer}
        options={{ headerShown: false }}
      />
    </RootStack.Navigator>
  );
}
```

**Comment by SaeedZhiany** [comment]
**For people using react-navigation 5.x.x and looking a solution**

@nbcnc and @micheilsgrey's solution might work but they are hard to extend and causes many duplicated codes.

I found [this documentation](https://reactnavigation.org/docs/screen-options-resolution#setting-parent-screen-options-based-on-child-navigators-state). it introduces a cleaner approach to setting every parent navigator option based on child navigator state.

**Comment by yosikal** [comment]
@SaeedZhiany  - it's working when it comes to styling the header, set the title, etc. I'm still confused on how to add buttons to the header that interacts with the screen itself.

**Comment by nbcnc** [comment]
@yosikal, that's the same issue I had since all of my logic for the header buttons resides in the component itself.  I used @SaeedZhiany's solution but I moved the `navigation.setOptions()` function inside the component where all of my logic resides for that particular screen.

**Comment by hungdev** [comment]
@nbcnc it isn't working in Tab.

**Comment by gshoanganh** [comment]
> **For people using react-navigation 5.x.x and looking a solution**
> 
> @nbcnc and @micheilsgrey's solution might work but they are hard to extend and causes many duplicated codes.
> 
> I found [this documentation](https://reactnavigation.org/docs/screen-options-resolution#setting-parent-screen-options-based-on-child-navigators-state). it introduces a cleaner approach to setting every parent navigator option based on child navigator state.

yeah! thank. This is what I need.

**Comment by gshoanganh** [comment]
This is what you need:

```
import * as React from 'react';
import { NavigationContainer, StackActions } from '@react-navigation/native';
import { createStackNavigator } from '@react-navigation/stack';
import {
    StyleSheet, Text, View, Button,
    TouchableOpacity,
    Image,
    Alert,
    ScrollView,
    FlatList,
} from 'react-native'; 
const Stack = createStackNavigator();
import { createBottomTabNavigator } from '@react-navigation/bottom-tabs';
import MaterialCommunityIcons from 'react-native-vector-icons/MaterialCommunityIcons';
const Tab = createBottomTabNavigator();

export default class App extends React.Component {
 HomeTabs=() => {
    return (<Tab.Navigator
        //initialRouteName="Home"
        tabBarOptions={{
            labelStyle: {
                fontSize: 10, 
            },
            //activeTintColor: 'red', 
            //inactiveTintColor: 'blue',

        }}
    >
        <Tab.Screen
            name="Home"
            component={HomePage}
            options={{
                tabBarLabel: 'For me',
                tabBarIcon: ({ color, size }) => (
                    <MaterialCommunityIcons name="home" color={color} size={19} />
                )
            }}
        />
        <Tab.Screen
            name="Help"
            component={HelpPage}
            options={{
                tabBarLabel: 'Help',
                tabBarIcon: ({ color, size }) => (
                    <MaterialCommunityIcons name="account" color={color} size={19} />
                ),
            }}
        /> 
    </Tab.Navigator>)
}
render() { 
    return (
        <NavigationContainer>
            <Stack.Navigator>
                <Stack.Screen name="Home" component={this.HomeTabs} />
               <Stack.Screen name="Settings" component={FeedScreen} /> 
            </Stack.Navigator>
        </NavigationContainer>
    );     
}
}

function FeedScreen({ navigation }) {
    return (
      <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
        <Button
          title="Go to Settings"
          onPress={() => navigation.navigate('Settings')}
        />
      </View>
    );
  }
```

**Comment by jacobmakarsky** [comment]
> options={{
>                 tabBarLabel: 'Help',
>                 tabBarIcon: ({ color, size }) => (
>                     <MaterialCommunityIcons name="account" color={color} size={19} />
>                 ),
>             }}

This only allows for a static header on each tab.. can't change the title of the header since it is just "Home" in `Stack.screen name = "Home"`

**Comment by stefanfrancis93** [comment]
> **For people using react-navigation 5.x.x and looking a solution**
> 
> @nbcnc and @micheilsgrey's solution might work but they are hard to extend and causes many duplicated codes.
> 
> I found [this documentation](https://reactnavigation.org/docs/screen-options-resolution#setting-parent-screen-options-based-on-child-navigators-state). it introduces a cleaner approach to setting every parent navigator option based on child navigator state.

Thankyou that worked!

**Comment by hackrx** [comment]
> This is what you need:
> 
> ```
> import * as React from 'react';
> import { NavigationContainer, StackActions } from '@react-navigation/native';
> import { createStackNavigator } from '@react-navigation/stack';
> import {
>     StyleSheet, Text, View, Button,
>     TouchableOpacity,
>     Image,
>     Alert,
>     ScrollView,
>     FlatList,
> } from 'react-native'; 
> const Stack = createStackNavigator();
> import { createBottomTabNavigator } from '@react-navigation/bottom-tabs';
> import MaterialCommunityIcons from 'react-native-vector-icons/MaterialCommunityIcons';
> const Tab = createBottomTabNavigator();
> 
> export default class App extends React.Component {
>  HomeTabs=() => {
>     return (<Tab.Navigator
>         //initialRouteName="Home"
>         tabBarOptions={{
>             labelStyle: {
>                 fontSize: 10, 
>             },
>             //activeTintColor: 'red', 
>             //inactiveTintColor: 'blue',
> 
>         }}
>     >
>         <Tab.Screen
>             name="Home"
>             component={HomePage}
>             options={{
>                 tabBarLabel: 'For me',
>                 tabBarIcon: ({ color, size }) => (
>                     <MaterialCommunityIcons name="home" color={color} size={19} />
>                 )
>             }}
>         />
>         <Tab.Screen
>             name="Help"
>             component={HelpPage}
>             options={{
>                 tabBarLabel: 'Help',
>                 tabBarIcon: ({ color, size }) => (
>                     <MaterialCommunityIcons name="account" color={color} size={19} />
>                 ),
>             }}
>         /> 
>     </Tab.Navigator>)
> }
> render() { 
>     return (
>         <NavigationContainer>
>             <Stack.Navigator>
>                 <Stack.Screen name="Home" component={this.HomeTabs} />
>                <Stack.Screen name="Settings" component={FeedScreen} /> 
>             </Stack.Navigator>
>         </NavigationContainer>
>     );     
> }
> }
> 
> function FeedScreen({ navigation }) {
>     return (
>       <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
>         <Button
>           title="Go to Settings"
>           onPress={() => navigation.navigate('Settings')}
>         />
>       </View>
>     );
>   }
> ```
> 
>

This is exactly what I am doing, but now I have an issue, in the Home screen, I have a flatList and I want to `scrollToTop` when the user taps it twice, I know we can achieve this by using listener `tabPress` but now the question is how can I pass this listener to my stack navigator so that in Home screen I can call this listener.
[Reference to listener](https://reactnavigation.org/docs/bottom-tab-navigator#tabpress)
Any suggestions on this?

**Comment by Mersall** [comment]
` navigation.setOptions({
    headerTitle: getHeaderTitle(route),
    headerRight: () => (
      <Button
        onPress={() => alert("This is a button!")}
        title="Info"
        color="#fff"
      />
    ),
  });`

**Comment by SurajanShrestha** [comment]
> **For people using react-navigation 5.x.x and looking a solution**
> 
> @nbcnc and @micheilsgrey's solution might work but they are hard to extend and causes many duplicated codes.
> 
> I found [this documentation](https://reactnavigation.org/docs/screen-options-resolution#setting-parent-screen-options-based-on-child-navigators-state). it introduces a cleaner approach to setting every parent navigator option based on child navigator state.

Thank You So Much!!!
