### ISSUE TITLE
route when push notification is opened

### ISSUE THREAD

**Issue by ddeanto** [react-community/react-navigation#742]
I want to route the user to a specific screen when they open a push notification. I don't understand how to do this because it seems I can't pass the navigation prop to myhighest order component. 

For example, I want to do something like this: http://stackoverflow.com/questions/42359027/react-native-render-a-page-on-push-notification

**Comment by ddeanto** [comment]
The solution may involve this https://reactnavigation.org/docs/navigators/#Calling-Navigate-on-Top-Level-Component

**Comment by raubas** [comment]
I use redux, and have a handler for the push-notification which triggers a navigation-action, works pretty smooth - although the correct view is pushed on the stack when the app is opened (would be neat to have it rendered initially) but works brilliantly for my use-case.

**Comment by ddeanto** [comment]
@raubas Where is the handler implemented? On your top level component? If so, I am confused how to use navigationActions from the top level component since I do not know how to dispatch them without access to a screen's navigation prop. Am I being stupid lol?

**Comment by raubas** [comment]
@ddeanto I have it set up in my root views component did mount where I register for notifications and Deep-links (using branch.io)

Basically I have a onNotification function which extracts all the params needed from the notification, and call:

this.props.dispatch( handleDeepLink(pushparams) )

Then I have som actions defined for handling deep links and navigation,
```

export function handleDeepLink( pushparams, uri ){
	return async dispatch => {
                // Some additional logic here ofc..
                let { routeName, params } = pushparams
		dispatch( navigate(routeName, params) )
	}
}

export function navigate(routeName, params = {}) {
	return {
		type: NavigationActions.NAVIGATE,
		routeName,
		params
	}
}
```

**Comment by Tom29** [comment]
@raubas If you use navigate or dispatch reset action. it might redirect to the new screen, not specified route we wanted.

i've tried with this code:

```
const resetAction = NavigationActions.reset({
			index: 1,
			key: null,
			actions: [
				NavigationActions.navigate({ routeName: 'Home' }),				
				NavigationActions.navigate({ 
					routeName: 'Main',
					params: {changeToTab: 'Message'}
				})
			]
		})
		this.navigator.dispatch(resetAction)
```

My schema:

StackNavigator
- Home (view component)
- Main (TabNavigator)
- - Tab1
- - Tab2

Now i want to navigate to Main (TabNavigator) and change to Tab2
It works if my app at Home, but if i already in Main or somewhere else, it will stack to new screen.
It would break the navigation flow.

**Comment by dengue8830** [comment]
i fixed with this

```
onPressNotificacion() {
  this.navigator.dispatch(NavigationActions.navigate({ routeName: 'somescreen', params: someParams }));
}

render() {
    return (
        <AppNavigator ref={nav => { this.navigator = nav; }} />
    );
  }
```

more info: 
https://reactnavigation.org/docs/en/navigating-without-navigation-prop.html
https://github.com/react-navigation/react-navigation/issues/71

**Comment by johnculviner** [comment]
This took me longer than I wish but so far this has been a simple relatively bulletproof way of handling it with notifications that work with a toast in the foreground and a push notification in the background with 'react-native-push-notification'. The key was the custom deferred to handle when react-navigation wasn't ready yet or loading at the root of the app.

`const SwitchNavigator = createSwitchNavigator(
  {
    Main: {
      screen: mainStackNavigator,
      path: 'main',
    },
  },
  {
    initialRouteName: 'Main',
  }
)

let navigationDeferred = new Deferred()

PushNotification.configure({
  onNotification: notification => {
    console.log('notification received', notification)
    navigationDeferred.promise.then(
      navigation =>
        notification.foreground
          ? // toast the message as to not remove the user from what they are doing
            // they can click it to go to the target or click the x to dismiss
            showToast(navigation, notification)
          : // wait until we have a navigation object available to actually navigate
            // which happens if the app is just starting
            navigateFromPushNotification(navigation, notification.data)
    )

    notification.finish(PushNotificationIOS.FetchResult.NoData)
  },

  popInitialNotification: true,
})

function navigateFromPushNotification(navigation, notificationData) {
  const config = notificationScreenConfig[notificationData.notificationTypeCode]
  if (!config) return

  const resetAction = StackActions.reset({
    index: 2,
    actions: [
      NavigationActions.navigate({ routeName: 'Home' }),
      NavigationActions.navigate({ routeName: config.parentScreen }),
      NavigationActions.navigate({ routeName: 'Notification', params: { notification: notificationData } }),
    ],
  })
  navigation.dispatch(resetAction)
}

function Deferred() {
  this.promise = new Promise((resolve, reject) => {
    this.reject = reject
    this.resolve = resolve
  })
}

export default class App extends React.Component {
  render() {
    return <SwitchNavigator ref={navigatorRef => navigationDeferred.resolve(navigatorRef)} />
  }
}`

**Comment by zashishz** [comment]
Using @johnculviner response i have added following code into my App.js for handling navigations from push notification.
which will wait for navigation object to be available inside **notificationOpen** method.

Also for NavigationService file please refer [here](https://reactnavigation.org/docs/en/navigating-without-navigation-prop.html).

```javascript
import React, { Component } from "react";
import Nav from "./src/routes";
import { Provider } from "react-redux";
import { PersistGate } from "redux-persist/integration/react";
import store, { persistor } from "./src/redux";
import firebase from "react-native-firebase";

import NavigationService from './src/utils/helpers/NavigationService';

const Deferred = () => {
  var d = {};
  d.promise = new Promise(function(resolve, reject) {
      d.resolve = resolve;
      d.reject = reject;
  });
  return d;
};

const navigationDeferred = new Deferred()

class App extends Component {
  
  componentDidMount() {
    this.createNotificationListeners();
  }

  async createNotificationListeners() {
    /*
     * Triggered when a particular notification has been received in foreground
     * */
    this.notificationListener = firebase
      .notifications()
      .onNotification(notification => {
        NavigationService.navigate(notification._data.url);
      });

    /*
     * If your app is in background, you can listen for when a notification is clicked / tapped / opened as follows:
     * */
    this.notificationOpenedListener = firebase
      .notifications()
      .onNotificationOpened(async (notificationOpen) => {
        NavigationService.navigate(notificationOpen.notification._data.url);
      });

    /*
     * If your app is closed, you can check if it was opened by a notification being clicked / tapped / opened as follows:
     * */
    const notificationOpen = await firebase
      .notifications()
      .getInitialNotification();
    if (notificationOpen) {
      navigationDeferred.promise.then(() => {
        NavigationService.navigate(notificationOpen.notification._data.url);
      });
    }
    /*
     * Triggered for data only payload in foreground
     * */
    this.messageListener = firebase.messaging().onMessage(message => {
      //process data message
      console.log(JSON.stringify(message));
    });
  }
  
  render() {
    return (
      <Provider store={store}>
        <PersistGate persistor={persistor}>
          <Nav ref={navigatorRef => {
            NavigationService.setTopLevelNavigator(navigatorRef);
            navigationDeferred.resolve(navigatorRef);
        }} />
        </PersistGate>
      </Provider>
    );
  }
}

export default App;
```

**Comment by AhmedNj** [comment]
@zashishz i have the same situation, i set up the code to push notification to my application, after that i dont know how to Navigate to specific screen when notification is clicked, this is my code `import React,{Component} from 'react';
import {Platform, StyleSheet, Text, View, Alert, AsyncStorage} from 'react-native';
import{ createAppContainer,	createSwitchNavigator, createStackNavigator, createBottomTabNavigator  } from 'react-navigation'
import AppNavigator from './components/navigation/Navigator'
import firebase from 'react-native-firebase';
import { MenuProvider } from 'react-native-popup-menu';
import {YellowBox} from 'react-native';

//const AppContainer = createAppContainer(AppNavigator);

//const App = () => <AppContainer/>

export default class App extends Component {

	constructor(props){
		super(props)
		this.levelsLoaded = false;
	}

	async componentDidMount() {
		// For push notifications
		this.checkPermission();
		this.createNotificationListeners();
	}

	componentWillUnmount() {
		this.notificationListener;
		this.notificationOpenedListener;
	}

	async createNotificationListeners() {

		/*
		* Triggered when a particular notification has been received in foreground
		*
		*/
		this.notificationListener = firebase.notifications().onNotification((notification) => {
			const { title, body } = notification;
			//this.showAlert(title, body);
			//Alert.alert(title, body)
			console.log('notification');

			const localNotification = new firebase.notifications.Notification({
	    sound: 'sampleaudio',
    	show_in_foreground: true,
      })
     .setSound('sampleaudio.wav')
     .setNotificationId(notification.notificationId)
     .setTitle(notification.title)
     .setBody(notification.body)
     .android.setChannelId('fcm_FirebaseNotifiction_default_channel') // e.g. the id you chose above
     .android.setColor('#000000') // you can set a color here
     .android.setPriority(firebase.notifications.Android.Priority.High);

     firebase.notifications()
	   .displayNotification(localNotification)
	   .catch(err => console.error(err));
		});

		const channel = new firebase.notifications.Android.Channel('fcm_FirebaseNotifiction_default_channel', 'Demo app name', firebase.notifications.Android.Importance.High)
    .setDescription('Demo app description')
    .setSound('sampleaudio.wav');
  firebase.notifications().android.createChannel(channel);

		/*
		* If your app is in background, you can listen for when a notification is clicked / tapped / opened as follows:
		*
		*/
		this.notificationOpenedListener = firebase.notifications().onNotificationOpened((notificationOpen) => {
			const { title, body,} = notificationOpen.notification;
			console.log('onNotificationOpened: ');
			Alert.alert(title, body)


			//console.log("1notifOpen: " + notificationOpen)
			//console.log("1notif: " + notificationOpen.notification)
		});

		/*
		* If your app is closed, you can check if it was opened by a notification being clicked / tapped / opened as follows:
		*
		*/
		const notificationOpen = await firebase.notifications().getInitialNotification();
		if (notificationOpen) {
			const { title, body } = notificationOpen.notification;
			console.log('getInitialNotification: ');
			Alert.alert(title, body)

			//console.log("2notifOpen: " + notificationOpen)
			//console.log("2notif: " + notificationOpen.notification.title)
		}

		/*
		* Triggered for data only payload in foreground
		*
		*/
		this.messageListener = firebase.messaging().onMessage((message) => {
			//process data message
			console.log("JSON.stringify: ",JSON.stringify(message));
		});
	}

	// Alert message when a notification is received
	/*
	showAlert(title, body) {
		Alert.alert(
			title, body,
			[
			{ text: 'OK', onPress: () => console.log('OK Pressed') },
			],
			{ cancelable: false },
		);
	}*/

	async checkPermission() {
		const enabled = await firebase.messaging().hasPermission();
		if (enabled) {
			// Permission already given
			this.getToken();
		} else {
			this.requestPermission();
		}
	}

	async getToken() {
		let fcmToken = await AsyncStorage.getItem('fcmToken');
		if (!fcmToken) {
			fcmToken = await firebase.messaging().getToken();
			if (fcmToken) {
				// user has a device token
				await AsyncStorage.setItem('fcmToken', fcmToken);
			}
		}
		//alert("token: " + fcmToken)
		console.log("token: " + fcmToken)
	}

	async requestPermission() {
		try {
			await firebase.messaging().requestPermission();
			// User has authorised
			this.getToken();
		} catch (error) {
			// User has rejected permissions
			console.log('permission rejected');
		}
	}

	render() {
		const AppContainer = createAppContainer(AppNavigator);
		return (
			<MenuProvider>
				<AppContainer/>
			</MenuProvider>
		);
	}
}
`

**Comment by AhmedNj** [comment]
@zashishz i have the same situation, i set up the code to push notification to my application, after that i dont know how to Navigate to specific screen when notification is clicked, this is my code.

`
import React,{Component} from 'react';
import {Platform, StyleSheet, Text, View, Alert, AsyncStorage} from 'react-native';
import{ createAppContainer,	createSwitchNavigator, createStackNavigator, createBottomTabNavigator  } from 'react-navigation'
import AppNavigator from './components/navigation/Navigator'
import firebase from 'react-native-firebase';
import { MenuProvider } from 'react-native-popup-menu';
import {YellowBox} from 'react-native';

//const AppContainer = createAppContainer(AppNavigator);

//const App = () => <AppContainer/>

export default class App extends Component {

	constructor(props){
		super(props)
		this.levelsLoaded = false;
	}

	async componentDidMount() {
		// For push notifications
		this.checkPermission();
		this.createNotificationListeners();
	}

	componentWillUnmount() {
		this.notificationListener;
		this.notificationOpenedListener;
	}

	async createNotificationListeners() {

		/*
		* Triggered when a particular notification has been received in foreground
		*
		*/
		this.notificationListener = firebase.notifications().onNotification((notification) => {
			const { title, body } = notification;
			//this.showAlert(title, body);
			//Alert.alert(title, body)
			console.log('notification');

			const localNotification = new firebase.notifications.Notification({
	    sound: 'sampleaudio',
    	show_in_foreground: true,
      })
     .setSound('sampleaudio.wav')
     .setNotificationId(notification.notificationId)
     .setTitle(notification.title)
     .setBody(notification.body)
     .android.setChannelId('fcm_FirebaseNotifiction_default_channel') // e.g. the id you chose above
     .android.setColor('#000000') // you can set a color here
     .android.setPriority(firebase.notifications.Android.Priority.High);

     firebase.notifications()
	   .displayNotification(localNotification)
	   .catch(err => console.error(err));
		});

		const channel = new firebase.notifications.Android.Channel('fcm_FirebaseNotifiction_default_channel', 'Demo app name', firebase.notifications.Android.Importance.High)
    .setDescription('Demo app description')
    .setSound('sampleaudio.wav');
  firebase.notifications().android.createChannel(channel);

		/*
		* If your app is in background, you can listen for when a notification is clicked / tapped / opened as follows:
		*
		*/
		this.notificationOpenedListener = firebase.notifications().onNotificationOpened((notificationOpen) => {
			const { title, body,} = notificationOpen.notification;
			console.log('onNotificationOpened: ');
			Alert.alert(title, body)


			//console.log("1notifOpen: " + notificationOpen)
			//console.log("1notif: " + notificationOpen.notification)
		});

		/*
		* If your app is closed, you can check if it was opened by a notification being clicked / tapped / opened as follows:
		*
		*/
		const notificationOpen = await firebase.notifications().getInitialNotification();
		if (notificationOpen) {
			const { title, body } = notificationOpen.notification;
			console.log('getInitialNotification: ');
			Alert.alert(title, body)

			//console.log("2notifOpen: " + notificationOpen)
			//console.log("2notif: " + notificationOpen.notification.title)
		}

		/*
		* Triggered for data only payload in foreground
		*
		*/
		this.messageListener = firebase.messaging().onMessage((message) => {
			//process data message
			console.log("JSON.stringify: ",JSON.stringify(message));
		});
	}

	// Alert message when a notification is received
	/*
	showAlert(title, body) {
		Alert.alert(
			title, body,
			[
			{ text: 'OK', onPress: () => console.log('OK Pressed') },
			],
			{ cancelable: false },
		);
	}*/

	async checkPermission() {
		const enabled = await firebase.messaging().hasPermission();
		if (enabled) {
			// Permission already given
			this.getToken();
		} else {
			this.requestPermission();
		}
	}

	async getToken() {
		let fcmToken = await AsyncStorage.getItem('fcmToken');
		if (!fcmToken) {
			fcmToken = await firebase.messaging().getToken();
			if (fcmToken) {
				// user has a device token
				await AsyncStorage.setItem('fcmToken', fcmToken);
			}
		}
		//alert("token: " + fcmToken)
		console.log("token: " + fcmToken)
	}

	async requestPermission() {
		try {
			await firebase.messaging().requestPermission();
			// User has authorised
			this.getToken();
		} catch (error) {
			// User has rejected permissions
			console.log('permission rejected');
		}
	}

	render() {
		const AppContainer = createAppContainer(AppNavigator);
		return (
			<MenuProvider>
				<AppContainer/>
			</MenuProvider>
		);
	}
}
`

**Comment by AhmedNj** [comment]
@zashishz i have the same situation, i set up the code of push notificatio, and i receive the notif in my app when i send it by postman, but i dont know how to navigate to specific screen when notification is clicked.
this is my code if can you help plz :

`import React,{Component} from 'react';
import {Platform, StyleSheet, Text, View, Alert, AsyncStorage} from 'react-native';
import{ createAppContainer, } from 'react-navigation'
import AppNavigator from './components/navigation/Navigator'
import firebase from 'react-native-firebase';
import { MenuProvider } from 'react-native-popup-menu';
import {YellowBox} from 'react-native';

export default class App extends Component {

	constructor(props){
		super(props)
		this.levelsLoaded = false;
	}
	async componentDidMount() {
		// For push notifications
		this.checkPermission();
		this.createNotificationListeners();
	}
	componentWillUnmount() {
		this.notificationListener;
		this.notificationOpenedListener;
	}

	async createNotificationListeners() {
		/*
		* Triggered when a particular notification has been received in foreground
		*/
		this.notificationListener = firebase.notifications().onNotification((notification) => {
			const { title, body } = notification;
			//this.showAlert(title, body);
			//Alert.alert(title, body)
			console.log('notification');
			const localNotification = new firebase.notifications.Notification({
	                sound: 'sampleaudio',
    	                show_in_foreground: true,
      })
     .setSound('sampleaudio.wav')
     .setNotificationId(notification.notificationId)
     .setTitle(notification.title)
     .setBody(notification.body)
     .android.setChannelId('fcm_FirebaseNotifiction_default_channel') // e.g. the id you chose above
     .android.setColor('#000000') // you can set a color here
     .android.setPriority(firebase.notifications.Android.Priority.High);
     firebase.notifications()
	   .displayNotification(localNotification)
	   .catch(err => console.error(err));
		});
		const channel = new firebase.notifications.Android.Channel('fcm_FirebaseNotifiction_default_channel', 'Demo app name', firebase.notifications.Android.Importance.High)
    .setDescription('Demo app description')
    .setSound('sampleaudio.wav');
  firebase.notifications().android.createChannel(channel);
		/*
		* If your app is in background, you can listen for when a notification is clicked / tapped / opened as follows:
		*/
		this.notificationOpenedListener = firebase.notifications().onNotificationOpened((notificationOpen) => {
			const { title, body,} = notificationOpen.notification;
			console.log('onNotificationOpened: ');
			Alert.alert(title, body)
		});
		/*
		* If your app is closed, you can check if it was opened by a notification being clicked / tapped / opened as follows:
		*/
		const notificationOpen = await firebase.notifications().getInitialNotification();
		if (notificationOpen) {
			const { title, body } = notificationOpen.notification;
			console.log('getInitialNotification: ');
			Alert.alert(title, body)
		}
		/*
		* Triggered for data only payload in foreground
		*/
		this.messageListener = firebase.messaging().onMessage((message) => {
			//process data message
			console.log("JSON.stringify: ",JSON.stringify(message));
		});
	}
	async checkPermission() {
		const enabled = await firebase.messaging().hasPermission();
		if (enabled) {
			// Permission already given
			this.getToken();
		} else {
			this.requestPermission();
		}
	}
	async getToken() {
		let fcmToken = await AsyncStorage.getItem('fcmToken');
		if (!fcmToken) {
			fcmToken = await firebase.messaging().getToken();
			if (fcmToken) {
				// user has a device token
				await AsyncStorage.setItem('fcmToken', fcmToken);
			}
		}
		//alert("token: " + fcmToken)
		console.log("token: " + fcmToken)
	}
	async requestPermission() {
		try {
			await firebase.messaging().requestPermission();
			// User has authorised
			this.getToken();
		} catch (error) {
			// User has rejected permissions
			console.log('permission rejected');
		}
	}
	render() {
		const AppContainer = createAppContainer(AppNavigator);
		return (
			<MenuProvider>
				### <AppContainer/>
			</MenuProvider>
		);
	}
}`

**Comment by Vicky-SilverSky** [comment]
@zashishz can you please attatch your all code releted other files for better understanding.

thank you :)
