### ISSUE TITLE
"Menu" button in the Header when we don't have the "Back" button

### ISSUE THREAD

**Issue by danilvalov** [react-community/react-navigation#745]
When we open the first screen (the first route) the "Back" button is hidden. I have a navigation where any screen can be first (when we press any button in the Menu routes reset).

How to add the "Menu" button when we don't see the "Back" button on the first screen.

**Comment by sigmazen** [comment]
Does this work?

    header: ({ navigate }) => ({
      left: ( <TouchableHighlight onPress = {() => {navigate('destinationScreen')} }>
                <Text>Menu</Text>
              </TouchableHighlight>
             ),
      }),
