### ISSUE TITLE
TabNavigation with listview bug on iOS!

### ISSUE THREAD

**Issue by 337240552** [react-community/react-navigation#748]
TabNavigation with listview has bug on iOS. ImageViews on ListView item are not a rectangle, I've set width 200 and height 100, iOS shows as the screenshot but works perfect on android.

InfoPage's renderRow method
```
 _renderRow(info) {

    return (
         <TouchableHighlight underlayColor={'red'}
          onPress={() => this._onItemClick(info)}>
          <View style={styles.itemContainer}>
              <Image source={{uri: info.image_url}}
                style={styles.thumbnail}/>
              <View style={styles.rightContainer} >
                <Text
                  numberOfLines={2}
                  style={styles.itemTitle}>{info.title}</Text>
                  <View style={styles.infoExtra}>
                    <Text style={styles.year}> {info.publication_date} </Text>
                    <Text style={styles.readCnt}>{info.click_num}</Text>
                  </View>
              </View>
          </View>
        </TouchableHighlight>
      )
  }
}

```
navigation
````
import {
  StackNavigator,
  TabNavigator,
} from 'react-navigation'

export let MainScreenNavigator = TabNavigator({
  Info: {screen: InfoPage},
  Setting: {screen: SettingPage},
});

export let SimpleApp = StackNavigator({
  Home: {screen: MainScreenNavigator},
  VideoDetail: {screen: VideoDetail},
})
````

style
```
itemContainer: {
      paddingLeft: 6,
      paddingRight: 6,
      paddingTop: 3,
      paddingBottom: 3,
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: '#fafafa',
    },
    rightContainer: {
      position: 'relative',
      flex: 1,
      justifyContent: 'center',
    },
    thumbnail: {
      width: 120,
      height: 81,
    },
    infoExtra: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      // alignItems: 'center',
    },
    itemTitle: {
      fontSize: 20,
      marginBottom: 8,
      marginLeft: 10,
      textAlign: 'left'
    },

    year: {
      textAlign: 'left',
      marginLeft: 10,
      marginLeft: 10,
      bottom: 5,
    },

    readCnt:{
        textAlign: 'right',
        marginRight: 10,
        bottom: 5,
        alignItems: 'flex-end',
    },

```

the first screen layout not as expected
![wechatimg12](https://cloud.githubusercontent.com/assets/329210/24106147/fcc36ab8-0dc1-11e7-96bb-7e452ec2d397.jpeg)

**when I scroll up, it display as expected.**
![wechatimg1](https://cloud.githubusercontent.com/assets/329210/24154642/c32904fe-0e8c-11e7-961e-3a5b68f9a8d4.jpeg)

if i remove the navigation, it show normally.

**Comment by alvaromb** [comment]
Hi @337240552!

Which is the bug?

**Comment by 337240552** [comment]
ImageViews on ListView item are  not a rectangle,  I've set width 200 and height 100, works on android

**Comment by 337240552** [comment]
@alvaromb I've updated description.

**Comment by alvaromb** [comment]
Can you post the actual code?

**Comment by 337240552** [comment]
@alvaromb Code updated

**Comment by kelset** [comment]
Pinging OP @337240552 since this issue is quite old and related to an old version of the lib. If no answer I'll close in 7 days.

**Comment by kelset** [comment]
Hi there @337240552 ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue (especially if it's a bug report) please open a new issue that uses the new Issue Template to provide some more details to help us solve it.
