### ISSUE TITLE
How to run the examples?

### ISSUE THREAD

**Issue by Steviey** [react-community/react-navigation#75]
As far as I know we have to first init a clean RN project and then add react-navigation via yarn or npm to the new project. 

If I got it right, we then have to navigate in the new project folder to node_modules/react_navigation and do the steps described here:

https://github.com/react-community/react-navigation/tree/master/examples/NavigationPlayground

```
cd react-navigation
npm install
cd examples/NavigationPlayground
npm install
cd ../..
react-native start
cd examples/NavigationPlayground
react-native run-ios # ignore packager starting error
react-native run-android # ignore packager starting error
```
But if I do this, I get: 'Android project not found' even with two separate shells.

How do we run the examples on the correct way?

Am I the only one?

**Comment by satya164** [comment]
https://github.com/react-community/react-navigation/blob/master/docs/guides/Contributors.md#1-run-the-native-playground

**Comment by thienanle** [comment]
I'm getting duplicate module errors when running `react-native start`. 
```
Failed to build DependencyGraph: @providesModule naming collision:
  Duplicate module name: react-native-vector-icons
```
Any idea how to fix?

**Comment by satya164** [comment]
Please check the doc I linked to which has exact instrcutions to run the app.

**Comment by thienanle** [comment]
I did follow that. Still getting the duplicate module errors.

**Comment by satya164** [comment]
The doc tell you to run `npm start`, not `react-native start`

**Comment by thienanle** [comment]
I get the same duplicate module error either way.

**Comment by satya164** [comment]
Delete your node modules and try again, or just delete the node modules from the `examples/NavigationPlayground`

**Comment by dually8** [comment]
I'm getting similar errors and cannot run the examples.

```
~/D/r/e/NavigationPlayground $ > react-native start
Scanning 464 folders for symlinks in /Users/user/Downloads/react-navigation-master/examples/NavigationPlayground/node_modules (4ms)
 ┌────────────────────────────────────────────────────────────────────────────┐ 
 │  Running packager on port 8081.                                            │ 
 │                                                                            │ 
 │  Keep this packager running while developing on any JS projects. Feel      │ 
 │  free to close this tab and run your own packager instance if you          │ 
 │  prefer.                                                                   │ 
 │                                                                            │ 
 │  https://github.com/facebook/react-native                                  │ 
 │                                                                            │ 
 └────────────────────────────────────────────────────────────────────────────┘ 
Looking for JS files in
   /Users/user/Downloads/react-navigation-master/examples/NavigationPlayground 

[01/31/2017, 13:46:33] <START> Initializing Packager
[01/31/2017, 13:46:34]         HMR Server listening on /hot

React packager ready.

[01/31/2017, 13:46:37] <START> Building Haste Map
Failed to build DependencyGraph: @providesModule naming collision:
  Duplicate module name: NavigationPlayground
  Paths: /Users/user/Downloads/react-navigation-master/examples/NavigationPlayground/package.json collides with /Users/user/Downloads/react-navigation-master/examples/NavigationPlayground/__exponent/package.json

This error is caused by a @providesModule declaration with the same name across two different files.
Error: @providesModule naming collision:
  Duplicate module name: NavigationPlayground
  Paths: /Users/user/Downloads/react-navigation-master/examples/NavigationPlayground/package.json collides with /Users/user/Downloads/react-navigation-master/examples/NavigationPlayground/__exponent/package.json

This error is caused by a @providesModule declaration with the same name across two different files.
    at HasteMap._updateHasteMap (/Users/user/Downloads/react-navigation-master/examples/NavigationPlayground/node_modules/react-native/packager/react-packager/src/node-haste/DependencyGraph/HasteMap.js:158:13)
    at p.getName.then.name (/Users/user/Downloads/react-navigation-master/examples/NavigationPlayground/node_modules/react-native/packager/react-packager/src/node-haste/DependencyGraph/HasteMap.js:133:31)
```

**Comment by dually8** [comment]
Finally got it to work. Had to re-install watchman (`brew install watchman`) and give myself permissions for the `~/Library/LaunchAgents/` folder  (`sudo chown -R $(whoami) ~/Library/LaunchAgents/`). Hope this helps anyone else having trouble.

**Comment by thienanle** [comment]
@satya164 looks like the instructions work for NavigationPlayground, but it doesn't work for ReduxExample. I tried with a clean clone of the repo.

**Comment by sibelius** [comment]
I have the saem error of duplicated module name

```jsx
This error is caused by a @providesModule declaration with the same name across two different files.
Error: @providesModule naming collision:
  Duplicate module name: react-native-vector-icons
  Paths: /Users/sibelius/Dev/entria/react-navigation/node_modules/react-native/local-cli/core/__fixtures__/files/package.json collides with /Users/sibelius/Dev/entria/react-navigation/examples/ReduxExample/node_modules/react-native/local-cli/core/__fixtures__/files/package.json

This error is caused by a @providesModule declaration with the same name across two different files.
    at HasteMap._updateHasteMap (/Users/sibelius/Dev/entria/react-navigation/node_modules/react-native/packager/react-packager/src/node-haste/DependencyGraph/HasteMap.js:158:13)
    at p.getName.then.name (/Users/sibelius/Dev/entria/react-navigation/node_modules/react-native/packager/react-packager/src/node-haste/DependencyGraph/HasteMap.js:133:31)

```

**Comment by Steviey** [comment]
Got it working somehow on Win.

https://steviey.github.io/win-react-navigation/

**Comment by AlanFoster** [comment]
There appears to be duplicated running steps both within https://github.com/react-community/react-navigation/blob/master/docs/guides/Contributors.md#1-run-the-native-playground and the readme.md of the native-playground folder.

However; I am getting the same `@providesModule` warning that others are running into:

```
This error is caused by a @providesModule declaration with the same name across two different files.
Error: @providesModule naming collision:
  Duplicate module name: react-native-vector-icons
```

**Comment by AlanFoster** [comment]
I was able to solve this issue by completely deleting my git clone of react-navigation, and following the steps within the contributors [document](https://github.com/react-community/react-navigation/blob/master/docs/guides/Contributors.md#1-run-the-native-playground)

**Comment by efkan** [comment]
Is there anyone to get run the examples on Linux.
I've applied the contributors document but I couldn't get run it.

I just changed `"start": "npm run run-playground-ios"` line as `"start": "npm run run-playground-android"` on `package.json`.

The outcome:

```
npm start

> react-navigation@1.0.0-beta.11 start /home/efkan/Projects/react-navigation
> npm run run-playground-android


> react-navigation@1.0.0-beta.11 run-playground-android /home/efkan/Projects/react-navigation
> cd examples/NavigationPlayground && npm run android


> NavigationPlayground@0.1.0 android /home/efkan/Projects/react-navigation/examples/NavigationPlayground
> react-native-scripts android

7:58:32 PM: Starting packager...
7:58:35 PM: Error starting packager: Error: Couldn't start project. Please fix the errors and restart the project.
    at /xdl/src/Project.js:1039:11
    at Generator.next (<anonymous>)
    at step (/home/efkan/Projects/react-navigation/node_modules/xdl/build/Project.js:1461:191)
    at /home/efkan/Projects/react-navigation/node_modules/xdl/build/Project.js:1461:361

```

**Comment by P-A-R-U-S** [comment]
I'm getting same error message 
ARUS@ValentynPonomarenko:~/Desktop/Development/React/pluralsight1$ npm start

> pluralsight1@0.1.0 start /Users/PARUS/Desktop/Development/React/pluralsight1
> react-native-scripts start

12:28:40 PM: Starting packager...
12:28:42 PM: Error starting packager: Error: Couldn't start project. Please fix the errors and restart the project.
    at /xdl/src/Project.js:1039:11
    at next (native)
    at step (/Users/PARUS/Desktop/Development/React/pluralsight1/node_modules/xdl/build/Project.js:1461:191)
    at /Users/PARUS/Desktop/Development/React/pluralsight1/node_modules/xdl/build/Project.js:1461:361
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pluralsight1@0.1.0 start: `react-native-scripts start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pluralsight1@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/PARUS/.npm/_logs/2017-06-02T17_28_42_743Z-debug.log

**Comment by cjoshmartin** [comment]
I am getting the same error as @P-A-R-U-S

**Comment by P-A-R-U-S** [comment]
@cjoshmartin  npm update helped me.

**Comment by alexli0707** [comment]
I am getting the same error as @P-A-R-U-S
