### ISSUE TITLE
Transitioner, value is undefined

### ISSUE THREAD

**Issue by Illuday** [react-community/react-navigation#751]
Hello,

I've follow steps provided on the doc, however I can't make my Transitionner works. Here is my code : 

**index.js**
```
const app = StackNavigator({
    Login: { screen: LoginScene }
});

AppRegistry.registerComponent('app', () => app);
```
**LoginScene component (login.js) render() method**
```
<Transitioner
    navigation={this.props.navigation}
    render={this._render}
/>
```
It's really simple but it always return me those errors :

**Warning: Failed prop type: The prop `navigation.state.index` is marked as required in `Transitioner`, but its value is `undefined`.**

and

**Cannot read property 'forEach' of undefined**

Is there any example of this working ?

Thanks for your help.

**Comment by ivanbekker** [comment]
+1
Same issue here: **Cannot read property 'forEach' of undefined**.
I use **TabNavigator** inside **StackNavigator** which is integrated in Redux.

Also typechecking failed:

```
Warning: Failed prop type: The prop `navigation.state.index` is marked as required in `Transitioner`, but its value is `undefined`.
```

Code:

```javascript
  _configureTransition = (transitionProps, prevTransitionProps) => {
    return {
      duration: 500,
      easing: Easing.bounce,
    };
  }


  render() {
    return (
      <Transitioner
        configureTransition={this._configureTransition}
        navigation={this.props.navigation}
        render={this._render}
        onTransitionStart={() => console.log('Start')}
        onTransitionEnd={() => console.log('End')}
      />
    );
  }

  _render = () => {
    return (...);
  }
```

**Comment by joeyzhao0113** [comment]
I got the same issue. I use StackNavigator inside TabNavigator.

**Comment by tangentlin** [comment]
I ran into the issue, and I commented out `autoRehydrate()` in Redux's enhancers, and and I was able to get my app working again.  Not sure if this would take care of your issue.

**Comment by fhad-getmaple** [comment]
+1

**Comment by MrToph** [comment]
Same here

**Comment by shotay79** [comment]
same here

**Comment by wangqianjun** [comment]
How can i fix ?

**Comment by lintonye** [comment]
The `navigation` prop received by a "screen" in a StackNavigator is different from the `navigation` prop that the Transitioner expects. See here https://github.com/react-community/react-navigation/blob/master/src/views/CardStack.js#L152

**Comment by maKSiM89** [comment]
@lintonye , and what we should pass as navigation value?

**Comment by kotazi** [comment]
Same here

**Comment by kelset** [comment]
Pinging OP @Illuday since this issue is quite old and related to an old version of the lib (and the introduction changed a bit since then). If no answer I'll close in 7 days.

**Comment by kelset** [comment]
Hi there @Illuday ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue (especially if it's a bug report) please open a new issue that uses the new Issue Template to provide some more details to help us solve it.
