### ISSUE TITLE
Nested navigators with the same screens

### ISSUE THREAD

**Issue by joshualcoffee** [react-community/react-navigation#752]
Hello and thank you for putting together this awesome library.  I have a question somewhat related to #362.  My app is controlled by redux and has 3 tabs.  Each tab is essentially the same  (jobs, opportunities, invoices) and will use the same screens.  When I first started the app I chose to use 4 different stores which would allow me to handle each tab independently.  This started to create issues as each store was a singleton and dispatching actions on a single store from another tab could lead to issues.  

When switching over to react-navigation this caused a circular dependency as I was including my store in some screens which would include the navigator.  So i started refactoring the app to use one store.  Now I have the scenario of managing the entire app state in a single store utilizing branches and Im curious what everyone feels best practices would be when dealing with nested navigators.  

Here are some things I have done to make this work.  
I have created a simple redux middleware that will get the active tab and append a key to the action.  
```javascript
export default function({ getState }){
  return (next) =>
    (action) => {
      const prevState = getState()
      const tabBar = getState().tabBar
      action.tabType = tabBar.routes[tabBar.index].routeName
      const returnValue = next(action);
      return returnValue;
    };
}
```
I also have a factory for my reducers that will append a string to each action that represents the tab.  

The part Im having trouble with is understand how we should handle the navigators.  From some basic test it looks like if I dispatch a navigate action and the screen exist in the router the navigator will navigate to the screen.  This caused inactive tabs to navigate to screens.  The best solution I came up with was to check the type in the reducer like so:
```javascript
jobsNav: (state,action) => {
      if(action.tabType == 'jobsNav' || typeof state == 'undefined'){ return jobsNav.router.getStateForAction(action,state) }
      return state
    }
```
I looked over the source and even searched through other issues that were related and found nothing on this topic.  I know everyone is busy working on libraries and projects so any input or direction would be great.

**Comment by WillyRamirez** [comment]
I have a similar issue, I have a "profile" screen which you can pretty much navigate to from every tab. How did you end up solving this?

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
