### ISSUE TITLE
Get rid of all console.* API calls to improve perf in dev mode

### ISSUE THREAD

**Issue by petermikitsh** [react-community/react-navigation#753]
The console.log statements in the source make developing with the [react-native-debugger tool](https://github.com/jhen0409/react-native-debugger), 
 (particularly those [here](https://github.com/react-community/react-navigation/blob/master/src/createNavigationContainer.js#L150-L154)) a less-than-ideal setup.

The console statements cause frames to be dropped. If maintainers are OK to taking out these statements, I'd be happy to make a PR.

**Comment by satya164** [comment]
Yes, please send a PR

**Comment by ninjaPixel** [comment]
+1 from me. FB advise against using console.log statements:

> Using console.log statements 
When running a bundled app, these statements can cause a big bottleneck in the JavaScript thread. This includes calls from debugging libraries such as redux-logger, so make sure to remove them before bundling.

https://facebook.github.io/react-native/docs/performance.html#using-console-log-statements

**Comment by grabbou** [comment]
It's been fixed. You can now turn off built-in logger, see https://github.com/react-community/react-navigation/commit/0f6b32868796a92a2a77a224b9140d6d5e02184e
