### ISSUE TITLE
NavigationPlayground stop install

### ISSUE THREAD

**Issue by zengzpi** [react-community/react-navigation#756]
I want to install  NavigationPlayground like this:

NavigationPlayground $ npm install
npm WARN deprecated exponent@13.1.0: The 'Exponent' project has beeen renamed to 'Expo'. This package is now named 'expo'.
npm WARN deprecated @exponent/vector-icons@4.0.0: The 'Exponent' project has been renamed to 'Expo'. This package is now named '@expo/vector-icons'.

then process stall.

**Comment by grabbou** [comment]
Example no longer depends on `expo`. Should be resolved.
