### ISSUE TITLE
Ios drawer renders weird

### ISSUE THREAD

**Issue by jeffreymendez1993** [react-community/react-navigation#757]
When using a custom drawer ios does not handle the constraints the same.

**Comment by temitope** [comment]
@jeffreymendez1993 i am experiencing a weird overhang where my drawer is spillin onto screen ui. how did you fix this?

**Comment by jeffreymendez1993** [comment]
@temitope   height: Dimensions.width() + 100,
      width: null,
      position:'absolute',
      left:0,
      right:0,
      bottom:0, 
      top:-7
for my image background style
