### ISSUE TITLE
navigate from top level component/navigator

### ISSUE THREAD

**Issue by ddeanto** [react-community/react-navigation#759]
I know a similar issue was already closed here https://github.com/react-community/react-navigation/issues/406 but I still have no idea how to do this. I have read the docs probably 10 times and looked through the source code for hours (I'm not really a javascript guy).

My specific use case: navigate user to a specific (nested) route when they open a push notification whose callback lives in my top level component/navigator. I can't figure out how to access the navigation prop from there. I suppose my push notification callbacks don't need to live at the highest level component, but I can't think of any other way to avoid its component from getting popped from the stack (which would kill the callbacks).

**Comment by ericvicenti** [comment]
You can grab a ref to your top-level navigator and then call `dispatch` on it.

```
<MyApp
  ref={app => {this.app = app;}}
/>
```

```
this.app.dispatch(NavigationActions.navigate(...));
```

**Comment by tinashe96** [comment]
I've tried to implement this but I get an error 
`undefined is not an object (evaluating '_this.props.navigation.state.params.conversation` when I try to navigate with 
`this.navigator && this.navigator.dispatch(NavigationActions.navigate({ routeName: 'Conversation' }));` or 
`this.navigator && this.navigator.dispatch({ type: 'Navigate', routeName: 'Conversation' });`

my navigation file looks like this...
`...
export default StackNavigator({
  TabNav: { screen: TabStack }, //this is tab navigator, the rest are stacks
  ItemDetails: { screen: ItemDetailsStack },
  Login: { screen: LoginStack },
  Conversation: { screen: ChatScreen },
}, { headerMode: 'none' }
);`

my top-level component...

`<Provider store={store}>
          <StatusBar barStyle='light-content' />
          <AppNavigation ref={nav => { this.navigator = nav; }} />
 </Provider>
`

**Comment by brentvatne** [comment]
https://reactnavigation.org/docs/navigating-without-navigation-prop.html
