### ISSUE TITLE
Pass properties to screen in TabNavigator

### ISSUE THREAD

**Issue by rendomnet** [react-community/react-navigation#760]
`const Tabs = TabNavigator({
  Info: {
    screen: Info,
  },`

My component "info" need properties for example **color**
<Info color="red">
How can I pass them?

**Comment by arvinsim** [comment]
[screenProps](https://reactnavigation.org/docs/navigators/tab) should work.

**Comment by rendomnet** [comment]
Can I pass prop for specific tab?

**Comment by arvinsim** [comment]
> Can I pass prop for specific tab?

None that I know of. I just pass everything in `screenProps` and get what I need.

**Comment by Gvade** [comment]
`const Tabs = TabNavigator({ 
    Info: { screen: (props) => <Info {...props} color="#fff" />}
});`

**Comment by dannyharding10** [comment]
Thanks @Gvade, this worked for me, but when I use  `{ screen: props => <Info {...props} color="#fff" />}` instead of simply `{ screen: Info }`, the component I'm using as the icon for that tab disappears.

The icon that disappears is the one I provide in the `Info` class under `navigationOptions.tabBarIcon`, like so:

`static navigationOptions = {
    tabBarLabel: 'MyLabel',
    tabBarIcon: () => (<Text size={24} color="white">SB</Text>) // This doesn't come through when I use your suggestion
  };`

**Comment by jpamarohorta** [comment]
I think I have the same issue. I have this architecture:

`// App.js

const HomeNavigation = StackNavigator({
  Home: { screen: Products },
  Product: { screen: Product }
});

const CategoryNavigation = StackNavigator({
  Categories: { screen: Categories },
  Category: { screen: Category },
  Product: { screen: Product }
});

const AppNavigation = TabNavigator({
  Home: { screen: HomeNavigation },
  Categories: { screen: CategoryNavigation },
}, { lazy: true });

class App extends Component {
  render(){
    return(
      <Provider store={store}>
        <AppNavigation/>
      </Provider>
    )
  }
}

AppRegistry.registerComponent('TTTismApp', () => App);`

I'm trying to add a `tabBarIcon` to each tab bar nested navigator and I don't want to explicitly define the icon in each screen `navigationOptions`  because some screens can be used in different navigators (like the `Products` one).

**Comment by RonnieRen** [comment]
you might need to move the navigationOptions out of that component and put it into the RouteConfigs

const Tabs = TabNavigator({
     Info:  { screen: props => <Info {...props} color="#fff" />,
              navigationOptions:(navigation, screenProps) => {
                        tabBarLabel: 'MyLabel',
                        tabBarIcon: () => (<Text size={24} color="white">SB</Text>)
                        }
            }})

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!

**Comment by sanjayholla94** [comment]
@dannyharding10 Did you find a solution to your issue?

**Comment by kingtross88** [comment]
how do you pass more than one prop to another screen. can someone show me an example. i'm only getting one prop at a time.

**Comment by JanithaR** [comment]
@kingtross88 `screenProps={{ details: this.props.details, isEditing: this.state.isEditing }}`

**Comment by esipavicius** [comment]
Here example how I did it with: DrawerNavigator -> StackNavigator -> TabNavigator and I get all props navigating from HomeScreen to tab

`
class Home2Screen extends React.Component {
  render() {
    console.log(this.props.navigation.state);
    return (
      <View>
      </View>
    );
  }
}

class SettingsScreen extends React.Component {
  render() {
    console.log(this.props.navigation.state);
    return (
      <View>
      </View>
    );
  }
}

const tab =  TabNavigator(
  {
    Home2: { screen: Home2Screen },
    Settings: { screen: SettingsScreen },
  },
  {}
);




class HomeScreen extends React.Component {
 goToTab() {
      navigate('Tab', {
        carData: {some: 'data'},
      });
}

  render() {
    return (
      <View>
... onPress={() => { this.goToTab() }} ...
      </View>
    );
  }
}

const HomeNavigator = StackNavigator({
    Home: {
        screen: HomeScreen,
    },
    Tab: {
      screen: tab,
    },
}, {
    mode: Platform.OS === 'ios' ? 'modal' : 'card',
});

const HomeNavigationDrawer = DrawerNavigator({
    HomePage: {
        screen: HomeNavigator,
    },
}, {
    contentComponent: SideMenu,
    drawerOpenRoute: 'DrawerOpen',
    drawerCloseRoute: 'DrawerClose',
    drawerToggleRoute: 'DrawerToggle',
    drawerWidth: 300,
});

export default HomeNavigationDrawer;
`

**Comment by i2chris** [comment]
@esipavicius   Strange.  I'm doing exactly the same thing with no luck

**Comment by esipavicius** [comment]
If you Can paste your code or give link i will look tomorow. Right now to me is 04hours. Maybe you forgot something or Maybe I to write something.

IT is important to this do not wrap screens to stack navigator which including to tab navigator. Maybe you Can use navigationAction setState or setParams with params and navigator key. When You Can dispatche it. And automaticaly changes state with params to which scren you dispatched.

**Comment by SandeshVakale** [comment]
This is my solution for passing more than one props through `screenProps`. The example is working for me.

`import React, { Component } from 'react'
import { TabNavigator, TabBarTop } from 'react-navigation'
import Icon from 'react-native-vector-icons/FontAwesome'
import DrawerNews from './Drawer/DrawerNews'
import DrawerFavorites from './Drawer/DrawerFavorites'
import FavoritesActions from '../Redux/FavoritesRedux'
import {connect} from 'react-redux'

export class DrawerNewsFavorites extends Component {
  render () {
    const params = {
      drawerMethods: this.props.drawerMethods,
      removeFavorite: this.props.removeFavorite
    }
    return (<TabScreen screenProps={params} />)
  }
}

const TabScreen = TabNavigator({
  Favoris: { screen: props => <DrawerFavorites {...props} /> },
  Actualites: { screen: props => <DrawerNews {...props} /> }
},
  {
    navigationOptions: ({ navigation }) => ({
      tabBarIcon: ({ focused, tintColor }) => {
        const { routeName } = navigation.state
        let iconName = (routeName === 'Actualites') ? 'comments' : 'star'
        // let labelName = (routeName === 'Actualites') ? 'Actualités' : 'Favoris'
        // You can return any component that you like here! We usually use an
        // icon component from react-native-vector-icons
        return <Icon name={iconName} size={25} color={tintColor} />
      }
    }),
    tabBarOptions: {
      style: {height: 64,
        backgroundColor: '#0080A0',
        borderTopColor: '#D3D3D3'},
      activeTintColor: 'white',
      labelStyle: {
        fontSize: 16,
        fontWeight: 'bold',
        backgroundColor: 'transparent'
      },
      showIcon: true,
      indicatorStyle: {
        backgroundColor: 'yellow'
      }
    },
    tabBarComponent: TabBarTop,
    tabBarPosition: 'top',
    animationEnabled: true,
    swipeEnabled: true
  }
)

const mapDispatchToProps = (dispatch) => {
  return {
    removeFavorite: (id) => dispatch(FavoritesActions.removeFavorite(id))
  }
}

export default connect(null, mapDispatchToProps)(DrawerNewsFavorites)
`

**Comment by usman1579** [comment]
i have a problem i am passing parameter from one screen to tab screen but its not getting the value from previous screen my code is given below.. 
relevant code.
// first screen code   .......   
  this.props.navigation.navigate('profile', { rootuser : '48' }


//second screen get code ....   
class Profile extends Component { 
  render() {
   const { navigation } = this.props; 
  var rootuser = navigation.getParam('rootuser',' ');
    return (
      <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
        <Text>
        Profile!
        </Text>
        <Text>
        rootuser:{JSON.stringify(rootuser)}
        </Text>
        
      </View>
    );
  }
}


export default createMaterialTopTabNavigator({
  Maps: Main,
  Settings: SettingsScreen,
  profile:Profile,
});

**Comment by ryanjayford** [comment]
How about passing of screenProps width to tabBarOptions scrollEnabled?

export default Tabs extends React.Component {
...
...
render() {
return (
<AppTopTabNavigator screenProps = {{navigation: this.props.navigation, screenWidth:
this.state.dimensions.width }} />
)
}
...

const AppTopTabNavigator = createMaterialTopTabNavigator
(
{ New: NewScreen ...
...
},
{
initialRouteName: 'New',
tabBarOptions: {
scrollEnabled: ( {screenProps.screenWidth value here} < 412),
...

My condition is to check if screen width is less than 412 then scrollEnabled: true (for phone portrait)
if not scrollEnabled: false (for phone landscape /tablets 7" up )

My srceenWidth already changing when you rotate device, I just need to set the condition to scrollEnabled.

Thanks in Advance!

**Comment by gjae** [comment]
> How about passing of screenProps width to tabBarOptions scrollEnabled?
> 
> export default Tabs extends React.Component {
> ...
> ...
> render() {
> return (
> <AppTopTabNavigator screenProps = {{navigation: this.props.navigation, screenWidth:
> this.state.dimensions.width }} />
> )
> }
> ...
> 
> const AppTopTabNavigator = createMaterialTopTabNavigator
> (
> { New: NewScreen ...
> ...
> },
> {
> initialRouteName: 'New',
> tabBarOptions: {
> scrollEnabled: ( {screenProps.screenWidth value here} < 412),
> ...
> 
> My condition is to check if screen width is less than 412 then scrollEnabled: true (for phone portrait)
> if not scrollEnabled: false (for phone landscape /tablets 7" up )
> 
> My srceenWidth already changing when you rotate device, I just need to set the condition to scrollEnabled.
> 
> Thanks in Advance!

This work for me!!!

**Comment by jasan-s** [comment]
Hey guys is `screenProps` not the way to pass down props in V3?

**Comment by JanithaR** [comment]
> Hey guys is `screenProps` not the way to pass down props in V3?

I believe it's no longer encouraged to put navigation such as TabNavigator nested within a component. I'm not quite sure how to handle such cases gracefully in V3. I wanted to upgrade from V1 to V3 recently and gave up on the upgrade since I couldn't find enough info on what to do with the nested navigators I have.

**Comment by avlisesac** [comment]
Is there any news on how to pass props to a screen in a tabnavigator with newer versions of react navigation? I'm trying to get the state from my main App down to a screen in a stack in a tab and I am having absolutely no luck.

**Comment by Sapkotaanish** [comment]
@avlisesac This job is easier in newer versions of react native.

In **App.js** : 
`<Tab.Screen
          name="UserScreen"
          options={{
            tabBarLabel: 'Track',
          }} >  {props => <UserScreen userInfo={this.state.name} />}
</Tab.Screen>`

In **UserScreen.js** : 
`<Text>{this.props.userInfo}</Text>`

It will send name state of App.js to UserScreen.js.
