### ISSUE TITLE
Component in Scene does not update on state change

### ISSUE THREAD

**Issue by markusguenther** [react-community/react-navigation#761]
Hello,

I have an component that updates the image dimensions on the chnage of the rotation. In a Scene within the TabNavigation it works fine.

But I nested a TabNavigation and a StackNavigation and within the StackNavigation the states changes but the Scene doesn`t update. Only when I am going back and open the Scene again the images rendered in the right dimensions.

But as I metioned ... when i debug the state and the image dimensions then the values changes but you don`t see the change.

Is there a way to trigger the rerender of a scene?

**Comment by ericvicenti** [comment]
Can you post a simplified example snippet that demonstrates the bug?

**Comment by markusguenther** [comment]
I will try to provide an example and hope that the error also occurs ;)

**Comment by markusguenther** [comment]
I created a app that uses my components ... it is a bit hacky because the original app uses redux and redux saga and so I throw out all the related things ...

But in the example it is also happens that the orientation change does not effect a rerender.

Steps to reproduce:
1. clone https://github.com/markusguenther/react-native-impulse-example and install all dependencies with yarn install
2. go to the list view in portrait mode
3. open the item
4. rotate the phone and the image in the box at the bottom does not not fill the width of the box
5. go back to the list and reopen the item
6. now the box should have a image over the full with

Hope that helps. I am just starting with everything. Not sure if it is just my fault.

**Comment by markusguenther** [comment]
@ericvicenti Is there something that i can provide? I am not sure if I am good enough to help, but will try if you have a hint.

**Comment by spencercarli** [comment]
Hi! Since this issue has been quiet for a while I'm going to go ahead and close it. If the issue persists in the latest version of React Navigation please re-open!
