### ISSUE TITLE
DrawerNavigator top section hides on custom header after using elevation  

### ISSUE THREAD

**Issue by aayushcoder** [react-community/react-navigation#762]
I use custom header.. I'm having following issues when i set elevation to custom header..

When `elevation:  0`
[![Screenshot_2017-03-21-16-15-47.png](https://s17.postimg.org/gc1tpdpqn/Screenshot_2017_03_21_16_15_47.png)](https://postimg.org/image/xpc448l1n/)

when `elevation: > 0 `
[![Screenshot_2017-03-21-16-17-58.png](https://s13.postimg.org/glfflptxz/Screenshot_2017_03_21_16_17_58.png)](https://postimg.org/image/w6wr5o5w3/)

**Comment by aayushcoder** [comment]
@ericvicenti

**Comment by aayushcoder** [comment]
@ericvicenti any solution here ??

**Comment by aayushcoder** [comment]
Set `backgroundColor` to any to remove this effect :)

**Comment by spencercarli** [comment]
Hi! In an effort to reduce the number of open issues I'm closing question-type issues that would be a better for the [react-navigation tag on StackOverflow](https://stackoverflow.com/questions/tagged/react-navigation). This is nothing personal, merely trying to get the # of issues to a more manageable level. If you think this issue should be re-opened please let me know. Thanks!
