### ISSUE TITLE
Performances differences DrawerNavigator vs using DrawerLayoutAndroid directly

### ISSUE THREAD

**Issue by ferrannp** [react-community/react-navigation#763]
I hope it will be noticeable in the gifs but there are noticeable differences between `DrawerNavigator` and using `DrawerLayoutAndroid` directly. With `DrawerNavigator`, it does not seem that fluid. Specially when swiping fast to close it, using `DrawerLayoutAndroid` closes much faster (as expected).

I also noticed that in `DrawerNavigator`, more or less 50% of the times, when I click outside of the drawer it does not response (when it should close).

I know that `DrawerNavigator` uses `DrawerLayoutAndroid` under the hood so not sure what might be causing this issue.

Using **DrawerLayoutAndroid** directly:

![drawer-direct](https://cloud.githubusercontent.com/assets/774577/24144080/3a540f62-0e2c-11e7-89a8-3e66888d41c2.gif)

Using **DrawerNavigator**:

![drawer-navigation](https://cloud.githubusercontent.com/assets/774577/24144361/3b5eff74-0e2d-11e7-9a89-7c944cff16ba.gif)

**Comment by stoffern** [comment]
@ferrannp good catch! 
I have the same problem, and think i have found the problem.

It seems like `react-native-drawer-layout-polyfill` returns the polyfill no matter if you are on android or not.
Overriding the component here with `DrawerLayoutAndroid` did fix the issue. 
https://github.com/react-community/react-navigation/blob/master/src/views/Drawer/DrawerView.js#L127-L145

Digging deeper to see if i can find out why it fails..

**Comment by vonovak** [comment]
this is no longer an issue, I think

**Comment by stoffern** [comment]
can confirm it is fixed.

**Comment by kelset** [comment]
This is fixed since PR #2568.

**Comment by stoffern** [comment]
I am still experiencing this issue, any others doing that?
