### ISSUE TITLE
How to enable header with DrawerNavigator?

### ISSUE THREAD

**Issue by alreadysabbir** [react-community/react-navigation#764]
I tried `header`  option in `navigationOptions` for my screen. Doesn't working with drawer navigation. I couldn't find an example for drawer navigation with Header.

Is header only for StackNavigator?

**Comment by ericvicenti** [comment]
The header is only for StackNavigator. If you have a minute to help clarify this in the docs, it would be greatly appreciated!

**Comment by gabriel-TheCode** [comment]
Really ?? 🤨🤨🤨
