### ISSUE TITLE
how to add badge or text to tabbar.

### ISSUE THREAD

**Issue by cbjs** [react-community/react-navigation#766]
I can't figure out a way to do it.

like count of unread messages, which stored in redux state.

<img width="335" alt="screen shot 2017-03-21 at 11 09 03 pm" src="https://cloud.githubusercontent.com/assets/1215843/24154227/8cf55b04-0e8b-11e7-8ce5-30aa00527824.png">

**Comment by sexykodo** [comment]
you can just pass a connected component as icon

`Notifications: {
    screen: NotificationScreen,
    navigationOptions: {
      tabBar: (state, acc) => ({
        icon: ({ tintColor, focused }) => (
          <BadgeTabIcon
            iconName="notification"
            size={26}
            selected={focused}
          />
        ),
        visible: (acc && acc.visible !== 'undefined') ? acc.visible : true,
      }),
    },
  },`

where

`
export default connect(state => ({
  notificationCount: state.notifications.count,
}))(({ dispatch, nav }) => (
  <View>
    <TabIcon {...props} />
    {
      props.notificationCount > 0 ?
        <View style={{ position: 'absolute', right: 10, top: 5, backgroundColor: 'red', borderRadius: 9, width: 18, height: 18, justifyContent: 'center', alignItems: 'center' }}>
          <Text style={{ color: 'white' }}>{props.notificationCount}</Text>
        </View> : null
    }
  </View>
));
`

**Comment by cbjs** [comment]
@sexykodo thanks~~

**Comment by mfclarke** [comment]
Still a noob so forgive the ignorance, but is there a non-redux way to do this?

**Comment by niocncn** [comment]
@mfclarke use mobX

**Comment by mfclarke** [comment]
@niocncn I should have said "is there an out of the box way of doing this?" I don't want to adopt a state management lib just because I can't set a badge on a tab. But thanks for the answer anyways.

What I was missing was using `navigation.setParams`, which sets params on the `state` object that you have access to in `navigationOptions`.

**Comment by AlanFoster** [comment]
Cross-referencing a duplicate/similar question https://github.com/react-community/react-navigation/issues/859

**Comment by beausmith** [comment]
Code snippets from another sample implementation…

Set `screenProps` where the component is rendered. _Static value used for simplicity of example._

```js
<App screenProps={{ unreadMessagesCount: 8 }} />
```

Using [react-native-icon-badge](https://github.com/yanqiw/react-native-icon-badge) with icons from [react-native-vector-icons](https://github.com/oblador/react-native-vector-icons), read `screenProps` in `navigationOptions` to define a `tabBarIcon` with a badge:

```js
const App = TabNavigator({
  Main: {
    screen: Main,
    navigationOptions: {
      tabBarIcon: ({tintColor}) => <Icon name='book' size={22} color={tintColor} />
    }
  },
  Profile: {
    screen: ProviderStack,
    navigationOptions: ({ screenProps }) => ({
      tabBarIcon: ({tintColor}) =>
        <IconBadge
          MainElement={<Icon name='user-circle' size={22} color={tintColor} />}
          BadgeElement={<Text style={{ color: 'white' }}>{screenProps.unreadMessagesCount}</Text>}
          Hidden={screenProps.unreadMessagesCount === 0}
        />
    })
  }
})
```

**Comment by hansfpc** [comment]
Niceeeee!

**Comment by Stophface** [comment]
@beausmith that simply overlays a red circle over the icon from react-native-vector-icons. The problem is that the circle gets cut off, as soon as it passes the bounds of the chosen icon from react-native-vector-icons.

**Comment by alihamza** [comment]
@mfclarke did you find any solution?

**Comment by reyhaan** [comment]
`iconStyle: { width: 70 }`

@alihamza  Add this to your tab config, play with width value to make your badge visible.

**Comment by beausmith** [comment]
@reyhaan Yup! 

@Stophface Sorry for the late reply, but use styles to adjust the icon styles to solve the overflow hidden issue.

**Comment by lucasleelz** [comment]
I like this

**Comment by brunoandradebr** [comment]
For those who wanna keep tab bar height as before @reyhaan solution, define a paddingVertical to tabStyle : 

`tabStyle: {
                justifyContent: 'center',
                alignItems: 'center',
                paddingVertical: 5
            },`

**Comment by Aung-Myint-Thein** [comment]
I am still trying to show the notification count stored in Redux in Tab navigation and still not successful.  @maurovisintin 's codes show error as of now. Does anyone of you have sample codes that can show? :) Would appreciate a lot.

Currently, I define my routers in a file called router where all stack and tab navigators are created. Thanks.

**Comment by Aung-Myint-Thein** [comment]
I managed to get it by using following codes:

Added a component in router as @maurovisintin suggested.

```
//router
Notification: {
      screen: NotificationStack,
      navigationOptions: {
        tabBarLabel: "Notification",
        tabBarIcon: ({ tintColor }) => (
          <View >
            <Icon type="material" name="notifications" color={tintColor} />
            <NotificationTabBarIcon />
          </View>
        )...
```

Then created a new component which is connected to redux.

```
// NotificationTabBarIcon.js

import React from "react";
import {
  Container,
  Content,
  Text,
  View
} from "native-base";
import { connect } from "react-redux";

const NotiTabBarIcon = props => (
  props.notificationCount > 0 ?
 
   <Text 
               style={{color: '#FF0000',
                       position:'absolute',
                       top:1,
                       right:1,
                       margin: -1,
                       minWidth:13,
                       height:13,
                       borderRadius:7,
                       alignItems: 'center',
                       justifyContent: 'center',
                       backgroundColor: '#FF0000', 
                       textAlign: "center",  
                       fontSize: 9 }}>{props.notificationCount}</Text>
  : null
);

export default connect(
  (state) => ({ 
    notificationCount: state.notifications.notificationCount
  })
)(NotiTabBarIcon);
```

Please let me know if you have any problems with the codes :) More than happy to help.

**Comment by myunusss** [comment]
> Code snippets from another sample implementation…
> 
> Set `screenProps` where the component is rendered. _Static value used for simplicity of example._
> 
> ```js
> <App screenProps={{ unreadMessagesCount: 8 }} />
> ```
> 
> Using [react-native-icon-badge](https://github.com/yanqiw/react-native-icon-badge) with icons from [react-native-vector-icons](https://github.com/oblador/react-native-vector-icons), read `screenProps` in `navigationOptions` to define a `tabBarIcon` with a badge:
> 
> ```js
> const App = TabNavigator({
>   Main: {
>     screen: Main,
>     navigationOptions: {
>       tabBarIcon: ({tintColor}) => <Icon name='book' size={22} color={tintColor} />
>     }
>   },
>   Profile: {
>     screen: ProviderStack,
>     navigationOptions: ({ screenProps }) => ({
>       tabBarIcon: ({tintColor}) =>
>         <IconBadge
>           MainElement={<Icon name='user-circle' size={22} color={tintColor} />}
>           BadgeElement={<Text style={{ color: 'white' }}>{screenProps.unreadMessagesCount}</Text>}
>           Hidden={screenProps.unreadMessagesCount === 0}
>         />
>     })
>   }
> })
> ```
> 
> **Update:** I've since replaced [react-native-icon-badge](https://github.com/yanqiw/react-native-icon-badge) with my own code because of how simple the code is to DIY. 😄

Hi @beausmith ,
How can i change value **unreadMessagesCount** without redux ?

thx

**Comment by myunusss** [comment]
@beausmith 😉 thx. But i got problem when update the state.

Here is my code for Tab
`const Tabs = createBottomTabNavigator({
    Homepage: {
        screen: Homepage,
    },

   NextTab: {
        screen: NextTab,
        navigationOptions: {
            tabBarIcon: ({focused, tintColor}) =>  {
                let iconSource;
                iconSource = focused ? require('../asset/icon/tab.png') : require('../asset/icon/tab-outline.png');

                return <BadgeWithIcon icon = {iconSource} />
            }
        }
    },
});`

and my BadgeWithIcon

`import React, { Component } from 'react';
import { Text, Image, View } from 'react-native';
import { withNavigation } from 'react-navigation';
import connectApi from '../utils/GetDataAPI';

class Notification extends Component{
    constructor(props){
        super(props);
        this.state = {
            count: 0,
        }
    }

    componentDidMount(){
        this.props.navigation.addListener('willFocus', this._fetchCountBadge)
    }

    _fetchCountBadge = async () => {
        connectApi.item(URL)
        .then(number => {
                this.setState({count : number})
        })
        .catch(error => {
            console.error(error)
        })
    }

    render(){
        const { count } = this.state;
        return(
            <View style={styles.viewStyle}>
                <Image style={styles.imageStyle} source={this.props.icon}/>
                    { count > 0 ?
                        <View style={ styles.myStyle }>
                            <Text style={{padding: 2, fontSize: 12, color: '#fff'}}>{count}</Text>
                        </View> : null }
            </View>   
        )
    }
}

export default withNavigation(Notification);`

I should **update** badge number when add or remove value from tab **NextTab**

Thx for help

**Comment by beausmith** [comment]
@myunusss - Sorry, I don't have time to provide more in-depth assistance. Keep troubleshooting and confirming assumptions about your code. You’ll figure it out!

**Comment by AurangsEmpire** [comment]
> you can just pass a connected component as icon
> 
> ```
>     screen: NotificationScreen,
>     navigationOptions: {
>       tabBar: (state, acc) => ({
>         icon: ({ tintColor, focused }) => (
>           <BadgeTabIcon
>             iconName="notification"
>             size={26}
>             selected={focused}
>           />
>         ),
>         visible: (acc && acc.visible !== 'undefined') ? acc.visible : true,
>       }),
>     },
>   },
> ```
> 
> where
> 
> ```
> export default connect(state => ({
>   notificationCount: state.notifications.count,
> }))(({ dispatch, nav }) => (
>   <View>
>     <TabIcon {...props} />
>     {
>       props.notificationCount > 0 ?
>         <View style={{ position: 'absolute', right: 10, top: 5, backgroundColor: 'red', borderRadius: 9, width: 18, height: 18, justifyContent: 'center', alignItems: 'center' }}>
>           <Text style={{ color: 'white' }}>{props.notificationCount}</Text>
>         </View> : null
>     }
>   </View>
> ));
> ```

how can I send my props from my main screen, item count is coming from API response I cannot run API in routes.js , any help?

**Comment by jovanialferez** [comment]
@AurangsEmpire you dont need to worry about the props as that component is `connect`ed to the redux store. I would assume you have a reducer that would update that.

**Comment by EmanoelJohannes** [comment]
> @AurangsEmpire you dont need to worry about the props as that component is `connect`ed to the redux store. I would assume you have a reducer that would update that.

I have a reducer called: UPDATE_NOTIFICATIONS, how can i use then with the solution of AurangsEmpire?

**Comment by jackimatin** [comment]
it does not update with redux....
any solution?
