### ISSUE TITLE
unmount components when navigating away

### ISSUE THREAD

**Issue by TheOne20001** [react-community/react-navigation#769]
Hey, I have an app where I use stack navigator to move from page to page many times. this leaves dozens of items in the stack, all of which are active all the time even when most of them are unseen. unfortunately while this speed up going back, it's very heavy on RAM memory. I was wondering if anyone has any suggestions, or whether there is a way to make the stack lazy load similar to the tab navigator?

**Comment by joonhocho** [comment]
I also noticed that when I have a camera feature turned on on one tab and move to another tab, camera is still running or at least torch (flash) mode is still on as I can see camera flash is left turned on.

**Comment by TheOne20001** [comment]
we did look at the discussion in thread 51, but until that is implemented, we decided to make is so a component notes id stack index, and if the index does not match then it is not visible. This does not unmount, but at least lets the component know that whether to render, and whether it may need to do some shutdown procedures.

**Comment by ansonyao** [comment]
Hey, is there any suggestions on the how to reduce the memory usage or is it possible to do it at all? We have many pages in the stacknavigator and the memory usage is high when use opened many pages. Seems the hidden pages are still using up the memory. Do you have any suggestions which I can do to optimize the memory usage? I have checked thread 51 but it is about tabnavigator. I know the lazyload trick but I am not sure how it is related to the stacknavigator.

**Comment by clementino36** [comment]
Hey can we reopen this ? I have the same issue, the more screens i navigate to, the slower the app gets. If i don't kill the app and open it again, the app is fast becoming impossible to use because of how slow it gets.

**Comment by mgiridhar** [comment]
I am facing memory leak issue when navigating back from a screen which has WebView component that embeds a video. Is there a way to unmount the component?

**Comment by brentvatne** [comment]
please create a new issue and follow the template @clementino36 / @mgiridhar
