### ISSUE TITLE
Running the examples on Windows.

### ISSUE THREAD

**Issue by Steviey** [react-community/react-navigation#77]
I managed to make the install scripts cross platform **(PR will follow**).

Now when I try this on Win 7...

https://github.com/react-community/react-navigation/blob/master/docs/guides/Contributors.md#1-run-the-native-playground

..It breaks at 'npm run run-playground-android' with the message:

'Looks like you installed react-native-globally. maybe you meant react-native-cli?
To fix the issue. run: 
npm uninstall -g react-native
npm install -g react-native-cli'

If I do so and try this: 'react-native-cli run-android' in folder react-navigation, I get:

react-native-cli is not recognized as an internal or external command operable program or batch file.

ANDROID_HOME is set correctly.

What now? Any suggestions?

**Comment by satya164** [comment]
After installing `npm install -g react-native-cli`, you've to run `react-native run-android`, not `react-native-cli run-android`

**Comment by Steviey** [comment]
How could this work without any Android folder in the project folder?

**Comment by satya164** [comment]
where are you running `react-native run-android`? you can either run `react-native run-playground-ios` in the project folder or run `react-native run-android` in `examples/Playground` as in the doc you linked to

**Comment by Steviey** [comment]
There we go. Wow what a journey. Thank you.
Anyways: 
If I say A)
'react-native run-android' in examples/NavigationPlayground I get the app running.
If I say B)
react-native run-playground-android in root, I get the error 'Unrecognized command run-playground-android'

**Comment by satya164** [comment]
sorry, my mistake. it's `npm run run-playground-ios`

**Comment by Steviey** [comment]
I see, 
If I run: npm run run-playground-android
I get 'Looks like you installed react-native-globally. maybe you meant react-native-cli?
To fix the issue. run:
npm uninstall -g react-native
npm install -g react-native-cli'

I have react-native-cli globally installed and react-native globally uninstalled.
This seems to be a bug.

**Comment by satya164** [comment]
yes, it's saying that you shouldn't have react-native globally installed

> Looks like you installed react-native-globally. maybe you meant react-native-cli

**Comment by Steviey** [comment]
Maybe this should be bug filed in rep. react-native. Or what would you think where it is located?

**Comment by Steviey** [comment]
Complete Windows Solution:

https://steviey.github.io/win-react-navigation/
