### ISSUE TITLE
make a specific screen a modal?

### ISSUE THREAD

**Issue by jeffreymendez1993** [react-community/react-navigation#770]
How can I make a specific route inside a StackNavigator to open as a modal.

**Comment by jeffreymendez1993** [comment]
<img width="380" alt="screen shot 2017-03-21 at 3 22 52 pm" src="https://cloud.githubusercontent.com/assets/8095978/24166635/49c1be22-0e4a-11e7-8ae0-14279c251c1f.png">

**Comment by travisday** [comment]
I am having the same issue...REKT

**Comment by ericvicenti** [comment]
If the modal is supposed to cover the navigation bar, then you probably want to create a new modal navigator outside the inner stack navigator.

**Comment by aimak** [comment]
This looks like an issue I'm having as well https://github.com/react-community/react-navigation/issues/690

**Comment by jeffreymendez1993** [comment]
@ericvicenti  That does not work.

**Comment by nihgwu** [comment]
@jeffreymendez1993 That does work, see https://github.com/react-community/react-navigation/issues/232#issuecomment-286973451 or my demo https://github.com/nihgwu/react-native-dva-starter#advance

**Comment by RichardLindhout** [comment]
@nihgwu What if I want the login modal not gesture enabled and another modal true?

**Comment by nihgwu** [comment]
@RichardLindhout `gesturesEnabled` is a `navigationOptions` for screen too, so you can turn on that in `StackNavigator` but turn it off in specific screens.

But IMO the gesture capture is not good enough in modal mode, it's to easy to be captured even in a `ScrollView`, so I prefer to turn it off.

**Comment by RichardLindhout** [comment]
Thank you, yes I did see that probably wil disable that.

**Comment by jeffreymendez1993** [comment]
@nihgwu  that does not work.

**Comment by jeffreymendez1993** [comment]
Found a workaround. You can just use react-natives built in Modal component and render the scene when you call that specific route. If you use a top-level-navigator this can be achieved simply. Closing the issue for now.

**Comment by travisday** [comment]
@jeffreymendez1993 Is there an example of this somewhere?

**Comment by RichardLindhout** [comment]
@jeffreymendez1993 It's probably not a good idea to use the Modal from react-native since there are multiple listeners on the back button on Android etc. Maybe it will result in strange behaviour.
``` 
import {
  StackNavigator as stackNavigator,
  // TabNavigator as tabNavigator,
  // TabView as tabView,

} from 'react-navigation'


import Login from './routes/Login'
import Home from './routes/Home'
import { enhance } from './navigation'
// import Account from './routes/Account'
// import Detail from './routes/Detail'
import EditTimer from './routes/EditTimer'

// const HomeNavigator = tabNavigator(
//   {
//     Home: { screen: Home },
//     Account: { screen: Account },
//   },
//   {
//
//     tabBarComponent: tabView.TabBarBottom,
//     tabBarPosition: 'bottom',
//     swipeEnabled: false,
//     animationEnabled: true,
//     lazyLoad: true,
//   }
// )
const MainNavigator = enhance(stackNavigator)(
  {
    Home: { screen: Home },
    EditTimer: { screen: EditTimer },
  },
  {
    cardStyle: {
      opacity: 1,
    },
    navigationOptions: {
      header: {
        tintColor: 'rgba(255,255,255,0.8)',
        titleStyle: {
          color: 'rgba(255,255,255,0.8)',
          fontWeight: '400',
        },
        style: {
          backgroundColor: 'rgba(69,37,200,1)',
          shadowColor: 'rgba(69,37,200,1)',
          shadowOpacity: 1,
          shadowRadius: 3,
          shadowOffset: {
            height: 3,
            width: 0,
          },
        },
      },
    },
    headerMode: 'screen',
  }
)

const Router = stackNavigator(
  {
    Main: { screen: MainNavigator },
    Login: { screen: Login },
  },
  {
    headerMode: 'none',
    mode: 'modal',
    cardStyle: {
      opacity: 1,
    },
    navigationOptions: {
      cardStack: {
        gesturesEnabled: true,
      },
    },

  }
)


export default Router

```

**Comment by jeffreymendez1993** [comment]
Your example will not work for a nested route and if anything we can handle
the event listener appropriately on the scene using BackAndroid

**Comment by jeffreymendez1993** [comment]
If a modal scene is called with back android close the modal and return
false.

**Comment by jeffreymendez1993** [comment]
Will post a example in a bit

**Comment by jeffreymendez1993** [comment]
`import React, { Component } from 'react';
import { InitiationStack, DrawerStack } from './navigationConfiguration';
import { View, Modal, BackAndroid } from 'react-native';

import MyComponent from '../something/MyComponent';


export default class NavigationRouter extends Component {
  constructor(props) {
    super(props);
    this.state = {
      showModal: false
    };
    global.navigate = this.topLevelNavigate;
    global.goBack = this.topLevelNavigationPop;
  }
  componentDidMount() {
    BackAndroid.addEventListener('hardwareBackPress', this.handleBack);
  }
  componentWillUnmount() {
    BackAndroid.removeEventListener('hardwareBackPress', this.handleBack);
  }
  handleBack = () => {
    let popAction = true;
    if (this.state.showModal) {
      this.setState({showModal:false});
      popAction = false;
    }
    return popAction;
  }
  topLevelNavigate = (routeName, params) => {
    if (routeName === 'MyModal') {
      let Scene = <SomeComponent someProps={params.someParam}/>;
      this.updateModal(Scene);
    }

    this.navigator && this.navigator.dispatch({ type: 'Navigation/NAVIGATE', routeName, params });
  }
  topLevelNavigationPop = (key) => {
    // if the modal is visible and the pop action is called close the modal and exit the function
    if (this.state.showModal) {
      this.closeModal();
      return;
    }
    this.navigator && this.navigator.dispatch({ type: 'Navigation/BACK', key: key });
  }
  updateModal = (component) => {
    this.setState({showModal:true, modalComponent: component});
    return;
  }
  closeModal = () => {
    this.setState({showModal:false, component: null});
  }
  renderRouter() {
  let isLoggedIN = true;
    return isLoggedIN ?
     // return the correct router depending on if your user is logged in or not
      <DrawerStack ref={nav => { this.navigator = nav; }}/>
      : <InitiationStack ref={nav => { this.navigator = nav; }}/>;
  }
  render() {
    return (
      <View style={{flexGrow:1}}>
        {this.renderRouter()}
        <Modal
           animationType={'slide'}
           transparent={false}
           visible={this.state.showModal}>
           {this.state.modalComponent}
         </Modal>
      </View>
    );
  }
}

`

**Comment by ericvicenti** [comment]
I would advise against using the RN Modal, because the navigation system does not know how to interact with it.

Lets go ahead and track this issue in https://github.com/react-community/react-navigation/issues/707, which has a clearer description

**Comment by benevbright** [comment]
Guys. here is what you want.

And do like this when you want to go to modal and back.
```
        screenProps.modalNavigation.navigate('modalmain');
```

```
const _NavMain = StackNavigator({
    root:{ screen: MainScreen },
    stackdepth1:{screen: stackdepth1},
    stackdepth2:{screen: stackdepth2},
}
, {navigationOptions:whatever})

const _NavModalMain = StackNavigator({
    modalroot:{ screen: modalroot, navigationOptions:(props) => ({
        headerLeft:
            <TouchableOpacity onPress={() => {props.screenProps.modalNavigation.goBack()}}>
                <Text style={{color:'white', fontWeight:'bold', marginHorizontal:15}}>Close Modal</Text>
            </TouchableOpacity>
    })}
}
, {navigationOptions:whatever})

const Main = StackNavigator({
    stackmain:{ screen: ({navigation}) => <_NavMain screenProps={modalNavigation:navigation}/>  },
    modalmain:{ screen: ({navigation}) => <_NavModalMain screenProps= screenProps={modalNavigation:navigation}/> },
}
, {navigationOptions:whatever, headerMode:'none', mode:'modal'})
```

**Comment by benevbright** [comment]
Hi, @infostreams. Thanks for your comment.
But it's obsolete now. Passing `navigation` through `screenProps` is the anti-pattern now.

You don't have to pass it.
Just do `this.props.navigation.navigate('modalmain');` It would work.

But I don't know after v2 version released. 
Things are changed so quickly..
