### ISSUE TITLE
Can stack screen overlap Tab bar?

### ISSUE THREAD

**Issue by dzuncoi** [react-community/react-navigation#771]
I'm developing an app with my root navigation is a Tab bar, and in each tab there will be some stack screens, like below
- Tab 1
   --- Stack 1 - 1
   --- Stack 1 - 2
- Tab 2
   --- Stack 2 - 1
   --- Stack 2 - 2
etc

Now, is there anyway that some of my stack screens (for ex: Stack 1 - 1) will overlap the Tab bar, it means fullscreen stack? I've tried to style my screen as `bottom: -50, zIndex: 999` but it doesn't work.

**Comment by Ehesp** [comment]
Also having this issue. The Stack seems to just get nested within the Tabs.

**Comment by aimak** [comment]
you can set 
```
navigationOptions = {
  tabBar: {
    visible: false,
  },
}
```

on your Stack 1 - 1

**Comment by dzuncoi** [comment]
Oh thank you @aimak, I didn't think about setting tabBar inside stack :)

**Comment by Ehesp** [comment]
Doing @aimak's solution renders a blank Header and the content doesn't show :/

**Comment by dzuncoi** [comment]
I followed his solution and everything works perfectly. So maybe your problem is outside of this question's scope.

**Comment by Ehesp** [comment]
Hmm my apps initial setup is a stack navigator, first screen renders a tab
navigator and then renders a stack navigator. Will investigate more.

**Comment by goyan** [comment]
Correct syntax inside a StackNavigator seems to now be:

`navigationOptions: {
    tabBarVisible: false
}
`

**Comment by rcalabro** [comment]
can the header be hidden the same way?

**Comment by brentvatne** [comment]
see https://reactnavigation.org/docs/en/navigation-options-resolution.html
