### ISSUE TITLE
How to disable swipe on TabNavigator once init?

### ISSUE THREAD

**Issue by capsule5** [react-community/react-navigation#776]
At some point I need to disable swipe from a screen component. How to do so? Is it possible without re-rendering the navigator?

**Comment by jkongie** [comment]
The TabNavigator configuration has a `swipeEnabled` boolean option that you can set

**Comment by yekaterinaTRU** [comment]
Also wondering if there's an easy solution to enable/disable the swipeEnabled option on the fly.

**Comment by aknad** [comment]
@capsule5 
I've the same problem
Did you find a solution?

**Comment by jppereyra** [comment]
Same issue here, my use case is as follows:

- I have 3 tabs in my TabNavigator.
- One of them is a ListView in which the elements can be swiped in and out.
- The TabNavigator swipe interferes with the other swipes.

I'd like to deactivate it for that specific screen and even replace it with an "edge" swipe. I know this makes for funky UX, but we're trying to find a workable solution. Any ideas?

**Comment by mrbeann** [comment]
@jppereyra 
you can try `swipeEnabled: false`

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
