### ISSUE TITLE
Custom close button inside the header of StackNavigator?

### ISSUE THREAD

**Issue by DFelten** [react-community/react-navigation#777]
I've got a question about React Navigation and the `StackNavigator`. I would like to add a custom close button to the header, but I'm not sure how to do this. It's just possible for me to navigate to the screens, but not for example to go back or dispatch something. 

On my example the `navigationOptions` for the `HomeScreen` is working. The drawer opens and the `SettingsButton` navigates to the settings screen. But I've got problems with the `navigationOptions` of the `EntryScreen`. There I build a `CloseButton` to go back, but I need access to the navigation object. 

With `navigate` it's possible to navigate to other screens, but I need access to the parent object `navigation`. For example on the class for the drawer it's possible to get access through `props.navigation` (For example `props.navigation.navigate('Home')` or `props.navigation.goBack(null)`)

This is a part of my current code. Of course it's currently not working because of the missing access to `navigation`:

```
const Stack = StackNavigator({
  Home: {
    screen: HomeScreen,
    navigationOptions: {
      header: ({ navigate }) => ({
        left: <DrawerButton navigate={navigate} />,
        right: <SettingsButton navigate={navigate} />
      })
    }
  },
  Entry: {
    screen: EntryScreen,
    navigationOptions: {
      header: ({ navigation }) => ({
        right: <CloseButton navigate={navigation } />
      })
    }
  }
})

export const Drawer = DrawerNavigator({
  Home: {
    screen: Stack
  }},
  {
    contentComponent: HamburgerMenu
  }
)
```

These are the buttons:

```
export const CloseButton = (props) => {
  let testButton = <TouchableHighlight onPress={() => props.navigation.goBack(null)}>
    <Icon name='close' style={styles.headerButtonIcon} />
  </TouchableHighlight>
  return testButton 
}

export const SettingsButton = (props) => (
  <TouchableHighlight onPress={() => props.navigate('Settings')}>
    <Icon name='more-vert' style={styles.headerButtonIcon} />
  </TouchableHighlight>
)
```

Maybe someone is able to help me here. Thanks in advance!

**Comment by sigmazen** [comment]
Hi.  Funnily enough I just hit the same issue with a custom left Icon and wanting to goBack.
I ended up back to the RN Navigator page:   https://reactnavigation.org/docs/navigators/navigation-prop
All I did is put `goBack` in the header, thus:

      header: ({ goBack }) => ({
        right: ( <Icon name={'close'} onPress={ () => { goBack() } }  /> )
      })

**Comment by DFelten** [comment]
Oh man, thank you for the help! Logically, but not so simple.

**Comment by stantoncbradley** [comment]
@sigmazen I tried doing it like that and I'm getting "Objects are not valid as a React child (found: object with keys ({left}).`
 The docs say:
```
header 
React Element or a function that given HeaderProps returns a React Element, to display as a header. Setting to null hides header.
```
so sounds like we're expected to return a React element and not an object?

**Comment by jDeppen** [comment]
This worked for me
```
headerRight: ({ goBack }) => <Icon name={"close"} onPress={goBack} />
```
