### ISSUE TITLE
onNavigationStateChange Fired at Inconsistent Times

### ISSUE THREAD

**Issue by jcady** [react-community/react-navigation#778]
I have a TabNavigator set up with an `onNavigationStateChange` listener. If I manually click a tab, the listener fires with the new state when the tab animation completes and the navigator settles. If I call `props.navigation.navigate('route')`, the listener fires immediately and does not wait for the animation to complete.

I'm not sure which is desired behavior. But it should be noted with the former, I can prevent the `onNavigationStateChange` listener from firing by quickly clicking back and forth between tabs and not waiting for the animation to fully settle.

If this is actually intended behavior, what is the definitive method of getting a callback when the state has changed before and after the animation?

**Comment by brentvatne** [comment]
cc @ericvicenti

**Comment by grabbou** [comment]
I think this is solved in https://github.com/react-community/react-navigation/commit/0f6b32868796a92a2a77a224b9140d6d5e02184e that moved it to `setState` callback.

**Comment by spencercarli** [comment]
Hi! Since this issue has been quiet for a while I'm going to go ahead and close it. If the issue persists in the latest version of React Navigation please re-open!
