### ISSUE TITLE
Custom drawer component

### ISSUE THREAD

**Issue by TomiHiltunen** [react-community/react-navigation#78]
Is there a way to use custom drawer component instead of the default one? Does using custom drawer require creating a custom navigator?

**Comment by ericvicenti** [comment]
With the current API, the best option is to fork `DrawerNavigator.js` and modify it as you see fit.

**Comment by satya164** [comment]
You can only change drawer content with `contentComponent` option. Why do you need to change the drawer?

**Comment by TomiHiltunen** [comment]
My goal is to get the drawer menu to show any number of dynamic items and a couple of static buttons. The static items and buttons are rendered in different ways. The dynamic items all use same type of screen component with just different props. Static buttons would have their own screen components.

**Comment by satya164** [comment]
@TomiHiltunen looks like you should be able to that with `contentComponent`

**Comment by TomiHiltunen** [comment]
@satya164 how would you suggest adding the per-item config to the items in DrawerNavigator's config?

**Comment by satya164** [comment]
@TomiHiltunen what do you mean by per-item config? you can replace the whole view with your own component. so do as you need

**Comment by TomiHiltunen** [comment]
@satya164 I see, I misunderstood the purpose of contentComponent earlier. Looks like it will do the trick for me. Thanks!

**Comment by satya164** [comment]
Great!

**Comment by temitope** [comment]
@TomiHiltunen if you implemented this can you share your code here? I am curious to see an example of how in rendering the entire view we can still hook up the navigation correctly. thanks!

**Comment by TomiHiltunen** [comment]
Sorry about slow reaction. I dropped the drawer navigation for now in favor of different app structure. I noticed the update on your comment but here's the old component code anyways:

```
const DrawerMenuView = (props) => {
    const {
        myItems,
        navigation
    } = props;
    return (
        <View>
            {myItems.map((myItem) =>
                <MyItemLink
                    key={myItem.uuid}
                    myItem={myItem}
                    onPress={() => {
                        navigation.navigate("TheView", { "displayName": myItem.displayName });
                    }} />
            )}
        </View>
    );
};
```

There is another component wrapping this one with react-redux's `connect` component. I didn't paste it here as it serves no purpose regarding the navigation.

**Comment by anhtuank7c** [comment]
@TomiHiltunen 
Can you show me your `myItems array`?

**Comment by Jacse** [comment]
@anhtuank7c not @TomiHiltunen, but this is about what I did (some quick edits, haven't tested this exact code).

In my Navigation:

```
import Menu from '../../components/Menu';

const navs = [
  { label: 'Lektier', iconName: 'book', nav: 'Lektier' },
  { label: 'Fravær', iconName: 'book', nav: 'Fravaer' },
  { label: 'Indstillinger', iconName: 'cog', nav: 'Settings' },
];

let drawerNavigatorConfig = {
  contentComponent: ({ navigation }) => <Menu navigation={navigation} items={navs} />,
};

export default DrawerNavigator({
  Lektier: { screen: LektierScreen },
  Fravaer: { screen: FravaerScreen },
  Settings: { screen: SettingsScreen },
}, drawerNavigatorConfig);
```

`Menu component`:
```
const Menu = ({ navigation, items }) => {
  return (
    <View style={{ flex: 1 }}>
        <List>
          {
            navigation.state.routes.map((route, index) => {
              const focused = navigation.state.index === index;
              const item = items.find(it => it.nav === route.routeName);
              return (
                <MenuItem
                  key={index}
                  icon={item.icon}
                  onPress={() => navigation.navigate(item.nav)}
                  focused={focused}
                >
                  {item.label}
                </MenuItem>
              );
            })
          }
        </List>
    </View>
  );
};
```

Here I use a custom `MenuItem`-component, but you get the idea.
