### ISSUE TITLE
creating two sidemenu or drawers navigator

### ISSUE THREAD

**Issue by XeniousSoftware** [react-community/react-navigation#780]
Hi There

its basically questions not issue.

i have two question 

1) does the DrawerNavigator support two drawers at a time one from left and one from right?
2) when the drawer opens, can drawer push the content to left or right instead of overlaying it?

any help will be much appreciated.

**Comment by sigmazen** [comment]
Hi
I got this working firstly by creating a TabNavigator (which would trigger the drawers).  These would then invoke two StackNavigators which would in-turn trigger the DrawerNavigator.
A little convoluted so here's some example code (reading from bottom-up):

    export const DrawerLeft = DrawerNavigator({
      Inbox:       { screen: InboxScreen,      },
      Calendar:    { screen: CalendarScreen,   },
    });
    
    export const DrawerRight = DrawerNavigator({
      Profile:     { screen: Profile,          },
      Settings:    { screen: Settings,         },
    }, {
        drawerPosition: 'right',
    });
    
    export const EmailStack = StackNavigator({
      Email:       { screen: DrawerLeft,       },
    });
    
    export const OptionsStack = StackNavigator({
      Options:     { screen: DrawerRight,      },
    });
    
    
    // Tabs setup
    export const TabStack = TabNavigator({
      tabEmail:    { screen: EmailStack,       },
      tabOptions:  { screen: OptionsStack,     },
    });

**Comment by XeniousSoftware** [comment]
i tried this, but swiping from left opens the left drawer then closes it then opens the right drawer.
so left drawer never stays open.
so not sure if this solution will work?

**Comment by kevinold** [comment]
I setup a demo of the code above from @sigmazen in Expo Snack and I'm seeing the same issue with the drawers that @XeniousSoftware mentioned.

https://snack.expo.io/ry7lYempe

**Comment by flo-pereira** [comment]
https://github.com/react-community/react-navigation/pull/1757

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!

**Comment by spencercarli** [comment]
Whoops! This shouldn't be closed. On my radar.

**Comment by parthgandhi7** [comment]
Any updates on multiple drawer implementation ? I do want two drawers in my app but i am stuck on the above referenced issue . I would be happy to implement a workaround if that is possible . Please check the above mentioned issue and tell me if this has been implemented in react navigation or if any kind of work around is possible.

**Comment by hoscarcito** [comment]
There's actually a PR open waiting for a review, the #1803

**Comment by parthgandhi7** [comment]
Anyways, I implemented two drawers seperately. One with react navigation(or more specifically react-router-flux) and the other drawer (right drawer) on each page using seperate drawer component (eg, drawer from native base , react-native-drawer etc.).

**Comment by kelset** [comment]
PR got merged, we'll do a release soon-ish!
In the meantime, you can point to master.

**Comment by oojikoo** [comment]
for some people who hasn't found a solution for drawers on both sides.

I wasted so much time to get it working. 

I hope some may get hints from it.

```
import RightSideMenu from '~/RightSideMenu';
import LeftSideMenu from '~/LeftSideMenu';
import { .. } '~/screens'

const MainStack = StackNavigator(
  {
    
    Main: {
      screen: Main,
      navigationOptions: { header: null },
    },
    Screen1: {
      screen:  Screen1,
      navigationOptions: { header: null },
    },
  },
  {
    initialRouteName: 'Main',
    navigationOptions: {
      gesturesEnabled: false,
      headerStyle: {
        backgroundColor: '#fff',
        elevation: 0,
        shadowOpacity: 0,
      },
    },
  },
);

const MainDrawer = DrawerNavigator(
  {
    MainStack,
  },
  {
    initialRouteName: 'MainStack',
    drawerWidth: Dimensions.get('window').width,
    drawerPosition: 'left',
    contentComponent: props => <LeftSideMenu {...props} />,
    drawerOpenRoute: 'LeftSideMenu',
    drawerCloseRoute: 'LeftSideMenuClose',
    drawerToggleRoute: 'LeftSideMenuToggle',
  },
);

const RootRoute = DrawerNavigator(
  {
    MainDrawer: {
      screen: MainDrawer,
    },
  },
  {
    navigationOptions: {
      drawerLockMode: 'locked-closed',
    },
    drawerPosition: 'right',
    drawerWidth: Dimensions.get('window').width,
    contentComponent: props => <RightSideMenu {...props} />,
    drawerOpenRoute: 'RightSideMenu',
    drawerCloseRoute: 'RightSideMenuClose',
    drawerToggleRoute: 'RightSideMenuToggle',
  },
);

export default AppRoute;

```
The structure is 

but a problem is that I can't find how to pass props to contentComponent when 

this.props.navigation.navigate('RightSideMenu');

anyone?

**Comment by 337240552** [comment]
@oojikoo 

> but a problem is that I can't find how to pass props to contentComponent when

this.props.navigation.navigate('RightSideMenu');

anyone?

try this
`
        contentComponent: props => <GuildSlideBar {...props} />,
`
