### ISSUE TITLE
Can someone explain how this example in doc does not end up in infinite loop?

### ISSUE THREAD

**Issue by joonhocho** [react-community/react-navigation#781]
Looking at https://reactnavigation.org/docs/routers/#Custom-Navigation-Actions,

```javascript
MyApp.router = {
  ...MyApp.router,
  getStateForAction(action, state) {
    if (state && action.type === 'PushTwoProfiles') {
      const routes = [
        ...state.routes,
        {key: 'A', routeName: 'Profile', params: { name: action.name1 }},
        {key: 'B', routeName: 'Profile', params: { name: action.name2 }},
      ];
      return {
        ...state,
        routes,
        index: routes.length - 1,
      };
    }
    return MyApp.router.getStateForAction(action, state);
  },
};
```

To me it seems like `getStateForAction` is calling itself, thus infinite loop, when calling `return MyApp.router.getStateForAction(action, state);`, since `MyApp.route.getStateForAction` is overridden.

Should it be like so?
```javascript
const prevGetStateForAction = MyApp.router.getStateForAction;
...

MyApp.router = {
  ...MyApp.router,
  getStateForAction(action, state) {
    ...
    return prevGetStateForAction(action, state);
  },
};
```

Am I missing something?

**Comment by AlanFoster** [comment]
From an external perspective I'd agree with your conclusion; I assume the stack explodes when running the doc's example?

**Comment by felixus95** [comment]
Which is exactly what's happening. call stack exceeded.

Can someone please explain how to call custom Navigation Actions. I've spent several hours trying to figure it out, but couldn't figure it out.

**Comment by spencercarli** [comment]
Hi! Since this issue has been quiet for a while I'm going to go ahead and close it. If the issue persists in the latest version of React Navigation please re-open!
