### ISSUE TITLE
Cannot turn off animation for specific screens

### ISSUE THREAD

**Issue by huston007** [react-community/react-navigation#783]
Hello! I'm trying to migrate to react-navigation from old Navigator my ReactNative app.
There was such logic in Navigator that "reset" action was switching views without any animation. That is what I really need, but I cannot find out the way.

I tried to use [this kind of animation config](https://github.com/JetBrains/youtrack-mobile/blob/develop-new-router/src/components/router/router.js#L4) for such screens, and it works partially. Screen appears without animation, but when I open next screen with animation and close it by dispatching "BACK" action, previous screen doesn't appear – empty screen shown.
Strange, but it is shown if i close it by "swipe to the right" action.

See gif for details. The list appears without animation, the details page has animation.

1th Part: go back by dispatching "BACK" action
2th Part: go back by swipe action:

![mar-22-2017 23-15-50](https://cloud.githubusercontent.com/assets/4318513/24218774/8d20dc8c-0f55-11e7-9513-efb3be280405.gif)

**Comment by grabbou** [comment]
Closing in favour of #175
