### ISSUE TITLE
[Performance] Cache calls to `props.router.getScreenConfig()`

### ISSUE THREAD

**Issue by joonhocho** [react-community/react-navigation#785]
I noticed that my `navigationOptions.header({state})` is called around 8 times for every `props.navigation.setParams` call.

This is okay if your navigationOptions is super lightweight, but many times it renders React Component as `header.right`.
Also, not just currently active `navigationOptions.header` is called, but all `navigationOptions.header()` in your navigation stack is called at the same time.

You can find multiple calls to `getScreenConfig` in the following files:
https://github.com/react-community/react-navigation/blob/master/src/views/CardStack.js
https://github.com/react-community/react-navigation/blob/master/src/views/Header.js
https://github.com/react-community/react-navigation/blob/master/src/views/TabView/TabView.js

**Comment by despreston** [comment]
Yeah I'm noticing a 1-1.5 second lag between when my screen is being rendered and when the right icon appears. This isn't really acceptable from a design standpoint so I +1 for additional eyes on this...

**Comment by satya164** [comment]
Calling it multiple times is fine. But we need to cache the results.

**Comment by joonhocho** [comment]
Agreed!

**Comment by kelset** [comment]
Pinging OP @joonhocho  since this issue is quite old and related to an old version of the lib; does this still happen?

(If no answer I'll close in 7 days, in order to try to clean up the issues and reduce redundancy)

**Comment by joonhocho** [comment]
@kelset  You can close it as I am not using react-navigation anymore :(
