### ISSUE TITLE
Multiple Drawers

### ISSUE THREAD

**Issue by danielfeelfine** [react-community/react-navigation#786]
The challenge is to create a screen with a _main_ drawer on the left side, and a _context_ drawer on the right side. 

When I trigger `this.props.navigation.navigate('DrawerOpen')` according [documentation](https://reactnavigation.org/docs/navigators/drawer#DrawerNavigator), the right (_context_) drawer is opened. It's ok, but how I open the left (_main_) drawer?

Is possible to change the value of `'DrawerOpen'` to the _main_ drawer as `'MainDrawerOpen'`? According [this line](https://github.com/react-community/react-navigation/blob/master/src/navigators/DrawerNavigator.js#L61) of `DrawerNavigator.js`, I think this is not possible. Right?

Do I need to create a [Custom Navigator](https://reactnavigation.org/docs/navigators/custom) for that? 

Thanks.

**Comment by sigmazen** [comment]
is this similar to #780  ??

**Comment by danielfeelfine** [comment]
Yes @sigmazen.

**Comment by BenoitClaveau** [comment]
@sigmazen in your case, you don't have 2 drawers for the same view. How can I do if I want 2 drawers, one for the navigation and the second to display a contextual action bar. 
Thanks.

**Comment by BenoitClaveau** [comment]
@udarts I use react-native-side-menu for my right drawer and react-navigation for my left drawer.

**Comment by udarts** [comment]
Thanks, I had that one installed, but haven't used it, will do now.

**Comment by brentvatne** [comment]
the discussion here might be help for you folks: https://github.com/react-navigation/react-navigation/issues/4440

**Comment by udarts** [comment]
@BenoitClaveau I have tried to use react-native-side-menu, it works, but it is very slow in opening the side bar.
