### ISSUE TITLE
[Docs][Need-Help] Redux Integration Clarification

### ISSUE THREAD

**Issue by ElliottJRo** [react-community/react-navigation#787]
Hey all, I didn't quite understand the Redux integration notes found in the first few paragraphs in [navigation props docs](https://reactnavigation.org/docs/navigators/navigation-prop) so I left it as verbatim from #319.

Need some help finishing PR #338

**Comment by grabbou** [comment]
PRs were merged so I am closing! Thanks for help.

Also, we recently improved redux example itself which may help
