### ISSUE TITLE
Background Transparent or Image to TabNavigator

### ISSUE THREAD

**Issue by chhornponleu** [react-community/react-navigation#788]
<img width="394" alt="screen shot 2560-03-23 at 8 48 26 am" src="https://cloud.githubusercontent.com/assets/14964945/24228290/d28544e8-0fa5-11e7-8743-96d60699972b.png">

I config with the following options, but still cannot see background through TabBar

tabBarOptions: {
        //tinColor: 'red',
        activeTintColor: '#fff',
        inactiveTintColor: '#eee',
        showIcon: true,
        showLabel: true,
        animationEnabled: false,
        lazyLoad: true,
        upperCaseLabel: false,
        indicatorStyle: {
            backgroundColor: 'transparent'
        },
        style: {
            backgroundColor: 'transparent',

**Comment by sunxlfree** [comment]
can u give me this tabBarOptions for all, i just want to learn you style that what i can't see below the backgroundColor

**Comment by chhornponleu** [comment]
tabBarOptions: {
        tinColor: '#fff',
        activeTintColor: '#eee',
        inactiveTintColor: '#fff',
        showIcon: true,
        showLabel: true,
        lazyLoad: true,
        upperCaseLabel: false,
        indicatorStyle: {
            backgroundColor: 'transparent'
        },
        style: {
            //backgroundColor: '#cc9933',
            backgroundColor: '#003366',
            //opacity: 0.7,
            padding: 0,
            margin: 0,
            borderTopWidth: 3,
            borderTopColor: '#996600'
        },
        labelStyle: {
            fontSize: 8,
        },
        tabStyle : {
            backgroundColor: 'transparent'
        }
    },

**Comment by AlanFoster** [comment]
@chhornponleu I believe this should be your use case:

```js
class YourScreen extends React.Component {
  render() {
    return (
      <View
        style={{
          backgroundColor: 'green',
          flex: 1
        }}
      >
        <Text style={{ color: 'white' }}>My Application</Text>
      </View>
    );
  }
}

const tabOptions = {
  Main: {
    screen: YourScreen
  },
  Checkout: {
    screen: YourScreen
  },
  Location: {
    screen: YourScreen
  },
  Settings: {
    screen: YourScreen
  }
};

const TabbedNavigation = TabNavigator(tabOptions, {
  initialRouteName: 'Main',
  animationEnabled: false,
  swipeEnabled: false,
  lazyLoad: true,
  tabBarOptions: {
    tinColor: '#fff',
    activeTintColor: '#eee',
    inactiveTintColor: '#fff',
    showIcon: true,
    showLabel: true,
    lazyLoad: true,
    upperCaseLabel: false,
    indicatorStyle: {
      backgroundColor: 'transparent'
    },
    style: {
      backgroundColor: 'rgba(22, 22, 22, 0.3)',
      borderTopWidth: 3,
      borderTopColor: '#996600',
      position: 'absolute',
      left: 0,
      right: 0,
      bottom: 0
    }
  }
});

export default TabbedNavigation;
```

With a green background for my application, rather than an image, that looks like:

![image](https://cloud.githubusercontent.com/assets/1271782/24636530/d4962b18-18d2-11e7-8bb3-0b231574a811.png)

Note - this means that the menu bar is now 'floating' above your application. You'll most likely want to add some marginBottom to push your content up now as a result, unless you want it to appear _under_ your tabbed navigator.

**Comment by chhornponleu** [comment]
That is what I want it to be.
Thanks

**Comment by sunxlfree** [comment]
thanks

**Comment by faceyspacey** [comment]
how can you set the `backgroundColor` for every screen? Do you really have to go into each screen and give the same styles over and over again? I was hoping to at least set the screen to `transparent` and be able to do some fancier stuff in the background. Does anyone know how to do this sorta stuff?

**Comment by arnaubennassar** [comment]
Any idea on how to achieve something similar for the top tabbar navigator. The bottom works awesome with @AlanFoster example, but the moment `position: 'absolute',` is set on the top navigator, the hole thing disappear, as mentioned in #1680 .

**Comment by valeriaabo** [comment]
@arnaubennassar  Did you found a solution? Im stucked :(

**Comment by arnaubennassar** [comment]
No, I didn't. I end up playing with the color of the background to match the color of the tab bar, which is far from ideal. Let me know if you figure out how to do it!

**Comment by KEYDATA** [comment]
@arnaubennassar 
1、Set the style "position: 'absolute',left: 0,right: 0,bottom: 0"，
if Tab Bar not visible：
1、remove containers around header and footer：https://github.com/react-native-community/react-native-tab-view/commit/13243a2c6e048c73b089de63da58b7320fdb8bf0
2、disable buggy zIndex on Android：https://github.com/react-native-community/react-native-tab-view/commit/13243a2c6e048c73b089de63da58b7320fdb8bf0

**Comment by ricbermo** [comment]
for future readers, the Tabs are now visible using the `1.0.0-beta.12` version

**Comment by ASAPHAANING** [comment]
Bump. I want to make the tabbar transparent yet none of these stylings seem to work.

**Comment by Kernael** [comment]
With version `1.0.0-beta.12`, don't forget to bump the TabBar `zIndex` to make it work.

**Comment by nihp** [comment]
@chhornponleu How did u set the image for the footer using tab navigation?. Kindly provide yr input

**Comment by nihp** [comment]
I have set showicon: true, but the footer does not displayed in the footer section

**Comment by Culzean** [comment]
@AlanFoster this solution worked for me as well. Though I find the behaviour unintuitive. For anyone else looking at this issue, we used a custom tab bar tabBarComponent: TXTabBar. So the position absolute has to be set in the custom component style sheet.

**Comment by brentvatne** [comment]
this should be resolved. if it is not working as expected still on the latest version, please create a new issue with a runnable example on https://snack.expo.io -- thanks!
