### ISSUE TITLE
navigation  header view have a shadow ，how does  it  to  remove shadow？

### ISSUE THREAD

**Issue by roselind** [react-community/react-navigation#790]
StackNavigator （StackNavigator）   
ios ： 
![c33f7c5d-b55e-4cdc-9f6a-2ad34f96fe11](https://cloud.githubusercontent.com/assets/9067932/24232951/90a7510a-0fc9-11e7-8aab-48b7389a1820.png)
 
android:
![android-](https://cloud.githubusercontent.com/assets/9067932/24233256/05bf982e-0fcc-11e7-8a3e-ea4eb44bb87a.png)

**Comment by jkongie** [comment]
You can change the header style in navigationOptions of the StackNavigator

Something like this ( I haven't tested it though )
```
const MainNavigator = StackNavigator(
  {
    Home: { screen: Home }
  },
  {
    navigationOptions: {
      header: {
        style: {
          shadowOpacity: 0,
          shadowOffset: {
            height: 0,
          },
          shadowRadius: 0,
        }
      }
    }
  }
);
```

**Comment by roselind** [comment]
It doesn't work

code：
`const standardNavigationOptions = {
  header: {
    visible:true,
    tintColor: 'white',
    style: {
         backgroundColor: ColorDefDictionary.standardBlue,
           shadowOpacity: 0,
           shadowOffset: {
             height: 0,
           },
           shadowRadius: 0,
   },
.....`

**Comment by jkongie** [comment]
These are the default header styles

https://github.com/react-community/react-navigation/blob/master/src/views/Header.js#L330-L341

`elevation` is an Android only style property that may be affecting causing the issue

**Comment by roselind** [comment]
It's not like that .
It doesn't work   I set shadow ' s   style

**Comment by roselind** [comment]
I tried a variety of ways or can not remove the shadow  on android.
Please help it

**Comment by kamalk333** [comment]
put this in its style object
-> elevation = 0

**Comment by Ehesp** [comment]
`elevation: 0` on Android removes this.

**Comment by roselind** [comment]
thanks . I solve it  . 
 
At first it didn't work, and the second day ，the shadow be removed,    it looked like it was a cache

code :
 navigationOptions: {
      header: {
        style: {
          shadowOpacity: 0,
          shadowOffset: {
            height: 0,
           width:0
          },
          shadowRadius: 0,
        }
      }

**Comment by zarcode** [comment]
@roselind using it like this
```export const AppNavigator = StackNavigator(
    {
      Login: { screen: LoginScreen },
      Main: { screen: MainScreen },
    },
    {
        cardStyle: {
            shadowColor: 'transparent',
        },
        navigationOptions: {
            header: {
                style: {
                    elevation: 0,       //remove shadow on Android
                    shadowOpacity: 0,   //remove shadow on iOS
                }
            }
        }
    }
);```

gives me error

```ExceptionsManager.js:63 Objects are not valid as a React child (found: object with keys {style}). If you meant to render a collection of children, use an array instead. in View (at CardStack.js:391)```

Please help

**Comment by roselind** [comment]
@zarcode 

export const AppNavigator = StackNavigator(
    {
      Login: { screen: LoginScreen },
      Main: { screen: MainScreen },
    },
    {
        cardStyle: {
            shadowColor: 'transparent',
        },
        header: {
                style: {
                    elevation: 0,       //remove shadow on Android
                    shadowOpacity: 0,   //remove shadow on iOS
                }
          }
  }
);

**Comment by Barylskyigb** [comment]
Properties names have changed, so:

```
  navigationOptions = {
      headerStyle: {
        elevation: 0,
        shadowOpacity: 0
      }
  }
```

**Comment by devfausto** [comment]
Use headerStyle para economizar linhas
```javascript
 headerStyle: {
                        elevation: 0
                    }
```

**Comment by tapz** [comment]
shadowOpacity and elevation do nothing in 1.0.0-beta.15.

**Comment by dsternlicht** [comment]
@tapz Upgrading react-navigation to **^1.0.0-beta.19** in package.json and re-installing, did the trick.

**Comment by billscheidel** [comment]
I've got a TabNavigator and no matter how I try to specify the `headerStyle` nothing seems to take. Is there a different way to do with a TabNavigator? 

````
const HomeScreenNavigator = TabNavigator(
  {
    [screens.TODO]: {
      screen: ToDoScreen,
      navigationOptions: {
        headerStyle: {
          shadowOpacity: 0,
          elevation: 0,
        },
      },
    },
    [screens.CONTACTS]: { screen: ContactsScreen },
    [screens.INBOX]: { screen: InboxScreen },
  },
}
````

With this the border is still visible on the To Do Screen.

**Comment by arronhunt** [comment]
Can confirm, `1.0.0-beta.27` I cannot get the shadow to go away.

I have tried both options:

```jsx
export default StackNavigator({
    Main: { 
        screen: Main,
        navigationOptions: {
            headerStyle: {
                shadowOpacity: 0
            }        
        }
    },
});
```

and 

```jsx
class Main extends Component {
    static navigationOptions = ({ navigation }) => {
        const { params = {} } = navigation.state;
        return {
            title: 'Main',
            headerStyle: { 
                shadowOpacity: 0
            },
        }
    }
}
```

**Comment by SteveGreenley** [comment]
I've looked through the code. On iOS the headerStyle property you need to override is 'borderBottomWidth'. This works for me with react-navigation ^1.0.3 as of 17th Feb 18:

headerStyle:{ 
  // iOS
  borderBottomWidth:0, 
  // Android
  elevation:0 
}

**Comment by dhirendrarathod2000** [comment]
We have header set to null for the page and then following worked
Seems like the card/screens have the shadow of their own
```
StackNavigator({
     Main: { 
      screen: Main,
     },
     Main2: { 
      screen: Main2,
     },
   } , 
   {
     initialRouteName:'Main',
     cardStyle: {
      shadowColor: 'transparent',
     },
  },
);
```

**Comment by totti1** [comment]
can someone please tell how to fix this if it's possible

**Comment by totti1** [comment]
i did it but nothing changed

**Comment by nsisodiya** [comment]
Trying to hide border from last 1 hour but because we hopelessly dependant on this repo and Google.
I hate this thing because I always waste so much time on such small issues. It is much easier to write our own code.

**Comment by mengruwu** [comment]
@nsisodiya Have you tried to set `borderBottomWidth: 0` in `headerStyle` ?

**Comment by tomleader** [comment]
```
headerStyle: {
        backgroundColor: '#fff',
        shadowColor: 'transparent',
        elevation: 0
      }
```
DON'T set the borderBottomWidth attr

**Comment by localshred** [comment]
Just to add clarity for others, I'm using a bottom tab navigator (from `react-navigation-material-bottom-tabs`) and two of my tabs have their own stack navigators. Setting the `headerStyle` didn't remove the shadow for me, but setting `cardStyle` did. Here's the source of the whole file just so it's totally clear. The only lines added were the two styles in `cardStyle` in the `stack` function.

```javascript
import { createStackNavigator } from 'react-navigation'
import { createMaterialBottomTabNavigator } from 'react-navigation-material-bottom-tabs'
import TabBarIcon from 'app/components/tab-bar-icon'
import CommitmentsScreen from 'app/containers/commitments-screen'
import FoodPlanScreen from 'app/containers/food-plan-screen'
import SettingsScreen from 'app/containers/settings-screen'
import FoodCategoriesSettingsScreen from 'app/containers/food-categories/settings-screen'
import FoodCategoriesEditScreen from 'app/containers/food-categories/edit-screen'
import PortionEditScreen from 'app/containers/meal-plans/portion-edit-screen'
import { colors, paperTheme } from 'app/themes'

export const DEFAULT_SCREEN_NAME = 'FoodPlan'

const stack = (initialRouteName, screens) =>
  createStackNavigator(screens, {
    initialRouteName,
    cardStyle: {               // <-------------- Adding cardStyle here is what removed the shadow
      elevation: 0,
      shadowOpacity: 0
    }
  })

const tab = (screen, title, iconName, backgroundColor) => ({
  screen,
  navigationOptions: {
    barStyle: { backgroundColor },
    headerStyle: { backgroundColor },
    headerTintColor: colors.snow,
    tabBarIcon: TabBarIcon(iconName),
    title
  },
  customOverrides: {
    styles: {
      screen: { backgroundColor }
    }
  }
})

const FoodPlanStack = stack('FoodPlan', {
  FoodPlan: FoodPlanScreen,
  PortionEdit: PortionEditScreen
})

const SettingsStack = stack('Settings', {
  FoodCategoriesEdit: FoodCategoriesEditScreen,
  FoodCategoriesSettings: FoodCategoriesSettingsScreen,
  Settings: SettingsScreen
})

const tabs = {
  Commitments: tab(
    CommitmentsScreen,
    'Commitments',
    'check',
    colors.frenchMauve
  ),
  FoodPlan: tab(FoodPlanStack, 'Food Plan', 'utensils', colors.mediumTurquoise),
  Settings: tab(SettingsStack, 'Settings', 'cog', colors.darkPastelBlue)
}

const navigationSettings = {
  initialRouteName: DEFAULT_SCREEN_NAME,
  order: ['FoodPlan', 'Commitments', 'Settings'],
  labeled: false,
  activeTintColor: colors.snow,
  inactiveTintColor: colors.deepSpaceSparkle,
  barStyle: { backgroundColor: paperTheme.colors.primary },
  headerStyle: { backgroundColor: paperTheme.colors.primary },
  headerTintColor: paperTheme.colors.primary
}

const AppNavigation = createMaterialBottomTabNavigator(tabs, navigationSettings)

export default AppNavigation
```

**Comment by matthewfbenjamin** [comment]
I am using react-navigation @ 2.14.2 and  [SteveGreenley's solution](https://github.com/react-navigation/react-navigation/issues/790#issuecomment-366419897) worked for me:

```
headerStyle:{
  // iOS
  borderBottomWidth:0,
  // Android
  elevation:0
}
```

**Comment by MounirDhahri** [comment]
For react-navigation 2.x this worked for me with both android and iOS:
```
navigationOptions: {
      headerStyle: {
        shadowOpacity: 0,
        shadowOffset: {
          height: 0
        },
        shadowRadius: 0,
        borderBottomWidth: 0,
        elevation: 0
      }
    }
```

**Comment by v-ken** [comment]
Solution above works, however on iOS, when you press the back button, the bottom border shows briefly.

**Comment by mikeyamato** [comment]
> Solution above works, however on iOS, when you press the back button, the bottom border shows briefly.

This is due to the previous screen not being unmounted. Therefore, what you're seeing is not from the header you removed the border from but from the header on the previous screen.

**Comment by evanlesmez** [comment]
As of 3.x on 4/25/19 on Android used : 

```     elevation: 0,
      shadowOpacity: 0,
      borderBottomWidth: 0,
      marginBottom: -1```

**Comment by Cpinto0594** [comment]
> @roselind put this in its style object
> -> (for ios)
> shadowColor : '#5bc4ff'
> shadowOpacity: 0,
> shadowOffset: {
> height: 0,
> },
> shadowRadius: 0,
> -> elevation: 0 (for android)

This was helpful

**Comment by matthewfbenjamin** [comment]
Here's what worked for me:

```
import { Platform, StyleSheet } from 'react-native'
import { BlurView } from '@react-native-community/blur'
import { createStackNavigator, createAppContainer, HeaderStyleInterpolator } from 'react-navigation'

createStackNavigator({
    RouteA: {
      screen: RouteA,
      params: { someVariable: true },
    },
    RouteB: {
      screen: RouteB,
    }
  },
  {
    defaultNavigationOptions: {
      headerBackground:
      Platform.OS === 'ios' ? (
        <BlurView style={{ flex: 1 }} blurType="light" />
      ) : (
        <AndroidSpecificHeader />
      ),
      headerStyle: {
        borderBottomColor: theme.colors.header.borderBottomColor,
        borderBottomWidth: StyleSheet.hairlineWidth,
      },
      headerTransparent: true,
    },
    headerTransitionPreset: 'uikit',
    transitionConfig: () => ({
      headerBackgroundInterpolator: HeaderStyleInterpolator.forBackgroundWithTranslation,
    }),
    headerMode: 'float',
    initialRouteName: 'RouteA',
  })
```

**Comment by JiangXuefeng** [comment]
this works well:
headerStyle: {
borderBottomWidth: 0, // for ios
elevation: 0// for android
}

**Comment by Hissvard** [comment]
I implemented a custom header on iOS and has this issue where the header had a white square, 2px wide, in the leftmost area of every header. It was particularly noticeable when swiping back from a screen.

What made it go away was:
```javascript
createStackNavigator({}, { cardShadowEnabled: false });
```

**Comment by Mlobaievskyi** [comment]
you need to use 
```
navigationOptions: { hideShadow: true }
```

**Comment by SubinRabin** [comment]
<Router >
     <Scene key = "root"  navTransparent={true}>
       <Scene key = "Home" component = {Home} title = "Home"  initial = {true}/>
       <Scene key = "AgentLogin" component = {AgentLogin} title = "" hideNavBar={false} />
     </Scene>
</Router>


navTransparent={true}

**Comment by felipejh** [comment]
`elevation: 0` in Android 10 doesnt work.
It is changes to transparent header.

![WhatsApp Image 2020-10-01 at 09 55 41](https://user-images.githubusercontent.com/37714181/94812038-8e448900-03cc-11eb-99a6-8aa3c8aa8432.jpeg)

**Comment by ihar-dambrouski** [comment]
![image](https://user-images.githubusercontent.com/60747836/99972458-9824b000-2daf-11eb-8382-055fb7df41f3.png)
it works for react native 0.63.3 and react navigation 5

**Comment by csbun** [comment]
```jsx
<Stack.Screen
  options={{ headerShadowVisible: false }}
  ...
/>
```

works on react-navigation@6

**Comment by sospedra** [comment]
In v6 I had to use `options: { headerLargeTitleShadowVisible: false }`. 
Worked like a charm 👍
