### ISSUE TITLE
component props

### ISSUE THREAD

**Issue by dansha** [react-community/react-navigation#791]
Is there a way to pass parmas that will be props in the screen components. 
for example: I have a CarView with prop Model
I understand I can change CarView to take the Model from "this.props.navigation.state"
and navigate to the  CarView by
this.props.navigation.Navigate('car' , {Model:'Totyota'});

is there an elegant way to  leave  CarView.js to take the Model from its Props ?

**Comment by hasaezs** [comment]
+1

**Comment by lappalj4** [comment]
+1

Can't believe there is no way to do this?

**Comment by spencercarli** [comment]
Hi! Since this issue has been quiet for a while I'm going to go ahead and close it. If the issue persists in the latest version of React Navigation please re-open!
