### ISSUE TITLE
inactiveTintColor and activeTintColor isn't working on tabnavigators.

### ISSUE THREAD

**Issue by kamalk333** [react-community/react-navigation#792]
Is anyone facing the same situation like mine. I'm stuck here and can't change the colour of the inactive or active tab bars.

**Comment by sigmazen** [comment]
activeTintColor is for the text and icon rather than the tab itself which I believe is handled by activeBackgroundColor.
This example is working fine for me:

    export const TabStack = TabNavigator({
      tabHome:     { screen: HomeStack,       },
      tabOptions:  { screen: GeneralStack,    },
    }, {
     tabBarOptions: ({
        activeBackgroundColor: 'blue',
        inactiveBackgroundColor: 'green',
        activeTintColor: 'white',
        inactiveTintColor: 'grey',
        style: { backgroundColor: 'blue' },
        labelStyle: { fontWeight: 'bold' },
      })
    } );

**Comment by kamalk333** [comment]
Well, I did exactly the same but nothing is happening neither active/inactive backgroundColor changes nor tintColor.

**Comment by kamalk333** [comment]
`const tabBarConfig = {
      tabBarOptions: {
         upperCaseLabel: false,
         activeTintColor: 'white',
         inactiveTintColor: 'grey',
         activeBackgroundColor: 'blue',
         inactiveBackgroundColor: 'green',
         indicatorStyle: {
             width: 30,
             height: 2,
             borderRadius: 4,
             marginLeft: width*15/72,
             backgroundColor: blackColour,
         },
    labelStyle: {
        color: blackColour,
        fontSize: 16,
        fontFamily: "montserrat_regular"
    },
    style: {
        backgroundColor: orangeColor,
        shadowColor : orangeColor,
    },
    
  },
};
const tabNavigatorRouteConfig = {
    Videos: {
       screen: VideoTab,
    },
   Tools: {
       screen: Toolspage,
  }
};

const TabNavigatorForVideoAndToolsPage = TabNavigator(tabNavigatorRouteConfig, tabBarConfig);`

**Comment by 277850318** [comment]
![image](https://cloud.githubusercontent.com/assets/8946022/25037048/8c3c1134-2129-11e7-98e1-dd7ede94ca0c.png)

**Comment by matthieucan** [comment]
Hi,
I can confirm the variables activeBackgroundColor, inactiveBackgroundColor, activeTintColor, inactiveTintColor have no effect, at least on Android.
@sigmazen I tried your example without success, only style and labelStyle seem to work.

**Comment by abhishek0058** [comment]
+1

**Comment by JohnPremKumar** [comment]
The active and inactive tint color actually works. But its actually overridden by the label style color.

In order to make it work the color attribute in the label style should be removed.

You can make use of activeTintColor and inactiveTintColor alone to get expected results
