### ISSUE TITLE
App crashes to exit pressing backAndroid

### ISSUE THREAD

**Issue by darleikroth** [react-community/react-navigation#794]
When I try to exit the app using the **backAndroid** button, I got the follow: _Unfortunately, appsample has stopped._ (Dialog android).
And in the log: _undefined is not an object (evaluating 'listener.hasOwnProperty')_.
This is my main RouterStack:
```js
import { StackNavigator } from 'react-navigation';
import Splash from './screens/Splash';
import Dashboard from './screens/Dashboard';
import Notifications from './screens/Notifications';

const MainStack = StackNavigator({
    Dashboard: { screen: Dashboard },
    Notifications: { screen: Notifications }
});

const App = StackNavigator(
    {
        Splash: {screen: Splash},
        Main: {screen: MainStack},
    },
    {
        headerMode: 'screen',
        navigationOptions: {
            header: { visible: false }
        }
    },
);

module.exports = App;
```

I'm doing this at right way?

**Comment by darleikroth** [comment]
Oh wait. I noticed that the navigation reset is not the problem. If I start with the follow configuration:
```js
const MainStack = StackNavigator({
    Dashboard: { screen: Dashboard },
    Notifications: { screen: Notifications }
});

const App = StackNavigator(
    {
        Main: { screen: MainStack },
        Splash: { screen: Splash },
    },
    {
        headerMode: 'screen',
        navigationOptions: {
            header: { visible: false }
        }
    },
);
```
So, my app start with **MainStack**, and I got the same problem reported above. Any way, I don't understand why.
Maybe a bug? Thanks!

**Comment by darleikroth** [comment]
I noticed that my problem can be related with some of this:
[#691](https://github.com/react-community/react-navigation/issues/691)

**Comment by jascaniojah** [comment]
@darleikroth any fix on this?

**Comment by brentvatne** [comment]
@jascaniojah - there was never a repro posted, create a new issue and follow template and we can help.
