### ISSUE TITLE
How to hide DrawerView.Item in DrawerNavigator contentComponent

### ISSUE THREAD

**Issue by maggialejandro** [react-community/react-navigation#795]
Hi, I have a Login screen in my DrawerNavigator
The Drawer content is replaced with a custom contentComponent, and I need to hide that screen from DrawerView.Items

is there a way to do that?
thanks in advance

**Comment by dantman** [comment]
#1039 adds an `items` property to `DrawerView.Item` that allows you to override `navigation.state.routes`. Using that you could `.filter` the routes to exclude your login route.

**Comment by makassigithub** [comment]
@dantman would you post a code snippet on that. In my case I have a Login Screen in my drawer Items. That screen is supposed to be the first screen when a user is login for the first time. But I do not want that Login screen  to be visible in the drawer  when the user's session is active.

Thanks for helping with this.

**Comment by markentingh** [comment]
could you give us an example of how to use DrawerView.Item.items to override navigation.state.routes?

**Comment by greatsteppe** [comment]
It works for me:
`contentComponent: props => {
    var copyprops = Object.assign({}, props); 
    copyprops.items = copy.items.filter( item => item.key !== 'login' )
    return (    
      <ScrollView>
        <DrawerItems { ...copyprops }/>
      </ScrollView>
    )
  } `

**Comment by dantman** [comment]
Thanks @greatsteppe it's a bit more cryptic than it needs to be, but that is the general idea.

@markentingh 
Here's a modified version of the ["Providing a custom `contentComponent`"](https://reactnavigation.org/docs/navigators/drawer#Providing-a-custom-contentComponent) example in the documentation. That hides one item and renders a Home item separate from the rest of the drawer items.
```js
import { DrawerItems } from 'react-navigation';

const CustomDrawerContentComponent = (props) => (
  <View style={style.container}>
    <DrawerItems
      {...props}
      items={items.filter((item) => item.routeName === 'Home' && item.routeName !== 'HiddenRoute')} />
    <Text>Section</Text>
    <DrawerItems
      {...props}
      items={items.filter((item) => item.routeName !== 'Home' && item.routeName !== 'HiddenRoute')} />
  </View>
);

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
});
```

**Comment by bencodezen** [comment]
Since I originally found this thread before this one https://github.com/react-community/react-navigation/issues/2021, just wanted to let people know of a handy trick that avoid custom drawerComponents

```js
class ScreenYouWantToHide extends React.Component {
    static navigationOptions = {
         drawerLabel: () => null
    }
}
```

**Comment by AlexKovalchuk** [comment]
bencodezen, thank you alot!

**Comment by shie-erlich** [comment]
@bencodezen this is super handy. thanks!

**Comment by Progoogler** [comment]
Just want to chime in that adding 
```
static navigationOptions = {
    drawerLabel: () => null
}

```
to the class component didn't work for me, but appending it to the DrawerNavigator config did:
```
const AppNavigator = DrawerNavigator({  
  Home: {
    screen: Home,
    navigationOptions = {
        drawerLabel: () => null
    }
});
```
Thanks for the direction @bencodezen !

**Comment by SatoshiInoue** [comment]
I took a different approach
`const AppStack = StackNavigator(
  {
    DrawerStack: {screen: DrawerStack},
    settingScreenStack: {screen: settingScreenStack}
  },
  {
    headerMode:'none'
  }
);`
DrawerStack contains multiple StackNavigator screens, which are displayed in the menu. 'settingScreenStack' doesn't show up in the menu (But gets invoked by a button placed in the Drawer view).

**Comment by alainib** [comment]
i want to hide an item from DrawerNavigator pragmaticaly from a webservice call.

This is my code :  

	const MyDrawerNavigator = DrawerNavigator(
	  {     
		...
		CreditsPage: { screen: CreditsPage }, 
		TestPage: { screen: TestPage },
		... 
	  },
	  {...}
	);


	export default class App extends React.PureComponent {
	  constructor (props) {
		super(props);
        ...
	  }


	  componentWillMount() {
		this.getTest();
	  }

	  async getTest() {
		const res = await getTestService();
		// return { enabled : true/false } 
		if(res.enabled){
			// i want to display TestPage
		}else{
			//hide TestPage
		}
	  }

	  render() {
		return (
		  <Provider store={store}>
			<PersistGate
			  loading={<ActivityIndicator />}
			  persistor={persistor}>

			  <View style={{ flex: 1, marginTop: Config.topMargin }}>
				<MyDrawerNavigator />
			  </View>
			</PersistGate>
		  </Provider>
		);
	  }
	}

any idea please ? thx

**Comment by dantman** [comment]
@alainib 
```js
import { DrawerItems, SafeAreaView } from 'react-navigation';

class CustomDrawerContentComponent extends PureComponent {
  state = {
    showTestPage: false,
  };

  componentWillMount() {
    this.getTest();
  }

  async getTest() {
    const res = await getTestService();
    this.setState({showTestPage: res.enabled});
  }

  render() {
    const {showTestPage} = this.state;

    return (
      <ScrollView>
        <SafeAreaView style={styles.container} forceInset={{ top: 'always', horizontal: 'never' }}>
          <DrawerItems
            {...props}
            items={items.filter((item) => item.routeName !== 'TestPage' || showTestPage)} />
        </SafeAreaView>
      </ScrollView>
    );
  }
}
```

**Comment by JPStrydom** [comment]
> Since I originally found this thread before this one #2021, just wanted to let people know of a handy trick that avoids the custom drawerComponents approach and is much simpler to implement.
> 
> ```js
> class ScreenYouWantToHide extends React.Component {
>     static navigationOptions = {
>          drawerLabel: () => null
>     }
> }
> ```

This method still makes the area where the item would appear in the drawer clickable I believe - I might be doing something wrong, but this is the case for me.

**Comment by mickey911112** [comment]
bencodezon. It works at  me. Thanks a lot.

**Comment by Taiterbase** [comment]
Since this is still a top result on Google search for this kind of problem, I'd like to point out that both:
`class ScreenYouWantToHide extends React.Component {
    static navigationOptions = {
         drawerLabel: () => null
    }
}`
and 
`const AppNavigator = DrawerNavigator({  
  Home: {
    screen: Home,
    navigationOptions: {
        drawerLabel: () => null
    }
});`
Will only remove the named label, but will unfortunately let the label still be clickable as mentioned above. The only way that I have found thus far to remove a drawer item from the drawer navigation is using a filter. Are there any other ways for accomplishing this? ...Perhaps removing a drawer item dynamically through some state?

**Comment by giacomocerquone** [comment]
@Taiterbase I don't know which version of react-navigation you're using, but with rn navigation at 3.11.1 just setting `drawerLabel: () => null` the item does completely disappear (tested it only on Android 9.0, not iOS) and it doesn't remain interactable

**Comment by sXakil** [comment]
for those using react-navigation v5, create a custom drawer and inside `DrawerContentScrollView` instead of rendering the `DrawerItemList` component, do something like the following-
`{props.state.routeNames.map((route, idx) => {
          if (route === 'HideThis' || route === 'AndThis') return null;
          const focused = idx === props.state.index;
          return (
            <TouchableNativeFeedback
              key={route}
              onPress={() => props.navigation.navigate(route)}>
              <View
                elevation={6}
                style={{
                  ...styles.footerBtn,
                  fontWeigt: 'bold',
                  backgroundColor: focused ? '#fefefe' : 'transparent',
                }}>
                <Icon
                  type="AntDesign"
                  name={
                    focused
                      ? ico[route].icon
                      : ico[route].aIcon || ico[route].icon //had to define a object for icon matching
                  }
                  style={{
                    color: focused ? '#333' : '#fff',
                    marginHorizontal: 10,
                  }}
                />
                <Text
                  style={{
                    color: focused ? '#333' : '#fff',
                    fontFamily: 'sans-serif-medium',
                  }}>
                  {route}
                </Text>
              </View>
            </TouchableNativeFeedback>
          );
        })}`

**Comment by CiroGomes** [comment]
> for those using react-navigation v5, create a custom drawer and inside `DrawerContentScrollView`, instead of rendering the `DrawerItemList` component, do something like the following-
> 
> ```js
>     {props.state.routeNames.map((route, idx) => {
>           if (route === 'HideThis' || route === 'AndThis') return null;
>           const focused = idx === props.state.index;
>           return (
>             <TouchableNativeFeedback
>               key={route}
>               onPress={() => props.navigation.navigate(route)}>
>               <View>
>                 <Icon
>                   type="AntDesign"
>                   name={
>                     focused
>                       ? ico[route].aIcon || ico[route].icon
>                       : ico[route].icon //had to define an object for icon matching
>                   }
>                 />
>                 <Text
>                   style={{
>                     color: focused ? '#333' : '#fff'
>                   }}>
>                   {route}
>                 </Text>
>               </View>
>             </TouchableNativeFeedback>
>           );
>         })}
> ```

Yeah, I'm using v5 too and `drawerLabel: () => null` does makes it invisible, but the option is still there, and what I wanted was it to desapear. 

The answer above does fix it, but I would have to care about style. I simply filter the routes and routeNames to exclude the DrawerItem that I don't want to show. So here's a simple example of what I did:
```js

import { NavigationContainer } from '@react-navigation/native';
import {
  createDrawerNavigator,
  DrawerItemList,
  DrawerContentScrollView,
} from '@react-navigation/drawer';

const Drawer = createDrawerNavigator();

const MyComponent = () => (
  <NavigationContainer>
    <Drawer.Navigator
      drawerContent={props => {
        const filteredProps = {
          ...props,
          state: {
            ...props.state,
            routeNames: props.state.routeNames.filter(
              value => value !== 'DrawerItemToHide'
            ),
            routes: props.state.routes.filter(
              value => value.name !== 'DrawerItemToHide'
            ),
          },
        };
        return (
          <DrawerContentScrollView {...filteredProps}>
            <DrawerItemList {...filteredProps} />
          </DrawerContentScrollView>
        );
      }}
    >

      // All the Drawer.Screen goes here

    </Drawer.Navigator>
  </NavigationContainer>
);
```

With that the item won't show anymore, but I still can navigate to it.
Hope I've helped!

**Comment by hackrx** [comment]
> > for those using react-navigation v5, create a custom drawer and inside `DrawerContentScrollView`, instead of rendering the `DrawerItemList` component, do something like the following-
> > ```js
> >     {props.state.routeNames.map((route, idx) => {
> >           if (route === 'HideThis' || route === 'AndThis') return null;
> >           const focused = idx === props.state.index;
> >           return (
> >             <TouchableNativeFeedback
> >               key={route}
> >               onPress={() => props.navigation.navigate(route)}>
> >               <View>
> >                 <Icon
> >                   type="AntDesign"
> >                   name={
> >                     focused
> >                       ? ico[route].aIcon || ico[route].icon
> >                       : ico[route].icon //had to define an object for icon matching
> >                   }
> >                 />
> >                 <Text
> >                   style={{
> >                     color: focused ? '#333' : '#fff'
> >                   }}>
> >                   {route}
> >                 </Text>
> >               </View>
> >             </TouchableNativeFeedback>
> >           );
> >         })}
> > ```
> 
> Yeah, I'm using v5 too and `drawerLabel: () => null` does makes it invisible, but the option is still there, and what I wanted was it to desapear.
> 
> The answer above does fix it, but I would have to care about style. I simply filter the routes and routeNames to exclude the DrawerItem that I don't want to show. So here's a simple example of what I did:
> 
> ```js
> import { NavigationContainer } from '@react-navigation/native';
> import {
>   createDrawerNavigator,
>   DrawerItemList,
>   DrawerContentScrollView,
> } from '@react-navigation/drawer';
> 
> const Drawer = createDrawerNavigator();
> 
> const MyComponent = () => (
>   <NavigationContainer>
>     <Drawer.Navigator
>       drawerContent={props => {
>         const filteredProps = {
>           ...props,
>           state: {
>             ...props.state,
>             routeNames: props.state.routeNames.filter(
>               routeName => routeName !== 'DrawerItemToHide'
>             ),
>             routes: props.state.routes.filter(
>               route => route.name !== 'DrawerItemToHide'
>             ),
>           },
>         };
>         return (
>           <DrawerContentScrollView {...filteredProps}>
>             <DrawerItemList {...filteredProps} />
>           </DrawerContentScrollView>
>         );
>       }}
>     >
> 
>       // All the Drawer.Screen goes here
> 
>     </Drawer.Navigator>
>   </NavigationContainer>
> );
> ```
> 
> With that the item won't show anymore, but I still can navigate to it.
> Hope I've helped!

Thanks man, it worked for me 😀, finally, after 2 days found the solution

**Comment by mayank-budhiraja** [comment]
@CiroGomes How to filter multiple drawer items?

**Comment by SnehalAgrawal** [comment]
> @CiroGomes How to filter multiple drawer items?

You can add 'and(&&)' condition for that
```JSON
routes: props.state.routes.filter(
  (route) => route.name !== 'HiddenPage' && route.name !== 'SecondPage',
),
```

Reference: [How to Hide Navigation Option from Navigation Drawer / Sidebar](https://aboutreact.com/how-to-hide-navigation-drawer-sidebar-option/)

**Comment by yashkumarsharma** [comment]
I ended up using the following code -
```
{state.routes.map((route, i) => {
          if(route.name === 'App') return;
          const focused = i === state.index;
          const { title, drawerLabel, drawerIcon } = descriptors[route.key].options;

          return (
            <DrawerItem
              key={route.key}
              label={
                drawerLabel !== undefined
                  ? drawerLabel
                  : title !== undefined
                  ? title
                  : route.name
              }
              icon={drawerIcon}
              focused={focused}
              activeTintColor={activeTintColor}
              inactiveTintColor={inactiveTintColor}
              activeBackgroundColor={activeBackgroundColor}
              inactiveBackgroundColor={inactiveBackgroundColor}
              labelStyle={labelStyle}
              style={itemStyle}
              to={buildLink(route.name, route.params)}
              onPress={() => {
                navigation.dispatch({
                  ...(focused
                    ? DrawerActions.closeDrawer()
                    : CommonActions.navigate(route.name)),
                  target: state.key,
                });
              }}
            />
          );
        })}
```
Complete code can be found here -

https://gist.github.com/yashkumarsharma/a56f4fe1517ee8ce07c153d2d2795f6f

**Comment by castalonirenz** [comment]
Hi i hope this helps.

i removed DrawerItemList then set <Drawer.Screen> drawLabel to null

`import * as React from 'react';
import {
    createDrawerNavigator, DrawerContentScrollView,
    DrawerItemList, DrawerItem} from '@react-navigation/drawer';
import { Text } from "react-native";
import { TabNav } from '../Tab/Tab';

const Drawer = createDrawerNavigator();


function CustomDrawerContent(props) {
    return (
        <DrawerContentScrollView {...props}>
            {/* <DrawerItemList {...props} /> */}
            <Text>Sample</Text>
            <DrawerItem
                label="Help"
              
            />
        </DrawerContentScrollView>
    );
}

export const DrawerNav = (props) => {

    return(
        <Drawer.Navigator drawerContent={CustomDrawerContent} drawerType={"slide"} drawerStyle={{
            width: "85%"
        }}>
            <Drawer.Screen options={{
                drawerLabel: () => null,
            }}  name="test" component={TabNav} />
        </Drawer.Navigator>
    )
    
}`

**Comment by castalonirenz** [comment]
Hi i hope this helps.

i removed DrawerItemList then set <Drawer.Screen> drawLabel to null

`import * as React from 'react';
import {
    createDrawerNavigator, DrawerContentScrollView,
    DrawerItemList, DrawerItem
} from '@react-navigation/drawer';
import { Text } from "react-native";
import { TabNav } from '../Tab/Tab';

const Drawer = createDrawerNavigator();


function CustomDrawerContent(props) {
    return (
        <DrawerContentScrollView {...props}>
            {/* <DrawerItemList {...props} /> */}
            <Text>Sample</Text>
            <DrawerItem
                label="Help"
            />
        </DrawerContentScrollView>
    )}

export const DrawerNav = (props) => {
    return (
        <Drawer.Navigator drawerContent={CustomDrawerContent} drawerType={"slide"} drawerStyle={{
            width: "85%"
        }}>
            <Drawer.Screen options={{
                drawerLabel: () => null,
            }} name="test" component={TabNav} />
        </Drawer.Navigator>
    )}`

**Comment by castalonirenz** [comment]
Hi i hope this helps.

i removed DrawerItemList then set <Drawer.Screen> drawLabel to null

```
import * as React from 'react';
import {
createDrawerNavigator, DrawerContentScrollView,
DrawerItemList, DrawerItem
} from '@react-navigation/drawer';
import { Text } from "react-native";
import { TabNav } from '../Tab/Tab';

const Drawer = createDrawerNavigator();

function CustomDrawerContent(props) {
return (
<DrawerContentScrollView {...props}>
{/* <DrawerItemList {...props} /> */}
<Text>SAMPLE</Text>


)}

export const DrawerNav = (props) => {
return (
<Drawer.Navigator drawerContent={CustomDrawerContent} drawerType={"slide"} drawerStyle={{
width: "85%"
}}>
<Drawer.Screen options={{
drawerLabel: () => null,
}} name="test" component={TabNav} />
</Drawer.Navigator>
)}
```

**Comment by an0o0nym** [comment]
Hi, I have looked for solution everywhere. I am using navigation v5 and `()=> null` solution did not work for me either.

I have come up with my own, more dynamic way (I guess) based on my predecessors answers above (and react-navigation [original implementation](https://github.com/react-navigation/react-navigation/blob/main/packages/drawer/src/views/DrawerItemList.tsx) of `DrawerItemList`) and I would like to share it.

```javascript
const CustomDrawer = props => {
  const {state, descriptors, navigation} = props;
  const buildLink = useLinkBuilder();

  return (
    <DrawerContentScrollView {...props}>
      {state.routes.map((route, i) => {
        const isHidden = descriptors[route.key].options?.hidden;
        if (isHidden === true) return null;

        const focused = i === state.index;
        const {
          title,
          drawerLabel,
          drawerIcon,
          drawerActiveTintColor,
          drawerInactiveTintColor,
          drawerActiveBackgroundColor,
          drawerInactiveBackgroundColor,
          drawerLabelStyle,
          drawerItemStyle,
        } = descriptors[route.key].options;

        return (
          <DrawerItem
            key={route.key}
            label={
              drawerLabel !== undefined
                ? drawerLabel
                : title !== undefined
                ? title
                : route.name
            }
            icon={drawerIcon}
            focused={focused}
            activeTintColor={drawerActiveTintColor}
            inactiveTintColor={drawerInactiveTintColor}
            activeBackgroundColor={drawerActiveBackgroundColor}
            inactiveBackgroundColor={drawerInactiveBackgroundColor}
            labelStyle={drawerLabelStyle}
            style={drawerItemStyle}
            to={buildLink(route.name, route.params)}
            onPress={() => {
              navigation.dispatch({
                ...(focused
                  ? DrawerActions.closeDrawer()
                  : CommonActions.navigate(route.name)),
                target: state.key,
              });
            }}
          />
        );
      })}
    </DrawerContentScrollView>
  );
};

export default CustomDrawer;
```

Then all you have to do is use CustomDrawer in Drawer.Navigator and pass  `hidden` option to `Drawer.Screen` like so:

```javascript
<Drawer.Navigator
              initialRouteName={ROUTES.SIGN_IN}
              drawerPosition="right"
              drawerContent={props => <CustomDrawer {...props} />}>
              <Drawer.Screen
                name={ROUTES.SIGN_IN}
                component={SignInContainer}
                options={{headerShown: false, hidden: true}}
              />
              <Drawer.Screen
                name={ROUTES.DASHBOARD}
                component={withHeader(DashboardContainer)}
                options={{headerLeft: false}}
              />
</Drawer.Navigator>
```

I wish there was some way to make this solution work without copy&pasting react-navigation code.

**Comment by JerryHuang2015** [comment]
V6.1 using 
with this error `TypeError: undefined is not an object (evaluating 'focusedRoute.key')`
so I did use this, 
`<Drawer.Screen name="hideme" component={HiddenScreen} options={{drawerItemStyle: { display: 'none' }}}/>`

**Comment by q2kPetrov** [comment]
> 

You just made my day!!! 4 days of reading all over the discussions, testing, trying different approaches, wrote a lot of code... and then Baaaam - {display: none} .... THANK YOU!

**Comment by q2kPetrov** [comment]
> V6.1.5 using with this error `TypeError: undefined is not an object (evaluating 'focusedRoute.key')` so I did use this, `<Drawer.Screen name="hideme" component={HiddenScreen} options={{drawerItemStyle: { display: 'none' }}}/>`

You just made my day!!! 4 days of reading all over the discussions, testing, trying different approaches, wrote a lot of code... and then Baaaam - {display: none} .... THANK YOU!

**Comment by sakshiigoyal** [comment]
> V6.1.5 using with this error `TypeError: undefined is not an object (evaluating 'focusedRoute.key')` so I did use this, `<Drawer.Screen name="hideme" component={HiddenScreen} options={{drawerItemStyle: { display: 'none' }}}/>`

Thank you for the solution!

**Comment by ErickSousa312** [comment]
Olá Estou usando o **react-navigation/drawer V6.6.11**

Eu criei minha própria maneira de fazer uma filtragem nas rotas e gostaria de compartilhar-lá. Deixei o mais simples possível para qualquer pessoa entender.
```javascript
import {
  DrawerContentScrollView,
  DrawerItemList,
} from '@react-navigation/drawer';
import { View, StyleSheet } from 'react-native';
import { Link, useTheme } from '@react-navigation/native';

export default function CustomDrawerContent(props: any) {
  const { colors } = useTheme();

  // Filtrando as rotas
  const filter = props.state.routes.filter(
    (route: any) => route.name !== 'nome da rota que não vai ser exibida',
  );

  // Criando uma cópia dos dados originais substituindo as rotas originais pela filtradas
  const data = {
    ...props,
    state: { ...props.state, routes: filter },
  };

  // Tudo aqui dentro será renderizado no drawer
  return (
    <View style={{ flex: 1 }}>
      <DrawerContentScrollView {...data} }>
        <DrawerItemList {...data} />
      </DrawerContentScrollView>
    </View>
  );
}
``` 

Depois disso importamos esse componente no arquivo _layout.tsx (onde o drawer será usado), como na foto a seguir: 

![image](https://github.com/react-navigation/react-navigation/assets/58636303/ea9bbd48-3b4d-49cd-a594-516617ece21d)

![image](https://github.com/react-navigation/react-navigation/assets/58636303/516556ed-5ce6-44f6-ae02-ea3a549c90ef)

Dentro de _layout.tsx é assim que passa o CustomDrawer para o componente Drawer, por meio da propriedade:

**drawerContent={}**

```javascript
import { Ionicons } from '@expo/vector-icons';
import { GestureHandlerRootView } from 'react-native-gesture-handler';
import { Drawer } from 'expo-router/drawer';
import CustomDrawerContent from '@/components/customDrawer';

export default function RootLayout() {
  return (
    <GestureHandlerRootView style={{ flex: 1 }}>
      <Drawer drawerContent={CustomDrawerContent}>
         
        // Personalizando o item index
        <Drawer.Screen
          name="index"
          options={{
            drawerLabel: 'Página inicial',
            title: 'Página inicial',
            drawerType: 'front',
            drawerIcon: () => <Ionicons name="home" size={20}></Ionicons>,
            drawerLabelStyle: { marginLeft: -15 },
          }}
        />
      </Drawer>
    </GestureHandlerRootView>
  );
}
```

Espero que ajude alguém, Abraços
