### ISSUE TITLE
Start StackNavigator on 2nd Screen

### ISSUE THREAD

**Issue by RubenSandwich** [react-community/react-navigation#796]
I'm trying to start a StackNavigator on the 2nd screen, searching through the docs I can't see a way to do this.

Has anyone figured out a way to set the set the routes for the initalRoute on a StackNavigator?

**Comment by brentvatne** [comment]
I assume you read the [StackNavigatorConfig](https://reactnavigation.org/docs/navigators/stack#StackNavigatorConfig) docs which describe what you seem to be trying to do. If that's not it, please elaborate further on what you need and provide specific code. Also, welcome @RubenSandwich, I remember you from HN! I hope you don't mind that Expo is involved in this project ;P

**Comment by RubenSandwich** [comment]
Hello @brentvatne, nice to see you again. First I can assure you my beef with CRNA considers the technology decisions for that specific project, not the people involved.

Yes, I have and the only thing that jumps out to me is initialRouteParams but after playing with it for a bit it seems that this just sends params to the initial route.

I'll state my problem again as my wording is a bit strange: How would I set the initalRoute for a StackNavigator to be 2 or so deep.

**Comment by brentvatne** [comment]
> I'll state my problem again as my wording is a bit strange: How would I set the initalRoute for a StackNavigator to be 2 or so deep.

Ah gotcha, that makes sense. If the use case is to handle a link, you might want to look into [Deep Linking](https://reactnavigation.org/docs/guides/linking). The code related to that is also instructive for how you could do this manually -- https://github.com/react-community/react-navigation/blob/26b165200fff47603274a235b08da29d2d2dfe4f/src/createNavigationContainer.js#L129-L139

It looks like there is currently no option to set this with an option or prop, that could be useful though! cc @ericvicenti

**Comment by RubenSandwich** [comment]
Thanks @brentvatne. 

I will definitely vouch for this feature. Not only for deep linking sake, but when you ultimately ship React Navigation for Web, which I understand is beyond the scope of v1, this will come in handy for SPA linking to specific routes.

**Comment by brentvatne** [comment]
@RubenSandwich - the docs website uses React Navigation! :)

**Comment by spencercarli** [comment]
Hi! Since this issue has been quiet for a while I'm going to go ahead and close it. If the issue persists in the latest version of React Navigation please re-open!
