### ISSUE TITLE
Linking is working only if app is not running before opening deep link.

### ISSUE THREAD

**Issue by joonhocho** [react-community/react-navigation#798]
Deep linking works if the app was not previously opened before, but it doesn't if the app is open already.

I've investigated a little and it seems that react native's `Linking.addEventListener` is not working properly. Is anybody experiencing the same issue?

Only tested in iOS using real device.

**Comment by mojocakes** [comment]
I'm having the same problem. If the app is already open in the background it gets focussed, but then event listener never gets fired.

Here's the code I'm using
`
Linking.getInitialURL()
    .then(url => {
        _this._handleDeeplink(url)
    })
    .catch(err => {
        console.warn('Deeplinking error', err)
    })

Linking.addListener('url', e => {
    this._handleDeeplink(e.url)
})`

**Comment by joonhocho** [comment]
@mojocakes 
I think I know the problem.
Are you using FacebookSDK or any libraries that uses the following method?
```
- (BOOL)application:(UIApplication *)application
            openURL:(NSURL *)url
            options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options {
```

https://github.com/facebook/react-native/pull/11674

**Comment by mojocakes** [comment]
Yep! I'm using that exact snippet taken from the FacebookSDK setup docs.
Do you know if there's a workaround for this issue?

**Comment by joonhocho** [comment]
@mojocakes 
```
  if ([RCTLinkingManager application:application
                             openURL:url
                   sourceApplication:nil
                          annotation:nil]) {
    return YES;
  }
```
For now, I just put the above code inside the `openURL with options` function.

**Comment by joonhocho** [comment]
Closing as this is rather react-native issue.

**Comment by mojocakes** [comment]
Thanks @joonhocho this solved it for me!

**Comment by joonhocho** [comment]
@mojocakes glad it helped!

**Comment by tuna123** [comment]
@mojocakes  can you provide code snippet for _handleDeeplink function?

**Comment by koenpunt** [comment]
If you're using Universal Links you also have to add the following method to the `AppDelegate.m`:

```objc
- (BOOL)application:(UIApplication *)application continueUserActivity:(NSUserActivity *)userActivity
 restorationHandler:(void (^)(NSArray * _Nullable))restorationHandler
{
  return [RCTLinkingManager application:application
                   continueUserActivity:userActivity
                     restorationHandler:restorationHandler];
}
```

**Comment by xavimb** [comment]
@joonhocho I had to add an extra check to your solution. When logging in with Facebook, RCTLinkingManager catches the event instead of passing it to the Facebook handler. So I have this:
```
NSString* stringURL = [url absoluteString];
if (([stringURL hasPrefix:@"myapp://"] == YES) &&
      ([RCTLinkingManager application:application
                             openURL:url
                   sourceApplication:nil
                          annotation:nil] == YES)) {
    return YES;
}
```

**Comment by igorarkhipenko** [comment]
@joonhocho I'm facing right the same issue right now. Could you share with me your solution please?

**Comment by joonhocho** [comment]
@igorarkhipenko I have already shared my solution (see above comment).
I haven't looked at deep linking since then, so there is a good chance that my previous code is outdated and not working with current version. If I get back to working on deep linking again, then I will share new code here.

**Comment by igorarkhipenko** [comment]
@joonhocho oh, I thought it was related to FacebookSDK library. Thank you, I'll give it a try

**Comment by jinxac** [comment]
Thanks @joonhocho was debugging the same thing and your comment really helped.

**Comment by bhatti-waqas** [comment]
You can work around with such issues using this plugin.
https://github.com/luisfcofv/react-native-deep-linking

**Comment by tomazahlin** [comment]
The above solution worked for me by adding the code snippet to AppDelegate.m. Don't forget about importing the RCTLinkingManager.h:

#import <React/RCTLinkingManager.h>

**Comment by a-koka** [comment]
Thanks for the fix @xavimb. Checking the scheme was definitely helpful. Why the second check though?

`[RCTLinkingManager application:application
                             openURL:url
                   sourceApplication:nil
                          annotation:nil] == YES`

Didn't seem necessary for my case.

**Comment by xavimb** [comment]
@a-koka You are right, you might not need it. You will only need that second check if you are using other handlers in the same method, like the Facebook handler.

**Comment by a-koka** [comment]
Thanks for the prompt response @xavimb. I am indeed using Facebook and everything seemed to work fine for both Facebook and myapp schemes which is why I was confused. I'm not super proficient at Objective-C and thus don't understand the statement itself. Just trying to understand what the goal for it is.

**Comment by DavitVosk** [comment]
@joonhocho Thanks. Your solution is awesome. Just as an addition: only one openURL method can be defined, so if you have multiple listeners which should be defined (for instance if you have both Google and Facebook OAuth), you must combine them into a single function. Cheers

**Comment by jinxac** [comment]
@DavitVosk yeah even i was stuck in this so tried on something like this:-

```
- (BOOL)application:(UIApplication *)application
            openURL:(NSURL *)url
            options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options {
  if ( [[GIDSignIn sharedInstance] handleURL:url
                                     sourceApplication:options[UIApplicationOpenURLOptionsSourceApplicationKey]
                                  annotation:options[UIApplicationOpenURLOptionsAnnotationKey]] ) {
    return YES;
  }
  
  if ([[FBSDKApplicationDelegate sharedInstance] application:application
      openURL:url
      sourceApplication:options[UIApplicationOpenURLOptionsSourceApplicationKey]
      annotation:options[UIApplicationOpenURLOptionsAnnotationKey]]) {
    return YES;
  }
  
  return [RCTLinkingManager application:application
                                openURL:url
                      sourceApplication:nil
                             annotation:nil];
}

```

**Comment by malithjkmt** [comment]
You can use something clear like below

     - (BOOL)application:(UIApplication *)application
            openURL:(NSURL *)url
            options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options {
  
      BOOL instaHandled = [RCTLinkingManager application:application openURL:url options:options];
   
      BOOL FbHandled = [[FBSDKApplicationDelegate sharedInstance] application:application
                                                                openURL:url
                                      sourceApplication:options[UIApplicationOpenURLOptionsSourceApplicationKey]
                                                             annotation:options[UIApplicationOpenURLOptionsAnnotationKey]
                  ];

      return FbHandled || instaHandled;
    }

**Comment by a-koka** [comment]
Look into branch.io. Linking is a challenging task when you account for links being opened on iOS, Android and web including the scenarios of app being open, closed, minimized etc.. Branch takes care of all of this and it's free for small projects.

**Comment by hugoh1995** [comment]
I get the following error when adding the line of code that's supposed to solve this issue: 

> Cannot read property 'apply' of undefined

Any idea how to fix this?

**Comment by hugoh1995** [comment]
@joonhocho could you please provide the entire snippet? I can't figure out where to put the code exactly.

**Comment by 337240552** [comment]
@mojocakes give the right answer

``` javascript
componentDidMount() {
    Linking.getInitialURL()
        .then(url => {
            _this._handleDeeplink(url)
        })
        .catch(err => {
            console.warn('Deeplinking error', err)
        })

    Linking.addListener('url', e => {
        this._handleDeeplink(e.url)
    })
}
```
addListener for activity onNewIntent event, and getInitialURL for activity onCreate event

ReactInstanceManager
``` java
  public void onNewIntent(Intent intent) {
    UiThreadUtil.assertOnUiThread();
    ReactContext currentContext = getCurrentReactContext();
    if (currentContext == null) {
      FLog.w(ReactConstants.TAG, "Instance detached from instance manager");
    } else {
      String action = intent.getAction();
      Uri uri = intent.getData();

      if (Intent.ACTION_VIEW.equals(action) && uri != null) {
        DeviceEventManagerModule deviceEventManagerModule =
          currentContext.getNativeModule(DeviceEventManagerModule.class);
        deviceEventManagerModule.emitNewIntentReceived(uri);
      }

      currentContext.onNewIntent(mCurrentActivity, intent);
    }
  }

```

Linking.js mapping Java source (IntentModule.java)
``` java
@ReactMethod
  public void getInitialURL(Promise promise) {
    try {
      Activity currentActivity = getCurrentActivity();
      String initialURL = null;

      if (currentActivity != null) {
        Intent intent = currentActivity.getIntent();
        String action = intent.getAction();
        Uri uri = intent.getData();

        if (Intent.ACTION_VIEW.equals(action) && uri != null) {
          initialURL = uri.toString();
        }
      }

      promise.resolve(initialURL);
    } catch (Exception e) {
      promise.reject(new JSApplicationIllegalArgumentException(
          "Could not get the initial URL : " + e.getMessage()));
    }
  }
```

**Comment by khanhhaduc** [comment]
@337240552 thank you!

**Comment by AnandKuhar** [comment]
I m facing same problem on android. when my app is in background, deep linking doesn't work.
Can anyone help me ??

**Comment by AnandKuhar** [comment]
It's working for me now

**Comment by codesinghanoop** [comment]
@AnandKuhar How you get this work ?

**Comment by Darkilen** [comment]
@AnandKuhar How did you fix this ? I'm also still get this issue.

**Comment by youssefatti** [comment]
> It's working for me now

Hi,
How did you make it?
thx

**Comment by youssefatti** [comment]
@AnandKuhar?

**Comment by Umasankar512** [comment]
@AnandKuhar How did you solve it?

**Comment by anurag-rapidue** [comment]
https://stackoverflow.com/questions/53256246/deep-linking-not-working-when-app-is-in-background-state-react-native

**Comment by jerodb** [comment]
I was facing same problem, now it's working perfectly.
1) Implement RN Linking API. Follow the doc: https://facebook.github.io/react-native/docs/linking.html
2) Turn RN "Debug js remotely" off. There is some bug there that makes Linking API to fail.
3) If it works when the app is closed (with Linking.getInitialURL) but doesn't work when the app is on the background (with Linking.addEventListener) make sure you implemented Linking.addEventListener and Linking.removeEventListener (when the component unmounts) correctly. I was implementing it in the wrong component and I was removing the listener by mistake, so when the app was in the background it was not listening for deeplinks opening the app.

**Comment by lukejsimonetti** [comment]
> 1. Implement RN Linking API. Follow the doc: https://facebook.github.io/react-native/docs/linking.html
> 2. Turn RN "Debug js remotely" off. There is some bug there that makes Linking API to fail.
> 3. If it works when the app is closed (with Linking.getInitialURL) but doesn't work when the app is on the background (with Linking.addEventListener) make sure you implemented Linking.addEventListener and Linking.removeEventListener (when the component unmounts) correctly. I was implementing it in the wrong component and I was removing the listener by mistake, so when the app was in the background it was not listening for deeplinks opening the app.

You're completely spot on about point #2 here. **Remote debugging jacks up the Linking API.** As soon as I turned it off the links worked (regardless if app was previously open or closed).

**Comment by pragneshpj** [comment]
This is my stack. 
welcomescreen -> homescreen -> profilescreen 
- when app is not in background and try to open home screen but it alway open welcomescreen. 
- when app in background then it will redirect to homescreen. 

get value from Linking.getInitialURL(); is myapp://home but it will not redirect to homescreen.

can anyone help me

**Comment by lonecruisader** [comment]
this issue also occurs when you have duplicate screen names in the navigation container one nested inside another.

**Comment by anabeatrizzz** [comment]
I have the opposite issue. When the app is not in the background and I try to open it with a link, I get a crash.

**Comment by Janak-Nirmal** [comment]
> If you're using Universal Links you also have to add the following method to the `AppDelegate.m`:
> 
> ```objc
> - (BOOL)application:(UIApplication *)application continueUserActivity:(NSUserActivity *)userActivity
>  restorationHandler:(void (^)(NSArray * _Nullable))restorationHandler
> {
>   return [RCTLinkingManager application:application
>                    continueUserActivity:userActivity
>                      restorationHandler:restorationHandler];
> }
> ```

This is the perfect solution when user comes back with app in the background. i.e. app is already opened.

**Comment by sahilgoyalajm** [comment]
@joonhocho it's still not working when using FBSDK. Could you please help me resolve it?
```
- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url options:(NSDictionary<NSString *,id> *)options {
   // Log the incoming URL
   NSLog(@"[AppDelegate] Received URL: %@", [url absoluteString]);
    if ([RCTLinkingManager application:application
                             openURL:url
                   sourceApplication:nil
                          annotation:nil]) {
    NSLog(@"[AppDelegate] URL handled by RCTLinkingManager: %@", [url absoluteString]);
    return YES;
  }

  NSString* stringURL = [url absoluteString];

  // Log when the URL is being handled by Facebook, Google Sign-in, or LinkingManager
  NSLog(@"[AppDelegate] URL not handled by RCTLinkingManager, passing to other handlers: %@", stringURL);
  return [[FBSDKApplicationDelegate sharedInstance] application:application openURL:url options:options] || [RNGoogleSignin application:application openURL:url options:options] || [RCTLinkingManager application:application openURL:url options:options];
}

- (BOOL)application:(UIApplication *)application continueUserActivity:(NSUserActivity *)userActivity
 restorationHandler:(void (^)(NSArray * _Nullable))restorationHandler
{
  return [RCTLinkingManager application:application
                   continueUserActivity:userActivity
                     restorationHandler:restorationHandler];
}
```
