### ISSUE TITLE
How to implement double click android back to exit app

### ISSUE THREAD

**Issue by Yorkey** [react-community/react-navigation#799]
I have read the docs,but does not find any way to control the android back button behavior.
So I also read the source code.
In createNavigationContainer.js
componentDidMount() {
...
        this.subs = BackAndroid.addEventListener('backPress', () => 
          this.dispatch(NavigationActions.back())
        );
...
}

dispatch = (action: NavigationAction) => {
      const { state } = this;
      if (!this._isStateful()) {
        return false;
      }
      const nav = Component.router.getStateForAction(action, state.nav);

      if (nav && nav !== state.nav) {
        if (console.group) {
          console.group('Navigation Dispatch: ');
          console.log('Action: ', action);
          console.log('New State: ', nav);
          console.log('Last State: ', state.nav);
          console.groupEnd();
        } else {
          console.log('Navigation Dispatch: ', { action, newState: nav, lastState: state.nav });
        }
        this.setState({ nav });
        return true;
      }
      return false;
    };

when I follow the docs,override Component.router.getStateForAction, reutrn null in some condition to prevent back navigation,but  "BackAndroid.addEventListener('backPress', () => 
          this.dispatch(NavigationActions.back())
        );" will return false. This cause the app exit.

**Comment by Kennytian** [comment]
+1

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!

**Comment by rgabs** [comment]
@Yorkey Please have a look at this module. I hope it solves your problem. https://www.npmjs.com/package/exit-on-double-back

**Comment by bashirpour** [comment]
https://stackoverflow.com/questions/52253072/react-native-double-back-press-to-exit-app/52253073#52253073

**Comment by amirhayati** [comment]
for react native v 0.61.0 I use this solution:
```
import React ,{useEffect, useState}from 'react'
import {BackHandler} from 'react-native'

const Main = () => {
    const [exitApp,SETexitApp]=useState(false)
    
    const backAction = () => {
        if(exitApp==false){
            SETexitApp(true);
            Toast.show({
                text: 'back click for exit',
                type:'warning',
                duration:1500,
                style:[styles.toast],
                textStyle:[styles.toast_text],
            }) 
        }
        else if(exitApp==true){
            BackHandler.exitApp()
        }

        setTimeout(()=>{
            SETexitApp(false)
        }, 1500);
        return true;
    };
    useEffect(() =>
    {
        const backHandler = BackHandler.addEventListener(
            "hardwareBackPress",
            backAction
        );
        return () => backHandler.remove();
    },[exitApp]) 

}

```
