### ISSUE TITLE
Allow screen option of `screenStyle` to for StackNavigator

### ISSUE THREAD

**Issue by ericvicenti** [react-community/react-navigation#8]
I think this would will be useful for changing the background color of a screen

**Comment by brunolemos** [comment]
Not sure if it's the same thing, but also a way to change the backgroundColor of the iOS rootView on runtime (and the android equivalent).

**Comment by ericvicenti** [comment]
Ok, closing this because `cardStyle` was implemented in #106.

@brunolemos, you can currently change the root view background by wrapping your app navigator in a view that has a background color set on it.

**Comment by brunolemos** [comment]
@ericvicenti if I understood you correctly, that would change the first view in the react hierarchy, but not the `rootView` from iOS, the one I set with this Obj-C code:
`rootView.backgroundColor = [UIColor colorWithRed:0.29 green:0.83 blue:0.71 alpha:1.0];`

If they have different background colors, which is my case, that would be very noticeable when you rotate the screen, for example:

[![rn-rootview.gif](https://s30.postimg.org/bnky8matd/rn_rootview.gif)](https://postimg.org/image/wx8kjgr3x/)

**Comment by ericvicenti** [comment]
Oh, hmm. You may need to jump into the ObjC to handle this case

**Comment by brunolemos** [comment]
I used to use `react-native-navigation` from wix, they have a `screenBackgroundColor` property that does this job, so I got used to it. (https://github.com/wix/react-native-navigation/pull/437)

But yes, I'll probably have to create a bridge to be able to change it dynamically independently of the navigation library.

**Comment by ericvicenti** [comment]
Ah. It may make sense to add that functionality to core as well. I can see that it may be important to adjust that

**Comment by sibelius** [comment]
I think it should be useful to modify this backgroundColor https://github.com/react-community/react-navigation/blob/e2f5e7fd494a9242edf1951e2398a1d1adf5b1ed/src/views/Card.js#L51

**Comment by koenpunt** [comment]
> I think it should be useful to modify this backgroundColor

This is possible using the `cardStyle` option:

https://github.com/react-community/react-navigation/commit/a64eb46c9ced9c84c11a53e1d25cd1da08a36804

**Comment by kelset** [comment]
Closing this since as @koenpunt said it's possible via `cardStyle`.
