### ISSUE TITLE
How does react navigation support android bottom navigation?

### ISSUE THREAD

**Issue by hellomaya** [react-community/react-navigation#801]
Hi,

I have read the react navigation docs, and didn't find anything to make an android bottom navigation, it do have tabNavigator, but it's still on the top of the page in android.

As long as Android 6+ support bottom navigation pattern, here https://material.io/guidelines/components/bottom-navigation.html, and there is a good android lib here, https://github.com/roughike/BottomBar

How does react native to support an android bottom navigation?

**Comment by Ehesp** [comment]
```
const Tabs = TabNavigator({
  // Screens
}, {
  tabBarPosition: 'bottom',
});
```

**Comment by hellomaya** [comment]
@Ehesp

Thank you for your help. I will try it more!!

**Comment by AlanFoster** [comment]
@hellomaya Any luck with this? Are good to close the issue? :)

**Comment by eduplus** [comment]
This just moves tabs to the bottom, not replicate bottom navigation UI/UX and behavior, so it is not an adequate solution. I think there should be navigator that would result into having Bottom Navigation for both platforms as it is now been supported pattern for both.

In the meanwhile, any ideas / workaround available?

**Comment by AlanFoster** [comment]
@eduplus Could you elaborate further on the functionality you desire? A reference sreenshot of the functionality you expected would be greatly appreciated :+1:

**Comment by eduplus** [comment]
I looked a little closer and realized that there is tabBarComponent, which can be changed as well. So with this I think it actually works like it: 

  {
    tabBarComponent: TabView.TabBarBottom
    tabBarPosition: 'bottom'
  }

Key is that tabBarComponent default TabBarBottom on iOS, but TabBarTop on Android. So it was not just the positioning, but also what component was used. So need to define that to get the correct behavior.

**Comment by bramvbilsen** [comment]
Hi eduplus,
I figured the same thing but where to import the TabView from? I just can't find it :/

**Comment by fdnhkj** [comment]
@bramvbilsen `import {TabView} from 'react-native`

I was trying to achieve the same few days ago.
And after reading the docs, I thought I would have to only change tabBarPosition to `'bottom'`.

@eduplus is right, we need to change tabBarComponent and tabBarPosition.
IMO, It is not that obvious. Maybe we can adapt docs to reflect this.

**Comment by jonasb** [comment]
Here are some other settings to make TabNavigator work more like Material Design Bottom Navigation. There are some remaining tweaks like reacting to the user selecting the active tab.
```
tabBarComponent: TabView.TabBarBottom,
tabBarPosition: 'bottom',
swipeEnabled: false,
animationEnabled: false,
backBehavior: 'none',
```

**Comment by charan1983** [comment]
@jonasb I have tried both the options but still the tab bar is displayed on the top instead of bottom. Can you please let me know what am I missing?

```
export const Tabs = TabNavigator({
       latest: {
    screen: Main,
    navigationOptions: {
      tabBarLabel: 'Latest',
    },
  },
  account: {
    screen: Account,
    navigationOptions: {
      tabBarLabel: 'Me',
    },
  },
},{
  tabBarOptions:{
    tabBarComponent: TabBarBottom,
    tabBarPosition: 'bottom',
  }
});
```

**Comment by lison16** [comment]
I set 
tabBarOptions:{
    tabBarComponent: TabView.TabBarBottom,
    tabBarPosition: 'bottom',
}
but there's no effect , the tabbar is still at screen top

**Comment by asafyish** [comment]
@lison16 You shouldn't use 'tabBarOptions':

```js
export const Tabs = TabNavigator({
       latest: {
    screen: Main,
    navigationOptions: {
      tabBarLabel: 'Latest',
    },
  },
  account: {
    screen: Account,
    navigationOptions: {
      tabBarLabel: 'Me',
    },
  },
},{
    tabBarComponent: TabBarBottom,
    tabBarPosition: 'bottom',
});
```

**Comment by smitthakkar1** [comment]
I have tried all the suggestions but still not working. Can anyone please help me to put tabs on the bottom? My code is as below: 

import React from 'react';
import { TabNavigator, TabView, TabBarBottom } from 'react-navigation';
import Home from '../components/Home';
import Profile from '../components/Profile';

export const Tabs = TabNavigator({
    Home:{
        screen: Home,
        navigationOptions:{
          tabBarLabel: 'Home',
        },
    },
    Profile:{
        screen: Profile,
    },
});

**Comment by RETFU** [comment]
@smitthakkar1 work for me

```javascript
import React from 'react';
import {TabNavigator, TabBarBottom} from 'react-navigation';
import MapScreen from './X/MapScreen';
import ListScreen from './X/ListScreen';

const Tabs = new TabNavigator(
    {
        Map: {
            screen: MapScreen,
        },
        List: {
            screen: ListScreen,
        },
    },
    {
        tabBarOptions: {
            activeTintColor: 'dodgerblue',
        },
        tabBarComponent: TabBarBottom,
        tabBarPosition: 'bottom',
    }
);
```

**Comment by bobbycao60** [comment]
f

**Comment by brentvatne** [comment]
this will hopefully become the default soon, working on it

**Comment by satya164** [comment]
Progress: https://github.com/react-navigation/react-navigation-tabs

**Comment by brentvatne** [comment]
also see https://v2.reactnavigation.org/docs/api-reference.html for the new navigator types
