### ISSUE TITLE
Changelog for 1.0.0 beta 7

### ISSUE THREAD

**Issue by nonameolsson** [react-community/react-navigation#806]
Is there a changelog somwhere of beta 7?
[https://github.com/react-community/react-navigation/releases/tag/v1.0.0-beta.7](https://github.com/react-community/react-navigation/releases/tag/v1.0.0-beta.7)

**Comment by zoontek** [comment]
Any news on this? Can somebody else can write it?

**Comment by grabbou** [comment]
We are likely going to skip it because there's `v8` to be released in next days. Here's a list of commits in `v7`, just a couple of them -> https://github.com/react-community/react-navigation/compare/v1.0.0-beta.6...v1.0.0-beta.7
