### ISSUE TITLE
Accessing navigator props outside of navigator?

### ISSUE THREAD

**Issue by rendomnet** [react-community/react-navigation#807]
How can I access props from specific Navigator from otside of this Navigator?

```
<StackNavigator1>
page1: {
 screeen: Page1
}

<StackNavigator2>
 page2: {
 screeen: Page2
}

</Page1>
 <Text>**Display StackNavigator2 routName** <Text>
 <StackNavigator2/>
</Page1>

```

**Comment by Ehesp** [comment]
I don't believe this is possible (could be wrong), but Redux would be something to handle this.

**Comment by spencercarli** [comment]
Might be tricky but you could access a [ref to it](https://reactnavigation.org/docs/navigators/#Calling-Navigate-on-Top-Level-Component)
