### ISSUE TITLE
Can't install react-navigation

### ISSUE THREAD

**Issue by ariona** [react-community/react-navigation#808]
```
npm WARN saveError Unexpected token }
/Users/someone/Documents/app
└── react-navigation@0.0.0 

npm WARN EJSONPARSE Failed to parse json
npm WARN EJSONPARSE Trailing comma in object at 13:3
npm WARN EJSONPARSE   },
npm WARN EJSONPARSE   ^
```

**Comment by AlanFoster** [comment]
@ariona Is this still an issue with the latest version `1.0.0-beta.7`?

In your error it shows the version number `react-navigation@0.0.0`

**Comment by ariona** [comment]
Yeah, i need to specify the version when installing this. `npm install --save react-navigation@1.0.0-beta.7` then it'll install. If i am not then it will install empty project instead (0.0.0)
