### ISSUE TITLE
Change Tab Title Case

### ISSUE THREAD

**Issue by ariona** [react-community/react-navigation#814]
How can i change the tab title case to Lowercase or capitalize? I think it should stay the same with navigation options

**Comment by ariona** [comment]
Found the solution, Just pass Text Component as label and style with your stylesheet
```js
tabBar: {
	label: <Text style={styles.tabLabel}>Favourite</Text>,
}
```

**Comment by connordear** [comment]
Hey I'm still pretty new to navigation in react-native, I'm just wondering where you are putting that? I'm also trying to get the tab label case to lowercase instead of all uppercase.

**Comment by ariona** [comment]
@connordear you can write it in each Tab screen class declaration. for example:

```js
class TabScreenExample extends Component {
  static navigationOptions = {
    tabBarOptions: {
      upperCaseLabel: false
    }
  };
  ...
```

refer to this docs https://reactnavigation.org/docs/navigators/tab

**Comment by connordear** [comment]
Ahh I can't believe I missed that, thank you!

**Comment by smitthakkar1** [comment]
What about TabBarBottom? It's only working in TabBarTop.
not working with TabBarBottom

**Comment by julestruong** [comment]
I second @smitthakkar1 , why is that only enable for TabBarTop and not the bottom one ?

**Comment by esipavicius** [comment]
Right now: 
tabBarLabel: <Text>Registration</Text>

**Comment by abidjamil** [comment]
labelStyle = { text-transform: capitalize }

**Comment by kienvanba** [comment]
what work for me is:

```
tabBarOptions={{
  labelStyle: { textTransform: 'none' },
}}
```

**Comment by abidjamil** [comment]
Yes because, Navigator Apply textTransform: Captial, and by apply none, it will discard transformation property

**Comment by rewaant** [comment]
> labelStyle = { text-transform: capitalize }

This works perfect for react navigation v5 (createMaterialTopTabNavigator)

**Comment by rewaant** [comment]
> what work for me is:
> 
> ```
> tabBarOptions= {{
>   labelStyle: { textTransform: 'none' }
> }}
> ```

This works perfect for react navigation v5 (createMaterialTopTabNavigator)

**Comment by Thilanka-97** [comment]
> what work for me is:
> 
> ```
> tabBarOptions= {{
>   labelStyle: { textTransform: 'none' }
> }}
> ```

This works for me.Thanks

**Comment by aryanm5** [comment]
This works in React Navigation v6:
```
<Tab.Navigator
        screenOptions={{
            tabBarLabelStyle: { textTransform: 'none' },
        }}
>
```

**Comment by goxr3plus** [comment]
@aryanm5  Thanks a lot your solutions worked for me

**Comment by bhagya88** [comment]
`renderLabel={({ route, color }) => <Typography color={color as TypographyColor}>{route.title}</Typography>}`

This fixed the issue for me.
