### ISSUE TITLE
Header buttons disappear when navigating to new screen in iOS

### ISSUE THREAD

**Issue by travisday** [react-community/react-navigation#816]
I am navigating to a new screen with a custom button on my Nav Bar. I set the screen to have a left and right button but they do not show up in iOS, they do however show up on Android.

here is the code:
```static navigationOptions = {
    header: ({state, setParams, navigate, goBack}) => ({
      left: <HeaderButton onPress={() => goBack(null)} name='arrow-left' />,
      right: <HeaderButton onPress={() => goBack(null)} name='tune' />
    })
  }
```

and here is the result:
![img_0509](https://cloud.githubusercontent.com/assets/14930262/24313210/36c8c2ec-1099-11e7-810b-27bff3618e47.PNG)

**Comment by spencercarli** [comment]
The API changed slightly. [Here's the new way](https://reactnavigation.org/docs/navigators/stack#headerLeft)
