### ISSUE TITLE
Typings

### ISSUE THREAD

**Issue by uDevel** [react-community/react-navigation#817]
Does anyone know if there is Typing created for this awesome lib?
If not, is there a plan for it?

Thanks!

**Comment by ericvicenti** [comment]
What is a typing?

**Comment by uDevel** [comment]
It is for people who uses Typescript for react native.
Wiki can explain better than I can: https://en.wikipedia.org/wiki/TypeScript#Declaration_files
Most popular libs have typing for the typescript developers.

You can see some examples of typings here https://github.com/DefinitelyTyped/DefinitelyTyped
This repo have over 1000 typings.

**Comment by shrutic** [comment]
Why is this closed? I think this is a very important library for which typings should be created

**Comment by ericvicenti** [comment]
For feature requests that are not on our roadmap, we close the issue. That way we can focus on the active bugs that people are facing.

Feel free to add TS types to the library, if it is done in a nice way, we will happily accept the pull request.

But keep in mind that things are still changing, even with the flow types that are used by the library authors. (See here for example, where some major changes are happening:  https://github.com/react-community/react-navigation/pull/984)

**Comment by jnbt** [comment]
@ericvicenti I totally agree in postponing the TS types until the API has stabilized. After this I'm willing to provide a TS declaration file and tests.

**Comment by shrutic** [comment]
I think given that the default navigator has been removed from react-native is an indicator that this API has stabilized enough. I think it is high time the type script community is provided with a typings for this library
