### ISSUE TITLE
gesturesEnabled config recently removed from CardStack

### ISSUE THREAD

**Issue by chromakode** [react-community/react-navigation#818]
It appears that https://github.com/react-community/react-navigation/commit/11cab8eab62b6ca1c2a0445f30a9d0dc75458e2e removed the ability to enabled/disable gestures for a stack ([documented here](https://github.com/react-community/react-navigation/blob/71e8c95b340503631ff6701a95637b569ea50229/docs/api/navigators/StackNavigator.md)).

**Comment by brunolemos** [comment]
I can confirm `gesturesEnabled ` is not working. cc @skevy

**Comment by brunolemos** [comment]
Submitted a PR fix: https://github.com/react-community/react-navigation/pull/886
