### ISSUE TITLE
Back button on iOS should be labeled with the title of the previous screen

### ISSUE THREAD

**Issue by rpowelll** [react-community/react-navigation#82]
Like it says on the tin. In addition to the leftwards-facing chevron, the back button in a StackNavigator's navigation bar should include the title of the previous screen in keeping with iOS UI conventions. It might also be a good idea to make this title customisable for screens with overly-long titles.

**Comment by satya164** [comment]
Want to send a PR?

**Comment by grabbou** [comment]
Since it's a part of my work on back-button (size and layout), I'll take that one as well.
