### ISSUE TITLE
Route 'xyz' should declare a screen

### ISSUE THREAD

**Issue by MarcelBlockchain** [react-community/react-navigation#821]
Hello folks,

I applied this tutorial: [react-navigation with complete redux state management, tab-bar, and multiple navigators
](https://medium.com/@parkerdan/react-navigation-with-complete-redux-state-management-tab-bar-and-multiple-navigators-ed30a69d9a4d#.neh4bs7rz) from @parkerdan / [Sample-Navigation](https://github.com/parkerdan/SampleNavigation)

Getting this error: Route 'TabOneNavigation' should declare a screen
and tried all mentioned fixes from:
#571 
#163 

When I replace the 
```
import NavigatorTabOne from '../tabOne/navigationConfiguration';

const routeConfiguration = {
  TabOneNavigation: { screen: NavigatorTabOne } //Reference to a StackNavigator
};
```
with:
```
import TabOneScreenOne from '../tabOne/views/TabOneNavigation';

const routeConfiguration = {
  TabOneNavigation: { screen: TabOneScreenOne } //Actual Screen
```
it works. 
I guess something is wrong with the import and the order when which screen is being rendered, according to all people who have the same issue. It wants to display it, but it's not available yet.
Or something went wrong with the 

`export const NavigatorTabOne = StackNavigator(routeConfiguration, stackNavigatorConfiguration); `

of TabOne navigationConfiguration.js

Any tipps?
Thanks a lot for helping!

![screen shot 2017-03-24 at 10 02 46 pm](https://cloud.githubusercontent.com/assets/26665436/24319314/b5c620a0-10dd-11e7-941f-44ab811a1ba4.png)

My Code: 
navigationConfiguration.js in Folder "tabBar"

```import { TabNavigator } from 'react-navigation';
import NavigatorTabOne from '../tabOne/navigationConfiguration';
import NavigatorTabTwo from '../tabTwo/navigationConfiguration';

const routeConfiguration = {
  TabOneNavigation: { screen: NavigatorTabOne },
  TabTwoNavigation: { screen: NavigatorTabTwo }
};

const tabBarConfiguration = {
  tabBarOptions: {
    //tint color is passed to text and icons if enabled
    // on the tab bar
    activeTintColor: 'white',
    inactiveTintColor: 'blue',
    //background Color is for the tab component
    activeBackgroundColor: 'blue',
    inactiveBackgroundColor: 'white',
  }
};

export const TabBar = TabNavigator(routeConfiguration, tabBarConfiguration);
```
navigationConfiguration.js in Folder "tabOne"

```import { StackNavigator } from 'react-navigation';

import TabOneScreenOne from './views/TabOneScreenOne';
import TabOneScreenTwo from './views/TabOneScreenTwo';

const routeConfiguration = {
  TabOneScreenOne: { screen: TabOneScreenOne },
  TabOneScreenTwo: { screen: TabOneScreenTwo }
};

// disabling the header for now
const stackNavigatorConfiguration = {
  headerMode: 'none',
  initialRouteName: 'TabOneScreenOne'
};

export const NavigatorTabOne = StackNavigator(routeConfiguration, stackNavigatorConfiguration);
```

My Reducers: 

```
export default combineReducers({
  tabBar: tabBarReducer,
  tabOne: (state, action) => NavigatorTabOne.router.getStateForAction(action, state),
  tabTwo: (state, action) => NavigatorTabTwo.router.getStateForAction(action, state)
  //getStateForAction = helper method, wires up route rand handles
  // all navigation Logic

});
```

My System:

  "dependencies": {
    "firebase": "^3.7.3",
    "native-base": "^2.0.13",
    "react": "~15.4.1",
    "react-native": "0.42.3",
    "react-native-elements": "^0.10.0",
    "react-native-sglistview": "^0.3.10",
    "react-native-vector-icons": "^4.0.0",
    "react-navigation": "^1.0.0-beta.7",
    "react-redux": "^5.0.3",
    "redux": "^3.6.0",
    "redux-persist": "^4.5.0",
    "redux-thunk": "^2.2.0"
  },
  "devDependencies": {
    "babel-jest": "19.0.0",
    "babel-preset-react-native": "1.9.1",
    "eslint-config-rallycoding": "^3.2.0",
    "jest": "19.0.2",
    "react-test-renderer": "~15.4.1"
  },
  "jest": {
    "preset": "react-native"
  }

**Comment by parkerdan** [comment]
@MarcelBlockchain, I literally just grabbed a new laptop, cloned that repo, npm install, ran xCode, and it was all good...

**Comment by MarcelBlockchain** [comment]
Can you post your dependencies? I can't figure out where the problem is

**Comment by parkerdan** [comment]
The error message you are getting is spot-on.

From looking at your code, it appears as though you missed a step from the article...this file:

https://github.com/parkerdan/SampleNavigation/blob/master/app/tabOne/views/TabOneNavigation.js

You are trying to declare a screen in your router with just a configuration:
`import NavigatorTabOne from '../tabOne/navigationConfiguration';`

When you need to render the navigator after you configure it, then import that as a screen with:
`import TabOneNavigation from '../tabOne/views/TabOneNavigation'`

**Comment by MarcelBlockchain** [comment]
EDIT, it worked! now, the next morning, I found out I probably messed up with different names and imports and updated all dependencies to the latest version. 
Happy Coding!

**Comment by varunchandran333** [comment]
Why this issue closed.I am having the same??
