### ISSUE TITLE
popN() or popToTop() possible? 

### ISSUE THREAD

**Issue by edo1493** [react-community/react-navigation#825]
Hi guys, 
I was wondering if the current behaviour was possible, cause I can't really understand it from the docs. I have tried with goBack() or by dispatching an action, but it doesn't seem to work. 

"Optionally provide a key, which specifies the route to go back from." 

This is not clear. : (

**Comment by aimak** [comment]
This is probably related to https://github.com/react-community/react-navigation/issues/285

**Comment by edo1493** [comment]
@aimak I wanted to ping the contributors. : )

**Comment by grabbou** [comment]
Closing in favour of #285. You can set `goBack({ key: '' })` to navigate to a specific route.

**Comment by zhaiyjgithub** [comment]
@grabbou Hi! goBack({ key: '' }) is not working for me. My code is here: 
` const {goBack} = this.props.navigation
		this.props.navigation.goBack({key: 'GuideViewController'})
`
`GuideViewController: {
			screen: GuideViewController,
		},
		LoginViewController: {
			screen: LoginViewController,
		},
		ForgotPasswordViewController: {
			screen: ForgotPasswordViewController
		},`


I have three screen: GuideViewController -- > LoginViewController --> ForgotPasswordViewController.
Thx!
