### ISSUE TITLE
Header too high on Android 

### ISSUE THREAD

**Issue by babsonmatt** [react-community/react-navigation#826]
Anyone else experiencing this? I have a header with a title and a right button and its something like 10 px too high.  No issues with iOS though.

**Comment by nihgwu** [comment]
That's designed to according to the Android Spec, not a bug, you can override the default style

**Comment by babsonmatt** [comment]
@nihgwu I'll have to attach a pic just to make sure, right now the right button is cut off mid way - thats intended? Apologies if so.

**Comment by stanonyime** [comment]
@nihgwu how does one override the style for the header container? I tried styling the screen header but it had no effect on the positioning

**Comment by AlanFoster** [comment]
@babsonmatt A picture would definitely help clarify this issue :+1:

**Comment by babsonmatt** [comment]
@AlanFoster apologies for the delay! - this is with the android emulator (pixel xl)

![image](https://cloud.githubusercontent.com/assets/853220/26042820/43e56788-3906-11e7-8e81-4cde4b44cebe.png)

**Comment by dantman** [comment]
@babsonmatt That's not "too high". You're using Expo, which implicitly sets the StatusBar to translucent. React Native's default is a translucent StatusBar on iOS you can go under, but an opaque StatusBar on Android that content does not go under.

You need to add padding+height to compensate for the translucent status bar Expo adds.

This is a duplicate of #12 and #1478.

**Comment by skevy** [comment]
Closing in favor of #1478

**Comment by babsonmatt** [comment]
@dantman thank you for clarifying that for me - apologies for the duplicate issue

**Comment by rawteech** [comment]
This [work-around](https://github.com/react-navigation/react-navigation/issues/1478#issuecomment-301220017) did the trick for me
