### ISSUE TITLE
Adding header/footer to DrawerSidebar

### ISSUE THREAD

**Issue by dulmandakh** [react-community/react-navigation#827]
DrawerNavigation is very common navigation in Android apps. It would be great if we can easily customize DrawerNavigation to have header/footer in the Drawer or Sidebar, because usually apps show logo and user related information in the header.

**Comment by dulmandakh** [comment]
drawer can be customized with contentComponent

**Comment by evgeni-tsn** [comment]
@dulmandakh Can you please give an example for header in the drawer. I know I have to use contentComponent but the docs are not really descriptive enough.

**Comment by dulmandakh** [comment]
@evgeni-tsn below is the sample code from my project. I hope that helps

``` javascript
{
  drawerWidth: 200,
  drawerPosition: 'right',
  contentComponent: props => (
    <View style={{flex:1}}>
      <Header />
        <DrawerView.Items {...props} />
       </Header>
    </View>
  )
}
```

**Comment by AlphaMikeFoxtrot** [comment]
> @evgeni-tsn below is the sample code from my project. I hope that helps
> 
> ```js
> {
>   drawerWidth: 200,
>   drawerPosition: 'right',
>   contentComponent: props => (
>     <View style={{flex:1}}>
>       <Header />
>         <DrawerView.Items {...props} />
>        </Header>
>     </View>
>   )
> }
> ```

Can I target individual items in `{...props}`?
For example, if I want to divide items in the drawer navigator into sections, how do I extract individual items from the `{...props}` attribute?
