### ISSUE TITLE
Example not working on Windows

### ISSUE THREAD

**Issue by WillyRamirez** [react-community/react-navigation#829]
Hi, installation of the example is not working on windows. One dependency is using _rm_ command.
We could maybe change the docs to notify users that it can't be installed, or the library should use _del_ command for windows users. 

Let me know if you need error message

**Comment by Ehesp** [comment]
Which dependency is causing the error/issue?

**Comment by PulsarBlow** [comment]
@Ehesp 

This line is not working

_package.json line 19:_
```
"clean": "rm -rf lib/ lib-rn/",`
```

**Comment by sibelius** [comment]
it should be `rimraf` instead

**Comment by spencercarli** [comment]
Hi! Since this issue has been quiet for a while I'm going to go ahead and close it. If the issue persists in the latest version of React Navigation please re-open!
