### ISSUE TITLE
Can't apply style to header

### ISSUE THREAD

**Issue by rafaelcorreiapoli** [react-community/react-navigation#83]
Hi! I'm trying to change the background color of my AppBar on iOS but I can't

```js
import React from 'react'
import {
  View,
  Text,
  StyleSheet
} from 'react-native'
import { StackNavigator } from 'react-navigation'

const styles = StyleSheet.create({
  header: {
    backgroundColor: 'blue',
  }
})
class MyScreen extends React.Component {
  static navigationOptions = {
    title: 'My Screen',
    header: {
      style: styles.header
    }
  }

  render() {
    return (
      <View>
        <Text>Hi</Text>
      </View>
    )
  }
}
export default StackNavigator({
  Home: {
    screen: MyScreen,
  },
})
```

What am I missing here?

I'm using 1.0.0-beta.1

**Comment by EQuimper** [comment]
+1

**Comment by despreston** [comment]
Are you using the version of react-navigation from npm? At the time of this post, the npm version does not allow you to do this. You can grab the latest from GitHub which has this.

**Comment by dpecos** [comment]
+1

I've also tried with master branch and got the same results.

**Comment by dpecos** [comment]
Thanks for your tip! This got me crazy for a while.

Now I'm able to set the background color for the header, but not the font color. Any idea?

**Comment by satya164** [comment]
We need to add support for that. Wanna send a PR? #36

**Comment by grabbou** [comment]
Support for custom `style` landed in this commit https://github.com/react-community/react-navigation/commit/a60607385bc1dfbd87244b543b6daaac1b073455 as others mentioned. #36 has a PR awaiting for `tintColor`.
