### ISSUE TITLE
Navigation after login

### ISSUE THREAD

**Issue by myhendry** [react-community/react-navigation#830]
Hi. React-native-router-flux allows authenticated users to be navigated to a main scene bucket from the login screen after login. Can that be achieved with react-navigation? If so, possible to advise how to achieve this using react-navigation? Tq

**Comment by AlanFoster** [comment]
@myhendry There is a [ReduxExample](https://github.com/react-community/react-navigation/tree/83f8a44219728f694f20b384c120154517fae06d/examples/ReduxExample) that you can use for inspiration :+1:

**Comment by myhendry** [comment]
Thanks Alan :)
