### ISSUE TITLE
Resetting causing TabNavigator tabs to unmount

### ISSUE THREAD

**Issue by Ehesp** [react-community/react-navigation#831]
My app returns a StackNavigator, with the first screen being a TabNavigator. If I reset my application to the TabNavigator, all of the individual tabs within it call `componentWillUnmount` after it's reset.

This means any setStates are not triggered and the views are not being updated.

Also the first tab is getting `componentDidMount` called, however the other tabs do not have this called. This issue is basically making it impossible to update my tab items using state.

**Comment by zywj** [comment]
Did you solve this problem?

**Comment by spencercarli** [comment]
I'm going to close this because it hasn't been updated in a while. If the issue still exists in the latest version please re-open (or ping me to). Thanks!
