### ISSUE TITLE
Tab Navigator position top under header

### ISSUE THREAD

**Issue by iDams** [react-community/react-navigation#833]
Hi,

Is it possible to have a header before a tab navigator positioned at the top of the screen?
I would like to have a view like the search on Instagram or Twitter app.

The header would contain a search bar, then the tab navigator is under it. And you can swipe between tabs.
For now, I have tried to set `tabBarPosition: "top"` but the tab bar comes first.

Thanks!

**Comment by Ehesp** [comment]
In my app I do something like:

```javascript
const Tabs = TabNavigator({
  Tab1: { screen: Tab1 },
  Tab2: { screen: Tab2 },
  etc...
});
const AppStack = StackNavigator({
  Tabs: {
    screen: Tabs,
  },
  Search: {
    screen: Search,
  },
});
```

This works, however I'm currently having issues where I'm unable to reset when say going from Tab1 => Search as the components in the Tab is unmounting.

**Comment by iDams** [comment]
Hmm but this way, you either render Search or Tabs no?
I want to be able to have tabs in my search to categorized results

**Comment by ankibalyan** [comment]
@iDams can you please post the final solution that you figured out.

**Comment by claudioscheer** [comment]
@ankibalyan look at this example

`const Tab1Navigator = StackNavigator({
    Tab1: { screen: Tab1 },
}, {
        headerMode: 'none',
    });

const Tab2Navigator = StackNavigator({
    Tab2: { screen: Tab2 },
}, {
        headerMode: 'none',
    });

const HomeTabNavigator = TabNavigator({
    Tab1: { screen: Tab1Navigator },
    Tab2: { screen: Tab2Navigator },
});

const HomeNavigator = StackNavigator({
    Home: { screen: HomeTabNavigator },
});

const navigatorConfig = {
    initialRouteName: 'Home',
    headerMode: 'none',
};
const AppNavigator = StackNavigator({
    Home: { screen: HomeNavigator },
}, navigatorConfig);`

**Comment by claudioscheer** [comment]
@ankibalyan look at this example

```
const Tab1Navigator = StackNavigator({
    Tab1: { screen: Tab1 },
}, {
        headerMode: 'none',
    });

const Tab2Navigator = StackNavigator({
    Tab2: { screen: Tab2 },
}, {
        headerMode: 'none',
    });

const HomeTabNavigator = TabNavigator({
    Tab1: { screen: Tab1Navigator },
    Tab2: { screen: Tab2Navigator },
});

const HomeNavigator = StackNavigator({
    Home: { screen: HomeTabNavigator },
});

const navigatorConfig = {
    initialRouteName: 'Home',
    headerMode: 'none',
};
const AppNavigator = StackNavigator({
    Home: { screen: HomeNavigator },
}, navigatorConfig);
```

**Comment by JackHowa** [comment]
headerMode 'none' allows content above the tab navigator? I'm trying to get a `createMaterialTopTabNavigator` below a component

**Comment by haroonahmed-sudo** [comment]
hello
