### ISSUE TITLE
Open child drawer from parent header

### ISSUE THREAD

**Issue by Armageddonas** [react-community/react-navigation#834]
I am trying to replace the back button with a menu icon. Inside my `StackNavigator` (Parent) there is a `DrawerNavigator` (Child). When the menu icon is pressed from the **Parent** the drawer needs to **open** in the **child** view. 
After many failed attempts i decided to ask.
These issues seem related: #745, #613

**Comment by PulsarBlow** [comment]
Hi @Armageddonas 

I started like you but had troubles hiding the header bar inside the drawer view, so i switched using a ```StackNavigator``` inside a ```DrawerNavigator``` (Parent)
This following code isn't probably working as-is, but you get the idea.

_RootNavigator.js_
```javascript
import React from 'react';
import { StackNavigator, DrawerNavigator } from 'react-navigation';
import LoginScreen from '../Containers/LoginScreen';
import SignupScreen from '../Containers/SignupScreen';
import HomeScreen from '../Containers/HomeScreen';
import DrawerButton from '../Components/DrawerButton';

const HomeNavigator = StackNavigator({
  Login: {
    screen: LoginScreen,
  },
  Signup: {
    screen: SignupScreen,
  },
  Home: {
    screen: HomeScreen,
  },
}, {
  navigationOptions: {
    header: navigation => ({
      title: 'My App',
      left: <DrawerButton navigation={navigation} />,
    }),
  },
});


const MainNavigator = DrawerNavigator({
  Home: {
    screen: HomeNavigator,
  },
});

export default MainNavigator;

```

_DrawerButton.js_

```javascript
import React from 'react';
import { TouchableOpacity } from 'react-native';
import Icon from 'react-native-vector-icons/MaterialCommunityIcons';
import styles from './Styles/DrawerButtonStyles';

const DrawerButton = ({ navigation }) => (
  <TouchableOpacity
    onPress={() => navigation.navigate('DrawerOpen')}
    style={styles.buttonStyle}
  >
    <Icon
      name="menu"
      style={styles.iconStyle}
    />
  </TouchableOpacity>
);

DrawerButton.propTypes = {
  navigation: React.PropTypes.object.isRequired,
};

export default DrawerButton;

```

_HomeScreen.js_
```javascript
import React from 'react';
import { View, Text } from 'react-native';

const HomeScreen = ({ navigation }) => (
  <View>
    <Text>Home Screen</Text>
  </View>
);

HomeScreen.navigationOptions = {
  drawer: () => ({
    label: 'Home',
  }),
  header: (navigation, defaultHeader) => ({
    ...defaultHeader,
    title: 'Items list',
  }),
};

HomeScreen.propTypes = {
  navigation: React.PropTypes.object.isRequired,
};

export default HomeScreen;

```

**Comment by Kishanjvaghela** [comment]
@PulsarBlow Thanks, Its work for me

**Comment by pxue** [comment]
Seems like this would override the default back button from the StackNavigator, any way I can work around this?

**Comment by valinsky** [comment]
@PulsarBlow thanks so much! I've been trying for 3 days to figure this out. You're a life saver. Works like a charm

**Comment by Armageddonas** [comment]
Thank you for the workaround @PulsarBlow, it really helped. Maybe there is a limitation though. How you render the drawer underneath the header in this use case?

**Comment by samuelpismel** [comment]
I'm 3 days trying to do this.. thanks a lot!

Should not this be on docs or in the examples?? This is what the most people want...

**Comment by Armageddonas** [comment]
As my question is mostly answered I will close the issue, thank you all for contributing!

**Comment by mynameisbams** [comment]
i follow this code and give me error  Objects are not valid as a React child (found: object with keys {left}). If you meant to render a collection of children, use an array instead.

**Comment by mynameisbams** [comment]
Objects are not valid as a React child (found: object with keys {title}). If you meant to render a collection of children, use an array instead. <===== can someone help me?

**Comment by tsmrafee-bs** [comment]
I found this error when running this
![screenshot_1494326361](https://cloud.githubusercontent.com/assets/27723951/25847030/28876a60-34d6-11e7-8152-1501270d2d1c.png)

**Comment by tsmrafee-bs** [comment]
@mynameisbams, Use this on the navigationOptions.

    navigationOptions: ({navigation}) => ({
      headerLeft: <DrawerButton navigation={navigation} />,
    }),

this solved my problem

**Comment by mynameisbams** [comment]
why i got warning BackAndroid is deprecated.... ??

**Comment by Monte9** [comment]
@tsmrafee-bs your solution worked like a charm! Thank you very much!

**Comment by walter211** [comment]
@PulsarBlow what should I do if I do want to  wrap the Drawer in to another StackNavigation?

**Comment by mateen-hussain** [comment]
@PulsarBlow Great explanation. For some reason I see my stack navigator on top of my stacknavigator as soon as the app launches.

This is my code:

App.js
```
import store from './src/store/store';
import ReduxNavigation from './src/ServiceCreationNavigation/index';

const Root = () => (
	<Provider store={store}>
		<ReduxNavigation />
	</Provider>
);

export default Root;
```
ServiceCreationNavigation/index.js
```
import Drawer from './ServiceCreationStackNavigation';

const ReduxNavigation = (props) => {
	const { dispatch, serviceCreationNavigation } = props;
	const navigation = ReactNavigation.addNavigationHelpers({
		dispatch,
		state: serviceCreationNavigation,
	});

	return <Drawer navigation={navigation} />;
};

ReduxNavigation.propTypes = {
	dispatch: PropTypes.func.isRequired,
	serviceCreationNavigation: PropTypes.object.isRequired, // eslint-disable-line react/forbid-prop-types
};

const mapStateToProps = state => ({
	serviceCreationNavigation: state.serviceCreationNavigation,
});

const ServiceCreationNavigation = connect(mapStateToProps)(ReduxNavigation);

export default ServiceCreationNavigation;

```

ServiceCreationStackNavigation.js
```
const ServiceCreationStackNavigation = StackNavigator({
	CentreSearch: {screen: CentresSearchScreen},
	SearchResults: {screen: SearchResultsScreen}
    }, {
	cardStyle: {
		paddingTop: Platform.OS === 'ios' ? 0 : StatusBar.currentHeight,
	},
	navigationOptions: ({navigation}) => ({
  	headerRight: <DrawerButton navigation={navigation} />,
	}),
});

const Drawer = DrawerNavigator({
	Service: {
		screen: ServiceCreationStackNavigation,
	},
	Home: {
		screen: Screen1,
	},
});

export default Drawer;
```
my reducer.js. 

```
import Drawer from './ServiceCreationStackNavigation';

const initialState = Drawer.router.getStateForAction(Drawer.router.getActionForPathAndParams('Service'));

const serviceCreationNavigationReducer = (state = initialState, action) => {
	const nextState = Drawer.router.getStateForAction(action, state);
	// Simply return the original `state` if `nextState` is null or undefined.
	return nextState || state;
};

export default serviceCreationNavigationReducer;
```

When the app loads, 'CentreSearch' screen is loaded on top of another 'CentreSearch' screen, with a "back" button pointing to the previous 'CenterSearch' screen. 
<img width="304" alt="screen shot 2018-01-17 at 23 03 46" src="https://user-images.githubusercontent.com/26531653/35072065-f6b70a00-fbda-11e7-8e92-542eb3d70acb.png">

**Comment by gurol** [comment]
See also https://stackoverflow.com/a/49686927/2101864

**Comment by wzup** [comment]
@PulsarBlow 

> Invariant Violation: Objects are not valid as a React child (found: object with keys {left}). If you meant to render a collection of children, use an array instead.
  in RCTView (at View.js:78)

**Comment by Gamma-Ko** [comment]
I am wondering how to add a splash screen in @PulsarBlow structure, would someone help?
