### ISSUE TITLE
Is StackNavigator broken on iOS?

### ISSUE THREAD

**Issue by qudde** [react-community/react-navigation#836]
There seems to be some serious issues with the transitions of the StackNavigator component. This is what i get with just the bare minimum code of stacknavigator and one component:

![ezgif-2-80f673da50](https://cloud.githubusercontent.com/assets/16950578/24356780/a83256f0-12fb-11e7-873c-6e983eb1469c.gif)

This is the same code on Expo sketch:
https://sketch.expo.io/rJ0V7rBnx

The issues i am getting (occasionally) are:
- Header title is overlapping
- Up to 1 second delay/freeze from tapping the link before the transition starts
- Sometimes the transition freezes
- Back button sometimes appear a second or less after the transition has finished

Anyone has any clue what this might be related to and how to fix this?

**Comment by GingerBear** [comment]
I saw the same issue

**Comment by luisfcofv** [comment]
Any update on this? My app is now super laggy when we implemented this library. This library supposed to improve the animations performance. 

> Solving this is one of the main goals behind the new React Navigation library. The views in React Navigation use native components and the Animated library to deliver 60 FPS animations that are run on the native thread.

https://facebook.github.io/react-native/docs/performance.html#slow-navigator-transitions

**Comment by ashemah** [comment]
Hi guys, I noticed this issue as well when I was running my app with the Chrome remote debugger attached and the debugger was in a background tab.

Things to try:

1. Make sure the debugger is in the foreground to make sure animations aren't slowed down
2. Disconnect the remote debugger entirely to see everything run at (almost) full speed
3. Disconnect the debugger and then run fully detached with a non-debug bundle to see everything run at full speed.

Putting the debugger in the foreground is often enough to make everything snappy again.

**Comment by andreialecu** [comment]
Probably related to this similar issue happening on Android: #706

**Comment by Warpenguin** [comment]
Also experiencing slowness/issues with StackNavigator on iOS.

Delay between transitions.. Unable to interact with UI via touch for at least 2 seconds after swiping to go back. Working fine in my UWP app.

**Comment by grabbou** [comment]
Two of the issues are already tracked in other issues:

> Header title is overlapping

#229 

> Back button sometimes appear a second or less after the transition has finished

#1164

**Comment by skevy** [comment]
@gregblass It's only closed because we believed this issue is being tracked in the two issues above (#229 and #1164).

If you feel like those issues don't cover the problems you're seeing -- could you open up another issue? Perhaps with an actionable example of the issues you're experiencing?

We know that polish is important -- we're working on polishing animations, etc for 1.0.

**Comment by gregblass** [comment]
Got it. I think there may be a third one here, but I'm not sure if its something I'm doing wrong or not optimally in my app - but for iOS using a stack navigator seems to have a significant delay. I'm trying to figure out if it may be due to react navigation or if I'm experiencing what is being described here? https://facebook.github.io/react-native/docs/performance.html#js-frame-rate-javascript-thread - The touchable highlight is also delayed on the flatlist item, for example.

**Comment by gregblass** [comment]
Here's a good idea: I'll try out the react navigation playground and see if it seems fluid/native there. If so I've got to be doing something wrong/sub-optimally.

**Comment by skevy** [comment]
@gregblass There's almost certainly some bad animation going on -- the easing curves aren't quite right. But, you shouldn't witnessing dropped frames. Make sure that you're testing in prod mode, with no console.logs, etc.

**Comment by gregblass** [comment]
No dropped frames at all. Just a pretty solid delay. I'm not sure if I'm in prod mode, so I'll check that.

**Comment by Warpenguin** [comment]
This is essentially what I experience on iOS (much less severe on android/windows) - just plain delay between the interaction and the transitions/navigation

**Comment by gregblass** [comment]
So react navigation playground doesn't have any delays at all, its smooth as butter. I'm using expo so the app is set to production mode by default. I'll have to keep investigating/debugging - it may be being caused by combining the stack navigator with a larger FlatList.

**Comment by gregblass** [comment]
@Warpenguin You using a ListView/FlatList by any chance?

**Comment by Warpenguin** [comment]
@gregblass No but I am doing something a bit unorthodox. I have 2 routes in my StackNavigator (Main and Dynamic) and I'm constantly navigating from Dynamic to Dynamic because I'm building the screen dynamically based on json prop values sent from a server.

I'm using redux and also I'm also hiding the header. The experience is fine on android. Just painfully noticeable on iOS.

**Comment by gregblass** [comment]
Alright so its definitely being caused by a log FlatList component. If I cut my data down to two items and it fixed the delay. So my issue is not one with react navigation.

**Comment by gregblass** [comment]
My issue was due to not using a React.PureComponent: https://github.com/facebook/react-native/issues/13649 - Also pretty clearly in the docs for FlatLists. Thank you @skevy

**Comment by skevy** [comment]
👍

**Comment by gregblass** [comment]
Also I was running Expo in development like Noob Saibot. Don't do that if you're testing performance!

**Comment by gregblass** [comment]
I'm still getting my back button disappearing for a split second randomly. I don't have any images on the screen either. I'll see if I can make a video.

**Comment by khushboogupta1** [comment]
@gregblass  I am using stack navigation its working fine in android but in IOS it behaving like just a back button. In my case, i am adding  a campaign and on save button it navigates to listview page where all campaigns are enlisted. It is navigating to listing page but newly added campaign is not listed there and in android it is listed. Please help.
