### ISSUE TITLE
Transition callbacks/lifecycle methods?

### ISSUE THREAD

**Issue by stevenleeg** [react-community/react-navigation#837]
Hi there,

Is there any way for a screen to know when it's been transitioned to/from? For example, if I have Screen A on the stack, then push Screen B, but the user presses back and returns to Screen A, is there any way for Screen A to know that the navigator has returned to it?

It appears that views are persisted in memory even after they are transitioned away from, so using `componentDidMount` for this use case doesn't work. I also tried `componentWillAppear`, but that didn't seem to get called in any case.

Anyone have any ideas? If this doesn't exist/there isn't a clean way of doing so I think there is a compelling case for adding something like "navigation lifecycle methods" to components, or something along those lines.

Thanks in advance!

**Comment by Ehesp** [comment]
https://github.com/react-community/react-navigation/issues/51

**Comment by stevenleeg** [comment]
Excellent, glad to see it's already being discussed. Thanks @Ehesp!
