### ISSUE TITLE
call setParams for current active screen?

### ISSUE THREAD

**Issue by aksonov** [react-community/react-navigation#838]
How to do it? I've tried to use `router.getPathAndParamsForState` but as I see StackRouter just returns empty path:
```
getPathAndParamsForState:function getPathAndParamsForState(state){

return{
path:''};

},
```

Why?

**Comment by grabbou** [comment]
The body of your issue has nothing to do with the title. If you meant calling `setParams`, then simply `this.props.navigation.setParams()`.

Related: #441
