### ISSUE TITLE
Unable to use an image inside `title`

### ISSUE THREAD

**Issue by G2Jose** [react-community/react-navigation#839]
I've got `react-navigation` set up to successfully display text title. However, when I change this to instead use an image, I see nothing.

This works:
```
static navigationOptions = {
    title: 'Text title',
    ...navigationOptions,
};
```

This does not work: 
```
static navigationOptions = {
    title: <Image source={require('./path/to/image.png')}
    ...navigationOptions,
};
```

In both cases, 

```
const navigationOptions = {
  header: {
    style: {
      backgroundColor: 'orange'
    },
  }
};
```

**Comment by cychiuae** [comment]
I think what you should do is 
```js
static navigationOptions = {
  header: () => ({
    title: <Image source={require('./path/to/image.png') />
  })
  ...navigationOptions,
};
```

**Comment by G2Jose** [comment]
Still doesn't work...

**Comment by philohelp** [comment]
It works here. Are your navOptions taken into account ?

**Comment by dantman** [comment]
The `title` option is supposed to be a string. It may be used for purposes other than the header title, such as the browser title.

**Comment by ChaoTzuJung** [comment]
it work for me. 
<img width="373" alt="2017-04-22 3 48 19" src="https://cloud.githubusercontent.com/assets/22141289/25302544/2448edb8-2773-11e7-9fa8-668503b62688.png">

<img width="1180" alt="2017-04-22 12 38 53" src="https://cloud.githubusercontent.com/assets/22141289/25302540/f7c60e1a-2772-11e7-944c-1e6d63af807c.png">

**Comment by michelalbers** [comment]
Try navigating away - you will get an error that it cannot be converted to a string :/
