### ISSUE TITLE
Is it possible to user the header component separately?

### ISSUE THREAD

**Issue by rom1k** [react-community/react-navigation#841]
I'm trying to make a transparent header above a background image, the most straight forward solution I've found is to make new header component for that specific screen but I don't want it to differ from the header in the rest of the app. So my question is:  Is it possible to use the header as a separate component with the same back button, platform specific style etc without having it attached to a navigator?

**Comment by andrerfneves** [comment]
You can pass in a `style` prop to the `header` object in the `navigationOptions` static inside each individual screen (or to the whole stack). Setting the style to `position: absolute`, and `backgroundColor: transparent` should do the trick. Doing that myself.

**Comment by rom1k** [comment]
@andrerfneves 
Thank you! I also had to change the zIndex and top/left/right position like this but it works:
```
transparentHeader: {
    position: 'absolute',
    backgroundColor: 'transparent',
    zIndex: 100,
    top: 0,
    left: 0,
    right: 0
  },
```

**Comment by hjh5696** [comment]
@rom1k @andrerfneves Thanks for your insights!! However, is it possible to pass the touch event down to the views under the header?
