### ISSUE TITLE
Error: Navigator doesn't accept its 'Screen' component as direct child

### ISSUE THREAD

**Issue by JNotelddim** [react-community/react-navigation#8416]
## **Current Behavior**

Following directly along with the docs, I've set up two basic screens (which both work fine on their own without the Navigator), and am trying to just set up basic navigation between them.
I've copied the syntax from the guide: https://reactnavigation.org/docs/hello-react-navigation/ and yet when it runs, the navigator never renders the Screen, it instead errors (see below).
I've also tried with `@react-navigation/bottom-tabs` and the same thing happens.
I'm assuming I must have a weird version of something, but I'm quite lost as to what's up here.

App.tsx:
```
import React from "react";
import "react-native-gesture-handler";
import { StyleSheet, Text, View } from "react-native";
import { NavigationContainer } from "@react-navigation/native";
import { createStackNavigator } from "@react-navigation/stack";
// import { createBottomTabNavigator } from "@react-navigation/bottom-tabs";

import HomeScreen from "./src/screens/HomeScreen";
import SecondScreen from "./src/screens/SecondScreen";

const Stack = createStackNavigator();
// const BottomTab = createBottomTabNavigator();
// console.log(BottomTab);

const App = () => {
  return (
    <View style={styles.container}>
      {/* <HomeScreen /> */}
      <NavigationContainer>
        <Stack.Navigator initialRouteName="Home">
          <Stack.Screen name="Home" component={HomeScreen} />
          <Stack.Screen name="Second" component={SecondScreen} />
        </Stack.Navigator>
      </NavigationContainer>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
});

export default App;
```

Error:
![image](https://user-images.githubusercontent.com/22509134/84296633-27d7ea00-ab01-11ea-961c-485694cac549.png)

Package.json:
```
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "@react-native-community/masked-view": "0.1.6",
    "@react-navigation/bottom-tabs": "^5.5.2",
    "@react-navigation/native": "^5.5.1",
    "@react-navigation/stack": "^5.5.1",
    "expo": "~37.0.3",
    "react": "~16.9.0",
    "react-dom": "~16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz",
    "react-native-gesture-handler": "~1.6.0",
    "react-native-reanimated": "~1.7.0",
    "react-native-safe-area-context": "0.7.3",
    "react-native-screens": "~2.2.0",
    "react-native-web": "~0.11.7"
  },
  "devDependencies": {
    "@babel/core": "^7.8.6",
    "@types/react": "~16.9.23",
    "@types/react-native": "~0.61.17",
    "babel-preset-expo": "~8.1.0",
    "typescript": "~3.8.3"
  },
  "private": true
}
```

## **Expected Behavior**

I expect the <Stack.Navigator> component to accept the <Stack.Screen> like in the guide, and that it shouldn't error, complaining that the component has to be the component which is given.
There should be a blank background, with centered text "HomeScreen", where the text has yellow background.

## **How to reproduce**

just a basic expo app: `yarn start` to the bundler, then open the app on an emulator/device.
https://github.com/JNotelddim/react-navigation-bug-repro/tree/navigation

## **Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Android emulator ![image](https://user-images.githubusercontent.com/22509134/84298113-75555680-ab03-11ea-81df-9acb60463eab.png) |
| expo                           | 3.11.2 |
| node                           | 12.18.0 |
| npm or yarn                    | 1.19.2 |

See package versions here: 
[package_versions.txt](https://github.com/react-navigation/react-navigation/files/4760143/package_versions.txt)

**Comment by zialink** [comment]
Worked for me, after spending a lot of time debugging
