### ISSUE TITLE
Header title not taking all the space available

### ISSUE THREAD

**Issue by iDams** [react-community/react-navigation#842]
Hey,

I'm trying to make the title component in the header of a `StackNavigator` taking all the space possible in the header, including left and right buttons spaces.

Right now I have this:
<img width="374" alt="capture d ecran 2017-03-28 a 10 25 44" src="https://cloud.githubusercontent.com/assets/1591702/24395792/2171f796-13a1-11e7-8354-5f5da284beb3.png">

Is there a way to extend the title?
I've already tried to set `left: null` and `right: null` with a `flex: 1` to the SearchBar but it doesn't seem to work.

Any help on this would be great!

Thanks!

**Comment by chandu0101** [comment]
https://reactnavigation.org/docs/navigators/stack 

`headerMode=none` and build your own header!

**Comment by iDams** [comment]
Hmm, interesting, thanks!
I've tried it, but my problem is the following:

I have a `StackNavigator` with a nested `TabNavigator` inside.
I've set `tabBarPosition: "top"` for the `TabNavigator`. And I would like to have my header first, then the TabBar.
When I try your solution, the TabBar comes first and the header, which is in the `render` of my page component now, is under the TabBar.

Is there a way to render a custom header for the `StackNavigation`?
I will dig into the doc.

**Comment by chandu0101** [comment]
>Is there a way to render a custom header for the StackNavigation?

https://github.com/react-community/react-navigation/pull/470#issuecomment-286036663
https://github.com/react-community/react-navigation/pull/681

**Comment by iDams** [comment]
Nice! Thanks!
It might already work with `headerComponent` if I get it right.

**Comment by aranda-adapptor** [comment]
I'd vote to reopen this. Building your own header bar is a much more involved process than customising the internal left/right/title elements. Ideally, any of these custom elements should be able to take up the whole space available in the header if the rest of the elements are not rendered.

**Comment by aranda-adapptor** [comment]
I found a workaround: wrap the search bar in a View with an explicit width, eg:
```
const screen = Dimensions.get("window");
//etc
  static navigationOptions = {
    header: {
      left: null,
      title: (
        <View style={{width: screen.width - 80}} >
          <SearchBar />
        </View>
      )
    }
  };
```

**Comment by iDams** [comment]
Hey, nice workaround.

Looking at #470 I've seen in the changes that there is a StackNavigator option called `headerComponent`. I didn't find it in the doc though. But you can use it to render your own React component as the header.
Like this:

```
const myStackNavigator =  StackNavigator(
  {
    home: { key: home, screen: HomePage },
    search: { key: search, screen: SearchPage }
  },
{
    initialRouteName: "home",
    headerMode: "screen",
    headerComponent: SearchPageHeader
  }
```

**Comment by aranda-adapptor** [comment]
Cool, did that work well for you? The problem is that #470 is replacing `headerComponent: Component` with something like `bar: ReactElement | function: ReactElement`. It seems the team is not decided which approach to take (ie whether to support components or just elements).

Also I find it easier to replace the title and keep the rest of the navigation header as default for consistency throughout the app.

**Comment by iDams** [comment]
It worked well but yeah it seems like it will no longer exist. But as the PR is taking some time to be merged, I've decided to try it for now.
One problem I have though but it is very specific to my use case. I need to be able to switch the header component depending on the route. Since `headerComponent` can only be set in `StackNavigator` constructor and not in the route component itself, I was kind of stuck. I think #470 is also fixing this.

Anyway, I've tried your solution and it works well for all my cases so thanks. I agree, it keeps consistency.

**Comment by aranda-adapptor** [comment]
> Since headerComponent can only be set in StackNavigator
Ah yeah that'd be annoying. I guess that is why they are making the header.bar changes: that custom bar element can be defined in the `static navigationOptions` of any screen. How do you respond to events in the search bar? I ended up with this:

```
  componentDidMount() {
    // Since the search bar is defined in navigationOptions header, it doesn't
    // have reference to `this`. Pass required callbacks as navigation params.
    this.props.navigation.setParams({
      onSearchChange: this.onSearchChange.bind(this)
    });
  }

// And inside the navigation options
            <SearchBar
              onSearchChange={txt => state.params.onSearchChange(txt)}
              // etc
            />
```

**Comment by iDams** [comment]
I'm using `redux` and I have connected my `<SearchPageHeader />` to the store.
So I just have to do this:

```
// SearchPage.js
static navigationOptions = {
    header: {
      left: null,
      title: (
        <View style={{ width: SIZES.SEARCH_BAR_WIDTH }}>
          <SearchPageHeader />
        </View>
      ),
      right: null,
      style: styles.header
    }
  };
```
And `<SearchPageHeader />` has a `mapDispatchToProps` to set the search value into the store.
I can then access it anywhere in my app.

Hope this helps.

**Comment by fukemy** [comment]
> headerTitleContainerStyle

headerTitleContainerStyle not working with v6 anymore

**Comment by daniel-ricado** [comment]
headerTitleContainerStyle not working with v6 anymore, needs to be reopened
