### ISSUE TITLE
Render parent screen on goBack

### ISSUE THREAD

**Issue by Snorlock** [react-community/react-navigation#845]
I would like to have a smooth way to go back from screen B to A, and have screen A render.
Right now I use a search view on screen B, and I update my state from there.
But since A dont render, I don't get the updated state in my view.
You can think of how google maps does it, when you click search. Thats how we do it, but the new state is not available in the parent view, since it does not render.

I have read people using DeviceEventEmitter, but that doesnt feel nice. Function as navigation prop, but still, I have to call render myself. The connected redux state of the parent is updated, so it should render by default.

Other issues talking about the same, but no good solutions: 
https://github.com/react-community/react-navigation/issues/684
https://github.com/react-community/react-navigation/issues/733

**Comment by ericvicenti** [comment]
You can store some state in redux, or a flux store, then subscribe to it on both screens.

**Comment by Snorlock** [comment]
Thanks for answer, I figuerd out it was just a code bug from my side. I had subscribed but sending wrong events. Guess I was a bit tired 🤤
