### ISSUE TITLE
need of some easy examples to use with redux

### ISSUE THREAD

**Issue by manjeets12** [react-community/react-navigation#846]
I followed the code of [redux example](https://github.com/react-community/react-navigation/blob/master/examples/ReduxExample/index.js) for my app, and it was working fine unless and until I decided to add TabNavigator to one of my screen,

this is how my routeConfig and StackNavigator looks

```
const routesConfig = {
  //Splash:{screen:SplashScreen},
  Landing:{screen:LandingScreen},
  Login: { screen: Login },
  SignUp: { screen: SignUp },
  ForgotPassword: { screen: ForgotPassword },
  Dashboard:{screen:Dashboard},
  UserProfile:{screen:UserProfile},
};
export const AppNavigator = StackNavigator(routesConfig, {initialRouteName:'Dashboard'});
```
Dashboard contains three tabs like this 
```
import {Platform} from 'react-native';
import { NavigationActions, TabNavigator} from 'react-navigation';

import Chats from './tabs/ChatsTab';
import Feeds from './tabs/FeedsTab';
import Maps from './tabs/MapsTab';

const Dashboard = TabNavigator({
  Feeds: { screen: Feeds },
  Chats: { screen: Chats },
  Maps:{screen:Maps}
}, 
{
  tabBarOptions: {
    activeTintColor: Platform.OS === 'ios' ? '#e91e63' : '#fff',
  }
});
export default Dashboard;
```

My tabs look something like this

```
import React, {Component} from 'react';
import {Alert,View, Text, Button} from 'react-native';
import {connect } from 'react-redux';
import styles from 'src/common/styles';
class Chats extends Component{
	constructor(props){
		super(props);
	}
	
	render(){
    	const { navigate } = this.props.navigation;
    	
		return(
			<View style={[styles.container,{alignItems:'center', backgroundColor:'#f2eae7'}]}>
			   <Text>Chats</Text>
			</View>
		);
	}
}
Chats.navigationOptions = {
  tabBar: {
    label: 'Chats',
  },
};


const mapDispatchToProps = (dispatch) => {
   return {
   	logout: () => dispatch(logout()),
   	startUpload:(data) =>dispatch(startUpload(data)),
   	openDrawer:() => dispatch(NavigationActions.navigate({ routeName: 'Drawer' }))
   }
};

const mapStateToProps = (state) => {
   return {
       user: state.user,
   };
};
export default connect(mapStateToProps, mapDispatchToProps)(Chats);
```

I ended up getting _"**undefined is not an object (evaluating state.routes[state.index]**_ , this error started to come only after I have added dashboard to my stackNavigator.

I have and other doubt how should get redux state at Dashboard because that is just a function and not a class, how should I achieve if I want to do some condtional rendering on the basis of store state at that particular component

**Comment by SidFerreira** [comment]
@manjeets12 I had some issues to understand too. And I was joining two libraries with poor documentation too. In the end I found https://github.com/fullstackreact/FirestackApp/blob/master/app/redux/modules/navigation.js which is a Firebase ReactRedux thing that has a great implementation. Few changes required to make it work. It took me some hours due to the lack of documentations. But I suggest you to use the FirestackApp as base and just fix the Provider + AppWithNavigationState part. If not clear, beep me and we try to setup a call. Maybbe we can create some docs out of it.

**Comment by manjeets12** [comment]
@SidFerreira  thanks for the reference, I will definitely look into that app

**Comment by callagga** [comment]
I'm looking for a basic example too that works out of the box so to speak.  I've been struggling trying to get a basic project working with instructions.

Anyone have the most minimalistic react-native app that uses React Navigation with Redux that would work out of the box?

**Comment by grabbou** [comment]
Please check official `ReduxExample` bundled with this project. It has a bare-bones setup with basic Redux integration.

**Comment by callagga** [comment]
yes I've been spending hours looking at this example trying to get it going :( - it would great it there was just one simplest redux integration example that works out of the box.  I'm still new to react-native but thinking of here the minimal download (not sure if it can be one file therefore, has to be a project perhaps with package.json etc I guess??) so you down, npm install, react-native run-ios.

**Comment by grabbou** [comment]
@callagga that's what happens with `ReduxExample` - it works out of the box. We recently shipped its small refactor that fixes few issues.

**Comment by wilomgfx** [comment]
@grabbou  The example does not provide action creators and an example of mapDisPatchToProps, as the OP post said, we get an error if we do so : 

```typescript
connect(mapStateToProps, mapDisPatchToProps)(RouterContainer);

```

I ended up needing to map my action creators either lower on another container component or
doing this (which works fine, but i don't really like it)

```typescript
<AppNavigator
        navigation={addNavigationHelpers({
            dispatch: this.props.dispatch,
            state: this.props.nav,
            ...bindActionCreators(actionCreators, this.props.dispatch),
        })}
        screenProps={this.props}
      />

```
