### ISSUE TITLE
TypeScript-Can I add typings into this repo? 

### ISSUE THREAD

**Issue by huhuanming** [react-community/react-navigation#847]
This repo is the best navigator for react native.

and I love TypeScript too.

😳 Can I add typings into this?

**Comment by andrerfneves** [comment]
Well I know for a fact they are using [Flow](https://github.com/facebook/flow) to do type checking on this repo. Converting to TS would probably be quite costly with small benefits.

**Comment by huhuanming** [comment]
1. Personal interest。
2. For the convenience of the TypeScript users
3. Just add a declarations.d.ts, not add into all source code.
😳

**Comment by andrerfneves** [comment]
Ah, makes more sense @huhuanming

**Comment by huhuanming** [comment]
Not limited to Flow and not modify source code, but make things meaningful to TypeScript users.

isn't that good?

**Comment by loopArray** [comment]
妥妥的，支持呀！提交给DefinitelyTyped也行啊

**Comment by huhuanming** [comment]
DefinitelyTyped Rule:

> if the package does not provide its own types, and you can not add them.
then you can add the types to DefinitelyTyped.

so, I should try it here at first

**Comment by huhuanming** [comment]
Others doesn't understand Chinese, try English @loopArray 
Or try it by Google Translate.

**Comment by loopArray** [comment]
See word DefinitelyTyped will be understand

**Comment by huhuanming** [comment]
makes more sense @loopArray

**Comment by wilomgfx** [comment]
I was thinking about doing it. Did you start yet ?

**Comment by huhuanming** [comment]
I'm gonna do it. 😊

**Comment by wilomgfx** [comment]
Great :) ! I'll keep an eye on it then ! :D Thanks :)
Can you post here when its done ?

**Comment by huhuanming** [comment]
Sure! And it is best that way.

**Comment by satya164** [comment]
Adding to repo is okay, but someone needs to take ownership and make sure they stay uptodate.

**Comment by huhuanming** [comment]
So for now going DefinitelyTyped is the best option.

😳  Reduce dependence on this repo

**Comment by wilomgfx** [comment]
great, ill pull your version of dt and test it out.

**Comment by huhuanming** [comment]
Thank you.

It's late, I should be in bed. 😴

**Comment by lionhive** [comment]
Thank you for putting this together! How can we make it available as an npm install?
-->
npm install -S @types/react-navigation

**Comment by huhuanming** [comment]
okay, will be available in weekend.

**Comment by wilomgfx** [comment]
My bad I forgot to reply back after testing. It seemed fine to me.

**Comment by huhuanming** [comment]
not mind, new version will be released tonight in my fork.

😳 timezone: gmt+8 in China.

**Comment by lionhive** [comment]
Hi folks, what is the recommended way to install this?
I see the files in this branch:
https://github.com/huhuanming/DefinitelyTyped/tree/react-navigation/types/react-navigation

The guide does not explain how to install from a branch:
https://github.com/DefinitelyTyped/DefinitelyTyped

types-publisher seems to work with master branch only.

And dependencies in package are short form as well:
  "dependencies": {
    "@types/redux-form": "^6.6.0",

**Comment by 43081j** [comment]
You should open a pull request to DefinitelyTyped, they will merge in your type definitions for react-navigation and make them available as `@types/react-navigation` (from what i remember).

The lack of types is surprising for a react project. Almost all now provide type definitions or have a definitelytyped entry. So this does need resolving ASAP as it gives good reason to not use the package in TS projects.

**Comment by grabbou** [comment]
Closing since there's nothing we can really do on our end. If someone opens up a PR to DefinitelyTyped, ping me or someone else and we will be able to help.

Happy to mention typings in the readme when they are stable.

**Comment by pierre-H** [comment]
@huhuanming did you do the PR ?

**Comment by huhuanming** [comment]
Sorry, I got in some trouble on my work.
Will need more time For it.

**Comment by pierre-H** [comment]
@huhuanming 
Ok, I hope everything will be fine for you.
I would be glad to help you to complete it !

**Comment by huhuanming** [comment]
thank you.

**Comment by llaine** [comment]
Any news on this @huhuanming  ? 
The latest react navigation update has some breakings changes, trying to implement my own, which is incomplete. Would love to type the `static navigationOptions` if you have any ideas?

**Comment by pierre-H** [comment]
@llaine I will try to add a pull request on https://github.com/huhuanming/DefinitelyTyped/tree/react-navigation/types/react-navigation in order to support the new version

**Comment by llaine** [comment]
@pierre-H amazing! If you have any ideas how to write the type definition for the `navigationOptions` in the `index.d.ts`

**Comment by huhuanming** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/16223

This have been merged, and I should publish new one for new version of react-navigation.

Thx everyone.

**Comment by pierre-H** [comment]
@huhuanming any news for the new version ? Thank you !

**Comment by huhuanming** [comment]
just `yarn  add @types/react-navigation`

**Comment by huhuanming** [comment]
I  add the typings in DefinitelyTyped

`https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-navigation`

**Comment by vTrip** [comment]
@huhuanming do you have a simple example of using this solution with a Typescript project that I could check out ?

**Comment by huhuanming** [comment]
```
yarn add @types/react-navigation
```

**Comment by jmc420** [comment]
Hi

I am getting this error with react-navigation types:

node_modules/@types/react-navigation/index.d.ts(30,3): error TS2305: Module "'.../node_modules/@types/react-native/index"' has no exported member 'StyleProp'.

These are the react, react_native and react-navigation type versions I am using:

"@types/react": "^16.0.7",
 "@types/react-native": "^0.42.8",
 "@types/react-navigation": "^1.0.20",

**Comment by DavidNorena** [comment]
@vTrip checkout https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-navigation/react-navigation-tests.tsx for and example how to use typedefinitions !

**Comment by brentvatne** [comment]
I would very much welcome definitions on this repo

**Comment by danielmhanover** [comment]
@types/react-navigator needs to be updated: https://gist.github.com/danielmhanover/eb478bae6691c41ed6adac264440cdd6
