### ISSUE TITLE
Screen tracking instructions don't cover initial route

### ISSUE THREAD

**Issue by jonasb** [react-community/react-navigation#848]
[Screen tracking and analytics](https://reactnavigation.org/docs/guides/screen-tracking) shows how to do screen tracking. However, `onNavigationStateChange` doesn't fire for the initial screen, only subsequent navigation.

Should `onNavigationStateChange` also fire for the initial screen?

Should there be another way of tracking the initial screen?

**Comment by nihgwu** [comment]
but It's clear what's the initial screen, why not just track it manually, only one line

**Comment by jonasb** [comment]
It's clear to me but I need to have to duplicate that piece of knowledge in two places (navigator config and screen tracking).

For me it's also a bit inconvenient since in my root component I either render a login screen or my stack navigator (`SignedInNavigator` below). 
```javascript
  render() {
    return !this.state.isLoggedIn ? <LoginScreen /> : <SignedInNavigator />;
  }
```
So as far as I can see there's not a good/convenient place for me to put code that should run when the navigator is mounted (i.e. before the initial screen of the navigator is mounted). I could wrap the navigator in another component, but would prefer not to.

**Comment by cooperka** [comment]
I have a very similar setup in my app as @jonasb. It would be nice and [DRY](https://en.wikipedia.org/wiki/Don't_repeat_yourself) if `onNavigationStateChange` were fired for the first view and e.g. passes `null` for `prevState`.

**Comment by grabbou** [comment]
> Should there be another way of tracking the initial screen?

I believe `componentDidMount` is enough. 

> It's clear to me but I need to have to duplicate that piece of knowledge in two places (navigator config and screen tracking).

Not quite, have you tried:

```js
class App {
   componentDidMount() {
      this.track('initialRoute');
   }

   render() {
     return <AppNavigator onNavigationStateChange={this.track} />
   }
}

**Comment by grabbou** [comment]
Also, see #1150

**Comment by cooperka** [comment]
@grabbou that's still duplicate logic, and 2 places that need to be unit tested instead of just 1. Are you opposed to adding this feature, or would you be open to a PR?

**Comment by grabbou** [comment]
Open to a PR that makes sense (from an API surface point of view). `onStateChange` cannot be used here since there's no change on initial run.

**Comment by cooperka** [comment]
I think the proposal is to fire `onNavigationStateChange(null, currentState)` on startup to indicate that the initial view is now visible. This makes the most sense to me. But you don't want to call `onNavigationStateChange` at all @grabbou?

**Comment by grabbou** [comment]
Not really in favour of that method, just like we don't have `componentWillReceiveProps()` called at the initial mount. 

I don't think that little code-duplication is worth the effort to complicate the API but I might be wrong.

@satya164 ?

**Comment by kumarpatel** [comment]
@grabbou Don't think I fully understand your recommended solution [here](https://github.com/react-community/react-navigation/issues/848#issuecomment-296686894)

In your example, is `this.track()` method implementation similar to what's outlined [here](https://reactnavigation.org/docs/guides/screen-tracking)
```
(prevState, currentState) => {
      const currentScreen = getCurrentRouteName(currentState);
      const prevScreen = getCurrentRouteName(prevState);

      if (prevScreen !== currentScreen) {
        // the line below uses the Google Analytics tracker
        // change the tracker here to use other Mobile analytics SDK.
        tracker.trackScreenView(currentScreen);
      }
    }
```

**Comment by Strate** [comment]
This is sespecially become hard with persistenceEnabled

**Comment by brentvatne** [comment]
can you post a new issue with more information @Strate? unfortunately i don't understand the concern you have because i haven't dealt with this. will lock the issue but look forward to seeing more information in a new issue!
