### ISSUE TITLE
Simplifying options passed to navigator

### ISSUE THREAD

**Issue by satya164** [react-community/react-navigation#85]
## Problem

Currently there are lots of different types of configuration, many doing similar things, which is confusing.

### Navigation options

This is quite straightforward. The navigation options can be defined statically on a component, in route config, or as global defaults in the second argument to the navigator.

```js
static navigationOptions = {
  header: {
    title: 'Home',
    visible: false,
  }
}
```

### Additional Navigator + Router config

This the second argument to the navigator. It's a mixed bag with router options, navigator options and navigation options. There are some keys which are too similar to be in 2 places.

```js
StackNavigator({...}, {
  initialRouteName: 'Home',
  headerMode: 'none',
  navigationOptions: {...},
})
```

### Requested feature to pass props to navigator

Ability to pass some props to the navigator during render is useful, for example `onChangePosition` callback to the `TabNavigator` as requested by @browniefed

```js
<MyTabNavigator
  onChangePosition={callback}
/>
```

### Navigator configuration

The second argument to navigator is the `navigationOptions` and nothing else,

```js
StackNavigator({...}, {
  tabBar: {
    activeTintColor: '#e91e63',
    style: styles.tabBar,
  },
  header: {
    mode: 'none',
  },
});
```

Options like `navigationOptions.tabBar` and `tabBarOptions` will be merged into a single key, called `navigationOptions.tabBar`. Similarly, options like `navigationOptions.header.visible` and `headerMode` will be merged to a single key, called `navigationOptions.header.mode`

### Router configuration and additional props

All router configuration and additional navigator configuration/props can be passed during the render,

```js
<MyTabNavigator
  {...TabNavigator.Presets.iOSBottomTabs}
  initialRouteName='Home'
  onChangePosition={callback}
/>
```

The advantage of specifying router configuration inside render is that it can be set conditionally.

The way to achieve this we could pass a thunk which returns the router to `createNavigator` instead of passing the `router` directly. It'll allow to pass options to router when creating it.

But this won't work if we want to have a static `router` property. So another option will be to `dispatch` an action for initial route in navigator's `componentWillMount`. Regarding order of tabs, the navigator can handle the order instead of the router, or the route config could support both arrays and objects. And maybe an optional third argument can be for router specific options, I assume this will be not needed often, so extra argument should be fine.

cc @ericvicenti  @skevy @mkonicek

**Comment by mkonicek** [comment]
> It's a mixed bag with router options, navigator options and navigation options.

This seems OK? The navigationOptions are clearly grouped under the key called `navigationOptions`.

> There are some keys which are too similar to be in 2 places.

What keys are these? What does "too similar" mean? What are the two places?
Do you have some examples?

> Options like navigationOptions.tabBar and tabBarOptions

Makes sense. It's weird to have `navigationOptions.tabBar` and `tabBarOptions` - sounds like the same thing.

> Similarly, options like navigationOptions.header.visible and headerMode will be merged to a single key, called navigationOptions.header.mode

One strange thing about:

```
header: {
  mode: 'float',
```

Is that a navigator can define this, but an individual screen can not, right? Should the keys I can pass to a Navigator's `navigationOptions` and a screen's `navigationOptions` be exactly the same to make it clear the navigator just defines the defaults for the screens?

> All router configuration and additional navigator configuration/props can be passed during the render,

```
<MyTabNavigator
  {...TabNavigator.Presets.iOSBottomTabs}
  initialRouteName='Home'
  onChangePosition={callback}
/>
```

This won't work in cases I never render my navigator manually, however. See https://github.com/mkonicek/ChatExample/blob/master/views/MainNavigator.js:

```
const MainNavigator = StackNavigator({
  Home: {
    screen: HomeScreenTabNavigator,
  },
  Chat: {
    screen: ChatScreen,
  },
});
```

Nowhere in my app's codebase I do `<HomeScreenTabNavigator>`. This means I won't be able to configure an `initialRouteName` for it.

---

Why not have configuration in one place like now and just clean up the confusing things like `navigationOptions.tabBar` vs `tabBarOptions`?

```
TabNavigator({...}, {
  initialRouteName: 'Home',
  onChangePosition={callback}
  headerMode: 'float',
  navigationOptions: {
    tabBar: {
      ...
    },
    header: {
      tintColor: '...',
    },
  },
});
```
---

**Comment by satya164** [comment]
> This seems OK?

Navigation options are ok. Router options are also ok.

> The navigationOptions are clearly grouped under the key called navigationOptions

Other options passed to the navigator are mixed. Some can be set inside `navigationOptions`, some can't be. For example `header.visible: false` and `headerMode: none` do the same thing. As a user, I shouldn't have to learn 2 different configs to the same thing.

> What keys are these? What does "too similar" mean? What are the two places?
Do you have some examples?

I'm talking about keys like `headerMode` and `header.visible`, `tabBar` and `tabBarOptions` etc.

> Is that a navigator can define this, but an individual screen can not, right?

Regarding `headerMode: float` and `headerMode: screen`, I'm not sure what will happens if someone tries to do that currently, but if we change the mode before the animation or after the animation, it should work fine I think.

>  Should the keys I can pass to a Navigator's navigationOptions and a screen's navigationOptions be exactly the same to make it clear the navigator just defines the defaults for the screens?

It is like that. The problem is there are similar keys outside.

> This won't work in cases I never render my navigator manually 

Right, I didn't think about this.

I think we should be able to specify initial route both dynamically and statically. Or do you think we shouldn't support the use case?

> Why not have configuration in one place like now and just clean up the confusing things like navigationOptions.tabBar vs tabBarOptions

Yeah, I guess we need to have navigator configuration where we have right now. And we need to move all `tabBarOptions` and `headerX` configs into `navigationOptions.tabBar` and `navigationOptions.header`. Otherwise it's confusing how options are split between these two right now.

So,

```js
StackNavigator({...},
  initialRouteName: 'Home',
  navigationOptions: {
    tabBar: {
      activeTintColor: '#e91e63',
      style: styles.tabBar,
    },
    header: {
      mode: 'none',
    },
  },
});
```

Though props like `onChangePosition` aren't useful if can't be passed as a prop, so if we want to use them we need to render the navigator. Probably we can just decide not to support the use case.

@brownniefed can you comment your use case, why you needed the prop and how did you plan to use it?

**Comment by ericvicenti** [comment]
I don't have a strong opinion on the API change, but I will note that it only makes sense to provide `initialRouteName` as a prop to the top-level navigator.


Something like this would make no sense, because `initialRouteName` never gets used because the `state` is always defined in the navigation prop.

```js
<MyTabNavigator
  initialRouteName="Home"
  navigation={{ state, dispatch }}
/>
```

**Comment by AlpZero** [comment]
Any chance to `onChangePosition` be supported?

**Comment by sibelius** [comment]
I think that a  `initialRouteName` on render makes sense.

One use case is to change `initialRouteName` based on deeplinking (`Linking`)

this was possible on `ex-navigation`

**Comment by grabbou** [comment]
This has been implemented in https://github.com/react-community/react-navigation/commit/a252b46c500ee2d789ced6ff4f75a400d7931ed0#diff-cbc20970cef83ca314bfdb0359f01115. 

You can now specify as many props on `navigator` as you want as long as there's no `navigation` prop as per @ericvicenti comment.
