### ISSUE TITLE
Accessing elements of children of a navigator?

### ISSUE THREAD

**Issue by bramvbilsen** [react-community/react-navigation#850]
I'm trying to access the title of my "Startup" page (in my "StartupStack") in my "MainStack". I can't figure out how I'd go about doing this, could someone help me a bit?
My code:
```
export const StartupStack = StackNavigator(
    {
        Startup: {
            screen: Startup,
            navigationOptions: {
                title: "Welcome"
            }
        },
        Login: {
            screen: Login
        },
        Signup: {
            screen: Signup
        }
    },
    {
        headerMode: 'none',
    }
);

export const Root = StackNavigator(
    {
        Startup: {
            screen: StartupStack,
            navigationOptions: {
                title: ///////////HELP PLEASE///////////
            },
        },
        Main: {
            screen: MainStack
        }
    },
    {
        mode: 'modal',
    }
);
```

**Comment by bramvbilsen** [comment]
Still having issues with this :/

**Comment by AlanFoster** [comment]
@bramvbilsen If I understand correctly this should just work if you remove the navigationOptions configuration within your `Root` stack navigator?

**Comment by bramvbilsen** [comment]
@AlanFoster If only it was that easy ;)
But no I'd like to get the title of the screens in my StartupStack, in my Root stack. So there are 3 screens in my StartupStack, so I'd like to be able to access those.

**Comment by AlanFoster** [comment]
@bramvbilsen Do you have a more runnable example with a screenshot of what it's currently showing, and what you expect it to show? 🤔

**Comment by bramvbilsen** [comment]
@AlanFoster I can't access a computer atm but I'll try to explain it a bit more :)
So I've got two stackNavigators: "StartupStack" and "Root". StartupStack is nested in Root.
The navbar for StartupStack is hidden and the navbar for Root is visible. 
Now, I want to get the appropriate title in the Root navbar. But, the titles are set in my StartupStack.
So the question is, can I somehow transfer the titles from StartupStack to Root?

I hope that explains the question a bit better :)

**Comment by AlanFoster** [comment]
@bramvbilsen With the configuration:

```js
class YourScreen extends React.Component {
  render() {
    return (
      <View>
        <Text>My Application</Text>
      </View>
    );
  }
}

export const StartupStack = StackNavigator(
  {
    Startup: {
      screen: YourScreen,
      navigationOptions: {
        title: "Child Header"
      }
    },
    Main: {
      screen: YourScreen
    }
  },
  {
    headerMode: 'none',
  }
);


export const Root = StackNavigator(
  {
    Startup: {
      screen: StartupStack
    }
  },
  {
    mode: 'modal',
  }
);

export default Root;
```

It looks like the following:

![image](https://cloud.githubusercontent.com/assets/1271782/24637173/ff093daa-18d6-11e7-937e-9db7b57eea7b.png)

Let me know if that was your use case :+1:

**Comment by bramvbilsen** [comment]
@AlanFoster
Wow yeah, that was exactly what I needed! I guess the solution was to obvious for me to see, hahah. Thanks!

**Comment by AlanFoster** [comment]
@bramvbilsen No problem! Feel free to close the issue if you're happy :)
