### ISSUE TITLE
Remove console log in createNavigationContainer.js

### ISSUE THREAD

**Issue by RyanMitchellWilson** [react-community/react-navigation#851]
This keeps logging 
`Navigation Dispatch: Action: {...}, New State: {...}`
Happening in createNavigationContainer.js line 150

react-navigation-beta7

**Comment by dzuncoi** [comment]
Or you can create a simple PR 👍

**Comment by grabbou** [comment]
It's been fixed - you can now disable logger by setting `onNavigationStateChange={null}` on a top-level navigator.
