### ISSUE TITLE
StackNavigator transition doesn't match iOS behavior

### ISSUE THREAD

**Issue by jarnell** [react-community/react-navigation#854]
When navigating to a new screen with StackNavigator, the old screen is pushed a bit to the left but not far enough to mimic the native iOS behavior.

This is how little the screen is moving in StackNavigator - the "A" is barely moving out of the display:

![nav_1](https://cloud.githubusercontent.com/assets/1726633/24435363/250271ee-1435-11e7-8bf5-bce0820055fe.gif)

This is what the native behavior looks like. Screen is pushed to the "a" in general (around 115px):

![nav_2](https://cloud.githubusercontent.com/assets/1726633/24435365/284b94de-1435-11e7-8df6-b64c45f32876.gif)

**Comment by mica16** [comment]
I noticed the same thing. 
Some users report that transitions seem weird since it's an overlay instead of standard transition.

**Comment by altayaydemir** [comment]
Is it possible to achieve a more native-like look by using a custom transition config?

**Comment by altayaydemir** [comment]
hi guys @mica16 @jarnell!

I think https://github.com/ajostergaard/react-navigation/commit/c6467e0a64aa5523c71ff74e3698a5a342f6b5e0 fixes this issue. 

however, this PR is included in v1.0.0-beta.12 which has not published to npm yet. try installing react-navigation from github (`npm install react-community/react-navigation --save`)

definitely looks better than the current state.

**Comment by kelset** [comment]
Pinging OP @jarnell & @altayaydemir since this issue is quite old and related to an old version of the lib (`beta.12` was published and current version is already `beta.15`). If no answer I'll close in 7 days.

**Comment by altayaydemir** [comment]
@kelset I can confirm that's resolved 👍
