### ISSUE TITLE
How to make StackNavigator's Header Transparent?

### ISSUE THREAD

**Issue by kamalk333** [react-community/react-navigation#855]
I tried putting style-> backgroundColor: 'transparent' to cardStyle props.

But I got no change. If anyone can help me that would be good.
I can't change the visibility to false as I need the goBack left button? Any other suggestions are welcomed.

**Comment by rom1k** [comment]
I made an issue about this yesterday and found a solution, you need to do this in the header's `style` prop inside `navigationOptions`:
```
transparentHeader: {
    position: 'absolute',
    backgroundColor: 'transparent',
    zIndex: 100,
    top: 0,
    left: 0,
    right: 0
  },
```



#841

**Comment by kamalk333** [comment]
Heyy!! thanks mate @rom1k 
little bit of editing in your code.

For readers taking reference of this thing.
put the style object inside of your header object.

`header:{
     style:{
         position: 'absolute',
    backgroundColor: 'transparent',
    zIndex: 100,
    top: 0,
    left: 0,
    right: 0
     }
}`

**Comment by tomav** [comment]
With this the header title disappear no?

**Comment by byk04712** [comment]
How to use `setNativeProps` for the header. Im my case, when I scroll the `ScrollView` , I use `setNativeProps` to dynamic change header backgroundColor opacity

**Comment by vishalmanohar** [comment]
Thanks @kamalk333 
The header style property names seems to have been changed to headerStyle recently. This is what worked for me:
static navigationOptions = { headerStyle:{ position: 'absolute', backgroundColor: 'transparent', zIndex: 100, top: 0, left: 0, right: 0 } };

**Comment by sukeyang** [comment]
@byk04712 I have the same problem, how do you deal with it?

**Comment by keeleycarrigan** [comment]
Works great! Thanks!

**Comment by clarktank** [comment]
static navigationOptions = { headerStyle:{ position: 'absolute', backgroundColor: 'transparent', zIndex: 100, top: 0, left: 0, right: 0 } }; This solution works but it doesn't get ride of the header line on ios. Any solutions for that?

**Comment by lyocooo** [comment]
@aksonov you could try with `pointerEvents: 'none'`?

**Comment by nipasarker01** [comment]
ThankYou @vishalmanohar

**Comment by dprivate** [comment]
After several searches, I found one solution that works. Thank you, @vishalmanohar .

**Comment by mojtababahrami70** [comment]
ThankYou @vishalmanohar

**Comment by hailelil** [comment]
@vishalmanohar : It is worked but with some issues. the headerLeft and headerRight navigators are also invisible or hidden. any otherway to deal with that? this is my code 
navigationOptions: {
      header: null,
      headerStyle: {
        backgroundColor: 'transparent',
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        borderBottomWidth: 0
      },
      headerTitle: <Text>Hello World</Text>,
      headerTintColor: 'transparent',
      headerRight: <Icon size={25} color="#fff" name="edit"/>  ,
      headerLeft:  <Icon size={25} name="back-arrow"/>

**Comment by gie3d** [comment]
Add headerTransparent: true as a navigationOptions. For example,

`static navigationOptions = ({navigation, screenProps}) => {
		return {
			headerTitle: <Text style={{color: 'white', fontSize: 18}}>Test</Text>,
			headerTransparent: true,
			headerStyle: {
				borderBottomWidth: 0,
			}
		}
	}`

**Comment by damianlattenero** [comment]
Afet hours and hours, the only solution was @gie3d , GENIUS!!! eternal gratitud

**Comment by anw063** [comment]
I also used solution by @gie3d, but the content overlaps into the header, which I read in another post is the intended behavior of headerTransparent: true -> #4074

For the solution to that posted several times in an example it is recommended to use BlurView, but it is imported from Expo, whereas my application is ejected.

All I have working right now is having the headerTransparent set to true and giving every page an empty view with flex: 0.10 to offset the rest of the page from the top, however this causes my transitions between my bottom tab navigator to jump occasionally. Has anyone else experienced this problem?

**Comment by Just01** [comment]
I have a custom header inside my StackNavigation...
``` javascript
{
  navigationOptions:
      () => {
        return ({
          header: (props) => {
            return (
              <Header {...props} />
            )
          },
        })
      },
}
```
But if i set `backgroundColor: 'transparent'` inside Header Component, backgroundColor becomes to black.
i tried to put 
```javascript
headerTransparent: true,
      headerStyle: {
        borderBottomWidth: 0,
      },
```
inside navigationOptions returns, but nothing changed.

**Comment by ozankonur** [comment]
static navigationOptions = {
        headerTransparent: true
    };

**Comment by aditodkar** [comment]
@vishalmanohar  I tried what you said in headerStyles but it is not working it throws warning saying left, right, top, position: 'absolute' has no effect on headerStyle
![screenshot_5](https://user-images.githubusercontent.com/16613832/50677098-f0b4fd80-101d-11e9-9f5b-da4b9e31c7c1.png)

**Comment by aditodkar** [comment]
@vishalmanohar  If I try to add top, left, right, bottom, position: 'absolute' inside headerStyles it gives warning saying it has no effect on headerStyles so it is not working. So as mentioned by @ozankonur  headerTransparent: true works fine.

**Comment by moahmed123** [comment]
static navigationOptions = {        
        headerTransparent: true,
        headerStyle: { borderBottomWidth: 0 }
    };

**Comment by FrankCumaio** [comment]
> static navigationOptions = {
> headerTransparent: true,
> headerStyle: { borderBottomWidth: 0 }
> };

Worked like a charm, Thank you :)

**Comment by schumannd** [comment]
@aksonov did you solve your problem?

**Comment by ahmedspring2020** [comment]
Though putting `headerTransparent: true` will make the header transparent but at the same time it also doesn't hold any height. It is acting like a position absolute, where it doesn't hold any height. So how to just make the background of the header as 'transparent' which holds it's natural height and width?

**Comment by AbhishekNairOfficial** [comment]
@gie3d headerTransparent: true does make it work, but the status bar area above the header is coloured white, and not reachable. Any solutions?

**Comment by gie3d** [comment]
> @gie3d headerTransparent: true does make it work, but the status bar area above the header is coloured white, and not reachable. Any solutions?

Does react-native `StatusBar` solve your problem? (https://facebook.github.io/react-native/docs/statusbar)

**Comment by uladkasach** [comment]
@aksonov if you use https://github.com/react-navigation/react-navigation/issues/855#issuecomment-445771199 it will solve your issue

**Comment by imkrishh** [comment]
> With react-navigation v5

`<Stack.Navigator>
    <Stack.Screen
      name={'CustomScreen'}
      component={CustomScreen}
      options={{
        title: '',
        headerLeft: () => <CustomBtn />,
        headerTransparent: true,
      }}
    />
  </Stack.Navigator>`

**Comment by mrcMesen** [comment]
Hi! it works for me, in the screems:
`         
options={{
    headerTitle: null,
    headerTransparent: true,
 }}
`

**Comment by marioas213** [comment]
I love you

**Comment by stevehs17** [comment]
This variant of mrcMesen's answer (thanks!) worked for me:

`                        options={{ title: null, headerTransparent: true, }}   
`
