### ISSUE TITLE
Title disappears on Drawer Open

### ISSUE THREAD

**Issue by tusharkhatiwada** [react-community/react-navigation#856]
Hi there,
I've a Nested Navigator in my app. I've nested `DrawerNavigator` inside `StackNavigator`. I am getting the following issue on my app.

The **title** from the **Header** disappears on opening the `Drawer` and reappears on closing the `Drawer`. Also is there any way to make the drawer **push** the **header bar** too ? 

![react-navigation](https://cloud.githubusercontent.com/assets/5126590/24447650/6e99a14a-1491-11e7-8ecd-e66095c2a9eb.gif)

**Comment by Ehesp** [comment]
Can you share your drawer `navigationOptions`?

**Comment by tusharkhatiwada** [comment]
@Ehesp 
Here's the `Dashboard` component:

```
export default class Dashboard extends Component {
  static navigationOptions = {
    title: 'Dashboard',
    drawer: () => ({
      label: 'Dashboard',
      icon: (
        <Ionicons
          name="md-map"
          size={32}
          color="dimgray"
        />
      )
    })
  };
  constructor(props) {
```

Here's the `DrawerNavigator` setting:

```
const Drawer = DrawerNavigator(
  {
    Dashboard: {
      screen: Dashboard
    },
    VehicleSetting: { screen: VehicleSetting, title: 'Vehicle Settings' },
  },
  {
    drawerPosition: 'right',
    drawerWidth: 200,
    contentOptions: {
      activeTintColor: '#000'
    }
  }
);
```

**Comment by martnu** [comment]
@tusharkhatiwada 
We solved it by having a `StackNavigator` with `headerMode: 'none'` first.
```js
const FooStackNavigator = StackNavigator({...});
const BarStackNavigator = StackNavigator({...});

const MyDrawerNavigator = DrawerNavigator({
  FooStack: { screen: FooStackNavigator },
  BarStack: { screen: BarStackNavigator }
});

const AppNavigator = StackNavigator({
  Drawer: { screen: MyDrawerNavigator },
}, {
  headerMode: 'none',
});
```

**Comment by tusharkhatiwada** [comment]
@martnu `headerMode: 'none'` hides the entire header. That is not what I wanted.

**Comment by martnu** [comment]
@tusharkhatiwada The implementation for the drawer in react-navigation is from https://github.com/react-native-community/react-native-drawer-layout. As you can see the Drawer never pushes the content but instead overlays the stack.

**Comment by tusharkhatiwada** [comment]
@martnu Ok. But what about the `title`? Is there any solution for not making it disappear? I couldn't solve it. Can you help me out please?

**Comment by martnu** [comment]
@tusharkhatiwada If you layout your Navigation as my example, you'll get it like this:

![stack-drawer](https://cloud.githubusercontent.com/assets/186496/24539748/3d594350-15f0-11e7-8282-2e8a768040be.gif)

If that's what you want try to apply the code above to your app.

**Comment by tusharkhatiwada** [comment]
@martnu This is my current configuration:

```
const Drawer = DrawerNavigator(
  {
    Dashboard: {
      screen: Dashboard
    },
    VehicleSetting: { screen: VehicleSetting, title: 'Vehicle Settings' },
    FuelSetting: { screen: FuelSetting, title: 'Fuel Settings' },
  },
  {
    drawerPosition: 'right',
    drawerWidth: 200,
    contentOptions: {
      activeTintColor: '#000'
    }
  }
);

const Routes = StackNavigator(
  {
    Login: { screen: Login },
    Home: { screen: Home },
    IndividualVehicle: {screen: IndividualVehicle},
    Dashboard: {screen: Drawer},
  },
  {
    navigationOptions: {
      header: {
        style: {
          backgroundColor: 'red',
          height: 80,
          paddingTop: 20,
        },
        titleStyle: {
          color: 'white',
          fontWeight: 'normal'
        },
        tintColor: 'white',
        right: (
          <Ionicons
            name="md-menu"
            size={28}
            color="white"
            style={{ marginRight: 10 }}
          />
        )
      }
    }
  }
);
```
if I add `headerMode: 'none'` on the `StackNavigator`, the header bar completely disappears.

**Comment by martnu** [comment]
@tusharkhatiwada Yes, which is what you want (for the Drawer). Then you'll need to move your screens (Login, Home, IndividualVehicle) into a new StackNavigator that displays the header. See my example here https://github.com/react-community/react-navigation/issues/469#issuecomment-290640137

**Comment by sourcesoftsolution** [comment]
tusharkhatiwada can you please share the navigation drawer example code i want navigation drawer on our dashboard screen after login.

**Comment by wzup** [comment]
@martnu 

Your code snippet is not enough to understand how add a header to a drawer.
Explain this:

```javascript
// how are these stack configured?
// what is their navigationOptions?
// how do they pass titles, headerTitles, drawerLabeles other props to top header of Drawer?

constconst  FooStackNavigatorFooStac  = StackNavigator({...});
const BarStackNavigator = StackNavigator({...});

const MyDrawerNavigator = DrawerNavigator({
  FooStack: { screen: FooStackNavigator },
  BarStack: { screen: BarStackNavigator }
});
```
