### ISSUE TITLE
Generation of RouteConfigs from redux store data.

### ISSUE THREAD

**Issue by alexkaraush** [react-community/react-navigation#858]
Hello, how to generate a new RouteConfigs for TabNavigator when opening nested navigation? And how do I obtain data for the generator from the redux store? It would be logical to wrap TabNavigator as/into a component, but then this connection with the parent StackNavigator would break. Thanks!

**Comment by christianversloot** [comment]
I support this issue, I've switched back to `react-native-router-flux` because my TabNavigator nested into StackNavigator breaks when specifying the initial navigation state.

**Comment by ericvicenti** [comment]
React Nav is designed to handle routing before your redux store has had a chance to load your screen's data. This allows the app to load faster. If the redux store loads and decides that the nav state is somehow invalid, you can fire a navigate action, or your screen can render an error.

Or, if you do want to have custom logic define your inner navigators, feel free to create the navigator after your data has loaded. But then you will be responsible for providing it with the `navigation` prop (including the current nav `state` and a navigation `dispatch` handler).

**Comment by max-mykhailenko** [comment]
@ericvicenti Can you help to configure redux state for nested routes? I have same error situation 

> my TabNavigator nested into StackNavigator breaks when specifying the initial navigation state.
> The error looks like:
> There is no route defined for key MainTabs. Must be one of: 'MainTabs'
