### ISSUE TITLE
Choose label and icon visibility for each tab

### ISSUE THREAD

**Issue by OmarMahili** [react-community/react-navigation#859]
I'm trying to achieve something very similar to this:

![example_tab](https://cloud.githubusercontent.com/assets/3227034/24599355/253d4462-1850-11e7-814c-2c0b39c2e779.jpg)

But currently I'm just able to select icon and label visibility for all tabs through `tabBarOptions`:

```
const Tabs = TabNavigator({
    Camera: {
        screen: CameraScreen,
        navigationOptions: {
            tabBar: {
                icon: ({ tintColor }) => (
                    <Image style={{ tintColor }} source={CameraImage} />
                ),
            },
        },
    },
    Chat: {
        screen: ChatScreen,
    },
}, {
    tabBarOptions: {
       showIcon: true,
       showLabel: true,
});
```

**Comment by AlanFoster** [comment]
@OmarMahili It's possible to configure the label within `navigationOptions` too:

```js
navigationOptions: {
  tabBar: (navigation, defaultOptions) => ({
    ...defaultOptions,
    label: ({ tintColor, focused }) => (
      <Text style={{ color: tintColor }}>
        Chat
      </Text>
    )
  })
}
```

**Comment by OmarMahili** [comment]
@AlanFoster Not really. I'm not trying to display a badge. Instead, as you can see in the example image, I need to display in the first tab an icon while in the second one a label. But what is possible now through `tabBarOptions` is displaying on all tabs both a label and an icon.

**Comment by AlanFoster** [comment]
@OmarMahili The label function can return an image if you wish. That way one of your tabs can have the default text label, and another can use a custom function to return an icon - which I think is your use case :+1:

Overall though - from a UI perspective, I think you should be consistent and choose one or the other if possible. i.e. Always show text, or an icon and text -  rather than just one or the other

**Comment by OmarMahili** [comment]
@AlanFoster Nice idea! I agree with you, but it's a consistent design alternative you can find on some user interfaces (i.e. Whatsapp).

**Comment by bhavyasruthi** [comment]
I am also facing same issue now , can any one help me how to solve this?

**Comment by ale77dan** [comment]
@bhavyasruthi
I've resolved it returning empty component for the label.

`
static navigationOptions = () => ({
    tabBarLabel: () => {},
});
`

**Comment by killboard** [comment]
> @bhavyasruthi
> I've resolved it returning empty component for the label.
> 
> `static navigationOptions = () => ({ tabBarLabel: () => {}, });`

This solution works thank you

**Comment by Huzaifaahmed20** [comment]
```javascript
navigationOptions: {
        tabBarIcon: ({ tintColor }) => (
          <View style={{ marginTop: 20 }}>
            <Icon name="camera" size={25} color={tintColor} />
          </View>
        )
}
```
you can do this and add some styling to it
