### ISSUE TITLE
support scrollable tab bar?

### ISSUE THREAD

**Issue by hieven** [react-community/react-navigation#86]
hello,
I found an PR from https://github.com/react-native-community/react-native-tab-view/pull/32 and it's been merged for a long time ago.

Because the code of [react-native-tab-view/TabBar](https://github.com/react-native-community/react-native-tab-view/blob/master/src/TabBar.js) and [react-navigation/TabBarBottom](https://github.com/react-community/react-navigation/blob/master/src/views/TabView/TabBarBottom.js) are similar, I am wondering is there any reason react-navigation doesn't support scrollable tab bar?

Thanks for the help.

**Comment by Ehesp** [comment]
Looking at this myself, I've currently got a custom implementation of a horizontal scroll tab bar, where the items extends the width of the page. I just created a TabNavigator with lots of pages (A-T) and no options.

![image](https://cloud.githubusercontent.com/assets/842078/22483569/b2ae9a84-e7f5-11e6-881b-86622306f9c9.png)

It seems that it scrolls off by default, however the items the active bar below is 1/19th of the screen width. Couple things which would make this work:

1. If the width of the container extends the device width (so it's scrolling), the active bar should be the width of the items.

2. If I click an item (e.g. J) it should ideally animate both the active bar & scroll area so the item is in view. Also the same with swiping along.

**Comment by satya164** [comment]
> If the width of the container extends the device width (so it's scrolling), the active bar should be the width of the items.

TabBar uses a normal `View` and flex to align it's children. So the width of container will never exceed screen width.

You can explicitly pass`scrollEnabled` in `tabBarOptions` to enable scroll

**Comment by onlydave** [comment]
Am I right in saying `scrollEnabled: true` only works for when `tabBarComponent: TabView.TabBarTop`? Didn't work for me in the iPhone simulator without using the Android TabNavigator presets.

What I did to get a long scrolling set of tabs was set my tabs config to the following
```
const tabsConfig = {
  ...TabNavigator.Presets.AndroidTopTabs,
  lazyLoad: true,
  initialRouteName: '5 Feb',
  tabBarOptions: {
    scrollEnabled: true,
    style: {
      backgroundColor: 'purple'
    },
    labelStyle: {
      fontSize: 12
    },
    tabStyle: {
      width: 60
    },
    indicatorStyle: {
      backgroundColor: 'teal'
    }
  }
};

TabNavigator(routeConfigs, tabsConfig);
```

The only required attributes being `...TabNavigator.Presets.AndroidTopTabs,` see [TabNavigator.js](https://github.com/react-community/react-navigation/blob/master/src/navigators/TabNavigator.js#L71) and `scrollEnabled`

**Comment by Benjamin-Dobell** [comment]
This may not be helpful for everyone, but the "scrollable tabs" pattern isn't really an iOS pattern, typically just an Android one (https://material.io/guidelines/components/tabs.html#tabs-types-of-tabs)...

I created a fairly bare bones NPM package a while ago to support this pattern "natively" on Android. I'm not sure how you'd go about hooking it up to a `TabRouter`, but it's at least there as a starting point if someone is interested.

**Comment by satya164** [comment]
@onlydave yeah, only `TabBarTop` supports scrollable tabbar. It doesn't make sense for `TabBarBottom`.

@Benjamin-Dobell it's already supported in `TabNavigator`

**Comment by Benjamin-Dobell** [comment]
@satya164 True, but the promise of React Native over using React and a web-view is native look and feel (performance). JS animations are the uncanny valley; all animation work should be off-loaded natively. I don't believe `react-native-tab-view` does that. Doing things natively also helps mitigate issues like #133

**Comment by satya164** [comment]
> I don't believe react-native-tab-view does that

React Native Tab View uses `ViewPagerAndroid` and `ScrollView` components under the hood, so the swipes are on native thread. The only thing not native is the indicator animation, because it's not possible to do that right now https://github.com/react-community/react-navigation/issues/133#issuecomment-276706941

I believe we should work to make it possible rather than writing fully native components for that. It's actually not that many changes, and will solve a wider use case than just the scrollable tab bar usecase.

**Comment by Benjamin-Dobell** [comment]
> I believe we should work to make it possible rather than writing fully native components for that. It's actually not that many changes, and will solve a wider use case than just the scrollable tab bar usecase.

Sure, I'm not sure what you have in mind. The whole communication layer between JS and native is asynchronous and native animations take place on UI thread whilst JS animations take place in the JS event loop, so I'm not sure I understand where you're going with this. Happy to be surprised though :smile:

Nonetheless, the reason I've started using React Native (and I suppose this applies to others) is because I want a native look and feel. If you can really get animations working identically (not mimicking, _identically_) and written in pure JS then that's _awesome_, but anything less is unacceptable.

**Comment by satya164** [comment]
> Sure, I'm not sure what you have in mind. The whole communication layer between JS and native is asynchronous and native animations take place on UI thread whilst JS animations take place in the JS event loop, so I'm not sure I understand where you're going with this. Happy to be surprised though 

Yeah, that's the biggest bottleneck for animations. But there have been lots of work to drive animations in the native thread avoiding the bridge altogether. The way it works is, when you try to do animations with the `Animated` API, the animation is serialized and sent to native. Then the animation happens on native thread without having to go through the bridge.

For things like scroll events (in this case swipe events), an animated event can be serialized and sent to native, and the native thread will drive the animation, without having to send the events to JS thread.

**Comment by coodoo** [comment]
@onlydave thanks for the `...TabNavigator.Presets.AndroidTopTabs,` hack, although it works but when scrolling near the end of the tabBar, things get a bit weird, i.e: last tab will never be visible no matter how one swipes the bar. Just wondering have you noticed such malfunction and found a better workaround?

@satya164 do you think providing a custom tabBar component built with `react-native-tab-view`, on iOS, will get this fixed? (Yes, I understand scrollable tabbar isn't a norm on iOS but I do have a valid use case hence needing to make that happen 😉)

**Comment by satya164** [comment]
Just set a width for your tabs in `tabStyle` and it'll be fine.

**Comment by coodoo** [comment]
@satya164 I tried that and it did make the last tab visible, but after the scrolling when I click any tab, the scroll position would go nuts and the yellow indicator would stop at wrong position, thought?

▼ before scrolling
![screen shot 2017-02-23 at 7 09 22 pm](https://cloud.githubusercontent.com/assets/325936/23256844/23d3c15e-f9fc-11e6-9221-55ba33549afd.png)

▼ after scrolling and clicking the `BBB` tab, the indicator position is wrong

![screen shot 2017-02-23 at 7 08 34 pm](https://cloud.githubusercontent.com/assets/325936/23256836/1e7e0a8e-f9fc-11e6-91f4-98cced6a3af1.png)

**Comment by satya164** [comment]
Are you using `tabBarOptions: { scrollEnabled: true }`?

**Comment by coodoo** [comment]
Yes I do, see code below.

As a side note, after clicking the tab, the indicator would be right on the spot, but then there seemed to be an after push to move it away from the target, maybe the tabbar is trying to reposition itself after the animation ends? See [this video](https://www.dropbox.com/s/at3q33uqd4j5anv/Untitled.mov?dl=0)

```javascript
const Comp = TabNavigator(

	routes,

	{
		tabBarPosition: 'top',
		swipeEnabled: true,
		...TabNavigator.Presets.AndroidTopTabs,

		tabBarOptions: {

			scrollEnabled: true,
			showIcon: false,

			activeTintColor: '#ff0000',
			activeBackgroundColor: 'rgb(29, 144, 175)',

			labelStyle: {
				color: '#FFFFFF',
				fontSize: 16,
				fontWeight: 'bold',
			},

			tabStyle: {
				// width: 200,
				borderLeftWidth: 1,
				borderRightWidth: 1,
			},

			style: {
				// width: 600,
				backgroundColor: 'rgb(45, 198, 235)',
			},

		},
	}
)
```

**Comment by satya164** [comment]
One more question, are you using master?

**Comment by coodoo** [comment]
Yes, master for react native, npm released version for react-navigation.

**Comment by satya164** [comment]
Use master of `react-navigation`

**Comment by coodoo** [comment]
Just gave that a try and it worked, but seems there's always a 1s lag before the indicator moves into the right position , [see video here](https://www.dropbox.com/s/3ielnv571dg3tml/a2.mov?dl=0).

**Comment by coodoo** [comment]
Just found by setting `animationEnabled: false` fixed the lagging issue, no worries!

**Comment by coodoo** [comment]
@satya164 I ended up [sending a PR](https://github.com/react-native-community/react-native-tab-view/pull/146) to add some minor styling tweaks that makes working with tabbar atop on iOS easier, would you mind having a look? Thanks.

**Comment by peni4142** [comment]
This does just work for me on Android. I have trouble on iOS. No scrolling tabbar.

`export const Tabs = TabNavigator({
    Page1: {
        screen: Page1,
    },
    Page2:{
        screen: Page2,
    },
    Page3:{
        screen: Page3,
    },
    Page4:{
        screen: Page4,
    },
    Page5:{
        screen: Page5,
    },
},
    {
        swipeEnabled:false,
        animationEnabled: true,
        tabBarOptions: {
          scrollEnabled:true,
          tabStyle:{
              width: 5,
          }
        },
})`

**Comment by MSSPL-PiyaleeMaiti** [comment]
@satya164 I using  
```
tabBarOptions: {
          scrollEnabled:true,
        },
```
But it's working fine in Android with `tabBarPosition: 'bottom',`  but it's not working in iOS, in iOS it's overlapping the tabs. Is `scrollEnabled:true,`  supported for iOS? I need this features both iOS and Android. Or was there any solution to scrollable the tab bar in iOS also? If any solution exists then please suggest me.

**Comment by AbdelhalimAhmed** [comment]
i publish a new article of my solution on Medium , you can see what am doning.
[https://medium.com/@abdelhalim.ahmed95/how-to-create-scrollable-and-dynamic-top-tabsbar-using-react-navigation-17ca52acbc51?fbclid=IwAR3B03f2uyvSPLDUmmMSbYdMelEZkujUJNr_yg9xpMpxtvaghg7wo9u24hc](url)

**Comment by MSSPL-PiyaleeMaiti** [comment]
@AbdelhalimAhmed  Nothing is there by clicking on your link.
Please provide valid link.

**Comment by AbdelhalimAhmed** [comment]
@MSSPL-PiyaleeMaiti  sorry about wrong!, Updated.
