### ISSUE TITLE
TabNavigator not working when setting to RTL on iOS 

### ISSUE THREAD

**Issue by yaronlevi** [react-community/react-navigation#860]
react-navigation@1.0.0-beta.7
react-native@0.42.3

If I enable RTL on iOS, which you need to do to two things:

- Call `[[RCTI18nUtil sharedInstance] allowRTL:true];` inside the appDelegate.

- Add an RTL language to the Xcode project (in my case Hebrew).

The result is that the TabNavigator shows only the content of the first tab. All the other tabs are blank:

![vid_20170329_213813](https://cloud.githubusercontent.com/assets/5398977/24471197/0676c64a-14ca-11e7-9f17-cdf6ed661e49.gif)

When working in regular mode (non-RTL) everything is fine:

![vid_20170329_213420](https://cloud.githubusercontent.com/assets/5398977/24470811/da179a9e-14c8-11e7-964e-e197b4e0888d.gif)

The code:
```
import React from 'react';
import {
    AppRegistry,
    View,
    Text,
} from 'react-native';
import { TabNavigator } from 'react-navigation';

class ScreenA extends React.Component {
    render() {
        return <Text style={{marginTop:50}}>ScreenA</Text>
    }
}

class ScreenB extends React.Component {
    render() {
        return <Text style={{marginTop:50}}>ScreenB</Text>
    }
}

class ScreenC extends React.Component {
    render() {
        return <Text style={{marginTop:50}}>ScreenC</Text>;
    }
}

const MainScreenNavigator = TabNavigator(
    {
        ScreenA: { screen: ScreenA },
        ScreenB: { screen: ScreenB },
        ScreenC: { screen: ScreenC }        
    }
);

AppRegistry.registerComponent('myapp', () => MainScreenNavigator);
```

**Comment by yaronlevi** [comment]
If It's any help, I know there is an [open issue](https://github.com/facebook/react-native/issues/11960) about ScrollView + RTL. Maybe it is related?
(the temp fix is flexDirection:'row-reverse')

**Comment by satya164** [comment]
Can you send a PR to https://github.com/satya164/react-native-tab-view to add it? Should be pretty straightforward.

**Comment by yaronlevi** [comment]
Ok, I will open a new issue there, linking to this one.

**Comment by spencercarli** [comment]
Hi! Since this issue has been quiet for a while I'm going to go ahead and close it. If the issue persists in the latest version of React Navigation please re-open!

**Comment by manjeetwadi** [comment]
it is working fine on **react-navigation@1.0.0-beta.11**  but not not on **react-navigation@1.0.0-beta.21**

on the other hand with **react-navigation@1.0.0-beta.11** clicking on tab is crashing app in android

**Comment by ablagodaryov** [comment]
I'm facing with this problem today. As a quick solution I set `swipeEnabled: true` for TabNavigator: 
`TabNavigator({...someRoutes}, { swipeEnabled: true })`.

Hope this helps someone.

**Comment by khalidahmedshalabi** [comment]
@ablagodaryov It fixed it, however it took me to another issue with `DrawerNavigator`, now the drawer wouldn't show up when `swipeEnabled: true`

**Comment by kseniamukhortova** [comment]
Still experiencing this behavior in react-navigation 1.5.11.
I have to use swipeEnabled: false as some of my screens have charts on them, that are scrolled horizontally, so I can not enable swipe.
In iOS RTL regime screens appear empty

**Comment by gabimoncha** [comment]
@spencercarli @satya164 - a PR on [react-native-community](https://github.com/react-native-community/react-native-tab-view/pull/602) is waiting to be merged. After its release, react-navigation should include it in the next version
