### ISSUE TITLE
Navigate not working to screens with tab visibility: false

### ISSUE THREAD

**Issue by NielsLindberg** [react-community/react-navigation#863]
Hi,

New to both react-native and react-navigation so it might be me doing something wrong :o,

When i call navigate('LoginStack') where the nested screen has the prop: 
static navigationOptions = {
    title: 'Login',
      tabBar: {
      visible: false
    }
  }

It navigates to an empty screen, while if i set visible to true it shows the content correctly? The content also shows correctly with the false setting on the initialRoute which is set to the LoginStack. It's only when i click logout and navigate back to the LoginStack that the problem arises and as mentioned only if tabBar>visible=false.

**Comment by jerossh** [comment]
I met the same problem.

**Comment by jerossh** [comment]
I cope it.
```
Home: { screen: Wrapper, navigationOptions: {headerMode: 'screen', header: {visible: false}}},
```

**Comment by jerossh** [comment]
```
const navigator = StackNavigator({
  Home: { screen: Wrapper, navigationOptions: {header: {visible: false}}},
  DetailPage: { screen: DetailPage }
},{ 
    headerMode: 'screen' 
  });
```
may help you

**Comment by NielsLindberg** [comment]
Yeah, ended up doing something similar with: 

export const Tabs = TabNavigator({
  TripsScreen: {
    screen: TripsScreen,
  },
  MapScreen: {
    screen: MapScreen
  },
  DirectionsScreen: {
    screen: DirectionsScreen,
  }
}, {
    headerMode: 'card',
    swipEnabled: true,
    tabBarOptions: {
      showIcon: true,
      showLabel: false,
      upperCaseLabel: false,
      inactiveTintColor: CommonStyles.colorAccentText,
      activeTintColor: CommonStyles.colorAccentText,
      pressColor: CommonStyles.colorAccent20P,
      style: {
        backgroundColor: CommonStyles.colorPrimary700,
        paddingVertical: 5,
      },
      indicatorStyle: {
        backgroundColor: CommonStyles.colorAccent
      }
    }
  }
);

export const Root = StackNavigator({
  LoginScreen: {
    screen: LoginScreen
  },
  Tabs: {
    screen: Tabs
  }
},
  {
    headerMode: 'screen'
  }
);

**Comment by ericvicenti** [comment]
Sounds like you were able to resolve it. Please provide more example code next time, otherwise it will be very difficult to help
