### ISSUE TITLE
Transparent backgrounds for cards in StackNavigator (e.g. for semi-transparent modals) lead to rendering glitches

### ISSUE THREAD

**Issue by jamesisaac** [react-community/react-navigation#864]
I imagine this would be a very common use-case, so surprised I can't find any mention of this elsewhere.  Say I want to create any kind of custom designed modal, which is surrounded by a semi-transparent background -- something like this:

![9c8cdae48f03b27946366cf1d156f53a](https://cloud.githubusercontent.com/assets/1068177/24480746/d68fc77e-14dd-11e7-8030-52eb97bbe629.jpg)

And I want it to tie in to the StackNavigation hierarchy that react-navigation provides -- handling of the back button, etc.

I can try to achieve this by setting the `StackNavigator` `cardStyle.backgroundColor` to transprarent.  This looks like it's going to work initially as the foreground card animates in, but as soon as the animation is finished, the behaviour gets very unpredictable.  Depending on platform and how many times the card has been triggered, the card behind either disappears (even though it should still visible through the transparent overlay) or flashes in and out of visibility.

Bizarrely, I can fix this on both platforms by adding `opacity: 0.99` to the cardStyle.  But I'm sure this could lead to unintended knock-on effects, so would prefer to find a cleaner solution.

Is there any reason that StackNavigator shouldn't out of the box support cardStyle.background of transparent or semi-transparent rgba values?

**Comment by MatthieuPeyrot** [comment]
i have the same issue. But i try  opacity it doesn't  work for me , it's affect all my pages not only my modal page .

**Comment by jamesisaac** [comment]
@MatthieuPeyrot If you have a StackNavigator nested inside a StackNavigator, make sure you're setting `cardStyle.backgroundColor` on both, as each stack will apply its own default light grey background.

**Comment by MatthieuPeyrot** [comment]
i put cardStyle.backgroundColor to transparent , or rgba(0,0,0,0) on all my stackNavigator. my modal blinked, and it's transparent , but the second time i try to open my modal the default light grey stay. i try do the same with opacity but all my page are transparent.

**Comment by ptc-jhughes** [comment]
I also have a similar issue. I've got a StackNavigator where I set the `backgroundColor` of the `cardStyle` options to `transparent` because I have the whole StackNavigator nested in its own background view. I get occasional glitches where on a transition from A -> B, after the transition animation, B renders on top of A and I see both screens at once.

**Comment by jamesisaac** [comment]
Ok, think I've got to the bottom of this for my needs.

In `CardStackStyleInterpolator.js`, you can see that most of the pre-defined transitions set the opacity to 0 when a card isn't in focus, which is why setting `opacity: 1` in the `cardStyle` works - it overrides all values set by the interpolator ([here](https://github.com/react-community/react-navigation/blob/7165efce02a60eecc41813fe5e030883996671ec/src/views/CardStack.js#L402) is where that happens).

Another option is to create a custom navigator based on the StackRouter, which defines its own transitions.

I initially thought this was some sort of strange rendering artifact, but it looks like everything here was just the result of animations intended for full-screen cards, which are fairly straightforward to override.

**Comment by theebi** [comment]
Hello,
I have a modal working fine.  I have made the modal window transparent. But I have to reduce the opacity of background screen when modal is presented. Any workaround on this?

**Comment by Obooman** [comment]
@theebi [This](https://github.com/react-community/react-navigation/blob/master/src/views/CardStackStyleInterpolator.js#L29) may be helpful I think.
