### ISSUE TITLE
How to remove border bellow the header?

### ISSUE THREAD

**Issue by binoy14** [react-community/react-navigation#865]
![screen shot 2017-03-29 at 10 00 02 pm](https://cloud.githubusercontent.com/assets/6476108/24484743/d6ae6504-14cd-11e7-94dc-ec909690d64e.png)

As in the previous image, I would like to remove border below the header and I have tried setting the `borderBottomColor`, `borderBottomWidth` in the styles but it does not work. Is there a way to do it?

**Comment by engin145** [comment]
set style 
shadowRadius: 0,
shadowOffset: {
    height: 0,
},

**Comment by binoy14** [comment]
@engin145 That did not work but setting `shadowColor: 'transparent'` worked. Thanks for guiding me in the right direction.

**Comment by davidfloegel** [comment]
@engin145 @binoy14 super weird, I'm trying to do the same thing!

```
style: {
        backgroundColor: '#fff',
        shadowColor: 'transparent',
        shadowRadius: 0,
        shadowOffset: {
            height: 0,
        }
    }
```

This is what I got but I'm still having the border!

Any ideas?

**Comment by winkerVSbecks** [comment]
@davidfloegel `shadowColor: 'transparent'` works for me

**Comment by davidfloegel** [comment]
@winkerVSbecks yeah I have that one but no difference.

**Comment by winkerVSbecks** [comment]
are you using it in the right place?

```
ProductInfoContainer.navigationOptions = {
  cardStack: {
    gesturesEnabled: false,
  },
  header: ({ goBack }) => ({
    ...headerStyles,
    left: (
      <Icon.Button
        name="close"
```

**Comment by davidfloegel** [comment]
yep pretty sure, because all the other styles apply

**Comment by sonaye** [comment]
I can confirm that `shadowColor: 'transparent'` works.

**Comment by janaraj** [comment]
Yes, shadowColor: 'transparent' works - thanks

**Comment by sonaye** [comment]
`elevation: 0` can also be added to have a similar result on android (flat).

**Comment by peterchibunna** [comment]
`headerStyle: {
	backgroundColor: '#fff',
	elevation:0
}`

**Comment by alexmngn** [comment]
There were a hairline border for me at the bottom of the header on iOS, I was able to remove it with:

```
headerStyle: {
    borderBottomWidth: 0,
}
```

**Comment by tuneZola** [comment]
I got it to work but not like @winkerVSbecks has it. You cannot have `{ style: shadowColor: 'transparent' }`, on the header property, it should be a property in the `headerStyle` property

`
headerStyle: {
  shadowColor: 'transparent'
}
`

**Comment by justinlok** [comment]
I'm using TabBarTop and to get rid of the line I needed to set borderTopColor: "transparent" for the tab bar.

**Comment by Xaber20110202** [comment]
The version 1.0.0-beta.11
navigationOptions = {
    headerStyle: {
        elevation: 0,
        shadowOpacity: 0
    }
 }
works for me.
https://github.com/react-community/react-navigation/issues/790

**Comment by evelyn2** [comment]
headerStyle: {
        borderBottomWidth: 0,
},
