### ISSUE TITLE
Navigate to difference screen from button in header

### ISSUE THREAD

**Issue by nikolasburk** [react-community/react-navigation#866]
Hey guys, I'm trying to use a button in my header that when pressed will navigate to a different screen. So, I'm declaring the button as `right` in my `navigationOptions`, but in there I only have access to `state` and `setParams`, so I'm not sure how I can call the `navigate` function or dispatch a `NavigationAction` from there. 

This is what my code looks like:

    const RootNavigationStack = StackNavigator({
      PokemonList: {
        screen: PokemonListWrapper,
        navigationOptions: {
          title: ({state}) => `Pokedex`,
          header: ({ state, setParams }) => {
            return {
              visible: true,
              right: (
                <Button
                  title={'Add'}
                  onPress={() => // navigate to new screen here
                />
              ),
            }
          }
        },
      },
    , {
      headerMode: 'screen'
    })

**Comment by nikolasburk** [comment]
I tried doing this

    navigationOptions: {
          title: ({state}) => `Pokedex`,
          header: ({ navigate }) => {
            return {
              visible: true,
              right: (
                <Button
                  title={'Add'}
                  onPress={() => // navigate to new screen here
                />
              ),
            }
          }

as was suggested in #621, but `navigate` always is `null` when trying to retrieve it like this.

**Comment by nikolasburk** [comment]
Fixed: see the SO post: http://stackoverflow.com/questions/43112550/how-to-navigate-to-new-screen-from-button-in-header-with-react-navigation/43117336#43117336

`header: ({ navigate }) => { ...` did work after all...

**Comment by benjick** [comment]
@nikolasburk null for me here, did you do anything else?

**Comment by kjunggithub** [comment]
This works okay for me and I can navigate like this.

```js
class Home extends Component {
  static navigationOptions = {
      header: ({navigate}) => ({
        left: (
            <TouchableHighlight onPress={() => navigate('Login')}>
              <Image source={require('../../images/back-arrow.png')} />
            </TouchableHighlight>
          )
      }),
  };
```

**Comment by benjick** [comment]
@kjunggithub What version are you on? For me it's `null`

```
  static navigationOptions = {
    title: () => 'My Reports',
    header: ({ navigate }) => {
      console.log('navigate', navigate); // null
      return ({
        right: (
          <Button onPress={() => navigate('Login')} title="ok" />
        ),
      })
    },
  }
```

**Comment by kjunggithub** [comment]
@benjick I am using version `1.0.0-beta.7`.

**Comment by benjick** [comment]
Hm, I'm using the same. I wonder why it doesn't work

**Comment by kjunggithub** [comment]
@benjick I dunno if it matters but do you have `headerMode` set to `screen` like this?

```js
const StackNav = StackNavigator({
    Login: { screen: Login },
    },
  {
    headerMode: 'screen',
  },
);
```

In the actual header function, I also have access to things like `state` and `goBack()`.

**Comment by benjick** [comment]
Yeah I do have `headerMode: 'screen',`. Without it I can't have hidden header on some routes

**Comment by darrenfurr** [comment]
In my case, 1.0.0-beta6 -- navigate is not null, but it will not navigate:
``export const HomeStack = StackNavigator({
  Home: { screen: Home, path: '/', navigationOptions: { title: 'Project Rescue',
    header:({navigate}) => ({
      titleStyle: styles.title,
      tintColor: colors.lightGreen,
      style: styles.header,
      showIcon: true,
      right: <Icon name="md-more" style={styles.more_button} onPress={() => { console.log(navigate); navigate('More') }} />
    })
  }
},
}, {headerMode: 'screen'});``

From Chrome:
![image](https://cloud.githubusercontent.com/assets/133894/25275964/84b1416c-265d-11e7-99c0-bd4aed07c168.png)
