### ISSUE TITLE
Update all tabs inside TabNavigator

### ISSUE THREAD

**Issue by cosivox** [react-community/react-navigation#868]
I've tried to dispatch setParams to all of my routes inside a TabNavigator like this:

`
this.props.navigation.dispatch(NavigationActions.setParams({
            params: { update: true },
            key: "FirstTab",
          }));

this.props.navigation.dispatch(NavigationActions.setParams({
            params: { update: true },
            key: "SecondTab",
          }));
`

But it's only working for the last tab that I did setParams (SecondTab in this case).

**Comment by ericvicenti** [comment]
Hi, can you provide the rest of the sample code so that we can see the shape of the app? Closing until more details are provided

**Comment by cosivox** [comment]
I have a TabNavigator nested in a StackNavigator and the following code in the StackNavigator:

```
export const stackNav = StackNavigator({
  Main: { screen: Main },
  TabNavigation: {
    screen: TabNavigation, navigationOptions: {
      header: ( navigation ) => {
        const right = <TouchableOpacity onPress={() => {
          navigation.dispatch(NavigationActions.setParams({
             params: { update: true },
             key: "FirstTab",
          }));

          navigation.dispatch(NavigationActions.setParams({
             params: { update: true },
             key: "SecondTab",
          }));
        }}><Icon style={{ marginRight: 10 }} name="refresh" size={25} color={"#fff"} /></TouchableOpacity >;
        return { right };
      }
    }
  },
}, {
    initialRouteName: "Main",
    headerMode: "screen",
    },
  });
```

**Comment by Tom29** [comment]
@cosivox Have you found the solution?
