### ISSUE TITLE
TabNavigator change icon sizes per screen

### ISSUE THREAD

**Issue by joshualcoffee** [react-community/react-navigation#869]
Im facing an issue that others may face or have faced and was curious how we feel the best solution would be to fix this.

Right now there is no way to set icon styles on the tab navigator configuration.  That's easy enough to fix by passing props.  The other issue im facing is having different icon styles per screen.  

Here is the example I have: 
![image](https://cloud.githubusercontent.com/assets/873384/24512912/d7f00c22-153d-11e7-8caa-c9d157178e50.png)
On android views are clipped so this will clip the icon if the icon is larger than the styles passed.  

Here are a few idea I have and working through:  

- Allow users to pass in a react component that will display in the tab.  This would allow users to format the tab anyway they see fit.  I believe ex-navigation did this.

- Allow users to set icon styles per screen.  This would require a getter and would update the style based off the scene.  

I'll be happy to work on a PR but was curious what the community thinks is the best solution.

**Comment by grabbou** [comment]
You can define `tabBarIcon` function on each of the screens and define the style of icon respectively.
