### ISSUE TITLE
Support drawer position, `left` or `right`

### ISSUE THREAD

**Issue by satya164** [react-community/react-navigation#87]

**Comment by mkonicek** [comment]
I think I've never seen an app with a drawer on the right though?

**Comment by satya164** [comment]
@mkonicek it'll be useful for RTL languages.

**Comment by mkonicek** [comment]
True, OK 👍

**Comment by luisgagocasas** [comment]
yes support.

`const DrawerOptions = DrawerNavigator(
  { 'Dashboard View': { screen: DashboardScreen } },
  { drawerPosition: 'right' },
);`
