### ISSUE TITLE
How to pass `initialProps` to a StackNavigator screen?

### ISSUE THREAD

**Issue by ferologics** [react-community/react-navigation#876]
# Desired behaviour

I'm using one component to display different content based on the initialProps. Think list with 2 data sources that depend on initialProps.

I have a `RCTRootView`. I modify it's `appProperties`. [Docs say](https://facebook.github.io/react-native/docs/communication-ios.html#passing-properties-from-native-to-react-native) that the component re-renders with new `appProperties` in `this.props` on change.

```swift
init(bridge: RCTBridge) {
    // init root view without initial props
    self.rootView = RCTRootView.init(bridge: bridge, moduleName: "Foo", initialProperties: nil)
}

// modify app properties later
self.rootView.appProperties = ["listType" : "A"]
```
The console prints
```JS
Running application Foo ({
    initialProps =     {
        listType = A;
    };
    rootTag = 1;
})
```

But the screen doesn't receive any properties and the component doesn't re-render. I put a breakpoint inside `componentWillUpdate` to check. Any idea where the props are going and how to access them? They aren't being passed inside navigation state either.

### Lazy loaded component

I recall that there was a lazy way to load components `getScreen: () => ReactComponent`. It might also be too slow to lazy load the component, ideally it's pre-loaded b/c React Native can take some time to render.

```JS
const listType
const subscription = notifierEmitter.addListener(eventName, (notification) => {
  listType = notification.listType // <- before navigating, native notifies JS about the list type
})

const Foo = StackNavigator({
  List: { 
    getScreen: () => () => <List listType = { listType }/>,
    path: ':demoListType',
  },
})
```
This works, but:
1) The performance is wack
2) Works ~90% of the time - it's unreliable
3) The list is jumpy
4) You can sometimes see previous list type being rendered before the new one appears

I'd like the `appProperties` be passed to `props` in the screen. 
Better would be if they're passed with navigation as state so that they can be used in navigationOptions for header titles, deep linking, etc.

**Comment by ferologics** [comment]
@satya164 @grabbou can you tell me where are the `appProperties` being passed? Thank you.

**Comment by ferologics** [comment]
They are being passed to `NavigationContainer`

<img width="412" alt="reactnavigaton_initialprops" src="https://cloud.githubusercontent.com/assets/5576161/24602170/efb3940c-185b-11e7-86dc-f26c0c4aab1b.png">

which passes them inside [render()](https://github.com/react-community/react-navigation/blob/master/src/createNavigationContainer.js#L179) to [createNavigator View component](https://github.com/react-community/react-navigation/blob/a7b124305393a8e392621a32e49fa96a3a14c6c9/src/navigators/createNavigator.js#L25)

<img width="267" alt="reactnavigation_initialprops_createnavigator" src="https://cloud.githubusercontent.com/assets/5576161/24602604/d4e0eb14-185d-11e7-9ac5-6b1d750a6f52.png">

**Comment by ferologics** [comment]
Ok, got a temporary hack [in my fork](https://github.com/ferologics/react-navigation/blob/master/src/views/CardStack.js#L581). I check for the route of the component that I want to pass the prop to, and modify the navigation state params.

It would be nice to have this supported by default so I'll try thinking of a way to PR this. In any case, I'd love to hear your ideas on how this could be added.

**Comment by ferologics** [comment]
False alarm, the component won't re-render on `appProperties` change b/c react navigation doesn't refresh state on `AppRegistry` JS call when runApplication is called with new initialProps. 

After all this I'm forced to use duplicate StackNavigators with the exact same routes and components but with different AppRegistry names. Same for UIViewControllers and the RCTRootViews.

```
const Foo = StackNavigator({
  List: { 
    screen: List,
    path: ':demoListType',
  }, // ... paths
})

AppRegistry.registerComponent('A', () => Foo);
AppRegistry.registerComponent('B', () => Foo);
```

**Comment by ericvicenti** [comment]
It sounds like you've found a workaround.

To my understanding, this is more of a RN bug than a problem with the nav library. RN makes it easy to provide initial props from native to the root react component, but it is not easy to update the props, so you'd need a better abstraction for that.

**Comment by ferologics** [comment]
@ericvicenti What??? the problem is clearly with the library - I still have to utilize a complete wack hack.

The library is messing with basic React Native functionality; my workaround is a total hack of something that should be supported by default. The navigation state be kept up to date on through multiple App restarts.

Once again:
1) The app's initial props are not passed to the topmost stack component (initial route)
2) The navigation state is not updated on App restart (ie. on modification of the appProps)

**Comment by ferologics** [comment]
Ping @ericvicenti

**Comment by ferologics** [comment]
Ping @ericvicenti

**Comment by ericvicenti** [comment]
Hi, I'm not sure why you're calling `AppRegistry.registerComponent` twice in your app, and that is what confused me.

Have you tried using the `screenProps` feature? It is documented here: https://reactnavigation.org/docs/navigators/stack#Navigator-Props

```js
const Foo = StackNavigator({
  List: { 
    screen: List,
    path: ':demoListType',
  }, // ... paths
});

const List = ({ screenProps }) => <MyListView foo={screenProps.bar} />;

// first, you can render:
<Foo screenProps={{ bar: true }} />;

// then you can re-render the navigator and the new screen prop will flow down to MyListView:
<Foo screenProps={{ bar: false }} />;
```

**Comment by ferologics** [comment]
@ericvicenti calling `AppRegistry.registerComponent` twice is used for two different RCTRootView inits which have different `initialProps`. [Docs](https://facebook.github.io/react-native/docs/communication-ios.html)

`screenProps` doesn't solve anything. The props I need are passed to the root component registered. (StackNavigator)

`app registered` -> init root view module with `initialProps: ["key":"value"]` initialized -> props get lost inside the StackNavigator as already described above -> initial screen component can't access initial props

**Comment by 601367322** [comment]
use screenProps
this.props. screenProps

**Comment by grabbou** [comment]
As already mentioned by others, the way you are doing it:
```
const Foo = StackNavigator({
  List: { 
    getScreen: () => () => <List listType = { listType }/>,
    path: ':demoListType',
  },
})
```
is not going to work.

You should instead:
```
const Foo = StackNavigator({
  List: { 
    screen: List,
    path: ':demoListType',
  },
});

class First extends React.Component {
   render() {
     // read from `initial props`
     return <Foo screenProps={{ listType: this.props... }} />
  }
}

AppRegistry.registerComponent('FirstComponent', () => First);
```

**Comment by joshuapinter** [comment]
@grabbou @ferologics I still can't access the `initialProps` with how you have suggested setting up the app. 

I'm not sure if we're doing something wrong. But you have closed this and the other issue that I made regarding the same thing (#634). You seem to be really confident that this is doable so please let us know what your secret here to accessing `initialProps` using this navigation library.

Thanks!

**Comment by joshuapinter** [comment]
@grabbou @ferologics 
And if you could please re-open this issue until one of us has confirmed that it's been resolved, that would be great. Thanks.

**Comment by joshuapinter** [comment]
Okay, finally understood the approach you were taking and managed to get it working. To help others, here is a full solution:

```js
import React from 'react';

import {
  AppRegistry,
  Text,
} from 'react-native';

import { StackNavigator } from 'react-navigation';

class MyApp extends React.Component {
  render() {
    console.log('this.props in MyApp', this.props); // This will list the initialProps.

    // StackNavigator **only** accepts a screenProps prop so we're passing
    // initialProps through that.
    return <Navigator screenProps={this.props} />; 
  }
}

class HomeScreen extends React.Component {
  render() {
    console.log('this.props in HomeScreen', this.props);
    // This will output something like this: 
    // { screenProps: { ...your initialProps }, navigation: { ...StackNavigator stuff... } }

    return <Text>My initialProps are {JSON.stringify(this.props.screenProps)}.</Text>;
  }
}

const Navigator = StackNavigator({
  Home: { screen: HomeScreen },
});

AppRegistry.registerComponent('MyApp', () => MyApp);
```

Thanks and I hope that helps clarify for others, including @ferologics.

**Comment by ferologics** [comment]
Hey, after this issue, I decided that React Navigation is performing extremely poorly in my production app and I decided to go with native iOS navigation + a bunch of RCTRootViews. 

((( why I decided to do so: 
- performance problems were with the navigation animations (pop, push were laggy)
- popping the entire screen stack resulted in an unexpected animation which caused confusion to many users. 
- #729

After testing with couple users they all concurred that the navigation is unlike the native one. Overall less responsive UI and there were subtle abovementioned animation differences that influenced the UX. )))

@grabbou and @ericvicenti are totally right, I should've used the `screenProps` as suggested in above examples. 

My error was in expecting the StackNavigator to take the `initialProps` and automagically pass them to the initial screen, without requiring an intermediary component to make use of the `screenProps`. 

^ Feedback to consider for the project collaborators and a lesson for me to read docs more thoroughly.

Thanks for the support!

**Comment by robertsimoes** [comment]
@joshuapinter I ❤️ U.

**Comment by joshuapinter** [comment]
@robertsimoes 🙏

**Comment by LouisJS** [comment]
Works perfectly ! Thanks @joshuapinter

**Comment by puckybreg** [comment]
@ferologics what debugger are you using for react-native?

**Comment by silhouette5366** [comment]
@joshuapinter  @grabbou  can you guys please give a solution which works for react-navigation-3 in which you must set up your app container directly.

**Comment by BochengLiu** [comment]
@silhouette5366 
`const HomeStack = createStackNavigator(
    {
        Home: {
            screen: Scene1,
        },
      },
      {
        initialRouteName: "Home"
      }
);

export default createAppContainer(HomeStack);

class Main extends React.Component {
  constructor(props) {
    super(props);
  }

  render() {
    return (
      <HomeStack screenProps={{ baseInfo: this.props }}  />
    );
  }

}
export default Main;;
`
this.props.screenProps , Now you can take it.

**Comment by BochengLiu** [comment]
@silhouette5366
```
const HomeStack = createStackNavigator(
  {
    Home: {
      screen: Scene1,
    },
  },
  {
    initialRouteName: "Home"
  }
);

export default createAppContainer(HomeStack);

class Main extends React.Component {
  constructor(props) {
    super(props);
  }

  render() {
    return (
      <HomeStack screenProps={{ baseProps: this.props }} />
    );
  }

}
export default Main;
```
Use this.props.screenProps ,  you can take it.
