### ISSUE TITLE
No tabStyle option available for TabBarBottom when using TabNavigator

### ISSUE THREAD

**Issue by cgadea** [react-community/react-navigation#877]
Seems like it's not possible to style a tab when using the TabBarBottom component.
https://github.com/react-community/react-navigation/blob/master/src/views/TabView/TabBarBottom.js#L151

- Is this something that could be implemented in the future?
- Does anyone know of a way around this limitation?

**Comment by satya164** [comment]
What's your use case? What do you want to customize?

**Comment by cgadea** [comment]
Want to control the layout of the tab, so setting flexbox properties and padding for example.

**Comment by bcarroll22** [comment]
This would also be nice since bottom navigation in android is supposed to have ripples.

**Comment by satya164** [comment]
You can't add ripples with `tabStyle`. Just use `TabView.TabBarTop` as your bottom tab bar.

**Comment by faceyspacey** [comment]
Why was this closed. There is a `tabStyle` option. It's supposed to do something. There are lots of potential use cases for stylizing the tab.
