### ISSUE TITLE
Help to find 'father' view of all! Simple question 

### ISSUE THREAD

**Issue by snksergio** [react-community/react-navigation#878]
Hi, I'm a beginner in react native and I came across a problem where I can not figure out how to solve it.
I want to use the https://github.com/instea/react-native-popup-menu plugin, which will open when clicking the icon that is located in the header.

But to use this plugin I need to put the <MenuContext> </ MenuContext> component as the parent of all views if the plugin is not cut by the overflow of the view, and since the header and stuff is being injected by the reactnavigation, could someone Advise how could I pass this component to be the main view before the header / card / screen? Thanks!

**Comment by ericvicenti** [comment]
maybe try something like this?

```js
const MyNavigator = StackNavigator({ ... });

export default class App extends Component {
  render() {
    return (
       <View>
         <MyNavigator />
         {popupMenuComponent}
       </View>
    );
```
