### ISSUE TITLE
Intercept Guesture

### ISSUE THREAD

**Issue by wangzhe890703** [react-community/react-navigation#879]
I want to intercept gestures such as swipe and drag. Does anyone know how to do it?

I have a nest navigation: a stack navigator nested in a drawer navigation. In the stack navigator, I want to disable swipe gesture. Does anyone know  how to do it?

**Comment by wangzhe890703** [comment]
closed

**Comment by RWOverdijk** [comment]
Why closed? What's the answer?

**Comment by annelorraineuy** [comment]
Same here. Did you figure out how to disable gesture, @wangzhe890703 ?

**Comment by koenpunt** [comment]
Read the docs peeps;

```js
navigationOptions: {
  gesturesEnabled: false,
}
```

**Comment by annelorraineuy** [comment]
@koenpunt this isn't referring to disabling gesture to pull and hide the drawer menu. It's to disable swipe to back gesture. -_-

**Comment by koenpunt** [comment]
That's exactly what I'm talking about; https://reactnavigation.org/docs/navigators/stack

**Comment by RWOverdijk** [comment]
@koenpunt From the docs:

> Whether you can use gestures to dismiss this screen

Unfortunately that's not what we're looking for. We're looking for a way to **lock the drawer**. Disable _those_ gestures. Which is useful if you have a nested stack navigator that doesn't provide access to the drawer on nested screens.

Also, maybe try to be less rude. there are [plenty of issues](https://github.com/react-community/react-navigation/search?q=disable+drawer&type=Issues&utf8=%E2%9C%93) concerning this topic. I doubt _none of them_ read the docs. I know I did, and it's [not a feature yet](https://github.com/react-community/react-navigation/pull/793).

**Comment by koenpunt** [comment]
The question states:

> In the stack navigator, I want to disable swipe gesture

So I think we're talking about 2 different things in this issue.

And was not meant to be rude, but I see so many questions here about things that are in the docs.

**Comment by RWOverdijk** [comment]
@koenpunt The phrasing allows for both interpretations of the issue, I agree. We're talking about different things.

And that's fair. It felt a bit rude, but I understand the frustration.
