### ISSUE TITLE
can I set the StackNavigatorConfig dynamically，different screen set different value?

### ISSUE THREAD

**Issue by zhipenglin** [react-community/react-navigation#880]

**Comment by Ehesp** [comment]
Please provide some code showing what you've already attempted. I'm not sure what you're looking to do here.

**Comment by zhipenglin** [comment]
I want to set StackNavigatorConfig->Visual options->mode='modal'(StackNavigator(.....screens,{
  mode:'modal'
})),but this setting is global，can I make it work only on a screen，such as Login Page，I want to get an animated effect from bottom to top。

**Comment by zhipenglin** [comment]
I want to set StackNavigatorConfig->Visual options->mode='modal'(StackNavigator(.....screens,{
mode:'modal'
})),but this setting is global，can I make it work only on a screen，such as Login Page，I want to get an animated effect from bottom to top。 @Ehesp

**Comment by ericvicenti** [comment]
Have you tried this?
```
const AppNavigator = StackNavigator({
  Main: {screen: InnerNavigator},
  Login: {screen: LoginScreen},
}, {mode: 'modal'});
const InnerNavigator = StackNavigator({
  Feed: {screen: FeedScreen},
  Profile: {screen: ProfileScreen},
});
```

**Comment by zhipenglin** [comment]
thank you very much

**Comment by TakaKeiji** [comment]
This works ok but generate duplicated navbar as well...
