### ISSUE TITLE
DrawerNavigator labelStyle not working

### ISSUE THREAD

**Issue by sonaye** [react-community/react-navigation#881]
I am trying to add a custom style to the text label of the items in the drawer of DrawerNavigator, [according to the docs](https://reactnavigation.org/docs/navigators/drawer#contentOptions-for-DrawerView.Items) this can be done through `contentOptions.labelStyle`, but it doesn't seem to work.

Note: I am actually trying to set a custom font, using `textDecorationLine: 'line-through'` here just for demo purposes.

![kapture 2017-04-01 at 16 59 38](https://cloud.githubusercontent.com/assets/23000873/24579374/d2797402-16fc-11e7-8ae3-67f10987c4b8.gif)

Code to reproduce:
```javascript
const Root = DrawerNavigator(
  {
    about: {
      screen: About,
      navigationOptions: {
        drawer: {
          label: 'About',
          icon: ({ tintColor }) => <FontAwesome name="info" size={24} color={tintColor} />
        }
      }
    }
  },
  {
    contentOptions: {
      labelStyle: { textDecorationLine: 'line-through' }
    }
  }
);
```
Am I doing something wrong with the config?

I also tried using a custom contentComponent:
```javascript
contentComponent: (props) => (
  <ScrollView style={{ flex: 1 }}>
    <DrawerView.Items {...props} labelStyle={{ textDecorationLine: 'line-through' }} />
  </ScrollView>
)
```

Also tried `drawer: () => ({ ... })` instead of just `drawer: { ... }`. Both didn't work.

**Comment by AlanFoster** [comment]
@sonaye Support for this functionality was added 5 days ago via https://github.com/react-community/react-navigation/pull/731

This functionality therefore isn't available in the latest released version `1.0.0-beta.7`.
You should be able to pick it up with `1.0.0-beta.8` when that lands :+1:

**Comment by sonaye** [comment]
Awesome!

**Comment by Kishanjvaghela** [comment]
@AlanFoster  It give me an error.
```
npm ERR! notarget No compatible version found: react-navigation@^1.0.0-beta.8
npm ERR! notarget Valid install targets:
npm ERR! notarget 1.0.0-beta.7, 1.0.0-beta.6, 1.0.0-beta.5, 1.0.0-beta.4, 1.0.0-beta.3, 1.0.0-beta.2, 1.0.0-beta.1, 0.0.0
```

**Comment by sonaye** [comment]
@Kishanjvaghela beta 8 is not published yet, you can try cloning the repo if it's urgent.

**Comment by Biplovkumar** [comment]
thanks @sonaye ,,its working

**Comment by LeoInCode** [comment]
Try drawerLabelStyle instead of labelStyle. I found this property on the documentation: https://reactnavigation.org/docs/drawer-navigator/
