### ISSUE TITLE
Background View

### ISSUE THREAD

**Issue by olegdizus** [react-community/react-navigation#884]
In my app I have MapView behind all app screens. This not a problem itself, but if I try to interact the map through transparent scene parts nothing happens. I can wrap my navigator in View and set pointerEvents='none', but in this case all interactive elements in scene won't work.

**Comment by ericvicenti** [comment]
This isn't really supported, but if you post sample code and screenshots, people may be more excited to fix it.

**Comment by jsierles** [comment]
I'm excited to fix it! Would this essentially be adding an option to turn `pointerEvents` off for a specific scene? Here it looks like all scenes lose pointerEvents unless they are the current scene.

https://github.com/react-community/react-navigation/blob/master/src/views/Card.js#L57

Would a solution then be to keep pointerEvents enabled on screens marked as 'transparent'?

I'll post code and screenshots shortly.

**Comment by Victorien-Tardif** [comment]
Hi @olegdeezus @jsierles , I'm having the same problem, If you managed to handle it I'd like to know how!
Thanks
