### ISSUE TITLE
StackNavigator: How to send data back from child screen to calling screen?

### ISSUE THREAD

**Issue by georgjaehnig** [react-community/react-navigation#885]
I have defined a `MainScreen`, from where the user can navigate to a "subscreen" called `EditScreen`, using `Stacknavigator` and `this.props.navigation.navigate()`.  There, the
user can change some data.

I now want to send the data back to `MainScreen`. What is the correct way of doing this? 

My self-made "trick" until now was:

First, navigate to `EditScreen` with 

    this.props.navigation.navigate( 
      'Edit', 
      { 
        parent: this 
      }
    );

Then, once the data shall be sent back from `EditScreen`:

    this.parent.foo = "new value";
    this.parent.setState({ bar }); // To trigger render.
    this.props.navigation.goBack();

However, this leads to some odd behaviour afterwards in `MainScreen`, such as
reloading it twice and loosing some of its `state`.

So I wonder: What is the correct way to send some data back to the calling
screen.

(BTW: I've simplified the example, if you want to see the original code:
[check here](https://github.com/georgjaehnig/qr-show/tree/master/js) )

**Comment by Ehesp** [comment]
I'd suggest using Redux here to pass state around your app.

**Comment by spencercarli** [comment]
Hi! In an effort to reduce the number of open issues I'm closing question-type issues that would be a better for the [react-navigation tag on StackOverflow](https://stackoverflow.com/questions/tagged/react-navigation). This is nothing personal, merely trying to get the # of issues to a more manageable level. If you think this issue should be re-opened please let me know. Thanks!
