### ISSUE TITLE
[StackNavigator] Cannot pass function parameters 

### ISSUE THREAD

**Issue by ricsirigu** [react-community/react-navigation#887]
I'm trying to pass a function in the following way 

`   <Button
        onPress={() => this.props.navigation.navigate('Profile', {cb:  () => this.setState({something})})}
      />`

But the params object is always empty.

Is it a bug?

**Comment by akotlov** [comment]
I may be wrong,but  I don't think you can pass a function as params.You can't serialize a function.Params must be something that can be serialized,like object.

**Comment by herudi** [comment]
Yes, you can pass function in your parameters.
For example :
MainScreen
```js
...
_onOpenModal(){
      this.setState({
          showModal:true
      });
  }
...
render() {
    const { navigate } = this.props.navigation;
    return (
         <View>
            <Button onPress={() =>{
                  navigate('Screen1',{
                      onOpenModal: this._onOpenModal.bind(this)
                  });
            }} />
         </View>
    )
}
...
```
then in Screen1 look like this
```js
...
render() {
    const { params} = this.props.navigation.state;
    return (
         <View>
            <Button onPress={() =>{
                  params.onOpenModal();
            }} />
         </View>
    )
}
...
```

Hope this helps.

**Comment by Palisand** [comment]
You can pass functions, however, flow will complain: https://github.com/react-community/react-navigation/blob/master/src/TypeDefinition.js#L171-L173

**Comment by kelset** [comment]
Pinging @ricsirigu since it looks like @herudi solution works (and the issue refers to an old version of the lib anyway.

If no answer I'll close in 7 days.

**Comment by kelset** [comment]
Hi there @ricsirigu ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue (especially if it's a bug report) please open a new issue that uses the new Issue Template to provide some more details to help us solve it.
