### ISSUE TITLE
Feature request: ability to disable redux logs in the console

### ISSUE THREAD

**Issue by sonaye** [react-community/react-navigation#890]

**Comment by AlanFoster** [comment]
@sonaye This seems to be a duplicate of https://github.com/react-community/react-navigation/issues/753

Fire a pull request and I think this will get merged in :+1:

**Comment by sonaye** [comment]
Glad someone already pointed that out, I am not familiar with the redux setup unfortunately, learned it from scratch for the sake of learning and having a better understanding of state management in general, ended up switching  to another solution though. Thanks for the heads up!

**Comment by AlanFoster** [comment]
@sonaye Out of interest, what alternative did you go with? :)

**Comment by sonaye** [comment]
MobX! of course, it just feels right, from the first line of code, been using it in production for a while now.
