### ISSUE TITLE
Cannot hide header in Stack-navigation

### ISSUE THREAD

**Issue by Domthegrom** [react-community/react-navigation#892]
I have tried this:
`export default StackNavigator({
  LoginPage: { 
    screen: LoginPage,
      navigationOptions: {
        header: {
          visibile: false
        },
      },
   },`

I have tried this: 
`export default class LoginPage extends React.Component {
static navigationOptions = {
    header: {
      visible: false,
    }
  };`

I am also not sure how to implement the `headerMode` to be `none`

Also on an un related note I cant seem to use the onpress function for react-navigation in a component that I import to a different file. I import a form, to a scene I created. It looks like this:

THIS below is exported from `CreateAccForm.js` to `CreateAcc`

```<TouchableOpacity onPress={() => this.props.navigation.navigate('Feed')} style={styles.buttonContainer}>
                    <Text style={styles.buttonText}>
                        LOGIN
                    </Text>
                </TouchableOpacity>  ```


This is the `CreateAcc.js`:


```<KeyboardAvoidingView behavior='padding' style={styles.container}>
              <CreateAccForm/>
              <View style={styles.accountLogin}>
                    <TouchableOpacity onPress={() => this.props.navigation.navigate('Forgot')}>
                        <Text style={{opacity: 0.9,color:'#34B3E4'}}>Forgot your password? </Text>
                    </TouchableOpacity>
                </View>  
            </KeyboardAvoidingView>```

That touchableopacity text doesnt work just gives me an undefined obj

**Comment by JulianKingman** [comment]
How'd you fix?

**Comment by Domthegrom** [comment]
This is my `Router.js` the magic that does the trick is
 `{ 
    headerMode: 'screen' `


```export default StackNavigator({
  LoginPage: { 
    screen: LoginPage,
    navigationOptions: {
      header: { visible:false },
    },
   },
  Create: { 
    screen: CreateAcc,
     navigationOptions: {
       title: 'Mentor',
       header:{
       titleStyle: { color: '#0077B5' }
       }
     }
   },
   Profile: {
     screen: Profile,
      title: 'Profile',
      header:{
       titleStyle: { color: '#0077B5' },
       },
   },
  Log:  { 
    screen: Login,
    navigationOptions: {
       title: 'Mentor',
       header:{
       titleStyle: { color: '#0077B5' }
       }
     }
  },
  Forgot: {
     screen: ForgotPass,
     navigationOptions: {
       title: 'Mentor',
       header:{
       titleStyle: { color: '#0077B5' }
       }
     }
   },
   Feed: {
     screen: Feed,
     navigationOptions: {
       title: 'Mentor',
       header:{
       titleStyle: { color: '#0077B5' }
       } 
     }
   },
   Settings: {
     screen: Settings,
      navigationOptions: {
        title: 'Mentor',
        header:{
       titleStyle: { color: '#0077B5' }
       }
      }
   },
  },
  { 
    headerMode: 'screen' 
  
  });```

**Comment by gotoAndBliss** [comment]
Thanks for the update @Domthegrom  . For some reason, this code :

```
    export const Navigation = StackNavigator({
      Home: { screen: Purgatory },
      Start: { 
        screen: GameStart,
        navigationOptions: {
          header: { visible:false },
        },    
      }
    }, {
      navigationOptions: {
        headerMode: 'screen',
      }
    });
```

Returns this ..

<img width="372" alt="screen shot 2017-05-27 at 5 31 43 pm" src="https://cloud.githubusercontent.com/assets/57091/26522489/795a7092-4302-11e7-9c28-0c2a6f804236.png">

**Comment by Domthegrom** [comment]
Looks like there is an error in your render method of your start.js file or home.js. May I see the code for both of them? Check to see if your View isn't closed.

**Comment by gotoAndBliss** [comment]
@Domthegrom Thanks for the reply.

I realized because I was on Beta6, it should now be written like this 

```
          header: null,
```

So this prevents the error from showing, but alas.. the header still remains. It doesn't seem to respond to any props I add though, `tintColor` `styles`. It seems to ignore everything.

**Comment by Domthegrom** [comment]
hmm, try removing the `headerMode: 'screen''.  @gotoAndBliss

**Comment by SmnTin** [comment]
@gotoAndBliss It helped me, thanks!

**Comment by godfredcs** [comment]
@Domthegrom about your TouchableOpacity. The reason why it is not working is that the function that you passed to onPress is not bound to the class in which TouchableOpacity exists. So to fixed that, you could define the function in the class and call it in the TouchableOpacity by binding the 'this' keyword to it.

eg. renderButton( ) { this.props.navigation.navigate('forgot') }

Then in the onPress of the TouchableOpacity:
onPress={ this.renderButton.bind(this) }

I hope it solves your problem and those of others.

**Comment by jayshah123** [comment]
I want to toggle header and I use following : 
```
    header: (navigation.state.params.shouldIHide ? null : undefined)
```
Is it dependable?
