### ISSUE TITLE
Drawer navigation click in dark to close

### ISSUE THREAD

**Issue by ronal2do** [react-community/react-navigation#894]
It`s possible close the drawer by tapping on the dark space overlay?

The following demonstration image

<img width="168" alt="captura de tela 2017-04-03 as 09 53 40" src="https://cloud.githubusercontent.com/assets/4389565/24610043/7cc1c2be-1853-11e7-8bfa-35b5e4c193a7.png">

**Comment by dominicrj23** [comment]
It works when you tap on the dark area. Be careful if you have Redux integration. Basically `router.getStateForAction` might return `null`. So you have to do something like this 
```
Navigator.router.getStateForAction(action, state) || state;
```

**Comment by ericvicenti** [comment]
Thanks @dominicrj23, I also think this works. Thanks for the reminder about the tricky redux integration!
