### ISSUE TITLE
TabNavigation Icon is cut off

### ISSUE THREAD

**Issue by Catharsis68** [react-community/react-navigation#896]
![screenshot_2017-04-03-15-35-52-01](https://cloud.githubusercontent.com/assets/6165055/24611935/0a63f4c2-1884-11e7-9724-dfb4df469b47.jpeg)

I created a `TabNavigator` with three screens, each screen got an Icon from `MaterialIcons` in `navigationOptions`.
The icons get cut off if I set the size > 26. Is there any possibility to increase the size for the icons in the TabNavigator? 

Best regards, Markus

```
const SettingsScreen = ({ navigation }) => (
  <Settings
    banner={'Settings Screen'}
    navigation={navigation}
  />
);
SettingsScreen.navigationOptions = {  
  tabBar: ({ state, setParams }) => ({
    icon: ({ tintColor }) => (
      <MaterialIcons
        name="settings"
        size={ 30 } 
        style={{ color: tintColor }}
      />
    ),
  }),
};
```

**Comment by navid94** [comment]
See issue #677. They made a pull request but got rejected. I need this feature too.

**Comment by TestTitans** [comment]
I try custom view and I need this feature.max Size 26 is not useful.

 icon: ({tintColor}) => {  return( <TouchableOpacity onPress={() =>
{animate();try{state.state.params.reRequest();}catch(e){console.log('errr '+e)}}}>
       
            <View style={{flex:1,backgroundColor:'blue'}} >
           
              {state.state.params.cartItemCount==0?null:circleFactory(state.state.params.cartItemCount*10)}
          <Icon name='shopping-basket'
            type='font-awesome' size={30} color={tintColor} />
         
         <View style={{backgroundColor:'red',position:'absolute',top:1,right:0,width:20,height:20,borderRadius:11,borderWidth:2,
    borderColor: 'red'}}><Text style={{color:'white',fontSize:12,textAlign:'center',fontWeight:'bold'}}>{state.state.params==undefined?0:state.state.params.cartItemCount}</Text></View>
        </View>
   </TouchableOpacity>)  }

**Comment by satya164** [comment]
Use `label` and render what you want. There is no size restriction for label.

**Comment by satya164** [comment]
> @navid94 : They made a pull request but got rejected.

Which pull request got rejected?

**Comment by navid94** [comment]
@satya164 #677 was rejected, but now with #965 the fix is in master. You can use iconStyle: { width, height} to render the icon with the right size and without being clipped. @Catharsis68 @TestTitans you can point to master with 
```
npm install react-navigation@https://github.com/react-community/react-navigation.git --save
```
and use iconStyle prop, just a temporary solution until v1.0.0 beta 8 comes out.

**Comment by satya164** [comment]
It was not rejected. It was still open, changes were requested and the author hadn't made the changes yet.

**Comment by navid94** [comment]
@satya164 ok

**Comment by studiobrain** [comment]
I have included the latest from master:
`"react-navigation": "https://github.com/react-community/react-navigation.git"`
...and I am using the tabs as such:
```export const Tabs = TabNavigator({
  Profile: {
    screen: Profile,
    navigationOptions: {
      tabBar: {
        label: 'Profile',
        icon: ({tintColor}) => <Icon name='ios-contact' size={38} color={tintColor}/>
      }
    },
  }, 
...
```
```
..., {
  animationEnabled: true,
  swipeEnabled: true,
  tabBarPosition: 'bottom',
  tabBarOptions: {
    iconStyle: {
      width: 100,
      height: 100,
      paddingBottom: 10,
    },
```

...but alas no change and the cropped icon is limited to size 29 on Android...

**Comment by navid94** [comment]
@studiobrain check if iconStyle prop is present in file
```
node_modules/react-navigation/src/views/TabView/TabBarTop.js
```

otherwise it means that you don't have installed it correctly.

Mine setup is:

```
static navigationOptions = {
        header: {
            visible: false
        },
        tabBar: {
            icon: ({ tintColor }) => {
                return (
                    <FontAwesome
                        name='cubes'
                        size={27}
                        color={ tintColor }
                    />
                );
            }
        }
    }
```
```
var MainTabNavigator = TabNavigator({
    ...
}, {
    lazyLoad: true,
    animationEnabled: false,
    tabBarOptions: {
        activeTintColor: '#3b5998',
        inactiveTintColor: '#cccccc',
        showIcon: true,
        showLabel: false,
        iconStyle: {
            width: 35,
            height: 30
        },
        style: {
            backgroundColor: 'white'
        },
        pressColor: '#d5dcea',
        indicatorStyle: {
            backgroundColor: 'white'
        }
    }
});
```

and it works. Maybe your icon is too big and you have to increase the size of the tab bar with the style prop.

**Comment by studiobrain** [comment]
Yeah, I checked and it is found.  Im currently using `react-native-vector-icons/Ionicons` and have a width and height set on style:
```
style: {
      backgroundColor: common.baseHex,
      borderTopWidth: 2,
      borderTopColor: "white",
      height: viewport.width * 0.2,
      width: viewport.width,
    },
```

It works fine on iOS, at least the icons render as expected.  On Android I see the cropping, but also Im not sure the iconStyles are even being rendered.  Are there any other params I can try to see if they are being read?  backgroundColor or any positioning doesnt work either.  I will continue to debug.

**Comment by navid94** [comment]
@studiobrain sorry but I don't know then, the IconStyle prop it's a normal style object for a view containing the icon, see [https://github.com/react-community/react-navigation/blob/master/src/views/TabView/TabBarIcon.js](url). 
You can also try increasing the dimensions of the single tab with tabStyle prop.

**Comment by studiobrain** [comment]
@navid94 I just wanted to respond back and let you know that after closing the server and simulator for both android and ios and then running the server (I run each platform on a separate port) and building, the `iconStyle` started rendering as expected!  Thanks!

**Comment by navid94** [comment]
@studiobrain nice!

**Comment by rom1k** [comment]
Is it possible to prevent the height of the tab bar from growing when chaning iconStyle size. It looks like there's a fixed padding around the icon.

**Comment by navid94** [comment]
@rom1k if you want to increase the size of the icon without the tab bar increasing its size, you have to use the prop size directly on the icon:

```
import MaterialIcons from 'react-native-vector-icons/MaterialIcons';
static navigationOptions = {
        header: {
            visible: false
        },
        tabBar: {
            icon: ( { tintColor }) => {
                return (
                    <MaterialIcons
                        name='format-list-bulleted'
                        size={30}
                        color={ tintColor }
                    />
                );
            }
        }
    };
```

**Comment by rom1k** [comment]
@navid94 
I did that, but I want to have a badge on the top right of my tab icon, but it is clipped. That's why I'm trying increase the size of the icon container but that causes the whole tab bar to grow.

**Comment by navid94** [comment]
@rom1k try using the prop 
```
tabStyle: {
    height: value
}
```

i tried and it decrease the size of the tab bar even if iconStyle has major height.

**Comment by rom1k** [comment]
@navid94 
That's what I did. Maybe it's because i'm using a bottom tab bar?

**Comment by navid94** [comment]
@rom1k i tried this setup:

```
var MainTabNavigator = TabNavigator({
    ...
}, {
    lazyLoad: true,
    animationEnabled: false,
    tabBarPosition: 'bottom',
    tabBarOptions: {
        activeTintColor: '#3b5998',
        inactiveTintColor: '#cccccc',
        showIcon: true,
        showLabel: false,
        iconStyle: {
            width: 35,
            height: 60
        },
        tabStyle: {
            height: 40
        }
        style: {
            backgroundColor: 'white'
        },
        pressColor: '#d5dcea',
        indicatorStyle: {
            backgroundColor: 'white'
        }
    }
});
```

```
static navigationOptions = {
        header: {
            visible: false
        },
        tabBar: {
            icon: ( { tintColor }) => {
                return (
                    <MaterialIcons
                        name='format-list-bulleted'
                        size={70}
                        color={ tintColor }
                    />
                );
            }
        }
    };
```
this is the result, isn't that what you want?
https://s22.postimg.org/xt7etgl01/Screenshot_2017-04-12-11-11-22.png

**Comment by eladcandroid** [comment]
@navid94 It works! Thanks!

**Comment by Unlighten** [comment]
Sorry guys I am still struggling here. Can you guys take a look at this. My icons are still getting cut off on android only.


    "react-navigation": "1.0.0-beta.11",

tabNavigation.js
```
const HomeTabNavigation = TabNavigator(
  
  {
    Profile: { screen: Profile },
    PhotoCard: { screen: PhotoCard },
    Chat: { screen: Chat }
  },
  {
    tabBarPosition: "bottom",
    // animationEnabled: true,
    initialRouteName: "PhotoCard",
    swipeEnabled: false,
    lazy: true,
    tabBarOptions: {
      activeTintColor: '#0080FF',
      inactiveTintColor: '#f4f4f4',
      showIcon: true,
      showLabel: false,
      pressColor: '#0080FF',
      // iconStyle: {
      //   width: 20,
      //   height: 20,
      //   color: '#0080FF'
      // },
      style: {
        backgroundColor: 'white',
        borderTopColor: 'white',
        borderTopWidth: 1,
        height: metrics.DEVICE_HEIGHT * 0.08
      },
      tabStyle: {
        width: metrics.DEVICE_WIDTH / 3,
      },
      indicatorStyle: {
        backgroundColor: 'white',
      },
    },
  }
);


```

  static navigationOptions = {
    header: {
      visible: false
    },
    tabBarIcon: ({ tintColor }) => {
      return(
       <Icon name="ios-mail" 
        //  size={27}
         color={tintColor}
        />
      )
    }
  }

**Comment by alainib** [comment]
i still get this bug on tablet, not on smartphone strange.


    const MyTabView = createBottomTabNavigator(
      {
        FeedObservations: { screen: FeedObservations },
        Projects: { screen: Projects },
        NewObservation: { screen: NewObservation },
        Explorer: { screen: Explorer },
        Profil: { screen: Profil }
      },
      {
        swipeEnabled: false,
        initialRouteName: initialRouteName,
        tabBarPosition: "bottom",
        tabBarOptions: {
          activeTintColor: "green",
          pressColor: "green",
          inactiveTintColor: "#373738",
          showIcon: true,
          showLabel: false,
          style: {
            backgroundColor: "white"
          },

          indicatorStyle: {
            backgroundColor: "green"
          } 
        }
      }
    );


  And the component who display the truncated camera icon



    export default class NewObservation extends React.PureComponent {
      static navigationOptions = ({ navigation }) => {
        return {
          tabBarIcon: ({ tintColor }) => (
            <TouchableOpacity
              underlayColor={"green"}
              onPress={() => {
                navigation.navigate("AddObservation");
              }}
            >
              <IconIonic name="md-camera" size={20} color={tintColor} />
            </TouchableOpacity>
          ),
          tabBarOnPress: () => {
            // ticket en cour https://github.com/react-navigation/react-navigation/issues/5708
            navigation.navigate("AddObservation");
          }
        };
      };

      render() {
        return <AddObservation />;
      }
    }

Version
   
    "react": "^16.8.4"
    "react-native": "^0.59.2"
    "react-native-vector-icons": "^6.4.0"  


Any fix ? thanks

**Comment by konjoinfinity** [comment]
> Use `label` and render what you want. There is no size restriction for label.

This is a great solution, thank you!  If anyone is interested in our usage:

```
tabBarLabel: ({ tintColor }) => (<View style={{ flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", paddingBottom: 20 }}><Icon name="home" color="#4db6ac" size={addButtonSize === "tablet" ? 50 : 25} /><Text style={{ fontSize: addButtonSize === "tablet" ? 25 : 10, color: tintColor }}>Home</Text></View>)
```

**Comment by konjoinfinity** [comment]
> > Use `label` and render what you want. There is no size restriction for label.
> 
> This is a great solution, thank you! If anyone is interested in our usage:
> 
> ```
> tabBarLabel: ({ tintColor }) => (<View style={{ flexDirection: "column", justifyContent: "center", alignItems: "center", alignContent: "center", paddingBottom: 20 }}><Icon name="home" color="#4db6ac" size={addButtonSize === "tablet" ? 50 : 25} /><Text style={{ fontSize: addButtonSize === "tablet" ? 25 : 10, color: tintColor }}>Home</Text></View>)
> ```

Also make sure to set showLabel to true and showIcon to false:

```
tabBarOptions: { 
showLabel: true, 
showIcon: false, 
tabStyle: { 
height: Dimensions.get('window').height * 0.088, 
width: Dimensions.get('window').width * 0.25 
}
                },
```
