### ISSUE TITLE
Using Android native cancel and back buttons?

### ISSUE THREAD

**Issue by suhshinhwang** [react-community/react-navigation#897]
Is there a way to use native Cancel and Back buttons used by Android without using the `<Image />` component to display them?

An example of the Cancel and Back button can [be seen here](https://i.stack.imgur.com/IAus6.png).

**Comment by Ehesp** [comment]
Please show an example of what buttons you mean.

**Comment by suhshinhwang** [comment]
@Ehesp I've updated my comment to include an example.

**Comment by satya164** [comment]
Juts show an image/icon. There is nothing wrong with that.

**Comment by Ehesp** [comment]
The back button can be nabbed from `CardStack.Header.BackButton`. As for the Cancel button, you're probably best rendering this from `react-native-vector-icons/MaterialIcons`. There'd be no reason for this lib to export the latter as I don't believe it's needed.
