### ISSUE TITLE
Possibility to adjust drawer active sliding PanResponder value

### ISSUE THREAD

**Issue by sonaye** [react-community/react-navigation#899]
Can this be achieved? I got some [feedback](https://github.com/sonaye/milk-station/issues/34) from from a tester that the area for slide-to-open was too narrow. No info on that in the docs.

**Comment by AlanFoster** [comment]
Hey; I assume that link is a private repo? It currently results in a 404 🤔

**Comment by sonaye** [comment]
ah yes, my bad, but you get the idea.

**Comment by AlanFoster** [comment]
Taking a look at the source code for react-navigation, the [DrawerView](https://github.com/react-community/react-navigation/blob/83f8a44219728f694f20b384c120154517fae06d/src/views/Drawer/DrawerView.js#L118) depends on [react-native-drawer-layout-polyfill](https://github.com/react-native-community/react-native-drawer-layout-polyfill), which then transitively depends on [react-native-drawer-layout](https://github.com/react-native-community/react-native-drawer-layout/blob/master/src/DrawerLayout.js)

It doesn't initially seem like this is configurable, but it would be worth a further poke to confirm :+1:

**Comment by sonaye** [comment]
@AlanFoster Thanks for pointing that out, I will take a look.

**Comment by ericvicenti** [comment]
Which OS? On Android it uses the native implementation, but on iOS it should be customizable within JS somehow

**Comment by sonaye** [comment]
@ericvicenti IOS, on android it's looking good.

**Comment by sonaye** [comment]
I am closing this one, I came to the conclusion that it's best to leave this property in the hands of the libraries that mange it.

**Comment by AlanFoster** [comment]
@sonaye I think that's a good call too :+1:
