### ISSUE TITLE
Website: command-click should not handle inside page

### ISSUE THREAD

**Issue by ericvicenti** [react-community/react-navigation#9]
Cmd-click on the website is broken

**Comment by ericvicenti** [comment]
Can somebody help fix this? Should be pretty easy to add a special case in the onClick handler:

https://github.com/react-community/react-navigation/blob/master/website/src/Link.js#L30

**Comment by irskep** [comment]
It really worries me that that navigation requires special JS routing rather than just working with browser events. It means you have to implement hacks like the one you suggested, or the one in the referenced PR.

**Comment by ericvicenti** [comment]
@irskep , sorry I'm a bit confused what the hack is.

Because of the [server rendering](https://github.com/react-community/react-navigation/blob/master/website/src/Server.js), React Navigation works great in browsers without JS. So I would not say it requires special JS routing.

For browsers that do have JS, we can improve page load time by blocking the browser navigation, and switching pages in JS. This will also allow us to implement animations and make the app feel faster.

There is no other standard way to speed up page transitions, so this technique is not considered a hack. It is a [web standard](https://developer.mozilla.org/en-US/docs/Web/API/History_API) and is supported by all major browsers.
