### ISSUE TITLE
When wrapping nested navigator: navigation.states.routes is not an object

### ISSUE THREAD

**Issue by EmielM** [react-community/react-navigation#90]
```js
function TestTab() {
    return <Text>text</Text>;
};

const TabNav = TabNavigator({
    A: {screen: TestTab},
    B: {screen: TestTab}
});

function HomeScreen(props) {
    return <TabNav navigation={props.navigation} />;
}

const AppNavigator = StackNavigator({
    Home: { screen: HomeScreen }
});
```

results in: `undefined is not an object (evaluating navigation.state.routes.forEach')`.

Reason is me passing down `navigation` to the sub-navigator, which seems to be the idea, right? Whenever I don't wrap as `HomeScreen`, but directly use `TabNav` as screen, it works fine.

**Comment by satya164** [comment]
Do this, `HomeScreen.router = TabNav.router`

PR welcome to add this to the docs and improve the error message.

**Comment by EmielM** [comment]
Ugh, my actual case involves a lot more wrapped elements (of which some are anonymous HOC's), it's not really easy to assign statics to them. Why is this needed?

**Comment by EmielM** [comment]
Also, I think a common use case would be that you create `TabNav` conditionally in your wrapping component (`HomeScreen` in this example), how would you then assign its `.router`?

**Comment by satya164** [comment]
> Why is this needed?

This is needed so that the parent navigator manages the state and need to know about child routes to be able to do that.

> my actual case involves a lot more wrapped elements

You just need to add the static to the screen which is passed to the navigator. You can also pass a `containerOptions` to your navigator so that it manages it's state instead of the root navigator - https://reactnavigation.org/docs/navigators/custom.

Though doing that means you won't able to navigate to a route of child navigator from parent navigator.

> Also, I think a common use case would be that you create TabNav conditionally in your wrapping component (HomeScreen in this example), how would you then assign its .router?

We don't support creating navigators dynamically. If you want to conditionally render screens, just create a stack navigator with the two child navigators and conditionally navigate to the correct route. Right now you can't specify `initialRoute` dynamically, but #85 aims to address that.

**Comment by EmielM** [comment]
Thanks for your elaborate (and very quick!) answer, @satya164. It's unfortunate, but I guess a side-effect of wanting to manage the complete navigation state on some level.

BTW: couldn't the context api or some kind of `navigation.registerSubNavigator` API in the child be used to do it automatically? Or is render-time too late? If render-time would work, it would perhaps also enable dynamic creation of sub-navigators?

**Comment by satya164** [comment]
@EmielM Can probably do. Haven't explored it yet.

**Comment by stief510** [comment]
@satya164 Do you mind elaborating on how to get the routes to show up?

**Comment by YasirPanjsheri** [comment]
@satya164  hi, where do we add `HomeScreen.router = TabNav.router` 
I am facing the same in trying out the example in React Navigation site

```
import React, {Component} from 'react'
import { AppRegistry, View, Text, Button } from 'react-native'
import { TabNavigator, StackNavigator } from "react-navigation";

class ChatScreen extends React.Component {
  // Nav options can be defined as a function of the screen's props:
  static navigationOptions = ({ navigation }) => ({
    title: `Chat with ${navigation.state.params.user}`,
  });
  render() {
    // The screen's current route is passed in to `props.navigation.state`:
    const { params } = this.props.navigation.state;
    return (
      <View>
        <Text>Chat with {params.user}</Text>
      </View>
    );
  }
}

class RecentChatsScreen extends Component {
  render() {
    return (
      <View>
        <Text>List of recent chats</Text>
        <Button
          onPress={() => this.props.navigation.navigate('Chat', { user: 'Lucy' })}
          title="Chat with Lucy"
        />
      </View>
    );
  }
}

class AllContactsScreen extends Component {
  render() {
    return (
      <View>
        <Text>List of all contacts</Text>
          <Button
            onPress={() => this.props.navigation.navigate('Chat', { user: 'Lucy' })}
            title="Chat with Lucy"
          />
      </View>
    );
  }
}

class NavigatorWrappingScreen extends React.Component {
  render() {    
    return (
      <View>
        <SomeComponent/>
        <MainScreenNavigator navigation={this.props.navigation}/>
      </View>
    );
  }  
}
  NavigatorWrappingScreen.router = MainScreenNavigator.router;

class SomeComponent extends Component {
  render() {
    return <Text>SOME COMPONENT</Text>
  }
}

const MainScreenNavigator = TabNavigator({
  Recent: { screen: RecentChatsScreen },
  All: { screen: AllContactsScreen },
});

const SimpleApp = StackNavigator({
  Home: { screen: NavigatorWrappingScreen },
  Chat: { screen: ChatScreen },
})

AppRegistry.registerComponent('myTest', () => SimpleApp);
```

I receive this error `undefined is not an object (evaluating 'MainScreenNavigator.router')`
