### ISSUE TITLE
How to use TabNavigator as Component

### ISSUE THREAD

**Issue by Kishanjvaghela** [react-community/react-navigation#903]
I have screen in StackNavigator and in that I want to display.

StackNavigator
- Screen 1
- Screen 2
      - Screen A (This will have TAB ) as below image. 
- Screen 3

Screen A
![github](https://cloud.githubusercontent.com/assets/11232063/24651314/03b7a53e-194b-11e7-945f-f8115b849064.jpg)

Can anyone explain how can I achieve this.
Thanks in advance.

**Comment by AlanFoster** [comment]
@Kishanjvaghela Are you wanting to [nest navigators](https://reactnavigation.org/docs/intro/nesting) ?

**Comment by Kishanjvaghela** [comment]
@AlanFoster Yes same as nesting navigator. But I want to display some layout between header and Tab.

**Comment by StephenStrickland** [comment]
@Kishanjvaghela 
You could do something like:
```js
Screen2: {
   screen: TabNavigator({
      Index:{screen:ScreenA}}, 
      {initialRouteName: 'Index'}
)}
```

**Comment by Kishanjvaghela** [comment]
@StephenStrickland but where to display my layout?? I want to display some layout between header of stack navigator and tab bar
![img_3494](https://cloud.githubusercontent.com/assets/11232063/24667690/ee93ef5a-1981-11e7-9178-7e3e3beabf34.JPG)

**Comment by bcarroll22** [comment]
The result of creating a `TabNavigator` is a component you can use the way you want to. There's nothing that would stop you from making the view like the picture you showed. 

That being said there are a few gotchas to look out for. You'll find everything you need in previously closed issues or the docs.

**Comment by Kishanjvaghela** [comment]
@bcarroll22 I tried TabNavigator as component. But it is not displaying. below is my  code

```
class RecentChatsScreen extends React.Component {
    render() {
      return <Text>List of recent chats</Text>
    }
  }

  class AllContactsScreen extends React.Component {
    render() {
      return <Text>List of all contacts</Text>
    }
  }

  const TabScreen = TabNavigator({
    Recent: { screen: RecentChatsScreen },
    All: { screen: AllContactsScreen },
  });  
```
Screen A
```
export default class UserDetailScreen extends Component {  
  render(){
    return(
      <View>      
        <Text>
          UserDetailScreen
        </Text>
        <TabScreen/>
      </View>
    );
  }
}

```

**Comment by laksh1010** [comment]
I'm also in same situation. Did you fixed it mate

**Comment by somnathbm** [comment]
Try setting `flex: 1` to the View.

**Comment by rpss2** [comment]
@somnathbm You're right, I was in same situation as @Kishanjvaghela , but putting flex: 1 to the parent View it worked.
Thanks.

**Comment by Kishanjvaghela** [comment]
This is worked for me https://reactnavigation.org/docs/en/common-mistakes.html#explicitly-rendering-more-than-one-navigator

```export default class App extends React.Component {
  render() {
    /* In the root component we are rendering the app navigator */
    return <AppContainer />;
  }
}

const AuthenticationNavigator = createStackNavigator({
  SignIn: SignInScreen,
  ForgotPassword: ForgotPasswordScreen,
});

class AuthenticationScreen extends React.Component {
  static router = AuthenticationNavigator.router;

  render() {
    return <AuthenticationNavigator navigation={this.props.navigation} />;
  }
}

const AppNavigator = createSwitchNavigator({
  Auth: AuthenticationScreen, // This screen renders a navigator!
  Home: HomeScreen,
});

const AppContainer = createAppContainer(AppNavigator);```

Can anyone help me to pass props? I want to pass props from AuthenticationScreen -> SignInScreen
