### ISSUE TITLE
DrawerNavigator : customise DrawerItem activeBackgroundColor for each item

### ISSUE THREAD

**Issue by IWCollege-AaronBentley** [react-community/react-navigation#904]
Hello 😀

I'm trying to set a unique activeBackgroundColor for each of the items in my DrawerNavigator but with no success so far.

Does anybody have an idea on how to accomplish this?

Thanks in advance 😀

**Comment by ericvicenti** [comment]
It sounds like you would be best off customizing the `contentComponent` of the DrawerNavigator

https://reactnavigation.org/docs/navigators/drawer#DrawerNavigatorConfig
