### ISSUE TITLE
Last button of tab navigator expands on second render

### ISSUE THREAD

**Issue by pavlelekic** [react-community/react-navigation#907]
I have a strange situation where when I render a secondary (nested) tab navigator, the first time it renders it looks ok, but as soon as I start pressing different tabs the right most tab bar button widens. I tried making a custom tab navigator using your TabView.TaabBarBottom as a starting point, but still I encounter the same bug. This is happening when I have 3 buttons in the tab bar, but I haven't tried it might happen with two buttons too.

**Comment by ericvicenti** [comment]
Hmm, maybe the title is changing, and causing the label to change size? Is the label explicitly provided for each tab?

Maybe you can post a gif of this behavior, with some simple example code to help us replicate the problem?

**Comment by pavlelekic** [comment]
Label is the same, hardcoded. Here is the code:

`
import React from 'react';
import {View, StyleSheet} from 'react-native';
import {TabNavigator, TabView} from 'react-navigation';

const MyLessonsNavigator = TabNavigator(
    {
        DailySchedule: {
            screen: () => (<View style={{backgroundColor: 'blue', flex: 1}}/>),
            navigationOptions: {
                tabBar: {
                    label: 'Daily Schedule'
                }
            }
        },
        WeeklyTimetable: {
            screen: () => (<View style={{backgroundColor: 'orange', flex: 1}}/>),
            navigationOptions: {
                tabBar: {
                    label: 'Weekly Timetable'
                }
            }
        },
        MyCalendar: {
            screen: () => (<View style={{backgroundColor: 'yellow', flex: 1}}/>),
            navigationOptions: {
                tabBar: {
                    label: 'My Calendar'
                }
            }
        }
    },
    {
        tabBarComponent: TabView.TabBarTop,
        tabBarPosition: 'top',
        swipeEnabled: true
    }
);
`

Here is an animated gif, https://ibb.co/nJzmDv
You can see how the right most button moves about 10px to the left after I press on other buttons.

**Comment by ericvicenti** [comment]
Oh, strange. Looks like a bug in the tab view. cc @satya164 

If you find the fix, it would be greatly appreciated!

**Comment by satya164** [comment]
Not sure why the issue will occur. The tabbar is basically

```js
<View>
   <View style={{ flex: 1 }} />
   <View style={{ flex: 1 }} />
   <View style={{ flex: 1 }} />
</View>
```

So unless something inside the tab bar changes, or the container width changes, the width won't change. Can you check if any of the above happens in your case?

**Comment by pavlelekic** [comment]
Container width didn't change, I checked. And inside the tab bar I have blank screens like <View style={{backgroundColor: 'yellow', flex: 1}}/>, so they are static and don't change.

**Comment by pavlelekic** [comment]
The issue is that all buttons after the first one on the left move a bit. So the first one doesn't change, only the ones after.

**Comment by spencercarli** [comment]
Hi! Since this issue has been quiet for a while I'm going to go ahead and close it. If the issue persists in the latest version of React Navigation please re-open!
