### ISSUE TITLE
Unable to resolve ReactDebugCurrentFrame

### ISSUE THREAD

**Issue by JoeLanglois** [react-community/react-navigation#908]
I am on the latest react-native 0.43 and my package.json points to the master branch of this github.

` Unable to resolve module "react/lib/ReactDebugCurrentFrame" from /Users/Joe/Projects/pegasius/node_modules/react-native/Libraries/Renderer/src/renderers/shared/stack/reconciler/ReactCompositeComponent.js"`

**Comment by AlanFoster** [comment]
@JoeLanglois Out of interest, what version of react are you currently on? I noticed that the latest react-native 0.43 release depends on react 16.0.0-alpha.6

**Comment by wilomgfx** [comment]
I got that error as well on react ^15.4.2 and react-native 0.43, but upgrading to 16.0.0-alpha.6 fixed it. So id say.. stay away from 0.43 or use react 16.0.0-alpha.6

**Comment by AlanFoster** [comment]
This seems related to https://github.com/facebook/react-native/issues/13291 🤔

**Comment by jiggle** [comment]
installing 16.0.0-alpha.6 using `npm install react@16.0.0-alpha.6` in the project root folder worked for me, thanks for the solution

**Comment by spencercarli** [comment]
Hi! Since this issue has been quiet for a while I'm going to go ahead and close it. If the issue persists in the latest version of React Navigation please re-open!

**Comment by nicewaytodoit** [comment]
Just to add it may be useful for someone: 
This often happens when react and react-dom versions in pacakge.json are not compatible. 
Try changing there first.
