### ISSUE TITLE
Expose flow types for react-navigation

### ISSUE THREAD

**Issue by thurt** [react-community/react-navigation#912]
I would like to use flowtypes from react-navigation in my project.

I have raised a similar issue with react-native facebook/react-native#13237 and @janicduplessis already had a PR out to expose those types.

Is it possible to do similar work here in this repo to expose flowtypes for react-navigation? https://github.com/react-community/react-navigation/blob/master/src/react-navigation.js#L2

Thanks!

**Comment by ericvicenti** [comment]
Our flow types aren't perfect yet, but I am still excited about exporting them. A fix for this would be greatly appreciated!

**Comment by ferrannp** [comment]
In my case, I am integrating the state with my own redux store. For now I do like:

```js
import type { NavigationState } from 'react-navigation/src/TypeDefinition';

export type State = {
  +nav: NavigationState,
  ...
}
```

Not sure what is the preferred way? Either export directly `TypeDefinition` or declaring it as a module so I can use `[libs]` from `.flowconfig`.

**Comment by Palisand** [comment]
@ferrannp I had to ignore react-navigation tests that were giving me flow errors. Did you have to do the same?
```
[ignore]
.*/node_modules/react-navigation/src/__tests__/.*
.*/node_modules/react-navigation/src/views/__tests__/.*
.*/node_modules/react-navigation/src/routers/__tests__/.*
```

**Comment by zhigang1992** [comment]
@Palisand same here.

```
.*/node_modules/react-navigation/.*/__tests__/.*
```

**Comment by Sundin** [comment]
Thanks @zhigang1992 and @Palisand, saved my day!

**Comment by sibelius** [comment]
any example of typing Props with `NavigationScreenProp`?

**Comment by Palisand** [comment]
@sibelius You mean like this?
``` javascript
type NavigationState = {
  params: {
   foo: "bar",
  },
}

type Props = {
  navigation: NavigationScreenProp<NavigationState, *>,
}

const Component = ({navigation}: Props) => {
  ...
  navigations.state.params.foo
}
```

**Comment by sibelius** [comment]
tks, this looks good to me

**Comment by kelset** [comment]
A lot of work has been done related to flowtypes, is this issue still present?

Pinging OP @thurt , If no answer I'll close in 7 days.

**Comment by hawkrives** [comment]
@kelset I believe that flow types are only available by importing an internal file, `react-navigation/src/TypeDefinition`. I forgot to reply to this issue before it closed, apologies. 

(That is to say, types are not yet exported and I believe that this issue is still relevant.)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by kelset** [comment]
Ah gotcha.
I'll reopen and ping @Ashoat since he's our "god of Flow" ;) He may know/suggest a way to do this properly. I think it may even be a good first issue.

**Comment by sibelius** [comment]
You can include this file in your .flowconfig

**Comment by Ashoat** [comment]
I usually import them directly from that file. I wouldn't be opposed to exporting them directly from the library, however. Would welcome a PR!

**Comment by hawkrives** [comment]
@Ashoat Well, I'll try to whip one up then!

@sibelius Noted. I have never thought about using `[include]`. I'll check that out too!
