### ISSUE TITLE
Navigation not working in Nested Navigator

### ISSUE THREAD

**Issue by InteractiveLogic** [react-community/react-navigation#913]
Conceptually, this is roughly the structure I'm using:

* Stack Navigator 1
  * Screen 1
  * Screen 2
  * Tab Navigator
    * Tab 1 Stack Navigator
      * Tab 1 - Screen 1
    * Tab 2 Stack Navigator
      * Checklist
      * Zone
      * Info
      * Select
      * Measurements
  * Screen 3-5

After much work thus far, and using the technique in #335 I can navigate from Stack Navigator 1 to the Checklist, contained by the Tab Navigator.

Once at the Checklist, I can navigate to any of the "peer" screens with no issues (and can navigate back as well, by doing the technique of using setParams to wire up an `onBackButtonPress` instance method as an event handler).

So the weird thing is that if I navigate to the Checklist screen, and then do the following from that screen:

```

    this.props.navigation.navigate({
      name: 'Measurements',
    });

```

...no navigation occurs.  (sad trombone sound)

If I debug and inspect at the point of the method call, I have a navigation object, and it has a navigate method, but for some reason it's not actually _performing_ the navigation.

Any ideas on what might be going on here?

**Comment by InteractiveLogic** [comment]
OK I think I have this one solved for the time being. 

Even though `this.props.navigation.navigate()` doesn't work, `this.props.navigation.dispatch()` does. 

I discovered this by trying out `this.props.navigation.goBack()` just for kicks, and it worked... So the next step was to just use `dispatch()` (which I probably should have tried first... oh well).

Anyway I appear to be unblocked and will report back if I encounter any more funny business.

**Comment by mkozhukharenko** [comment]
> After much work thus far, and using the technique in #335 I can navigate from Stack Navigator 1 to the Checklist, contained by the Tab Navigator.

@InteractiveLogic how did you manage to do so? I tried all approaches listed in #335 but neither works

**Comment by beausmith** [comment]
@InteractiveLogic Found this Issue when looking for a solution. Ultimately this solution worked for my similar use case:
https://github.com/react-community/react-navigation/issues/1127#issuecomment-295841343
