### ISSUE TITLE
url/path bar on top to show current path?

### ISSUE THREAD

**Issue by MovingGifts** [react-community/react-navigation#916]
I read a medium article about react native navigation, and I thought it might have been this package, but I am not sure since I can't seem to find it after searching again for it.

Either way, what I discovered in the article's image/video was a url/path bar on top of each `scene` (I think it was a configurable option to show it). When shown, you can see the entire path, and if there was a `/path/:variable` the `:variable` would be the actual content (i.e. the actual `string/number`)

Does the url/path bar I described exist in `react-navigation` yet?

**Comment by ericvicenti** [comment]
This is not currently implemented with React Navigation, but you could use the router API to implement this in your app!
