### ISSUE TITLE
navigate back re-render 

### ISSUE THREAD

**Issue by TestTitans** [react-community/react-navigation#922]
default navigate back in stacknavigator doesnt fire render or componentmount,componentWillFocus,componentWillFocus bla bla bla 
How can I fire render method back is pressed

**Comment by dvdmmc** [comment]
We had a similar desire and solved it by passing a refresh function from the parent to the child.

for example, when you open the child, you would have something like `navigate('Child', { refresh: refreshFunction }`

You can then access this function in the child ( via something like `this.props.navigation.state.params.refresh()`; ) before the back action.

**Comment by TestTitans** [comment]
Thanks work like a charm.

**Comment by ericvicenti** [comment]
I don't think you should pass functions inside params like that, because route parameters are sometimes saved to disk, and functions cannot be saved like that.

Instead, maybe you can use a flux store or redux to change something on the second page, which you subscribe to from the first page?

**Comment by jszcl** [comment]
Thanks buddy

**Comment by manoharank** [comment]
I work around this by implementing a simple pub/sub like https://davidwalsh.name/pubsub-javascript

```js
// events.js

var events = {};
var hOP = events.hasOwnProperty;

export default {
  subscribe(event, listener) {
    // Create the event's object if not yet created
    if(!hOP.call(events, event)) events[event] = [];

    // Add the listener to queue
    var index = events[event].push(listener) -1;

    // Provide handle back for removal of event
    return {
      remove () {
        delete events[event][index];
      }
    };
  },

  publish (event, args) {
    // If the event doesn't exist, or there's no listeners in queue, just leave
    if(!hOP.call(events, event)) return;

    // Cycle through events queue, fire!
    events[event].forEach((fn) => {
        fn(args);
    });
  }
};
```

```js
// list.js

import Events from './events';

...

componentDidMount () {
  this.refreshEvent = Events.subscribe('RefreshList', () => this.refresh());
}

...

componentWillUnmount () {
  this.refreshEvent.remove();
}
```

```js
// edit.js

import Events from './events';

...

savve () {
  fetch().then(() => Events.publish('RefreshList');)
}
```

**Comment by njt1982** [comment]
@manoharank This seems to be a good way to go, although I am getting errors due to the refreshing the state of an unmounted page.

```
Warning: Can only update a mounted or mounting component. This usually means you called setState, replaceState, or forceUpdate on an unmounted component. This is a no-op.
```

So I fire the event (using publish as you do) from my "details" page which has the option to flag something as "pinned". Then the parent "search" page has a listener which triggers the "Refresh" method, which does a `setState` to pull the data back from Redux.

In your list.js example, what does refresh change? Is it a local variable or something?

**Comment by manoharank** [comment]
> I am getting errors due to the refreshing the state of an unmounted page.

I am not sure what's going wrong in your code, but in refresh you shouldn't modify state of `details` page.  Share the gist of your code to identify actual problem.

> In your list.js example, what does refresh change? Is it a local variable or something?
`refresh` is a function in list component to fetch data from server and setState in list component.

Please note that, I am not using redux (global state) in my app. I always fetch data from server using `fetch`. If you are using redux then you don't need the above workaround. You can use the redux actions to refresh the global state.

**Comment by njt1982** [comment]
Thanks @manoharank I'm using Redux to store "pinned" items. I've read that you can "connect" the redux store items to a component, but I'm not 100% clear on how that works/how it's implemented. Initially, in my `render()` I had a getter helper method in my store service which got the array of pinned items and that was provided as a dataArray to a `<List />` and it worked on load (so if I went all the way back to "Home" then navigated to the page, the componentDidMount would fire and retrieve the store data and render the list). However when I was on a detail page and pressed Pin, I could see from my Console Logging that the store had been changed (and if I did the whole "navigate back to the top and down again" method, it shows on the search). But when I went back from detail > search, then the pinned item was not listed.

Your explanation on changing state makes sense and the fact you refresh directly from a remote source makes sense too; but where do you store that result for render to use?

**Comment by manoharank** [comment]
@njt1982 Sorry, I am not expert in redux

> but where do you store that result for render to use?

I store the result in list component state `this.setState('list', [])`. Once the state is changed, the component will be re-rendered.

**Comment by staifn** [comment]
Put navigation to redux and connect your component to navigation state. There are two ways to do it. Either you add a custom navigation state with a callback: https://github.com/react-community/react-navigation/blob/master/docs/guides/Screen-Tracking.md, either you use the native integration of react-navigation: https://github.com/react-community/react-navigation/blob/master/docs/guides/Redux-Integration.md. The custom integration is the simplest way.

**Comment by kesiena115** [comment]
Could someone provide a bit more details or example about @dvdmmc solution. I don't understand what it does or how to include it in my code.

**Comment by beausmith** [comment]
@kesiena115 Here's how I used @dvdmmc's tip:

## Screen A
Method to do the thing in Screen A that you want to happen when navigating back from Screen B:
```js
onNavigateBackMethod = (foo) => {
  this.setState({
    foo
  })
}
```

This is the React Navigation method in Screen A to navigate to Screen B:
```js
this.props.navigation.navigate('ScreenB', {
  onNavigateBack: this.onNavigateBackMethod
})

```

## Screen B
After navigating to Screen B and ready to Navigate back to Screen A…

Call the function (passed to Screen B from Screen A) to do the thing in Screen A:
```js
this.props.navigation.state.params.onNavigateBack(this.state.foo)
```

Then call the React Navigation method to go Back (to Screen A):
```js
this.props.navigation.goBack()
// I'm actually using this method to go back: this.props.navigation.dispatch(NavigationActions.back())
```

Hope that helps. 🍏

**Comment by kesiena115** [comment]
Thanks @beausmith

**Comment by stanica** [comment]
A small addition to the solution posted by @beausmith 

I had to bind **this** to the function I was passing through to screen B:

this.props.navigation.navigate('ScreenB', {
  onNavigateBack: this.handleOnNavigateBack.bind(this)
})

**Comment by beausmith** [comment]
@stanica Interesting. Did you use an arrow function when defining `handleOnNavigateBack()`?

**Comment by stanica** [comment]
No, that would explain it. 

this.props.navigation.navigate('ScreenB', {item, onNavigateBack:(() => this.memberFunction())})

**Comment by imomer** [comment]
@beausmith worked for me like a charm ... Thanks Budd :)

**Comment by milon87** [comment]
but when to call this function if user press back button(Android) or slide back in (iOS)

**Comment by Kush5900** [comment]
please help about this react-navigation [issue](https://stackoverflow.com/questions/48222872/react-native-and-react-navigation-unable-to-pass-a-function-as-a-param-to-the-ne?s=1|161.9226) on how to pass a function as param in navigationOptions

**Comment by koswarabilly** [comment]
@milon87 you just need to set up `backhandler` in react native

**Comment by koswarabilly** [comment]
@stanica i have a question, what if the case is i navigate to another stack which in that other stack i have made reset action or something like that, the params will be deleted as i reset navigation. so what can i do to solve it?

**Comment by kcirred-setybaxe** [comment]
how to handle this on iOS swipe back?

**Comment by just4fun** [comment]
My case is, navigate from screen A (card) to screen B (mode), after I finished my work in screen B, I will close screen B (`navigation.goBack()`) then fetch the list again in screen A to get the new stuff which added in screen B.

My solution is using `connect()` in screen A, and call fetch function before we call `goBack()` in screen B. In this case screen A will know 'hey the list we connected has updated, so let's re-render'.

**Comment by koswarabilly** [comment]
@just4fun what do you mean by `connect()` can you give us a full example? in my case the solution provided above is good which pass function as parameter to the navigated screen. in my case, i navigate to another stack which works fine at first. but using the navigation options `reset` inside the navigated stack the passed function disappeared which cause error when i `goBack()` to previous screen

**Comment by SurajMDurgad** [comment]
@beausmith 
Hi,

When I implement your method I get an error saying "Can only update a mounted or mounting component. This usually means you called setState, replaceState, or forceUpdate on an unmounted component. This is a no-op."

Any work around?

**Comment by beausmith** [comment]
@SurajMDurgad I got this error too. Is your callback function an arrow function or does it bind `this` correctly? Make sure when you navigate back that the component you are going back to isn't being un/remounted. Also, google for that error and then look at the places where you "setState, replaceState, or forceUpdate on an unmounted component".

**Comment by axlider** [comment]
I use redux in my project and faced the same problem. 
Although I don't use redux for navigation as there is a warning (https://reactnavigation.org/docs/redux-integration.html).

brentvatne's solution worked best for me.

```
class MyContainer extends Component {

  willFocus = this.props.navigation.addListener(
    'willFocus',
    payload => {
      this.forceUpdate();
    }
  );
```

**Comment by TejasSJ** [comment]
Thanks @beausmith Worked for me!

**Comment by Mixpeal** [comment]
@Albert0405 , trust me, your answer should be kept in world museum 🥇 , worked perfectly

**Comment by ryanefendy95** [comment]
What's consider the best practice for `addListener`

- Inside constructor
```
constructor(props) {
    super(props);

    this.willFocus = this.props.navigation.addListener('willFocus', () => {
      // do something
    });
  }
```

- Inside componentDidMount
```
componentDidMount() {
    this.willFocus = this.props.navigation.addListener('willFocus', () => {
      // do something
    });
  }
```

Coming from angular - Mostly we use `ngOnInit` (also a life cycle hook called by Angular) for all the initialization/declaration and avoid stuff to work in the constructor. The constructor should only be used to initialize class members but shouldn't do actual "work". Assuming this best practice carry over to React, is better to have `addListener` in  `componentDidMount`?

**Comment by darshancreed** [comment]
> We had a similar desire and solved it by passing a refresh function from the parent to the child.
> 
> for example, when you open the child, you would have something like `navigate('Child', { refresh: refreshFunction }`
> 
> You can then access this function in the child ( via something like `this.props.navigation.state.params.refresh()`; ) before the back action.

hey dude i agree with this but when i press a default android back button which function will trigger thats the question please help me

**Comment by Isra-ib1403846** [comment]
@beausmith you are amazing thank you <3

**Comment by gauravgrover95** [comment]
> @kesiena115 Here's how I used @dvdmmc's tip:
> ## Screen A
> 
> Method to do the thing in Screen A that you want to happen when navigating back from Screen B:
> 
> ```js
> handleOnNavigateBack = (foo) => {
>   this.setState({
>     foo
>   })
> }
> ```
> 
> This is the React Navigation method in Screen A to navigate to Screen B:
> 
> ```js
> this.props.navigation.navigate('ScreenB', {
>   onNavigateBack: this.handleOnNavigateBack
> })
> ```
> 
> …or if your `handleOnNavigateBack` function is not a arrow function (which binds `this`) you'll need to bind `this`: (ht @stanica)
> 
> ```js
> this.props.navigation.navigate('ScreenB', {
>   onNavigateBack: this.handleOnNavigateBack.bind(this)
> })
> ```
> 
> ## Screen B
> 
> After navigating to Screen B and ready to Navigate back to Screen A…
> 
> Call the function (passed to Screen B from Screen A) to do the thing in Screen A:
> 
> ```js
> this.props.navigation.state.params.onNavigateBack(this.state.foo)
> ```
> 
> Then call the React Navigation method to go Back (to Screen A):
> 
> ```js
> this.props.navigation.goBack()
> // I'm actually using this method to go back: this.props.navigation.dispatch(NavigationActions.back())
> ```
> 
> Hope that helps. 🍏

Thanks for the detailed reply. Working great for me :-)

**Comment by gauravgrover95** [comment]
@beausmith  

Thanks for the detailed reply. Working great for me :-)

**Comment by kpose** [comment]
@alz10, your solution saved me after hours of running around. Thanks

**Comment by sunilmanipara** [comment]
Thanks @alz10 it's working for me

**Comment by ndrppnc** [comment]
For those of you using newer versions of React Native and/or function components, here's the solution in a nutshell:

`useEffect(() => {
    props.navigation.addListener('focus', () => {
      loadAccount();
    });

    loadAccount();
  }, []);`

This code will call `loadAccount()` when the component first loads. Then it will load it again, every time you re-focus (go back) to the component – achieving the intended re-render on navigating back.

**Comment by VictorPullzz** [comment]
I think it should be a lot easier. I tried using navigation.navigate.reset('Screen_to_Back') (in 4x version), and it worked for me. In general, it would be nice if there were fewer 'crutches' in the React :)

**Comment by olamigokayphils** [comment]
A little change: 
- (a) `focus` should be `willFocus`, 
- (b) `[x]` can be removed if there is no (additional) depending variable to be considered.
```
useEffect(() => {
     props.navigation.addListener(
         "willFocus",
          () => {
               // Call your function here..  e.g dispatch(loadAccount())
         }
})
```

> For those of you using newer versions of React Native and/or function components, here's the solution in a nutshell:
> 
> ```
> useEffect(() => {
>     props.navigation.addListener('focus', () => {
>       loadAccount();
>     });
> 
>     loadAccount();
> }, []);
> ```
> 
> This code will call `loadAccount()` when the component first loads. Then it will load it again, every time you re-focus (go back) to the component – achieving the intended re-render on navigating back.

**Comment by fxbayuanggara** [comment]
Thanks @olamigokayphils

**Comment by omar-bakhsh** [comment]
> A little change:
> 
> * (a) `focus` should be `willFocus`,
> * (b) `[x]` can be removed if there is no (additional) depending variable to be considered.
> 
> ```
> useEffect(() => {
>      navigation.addListener(
>          "willFocus", // or " didFocus"
>           () => {
>                // Call your function here..  e.g dispatch(loadAccount())
>          }
> })
> ```
> 
> If anyone experiences any lag in the transition animations... **add navigation prop into the dependencyList.**
> i.e
> 
> ```
> useEffect(() => {
>      navigation.addListener(
>          "willFocus", // or " didFocus"
>           () => {
>                // Call your function here..  e.g dispatch(loadAccount())
>          }
> }, [navigation])
> ```
> 
> > For those of you using newer versions of React Native and/or function components, here's the solution in a nutshell:
> > ```
> > useEffect(() => {
> >     props.navigation.addListener('focus', () => {
> >       loadAccount();
> >     });
> > 
> >     loadAccount();
> > }, []);
> > ```
> > 
> > 
> > This code will call `loadAccount()` when the component first loads. Then it will load it again, every time you re-focus (go back) to the component – achieving the intended re-render on navigating back.

can't find var navigation, have navigation v-4
