### ISSUE TITLE
[TabNavigator] onPress Override

### ISSUE THREAD

**Issue by rileybracken** [react-community/react-navigation#932]
Use Case:
If a app has a tab that requires authentication and there is no session present it should pop up a modal prompting login or signup.

I haven't dug too much into react-navigation's API. After converting from React Native's `Navigation` and `TabBarIOS` I find that this is the only thing I am really missing.

I would like to look into this and possibly open a PR if no one else is working on it currently.

In a quick search I found this issue #546, and the recommended solution is to build your own custom tab bar.

**Comment by jayesbe** [comment]
I have been working on this for a couple hours and finally found a solution that doesn't use Redux. (The app I am working on has an explicit, Redux ONLY when Redux is absolutely necessary policy, so far we've not needed Redux in any way :)

I used this as a basis for the solution (https://reactnavigation.org/docs/routers/#Handling-Custom-URIs)

Heres the jist 

```

const MyTabNav = TabNavigator({
  Tab1: {
    screen: Tab1,
    navigationOptions: {
      title: 'Tab1',
    }
  },
  Tab2: {
    screen: Tab2,
    navigationOptions: {
      title: 'Tab2',
    }
  }
},{
  tabBarPosition: 'bottom',
});

export default class MyComponent extends Component {
  constructor(props) {
    const originalGetStateForAction = MyTabNav .router.getStateForAction;
    Object.assign(MyTabNav .router, {
      getStateForAction(action, state) {
        /* do what you want right here
         *
         * custom stuff
         */
        return originalGetStateForAction(action, state);
      }
   });
  }
}
```

**Comment by jayesbe** [comment]
Actually you can replace the above by using 
https://reactnavigation.org/docs/navigators/#onNavigationStateChange-prevState-newState

```
<MyTabNav onNavigationStateChange={(prevState, nextState) => {}} />
```

**Comment by tmaly1980** [comment]
@jayesbe, Does that prevent the default handler for the state change from happening? Or in addition to it?

In my case, I want each tab button to clear the sub-stacks so I'm always going to the first item, by overriding jumpToIndex on the tabBarComponent:

export const TabContainer = TabNavigator({
	VaultStack: { 
		screen: VaultStack,
	}
}
}, {
  tabBarComponent: (props) => {
  		const { navigation, navigationState } = props;
  		const _jumpToIndex = props.jumpToIndex; // Just in case 
		return (<TabView.TabBarBottom {...props} jumpToIndex={(index) => {
			tab = navigationState.routes[index];
			tabRoute = tab.routeName;
			firstRoute = tab.routes[0].routeName; // navState is Tabs object

// Do what you want here

			const tabAction = NavigationActions.navigate({ routeName: tabRoute });
			const firstScreenAction = NavigationActions.reset({ index: 0,
				actions: [ NavigationActions.navigate({ routeName: firstRoute }) ]
			});
			navigation.dispatch(tabAction);
			navigation.dispatch(firstScreenAction);
		}} />)
	}, 
});

**Comment by tmaly1980** [comment]
@rileybracken , instead of changing it here, why not have a method in each component that requires authentication to render() a LoginScreen if they're not signed in? That way, they won't have the animation. Think in terms of statefulness. This is what i have in my Vault component:

```
  render() {
    if(!this.props.userProfile) { return (<Login/>) } // Prompt for login if needed
    // .... continue for signed in users....
```

This way, you won't have to worry about 'redirecting' from the LoginScreen back to the "intended" screen. The login screen just disappears once the userProfile is set in redux.

**Comment by jayesbe** [comment]
@tmaly1980  I couldn't prevent tab change. The docs show an example of how to do it but it doesnt work. 

What I ended up doing was moving the instantiation of the TabNavigator to inside my constructor. 

```
  constructor(props, context) {
    super(props, context);

    const component = this;
    this.MyTabNavigator = TabNavigator({
	  MyTab: {
	    screen: MyScreen,
	    navigationOptions: {
	      title: 'My Screen',
	    }
	  }
	},{
	  tabBarPosition: 'bottom',
	  tabBarOptions: {
	    indicatorStyle: {
	      backgroundColor: '#fff'
	    },
	    style: {
	      backgroundColor: '#2b87a2'
	    },
	    onTabPress: (tab) => {
	    	// onTabPress stuff here..
	    }
	  }
	});
  }

  render() {
    const MyTabNavigator = this.MyTabNavigator;
    return (
      <MyTabNavigator />
    );
  }
```

**Comment by rileybracken** [comment]
To be honest I think that the best route to fix this (for my use case) would be with a HOC. 

It is gone over documented well in [this issue](https://github.com/react-community/react-navigation/issues/51#issuecomment-283656879).

It is similar to what @tmaly1980 is saying. Your HOC would be something like `authenticatedUser`, before it mounts it would check if a user is authenticated, if not it would fire the session `StackNavigator`, if they are authenticated it would fire the profile `TabNavigator`.

**Comment by rileybracken** [comment]
Once I have the HOC implemented I will post it in the issue, above is just my idea of how it would work.

**Comment by grabbou** [comment]
Closing in favour of #314

**Comment by brunoreis** [comment]
```
import hoistNonReactStatic from 'hoist-non-react-statics';

const withGetOnPressOverriden = (routesAndFunctions) => (WrappedComponent) => {
    class overriden extends React.Component {
        render() {
            const getOnPress = (_,data) => {
                const routeName = data.route.routeName;
                if(routesAndFunctions[routeName]) {
                    return () => routesAndFunctions[routeName]();
                }
                else {
                    return this.props.getOnPress(_,data)
                }
            }
            return <WrappedComponent {...this.props} getOnPress={getOnPress}/>;
        }
    }
    return hoistNonReactStatic(overriden, WrappedComponent);
}

const TabBarBottomOverriden = withGetOnPressOverriden(
    {
        CreatePost: () => console.log('createPost')
    }
)(TabBarBottom)
```
