### ISSUE TITLE
TabNavigator Bottom reset stack when pressing selected tab

### ISSUE THREAD

**Issue by RyanMitchellWilson** [react-community/react-navigation#933]
This is more of a question/feature request than an issue. Is it possible with the TabNavigator to press on the active tab and have it reset it's stack? Much like most iOS TabNavigators if you are a few screens deep on a tab and want to get back to the initial route you can usually just press the current tab again and it will reset your stack. Is this currently possible and if not could this be added to the TabNavigator?

As an example if you have an iOS device just open the app store, navigate to an app then press the active tab and you will see expected behavior.

**Comment by tmaly1980** [comment]
You read my mind, I've been working on that all day. Still not quite there. I'll post details. Essentially, you need to customize tabBarComponent and pass along a custom jumpToIndex to the props which will call the proper navigation.

**Comment by tmaly1980** [comment]
This is incomplete, it's what I have so far, passed as parameters to TabNavigator (2nd argument):
```
{
 tabBarComponent: (props) => {
  		const { navigation, navigationState } = props;
  		const _jumpToIndex = props.jumpToIndex; // Just in case 
		return (<TabView.TabBarBottom {...props} jumpToIndex={(index) => {
			tab = navigationState.routes[index];
			tabRoute = tab.routeName;
			firstRoute = tab.routes[0].routeName; // navState is Tabs object

			navigation.navigate(firstRoute); // Goes to route, but adds to stack (w/back arrow)
		}} />)
	}
}   
```

**Comment by tmaly1980** [comment]
This looks like it works, I tried chaining the routes together, but kept getting an issue with it not finding the subroute in the context of the original (previous) tab. Putting them in sequence seems to work, but I'm not sure about a race condition if they're asynchronous

```
  tabBarComponent: (props) => {
  		const { navigation, navigationState } = props;
  		const _jumpToIndex = props.jumpToIndex; // Just in case 
		return (<TabView.TabBarBottom {...props} jumpToIndex={(index) => {
			tab = navigationState.routes[index];
			tabRoute = tab.routeName;
			firstRoute = tab.routes[0].routeName; // navState is Tabs object

			const tabAction = NavigationActions.navigate({ routeName: tabRoute });
			const firstScreenAction = NavigationActions.reset({ index: 0,
				actions: [ NavigationActions.navigate({ routeName: firstRoute }) ]
			});
			navigation.dispatch(tabAction);
			navigation.dispatch(firstScreenAction);
		}} />)
	}, 
```

**Comment by RyanMitchellWilson** [comment]
@tmaly1980 That works pretty well for me. One problem though is that it resets every time you press the tab when I'm more looking for it only to reset if you are currently on the tab and select the same tab again. But this gets me pretty close, I'll see if I can figure out a way to have this work in my specific case and I'll post what I come up with.

**Comment by tmaly1980** [comment]
@RyanMitchellWilson , maybe add to the beginning something like:

`if(navigationState.index === index) { return navigationState; }`

**Comment by RyanMitchellWilson** [comment]
Here is what I ended up with:
```
tabBarComponent: props => {
  const {navigation, navigationState} = props
  const jumpToIndex = index => {
    const lastPosition = props.getLastPosition()
    const tab = navigationState.routes[index]
    const tabRoute = tab.routeName
    const firstTab = tab.routes[0].routeName

    navigation.dispatch(pushNavigation(tabRoute))
    lastPosition === index && navigation.dispatch(resetNavigation(firstTab))
  }
  return <TabView.TabBarBottom {...props} jumpToIndex={jumpToIndex}/>
},
```
My actions are a bit different here but essentially the same logic. I'm using the getLastPosition function off props for my logic around resetting but using `navigationState.index` works equally as well. Thanks for the help @tmaly1980 greatly appreciated!

**Comment by RyanMitchellWilson** [comment]
Notice today there is a slight race condition here. While the app is animating to a new tab, if you keep pressing that tab, it will push multiple instances of that tab screen onto the stack.

**Comment by RyanMitchellWilson** [comment]
Found the fix, just need to use `navigationState.index` over `props.getLastPosition()` and add a check before the dispatch to see which tab is the current.

```
tabBarComponent: props => {
  const {navigation, navigationState} = props
  const jumpToIndex = index => {
    const lastPosition = navigationState.index
    const tab = navigationState.routes[index]
    const tabRoute = tab.routeName
    const firstTab = tab.routes[0].routeName

    lastPosition !== index && navigation.dispatch(pushNavigation(tabRoute))
    lastPosition === index && navigation.dispatch(resetNavigation(firstTab))
  }
  return <TabView.TabBarBottom {...props} jumpToIndex={jumpToIndex}/>
},
```

**Comment by ldipasquale** [comment]
Thanks @RyanMitchellWilson!

**Comment by grabbou** [comment]
Closing in favour of #314

**Comment by itswaze** [comment]
This isn't working for me, do I need to do anything more?
I get the error:

```
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in.

Check the render method of `tabBarComponent`.
```

**Comment by AkaOne** [comment]
@itswaze try using
```js
return <TabBarBottom {...props} jumpToIndex={jumpToIndex}/>
```
instead of 
```js
return <TabView.TabBarBottom {...props} jumpToIndex={jumpToIndex}/>
```

**Comment by phoenixzsun** [comment]
@tmaly1980 Please hava a look at this issue: [#1755 ](https://github.com/react-community/react-navigation/issues/1755), We need help.

**Comment by phoenixzsun** [comment]
@tmaly1980 Hi. When I switched to a new tab, What I expected is that the stack of the tab is reseted. Can you help me with that?

**Comment by valinaga** [comment]
@tmaly1980, @RyanMitchellWilson great solution you found! Really great work!
However, I'm stuck with an issue. The tab navigator is not my top navigator but a screen in a StackNavigator. Something like this:
`
const AppNavigator = StackNavigator({
    main: { screen: MainScreenNavigator },
    login: { screen: LoginScreen },
    recover: { screen: RecoverScreen },
    register: { screen: RegisterScreen },
    photo: { screen: PhotoScreen },
    intro: { screen: IntroScreen }
  });

const MainScreenNavigator = TabNavigator({
    home: { screen: HomeNavigator },
    mywishlist: { screen: MyWishBoxNavigator },
    friends: { screen: FriendsNavigator },
    messages: { screen: MessagesNavigator },
    more: { screen: MoreNavigator }
  });
`
Unfortunately I was not able to make your above code work. The issue was that dispatching the reset action was throwing an error because the route name must be from the AppNavigator and not from MainScreenNavigator.
Any hints will be highly appreciated.
Thanks in advance!

**Comment by ou2s** [comment]
@valinaga I have the same problem... Did you fin any solution to the problem?

**Comment by ou2s** [comment]
@valinaga I found a dirty workaround for your usecase:
```
 tabBarComponent: ({ jumpToIndex, ...props }) => (
      <TabBarKeyboard
        {...props}
        jumpToIndex={async index => {
          const numberOfScreenInStack =
            props.navigationState.routes[index].routes.length;

          if (
            props.navigation.state.index === index &&
            numberOfScreenInStack > 1
          ) {
            for (let i = numberOfScreenInStack; i > 1; i--) {
              props.navigation.dispatch(NavigationActions.back());
            }
          } else {
            jumpToIndex(index);
          }
        }}
      />
```

If you found a cleaner solution let me know :)

**Comment by valinaga** [comment]
@ou2s hi, yes I finally found something. It works on 1.0.0-beta.21.
```
  navigationOptions: ({ navigation }) => ({
    tabBarOnPress: ({ previousScene, scene, jumpToIndex }) => {
      const { route, focused, index } = scene;
      if (!focused) {
        if (route.index > 0) {
          const tabRoute = route.routeName;
          const { routeName, key } = route.routes[0];
          navigation.dispatch(
            NavigationActions.navigate({ routeName: tabRoute })
          );
          navigation.dispatch(
            NavigationActions.reset({
              index: 0,
              key,
              actions: [
                NavigationActions.navigate({ routeName })
              ]
            })
          );
        } else {
          jumpToIndex(index);
        }
      }
    },
  })
```

**Comment by ou2s** [comment]
@valinaga thanks for sharing. However I was not able to run your code successfully...

**Comment by valinaga** [comment]
@ou2s depends on what you were looking for. I was trying to avoid reseting the stack if you already on a specific tab. Your version was doing the opposite, if that was what you were looking for. But when you go to a different tab, the corresponding stack won't reset until you press again.
Nevertheless, glad it's working.

**Comment by neilhamilton** [comment]
@valinaga This helped me huge and works great. If only we could remove the animation that happens when the nav of the tab is reset, as though it would appear that it was automatically at the index. Are you aware of anything?

**Comment by valinaga** [comment]
@neilhamilton only solution I see is to disable the animation. Dispatching a navigation action will bring animation with it.

**Comment by tuanmai** [comment]
@valinaga thank for your sharing. I changed your code a little bit that won't need to reset the stack, just go back.
```
navigationOptions: ({ navigation }) => ({
  tabBarOnPress: ({ scene, jumpToIndex }) => {
    const { route, focused, index } = scene;
    if (focused) {
      if (route.index > 0) {
        // eslint-disable-next-line immutable/no-let
        let currentIndex = route.index;
        while (currentIndex > 0) {
          navigation.dispatch(NavigationActions.back({}));
          currentIndex -= 1;
        }
      }
    } else {
      jumpToIndex(index);
    }
  },
});
```

**Comment by neilhamilton** [comment]
@tuanmai I ended up also using back, but instead of looping through each index and going back, you can do one fluid back motion by specifying a key to go back _from_ in the [Back Action](https://reactnavigation.org/docs/navigators/navigation-actions#Back)

You could modify your code to find the key that is after the initial route and pass that to the back action:

```
navigationOptions: ({ navigation }) => ({
  tabBarOnPress: ({ scene, jumpToIndex }) => {
    const { route, focused, index } = scene;
    if (focused) {
      if (route.index > 0) {
        // eslint-disable-next-line immutable/no-let
        const { routeName, key } = route.routes[1]
        navigation.dispatch(NavigationActions.back({ key }))
      }
    } else {
      jumpToIndex(index);
    }
  },
});
```

**Comment by greghuels** [comment]
Here's another example that resets the stack on each tab change:

```
function resetStack(navigation, routes) {
  if (routes.length > 1) {
    const { routeName } = routes[0];
    navigation.dispatch(NavigationActions.reset({
      index: 0,
      actions: [NavigationActions.navigate({ routeName })],
    }));
  }
}

```

And then in your TabNavigator:

```
  navigationOptions: ({ navigation }) => ({
    tabBarOnPress: ({ previousScene, scene, jumpToIndex }) => {
      resetStack(navigation, previousScene.routes);
      jumpToIndex(scene.index);
    },
  }),
```

**Comment by noymer** [comment]
It seems that in `v1.5.6` this feature is implemented!

https://github.com/react-navigation/react-navigation/commit/c8531d0f38c9c8bdc74f59762df778e877a00789

**Comment by daveteu** [comment]
I've been trying all the above solutions and was confused why they don't work.

If you have come here because jumpToIndex is not a function, please note for **react navigator v2**, the above is depreciated.

You should use 

```
navigationOptions: ({ navigation }) => ({
    tabBarOnPress: ({navigation}) => { //Note the change.

   if  (!navigation.isFocused) {
  
  //do soundthing when it's not a focused tab. e.g Play a tab sound.

  }
    console.log(navigation); 
  }
})
```

Documentation here -> [https://reactnavigation.org/docs/en/bottom-tab-navigator.html](https://reactnavigation.org/docs/en/bottom-tab-navigator.html)

**Comment by brentvatne** [comment]
yeah this is also just implemented by default in react-navigation@^2
