### ISSUE TITLE
Use custom DrawerNavigatorItems?

### ISSUE THREAD

**Issue by svenadlung** [react-community/react-navigation#934]
Is there any way to have custom DrawerNavigatorItems? 
Or maybe is there a way to customize the styling of the items? I wanna get rid of the marginTop of 20 on the outer container. Plus I don't see any chance to set a borderBottom to the child elements. I only found out using labelStyle to set the style of the label but nothing to style the wrapping `<View>`. 

Please correct me if I am wrong.

**Comment by tmaly1980** [comment]
Have you tried using a custom contentComponent? That way you can style/code it however you want. For me, I have items that show/hide depending on the user's account status (guest or signed in).

**Comment by svenadlung** [comment]
Good point, right now I do use it but within the contentComponent I use `<DrawerView.Items {...props} />` for the items. I have to replace this with an own customized component instead of the imported one from `react-navigation`, I guess?

**Comment by tmaly1980** [comment]
Right, it's just a View component. I use native-base so mine is essentially:

```
<Content>
  <List>
           <ListItem button iconLeft onPress={() => this.props.navigation.navigate('DealList') } >
            <View style={styles.listItemContainer}>
              <View style={styles.iconContainer}>
                <Icon name="ticket" style={styles.sidebarIcon} />
              </View>
              <Text style={styles.text}>Inventory</Text>
            </View>
          </ListItem>
           ... other items here ....
  </List>
</Content>
```

**Comment by ericvicenti** [comment]
Yeah, you should just customize the contentComponent if you're not happy with the included drawer items

**Comment by svenadlung** [comment]
Thanks! What I have done for not using static labels but looping through the defined routes:
`
<View style={[styles.container]}>
	{props.navigation.state.routes.map((route: *, index: number) => {
		return (
			<TouchableWithoutFeedback
				key={route.key}
				onPress={() => {
					props.navigation.navigate('DrawerClose')
					props.navigation.navigate(route.routeName)
				}}
				delayPressIn={0}
			>
				<View style={[styles.item]}>
					<Text style={[styles.label]}>
						{props.getLabel({route, index})}
					</Text>
				</View>
			</TouchableWithoutFeedback>
		)
	})}
</View>`
