### ISSUE TITLE
passing not only string props?

### ISSUE THREAD

**Issue by vonovak** [react-community/react-navigation#936]
Hi! according to https://reactnavigation.org/docs/navigators/navigation-prop#state-The-screen's-current-stateroute

```
A screen has access to its route via this.props.navigation.state. Each will return an object with the following:
{
  // the name of the route config in the router
  routeName: 'profile',
  //a unique identifier used to sort routes
  key: 'main0',
  //an optional object of string options for this screen
  params: { hello: 'world' }
}
```

can the `params` contain things other than strings? this seems pretty limiting...

**Comment by caspg** [comment]
The string is just an example here. You can pass objects:
```js
{
  params: { something: { hello: 'Hello', world: 'World' } } 
}
```

**Comment by vonovak** [comment]
hmm, probably a stupid question but I wanted to be sure. I was thinking that maybe you can pass only serializable values, so functions could't be passed, foe example. Will do a PR to clarify the docs. thanks @caspg

**Comment by vonovak** [comment]
@caspg see #952

**Comment by caspg** [comment]
@vonovak Thanks 👍
