### ISSUE TITLE
Nested redux navigators stop working

### ISSUE THREAD

**Issue by cooperka** [react-community/react-navigation#937]
### Issue description

In the following example, I've nested the original StackNav inside a new StackNav, and connected just the top-level one to my redux state. It does maintain its own state, but it no longer seems to be possible to control any of its children. The app loads as usual, but none of the buttons work anymore.

Here's a very simple diff to reproduce this (call it "StackInStack A"), based on the ReduxExample app: https://github.com/cribspot/react-navigation/commit/3ef0a223bdb921518e8a92aa2b204bd518b20a4a ~~(Old, outdated one: https://github.com/cribspot/react-navigation/commit/8afcfd3315e1a276fc18b7a48096229787c8af7c)~~

Here's a second diff ("StackInStack B") doing the same thing but in a slightly different way; this time it doesn't even render, giving `Expect nav state to have routes and index, {"routeName":"Root","action":{"type":"Navigation/NAVIGATE","routeName":"Login"},"key":"Init"}`: https://github.com/cribspot/react-navigation/commit/9332bf1eab3b9d691b7ad7517fae168be6dd1c9e

Similar error with a DrawerNav nested in a StackNav ("DrawerInStack A", gives `Expect nav state to have routes and index, {"routeName":"Root","key":"Init"}`): https://github.com/cribspot/react-navigation/commit/af0f571a59df96fbb5ab3ec8865ceff1a6c6a308 (though, of course, it works if we navigate to a route other than the drawer itself: https://github.com/cribspot/react-navigation/commit/5260b0962aa01df2d15502883d5900809770d1c3, "DrawerInStack B").

In order to control the children, they must be given their own, separate reducer like so: https://github.com/react-community/react-navigation/compare/8afcfd3...110fce9d. This means for every Navigator in your app, you need to create a reducer and duplicate logic to control anything inside of that navigator.

Personally, I would expect the default behavior to be that any navigator passes its props (such as `navigation` and `onNavigationStateChange`) down to any nested navigators and that `router.getStateForAction` would return a hierarchy of routes so you only need one reducer. This could, of course, be explicitly prevented by manually setting the props to `null` in a particular child.

Related issue here: https://github.com/react-community/react-navigation/issues/1041

### Initial state output

StackInStack A (it renders, but buttons aren't clickable) has an initial state of:

```js
{
  "index": 0,
  "routes": [
    {
      "routeName": "Root",
      "key": "Init"
    }
  ]
}
```

StackInStack B (it doesn't render, error as described above) has an initial state of:

```js
{
  "index": 0,
  "routes": [
    {
      "routeName": "Root",
      "action": {
        "type": "Navigation/NAVIGATE",
        "routeName": "Login"
      },
      "key": "Init"
    }
  ]
}
```

Even though both of them seem like they should have the **same** initial state (!)

Am I misunderstanding how to set this up -- is there an easier way, or is this already possible somehow? Any advice on how to achieve this would be greatly appreciated!

**Comment by max-mykhailenko** [comment]
I also have question about nested routes. Should I describe all nested routes in initial redux state?

**Comment by cooperka** [comment]
@max-mykhailenko intuitively it seems like you should, but I don't think they actually handle that yet. It's unclear.

**Comment by lorenzsell** [comment]
@max-mykhailenko you can also do something like this:
``
const INITIAL_STATE = InitialNavigator.router.getStateForAction(InitialNavigator.router.getActionForPathAndParams('Login'));
``

**Comment by max-mykhailenko** [comment]
@cooperka @lorenzsell 
Thanks guys, it's ok to duplicate all tabs in state once, but it's was unclear from documentation.

**Comment by cooperka** [comment]
Solved it! It works after switching to `NavigationActions.navigate` instead of `getActionForPathAndParams` (https://github.com/cribspot/react-navigation/commit/4c07d8b5fafd386004dd8197659fff8d9126467e). Programmatically generated initial state now, all as it should be:

```js
{
  "index": 0,
  "routes": [
    {
      "routes": [
        {
          "routes": [
            {
              "key": "Login",
              "routeName": "Login"
            },
            {
              "key": "Main",
              "routeName": "Main"
            },
            {
              "key": "Profile",
              "routeName": "Profile"
            }
          ],
          "index": 0,
          "key": "DrawerClose",
          "routeName": "DrawerClose"
        },
        {
          "key": "DrawerOpen",
          "routeName": "DrawerOpen"
        }
      ],
      "index": 0,
      "routeName": "Root",
      "key": "Init"
    }
  ]
}
```

**Comment by skiral** [comment]
I am having the same issue when I have nested navigation.

this is only generating the first route for me, as you can see below I only get the Fans, Please help if you know the answer.

I am thinking to manually create the initial state now.

```
const stackNav = StackNavigator({
	Fans: {
		screen: StackNavigator({
			Fans: {
				screen: () => (<View><Text>Fans</Text></View>)
			}
		})
	},
	Followings: {
		screen: StackNavigator({
			Followings: {
				screen: () => (<View><Text>Followings</Text></View>)
			}
		})
	}
});
```

```
console.log(stackNav.router.getStateForAction(NavigationActions.init()));
```
```
{
  "index": 0,
  "routes": [
    {
      "index": 0,
      "routes": [
        {
          "routeName": "Fans",
          "key": "Init"
        }
      ],
      "routeName": "Fans",
      "key": "Init"
    }
  ]
}
```

**Comment by cooperka** [comment]
@skiral my example is a `DrawerNavigator`. For `StackNavigator`, you won't see the routes in your state tree until they've actually been pushed. Your tree looks correct to me.

If you want to start with one of the routes already pushed (e.g. "Followings" on top of "Fans"), you can call `getActionForPathAndParams` multiple times [like this](https://github.com/react-community/react-navigation/blob/master@%7B2017-06-11%7D/examples/ReduxExample/src/reducers/index.js#L7-L13).

**Comment by haseebnaseem** [comment]
I have not been able to generate the state correctly using either from @dchersey's method or from the the one mentioned in the docs. 
This is how my navigators are defined:
```
const HomeNav = TabNavigator({
    feed:{screen:Feed},
    restaurantScreen:{screen:Restaurant},
},{
    tabBarComponent:NavigationComponent,
    tabBarPosition:'bottom',
    tabBarOptions:{
        bottomNavigationOptions:{
            labelColor:'white',
            rippleColor:'white',
            tabs:{
                feed:{
                    barBackgroundColor:'#37474F',
                },
                restaurantScreen:{
                    barBackgroundColor:'#00796B',
                }
            }
        }
    }
});
export const Navigator=StackNavigator(
    {
        HomeScreen:{screen:Home},
        VerifyScreen:{screen:Verify},
        newUserScreen1:{screen:newUser1},
        newUserScreen2:{screen:newUser2},
        loginScreen:{screen:login},
        feedScreen:{screen:HomeNav},
    },
    {
        headerMode:'none',
    },
);
```
and this is how I am trying to set the initial state and navigate:
```
const initialState=Navigator.router.getStateForAction(
    NavigationActions.init()
);

function navigate(screenName,state){
    return Navigator.router.getStateForAction(NavigationActions.navigate({routeName:screenName},state));
}
```
The following error comes up when navigating from Home screen to the feed Navigator:
```
Expect nav state to have routes and index, {"routeName":"feedScreen","key":"Init-id-1510393473667-1"}
```
