### ISSUE TITLE
Drawer to push screen instead of overlay?

### ISSUE THREAD

**Issue by MovingGifts** [react-community/react-navigation#939]
When a left drawer opens, how can we push the screen to the right instead of overlaying it (and revert the same way when we close the drawer)?

**Comment by ericvicenti** [comment]
This isn't currently supported, but you could make a custom drawer navigator for your app if you want

**Comment by MovingGifts** [comment]
@grabbou Since this is pretty common pattern in many apps, can you please add it as a feature request?

**Comment by pvsong** [comment]
That would be awesome when have more like parallax, door, push,...

**Comment by Echelpoel** [comment]
Is there perhaps any well-documented example available how to make a custom (drawer) navigator?

**Comment by selfeky** [comment]
@Echelpoel Did you find a solution? Looking for the same thing.

**Comment by blackneck** [comment]
@selfeky I added a [gist](https://gist.github.com/blackneck/a4cbe54f6b78459f180c961b7bf98ad2) where edit DrawerLayout a little to bring "push view" functionality. To use it with react-navigation, you should get rid of react-native-drawer-layout-polyfill and use mine instead. There is 'drawerType' prop to enable 'push-screen' behaviour

**Comment by ygorlazaro** [comment]
hi @blackneck , do you have a sample how to use your gist?

**Comment by mxmzb** [comment]
would be great to have this built into the library, though! 👍

**Comment by blackneck** [comment]
@tbarho @ygorlazaro 
Here is what i've found:

react-navigation's drawer navigator heavily depends on [react-navigation-drawer](https://github.com/react-navigation/react-navigation-drawer), which in turn depends on [react-native-drawer-layout-polyfill](https://github.com/react-native-community/react-native-drawer-layout-polyfill) which (eventually) depends on [react-native-drawer-layout](https://github.com/react-native-community/react-native-drawer-layout) - if we take a look at the code of all this dependencies appears that for android react-navigation uses native drawer implementation (from react-native package) and for iOS it uses pretty full JS react-native-drawer-layout. And this was my starting point I dig into sources, find the place where owners apply animation to show drawer and just use the same value to move underlying content in the same direction (you can read comments for the changes [I've made to this file ](https://github.com/blackneck/react-native-drawer-layout/blob/master/src/DrawerLayout.js) to make drawer push the underlying content (marked as 'comment:')) . Then you got to do really terrible stuff - proxy this new prop `drawerType?: 'overlay' | 'push-screen'` from your code into `react-native-drawer-layout` through the dependency chain I described above :) just for the test I've done following steps:

1. `react-native init`
2. `yarn add react-navigation`
3.  replace `./node_modules/react-native-drawer-layout/dist/DrawerLayout.js` file with one from my [fork](https://github.com/blackneck/react-native-drawer-layout/blob/master/src/DrawerLayout.js)
4. add `drawerType: 'push-screen'` in your navigator, e.g. 
`export default createDrawerNavigator({
  MyApp: MyApp
}, {
  drawerType: 'push-screen',
})`
5. in file `./node_modules/react-navigation-drawer/dist/views/DrawerView.js` pass this `drawerType={this.props.navigationConfig.drawerType}` into the `<DrawerLayout ...>`

Looks not so good, but I'm fallen in love currently and just cannot figured out how to bring this feature as a single import without changing guts of node_modules folder. Waiting for your opinions :)
Oh, and here is what I've got all in all
![appvideo](https://user-images.githubusercontent.com/7744079/41494003-33b057c6-7116-11e8-85b0-c666f4ba983e.gif)

just a short note: to use it with android - replace `import DrawerLayout from 'react-native-drawer-layout-polyfill';` inside `./node_modules/react-navigation-drawer/dist/views/DrawerView.js` with `import DrawerLayout from 'react-native-drawer-layout';`

**Comment by saitbnzl** [comment]
I think @blackneck's solution works great. I hope this change will be merged soon.

**Comment by Amnesthesia** [comment]
I would love this! 

+1 for merge

**Comment by nik-007** [comment]
@blackneck thanks for the simple solution, you saved my lot of time. but still couldn't figure out how to enable swipe/drag to open the drawer without any click event on hamburger icon. Thank you so much again.

**Comment by MurugappanV** [comment]
Available as `drawerType : "slide"` in react navigation version 3.x

**Comment by blackneck** [comment]
thanks for pointing @MurugappanV :)

**Comment by Vishwendrakumar** [comment]
drawerType : "slide" is not working @MurugappanV

**Comment by MurugappanV** [comment]
> drawerType : "slide" is not working @MurugappanV

Are you sure, using react navigation version 3 ?

Here is my code, hope it helps

````
createDrawerNavigator(
	{
		HomeDrawerScreen: { screen: HomeStack },
		HistoryDrawerScreen: { screen: History },
		BookmarkDrawerScreen: { screen: Bookmark },
	},
	{
		initialRouteName: "HomeDrawerScreen",
		contentComponent: DrawerNavigator,
		drawerPosition: "right",
		drawerType: "slide",
		drawerWidth: 300,
	},
)
```

**Comment by Base29** [comment]
> > drawerType : "slide" is not working @MurugappanV
> 
> Are you sure, using react navigation version 3 ?
> 
> Here is my code, hope it helps
> 
> ```
> createDrawerNavigator(
> 	{
> 		HomeDrawerScreen: { screen: HomeStack },
> 		HistoryDrawerScreen: { screen: History },
> 		BookmarkDrawerScreen: { screen: Bookmark },
> 	},
> 	{
> 		initialRouteName: "HomeDrawerScreen",
> 		contentComponent: DrawerNavigator,
> 		drawerPosition: "right",
> 		drawerType: "slide",
> 		drawerWidth: 300,
> 	},
> )
> ```
> ```

@MurugappanV ... tested this as well and drawerType isn't working for me as well ... I have react-navigation@3.5.1

**Comment by jordanpicaso** [comment]
@MurugappanV Your solution worked for me, tnx man.

**Comment by rodrisapiens** [comment]
Hi, using navigation v6. passing prop drawerType ="slide" will do the work :)

**Comment by hemanthAppmaker** [comment]
Hi,
Drawer have property : drawerType?: 'front' | 'back' | 'slide' | 'permanent';
use this property shown:
--------------------- 
drawerType:'front'
---------------------

**Comment by juliangalvez** [comment]
In 2023, with "@react-navigation/drawer": "6.5.8", after a lot of time searching for the solution for this... finally got it! XD:
Eg.;

<Drawer.Navigator  screenOptions={{ drawerType: "slide" }}
      <Drawer.Screenname="Home" component={Home} />
</Drawer.Navigator>

**Comment by Harshith-Karkera** [comment]
screenOptions={{
          headerShown: false,
          drawerType: 'front',
        }}
ios default : slide
android default : front
