### ISSUE TITLE
How to pop current scene from store?

### ISSUE THREAD

**Issue by MovingGifts** [react-community/react-navigation#942]
I am using `mobx` over `redux`, and I am wondering how to programmatically go back from a store's method. I have many stores and many times in them, like after submitting a form to the server, I pop off the current scene.

I am moving from `react-native-router-flux` which simply does it like this:

```
import { Actions } from 'react-native-router-flux';

contactForm(data){
  // Go back
  Actions.pop();
}
```
How can I accomplish the same thing using `react-navigation` without having to pass the navigation property every single time to each method from the ui, and just access it in the store like above?

**Comment by vonovak** [comment]
Im sure you can call the navigation methods on the navigation store itself. howeevr, I don't see any examples in the docs. You'll probably have to install redux alongside with mobx, but redux is a small library so it's not a problem at all, unless you're on the web.

**Comment by MovingGifts** [comment]
@vonovak Yeah, I really don't want to use redux. I would be really surprised if there is no other way to do something as simple as the above. Pop off the current scene to the one before it should be pretty darn simple to implement programmatically, without passing props everywhere (just like above).

**Comment by MovingGifts** [comment]
bump

**Comment by vonovak** [comment]
the `this.props.navigation` syntax works with redux store - it dispatches actions to it behind the scenes. This is how what you need is done in ex-navigation: https://github.com/expo/ex-navigation#perform-navigation-actions-from-outside-of-a-component

I'm afraid you'll need redux to accomplish that, but you can encapsulate the redux part in one small module and not expose it to your mobx stores, so you don't mix redux and mobx too much.

**Comment by MovingGifts** [comment]
Hmmm... still not 100% sure how to accomplish that. @satya164 Sorry to bother you, but how do we navigate back or to a route from a store? I might have missed it in the docs, or maybe it is missing from the docs.

Can you share an example code that would work without having to pass the `this.props.navigation` to every method in the store (basically a way to hook to the current navigator from a store without `this.props`, something like my example above that works?

**Comment by felipap** [comment]
Are there any updates on this?

**Comment by SpenceSouth** [comment]
Bump

**Comment by vonovak** [comment]
https://github.com/react-community/react-navigation/issues/840

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
