### ISSUE TITLE
Header buttons not showing up when TabNavigator nested inside StackNavigator

### ISSUE THREAD

**Issue by amitava82** [react-community/react-navigation#946]
I have TabNavigator inside StackNavigator and I want to be able to configure left/right buttons in each tab. If I set them in `navigationOptions` within tab screens it does not show up.

```
//Tab bar
const TabNavigation = TabNavigator({
    Home: {screen: HomeScreen, navigationOptions: {
        tabBar: {
            icon: ({tintColor}) => <Icon name="home" size={20} color={tintColor} />
        }}}
});

//Root router
const PrimaryNav = StackNavigator({
  Main: {
      screen: TabNavigation,
      navigationOptions: {
          header: (state, options) => {
              return {
                  ...options,
                  ... {
                      visible: true,
                      backTitle: null
                  }
              }
          }
      }
  }
}, {
  // Default config for all screens
  headerMode: 'screen',
  initialRouteName: 'Main'
});


//HomeScreen
class HomeScreen extends React.Component {
    static navigationOptions = {
        title: 'Home',
        header: {
            left:  <Text>Left</Text>,
            right: <Text>Right</Text>,
        }
    };
    render() {
        return (
            <View style={styles.container}>
                <Text>Hello</Text>
            </View>
        )
    }
}
```

**Comment by chase0010** [comment]
same problem

**Comment by Richard-Cao** [comment]
same problem

**Comment by BigPun86** [comment]
+1

**Comment by mhaagens** [comment]
+1

**Comment by max-mykhailenko** [comment]
Same problem. Should we reorganize our routes?

**Comment by sagax85** [comment]
any workaround for this?

**Comment by amitava82** [comment]
Is there any other routing library can handle this use case?

**Comment by dready** [comment]
Try to not define default options within the stack navigator. That worked for me. 

If that will not work, try an additional stack navigator as root, nesting your stack and set options to none for header... It's a mess and i am not sure if it is a good idea but if it works...

See issue 1046

**Comment by laclance** [comment]
+1

**Comment by ravirajn22** [comment]
```
Home: { screen: TabNavigator({
    tab1: { screen: tab1 },
    tab2: { screen: tab2 },
    tab3: { screen: tab3 },
    tab4: { screen:tab4 }
  }) 
},
  Login: { screen: LoginScreen },
  Profile: { screen: ProfileScreen },
}
);
```
Now each tabs i.e tab1,tab2,tab3,tab4 will get the navigationOptions as if they were stand alone routes like login and profile screen. 
check this link on updating navigation options https://reactnavigation.org/docs/navigators/navigation-options

**Comment by dekm** [comment]
raviraj you are a life saver dude!  Thanks for sharing.

**Comment by kelset** [comment]
Pinging OP @amitava82 since this issue is quite old and related to an old version of the lib (and @ravirajn22 solution seems to work). If no answer I'll close in 7 days.

**Comment by amitava82** [comment]
Closing this. This is working.

**Comment by Rutheniceye92** [comment]
> ```
> const App = StackNavigator({
>  Home: { screen: TabNavigator({
>     tab1: { screen: tab1 },
>     tab2: { screen: tab2 },
>     tab3: { screen: tab3 },
>     tab4: { screen: tab4 }
>     }) 
>  },
>  Login: { screen: LoginScreen },
>  Profile: { screen: ProfileScreen },
> });
> ```
> 
> Now each tabs i.e tab1,tab2,tab3,tab4 will get the navigationOptions as if they were stand alone routes like login and profile screen.
> check this link on updating navigation options https://reactnavigation.org/docs/navigators/navigation-options

Page not found..!

**Comment by mikeRChambers610** [comment]
This solution does not work when you are trying to define a stack navigator inside of each tab... Please correct me if I am wrong.

**Comment by zalharash** [comment]
For React Navigation 5.  Let's say you have a nested TabNavigator that contains two tabs `Home` and `Settings` and you want to add a Header button only to the Home tab screen, to do that use the `navigation.setOptions` inside the TabNavigator as follow:

```js
import {  getFocusedRouteNameFromRoute} from '@react-navigation/native'

// Main Stack
const MainStackNavigator = ()=>{
 <Stack.Navigator>
      <Stack.Screen
         name="Home"
        component={MainTabNavigator}
      />
    </Stack.Navigator>
}

// Nested Tab stack
const MainTabNavigator=({navigation, route})=>{

// This is the important part to be added 
  React.useLayoutEffect(() => {
    const routeName = getFocusedRouteNameFromRoute(route) ?? 'Home';
    navigation.setOptions({
      headerRight: (props) =>
        routeName === 'Home' ? <Button onPress={() => {}} title=" /> : null,
    });
  }, [navigation, route]);

return (
    <Tab.Navigator>
      <Tab.Screen
        name="Home"
        component={HomeScreen}
        options={() => {}}
      />

      <Tab.Screen
        name="Settings"
        component={SettingScreen}
      />
    </Tab.Navigator>
  );
}


```

**Comment by AnyByte** [comment]
> 
> 
> For React Navigation 5. Let's say you have a nested TabNavigator that contains two tabs `Home` and `Settings` and you want to add a Header button only to the Home tab screen, to do that use the `navigation.setOptions` inside the TabNavigator as follow:
> 
> ```js
> import {  getFocusedRouteNameFromRoute} from '@react-navigation/native'
> 
> // Main Stack
> const MainStackNavigator = ()=>{
>  <Stack.Navigator>
>       <Stack.Screen
>          name="Home"
>         component={MainTabNavigator}
>       />
>     </Stack.Navigator>
> }
> 
> // Nested Tab stack
> const MainTabNavigator=({navigation, route})=>{
> 
> // This is the important part to be added 
>   React.useLayoutEffect(() => {
>     const routeName = getFocusedRouteNameFromRoute(route) ?? 'Home';
>     navigation.setOptions({
>       headerRight: (props) =>
>         routeName === 'Home' ? <Button onPress={() => {}} title=" /> : null,
>     });
>   }, [navigation, route]);
> 
> return (
>     <Tab.Navigator>
>       <Tab.Screen
>         name="Home"
>         component={HomeScreen}
>         options={() => {}}
>       />
> 
>       <Tab.Screen
>         name="Settings"
>         component={SettingScreen}
>       />
>     </Tab.Navigator>
>   );
> }
> ```

and how will you access the callback inside the Home page?

**Comment by jsunwoo** [comment]
> > For React Navigation 5. Let's say you have a nested TabNavigator that contains two tabs `Home` and `Settings` and you want to add a Header button only to the Home tab screen, to do that use the `navigation.setOptions` inside the TabNavigator as follow:
> > ```js
> > import {  getFocusedRouteNameFromRoute} from '@react-navigation/native'
> > 
> > // Main Stack
> > const MainStackNavigator = ()=>{
> >  <Stack.Navigator>
> >       <Stack.Screen
> >          name="Home"
> >         component={MainTabNavigator}
> >       />
> >     </Stack.Navigator>
> > }
> > 
> > // Nested Tab stack
> > const MainTabNavigator=({navigation, route})=>{
> > 
> > // This is the important part to be added 
> >   React.useLayoutEffect(() => {
> >     const routeName = getFocusedRouteNameFromRoute(route) ?? 'Home';
> >     navigation.setOptions({
> >       headerRight: (props) =>
> >         routeName === 'Home' ? <Button onPress={() => {}} title=" /> : null,
> >     });
> >   }, [navigation, route]);
> > 
> > return (
> >     <Tab.Navigator>
> >       <Tab.Screen
> >         name="Home"
> >         component={HomeScreen}
> >         options={() => {}}
> >       />
> > 
> >       <Tab.Screen
> >         name="Settings"
> >         component={SettingScreen}
> >       />
> >     </Tab.Navigator>
> >   );
> > }
> > ```
> 
> and how will you access the callback inside the Home page?

I just solved it with useContext.
