### ISSUE TITLE
Second List View in TabNavigator is not visible

### ISSUE THREAD

**Issue by tangentlin** [react-community/react-navigation#947]
Library: React Native 0.42.3, React Navigation 1.0.0-beta7, Redux

Here is my navigation setup

```
TabNavigator
    |--- Ideas ( StackNavigator )
    |        |--- IdeaList (has ListView1)
    |        |--- IdeaDetail (has ListView2)
    |--- Projects
```

When I start the project, the first ListView1 shows the content, but when I tap and show the second ListView2, it is invisible!  But the funny thing is that when tap on "Projects" tab, and taps on "Ideas" tab, I can see the ListView2.

**Comment by evollu** [comment]
I have similar issue. The second list view shows up when I scroll the blank screen

**Comment by shankymunjal** [comment]
Facing same issue, ListView not working with TabNavigator

**Comment by jpamarohorta** [comment]
Facing the same issue, ListView inside a StackNavigator

**Comment by c100k** [comment]
Yep same problem. I tried to wrap my `ListView` inside a `View` but it does not work either.

**Comment by tmaly1980** [comment]
This is because ListView has removeClippedSubviews={true} by default. I'll bet if you pull to refresh on the blank ListView that it will re-render. I'm not quite sure how to have the tab click do it automatically though. I wouldn't disable removeClippedSubviews for performance reasons.

**Comment by GotJimmy** [comment]
removeClippedSubviews={false} on the ListView does the trick.

**Comment by kelset** [comment]
Pinging OP @tangentlin since this issue is quite old and related to an old version of the lib. If no answer I'll close in 7 days.

**Comment by kelset** [comment]
Hi there @tangentlin ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue (especially if it's a bug report) please open a new issue that uses the new Issue Template to provide some more details to help us solve it.
