### ISSUE TITLE
Tab label changes when pushing to nested StackNavigator

### ISSUE THREAD

**Issue by MyGuySi** [react-community/react-navigation#95]
Hi,

I'm trying to create a TabNavigator with nested StackNavigators for each tab but I've just noticed that the label of a Tab changes when a screen is pushed to it's nested StackNavigator. 

Specifically, it changes to the value of the 'title' of the new screen.

![](https://media.giphy.com/media/EEGnvrsfoyQxy/giphy.gif)

```javascript
import React from 'react';
import {
  AppRegistry,
  View,
  Button,
  Text,
} from 'react-native';

import { StackNavigator, TabNavigator } from 'react-navigation';

class AgendaScreen extends React.Component {
  static navigationOptions = {
    title: 'Agenda'
  }
  render() {
    return (
      <View>
        <Text>Agenda Screen</Text>
        <Button
          title="Next screen"
          onPress={() => this.props.navigation.navigate('Detail')}
        />
      </View>
    );
  }
}

class DetailScreen extends React.Component {
  static navigationOptions = {
    title: 'Detail'
  }
  render() {
    return (
      <View>
        <Text>Detail Screen</Text>
        <Button
          title="Go back"
          onPress={() => this.props.navigation.goBack()}
        />
      </View>
    );
  }
}

class AllScreen extends React.Component {
  static navigationOptions = {
    title: 'All'
  }
  render() {
    return (
      <View>
        <Text>All Screen</Text>
      </View>
    );
  }
}

class ModalScreen extends React.Component {
  static navigationOptions = {
    title: 'Modal'
  }
  render() {
    return (
      <View>
        <Text>Modal Screen</Text>
      </View>
    );
  }
}

const HomeNav = StackNavigator({
  Agenda: { screen: AgendaScreen },
  Detail: { screen: DetailScreen }
});

const TabNav = TabNavigator({
  Home: { screen: HomeNav },
  All: { screen: AllScreen }
});

export default TabNav;
```

**Comment by satya164** [comment]
Thanks for the report. Can you paste this code so I can test?

**Comment by MyGuySi** [comment]
Just added it to the OP

**Comment by satya164** [comment]
Thank you. Will look into it soon.

**Comment by MyGuySi** [comment]
No problem, you can actually ignore the top level stack navigator as I've tried without it. I'll remove it from my snippet for future reference.

**Comment by ericvicenti** [comment]
@MyGuySi, this is the intended behavior when you do not provide a tabBar.label. (The tab bar defaults to the title when label is not specified, and the title will change depending on the screen)

To change the gif to present a persistent label:

```
HomeNav.navigationOptions = {
  label: 'Home',
};
```

Hopefully this works. Please re-open if this doesn't fix it. If it does, please consider submitting a PR to make this more clear in the documentation.

**Comment by MyGuySi** [comment]
@ericvicenti - Thanks for that. I just tried adding it but doesn't seem to enforce a persistent label, I still get the dynamic behaviour. 

```javascript
const HomeNav = StackNavigator({
  Agenda: { screen: AgendaScreen },
  Detail: { screen: DetailScreen }
});

HomeNav.navigationOptions = {
  label: 'Home',
};
```

**Comment by MyGuySi** [comment]
I got it working with this solution, but I'm assuming this shouldn't be necessary for what I'm trying to achieve:

```javascript
import React from 'react';
import {
  AppRegistry,
  Button,
  Text,
  View,
} from 'react-native';
import { StackNavigator, TabNavigator } from 'react-navigation';

class AgendaScreen extends React.Component {
  static navigationOptions = {
    title: 'Agenda',
  }
  render() {
    return (
      <View>
        <Text>Agenda Screen</Text>
        <Button
          title="Next screen"
          onPress={() => this.props.navigation.navigate('Detail')}
        />
      </View>
    );
  }
}

class DetailScreen extends React.Component {
  static navigationOptions = {
    title: 'Detail'
  }
  render() {
    return (
      <View>
        <Text>Detail Screen</Text>
      </View>
    );
  }
}

class AllScreen extends React.Component {
  static navigationOptions = {
    title: 'All'
  }
  render() {
    return (
      <View>
        <Text>All Screen</Text>
      </View>
    );
  }
}

const HomeNav = StackNavigator({
  Agenda: { screen: AgendaScreen },
  Detail: { screen: DetailScreen }
});

class HomeNavWrapper extends React.Component {
  static navigationOptions = {
    tabBar: {
      label: 'Home'
    }
  }
  render() {
    return (
      <HomeNav />
    )
  }
}

const TabNav = TabNavigator({
  Home: { screen: HomeNavWrapper },
  All: { screen: AllScreen }
});

export default TabNav;
```

**Comment by croshim** [comment]
You can probably fix it with this:

```javascript
const TabNav = TabNavigator({
  Home: { screen: HomeNav, navigationOptions: { tabBar: { label: 'Home' } } },
  All: { screen: AllScreen }
});
```

**Comment by MyGuySi** [comment]
@croshim I'll give that a try tomorrow.

It feels as though the label value should default to the route name if one is not intentionally set. Otherwise you're explicitly having to create `navigationOptions` to achieve native behaviour. Neither iOS or Android have a dynamic tab label.

**Comment by ericvicenti** [comment]
Oops sorry, my above example was bad. This should work:

```js
HomeNav.navigationOptions = {
  tabBar: {
    label: 'Home',
  },
};
```

**Comment by si-harps** [comment]
Thanks, that worked for me

**Comment by amsimoes** [comment]
Stumbled upon this issue and @croshim snippet fixed it with only a minor correction (probably due to newer version?): 
```javascript
  const TabNav = TabNavigator({
    Home: { screen: HomeNav, navigationOptions: { tabBarLabel: 'Home' } },
    All: { screen: AllScreen }
  });
```

```tabBar: { label: 'Home' } ``` gave me an error suggesting to use the tabBarLabel option instead.

**Comment by DaveCole** [comment]
The problem with this approach is that if you use data in navigation to do something like update a badge number, the number never gets updated when adding navigationOptions in the constructor of TabNavigator -- you have to use a static const in the screen component instead.  It would be nice to have a flag that we could pass in the configuration that turned this "feature" off.

**Comment by askarhu** [comment]
It's now tabBarLabel if someone is still looking for this. For example,

navigationOptions: {
      tabBarLabel: 'Updates',
      tabBarIcon: ({ tintColor, focused }) => (
        <Icon 
          name={focused ? "ios-timer" : "ios-timer-outline"}
          size={28} 
          style={{color: tintColor}} />
      ),
    }

**Comment by yctung** [comment]
Should this issue be closed? As suggested by DaveCole, there should be an option to turn off this "feature" of dynamical labels. 

The amsimoes's solution will not work if you also need to set the headerRight option (or any other options) inside the component because that will override the navigationOptions and mess up the tab bar icons/labels. 

An option of turning this dynamic feature off is necessary, in my mind.

**Comment by dwivediamit** [comment]
Hi can anyone help here..

how to call saved data inside export default and how to define constructor inside export default.

import styles from "../../css/style";
export default (MainScreenNavigator = TabNavigator(

  { 
    Home: { screen: Home},
    Schedule: { screen: Schedule },
    Account: { screen: Account },
    Location: { screen: Location },
    Profile: { screen: Profile }
  },
  {
    tabBarPosition: "bottom",
    tabBarComponent: props => {
      return (

        <Footer>
          <FooterTab>
            <Button
              vertical
              active={props.navigationState.index === 1}
              onPress={() => props.navigation.navigate("Schedule")}
            >
              <Icon name="calendar" />
              <Text>Schedule</Text>
            </Button>
        </FooterTab>
     </Footer>

);
    }
  }
));

**Comment by Johncy1997** [comment]
static navigationOptions={
                                tabBarLabel: this.props.data.offerstitle[0].ColumnOne,
                                drawerIcon: ({tintColor }) => (
                                <Image
                                                   source = {require('../assets/contactusicon.png')}
                                                   style={{height:50,width:'100%',resizeMode:'contain'} }/> 
                                                                             ),
        
                                                  } 
      
Please someone tell me how to change the tabarlabel.It throws an error this.protps.data is not an object.
