### ISSUE TITLE
How can I set the Stack Navigator title as an image

### ISSUE THREAD

**Issue by haishangshijie** [react-community/react-navigation#951]
How can I set the Stack Navigator title as an image?

**Comment by prontiol** [comment]
try
```
StackNavigator({
  Screen1: { screen: Screen1 },
  Screen2: { screen: Screen2 }
}, {
  header: {
    title: <Image {..yourPropsHere} />
  }
})
```

**Comment by Reg1nleifr** [comment]
Is the a way to give the Image a value which can be displayed on the back-button?

**Comment by koenpunt** [comment]
@Reg1nleifr you can use `headerBackButtonTitle` to customize the text in the back button

**Comment by Reg1nleifr** [comment]
@koenpunt thanks alot that fixed it.
For anybody else wanting to achieve this effect: I think it's important to note that this is only possible inside the Navigator declaration, not inside the navigationOptions of the given screen!

**Comment by pietro909** [comment]
I'm struggling with the `headerBackTitle` option: I tried to set it to a `string`, a React element, `null`... never works.

Tried both in the `navigationOptions` of the single component and in the `StackNavigation` declaration.

**Comment by xaphod** [comment]
@pietro909 You probably already figured it out, but: one thing that catches me is that on iOS at least, the stuff in the navigator does NOT refresh when I do a reload. I need to recompile/re-run.

**Comment by koenpunt** [comment]
@xaphod I've seen it not working with hot reloading, but on refresh it should always work. Or are you talking about replacing the image?

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!
