### ISSUE TITLE
Customize DrawerItem

### ISSUE THREAD

**Issue by prontiol** [react-community/react-navigation#953]
I want to customize `DrawerItem` but can't figure out the best way to do so.
Redefining `contentComponent` option for DrawerNavigator with my own content component works fine, but I have to fully rewrite (or copy-paste) `DrawerView.Items` component which is undesirable, as I only want to change `DrawerItem` UI a bit (add additional explanatory text line for each item)
Can someone advise?

**Comment by prontiol** [comment]
Okay, I managed to solve this by myself, using
```
navigationOptions: {
    drawer: {
        label: <CustomLabelComponent {...myProps} />
    }
}
```

**Comment by MovingGifts** [comment]
Glad you solved it, can you close the issue now? :)

**Comment by prontiol** [comment]
I guess so.
