### ISSUE TITLE
Toggle `Drawer` programatically

### ISSUE THREAD

**Issue by prontiol** [react-community/react-navigation#954]
I have the following structure
```
StackNavigator({
  Splash: { screen: SplashScreen },
  Landing: { screen: LandingScreen },
  Drawer: {
    screen: DrawerNavigator({
        GetStarted: { screen: GetStartedScreen }
    })
  }
});
```
I made a header button for opening Drawer by `navigate('DrawerOpen')`.
It works fine in GetStarted scene, but does nothing in Landing scene.
How do I open my Drawer from Landing?

**Comment by MovingGifts** [comment]
Check this out, it might help: https://github.com/react-community/react-navigation/issues/957

**Comment by BigPun86** [comment]
+1

**Comment by Andreyco** [comment]
As heads up, I would pick `DrawerNavigator` as top level navigator.

**Comment by prontiol** [comment]
@Andreyco How would you prevent users from opening the drawer by swiping from the left on screens, where you don't wont them to do so?

**Comment by Andreyco** [comment]
@prontiol unfortunately, not aware of solution for this. Will dig into this later, as I will probably need same feature as well

**Comment by grabbou** [comment]
CC: @ericvicenti this is getting more traffic recently

**Comment by felemedeiros** [comment]
@grabbou Any movement on this? This seems like a basic feature.

**Comment by ababba15** [comment]
Well, guys... Opening drawer `with navigate('DrawerOpen')` cause dispatching `"Navigation/NAVIGATE"` action with `routeName:"DrawerOpen"`. Not sure if opening drawer should behave like this. Also this cause issue, that opening the same screen from drawer multiple times opens new screen each time. So, I get my data in `componentWillReceiveProps()` hook, and for some reason it doesn't work when the same screen opens again.

![may-20-2017 15-49-23](https://cloud.githubusercontent.com/assets/13153161/26276042/63707032-3d77-11e7-8082-1ecbc190ff74.gif)

**Comment by nonameolsson** [comment]
I experience the same problem! Any idea how to solve this? @ababba15

**Comment by ababba15** [comment]
@nonameolsson 
Hi mate, I have solved it. Not sure if my way will be okay for you. I found a cool combination of nesting and mixing StackNavigators and DrawerNavigator, so each Drawer item is a separate StackNavigator with it's own screens. Let me know if you would like to get some code.

**Comment by nonameolsson** [comment]
@ababba15 That is actually how my app is built. I appreciate if I can see some code :)

**Comment by ababba15** [comment]
Ok, which part would be more useful for you?

**Comment by nonameolsson** [comment]
How do you reset the stack?
```javascript
onPress(navigation, route) {
  navigation.navigate('DrawerClose')
  const resetAction = NavigationActions.reset({
    index: 1,
    actions: [
      NavigationActions.navigate({ routeName: route.routeName})
    ]
  })
  this.props.navigation.dispatch(resetAction)
}
```

That is what I'm trying to do but it doesn't work :-/

**Comment by ababba15** [comment]
Nope, didn't use `reset`. Wait few minutes please, I'll share a gist.

**Comment by nonameolsson** [comment]
@ababba15 Thanks!

**Comment by ababba15** [comment]
Well, [not the cleanest code in the world](https://gist.github.com/ababba15/5b52c4557dd6d5f861a2dd841ceceb26), but it works as I expect it to work.
Please, pay attention to `screenProps`, which is passed from `navigation.js` into `NavHeader.js`. Seems like it is the saver : )

**Comment by nonameolsson** [comment]
Thanks @ababba15! Will have a look on that code!

**Comment by Agontuk** [comment]
@ababba15, I made a pull request #1817 to fix this issue. Check if it works for you.

**Comment by ababba15** [comment]
@Agontuk thanks, will try to check soon.

**Comment by kelset** [comment]
Pinging OP @prontiol since this issue is quite old and related to an old version of the lib. If no answer I'll close in 7 days.

**Comment by kelset** [comment]
Hi there @prontiol,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue (especially if it's a bug report) please open a new issue that uses the new Issue Template to provide some more details to help us solve it.
