### ISSUE TITLE
Header and tab label missing in the CustomTabs example, how to add it?

### ISSUE THREAD

**Issue by pavlelekic** [react-community/react-navigation#956]
I want to make a secondary level navigation on top, something like 'Status', 'Photo', 'Check In' in the facebook app (https://alty.co/blog/wp-content/uploads/2017/03/Facebook-App.jpg). So I used your CustomTabs navigator from the NavigationPlayground example as a starting point, and then customized it a bit.

The problem is, how do I pass label like 'Check In' to the component where the tab buttons render? Currently it renders route name, which is something in camel case like 'CheckIn', and I don't want camel case I want a nice human readable label. Can you please give me some advice on how to proceed with this? If I set label in the navigationOptions, how do I retrieve it in the CustomTabView component?

Also, I'd like to add Header component, I have the same problem of not being able to read navigationOptions, that I previously set, in the CustomTabView component where I'm supposed to render the header.

Thanks.

**Comment by grabbou** [comment]
Here's how you can access it on master:

```
const CustomTabView = ({
  router,
  screenProps,
  navigation,
}) => {
  const { routes, index } = navigation.state;
  const ActiveScreen = router.getComponentForState(navigation.state);
  
  const routeNav = addNavigationHelpers({
    ...navigation,
    state: routes[index],
  });

  const routeOptions = router.getScreenOptions(routeNav, screenProps || {});
 
  // read whatever you want from here, or pass to `CustomTabBar`
  console.log(routeOptions);

  return (
    <View style={styles.container}>
      <CustomTabBar navigation={navigation} />
      <ActiveScreen navigation={routeNav} />
    </View>
  );
};
```

I took CustomTabs example and modified it.

**Comment by pavlelekic** [comment]
Thank you for taking the time and answering my question. However, this code does not work. I get an error saying that router.getScreenOptions does not exist (is undefined).

**Comment by pavlelekic** [comment]
I figured it out. The way to get tab label name is from:
```
const routeOptions = router.getScreenConfig(routeNav, 'tabBar');
console.log(routeOptions.label);
```

**Comment by sercanov** [comment]
Did anyone found a way to show Navigation Header ? Seems related to #477
