### ISSUE TITLE
Drawer not opening from navigation bar

### ISSUE THREAD

**Issue by vineetkumar198715** [react-community/react-navigation#957]
I'm using DrawerLayout for Side Drawer. I have one header in my App which is being rendered from a separate class. I have an icon in the left which should open the Drawer if I tap on it. But the open/close drawer public methods can't be accessed. How can I call opendrawer method explicitly from other view?

**Comment by MovingGifts** [comment]
`onPress={() => this.props.navigation.navigate('DrawerOpen')}` is how it should be called. If you are already calling it like that from your component and it's not working, you need to define your drawer in your routes file, and then reference the drawer as the first item in your main navigator, like this:

```
Drawer: {
   screen: MyDrawerNavigator // this is your referenced drawer navigator
}
```

**Comment by prontiol** [comment]
@MovingGifts, This did not help.

Here is my config:
```
RootStackNavigator({
  MainDrawer: { screen: MyDrawerNavigator },
  Inner: { screen: MyInnerStackNavigator }
})
```
Calling `this.props.navigation.navigate('DrawerOpen')` from any screen of the `MyInnerStackNavigator` does nothing at all.

**Comment by matthamil** [comment]
I'm having a similar issue. Before I updated React Navigation, I was able to have an icon in my top bar that called `this.navigation.navigate('DrawerOpen')` to open the drawer. After updating to the latest version of React Navigation, this no longer works.

**Comment by BigPun86** [comment]
+1

**Comment by m1ck2** [comment]
// Add the header at the top of the file:
#import <React/RCTLinkingManager.h>

// Add this above the `@end`:
- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url
  sourceApplication:(NSString *)sourceApplication annotation:(id)annotation
{
  return [RCTLinkingManager application:application openURL:url
                      sourceApplication:sourceApplication annotation:annotation];
}You have

**Comment by matthamil** [comment]
@m1ck2 Can you explain this snippet?

**Comment by grabbou** [comment]
Closing in favour of #954

**Comment by cesarbuenrostro-tiempodev** [comment]
Here is the solution!!! https://reactnavigation.org/blog/#drawer-routes-have-been-replaced-with-actions

**Comment by mdavid88** [comment]
That's only a solution if you're on 2.0, right? This issue is happening for me on 1.5.11.
