### ISSUE TITLE
Tabbed Scenes to hide/show tabbar on listview scroll down/up?

### ISSUE THREAD

**Issue by MovingGifts** [react-community/react-navigation#958]
**This is a very common use case:**

When you are on a scene with the bottom `tabBar` shown, as you scroll upwards with your finger, say `300` offset y, the `tabBar` hides for more real estate on the screen, and when you scroll down, again, say `300` offset y, it shows the `tabBar` again.

Using `react-native-router-flux`, I did it like this `Actions.refresh({ hideTabBar: true/false })`

How can this be implemented in `react-navigation`?

**Comment by xiaokekeT** [comment]
this? https://github.com/react-community/react-navigation/issues/480

**Comment by kevinold** [comment]
@ericvicenti 
Thanks for all the hard work in code and coordination with react-navigation!

I agree this would be a welcomed feature.  I've limited experience in this area, but wanted to ask for a bit of direction and/or if this is on the current roadmap for react-navigation?

**Comment by MovingGifts** [comment]
bump

**Comment by dayudodo** [comment]
waiting for answer...

**Comment by cooperka** [comment]
This seems like a great idea! There's no way to do this currently as far as I know, but I'm sure a PR would be welcome.

**Comment by cooperka** [comment]
It actually might be easier to implement this on a per-project basis by toggling `tabBarVisible`. Even in that case, we could add it to the demo app to show it off and make it easier for others to implement.

**Comment by MovingGifts** [comment]
@cooperka How would you toggle the `tabBarVisible` to false when scrolling in a screen with a visible tab bar?

**Comment by cooperka** [comment]
@MovingGifts it would probably look something like this:

```js
static navigationOptions = ({ navigation }) => ({
  tabBarVisible: navigation.state.params.tabBarVisible,
});
```

And to toggle it on scroll:

```js
onScroll() {
  const shouldShowTabBar = /* some logic to determine whether to show it */;
  this.props.navigation.setParams({ tabBarVisible: shouldShowTabBar });
}
```

Here are some relevant docs: https://reactnavigation.org/docs/navigators/tab#Screen-Navigation-Options

**Comment by MovingGifts** [comment]
@cooperka Hmm... Doesn't work for me. Does it work for you?

**Comment by cooperka** [comment]
@MovingGifts it's actually just pseudocode, I haven't implemented it myself. Can you post a link to a working demo app so I can take a look?

**Comment by MovingGifts** [comment]
@cooperka [Here is a demo](https://github.com/MovingGifts/TabbarToggle) that you can clone locally :)

**Comment by cooperka** [comment]
You just needed to set `tabBarVisible` in your router.

If you want to, you can copy/paste the diff below into a text file and apply it to your code using `git apply diff.txt`:

```diff
diff --git a/app/config/router.js b/app/config/router.js
index a62ee297..ab8bff50 100644
--- a/app/config/router.js
+++ b/app/config/router.js
@@ -36,9 +36,15 @@ export const Tabs = TabNavigator({
   },
   NewForm: {
     screen: NewFormStack,
-    navigationOptions: {
-      tabBarLabel: 'New Form',
-      tabBarIcon: ({ tintColor }) => <Icon name="ios-add" size={35} color={tintColor} />,
+    navigationOptions: ({ navigation }) => {
+      console.log('nav state:', navigation.state);
+      const newFormRoute = navigation.state.routes[0];
+
+      return {
+        tabBarLabel: 'New Form',
+        tabBarIcon: ({ tintColor }) => <Icon name="ios-add" size={35} color={tintColor}/>,
+        tabBarVisible: newFormRoute.params && newFormRoute.params.tabBarVisible,
+      }
     },
   }
 });
diff --git a/app/screens/NewForm.js b/app/screens/NewForm.js
index bec8a004..73eb0f32 100644
--- a/app/screens/NewForm.js
+++ b/app/screens/NewForm.js
@@ -36,10 +36,10 @@ class NewForm extends Component {
   onScrollProfileListView = (event) => {
    const scrollOffsetY = event.nativeEvent.contentOffset.y;
    const height = 200;
-   const shouldShowTabBar = scrollOffsetY > height ? true : false;
+   const shouldShowTabBar = scrollOffsetY > height ? false : true;
    const direction = scrollOffsetY > height ? 'down' : 'up';
    console.log('scroll direction ' + direction);
-   console.log(this.props.navigation.state);
+   console.log('setting visible:', shouldShowTabBar);
    this.props.navigation.setParams({ tabBarVisible: shouldShowTabBar });
   }
 ```

**Comment by cooperka** [comment]
As a side-note, please make sure to always add `node_modules`, `ios`, and `android` directories to your `.gitignore` file so they don't bog down the repo :) it took quite a while do download all that code!

**Comment by MovingGifts** [comment]
@cooperka Thank you so much, it is working now. It's also much better than having to declare it as static on the component (and just doing it in the tab router is much cleaner).

It's my first repository, so I apologize for not including the `.gitignore` Since you posted all the relevant code, I removed the bogged down repo.

Thank you again for a clean solution to this issue :)

**Comment by cooperka** [comment]
Happy to help :)

**Comment by im21** [comment]
@MovingGifts / @cooperka  can you please post the working solution?

Thanks :)

**Comment by cooperka** [comment]
@im21, it looks like @MovingGifts deleted their repo 😿 the main thing to do is this:

```js
navigationOptions: ({ navigation }) => {
  const routeParams = navigation.state.params;

  return {
    tabBarLabel: 'Demo',
    tabBarVisible: routeParams && routeParams.tabBarVisible,
  }
}
```

Then anywhere else in the component you can set `tabBarVisible` using

```js
navigation.setParams({ tabBarVisible: false });
```

**Comment by im21** [comment]
@cooperka  thanks for your prompt reply. 
tried the following but couldn't get it working :( 
can you please help :)

**in my Appnavigation>>>**

export const HomeTabs = TabNavigator({
  FirstScreen: {
    screen: FirstScreenStackNavigator,
    navigationOptions: ({ navigation }) => {
      const routeParams = navigation.state.params;
      
      return {
        tabBarLabel: 'HOME',
        tabBarIcon: ({ tintColor }) => <Icon name='file-text-o' size={20} type='font-awesome' color={tintColor} />,
        tabBarVisible: routeParams && routeParams.tabBarVisible,
      }
    }
  }

const FirstScreenStackNavigator = StackNavigator({
  FirstScreen: { screen: HomeScreen }
}, {
  headerMode: 'none'
})

**in My HomeScreen>>** 
class HomeScreen extends Component {
 

    static navigationOptions = ({ navigation }) => ({
        header: null,
        tabBarVisible: false,
    });


  constructor(props){
    super(props)

    this._onScroll = this._onScroll.bind(this)
    this.state = {
      contentOffsetY: 0
    }
  }

_onScroll(event){

    const scrollOffsetY = event.nativeEvent.contentOffset.y;
    const height = 200;

    const shouldShowTabBar = scrollOffsetY > height ? false : true;
    const direction = scrollOffsetY > height ? 'down' : 'up';
    console.log('scroll direction ' + direction);

    console.log('setting visible:', shouldShowTabBar);
    this.props.navigation.setParams({ tabBarVisible: shouldShowTabBar });
    
  }

**Comment by cooperka** [comment]
@im21 every individual scene has its own set of navigation params. It looks like you might be setting `shouldShowTabBar` on `HomeScreen`, then trying to access it on `FirstScreen`, which won't work. Does that make sense?

**Comment by im21** [comment]
thanks for the tip @cooperka 
i've change to the following but it's still not working .. :( 
im still new to react-native 
plz help 

// Create Stack Navigation for the first screen
const HomeScreenStackNavigator = StackNavigator({
  HomeScreen: { screen: HomeScreen }
}, {
  initialRouteName: 'HomeScreen',
  headerMode: 'none'
})

export const HomeTabs = TabNavigator({
  HomeScreen: {
    screen: HomeScreenStackNavigator,
    navigationOptions: ({ navigation }) => {
      const routeParams = navigation.state.params;
      
      return {
        tabBarLabel: 'HOME',
        tabBarIcon: ({ tintColor }) => <Icon name="SortArrows" size={20}  color={tintColor} />,
        tabBarVisible: routeParams && routeParams.tabBarVisible,
      }
    }
  }, {
  initialRouteName: 'HomeScreen',
  tabBarOptions: {
    activeTintColor: NavColors.activeTintColor,
    activeBackgroundColor: NavColors.activeBackgroundColor,
    inactiveTintColor: NavColors.inactiveTintColor,
    inactiveBackgroundColor: NavColors.inactiveBackgroundColor,
    labelStyle: styles.tabTitle,
    style: styles.tabBar,
    tabStyle: styles.tabStyle
  }
})


// In my homescreen class
class HomeScreen extends Component {
 

    static navigationOptions = ({ navigation }) => ({
        header: null,
        tabBarVisible: false,
    });


  constructor(props){
    super(props)
    this._onScroll = this._onScroll.bind(this)
    this.state = {
      contentOffsetY: 0
    }
  }

_onScroll(event){

    const scrollOffsetY = event.nativeEvent.contentOffset.y;
    const height = 200;

    const shouldShowTabBar = scrollOffsetY > height ? false : true;
    const direction = scrollOffsetY > height ? 'down' : 'up';
    console.log('scroll direction ' + direction);

    console.log('setting visible:', shouldShowTabBar);
    this.props.navigation.setParams({ tabBarVisible: shouldShowTabBar });
    
  }

**Comment by sajjanbalar** [comment]
Thank you!

**Comment by Angelk90** [comment]
@cooperka , @im21 , @sajjanbalar : 
You could post the complete solution.
That is, if the downward scroll disappears, if the upward scroll appears.

**Comment by sujitpk-perennial** [comment]
@MovingGifts are you able to scroll tabbar with list scroll? I have same UI like facebook android app.

**Comment by akhilsanker** [comment]
Hi,
Any idea how do do it in navigation 5 with each tab has a stack navigation with in?

**Comment by chirag773** [comment]
> Hi,
> Any idea how do do it in navigation 5 with each tab has a stack navigation with in?

have you found the solutions?

**Comment by lakhwinderdebut** [comment]
@chirag773 

var scroll = 0; // at top

const onScroll = (e: NativeSyntheticEvent<NativeScrollEvent>) => {
    let contentOffsetY = e.nativeEvent.contentOffset.y;
    let diff = contentOffsetY - scroll;
    if (diff < 0) {
      navigation.setOptions({tabBarStyle: {display: 'flex'}});
    } else {
      navigation.setOptions({tabBarStyle: {display: 'none'}});
    }
    scroll = contentOffsetY;
  };

pass this to onScroll of any scrollview component
