### ISSUE TITLE
Cannot reset from nested navigator

### ISSUE THREAD

**Issue by prontiol** [react-community/react-navigation#959]
I have nested navigators like this:
```
Root StackNavigator
  ---> NestedStackNavigator1
  ---> NestedStackNavigator2
...
```
While in a Scene2_1 from `NestedStackNavigator2` i am trying to do
```
const resetAction = NavigationActions.reset({
    index: 0,
    actions: [NavigationActions.navigate({ routeName: 'Scene1_1' })],
});
this.props.navigation.dispatch(resetAction);
```
But it does not work.
It only allows me to reset to one of the `NestedStackNavigator2` scenes. Why so?
If I replace reset code with simple
```
this.props.navigation.navigate('Scene1_1');
```
It works.

**Comment by evollu** [comment]
but `this.props.navigation.navigate('Scene1_1');` will show animation

**Comment by jeffreymendez1993** [comment]
Neither works for me.

**Comment by prontiol** [comment]
I believe that `dispatch` only acts within current navigator, while `navigate` action is somehow propagated to the parent navigators. What we need is just the same `reset` helper method.

**Comment by prontiol** [comment]
Okay, I tried passing drawer navigator down via `screenProps` and use it instead, like this:
```
DrawerNavigator({
  Boot: {
    screen: ({ navigation }: INavigationEnabled ) => <BootNavigator screenProps={{ rootNavigation: navigation }} />,
  }
})
```
I can not use `this.props.screenProps.rootNavigation` but `this.props.navigate('DrawerOpen')` no longer works.

**Comment by mica16** [comment]
+1    Same issue for me.

**Comment by iRoachie** [comment]
@evollu how are you resetting right away?

**Comment by evollu** [comment]
just call `reset` with exact the same state right after `navigate`.

**Comment by iRoachie** [comment]
@evollu I eventually found a better solution https://github.com/react-community/react-navigation/issues/335, by passing down the parent navigator as a screenProp

**Comment by kelset** [comment]
Pinging OP @prontiol since this issue is quite old and related to an old version of the lib. If no answer I'll close in 7 days.

**Comment by kelset** [comment]
Hi there @prontiol,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue (especially if it's a bug report) please open a new issue that uses the new Issue Template to provide some more details to help us solve it.
