### ISSUE TITLE
Modal React-native's component does not show in IOS but not Android

### ISSUE THREAD

**Issue by gungungun93** [react-community/react-navigation#960]
I have no idea why I cannot use it inside StackNavigator.
example like this
```
 <View>
        <Modal
          animationType={'slide'}
          transparent={true}
          visible={this.state.show}
          onRequestClose={() => this.setState({show: false})}>
          <Text>test</Test>
        </Modal>
</View>

```

**Comment by gungungun93** [comment]
somehow, the modal shows when I disable debug-mode. I don't quite understand but I guess, it would work in real devices

**Comment by neilakoh** [comment]
Yes indeed it will work on the actual app  when you build the ipa . . it is just frustrating that all you can do is imagine and expect that it will work until you build it . .
