### ISSUE TITLE
How to access the current navigation state or active screen

### ISSUE THREAD

**Issue by morungos** [react-community/react-navigation#962]
I can't figure an easy way to get the current navigation state from the `Navigator`. This ought to be trivial, I am sure, but it's not clear or friendly, so any help would be wonderful.

There is the `navigation` prop state, yes, but it's (a) packed in an undocumented/unexplained `nav` property I don't want to poke around in, and (b) the navigator versus `navigator` prop state values are different but sufficiently similar to be more than a confusing. State transitions don't help, because sometimes they don't happen, when an app goes to the background and restores directly in a given state. And I don't really want to (or need to) make a deep redux navigation integration. 

This is the situation. I have an incoming alert, above the navigator level, and the UI should only display an alert in certain screens, and when the parameters match. There really doesn't seem to be an easy way, from outside the `Navigator`, of knowing what the current screen is. However, since the incoming alerts are in an event, it's also not possible to know which screen to route it to. 

There are so many corners to this, it feels there must be a very much simpler way, but I can't find it. Any advice or pointers would be very welcome.

**Comment by twvdb** [comment]
+1

**Comment by VincentCATILLON** [comment]
+1

**Comment by jorisdegeringel** [comment]
+1

**Comment by kjunggithub** [comment]
+1

**Comment by RichardLindhout** [comment]
+1

**Comment by Congrammers** [comment]
+1

**Comment by RichardLindhout** [comment]
Connect it to redux is a solution

First in your Root app.

```
const RouterNav = props =>
  <Router
    navigation={addNavigationHelpers({
      dispatch: props.dispatch,
      state: props.nav,
    })}
  />

const mapStateToProps = ({ nav }) => ({ nav })
const RouterWithState = connect(mapStateToProps)(RouterNav)


const App = () =>
  <Provider store={store}>
    <Gradient>
      <StatusBar />
      <RouterWithState />
    </Gradient>
  </Provider>


export default App
```


navReducer.js

```
import Router from '../../components/Router'

const navReducer = (state, action) => {
  const newState = Router.router.getStateForAction(action, state);

  return newState || state;
}

export default navReducer
```




Then connect the nav reducer to your component or yield select (for saga e.g.)
You can now select the nav property from the state and get the current route as follows.
```

  const { nav } = props
  const { routes, index } = nav
  // console.log('OPEN AUTH SCREEN')
  // console.log(nav)
  const currentRoute = routes[index];
  // console.log(currentRoute)
  // console.log(navigateTo)
  // console.log(currentRouteKey)
  // console.log(routeName)
  // console.log(navigateTo)
  // console.log(`${props.navigation.state.routeName}===${routeName}`)


```

**Comment by vinogradov** [comment]
It would be great to have this functionality without the need to connect to Redux (because it seems connecting to Redux brings some other problems)

**Comment by tnguyenblurb** [comment]
+1

**Comment by jigarvyas** [comment]
Here's what worked for me:
```javascript
<Provider store={store}>
    <TabNavigation
        onNavigationStateChange={(prevState, newState) => {
            this._getCurrentRouteName(newState)
        }}
    />
</Provider>

_getCurrentRouteName(navState) {

    if (navState.hasOwnProperty('index')) {
        this._getCurrentRouteName(navState.routes[navState.index])
    } else {
        console.log("Current Route Name:", navState.routeName)
       	// can then save this to the state (I used redux)
        store.dispatch(setCurrentRouteName(navState.routeName))
    }

}
```

Am using:
 "react-native": "0.42.3",
 "react-navigation": "^1.0.0-beta.7",

**Comment by ryanvanderpol** [comment]
+1

**Comment by LearningRaph** [comment]
+1

**Comment by lsroa** [comment]
+1

**Comment by Nickersoft** [comment]
+1

**Comment by beornborn** [comment]
recursive selector to get current route name from redux:

```js
export const getCurrentRoute = (state: Object) => {
  const findCurrentRoute = (navState: Object) => {
    if (navState.index !== undefined) {
      return findCurrentRoute(navState.routes[navState.index])
    }
    return navState.routeName
  }
  return findCurrentRoute(state.nav)
}
```

**Comment by pensierinmusica** [comment]
You can get the current route from `this.props.navigation.state.routeName`.

**Comment by SteffeyDev** [comment]
+1 shouldn't need to use redux to enable something this simple

**Comment by Palisand** [comment]
As @vinogradov mentions, connecting to Redux brings about some inconveniences: ["...when a navigator is given a navigation prop, it relinquishes control of its internal state. That means you are now responsible for persisting its state, handling any deep linking, integrating the back button, etc."](https://reactnavigation.org/docs/guides/redux) Since I don't want navigators to stop using their internal state, but want certain components/screens to be aware of the current route / active screen, I am using a reformated version of @beornborn's recursive selector and doing the following:

``` javascript
const AppNavigator = StackNavigator({ ... })

const getCurrentRoute = (state: NavigationState) => (
  state.index !== undefined ? getCurrentRoute(state.routes[state.index]) : state.routeName
);

const mapDispatchToProps = dispatch => ({
  setRoute: route => dispatch(setRoute(route)),
});

class App extends React.Component {

  props: {
    setRoute: string => void,
  };

  handleNavigationStateChange = (prevState, newState) => {
    this.props.setRoute(getCurrentRoute(newState));
  };

  render() {
    return <AppNavigator onNavigationStateChange={this.handleNavigationStateChange} />
  }
}

const ConnectedApp = connect(null, mapDispatchToProps)(App);

const Root = () => (
  <Provider store={store}>
    <ConnectedApp />
  </Provider>
);

export default Root;
```

Some component that should know of the currently active screen:
``` javascript
const mapStateToProps = state => ({
  route: state.navigation.route,
})

class Foo extends Component {
  props: {
    route: string
  }

  shouldComponentUpdate({route}) {
    if (route !== "Foo") {
      /*
        the screen corresponding to this component has not been activated 
        with the latest route change so there is no need to update it
      */
      return false;
    }
    // the screen corresponding to this component is now active so do something...
  }
}
```

What do you guys think about this approach?

**Comment by Palisand** [comment]
Here's a HOC that should come in handy for anyone who wants to give what I posted a try:
``` javascript
function navigationAware(ScreenComponent, routeName: string) {

  const mapStateToProps = state => ({
    routeName: state.navigation.route,
  });

  class NavigationAware extends Component {
    props: {
      routeName: string
    };

    screenWillFocus = (): boolean => (
      this.props.routeName === routeName
    );

    render() {
      return (
        <ScreenComponent
          {...this.props}
          routeName={this.props.routeName}
          screenWillFocus={this.screenWillFocus}
        />
      );
    }
  }

  return connect(mapStateToProps)(NavigationAware);
}
```
Usage
``` javascript
navigationAware(ScreenComponent, "Screen")
// or if your ScreenComponent is also connected to redux
navigationAware(connect(...)(ScreenComponent), "Screen")
```

**Comment by jedrichards** [comment]
@Palisand 👍 

Just tried your approach and seems to work well. Better than the other more complex ones I've seen in other issues.

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!

**Comment by pensierinmusica** [comment]
Somehow related to #51

**Comment by benevbright** [comment]
Guys, can't you please consider this issue without redux?

**Comment by pensierinmusica** [comment]
@spencercarli does it make sense to label this as `feature-request` instead of closing the issue? It seems to have a lot of +1s

**Comment by dancherb** [comment]
Seems like currently (if using redux), what works for me is:
```
const index = state.nav.routes[0].index
console.log(state.nav.routes[0].routes[index].key)
```

bit of a nightmare

**Comment by pensierinmusica** [comment]
I ended up doing something like this:

```js
function findRouteNameFromNavigatorState ({ routes }) {
  let route = routes[routes.length - 1];
  while (route.index !== undefined) route = route.routes[route.index];
  return route.routeName;
}
```

**Comment by swaroop03** [comment]
I ended up using ```onTransitionEnd/onTransitionStart``` callbacks to get current navigator instance which contains ```scenes``` array.

```
index:1
layout:{height: AnimatedValue, initHeight: 667, initWidth: 375, isMeasured: true, width: AnimatedValue}
navigation:{state: {…}, dispatch: ƒ, goBack: ƒ, navigate: ƒ, setParams: ƒ}
position:AnimatedValue {_children: Array(4), _value: 1, _startingValue: 0, _offset: 0, _animation: null, …}
progress:AnimatedValue {_children: Array(0), _value: 0, _startingValue: 1, _offset: 0, _animation: null, …}
scene:{index: 1, isActive: true, isStale: false, key: "scene_id-1515414096341-2", route: {…}}
scenes: {[
  	{  
     	index:0
		isActive:false
		isStale:false
		key:"scene_Init-id-1515414096341-0"
		route: {
			key:"Init-id-1515414096341-0"
			routeName:"abc"
		}
	},
	{
		index:1
		isActive:true
		isStale:false
		key:"scene_id-1515414096341-2"
		route: {
			key:"id-1515414096341-2"
			params:{...}
			routeName:"xyz"
		}
	}
]}
```

**Comment by seanmorton** [comment]
FYI, I ended up here looking for a way to determine if a screen is currently focused. After poking around, I discovered that a new `isFocused()` helper was added to the `navigation` prop in this merge: https://github.com/react-navigation/react-navigation/pull/3651

**Comment by Palisand** [comment]
@seanmorton `isFocused()` and, by extension, `withNavigationFocus`, might not behave the way you want. See [this comment](https://github.com/react-navigation/react-navigation/pull/3345#issuecomment-383789778) in #3345.

**Comment by GuiCavi** [comment]
For those who still need this,  @beornborn [comment](https://github.com/react-navigation/react-navigation/issues/962#issuecomment-321761053) solves the issue, with one correction (for me at least): as I'm not using redux integration, the return line change from
```js
return findCurrentRoute(state.nav)

// to 

return findCurrentRoute(state)
```

**Comment by silasrm** [comment]
This solve my problem https://www.npmjs.com/package/react-navigation-current-route

**Comment by arnoldbird** [comment]
Use the new Navigation Event Subscribers feature in react-navigation, released in January 2018: 
https://github.com/react-navigation/react-navigation/pull/3345

Redux is not required for this solution.

**Comment by martinchristov** [comment]
@jigarvyas solution worked for me, but I am profoundly indignant that I had to resort to a implementing a reducer + a recursive function to get out something so basic as the current route name!

**Comment by coreform** [comment]
For me, isFocused does not help to determine when a Tab becomes focused.
That is an important event in mobile UX, however react-navigation overlooks
it (unless I've overlooked RN's solution, let me know!). You could say
'isFocused' is a non-event, I could imagine it being useful if
react-navigation were using or implementing its own notion of Fragments
whereby one or more routes may be focussed at the same time - but there
cannot be more than one route focussed at the same time. For lack of a
better solution, I had to implement a NavTracker which determines that
short-windowed lifecycle event, sets a Redux flag momentarily, that flag is
used to kick off, say, a request for the data backing the Tab.

**Comment by kriskate** [comment]
The problem I have to which none of the above helps is that we have a nested DrawerStack inside a NavigationStack, and navigating from the latter to a sub-stack of the Drawer prints out the state.key of the Drawer, not of the Drawer.substack_item.

```
const MainStack = createStackNavigator({
  HomeScreen, // this here calls DrawerNavigation's items, and sets navigation.state.key as DrawerNavigation's key
  DrawerNavigator,
})

const drawerNav = createDrawerNavigator({
  ...otherScreens // these keys will never appear as "selected"
})
```

I've implemented a solution, but I will lock ```react-navigation``` as a potential breaking change will mess with my stuff.

What I'm doing is looking at ```navigation.state.index``` and comparing it to ```navigation.state.routes```, from which I extract ```routeName```, as such:

```
const labels = [...];

const ListItem = ({ label, navigate, selected }) => (
  <Button viewStyle={[styles.item, selected && styles.selectedItem]} 
      onPress={() => !selected && navigate(label)} >
    <Text style={styles.label}>{ label }</Text>
  </Button>
)

myClass {
  _selected = (label) => {
    const { index, routes } = this.props.navigation.state;
    const { routeName } = routes[index];
    return routeName == label;
  }
  render() {
    return labels.map( label => (
       <ListItem key={label} label={label} navigate={navigate} selected={this._selected(label)} />
     ))
  }
}
```

... where I'm using labels as a constant that both generates the actual DrawerStack and renders the ListItem's.

It's a shame that we don't have an defined way of doing this, but hopefully we'll get an implementation for this and I won't have to lock the ```react-navigation``` version

**Comment by Jekiwijaya** [comment]
If you want to know if current Component is on top most or not, there's already an API for that.
https://reactnavigation.org/docs/en/with-navigation-focus.html

**Comment by OmbraDiFenice** [comment]
Maybe my solution can be useful to someone. I made some quick test and it seems to work fine even with nested stacks (tried with just 1 level, but should work with more as well).

I looked for a solution witch didn't involve Redux, as it seems that [it won't be supported anymore](https://reactnavigation.org/docs/en/redux-integration.html) in the near future.

First thing I followed [this guide](https://reactnavigation.org/docs/en/connecting-navigation-prop.html) to be able to access the root stack navigator.

Then I simply added the following function to `NavigationService.js`:
```javascript
function getCurrentRoute() {
	let route = _navigator.state.nav
	while(route.routes) {
		route = route.routes[route.index]
	}
	return route
}
```
and of course added it to the exported ones:
```javascript
export default {
        // ...
	getCurrentRoute,
};
```
So now I'm able to get informations about the current route just by calling `getCurrentRoute()` from any point in code:
```javascript
import NavigationService from './NavigationService';
// ...
let currentRoute = NavigationService.getCurrentRoute();
```
This returns the [state](https://reactnavigation.org/docs/en/navigation-prop.html#state-the-screen-s-current-state-route) of the current displayed route, allowing to access both the `routeName` string and the `params` object.

**Comment by agm1984** [comment]
`withNavigationFocus`` is great, but I need to be able to observe the route by name because I have a BottomNav component that changes the displayed icon based on the active view. (ie: filled-in icon vs. outline icon)

It would be nice to poll the API and see what the active route/stack is so I can compare against it.

**Comment by Theofilos-Chamalis** [comment]
I wanted to retrieve the current screen name so I could show or hide a back button on the header of my App. After some search I found that the solution is quite simple and does not require Redux. Simply accessing `this.props.navigation.state` gives you a hold of the current route's name under  `this.props.navigation.state.routeName` and its key under `this.props.navigation.state.key`. Hope this helps someone in the future

**Comment by arshidkv12** [comment]
I am using as follows 
` let last          = this.props.navigation.state.routes[0].routes.length - 1;
 let curentScreen = this.props.navigation.state.routes[0].routes[last].routeName;
 `

**Comment by mgscreativa** [comment]
In my case I created this function in my the CustomDrawerComponent

```
isFocused = routeName => {
    const { items } = this.props;
    const currentRouteName = items[0].routes[items[0].index].routeName;

    return currentRouteName === routeName;
  };
```

**Comment by petekanev** [comment]
@i1990jain no you can't, unless you are using the default DrawerItem, which is seldom the case!

**Comment by Oscar963** [comment]
thanks @Theofilos-Chamalis  to me, that worked.
`this.props.navigation.state.routes[this.props.navigation.state.index].routeName`

**Comment by duenwaldd1** [comment]
this.props.navigation.state.routeName?

**Comment by vnd-ranga** [comment]
In TabBar You can check is screen is active By

this.props.navigation.isFocused()

**Comment by schumannd** [comment]
A more general solution for nested navigation stacks:
```

    let navIterator = navigator.state.nav;
    while (navIterator.index != null) {
      navIterator = navIterator.routes[navIterator.index];
    }
    if (navIterator.routeName) return navIterator.routeName;
```

**Comment by jacquesdev** [comment]
Thanks @schumannd, that while method works great, I just can't believe it's not a pre-existing built in method for the navigator object, seems like an obvious one to use.

**Comment by ehsunoo** [comment]
if you are using **native-base**:

```
<Button
vertical
active={props.navigation.state.index === 0}
onPress={() => props.navigation.navigate("Reports")}>
</Button>

<Button
vertical
active={props.navigation.state.index === 1}
onPress={() => props.navigation.navigate("Reports")}>
</Button>
.
.
.
```

**Comment by cristianoccazinsp** [comment]
Wondering this myself as well... How is this not a built in?

**Comment by nsdub** [comment]
@OmbraDiFenice 's solution works well (thanks!), but the docs you want to reference to access the root stack navigator are now located [here](https://reactnavigation.org/docs/en/navigating-without-navigation-prop.html).

**Comment by MikaelConecto** [comment]
I did a HOC With a context from the @OmbraDiFenice answer (ty btw)! Hope it will help you with this.

```
import React from 'react'
import {createAppContainer, createStackNavigator} from "react-navigation";
import SignIn from "../SignIn";
import Dashboard from "../Dashboard";

export const NavigatorContext = React.createContext()

class WithNavigatorContext extends React.PureComponent {
  constructor(props) {
    super(props)

    this.state = {
      currentRoute: props.initialRouteName,
    }

    this._nav = React.createRef();
    this.navigator = createStackNavigator({
      Home: {
        screen: SignIn,
        navigationOptions: {
          header: null,
        }
      },
      Dashboard: {
        screen: Dashboard,
        navigationOptions: {
          header: null,
        }
      }
    }, {
      initialRouteName: props.initialRouteName,
    });
    this.container = createAppContainer(this.navigator)

    this.handleNavigationChange = this.handleNavigationChange.bind(this)
    this.getCurrentRoute = this.getCurrentRoute.bind(this)
  }

  handleNavigationChange(prevState, newState, action) {
    console.log('handleNavigationChange', prevState, newState, action)
  }

  getCurrentRoute() {
    let route = this._nav.current.state.nav

    while(route.routes) {
      route = route.routes[route.index]
    }

    return route.routeName
  }

  render() {
    const Navigator = this.container

    return (
      <NavigatorContext.Provider
        value={{
          ...this.state,
        }}
      >
        <Navigator
          ref={this._nav}
          onNavigationStateChange={this.handleNavigationChange}
        />
      </NavigatorContext.Provider>
    )
  }
}

export default WithNavigatorContext
```

**Comment by danghuyminh** [comment]
> 
> 
> thanks @Theofilos-Chamalis to me, that worked.
> `this.props.navigation.state.routes[this.props.navigation.state.index].routeName`

This is the simplest solution to me. This is a navigation plugin, and we have no functions to get the current route :) I can't believe it has been 2 years ago since the question was post, and nothing has changed.

**Comment by varunchandran333** [comment]
> Maybe my solution can be useful to someone. I made some quick test and it seems to work fine even with nested stacks (tried with just 1 level, but should work with more as well).
> 
> I looked for a solution witch didn't involve Redux, as it seems that [it won't be supported anymore](https://reactnavigation.org/docs/en/redux-integration.html) in the near future.
> 
> First thing I followed [this guide](https://reactnavigation.org/docs/en/connecting-navigation-prop.html) to be able to access the root stack navigator.
> 
> Then I simply added the following function to `NavigationService.js`:
> 
> ```js
> function getCurrentRoute() {
> 	let route = _navigator.state.nav
> 	while(route.routes) {
> 		route = route.routes[route.index]
> 	}
> 	return route
> }
> ```
> 
> and of course added it to the exported ones:
> 
> ```js
> export default {
>         // ...
> 	getCurrentRoute,
> };
> ```
> 
> So now I'm able to get informations about the current route just by calling `getCurrentRoute()` from any point in code:
> 
> ```js
> import NavigationService from './NavigationService';
> // ...
> let currentRoute = NavigationService.getCurrentRoute();
> ```
> 
> This returns the [state](https://reactnavigation.org/docs/en/navigation-prop.html#state-the-screen-s-current-state-route) of the current displayed route, allowing to access both the `routeName` string and the `params` object.

What is _navigator in getCurrentRoute() method?

**Comment by schumannd** [comment]
I am not 100% sure but if you look at my example above I believe it is the equivalent of my `navigator` variable which has been set in index.js using `setNavigator` e.g. like so:

```
<RootNav ref={nav => setNavigator(nav)} />

**Comment by OmbraDiFenice** [comment]
Hello @varunchandran333, @schumannd is right - the `_navigator` object is assigned at the top level component using the `setNavigator()` function.

Apparently things have changed since my first post here, now we have the [withNavigation](https://reactnavigation.org/docs/en/with-navigation.html) component and the link I provided actually points to the page explaining how to use that. I didn't try it yet, but I think the principle is the same: initialize the top level navigation (my `_navigator` object) somewhere and use that to traverse the route tree.

Just not to lose track of it, I copy paste here the code from my whole **NavigationService.js** file, which I built following the old guide:

```javascript
import {NavigationActions} from 'react-navigation';

let _navigator;

function setTopLevelNavigator(navigatorRef) {
  _navigator = navigatorRef;
}

function navigate(routeName, params) {
  _navigator.dispatch(
      NavigationActions.navigate({
        routeName,
        params,
      })
  );
}

function getCurrentRoute() {
  let route = _navigator.state.nav;
  while (route.routes) {
    route = route.routes[route.index];
  }
  return route;
}

// add other navigation functions that you need and export them

export default {
  navigate,
  setTopLevelNavigator,
  getCurrentRoute,
};
```

and the usage, in **App.js**:

```javascript
import NavigationService from "./helpers/NavigationService";

//...

export default class App extends React.Component {

    render() {
        return (
            <Provider store={store}>
                <AppContainer
                    ref={(navigatorRef) => {
                        NavigationService.setTopLevelNavigator(navigatorRef);
                    }}
                />
            </Provider>
        );
    }
}
```

**Comment by ScreamZ** [comment]
I was also struggling with navigation state so I wrote a small article to easily get the navigation state : https://medium.com/javascript-in-plain-english/how-to-get-the-current-screen-metadata-in-react-within-react-navigation-b9c18206e9c4

Hope this helps…

**Comment by ahmadsyamim** [comment]
using this instead of   let route = _navigator.state.nav;
```
export function getCurrentRoute() {
  let route = navigationRef.current.getRootState();
  while (route.routes) {
    route = route.routes[route.index];
  }
  return route;
}
```

**Comment by kierien** [comment]
For those using React Navigation 5 and are looking to get the state/name of the current route and/or navigate without the navigation prop, here's what I managed to come up with based off the answers above & the official documentation:  

First create a new module called **RootNavigation** (or whatever you fancy) with the following code: 
```
// RootNavigation.js

import {createRef} from 'react';

export const isMountedRef = createRef();
export const navigationRef = createRef();

export function navigate(name, params) {
  if (isMountedRef.current && navigationRef.current) {
    // Perform navigation if the app has mounted
    navigationRef.current.navigate(name, params);
  } else {
    // You can decide what to do if the app hasn't mounted
    // You can ignore this, or add these actions to a queue you can call later
  }
}

export function getCurrentRoute() {
  let rootState = navigationRef.current.getRootState();
  let route = rootState.routes[rootState.index];

  while (route.state) {
    route = route.state.routes[route.state.index];
  }
  return route;
}
```

Then in **App.js** attach the **navigationRef** ref defined earlier in the **RootNavigation** module. _The useEffect hook here is used to tell **RootNavigation** if the app has mounted._ 

```
// App.js

import React, { useEffect } from "react";
import { NavigationContainer } from "@react-navigation/native";
import { navigationRef, isMountedRef } from "./RootNavigation";

const App = () => {
    useEffect(() => {
        isMountedRef.current = true;

        return () => (isMountedRef.current = false);
    }, []);

    return (
        <NavigationContainer ref={navigationRef}>
            // ...
        </NavigationContainer>
    );
};

export default App;
```

Now, from anywhere in your code you can get your route state/name and/or navigate like this: 

```
import * as RootNavigation from "./RootNavigation";

// get route state
const route = RootNavigation.getCurrentRoute();
// navigate somewhere
const navigate = () => RootNavigation.navigate("Somewhere");
```

Hope this helps someone!

**Comment by kierien** [comment]
For those using React Navigation 5 and are looking to get the state/name of the current route and/or navigate without the navigation prop, here's what I managed to come up with based off the answers above & the official documentation:  

First create a new module called **RootNavigation** (or whatever you fancy) with the following code: 
```javascript
// RootNavigation.js

import {createRef} from 'react';

export const isMountedRef = createRef();
export const navigationRef = createRef();

export function navigate(name, params) {
  if (isMountedRef.current && navigationRef.current) {
    // Perform navigation if the app has mounted
    navigationRef.current.navigate(name, params);
  } else {
    // You can decide what to do if the app hasn't mounted
    // You can ignore this, or add these actions to a queue you can call later
  }
}

export function getCurrentRoute() {
  let rootState = navigationRef.current.getRootState();
  let route = rootState.routes[rootState.index];

  while (route.state) {
    route = route.state.routes[route.state.index];
  }
  return route;
}
```

Then in **App.js** attach the **navigationRef** ref defined earlier in the **RootNavigation** module. _The useEffect hook here is used to tell **RootNavigation** if the app has mounted._ 

```javascript
// App.js

import React, { useEffect } from "react";
import { NavigationContainer } from "@react-navigation/native";
import { navigationRef, isMountedRef } from "./RootNavigation";

const App = () => {
    useEffect(() => {
        isMountedRef.current = true;

        return () => (isMountedRef.current = false);
    }, []);

    return (
        <NavigationContainer ref={navigationRef}>
            // ...
        </NavigationContainer>
    );
};

export default App;
```

Now, from anywhere in your code you can get your route state/name and/or navigate like this: 

```javascript
import * as RootNavigation from "./RootNavigation";

// get route state
const route = RootNavigation.getCurrentRoute();
// navigate somewhere
const navigate = () => RootNavigation.navigate("Somewhere");
```

Hope this helps someone!

**Comment by pacarvalho** [comment]
@kierien Interesting solution. However, it does not appear to work when using `navigation.reset`.

**Comment by azhararmar** [comment]
This doesn't work 

> Here's what worked for me:
> 
> ```js
> <Provider store={store}>
>     <TabNavigation
>         onNavigationStateChange={(prevState, newState) => {
>             this._getCurrentRouteName(newState)
>         }}
>     />
> </Provider>
> 
> _getCurrentRouteName(navState) {
> 
>     if (navState.hasOwnProperty('index')) {
>         this._getCurrentRouteName(navState.routes[navState.index])
>     } else {
>         console.log("Current Route Name:", navState.routeName)
>        	// can then save this to the state (I used redux)
>         store.dispatch(setCurrentRouteName(navState.routeName))
>     }
> 
> }
> ```
> 
> Am using:
> "react-native": "0.42.3",
> "react-navigation": "^1.0.0-beta.7",

For those who are using react navigation 5, I have to do some minor change to get it to work.

```
_getCurrentRouteName(navState) {
	navState = navState?.state ? navState.state : navState;
	if (navState.hasOwnProperty('index')) {
		this._getCurrentRouteName(navState.routes[navState.index]);
	} else {
		const currentRouteName = navState.name;
		console.log(currentRouteName);
	}
}
```

**Comment by Blkc** [comment]
> using this instead of let route = _navigator.state.nav;
> 
> ```
> export function getCurrentRoute() {
>   let route = navigationRef.current.getRootState();
>   while (route.routes) {
>     route = route.routes[route.index];
>   }
>   return route;
> }
> ```

If your routes are encapsulated by a root route, you will need to add an extra line

```
function getCurrentRoute(navigationRef) {
  let route = navigationRef.current.getRootState();
  while (route.routes) {
    route = route.routes[route.index]
  }
  route = route.state?.routes[route.state.index]?.name ?? INITIAL_ROUTE_NAME
  return route
}
```

**Comment by Yeab13** [comment]
@vnd-ranga Your solution works fine . Thank You

**Comment by infinitbility** [comment]
the simplest way to get the current route name from react-navigation.

https://infinitbility.com/how-to-get-the-current-route-in-react-navigation

**Comment by veeramarni** [comment]
> For those who are using react navigation 5, following solution works for me.
> 
> ```
> getActiveRouteName(state) {
>     const route = state.routes[state.index];
>     if (route.state) {
>         return getActiveRouteName(route.state);
>     }
>     return route.name;
> }
> ```
> 
> Which is documented in here. https://reactnavigation.org/docs/screen-tracking/
> 
> Instead of `Analytics.setCurrentScreen` from the documentation, we can use redux to dispatch the current route name.

@azhararmar We are planning to integrate `react-navigation` with `redux`, do you any example for it?
