### ISSUE TITLE
react native 0.43   Unable to compile release

### ISSUE THREAD

**Issue by fangkyi02** [react-community/react-navigation#963]
* What went wrong:
Failed to capture snapshot of input files for task 'bundleReleaseJsAndAssets' property '$1' during up-to-date check.
> Failed to create MD5 hash for file '/Users/lv/Desktop/ReactNative/WYMusic/.buckd/sock'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by satya164** [comment]
This issue is irrelevant to React Navigation.
