### ISSUE TITLE
react-navigation seems dosen't support react-native@0.43?

### ISSUE THREAD

**Issue by jszcl** [react-community/react-navigation#964]
i  got errors about react-navigation when i  upgrade my react-native .   Then I deleted my npm modules. When I do npm install again, it tells me   either react@15.4.2 was not installed or react@16.0.0 was not installed ,witch means   react-navigation require react@15.4.2,but react-native requires react@16.0.0 , wasn't it?

**Comment by pxue** [comment]
This work-around fixed for me. https://github.com/react-community/react-navigation/issues/923#issuecomment-292442911

**Comment by grabbou** [comment]
Master already supports latest React Native and remaining flow issues and dependency warnings were fixed. 

Until new version is released to `npm`, you can pin your dependency to a commit of your choice.
