### ISSUE TITLE
navigationOptions do not work for Composed Components

### ISSUE THREAD

**Issue by joncursi** [react-community/react-navigation#966]
Most of my screens are composed with `recompose`, or wrapped by various other HOCs. When a screen is composed like so:

```jsx
import { compose } from 'redux'; // or import { compose } from 'recompose';
import { connect } from 'react-redux';

const mapDispatchToProps = { ... };

class SomeScreen extends Component {
  static navigationOptions = {
    title: 'Hellooo!',
  };

  render(): { ... }
}

const enhance = compose(
  // other HOCs, such as withState
  connect(null, mapDispatchToProps),
  // other HOCs, such as withHandlers
);

export default enhance(SomeScreen);
```

`navigationOptions` are not respected. They seem to have no effect. However, if I export the raw component via:

```jsx
export default SomeScreen;
```

`navigationOptions` start to kick in. How can I get `react-navigation` to respect the `navigationOptions` on my composed components?

**Comment by joncursi** [comment]
For some odd reason, the `connect` HOC works if used in isolation:

```jsx
export default connect(null, mapDispatchToProps)(SomeScreen);
```

But other HOCs do not work:

```jsx
export default injectIntl(SomeScreen); // nope :( ; injectIntl is from the react-intl package
```

Nor does chaining together HOCs:

```jsx
export default connect(null, mapDispatchToProps)(injectIntl(SomeScreen)); // nope :(
```

**Comment by joncursi** [comment]
Update 2:

This workaround seems to work:

```jsx

class SomeScreen extends Component {
  render() { ... }
}

const enhance = compose(
  connect(null, mapDispatchToProps),
  injectIntl,
);

const EnhancedSomeScreen = enhance(SomeScreen);

EnhancedSomeScreen.navigationOptions = {
  title: 'Helloooo!',
};

export default EnhancedSomeScreen;
```

What this seems to do is set `navigationOptions` on the outer-most HOC, since `react-navigation` is unable to detect / respect `navigationOptions` on the inner components.

Hoping for a cleaner solution though, ideally via `static` on the inner component itself. I have a pet peeve for configuration drifting too far outside of the component desiring the effect.

**Comment by philohelp** [comment]
Thanks for the trick, saved me a lot of time !

```
Login = createContainer(
  props => {
    const userId = Meteor.userId();
    const userSub = Meteor.subscribe("my.user.details", userId);
    return {
      userSubReady: userSub.ready(),
      user: Meteor.user()
    };
  },
  LoginUI
);

const mapStateToProps = state => ({
  isConnected: state.netinfo.isConnected
});

const loginWithRedux = connect(mapStateToProps)(Login);

loginWithRedux.navigationOptions = {
  title: "Hello login with Redux !",
};

export default loginWithRedux;
```

**Comment by joncursi** [comment]
The problem with this workaround is that navigationOptions are being set **statically** on the enhanced component, and we do not have access to the lifecycle hooks of the enhanced component. Therefore, it is impossible to update header options with `setParams` later (See: https://github.com/react-community/react-navigation/issues/145). You only have one chance to set your header options: on mount. After that, you're SOL.

**Comment by satya164** [comment]
> The problem with this workaround is that navigationOptions are being set statically on the enhanced component, and we do not have access to the lifecycle hooks of the enhanced component. Therefore, it is impossible to update header options with setParams later (See: #145). You only have one chance to set your header options: on mount. After that, you're SOL.

What does lifecycles have to do with`setParams`, and why can't you call `setParams` with the above solution?

**Comment by joncursi** [comment]
@satya164 oh wow, you're right. I should have done more testing. Looks like you can set `navigationOptions` on the outer-most HOC:

```jsx
const enhance = compose( ... );

const EnhancedSomeComponent = enhance(SomeComponent);

EnhancedSomeComponent.navigationOptions = {
  header: ({ state }) => ({
    title: state.params ? state.params.title : 'Default Title',
  }),
};
```

... and then update them later from a lifecycle on the inner-most component:

```jsx
class SomeComponent extends Component {
  ...

  someHook() {
    navigation.setParams({
      title: 'general.onboarding.welcome',
    });
  }

  ...
}
```

**Comment by doomsower** [comment]
There is `hoistStatics` helper in recompose.

```js
import { compose, hoistStatics, ... } from 'recompose';

class SomeScreen extends Component {
  static navigationOptions = {
    title: 'Hellooo!',
  };

  render(): { ... }
}

const enhance = compose( ... );

export default hoistStatics(enhance)(SomeScreen);
```

**Comment by joncursi** [comment]
Thanks @doomsower ! Just what I was looking for.

**Comment by jeshio** [comment]
`export default BaseComponent => {
  const { navigationOptions } = BaseComponent;

  const component = props => (
    <Page>
      <BaseComponent {...props} />
    </Page>
  );

  component.navigationOptions = navigationOptions;

  return component;
};`

**Comment by mattslight** [comment]
@joncursi came here looking for this. @doomsower thanks for the hoistStatics tip

Came for 1 solution, got two. Thanks guys.
