### ISSUE TITLE
Nested StackNavigator + DrawerNavigator issue - unable to navigate from Drawer to Stack

### ISSUE THREAD

**Issue by kenma9123** [react-community/react-navigation#967]
Hello there,
thank you for this wonderful react navigator.

I have a simple issue yet I'm not sure how to really resolve it. I've been looking for solutions but I couldn't find anything so I'm here.

I have a root navigator(`StackNavigator`). This navigator contains a `DrawerNavigator` and a few screens.
Here's a simple example
```javascript
let Routes = StackNavigator({
  Settings: { screen: Settings },
  Drawer: {
    screen: DrawerNavigator({
        Stage: { screen: Stage }
    })
  }
});
```

This navigator is connected to redux.
```javascript
class Router extends Component {
  render() {
    return (
      <Routes navigation={addNavigationHelpers({
        dispatch: this.props.dispatch,
        state: this.props.routes
      })} />
    );
  }
}

export default connect(state => ({
  routes: state.routes,
}))(Router);
```

The issue is that inside `Stage` screen from the drawer navigator. I can't seem to navigate to `Settings` using the `this.props.navigation.navigate`. It does nothing, I was expecting for the settings to be pushed but no.

It only works when I put the `Settings` screen inside the DrawerNavigator. But I don't want the `Settings` screen to have a drawer. I would like to push the screen above the DrawerNavigator.

Is this something related to scope? That child screen can't access parent screens or something? Please enlighten me. Thank you

**Comment by lorenzsell** [comment]
@kenma9123 - did you ever figure this issue out?

**Comment by DanGDroid** [comment]
same hear +1

**Comment by kevalbhatt** [comment]
+1

**Comment by kheraprabhat** [comment]
@kenma9123 did you find any solution for this issue?

**Comment by kenma9123** [comment]
I did figure this out, I shifted to https://github.com/wix/react-native-navigation instead :D

**Comment by reddyabhishek** [comment]
+1
