### ISSUE TITLE
Tabnavigator inside stacknavigator

### ISSUE THREAD

**Issue by rendomnet** [react-community/react-navigation#968]
I have this structure

```
Stacknavigator
 screen 1 - Page1
 screen 2 - Page 2
  TabNavigator
   Tab 1
   Tab 2
   Inside Tab 2 there is a button with link to "Page 1"
```
How can I go to Page 1 from inside Screen 3

**Comment by jszcl** [comment]
onPress={()=>{const {navigate}= this.props.navigation;navigate ('screen1')}

**Comment by rendomnet** [comment]
Not working.
Even if I fix your error "this.props.navigation ; <-- .  navigate ('screen1')}"

**Comment by gwitteveen** [comment]
Not sure if this the proper way of doing things, but its working for me. You can use Navigator Props [https://reactnavigation.org/docs/navigators/tab](url). (Scroll to the end)

Bit of pseudo code, but you'll get the idea:
```javascript
//Page 2
const Page2 = ({ navigation }) => {
    navigateToPage1 = () =>{
        navigation.navigate('Page1')
    }
    return(
        <TabNavigator screenProps={ navigateToPage1 } />
    )
}

//Tab 2
const Tab2 = ({ screenProps:navigateToPage1 }) => {
    return(
        <Button onPress={() => navigateToPage1} />
    )
}
```

**Comment by ericvicenti** [comment]
Actually I think this may be a real bug, which we are tracking in #983

**Comment by gwitteveen** [comment]
But the bug only arises when the TabNavigator is a route in the StackNavigator, like in:

Stacknavigator
> screen 1 - Page1
> screen 2 -TabNavigator
> >  Tab 1
> >  Tab 2
  
When you place the TabNavigator as a component inside page2 as suggested in the original example you wouldn't expect the TabNavigator to be 'aware' of the routes inside the StackNavigator, or would you?

**Comment by gwitteveen** [comment]
You're right. I misunderstood the example. I assumed the TabNavigator was placed as a component inside page2

**Comment by manjeets12** [comment]
@ericvicenti  Is this fixed ?

**Comment by EdoFoco** [comment]
Hi @ericvicenti,

Is this fixed now? Still can't get it working.

Thanks

**Comment by mqstack** [comment]
Got the same problem.
Is it fixed?

**Comment by RonnieRen** [comment]
you might need to use the navigation of stackNavigator to navigate to page 1,  this.props.navigation is the navigation of TabNavigator's

**Comment by nhohb07** [comment]
I got same problem, how to resolve it?

**Comment by lionel95200x** [comment]
Have you found a solution ? i got same problem

**Comment by nhohb07** [comment]
I found solution below:

in Home.js
```
const AppNavigator = StackNavigator({
  Page1: { screen: Page1 },
  Page2: { screen: Page2 },
  TabPage: { screen: ({ navigation }) => <TabPage screenProps={{ rootNavigation: navigation }} />},
});
```

in TabPage.js
```
render() {
  const MainTab = TabNavigator({
      Tab1: {  screen: Tab1 },
      Tab2: {  screen: Tab2 },
  });

  return (
      <MainTab screenProps={{rootNavigation: this.props.screenProps.rootNavigation}} />
  );
```

in Tab1.js
`onPress={() => {this.props.screenProps.rootNavigation.navigate("Page1")}}`

Hope to help you resolve your problem

**Comment by Rebaiahmed** [comment]
@rendomnet it's not working for me ...

**Comment by donmesserli** [comment]
@nhohb07 

I tried this in Tab1.js and I get an error... "Cannot read property 'screenProps' of undefined

In the constructor of the page I log the props and this is what I get...
{"screenProps":{"rootNavigation":{"state":{"routeName":"TabPage","key":"id-1521691556063-0"}}},"navigation":{"state":{"key":"Tab1","routeName":"Tab1"}}}

Am I doing something wrong?

**Comment by brentvatne** [comment]
hi there! if this is still a bug can you create a new issue that reproduces the bug on https://snack.expo.io? thanks!
