### ISSUE TITLE
Reset stack when navigating onto a new route from the drawerNavigator

### ISSUE THREAD

**Issue by jeffreymendez1993** [react-community/react-navigation#973]
Currently when if you navigate onto a sub scene of a nested stack navigator within a drawer stack when you navigate onto a new route from the drawer stack the scene should reset when you navigate back to the previous stack. Like this  drawer routes ['HomeStack','SessionsStack]. Each stack has multiple routes. When you to  navigate('Sessions') from home the route should be at the first index.

**Comment by jeffreymendez1993** [comment]
Added the route onto the stack and reset it seemed to solve the issue closing for now.

**Comment by vendramini** [comment]
@jeffreymendez1993 could u provide some code, please? When do you reset the stack?

Thanks.

**Comment by thomasbaldwin** [comment]
@jeffreymendez1993 having a similar issue, would greatly appreciate if you could post a code snippet :)
