### ISSUE TITLE
CardStack default header options are completely overwritten by component navigationOptions

### ISSUE THREAD

**Issue by rockmacaca** [react-community/react-navigation#974]
Currently I have some default styles being applied to my appbars depending on what screen is showing. However, I have some components specifying custom `left` and `right` components in`navigationOptions.header`. However, as soon as the `header` property is specified, anything specified in the default header options is lost.

Basically I think these options should be merged recursively rather that just a shallow assign. Or at the very least header options should be merged with the default header options before the other properties are merged.

**Comment by rockmacaca** [comment]
Okay, I figured out what is supposed to happen, it just needs some documentation. It appears that every property under `navigationOptions` in a component can also be a function that takes `(navigation, config)` as arguments. `navigation` contains everything needed to render `left` and `right` (since they are actually JSX elements, not components), and for most people `config` can just use in a object spread in the the returned config.

**Comment by grabbou** [comment]
> It appears that every property under navigationOptions in a component can also be a function that takes (navigation, config) as arguments. 

Because of that reason we were not merging that automatically but leaving that up to users.

V8 (about to be released), contains a new options system (flat), that works as expected (no spread). And because it's flat, shallow merge satisfies most use cases.
