### ISSUE TITLE
TabNavigator remount component on screen change

### ISSUE THREAD

**Issue by MicahSteinbrecher** [react-community/react-navigation#976]
I am using the tab navigator. I have: 
`const MainScreenNavigator = TabNavigator({
    Home: { screen: Home },
    New: { screen: NewCase },
});`
Home displays a list of locally stored data. Data is retrieved on component mounting. This screen is mounted when the app loads, and never seems to be remounted. when i navigate from new -> home, the component should ideally remount to check for changes in the source data. insight is much appreciated.

**Comment by zakster12** [comment]
I am interested in the same thing. This way we also can change Status bar color https://github.com/react-community/react-navigation/issues/11. From there: 

> As one example of where this component usage falls down: say I have a tab navigator and I want one tab to have a dark header and light-content status bar. When switching tabs, the status bar should change, but once they are both already mounted, the <StatusBar/> component doesn't cause the style to change. This is why I think we should use navigationOptions to define the status bar

**Comment by MicahSteinbrecher** [comment]
I think the navigation container exposes a method that solves this: `<AppNavigator
    onNavigationStateChange={(prevState, currentState) => {
      updateState()
      }
    }}
  />`
Though I'm not sure what the navigation container is and how to use it, and would appreciate some clarification

**Comment by grabbou** [comment]
I believe #51 is what you are looking for.
