### ISSUE TITLE
StackNavigator with more than one route breaks on Android. 

### ISSUE THREAD

**Issue by JesperLekland** [react-community/react-navigation#977]
If I have this navigation state:  ```{ index: 0, routes: [ { routeName: 'foo', key: 'foo' }, { routeName: 'bar', key: 'bar' }, ]```
The StackNavigator on Android somehow renders the scenes so that the inactive view ('bar') steals all touch events. It works as expected on iOS, i.e both screens are rendered ('bar' offscreen) but 'foo' still get all touch events. 

Current workaround I use is to use a tabNavigator instead but that feels kind of dirty

**Comment by vjeranc** [comment]
Happens to me too. iOS works fine but Android touch events don't work on the displayed screens.

**Comment by vjeranc** [comment]
Quickfix is changing [this](https://github.com/react-community/react-navigation/blob/c37ad8a0a924d13f3897bc72fbda52aac76904b6/src/views/PointerEventsContainer.js#L104-L106) return value to always be `'none'`.

I'm not sure if it breaks gestures but works for my use case without gestures.

**Comment by hjh5696** [comment]
@vjeranc changing return value to be 'none' works!! Thanks. 
I have custom ViewPager component consisting of ScrollView(pageEnabled) in ios and ViewPagerAndroid in android, but the swipe gesture did not work in android.

**Comment by vjeranc** [comment]
This is fixed in current `beta.9` release.

**Comment by vjeranc** [comment]
Seems to not work in `beta.9` on Android. It's been a while since I've played with it and forgot it does not work on Android.

**Comment by JesperLekland** [comment]
Still does not work as expected (beta-9)

**Comment by spencercarli** [comment]
Gonna close this since it hasn't been updated in a while. Make sure to check on beta.11/beta.12 to see if this still exists!

**Comment by dotansimha** [comment]
Tested now with beta 13 and it was fixed :)
