### ISSUE TITLE
close drawer then navigate 

### ISSUE THREAD

**Issue by devjaw** [react-community/react-navigation#978]
i'm using DrawerNavigator(parent)  with StackNavigator(child) , 
when i press back button or using goBack() function in StackNavigator page  to DrawerNavigator page  , the drawer is still open

i tried to use goBack(routeName) but it doesn't work.
can i close the drawer before navigate to another page ?

**Comment by matthamil** [comment]
`this.props.navigation.navigate('DrawerClose')` to close the drawer. Alternatively, `this.props.navigation.navigate('DrawerOpen')` to open it.

**Comment by devjaw** [comment]
hi @matthamil 
i want to do something like this : 
`onpressnav(pageName){
  const { navigate } = this.props.navigation;
  navigate('DrawerClose')
  navigate(pageName);
}`

so when the user click to the navigate button , the drawer will close first then navigate. but this code doesn't work for me. 
actually i tried to use this code when the user click back : 
`goBack({ numberOfPages: 2 })` 
what is expected is to go back to DrawerNavigator page and close the drawer,  but unfortunately it doesn't work for me.

**Comment by MovingGifts** [comment]
The second `navigate(pageName)` I believe has to be inside a setTimeout function, because I don't think it can run both at the same time.

**Comment by matthamil** [comment]
@MovingGifts is right. You'll need to wait for the navigation to complete before you can call `navigation.navigate('PATH')` again.

**Comment by devjaw** [comment]
thanks guys 
it works fine with setTimeout function : 
`setTimeout(function(){
    navigate(pageName);
  }, 500);
  navigate('DrawerClose')`

**Comment by AlexanderPPetrov** [comment]
After doing some testing I've found that it is a good idea just to use delay of **0** seconds as it will move the navigate(pageName) at the end of the callstack

**Comment by davigmacode** [comment]
```
props.navigation.navigate('DrawerClose')
requestAnimationFrame(() => props.navigation.navigate(pageName'))
```

**Comment by rahmanazhar** [comment]
@davigmacode this works well 

```
    this.props.navigation.navigate('DrawerClose')
    requestAnimationFrame(() => this.props.navigation.navigate('pagename'))   
```

**Comment by xaamin** [comment]
See this [example](https://github.com/xaamin/react-native-drawer-navigation). After research through the source code this seems to work.

Relevant files

./src/drawer/*

getStateForAction overrided in App.js
