### ISSUE TITLE
Change color of HeaderBackButton

### ISSUE THREAD

**Issue by Ehesp** [react-community/react-navigation#98]
HeaderBackButton requires the `assets/back-icon.png` file, which on Android is a black back arrow.
Is it possible to change the color of this?

I noticed there is a tintColor prop, but on the `Header.js` file it only has the following:

```
      return (
        <HeaderBackButton
          onPress={props.onNavigateBack}
        />
      );
```

**Comment by satya164** [comment]
Duplicate of #36

**Comment by Ehesp** [comment]
Ah sorry :)
