### ISSUE TITLE
How to set header above tabbar in Android?

### ISSUE THREAD

**Issue by agarciaguillo** [react-community/react-navigation#981]
At the documentation (https://reactnavigation.org/docs/intro/nesting) we can see that the title of the page is above the tabnavigator in Android:

![captura](https://cloud.githubusercontent.com/assets/16135348/24858499/e2c4bb5e-1dec-11e7-8ce1-531f47fd2749.PNG)

But in my case, the title of the page is located below. Is it possible in android to place the header with the title above the tabbar?

Thanks!

**Comment by AdamChrist** [comment]
```javascript 
const MainScreenNavigator = TabNavigator({
  Recent: { screen: RecentChatsScreen },
  All: { screen: AllContactsScreen },
},{
  ...TabNavigator.Presets.iOSBottomTabs
});
```
