### ISSUE TITLE
Race condition in the way SET_PARAMS dispatch is handled

### ISSUE THREAD

**Issue by amodm** [react-community/react-navigation#986]
There's a race condition in SET_PARAMS dispatch handling, which manifests whenever SET_PARAMS is called on different route keys in quick succession, e.g. if this.props.navigation.setParams() is called during componentWillMount() of each screen in a TabNavigator

This happens because currently SET_PARAMS dispatch calls setState({ nav }) for each call. When a lot of SET_PARAMS calls are received in quick succession, because of the async nature of setState(), the effect is that of only some of the setState() actually happening. For a test with 4 tabs, only the first and last saw the corresponding state change done.

**Comment by johnnylc** [comment]
+1. In my case, only 2 tabs with setParams() in componentWillMount() will casuse this.

**Comment by amodm** [comment]
@johnnylc I'd submitted a PR #982 to fix this, but @ericvicenti rightly mentioned that it's a hack and we should look at solving it differently.

Temporarily, you can reference the following to fix the issue: https://github.com/udaan-com/react-navigation/commit/f7c6ccc80fb3d14d5b28231cdc6ad2272381b06e

**Comment by amodm** [comment]
@ericvicenti if you have developed thoughts on how to fix the issue properly, please share. I can take a shot at the implementation than wait for it.

**Comment by spencercarli** [comment]
Hi! Since this issue has been quiet for a while I'm going to go ahead and close it. If the issue persists in the latest version of React Navigation please re-open!
