### ISSUE TITLE
Unable to resolve ReactComponentWithPureRenderMixin /src/views/Header.js

### ISSUE THREAD

**Issue by timtawan** [react-community/react-navigation#989]
The development server returned response error code: 500

URL: http://10.0.2.2:8081/index.android.bundle?
<img width="299" alt="screen shot 2017-04-11 at 12 51 39" src="https://cloud.githubusercontent.com/assets/10970130/24890933/fc21c88e-1eb5-11e7-91e1-09f43ead4191.png">
platform=android&dev=true&hot=false&minify=false

Body:
{"from":"/Users/timtawan/ReactNative/TreasureagogoProject/node_modules/react-navigation/src/views/Header.js","to":"react/lib/ReactComponentWithPureRenderMixin","message":"Unable to resolve module `react/lib/ReactComponentWithPureRenderMixin` from `/Users/timtawan/ReactNative/TreasureagogoProject/node_modules/react-navigation/src/views/Header.js`: Module does not exist in the module map or in these directories:\n  /Users/timtawan/ReactNative/TreasureagogoProject/node_modules/react/lib\n\nThis might be related to https://github.com/facebook/react-native/issues/4968\nTo resolve try the following:\n  1. Clear watchman watches: `watchman watch-del-all`.\n  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.\n  3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start --reset-cache`.","name":"UnableToResolveError","type":"UnableToResolveError","errors":[{}]}
onResponse
    DevServerHelper.java:339
execute
    RealCall.java:126
run
    NamedRunnable.java:32
runWorker
    ThreadPoolExecutor.java:1112
run
    ThreadPoolExecutor.java:587
run
    Thread.java:841

**Comment by harshq** [comment]
Duplicate #923
