### ISSUE TITLE
TabNavigation: Scoll to Top Functionality

### ISSUE THREAD

**Issue by joncursi** [react-community/react-navigation#991]
On a lot of mobile apps, if you are on your News Feed tab and scroll down a bit, tapping on the News Feed tab again will scroll the ScrollView to the top. Similar to the effect of pressing on the status bar (at least in iOS).

How might one implement this with TabNavigator?

**Comment by ericvicenti** [comment]
I'd be in support of a `GoToTop` action for this. The active tab would fire that action instead of the navigate action. I think the route key should also be included in the action.

The first tap would cause the tab to "pop-to-top" within it, and the second tap could cause the scroll-up

**Comment by joncursi** [comment]
@ericvicenti yep, that's exactly what I'm looking for.

**Comment by max-mykhailenko** [comment]
@ericvicenti when you plan to add this? How we can do that in current beta version?

**Comment by grabbou** [comment]
Closing in favour of #314

**Comment by svbasi** [comment]
my additional suggestion: 

user also can be in second stack in the tab. if he/she clicks the same-tab (where he is) then it should also go to initial stack in the tabe.

**Comment by ericwrobinson** [comment]
> On a lot of mobile apps, if you are on your News Feed tab and scroll down a bit, tapping on the News Feed tab again will scroll the ScrollView to the top. Similar to the effect of pressing on the status bar (at least in iOS).
> 
> How might one implement this with TabNavigator?

I still feel like there is no clear documentation on how to do this. I'm trying to figure out a way to have my 'Header Title' have the same scroll to top functionality as tabBarOnPress (i.e. the instagram logo) and the tap on the status bar. Does anyone possibly have any examples they might be able to share?

**Comment by brentvatne** [comment]
this happens automatically when you tap status bar, you don't have to add any code, it's built into the os. to make it work with tab navigators you need to use these things: https://reactnavigation.org/docs/en/scrollables.html. 

on tab navigator this is implemented by calling `navigation.emit('refocus')` (https://github.com/react-navigation/react-navigation-tabs/blob/542a5cc35e19edbc272e4946d0754ec8c6d1941e/src/utils/createTabNavigator.js#L121-L132)  and the scrollable listens for this event and then scrolls to top (https://github.com/react-navigation/react-navigation-native/blob/39317023080a7e33e9e064a90860d3011bcf56c6/src/createNavigationAwareScrollable.js#L13-L27)

now that i've explained it, it'd be cool if you could open a pr to make this more clear in the docs! related issue: https://github.com/react-navigation/react-navigation.github.io/issues/360

**Comment by ericwrobinson** [comment]
Hi @brentvatne, I've configured the functionality that is intended and created a [PR](https://github.com/react-navigation/react-navigation-stack/pull/86).

Extending the props that are passed to the `headerTitle` will allow us to take action with navigation state in mind. The example of what we're trying to achieve is utilizing the `params` object within the static `navigationOptions` to scroll to top of the page by tapping on the `headerTitle` component specifically. This is separate from utilizing the Status Bar functionality provided by the OS. This also allows us to extend to even further functionality when creating custom navigation headers (specifically touchable and accessible ones), while not disturbing what is currently being rendered by default.

Let me know if there are any questions or concerns.

Thanks
