### ISSUE TITLE
How to update navigation title for parent, when value comes from redux and gets updated in child?

### ISSUE THREAD

**Issue by lww** [react-community/react-navigation#992]
I have a StackNavigator with a  **ParentScreen** and a **ChildScreen**.

Both screens have the same navigation bar with a dynamic value from redux. Implemented like described in [Issue #313](https://github.com/react-community/react-navigation/issues/313)

This works as expected. When I'm in DetailScreen and I update the value for the count variable, it also updates the value in the navigation bar.

Problem is, if I go back to the parent scene, there is still the old value in the navigation bar. It doesn't update to the current value in redux store.

**Child**
![screen shot 2017-04-11 at 15 20 28](https://cloud.githubusercontent.com/assets/1635916/24911196/724641de-1eca-11e7-8a34-448c4b398f4f.png)

**Parent** (when I go back)
![screen shot 2017-04-11 at 15 21 31](https://cloud.githubusercontent.com/assets/1635916/24911239/97c723d8-1eca-11e7-9737-07d2e5851d6f.png)

**ChildScreen**
```
class ChildScreen extends Component {
  static navigationOptions = {
    title: ({ state }) => `Total: ${state.params && state.params.count ? state.params.count : ''}`
  };

  componentWillReceiveProps(nextProps) {
    if (nextProps.count != this.props.count) {
      this.props.navigation.setParams({ count: nextProps.count });
    }
  }

  render() {
    return (
      <View>
        <Button onPress={() => this.props.increment()} title="Increment" />
      </View>
    );
  }
}
```

**ParentScreen**
```
class ParentScreen extends Component {
  static navigationOptions = {
    title: ({ state }) => `Total: ${state.params && state.params.count ? state.params.count : ''}`
  };
}
```
Any advice?
You can also answer on [StackOverflow](http://stackoverflow.com/questions/43347536/react-navigation-how-to-update-navigation-title-for-parent-when-value-comes-fr)

**Comment by hlandao** [comment]
Not the most efficient, but a working  solution:

1. Add `reduxState` to the `navigationHelpers` when wrapping the navigator:
```js
      <Navigator navigation={addNavigationHelpers({
        dispatch: dispatch,
        state: nav,
        reduxState: state
      })} />
```
2. In `navigationOptions`, the navigation object now contains the redux store:
```js
  static navigationOptions = {

    header: (navigation) => {
      console.log('we got the redux state here',navigation.reduxState);
      return ({
        title: navigation.reduxState.appNav.routes[navigation.reduxState.appNav.index].routeName,
      })
    },
  };
```

**Comment by henrikra** [comment]
@hlandao Yeah looks like `reduxState` is removed on rerender :/

**Comment by grabbou** [comment]
Alternatively, title can also be a `React element`. You can create your own component, connect it to Redux store and print the value you want.

**Comment by odairto** [comment]
Guys, I found a solution for my case: I'm using Redux to set the title of my pages.

In each page i had:
dispatch(setTitle("Patrimony"));

And then I changed to:

    useEffect(() => {
        dispatch(setTitle("Patrimonyyyyy"));
    }, [dispatch]);
Reading a litle about it, have the same behavior of: componentDidMount and componentDidUpdate
source: https://reactjs.org/docs/hooks-effect.html

Hope I can help someone with this.
