### ISSUE TITLE
Support non-route/non-touchable items in drawer (subheaders, dividers)

### ISSUE THREAD

**Issue by dantman** [react-community/react-navigation#998]
The drawer currently only permits touchable route items and doesn't have a way to add non-touchable/non-route items. This is true even when building your own `contentComponent`, `DrawerView.Items` uses `navigation.state.routes` directly so you can't use `DrawerView.Items` multiple times with subsets of the routes.

![screenshot_20170411-203334](https://cloud.githubusercontent.com/assets/53399/24940225/de2e49ce-1ef6-11e7-97be-e6eb86641bed.png)

**Comment by ericvicenti** [comment]
True, this is a limitation of `DrawerView.Items`. If you want to add the feature, feel free to send in a pull request.

But we have no current plans to add this feature because you can already customize the `contentComponent`, and what you render inside of there isn't really a concern of the navigation library.

**Comment by cooperka** [comment]
@dantman check out #1317 :smile_cat:

**Comment by dantman** [comment]
@cooperka That looks like too much of a hack.

I already created a fix to allow for `customComponent`s to be implemented with any sort of section headers, dividers, and more. I use it not just for section headers and dividers, but also for that pattern you see in some Google apps where there's a header inside the drawer with a large button with a dropdown arrow that makes a separate set of drawer items for signing in/out.

See #1039

**Comment by cooperka** [comment]
Replied in the PR. Thanks for the feedback and link!
